### ISSUE TITLE
[Firefox Mobile] uBlock fails to load when used with HTTPS Everywhere

### ISSUE THREAD

**Issue by droidery** [gorhill/uBlock#10]
I'm wondering if it's possible to pull in Alex's fix for the Firefox Mobile issue where HTTPS Everywhere and uBlock worked intermittently.

The discussion is at https://github.com/chrisaljoudi/uBlock/issues/1149 and Alex contributed a fix that works.

I originally found the bug with builds from the original repo (gorhill/ublock).

**Comment by gorhill** [comment]
I need to find out if and how I can pull specific commit from another branch, in order to keep contributions properly sourced.

**Comment by hotdogman** [comment]
`git cherry-pick`?

**Comment by gorhill** [comment]
Yes, that doesn't look so simple. There are only a few added lines in the commit to fix #1149, however from git point-of-view, it needs the same reference point in both fork -- or something like that -- looks like something way past my nasic git skills.

**Comment by gorhill** [comment]
Given that it was just a few lines, I didn't feel it was worth spending time trying to figure how to use git-cherry-pick.
