### ISSUE TITLE
Blacklist instead of whitelist

### ISSUE THREAD

**Issue by forgedbyte** [gorhill/uBlock#100]
Is there a way I can set ublock to not filter pages by default? I'd rather blacklist pages I want to see no ads on instead of whitelisting pages.

**Comment by my-password-is-password** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except

**Comment by meetshawn** [comment]
Thanks!
