### ISSUE TITLE
http://windowsmatters.com/ gives message "The connection was reset."

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#1002]
I usually get this the first time I go to the site after starting FireFox.  I press 'Try Again' and I get to the site.  It sometimes stays this way for awhile.

Any ideas on this one?  It only started happening in the past 2 weeks or so.

W10 x64 Pro TH2
Firefox Nightly 64 bit
Default filter lists.

**Comment by publicarray** [comment]
hmm. What makes you think this is an issue with uBlock Origin and not the network or server?

**Comment by gorhill** [comment]
<https://support.mozilla.org/en-US/questions/1024256>.

Please next time plug the error message in a search engine.

**Comment by streetwolf** [comment]
Thanks for the suggestion.  I'll file it in my bit bucket.  What a drek kop.
 > .
 >
 > Please next time plug the error message in a search engine.
 >
 > ---
 > Reply to this email directly or view it on GitHub:
 > https://github.com/gorhill/uBlock/issues/1002#issuecomment-161466185
 >

-- 
----
Gary
