### ISSUE TITLE
Interfering with Service Worker

### ISSUE THREAD

**Issue by adactio** [gorhill/uBlock#1003]
uBlock seems to have issues with sites using Service Workers. Regular fetch network requests don't end up resolving.

You can see an example of this on https://adactio.com which using https://adactio.com/serviceworker.js

A browser with uBlock installed gets the /offline page even when the network connection is working just fine.

**Comment by gorhill** [comment]
I opened `https://adactio.com` and the final URL in the address bar was `https://adactio.com/`, the page displays fine.

Please see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). Ensure whatever issue you have is not caused by a 3rd-party filter list, I will reopen when you page the case there is an issue with uBO itself or one of uBO's own filter lists (not a 3rd-party one).

**Comment by gorhill** [comment]
By the way, on Chromium your `serviceworker.js` is pulled from the behind-the-scene context, so if you are blocking network requests in the behind-the-scene, expect issues -- as warned on the wiki.

**Comment by adactio** [comment]
Yeaahhhh ...just visiting the site once isn't going to reproduce the problem. You'd need to go back, click around (with uBlock enabled) and on repeat visits, you'll start getting the issue: URLs that should resolve get redirected to /offline instead.

**Comment by gorhill** [comment]
Just use the logger to find out what is blocked -- bottom line you have to make the case the issue is with uBO, and not with whatever filters or rules you are using.

**Comment by karlcow** [comment]
ok here a sequence. I don't know if it's the interaction of ublock and service workers. Just noticed the issue. Maybe it's all logical.

1. Access https://adactio.com/links/9896 (content is there)
2. click on older https://adactio.com/links/9896 (the offline page is triggered. the content is not there)

I used uBlock Origin 1.3.7b10 in Firefox 44.0a2 (2015-12-03) on Mac OSX 10.11.1 (15B42)

using [httpie](http://httpie.org/) on the CLI 

```
http GET https://adactio.com/links/9896 
```
gives me the full content of the page.

This is a screenshot of the log.

![capture d ecran 2015-12-04 a 09 40 28](https://cloud.githubusercontent.com/assets/505230/11578834/2613ac5e-9a6c-11e5-993e-6c19de1bb226.png)

And this is a screenshot of the offline page which has a CSS (I guess from the cache?)

![capture d ecran 2015-12-04 a 09 49 13](https://cloud.githubusercontent.com/assets/505230/11578866/5dd1fa2e-9a6c-11e5-8321-97d2e0b40be0.png)

The funny thing is that if I do a shift-reload. I get finally the content without CSS (normal), but I do older and go to the next page. Same pattern again until I do a shift reload.

Everything is working fine if I allow adactio.com (obviously). 

hope it helps.
