### ISSUE TITLE
Problem on building uBlock Firefox 

### ISSUE THREAD

**Issue by CyrusSUEN** [gorhill/uBlock#1005]
Tried on Mac OS X 10.10 and Ubuntu 15.04
Here are my steps to build XPI for Firefox:
run ```$ sh tools/make-firefox.sh```
copy ```uBlock/dist/build/uBlock0.chromium/_locales``` to ```uBlock/dist/build/uBlock0.firefox```
run ```$ python tools/make-firefox-meta.py dist/build/uBlock0.firefox/ beta```

Error: 
```
Traceback (most recent call last):
  File "tools/make-firefox-meta.py", line 111, in <module>
    f.write(install_rdf.format(**manifest))
KeyError: u'ec8030f7-c20a-464f-9b0e-13a3a9e97384'
```

Is there a problem with the _locales folder or the second parameter of the python command that is causing the problem? Thanks!

**Comment by gorhill** [comment]
From root of the project: `./tools/make-firefox.sh all`.

**Comment by CyrusSUEN** [comment]
Thanks! It works
