### ISSUE TITLE
image-assets.stackcommerce.com seems to carry ads.

### ISSUE THREAD

**Issue by antdude** [gorhill/uBlock#1007]
Hello.

I don't know if this is the proper place to report missed ad blockages since none of the (thi/3)rd party filter subscriptions seems block http://image-assets.stackcommerce.com/images/2906/medium_2906_PWYWLearntoCode2016_MF.jpg on http://slashdot.org 's home page. It started showing this annoying big image earlier today (12/3/2015) for me. I tried both AdBlock Plus and uBlock Origin too. Maybe stackcommerce.com needs to be blocked? I also posted about this in https://adblockplus.org/forum/viewtopic.php?f=2&t=42846&start=0 as well.

Thank you in advance. :)

**Comment by gorhill** [comment]
<https://forums.lanik.us/viewforum.php?f=62>.
