### ISSUE TITLE
Ad-Defend (uabInject): several new sites for ublock filters

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1008]
tvtoday.de (i.e. http://www.tvtoday.de/programm/standard/)
teccentral.de
serienjunkies.de
wetteronline.at (i.e. http://www.wetteronline.at/wetter)
webfail.com
notebookcheck.net
comunio.de (i.e. http://classic.comunio.de)

**Comment by gorhill** [comment]
Thanks for reporting.
