### ISSUE TITLE
Resources blocked through a redirection URL are not collapsed

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1013]
Repro steps:
- Enable _"Hide placeholders of blocked elements"_ setting.
- Globally block 3rd-party frames using _advanced user_ mode.
- Go to http://gawker.com/watch-the-most-deeply-uncomfortable-moments-of-the-ted-1746198836.
- The embedded Youtube video at the top of the article is properly blocked, but the corresponding DOM element is not collapsed.

The `src` property for the embedded `iframe` is `/ajax/inset/iframe?id=youtube-video-KqpHTFJO4mE&start=0`, which means that the `iframe` appears to be 1st-party.

However there is redirection server-side which causes the effective URL for the `iframe` to be `https://www.youtube.com/embed/KqpHTFJO4mE?wmode=transparent&rel=0&autohide=1&enablejsapi=1&showinfo=0&start=0`, which is properly blocked. 

However the DOM element collapser uses the original `src` attribute to find out whether collapsing must take place, hence it fails to collapse the `iframe` which was blocked using redirected URL.

**Comment by BenjaminProgram** [comment]
@gorhill Another side effect of this would be that you could not allow it if you wished.

**Comment by gorhill** [comment]
> you could not allow it if you wished

I don't understand why not. The logger shows everything, including redirections.

**Comment by gorhill** [comment]
Closing since I can't reproduce on the test case, the frame is properly collapsed.
