### ISSUE TITLE
Liveperson Broken

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1016]
The entry ||liveperson.net^ in MVPS HOSTS blocks sales.liveperson.net which is needed for the support chat function. I was wondering why Skype Support was never online and found out that it was because uBlock Origin blocked it because I subscribed to MVPS HOSTS. sales.liveperson.net is already commented out in MVPS HOSTS but liveperson.net is not.

**Comment by gorhill** [comment]
Please, <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>:

> Issues with 3rd-party filter lists are the responsibility of their respective maintainers.

**Comment by IDKwhattoputhere** [comment]
I already contacted Mike Burgess about it but I guess I will try again. Maybe he'll remove the entry.

**Comment by IDKwhattoputhere** [comment]
He's hasn't written me back yet. I guess he doesn't see it as an issue of his list but an issue of uBlock Origin since it interprets it in a way which breaks the chat. Can you add it to "Unbreak", please? It's pretty problematic because the website tells you customer service is not online instead of throwing an error so one wouldn't think it's because of a blocked script.

**Comment by gorhill** [comment]
Does ...

    @@||sales.liveperson.net^

... works?

**Comment by IDKwhattoputhere** [comment]
I tested it and these two filters do the job:

    @@||sales.liveperson.net^
    @@||adminlogin.liveperson.net^
The first one is for the script which is absolutely needed and the second one is for connecting to a support  agent once you open a chat session. Without the second one it will always tell you you are not currently in a session.

**Comment by gorhill** [comment]
> The first one is for the script

Do you have a more narrow filter for this? What is the exact URL?

More narrow filters would be best. Also, what is the site where these exceptions are needed?

**Comment by IDKwhattoputhere** [comment]
http://www.skype.com/go/contactcs
Try to delete your account for example. They will give you the option for Text Chat Support. The site then loads a script every few seconds which all look like this:

    https://sales.liveperson.net/hc/11111111/?&visitor=11111111111111&msessionkey=1111111111111111111&siteContainer=Secondary1&site=11111111&cmd=mTagInPage&lpCallId=111111111111-111111111111...

The chat window (https://sales.liveperson.net/hc/...) loads a bunch of images, scripts and other stuff from https://sales.liveperson.net/api/ and /hc/ and more and one script from https://adminlogin.liveperson.net/csdr/account/11111111/service/adminArea/baseURI.lpCsds?version=1.1&ccn=LPChatAPINS&lpCallId=1111111111111111111-1111111111&protV=11&lpjson=1&ccn=LPChatAPINS

**Comment by gorhill** [comment]
I reverted the fix -- I should just have stuck to my rules re. those hosts-based 3rd-party filter lists which are not selected by default: use at your own risks.

> Try to delete your account for example

I do not have a Skype account and do not care to open one.

> loads a script every few seconds which all look like this: `https://sales.liveperson.net/hc/11111111/?&visitor=11111111111111&msessionkey=111`

There are two filters in EasyPrivacy related to `liveperson.net`:

    ||liveperson.net/hc/*/?visitor=
    @@||sales.liveperson.net/visitor/addons/deploy2.asp?*&d_id=adcenter&$script

So essentially the "fix" was causing that block filter in EasyPrivacy to no longer work.

So here is the thing: Whatever I put in _Unbreak_ should **never** override filters from the default filter lists, unless it's to unbreak something in the default filter lists. MVPS is an optional filter list, and using it may cause more web page breakage than would be without it -- uBO does not guarantee it won't cause problem, and whatever problem there is, it's for the user to deal with it. I am open to add filters in _Unbreak_ **if and only if** these filters do not cripple filters from default filter lists. So if you figure a much narrower set of filters, I will look into them.

**Comment by IDKwhattoputhere** [comment]
I was hoping there would be an easy fix. But you're right about it not being a default list. Maybe you can add an exception which only applies if you're on liveperson.net since the uBO icon is hidden in the chat popup so you can't disable blocking. The Skype support website I linked is a mess anyways (needs third-party cookies, flash, a bunch of third-party scripts) so might as well not fix it.

**Comment by gorhill** [comment]
Would this work?

    @@||adminlogin.liveperson.net^$first-party

At least this exception would apply _only_ on `liveperson.net`.

**Comment by IDKwhattoputhere** [comment]
The first one would work if the user unblocks sales.liveperson.net which he has to do when the popup opens since uBO "has prevented the following site from loading".

**Comment by gorhill** [comment]
> when the popup opens since uBO "has prevented the following page from loading"

I see, so the second one is best then. I think it is reasonable, since it applies **only** to network requests from the site itself -- this way the popup wouldn't be blocked. Can you try the second one and see if this makes the popup work flawlessly?

**Comment by IDKwhattoputhere** [comment]
The popup works with the second filter.
