### ISSUE TITLE
computerbild.de - inline-script

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1017]
computerbild.de
now has massive ugly ads around the content and on some subsites: http://postimg.org/image/l9xo00o6j/

It seems to be Ad-Defend and filter
||computerbild.de^$inline-script
works for me. But I'm not sure if this is the correct filter.

**Comment by gorhill** [comment]
I can't see the background ad on my side (even with VPN), so I just added `computerbild.de` to the `uabInject` filter.

**Comment by TonyTough** [comment]
Hi,

the uabInject filter does not work, I already tried it before and it's still the same.

If I add ||computerbild.de^$inline-script
to "My Filters" it works.

**Comment by gorhill** [comment]
> the uabInject filter does not work

It does, I tested it before committing the change.

**Comment by TonyTough** [comment]
Hi,

I tested again thourougly and found out the cause:

If I deactivate Anti-Adblock Killer Reek List, it works.
So I guess there is a conflict with that list that has to be fixed by Reek - I will post it there.

Thanks for your work.
