### ISSUE TITLE
[Feature request] Ability to block totally or partially Web Components

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#1018]
Web Components are the future.  See : https://en.m.wikipedia.org/wiki/Web_Components
Yes I know webcomponents are not currently finished to be standardised and the layout engine don't support it. I Just open this issue by advance. 

Thanks.

**Comment by gorhill** [comment]
Please do not open vague, unspecific issues, which can't ever be closed because too unspecific. I don't even know what you have in mind when you say "block totally or partially Web Components". Stick to providing specific cases with reproducible steps.

**Comment by LifeIsStrange** [comment]
Sorry
