### ISSUE TITLE
[non-issue] update for a wiki link 'CSS selector'

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#102]
Would you please update the link inside _About that CSS selector with "www.faceporn.net"_ topic?
It should be:
![https://github.com/chrisaljoudi/uBlock/issues/161](https://github.com/chrisaljoudi/uBlock/issues/161)

I have no write permissions.

**Comment by gorhill** [comment]
Done.

**Comment by gorhill** [comment]
By the way, you do have write permission, the wiki is open for editing by anybody.

**Comment by alejandrolemus** [comment]
The AdBlock Gold Edition link in the [wiki](https://github.com/gorhill/uBlock/wiki/Forks-and-%22forks%22-of-uBlock) gives an "item not found" error.

PS. I don't see an edit button or anything in the wiki page

**Comment by gorhill** [comment]
> PS. I don't see an edit button or anything in the wiki page

My mistake, I missed a checkbox to allow anybody to edit.
