### ISSUE TITLE
Ad-Defend (uabInject): the next sites for ublock filter

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1021]
oberhessische-zeitung.de (http://postimg.org/image/3k6s2iuu9/)
gelnhaeuser-tageblatt.de
giessener-anzeiger.de
usinger-anzeiger.de
kreis-anzeiger.de
lauterbacher-anzeiger.de

**Comment by TonyTough** [comment]
and the next:

wn.de
sommerhaus.de (this one seems to be a different script)

**Comment by gorhill** [comment]
Thanks for reporting, filters added.

**Comment by TonyTough** [comment]
Thanks for adding.

Here I have a last one for today:
abendzeitung-muenchen.de (http://postimg.org/image/wtp7tvzfx/)

**Comment by TonyTough** [comment]
And still 2 more:
hofheimer-zeitung.de
hochheimer-zeitung.de

**Comment by TonyTough** [comment]
and (window.tisoomi):
brieffreunde.de
moviejones.de

**Comment by gorhill** [comment]
Thanks for reporting, all added. I could not verify 1st-hand `brieffreunde.de` because they forbid access to the site when I use a vpn, but I added anyway since `window.tisoomi` is in the source code.

**Comment by gorhill** [comment]
`spielesite.com` can be blocked using traditional filters:

    ||mc.spielesite.com/image$image,first-party
    spielesite.com##iframe[height="90"][width="728"]
    spielesite.com##iframe[height="600"][width="160"]

This should be reported to EasyList Germany.

**Comment by TonyTough** [comment]
OK, thanks
spielesite.com posted to Easylist Germany Forum.
