### ISSUE TITLE
1.4.0rc0 chrome download installs 1.3.7

### ISSUE THREAD

**Issue by tacosuzy** [gorhill/uBlock#1026]
I have tried to install the 1.4.0 version twice with instructions but only manage to install 1.3.7.

**Comment by SW1FT** [comment]
I think he forgot to update the version number in the package, on Firefox it's also displaying 1.3.7.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
