### ISSUE TITLE
Hard Mode appears to block filter list updates

### ISSUE THREAD

**Issue by josejuan05** [gorhill/uBlock#1027]
It appears that "Hard Mode" blocking (`* * 3p{,-frames,-scripts} block`) prevents uBlock itself from updating filter lists in Chrome. For example, this is what I see in the the uBlock network request logger when I press the "Update Now" button in the 3rd-party filters tab.
![screenshot from 2015-12-07 17 05 14](https://cloud.githubusercontent.com/assets/1211288/11643083/4963f63a-9d07-11e5-93b2-311f71e1c3ab.png)
And this is what appears in the Chrome Developer Tools tab:
![screenshot from 2015-12-07 17 12 52](https://cloud.githubusercontent.com/assets/1211288/11643084/4978e446-9d07-11e5-961e-185e17a0c3ed.png)

This is referred to rather obliquely in the [Behind The Scenes](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests) wiki page:
> Remember that if you block indiscriminately, you could cripple the ability of your browser to update parts of itself or update extensions as well as the ability of extensions to work properly. This is why this is an advanced user feature.

But it would be good to make it more explicit, since it is so specifically self-defeating and counterintuitive. Another useful option might be to create a checkbox in the "3rd-party Filters" tab to automatically whitelist the filter list update URLs.

**Comment by gorhill** [comment]
> It appears that "Hard Mode" blocking prevents uBlock itself from updating filter lists in Chrome

Behind-the-scene scope is whitelisted by default, so you removed it from the _Whitelist_.
