### ISSUE TITLE
v1.4 New popunder

### ISSUE THREAD

**Issue by LoreJon** [gorhill/uBlock#1028]
Just installed v1.4 in FF 42.

Nice work. Thanks.

Regarding the new popunder in xHamster.com (#995):
The closed tab is added to the recently-closed-tabs list, and the new tab doesn't contain the closed tab's back/forward pages.

**Comment by gorhill** [comment]
> the new tab doesn't contain the closed tab's back/forward pages

There is nothing I can do for this.

**Comment by LoreJon** [comment]
Is the new popunder method more efficient than the old way with "||eu-st.xhcdn.com/js/p.js?*"?

Thanks.

**Comment by gorhill** [comment]
If the popunder can be prevented at the source, it's always better, so if `||eu-st.xhcdn.com/js/p.js?*` prevents the popunder, yes, it's better.

**Comment by LoreJon** [comment]
So should I leave the ||eu-st.xhcdn.com/js/p.js?* filter for this specific site?
If true, what's the advantage of the new popunder feature?

I highly appreciate your; just asking in order to understand it better.

Thanks.

**Comment by gorhill** [comment]
> If true, what's the advantage of the new popunder feature?

Popunders affect more than just xhamster.com. So now there is a tool to deal with them. There is an [open issue](https://issues.adblockplus.org/ticket/2095) on Adblock Plus about this.

**Comment by LoreJon** [comment]
Great. You're the best! :+1: 
Thanks.

**Comment by gorhill** [comment]
Thinking more about this, in case of popunder situation, I suppose uBO could close the new tab or window, and instead force the current tab to be loaded with the legitimate URL. I will leave it open as a possible solution to investigate in the future.

**Comment by LoreJon** [comment]
I trust your judgement.

Thanks again for all your work. The number of uBO users on AMO has been steadily growing. :)

**Comment by gorhill** [comment]
This can't be fixed unfortunately, too many bad side effects -- especially when the popunder is loaded with a URL which is strict-blocked by uBO. We will have to accept that the history is lost in popunder cases.

**Comment by LoreJon** [comment]
Thank you. This feature is great.
