### ISSUE TITLE
[WORKAROUND] Add regional list to hide EU cookie law banners

### ISSUE THREAD

**Issue by sergeevabc** [gorhill/uBlock#103]
We already have “EU: [Prebake](http://prebake.eu/) Filter Obtrusive Cookie Notices‎” list.
Yet there’s one more prominent list on the same subject called Shitlist ([github](https://github.com/r4vi/block-the-eu-cookie-shit-list), [txt](https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt)).
Would you care to add it?

**Comment by RandomAcronym** [comment]
Prebake includes rules from shitlist.
search for "block-the-eu-cookie-shit-list" in prebake

**Comment by sergeevabc** [comment]
@RandomAcronym, your obversation is half-truth, devil is in the detail. Shitlist has extended coverage.
E.g. Shitlist blocks all ```###COOKIE_BANNER``` whereas Prebake applies it for two domains only.

**Comment by Mikey1993** [comment]
@sergeevabc I was the one who asked gorhill to add the “EU: Prebake Filter Obtrusive Cookie Notices‎” list at the time, and I don't see the **real** benefit of adding this list to uBlock, as broader rules tend to do more damage and break sites than help.

**Comment by sergeevabc** [comment]
@Mikey1993, Prebake’s weakness is that it filters known sites whereas new sites appear every day in EU and most of them use same scripts to alert user of EU law cookies — Shitlist is a niche list, it full of that very unique names attached to div containers with cookie alert only, so chance of damage is very low. Moreover, if you’re not convinced, just leave this filter unchecked, while rest of us will be happier than yesterday.

**Comment by gorhill** [comment]
Can be imported in custom filter.

**Comment by IDKwhattoputhere** [comment]
Just wanted to mention that Fanboy now maintains such a list too.
https://www.fanboy.co.nz
Not sure if worth adding in uBO but can be imported like stated above.
