### ISSUE TITLE
Please add a new filter - GNU IceCat: Known privacy trackers

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1033]
http://gnuzilla.gnu.org/filters/blacklist.txt is enabled by default in SpyBlock (part of GNUzilla IceCat). This file says "Check http://gnuzilla.gnu.org/filters/retriever/ for the whole source." which contain a file called [custom](http://gnuzilla.gnu.org/filters/retriever/custom) with the Title: Block all well known privacy trackers.

Can you please add this filter to uBO's 3rd-party filters?

It should be named something like:
* GNU IceCat: Known privacy trackers
* IceCat: Custom privacy trackers

**Comment by gorhill** [comment]
It causes to much breakage -- it's why I removed it in the past. If someone wants it, it can be subscribed too [from the wiki](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web).

**Comment by flyingzebras** [comment]
Very nice @gorhill!

**Comment by flyingzebras** [comment]
@gorhill Can you please upload http://gnuzilla.gnu.org/filters/retriever/custom to https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web#external-filter-lists-of-interest

It contains the custom filters that is used in http://gnuzilla.gnu.org/filters/blacklist.txt.

I do not want to subscribe to http://gnuzilla.gnu.org/filters/blacklist.txt as it includes EasyList that already is enabled by uBO by default.

**Comment by harshanvn** [comment]
> I do not want to subscribe to http://gnuzilla.gnu.org/filters/blacklist.txt as it includes EasyList that already is enabled by uBO by default.

Even if you subscribe, you will be fine. Duplicates will be discarded!!

**Comment by flyingzebras** [comment]
@harshanvn Thanks.
