### ISSUE TITLE
[Seamonkey] Filter list is empty after browser restart

### ISSUE THREAD

**Issue by figvam** [gorhill/uBlock#1034]
I experienced issue #948 in Seamonkey/Linux too, but after updating to 1.3.6, there is a new twist: if I exit the browser and start again, the filter list is empty like in #948: http://i.imgur.com/iudHGm5.png
If I reset the settings to the defaults, the filter list is populated again and everything works until the browser shutdown.

There is "vAPI.cloud is undefined" error in the console when selecting the empty filters tab:
![scr_2015-12-03_14-29-12](https://cloud.githubusercontent.com/assets/316709/11678859/aaf90ac4-9e5c-11e5-882c-b94001b63e72.png)

**Comment by figvam** [comment]
New profile doesn't have this problem so it's something in my profile.

**Comment by gorhill** [comment]
> There is "vAPI.cloud is undefined" error in the console

Were there other errors on the console when uBO started? The error above suggest something happens at start time causing uBO to fail to initialize.

**Comment by figvam** [comment]
Yes, apparently the console log got overwritten, it's only 250 lines.
Here is the screenshot right after the startup.
![scr_2015-12-10_10-24-54](https://cloud.githubusercontent.com/assets/316709/11709416/a3ce3f0e-9f28-11e5-901c-66bf2860efb8.png)

**Comment by gorhill** [comment]
That screenshot show not only uBO is having issue, you have another addon throwing exception in there. Please do not truncate line numbers, it's also key information -- now I can't tell where in the source code there are exceptions being thrown. Also, launch the browser with only uBO, disable all other extensions.

**Comment by figvam** [comment]
Sorry about the line length. Here is the updated log. Took me a while to capture it, the default 250 lines console log is overflowing too quickly.
![scr_2015-12-11_21-25-21](https://cloud.githubusercontent.com/assets/316709/11751934/d4aa937c-a04d-11e5-86f5-a987c32b2261.png)

**Comment by gorhill** [comment]
Can you try with latest build dev? It's on dev channel in AMO: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>.

**Comment by Veyrdite** [comment]
I've had this problem in seamonkey for a while now.  I've just installed 1.40rc4 and it seems to be fixed, but I will see if it pops up again.

More than just the filter lists are lost: settings such as "I am an advanced user" also reset to default.

**Comment by figvam** [comment]
1.4.0rc4 fixed the issue for me. By the way, the "download anyway" link on the dev channel page leads to 1.2.2b3.

**Comment by gorhill** [comment]
> the "download anyway" link on the dev channel page leads to 1.2.2b3

My bad, I should have posted this link for SeaMonkey: <https://addons.mozilla.org/en-US/seamonkey/addon/ublock-origin/versions/beta>.

**Comment by gorhill** [comment]
Possibly fixed by #1004.

**Comment by Veyrdite** [comment]
Fixed for me too.  Thanks :)
