### ISSUE TITLE
uBlock getting detected as "Adblock" by chrome:// URI trickery?

### ISSUE THREAD

**Issue by moddingg33k** [gorhill/uBlock#1035]
Check out yourself: https://thehackerblog.com/addon_scanner/index.html

Read further here: https://thehackerblog.com/dirty-browser-enumeration-tricks-using-chrome-and-about-to-detect-firefox-plugins/index.html

Quote:
>To put it short, if the addon has a line like the following in it’s “chrome.manifest” file:
>
>**content packagename chrome/path/ contentaccessible=yes**
>
>Then the addon’s resources can be included just like any other web resource. Which means if the addon has any style-sheets, images, or JavaScript – it can be enumerated!

Possible solution might be changing:
>**content ublock0 ./**

to:

>**content ublock0 ./ contentaccessible=no**

Weren't able to test and verify this, yet.

**Comment by gorhill** [comment]
The `contentaccessible` parameter is `no` by default, and uBO does not declare it -- so it's implicitly turned off ([source](https://developer.mozilla.org/en/docs/Chrome_Registration#contentaccessible)).

The page does not detect Adblock Plus or uBO, it detects whether someone is using EasyList.
