### ISSUE TITLE
Update list problem

### ISSUE THREAD

**Issue by alain1965** [gorhill/uBlock#1036]
Hello, I have had a problem to update a list for 5 days now ,Malware Domain List, this list still "obsolete" whatever I do (with cloud or without, with less list) but nothing work.

![image](https://cloud.githubusercontent.com/assets/12104299/11688562/acfd9b42-9e8d-11e5-9579-cfaec5bf6ab6.png)

I had the same problem with Badware risk but it's working now.

**Comment by gorhill** [comment]
The whole site is down: http://www.malwaredomainlist.com/.

**Comment by gorhill** [comment]
It's back -- please refrain from opening an issue each time one of the remote servers is down, it's out of uBO's control.

**Comment by alain1965** [comment]
Ok, I know the lists are not your responsability (and I didn't accuse you of it) but when it's during a few days or more it's useless to check it by default if the list isn't sure. Sorry for disturbing, good work on the new release.
