### ISSUE TITLE
[Feature Request] replace dynamic filtering with uMatrix

### ISSUE THREAD

**Issue by 360up** [gorhill/uBlock#1038]
Would you please consider integrating uMatrix in uBlock as a replacement of the dynamic filtering?

The big issue I have running both addons simultaneously (using uMatrix instead of "dynamic" filtering) is that there is no centralized logger. You have to open both loggers to see who is blocking what and rule out manually what one or the other already has blocked.

Since it would still be an advanced feature it would not interfere with the ease of use for the standard user but make life much easier for the power user.

**Comment by vzjrz** [comment]
Yeah a unified logger would be great.

**Comment by gorhill** [comment]
> Would you please consider integrating uMatrix in uBlock as a replacement of the dynamic filtering?

I don't see how this can be done -- and this would anyway push uBO outside the usability realm for a whole lot of users, which is something I do not want to happen.

The more complicated a tool, the smaller the number of users, and in the big picture this means less users protected from invasive 3rd parties. I believe uBO is currently in a sweet spot to allow a greater number users to reduce their exposure to 3rd parties.

**Comment by 360up** [comment]
> I don't see how this can be done (if you think about it beyond the surface)

From the surface it looks like uMatrix and uBO dynamic filtering are very similar both in syntax and implementation. Hence why this idea came up. Apart from finer granulation how is it different?


> this would anyway push uBO outside the usability realm for a whole lot of users
 
But the average user doesn't even activate the dynamic filtering, so it would still be hidden.
Personally I find uMatrix more intuitive since it shows you request type and number. Regarding uBO dynamic filtering I had to consult the manual to find out what the columns as well as "+" and "-" stand for.

**Comment by msva** [comment]
Btw, what is your use-case for uMatrix together with uB⁰?

@@
For me, it is only thing that uMatrix DynFilter UI is much more handy, beauty and useable. But, while I'm, just as you, upset by the fact that uM missing uB features and vice versa (and, knowing there was httpswitchboard, where they were both altogether!), I considered to disable uM and only use uB (and wipe the tears of eye-pain ☹).

// and althouch Chris wrote something about UI-changes in changelogs, before he disappeared (and left non-origin uB orphaned), that uB fork has same uncomfortable dynamic filters panel.
@@

And what is your reasons to have uM beside of uB⁰? ☺
