### ISSUE TITLE
Temporary dynamic filters with 3p-script won't save

### ISSUE THREAD

**Issue by jbutz** [gorhill/uBlock#1039]
When I try and save `* js-agent.newrelic.com 3p-script allow` as a temporary dynamic filter the text box gets cleared and the filter is not saved. If I change it to `* js-agent.newrelic.com * allow` it will save.

**Comment by gorhill** [comment]
As per [wiki doc](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax):

> Note that with type-based rules, the destination hostname is always *, meaning "from anywhere".

The rule you are trying to use is more granular than what uBO supports. For higher granularity, there is uMatrix.

**Comment by jbutz** [comment]
I guess I missed that. Adding an alert that the filter you put in was too complex and not erasing the contents of the textbox would be a nice UX improvement.

**Comment by zeird** [comment]
Is it intended behavior that rules for subdomains are forbidden too? Like this

> *.mozilla.org mozilla.net * noop

I've grouped a lot of my rules to work on all subdomains of sites I visit a lot. Typical usecase is noopping CDNs on all subdomains of specific domains.

Today I discovered that the most part of my rules are gone, because of this I think.

**Comment by gorhill** [comment]
Wildcards are not allowed in rules. Subdomains are always inheriting the rules, unless overriden by a narrower rules. Your rules should be:

    mozilla.org mozilla.net * noop

**Comment by zeird** [comment]
Didn't know that. Thanks!

> Wildcards are not allowed in rules -- nowhere in the doc it says otherwise. Subdomains always inherits rules from a broader scope, unless overriden by a narrower rule.

The latter isn't said in the docs too. At least there's not a word about subdomains in the [Dynamic filtering: rule syntax](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax) wiki page, i.e. the page anyone (or just me) expects to find that kind of info. On that page:

> Source hostname always correspond to the hostname extracted from the URL of the web page in the browser.

I get used to think that subdomain are always included in a `hostname`. For example, just look at the browser's console's output:

![](https://i.imgur.com/BSv3Gjs.png)

So I propose you to add that info about subdomains inheriting to that wiki page.

Thanks again. You're awesome.

**Comment by gorhill** [comment]
Agreed, the doc need more work overall.

**Comment by gorhill** [comment]
Looks like I had updated the documentation on Dec 10, 2015: <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax/_compare/2894605a3bd94365f08338bcd0a64775b2bd02b3...3245c78acc419b49b06806178ccf1b7f5d945987>

Given this and given that now errors in rules are highlighted, I close this issue as fixed.
