### ISSUE TITLE
uBo 1.3.6 (possibly) unstable in Firefox Nightly 45

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1040]
"As of the new Firefox Nightly 45.xxxx addon randomly breaks and I have to disable and re-enable for it to work again for that browser session." - https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/767327/

I do not know if it is easy to reproduce this bug but I suggest that you investigate this @gorhill.

**Comment by gorhill** [comment]
I've installed the latest Nightly 45.0a1 and so far all is fine.

**Comment by gorhill** [comment]
Works fine on FF 46.0a1 as well. Please open an issue **only** if you experience first-hand issues -- which you have _narrowed_ to really be with uBO, not 2nd-hand anecdoctal issues bare of details from somewhere else.
