### ISSUE TITLE
make that button smaller, will you

### ISSUE THREAD

**Issue by 360up** [gorhill/uBlock#1041]
*based on a true story*

Preamble: In 15 years of riding the waves of the www I've never hit the reef so hard

 I cant recall exactly when it happened, but it happened in an instant. It was late that night when I was about to test that new static rule set which I had carefully crafted.
I fired up the logger, following a page refresh to see how my new ruleset is doing in the wild. But what I then had to witness was disaster striking at its fullest: Countless 3rd parties having a big scripting party invoking countless more 3rd (4th?) parties.
I rushed to the mains pulling the cord in order to save whatever there is left to save. But it was all too late, everyone had had its feast. It was only after a cold boot that I realized I must have missclicked that colossal power button to deactivate the addon.

I was browsing the dailymail, I felt humiliated...

Ok, it won't happen again. But for the sake of the dignity of my fellow human beings, just make that button smaller :P

**Comment by publicarray** [comment]
Instead of turning the power off you could've just quit the browser... and than cleared out the cache and cookies. Just my 2 cents.

**Comment by gorhill** [comment]
I do not plan to grand-redesign the UI -- it's baked in -- it makes no sense to redesign stuff because of that one personal incident.
