### ISSUE TITLE
Question about the chrome store update

### ISSUE THREAD

**Issue by Redshift91** [gorhill/uBlock#1042]
I am wondering why is the latest ublock origin is out 3 weeks but the chrome store still doesnt updated to the 1.3.6 version?Thanks.

**Comment by tauxeta** [comment]
https://github.com/gorhill/uBlock/issues/1019

**Comment by Redshift91** [comment]
Thanks Tauxeta the info!

**Comment by gorhill** [comment]
Duplicate of #1019.
