### ISSUE TITLE
Please redirect resources used to display ads for videos on spiegel.de

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#1043]
Check this:
http://www.spiegel.de/video/tiervideo-zoo-affe-lacht-ueber-zaubertrick-video-1633775.html

I think another resource redirection is needed in order to block the ads playing before the video (I hope this is a resource redirection issue as well).

Thanks! You're doing a great job.

**Comment by gorhill** [comment]
The redirect is working on my side.

**Comment by tobbi** [comment]
I can confirm that it works. Thanks!

**Comment by tobbi** [comment]
The same technique is apparently used here:
http://www.golem.de/news/echtzeituebersetzung-skype-translator-wird-regulaer-in-skype-integriert-1510-116643.html
