### ISSUE TITLE
more sites for uBlock filter

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1044]
uabInject:
general-anzeiger-bonn.de

window.tisoomi:
helles-koepfchen.de

**Comment by gorhill** [comment]
The placeholders on `` can be taken care by EasyList Germany:

    www.helles-koepfchen.de###Superbanner1
    www.helles-koepfchen.de##.ad

**Comment by TonyTough** [comment]
OK, thanks.

I will post the the suggested filter to EasyList Germany forum.

**Comment by TonyTough** [comment]
I found 2 more sites:
window.tisoomi:
news.de (http://postimg.org/image/4t0jci6zx/)

and unknown script here:
tiervermittlung.de (http://postimg.org/image/5xunbj2ot/)

**Comment by gorhill** [comment]
Added. For both sites I also added two redirection-based filters, this makes the fix work for Chromium-based browsers too.

**Comment by TonyTough** [comment]
Thanks,

but I guess tiervermittlung.de was forgotten to add to "regular" filter, I still have the ads in Firefox.

**Comment by gorhill** [comment]
Works fine from here for both Chromium and Firefox. Something may not be up to date on your side (uBO or the filter lists).

**Comment by TonyTough** [comment]
I updated the filterlists again and "tiervermittlung.de" is not in the ublock filterlist, only "news.de".

**Comment by gorhill** [comment]
`||tisoomitech.com/*/ad-image.png$image,redirect=2x2-transparent.png` is what blocks the self-defacing ads on `tiervermittlung.de`.

**Comment by gorhill** [comment]
Also, EasyList Germany should use:

    ||tiervermittlung.de/adblocks.php

The site is gathering data about whether the user is using a blocker.

**Comment by TonyTough** [comment]
Hm,

I deactivated all filters with the exception ublock filters and Easylist English and still the same.
Also adding
||tiervermittlung.de/adblocks.php
to "my filters" makes no difference.

Is this possibly again a special thing with German IP address?

These are examples of the ad URLs
On the TOP
http://www.tiervermittlung.de/image/sML9wfX/1449789309813PGIWu/1449789309815seU90.html
(http://postimg.org/image/a73flijm1/)
right side:
http://www.tiervermittlung.de/image/sML9wfX/1449789309810GMzzW/1449789309812uGZxx.html
(http://postimg.org/image/hcqz5bzlt/)
inside right:
http://www.tiervermittlung.de/image/sML9wfX/1449789309816hEdpc/1449789309818bBzJS.html

These links also work if directly used with german IP address

**Comment by gorhill** [comment]
> Is this possibly again a special thing with German IP address?

I was on a VPN server in Germany when I created the filter.

What version of uBO are you using?

**Comment by TonyTough** [comment]
1.36 and Firefox 42 64bit

**Comment by gorhill** [comment]
Notice in my comment above, I mentioned "requires uBO 1.4.0" -- because redirection.

**Comment by TonyTough** [comment]
OK, sorry, then I misunderstood it.
I thought 1.4.0 is only necessary for Chrome

**Comment by gorhill** [comment]
Try `@@||tisoomitech.com/*/ad-image.png$image`, and if it works it should be included in EasyList Germany.

**Comment by TonyTough** [comment]
Yes, that works.
I will post the suggested filter to the Easylist forum.
