### ISSUE TITLE
Origin breaks vimFX in Firefox

### ISSUE THREAD

**Issue by jonpolak** [gorhill/uBlock#1045]
### vimFX, Firefox add-on, breaks when enabling ublock origin in advanced mode 

vimFX is an extension that provides VIM bindings in firefox - similar to the _vimium_ extension for chromium. ublock __does not__ break vimium on chromium but does break vimFX on firefox. I searched "behind the scenes" and don't see any requests that are being blocked (behind-the-scene" is whitelisted as well).

**Comment by gorhill** [comment]
Before I investigate, what exactly is "broken"? Any error messages in the browser console?

**Comment by jonpolak** [comment]
I can't find any changes in the console messages with ublock enabled. It currently is working concurrently with ublock. I apologize for opening this issue without doing more testing.
