### ISSUE TITLE
THANK YOU "ISSUE" (no other possibility except here) :-)

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1048]
Hello @gorhill 

**I know no other way to say a BIG THANK YOU for all your hard work!!**

uBlock and uMatrix is for me and - i am very sure about that - for many other users too - the most important addon/extension for my browser!

So, maybe you will not immediately close this "issue" to receive other postings. OR - of course - if this is not a good idea, you can close it again right now :-)

However, have a good time and new year!

_Alpengreis_

**Comment by lewisje** [comment]
For things like this, a courtesy is to close the issue right away.

**Comment by gorhill** [comment]
> THANK YOU for all your hard work

In general I am assuming gratitude from people who have been long term user of the extension -- so it does not really need to be said; thanks anyways.

**Comment by kousu** [comment]
:+1: :star: :star2: :star: :+1: 

I agree wholeheartedly!

**Comment by Hrxn** [comment]
I certainly agree, as a grateful user, but please keep in mind that creating issues, commenting on issues, etc. sends out mail notifications.

Don't send out mail notifications. Unless you *really* want to send out mail notifications.

It is expressed beautifully by this German word: Funkdisziplin.

Radio discipline, I don't know if it's called that in English..

;-)
