### ISSUE TITLE
Block "Please disable ad block" style ads

### ISSUE THREAD

**Issue by rappo** [gorhill/uBlock#1049]
Some sites detect that you're blocking ads and display ads telling you to disable ad blocking. I feel like these sort of ads should be blocked by default. I couldn't find an existing issue/discussion for this, but I imagine this has come up before.

Example:

http://www.edmunds.com/tesla/model-s/2015/sedan/

![image](https://cloud.githubusercontent.com/assets/2245234/11753454/066d9d90-9ffa-11e5-83cc-6ff9e7606a27.png)
Note: I'm only running uBlock Origin, the modal ad incorrectly calls it ABP.

**Comment by gorhill** [comment]
You need to ask this to the [maintainers of filter lists](https://forums.lanik.us/viewforum.php?f=62) -- each case requires a specific solution.

**Comment by gorhill** [comment]
Try this filter:

    ||d1zatounuylvwg.cloudfront.net/abw.js$script

If it works, please report to EasyList maintainers so that everybody benefit from it.
