### ISSUE TITLE
Stores links

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#105]
gorhill/uBlock and chrisaljoudi/uBlock have the same link to Firefox, Opera and Safari Stores in Readme.md

**Comment by gorhill** [comment]
Fixed README.

**Comment by mikhaelkh** [comment]
You forgot Opera Store link in Chromium section

**Comment by gorhill** [comment]
No I didn't, Opera store version is uBlock Origin, it just doesn't look possible to change the name.

**Comment by mikhaelkh** [comment]
Do you plan to put uBlock Origin on Firefox Add-ons?
