### ISSUE TITLE
WebRTC leaking issue

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#1050]
Hi I am using chrome v47 with ublock v1.3.3.I tried to test webrtc leaking using psiphon vpn app on https://www.browserleaks.com/webrtc webpage and then I saw that I have webrtc leaking issue.How can I solve this issue?

**Comment by gorhill** [comment]
[Prevent WebRTC from leaking local IP address](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address):

> **Caveats** [...] **Chromium-based browsers** [...] If you are using an extension-based VPN, this setting won't prevent your ISP IP address from leaking.
