### ISSUE TITLE
Ublock and  chrome web store

### ISSUE THREAD

**Issue by alain1965** [gorhill/uBlock#1051]
Hello, I have a simple question, ublock origin 1.40 will be avaible in the chrome web store ? Each version were not avaible when it doesn't have interest to chromium. Thank you.

**Comment by gorhill** [comment]
yes

**Comment by alain1965** [comment]
Thank you for your so charming and longuest answer, it's a pleasure.to read.

**Comment by gorhill** [comment]
My answer was short and to the point, yours is sarcastic and accomplishes nothing, except to force me to spend time to try to make you understand why such issue should not be opened in the first place.

Do not open issue to ask such trivial questions, it adds unnecessary burden to the project -- however trivial that burden might look to an outsider.

I will upload to the Chrome store whenever I believe it is beneficial for the users of uBO on the Chrome store to have a new version. If someone can't wait to use the latest version, there is the [_Releases_ section](https://github.com/gorhill/uBlock/releases) of the project.

**Comment by alain1965** [comment]
You know it was only humor and like I'm french I'm arrogant & saccarstic by nature. Sorry if my question seemed so trivial for you, you're a very brilliant programmer, Ublock is really good and honest especially when you look what happen to adblock plus, you work hard but it's not an excuse to be so arrogant (more than me and without humor but like you're not french it's an handicap) and this way to make feel to people they are useless and silly, sorry I can't accept it, You're brilliant with computers but disgusting with peoples you think not at your level with a computer. You have chance than I have enought vocabular in english because write worth things I think on person like you. Only one thing before the end : goes to hell.

**Comment by gorhill** [comment]
> it's not an excuse to be so arrogant

Sorry if I give this impression. It's rather me trying to spend more of my limited free time on working on issues or improving the code, and time spent on trivial issues all adds up to erode free time available working on fixing real issues or improving the code.
