### ISSUE TITLE
New popunder rule for streamcloud.eu

### ISSUE THREAD

**Issue by Goderw** [gorhill/uBlock#1053]
Due to the new feature of blocking popunders in uBo 1.4 I would like to mention that on streamcloud.eu such filtering might be usefull (test URL: http://streamcloud.eu/mt368d0krgj3/Nosferatu__Eine_Symphonie_Des_Grauens.flv.html ).

Click (after 10 seconds of interrupt) on the "start movie player" button... there will be opened up a new (focused) tab with the video in it... in the former tab a new domain (ads) will be opened up as well! 

THANKS!

**Comment by gorhill** [comment]
If ever the site uses other sources for its popunder, report here please, I will add them as they are encountered.

**Comment by IDKwhattoputhere** [comment]
Reporting new source: trimpur.com
Only change after two months. Not bad.

**Comment by IDKwhattoputhere** [comment]
They changed it again: signetter.com
