### ISSUE TITLE
How to filter in-line frame?

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#1054]
URL:http://www.iqiyi.com/a_19rrhb72zt.html
i.g. `<iframe id="sina_anywhere_iframe" style="display: none;">`

**Comment by gorhill** [comment]
You can't,. The document `iframe` can be blocked using a network request filter, or hidden using a cosmetic filter. Specifically what is the issue with the page? I see a bunch of `iframe` with all the same `id`, but they are all `display: none;`.

**Comment by xinggsf** [comment]
rule: iqiyi.com http://www.iqiyi.com/ sub_frame block
This rule is OK？
Thank you!

**Comment by gorhill** [comment]
This will block frames from `http://www.iqiyi.com/`, so this work because there are network requests to block. The example you gave in your opening comment however there is not `src` attribute for the frame, hence no network request to block.
