### ISSUE TITLE
[static filter syntax] separator characters (^) support

### ISSUE THREAD

**Issue by 360up** [gorhill/uBlock#1056]
Am I missing something or is there no support for separator characters by specifying "^" in the filter?
See https://adblockplus.org/en/filters#separators

**Comment by gorhill** [comment]
How did you come to this conclusion? Be detailed.

**Comment by 360up** [comment]
browser version/ublock version: iw-38.4.0esr / uBO-1.4.0
do this: add filter ^stat*
open this exact URL: https://www.youtube.com/
observe this: https:// apis.google.com/_/scs/abc-static/_/js... gets filtered with uBO, but not with ABP
observe this: filter is shown as stat* in the logger (w/o "^")

Can you reproduce this so far?

The issue seems bigger than that, while testing I ran into quite a few irregularities when using short filters w/o wildcards. I'll report back when I found a pattern for that behaviour.

**Comment by gorhill** [comment]
> I'll report back when I found a pattern for that behaviour.

No need to find a pattern, uBO interprets slightly differently the `^` filter -- for efficiency purpose. This occurs only if the `^` is leading or trailing.
