### ISSUE TITLE
Infinity ad blocking at http://www.comnews.ru/node/80095

### ISSUE THREAD

**Issue by qarpin** [gorhill/uBlock#1058]
Opera stable 34.0.2036.25
Ublock 1.3.2
Filters: EasyList, Peter Lowe’s Ad server list, EasyPrivacy, Fanboy’s Enhanced Tracking List‎, RU AdList
URL: http://www.comnews.ru/node/80095
Open link with UBlock turned on and observe endless ad blocking, counter goes to insane values.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/9299607/11766983/22588706-a1a6-11e5-86ae-9174cf584906.png)

This is what is in network requests log:
![image](https://cloud.githubusercontent.com/assets/9299607/11767016/afb3a7e2-a1a7-11e5-9af4-e5ee918e5362.png)

**Comment by gorhill** [comment]
Not a uBO issue, the site is the issue, the site throws a tantrum and firehose network requests non-stop if they are blocked.

This can be worked around using redirect filter, but that is version 1.4.0 only:

    ||comnews.ru/*/468x60.$image,redirect=2x2-transparent.png

Or use an exception filter to prevent the blocking of the resource:

    @@/468x60.$image
