### ISSUE TITLE
Video ads before regular video on several German sites

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1059]
The new new resource redirect on spiegel.de with ublock 1.4.0 works perfect.

I don't know if this can also implemented for several other German newssites:

welt.de
http://www.welt.de/politik/deutschland/article149901583/Vollverschleierung-diskreditiert-Weiblichkeit.html

stern.de
http://www.stern.de/panorama/video/ins-netz-gegangen/sportwelt/treffer-nach-parade---das-unglaubliche-tor-eines-torwarts-6602428.html

on
focus.de
the ads seem to be filtered out by ublock in most cases, but sometimes they are shown.
Maybe they use different video ad servers?
http://www.focus.de/politik/videos/aegaeisches-meer-russischer-zerstoerer-schiesst-um-kollision-mit-tuerkischem-boot-zu-vermeiden_id_5151369.html

**Comment by gorhill** [comment]
For stern.de, added to the redirection filter.

For welt.de and focus.de, I don't see video ads -- be sure you are using the non-Flash player -- their player is not that of stern.de, chip.de, etc.

**Comment by TonyTough** [comment]
With the new filter list, now the videos don't start on stern.de
and also nothing happens when I click on play button.
No problems on spiegel.de.

On welt.de and focus.de: If I deactivate Flash player no videos are played.

I'm using ublock 1.4.0 and Firefox 42 64bit.

**Comment by gorhill** [comment]
> On welt.de and focus.de: If I deactivate Flash player no videos are played

All those sites work fine from here using HTML5 player. You will need to investigate on your side -- be sure to set Flash to "Never activate".

**Comment by TonyTough** [comment]
Oh thanks,

"Never activate" did the trick.
all mentioned sites now working.

**Comment by gorhill** [comment]
Flash has to be considered proprietary blob, so this means a Flash player could force ads on users and no workaround possible -- so we should all stick to non-Flash player as much as possible.

**Comment by TonyTough** [comment]
Hello,

one more german site with video ads using html5 player:
t-online.de
http://www.t-online.de/tv/webclips/lustige-videos/id_76328398/katze-hat-es-faustdick-hinter-den-ohren.html
http://www.t-online.de/tv/webclips/lustige-videos/id_76403998/affe-schmeisst-sich-weg-vor-lachen.html

**Comment by gorhill** [comment]
Added, thanks for reporting.

**Comment by TonyTough** [comment]
one more site with video ads using html5 player:
pz-news.de
http://www.pz-news.de/video-uebersicht_video,-Pforzheim-Baukran-stuerzt-auf-Strasse-_ckvid,80985.html
http://www.pz-news.de/video-uebersicht_video,-Star-Wars-feiert-Premiere-in-Pforzheim-_ckvid,80775.html

**Comment by gorhill** [comment]
I am unable to get any video widget at all on this site, this is also true if using ABP:

![a](https://cloud.githubusercontent.com/assets/585534/11978226/d07795b2-a957-11e5-9f6b-c876bd2b686e.png)

**Comment by TonyTough** [comment]
Depends again on German IP address?
http://s15.postimg.org/wc63osp8r/image.jpg

The video URL is
http://cloud.clipkit.de/1694/video/469716/stream/10518-1-orgv-star-wars-premiere-pforzheim.mp4.sd.mp4

Ad URL
http://cloud.clipkit.de/liverail/1555/27881/461769/lo.mp4

**Comment by gorhill** [comment]
I can get the video to work **only** if I disable both EasyList and Peter Lowe's. Also, I will _try_ to address that sort of case **only** if the official maintainers of EasyList Germany are unable to provide a solution -- that sort of task is very time-intensive, and best addressed by people dedicated to do this, while my task is first to write/maintain code.

**Comment by TonyTough** [comment]
OK, I tested again with different lists activated/deactivated

I havn't encountered this problem because I have always enabled Reek's AAK List in ublock, and so the videos work regardless of EasyList and Peter Lowe's list.

Anyway, I will post it to Easylist Germany forum.

**Comment by IDKwhattoputhere** [comment]
Stern videos now seem to be broken. Disabling `uBlock filters` fixes it.
Example: http://www.stern.de/panorama/video/ins-netz-gegangen/sportwelt/treffer-nach-parade---das-unglaubliche-tor-eines-torwarts-6602428.html
uBlock Origin 1.6.0 with standard configuration and updated filter lists
Chrome 48 with flash enabled
Result: Video simply not playing. Stops right at the preview image.

**Comment by gorhill** [comment]
Does the following filter help?

    ||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices.com/gpt.js,domain=stern.de

**Comment by IDKwhattoputhere** [comment]
No, no change.

**Comment by gorhill** [comment]
I removed `stern.de` from the neutered `hdmain.js` script for now, so that videos play. Also for now, I added procedural cosmetic filters for the delayed ads.

**Comment by okiehsch** [comment]
Does  `stern.de##script:inject(abort-on-property-write.js, exportz)` work on your end?
Playing the videos without ads while not breaking any functionality of the site I.

**Comment by IDKwhattoputhere** [comment]
In case you're asking me: That filter works on my side. The video plays fine.
