### ISSUE TITLE
Login expires for sites when uBlock Origin is enabled.

### ISSUE THREAD

**Issue by electricessence** [gorhill/uBlock#1060]
I've noticed this happening for my Facebook and Youtube.  With uBO enabled it's like the cookie has a short expiration.  How do I modify that for some sites?

**Comment by gorhill** [comment]
uBO does not touch cookies, and it's impossible to provide any answer to your question, as it's impossible to investigate anything without detailed repro steps. I can only provide an attempt at a vague answer: uBO is blocking something which refresh the session cookie maybe. This is a 3rd-party filter list issues, report to filter list maintainers.

**Comment by gorhill** [comment]
Marking as invalid as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
