### ISSUE TITLE
Update subscription url for Liste AR

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#1061]
Hi, 
**uBlock Origin** ![uBlock Origin](http://i.imgur.com/g5T7Xfl.png) use old subscription url for **Liste AR** (القائمة العربية لمانع الشرائط الإعلانية).
* old : `https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt` (*google code shutdown*).
* new url : https://easylist-downloads.adblockplus.org/Liste_AR.txt (since august 24, 2015).
* forum https://forums.lanik.us/viewforum.php?f=98
* changes https://hg.adblockplus.org/listear/shortlog

Thanks for update!
Med

**Comment by gorhill** [comment]
Thanks for the notice, appreciated.
