### ISSUE TITLE
How to make dynamic filters static?

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1063]
Is this correct (taking https://github.com/gorhill/uBlock/issues/1056 into account)?: From https://github.com/chrisaljoudi/uBlock/issues/1395

List of Local uBO dynamic filtering

* all: github.com * * block
* images: github.com * image block
* 3rd-party: github.com * 3p block
* inline scripts: github.com * inline-script block
* 1st-party scripts: github.com * 1p-script block
* 3rd-party scripts: github.com * 3p-script block
* 3rd-party frames: github.com * 3p-frame block

List of Global uBlock dynamic filtering

* all: * * * block
* images: * * image block
* 3rd-party: * * 3p block
* inline scripts: * * inline-script block
* 1st-party scripts: * * 1p-script block
* 3rd-party scripts: * * 3p-script block
* 3rd-party frames: * * 3p-frame block

List of Local uBlock dynamic filtering translated to static filters

* all: *$domain=github.com
* images: ||github.com^$image
* 3rd-party: ||github.com^$third-party
* inline scripts: ||github.com^$inline-script
* 1st-party scripts: ||github.com^$script
* 3rd-party scripts: ||github.com^$third-party,script
* 3rd-party frames: ||github.com^$subdocument

List of Global uBlock dynamic filtering translated to static filters

* all: $domain=*
* images: $domain=*^$image
* 3rd-party: $domain=*^$third-party
* inline scripts: $domain=*^$inline-script
* 1st-party scripts: $domain=*^$script
* 3rd-party scripts: $domain=*^$third-party,script
* 3rd-party frames: $domain=*^$subdocument

**Comment by gorhill** [comment]
List of Local uBlock dynamic filtering translated to static filters

all: `*$domain=github.com`
images: `*$image,domain=github.com`
3rd-party: `*$third-party,domain=github.com`
inline scripts: `||github.com^$inline-script`
1st-party scripts: `||github.com^$script,first-party`
3rd-party scripts: `*$script,third-party,domain=github.com`
3rd-party frames: `*$subdocument,third-party,domain=github.com`

List of Global uBlock dynamic filtering translated to static filters

all: `*`
images: `*$image`
3rd-party: `*$third-party`
inline scripts: `*$inline-script`
1st-party scripts: `*$script,first-party`
3rd-party scripts: `*$script,third-party`
3rd-party frames: `*$subdocument,third-party`

**Comment by flyingzebras** [comment]
@gorhill Thank you for helping me. You can put this to the wiki if you think its useful to explain how static can be converted to dynamic filters and vice versa.

**Comment by flyingzebras** [comment]
@gorhill So how do you block third-parties excluding a particular third-party site?

```*$third-party,domain=pornhub.com``` will block all third-parties. How do I exclude phndcn.com in that filter?

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1357

**Comment by gorhill** [comment]
> How do I exclude the third-party domain phndcn.com in that filter?

You can't if you are using the `important` option, no exception filter can override a block filter with the `important` option, that is the whole point of such option.

**Comment by flyingzebras** [comment]
I was confused by some filters that prevented me to do things that I normally would be able to.
