### ISSUE TITLE
"no-popups: * true" rule blocks opening of a clicked url

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#1066]
Background Info: When you have popups blocked globally <code>no-popups: * true</code>, clicking a link on a page some times is blocked.

##### STR - (tested in firefox v42 only)
1. Add <code>no-popups: * true</code> rule
2. Try clicking a link present <a href="http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-69#post-2548531">in this post</a>. 
3. We will see the new tab opening blocked with the logger reporting below -

 no-popups: * true	| --	| popup	| about:blank 
 ----------------------  | --- | ------- | ------------- 

**Note:** Looks like this is fixed in v1.4.1 beta @https://github.com/gorhill/uBlock/commit/945a8a999ad319a656a622fea098291edc4962cd. Just opened to better track the issue and link the commit and close the issue..

**Comment by gorhill** [comment]
Fixed with 945a8a999ad319a656a622fea098291edc4962cd.

**Comment by harshanvn** [comment]
Thanks!
