### ISSUE TITLE
Userinterface opimization Part 1

### ISSUE THREAD

**Issue by Gnuop** [gorhill/uBlock#1067]
Hello alltogether,

i decided to contribute to this project. i hope you like it. if so, if would continue (have several other things in mind). i began with the dashboard.

look at the screenshots.

great project!

- integrated logo and slogan
- new element in navigation: back/restore (took these elements from the "Einstellungen" Tab)
- many adjustments (just compare Firefox layout right now with new screens to identify them)
 

![uber](https://cloud.githubusercontent.com/assets/11529553/6766739/50022cca-d00a-11e4-8e0a-51a27bf5c163.jpg)
![einstellungen](https://cloud.githubusercontent.com/assets/11529553/6766740/50b8e1c2-d00a-11e4-9d37-ef85a6eea9ab.png)
![vorgegebene filter](https://cloud.githubusercontent.com/assets/11529553/6766741/523e09d2-d00a-11e4-9891-cd34eed0940c.jpg)
![backup](https://cloud.githubusercontent.com/assets/11529553/6766742/533f6cfe-d00a-11e4-9b1a-d00ffa458bd6.png)

**Comment by chrisaljoudi** [comment]
What are the differences, and what problem do they solve?

**Comment by Gnuop** [comment]
- integrated logo and slogan
- new element in navigation: back/restore (took these elements from the "Einstellungen" Tab)
- many adjustments (just compare Firefox layout right now with new screens to identify them)

actually these changes do not solve any problems. just a leaner layout - put things where they belong.

**Comment by Dashed** [comment]
I like it; mainly because the tabs are way too close to the top.

**Comment by gorhill** [comment]
> these changes do not solve any problems

**Comment by Gnuop** [comment]
@Dashed: thanks.

next steps would be optimizing last navigation elements.

**Comment by Gnuop** [comment]
imho good/great design is always a problem solver because it optimizes the usability with a product.

take a look at the settings from https://getadblock.com/.

simple, lean, professional!
