### ISSUE TITLE
[Efficiency] Make use of `String.prototype.startsWith`

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1067]
`String.prototype.startsWith` appeared in Chromium 41, so this means it is currently available in both Chromium-based and Firefox-based browsers.

Using `String.prototype.startsWith` is probably more efficient -- or at least more concise -- than using:

- `haystack.substr(pos, needle.length) === needle`
- `haystack.lastIndexOf(needle, 0) === 0`

A polyfill will have to be created for older versions of Chromium (Firefox has supported `startsWith` [since version 17](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)).

**Comment by tophf** [comment]
I don't see any improvement on Chrome 49/Win7x64 and the [source code](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/js/string.js&q=String.prototype.startsWith&sq=package:chromium&type=cs&l=873) contains only a js wrapper on substr.

**Comment by gorhill** [comment]
Open an issue with Chromium devs if you make the case there is something wrong with Chrome 49.

**Comment by tophf** [comment]
My point is that it was always a wrapper since [the beginning in 2013](https://chromium.googlesource.com/v8/v8/+/0627d433b0bbfb7282a9f59f92665478e1b21ff9) so if you see an improvement in Chrome it can noly mean the test is flawed. I've ran your tests on Chrome 45 and 46 and the results are worse for `startsWith`, **as expected**. And since those version don't yet have Turbofan optimization for V8 the speed drop is -42%!

**Comment by gorhill** [comment]
> My point is that it was always a wrapper

<https://chromium.googlesource.com/v8/v8/+/84b4e1d4336454908a6824e81d5fa5257003eaf0>.

**Comment by tophf** [comment]
Well, that explains why Chrome 49 shows only -0.29% speed drop. Anyway, there's no gain and as I've said, not sure there ever will be...

**Comment by gorhill** [comment]
> there's no gain

Explain the benchmark results then. You are asking to me to disregard objective benchmarks and stick to your "**I** see no improvement".

**Comment by tophf** [comment]
Maybe it depends on CPU? Or something else? Why a js wrapper that calls `substr` should be objectively faster than a [simpler `indexOf` wrapper](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/js/string.js&q=String.prototype.startsWith&sq=package:chromium&type=cs&l=104) in your opinion?

**Comment by gorhill** [comment]
> Why a js wrapper that calls

Your the one asking the question and making the claim that it makes no difference, spend the time to research why. That's how it works, if you are curious about something, do not ask other to spend their own time to seek the answers to your questions -- you have access to the code, read it.

**Comment by tophf** [comment]
That was a rhetorical question, obviously. The point is that it may be faster in *some* cases where the haystack is big and the needle is small, but it may be [much] slower in case of a typical url of 50-200 characters long because of overhead for creating a new string object.

**Comment by tophf** [comment]
FWIW, I see the same 3x speedup in Chrome 47 - 1.2million op/s which is also 3 times faster than Chrome 49.

I'll revisit this issue once Chrome 48 and 49 are in stable channel.

**Comment by gorhill** [comment]
> the source code contains only a js wrapper on substr

I replaced all instances of `haystack.lastIndexOf(needle, 0) === 0` with `haystack.startsWith(needle)`. `lastIndexOf` is **not** _"only a js wrapper on substr"_, see the dependencies below:

- `StringStartsWith`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/js/string.js&l=873)
    - `%_SubString`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/runtime/runtime-strings.cc&l=285)
- `StringLastIndexOfJS`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/js/string.js&l=121)
    - `%StringLastIndexOf`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/runtime/runtime-strings.cc&l=186)

I also replaced all instances if `haystack.slice(-needle.length) === needle` with `haystack.endsWith(needle)`, and `haystack.slice(pos, needle.length) === needle` with `haystack.startsWith(needle, pos)`; and in this case `slice` is a wrapper around substr:

- `StringEndsWith`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/js/string.js&l=903)
    - `%_SubString`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/runtime/runtime-strings.cc&l=285)
- `StringSlice`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/js/string.js&l=524)
    - `%_SubString`: [source](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/runtime/runtime-strings.cc&l=285)

So essentially in the worst case, same performance, and if ever a browser (uBO is for more than just Chromium) creates a better implementation of `startsWith`/`endsWith` which no longer cause instances of temporary slices to be created, uBO will benefit immediately.

However the benchmark shows that replacing `slice` with `endsWith` benefits a lot Chromium and Firefox. I included `indexOf` just out of curiosity in the benchmark, but this was never used in uBO.

It's not unexpected nightly built of browsers may have performance regression issues, and development decision here should not be based on these regressions which are very likely to be fixed -- I am sure the browser devs care about these regressions.

By the way "rhetorical questions" are completely useless with such technical topics -- we are dealing with code here, not philosophy -- the only valid way is to actually fully research and report.

**Comment by deepj** [comment]
@gorhill See these results in Firefox 44 beta. I guess `startsWith` is not slower only in Chrome/Chromium...

![screen shot 2015-12-21 at 14 34 25](https://cloud.githubusercontent.com/assets/33736/11931739/492332f0-a7f0-11e5-9303-9a386f7d69cd.png)
