### ISSUE TITLE
Add tooltips to advanced features

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#1069]
Now that advanced mode can have tooltips we need tooltips on advanced mode features.

**Comment by gorhill** [comment]
See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) for feature request. Work as already started on this.

**Comment by SoniEx2** [comment]
Uhh... You do realize #451 was a feature request right?
