### ISSUE TITLE
[Efficiency] Use ES6 Map()/Set() in lieu of Object where possible

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1070]
Benchmarks:
- Write ops: http://jsperf.com/smalles6set-vs-smallobject-write.
- Read ops: http://jsperf.com/smalles6set-vs-smallobject-read.

For instances in the code where no iteration through the set is needed, we can use a shim for [versions of Chromium older than 38](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility) -- Firefox supports ES6 Set() since FF 13.

Because `for...of` is supported only for Chromium 38+, for instances in the code where iterations through the set is needed, this will have to wait for longer term. Possibly a v2.0 of uBO will be incompatible with Chromium version 37 and older.

**Comment by gorhill** [comment]
Need to survey where else conversion to Set/Map is possible.

**Comment by gorhill** [comment]
`jsperf.com` is down, so there is a custom benchmark now: https://gorhill.github.io/obj-vs-set-vs-map/

**Comment by kurtextrem** [comment]
@gorhill Thank you very much for doing that. First of all it is great to have an efficient blocker and at the same time an open development. The benchmark for Set/Map was interesting, I'm gonna use it as well.

**Comment by lewisje** [comment]
Also, in case anyone ports this to Safari: 9+ supports `Map` and `Set` very well, 7.1 and 8 support them fairly well, and older versions don't support them natively.

**Comment by Betsy25** [comment]
Just fixed in Firefox Nightly : [Bug 1305062 - Improve ES6 Map performance for fresh object keys ](https://bugzilla.mozilla.org/show_bug.cgi?id=1305062)
