### ISSUE TITLE
"Whitelist YouTube channels in uBlock Origin" retains previous entry on page change.

### ISSUE THREAD

**Issue by TheSchnebbz** [gorhill/uBlock#1071]
(Apologies if this should be reported on the Greasyfork page instead.)

Using Google Chrome Version 47.0.2526.80 m
TamperMonkey Version 3.12.58 
Whitelist Channels in uBlock Origin UserScript Version 1.1
uBlock Origin Version 1.4.0
YouTube+ (by ParticleCore) Version 0.8.7

When navigating YouTube.com the "&user=[YouTube Channel Name]" entry will remain in the URL field of Chrome for one page after navigating away from the video that caused it to be put there.

E.G.
I click on a video from "X", the URL is appended with "&user=X"
Then I click on a video from "Y", the URL now shows "&user=X&user=Y"
I then click on a video from "Z", the URL shows "&user=Y&user=Z"
I then go to my subscription feed, the URL shows "youtube.com/feed/subscriptions?user=Z" (With a "?" instead of a "&")

The issue still happens with all other plugins and scripts disabled (done by allowing TamperMonkey to run in incognito mode, and disabling the YouTube+ script, which is the only other script running on YouTube.com)

I do not experience this issue on Pale Moon Version 25.8.1 and GreaseMonkey Version 1.15.1 (Same userscript and version)

I did not test this on Firefox, but I can if needed.

I'll supply any additional information that's needed as best I can.

Thanks for your time.
The_Schnebbz

**Comment by gorhill** [comment]
Fixed: <https://greasyfork.org/en/scripts/13226-youtube-whitelist-channels-in-ublock-origin/versions>. 

Thanks for reporting.
