### ISSUE TITLE
No Retina/HiDPI icon on right click menu in Chrome

### ISSUE THREAD

**Issue by ChrisBegley** [gorhill/uBlock#1073]
I recently got a Mac with a Retina display, and noticed that the uBlock icon displayed in the right click menu in Chrome looks blurry and pixelated. It looks great in Firefox.

![Retina](http://i.imgur.com/A6Ul8iw.png)

**Comment by gorhill** [comment]
Browser bug: <https://code.google.com/p/chromium/issues/detail?id=418380>.

**Comment by Hrxn** [comment]
Solution: Disable context menu entry for uBO in the dashboard.

This is redundant functionality, IMHO, since you just can activate element picker mode from the extension bar menu (That eyedropper icon).
