### ISSUE TITLE
uBlock Origin Uninstalling

### ISSUE THREAD

**Issue by KingThunder** [gorhill/uBlock#1074]
I've experienced the bug that the uBlock Origin uninstall by itself in Firefox,  but it's not every time that it happens, it happened twice. Today, i was checking my quarantine, and for my surprise the uBlock Origin .xpi was there, two of them. I can remember that some users are having the same problem. So it can be antivirus related. And it was not flagged as a malware in Avira, it was saying that it's a "Suspect file".

Sorry for my bad english.

**Comment by 5t3f4n** [comment]
It's a known issue. Most likely caused by uBlock Origin including links of known malware sites as part of the bundled filter lists.

https://github.com/gorhill/uBlock/issues?q=virus

**Comment by gorhill** [comment]
[Software known to have uninstalled uBlock Origin](https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin).

**Comment by Hrxn** [comment]
Best solution: Don't use 'antivirus' snake oil..
