### ISSUE TITLE
Firefox 43 labels uBlock Origin as unverifiable

### ISSUE THREAD

**Issue by Smultie** [gorhill/uBlock#1075]
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by gorhill** [comment]
All extensions on AMO are signed. The one in the _Releases_ section on GitHub is not, if you want to use that version, you will have to use a version of FF which allows the use of unsigned versions.

**Comment by Smultie** [comment]
Alright, makes sense.

Thanks!

**Comment by lewisje** [comment]
I have not seen the promised "unbranded builds" yet, but you might try setting `xpinstall.signatures.required` to `false` in `about:config`: https://wiki.mozilla.org/Addons/Extension_Signing#Timeline

**Comment by gorhill** [comment]
Or just install the [dev build from AMO](https://addons.mozilla.org/addon/ublock-origin/versions/beta).

**Comment by Smultie** [comment]
Thanks. I think I disabled those when they weren't auto-updating.
Did Mozilla fix the auto-updating for the development channel?

**Comment by lewisje** [comment]
It did, and even the 64-bit dev builds auto-update.
