### ISSUE TITLE
On a site with 0 connections displayed

### ISSUE THREAD

**Issue by zymase** [gorhill/uBlock#1076]
I've opened a GitHub account for the sole reason of finding an answer to a mystery beyond my understanding.

uBolockO 1.4.0 on Firefox 43.0 64-Bit on Windows 7SP1 64-BIT
uBlockO is configured "Max" : 3rd-party frames - 3rd-party scripts - 3rd-party

I opened http://www.smashingmagazine.com/, page displays a bit naked but OK - I call uBlockO to have a look as usual on what I'll have to set for this new site, when I notice that uBlockO displays that there are 0 connections. I'm on smashingmagazine.com and uBlockO shows 0 connections established, yet I have at least one connection, to smashingmagazine.com, no?!

Screenshot : http://img15.hostingpics.net/pics/359521Smashingmagazine.jpg

After that I authorized access to netdna-ssl.com and the page got better dressed up ...
But how was it possible to have accessed a page and have uBlockO display 0 connections?
Maybe I've missed something but I've been using uBlockO since its launch and it's the first time I encounter such an oddity.

Thanks :)

**Comment by gorhill** [comment]
Resources were pulled from cache?

**Comment by gorhill** [comment]
Ok I can reproduce even with the cache disabled (by keeping dev console opened). Will see what I can find.

**Comment by zymase** [comment]
No, gorhill. Hi,

I should have mentioned it : cache was clean, toyally

**Comment by gorhill** [comment]
The navigation event is fired after the network request to fetch the root document, so this causes the count to be reset to [zero at line 457 of `tab.js`](https://github.com/gorhill/uBlock/blob/ea49484dd3c846565deef50acd653a70e257f0ca/src/js/tab.js#L457). This causes the current issue for web pages which pull *all* their resources from 3rd-party servers, which is the case here.

**Comment by zymase** [comment]
OK, gorhill- Thanks
Just one thing : I'm unaware of the terminology.  What does "correction" mean here? That it'll be corrected in next uBO's update?

**Comment by zymase** [comment]
OK, gorhill. Thanks.
