### ISSUE TITLE
Anti-Adblock inline-script on eurotransport.de

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1078]
On eurotransport.de
there is an Anti-Adblock notice when loading with ublock + Standard Filters + Easylist Germany and Firefox 43.
http://postimg.org/image/o5vpc23yz/

I tried a bit and the following filter works for me:
eurotransport.de##script:contains(antiAdBlock)

So this or a better filter could be added to ublocks filter.

**Comment by gorhill** [comment]
Can you try:

    ||eurotransport.de/*/antiAdBlock.js$script,first-party,redirect=fuckadblock.js-3.2.0

And see if the site work fine with this? This solution would work for both Chromium and Firefox.

**Comment by gorhill** [comment]
Err never mind, I had forgotten to remove the blocking of inline scripts. The site is using fuckadblock, so I may need to further fine tune the redirect version.

**Comment by TonyTough** [comment]
Hello,

i refreshed the ublock filters, but this fix does not work for me, I still get the anti-adblock message.

**Comment by gorhill** [comment]
Works on my side -- try restarting uBO, then go to 3rd-party filters pane, then force an update of the assets. See if this works.

**Comment by gorhill** [comment]
Ok, I found an issue when the `redirect-resources.txt` file is updated, it won't be reloaded in memory when updating manually. Quit and restart the browser as a workaround, until the issue is fixed.

**Comment by TonyTough** [comment]
OK,
after restarting Firefox, it works.

**Comment by gorhill** [comment]
Could you confirm the site is no longer using an anti-blocker script?

**Comment by TonyTough** [comment]
Yes, it seems so.
