### ISSUE TITLE
Google rewrite inline script rule in Wiki

### ISSUE THREAD

**Issue by EchoDev** [gorhill/uBlock#1084]
The Wiki mentions a rule to stop Google from tracking URLs that are clicked when searching.
I removed my Google link fix script for a while since the rule "google.*##script:contains(rwt)" seemed to work fine but it killed Google Images for me. It is probably not good to keep that in the Wiki.

Google images stopped working for me with:
the rule: google.*##script:contains(rwt)
browser: Firefox 43 x64
os: Windows 7 x64

Can anyone check if Google Images stops working with the rule "google.*##script:contains(rwt)"? Maybe it is just on my end.

**Comment by gorhill** [comment]
Yes, Google Images was broken for me. I removed the example.
