### ISSUE TITLE
Block ads on focus.de and golem.de using redirect resources

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#1085]
Videos here...
http://www.golem.de/news/echtzeituebersetzung-skype-translator-wird-regulaer-in-skype-integriert-1510-116643.html
...and here: http://www.focus.de/politik/videos/wut-video-fuer-seine-feinde-so-rechnet-ein-fluechtling-mit-den-besorgten-buergern-ab_id_5029105.html

Should be the same technique and script file used for the other sites as well.

**Comment by gorhill** [comment]
I don't see any ads. Be sure you disable Flash completely, there is no ads with HTML5 players.

**Comment by tobbi** [comment]
True, my mistake.
