### ISSUE TITLE
Manually updating lists always shows newer versions

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1087]
When I purge caches and manually updates lists and then immediately I try to do the same, there are always new versions showing.  And after the second update, I can see list numbers are getting updated. I doubt many lists are getting updated many times within the span of a few minutes, anyone know the reason why this is?

As a side question: why do most lists not use all the available items (e.g. using 23 out of 25 instead of 25 out of 25). Is this because duplicate items are taken into consideration by uBO?

**Comment by gorhill** [comment]
Be **specific**, provide screenshots etc. "there are always new versions showing" is too vague. What lists, numbered steps etc.

**Comment by publicarray** [comment]
> I purge caches and manually updates lists and then immediately I try to do the same

Please [read the wiki](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters) before asking questions here. 
From the wiki:
> **Update now**
This button is available for use if and only if there is at least one filter list which is deemed outdated. If this condition is fulfilled, you can force an update of all filter lists which are deemed out of date.
**Purge all caches**
This will remove all locally cached copies of filter the filter lists. Essentially, this will cause all filter lists to become out of date. This can be used to force an update of all filter lists.

So effectively you are repetitively downloading the lists and deleting them. 

>  Is this because duplicate items are taken into consideration by uBO?

[Yes](https://github.com/gorhill/uBlock/wiki/Myth:-uBlock-consumes-over-80MB)

**Comment by publicarray** [comment]
I think this can be closed.

**Comment by gorhill** [comment]
> When I purge caches and manually updates lists and then immediately I try to do the same, there are always new versions showing.

"Purging the cache" means to delete the cached copy of the most recent versions of filter lists, so this will always result in the stock filter lists to be marked as "new version available".
