### ISSUE TITLE
I've made a website for uBlock Origin

### ISSUE THREAD

**Issue by Wolfgange3311999** [gorhill/uBlock#1088]
I've spent some time and created [a website for uBlock Origin](http://wolfgange3311999.github.io/uBlock/), if anyone's interested. Here's the source:
https://github.com/Wolfgange3311999/uBlock/tree/website-source

However I cannot create a pull request because there's no new-branch request support in GitHub (And both the 'gh-pages' and 'website-source' branches do not exist in the upstream repository). If someone's interested, could they create two new empty branches ('gh-pages' and 'website-source') in order for me to submit a pull request?

By the way, I'm open to making any modifications however that discussion would be better-suited for the pull request.

**Comment by publicarray** [comment]
I don't know if @gorhill wants a webpage for this project. See https://github.com/gorhill/uBlock/wiki/Why-don't-you-accept-donations%3F. Though gh-pages hosting is a free service It does require a little time to maintain. On a seperate note I am not sure why you want 2 branches, gh-pages is fully compatible with Jekyll: https://help.github.com/articles/using-jekyll-with-pages/ so only one branch is needed. For example one of my sites using gh-pages and jekyll: https://github.com/publicarray/solarsystem

**Comment by publicarray** [comment]
Sorry I see that you are using grunt, that explains the 2 repositories.

**Comment by Wolfgange3311999** [comment]
I could maintain the website however as you've mentioned, the website doesn't necessarily require any maintenance considering everything links back to GitHub.

**Comment by publicarray** [comment]
Hm. I think if you used [git submodules](https://help.github.com/articles/using-submodules-with-pages/) than it would make it more maintenance free, saves pushing to two different branches for a single change. Just my 2 cents.

**Comment by gorhill** [comment]
As often stated, I do not want uBO to have a home -- hence no "phone home".

To find out whether such mini site is compatible with uBO, I would have to look at the details of GitHub Pages -- the important part being that it does not contradict at all the current _Privacy policy_, which one won't be changed. For now I just do not have the time to even look into all this.

Also should definitely not depend on any unessential 3rd parties -- I see `fonts-googleapis.com` on that site (which I block globally by default on my side).

**Comment by hyiltiz** [comment]
Instead of doing this, maybe we should let the project which is almost unmaintained yet is still living off of the reputation of uBlock by registering the domain name uBlock.org and even calling itself "official", go dead. Dead is a heavy word. But the fact that they claim they are official really pisses me off.

**Comment by Wolfgange3311999** [comment]
I've removed all fonts and the `fonts-googleapis.com` dependency. Along with that, I've checked GitHub's [Terms of Service][1] and [Privacy policy][2], neither of which appear to directly contradict any of [your Privacy Policy][3]. And I wouldn't in any way consider it a "home". If you ever get the time to look into it, let me know.

[1]:https://help.github.com/articles/github-terms-of-service/
[2]:https://help.github.com/articles/github-privacy-policy/
[3]:https://github.com/gorhill/uBlock/wiki/Privacy-policy/

**Comment by lewisje** [comment]
I think that any official website should run off a server suitable for serving auto-updates for a potential Safari version of this extension, and if such a server is set up, I hope that whoever maintains it, and whoever maintains the Safari version, practice good stewardship of them.

**Comment by Wolfgange3311999** [comment]
@lewisje I don't think that would work because such a thing requires server side code which Github doesn't support (and gorhill doesn't want an actual server).

**Comment by lewisje** [comment]
You were missing my point, so to make it briefer: I don't think that an official website for uBlock Origin should be hosted on GitHub.

(I guess gorhill doesn't want a Safari version to exist after all, which is a shame.)

**Comment by gorhill** [comment]
> doesn't want a Safari version to exist after all

Where did I ever said this? I only said I am not equipped to develop one, and even if I had the h/w + OSX, I just wouldn't have the time.

**Comment by lewisje** [comment]
It's implied by not wanting an actual server, and by Apple's requirement to have an actual server in order for an extension to auto-update.

**Comment by ilu33** [comment]
Why should he care for what Apple wants if he does not develop anything for Apple? There is absolutely no reason to be offended. He says he does not have the time, so any discussion is moot. Nobody prevents you from developing for safari and setting up a server for it if you want to.
Back to topic: Your design looks nice, whether it's needed or not :-)

**Comment by hyiltiz** [comment]
This is really a great idea, and the design looks great. From a user's perspective, we should just be delivering easy way to do what they think the software should do: install once and do what we promised to do. So we need auto-update. Fighting with Apple is great, but not in this Issue :grinning: People do that in other places. 

Let's concentrate on whether we can make an official website.

**Comment by Wolfgange3311999** [comment]
Let me enumerate the advantages and disadvantages of a website:
### Advantages
 - Increased percieved reputability (in my opinion, a website alone makes an addon seem more mature and thus more reputable).
 - More accessible FAQ and other info (if added to the site or simply linked to the wiki, it provides a much more accessble FAQ. Many people won't bother to click a wiki page but they will for an FAQ page. This could mean less incalid bug reporsts)

### Disadvantages
 - gorhill doesn't want uBlock to have a home
 - GitHub's hosting policy might contradict something in uBlock's privacy policy (although I've done a rudimentary check without finding anything significant).

Does anyone have anything else to add?

@ilu33 Thanks, although in my opinion it looks rather awkward without the light fonts previously used.

**Comment by publicarray** [comment]
> it looks rather awkward without the light fonts previously used.
you can try `-webkit-font-smoothing: antialiased;` to make them a little thinner for webkit browsers.

**Comment by lewisje** [comment]
ilu33, I was just thinking ahead for when some Mac user decides to make and distribute a Safari version of this extension (I'd have done it already, if I could afford a Mac, the Apple developer fees, and the bandwidth fees for the update server); at this point, once that happens, there will be *two* sites for uBlock Origin, because the one hosted on GitHub Pages cannot be used to distribute automatic updates.

Oh, thanks for assuming that I was thinking gorhill would be the one to port to Safari; it's not like I wasn't already well aware, for more than a year, of his lack of interest in going out of his way to do so.

**Comment by seanrand** [comment]
I'm all for uBlock having a GitHub Page.

> gorhill doesn't want uBlock to have a home

Since GitHub Pages are mostly static and the source is right in the gh-pages branch, I wouldn't even consider them a "home", but more as a fancy splash page for the content in the project repo and wiki. It doesn't contradict uBlocks manifesto or privacy policy, so I'd say go ahead with it.

Maybe linking to the uBlock FAQ from the GH Page would be a good idea too.

**Comment by hyiltiz** [comment]
Guys, can't we instead get this lame page ublock.org off from Internet, or get that domain? The dev is dead already, but is ruining uBlock Origin's reputation. I tried opening Issues on that project page, but ruthlessly got my Issues deleted. What he is doing, I assume, is somehow against some rule, and as long as we can find a rule that can go against him, maybe we can file a report to Github dev team to say something about him. I know this could be controversial, and some people (I guess including key dev here) might remain silent to this. But we as more marginal contributors could do something about it.

**Comment by Wolfgange3311999** [comment]
@publicarray Thanks, I can try the webkit filter. And I wasn't sure if gorhill wanted any fonts hosted on the webpage (uBlock still blocks them when held internally on gh-pages).

@seanrand Yeah, I can definitely put an FAQ link to the top. I'll do that later today.

@hyiltiz Getting ublock.com off the internet would be great. If you have any ideas, go for them, but I don't think we should wait for something that might never happen. Instead, prevent the misunderstanding with a webpage of our own. By default most people see one website and one GitHub repo and associate them (especially since the repo is still named "ublock"). By having two websites it automatically differentiates the two and raises the question, "What's the different?", which would conveniently be on the homepage (a link to wikipedia).

**Comment by lewisje** [comment]
I don't think ublock.org is even hosted on GitHub Pages (otherwise, Chris wouldn't be able to host an auto-updating Safari build there), so you can't take the issue to GitHub.

**Comment by hyiltiz** [comment]
​Well, I feel like we got bitten by some very bad scenario that ​could happen for softwares licensed under GNU GPL, in this case GNU GPLv3+. Our license does not forbid chris from forking, and does not forbid him from hosting the website uBlock.org. I think the only way for us, which is also good for users, is to gain enough publicity and attention so that, as @lewisje pointed out, people get aware that these are not the same.

**Comment by BUAWF** [comment]
I'm Satisfied with @gorhill.
Let the decision go with the Dev.
I Genuinely don't want this Project to go Popular/Rep Increase (as per your choices).
Let it go the way as it is.

**Comment by gorhill** [comment]
I still do not plan on spending time at all on anything else but code for uBO, so I will decline to create/maintain a web site, however trivial it appears. Other people can do so if they wish, as long as it is clear this is not an official site.
