### ISSUE TITLE
uBlock filter - privacy, blocks script on the Zapytaj.onet.pl 

### ISSUE THREAD

**Issue by alice37** [gorhill/uBlock#109]
For example: http://zapytaj.onet.pl/Profile/page,question,16312,0.html
This list after scroll to the end site, will load next 10 questions if there are.
However, any filter is active  that does not happen.

edit:
The problem I'm mostly on Firefox 37.0.2 and uBlock Origin 9.4.4

**Comment by gorhill** [comment]
I confirm that `||addthis.com^$important ` "breaks" the site.

However, given that this is an `important` filter, I am not going to provide an exception to fix that web site. The web site should fix itself, and accept that users may not want to allow `addthis.com` **at all**, not work against users.

Related info about `addthis.com`: <http://en.wikipedia.org/wiki/Canvas_fingerprinting#History>.

As far as I am concerned, I rather see a website broken by the use of "uBlock -- Privacy".

Workaround for users is to use dynamic filtering and create an `allow` rule for `s7.addthis.com` for the web site `http://zapytaj.onet.pl`, like so: `zapytaj.onet.pl s7.addthis.com * allow`, when entered manually in the _"My rules"_  pane.

**Comment by alice37** [comment]
OK. Add this rule and testing :)
