### ISSUE TITLE
0 blocked until now since install

### ISSUE THREAD

**Issue by hyiltiz** [gorhill/uBlock#1090]
Have been using uBlock Origin since about last year, and now is version 1.4.0 in Debian testing on Iceweasel 38.2.1. I have NoScript installed but is always Allowing  Scripts Globally. So why isn't uBlock Origin blocking anything to count? Might I have misconfigured something?

**Comment by gorhill** [comment]
Be more detailed. Are you saying uBO's blocked network requests count has been reset to zero from whatever non-zero value it was before? Is this a new install?

**Comment by hyiltiz** [comment]
I would love to give you detailed logs but I am not sure how.  The blocked
count since install which is visible at the middle of the uBO popup  had
always been as far as I can remember, 0.

On Sat, Dec 19, 2015, 13:03 Raymond Hill <notifications@github.com> wrote:

> Be more detailed. Are you saying uBO's blocked network requests count has
> been reset to zero from whatever non-zero value it was before? Is this a
> new install?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uBlock/issues/1090#issuecomment-166010644>.
>
-- 

Sent from Gmail Mobile.

**Comment by gorhill** [comment]
> had always been as far as I can remember, 0.

What is "as far as I can remember"? Months? Days? Minutes?

The block count is saved in uBO's SQLlite database which location is documented [here](https://github.com/gorhill/uBlock/blob/master/dist/README.md). Use another app to open the SQlite file (after disabling uBO to prevent corruption of the db) and see its content. This is what I see on my side:
![a](https://cloud.githubusercontent.com/assets/585534/11914609/148b5e94-a653-11e5-85d1-0817f101924b.png)

**Comment by hyiltiz** [comment]
OK, about at least 6 month. I will try to dump the db today.

On Sat, Dec 19, 2015, 13:21 Raymond Hill <notifications@github.com> wrote:

> had always been as far as I can remember, 0.
>
> What is "as far as I can remember"? Months? Days? Minutes?
>
> The block count is saved in uBO's SQLlite database which location is
> documented here
> <https://github.com/gorhill/uBlock/blob/master/dist/README.md>. Use
> another app to open the SQlite file (after disabling uBO to prevent
> corruption of the db) and see its content. This is what I see on my side:
> [image: a]
> <https://cloud.githubusercontent.com/assets/585534/11914609/148b5e94-a653-11e5-85d1-0817f101924b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uBlock/issues/1090#issuecomment-166011729>.
>
-- 

Sent from Gmail Mobile.

**Comment by hyiltiz** [comment]
Had a keyboard time at last. Here comes the screenshot. It seems blank. Maybe I should re-install?

![ublock0](https://cloud.githubusercontent.com/assets/3246683/11925212/58f44a98-a787-11e5-8d45-22383591b26c.png)

**Comment by gorhill** [comment]
Click the _"Browse Data"_ pane, find the value in there.

**Comment by hyiltiz** [comment]
It was blank. It was strange, since the uBlock0.sqlite file is 9.6M large.
![ublock1](https://cloud.githubusercontent.com/assets/3246683/11939779/5fad8262-a7f2-11e5-9b7e-c2d0a53c248a.png)

**Comment by hyiltiz** [comment]
Maybe I can send the `uBlock.sqlite` file to you @gorhill ? The database is behaving abnormal; I tried dumping it to a .csv file according to https://www.sqlite.org/cli.html, but it gives only an error for the first time when `select * from settings;` is executed by `sqlite3`, and when the same `select * from settings;` is executed for a second time, a huge list is dumped to standard out then followed by the same error. The error was:

> Error: database disk image is malformed

Here is a snipped out the output when executed for a second time:

```
...
""http://someonewhocares.org/hosts/hosts"":{""off"":true,""title"":""Dan Pollock’s hosts file"",""group"":""multipurpose"",""supportURL"":""http://someonewhocares.org/hosts/""},""https://spam404bl.com/spam404scamlist.txt"":{""off"":true,""title"":""Spam404"",""group"":""malware"",""supportURL"":""http://www.spam404.com/""},""http://stanev.org/abp/adblock_bg.txt"":{""off"":true,""title"":""BGR: Bulgarian Adblock list"",""group"":""regions"",""supportURL"":""http://stanev.org/abp/""},""http://winhelp2002.mvps.org/hosts.txt"":{""off"":true,""title"":""MVPS HOSTS"",""group"":""multipurpose"",""supportURL"":""http://winhelp2002.mvps.org/""},""https://www.fanboy.co.nz/enhancedstats.txt"":{""off"":true,""title"":""Fanboy’s Enhanced Tracking List"",""group"":""privacy"",""supportURL"":""https://forums.lanik.us/""},""https://www.fanboy.co.nz/fanboy-antifacebook.txt"":{""off"":true,""title"":""Anti-ThirdpartySocial (see warning inside list)"",""group"":""social"",""supportURL"":""https://forums.lanik.us/""},""https://www.fanboy.co.nz/fanboy-korean.txt"":{""off"":true,""title"":""KOR: Fanboy's Korean"",""group"":""regions"",""supportURL"":""https://forums.lanik.us/""},""https://www.fanboy.co.nz/fanboy-swedish.txt"":{""off"":true,""title"":""SWE: Fanboy's Swedish"",""group"":""regions"",""supportURL"":""https://forums.lanik.us/""},""https://www.fanboy.co.nz/r/fanboy-ultimate.txt"":{""off"":true,""title"":""Fanboy+Easylist-Merged Ultimate List"",""group"":""multipurpose"",""supportURL"":""https://forums.lanik.us/""},""https://www.fanboy.co.nz/fanboy-vietnam.txt"":{""off"":true,""title"":""VIE: Fanboy's Vietnamese"",""group"":""regions"",""supportURL"":""https://forums.lanik.us/""},""https://www.void.gr/kargig/void-gr-filters.txt"":{""off"":true,""title"":""GRC: Greek AdBlock Filter"",""group"":""regions"",""supportURL"":""https://github.com/kargig/greek-adblockplus-filter""}}"
```

**Comment by gorhill** [comment]
Looks like your SQlite file is corrupted. You will have to delete it and let uBO generates a new one.

**Comment by gorhill** [comment]
See <https://developer.mozilla.org/en/docs/Storage#How_to_corrupt_your_database>.

**Comment by hyiltiz** [comment]
Let me try. Thanks!
