### ISSUE TITLE
Video ads on Daisuki are not getting blocked!

### ISSUE THREAD

**Issue by dan96kid** [gorhill/uBlock#1091]
Earlier today, I tried to watch an anime on the Daisuki website, only to encounter a video ad. I updated my filters and that video ad STILL shows up! If it is possible, how can I block that video ad?

**Comment by gorhill** [comment]
Report to EasyList maintainers please: <https://forums.lanik.us/viewforum.php?f=62>.

Also, always respect [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) guidelines.
