### ISSUE TITLE
uBlock Origin Android App

### ISSUE THREAD

**Issue by SlimShayD** [gorhill/uBlock#1092]
On multiple occasions you made clear you want to provide users an alternative solution to the Adblock Plus addons/extensions. 
On my Android device I use Opera which works better than Firefox, but doesn't have an adblocker (because no extension support). So I use the [ABP for Android](https://adblockplus.org/en/android-about) app. Which works fine.
Would you consider creating an Android app? With more options for privacy and filter lists?

**Comment by gorhill** [comment]
No, it's a hobby, I wouldn't have time for this.

**Comment by lewisje** [comment]
ABP for Android works very differently from ABP for a browser; lacking browser APIs, this local Web proxy uses heuristics to figure out how best to apply the filters, and it doesn't do a good job of it.

Almost none of the innovations in uBlock Origin would translate to an Android app, and it's likely that the reason for fewer options for filter lists is that ABP for Android has problems processing large numbers of filters.
