### ISSUE TITLE
[Logger] Cannot reverse find a specific filter

### ISSUE THREAD

**Issue by g3939434** [gorhill/uBlock#1093]
uBlock Origin v1.4.0, Firefox 43, Windows 10

1. Add filter `##a[href^="http://gjsq.me/"]`

2. Open logger and go to https://plus.google.com/112899958745525792284/posts/BhQ3UuCSQyq

3. Click `##[href^="http://gjsq.me/"]` and the result is blank

**Comment by gorhill** [comment]
The filter `##a[href^="http://gjsq.me/"]` is not applied when I visit above URL, there is no matching elements.

**Comment by g3939434** [comment]
That's strange. When I visit the URL, I get the following

![01](https://cloud.githubusercontent.com/assets/12552952/11958231/97718d00-a901-11e5-8f5c-f9e282e72c36.PNG)
```HTML
<a rel="nofollow" target="_blank" href="http://gjsq.me/web" class="ot-anchor aaTEdf" jslog="10929; track:click" dir="ltr">http://gjsq.me/web</a>
```

Here is what I got from logger when clicking `##[href^="http://gjsq.me/"]`
![02](https://cloud.githubusercontent.com/assets/12552952/11958259/c57128d2-a901-11e5-88bf-52628bac5392.PNG)

**Comment by gorhill** [comment]
For some reasons now I can reproduce. Investigating.
