### ISSUE TITLE
Element Picker issue on mashable.com

### ISSUE THREAD

**Issue by zymase** [gorhill/uBlock#1095]
Looks like mashable.com has been redesigned, very heavy front page but the concern here is with uBlockO and its Element Picker function, totally ineffective on http://mashable.com/

I'm running uBlockO 1.4.1b6 installed from AMO, reverted back to 1.4.0 stable, same issue.
Firefox 43.1 64-BIT on Windows 7SP1 64-BIT

The Element Picker does not allow "picking" anything on that site, yet I believe it is running because if I close the page, exit Firefox with all pages closed, Firefox stays in memory because a "MCI something" (pardon my lack of knowledge) is still open ...

**Comment by gorhill** [comment]
Works from here (FF43/Chromium47):

![a](https://cloud.githubusercontent.com/assets/585534/11930712/0159689a-a7b4-11e5-9dd1-62039319449d.png)

See if another extension interfere.

**Comment by zymase** [comment]
Thanks, gorhill.
I'm investigating right now, I'll report as soon as I find the culprit.
I'm testing add-ons installed/updated recently (even if an incompatibility could be older and considering I haven't visited mashable.com for some time)
I'll be back, if it's only me (and it most likely is since you've got it right) then sorry for the disturbance.

By the way, you've tested on Chromium47 while iIm running FF43.01, but I guess you've taken that into consideration.

I'll be back as soon as I find the culprit.

**Comment by zymase** [comment]
gorhill, the issue is not related to uBlockO and it occurs only (up to now) on mashable.com

When I wrote that Firefox wouldn't close properly after mashable.com and Element Picker, in fact it was not related to Element Picker. To check further, I've disabled uBlock, restarted Firefox, returned to mashable.com, closed the page, exited Firefox, and Firefox again wasn't closed properly. Task Manager showed as still active after FF exit, under Firefox:
- MCI command handling window
- nsAppShell:EventWindow
Only occurs after having visited mashable.com, never encountered this before.

So : nothing to do with uBlockO -- Sorry for the disturbance -- Feel free of course (you have my permission, lol) to remove my post, gorhill -- Thanks

**Comment by zymase** [comment]
I found the culprit, it was related to a Firefox setting inside my profile and as I mentioned above, appeared to have nothing to do with uBlockO
gorhill, please remove this post I initiated, sounds clumsy when so totally inappropriate.
Thanks-
