### ISSUE TITLE
New Popunder - WatchSeries

### ISSUE THREAD

**Issue by tracerman** [gorhill/uBlock#1096]
http://www.watchseries.li/

Popunders are showing  when you click on a video.

http://www.watchseries.li/link/5616639

Happened twice on that link.

**Comment by gorhill** [comment]
I could not reproduce a popunder, or even popup. Please provide precise detailed step-by-step instruction on how to reproduce the popunder issue.

**Comment by tracerman** [comment]
![ublock1](https://cloud.githubusercontent.com/assets/6810355/11946815/3ce4dc08-a824-11e5-96ff-13b37ddf0501.JPG)

**Comment by LimboSlam** [comment]
@tracerman: Is this the pop-up you get? It was blocked by my extension called JavaScript Popup Blocker. So @gorhill take a look please: http://healthydevil.com/got-5-minutes-you-can-brush-away-your-cellulite/?zt=55f32a1c6d47cd6364000193&zz=53b1d47c6d47cd82ae000011&site_id=&zr=177610&cb=VNtRbX68a988&f=pNb.

**Comment by tracerman** [comment]
Yes, one of them auto blocks it. But there are some times where it doesn't. I looked at my chrome history and these are the links it's been opened.

https://static.htmlhubing.xyz/tvmenew/

http://static.htmlhubing.xyz/tvmenew/?runauction=1?crr=fd6b68ccf4082072de7d,,AbtRHauATN0gHM1gTL3Y2dqZTM2Y3YyRnZtQWZi1WZGJTJl1mLvVGZpZXZoRnRyUiRyUSQzUCc0RHa4174ecc3558507e4e2c3&ctbust=0.6531584684176117

http://static.htmlhubing.xyz/tvmenew/?k=5678b3435d6157611533.19314746&h=26c1f2a02fc555615561106a84e4f43a9ec7300b&ban=7611533&iid=14507507871659014636209490918772333&r=982353&exp=prpd&ci=TNlHegRHUwwVPJ0SKxgAe4hGYYBFMcVTAt0WftEXIxgAXcxFXcBFMclWHpFQPt1XMUFFMwGDCMlHUwwVPJ0SKxgAe4hGYYBFMcVTAt0WftEXIxgAfQBDXp1RaB0Tb9FDVRBDtxgAT5BFMc1TCtkSMIgHeoBGWQBDX1EQLt1XLxFSMIwFXcxFXQBDXp1RaB0Tb9FDVRBD0xQV&pm=%3DwATU5VTxJ0TctEQLlUcDJED&pabt=%3D%3DADdAwH%2BRXcd4FD&pc=ZgBGYgBGA8xH&id=7611533

http://breignqued.com/

**Comment by LimboSlam** [comment]
Yes these are definitely pop-ups and if you disable Ublock Origin and other security extensions: it's clearly malware by Panda Free AV, as well as AVG Free. 

Another one, here it is: http://techteam2016.com/vella/1velapa.html?voluumdata=vid..00000002-002e-4eaa-8000-000000000000__vpid..16eeb800-a858-11e5-8b77-be4ca2e6d70e__caid..0c60d9a7-6da0-4636-92a3-477dff9bbf92__rt..R__lid..8f1b7c8f-af24-48eb-ab56-4120c1934543__oid1..02cb514d-fbfa-4a5f-9692-84b909105be3__var1..%5BWEBSITEID%5D__var2..%5BKEYWORD%5D__var3..%5BCATEGORYID%5D__var4..%5BCOUNTRY%5D__var5..%5BBID%5D__rd..serve%5C.%5Cpopads%5C.%5Cnet__aid..__sid..&websiteid=[WEBSITEID]&keyword=[KEYWORD]&categoryid=[CATEGORYID]&country=[COUNTRY]&bid=[BID]

**Comment by LimboSlam** [comment]
**Steps:**

1.) Disable click-to-play (Run all plugin content)
2.) Allow cookies to be set
3.) Disable Ublock Origin and any other security extensions/add-ons
4.) Temporarily disable your AV or just turn off web protection
5.) Then load offending website: http://www.watchseries.li/link/5616639

**Comment by gorhill** [comment]
> I looked at my chrome history 

Use the logger, it's the tool of choice to sort out what is occurring inside uBO.

**Comment by gorhill** [comment]
I still do not see popunders -- only popups. These can be handled by EasyList, report to maintainers of EasyList. For example:

    ||htmlhubing.xyz^$popup
