### ISSUE TITLE
custom about:blank background interferes with block element selection

### ISSUE THREAD

**Issue by xxxxme** [gorhill/uBlock#1097]
Firefox 43.0.1
ublock origin 1.4.0

Set a custom about:blank background in Firefox, using the userContent.css file (example file: 
http://paste.pound-python.org/show/10EBpugOawwa4h2tllgo/ http://desktop.freewallpaper4.me/view/original/5739/nasa-night-launch.jpg )

Open any web page (example: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md ), right-click some element and select "block element".

Result: The page is overlaid with the custom image, making element selection difficult.

default (white) about:blank
![default](https://cloud.githubusercontent.com/assets/3073154/11946680/2a858560-a82b-11e5-9a00-e253989a8e39.jpg)

custom background image on about:blank
![custom bg](https://cloud.githubusercontent.com/assets/3073154/11946679/2a84790e-a82b-11e5-9e59-2f5c6e62e62c.jpg)

Edit: I realize adblock plus, whose icon you can see in the screenshots, may interfere with ublock. I have it disabled currently.

**Comment by gorhill** [comment]
uBO can't prevent people from using user styles which intefere with uBO. Try the solutions [in there](https://github.com/chrisaljoudi/uBlock/issues/806#issuecomment-74441115):

> @ -moz document url (about: blank) {
>   *: empty: not ([style]) {
>   background-color: # F1F1F7;}
> }

You could add `:not([id])` as well to further narrow.
