### ISSUE TITLE
Integrate "FuckFuckAdBlock"

### ISSUE THREAD

**Issue by zx2c4** [gorhill/uBlock#1098]
https://github.com/Mechazawa/FuckFuckAdblock/

Would be nice to have this built into uBlock Origin.

**Comment by harshanvn** [comment]
I believe it already is. See <a href="https://github.com/gorhill/uBlock/blob/master/assets/ublock/redirect-resources.txt"> uBlock Origin's redirect resources</a>

Only thing is, if a site uses it, a filter needs to be created to re-map it to an benign uBlock's version..

**Comment by gorhill** [comment]
@harshanvn answer is correct.
