### ISSUE TITLE
y.net-games.co.il - Games not loading

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1099]
Please add `@@||2mdn.net/instream/flash/v3/adsapi_3.swf$domain=y.net-games.co.il`.
Make sure you use the latest version of EasyList Hebrew. Problems with this site have been fixed there few days ago.

**Comment by gorhill** [comment]
Works fine here. For example, <http://y.net-games.co.il/game/board/1811/> loaded fine (please provide exact URL next time, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)).

`@@||s0.2mdn.net/instream/flash/v3/adsapi_3.swf$object` is already in _Unbreak_ filter list.

**Comment by IsraeliUser** [comment]
My mistake, sorry.
