### ISSUE TITLE
AdBlock borrowing code from uBlock?

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#110]
Trivial (couple of lines), but still, just because it's amusing to see, I will put this here:

AdBlock CHANGELOG file in its [2.19 release](http://code.getadblock.com/releases/):

```
- Updated the workaround logic to Chrome's reporting fonts as "other" types (#439)
```

Code block added to AdBlock's `background.js` in its 2.19 release:

```
var normalizeRequestType = function(details) {
    // normalize type, because of issue with Chrome 38+
    var type = details.type;
    if (type !== 'other') {
        return type;
    }
    var url = parseUri(details.url);
    if (url && url.pathname) {
        var pos = url.pathname.lastIndexOf('.');
        if (pos === -1) {
            return type;
        }
    }
    var ext = url.pathname.slice(pos) + '.';
    if ('.eot.ttf.otf.svg.woff.woff2.'.indexOf(ext) !== -1) {
        return 'font';
    }
    // Still need this because often behind-the-scene requests are wrongly
    // categorized as 'other'
    if ('.ico.png.gif.jpg.jpeg.webp.'.indexOf(ext) !== -1) {
        return 'image';
    }
    // https://code.google.com/p/chromium/issues/detail?id=410382
    if (type === 'other') {
        return 'object';
    }
};
```

[uBlock's code base](https://github.com/gorhill/uBlock/blob/4f2bd14ce6562f87dc94fa1cc9c7b0b0e4451f6c/platform/chromium/vapi-background.js#L393) -- (from a version somewhere on or after Jan 21, and before Feb 22):

```
var normalizeRequestDetails = function(details) {
    µburi.set(details.url);

    details.tabId = details.tabId.toString();
    details.hostname = µburi.hostnameFromURI(details.url);

    // The rest of the function code is to normalize type
    var type = details.type;
    if ( type !== 'other' ) {
        return;
    }
    var path = µburi.path;
    var pos = path.lastIndexOf('.');

    // https://github.com/gorhill/uBlock/issues/862
    // If no transposition possible, transpose to `object` as per 
    // Chromium bug 410382 (see below)
    if ( pos === -1 ) {
        details.type = 'object';
        return;
    }

    var ext = path.slice(pos) + '.';
    if ( '.eot.ttf.otf.svg.woff.woff2.'.indexOf(ext) !== -1 ) {
        details.type = 'font';
        return;
    }
    // Still need this because often behind-the-scene requests are wrongly
    // categorized as 'other'
    if ( '.ico.png.gif.jpg.jpeg.webp.'.indexOf(ext) !== -1 ) {
        details.type = 'image';
        return;
    }
    // https://code.google.com/p/chromium/issues/detail?id=410382
    if ( type === 'other' ) {
        details.type = 'object';
        return;
    }
};
```

(The pointless last test was removed in a [later release](https://github.com/gorhill/uBlock/commit/37aaeca8aa522011c2db4dea1e4ce5447287fb44).)

**Comment by H4vC** [comment]
These are the things that are bound to happen in an open source project, at least they had the decency of referencing your repo, sort of.

**Comment by gorhill** [comment]
> they had the decency of referencing your repo

Where do you see a reference to the repo here in AdBlock's code?

Anyways, as you say, it's bound to happen, and for such a trivial piece of code there, as said I find it more amusing than anything else.

**Comment by H4vC** [comment]
While the current codebase doesn't seem to contain it (not that I looked very hard), they seem to reference https://github.com/gorhill/uBlock/issues/862 in your snippet, granted they don't reference this code but if I'm not mistaken they do reference the issue that your work-around fixes. (I was unable to check since that url 404s).

Then again if it was blatantly copied I believe it should be mentioned, but as you say it's a trivial bit of code, so it's up to you.

**Comment by GotDemBallsOfSteel** [comment]
Nice find, gorhill.
There is something fishy going over there. "BetaFishy", so to say.
We should all just sit back and watch this (rename thing) unfold.

**Comment by gorhill** [comment]
> they seem to reference https://github.com/gorhill/uBlock/issues/862 in your snippet

The snippet is uBlock's own code, not the AdBlock's one.

**Comment by H4vC** [comment]
Oh god.
Sorry about this. Should've paid more attention, sorry again.
