### ISSUE TITLE
DOM inserted ad not blockable, filter syntax extension required?

### ISSUE THREAD

**Issue by ml31415** [gorhill/uBlock#1100]
spiegel.de recently came up with some hard to block ad. There is an inline JS which adds an image into the DOM a second or so after the page got loaded. The image is served from their own CDN, using the same naming scheme as usual content images, wrapped only into a div with a randomized ID. I couldn't find a way to apply any cosmetic filters here, without blocking intended content.

Filtering any inline-script works in blocking the ad. Though, this breaks some other stuff like the video slider on the page:

    ||*.spiegel.de^$inline-script

What would be required would be a way, to further specify, which inline scripts to filter. Something like:

    ||*.spiegel.de^$inline-script,contains=topPosterInit

Also, they'll probably soon just start to randomize the function names in there, too. So a whitelist mechanism, triggered by some contained words may be even better. It would also be good, to be able to specify the xpath of the script within the document, for being even more specific.

I'm new to the ublock internals, so I beg my pardon, if there is already a way to do that. At least I couldn't find something after an hour of experimenting. Any ideas?

**Comment by gorhill** [comment]
This is blocked properly on Firefox, using [inline script tag filtering](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering). See [_Caveats_](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#caveats) for Chromium-based browsers.

**Comment by gorhill** [comment]
Side note: use `||spiegel.de` instead of `||*.spiegel.de`, the leading wildcard is always implied with the first form.

**Comment by gorhill** [comment]
I figured I can maybe use `redirect` as another solution for these ads. Will experiment.

**Comment by ml31415** [comment]
Thanks for looking into this! I'm indeed on Chromium.

**Comment by dungsaga** [comment]
I see some examples in the code:
* focus.de##script:contains(/uabInject/)
* focus.de##script:contains(uabInject)
* focus.de##script:inject(uabinject-defuser.js)

This should be documented somewhere (to help list maintainer)

**Comment by dungsaga** [comment]
I read commit 1fe5a16 and notice that:
* function `injectScripts` appends scripts to the end of the element `head` (thus, injected scripts are executed after other existing scripts)
* scripts are appended in reversed order

I wonder:
* is it better to adding scripts to the start of `head`?
* is the order of injected scripts important?

**Comment by TonyTough** [comment]
Is it now no more necessary to post here websites that use Addefend and add them in ublocks filter?

runnersworld.de
for example is also a new site that uses Addefend but the ads are already filtered by ublock in Firefox.

**Comment by flyingzebras** [comment]
@gorhill : uBO 1.5.0 release note: "Ability to inject script resource from the resource library directly into a page -- i.e. not through redirection. Can be used to defeat some otherwise hard to defeat ad injection mechanisms on some sites. More specifically, this allows to defeat AdDefend- or Yavli-based ads on many sites (as of writing), which so far were defeated only through inline script tag filtering -- so this means that now Chromium-based browsers can also bypass AdDefend/Yavli (for example, see #1100). Some documentation available here (will eventually create a dedicated page)."

Are AdDefend- or Yavli-based ads defeated by default?


Perhaps that should be mentioned if that is the case.

**Comment by gorhill** [comment]
Not by default, if a site has such ads, it must be reported here so I can add the site to the uBO-specific filter.

**Comment by flyingzebras** [comment]
Why not defeat AdDefend- or Yavli-based globally?

**Comment by gorhill** [comment]
Injecting a js scriplet indiscriminately on all web pages is incompatible with efficiency.

**Comment by flyingzebras** [comment]
@gorhill And it is not possible to inject a JS scriptlet only if AdDefend- or Yavli are detected?

**Comment by gorhill** [comment]
Detection requires specific js script code to run on every page ("specific" = Yavli, AdDefend -- or whatever else surfaces), and even then, if ever detected, it is too late to premptively foil what it is we want to foil.

**Comment by flyingzebras** [comment]
@gorhill Thank you.

**Comment by sp00n** [comment]
finya.de seems to use this as well.

**Comment by okiehsch** [comment]
> if a site has such ads, it must be reported here so I can add the site to the uBO-specific filters.

I don't know if this is still the correct place, if not I will open a new issue at `uBlockOrigin/uAssets`.

The following sites are now using `Addefend` and can be added  to the uBO-specific filters
`cavallo.de,
computerworld.nl,
gusto.at,
hoerzu.de,
landwirt.at,
macwelt.de,
mehr-tanken.de,
planetsnow.de,
profil.at,
testedich.ch,
trend.at,
tv-media.at,
tv-media.at,
woman.at`

The following sites are not using `Addefend` anymore and can be deleted from the uBO-specific filters.
`1erforum.de,
20min.ch,
autoexperience.de,
brigitte.de,
computerbild.de,
fem.com,
flugzeugforum.de,
foot01.com,
gamona.de,
kreatives-wohnforum.de,
lpgforum.de,
mazda-forum.info,
mercedes-forum.com,
modernboard.de,
notebookcheck.*,
teccentral.de,
transfermarkt.de,
unixboard.de,
vermieter-forum.com`

**Comment by gorhill** [comment]
Thanks for the update.

> I don't know if this is still the correct place, if not I can open a new issue at `uBlockOrigin/uAssets`.

Yes, from now on reporting at uAssets would be better.

**Comment by IDKwhattoputhere** [comment]
`lablue.de` and `lablue.at` ([mentioned before](https://github.com/gorhill/uBlock/search?q=lablue&type=Issues&utf8=%E2%9C%93)) sneak ads through too which can be stopped using `##script:inject(uabinject-defuser.js)`. The ads will only appear after you log in so if necessary I can post a login here.

**Comment by okiehsch** [comment]
The situation is indeed similar for `finya.de`, but the filter
`||adternal.com/*/ad-loading.*$image,redirect=3x2-transparent.png`
already prevents ads from being pushed through. 
If you add `finya.de##script:inject(uabinject-defuser.js)`, the `redirect` filter becomes
irrelevant for that site, but the end result remains the same.

**Comment by okiehsch** [comment]
Added `stern.de`.
