### ISSUE TITLE
chrome://extensions will crash when uBO options is clicked

### ISSUE THREAD

**Issue by Tomaku** [gorhill/uBlock#1101]
Steps to repro:

* Navigate to chrome://extensions
* Click uBO options
* uBO options will open in a new tab
* chrome://extensions tab will crash with a Aw Snap message

I didn't discover this bug with other extensions I tested. I think this bug started after the build 1.4.0, I never had this issue with 1.3.3 version.

Chrome Canary 49.0.2599.0 x64
uBlock Original 1.4.0

Update:

I tested 1.3.3 version and it will crash the tab, but only uBO is affected which is weird.

**Comment by gorhill** [comment]
_Aw snap!_ are messages are the browser crashing, report to Chromium devs.
