### ISSUE TITLE
How can I block Google Autocomplete?

### ISSUE THREAD

**Issue by Noexpert** [gorhill/uBlock#1102]
Hi,

I'm on Windows 10, Firefox 43.0.1 and uBlock Origin 1.4.0.
I'm trying to disable Google Autocomplete (this: https://www.youtube.com/watch?v=gBQxZ3ENZJo).

I notice that a similar issue was raised for Duckduckgo (here: https://github.com/gorhill/uBlock/issues/721).

I've tried the filters suggested by the Adblock Plus users, but without any luck:
https://adblockplus.org/forum/viewtopic.php?t=7218
https://adblockplus.org/forum/viewtopic.php?t=7007

Any suggestions welcome.

Thanks

**Comment by yupi2** [comment]
This works fine for me
```
||google.*/s$xmlhttprequest,important
||google.*/complete/search$xmlhttprequest,important
```

**Comment by Noexpert** [comment]
It does indeed.
Thanks for the quick response.
