### ISSUE TITLE
Google autocomplete blocking rules do not work on Firefox mobile.

### ISSUE THREAD

**Issue by Noexpert** [gorhill/uBlock#1103]
Hi,

This is a continuation of this issue (https://github.com/gorhill/uBlock/issues/1102), as I am unable to re-open it.

I'm using the following filters to block Google Autocomplete:

    ||google.*/s$xmlhttprequest,important
    ||google.*/complete/search$xmlhttprequest,important

But it does not appear to work on mobile (Android 5.1.1, Firefox 43.0, uBlock Origin 1.4.0).
The issue is worst on mobile, as users are more bandwidth constrained.

Could someone please replicate and confirm?

Thanks

**Comment by gorhill** [comment]
Please first confirm the issue is with uBO, and not with your filters -- the issue section here is for bugs in uBO.

Use the logger to confirm whether something is not working as expected.
