### ISSUE TITLE
How do I block ads on "local" lastpass vault

### ISSUE THREAD

**Issue by Rava77** [gorhill/uBlock#1104]
How do I block advertising images from my lastpass local vault page, the URL to that is chrome://lastpass/content/home2.xul
I added an rule in "my filters" as this:
https://lastpass.com/images/ads/*
and clicked "Apply Changes", and reloaded the local vault, aka the chrome://lastpass/content/home2.xul page.
All advertising images seem to have the starting URL of https://lastpass.com/images/ads/ so my filter should work, but it does not. The ads are still there and they are annoying, since I force all web pages to have my colour scheme (black background with light text), and the ads are very bright and therefore quite annoying.

I presume this could be because the page is not a remote one, but a kinda local one aka chrome:// one, I tried searching for chrome:// in this very wiki for uBlock origin, but since it is also coded in working as "chrome://", I found too much results to be of any help.

Any tips appreciated.

Another question: Am I right as that there is no official uBlock origin support forum [or sub-forum on an already existing forum), but all support is via the github issue system?

Cheers,
yours Rava

**Comment by gorhill** [comment]
These ads are probably pulled from within the `behind-the-scene` scope. As always, the logger is your best friend in uBO. Open it, then select _All_ in the drop down list -- to see all network requests at once without missing any -- then go through your steps to make LastPass ads occur. See what happens in the logger.

Things to keep in mind: uBO can filter only `http`/`https` network traffic. Also, uBO's cosmetic filtering does not work on anything else then `http`/`https` pages.

**Comment by RoxKilly** [comment]
@Rava77 How do you force all pages to use dark background with light text?

**Comment by alejandrolemus** [comment]
On Firefox those are blocked by a filter in EasyList: .com/ads.

On a side note, I'm starting to dislike LastPass a lot! Ads on the popup even as Premium user (yes, I consider those 'Give the gift of premium' and 'Try Enterprise version' advertisement) and now ads on the vault

**Comment by Rava77** [comment]
@gorhill , the logger tells me this:
inline-script	https://lastpass.com/ads.php

Does that mean I have to block https://lastpass.com/ads.php instead of https://lastpass.com/images/ads/*?

@RoxKilly
Go to Preferences/Contents/ Click the "Colours..." Button. Then select the colours, e.g. black as background, and light green as text, very pleasant for the eyes, also choose lighter than default colours for links and visited links. And then untick the "allow pages to choose their own colours"
But know that on some few pages some buttons are no longer visible, like on phpbb forums, the "edit post" or"reply with quote" buttons are now black on black background, dunno why, it still works when you know where the button is, since hovering with the mouse tells you in the popup which button there is. HTH!

**Comment by Rava77** [comment]
Update
I did block https://lastpass.com/ads.php but the ad still appears.

Now the logger also gives me a 	
frame	https://lastpass.com/ads.php

Should frames not be loaded by default anyway,when they load stuff from 3rd pages?

**Comment by thegoodthings** [comment]
If the page the ads are on is `chrome://lastpass/content/home2.xul`, then you might also need to remove the `chrome-scheme` default entry in your white-list (though this could have other side effects).

**Comment by gorhill** [comment]
I will pass on this one, to difficult to obtain detailed information as requested from OP.

**Comment by alejandrolemus** [comment]
This is what I get by default in my Lastpass vault:

![ublock_lp](https://cloud.githubusercontent.com/assets/9505902/12004024/19c7ab0c-ab07-11e5-9999-457b3567a3cf.JPG)

>Should frames not be loaded by default anyway,when they load stuff from 3rd pages?

If you have the rule "* * 3p-frame block" then yes, but I don't think that works for local resources (chrome://)? Either way, I don't see any adds in my Vault, just a gray area to the right where they were suppose to show.

**Comment by Rava77** [comment]
@gorhill 
"to difficult to obtain detailed information as requested from OP."

I gave you the info you wanted, especially the logger stuff. What did I miss?

@alejandrolemus 
 rule "* * 3p-frame block"

How do I set that?

**Comment by gorhill** [comment]
@Rava77 You just gave me one part of one line:

> `inline-script https://lastpass.com/ads.php`

See [Logger](https://github.com/gorhill/uBlock/wiki/The-logger).

Anyways, someone with a LastPass installation is better placed than me to answer.

**Comment by anewuser** [comment]
That ad isn't displayed if you whitelist only `about-scheme` and block third-party frames. However, @Rava77  doesn't even seem to have taken the time to read the documentation and learn about dynamic rules. It's better for him/her not to edit the whitelist, or he/she won't be able to figure out how to deal with unwanted side effects.

**Comment by gorhill** [comment]
> he/she won't be able to figure out how to deal with unwanted side effects.

Yes, that is pretty much it. Only those who understand how to do it should do it themselves without asking for directions on how to do it here, potential negative side effect has to be the burden of whoever chose to play with more advanced techniques.

**Comment by verum-est** [comment]
Anyone here knows how to block/hide those pesky ads(right side) inside the LastPass' Vault? 

Using Chromebook latest stable version.
uBlock Origin: 1.6.8

Many thanks in advance!

**Comment by anewuser** [comment]
> Anyone here knows how to block/hide those pesky ads(right side) inside the LastPass' Vault? 

@verum-est  Read the discussion above you or buy the premium version of LastPass.

If you want another answer, use the uBlock Origin support forum instead of Github (which is to be used only to report bugs): https://discourse.mozilla-community.org/t/support-ublock-origin/6746

**Comment by Rava77** [comment]
Folks, sorry, I was too busy to check all my forum and support stuff for quite a while. I am back now and to my best to give you the needed info.

@anewuser / post from Dec 26, 2015 
You are right, unfortunately I have not read all the the documentation and did not learn all learn about dynamic rules. 
But I agree with you, I think removing the white list of chome:// is a bit tricky, I don't want to go that way, unless I know how to load and save several versions of uBlock settings (so that I can revert to a known working version any time anything went wrong, for example)
Also, I like uBlock already more than the AdBlockers I used before, it seems so much better and so much more "slim" coded (as in contrast to bloated code, sorry, non native tongue here) so I want to get into it more, but I only have the free time that I do, RL usually comes first...

So, if anyone of you want to give me hints how to prioritize my learning experience, it would be greatly appreciated!

**Comment by anewuser** [comment]
>So, if anyone of you want to give me hints how to prioritize my learning experience, it would be greatly appreciated!
Ask on the [support forum](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by Rava77** [comment]
@anewuser 
That is not worling for me.
When I click Sign Up a new window opens with the info of
| "Click 'Connect' to sign in with Persona.
When I click that, I get the info of 
| Es tut uns leid, aber Ihr Browser wird derzeit nicht unterstützt. 
Translated "We're sorry, but currently your browser is not supported"

Seems that support forum works only for the original Firefox, but I use Palemoon.

I know that I did so far not mentioned that that I run Palemoon, since uBlock & Palemoon work like a charm, but [support forum via discourse.mozilla-community.org](https://discourse.mozilla-community.org/t/support-ublock-origin/6746) is sadly not.

Please tell me where you have your Palemoon support forum. Or a support forum that can accessed via Palemoon. Thanks.

**Comment by RoxKilly** [comment]
@Rava77 uBlock origin allows you to export/import settings from the first page of its settings menu.  Look to the bottom for `Backup to file` and `Restore from file`.  I've used it several times to move my settings from one device to another (Firefox on PC to Firefox on phone/tablet)
![1](https://cloud.githubusercontent.com/assets/12346501/14584624/8e3513fc-041d-11e6-897e-44f6438d1f3b.png)

@anewuser Why threaten to ban people who are not being disruptive or malicious, but who are politely asking for help?  Even if the request is misplaced, I can understand ignoring it once you've referred the person to the right channel, or marking the issue as invalid.  A ban is basically the strongest action (short of legal procedures) that can be taken against a website user. Such a threat has impacts beyond just the people in the conversation.  To anyone curious about the project who reads this board, it sends a message about how we treat people.  I don't know whether you represent uBO, but either way it reflects on the project.

Just my two cents.
