### ISSUE TITLE
Display ads visible

### ISSUE THREAD

**Issue by Bloggerss** [gorhill/uBlock#1107]
Take a look: www.stern.de

![1](https://cloud.githubusercontent.com/assets/11684711/6874763/b811bd7a-d4b1-11e4-92ce-f8f410c5a5cb.png)
![2](https://cloud.githubusercontent.com/assets/11684711/6874764/b887d370-d4b1-11e4-9c5f-788c0987256f.png)
![3](https://cloud.githubusercontent.com/assets/11684711/6874766/bb61a3be-d4b1-11e4-9d55-d0677b90f0f8.png)

A problem of this tool? - Perhaps this helps: https://forums.lanik.us/viewtopic.php?f=90&t=19760
(Sorry, i am not a programmer, dont understand the info)

**Comment by harshanvn** [comment]
It can be blocked by enabling inline script!

See the below picture! (Warning: Enabling Inline Scripting some times breaks a web page functionality)

![ublock inline script](https://cloud.githubusercontent.com/assets/779630/6875015/d01423ec-d4e1-11e4-8073-c57f4b80f9a0.png)

**Comment by gorhill** [comment]
I don't maintain filter lists.

**Comment by Bloggerss** [comment]
i update my filter always and the ads come back - what is new is that there are display ads. on focus.de the same. if i turn inline scripting on the site does not work?? i used ablock plus before and those sites did work?!? perhaps i dont know how to use ublock...

**Comment by gorhill** [comment]
> i used ablock plus before and those sites did work?!?

ABP doesn't block these.

**Comment by tlu1024** [comment]
Try this rule:

`||d1.stern.de/*.gif`

I created it with the Element Picker. Works for me.

**Comment by Bloggerss** [comment]
ABP doesn't block these.

i meant some weeks ago!
i read the german easylist forum, many sites have this problem. Adblocker do not work any longer!

**Comment by Daniellynet** [comment]
@tlu1024 
And that's probably why it isn't blocked by the filter lists. I'd imagine that kind of blocking would be too broad and probably break the site? 
Blocking scripts seems to be the way to go for now.

**Comment by Bloggerss** [comment]
in thread https://forums.lanik.us/viewtopic.php?f=90&t=19760 last post is a link:
www.addefend.com

that it why it is not working any longer. (((

**Comment by gorhill** [comment]
@Bloggerss well there were two proposed solutions above, with their side effects. As far as I am concerned, if I can read articles, it's all fine. Another solution is to stop visiting the site if it comes to the point where the ads are the main purpose and whatever content is just an excuse to throw ads at people.

**Comment by tlu1024** [comment]
@Daniellynet The site isn't broken for me although some other pictures might be blocked, too. Blocking scripts has other negative side-effects. 

Regarding the other site mentioned, www.focus.de, I created those filters some days ago which work well for me:

`||focus.de/*crop*.gif`
`www.focus.de###fancybox-outer`

I don't agree that Adblockers don't work any longer. It's become a bit more difficult on some sites, though. As gorhill said elsewhere, it's a cat-and-mouse game. I have no idea if the filters above will still work in one week or one month. Thankfully, the Element Picker makes it rather easy to create new filters if necessary.

**Comment by Bloggerss** [comment]
@Daniellynet : I have no idea if the filters above will still work in one week or one month. Thankfully, the Element Picker makes it rather easy to create new filters if necessary.

for many unexperienced intenet surfer it may appear as if it is broken. adblockers are so famous because it is a simple solution for everyone by using a central-organized filter. now i have to use a element picker - dont even know what it is or create my own filter. 

what about the following: if we know a site which uses the mechanism above, ublock shows a layer with an explanation how to disable the ads with the element picker (video explanation) and shows other altenative sites, which do not use it (as gorhill mentioned).  so this way the user knows it isnt because of ublock and he can decide what to do.

**Comment by Bloggerss** [comment]
@gorhill: what do you think about the suggestion above?

**Comment by tlu1024** [comment]
@Bloggerss : I'm not gorhill, but still my take on it.

> if we know a site which uses the mechanism above, ublock shows a layer with an explanation how to disable the ads with the element picker (video explanation) 

As far as I can see there is no _specific_ mechanism used but various mechanisms. I don't think that uBlock won't be able to automagically detect them particularly since one must expect that those mechanisms will change over time.

> and shows other altenative sites, which do not use it

I'm puzzled. Really. What do you expect uBlock to become? Do you really expect gorhill to maintain a database of such sites? You must be kidding.

**Comment by Bloggerss** [comment]
@tlu1024:
you are right. it would be a new list. - first entry would be the site which uses these mechanisms, second entry could be alternative sites (or we present a video which explains how the element filter works). maintained by the community. 

lets face it: if nothing happens, many more sites will use that mechanism to make money - the dont care about adblock users. in the end the user will see ads although he is using an adblocker. i am just thinking how to help the general user  to stop this mechanism. but i am not a programmer. 

so anybody having better ideas? 

new sites: www.serienjunkies.com, www.wetteronline.com, www.wetter.com
