### ISSUE TITLE
The global rule is invalid 

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#1110]
##.ad

i.g. https://greasyfork.org/scripts/1317

**Comment by lewisje** [comment]
Does this script add an element with class `ad` or something?

**Comment by gorhill** [comment]
Works fine here:

![a](https://cloud.githubusercontent.com/assets/585534/12000330/8b36ee52-aaa2-11e5-975a-6c5b1110dd39.png)

**Comment by gorhill** [comment]
Closing as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by xinggsf** [comment]
##.ad no work,~zzttzzzz.zzz##.ad is OK!
Thank you!

**Comment by gorhill** [comment]
It works, it's what I used in the screenshot, `##.ad`.
