### ISSUE TITLE
[request] Add regional list and perhaps one multipurpose list

### ISSUE THREAD

**Issue by betterwebleon** [gorhill/uBlock#1112]
Hello!

I have been working on two (mostly cosmetic) filter lists for a few months. Recently, I uploaded them on Github.
1. [Slovenian List](https://github.com/betterwebleon/slovenian-list): it covers a lot of cosmetic and a few tracking filters for Slovenian websites.
2. [International List](https://github.com/betterwebleon/international-list): it covers English and few German websites. It is mostly a cosmetic list.

Could you add Slovenian List to the uBlock Origin's Regional filters (among 3rd-party filters) in the next version? There is no other filter list for this country. Besides, I could say it already covers the majority of popular websites, although it's still growing.

The second list could be placed among uBlock Origin's Multipurpose filters. I'm not sure if it meets your criteria to be placed among them, because it's not so comprehensive. Otherwise I can also add it to your [wiki page](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web).

I hope at least Slovenian list makes it to uBlock Origin, so others will be able to use it if they decide so.

**Comment by gorhill** [comment]
Sure, I will add the first one. The second should go on the wiki page.

There is [an invalid filter in your first list](https://github.com/betterwebleon/slovenian-list/blob/385fcd0c996789eab9a86bfce3152ae1f5e14801/filters.txt#L201):

    www.dominvrt.si##[id*="box_" > .header > .clearfix.headerMiddle > .banner

Probably you meant:

    www.dominvrt.si##[id*="box_"] > .header > .clearfix.headerMiddle > .banner

**Comment by betterwebleon** [comment]
Thank you!
I fixed the invalid filter. I also added the second list to the wiki page.

P.S. Since I probably won't be writing here: I wish you a Happy New Year! :)
