### ISSUE TITLE
No advanced user mode with Firefox 38.5.2 ESR

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#1113]
Switched back to Firefox 38 ESR since a few weeks due to recent FF inflation unbearable by my system (Win XP SP3) - As a simple uBO user (no advanced), I notice only today that the advanced user mode no longer works. The uBO UI popup remain simple, as if I did not activate advanced mode. 

[uBO settings](http://skylonda.aptos.free.fr/capt/ScreenShot01444.png)
[Filters list (1)](http://skylonda.aptos.free.fr/capt/ScreenShot01445.png)
[Filters list (2)](http://skylonda.aptos.free.fr/capt/ScreenShot01446.png)

My first thought was in an issue with uBO 1.5.0**.** I switched back to 1.4.0, then 1.3.6 ... until 0.9.9.0 with no success.
I then disabled all Firefox addons, keeping only uBO enabled, and it does not work better.

After some other investigations, I think it's probably a Firefox 38.5.x issue since I have not seen any recent similar issue in the uBO repo, but I hope you will give me wrong.

(Actual FF version: 38.5.2 - uBO 1.5.0).

**Comment by gorhill** [comment]
Can you provide a screenshot of the popup panel?

**Comment by onestepbeyond** [comment]
![screenshot01447](https://cloud.githubusercontent.com/assets/11029138/12007861/88b970ce-ac18-11e5-8ac8-c29b1d7dcfa6.png)

**Comment by onestepbeyond** [comment]
Nevermind, I just saw the "+" icon in front of "Domaines connectés"
Sorry for the noise!

**Comment by gorhill** [comment]
> It's a recent feature?

Always been like this. For new install, the dynamic filtering pane is expanded by default -- otherwise it remembers whatever state it was last time.

**Comment by onestepbeyond** [comment]
OK. I can confirm that it is not a new installation; I had recovered an old profile which already contained uBO when I switched to FF 38.
My bad, I had never paid attention to these "+".
