### ISSUE TITLE
Using Ublock with Avant Browser, Dashbord not opening.

### ISSUE THREAD

**Issue by neoatomic** [gorhill/uBlock#1115]
First i would like to thank the developers for providing us with this nice Adblocker. 

I tried using Avant Browser in combination with Ublock, but run into some issues.
http://www.avantbrowser.com/download.aspx
(Avant browser supports IE/FF/Chrome engines and has some extra features on top of those.)

So when i use the FireFox engine and install Ublock, i cant access the dashboard of Ublock under the firefox addons section. If i push the Dashboard button noting happens. That is preventing me from making any changing to the  settings etc.
When you find some time, could you see if you could find a solution so that its accessible in Avant Browser.?

Ublock is working fine for the rest, also can block Eliments on a page. Just the Dashboard GUI part is not. Probbebly du to the fact Avant Browsers puts another Theme on top of FireFox.

**Comment by gorhill** [comment]
I will let somebody else take this one.

**Comment by AlexVallat** [comment]
That has got to be one of the most horrible browsers I've tried to test under. Terrible performance, and somehow even manages to make mouse movement choppy, which is impressive.

Anyway, if you need to get at the dashboard you can navigate to chrome://ublock0/content/dashboard.html using the Firefox rendering engine and it at least loads.

**Comment by gorhill** [comment]
Ok, whatever Avant browser is, this project here does not officially support it. If someone investigate and provide a trivial fix, I may agree to import it.
