### ISSUE TITLE
"Continuar" button doesn't work with Ublock

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#1116]
Web Browser: Firefox 43
Platform: Win 7 X86
Ublock Origin 1.5.0, default settings

Steps to reproduce: 
1.- Open this URL with Firefox https://wbc1.burodecredito.com.mx:543/RceOnline/index.html
2.- Clic on "Continuar"

Actual results:
1.- "Continuar" button doesn't work

Expected results: 
1.- After clic on "Continuar" Firefox should display the next page.

Note
- If you uninstall or disable Ublock origin the button works normally.
- Same problem with Chrome

Sorry for my poor English

**Comment by gorhill** [comment]
Force an update of _Unbreak_ filters from the dashboard (purge the cache of _Unbreak_ if uBO does not detect there is a new version).
