### ISSUE TITLE
Inconsistent behavior when committing user rules to memory

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#1117]
Generally, when a user changes a dynamic filter, the change is temporary. To commit to memory, the user has to press the LOCK icon in the uBO panel.

An unexpected exception to this behavior occurs with whitelisting fonts.  To replicate:
1. add `no-remote-fonts: * true` rule, save it and restart the browser.
2. Go to any website that uses remote fonts (eg: [github](https://github.com) or [wikihoops](http://wikihoops.com/))
3. Expand the uBO panel and click the Fonts-blocked icon (bottom right corner) to enable fonts.
4. Refresh the page. At this point I would expect the change to be only temporary with the usual UI options to lock-in and clear the change, but instead the change is committed and will in fact survive a browser shutdown.

Firefox 43 on Windows 7 x64
uBO 1.4.0 and 1.5.0 both affected

**Comment by harshanvn** [comment]
> Generally, when a user changes a dynamic filter, the change is temporary

This is true. However the switches present on the popUI aren't.
This is expected behavior. Any change done to these switches will save directly.

**Comment by RoxKilly** [comment]
If this is the expected behavior, it leads me to ask: why the different approaches?  Why take the position that users' changes in parts of the panel are temporary until the user actively "locks" them in, but elsewhere within the same panel take the opposite position?

**Comment by gorhill** [comment]
The padlock applies only to dynamic filtering and url filtering rules, everything else is sticky. I will not make the basic panel more complicated for non-advanced users by introducing a padlock/eraser somewhere in there (assuming I could make these buttons fit), that leads to the UI more complicated, requiring more explaining, etc. I want to keep the UI of the basic panel simple.

**Comment by gorhill** [comment]
Will try to think of something, which requirements will be:
- Not having to go through padlock (available only in advanced user mode)
- Keep the current behavior by default -- to not force users to change their habits.
    - Possibly: a modifier key to force a temporary rule only.
- Need to think of a UI representation for temporary rule.

**Comment by Kees1958** [comment]
Sorry posted my UI-suggestion for a clean implementation (not affecting user experience in simple mode or users not having enabled the suggested option in advanced mode) in the issue I opened. Do you (@gorhill) want me to close that on and continue here?
