### ISSUE TITLE
uBlock Pro should be added as a fork

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1119]
Please add uBlock Pro: https://chrome.google.com/webstore/detail/ublock-pro/fmaicbnbcbjgbpecclcnaehmbpjpdane?hl=en to the page of uBO forks. I forgot where it is located.

**Comment by gorhill** [comment]
I removed the wiki page.

**Comment by 5t3f4n** [comment]
>I removed the wiki page.

@gorhill you may want to remove the link from the [wiki](https://github.com/gorhill/uBlock/wiki). It's the second last link.
