### ISSUE TITLE
Firefox: Popup user interface doesn't display if url bar is disabled. 

### ISSUE THREAD

**Issue by dylanaraps** [gorhill/uBlock#112]
I've moved my extension icons into the tab bar and disabled my url bar. As you can see in the screenshot below I've got a few icons on the bar. Noscript and Self destructing cookies both dispaly their Ui's on click while ublock's ui fails to display. 

![2015-04-24-150031_1581x66_scrot](https://cloud.githubusercontent.com/assets/6799467/7312710/cab7f460-ea93-11e4-9351-cff381077c10.png)

If I re-enable the url bar the popup interface works again. I'm disabling the url bar with **display: none;**

All ublock settings are default and It happens on the newest release and newest pre-release.

**Comment by WyohKnott** [comment]
I can't reproduce because I can't see any option to move the URL bar and the Hamburger menu, nor actually remove that bar? Are you using an additional extension to achieve that?

**Comment by therealvdeadline** [comment]
You edit userChrome.css or use an extension such as Stylish to set #nav-bar to display: none; like so.

#nav-bar {
  display: none !important;
}

**Comment by WyohKnott** [comment]
Ok, you're doing it that way (I'm using stylish too, [shameless self promo](https://userstyles.org/users/244853)). And indeed it does not display, but if I connect to the chrome url of the popup ( chrome://ublock0/content/popup.html ), I can see that at least it does get populated. I don't know if that's of any help.

**Comment by therealvdeadline** [comment]
Found two issues in Chris' fork related to this and there's a temp fix for the stylish css in the first link.
https://github.com/chrisaljoudi/uBlock/issues/549
https://github.com/chrisaljoudi/uBlock/issues/720

I'll try out the fiz in the first link and report back.

**Comment by WyohKnott** [comment]
I'd class this as NOTABUG personally. 
The µBlock popup is added to ```PanelUI-multiView```

```javascript
vAPI.toolbarButton.onBeforeCreated = function(doc) {
    var panel = doc.createElement('panelview');
    panel.setAttribute('id', this.viewId);

    var iframe = doc.createElement('iframe');
    iframe.setAttribute('type', 'content');

    doc.getElementById('PanelUI-multiView')
        .appendChild(panel)
        .appendChild(iframe);
```
… which is a child of PanelUI-popup, which contains many others default Firefox popup:
![dom inspection](https://cloud.githubusercontent.com/assets/6247191/7316191/33f8c7b6-ea75-11e4-85aa-4d48958581c4.PNG)

I didn't look into Firefox code but I assume that PanelUI-popup is added as a child of #nav-bar at some point, because it is assumed that #nav-bar is always present/visible. All other official popups on the list above won't work if you do that: I've tried History, Bookmarks… basically hiding the #navbar is breaking basic Firefox functions. Therefore I don't think it's a µBlock side that needs fixing, if you really want this, I think you should look into why all PanelUI-popup popups are not displayed when #urlbar is hidden.

NoScript is not a popup, but a simple menu. SDC is a panel but is created using the entire Addons SDK that µBlock is not using. I assume the Addons SDK is not placing the panel inside PanelUI-popup and thus is not affected by the hiding of #urlbar.

**Comment by WyohKnott** [comment]
Okay, I think I've found a hint from where it's coming, it's not related to where the popup is attached (I've changed PanelUI-popup to mainPopupSet, like where the AddonSDK is attaching its popup), but if the popup is compatible with the Menu Panel: all popups that have a sliding menu in the Menu Panel seems affected. I think they are calling this "CustomizableUI"

```
    // In Australis, widgets may be positioned in an overflow panel or the
    // menu panel.
    // In such cases clicking this widget will hide the overflow/menu panel,
    // and the widget's panel will show instead
```
(from the SDK https://github.com/mozilla/addon-sdk/blob/master/lib/sdk/panel/utils.js )

**Comment by WyohKnott** [comment]
Okay so after using the debug console to retrace the Panel initialisation step by step, here what I've found.

https://github.com/mozilla/gecko-dev/blob/master/browser/base/content/browser.css#L116
```css
panelview:not([mainview]):not([current]) {
  display: none;
}
```
 The panelview is hidden if it has not the attribute ```mainview=true```, which is set by the constructor of ```panelmultiview``` here : https://github.com/mozilla/gecko-dev/blob/master/browser/components/customizableui/content/panelUI.xml#L148

```panelmultiview``` is constructed when ```showsubview``` is called (i.e. when we want to display our popup). But in this function, our panel is added to the ```#nav-bar``` ( i.e. ``` CustomizableUI.AREA_NAVBAR``` in the code)  which is hidden:
https://github.com/mozilla/gecko-dev/blob/master/browser/components/customizableui/content/panelUI.js#L336

```javascript
      document.getElementById(CustomizableUI.AREA_NAVBAR).appendChild(tempPanel);
      // If the view has a footer, set a convenience class on the panel.
      tempPanel.classList.toggle("cui-widget-panelWithFooter",
                                 viewNode.querySelector(".panel-subview-footer"));

      let multiView = document.createElement("panelmultiview");
      multiView.setAttribute("id", "customizationui-widget-multiview");
      multiView.setAttribute("nosubviews", "true");
      tempPanel.appendChild(multiView);
```
Somehow (I'm not sure why yet), appending ```tempPanel``` to the hidden ```#nav-bar``` prevent ```panelmultiview``` to be constructed correctly.
By replacing ```CustomizableUI.AREA_NAVBAR``` with ```CustomizableUI.AREA_TABSTRIP``` in the previous function, I was able to display the popup correctly even with the ```#nav-bar``` hidden.

**Comment by gorhill** [comment]
@WyohKnott I see at [the link you mention](https://github.com/5digits/dactyl/issues/28) that privacy Badger works fine without the URL bar. Doesn't this confirm that the problem is in uBlock?

**Comment by WyohKnott** [comment]
No. The Privacy Badger uses the Addon SDK to create its UI, while µBlock Firefox code was created without the SDK but only as a bootstrapped extension (Read on here: https://blog.mozilla.org/addons/2014/06/05/how-to-develop-firefox-extension/ ).  I think the extensions built with the Addon SDK are not subject to this bug because the SDK is not using CustomizableUI to create its toolbar buttons and panels.

**Comment by wavexx** [comment]
I'm also affected by this issue when using pentadactyl. Note that the suggested solutions often mention setting ``* #nav-bar * { visibility: visible; }`` as a work-around, but they introduce several nasty focus issues.

In several circumstances the url-bar gets focused even though it's nested in a hidden element. This will cause keystrokes to get sent to the url-bar causing the autocompletion popup to show in unexpected ways, basically breaking pentadactyl and similar extensions entirely.

As a "better" workaround, couldn't ublock set temporarily the visibility of nav-bar when clicked, and then restore the original value when the popup is successfully constructed/shown? This would at least prevent the nav-bar focusing issues, as there's little chance this will be looked up upstream.

**Comment by lucianposton** [comment]
Another workaround is enabling the legacy toolbar button by setting `extensions.ublock.forceLegacyToolbarButton` to true in about:config.

**Comment by pmaziere** [comment]
@lucianposton it works great, thanks ! 
I did not have a clue about this setting before. Was it documented somewhere or did you just dig into the source code ?

**Comment by polyzen** [comment]
@lucianposton, I've had this enabled, but it still doesn't show. Pretty sure this works in chris/ublock

**Comment by wavexx** [comment]
Just tested, and indeed using ``extensions.ublock.forceLegacyToolbarButton`` works wonderfully even when the button is dragged in the addon bar.

**Comment by timss** [comment]
Using `* #nav-bar * { visibility: visible; }` I've been able to fix the same issue with uMatrix with Vimperator. 

While 'forceLegacyToolbarButton' does seem to be a thing in uMatrix it does not seem to have the same effect though. Changing it didn't change much.

https://github.com/gorhill/uMatrix/blob/6fdbf9dd9465484281fad14f06af93acf1627835/platform/firefox/vapi-background.js#L2098

https://github.com/gorhill/uBlock/blob/7d9525d6e91f3cb0ae3f868855d342769df17be2/platform/firefox/vapi-background.js#L2328

The function is the same, but I can't tell if the surrounding environment is the same so it should work as is with uMatrix as with uBlock. I might be able to test it further on another install where I use uBlock+Vimperator later.

**Comment by polyzen** [comment]
Removing "set! extensions.ublock.forceLegacyToolbarButton=true" from my .pentadactylrc resolved my issue. Now extensions.ublock0.forceLegacyToolbarButton works

**Comment by timss** [comment]
After giving it another shot with a proper restart and comparing it to a fresh profile I found out that it indeed did work after all even with vimperator. 

This issue should probably be closed now, at least if you're able to confirm it as well @dylanaraps

**Comment by dylanaraps** [comment]
Seems to work for me too, I'll close the issue.

**Comment by wavexx** [comment]
I would mention the work-around more prominently though before blindly closing the report.
