### ISSUE TITLE
[Firefox] Won't block requests when moving a tab to a new window

### ISSUE THREAD

**Issue by g3939434** [gorhill/uBlock#1120]
uBlock Origin v1.5.0, Firefox v43.0.2
1. Open 2 new tabs and the logger
2. Visit https://www.yahoo.com/ in the first new tab and trackers, e.g. `analytics.yahoo.com`, are blocked and showed in the logger
3. Move the first tab to a new window
4. Trigger the trackers by any means, i.e. hover links
5. Trackers are not blocked unless reloading the tab

**Comment by gorhill** [comment]
For the new tab, `locationChangedListener` is called with an `about:blank` URL, and then no further events, so uBO is not aware that the tab's location has changed, that it is not really `about:blank`.

**Comment by BenjaminProgram** [comment]
@gorhill Would it be possible to apply the base settings to behind the scenes requests?

**Comment by gorhill** [comment]
Please, read the wiki -- the issue tracker is [not a bulletin board](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Can't reproduce the issue with the webext version of uBO. Convernin the legacy version, this is a browser bug, the browser fails to fire proper LocationChangedListener event.

**Comment by reallyuniquename** [comment]
Hey @gorhill, are there any updates on this issue? 

I am on latest Firefox 52 and uBlock legacy, took me a while to figure out why I get youtube ads sometimes. Apparently moving tab between windows disables uBlock on it.

**Comment by harshanvn** [comment]
> are there any updates on this issue?

As seen in the above comment by Raymond. This is a browser issue, when concerning the legacy version.
I see no point in trying to hunt down and fix for legacy browsers..
