### ISSUE TITLE
Element Picker Rule

### ISSUE THREAD

**Issue by bytos** [gorhill/uBlock#1121]
This rule generated by the element picker doesn't work:

sputniknews.com##.m-clear.l-wrap > .l-sidebar > .b-tabs.b-block:nth-of-type(5)

Names of the classes are:

l-wrap m-clear
l-sidebar
b-block b-tabs

These rules don't work:

sputniknews.com##.l-wrap.m-clear > .l-sidebar > .b-block.b-tabs
sputniknews.com##.l-wrap.m-clear > .l-sidebar > .b-block.b-tabs:nth-of-type(5)

**Comment by gorhill** [comment]
There is no `.m-clear` element on the page:

    > document.querySelectorAll('.m-clear');
    > []

**Comment by bytos** [comment]
FOLLOW US (FACEBOOK) - this is on the right column (using FF's Inspect Element)
<div class="l-wrap m-clear">
  <div class="l-sidebar">
    <div class="b-block b-tabs">

Facebook.net is blocked globally, but 3rd party scripts/frames allowed for this site.

**Comment by gorhill** [comment]
If the filter does not work it's because it doesn't match anything on a page. I still do not know:

- Exactly what URL you are using for this issue.
- What exactly on the page you are trying to remove.

**Comment by bytos** [comment]
Go to http://sputniknews.com/ and select any news, for example:
http://sputniknews.com/middleeast/20151227/1032365363/iraq-us-daesh-ramadi.html

I can remove the box using the picker, but is only temporary, if you refresh the page the box is back.

![s1](https://cloud.githubusercontent.com/assets/16452541/12010698/f0eb7f1a-ac87-11e5-8e43-58e4c572904a.png)
![s2](https://cloud.githubusercontent.com/assets/16452541/12010699/f0ed6ad2-ac87-11e5-865b-e48e37d18fe2.png)

**Comment by gorhill** [comment]
> for example:
> http://sputniknews.com/middleeast/20151227/1032365363/iraq-us-daesh-ramadi.html
> if you refresh the page the box is back.

Ok, I removed the widget using the picker:

    sputniknews.com##.m-clear.l-wrap > .l-sidebar > .b-tabs.b-block:nth-of-type(5)

When I refresh the page, that widget no longer show up, it's gone for good, including on other articles:

![a](https://cloud.githubusercontent.com/assets/585534/12010722/3bbbae14-ac80-11e5-905d-e27f12918166.png)

Do you have any other extensions that could be interfering with the DOM layout?

**Comment by gorhill** [comment]
Any [of the following](https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappear-when-you-reload-the-page) applies to your case?

**Comment by bytos** [comment]
Only using uBlock Origin addon to block ads, plus disabled all other misc addons in Firefox v43 to test, the box is still there, even copying and pasting your rule, which seems to be the one created automatically by the picker.

These are My Rules:

! Sputnik News
sputniknews.com##.l-dark
sputniknews.com##body > .m-oh.l-wrap:nth-of-type(13) > .l-sidebar
sputniknews.com##.footer > .m-oh.l-wrap
sputniknews.com##.m-clear.l-wrap > .l-sidebar > .b-tabs.b-block:nth-of-type(5)
! sputniknews.com##.m-clear.l-wrap > .m-static.l-maincolumn > .b-article > .social-likes1
sputniknews.com##.m-clear.l-wrap > .m-static.l-maincolumn > .b-article > .social-likes1 > .gplus.social-likes1-item
sputniknews.com##.m-clear.l-wrap > .m-static.l-maincolumn > .b-article > .b-article__likes
sputniknews.com##.m-clear.l-wrap > .m-static.l-maincolumn > .b-article > .comments
sputniknews.com##.m-clear.l-wrap > .m-static.l-maincolumn > .b-article > .b-article__refs > .b-article__refs-list:nth-of-type(3)
sputniknews.com##.m-clear.l-wrap > .l-sidebar > .b-tabs.b-block:nth-of-type(5)

![s4](https://cloud.githubusercontent.com/assets/16452541/12010753/b23fe718-ac89-11e5-8514-e802ef503a0e.png)

**Comment by gorhill** [comment]
The problem is your `allow` rule for `sputniknews.com`, this disables cosmetic filtering for the site. What is the reason for this rule?

**Comment by bytos** [comment]
Trying to find an example, I believe it had to do with a photo slide-show they use in some articles, or maybe videos (not just Youtube).

Must be since I have not set anything else to allow so far, except on this site.

**Comment by gorhill** [comment]
Given this has happened in the past, I am tempted to remove this behavior of `allow` rule on 1st-party domain causing the disable of cosmetic filtering, given that now there is a dedicated switch for this.

Not sure how this could affect negatively some users who rely on that behavior -- I doubt many (if any) users purposefully want that behavior -- and in any case, the workaround would be to use the cosmetic filtering switch.

I will re-open and use this issue as the rationale to remove this behavior -- it was implemented when there was no other way to disable cosmetic filtering.

**Comment by bytos** [comment]
I was thinking that I can simply allow the specific element as a static rule, I'm new to uBlock and back then didn't know much so probably that's the reason I allowed all scripts in that site.

**Comment by bytos** [comment]
This is a line in the logger that could be related:

12:47:33		/adriver.$script	--	script	http://cdn1.img.sputniknews.com/js/libs/adriver.core.2.js?4119577162

![s6](https://cloud.githubusercontent.com/assets/16452541/12011127/ae87ac8c-ac98-11e5-9d50-43b6448c523b.png)

**Comment by bytos** [comment]
Got it working by removing all rules and redoing the rules, but now I can't get the Follow Us to disappear and I'm not allowing all from the site

**Comment by mitalie** [comment]
This (sort of) breaks the use case of blacklist mode as described in https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except
Having to click the cosmetic filtering button defeats the purpose of allow-by-default.

I can work around this with "no-cosmetic-filtering: * true", but this means that I need to have double rules for blacklisted sites if I still want to use cosmetic filtering on them; "no-cosmetic-filtering: badsite.net false" and "badsite.net * * noop". Is this the price I have to pay for blaclist mode, or could this be improved? For example, would it be feasible to add cosmetic filtering as a type alongside image, 3p-frame, etc. so that a global cosmetic filtering disable(allow) would be overridden by the site specific noop rule?

**Comment by gorhill** [comment]
> would it be feasible to add cosmetic filtering as a type alongside image, 3p-frame, etc.

"Blacklist mode" was never intended to be officially supported, it's a side-effect of how dynamic filtering pane works. The majority of people who install uBO do so for it's block-everywhere-whitelist-exceptionally mode, not it's allow-everywhere-block-exceptionally mode.

Disabling cosmetic filtering when creating an allow rule for the current site was causing more unexpected results, the issue here was not an isolated case.

Just an idea, I need to think more about it: if I bring back the former behavior, but **only** for when the `all` cell is set to `allow`, would that work for you?

**Comment by mitalie** [comment]
Yes, that would work for my use case.
