### ISSUE TITLE
Can't Import my data from the Cloud storage

### ISSUE THREAD

**Issue by ZIEXED** [gorhill/uBlock#1123]
I have closed the browser and deleted the ublock0.sqlite file in myprofile/extension-data
then I started my browser again And turned on "Enable cloud storage support"
but I can't import my data
of course the sync feature is working on my Firefox browser
clicking on the export button on whitelist tab has overwritten my old data as I expected
but I don't care about the whitelist data
How can I restore my filters\rules\3pfilters data?

![capture](https://cloud.githubusercontent.com/assets/14824755/12010774/9219b9cc-acbc-11e5-8a35-d9a3b995f1c5.JPG)

last thing
if I added /ads/ how to exclude /loads/ and /threads/ from that filter?
Any help is appreciated

**Comment by gorhill** [comment]
Did you also delete uBO-related entries in `about:config`?

**Comment by ZIEXED** [comment]
No I didn't

**Comment by gorhill** [comment]
What version of Firefox are you using?

**Comment by ZIEXED** [comment]
I'm using the latest stable version 43.0.0.2

**Comment by gorhill** [comment]
According to the [bug #753289 entry](https://bugzilla.mozilla.org/show_bug.cgi?id=753289), the cloud storage issue in FF was fixed in 43.3:

> 43.3 - Sep 21

**Comment by ZIEXED** [comment]
I think I will build my filters again from scratch
what about my Q :)

**Comment by gorhill** [comment]
> if I added /ads/ how to exclude /loads/ and /threads/ from that filter?

Why not just `/ads^`?

**Comment by ZIEXED** [comment]
I need to know how to block any URL contain "ads" except for those two words
like https://www.facebook.com/business/products/ads
https://www.facebook.com/about/ads/
http://adsoftheworld.com/
and so on
/ads^ won't work for that
