### ISSUE TITLE
gaytube.com problem uBO 1.5.0

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1125]
For http://www.gaytube.com/media/901702/boyhous_gets_us/ with "all" local rules set to accepted I still get this message:

html5: Video not properly encoded

http://cdn.public.gaytube.com/media/201412/17/bdf051d2a74cab760735e236ddb38148d913a910/480P_448k_52f854773c8e4a101a044927c490b87b8fcc576f.mp4?nvb=20151225171004&nva=20151229171004&hash=0c082b3372d4ba8c8a792

The video works as expected when I turn of uBO.

**Comment by flyingzebras** [comment]
@gorhill Using IceCat 38.5.2 for GNU/linux: https://ftp.gnu.org/gnu/icecat/38.5.2/

**Comment by gorhill** [comment]
> with "all" local rules set to accepted

What does that mean exactly?

**Comment by flyingzebras** [comment]
@gorhill This appear to be a website problem, I get the same error now even with uBO turned off.
