### ISSUE TITLE
pornhub.com userABMessage

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1126]
Can you please add userABMessage seen in pornhub.com to your JS injection part of your block defeat arsenal?

It shows this message: "Looks like you've enabled AdBlock. Ads suck. Why don't you try the new Premium? It has everything you know and love but with 1080p, full-length videos and NO ADS."

**Comment by gorhill** [comment]
This is at most an annoyance, and this is can be taken care by 3rd-party filter list -- there is nothing which requires uBO specific filter syntax.

**Comment by flyingzebras** [comment]
userABMessage is JS.

**Comment by lewisje** [comment]
Even so, you can block certain resources and that should do the trick; you don't need to re-create a dummy API the way you might if you block, say, Google Analytics and then sites stop working.

**Comment by flyingzebras** [comment]
@lewisje How do I block userABMessage with uBO?

**Comment by LimboSlam** [comment]
@flyingzebras: This is what I use:

  ! Monday, December 28, 2015 12:43:41 PM http://www.pornhub.com/
www.pornhub.com###abAlert > .abAlertInner

And I did using the element picker.

**Comment by flyingzebras** [comment]
@LimboSlam, @lewisje Added in https://github.com/reek/anti-adblock-killer/issues/887

**Comment by flyingzebras** [comment]
pornhub.com###abAlert added to [Anti-Adblock Killer | Reek‎](https://github.com/reek/anti-adblock-killer/commit/3702f510379d36e8cadb73bd4cf21564177770c6), 6 Jun.
