### ISSUE TITLE
domain option is ignored

### ISSUE THREAD

**Issue by nick75e** [gorhill/uBlock#1127]
Hi!
I have these rules in my filters:
`||twimg.com^$domain=~twitter.com,important`
`||fbcdn.net^$domain=~facebook.com,important`
`||instagram*.akamaihd.net^$domain=~instagram.com,important`

They used to block connections unless on twitter, facebook or instagram.
But since 1.5.0, uBlock0 blocks them even on these sites.
![the logger](https://cloud.githubusercontent.com/assets/10011516/12011701/1f5b2138-acd9-11e5-99a3-9a2f2917ae3d.png)
I have to allow them with dynamic filtering.
Can you please help me?

Linux Mint 17.3, Firefox 43

**Comment by gorhill** [comment]
Can you confirm the fix using 1.5.1rc0? If you confirm, I will push an update to AMO.

**Comment by nick75e** [comment]
yes, it works.
Thanks!
