### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1128]
hi. i was just wondering is it possible to block the urls below with the experimental filters list? the first and second urls are unblocked on opendns.com by two exception filters.

https://ssl.google-analytics.com/ga.js
https://www.google-analytics.com/plugins/ga/inpage_linkid.js

if you login with this email and password and go to this link you will see the urls that are whitelisted in the logger.

email: test@yhg.biz
password: Password123@

**Comment by gorhill** [comment]
Sorry, I won't login to accounts which are not mines.

**Comment by gorhill** [comment]
You can try for yourself if this works using:

`||google-analytics.com/ga.js$script,redirect=www.google-analytics.com/ga.js,important`

That is the same as the one in the _Experimental_ filter lists, except I removed teh leading `www.`. See if this works.
