### ISSUE TITLE
Add keyboard shortcut for opening the Network-Request-Log

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uBlock#113]
Hi, gorhill. I know you're not big on feature requests. But I'm throwing this out there in case you're receptive.

Please add a keyboard shortcut for opening the Network-Request-Log. Something along the lines of CTRL+SHIFT+V or CTRL+SHIFT+U.

Thanks much.

**Comment by lewisje** [comment]
`Accel+Shift+U` is better, because it won't override the shortcut that some Webmail providers (like GMail and Hotmail) use for "Paste Without Formatting" (I said this in the analogous issue in chrisaljoudi's repo): https://github.com/chrisaljoudi/uBlock/issues/1303

**Comment by Snapy** [comment]
@gorhill @vdcbb  You can close the PR now that it has been implemented.

**Comment by gorhill** [comment]
It will be opened again, the shortcuts are not implemented for the non-webext version of uBO for Firefox. I looked into it a bit, it does not appear trivial.

**Comment by Snapy** [comment]
You could add a big warning in the release notes or in the docs. Anyway, "normal" users will be forced by the end of the year to use the webext version. Plus commands is supported [since Firefox 48](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands) so users on ESR 52 and uBO webext should be able to use the keyboard shortcuts.

**Comment by TPS** [comment]
@Snapy A lot of "normal" users are on Ff alternatives _because_ of Mozilla regularly re-abandoning their userbase with things like forcing Australis & WebExt.  We appreciate @gorhill improving our versions, as well.

**Comment by F-DK** [comment]
@gorhill Not cool 👎 , whenever and wherever I try to add an "@" sign into any input field/ form (with: cmd+alt+L) it opens the log in a new tab — I don't see any option where/how to change this. I'd be happy if I knew where to change this.

Context: current macOS Sierra with Chrome.

**Comment by gorhill** [comment]
See [Release notes for 1.13.2](https://github.com/gorhill/uBlock/releases/tag/1.13.2) please.

**Comment by gorhill** [comment]
I added a note in the _Release notes_ for those who like you feel the need to thumb down because of such issue:

> **P.S.:** Such an issue should never have made it to the release version. The fact that it did means nobody is testing the dev build, or nobody using the dev build reported the issue. It's completely unrealistic to expect me alone to find all such issues. Given the nature of this project, you will have to accept for such quirks to happen when nobody is willing to contribute by using the dev build and reporting such issues. TL;DR: Contribute by installing and using the dev build.
