### ISSUE TITLE
BUG:The global DOM rule

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#1130]
###ggPar,#side-ad,#preAdContent,.ad
The rule (.ad) no works!  
i.g. https://greasyfork.org/scripts/1317
Now two rule :
###ggPar,#side-ad,#preAdContent
##.ad

**Comment by gorhill** [comment]
Works from here:

![a](https://cloud.githubusercontent.com/assets/585534/12025927/953f7856-ad81-11e5-94ee-db457a5de1d9.png)
