### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by trevor122** [gorhill/uBlock#1132]
please make release of ublock origin for latest safari or add to wiki some tutorial how to add it manually

thank you

martin

**Comment by zummuz** [comment]
https://github.com/gorhill/uBlock/issues/999#issuecomment-160972800

**Comment by lewisje** [comment]
Before I read that comment, I was about to try to find a used MacBook that was still new enough to run El Capitan, just so I could port uBlock Origin to Safari; I guess instead, if you're stuck on an older version of Safari, just use ABP, if you're stuck on Safari 5, find an early version of AdBlock for Safari (the one with the logo with the hand in the stop sign), and if you're stuck on Safari 4 for Mac, you might still be able to find the old ad-blocking WebKit extension.

**Comment by sammcj** [comment]
+1 even though its closed, I just find firefox and chrome too unreliable to use.

**Comment by Hrxn** [comment]
I have something of interest for you:

HP: http://jsblocker.toggleable.com/
GH: https://github.com/infernoboy/JavaScript-Blocker-5

It is not exactly the same kind of blocker, judging from my quick glance, so don't expect to just import EasyList with a simple click or something, I guess.
But it might be a good start..
