### ISSUE TITLE
Rename "Adblock Warning Removal List" to "EasyList Adblock Warning Removal List"

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1134]
In 3rd-party filters there is a filter titled "Adblock Warning Removal List". This is misleading, I contacted "Adblock Warning Removal List" after a suggested filter was rejected by EasyList, and they asked why I asked them again. I would not have done it if it was labeled "EasyList Adblock Warning Removal List".

**Comment by gorhill** [comment]
I use whatever title in in the list, and the support URL links to EasyList, and the list itself contains all the information about where to find support.
