### ISSUE TITLE
Settings reset after quiting or restarting Firefox

### ISSUE THREAD

**Issue by Morac2** [gorhill/uBlock#1137]
Any changes I make to settings in the Dashboard are lost after Firefox (43.0.3) quits or restarts.  I've had this problem since installing uBlock many months ago, but finally got around to reporting it as it's very annoying.

I tested this in a brand new profile with no other addons installed and the same thing happens.  

I haven't been able to figure out where uBlock stores it's settings, but it doesn't appear to be using the default prefs.js file.

Edit: 

I found the ublock0.sqlite file which has a settings table in it, though I don't see any of the actual user changeable settings in that table.

**Comment by Morac2** [comment]
Okay this is weird.  I used an SQLite viewer to view the ublock0.sqlite file and saw that the settings were being set there in fact, but only when I was using the viewer.  When I first opened the sqlite file there were no settings in the ublock0.sqlite file.

Once the settings got set, they appeared to stick.

I have no idea why I needed to use a SQLite viewer (SQLite Manager addon) to get the entries in the settings table in the ublock0.sqlite file to be inserted.  I tested this in two profiles.  It's not related to using the SQLite Manager addon though since I used it in one profile to view the ublock0.sqlite file in another.

**Comment by gorhill** [comment]
> I have no idea why I needed to use a SQLite viewer

You should not need to. There is no known issue regarding settings not sticking, so there is likely something specific on your side causing the issue, and best is you investigate it, there is not much I can do from a distance.

**Comment by Morac2** [comment]
uBlock has forgotten it's settings again and reverted back to the default settings.

I'm not sure why it would be something specific to my setup considering I've reproduced this problem in Firefox 43.0.3, with two different profiles, including a newly created one, so it's not an addon conflict or anything else profile related.

I'm not sure how to investigate this since the problem seems to be in the uBlock add-on itself.  I don't have a problem with any other add-on or Firefox forgetting settings.

**Comment by gorhill** [comment]
Antivirus? Sandboxie?

> I used an SQLite viewer to view the ublock0.sqlite file and saw that the settings were being set there in fact, but only when I was using the viewer

The SQlite is accessed through a standard FF API. See if something else on your computer is somehow locking its accessed. uBO will still work fine even if the databse file is not accessible, it will just not be able to save its settings. If the database file is not accessible when uBO tries to use it (see browser console message), then something else on your computer is doing this.

**Comment by Morac2** [comment]
But even the SQlite file was locked, that wouldn't explain how settings that had been set to true (cloudsave, advanced), suddenly reverted to false.

**Comment by gorhill** [comment]
> suddenly reverted to false

This can happen only when the user actually click the corresponding setting.

> cloudsave, advanced

What?

**Comment by Silfir** [comment]
I'm having this same issue. Disabling the add-on (hitting the power button icon, not disabling in the extension list) only has an effect on my current browser session, the instant I close it down the sites I've disabled it on are gone. I've tried setting up filters through the "My Filters" tab, "My Rules" tab and "Whitelist" tab with none of them yielding any results and come back with their default states after every browser load. It's honestly as though ublock re-installs itself each time I open the browser.

Older versions of the extension work fine, I currently have an instance on my laptop that functions perfectly.

**Comment by gorhill** [comment]
> come back with their default states after every browser load

The sqlite file where uBO saves its settings could be corrupted. Delete it and see if this fixes the issue. See [location of ublock0.sqlite](https://github.com/gorhill/uBlock/tree/master/dist#firefox).

**Comment by Silfir** [comment]
> The sqlite file where uBO saves its settings could be corrupted. Delete it and see if this fixes the issue.

Oh perfect, that fixed the issue completely, thank you so much.
