### ISSUE TITLE
[Suggestion] Per rule commit/revert

### ISSUE THREAD

**Issue by WyohKnott** [gorhill/uBlock#114]
I'm throwing this again as a suggestion: allow us to commit and revert rules on an individual basis in the Dashboard.

It looks like this (with https://github.com/WyohKnott/uBlock/tree/per-rule-action )
![screenshot-ublock0 2015-04-24 16-32-09](https://cloud.githubusercontent.com/assets/6247191/7320936/af48eac0-ea9f-11e4-8568-9e9254138d54.png)

**Comment by deathtrip** [comment]
+1
it would also be good to see this in uMatrix

**Comment by gorhill** [comment]
As [suggested here](http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-61#post-2526626), make the per-column toolbars sticky: useful especially for when dealing with long list of rules, editing a specific rules far down, and wanting to save/discard.

**Comment by gorhill** [comment]
Closing this issue, the _"My rules"_ pane has changed enough since then for the issue here to be considered obsolete.
