### ISSUE TITLE
Popunders

### ISSUE THREAD

**Issue by popunders** [gorhill/uBlock#1142]
1. www.primewire.ag / .ts / .org:   on first visit (only),  click a link (f. example a movie cover) -> popunder (http://onlinecasino.sunmaker.com/) 

2. http://www.primewire.ag/tv-2728055-American-Horror-Story/season-5-episode-10 (just a demo adress, it happens an all video content sites):
on click the following hosters: Version27 (nosvideo), Version 26 (vidup.me), Version25 (thevideo.me), Version24 (noslocker.com), Version4 (briskfile.com), Version3 (promptfile.com) -> popunder + popover

3. onclick on "watch now", "play" etc on the sites described in step 2., again many popunder+popover

**Comment by gorhill** [comment]
I can't get popunders, but I do get popups -- one of which wasn't blocked by EasyList. Fortunately, the site uses the exact same mechanism for its popup as pornhub et al., so this means I can just reuse the existing popup defuser for that site. Could you confirm the following filter this works for you?

    primewire.*##script:inject(pornhub-popup-defuser.js)

uBO 1.5.1 required.

**Comment by popunders** [comment]
1. solved
2. + 3. not solved 

to reproduce: click on Version 27 (link http://www.primewire.ag/external.php?title=American+Horror+Story&url=aHR0cDovL25vc3ZpZGVvLmNvbS85NThiMjI0N2E1OWI1Y2Ez&domain=bm9zdmlkZW8uY29t&loggedin=0) 
then on "watch now". a popunder/over appears and in a new tab the same page but now with nosvideo.com url. then click again on "watch now". again popunder/over. the video starts.

first popunder: from primewire, second: from nosvideo.com

the same for the other urls from initial post. 

out of curiosity: is the filter above shown in the logger? also the redirection filters?

**Comment by IDKwhattoputhere** [comment]
These two filters got rid of all the popunders for me:

    ||primewire.ag^$popunder
    ||branchroughlend.info^$popunder

**Comment by HL-Audit** [comment]
@IDKwhattoputhere : suggested filters arent working, at least if i reproduce described steps above.

**Comment by gorhill** [comment]
`||branchroughlend.info^$popunder` is in uBlock's filters since I don't know when. I can't add `||primewire.ag^$popunder` though, as it is the main site itself, that would prevent it from opening new tabs.
