### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by popunders** [gorhill/uBlock#1143]
rjwalls.github.io/papers/walls15_imc.pdf
Measuring the Impact and Perception of
Acceptable Advertisements

**Comment by Betsy25** [comment]
I have learned the habit that I disable ad-blocking for the sites i think deserve them, including my prefered (non-commercial) youtube channels.
The weird thing is this article nowhere mentions about the 100% trackers among what they deem as "Acceptable Ads"...

**Comment by Hrxn** [comment]
We need GitHub bans for abusing the issue tracker...
