### ISSUE TITLE
Wrong Blocked Count    version 1.5.3b0

### ISSUE THREAD

**Issue by dave47** [gorhill/uBlock#1147]
I am getting the same exact counts on different websites.  It updates blocked count for all sites to the count for the latest website visited.  It does not do it on 1.5.2

**Comment by gorhill** [comment]
Marking _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by dave47** [comment]
Sorry did not realize you need all that info.

Firefox 43.03 windows 7 sp1   ublock 1.5.3b0
TBO.com  tampabay.com huffpost.com
settings and filters   see attached     no custom filters
open each website look at counts

On 12/30/2015 8:58 AM, Raymond Hill wrote:
>
> Marking /invalid/ as per CONTRIBUTING 
> <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1147#issuecomment-168003973>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by gorhill** [comment]
`tbo.com`: 50
`tampabay.com`: 27
`huffpost.com`: 24
`arstechnica.com`: 14

**Comment by dave47** [comment]
I think i know what happened. from github installed via xpi.  it told me 
it was 1.5.3 and it did not  say restart.  after this is when all counts 
were the same.

I then downloaded 1.5.3 again but then shutdown FF.  When i started 
firefox everything was working perfectly.

thx dave

On 12/30/2015 9:24 AM, Raymond Hill wrote:
>
> |tbo.com|: 50
> |tampabay.com|: 27
> |huffpost.com|: 24
> |arstechnica.com|: 14
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1147#issuecomment-168010460>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by gorhill** [comment]
uBO is restartless, so you should not have to restart the browser. I re-ran the test again after dropping a new uBO xpi into the browser, and the count was properly updated. Next time if it happens again, look into the browser console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>j</kbd>) and see if there are error messages for uBO.

**Comment by dave47** [comment]
that may be but i know for sure that i saw identical counts.  perhaps 
this is one of those mysteries nobody will know about.

dave

On 12/30/2015 9:46 AM, Raymond Hill wrote:
>
> uBO is restartless, so you should not have to restart the browser. I 
> re-ran the test again after dropping a new uBO xpi into the browser, 
> and the count was properly updated. Next time if it happens again, 
> look into the browser console (Ctrl-Shift-j) and see if there are 
> error messages for uBO.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1147#issuecomment-168013540>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
