### ISSUE TITLE
Disabling adware downloads from software and filehosting websites

### ISSUE THREAD

**Issue by anonsubmitter** [gorhill/uBlock#1148]
Would it be possible to make uBlock inject the [SourceForge ?nowrap trick](http://academe.co.uk/2013/12/filezilla-without-the-spyware/) into SourceForge download URLs to sterilize them and get the adware installers replaced with legit installers?

Another thought I have is if it would be possible to integrate [the AntiAdware script](https://github.com/HandyUserscripts/AntiAdware) into uBlock?

**Comment by gorhill** [comment]
This is beyond the scope of uBO.

**Comment by Hrxn** [comment]
On top of that, this is also a bad idea.

**Comment by anewuser** [comment]
@anonsubmitter You modify URLs with [Redirector](http://einaregilsson.com/redirector/).
