### ISSUE TITLE
What the hell is with “Bidgewalbelp filters”?

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#1149]
Some days ago it was available for everyone for download. Now, since about two days there's no filters list and web page has been changed drastically :/

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web/_compare/c0226f9a9ea0d265cb5cb54c2181912b40159c8c...736cddb2c7f5fd8bcf3d509fee287f99db4fc584>.
