### ISSUE TITLE
[Firefox] Site-switch rule making; user error

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#115]
Firefox 37.0.2; Mint 17.1; Origin 0.9.5.0-dev.1

Site specific rules work here, but can't seem to figure out how to make a universal change.

As example:

```
no-strict-blocking: * true
```

Visiting outgoing links in [say](https://encrypted.google.com/search?q=troll&tbm=shop) still leads to strict blocking kicking in.

What am I doing wrong with the rule?

**Comment by gorhill** [comment]
`no-strict-blocking: * true` works fine here. I need a **very specific scenario** where you get the problem. URL to visit which should not be blocked, filters, etc. The URL you provided is not blocked even with strict blocking enabled. Need specifics please.

**Comment by kintpuash** [comment]
[Link](https://encrypted.google.com/aclk?sa=l&ai=CUMviKHw6VZHJFIbYpgPPhIDoAouaqKMG286u0eoBw6ja-YwDCAkQASDezc8eKB1gyYbYiPyjqBSgAZL68doDyAEHqgQmT9ATvrI-QSP-Fsh-od3GiMZFrgis8xnU-JxjbhiyFourVmGac9TABQWgBiaAB8PCxDGQBwOoB6a-G9gHAeASrZeV3Pjeg__nAQ&sig=AOD64_1Y4BejVeIFB24BAbZWUn3Vhf-MtQ&adurl=http://5203.xg4ken.com/media/redir.php%3Fprof%3D402%26camp%3D175%26affcode%3Dpg750%26k_inner_url_encoded%3D1%26cid%3D62855822915%26networkType%3Dsearch%26kdv%3Dc%26kpid%3D154381956%26url%3Dhttps://www.etsy.com/listing/154381956/rare-2-headed-troll-doll-by-uneeda-1965%3Futm_source%253Dgoogle%2526utm_medium%253Dcpc%2526utm_campaign%253Dshopping_us_mid-toys_and_games-toys-dolls_and_action_figures%2526utm_custom1%253D_kenshoo_clickid_&ctype=5&rct=j&q=troll&ei=KHw6VeDwEci0sASu2YGQCw&ved=0CJQBEKcrMAA&cad=rja) representing an outgoing link on the page.

**Comment by gorhill** [comment]
Ok, my findings.

Without `no-strict-blocking: * true`, the link was blocked.

With `no-strict-blocking: * true`, the link was not blocked.

**Comment by kintpuash** [comment]
We are good. Works now. User error confirmed.

**Comment by gorhill** [comment]
What was the error?

**Comment by kintpuash** [comment]
Under the mistaken impression rules applied under "My Filters" as opposed to "My Rules" would have an effect. In other developments, a US state has also issued me a license to drive a motor vehicle. Something to consider if you ever cross the border

**Comment by gorhill** [comment]
Don't feel bad, I once open an emergency issue that "cosmetic filtering was broken". I had forgotten I had disabled uBlock for the site...
