### ISSUE TITLE
Broken site: http://view.stern.de

### ISSUE THREAD

**Issue by Hrxn** [gorhill/uBlock#1152]
I only see a completely grey page, nothing else
http://view.stern.de/de

Tested with:
```
Chrome 47.0.2526.106 (Official Build) m (64-bit) + uBO  1.5.2
Firefox 43.0.3 + uBO 1.5.1
```
On Windows 7 SP1 x64
Both with default uBO settings and filters.

Disabling uBO shows the site in both browsers, choke full with huge ad banners and terrible page load delay.

I took a glance at the logger, found this suspicious:
```
01:44:40		/gujad/*	--	script	      http://view.stern.de/gujAd/gujAd.js
01:44:40				        script	      http://view.stern.de/js/app/view_gujAdd.js?5
01:44:40		/gujad/*	--	css           http://view.stern.de/gujAd/gujAd.css
```
No hit for http://view.stern.de/js/app/view_gujAdd.js ?

Appearing again:
```
01:44:41		/gujad/*	--	script	http://view.stern.de/gujAd/gujAd.js
01:44:41		/gujad/*	--	css	    http://view.stern.de/gujAd/gujAd.css
```
And finally:
```
01:44:42		##div[itemtype="http://schema.org/WPAdBlock"]	--	dom	http://view.stern.de/de/rubriken/natur/winter-nebel-stille-fog-schlecht-wetter-winter-standard-2949417.html?top=1
01:44:42		##.gujAd	--	dom	http://view.stern.de/de/rubriken/natur/winter-nebel-stille-fog-schlecht-wetter-winter-standard-2949417.html?top=1
01:44:42		##.adWrapper	--	dom	http://view.stern.de/de/rubriken/natur/winter-nebel-stille-fog-schlecht-wetter-winter-standard-2949417.html?top=1 
```

This happens directly on the start page http://view.stern.de as well as any other sub page or direct link to image page like http://view.stern.de/de/rubriken/tiere/tierfotografie-katzenportrait-viewspotlight-eyes-katzenaugen-katzengesicht-cat-standard-2949748.html?top=1

Anyone recognizing `gujAd` or `adWrapper`?

**Comment by gorhill** [comment]
Works fine with EasyList Germany enabled.

**Comment by gorhill** [comment]
I get same result with ABP if I disable EasyList Germany in ABP.

**Comment by Hrxn** [comment]
Oh, right.

Can confirm, works with EasyList Germany.

That list is disabled by default, and I don't visit that many German sites in a regular fashion, so I've never enabled it.


I looked at the logger again, and couldn't find a difference. But I don't think that it's much what EasyList Germany is doing here..

**Comment by Hrxn** [comment]
Also confirming as OK for:

Chrome 47.0.2526.106
uBO 1.5.2
with EasyList Germany active

**Comment by Hrxn** [comment]
I just had a (small) idea..

Because the issue label is not correct, technically. It was not a problem with the 3rd-party filter list. EasyList Germany was working correctly as given.

The website is just, well, dumb. Just turned the whole page into full gray, no warning whatsoever.

The problem being the site itself, I'd suggest a new label like 'bad site' or 'dumb site' or 'design fault' or whatever...
