### ISSUE TITLE
Better German translation for disabling uBlock because of indistinguishability

### ISSUE THREAD

**Issue by Lalarian** [gorhill/uBlock#1153]
Hello!

I got big problems in distinguishing the two options "Klick: UBlock für diese Website aktivieren/deaktivieren" and "Strg+Klick: UBlock nur für die aktuelle Website deaktivieren".

It's really hard to understand and i got to try out and backcheck everytime I need to disable UBlock for some reason. This is because both statements have an identical meaning, as a website in the meaning of a single page still is the same word as a website in the meaning of a whole domain of websites, no matter what other words you put there for describing them.
So these options just don't tell the user, whether they regard to a sole site or the whole domain and everytimeI need to disable UBlock I have to think about what's the option I need for multiple seconds.

For sure I'm not the only german user suffering from this lack of discriminability, thus I suggest, changing the option for disabling UBLock on more than just a single website to: "Klick: UBlock für alle Seiten dieser Domain deaktivieren".

Also: In a more sophisticated view on the topic I think that it would be better do use two clearly different buttons for each case instead of the big blue button there anyway.

Thank you!
regards

**Comment by gorhill** [comment]
All translation work occurs on [Crowdin](https://crowdin.com/project/ublock). If you think something is wrong, raise the issue there with the translators, or provide your own translation.

**Comment by Lalarian** [comment]
Hello! I was a bit lazy and so it took me some time to get back here, but as I have seen in the recent Version you have already commited the change. Thank you very much! :)
