### ISSUE TITLE
Use HTTPS for MDL

### ISSUE THREAD

**Issue by J0WI** [gorhill/uBlock#1154]
As proposed in #1138 you should use HTTPS for malwaredomainlist.com

**Comment by harshanvn** [comment]
Its there now. checked in with this <a href="https://github.com/gorhill/uBlock/commit/7952143a1f1d0dd97a58646d4f9cfc1b2428a6aa">commit</a>

**Comment by J0WI** [comment]
Well, nice commit msg...

But this still lacks of the httpS in the shell script and the docs.
