### ISSUE TITLE
handle redundant lists

### ISSUE THREAD

**Issue by J0WI** [gorhill/uBlock#1155]
[uBlock Origin 1.5.1]

Some filter lists like 'Fanboy’s Annoyance List‎' and 'Fanboy’s Social Blocking List‎' are redundant [1].
There should be radio buttons instead of check boxes to activate the lists. Or at least a hint.

There might be other redundant lists to I didn't checked. (e.g. 'Fanboy+Easylist-Merged Ultimate List‎'?)

[1] see description on https://fanboy.co.nz/

*(this is not a feature request, it's a usability/performance bug)*

**Comment by harshanvn** [comment]
> it's a usability/performance bug

It defintely does not effect the performance. All the duplicate filters are discarded, during compilation.

**Comment by TPS** [comment]
now @ #1181.
