### ISSUE TITLE
cosmetic filter doesn't work after reload

### ISSUE THREAD

**Issue by ZIEXED** [gorhill/uBlock#1159]
to reproduce do the following
1- Go to http://1take.com/ with javascript disabled
![capture](https://cloud.githubusercontent.com/assets/14824755/12072044/6b37f40a-b0d5-11e5-84aa-86edd6f76521.JPG)
2-  With the element picker add  "1take.com##noscript"
the nag window will be hidden successfully for this time
once you refresh the page the nag window will appear again
the filter "##body > div:nth-of-type(1) > noscript > div" will work but "1take.com##noscript" should also work?
And "##body > div:nth-of-type(1) > noscript" only work for once then it won't work again

**Comment by gorhill** [comment]
[CONTIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
