### ISSUE TITLE
AMO or not

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#116]
Hello, I know it's a question you don't like to answer, will you have the project to propose ublock origin on AMO ? My opinion is you're better and faster than the team of ublock and like their addon begin to have success on AMO (more then 140 000 users), yours could have enought or much, because users like addons who are often updated and be better and better. And like AdBlock Edge will let down in june, it will have a place face off the monster ABP.

**Comment by gorhill** [comment]
Yes, once 0.9.5.0 is released, I will submit to AMO.

**Comment by alain1965** [comment]
Thank you for your answer and good news for users of Firefox.

**Comment by Betsy25** [comment]
@Gorhill If it's on AMO, think about finishing off the fork, and perhaps simply set up a new uBlock Origin repo, in all honesty your skill and dedication deserve more of what is happening currently, and unknowing users unaware that uBlock is for 99.5% you work, and so it will be (aside for the bunch of readme.md changes which still are, and will probably stay the most major changes by the new """"main developer"""".
