### ISSUE TITLE
Filter list not supported

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1161]
I tried adding
https://raw.githubusercontent.com/magdev/leistungsschutzgelderpresser/master/domains.json
from https://github.com/magdev/leistungsschutzgelderpresser
and uBO says it uses 450 out of 450 filters but I can still open e.g. bild.de. I'm guessing the format isn't supported by uBO?

**Comment by gorhill** [comment]
That is not a valid ABP-compatible filter list, neither a hosts one.

**Comment by IDKwhattoputhere** [comment]
Adding support for this style of list is probably not worth it?

**Comment by gorhill** [comment]
It's a JSON file, JSON can be anything.

Please answer this: if you feel strongly that the list should be usable in uBlock, why not just create a project on **your** GitHub repo and convert it to a list usable by blockers? In short, why not just be proactive instead of asking **others** to do something about it?

**Comment by IDKwhattoputhere** [comment]
True. https://github.com/IDKwhattoputhere/leistungsschutzgelderpresser/blob/master/domains.txt

**Comment by lewisje** [comment]
I was hoping at least it would be the kind of JSON expected by Safari's content-blocker, but it's just the serialization of an array of strings; the good thing is that it can easily be converted to hosts-file format as @IDKwhattoputhere has almost done (the IP addresses are not on each line, but maybe uBlock Origin doesn't require that), but the bad thing is that it can't be used directly in a content-blocking app.

Soon I'll go ahead and make a variant of that list that works even in ABP and AdBlock.

**Comment by IDKwhattoputhere** [comment]
It works in uBO just like the Disconnect lists which are also just simple domain lists. Sure, it would be better if it was in the form of

    ||bild.de^
but it works for my purpose.

**Comment by lewisje** [comment]
Here's a version that works similarly, except that ABP and AdBlock do not block the network request in the address bar: https://raw.githubusercontent.com/lewisje/leistungsschutzgelderpresser/master/abp.txt

This is a proper hosts file: https://raw.githubusercontent.com/lewisje/leistungsschutzgelderpresser/master/hosts.txt
