### ISSUE TITLE
Issues when download AMD Radeon Software

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#1164]
Web Browser: Firefox 43.0.3
Platform: Win 7 X86
Ublock Origin 1.5.1, default settings

Steps to reproduce:
1.- Open this URL: http://support.amd.com/en-us/download
2.- Go to "Manually Select Your Driver" section
3.- Select any option of each steps of the list
4.- Clic on "Display results" button

Actual results:
1.- The button doesn't work. Appears a message that says "Please choose a platform of the list"

Expected results:
1.- After clic on "Display results" button, Firefox should display the next page.

Note

    If you uninstall or disable Ublock origin the button works normally.
    Same problem with Chrome

Sorry for my poor English

**Comment by IDKwhattoputhere** [comment]
As far as I can tell the commit has made this filter rule redundant:

    @@||www.google-analytics.com/plugins/ua/linkid.js$script,domain=support.amd.com

Somewhat unrelated:
Some filter rules have unnecessary trailing wildcards. E.g.

    @@||s0.2mdn.net/instream/*$object,script,domain=wsmv.com
