### ISSUE TITLE
Blocks credit card activation pages

### ISSUE THREAD

**Issue by c627627** [gorhill/uBlock#1165]
For example:
http://citi.com/activate
Adblock Plus does not block the name & address fields on that page and neither should uBlock. I am trying to switch away from Adblock Plus, and would like to report major pages like this that uBlock should not be blocking. Thank you.

**Comment by gorhill** [comment]
The issue also exists in Adblock Plus if you enable EasyPrivacy (which is enabled by default in uBO). This needs to be reported to the maintainers of EasyPrivacy: <https://forums.lanik.us/viewforum.php?f=64>.

Meanwhile, you can use this custom filter:

    @@||mpsnare.iesnare.com/snare.js$domain=citi.com

**Comment by gorhill** [comment]
Submitted to EasyPrivacy maintainers: <https://forums.lanik.us/viewtopic.php?f=64&t=27588>.

**Comment by c627627** [comment]
How is EasyPrivacy disabled in uBlock if we want uBlock to allow the same sites to go through as Adblock Plus?

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters>.
