### ISSUE TITLE
[Firefox] No 1.5.2 update on AMO

### ISSUE THREAD

**Issue by PalZer0** [gorhill/uBlock#1167]
I've noticed that I haven't received uBlock Origin 1.5.2 through the Firefox auto-updater. This is because it's not on AMO (other releases up to 1.5.1 have made it there normally).

I'm on Firefox 43.0.3 x64.

**Comment by harshanvn** [comment]
The reason it is not available on AMO is, it contains only chromium specific fixes. Please see <a href="https://github.com/gorhill/uBlock/releases/tag/1.5.2">here</a> for more info.
Its just waste of bandwidth in pointlessly updating, if the fixes are not related to that specific platform. Which is what the author here is doing.

**Comment by PalZer0** [comment]
I pointed it out because there's a Firefox XPI download for 1.5.2 offered on that link so it seems odd that it's not on AMO as well.

**Comment by harshanvn** [comment]
> I pointed it out because there's a Firefox XPI download for 1.5.2 offered on that link

As I said -
"Its just waste of bandwidth in pointlessly updating, if the fixes are not related to that specific platform."
So, not available on AMO.

I believe it is travis, which creates packages automatically for each release. However, it is pushed to chrome/opera/mozilla stores, iff there is a change that platform.
Hope this clears the things for you.

**Comment by PalZer0** [comment]
That clears the air on that one.
