### ISSUE TITLE
Auto-update filter lists

### ISSUE THREAD

**Issue by antdude** [gorhill/uBlock#1168]
Hello.

How often are these lists checked to update? Is there a way to manually get the updates like waiting for fixes from filter subscription changes that I submitted? Purging all caches and redownloading take too long. 

In AdBlock Plus, I could use the hidden hot keys to get the updates manually on demand instead of waiting for days.

Thank you in advance. :)

**Comment by gwarser** [comment]
4 days.

Click "purge cache" button, next to filter name, then update.

**Comment by antdude** [comment]
Ah thanks. Why do some filters don't have purge cache button even if they have checkmarks?

**Comment by harshanvn** [comment]
i think, if the shipped version and version at the remote location are same. then there will be no purge cache button.

**Comment by antdude** [comment]
Hmm, interesting and thanks.
