### ISSUE TITLE
Cosmetic filtering inconsistent on google.com

### ISSUE THREAD

**Issue by yieldman** [gorhill/uBlock#1172]
![ublock](https://cloud.githubusercontent.com/assets/15101945/12122347/4659b3c0-b400-11e5-9aba-b1daf3bd9a09.png)

Browser:- firefox dev edition 44
url:- https://www.google.co.in/search?q=buy+book
addons:- greasemonkey(no userscripts running on google.com btw), noscript, umatrix, ublock.
details:- might have to refresh couple of times. depends.

**Comment by gorhill** [comment]
Are you using FFdev with e10s enabled?

Try with NoScript disabled. I am not sure NoScript is completely compatible with e10s, and this can cause issues which are outsite of uBO/uMatrix's control.

**Comment by gorhill** [comment]
Ok, e10s does not matter. But I can reproduce the issue _only_ when NoScript is enabled.

**Comment by gorhill** [comment]
If I block 1st-party scripts with uMatrix or uBO, the issue does not occur. It occurs only if I block 1st-party scripts with NoScript.

**Comment by gorhill** [comment]
A bit more testing here is the conclusion:

- I finally could reproduce with 1st-party scripts blocked by uMatrix/uBO
- Same issue with ABP + NoScript.

Thus it is a 3rd-party filter list issue: when scripts are forbidden on the page, the page renders differently than expected, and some elements end up not matching existing cosmetic filters.
