### ISSUE TITLE
Exoclick Popunder

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1173]
Is it correct that popunder rules should be posted here?

    ||exoclick.com^$popunder
Used on a couple of sites (NSFW e.g. empflix.com, tnaflix.com). They've used this domain for years so it's a safe bet to add this.

**Comment by gorhill** [comment]
> Is it correct that popunder rules should be posted here?

Sure, as long as you document where they are occurring so that it can be checked in the future whether the filter is still needed. I see `exoclick.com` is already used for a popup filter, so I will just add it for popunder, no need for me to visit these sites.
