### ISSUE TITLE
EasyPrivacy breaks https://www.cloudflare.com/a/overview

### ISSUE THREAD

**Issue by jab** [gorhill/uBlock#1174]
(Reporting here as I still don't have access to the EasyList forums, and hope this is helpful in the meantime.)

1. Create a free CloudFlare account if you don't have one already
1. Log in
1. Get redirected to https://www.cloudflare.com/a/overview
1. Observe the page content doesn't load

![screen shot 2016-01-05 at 13 17 27](https://cloud.githubusercontent.com/assets/64992/12123426/f248eeb4-b3ae-11e5-9e46-773725ad4ce2.png)

![screen shot 2016-01-05 at 13 15 05](https://cloud.githubusercontent.com/assets/64992/12123429/f7a48044-b3ae-11e5-9e7e-b15f3d4871ce.png)

Looks like it's an issue with the newrelic filter?

Narrowed it down to EasyPrivacy by testing with ABP + EasyList without EasyPrivacy.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

>  1. Verify that the issue is not related to a 3rd-party filter lists.
>     - Issues with 3rd-party filter lists are the responsibility of their respective maintainers.

=> <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by jab** [comment]
I took it from your response to #1169 that this would be ok, given I said
> I see from https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md you don't have time for filter-related issues, so please feel free to close. Still valuable to have this issue documented in the tracker so it turns up in search results, as currently searching turns up nothing.

and you didn't close, but it sounds like you wish I hadn't opened this? I did search the forums for this issue before I opened it here and didn't find it reported. Again, I still haven't been given access to post over in the EasyList forums.

Anyway, will close this as it apparently isn't helping.

**Comment by gorhill** [comment]
That said, I would expect uBO's neutered `google-analytics.com/analytics.js` script to prevent the breakage, however it is not. The reason is that the page make use of a CSP policy which forbids data: URI.

Unsure whether something can be done for this, I will have to experiment.

**Comment by gorhill** [comment]
Fixed with ba18218487975dc6458360fc9ab695cec7007b51.

Purge _"uBlock filters -- Privacy"_  filter list and force an update.
