### ISSUE TITLE
gmx.net inbox AD Block Filterrule not working anymore with ublock 1.5.3rc0 and Firefox 44b6

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#1175]
Hi 

the problem is with ublock 1.5.1 the rules:
gmx.net###mail-list .new.iba
gmx.net###mail-list .iba
gmx.net###mail-list .ad-hint
gmx.net###mail-list *.iba

works perfekt to block  the inbox ad @ gmx.net with Firefox 44b6!
i test it many times with 1.5.1 and with ublock 1.5.3rc0,but the same rule dont work anymore with 1.5.3rc0! a bug? 

plz help and sry for my bad english!

greetings

**Comment by gorhill** [comment]
`gmx.net###mail-list *.iba` is not a valid cosmetic filtering rule, uBO rejects it (regardless of uBO's version).

**Comment by gorhill** [comment]
There was no changes between 1.5.1 and 1.5.3 which could cause such issue. Be sure that it is not caused by one of the following reasons: <https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page>.

**Comment by akks1981** [comment]
Ok, i make a clean install of Firefox 44b6 and now, sry i don't know why it seems to work with ublock 1.5.3rc0 and the gmx Filter! Thx for ur Help ^^ greetings

**Comment by akks1981** [comment]
Hi is this Filterrule correkt for ublock?? 

gmx.net##TR[id^="id7c"][class="new iba-uncertain"]

**Comment by gorhill** [comment]
That would be better, less dependent on how the order he class names are declared in the element:

    gmx.net##TR.new.iba-uncertain[id^="id7c"]

**Comment by akks1981** [comment]
hi thx but it dont work! i testet it with ublock 1.5.1 and it working perfekt! i think its a problem with the logger or so!
thats the gmx.net Ad with latest ublock:
![gmx ad](https://cloud.githubusercontent.com/assets/12896716/12210855/620dd72c-b65d-11e5-93b2-a4ac02e02530.png)

nothing was in the logger! 

but with ublock 1.5.1 

it works, see in the logger:

![logger](https://cloud.githubusercontent.com/assets/12896716/12210897/a05d4670-b65d-11e5-8c84-2b386ef14320.png)

gmx.net###mail-list .ad-hint
gmx.net###mail-list .iba-uncertain


the filter works like a sharm with Firefox latest beta and final with ublock 1.5.1

???? sry for my bad english!

greetings 

...i testet the filter gmx.net##TR.new.iba-uncertain[id^="id7c"] dont work at all....

**Comment by gorhill** [comment]
I can't help, I would need to use the inspector to find out how the DOM looks like.

Launch the element picker for that page, and manually paste `##TR.new.iba-uncertain[id^="id7c"]` in the text area. If the filter matches somethign on the page, the element picker will highlight it.

**Comment by akks1981** [comment]
Hi, now with ublock 1.5.6 the filter rules works fine and was shone in the logger! thx for ur help and keep the good work on for the best blocker ever!!!! (sry for my bad english)

greetings bro

**Comment by gorhill** [comment]
Ok, so the bug was fixed with 5591ff34f1a47adca847d52979ce98f64663c16f -- a bad regression bug: cosmetic filtering was no longer applied inside frame elements.
