### ISSUE TITLE
Bild.de Anti-Adblock filters

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1178]
Your solution (https://github.com/gorhill/uBlock/issues/821#issuecomment-148908117) works great. It would be nice however if you could add that inline script blocking filter to one of uBO's lists to make it more accessible to the users (I first thought "Experimental" but it's not a resource so it doesn't really fit). I for example didn't see this until today (months after they started doing this) when I had the idea to search this repository for a solution. 
There's also one more filter which would be nice if it could be added:

    bild.de##DIV.no-js
blocks their malicious attempts to get NoScript users to allow their ads.
Without filter: https://i.imgur.com/kp7rLS6.png
With filter (NSFW): https://i.imgur.com/AUblN1W.jpg

**Comment by gorhill** [comment]
If  you block 1st-party scripts with uBO, the warning does not appear.

**Comment by gorhill** [comment]
Err... never mind, looks like bild.de has been updating their site to now also block uBO. Will investigate.

**Comment by IDKwhattoputhere** [comment]
Yes, this is because uBO doesn't read the <noscript> tag which is being abused by Bild.de to display the message.

**Comment by gorhill** [comment]
You do realize that adding `||bild.de^$inline-script` would actually cripple uBO's own workaround for bild.de on FF?

**Comment by IDKwhattoputhere** [comment]
I can visit bild.de in Firefox with and without that filter. In Chrome however this filter is required to do so.

**Comment by gorhill** [comment]
Users of chromium-base browsers can block themselves inline scripts using the dynamic filtering pane, this way FF users are not going to be penalized because of a filter which is useful only for chromium.

**Comment by IDKwhattoputhere** [comment]
In which way are they penalized though?

**Comment by MagicAndre1981** [comment]
Bild.de is now blocked again when using µBlock Origin:

> Ein Plugin in Ihrem Browser beschädigt die Funktion der Webseite, deshalb können wir Ihnen keinen Zugriff auf die Inhalte gewähren.
> 
> Möglicherweise nutzen Sie **Ublock Origin** oder ein anderes Adblocker Plugin. Falls dies der Fall ist, versuchen Sie bitte es zu deaktivieren.

**Comment by Serkan-devel** [comment]
I think it now works again since firefox Nightly 57.0a1
