### ISSUE TITLE
uBlock license?

### ISSUE THREAD

**Issue by alejandrolemus** [gorhill/uBlock#118]
@gorhill 
Sorry to post something is not a bug or issue, but I'm gonna go ahead the same, as I really care about uBlock and its future. So please, feel free to close at will.

Regarding [this](https://github.com/gorhill/uBlock/wiki/Maintainership-transfer-of-uBlock%3A-post-mortem), is there a way to modify uBlock's current license so from now on would be required to mention and acknowledge who the ~~original~~ developers and contributors ~~were~~ are?

**Comment by gorhill** [comment]
I don't intend to linger anymore than this on all that (hence "post mortem"). Time to move forward.

**Comment by alejandrolemus** [comment]
> I don't intend to linger anymore than this on all that

Neither do I, I was thinking to prevent something like that in the future. Anyway, the decision is yours.

**Comment by my-password-is-password** [comment]
Time to update the wikipedia, http://en.wikipedia.org/wiki/UBlock.

I wonder who made it.

**Comment by gorhill** [comment]
I will eventually donate the copyrights to a trustworthy organisation (FSF or whatever is incorruptible out there, I haven't figure out which one yet). Once done, they can decide how to deal with that sort of thing, assuming they agree it's wrong.

**Comment by kintpuash** [comment]
@my-password-is-password 

I wasn't the creator of the wikipedia page, it was another party. However, a significant percentage of changes were from my account there. Tried to remain neutral with editing during the exchange the last few weeks, while Chris made some somewhat self serving edits in the past. 

I'm not sure that it is possible to remain neutral moving forward.  Chris's activities are pretty disappointing.

@gorhill 

You mentioned reddit as a support possibility. The uBlock subreddit is currently ran by Chris (assuming he will not step down.) You have any objections to a uBlock Origin subreddit for support help? Or am I misreading your text?
