### ISSUE TITLE
uBlock not applying element hiding rules

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1180]
https://forums.lanik.us/viewtopic.php?f=62&t=27641
I thought this was an EasyList issue at first but apparently not. Sometimes the ad gets displayed and after a reload it's gone. After another reload it sometimes appears again.
Chrome 47
uBO 1.5.2

**Comment by gorhill** [comment]
Can't reproduce. The only way I could reproduce similar behavior is by disabling cosmetic filtering -- sometimes the ad appears, sometimes not. You are not disclosing much as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
I was able to get it again.
Screenshot: 
![2016-01-06_17-18-05](https://cloud.githubusercontent.com/assets/16030872/12147658/5fa06028-b49a-11e5-841e-475a1dc9d0b1.png)
URL (will expire): https://search.disconnect.me/searchTerms/serp?search=65ffaac5-f04c-47bb-8b9c-6e5eb7d4643f
This is the URL I use in the omnibox to search (I think %s needs to be replaced by the search term): https://search.disconnect.me/searchTerms/search?location=DE&query=%s&ses_nojs=Google&create=&location_option=DE&lang=&option=&from_homepage=&from_form=true&source=&showIcons=&filterIcons=&js_enabled=1&ses=Google
uBO settings backup: 
[my-ublock-backup_6.1.2016,_17-15-11.txt](https://github.com/gorhill/uBlock/files/80048/my-ublock-backup_6.1.2016._17-15-11.txt)
Logger:
![2016-01-06_17-24-12](https://cloud.githubusercontent.com/assets/16030872/12147670/6fd877be-b49a-11e5-816e-c649e05e3475.png)
Chrome Version: 47.0.2526.106
OS: Windows 7 Home Premium 64-bit
Extensions: 
![2016-01-06_17-26-52](https://cloud.githubusercontent.com/assets/16030872/12147777/efa4033c-b49a-11e5-89d1-ba5e6eef4be3.png)
![2016-01-06_17-27-05](https://cloud.githubusercontent.com/assets/16030872/12147778/efbe33e2-b49a-11e5-8ba0-9c9cc5bd2022.png)
Problem also occurs with only uBO enabled.

**Comment by gorhill** [comment]
You are using _"EasyList without element hiding rules"_ instead of _"EasyList"_.

**Comment by IDKwhattoputhere** [comment]
Holy s*** I'm stupid. Yea, I changed it yesterday to test something. Sorry for wasting your time.

**Comment by gorhill** [comment]
Could you clarify the issue on EasyList forum as well? This could lead people stumbling onto that thread to presume to quickly there might be something wrong with uBO's cosmetic filtering.

**Comment by IDKwhattoputhere** [comment]
Yes, was about to do that.
