### ISSUE TITLE
Some buttons doesn't work when you visit Santander Bank's Page

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#1182]
Web Browser: Firefox 43.0.3
Platform: Win 7 X86
Ublock Origin 1.5.2, default settings

Steps to reproduce:
1.- Open this URL: www.santander.com.mx.
2.- A pop up appears, close it or wait until it disappears
3.- Go to "SUPER NET" section
4.- Clic on "Afiliarse" or "Tutorial".

Actual results:
1.- Both buttons doesn't work

Expected results:
1.- After clic on those buttons Firefox should open other window, displaying the next page

Notes:
- If you try to clic on other buttons in the same page, the problem persist.
- If you uninstall or disable Ublock origin the buttons work normally.
- Same problem with Chrome

**Comment by gorhill** [comment]
You should see an update for _"uBlock filters -- Unbreak"_, or purge the cache for that filter list.
