### ISSUE TITLE
uBlock doesn't understand ABP's `Redirect` flag.

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#1183]
[Adblock Plus 2.0]
! Title: Please update.
! Expires: 1 days
! Redirect: http://xxxxxxxx.txt

Expected Result:
uBlock update URL to "!Redirect" one like Adblock does.

Actual Result:
uBlock doesn't update URL to new one.

**Comment by gorhill** [comment]
You have a concrete case?

**Comment by espress0** [comment]
I can't understand what "concrete case" is, but here's more detailed explanation:

> https://adblockplus.org/en/filters



! Redirect: http://example.com/list.txt

This comment indicates that the filter list has moved to a new download address. Adblock Plus will ignore any file contents beyond that comment and immediately try downloading from the new address. In case of success the address of the filter list will be updated in the settings. This comment is ignored if the new address is the same as the current address, meaning that it can be used to enforce the "canonical" address of the filter list.


> [Adblock Plus 2.0]

NoMercy's SSL list is moving to HTTP.

**Comment by espress0** [comment]
Also, ABP can handle 301/302 list redirection. How uBlock handle them?

http://other.list/ "HTTP 301. go to https://other.list"
https://other.list/ "HTTP 200. Here's your file." <--- ABP will update list URL to this one

**Comment by gorhill** [comment]
> I can't understand what "concrete case" is

It means I won't bother investing my free time implementing something which does not actually occur in the real world.

**Comment by Havokdan** [comment]
Well, I don't think it's the case to open a new ticket, but it is possible the uBlock go straight to the target site, for example, I am Brazilian, I visit the site, www.uol.com.br which is a site of news, information, and etc all link I click there the uBlock now blocks with resource usage which I imagine is this redirect that has been added in the latest version What I want to know is whether it is possible to go straight to the target site, ignoring in this case, the address "www.click.uol.com.br"e going straight to the desired page, without stopping on uBlock page, as in the image:

http://i.imgur.com/pyPthhL.png

I'm sorry in advance, don't speak English, although it can understand some of what is written by you, I can't write well, so I used an online translator.

**Comment by aimtsou** [comment]
I tried the case and I see the redirect/tracking part before the real news subpage. But my Ublock0 does not block that and does not show the parameters. Which are your settings?

**Comment by Havokdan** [comment]
My settings is:

http://i.imgur.com/oX1Pt2D.png

**Comment by gorhill** [comment]
@Havokdan , @aimtsou 

Let's keep issues separate please, otherwise this drown the original issue in noise. Original issue is "ABP redirect directive in filter lists".

What you are talking about is uBO's strict blocking -- a completely different, unrelated issue. See <https://github.com/gorhill/uBlock/issues/973>.

**Comment by anewuser** [comment]
@Havokdan Use [Redirector](http://github.com/einaregilsson/Redirector/) (Opera version [here](https://addons.opera.com/extensions/details/redirector-2/)):

![Redirector screenshot](https://cloud.githubusercontent.com/assets/6733770/12178966/7be151b8-b55b-11e5-98b8-5a5807a64263.png)

**Comment by Havokdan** [comment]
Thanks, i will try.

**Comment by lewisje** [comment]
I was honestly surprised that the `Redirect` command wasn't understood; I'm thinking about opening an issue now for a similar command that I have found wasn't understood (but the fact that uBlock Origin doesn't enforce it makes it easier on list authors).

**Comment by maxxyme** [comment]
> NoMercy's SSL list is moving to HTTP.

I think that was the concrete case. But I can't find this list.
Found some discussion about it here: https://adblockplus.org/forum/viewtopic.php?t=29330
Re-installed Adblock Plus (last v.1.11) but didn't find this list in the already built-in suggestions.

**Comment by Jeroen52** [comment]
I just moved a small list of maybe 6 PCs to a new location, this feature would be appreciated to move all the PCs to the new location.

**Comment by fuzzyroddis** [comment]
@gorhill I used `! Redirect:` to move my own filter list from example.com to cdn.example.com
I understand that there are more pressing issues however. Traffic costs on example are much higher for me but worth it as it's much much better latency and speeds. I use cdn.example.com for bulk bandwidth where it's much cheaper and suited for something that updates in the background.

**Comment by lewisje** [comment]
If you can set HTTP headers on your old domain, try sending a `301 Moved Permanently` response whenever the old lists are requested; I'm not sure whether uBlock Origin will update the list URLs after receiving that header, but at least you'll only get the overhead of the requests and not the overhead of the response bodies.
