### ISSUE TITLE
this list is AUTOMATICALLY subscribed, why

### ISSUE THREAD

**Issue by espress0** [gorhill/uBlock#1184]
uBlock filters – Block-then-redirect‎ : 0 used out of 9

After I upgrade your uBlock, I noticed that this list is AUTOMATICALLY subscribed.
Why don't you notify users before enable such lists?

Also, where's the original URL for this list?
And how can I block uBlock's background update?

I want to update ONLY LISTS I SPECIFIED. I don't want other lists, and don't want uBlock to make such connection.

**Comment by gorhill** [comment]
Yes, it is automatically subscribed, like others when you install uBO. This is a new filter list which was introduced in 1.4.0, and it is enabled by default.

> how can I block uBlock's background update?

<https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#auto-update-filter-lists>.
