### ISSUE TITLE
Firefox: block an element from the Web Inspector

### ISSUE THREAD

**Issue by tyaremco** [gorhill/uBlock#119]
This is quite useful.  I hope you'll consider pulling this in.

https://github.com/chrisaljoudi/uBlock/commit/e8572bdc214c816a508591e6a7e40b09601c1bda

**Comment by d4k0** [comment]
+1

**Comment by anewuser** [comment]
@d4k0 on Github, avoid posting meaningless comments like "+1". The issue remains open until the developers have the time to implement the suggestion or close it for considering them innapropriate.

@gorhill if you add this, please add different toggles for showing this and item in the main Firefox context menu. @chrisaljoudi version uses the same "Make use of context menu where appropriate" checkbox for both things, which is an annoyance since I'm only interested in seeing this menu entry in the web inspector context menu.

**Comment by tyaremco** [comment]
@anewuser   "+1" is not meaningless. In this context it means "I would also like to see this feature implemented".

Until Github implements a system other than "issue participant total" to gauge the demand for a feature, a "+1" comment seems fine to me.  A "+1" comment would only be redundant if the developer had already commented on his intentions to address the issue.

**Comment by anewuser** [comment]
@tyaremco the developer already aware of this issue no matter how many "+1" you keep adding to the page. It just annoys people. He has forked his own project not to see stuff like this anymore.

**Comment by tyaremco** [comment]
@anewuser 
> the developer is already aware of this issue no matter how many "+1" you keep adding to the page. 

As I'm sure you know, "+1" is about developer awareness of the _demand_ for a feature not awareness of the feature itself.

>  If the suggestion is decent, it's going to be implemented even if it has been suggested by only a single user. 

I consider this is a dubious statement.  Of course, this is not the place for me to elaborate.

> He has forked his own project not to see stuff like this anymore.

If gorhill has preferences about what stuff he doesn't want to see then he make them clear in CONTRIBUTING.md (which he has).  

In fact, this is a borderline issue anyway as it's technically a feature request which he explicitly discourages.  Because it's a already been implemented in the main repo, I thought he might be OK with it.

**Comment by anewuser** [comment]
@tyaremco  Imagine being flooded with notifications about new posts in an issue you're following (or new posts to the entire repository if you follow all of it). Imagine clicking on those notifications only to see yet another "+1" from a user that has added nothing to the discussion. Imagine reading an issue or forum thread trying to find some relevant info or feedback, and having to scroll past horders of "+1".

@gorhill  has publically declared that uBlock  is, in his opinion, *feature complete*. Anything else is possibily *bloat* and he will need time to consider all implications of adding it. Spamming trackers with "+1" won't help anybody but your own childish expectation that it'll make developers who do their job for free work for you faster.

**Comment by gorhill** [comment]
"+1" makes absolutely no difference on whether or not I want to implement something. What makes a difference is whether **I** believe I should work on it considering every else, "every else" being **all other issues and shortcomings** of uBlock.

**Comment by bitst0rm** [comment]
I tested the 2 patches:
https://github.com/chrisaljoudi/uBlock/commit/e8572bdc214c816a508591e6a7e40b09601c1bda (Block an element from the Web Inspector)
https://github.com/chrisaljoudi/uBlock/commit/c98ff26709a62c8502fcbfceae622ef85143ba31 (Block an element from the Network Inspector)
and it seems to work perfectly.
However, i still prefer to use the official release from AMO with this new feature.

**Comment by sn260591** [comment]
@gorhill is there any news on this?

**Comment by gorhill** [comment]
I want to implement this in a portable way. Since it was implemented on Firefox, I did write prototype code to make this work for Chromium, and I did not like the result. I am thinking of other approaches to accomplish the same thing.
