### ISSUE TITLE
The wiki should link W3C Recommendation instead of draft

### ISSUE THREAD

**Issue by Loirooriol** [gorhill/uBlock#1190]
https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering says

> The `beforescriptexecute` event is not specific to "Gecko-based extensions", it is part of the latest [W3C Working Draft](http://www.w3.org/html/wg/drafts/html/master/semantics.html#scripting-3)...

And that's true, but better link the recommendation:

> The `beforescriptexecute` event is not specific to "Gecko-based extensions", it is part of the latest [W3C Recommendation](http://www.w3.org/TR/html5/scripting-1.html#scripting-1)...

I guess this should be a pull request instead of bug, but I don't know how to do it for wikis.

**Comment by gorhill** [comment]
Thanks -- fixed.
