### ISSUE TITLE
uBlock causes Firefox to load some resources from cache on F5 without making a request

### ISSUE THREAD

**Issue by T3rm1** [gorhill/uBlock#1191]
I haven't found out under which circumstance this happens. If it happens it is 100% reproducible.

Problem: Some resources are directly loaded from cache (without a request made) although they have changed on the server.

Expected behavior: On F5 every resource should be requested with a If-Modified-Since header when it was cached.

It's strange to see that on F5 some resources are requested with If-Modified-Since header and some are not. All responses have the same Expires header. When I disable uBlock everything works as expected.

**Comment by gorhill** [comment]
> On F5 every resource should be requested with a If-Modified-Since header when it was cached.

The browser handles this, not uBO.

**Comment by gorhill** [comment]
As outlined in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> You will have to make the case that the issue is really with uBlock Origin 

Otherwise it is just sending me on a fishing expedition based on someone else's speculations. Make the case.

**Comment by gwarser** [comment]
Try ctrl+f5 https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_navigation

**Comment by T3rm1** [comment]
This IS a problem of uBlock. You didn't read my post carefully enough. As I said this problem does NOT occur when I disable uBlock. It has nothing to do whether I refresh the page with F5, Ctrl + F5, Ctrl + R or Ctrl + Shift + R. Please reopen this.

**Comment by gorhill** [comment]
> You didn't read my post carefully enough

On the other hand, you did not read [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) carefully.
