### ISSUE TITLE
Add explanation of logger output to documentation

### ISSUE THREAD

**Issue by bradbulger** [gorhill/uBlock#1192]
This page
https://github.com/gorhill/uBlock/wiki/The-logger

is pretty good at describing everything _except the main content of the logger output_. What are those columns? What are those values? What do the colors mean?

**Comment by Snapy** [comment]
@bradbulger I think your question has been answered with the [recent changes] (https://github.com/gorhill/uBlock/wiki/The-logger/_compare/147210c1c5fcd5fd36a2679bf67f229f68ac317c...f3ba0d0128edd9aafd4bec7df21675037bfcc653?diff=unified).

**Comment by bradbulger** [comment]
certainly an improvement.
