### ISSUE TITLE
Provide a UI to pick the default state of some per-site switches

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1193]
It should be possible to easily pick the default state of the following per-site switches:

- Disable cosmetic filtering (this would create/remove the `no-cosmetic-filtering: * true` rule).
- Block remote fonts (this would create/remove the `no-remote-fonts: * true` rule).

**Comment by IDKwhattoputhere** [comment]
Would be nice to have one for no strict blocking too. This feature keeps me from recommending uBO to less experienced users because it would make them panic or uninstall uBO.

**Comment by gorhill** [comment]
Less experienced users are the ones who need to be warned by strict blocking, that is the exact reason I will not provide a UI for this one.

**Comment by gorhill** [comment]
Fixed with 89148351e86ce933ba5fc8cc998681a884c13a3f.
