### ISSUE TITLE
Whitelisted domains don't apply to iframes?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gorhill/uBlock#1194]
Whitelist on:
https://openload.co/f/uzmodWIgTjM/Straight.Outta.Compton.2015.DC.720p.BRRip.x264.AAC-ETRG.mp4
it doesn't apply to embedded vids (NSFW):
http://www.werehd.com/letstryanal-abella-danger-abella-dangers-anal-sextape/

This works in ABP, is there a different method that works in Ublock?

**Comment by IDKwhattoputhere** [comment]
It works in ABP? Because for me it doesn't.

**Comment by gorhill** [comment]
> is there a different method that works in Ublock?

Yes, in uBO whitelisting a site by creating a hostname-based whitelist directive won't cause embedded versions of that site to be whitelisted as well.

When it comes to whitelisting, uBO approach is different, it's not filter-based -- uBO does not parse and enforce the `document` filter option for exception filters -- whitelisting is wholly under the control of users, 3rd-party filter lists can't whitelist sites for you.

Whitelisting on such site is strongly discouraged. The solution is rather to defuse whatever the site is doing to force you to lower your defenses. I update uBO's own filters to workaround the site's anti-blocker. Force an update of your filter lists.

Another good advice for shady sites: use dynamic filtering in medium mode. The page above works all fine by blocking all 3rd parties except `ajax.googleapis.com`.

**Comment by gorhill** [comment]
Also I should add that using medium mode as suggested will also counter whatever exception filters (ABP-specific solution) created for a site as a workaround for anti-blocker mechanisms. Often, exception filters are added to EasyList because that is the only way this can work for ABP/AdBlock (like uBO, AdGuard has more capabilities to work around anti-blocker mechanisms). I consider blocking less for the purpose of working around anti-blocker mechanisms to be undesirable, to be avoided where possible.

**Comment by narcolepticinsomniac** [comment]
I know allowing  1986a44b12e.com will work, but I'm sure you're familiar with this site, they switch their adblock tripper like twice a week. I got sick of investigating all the time. The only ads they serve are pop-ups that get blocked by my pop-up blocker anyway, so I whitelisting is much less annoying.

I can see how medium mode might work on the site itself, but not embedded videos.

**Comment by gorhill** [comment]
> I'm sure you're familiar with this site

First time I visited this site. If the workaround I created stops working, just open an issue, I will look into it.

**Comment by narcolepticinsomniac** [comment]
Thanks.

**Comment by narcolepticinsomniac** [comment]
At first I didn't realize you were injecting a bit of javascript to fix this issue. It has worked very well. I hope something similar can be done for another popular streaming site that just upped their anti-adblock campaign. Example: http://www.alluc.ee/l/The-Big-Bang-Theory-S09E14-1080p-HDTV-X264-DIMENSION/2medo223
