### ISSUE TITLE
anti-hacker-alliance.com's potentially harmful frames

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1196]
I don't know where else this could go and I thought this might fit into uBO's filters.
This website shows up sometimes if you search for an IP.
Example: hxxp://anti-hacker-alliance.com/index.php?ip=192.30.252.129
Their website is loaded with frames. The worst thing is: They load the IP you looked up as a frame. Of course this isn't an issue when using 3party-frame block but for everyone not using it it is problematic.
This specific filter would block it:

    |http://*.*.*.*/$subdocument,third-party,domain=anti-hacker-alliance.com
Maybe they also support looking up domains or IPV6 addresses. (I can't tell because they banned my IP after trying to look something up.) This filter also blocks a frame from rexswain.com so there might be a better filter.

**Comment by gorhill** [comment]
> I thought this might fit into uBO's filters.

No, this would turn me into a filter list maintainers, which I am not, unless it is to support uBO's specific syntax.

**Comment by IDKwhattoputhere** [comment]
I see. I'm going to suggest it for EasyPrivacy. Do you know a list where this would fit best?
