### ISSUE TITLE
Blocking bypassed (possibly) by using 192.168 in URL

### ISSUE THREAD

**Issue by pgl** [gorhill/uBlock#1197]
This URL (**NB: NSFW**):

http://192.168.cdn11.contentabc.com/images/adv_/ads/bz_315x300_517114/uploadMP4.mp4

is loaded with uBlock Origin enabled.

However, `contentabc.com` is included in my list - try to view the following URL with uBlock Origin enabled: http://contentabc.com

I believe this is because it's using `192.168` in the URL.

**Comment by Goderw** [comment]
Yes, it seems to be bypassed in this case -> I can confirm. In normal cases (w/o 192. in front of) contentabc.com is blocked by Peter Lowe’s Ad server list.

btw. 
The shown video is very special for testing purposes. ;)

**Comment by vzjrz** [comment]
Dude could you mark that link NSFW next time.

**Comment by pgl** [comment]
Is it possible to mark links as NSFW on Github?

Reference discussion: https://www.reddit.com/r/ublock/comments/4059az/ublock_origin_153_is_not_blocking_some_ads/

**Comment by pgl** [comment]
I've made a note in my original issue report.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> You will have to make the case that the issue is really with uBlock Origin and not something else on your side

The logger, it's there to be used.

**Comment by pgl** [comment]
I'm sorry for wasting your time. This is obviously something that has been already recognised. Again, sincere apologies, I hate to waste the time of someone who is doing something so worthwhile.

**Comment by gorhill** [comment]
@pgl sorry for handling the issue hastily, I realized after closing the issue who I was answering to.
