### ISSUE TITLE
How to create popunder filter

### ISSUE THREAD

**Issue by Nathgen** [gorhill/uBlock#1198]
Most of the sites create a pop up window even when i've disabled that pop up site, or it creates a new tab and closes or that malicious tab stays open when the user clicks on the page, whats the best way to make a popunder filter

**Comment by Betsy25** [comment]
Take a look at the [current popupunder filters](https://github.com/gorhill/uBlock/blob/d462bc197cd4171cd222c24169af65ca446c117f/assets/ublock/filters.txt#L205)

I'm not too knowledged, so don't take my words as 100% accurate, others will probably have a better explanation, but for the site that triggers the popunder, it's probably enough to add something like this to the "My Filters" list : 

```
||site_that_triggers_the_popunder^$popunder,popup
```

**Comment by Nathgen** [comment]
thanks, that's a start i didn't think about looking at the source first, i'll add one to the list and see if it works
