### ISSUE TITLE
question spanish

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uBlock#1199]
What about Spanish subscriptions?
https://adblockplus.org/en/subscriptions this page have two
EasyList Spanish & Filtros Nauscopicos

**Comment by rusingineer** [comment]
updated filter here https://easylist-downloads.adblockplus.org/easylistspanish.txt

**Comment by gorhill** [comment]
I added EasyList Spanish, however I won't add Filtros Nauscopicos, the list was last updated in 2013. People can still subscribe to it by clicking on it on the _"Known Adblock Plus subscriptions"_ page.
