### ISSUE TITLE
uBlock Origin 1.5.3 cause 'Content Encoding Error'

### ISSUE THREAD

**Issue by LearZhou** [gorhill/uBlock#1200]
with the following url: http://www.cnbeta.com/articles/465259.htm
The page shows as:

The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

Please contact the website owners to inform them of this problem.

Actually the url can be opened by other browsers.

BTW, I am using Firefox 43.0.4 mac version.

**Comment by SW1FT** [comment]
Not happening on my end, I'm using FF Dev Edition 45.0a2 on W10.

**Comment by LearZhou** [comment]
It's weird, it works fine now. It might not be a problem of uBlock then, a firefox issue in certain circumstances maybe.
