### ISSUE TITLE
Workaround for Youtube initial freeze and lag:  ||youtube.com/watch_fragments_ajax?*

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uBlock#1203]
Adding this filter seems to fix most of the issues mentioned in the following link: 
https://github.com/gorhill/uBlock/issues/907

**Comment by happysurf** [comment]
Works fine but I lose the comments, for complete loading page is good:
"@@|https://www.youtube.com/watch_fragments_ajax?v=*&tr=time&frags=guide"

**Comment by gorhill** [comment]
Ok, this is more a trick to address a Firefox issue on a specific Youtube page, as [originally reported on Reddit](https://www.reddit.com/r/firefox/comments/3zmu55/poor_performance_when_youtube_is_open_it_may_be/), I can't add this filter in uBO's filter, it's not really a uBO issue.

**Comment by AdKiller** [comment]
I'm using this filter:

||youtube.com/watch_fragments_ajax?*

and it has got rid of all the annoying lags and freezes I was experiencing on 90% of Youtube videos. Might be something worth looking into...
