### ISSUE TITLE
constructor.com and constructor.io websites appear blank

### ISSUE THREAD

**Issue by danmcc** [gorhill/uBlock#1206]
For constructor.com and constructor.io (and perhaps constructor.*), this gets inserted in the `<head>` and the whole page is blank:

```<style type="text/css">:root 
{display:none !important;}</style>```

I work at constructor.io, so if I can in any way help resolve this, please let me know.  We've tried to work around this by inserting our own `<style>:root {display: inline !important;}</style>`, but it only fixes the issue sporadically.

**Comment by anewuser** [comment]
https://github.com/gorhill/ublock/blob/master/CONTRIBUTING.md

**Comment by danmcc** [comment]
Thanks!  More details:

Versions: uBlock Origin 1.5.3 with cosmetic filtering turned on; Browser: Mac Chrome 47.0.2526.106 (64-bit)

To reproduce: open http://constructor.com.  The page will be blank.  If you turn off uBlock Origin (or just cosmetic filtering), the page will display.

I don't think this is related to a filter list, because the logger doesn't show any particular list that's causing this:

![image](https://cloud.githubusercontent.com/assets/171131/12226713/2ea4dbc8-b7ee-11e5-8eff-d81d4fde3ee9.png)

**Comment by gorhill** [comment]
Did you click on `##`?

**Comment by anewuser** [comment]
@gorhill I've found a similar problem with `stumbleupon.com` when the list `RUS: RU AdList (Дополнительная региональная подписка)‎` is enabled. It shows that the filter

    /^https?:\/\/[^/]+\/[a-z0-9]{15,}(\?hope=.*)?$/$script

is blocking

    http://nb9-stumbleupon.netdna-ssl.com/4AMJcGMiLnOT4iswOavSPw

But the infobox is blank when I click on it.

This happens on Firefox 43.0.3 (uBlock Origin 1.5.5) and Google Chrome (uBlock Origin 1.5.6 with default settings plus that Russian list).

**Comment by gorhill** [comment]
This is not a valid regular expression:

    /^https?://[^/]+/[a-z0-9]{15,}(\?hope=.*)?$/

They forgot to escape the backslashes:

    /^https?:\/\/[^\/]+\/[a-z0-9]{15,}(\?hope=.*)?$/

However uBO is supposed to detect bad regexes and reject them, and for some unknown reason, this is not detected by uBO. If I enter `var re = new RegExp('^https?://[^/]+/[a-z0-9]{15,}(\?hope=.*)?$');` in the browser console. this throws, as excepted. but somehow the same code does not throw in uBO. I have to investigate why.

**Comment by gorhill** [comment]
Ok so somehow even though the regex filter is missing some backslashes, it is still properly consumed by uBO, and properly enforced. Two issues:

1) that filter has potential to cause a lot of false positives, this is what is occurring on `stumbleupon.com`. Filter list miaintainers need to address this.
2) uBO uses the original representation of the filter at filter list lookup time. However that representation is faulty (missing escape slases), and this prevents uBO from finding the filter in the compiled filter list.

**Comment by gorhill** [comment]
@anewuser Can you open an issue for point 2.? Root cause is different than issue here.

**Comment by gorhill** [comment]
Side note: AdGuard's _Russian filters_ does not have that bad filter -- maybe I should add it to uBO's list of stock filters.

**Comment by anewuser** [comment]
I've reported that filter to the list maintaners and created a new issue for the regex problem: [#1246](https://github.com/gorhill/uBlock/issues/1246).
