### ISSUE TITLE
/r/uBlockOrigin/

### ISSUE THREAD

**Issue by Snow8** [gorhill/uBlock#121]
Hi,

after your recent statement "Maintainership transfer of uBlock: post mortem" and your intention to bring uBlock Origin to AMO, I thought it might be nice to have a subreddit for you addon on reddit. Lots of people talk about your addon on /r/firefox already.

http://www.reddit.com/r/uBlockOrigin/

If you have any objections, I will remove/delete the sub right away. If you are ok with it, I would like to give you mod rights and control over the subreddit.

As of now I haven't done much with the look and feel. If it is fine, I will adjust the CSS in the coming week to the colors of uBlock!

You can contact me here or on reddit if you prefer. I created this issue simply because I had no other way to reach out to you. Feel free to delete or close it!

**Comment by gorhill** [comment]
Thanks for this, nice to see. I don't intend to run myself a forum of any sort, but I am happy if volunteers jump in to take care of this -- it's pretty much how I envision things, nothing formal, just volunteers jumping in whenever they want to address needs which I do not have the time to fully take care myself. I will try my best to visit to answer whatever technical questions<sup>[1]</sup>, as time allows.

Given the state of uBlock Origin, I suspect most issues users are facing nowadays are about filters, filter lists, or how to use advanced features such as dynamic filtering.

<sub>[1] Just in case, I don't intend to say anything more re. post-mortem, I said pretty much all I felt I needed to say about this.</sub>
