### ISSUE TITLE
Whitelist doesn't work

### ISSUE THREAD

**Issue by maxoku** [gorhill/uBlock#1211]
Filters for my language (pol) blocked whole input box for writing new e-mails. I turned it off, blocked that box and added "@@" in front of whole code. I did it with whole page too, but after enabling filters it is still blocked. Seems like white list doesn't work at all on external filters, only for my own.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
