### ISSUE TITLE
Ad blockong doesn't work in popup dialog windows

### ISSUE THREAD

**Issue by maxoku** [gorhill/uBlock#1212]
I have a personal filters that block some adds in certain page. I open that page in a pop-up dialog window. Unfortunately adds aren't blocked there. Before I used AdBlock Plus and adds were blocked everywhere.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by maxoku** [comment]
Why did you close this topic?

**Comment by harshanvn** [comment]
Read the contributing.md 
You need to provide the proper steps to reproduce the issue.  Tell what are your browser settings,  addons installed,  uBlock origin details...
