### ISSUE TITLE
Whitelist doesn't work

### ISSUE THREAD

**Issue by maxoku** [gorhill/uBlock#1213]
Filters for my language (pol) blocked whole input box for writing new messages in my e-mail site. I've added filter with "@@" for that box and whole page too in my personal filters. Unfortunately it doesn't work, input box is still blocked/hidden. Seems like my exception filters doesn't work on extension filters. Is it a bug or I am doing something wrong?

**Comment by anewuser** [comment]
@maxoku Problems with filters must be reported to their authors: https://github.com/MajkiIT/polish-ads-filter/issues
