### ISSUE TITLE
Update Reek Anti-Adblock killer filters URL

### ISSUE THREAD

**Issue by Cormak** [gorhill/uBlock#1214]
Reek's Greasemonkey extension kept telling me to add his filterlist even though I had it enabled in uBlock, but it seems the URL in uBlock is out date. Here's the current URL so people don't have to manually add his URL and disable the built-in URL. 

https://reek.github.io/anti-adblock-killer/#filterlist

**Comment by seanrand** [comment]
The filter list URL is (and has been) https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

I don't see any update notifications here, using Chromium 48 - and the [AAK Settings](https://reek.github.io/anti-adblock-killer/#settings) show "List: Subscribed" for me.

**Comment by gorhill** [comment]
URL used by uBO works fine.
