### ISSUE TITLE
[Request] Allow browser specific rules

### ISSUE THREAD

**Issue by tcptomato** [gorhill/uBlock#1215]
Unfortunately not all functionality is implemented on all browsers ( script:contains would be a perfect example). I think it would make sense to allow for browser specific rules, like

`example.com##script:contains(ads)$firefox`
`example.com$inline-script,chrome`

**Comment by IDKwhattoputhere** [comment]
I had a similar idea here: https://github.com/gorhill/uBlock/issues/1178#issuecomment-169191879
Yours seems better though.

**Comment by tcptomato** [comment]
@gorhill What would be your recommendation to use in a filter list to block things efficiently on both browsers? Using a coarse filter (for chrome) on firefox ( where you can use a finer one) is not the most efficient thing in the world.

**Comment by gorhill** [comment]
Blocking inline scrip is easy using dynamic filtering pane. The wholesale blocking inline scripting by default should be left to the user given how this can cripple a site.

**Comment by tcptomato** [comment]
I'm sorry, I think I should have explained the use case better. It's to remove some annoying anti-adblocker scripts on specific sites, not something that should be done by default. The option here would be not use the site at all, or use it in a crippled fashion. (if using the inline-script option). Unfortunately this filter could be replaced with a better one on firefox, but at the moment it can't be done in an automatic fashion using a single list for both browsers.

And I don't want to impose myself, but could you please give me a feedback on my pull request.
