### ISSUE TITLE
Chip.de Video not working correkt with Firefox 44b8 and ublock 1.5.5

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#1216]
look @ 

http://www.chip.de/video/Drohnen-Helikopter-ohne-Pilot-Video_87914692.html
http://www.chip.de/news/Die-Zukunft-des-Gamings-Virtual-Reality_87864177.html
http://www.chip.de/artikel/Notebook-Preis-Leistung-Guenstige-Laptops-im-CHIP-Test_64439568.html

the video works without ad, but the video play a little and looks only white than!

dellet cache from firefox and ublock filters not work!

(sry for my bad english)

greetings

**Comment by Betsy25** [comment]
Confirmed on Firefox v46 + uBo 1.5.3.rc0

Please always try to explain what browser and uBlock version you have the issue with. [Contributing](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

**Comment by akks1981** [comment]
ok sry 

Firefox 44b8 + uBo 1.5.5
