### ISSUE TITLE
Why does this filter not work?

### ISSUE THREAD

**Issue by madranet** [gorhill/uBlock#1217]
I'm trying to block the annoying 'People you might like to follow' panel on Twatter. It appears inside a DIV with ID: 

```
stream-item-who_to_follow_entry-xxxxxxxxxxxxxxxxxx
```

Where xxxxxxxxxxxxxxxxxx is some random number.

I've created the following filter:

```
! 11/12/2015 13:08:47 https://twitter.com/  
twitter.com###stream-item-who_to_follow_entry-*
```

But I'm still seeing that panel. The weird thing is that, if I add the exact same filter again and reload the page, uBlock Origin blocks the element but, for some reason doesn't catch it on first loading the page. Am I doing something wrong, or is this an unexpected behaviour?

**Comment by gwarser** [comment]
http://www.w3.org/TR/css3-selectors/#attribute-substrings

**Comment by gorhill** [comment]
Cosmetic filters have to be valid CSS selectors: <https://adblockplus.org/filter-cheatsheet#elementhiding>.

**Comment by RichGriese** [comment]
madranet

The filter you want to add is this;

twitter.com##*[id^='stream-item-follow_entry-']
