### ISSUE TITLE
QR code For web Whatsapp not showing even if whitelisting

### ISSUE THREAD

**Issue by algui91** [gorhill/uBlock#1218]
Hi,

After a few days wondering why the QR code for log in to whatsapp via web, I've discovered that I have to completely disable the plugin in order to the QR code to show and be able to log in.

It seems that ublock, although being disabled for whatsapp, still blocks this request:

![screenshot from 2016-01-12 21 50 46](https://cloud.githubusercontent.com/assets/394797/12276556/c3ee320e-b976-11e5-9003-b7e9bcd54530.png)

## Some captures

![screenshot from 2016-01-12 21 54 15](https://cloud.githubusercontent.com/assets/394797/12276629/152f8f28-b977-11e5-9720-c07451466688.png)

## Reproduce the bug

1. Go to web.whatsapp.com
2. WhiteList the page
3. The QR code does not show
4. Disable ublock
5. Go to the website
6. The QR now shows

The same occurs to me with google Analytics and some other Google apps.

Best regards 

## Details 

- Firefox 43.0
- OS: Linux Mint Debian Edition (64bits)

**Comment by gorhill** [comment]
The page displays fine here. You are probably blocking something which is not blocked when using default settings. Use the logger to find out why that request is blocked.

**Comment by algui91** [comment]
It seems that nothing is getting blocked:

![screenshot from 2016-01-12 22 47 14](https://cloud.githubusercontent.com/assets/394797/12277943/7ef1ce7e-b97e-11e5-9a9e-ef580e711091.png)

**Comment by gorhill** [comment]
Did you select _All_ in the dropdown selector?

**Comment by algui91** [comment]
Sorry, only selected whatsapp. Now its working. Thank you!

**Comment by gorhill** [comment]
You were blocking behind-the-scene requests?

**Comment by anewuser** [comment]
That's a base64-encoded image. Maybe the generated image/code had some string of characters like "ad" that was covered by one of @algui91's filters.

![untitled-1](https://cloud.githubusercontent.com/assets/6733770/12278108/578f6ae8-b966-11e5-8cc2-64ed97dad31b.png)

**Comment by gorhill** [comment]
@anewuser uBO won't touch images which do not starts with `http`/`https`.

**Comment by algui91** [comment]
@gorhill, yes, a behind scene request.

**Comment by anewuser** [comment]
@gorhill For some reason I was sure that I was able to hide an overlay inline image like that months ago. It seems that I just used some CSS class to remove it from a video player.
