### ISSUE TITLE
"Reset settings" shouldn't delete filter lists updates

### ISSUE THREAD

**Issue by vlakoff** [gorhill/uBlock#1219]
An effect of using the "Reset to default settings..." button is that the filter lists updates are deleted.

* It's very surprising and really unexpected (at least for me).
* Downloading the updates again takes a noticeable amount of time.
* There is already a "Purge all caches" button if one really needs to delete the filter lists updates.

**Comment by gorhill** [comment]
It's by design -- this allows to wipe clean the storage and there is no guarantee that the filter lists selected post-reset will be the same as the filter lists pre-reset.
