### ISSUE TITLE
Custom filters for redirect?

### ISSUE THREAD

**Issue by Masung** [gorhill/uBlock#1220]
I noticed the new addition of "redirects" in Ubo. But as i understand it only some predefined redirects are allowed? If this is the case, are there any plans on allowing custom ones? specifically for "behind-the-scene" connections?

I'm asking because there are a couple of "popular" firefox addon(s) that gives away a bit to much personal information trough the update url of their filters.
I know the Redirect addon can do this. but its unsigned and will stop working shortly.(thnx mozilla)

**Comment by gorhill** [comment]
The purpose of uBO's `redirect` filter option is to use a local resource in place of a remote one, it is not to rewrite URLs.

**Comment by Masung** [comment]
Oh i see... Not the answer i was hoping for, but understandable :)

**Comment by anewuser** [comment]
@Masung  See if [Redirector](https://github.com/einaregilsson/Redirector#download-links) can do what you want and please close this issue.

**Comment by Masung** [comment]
@anewuser sorry for not being more clear, this is the extension i was referring to have tried. But its not signed thus its blocked in latest Firefox

**Comment by anewuser** [comment]
@Masung You don't know what you are talking about. It of course is signed, just like any other extension updated and reviewed in the last months on the official Mozilla site. However, please use its repository if you have to report any problems you have with it.

**Comment by gorhill** [comment]
@Masung All extensions on AMO are signed. [Redirector is on AMO](https://addons.mozilla.org/en-GB/firefox/addon/redirector/), thus it is signed.

**Comment by Masung** [comment]
@anewuser @gorhill My apologies then. i checked the extension on AMO and it hasn’t been updated since September. and since i didn't see "-signed" in gray text beside the name like the other popular extensions i checked at the time, i assumed it will stop working when they start forcing signed extensions in Firefox.

Now my question is. why does some extensions have the label "-Signed" beside it, and some not? can the creator type whatever they want there?

**Comment by gwarser** [comment]
".1-signed" was used to bump extension version number, so Firefox will update to signed version.

**Comment by gorhill** [comment]
> why does some extensions have the label "-Signed" beside it, and some not? 

An extension with the `-signed` suffix means it was never updated by their owner after it was signed by AMO.
