### ISSUE TITLE
Swap button location to be consistent with uMatrix

### ISSUE THREAD

**Issue by yupi2** [gorhill/uBlock#1221]
The placement of the **eraser** and the **lock** buttons are swapped from uMatrix's placement. This can cause accidental edit savings or deletions.
[uBlock's placement](http://i.imgur.com/gfS8kKG.jpg) - [uMatrix's placement](http://i.imgur.com/29EshN2.jpg)

**Comment by zummuz** [comment]
How often user should add changes to get muscular memory for save/erase action?
Even if it was real problem, uBlock's user base is larger than uMatrix'es, so uMatrix icons would have to be swapped, I guess.

**Comment by Havokdan** [comment]
Another thing that could be done is to put the buttons to save backup, restore and restore to the default in the same places, since the buttons are on the tab uBlock "settings", while in "about" staying in uMatrix.

I'm sorry, I made use of online translator.
