### ISSUE TITLE
Hover text over logger options

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1222]
In the logger, there are only icons and no text within the logger itself explaining what each button does which is confusing. Each icon should have a hover text e.g. 'Reload' to make it easier to identify and use. Should also hover full URL over urls that are long (when dropdown is not clicked).

Also somewhat related to #1163 that can help, is it possible to add option in logger to sort by: 1) request/response size 2) request/response type 3) blocked/allowed and being able to select multiple lines in the logger?

**Comment by ReticentAdjuvant** [comment]
MouseOver text is also something I'd like to see in the logger. I was ecstatic when they were added to the per site switches.

**Comment by stonecrusher** [comment]
I also would appreciate tooltips in the logger. It feels very incomplete and especially the X needs a reminder. Suggestions:
`Reload`
`Tree view` `List view`

In list view:
`Expand` `Collapse`
`Clear closed`
`Clear all`
`Filter on` `Filter off`

In tree view:
`Expand all elements` `Collapse all elements`
`Expand lines` `Collapse lines`
`Discard changes`
`Save changes as rules`

Furthermore I also vote for showing the full URL on hover (with a little delay, of course) without having to expand all and having to search again for that entry in the now elongated list. But that's another issue.
