### ISSUE TITLE
High hidden elements counter

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1223]
uBO displays an absurdly large number of hidden elements.
How to reproduce:
1. Install uBO 1.5.6
2. Visit https://donottrack-doc.com/en/episodes/
Result: uBO reports over 200 hidden elements. The logger reports way less.
Happens in Chrome 47 and Firefox ESR 38. However can't reproduce in a new profile.
[Configuration](https://github.com/gorhill/uBlock/files/89158/my-ublock-backup_13.1.2016._17-15-48.txt)

![](https://cloud.githubusercontent.com/assets/16030872/12299772/c01da252-ba18-11e5-8772-d0fcfbf84baf.png)
![](https://cloud.githubusercontent.com/assets/16030872/12299771/c0189938-ba18-11e5-87e8-f8ca52a011cd.png)

**Comment by gorhill** [comment]
The count in the popup is the number of DOM elements hidden. The logger shows the cosmetic filters which have an effect on the page, it's not the same as the number of elements. I could not reproduce with default settings, and anyway, you will have to make the case that uBO is not actually hiding 217 elements on the page -- I am not responsible for how people design their sites.

**Comment by IDKwhattoputhere** [comment]
I attached my config because this doesn't happen by default. I only see a single thing that's actually hidden (the cookie notification). I thought this might be a bug since the logger only shows a few hidden items.

**Comment by gorhill** [comment]
> I attached my config

Sorry I missed this, I am testing some local code which hid the attachment image.

> I thought this might be a bug since the logger only shows a few hidden items.

The logger does not report hidden items, it report which injected cosmetic filters have an effect on the page. One single filter can affect hundreds of DOM elements. The popup reports the number of affected DOM elements.
