### ISSUE TITLE
herofw

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1224]
hi. i am kind of confused. i see that we are using the ##script:inject(yavli-defuser.js) filter for the yavli sites. is that the same as herofw because i tried using it on the site below and it wouldn't block the domain used by herofw: http://fruamens.com/adBlockDetector/12372

site used on:

http://www.whowhatwear.com/kate-moss-david-bowie-outfit/slide3

**Comment by gorhill** [comment]
I don't know what "herofw" is. I could load and see the site at the link you posted above just fine. Please see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
