### ISSUE TITLE
beforeitsnews adblock popup

### ISSUE THREAD

**Issue by craigevil** [gorhill/uBlock#1227]
Beforeitsnews.com now has a adblock warning popup that is not blocked.

**Comment by anewuser** [comment]
Post it on the forum of the list you use. This issue tracker is for reporting extension bugs.

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by Betsy25** [comment]
Or add the following line to your "My Filters" list.
```
beforeitsnews.com##script:contains(afs_ads)
```

**Comment by gorhill** [comment]
Report to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=62>.

What works meanwhile: [disable generic cosmetic filtering for the site](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering). (this is the equivalent of `@@||beforeitsnews.com^$generichide`, the solution that will likely be proposed by EasyList maintainers).
