### ISSUE TITLE
Describe filters that require external software support

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1229]
```Settings -> 3rd-party fitlers -> Anti-Adblock Killer | Reek‎```: This filter is used to enable AAKScript as explained by the author in https://github.com/reek/anti-adblock-killer.

I suggest that you explain that in the title of the filter to avoid confusion, with something like: ```Anti-Adblock Killer | Reek‎ [used to enable <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">AAKScript</a>]```

**Comment by anewuser** [comment]
Did you click on the "i" icon next to the list name?

**Comment by flyingzebras** [comment]
@anewuser This is embarrassing. Thanks.
