### ISSUE TITLE
Add deals.sourceforge.net to Badware Risks list

### ISSUE THREAD

**Issue by vgturtle127** [gorhill/uBlock#1231]
Hey, Gorhill. I just realized **http://deals.sourceforge.net/** is serving ads to all SourceForge users.

I would recommend just blacklisting deals.sourceforge.net, but maybe you have a different approach that is more elegant?

Here is a screenshot to illustrate what I am talking about:

![screenshot 19 2](https://cloud.githubusercontent.com/assets/3183676/12346254/777dce0e-bb18-11e5-9ef5-14353ca9ecde.png)

Here are the links to the images and also some links uBlock, my firewall, and some other applications picked up while I was sniffing for where the ad was coming from:

* http(s)://images.stackcommerce.com/assets/productshot1-image/11530/641ceb634cb533e48ba6aa5e0105ebb8e4e6e7f5_main_hero_image.jpg

These can be created with the "block element" feature in uBlock Origin:

    Net filters
        ||images.stackcommerce.com/assets/productshot1-image/11530/641ceb634cb533e48ba6aa5e0105ebb8e4e6e7f5_main_hero_image.jpg
    Cosmetic filters
        ##.ss-deals-image[alt="deals_image"]
        ##.stackcommerce-widget.sidebar-widget
        ##.ss-deals-link[href="https://deals.sourceforge.net//sales/lifetime-of-purevpn"]
        ###files-sidebar
        ###page-body

Here is another image I found:

* http(s)://image-assets.stackcommerce.com/images/2346/medium_2346_pwywgamedeveloperbundle_mf-primary1.jpg

Block element filters:

    Net filters
        ||image-assets.stackcommerce.com/images/2346/medium_2346_pwywgamedeveloperbundle_mf-primary1.jpg
    Cosmetic filters
        ##.ss-deals-image[alt="deals_image"]
        ##.stackcommerce-widget.sidebar-widget
        ##.ss-deals-link[href="https://deals.sourceforge.net//sales/the-pay-what-you-want-game-developer-bundle"]
        ###files-sidebar
        ###page-body

Some filters for the text and related parts of the image:

 Cosmetic filters

    ##.ss-deals-title
    ##.ss-deals-title-box
    ##.ss-deals-footer
    ##.stackcommerce-widget.sidebar-widget
    ##.ss-deals-link[href="https://deals.sourceforge.net//sales/the-pay-what-you-want-game-developer-bundle"]
    ###files-sidebar
    ###page-body

Percentage:

 Cosmetic filters

    ##.ss-deals-price-box
    ##.ss-deals-footer
    ##.stackcommerce-widget.sidebar-widget
    ##.ss-deals-link[href="https://deals.sourceforge.net//sales/the-pay-what-you-want-game-developer-bundle"]
    ###files-sidebar
    ###page-body

Anyway, you get the idea. What is the best way for me to add these ads to the badware risks filter, and what is the best method of blocking all of them?

I found the filter file, but it doesn't have a repository, just a Wiki page.

Anyway, thanks for uBlock!

**Comment by gorhill** [comment]
`sourceforge.net` is already in _Badware risks_, no point adding subdomains.

**Comment by vgturtle127** [comment]
Well, but I mean there is an ad there, and it isn't being blocked. Shouldn't we add something so that it is blocked?
