### ISSUE TITLE
uBlock blocks youtube css and images

### ISSUE THREAD

**Issue by zyrikby** [gorhill/uBlock#1232]
It seems that uBlock is responsible for blocking loading of css and images on youtube. I experienced the problem and after disabling uBlock on this webpage it disappears. I assume that maybe this is not the problem of uBlock itself but the used blacklists. However, I did not enable any additional list, so this functionality is available for the default version.

**Comment by PSeitz** [comment]
+1, this issue occurs only since yesterday

**Comment by PSeitz** [comment]
the issue disappeared updating the filter lists

**Comment by randfur** [comment]
Seems to be the malwaredomains.com filter with the rule `||s.ytimg.com^` blocking things like:
 - https://s.ytimg.com/yts/cssbin/www-home-c4-webp-vflqOmQC5.css
 - https://s.ytimg.com/yts/cssbin/www-guide-webp-vfl5jXYL4.css
 - https://s.ytimg.com/yts/cssbin/www-pageframe-webp-vflRPu9a5.css
 - https://s.ytimg.com/yts/cssbin/www-core-webp-vflaLpYYk.css
