### ISSUE TITLE
uBlock Experimental -  googletagservices blocking causes problems

### ISSUE THREAD

**Issue by Stefan-Code** [gorhill/uBlock#1234]
The rule `||googletagservices.com/tag/js/gpt.js$important,script` in the uBlock experimental list breaks the pretty popular german ["ebay kleinanzeigen"](http://www.ebay-kleinanzeigen.de/). (Search doesn't really work, image loading problems in gallery sometimes).
I am suprised this is happening as it's actually a redirect rule.
Unbreaking with`@@||www.googletagservices.com/tag/js/gpt.js$script,important,domain=www.ebay-kleinanzeigen.de` doesn't work unfortunately. 

I'm Using uBlock origin 1.5.6 and Chromium Version 45.0.2454.101

Page looks like this when broken:
![ebay kleinanzeigen broken](http://i.imgur.com/mu3LFbS.png)
Images missing and location search radius box empty. Page keeps loading forever.

**Comment by gorhill** [comment]
Unable to reproduce, works fine here. I will re-open if you provide all the information that _make the case_ that "googletagservices blocking causes problems".

**Comment by Stefan-Code** [comment]
Just tried it with a fresh firefox profile and it indeed works, which is weird because in chromium the problem only went away when manually allowing `googletagservices.com`. I'll see if I can reproduce it with a clean profile.
