### ISSUE TITLE
[Request] Change the frequency in which custom user filter-lists are updated

### ISSUE THREAD

**Issue by SurenSK** [gorhill/uBlock#1235]
Is there some existing method of forcing my Custom 3rd-party filter to 'Purge Cache' and auto-update on browser launch?

**Comment by Stefan-Code** [comment]
You could adding `! Expires: 1 hour` to your list header.

**Comment by SurenSK** [comment]
I did try that actually. However, it didnt work unfortunately. From what Ive found out through googling those tags only work for the 'official' 3rd party lists.

https://adblockplus.org/filters, "Special comments will only have an effect in downloaded filter lists, not in custom filters." I realize that thats a different 'branch', but the syntax they use is identical (same filterlists, formatted the same way for both).

**Comment by Stefan-Code** [comment]
`! Title` works for me, I haven't tried the others to be honest.
