### ISSUE TITLE
YouTube Format Broken 

### ISSUE THREAD

**Issue by thehello40** [gorhill/uBlock#1238]
YouTube format seems to be broken on the latest update. The format goes back to normal when disabling the extension. 
![issue](https://cloud.githubusercontent.com/assets/16723368/12360233/9c0a2ee0-bb6b-11e5-9300-54999ca0bed4.png)

**Comment by gwarser** [comment]
Go to 3rd-party filters pane and click Update now.

**Comment by thehello40** [comment]
Thank you!
