### ISSUE TITLE
Dynamic filters are not saved

### ISSUE THREAD

**Issue by GSNord** [gorhill/uBlock#1239]
I am using uBlock Origin on Firefox mobile 42.0.2 on an Android 5.1 device. I have no static filter list, I only use dynamic filtering.
So I am in the dynamic filtering pane in advanced modus. I click all the ad sites to red in the left column, so this should apply global to all sites.

However, when I restart firefox, or even visit another site and come back to the first site later, all filtering rules are forgotten.

**Comment by Betsy25** [comment]
Have you clicked the "lock" icon in the top left to make your settings permanently ?

**Comment by GSNord** [comment]
Betsy, you are telling me something...
ok, found the lock symbol. It only pops up when I change one the filters. Seems to work now.
So I remember that dynamic filters were saved automatically in a previous version, wasn't it?

**Comment by gorhill** [comment]
> So I remember that dynamic filters were saved automatically in a previous version, wasn't it?

This has been like this for months.
