### ISSUE TITLE
Add µblock0 to Addons Firefox

### ISSUE THREAD

**Issue by qwertygc** [gorhill/uBlock#124]
Hello !
It's possible to add µblock origin to https://addons.mozilla.org/ ?

Regards

**Comment by alain1965** [comment]
Hello, @gorhill try with the actual version 0.9.5.0 like it's a fork of his creation (ublock) why not ? Adblock Edge is yet on AMO and Adblock Plus too and in the past they had the same icon but after the bul.....t of the transmition of ublock from @gorhill to alex vallat maybe it will have some problems like Betsy25 writed in #116.

**Comment by gorhill** [comment]
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by kintpuash** [comment]
:thumbsup:

**Comment by qwertygc** [comment]
Think you is perfect :)

**Comment by alain1965** [comment]
Yeeeeesssssss !

**Comment by petersaints** [comment]
The addon is still not reviewed, and you haven't submitted 0.9.6.0 yet. Have you selected the addon for Full Review or Preliminary Review?

The Firefox Add-ons Website has been extremely SLOW at approving add-ons and updates. It's a bit annoying! Don't you think so?
