### ISSUE TITLE
yavli

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1240]
hi. i noticed the yavli urls are not blocked anymore. did they change the method?

my browser version is chrome 49.0.2622.0 ublock version 1.5.6 origin from chrome store

example url: http://www.activistpost.com/2016/01/sunny-nevada-just-killed-the-solar-industry-with-40-tax-hike-derailing-the-off-grid-movement.html

**Comment by gorhill** [comment]
Yes, they changed something. Go to _3rd-party filters_ pane, purge cache of _uBlock filters_, then click _Update now_.

**Comment by jo2dan23** [comment]
frustrating they changed it again :(

**Comment by gorhill** [comment]
Purge the cache for "uBlock filters", then click _"Update now"_.

**Comment by jo2dan23** [comment]
they changed it again :(

**Comment by jo2dan23** [comment]
how do they keep bypassing this :( changed it again

**Comment by gorhill** [comment]
I do not get the ads, maybe a fix was added to EasyList, force an update of it.

**Comment by jo2dan23** [comment]
yea. element is only hidden. it still connects to ad domain: http://buandirs.net/botryogen/bronzite/2015/08/beudantite-dragunow6994a-j1g652nk8pr.png

on:

http://www.latinpost.com/articles/113214/20160203/puerto-rico-news-2016-leaders-urge-congress-to-act-on-health-economic-crises.htm

**Comment by gorhill** [comment]
> it still connects to ad domain

Not here. As said, force an update.

**Comment by IDKwhattoputhere** [comment]
Am I wrong or are you missing rightwingnews.com? https://reports.adblockplus.org/24d80a1f-253d-464c-aaf3-6c4980395499

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/fe98eda1be89

**Comment by jo2dan23** [comment]
allenbwest.com,askmefast.com,chacha.com,christianpost.com,christiantoday.com,classicalite.com,comicbookmovie.com,dailyheadlines.net,digitaljournal.com,enstarz.com,gamezone.com,heroichollywood.com,hngn.com,infowars.com,kdramastars.com,kpopstarz.com,latinopost.com,listverse.com,mstarz.com,musictimes.com,naturalnews.com,natureworldnews.com,newser.com,rantlifestyle.com,realfarmacy.com,spectator.org,starmagazine.com,stevedeace.com,techtimes.com,thechive.com,townhall.com,variety.com

these sites are missing from your yavli list also.

**Comment by jo2dan23** [comment]
how does this one still have ads and the other sites listed in your yavli list don't? is it not a yavli based ad they are hosting?

http://libertyunyielding.com/2016/02/06/libs-love-the-so-called-establishment-clause-except-when-it-gets-in-the-way-of-proselytizing/

**Comment by gorhill** [comment]
The ones I did not include I have verified they did not contains the code which is defused by the filter I have for Yavli ads. This will require some investigations to figure what else need to be done for these other sites.

**Comment by ryanbr** [comment]
Some sites will inject an imagemap (internal and external), while other Yavli sites will simply add an external javascript to load it.  I'll just blanket block any sites from using Yavli, seems the only way we get attention away from this insidious adserver, and hide via some funky element rules.

**Comment by jo2dan23** [comment]
the must have changed it again. having my elements not hidden it shows the ads

http://www.activistpost.com/2016/01/sunny-nevada-just-killed-the-solar-industry-with-40-tax-hike-derailing-the-off-grid-movement.html

**Comment by jo2dan23** [comment]
changed again :(

**Comment by jo2dan23** [comment]
changed again

**Comment by ryanbr** [comment]
Given I'm filtering via his href links, it'll keep changing regularly.

**Comment by jo2dan23** [comment]
@ryanbr are you the official fanboy list maintainer?

**Comment by jo2dan23** [comment]
looks like they have changed it again. only being hidden by elements

**Comment by jo2dan23** [comment]
traileraddict.com and cheatsheet.com can be added to the yavli filter list

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/d01214b1c19a
https://hg.adblockplus.org/easylist/rev/351dbda4e738

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/663e664df0c0

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/0bede29bcea0

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/a171ffed1990

**Comment by jo2dan23** [comment]
looks like they changed it again

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/637b5ddf5b7e

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/1da5135cdbc5

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/c1a72dacf63f

**Comment by jo2dan23** [comment]
changed again

**Comment by ryanbr** [comment]
I'm not seeing anything here, which site?

**Comment by ryanbr** [comment]
I have noticed he's updated a few adservers, I'd say he'll be updating the sites again soon.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/e663aac86cb7

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/af1d053f81b8

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/39a93f461f4a

**Comment by jo2dan23** [comment]
changed again

**Comment by jo2dan23** [comment]
another yavli site:

http://www.faithit.com/man-is-crying-by-her-gas-pump-when-she-sees-his-wife-covering-her-face-in-the-car-she-knows-spiritual/#.Vv7gIAyWUD4.facebook

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/803f7a6c4990

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/83c33c27b0c3

**Comment by Betsy25** [comment]
*yawn*

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/698dde55807a

**Comment by ryanbr** [comment]
http://pastebin.com/raw/8VJmVi00

https://hg.adblockplus.org/easylist/rev/99accdc33083

**Comment by gorhill** [comment]
> `http://pastebin.com/raw/8VJmVi00`

Thanks. In the process of checking/confirming each one of them, I found another one: `100percentfedup.com`.

Also, there are adblade ads on `coviral.com`, this filter works for me: `||coviral.com/*callback=callback_json_adblade*$script,first-party`.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/748432ee45a3

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/7429ff8abdf5

**Comment by ryanbr** [comment]
http://pastebin.com/raw/A8na6iHR

**Comment by ryanbr** [comment]
http://pastebin.com/raw/SLQTwWD0
https://hg.adblockplus.org/easylist/rev/d6448aed08e9

**Comment by ryanbr** [comment]
And lastly; https://hg.adblockplus.org/easylist/rev/cc26004e2a55

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/338106808f1e

**Comment by ryanbr** [comment]
Safe to remove unilad.co.uk, they've remove Yavli after speaking with us.

**Comment by ryanbr** [comment]
http://pastebin.com/raw/9aL0jdZT

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/aeacbac39771

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/ad5f2a1126fc

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/edb1aca564e2

**Comment by ryanbr** [comment]
http://pastebin.com/raw/x4RpXxUc

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/023ebd9359be

**Comment by ryanbr** [comment]
http://pastebin.com/raw/EfMug57v

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/20616b951e61

**Comment by ryanbr** [comment]
http://pastebin.com/raw/47vYE34X

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d0b8aae4aa563db1a8cc5551227f2047f962c869

**Comment by ryanbr** [comment]
http://pastebin.com/raw/DAEnxQNc

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/14ef956fe966153c17561e281c0e179f0d05abcb

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/48c35c2c5d29ce01aa9b8c78914b9579faf03f37

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f145ea8fbc248cafbf0c7172ea6f6c5a2819cdb2

**Comment by ryanbr** [comment]
http://pastebin.com/raw/HSwPMwiD

**Comment by gorhill** [comment]
@ryanbr I also needed `||patriotupdate.com/*callback_json_adblade$script` for `patriotupdate.com`.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/91bce116b4e0f7d2018e83ce46560293a90d9b24
