### ISSUE TITLE
Breaks YouTube

### ISSUE THREAD

**Issue by thdoan** [gorhill/uBlock#1242]
I noticed today that YouTube breaks with uBlock enabled (it was fine before) -- I have to manually whitelist youtube.com. Is this a known issue?

**Comment by gwarser** [comment]
Go to 3rd-party filters pane and click Update now.

**Comment by gorhill** [comment]
Dup of #1232.

**Comment by seiyria** [comment]
For some reason my "update now" button is disabled. even if I hit "auto update filter lists" the option becomes unchecked if I navigate away from that tab. Not sure if that's a separate bug but it's annoying.

**Comment by gorhill** [comment]
> For some reason my "update now" button is disabled

[Doc](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters) says: "[_Update now_] button is available for use if and only **if there is at least one filter list which is deemed outdated**".

> if I hit "auto update filter lists" the option becomes unchecked if I navigate away from that tab

Unable to reproduce.

Anyway, if you were to open an issue with your comment, it would be closed as _invalid_ and _unable to reproduce_: [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by seiyria** [comment]
For whatever reason, I had to fully restart chrome (ie, kill all processes) and everything started working again. The UI looks completely different compared to earlier, and I'm not sure what I did to get in that state. Guess that's not uBlocks fault.

**Comment by Hrxn** [comment]
>For whatever reason, I had to fully restart chrome (ie, kill all processes) [...]

I sincerely hope you didn't literally kill Chrome's processes..
Always close it properly. Always close all Browsers properly.

**Comment by gorhill** [comment]
Even quitting Chromium/Chrome, there can be processes left running into memory. Probably has to do with the setting "Continue running background apps when Chromium is closed", something which I disable. I never checked whether this setting causes uBO to stick into memory after leaving Chromium.

**Comment by Hrxn** [comment]
Yes, disabling that setting is definitely a good idea. I always turn it off as well.

I have seen this feature only in use on Windows, so I am not sure how it works on other OS.
But on Windows, for example, if you use Google Drive and close all Chrome windows, the processes are still running in the background (doing Google Drive sync, etc. obviously). You now have a small Google Drive icon in your system tray, and when you exit this, all running processes stop subsequently.

I can only speak for myself here, but regardless of all other quirks I've encountered while using Chrome/Chromium so far, an incomplete program exit has never happened to me.
