### ISSUE TITLE
uBlock partly breaks AMD.com

### ISSUE THREAD

**Issue by Nuc1eoN** [gorhill/uBlock#1245]
Hi, I have noticed that uBlock partly breaks the links on AMD.com.
To reproduce just enter the main site (www.amd.com) and press one of the black buttons/links (not in the navigation). You will see that there is no reaction all. Those buttons get blocked for no reason.

**Comment by anewuser** [comment]
Please read this: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). This issue is going to be closed if you don't follow the guidelines.

**Comment by gorhill** [comment]
Report to [EasyPrivacy maintainers](https://forums.lanik.us/viewforum.php?f=64) -- blocking the following breaks the page:

    ||googletagmanager.com/gtm.js?$third-party
    ||google-analytics.com/analytics.js
