### ISSUE TITLE
Programmatically change settings

### ISSUE THREAD

**Issue by szepeviktor** [gorhill/uBlock#1247]
How is it possible to check `I am an advanced user` from Firefox's user.js?
If it is impossible then do you plan to support this?

*I use uBlock and Firefox without any installation, by just [extracting the setup.exe](https://github.com/szepeviktor/windows-workstation/blob/master/ff-dev/START-ffdev.cmd#L33-L36), then deleting everything.*

Thanks.

**Comment by gorhill** [comment]
In `about:config`, add `extensions.ublock0.adminSettings` as a string value, and set it to `{"userSettings":{"advancedUserEnabled":true}}`. This content of `extensions.ublock0.adminSettings` will always write over whatever user settings it declares.

See <https://github.com/gorhill/uBlock/issues/531>.

**Comment by szepeviktor** [comment]
You're very kind.

**Comment by szepeviktor** [comment]
Meanwhile my hack proved to be working:
- strip down ublock0.sqlite to just the needed rows
- copy it to `%PROFILEDIR%\extension-data\`
- start Firefox
