### ISSUE TITLE
unblocked google analytics

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1248]
hi. i saw a unblocked google analytics script is it possible to do a redirect and block like we do for the ga.js and analytics.js ones?

https://www.google-analytics.com/plugins/ga/inpage_linkid.js

link appears on site below

https://vimeo.com/ondemand/whendogsfly/122763923

**Comment by gorhill** [comment]
There is this exception rule in EasyPrivacy:

    @@||google-analytics.com/plugins/ga/inpage_linkid.js$domain=lovehoney.co.uk|maxiclimber.com|opendns.com|openshift.com|vimeo.com|westernunion.at|westernunion.be|westernunion.ca|westernunion.ch|westernunion.cl|westernunion.co.jp|westernunion.co.nz|westernunion.co.uk|westernunion.co.za|westernunion.com|westernunion.com.au|westernunion.com.co|westernunion.com.hk|westernunion.com.my|westernunion.com.pe|westernunion.de|westernunion.fr|westernunion.ie|westernunion.it|westernunion.nl|westernunion.ph|westernunion.pl|westernunion.se|westernunion.sg

I would like to understand why it was added, so that I can test the case with the neutered script.

**Comment by gorhill** [comment]
Added to _"uBlock filters -- Experimental"_, will see how this work.
