### ISSUE TITLE
Overlay scrollbars in Opera Developer 36 - chrome://flags/?search=scroll#overlay-scrollbars

### ISSUE THREAD

**Issue by inDigazzZ** [gorhill/uBlock#1249]
When Overlay scrollbars is set as 'Default' it's turned off and we have usual scrollbar.
![1](https://cloud.githubusercontent.com/assets/7425050/12385596/afe6d4f6-bddf-11e5-99c4-db859553755b.png)

When Overlay scrollbars is set as 'On' we have scrollbars than hide indicator of uBlock while scrolling a list.
![2](https://cloud.githubusercontent.com/assets/7425050/12385629/e8417112-bddf-11e5-8fc7-fdb4a45c839f.png)

Could you add some margin before indicators so scrollbar couldn't overlap them.

**Comment by seanrand** [comment]
I raised this issue back in April (https://github.com/chrisaljoudi/uBlock/issues/1302), it probably got lost in the repo ownership move. I still think my argument stands.

**Comment by SW1FT** [comment]
I like your idea @seanrand and it makes reading a bit easier too.

**Comment by gorhill** [comment]
> Could you add some margin before indicators so scrollbar couldn't overlap them

That would not be nice for those not using an overlay scrollbar. That information is redundant to the pluses/minuses, it's not terribly important. And I disagree on placing this in the middle, I consider this increases too much the density of information -- especially given that I tried to remove these bars in the past, they are just redundant to what is already in there.

**Comment by seanrand** [comment]
Ok, fair enough. Thanks for explaining the dismissal though, gorhill. For what it's worth, I also closed the issue over at chrisaljoudi.
