### ISSUE TITLE
[non-issue] SeaMonkey-related note

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#125]
The <a href="https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/">AMO info</a> shows uBlock0 as not-compatible with SeaMonkey.

While the GUI does not work properly, and there's the 3rd-party filters issue (<a href="https://github.com/gorhill/uBlock/issues/49">#49</a>), the addon itself works fantastic, as do the dynamic filters.

So, maybe you'd be willing to add a comment for SeaMonkey users' benefit somewhere visible, like the readme or something?

Same goes for Palemoon:
It does have GUI issues, but the addon works great, so same request?

**Comment by WyohKnott** [comment]
https://github.com/AlexVallat is working on the Palemoon/SeaMonkey issue over here https://github.com/chrisaljoudi/uBlock/issues/1315 Maybe his changes could be backported for Origin if both parties agree.

**Comment by gorhill** [comment]
Duplicate of #49.
