### ISSUE TITLE
Chip.de Video not working again with Firefox 44b9 and ublock 1.5.5/latest dev

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#1250]
issue with Firefox 44b9 + uBo 1.5.5, 1.6.0b1 (Video stops after +- 30secs.)

look @ Chip.de

http://www.chip.de/news/Schluss-mit-Windows-7-Microsoft-verbietet-altes-Windows-auf-neuen-CPUs_88373822.html

http://www.chip.de/news/WhatsApp-wieder-komplett-gratis-Gruender-verkuendet-grosse-Neuerung_88282979.html

no Video Ad, but Videos stops after +- 30secs @chip.de

greetings

**Comment by gorhill** [comment]
I have a fix for this, but this required a slight, trivial change to uBO -- to deal with local `iframe` elements (those without a `src` attribute), so I won't post the new filter until I publish the fix. It seems they are paying attention to uBO, as the previous fix was very specific to uBO (unless similar fix was present elsewhere, maybe in some Greasemonkey script?)

**Comment by akks1981** [comment]
Ok Big thx for ur help and work bro

greetings

**Comment by akks1981** [comment]
Hi now, not one Video play anymore! The Videos only load...  (no ad, no play, no sound)
(sry for my bad english)

greetings

**Comment by gorhill** [comment]
My fix still work on my side, but now it requires to unblock `http://widgets.outbrain.com/outbrain.js`, which is blocked by Peter Lowe's. Will see if it's worth creating a neutered script for this one.

**Comment by akks1981** [comment]
I am hopeful that its worth...THX bro

greetings

**Comment by gorhill** [comment]
If you don't mind using the latest dev build, it's fixed -- I verified it works from here.

**Comment by akks1981** [comment]
Hi, it dont work for me with the latest dev! All Videos @ chip.de only load. Clean install from firefox 44RC2 and uBO1.6.0b5 help nothing. Dont know why. But i Thank u so much for ur help and work bro.

greetings

**Comment by akks1981** [comment]
sry, Update when i deaktivate "Peter Lowe’s Ad server list‎" than it works with latest dev and Firafox! it is recommended to deaktivate this list?

**Comment by gorhill** [comment]
Give me a URL where you say it does not work. The one you provided in your 1st comment works.

**Comment by akks1981** [comment]
hey, i dont know why, but now it works with the aktive list and all chip.de videos! 

BIG THX bro

greetings
