### ISSUE TITLE
How to debug default rules?

### ISSUE THREAD

**Issue by dimaqq** [gorhill/uBlock#1251]
I'm writing a LAN gizmo that has a web interface.

Thus, typically, some user would open `http://191.168.0.123:1234/` to configure this gizmo.

That page has some javascript that makes a few POST requests to same ip:port.

At least 2 of these get blocked by uBlock origin: `get_ad_timestatus` and `do_save_authconfig`.

Now I could imagine that the extension doesn't like `*_ad_*`, but that's just a guess. Alternatively it could be something the posted data.

How can I track which specific rule is triggered for these requests?

**Comment by harshanvn** [comment]
Use the <a href="https://github.com/gorhill/uBlock/wiki/The-logger">logger</a> (make sure to read it completely, it is quite powerful to debug what is and what not happening!), to find the filter causing the issue. Click on the 3rd column, to see the filter origination details..

**Comment by gorhill** [comment]
Use the [logger](https://github.com/gorhill/uBlock/wiki/The-logger). Marking and closing as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
