### ISSUE TITLE
[Chromium Version 50.0.2624.0 (64-bit)] uBlock Origin crashes on load

### ISSUE THREAD

**Issue by the-bobo** [gorhill/uBlock#1253]
uBlock Origin 1.5.6 crashes as soon as it starts on Chromium. Any advice on how to debug/move forward? OS X 10.11.2.

All I did was install uBlock Origin from the Chrome Webstore, and whenever it tries to start I get a notification saying "uBlock Origin has crashed. Click this balloon to reload the extension."

Clicking just crashes again and shows another balloon.

**Comment by gorhill** [comment]
What do you call "crash"?

**Comment by the-bobo** [comment]
thanks, didn't realize i had grabbed a canary build

**Comment by lewisje** [comment]
The pre-built "Chromium" binaries you could download from Google (as opposed to "Google Chrome") are at the same level of stability as Canary; the difference is that there is no built-in Flash Player, MP4 codecs, or other non-free-software components.

There are, however, other Chromium-based browsers, many of which are based on older milestones than Chrome Stable, that you might wish to try out, if your reason for picking Chromium was that Chrome invades your privacy too much.
