### ISSUE TITLE
Restore Strict Blocking button in the popup UI

### ISSUE THREAD

**Issue by aimtsou** [gorhill/uBlock#1255]
With the use of block large elements button, now there is no button for enabling/disabling per site strict blocking. Will it be back?

**Comment by gorhill** [comment]
uBo's block page is best place to choose whether or not to disable strict blocking (temporarily or permanently), there was not much point to have that switch in the popup panel. No it will not be back. Go to _My rules_ if you want to remove a previously permanently disabled strict blocking.
