### ISSUE TITLE
Block images by size

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1256]
Is it possible to block an image based on it's size? Let's say you wanted to block all 1x1 images. Could this somehow be done? Is there a reason not to use such a filter?

**Comment by gorhill** [comment]
Because that's pointless? 1x1 is just one size used for tracking purpose. Transparent 1x2, 2x1, 7x11, 13x4, etc. images are all as valid for tracking purpose.

**Comment by IDKwhattoputhere** [comment]
It's the most common one though. Whatever.

**Comment by gorhill** [comment]
Of course it's not the same as finding a pattern in a URL before a request is made.

[See](https://github.com/gorhill/uBlock/releases):

> **Block media elements by size** [...] this feature has no privacy value: a connection to the remote server must be performed in order to fetch the size of the resource

**Comment by IDKwhattoputhere** [comment]
> a connection to the remote server must be performed

That's part of the equation I didn't know. Scratch this issue then. Thanks for getting back to it.
