### ISSUE TITLE
[Feature Request] An option to only Import Filters

### ISSUE THREAD

**Issue by theTomaku** [gorhill/uBlock#1259]
Reason for this feature request is that when you're going to test the latest Dev version of uBO and it will contain new features which are not in the Stable version yet and you'll Import Filters and Settings from the Stable version over the Dev version it'll cause weird behaviour and might cause that some of the Filters  might not get Imported properly.

Just to wrap things up, I would love to get a feature to Import only Filters, not the every setting possible between Stable and Dev versions.

**Comment by gorhill** [comment]
> Import Filters and Settings from the Stable version over the Dev version it'll cause weird behaviour

Be specific please: what "weird behaviour"?

> I would love to get a feature to Import only Filters

Just export/import from the _My filters_ pane.

**Comment by theTomaku** [comment]
Sorry if I didn't state my words correctly, this might be a bug in Chrome Canary itself where sometimes if you Import Filters and Settings from the Stable version over the Dev version it might in some cases add a so called "shadow filter" where the filter itself is not actually in the uBO and needs to be removed and manually re-added. That's why I named this Issue like this, I'm not sure if I even understand this whole Import feature correctly. Is it suppose to Import Filters and Settings? If I understand this correctly it'll Import both and in some rare cases there might be a "shadow filter". But that doesn't happen so often and might also be a browser bug.

**Comment by gorhill** [comment]
> I'm thinking about a pop-up window after you select your Exported Settings file which would ask you that do you want to Import Filters only and/or Filters+Settings.

Declined.
