### ISSUE TITLE
How to block base64 images?

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1260]
How do I block ```data:image/jpeg;base64```?. ```www.gaytube.com##img[src^="data:"]``` didn't help, something I learned from http://support.getadblock.com/discussions/problems/73821-cant-block-a-dataimagepngbase64-encoded-and-added-images

Example 1:
This issue appear on the bottom of the main page of gaytube.com. If I block the image with uBlock Origin, it will reappear!

Example 2:
This issue appear on the main page of gaytube.com in the middle of the screen next to "Full Videos".

Example 3:
This affect all video pages. See http://www.gaytube.com/media/1033912/barebacking_ama/ for example.

First block the ad banner to the right with ```www.gaytube.com##.text-center.rkl-block```.

After that one of the single images will be seen, as a background image. View Background Images redirect me to data:image/jpeg;base64,/9j/4QAYRXhpZgAA......so on

**Comment by gorhill** [comment]
I tried `google.ca##[src^="data:"]` on <https://www.google.ca/search?q=cat&tbm=isch> and it worked fine. If you ant to block a background image which URL is `data:`, you will have to block the element itself using a CSS rule.

**Comment by flyingzebras** [comment]
@gorhill I just found out that these base64 background images are injected with JS.

**Comment by gorhill** [comment]
Do these background image stop if you block inline script?

**Comment by flyingzebras** [comment]
@gorhill Yes.

**Comment by gorhill** [comment]
Give me a URL to a `view-source:` page with the issue, I will see what can be done from the source code.

**Comment by gorhill** [comment]
If using Firefox, you can try: `gaytube.com##script:contains(data:image)`.

**Comment by flyingzebras** [comment]
@gorhill You do not need to see any porno if you investigate view-source:http://www.gaytube.com/

**Comment by flyingzebras** [comment]
@gorhill ```gaytube.com##script:contains(data:image)``` did not block them.

**Comment by flyingzebras** [comment]
@gorhill Here is the gist: https://gist.github.com/flyingzebras/47397b54c045684bbdc7

**Comment by flyingzebras** [comment]
@gorhill ```gaytube.com##script:contains(data:image/)``` did not block them either.

**Comment by gorhill** [comment]
Does `gaytube.com##script:contains(PHENV.onDetection)` work?

**Comment by flyingzebras** [comment]
@gorhill Yes!

**Comment by flyingzebras** [comment]
assets/ublock/filters.txt now block the base64 images on gaytube.com with

`filmvf.net,filmstreaming-hd.com,gaara-fr.com,gaytube.com,gum-gum-streaming.com,hentaifr.net,hentaihaven.org,narutoshippudenvf.com,tuxboard.com,xstory-fr.com##script:inject(phenv-defuser.js)`

Thanks!
