### ISSUE TITLE
[Feature Request] automaticaly go to final destination

### ISSUE THREAD

**Issue by lfourrier** [gorhill/uBlock#1261]
when clicking on :http://logi4.xiti.com/go.click?xts=290428&s2=13&clic=T&type=click&p=www::paris::paris_20160120&url=http://ojd.octelio.com/track?link=154&n=20160120&url=http://pdf.20mn.fr/2016/quotidien/20160120_PAR.pdf?1, 
we have:
uBlock Origin has prevented the following page from loading:
http://logi4.xiti.com/go.click?xts=290428&s2=13&clic=T&type=click&p=www::paris::paris_20160120&url=http://ojd.octelio.com/track?link=154&n=20160120&url=http://pdf.20mn.fr/2016/quotidien/20160120_PAR.pdf?1
Because of the following filter ...

This is great. But what wwould be greater would be the option to silently go to http://pdf.20mn.fr/2016/quotidien/20160120_PAR.pdf?1, that is the last part of the url that begin with http or https. Note : this sould be filtered, perhaps by destination.

**Comment by vzjrz** [comment]
Dup of https://github.com/gorhill/uBlock/issues/1025, https://github.com/gorhill/uBlock/issues/973?

**Comment by lfourrier** [comment]
yep.
so it won't be done :(
too bad. I just close it then.
