### ISSUE TITLE
Whitelisting in a filter

### ISSUE THREAD

**Issue by szepeviktor** [gorhill/uBlock#1262]
Is it possible to whitelist a domain in a filter?
I've tried `@@||szepe.net^$document` but third-party resources are still blocked.
Thank you.

**Comment by szepeviktor** [comment]
:cry: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#not-supported

**Comment by gorhill** [comment]
Why not just add `szepe.net` to the _Whitelist_ pane?

**Comment by szepeviktor** [comment]
I use Firefox in a simple way: extract setup, run, delete. Even the profile is deleted.
https://github.com/szepeviktor/windows-workstation/blob/master/ff-dev/START-ffdev.cmd#L33-L36

So I need to set up everything from a Windows batch file and `user.js`.

`user_pref("extensions.ublock0.adminSettings", '{"userSettings":{"advancedUserEnabled":true,"netWhitelist":"about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nopera-scheme\npaypal.com\nstartssl.com\nszepe.net"}}');`

**Comment by gorhill** [comment]
The content of `adminSettings` as to match the content of a proper backup file. I don't think your `adminSettings` value would work for the whitelisting. Try:

    user_pref("extensions.ublock0.adminSettings", '{"userSettings":{"advancedUserEnabled":true},"netWhitelist":"about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nopera-scheme\npaypal.com\nstartssl.com\nszepe.net"}}');

**Comment by szepeviktor** [comment]
For Googlers:
```js
'{"userSettings":{"advancedUserEnabled":true},"netWhitelist":"paypal.com\\nstartssl.com\\nszepe.net"}');
```
