### ISSUE TITLE
Can you make it so this weather page again displays weather with no adds

### ISSUE THREAD

**Issue by c627627** [gorhill/uBlock#1263]
It only works if all adblocking is disabled now, before you could see the weather and not adds:
http://www.intellicast.com/Local/Weather.aspx?location=USNY0996

**Comment by harshanvn** [comment]
Hello, This is not the right place for providing filters. Please see the <a href="https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md">contributing.md</a>.
You can ask about the filters here - https://forums.lanik.us/

Also, it is always better to provide a screenshot depicting the problem. So, if any one of us wanted to take a look at it, it will be quite easier. I tried, and i don't see any ads. Though i have some additional filter lists checked..

**Comment by c627627** [comment]
Thank you for those links, I will use them in the future.
The issue appears to have "fixed itself". Thank you.

**Comment by c627627** [comment]
The solution was to:
Show Dashboard > 3-rd party filters > Update now.

**Comment by anewuser** [comment]
@c627627 You didn't need to reopen the issue to leave your final comment. Please close it again.
