### ISSUE TITLE
Doesn't work with CoolPreviews

### ISSUE THREAD

**Issue by rikkdekkard** [gorhill/uBlock#1264]
I'm currently using chrisaljoudi's uBlock, but since it's longer being maintained, I've been looking to switch to uBlock Origin. I am however very attached to this Firefox addon, CoolPreviews, which displays a preview of a website in a small pop-up window when hovering over an icon next to a link.  Problem is, whereas uBlock works in those pop-up windows with default settings since version 0.9.4.5, the only way to make uBlock Origin block the ads in them is to turn on the advanced user mode and delete behind-the-scenes from the whitelist, which I understand is not the best of ideas. My question is: is there any other way to have that functionality in uBlock Origin?

**Comment by anewuser** [comment]
>**CoolPreviews no longer supported**

>In an effort to sharpen our focus on delivering delightful communication experiences to our users, we have discontinued support for the CoolPreviews browser add-on. 

https://www.coolpreviews.com/

**Comment by gorhill** [comment]
> uBlock works in those pop-up windows with default settings since version 0.9.4.5

That does not make much sense to me. See what the logger of uBlock says versus what the logger of uBO says. Report your finding please.

**Comment by rikkdekkard** [comment]
Due to the nature of the pop-up, I don't think it's possible to perform a log inside of it. When opened in a tab, both uB and uBO block all of the ads flawlessly, the issue occurs in the pop-up.

For comparison, here's how it looks with uB (and also ABP, for that matter):
![ub](https://cloud.githubusercontent.com/assets/16802939/12477197/7bcd7b92-c02e-11e5-83e7-99e5975ebb50.png)


and this the same area with uBO:
![ubo](https://cloud.githubusercontent.com/assets/16802939/12477285/f023855e-c02e-11e5-959f-4b9edd694df3.png)

The same thing happens when using the Page Portal addon and the Hover Preview userscript, which are similar to CoolPreviews. It's probably irrelevant in this case, but I might add the problem doesn't occur in Chrome when using EZLinkPreview, which is another nearly identical addon.

I know that it's not likely that a lot of people are concerned by this issue, so thanks for even taking the time to respond.

**Comment by gorhill** [comment]
uBO's logger will report all network requests, please use the logger and see what it says.

**Comment by harshanvn** [comment]
And make sure you put the drop down selected to "all".

**Comment by rikkdekkard** [comment]
Thanks for being patient with me.

The only thing uB logs is this:
![ub](https://cloud.githubusercontent.com/assets/16802939/12483810/5d609e7c-c057-11e5-8170-372b07396315.png)
This is the "behind-the-scene" context, and yes, this the only way to make uB log anything at all when using CoolPreviews.

And this is the uBO log (it's quite long, so I'm posting it as txt. file):
[uBO.txt](https://github.com/gorhill/uBlock/files/99305/uBO.txt)
There are no red markers anywhere to be seen in the log.

**Comment by gorhill** [comment]
> For comparison, here's how it looks with uB

Ok, I installed Portal and tried with uBlock, and it does show ads in the Portal frame, so you **did** remove `behind-the-scene` from _Whitelist_ in uBlock -- that is also the only way to have ads removed in uBlock.
