### ISSUE TITLE
scorecardresearch neutured

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1265]
hi. is it possible to make a neutured script for the scorecard research filters? for example the filter below:

@@||scorecardresearch.com/beacon.js$domain=agame.com|allrecipes.com|amctv.com|apl.tv|babycenter.com|bonappetit.com|calgaryherald.com|canada.com|cbc.ca|dailymail.co.uk|deviantart.com|discovery.com|edmontonjournal.com|fastcompany.com|financialpost.com|firstwefeast.com|hitfix.com|huffingtonpost.com|landandfarm.com|last.fm|leaderpost.com|m.tmz.com|montrealgazette.com|nationalpost.com|newsday.com|ottawacitizen.com|outsideonline.com|radaronline.com|salon.com|sci2.tv|syfy.com|theprovince.com|thestar.com|thestarphoenix.com|thinkatheist.com|vancouversun.com|windsorstar.com

**Comment by gorhill** [comment]
What is needed is why it was whitelisted for some of the sites in there, so that I can test the neutered script to see if there is still an issue if we use a neutered script.

**Comment by jo2dan23** [comment]
if i understand correctly what your saying. you want an example of a site that is dependent on the script. if so add this filter to your list first as it fixes the page: @@||bonappetit.com/ads/js/cn.dart.bun.min.js

then block the  @@||scorecardresearch.com/beacon.js$domain= exception filter and if you click the arrows on the slideshow it will allow you to view two images only. clicking the arrow does nothing after that. when the beacon.js filter is whitelisted it will allow you to view the full slideshow. page here:

http://www.bonappetit.com/recipes/holidays-recipes/slideshow/thanksgiving-appetizers/?slide=1#15

**Comment by gorhill** [comment]
Thanks for the test case. I could slide through more than two images -- so I added the neutered script, and the related filter in the _uBlock filters -- Exprimental_ filter list.

**Comment by gorhill** [comment]
Found that the neutered script also unbreaks Best Buy's site:
<http://www.bestbuy.ca/Search/SearchResults.aspx?type=product&page=1&sortBy=relevance&sortDir=desc&query=cables>

Without it, the links (`javascript://` when hovering) on the left-hand side do not work.
