### ISSUE TITLE
utag

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1268]
is it possible to do  a neutered script of utag. i seen these on atleast 50 or more sites so far, i have a test case to reproduce if it is possible. but i am guessing it isn't since each website it is hosted on has a different script?

here are two different site scripts

http://tags.tiqcdn.com/utag/cbsi/cnetglobalsite/prod/utag.js
https://tags.tiqcdn.com/utag/victoriassecret/main/prod/utag.js

it would be great if we could block those without breakage as they load tons of scripts after the utag.js is loaded

**Comment by gorhill** [comment]
I will decline: these scripts appear rather large, and yes, they have site-sepcific stuff embedded in them.
