### ISSUE TITLE
Ublock origin 1.5.1 cannot get out of create filter from log screen. 

### ISSUE THREAD

**Issue by bulrush15** [gorhill/uBlock#1270]
Firefox 40.0.3, uBlock Origin 1.5.1 on Win 7. 

When I go to this screen, http://imgur.com/rXHx8Xw, there is no way for me to get out of it. Hitting Escape does nothing, nor does hitting any other key, and there no close [x]. I have to close the browser tab to get out of it. 
![sqlite20160121](https://cloud.githubusercontent.com/assets/7031486/12485269/04ce1a1c-c02c-11e5-960c-6c1468878d41.jpg)

**Comment by gorhill** [comment]
Click anywhere outside the dialog.
