### ISSUE TITLE
EasyPrivacy blocks jotform.com forms

### ISSUE THREAD

**Issue by ivan** [gorhill/uBlock#1273]
(I know gorhill doesn't want issues about third-party filter lists, so I'm going to close this immediately.  Posted here because I tried reporting this on https://forums.lanik.us/ several times, but the post didn't go through because I was flagged as a spammer.  If uBlock Origin doesn't want to whitelist this, could someone please copy this report to https://forums.lanik.us/viewforum.php?f=64?  Thanks.)

EasyPrivacy includes

```
||jotform.com^$third-party
```

which blocks the 'Sign Up For Beta' form on https://www.brave.com

Other jotform users are reporting problems on http://www.jotform.com/answers/745923-Embedded-form-being-blocked-by-uBlock-plugin-extension

**Comment by gorhill** [comment]
If you use custom filter `@@||form.jotform.com$script`, does it fix the issue?

If so, I will propose the exception filter to EasyList.

**Comment by ivan** [comment]
Yes, that fixes the issue.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/028b5a11cbe9
