### ISSUE TITLE
Cannot block ads on large media site

### ISSUE THREAD

**Issue by cheilbut** [gorhill/uBlock#1274]
I can't seem to block the large ads on CP24.com, one of the largest news websites in Canada.

Here is an image showing the problem: http://i.imgur.com/g99fn0F.png

![unspecified](https://cloud.githubusercontent.com/assets/16830188/12501904/c9b39078-c090-11e5-8c47-d93bb8649359.png)

The advertising images are not selectable user the element picker tool.

**Comment by gorhill** [comment]
Also, duplicate of #1202.
