### ISSUE TITLE
Polish filters - change url

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#1275]
I must change url to filters. 

Old url https://www.certyficate.it/adblock/adblock.txt
new url https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

I make redirect from old to new url. 

Thanks

**Comment by TPS** [comment]
@gorhill Commited in https://github.com/gorhill/uBlock/commit/7a49a7f56ff098aeb265be5df2d02a37b0080e41, but not auto-closed....

**Comment by gorhill** [comment]
Because there is another step to the fix, in `filter-lists.json`.
