### ISSUE TITLE
IPv6 raw addresses are not correctly handled

### ISSUE THREAD

**Issue by alexander255** [gorhill/uBlock#1276]
Currently uBlock does not properly handle websites that are hosted on raw IPv6 addresses:
![Screenshot](https://cloud.githubusercontent.com/assets/246386/12511096/ee2c471e-c10e-11e5-8b0d-a5ba96008977.png)

uBlock thinks that the website is hosted on `[1234:5678:9abc::cdef]`, while any resources used by that site (even if they are provided by the same server) will considered to be hosted on `1234:5678:9abc::cdef` (= a different server). The net result of this is that any site hosted on a raw IPv6 address will be completely broken if any third-party resources have been disabled globally.

Since I do not have access to the "normal" IPv6 internet at the moment, I cannot  provide any (globally) working IPv6 URLs for testing right now. (sorry!)
Some of these might work (make sure they don't redirect you to a domain name):
http://[2001:1900:3001:11::2c]/
http://[2a00:1450:4001:809::1007]/

**Comment by gorhill** [comment]
Is the issue present also in Chromium? uBO assumes the browser's API presents it a properly formed IPv6 address.

**Comment by alexander255** [comment]
No, Chromium is not affected:
![Screenshot](https://cloud.githubusercontent.com/assets/246386/12512662/eb695976-c119-11e5-918a-b61481a2ac1b.png)

**Comment by gorhill** [comment]
Found this, <https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIURI>:

> **Note:** IPv6 addresses are not enclosed in square brackets.

So I will have to give up on trying to use the already computed `hostname` by Firefox's API. There was already another issue (#966) which required special handling.

**Comment by alexander255** [comment]
Thank you!

I've tested the latest git snapshot and it works now: :grinning: 
![Screenshot](https://cloud.githubusercontent.com/assets/246386/12521968/3bb8bcd0-c14e-11e5-960f-d77db108229b.png)

**Comment by gorhill** [comment]
Side note: looking at your screenshot, just want to be sure... You realize that using `allow` rules will override any block filter in the static filter lists that may otherwise apply?
