### ISSUE TITLE
[Request] Feature to isolate detected items instead of blocking them

### ISSUE THREAD

**Issue by rafajafar** [gorhill/uBlock#1277]
I'm going to probably develop a solution for this on my own, but I would like a more general-purpose version of this: https://github.com/garysieling/adsense-scraper

I've worked with a lot of monitoring companies. These companies wish to capture the advertisements within a web page, use it as evidence, and then follow the click events found in the advertisements and repeat the process on the landing page. They kinda have solutions, but they are frequently poorly-designed in-house solutions which break a lot. After encountering this again, I realized it would just make a lot of sense if there was an adblocker which did the opposite of block ads. Instead, it would isolate them.

There's three features such a tool would require to be useful: 

1. Needs either be standalone from a command line or integrate into standalone tools
    * I recommend PhantomJS, personally
    * Any command line interface would be fine, though... even an API into the browser and let the browser run headless.
2. It would need to do the following in detection:
    * Take a URL as input
    * Discover the nearest container for each advertisement
    * Discover all click events associated within the container.
    * Find any URLs or Form Submissions associated with the click events.
3. It would need to isolate the advertisement creative.
    * Initially, just highlighting anything that's an advertisement in a big bold box would be sufficient.
    * It would be very nice to also have the rest of the page "whited out" so that only advertisements display.

Output would be: 

1. The list of urls being used to render the advertisement
    * CSS associated with the advertisement
    * JS associated with the advertisement
    * Images or Flash creative on the advertisement
2. Landing pages the advertisement directs the user toward.
3. An HTML page which would be used to bare-minimum display the advertisement and only the advertisment (not guaranteed to work or be consistent).

This would allow a system to feed in URLs and return what is needed to monitor an advert.

There might be some issues with HTML5 ads and click events, though.

I am not 100% certain that uBlock Origin is the right place for the *entirety* of this. However, I do feel that if there was some way to, **at bare minimum**, isolate the advertisement location on a web page and return it to PhantomJS, this would be HUGE for a lot of companies who monitor things like ad placement and compliance. 

I would have reached out directly about this, but you request that we do not do that, so I'm really hoping that rather than close this, there can be an open discussion about this idea/topic. 

Thanks!

**Comment by gorhill** [comment]
I don't want to be reached out elsewhere than here because this makes it clear that anything related to this project is to be discussed in the open, and that for anything else not related to this project, it should be assumed I have no interest whatsoever.

**Comment by rafajafar** [comment]
Damn, no need to be a prick, sparky. Get off your high horse there, son.

**Comment by gorhill** [comment]
It's not fun to have to deal to attempt at using someone's hobby time for the benefit of "lot of companies".

**Comment by rafajafar** [comment]
I mean I get that, but it needs to be done, so I'm just going to fork this project and use it as derivative work for what I'm doing. Was hoping you'd had some advice... especially since this would be used to monitor crappy ads in the general case for people who do not know about ad blockers (like someone's grampa). I didn't come here trying to tick you off or even ask for your hobby time necessarily. 

If I had known it would piss you off, I wouldn't have wrote it out, man.
