### ISSUE TITLE
[Firefox for Android] "Show Dashboard" and "Show Network Request Log" buttons are empty

### ISSUE THREAD

**Issue by KlipperKyle** [gorhill/uBlock#128]
I just installed uBlock Origin on Firefox on Android (switched over from chrisljoudi's µBlock).

On a fresh install, I went to Menu > Tools > Addons > uBlock Origin.  There were two buttons labeled "Show Dashboard" and "Show Network Request Log" (just like on the desktop version of Firefox).

I then went into "Show Dashboard" and enabled advanced user mode.  The labels on the buttons in the previous screen disappeared after a reload.  So, I think this might be related to advanced user mode hiding tooltips.

![screenshot_2015-04-25-09-35-52](https://cloud.githubusercontent.com/assets/6385218/7333731/b217b9b8-eb2e-11e4-9e0e-d89cb6882171.png)

By resetting uBlock Origin's settings, sometimes I can make the text on the buttons reappear.

![screenshot_2015-04-25-09-45-00](https://cloud.githubusercontent.com/assets/6385218/7333755/e704cbd8-eb2f-11e4-8169-e350108a949e.png)

I am using version 0.9.5.0.

**Comment by WyohKnott** [comment]
See https://github.com/chrisaljoudi/uBlock/issues/1292#issuecomment-94880199

**Comment by gorhill** [comment]
@WyohKnott Thanks for this, this saved me a lot of time, as I do not have access to a mobile device, I was trying to code review to find any code change which could explain this.

**Comment by gorhill** [comment]
It's a while I haven't heard of this issue. Will re-open if reported again.
