### ISSUE TITLE
dynamic URL filtering + subdomain matching

### ISSUE THREAD

**Issue by wavexx** [gorhill/uBlock#1281]
Currently, the destination URL in a rule must match exactly the beginning of the URL being requested. Many sites however now request data from a set of subdomains which have the same URL structure.

It would be nice to have ``*`` matching a single subdomain part, and ``**`` match any domain part.
For example:

    youtube.com https://*.googlevideo.com * noop

would match a single subdomain of the form xyz.googlevideo.com while not matching a.b.googlevideo.com. The latter could be matched with:

    youtube.com https://**.googlevideo.com * noop

This would also help a for the same domain with multiple TLDs:

   something https://**.google.*/...

But TLDs are generally limited to a few so they're not a show-stopper, while CDNs tend to have wildcard records that do the dirty work.

I'm currenly not aware if cosmetic filters have already some wildcard syntax which would make sense to re-use.

**Comment by gorhill** [comment]
Declined. The main purpose of dynamic filtering rules is to easily toggle on/off specific network requests from the logger. At this point I do not want to overcomplicate further the code.

**Comment by gorhill** [comment]
Note that your 1st example can be implemented using plain dynamic filtering:

    youtube.com googlevideo.com * noop
