### ISSUE TITLE
Hiding filter's source missing

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1282]
I have absolutely no idea which terms I would search to find this issue on here so I'm sorry if it has been reported before.
uBO doesn't correctly display the source for some element hiding filters.
![](https://cloud.githubusercontent.com/assets/16030872/12525669/4e7efcf4-c166-11e5-8426-ab62c36bfaee.png)
How to reproduce:
1. Install uBO and enable the "Anti-Adblock Killer | Reek‎" filter list
2. Open the logger and go to yifytorrents.net

The filter in AAK list is `/wp-content/uploads/an-temp/$script,stylesheet` while uBO displays `/wp-content\/uploads\/an-temp/$stylesheet` and `/wp-content\/uploads\/an-temp/$script`.

**Comment by gorhill** [comment]
uBO is showing the properly escaped regular expression.

**Comment by gorhill** [comment]
I had not noticed the screenshot (filtering image by size here). The issue seen in screenshot was solved in 1.6.0.
