### ISSUE TITLE
How to block "blockadblock" script on any webpage?

### ISSUE THREAD

**Issue by tdkr147** [gorhill/uBlock#1283]
"blockadblock" getting smarter.
(BlockAdblock is the easiest, free defense against adblocking) :)

I have tried all the workaround below, but still doesn't work with uBlock Origin.
not sure with other adblockers.

https://forums.lanik.us/viewtopic.php?f=64&t=27908&p=84750&hilit=blockadblock#p84750
https://forums.lanik.us/viewtopic.php?f=64&t=27745&p=84258&hilit=blockadblock#p84258
https://forums.lanik.us/viewtopic.php?f=64&t=27584&p=83701&hilit=blockadblock#p83701

**Comment by harshanvn** [comment]
Can you give the url where blockadblock is being used...

I tried going to  http://www.ip-address.org, and the site is fine.

Can you provide the screenshot of the ad?

**Comment by gorhill** [comment]
> I have tried all the workaround below, but still doesn't work with uBlock Origin.

The only concrete case in the link you posted is <http://www.ip-address.org/> -- and the site displayed just fine with nothing to do.

Read and respect [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) please.
