### ISSUE TITLE
Warning: rouge chromium extension since 2016-01-23 by ditepi.com

### ISSUE THREAD

**Issue by COLABORATI** [gorhill/uBlock#1286]
Accidentaly I found a "new" chromium extension in the chrome store that is showing up by searching for "ublock origin". This seems to be an unauthorized copy of the original code, however the author still points back to this repository, but also points to a ditepi.com domain which has this whois info today:
```
Registrant Name: Sasa Chesk
Registrant Organization: 
Registrant Street: Los angeles
Registrant City: Los angeles
Registrant State/Province: stasun
Registrant Postal Code: 212355
Registrant Country: ZA
Registrant Phone: +27.5555555555
Registrant Phone Ext: 
Registrant Fax: 
Registrant Fax Ext: 
Registrant Email: monhako@gmail.com

```
I did not check if the code contains some malware or any spam, but it seems obvious that the authors intentions are not positive. Maybe it would make sense to put a warning on the repo readme and of course contact the google chrome store team.

**Comment by gorhill** [comment]
Best is for people to report such occurrences when they are misleading. In the current case using the exact same name and icon of another extension. I reported it, others can do so too.

**Comment by IDKwhattoputhere** [comment]
All other extensions of that developer (ditepi.com) are also rip-offs.

**Comment by lewisje** [comment]
Well that certainly is a *rouge* extension. :red_circle:

**Comment by gorhill** [comment]
Now I get it, he meant "rogue"... I didn't understand until now why he referring to it as "rouge".
