### ISSUE TITLE
How to block Subframe connections? Possible with uBO?

### ISSUE THREAD

**Issue by theTomaku** [gorhill/uBlock#1287]
If you run Chrome with a --enable-site-per-process flag it will run a Subframe connections, I really don't know how to explain this. 

![untitled](https://cloud.githubusercontent.com/assets/16628554/12537727/0384a45a-c2cf-11e5-98a1-e4ebde3706aa.png)

I have Subframe connection to Facebook.com, I think the website I was at had a Facebook share buttons or something. Is there any way to block these Subframe connections to Facebook?

**Comment by gorhill** [comment]
Please, provide a URL where you got the above.

**Comment by theTomaku** [comment]
This is Finnish website:

http://keskustelu.suomi24.fi/terveys/henkinen-hyvinvointi-ja-mielenterveys/yksinaisyys

**Comment by gorhill** [comment]
Static filtering-based solution: Enable _"Anti-ThirdpartySocial"_ filter list.

Dynamic filtering-based solution: <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-to-easily-reduce-privacy-exposure>.

**Comment by theTomaku** [comment]
I have that filter enabled.

**Comment by gorhill** [comment]
I just tried it: there was no `facebook.com` in the Task Manager. Use the logger to find out why `facebook.com` was not blocked.

**Comment by theTomaku** [comment]
Blocking facebook.com/net connections through uBO toolbar icon worked correctly.

**Comment by theTomaku** [comment]
I also tried the logger and I highlighted the website I was at and logger was empty.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/12537941/7bcce024-c29a-11e5-9bd1-9e8c8ef04f6c.png)

**Comment by gorhill** [comment]
> and logger was empty

You are not reading [the doc](https://github.com/gorhill/uBlock/wiki/The-logger). Please take time to read the doc -- this will help prevent opening non-issue.

**Comment by theTomaku** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16628554/12537971/98ca1d82-c2d5-11e5-8cc6-5f50d6e70c61.png)

**Comment by gorhill** [comment]
Remove the dynamic filtering block rule and refresh the page -- the best explanation is that there was an exception filter preventing _"Anti-ThirdpartySocial"_ from doing its work.

**Comment by theTomaku** [comment]
Done.

![untitled](https://cloud.githubusercontent.com/assets/16628554/12538015/86f11c22-c2d6-11e5-8345-997cfb2af9b3.png)

**Comment by gorhill** [comment]
Click on the filter to see from which filter list it comes from.

**Comment by theTomaku** [comment]
International List + EasyPrivacy + Fanboy+Easylist-Merged Ultimate List

**Comment by gorhill** [comment]
No, click on the filter (`@@||facebook.com/[...]`) in the logger.

**Comment by theTomaku** [comment]
That's what I did yeah.

**Comment by gorhill** [comment]
Ok. What is "International List"?

**Comment by theTomaku** [comment]
I found the International list here:

https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

**Comment by gorhill** [comment]
It contains:

    @@||connect.facebook.net/*/sdk.js
    @@||facebook.com/connect
    @@||facebook.com/plugins/comments
    @@||facebook.com/v2.*/plugins/video.php
    @@||www.googletagservices.com/tag/js/gpt.js

I will remove that filter list from the wiki page, such broad exception filters should not be in any filter list.

**Comment by theTomaku** [comment]
After removing the International List uBO will block facebook.com connection correctly.

**Comment by IDKwhattoputhere** [comment]
That list contains even more problematic filters:
`||fastly.net` is just a generic CDN.
`||cdn.jquerytools.org/*/jquery.tools.min.js` This is bound to break websites.
`||safebrowsing.google.com^` I'm baffled.
