### ISSUE TITLE
Filter List Dan Pollock's host file isn't updated with given URL anymore

### ISSUE THREAD

**Issue by Goderw** [gorhill/uBlock#1288]
Hello,
I've just reached out that after updating the filter lists, Dan Pollock's filter list isn't updated nor does it contains any amount of entries anymore. uBo shows me after the update, that 0 out of 0 filters are used although it is marked and before the update it was something like 400 out of 2000 (I don't remember the exact value!)!
Maybe, the filter URL changed from uBo's standard http://someonewhocares.org/hosts/hosts to http://someonewhocares.org/hosts (when I was searching it by myself via browser URL entry).

uBo Version 1.5.5
Firefox 43
Debian

**Comment by gorhill** [comment]
The filter list is at <http://someonewhocares.org/hosts/hosts>, not <http://someonewhocares.org/hosts>. I just selected the filter list and it loaded fine -- ~12K filters.

Sometimes remote servers can be down, or return an invalid result, this is out of control of uBO. Also, uBO will throw out duplicates, so depending on which other filter lists you are using, it is possible that the whole content of the filter list was already loaded from other filter lists (you are not disclosing your settings).

**Comment by gorhill** [comment]
Closing until you make the case that there is really an issue with uBO, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). If the filter list is not loaded, you are the best placed to find out why, see that it's not blocked by something else on your computer, or even uBO if you de-whitelisted `behind-the-scene`.

**Comment by Goderw** [comment]
I found the reason why:
If the extension "Refcontrol" is set to "replace the referer with the currently visited site", uBo isn't be able to load the list from Dan Pollock's page anymore. Strange!? 
In the end it isn't a uBo related bug. :)

**Comment by Goderw** [comment]
Addition: 
If Refcontrol is set to "block the referer entirely"... everything works fine. This was my initial setting over years.
