### ISSUE TITLE
Get rid of randomly named elements

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#1289]
I think I've already seen a similar issue here, but infortunately cannot find it.

How to get rid of these kind of advertisments: 

![screenshot01474](https://cloud.githubusercontent.com/assets/11029138/12539069/85ba1070-c2ea-11e5-9e55-236e9e5ddf2d.jpg)

Link: http://sante-medecine.journaldesfemmes.com/faq/6440-nevralgie-d-arnold-symptomes-et-traitements

Each img/block/element has it's randomly generated id like `.sXqQsU8DPNi`, as well as the whole frame. 
Blocking *Ligatus* advertising (already blocked here) is not enough in that example.

Thanks ;-)

**Comment by anewuser** [comment]
Please read [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). This tracker is meant to be used to report bugs, not to ask people to create rules for you.

You can ask the maintainers of the French list to block those ads on the [LIST FR forum](https://forums.lanik.us/viewforum.php?f=91).

**Comment by onestepbeyond** [comment]
Done *(but needs admin's approval before viewable in the list of threads)*.

**Comment by anewuser** [comment]
Please close this issue to mark it as solved.

**Comment by onestepbeyond** [comment]
@anewuser, If this does not bother you, I will wait to have the link to the thread I opened on the ListeFR forum before closing here. So that everyone interested can benefit from the solution.

With all apologies for having opened such thread here.
