### ISSUE TITLE
[Suggestion/Not a Issue] Name change to differentiate from uBlock?

### ISSUE THREAD

**Issue by asantos3** [gorhill/uBlock#129]
There's loads of confusion with uBlock vs uBlock Origin and you mentioned that it's time to move on.

Perhaps a name change would be good to new comers and (I know I mentioned this before but hear me out) perhaps setting up a github org (with only you on it if you want) so you can have newname.github.io and in it a page with simple information that links to a subreddit for support?

**Comment by alain1965** [comment]
I think it has no more confusion with ublock vs ublock origin than it has confusion with adblock plus vs adblock edge. For chrome it has a confusion with all adblocks, yes but in AMO the number is limited.
