### ISSUE TITLE
Gmail contacts fail with uBlock and Firefox 43.0.4

### ISSUE THREAD

**Issue by pwp3** [gorhill/uBlock#1290]
Using Firefox (43.0.4 on PC) Gmail contacts just won't open, it just hangs. Contacts open just fine on Chrome & MS Edge. The Mail area is fine. It all worked fine up to FF 43.0.4

When uBlock is disabled, everything works fine. This looks like a uBlock/Firefox 43.0.4 issue.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

I am not responsible for 3rd-party filter lists. You will have to make the case the issue is with uBlock Origin proper.
