### ISSUE TITLE
Adding a subscription (RU Adlist Counters) in the main sheet.

### ISSUE THREAD

**Issue by thejustsoul** [gorhill/uBlock#1291]
If possible, please add to main kit subscription: 
`RU Adlist: Counters (https://easylist-downloads.adblockplus.org/cntblock.txt)`

**Comment by gorhill** [comment]
Added to: <https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web>.

**Comment by thejustsoul** [comment]
It's understandable that can manually add the subscription. But I would like it to appear in the add-on dashboard. All the time to manually add it on a different PC after installing, tire.
