### ISSUE TITLE
Whitelist specific youtube channels

### ISSUE THREAD

**Issue by jshthornton** [gorhill/uBlock#1292]
Rather than allowing the entire youtube domain, it would be nice to be able to support specific channels by whitelisting them.

**Comment by anewuser** [comment]
You can try this: https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#a-youtube-channel

Please also read this and close this issue: [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

**Comment by jshthornton** [comment]
@anewuser A great alternative, but that requires a third party extension, and a bit of setup. Would be nice to have an easy to use GUI for users. That being said, that script allows for a starting point for a fork.

**Comment by anewuser** [comment]
@jshthornton that script was developed by the creator and maintainer of uBlock Origin himself. Be thankful and read the "[Before you submit](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)" guidelines.

**Comment by gorhill** [comment]
I don't plan to put in code and UI for the whitelisting for specific vendors.

**Comment by sinistersnare** [comment]
Hey, I'm looking for how to whitelist specific YouTube channels, and I came across this issue. The wiki URL linked does not mention how to do this. Is there more up to date information on this?

**Comment by anewuser** [comment]
@sinistersnare Read the comment just above you.

**Comment by sinistersnare** [comment]
I know that its not in ublock officially, but I figured that the people here, if anyone, would know if there was any way with the current iteration of ublock to whitelist specific channels.

I did read the thread, sorry if I seemed misinformed more than I meant to. Have a nice night :)

**Comment by anewuser** [comment]
I'm sorry. I thought that this was the thread where it has been announced that the script wouldn't be supported anymore. Apparently, I'm the one who should read things more carefully. I edited my comment after realizing my mistake, but you saw it before I updated it.

**Comment by sinistersnare** [comment]
great, thanks for the information, and for the link!

I hope one day to support my favorite content creators more efficiently.

Have a good night again!

**Comment by gorhill** [comment]
I do not have time to maintain that script, apparently it was broken, I tried to fix it, but people reports it does not work -- for whatever reasons, could be Youtube changing stuff or just me not spending enough time to fix all the kinks.

Anybopy can write such scripts, so it's just a matter of findings someone who will dedicate some of their time to ensure it works on a regular basis.

**Comment by sinistersnare** [comment]
@gorhill, thanks for the quick reply! Very interesting that the script was finicky. I hope that I (or someone smarter than I), will write such as script. Time to figure out how I guess!
