### ISSUE TITLE
Unable to log in to aetv premium content

### ISSUE THREAD

**Issue by enduser9999** [gorhill/uBlock#1294]
Using FF v 43.0.4, W7 Ultimate. Go to link listed below, when there the content with the empty blue dots shown normally have a key that allows you to log on. When uBlock Origin is enabled the key no longer shows up. Even when all the 3rd party filters are disabled and the cache cleared no content shows up. In fact even when uBlock Origin is disabled the content no longer shows up. You now have to uninstall uBlock Origin in order for the site to work correctly. This problem started to happen sometime within the last two weeks. 
http://www.aetv.com/shows/the-first-48

**Comment by gorhill** [comment]
I don't know what is "content with the empty blue dots". Page appears to display fine.

Marking issue as invalid as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
