### ISSUE TITLE
marketo

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1295]
hi. are you able to do  a neutered version of this: https://munchkin.marketo.net/munchkin.js

i have seen it on a couple sites so far. test page below. the message "You must enable the Marketo cookie to submit this form. Please check any settings you may have blocking cookies. " should not appear if the neutured version of the script works.

https://www.ghostery.com/about-us/contact-us/

**Comment by jo2dan23** [comment]
well something must have changed now it works. very sorry about that.

**Comment by jo2dan23** [comment]
sorry to reopen. it does it now. closed my browser and reopened the webpage now it senses the adblock.

**Comment by gorhill** [comment]
I won't provide a neutered script for every single script out there -- this is a demanding task requiring much more effort and time than crafting a filter. One argument to justify the efforts/time for a neutered script is whether the script is used on a large number of sites.
