### ISSUE TITLE
MakoTV stocks when video ends playing

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1296]
http://www.mako.co.il/mako-vod
please add @@||odb.outbrain.com/crossdomain.xml$object-subrequest,domain=mako.co.il to the Unbreak list.

**Comment by gorhill** [comment]
I do not see any network request to `outbrain.com` on that page.

**Comment by IsraeliUser** [comment]
Pick a show there and seek to the ending.

**Comment by gorhill** [comment]
Pick a show _where_? I just see a black page with one thumbnail at the bottom. Please, provide steps as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), or else we are all wasting time. Something to keep in mind when opening an issue: my time is not cheaper than whoever opens an issue.

**Comment by IsraeliUser** [comment]
It thinks it blocks you because you are not from Israel (by IP).
They also use anti-adblock so if you are not using EasyList Hebrew, videos are blocked for you.
![ma](https://cloud.githubusercontent.com/assets/16334618/12560123/a538aae4-c3a1-11e5-85c5-c83969f8fca4.png)

**Comment by gorhill** [comment]
Ok, now I found out I had to have Flash enabled, the whole page is a Flash widget.

Once it's done, I clicked on one of the thumbnail which had a play icon, and this is what I was served:

![a](https://cloud.githubusercontent.com/assets/585534/12560339/26dcb34a-c368-11e5-9e09-30f20c8ab9a8.png)

I will just go ahead and take your word for it and add the exception -- it applies only to one single web site anyways.

**Comment by IsraeliUser** [comment]
It's their anti-adblock. If you use **EasyList Hebrew** you should NOT see this message.

**Comment by gorhill** [comment]
> If you use EasyList Hebrew you should NOT see this message

Sorry about that, I missed that part. With EasyList Hebrew I get a different message, probably geo-blocked I supposed:

![a](https://cloud.githubusercontent.com/assets/585534/12560565/77f0fff6-c369-11e5-94f2-b2dc161098e5.png)

**Comment by IsraeliUser** [comment]
You are correct.

**Comment by gorhill** [comment]
I wonder if blocking <http://odb.outbrain.com/crossdomain.xml> causes a lot of video players to break. The content of the file is almost nothing. Were there parameters in your `http://odb.outbrain.com/crossdomain.xml` URL? (the part following the `?`)

If not, I will just create a global exception for that one resource -- probably only used with Flash-based players.

**Comment by gorhill** [comment]
Actually never mind, answer is in your screenshot above.
