### ISSUE TITLE
After visiting particular page, rule to block all 3party stuff gets deactivated 

### ISSUE THREAD

**Issue by pnebert** [gorhill/uBlock#1299]
after visiting http://www.golem.de/
my selfdefined rule "* * 3p block" gets deactivated and ads will be shown.

after reseting to permanent rules, it works like it should. perhaps they found
 a way to deactivate selfdefined rules? happened 2 times on this page

version: 1.5.5
browser: firefox 43.0.4
os: linux

**Comment by gorhill** [comment]
> my selfdefined rule `* * 3p block` gets deactivated and ads will be shown

Makes no sense, something else deactivated your `* * 3p block`, web pages cannot see extensions, let alone modify their inner state.
Use the logger to diagnose what is occurring on your side. Closing as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
