### ISSUE TITLE
stats.pusher.com

### ISSUE THREAD

**Issue by vivangkumar** [gorhill/uBlock#1301]
Hello,

I work for Pusher and I've recently had a support ticket about uBlock blocking `stats.pusher.com`. It seems to be causing issues for some of our customers.

Would it be possible to remove us off the list? The information we collect is solely related to connections made to Pusher. We collect metrics such as user agents, connection times, connection strategies used and connection state changes etc. This contributes to our logs that we often rely on to help customers out.

I did read the guidelines for contributing  to the repository and this issue does not keep in line with any of them. I'm sorry about that, but I'm unsure where else I can pop this.

**Comment by aggat** [comment]
stats.pusher.com blocked by [EasyPrivacy](https://forums.lanik.us/)
[7. Verify that the issue is not related to a 3rd-party filter lists.](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit)

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> **Verify that the issue is not related to a 3rd-party filter lists.**
> - Issues with 3rd-party filter lists are the responsibility of their respective maintainers.

**Comment by vivangkumar** [comment]
If you did see the last few lines, I mention the exact same thing. However, thanks for pointing me to the right place. Cheers!

**Comment by gorhill** [comment]
>  I mention the exact same thing

Ok sorry, I did not understand the meaning there.

**Comment by gorhill** [comment]
By the way, it's unlikely `stats.push.com` will be removed from EasyPrivacy based on the given reasons -- the reasons you invoke ("collect metrics") actually support that it should stays in EasyPrivacy as per its primary purpose.
