### ISSUE TITLE
Each time I "element-picker-select" something a new "selfie" is shot.

### ISSUE THREAD

**Issue by Goderw** [gorhill/uBlock#1302]
Hello,

each time I  select something with the element-picker a new selfie will be created by uBo. What about a critical-mass selection... maybe 30 new filters created by element-picker in cache before a selfie is shot? 
Why: If Firefox isn't run a while after that (before a selfie is taken) the start of FF is 5 times slower than with a given selfie instead. And the power consumption for just one new filter to create isn't worth it!? :)

**Comment by gorhill** [comment]
I don't understand your point. You recommend to create a selfie only after "30 new filters" are created, but yet point out that FF is slow to start without a selfie. This is contradictory.

**Comment by Goderw** [comment]
Sorry for inconvenience, 
I can agree that a selfie is really necessary for 127000 filters... but my point of view was to argue that just a few filters extra (<2 maybe)  don't slow down the browser - or do they, I don't know by now. It was just a try to reduce a possible overwhelming.

**Comment by gorhill** [comment]
Ok, I think I get what you mean: do not invalidate the current selfie until many filters are created.

I am still going to decline this one, this would require too much code change, make code path more complicated, (and add work on my plate), while at this point I favor stability. In the big picture, I think a majority of people do not create new filters, so such change would not benefit the majority.

As usual I may change my mind in some future -- sometimes thinking more about something help, but for now I will decline.

**Comment by Goderw** [comment]
Yes, this was my intention... thanks for your effort!!!

**Comment by gorhill** [comment]
BY the way, how many filter lists do you have selected? "5 times slower" seems a bit much, especially considering that uBO would _still_ load from pre-compiled filter lists (no complicated parsing required).

**Comment by Goderw** [comment]
I have 30 lists activated. Maybe 5 times slower was a bit vague... it is very noticeable slower. My FF starts in a fraction of a second with a selfie (SSD)... with the need to create a new selfie it FIRST comes up slower... then the "background" comes up darker (like if it was under full load) for nearly a second. With a selfie given instead it comes up *without the "darker background"*. So it is always visible to me (beneath the normal delay for the complete window to come up first) that the selfie is missing.

**Comment by Goderw** [comment]
Just for information purposal:
This leads me to rethink every use of the element picker -> is it really worth it!? Why? Because my browser gets closed each time I get what I was searching for... and the given time might not be enough time to create a new selfie... so FF might be still slow for a long period. My PC ins't running all the time so the browser. :)
