### ISSUE TITLE
CONTRIBUTING.md: Need to elaborate on...

### ISSUE THREAD

**Issue by untitaker** [gorhill/uBlock#1304]
* "do not submit PRs" -- Do you mean something like #1241, where the patch is submitted before the idea is proposed?

  * Or are you generally not interested in third-party code submissions?

  * Does that mean I absolutely have to submit issues for trivialities like e.g. typos I find in the UI, instead of "simply" sending a PR?

* "Only submit bug reports" -- Are you generally not interested in suggestions, e.g. how to make the UI better?

* Does this issue violate the CONTRIBUTING rules?

**Comment by gorhill** [comment]
> Does this issue violate the CONTRIBUTING rules?

Yes, because this is not a concrete, specific issue, and everything you ask is answered by the page you reference.

**Comment by untitaker** [comment]
I see an issue with the clarity of said page. I would like to help with that if you told me what the intended meaning is.

**Comment by gorhill** [comment]
The intended meaning is literal:

"do not submit PRs" = do not submit pull requests.

"Only submit bug reports" = only submit bug report.

I don't know how else this can be made more clear.

**Comment by untitaker** [comment]
Alright, thank you. It's what I suspected. My confusion came from the "Submitting issues" headline of the document, implying those rules are specific to reporting issues. Hence this interpretation:

>where the patch is submitted before the idea is proposed

Offtopic (yes, I know, violates the rules): It would be nice to have some sort of rationale or explanation for those rules somewhere.

**Comment by anewuser** [comment]
@untitaker See my opinion [here](https://github.com/gorhill/uBlock/issues/1202#issuecomment-172731730) and the three points listed on [Dear Github](https://github.com/dear-github/dear-github). 

If you want to continue this discussion, follow the fourth "Before you submit" rule and post on Reddit or [Wilders Security Forums](http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/):

> DO NOT... Use issues as replacement for threads on a bulletin board.
