### ISSUE TITLE
Some one added an app with name "Ublock Origin" to chrome webstore. It is not this extension.

### ISSUE THREAD

**Issue by vijaykm2** [gorhill/uBlock#1308]
Some one added an app with name "Ublock Origin" to chrome web store. This new app would cause confusion for users. It is not this extension. I actually managed to install this app install instead of extension on new chrome installation. See attached screenshot.
<img width="960" alt="ublock duplicate" src="https://cloud.githubusercontent.com/assets/6619551/12635540/f7b7ba36-c549-11e5-83fc-5457fa23a84e.PNG">

**Comment by anewuser** [comment]
Please use the report feature of the Google Chrome Store instead of creating issues here. This repository is to be used only to report bugs. 

[CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by vijaykm2** [comment]
?I reported this to chrome webstore also. I was wondering if this is a valid app.

**Comment by anewuser** [comment]
The actual developer goes by the nickname **gorhill** on all websites related to his extensions, and he updates them by himself. He doesn't have anything to do with extensions offered under other names or websites (and neither do the rest of us here). You can see [a list of official links on the frontpage of this repo](https://github.com/gorhill/uBlock#installation).

Thank you for using and support uBlock Origin. Please close this issue to mark it as solved.
