### ISSUE TITLE
Cannot download files properly

### ISSUE THREAD

**Issue by hroncok** [gorhill/uBlock#1311]
1. browser version/ublock version: Chromium 47.0.2526.80 and .106 on Fedora 64bit, uBlock Origin 1.5.6
2. I've explicitly clocked the button to restore default settings of uBlock
3. Go to http://www.addic7ed.com/serie/Making_A_Murderer/1/6/Testing_the_Evidence
4. Click Download button at any subtitles
5. Observe no download is happening * (log attached in [logs.zip](https://github.com/gorhill/uBlock/files/108959/logs.zip))
6. Got to https://churchyard.fedorapeople.org/
7. Click on any file your browser would normaly download and not try to display (try zips or odts)
8. Observe download is not happening * (log attached in [logs.zip](https://github.com/gorhill/uBlock/files/108959/logs.zip))
9. Close the browser window (the last remaining one)
10. Observe a message about download in progress

* Sometimes, the download starts when you change tabs to the logger, try to reproduce without logger opened. Sometimes the download just starts 10-20 secunds than expected.

I think if I go to addic7ed.com then it affects are other sites and tabs as well (so fedorapeople is not necessarily here to blaim). Also sometimes the download never happens, sometimes it just does after some amount of time (sometimes even a minute).

When I deactivate uBlock ang go back to the tab where the download originated (was supposed to happen), it happens. This issue only happens when uBlock is activated.

Let me know what other information I can provide.

**Comment by Eeems** [comment]
You may also want to list the other addons you have installed just in case they are fighting with ublock for some reason.

**Comment by hroncok** [comment]
Only Google Docs offline.

**Comment by hroncok** [comment]
Disabling it doesn't change the issue.

I'v also noticed a very long delay when clicking Browse... button in file upload forms.

**Comment by gorhill** [comment]
Unable to reproduce, everything downloaded just fine.

**Comment by hroncok** [comment]
That's what I was afraid of :(

Would a video help?

**Comment by gorhill** [comment]
According to your logs, the downloads were not blocked:

    23:21:05    inline-script  https://churchyard.fedorapeople.org/bug1152846.zip
    23:21:04    doc            https://churchyard.fedorapeople.org/bug1152846.zip
    https://churchyard.fedorapeople.org/bug1152846.zip

I get the same exact thing and it works fine here.

Do you have any flags set in your Chromium which are not normally set?

**Comment by gorhill** [comment]
Other things to try:
- Any message of interest in the page's dev console?
- What does the Network pane in the page's dev tools report?
- Anything in uBO's dev console?
- If you launch the browser with command line, any interesting message in shell console?

**Comment by vendforce** [comment]
#horcok try uninstalling ublock and reinstalling also deactivate all extension you have installed except for ublock and see if you can download , Ive tried the links and I also have no problems like gorhill downloading

**Comment by hroncok** [comment]
Thanks all. I've update to Chromium 48 and the issue is gone.
