### ISSUE TITLE
uBlock Origin in Tor Browser and Tails

### ISSUE THREAD

**Issue by nikcub** [gorhill/uBlock#1313]
Per [this conversation on HN](https://news.ycombinator.com/item?id=10988948) we want to migrate privacy-oriented operating system from using AdBlock Plus to using uBlock Origin.

We here know the pro's and con's so we don't have to go through that, but i'm going to post it to the tails-dev mailing list in a moment. It is a topic that comes up with regularity on tails-dev, and now it seems all the last impediments to moving to uBlock Origin have been removed.

Hey @gorhill I couldn't find your email address online (in your line of work that is probably a good thing) - would you like me to copy you on this email thread with tor-dev? If so shoot me an email on nik at nikcub.com so I have your address.

**Comment by RoxKilly** [comment]
it'll be great to have uBo on Tails and in Tor Browser

**Comment by gorhill** [comment]
Ok I just subscribed to tails-dev and tor-dev.

**Comment by nikcub** [comment]
Both is fine - i'll start this up on Tails first then once that is done we'll work on getting it done in the standard Tor Browser.

**Comment by nikcub** [comment]
@gorhill email is out, let me know if there is anything you want to add or change because I also take this up with Tor Browser.

What do you think about building support for the HTTPS Everywhere ruleset? Their format is XML so it would be transformed and hosted somewhere else, but to me it doesn't make much sense to have to build and run an entirely separate engine for HTTPS redirects when it could be achieved in uBlock.
