### ISSUE TITLE
Fix problems reported in Debian Lintian's runs

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1318]
See <https://lintian.debian.org/maintainer/pkg-mozext-maintainers@lists.alioth.debian.org.html#ublock-origin>:

> src/js/uritools.js line length is 1115 characters (>512)

**Comment by gorhill** [comment]
Fixed in 8b721f654cb0ff22830a6c745c5b51d3da862c9b.

**Comment by spwhitton** [comment]
Thanks for removing code that you no longer needed.  However, you should know that Lintian was incorrect in thinking that the source was not available -- there's nothing wrong with a long regexp.  I thought I'd overriden the warning but apparently not.
