### ISSUE TITLE
[suggestion] language option

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uBlock#1319]
It may be should add an option for choice of language right in the ublock's interface?

**Comment by gorhill** [comment]
uBO will use whatever language is selected for the browser.

Dup of #241.

**Comment by jhsagl4a** [comment]
Yes, but in browser I use English language, because that's good for privacy, but in uBlock I would like to use my native language and I can't.

**Comment by arthurtiteica** [comment]
Language of the browser has nothing to do with the language you transmit in the headers with 'Accept-Language'

**Comment by jhsagl4a** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=670450
https://bugzilla.mozilla.org/show_bug.cgi?id=670451

**Comment by gorhill** [comment]
`intl.accept_languages`

**Comment by jhsagl4a** [comment]
`intl.accept_languages "en-US, en"`
`general.useragent.locale "en-US"`
for better privacy, because
https://bugzilla.mozilla.org/show_bug.cgi?id=670451
