### ISSUE TITLE
(SeaMonkey) Adding subscription from resource: URI does not work

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uBlock#1321]
**Environment:**
- uBlock Origin 1.6.0 (self-built from https://github.com/gorhill/uBlock/commit/64e9eb7aae853e1c4b5511ddc1796c49debeb0d1 using the included make-firefox.sh script)
- SeaMonkey 2.39

--------------------------------------------------

Under "3rd-party filters" it does not work to add a custom subscription pointed to a resource: URI.  The subscription I used for testing has many valid filters (including both blocking and cosmetic), but uBlock Origin reports this:
`resource://[path/to/subscription].txt : 0 used out of 0`
and clicking the link for the uBlock Origin asset viewer on this subscription, gives a blank page.

It seems that what matters here is only that the subscription be at a resource: URI, not a problem with the particular subscription.  (FWIW Adblock Plus correctly handles the subscription from its same resource: URI.)

I tried to add the subscription by replacing the entire text of the textbox under "Custom" with the resource: URI; then select "Parse", then disable all other subscriptions (except "My filters") then "Apply changes".

Testing in a clean profile, installed only uBlock Origin and a simple addon that only creates a resource: URI pointer to a subdirectory of the profile; and all settings other than mentioned above are default.  (And I restarted the browser after installing uBlock Origin and before testing.)

**Comment by gorhill** [comment]
What is the exact URL?

**Comment by laniakea64** [comment]
Thanks for looking into this.  If exact URL is needed I should probably post my addon's bootstrap.js...
```
const Cc=Components.classes, Ci=Components.interfaces, Cr=Components.results, Cu=Components.utils;
Cu.import("resource://gre/modules/Services.jsm");
Cu.import("resource://gre/modules/osfile.jsm");

let handler = Services.io.getProtocolHandler("resource").QueryInterface(Ci.nsIResProtocolHandler);
let RESOURCE_URI_BASE="abplocal";

function startup(data, reason)
{
  handler.setSubstitution(RESOURCE_URI_BASE, Services.io.newURI("file://"+OS.Constants.Path.profileDir+"/"+RESOURCE_URI_BASE+"/", null, null));
};

function shutdown(data, reason)
{
  handler.setSubstitution(RESOURCE_URI_BASE, null);
};

// unneeded boilerplate code
function install(data, reason) {};
function uninstall(data, reason) {};
```
It's needed to manually create the abplocal directory inside the profile folder.

subscription's exact URL would be `resource://abplocal/yt.txt` here.

**Comment by gorhill** [comment]
My understanding is that the same-origin-policy is enforced for `resource:` URI, so I don't understand that this would work with ABP -- unless `resource://abplocal/yt.txt` is a resource inside the realm of ABP.

Try to use a `file:` URI for uBO, last time I tried this worked.

**Comment by laniakea64** [comment]
Last I checked, ABP fetches subscriptions with XMLHttpRequest run from its chrome context (lib/downloader.js); I think same-origin policy doesn't apply there.

This particular resource: URI is related only to the extension of which I post the bootstrap.js, nothing else. (the basename of the resource: URI can be anything)

Testing with file: URL and that does works perfectly.  However the reason I can't use file: URLs is because I have to copy my entire profile to several different computers (mostly VMs) that simply don't/can't have the same file paths as my main machine.  The use of resource: URI alias of a folder inside the profile directory, is the best way I could come up with to reliably transfer miscellaneous local files needed by the profile, without paths becoming messed up at the destination.

**Comment by gorhill** [comment]
> Last I checked, ABP fetches subscriptions with XMLHttpRequest run from its chrome context 

This is exactly what uBO is doing.

I just tried with ABP, and it is not true that it is able to read a `resource:` URI:

    Adblock Plus: Downloading URL resource://adguard/filterrules_2.txt failed (synchronize_invalid_url)
    Download address: resource://adguard/filterrules_2.txt?addonName=adblockplus&addonVersion=2.7.1.4132-beta&application=firefox&applicationVersion=44.0&platform=gecko&platformVersion=44.0&lastVersion=0&downloadCount=0
    Channel status: -1
    Server response: 0

**Comment by gorhill** [comment]
Ok, I forgot uBO was filtering URL according to scheme, but even removing that filtering, an error is returned when trying to fetch the resource:

    "Unable to connect to resource://extension-data/toto.txt" assets.js:953:1

So from here both ABP and uBO can't fetch from a `resource:` URI.

**Comment by laniakea64** [comment]
> I just tried with ABP, and it is not true that it is able to read a resource: URI

I'm not making this up, it really does work for me.  Are you testing with SeaMonkey?  That ABP download URL indicates you're testing with Firefox 44.0.

------------
And thank you for the pointer to assets.js - because if I change this line in assets.js
`var reIsExternalPath = /^(file|ftps?|https?):\/\//;`
to this
`var reIsExternalPath = /^(resource|file|ftps?|https?):\/\//;`
then uBlock Origin correctly fetches the subscription from the resource: URI, and the asset viewer works as expected as well.
I have confirmed again that the filters are indeed being read, by adding `||com^$important` to my subscription, forcing an update, and visiting some .com site - uBlock Origin blocked that site completely.

**Comment by gorhill** [comment]
> I'm not making this up

Can you give me the details on how I could reproduce? I put a file named `toto.txt` in `[profile]/extension-data/`, then tried to use `resource://extension-data/toto.txt` in both ABP and uBO, it didn't work.

**Comment by laniakea64** [comment]
> Can you give me the details on how I can reproduce?

Sure, no problem.
OK so the bootstrap.js I posted above is all that's really needed to get the resource: URI pointer extension I'm using to work.  Create your own restartless-extension install.rdf to go alongside it, rename the resource: URI pointer if you want (but make sure it isn't to an already-existing directory in the profile nor an already-existing resource: URI), then pack those up as an xpi.

Here are the STR using that xpi and SeaMonkey, from a clean profile:
1) in your profile folder, create the directory for your resource: URIs and add your valid subscription file
2) install the extension created from my bootstrap.js
3) install uBlock Origin, restart SeaMonkey
4) add the subscription from (1) to uBlock Origin per above

**Comment by gorhill** [comment]
I will just go ahead and make the change which make the `resource:` works -- I will try the step-to=-reproduce when I have time, the issue was rather me not fully grasping what exactly a FF `resource:` is.

**Comment by laniakea64** [comment]
Fixed, thank you gorhill ! :smiley:
