### ISSUE TITLE
Popup appears for a split second when searching on The Pirate Bay using Firefox

### ISSUE THREAD

**Issue by Cormak** [gorhill/uBlock#1324]
When using ["Medium mode" ](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) on uBlock 1.5.5 on Firefox 44, performing a search on [The Pirate Bay](https://thepiratebay.se/) lets in a popup for a split second before it disappears. As soon as the results page loads after performing a search, you can see a popup window appear and disappear. Shouldn't the popup be completely suppressed when using Medium mode? 

No other blocking addons are installed.

**Comment by gorhill** [comment]
Popup blocking can't be done in a synchronous manner, there is no blocking API which can guarantee the popup window won't appear.

**Comment by gorhill** [comment]
Another trick: block inline script for the site, the popup code is triggered by inline script code on the page.

**Comment by jo2dan23** [comment]
if you add this filter: /?placement=*&redirect$document

it will stop the connection to the ad domain.
![screen shot 2016-02-08 at 5 24 16 pm](https://cloud.githubusercontent.com/assets/15130139/12902744/98e0cf82-ce88-11e5-94ab-5f13b3d478d7.png)

**Comment by Cormak** [comment]
@jo2dan23 @gorhill Thanks for the pointers.

**Comment by IDKwhattoputhere** [comment]
Couldn't uBO treat `$popup` as `$document,popup`? Then this request wouldn't be send. :question:

**Comment by gorhill** [comment]
Network requests and notifications about new tab or window opening are two different code paths. There is no way to prevent tab or window from opening, there is no blocking API for this.
