### ISSUE TITLE
Firefox 44 cannot load anything

### ISSUE THREAD

**Issue by OrangeDog** [gorhill/uBlock#1325]
After upgrading to Firefox 44 no pages were ever loaded - just blank pages with infinite loading spinners in the tabs.
Enabling addons one at a time showed that uBlock Origin 1.5.5 was responsible.

**Comment by Hrxn** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
