### ISSUE TITLE
EasyList and EasyPrivacy filters outdated

### ISSUE THREAD

**Issue by djprmf** [gorhill/uBlock#1326]
hi,

I notice that the EasyList and EasyPrivacy filters in uBlock are almost 2 months outdated (last update 13 Dec 2015).

- https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
- https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt

Since this date, the filters have been updated and there was some important "false positives" issues fixed. For instance, the Google Tag Manager script is being blocked by your filter, but not in the EasyPrivacy filter (due to the high false positive of this).

Isn't time to update the lists to users that don't add the EasyList directly? (new users of uBlock, for instance).

BTW:

- https://easylist-downloads.adblockplus.org/easylist.txt
- https://easylist-downloads.adblockplus.org/easyprivacy.txt

Thanks

**Comment by gorhill** [comment]
> Google Tag Manager script is being blocked by your filter

False:

uBO's current EasyPrivacy:

    ||googletagmanager.com/gtm.js?$third-party

Current EasyPrivacy:

    ||googletagmanager.com/gtm.js?$third-party

I do plan on updating the packed version of the filter lists once in a while -- I was planning to possibly do it for 1.6 -- please do not open an issue about this, specially using an invalid argument such as _"Google Tag Manager script is being blocked by your filter"_.
