### ISSUE TITLE
uBlock Origin sometimes deactivated when running it from a network drive on Firefox Portable

### ISSUE THREAD

**Issue by anonsubmitter** [gorhill/uBlock#1331]
I run Firefox Portable from a network drive in school since that is the only way to have any kind of custom browser configuration. The school's networks drives are very slow and laggy. Sometimes when I start up Firefox Portable the uBlock Origin icon has disappeared from the toolbar and the "Show Dashboard" and "Show Logger" buttons in Firefox's Add-ons Manager are blank and unclickable. If I remember correctly ad blocking is also not working when this happen, but I'm not 100% sure since I usually restart the browser until the bug is gone again.

Firefox Portable 41.0
uBlock Origin 1.5.5

**Comment by gorhill** [comment]
When this happens, you will have to report here errors from the browser console -- the symptom you describes mean uBO failed to initialize because of some errors triggered in the initialization code.

**Comment by anonsubmitter** [comment]
Ok. Here's what the browser console gives me:

`case-change:ReferenceError: storage is not defined
Stack trace:
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-ekpckn0oj3pa4zh8lzqavyghxcy-at-jetpack/case-change/lib/main.js:132:8
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:151:1
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740:39
 runner.js:164
case-change:ReferenceError: storage is not defined
Stack trace:
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-ekpckn0oj3pa4zh8lzqavyghxcy-at-jetpack/case-change/lib/main.js:132:8
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:151:1
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740:39
 Promise-backend.js:925
SecurityError: The operation is insecure. proxy.html:59:0
about:blank : Unable to run script because scripts are blocked internally. <unknown>
SecurityError: The operation is insecure. Browser_Console:59:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com"). 1331:1:0
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-ee521b8e9facac68ff27e93fc3ae0f8ed811d7bf9e434e84f4b9ea227780b084.js:1:20147`

**Comment by anonsubmitter** [comment]
And for comparision here is a healthy browser session:

`Could not read chrome manifest 'file:///U:/FirefoxPortable/App/firefox/chrome.manifest'.
SSL Observatory WARN: Failed to initialize NSS component:Error: couldn't find function symbol in library
Get a connection to permissions.sqlite.
case-change:ReferenceError: storage is not defined
Stack trace:
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-ekpckn0oj3pa4zh8lzqavyghxcy-at-jetpack/case-change/lib/main.js:132:8
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:151:1
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740:39
 runner.js:164
case-change:ReferenceError: storage is not defined
Stack trace:
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-ekpckn0oj3pa4zh8lzqavyghxcy-at-jetpack/case-change/lib/main.js:132:8
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:151:1
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740:39
 Promise-backend.js:925
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] aus4.mozilla.org
[ABE WAN] Detected WAN IP 81.209.26.4
Key event not available on some keyboard layouts: key="r" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="c" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt,shift" browser.xul
SecurityError: The operation is insecure. repair:7:0
1454575440090	Services.HealthReport.HealthReporter	WARN	Saved state file does not exist.`

**Comment by gorhill** [comment]
I don't see anything related to uBO in that stack trace.

**Comment by anonsubmitter** [comment]
I haven't removed any line breaks, I just used Ctrl + A and Ctrl + C on the browser console.
Maybe the error has something to do with the laggy network drive then?

**Comment by gorhill** [comment]
When you say "laggy", what sort of lag are we talking here? Seconds?

**Comment by anonsubmitter** [comment]
Here is a proper diff paste: https://www.diffchecker.com/gasc2qj9
I forgot that I have [Copy As Plain Text](https://addons.mozilla.org/firefox/addon/copy-as-plain-text/) installed, so that must have stripped away the line breaks when I copied the browser console logs from my GitHub comments.

Seconds yeah. Not sure for how long exactly, but at least tens of seconds. The browser almost crashes sometimes (and a few times it does crash).

**Comment by gorhill** [comment]
> but at least tens of seconds

Ok then, this could explain the issue here. There are many places uBO will time out after 2 seconds if something it wants to initialize can't be initialized just yet. The bootstrap code itself will wait up to 10 seconds before giving up.

**Comment by anonsubmitter** [comment]
Ok, then that's probably it.

**Comment by gorhill** [comment]
Actually I was mistaken, uBO's `bootstrap.js` will try for 30s, not 10s. Is it still within the lag time?

**Comment by anonsubmitter** [comment]
It's not within the response time for when the browser almost crashes, but it might be within the time it takes from clicking on Firefox Portable until the browser window has popped up. I'll have to time it the next I have the chance to do so.
