### ISSUE TITLE
Hosts bypassed afer last filter update

### ISSUE THREAD

**Issue by hoybles** [gorhill/uBlock#1332]
One of the latest definiton updates (I believe uBlock filters‎) seems to have bypassed my hosts file allowing pop ups to be enabled.

with uBlock enabled i get pop ups and with it disabled i do not. so it appears my hosts file is being bypassed with the extension enabled.

I only have the ublock filters and Fanboy+Easylist-Merged Ultimate List‎ enabled

![untitled](https://cloud.githubusercontent.com/assets/17029499/12756391/7a229330-c9cb-11e5-9447-717d24471ee4.png)

This was working fine before the last definition update so something must of changed.

I can also ping the IP that is blocked in my hosts when chrome is open and uBlock  is enabled but when i close chrome I cannot ping it.

**Comment by gorhill** [comment]
> with uBlock enabled i get pop ups

[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> The most important part when opening an issue: detailed steps.

Also, to claim uBlock Origin is bypassing your HOSTS file is nonsense, uBO hooks into Chrome's webRequest API to block network requests, it is sandboxed by the browser, it can't modify your network or OS settings.
