### ISSUE TITLE
[Question] About Filters Auto Update feature

### ISSUE THREAD

**Issue by ThisIsTooHardStepToTake** [gorhill/uBlock#1333]
> **Browser:** Chrome Canary 50.0.2638.0 x64
> **uBO:** 1.5.6

I'm not sure how often uBO will automatically check the updates if Filter list is outdated and/or if there is a newer version available. But I noticed that I have outdated Filters, I decided to wait a bit. After around 4 days I thought to check out my Filters if they were updated. I noticed that they were still outdated.

I think that it would be great if uBO would tell users that there is Filters which you can update, like through Chrome's desktop notification or flashing the uBO toolbar icon. There should be easier way to identify outdated Filters without constantly checking out uBO settings. Desktop notification could be a 3rd-party feature which you can enable through uBO settings. Or you could just click uBO toolbar icon and select Update Filters, that would be very handy.

**Comment by gorhill** [comment]
> Desktop notification could be a 3rd-party feature which you can enabled through uBO settings.

I prefer uBO to stay low profile as much as possible, not remind its own existence through notifications which add little to no value. Filter lists auto-update every 4-5 days, there is no need to obsess over this. The only time updating filters is issue is if a problem occurs on a specific web site while knowing the fix has been added to one of the filter lists -- a rare occurrence.
