### ISSUE TITLE
Block X if X.Y matches?

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#1334]
I have a selector `X`, and I have a trigger `.Y`, how can I block **an** `X` (not all `X`) iff it has a `.Y` child?

**Comment by Betsy25** [comment]
Don't know if I'm referring to what you want, but here's some more info anyway.

[ABP Filters explained](https://adblockplus.org/filter-cheatsheet#elementhiding)
... more specifically : [CSS Selectors](http://www.w3.org/TR/css3-selectors/#selectors) can point you in the right direction.

**Comment by gorhill** [comment]
> how can I block an X (not all X) iff it has a .Y child?

You can't, there are no CSS3 selector syntax supporting this. CSS4 will support this with `:has()` (unless to remove this from the draft), but we are not there yet.

**Comment by SoniEx2** [comment]
Can it be added as a uBlock feature?

**Comment by Hrxn** [comment]
Matching a selector, independent of the actual selector pattern, to a node/element in the DOM tree is done by the rendering engine at the core of the browser, this is not within scope of an extension.
Without ever looking at the uBO source, I'd bet that it's not an exception here..

It can be done somehow, but I'd assume that (implementing your own selector matching engine) would be **a lot** of work.

So I guess, the answer is, no.

Correct me if I'm wrong, though..

**Comment by SoniEx2** [comment]
Match all base components then check each for submatches. First one gives you a list of `X` and second one checks if they have a `.Y` child.

**Comment by Hrxn** [comment]
If the browser doesn't provide an API to do this kind of stuff..

**Comment by SoniEx2** [comment]
Then you can just use jQuery, probably.

**Comment by gorhill** [comment]
> Then you can just use jQuery

jQuery does not cause a browser to automagically start supporting natively features that are not part of the browser yet.

See <https://github.com/gorhill/uBlock/issues/769>.
