### ISSUE TITLE
[How to block] Action Panels on YouTube

### ISSUE THREAD

**Issue by ThisIsTooHardStepToTake** [gorhill/uBlock#1335]
I tried to block `Action Panels` with `###watch-action-panels` with no luck. I also have a [YouTube Other Annoyances](https://easylist-downloads.adblockplus.org/yt_annoyances_other.txt) Filter list by Adblock and I think it's not working as it should. I know I should report this bug to them but I wanted to ask you first. Then I can link this thread after I've contacted you. I also checked out the uBO Logger but I'm not 100% sure if I saw anything there.

This is from the Adblock's list which should work but it's not working if I understand correctly.

> ! Removes sharing tab below videos
> ||youtube.com/share_ajax?action_get_share_box=1&video_id=$xmlhttprequest
> youtube.com##.action-panel-trigger[role="button"][data-trigger-for="action-panel-share"]
> youtube.com##.yt-uix-button[data-trigger-for="action-panel-share"]

![untitled](https://cloud.githubusercontent.com/assets/17030424/12768701/39cee244-ca1a-11e5-8aa8-7511a8851f98.png)

I also found this thread on [Adblock's forum](https://adblockplus.org/forum/viewtopic.php?f=2&t=43534).

Here's a [example video](https://www.youtube.com/watch?v=ymVXuT0Yfl4) for you.

**Comment by gorhill** [comment]
I have no problem creating a filter for `#watch-action-panels` with the element picker.

See if the filter is in _My filters_ in the dashboard. If so, then find out why it is not applied: <https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page>.

**Comment by ThisIsTooHardStepToTake** [comment]
It does appear there:

![untitled](https://cloud.githubusercontent.com/assets/17030424/12769216/9e07bd5e-ca1e-11e5-9a11-2ed7b9c22e1f.png)

But somehow this rule is not working because YouTube will somehow inject the Action Panel again when you refresh the page.

**Comment by gorhill** [comment]
> YouTube will somehow inject the Action Panel again when you refresh the page.

It works here. The panel is not removed by uBO, a `display: none !important;` style is applied to it. Since it works fine from here, the best explanation is that something is overriding the cosmetic filter on your side, be sure to rule out the reasons in the link I provided above.

**Comment by ThisIsTooHardStepToTake** [comment]
I also tried to disable YouTube Other Annoyances filter list and only enabled the `#watch-action-panels` rule, it will hide the Action Panel yes but it will display the Action Panel like 2 seconds before hiding it.

**Comment by gorhill** [comment]
> it will hide the Action Panel yes but it will display the Action Panel like 2 seconds before hiding it.

What is your browser? How many extensions do you have, and what are they? What is your CPU/memory?

`youtube.com###watch-action-panels` is a specific cosmetic filter, meaning it is typically injected before the DOM of the page is completely loaded, there should be no glitch.

**Comment by ThisIsTooHardStepToTake** [comment]
> **Browser:** Chrome Canary 50.0.2638.0 x64
> **uBO:** 1.5.6 (Only extension I have)
> **CPU:** Intel Core i7-4790K
> **RAM:** 16GB DDR3 2133MHz

**Comment by gorhill** [comment]
First:

> I tried to block Action Panels with ###watch-action-panels with no luck.

Then, after I spent time trying to reproduce your issue:

> it will hide the Action Panel yes but it will display the Action Panel like 2 seconds before hiding it.

What is the issue **exactly**?

**Comment by gorhill** [comment]
> it will display the Action Panel like 2 seconds before hiding it.

I have a hard time believing this given your h/w profile. Make a video to support this -- specific cosmetic will typically never cause DOM elements to glitch.
