### ISSUE TITLE
network requests being re-addressed

### ISSUE THREAD

**Issue by ferrvittorio** [gorhill/uBlock#1336]
On Chrome, network requests of extension Ghostery are being readdressed by Ublock

**Comment by gwarser** [comment]
Like this https://github.com/gorhill/uBlock/issues/1170 ?

**Comment by ferrvittorio** [comment]
Yes, but not in Polish.

--
Vittorio Ferrando
Il 03/feb/2016 10:14, "gwarser" <notifications@github.com> ha scritto:

**Comment by gorhill** [comment]
Duplicate of #1170.
