### ISSUE TITLE
[Chrome, Windows 7] Strange bug with specific website

### ISSUE THREAD

**Issue by gotmilk0112** [gorhill/uBlock#134]
Over the past month or so, I've been experiencing a strange bug in uBlock with a specific website, "derpibooru.org".

Every once in a while, when I block an image on that site, uBlock somehow bugs out and starts blocking almost every single element on every page, leaving nothing but a header bar at the top of the page. It doesn't do this EVERY time, it does it at random, after blocking an image.

I then go into the "My Filters" tab and look at the latest additions, and there's nothing unusual about them. Just the same image URLs as the others I've blocked.

Stranger still, to fix this issue, all I have to do is change something so that I can use the "Apply Changes" button. Like...adding a space at the end of one of the URLs, and then clicking "Apply Changes". And this fixes the strange bug, without adding or removing any filters.

Any idea what's going on here? It doesn't seem to do this on any other website, only Derpibooru.org. And since use of the "Apply Changes" button seems to fix it, I'm guessing that it's some kind of glitch with uBlock.

**Comment by gorhill** [comment]
If I want to try to reproduce, which images on that site should I block?

**Comment by gotmilk0112** [comment]
Any of the images in the squares. Those are typically what I block, and while most of the time it works (only that image gets blocked and nothing else), sometimes it bugs out and blocks 95% of the page, on every single page that I try to visit.

**Comment by gorhill** [comment]
Just to be sure, could it be related to that element picker feature introduced in [0.9.2.0](https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.2.0)?

> Element picker: ability to point-and-click to create **wildcard-based** network filters

Wildcard = `*`.

If you select the bottom-most **network** filter in the element picker, it might be a wildcard-based one, and it will likely target to more than one image -- that's their purpose. That filter entry do get broader and broader as you block more and more images for one single web site (not web page, web site).

**Comment by gorhill** [comment]
Do you have a lot of custom filter?

**Comment by gorhill** [comment]
I found a problem. I can't tell yet however whether this can cause the issue you are experiencing.

**Comment by gotmilk0112** [comment]
I don't think I'm using any wildcards when adding a filter, no. When I go to filter something, the URL that comes up looks something like:

||derpicdn.net/img/2015/4/26/883535/thumb.png

No wildcards, just the direct URL of the image.

And yes, I have a ton of custom filters. A lot of them aren't exactly necessary anymore now that I think about it, so I could try cutting my custom filters down a bit.

**Comment by gorhill** [comment]
Ok, the bugs I found are bad (as in embarrassingly bad -- I don't get how I could come up with that code), I will assume this is what is causing the issue you are experiencing. The bug expresses itself only when creating a filter from the element picker.
