### ISSUE TITLE
goyavelab.com

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#1340]
Hi @gorhill, 

similar to `jeu.info` already on [optimized uBlock filters‎ list](https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt) all these websites below use [g0yave lab](http://tinyurl.com/anti-adblock-g0yav3-lab) solution to bypass adblockers and display their very annoying ads.

Thanks for fixing!

```
filmvf.net
gum-gum-streaming.com
gaara-fr.com
tuxboard.com
dpstream.net
filmstreaming-hd.com
```

**nsfw**
```
hentaifr _ net
xstory-fr _ com
hentaihaven _ org
gaytube _ com
```

* ***I will use this thread to report other sites with same Issue***.

**Comment by gorhill** [comment]
Actually `jeu.info` is rather broken when disabling inline scripts, that was put in there a long time ago. I removed the `inline-script` filter and will dig further when I have time, now that uBO has more tools to defuse such ads.

**Comment by gorhill** [comment]
I can't tell whether this helps or not, don't know these sites enough.

**Comment by IDKwhattoputhere** [comment]
> gorhill closed this 14 minutes ago

Does that mean I shouldn't be seeing ads on those sites? Just updated my filter lists but I'm still getting ads: [NSFW hentaihaven _ org](https://cloud.githubusercontent.com/assets/16030872/12918864/ba2d0fde-cf41-11e5-943f-a185b306a776.jpg)
I'm also getting popunders.
uBlock Origin 1.5.6 / 1.6.0rc1 with standard configuration
Chrome 48 / Chromium 50

**Comment by SMed79** [comment]
@IDKwhattoputhere actually [Anti-Adblock Killer Script](https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek) (by @reek) kill these kinds of crap ads provided by g0yave lab.

**Comment by IDKwhattoputhere** [comment]
[Version 9.2](https://cloud.githubusercontent.com/assets/16030872/12924908/0936bf20-cf5c-11e5-91a1-08fb21946e1d.png)

**Comment by reek** [comment]
@SMed79 
<code>hentaihaven.org</code> is not supported by 9.2 but will be in the 9.3

@IDKwhattoputhere 
but you can add it line
https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L3944

**Comment by IDKwhattoputhere** [comment]
@reek It works. Thanks! The two popunders are unaffected though. Two cookies (hh_ppndr1 and hh_ppndr2) are created. The domains for the popunders are trw12.com and traffichaus.com (syndication.traffichaus.com to be precise). Should I send those domains to @pgl or can you or @gorhill add something for them?

**Comment by reek** [comment]
@IDKwhattoputhere 
I'll see if I can add a rule

**Comment by reek** [comment]
add rule
<pre>
    hentaihaven_org : {
      // issue: https://github.com/gorhill/uBlock/issues/1340
      host : ['hentaihaven.org'],
      onAlways : function () {
        // Prevent popunder
        Aak.setCookie('hh_ppndr1', 1);
		Aak.setCookie('hh_ppndr2', 1);
      }
    },
</pre>

**Comment by IDKwhattoputhere** [comment]
Works great! Thank you.

**Comment by SMed79** [comment]
un autre site que j'ai trouver `http://www.narutoshippudenvf.com/`

**Comment by reek** [comment]
Ok, merci.

2016-03-02 7:09 GMT+01:00 Med <notifications@github.com>:

**Comment by SMed79** [comment]
et un autre `http://www.thebadbuzz.com/`

**Comment by SMed79** [comment]
uBo currently not block ads on `gum-gum-streaming.com`
Also i think `tuxboard.com`, `filmvf.ws` & `dpstream.net` stopped using goyavelab tricks.

**Comment by SMed79** [comment]
also find: `http://www.manga-news.com/`

**Comment by SMed79** [comment]
```
http://jeu.video/
http://jeu.video/agario/
```

**Comment by SMed79** [comment]
`http://www.generation-nt.com/`

**Comment by SMed79** [comment]
`http://forums.mangas-fr.com/`
Thanks.
