### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by noscripter** [gorhill/uBlock#1341]
url: <chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html?details=eyJ1cmwiOiJodHRwczovL2NsaWNrLnNpbWJhLnRhb2Jhby5jb20vY2NfaW0/cHJlcHZpZD0zMDBfMTAuMTc3Ljc3LjE3Nl8zNDA3MjVfMTQ1NDU2NzU4ODQ3MyZleHRyYT0mcD0lQ0UlRTUlQjUlREIlQzclQUUmcz03NTk0ODU3MDUmaz0zNzcmY2xrMT1hYjA0NjI1YzM3MjE3MmM5NzFjNTE3MmIzNDAyMGMzYyZlPVolMkJEZHMlMkJ3ZTBWdUVqOHBnZFQzbzVlZkdhYmxTRm5kWVIyT2klMkZkdCUyRlUyZ3ZITTlURnNDYVcxJTJGZGtVVnNtaUlXTnJkR1RHblNSS3JQNDElMkJWVUs3dHQweVpZZGo3Um5ZSlpvJTJCS3VMTyUyQmloNERicGF2SE0xNHdlVTYyN0lRZSUyRjRQdWJoRWxWVVBwRHRFJTJGVzR4MWZWYnBmUWRnREdDUkJyMyUyQlgxdTB0SFJJZjJHeXhmTTc1JTJCSTJtZ1cxRWFZMk9aNlVkSjlhQ0d4akhGWmFGd3dmSmxtRkNzQUxEcSUyRiUyQmx2WTY5RmoyUXJneExtUmVlTEVHdlJ3b3FwM1ZJbiUyQjExejhhUFpYa2l1ZTluQkltbm5zRk9Lb25iWUZuNzlPeUF0aHZleklwWWlkZXVVQzRuOXpMYzc2V2FaODVMc0pSNVBpRmlRTGFHVTZXaWphOGl2JTJGNGlVV1V3MTEya0g4a29NcDJJdVA0TVclMkZMdHJRbjElMkJpcUlZTTdBJTNEJTNEJmNsazE9YWIwNDYyNWMzNzIxNzJjOTcxYzUxNzJiMzQwMjBjM2MiLCJobiI6ImNsaWNrLnNpbWJhLnRhb2Jhby5jb20iLCJkbiI6InRhb2Jhby5jb20iLCJmYyI6IjBcdTAwMGIuXHUwMDBiY2xpY2suc2ltYmEudGFvYmFvLmNvbSIsImZzIjoifHxjbGljay5zaW1iYS50YW9iYW8uY29tXiJ9>

error message: `Uncaught URIError: URI malformed`

cause of error with param's value equal to: `"p=%CE%E5%B5%DB%C7%AE`

**Comment by noscripter** [comment]
update: 

rawURL: `https://click.simba.taobao.com/cc_im?prepvid=300_10.177.77.176_340725_1454567588473&extra=&p=%CE%E5%B5%DB%C7%AE&s=759485705&k=345&clk1=ab04625c372172c971c5172b34020c3c&e=aRmcsykOKkWEj8pgdT3o5efGablSFndYR2Oi%2Fdt%2FU2gvHM9TFsCaW1%2FdkUVsmiIWNrdGTGnSRKqQ%2BERWiUb04mtIw6FeZlYRLjmpUbwt2EMDbpavHM14weU627IQe%2F4PubhElVUPpDtE%2FW4x1fVbpfQdgDGCRBr3%2BX1u0tHRIf2GyxfM75%2BI2mgW1EaY2OZ6V7HgClnbNj7Wjxs%2F0M%2FBXaOgYCS9%2FFAZFSPZI8%2FYC4NPuimPmkZDQNCwCiObaC6JlPfWXLD5ZQLJZ6wUnZ%2FO%2B0VUPLs%2FEQ0JDaOuMo%2B5S%2B34if03MHZcYUMjDy90FPWMvXTOuumnAXzpBSzyye8Hsg%3D%3D&clk1=ab04625c372172c971c5172b34020c3c`

**Comment by noscripter** [comment]
proposed pr:<https://github.com/gorhill/uBlock/pull/1342>

**Comment by gorhill** [comment]
That's not how it works: I need a reproducible test case. (see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md))

**Comment by gorhill** [comment]
If I type the following in the console:

    var uri = new window.URL('https://click.simba.taobao.com/cc_im?prepvid=300_10.177.77.176_340725_1454567588473&extra=&p=%CE%E5%B5%DB%C7%AE&s=759485705&k=345&clk1=ab04625c372172c971c5172b34020c3c&e=aRmcsykOKkWEj8pgdT3o5efGablSFndYR2Oi%2Fdt%2FU2gvHM9TFsCaW1%2FdkUVsmiIWNrdGTGnSRKqQ%2BERWiUb04mtIw6FeZlYRLjmpUbwt2EMDbpavHM14weU627IQe%2F4PubhElVUPpDtE%2FW4x1fVbpfQdgDGCRBr3%2BX1u0tHRIf2GyxfM75%2BI2mgW1EaY2OZ6V7HgClnbNj7Wjxs%2F0M%2FBXaOgYCS9%2FFAZFSPZI8%2FYC4NPuimPmkZDQNCwCiObaC6JlPfWXLD5ZQLJZ6wUnZ%2FO%2B0VUPLs%2FEQ0JDaOuMo%2B5S%2B34if03MHZcYUMjDy90FPWMvXTOuumnAXzpBSzyye8Hsg%3D%3D&clk1=ab04625c372172c971c5172b34020c3c');

There is no exception thrown. I need a repro case, and once I can repro I will come out with the fix if any is needed.

**Comment by gorhill** [comment]
Ok sorry, merely pasting the URL in the address bar I could reproduce.

**Comment by fff99** [comment]
hi no te olvides del ie browser and edge browser
