### ISSUE TITLE
ftp block

### ISSUE THREAD

**Issue by andoommi** [gorhill/uBlock#1343]
I am using the JonDoFox version of firefox and have switched from ABP that is included in their bundle to uBlock Origin. When I copy the custom rules over, the following rule is not working.

|ftp://$other,script,image,stylesheet,object,subdocument,xmlhttprequest,object-subrequest,font,media,popup

Any suggestions?

**Comment by lewisje** [comment]
uBlock Origin works only on the `http:` and `https:` schemes, not `ftp:`

**Comment by gorhill** [comment]
Closing as this issue is missing an actual case for why `ftp:` should be supported.
