### ISSUE TITLE
issue on NBCNEWS.com

### ISSUE THREAD

**Issue by ZongMan** [gorhill/uBlock#1344]
http://www.nbcnews.com/tech/internet   from here i click the first article here V 
http://www.nbcnews.com/tech/social-media/twitter-remembers-simpler-times-beforefacebooki-hashtag-n511556
it loads for a second then disappears Ive let the page load with some and with all domains and still nothing , even disabled some 3rd party lists and bupkis 
Not very familiar with JS or the uBlock syntax , point me to a good learning source for ublock that would help big time

**Comment by gwarser** [comment]
Static filter `##.social-media` found in:
    [Fanboy’s Annoyance List](https://forums.lanik.us/)

block `body` element.

**Comment by ZongMan** [comment]
This worked `##.social-media` heheh thanks though, also i temp allowed twitter in NoScript

**Comment by gorhill** [comment]
One potential quick solution when this happens is to [toggle off cosmetic filtering for the site](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering).
