### ISSUE TITLE
uBlock detected in sportdeutschland.tv / sportdeutschland.vidibuscloud.net

### ISSUE THREAD

**Issue by towlie** [gorhill/uBlock#1346]
Example: http://sportdeutschland.tv/vbl/tv-beitrag-vilsbiburg-vs-koepenick
If the video starts they mute the sound of the video and add an overlay.

It looks like they are doing this with their video player script from http://sportdeutschland.vidibuscloud.net/themes/sportdeutschland-623/javascripts/all.js
So blocking this script will break everything.

Better readable version of the script (including the line of the block notice): 
https://gist.github.com/towlie/868aab43c4d9aec31b52#file-deob_all-js-L14326

**Comment by gorhill** [comment]
Same issue with ABP, Adguard, thus filter list issue.
