### ISSUE TITLE
Popunders to block on Spankwire Sites

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1347]
Please add these to assets/ublock/filters.txt to block popunders from these sites.

! Spankwire Sites
||extremetube.com^$popunder
||keezmovies.com^$popunder
||mofosex.com^$popunder
||spankwire.com^$popunder

**Comment by gorhill** [comment]
See https://github.com/gorhill/uBlock/issues/1209#issuecomment-170648254

**Comment by flyingzebras** [comment]
@gorhill I'm willing to maintain ublock filters for the PornHub Network (PHN) and Spankwire Sites. Can you please give me permission?

**Comment by IDKwhattoputhere** [comment]
@flyingzebras If you added the filters from above than those pages could not be opened in a new tab without the origin tab being closed.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Is there any way to circumvent that?

**Comment by IDKwhattoputhere** [comment]
@flyingzebras Use a filter that targets the advertising server instead.
`||traffichunt.com^$document,popunder,popup`

**Comment by gorhill** [comment]
> Can you please give me permission?

No, I prefer this filter list to be independent, not part of this project. Just make its purpose clear, then I will add it to the list of filter lists on the wiki page.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Great filter but the source tab is still closed, I cannot go back.

**Comment by flyingzebras** [comment]
@gorhill Ok.

**Comment by IDKwhattoputhere** [comment]
@flyingzebras The source tab is only closed if it loads the popunder. Also see https://github.com/gorhill/uBlock/issues/1028

**Comment by flyingzebras** [comment]
@gorhill ```||traffichunt.com^$document,popunder,popup``` is a major blocking filter that will block popunders on many sites. I suggest that you add it to uBlock filters anyway.

**Comment by flyingzebras** [comment]
@gorhill Thank you very much!

**Comment by flyingzebras** [comment]
@gorhill Please have patient. I'm listing every popunder domains right now. Here's another good filter: ```||slopeaota.com^$document,popunder,popup``` will block gaytube.com, pornhub.com, redtube.*, youporn.com, youporngay.com.
