### ISSUE TITLE
Anti WebRTC Ip Leak does not work

### ISSUE THREAD

**Issue by PekaFat** [gorhill/uBlock#1348]
Hello, i test my browser here https://2ip.ru/privacy/ and it's detect my real ip behind proxy, even with uBlock (1.5.6) funtion "Anti WebRTC" enabled. It's on Chrome 48.0.2564.103.
![default](https://cloud.githubusercontent.com/assets/13280748/12870945/e80ca4de-cd6e-11e5-8f06-a0e2299aa920.png)

**Comment by gorhill** [comment]
Did you read the [caveats](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address#caveats)? Does it apply to you?

In any case, if you disable the leaking of local addresses and these local addresses leak, this is a browser bug, you will have to report to open a [Chromium issue](https://code.google.com/p/chromium/issues/list) (and provide them with more information then there is here), uBO is merely turning on the switch in the browser which disable local IP addresses leakage.

**Comment by PekaFat** [comment]
Ohh, yes, i use ZenMate :/
