### ISSUE TITLE
Firefox and yt-Link with timestamp doesnt play

### ISSUE THREAD

**Issue by Maradonna90** [gorhill/uBlock#1350]
So if I click on a link of a yt-video with a timestamp it wont start playing. Player just stays black with the control panel at the bottom. Works if I turn uBlock off.

OS: Windows 7
Browser: Firefox 43.0.4 and 44.0
uBlock: 1.5.5

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
