### ISSUE TITLE
Subscribe to External filter by "subscribe" link not work ever.

### ISSUE THREAD

**Issue by mboveiri** [gorhill/uBlock#1351]
hi.
a sample you provide to put subscribe link to any markdown was not work ever : [Here ](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web)
i put it to my readme.md, and it's not work and it's show my list content. and open my.txt list.
please explain : how to put subscribe links on markdowns to ublock identify the list.

my [README.MD](https://github.com/mboveiri/Iran-uBlocklist/blob/master/REDME2.MD)

thanks for your efforts.

**Comment by thegoodthings** [comment]
That format is only for that specific "Filter lists from around the web" wiki page.  

For any other page, you'll need to use the format like below:
`abp:subscribe?location=https://easylist-downloads.adblockplus.org/easylist.txt&title=EasyList`

**Comment by gorhill** [comment]
> That format is only for that specific "Filter lists from around the web" wiki page.

This is the answer, thanks.
