### ISSUE TITLE
Add "I don't care about cookies" list

### ISSUE THREAD

**Issue by poutros** [gorhill/uBlock#1352]
Just like prebake, which is already included in ublock origin, "i don't care about cookies" also removes cookie warnings. It supports more websites than prebake.

Website:
http://www.kiboke-studio.hr/i-dont-care-about-cookies/
List:
http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/search?q=i+dont+care+about+cookies&type=Issues&utf8=%E2%9C%93

**Comment by poutros** [comment]
I guess I can close this issue then, right?

**Comment by gorhill** [comment]
Duplicate of #909.
