### ISSUE TITLE
elemhide whitelist being ignored

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1355]
uBlock Origin hides ads even when an exception is found.

How to reproduce:
1. Add the following rules (found [here](https://easylist-downloads.adblockplus.org/exceptionrules.txt)):
`@@||duckduckgo.com/?q=$elemhide`
`@@||duckduckgo.com^*^q=$elemhide`
2. Go to https://duckduckgo.com/?q=travel
Observe that the ads are still being hidden.

[Logger](https://cloud.githubusercontent.com/assets/16030872/12889019/33a84128-ce7d-11e5-8c1e-8ec49f50d38d.png)

uBlock Origin 1.5.6 / 1.6.0rc1 with standard configuration
Chrome 48 / Chromium 50

**Comment by gorhill** [comment]
By design, I implemented `elemhide` to disable only generic cosmetic filters. Use the cosmetic filtering switch if you want to disable completely cosmetic filtering for `duckduckgo.com`,
