### ISSUE TITLE
Feature request: support for XUL/Firefox-based browser Conkeror

### ISSUE THREAD

**Issue by Jehops** [gorhill/uBlock#1356]
Ublock mostly works in Conkeror [1], but some ads seems to pass through that don't make it through in Firefox (e.g. the ads on http://ads-blocker.com/testing/).

[1] http://conkeror.org/uBlock

**Comment by Jehops** [comment]
The above testing was with 1.6.0rc1.  Those ads are blocked in 1.5.7.  It was also pointed out that a similar issue was submitted before the change in GitHub profiles. https://github.com/chrisaljoudi/uBlock/issues/827

**Comment by spwhitton** [comment]
I can confirm this for version 1.6.2, too.

**Comment by gorhill** [comment]
[InstallationDebian](http://conkeror.org/InstallationDebian):

    [...] $ sudo apt-get install conkeror conkeror-spawn-process-helper
    [sudo] password for [...]: 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package conkeror
    E: Unable to locate package conkeror-spawn-process-helper

So I will have to let someone else investigate where is the issue.

**Comment by spwhitton** [comment]
@gorhill What version of Debian are you using?  I installed Conkeror on Debian Stretch this morning just fine.

**Comment by gorhill** [comment]
Linux Mint -- I would have thought this gives me access to all Debian packages. I have a bootable USB with Debian as a GRUB option, I will investigate when I have time.

**Comment by scottjad** [comment]
Just trying out conkeror is very easy:
git clone http://repo.or.cz/conkeror.git
path/to/firefox -app conkeror/application.ini

Then to install uBlock:

M-x extensions (M-x is alt+x)
Click "Gear" button
"Install Add-on from File"
select ublock origin xpi

If that doesn't work try evaluating these lines with M-: and retry installing ublock:

user_pref("extensions.checkCompatibility", false);
user_pref("xpinstall.whitelist.required", false);
user_pref("xpinstall.signatures.required", false);

Note there is an issue with addons activating on startup in ff44, either use ff43 or 45, or manually disable and then enable the extension from M-x extensions on startup.

**Comment by caadar** [comment]
Is it possible to use element picker mode in Conceror?

It seems accessible only by uBlock icon, not displayed in Conkeror interface.

Showstopper for me.
