### ISSUE TITLE
Blocking PornHub Network and Spankwire Sites for good

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1357]
There would be no need to maintain a long list of third-party if we could use a "global" filter for these sites:

*$third-party,domain=extremetube.com|gaytube.com|keezmovies.com|mofosex.com|peeperz.com|pornhub.com|porniq.com|pornmd.com|redtube.com|redtube.com.br|spankwire.com|thumbzilla.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com
*$third-party,important,document,popunder,popup,domain=extremetube.com|gaytube.com|keezmovies.com|mofosex.com|peeperz.com|pornhub.com|porniq.com|pornmd.com|redtube.com|redtube.com.br|spankwire.com|thumbzilla.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com
@@||phncdn.com
@@||rncdn3.com
@@||redtubefiles.com
@@||images-gaytube.com

These filters works as they supposed to do when filters subscriptions are turned off. The problem is that I do not know how to let these settings override EasyList and the other filters when they are turned back on. I've tried this without success (test to block everything else but phncdn.com on pornhub.com):

@@*$~third-party,important,domain=pornhub.com

and

*,~phncdn.com$third-party,important,domain=pornhub.com

and

*$third-party,important,domain=pornhub.com
@@phncdn.com$important

and

||pornhub.com^$third-party,important
@@phncdn.com$important

@gorhill How can this be solved?

**Comment by Betsy25** [comment]
Find a girlfriend & dump porn.

**Comment by IDKwhattoputhere** [comment]
You are aware that your rules wouldn't block the popunders?

@Betsy25 Get out. :>

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by flyingzebras** [comment]
@IDKwhattoputhere The second line with filter do that. The later filters are just used for evaluation so I'd know how to implement it.

@gorhill Invalid for what?

I can block the PHN+SS in a browser that I dedicate to these sites.

**Comment by IDKwhattoputhere** [comment]
It's not possible to include a filter like that. See https://github.com/gorhill/uBlock/issues/1322.

**Comment by gorhill** [comment]
`*,~phncdn.com$third-party,important,domain=pornhub.com` is not a valid filter. Read carefully about ABP filter syntax.

**Comment by flyingzebras** [comment]
@gorhill I'm trying to. The first filter seem to be valid: ```*$third-party,important,domain=pornhub.com```.

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1063#issuecomment-164357252

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1063

**Comment by flyingzebras** [comment]
@gorhill These filters are not overridden by EasyList etc in Firefox 38.6.0 on Windows 7. Interestingly they are overridden in IceCat 38.6.0 tested from Trisquel GNU/Linux 7:

*$third-party,domain=extremetube.com|gaytube.com|keezmovies.com|mofosex.com|peeperz.com|pornhub.com|porniq.com|pornmd.com|redtube.com|redtube.com.br|spankwire.com|thumbzilla.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com
*$third-party,important,document,popunder,popup,domain=extremetube.com|gaytube.com|keezmovies.com|mofosex.com|peeperz.com|pornhub.com|porniq.com|pornmd.com|redtube.com|redtube.com.br|spankwire.com|thumbzilla.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com
@@||phncdn.com
@@||rncdn3.com
@@||redtubefiles.com
@@||images-gaytube.com

This should be investigated.

**Comment by flyingzebras** [comment]
@gorhill I removed the noop issue in this post for now. Can you please have a look on [this](https://github.com/gorhill/uBlock/issues/1357#issuecomment-182177249) now?

**Comment by flyingzebras** [comment]
@gorhill Can you please expand `||traffichunt.com^$document,popunder,popup` to ```||traffichunt.com^$document,popunder,popup
||trhnt.com^$document,popunder,popup
||trhunt.com^$document,popunder,popup```

They are used radomly on Spankwire Sites (SS).

**Comment by gorhill** [comment]
I did not use the `popunder` option, uBO 1.6.4 should be able to foil popunders as well with those filters, if you can confirm please.

**Comment by flyingzebras** [comment]
@gorhill Thanks, but why do you use `popunder` for traffichunt then?

**Comment by gorhill** [comment]
Because this one was added before 1.6.4. I will remove the `popunder` where unneeded after 1.6.4 is out.

**Comment by flyingzebras** [comment]
@gorhill Ok great.

What about https://github.com/gorhill/uBlock/issues/1389?

**Comment by gorhill** [comment]
> What about #1389?

#1389 is one out of currently 100 open issues.

**Comment by flyingzebras** [comment]
@gorhill Sorry, I didn't mean to push you. Can you please let me know when I can ask about it again (1 month, or 6 months, for example)?

**Comment by gorhill** [comment]
You don't need to ask me ever again, when it's fixed the issue will be closed and GitHub will notify you.

**Comment by flyingzebras** [comment]
Noted.

**Comment by flyingzebras** [comment]
https://github.com/uBlockOrigin/uAssets/issues/82
