### ISSUE TITLE
ublock is not allowing http://economictimes.indiatimes.com  to load if enabled

### ISSUE THREAD

**Issue by neo269** [gorhill/uBlock#1358]
ublock is not allowing http://economictimes.indiatimes.com  to load if enabled

**Comment by harshanvn** [comment]
If Firefox, adding below filter fixes the issue..
`indiatimes.com##script:contains(opacity)`

**Comment by gorhill** [comment]
Same issue with ABP, Adguard, thus it's a filter list issue.

**Comment by harshanvn** [comment]
As far as i see allowing some domains to bypass the site restrictions is not a good thing as you usually say.

So, i think this site is a good candidate for inline tag filtering..

**Comment by gorhill** [comment]
I want the issue tracker to be reserved for issues in the code, not issues with filters. The trend is that if I care to provide just one assistance with filter issues, then people see it as a signal for pile on more filter issues.

The solution is simple: someone step up to create a separate project to maintain a list of filters specific to uBO. As often said, I just do not have the time.

**Comment by harshanvn** [comment]
Ok Thanks. Understood.

**Comment by IDKwhattoputhere** [comment]
@gorhill I would like to know what would have to be managed by the person(s) which maintains the filters. Obviously popunder filters but what else? Everything in `uBlock filters`? `Unbreak` too? Anything else? Some information on that would be helpful.

**Comment by gorhill** [comment]
If someone decide to become a filter list maintainer, they do whatever they want, just like any of the 3rd-party filter list used by uBO. I will probably contribute but that won't be my project. If it becomes good enough I will probably include it in uBO's selection of filter lists.
