### ISSUE TITLE
UI blocked at map.krak.dk

### ISSUE THREAD

**Issue by Thue** [gorhill/uBlock#1360]
On http://map.krak.dk/ , ublock origin removes the non-ad interface such as the search field.
![krak_with_ublock](https://cloud.githubusercontent.com/assets/519347/12916813/7d6537ae-cf35-11e5-8350-e28f91a3849e.png)
![krak_without_ublock](https://cloud.githubusercontent.com/assets/519347/12916812/7d5267e6-cf35-11e5-9269-907f22e9596a.png)

**Comment by IDKwhattoputhere** [comment]
Not a uBlock Origin issue. A third-party filter list issue (EasyPrivacy).
Submit here: https://forums.lanik.us
First read this: https://forums.lanik.us/rules
Temporary workaround: `@@||map.krak.dk*/xgemius.js$first-party`

**Comment by Thue** [comment]
Thanks - done!

**Comment by IDKwhattoputhere** [comment]
No problem. Just as a tip: You can usually get a lot of information with [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) in those situations. For example right now I saw two blocked scripts, tried unblocking the one from map.krak.dk and it fixed it.
