### ISSUE TITLE
https://userscloud.com/yxnl6knoan2j - annoying clickunder

### ISSUE THREAD

**Issue by Alex1188** [gorhill/uBlock#1361]
Reproduce: click anywhere
Chrome 48, uBlock Origin 1.5.6
Filters:
 uBlock filters‎ 
 uBlock filters – Badware risks‎
 uBlock filters – Block-then-redirect‎
 uBlock filters – Experimental‎
 uBlock filters – Privacy‎
 uBlock filters – Unbreak‎
EasyList

I see in the Session Storage - admaven_pop_600304_ts

**Comment by Betsy25** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Correct, it's not a uBlock issue. It's third-party filter list issue.
You need to submit those here: https://forums.lanik.us
In accordance with this: https://forums.lanik.us/rules
I did it for you this time: https://forums.lanik.us/viewtopic.php?f=62&t=28492
