### ISSUE TITLE
[Firefox] whitelist about:addons

### ISSUE THREAD

**Issue by bhabba** [gorhill/uBlock#1362]
I hope this didn't already come up earlier (I briefly searched through closed issues but didn't make a find).

I think the Firefox page ``about:addons`` should be whitelisted by default. If not whitelisted and [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) is enabled _Get Add-ons_ is missing it's "startpage" (due to blocked iframes).

Additionally if [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode) is enabled many icons are missing (under _Get Add-ons_, _Extensions_, _Appearance_, _Languages_, ...) (due to blocked 3p content).

The missing content seems always being pulled from ``mozilla.net`` (see logger screen below) so I think whitelisting this page shouldn't be a privacy concern (correct me if I'm wrong).

![logger about:addons](https://i.imgur.com/sXotYok.jpg)

**Comment by gorhill** [comment]
`About` pages are all whitelisted by default -- you must have removed `about-scheme` from the whitelist directives.

**Comment by bhabba** [comment]
Oops, didn't notice I did. Sorry for bothering and thanks for the hint!
