### ISSUE TITLE
Netzwelt.de banner not hidden

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1366]
Banner ads on netzwelt.de are not hidden.

How to reproduce:
1. Subscribe to EasyList Germany
2. Go to http://www.netzwelt.de/news/74353-super-soaker-championship-jugendfreier-online-shooter-kostenlos.html
3. "Sky" banner ad is not hidden. Might need to wait a few seconds or reload. Maybe delete cache and cookies.

[Screenshot](https://cloud.githubusercontent.com/assets/16030872/12969859/e804642a-d086-11e5-86b8-e8772712ef8f.png)
[Logger](https://cloud.githubusercontent.com/assets/16030872/12970004/35484e02-d089-11e5-9fa1-2c656a9686a8.png)

Tried with uBO 1.5.6 in Chrome 48 and with uBO 1.6.0 in Firefox 38.6.0  (fresh profile). Seems to be an issue with uBO since it works with ABP 2.7.1 in Firefox with the same [filter lists](https://reports.adblockplus.org/9bb8da60-69a2-4418-ac9e-0b272bb51830#tab=subscriptions) way more reliably (rare exceptions like [here](https://forums.lanik.us/viewtopic.php?p=86707#p86707)).

**Comment by zummuz** [comment]
see entry №7
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit
https://forums.lanik.us/viewtopic.php?f=90&t=27698

**Comment by gorhill** [comment]
It does not work with Chromium/ABP 1.10.1.

**Comment by gorhill** [comment]
Just a filter list issue: `||img.netzwelt.de/picture/*/sky-*-*.*`.

I use the [feature shown here](https://www.youtube.com/watch?v=kO0Mh-SAkHM) to create that filter + a bit of editing.

**Comment by IDKwhattoputhere** [comment]
@zummuz I even linked that thread.

@gorhill You are right, it doesn't work in with uBO or ABP in Chromium. However it works with ABP in Firefox but not with uBO.

**Comment by gorhill** [comment]
> Therefore it must be a uBO issue, right?

uBO works differently than ABP. uBO works the same on any browser. Chromium-ABP works differently than FF-ABP. ABP uses user stylesheet on FF, which override all CSS rules on a page, something not possible on Chromium.

I don't know why the banner does not appear on FF-ABP, as I did not spot any specific CSS rules for that banner -- I would need to investigate more.

In any case, here is a filter which will take care of the banner, and will work better for ABP too, as it removes the placeholder on FF:

    www.netzwelt.de###mhc + div[id][class]

It should be proposed for inclusion in EasyList.

**Comment by IDKwhattoputhere** [comment]
Thanks. However the background still gets clickable and dark but I submitted it to EasyList: https://forums.lanik.us/viewtopic.php?p=86736#p86736

**Comment by gorhill** [comment]
> the background still gets clickable

    netzwelt.de###mr
    netzwelt.de###ml
    netzwelt.de###mhc + div[id][class]
