### ISSUE TITLE
can I install the finalized version 1.6.0 ?

### ISSUE THREAD

**Issue by laozi83** [gorhill/uBlock#1367]
Hello
I very regularly consults these pages and I am pleased that new versions are available 1.5.6, 1.5.7 1.6.0 (https://github.com/gorhill/uBlock/releases) but on the Mozilla Add-ons page only the version 1.5.5 is referenced!
question: can I install the finalized versions? I speak not the rc versions
Thanks for your lighting

**Comment by sidz** [comment]
If you want to install new version right now - download it from released page.
You 1.5.6 and 1.5.7 contain fixes only for Opera and Chromium, that is why you can't install from Mozilla Addons Page.

I think new version of the uBlock on the pre moderation and we need to wait some time

**Comment by laozi83** [comment]
un grand merci pour ces précisions
Thank you for these details
well cordially
