### ISSUE TITLE
https://addons.mozilla.org/de/firefox/addon/ublock-origin/

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#1368]
hi, 
Question, when is the final version from uBo available @ 
https://addons.mozilla.org/de/firefox/addon/ublock-origin/  
??

greetings

**Comment by IDKwhattoputhere** [comment]
Mozilla and Google scan the extensions before they get released. That's why you have to wait.
See also https://github.com/gorhill/uBlock/issues/1367

**Comment by akks1981** [comment]
ok thx

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
