### ISSUE TITLE
sc2links.com detection

### ISSUE THREAD

**Issue by electic** [gorhill/uBlock#1369]
Version 1.5.6. Sc2links.com appears to detect adblock and redirect.

**Comment by IDKwhattoputhere** [comment]
`@@||sc2links.com/js/adsbygoogle.js$script,first-party` into "My Filters"

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
