### ISSUE TITLE
doubleclick

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1370]
are we able to do a neutured version of this. i see it like everywhere. all it is a 2 line script, it should be easy enough to do one right? unhide your elements on this page to see the line below

http://pubads.g.doubleclick.net/crossdomain.xml

located here: 

http://insider.foxnews.com/2016/02/11/jesse-watters-gets-reaction-new-hampshire-primary-donald-trump-bernie-sanders

click play on the video to see the script

**Comment by jo2dan23** [comment]
we cant make it generic tho it has to be specific because http://googleads.g.doubleclick.net/crossdomain.xml is a whole different script. so we would have to do:

||pubads.g.doubleclick.net/crossdomain.xml$object-subrequest,redirect=pubads.g.doubleclick.net/crossdomain.xml,important

**Comment by jo2dan23** [comment]
https://www.washingtonpost.com/news/the-intersect/wp/2015/11/23/the-secret-american-origins-of-telegram-the-encrypted-messaging-app-favored-by-the-islamic-state/

another site it is located on. loads after clicking play on video

**Comment by gorhill** [comment]
Nowhere do I see a network request to `doubleclick.com` on these pages, and videos play fine.

**Comment by gorhill** [comment]
Never mind, I see Flash plugin needs to be enabled.

**Comment by gorhill** [comment]
After looking into content of <pubads.g.doubleclick.net/crossdomain.xml>, I rather not redirect it:
- That would not be about neutering the content.
- The content could change in a way that makes redirection detrimental to users (what if they narrow the permissions?)
