### ISSUE TITLE
Sourceforge - Badware risks

### ISSUE THREAD

**Issue by dmex** [gorhill/uBlock#1371]
Is it possible to review Sourceforge.net being listed under the "uBlock filters – Badware risks" considering the "DevShare" program that delivered installer bundles has been terminated?

https://sourceforge.net/blog/sourceforge-acquisition-and-future-plans/

**Comment by Eeems** [comment]
Related #937
I'm going to say this should be closed as per @gorhill's comment when this link was posted there.

> All the source material supporting that sourceforge.net is "badware risks" are independent of the site. So It's going to take independent source material to make the case that sourceforge.net is no longer "badware risks". The announcement you link to is not independent source material.

**Comment by dmex** [comment]
I think it's a really bad idea to reply upon ametuar anaysis from the media to make decisions.

You will also have issues finding "independent source material" considering the majority of sites these days are looking for the 'shock' value that bring website hits (which doesn't exist in the termination of the SF program) and even if they do mention anything it will likely just be the regurgitation of the Sourceforge press release.

I suggest re-reviewing the original "independent source material" and determining if this is still the case considering that material was the basis of the original decision?

**Comment by gorhill** [comment]
@Eeems pointed out the correct answer above.

**Comment by PlasmaPower** [comment]
To save some work for future visitors like me, this was done in 1524d93f2fb619183395411513bddd857c05f730 (commented on #937).
