### ISSUE TITLE
uBlock Origin 1.6.0 build broken on AMO?

### ISSUE THREAD

**Issue by EchoDev** [gorhill/uBlock#1373]
When trying to install uBo 1.6.0 I get the following message

"The addon could not be installed because it does not match the add-on Firefox expected."

Updating from within Firefox also seems to fail. Is this an issue on my end or do others have the same problem?

**Comment by DarkEra** [comment]
1.6.0 indeed doesn't seem to update on Firefox 44.0.1 nor can it be installed after removing the previous version of µblock origin. Had to switch back to AdBlock Plus for now because of this issue.

**Comment by EchoDev** [comment]
@DarkEra You can install version 1.5.5 from here: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/1.5.5

**Comment by DarkEra** [comment]
@EchoDev Thanks, it's appreciated. Didn't know about that.

**Comment by gorhill** [comment]
I can install fine when I try. I don't know why this would happen.

**Comment by gorhill** [comment]
Looks like the issue is also suffered elsewhere:

- https://discourse.mozilla-community.org/t/webapp-tabs-for-thunderbird-install-issue/6292/2
- https://github.com/mozilla/addons-server/issues/1111

**Comment by gorhill** [comment]
Could this be caused by your anti-virus (assuming you have one)?

**Comment by EchoDev** [comment]
Disabled AV, no change. Same error. Might be just something on Mozilla's end.

**Comment by DarkEra** [comment]
Running a Linux distro here without a anti-virus

**Comment by IDKwhattoputhere** [comment]
I'm using the ESR version of Firefox and it updated just fine. Don't know if that helps in any way.

**Comment by raesene** [comment]
Just to provide another data point. I'm seeing the same issue.  Setup is Windows 10 / FF44.0.2 / no 3rd party A-V (just windows defender).  From the addons page above I can install 1.6.0 rc2 ok but 1.6.0 has the error described

**Comment by gorhill** [comment]
If you instead download the XPI file first (right-click, save as), then drag-n-drop the file into Firefox, does it work?

**Comment by Radagast** [comment]
No issues here: linux/fx 44 and 46

**Comment by JohnDDuncanIII** [comment]
Works fine for me using SeaMonkey 2.39 (Firefox/42.0) using the built in updater

**Comment by EchoDev** [comment]
@gorhill When I do that it says "This addon could not be installed because it appears to be corrupt"

**Comment by Kilissue** [comment]
I haven't been able to update since version 1.5.5, i am using Palemoon (26.0.3), NewMoon (25.4.0b3 (x64)) and FF 44.0.2, when i try to update on either of them i get  "There was an error downloading uBlock Origin, try again"

**Comment by raesene** [comment]
@gorhill So the drag-drop into Firefox method worked for me ok.  I also tried a couple of other setups (Firefox 44.0 and 44.01 on Xubuntu) and they both work fine with the standard extension installation method (get add-ons-->search for ublock-->click install).  So for me the problem now appears to be confined to Windows and installing via that standard mechanism. One other thing I noticed that using the addons page and clicking "Add to firefox" now works ok for me on windows, which it didn't yesterday (although somewhat potentially contaminated target now as I've installed/un-installed several times...)

**Comment by gorhill** [comment]
Reportedly some users had same sort of issue with NoScript. [Giorgio Maone commented in the thread](https://forums.informaction.com/viewtopic.php?f=7&t=21609#p81104):

> It's working for me, but then AMO devs where busy upgrading their infrastructure yesterday, so maybe a temporary glitch.

This could explain the issue here.

**Comment by xpris** [comment]
Can't install uBlock Origin 1.6.0 on Firefox 44 in Android 4.4 because "The addon could not be installed because it does not match the add-on Firefox expected."

Origin in 1.5 version works fine.

Also I use desktop Linux - Ubuntu 15.10 with Firefox 44.0.2 from Canonical repo and uBlock Origin 1.6.0 working fine from some time.

**Comment by heubergen** [comment]
I freshly installed firefox_stable 44.0.2 with a new profile and don't change any settings or click anything.
Then I tried to install uBlock Origin 1.6.0 over AMO and it works perfectly.

My System: Win7 Pro x86

So I think it was a temporary issue or a profile problem. For sure no issue with this addon.

**Comment by EchoDev** [comment]
I manually downloaded the xpi file, tried to unpack it but winrar gave me an error (C:\ublock_origin-1.6.0-fx+an+sm+tb2.zip: The archive is corrupt )
Anyone else having this problem?
I can unpack the xpi hosted on github without issues.

MD5 for AMO xpi 3F06B29615D9224605EDE80E78B5886C
MD5 for Github xpi DBA426C912B0AE55F170EF8D0CFBC385

Does Mozilla repack the submitted files?

**Comment by gorhill** [comment]
> Does Mozilla repack the submitted files?

Yes, they add a `META-INF` folder with the signature data in it. That should be the only difference.

**Comment by EchoDev** [comment]
gorhill can you check the MD5 on the AMO xpi? And can you try unpacking it?

**Comment by heubergen** [comment]
I get the follow MD5 hash for the AMO xpi v1.6.0:
filename: ublock_origin-1.6.0-fx+an+sm+tb.xpi
`a378015bd8137fbee0a786e64a4a9b52`

**Comment by EchoDev** [comment]
So it seems AMO is serving different xpi files. That explains why some people are getting errors and some don't.

**Comment by heubergen** [comment]
@EchoDev Did you rename your xpi file to zip?
Also why is there a '2' in the filename?
ublock_origin-1.6.0-fx+an+sm+tb2.zip

The direct download link I use is:
https://addons.mozilla.org/firefox/downloads/file/398047/ublock_origin-1.6.0-fx+an+sm+tb.xpi
If i add there a 2 after 'tb', the server will redirect me to the link above and download it correctly.

**Comment by EchoDev** [comment]
I downloaded multiple xpi files through VPNs, I was hoping maybe AMO would redirect me to another server. I redownloaded the 1.6.0 xpi file to be sure and the MD5 my file has is still 3F06B29615D9224605EDE80E78B5886C

**Comment by heubergen** [comment]
@EchoDev Did you try it with my direct download link?
If not, can you share you're download link?

It can not be that mozilla share two different files for the exact same version of a addon.

**Comment by EchoDev** [comment]
@heubergen I tried the download through your link. Same result. (I did right click on the install button, gives the same file for me)
![022535](https://cloud.githubusercontent.com/assets/3149302/13055533/23c3f0de-d410-11e5-82c3-e89b3f8d1283.png)

**Comment by heubergen** [comment]
Okay that's strange.

Will you try "my" version so you can finally use uBlock Origin? Or don't you need it?

**Comment by EchoDev** [comment]
uBo 1.6.1 already is submitted to AMO but not approved yet, It should be up in a few days I guess. I will wait for it, no hurry.

**Comment by EchoDev** [comment]
More people who have the same issue:

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/779822/
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/779769/
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/779684/

**Comment by heubergen** [comment]
With 1.6.1 (https://addons.mozilla.org/firefox/downloads/file/399765/ublock_origin-1.6.1-fx+an+sm+tb.xpi) I get the follow MD5:
`62452b979baec2bd877571a855d69cb7`

**Comment by EchoDev** [comment]
@heubergen same for me
![1a161e](https://cloud.githubusercontent.com/assets/3149302/13055695/096a1352-d411-11e5-9d22-ed7c9e87d228.png)

**Comment by heubergen** [comment]
That's great, hopefully then will this strange issue be fixed :)

**Comment by EchoDev** [comment]
Version 1.6.1 just got approved thanks to jorgev from Mozilla IRC. It updated fine for me.

**Comment by DarkEra** [comment]
Update to 1.6.1 worked as should. Thanks a lot @gorhill and keep up the great job.

**Comment by gorhill** [comment]
It seems this was probably a glitch on one of the AMO servers, hosting an unsigned version of the extension's package.

**Comment by FTno** [comment]
I see this issue has been closed now, but I will just add some related and interesting information in case someone might find it useful.

I found this interesting information about updating addons on Firefox Android on this page: http://stackoverflow.com/questions/32615103/how-to-install-my-xpi-on-firefox-android

I tested this by creating an install.html modified for uBlock Origin:

<html><body>
    <a href="ublock_origin-1.6.1-fx+an+sm+tb.xpi">uBlock Origin</a>
    </body></html>

Updating this way worked fine for me on Firefox Android 44.0.2, but when I before that tried to update manually with file:///path/to/xpi it did not work.

**Comment by FTno** [comment]
A little correction (install.html):

`<html><body>
    <a href="ublock_origin-1.6.1-fx+an+sm+tb.xpi">uBlock Origin</a>
    </body></html>`

**Comment by gorhill** [comment]
_Maybe_ related bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1249402#c2

**Comment by gorhill** [comment]
I created a thread on Mozilla Discourse, if anybody wants to add details which may be helpful in identifying the issue: <https://discourse.mozilla-community.org/t/the-addon-could-not-be-installed-because-it-does-not-match-the-add-on-firefox-expected/7307>.

**Comment by krlk89** [comment]
Seems to be fixed! Thanks for the help!

**Comment by matachi** [comment]
@krlk89 I still experience this problem:

![img](http://i.imgur.com/lrQhZQr.png)

However, on AMO it says it only "[w]orks with Firefox for Android 24.0 - 42.*," which might explain it?

![screenshot from 2016-03-03 16-06-14](https://cloud.githubusercontent.com/assets/980838/13498543/bf967e76-e15a-11e5-9a44-878a8952b4ae.png)

**Comment by gorhill** [comment]
Please report to AMO people, there is nothing I can do on my side, I do not control the AMO servers which deliver uBO. uBO works fine on FF Android 44.
