### ISSUE TITLE
What does lines in the logger with "<<" mean

### ISSUE THREAD

**Issue by iamzam** [gorhill/uBlock#1374]
I see the following in the logger:
![screen shot 2016-02-12 at 21 25 31](https://cloud.githubusercontent.com/assets/787312/13025228/4b105e4e-d1d0-11e5-9bdc-c2604471511d.png)

What does the << line mean?  I can't find anything in the Wiki about it, and github doesn't allow the < character in searches.

**Comment by IDKwhattoputhere** [comment]
It symbolizes that the request has been redirected to a local uBO resource.

**Comment by gorhill** [comment]
The [logger documentation](https://github.com/gorhill/uBlock/wiki/The-logger) has been updated.
