### ISSUE TITLE
I cannot login on homebank.ro with uBlock Origin on Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [gorhill/uBlock#1375]
Hello,

I cannot login to homebank.ro with uBlock Origin enabled.

Firefox v44.0 and Firefox Nightly (47.0a1 (2016-02-12)) on Fedora23 I tested with both

[uBlock Orign](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) v1.6.0

The full URL it did not work on is [this](https://www.homebank.ro/public/HomeBankLogin/home?lang=ro)

Fill in "Cod" and "Cod utilizator", select "PAROLA" and click "LOGIN->". It does not work. I obviously cannot give you my credentials but I have a hunch that you don't need them. I can troubleshoot more and even can give logs, screenshots, HAL list of requests etc.

See screenshot 
![screen shot 2016-02-13 at 11 16 36](https://cloud.githubusercontent.com/assets/922368/13026939/d8e62d48-d243-11e5-9681-5e2036b3ebd7.png)

**Comment by gorhill** [comment]
Try this custom filter: `@@homebank.ro/public/HomeBankLogin/js/fingerprint/fingerprint.js$script`. If it fixes the issue, report the issue to [EasyPrivacy maintainers](https://forums.lanik.us/viewforum.php?f=64).

**Comment by andreicristianpetcu** [comment]
Cool! Your fix worked! I will report it to EasyPrivacy. Thank you @gorhill

**Comment by andreicristianpetcu** [comment]
[Here](https://forums.lanik.us/viewtopic.php?f=64&t=28568&sid=ba850e31de3e7dab7c99428fc0938e8d) is th thread on EasyPrivacy for whoever is interested

**Comment by andreicristianpetcu** [comment]
Apparently it is fixed in upstream. When will the fix land in uBlock Origin?

**Comment by gorhill** [comment]
The filter lists are update automatically in uBO. You can force an update of EasyPrivacy by clicking the "purge cache" button aside the list, then clicking "Update now" button in the "3rd-party filters" pane in the dashboard.

**Comment by andreicristianpetcu** [comment]
@gorhill Awesome! It works :D
