### ISSUE TITLE
Inline Script Tag Filtering doesn't really work

### ISSUE THREAD

**Issue by ayuanx** [gorhill/uBlock#1376]
Example:
http://www.spaste.com/p/?c=COo3zT5186
Filter:
||spaste.com##script:contains(adsBlockerDetected)
Firefox 43 Result:
Wait for 5 seconds and see. Is it because the timer is armed before filtering?

**Comment by Snapy** [comment]
Read the wiki page. 
spaste.com##script:contains(adsBlockerDetected)  should work.

**Comment by ayuanx** [comment]
Am I missing something here?
The wiki says "Compatible to ABP syntax", but not "||" combined with inline script?

**Comment by IDKwhattoputhere** [comment]
Inline script filtering is not part of ABP's syntax.

**Comment by aggat** [comment]
[Because it's cosmetic filter](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#why-is-the-new-inline-script-tag-filter-a-cosmetic-one)
Element hiding  selector (##) in uBO and ABP not combined "||"

**Comment by ayuanx** [comment]
No. I am talking about the "||" part. By reviewing the ABP syntax, I guess it is my misinterpretation.
It seems all element hiding (i.e. "##") must not be used with "||" or "|".
But even ABP doesn't explain why. What's the limitation or consideration behind this restriction.

**Comment by ayuanx** [comment]
Yes aggat.
Do you know what the justification is behind this? Why not design a consistent generic symbol system on domain names for all kinds of filters?

**Comment by gorhill** [comment]
> What's the purpose or consideration behind this restriction?

There is no restriction. A specific cosmetic filter will apply to all subdomains of whatever hostname is specified. I don't know if it's the case for ABP, but with uBO, even a TLD can be used, i.e. `de###ad`.

**Comment by ayuanx** [comment]
@gorhill
No, you are wrong. "||", "|" and "^" are more flexible and have more control over precision.
But anyway, I've found the original reason in ABP why Element Hiding doesn't support them:

> Note: Due to the way how element hiding is implemented, you really can only limit it to full domain names. You cannot use any other part of the address and you cannot use domain as a replacement for domain.example,domain.test.

**Comment by gorhill** [comment]
> No, you are wrong.

A network filter's `||example.com` is semantically equivalent to a cosmetic filter's `example.com`, that was my point.
