### ISSUE TITLE
Iframe - youtube black border bars, affects sites like imgur.com!

### ISSUE THREAD

**Issue by wolfyrion** [gorhill/uBlock#1377]
This affects iframe youtube and is showing black bars below on status.
This affects sites like imgur and other sides that display video using iframe.

Example
http://imgur.com/gallery/njquI/comment/585726168

if you click on the Video it will show you the video but it will show you a black border below on youtube video.

ALL ADDBlockers have this issue , the reason is 

On this file
SiteSecurityServiceState.txt
www.youtube.com:HSTS	0	16844	1456007730335,1,0

if you remove that line you dont have these problems but it will be added again if you dont remove the uBlock addon

It took me a week to find what is causing this issue... ><

Have in mind that if you disable ublock is not solving the problem because the only way to fix this is to delete  www.youtube.com:HSTS	0	16844	1456007730335,1,0 from SiteSecurityServiceState.txt on your Firefox profile

**Comment by IDKwhattoputhere** [comment]
I don't get black borders but maybe I don't understand what you mean. And how would adblockers influence HSTS in the first place?

**Comment by wolfyrion** [comment]
This is what I am getting...

http://i.imgur.com/snjuTgH.png

Anyway maybe it needs further investigation... I will let you know :o

**Comment by IDKwhattoputhere** [comment]
Firefox with uBlock Origin: 
![](https://cloud.githubusercontent.com/assets/16030872/13031262/77909bc6-d2c7-11e5-9e6f-d27c479d8c8e.png)

**Comment by gwarser** [comment]
[Bug 1244495 - YouTube HTML5 embedded video control buttons are hidden](https://bugzilla.mozilla.org/show_bug.cgi?id=1244495)
