### ISSUE TITLE
half activated tabs

### ISSUE THREAD

**Issue by usrnone** [gorhill/uBlock#138]
I have no idea of programming just signup. I installed the extension on Ff after browsing while closed it started again. Then I switch tabs continuously then this happened. It's in the image link is below. It shows home tab icons & newtab icons together like tab is half activated. ex: restore previous session, Firefox logo.
http://i.imgur.com/l36keqv.jpg

**Comment by usrnone** [comment]
tried same thing after disabling the extension didn't happen such a thing.

**Comment by DoodleChan** [comment]
[It's a Firefox issue.](https://bugzilla.mozilla.org/show_bug.cgi?id=1067470)

**Comment by gorhill** [comment]
@DoodleChan Thanks for the finding.
