### ISSUE TITLE
exoclick (NSFW)

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1380]
when clicking back button it redirects to random site.

||exoclick.com^$document,popunder will stop it

https://www.tnaflix.com/

**Comment by gorhill** [comment]
`||exoclick.com^$popunder` is already part of _uBlock filters_.

**Comment by jo2dan23** [comment]
yea. but the document part isn't. thats whats not blocked.

**Comment by jo2dan23** [comment]
here. the document
![screen shot 2016-02-14 at 8 28 16 pm](https://cloud.githubusercontent.com/assets/15130139/13038503/55144c04-d359-11e5-81e7-d18132356445.png)
 filter shown is added in my own list.

**Comment by IDKwhattoputhere** [comment]
The popunder is blocked for me on Tnaflix. No need for a document filter.

**Comment by jo2dan23** [comment]
u have to click the back button on the main page for it to show

**Comment by IDKwhattoputhere** [comment]
I see what you mean. If I open this page in a new window, then click on your Tnaflix link and then the back button of the browser it sens me to Exoclick.

**Comment by gorhill** [comment]
@jo2dan23 If I understand correctly, you did not have Peter Lowe's list selected?

**Comment by jo2dan23** [comment]
@gorhill no. i dont use the host file ones.
