### ISSUE TITLE
adf.ly popunder

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1381]
ad this filter to your list first to get rid of the antiadblock: @@||adf.ly/ad/banner/*

then wait til timer stops then hit skip ad.

http://adf.ly/1UIiUW

**Comment by jo2dan23** [comment]
also. bc.vc has one too but the popunder filter doesn't block it. it shows it being allowed in the logger:

![screen shot 2016-02-14 at 8 35 50 pm](https://cloud.githubusercontent.com/assets/15130139/13038567/5064361e-d35a-11e5-96a2-0b35ebcf105b.png)


http://bc.vc/Uo0pHw#

**Comment by jo2dan23** [comment]
j.gs has one also. add this to get rid of the popunder that appears after clicking skip ad: ||adplxmd.com^$popunder


![screen shot 2016-02-14 at 8 53 35 pm](https://cloud.githubusercontent.com/assets/15130139/13038766/c6ccd4f8-d35c-11e5-9158-bdf3cddd24a0.png)

http://j.gs/FGQ

**Comment by IDKwhattoputhere** [comment]
Interestingly I didn't get any ads on those sites while having my VPN connected. Without it I was able to find two domains:
`||adplxmd.com^$popunder`
`||adnetworkperformance.com^$popunder`
Do those filters get rid of all the popunders for you too?

**Comment by jo2dan23** [comment]
i dont see the second one. where did you find that one on?

**Comment by IDKwhattoputhere** [comment]
On the adf.ly link.
![](https://cloud.githubusercontent.com/assets/16030872/13039786/02fc5baa-d3a4-11e5-82fa-344d38515ac0.png)

**Comment by gorhill** [comment]
I am testing 1.6.4b0 with the case here, and the filters:

    ||adplxmd.com^$popup
    ||adnetworkperformance.com^$popup

To see if the popunder can be blocked by just using the `popup` filter option.

Found out this required a patch with Chromium-specific code, as there are two competing replace URL operations going on, one from the popunder code, on from the document-blocked code.

Now I am trying to find out how Firefox-specific code copes with this, but the test case behaves differently with FF: the new tab does not open a page to `zippyshare.com`, but rather a page on Youtube. Could someone else try to see if they get the same result? (be sure to remove `popunder` filters for this test case, and add only above `popup` filters).

**Comment by DAOWAce** [comment]
Just got a popunder when clicking "skip ad" in adf.ly.  (default list subscription, PM v26.1.1)

Not educated enough to know what to do about this, so I'm just leaving a comment here.

This type of ad is in stepping into the territory of malware to me, since it screws with the browser's session and is being display at all to boot.  More fuel in my fire of requirements to adblock when using the internet.
