### ISSUE TITLE
Applying all rules to web.archive.org

### ISSUE THREAD

**Issue by kepalmer** [gorhill/uBlock#1382]
Would it be possible to add to uBlock filters the ability to block ads on web.archive.org ? 

For example when I open the below page it redirect to an advertisement just after the page finishes loading:
https://web.archive.org/web/20150728171056/http://podium.life/en/models?
and an older snapshot which redirects to a different advertisement:
https://web.archive.org/web/20150520081752/http://podium.life/en/models

Thanks.

**Comment by jo2dan23** [comment]
i dont think so. they are all proxied by the archive.org url. example:

https://web.archive.org/web/20150728171056js_/http://counter.rambler.ru/top100.jcn?2309974

is unblocking a filter listed in easyprivacy. they would have to be generic filters to be blocked.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
