### ISSUE TITLE
Allow source in rules to be a wildcard

### ISSUE THREAD

**Issue by Mikachu** [gorhill/uBlock#1383]
It would be nice if a rule could be specified for an entire site, rather than only a specific subdomain. For things like tumblr, each blog is a new subdomain, which means if I have default-block, I have to create a new ruleset for each tumblr blog I go to. It would save a lot of time to just be able to say *.tumblr.com <destination> blabla once and be done with it.

**Comment by gorhill** [comment]
You can manually enter such rule `tumblr.com blabla * noop` from the _My rules_ pane, it's just not allowed from the popup panel, which won't list entries above base domain.

**Comment by Mikachu** [comment]
Ah, I had only tried putting in *.tumblr.com and it was helpfully deleted, thanks :)

**Comment by surashu** [comment]
@gorhill can you explain this further? I'm trying to use `*.domain.com` and it isn't working unless I specifically put the exact subdomain in.

Example:
`*.zippyshare.com###video_html5_api` won't work on `www22.zippyshare.com` or `www51.zippyshare.com`

**Comment by gorhill** [comment]
[Adblock Plus filters explained / Element hiding / Domain selection](https://adblockplus.org/en/filter-cheatsheet#elementdomains).
