### ISSUE TITLE
dle.rae.es - Verb Conjugation on Real Academia Española Is Broken

### ISSUE THREAD

**Issue by emariz** [gorhill/uBlock#1384]
Normally, when one searches the definition of a verb on the dictionary of the Real Academia Española (1), the verb conjugation is offered through a blue, pill-like button labelled "Conjugar". Well, uBlock breaks this conjugation function and shows a blank page instead.
The registry shows nothing relevant, other than its being an inline-script/doc.

I am using uBlock Origin on Iceweasel (Firefox) 44 on Debian Testing.

For those who do not speak Spanish, one can test this by looking up the verbs "ser", "estar" (to be) or "ir" (to go), and then pressing the blue button labelled "Conjugar" right next to it.

1. http://dle.rae.es/

.
This issue was already reported to EasyList, and a developer/maintainer pointed out that the error was in uBlock Privacy filters.
https://forums.lanik.us/viewtopic.php?f=64&t=28601

> Adblock plus + Easylist → No issue.
>
> disable uBlock filters – Privacy list and test again
>if works report this issue on https://github.com/gorhill/uBlock/issues
>
> bad filter:
> `||addthis.com^$third-party,important`
>

**Comment by gorhill** [comment]
Force an update of your filter lists in the _3rd-party filters_ pane.

**Comment by emariz** [comment]
The dictionary works as expected now. Thank you very much for your time and fast response.
Cheers, mate.
