### ISSUE TITLE
addthis filter

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1385]
i saw you added the neutured add this script. it fixes the site that the issue was opened about. but this site it breaks.

go to website below. then click the calendar button to the right of the left pointing arrows. it doesnt work unless i disable ublock privacy

http://www.gocomics.com/kidspot

**Comment by IDKwhattoputhere** [comment]
It works when blocked with Ghostery though. Seems they neuter it differently.

**Comment by jo2dan23** [comment]
i dont think ghostery is blocking it then. because i don't think ghostery does neutered scripts

**Comment by IDKwhattoputhere** [comment]
Why do you think they don't? They do it with a lot of scripts which is the reason why it can block relatively much with little website breakage.

**Comment by jo2dan23** [comment]
do you have annoyance list enabled or RUS: BitBlock List (Дополнительная подписка фильтров)?

**Comment by IDKwhattoputhere** [comment]
![](https://cloud.githubusercontent.com/assets/16030872/13061846/e0ea309a-d43a-11e5-802b-87483eaedf84.png)

**Comment by gorhill** [comment]
Console says:

> Uncaught TypeError: addthis.init is not a function

Need to add `init`, I just added the ones I saw in console.

**Comment by jo2dan23** [comment]
wow. awesome job! addthis is now completely blocked on over 15 million websites :dancer:

**Comment by gwald** [comment]
:(
