### ISSUE TITLE
gigya

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1386]
is there a way to do a neutured version of this script without it breaking websites? its similar to addthis

https://cdns.gigya.com/JS/socialize.js?apikey=3_fAWdKrSiknuIiCsLrGHAWZTerkRZNppTl6s4mMm6Fdj39ykUSs1AuephqvoJoD2j&lang=

site example: https://www.beatsbydre.com/ (breaks slideshow if blocked)

**Comment by lewisje** [comment]
It's mentioned in CONTRIBUTING.md rather than more prominently, but this is where support requests should go now: https://discourse.mozilla-community.org/t/support-ublock-origin/6746
