### ISSUE TITLE
Elusive ads

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#1387]
Sorry if this is not the best place to do it but I didn't know where to put it. I would like to know if it's possible to block ads that have random numbers on it and how to do it. For example

www.newgrounds.com###outer > .PalevioletredHighlevelRockrat1455516819

www.newgrounds.com###\38 38693 > div > a[href^="http://www.mmo123.co/egame"]

Thanks in advance.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by rayman89** [comment]
Can't you help me in any way?

**Comment by aggat** [comment]
Some  `>`   can be omitted. 
`.name` and `#name` can be written as `[class="name"]` and `[id="name"]`.
This will work
`newgrounds.com##div[class^=PalevioletredHighlevelRockrat]`
`newgrounds.com##a[href^="http://www.mmo123.co/egame"]`

**Comment by rayman89** [comment]
Thanks a lot @aggat .

**Comment by lewisje** [comment]
This is where support requests should go now (it's also in CONTRIBUTING.md but I'm posting the link here in case you don't read that): https://discourse.mozilla-community.org/t/support-ublock-origin/6746
