### ISSUE TITLE
Slow But Sustained CPU Drain

### ISSUE THREAD

**Issue by rdsubhas** [gorhill/uBlock#1388]
Hi, firstly thanks so much for this wonderful extension.

I'm observing a slow but consistent CPU drain (0.3% CPU usage), irrespective of any tab is active or not. I'm not sure if this is normal, but 0.3% over a long period of time (I tend to leave Chrome running) seems to consume a lot of energy. Interestingly, uMatrix doesn't have this problem.

So is this an issue, or is there any way the extension can go to complete sleep (0% cpu) when there is nothing active?

With no tabs active:

<img width="592" alt="screen shot 2016-02-16 at 12 35 37 pm" src="https://cloud.githubusercontent.com/assets/1570745/13069404/7fb615da-d4aa-11e5-9d55-da5172311e1c.png">

With tabs settled:

<img width="592" alt="screen shot 2016-02-16 at 12 33 33 pm" src="https://cloud.githubusercontent.com/assets/1570745/13069414/93cebe3c-d4aa-11e5-9d24-cf956a19b4a6.png">

More details:
Chrome 48.0.2564.109 (64-bit), OSX 10.11.2, uBlock Origin 1.5.6

**Comment by gorhill** [comment]
Here is a 2-minute video of uBO's CPU usage while the browser is left idle:
https://a.pomf.cat/kblydv.webm

Following this, I opened uBO's dev console, and clicked _"Pause script execution"_ in the _Sources_ pane: the execution was not paused when the browser was left on idle, despite the CPU value sometimes showing "1". This means that whatever is causing CPU to show non-zero value while on idle, it's not uBO's code executing, it's the browser's code.
