### ISSUE TITLE
Popup user interface refreshed while on same page

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1389]
I noticed that these filters are incompatible, they hide flugubluc.com in uBO's own popup window:

```
filmvf.net,filmstreaming-hd.com,gaara-fr.com,gaytube.com,gum-gum-streaming.com,hentaifr.net,hentaihaven.org,tuxboard.com,xstory-fr.com##script:inject(phenv-defuser.js)
||flugubluc.com^$third-party,domain=gaytube.com
```

The prior filter is found in `uBlock filters` and have a tendency to make the latter filter useless.

Why do they interfere?

**Comment by gorhill** [comment]
> make the latter filter useless

What does "useless" mean exactly here? Please describe the specific behavior, "useless" is vague.

**Comment by flyingzebras** [comment]
@gorhill `filmvf.net,filmstreaming-hd.com,gaara-fr.com,gaytube.com,gum-gum-streaming.com,hentaifr.net,hentaihaven.org,tuxboard.com,xstory-fr.com##script:inject(phenv-defuser.js)` white list `||flugubluc.com^$third-party,domain=gaytube.com`.

**Comment by gorhill** [comment]
This makes no sense, `phenv-defuser.js` can't cause uBO to whitelist anything. Provide repro steps please.

**Comment by gorhill** [comment]
The filter `||flugubluc.com^$third-party,domain=gaytube.com` does not make sense. Try `||flugubluc.com^$third-party` instead.

**Comment by flyingzebras** [comment]
@gorhill If I only want to block flugubluc.com on gaytube.com then?

**Comment by gorhill** [comment]
`||flugubluc.com^$domain=gaytube.com`.

Now, you will have to substantiate your claim that the filter is rendered useless by some injected script -- this makes no sense. I won't try to pull information from you anymore, it's time-consumnig. Be proactive: investigate and provide evidence for your claim. I will re-open if you do so.

**Comment by flyingzebras** [comment]
@gorhill 

`*$third-party,domain=extremetube.com|gaytube.com|keezmovies.com|mofosex.com|peeperz.com|pornhub.com|porniq.com|pornmd.com|redtube.com|redtube.com.br|spankwire.com|thumbzilla.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com`will block selipuquoe.com but not flugubluc.com, on say http://www.gaytube.com/information. Can you please explain why?

**Comment by lewisje** [comment]
Look in the logger to see which whitelist rules are actually applied: I can tell that the filter you just posted is not a whitelist rule, and neither is the filter you first posted, although that one didn't explicitly block those domains either.

**Comment by IDKwhattoputhere** [comment]
Use the logger.
![](https://cloud.githubusercontent.com/assets/16030872/13077966/713b003a-d4bc-11e5-9dd0-691ea16807aa.png)

**Comment by flyingzebras** [comment]
@lewisje @IDKwhattoputhere Can you reproduce this https://github.com/gorhill/uBlock/issues/1389#issue-133941001

**Comment by IDKwhattoputhere** [comment]
Yes, look at the darn logger.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Why would EasyList white list flugubluc.com only when `filmvf.net,filmstreaming-hd.com,gaara-fr.com,gaytube.com,gum-gum-streaming.com,hentaifr.net,hentaihaven.org,tuxboard.com,xstory-fr.com##script:inject(phenv-defuser.js)` is in use, but not otherwise?

**Comment by IDKwhattoputhere** [comment]
I don't understand what you mean.
![](https://cloud.githubusercontent.com/assets/16030872/13078316/75ddb856-d4be-11e5-8c99-68afc7382e03.png)
![](https://cloud.githubusercontent.com/assets/16030872/13078342/a67f128e-d4be-11e5-9a36-5e228466cf6f.png)

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Turn off `377 benutzt aus 347 Leere den Cache` and reload gaytube.com in the logger. Now you will notice that flugubluc.com is not loaded.

**Comment by IDKwhattoputhere** [comment]
Look at the second screenshot.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere I just noticed. We get different results.

**Comment by IDKwhattoputhere** [comment]
Post a screenshot like mine.

**Comment by flyingzebras** [comment]
![script-inject](https://cloud.githubusercontent.com/assets/11916082/13079193/4d684512-d4c3-11e5-9c7c-b6d2cd1ac775.png)

**Comment by lewisje** [comment]
In the uBlock Origin popup menu, click the icon just to the right of the eyedropper; that's the logger. Then take a screenshot of *the logger* just like @IDKwhattoputhere did.

**Comment by IDKwhattoputhere** [comment]
The script is loaded both times. Isn't that the opposite of what you said?

**Comment by flyingzebras** [comment]
@lewisje @IDKwhattoputhere @gorhill notice the red mark in the popup window.

**Comment by lewisje** [comment]
What we want to see is what precisely is whitelisting the domain.

**Comment by IDKwhattoputhere** [comment]
It's EasyList. The problem here is that the popup user interface isn't displaying the domain. @gorhill will have to say if this needs to be fixed or not.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Yes, and it all boils down to `3rd-party filters -> uBlock filters` that uses the filter `filmvf.net,filmstreaming-hd.com,gaara-fr.com,gaytube.com,gum-gum-streaming.com,hentaifr.net,hentaihaven.org,tuxboard.com,xstory-fr.com##script:inject(phenv-defuser.js)`.

So that filter interfere with uBO's own popup window.

**Comment by IDKwhattoputhere** [comment]
I think this is causing the issue, not the filter: ![](https://cloud.githubusercontent.com/assets/16030872/13081564/936bbcce-d4cd-11e5-9265-78317dfa2d4f.png)

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Thank you for helping me out! So should `document` be added somewhere?

I'm not so good with filters yet.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere 

Are you sure? Please read the [first](https://github.com/gorhill/uBlock/issues/1389#issue-133941001) description in this post

If not, should `document` be added somewhere?

**Comment by IDKwhattoputhere** [comment]
A filter won't help. Since the `document` is loaded it causes the popup user interace to refresh. I don't know if this is a bug of the popup user interace or somewhere else in uBO.

**Comment by IDKwhattoputhere** [comment]
Your filter is useless no matter what since EasyList is whitelisting the script.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Yeah, but I'm interested in helping out and fixing this bug to get rid of confusion when I evaluate my filters.

**Comment by IDKwhattoputhere** [comment]
Yes, but "phenv-defuser.js interfere with uBO's own popup window" is wrong. And if you really want to block flugubluc.com you can try to use the `important` filter option.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Please give me a suitable title and I will change it.

**Comment by IDKwhattoputhere** [comment]
Maybe `Popup user interface refreshed while on same page`.

**Comment by gorhill** [comment]
> Since the document is loaded it causes the popup user interace to refresh.

Was the URL of the tab changed to `http://www.gaytube.com/?gtdoi`? If so, everything works just as expected.

**Comment by flyingzebras** [comment]
@gorhill 
> Was the URL of the tab changed to http://www.gaytube.com/?gtdoi? If so, everything works just as expected.

http://www.gaytube.com/

Did you read https://github.com/gorhill/uBlock/issues/1389#issuecomment-184703965 ?

**Comment by gorhill** [comment]
There is a quirk specific to Firefox here. Unclear whether this is fixable.

So far my understanding is that uBO receives a "Location Change" event after it has started to process the document. A "Location Change" event will cause all the data collated from the page to be reset, and so the record that there was a network request to `flugubluc.com` is lost.

"Location Change" events are always received before the network request to fetch the document is processed. For some reasons it does not seem to happen here. Using synchronous messaging from in `LocationChangeListener.prototype.onLocationChange` does not help -- as if the issue is within Firefox itself.

**Comment by flyingzebras** [comment]
@gorhill > Unclear whether this is fixable.

I suggest that you ask the developers of Firefox.

**Comment by SMed79** [comment]
@flyingzebras why you want to block `flugubluc.com` & `selipuquoe.com` ?

**Comment by flyingzebras** [comment]
@SMed79 Both of them are ad domains.

**Comment by SMed79** [comment]
@flyingzebras No ads from these domains ! `selipuquoe.com` is added in an iframe created for example on `http://jeu.info/` by this script `http://dtf.goyavelab.com/dtct.js` the trick is used exactly to avoid using an exception filter and eventually using a super-general exception filter which can enable ads on other sites. (This main `selipuquoe.com` is used to detect if you block ads on your browser...)

all domains http://pastebin.com/raw/sJ9aaCX9

Try these filters on `http://jeu.info/uphill-rush-6.html`
```
@@||dtf.goyavelab.com/dtct.js$script
@@||selipuquoe.com^$image,~third-party
@@||infojeu.com/*.js?$script,third-party
@@||adnxs.com^$domain=jeu.info
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=jeu.info
```

**Comment by flyingzebras** [comment]
@SMed79 The main focus here is to fix the bug that is triggered by flugubluc.com. Thank you for letting me know that selipuquoe.com is used for ad blocking detection though.
