### ISSUE TITLE
ABP issue #2390: "Create a new filter class for CSS property filters"

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#139]
It seems ABP is creating a new class of cosmetic filters:

[#2390: Create a new filter class for CSS property filters](https://issues.adblockplus.org/ticket/2390)

Will need to keep track when this become reality, and then eventually implement support for this in uBlock.

My current understanding of this new class of cosmetic filters is to gain the ability to run a regex against the value of the `style` attribute of a DOM element.

**Comment by massar** [comment]
FYI: Apparently there was some code commited:
 https://hg.adblockplus.org/adblockplus/rev/f99ad521dd5f

**Comment by gorhill** [comment]
Just to be clear, I don't take code from ABP -- I implement my own code according to spec.

**Comment by massar** [comment]
@gorhill I am well aware (but yes, others might not), your code does not contain remarks like "CSS property filters are inefficient" :)

I could not quickly find a spec unfortunately for this new setup.


Being able to allow CSS (for stuff like colors/locations) when that CSS is loaded from a domain enabled in dynamic filtering would be a nice thing; I guess though that this feature would help a lot already as then odd css for loading fonts etc can easily be filtered out.

**Comment by lewisje** [comment]
This new syntax was announced in December and just recently implemented in stable builds of ABP: https://adblockplus.org/development-builds/new-css-property-filter-syntax

**Comment by gorhill** [comment]
I [commented](https://github.com/gorhill/uBlock/issues/1752#issuecomment-228546295) in issue #1752:

> I do worry about the overhead introduced by `-abp-properties`

To confirm/infirm whether I worry needlessly, I profiled a page (timings are for reloading the page 10 times) where `-abp-properties` is used, here is the results (ABP top, uBO bottom, both using EasyList, EasyPrivacy + EasyList Germany):

![a](https://cloud.githubusercontent.com/assets/585534/16363217/cc7b02d8-3b91-11e6-8b0f-7a31dddbc333.png)

The yellow-highlighted lines are the top contributed overhead by the content scripts of the extension. As expected, `-abp-properties` adds a significant overhead to page load, as seen by the `CSSPropertyFilters.onLoad()` timings (and in the current case, those filters seemingly didn't accomplish anything, the page still loaded those annoying ads). The overhead introduced by `-abp-properties` is not present if there is no `-abp-properties` filters for the page.

**Comment by TheFinalCut83** [comment]
This is strange, but when I checked your example with focus.de (same filters as yours), uBO seems to have missed that ads at the top.
![1](https://cloud.githubusercontent.com/assets/16985985/16374581/c7d19e4e-3c5f-11e6-81de-2dab2e101d65.jpg)
I've reloaded the page with cache and without at least 5 times.
ABP, same filters.
![3](https://cloud.githubusercontent.com/assets/16985985/16374633/03bb978e-3c60-11e6-9cfe-da166d6c387d.jpg)
German IP, of course
![2](https://cloud.githubusercontent.com/assets/16985985/16374869/2629add2-3c61-11e6-8a20-71a021174ce9.jpg)
But yes, not a VPN, but browser plugin Zenmate, maybe such result because of this.

**Comment by gorhill** [comment]
@IDKwhattoputhere, @TonyTough, do you get the same thing as @TheFinalCut83? All works fine from my side.

**Comment by IDKwhattoputhere** [comment]
Cyberfox:
https://cloud.githubusercontent.com/assets/16030872/16380211/f50e7b3c-3c75-11e6-96e1-6d902d00278e.jpg
Sometimes I get no, sometimes I get some and other times I get all the banners (after reloading, clearing cache doesn't seem to matter).
https://cloud.githubusercontent.com/assets/16030872/16380217/fbef477e-3c75-11e6-9ed0-2f737441923c.jpg
Firefox:
https://cloud.githubusercontent.com/assets/16030872/16380508/c3c661a0-3c77-11e6-8381-3e4735082457.jpg
Same behaviour except that there's always a delay of multiple seconds before the banners are inserted (after the page has finished loading) which I didn't notice in Cyberfox.
https://cloud.githubusercontent.com/assets/16030872/16380514/cd0d161e-3c77-11e6-93d3-72f7f1c71271.png

**Comment by gorhill** [comment]
>  I thought you meant only those filter lists

For uBO, I meant default filter lists + EasyList Germany, for ABP I meant EasyList + EasyList Germany + EasyPrivacy minus "_Acceptable ads"_.

**Comment by TonyTough** [comment]
For me all is OK on focus.de with ublocks standard filters and Firefox 47 (German IP).
I use focus.de several times a day.

**Comment by TheFinalCut83** [comment]
Yes, with default filter lists + EasyList Germany all is OK.

**Comment by ryanbr** [comment]
Recently I've been tackling a few base64 encoded ad sites on onwatchseries.to (and mirror sites). Using 

`
onwatchseries.to##[-abp-properties='data:']
onwatchseries.to##[-abp-properties='base64']
`

Which doesn't seem to work well in uBo. I'm pretty sure you can inject scripts etc, but given the popularity of base64 encoded ads, -abp-properties support would be helpful for a quick and dirty fix.

Related commits:
https://github.com/easylist/easylist/commit/129c24894548327859ee07d5795973f2c7b33edb
https://github.com/easylist/easylist/commit/fb484f34e3665540964c486b88153be1d2075dfc
https://github.com/easylist/easylist/commit/f664b6ab51473f62d78e56256e73b9f7b02ed858

**Comment by gorhill** [comment]
> `-abp-properties` support would be helpful for a quick and dirty fix.

As said, it's performance-wise scary. Each rule in each stylesheet present on the page must be iterated, and for each of these rules, a string version of all its own CSS properties, sorted, must be constructed and the result tested against a regular expression derived from the filter. Repeat for all single `-abp-properties` filter. 

What I am seeing on `onwatchseries.to` after updating EasyList to get the filters above is that the exception filters `@@||bambergerkennanchitinous.com^$script,domain=[...]` is at the root of these ads, it allows the request `http://bambergerkennanchitinous.com/.adframesrc.` to go through unblocked. Why not just remove this exception filter?

The real issue from uBO's point of view is ABP's limitations forcing the use of such exception filters in EasyList, so aside `-abp-properties` being a performance concern, it's the wrong fix: it fixes the symptoms, the root issue is those exception filters created for the sake of ABP.

**Comment by uBlock-user** [comment]
If you pick `gorillavid.in` as the source on `onwatchseries.to`, it now tries to load popups using `ddata:` as the protocol FYI

Logger - `https://i.gyazo.com/93af9a3c8d65e4ed6e65c69e4621bea3.png`

Is that even possible using `ddata:` as the protocol ?

**Comment by lewisje** [comment]
What specific link did you find this behavior in?

I think `ddata:` is a typo, I know I can't load from that URI scheme in Chrome.

**Comment by uBlock-user** [comment]
> What specific link did you find this behavior in?

Try to reproduce here - What specific link did you find this behavior in?

> I think ddata: is a typo

I don't think so, they're bypassing the block now by using `ddata:` which is indeed invalid URI scheme.

**Comment by mapx-** [comment]
ddata on eztv.ag (chrome)
https://forums.lanik.us/viewtopic.php?p=111420#p111420

**Comment by uBlock-user** [comment]
Using `|ddata:$popup` doesn't have any effect in uBO fyi

**Comment by gorhill** [comment]
> it now tries to load popups

Does it work? The popup got closed on my side.

**Comment by uBlock-user** [comment]
No it doesn't work, thanks to other popup blocking filters, but I came across this, so I felt like reporting. Hence the word "tries".

**Comment by gorhill** [comment]
Anyway, the issue here is about the `-abp-properties` filter, unrelated filter issues need to be reported at uAssets.

**Comment by uBlock-user** [comment]
That domain has been swapped again and the new domain is `mywatchseries.to`
