### ISSUE TITLE
Logger displays wrong source for some filters

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1392]
The logger seems to report the wrong source sometimes.

How to reproduce:
1. Go to NSFW pornhub.com
2. Open the logger and click on the slopeaota.com entry

Result: uBO reports "uBlock filters" as a source even though it doesn't contain the filter `||slopeaota.com^`.

![](https://cloud.githubusercontent.com/assets/16030872/13080651/e9708676-d4c9-11e5-997b-68c16eaaddb6.png)

Tested with newest uBO versions from the stores on Firefox (fresh profile) and Chrome.

**Comment by jo2dan23** [comment]
mine doesnt show that. what version are you on

**Comment by gorhill** [comment]
The regular expression used to find the compiled filter is `0.slopeaota.com`, which causes the existing `b0.slopeaota.com` filter in that list to be hit.

Need to anchor the start of the regular expression on a word boundary.

**Comment by IDKwhattoputhere** [comment]
@jo2dan23 
> Tested with newest uBO versions from the stores on Firefox (fresh profile) and Chrome.

@gorhill Thanks! Could you also please take a look at [my filter list](https://github.com/IDKwhattoputhere/uBlock-Filters-Plus) and maybe add it to the wiki?

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Thank you very much for posting this issue.
