### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1393]
is there anyway to stop the anti adblock without having to keep whitelist?

http://www.cbs.com/shows/grammys/video/OWWhlLfQ9hlSekNNkVgTkOKCopvwo7Tp/the-58th-annual-grammy-awards/

**Comment by gorhill** [comment]
The site uses a Flash player. For anything based on such proprietary blob, I won't bother trying to find out if something can be bypassed, we are not dealing with javascript code which can be fully scrutinized.

**Comment by IDKwhattoputhere** [comment]
Have you tried [Anti-Adblock Killer](https://github.com/reek/anti-adblock-killer#instruction)?
