### ISSUE TITLE
"Block media elements by size" breaks youtube video playback

### ISSUE THREAD

**Issue by yakka34** [gorhill/uBlock#1394]
I found that since ublock updated on google store youtube videos wouldn't play properly. It would buffer some and then pause to buffer more droping internet usage to 0% for a moment. After disabling the feature the problem went away.
Perhaps this bandwith saving feature shouldn't be activated by default?

**Comment by gorhill** [comment]
> Perhaps this bandwith saving feature shouldn't be activated by default?

It's not.
