### ISSUE TITLE
uBlock is not able to apply ONLY my cosmetic filters

### ISSUE THREAD

**Issue by romanmd86** [gorhill/uBlock#1395]
Having some own cosmetic filters for some sites, they are not applied by uBlock, unless I enable "Parse and enforce cosmetic filters" from "3-rd Party filters" tab. And this will enforce thousand of filters on these sites, not exclusively my own ones.

**Comment by gorhill** [comment]
I don't plan to support this. Network filtering is what uBO is first and foremost, it does not make much sense to be able to disable this.

**Comment by gorhill** [comment]
Ugh, I misunderstood the issue.

**Comment by romanmd86** [comment]
That was fast
thx

**Comment by IDKwhattoputhere** [comment]
Interesting. I always thought this was already the case since the option is located in the 3-rd Party filters panel.
Thanks for implementing this.
