### ISSUE TITLE
uBlockOrigin keeps on blocking even when turned off

### ISSUE THREAD

**Issue by the-trooper0000** [gorhill/uBlock#1396]
Hello
Here are two screen shoots
With uBO on:
http://i.imgur.com/JOxWQlV.jpg
With uBO off:
http://i.imgur.com/UChP4xN.jpg

uBlockOrigin is the only add blocker I use. Version 1.6.1 with Firefox 44.0b1, but this has been bugging me for several version of both uBlock and Firefox. And it's not just this page in screenshots, all pages look exactly the same with uBO on or off. Again, uBO is the only add blocker installed and I don't know where else to look.
Thanks in advace!

**Comment by harshanvn** [comment]
Looks like you might have `Use Tracking Protection in Private Windows` enabled in your firefox settings. You would need to disable it, for the site not to detect the adblocker!

**Comment by the-trooper0000** [comment]
Nope, even with it turned off it's still the same. Besides, it's happening in normal mode not private (these screenshots too), so I guess it shouldn't make a difference, right?

**Comment by harshanvn** [comment]
Ok, clear your cache and try again in Private browsing mode, after turning off `Use Tracking Protection in Private Windows`

If its still happening, then open Firefox Dev Console `F12` paste the results here.
See my Dev Console log for reference -
>  [  0.020s] [studio.sdk]  Enabler.js:100:255
 [  0.023s] [studio.sdk]  Enabler.js:100:255
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create index.html:12:9491
 [  0.261s] [studio.sdk] Asset properties have been set by host. Enabler.js:100:255
 [  0.262s] [Enabler] ad visible Enabler.js:100:255
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:7108
 [  1.201s] [studio.sdk] Using default ad parameters in test environment. Simulating local events. Enabler.js:100:255
Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping:1:51


For me after disabling uBlock for this particular site, i no longer see the message -

**Comment by the-trooper0000** [comment]
Solved! It was tracking protection after all. Thank you!

**Comment by lewisje** [comment]
TFW emoji shortcodes are parsed in logs

**Comment by IDKwhattoputhere** [comment]
Except that's not code but a quote.
Quote:
> :+1: 

Code:
` :+1: `
