### ISSUE TITLE
www.focus.de

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#1397]
Since today www.focus.de is totally broken using firefox 44.02 and ublock 1.61 and standard filters.

Only disabling of EasyList, PeterLowe and EasyPrivacy makes the site work as it should.
So I think this could be some new anti-adblock script?

Adding
||focus.de^$inline-script
works in the meantime for me, but this way some useful scripts are also blocked.

**Comment by gorhill** [comment]
Seems to all work fine from here, no ads + videos play fine. Be very specific about what is "totally broken".

**Comment by TonyTough** [comment]
http://s15.postimg.org/px2fwlamz/focus.jpg

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/13111257/d4d02d8c-d552-11e5-966a-f745b931d301.png)

**Comment by gorhill** [comment]
Use the logger, since I can't reproduce you will need to investigate on your side.

**Comment by harshanvn** [comment]
Neither can i. It works fine here on Firefox v44 + uBlock v1.6.1

**Comment by sigtus** [comment]
Works just fine here as well. And having Easylist, Peter Lowe, and EasyPrivacy as well.

**Comment by TonyTough** [comment]
ublock logger didn't help me, so I used the Firefox Javascript-Debugger.

The site works for me now adding this:
focus.de##script:contains(fol_tfm_container.js)

**Comment by TonyTough** [comment]
But I don't know why others don't have this problem.
BTW: I'm using the 64 bit version of Firefox if that matters.

**Comment by gorhill** [comment]
Ok, I found that if I disable _"uBlock filters -- Experimental"_, I can reproduce the issue. More specifically, this fixes the issue:

    ||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices.com/gpt.js,domain=focus.de

**Comment by gorhill** [comment]
Just found out ABP suffers same issue with up-to-date filter lists (EasyList, EasyPrivacy, EasyList Germany).
