### ISSUE TITLE
uBlock always requires restarting browser for changes to make effect.

### ISSUE THREAD

**Issue by ppklom** [gorhill/uBlock#1398]
Self-explanatory.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by anewuser** [comment]
@gorhill It is now possible to create templates for issues and pull requests on Github. This will hopefully make more people file issues the way you want and save your time:  https://github.com/blog/2111-issue-and-pull-request-templates
