### ISSUE TITLE
Views on 1st-party tracking

### ISSUE THREAD

**Issue by kevinsimper** [gorhill/uBlock#1399]
I have a deep respect for people that fights for privacy! Privacy is well needed these days.

I do have a question that I could not find a answer for when searching. There is a lot of websites that just uses Google Analytics to track who is visiting their site and javascript tracking is a lot better to detect bots/scraping vs real users.

I understand the difference between 1st and 3rd party, but would first party tracking be allowed in the eyes that the website owner really just want to knows if somebody visits their website and not just bots, or is the solution just to require login.

An example could be a announcement about a old exhibition. How many real people did actually see that announcement but did not react. You can always just look at the server logs, but that includes a lot of bots.

I know there very well may not a single answer and the answer could just be "maybe", but I would hope to be a useful discussion.

Thanks and sincerely 
Kevin Simper

**Comment by IDKwhattoputhere** [comment]
Related: https://adblockplus.org/forum/viewtopic.php?f=17&t=44029

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
