### ISSUE TITLE
Detect ublock by sending ajax

### ISSUE THREAD

**Issue by nmtrung** [gorhill/uBlock#140]
Ublock Chrome
A site can detect ublock by sending ajax request to "document-blocked.html" file on your extension.
I read manifest.json and find: "web_accessible_resources": [ "document-blocked.html" ].
Please fix it, thank you. I love your extension.

**Comment by gorhill** [comment]
Can you be more specific? I am not understanding your "sending ajax request to 'document-blocked.html'"

**Comment by theheroofvn** [comment]
$(document).ready(function() {
    ddsmoothmenu.init({
        mainmenuid: "smoothmenu1", //menu DIV id
        orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
        classname: 'ddsmoothmenu', //class added to menu's outer DIV
        //customtheme: ["#1c5a80", "#18374a"],
        contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
    })
    $("img.lazy").lazyload({
        effect: "fadeIn"
    });
    //*Banner slide Home, Event, Phimle, Phimbo
    if ($('.pix_diapo').length > 0) $('.pix_diapo').diapo();
    //autoComplete Search
    $('input[name=keyword]').autoComplete({
        // preventEnterSubmit is already flagged true by default
        onSelect: function(event, ui) {
            $("form#frmSearch").submit();
        }
    });

    var pluginsForbidden = [
        "cfhdojbkjhnklbpkdaibdccddilifddb/block.html",
        "gighmmpiobklfepjocnamgkkbiglidom/jquery/css/jquery-ui.custom.css",
        "abjfcmmbedogiedgdhjhbijmcflpmdei/document-blocked.html",
        "cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html"
    ];
    for(i = 0; i < pluginsForbidden.length; i++){
        if(detectExtension(pluginsForbidden[i])){
            ADS_TRACK = true;
            break;
        }
    }
});

function detectExtension(link) { 
   var retval = false;
   link = "chrome-extension://" + link;
   $.ajax({
        url : link,
        async : false,
        success: function(rs){
            retval = true;
        }
    }
   )
   return retval;
}

**Comment by theheroofvn** [comment]
cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html
This is path of your id extensions + document-blocked.html

**Comment by gorhill** [comment]
Ok I see. `web_accessible_resources` is actually not needed, I put that in when I was trying to redirect network requests to it, rather than navigate to it.

**Comment by flyingzebras** [comment]
@gorhill I noticed "Site detects blocker: http://dayt.se/forum/showthread.php?7055-Ninety-Nine-Homes-(2015)-1080p-WEBRip-Download-Online-Streaming" in https://github.com/gorhill/uBlock/releases/tag/1.3.7b8

I hope I can help you further; These sites have adblock detection:

Reported in ​https://forums.lanik.us/viewtopic.php?f=62&t=23492&p=71983#p71983

* extremetube.com
* porntube.com
* keezmovies.com
* youporn.com
* sextube.com
* spankwire.com
* mofosex.com

There might be other sites in the Pornhub NETWORK as well that detect adblockers.

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1000
