### ISSUE TITLE
Ublock still detects ghostery 

### ISSUE THREAD

**Issue by Redshift91** [gorhill/uBlock#1400]
Hi!

I already whitelisted the google analytics in Ghostery yet it still warn me about the ublock redirecting.If its not the google analytics then what it is?So if I knew I could whitelist it.Thank you.
![java](https://cloud.githubusercontent.com/assets/11966222/13147441/548d2258-d659-11e5-8fb3-793940f5dc55.JPG)

**Comment by gorhill** [comment]
> If its not the google analytics then what it is?

I don't know, you provide so little information that it's impossible for me to provide an answer.

The first thing to do is to always use the logger, it will tell you what is being blocked, and what is being redirected by uBO (the lines marked with `<<`):

![](https://cloud.githubusercontent.com/assets/787312/13025228/4b105e4e-d1d0-11e5-9bdc-c2604471511d.png)

**Comment by Redshift91** [comment]
Thanks for the help.

**Comment by Redshift91** [comment]
I find the addThis widget has the same mark as the google analytics.So this is what causing it?Did you changed the addthis script like the GA?
