### ISSUE TITLE
[Feature Request] Blocking base64 images on sites by user choice

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uBlock#1401]
For example http://armorgames.com/ is full of the 1st-party base64 advertisement which is unblockable for me and for filter writers.

**Comment by gorhill** [comment]
> unblockable for me and for filter writers

What "filter writers" did you report to?

    armorgames.com##a[href^="http://www.mmo123.co/"]

**Comment by jhsagl4a** [comment]
No-one.
But easylist earlier blocked same ads in this site. And this site began to use the 1st-party base64 tactic and I decided that now the easylist team can't do anything with it.
But it's a great filter, I make a mistake.

**Comment by lewisje** [comment]
There isn't a good way to deal with this, I mean you might try something like `domain##img[src^="data:image/"]` but that hides *all* images loaded with data URIs, and you can't block them because they're part of the page, so there's no separate network request to block.

**Comment by jhsagl4a** [comment]
There is a else filer from here https://forums.lanik.us/viewtopic.php?f=62&t=28014
`armorgames.com##IMG[src^="data:image/;base64,"]`

**Comment by gorhill** [comment]
That filter removes only the images inside the links, my suggested filter removes the links **and** the images.

This is the DOM:
- `a[href="http://www.mmo123.co/..."]`
    - `img[src="data:image/;base64,..."]`

Notice there are links left behind on the page with `armorgames.com##IMG[src^="data:image/;base64,"]`.

**Comment by gorhill** [comment]
After looking at the thread on EasyList forum, I decided to add the filter I suggested to uBO's filter -- as it does not look it will be fixed  given that the issue was first reported a month ago on Jan. 21th.
