### ISSUE TITLE
could ublock origin be blocking google instant results?

### ISSUE THREAD

**Issue by jayceekay** [gorhill/uBlock#1402]
tl;dr - silly question maybe but i thought i'd ask here before trying to debug this. 

i'm not even sure how to debug other than launching chrome with a new profile that's clean, which i haven't researched how to do yet. i also don't know the implications of disabling ublock for google search pages in order to test from that direction either.

**Comment by IDKwhattoputhere** [comment]
> which i haven't researched how to do yet.

Why?

Have you checked your Google settings? https://www.google.com/preferences
Instant works fine for me in Chrome with uBO.

**Comment by gorhill** [comment]
Use the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) -- it tells what i happening inside uBO, and why.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
