### ISSUE TITLE
Empty domain line (cell) - how can this be?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1403]
After I connect to my Router page, I saw the following:

![ubo_emptyfield](https://cloud.githubusercontent.com/assets/11355601/13156671/ec4098c6-d683-11e5-85ad-07d85be69adc.png)

Here is the log ...

How can this be - a such empty line?
![ubo_emptyfield-log](https://cloud.githubusercontent.com/assets/11355601/13156682/03dd5a32-d684-11e5-870b-c307357ead96.jpg)

**Comment by gorhill** [comment]
Since it's something I can't reproduce, it would be nice if you can contribute investigation work -- the browser contains all the tools to investigate all of uBO. For example, see if there is really no text in the hostname label: right-click on it, then click inspect, see DOM.

Will mark as available so that whoever is willing to contribute investigating this is welcome. Actually, investigation to pinpoint cause of issues is always welcome.

**Comment by Alpengreis** [comment]
Thanks! I'll investigate it and report here soon ...

**Comment by Alpengreis** [comment]
This is a first try to give you more data about this ... please do not hesitate to inform me, if you need more things ...

Here the result from a direct proof for this cell:

![proofresult1](https://cloud.githubusercontent.com/assets/11355601/13187554/0a7b5dee-d74c-11e5-9c76-35d1cbf5a601.png)

And here the website incl. data - unfortunately, I cant upload a ZIP here (github says to chrome browser should possible, but does not work (MSG: "Unfortunately, we don’t support that file type.  Dateien auswählen Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.")) - so, all as .txt ...

File "Internet-Box plus.html":
[Internet-Box plus.txt](https://github.com/gorhill/uBlock/files/138631/Internet-Box.plus.txt)

File "Internet-Box plus_files\app.min.css":
[app.min.txt](https://github.com/gorhill/uBlock/files/138633/app.min.txt)

File "Internet-Box plus_files\core.min.js":
[core.min.txt](https://github.com/gorhill/uBlock/files/138634/core.min.txt)

File "Internet-Box plus_files\lib.min.js":
[lib.min.txt](https://github.com/gorhill/uBlock/files/138636/lib.min.txt)

**Comment by nick75e** [comment]
Hi!
If I may chime in, you can reproduce this bug with the [CUPS](http://localhost:631/) server.
![capture du 2016-02-22 20 41 40](https://cloud.githubusercontent.com/assets/10011516/13230350/4ba9739a-d9a5-11e5-9578-d6efd3fafd21.png)

I hope it helps!
uBO 1.6.1, Linux Mint 17.3

**Comment by gorhill** [comment]
Yes I can reproduce, thanks.

I did try `localhost` originally, but then I now realize I forgot to expand the list of hostnames.
