### ISSUE TITLE
UI not displayed in Google Chrome for Windows

### ISSUE THREAD

**Issue by davenorth** [gorhill/uBlock#1404]
Google Chrome for Windows Version 49.0.2623.54 beta-m (64-bit)
Windows 10

When I click the uBlock Origin toolbar button, no UI is visible - however, I can still click target elements on the UI, such as turning off uBlock Origin for a site.

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/17339878/13180132/7d410e4a-d6e4-11e5-8d9e-c09c9580a6a1.png)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. nobody can read your mind. Etc.

### Your settings

- Browser/version: 
- uBlock Origin version:

**Comment by gorhill** [comment]
The browser is responsible for displaying uBO's popup panel, so there is something wrong with the browser. See if this occurs with Chrome stable -- I was unable to reproduce with Chromium 48 or Chrome 50. You should report to Chromium devs.

**Comment by gorhill** [comment]
<https://bugs.chromium.org/p/chromium/issues/detail?id=518832>

Related?

**Comment by lewisje** [comment]
It shows up for me on Chrome Stable, then again both monitors are connected to one video card.

**Comment by davenorth** [comment]
Thanks for such a prompt reply. I started looking through the Chromium bug database and there are quite a few bugs indicating the same problem. The bug you reference is dead-on reproducible for me. If I open Chrome on a laptop with multiple monitors, and Chrome opens up on an external monitor - no popup is visible. If I drag Chrome to the laptop panel, the popup is visible -- and dragging back it remains visible.
