### ISSUE TITLE
Is it possible to use "redirect-resources" in a 3rd party filter?

### ISSUE THREAD

**Issue by CODYQX4** [gorhill/uBlock#1405]
### Describe the issue
I noticed uBlock has gained a "Script Surrogate" like feature where you can redirect scripts to modified, neutered versions.

Is it possible, if I wrote to the format currently used within uBlock, to save a file on my server and load it via Custom Filter Lists?

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
N/A

### Steps for anyone to reproduce the issue
N/A

### Your settings

- Browser/version: Chrome 48.0.2564.109
- uBlock Origin version: 1.6.2b0

##### Your filter lists
 My filters
 uBlock filters
 uBlock filters – Badware risks‎
 uBlock filters – Experimental
 uBlock filters – Privacy‎
 uBlock filters – Unbreak‎
Ads (4)
 Adblock Warning Removal List‎ 
 Anti-Adblock Killer | Reek‎
 EasyList
 Peter Lowe’s Ad server list‎
Privacy (3)
 Basic tracking list by Disconnect‎
 EasyPrivacy‎
 Fanboy’s Enhanced Tracking List‎
Malware domains (6)
 Malvertising filter list by Disconnect‎
 Malware Domain List‎ (malwaredomainlist.com)
 Malware domains‎ (www.malwaredomains.com)
 Malware domains (long-lived)‎ (www.malwaredomains.com)
 Malware filter list by Disconnect‎
 Spam404‎
Social (3)
 Anti-ThirdpartySocial
 Fanboy’s Annoyance List‎
 Fanboy’s Social Blocking List‎
Multipurpose (4)
 Dan Pollock’s hosts file‎
 Fanboy+Easylist-Merged Ultimate List
 hpHosts’ Ad and tracking servers‎
 MVPS HOSTS‎

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
`redirect-resources.txt` is obsolete, use `resources.txt`.

Yes, you can use entries from `resources.txt` in any filter.

**Comment by IDKwhattoputhere** [comment]
@CODYQX4  Maybe I'm wrong but is this what you mean? https://github.com/gorhill/uBlock/issues/1364
