### ISSUE TITLE
Please add these three filters by default if possible

### ISSUE THREAD

**Issue by Hongbo-Miao** [gorhill/uBlock#1406]
If possible, please add these three main famous filters for Chinese website by default, thanks!
Right now built-in filters do work, but not "really" work. For example, [this one](http://bbs.feng.com/read-htm-tid-7453529.html).

https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
http://sub.adtchrome.com/adt-chinalist-easylist.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

After adding these three, it has a big difference for most Chinese websites.

**Comment by gorhill** [comment]
1st and 3rd ones are already in there. Second one is no longer maintained, last update was two years ago.

**Comment by Hongbo-Miao** [comment]
@gorhill sorry, the first one I added by mistake, not for Chinese websites. I just saw third one.
thanks anyway!

**Comment by gorhill** [comment]
Actually my mistake, I realize that the 3rd ones is not listed in uBO, the one listed is rather `cjxlist.txt`, not `cjx-annoyance.txt`.

**Comment by Hongbo-Miao** [comment]
cjxlist.txt and cjx-annoyance.txt seem having same effect after I tested those websites.

**Comment by gorhill** [comment]
Looks likes most of `cjxlist.txt` (except for 7 filters) is found in EasyList. Content of `cjx-annoyance.txt` is unique though, except for one filter.

**Comment by Hongbo-Miao** [comment]
that is cool. haha
