### ISSUE TITLE
Hide adblock detection

### ISSUE THREAD

**Issue by vendforce** [gorhill/uBlock#1407]
Is there any way to hide the detection of adblock orgin
There is some websites that detect theres an ad blocker and wont play the video
sites like

# www.channel4.com/programmes/catchup
# www.bbc.co.uk/iplayer

So What Im looking to do is block the ads before the programmes but hide the fact theres an ad blocker from the site, as when it detects the adblocker it wont play the content and Im forced to disable the adblocker and watch the adverts which are not only at then start but when there is ad breaks between the program which is very annoying

#### Configuration
- Browser/version: Firefox 44.0.2-1
- uBlock Origin version: 16.1
- OS : arch 
- DE:  gnome-shell

##### Filter lists
Default selected

**Comment by Azuok** [comment]
Adblock detection on 
http://www.footstream.tv/

**Comment by vendforce** [comment]
Thank you for your solution, but Im looking for a solution for certain websites

**Comment by lewisje** [comment]
I have posted many times on the ABP forums on this issue, and this is a particularly thorough write-up: https://adblockplus.org/forum/viewtopic.php?p=143825#p143825

The TL;DR is that code on the page can't detect ad-blockers directly: Instead it detects whether certain content was blocked or hidden and infers the presence of an ad-blocker, and an extension can't trick the JS engine into lying about the state of the page.

**Comment by vendforce** [comment]
Is there nothing that be done ? 

Im starting to see a lot of sites now blocking all content and forcing you to disable your adblocker so you can view the webpage or content, Its a bit pointless having an adblocker if you have to disbale it to view pages

http://www.avaxhome.co/ is one of thoses sites and Ive come across many more the list is starting to grow

**Comment by RoxKilly** [comment]
I'm almost never stopped by this problem. If you do the following you will be fine on most websites.
1) If you use uBO with advanced settings, disable 1st-party and inline javascript.  A lot of these sites rely on javascript to test for adblocking. To do so, open the uBO panel dynamic filters and make sure the inline-script and 1st-party scripts rows are red.  The left column will affect all sites. The right column is for the current site (if set, it overrides the left column)
![1](https://cloud.githubusercontent.com/assets/12346501/13227396/769af506-d964-11e5-81df-24455feeaa6d.png)


2) Use [Reek's Anti-Adblock Killer](https://github.com/reek/anti-adblock-killer#instruction).  This is really effective even without no.1 above. It basically injects custom filters and javascript unto pages to disarm the adblock detectors

**Comment by IDKwhattoputhere** [comment]
Anti-Adblock Killer is great. Make sure to closely follow the [instructions](https://github.com/reek/anti-adblock-killer#instruction).
Often simply disabling element hiding and allowing the current domain through dynamic filtering helps. Or do as @RoxKilly said and block scripts until you get the desired result.

**Comment by vendforce** [comment]
Thanks  guys ..

**Comment by Azuok** [comment]
Adblock detected http://www.programmes-cinema.com/publicite.html

**Comment by gorhill** [comment]
Please, all filter list issues need to be reported to filter list maintainers.

This just confirms that if I care to look into one issue, it sends the signal that I will look into all issues reported. Maybe one day I will become a filter list maintainers, but this is not the case now, and that would be a separate project anyways.

**Comment by IDKwhattoputhere** [comment]
@Azuok At least try what has been suggested before requesting help.
