### ISSUE TITLE
[not issue] Question << in the logger

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uBlock#1408]
![default](https://cloud.githubusercontent.com/assets/15322618/13197907/94491974-d825-11e5-91c9-cf98a5d64997.PNG)
What does it `<<` mean? What does the whole yellow string mean?
I don't find anything about it at https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by kowith337** [comment]
It's mean the GA script was redirected to the uBlock Resource, neutured script was do nothing (noop), don't worry (Same question as #1374)

**Comment by jhsagl4a** [comment]
>GA script was redirected
But that script didn't load.

**Comment by CrisBRM** [comment]
>But that script didn't load.

Yes, for the redirect feature to work, the script must be blocked.
