### ISSUE TITLE
Remove SourceForge from Badware risks filterlist

### ISSUE THREAD

**Issue by anonsubmitter** [gorhill/uBlock#1409]
[Since SourceForge switched owners they have scrapped the malware infested installers](https://sourceforge.net/blog/sourceforge-acquisition-and-future-plans/) and no longer inject malware into downloads I think that it should be removed from the Badware risks filterlist.

[Here](https://www.virustotal.com/en/file/0af7f25a4898249a6dbaa9d2cdf67f9b030e64bac09fc113431787b47ba6bfdf/analysis/1456053123/) is a VirusTotal scan I ran on the Windows installer for FileZilla 3.15.0.2 64-bit from SourceForge and it's clean (0/55 detection ratio).

**Comment by vendforce** [comment]
I wouldnt recommend that just yet, It took them an awful long time to reverse there decision , only because that it may be hurting them now, But I wouldnt trust them just yet I'd leave it for year to see do they keep to there promise's

**Comment by gorhill** [comment]
Duplicate of #1371.
