### ISSUE TITLE
Tweet button is blocked

### ISSUE THREAD

**Issue by mholt** [gorhill/uBlock#141]
Actual behavior:

The Tweet button on Twitter is gone.

Expected behavior:

The Tweet button on Twitter is visible.

Current workaround:

Disabling uBlock on Twitter causes the Tweet button to re-appear.

**Comment by gorhill** [comment]
Unable to reproduce following the above repro steps. Will close after one day if no more details is provided.

**Comment by mholt** [comment]
Using 0.9.4.4. 

Without uBlock, Tweet button (the one in the top bar, for instance) has this markup:

```html
<button id="global-new-tweet-button" type="button" class="js-global-new-tweet js-tooltip btn primary-btn tweet-btn js-dynamic-tooltip" data-placement="bottom" data-component-term="new_tweet_button">
                  <span class="Icon Icon--tweet Icon--large"></span>
                  <span class="text">Tweet</span>
                </button>
```

With it,

```html
<button id="global-new-tweet-button" type="button" class="js-global-new-tweet js-tooltip btn primary-btn tweet-btn js-dynamic-tooltip" data-placement="bottom" data-component-term="new_tweet_button" style="display: none !important;">
                  <span class="Icon Icon--tweet Icon--large"></span>
                  <span class="text">Tweet</span>
                </button>
```

Notice the `display: none !important`. Seems to do the same for all other Tweet buttons.

Here's a screenshot of my Twitter feed with dev tools open:

![Missing tweet button](https://cloud.githubusercontent.com/assets/1128849/7352048/607b1016-ecc6-11e4-9f7a-103121e88989.png)

Hope that helps somewhat.

**Comment by Betsy25** [comment]
Can you post a screenshot of which 3rd party lists are checked ?

**Comment by mholt** [comment]
Is this what you wanted?

![screen shot 2015-04-27 at 10 26 16 am](https://cloud.githubusercontent.com/assets/1128849/7352288/e81d9ba0-ecc7-11e4-9e80-eebd981a434c.png)

"My filters" didn't have anything in there for Twitter; and the rest below the fold were all unchecked.

**Comment by gorhill** [comment]
Probably a filter list issue. This was added to Fanboy Social 9 hours ago:

    https://hg.adblockplus.org/easylist/rev/633d5b637619

So purge cache for Fanboy Social, for an update, and see if this fixes the issue.

**Comment by mholt** [comment]
Ah, good find. That did the trick - thanks!

**Comment by gorhill** [comment]
Just a hint regarding this. Instead of turning off completely uBlock, you can toggle the cosmetic filtering switch to un-hide DOM elements hidden by uBlock on the page. It's a less drastic workaround than turning off uBlock completely.
