### ISSUE TITLE
Some ads not blocked / changed to plain text address

### ISSUE THREAD

**Issue by exodius48** [gorhill/uBlock#1410]
### When i access web, (almost ppc site), then i click download button ., it redirect automatically to plain address: 

data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD53aW5kb3cubG9jYXRpb249Imh0dHBzOi8vcmV2Y2xvdWRzLmNvbS9jNno1ZXpoeHBrMXEiOzwvc2NyaXB0PjwvYm9keT48L2h0bWw+

Then it load ads / redirect to another web

### Steps for anyone to reproduce the issue

Visit site above, then wait load done, then click download (green button) , don't forget to uncheck download with accelerator if any

### Your settings

- Browser/version: Firefox 44.0.2
- uBlock Origin version: 1.6.1

##### uBlock filters‎ 
uBlock filters – Badware risks‎ 
uBlock filters – Experimental‎ 
uBlock filters – Privacy‎ 
uBlock filters – Unbreak‎ 
Adblock Warning Removal List‎ 
Anti-Adblock Killer | Reek‎ 
EasyList
EasyList without element hiding rules‎ 
Peter Lowe’s Ad server list‎ 
Basic tracking list by Disconnect‎
EasyPrivacy
Fanboy’s Enhanced Tracking List‎ 
Malvertising filter list by Disconnect‎ 
Malware Domain List‎ 
Malware domains‎ 
Malware domains (long-lived)‎ 
Malware filter list by Disconnect‎ 
Spam404‎ 
Anti-ThirdpartySocial
Fanboy’s Annoyance List‎
Fanboy’s Social Blocking List‎ 
Dan Pollock’s hosts file‎
Fanboy+Easylist-Merged Ultimate List‎
hpHosts’ Ad and tracking servers
MVPS HOSTS
ara: Liste AR‎ 
ara: Liste AR 
BGR: Bulgarian Adblock list‎ 
CHN: CJX's Annoyance List‎ 
CHN: CJX's EasyList Lite
CHN: EasyList China 
IDN: ABPindo‎ 
ISR: EasyList Hebrew‎
JPN: ABP Japanese filters
KOR: Fanboy's Korean‎
KOR: Korean Adblock List
KOR: YousList‎
RUS: Adguard Russian Filter‎
RUS: BitBlock List 
RUS: RU AdList
VIE: Fanboy's Vietnamese‎

**Comment by gorhill** [comment]
It's just a filter issue, not a uBlock Origin issue. Try:

    ||data.cytochemistryrecitativewrasse.com^$popunder,domain=revclouds.com

Filter issues should be reported [there](https://github.com/IDKwhattoputhere/uBlock-Filters-Plus), not here.
