### ISSUE TITLE
Links opening with linkr.us 

### ISSUE THREAD

**Issue by aaburlaka** [gorhill/uBlock#1411]
I found that some links opens with linkr.us and then redirects to right address. Reddit users noticed the same and found that this was caused by uBlock original extension. Can you explain this behavior? 
I have uBlock Origin v1.6.0

https://www.reddit.com/r/chrome/comments/445wf8/chrome_forwarding_links_through_linkrus/?sort=old

http://i.imgur.com/lBhUOQO.jpg

**Comment by gorhill** [comment]
uBlock Origin has nothing to do with `lnkr.us`.

What are your other extensions/apps installed? You should also run malware/adware cleaner: [try step 4+](http://decentsecurity.com/holiday-tasks/).

**Comment by gorhill** [comment]
Given the comment from OP in the redddit thread:

> I notice that my address bar briefly has a "linkr.us" address in it

I will add `linkr.us` to the blocked hostname in uBlock filters. This will help users to become aware that they have a badware issue which needs attention.

**Comment by aaburlaka** [comment]
I apologize for the false accusations. I inspected the code of page which send me to lnkr.us and found the code was implemented to extension `jljdjlfhoioookcfbhfmeagkihpniglj` by a third-party partner. Now I blocked the site partner `metrext.com`. I consider that they violate users' privacy by collecting statistics. I suppose the rule `||metrext.com^$document` should be applied for all.
http://imgur.com/L6bl6EJ

**Comment by gorhill** [comment]
Thanks for the finding re. `metrext.com`, I added it to uBO's _Privacy_ filter list -- that domain name is an alias of `icontent.us`.

**Comment by e271828-** [comment]
@gorhill From a quick search this metrext.com entity has many domains in use. For example:

icontent.us
ratexchange.net
trendtext.eu
adnotbad.com
adserv.info
serverads.net
jsfuel.com
spaceshipad.com
takethatad.com
tradeadsexchange.com

They should probably all be blocked.

Their script at http://metrext.com/addons/lnkr15.min.js includes an exclusion list.

Presumably they're the beneficiaries of the link skimming service. 

It would be useful to find a way to penalize such companies if they fail to police their affiliate programs, perhaps by having uBlock throw up an interstitial saying they support badware.

As of 24-03-2016:

"aliexpress.com", "booking.com", "centauro.com.br", "choies.com", "dafiti.com.br", "dinodirect.com", "kanui.com.br", "lenovo.com", "netshoes.com.br", "newfrog.com", "rihappy.com.br", "romwe.com", "sapato.ru", "tomtop.com", "zocprint.com.br", "delivery-club.ru", "quelle.ru", "mytoys.ru", "rencredit.ru", "tcsbank.ru", "svyaznoy.ru", "butik.ru", "alltime.ru", "kupivip.ru", "moneyman.ru", "onedate.com", "uselets.com.br", "walmart.com.br", "clickbus.com.br", "dafitisports.com.br", "epocacosmeticos.com.br", "livrariasaraiva.com.br", "lojaskd.com.br", "natue.com.br", "nike.com.br", "polishop.com.br", "posthaus.com.br", "sandromoscoloni.com.br", "sepha.com.br", "shopfato.com.br", "usehuck.com.br", "banggood.com", "casualclub.com", "dx.com", "dafiti.com.co", "lamoda.ru", "laredoute.ru", "marisa.com.br", "plarium.com", "warframe.com", "003.ru", "allbags.com.br", "amazonkashtan.com", "amissima.com.br", "amomuito.com", "aqua-gel.ru", "astro7.ru", "audiomania.ru", "babadu.ru", "beauty-shop.ru", "bebakids.ru", "bestwatch.ru", "boffo.ru", "brain.com.ua", "bt.kiev.ua", "capitollium.com.br", "centralfit.com.br", "chocomart.kz", "cigabuy.com", "compremarcas.com", "condom-shop.ru", "constance.com.br", "deshevshe.net.ua", "dochkisinochki.ru", "e-lens.com.br", "ebaysocial.ru", "eco-energy.me", "ecofuel.me", "ecowater.me", "eldorado.com.ua", "electra-box.ru", "elitdress.ru", "eshop24.com.br", "extremelife.com.br", "fallostone-plus.ru", "fallostone.ru", "fame.ua", "fellipekrein.com.br", "fotomag.com.ua", "fotosklad.ru", "frenza.ru", "gamazavr.ru", "hilt.com.ua", "i-lux.ru", "igromagaz.ru", "inksystem.biz", "intermarket.kz", "israelbooking.ru", "kolgot.net", "krest-torreto.ru", "lacywear.ru", "lamoda.kz", "litres.ru", "logovia.com.br", "lojadointer.com.br", "lojadoprazer.com.br", "lojanba.com", "lojasrenner.com.br", "lucky-print.com.ua", "macov.net", "madrobots.ru", "matrix.ua", "mebelion.ru", "meuespelho.com.br", "micromaxstore.ru", "mojos.ru", "molot-tor.ru", "mond-sub.ru", "multistock.com.br", "multivarka.pro", "mundopalmeiras.com.br", "mvideo.ru", "n-store.ru", "nano-slim.ru", "nazya.com", "netbabys.com.br", "netprint.ru", "neweracap.com.br", "nokiastore.kz", "notik.ru", "ogo1.ru", "oldi.ru", "onlinetours.ru", "organizeshop.com.br", "ozon.ru", "petnanet.com.br", "pharmacosmetica.ru", "pleer.ru", "poemese.com", "power-braselet.ru", "powerlifes.com", "preta.com.ua", "printclick.ru", "proball.ru", "proskater.ru", "pudra.ru", "pult.ru", "redcube.ru", "redmondshop.com", "saopaulomania.com.br", "savage.ru", "sensorella.com.br", "sexy-lips.ru", "shopotam.ru", "shopozz.ru", "shoptimao.com.br", "showrooms.ru", "softkey.ru", "spina-pro.ru", "sportgrad.ru", "stolplit.ru", "tanuki.ru", "tehnosila.ru", "terrasport.ua", "thenorthface.com.br", "timberland.com.br", "tinydeal.com", "titanic-kulon.ru", "tktimport.com", "tops.com.ua", "travelata.ru", "trendsbrands.ru", "ufcstore.com.br", "usereserva.com", "valgys.ru", "vamsvet.ru", "viladosantos.com.br", "wqsurf.com.br", "zattini.com.br", "zerosmoke.ru", "abbelt.ru", "biletix.ru", "city.travel", "clockshop.ru", "diior.ru", "domatv.ru", "g-shock.original-watchs.ru", "icover.ru", "just.ru", "kotofoto.ru", "loja.compracerta.com.br", "loja.mizunobr.com.br", "mamagazin.ru", "mnogomeb.ru", "moysklad.ru", "mrdom.ru", "nils.ru", "poll.polltopay.com", "rbt.ru", "roquenrou.com", "s-shina.ru", "salomaocountry.com.br", "shop.bork.ru", "shop.the-alba.com", "sofiabyvix.com.br", "vseinstrumenti.ru", "wer.ru", "4slovo.ru", "baonshop.ru", "bm.ru", "crisis-game.ru", "fingooroo.ru", "foxford.ru", "moymir.ru", "mti.edu.ru", "oneclickmoney.ru", "payps.ru", "psbank.ru", "railnation.ru", "smsfinance.ru", "zaymiprosto.ru", "colcci.com.br", "forum.com.br", "nicephotos.com.br", "sommerland.com.br", "supermuffato.com.br", "triton.com.br", "cissamagazine.com.br", "colombo.com.br", "botoskin.com.br", "astrolords.ru", "mlgame.ru", "atlasformen.ru", "clasno.com.ua", "eapteka.ru", "gold.ua", "magiadigamma.ru", "pichshop.ru", "piluli.ru", "sendflowers.ru", "tom-tailor-online.ru", "yakaboo.ua"

**Comment by gorhill** [comment]
> From a quick search this metrext.com entity has many domains in use

How did you find these other domains?

**Comment by e271828-** [comment]
@gorhill Replied via email.

**Comment by LimboSlam** [comment]
Nice to see someone brought this up. So what this new fix in place, will there be a need to block this tracker/website globally?
