### ISSUE TITLE
Inline style with 'important!' overriding  rules

### ISSUE THREAD

**Issue by kilotaras** [gorhill/uBlock#1412]
### Describe the issue
Elements that have inline style with `!important` are displayed.

### One or more specific URLs where the issue occurs
https://vk.com/feed (have to log in though)

### Screenshot in which the issue can be seen
http://i.imgur.com/pUpY4B4.png
http://i.imgur.com/9gbmFAk.png
http://i.imgur.com/Mqmqh7k.png

### Steps for anyone to reproduce the issue
0. Add `vk.com##.ads_ads_box` rule
1. Go to vk.com
2. login
3. Ad block on left side is displayed

### Your settings
- Browser/version: Firefox 44
- uBlock Origin version: 1.6.1

##### Your filter lists
RUS: RU AdList that has `vk.com##.ads_ads_box` in it

##### Your custom filters (if any)
`vk.com##.ads_ads_box`

**Comment by gorhill** [comment]
Duplicate of #963.

I will try to work on this for next release.

**Comment by kilotaras** [comment]
Thanks, closing this.

**Comment by gorhill** [comment]
Note: this may not occur with Chromium because it makes use of shadow nodes. If one feels like experimenting, this can be enabled in Firefox by setting `dom.webcomponents.enabled` to `true` in `about:config`.

**Comment by kilotaras** [comment]
Setting `dom.webcomponents.enabled` to `true` fixes the issue.
