### ISSUE TITLE
[Firefox] error downloading + add-on appears corrupt

### ISSUE THREAD

**Issue by 5t3f4n** [gorhill/uBlock#1413]
Attempting to update from 1.6.1 to 1.6.2 gives the follow errors:

When attempting to update through`about:addons`:
![1](https://cloud.githubusercontent.com/assets/11399326/13229614/2dc4a410-d9a2-11e5-9aeb-02f203ad52c0.png)

When attempting to install directly from AMO:
![2](https://cloud.githubusercontent.com/assets/11399326/13229668/5b5b75c0-d9a2-11e5-840e-b336d55031be.png)

`Firefox 44.0.2`
`uBlock Origin 1.6.1`
`OS X 10.11.3 (15D21)`

**Comment by gorhill** [comment]
Report to FF please, I don't have any control over FF servers.

**Comment by 5t3f4n** [comment]
Well I wasn't sure if it was a problem with AMO or if it was, in fact, corrupt. I already checked [here](https://status.mozilla.org/) before opening the issue and everything looked fine. Can you confirm the integrity of it or should I install from GitHub for the time being?

**Comment by IDKwhattoputhere** [comment]
Both, downloading from AMO and through about:addons, works fine for me with Firefox 44.0.2 on Windows 7. Must be either on your side or a problem with some AMO servers.

**Comment by gorhill** [comment]
Possibly duplicate of #1373?

It appears that depending on your location, there might be one AMO server which is hosting non-signed version of uBO.

**Comment by 5t3f4n** [comment]
Possibly. I think we can rule out problems on my end since other extensions including uMatrix works fine, and we can rule out uBlock Origin itself being the problem since it works for other people. So the location issue seems plausible.

But if the problem is that they're serving a non-signed copy, shouldn't the error message be more similar to the one you get when installing from [here](https://github.com/gorhill/uBlock/releases)? Even with unsigned extensions enabled I cannot install from AMO.

**Comment by gorhill** [comment]
_Maybe_ related bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1249402#c2

**Comment by git-in-my-anus** [comment]
Having the same issue as OP.
Other add-ons are updating and being installed fine.

Is it possible to install uBlock from github releases and receive updates from AMO later?

**Comment by gorhill** [comment]
> Is it possible to install uBlock from github releases

No, signed extensions can only be hosted on AMO. I have no clue why this happens, I merely upload the package to AMO, AMO signs it then distribute it. Best is to report the issue to AMO so that they look into this, what AMP serves is out of my control.

**Comment by 5t3f4n** [comment]
Seem like Mozilla have fixed whatever the issue was.

**Comment by krystian3w** [comment]
Test
