### ISSUE TITLE
Blocking Intercom

### ISSUE THREAD

**Issue by timolson** [gorhill/uBlock#1415]
uBlock 1.6.0 on Mac/Chrome blocks the Intercom chat service.  Our ecommerce website is using it legitimately for customer support, so I was wondering if this is some kind of uBlock policy?  Intercom is not an ad service AFAIK, so… why is it in the filter list?  Our customers are unable to reach our support line.

**Comment by timolson** [comment]
The block rule is in `EasyPrivacy.txt`:
`api-ping.intercom.io^`

**Comment by gorhill** [comment]
EasyPrivacy is 3rd-party to uBO, it's a community-maintained filter list. You need to report any issue to the maintainers of EasyPrivacy: <https://forums.lanik.us/viewforum.php?f=64>.
