### ISSUE TITLE
Unable to install on Firefox for Android

### ISSUE THREAD

**Issue by ristokoo** [gorhill/uBlock#1416]
### Describe the issue
The new version 1.6.2 won't install. Installing version 1.6.2b0 is succesful.
Firefox error message:
The add-on from addons.mozilla.org could not be installed because it does not match the add-ons Firefox expected.

### Steps for anyone to reproduce the issue
Try to install uBlock Origin version 1.6.2 on Firefox Android.

### Your settings
- Browser/version: Firefox 44.0.2
Android 5.1.1 (CyanogenMod 12.1)

- uBlock Origin version: 1.6.2

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1373

**Comment by ristokoo** [comment]
Thanks! Sorry I missed that, checked back for a couple of weeks but the headline of #1373 isn't exactly very descriptive;)

**Comment by gorhill** [comment]
Dup of #1373.

_Maybe_ related bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1249402#c2
