### ISSUE TITLE
Filter misinterpretation?

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#142]
A filter<sup>[1]</sup> in EasyList seems to be interpreted differently in uBlock, compared to Adblock Plus.  This causes this<sup>[2]</sup> request to be blocked on [this page](https://au.tv.yahoo.com/plus7/waking-the-dead/-/watch/27359504/) (will only load within Australia, due to region-locking).

According to the network request log, the filter is converted to `doubleclick.net$domain=yahoo.com`. It seems like it should be `||doubleclick.net^$domain=yahoo.com`, but when I added that to my custom filters and disabled all other filter lists (for testing), the log still showed that request being blocked as `doubleclick.net$domain=yahoo.com`.

Browser info: Firefox 38b6, uBlock Origin 0.9.5.0

---

<sup>[1]</sup> `||doubleclick.net^$third-party,domain=3news.co.nz|92q.com|abc-7.com|addictinggames.com|allbusiness.com|allthingsd.com|bizjournals.com|bloomberg.com|bnn.ca|boom92houston.com|boom945.com|boomphilly.com|break.com|cbc.ca|cbs19.tv|cbs3springfield.com|cbsatlanta.com|cbslocal.com|complex.com|dailymail.co.uk|darkhorizons.com|doubleviking.com|euronews.com|extratv.com|fandango.com|fox19.com|fox5vegas.com|gorillanation.com|grooveshark.com|hawaiinewsnow.com|hellobeautiful.com|hiphopnc.com|hot1041stl.com|hothiphopdetroit.com|hotspotatl.com|hulu.com|imdb.com|indiatimes.com|indyhiphop.com|ipowerrichmond.com|joblo.com|kcra.com|kctv5.com|ketv.com|koat.com|koco.com|kolotv.com|kpho.com|kptv.com|ksat.com|ksbw.com|ksfy.com|ksl.com|kypost.com|kysdc.com|live5news.com|livestation.com|livestream.com|metro.us|metronews.ca|miamiherald.com|my9nj.com|myboom1029.com|mycolumbusmagic.com|mycolumbuspower.com|myfoxdetroit.com|myfoxorlando.com|myfoxphilly.com|myfoxphoenix.com|myfoxtampabay.com|nbcrightnow.com|neatorama.com|necn.com|neopets.com|news.com.au|news4jax.com|newsone.com|nintendoeverything.com|oldschoolcincy.com|own3d.tv|pagesuite-professional.co.uk|pandora.com|player.theplatform.com|ps3news.com|radio.com|radionowindy.com|rottentomatoes.com|sbsun.com|shacknews.com|sk-gaming.com|ted.com|thebeatdfw.com|theboxhouston.com|theglobeandmail.com|timesnow.tv|tv2.no|twitch.tv|universalsports.com|ustream.tv|wapt.com|washingtonpost.com|wate.com|wbaltv.com|wcvb.com|wdrb.com|wdsu.com|wflx.com|wfmz.com|wfsb.com|wgal.com|whdh.com|wired.com|wisn.com|wiznation.com|wlky.com|wlns.com|wlwt.com|wmur.com|wnem.com|wowt.com|wral.com|wsj.com|wsmv.com|wsvn.com|wtae.com|wthr.com|wxii12.com|wyff4.com|yahoo.com|youtube.com|zhiphopcleveland.com`

<sup>[2]</sup> `https://secure.brightcove.com/services/viewer/federated_f9?&width=100%25&height=281&flashID=brightcove_player27359504_plyr&isUI=true&isVid=true&autoStart=true&playerKey=AQ~~%2CAAACKW9LG-E~%2CUJVysOuwpLSTwV9EBab-3q-xJRGA2_qN&includeAPI=true&dynamicStreaming=true&showNoContentMessage=true&bgcolor=%23FFFFFF&wmode=opaque&%40videoPlayer=ref%3A27359504&linkBaseURL=https%3A%2F%2Fau.tv.yahoo.com%2Fplus7%2Fwaking-the-dead%2F-%2Fwatch%2F27359504%2F&playerID=2779795865001&adServerURL=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D400x300%26iu%3D%2F58250233%2Ftv%2Fplus7%2Fwaking-the-dead%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast3%26unviewed_position_start%3D1%26url%3Dhttps%3A%2F%2Fau.tv.yahoo.com%2Fplus7%2Fwaking-the-dead%2F-%2Fwatch%2F27359504%2F%26correlator%3D1430158043%26cmsid%3D513&templateLoadHandler=BCVideoPlayer.onPlayerLoaded&templateErrorHandler=BCVideoPlayer.onPlayerError&secureConnections=true&secureHTMLConnections=true&debuggerID=&startTime=1430158088841`

**Comment by gorhill** [comment]
Confirmed. Will fix asap.

**Comment by One23** [comment]
Thank you!  Confirmed working with 0.9.5.1-dev.5.
