### ISSUE TITLE
[Chrome] Stopped working, GUI bugged

### ISSUE THREAD

**Issue by andreasf93** [gorhill/uBlock#1420]
I believe no explanation is needed, here is a screenshot: ![](https://i.imgur.com/zXQRIFP.jpg)

**Comment by gorhill** [comment]
Try disabling/enabling the uBlock Origin in the _Extensions_ page. Report result.

**Comment by andreasf93** [comment]
Nothing happened. Options link shows this: https://i.imgur.com/wuKNxPe.png

**Comment by gorhill** [comment]
It's as if uBO's javascript is not being executed. Open uBO's dev console and see if there are any error messages:
![](https://cloud.githubusercontent.com/assets/585534/10864111/0a9cf23c-7fb9-11e5-83c0-97bc3f143849.png)

**Comment by andreasf93** [comment]
https://i.imgur.com/p7mAOHA.png

**Comment by gorhill** [comment]
That answers the question: all uBO's javascript files are no longer in there. Now you have to find out why -- it's not uBO, it does not have the power to access the file system.

**Comment by andreasf93** [comment]
I checked my %AppData% and couldn't find the mentioned js folder. Removed and re-added the extension and the folder is back again. This is so weird. Thankfully I've had backups of my lists. Thanks for your support!

**Comment by gorhill** [comment]
You should really look into what removed that folder, this is not supposed to happen. Maybe a cleaner/antivirus? If ever you find the cause, would be nice to add info here in case somebody else suffers same issue.

**Comment by andreasf93** [comment]
I doubt I will figure how it happened. My first thought was a virus, but I'm always very careful. I also use Malwarebytes but I don't think it would touch Chrome extensions.
