### ISSUE TITLE
Additional AdDefend / Yavli sites

### ISSUE THREAD

**Issue by haarp** [gorhill/uBlock#1421]
Firefox 44, Ublock0 1.6.2, the following AdDefend sites are missing in the extension's own filter list:

- notebookcheck.com (they have multiple TLDs)
- www.winboard.org

This site has recently started using Yavli (I think, the defacer script at the bottom of the html body mentions exactly0r.com, which seems to be Yavli):

- dilbert.com

Also, the filter list is now using uabinject-defuser.js and similar snippets. Is this the preferred way of dealing with these now? I remember that it was script:contains() at some point. Wouldn't blocking the defacer scripts completely be more efficient?

**Comment by gorhill** [comment]
Thanks for reporting.
