### ISSUE TITLE
Block Adblock detectors like the one found here

### ISSUE THREAD

**Issue by X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-XX** [gorhill/uBlock#1422]
Sorry for the poor formatting.

Block Adblock detectors like the one found here:

Webpage: www.droidextra.net/solved-fix-adb-devices-offline-100-working/

Image:
https://i.imgur.com/Oq6wPIQ.png

**Comment by gorhill** [comment]
It's a filter issue, [just report to EasyList](https://forums.lanik.us/viewforum.php?f=62): `@@||droidextra.net^$generichide`.
