### ISSUE TITLE
jeux.com

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#1423]
Hi,
Ad banners and popup via inline script on `http://www.jeux.com/flash/smarty-bubbles-8981.html`

base64 inline script http://nopaste.linux-dev.org/?954229&download
base64 popup http://nopaste.linux-dev.org/?954250&download

- Browser/version: firefox 44.0.2 
- uBlock Origin version: v1.6.2

Thanks!

**Comment by RoxKilly** [comment]
uBlock doesn't block ads itself, so your report is misplaced. It just runs the rules provided by 3rd party filters. If you'd like to see ads blocked, the place to report them is with the filter authors. The biggest of these is EasyList.  Below are the instructions from the EasyList [website](https://easylist.adblockplus.org/en/):
> If you should encounter unwanted items or problems with the EasyList subscriptions you should report the issues in the [EasyList Forums](http://forums.lanik.us/). No registration is required

**Comment by gorhill** [comment]
There is something to look into here: I have to investigate if the `data:` URI popup can be handled by uBO.

**Comment by SMed79** [comment]
https://github.com/gorhill/uBlock/issues/1340
