### ISSUE TITLE
video (html5)/brightcove player not loading 

### ISSUE THREAD

**Issue by Snow8** [gorhill/uBlock#1424]
### Describe the issue
Instead of showing the player and its controls to start the video, a gray box is shown with the player controls as simply text that cannot interact with.

### One or more specific URLs where the issue occurs
This is just one example but this happens on every page that uses the brightcove player for me:

http://www.zeit.de/politik/deutschland/2016-02/baden-wuerttemberg-afd-podiumsdiskussion

### Screenshot in which the issue can be seen
http://imgur.com/Ha1vfEu

I highlighted the text within the player manually.

### Steps for anyone to reproduce the issue

go to webpage, player not loading

### Your settings

- Browser/version: Firefox Dev Edition v 46, Google Chrome current Stable (v48?)
- uBlock Origin version: 1.6.2

##### Your filter lists
- uBlock Filters except Experimental
- Ads Filters except EasyList without element hidiing
- EasyPrivacy and Fanboys Enhanced
- Malware Domain List, Malware Domains, Spam404
- All Social Lists
- EasylistGermany
- EU: Prebake
- Fanboy+Easylist Merged
- hpHosts Ad

##### Your custom filters (if any)
||google-analytics.com^$third-party
||gravatar.com^$third-party
||platform.twitter.com/widgets.js$third-party
||facebook.com^$third-party
||facebook.net^$third-party
||linkedin.com^$third-party,important

||images-amazon.com$object,domain=amazon.ca
||images-amazon.com$object,domain=amazon.co.uk
||images-amazon.com$object,domain=amazon.co.jp
||images-amazon.com$object,domain=amazon.de
@@||images-amazon.com/images/*/video$object,domain=amazon.com
@@||images-amazon.com/*.mp4$object,domain=amazon.com
@@||images-amazon.com/images/*/video$object,domain=amazon.de
@@||images-amazon.com/*.mp4$object,domain=amazon.de

For advanced settings I have the following permanent rules set regarding this issue:

* * 3p-frame block
* brightcove.net * allow

**Comment by okiehsch** [comment]
You can see that the static filter
||brightcove.vo.llnwd.net^
prevents the player loading the video.

![aufzeichnen1](https://cloud.githubusercontent.com/assets/16838044/13314455/8c69c9a0-dba5-11e5-8ea3-de6c6d23f431.PNG)

If you disable the -hpHosts list the video plays just fine.

**Comment by Snow8** [comment]
hmm... this does not work for me. I disabled your suggested static filter list, and the player still does not load. :(

I disabled all static filter lists except the standard ones and it does not work for me :(

**Comment by okiehsch** [comment]
Open the logger, look for all entries starting with
http://brightcove.vo.llnwd.net
is any of them blocked, if yes which list blocks them if no
the video should play.
![aufzeichnen12](https://cloud.githubusercontent.com/assets/16838044/13316042/61379ae2-dbae-11e5-9c4e-48e88973797e.PNG)

**Comment by Snow8** [comment]
hmm, none of the entries you are mentioning are showing up... all i have are those brightcove entries you see below...
![logger](https://cloud.githubusercontent.com/assets/11486958/13316847/2eff869e-dbb2-11e5-926c-48d6101285ce.png)

**Comment by okiehsch** [comment]
Can you open this link?
http://players.brightcove.net/18140073001/c09a3b98-8829-47a5-b93b-c3cca8a4b5e9_default/index.html?videoId=4769554863001&wmode=transparent&preload=none

after you click play your logger should look like this.
![aaufzeichnen](https://cloud.githubusercontent.com/assets/16838044/13317747/0adb37ea-dbb7-11e5-997c-79cf8131086b.PNG)

**Comment by Snow8** [comment]
yes I can open the link.
![logger](https://cloud.githubusercontent.com/assets/11486958/13318146/4c2e4104-dbb9-11e5-8a89-93243d623377.png)
![video](https://cloud.githubusercontent.com/assets/11486958/13318147/4c2fec3e-dbb9-11e5-935d-9bf1745d02b2.png)

The video shows and plays fine. Why does it not load then on the "original" website...

**Comment by gorhill** [comment]
The video does not play even without uBO -- that is the first ting to try.

The site requires that 3rd-party cookies are allowed.
