### ISSUE TITLE
Unbreak filter to unbreak getsatisfaction.com's stylesheet and images (hpHosts ATS filter)

### ISSUE THREAD

**Issue by AmperAndSand** [gorhill/uBlock#1425]
Getsatisfaction.com doesn't properly load its stylesheet and other assets like some images if subscribed to hpHosts’ Ad and tracking servers‎ as hpHosts ATS blocks many Amazon CloudFront CDN (cloudfront.net) subdomains where some getsatisfaction.com assets are stored.

- Sample URL: https://getsatisfaction.com/ghostery
- Browser/version: Firefox 44.0.2
- uBlock Origin version: 1.6.2
- Suggested filter for the Unbreak list: `@@||cloudfront.net^$domain=getsatisfaction.com`

Screenshot of page if subscribed to hpHosts ATS:   

[![screenshot][1]][2]

  [1]: http://i.imgur.com/4MalpZHl.png
  [2]: http://i.imgur.com/4MalpZH.png

**Comment by gorhill** [comment]
It works fine using default filter lists. I do not provide support for hpHosts, only for Peter Lowe's, because it is enabled by default.
