### ISSUE TITLE
Cosmetic issues when web fonts unavailable?

### ISSUE THREAD

**Issue by S-Graham** [gorhill/uBlock#1426]
I set the flag in NoScript to disallow downloading of fonts. A side effect seems to have been to break uBlock's displays. I'm seeing placeholder chars in the unicode Private Use Area, so I'm guessing that something was populating that.

Firefox 44.0.2 on Debian Linux.

**Comment by gorhill** [comment]
uBO does not download its FontAwesome resource from a remote location, it's part of the package. Try blocking the downloading of fonts using [uBO's own switch for this](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts) instead -- which has the advantage of being a per-site switch too.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i've noticed this recently too as i've turned `browser.display.use_document_fonts` off in firefox, which is probably the same or similar to noscript's font blocking feature. it disables all custom fonts everywhere including non-remote fonts. so my ublock now looks different. but this is a firefox issue not anything else

**Comment by gorhill** [comment]
@berrythesoftwarecodeprogrammar What version of Firefox are you using? This was fixed in Firefox 41.

**Comment by gorhill** [comment]
There is a review on AMO about the font issue, with a solution by the poster: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/782143/>.

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh woops i was thinking of umatrix. ublock looks fine to me, umatrix's fonts look different but its not a big issue. im using firefox 43.0.3

**Comment by gorhill** [comment]
> umatrix's fonts look different

Yes. uMatrix uses Roboto Condensed, it ships with the package. I picked that font because of the limited space horizontally.

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh well i mean the font changes when `browser.display.use_document_fonts` is toggled. see images below:

![ufonts](https://cloud.githubusercontent.com/assets/6548571/13343133/87a99406-dc9d-11e5-9ed7-64f390973498.png)

![ufonts2](https://cloud.githubusercontent.com/assets/6548571/13343134/8ab65eea-dc9d-11e5-9c92-326389f12dc8.png)

**Comment by gorhill** [comment]
That's it, `document_font` set to `0` will prevent uMatrix from using its Roboto Condensed font.
