### ISSUE TITLE
Yavli Number 2

### ISSUE THREAD

**Issue by AdHelper** [gorhill/uBlock#1428]
### Describe the issue
There is another company like Yavli which doing server side ads implemented on the source of each site.
the company is C.P.M S.T.A.R

### One or more specific URLs where the issue occurs
http://armorgames.com
http://www.onrpg.com
http://mmohuts.com
http://www.silvergames.com
http://newgrounds.com

those are what I've found, there are quite a lot.

### Steps for anyone to reproduce the issue
just surf the sites, you will see multiple XHR requests in random get values to the site domain.

### Your settings

- Browser/version: Chrome Mac newest
- uBlock Origin version: 1.6.2

reported on easylist to:
https://forums.lanik.us/viewtopic.php?f=62&t=28757
no answer from any admin yet (a week had passed, and my report wasn't the only one)

**Comment by gorhill** [comment]
These are not Yavli-like ads, plain cosmetic filters can take care of them.

**Comment by AdHelper** [comment]
They are highly integrated into each website with php file, I've found all of their file names but they are changing them every time, we can block mmo123.co entirely but they will change it again.
I think we should block XHR entirely from those sites.
do you have better Idea mate?

**Comment by IDKwhattoputhere** [comment]
Which ads do you mean? Those?
![](https://cloud.githubusercontent.com/assets/16030872/13354486/9cec4ec8-dc9b-11e5-853e-f465b7fb4a0c.png)
Easily blocked: `mmohuts.com##a[href^="http://mmo-it.com/"]`

**Comment by AdHelper** [comment]
no those are in-house ads, only the ads that redirect to mmo123.co are the "c.p.m S.t.a.r" ads
Those: 
![cpmstar](https://cloud.githubusercontent.com/assets/17493940/13354636/fb777eaa-dca4-11e5-9071-57bfacfdf0d6.png)

**Comment by IDKwhattoputhere** [comment]
Those don't show up for me after the filter list update. Click "Purge all caches" and then "Update now".

**Comment by AdHelper** [comment]
Thanks, those annoying ads are all gone now!
