### ISSUE TITLE
Purging caches deselects filter lists

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1429]
### Describe the issue

Selecting a filter list and then clicking `Purge all caches` removes the check mark from said filter list.
### Screenshot in which the issue can be seen

https://zippy.gfycat.com/BleakSorrowfulAmazontreeboa.webm
### Steps for anyone to reproduce the issue
1. Open the `3rd-party filters` tab in uBO's dashboard.
2. Select a filter list.
3. Click `Purge all caches`.
### Your settings
- Browser/version: Firefox 44.0.2
- uBlock Origin version: 1.6.2

**Comment by lewisje** [comment]
I think this only happens if you didn't select "Apply Changes" first, and it's similar to what happens if you select a list and then click the Update button without first clicking the Apply button; it is annoying, but I had just thought it was intentional.

**Comment by gorhill** [comment]
> similar to what happens if you select a list and then click the Update button without first clicking the Apply button

This one was fixed a long while ago.

**Comment by IDKwhattoputhere** [comment]
Same problem:

1. Open the `3rd-party filters` tab in uBO's dashboard.
1. Select a filter list.
1. Add a custom filter URL in the text box and click `Apply` underneath.

Result: The filter list selected in step 2 is deselected again.

**Comment by gorhill** [comment]
Appears to have been solved, quite probably when I implemented incremental rendering in #2314.
