### ISSUE TITLE
foot01.com - Ligatus ads via inline script

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#1430]
Hi, 
it would be great if you could add rule to disable/block Ligatus ads ([inline script](http://pastebin.com/xyzQFWg1)) on `http://www.foot01.com/` show only to adblocks users (https://vgy.me/yM8Prz.png) who does not stop change at  each blocking by **Liste FR**.

similar issues on : 
```
- http://deco.journaldesfemmes.com/achat/1483483-ikea-nouveautes-fevrier-2016/
- http://www.journaldunet.com/media/publishers/1166117-emilie-coquard-lagardere-elle/
- http://www.commentcamarche.net/news/5867772-google-modifie-l-affichage-des-pubs
- http://www.linternaute.com/television/programme/1273517-candidats-koh-lanta-voici-le-casting-de-la-nouvelle-edition/
- http://www.linternaute.com/actualite/depeche/afp/17/1552247/le-pape-au-mexique-apres-une-rencontre-historique-avec-le-patriarche-orthodoxe-russe.shtml
```

Thanks!

**Comment by gorhill** [comment]
> who does not stop change at each blocking by Liste FR.

I can't parse that sentence.

I don't see the ads in your [screenshot]((https://vgy.me/yM8Prz.png), neither with ABP + EasyList France, neither with uBO.

No need to provide pastebined source code, I can easily click "View source" on my side, however it would be nice for the detailed settings, browser version, etc, as per issue template.

**Comment by SMed79** [comment]
Sorry to have wasted your time.
