### ISSUE TITLE
ET site bypassing ub0 hiding/blocking?

### ISSUE THREAD

**Issue by Morisatos** [gorhill/uBlock#1431]
Hey gorhill, loving your extension keep up the great work.

Regarding [#1031](https://github.com/gorhill/uBlock/issues/1031)

I know this is an old issue and has been deemed fixed but I still have some issues with this site on current v1.6.4b0 of ublock0.

-Filters up to date
-ublock0 up to date
-Filters DO block ads from appearing but the frame/style/placeholder still remain with greyed out boxes of where the ads should be.

http://www.extremetech.com/gaming/219038-amds-radeon-technologies-group-highlights-next-gen-display-standards-new-freesync-capabilities <--- Some interesting comments on the ads itself if you read the top ones starting with 'Dear ET team'.

How do I go about blocking/hiding them or is this the intended consequence? Every refresh it loads the following:

javascript:"< html >< body%20style='background:transparent'>< /body >< /html >"$domain=www.extremetech.com

www.extremetech.com###jivvmzil (this always leaves a tiny bar behind followed by the one below)
www.extremetech.com###jivvmzil > .(random letters upon refresh; adding * doesn't help)
www.extremetech.com###BwxJivvmz
www.extremetech.com###owwotm_ila_qnzium_\/4585\/zd\.extech\/_ATF_0
www.extremetech.com###owwotm_ila_qnzium_\/4585\/zd\.extech\/_ATF_0__container__

**Comment by gorhill** [comment]
Alright... Looks like I have to go back to be extremely strict. Can't reproduce. I don't know exactly what you are talking about. Provide screenshot as per template for such visual issues.

**Comment by Morisatos** [comment]
![2016-02-26_124719](https://cloud.githubusercontent.com/assets/6749395/13364983/39a3d304-dc87-11e5-8e95-1fa4be2b1e8c.jpg)

That small grey bar that blocks out the text under Computing. There is a larger one that appears but seems to get blocked with those filters above in place but this one seems to remain due to www.extremetech.com###jivvmzil > .(random letters upon refresh)

**Comment by gorhill** [comment]
> How nice of you to close the issue before I can respond

You issue is marked as _invalid_, because you do not provide the required details for me to reproduce. I won't spend time on such issue, there is a whole lot of other things I can do with my free time rather than go on a lengthy quest to reproduce by trying all sort of combos of settings guessing at what are your settings to reproduce your issue -- which anyways sounds a lot like a filter issues, no a uBO issue.

[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

>  I simply do not have the time to take care of filter-related issues, you will have to find help elsewhere for this. The mere need to have to respond to filter-related issues can quickly become a burden. Consider that writing code/doc occupies all my free time. Surely there are other people out there ready to help with filter-related issues, it does not have to be me.
