### ISSUE TITLE
Update Spam404 filter URL

### ISSUE THREAD

**Issue by vavavr00m** [gorhill/uBlock#1432]
### Describe the issue
Update spam404 3rd-party filter URL to https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt
Reference: https://adblockplus.org/en/subscriptions

**Comment by vavavr00m** [comment]
Oops. Was to slow to add another link. cjxlist is also outdated

**Comment by gorhill** [comment]
Re. cjxlist, this was fixed more than a year ago: 52aa5cebc0f3a87dac3108f3f2954c931082e108.

**Comment by IDKwhattoputhere** [comment]
Is there any way the check mark could be moved in a future release from `Spam404 (obsolete, will be removed)‎` to `Spam404` if the first one was selected?

**Comment by gorhill** [comment]
There is no way currently, this would require code change. There is code in there which meant to do so, but it does not work. There is another part of the code that does this, and this one works, but the "redirection" are currently hard-coded in the code. If I could make this a separate resource, that would fix the issue of filter lists changing locations.

**Comment by vavavr00m** [comment]
@gorhill My bad. It's the [wiki](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web) I was referring to.

**Comment by gorhill** [comment]
I am thinking scrapping the list of lists on this page (would keep the intro doc though) and referring readers to <https://filterlists.com> instead. Having someone fully invested in taking care of such list of filter lists would relieve me from maintaining that page, which for lack of time I am not doing a very good job at maintaining.

**Comment by collinbarrett** [comment]
Hi @gorhill , filterlists.com creator here. First, I apologize if filterlists trampled on the uBlock wiki at all. I definitely did not intend that. I had bought the domain awhile back, and wanted to throw up a resource that I felt was lacking in the community. I put it on WordPress initially, just because that's what I know best. I am committing to keeping it updated if it is a valuable resource for folks, and I completely agree that open-sourcing it is a better option and it will be able to be better maintained that way. I will look into doing so in the very near future (getting started today).

Thanks for all you do with uBlock.

**Comment by collinbarrett** [comment]
@gorhill I don't mean to hijack this non-related issue, but after looking into it for about 24 hours, I'm just not sure open-sourcing FilterLists via a simple method like using Jekyll would be the right decision. I am committed to keeping the resource updated, and I'd even like to add features, but moving to a static site would already lose one feature I have (auto-notification of broken links) and prevent a lot of dynamic features that I'd like to add in down the road (such as auto-flagging stale lists, etc.). I do not have the resources, nor would it be worth it, to build a custom site for this, and I'm not sure there is a way to open-source a WordPress site when the content is in a db. If anyone comes across this and has an idea, however, I'm definitely open to it.

I am open to replacing the contact form with a public issue tracker or forum of some kind to "open-source" the feedback if it gets used a lot (which I'm not real convinced it will).

That being said, I'm definitely fine with you pointing to it in the wiki if you choose to as you have much better things you can work on than maintaining that corner of the wiki. I can be sure to add some verbage in the "About" page that the project is in no way officially affiliated with uBlock. But, that's totally your call.

**Comment by gorhill** [comment]
> I apologize if FilterLists trampled on the uBlock wiki at all.

I don't know why you feel like apologizing, the gist of what I was saying is that it's a great resource and it relieve me from maintaining my badly maintained one in the wiki.

Re. open source, it's just that it is a useful resource, and it would suck if it stopped existing or being maintained, open sourcing makes it possible for someone else to pick up a project when this happens.

Regardless, I will point at it in the wiki, users of uBO are better served by it than my poorly maintained one.

**Comment by collinbarrett** [comment]
Gotcha. Sounds good. Maybe I'll look into making a dump of the contents on GitHub or something in case it ever goes down. Thanks.

**Comment by gorhill** [comment]
I guess eventually it will be picked by archive.org, so this is probably a non-issue really, it's just me worrying for no good reasons. Don't mind me, and thanks for this useful resource.
