### ISSUE TITLE
A pop up appers after click on any location of the page

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#1433]
Web Browser: Firefox 44.0.2
Platform: Win 7 X86
Ublock Origin 1.6.2, default settings

Steps to reproduce:
1.- Open this URL http://www.cinetux.org/
2.- Clic on any location of the page

Actual results:
1.- A pop up appers

Expected results:
1.- Ublock Origin should block the pop up

Note: Same problem with Chrome

**Comment by IDKwhattoputhere** [comment]
Not a uBlock Origin issue. A 3rd-party filter list issue.
https://forums.lanik.us/viewforum.php?f=62
https://forums.lanik.us/rules

**Comment by gorhill** [comment]
Also, while waiting for filter list maintainers to provide a fix, you can use the [no-popups switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups) for the site, it works.
