### ISSUE TITLE
Fake ublock origin in chrome web store?

### ISSUE THREAD

**Issue by dimaqq** [gorhill/uBlock#1436]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

First hit when searching for "ublock origin" on google web store is some app from other developer... I guess it's a fake app that rides on ublock origin's good name...

### One or more specific URLs where the issue occurs

https://chrome.google.com/webstore/search/ublock%20origin?hl=en-US

### Screenshot in which the issue can be seen

![screen shot 2016-02-28 at 11 45 23](https://cloud.githubusercontent.com/assets/662249/13378774/a52b694e-de11-11e5-8ef6-753b5f26b7db.png)

### Steps for anyone to reproduce the issue

1. start chrome
2. go to about:extensions
3. click get more extensions
4. search for "ublock origin"

### Your settings

Chrome Version 48.0.2564.116 (64-bit) (OSX)

##### Your filter lists

N/A

##### Your custom filters (if any)

**Comment by IDKwhattoputhere** [comment]
Has happened a few times before. It's the first result because it's an app which Google shows before extensions. Report it and move on.

**Comment by gorhill** [comment]
The proper step is to simple report such fake instances -- there is nothing else to do unfortunately. I reported myself days ago, and I am sure a lot of other people also. That's the Chrome store. This was even part of an [article in PC World](http://www.pcworld.com/article/3027642/security/googles-chrome-web-store-lists-malicious-chrome-apps-ahead-of-legit-extensions.html), and still, no changes, those fake apps still come back -- you would think the Chrome store would flag for review such new entries after so many repeats. uBO is not the only extension targeted by whoever is behind this.
