### ISSUE TITLE
Remove sourceforge.net from Badware risks

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#1437]
Sourceforge has stopped bundling their downloads with Adware, thus I guess the SourceForge badware risks filter can be removed.

Check https://sourceforge.net/blog/sourceforge-acquisition-and-future-plans/

I checked the FileZilla download on SourceForge and it seemed to not contain adware.

**Comment by gorhill** [comment]
Duplicate of #1409.

**Comment by tobbi** [comment]
Oh, sorry about this.
