### ISSUE TITLE
the problem with ads on the sides of the option to block ads on video

### ISSUE THREAD

**Issue by lukjan32** [gorhill/uBlock#1438]
Please improve ublock or filters, because they still pop up ads on pages.

Please add an option or feature to be able to block ads, video materials, and that the video was no ads playing.

**Comment by RoxKilly** [comment]
uBO doesn't determine which ads get blocked; the 3rd party filters do, along with filters that we add as users.  If you see specific ads that you want removed, I suggest you make a request over at [EasyList](https://easylist.adblockplus.org/en/), the biggest filter (look for instructions at the bottom of the page).  You will have to be specific though: which ads on which webpages.

**Comment by IDKwhattoputhere** [comment]
To be precise:
This is where you have to report ads that aren't blocked: https://forums.lanik.us/viewforum.php?f=62
Here are the instructions: https://forums.lanik.us/rules

**Comment by lukjan32** [comment]
good. I thought that you add. I unfortunately do not know.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
