### ISSUE TITLE
Script Surrogate breaking Coinbase

### ISSUE THREAD

**Issue by CODYQX4** [gorhill/uBlock#1439]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
It currently isn't possible to sign in to Coinbase because of Google Analytics redirection. This noop script is triggering a CSP error and causing an end of session as soon as you login, keeping it stuck on the logon page.

### One or more specific URLs where the issue occurs
https://www.coinbase.com/signin

### Steps for anyone to reproduce the issue
Try to sign-in to Coinbase (valid account doesn't seem to be required, because it says session error instead of invalid account if you use a bad login/password), it will say session expired immediately. If you look in the console log, there is a CSP Error due to the injected Google Analytics Base64 Script Surrogate. If you whitelist GA for Coinbase it works (but lets GA work).

Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1…kpOwoJCQl9CgkJfQoJfSkoKTsKCXdpbmRvdy5fZ2FxID0gZ2FxLnFmID0gZ2FxOwp9KSgpOw==' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.coinbase.com https://*.olark.com https://*.pusher.com https://cdn.siftscience.com https://*.newrelic.com https://bam.nr-data.net https://*.google-analytics.com https://www.google.com https://www.gstatic.com https://www.youtube.com https://*.ytimg.com https://*.online-metrix.net https://chart.googleapis.com https://maps.googleapis.com https://maps.gstatic.com https://netverify.com https://ajax.cloudflare.com https://www.fullstory.com https://code.jquery.com".

I have inspected that script, decoding the Base64 and it's noop-ing Google Analytics.

### Your settings

- Browser/version: Chrome 48.0.2564.116
- uBlock Origin version: 1.6.4b1

##### Your filter lists
All Default Filters Enabled except Regional and the EasyList without Element Hiding.

**Comment by gorhill** [comment]
Can't reproduce, I get:

> Invalid email or password. Try clicking 'Forgot Password' if you're having trouble signing in.

**Comment by IDKwhattoputhere** [comment]
> All Default Filters Enabled except Regional and the EasyList without Element Hiding.

It seems to me like wrong phrasing is causing a misunderstanding here. I think @CODYQX4 does in fact not mean the default filter lists but **all** filter lists that are offered under 3rd-party filters. This means that `uBlock filters – Experimental` would cause a redirection.
However I can't reproduce this in Chrome 48 with uBO 1.6.2.

**Comment by CODYQX4** [comment]
Yes, by default I meant to say built in. All built in filters are enabled
except Regional and EasyList without Element Hiding (because the latter is
redundant if I use full EasyList).

**Comment by gorhill** [comment]
All filter lists selected as described above, I still get

> Invalid email or password. Try clicking 'Forgot Password' if you're having trouble signing in.

**Comment by CODYQX4** [comment]
I think I may have some corner case.

If I go into Incognito mode with just uBlock and 1Password. It didn't work,
and then did.

It's behaving extremely inconsistently for me, sometimes OK sometimes not.

The 2 main things I can see being blocked are whatever uBlock would ban
with my filter combo + ban fonts, and Chrome's Click To Play plugins (there
is a plugin blocked but I've never needed to unblock that plugin, it was
just a clipboard clearer last time I checked).

**Comment by IDKwhattoputhere** [comment]
> whatever uBlock would ban
with my filter combo + ban fonts

Could you post a screenshot of what shows up in the logger when you visit the site?

Off-topic: https://medium.com/@rosshosman/1password-sends-your-password-across-the-loopback-interface-in-clear-text-307cefca6389

**Comment by CODYQX4** [comment]
There’s some weird chain of glitches going on somewhere with my setup, but since it’s so inconsistent and possibly not uBlock, you can just close this issue.

I did fix it whenever it broke by allowing GA, which might have been a fluke.


On March 2, 2016 at 4:37:25 PM, IDKwhattoputhere (notifications@github.com) wrote:

whatever uBlock would ban
with my filter combo + ban fonts

Could you post a screenshot of what shows up in the logger when you visit the site?

Off-topic: https://medium.com/@rosshosman/1password-sends-your-password-across-the-loopback-interface-in-clear-text-307cefca6389
