### ISSUE TITLE
Flaky support in chrome and doesn't support disabling or hiding inline scripts

### ISSUE THREAD

**Issue by JonasNo** [gorhill/uBlock#1440]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>
uBlock Origin 1.6.2
Browser Version 51.0.2664.0 canary

### Describe the issue
Disruptive messages "Disable adblock" and trolling images show when you have uBlock enabled.

### One or more specific URLs where the issue occurs
[NSFW] https://www.8muses.com/album/8muses-comics

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
[Screenshot(s) for visual issues are **mandatory**]
Nagging to turn off adblock - anti-adblock detection:
http://imgur.com/ycSOeJ3

Trolling image example:
http://imgur.com/no0vNfL

### Steps for anyone to reproduce the issue

1. Got to the site.
2. Click on an image in chrome BAM! anti-adblock nag.
3. Press F5 a few times and you get passed it.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version:  Version 51.0.2664.0 canary
- uBlock Origin version: uBlock Origin 1.6.2

##### Your filter lists
Default.

##### Your custom filters (if any)

8muses.com##script:contains(/^\s*adblock/)

Alternatives tried:
8muses.com##script:contains(adblock)
8muses.com##script:contains(cage)
8muses.com##script:contains('adblock')
https://www.8muses.com##script:contains(adblock)
https://www.8muses.com##script:contains(cage)
https://www.8muses.com##script:contains('adblock')

!! No other extension was running during these tests of ublock. !!

uBlock doesn't block script tags in chrome. Period!
Chrome doesn't work around it and chrome doesn't support.

ATM: Solved it with a custom userscript for the person having this issue. Keeping the userscript secret to prolong it's usage.

**Comment by gorhill** [comment]
[Inline script tag filtering: Caveats](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#caveats):

> Not supported in Chromium-based browser.

**Comment by JonasNo** [comment]
Thought that meant the open source based browser and not the closed source one because you used "Chromium". Perhaps you should clear up that.

Feel disappointed that you didn't even take a look at the anti-adblock scripts before IDKwhattoputhere filled another issue.

**Comment by IDKwhattoputhere** [comment]
Chrome is a Chromium-based browser just like all the ones listed [here](https://en.wikipedia.org/wiki/Chromium_(web_browser)#Other_browsers_based_on_Chromium).

The anti-adblock is not hard to circumvent at all. Just disable element hiding for the site. No user script needed. It's not even a uBlock issue but a 3rd-party filter list issue. `@@||8muses.com^$generichide` does the job just fine.

**Comment by gorhill** [comment]
> Feel disappointed that you didn't even take a look at the anti-adblock scripts

Try `||cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js$script,domain=8muses.com`.
