### ISSUE TITLE
[Suggestion] add a flag to user filters so blocked domains pop ups close

### ISSUE THREAD

**Issue by mcabel** [gorhill/uBlock#1441]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When and user makes a filter, it still pop ups although covered with a message similar to this https://raw.githubusercontent.com/chrisaljoudi/uBlock/master/doc/img/page-block.png

Instead, it would be nice if after adding a filter, we could have a textbox to input a "handling" flag for a domain or website
0) default, website is handled as default, probably showing 
https://raw.githubusercontent.com/chrisaljoudi/uBlock/master/doc/img/page-block.png
1)Block, this flag blocks the domain from loading, opening windows or tabs. I have not seen any way to do this with uBlock(maybe I'm missing something?)
2)Close, a "CLOSE" command will be automatically sent to an user filtered domain or site with this flag. The tab or pop up will load blocked, as in "default mode, but will close after 100(o n?) milliseconds. This mode is for sites with adblock-detection-scripts, which will detect the "blocking" but not the closing.
3)unfocused, this mode will allow the pop up to appear or the tab to open in the same way as default mode, but will "force" the current tab or page to stay focused(I don't really need this feature, but I thought it would be useful for some people who might find popups useful, but not enough to have them take away the focus of their tab w/o consent).

### One or more specific URLs where the issue occurs
This occurs in any site that is not on the filters but this is the only example I remember
example site
http://salefiles.com/oi3hzcqwry1a/58832_300x300.jpg.html
example popup on such site(note: pop up type change daily or weekly)
http://poprush.net/panel/next.php?website=21456513ecac7062314

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

open a site that is not currently blocked by filters/has popups not blocked, such as the salefiles url provided above.
in this example click on free download , write the captcha, wait and download (a test pic was uploaded for this example). A pop up will probably appear. After adding the popup url to an user filter, the pop up will still appear on future occasions, although with this kind of layout, (which is ok, as long as the pop up is wanted, but sometimes it's not, hence this suggestion) https://raw.githubusercontent.com/chrisaljoudi/uBlock/master/doc/img/page-block.png

technically this will happen on any site that opens popups or tabs, and shows  
https://raw.githubusercontent.com/chrisaljoudi/uBlock/master/doc/img/page-block.png

Disallowing/blocking popups completely would be too aggressive, hence, the suggestion of individual-case-by-case site flagging.

### Your settings

default setting  are used

- cyberfox 44.0.2
- uBlock Origin version: 1.6.4

##### Your filter lists

Default filter lists

**Comment by lewisje** [comment]
The message means the site *isn't* loading, and it's more user-friendly than just showing a blank page; also, the use-case of closing popups to the site is handled by the `$popup` option, and I think to do both you would add a rule for dynamic filtering (but this works only at the domain level, while `$popup` can work for just specific pages on a site).

**Comment by gorhill** [comment]
Blocked documents are not necessarily popups, and vice-versa. I do not plan to have blocked documents closed on their own, this would destroy information useful to users. The `popup` filter option must be used to make uBO closes new undesirable tab/window, or use the [per-site no-popups switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups).
