### ISSUE TITLE
[Suggestion]Right-Click:Filter this domain

### ISSUE THREAD

**Issue by mcabel** [gorhill/uBlock#1442]
Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
### Describe the issue

Besides from having the opportunity to block an element, it would be very nice to have the opportunity to block a popup or tab, by adding it to a custom filter with a simple right click command. 

By default, after clicking this option, I'd recommend  a small editable text box with the url just clicked, so user gets a chance to block only part of the site, or add wildcards.

After clicking ok, a new user-filter is added.

> edit: If a filter already exist, then user could be given the chance to change the blocking flag type, as described in "issue  #1441"
### One or more specific URLs where the issue occurs

n/a
### Screenshot in which the issue can be seen

n/a
### Steps for anyone to reproduce the issue

see above
### Your settings

default settings
- Browser/version: cyberfox 44
- uBlock Origin version: 1.6.4
##### Your filter lists

Default filter lists

**Comment by lewisje** [comment]
Some of this use-case is handled by the icon's pop-up menu: If you click the + sign by "domains connected" then you'll see a set of domains along with cells for dynamic filtering rules.

However, I like the idea of suggesting static filtering rules based on the URL of the current page, in addition to cosmetic rules based on the current element clicked.

**Comment by IDKwhattoputhere** [comment]
> If you click the + sign by "domains connected" then you'll see a set of domains along with cells for dynamic filtering rules.

Just wanted to add that `I am an advanced user` needs to be checked for this to work.
