### ISSUE TITLE
[Pale Moon] UO displays old connected domains

### ISSUE THREAD

**Issue by quroe** [gorhill/uBlock#1444]
### Describe the issue
UO continues to handle 1st displayed site's rule when new site opened.
UO displays old connected domains in Dynamic filtering pane.
If using uMatrix,this issue occurs.

### One or more specific URLs where the issue occurs
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Screenshot in which the issue can be seen
![SS](https://cloud.githubusercontent.com/assets/2657891/13545231/195866a4-e2c8-11e5-87f5-5ca54af4276b.jpg)

### Steps for anyone to reproduce the issue
1) Open URL in new tab.(ex.addon page)
2) Open external domain link in current tab.(ex.github/Project change log)
If open external domain link in new tab,this issue dose not occur .

### Your settings
Windows7 x64
Pale Moon 26.1.1 x86
uBlock Origin version: 1.6.4rc0
uMatrix 0.9.3.4
checked "Advanced-user mode"

**Comment by gorhill** [comment]
I can not reproduce with Pale Moon 25.8.1. Is this 26.1.1 version a beta one?

**Comment by quroe** [comment]
26.1.1 is official stable version.
https://www.palemoon.org/palemoon-win32.shtml
I also tried Pale Moon 25.8.1.

1)Start Pale Moon 25.8.1 with new profile.
2)Install uMatrix 0.9.3.4 and uBlock Origin 1.6.4rc0.
3)Restart Pale Moon.
4)Open URL and click external domain link.
5)This issue occurs.

**Comment by gorhill** [comment]
Ok, I could reproduce with 25.8.1.

**Comment by gorhill** [comment]
- So both uBO and uMatrix needs to be installed and enabled.
- Restart Pale Moon.
- Open new tab.
- Paste <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/> in address bar.
- Click _"Add-on home page"_ link on the right-hand sidebar.
- Content of uBO's advanced panel still contains hostnames of previous page.
- Content of uMatrix panel is correct.

**Comment by gorhill** [comment]
For unknown reasons, Pale Moon does not fire `onLocationChange` notifications during navigation, only for when a new tab is created.

**Comment by gorhill** [comment]
Observation: When disabling/enabling uBO in presence of uMatrix, this fixes uBO, but this causes uMatrix to start to misbehave.

**Comment by TPS** [comment]
@gorhill I hope you don't mind I copied this issue into the above linked 1 to be fixed in Pale Moon.

**Comment by gorhill** [comment]
There is no issue with Pale Moon. The bug was fixed, and the cause was finally identified as a variable collision issue -- apparently older Firefox versions used the same context for all frame scripts.
