### ISSUE TITLE
[Suggestion] Add filter category to strict blocking dialogue

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1445]
### Describe the issue

The strict blocking dialogue provides too little detail for inexperienced users. They will see the name of the filter list and will have to guess how high the threat level is. This becomes especially problematic if the user doesn't speak English since the list names and websites are not translated or if the filter originates from say EasyList and the user, when clicking the name of the list, will only be taken to the forums which provide little overview of EasyList's purpose.

### Proposed solution

Adding the [category](https://cloud.githubusercontent.com/assets/16030872/13546873/ba8707b8-e2bb-11e5-8979-16c540cdf7c6.png) to the strict blocking dialogue would help the user understand what kind of site was just blocked. Only problem I see is with the `Multipurpose` and `Regions, languages` categories since those descriptions provide little additional information. Maybe the solution would have to look different so that the mentioned lists have some description to them. Color coding [like hpHosts does it](http://hosts-file.net/?s=plusnetwork.com) might be another idea. Although custom lists might not be covered by any of this. I also found [this](https://github.com/gorhill/uBlock/issues/352) but it's not a solution since most filters don't have comments.

**Comment by gorhill** [comment]
The list name is clickable it is a link to the list's support, I consider this is good enough.

**Comment by IDKwhattoputhere** [comment]
But how will someone find out what say EasyList even is? Are the users supposed to ask on the forum what the lists are? forums.lanik.us has absolutely no information on what the lists even do. And even if it had it would be impossible to understand for users who don't understand English. I think adding the list's category would be a good way to show inexperienced users if the warning is more serious (e.g. malware) or if they might want to click through anyways (e.g. ads). Not telling the user about this only leads to a. paranoia or b. carelessly clicking through all warnings.

**Comment by gorhill** [comment]
You are making this a bigger issue than it really is -- as shown by the fact that you see only two outcomes, "paranoia" or "carelessness".

> I think adding the list's category would be a good way to show inexperienced users if the warning is more serious

With many documented events of malware serevd through ads, is it really important to make the distinction between a page blocked because of a malware list and a page blocked because of EasyList? You will also find a lot of really undesirable stuff blocked by EasyList which I wouldn't feel comfortable qualifying as "benign" or even just mere "ads".

**Comment by IDKwhattoputhere** [comment]
I was mainly thinking about affiliate links from shopping sites which are sometimes blocked but I wouldn't consider harmful. But your point makes sense and thinking about it more often than not the redirections are undesirable. Thanks for the reply.
