### ISSUE TITLE
Saving web page in Chrome 49.0.2623.75 + Easylist

### ISSUE THREAD

**Issue by Safari77** [gorhill/uBlock#1446]
- Browser/version: Chrome x86_64 Linux 49.0.2623.75
- uBlock Origin version: 1.6.2

If "Easylist" or "Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us)" is enabled, saving page (CTRL-S) fails.
To reproduce: go to https://www.startpage.com , press CTRL-S.
Stalls at 6/18, no files created.

If those lists are disabled, saving works.
Tried also without other extensions.

**Comment by gorhill** [comment]
Duplicate of #1185.
