### ISSUE TITLE
(Pale Moon) A minor bug with the "Block media elements" function   

### ISSUE THREAD

**Issue by LimboSlam** [gorhill/uBlock#1448]
I've notice this ever since uBlock Origin v1.6.0 introduced this new functionality. It seems the scroll buttons are missing and when I try to change the value, it gets unchecked/disabled. I'm using Pale Moon v26.1.1 x64 on Windows 8.1.

Here are some screenshots:

**Pale Moon, just hovering over the Block media elements function**  
![pale moon](https://cloud.githubusercontent.com/assets/10698432/13551140/92896188-e2e4-11e5-9102-967f72514679.jpg)

**Pale Moon, changing the value of it**
![pale moon changing value](https://cloud.githubusercontent.com/assets/10698432/13551145/b0b5b44a-e2e4-11e5-9418-a0e9db4e788b.jpg)

**Firefox ESR v38.6.1, scroll buttons appear as should:**   
![firefox esr](https://cloud.githubusercontent.com/assets/10698432/13551146/befec15e-e2e4-11e5-89c5-6b24ffc1b09b.jpg)

**Firefox ESR v38.6.1, changing the value functions as normal:** 
![firefox esr changing the value](https://cloud.githubusercontent.com/assets/10698432/13551147/ca58741e-e2e4-11e5-93df-b76bc45d3fa8.jpg)

**Google Chrome v49, scroll buttons and changing the value function normally:** 
![google chrome changing value](https://cloud.githubusercontent.com/assets/10698432/13551149/d88e2bf0-e2e4-11e5-8eb5-3e1abfd9ee98.jpg)

Hope this is enough information. If more is needed, let me know.

**Comment by gorhill** [comment]
`input` of type `number` was introduced in Firefox 29.

The focus issue is not present with Firefox or Chromium, I will consider this a browser bug. Workaround, double-click on the value to change it.

**Comment by gorhill** [comment]
As per standard, content model:

> Phrasing content, but with no descendant labelable elements unless it is the element's labeled control, and no descendant label elements.

So the `input` element should not be a descendant of the `label` element. But this would overly complicate the localization code. I will try to find a workaround.

**Comment by LimboSlam** [comment]
Nice! I can't wait for the next release! 

Thanks @gorhill!
