### ISSUE TITLE
excessive memory consumption

### ISSUE THREAD

**Issue by sam113101** [gorhill/uBlock#1449]
### Describe the issue
Some pages consume a lot of memory when ublock origin is enabled. Memory consumption seems to grow linearly with time. The issue is not present in safe mode, but is present when ublock origin is enabled. It is also present when all of my other add-ons are disabled, meaning that it is an issue with ublock origin.

### One or more specific URLs where the issue occurs
http://www.meteomedia.com/mensuel/canada/quebec/quebec

### Screenshot in which the issue can be seen
http://i.imgur.com/IURu0vC.png

### Steps for anyone to reproduce the issue
1. Open the URL above
2. Watch its memory consumption in about:memory

### Your settings
default settings

- Browser/version: firefox 45 (beta), also happens on firefox 44
- uBlock Origin version: 1.6.2
- operating system: fedora 23

##### Your filter lists
default filter lists

**Comment by gorhill** [comment]
Issue is with the site, not uBO.

Some sites are so bloated and poorly designed that it's not uncommon for their javascript code to misbehave -- their were written with no expectation of anything failing. This is the case here:

![a](https://cloud.githubusercontent.com/assets/585534/13552253/303c9e56-e329-11e5-90d6-a9b8f481b054.png)

The script `http://s1.twnmm.com/js/fr_ca/r1309011/modernizr/dfpad/s_code/adb_dil/adobe_audience_manager` on the page keeps creating and adding `script` tag elements to the `head` section. Blocking this script solves the issue.

It's a filter list issue, report to filter list maintainers. I did not investigate the other site, but sure it is a similar filter list issue -- sites misbehaving as a result of blocking is not uncommon, the proper step is to report to filter list maintainers.

**Comment by gorhill** [comment]
Required related fix: https://github.com/uBlockOrigin/uAssets/commit/d2443eda27d80d5cc42f419581fac80d33477725
