### ISSUE TITLE
RFE: whitelisting hosts could be more intuitive

### ISSUE THREAD

**Issue by jpjp** [gorhill/uBlock#145]
e.g. the traffic monitor says that xyz.abc.amazon-images.com is blocked

I enter amazon-images into the whitelist: it doesn't help.
I try _.amazon-images.com: invalid hostname
I try ||amazon-images.com like in the monitor: invalid hostname
I try *amazon-images.com/_: it's accepted, but it doesn't help. Also: this would probably block not-amazon-images.com, which I didn't mean.

So I gave up in the end and just clicked the button to whitelist all of amazon.
Maybe a few examples below the textarea.

**Comment by scronide** [comment]
Looks like you were over-thinking it and the one thing you didn't try was just amazon-images.com (FWIW, I think the actual domain is images-amazon.com)

**Comment by gorhill** [comment]
> I enter amazon-images into the whitelist: it doesn't help.

_Whitelist_ pane says:

> Your list of host names for which uBlock₀ will be disabled

What you want is an exception filter:

    @@||xyz.abc.amazon-images.com^

Put that in the _My filters_ pane.
