### ISSUE TITLE
automatic cache cleaning ublock

### ISSUE THREAD

**Issue by lukjan32** [gorhill/uBlock#1450]
Please add to the ublocka, automatic cache cleaning ublocka, after you shut down your browser or after a specified period of time.

**Comment by IDKwhattoputhere** [comment]
Do you mean the browser's cache or uBO's cache that can be cleared in the settings? The former can be cleared through a browser setting and clearing the latter doesn't make much sense. uBO auto-updates the lists every few days anyways.

**Comment by lukjan32** [comment]
it comes to ublock cache

**Comment by gorhill** [comment]
> it comes to ublock cache

What?

**Comment by lukjan32** [comment]
I reply, what I had in mind.

I always like to pop up ads.

**Comment by gorhill** [comment]
Auto-update **is** automatic cache purging: the cached version of filter lists is automatically deemed obsolete after a few days. Having the cached filter lists automatically purged for any shorter period, I consider this to be detrimental to the remote servers hosting the filter lists.

**Comment by lukjan32** [comment]
good :(
