### ISSUE TITLE
uBlock doesn't visually stop popular trackers

### ISSUE THREAD

**Issue by ogregoire** [gorhill/uBlock#1452]
### Describe the issue

uBlock doesn't visually stop tracker buttons like Facebook's "Like" or Google's "+1".

I would expect that a blocker would block these trackers **by default**.

Or maybe they're blocked on another level, but then I get no indicator that's actually the case!

### One or more specific URLs where the issue occurs

https://news.google.com/

### Screenshot in which the issue can be seen

![capture du 2016-03-06 17-10-48](https://cloud.githubusercontent.com/assets/666970/13555397/e1668f8e-e3bf-11e5-86b5-3592dde083dd.png)

### Steps for anyone to reproduce the issue

1. Open https://news.google.com/
1. See that all popular trackers are present (Facebook, Twitter, Google+)

### Your settings

- Browser/version: Firefox 44.0.2 on Ubuntu 15.10
- uBlock Origin version: 1.6.2

##### Your filter lists

Default filter list

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
I don't see any connections to Facebook or Twitter in the logger. There are connections to Google servers, but then you are on a web page served from Google servers.

Enable _"Fanboy’s Social Blocking List‎"_ if you do not want these social widgets. This filter list used to be selected by default but it created too many issues (see <https://github.com/chrisaljoudi/uBlock/releases/tag/0.8.2.8>), so it's now optional. I don't intend to change this.

**Comment by ogregoire** [comment]
Yeah, I was on news.google.com but it also happens on several newspapers I read. Only it was clearer on news.google.com.

Thanks for the tip.

**Comment by Hrxn** [comment]
> I would expect that a blocker would block these trackers by default.

And I would expect otherwise..

Some people actually use these, you know? Also, I wouldn't call them "trackers", because it is an entirely different game than real, invisible trackers used by ad networks. Rather social widgets, or social plugins, or social network site elements..

In my opinion, the current default is sensible.

**Comment by ogregoire** [comment]
@Hrxn I understand the default and I appreciate the existence of a specific filter which I now have enabled. So I'm good and I can't agree more with the decision of gorhill.

That being said, you're being pedantic: they do track (all social networks admit that), so they can be called "trackers". Therefore I just don't understand what your point is.

**Comment by IDKwhattoputhere** [comment]
I think what people usually mean when talking about trackers are [web beacons](https://en.wikipedia.org/wiki/Web_beacon). Basically the kind of requests blocked by EasyPrivacy which provide no benefit for visitors.

**Comment by Hrxn** [comment]
Yeah, tracker, beacon mostly the same. The term beacon is actually quite old, stuff like this was used before tracking on the web even was a thing. That said, beacons don't necessarily track, an invisible element just for counting access to a resource was also called beacon..
But that is just stretching semantics, to some extent..

> Therefore, and with all due respect, I just don't understand what your point is.
Well, my point is this: It is misleading and not fair to lump these two together in the same category.
Social widgets are clearly visible, while "real" trackers are hidden.
Social widgets have a purpose (besides tracking), quick and easy sharing of content, for example.
Real trackers have no other purpose..

And then there's the difference between anonymous tracking and trackers that use techniques, sometimes quite aggressive ones, trying to uniquely identify site visitors.

**Comment by ogregoire** [comment]
@Hrxn I don't understand why you're hijacking this issue. You admit they're trackers but you just don't want to call them trackers.

You want an analogy?
Me: look, this is an animal
You: no, this is a dog
Me: yes, but a dog is an animal
You: no, this is a dog, a dog is usually friendly allows you to pet him, etc. Some dogs are big, some others are small.

See? I just don't understand what's your point. So please stop hijacking this issue for pointless semantics. I opened an issue, it was properly handled and my problem has been solved. What is there more to say?

**Comment by gorhill** [comment]
Any 3rd-party servers which is ubiquitous enough can be reasonably called a "tracker" -- regardless of whether they provide a "useful" widget or not -- as through their ubiquity, they have the ability to build a profile of your browsing history. The safest assumption is: if they collect the data, they will use it.

My advice for people concerned with such ubiquitous 3rd parties is to use uBO's advanced mode, that will deal with the issue much more thoroughly than using 3rd-party filter lists, since nothing override dynamic filtering rules.

See: [Dynamic filtering: to easily reduce privacy exposure](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-to-easily-reduce-privacy-exposure).

Also, see [diff](https://www.diffchecker.com/h3jjgxgd) in [blocking mode benchmarks](https://github.com/gorhill/uBlock/wiki/Blocking-mode) to find out instances of ubiquitous 3rd-party servers (`googletagservices.com` has been taken care of since then).

**Comment by Hrxn** [comment]
> @Hrxn I don't understand why you're hijacking this issue.

I'm not hijacking anything, I just voiced my disagreement about your assumption of a sensible default.

> You admit they're trackers but you just don't want to call them trackers.

Your neighborhood drug dealer and a serial killer a both criminals, would you lump these two in the same category as well? You don't agree with the old aphorism "Let the punishment fit the crime"?

> You want an analogy?
Me: look, this is an animal
You: no, this is a dog
Me: yes, but a dog is an animal
You: no, this is a dog, a dog is usually friendly allows you to pet him, etc. Some dogs are big, some others are small.

Not really. Well, yes, a dog is an animal. But that is not the important part. An animal/dog could be friendly, big, small, or whatever. But it could also be aggressive, dangerous, etc. and that is where you should start to listen. An animal/dog could also be alive - or dead. But what is this? Is a dead animal still an animal, or only a cadaver? Adjectives matter, they can make all the difference.

> See? I just don't understand what's your point.

My point still stands. Being able to differentiate is a very useful ability.

> What is there more to say?

That I still will make the distinction between social widgets and real trackers.

**Comment by Hrxn** [comment]
> I personally block Facebook, Twitter, Disqus, Gravatar, Linkedin, etc. as 3rd-party using dynamic filtering rules because of their ubiquity. As a bonus, this also helps pages load faster.

Blocking Disqus, like completely? No good for me, I don't always read user comments on the web, but that would still be relevant to me.
