### ISSUE TITLE
Ublock cloud storage problem

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#1456]
Hi.I am using Ublock origin v1.6.4 with Chrome v49.I noticed a problem in this version.When I try to upload my filters to Ublock cloud storage it does not work.Because the upload date does not change.But I can upload 3rd-party filters, my rules and whitelist filters to the cloud storage easily.Thanks.

**Comment by gorhill** [comment]
You are probably hitting the size limit? How many custom filters do you have?

**Comment by mozkan007** [comment]
I have 620 number of filters.

**Comment by gorhill** [comment]
There is a size limit for vendor's cloud size. For Chrome it is ~100kB -- see [Caveats](https://github.com/gorhill/uBlock/wiki/Cloud-storage#caveats).

All your settings added together are probably busting that limit. You could put your long settled cusom filter into a separate file, save this file to a remote location and import this location using the _External filter lists_ feature.

You could even use GitHub to create a "secret" Gist for that purpose.

**Comment by mozkan007** [comment]
Thank you.I will try this solution.So I want to ask you, do you have a chance increase the size of the limit?

**Comment by gorhill** [comment]
> do you have a chance increase the size of the limit?

Of course not, this is a limit set by the vendor, Google in this case, it's completely out of my control.

**Comment by mozkan007** [comment]
OK.Thank you for your attention.
