### ISSUE TITLE
Google search sometimes leaves gap before search results? 

### ISSUE THREAD

**Issue by wickles** [gorhill/uBlock#1457]
### Describe the issue

Sometimes in google search results there is a large gap (white space) below the search bar, before the search results. 

### One or more specific URLs where the issue occurs

https://www.google.com/search?q=search

### Screenshot in which the issue can be seen

PC: 

![2016-03-03 13_14_20-google - google search](https://cloud.githubusercontent.com/assets/4229542/13615115/921c2ed8-e528-11e5-82d0-fe7264a4a69a.png)

Mac: 

![search](https://cloud.githubusercontent.com/assets/4229542/13615146/c6967196-e528-11e5-817e-9a6e2a502507.png)

### Steps for anyone to reproduce the issue

I don't know how to reproduce it exactly. I see it a lot and I am trying to figure out the exact cause. It might not even be this extension's fault, but I've narrowed it down a bit (still see issue with other extensions disabled, but haven't tried all yet) and so far I haven't seen it with uBlock disabled. Please let me know if/how I can get any logs or anything to diagnose. 

### Your settings

- Browser/version: 49.0.2623.75 (64-bit)
- uBlock Origin version: uBlock Origin v1.6.4

##### Basic settings enabled

Hide placeholders of blocked elements 
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing/beacon 
Prevent WebRTC from leaking local IP addresses 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Defaults 
uBlock -- Experimental
EasyList
Peter Lowe's Ad server
EasyPrivacy
Malware Domain List
Malware domains

##### Your custom filters (if any)

Allow non-intrusive advertising
https://easylist-downloads.adblockplus.org/exceptionrules.txt
(I'm now realizing this may be the issue, but I think I've seen it even without this. I'll disable it and report back if I still see the issue.)

**Comment by gorhill** [comment]
> I'll disable it and report back if I still see the issue.)

I will reopen if you make the case there is any issue with uBO and that it is not an issue with a filter list.

**Comment by wickles** [comment]
Okay, fine with me. I haven't seen this discussed elsewhere so at least it might help others diagnose the same problem.

**Comment by gorhill** [comment]
When it happens, see what is the class/id of whatever DOM element(s) is in there, then see if this matches an exception cosmetic filter in `exceptionrules.txt`.

For now uBO does not report exception cosmetic filter in the logger, this is issue #127.

**Comment by wickles** [comment]
Still happening. I disabled the custom filter and experimental filter. It shows up like this in inspector: 

`<div id="subform_ctrl" style="visibility: visible; margin-top: 90px;"></div>`

Can't really check the logger because it typically goes away when I refresh. I checked another tab with a working search and the same line appears like this: 

`<div id="subform_ctrl" style="visibility: visible;"></div>`

Still can't say for certain whether it's uBlock or some other extension, I will look into it further.

**Comment by To-mos** [comment]
I was able to replicate the problem as well.

![image](https://cloud.githubusercontent.com/assets/5252667/23094258/2c05e1b4-f5aa-11e6-81ba-145cd56da7e9.png)

**Comment by wickles** [comment]
@To-mos do you use HTTPS everywhere?

**Comment by To-mos** [comment]
After a format it has stopped, however before hand the only other plugin was greasemonkey. I'm guessing it was like tampermonkey.

**Comment by wickles** [comment]
Thanks, I'll try disabling Tampermonkey and see if it helps.

**Comment by wickles** [comment]
I am still seeing this behavior with Tampermonkey disabled.

**Comment by Shriniket33** [comment]
Deleting Google's extensions helped me resolve the issue.
