### ISSUE TITLE
[Feature Request] Being able to select/unselect several filter in one click

### ISSUE THREAD

**Issue by Dostoi** [gorhill/uBlock#1458]
It would be nice to be able to select/unselect the list of filter with just one click. It would make the initial setting of the app easier and testing too, when one filter is breaking a site but you don't know which one.

Like if you click the box next to "Publicités" here, all of the filters of this category would be selected or unselected.

![ublock](https://cloud.githubusercontent.com/assets/7694864/13630312/0672d4a6-e5df-11e5-9caa-4ee0dd31fea0.png)

Thanks for all your work ! :)

**Comment by Hrxn** [comment]
Huh, in this case, you would basically save 4 clicks. That's all.

I would be more concerned with broken sites, because that actually should not happen too often, in my experience. So check your settings first..
