### ISSUE TITLE
Improve the My Rules parser to trim redundancies after edits

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#1460]
When a user enters custom dynamic filtering rules on the `My rules` tab, uBO parses the rulelist.  There is an opportunity for improvement: we could remove redundant rules.

Here is the use case I ran into.
1.  A while back, I added `addons.mozilla.org * 1p-script noop` to improve browsing the Mozilla store.
2.  A couple of months later, I added `www.mozilla.org * 1p-script noop`
3.  Today, I added `mozilla.org * 1p-script noop`

At this point, the parser could notice that rules 1 and 2 are redundant and remove them when rule 3 is committed.  The redundancy check could be extended to the 2nd domain in the rule.  For instance `mozilla.org www.mozilla.net * noop` becomes redundant if the user adds `mozilla.org mozilla.net * noop`

This change would reduce bloat and perhaps achieve performance gains from having fewer rules to evaluate.

**Comment by gorhill** [comment]
I don't intend to have uBO automatically removes rules trying to guess what the user has in mind. When #571 is fixed, I don't see your example as being an issue.
