### ISSUE TITLE
Explanation missing for "http" behind 3p filter list entries

### ISSUE THREAD

**Issue by petmue** [gorhill/uBlock#1462]
### Describe the issue

There's no entry in the wiki which explains what the "http" with the red background indicates or stands for behind some third party lists.

### One or more specific URLs where the issue occurs

chrome://ublock0/content/dashboard.html#3p-filters.html
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters

### Screenshot in which the issue can be seen

![ublock_http](https://cloud.githubusercontent.com/assets/16270886/13680435/d10aa8be-e6f8-11e5-88cc-98c71aee3cf7.png)

**Comment by SW1FT** [comment]
It means the list is hosted in a website that only offers HTTP connections and therefore is a security risk since the connection is not encrypted when uBlock retrieves the list.

**Comment by gorhill** [comment]
Fixed doc.
