### ISSUE TITLE
Project Ublock - collaboration 

### ISSUE THREAD

**Issue by AlexanderPaternoster** [gorhill/uBlock#1463]

**Comment by gorhill** [comment]
> middle ground in which users can benefit from opening up ads or viewing them

My view on this is to let users decide what is best for them, I don't see why it should be otherwise. Whitelisting a site is just a matter of few clicks. Everyone has his/her own idea of what "middle ground" is -- for those who believe there has to be one -- they can choose for themselves.

**Comment by AlexanderPaternoster** [comment]
Hi Gorhill, 

We see that your view differs a little bit from ours, but I don't think that needs to be a problem for us to have a good collaboration. In the end, our main belief is the same: we don't like advertisements and we want the user to have the option of opting out. 

You do magnificent work on giving the user a way to completely opt-out of advertisements and when installed you give them the option to opt-in. In our fork we would like to make it more interesting for the user to opt-in certain advertisements. We think that the user himself should make a trade-of between blocking ads vs. opening up ads AND getting a reward for it. At the moment the user is too much tempted to block all ads (which is not beneficial for content providers and their revenue models). We belief that this attitude might deliver good relationships with the content providers as well.

Our team (containing 2 PhD-students and 2 final years masters) would like to approach the problem from a different perspective. However, we don't chase different goals!

To the point: what is it what we want?
- We'd like to have your blessing for forking ublock and adapting it in the way we described it above
- It would be cool if we could mention our tool is based on ublock, as we think that your adblocker is fantastic and that's it.
 
We hope you see that we don't want to attack your project or even want to insinuate that it is not good enough. 

Kind regards

**Comment by CrisBRM** [comment]
@AlexanderPaternoster Brave (browser) is already doing what you want. Besides, uBlock is not merely an 'ad blocker', it blocks trackers and other objects.

https://www.brave.com/

**Comment by berrythesoftwarecodeprogrammar** [comment]
i cant answer for @gorhill  but im pretty sure he has enough on his plate @AlexanderPaternoster and that anybody is allowed to fork this according to its license as it is open source software. you dont need him to be on your team

**Comment by gorhill** [comment]
> We'd like to have your blessing for forking ublock

You don't need my blessing (assuming I felt important enough to believe my "blessing" was needed for anything): the code is GPL -- so the only requirement is that the GPLv3 license is respected.

**Comment by AlexanderPaternoster** [comment]
Good to hear that! We see that there are some similarities with the business model of 'Brave'. However, we want to give a user experience which is slightly different than the one 'Brave' provides. Thank you @gorhill , @CrisBRM , @berrythesoftwarecodeprogrammar  for your comments.
