### ISSUE TITLE
[Feature Request] Click on Page element to enable.

### ISSUE THREAD

**Issue by schliden** [gorhill/uBlock#1464]
I run ublock with 3rd party blocked.
This breaks many pages, which is fine, as I am happy to selectively enable 3rd parties as needed.
Often (with media elements) it can take a long time and multiple page reloads to identify what combination of 3rd party content is required to make an element work.

 If possible it would be extremely useful to provide the inverse of element picker mode, that would support clicking on a non functional page element (typically media element), which would automatically activate the required third party content to make the clicked element work..

**Comment by gorhill** [comment]
There is no way I can think which would work. Most of the time what breaks a page is javascript being blocked, and there is no way to track back which javascript resources are responsible for make a specific element work, other than by investigating + trial/error -- experience helps.

**Comment by Hrxn** [comment]
I wouldn't use 3rd-party blocking so indiscriminately. Legit site functionality requires 3rd-party Javascript quite often, I don't think blocking it all is a useful default.

Just my 2 cents..
