### ISSUE TITLE
3rd-party filters update status broken

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1465]
![new](https://cloud.githubusercontent.com/assets/6416073/13701193/72481bac-e786-11e5-9a6c-398355661833.png)

![new](https://cloud.githubusercontent.com/assets/6416073/13701128/0a9bdec6-e786-11e5-90ca-b777719b6d16.png)

![new](https://cloud.githubusercontent.com/assets/6416073/13701091/abfa39a8-e785-11e5-9de2-b7b532329a5f.png)

As you can see both the "Update" button and "out of date" indicates a failure (second screenshot) of the current status as it was downloaded (first screenshot). I've repeatedly done this so the "x out of y" filters in the text of the screenshots that appear to not have been updated is correct.

Using uBO 1.6.4.

**Comment by davidhedlund** [comment]
https://github.com/gorhill/uBlock/issues/132

**Comment by IDKwhattoputhere** [comment]
Works fine on my end. Can you visit this URL? https://mirror.cedia.org.ec/malwaredomains/justdomains

> #132

That's not the issue you describe though, right? Seems completely unrelated.

**Comment by davidhedlund** [comment]
@IDKwhattoputhere No I cannot visit https://mirror.cedia.org.ec/malwaredomains/justdomains. This seem to be an IceCat issue. I will report it to the developer.

Thank you.

**Comment by davidhedlund** [comment]
@IDKwhattoputhere I can visit http://mirror.cedia.org.ec/malwaredomains/justdomains (but not https://mirror.cedia.org.ec/malwaredomains/justdomains).

**Comment by gorhill** [comment]
> No, I can only visit the non-SSL connection

Not a uBO issue then. CONTRIBUTING: "make the case there is an issue with uBO". This means yes, you will have to investigate on your side, not dump this here for others to investigate for you.

**Comment by davidhedlund** [comment]
@gorhill There is nothing that says that SSL have to be used in chrome://ublock0/content/asset-viewer.html?url=assets/thirdparties/mirror1.malwaredomains.com/files/justdomains. How do you figure that out?

**Comment by davidhedlund** [comment]
A solution would be that uBO ask for a non-SSL connection if it cannot establish a SSL connection.

**Comment by IDKwhattoputhere** [comment]
> There is nothing that says that SSL have to be used in chrome://ublock0/content/asset-viewer.html?url=assets/thirdparties/mirror1.malwaredomains.com/files/justdomains.

Yes, there is. It says `http` if the connection is not encrypted.

**Comment by gorhill** [comment]
That list also ships as part of the package -- so its entry is a key rather than a URL. The URLs to use are all found in `[filter-lists.json`](https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json#L233):

    "mirror1.malwaredomains.com/files/justdomains": {
        "title": "Malware domains",
        "group": "malware",
        "homeURL": "https://mirror.cedia.org.ec/malwaredomains/justdomains",
        "supportURL": "http://www.malwaredomains.com/"
    },

Why would your browser not be able to load `https:` resources?

**Comment by davidhedlund** [comment]
@gorhill >Why would your browser not be able to load https: resources?

Because I use GNU IceCat 38.6.0; there is a bug to connect to certain SSL sites including https://gnupg.org/ (see https://lists.gnu.org/archive/html/bug-gnuzilla/2016-02/msg00004.html).

**Comment by gorhill** [comment]
> uBO should try connect to non-SSL if it fails with SSL

I am not very fond of the idea of adding code to uBO just for the sake of working around a bug in a browser, which from what I understand can be trivially fixed:

> For now, users can work around this problem by going into about:config
> and changing these settings to "true".  I'm also going to remove these
> customizations from the IceCat build in GNU Guix.

This on top of also having a work around in uBO: import the non-https version of the URL as an external filter list.

For these reasons, I decline.

**Comment by davidhedlund** [comment]
@gorhill I respect your decision, there are more important issues to focus on. Also, this bug should be fixed in IceCat soon.

**Comment by davidhedlund** [comment]
I can reach https://mirror.cedia.org.ec/malwaredomains/justdomains with IceCat 38.7.1 now.
