### ISSUE TITLE
Unable to connect background

### ISSUE THREAD

**Issue by vendforce** [gorhill/uBlock#1466]
Ive permanently blocked ad.httpool.com and the I get the below  page message when loading that page or any others that I block

Unable to connect
Firefox can't establish a connection to the server at ad.httpool.com.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

is there any way to change the design of this page i.e have a picture or background instead of the default error message page

Ive tried stylish firefox addon but it doesnt seem to apply the theme after restarting firefox and going to the blocked page

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Where did you block the domain?
If you've blocked the page in uBO it will display a message like this one:
![](https://cloud.githubusercontent.com/assets/16030872/13716717/27e810a6-e7dd-11e5-9a25-030389153550.png)
What you're talking about is a message the browser displays when it can't connect to a server. It has nothing to do with uBO.
