### ISSUE TITLE
Blacklist mode not working correctly

### ISSUE THREAD

**Issue by Doot1952** [gorhill/uBlock#1467]
### Describe the issue
Blacklist mode seems to be somewhat broken. When all is selected in the global rules column, no requests are blocked and all domains connected, but ads and placeholders are still blocked. There are a couple of sites that display ads correctly, but most I've found are still blocked.  

### One or more specific URLs where the issue occurs:
eurogamer.net
independent.co.uk
theguardian.com/uk
thewirecutter.com/
sputnikmusic.com

### Screenshot in which the issue can be seen
![blacklist mode active](https://cloud.githubusercontent.com/assets/17791177/13718431/c68abade-e7e1-11e5-8900-ff520fad9f33.png)
![whitelisted](https://cloud.githubusercontent.com/assets/17791177/13718438/cbb4cb4e-e7e1-11e5-9826-9559e52bb91f.png)
![blacklist mode active 2](https://cloud.githubusercontent.com/assets/17791177/13718440/d1dd1e4a-e7e1-11e5-8e64-2ca5d9ba9c99.png)
![whitelisted 2](https://cloud.githubusercontent.com/assets/17791177/13718444/d56803d6-e7e1-11e5-94aa-1e7f0eed1ff8.png)
![site that displays ad correctly](https://cloud.githubusercontent.com/assets/17791177/13718447/da4345be-e7e1-11e5-9969-0d2272d24359.png)

### Steps for anyone to reproduce the issue
Activate blacklist mode and visit certain sites. 

### Your settings
Hide placeholders
Show number of requests
Make use of context menu
Advanced user
Disable pre-fetching
Disable hyperlinking
Disable WebRTC

- Browser/version: Chrome 49.0.2623.87 m (64-bit)
- uBlock Origin version: 1.6.4

##### Your filter lists
Default filter lists + 
uBlock filters – Experimental‎
Adblock Warning Removal List‎
Basic tracking list by Disconnect‎
Fanboy’s Enhanced Tracking List‎
Malvertising filter list by Disconnect‎
Malware domains (long-lived)‎
Malware filter list by Disconnect‎
Spam404‎
Anti-ThirdpartySocial (see warning inside list)‎
Fanboy’s Annoyance List‎ 
Fanboy’s Social Blocking List‎ 
Dan Pollock’s hosts file‎ 
Fanboy+Easylist-Merged Ultimate List‎ 
hpHosts’ Ad and tracking servers‎ 
MVPS HOSTS‎
EU: Prebake - Filter Obtrusive Cookie Notices‎

##### Your custom filters (if any)
No custom filters.

**Comment by gorhill** [comment]
Thee is no official blacklist mode -- just an incidental one. Using `allow` rules for a site does not affect cosmetic filtering, only network filtering. So if you want to use blacklist mode, I advised you turn off cosmetic filtering by default as well, in _Settings_, and turn it on only on a per need basis.

**Comment by Doot1952** [comment]
@gorhill 
This fixed the issue. Thanks a lot Raymond.
