### ISSUE TITLE
HOSTS file filtering also blocking domains with a different ccTLD

### ISSUE THREAD

**Issue by AmperAndSand** [gorhill/uBlock#1468]
## Issue description
I have added the [CHEF-KOCH's NSA Blocklist HOSTS file](https://github.com/CHEF-KOCH/NSABlocklist) as a custom filter. It blocks many US government domains (ending in `.gov`). However, I noticed that with uBlock Origin, .gov domains with a non-US ccTLD, e.g. `.gov.ph` are also blocked.

For example: `doe.gov` is blocked in the HOSTS file, but if I go to http://www.doe.gov.ph/ (Philippine government), uBlock Origin also blocks it, stating the `doe.gov` filter, even though those are completely different websites.

### One or more specific URLs where the issue occurs

http://www.doe.gov.ph/ - any many other non-US .gov domains

### Settings

- Browser/version: Firefox 44.0.2
- uBlock Origin version: 1.6.4

##### Filter lists

Default filter lists + [CHEF-KOCH's NSA Blocklist HOSTS file](https://github.com/CHEF-KOCH/NSABlocklist)

**Comment by gorhill** [comment]
Thanks for the report. Fix is in 1.6.5b2, which is available in dev channel on AMO.

**Comment by gorhill** [comment]
Forgot to mention, for the fix to work you need to purge the cache of that list, as it needs to be re-compiled by uBO.
