### ISSUE TITLE
3rd-party filters -> MVPS HOSTS‎ = Windows-recommending

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1474]
winhelp2002.mvps.org, this link encourage Windows, I don't like it. The filter is distributed under a non-free license too.

Consider removing MVPS HOST.

**Comment by tainothewarden** [comment]
>this link encourage Windows, I don't like it.
Since when "I don't like it" is an issue? I can just remove it yourself.

**Comment by davidhedlund** [comment]
From https://www.gnu.org/philosophy/is-ever-good-use-nonfree-program.en.html

If you run a nonfree program on your computer, it denies your freedom; the main one harmed is you. Your usage of it can harm others indirectly, by encouraging development of that nonfree program. If you make a promise not to redistribute the program to others, you do wrong, because breaking such a promise is bad and keeping it is worse. Still, the main direct harm is to you.

It is even worse if you recommend that others run the nonfree program, or lead them to do so. When you do that, you're leading them to give up their freedom. Thus, what we should avoid most firmly is leading or encouraging others to run nonfree software. (Where the program uses a secret protocol for communication, as in the case of Skype, your own use of it pressures others to use it too, so it is especially important to reject any use of these programs.)

**Comment by berrythesoftwarecodeprogrammar** [comment]
uBlock is in no way encouraging the use of Windows or non-free software. You can't link uBlock to Windows through a host file subscription.

**Comment by davidhedlund** [comment]
@ProudNoob I changed my mind, I don't care what site they host their stuff on.
