### ISSUE TITLE
Wrong redirect to facebook.com via an iframe despite a filter

### ISSUE THREAD

**Issue by birdie-github** [gorhill/uBlock#1475]
I hope you don't mind if I leave a link to an already posted bug report:

https://github.com/chrisaljoudi/uBlock/issues/1597

If I'm missing any information, please, let me know - I will post it promptly.

**Comment by gorhill** [comment]
When I visit the page I am not redirected. There must be something specific on your side causing this.

**Comment by birdie-github** [comment]
Indeed invalid, it was a conflict with the QuietUrl extension which had a rule which didn't work at the website.
