### ISSUE TITLE
Misinterpreting filters with elemhide

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1477]
### Describe the issue

uBO is breaking some sites because it misinterprets certain filters.

### One or more specific URLs where the issue occurs

http://www.lablue.de/nu.html

### Steps for anyone to reproduce the issue

1. Subscribe to `DEU: EasyList Germany‎`
1. Go to http://www.lablue.de/nu.html and click `Login für Mitglieder` (`Login for members`) in the upper right corner.

Result: The login doesn't open. I presume it's broken because uBO interpreted the filter `@@||lablue.de^$elemhide,script` incorrectly.

### Your settings

- Browser/version: Chrome 49
- uBlock Origin version: 1.6.4

##### Your filter lists

Default filter lists + EasyList Germany‎

**Comment by gorhill** [comment]
Side note: why is the `script` filter option needed at all? I do not see any matching block filter to justify the need of that exception.

**Comment by IDKwhattoputhere** [comment]
Maybe there were some problems with the site for logged in users. I unfortunately do not have an account. Searching the EasyList forums brings no results. Looks to me like they might have/had some Anti-Adblock since `pagead2.googlesyndication.com/pagead/show_ads.js` is whitelisted too for that domain in EasyList Germany.
