### ISSUE TITLE
Sometime error load page of Firefox

### ISSUE THREAD

**Issue by volpe2** [gorhill/uBlock#1479]
I'm using last version (64bit) of Firefox sometime-usually when i visit a website doesn't charge and I have to recharge it.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Does it happen when uBlock Origin isn't installed/enabled? Then it doesn't have anything to do with uBO. It's the page the browser displays when it can't connect to a server.

**Comment by volpe2** [comment]
Without uBO doesn't happen so.

**Comment by IDKwhattoputhere** [comment]
> so

What? So often?

**Comment by volpe2** [comment]
Without UBO, this problem does not occur.

**Comment by gorhill** [comment]
> What? So often?

Just a troll. Blocked.

**Comment by IDKwhattoputhere** [comment]
Ok, thanks. ¦-D
