### ISSUE TITLE
Can't search repository on GitHub

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#148]
Hi,

since GitHub doesn't allow searching code on forked repositories, I am unable to do so with ublock origin's repo as well. This is a bummer when not using my personal machine or when using a phone or slow net connection. 

Since this is a non-trivial fork and likely to deviate a lot in the future, I suggest you convert the repository into a standalone one, so that GitHub treats it with respect ;)

**Comment by gorhill** [comment]
Won't I lose the ability to push changes to the main project? I need to keep this ability for important bug fixes, and for important core functionality (like issue #139).

**Comment by anewuser** [comment]
@notfoss https://help.github.com/articles/searching-code/#search-by-the-number-of-forks-the-parent-repository-has

**Comment by notfoss** [comment]
Yes, I believe you won't be able to seamlessly push to the main project. There can be workarounds, but that would be too much hassle.

@anewuser posted this link: https://help.github.com/articles/searching-code/#search-by-the-number-of-forks-the-parent-repository-has

which says:

> However, to ensure better relevancy, repository forks will not be searchable unless the fork has more stars than the parent repository.

Ridiculous! Maybe a few months down the line, ublock origin will have more stars than ublock :wink: . Too bad, the idiocity of GitHub is affecting proper access to the repositories.

I guess there's no option but to close the issue.

**Comment by anewuser** [comment]
@notfoss I've deleted it because it mentioned some search parameter and I assumed it'd work, but it didn't.

**Comment by notfoss** [comment]
It didn't work due to the number of stars limitation probably.
