### ISSUE TITLE
Slightly better 'document-blocked.html' page

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#1482]
Sometimes I set filters to block annoying/tracking url parameters such as: `^src_vid=$domain=youtube.com,document` which for example blocks: https://www.youtube.com/watch?v=KuG_CeEZV6w&feature=iv&src_vid=igxN6HmHj_s&annotation_id=annotation_1496362339. As you can see most of the time for me only a single parameter is useful `v`. How about implementing something like this:
![ublockissue001](https://cloud.githubusercontent.com/assets/930620/13802711/7bb23496-eb0c-11e5-8ca6-75a8133003fe.png)
As you can see each parameter li now also links to the url with only that parameter to quickly pick the best one.

**Comment by lewisje** [comment]
It is more convenient than copying the entire link and manually removing everything but the query-string parameter.

**Comment by Hrxn** [comment]
I don't get it..

And why do you block YouTube?!

**Comment by IDKwhattoputhere** [comment]
I think he wants clean YouTube URLs. I use [YouTube Link Cleaner](https://greasyfork.org/scripts/1193-youtube-link-cleaner) which is easier. Of course that only works for YouTube and not other links with parameters.

**Comment by anewuser** [comment]
@vzjrz This is out of the scope of uBlock Origin.

You can use this extension to manipulate URLs: https://github.com/einaregilsson/Redirector#download-links

**Comment by vzjrz** [comment]
I only block youtube links with `src_vid` parameters. I can think of a few more sites which add these tracking parameters to an otherwise useful link (twitter, amazon, ...).
This is not about manipulating links. This change just gives the option to click one of the listed parameters which points to the link with just that one parameter. This would just make it easier to pick out the useful parameter of a blocked link.

**Comment by Halibut80** [comment]
@vzjrz But what reason for block link, if you can just remove tracking/garbage parameters?
Use <a href='https://github.com/diegocr/CleanLinks'>Clean Links</a> or <a href='https://addons.mozilla.org/en-US/firefox/addon/pure-url/'>Pure URL</a> (supports rules like <code>src_vid@youtube.com</code>, that's cleans links only with specified domain) to remove garbage parameters from url.

**Comment by gorhill** [comment]
I will decline this. Creating links with one or another parameters is maybe useful on a random basis -- that it ends up being useful to you is just luck for the specific case you mention. One other case may require two or more from the set of parameters. A URL re-writer/fixer is optimal for this purpose, not uBO.

**Comment by vzjrz** [comment]
Ok thanks anyways guys. I think I'll set up Pure URL then looks pretty sweet.
