### ISSUE TITLE
 Block Reddit from tracking outbound links

### ISSUE THREAD

**Issue by Snow8** [gorhill/uBlock#1485]
Hey... Would it be possible to implement this into uBLockO?

http://www.ghacks.net/2016/03/17/block-reddit-from-tracking-outbound-links/

**Comment by gorhill** [comment]
I consider URL rewriting to go beyond the scope of uBO -- this is best left to a dedicated extension, maintaining re-writing URL rules requires work.

In uBO, one could use a filter such as `||out.reddit.com^$document` and click on the real destination link on the block page, but that is as far as uBO will go.

**Comment by Snow8** [comment]
yeah that is cool. I was just wondering if it would be possible to put it somehow into the filter pane.

**Comment by gorhill** [comment]
Given how high traffic Reddit is, I will look into creating a privacy filter + scriptlet once I am able to reproduce the issue on my side.

**Comment by ethus3h** [comment]
How about just having a syntax for URL rewriting in filter lists, without including any out of the box so URL rewriting lists don't need to be maintained except by users? E.g., when a request is made to http://foo.org/blah and there's a rewrite rule
```
^https?://([\w-]\.)foo.org(/?([\S\s]+))$ https://\1foo.org/folder/\3
```
the request is instead changed to https://foo.org/folder/blah — that would be very handy, and wouldn't need to have filters using this ability included in the addon.
