### ISSUE TITLE
Whitelist [Apply changes] doesn't enable

### ISSUE THREAD

**Issue by MaxMillion** [gorhill/uBlock#1487]
### Describe the issue
[Apply changes] is not enabled when whitelist is changed, only when entire whitelist is cleared, no other change seems to enable it.

My proposed change is UNCHECKED, I'm not sure if it will work.

`src/js/whitelist.js`
Line 54#: "cachedWhitelist = whitelist.value.trim();"  //Added ".value" before ".trim()"

### One or more specific URLs where the issue occurs

chrome://ublock0/content/dashboard.html#whitelist.html

### Screenshot in which the issue can be seen

![Unmodified](https://cloud.githubusercontent.com/assets/8866895/13888010/1f2cab74-ecfc-11e5-98b3-4db140625269.png)
![Modified](https://cloud.githubusercontent.com/assets/8866895/13888014/234b01a6-ecfc-11e5-9e64-fc32f4b2f939.png)

### Steps for anyone to reproduce the issue

1. uBlock dashboard > [Whitelist]
2. Modify existing Whitelist
3. Take note how [Apply changes] does not enable after modifying existing Whitelist.

### Your settings

Active: 
- [x] Hide placeholders of blocked elements
- [x] Make use of context menu where appropriate
- [x] I am an advanced user (Required reading)
- [x] Disable pre-fetching (to prevent any connection for blocked network requests) 
- [x] Disable hyperlink auditing/beacon 
- [x] Prevent WebRTC from leaking local IP addresses 

- Browser/version: Firefox 45.0 on lubuntu x86
- uBlock Origin version: uBlock Origin v1.6.4

##### Your filter lists

uBlock
 + filters
 + Badware
 + Privacy
 + Unbreak

Ads
 + Adblock Warning Removal List
 + Anti-Adblock killer
 + EasyList
 + Peter Lowe's Ad server list

Privacy
 + EasyPrivacy
 + Fanboy's Enhanced Tracking List

Malware domains
 + Malvertising filter list by Disconnect
 + Malware domain list
 + Malware domains
 + Malware domains (long-lived)
 + Malware filter list by Disconnect

Social
 + Anti-ThirdpartySocial (see warning inside list)
 + Fanboy's Annoyance List
 + Fanboy's Social Blocking list

Multipurpose
 + Fanboy+Easylist-Merged Ultimate list
 + MVPS HOSTS

Custom
 * Facebook
  * Annoyances blocker
  * news feed annoyances blocker
  * sidebar blocker
 * Yotube
  * Other annoyances
  * Pure Video Experience
  * Remove Comments
  * Remove Youtube Suggestions

**Comment by gorhill** [comment]
I can't reproduce.

`whitelist` at line 54 is a string, not an object, so adding `.value` to it accomplishes nothing.

It looks to me you have bad characters somewhere in there, be sure you do not have stray tab or other invisible characters.

**Comment by MaxMillion** [comment]
It seems like a "~" character in one of the urls was causing the issue as removing that url seems to have resolved the issue.  Thank you for your help 😄

**Comment by monorailmedic** [comment]
I am able to reproduce this issue and have no "~" in my whitelist.  I've seen the issue over the past months and it seems oddly intermittent.  I've not yet found a clear work-around.

**Comment by gorhill** [comment]
Can't help without specifics. It does not have to be `~` only, it can be any characters as specified by [the regexp here](https://github.com/gorhill/uBlock/blob/eb8c17d55c402d5dfb3dd0dafbced1b56e4b22ce/src/js/whitelist.js#L36):

    var reUnwantedChars = /[\x00-\x09\x0b\x0c\x0e-\x1f!"$'()<>{}|\\^\[\]`~]/;
