### ISSUE TITLE
lists of filters (learning)

### ISSUE THREAD

**Issue by laozi83** [gorhill/uBlock#1489]
hello,
just a question for good understanding of uBlock origin lists,
example:
uBlock filters experimental > 8 used on a total of 8
EasyList > 0 used a total of 62294
is this to say that Easylist is useless for me?
Thanks for your lighting
excuses for my bad English

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
> is this to say that Easylist is useless for me?

If you set the check mark next to EasyList then basically yes since your other filter lists already cover all of EasyList's filters.

**Comment by laozi83** [comment]
un grand merci pour cette précision,
Thank you for this precision
