### ISSUE TITLE
Vanishing from Firefox and needs to be reinstalled (Win7 x64, Firefox 45.0 x64)

### ISSUE THREAD

**Issue by Ketrel** [gorhill/uBlock#1490]
### Describe the issue
Every so often, I restart firefox for some reason or another (usually with a reboot) and I find that ublock is uninstalled.  Reinstalling it is fine and my settings are still there, but it's happened upwards of 10 times.

### One or more specific URLs where the issue occurs
Not specific to sites

### Screenshot in which the issue can be seen
Already reinstalled, nothing to take screenshot of

### Steps for anyone to reproduce the issue
What I just did that produced it last time

1. Closed Firefox with the X button.
2. Selected "Save and restore at startup" to Session Manager Prompt
3. Rebooted machine
4. Opened Firefox
5. Noticed ublock button was missing refreshed a page to confirm

### Your settings
Checked Settings, all others unchecked  
* Settings->Hide placeholders of blocked elements
* Settings->Make use of context menu where appropriate
* Privacy->Disable pre-fetching (to prevent any connection for blocked network requests)
* Privacy->Disable hyperlink auditing/beacon

**Browser/version:** 
Windows 7x64 Firefox 45.0 x64

**uBlock Origin version:**
Unsure which one I was on prior.  Has happened through a number of versions, I install the latest dev each time it's happened.

##### Your filter lists  
* My Filters (defined below)
* uBlock Filters
* uBlock Filters - Badware risks
* uBlock Filters - Privacy
* uBlock Filters - Privacy 
* uBlock Filters - Unbreak 
* EasyList  
* Peter Lowe's Ad  server list  
* Easy Privacy
* Malware Domain List  
* Malware domains

##### Your custom filters (if any)
`@@||www.hlserve.com/Delivery/ClientPaths/Library/hook.js$script,domain=www.costco.com`
`www.abandonia.com###block-block-70 > .content > .fundingdiv`
`imgur.com###side-gallery`
`imgur.com###fixed-side-footer-links`
`imgur.com###inside > .post-pad.left > .post-container > .fixed-share-container`
##### Additional Info  
I also use uMatrix, and it's never occurred with that.

**Comment by gorhill** [comment]
There is no code in uBlock Origin to uninstall itself without the browser asking for it. So something else on your side is doing this. See <https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin>.

**Comment by Ketrel** [comment]
I didn't think it was intentional, I thought it may have been a glitch of some sort.

But I do use Avira as the AV.  I just checked the quarantine and the XPI is there.  I'll whitelist it.

Thanks.  Didn't realize it was actually getting removed rather than corrupted somehow.
