### ISSUE TITLE
Some "gallery" pages always reset back to first image when you click forwards 

### ISSUE THREAD

**Issue by bengb** [gorhill/uBlock#1491]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

On some pages with galleries of photos/articles, when you click forward to the second photo, the page seems to auto-reload and go back to the first image, so you can't move forward through the gallery. 

### One or more specific URLs where the issue occurs

http://www.muscleandfitness.com/workouts/workout-tips/5-best-exercises-every-beginner-should-perfect/netseer

This seems to be a problem especially with pages on this site.

### Steps for anyone to reproduce the issue

Go to the example page. Click on the right arrow on the main picture, this first goes to an ad which is displayed as blank grey, then click the right arrow again, and the page seems to reload back to the first gallery image. 

If ublock is disabled, the problem disappears.

### Your settings

I just use default settings.

- Browser/version: Firefox 45.0.1 (also on previous versions: 44.*)
- uBlock Origin version: 1.6.4

##### Your filter lists
Ublock default lists (except expertimental)
EasyList
Peter Lowe's Adserver List
EasyPrivacy
Malware Domain List
Malware Domains

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
https://forums.lanik.us/viewforum.php?f=64
