### ISSUE TITLE
uBlock sometimes when loading the page shows the blocked content

### ISSUE THREAD

**Issue by Ronnie91** [gorhill/uBlock#1494]
uBlock sometimes when loading the page shows the blocked content which then disappear at the end of properly loading.

uBlock sometimes misinterprets the filters like this: ###bannerPolicy , to function properly needs the filter is this: mediaworld.it###bannerPolicy

Here even with the filter as well: ###_evh-ric and not so : gazzetta.it###_evh-ric , remains a space.
![ublock origin bug](https://cloud.githubusercontent.com/assets/15952258/13933716/e260645a-efae-11e5-8707-4f0b727ee18c.png)
![ublock origin bug 2](https://cloud.githubusercontent.com/assets/15952258/13933715/e25a2b80-efae-11e5-972a-1ebec519d0cf.png)
Adblock Plus does not have these problems.

If you need more details, they are available.

I'm sorry for my english.

Best regards and thanks for everything.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

**Comment by gorhill** [comment]
@gwarser provided a link to the answer: by design.
