### ISSUE TITLE
uMatrix at the same time with uBlock with "behind-the-scene"

### ISSUE THREAD

**Issue by GitHubBlow** [gorhill/uBlock#1496]
### Describe the issue

Unclear documentation regarding "behind-the-scene" rule in uBlock.

I am using uBlock with uMatrix **at the same time.**

My uBlock rules:

```
no-remote-fonts: * true
no-strict-blocking: sourceforge.net true
behind-the-scene * * block
```

My uMatrix rules are

```
https-strict: * true
matrix-off: 127.0.0.1 true
matrix-off: 192.168.1.1 true
matrix-off: 192.168.2.1 true
matrix-off: about-scheme true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: opera-scheme true
* * * block
* * css allow
* * frame block
* * image allow
* * other block
* * xhr allow
* 1st-party cookie allow
Shitton of whitelisted domains.
```
Question.

Are my uBlock rules OK if I want "behind the scenes" shit stopped cold.

Thanks

### Your settings

- Browser/version: **Chromium 42.0.2298.0**
- uBlock Origin version: **uBlock Origin v1.5.6**
- uMatrix version: **uMatrix 0.9.3.1**

### Your filter lists

_Gary Oldman's voice_:EVERYTHING!

### For the people who reply with RTFM one word posts:

This page does not say anything about using uBlock behind-the-scene with uMatrix.
https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests

Also IIRC there was a wiki page titled "Using uBlock with uMatrix". No longer there.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
> Are my uBlock rules OK if I want "behind the scenes" shit stopped cold.

Yes (with exception of other extensions' `behind-the-scene` requests) but are you aware this disables downloading/updating filter list?

**Comment by GitHubBlow** [comment]
The only invalid thing here is your committment to documentation, as per normal software practices...

> There is nothing to say really: whoever is advanced enough to use uMatrix is able to understand where uBlock Origin and uMatrix overlap, and decide how to configure both extensions in such case.

...and not being a douchebag.

My 2 cents.

**Comment by gitarra** [comment]
This is a bug tracker. Not your personal support forum.

Also as [Mozilla Bugzilla etiquette ](https://bugzilla.mozilla.org/page.cgi?id=etiquette.html)puts it quite succinctly:

No obligation. "Open Source" is not the same as "the developers must do my bidding."
