### ISSUE TITLE
Add Websocket blocker to resource library

### ISSUE THREAD

**Issue by neuronix** [gorhill/uBlock#1497]
Services like revdefender use websockets to load anti-adblocking scripts. Currently, Chrome does not allow extensions to monitor websocket communication. A workaround would be to inject a small script replacing the Websocket definition by a dummy implementation.

Unfortunately, custom scripts are not allowed, so this would have to be included in the resource library.

**Comment by IDKwhattoputhere** [comment]
> Services like revdefender use websockets to load anti-adblocking scripts.

Got any example links? Until now I only came across an undesirable websocket [here](http://putlocker.is/watch-better-call-saul-tvshow-season-1-episode-1-online-free-putlocker.html): `ws://go.wsockd.com:9000/?id=115535`
Needs to be blocked by `||wsockd.com^$third-party` in EasyList.

**Comment by neuronix** [comment]
I just found a duplicate report here with an example: https://github.com/gorhill/uBlock/issues/956

However, please note that I am suggesting a real solution whereas in the original post there is none! Blocking inline scripts is unacceptable, dummy Websocket would be good.

**Comment by lewisje** [comment]
How would you propose ensuring this dummy implementation actually replaces the existing WebSocket definition? It could well be defined inside a closure, so that it's not open to interpretation by extension code.

**Comment by neuronix** [comment]
If the script is injected before all the others, they could not create a reference to the original object. You just need this kind of code (not exact, would need to check the Websocket API):
`window.Websocket = { connect: function () {}, send:  function () {} .... };`

I have seen other people suggest such code:
`var undefined; window.Websocket = undefined;`
But that could lead the third party code to use a polyfill or raise an error. The dummy code has the advantage of not raising errors and make the code fail silently.

**Comment by lewisje** [comment]
To be extra secure, try something like

```javascript
Object.defineProperty(window, 'WebSocket', {value: function WebSocket() {/* code */}});
```

that way, craftier anti-adblock mechanisms can't re-redefine it (though they could make a dummy iframe and pull out the `.contentWindow.WebSocket` from there, and apply it to the main `window`...)

**Comment by neuronix** [comment]
Didn't know about that, nice touch! :)

**Comment by laniakea64** [comment]
> make a dummy iframe and pull out the .contentWindow.WebSocket from there, and apply it to the main window

Nope, that trick would fail if this is implemented well.  "Dummy" iframes have about:blank URL (at least in Gecko-based browser), so provided it's technically possible to making sure to apply the redefine to about:blank (and any equivalents on other browser-platforms) should make that moot.

**Comment by lewisje** [comment]
Maybe an ES6 `Proxy` could ensure that whenever a new frame is created, the implementation of `WebSocket` inside that frame is re-defined to be the dummy, but I'm not that well-versed in the use of `Proxy` traps.

**Comment by laniakea64** [comment]
Do Blink-based browsers not have an equivalent of Gecko's [`content-document-global-created` observer notification](https://developer.mozilla.org/docs/Observer_Notifications#Documents)?

**Comment by lewisje** [comment]
I believe that's only for extension code: This is code that gets injected into the page.

**Comment by laniakea64** [comment]
Sorry, I wasn't being clear.  Yes it's only for extension code - thing is, extension can't know to inject code into the page (or otherwise run code in page context) without some kind of listener.  In Blink extensions, are such listeners limited to top-level `window`, thus forcing the injected code to do all the work finding and applying to any frames & sub-frames?

**Comment by lewisje** [comment]
I think I understand what you're getting at: I presume that the Chrome extension API has this capability (although I haven't checked), and then the way to keep the attack I described from working might be to use a rule like `*$subdocument,domain=bad.site,redirect=dummywebsocket`

...but I just remembered something else, all of the redirect resources are replacing scripts that would have been loaded over the network, but this proposal is to replace a native browser API, so there's nothing to block-then-redirect.

Maybe this could instead be done with a new `$websocket` option that leads uBlock Origin to dummy out the `WebSocket` API.

**Comment by gorhill** [comment]
> Maybe this could instead be done with a new $websocket option that leads uBlock Origin to dummy out the WebSocket API.

I like this idea. Will see what I can do.

By the way, as a rule I prefer to investigate/write the code myself, it's just how it works best for me.

**Comment by gorhill** [comment]
For the specific case raised here, `http://putlocker.is/watch-better-call-saul-tvshow-season-1-episode-1-online-free-putlocker.html`, the solution is this filter:

    ||oclasrv.com^$script,redirect=noopjs,domain=thevideos.tv

This prevent the blocked script from raising an error. A websocket is used when this the script from `oclasrv.com` is blocked.

**Comment by gorhill** [comment]
Tested working with `http://www.websocket.org/echo.html`.

**Comment by gorhill** [comment]
The issue is not taken care through a resource in the resource library. There is a special script injected for Chromium-based browsers only, which script communicates with uBO's main process through a specially crafted http/https network request, which purpose is solely to let uBO evaluate the URL used for the websocket URL. This allows to expose websocket connection attempts to the platform-independent code of uBO, hence static or dynamic filtering can block/allow websocket connections, and these will be reported in the logger like any other network requests.
