### ISSUE TITLE
http:*?tid=$popup closes tabs that are neither ads or popups

### ISSUE THREAD

**Issue by fluxtendu** [gorhill/uBlock#1499]
This filter: http:*?tid=$popup (which is in the FRA: EasyList Liste FR‎) closes tabs that are neither ads or popups...

You could try to right click and open in a new tab this link to a post from the kodi forum: [http://forum.kodi.tv/showthread.php?tid=252852](http://forum.kodi.tv/showthread.php?tid=252852). 

Steps to reproduce:
1) add FRA: EasyList Liste FR to your filter lists
2) Right click and open in a new tab any link to a post from the kodi forum

- Browser/version: Google Chrome 49.0.2623.87 m (64-bit)
- uBlock Origin version: 1.6.4

**Comment by SMed79** [comment]
Hi, 
[fixed](https://forums.lanik.us/viewtopic.php?f=91&t=29325#p89782), purge & update your filters lists.

**Comment by fluxtendu** [comment]
It's nice to have removed the filter from the list, but I'm not sure that's a normal behaviour for "$popup" to be active when a new tab is opened manually...

**Comment by gorhill** [comment]
I looked into this again this morning, with a rested mind.

> not sure that's a normal behaviour for "$popup" to be active when a new tab is opened manually

A site could create an invisible `<a>` tag which covers the whole page, and a click on the page would be perceived as a normal click, and the popup from such case would not be properly filtered and this case. So this was really a case of a way too broad popup filter.
