### ISSUE TITLE
Icons are broken with standard font set.

### ISSUE THREAD

**Issue by louipc** [gorhill/uBlock#15]
The issue is already well described here: https://github.com/chrisaljoudi/uBlock/issues/1181
Commits to fix are here: https://github.com/chrisaljoudi/uBlock/compare/a947537...53768aff22dba312ee86ce35885848e69b126e6a

**Comment by FrankNitty** [comment]
Can anybody explain this for the non tech guy. Is this issue going to be fixed in an upcoming release? I do not personally have this issue but a family member does have the broken icons and I have no idea how to fix it.
any help is appreciated.

**Comment by gorhill** [comment]
The extension's package contains [FontAwesome font file](https://github.com/gorhill/uBlock/tree/master/src/css/fonts), this is used to render various icons used in uBlock. Using icons as font simplify a lot maintenance. However the `--disable-remote-fonts` switch also affects local fonts, and this prevents the FontAwesome font file (which is local, part of uBlock package) from being loaded by uBlock, and as a result, no icons in the UI.

**Comment by FrankNitty** [comment]
Thank you for the explanation. The only question I have is, Is there something I can do on my end to fix it or do we need to wait for it to be fixed in an upcoming release?

**Comment by gorhill** [comment]
I don't know of anything else which can be done other than not using `--disable-remote-font`. I don't plan to release a fix for this in the next release, because that would delay unduly the release to the next week end at earliest. You could install [chrisaljoudi/uBlock](https://github.com/chrisaljoudi/uBlock) repo, it has the fix.

**Comment by FrankNitty** [comment]
I thank you for your patience in explaining it. I would rather continue using your releases.
Where Is The --disable-remote-font setting? Is that in ublock or in firefox itself? 
How do I not use it

**Comment by gorhill** [comment]
You can toggle the flag in `about:config`, as explained [here](http://www.techpowerup.com/forums/threads/disabling-web-fonts-in-mozilla-firefox-and-google-chrome.184198/).

**Comment by kintpuash** [comment]
This user style allows the user to only use a font they want while allowing font awesome to work. It requires Stylish of course.

Third party fonts are a potential privacy issue. I'm uncertain if the user style could address this. If the desire to use a specific font is driven by aesthetics then the user style should be a nice work around.

Fanboy's Anti-thirdparty Font list addresses the privacy issue to an extent. Fwiw, IceCat, the GNU version of Firefox is pretty keen on disabling fonts out of the box.

**Comment by louipc** [comment]
On Fri 17 Apr 2015 09:42 -0700, FrankNitty wrote:
> Thank you for the explanation. The only question I have is, Is there
> something I can do on my end to fix it or do we need to wait for it to be
> fixed in an upcoming release?
 
It's patched in the latest beta release of the chrisaljoudi maintained ublock.
https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.3.5-beta.2

**Comment by FrankNitty** [comment]
thank you all for your help and your hard work on the addon itself

**Comment by chrisaljoudi** [comment]
#154 addresses this.

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8083299/8b0af56e-0f51-11e5-8dcc-affe217da91c.png)

**Comment by RoxKilly** [comment]
@gorhill,

Either I'm missing something (probably) or there is still something unresolved here.  Even after disabling all remote fonts, I am still unable to prevent browserleaks.com tests from seeing the fonts installed on the machine, so font information is still leaking.

My setup before uBlock.o.  In Firefox Options >> Content Settings >> Advanced settings, I unchecked "Allow pages to choose their own fonts".  Running the test at http://www.browserleaks.com/fonts (javascript ON) showed no font leakage.

I installed uBlock.o and noticed that none of the icons were displayed.  So I returned to FF settings and checked "Allow pages to choose their own fonts".  Font info leaked as expected.  I then added the rule "no-remote-fonts: * true" and restarted the browser.  The uBlock.o UI is updated to show that fonts are blocked, however the browserleaks test can still see the fonts installed.  What am I missing?
![fonts_detected](https://cloud.githubusercontent.com/assets/12346501/8179190/fd6ba2e4-13e2-11e5-888e-2eb15cde3f4a.png)
![no_remote_fonts_rule](https://cloud.githubusercontent.com/assets/12346501/8179193/0b01e0f8-13e3-11e5-89fe-3fd5d1832213.png)

**Comment by louipc** [comment]
That is a nice feature but it doesn't address the bug.
The interface is still broken when using standard font set.
Is this a won't implement?

**Comment by gorhill** [comment]
It does fix the bug for people who wanted to disable remote fonts (as reported in the [original issue](https://github.com/chrisaljoudi/uBlock/issues/1181)). If your goal is to force web page to use a specific font, I consider this a [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=789788).

**Comment by louipc** [comment]
Not strictly a firefox issue. The interface breaks in chromium as well when launching with --disable-remote-fonts. Would be nice if it didn't break. Please reopen if you're open to solutions/ideas. thanks!

**Comment by gorhill** [comment]
> The interface breaks in chromium as well when launching with --disable-remote-fonts

That's the point of the fix, to not use `--disable-remote-fonts` and to let uBlock do the blocking of remote fonts instead.
