### ISSUE TITLE
[Feature Request] Blocking of Similar Type Elements

### ISSUE THREAD

**Issue by Kalpit1** [gorhill/uBlock#1500]
I was using Quora , every time I get a sign up dialog.
I use to block it every time.

I just wondered, it would be great if it is blocked for all quora pages instead of picking out each time.

The element code keeps on changing every time.
But here's one of them.
www.quora.com###__w2_redeVi3_signup_wall_wrapper > .new_signup_dialog.modal_bg

"w2_redeVi3" part only changes rest is same for all Quora pages.

You may test it with 
https://www.quora.com/Google-Interview-Questions/If-algorithmic-problem-solving-is-what-they-want-to-test-why-dont-they-hire-top-rated-TopCoder-Codeforces-directly-taking-only-HR-and-Behavioral-rounds
And then click another question below. Then you will get a message to sign up.

I'm using 1.6.5rc4 u Block Origin on Android Firefox 45.0

**Comment by Kalpit1** [comment]
@gorhill

I think there can be a feature in uBlock Origin's Cosmetic filtering to block elements of same genre.

For example,
Cosmetic filtering in this case. 
There can be such cosmetic filter like-
http://www.quora.com/###__w2_*_signup_wall_wrapper

This would block all elements with same format and having anything in place of *

Thank You.

**Comment by gorhill** [comment]
You opened an issue without first reading the available documentation -- there is a proper solution for what you want. Please, **read carefully** the documentation about how to [write filters](https://adblockplus.org/filters#elemhide).
