### ISSUE TITLE
Have uBlock last in the plugins-filtering list (Or: Play nicely with Decentraleyes)

### ISSUE THREAD

**Issue by gsurrel** [gorhill/uBlock#1501]
(Sorry for the issue title, I couldn't find a better one)

I am currently browsing by blocking by default all third parties. I think using [Decentraleyes (local CDN as a Firefox plugin)](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) is a good way to restore the functionality of websites while limiting tracking and network load.

The problem is that uBlock blocks the requests before Decentraleyes can provide the local version. Is it possible to set uBlock at the very end of the chain of plugins working on the requests made by the browser?

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0
uBlock Origin: 1.6.4

**Comment by harshanvn** [comment]
Am not sure if that can be done. And i think it is better to resolve this issue by manually white-listing that particular file in uBlock. And it is a safer approach.

**Comment by IDKwhattoputhere** [comment]
https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on

**Comment by gsurrel** [comment]
Oooh, thank you, it's (almost) exactly the kind of things I was looking for! Thanks!

**Comment by gorhill** [comment]
The browser decides to which add-on to dispatch and when, it's out of control of uBO.
