### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by tsogreg** [gorhill/uBlock#1503]
It's been working perfectly until the recent Chrome update.  Now I see ads everywhere.  And clicking on the logo next to the url bar results in no drop down window.

Possibly unrelated but the browser appears to hang more often.

It seems others are having the same issue such as "Alexandra Mims Pike" here
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/reviews

Mac OSX 10.9.5
Chrome Version 49.0.2623.108 (64-bit)
uBlock Origin 1.6.4

**Comment by Gorneman** [comment]
Linux Mint 17.3 - Firefox 45 - uBlock not work and button is gone

**Comment by gorhill** [comment]
Did you try re-starting uBO?

**Comment by tsogreg** [comment]
No, previously I tried re-starting the browser and computer.

Re-starting uBO has set things right again. Thank you.

**Comment by Gorneman** [comment]
Refresh Firefox and reinstall uBlock and problem is gone

**Comment by timthelion** [comment]
I had the problem that the blocker stopped blocking on two separate computers both running Debian Jessie and Chromium. Dissabling and re-enabling solved it on one computer but not on the other.

The computer that is fixed after dissabling+re-enabling is running chromium Version 49.0.2623.108 Built on 8.3, running on Debian 8.4 (64-bit).

The computer tha isn't fixed is running the same version, but 32 bit.

![ublock](https://cloud.githubusercontent.com/assets/1391608/14761368/619ceae4-095f-11e6-919f-182087149cd4.png)

**Comment by gorhill** [comment]
uBO appears working in your screenshot. There is too much information missing, I have no idea of what your settings are, which filter lists are in use, how many filters are in effects, what is the exact URL of the page in your picture, etc.

**Comment by IDKwhattoputhere** [comment]
Have you disabled element hiding filters in one of the available ways? Use the button to reset settings in uBO's settings if you're not sure.

**Comment by timthelion** [comment]
Aha, @IDKwhattoputhere thank you for your reply! This fixed the problem :)

Tim

**Comment by gorhill** [comment]
Looks like it's just the not so uncommon issue of when uBO updates, for some reasons the browser does not always restarts the extension properly. Forcing a reload of the extension after an update usually fixes this.
