### ISSUE TITLE
Regular expression in element hideing

### ISSUE THREAD

**Issue by Tojkar** [gorhill/uBlock#1508]
When blocking ads in a specific web site, uBlock leaves an unnecessary empty element behind. I can hide the element with the element picker, but the ID of the element is random, so I'd have to hide it hundreds of times.

I have tried to create a regular expression rule in my filter tab unsuccessfully. I have read all the related documentary from uBlock, Adblock and various other sites that explains regular expressions, but I have only very basic knowledge coding and reg exp, so I must be missing something fundamental to get this working.

This is a short list of individually blocked elements:
www.example.net###MTYxM
www.example.net###MTgxM
www.example.net###MjExM
www.example.net###MjIxM
www.example.net###MDgxN
www.example.net###MTAxN
www.example.net###MTMxN

The first letter is always capital "M", followed by four random letter with random case. How can I hide those element with single reg exp filter?

I think it's unnecessary to show examples of what I've tried as everything so far has been unsuccessful.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
Regexp is only supported in blocking filters, not hiding filters; the closest thing you can do in a hiding filter is `www.example.net##[id^="M"]` but you can't specify the number of characters or what range they can be in.
