### ISSUE TITLE
[Chrome] Sync limit(?) in 3rd-party filters lists, custom filters, custom rules and whitelist?

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#1510]
### Describe the issue

I'm not sure, but this looks like a sync limit(?) (I'm not sure, how to name that) in custom rules (and also in 3rd-party filters lists, custom filters and whitelist) :/

---
### One or more specific URLs where the issue occurs

uBlock Origin settings > My rules (or 3rd-party filters/My filters/My whitelist)

---
### Screenshot in which the issue can be seen

![27-3-2016 r 23 57 31](https://cloud.githubusercontent.com/assets/5713816/14068078/5c286cce-f478-11e5-85cd-2b5cd8975f21.gif)
Not a screenshot, but video-like (GIF actually, because AVI file is too large for GitHub :/) file to better explain (video-like file recorded around 27 March 2016 at 23:57 [23:57 in Poland]).

For those, who don't see the date because of pixels on the GIF (yeah, I know, I need a new GPU, because my actual will die soon), the date is **27 March 2016** at **22:50:51 CEST**

---
### Steps for anyone to reproduce the issue
1. Open uBlock Origin settings,
2. Enable cloud syncing,
3. Go to "My rules" section, import
   [my dynamic rules settings and don't change it in the extension](https://github.com/gorhill/uBlock/files/191123/ublock-dynamiczne-reguly_27.03.2016._16-55-35.txt) (but before doing that, YOU MUST BACKUP ALL YOUR SETTINGS!),
4. Try to export to the cloud on Chrome (~~I'm not sure how with Firefox :P~~ #Update: Everything is fine on Firefox).

---
### Your settings

| Disabled | Enabled |
| --- | --- |
| Hide placeholders | Show blocked elements on uBO's icon |
| Don't display tooltips | Enable context menu |
| Color-blind friendly | Enable cloud syncing |
| Disable pre-downloading | Enable advanced features |
| Don't track clicked links | Prevent IP address leaking in WebRTC |
| Disable cosmetic filtering | Block remote fonts |
| Disable large media (with default amount) |  |

(#Update: About settings listed above in the table, it changed a bit, I mean I have **enabled** "Hide placeholders" and "Disable pre-downloading")

- Browser/version: Newest stable Chrome for Windows XP – 49.0.2623.108 (#Update: But also on newest 64-bit Chrome on Windows 10 Anniversary Update),
- uBlock Origin version: Newest avalaible from Chrome Web Store – 1.10.4.

---
##### Your filter lists

All uBlock Origin's and default filters lists + all ads filters lists + all privacy filters lists + all malware filters lists + all social filters lists + all multifunctional filters lists + all CHN, KOR & RUS filters lists + CZE, DEU, FRA, HUN, JPN & POL filters lists.

(#Update: It changed a bit now, but actually I have more filters lists enabled not less, similar with my custom filters lists).

---
##### Your custom filters (if any)

![27-3-2016 r 23 10 20 ubo wl filtry](https://cloud.githubusercontent.com/assets/5713816/14067909/9de559bc-f471-11e5-8973-e74e555ce625.png)
The two of three blurried positions is the HTTP version of two default filters lists in uBlock Origin (because I'm on XP and Chrome doesn't support old security protocols like SSL3). About the third one – ~~I have it for safety, because maybe one day that filters list will be back (I can't find the newest mirror of it :/) and I disabled that filter.~~ I had it for safety (and I still I have it :P), but looks like the author of that filters has returned with his filters and he's still doing them (the old address was http://bidgewalbelp.neocities.org/filters.txt and the new is https://satterly.neocities.org/filters.txt).

**Comment by gorhill** [comment]
Look in the [uBO's dev console](https://github.com/gorhill/uBlock/issues/736#issuecomment-152739446).

**Comment by Piter432** [comment]
Hmm, strange. No errors. Maybe one of the Chrome's flags has an influence on it? :/

**Comment by Piter432** [comment]
Okay, now I can tell something more about this.

- I tried to reset flags in chrome://flags – it didn't help
- I checked many times using uBO's dev console – no errors or warnings, which is strange
- It looks like that sync limit(?) is also on 3rd-party filters lists, user filters and whitelist, because I can't export to the cloud, when there're too many data in the uBO to sync (if you know what I mean :P) [currently, I can export to the cloud user filters and whitelist, because there's not too many data in this sections, if I named it correctly]

Any ideas? Or maybe it's not the uBO's/Chrome's extensions' problem, but the Chrome's problem itself?

**Comment by gorhill** [comment]
I plan to add code to relay error code of failed of sync attempt to the UI.

**Comment by Hrxn** [comment]
Well, I think it's safe to assume that there is some kind of limitation for Chrome's sync feature.

Have you looked here? : chrome://sync-internals

Maybe there is something of use..

**Comment by Piter432** [comment]
@Hrxn: I just looked there, but... there's so many info there :P

**Comment by Piter432** [comment]
How the work going on this, @gorhill?

**Comment by gorhill** [comment]
I did no work on this. I will try to remember to do something about this for the next release.

**Comment by Piter432** [comment]
Okay, I'm not sure what you did with this, @gorhill, but looks like it's uBO bug in Chrome or Chrome's bug or Chrome's limitation. I'm using now Windows 10 Pro with Anniversary Update. Of course the OS is 64-bit, but the bug(?) still occurs and I don't know what to do 😕

**Comment by Piter432** [comment]
Any news on this, @gorhill?

**Comment by Piter432** [comment]
Strange, I've updated my Windows 10 from Anniversary Update to Creators Update (I skip that update made some problems to my PC) and... I can now synchronize settings of 3rd-party filters lists (I'm 100% sure that before installing Creators Update I couldn't do that). However, after “resetting” “My rules” to almost default one and start configuring it (the uBO's “My rules” tab) from the beginning, I've imported my old file with saved “My rules” section settings and... these settings in this tab couldn't be synchronized.
## WHAT THE HELL? XDDDD

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/30705319-1b0cd526-9ec3-11e7-923d-8a708c225458.png)
