### ISSUE TITLE
Few issues in uBlock 1.6.6

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1511]
Browser/version:  Firefox 45
uBlock Origin version: v1.6.6

1) When you backup uBlock filter lists/custom list settings and restore them back, only the default included lists preferences are loaded correctly. The custom filter URLs added are ALL added and the ones which were commented out before the backup are also loaded as enabled.

2)  If the link is too long when adding a filter through the logger, the desktop refreshes by itself. Can be reproduced by just clicking in static filtering "which URL address matches" if the url is long enough e.g. try one from a google search

**Comment by IDKwhattoputhere** [comment]
It is preferred to open one issue per bug and not one for multiple bugs.

2) I too do have this problem. An example would be to create a static filter for the CSS from nocookie.net on [this site](http://spongebob.wikia.com/wiki/List_of_deleted_scenes). I'm using Windows 7 and trying to select a different pre-defined URL that should be filtered crashes the aero design. The screen goes black for a second and when running the problem diagnosis it fixes the problem and says the Desktop Window Manager was deactivated. I suppose Windows can't handle the text continuing that far outside the screen.

**Comment by gorhill** [comment]
1) There is an issue opened about this already.

2) I can reproduce this on both Chromium and Firefox, and Linux/Cinnamon. HTML markup should not cause any crash -- so surely an issue should be filed with both Chromium/Firefox. But given the seriousness of the issue, I will try to provide a workaround.
