### ISSUE TITLE
About Filter lists from around the web

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#1513]
Hi.I have a problem about this site.In previous design of this filter list page there was the information about the filters which can cause web site breakage.But there is no information in this new design.Therefore I can not find which filter cause the breakage.Could you add this information again?Thanks.

**Comment by collinbarrett** [comment]
hi, @mozkan007 , maintainer of [filterlists.com](https://filterlists.com/) here. we are planning to add breakage information to FilterLists in the very near future, we are just in the process of evaluating the best way to do that. If you have any suggestions as to ways we could do that or breakage information about specific lists, please let us know. at this point, it looks like it will just be a very manual process to maintain such a feature. thanks so much!

**Comment by mozkan007** [comment]
Thank you very much.
