### ISSUE TITLE
uBlock is blocking the signup form of my website

### ISSUE THREAD

**Issue by dangrossman** [gorhill/uBlock#1517]
### Describe the issue

I've run a free web stats site called W3Counter for 12 years. It provides basic web stats reports and hit counters, with no cross-site or global tracking. 

Recently, people started telling me that they can't sign up. When they submit the signup form, they are returned to it as if they submitted nothing. 

Upon investigating, these people were all running uBlock. uBlock is preventing people from submitting the signup form. I don't think this is something intentional; the signup form is not an ad or a tracking script.

### One or more specific URLs where the issue occurs

https://www.w3counter.com/signup

### Steps for anyone to reproduce the issue

1. Go to https://www.w3counter.com/signup
2. Fill out the form
3. Submit the form
4. Be returned to the form with all the inputs blanked out, as if you didn't fill them out

### Your settings

I was able to reproduce the issue by installing uBlock Origin 1.6.4 on Chrome 49 for Windows.

##### Your filter lists

Defaults. I have changed no settings.

**Comment by gorhill** [comment]
Purge one uBO's filter list, then force an update.

**Comment by dangrossman** [comment]
That was very quick, thank you very much
