### ISSUE TITLE
Force quitting firefox causes saved sessions to fail on next start

### ISSUE THREAD

**Issue by kr094** [gorhill/uBlock#1518]
Force quitting firefox through windows shutdown causes the saved session to fail on next start. Tested with safe mode and exclusively with ublock enabled. 

Steps to reproduce:

1. Open any URL in firefox (I tested with youtube.com)
2. Force quit firefox via task manager with "End Process Tree". This can also be a windows shutdown or logout
3. Restart firefox
4. Page showing "Whoops, this was embarrassing" and the previous session tabs are displayed

OS: Windows 7
Browser: Firefox 45.0.1
UBlock: 1.6.6 / Default filter settings

My rules:

    no-popups: blank.about-scheme true
    no-strict-blocking: blank.about-scheme true
    no-strict-blocking: softonic.com true
    no-strict-blocking: sourceforge.net true
    behind-the-scene * 3p noop
    behind-the-scene * 3p-frame noop

Temporary rules

    no-popups: blank.about-scheme true
    no-strict-blocking: blank.about-scheme true
    no-strict-blocking: softonic.com true
    no-strict-blocking: sourceforge.net true
    behind-the-scene * 3p noop
    behind-the-scene * 3p-frame noop

The blank.about rules might be the cause of this?

**Comment by gorhill** [comment]
How did you conclude this is a uBO's issue?

**Comment by kr094** [comment]
Enabling one add on at a time and re-trying my test case. I have 3 add ons:
uBO
Greasemonkey
Firebug

**Comment by gorhill** [comment]
You say

> The `blank.about-scheme` rules might be the cause of this?

Did you try to answer your own question by trying to reproduce without these rules?

**Comment by kr094** [comment]
Yes, opening ublock on the new tab page doesn't allow me to enable/disable the power button.

**Comment by gorhill** [comment]
Alright, will do this: what you describe is a normal Firefox behavior, nothing to do with uBO. Open if and only if you explain very clearly what is actually wrong, along with supporting evidence that uBO is causing whatever you think is wrong.

**Comment by kr094** [comment]
I've managed to reproduce the issue already and confirmed it is with ublock. It does not happen in firefox safe mode. I've read your contributing doc and made sure to test this thoroughly

**Comment by kr094** [comment]
And it doesn't seem I can reopen github issues: https://github.com/isaacs/github/issues/583

**Comment by gorhill** [comment]
You say:

> Page showing "Whoops, this was embarrassing" and the previous session tabs are displayed

What are you actually reporting that you think is wrong? When Firefox crashes, this is actually exactly how it is supposed to behave.

**Comment by kr094** [comment]
But that behavior doesn't happen in safe mode

**Comment by kr094** [comment]
My apologies, Raymond. I resolved the issue by following the steps listed here. https://support.mozilla.org/en-US/questions/956252
