### ISSUE TITLE
Multiple selection option for element picker

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#1519]
Hi.I want to a request from you about element picker.Element picker is quite perfect feature for Ublock origin.So I use this feature on many websites constantly and it makes easy to my blocking work.However occasionally I have to use  element picker feature many times, for blocking numerous parts of some websites.So the process that blocking too much thing is very tiring for me.Therefore, could you add multiple selection at the same time option, into element picker feature?If you do that, it will be better for users.It is just an advice from me to you.Thank you.

**Comment by anewuser** [comment]
> Do **NOT**:
> 
>     Submit pull requests.
>     Submit design ideas.
>     Submit feature requests.

[CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
How would that be possible if you need to create a filter per element you want to block?

**Comment by curiosity-seeker** [comment]
This feature is already available:

https://www.youtube.com/watch?v=kO0Mh-SAkHM

**Comment by mozkan007** [comment]
Thank you.I learned how I can do this.The topic can be closed.

**Comment by anewuser** [comment]
@mozkan007 There's a button for you to do that by yourself below the area where you typed your comment.
