### ISSUE TITLE
Page rendering garbled in Firefox

### ISSUE THREAD

**Issue by Lastique** [gorhill/uBlock#152]
Opening [this](https://software.intel.com/sites/landingpage/IntrinsicsGuide/) page in Firefox 37.0.2 with uBlock Origin 0.9.5.0 results in garbled text. The page is displayed correctly with uBlock disabled and in Chrome with uBlock Origin.

![firefox_snapshot2](https://cloud.githubusercontent.com/assets/1589747/7393311/ab6e81fe-ee95-11e4-92df-6cec650cc613.png)

PS: I also created a similar issue for uBlock (https://github.com/chrisaljoudi/uBlock/issues/1334). Not sure if duplicating the report was the right thing to do.

**Comment by gorhill** [comment]
Unable to reproduce with the limited information provided. Will close after one day if no [more information](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include) is provided.

**Comment by ozar** [comment]
That page seems to be loading fine for me, with the same browser and uBlock version.

**Comment by Lastique** [comment]
- I'm running on Kubuntu 14.10, x86_64, opensource AMD video drivers from the official Kubuntu repo. As mentioned, Firefox 37.0.2 (from the official repo), uBlock Origin 0.9.5.0.
- [Here][1] is the configuration for uBlock Origin.
- To reproduce it is enough to follow the link and wait until the page loads (the "Loading..." text should get replaced with the list of intrinsics). In my case I can see the list for a brief moment, then it is replaced with the corrupted image presented on the screenshot.
- The only other addon I have is Ubuntu Firefox Modifications 3.0. Disabling it and restarting Firefox does not help.

[1]: https://gist.github.com/Lastique/57ebf900130638660fd1

**Comment by gorhill** [comment]
Issue is with 3rd-party _RUS: BitBlock List_. Same issue with ABP + _RUS: BitBlock List_. Report to maintainers of that list.

Workaround in uBlock Origin: toggle cosmetic filtering switch for the site (in popup UI).
