### ISSUE TITLE
3rd-party filter rules should not override personal blocker rules

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#1520]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I found that an EasyList classification of an image overrides a personal blocking rule for an image which I created using element picker.

### One or more specific URLs where the issue occurs
https://en.wikipedia.org/wiki/Murder_of_Du%27a_Khalil_Aswad

### Steps for anyone to reproduce the issue
1. Open the page above, open element picker.
2. Create a filter for one of the image elements on that page, mine is the following:
! 1.4.2016, 02:44:46 https://en.wikipedia.org/wiki/Murder_of_Du%27a_Khalil_Aswad
||upload.wikimedia.org/wikipedia/en/thumb/2/25/AswadStoning.jpg/220px-AswadStoning.jpg
3. Reload the page.

Result:
Image element is not blocked anymore due to easylist overriding the images on upload.wikimedia.org as whitelisted. However, I think that specific user-rules should override even easylist.

### Your settings
- Browser/version: Firefox Nightly 48.0a1 
- uBlock Origin version: 1.6.6

##### Your filter lists
Default filter lists

##### Your custom filters (if any)
(see above).

**Comment by tobbi** [comment]
I just read https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page and I it is my opinion that personal filter rules should have precedence over 3rd party rules.

**Comment by gorhill** [comment]
Use the `important` filter option -- that's its purpose.

**Comment by tobbi** [comment]
Thanks!
