### ISSUE TITLE
Doesn't block Video Ads

### ISSUE THREAD

**Issue by habakook** [gorhill/uBlock#1521]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Ad runs at the beginning of the video.

### One or more specific URLs where the issue occurs

http://politrussia.com/ekonomika/laquo-yamal-spg-raquo-zatyagivaet-989/

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/4162734/14197556/6f2e6aa8-f784-11e5-9e79-d7f0fb10e953.png)

### Steps for anyone to reproduce the issue

1. Click on the video at http://politrussia.com/ekonomika/laquo-yamal-spg-raquo-zatyagivaet-989/
Observe: Ads runs

### Your settings

- Browser/version: Chrome/48.0.2564.116
- uBlock Origin version: 1.6.4

##### Your filter lists

"Default filter lists"

**Comment by anewuser** [comment]
@habakook, you can't expected uBlock Origin to block sites on **Russian** sites using the **French list**. Check the two Russian lists in the settings, and in case the ad is still displayed, report it to the **list authors**.

> Issues with 3rd-party filter lists are the responsibility of their respective maintainers.

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by habakook** [comment]
Didn't realize about the filters. The FRA one I copied from the template
about the bug.
Once I found how to apply russia filters it worked!
Thanks, whoever you are!
