### ISSUE TITLE
uBlock Unbreak filter for tags.tiqcdn.com unnecessarily exposes users

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#1522]
`uBlock filters -- Unbreak` has the rule: 
`@@||tags.tiqcdn.com/utag/*.js$domain=cnet.com|weather.com,script`.  This prevents cnet.com from breaking but at the cost of allowing all the tracking scripts from `tags.tiqcdn.com`.

A better approach may be: 
`||tags.tiqcdn.com/utag/*.js$domain=cnet.com|weather.com,script,redirect=noopjs` which redirects the request to a local inert script and therefore has no privacy/tracking downside.

To test, go to [this CNET article](http://www.cnet.com/news/feds-have-asked-google-for-help-breaking-into-phones-too/), and watch the logger. With just the default filters, about 8 JS files from `tags.tiqcdn.com` are executed. Blocking that domain altogether breaks the page (it's not possible to load and view the comments beneath the article). However, things work once again when the 2nd rule above is used. I did not test `weather.com` with the new rule because I don't know the breakage that the original rule was trying to address.

I suggest that before allowing a 3rd party script to run for the purpose of unbreaking a site, we check whether the existing `noopjs` might work.

**Comment by gorhill** [comment]
> I suggest that before allowing a 3rd party script to run for the purpose of unbreaking a site, we check whether the existing noopjs might work.

That's what I do. That exception filter was put in there way before `redirect` filter option was implemented.

Thanks for the finding, I will indeed add the redirection. I will investigate `weather.com`, I think I vaguely recall it was breaking video playback.
