### ISSUE TITLE
[question] Ublock origin on MS Edge ?

### ISSUE THREAD

**Issue by Mezuv** [gorhill/uBlock#1523]
Hi,

I work as a independent jurnalist and currently im writing article about yesterdays MS build conference, and for MS new browser Edge.It was announced that popular adblocking software is coming this summer.
My question is are you planning to make Ublock origin for MS Edge ?
And where do you see MS claims that porting extensions from Chrome for Edge is simple and easy task ? 
![img_1686_story](https://cloud.githubusercontent.com/assets/18211083/14204312/ba5aad28-f803-11e5-8167-cdf80342026e.jpg)

**Comment by gorhill** [comment]
See #1486.

**Comment by Hrxn** [comment]
I can help you with one thing, regarding this claim:
> MS claims that porting extensions from Chrome for Edge is simple and easy task 

That claim is true, the APIs used by Edge are very similar to those in Chrome. They clearly had compatibility here in mind. :smile:
