### ISSUE TITLE
readUserAsset vs readCacheAsset in assets.js

### ISSUE THREAD

**Issue by yansh** [gorhill/uBlock#1524]
Clarification question regarding the implementation of  ```readUserAsset``` and ```readCacheAsset``` functions. Why have the same functionality implemented twice?

https://github.com/gorhill/uBlock/blob/master/src/js/assets.js#L985-L1019

**Comment by lewisje** [comment]
I guess it's in case he decides to implement the two functions differently in the future.

**Comment by yansh** [comment]
@gorhill is that so?

From my understanding "user assets" are meant to be read from external files located in ```assets/user/``` .

**Comment by lewisje** [comment]
I guess if he wants more type-safety, he could validate the first few characters of the `path` argument to each function; that's one way "to implement the two functions differently" albeit not a major way.

**Comment by gorhill** [comment]
The implementation for `readUserAsset()` should change to a more sensible one. Conceptually, a user's custom filters are not cached, so ideally they should not be treated as such, they should just be saved as any other user settings, a plain string. Currently saving as a cache entry cause code path exceptions in there which should be removed eventually -- i.e. the code to purge all caches [should not have to be careful](https://github.com/gorhill/uBlock/blob/master/src/js/assets.js#L263) to not flush the cache entry reserved for a user's custom filters.

**Comment by yansh** [comment]
Thanks. quick follow up:
 >  Conceptually, a user's custom filters are not cached, so ideally they should not be treated as such, they should just be saved as any other user settings, a plain string keyed on something like customFilters.

Why not use something like ``readExternalAsset`` instead?

**Comment by gorhill** [comment]
`redExternalAssets()` is for external filter lists, can be any URL.
