### ISSUE TITLE
uBlock popup control panel not being displayed with pentadactyl

### ISSUE THREAD

**Issue by vague666** [gorhill/uBlock#1527]
The default behaviour for pentadactyl on Firefox is to hide the toolbar where the addressbar and searchbar recide, which leads uBlock to not display the popup window when clicking the icon.
If the setting for pentadactyl is instead changed to :set guioptions=bCrsT where T stands for toolbar the popup window can be viewed

- Browser/version: Firefox 45
- uBlock Origin version: uBlock Origin v1.6.7rc0 (I've tried with the current stable version 
                                          also with the same results)

**Comment by anewuser** [comment]
If you are consciously using a third-party piece of software that disables such popups, why are you complaining about it to the developer of uBlock Origin, who has nothing to do with it?

**Comment by gorhill** [comment]
@AlexVallat says in <https://github.com/chrisaljoudi/uBlock/issues/1315>:

> The legacy button will automatically be used if CustomizableUI is not available in the browser at all, but if it is available and just not working properly (probably because you've hidden the navigation bar, and probably by using Pentadactyl or Vimperator) then you can force it to use the legacy button by setting the `about:config` preference `extensions.ublock.forceLegacyToolbarButton` to true and restarting the browser. I'm not sure if we need any more user friendly way of doing this, but my current opinion is that if a user is advanced enough to be breaking Australis by hiding the nav bar (or anything else) they can probably cope with setting a preference manually.

Just use `extensions.ublock0.forceLegacyToolbarButton` instead for uBlock Origin.
