### ISSUE TITLE
I can't filter this elements

### ISSUE THREAD

**Issue by KwToPA** [gorhill/uBlock#1529]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
can't filter this elements

### One or more specific URLs where the issue occurs

URL:http://www.tuku.cc/comic/126/n-1425373142-87605/

### Screenshot in which the issue can be seen

http://i.imgur.com/MVv7sk0.png
### Steps for anyone to reproduce the issue

When I enter the elements picker mode, I can't pick this AD
### Your settings

default settings

- Browser/version: chrome 49
- uBlock Origin version: 1.6.6

##### Your filter lists

Default filter lists minus uBlock -- Badware risks

##### Your custom filters (if any)

I find this code in developer tools, How  can I filter this AD 
 
`<div id="ft_right_bottom" style="position: fixed; bottom: 0px; z-index: 2147483647; overflow: hidden; right: 0px;"><div style="margin: 0px; padding: 0px; width: 300px; height: 250px;"><div style="position: absolute; z-index: 1;"><a href="http://c.jk2h.com/s/1/1383/0.html?uid=310198&amp;ext=YTIxNTtWMjY9NSknZGFkZmsoa25pZltYY2dnKmZpbmFZU2VobCNjaHFjYldfZ2svYGd0YVtXYmtrK2Jpbm1ZXGZl" target="_blank" style="width: 300px; height: 250px; display: block; opacity: 0.1; background: url(&quot;http://img.feitian001.com/img/r/dot.gif&quot;);"><img src="http://img.feitian001.com/img/r/dot.gif" border="0" width="300" height="250" style="background-color: transparent;"></a></div><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,24,0" width="300" height="250" align="middle"><param name="movie" value="http://c.jk2h.com/b/1/1383/gdd9fid.swf?uid=310198"><param name="quality" value="high"><param name="wmode" value="transparent"><embed pluginspage="http://www.macromedia.com/go/getflashplayer" width="300" height="250" align="middle" type="application/x-shockwave-flash" src="http://c.jk2h.com/b/1/1383/gdd9fid.swf?uid=310198" quality="high" wmode="transparent"></object></div><div id="ft_rich_close" kc="false" style="z-index: 1998349; top: 3px; left: 264px; width: 25px; height: 13px; position: absolute; display: block;"><img src="http://img.feitian001.com/img/r/close.gif" ck="ft_rich_close_hide" style="width: 25px; height: 13px; cursor: pointer;"></div><div style="z-index: 1998349; top: 234px; left: 240px; width: 60px; height: 16px; position: absolute;"><a href="http://www.feitian001.com" target="_blank"><img src="http://img.feitian001.com/img/r/logo.gif" style="width: 60px; height: 16px; border-style: none;"></a></div></div>`

**Comment by gorhill** [comment]
The site is constantly modifying (lowering) the `z-index` of uBO's element picker, making it impossible to select any element above the picker.

I need to see if I can prevent this, for now you can use `tuku.cc###ft_right_bottom` to hide the element.

**Comment by KwToPA** [comment]
Thanks man
