### ISSUE TITLE
loopconversation.about-scheme keeps coming back when you comment or remove it from Whitelist

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uBlock#153]
1. Comment or remove `loopconversation.about-scheme` from the "Whitelist"
2. Reload uBlock Origin in `chrome://extensions/`
3. Go back to "Whitelist"

`loopconversation.about-scheme` is back.  Happens in both Chrome and Firefox.

![ublockoriginloopconversation](https://cloud.githubusercontent.com/assets/6408935/7395444/c5e7007a-ee4e-11e4-8bb2-b375c6e38909.gif)

```
uBlock Origin 0.9.5.1
FF 37.0.2  and Chrome (stable)
Win XP
```

**Comment by gorhill** [comment]
Yes, this happens only for the dev version, it won't happen in the official release version, because the version number will go up.
