### ISSUE TITLE
Documentation: There should be a uBlock Ontology

### ISSUE THREAD

**Issue by Bartolomeus-649** [gorhill/uBlock#1530]
In the page [Dynamic filtering: quick guide](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) the term `site` is used without explaining or defining it.

Possible interpretations of `site` for the URL: `http://www.SubDomain.Domain.com/RootPath/Folder/Page.html`
- Any content from the host: `www.SubDomain.Domain.com` is part of the `site`.
- Any content from any host in the domain: `SubDomain.Domain.com` is part of the `site`.
- Any content from any host in any sub-domain in the domain: `Domain.com` is part of the `site`.
- Content from any host matching the domain for the cookie set by the current page. For example if a response set the domian of it's cookie to `SubDomain.Domain.com`then content from any host in that domain would be part of the `site`, and for a cookie with a domain of `www.SubDomain.Domain.com`, only content from that specific host whould be considered part of the `site`.
- Only content matching the `path` for the cookie set by the current response.  For example, if a response sets a cookie with the path `/RootPath/Folder`, then only content matching that path is considered to be part of the `site`.

I am sure there are even more possible interpretations of the term `site`.

I suggest there should be a uBlock [Ontology](https://en.wikipedia.org/wiki/Ontology_%28information_science%29), where all terms, names and concepts used within the _uBlock Universe_ should be defined.

**Comment by gorhill** [comment]
https://en.wikipedia.org/wiki/Website

**Comment by lewisje** [comment]
In context, it looks like "site" means "base domain" (a subdomain of a public suffix, which is itself not a public suffix, or roughly a registrable domain name, with exceptions for cases like subdomains of cloudfront.net, which are all considered base domains even though cloudfront.net is actually a registered domain name).

**Comment by smilingredhead** [comment]
Hey @Bartolomeus-649  I'm currently working on this Ontology. Can you please clarify the scope of the ontology? Do you mean the terms in the wiki, the specific page you linked to, or terms used in the programming files? 

Thank you,
Team Rocket

**Comment by Bartolomeus-649** [comment]
the scope is that there should be one and only one possible interpretation of any term used

**Comment by smilingredhead** [comment]
@Bartolomeus-649  Would this be something you're looking for? [uBlock Ontology](https://github.com/Team-Rocket-FIT-2017/uBlock/wiki/uBlock-Origin-Ontology)

**Comment by Bartolomeus-649** [comment]
Yeah, something like that. I would have put the term as the first word, followed by the explanation.
Also it is imperative that the terms described are used consistently throughout the uBlock applications, apps, plugins, sites, documentation and so on.

**Comment by gorhill** [comment]
Closing as too vague. Documentation can be freely edited at <https://github.com/uBlockOrigin/uBlock-issues/wiki>, so whoever is welcome to improve it rather than have requests being made for _someone else_ to improve it.
