### ISSUE TITLE
Firefox Extension-Reuse Vulnerabilities

### ISSUE THREAD

**Issue by curiosity-seeker** [gorhill/uBlock#1534]
@gorhill: This post is meant to inform you about a paper that presents a new vulnerability targeting Firefox extensions:

https://www.internetsociety.org/sites/default/files/blogs-media/crossfire-analysis-firefox-extension-reuse-vulnerabilities.pdf

According to that paper malicious extensions can bypass the Mozilla vetting process and can misuse other installed extensions, one of them Noscript. uBlock0 and uMatrix are not mentioned in that paper, but perhaps you want to check if they are affected by using the tool mentioned in that paper.

**Comment by gorhill** [comment]
Reportedly Mozilla reviewers were given the source code of the static analysis tool, and they will use it to review add-ons. If there is an issue with uBO, Mozilla reviewers will provide feedback.
