### ISSUE TITLE
Toolbar icon not available in some popup windows

### ISSUE THREAD

**Issue by schliden** [gorhill/uBlock#1535]
### Describe the issue

The uBlock Original icon does not appear on some sites that 'popup' new windows.

This makes it difficult to troubleshoot any issues without any way to access the uBlock interface.

### One or more specific URLs where the issue occurs

http://www.javascript-coder.com/files/window-popup/javascript-window-open-example1.html

### Steps for anyone to reproduce the issue

1. open http://www.javascript-coder.com/files/window-popup/javascript-window-open-example1.html
2. click the "Open the JavaScript Window Example 1" hyperlink
3. a new window is opened without toolbar buttons

Note: I also use noscript, which always manages to persist its icon even on these controlled popups.

### Your settings
- Browser/version: Firefox 45.0.1
- uBlock Origin version: 1.6.6

**Comment by gorhill** [comment]
It's a browser issue. Use the logger to access the popup panel of specific window.
