### ISSUE TITLE
Unblocking comments

### ISSUE THREAD

**Issue by SumatraPeter** [gorhill/uBlock#1536]
Just switched to uBlock Origin. All default settings etc. and it seems to work quite well. I'm just trying to figure out how to unblock commenting systems such as Disqus and Livefyre on **all** sites. If that can't be achieved then I suppose tedious per-site unblocking will have to do. In that case can you get me started on how to unblock Livefyre comments for example on zdnet.com?

- Browser/version: Firefox 45.0.1 32-bit on Windows 10 Home 32-bit
- uBlock Origin version: 1.6.6

**Comment by anewuser** [comment]
Please close this issue and read this before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

>  **The issue tracker is for provable issues only**
> 
> For **support/discussions**, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).
