### ISSUE TITLE
Share photo facebook

### ISSUE THREAD

**Issue by Reoldyk** [gorhill/uBlock#1537]
cannot Share photo facebook because this rule.

`||pixel.facebook.com^`
found in:
hpHosts’ Ad and tracking servers
MVPS HOSTS

`https:*_ad_`
found in:
JPN: ABP Japanese filters (日本用フィルタ)

![ublock logger 2016-04-05 18-53-55](https://cloud.githubusercontent.com/assets/4547317/14280888/e648e198-fb5f-11e5-8c3b-35fbee460f6b.png)

**Comment by gorhill** [comment]
Report to filter list maintainers.

**Comment by berrythesoftwarecodeprogrammar** [comment]
the pixel.facebook.com one isnt the problem, its that other weird rule. pixel.facebook.com is never needed for anything

**Comment by Reoldyk** [comment]
@berrythesoftwarecodeprogrammar  you're right.
now unsubscribe JPN: ABP Japanese filters (日本用フィルタ)

**Comment by IDKwhattoputhere** [comment]
> Report to filter list maintainers.

Apparently Facebook "is not supported".
https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy#web-sites-not-to-be-supported
https://github.com/k2jp/abp-japanese-filters/issues/5
