### ISSUE TITLE
no-remote-fonts option not working

### ISSUE THREAD

**Issue by icasdri** [gorhill/uBlock#1539]
uBlock Origin's `no-remote-fonts: * true` option (i.e. by checking "Block remote fonts" in Settings or adding that line to rules) does _not_ have the desired effect of blocking `@font-face` remote webfonts from being downloaded/used. 

`@font-face` fonts are still downloaded/used even when the option is enabled. This can be seen in Firefox's Font Inspector. Below is an example with http://arstechnica.com.

<img src="http://i.imgur.com/QJj3Ugn.png" height="400">

Notice that uBlock Origin's font blocking option is enabled per the red X in bottom-right of popup, yet the `@font-face` remote webfonts are still being used per Inspector (example of "Bebas Nueue" present in screenshot; this is also easily seen in the difference in page rendering).

Note that setting Firefox's built-in `gfx.downloadable_fonts.enabled` to `false` _does_ have the desired effect (see Steps to Reproduce below), but this ruins uBlock Origin's popup UI as discussed in #15 when this feature was first introduced.

**Steps to reproduce:**
1. Visit a site with webfonts, e.g. http://arstechnica.com, open `Inspector`, click on `Fonts` tab, observe that a number of `@font-face` remote webfonts are being used.
2. Enable "Block remote fonts" in uBlock Origin's settings (or add the appropriate rule)
3. Visit the site again (force disable cache and refresh), and observe in Font Inspector that the `@font-face` webfonts are still being used.
4. Set `gfx.downloadable_fonts.enabled` to `false` in `about:config` (from #15, this is what no-remote-fonts is supposed to accomplish without uBlock's interface breaking)
5. Visit the site again, and observe in Font Inspector that all fonts are now "system" fonts, and no `@font-face` are used.
6. Set `gfx.downloadable_fonts.enabled` back to `true`, while keeping uBlock Origin's "Block remote fonts" option, and observe on the site in Font Inspector that the `@font-face` webfonts come back, signifying that uBlock's option has no effect.

**Version information:**
- Firefox 45.0.1 (new profile, no other extensions, running on latest Arch Linux)
- uBlock Origin 1.6.8 (fresh from AMO, no other settings changed)

**Comment by gorhill** [comment]
These are inline `data:` URI-based fonts, they can't be blocked as there is no specific network requests for these.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@gorhill do you think anything should be done about data: URIs? seems like an easy way for websites to bypass blockers and load unwanted/malicious content. see: https://github.com/gorhill/uMatrix/issues/276#issuecomment-206082708 
it would require extra work but treating data: URIs as additional requests or special requests which can be blocked based on content type might be a good idea. if not in ublock/umatrix maybe someone else can do it. maybe browser vendors will address it if they start seeing them being abused

**Comment by icasdri** [comment]
@gorhill Thanks for the explanation. This is interesting and does indeed seem like an easy bypass for websites. Curiously, [NoScript's option](https://hackademix.net/2010/03/24/why-noscript-blocks-web-fonts/) seems to successfully block these (as part of their various types of "Blocked Objects"), so I wonder how they do it in addition to `gfx.downloadable_fonts.enabled`'s behavior.

**Comment by gorhill** [comment]
> I wonder how they do

Probably blocking through `nsIContentPolicy`. I could do the same for uBO -- I did that in the past for video resources, something which eventually reverted -- but there are performance issues doing so, especially concerning multiprocess Firefox. And anyways, this would work only for Firefox, not Chromium-based browsers, and not for Firefox WebExtensions.

My understanding of how things are evolving, is that Giorgio Maone is working closely with Mozilla re. WebExtensions, and I am assuming that the missing parts of WebExtensions as implemented on Chromium-based browsers to solve the kind of issues here will be added to Firefox's version of WebExtensions (and hopefully this will motivate Chromium devs to follow suit).

**Comment by RoxKilly** [comment]
@icasdri , if you do not wish to download remote fonts, but you still want uBO UI to work, instruct Firefox to prevent websites from using their own fonts.  To do this, go to `Options > Content > Advanced button > uncheck "Allow pages to choose their own fonts"`.   In `about:config`, you can accomplish the same thing by setting `browser.display.use_document_fonts=0`.  Doing so and refreshing ArsTechnica page, you will see that only local fonts are used regardless of whether you block fonts in uBO.

By making that settings change in Options menu (instead of about:config), you can choose which font you want all pages to use.  Here is my own setting; it has worked well on just about all pages so far:
![6](https://cloud.githubusercontent.com/assets/12346501/14353579/a79d8ac2-fca7-11e5-92c8-9575b6a967a4.png)

**Comment by lewisje** [comment]
That's a bit too heavy-handed, because it keeps *all* page-specified fonts, even fonts loaded from the local machine rather than the Web (a.k.a. "non-web" fonts), from working unless they're in that small set of allowed fonts; for example, it would keep Verdana from being used on a page if Arial is set as the default sans-serif.

**Comment by RoxKilly** [comment]
I don't understand the exact workings of this setting to be honest.  What @lewisje just posted makes sense, and the setting seemed to successfully block Arstechnica site from loading remote fonts. Then again, if I go to http://getbootstrap.com/css/, even though I have  `browser.display.use_document_fonts=0` and uBO set to block remote-fonts, only some fonts get blocked.  The Fonts tab of the Inspector tool (Firefox) shows that fonts can *still* be loaded remotely.

![8](https://cloud.githubusercontent.com/assets/12346501/14373474/808d7c46-fd18-11e5-8c7f-228f5b8f7282.png)

Firefox 45.0.1
uBO 1.6.8

**Comment by berrythesoftwarecodeprogrammar** [comment]
can you link to the exact page with the fonts? i dont see them on your link

**Comment by RoxKilly** [comment]
@berrythesoftwarecodeprogrammar  Not sure whether you're referring to me. If so, the page is http://getbootstrap.com/css/ .  In Firefox, press `Ctrl+Shift+C` to open the Inspector, then choose the `Fonts` tab within the tool.  If in `about:config` you have `browser.display.use_document_fonts=0` and you have set uBO to block remote fonts, you should still see a remote font loaded, called *anchorjs-icons* as in my last post

**Comment by gorhill** [comment]
http://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/

**Comment by RoxKilly** [comment]
Great find. Coupled with the quote below from gorhill, the ghacks link explains it all for me.
>  inline data: URI-based fonts, they can't be blocked as there is no specific network requests for these
*-gorhill*

**Comment by berrythesoftwarecodeprogrammar** [comment]
@RoxKilly oh i didnt know that your screenshot was of the font inspector

i wonder how it determines which fonts are icon fonts

**Comment by Wannabe-Programmer** [comment]
[RAS](https://github.com/dillbyrne/random-agent-spoofer) solves this problem through limiting the detectable fonts.

![45352](https://cloud.githubusercontent.com/assets/16097892/15505484/162dae84-2207-11e6-8fef-dd449fb0fdec.jpg)
The add-on basically removes the ability for scripts to detect the web-browser and to spoof the user agent using a fake profile. Limiting the detectable fonts was a way to minimize the ability for the browser to be identified. Though this may not be the goal of uBlock Origin, limiting detectable fonts may be beneficial for the above reason.

Tested on the same website - these results were returned.
![34512354](https://cloud.githubusercontent.com/assets/16097892/15505474/0d6ce4fe-2207-11e6-949a-2927f60aec70.jpg)

**Comment by yurikhan** [comment]
Is there an issue for blocking data: URI fonts? I’d like to +1 it.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues/1539#issuecomment-206230700

**Comment by gorhill** [comment]
With current version of uBO, this should work to prevent inlined fonts from being used by the browser:

    *$csp=font-src *

**Comment by yurikhan** [comment]
Good. This should probably be mentioned in a wiki page easily accessible from the wiki home.

Also, did you mean `*$csp=font-src 'none'`, or am I misunderstanding how it works?

**Comment by gorhill** [comment]
> Also, did you mean `*$csp=font-src 'none'`, or am I misunderstanding how it works?

Using `*` means that non-inline fonts won't be blocked by the CSP, hence they can still be blocked/allowed using the no-remote-fonts switch.

**Comment by birdie-github** [comment]
@gorhill 

For those of us who are extremely stupid or unsavvy, how can this rule be applied on a per website basis?

**Comment by okiehsch** [comment]
`||example.com^$csp=font-src *`
or 
`*$csp=font-src 'none'` and then disable it on any website you want
`@@*$csp=font-src 'none',domain=example.com`

**Comment by RoxKilly** [comment]
@okiehsch , @gorhill I may be missing something but it doesn't seem to work.  Try:

1. add rule: `*$csp=font-src *` to the My Filters pane
2. add rule `no-remote-fonts: * true` to the My Rules pane
3. Open dev tools (`F12`) to observe the fonts loaded
4. go to [http://getbootstrap.com/css/](http://getbootstrap.com/css/)

you'll notice that the Anchor-JS fonts are still being loaded (they show up as "remote" in Firefox Fonts Inspector)

**Comment by gorhill** [comment]
I don't see "Anchor-JS fonts" on that page, the only font resource I see is `http://getbootstrap.com/dist/fonts/glyphicons-halflings-regular.woff2`, and it is properly blocked by the no-remote-fonts switch. Unsing Firefox Nightly.

**Comment by Alpengreis** [comment]
Would it be not easier - for the user - to block inline fonts with the uBlock switch too??
