### ISSUE TITLE
No Video playback @ Chip.de

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#1540]
Issue with Firefox 46. beta 8, uBo 1.6.8 and flashplayer dissabled

Video playback not working @ chip.de 

look:

http://www.chip.de/video/ 

no Video playback!

**Comment by gorhill** [comment]
Caused by the blocking of `tfag.de` in Peter Lowe's and EasyList.

Solution: `@@||tfag.de^$script,domain=chip.de`.

**Comment by gorhill** [comment]
Since you are using 1.6.8, please report filter list issues in <https://github.com/uBlockOrigin/uAssets> next time.

**Comment by akks1981** [comment]
thx it works! ok next time i do it.
