### ISSUE TITLE
Addon not signed

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1541]
On Firefox 45, uBlock got disabled because the signature could not be verified. All was fine for 1.6.6 but appears to have happened when upgraded to 1.6.8.

**Comment by gorhill** [comment]
You installed 1.6.8 from where?

**Comment by grenzor** [comment]
I had 1.6.6 installed from addons.mozilla.org which then updated to 1.6.8 and was disabled for not being signed.

**Comment by gorhill** [comment]
You should report to <https://github.com/mozilla/addons-server/>, as soon as I upload a new version to AMO, the signing process is out of my control.

There is this one specific issue, don't know if this is related: <https://github.com/mozilla/addons-server/issues/1111>.
