### ISSUE TITLE
"uBlock has all the features uBlock Origin has!" myths missing

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1542]
Missing: (uBlock has all the features uBO has!)https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#ublock-has-all-the-features-ublock-origin-has (then also rename [this](https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#abp-has-all-the-features-ublock-has) to [this](https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#abp-has-all-the-features-ubo-has))

* `"The filter type popup also blocks popunders."` - This is not found in uBlock.
* the unique inline script tag filtering feature - This is not found in uBlock.
* the unique strict blocking feature - This is not found in uBlock.
* Thunderbird support - This is not found in uBlock.

**Comment by gorhill** [comment]
I rather not spend any time on this.
