### ISSUE TITLE
Disabling for sites does not work in 64-bit Firefox on Windows

### ISSUE THREAD

**Issue by gkkovacs** [gorhill/uBlock#1543]
I am running Firefox 45 64-bit on Windows 7 with uBlock Origin 1.6.8 (default settings).

Disabling uBlock Origin for specific sites does not work: the "power" button and the icon both correctly turn gray, yet the sites display no ads upon reloading, and the anti-adblock overlays come up the same as before.

I have first noticed this on wired.com articles, but disabling on other sites show the same effect: uO just keeps working.

![firefox45-x64-ublockorigin-disable-fail-wired](https://cloud.githubusercontent.com/assets/12697870/14348011/2e0525b8-fcba-11e5-8187-ccd6422b1ee6.png)

**Comment by IDKwhattoputhere** [comment]
It looks like you have tracking protection enabled in Firefox. Switch it off and try again.

**Comment by gkkovacs** [comment]
@IDKwhattoputhere I did have tracking protection on. Switching it off does not help unfortunately, uO still blocks everything despite being turned off. (Reloaded and even restarted Firefox.)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
@gkkovacs So it looks like this in about:config?
`privacy.trackingprotection.enabled   false`
`privacy.trackingprotection.pbmode.enabled   false`
Because that works fine for me on Windows 7 with Firefox. Maybe you have some other add-on installed that blocks ads/trackers or you have modified your hosts file or similar? Other than that I don't know.

**Comment by gkkovacs** [comment]
@IDKwhattoputhere I don't know how you came to the conclusion that tracking protection has _anything_ to do with the issue I'm experiencing. Also please note that I'm running the 64-bit version of Firefox, which is **not** the default, you have to specifically download an install it.

**Comment by gorhill** [comment]
Wired has no value in making the case that uBO is not whitelisting properly -- it is known to still block users who disable their blocker, the site is flawed. So what is left from your bug report is "other sites", which is completely useless when it comes to **make a case**.

**Comment by IDKwhattoputhere** [comment]
@gkkovacs Because Tracking Protection very often blocks ads because of they track users' behavior and interests. 64-bit doesn't make a difference. 32 and 64-bit work flawlessly here with Windows 7 and uBO 1.6.8.
