### ISSUE TITLE
"|https://$third-party,image" uBlock incorrect reading

### ISSUE THREAD

**Issue by reportingnow** [gorhill/uBlock#1546]
uBlock enforce "|https://$third-party,image" blocking rule even the blocklist
have nothing such line.

### One or more specific URLs where the issue occurs
https://www.amazon.co.jp/
(not http://)

### Screenshot in which the issue can be seen
https://i.imgur.com/3GoQl3J.jpg

### Steps for anyone to reproduce the issue
1. Subscribe NoMercy blocklists and nothing else.
2. Open chrome://ublock0/content/logger-ui.html
3. Visit the URL above.
3. Blocked with reason(screenshot).

### Your settings
- Browser/version: Palemoon 26.2(latest)
- uBlock Origin version: 1.6.9b0 (from this github)

##### Your filter lists
Only these; other lists are not checked.
http://repo.a2af37vnxe44tcgo.onion/data/abl/nm_fanboy-ultimate.txt
http://repo.a2af37vnxe44tcgo.onion/data/abl/nm_easylist_asia.txt

##### Your custom filters (if any)
none.

This is NOT blocklist's fault; Adblock works fine.

**Comment by reportingnow** [comment]
Current data, for @gorhill. See, there's no "|https://$third-party,image".
What do you think? Why uBlock Origin think "|https://$third-party,image" is exist?

**Comment by lewisje** [comment]
It [has been dealt with](https://github.com/gorhill/uBlock/issues/1548), and the NoMercy lists are still idiotic.
