### ISSUE TITLE
uBlock Origin: Stop Phone Phone, please.

### ISSUE THREAD

**Issue by reportingnow** [gorhill/uBlock#1547]
When I install uBlock Origin, and select nothing in "3rd party filters",
uBlockO still make a connection to github server.
This is called "phone home" activity, aka spyware activity.

More details below.

### Steps for anyone to reproduce the issue

1. Install uBO.
2. Uncheck every 3rd party lists.
3. Check only:
Auto-update filter lists. 
Parse and enforce cosmetic filters.
4. Add 2 Custom URLs to "Custom list" box, and parse them.
5. Update.
6. uBO make a connection to custom URLs(expected), but still, sometimes, make a connection to github(NOT expected).

### Your settings
- Browser/version: Firefox Latest / Also tested on Palemoon latest
- uBlock Origin version: Latest version from this github

##### Your custom filters (if any)
None.

Again, I DO NOT wish uBO to make a connection to NOTHING else, EXCEPT I specified.

"Uncheck Auto-update filter lists then."
No, if I do it, my custom URLs are not updated automatically, right?

"It's just a github..."
Phone. Home. Must. Stop. Period.

https://en.wikipedia.org/wiki/Phoning_home

Malicious phoning home

There are many malware applications that "phone home" to gather and store information about a person's machine. For example, the Pushdo Trojan[8] shows the new complexity of modern malware applications and the phoning home capabilities of these systems. Pushdo has 421 executables available to be sent to an infected Windows client.

Surveillance cameras have been reported by security researcher Brian Krebs to secretly phone home to the manufacturer.[9]

**Comment by lewisje** [comment]
Opening a new copy of [a wrongheaded issue](https://github.com/gorhill/uBlock/issues/1549) won't make it relevant.

**Comment by Eeems** [comment]
Can't tell if troll or not...

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
