### ISSUE TITLE
uBlock Origin: Stop Phone Phone, please.

### ISSUE THREAD

**Issue by whydoyoublockmefk** [gorhill/uBlock#1549]
reportingnow commented Apr 8, 2016

When I install uBlock Origin, and select nothing in "3rd party filters",
uBlockO still make a connection to github server.
This is called "phone home" activity, aka spyware activity.

More details below.
Steps for anyone to reproduce the issue

    Install uBO.
    Uncheck every 3rd party lists.
    Check only: Auto-update filter lists.  Parse and enforce cosmetic filters.
    Add 2 Custom URLs to "Custom list" box, and parse them.
    Update.
    uBO make a connection to custom URLs(expected), but still, sometimes, make a connection to github(NOT expected).

Your settings

    Browser/version: Firefox Latest / Also tested on Palemoon latest
    uBlock Origin version: Latest version from this github

Your filter lists
Your custom filters (if any)

None.

Again, I DO NOT wish uBO to make a connection to NOTHING else, EXCEPT I specified.

"Uncheck Auto-update filter lists then."
No, if I do it, my custom URLs are not updated automatically, right?

"It's just a github..."
Phone. Home. Must. Stop. Period.

https://en.wikipedia.org/wiki/Phoning_home

Malicious phoning home

There are many malware applications that "phone home" to gather and store information about a person's machine. For example, the Pushdo Trojan[8] shows the new complexity of modern malware applications and the phoning home capabilities of these systems. Pushdo has 421 executables available to be sent to an infected Windows client.

Surveillance cameras have been reported by security researcher Brian Krebs to secretly phone home to the manufacturer.[9]

**Comment by lewisje** [comment]
The code is open-source under the GPLv3, a strong copyleft license; additionally, you can inspect the extension package yourself, and the code it is currently running, in every browser that runs this extension.

This extension does not make requests to GitHub to track users or exfiltrate their private data, or for any other malicious purpose; it makes requests solely to update certain built-in filter-lists that are regularly updated [to ensure that uBlock Origin doesn't break the Web](http://i.imgur.com/5OwGK.jpg). Also, it downloads them over HTTPS to guard against MITM attacks, and shows a warning for third-party lists that aren't served over HTTPS.

I will admit that as a power user, it would sound nice to be able to *use* certain filter-lists without keeping them regularly updated, but it's a low priority and it would definitely clutter the UI and make it confusing.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
@whydoyoublockmefk  blocked for wasting my time.

**Comment by RoxKilly** [comment]
To anyone else who has the same concerns as @whydoyoublockmefk, [the Privacy Policy page](https://github.com/gorhill/uBlock/wiki/Privacy-policy) explains uBO's net requests.

**Comment by gorhill** [comment]
> I will admit that as a power user, it would sound nice to be able to use certain filter-lists without keeping them regularly updated

As a power user, you could turn on _advanced user_ mode, un-whitelist `behind-the-scene` scope, then create whatever filter to block uBO's own network requests.
