### ISSUE TITLE
login issue on this website

### ISSUE THREAD

**Issue by S3ndG** [gorhill/uBlock#1550]
Hi, when I go on this website: http://www.vulgaris-medical.com/forum-sante
 I got an issue if If click on "Rejoignez Vulgaris !
Je m'inscris  **Je m'identifie**"  at the top left on the page. It stops loading. I cannot login on this website with ublock enabled.
Here is a screenshot so you can click on the right link : http://ratm6.free.fr/vulgaris_ublock_issue.JPG

My settings:
firefox 45.0.1 x64 for windows
uBlock Origin version: 1.6.8

I use the default user lists.

Could you tell me what can I do in order to login on this website with ublock enabled?
thanks! :)

**Comment by gorhill** [comment]
Here is only for source code issues. Filter issues must be opened at <https://github.com/uBlockOrigin/uAssets/issues>.
