### ISSUE TITLE
Some "annotations" in Youtube

### ISSUE THREAD

**Issue by Irbidan** [gorhill/uBlock#1551]
Hello,

When you are in Youtube some videos add some kind of ads (not the famous ads). Is it possible to hide or remove with uBlock Origin?

I attach screenshots:
![sin titulo](https://cloud.githubusercontent.com/assets/541941/14390000/493537e6-fdb5-11e5-9945-e80fced3a620.png)
![captura](https://cloud.githubusercontent.com/assets/541941/14390134/d7b4b532-fdb5-11e5-84d4-e7e058ac26f3.PNG)

**Comment by jo2dan23** [comment]
||youtube.com/annotations

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
