### ISSUE TITLE
How does '^' in static filter work?

### ISSUE THREAD

**Issue by Darayavaush** [gorhill/uBlock#1552]
ABP filter documentation states that ^ marks a separator, but as far as I can tell it behaves exactly like * wildcard here.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
I believe he dealt with this issue already: https://github.com/gorhill/uBlock/issues/1056#issuecomment-164263353

**Comment by Darayavaush** [comment]
Well, that issue doesn't mention how it works other than that it is 'slightly different'.

**Comment by gorhill** [comment]
Issue tracker is only for reporting actual issues, please respect this.
