### ISSUE TITLE
EasyList Not appearing to work "0 used out of 62,821"

### ISSUE THREAD

**Issue by CrowdMeme** [gorhill/uBlock#1553]
It appears that the EasyList filters don't appear to be working. They are selected, and they have been updated and Changes applied yet they say 0 used out of x.

I try purging the cache and then it says "y amount used of z" with only a slight number of filters or items not being used/blocked. I don't know why this is happening. The issue is replicated on different machines being used at different places, and even on machines that don't belong to me that I have tested it on. Chrome version: 49.0.2623.110 m (There is an update ready to install I will install that and come back and report if the issue persists.

(No specific sites where issues persists or appears, it's shown in uB dashboard.

See image:
[IMGUR](http://i.imgur.com/iWqC3sF.png)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: Select ALL filters excluding language packs, EXCEPT the obselete Spam404 filter list, leave that unchecked.
2. Apply Changes
3. Update all filter lists, enable out update of filter lists
4. Enable Parse and enforcing cosmetic filters (Could this be part of the issue?)

### Settings:

√ Hide placeholders of blocked elements (If you can't see the check: (Enabled)
√ Show the number of blocked requests on the icon (Enabled)
√ Make use of context menu where appropriate (Enabled)
 X Disable tooltips (Not Enabled)
 X Color-blind friendly (Not Enabled)
 X Enable cloud storage support (Not Enabled)
 √  I am an advanced user (Required reading) (Enabled)
**Privacy**
√ Disable pre-fetching (to prevent any connection for blocked network requests) (Enabled)
√ Disable hyperlink auditing/beacon (Enabled)
√ Prevent WebRTC from leaking local IP addresses (Enabled)
**Default behavior
These default behaviors can be overridden on a per-site basis **
 X Disable cosmetic filtering (Not Enabled)
 X Block media elements larger than 50kB (Not Enabled)
 X Block remote fonts (Not Enabled)

- Browser/version: 
- uBlock Origin version: v1.6.8
- OS: Windows 7

##### Your filter lists

Default filters lists - Obsolete Spam404 list - My Filters (As there are none)
```
**::
::**
134,243 network filters ＋ 58,206 cosmetic filters from:

 **X **My filters‎ : 0 used out of 0
 **√** uBlock filters‎ : 421 used out of 424
 **√** uBlock filters – Badware risks‎  (github.com): 4 used out of 4
** √** uBlock filters – Experimental‎ (github.com): 8 used out of 9
 **√ **uBlock filters – Privacy‎ : 22 used out of 25
 **√** uBlock filters – Unbreak‎ : 86 used out of 86
Ads (5)
 **√** Adblock Warning Removal List‎ (forums.lanik.us): 110 used out of 115
**√ ** Anti-Adblock Killer | Reek‎  (github.com): 1,689 used out of 1,739
 **√** EasyList‎ (forums.lanik.us): 0 used out of 62,821 **ISSUE**
**√**  EasyList without element hiding rules‎ (forums.lanik.us): 0 used out of 24,698 **ISSUE**
**√**  Peter Lowe’s Ad server list‎ (pgl.yoyo.org): 1,567 used out of 2,417
Privacy (3)
**√ ** Basic tracking list by Disconnect‎ : 28 used out of 34
**√**  EasyPrivacy‎ (forums.lanik.us): 5 used out of 11,361 **ISSUE**
**√** Fanboy’s Enhanced Tracking List‎ (forums.lanik.us): 0 used out of 951
Malware domains (6)
 **√** Malvertising filter list by Disconnect‎ : 287 used out of 5,590
 **√** Malware Domain List‎ (malwaredomainlist.com): 1,671 used out of 1,671
**√**  Malware domains‎ (www.malwaredomains.com): 18,551 used out of 18,706
**√**  Malware domains (long-lived)‎ (www.malwaredomains.com): 1 used out of 1,194
**√ ** Malware filter list by Disconnect‎ : 93 used out of 2,854
**√**  Spam404‎ (www.spam404.com): 5,400 used out of 5,408
 **X** Spam404 (obsolete, will be removed)‎ (www.spam404.com): 0 used out of ?
Social (3)
 **√** Anti-ThirdpartySocial (see warning inside list)‎ (forums.lanik.us): 43 used out of 63
 **√** Fanboy’s Annoyance List‎ (forums.lanik.us): 1 used out of 22,479
**√** Fanboy’s Social Blocking List‎ (forums.lanik.us): 0 used out of 13,588
Multipurpose (4)
 **√** Dan Pollock’s hosts file‎ (someonewhocares.org): 9,688 used out of 11,730
 **√** Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us): 97,549 used out of 97,606 **<-- Is this an issue?**
 **√** hpHosts’ Ad and tracking servers‎ (hosts-file.net): 40,733 used out of 47,714
 **√** MVPS HOSTS‎ (winhelp2002.mvps.org): 13,077 used out of 13,464
**::
::**
```
##### Custom filters?: None.

**Comment by lewisje** [comment]
I'm thinking that it parses and loads in Fanboy Ultimate first (maybe it goes bottom-to-top, or at random?), and then the other included lists are redundant, so their filters aren't included; I see that Fanboy's Annoyances does have one filter included, so that one could have been updated just after the Ultimate compilation.

BTW, although uBlock Origin does dedupe for you, it's still a good idea, when using a multi-pack list like Fanboy Ultimate, to not also use the component lists, like EasyList, EasyPrivacy, Fanboy's Enhanced Tracking, and Fanboy's Annoyances (which itself includes and makes redundant the Social Blocking List); similarly, if you use the full Malware Domains list, the Malware Domains long-lived list is redundant.

That way, uBlock Origin won't need to make so many network requests to update its filter lists.

**Comment by gorhill** [comment]
> maybe it goes bottom-to-top, or at random?

No defined order.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters>:

> uBlock Origin discards duplicate filters [...]
