### ISSUE TITLE
Interstetial double click ad appearing

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uBlock#1556]
### Describe the issue
Interstetial ad of doubleclick appearing though its blocked in ublock

### One or more specific URLs where the issue occurs
http://www.firstpost.com

### Screenshot in which the issue can be seen
![1](https://cloud.githubusercontent.com/assets/3329844/14417028/f3637970-ffcd-11e5-9d0c-02f87c6d59c0.png)
![2](https://cloud.githubusercontent.com/assets/3329844/14417036/1125b946-ffce-11e5-92fa-b52fbe41c43f.png)
![3](https://cloud.githubusercontent.com/assets/3329844/14417039/187b35c2-ffce-11e5-827b-d0a1d3000673.png)

### Steps for anyone to reproduce the issue
The first time we visit the site firstpost.com, it shows an interstetial ad. I doesnt happen in the same session again, but if you close the browser and reopen it, the ad comes. I blocked doubleclick universally using ublock origin.

### Your settings
- Browser/version: Firefox 45.0.1
- uBlock Origin version: uBlock Origin 1.6.8

##### Your filter lists
![4](https://cloud.githubusercontent.com/assets/3329844/14417066/9335a3ce-ffce-11e5-80d7-4ba96b34f8c8.png)

##### Your custom filters (if any)
....
....
     * doubleclick.net * block
....
....

**Comment by harshanvn** [comment]
looks like an issue with the filters. Best place for these filter list issues are [here](https://github.com/uBlockOrigin/uAssets)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
I won't make any exception, filter issues have to go to uBlockOrigin/uAssets.
