### ISSUE TITLE
uBlock is blocking my page slider

### ISSUE THREAD

**Issue by orgztion** [gorhill/uBlock#1557]
Hello!
uBlock block my homepage slider.
Is any recommendation/guideline for avoid this?

Thanks

**Comment by iparr** [comment]
Adblockers in general often block elements based on the classname they use.

What is your markup like?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
