### ISSUE TITLE
uBlock inserts its own stylesheet in <head>

### ISSUE THREAD

**Issue by Sperko** [gorhill/uBlock#1558]
I was reviewing the source code of my site and I saw an unknown block of code appearing in the head tag, which isn't in the original source.

The code that shows:

```
<style type="text/css">:root #content > #right > .dose > .dosesingle,
:root #content > #center > .dose > .dosesingle
{display:none !important;}</style>
```

This affects most websites while uBlock Origin is enabled.

I have only just noticed this so it may be due to a recent update?

**Comment by publicarray** [comment]
Could you please provide the url? Styles are injected according to element hiding rules see: https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters and https://github.com/gorhill/uBlock/wiki/Cosmetic-filtering-in-%C2%B5Block:-version-0.4.0.0-update

> To be able to inject only the cosmetic filters which are relevant to a web page (rather than all of them), µBlock waits for the primary DOM to be available, then survey and collect information on the page to find out which cosmetic filters need to be injected in the page.

**Comment by gorhill** [comment]
That's how cosmetic filtering is implemented since uBlock was first released in June 2014.

**Comment by lewisje** [comment]
It's similar to how Adblock Plus implements hiding rules, except that ABP injects all generic hiding rules and all domain-specific rules for which the current page domain matches (This might be how AdBlock does it too).

**Comment by Sperko** [comment]
Strange how I've only just noticed this while developing my code, is this strictly necessary?

**Comment by lewisje** [comment]
I'm guessing it's more performant to do that than to perform a bunch of `querySelectorAll` calls and then modify the relevant elements' `style` attributes.

**Comment by Sperko** [comment]
I think I understand now, it wasn't causing me any problems it was just causing my concern.

Thank you
