### ISSUE TITLE
uBlock Origin blocks direct linked pictues on special domains

### ISSUE THREAD

**Issue by towlie** [gorhill/uBlock#156]
Happens on Chrome and Firefox.
Example:
- Browse the /adv/ part of 4chan: https://boards.4chan.org/adv/catalog
- Open some thread and then move a picture from it to a new tab (like you would open https://i.4cdn.org/adv/1430393275360.jpg)

-> Firefox and Chrome will load the page but they will override it with a black / white page

![ublock0](https://cloud.githubusercontent.com/assets/6986141/7413229/31d0f5c4-ef4a-11e4-9d6b-8ccd95c56bfc.jpg)
![ubloc02](https://cloud.githubusercontent.com/assets/6986141/7413246/437bae4a-ef4a-11e4-848d-2285eb8e10d1.jpg)

I think this only happens on the /adv/ forum.

**Comment by towlie** [comment]
Oh and it's not a new issue. I saw this in 0.9.3.0 already.

**Comment by gorhill** [comment]
It's a filter issue. You need to create an exception filter for `4cdn.org`:

    @@||4cdn.org/adv/$domain=4cdn.org

To counter `.org/adv/` in EasyList.

There is already `@@||4cdn.org/adv/$image,domain=4chan.org` in EasyList, it should be extended to:

    @@||4cdn.org/adv/$image,domain=4cdn.org|4chan.org

You may want to report false positive to maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

I noticed ABP does not block the image, while it should as per EasyList.
