### ISSUE TITLE
uBlock blocking ScholarlyIQ and Squid tracking by default

### ISSUE THREAD

**Issue by ShawnXu** [gorhill/uBlock#1560]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

UBlock blocking Squid and ScholarlyIQ tracking script by default. Both Squid and ScholarlyIQ are commonly used trackers. ScholarlyIQ is commonly used in academic sites, its tracking results are oftenly used for standard reports such as COUNTER 4. Blocking it results in inaccurate stats which has various business consequences.

Scripts blocked:

http://aws.tracker.squidanalytics.com/js/tracker.js (squid tracker) please ignore this case, author replied that it's blocked by EasyPrivacy.

http://asptag.scholarlyiq.com/ntpagetag.js (siq tracker)

### One or more specific URLs where the issue occurs

http://search.alexanderstreet.com/view/work/388953

### Screenshot in which the issue can be seen

http://screencast.com/t/3nbX5u6q96HU

### Steps for anyone to reproduce the issue

1. in chrome, open http://search.alexanderstreet.com/view/work/388953
2. open developer toolbar and wait for page load
3. see script blocked by client ERROR in red, see screenshot provided above

### Your settings

- Browser/version:  Chrome, Windows 7 / Version 49.0.2623.112 m
- uBlock Origin version: 1.6.8

##### Your filter lists

Default only.

##### Your custom filters (if any)

None.

**Comment by gorhill** [comment]
Filter list issues must not be opened here, but at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues), as stated in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Still, the issue reported is not one of page breakage from a user's point of view: you simply disagree that `http://asptag.scholarlyiq.com/ntpagetag.js` should be blocked. In any case, if you want to dispute that `http://asptag.scholarlyiq.com/ntpagetag.js` should be blocked, you will have to make your case with the [maintainers of EasyPrivacy](https://forums.lanik.us/viewforum.php?f=64):

![a](https://cloud.githubusercontent.com/assets/585534/14466514/2acc7402-00a5-11e6-9831-e85ecb289f0e.png)
