### ISSUE TITLE
problems with the cosmetic filter specificity boost

### ISSUE THREAD

**Issue by epicgirl1998** [gorhill/uBlock#1564]
i posted this comment on #1015 but idk if anyone saw it

> some stuff about the fix in 89f0e8f1a9a66b3c344562a1e68124ae1600f648

> issue one:

> blindly prefixing the selectors with `:root ` breaks the inserted css rules for filters with otherwise valid selectors that already make use of `:root` or `html`

> like how `example.org##:root .ads` turns into `:root :root .ads`

> the elements do seem to get hidden later though using the shadow dom thing

> issue two:

> for filters whose selectors have multiple selectors separated by commas (a css feature), the specificity boost only applies to the first selector

> like how `example.org##.ad, .ads` turns into `:root .ad, .ads`

> fixing it by blindly replacing commas with `, :root` would still suffer from issue one & it'd also break escaped commas and attribute selectors whose values contain commas

.

**Comment by gorhill** [comment]
I do not see any real issue.

Do not use cosmetic filters prefixed with `:root`; do not use cosmetic filters which are a comma-separated list of selectors.

**Comment by epicgirl1998** [comment]
but what if you want to hide an element only if `:root` has a specific attribute or class

**Comment by gwarser** [comment]
@epicgirl1998 real life example please.
