### ISSUE TITLE
youtube heartbeat

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1565]
every minute it connects to a tracker while the video is playing. if it is blocked it keeps trying to connect to two blocked filters every second which is overloading ublock. is there a way to do a neutured script since it is just a one line script? not a big deal i just don't like my bandwith wasted by a useless connection

### One or more specific URLs where the issue occurs

https://www.youtube.com/watch?v=iZqnZasmFxY

script: https://www.youtube.com/heartbeat?video_id=iZqnZasmFxY&heartbeat_token=CAEQkeCflMP826fwARgAIAA&c=WEB&cpn=x3-zm4_eopkIJerS

the line of code is: {"status":"ok"}

**Comment by gorhill** [comment]
> which is overloading ublock

Let's not exaggerate please.

> i just don't like my bandwith wasted by a useless connection

It is not, blocked network requests are blocked before hitting the wire.

**Comment by jo2dan23** [comment]
no i was saying if i block it it keeps requesting the blocked tracker every second as oppose to every minute when unblocked. so you're saying when a blocked tracker is is requested every second it isn't slowing down the browser at all? because thats my impression.

**Comment by lewisje** [comment]
No, he's saying that it isn't *using any bandwidth* at all; not all browser slowdowns are caused by connections that are made and become slow.

**Comment by Hrxn** [comment]
Just to understand you correctly, the issue is not network I/O, rather high CPU usage?
