### ISSUE TITLE
Outlook.com Ad space

### ISSUE THREAD

**Issue by pushkargogte** [gorhill/uBlock#1566]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Can please remove the ad space present in new layout of outlook.com

### One or more specific URLs where the issue occurs

https://outlook.live.com/owa/

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
![screenshot 5](https://cloud.githubusercontent.com/assets/16486468/14579100/ed711680-03ba-11e6-8314-73e6bf648d4e.png)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: By logging in to the account.
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

Default settings

- Browser/version: Chrome 50 x64
- uBlock Origin version: 1.6.8

##### Your filter lists
Deafult filters
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
N/A

**Comment by RoxKilly** [comment]
This is not the correct venue for requesting that ads and other nagware be blocked.  This board is meant to report bugs in uBlock Origin.

I think you'll have better luck making blocking requests at the [EasyList forum](https://forums.lanik.us/)

If you wish to report a broken page as a result of an adblock filter, head to the [uBlockOriigin/uAssets](https://github.com/uBlockOrigin/uAssets) board.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
