### ISSUE TITLE
no-large-media directive parameters, documentation?

### ISSUE THREAD

**Issue by rmenessec** [gorhill/uBlock#1567]
### Describe the issue
I can't find any documentation on the syntax of the **no-large-media** directive. Does it accept a parameter for element size? If not, can that be added? For example:
```
no-large-media: example.com true 50KB # SI kilobytes
no-large-media: acme.com true 2MiB # SI mebibytes 
```
Support for adding per-site size rules in the advanced UI would be great, too.

### One or more specific URLs where the issue occurs
_.*_

### Screenshot in which the issue can be seen
_n/a_

### Steps for anyone to reproduce the issue
_n/a; feature / doc request_

### Your settings
_n/a; feature / doc request_

- Browser/version: FIrefox Aurora 47.0a2 (20160416004025)
- uBlock Origin version: 1.6.9b1

##### Your filter lists
_n/a; feature / doc request_

##### Your custom filters (if any)
_n/a; feature / doc request_

**Comment by Hrxn** [comment]
> no-large-media: example.com true 50KB # SI kilobytes
no-large-media: acme.com true 2MiB # SI mebibytes 

Wow, good one..
For one, binary prefixes is not SI, it's called IEC prefix, because it's their standard, so to speak.

Moreover, If I ever see a parser that actually makes this distinction, I'll fall off my chair laughing.

**Comment by rmenessec** [comment]
@Hrxn okay, yes, brain fart. And what I _meant_ and failed to explain properly was that I wasn't sure whether uBlock used SI or IEC units, and I was hoping to find out.

@gorhill Declined because I labeled my comments incorrectly?

**Comment by anewuser** [comment]
@rmenessec https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit
