### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kristian-hermansen** [gorhill/uBlock#1568]
.

**Comment by kristian-hermansen** [comment]
I am a computer scientist and used the scientific method to reduce the bug down to be uBlock Origin as the bug ;)

**Comment by IDKwhattoputhere** [comment]
So what was the actual issue? Don't just delete everything. What if someone else has this problem? They would be glad to find your answer hear.

**Comment by kristian-hermansen** [comment]
It's a problem somewhere in ublock matrix instead. I have not narrowed it down yet. I put this issue in the wrong forum.

**Comment by gorhill** [comment]
Just in case: when submitting issues, it's irrelevant whether someone is a computer scientist or not, what matters is that the submitter makes the case that there is indeed an issue with uBO or uMatrix, with all the substantiating information.
