### ISSUE TITLE
uBlock doesn't block pop-up window

### ISSUE THREAD

**Issue by ramiresto** [gorhill/uBlock#1569]
I am using Firefox latest version with uBlock Origin latest version with the default filters.

uBlock is not blocking pop-up windows from the http://filmisub.com/

For example, please try http://filmisub.com/filmi/11929-fifty-shades-of-black-petdeset-nyuansa-cherno-2016.html

If is there anything which I can do, please let me know.

**Comment by Snapy** [comment]
> If is there anything which I can do, please let me know.

Read the contributing.md file and the issue template before ignoring it.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
No popups here. Make sure you've checked `Anti-Adblock Killer | Reek‎` or `RUS: RU AdList (Дополнительная региональная подписка)‎` (not sure why it's fixed in there since it seems to be a Bulgarian website and not a Russian one).
