### ISSUE TITLE
GNU.org privacy list?

### ISSUE THREAD

**Issue by direwolfie** [gorhill/uBlock#157]
Hi! I am using Firefox 37.0.2 with UblockOrigin 0.9.5.0
Why was the GNU.org privacy list removed?
Thanks in advance!

**Comment by gorhill** [comment]
It's explained in the change log: <https://github.com/gorhill/uBlock/releases>.

Mainly, a high breakage filter list, which would cause this project to be swamped in users filing issues as if the problems were within uBlock. It's a filter list more suitable for advanced users, and so it's best that these advanced users imported it as a custom filter list.

**Comment by Snapy** [comment]
Just a small question : if it was in used is it automatically added as a custom list or do we have to add it again manually ?

**Comment by RandomAcronym** [comment]
It was not possible to have it be added as a custom list automatically. 
You will need to do it yourself or preferably, use default deny mode, Why use a filter-list that has the same downside of default deny (both will brake sites quite often) without it's upside? (only default deny stops ALL 3rd-party requests)

**Comment by anewuser** [comment]
You can use these rules to deny third-party scripts and frames by default, but allow images from everywhere:

    * * 3p-frame block
    * * 3p-script block

**Comment by direwolfie** [comment]
@gorhill Thank you for the info and for best the advert blocking add-on ever! :)
I also wanted to ask, if two or more block lists have common rules (e.g. GNU.org privacy list and EasyList) does this somehow affect the overall uBlock0 performance?
@RandomAcronym Maybe its just me, but the GNU.org privacy list almost never broke stuff for me. And the default deny mode is too much work... :P

**Comment by anewuser** [comment]
@direwolfie it shouldn't affect the performance of the extension. If you use EasyList, EasyPrivacy and Fanboy's Annoyance list, you don't need the buggy GNU.org privacy list at all.

**Comment by direwolfie** [comment]
@anewuser Thanks! Good to know. :)
