### ISSUE TITLE
Opera 12 (Presto) and Midori (WebKit) PORT?

### ISSUE THREAD

**Issue by rastaman2000** [gorhill/uBlock#1570]
_Hello, Mr. Hill,_

not really an issue, but I'd like to ask you: Would it be difficult or possible to port **uBlock Origin** to the [Opera 12](http://www.opera.com/download/guide/?os=windows&list=all) (the last with [Presto](https://en.wikipedia.org/wiki/Presto_%28layout_engine%29) layout engine) and [Midori](http://midori-browser.org/) ([WebKit](https://en.wikipedia.org/wiki/WebKit) layout engine - used also by [Safari](http://www.apple.com/safari/) and significantly co-developed by Apple) web browsers?

_À propos, thank you for your great work._

_Kind regards
rastaman_

**Comment by gorhill** [comment]
Anybody can fork and work to extend support to other browsers -- it does not have to be me. I personally have no free time left for anything else than maintaining support for Chromium- and Firefox-based browsers.

**Comment by rastaman2000** [comment]
_Hello, Mr. Hill,_

thank you for your answer.

Yes, I understand, that's why I was asking the given way. I WOULD do it by myself, [if I only could, I surely would](https://youtu.be/pey29CLID3I)... IF I were a programmer.

Don't you, please, know anybody, who would be willing to do it? Or publish something as a **_call_**?

_Thanks again. For the uBlock particularly._

_Kind regards
rastaman_
