### ISSUE TITLE
The rule work wrong: ||g.$third-party

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#1571]
URL: http://www.kktv5.com/
bad filter: http://pull-g.kktv8.com/*

win7x64 chrome48

**Comment by IDKwhattoputhere** [comment]
Read https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit:
> Verify that the issue is not related to a 3rd-party filter lists.

Please use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates) to find out where the filter comes from. Then in the options of uBlock click the link next to that filter list and report your issue there.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
