### ISSUE TITLE
FR: MS-Edge support

### ISSUE THREAD

**Issue by MaxRink** [gorhill/uBlock#1572]
Support for MS-Edge would be dope.

**Comment by anewuser** [comment]
You've ignored and deleted the template text that appears when you create a new issue.

That text isn't there just for decoration.This is also a duplicate of #1486. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
