### ISSUE TITLE
UBO can cause FF 45 "Exit" to not terminate correctly.

### ISSUE THREAD

**Issue by LL25255252** [gorhill/uBlock#1573]
Steps to reproduce:

Open a new/clean firefox profile
install uBlock Origin 1.6.8
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

Now to reproduce I have 2 options for you (choose one of them):
- 1. open http://webdesigns.ms11.net/chromeditp.html (the old chromedit homepage which by the way sometimes I still use)
- 2. open UBO's dashboard - chrome://ublock0/content/dashboard.html

UBO blocks this site with "uBlock Origin has prevented the following page from loading:"

Click on **Exit Firefox** (quit Firefox the right way by using the **power button** in the hamburger menu. Don't just close the window by clicking the "x" button at the top of the window).

the browser window will be closed but firefox process doesnt terminate unless you "kill it"

To stop it  from happening again I had to :
- close the problematic tab
- and to "clear recent closed tabs"

Firefox 45.0.02
Win 7 x64

**Comment by gorhill** [comment]
Unable to reproduce using FF 45.01/Linux -- thus likely unrelated to uBO.

**Comment by IDKwhattoputhere** [comment]
I followed your instructions carefully but am also unable to reproduce using Firefox 45.0.2 on Windows 7 64-bit.

**Comment by LL25255252** [comment]
I Updated my opening thread post with another example.

Exactly the same issue happens when instead of 
http://webdesigns.ms11.net/chromeditp.html
I opened UBO's dashboard :
chrome://ublock0/content/dashboard.html


Can you try again to reproduce on your PC ?

**Comment by gorhill** [comment]
> Can you try again to reproduce on your PC ?

Still unable to reproduce.

**Comment by IDKwhattoputhere** [comment]
> Still unable to reproduce.

Same.

**Comment by LL25255252** [comment]
I changed the title so it would be more accurate.

**Comment by LL25255252** [comment]
I tried installing  the beta version - https://github.com/gorhill/uBlock/releases/download/1.6.9b2/uBlock0.firefox.xpi
Still the issue remains.

BTW - Although I installed 1.6.9b2 it displays as 1.6.8 on the "MORE" page of UBO on Firefox Addons Manger.

**Comment by gorhill** [comment]
Since nobody else so far can reproduce, you will have to investigate on your side why you have this issue.

**Comment by LL25255252** [comment]
@gorhill can you address this small thing ?
> BTW - Although I installed 1.6.9b2 it displays as 1.6.8 on the "MORE" page of UBO on Firefox Addons Manger.>

**Comment by gorhill** [comment]
> can you address this small thing

The version shows fine here.

**Comment by LL25255252** [comment]
OK , sorry I mistakenly ignored 
![unverfied addon notification](https://cloud.githubusercontent.com/assets/3327540/14684500/e684e4d8-0738-11e6-9ba2-99dd28f3ed02.png)
So I changed the about:config peference xpinstall.signatures.required to TRUE and now it shows 1.6.9 correctly.

So now I "really" tested 1.6.9 RC and the result is that my issue is continuing.

**Comment by LL25255252** [comment]
I've suddenly noticed something. 
If I have one window and use the "x" button to close the window then firefox process terminates properly.

So just to make sure. Have you @gorhill and @IDKwhattoputhere  exactly followed my STR (steps to reproduce) and exited Firefox with the "EXIT" item of the "three lines" menu button and not with the "x" button?

**Comment by IDKwhattoputhere** [comment]
Yes, I tried both ways.

**Comment by gorhill** [comment]
I can reproduce when I quit using the power button in the hamburger menu.

**Comment by gorhill** [comment]
If I wait long enough after quitting using the steps to reproduce the issue, Firefox warns that it has crashed.

**Comment by LL25255252** [comment]
It warns me also.

**Comment by LL25255252** [comment]
BTW 
I should have better emphasized the "EXIT FIREFOX" on my opening post (personally I never click the "x' button when I want to exit Firefox).
To make things easy I use https://addons.mozilla.org/en-US/firefox/addon/exit-button-firefox/

**Comment by gorhill** [comment]
If I comment out [this line of code](https://github.com/gorhill/uBlock/blob/2d26d1dd3d3a7f72c37b662554c7c47ad7fb4cbe/platform/firefox/vapi-background.js#L1367) ...

    vAPI.tabs._remove(tab, getTabBrowser(win));

... which is executed at shutdown time to get rid of uBO's own tabs, the issue goes away.

The line above just end up calling FF's API `tabBrowser.removeTab()`.

Will have to find out why this is a problem to call this method -- and only for when one quit using the hamburger menu (or the equivalent <Ctrl>-Q).

**Comment by LL25255252** [comment]
@gorhill can u confirm the issue happens to u also after opening http://webdesigns.ms11.net/chromeditp.html

**Comment by LL25255252** [comment]
The issue also happens if u install
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/
and goto to the setting page at:
resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/data/options/index.html

Can u please make sure your fixed version fixes this ?
TIA

**Comment by gorhill** [comment]
> Can u please make sure your fixed version fixes this ?

Did you try to reproduce **without** uBO for that case?

**Comment by LL25255252** [comment]
Yes, you are correct, I tested again and  both addons have this issue (that means it can happen when only one of them is installed).
So what is needed to do now ?

**Comment by LL25255252** [comment]
Many thanks for the quick fix (the new beta 4 version). 
Glad you've managed to fix it b/c I have many addons and it wasn't easy to find which of them causes Firefox to hang and the exact cases it happen.

BTW - I've just reported to the dev Gmail Notifier Restartless about this issue and added [a link to your fix](https://github.com/gorhill/uBlock/commit/d34d47032de73f86528e9bbabe6f397aea5caa22). Hope that's ok with you.
https://github.com/inbasic/ignotifier/issues/400

**Comment by 3ckH4rd** [comment]
Hmm.. I dont really get it. What is the fix for this problem? I have non of the 2 addons installed, neither gmail notifier nor the Firefox exit button. Thank you!
