### ISSUE TITLE
Cannot block surpurfluous network requests that are indistinguishable from desired content

### ISSUE THREAD

**Issue by tyaremco** [gorhill/uBlock#1574]
Tumblr.com has a "related posts" feature that shows previews of other posts at the bottom of a post page.  On many blogs, this can cause serious performance degradation as this section is often full of multi-megabyte animated images.  

AFAICT, there is no way to use a static or dynamic filter to block the related images without also blocking the article image.  As you can see, the article image on [this post](https://staff.tumblr.com/post/130631908085/related-posts) is 
`45.media.tumblr.com/a157566ef3e95598171cdc16b11f2221/tumblr_nvm2phCwjS1qz8q0ho2_r1_1280.gif`

and one of the related images is 
`49.media.tumblr.com/e0c1c9e8b75eb79b041fd652cbdae301/tumblr_mtc1lrJbnF1qz8q0ho1_500.gif`

Distinguishing on the subdomain (45, 49, etc) or the suffix (_500, _1280) is not reliable, either.

I can use a cosmetic filter to hide `.related-posts-wrapper` but this does not stop the images from downloading which are the source of the performance issues.  In fact, it appears the requests cannot even be stopped with a Greasemonkey script because image sources start downloading even before `DOMContentLoaded` fires.

### Suggestion
It would be useful to be able to block requests from [embedded content](https://www.w3.org/TR/html5/embedded-content-0.html) (img, video, audio, etc) in situations where undesirable content cannot be distinguished by a network request pattern.  

An extension to cosmetic filters might look something like
`tumblr.com##embedded:selector(.related-posts-wrapper img)`
or 
`tumblr.com##source:query(.related-posts-wrapper img)`

For the specified elements, their `src` addresses would be blocked.

One can also see the the utility of this feature for blocking ad content served in the same manor.

**Comment by anewuser** [comment]
> **Do NOT**:
> 
>     Submit design ideas.
>     Submit feature requests.
>     Submit "revolutionary ideas".

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by tyaremco** [comment]
Thanks, modified.

**Comment by tyaremco** [comment]
I'll give another example where this could be useful for the video element.

When scrolling through a Facebook news feed, timeline, or video gallery, embedded videos in Firefox are preloaded 100-800kb automatically.  There is no way to disable to this.  If you have have a limited data transfer quota with your ISP this can make a massive difference and I've experienced it first hand.

In uBlock, your only option is to block video files wholesale.  This is obviously not ideal.  With the above suggestion, one could disable video requests within the "news feed" or "gallery" elements exclusively.  As a result, videos in a player overlay or on individual post pages would still be playable.

**Comment by gorhill** [comment]
Why not just use "Block media elements which size is larger than [...] kB"? The first gif you link to is 1.2 MB, that is exactly why that feature was implemented.

**Comment by tyaremco** [comment]
I don't want to block the first gif; it's part of the article.  I do want to block the second gif because it's one of many "related images".

**Comment by tyaremco** [comment]
> Why not just use "Block media elements which size is larger than [...] kB"? The first gif you link to is 1.2 MB, that is exactly why that feature was implemented.

Sorry, my explanation was poor; I have modified the OP.  In summary:

> The goal is to block the excessive network requests caused by images in the "related posts" section without blocking the image(s) embedded in the article.

**Comment by gorhill** [comment]
The browser's parsing engine causes network request for the images to be fired. What you want is a hook into the parser engine such that images which are not visible won't cause network requests to be fired. There is no extension API to accomplish what you want: uBO can intercept and cancel network request, but it cannot prevent the browser from firing the network requests in the first place. If you want to dispute that the browser fires network requests for images which are not visible, you will have to bring your issue to the browser devs.

**Comment by tyaremco** [comment]
The "Block media elements" feature shows uBlock can intercept these requests.  Couldn't they be filtered in this way:

1. page load begins
2. media requests begin arriving and uBlock temporarily holds them until the DOM is ready
3. DOM is ready
4. uBlock traverses DOM and collects src attributes for elements specified by the cosmetic filter
5. uBlock compares the media requests with the list of src attributes and blocks the matches
6. the remaining media requests are allowed to load

In this case, elements having the same src as ones specified by the filter are also blocked but it still works for the purposes described above.  The cosmetic filter is acting as a way to collect additional requests to block.

**Comment by Hrxn** [comment]
I agree, I think the extension APIs are of no help here.

This related posts setting is used with some custom Tumblr themes. Well, you can also use this feature with the default theme.

The easiest way would be to ask the the person running the Tumblr log to stop using crappy themes, I guess.

The option to display related posts is described [here](https://www.tumblr.com/docs/en/custom_themes#related-posts), but that is some kind of template system on the server side, I guess you won't see any of this on the client..

But you're right about one thing, all content hosted on Tumblr has the same URL scheme, so it's not possible to distinguish by URL patterns what is the actual element of the post/permalink page and what is displayed as 'Related'.

On the other hand, every single post is accessible via the public Tumblr API, as used by some 3rd-party Tumblr viewer sites, for example.

**Comment by tyaremco** [comment]
The issue is not about Tumblr, per se.  It's about the fact that we don't have the ability to selectively block downloads from embedded content where:
- the filename is variable
- the file shares the same path as desirable files

For example, If a site delivers animated ads in this way, there's no way to deal with the ad in a convenient way.  My only options are:
- hide the element where the performance penalty is the same, or
- "block media requests" per-site where desirable content is also blocked

Gorhill made it clear that we can't stop the _request_ but stopping the _download_ is another matter.  So, I'm curious whether my proposed solution in my previous comment is feasible.
