### ISSUE TITLE
Add private mode filters to make uBO part of GNU IceCat

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1576]
I suggest that SpyBlock (part of GNU IceCat) fork its code from uBlock [Origin] rather than Adblock Plus.

IceCat author (Rubén Rodríguez) responded: "I made the Spyblock hack before uBlock was available (or well known
anyway). It could be replaced, provided that we can implement with
uBlock the same features SpyBlock provides over Adblock: extra lists
that get enabled when entering private mode.

Since Spyblock is providing the desired functionality right now,
replacing it for the sake of performance is not a priority compared with
improving LibreJS, which is what I'll be working on next. But if
somebody wants to contribute that code I'll be happy to add it."

**Comment by CrisBRM** [comment]
Wouldn't that require platform specific changes?

**Comment by lewisje** [comment]
This would be a good time for someone to make a "SpyBlock Origin" fork or something like that, with the desired platform-specific functionality; I'm thinking that whatever was done to allow an Adblock Plus fork to activate a certain filter-list in private mode would be portable across Firefox extensions.

**Comment by gorhill** [comment]
I do not intend to create/maintain yet another extension.

**Comment by davidhedlund** [comment]
@gorhill This is not about create/maintain another extension but to add a private mode detection to uBO. If the author or IceCat would do that, would you adopt it then?

**Comment by gorhill** [comment]
> would you adopt it then?

Most likely not, because I can't make sense of such feature. I fail to see the point of a "non private mode" for uBO, which is what supporting a special "private mode" implies.

**Comment by davidhedlund** [comment]
@gorhill Thank you. I told the icecat bugzilla mailing list about this so the IceCat maintainer can decide if he think its worth to do it himself.
