### ISSUE TITLE
Block ads in http://bukvi.bg/

### ISSUE THREAD

**Issue by Rusenche** [gorhill/uBlock#1577]
How can we block ads with my version: uBlock Origin v.1.6.8?

Other ads blocked perfectly but I cannot block those ads even with element picker. Element picker cannot catch it.

Please check the following example website.

http://bukvi.bg/

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
