### ISSUE TITLE
Qualays SSL Client Websocket Mixed Content Test Failing

### ISSUE THREAD

**Issue by TheRyuu** [gorhill/uBlock#1579]
With the addition of the new Websocket filtering for Chrome/Chromium based browsers the websocket mixed content test in the Qualay's SSL Client test[1][2] is now failing (reported as "Test failed").  The expected behavior would be a "No" since all mixed content save for Images in this test case are not allowed in Chrome (or Firefox or Edge/IE).  The logger shows nothing being blocked.  I do not use dynamic filtering because I use uMatrix for that (and speaking of uMatrix can the websocket filtering be ported to it, it seems like it would be useful there if you use both as I do since I'm not/can't use dynamic filtering in uBlock).

I don't know if this behavior should be expected considering the websocket blocking is somewhat of a workaround or if it's a legitimate bug.  I also use HTTPS Everywhere and uMatrix although that doesn't seem to matter in this case.  This behavior is new and did not occur before the websocket filtering was added.

Disabling uBlock causes it to revert to the correct behavior of displaying "No".  Disabling in this case means completely unloading uBlock by unchecking the Enabled box under extensions.  Simply disabling it for that site by clicking the power button has no effect.

Possible relevant console log from Chrome:
`Mixed Content: The page at 'https://dev.ssllabs.com/ssltest/viewMyClient.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://plaintext.dev.ssllabs.com/plaintext/ping'. This request has been blocked; this endpoint must be available over WSS.
Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
GET https://dev.ssllabs.com:10444/ssl-labs-logo.gif?t=1461307135234 net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
GET https://dev.ssllabs.com:10200/1x1-transparent.png?t=1461307135234 net::ERR_CONNECTION_CLOSED
GET https://dev.ssllabs.com:10300/1x1-transparent.png?t=1461307135234 net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

Chrome dev 51.0.2704.19
uBlock git d34d470 (latest as of writing)
All testing in this post was done from an Incognito window.

[1] https://www.ssllabs.com/ssltest/viewMyClient.html
[2] https://dev.ssllabs.com/ssltest/viewMyClient.html

**Comment by gorhill** [comment]
uBO's WebSocket wrapper has to delay creating the real WebSocket instance, so that the URL can be fed to uBO's filtering engine, because as soon as you create an instance of a real WebSocket, the connection will be attempted (if only there was a `WebSocket.connect()` method...).

This means that in case a specific WebSocket connection is not allowed due to mixed content issues, the exception thrown will not occur from within the constructor, as the source on that page expect it.

To mimic as best as possible, I suppose uBO's wrapper should check itself for mixed content in its own wrapper ctor.

**Comment by TheRyuu** [comment]
Ah, that would make sense then.  What would worry me about the behavior before the fix is that because it's different from what's expected it could leak information (e.g. uBlock's presence).
