### ISSUE TITLE
Cannot add image noop rule for cloudfront.net

### ISSUE THREAD

**Issue by eproxus** [gorhill/uBlock#158]
The following rule cannot be added:

```
* cloudfront.net image noop
```

However, this rule works:

```
* cloudfront.net * noop
```

**Comment by gorhill** [comment]
By design: <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax>.

For higher granularity than what uBlock offers, use Policeman or uMatrix.

**Comment by eproxus** [comment]
Ah, missed the part about type based rules always being on `*`. Thanks!
