### ISSUE TITLE
Facebook Notifications Empty with Fanboy's Annoyance List in Chromium/Chrome

### ISSUE THREAD

**Issue by Magotchi** [gorhill/uBlock#1580]
### Describe the issue

When using Chromium or Chrome, when Fanboy's Annoyance List is enabled, the Facebook Notifications dropdown (shown after clicking the globe in the top-right of the Facebook desktop interface) has no notifications shown.

### One or more specific URLs where the issue occurs

https://www.facebook.com/ (logged in as a person)

### Screenshot in which the issue can be seen

http://i.imgur.com/RDnfcMn.png

### Steps for anyone to reproduce the issue

1. Install uBlock Origin in Chromium or Chrome.
2. Update all filters on the "3rd-party filters" tab in uBlock Origin's options.
3. Check "Fanboy's Annoyance List" on the "3rd-party filters" tab in uBlock Origin's options and click "Apply changes".
4. Visit https://www.facebook.com/
5. Log in as a person.
6. Click the globe (Notifications) icon at the top-right.

I tested it in Firefox on Arch Linux (64-bit), and the problem **did not** occur.
I also tested Adblock Plus in Chromium on Arch, with Fanboy's Annoyance List added as a custom filter, and the problem **did not** occur.

### Your settings

(I tested two browsers on two different OS, in order to be sure).
Browser: Chromium 50.0.2661.75 (64-bit) on Arch Linux (64-bit)
Browser: Chrome 50.0.2661.87 m on Windows 10 (64-bit)
uBlock Origin version: 1.6.8

default settings in uBlock, except for the additional filter checked
no other extensions enabled in browser

##### Your filter lists

Default filter lists + Fanboy's Annoyance List 201604221451

##### Your custom filters (if any)

none

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit

> Verify that the issue is not related to a 3rd-party filter lists.

This is the place you're looking for:
https://forums.lanik.us/viewforum.php?f=64
https://forums.lanik.us/rules

**Comment by Magotchi** [comment]
I got a notification about this issue saying that it shouldn't be posted here because it's related to a third-party filter list, but as you can see above, it doesn't occur with the same list in other situations:

> I tested it in Firefox on Arch Linux (64-bit), and the problem **did not** occur.
> I also tested Adblock Plus in Chromium on Arch, with Fanboy's Annoyance List added as a custom filter, and the problem **did not** occur.

**Comment by Magotchi** [comment]
I'm not familiar with the way messaging on GitHub works, so if this was 
a comment reply that then got deleted, I'll quickly delete this message 
if it appears as a comment.

Anyway, this is not a problem with just the third-party list:
 > I tested it in Firefox on Arch Linux (64-bit), and the problem **did 
not** occur.
 > I also tested Adblock Plus in Chromium on Arch, with Fanboy's 
Annoyance List added as a custom filter, and the problem **did not** occur.

**Comment by gorhill** [comment]
What does uBO's logger says?

**Comment by Magotchi** [comment]
Every time I click on the Notifications button, the logger shows a line like the following (and nothing else):
> 09:56:06    xhr    https://www.facebook.com/ajax/bz

**Comment by gorhill** [comment]
> I also tested Adblock Plus in Chromium on Arch, with Fanboy's Annoyance List added as a custom filter, and the problem did not occur.

That is simply not true.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/14747552/d66a0d6c-0882-11e6-9f23-85fb766e2ac0.png)

**Comment by Magotchi** [comment]
You're right.  I tested it again in Adblock Plus, and the problem did occur.  I don't know why I thought it worked the first time.  I'll get in touch with the creators of the list.  Sorry about the hassle.  Thanks for your time.

**Comment by Magotchi** [comment]
You're right about AdBlock Plus.  I re-tested it, and the problem did occur there.  I don't know where I went wrong in my first test.

However, the problem is NOT occurring in Firefox with uBlock Origin.  I've now tested that 3 times.

**Comment by gorhill** [comment]
> However, the problem is NOT occurring in Firefox with uBlock Origin. I've now tested that 3 times.

It does not occur in Firefox with ABP either.

**Comment by Magotchi** [comment]
Well, I made a [topic about it](https://forums.lanik.us/viewtopic.php?f=64&t=29966) over in the EasyList forums.  Hopefully they have an idea.  As it's occurring in Chrome/Chromium but not Firefox, with both uBlock Origin and ABP, that would seem to me like an ad-blocker/browser implementation issue rather than an issue with the list, but that's up to you to decide.

**Comment by gorhill** [comment]
> but uBlock Origin's developer believes the issue is with Fanboy's Annoyance List itself

I never said the issue is with Fanboy's List, I said report to them, they will decide whether there is an issue at all. Also, the fact that Facebook renders the site differently depending on the browser is not the fault of the blockers.

**Comment by Magotchi** [comment]
Sure.  That makes sense.  Excuse my choice of words.

**Comment by lewisje** [comment]
Whatever issue the list had must be gone; I saw it, and less than a day later the issue was fixed.

**Comment by ryanbr** [comment]
Was added because of this request: https://forums.lanik.us/viewtopic.php?f=62&t=29916&p=91969
