### ISSUE TITLE
How to hide strict block warning

### ISSUE THREAD

**Issue by varkmat** [gorhill/uBlock#1581]
Hi,

i am getting following type of warnings all the time,

i don't want to temporarily nor permanently disable strict blocking for many sites,

so i want to keep strict for particular site but don't want get selecting one of those options 

is there a way to hide strict block warning

http://s31.postimg.org/yzu8p3xmz/2016_04_23_3_32_35.png

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Strict-blocking

**Comment by varkmat** [comment]
i Did read that wiki full.

But there was no mention on how to block popup for a specific site without opening warning popup.

my question is, how to keep blocking the popup and also not seeing this warning?

**because this warning pop up causing as much annoyance as the popup ad it self**

**Comment by varkmat** [comment]
or at least give one more button in warning page, where it says, allow strict blocking for this domain permanently.

**Comment by IDKwhattoputhere** [comment]
Which site did the popup appear on? Was it some kind of redirection similar to a popunder? Because popups are already blocked for Directrev by EasyList.

**Comment by varkmat** [comment]
example : monova.org

when i click on the page, it opens another tab,where redirect kicks in (which gets block by  Peter Lowe’s Ad server list for that site)

still the site opens redirect many times, so i am seeing following message all the time, its annoying,

**my main question is, is there anyway to keep using strict block for a site, but not get warning message all the time?

maybe adding one more button in warning pop up to permanently block this site in strict blocking?**

**Comment by IDKwhattoputhere** [comment]
> when i click on the page, it opens another tab,where redirect kicks in

That's called a popunder.
`||directrev.com^$popup,third-party` in EasyList doesn't seem to be blocking it.
Try `||directrev.com^$popunder` in "My Filters".

**Comment by varkmat** [comment]
I added the filter and it works 90%

still when i click any part of the site, it still reloads,

is there a way to stop that?

btw, any idea on why easylist didn't work, any past experience on that?

thanks a lot.

**Comment by Hrxn** [comment]
> still when i click any part of the site, it still reloads, (no redirect,no pop up warning,just reload

Like the <a element as a background, or something like that? If that is the case, the site works as designed. The site is just crap then..

> btw, any idea on why easylist didn't work, any past experience on that?

You mean why I didn't work 100% in this special case?
Well, someone has to maintain these lists..

**Comment by IDKwhattoputhere** [comment]
@varkmat 
> I added the filter and it works 90%

So it blocks the popunder only 90% percent of the time? The other 10% it let's it slip through

> still when i click any part of the site, it still reloads, (no redirect,no pop up warning,just reload)

That's simply how they try to circumvent adblockers.

> is there a way to stop that?

You could block inline scripts for Monova.org using [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering). This will break some site functionality but is the only option since inline scripts is what they use for the popunders.

**Comment by varkmat** [comment]
sorry guys for not making it clear.

after adding the filter, it blocks popunder each time ! and no strict warning pop up is well!

so i got what i wanted,

only problem is, it reloads page when i click any part of the site (without filter,its another pop under) (meaning each and every time still wants to open popunder)

**as IDK said, it might be inline script, i will try dynamic filtering, if it won't break important functions

thanks a million guys for the help !!!!!**

**Comment by varkmat** [comment]
Btw, one last doubt guys,

is there anyway to keep strict blocking for specific sites (maybe using filter) without warning popup

that's exactly what i want, and that would be amazing, choosing strict block permanently for specific sites.

**Comment by IDKwhattoputhere** [comment]
Depends on the site. Maybe try a filter like above. BTW: Strict blocking **is** the warning message. What you want is popup or popunder blocking like with the above filter.

**Comment by varkmat** [comment]
Now i understand strict blocking,dynamic filtering and filter needs !

I prevented inline script for that site, and used the filter that you gave, now no reloads,no popunder,no strict block message !

thanks for the amazing help guys, you rock !!!!
