### ISSUE TITLE
please revisit the possibility of local mirroring aka surrogates

### ISSUE THREAD

**Issue by stewie** [gorhill/uBlock#1582]
I read the old version of the wiki page for the experimental local mirroring, and understand that it created problems. I also read that you intend to defer to other addons (e.g. decentraleyes) to achieve such surrogate functionality.

Even if decentraleyes adopts my (pasted here, hopefully rendered italic) request/suggestion,
managing rules/replacements via a single addon, ublock, would be more expedient.
_Many of the assets I would hope to replace do not appear in any "commonly used libraries" list, so I'm asking your to please consider supporting custom mappings. This could be a gui-less advanced feature. At startup, decentraleyes would just parse an additional custom_mappings.txt file, loading custom pairs of regex url match rule + file://path/to/replacement_

Different from the earlier experimental approach, none of the assets to be "mirrored" would be loaded into memory when ublock starts; ublock would just parse the custom mapping file, loading and injecting the appropriate replacement asset when a url matching rule is triggered.

Mozilla is already bundling a local jquery.min.js into the browser distribution, but it's only intended for use with devtools. My stance is this: if a webpage author (maliciously, or otherwise) intends the page to load an asset named, for example, "jquery.min.js" ...no, dammit, just inject my locally permacached copy of same named file. So far, decentraleyes approach is lame, is ineffectual, toward meeting this goal.

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/issues/1364#issuecomment-182619292

**Comment by anewuser** [comment]
@stewie https://addons.mozilla.org/firefox/addon/decentraleyes/
