### ISSUE TITLE
[Chrome] Problem blocking ads flightradar24.com

### ISSUE THREAD

**Issue by Irbidan** [gorhill/uBlock#1583]
### Describe the issue

Using Google Chrome with uBlock Origin enabled appear certain ads and warnings.

### One or more specific URLs where the issue occurs

www.flightradar24.com

### Screenshot in which the issue can be seen

![screenshot](https://cloud.githubusercontent.com/assets/541941/14761911/67599faa-096d-11e6-971b-55b6123a6001.JPG)

### Steps for anyone to reproduce the issue

1. Enter www.flightradar24.com
2. Check left column and footer

### Your settings

- Browser/version: Google Chrome 50.0.2661.87 m (64-bit)
- uBlock Origin version: 1.68
![config](https://cloud.githubusercontent.com/assets/541941/14761942/708cb822-096e-11e6-877a-49bbcb0a548a.jpg)

**Comment by gorhill** [comment]
What evidence do you have that this is *not* a filter list issue?

**Comment by fuzzyroddis** [comment]
@Irbidan have you updated your filters in Chrome?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
