### ISSUE TITLE
Create button is grayed

### ISSUE THREAD

**Issue by vSolo** [gorhill/uBlock#1586]
I want to remove the top of a banner on my home router, IP address is 192.168.1.1, I use ublock origin element is selected but the Create button is grayed out, please help solve, thank you
URL(s)=192.168.1.1 and the router is FAST
### Screenshot in which the issue can be seen

![bar](https://cloud.githubusercontent.com/assets/9264222/14764988/874b5172-09ff-11e6-82bc-36a58a9e70b3.jpg)
![button](https://cloud.githubusercontent.com/assets/9264222/14764989/8c9185c0-09ff-11e6-9824-f2659825d13d.jpg)

### My settings
- Browser/version: FireFox 45.0.1
- uBlock Origin version: 1.6.4

##### My filter lists
Default filter lists + CHN  minus Experimental‎

**Comment by gorhill** [comment]
Because your filter does not match any element on the page.

**Comment by vSolo** [comment]
Still grateful, but my problem is still not resolved
