### ISSUE TITLE
Facebook notifications popup doesn't work fine when uBlock is enabled

### ISSUE THREAD

**Issue by RamRS** [gorhill/uBlock#1587]
### Describe the issue
Facebook notifications pop-up menu is not shown when uBlock Origin is enabled. I dug into the HTML and I see that the `<ul>` of notifications is removed when uBlock is enabled

### One or more specific URLs where the issue occurs
https://www.facebook.com/

### Screenshot in which the issue can be seen
With uBlock enabled, the notification panel does not show notifications:
![Disabled](http://i.imgur.com/gNF4UnB.png)

With uBlock disabled, the panel works fine:
![Enabled](http://i.imgur.com/2hr49Rf.png)

### Steps for anyone to reproduce the issue

1. Log in to facebook with uBlock enabled
1. Open notifications dialog

NOTE: Intermittently, the notification dialog works fine even with uBlock enabled. Also, I'm seeing this only over the past 24 hours.

### Your settings

- Browser/version: Google Chrome Version 49.0.2623.112 m on Windows 10
- uBlock Origin version: 1.6.8

##### Your filter lists

Default filter lists + Facebook Annoyances Blocker

##### Your custom filters (if any)

```
@@-social_$domain=facebook.com,image
```

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by RamRS** [comment]
Is the closing because it's a filter related issue? Apologies if that's the case - I did not notice that part of the CONTRIBUTING.

**Comment by gorhill** [comment]
See #1580. uBO's logger will help you diagnose yourself filter list issues.
