### ISSUE TITLE
uBlock0 breaks Google Images previews

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#159]
uBlock0 v0.9.6.0 - Firefox 37.0.2 - XP Pro SP3 

I noticed with uBlock0 v0.9.5.0 (but since when?) that it breaks Google Images previews. The issue is the same with v0.9.6.0 newly installed. 
It looks like this: 
![screenshot01265](https://cloud.githubusercontent.com/assets/11029138/7417916/e02e3eb4-ef69-11e4-8506-204c449be7a4.png)
Just a Xclose icon instead of image previews...

Thanks if finding the why from the how (litteral translation huh!)

**Comment by gorhill** [comment]
Can't reproduce using the limited provided information (assuming default settings, and I picked a random URL). See <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include>.

**Comment by onestepbeyond** [comment]
Thanks for the steps to reproduce. 
Here's a short link to a broken image preview: http://tinyurl.com/mg8jvfv (but it happens everywhere).  
I use uBlock0 in basic version (not advanced). 
In the settings, only "Hide placeholders..." and "use the context menu..." are ticked. 
In the list of "origin" filters are checked the first 4 boxes (my filters & uBlock filters), EasyList, EasyPrivacy, Fanboy's Social, EU: Prebake and Liste FR. 
I have a list of personal filters.
I do not use permanent or temporary rules. 

Here's what I did:
In Firefox profile, First disabled my personal css styles ; no results. (Revert). 
Then, in uBlock0, emptied my personal filter list, still not better... (Revert).  
I just found the culprit! it is EasyPrivacy. When turned off, everything works in Google Images.
I did several cross-tests and only EasyPrivacy induced this behavior.

**Comment by onestepbeyond** [comment]
Hello Betsy, seems indeed the same issue...

**Comment by gorhill** [comment]
I see `||www.google.*/url?$image` in EasyPrivacy is the culprit. Same issue occur with ABP + EasyPrivacy.

Report to EasyPrivacy maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by onestepbeyond** [comment]
The workaround works fine, thanks! 
I have an account at forums.lanik.us, I'll go report the issue.
