### ISSUE TITLE
 Fanboy’s Social Blocking List‎ breaks flightradar24.com with v1.6.9

### ISSUE THREAD

**Issue by octoploid** [gorhill/uBlock#1590]
Running latest v1.6.9 with Chromium 52.0.2716.0.
Fanboy’s Social Blocking List‎ breaks flightradar24.com.
Only a black page is displayed. 
Disabling "Fanboy’s Social Blocking" fixes the issue.

It works fine with v1.6.8 and Firefox.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
