### ISSUE TITLE
Chrome display iframe error for doubleclick ads

### ISSUE THREAD

**Issue by boussouira** [gorhill/uBlock#1591]
When i use uBlock Origin without Ghostery on Chrome, i run to a lot of this:
[Screenshot](http://i.imgur.com/D9pwsvF.png)

is this normal? can uBlock do anything to hide those iframes like Ghostry?

### One or more specific URLs where the issue occurs
[Server Fault](http://serverfault.com/questions/360473/gzip-compression-doesnt-work-in-nginx-reverse-proxy-setup)

### Screenshot in which the issue can be seen
See above

### Steps for anyone to reproduce the issue

1. Disable Ghostry or alike extensions, keep only uBlock Origin
2. Visit [the website](http://serverfault.com/questions/360473/gzip-compression-doesnt-work-in-nginx-reverse-proxy-setup)

### Your settings
- Chrome 49
- uBlock Origin 1.6.8 

##### Your filter lists

Default filter lists minus uBlock -- Badware risks

**Comment by gorhill** [comment]
The issue occurs **only** when the following exception filter from EasyList kicks in on the page:

    @@||static.adzerk.net/ados.js$domain=serverfault.com|stackoverflow.com

I don't know what is the purpose of such exception filter, but its effect is to whether leave a broken `iframe` behind, or a gap (which is actually a blocked `img`).

Using this filter:

    ||static.adzerk.net/ados.js$script,important,domain=serverfault.com|stackoverflow.com

Will override the exception filter and block the script from `adzerk.net`. See if this works or you, if so, I will add it to uBO's filters.

I would normally close and mark this issue as _Invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), but I suspect that uBO's injected content scripts in the parent `iframe` bail out before script tags are added to child `iframe`, preventing it from hiding the placeholder. At this point, the simplest solution is to just outright block `adzerk.net`. You may want to find out why EasyList maintainers are allowing scripts from `adzerk.net`.

**Comment by gorhill** [comment]
I have been unable to track down the reason why this exception filter was added -- so I went ahead and added the above filter to override the exception.

**Comment by boussouira** [comment]
It work as excpected, thank you
