### ISSUE TITLE
Please integrate I don't care about cookies Filterlist and Adware Filters Filterlist (MonztA)

### ISSUE THREAD

**Issue by gunther1** [gorhill/uBlock#1592]
Hello.
Please integrate 

- Idon't care about cookies   Filterlist and 

- Adware Filters   Filterlist (from MonztA)

in a new version from uBlock Origin.

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/search?q=i+dont+care+about+cookies&type=Issues&utf8=%E2%9C%93

https://github.com/gorhill/uBlock/search?q=adware+list&type=Issues&utf8=%E2%9C%93

Use the search. Use [FilterLists.com](https://filterlists.com).
