### ISSUE TITLE
Fonts blocking doesn't work at wsj.com in Google Chrome for Linux

### ISSUE THREAD

**Issue by birdie-github** [gorhill/uBlock#1593]
While I'm at http://www.wsj.com/articles/computers-that-crush-humans-at-games-might-have-met-their-match-starcraft-1461344309 and trying to block fonts, visually nothing happens - Chrome still uses custom fonts (as proven by the developer console).

Google Chrome 50.0.2661.86 (64-bit), the official Linux RPM
uBlock Origin v1.6.8

![wsj](https://cloud.githubusercontent.com/assets/4958603/14794296/13dc2904-0b45-11e6-883a-a9385171237e.png)

**Comment by gorhill** [comment]
Please search first: #1539.
