### ISSUE TITLE
U block breaks yahoo mail page, no search bar

### ISSUE THREAD

**Issue by 206greasemonkey** [gorhill/uBlock#1595]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>
when U block is enabled it doesn't allow Yahoo mail page to show search bar.
![no search bar with u block enabled](https://cloud.githubusercontent.com/assets/18699764/14851432/e266e030-0c4d-11e6-8c66-9c1c59fa20ac.PNG)
![disabled u block now search bar](https://cloud.githubusercontent.com/assets/18699764/14851440/efb0d958-0c4d-11e6-9e1f-5882250f78de.PNG)

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Can you find which filter causes this?

- See if toggling off cosmetic filtering brings back the search bar.
- Use the logger, see if you can identify a culprit filter.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by 206greasemonkey** [comment]
cosmetic filtering is the cause.
 

    On Wednesday, April 27, 2016 10:30 AM, Raymond Hill <notifications@github.com> wrote:
 

 Can you find which filter causes this?   
   - See if toggling off cosmetic filtering brings back the search bar.
   - Use the logger, see if you can identify a culprit filter.
