### ISSUE TITLE
Preferring document over popup filters

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1598]
### Describe the issue

uBO is sometimes preferring $document over $popup filters. This results in strict blocking dialogues that wouldn't need to appear IMO (when using using uBlock Filters + for example).

### One or more specific URLs where the issue occurs

`http://monova.org/`

### Screenshot in which the issue can be seen

![](https://cloud.githubusercontent.com/assets/16030872/14856627/27902e32-0c99-11e6-9e57-14f8c0a69f17.png)

### Steps for anyone to reproduce the issue

1. Add the filter at the bottom.
1. Visit Monova and click "Browse".

Result: uBO sometimes doesn't close the popunder even though EasyList contains `||directrev.com^$popup,third-party` ~~and `/realmedia/ads/*$popup`~~.

### Your settings

Default settings.

- Browser/version: Chrome 50
- uBlock Origin version: 1.6.8

##### Your filter lists

Default.

##### Your custom filters (if any)

`/realmedia/ads/*$document`

**Comment by gorhill** [comment]
uBO does not choose between one or the other, popups and strict blocking are two completely different code paths, given their difference in purpose. Even when a document is strict-blocked, the popup blocker will still look to close the tab, as it will fall back on using the blocked URL for filtering purpose. Your page above should definitely have been closed. This needs investigation.

**Comment by gorhill** [comment]
Ok, it's a popunder issue: uBO will detect and extract the real target URL for popup, but it does not apply that detection to the source URL, which in the current case is the tab to close.

**Comment by gorhill** [comment]
Never mind, code works correctly.

It's a limitation of popunder detection: as stated when released, the _broad_ popup filters won't be used for popunders. `/realmedia/ads/*$popup` is _broad_, it applies to all domains.

**Comment by IDKwhattoputhere** [comment]
> `/realmedia/ads/*$popup` is broad

True. My mistake.

**Comment by IDKwhattoputhere** [comment]
Why closed? Seems I misunderstand. Shouldn't `||directrev.com^$popup,third-party` from EasyList be applied to the popunder?

**Comment by gorhill** [comment]
> Shouldn't `||directrev.com^$popup,third-party` from EasyList be applied to the popunder?

EasyList filters do not obey a precedence concept. Whichever filter is found first will be deemed a hit. uBO (or any other blocker) can't start evaluating for all possible hits, this would make them highly inefficient.

**Comment by gorhill** [comment]
However, 2 seconds after I posted my comment, I realize uBO could try a 2nd evaluation round using just the origin part of the URL (i.e. `http://directrev.com`). This would add an overhead of trying to match again a filter, but this would apply _only_ for a case of popunder detection.

**Comment by gorhill** [comment]
This will not guarantee that all popunders will be caught by the second attempt, my earlier comment still stand. However, the second attempt is a reasonable one. Everything else that is not caught by the popunder-guessing code, then a specific `popunder` filter will have to be created.
