### ISSUE TITLE
popup selection issues in palemoon statusbar

### ISSUE THREAD

**Issue by 0strodamus** [gorhill/uBlock#1599]
OS: Arch Linux x64
Browser/version: Pale Moon 26.2.1 (occurs in earlier versions too)
uBlock Origin version: 1.6.9rc1 (occurs in earlier versions too)

I've tried my best to provide a reproducible test condition below. I can reproduce this with a new Pale Moon profile in Virtualbox, so I hope this isn't limited to something unique with my setup and I'm wasting your time in reporting. I can only get this issue to occur if uBlock Origin's icon is moved to the statusbar.

Issue reproduction:
1) Move uBlock Origin's icon from Pale Moon's Navigation Toolbar to the Status Bar.
2) Customize the Status Bar by adding a "Flexible Space" to the right side of the uBlock Origin icon.
3) Load any webpage and open the dashboard (click popup titlebar) and/or log window (click log icon) or sometimes both.
![can-select](https://cloud.githubusercontent.com/assets/18707615/14867172/2769b990-0c7c-11e6-821b-da0f81019e78.png)

4) Go back to the webpage tab - now the element picker and log icon cannot be selected (doesn't matter if popup is collapsed or expanded). Sometimes the large power button is affected too.
![cant-select2a](https://cloud.githubusercontent.com/assets/18707615/14867519/c4ed88f8-0c7d-11e6-89c4-96010ac813b2.png)

Workaround (only works if "I am an advanced user" is selected in settings):
Depending on the popup state when initially opened, either
click "- requests blocked" or "- domains connected" to collapse popup - now large power button, dashboard, element picker, or log window icons can be clicked
![can-select](https://cloud.githubusercontent.com/assets/18707615/14867172/2769b990-0c7c-11e6-821b-da0f81019e78.png)
or
click "+ requests blocked" or "+ domains connected" to expand popup - now large power button, dashboard, element picker, or log window icons can be clicked
![still-can-select](https://cloud.githubusercontent.com/assets/18707615/14867237/73367714-0c7c-11e6-8dda-53bea48d34f3.png)

other observations: when large power button, element picker, and log window icons cannot be selected, hovering over the site-based switches seems to be offset by 1 switch to the left

EDIT: added OS version information

**Comment by gorhill** [comment]
Weird issue, will need to investigate. Speculation: some non-uBO styles are bleeding into uBO's popup panel?

**Comment by 0strodamus** [comment]
Thanks for the prompt response!

I have another observation to report. The first time uBO's popup is opened, it is directly lined up with the uBO statusbar icon.
![1st-popup](https://cloud.githubusercontent.com/assets/18707615/14906319/074b1f3e-0d6f-11e6-94f2-9b1434efca47.png)
After opening and closing the dashboard and/or log window and reopening the popup, it is offset to the right of the uBO statusbar icon.
![2nd-popup](https://cloud.githubusercontent.com/assets/18707615/14906356/637ea7bc-0d6f-11e6-9fb3-0e528c2e53b0.png)
I think this offset is the problem and it explains why the site-based switches are offset when hovered over. Expanding or shrinking the uBO popup lines it back up directly over the uBO statusbar icon. My apologies for not noticing and reporting this with my initial issue report.

I also tried to recreate the issue in Firefox 24 ESR and couldn't. I've done all testing with new user profiles and no other extensions installed. I'm thinking there must be some difference between Pale Moon's statusbar implementation of the toolbar item "Flexible Space" vs. Firefox's Add-on bar that's causing this behavior. I wonder why Pale Moon's statusbar popup isn't being consistently placed? I could work around the problem by replacing the single "Flexible Space" I'm using with a ton of "Space" items, but I'm hoping it's something that can be fixed. Thanks again for the reply and for creating and sharing uBO!

**Comment by TPS** [comment]
Perhaps related to https://github.com/gorhill/uBlock/issues/833#issuecomment-186042687?

**Comment by 0strodamus** [comment]
I've never experienced an issue with the icon going missing after a restart. I see 2 references in that thread to Windows. I'm running Linux, so maybe that issue is isolated to Windows builds of Pale Moon?

**Comment by 0strodamus** [comment]
I'm going to close this issue as it is a corner-case. I've had no issues since removing the "Progress Meter" item from the statusbar.
