### ISSUE TITLE
Firefox on Mac doesnt completely closes with active uBlock Origin Tab open

### ISSUE THREAD

**Issue by 3ckH4rd** [gorhill/uBlock#1600]
Mac OS El Capitan 10.11.4

Firefox 46.0 (also with Firefox 45 I had same issue)

uBlock Origin 1.6.8

Open uBlock Settings in Browser and then chose "Firefox" - "Close". Firefox will hang and has to be forced to shut down.

**Comment by gorhill** [comment]
Search issue first please. Duplicate of #1573.
