### ISSUE TITLE
Can't seem to set up filters in about:home.

### ISSUE THREAD

**Issue by khatharr** [gorhill/uBlock#1601]
I have a Stylish filter that removes the 'snippets' div from about:home. I've only ever used Stylish for blocking things that naive filters didn't catch, but now that I've learned to block elements with UO I've converted all of them, and this is the last one remaining.

This applies exclusively to Firefox's about:home page. There's no 'block element' option in the context menu on this page, and if I try to activate the picker nothing happens. I get that this may be due to some kind of security issue, but if possible I'd like to be able to use UO normally on this page.

I did try creating a custom filter, but it didn't work. I tried:

about:home###snippets < div

I'm using Firefox 45.0.2 with uBlock Origin 1.6.8.

**Comment by IDKwhattoputhere** [comment]
As a workaround: What about setting `browser.aboutHomeSnippets.updateUrl` to ` ` in about:config?

**Comment by khatharr** [comment]
I think I tried that before but it didn't work for some reason. I'll check it out again.

**Comment by Piter432** [comment]
I think you should remove `about-scheme` from your whitelist in your uBO's settings and then try again.

**Comment by khatharr** [comment]
I don't have that entry, but I just tried removing everything from the the whitelist temporarily and restarting, but it didn't work.

**Comment by gorhill** [comment]
uBO's content scripts are not injected into anything else than http/https. The content scripts are needed for cosmetic filtering.

**Comment by khatharr** [comment]
Is that the same as "no"?

**Comment by berrythesoftwarecodeprogrammar** [comment]
well since he didn't close it, maybe he will do something about it... @IDKwhattoputhere's solution works fine for me though, I've never seen any 'snippets'. maybe consider changing your homepage to the actual search engine you use or make a file identical to about:home without the crap. maybe you can check the logger for the requests it makes for the snippets and block that in about-scheme or behind-the-scene (whichever one it uses to make the request)

**Comment by gorhill** [comment]
Not "no", rather "not sure" at this point. For the sake of code sanity, I need better arguments than "to replace Stylish": that is not the purpose of uBO.

**Comment by khatharr** [comment]
I'm not really looking to replace Stylish categorically; I was just thinking that it would be nice to have only one plugin doing the "remove content cancer" job. From the user perspective it doesn't make any sense for uBO to not work on any page.  I get that it's a different story from the implementation side, though I don't work with browser stuff much, so I don't know how complex it would be and therefore can't gauge whether it's worthwhile.

In any case, it's my request as a user, fwiw.

**Comment by anewuser** [comment]
>In any case, it's my request as a user, fwiw.

Read what this says about requests: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by onestepbeyond** [comment]
@khatharr For that purpose, I use a simple userscript (_usercontent.css_, in the `chrome` subfolder): 
```
/* hide snippet on the about:home page */
@-moz-document url(about:home) {
#snippetContainer {
    display: none !important;
    }
}
```
An ultralightweight 137 Bytes file...
That said, I'm aware that it does not really answer your question.
