### ISSUE TITLE
Blocked Count Icon showing three dots instead of number

### ISSUE THREAD

**Issue by dave47** [gorhill/uBlock#1602]
Windows 7  Ublock Origin 1.7

**Comment by gorhill** [comment]
There is nothing I can do with so little details.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by dave47** [comment]
Instead of count of blocked getting ...



On 5/2/2016 5:12 PM, Raymond Hill wrote:
>
> Closed #1602 <https://github.com/gorhill/uBlock/issues/1602>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1602#event-648134244>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dave47** [comment]
Instead of count of number blocked getting ... dot dot dot



On 5/2/2016 5:12 PM, Raymond Hill wrote:
>
> Closed #1602 <https://github.com/gorhill/uBlock/issues/1602>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1602#event-648134244>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by IDKwhattoputhere** [comment]
Read: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
What about a screenshot for example? Your browser? The information you're providing is not enough by far.

**Comment by dave47** [comment]
I did supply an embedded screen shot.  Scroll down.  I have now included 
it as an attachment also.


On 5/6/2016 7:56 AM, IDKwhattoputhere wrote:
>
> Read: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
> What about a screenshot for example? Your browser? The information 
> you're providing is not enough by far.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1602#issuecomment-217421166>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hrxn** [comment]
I don't see any embedded screenshots or an attachment or anything else of use?

**Comment by dave47** [comment]
How is this?
On 5/6/2016 12:38 PM, H R X N wrote:
>
> I don't see any embedded screenshots or an attachment or anything else 
> of use?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1602#issuecomment-217493105>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dave47** [comment]
If you haven't gotten yet there is something in your email system that 
is filtering it out.  The attachment is a .png file


On 5/6/2016 1:28 PM, Dave Auge wrote:
>
> How is this?
> On 5/6/2016 12:38 PM, H R X N wrote:
>>
>> I don't see any embedded screenshots or an attachment or anything 
>> else of use?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/gorhill/uBlock/issues/1602#issuecomment-217493105>
>>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by IDKwhattoputhere** [comment]
Just go to https://github.com/gorhill/uBlock/issues/1602#issuecomment-217512700 and fill out this template you deleted:
https://pastebin.com/raw/eW50vHYU
Post it here. You can upload screenshots right here too (`Attach files by dragging & dropping, selecting them, or pasting from the clipboard.`).
