### ISSUE TITLE
uBlock Origin blocking BinaryTypes on WebSockets

### ISSUE THREAD

**Issue by AdrianKoshka** [gorhill/uBlock#1603]
### Description
I assume Ublock origin interferes with communication between websockify and spice-html5. It makes chrome spit up an error about ``BinaryTypes`` not being supported. Though upon installing a clean, stock, fresh install of chromium, spice-html5 works! My next step was to try to whitelist the page, this for some reason did not work, even though ublock origin was "disabled" it wasn't fully? So unless I went into the ``extensions`` section of chrome, and/or chromium, and disabled ublock origin that way, spice-html5 would through this error up and refuse to work.

### One or more specific URLs where the issue occurs
http://adriankoshka.xyz/spice-html5/spice.html
http://www.spice-space.org/spice-html5/spice.html

## Working in a stock install of Chromium
![working in chromium](https://a.pomf.cat/etvzok.png)
## Working with ublock origin completely disabled via extensions settings.
![working_2](https://a.pomf.cat/tmbzmp.png)
## The error chrome was throwing up with ublock origin enabled, and whitelisted
![stupid](https://a.pomf.cat/kkpfrq.png)
## Ublock origin "whitelisted" on my site, still not working
![even worse](https://a.pomf.cat/mkjvjl.png)

### Steps for anyone to reproduce the issue

1. Install chrome and/or chromium
2. Install ublock origin
3. go to [this](http://www.spice-space.org/spice-html5/spice.html) link and type any password, try to login
4. see if you get the same error

### Your settings

All settings for ublock origin are default, except for the whitelisting of adriankoshka.xyz for test purposes.

- Browser/version: 
- uBlock Origin version: 1.7.0

#####  filter lists
 Default filter lists

**Comment by gorhill** [comment]
Websocket support in uBlock Origin has been moved to a separate companion extension, so the fix is in the next release of that companion extension. Sorry for the inconvenience.

**Comment by AdrianKoshka** [comment]
Thanks for the quick response! The inconvenience was very little, thanks again.
