### ISSUE TITLE
Tradingview does not work, despite an entry in uBlock's whitelist.

### ISSUE THREAD

**Issue by findftp** [gorhill/uBlock#1605]
I use www.tradingview.com to view financial charts.
I think something got updated because suddenly the site doesn't give a chart anymore when the plugin is enabled.
I've put the site in the whitelist but it doesn't work. Also pressing the enabled/disabled button doesn't work
Only when I completely disable the plugin the website works.
I'm on chromiumbrowser Version 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)
uBlock version 1.7.0

Few days ago it worked without problems.

**Comment by gorhill** [comment]
Duplicate of #1604.

**Comment by findftp** [comment]
Oh, I'm really sorry!

**Comment by gorhill** [comment]
Don't, I am the one who should (I do) feel sorry.
