### ISSUE TITLE
Videos not playing on BBC

### ISSUE THREAD

**Issue by ResetOnset** [gorhill/uBlock#1608]
With uBlock enabled, Flash videos throw an error. So to watch video on BBC I have to disable uBlock.

Example URLs where the issue occurs:
http://www.bbc.co.uk/sport/football/36183247
http://www.bbc.co.uk/sport/football/36188970

Steps to reproduce the issue:
Visit BBC website and try to play Flash videos. In the above examples I had uBlock enabled and an error appeared where the video should appear, stating "This content doesn't seem to be working".
After disabling uBlock and refreshing the page, videos play properly. As a test I then re-enabled uBlock and tried to play the same video and the error appeared again.

Right-clicking on the flash file that will not play gives this detailed error:
```
Error code : EmpBaseErrorVO
code = 1024
type = No further playback is possible following a mediation error
detail = 

1026
severity = critical
responsibility = MediaSelector
info = 1026
```

- Browser/version: Iceweasel (Firefox) 38.8.0 running on Linux, Debian 7 
- uBlock Origin version:  v1.7.0

My filter lists:
uBlock filters‎ : 4 (all except Experimental)
EasyList‎ (forums.lanik.us)
Peter Lowe’s Ad server list‎ (pgl.yoyo.org)
EasyPrivacy‎ (forums.lanik.us)
Malware Domain List‎ (malwaredomainlist.com):
Malware domains‎ (www.malwaredomains.com):
 EU: Prebake - Filter Obtrusive Cookie Notices‎ (github.com)

**Comment by gorhill** [comment]
I do not have IceWeasel, but I tried on Palemoon, Firefox 46, Nightly, Chromium 49, Chrome 52 andI could not reproduce the issue, BBC player played fine.

**Comment by gorhill** [comment]
Actually, strike this, I can't get it to play on FF 46, but it works fine on Palemoon, Nightly.

**Comment by ResetOnset** [comment]
I'll try to get Flash installed on other browsers on my Debian system to test - (not a trivial job at first glance!)

**Comment by gorhill** [comment]
It works fine when using the exception filter `@@||stats.bbc.co.uk/o.gif$object,domain=bbc.com|bbc.co.uk` (to override `||stats.bbc.co.uk` in EasyPrivacy).

Currently I am flustered as to why this works fine in other browser without this exception filter, but I will add it so that it un-breaks BBC player, and investigate further for the root of the problem.

**Comment by gorhill** [comment]
Re-opening for further investigation.

**Comment by ResetOnset** [comment]
Thanks for your help gorhill - I confirm that adding your exception filter has fixed the issue here.

**Comment by gorhill** [comment]
I changed the exception filter into a redirection filter, to preserve the block, you may want to use this instead, or more simply, force an update of your filter lists.

Still can't make sense of why this works in other browsers without that filter. Also, the player works fine with ABP with blocking the `stats.bbc.co.uk/o.gif` network requests. There seems to be some sort of a timing issue.
