### ISSUE TITLE
[Feature Request] Fanboy's Cookiemonster List

### ISSUE THREAD

**Issue by liracobopu** [gorhill/uBlock#1609]
Fanboy recently created a [separate Anti-Cookies List from his Annoyances List](https://www.fanboy.co.nz/).
https://www.fanboy.co.nz/fanboy-cookiemonster.txt

I believe it is a better alternative to [Prebake](http://prebake.eu/) as it is updated frequently. It would be nice to add Fanboy's list to uBlock's list of filters.

**Comment by gwarser** [comment]
Better than this http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/ ?

**Comment by Hrxn** [comment]
For requests regarding filter lists et al. : 

https://github.com/uBlockOrigin/uAssets

If you want to add a custom list, you can already do that,
on the 3rd party filter lists tab..

**Comment by happysurf** [comment]
In any case these are the differences: 
- I don't care about cookies‎ list = 7200 filters;
- Cookiemonster list = 2100 filters;
- Prebake list = 850 filters.

**Comment by gorhill** [comment]
I declined to add _I don't care about cookies‎_ because the author advise to install hist own extension to use the list.

Now, I wonder how much _Cookimonster_ and _Prebake_ intersects. Also, would _Cookiemonster_ qualify as a "EU" list, or is it completely generic (in which case I have no idea in which category it would fit).

**Comment by IDKwhattoputhere** [comment]
In the past you declined the Block-EU-Cookie-Shit-List‎.
https://github.com/gorhill/uBlock/issues/103
Is this any different?

**Comment by happysurf** [comment]
This is the Cookiemonster list description by the author:
"_This will remove **cookie and privacy warnings** (List already included in Annoyances List, don't add list if you're using the Annoyances List)_" , for that I think could replace the poor EU Prebake list.
Actually now  I have only Cookiemonster enabled (with I don't care about cookies list disabled) for testing.

**Comment by gorhill** [comment]
> _List already included in Annoyances List_

Well that makes it easy: no point adding that CookieMonster list then.

**Comment by happysurf** [comment]
Unfortunately the Annoyances List blocks also important element (for me and maybe for other users) in the pages like the RSS - Feed.
Therefore could be useful have an efficient separate cookie filter list.

**Comment by liracobopu** [comment]
@gorhill Based on your argument, then remove Social Blocking since it is included in Annoyances, or remove the separate EasyList, EasyPrivacy lists because they're already included in Fanboy Ultimate.

Like @happysurf I find Annoyances List to block too many things. Killing the annoying and sometimes obtrusive cookie notices is all I really care for.

If you did decide to add the list, I would classify it as an EU list as these annoying cookie notices are a direct result of EU law. If you simply scanned the list yourself, you'd see that most are european-based domains/companies or multinational companies.

Oh well. I just wanted to add the list because on Android for Firefox, it is much easier to check the lists I want than manually add a list.

**Comment by vlakoff** [comment]
Is there a clear winner between "Prebake", "EU cookie shit" and "Fanboy's Cookiemonster"?
(search "cookie" on [filterlists.com](https://filterlists.com/) to quickly get the relevant links)

"Prebake" hasn't been updated for a year, "I don't care about cookies" is ruled out, "EU cookie shit" seems quite small.

Therefore remains"Fanboy's Cookiemonster", to replace "Prebake".

**Comment by happysurf** [comment]
You are right but there is an other great alternative, **Adguard Annoyances Filter​** and works great on cookie notifications.
- Cookiemonster list = 2100 filters;
- Adguard Annoyances Filter​ = 7200 filters.

**List:**
https://filters.adtidy.org/extension/chromium/filters/14.txt

**Description:**
Blocks irritating elements on webpages, including cookie notices, third-party widgets and in-page popups (Doesn’t include social media widgets and buttons, to block them you can still use Social media filter separately). It was inspired by Fanboy Annoyances List, but doesn’t duplicate it, so you can use them both together.

**Comment by vlakoff** [comment]
After having tested "Fanboy's Cookiemonster" for a few days, I still got a handful of cookies banners.

Guess I'll just switch back to "I don't care about cookies" which was doing the job really fine. But this time I won't use the separate extension, I'll add its list to uBlock, for performances reasons.

**Comment by heubergen** [comment]
I think Adguard Annoyances Filter is not appropriate as a Cookie List because it do so much more.h

I'd like to suggest block-the-eu-cookie-shit-list with currently 1152 filters.

**Comment by vlakoff** [comment]
I tried all the mentioned lists, including "I don't care about cookies", and I am still getting a lot of banners.

When I was using "I don't care about cookies" as a separate extension, I was almost never getting banners. Does the separate extension block more stuff?

**Comment by elypter** [comment]
just a guess but maybe the addon adds cookies to the browser to shut up the websites

**Comment by gorhill** [comment]
> I tried all the mentioned lists, including "I don't care about cookies", and I am still getting a lot of banners.

Provide one or more example URLs of such issue please.

**Comment by vlakoff** [comment]
I forgot I had unchecked "**Ignore generic cosmetic filters**" for performance reasons (hobo computer)…

Just checked it again, and went from "f–ing banner on every site" to "close to zero banners".

**Comment by gorhill** [comment]
Fixed with 355dbc00.
