### ISSUE TITLE
Requests list page on Firefox/Android has overlapping buttons

### ISSUE THREAD

**Issue by colaas** [gorhill/uBlock#161]
There are two buttons overlapping on the right in the requests page in uBlock on Firefox/Android next to the tabs menu. (the image is downsized, the phone's resolution is 1920x1080). They do not overlap when using the phone horizontally.
![a](https://cloud.githubusercontent.com/assets/12163378/7428038/2013faf8-efe9-11e4-94ce-f8c84d275d93.png)

P.S. just noticed that the maximum number box is also cut off

**Comment by gorhill** [comment]
That button does not exist anymore.
