### ISSUE TITLE
Feature Enhancement: regex blocking

### ISSUE THREAD

**Issue by seshaljain** [gorhill/uBlock#1610]
I believe regex can make blocking much more effective.

For example, a site foo.com:
If I want to block a specific element on all subdomains of the site, I want to use *.foo.com as the addressing filter. Thanks in advance!

I felt that since this an enhancement request, the required details are not necessary.

**Comment by gorhill** [comment]
Without specific, concrete case I do not understand exactly what you are asking. Provide a concrete example of what you want would look like and what it would accomplish exactly. I feel that what you are asking is already supported.

**Comment by gorhill** [comment]
See https://adblockplus.org/filters

**Comment by lewisje** [comment]
In case you don't read that link, the following cosmetic filter will hide all paragraph elements (the ones surrounded by `<p>` tags) on `foo.com` and all subdomains:

    foo.com##p

This blocking rule will block all third-party content on `foo.com` and all subdomains:

    *$third-party,domain=foo.com

The key phrase is "domain specifier."

**Comment by seshaljain** [comment]
Thank You!
