### ISSUE TITLE
dot dot dot

### ISSUE THREAD

**Issue by dave47** [gorhill/uBlock#1614]
![snapshot](https://cloud.githubusercontent.com/assets/18049384/15081991/7dc1d57a-1393-11e6-8e77-bbabd151b16c.png)

**Comment by IDKwhattoputhere** [comment]
Why tf didn't you post it here: https://github.com/gorhill/uBlock/issues/1602

**Comment by lewisje** [comment]
The taskbar does look like Windows 7 with the Classic theme.

**Comment by dave47** [comment]
It is windows 7 and the theme is Blue Sharepoint.  The three dots just 
started showing up a week or two ago.  Prior to that it had always shown 
the count which is selected in options in Dashboard.  The three dots are 
on the tab bar just to the right of the download arrow.



On 5/6/2016 4:24 PM, James Edward Lewis II wrote:
>
> The taskbar does look like Windows 7 with the Classic theme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1614#issuecomment-217549180>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dave47** [comment]
ublock origin is 1.7.0


It is windows 7 and the theme is Blue Sharepoint.  The three dots just 
started showing up a week or two ago.  Prior to that it had always shown 
the count which is selected in options in Dashboard.  The three dots are 
on the tab bar just to the right of the download arrow.



On 5/6/2016 4:24 PM, James Edward Lewis II wrote:
>
> The taskbar does look like Windows 7 with the Classic theme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1614#issuecomment-217549180>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dave47** [comment]
It does the same thing with the Default Theme.


ublock origin is 1.7.0


It is windows 7 and the theme is Blue Sharepoint.  The three dots just 
started showing up a week or two ago.  Prior to that it had always shown 
the count which is selected in options in Dashboard.  The three dots are 
on the tab bar just to the right of the download arrow.



On 5/6/2016 4:24 PM, James Edward Lewis II wrote:
>
> The taskbar does look like Windows 7 with the Classic theme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1614#issuecomment-217549180>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by gorhill** [comment]
The "three-dot" are not an icon which is part of uBO.

**Comment by dave47** [comment]
It turns out the three dots are part of last pass password manager, 
something to do with copyright infringement which caused them to have to 
change their icon.  Unfortunately they are putting the 3 dots not only 
on their own icon but over top of yours.

Sorry for the false alarm.

thanks for your help.  dave
On 5/7/2016 1:03 AM, Raymond Hill wrote:
>
> The "three-dot" are not an icon which is part of uBO.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gorhill/uBlock/issues/1614#issuecomment-217608045>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
