### ISSUE TITLE
[Firefox] Sync settings between desktop and mobile

### ISSUE THREAD

**Issue by 3licie** [gorhill/uBlock#1615]
> Add-on sync only works between similar Firefox installations. For example, if you install an add-on on desktop Firefox, it will only sync to other desktops, not to your Android device running Firefox. 

>Note: Add-on sync currently only works on desktop Firefox and Firefox for tablets. It doesn't work on Firefox for smaller mobile devices.
https://support.mozilla.org/en-US/kb/sync-your-add-ons-another-copy-firefox

Nevertheless, it would be very helpful if some workaround could be devised.

**Comment by n1trux** [comment]
Not sure if this should be the default because I like to have a lot more filtering lists on my desktop because my phone has less processing power.

Maybe rather task Mozilla with this? Workarounds are never sane solutions.

**Comment by kowith337** [comment]
I know it's very good if it possible to sync between Firefox desktop and Firefox mobile, but for temporary solution you can export settings and restore to your devices, go to dashboard and press "backup to file", save and transfer backup file to your device, then open uBlock dashboard on your device and press "Restore from file" pick a backup file that you tranfered and load it.
Note: all cache of third-party filter lists will be purged, you need to update their lists again, also uBlock experimental list will always unchecked, even you've checked to load this list before performing backup.
