### ISSUE TITLE
Not blocking popups originating from iframes

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1616]
### Describe the issue

uBO doesn't block popups when they originate from iframes.

### One or more specific URLs where the issue occurs

https://forums.lanik.us/viewtopic.php?f=62&t=30237
NSFW: `http://jizzman.com/video/31834/aidra-fox-in-unexpected-dinner-guest-brazzers-exxtra-brazzers.html`

### Steps for anyone to reproduce the issue

1. Block `1986a44b12e.com` and `25643e662a2.com` with dynamic filtering rules (will trigger the popup on `openload.co`).
1. Go to one of the links provided and click the play button of the `openload.co` frame.

Result: Popup is not blocked even though the filter `|http:$popup,third-party,domain=[...]|openload.co|[...]` exists in EasyList.

### Your settings

Default settings with updated filter lists.

- Browser/version: Chromium 51
- uBlock Origin version: 1.7.5b1

**Comment by gorhill** [comment]
> https://forums.lanik.us/viewtopic.php?f=62&t=30237

Is that the proper link? The case in there is well handled by uBO (with up-to-date lists).

**Comment by gorhill** [comment]
I don't see an issue here. Just add `jizzman.com` to the filter `|http:$popup,third-party,domain=[...]` and the popups will be blocked fine. If you really think there is an issue, make the case that ABP still block the popup without whitelisting the bait scripts.

**Comment by gorhill** [comment]
I checked and ABP also won't block the popups if blocking the bait scripts.

This is an interesting point though: should uBO (or ABP and whatever else blockers behave the same) take into account the context of the frame from which the `window.open()` call was made?

**Comment by gorhill** [comment]
I will decline.

This is handled by default with EasyList.

If one choose to work in medium mode -- a good idea on that sort of site<sup>[1]</sup>, the workaround is easy enough: toggle on the no-popups switch for the site.

***

[1] Suggested rules on top of medium mode, to unberak the site: `jizzman.com ajax.googleapis.com * noop`, `jizzman.com openload.co * noop`, `no-popups: jizzman.com true`.

**Comment by IDKwhattoputhere** [comment]
> should uBO (or ABP and whatever else blockers behave the same) take into account the context of the frame from which the window.open() call was made?

That was the idea I had.

> I will decline.

Alright. I actually remembered ABP handling it that way but haven't really used it in some time so maybe I just misremembered.

**Comment by gorhill** [comment]
I may change my mind, but for now I don't feel adding what seems lot of non-trivial code to deal with the case of an advanced user blocking on top of EasyList: I expect advanced users to find a way out of such issue with the available uBO tools. In the current case, the way out is trivial, the no-popups switch.

**Comment by IDKwhattoputhere** [comment]
I'm just confused why @ryanbr claims the popup is blocked for them.
> `|http:$popup,third-party,domain=24avarii.ru|allmyvideos.net|embed.videoweed.es|extreme-board.com|fastspics.net|filepost.com|filmovizija.com|go4up.com|gorillavid.in|imagebam.com|imagefruit.com|imageporter.com|img24.org|imgbox.com|imgmade.com|imgshots.com|imgsin.com|imgspice.com|load.to|mofunzone.com|openload.co|pic2pic.site|promptfile.com|putlocker.is|thevideo.me|twer.info|vid.ag|vidspot.net|watchcartoononline.com|xtshare.com|youwatch.org`

> This already blocks it for me, no reason to add any further filters.

I guess they're using Firefox where ABP takes the popup's context into account.

**Comment by gorhill** [comment]
What blocks the popup for me on Nightly is `||openload.co^*/_$popup`, not the other filter.

**Comment by IDKwhattoputhere** [comment]
There're other popups for me which get blocked by ABP:
![](https://cloud.githubusercontent.com/assets/16030872/15099302/07c7fd52-1552-11e6-97de-c513a5da28fc.png)

**Comment by ryanbr** [comment]
So is it more of a limitation of uBlock Origin?

**Comment by IDKwhattoputhere** [comment]
ABP on Chrome has the same limitation.

**Comment by ryanbr** [comment]
Seems to be blocked for me in Adblock Plus (Dev) for chrome, popups were closed quickly when I clicked on video

**Comment by IDKwhattoputhere** [comment]
Add to hosts file to block bait scripts:
`127.0.0.1 1986a44b12e.com`
`127.0.0.1 25643e662a2.com`
https://zippy.gfycat.com/ExcitableBigCoot.webm

**Comment by IDKwhattoputhere** [comment]
Add to hosts file to block bait scripts:
`127.0.0.1 1986a44b12e.com`
`127.0.0.1 25643e662a2.com`
https://a.pomf.cat/zgnikt.mp4
