### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by onovotny** [gorhill/uBlock#1617]
Starting in the latest Fast Ring builds, Edge in Windows 10 supports ad blocking extensions. Ad Block and Ad Block Plus have added Edge support:

http://www.windowscentral.com/adblock-and-adblock-plus-extensions-microsoft-edge-launched-insiders-windows-store

It would be great to have uBlock as an option for Edge as well.

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/search?q=edge&type=Issues&utf8=%E2%9C%93

**Comment by gorhill** [comment]
Duplicate of #1486.
