### ISSUE TITLE
WebRTC scan detect my IP even i set uBlock to prevent it (Firefox)

### ISSUE THREAD

**Issue by slrslr** [gorhill/uBlock#1618]
### Describe the issue

Hello,

Im using Firefox 46.0 and the "Prevent WebRTC from leaking local IP address" is ticked in my uBlock Origin v1.7.0
But when i open https://www.privacytools.io/webrtc.html it shows my real IP behind "Your public IP addresses:"

When i enable third party Firefox extension called Disable WebRTC 1.0.11 then my public IP is not found on mentioned webpage.

Thank You

### One or more specific URLs where the issue occurs

https://www.privacytools.io/webrtc.html

### Your settings

- Browser/version:  Firefox 46.0
- uBlock Origin version:  uBlock Origin v1.7.0

**Comment by gorhill** [comment]
> then my public IP is not found on mentioned webpage

The purpose of the setting _"Prevent WebRTC from leaking local IP address"_ is not to prevent your public IP from being visible (you will need a VPN, proxy, or Tor browser for this), it is to prevent leakage of local IP addresses, those IP addresses not visible.
