### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by UnrulyNatives** [gorhill/uBlock#1620]
I wish to add a blocked hosts list, with entries such as `127.0.0.1 skin-care.1.p2l.info`. 
I have read somewhere that it is possible in uBlock.

The temporary rules example patterns (in Dynamic filtering rule syntax) are different than the host entry. 

Thx

**Comment by gorhill** [comment]
You can import such list by importing it as an [external filter list](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web).
