### ISSUE TITLE
Facebook feed share widget not functioning

### ISSUE THREAD

**Issue by danqing** [gorhill/uBlock#1621]
### Describe the issue

uBlock prevents Facebook share widget from working correctly.

### One or more specific URLs where the issue occurs

Any sharable content on Facebook (see screenshot below).

### Screenshot in which the issue can be seen

![screen shot 2016-05-10 at 12 52 38 am](https://cloud.githubusercontent.com/assets/5134133/15139225/ab87454a-1649-11e6-812f-781cedf5dee4.png)

In Facebook feed, click on Share for anything that can be shared.

![screen shot 2016-05-10 at 12 52 44 am](https://cloud.githubusercontent.com/assets/5134133/15139247/c58da132-1649-11e6-8964-7b4e5ec2e03b.png)

Select "Send as Message". Then select a friend and press "Send". It won't function.

### Your settings

- Browser/version: Chrome 51.0.2704.29 beta (OS X 10.11.4)
- uBlock Origin version: 1.7.2

##### Your filter lists

Default + CHN + JPN.

**Comment by IDKwhattoputhere** [comment]
Does it work when uBlock Origin is disabled? What does [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) show? Have you tried disabling the CHN and JPN list and then testing again? Also which CHN list? There are three of them.

**Comment by danqing** [comment]
Yes it works when uBlock Origin is disabled, and the CHN/JPN lists don't seem to change anything.

![screen shot 2016-05-10 at 1 07 56 am](https://cloud.githubusercontent.com/assets/5134133/15139573/b0f731b4-164b-11e6-8094-ff661f92485b.png)

**Comment by IDKwhattoputhere** [comment]
Have you tried whitelisting the blocked image? Something like this filter should work:
`||pixel.facebook.com/share/share_now/counter/?event=$domain=facebook.com`

**Comment by gorhill** [comment]
If the suggested filter above fixes the issue, then this needs to be reported to EasyPrivacy maintainers.

**Comment by gorhill** [comment]
> the CHN/JPN lists don't seem to change anything

Did you force a reload of the page after you disabled these lists?

**Comment by gorhill** [comment]
Closing because no feedback on issue for months.
