### ISSUE TITLE
Whitelist by default

### ISSUE THREAD

**Issue by fewfre** [gorhill/uBlock#1623]
### Describe the issue
I would love a way to have all websites whitelisted by default, and then enable blocking selectively. For my needs most websites are fine, and I'd prefer to support them by default. I've been stuck on adblock (not plus) for awhile now because I really like this feature.

Part of the issue is that even if I found a valid "host name" to whitelist everything, it would just be removed once I enabled it on one site as per normal.

### Your settings
- Chrome V50.0.2661.94 on Mac
- uBlock Origin v1.7.2
- Just installed at work (default settings for everything)

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering
See "Turn off uBlock everywhere" and "Turn off uBlock everywhere except... (blacklist mode)".

**Comment by fewfre** [comment]
Perfect! A little convoluted, but that's to be expected for such a weird feature request. To get the effect I wanted, I also had to check "Disable cosmetic filtering" in settings.

**Comment by IDKwhattoputhere** [comment]
> I also had to check "Disable cosmetic filtering" in settings.

Good catch. Maybe that should be added to the wiki.
