### ISSUE TITLE
Is there anyone working on an Edge version yet?

### ISSUE THREAD

**Issue by Haplois** [gorhill/uBlock#1625]
Microsoft Edge recently started to support plugins & extensions, Do you plan to release an Edge version?

https://developer.microsoft.com/en-us/microsoft-edge/extensions/

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/search?o=desc&q=edge&s=created&type=Issues&utf8=%E2%9C%93

**Comment by Haplois** [comment]
Sorry for dup.
