### ISSUE TITLE
Blocking live chat software

### ISSUE THREAD

**Issue by alphanumerritt** [gorhill/uBlock#1626]
uBlock is disabling Live Chat functionality for BoldChat technology on our website.

Seen on www.dnb.com

![ublockproblem](https://cloud.githubusercontent.com/assets/10160072/15197912/bbb71016-1799-11e6-9342-603ee2efd0b8.jpg)
![howchatshoulddisplay](https://cloud.githubusercontent.com/assets/10160072/15197913/bce62d00-1799-11e6-88e3-3ef224726749.jpg)
![ublocklogofproblem](https://cloud.githubusercontent.com/assets/10160072/15197914/be14acba-1799-11e6-9f47-0426529a49f1.jpg)

1. Go to www.dnb.com. Best viewed on desktop.
2. It's possible this will only work during business hours. If the following steps don't work, please check back 8am - 5pm Monday - Friday EST.
3. If ublock is enabled, look at the floating footer where contact information is available. If you don't see a 'Start a live chat' link then it is being blocked.
4. Check log file and look for blocks on URLs with 'boldchat' in them.
5. Disable ublock and reload the page.
6. You should see the start a live chat link appear.
7. Note link is still clickable when blocked but the image display is not there.

I'm using Chrome v50.0.266blahblahblah

- uBlock Origin version: 1.7.2

Default filter lists

No custom filters

**Comment by gorhill** [comment]
Sorry about this, I created an exception filter to prevent the blocking.

(@pgl: FYI).

**Comment by lewisje** [comment]
Indeed, this is in Peter Lowe's Ad Servers, and it's also in the Malvertising Filter List by Disconnect (which isn't enabled by default IIRC); maybe `boldchat.com` is generally dangerous and the exception filter should be targeted at `dnb.com` specifically, perhaps with specific request types allowed.

**Comment by IDKwhattoputhere** [comment]
Pretty sure Disconnect imported Peter Lowe's list (huge overlap). [Boldchat isn't blacklisted a lot btw.](https://www.virustotal.com/url/d69736d7e69afa6b8bafdbbe3779fc99b0b3e12fd04fa6406ee5c1344b830142/analysis/) Couldn't find much info in regards to why they would be dangerous. Apparently they're part of a [division of LogMeIn](https://en.wikipedia.org/wiki/Xively) and of course [track users and share the data with 3rd-parties](https://secure.logmein.com/policies/privacy.aspx). Maybe that's why it was added and maybe the damage wasn't noticed.

**Comment by lewisje** [comment]
With that said, I now just used two [skip-parameters](http://pgl.yoyo.org/as/formats.php#skip) in my custom URL for Peter Lowe's Ad Servers, skipping both `adf.ly` and `boldchat.com`.

**Comment by alphanumerritt** [comment]
Thank you. I purged my cache and updated the filters and just confirmed
normal functionality of our site.

In case you revert to a whitelist for dnb.com, please know we have a few
other domains where we also use boldchat: hoovers.com and dandb.com. I'd
appreciate those whitelisted as well (again, if that's the route you take).

Regards.
Merritt Aho

Merritt Aho
801.413.6285
alphanumerritt@gmail.com
