### ISSUE TITLE
Donate using bitcoins

### ISSUE THREAD

**Issue by cig0** [gorhill/uBlock#163]
Dear all,
Are the project currently accepting bitcoins donations vi? If so please provide me an address to where to transfer some.
Thanks for this jewel among adware blockers.

**Comment by anewuser** [comment]
> Free. Open source. For users by users. No donations sought.

https://github.com/gorhill/uBlock/blob/master/README.md#about

If you want to help, report problems to the maintainers of the lists included by default (like Easylist) on their own forums. Please close this issue to mark it as solved.
