### ISSUE TITLE
uBlock prevents the display of "gallery" style articles on ZDNet

### ISSUE THREAD

**Issue by HubJ** [gorhill/uBlock#1631]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
ZDNet regularly has articles that are supposed to be displayed as "galleries." Like in a "flipbook," the user is supposed to move from page to page by clicking on arrows.Even with uBlock switched off for the site, the arrows do not cause the next page in the gallery to display

### One or more specific URLs where the issue occurs
http://www.zdnet.com/pictures/apples-ipad-air-first-look-in-pictures-gallery/  All "gallery" type pages on zdnet.com have the same problem.
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

Go to that URL, and click on an arrow. 

### Your settings
On the "Settings" tab, all check boxes are cleared except these four:
     Show the number of blocked requests on the icon
     Make use of context menu where appropriate
     Disable pre-fetching (to prevent any connection for blocked network requests) 
     Disable hyperlink auditing/beacon  

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 45.1.1 ESR
- uBlock Origin version: 

##### Your filter lists
Default
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
! 6/11/2015, 2:50:53 AM http://www.amazon.com/Actiontec-Wireless-N-Modem-Router-GT784WN/dp/B004NBZ98K
www.amazon.com###miniATFUDP

! 6/13/2015, 1:56:58 AM http://www.actiontec.com/262.html
www.actiontec.com###ddmenu > ul

! 6/13/2015, 1:57:38 AM http://www.actiontec.com/262.html
www.actiontec.com###wrap > header > .navbar-fixed-top.navbar > .navbar-inner > .container

! 6/13/2015, 1:57:51 AM http://www.actiontec.com/262.html
www.actiontec.com###wrap > header > .navbar-fixed-top.navbar > .navbar-inner

! 6/13/2015, 12:13:31 PM http://new.office-watch.com/2013/adding-a-background-image-to-a-word-page/
new.office-watch.com###main-nav

! 6/13/2015, 12:13:57 PM http://new.office-watch.com/2013/adding-a-background-image-to-a-word-page/
new.office-watch.com###announcement_bar_slider

! 6/13/2015, 9:39:52 PM http://www.stumbleupon.com/su/1zurOR/1G_5nO5B!:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
www.stumbleupon.com###progress-bar-view-container > .progress-content

! 6/13/2015, 9:40:11 PM http://www.stumbleupon.com/su/1zurOR/1G_5nO5B!:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
www.stumbleupon.com###toolbar-container > .rendered.container.toolbar > .inner-container

! 6/13/2015, 9:40:28 PM http://www.stumbleupon.com/su/1zurOR/1G_5nO5B!:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
www.stumbleupon.com###progress-bar-view-container

! 6/13/2015, 9:40:40 PM http://www.stumbleupon.com/su/1zurOR/1G_5nO5B!:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
www.stumbleupon.com###toolbar-container > .rendered.container.toolbar

! 6/13/2015, 9:41:07 PM http://www.stumbleupon.com/su/1zurOR/1G_5nO5B!:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
www.stumbleupon.com##body > div:nth-of-type(1)

! 6/13/2015, 9:41:44 PM http://www.stumbleupon.com/su/1zurOR/1G_5nO5B!:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
||lifehacker.com/5412886/61-free-apps-were-most-thankful-for

! 6/13/2015, 9:42:27 PM http://www.stumbleupon.com/su/1zurOR/VjyQUfe@:88hRB10H/lifehacker.com/5412886/61-free-apps-were-most-thankful-for
||lifehacker.com/5412886/61-free-apps-were-most-thankful-for

! 6/16/2015, 3:09:32 PM https://www.raymond.cc/blog/move-windows-xp-hard-drive-or-change-motherboard-without-getting-blue-screen-of-death/
www.raymond.cc###pull[href="#"]

! 6/18/2015, 7:58:08 AM http://chmeditor.com/
chmeditor.com###jivo_chat_iframe

! 6/24/2015, 11:39:42 PM http://patient.info/health/ercp
patient.info##.is-open.js-gizmo.js-peekaboo.peekaboo

! 6/30/2015, 1:29:54 AM http://www.mysongbook.com/
www.mysongbook.com##.fancybox-opened.fancybox-default.fancybox-wrap > .fancybox-outer > .fancybox-inner

! 6/30/2015, 5:29:25 AM http://www.hongkiat.com/blog/gmail-security-tips/
www.hongkiat.com##.et_social_fadein.et_social_mobile > .et_social_heading

! 7/1/2015, 8:31:44 PM http://translate.google.com/translate?hl=en&sl=ru&tl=en&u=http://www.comss.info/page.php%3Fal%3DSoft_Organizer_free&sandbox=0&usg=ALkJrhiUKq78dzuwQ5TnYPRTMR9WiVGReg
translate.google.com###gt-tl

! 7/1/2015, 9:39:49 PM http://www.economist.com/news/business-and-finance/21614181-who-lies-behind-latest-cyber-attacks-jp-morgan-chase-hacking-banks
||www.economist.com/ec-overlay/init/emptyframe

! 7/1/2015, 9:40:14 PM http://www.economist.com/news/business-and-finance/21614181-who-lies-behind-latest-cyber-attacks-jp-morgan-chase-hacking-banks
www.economist.com###simplemodal-container > .simplemodal-wrap

! 7/9/2015, 10:59:38 AM http://whois.domaintools.com/
whois.domaintools.com###spiders

! 7/11/2015, 5:12:36 PM http://www.downloadcrew.com/article/33508-gimagereader
www.downloadcrew.com###outerImageContainer

! 7/18/2015, 2:59:55 PM http://dothisbest.com/how-to/fix-upgrade-windows-8-windows-8-1-fail-error/
dothisbest.com##.site-container > .site-header > .wrap

! 7/30/2015, 12:09:53 PM https://www.thurrott.com/windows/windows-10/4881/windows-10-and-automatic-updates
www.thurrott.com###menu-main-menu-1

! 7/30/2015, 12:12:10 PM https://www.thurrott.com/windows/windows-10/4881/windows-10-and-automatic-updates
www.thurrott.com###menu-site-selector-1

! 7/30/2015, 12:12:30 PM https://www.thurrott.com/windows/windows-10/4881/windows-10-and-automatic-updates
www.thurrott.com###navWrapper-sticky-wrapper

! 8/1/2015, 10:43:48 PM https://www.zoho.com/general/blog/provide-remote-assistance-with-zoho-meeting.html
www.zoho.com###coltab > li > .btn

! 8/4/2015, 5:24:19 AM http://www.semdrive.com/category/seo/#
www.semdrive.com###menu-item-23 > a[href="http://www.semdrive.com/solutions/"]

! 8/4/2015, 5:24:41 AM http://www.semdrive.com/category/seo/#
www.semdrive.com###menu-item-30 > a[href="http://www.semdrive.com/enterprise/"]

! 8/4/2015, 5:26:05 AM http://www.semdrive.com/category/seo/#
www.semdrive.com###primary

! 8/10/2015, 10:12:02 PM https://www.ablebits.com/office-addins-blog/2014/02/20/create-email-templates-outlook/
www.ablebits.com###bn-maximize[href="#"]

! 8/11/2015, 7:37:14 AM http://lifehacker.com/another-day-another-hack-what-security-news-should-yo-1723127575
lifehacker.com###sharingfooter

! 8/12/2015, 12:14:04 AM https://www.ibabbleon.com/apple-ios-localization-term-glossary.html
www.ibabbleon.com###header > .navbar-fixed-top.navbar > .navbar-inner > .container

! 8/12/2015, 2:10:51 AM https://www.safaribooksonline.com/library/view/professional-iphone-and/9780470636176/ch04.html
www.safaribooksonline.com###js-subscribe-nag

! 8/12/2015, 2:23:14 AM http://iosguides.net/how-to-copy-cut-and-paste-on-ipad/
iosguides.net###menu-main-menu-1

! 8/12/2015, 10:34:55 PM http://techcrunch.com/2012/09/19/ios-6-is-now-available-heres-what-features-your-idevice-gets/
techcrunch.com##.fluid > .article-extra > .l-three-col.lc > .section.recirc-up-next.l-sidebar-2 > .popped.section.toaster > .toaster-container > .toaster-content

! 8/12/2015, 10:35:52 PM http://techcrunch.com/2012/09/19/ios-6-is-now-available-heres-what-features-your-idevice-gets/
techcrunch.com##.header-fixed.header-context-news.cf.header-fixed-mobile.header > .nav-bar > .lc > .lc > .cf.header-logo-bar > .nav-contextual > .nav > .nav-news > .nav-parent[href="/"]

! 8/17/2015, 1:33:59 AM http://www.nfsesq.com/resources/timelimits/
||www.nfsesq.com/wp-content/uploads/2013/07/newsletter-popup.png

! 8/17/2015, 1:34:27 AM http://www.nfsesq.com/resources/timelimits/
www.nfsesq.com###message

! 8/21/2015, 6:31:02 AM https://www.creditkarma.com/shop/creditcards/secured_cards
www.creditkarma.com###cc-compare-ribbon-tray

! 8/21/2015, 6:31:26 AM https://www.creditkarma.com/shop/creditcards/secured_cards
www.creditkarma.com###cc-compare-ribbon-tab

! 8/30/2015, 7:14:59 PM http://www.microsoftvirtualacademy.com/ebooks
www.microsoftvirtualacademy.com###aspnetForm > .footer > .footer-content

! 8/31/2015, 11:14:34 AM http://www.nolo.com/legal-encyclopedia/can-i-keep-my-disability-payments-chapter-7-bankruptcy.html
||www.gstatic.com/trustedstores/images/badges/ts_badge_v2.png

! 9/1/2015, 2:30:42 PM https://www.crunchbase.com/organization/square
www.crunchbase.com###anchor-title

! 9/1/2015, 2:31:09 PM https://www.crunchbase.com/organization/square
www.crunchbase.com###anchor-filter > .container.action-block

! 9/1/2015, 2:31:32 PM https://www.crunchbase.com/organization/square
www.crunchbase.com##.mobile-sticky.entity.container.page > .entities.container.row.main-content > .sticky.first-column.large-8.small-8.columns > .timeline-navigation.navigation > .sticky.base > .title-border-bg

! 9/1/2015, 2:31:53 PM https://www.crunchbase.com/organization/square
www.crunchbase.com##.mobile-sticky.entity.container.page > .main-header > .container.row > .large-12.small-12.columns

! 9/1/2015, 2:32:11 PM https://www.crunchbase.com/organization/square
www.crunchbase.com###anchor-filter

! 9/1/2015, 2:32:28 PM https://www.crunchbase.com/organization/square
www.crunchbase.com##.mobile-sticky.entity.container.page > .main-header

! 9/30/2015, 2:45:25 PM http://www.rabbitsreviews.com/s25827/Shadow-Lane.html
www.rabbitsreviews.com###join > .btn-xxl.btn-green.join-btn.btn[href^="http://www.rabbitsreviews.com/OpenSite.aspx"]

! 10/10/2015, 11:27:13 AM https://blog.zimperium.com/zimperium-zlabs-is-raising-the-volume-new-vulnerability-processing-mp3mp4-media/
blog.zimperium.com###menu-menu-1-navigation

! 10/10/2015, 11:27:52 AM https://blog.zimperium.com/zimperium-zlabs-is-raising-the-volume-new-vulnerability-processing-mp3mp4-media/
blog.zimperium.com###nav-main > .container.navbar-default.navbar > .navbar-ex1-collapse.navbar-collapse.collapse

! 10/17/2015, 5:49:14 PM http://www.experts-exchange.com/articles/17495/How-to-save-the-names-and-URLs-of-open-Firefox-tabs-in-a-plain-text-file.html
www.experts-exchange.com###col1

! 10/25/2015, 5:10:11 PM http://www.repairclinic.com/Shop-For-Parts/a4b101d507242/Model-AT17EM6W-Admiral-Refrigerator-Parts
||www.gstatic.com/trustedstores/images/badges/ts_badge_v4.png

! 11/6/2015, 7:11:29 PM http://sigalongoogle.soup.io/tag/Google%20Translate?newer=1&since=322591309
sigalongoogle.soup.io###admin-message

! 11/10/2015, 1:03:32 AM http://www.lifehack.org/articles/technology/how-to-continue-reading-the-new-york-times-online-for-free.html
www.lifehack.org###single > .popup.slidein.popular-header

! 11/10/2015, 1:05:31 AM http://5.hidemyass.com/ip-1/encoded/Oi8vd3d3Lm55dGltZXMuY29tLw%3D%3D
5.hidemyass.com###hma-survey-button

! 11/14/2015, 4:14:04 AM http://goodereader.com/blog/electronic-readers/overdrive-media-console-now-available-for-windows-8
goodereader.com###menu-template-top

! 11/14/2015, 7:31:09 AM https://blogs.windows.com/windowsexperience/2013/11/12/nook-gets-updated-for-windows-8-1/
blogs.windows.com###bottom-bar > .container.main-nav

! 11/26/2015, 3:53:15 PM http://deals.kinja.com/the-best-black-friday-deals-1742820364?rev=1448558328344#_ga=1.98387039.1326673221.1440044029
||i.kinja-img.com/gawker-media/image/upload/s--CmR1AzUP--/c_fit,f_auto,fl_progressive,q_80,w_636/1534637960131804198.gif

! 11/29/2015, 5:47:33 AM http://www.staples.com/sheaffer+fountain+pen/directory_sheaffer+fountain+pen?fids=facet%3A2997887173279&sr=true&sby=&min=&max=
www.staples.com###oo_tab > div:nth-of-type(1)

! 11/30/2015, 9:07:25 PM http://www.techno360.in/multcloud/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+Techno360+%28Techno360%29
www.techno360.in###dialog

! 11/30/2015, 9:07:44 PM http://www.techno360.in/multcloud/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+Techno360+%28Techno360%29
www.techno360.in##.ui-resizable.ui-front.ui-corner-all.ui-widget-content.ui-widget.ui-dialog > .ui-helper-clearfix.ui-corner-all.ui-widget-header.ui-dialog-titlebar

! 11/30/2015, 11:18:02 PM http://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http://www.pcwelt.de/specials/xmas/xmas-vollversions-kalender%23null&sandbox=0&usg=ALkJrhgUnJ6d3NZ1QAnAVE0Sf7evuYDCKQ
||translate.googleusercontent.com/translate_p?hl=en&sandbox=0&sl=auto&tl=en&u=http://www.pcwelt.de/specials/xmas/xmas-vollversions-kalender%23null&depth=1&rurl=translate.google.com&usg=ALkJrhgAAAAAVl1KqNBQ084Zzf60BbNH5i9FNiXg5Jkl

! 12/4/2015, 11:08:40 PM http://www.retailmenot.com/view/amazon.com
www.retailmenot.com###quick-feedback > .quick-feedback-questions > .js-quick-feedback-question-1.active.quick-feedback-question

! 12/4/2015, 11:08:54 PM http://www.retailmenot.com/view/amazon.com
www.retailmenot.com###quick-feedback

! 12/6/2015, 11:14:38 PM http://www.staples.com/windows+7+usb+kvm+switch/directory_windows+7+usb+kvm+switch
www.staples.com###oo_tab

! 12/7/2015, 2:18:05 AM http://www.erfolgreich-ecommerce.de/adventsaktion/?ref=cj
www.erfolgreich-ecommerce.de###sticky

! 12/8/2015, 3:12:45 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com###wpfront-notification-bar

! 12/8/2015, 3:13:14 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com###sticky-bar > .row > .col-md-12

! 12/8/2015, 3:13:29 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com###sticky-bar

! 12/8/2015, 6:56:37 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com##.after-header > .category-utilities.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-3189.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-next.popnav > .popnav-link[href="http://www.filecritic.com/skype-desktop-app-for-windows-10-may-not-launch-anytime-soon/"]

! 12/8/2015, 6:57:02 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com##.after-header > .category-utilities.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-3189.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-next.popnav

! 12/8/2015, 6:57:27 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com##.after-header > .category-utilities.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-3189.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-previous.popnav > .popnav-link[href="http://www.filecritic.com/acronis-true-image-2015-review/"]

! 12/8/2015, 6:57:45 AM http://www.filecritic.com/pdf-impress-2014-review/
www.filecritic.com##.after-header > .category-utilities.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-3189.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-previous.popnav

! 12/21/2015, 4:24:56 AM http://www.lifehacker.com.au/2015/10/proxmate-extension-abandons-free-model-moves-to-subscription/
www.lifehacker.com.au###wrap > .ad-block-message

! 12/21/2015, 3:19:00 PM http://community.spiceworks.com/topic/396103-cryptolocker-prevention-kit-updated
community.spiceworks.com##.in.modal-backdrop

! 12/23/2015, 2:08:14 PM http://www.softorbits.com/photo-stamp-remover/demo.html
www.softorbits.com###sticker

! 12/25/2015, 8:55:55 PM http://giveaway.downloadcrew.com/?act=home
giveaway.downloadcrew.com###noSupportPopup > .content

! 12/25/2015, 8:56:07 PM http://giveaway.downloadcrew.com/?act=home
giveaway.downloadcrew.com###noSupportPopup

! 12/28/2015, 2:45:38 AM http://www.softwarecrew.com/2014/06/quickly-transcribe-audio-or-video-files-with-easytranscript/
www.softwarecrew.com##.ginger_banner-wrapper > .ginger_container--open.ginger_container.dark.bottom.ginger_banner > .ginger_message

! 12/28/2015, 2:45:50 AM http://www.softwarecrew.com/2014/06/quickly-transcribe-audio-or-video-files-with-easytranscript/
www.softwarecrew.com##.ginger_banner-wrapper > .ginger_container--open.ginger_container.dark.bottom.ginger_banner

! 12/30/2015, 9:36:26 AM https://www.sling.com/signup/billing_info?var=a
www.sling.com##header-directive > .ng-scope.navbar-fixed-top.navbar > .container-wrap > .container

! 12/30/2015, 9:36:40 AM https://www.sling.com/signup/billing_info?var=a
www.sling.com##header-directive > .ng-scope.navbar-fixed-top.navbar

! 1/14/2016, 1:35:42 AM http://www.thehonestkitchen.com/articles/what-is-human-grade-pet-food-really/
www.thehonestkitchen.com###back-to-top-button[href="#"]

! 1/21/2016, 12:01:07 AM http://2.hidemyass.com/ip-3/encoded/Oi8vd3d3LnRvbXNoYXJkd2FyZS5jb20vYW5zd2Vycy9pZC0xODQwMTc3L2Nsb25lLWhkZC1iYWQtc2VjdG9ycy5odG1s&f=norefer
2.hidemyass.com###hmaform

! 1/21/2016, 12:01:30 AM http://2.hidemyass.com/ip-3/encoded/Oi8vd3d3LnRvbXNoYXJkd2FyZS5jb20vYW5zd2Vycy9pZC0xODQwMTc3L2Nsb25lLWhkZC1iYWQtc2VjdG9ycy5odG1s&f=norefer
2.hidemyass.com###hmaurlbar2

! 1/28/2016, 10:00:33 PM https://blogs.office.com/2015/05/04/office-2016-public-preview-now-available/
blogs.office.com###site-navigation > .main-navigation-top-level > .filter-parent:nth-of-type(2)

! 1/28/2016, 10:02:35 PM https://blogs.office.com/2015/05/04/office-2016-public-preview-now-available/
blogs.office.com###site-navigation > .main-navigation-top-level

! 1/28/2016, 10:02:46 PM https://blogs.office.com/2015/05/04/office-2016-public-preview-now-available/
blogs.office.com###site-navigation

! 1/28/2016, 10:03:10 PM https://blogs.office.com/2015/05/04/office-2016-public-preview-now-available/
blogs.office.com###masthead > .header-dropdown

! 2/5/2016, 9:16:56 AM https://www.grc.com/sr/smart-studymode.htm
||www.grc.com/sr/smart-studymode.png

! 2/12/2016, 6:25:28 PM http://www.webmd.com/fibromyalgia/fibromyalgia-pain-10/fibromyalgia-creating-treatment-plan
||tpc.googlesyndication.com/safeframe/1-0-2/html/container.html

! 2/12/2016, 6:25:49 PM http://www.webmd.com/fibromyalgia/fibromyalgia-pain-10/fibromyalgia-creating-treatment-plan
www.webmd.com###google_ads_iframe_\/4312434\/consumer\/webmd_0__container__

! 2/12/2016, 6:27:24 PM http://www.webmd.com/fibromyalgia/fibromyalgia-pain-10/fibromyalgia-creating-treatment-plan
www.webmd.com###non_sp_ft_rdr

! 2/12/2016, 6:27:43 PM http://www.webmd.com/fibromyalgia/fibromyalgia-pain-10/fibromyalgia-creating-treatment-plan
www.webmd.com###ContentPane2 > .scrollbar-stuck.masthead-scrollbar

! 2/22/2016, 1:26:11 AM http://www.filecritic.com/hard-disk-sentinel-pro-review/
www.filecritic.com##.after-header > .category-utilities.category-reviews.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-1231.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .moved.single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-next.popnav > .popnav-link[href="http://www.filecritic.com/blue-ridge-networks-appguard-review/"]

! 2/22/2016, 1:26:28 AM http://www.filecritic.com/hard-disk-sentinel-pro-review/
www.filecritic.com##.after-header > .category-utilities.category-reviews.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-1231.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .moved.single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-next.popnav

! 2/22/2016, 1:26:54 AM http://www.filecritic.com/hard-disk-sentinel-pro-review/
www.filecritic.com##.after-header > .category-utilities.category-reviews.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-1231.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .moved.single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-previous.popnav > .popnav-link[href="http://www.filecritic.com/passware-kit-standard-2015-review/"]

! 2/22/2016, 1:27:05 AM http://www.filecritic.com/hard-disk-sentinel-pro-review/
www.filecritic.com##.after-header > .category-utilities.category-reviews.hentry.has-post-thumbnail.format-standard.status-publish.type-post.post.post-1231.single-wrapper.no-padding.container-fluid > .row > .col-md-12 > .container-inner > .row > .moved.single-post-selector.col-md-9 > .category-.shadowed.single-page > .shown.add-active.popnav-previous.popnav

! 3/8/2016, 3:19:07 AM https://www.google.com/?gws_rd=ssl
www.google.com###hplogop

! 3/12/2016, 11:38:07 PM http://stealthpuppy.com/prepare-mozilla-firefox-for-enterprise-deployment-and-virtualization/
stealthpuppy.com##.wrapper-site > .invert.header-left.header-sticky.header-site > .header-block.container

! 3/15/2016, 8:11:14 AM http://www.nuance.com/for-healthcare/index.htm
www.nuance.com###themeController > .healthcare.flyout-wrapper > .flyout-content

! 3/19/2016, 7:57:57 PM https://mirillis.com/en/products/action.html
mirillis.com##body > div:nth-of-type(9)

! 3/21/2016, 8:45:00 PM https://www.pinterest.com/pin/154318724707993244/
www.pinterest.com##.showingCloseup.unauth.full.Module.AppBase.App > .appContent > .mainContainer > .Nags.Module > .quarterScreenBanner.wallStep.UnauthBanner.Module.InlineSignup > .mainContent.gridWidth.centeredWithinWrapper > .textAndButtons

! 3/21/2016, 8:45:08 PM https://www.pinterest.com/pin/154318724707993244/
www.pinterest.com##.showingCloseup.unauth.full.Module.AppBase.App > .appContent > .mainContainer > .Nags.Module > .quarterScreenBanner.wallStep.UnauthBanner.Module.InlineSignup

! 3/25/2016, 10:19:02 PM http://www.giveaway-club.com/
www.giveaway-club.com###scrollto[href="#today-recommended"]

! 4/2/2016, 3:37:43 PM http://www.ncaa.com/march-madness-live/game/601
www.ncaa.com###mml-falcon > .page-container > .player-container-wrapper

! 4/18/2016, 4:22:23 AM http://www.downloadcrew.com/article/33904-inno_setup_unpacker
www.downloadcrew.com###footer

! 4/18/2016, 4:23:39 AM http://www.downloadcrew.com/article/31596-msi_unpacker
www.downloadcrew.com###footer

! 4/22/2016, 3:21:40 PM https://www.opera.com/blogs/desktop/2016/04/free-vpn-integrated-opera-for-windows-mac/
||www.opera.com/en/downloadassets/sticky-bar

! 4/23/2016, 12:35:42 AM https://www.raymond.cc/blog/offline-windows-update/view-all/
www.raymond.cc###related_posts-3

! 4/23/2016, 7:05:16 PM http://www.watermark-software.com/summer/
www.watermark-software.com###shareside

! 4/26/2016, 7:01:47 AM http://liliputing.com/2011/06/tablet-drop-test-video.html
liliputing.com##.site-container > .site-header > .wrap

! 4/30/2016, 12:00:38 PM http://www.idgconnect.com/blog-abstract/15818/dropbox-trades-blows-box-fight
www.idgconnect.com###wrapper > .dialog-block

! 5/6/2016, 4:03:16 PM http://www.sperlongadata.com/
www.sperlongadata.com###services > .accordion > li:nth-of-type(1) > h3

! 5/6/2016, 4:03:32 PM http://www.sperlongadata.com/
www.sperlongadata.com###services > .container

! 5/6/2016, 4:03:48 PM http://www.sperlongadata.com/
www.sperlongadata.com###header

! 5/6/2016, 5:55:31 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/Homepage%20Family%20Cropped%201600%201188.jpg

! 5/6/2016, 5:55:44 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/garlandbanner_notmoving_re3.jpg

! 5/6/2016, 5:56:14 PM http://hcidla.lacity.org/
hcidla.lacity.org###block-block-15 > .content > .community-everyone > .community-everyone-container.container

! 5/6/2016, 5:56:51 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/Homepage%20structure%20cropped%201344%20x%20537.jpg

! 5/6/2016, 5:57:05 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/FSC%20ESL%20and%20Computer%20Class%201312%20x%20524.jpg

! 5/6/2016, 5:57:24 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/LA%20city%20landscape%20cropped%201344%20x%20537.jpg

! 5/6/2016, 5:57:39 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/hcidla-news-2_0.png

! 5/6/2016, 5:58:01 PM http://hcidla.lacity.org/
||hcidla.lacity.org/sites/default/files/hcidla-news-1_1.png

**Comment by gorhill** [comment]
Works fine with default settings. Filter issues, I will let investigate yoruself.

**Comment by HubJ** [comment]
I just reset uBlock to default settings, and returned to the link provided.

 

I still got no response to the arrows, even with uBlock disabled for that page.

 

Do you have any further troubleshooting suggestions?

**Comment by gwarser** [comment]
Static filter `||tags.tiqcdn.com^` found in:

    uBlock filters – Experimental

and after disabling Experimental filters:

Static filter `||tags.tiqcdn.com^$third-party` found in:

    Fanboy’s Enhanced Tracking List

This works:

! 5/14/2016, 6:50:18 PM zdnet.com
`@@||tags.tiqcdn.com/utag/cbsi/zdnetglobalsite/prod/utag.js$script,domain=www.zdnet.com`

**Comment by HubJ** [comment]
Thanks for responding. I’m sorry to say, however, that, unless I’m misunderstanding you, your comments don’t pertain to the situation at this point. Here’s why.

 

It seems that you’re telling me that a static filter is blocking the action of the arrow keys. However, “Experimental Filters” is disabled in the default installation of uBlock—and my last message reported that I was having the same problem when using the default settings as I had previously. 

 

HOWEVER, I HAVE DISCOVERED SOMETHING BIG – about this small problem.

 

uBlock is not the cause.

 

I restarted FF in safe mode, with all add-ons disabled—and the page works.

I then opened a clean install of FF with no add-ons installed (but not in safe mode)—and the page works.

Therefore, it is some other add-on which is causing the problem. 

 

I’m now giving up, because I can’t see anything that I have installed that is supposed to operate at the page element level to make changes to what is rendered.

 

I’ll just have to open those pages in another browser if necessary.

 

Thanks for your effort.

 

Jeff

**Comment by vlaszlo** [comment]
Do you have [Tracking Protection](https://support.mozilla.org/en-US/kb/tracking-protection-firefox) enabled in Firefox, by any chance? That also makes those galleries not work for me.

**Comment by HubJ** [comment]
Hope springs eternal!

 

My heart skipped a beat when I saw your words, because I do have Tracking Protection enabled.

 

I quickly unchecked that option in the Firefox Options/Privacy tab, restarted the browser, and – there was no change.

 

Still, it was worth having something to get excited about.

 

Thanks for responding.
