### ISSUE TITLE
Clicking some links causes new tab to open, then immediately close

### ISSUE THREAD

**Issue by JetCrusherTorpedo** [gorhill/uBlock#1632]
Occurs when clicking links on a Twitter feed and links in Discord web chat. New tab will open, but immediately closes. When uBlock is disabled, tab opens fine.

- uBlock 1.7.2
- Default filter lists
- Chrome 50

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

> **ALWAYS INCLUDE A SPECIFIC URL WHERE THE ISSUE OCCURS**

**Comment by JetCrusherTorpedo** [comment]
@IDKwhattoputhere I cannot provide a URL to my private twitter feed or my Discord channels. Any link that someone posts is affected.

**Comment by IDKwhattoputhere** [comment]
Then you need to investigate yourself. Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) and see what blocks those tabs.

**Comment by JetCrusherTorpedo** [comment]
Found it! An EasyList rule is blocking _roblox.com_ links from being opened from another domain.

Here is the rule:
`||roblox.com^$third-party,popup`

**Comment by IDKwhattoputhere** [comment]
This exception filter should work then: `@@||roblox.com^$popup`
Best to also report here so they can fix it: https://forums.lanik.us/viewforum.php?f=64
https://forums.lanik.us/rules#participation

**Comment by JetCrusherTorpedo** [comment]
OK, will do. Thanks for your help.
