### ISSUE TITLE
YouTube whitelisting script is being unnecessarily run on channel pages

### ISSUE THREAD

**Issue by rcmero** [gorhill/uBlock#1633]
When this happens, the header displays "An error occurred during validation.", but the page still works well otherwise, as far as I can tell.

This is rather easy to fix, actually. You just need to add these to the script's header:
```
// @exclude      https://*.youtube.com/user/*
// @exclude      https://*.youtube.com/channel/*
```

**Comment by anewuser** [comment]
This is the repository of uBlock Origin. That script isn't included by default.

Please click on "Start a new discussion on this script." on this page instead to report problems with the user script:  https://greasyfork.org/scripts/13226-youtube-whitelist-channels-in-ublock-origin/feedback

**Comment by TPS** [comment]
@anewuser: @gorhill links https://github.com/gorhill/uBlock/issues _on_ that site ___&___ _in_ the script itself as the official support link, so I suppose @rcmero is justified in opening this issue.

**Comment by anewuser** [comment]
It's interesting to see how users are using the new "reaction buttons" to disrupt Github communities and like their own posts.

![untitled-1](https://cloud.githubusercontent.com/assets/6733770/15271959/fe1e2b14-1a38-11e6-8d72-58a53e742931.png)

**Comment by rcmero** [comment]
I was going to post this on Greasyfork instead, but the author is very much
active here.
Em 15/05/2016 02:00, "anewuser" <notifications@github.com> escreveu:

**Comment by gorhill** [comment]
Just tested and I see the user script does not work very well anyways.

Youtube does not make it easy to whitelist specific users/channels. I am just going to give up on trying to maintain such user script -- I will let somebody else take the duty.

I will revise the wiki accordingly.
