### ISSUE TITLE
Disappears uBlock button

### ISSUE THREAD

**Issue by Kristinita** [gorhill/uBlock#1634]
Windows XP SP3
Pale Moon 25.5.0.1 (x86)
uBlock 0.9.5.0.1-let-fixed

When I installed uBlock, in my navigation bar appeared uBlock icon:

![uBlock 1](https://i.gyazo.com/abad0d04273060e5d90f3a410e5d357f.png)

But when I reboot the browser, uBlock disappears.

![uBlock 2](https://i.gyazo.com/99776734c3d4face94a8f7952b7275da.png)

I have to manually return the button. 

What should I do to uBlock button has always been in my navigation bar?

Thanks.

**Comment by IDKwhattoputhere** [comment]
Are you using uBlock instead of uBlock Origin? uBlock's repo is over here: https://github.com/chrisaljoudi/uBlock
It's not being worked on anymore though. Just like all other software you're using (old Pale Moon version and XP).

**Comment by TPS** [comment]
Not to negate what @IDKwhattoputhere is saying, but as an observation: it's amazing that #833 manifests _that_ many versions back all the way through the most current.

**Comment by gorhill** [comment]
You are using uBlock, not uBlock Origin.

**Comment by lewisje** [comment]
Have you considered switching to the Atom-optimized build of Pale Moon? Even if your system doesn't have an Atom CPU, it should still work, and it's the only Pale Moon build for Windows XP that is still being updated.

**Comment by Hrxn** [comment]
I don't know, but still using Windows XP, that's somehow akin to committing technological suicide.
