### ISSUE TITLE
[Third-Party] The hardest-working anti-adblocking webmaster I've ever seen

### ISSUE THREAD

**Issue by lewisje** [gorhill/uBlock#1636]
The webmaster of 3dsthem.es is engaged in an extended cat-and-mouse game with the maintainers of Reek's Anti-Adblock Killer UserScript; look at this issue thread to see how deep the rabbit-hole goes: https://github.com/reek/anti-adblock-killer/issues/1433

I just thought I'd make this Issue to spread the word, just as I posted in both the Adblock Plus and EasyList forums.

**Comment by usagirei** [comment]
It's our machines and we should have control of what gets executed or not on them.

I'm not standing idle while a 15 year old tries to force me to expose my computer to malware risk by forcing me to not use my adblocker.

But truth be told, I made my userscript mostly for the salt.

**Comment by lewisje** [comment]
FrankerZ would be proud.
