### ISSUE TITLE
Ublock Origin:  Intermittently Fails to Load on Firefox

### ISSUE THREAD

**Issue by informationeagle** [gorhill/uBlock#1638]
Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
### Describe the issue

Hello Folks,
I've been using uBlock Origin for a few months now and finding it works well for me.  However, it quite often fails to load when I startup Firefox.  Closing and restarting FF usually clears up the problem right away.  Today I did a fresh install of firefox with no extensions on a friends computer (both of us using Windows Home Premium) and found the same problem.  Has anyone encountered this and found a solutions?

Thank you.
### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
### Steps for anyone to reproduce the issue
1. Be as detailed as possible:
2. Because we are not looking over your shoulder and
3. Keep in mind: Nobody can read your mind.
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
- Browser/version: 
- uBlock Origin version: 
##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Since I have never had this issue, you will have to investigate to find the source of the issue. Use the tools the browser put at your disposal: browser console, etc.

**Comment by n1trux** [comment]
you copied the template but didn't include any actual information (version numbers, screenshots, error console – you can get the latter with `Ctrl`+`Shift`+`J`). We can't help you this way.

With "Windows Home Premium" I suppose you mean Windows **7** Home Premium? Is the latest service pack installed?

**Comment by Imold** [comment]
I can confirm this bug. Sometimes when firefox loads Ublock Origin will seemingly be disabled however restarting firefox is unnecessary disabling and reenabling Ublock Origin will fix it.

If it helps here's the info I get from about:support
Application Basics
------------------

Name: Firefox
Version: 47.0
Build ID: 20160604131506
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
OS: Windows_NT 6.1 x86
Multiprocess Windows: 0/2 (Disabled)
Safe Mode: false

Crash Reports for the Last 3 Days
---------------------------------

All Crash Reports

Extensions
----------

Name: 2 Pane Bookmarks
Version: 1.0.2016020701
Enabled: true
ID: {FD61379B-066A-4afc-89DE-89FB24D907C2}

Name: Add Bookmark Here ²
Version: 41.0.20160423
Enabled: true
ID: abhere2@moztw.org

Name: Add to Search Bar
Version: 2.9
Enabled: true
ID: add-to-searchbox@maltekraus.de

Name: Add-ons Manager Context Menu
Version: 0.4.2.1-signed.1-signed
Enabled: true
ID: amcontextmenu@loucypher

Name: Addons Quick Search
Version: 0.1.2
Enabled: true
ID: addonsQuickSearch@infocatcher

Name: Advanced Locationbar
Version: 1.0.3
Enabled: true
ID: advancedlocationbar@veg.by

Name: AutoAuth
Version: 2.1.1-signed.1-signed
Enabled: true
ID: autoauth@efinke.com

Name: Beyond Australis
Version: 1.4.6
Enabled: true
ID: thefoxonlybetter@quicksaver

Name: Classic Theme Restorer
Version: 1.5.3
Enabled: true
ID: ClassicThemeRestorer@ArisT2Noia4dev

Name: Clean Links
Version: 2.7.1-signed.1-signed
Enabled: true
ID: {158d7cb3-7039-4a75-8e0b-3bd0a464edd2}

Name: Click to Play per-element
Version: 0.3.3
Enabled: true
ID: ClickToPlayPerElement@uaSad.addons.mozilla.org

Name: Click-to-Play Manager
Version: 1.4
Enabled: true
ID: click-to-play-manager@xulforge.com

Name: Config Descriptions
Version: 1.0.1-signed.1-signed
Enabled: true
ID: {1823e248-6bf4-f6f1-7901-65a68e8b6c1e}

Name: Context Search
Version: 0.6.4
Enabled: true
ID: {902D2C4A-457A-4EF9-AD43-7014562929FF}

Name: Custom Buttons
Version: 0.0.5.8.9
Enabled: true
ID: custombuttons@xsms.org

Name: DOM Inspector Plus! [dm]
Version: 2.0.16.3
Enabled: true
ID: inspector-dp@mozilla.org

Name: Download Cleaner
Version: 1.5.1.1-signed.1-signed
Enabled: true
ID: jid1-LSHV456F7wAw9g@jetpack

Name: Download Manager (S3)
Version: 4.06
Enabled: true
ID: s3download@statusbar

Name: Element Inspector
Version: 0.1.0
Enabled: true
ID: InspectElement@zbinlin

Name: Extension Options Menu
Version: 2.18
Enabled: true
ID: {1feca320-6b4d-11df-a08a-0800200c9a66}

Name: Fast Dial
Version: 4.15.1
Enabled: true
ID: fastdial@telega.phpnet.us

Name: Feedly Notifier
Version: 2.11.2
Enabled: true
ID: jid1-BOjn8b0IM7kH2w@jetpack

Name: FindBar Tweak
Version: 2.1.10
Enabled: true
ID: fbt@quicksaver

Name: Firebug
Version: 2.0.17
Enabled: true
ID: firebug@software.joehewitt.com

Name: FireGestures
Version: 1.10.9
Enabled: true
ID: firegestures@xuldev.org

Name: FirePath
Version: 0.9.7.1.1-signed.1-signed
Enabled: true
ID: FireXPath@pierre.tholence.com

Name: Flagfox
Version: 5.1.12
Enabled: true
ID: {1018e4d6-728f-4b20-ad56-37578a4de76b}

Name: Flash Game Maximizer
Version: 1.3.6.1-signed.1-signed
Enabled: true
ID: {258735dc-6743-4805-95fc-f95941fffdad}

Name: FlashResizer
Version: 1.4.1-signed.1-let-fixed.1-signed
Enabled: true
ID: {C6F77964-B0B5-4953-A144-93051184EC0C}

Name: FoxReplace
Version: 0.17.1.1-signed.1-let-fixed
Enabled: true
ID: fox@replace.fx

Name: Free Memory 2.0
Version: 0.0.2
Enabled: true
ID: @freememory2

Name: Gmail™ Notifier (restartless)
Version: 0.6.4
Enabled: true
ID: jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack

Name: Google search link fix
Version: 1.5.3
Enabled: true
ID: jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack

Name: Google Translator for Firefox
Version: 2.1.0.5.1.1-signed
Enabled: true
ID: translator@zoli.bod

Name: Greasemonkey
Version: 3.8
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Greasy Scripts
Version: 1.0.8
Enabled: true
ID: greasyscripts@ede123

Name: Hide Unwanted Results of Google Search
Version: 1.6
Enabled: true
ID: jid0-TpZJ4wPImlT1zIqfw58bD9vOeWQ@jetpack

Name: History Submenus II
Version: 3.1.2
Enabled: true
ID: HistorySubmenus2@Merci.chao

Name: Image Zoom
Version: 0.6.3.1-signed.1-signed
Enabled: true
ID: {1A2D0EC4-75F5-4c91-89C4-3656F6E44B68}

Name: KillSpinners
Version: 1.3.1
Enabled: true
ID: killspinners@byo.co.il

Name: Load Tabs Progressively Fixed
Version: 1.5
Enabled: true
ID: loadTabsProgressivelyFixed@prz.addons.mozilla.org

Name: Menu Wizard
Version: 5.01
Enabled: true
ID: s3menu@wizard

Name: More Tools Menu
Version: 1.2.4.1-signed.1-signed
Enabled: true
ID: {9a7a67d3-3048-47fb-acde-d0f7ae51f86a}

Name: Multi-process staged rollout
Version: 1.0
Enabled: true
ID: e10srollout@mozilla.org

Name: NoSquint Plus
Version: 47.5.0
Enabled: true
ID: zoomlevelplus@zoomlevelplus.net

Name: OmniSidebar
Version: 1.6.13
Enabled: true
ID: osb@quicksaver

Name: Open in Google™ Translate
Version: 0.1.2
Enabled: true
ID: jid1-r2tWDbSkq8AZK1@jetpack

Name: Open Link in New Tab
Version: 1.0.2016011401
Enabled: true
ID: openlinkintab@piro.sakura.ne.jp

Name: Open With Google Chrome
Version: 45.1
Enabled: true
ID: {3cc6c6ba-654c-417e-a8af-6997ac388ae1}

Name: Organize Status Bar
Version: 0.6.5
Enabled: true
ID: {35106bca-6c78-48c7-ac28-56df30b51d2c}

Name: Personal Menu
Version: 6.2.1
Enabled: true
ID: CompactMenuCE@Merci.chao

Name: Private Tab
Version: 0.1.9.1
Enabled: true
ID: privateTab@infocatcher

Name: Pure URL
Version: 1.2.4.1-signed.1-signed
Enabled: true
ID: pure-url@jetpack

Name: QuickNote
Version: 0.7.6
Enabled: true
ID: {C0CB8BA3-6C1B-47e8-A6AB-1FAB889562D9}

Name: Redirector
Version: 3.0.6
Enabled: true
ID: redirector@einaregilsson.com

Name: Restart
Version: 1.2.8
Enabled: true
ID: Restart@schuzak.jp

Name: Scroll here
Version: 1.0.1.1-signed.1-signed
Enabled: true
ID: jid0-lZXQJ9GTjTkK42kbqfV7fvBmSkc@jetpack

Name: Semi-Full Screen
Version: 1.0.1
Enabled: true
ID: SemiFullScreen@Merci.chao

Name: Sidebars List
Version: 0.2.3
Enabled: true
ID: sidebarsList@infocatcher

Name: Simplified Tab Groups
Version: 0.4.0
Enabled: true
ID: tabgroups@schub.io

Name: StartupMaster
Version: 1.6.1-signed.1-signed
Enabled: true
ID: {506d044e-41fa-4cc8-9dc6-9ff70e96eebf}

Name: Status-4-Evar
Version: 2015.11.16.23.1-signed.1-let-fixed
Enabled: true
ID: status4evar@caligonstudios.com

Name: Stylish
Version: 2.0.6
Enabled: true
ID: {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}

Name: Tab Mix Plus
Version: 0.5.0.0
Enabled: true
ID: {dc572301-7619-498c-a57d-39143191b318}

Name: Text Link
Version: 5.0.2016031501
Enabled: true
ID: {54BB9F3F-07E5-486c-9B39-C7398B99391C}

Name: Tile Tabs
Version: 13.9
Enabled: true
ID: tiletabs@DW-dev

Name: uBlock Origin
Version: 1.7.0
Enabled: true
ID: uBlock0@raymondhill.net

Name: Undo Bookmarks Menu
Version: 1.7.1-signed.1-signed
Enabled: true
ID: undoBookmarksMenu@alice

Name: Update Scanner
Version: 3.2.4
Enabled: true
ID: {c07d1a49-9894-49ff-a594-38960ede8fb9}

Name: URL Flipper
Version: 3.1.1.20.1-signed.1-signed
Enabled: true
ID: urlflipper@mozilla.ktechcomputing.com

Name: What about:..
Version: 4.12
Enabled: true
ID: jid0-IPSuVKD0J7yL1cIBwQAdoHTCWmY@jetpack

Name: YesScript
Version: 2.1.1-signed.1-signed
Enabled: true
ID: yesscript@userstyles.org

Name: Adblock Plus
Version: 2.7.3
Enabled: false
ID: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

Name: Adblock Plus Pop-up Addon
Version: 0.9.2.1-signed.1-signed
Enabled: false
ID: adblockpopups@jessehakanen.net

Name: Add-on Toolbarbutton
Version: 1.1.0
Enabled: false
ID: addontbb@byo.co.il

Name: All-in-One Sidebar
Version: 0.7.28
Enabled: false
ID: {097d3191-e6fa-4728-9826-b533d755359d}

Name: Anti Tumblr Infinite Scroll
Version: 1.2
Enabled: false
ID: anti_tumblr_infinite_scroll@davidk.se

Name: CacheViewer
Version: 0.8.6.3.1-let-fixed
Enabled: false
ID: {71328583-3CA7-4809-B4BA-570A85818FBB}

Name: checkCompatibility
Version: 1.3.1-signed.1-signed
Enabled: false
ID: check-compatibility@dactyl.googlecode.com

Name: Classic Reload-Stop-Go Button
Version: 1.0.3
Enabled: false
ID: crsg@ArisT2_Noia4dev

Name: CLEO
Version: 6.2
Enabled: false
ID: CLEO@guid.customsoftwareconsult.com

Name: CSS Usage
Version: 0.3.4.1-signed.1-signed
Enabled: false
ID: csscoverage@spaghetticoder.org

Name: Customizations for Adblock Plus
Version: 1.0.5
Enabled: false
ID: customization@adblockplus.org

Name: Disable Anti-Adblock
Version: 3.1.1-signed.1-signed
Enabled: false
ID: {d49a148e-817e-4025-bee3-5d541376de3b}

Name: Disable HTML5 Fullscreen Alert
Version: 2.0.0
Enabled: false
ID: jid1-Duz06d3mQhPItw@jetpack

Name: eCleaner
Version: 1.4.1-signed.1-let-fixed.1-signed
Enabled: false
ID: {c72c0c73-4eb0-4fb3-af0f-074e97326cfd}

Name: Element Hiding Helper for Adblock Plus
Version: 1.3.8
Enabled: false
ID: elemhidehelper@adblockplus.org

Name: Feed Sidebar
Version: 8.0.4.1-signed.1-signed
Enabled: false
ID: feedbar@efinke.com

Name: Firefox Hello
Version: 1.3.2
Enabled: false
ID: loop@mozilla.org

Name: Firefox Video Add-On
Version: 1.0.0
Enabled: false
ID: addon@gemaoff

Name: Flashblock
Version: 1.5.20
Enabled: false
ID: {3d7eb24f-2740-49df-8937-200b1cc08f8a}

Name: Flat Bookmarks
Version: 1.12
Enabled: false
ID: flatbm@xuldev.org

Name: FlipClock
Version: 0.82.1-signed.1-signed
Enabled: false
ID: {cdd09450-7280-11de-8a39-0800200c9a66}

Name: Greasemonkey Shared Script Folder
Version: 0.2.0.1-signed.1-signed
Enabled: false
ID: greasemonkeybcsf@stpors.net

Name: gui:config
Version: 1.10.1
Enabled: false
ID: guiconfig@slosd.net

Name: img2tab
Version: 1.67.1-signed.1-signed
Enabled: false
ID: sumeetkpatel@gmail.com

Name: keyconfig
Version: 20110522
Enabled: false
ID: keyconfig@dorando

Name: LCD Clock
Version: 0.4.2.1-signed
Enabled: false
ID: lcdclock_boller@gmail.com

Name: NO Google Analytics
Version: 0.6.1-signed.1-signed
Enabled: false
ID: jid1-JcGokIiQyjoBAQ@jetpack

Name: No Native Notifications
Version: 0.1.1-signed.1-signed
Enabled: false
ID: nnnotifier@robwu.nl

Name: NoRedirect
Version: 1.3.2.13.1-signed.1-signed
Enabled: false
ID: {c1970c0d-dbe6-4d91-804f-c9c0de643a57}

Name: NoSquint
Version: 2.1.9.1-signed.1-signed
Enabled: false
ID: nosquint@urandom.ca

Name: Omnibar
Version: 0.7.27.20141004.1-signed.1-signed
Enabled: false
ID: omnibar@ajitk.com

Name: Omnibar Plus
Version: 1.0.20.1-signed.1-let-fixed.1-signed
Enabled: false
ID: omnibarplus@quicksaver

Name: OPIE
Version: 6.6
Enabled: false
ID: OPIE@guid.customsoftwareconsult.com

Name: Pocket
Version: 1.0.2
Enabled: false
ID: firefox@getpocket.com

Name: Preferences Cleaner
Version: 0.3.2
Enabled: false
ID: pcln@cycledlm.gmail.com

Name: Prefsearch
Version: 0.2.1-signed.1-signed
Enabled: false
ID: prefsearch@eric.hamiter

Name: ProfileSwitcher
Version: 1.7.5.1-signed
Enabled: false
ID: {fa8476cf-a98c-4e08-99b4-65a69cb4b7d4}

Name: Puzzle Bars
Version: 2.1.14
Enabled: false
ID: thePuzzlePiece@quicksaver

Name: Redirect Bypasser
Version: 2.1.2
Enabled: false
ID: redirectbypasser@moonlight21.com

Name: Redirect Cleaner
Version: 2.4.0
Enabled: false
ID: redirectcleaner@example.net

Name: RedirectCleaner
Version: 1.0.0.1-signed
Enabled: false
ID: redirectcleaner@example.org

Name: Reload Plus
Version: 5.1.0
Enabled: false
ID: reloadplus@blackwind

Name: RightToClick
Version: 2.9.6
Enabled: false
ID: {cd617375-6743-4ee8-bac4-fbf10f35729e}

Name: Search by Image for Google
Version: 1.2.0.1-signed.1-signed
Enabled: false
ID: {ab4b5718-3998-4a2c-91ae-18a7c2db513e}

Name: SettingSanity
Version: 1.2
Enabled: false
ID: {12A60D0F-0077-4F41-81B2-1286DDD278BB}

Name: Stacked Inspector
Version: 1.0.20110524.1-signed.1-signed
Enabled: false
ID: stackedinspector@example.com

Name: Tab Memory Usage
Version: 0.2.5
Enabled: false
ID: jid1-fRvgLzKONCsPew@jetpack

Name: YouTube Unblocker
Version: 0.6.20
Enabled: false
ID: youtubeunblocker@unblocker.yt

Name: YouTube Unblocker
Version: 0.6.20
Enabled: false
ID: youtubeunblocker__web@unblocker.yt

Name: Zoom Page
Version: 14.5
Enabled: false
ID: zoompage@DW-dev

Graphics
--------

Adapter Description: AMD M880G with ATI Mobility Radeon HD 4250
Adapter Drivers: atiu9p64 atiuxp64 atiu9pag atiuxpag atiumdva atiumd6a atitmm64
Adapter RAM: 256
Asynchronous Pan/Zoom: none
ClearType Parameters: Gamma: 2200 Pixel Structure: R ClearType Level: 100 Enhanced Contrast: 400
Device ID: 0x9712
DirectWrite Enabled: false (6.2.9200.17568)
Driver Date: 9-19-2010
Driver Version: 8.770.2.1000
GPU #2 Active: false
GPU Accelerated Windows: 0/2 Basic
Subsys ID: 1604103c
Supports Hardware H264 Decoding: No; Hardware video decoding disabled or blacklisted
Vendor ID: 0x1002
WebGL Renderer: Google Inc. -- ANGLE (AMD M880G with ATI Mobility Radeon HD 4250 Direct3D9Ex vs_3_0 ps_3_0)
windowLayerManagerRemote: false
AzureCanvasAccelerated: 0
AzureCanvasBackend: skia
AzureContentBackend: cairo
AzureFallbackCanvasBackend: cairo

Important Modified Preferences
------------------------------

accessibility.loadedInLastSession: true
accessibility.typeaheadfind.flashBar: 0
accessibility.typeaheadfind.prefillwithselection: false
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 3
browser.download.importedFromSqlite: true
browser.download.manager.addToRecentDocs: false
browser.download.manager.closeWhenDone: false
browser.download.manager.showAlertOnComplete: false
browser.download.manager.showWhenStarting: false
browser.download.useDownloadDir: false
browser.link.open_newwindow.restriction.override: 2
browser.places.smartBookmarksVersion: 7
browser.search.openintab: true
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20160604131506
browser.startup.homepage: chrome://fastdial/content/fastdial.html
browser.startup.homepage_override.buildID: 20160604131506
browser.startup.homepage_override.mstone: 47.0
browser.tabs.animate: false
browser.tabs.closeWindowWithLastTab: false
browser.tabs.remote.disabled-for-a11y: true
browser.tabs.tabMaxWidth: 9999
browser.tabs.warnOnClose: false
browser.urlbar.autoFill: false
browser.urlbar.clickSelectsAll: false
browser.urlbar.doubleClickSelectsAll: true
browser.urlbar.mouseOnBottomLinkifies: true
browser.urlbar.suggest.searches: true
browser.urlbar.trimURLs: false
browser.zoom.siteSpecific: false
browser.zoom.updateBackgroundTabs: false
dom.apps.reset-permissions: true
dom.compartment_per_addon: false
dom.disable_window_flip: false
dom.disable_window_open_feature.location: false
dom.disable_window_status_change: false
dom.ipc.plugins.enabled.npietab2.dll: true
dom.ipc.plugins.flash.disable-protected-mode: true
dom.mozApps.used: true
dom.report_all_js_exceptions: true
dom.w3c_touch_events.expose: false
extensions.checkCompatibility.28.0: true
extensions.checkCompatibility.nightly: true
extensions.lastAppVersion: 47.0
font.internaluseonly.changed: false
font.language.group: x-western
font.name.serif.x-mlym: Arial
gfx.crash-guard.d3d11layers.appVersion: 47.0
gfx.crash-guard.d3d11layers.deviceID: 0x9712
gfx.crash-guard.d3d11layers.driverVersion: 8.770.2.1000
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.glcontext.appVersion: 43.0.4
gfx.crash-guard.glcontext.deviceID: 0x9712
gfx.crash-guard.glcontext.driverVersion: 8.770.2.1000
gfx.crash-guard.glcontext.gfx.driver-init.direct3d11-angle: true
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle: true
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-d3d11: false
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-warp: false
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-try-d3d11: true
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.glcontext: 2
gfx.direct2d.disabled: true
gfx.direct3d.last_used_feature_level_idx: 0
gfx.direct3d.prefer_10_1: true
gfx.driver-init.appVersion: 41.0.2
gfx.driver-init.deviceID: 0x9712
gfx.driver-init.driverVersion: 8.770.2.1000
gfx.driver-init.feature-d2d: false
gfx.driver-init.feature-d3d11: true
gfx.driver-init.status: 2
layers.acceleration.disabled: true
layers.offmainthreadcomposition.enabled: false
media.benchmark.vp9.fps: 15
media.benchmark.vp9.versioncheck: 1
media.eme.enabled: false
media.gmp-eme-adobe.enabled: false
media.gmp-gmpopenh264.abi: x86-msvc-x64
media.gmp-gmpopenh264.enabled: true
media.gmp-gmpopenh264.lastUpdate: 1455049713
media.gmp-gmpopenh264.version: 1.5.3
media.gmp-manager.buildID: 20160604131506
media.gmp-manager.lastCheck: 1467585769
media.gmp-provider.enabled: false
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
media.peerconnection.ice.default_address_only: true
media.webrtc.debug.aec_log_dir: C:\Users\Ed\AppData\Local\Temp
media.webrtc.debug.log_file: C:\Users\Ed\AppData\Local\Temp\WebRTC.log
media.youtube-ua.override.to: 43
mousewheel.withcontrolkey.action: 3
network.auth.allow-subresource-auth: 2
network.cookie.prefsMigrated: true
network.dns.disableIPv6: true
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.prefetch-next: false
places.database.lastMaintenance: 1467423105
places.history.expiration.transient_current_max_pages: 46843
plugin.importedState: true
plugin.state.flash: 1
plugin.state.npdeployjava: 0
plugin.state.npgoogleupdate: 0
plugin.state.nppdf: 1
plugin.state.npunity3d: 1
print.printer_Fax.print_bgcolor: false
print.printer_Fax.print_bgimages: false
print.printer_Fax.print_colorspace:
print.printer_Fax.print_command:
print.printer_Fax.print_downloadfonts: false
print.printer_Fax.print_duplex: -2147483586
print.printer_Fax.print_edge_bottom: 0
print.printer_Fax.print_edge_left: 0
print.printer_Fax.print_edge_right: 0
print.printer_Fax.print_edge_top: 0
print.printer_Fax.print_evenpages: true
print.printer_Fax.print_footercenter:
print.printer_Fax.print_footerleft: &PT
print.printer_Fax.print_footerright: &D
print.printer_Fax.print_headercenter:
print.printer_Fax.print_headerleft: &T
print.printer_Fax.print_headerright: &U
print.printer_Fax.print_in_color: true
print.printer_Fax.print_margin_bottom: 0.5
print.printer_Fax.print_margin_left: 0.5
print.printer_Fax.print_margin_right: 0.5
print.printer_Fax.print_margin_top: 0.5
print.printer_Fax.print_oddpages: true
print.printer_Fax.print_orientation: 0
print.printer_Fax.print_page_delay: 50
print.printer_Fax.print_paper_data: 0
print.printer_Fax.print_paper_height: 11.00
print.printer_Fax.print_paper_name:
print.printer_Fax.print_paper_size_type: 1
print.printer_Fax.print_paper_size_unit: 0
print.printer_Fax.print_paper_width: 8.50
print.printer_Fax.print_plex_name:
print.printer_Fax.print_resolution: 486
print.printer_Fax.print_resolution_name:
print.printer_Fax.print_reversed: false
print.printer_Fax.print_scaling: 1.00
print.printer_Fax.print_shrink_to_fit: true
print.printer_Fax.print_to_file: false
print.printer_Fax.print_unwriteable_margin_bottom: 0
print.printer_Fax.print_unwriteable_margin_left: 0
print.printer_Fax.print_unwriteable_margin_right: 0
print.printer_Fax.print_unwriteable_margin_top: 0
privacy.clearOnShutdown.cache: false
privacy.clearOnShutdown.cookies: false
privacy.clearOnShutdown.downloads: false
privacy.clearOnShutdown.formdata: false
privacy.clearOnShutdown.history: false
privacy.clearOnShutdown.sessions: false
privacy.cpd.downloads: false
privacy.cpd.extensions-nosquint: false
privacy.cpd.extensions-tabmix: false
privacy.cpd.formdata: false
privacy.cpd.history: false
privacy.cpd.offlineApps: true
privacy.cpd.siteSettings: true
privacy.donottrackheader.enabled: true
privacy.popups.showBrowserMessage: false
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 0
security.dialog_enable_delay: 200
security.disable_button.openCertManager: false
services.sync.declinedEngines:
services.sync.engine.greasemonkey: true
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1465698469

user.js Preferences
-------------------

Your profile folder contains a user.js file, which includes preferences that were not created by Firefox.

Important Locked Preferences
----------------------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: true
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.12
Version in use: 4.12

NSS
Expected minimum version: 3.23 Basic ECC
Version in use: 3.23 Basic ECC

NSSSMIME
Expected minimum version: 3.23 Basic ECC
Version in use: 3.23 Basic ECC

NSSSSL
Expected minimum version: 3.23 Basic ECC
Version in use: 3.23 Basic ECC

NSSUTIL
Expected minimum version: 3.23
Version in use: 3.23

Experimental Features
---------------------

**Comment by Hrxn** [comment]
I'm not surprised, considering this amount of installed extensions..

**Comment by gorhill** [comment]
So much information and yet nothing about possible error message in the browser console -- the first thing to look at.

**Comment by Imold** [comment]
I'll get that the next time it happens, if I remember.

**Comment by gorhill** [comment]
Obsolete issue + OP never came to collaborate in solving his own issue.
