### ISSUE TITLE
"Start" button doesn't work with Ublock

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#1639]
Ublok Origin Version 1.7.0
Firefox 46.0.1
Flash player disabled or not installed on the browser.

Steps to reproduce:

1.- Go to this page: http://beta.speedtest.net/    (The speedtest's main page uses Flash Player, but I disabled Flash Player because I wanted to try the beta, so that page is ready to work with Flash-free)

2.- Clic on "Begin test"

Actual results:

1.- The button doesn't work

Expected results:

1.- The button should begin the test

Note:
If you disabled Ublock Origin and refresh the page, the button works.
I updated de filter list, but the problem persists.

**Comment by gorhill** [comment]
Unable to reproduce using default settings. I will let you investigate the issue on your side, assume it's a 3rd-party filter list issue (i.e. not uBO proper).

**Comment by gwarser** [comment]
`www.budgetedbauer.com` and `ad.doubleclick.net`

**Comment by RobertJGabriel** [comment]
getting same issue , on chrome  52.0.2743.116

**Comment by aabadh** [comment]
Same issue on Firefox 48 and Ublock Origin 1.9.4.

**Comment by gorhill** [comment]
Still unable to reproduce with default settings and up-to-date lists, using a US VPN server. If there is an issue, investigating the cause (logger, browser console, screenshot, js debugger, etc.) will be more useful than just adding no more info than "same issue".

**Comment by Hrxn** [comment]
Works for me, latest Chrome Stable (52.0.2743.116 x64) on Windows 10, uBO 1.9.4.

**Comment by RobertJGabriel** [comment]
@gorhill 
<img width="1253" alt="screen shot 2016-08-30 at 16 05 53" src="https://cloud.githubusercontent.com/assets/6218780/18094835/bfde8734-6ecc-11e6-9edf-14ac205da84a.png">
<img width="1252" alt="screen shot 2016-08-30 at 16 06 38" src="https://cloud.githubusercontent.com/assets/6218780/18094834/bfd8187c-6ecc-11e6-86d6-750137051ca3.png">

**Comment by gorhill** [comment]
I didn't realize there were exception filters for Google servers. Does this help?

    ||www.googletagservices.com^$script,domain=beta.speedtest.net,important
    ||doubleclick.net$domain=beta.speedtest.net,important

**Comment by RobertJGabriel** [comment]
Yep it does, in our cause it was cause of it blocking Google Analytics script from there server .... it took a while to track down the issue (I work for a software company)
