### ISSUE TITLE
Is ublock origin ublock's new name?

### ISSUE THREAD

**Issue by mzso** [gorhill/uBlock#164]
Hi!
Last time I upgraded a new button appeared for "ublock origin". I thought it was some sort of new feature, but now I suspect it might be ublock renamed.
Which is troublesome since it appeared as a new addon in the addon manager instead of overwriting the old version, which I didn't realize until now. So I was running to adblockers in parralel.  Also none of my settings were imported so everything's reset to default...

If this is the case it was handled far less than elegantly. Also can I use export/import between the two addons?

**Comment by mzso** [comment]
[**@mzso**](https://github.com/mzso) commented on [2015. máj. 2. 13:02 CEST](https://github.com/gorhill/uBlock/issues/164#issue-72630427 "2015-05-02T11:02:58Z - Replied by Github Comment Enhancer"):
> Hi!
> Last time I upgraded a new button appeared for "ublock origin". I thought it was some sort of new feature, but now I suspect it might be ublock renamed.
> Which is troublesome since it appeared as a new addon in the addon manager instead of overwriting the old version, which I didn't realize until now. So I was running to adblockers in parralel.  Also none of my settings were imported so everything's reset to default...

If this is the case it was handled far less than elegantly. Also can I use export/import between the two addons?

**Comment by gorhill** [comment]
It's the new name of the uBlock version I personally take care of.

> Which is troublesome since it appeared as a new addon in the addon manager instead of overwriting > can I use export/import between the two addons.

Yes.

**Comment by mzso** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [2015. máj. 2. 13:22 CEST](https://github.com/gorhill/uBlock/issues/164#issuecomment-98348209 "2015-05-02T11:22:57Z - Replied by Github Comment Enhancer"):
> It's the new name of the uBlock version I personally take care of.
> 

So there will be two concurrent versions?

**Comment by gorhill** [comment]
I contribute to the other version as well, can't say "concurrent".

**Comment by anewuser** [comment]
@gorhill, they are indeed [concurrent](http://www.wordreference.com/definition/concurrent) (in English), even though they aren't in [French](http://www.wordreference.com/fren/concurrent) and other Latin languages. :)

**Comment by gorhill** [comment]
Ah yes, I had the French meaning in mind ("competitor"). So then I guess the answer is yes, there will be two concurrent versions.
