### ISSUE TITLE
[Feature Request] Use uBlock in different language

### ISSUE THREAD

**Issue by RedDragonx** [gorhill/uBlock#1640]
I'd like to use English as a default language instead of my native language, but uBlock has no option to do that, it only change to English if I change my browser language to English. This is very inconvenient.

**Comment by gorhill** [comment]
Duplicate of #1319.

**Comment by RedDragonx** [comment]
But the Vietnamese translation has some very poor line and I'll understand uBlock better if it's in English.

**Comment by gorhill** [comment]
You can contribute to improve the Vietnamese translation: <https://crowdin.com/project/ublock/vi#>.

**Comment by RedDragonx** [comment]
So unless I change my browser language to English, there's no way I can use uBlock in English?

**Comment by gorhill** [comment]
@RedDragonx That is correct.
