### ISSUE TITLE
Export in YYYY-MM-DD format for easier folder navigation.

### ISSUE THREAD

**Issue by Betsy25** [gorhill/uBlock#1641]
### Describe the issue
Currently the Export format is **my-ublock-backup_DD-MM-YYYY_TIME**
It's hard to navigate your backup folder, since with 99% of users, Explorer is configured to sort,
which put dates like 6-5-2016 before 17-5-2011, thus all backup are scattered around "randomly". If the export string would be **my-ublock-backup_YYYY-MM-DD-TIME**, _the backups would be sorted from oldest to newest, making it easier for the user to find, inspect or Import the last backup_.

Other guidelines do not relate to this issue.

**Comment by gorhill** [comment]
Can'r Explorer sort files by "last modified time"?

**Comment by krzysztof-sikorski** [comment]
> Can't Explorer sort files by "last modified time"?

This works when you use a single backup folder on a single machine - but the modification dates could probably get messed up if you copy files around or send them over the network.

**Comment by gorhill** [comment]
I could use `Date.toISOString()` instead of `Date.toLocaleString()`, but I don't know how well it would be appreciated by those who rather have the date localized. For example, in arabic:

`Date.toLocaleString()`: `١٧‏/٥‏/٢٠١٦ ١٠:٢٠:٠٦ ص`
`Date.toISOString()`: `2016-05-17T14:20:06.720Z`

**Comment by Betsy25** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country) DMY is the most used format, however i suspect most of the people might prefer the YMD format regarding computers & exploring, the big advantage (for all of us) is that no constant fiddling with sorting formats is needed when YMD is used.

**Comment by jjohns71** [comment]
YYYY-MM-DD is an internationally recognized standard with the publication of [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

Like the OP stated, this would be a nice feature to add!

**Comment by Hrxn** [comment]
Maybe stuff like this is best dealt with the right tools, i.e. the countless programs designed for renaming of files.

Any tool that can rename using regular expressions, for example.
Match:
`(my-ublock-backup_)(\d\d)(-)(\d\d)(-)(\d\d\d\d)(_)(\S*)`
Replace with:
`$1$6-$4-$2-$8`

**Comment by n1trux** [comment]
Proposed solution: Add an advanced switch for using locale, use yyyy-mm-dd by default.

**Comment by Grossdm** [comment]
I thought that I would start a request/issue for ISO 8601 filenames, but please add me to the list of those wanting it.

Something that would satisfy ISO 8601 and most modern file systems, AFAIK:
`(ublock-name)-YYYY-MM-DDThh.mm.ss.txt`

Two other thoughts: the weekday is of no use to me (and obviously redundant), and please do not use a comma in filenames.  I'm sure the latter thought has its dissenters.

[ISO 8601: Combined date and time representations](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations)

**Comment by Betsy25** [comment]
Sorry to dig this up, but would it be a good idea, to do the same for the default !time... header
`! 2-1-2017 03:40:13 https://www.cnet.com/news/ces-2017-5g-wireless-networks-treading-topic-at-t-qualcomm-ericsson-verizon-samsung/
` 
...which is automatically added to the "My filters" list upon adding an item created with the element picker ?

**Comment by Grossdm** [comment]
@Betsy25 I'm becoming a fan of yours. :grinning: 

Although I would put this at a much lower priority than ISO 8601 style file naming, "My filters" does get cluttered with a variety of date and time formats.
If a simple change, I would prefer ISO 8601 here also.
