### ISSUE TITLE
Unexpected result when blocking Javascript

### ISSUE THREAD

**Issue by choog** [gorhill/uBlock#1642]
I want uBlock Origin to block all Javascript until I allow it on a per-site basis. To accomplish this I have enabled [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) and added these **additional** rules in *My Rules* pane:

`* * 1p-script block`
`* * inline-script block`

By looking in the *Dynamic filtering* pane I can confirm that all rules are enabled.

I would now expect all Javascript to be blocked, but by doing a Google search I see a different result than when disabling Javascript directly in Firefox:

Firefox with Javascript disabled in `about:config`:
![google_javascript_disabled](https://cloud.githubusercontent.com/assets/19412133/15329033/7f3d6208-1c57-11e6-893a-16341100f2ae.png)

---

Firefox  with Javascript enabled in `about:config` and uBlock Origin installed:
![ublock_origin](https://cloud.githubusercontent.com/assets/19412133/15329325/94a9991c-1c58-11e6-9559-2d3fbadb9215.png)

In Firefox with Javascript enabled and uBlock Origin configured as  above, Google is almost identical to when Javascript is fully enabled, the only difference being a missing image and all drop down menus not working.

I have been looking in *Logger* while searching and see *inline-script* gets blocked for every query.

*With uBlock Origin configured  as above, one would expect an identical output as when Javascript is disabled directly in Firefox.*

Browser: **Firefox 46.0.1**
uBlock Origin version: **1.7.0**

**Comment by gorhill** [comment]
In uBO, javascript is blocked using resource blocking and/or CSP directives.

**Comment by choog** [comment]
@gorhill Sorry for assuming it was a bug, I don't know much about this subject.

Of pure interest I have tried to research what "resource blocking" and "CSP directives" mean. I didn't understand too much but while I did a search query on Google, I could see in the Firefox console that scripts were blocked by CSP as you said:

`Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src" 'unsafe-eval' *").`

If you don't mind I have two questions:

1. I assume that by configuring uBO as explained above, absolutely no scripts are run before I allow them to. Disabling Javascript directly in Firefox also prevents all scripts from runnning, then, how can Google "detect" the difference and serve me two different layouts?

2. The layout when disabling scripts directly in Firefox is more friendly, as all the basic functions work, can I configure a filter or rule in uBO to get this layout when using Google?

Thanks.

**Comment by gwarser** [comment]
Probably https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

**Comment by gorhill** [comment]
> how can Google "detect" the difference and serve me two different layouts?

See #308.

**Comment by choog** [comment]
@gorhill  What if a button was available in the popup UI for advanced users, that would enable/disable Javascript by toggling `pref("javascript.enabled", BOOL)`
in Firefox or the equivalent in other supported browsers?

One could then use the Web with Javascript disabled and `noscript` tags would be honoured, if a site was deemed worthy to have it's Javascript executed, one could toggle the switch and already added rules would apply or the dynamic filtering pane could be used.

This would not require changing how uBO works, only a button that would enable/disable Javascript in the browsers. Of course, one could just do this directly in the browser, but it would be much less akward with a button in the UI.

**Comment by eladkarako** [comment]
@choog use built-in Chrome feature instead.
<ol>
<li>Switch JavaScript off at <code>chrome://settings/content<strong>/javascript</strong></code>
<img src="https://i.imgur.com/9GHo5LGl.png"/></li>
<li>Per website, use the toolbar-icon on your right.
<img src="https://i.imgur.com/KzhY4Rpl.png"/>
You can also allow all sub-domains by adding an allow-rule like so:<br/>
<code><strong>[*.]</strong>mydomain.com</code>
</li>
<li>Optionally - do the same for cookies with <code>chrome://settings/content/cookies</code></li>
</ol>

Also, it will be sync up with your Google-account it will sync,<br/>
plus it will keep your <em>uBlock-origin</em> performing better,<br/>
since you're using a native-kind of blocking, <br/>
that will not pipe-through the extensions-process.<br/>
