### ISSUE TITLE
Redirecting doesn't work when script has integrity and crossorigin attributes

### ISSUE THREAD

**Issue by Tommy23** [gorhill/uBlock#1643]
For example, uBlock is redirecting FuckAdBlock. It's working when loaded like this:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js"></script>`

But it doesn't work when loaded like this:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js" integrity="sha256-xjwKUY/NgkPjZZBOtOxRYtK20GaqTwUCf7WYCJ1z69w=" crossorigin="anonymous"></script>`

uBlock is blocking FuckAdBlock script, but he's not injecting its own neutered version.

Console log error:
> Script from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'null' is therefore not allowed access.

Live example: [https://jsfiddle.net/uyvfaqug/](https://jsfiddle.net/uyvfaqug/)

**Comment by lewisje** [comment]
This sort of thing is what SRI was designed to do.

**Comment by Tommy23** [comment]
I know exactly what it is, but now redirecting is useless.

**Comment by Hrxn** [comment]
Is redirecting strictly required for defeating of _FuckAdBlock_?

I am not up-to-date regarding theses Anti-block techniques, it would be nice to have some sort of one-stop overview. Is there some kind of website (or wiki, etc.) out there?

**Comment by gorhill** [comment]
> redirecting is useless

Bottom line: provide a real world case (jsfiddle is no such case).

**Comment by Tommy23** [comment]
FuckAdBlock's main page is also a bad example, because they are not blocking the whole site, but just showing a message, right? Right.

http://fuckadblock.sitexw.fr/

I don't know why am I writing here. Issue was declined and closed. EOT.

**Comment by gorhill** [comment]
> FuckAdBlock's main page is also a bad example

Exactly -- that's why there is no filter for that site.
