### ISSUE TITLE
Whitelist everything from same host or first-party by default

### ISSUE THREAD

**Issue by alvinrxg** [gorhill/uBlock#1645]
### Describe the issue
Hello, i'm not a heavy ad blocker.
i want to whitelist resources from same host or first-party by default.
For example:
in `every-domain.com` the resource `every-domain.com/file.jpg` is blocked by some filter. I want to whiltelist such resource from the same host include subdomains. Is this possible?

i tried some filters start with `@@`
`@@*$~third-party`
`@@*$first-party`
none works.

### Your settings
- Browser/version: google chrome Version 50.0.2661.102 m (64-bit)
- uBlock Origin version: 1.7.2

##### Your filter lists
Default
##### Your custom filters (if any)
`@@*$~third-party`
`@@*$first-party`

### some other searchs
https://github.com/gorhill/uBlock/issues/1623 this issue wants to allow all ads by default. but i still want to block third party ads.

https://github.com/gorhill/uBlock/issues/1262 this issue wants to whitelist one specified domain. In my case i want to apply to all domains...

thank you guys for any help

**Comment by gorhill** [comment]
`@@*$first-party` works fine.

**Comment by alvinrxg** [comment]
Hello @gorhill ,
thanks for your reply.

i found i made a mistake.
for example the visited domain is abc.**com** and it has some resources in abc.**net**.

sorry for my issue pollution
