### ISSUE TITLE
Random DIV ID blocking not working all the time

### ISSUE THREAD

**Issue by Yanniclord** [gorhill/uBlock#1648]
So, i know that some websites use the random DIV id trick, where they cleverly use random generated ids to display ads or add click redirect overlays. I found some to be blocked by uBlock Origin, but some not, one being PowerWatch.

URL: http://powerwatch.pw/jgp1jsrq47vw

Here a screenshot with the div id, and the button you are supposed to click on, but there is a clever overlay over the entire website, and when you click it, your previous tab from which the powerwatch tab originated, will be redirected to an ad filled page:

![unbenannt](https://cloud.githubusercontent.com/assets/5807595/15453382/2169505e-2014-11e6-9565-49330bccf248.PNG)

Steps to reproduce:
Go to ( https://bs.to/serie/Stargate/10/5-Mutanten ) and click the PowerWatch button. Then click the "video" that pops up above the link set from Vivo, Openload, Powerwatch, etc. Then when the countdown is over, try clicking the "Proceed to Video" button. You will see that the tab it originated from, bs.to, will be redirected to some ad filled page. If you reload the PowerWatch page, and do a right click basically anywhere, and click Inspect, you will see that the id it points to is always random.

- Browser/version: Google Chrome v 50.0.2661.102 m
- uBlock Origin version: v1.7.2

Filter settings:
![2](https://cloud.githubusercontent.com/assets/5807595/15453401/d0d72bb0-2014-11e6-95c7-fb73290c1540.PNG)

I think that should be all, tell me if i missed something (stats, settings or alike). Regards, -Lord

**Comment by gwarser** [comment]
Try this:

`powerwatch.pw##script:inject(overlay-buster.js)`

**Comment by Yanniclord** [comment]
Works, thanks :) So, how exactly can i find out the same as you did? How can i reproduce what you did so that the next time, i can find this for myself. I tried finding it, but never actually found it.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1505
