### ISSUE TITLE
Version not displayed

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1649]
### Describe the issue
I just installed uBO 1.7.5b2 but uBO -> About says "1.7.5".

- Browser/version: IceCat 38.8.0
- uBlock Origin version:  1.7.5b2 installed from https://github.com/gorhill/uBlock/releases/

The proper version identifier missing in uBO?

**Comment by gwarser** [comment]
Your browser? From where you installed UBO? 
Try restarting your browser.

**Comment by davidhedlund** [comment]
@gwarser Restarting the browser didn't help.

**Comment by IDKwhattoputhere** [comment]
No, that's normal. It never shows if it's a beta but just the version number.

**Comment by davidhedlund** [comment]
@gorhill @IDKwhattoputhere This is stupid.

**Comment by gwarser** [comment]
I have uBlock from AMO, where `install.rdf` contains line `<version>1.7.5b2</version>` .
In uBlock from release page this line looks like this `<version>1.7.5</version>`

**Comment by davidhedlund** [comment]
@gwarser Now we're getting somewhere.

**Comment by IDKwhattoputhere** [comment]
> This is stupid.

Really smart argument.

**Comment by davidhedlund** [comment]
@IDKwhattoputhere Thank you.
