### ISSUE TITLE
Describe uBO's popunder blocking feature

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1650]
uBO recently hit the top 10 list at AMO. uBO's popunder blocking feature are not described at some places dough.

@gorhill I suggest that you spread your own sentence `"The filter type popup also blocks popunders."` to make this clear this way:

* Add `The filter type popup also blocks popunders.` to [ABP has all the features uBlock has!](https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#abp-has-all-the-features-ublock-has)
* Update `To block "popunders" windows/tabs. To be used in the same manner as the popup filter option, except that it will block popunders.` to `The filter type popup also blocks popunders.` in [Static filter syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax).
* Add `The filter type popup also blocks popunders.` to [AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/). Note that you also might want to add [this info](https://github.com/gorhill/uBlock/issues/810#issue-110814778) to the AMO page too while you're editing it.

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/issues/1542
> flyingzebras commented on 7 Apr

**Comment by IDKwhattoputhere** [comment]
> - Add The filter type popup also blocks popunders. to ABP has all the features uBlock has!

It already links to https://github.com/gorhill/uBlock/wiki/Static-filter-syntax which explains all additional filter options.

> - Update To block "popunders" windows/tabs. To be used in the same manner as the popup filter option, except that it will block popunders. to The filter type popup also blocks popunders. in Static filter syntax.

That's not entirely true since only one type of popup filter blocks popunders.

> - Add The filter type popup also blocks popunders. to AMO. Note that you also might want to add this info to the AMO page too while you're editing it.

That doesn't fit on the AMO page IMO. It's one of so many equally or more important features which are not all named on the AMO page to make it not too overwhelming.
