### ISSUE TITLE
"Update now" still active for uBlock filters after update occured

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1651]
### Describe the issue

I get "uBlock filters‎ : 513 used out of 515new version available" despite that I've clicked on "Update now". "Purge caches" didn't help either.

I found out that this problem stops when I restart my browser and click on "Update now" so I put my bet that this is a cache related issue.

### One or more specific URLs where the issue occurs

uBO -> "3rd-party filters"

### Screenshot in which the issue can be seen

![ubo](https://cloud.githubusercontent.com/assets/6416073/15463121/8279ce2e-20c7-11e6-902b-c67064d005f9.png)

### Steps for anyone to reproduce the issue

* Click on "Update now", this should update all your filters, except uBlock filters.
* Problem persist, sporadically.

### Your settings

- Browser/version: IceCat 38.8.0
- uBlock Origin version: 1.7.5b2

##### Your filter lists

Default uBO settings + Fanboy's Annoyance List + SWE: Fanboy's Annoyance

##### Your custom filters (if any)
www.youtube.com###movie_player > .ytp-iv-video-content > .video-annotations

**Comment by gorhill** [comment]
Restart uBO.

**Comment by davidhedlund** [comment]
@gorhill I changed the title.

**Comment by davidhedlund** [comment]
[mylabel:quarantined](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aquarantined%22+in%3Acomments&type=Issues&ref=searchresults)
