### ISSUE TITLE
Ads squares reappears after removing with the element picker

### ISSUE THREAD

**Issue by ccrowles** [gorhill/uBlock#1652]
So far I've seen this issue only on Kissanime: when watching a video, there are still the blank squares where ads where. I wanted to take them off since they occupy a large portion of the page, so I chose them with the element picker and added them to my list. But after refreshing the page, they are still there, and I seem unable to permanently take them off.

![screenshot03088](https://cloud.githubusercontent.com/assets/12866474/15467782/8e69b528-20e0-11e6-9c9d-7f9cce6cf4a2.jpg)

example: https://kissanime.to/Anime/Boku-no-Hero-Academia-My-Hero-Academia/Episode-008?id=126058

##### How to reproduce the issue: 

1. Go to Kissanime.to
2. Click on whichever anime
3. Click on an episode
4. Select with ublock's element picker the blank squares with hide on bottom and add them to your filters
5. Refresh the page and see them reappear.

##### Settings:

- Browser/version: Mozilla Firefox dev edition 48.0a2
- uBlock Origin version: 1.7.0

##### Your filter lists

Default filter lists + Anti-Adblock Killer + ublock badware + Malware domain list + Malware domains + both ITA lists

##### Your custom filters (if any)

kissanime.to###divFloatRight > .divCloseBut > a[href="#"]
||kissanime.to/ads/madads300.aspx$subdocument
||kissanime.to/ads/*$subdocument

**Comment by IDKwhattoputhere** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) next time. It's whitelisted in EasyList. Apparently to circumvent Anti-Adblock.
https://forums.lanik.us/viewtopic.php?p=83439#p83439
This is exactly why the [`important` filter option](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#network-filters-options) exists. Use it.
