### ISSUE TITLE
Suggestion: Add option to reset dynamic filtering rules and whitelist to defaults

### ISSUE THREAD

**Issue by sylveon** [gorhill/uBlock#1653]
In case the user messes too much with it and breaks it, it'd be great to have an "reset to defaults" button for these.

And only those, because the user won't specifically want to reset all settings.

**Comment by zummuz** [comment]
[The issue tracker is for provable issues only](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues)
Export the panes you need to the cloud, make reset from the settings pane, import things back from the cloud

**Comment by gorhill** [comment]
What I will do is provide a wiki page with the default data, so it will be a matter of cut&paste from the wiki into the dashboard.

**Comment by bendover22** [comment]
Along the same lines, I suggest that "user added" whitelist items be made easily identifiable in the UI.  That shouldn't be difficult.
* So they can quickly be selected to delete, or see which sites have been whitelisted, etc.  
* Now, they're all mixed w/ the default.

> about-scheme
> **_arstechnica.com_**
> behind-the-scene
> chrome-extension-scheme
> chrome-scheme
> loopconversation.about-scheme
> opera-scheme
> vivaldi-scheme
> _**www.microsoft.com
> www.neowin.net**_

  Many apps distinguish (somehow) when settings or items are default or user set.  By italics, grouping them separately, asterisks, etc.  If the list gets very long & added ones fall between default items, it's a chore to pick them out.

**Comment by Cerberus-tm** [comment]
Excellent idea! Messing things up is unfortunately common, and the ability to 1. recognise user-added rules, and 2. revert to factory settings would be nice.
