### ISSUE TITLE
Trying to Deploy Ublock Origin

### ISSUE THREAD

**Issue by kamidon2** [gorhill/uBlock#1654]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I'm trying to deploy uBlock Origin to our domain computers and I'm having trouble finding the URL... I found the ID of course, but the URL isn't in the manifest where I read that it's usually located at.  Aside from that, I guess I need an update URL too?  @_@ I've never deployed Chrome extensions before, can someone help?  Otherwise I haven't had any issues with the extension so far. Thanks for all the hard work putting this together.
The GPO is "Force Extensions to be installed list"  not verbatim...

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by lewisje** [comment]
Did you follow the directions [from Google](https://developer.chrome.com/extensions/external_extensions#registry)?

Presuming all computers in question run 64-bit Windows, you need to add the following entry to the Registry (which may be done via GPO):

in `HKEY_LOCAL_MACHINE\Software\Wow6432Node\Google\Chrome\Extensions`

make a new key: `cjpalhdlnbpafiamejdnhcphjbkeiagm` (same as the ID in the Chrome Web Store)

in that key, make a `REG_SZ` named `update_url` with value `https://clients2.google.com/service/update2/crx`

---
I also found the specific [directions for GPO](https://dev.chromium.org/administrators/policy-list-3#ExtensionInstallForcelist).

The specific policy for your case is

    Software\Policies\Chromium\ExtensionInstallForcelist\1 = "cjpalhdlnbpafiamejdnhcphjbkeiagm;https://clients2.google.com/service/update2/crx"

---
In either case, the update URL is the same one that all extensions on the Chrome Web Store use.

**Comment by gorhill** [comment]
Sorry, I am not the right person for admin questions.

See <http://decentsecurity.com/ublock-for-firefox-deployment/>.

**Comment by lewisje** [comment]
I also remember this effort to bring Group Policy to Firefox: https://sourceforge.net/projects/firefoxadm/

Still, at least Chrome offers GPO control by default, and Chrome is what this Issue was about.

**Comment by kamidon2** [comment]
Oh I'm sorry guys, I thought the example URL Google gives is just that, an example haha....I didn't think it was actually valid.
Thank you for the prompt replies and your help, I'll try it out now!  :D

**Comment by lewisje** [comment]
It was a bit confusing, because the extension ID really *was* just an example.
