### ISSUE TITLE
The entire ATT.COM home page is blocked by uBlock origin.

### ISSUE THREAD

**Issue by jdeleon1966** [gorhill/uBlock#1655]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Entire page for att.com is blocked.  Just shows the page background.

### One or more specific URLs where the issue occurs
https://www.att.com

### Steps for anyone to reproduce the issue

Enable uBlock origin.  Navigate using Firefox to https://www.att.com.  To view the site, disable uBlock for the site and now page comes up.

### Your settings

Using default settings.

- Browser/version: Firefox 46.0.1
- uBlock Origin version: 1.7.0
OS: Windows 10 Enterprise

##### Your filter lists

Default filter lists, nothing changed.

##### Your custom filters (if any)

None

**Comment by okiehsch** [comment]
It is an issue with the easy privacy list.
If you add the exception rule
`@@||attservicesinc.tt.omtrdc.net$xmlhttprequest,domain=www.att.com`
the problem is solved.

**Comment by jdeleon1966** [comment]
Okay, thank you.  Then can you tell me how to add the exception rule.  Sorry, I've only just used default settings and I'm not able to find any documentation on how to add an exception rule.

Thanks.

**Comment by IDKwhattoputhere** [comment]
"My filters" in the settings. You should also report it to the list maintainers so that they can fix it.
https://forums.lanik.us/viewforum.php?f=64

**Comment by jdeleon1966** [comment]
Thank you, that did the trick.  I guess you can consider this issue closed since it isn't really a problem with uBlock itself.

**Comment by lewisje** [comment]
As the person who opened the issue, you can close it: Right below the comment box, there is a "Close Issue" button.

I mean a maintainer can also close the issue, but if you recognize your own issue is worthy of being closed, you should do it as a courtesy to the rest of us.

**Comment by jdeleon1966** [comment]
Closing, issue is with the list and not uBlock
