### ISSUE TITLE
Unblock 01net.com/telecharger/

### ISSUE THREAD

**Issue by getdownjs** [gorhill/uBlock#1656]
In january 2016, 01net.com stopped to distribute adware/pup with their download manager. They only use official binaries from developers, like others french based download websites.

http://www.quechoisir.org/telecom-multimedia/internet/actualite-sites-de-telechargement-gare-aux-fichiers-parasites

http://www.01net.com/info/faq/telechargement/

**Comment by SARG04** [comment]
The place for filter list related issues uBlockOrigin/uAssets is the right place: 
https://github.com/uBlockOrigin/uAssets/issues

And for being removed from the list, it should be the same as for Sourceforge:
https://github.com/gorhill/uBlock/issues/1371

I don't see 01net.com in the second link.

**Comment by getdownjs** [comment]
01net.com/télécharger/ = telecharger.com
it's the same website

**Comment by gorhill** [comment]
Declined. The only activity of OP on GitHub is the issue here, and it was filed the same day he joined GitHub.

Maybe `01net.com` is clean now, but I will need actual evidences in opposition to the evidences that has been gathered for `01net.com`.
