### ISSUE TITLE
[Request] add anti-antiClickjack function to resources.txt

### ISSUE THREAD

**Issue by N4melessGitter** [gorhill/uBlock#1657]
### Describe the issue

Please add a function to resources.txt to deal with those:

```
<style type="text/css" id="antiClickjack">body{display:none !important;}</style>
<script type="text/javascript">
if (self === top) {
var antiClickjack = document.getElementById("antiClickjack");
antiClickjack.parentNode.removeChild(antiClickjack);
} else {
top.location = self.location;
}
</script>
```

NoScript already can deal with it, but as you said yourself uBlock and uMatrix can make NoScript mostly obsolete and I'd like to keep it that way.

### One or more specific URLs where the issue occurs

https://www.melani.admin.ch/melani/en/home/dokumentation/reports/technical-reports/technical-report_apt_case_ruag.html

### Steps for anyone to reproduce the issue

0. (whitelist above domain in NoScript to prevent it's surrogate to deal with this)
1. block javascript
2. go to above page and see a blank screen

### Your settings

- Browser/version: FF46
- uBlock Origin version: 1.7.0

##### Your filter lists

don't matter

##### Your custom filters (if any)

none

**Comment by gorhill** [comment]
Block 3rd-party scripts/frames everywhere by default if you want to control which 3rd-party's active content is allowed in your web pages.

**Comment by N4melessGitter** [comment]
I'm sorry but your reply makes no sense. While I understand that the code is meant as a clickjacking protection when the site is displayed in an iframe, I think every "protection" forcing the user to allow javascript is kind of counter-productive from a security standpoint. So to clarify, my feature request has nothing to do with 3rd party anything, it's code used in the main document itself.
The whole point is to un-hide the document body without allowing javascript!
What I requested was an additional function similar or same to what NoScript uses:

`if(window.top===window&&document.body.offsetWidth===0)['body','documentElement'].forEach(function(e){document[e].style.setProperty('display','unset','important')})`

I understand that you probably think every one of us is just a random idiot on the internet suggesting stupid things which only waste your precious time, but please, at least give us the benefit of a doubt and at least try to understand what we idiots write. Basically my first step to reproduce the issue assuming you don't have NoScript enabled was to block JS, so I don't understand why you would reply with "block 3rd-party scripts"?!
Perhaps re-read and re-consider, I'd appreciate it. Thank you.

**Comment by gorhill** [comment]
"Clickjacking" is just an invisible `iframe` from an malicious source. Block 3rd-party frames by default, this has [other benefits](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-Benefits-of-blocking-3rd-party-iframe-tags).

**Comment by N4melessGitter** [comment]
Ok, I'll try again.
First of all,  I block everything everywhere except 1st-party css and 1st-party images by default.

"clickjacking" doesn't have to be an invisible iframe I think; it's possible to display a page in an iframe and hijack any link-clicks or steal form-inputs or whatever with JS in the main document, the one embedding the iframe, right? That's I think the reason why the page mentioned in my original request uses that code.
But that code also prevents viewing the page even if directly called, not in an (i)frame.
If you would just click the link I provided you would understand what I mean.
That's what I would like to be able to circumvent without allowing JS for that domain.

I was hoping you could implement something along the lines of the code I provided that NoScript uses for this purpose, which I could use with:
`admin.ch##script:inject(anti-anticlickjack.js)`

I'm not sure if that would also remove the protection if any admin.ch page would be displayed in an iframe by a malicious site though? And maybe that's the reason you don't want to implement such a function? It probably would, but the code isn't much of a protection anyway IMO and just forces viewers to allow JS! And with a default setting of global JS/frame block wouldn't be much of a concern anyway because the malicious domain wouldn't have any JS permissions and no useful way to overlay DIVs etc.

If some uBlock users would use that feature without understanding its impact wouldn't have to be a concern for you either. If people want to shoot their own foot then there's nothing you can do about it ;-)
I hope this is much clearer now and hopefully you'll reconsider your "decline" for my request.

PS: NoScript provides that very same feature with a surrogate so it should be safe to also provide such a feature in uBlock without much concern for users safety. And since you now also have surrogate-type functions in resources.txt, I think this would be a nice addition.

Thanks, and sorry for continuously bothering you with this ;-)
