### ISSUE TITLE
Custom filter bug on Userscloud.com

### ISSUE THREAD

**Issue by CHEF-KOCH** [gorhill/uBlock#166]
Hello, I want to block some annoying stuff on UsersCloud.com and I used the _custom filter_ option provided by uBlock 0.9.6.0. So after adding my stuff and reloading the page it's still (or should I better say again) visible. 

Here is an [example userscloud page](https://userscloud.com/690e794dwv8g) -> I want to remove the green NoAds banner (... ._alert-success.alert_) and at the bottom of the page the fake Download button (_nitro.png_).

So my rules are:
```
! 10.4.2015 04:37:16 https://userscloud.com/bd8shaoklgav
userscloud.com###content > center > center > .container > .padding-none.row

! 1.5.2015 16:46:53 https://userscloud.com/ye728501hf5y
userscloud.com###content > .container > .innerLR > div:nth-of-type(1) > form > center > a[href^="https://userscloud.com/"] > .alert-success.alert

! 1.5.2015 16:47:00 https://userscloud.com/ye728501hf5y
||userscloud.com/i/nitro.png

! 1.5.2015 16:47:19 https://userscloud.com/ye728501hf5y
userscloud.com###content > center
```

My test setup:
```
Firefox on Ubuntu (+ the beta version on Android) + Cyberfox (on Win) (both 37.0.2 / 38.0 Beta Android)
Windows 7 SP1 fully patched + Ubuntu 14.04 LTS + Android 4.4.4 up to 5.1.1 with Firefox Beta 38.0
uBlock Origin 0.9.6.0 + NoScript (JS allowed for UsersCloud.com)
HTTPS Everywhere or any other problematically addons are not in use
Custom fIlter set (see above)
Cookies are whitelisted (for session)
```

Backup (rename to my-ublock-backup_3 5 2015_01_22_28 txt and remove the .png extension)
![my-ublock-backup_3 5 2015_01_22_28 txt](https://cloud.githubusercontent.com/assets/727123/7443088/fc37acec-f132-11e4-9db8-769430d269d0.png)

**Comment by gorhill** [comment]
Works fine here.

I can't see <https://cloud.githubusercontent.com/assets/727123/7443088/fc37acec-f132-11e4-9db8-769430d269d0.png>.

**Comment by gorhill** [comment]
It's because you have an `allow` rule for (green) `userscloud.com`. Allow rules will also disable cosmetic filtering for the site. See <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-disabling-cosmetic-filtering-for-the-current-site>.

Any reason you use an `allow` rule rather than a `noop` rule?

**Comment by CHEF-KOCH** [comment]
Thanks for the fast answer, after switching to <code>noop</code> it seems to work, but it breaks the dl (or better the resuming download after a reload) so I had to add manually add a cookie whitelist for that site. I didn't know that allowing a site also disallow the custom filters, than it makes sense and is my problem and not ublocks.

Thanks, next time I will be watch more carefully the docs.
