### ISSUE TITLE
Is uBlock Origin's static filter case-sensitive?

### ISSUE THREAD

**Issue by scratchyleet** [gorhill/uBlock#1660]
**Requirements:**
- Firefox 46.0.1.
- uBlock Origin 1.7.0.

**Reproducing steps:**
- Create a new profile.
- Install uBlock Origin.
- Add static filters:
```
||*$image
@@/^https:\/\/raw\.githubusercontent\.com\/gorhill\/uBlock\/master\/doc\/img\/icon38@2x\.png$/$image,domain=github.com
```
- Open uBlock Origin logger.
- Open page: https://github.com/gorhill/uBlock
- Watch uBlock Origin logger. Image: https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.png is still blocked.
- Change filters (or this part: \/uBlock\/ to \/ublock\/):
```
||*$image
@@/^https:\/\/raw\.githubusercontent\.com\/gorhill\/ublock\/master\/doc\/img\/icon38@2x\.png$/$image,domain=github.com
```
- Open _(or refresh)_ page: https://github.com/gorhill/uBlock
- Watch uBlock Origin logger. Image: https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.png is allowed now.

**Additional information:**
It would be also allowed without regex via a static filter:
`@@||https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.png^$image,domain=github.com`
either way
`@@||https://raw.githubusercontent.com/gorhill/ublock/master/doc/img/icon38@2x.png^$image,domain=github.com`

Is this a feature? Is there a switch to change behavior? Or a browser limitation? Is there a reason for uBlock's static filter to be a case-insensitive? If so then why regex version of a static filter differ from default static filter?

Good luck fixing that.

**Comment by gorhill** [comment]
Case insensitive by design.

**Comment by gwarser** [comment]
Then first example is broken.

For:
```
||*$image
@@/uBlock/$image,domain=github.com
```
Images are not whitelisted.

**Comment by gorhill** [comment]
That's right, I can reproduce.

**Comment by gorhill** [comment]
> why regex version of a static filter differ from default static filter?

The whole time I had assumed regex-based filters were treated as is by ABP. I just checked and I see regex-based filters are case-insensitive in ABP.

**Comment by gwarser** [comment]
I want to be sure - your see that upper-case filter is not whitlelisting upper-case URL, but lower-case filter do? This looks inverted.

Anyway `i` flag should work.

**Comment by gorhill** [comment]
> your see that upper-case filter is not whitlelisting upper-case URL, but lower-case filter do?

uBO normalizes URLs to lower case before static filter evaluation, so the URL which was internally matched against the `@@/uBlock/` regex-based filter was really:

    https://raw.githubusercontent.com/gorhill/ublock/master/doc/img/icon38@2x.png
