### ISSUE TITLE
Dynamic filtering problem

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBlock#1662]
### One or more specific URLs where the issue occurs

`http://thebiglead.com/2016/05/25/copa-america-2016-rob-stone-of-fox-sports-breaks-down-the-nuts-and-bolts/`

### Steps for anyone to reproduce the issue

Use Ublocko in blocking mode medium, go to
`http://thebiglead.com/2016/05/25/copa-america-2016-rob-stone-of-fox-sports-breaks-down-the-nuts-and-bolts/`
if you want to listen to the podcast it should be sufficient to noop 
`wpcomwidgets.com` and `soundcloud.com`.
The result I get is this.
![thebig](https://cloud.githubusercontent.com/assets/16838044/15591456/8ebdc216-239d-11e6-83e8-8f83f4a58c23.PNG)

I can achieve the expected result only if I make the noop rules permanent and start a new browser session.

![lead](https://cloud.githubusercontent.com/assets/16838044/15591574/20b2d634-239e-11e6-9d97-d3a492b951c5.PNG)

### Your settings

- Browser/version: Chrome 51
- uBlock Origin version: 1.7.4

##### Your filter lists

Default filter lists.

**Comment by gorhill** [comment]
Unrelated to medium filtering, I could reproduce the issue with default settings. I did not need to restart the browser, I could make the soundcloud widget appear after disabling Peter Lowe's. After I re-enabled Peter Lowe's + clearing the cookies, I could no longer reproduce the issue. This looks like a server-side issue.

**Comment by gorhill** [comment]
Forget above comment, I had erased the temporary rules -- back to square one.

**Comment by gorhill** [comment]
Repro steps:

1. Go to `http://thebiglead.com/2016/05/25/copa-america-2016-rob-stone-of-fox-sports-breaks-down-the-nuts-and-bolts/`.
1. Block 3rd-party frames and scripts for the page: Soundcloud widget does not appear (expected).
1. Locally noop `wpcomwidgets.com`: Soundcloud widget does not appear (expected).
1. Locally noop `soundcloud.com`: Soundcloud widget does not appear.
1. Locally noop 3rd-party frames and scripts: Soundcloud widget does not appear.
1. Remove global block rules for 3rd-party frames and scripts: Soundcloud widget finally appears.
1. Re-add global block rules for 3rd-party frames and scripts: Soundcloud widget still appears.

To repeat the issue, it's simply a matter of removing and re-adding the local noop rule for `soundcloud.com`, then repeat steps 5-7.

I can't explain what is happening here, need to investigate more with above steps.

**Comment by gorhill** [comment]
It's a cosmetic filtering cache issue.

uBO needs to flush cache entries of collapsed blocked frames when changing local rules.

**Comment by gorhill** [comment]
Side note re. Peter Lowe's list: disabling/enabling a filter list causes filters to be reloaded, which will cause all cache entries to be flushed -- but ultimately the issue was unrelated to any of the filter lists.
