### ISSUE TITLE
Static filter anchor malfunction.

### ISSUE THREAD

**Issue by scratchyleet** [gorhill/uBlock#1665]
**Requirements:**
- Firefox 46.0.1.
- uBlock Origin 1.7.0.

**Reproducing steps:**
- Set uBlock Origin's static filter to rules below:
```
||*$image
@@||avatars1.githubusercontent.com/u/12792253^$image,domain=github.com
```
- Open uBlock Origin logger.
- Open page: https://github.com/gorhill/uBlock/issues/1647
- Watch as an image with the url address https://avatars1.githubusercontent.com/u/12792253?v=3&s=40 is being allowed.
- Change static filter to rules below:
```
||*$image
@@||avatars1.githubusercontent.com/u/12792253?^$image,domain=github.com
```
- Open _(or reload)_ page: https://github.com/gorhill/uBlock/issues/1647
- Watch as an image with the url address https://avatars1.githubusercontent.com/u/12792253?v=3&s=40 is being blocked now.

Is that an expected behavior?

**Additional information:**
It seems when anchor in a static filter rule is stated after digits or letters then everything after anchor is passed. But if anchor is stated after special characters _(e.g.: "?", "=")_ then everything after anchor is not passed. Probably i do not completely understand anchor's role in uBlock's static filter. What does it expected to do?

Good luck fixing that.

**Comment by gwarser** [comment]
Works as expected https://adblockplus.org/en/filters#separators

**Comment by scratchyleet** [comment]
> Works as expected https://adblockplus.org/en/filters#separators

Then it is not an issue. My apologies.

Interesting though. Is there any difference between static and dynamic filters?
I have tended to think that dynamic filter allows string+anything after that. But now i see that static filter acts the same? Shouldn't it be an address explicit by default?

For example:
I would like to allow: `https://avatars1.githubusercontent.com/u/12792253`
But not: `https://avatars1.githubusercontent.com/u/12792253?v=3&s=40`
If i place a rule:
`@@||https://avatars1.githubusercontent.com/u/12792253`
in a static filter then `https://avatars1.githubusercontent.com/u/12792253?v=3&s=40` would be also allowed.
Though i have found a solution in the given link above:
`@@||https://avatars1.githubusercontent.com/u/12792253|`
Is that correct?

Also i would like to ask about pipes _("|", "||")_.
What is the difference between:
```
|https://avatars1.githubusercontent.com
||https://avatars1.githubusercontent.com
```
I couldn't understand that part from the given resource.

And i guess double pipes are not used in the end of an address? E.g.:
`https://avatars1.githubusercontent.com||`

**Comment by gorhill** [comment]
There is more details here: <https://adblockplus.org/filter-cheatsheet>.
