### ISSUE TITLE
Mozilla Discourse DOES NOT works

### ISSUE THREAD

**Issue by andersbateva** [gorhill/uBlock#1667]
The official support site does not works. Appears that I need to click "reply", but there is no reply button!

So, there is an issue with the support feature.

**Comment by gorhill** [comment]
Works fine here using default settings.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by andersbateva** [comment]
OK, where is the reply button then? I don't know where to get support about the support!

**Comment by IDKwhattoputhere** [comment]
![](https://cloud.githubusercontent.com/assets/16030872/15633498/eaaed3a0-25ad-11e6-8b33-fc36552df412.png)
Wadafuq?
