### ISSUE TITLE
###\5f filters not read by uBlock

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#1668]
### \5f iph_cp_popup Isn't read by uO, Because of the "_" being the first character

Open http://blog.hu/ in Firefox/Adblock Plus which hides the cookie element, and then with uBlock which shows the cookie message

**Comment by gorhill** [comment]
`blog.hu###_iph_cp_popup` works fine for both uBO and ABP -- and is easier to parse by humans. Why not use this?

**Comment by ryanbr** [comment]
Guessing that css elements shouldn't begin with "_" and maybe other non-standard ascii charaters may break the filters.

**Comment by gwarser** [comment]
@gorhill `blog.hu###\_iph_cp_popup` works because is specific. Even `blog.hu###\5f iph_cp_popup` works because is inserted forcibly.

`###\_iph_cp_popup` not work.

**Comment by gwarser** [comment]
Bit of documentation:

>An ID selector contains a "number sign" (U+0023, #) immediately followed by the ID value, which must be an CSS identifiers.

https://www.w3.org/TR/css3-selectors/#id-selectors

>identifiers (...) cannot start with a digit, two hyphens, or a hyphen followed by a digit. 

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

**Comment by ryanbr** [comment]
Can we get an update on this?
