### ISSUE TITLE
Request: Temporarily disable (pause)

### ISSUE THREAD

**Issue by derrickb** [gorhill/uBlock#167]
I'm not really a power user, only occasionally need to add sites to the whitelist.

The one feature I miss the most from Adblock was the pause feature.  I believe you could temporarily turn off the plugin on a given page from the context menu or the address bar icon.

With uBlock I have to go to manage extensions, turn off the plugin, and then turn it back on if I need to temporarily have it disabled.  Any way to add a "pause" feature?

**Comment by anewuser** [comment]
To disable it:

1. Click on the extension button
2. Click on the huge blue icon

To re-enable it:

1. Click on the extension button
2. Click on the huge greyed-out icon 
3. Click on the refresh icon to reload the current page

Please close this issue to mark it as solved.

**Comment by hotdogman** [comment]
@anewuser, I believe @derrickb is requesting an option to disable uBlock on every website.

**Comment by anewuser** [comment]
@hotdogman, if you **read the wiki**, you'll learn how to do that too.

Advanced user mode: https://github.com/gorhill/uBlock/wiki/Advanced-user-features

Dynamic filtering (check the first column): https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by gorhill** [comment]
> I believe @derrickb is requesting an option to temporarily disable uBlock on every website

I don't intend to implement this.

Excerpts from OP:

> go to manage extensions
> turn off the plugin
> turn it back on if I need to temporarily have it disabled

So this would only save one step, the _"go to manage extensions"_ one -- one easily overcome by clicking _"Manage extensions"_ in context menu of the extension icon. This is such a trivial step -- nowhere near enough to justify the code/UI changes to support this.

**Comment by anewuser** [comment]
@gorhill I've found [a specific wiki page about this]( https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere) and made a new screenshot for it:  https://i.imgur.com/7u8n9UM.png 

I was going to replace it, but noticed that the current image is hosted locally on Github. Is it tied to your account?

**Comment by gorhill** [comment]
It comes from an image I embedded in a comment in the issue section: <https://github.com/chrisaljoudi/uBlock/issues/40#issuecomment-73415681>.

**Comment by anewuser** [comment]
I wonder if the image URL is going to expire if I use this method to upload it but don't save my comment.

Just in case, here it is:

 ![Whitelisting all resources with the "All" column](https://cloud.githubusercontent.com/assets/6733770/7446377/d03b1ab4-f1ac-11e4-9a86-455a34bfca95.png)

**Comment by derrickb** [comment]
@anewuser @gorhill thanks for the info.  I actually didn't even know that the blue icon was added for enabling/disabling the plugin... was this added recently?  Anyway, I'm pretty sure this does exactly what I was looking for, being able to quickly turn on/off the plugin without going to the extensions page.

**Comment by anewuser** [comment]
@derrickb no, this is an old feature. Months ago it used to be green though.

**Comment by ackern** [comment]
Seems like in the time that it takes to tell all the people this feature will never be added and all the people who *think* they want it are in fact wrong and they don't really need it, it could already have been added.

**Comment by gorhill** [comment]
@ackern Why use a blocker if one needs to disable it so often that it becomes a big deal to have to deal with one extra click?

**Comment by anewuser** [comment]
@ackern If you want to invest your own time wisely, you can learn how to code for free on sites like http://www.codecademy.com/ and https://developer.mozilla.org/Learn . If that's too much work for you, you can hire a freelancer to make the change you want and have a custom version of uBlock.

This repository is meant to be used to report and talk about bugs and problems with existing features. If you want to keep discussing your opinions and wishes, please [start a thread on Reddit](http://reddit.com/r/ublockorigin), [as indicated by our rules](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ackern** [comment]
It's 6 or 9 clicks depending on whether you count keystrokes as separate clicks:

alt - t - a, or ctrl-shift-a

click to get focus in add-ons list

page down through list

page down again

disable

ctrl-w

...as opposed to 2 in Adblock Plus:

- click on icon

- Disable Everywhere

..or, since you don't seem to take my word for it nor the numerous other people who've asked for the same thing, ask the people at Adblock Plus why they have a Disable button, or NoScript or Ghostery or thousands of other extensions.

**Comment by gorhill** [comment]
Pin add-on tab. Two clicks:

- Select add-on tab
- Disable/enable

Works for any extension.
