### ISSUE TITLE
Possible to use cosmetic filters using wildcard?

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1670]
I know there a few sites with generated elements that are similar to:
##.random_NUi242j_block
##.random_HUH82n_block
##.random_xN29J0m_block
etc. and requires the user to add each cosmetic filter manually

Is there someway already or is it possible to add functionality to block all cosmetic elements by something similar to ##.random_*_block?

**Comment by anewuser** [comment]
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gwarser** [comment]
https://adblockplus.org/en/filters#elemhide_attributes

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by madranet** [comment]
Usual helpful answers by @anewuser and @gorhill there.

Short answer. It would appear not.  From the [Writing Adblock Plus filters docs](https://adblockplus.org/en/filters):

>Note: Element hiding works very differently from normal filters. This has the implication that no wildcards are supported in element hiding rules.
