### ISSUE TITLE
Block content div

### ISSUE THREAD

**Issue by kudataz** [gorhill/uBlock#1671]
example i have `<div id="z2c7">blbalbalblab</div>`
how to block this div?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Don't spam. https://github.com/uBlockOrigin/uAssets/issues/55
