### ISSUE TITLE
Edge Support?

### ISSUE THREAD

**Issue by kamidon2** [gorhill/uBlock#1672]
I'm sorry, not an issue, just a question.  Will uBlock be available for Edge when Edge comes out with Extension capabilities?
We all use Chrome, but want that extra protection just in case someone decides to use Edge.

Thank you

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/pull/1486

**Comment by kamidon2** [comment]
That's weird, I did a search before I posted and turned up nothing.
Thank you gwarser.

**Comment by IDKwhattoputhere** [comment]
How?
https://github.com/gorhill/uBlock/search?o=desc&q=edge&s=created&type=Issues&utf8=%E2%9C%93

**Comment by kamidon2** [comment]
...That's weird... I searched where it says "This repository" and I hit a few articles, but none had to do with the Edge browser.  Lol....I'm very new to this weird site :P

**Comment by IDKwhattoputhere** [comment]
At leat you tried. Maybe you searched the code but not the issues?

**Comment by kamidon2** [comment]
OOOOOOOOOoooooooooooohhhhhhhhhh.................. Yeaaaaah I did...  I thought search would by default search the entire article..... Lesson learned!
