### ISSUE TITLE
Easylist Hebrew has moved

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1673]
new links:
https://github.com/easylist/EasyListHebrew
https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt

**Comment by Yaron10** [comment]
Hello gorhill,

Could you please uplift this issue?
Currently the Hebrew list does not work "out of the box" and you have to add https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt as a customized list.
It might be a problem for many users.

Thank you very much.

Best regards.

**Comment by Yaron10** [comment]
Hello gorhill,

Thank you. I appreciate it.

FF memory usage on startup is now 10 MB higher than before the change.
Any explanation?

BR

**Comment by gorhill** [comment]
> Any explanation?

Memory usage measurement must always be performed very carefully, and these careful results must also always be interpreted very carefully. So it's impossible for me to say anything about _"10 MB higher than before the change"_. The change is merely adding an entry in the list of filter lists -- so quite likely unrelated to uBO.

**Comment by Yaron10** [comment]
Hello gorhill,

Thanks for the explanation.

BR
