### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by kamidon2** [gorhill/uBlock#1674]
Firstly, I get Internet Exploder is the worst browser ever created, but how come there isn't a uBlock Origin extension for it?  A few of my users are stubborn...and still stick with IE instead of Chrome...No surprise that one of the machines the other day got a virus...  Well thanks to applocker it didn't get installed....but still!  :P

**Comment by IDKwhattoputhere** [comment]
Really now? https://github.com/gorhill/uBlock/search?q=internet+explorer&type=Issues&utf8=%E2%9C%93

**Comment by kamidon2** [comment]
Lmao.......ok that time I didn't search................................... Sorry!

**Comment by gorhill** [comment]
> ok that time I didn't search

The real problem is that you are not respecting [CONTRIBUTING](https://github.com/uBlockOrigin/uAssets/blob/master/CONTRIBUTING.md).

**Comment by kamidon2** [comment]
Well Gorhill, I can't argue with that... I apologize, I will do you right next time.
As long as uBlock Origin around :)
