### ISSUE TITLE
Prevents from posting comments on YouTube

### ISSUE THREAD

**Issue by vibrasphere** [gorhill/uBlock#1675]
Which filter is that? It loads comments and comment field, but when typing nothing happens, cursor just blinking.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Working fine here. Does it work with uBlock disabled? Then use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) and figure it out.
