### ISSUE TITLE
what are "remote fonts"?

### ISSUE THREAD

**Issue by loominade** [gorhill/uBlock#1676]
are they:

1. Fonts not installed on my computer or…
2. …fonts from a domain other than the domain I am currently on ala. [Google Fonts](https://www.google.com/fonts)?

**Comment by Hrxn** [comment]
Point 1: Yes.
Point 2: Partially, remote fonts can come from the same domain, or another domain (3rd-party remote fonts).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
