### ISSUE TITLE
Combination of uBO + uMatrix + Anti-Adblocker Killer let some ads pass

### ISSUE THREAD

**Issue by alexara** [gorhill/uBlock#1677]
### Describe the issue

I recently reported that I'd see ads on TVinfo: https://github.com/uBlockOrigin/uAssets/issues/51
They disappear as soon as I turn off uMatrix and appear again when I turn it on.

### One or more specific URLs where the issue occurs

- http://www.tvinfo.de/tv-programm/20:15
- http://www.aachener-zeitung.de/lokales/heinsberg/waechst-dmk-eis-noch-weiter-als-gedacht-1.981044

### Screenshot in which the issue can be seen

A screenshot can be found here: https://github.com/uBlockOrigin/uAssets/issues/51

### Steps for anyone to reproduce the issue

1. Have uBO + uMatrix installed with default config and updated filter lists
2. Subscribe to EasyList Germany and  Anti-Adblock Killer | Reek‎
3. Turn off uMatrix
4. Visit http://www.tvinfo.de/tv-programm/20:15
5. You won't see any ads
6. Turn on uMatrix and reload the page
7. Ads are displayed

### Your settings

- Browser/version: FF 46.0.1
- uBlock Origin version: 1.7.0
- uMatrix 0.9.3.3

- All settings reset to default.
- The noScript addon was turned off. 

##### Your filter lists

Default + EasyList Germany + Anti-Adblocker Killer

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by alexara** [comment]
> Closing and marking as invalid, as per CONTRIBUTING.

I don't understand agains what I am violating. Both uBlock and uMatrix are by you: Aren't they meant to be used together? How shall I report the error if one affects the other? Is it about the third party filter which plays a role here and makes uBlock and uMatrix not work together?

Alex

**Comment by gorhill** [comment]
> Aren't they meant to be used together? 

No, they are both standalone extensions, each does not care about the other.

**Comment by alexara** [comment]
> each does not care about the other

Somehow they do as I described in the opening post. But if you don't believe me or you are not interested in solving this issue, then let that be an end to it.

However, I still believe I fulfilled all your points mentioned on CONTRIBUTING.

A confused Alex

**Comment by gorhill** [comment]
> Somehow they do as I described in the opening post.

Block `adternal.com` with a hosts file, observe same issue.

**Comment by gorhill** [comment]
Also, use uBO logger before filing issues, it would have shown you exactly what is happening (and save time for everybody). There is the exception filter `@@||adternal.com/*/ad-loading.bmp$image` in Reek's _Anti-Adblock Killer_. So clearly this means that if the resource affected by this filter is blocked by any other mean, it will defeat its purpose.
