### ISSUE TITLE
Feature request: Anti-Adblock Killer + uBO

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1678]
uBlock Origin will be less and less effective at blocking ads as especially video on demand (VOD) sites use blocking detections to enforce their ads. And "TV" through internet is taking over terrestrial TV.

To circumvent this a mechanism to prevent blocking detection need to be implemented in uBO. What do you think about adding [AAK](https://github.com/reek/anti-adblock-killer)?

**Comment by IDKwhattoputhere** [comment]
Why though? It can already be used in combination with uBO.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Because most people do not install AAK. uBO on the other hand is on rank #10 on AMO.

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1681

**Comment by flyingzebras** [comment]
> Reek's Akk Script requires a [scriptmanager](https://github.com/gorhill/uBlock/issues/1681#issuecomment-223155730)

**Comment by flyingzebras** [comment]
@gorhill Can you please recommend  AAK Script + a scriptmanager somewhere in the wiki?
