### ISSUE TITLE
Cannot block the "thing" ads on Reddit--

### ISSUE THREAD

**Issue by accordingtoame** [gorhill/uBlock#1679]
### Describe the issue
When I go to reddit.com, there are blocks of ads which I cannot seem to totally eliminate. I will select it and set a rule, but as soon as I refresh they come back. I have basically everything turned on to filter, except the individual national ones, and I cannot seem to get these things to go away. 

![settings2](https://cloud.githubusercontent.com/assets/19696650/15724974/39a7f03c-280f-11e6-8461-7006d9dfd1ff.jpg)
![screenshotofredditads](https://cloud.githubusercontent.com/assets/19696650/15724975/39be0494-280f-11e6-935a-29321b4ace90.jpg)
![shot2reddit](https://cloud.githubusercontent.com/assets/19696650/15724976/39c80d36-280f-11e6-8348-acc4f8a8bb63.jpg)
![settings1](https://cloud.githubusercontent.com/assets/19696650/15724977/39d89796-280f-11e6-917f-3d112739a819.jpg)

### One or more specific URLs where the issue occurs
https://www.reddit.com/

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
Mozilla 46.0.1

- uBlock Origin version: 
1.7.0

##### Your filter lists
see screenshot
uto-update filter lists. 
Parse and enforce cosmetic filters.

    121,360 network filters ＋ 59,394 cosmetic filters from:

        My filters‎ : 3 used out of 4
        uBlock filters‎ : 536 used out of 539purge cache
        uBlock filters – Badware risks‎  (github.com): 4 used out of 4
             uBlock filters – Privacy‎ : 22 used out of 31purge cache
        uBlock filters – Unbreak‎ : 99 used out of 101purge cache 
    Ads (5)
        Adblock Warning Removal List‎ (forums.lanik.us): 180 used out of 194purge cache
        Anti-Adblock Killer | Reek‎  (github.com): 1,838 used out of 1,885purge cache
        EasyList‎ (forums.lanik.us): 0 used out of 64,792purge cache
        EasyList without element hiding rules‎ (forums.lanik.us): 9 used out of 25,319purge cache
        Peter Lowe’s Ad server list‎ (pgl.yoyo.org): 2,335 used out of 2,401purge cache 
    Privacy (3)
        Basic tracking list by Disconnect‎ : 29 used out of 34purge cache
        EasyPrivacy‎ (forums.lanik.us): 5 used out of 11,613purge cache
        Fanboy’s Enhanced Tracking List‎ (forums.lanik.us): 0 used out of 977purge cache 
    Malware domains (6)
        Malvertising filter list by Disconnect‎ : 322 used out of 5,711purge cache
        Malware Domain List‎ (malwaredomainlist.com): 1,783 used out of 1,783purge cache
        Malware domains‎ (www.malwaredomains.com): 22,509 used out of 23,046purge cache
        Malware domains (long-lived)‎ (www.malwaredomains.com): 34 used out of 1,194httppurge cache
        Malware filter list by Disconnect‎ : 158 used out of 2,975purge cache
        Spam404‎ (www.spam404.com): 5,453 used out of 5,454
Social
 Fanboy’s Annoyance List‎ (forums.lanik.us): 1 used out of 23,057purge cache 
Multipurpose
 Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us): 100,368 used out of 100,425purge cache
hpHosts’ Ad and tracking servers‎ (hosts-file.net): 45,066 used out of 47,770httppurge cache 

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

! https://www.reddit.com###thing
(isn't working)

my filters
http://www.rewardstyle.com

! 5/17/2016, 10:25:55 AM http://www.neimanmarcus.com/Accessories/Bags-Wallets/cat8670736_cat21150736_cat000470/c.cat#userConstrainedResults=true&refinements=731,721,4294894805,4294903711,4294894797&page=1&pageSize=120&sort=PCS_SORT&definitionPath=/nm/commerce/pagedef_rwd/template/EndecaDrivenHome&locationInput=&radiusInput=100&onlineOnly=instore&allStoresInput=false&rwd=true&catalogId=cat8670736&selectedRecentSize=
||www.neimanmarcus.com/category/promotiles/event/MensPT_0416/PromoTile_MCM_050416.jpg$image

! 6/1/2016, 3:21:13 PM https://www.reddit.com/
www.reddit.com###thing_t3_4k9jkw

! 6/1/2016, 3:23:03 PM https://www.reddit.com/
www.reddit.com###thing_t3_4k9jkw

my rules

    no-cosmetic-filtering: * true
    behind-the-scene * 3p noop
    behind-the-scene * 3p-frame noop

Temporary rules

    no-cosmetic-filtering: * true
    behind-the-scene * 3p noop
    behind-the-scene * 3p-frame noop

whitelist
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
loopconversation.about-scheme
oldnavy.gap.com
online.americanexpress.com
opera-scheme
secure-oldnavy.gap.com
secure.nordstrom.com
staywellkept.com
www.ebates.com
www.sephora.com

**Comment by IDKwhattoputhere** [comment]
> `no-cosmetic-filtering: * true`

That's your issue.

**Comment by accordingtoame** [comment]
Thank you!  I noticed that at home (same OS/Versions) I don't have that checked. So I probably should've realized that's the difference...

So, what issues will I run into elsewhere by unchecking that, yknow, that I clearly haven't figured out yet?  I thought that could be why sites like Sephora.com won't work (which might be why I did that) because it loads the framework of the site fine, but if I wanted to see anything for sale, like, to buy something, it doesn't seem to matter what is checked, and I basically just have to entirely disable it.

Sidebar: I have that Privacy Badger--should I ditch that? Is that causing conflicts?

**Comment by Hrxn** [comment]
Issues with cosmetic filtering? Not really, this should work without any problems.

If you, in the very unlikely case, find a site where something is not displayed properly because of cosmetic filtering, you can report it here: https://github.com/uBlockOrigin/uAssets

You can use Privacy Badger at the same time, but, in my opinion, it is pretty much pointless.

**Comment by anewuser** [comment]
I think that you can disable that block by opening your Reddit account settings and checking the appropriate option. I can't tell you the exact words because I've deleted my account.

**Comment by gwarser** [comment]
>You can easily toggle on/off cosmetic filtering for a given site:

https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

**Comment by accordingtoame** [comment]
Thank you everyone!  

I had no idea I could turn that block off on Reddit, btw. *feels stupid*

**Comment by Hrxn** [comment]
All cleared up?

If yes, I assume this issue can be closed.

**Comment by accordingtoame** [comment]
Yes I believe so, thank you!

**Comment by anewuser** [comment]
@accordingtoame Open Github on your browser, so you can see the button to close the issue.
