### ISSUE TITLE
A button for Dashboard

### ISSUE THREAD

**Issue by najjara** [gorhill/uBlock#168]
The way things work right now is: Hamburger -> Addons -> look for uBlock among all the addons, double click -> Show Dashboard

This could be: uBlock icon -> Show Dashboard

As the drop down interface is very limited, access to Dashboard is needed to experiment. For example with rules.

**Comment by tenkuu** [comment]
uBlock icon -> click the black bar with "uBlock Origin 0.9.x.x"

**Comment by najjara** [comment]
Neat
This leads to my next "issue"; more extensive documentation

**Comment by tenkuu** [comment]
[There is a wiki](https://github.com/gorhill/uBlock/wiki)

**Comment by najjara** [comment]
Ya, sorry for that. I read it before, but I skipped the part you're referring to (the title bar). So I edited my comment
