### ISSUE TITLE
Suggestion: Subscribe to Reek's Anti-Adblock Killer list by default

### ISSUE THREAD

**Issue by h5675ga** [gorhill/uBlock#1681]
Considering how common Anti-Adblock measures are becoming on mainstream websites, I suggest that you should consider having ublock origin subscribe to the list by default.

**Comment by CrisBRM** [comment]
Completely pointless because Reek's Anti-Adblock Killer requires a scriptmanager and its corresponding userscript to work alongside uBlock should you subscribe to that list.

**Comment by IDKwhattoputhere** [comment]
Hello, @flyingzebras. :wave:

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Bingo.

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1678
