### ISSUE TITLE
uBlock does not work with http://www.delfi.ee/

### ISSUE THREAD

**Issue by keevitaja** [gorhill/uBlock#1682]
This started few days ago with http://www.delfi.ee 

http://i.imgur.com/5AQhgEB.png

Before there was no background image and a top banner.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Are you using the EST filter list?

**Comment by keevitaja** [comment]
@IDKwhattoputhere i was not :( now everything is as it is supposed to be.
