### ISSUE TITLE
Make Ctrl + S save changes to My Filters

### ISSUE THREAD

**Issue by Industry** [gorhill/uBlock#1683]
Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
### Describe the issue

It would be nice if Ctrl + S applied changes in My Filters instead of opened the "Save Webpage" Dialogue like it does in chrome.
### One or more specific URLs where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html
### Screenshot in which the issue can be seen

https://i.imgur.com/eI4RsJT.png instead of actually saving
### Steps for anyone to reproduce the issue

Head over to the settings page -> My Filters and press Ctrl S
### Your settings
- Browser/version: Chrome 50.0.2661.102 m on Win 10 x64
- uBlock Origin version: uBlock Origin v1.7.2
##### Your filter lists

N/A

**Comment by lewisje** [comment]
The first question is whether it's possible to override that shortcut, because it's used by the browser itself.

**Comment by tophf** [comment]
>whether it's possible to override that shortcut, because it's used by the browser itself

Chrome/Chromium allow overriding of all shortcuts except Ctrl-Tab/N/T/W (switch tabs, open a new window, open a new tab, close the tab). However, it's not the case with some chromium forks that define their own shortcut management feature (Vivaldi, for example).

**Comment by Buranek** [comment]
How about Ctrl+Enter?

**Comment by lewisje** [comment]
Ctrl+S is probably better to override: Ctrl+Enter normally opens the selected link in a new tab.

**Comment by gorhill** [comment]
From my last experience with creating built-in shortcuts, I will declined. What works well in one language/keyboard layout might not be true in others.

**Comment by gorhill** [comment]
I started to use [CodeMirror](http://codemirror.net/), and keboard shortcut to save came for free as a result. So Ctrl-S (or equivalent in other OS) is now available in "My filters" with 8d5ebf44efb7.
