### ISSUE TITLE
Some FontAwesome icons are blocked even with all permissions allowed

### ISSUE THREAD

**Issue by IceGiant** [gorhill/uBlock#1687]
Accidentally discovered an odd bug while developing my webpage at http://45.62.253.141/

In the header navbar, the icons display correctly, but the ones that should be showing in the nav-items in the navbars I've been creating below the header won't show up unless uBlock is turned off entirely.  Allowing everything on the page doesn't work, oddly.  Only shutting uBlock off entirely seems to work.

##### Filters I have
All uBlock filters (minus Experimental)
All of the below:
Ads
Privacy
Malware domains
Social
Multipurpose

**Comment by gwarser** [comment]
Static filter ##.fa-reddit found in:

    Fanboy’s Annoyance List

**Comment by IceGiant** [comment]
Thanks!  Not sure why that would get blocked even when I'm telling the addon to let everything through.

**Comment by IDKwhattoputhere** [comment]
> Allowing everything on the page doesn't work

What do you mean by that? It's an element hiding filter so allowing network requests won't do anything. [*click*](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering)

**Comment by gorhill** [comment]
> Not sure why that would get blocked even when I'm telling the addon to let everything through.

I check and disabling uBO for the site does let the icons appear. How did you tell uBO "to let everything through"?

**Comment by IceGiant** [comment]
My mistake, didn't realize there was a separate toggle for cosmetic filtering.

**Comment by IDKwhattoputhere** [comment]
Why not use the blue power button? It's your website after all so why would you block anything there to begin with?

**Comment by IceGiant** [comment]
I was thinking more from the perspective of other people visiting the site.  I trust my site, but why would anyone who doesn't know me?

**Comment by gorhill** [comment]
I still do not understand what was done to "let everything through". Disabling filtering using the blue button worked, disabling cosmetic filtering worked. How did you "let everything through"?

**Comment by IceGiant** [comment]
I mistakenly thought allowing "all" for the site in the matrix for controlling per site/global permissions allowed everything through.  I didn't realize it was separate from the cosmetic filter toggle.

**Comment by IDKwhattoputhere** [comment]
> other people visiting the site

In that case you might want to report it here: https://forums.lanik.us/viewforum.php?f=64
I mean I don't think the icons are a big deal but maybe you want to get it fixed in the filter list.
Or just rename it.

**Comment by IceGiant** [comment]
Looks like there's another reddit logo FontAwesome has that's not in the list if I want to take the lazy route.  My line of thinking was to use the icon instead of dropping "/r/" in front of the name to denote feeds I'm pulling from reddit.
