### ISSUE TITLE
ublock not blocking the two 'gold-colored' ads of youtube videos on the youtube search result page

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [gorhill/uBlock#1689]
im sure that you all noticed this but recently (like 2-4 days ago)

ublock doesnt block the the two ads of youtube videos showing up on the youtube results search page

youtube must've changed something on their end recently

*** im sure that everyone does, but if you anyone doesn't see this problem, then forget it *** 
 
settings are default & regular

**Comment by IDKwhattoputhere** [comment]
No ads here.
This is also not the repo to report filter issues and you ignored and deleted the template so now we don't have good information to help you.
Try updating the filter lists (purge cache + update) or resetting to default settings in the [settings pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
