### ISSUE TITLE
ads showing 

### ISSUE THREAD

**Issue by rajatmathurs** [gorhill/uBlock#1693]
Hi,

I have installed ublock origin on my android firefox, its working great, but when i open
this website `http://www.parentherald.com/articles/46992/20160602/samsung-galaxy-c5-c7-price-specs-comparing-similarities-differences-iphone.htm`

then at the bottom of the page a add box shows "Addsupply" i had to click on the X button to close it.
Kindly please check and release a update for this issue, so that this type of add is blocked by ublock origin filters.

Waiting for the solution

thanks

**Comment by IDKwhattoputhere** [comment]
You're in the wrong place.
https://forums.lanik.us/viewforum.php?f=62

**Comment by rajatmathurs** [comment]
IDKwhattoputhere,

I had to post the issue in the forum, is it possible that submit the issue to the concerned team.

please and thanks

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
