### ISSUE TITLE
uBlock disables GMail search input box in Chrome

### ISSUE THREAD

**Issue by krishnanand** [gorhill/uBlock#1694]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When uBlock is enabled in Chrome latest, it disables the input search box after logging in. When uBlock is disabled, the input search box is enabled. This behaviour is not observed in Firefox.

### One or more specific URLs where the issue occurs
Gmail.com

### Screenshot in which the issue can be seen

https://imgur.com/a/Nej6C

### Steps for anyone to reproduce the issue
1. Login to Gmail with uBlock enabled on Chrome latest
2. The search box should be disabled.
3. Disable uBlock on Chrome latest.
4. The search box should be enabled.

### Your settings

- Browser/version: Chrome Version 51.0.2704.79 (64-bit)
.
- uBlock Origin version: 1.7.2

##### Your filter lists

No custom filter list of any kind.

##### Your custom filters (if any)

www.facebook.com###pagelet_loggedout_sign_up > .bottomborder.uiBoxOverlay.pam
www.facebook.com##DIV.ego_column.egoOrganicColumn
##.taboola_rhs
##DIV.gbqfwa
##.taboola_lhs
##DIV[data-item-id*="~~V1~~"]
###taboola-below-main-column-sc
##.bh_container
##.buyhatke_widget
###shop_advertise_div_1
amazon.com##.s-sponsored-list-header ~ *
amazon.com##.s-sponsored-list-header
amazon.com##.s-hidden-sponsored-item
amazon.com##a[href^='/gp/slredirect/redirect.html']
facebook.com##div[data-referrer="pagelet_growth_expanding_cta"]
facebook.com##DIV[data-referrer="pagelet_trending_tags_and_topics"]
www.facebook.com##._3qw.uiLayer._3qx._n8 > ._3ixn
www.theworldin.com##div[class*="ad-panel"]
www.facebook.com##.generic_dialog.pop_dialog.generic_dialog_modal
##DIV[class="fadeMe"]
||tm.zedo./*/*/*;$script
##DIV.rec_container_footer
in.news.yahoo.com###YDC-Col2

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Works fine for me. Have you tried using the logger? You should be able to find the offending filter there.

**Comment by gorhill** [comment]
Such issue should not be addressed here _at all_ -- and this specific one even more than any other.
