### ISSUE TITLE
"Errors" link in the Extension tab

### ISSUE THREAD

**Issue by mk2soldier** [gorhill/uBlock#1697]
Hi guys, I'm not sure if this is applicable as issue however here it is:

When I manually install uBlock, in the Extensions tab I get the "Errors" link.
If I click the link I get a little window, inside it there is the text from the attached image underlined in red.
Apart from this, uBlock seems to work fine.

Windows 10 Version 1511 (OS Build 10586.318)
Chromium version: 51.0.2704.84 (386251)
No sync • No WebRTC • No Widevine variant
Downloaded from this site: http://chromium.woolyss.com/
uBlock Origin version 1.7.4

**EDIT:**

I get the same "error" with uBlock 1.7.5

![ublock0](https://cloud.githubusercontent.com/assets/5905339/15872958/844a69ac-2cfc-11e6-8446-b5a38f28c786.PNG)
![ublock1](https://cloud.githubusercontent.com/assets/5905339/15872956/8446da8a-2cfc-11e6-9aa7-fd0639f53c59.PNG)
![ublock2](https://cloud.githubusercontent.com/assets/5905339/15872957/8448d36c-2cfc-11e6-8b46-e3ebd7a90644.PNG)

**Comment by gorhill** [comment]
> No sync • No WebRTC • No Widevine variant
> Downloaded from this site: http://chromium.woolyss.com/

So your special Chromium version was built without support for WebRTC -- hence a normal error in such case.

**Comment by mk2soldier** [comment]
Thank you for the answer!
