### ISSUE TITLE
[Enhancement] blacklist and allow by default

### ISSUE THREAD

**Issue by Jan02** [gorhill/uBlock#1698]
Currently, we can only whitelist with ublock. What about blacklisting in a context where the extension would allow all by default? Or is that a different addon? If so which one? thank you

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except

**Comment by IDKwhattoputhere** [comment]
RTFM
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except
