### ISSUE TITLE
Block style

### ISSUE THREAD

**Issue by sfassfas** [gorhill/uBlock#170]
can i use ublock to turn style="display: none;" to style="display: all;" on a specific webpage and how would i do that? also i know that style="display: all;" doesnt work but it stops it being hidden at the same time

**Comment by gorhill** [comment]
Just tell me what you want to accomplish or what is the issue, then I can answer proeprly.

**Comment by anewuser** [comment]
If you use Firefox, this is what you're looking for: [How to override the CSS of a site in Firefox with userContent.css?](http://superuser.com/a/319322/33758)

If you prefer an extension to create custom stylesheets, use [Stylish](https://addons.mozilla.org/firefox/addon/stylish/) (which also [available for Chrome](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe)).

No matter what solution you use, remember to add [!important rules](https://duckduckgo.com/?q=css+!important+rule) to your custom CSS to make sure that it will work.

**Comment by gwarser** [comment]
@sfassfas if you wanto to disable cosmetic filtering on the page you can use exception filter `@@||example.com^$elemhide` or simple click on eye icon in uBlock popup
