### ISSUE TITLE
uBlock Origin showing ads

### ISSUE THREAD

**Issue by rajatmathurs** [gorhill/uBlock#1701]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

I have installed uBlock Origin add on in android firefox version 47.0, i am on 5.1.1 android version, when open this site 

[URL(s) songspk.live]

then ads are showing, see the below screenshot

![screenshot_2016-06-09-13-24-34](https://cloud.githubusercontent.com/assets/19775409/15922647/7897e904-2e46-11e6-99b0-933086ce3bfb.png)

Kindly check as the add is the trending apps, how to block this trending apps add

Let me know

Thanks

**Comment by lewisje** [comment]
Chances are it's a filter-list issue; does the logger work in Firefox for Android?

**Comment by rajatmathurs** [comment]
Well i don;t how logger works,  please tell me all the details in steps how to block this ads

thanks

**Comment by harshanvn** [comment]
yes, the logger works in android too!
I had created couple of dynamic filtering rules myself.

**Comment by rajatmathurs** [comment]
Please tell me step by step details so that i can block the above ads showing on songspk.live

**Comment by harshanvn** [comment]
may be try creating a filter using [element picker](https://github.com/gorhill/uBlock/wiki/Element-picker)

And here is the [logger ](https://github.com/gorhill/uBlock/wiki/The-logger)to inspect more deeper.

**Comment by rajatmathurs** [comment]
harshanvn,

I am unable to figure it out, how to make it happen, could you please tell me all the steps that i had to do in screenshots, your help is appreciated

thanks a lot

**Comment by lewisje** [comment]
We're not a hand-holding operation here; go to forums.lanik.us as in the previous post, and ask the helpful EasyList forum users to find some filter to block that ad if you don't want to figure it out yourself.

**Comment by rajatmathurs** [comment]
ok thanks all for your help

**Comment by rajatmathurs** [comment]
One doubt i have those, user who make there own filter using element picker, are for your personal mobile or will these filters get updated for everyone on ublock origin and if yes then how long will it take for ublock origin to update

Let me know

thanks

**Comment by harshanvn** [comment]
Report the problem @https://forums.lanik.us/
They will create and update the filter in EasyList filter-list, which will benefit all the users.

**Comment by IDKwhattoputhere** [comment]
Maybe you want to reword that title to say `songspk.live showing ads`.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Each time we provide support for an invalid issue, it sends the signal that invalid issues will be taken care anyways, and this encourages disrespecting and ignoring [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
