### ISSUE TITLE
Rutracker.org cosmetic problem in Firefox

### ISSUE THREAD

**Issue by TheFinalCut83** [gorhill/uBlock#1705]
### Describe the issue

There is a strange shift of left sidebar in Firefox with uBO only. With Adblock Plus all is correct, same as in Opera Next and Chrome 51 with uBO 1.7.4 and 1.7.2 respectively. I've disabled all the filters in uBO, leaving either Easylist or Ru AdList only, i've disabled Greasemonkey (with [RU AdList CSS Fixes](https://userstyles.org/styles/101141/ru-adlist-css-fixes)), i've disabled Firefox's privacy protection and everything except uBO and Browsec (rutracker.org has been recently forbidden in Russia).

### One or more specific URLs where the issue occurs

https://rutracker.org/forum/index.php

### Screenshot in which the issue can be seen

![1](http://i.imgur.com/EQOFAxR.jpg)
![2](http://i.imgur.com/dmUfL4c.jpg)

In Opera 37 it seems to look okay with uBO 1.7.4 and same filterlists as below
![3](http://i.imgur.com/ofR7Jq3.jpg)

### Your settings

- Firefox 47.0 and 48.0b1: 
- uBlock Origin 1.7.5rc2 and 1.7.0: 

##### Your filter lists

- uBlock filters‎
- uBlock filters – Badware risks
- uBlock filters – Privacy‎
- uBlock filters – Unbreak‎
- Adblock Warning Removal List‎
- Anti-Adblock Killer | Reek‎
- EasyList
- EasyPrivacy
- Malvertising filter list by Disconnect‎
- RUS: Adguard Russian Filter
- RUS: BitBlock List
- RUS: RU AdList

**Comment by gorhill** [comment]
Unable to reproduce using FF 46/Nightly 50 (I do not have FF 47/48).

**Comment by gorhill** [comment]
These are the filters which cause the area to be collapsed:

![a](https://cloud.githubusercontent.com/assets/585534/15967681/b9b6b0c2-2ef6-11e6-9d4b-7a076d8b2c08.png)

Since I can't reproduce, please investigate further on your side whether these filters are applied onto the page.

**Comment by TheFinalCut83** [comment]
It's my fault, sorry. Activation of cosmetic filtering helped because of this, I think
![1](https://cloud.githubusercontent.com/assets/16985985/15968365/48903c5e-2f34-11e6-8fe2-d7c171a5a7ce.jpg)
Closed.
