### ISSUE TITLE
adf.ly and q.gs blocked

### ISSUE THREAD

**Issue by footsiefellow** [gorhill/uBlock#1706]
Example: http://q.gs/AC46e

If noscript activated then: 
https://anonmgur.com/up/1bc1bc2ef6535be472b30ebf27fa3623.jpg

If noscript deactivated then:
https://anonmgur.com/up/e12f7cce4183cd25d0199b52267816f0.jpg

Hope fix thanks

**Comment by anewuser** [comment]
You've ignored and deleted the template text that appears when you create a new issue.

That text isn't there just for decoration. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
