### ISSUE TITLE
Request - not an issue

### ISSUE THREAD

**Issue by CliveBB** [gorhill/uBlock#1708]
Would be very useful if one could access the dashboard from the icon rather than having to go to
Tools > Add-ons > Extensions > uBlock origin > Preferences > Show Dashboard

Could not find a way of posting a request, sorry if I missed it.

**Comment by jjohns71** [comment]
You can access it, click the UBO icon, then click on the Title 'Ublock Origin 1.7.x'. (See red highlight in the attachment)

It will open the dashboard for you.

![capture](https://cloud.githubusercontent.com/assets/6795795/15975273/b074615c-2f1a-11e6-9aea-58de44422763.PNG)

Please mark this is closed.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
