### ISSUE TITLE
uBO's whitelist more like uBO's rules.

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#1709]
Yeah, yeah. I should request this feature on Mozilla's Discourse in the topic about uBO, but... I'm lazy guy 😛

What I mean in the title is to change how user can configure the whitelist. Currently we only need to type the address there (like `inoreader.com` or `www.inoreader.com`, or `blog.inoreader.com` [Btw., it's not an advertisement of Inoreader ;)] or specific webpage like `twitter.com/Piter432YT/status/35285729875` [Twitter link is to show, what I mean, ofc.]) and confirm the changes. However, I think the whitelisting could be better if its mechanics could be more like rules mechanics, I mean temporary (editable by users' like in rules settings) and permanent (after users' apply like in rules settings) whitelisted sites.

I hope that change (if it will be accepted by @gorhill) will not interrupt current users' whitelist settings 🤔

**Comment by anewuser** [comment]
>Yeah, yeah. I should request this feature on Mozilla's Discourse in the topic about uBO, but... I'm lazy guy :stuck_out_tongue:

Nobody deserves special treatment. This issue is going to be closed as all the other invalid posts.

**Comment by gorhill** [comment]
Rules are hostname-based. Whitelist directives are pattern-based, this does not fit rule-based syntax. I don't plan to rewrite all this.
