### ISSUE TITLE
Empty whitelist applies default whitelist

### ISSUE THREAD

**Issue by seanrand** [gorhill/uBlock#171]
Affects both latest master of uBlock Origin and uBlock.
To reproduce:
1. Apply `behind-the-scene * * noop` rule
2. Delete everything from the whitelist and apply changes
3. Open Behind the scene in request log
4. Open a GitHub tab (or any other page that uses navigator beacons)
5. Observe `https://www.google-analytics.com/collect` not being blocked in the request log
6. Add `#` to the whitelist and apply changes
7. Refresh GitHub tab
8. Observe `https://www.google-analytics.com/collect` being blocked in the request log

Without looking into it, my guess is that when the whitelist is completely empty, uBlock uses the default whitelist (with behind-the-scene whitelisted) instead.

**Comment by gorhill** [comment]
> Observe https://www.google-analytics.com/collect being blocked in the request log

I don't understand the issue.

If you comment out the whitelisting of `behind-the-scene`, it is expected `https://www.google-analytics.com/collect` will be blocked.

**Comment by gorhill** [comment]
Never mind, I read more carefully.
