### ISSUE TITLE
uBlock Origin blocks flash plugin on a website

### ISSUE THREAD

**Issue by knzudgt** [gorhill/uBlock#1711]
uBlock Origin blocks the visualisation of the player for www.supertennis.tv
I am using firefox 47.0 on a Ubuntu machine, with flash plugin version 11.2.202.621
To watch the stream I have to add the whole website to the whitelist, otherwise I am able to see only the white background

Ubuntu 14.04 LTS
uBlock Origin version: 1.7.0
Firefox version: 47.0
Flash plugin version 11.2.202.621

3rd party filters: uBlock filters +  uBlock filters – Badware risks + uBlock filters – Privacy‎ + uBlock filters – Unbreak‎ + Anti-Adblock Killer | Reek + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Malware domains‎

My filters: @@||abysstream.com/ads.js

My rules: behind-the-scene * 3p noop + behind-the-scene * 3p-frame noop

![screenshot from 2016-06-11 14 20 18](https://cloud.githubusercontent.com/assets/15718033/15985057/6e3c19ac-2fe1-11e6-9342-a466f0ca4f44.png)
![screenshot from 2016-06-11 14 21 22](https://cloud.githubusercontent.com/assets/15718033/15985058/6e3d7018-2fe1-11e6-9480-bfc742254cae.png)

**Comment by IDKwhattoputhere** [comment]
The logger shows there's a problematic filter in @reek's list.

**Comment by knzudgt** [comment]
Thanks.
Which one of the reek's list is problematic? To detect this filter am I required to open the logger with uBlock origin enabled or disabled?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
