### ISSUE TITLE
Not able to click button

### ISSUE THREAD

**Issue by 3ckH4rd** [gorhill/uBlock#1712]
Almost everytime after starting firefox and clicking the button in task menu of firefox, the button remains like you see in the pic. there is no action anymore then no matter how often i try to click the button. I always have to restart.
![bildschirmfoto 2016-06-11 um 23 24 22](https://cloud.githubusercontent.com/assets/13890764/15987560/ec0627ca-302b-11e6-975b-7c9fbe435830.png)

**Comment by gorhill** [comment]
It's not something I have ever experienced. You will have to investigate yourself, as I can't investigate what I can't reproduce. Once you make the case the issue is with uBO itself, and not something on your side interfering with your uBO's installation, I will re-opened.

**Comment by 3ckH4rd** [comment]
Hi,
I found the reason. As soon as I activate this addon:

https://addons.mozilla.org/de/firefox/addon/hide-tab-bar-with-one-tab/

The uB Icon on the panel doesnt work properly anymore. But only when you open firefox with only 1 tab so for opening the uB settings, firefox has to open a new tab.

Can you reproduce the bug?

I guess this is a bug of "Hide Tab bar with one tab"?

Thanks!

**Comment by gorhill** [comment]
I still can't reproduce after installing <https://addons.mozilla.org/de/firefox/addon/hide-tab-bar-with-one-tab/>, and having only one tab opened.

**Comment by gorhill** [comment]
In `bout:config`, do you have the setting `extensions.ublock0.forceLegacyToolbarButton` set to `false`?

**Comment by 3ckH4rd** [comment]
yes, set to false
