### ISSUE TITLE
non permanent statics filters

### ISSUE THREAD

**Issue by laozi83** [gorhill/uBlock#1714]
Hello
apologies if this is not the right place to pos tbut I can not find the right place
configuration: Windows 7 32B, FireFox 47.0, ublock O 1.7.0
with the eyedropper tool, I have edited some pages of weather site to view the essential,
but I note that randomly after an indeterminate time one appears more correctly,
only an upper apron and some data will be displayed!
attached generated statics filters and to avoid these annoyances have you a solution?

the 4 sites referenced:
http://france.lachainemeteo.com/meteo-france/ville/previsions-meteo-draguignan-1596-0.php
http://montagne.lachainemeteo.com/meteo-alpes-du-sud/station-montagne/previsions-meteo-isola-2000-282-0.php
http://montagne.lachainemeteo.com/meteo-alpes-du-nord/station-montagne/previsions-meteo-les-deux-alpes-228-0.php
http://montagne.lachainemeteo.com/meteo-alpes-du-sud/station-montagne/previsions-meteo-orcieres-merlette-249-0.php

My statics filters:
! 12/06/2016 à 05:56:06 http://france.lachainemeteo.com/meteo-france/ville/previsions-meteo-draguignan-1596-0.php
||image.lachainemeteo.com/images/lachainemeteo2013/habillage/fonds/fond_header3.png?ts=cmp$image
france.lachainemeteo.com##body > div:nth-of-type(6)
||image.lachainemeteo.com/images/lachainemeteo2013/habillage/pictos/menu/fond_menu-lcm.jpg$image
france.lachainemeteo.com###bandeau_meteolive
france.lachainemeteo.com###bloc_prevision > div:nth-of-type(1)
france.lachainemeteo.com###conteneur_principal > .fil_ariane > .fildariane > div
france.lachainemeteo.com###conteneur_principal > .fil_ariane
||image.lachainemeteo.com/images/publicator_2009/videotheque/publie/lcm_quotidien/vignette/REGION_R0017_moy.jpg$image
france.lachainemeteo.com###conteneur_principal > .zone:nth-of-type(5) > .colonne_droite:nth-of-type(3) > div > .liste_conteneur > .liste_element > .element_grand
france.lachainemeteo.com###conteneur_principal > .zone:nth-of-type(5) > .colonne_droite:nth-of-type(3) > div > .liste_conteneur
france.lachainemeteo.com###conteneur_principal > .zone:nth-of-type(5) > .colonne_droite:nth-of-type(3) > div > .barre_titre
! 12/06/2016 à 07:15:30 http://montagne.lachainemeteo.com/meteo-alpes-du-sud/station-montagne/previsions-meteo-isola-2000-282-0.php
||image.lachainemeteo.com/images/lachainemeteo2013/habillage/fonds/fond_header3.png?ts=cmp$image
montagne.lachainemeteo.com##body > div:nth-of-type(6)
montagne.lachainemeteo.com###bandeau_meteolive
||image.lachainemeteo.com/images/lachainemeteo2013/habillage/fonds/habillage_montagne_ete_hph.png$image
montagne.lachainemeteo.com###bloc_prevision > div:nth-of-type(1)
montagne.lachainemeteo.com###bloc_prevision > div:nth-of-type(2)
montagne.lachainemeteo.com###conteneur_principal > .zone:nth-of-type(5) > .colonne_droite:nth-of-type(3) > div > .liste_conteneur > .liste_element > .element_grand
montagne.lachainemeteo.com###conteneur_principal > .zone:nth-of-type(5) > .colonne_droite:nth-of-type(3) > div > .liste_conteneur
montagne.lachainemeteo.com###conteneur_principal > .zone:nth-of-type(5) > .colonne_droite:nth-of-type(3) > div > .barre_titre
montagne.lachainemeteo.com###conteneur_principal > .fil_ariane > .fildariane > div
montagne.lachainemeteo.com###conteneur_principal > .fil_ariane

Thanks for your lighting
merci et cordialement

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
