### ISSUE TITLE
Add these filters in EasyList

### ISSUE THREAD

**Issue by rajatmathurs** [gorhill/uBlock#1715]
Hi,

`www.songspk.live###nopop`  this will remove the blank space showing on the mobile site

`phonearena.com##.s_mb_15 `   this will remove the blank space showing on the mobile site
` phonearena.com##.s_w_300`    this will remove the blank space showing on the mobile site

`mymp3song.info###mainDiv > a[href^="http://c.ketads.com/site/click"]` this will remove the "Click Here" add showing on the mobile site

Please add the above filters in EasyList

Thanks a lot

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
You keep opening invalid issues.

**Comment by IDKwhattoputhere** [comment]
https://forums.lanik.us/viewforum.php?f=62
