### ISSUE TITLE
Logger & Dynamic filtering pane doesn't show some domain.

### ISSUE THREAD

**Issue by quroe** [gorhill/uBlock#1718]
### Describe the issue
When I open site with leftclick,uBO doesn't show some domain.
(hp.com,justsystem.com,justsystem.co.jp,pc-koubou.jp,sofmap.com,st-hatena.com)
I checked this issue by Firefox & PaleMoon.

### One or more specific URLs where the issue occurs
https://duckduckgo.com/?q=http%3A%2F%2Fskyline798.blog118.fc2.com%2F&ia=web
http://skyline798.blog118.fc2.com/

### Steps for anyone to reproduce the issue
1. Lauch Firefox with new profile.
2. Paste "about:config" in adress bar.
3. Change "xpinstall.signatures.required" to "false".
4. Install uBlock Origin.
5. Open new tab.
6. Paste "https://duckduckgo.com/?q=http%3A%2F%2Fskyline798.blog118.fc2.com%2F&ia=web" in adress bar.
7. Open Logger.
8. MiddleClick "http://skyline798.blog118.fc2.com/".
9. LeftClick "http://skyline798.blog118.fc2.com/".

8 shows all domains,but 9 doesn't show some domain.

### Your settings
uBlock Origin : default settings
Firefox : xpinstall.signatures.required:false
- Browser/version: Firefox 47.0 x86
- uBlock Origin version: 1.7.5 rc4
- Windows7 x64

##### Your filter lists
Default filter lists

**Comment by gorhill** [comment]
I can't see none of the hostnames you enumerate<sup>[1]</sup> in the logger for `http://skyline798.blog118.fc2.com/` whether the page is loaded through middle or left click.

[1] `hp.com`, `justsystem.com`, `justsystem.co.jp`, `pc-koubou.jp`, `sofmap.com`, `st-hatena.com`.

**Comment by gorhill** [comment]
Please make the case that these hostnames do appear on the web page -- for example use the dev tool's _Network_ pane to obtain more details about these hostnames.

**Comment by gorhill** [comment]
Forcing a simple reload, I can see these hostnames in the _Network_ pane.

Investigating.

**Comment by gorhill** [comment]
Ok, in my first attempt to reproduce I was clicking on the wrong link in Duck Duck Go results.

I followed the steps carefully, and I can reproduce. Observations:

- It does not matter left- or middle-click, what matters is whether the web page had been previously loaded.
- uBO's logger output matches that of the _Net_ pane in the browser console, and also that of the _Network_ pane in the page console -- meaning Firefox does not connect to these missing hostnames in the first place.

uBO will show you everything which goes through its HTTP observer. In the current case, the missing hostnames are missing because the browser does not connect to these hostnames.

**Comment by quroe** [comment]
>Please make the case that these hostnames do appear on the web page -- for example use the dev tool's Network pane to obtain more details about these hostnames.
I tried steps 1-7 & 9.
Logger shows all domains.
When I tried 8,web page's image was cached.
So Logger doesn't show cached image logs at 9.
I misunderstand logger also shows cached contens.
Sorry,gorhill.

**Comment by gorhill** [comment]
> I misunderstand logger also shows cached contents

On Chromium it would -- as `chrome.webRequest.onBeforeRequest` would be called even for cached content. However it appears on Firefox `http-on-modify-request` (or even `http-on-opening-request`) is not called for cached content.

I believe it would be possible for uBO to report cached content in the logger, I would need to dig into FF API (maybe through [`http-on-examine-cached-response`](https://developer.mozilla.org/en-US/docs/Observer_Notifications#HTTP_requests)). I want to look into this.

**Comment by gorhill** [comment]
Turns out `http-on-examine-cached-response` is no solution.

**Comment by quroe** [comment]
I'm sad t hear that...
I'll use reloading page :)
Thank you very very much!
