### ISSUE TITLE
translation consistency/Documentation translation

### ISSUE THREAD

**Issue by treaki** [gorhill/uBlock#1719]
Hi Folks,

first of all thank you for your very good work with uBlock. But as i am getting used / working in to it i have one particular problem: Language inconsistency. I have opened the settings and i see, which is very good, that after eny important setting is an (i) icon with is linked to the matching section in the documentation. All that settings in thad configuration view are infact very good translated in my motherlanguage. But if i click on one of this information icons i get linked to the documentation which is completely written in English.

So out of my perspective: ive got no problem with sufficient english software, i also got no problems with sufficient german software. But what i hate is what i call "inconstant translation/language inconsistence".

So as Richard Stallman sad, "software is not complete without documentation" (or so), in my opinion good documentation should be a part of good software...

So i would be very happy if the documentation could be translated to. I have seen that your translation is working through Crowdin so i guess it wouldn't be a big deal including the documentation in there for getting translated. And if i find time i could also try to help with the german translation...

Otherwise it would be good if i could switch the plugins language to english.

regards

treaki

**Comment by gorhill** [comment]
> if i find time i could also try to help with the german translation

Translate documentation pages, and I will provide links at the top  in the corresponding main wiki English pages to the available translations.
