### ISSUE TITLE
WebRTC IP leaking when in Settings "Prevent WebRTC from leaking local IP addresses" is enabled?

### ISSUE THREAD

**Issue by secureemail** [gorhill/uBlock#1720]
### Describe the issue
Not sure what is going on, but when you go to:
https://diafygi.github.io/webrtc-ips/
or
https://www.privacytools.io/webrtc.html
it shows my IP under "Your public IP addresses: ".

But uBlock Origin is supposed to disable WebRTC IP leaking when in Settings "Prevent WebRTC from leaking local IP addresses" is enabled?, but this doesn't work. What works is if I set manually in `about:config` `media.peerconnection.enabled` to `false`.

- Browser/version: Latest Firefox.
- uBlock Origin version: 1.7.0

**Comment by gorhill** [comment]
> it shows my IP under "Your public IP addresses:"

The IP that is shown, is it your public IP?

**Comment by gorhill** [comment]
> uBlock Origin is supposed to disable WebRTC IP leaking

No, the setting says clearly "local IP addresses", not just "IP addresses". It seems you misunderstood what the feature does.

**Comment by secureemail** [comment]
> The IP that is shown, is it your public IP?
The IP is my public IP. (If I set media.peerconnection.enabled to false nothing is shown.)

**Comment by secureemail** [comment]
> No, the setting says clearly "local IP addresses", not just "IP addresses". It seems you misunderstood what the feature does.

Ok, so this means that I still have to manually set media.peerconnection.enabled to false?

**Comment by gorhill** [comment]
> If I set `media.peerconnection.enabled` to false nothing is shown.

Yes, because WebRTC is completely disabled. The setting in uBO is not _"Disable completely WebRTC"_, it's _"Prevent WebRTC from leaking local IP addresses"_.

Try <https://ipleak.net/>. Your public IP is shown at the top, this won't be hidden by uBO, you need a VPN/proxy/Tor browser for this.

**Comment by secureemail** [comment]
It's weird because it's suggested here https://www.bestvpn.com/blog/31048/the-webrtc-vpn-bug-and-how-to-fix-it/ (see under "Fixes") The desciptions does not clearly differentiate between pub and local. Alright, I guess it's indeed not bug then.

**Comment by gorhill** [comment]
Note that if you are behind a VPN, your ISP-provided IP address will cease being public -- in such case your ISP-provided IP address will no longer be available, including through WebRTC.

Before FF 42, uBO was setting `media.peerconnection.enabled` to `false`. With FF 42 and above, it has [become possible to prevent local IP address leakage without disabling WebRTC](https://github.com/gorhill/uBlock/issues/894).

The key concept here "**local** IP address leakage" -- this is what the setting prevents.

**Comment by secureemail** [comment]
This is sufficient then, right? Does it still make sense to do manually `media.peerconnection.enabled` to `false` in any case?

**Comment by gorhill** [comment]
> The desciptions does not clearly differentiate between pub and local.

It does. What the article calls _"true IP address"_, I call _"ISP-provided IP address"_.

The unambiguous expression is _"public IP address"_, the one IP address which is understood to be internet-facing. Normally that is from your ISP. If using a VPN, that will be that of your VPN provider. If using Tor browser, that will be that of a Tor exit node. These are public IP addresses, and are not meant to be hidden by uBO. All other IP addresses than the your current public IP address will be prevented from leaking through WebRTC when the setting in uBO is enabled.

> Does it still make sense to do manually media.peerconnection.enabled to false in any case?

If you want to completely disable WebRTC, you are free to do so -- uBO won't touch this setting for FF 42+, and will leave it unchanged if already set to `false` by the user for older versions of FF.

**Comment by gorhill** [comment]
The test I provide in the documentation test is what tells whether the WebRTC setting in uBO works properly: <https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/>. Click _"Gather candidates"_ at the bottom. If local IP addresses are prevented from leaking though WebRTC, then the only IP address shown should your current public IP address (ISP or VPN, Tor, etc.) which you can see at the top of <https://ipleak.net/>.

**Comment by secureemail** [comment]
Ok, thanks.
