### ISSUE TITLE
Yandex Browser Turbo Mode Issue

### ISSUE THREAD

**Issue by linuxtopia** [gorhill/uBlock#1722]
### Yandex Browser Turbo Mode Issue

Problem occurs on Yandex Browser's settings panel

### Screenshot in which the issue can be seen

<blockquote class="imgur-embed-pub" lang="en" data-id="sOqGHkZ"><a href="//imgur.com/sOqGHkZ">Yandex Browser uBlock Origin Issue</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

### Detailed Information on the Issue

As you see the image's content is on Turkish language because I use Yandex Browser in Turkey. If I translate the problem roughly:

- To load the pages fast then request their data early.

Error message says that:

-That setting is controlled by that extension:

So this error occurs in Yandex Browser because of the uBlock Origin. How to solve that problem? I generally use YB in Turbo Mode to compress my data.

Thanks.

**Comment by IDKwhattoputhere** [comment]
The setting marked in your screenshot doesn't compress data. It actually wastes data. It's disabled for privacy reasons.

**Comment by gorhill** [comment]
If you do not want uBO to disable pre-fetching, un-check the box in the _Settings_ pane.

**Comment by gorhill** [comment]
Note that this is not an "error message", this is the browser informing you that uBlock Origin controls this setting.
