### ISSUE TITLE
 右键屏蔽元素导致页面卡住且右下键不能出现屏蔽自定义规则

### ISSUE THREAD

**Issue by liangshengzero** [gorhill/uBlock#1725]
![ashampoo_snap_2016 06 16_13h16m03s_001_](https://cloud.githubusercontent.com/assets/17328925/16106148/88d02cb8-33c4-11e6-9172-0ba8cce15cab.jpg)
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs
http://www.bilibilijj.com/

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

chrome 51.0.2704.84 (64-bit)

- uBlock Origin version: 1.7.2

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
`bilibilijj.com##.BV91255`

**Comment by seanrand** [comment]
@gorhill when selecting that image with the element picker, the tab is unresponsive for up to a minute before the element picker dialog appears. Maybe that's what OP wanted to point out. No obvious errors in the console though.

![screenshot-20160616t150320](https://cloud.githubusercontent.com/assets/929479/16117722/bec278da-33d3-11e6-8454-efcfc1d42e4d.png)

**Comment by gorhill** [comment]
> the tab is unresponsive for up to a minute before the element picker dialog appears

I noticed the delay (a few seconds here). The selected image is a `data:` encoded image which is over 900,000+ bytes.

**Comment by gorhill** [comment]
"longht"... ugh.

**Comment by gorhill** [comment]
Actually, maybe the issue is that when selecting the suggested `data:` network filter, uBO won't remove the image. I will assume this is the filed issue.

**Comment by seanrand** [comment]
> "longht"... ugh.

Heh.

Also, no more delay here with that commit in place.

**Comment by gorhill** [comment]
`data:` URI-based resources should not be suggested as static network filters in the first place, a more appropriate cosmetic filter should be suggested instead.
