### ISSUE TITLE
*$third-party filter blocking display of 1st party content on Pale Moon

### ISSUE THREAD

**Issue by 0strodamus** [gorhill/uBlock#1726]
OS: Arch Linux x64
Browser/version: Pale Moon 26.2.2
uBlock Origin version: 1.7.5rc5

Issue:
1st party content not displayed on webpage when `*$third-party` rule is used. This content is shown in the logger as being allowed.

Issue reproduction:
1) create single uBlock Origin rule *$third-party
![rule](https://cloud.githubusercontent.com/assets/18707615/16135635/ddb0c660-33d9-11e6-9ad7-ca1e4373ca86.png)

2) navigate to site http://www.blabbermouth.net/
3) logger will show 1st party images as being allowed, but the images are blocked on the webpage
![log](https://cloud.githubusercontent.com/assets/18707615/16135680/24d89914-33da-11e6-9942-72828f0cb7fc.png)

![webpage](https://cloud.githubusercontent.com/assets/18707615/16135644/eae94294-33d9-11e6-86ed-e4ba5fb44568.png)

Resolution:
revert the following deletions made to messaging.js in version rc5:
`// https://github.com/gorhill/uBlock/issues/978
// Ignore invalid URLs: these would not occur on the HTTP
// observer side.
if ( (context.requestHostname = hostnameFromURI(request.url)) === '' ) {
    continue;
}`

I noticed that successive page reloads rarely caused the elements that were not displayed to vary, so maybe this is another [timing issue](https://github.com/gorhill/uBlock/issues/1702)?

**Comment by gorhill** [comment]
> maybe this is another timing issue?

No, it's just a gorhill-being-stupid issue. Sorry about this, will release a fix asap.

**Comment by 0strodamus** [comment]
gorhill, you're the best - no need to apologize. Thanks for creating and sharing your extensions!
