### ISSUE TITLE
Problem with Specific Site (HWzone.co.il)

### ISSUE THREAD

**Issue by Sarm1X** [gorhill/uBlock#1728]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Page is not loading on site, loading infintly (White screen)

Not happens with ABP.

### One or more specific URLs where the issue occurs
HWzone.co.il

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

**?**

### Your settings

- Browser/version: Firefox - 47
- uBlock Origin version: 1.7.0

##### Your filter lists
Defualt filters + Anti-Adblock (script + filter), Easylist, peter lowe's, easyprivacy, malware domains + domain list And Fanboy+Easylist Merged Ultimate list.

##### Your custom filters (if any)

! 5.3.2016, 22:46:43 http://www.fxp.co.il/showthread.php?t=16643392
www.fxp.co.il###left_nav_arrow

! 5.3.2016, 22:46:48 http://www.fxp.co.il/showthread.php?t=16643392
www.fxp.co.il###right_nav_arrow

! 6.3.2016, 8:59:48 https://hwzone.co.il/
hwzone.co.il###td-outer-wrap > .td-content-wrap.td-transition-content-and-menu > .td-header-style-12.td-header-wrap > .td-banner-wrap-full.td-header-header-full > .td-header-header.td-header-row.td-container-header > .td-header-sp-recs > .td-header-rec-wrap

! 6.3.2016, 8:59:58 https://hwzone.co.il/
hwzone.co.il###td-outer-wrap > .td-content-wrap.td-transition-content-and-menu > .td-header-style-12.td-header-wrap > .td-banner-wrap-full.td-header-header-full > .td-header-header.td-header-row.td-container-header > .td-header-sp-recs

! 23.3.2016, 21:00:15 https://www.fxp.co.il/showthread.php?t=17110924
||images.fxp.co.il/adsgolan/iss/asp/b.php?d=1

! 30.5.2016, 10:49:54 https://hwzone.co.il/
hwzone.co.il###td-outer-wrap > .td-header-style-12.td-header-wrap > .td-banner-wrap-full.td-header-header-full > .td-header-header.td-header-row.td-container-header > .td-header-sp-recs

Thats it, hope you look into it. :)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Site loads fine with default settings -- so default is to assume a filter issue, which must not be filed here, as stated in CONTRIBUTING.
