### ISSUE TITLE
Tabs being closed automatically (related to uBlock #1051?)

### ISSUE THREAD

**Issue by bjvandrews** [gorhill/uBlock#173]
Encountering bug similar to the closed/fixed bug [#1051 in uBlock](https://github.com/chrisaljoudi/uBlock/issues/1051) in uBlock Origin 0.9.6.0.

When attempting to open some RSS-feed links on inoreader.com I've encountered a problem with the tabs automatically being closed by uBlock Origin, despite my intentionally opening them. This does not occur when uBlock Origin is disabled. Using Google Chrome Version 42.0.2311.135 m (all other extensions disabled) with uBlock Origin 0.9.6.0 (default settings) on Windows 8.1 (up-to-date).

Repro:
Visit the [Slashdot Feed](https://www.inoreader.com/feed/http%3A%2F%2Frss.slashdot.org%2FSlashdot%2Fslashdot) on inoreader.
Click a story heading so it opens the summary.
Click the title so it opens the slashdot.org url in a new page.
Observe that the page closes shortly after opening when uBlock is enabled. This does not occur with uBlock disabled.

**Comment by gorhill** [comment]
I can't reproduce with default settings.

Might be related to: <https://adblockplus.org/forum/viewtopic.php?f=2&t=30156>.

Force an update of EasyList and see if this still happen.

**Comment by gorhill** [comment]
Actually I confirm this is the issue by the look of the bad filter and the content of the logger. So force an update of EasyList.
