### ISSUE TITLE
Ublock can't block adblocker and popup

### ISSUE THREAD

**Issue by X1z1** [gorhill/uBlock#1731]
### One or more specific URLs where the issue occurs
fullpremiums.com/index.php

### Describe the issue / Steps for anyone to reproduce the issue
1) when i open the site i get "please disable your adblocker" and it use a random div that you can't block (note that i allow fullpremiums.com/adblock.js in filters)
2) when i insert a link in "Enlace a transferir:" and then i click on  "transferir archivo" open a popup that i can't block

I see old issues and i try fullpremiums.com##script:inject(overlay-buster.js) but don't work

### Screenshot in which the issue can be seen
http://img231.imagevenue.com/img.php?image=01377_00042421_122_450lo.jpg
(I upload screenshot here because i get an error when i try to attach)

### Your settings
- Browser/version: 
Firefox 45.2 esr
- uBlock Origin version: 
1.7.0

### Your filter
Default filter lists + all privacy list + hphosts + mvps +
||cualesmiip.biz
||fkref.com
||fullpremiums.com/templates/plugmod/images/a.png
||miips.net
||myips.us
@@||fullpremiums.com/adblock.js

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
