### ISSUE TITLE
"Purge all caches" does not purge EasyList Hebrew

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#1733]
### Describe the issue
Pressing "Purge all caches" purges all my lists except EasyList Hebrew.

### Steps for anyone to reproduce the issue
Press "Purge all caches".

### Your settings
"Disable hyperlink auditing/beacon" is unchecked.

- Browser/version: 
Firefox 47.
- uBlock Origin version: 
1.7.5rc6

##### Your filter lists
uBlock filters, uBlock filters – Unbreak‎, EasyList, EasyList Hebrew

**Comment by gorhill** [comment]
Works fine here. How did you come to the conclusion that the filter list's cache is not purged?

**Comment by Yaron10** [comment]
Hello gorhill,

I never see "New Version Available" or "Out of Date" next to EasyList Hebrew.
This is consistent.

If I press "Purge cache" next to EasyList Hebrew, I do get one of the indications.

Thank you.

**Comment by gorhill** [comment]
> I never see "New Version Available" or "Out of Date" next to EasyList Hebrew.
> This is consistent.

Maybe because when you look at it, the filter list has been updated in the last 4-5 days?

**Comment by Yaron10** [comment]
1) In other lists I see "Out of Date" whenever I "Purge all caches" (i.e. regardless of recent updates).
2) Why do I get one of the indicators when pressing "Purge cache" next to EasyList Hebrew but not on "Purge all caches"?

Thanks again.

**Comment by Yaron10** [comment]
One more comment:
I'm sure it used to work properly. Could it possibly have to do with the recent new EasyList Hebrew links?

**Comment by gorhill** [comment]
> Could it possibly have to do with the recent new EasyList Hebrew links?

You will get the same result with any other filter lists which are only available on a remote server. uBO's own filter lists, and other default filter lists have an installation copy, so uBO is able to tell whether these filter lists are obsolete or not.

All other filter lists are fetched from a remote server only, and uBO can only _guess_ that they are out of date.

If there is an issue here, it's that clicking _"purge cache"_  should not cause the label "new version available"_ to appear for filter list which can only be fetched from a remote server -- the filter list will be downloaded from that server regardless.

**Comment by Yaron10** [comment]
Thanks for the detailed explanation.

I've just tested it again.
1) Press "Purge cache" next to EasyList Hebrew ("New Version Available").
2) Update.
3) Press again "Purge cache" next to EasyList Hebrew ("New Version Available").

BR

**Comment by gorhill** [comment]
I changed the behavior of the "purge cache" button: purely external the filter list won't be marked with "new version available" when their cache is purged, because there is no local copy against which to compare, as external the filter list are always downloaded from a remote server.

**Comment by Yaron10** [comment]
Hello gorhill,

Thank you very much for the quick fix.

So "New Version Available" should not be added whether I press "Purge all caches" or "Purge cache" next to a local list.
However  "Out of Date" should be added only on "Purge cache" next to a local list.

Is that correct?

BR

**Comment by gorhill** [comment]
"new available version"<sup>[1]</sup> or "out of date"<sup>[2]</sup> may be added to locally available filter lists when you click "purge cache".

This won't happen however for filter lists not available locally.

[1] uBO knows for sure there is a new version available to download.
[2] uBO guesses a newer version is available on the remote server.

**Comment by Yaron10** [comment]
Thanks again.
I do appreciate your great work.

BR
