### ISSUE TITLE
data:text/html 

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#1735]
I noticed there are many sites now that the first click you
do on the page it makes you open an other tab or pop-up. The pop-up/tab
is almost always closed immediately by ublock but is it possible to
disable that tab/pop-up from ever opening? Thanks for your time.

Example: http://animeflv.net/ or http://gorillavid.in/anq4ij0u58ug1

I'm using firefox 45 ESR x64 on W7 x64

The pop-ups and tabs that open have this format:
data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD52YXIgZXBvY2ggPSBuZXcgRGF0ZSgpLmdldFRpbWUoKTt2YXIgX2Vwb2NoRnJvbVdpbmRvd05hbWUgPSB3aW5kb3cubmFtZS5zcGxpdCgnXycpWzNdO2lmKGVwb2NoIC0gX2Vwb2NoRnJvbVdpbmRvd05hbWUgPCAyNTApe3dpbmRvdy5sb2NhdGlvbj0nJzt9PC9zY3JpcHQ+PC9ib2R5PjwvatbD4=

I tried ||data:text/html^$popup to prevent it for opening but it's the same.

I have the default options enabled with anti adblock killer, spa, malaware domains, easy privacy, easy list all the ublock filters minus experimental.

**Comment by gorhill** [comment]
> is it possible to disable that tab/pop-up from ever opening?

Not really. As shown in uBO's logger, a new tab with the URL `about:blank`, then the real URL `http://animeflv.net/_a:` is used, which itself redirect to `firegetbook.com`, which is the one filtered as a popup.

You can use the no-popups switch for that site to have the popups closed earlier, but this still won't prevent the tab from opening. Custom filter `||animeflv.net/_a:$popup` will also cause the tab to be closed earlier, maybe `||animeflv.net/_a:$popup,document` might be better.

**Comment by rayman89** [comment]
Thank you.

**Comment by gorhill** [comment]
In light of this [new ABP issue](https://issues.adblockplus.org/ticket/4417), I decided to run some tests with both Firefox and Chromium to see if I could intercept these `data:` URL. Turns out, I can.

**Comment by rayman89** [comment]
Thanks a lot. Do we need to add the data:text/html;base64$popup or something for it to work?

**Comment by gorhill** [comment]
> Do we need to add the `data:text/html;base64$popup` or something for it to work?

Turns out there is already such a filter in EasyList. But it doesn't work in Chromium because <https://forums.lanik.us/viewtopic.php?f=62&t=32826>. Until it is fixed, you may want try `data:$popup`.
