### ISSUE TITLE
Provide alternative way in picker to block by dimensions

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1736]
Currently, when using the element picker it usually blocks cosmetic elements by the element names. 

Is it possible to add an additional way in the element picker to block by automatically determining dimensions and block using the element selection methods e.g.

```
##div[style="width:300px;height:250px;"]
##table[height="100"][width="100"]
```

This would also help block most uniquely generated cosmetic elements

**Comment by elypter** [comment]
i think its possible to do this with xpath but it doesnt work in the picker

**Comment by gorhill** [comment]
There is no reason to use xpaths [when plain CSS selectors can do the job](https://github.com/gorhill/uBlock/releases/tag/1.8.0):

> When it comes to cosmetic filtering, preferably, always favor a plain old CSS3-based cosmetic filter, since they can be used in a declarative way, inside a `style` tag.

**Comment by gorhill** [comment]
I will only consider requests by volunteers with a long track record of maintaining filter lists.
