### ISSUE TITLE
Google Analytics Surrogate broken on WillyWeather.com.au

### ISSUE THREAD

**Issue by fuzzyroddis** [gorhill/uBlock#1737]
http://www.willyweather.com.au/

Steps: Type in Sydney in the location box.

Should Happen: Dropdown with locations appears
Result: ```nation.1-5-3.js:931 Uncaught ReferenceError: ga is not definedonTrackAndThrow @ nation.1-5-3.js:931dispatch @ nation.1-5-3.js:3r.handle @ nation.1-5-3.js:3trigger @ nation.1-5-3.js:3searchCallback @ nation.1-5-3.js:911(anonymous function) @ nation.1-5-3.js:857j @ nation.1-5-3.js:2fireWith @ nation.1-5-3.js:2x @ nation.1-5-3.js:4(anonymous function) @ nation.1-5-3.js:4```

### Your settings
- Browser/version: Chrome 51.0.2704.103
- uBlock Origin version: 1.7.2
- HTTPS Everywhere 2016.6.9

##### Your filter lists

<img width="586" alt="screen shot 2016-06-20 at 4 46 21 pm" src="https://cloud.githubusercontent.com/assets/2271265/16185368/9e690c58-3706-11e6-8235-97f50e6e4b71.png">

##### Your custom filters (if any)
||internaldomain.example/image.jpg

**Comment by gorhill** [comment]
There is no surrogate for `googletagmanager.com/gtm.js`, so this is a 3rd-party filter list issue, you must report it to EasyPrivacy maintainers, they will need to create an exception for the site, like `@@||googletagmanager.com/gtm.js?$domain=willyweather.com.au`.

Paging @ryanbr.

**Comment by fuzzyroddis** [comment]
@gorhill I suspect this would be related https://forums.informaction.com/viewtopic.php?f=7&t=20804
It was fixed by adding using the Google Analytics Surrogate for gtm.js
