### ISSUE TITLE
Injected ads are not blocked on a website.

### ISSUE THREAD

**Issue by shinycake** [gorhill/uBlock#1738]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Some ads are not blocked and are "immune" to element picker blocking as well.
only happens in [this website](http://www.mako.co.il/) when you click on a story.

### One or more specific URLs where the issue occurs
http://www.mako.co.il/news-law/crime-q2_2016/Article-2b11a7fad8c6551004.htm?sCh=3d385dd2dd5d4110&pId=1898243326
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
screenshots:
http://imgur.com/a/D10xv

short clip demonstrating element picker blocking attempts:
https://vid.me/Q5ep
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. go to mako.co.il
2. click on the main story
3. sometimes it take those ads a few seconds to load
4. try to block using the element picker.

### Your settings

[my settings](http://i.imgur.com/3GRi0xX.png)

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Opera 38 (also occurs in chrome and firefox, i've only managed to reproduce in firefox and only to some extent).
- uBlock Origin version: 1.7.4
##### Your filter lists

Default lists + new Hebrew List

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

custom filters:

! 5/4/2016, 6:25:31 PM https://www.google.com/search?client=opera&q=opera+turbo&sourceid=opera&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=VhQqV9rpBtHb8AfJpYvYCA
www.google.com###gbw > div > .gb_T.gb_gf.gb_R.gb_hf.gb_cb > .gb_R.gb_hf.gb_dc > .gb_g.gb_wc.gb_yc.gb_xc > .gb_g.gb_ga

! 5/5/2016, 9:42:23 AM http://www.geektime.co.il/24-million-gmail-accounts-breached/
||www.geektime.co.il/wp-content/themes/geektime/css/images/popup_bg.png$image

! 5/5/2016, 9:42:33 AM http://www.geektime.co.il/24-million-gmail-accounts-breached/
www.geektime.co.il###main-content > .popup__main_hidden

! 5/5/2016, 9:43:53 AM http://www.haaretz.co.il/
||www.haaretz.co.il/htz/images/popup/popup-weekly.jpg$image

! 5/5/2016, 9:44:01 AM http://www.haaretz.co.il/
www.haaretz.co.il##.modal-wrapper--dark.modal-wrapper--fixed.modal-wrapper

! 5/5/2016, 9:44:08 AM http://www.haaretz.co.il/
www.haaretz.co.il##.footer-ruler

! 5/6/2016, 12:20:49 PM http://www.themarker.com/hrtz/1.2936038
www.themarker.com###top-prom-ban > div > .island--flush.promo

! 5/17/2016, 9:40:07 PM https://imgur.com/gallery/Spbad
||s.imgur.com/images/house-cta/cta-icymi-form.png?1440530195$image

! 5/17/2016, 9:40:14 PM https://imgur.com/gallery/Spbad
imgur.com###cta-container > .cta-background

! 5/17/2016, 9:40:25 PM https://imgur.com/gallery/Spbad
imgur.com###cta-container

! 5/22/2016, 10:53:59 PM http://www.haaretz.com/world-news/u-s-election-2016/1.720720
www.haaretz.com##.footer-ruler

! 5/31/2016, 10:49:35 AM http://www.mako.co.il/
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/4/2016, 1:41:05 PM http://www.mako.co.il/
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/7/2016, 4:15:22 PM http://www.mako.co.il/
||img.mako.co.il/2016/06/07/Banner_960x48-min_01.jpg$image

! 6/17/2016, 11:14:09 PM http://www.mako.co.il/
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/17/2016, 11:14:16 PM http://www.mako.co.il/
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/20/2016, 11:30:30 AM http://www.mako.co.il/
www.mako.co.il###VideoVideo

! 6/20/2016, 11:30:55 AM http://www.mako.co.il/news-law/crime-q2_2016/Article-2b11a7fad8c6551004.htm?sCh=3d385dd2dd5d4110&pId=1898243326
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/20/2016, 11:39:29 AM http://www.mako.co.il/news-law/crime-q2_2016/Article-2b11a7fad8c6551004.htm?sCh=3d385dd2dd5d4110&pId=1898243326
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/20/2016, 11:39:38 AM http://www.mako.co.il/news-law/crime-q2_2016/Article-2b11a7fad8c6551004.htm?sCh=3d385dd2dd5d4110&pId=1898243326
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

! 6/20/2016, 11:39:44 AM http://www.mako.co.il/news-law/crime-q2_2016/Article-2b11a7fad8c6551004.htm?sCh=3d385dd2dd5d4110&pId=1898243326
javascript:"<html><body style=%27background:transparent%27></body></html>"$domain=www.mako.co.il,subdocument

**Comment by idanbirman** [comment]
reinstalled uBlockOrigin, made sure no custom filters are populated, checked the EasyList Hebrew list and updated.

went on that website and:

http://imgur.com/a/EMtnm

**Comment by gorhill** [comment]
I am unable to reproduce.

Maybe:

- The site serves a different page according to IP.
- Something else on your computer is injecting these ads.
- Your ISP is injecting these ads.

**Comment by idanbirman** [comment]
> The site serves a different page according to IP.

I've tried accessing the website via a VPN and the ads were showing, so probably not IP related?

> Something else on your computer or browser is injecting these ads.

Doubtful, but even if true, why would it only inject ads to that particular website?

> Your ISP is injecting these ads (try the HTTPS version: https://www.mako.co.il/).

I think this is it. adblock and adblock plus also failed to block the ads. the https version doesn't show ads on the homepage but the articles load broken. when connecting via a mobile hotspot no ads were displayed.

Apparently content blockers on safari are able to block these ads.

In any case, I'm terribly sorry for wasting your time. thanks for all the hard work you do!

**Comment by hairycactus** [comment]
Clicking on any article at http://mako.co.il, I do get an advert on each page. But the advert is not at the top (unlike in _ghost_'s [screenshot](https://i.imgur.com/nqKOFTk.png)), but within a slider-type holder somewhere at the bottom right-hand side [[screenshot](https://i.imgur.com/IbShUo5.png)] of the page. At the time of testing, it was always supermarket products regardless of which page I load, & the adverts link to the same Israeli supermarket website.

As _ghost_ had reported, the advert seems to be resistant to uBO's element picker. Using the element picker on the same advert merely uncovers multiple, never-ending "layers" of different supermarket products interspersed by blank element-holders. (Ironically enough, the topmost advert is always the _Vanish_ brand of clothes bleach.)

> **ghost**: _the https version doesn't show ads on the homepage but the articles load broken_

Same experience here. The HTTPS page-layout loads broken, but there are no adverts.

I'm sure I do not share the same ISP or IP address as _ghost_. I don't think my browser or computer is injecting adverts, because I encounter this peculiarity _only_ on http://mako.co.il. (And today is the first time I visit this website. Using Firefox.)

**Comment by shinycake** [comment]
Interesting. Did you have the EasyList Hebrew filters list checked and up to date?

**Comment by hairycactus** [comment]
> **shinycake:** _Did you have the EasyList Hebrew filters list checked and up to date?_

**EasyList Hebrew filter-list installed & enabled at http://mako.co.il:**
* Slider-frame adverts at bottom right: NO
* Top banner-advert: NO

**Without EasyList Hebrew filter-list:**
* Slider-frame adverts at bottom right: YES (& can't be removed with uBO's element picker)
* Top banner-advert: NO

**Comment by gorhill** [comment]
When the issue occurs, please look in the browser console (ctrl-shift-j) to find out if there are any error message related to uBO.

**Comment by gorhill** [comment]
> As ghost had reported, the advert seems to be resistant to uBO's element picker. 

I got rid of it by simply picking what seemed the best candidates in the element picker:  `###mysupermarketcontainer`.

**Comment by gorhill** [comment]
Closing as I can't reproduce any issue, and it has gone stale. Site changed too, so I can't try to repro with latest version anyways.
