### ISSUE TITLE
[Suggestion] Add "Block this page" in context menu.

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#1742]
Sometimes there are bad redirections on other page, for fix that I must manually add a custom filter for solve the problem.
For example, this morning I have a redirection on http://mp3.uzhgorod.name/ to very bad http://hardcoreyouth.com/
In this case will be great have on context menu the option "Block this page" for add automatically the custom filter  `||http://hardcoreyouth.com` because not all users are advanced users.

UPDATE: The redirection site is changed to http://www.ifuckedherfinally.com/
With the logger info is possible fix the redirection in two way:
- disable the Inline script on http://mp3.uzhgorod.name/
- add the custom filter `||http://hdsh.loadseqip.ru` that is redirection maker site.

In any case the suggestion remain good for non advanced users.

**Comment by proxifier** [comment]
Don't add this in context menu, instead add this in drop-down menu(UO icon).

**Comment by gorhill** [comment]
Best is to report to filter list maintainers -- this way the issue will be solved for all users.
