### ISSUE TITLE
Cosmetic Filter for "Edit this section" button on Wikipedia Mobile page.

### ISSUE THREAD

**Issue by chella1cm** [gorhill/uBlock#1747]
### Describe the issue
I am using Mobile version of Wikipedia as my default and i wanted to block "Edit this section" button but using element picker i have to do it for every single element. Is there a way to block it with Wildcard?.

### One or more specific URLs where the issue occurs
eg-page: https://en.m.wikipedia.org/wiki/Schmerber_v._California
I am trying to block this element on every section. 

`###content-collapsible-block-0 > .in-block:nth-of-type(1) > span:nth-of-type(2)`

### Steps for anyone to reproduce the issue
To reproduce goto

https://en.m.wikipedia.org/wiki/Schmerber_v._California

### Your settings

- Browser/version:  Chrome Dev :53.0.2767.5
- uBlock Origin version: 1.7.2

##### Your filter lists

Default filter lists - Malware Domains

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
https://raw.githubusercontent.com/chella1cm/Blocklist/master/Malware%20urls.txt
https://raw.githubusercontent.com/chella1cm/Blocklist/master/Phishing%20urls.txt

**Comment by gwarser** [comment]
ctrl+click

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
