### ISSUE TITLE
[Non-issue/Minor issue] Dynamic filtering precedence confusion

### ISSUE THREAD

**Issue by scratchyleet** [gorhill/uBlock#1748]
**Requirements:**
- Firefox 46.0.1.
- uBlock Origin 1.7.6.

**Reproducing steps:**
- Set dynamic filter with rules below:

```
* * 3p block
addons.mozilla.org * image noop
```
- Open logger.
- Open page https://addons.mozilla.org/
- Watch in the logger as images are being blocked yet rule `addons.mozilla.org * image noop` is present in a dynamic filter.

**Additional information:**
I do realize that `3p` has a precedence over an `image` type but it is a bit confusing. Since `addons.mozilla.org * image noop` rule does coexist in a dynamic filter with `* * 3p block`. Although in my opinion `* * 3p block` is being less specific than `addons.mozilla.org * image noop`. An intended behavior?

Good luck fixing that.

**Comment by gorhill** [comment]
> `* * 3p block` is being less specific than `addons.mozilla.org * image noop`

The cell at `addons.mozilla.org * 3p` evaluate to block.

If it really confuse a majority of users, I will just remove the ability to create block rules for images. The primary purpose of `image` rules was to save bandwidth, while more recent version of uBO can block images based on size.

**Comment by scratchyleet** [comment]
> If it really confuse a majority of users, I will just remove the ability to create block rules for images.

I guess that is not really required though it would be nice to add/update examples at:
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence

For example:
What is that?

> The more specific the party, the higher the precedence.
> - `example.com` overrides `1rd-party scripts`

Is that `1st-party scripts` or `3rd-party scripts`?


Also a statement:
> All cells override the `all` cells.

implies that a below dynamic filter rule would not work?
```
* * 3p block
addons.mozilla.org * * noop
```
This one is confusing too since it is present in the rules but does not work.

**Comment by Blaisorblade** [comment]
I have a similar/the same problem. I left a Medium article open, and noticed uBlock blocked ~300k requests, so I investigated. Turns out that the webpage connects to `collector-medium.lightstep.com` periodically, EasyPrivacy blocks that, and since lightstep seems just performance monitoring, I tried to re-enable it.

First I tried various dynamic rules, ending up with the following permanent dynamic rule:
```
* collector-medium.lightstep.com * allow
```
The docs seem pretty clear this rule should override the static ones, but that doesn't work.

**Comment by gorhill** [comment]
> The docs seem pretty clear this rule should override the static ones

Your rule works fine here. Did you enable _Advanced user mode_?

**Comment by Blaisorblade** [comment]
@gorhill You're right, I didn't and that fixed it, but the UI/docs doesn't tell me to in places I looked at.

The "My rules" settings page is shown without that enabled, and neither that settings page nor the page linked at "full documentation" (https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax) dynamic page mentions it. (I didn't find an edit button for the wiki, so I'm afraid some contributor will have to fix it). Would you like a separate issue for that?

**Comment by gorhill** [comment]
> Would you like a separate issue for that?

No. This is a sub page on the whole topic -- go back to the main page and it's clearly mentioned.

**Comment by Blaisorblade** [comment]
Could I then suggest linking to https://github.com/gorhill/uBlock/wiki/Dynamic-filtering instead?

(I'd also say the Dynamic filtering page should at least have a warning if it's disabled, to be a bit more usable, but changing the link is easier and would make things much better).

**Comment by gorhill** [comment]
> Could I then suggest linking to https://github.com/gorhill/uBlock/wiki/Dynamic-filtering instead?

It does already link back, that's what I pointed out in my answer above.

**Comment by gorhill** [comment]
Ok I see, you mean from the dashboard of uBO itself.
