### ISSUE TITLE
Problem with Aliexpress Affiliate Links

### ISSUE THREAD

**Issue by mustafaturksavas** [gorhill/uBlock#175]
Hi @gorhill,

I started a project and added affiliate links from Aliexpress. But, when I click on them new tab closes instantly, obviously recognising it as spam. There are no problems with Amazon Affilate links, probably because of the format. Here is an example affiliate link from Aliexpress, hope you can fix it soon.

http://s.click.aliexpress.com/e/by7AMzJmE

**Comment by gorhill** [comment]
Can't reproduce with the limited amount of [information given](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

In all likeliness, a 3rd-party filter list issue. Please try to find out if this is the case before filing an issue here. Re-open if you confirm there is an issue with uBlock itself.

**Comment by mustafaturksavas** [comment]
Hi, I confirmed it was an uBlock issue before opening this. Confirming was simple really. I disabled the plugin and there was no problem, I re-enabled the plugin and there it was. I haven't added any lists or rules to uBlock.

Here is the info that you might need:

<a href="http://s.click.aliexpress.com/e/by7AMzJmE" target="_blank">Title</a>

uBlock Origin0.9.6.0
Chrome Version 41.0.2272.118 (64-bit)
Mac OS 10.10.3 (14D136)

**Comment by iandol** [comment]
That hasn't really confirmed anything; have you disabled the 3rd party filter lists and checked which list may be doing this? There is also a logger that may help you pin-point where the problem may be.

**Comment by mustafaturksavas** [comment]
Hi @iandol. Yes, I did and like I said, it's uBlock that's blocking it. Thanks for letting me know about the logger. Here is the output. Looks like, uBlock thinks it's a popup, but it's just a new tab initiated by target="_blank"

 - 	||click.aliexpress.com/e/	popup	http://s.click.aliexpress.com/e/by7AMzJmE

**Comment by gorhill** [comment]
Logger says: 

    ||click.aliexpress.com/e/
    popup

From:

    easylist-downloads.adblockplus.org/easylist.txt:28700:||click.aliexpress.com/e/$popup,third-party

Report to maintainers of EasyList.

**Comment by eexit** [comment]
Add this into your filters: 

    @@||aliexpress.com^$popup
