### ISSUE TITLE
ublock is not active when click link from new tab

### ISSUE THREAD

**Issue by dennyhalim** [gorhill/uBlock#1750]
on win7, firefox esr 45.2
when click link from new tab, ublock not working

how to reproduce:
- ctrl-T to open new tab
- ublock not active, icon is greyed
- click on one of the sites listed there
- ublock still not active

**Comment by gorhill** [comment]
Unable to reproduce with FF47 or Nightly.

**Comment by berrythesoftwarecodeprogrammar** [comment]
are you sure ublock isnt working? or the icon just makes it appear like its not working? i get this sometimes. im pretty sure its just a UI bug where sometimes ublock or umatrix icons are grey but they still block

**Comment by dennyhalim** [comment]
i'm sure it's not working because i start seeing ads all over the web.
that's actually how i know ublock not working, before i look at the icon.
