### ISSUE TITLE
Adobe Muse 2015.2 generated website blocking pictures

### ISSUE THREAD

**Issue by wckleghorn** [gorhill/uBlock#1753]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

http://www.clearwaterdocks.com

### Screenshot in which the issue can be seen

Go to the website www.clearwaterdocks.com you will notice images are missing in header.  You can go to dock building components tab and see more pictures missing.  Not all pictures are blocked.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chrome, Firefox
- uBlock Origin version: 1.7.2

##### Your filter lists

Default

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
