### ISSUE TITLE
Cannot set exemptions to strict blocks

### ISSUE THREAD

**Issue by Alexendoo** [gorhill/uBlock#1754]
### Describe the issue

Setting a filter of `example.com$document` blocks an entire page, I was trying to unblock a subpage e.g. [example.com/page](http://example.com/page).

both:

```
example.com$document
@@example.com/page
```

and

```
example.com$document
@@example.com/page$document
```

Resulted in both [example.com](http://example.com) and [example.com/page](http://example.com/page) being blocked
### Your settings

Default settings
- Browser/version: Chrome 53.0.2774.3 dev-m 
- Browser/version: Firefox 47.0
- uBlock Origin version: 1.7.6
##### Your filter lists

`My filters` only

**Comment by gorhill** [comment]
To fix this requires to support exception filters for the `document` option. I will implement support for this, but of course the semantic of such filter in uBO will be completely different than that of ABP -- where the `document` option means "disable all filters for the document".

**Comment by monolifed** [comment]
Does strict blocking syntax support some kind of string matching?

**Comment by gorhill** [comment]
It's just a filter option on whatever is a valid ABP-compatible filter syntax.

**Comment by monolifed** [comment]
I read it a little it might be something like:
||example.com^$document 
@@||example.com/foo^$~document
