### ISSUE TITLE
Append ! to unticked filters 

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1758]
Currently in uO 3rd party filters, when you untick custom filters they get unticked but an exclamation point is not appended in the URLs in text area. 

This causes users to not be able to properly backup their custom 3rd party filters and if you change the URLs of existing filters which were unticked they become ticked.

**Comment by gorhill** [comment]
what?

**Comment by grenzor** [comment]
Example: https://i.imgur.com/HWQXvoA.png

Both these filters are actually unticked above the text area above it under the 'Custom' section but only 1 of them is shown as not to be used (! appended at the front) while the other is able to be used but "manually unticked" . If you change the URL in any way e.g. change to https, change filename etc and 'apply changes' uO will automatically tick the amended filter.

**Comment by gorhill** [comment]
The text area is not to enable/disable filter lists, it's to tell uBO which filter lists to import, it's completely under your control, uBO won't mess up whatever you add in there.

**Comment by grenzor** [comment]
Is there a way to back up these Custom filters properly (so that whatever the user unticked manually is still unticked when the user imports it back)?

**Comment by gorhill** [comment]
> whatever the user unticked manually is still unticked when the user imports it back

That is issue #344.
