### ISSUE TITLE
MGID ads injected on Postimage, almost unblockable

### ISSUE THREAD

**Issue by RMisaki** [gorhill/uBlock#1759]
By the way, it ISN'T malware on my computer, just to make it clear

### Describe the issue
Postimage.org is using some ANNOYING ads injected from mgid, even though they can block pages from opening when clicked, the ads are still displayed, using base64 encoding so they don't get blocked.
I could block the side ads by using this filter:
postimg.org###content > .show-image.container > .td-ad

But the other ads I couldn't, even with:
postimg.org##img[src^="data:"]

Well, those ads on the bottom aren't in a named div or anything, they are very shielded from blocking >.>

### One or more specific URLs where the issue occurs

You can look the issue here on my incredible HD horse drawing over an image
https://postimg.org/image/8nre36631/

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/20160983/16369945/1183f9f4-3c12-11e6-835d-fc2ce357fe75.png)

![image](https://cloud.githubusercontent.com/assets/20160983/16370245/691f3848-3c14-11e6-9924-8e4a8752f82f.png)

### Steps for anyone to reproduce the issue

I couldn't block it, go there on postimage.org images and try! D=

### Your settings

- Browser/version: Comodo Dragon, updated
- uBlock Origin version: v1.7.6

##### Your filter lists

Default + Experimental +Anti Adblock

##### Your custom filters (if any)

mgid.com
*mgid.com
steepto.com
*steepto.com
postimg.org##img[src^="data:"]
postimg.org###content > .show-image.container > .td-ad

**Comment by MarkTheFucker** [comment]
Yes none of those will work as uBlock cannot detect WebSocket connections on its own. That's a websocket connection displaying ads. You need to install this - https://github.com/gorhill/uBO-WebSocket#installation

Then block mgid.com itself via `||mgid.com^`

**Comment by gorhill** [comment]
`mgid.com` is already blocked by Peter Lowe's list, which is selected by default in uBO. So it's just a matter of installing the uBO_WebSocket extension.

![a](https://cloud.githubusercontent.com/assets/585534/16379422/7fc11528-3c3f-11e6-90eb-99255c44c107.png)

**Comment by MarkTheLover** [comment]
gorhill, would you update uBlock Origin on Opera Store ? It's still 1.7.4 there.
