### ISSUE TITLE
How to recreate the Chromium extension CPU usage benchmark

### ISSUE THREAD

**Issue by CyrusSUEN** [gorhill/uBlock#1760]
I understand we have to install [sessbench](https://github.com/gorhill/sessbench) and load the script from https://github.com/gorhill/uBlock/wiki/Reference-benchmark to do the benchmark.

But I'm not so sure how to collect the number of CPU usage sample for the extension during the benchmark like the following chart:
![cpu-usage-overall-chart-20141226.png](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/benchmarks/cpu-usage-overall-chart-20141226.png)

Thank you!

**Comment by gorhill** [comment]
It's stated under the picture your posted above on the front page of the project:

> Details of the benchmark available in [this LibreOffice spreadsheet](https://github.com/gorhill/uBlock/blob/master/doc/benchmarks/cpu-usage-overall-20141226.ods).

**Comment by CyrusSUEN** [comment]
Thanks again!

**Comment by gorhill** [comment]
This is the raw footage btw: <https://www.youtube.com/watch?v=DKM78oV_ftg>.
