### ISSUE TITLE
Firefox freezes/hangs with siderail filter

### ISSUE THREAD

**Issue by itVictor** [gorhill/uBlock#1762]
### Describe the issue

Attempting to filter the ###siderail on gamepedia will result in a hang of the browser, freezing before the filter is applied (via element picker) or if the filter is added directly, the page will cause Firefox to hang once the page has finished loading.

### One or more specific URLs where the issue occurs
http://overwatch.gamepedia.com/Torbj%C3%B6rn
http://dota2.gamepedia.com/Mechanics
etc. any gamepedia page

### Steps for anyone to reproduce the issue

1. Go to any gamepedia page with a siderail (eg. http://overwatch.gamepedia.com/Torbj%C3%B6rn )
2. Use the element picker on the siderail [here.](http://i.imgur.com/FlvQdDz.jpg)

alternatively, 

1. Go to my filters and add `overwatch.gamepedia.com###siderail` and apply.
2. Go to http://overwatch.gamepedia.com/Torbj%C3%B6rn the browser will hang once the page loads.

### Your settings

- OS: OSX 10.11.5
- Browser/version: Firefox 47.0 (had no issues with the filter in Chrome 51.0.2704.106)
- uBlock Origin version: 1.7.6

##### Your filter lists

Default

##### Your custom filters (if any)

Default + anti-adblock killer

(This is my first time using github like this, so if I missed something or this isn't a vaild issue I apologize)

**Comment by gorhill** [comment]
The issue is the page's javascript, not uBO. Some pages may starts to behave erratically when the DOM is not as they expect.
