### ISSUE TITLE
Suggestions and  Issue v1.7.6

### ISSUE THREAD

**Issue by vijebu** [gorhill/uBlock#1763]
uBlock Origin v1.7.6 (minimum chrome version is 22)

Issue: chronium portable v22-v30, element blocking window dont show after pres block button.
All buttons in pop-up menu dont have images - only white squares

Suggestion: 
1. add in list this popular list:  RU AdList: Counters‎
https://easylist-downloads.adblockplus.org/cntblock.txt
2. Button to hide other languages lists
3. parser to migrate from  Adb/ADBP - get whitelist (it is not reach out from gui)

**Comment by anewuser** [comment]
Only the official versions of Firefox, Chrome/Chromium and Opera are supported officially by uBlock Origin. Also, you've ignored and deleted the template text that appears when you create a new issue.

That text isn't there just for decoration. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by vijebu** [comment]
chrome is 100% chronium official browser

**Comment by anewuser** [comment]
"chronium portable v22-v30" isn't an official version.
