### ISSUE TITLE
sometimes uBO ignores the ^

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1764]
Example:
`||en.wikipedia.org^$image,domain=en.wikipedia.org`
Go to en.wikipedia.org and open the logger.

uBO v1.7.6, Firefox 47 64 bit

**Comment by gorhill** [comment]
I don't see anything wrong.

**Comment by IsraeliUser** [comment]
Try `||en.wikipedia.o^$image,domain=en.wikipedia.org` (without the _rg_ after the _o_). uBO blocks the English Wikipedia logo, although it should not.

**Comment by IsraeliUser** [comment]
(duplicate)
https://github.com/gorhill/uBlock/issues/1757

**Comment by gorhill** [comment]
I don't see this issue with 1.7.7b0. I do see it however with 1.7.6, so it was apparently fixed with #1757.
