### ISSUE TITLE
Filters in "my filters" not working

### ISSUE THREAD

**Issue by Sclarki** [gorhill/uBlock#1769]
### Describe the issue

Using any sort of filter in ublock's "My filters" section fails.

### One or more specific URLs where the issue occurs

`google.com`
`example.com`

*_Literally any site_.

### Screenshot in which the issue can be seen

![screenshot_wed-jun-29_19-03-35-cdt-2016](https://cloud.githubusercontent.com/assets/8389374/16473094/dd3d823a-3e2f-11e6-8612-c6d3f264e391.png)

### Steps for anyone to reproduce the issue

1. Apply `||example.com^` as a filter (as per [wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax)) in the section `My filters`.
2. Open `example.com` and watch the logger
3. Logging shows the filter was never applied

*_Issue with various filters: `example.com`, `example.com^`, `||example.com^$inline-script`, etc_

### Your settings

- Browser/version: Firefox 47
- uBlock Origin version: 1.7.6

#### Your filter lists

Issue occurs regardless of whether lists are selected.

#### Your custom filters (if any)

None

**Comment by gorhill** [comment]
You will have to find out why it's not working on your side. I will close after a few days if you can't make the case there is somethign wrong with uBO -- this requires that you provide exact repro steps for anybody to repro.

**Comment by Sclarki** [comment]
The good news: I resolved the issue. It is not a uBlock bug.

The bad news: I'm an idiot and forgot to enable the filters in the first place.

Sorry about that!
