### ISSUE TITLE
Some cosmetic filters stop working 1.7.7 

### ISSUE THREAD

**Issue by olgon** [gorhill/uBlock#1770]
### Describe the issue

Befote 1.7.7 this filter in `My filters` works
`##a[href^="http://funding.to/"]`

### One or more specific URLs where the issue occurs
e,g https://aftershock.news/?q=node/402147

![](https://aftershock.news/sites/all/themes/AsLoD/images/donate.png) This image disappear with
`##a[href   ^="http://funding.to/"]` (with space between `href` and `^=` )  or
`aftershock.news##a[href^="http://funding.to/"]` (no space between `href` and `^=` )  or
`##a[href*="http://funding.to/"]` (no space between `href` and `*=` ) 

but persists with  `##a[href^="http://funding.to/"]` (no space between `href` and `^=` ) 

### Your settings

- Browser/version: Firefox 47.0
- uBlock Origin version:  1.7.7b7

**Comment by gorhill** [comment]
Regression following re-factoring of content script code. Will fix asap.
