### ISSUE TITLE
:has(> iframe) and :has(+ iframe) support

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#1771]
Hi,

Simple testcast. I want to block all divs that have `iframe` child.

`##div:has(iframe)` works fine, but as expected it block top level div, because it obviously have an iframe in it's descendants. 

No I want to block divs only that have a iframe child. So this would be `##div:has(> iframe)` but doesn't seem to work. Neither does  `##div:has(+ iframe)`.

I guess this is not yet supported so I consider this issue feature request.

**Comment by gorhill** [comment]
Use `:xpath` if you want fancier `:has` syntax -- performance trumps mimicking perfectly `:has`.

**Comment by kasper93** [comment]
Thanks. Make sens to have lighter `:has()` operator. `:xpath()` works fine in my use case :)

**Comment by gorhill** [comment]
I just tried and `##div:has(* > iframe)` works.

**Comment by gorhill** [comment]
Got it: Try `##div:has(:scope > iframe)`.

**Comment by kasper93** [comment]
Yeah, this one works fine! 

For reference xpath looks like this `##:xpath(//div[iframe])` but I have this gut felling that `:has()` operator is faster. xpath is big hammer.

**Comment by gorhill** [comment]
I could possibly prepend `:scope` so that people don't have to worry about it, it's rather trivial perf-wise. Of course for the second case, `:has(+ iframe)`, I see no obvious solution aside over-complicating the code, which I prefer to avoid.

**Comment by gorhill** [comment]
Ok finally I will decline prepending `:scope`, that would make the `:has()`-based filters not work on Pale Moon -- `:scope` wasn't supported inside `querySelectorAll` before FF 32.
