### ISSUE TITLE
Recent commit broke certain cosmetic filters (e.g. collapsing elements)

### ISSUE THREAD

**Issue by TheRyuu** [gorhill/uBlock#1773]
8374799 (the commit that broke it) up to and including what is the current HEAD (bec8243) have broken cosmetic filtering where certain things are not hidden/collapsed properly.  The previous commit (a3f6a41) does not display this issue.

This can be easily seen on youtube videos which have ads.  The yellow parts in the seek bar are not hidden.  

Another example is on this weather site:
https://www.wunderground.com/us/ny/new-york
To the right of the 10 day forecast appears and ad which should be hidden/collapsed.

Another example:
https://techreport.com/
There's a blank space that appears above the "Top Comments".  This should be collapsed and the top comments moved up in its place.

I have most filter lists enabled except for the language specific ones, anti-adblock, easylist without element hiding or the merged one which would be redundant.  This should be reproducible with just easylist though since I think that's where all the filters that are broken for my examples are from.

This is on the latest Chrome dev version.

**Comment by gorhill** [comment]
Thanks for narrowing this down. Will fix asap.
