### ISSUE TITLE
Cosmetic filtering regression 1.7.7

### ISSUE THREAD

**Issue by olgon** [gorhill/uBlock#1774]
### Describe the issue
Add  `~example.com##body` to `My filters` 
Open e.g.  https://github.com/gorhill/uBlock (you'll see blank tab)
Open http://example.com/
Open or reload https://github.com/gorhill/uBlock (you'll see normal content)

I mean that any filter this kind `~site##selector` 
stop working ewerywhere if open site (the same one that was excluded by `~`)

- Browser/version:  Firefox 47
- uBlock Origin version:  1.7.7b9

**Comment by duanemoody** [comment]
I'm on 1.7.6 and last night uBlock stopped filtering any site; I haven't made a change to the custom filters in at least a week.

**Comment by gorhill** [comment]
You need to do some investigation on your side, there is nothing I can do without you first try something on your side. What does the logger says? Browser? etc. Investigate as much as possible, then report findings if you have evidence there is somethign wrong with uBO.
