### ISSUE TITLE
uBO 1.7.7beta -- Cosmetic filters using [style="..."] not working

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#1775]
### Describing the issue

Since uBO 1.7.7_beta_, following sort of filter no longer works: `forum.pcastuces.com##DIV[style="background-color:#eff4fc;margin:auto;font-size:1.2em;text-align:center;width:80%;border:1px solid #c9c9c9;padding:5px;"]`

### One or more specific URLs where the issue occurs

- https://forum.pcastuces.com/recuperer_fenetre_automatique_pour_telecharger_photos_iphone_5-f21s7118.htm?page=1&#5514204
- https://forum.pcastuces.com/est_ce_normal-f13s5020.htm?page=1&#5514250
- https://forum.pcastuces.com/zimbra-f6s69637.htm?page=1&#5514270

### Screenshot in which the issue can be seen
![screenshot01613](https://cloud.githubusercontent.com/assets/11029138/16541848/f65128f4-4090-11e6-9e3c-a0dbf0dbbfc8.png)

### Steps for anyone to reproduce the issue

- With uBO 1.7.7_beta_, click any link above and notice that the _table_ near the footer is displayed.
- Reproduce with uBO 1.7.6 or prior and notice that this table is correctly hidden.  

### My settings

- OS: Win XP SP3
- Browser/version: Firefox ESR 38.8.0
- uBlock Origin version: 1.7.7b8

##### My filter lists

![screenshot01614](https://cloud.githubusercontent.com/assets/11029138/16541903/01dee128-4093-11e6-9ae5-e84febb71d81.png)
![screenshot01615](https://cloud.githubusercontent.com/assets/11029138/16541904/0728734c-4093-11e6-84d8-8e38f861d8f4.png)
![screenshot01616](https://cloud.githubusercontent.com/assets/11029138/16541905/0ba1af38-4093-11e6-9b1f-b215ee18ce56.png)

##### Your custom filters (if any):  none

**Comment by gorhill** [comment]
Can you confirm this was with 1.7.7b8?

**Comment by onestepbeyond** [comment]
Yes, I do confirm. 
-- sorry, this topic has a duplicate in uAssets...

**Comment by gorhill** [comment]
Ok I see the issue, it's a code issue. The new code fixes cases like #963, but breaks cosmetic filters which use `[style="..."]`.

**Comment by onestepbeyond** [comment]
OK. What means exactly "declarative way" ? Should I manually change something in such filters ? 
or this question makes no sense... ? I feel so stupid with uBO, how frustrating...

**Comment by gorhill** [comment]
Meanwhile, since you are using the beta version, use: `forum.pcastuces.com##body > div:has(a[href="enregistrement.asp"])`

**Comment by gorhill** [comment]
When I use "declarative" I mean the CSS rule will be injected in a `style` tag, and no further action will be taken. "Further action" means that uBO, on top of injecting style tags, will also visit all affected DOM elements to force `display: none !important` on them, to be sure sites do not try to override uBO's cosmetic filtering. But changing the style of an element to force-hide it has the side effect of modifiying its `style` attribute, which causes the DOM element to **no** longer match the cosmetic filter. This is what causes #435. The cod refactoring in 1.7.7 made the issue more prominent -- but it was already in there.

**Comment by onestepbeyond** [comment]
> Meanwhile, since you are using the beta version, use: forum.pcastuces.com##body > div:has(a[href="enregistrement.asp"])

Wow! works and `:has` seems fantastic! :thumbsup:

Thanks for the additional explanations.

**Comment by onestepbeyond** [comment]
I just noticed that infortunately, the header goes away (same target). 
Does not matter at this stage, I will wait for the release.

**Comment by gorhill** [comment]
Try `forum.pcastuces.com##body > div:has(:scope > a[href="enregistrement.asp"])`.

**Comment by onestepbeyond** [comment]
As far as I can see after testing several scenarios, that filter seems working without side-effect.:ok_hand:

**Comment by gorhill** [comment]
Just for the fun of it I came up with these too:

    forum.pcastuces.com##:xpath(/html/body/table//tr[@class="formsubtitle2"][.//text()="Publicité"])
    forum.pcastuces.com##:xpath(/html/body/table//tr[@class="formsubtitle2"][.//text()="Publicité"]/following-sibling::tr[1])

**Comment by onestepbeyond** [comment]
WOW!  
J U S T  P E R F E C T !
If I had thought about that "impossibility" today, I would have said you read my mind! :sunny:

**Comment by onestepbeyond** [comment]
What do you think about adding this third filter:
`forum.pcastuces.com##:xpath(/html/body/table//tr[@class="formsubtitle2"][.//text()="Publicité"]/following-sibling::tr[2])` 
(I just change the final "1" to "2")
... to reproduce the standard height existing between the other posts on the page. 
I tried and do not feel that this generates some quirk, unless I am mistaken.

**Comment by gorhill** [comment]
Looks fine to me, I hadn't noticed there was an empty row used for spacing.

**Comment by onestepbeyond** [comment]
Aaargh! it brokes pagination (in the bottom of the page, above the footer).

![screenshot01617](https://cloud.githubusercontent.com/assets/11029138/16543375/f216c1c2-40d1-11e6-9edc-d6159cd3b787.png)

No matter, I let only 1 sibling, that's fine. Le mieux est l'ennemi du bien. 
Thank you again you for your help, much appreciated.

**Comment by gorhill** [comment]
Ça va aider quand je vais implémenter #1772.

**Comment by gorhill** [comment]
Wish I had found this before: <https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden>. This completely solves the issue.

**Comment by onestepbeyond** [comment]
> This completely solves the issue.

I'm infortunately not technically advanced enough to understand all the implications of this good news, and the *language barrier* is another obstacle. 
However, I sometimes use the `display: none !important;` declaration in the `userContent.css` file to hide some elements. 
So, dumb question, sorry, am I supposed to make something on my side to solve the issue?

**Comment by gorhill** [comment]
I am not asking you to understand anything, it's a code repo and I will often add dev notes to issues.

**Comment by phrokton** [comment]
@gorhill How are you generating XPath?  

For firefox I once used

[https://addons.mozilla.org/en-US/firefox/addon/xpather/](https://addons.mozilla.org/en-US/firefox/addon/xpather/ )

[https://addons.mozilla.org/en-US/firefox/addon/yarip](https://addons.mozilla.org/en-US/firefox/addon/yarip)

**Comment by gorhill** [comment]
> How are you generating XPath?

I just craft it manually according my observation of the DOM. There is also an _"Copy XPath"_ menu entry in Chromium's inspector (can't see this in Firefox though).

**Comment by gorhill** [comment]
Reported issue was fixed with 02e6b088ef0716a087986e093331ad4a5a1d5b67.
