### ISSUE TITLE
Configuring uBlock programmatically

### ISSUE THREAD

**Issue by michalrus** [gorhill/uBlock#1776]
### Description

I’d like to configure uBlock programmatically, from my `~/.conkerorrc.js`, e.g. add some custom filters, update them, etc. Everything that’s accesible through the `µBlock` object.

**Question**: how can I get a grip of the `µBlock` object?

E.g.:
* with NoScript, one can do:

  ```js
  var noscript_service = Cc["@maone.net/noscript-service;1"]
        .createInstance().wrappedJSObject;
  ```
and configure it through `noscript_service.doWhateverYouWant(withSomething)`,

* with mozrepl, one can do:
  ```js
  var mozrepl_service = Cc['@hyperstruct.net/mozlab/mozrepl;1']
        .getService(Components.interfaces.nsIMozRepl);
  ```

* etc. …

uBlock defines `Cc['@ublock0/content-policy;1']` and `Cc['@ublock0/net-channel-event-sinks;1']`, but I don’t know how to get to `µBlock` from them. :crying_cat_face: 

### Settings

- Browser/version: conkeror/1.0.3
- uBlock Origin version: 1.7.4

##### Filter lists

*[Irrelevant]*

**Comment by anewuser** [comment]
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by michalrus** [comment]
Okaaaay, I’ll try. But from the first look of Mozilla Discourse, I have no idea how to use it. Where are the threads? ಠ_ಠ One thread for all inquiries? What happens if someone posts many messages after mine which is still unanswered? \*sigh\*

**Comment by michalrus** [comment]
Okay, I’m reopening this, as Mozilla Discourse is not helpful and this issue/question is a technical one, and answer will deal with µBlock inner workings.

@gorhill, can you, please, look at this?

**Comment by michalrus** [comment]
:slow_clap:
