### ISSUE TITLE
Blocklist Optimizer

### ISSUE THREAD

**Issue by proxifier** [gorhill/uBlock#1777]
When I load custom list, I got 

> : 93,632 used out of 96,017

How did you optimize the blocklist?
Is there any plan to release "Blocklist Optimizer"(as a EXE or Python/PHP/Perl script), so many list creators will appreciate your work?

**Comment by proxifier** [comment]
I already removed duplicated lines and comments, and it seems 2385 lines are wasted.

**Comment by anewuser** [comment]
Filters found in two or more lists are only used/applied/counted once.

Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by proxifier** [comment]
> clicking on the "Code" tab on this website.

yeah, right. I'll do it myself.
