### ISSUE TITLE
[NSFW] PornHub vids won't play

### ISSUE THREAD

**Issue by LoreJon** [gorhill/uBlock#1780]
http://www.pornhub.com/

After the last uBlock filters update the ads are blocked but the videos won't play.

Thanks.

**Comment by gorhill** [comment]
I just committed a fix prior to see the issue here. Can you try with updated filters?

**Comment by gorhill** [comment]
Also, are you using the Flash-based player or HTML5 one?

**Comment by gorhill** [comment]
The Flash-based videos were blocked -- the HTML5 ones worked. Fixed.

**Comment by LoreJon** [comment]
Flash-based videos are still locked.
Thanks.

**Comment by aggat** [comment]
Add `$object` also here
`@||phncdn.com^$media,stylesheet,domain=gaytube.com|pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|xtube.com|youjizz.com|youporn.com|youporngay.com`

**Comment by LoreJon** [comment]
Still blocked.

**Comment by aggat** [comment]
LoreJon try add to `My filters`
`@@||phncdn.com^$object,media,stylesheet,domain=gaytube.com|pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|xtube.com|youjizz.com|youporn.com|youporngay.com`

**Comment by LoreJon** [comment]
@aggat ,
That works.

@gorhill ,
Souldn't this rule be addaed to uBlock filters – Unbreak?

Thanks

**Comment by IDKwhattoputhere** [comment]
It's caused by `uBlock filters‎` so the fix should be in there‎ too.
