### ISSUE TITLE
Own static filter not immediately available?!

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1786]
Hello

On the page ...

https://www.cyon.ch/webhosting/vermittlerprogramm

... the pictures with path "/files/ads/*" are blocked. The reason in my case are those static filter lists:

"AdGuard English FIlter" and "EasyList". So far so good.

Now, i'd like to unblock the pictures, so I create the following STATIC filter from the logger:

@@||www.cyon.ch/files/ads$image,domain=www.cyon.ch

After a reload even without cache, those picture entries are GREEN in logger. Unfortunately they are still blocked in Browser (see below which Browser).

BUT: after a manually change in "Meine Filter" ("My filters") and "Änderungen anwenden" ("Apply changes"?) - for exampe I do change a comment line - and a reload again, I can see those pictures then!

I have the same behaviour with Firefox 47.0.1 64-bit and Chrome 51.0.2704.106 m 64-bit with uBlock Origin 1.7.7b10 on my OS Windows 10 1511 (10586) 64-bit.

My question is now: why is the effect not immediately after create the new static filter - or in other words: why is it necessary to make a change (not related to this newly created static filter) in "Meine Filter" ("My filters"), before the pictures are displayed?

Thanks for all answers in advance!

**Comment by gorhill** [comment]
I can reproduce.
