### ISSUE TITLE
High "Idle Wake Ups" on Chrome and Mac OS X

### ISSUE THREAD

**Issue by skuhl** [gorhill/uBlock#1788]
On OS X, the Chrome task manager reports that uBlock Origin constantly showing 50-80 "Idle Wake Ups". This occurs almost all of the time, regardless of if I have the ublock origin settings tab open, and even happens when I just have the browser open without interacting with it. The other extensions I use and tabs that I have open show 0 or very few "Idle Wake Ups" unless I'm interacting with them. 

Are the constant idle wakeups from uBlock Origin expected? Is it feasible to reduce this number to reduce energy use?

![image](https://cloud.githubusercontent.com/assets/1674979/16673975/30d300ee-4481-11e6-879d-0b052eac64e9.png)

### Settings

- OS: Mac OS X 10.11.5
- Browser/version: Chrome 51.0.2704.106 (64-bit)
- uBlock Origin version: 1.7.6

##### Filter lists

The problem occurs even when I have all filter lists disabled. I've also tried toggling several options to see if I could find something to reduce Idle Wake Ups---but I couldn't find a setting which changed it (short of disabling the uBlock Origin extension entirely).

**Comment by gorhill** [comment]
I cannot reproduce the "constantly showing 50-80" -- it settles to zero on my side when leaving the browser idle. Screencast: [ublock-1089.webm.zip](https://github.com/gorhill/uBlock/files/353458/ublock-1089.webm.zip).

**Comment by gorhill** [comment]
I notice you have the dashboard open. Were you moving the mouse over the dashboard when you took this screenshot? Because if so, that is a Chrome thing, and not specific to uBO -- the _Idle Wake Ups_ value will shot up for a given tab whenever you move the mouse over it, even when there is no mouse event listener installed (in such case the CPU value would also go up). This is true for any tab, including `about:blank`.

**Comment by skuhl** [comment]
It happens regardless of if the dashboard is open. Here is another screenshot. I exited chrome, started it (blank tab opens by default in my configuration) and opened the task manager.

![image](https://cloud.githubusercontent.com/assets/1674979/16688092/47eb9a20-44ea-11e6-90ba-14c0bcf81929.png)

Perhaps there is something unique about my configuration that is causing this. If I get a chance later today, I'll try to work out what part of my configuration might be causing it.

**Comment by gorhill** [comment]
Things to try if you can which result may be interesting;

- Same repro case but on Windows (I couldn't repro for linux -- I do not have access to a proper Windows installation, just a clunky VM one).
- When all is idle, open dev console for uBO and click the _Pause script execution_ button. Typically, unless uBO has real work to do (inspecting network requests, responding to content script from a page which DOM changes, etc), it should take a while before the breakpoint is triggered. If the breakpoint is not triggered very often, this means for some reasons Chrome is causing those _Idle wake ups_.

**Comment by skuhl** [comment]
I tried your "pause script execution" suggestion and the breakpoint and it doesn't get triggered while idle. Therefore, as you say, it seems that Chrome is causing those idle wakeups. 

I also noticed that the chrome://help/ (i.e., the "about" or "version" page) consumes 30-100 wakeups whenever I have it open. Not sure if that is the same problem or a different one. I think I'll switch to Safari my Mac laptop to conserve battery life.

Thanks for your help and all your work on this extension.

**Comment by gorhill** [comment]
Trying to find something in Chromium issue tracker, found out that integrated tool which may provide useful data: `chrome://tracing/`. I ran it while leaving the browser idle, and this is what I got:

![a](https://cloud.githubusercontent.com/assets/585534/16692087/4a7976dc-44fd-11e6-8f2c-57f753fa0a1d.png)

It appears the more the timeline of one entry is crowded, the more likely the entry is one with high wakeups. On my side, the browser and GPU are the ones always showing some level of wakeups. You can expand an entry and select portion of the output and the Chromium-side calls are reported in the list pane.

For uBO, the Chrome_ChildIOThread shows regular activity -- though wakeups was zero most of the time. When I select these bars, it reports:

    Name                                         Dur          Occ
    MessagePumpLibevent::OnLibeventNotification	 0.634 ms ... 11
    ChannelReader::DispatchInputData	         0.372 ms ... 11
    TracingMsg_GetTraceLogStatus                 0.180 ms ... 11

I wonder what this would show on your side.

**Comment by skuhl** [comment]
I have confirmed that I, like you, don't have this problem on Linux. When I ran the "tracing" feature on my OS X machine, I found results that mostly matched yours.

<img width="884" alt="screen shot 2016-07-08 at 3 40 48 pm" src="https://cloud.githubusercontent.com/assets/1674979/16699468/63754920-4522-11e6-902f-45d02d9bf9c3.png">
