### ISSUE TITLE
This site won't let me run ublock...

### ISSUE THREAD

**Issue by kkaran360** [gorhill/uBlock#1789]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Ublock doesn't run on above link. The link redirects and flips the content and asks to disable the ublock.

### Screenshot in which the issue can be seen

![](http://i.imgur.com/KFfyZ2e.png)

### Steps for anyone to reproduce the issue

1. Just open the [link] (http://www.divyabhaskar.co.in/news-ht/UGUJ-MEH-OMC-two-interesting-cases-of-dispute-between-couple-in-patan-and-mehsana-a-couple-jo-536759.html) 
wait for the redirect and the issue will pop up
2. This is happening to all the pages of this website.

### Your settings

- OS: Microsoft Windows 10 (64 - Bit)
- Browser/version: Chrome 51.0.2704
- uBlock Origin version: 1.7.6

##### Your filter lists

Default filter list: EasyList

**Comment by gorhill** [comment]
@@||central.bhaskar.com/revenue/blocker/ads.js

**Comment by kkaran360** [comment]
What can i do with this java script?

**Comment by gorhill** [comment]
Paste the line in the _My filters_ pane in the dashboard, then click _Apply_. Or just force an update of the filter lists.

**Comment by kkaran360** [comment]
# Thank You soo much
