### ISSUE TITLE
3rd party scripts not blocked on startup

### ISSUE THREAD

**Issue by kikaxa** [gorhill/uBlock#179]
at one site i noticed that some timer is triggering page refreshes:
http://www.guidetojapanese.org/learn/complete/verb_particles

developer-timeline shows that 
the timer originates from pluseone.js from google, 
while i have all 3rd party content default-denied, shown as blocked in ublock ui, 
yet i can view 3rd party script content in "sources" tab.

I thought that 3rd party/script blocking prevents scripts from loading, is that right?

chromium Version 42.0.2311.68 (64-bit) linux.
uBlock Origin v0.9.6.0

screenshot with some details:
![scre8](https://cloud.githubusercontent.com/assets/96402/7484186/928e84e2-f38e-11e4-9c23-c141a95fb7b2.png)

**Comment by kikaxa** [comment]
after some tests, 
this only happens when the page is reopened at browser startup.

i guess there's nothing you can do with scripts?

**Comment by gorhill** [comment]
uBlock starts as fast as it can, but no, it can't guarantee that it will be up and running before any pages load, by browser design.
