### ISSUE TITLE
Unable to load the page 

### ISSUE THREAD

**Issue by kkaran360** [gorhill/uBlock#1790]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When uBlock is turned on a blank page appears the content of the page is not displayed.

### Screenshot in which the issue can be seen

![](http://i.imgur.com/oOu7DL9.png)

### Steps for anyone to reproduce the issue

1. Open this [link] (http://www.saavn.com/s/featured/hindi/Jhoomo_Re_with_Kailash_Kher/8hVe1KwZ580_)

### Your settings

- Browser/version: Mozilla Firefox 47.0
- uBlock Origin version: 1.7.6

##### Your filter lists
Default: Easylist

**Comment by aggat** [comment]
EasyList issue.  https://forums.lanik.us 
You can add  `My filters` pane
`saavn.com#@#.ad-scroll`
