### ISSUE TITLE
WebRTC Leaking Private LAN IP Address in Vivaldi (Chromium)

### ISSUE THREAD

**Issue by bytos** [gorhill/uBlock#1791]
I have all Privacy settings checked, including "Prevent WebRTC from leaking local IP addresses", but at ipleak.net and browserleaks.com/webrtc I can see my LAN IP address.

Even the official Chrome extension "WebRTC Network Limiter" is not working well.

Vivaldi 1.3.519.25
uBlock Origin 1.76
WebRTC Network Limiter 0.2.1.3

**Comment by gorhill** [comment]
Maybe Vivaldi does not support the `chrome.privacy.network.webRTCMultipleRoutesEnabled` that uBO uses to disable the leaking of local IPs? Can you verify this setting is supported by Vivaldi?

**Comment by Hrxn** [comment]
By the way, that must be some dev or beta version of Vivaldi, where do you take this from?

Because the latest official/stable version is 1.2.490.43, did you test this also?

**Comment by bytos** [comment]
Apparently, it is an issue for Chrome/Chromium browsers, since a certain version there is no native way to disable WebRTC, maybe that's why the official extension fails under some circumstances.

Only know of two extra settings pages (vivaldi://flags & vivaldi://settings/search#a) and that line is not present:

Experiments:
WebRTC Stun origin header
Negotiation with DTLS 1.2 for WebRTC
Use ECDSA certificates for WebRTC
WebRTC H.264 software video encoder/decoder

Unavailable Experiments:
WebRTC hardware video decoding
WebRTC hardware video decoding

Read this from April of last year:

"ScriptSafe does not fix it, none of the chrome extensions do.  The Chrome extensions merely stop the website script from "displaying" the data.  The leak is still there.  Firefox WebRTC can be stopped entirely, and my understanding is Chrome 43 (dev?) onwards WebRTC can be blocked."

@Hrxn: It is the x86 snapshot version of Vivaldi (updated more frequently), the download linke is at the top right (https://vivaldi.net/en-US/).

**Comment by gorhill** [comment]
> Apparently, it is an issue for Chrome/Chromium browsers

There is no issue of private IP address leaking for Chromium and Chrome when the setting is enabled in uBO.

**Comment by bytos** [comment]
Vivaldi with uBlock Origin (checked "Prevent WebRTC from leaking local IP addresses") leaks my private LAN address @ https://ipleak.net/.
