### ISSUE TITLE
uBlock & uMatrix "crashing" in Firefox

### ISSUE THREAD

**Issue by SINE** [gorhill/uBlock#1792]
**Describe the issue**

Hello, so I noticed a very weird issue, where the uBlock and uMatrix icons just disappear, and looking at Addons -> uBlock -> Settings where there are the two buttons: "Dashboard" and "Protocol", they both are still there but there is no more text inside of them. Clicking them also has no function.

I noticed this happening mainly when I'm on the forum of the game [Squad ](http://forums.joinsquad.com).

One additional info: I always leave the protocol tab open, with 200-300 max protocol entries. This tab also closes when the issue appears.

It's really hard to explain what to do as I couldn't find a good way to reproduce the issue, yet. I will try maxing out the max-protocol entries because I have a slight suspicion it could be caused by memory overflowing or something of that nature.

**One or more specific URLs where the issue occurs**

forums.joinsquad.com

**Steps for anyone to reproduce the issue**

1. Login to the forum of joinsquad.com
2. Leave the website open for a few hours
3. ??
4. The uBlock and uMatrix icons in Firefox disappear, as if one had uninstalled the add-ons.
5. Restart Firefox and see them having returned

**Your settings**

https-strict: joinsquad.com false
ua-spoof: joinsquad.com false
bigdgaming.net joinsquad.com image allow
joinsquad.com * image allow
joinsquad.com * script inherit
joinsquad.com 1st-party script allow
joinsquad.com ajax.googleapis.com * allow
joinsquad.com cf-media.sndcdn.com other allow
joinsquad.com cloudflare.com * allow
joinsquad.com csscheckbox.com * allow
joinsquad.com doubleclick.net * block
joinsquad.com facebook.net * block
joinsquad.com fonts.googleapis.com * allow
joinsquad.com fonts.googleapis.com script allow
joinsquad.com google-analytics.com * block
joinsquad.com google.com * block
joinsquad.com googlevideo.com * allow
joinsquad.com gstatic.com * allow
joinsquad.com jquery.com * allow
joinsquad.com paypalobjects.com * allow
joinsquad.com reactionimage.org * allow
joinsquad.com soundcloud.com * allow
joinsquad.com style.sndcdn.com css allow
joinsquad.com t.co * allow
joinsquad.com t.co frame allow
joinsquad.com twitter.com * allow
joinsquad.com vimeo.com * allow
joinsquad.com vimeocdn.com * allow
joinsquad.com wis.sndcdn.com xhr allow
joinsquad.com youtube.com * allow
joinsquad.com youtube.com script allow
joinsquad.com ytimg.com * allow
joinsquad.com ytimg.com script allow
ldetachment.co.uk joinsquad.com * allow
squad.rocks joinsquad.com image allow

- **Browser/version:** Firefox 47.0.1 x64 on Windows 7 
- **uBlock Origin version:** 1.7.0

**Your filter lists**

Long-lived malware domains‎ (lehigh.edu)
Malware Domain List‎ (malwaredomainlist.com)
Malware domains‎ (cedia.org.ec)
MVPS HOSTS‎ (mvps.org)

**Comment by gorhill** [comment]
Did you try the same scenario without uBlock/uMatrix, or with another blocker configured similarly? By the description of it, FF itself is becoming unstable -- possibly out of memory. Some web sites' javascript may turn buggy when some of their stuff is blocked, and this includes leaking memory. You need to make a better case that there is an issue with uBO/uMatrix.

**Comment by SINE** [comment]
Thanks for your response. Which logger are you speaking about, the uMatrix log tab? It's gone at that moment, I'm not aware where else I could take a look at a log.

Yep, regarding Javascript was what I thought, some kind of bug causing Firefox to shut down the two add-ons. 

I'm really trying to reproduce it, but it seems to be completely random.

**Comment by SINE** [comment]
Issue disappeared after manually updating multiple add-ons.
Will close the issue for now.
