### ISSUE TITLE
suggestion: prompt new installs to consider social blocking

### ISSUE THREAD

**Issue by wolftune** [gorhill/uBlock#1794]
Blocking of social stuff is a serious issue for privacy, so it would be best if they were blocked by default. However, if doing that causes people frustration over things breaking such that they remove the uBlock entirely, that's would be really bad. So, I understand not blocking social by default, but I really wish there were a prompt upon first install asking people if they are willing to block social to improve privacy even though it may affect their experience in some ways.

This is like how Adblock Plus prompts new installations to consider social blocking.

I think this feature would result in far more users successfully blocking these things and sticking with it (and at least re-enabling social instead of removing uBlock otherwise). It would also remove extra burden from those of us promoting uBllock but wanting to tell friends and family to include the social blockers.

(This goes for the anti-adblock blocking too, though that's less serious)

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/commit/ce04053ae3054ff287af67b87b4d63b67b35a316>.
