### ISSUE TITLE
uBlock is detected 

### ISSUE THREAD

**Issue by kkaran360** [gorhill/uBlock#1795]
### Describe the issue
uBlock is detected.

### Screenshot in which the issue can be seen

![untitled](https://cloud.githubusercontent.com/assets/14898078/16710169/b5a65fbe-45f3-11e6-9682-6e6cebc1dcc2.png)

### Steps for anyone to reproduce the issue

- Open this [link] (http://timesofindia.indiatimes.com/world/rest-of-world/This-guy-used-a-frequent-flyer-loophole-to-take-a-60000-trip-in-a-first-class-suite-on-Emirates-heres-what-it-was-like/articleshow/51730463.cms?utm_source=facebook.com&utm_medium=referral&utm_campaign=TOI).

### Your settings

- Browser/version: Firefox 47.0.1
- uBlock Origin version: 1.7.6

### Your filter lists
- Adblock Warning Removal List‎ 
- Anti-Adblock Killer | Reek‎ 
- EasyList‎ 
- EasyList without element hiding rules‎
- Peter Lowe’s Ad server list‎

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
