### ISSUE TITLE
Ublock not updated on Opera

### ISSUE THREAD

**Issue by dragonble** [gorhill/uBlock#1796]
Hi, I just wanted to ask why ublock origin was not updated  to  the latest stable version,1.7.6,  on the opera extension store?

Thanks.

**Comment by anewuser** [comment]
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by dragonble** [comment]
Close #1796

**Comment by dragonble** [comment]
close #1796

**Comment by dragonble** [comment]
closed #1796
