### ISSUE TITLE
upornia.com##.mjs-closeplay not block

### ISSUE THREAD

**Issue by DandyClubs** [gorhill/uBlock#1798]
i add easylist filter

but 

upornia.com##.mjs-closeplay not block.

only block work firefox add-on Pan

adblock plus, adguard, ublock can't block.

i test chrome and firefox

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
