### ISSUE TITLE
Novel WebRTC usage

### ISSUE THREAD

**Issue by pcastellazzi** [gorhill/uBlock#1799]
I found an interesting technique to hide ads at http://yts.ag

What they do is to create a span with `display: none`. As text, they use a base 64 encoded javascript code, you can find an example at (http://pastebin.com/40wD12Wm).

They add the script below at the end of their page to decode it and run it.

```
(function() {
  if (window.atob) {
    eval(window.atob(document.getElementById('jM5v2EpV').innerHTML))
  }
})();
```

The interesting bit is the use of WebRTC on the snippet from pastebin. They connect to a known server and use the ICE candidates response to get a list of servers from which they build an URI which will redirect you to a random ad.

I wonder how to block this effectively?

**Comment by gorhill** [comment]
yts.ag##script:inject(noeval.js)

**Comment by pcastellazzi** [comment]
Awesome. Thank you very much.
