### ISSUE TITLE
uBlock makes YouTube slow

### ISSUE THREAD

**Issue by chris579** [gorhill/uBlock#1800]
### Describe the issue

YouBlock seems to make YouTube really slow (including the video stream). Over time, especially when using Autoplay or using Playlists, uBlock is blocking more and more ads. The count of blocked ads is increasing really fast. In the end the whole tab doesn't reacts any more and Chrome needs to be killed in process explorer. 
The workaround for this is to simply reload the page or close the tab if the count of blocked ads is too high. I can't say if this just happens on YouTube or on other video platforms too. 

I also deactivated uBlock or used the incognito mode. If so, this issue doesn't happens any more so I'm very sure that this is related to uBlock.

This issue was even worse when I had more filter lists activated than now. After deactivating quite a lot I can play more videos in a row before the tab hangs up.

### One or more specific URLs where the issue occurs

[http://youtube.com](YouTube)

### Screenshot in which the issue can be seen

![](https://i.gyazo.com/0efb0ea3f83384e0c5287b97ff2c747c.png)

### Steps for anyone to reproduce the issue

Just use Autoplay on YouTube or let a playlist play in the background while working. After some time the video streaming is going to stop and the tab won't react any more.

### Your settings

- Browser/version: Google Chrome 51.0.2704.103 m
- uBlock Origin version: 1.7.6

##### Your filter lists

- uBlock filters‎
- uBlock filters – Badware risks‎
- uBlock filters – Experimental
- uBlock filters – Privacy‎
- uBlock filters – Unbreak‎
- Adblock Warning Removal List‎
- Anti-Adblock Killer | Reek‎
- EasyList‎ (forums.lanik.us)
 
- Basic tracking list by Disconnect‎
- EasyPrivacy‎ (forums.lanik.us)
- Fanboy’s Enhanced Tracking List‎ (forums.lanik.us)

- Malvertising filter list by Disconnect‎
- Malware Domain List‎ (malwaredomainlist.com)
- Malware domains‎ (www.malwaredomains.com)
- Malware domains (long-lived)‎ (www.malwaredomains.com)
- Malware filter list by Disconnect‎
- Spam404‎ (www.spam404.com)
- Fanboy’s Annoyance List‎ (forums.lanik.us)
- Fanboy’s Social Blocking List‎ (forums.lanik.us)

- Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us)
- hpHosts’ Ad and tracking servers‎ (hosts-file.net)
- DEU: EasyList Germany‎ (forums.lanik.us)
- EU: Prebake - Filter Obtrusive Cookie Notices‎ (github.com)

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Any case of "seems ... really slow" will have to be made using with competent profiling evidence. I profile all the time at development, and vague "feeling of slowness" won't cut it. Make the case.

**Comment by chris579** [comment]
> use the browser's profiling tools

Quite funny as you're presupposing that every user that is reporting issues here is able to do this.

This is not just a "feeling" it's quite a fact that my browers tab is hanging up.

**Comment by gorhill** [comment]
> Quite funny as you're presupposing that every user that is reporting issues here is able to do this

You are pre-supposing I have an infinite amount of time to go on a chase to validate everybody vague feelings that there is an issue with uBO. You provide absolutely no evidence,  just "YouBlock seems to". If you are unable to profile, this is a hint you are making a wild guess, which more often than not are alwats wrong. _Make the case_, this is how issue trackers are best used, and it's not specific to uBO's one.

- Profiling tool is available to everybody in the dev tools of the page.
- Look at Chrome's task manager, see how is CPU usage of uBO when you say you have the issue, and also the CPU usage of the Youtube page.

**Comment by gorhill** [comment]
How much memory your computer has?

**Comment by chris579** [comment]
16 GB

**Comment by gorhill** [comment]
I will let Youtube play the whole day and analyze the page using the dev tools at the end of the day.

**Comment by Hrxn** [comment]
You did not state the OS. What is it, Windows? ("Process Explorer")

Will see if I can reproduce it in some way.

**Comment by romainPrignon** [comment]
Hello :-)
It's the same for me. Almost all video stop playing after a while.
But, it don't seems to be related to ublock. I used adblock plus and I switch to uBlock for this reason.

I'm sure it is related to ads because it works when I disable adblock, ublock, etc

I'm not an expert in adblock so I don't know where I can report this ?
Here's a screenshot, maybe it can helps
![Uploading bug.png…]()

**Comment by gorhill** [comment]
Results of the 24h+ test is that there was no hang, no CPU issues.
