### ISSUE TITLE
Why is a separate extension required to deal with websockets ?

### ISSUE THREAD

**Issue by XorgonTheTypesafe** [gorhill/uBlock#1801]
As opposed to having it's functionality added to uBlock

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1604#issuecomment-216276710

**Comment by gorhill** [comment]
The websocket wrapper has to be injected unconditionally as early as possible and on every web page, so this means it can't be disabled if ever it is found to cause an issue -- this would required to disable uBO in the _extensions_ panel.

**Comment by XorgonTheTypesafe** [comment]
Thanks, so if I'm understanding correctly this is a chromium-specific problem that required a wrapper around the WebSocket object and the difference between the wrapper behavior and expected native behaviour broke alot of things at some point. Where can I find an explanation of the underlying chromium issue ?
Also wouldn't it be possible to save the original WebSocket methods and restore them when the extension is disabling (that is to de-inject the wrapper when disabling) ?
Also, also - isn't it legitimate to expect (or even force) a full web page refresh when ublock origin is disabled ?
