### ISSUE TITLE
ublock origin not working

### ISSUE THREAD

**Issue by ghajini** [gorhill/uBlock#1802]
antiadblock killer not working with ublock origin 1.7.6 installed

url=  http://q.gs/A9cNn

all default settings

![screenshot 4](https://cloud.githubusercontent.com/assets/20338483/16715238/dbbdbbb6-46f7-11e6-8fdf-1bb4968ecd64.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/20338483/16715239/dbc675e4-46f7-11e6-8052-4ad2d6ccf92c.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ghajini** [comment]
open thread
