### ISSUE TITLE
antiadblock killer not working with ublock origin

### ISSUE THREAD

**Issue by ghajini** [gorhill/uBlock#1803]
![screenshot 4](https://cloud.githubusercontent.com/assets/20338483/16738404/22ba85f6-47b3-11e6-9319-de424a028c7b.png)
describe the issue=
on going to following url , site advise me to block advert blocking extension though i have installed tampermonkey with antiadblock killer and aak list subscribed and enabled...........

One or more specific URLs where the issue occurs

http://q.gs/A9cNn

steps to reproduce=
go to q.gs/A9cNn
it will give warning as per screenshot or see here 
https://postimg.org/image/ok6f7hh87/

your settings=
all default settings alongwith 
tampermonkey , antiadblock killer script and antiadblock killer list installed,enabled.

browser version= google chrome Version 51.0.2704.106 m (64-bit) on windows 10 64 bit

ublock origin version = 1.7.6

your custom filter list=
aak list (anti adblock killer)
youtube : pure video experience

issue is only with ublock origin and it us not with adblocker plus extension

**Comment by ghajini** [comment]
![Uploading dbbdbbb6-46f7-11e6-8fdf-1bb4968ecd64.png…]()
![Uploading dbc675e4-46f7-11e6-8052-4ad2d6ccf92c.png…]()

**Comment by Betsy25** [comment]
FYI, Can't help you, but there are a couple of reports on the [Easylist forum](https://forums.lanik.us/viewforum.php?f=62) about adf.ly

**Comment by ghajini** [comment]
iam using method to block adf.ly as per https://github.com/reek/anti-adblock-killer....it works fine with adblocker plus extension.....the method of anti-adblock killer not working with ublock origin....more info down
https://github.com/reek/anti-adblock-killer/issues/1733

gorhill need to work with ublock origin because adblockerplus works finely

**Comment by gorhill** [comment]
If you add the filter `@@||adf.ly^$domain=q.gs`, does it work?

**Comment by ghajini** [comment]
worked

**Comment by ghajini** [comment]
fix this in ublock origin itself so that i don't need to add your filter....see how adblock plus works without needing this filter........

**Comment by gorhill** [comment]
The issue is not in uBlock Origin itself, it's because Peter Lowe's block `adf.ly`. Un-select Peter Lowe's list if you want the same behavior as ABP, or select Peter Lowe's in ABP of you also want the same issue in ABP.

**Comment by Paviluf** [comment]
Is there nothing that can be done in µBlock to make the anti-adblock-killer work in those particular cases ?

**Comment by ghajini** [comment]
again stopped working @gorhill 
http://q.gs/AHm4n
![screenshot 7](https://cloud.githubusercontent.com/assets/20338483/17817792/fc857714-665d-11e6-8666-08d75024f26f.png)
