### ISSUE TITLE
uBO WS is easy to circumvent (at least in Google Chrome)

### ISSUE THREAD

**Issue by lainverse** [gorhill/uBlock#1805]
### Describe the issue
I've installed latest uBO (1.7.6) and uBO WS (1.1), and then did this in the console:
```
> var s = new WebSocket('wss://echo.websocket.org');
> s

WebSocket {}

> s.onclose = function(e) {window.someobj = e.target;};
> s.close()
> var j = new someobj.__proto__.constructor('wss://wsp.marketgid.com/ws');
> j

WebSocket {url: "wss://wsp.marketgid.com/ws", readyState: 1, bufferedAmount: 0, onopen: null,
onerror: null…}
```
While direct connection through call to `new WebSocket('...')` ends up being blocked it's possible to circumvent uBO through a connection to something harmless and then access real WS through `event.target.__proto__.constructor`.

### One or more specific URLs where the issue occurs

Anywhere, just open the console and type that code.

##### Your filter lists

Default filter lists + RU AdList.

**Comment by gorhill** [comment]
Would you mind reviewing changes to fix the issue? <https://github.com/gorhill/uBO-WebSocket/commit/6e61c3d932b1d04c363e1a8de67f22ff61260410>.

**Comment by lainverse** [comment]
I've tested your fix and it works fine.
