### ISSUE TITLE
Remove empty wiki pages

### ISSUE THREAD

**Issue by z3ntu** [gorhill/uBlock#1807]
(https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-%C2%B5Block-everywhere-except)
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-%C2%B5Block-everywhere-except...-(blacklist-mode)
The last one is really completely empty without redirection.

**Comment by gorhill** [comment]
Fixed as suggested.
