### ISSUE TITLE
Q regarding inline scripts on chrome

### ISSUE THREAD

**Issue by chrcoluk** [gorhill/uBlock#1808]
is there a point in using an advanced rule for blocking inline scripts by default on a whitelist basis in chrome? As I read this only works in firefox due to chrome developers refusing to add a feature for it.

Every site seems to function as if JS is completely disabled when its on, so ideally if you can verify what I am thinking would be appreciated, thanks.

**Comment by gorhill** [comment]
Inline scripts can be disable on Chromium-based browser as well.

**Comment by chrcoluk** [comment]
how?

Sorry there is no documentation on it and the answer was vague.

If I enable inline script filtering all javascript on page is blocked.
