### ISSUE TITLE
[QUESTION] Block Google Translate Page bar

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#1809]
Hello,

Firefox 47.
Languages: Hebrew, English.

In many sites (e.g. http://www.newegg.com/global/nl) I get  the [Google-Translate-This-Page](https://s32.postimg.org/eaow2sc3p/image.png) bar.
How can I block it in *all sites*?

I'd appreciate your help.
BR

**Comment by jjohns71** [comment]
Have you tried going into 'about:config' and setting 'browser.translation.detectLanguage' Value to 'false'?

**Comment by Yaron10** [comment]
Hello jjohns71,

Thanks for replying. I appreciate it.

`browser.translation.detectLanguage` is set to `false`. The problem is there.

BR

**Comment by jjohns71** [comment]
Hi Yaron10,

No problem, please mark issue as closed.
Thanks

**Comment by Yaron10** [comment]
Hello jjohns71,

I'm afraid I haven't been clear enough.
The problem exists even if  `browser.translation.detectLanguage` is set to `false`.
I'm looking for a way to block that bar.

Thanks again.
BR

**Comment by aggat** [comment]
Add `||google.com/translate_a/element.js?cb=googletranslateelementinit`
to `My filters`

**Comment by Yaron10** [comment]
Hello aggat,

That's great. Thank you very much.

BR
