### ISSUE TITLE
Youtube player bug. 

### ISSUE THREAD

**Issue by Lorfa** [gorhill/uBlock#181]
I'm getting a very strange bug in which when uBlock origin is activated, the youtube player button bar is larger than normal with larger buttons. It doesn't matter if I add exceptions to youtube.

To illustrate, here is how they look normally: http://i.imgur.com/aj4RDaI.png

I used chrome's "incognito" mode which disables extensions by default to illustrate how they look normally here: http://i.imgur.com/aj4RDaI.png

..and this is how they look when uBlock origin is running: http://i.imgur.com/9FbKJ12.png

This is actually incredibly annoying, and I hope some kind of fix exists or for an update that fixes it because otherwise uBlock origin is awesome. It's had the biggest positive impact on my browsing experience since chrome came out.

Thank you for your time.

**Comment by gorhill** [comment]
Can't reproduce with the provided details.

**Comment by anewuser** [comment]
> ..and this is how they look when uBlock origin is running: http://i.imgur.com/9FbKJ12.png

The extension button is grayed-out in this screenshot. That shows that it is disabled.

**Comment by Lorfa** [comment]
It isn't 'completely' disabled, as the phenomenon only occurs when enabled.

As for provided details: 

uBlock Origin 0.9.6.0

Chrome Version 42.0.2311.135 m

Windows XP SP3

The other extensions I have are Stylish 1.3.1 and Speed Dial 2.5.7, I tried disabling them but this had no effect on the issue.

I did not change any uBlock settings, other than as I mentioned, whitelisting www.youtube.com. This has no effect on the issue as I have tested on and off.

As for URL, _any_ youtube video. For example: https://www.youtube.com/watch?v=5LMPXah4dG4

**Comment by gwarser** [comment]
New youtube player design. Changes when you are logged in / logged out.

**Comment by gorhill** [comment]
Still can't reproduce using provided information. Controls look both the same whether incognito or not, whether signed in or not.

**Comment by seanrand** [comment]
As gwarser said, [it's the new youtube player design](http://www.popularmechanics.com/technology/design/a15049/new-youtube-player/). In incognito you are logged out of your Google account and have the old design.

**Comment by Lorfa** [comment]
My mind is blown. As I completely disabled the extension and it's still showing up that way.

It appears as the old player in incognito mode, as well as firefox and firefox private browsing.

So I mean, installing uBlock somehow triggered the use of this new player? It's too timely to be a coincidence. Still this is really wild.

I tried changing the value of and also deleting the cookie VISITOR_INFO1_LIVE, no dice to get the old player back. I know this can be done because I still get it in incognito mode! Logging in/out has no effect, only incognito mode does.

Any idea on how to trick youtube into giving me the old player?

**Comment by gorhill** [comment]
> too timely to be a coincidence

Yet it's the most likely explanation.

**Comment by lewisje** [comment]
> Any idea on how to trick youtube into giving me the old player?

Delete your YouTube cookies and see whether that works; I actually deliberately got the player by editing my cookies, and then to diagnose a problem that recently cropped up I deleted them, and I got the old player back after I logged back in (but your account might have been specially selected to get the experiment whether you opt in or not, automatically setting that special cookie at every login).

**Comment by Lorfa** [comment]
@ lewisje it worked! Brilliant! Thanks a bunch.
