### ISSUE TITLE
uBO 1.7.7b12 conflict with RUAdlist CSS Fixes on kg-portal.ru

### ISSUE THREAD

**Issue by TheFinalCut83** [gorhill/uBlock#1810]
### Describe the issue

It seems that the newest uBO beta version is in conflict with RUAdlist CSS Fixes (installed in Stylish extension) on mentioned site. With uBO 1.7.7b12 and newest RUAdlist CSS Fixes (14.07.2016) a grey margin appears below the menu bar regardless Stylish (with RUAdlist CSS Fixes) is enabled or not ([Scr 1 - 1.7.7b12, Stylish is on](http://i.imgur.com/xxIquys.jpg), [Scr 2 - 1.7.7b12, Stylish is off](http://i.imgur.com/F8k3FRA.jpg)). With uBO 1.7.6 all is ok when Stylish is on ([Scr 3 - 1.7.6, Stylish is on](http://i.imgur.com/9tYD49r.jpg), [Scr 4 - 1.7.6, Stylish is off](http://i.imgur.com/jvnhq65.jpg)). All is ok also in Slimjet 11 with uBO 1.7.6 ([Scr 5](http://i.imgur.com/XYwxYKu.jpg)) and Cyberfox with ABP (updated RUAdlist+Easylist) ([Scr 6](http://i.imgur.com/9TxkB3z.jpg)). RUAdlist CSS Fixes uses [that code (Scr 7)](http://i.imgur.com/CMAQioM.jpg) for the mentioned site.

### One or more specific URLs where the issue occurs

http://kg-portal.ru/

### Your settings

- Browser/version: Firefox 48.0b7 / Cyberfox 47.0.1 / Slimjet 11.0.1.0 (Chromium 51.0.2704.84)
- uBlock Origin version: 1.7.7b12

##### Your filter lists

uBlock filters
uBlock filters – Badware risks‎
uBlock filters – Privacy‎
uBlock filters – Unbreak‎
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList
EasyPrivacy‎
Malvertising filter list by Disconnect‎
RUS: Adguard Russian Filter
RUS: BitBlock List
RUS: RU AdList

**Comment by gorhill** [comment]
The issue is in _Adguard Russian Filter_ list, there is this rule: `kg-portal.ru#$#.des_front { height: 300px!important; }`. It should be changed to `kg-portal.ru#$#.des_front { height: auto !important; }`.

**Comment by gorhill** [comment]
@ameshkov, you may want to fix the filter in _Adguard Russian Filter_.

**Comment by TheFinalCut83** [comment]
Many thanks, but how can different site appearance made possible with 2 different uBO versions, but with absolutely equal set and version of filters?

**Comment by ameshkov** [comment]
@gorhill "height: auto" breaks the page layout in our case (i don't get why it works ok in case of that stylish extension).

Anyway, changed it to 200px, website looks good now:
https://github.com/AdguardTeam/AdguardFilters/commit/9e9d066053239580ac5e2f594cf5275dc959cb10

**Comment by ameshkov** [comment]
@TheFinalCut83 @gorhill has recently added support for CSS injection rules which are widely used in Adguard filters.

**Comment by gorhill** [comment]
> but how can different site appearance made possible with 2 different uBO versions

You are using 1.7.7b12, see [release notes](https://github.com/gorhill/uBlock/releases) for that version.
