### ISSUE TITLE
Images don't show even creating filters allow it

### ISSUE THREAD

**Issue by Connor37** [gorhill/uBlock#1811]
### Describe the issue

The issue is that when I browse the page [Softpedia](http://news.softpedia.com/) with the EasyList enabled, the images won't show because of the filter from the list. So I created the filter to allow the image to be shown, but it just won't load for me.
Also, the image won't show because of the cosmetic filtering which I've disabled for the site, but there still remain some won't load.

### One or more specific URLs where the issue occurs

[Softpedia](http://news.softpedia.com/)

### Screenshot in which the issue can be seen

Without cosmetic filtering
![http://i.imgur.com/kNm7Wm3.png](http://i.imgur.com/kNm7Wm3.png)

With cosmetic filtering
![http://i.imgur.com/ir8XR1p.png](http://i.imgur.com/ir8XR1p.png)

The logger with the allowed filter
![http://i.imgur.com/cLj2Jsb.png](http://i.imgur.com/cLj2Jsb.png)

### Steps for anyone to reproduce the issue

1. Enabled the EasyList
2. Visit the page [Softpedia](http://news.softpedia.com/)
3. Toggle disable cosmetic filtering
4. Add allowed filter @@||i1-news.softpedia-static.com$domain=news.softpedia.com,image

### Your settings

Default settings

- Browser/version: Google Chrome 51.0.2704.106 m (64-bit) 
- uBlock Origin version: 1.7.6

##### Your filter lists

![http://i.imgur.com/SbEFOEL.png](http://i.imgur.com/SbEFOEL.png)

##### Your custom filters (if any)

![http://i.imgur.com/NU5pEEs.png](http://i.imgur.com/NU5pEEs.png)

**Comment by gorhill** [comment]
Test with only uBO + default settings. report whether there is still an issue.

**Comment by gorhill** [comment]
Strike this, I just tested with uBO + default filters and all works fine. You will have to investigate yourself this issue, it's not a uBO one, most likely a filter list one and/or other extension one.
