### ISSUE TITLE
[Questions] Google Redirect and Facebook popup

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#1812]
Hello,

I wonder if it's possible to disable Google Redirect using uBO only (without any other scripts/extensions).
***
Another question:
How can I block Facebook Sign-In popup?

I'd appreciate your help.

Best regards.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
