### ISSUE TITLE
Google Searching is not working

### ISSUE THREAD

**Issue by Vitaio** [gorhill/uBlock#1815]
### Describe the issue
Please check this video: https://youtu.be/Q-BZor84ZzE

### One or more specific URLs where the issue occurs

All Google Searching is not working.

### Your settings

- Windows 10 Pro 64bit
- Browser/version: Google Chrome 51.0.2704.106 m (64-bit)
- uBlock Origin version: uBlock Origin v1.7.6

My email is: bbence16@gmail.com

Best wishes,
Bence

ps: What can I do for now? :) I really hate Google Ads, so I prefer uBlock!!! :P

**Comment by gorhill** [comment]
Be sure uBO is active **when the page load**. Turning it on after the page has loaded won't work.

**Comment by Vitaio** [comment]
When I turn on, the Google Search not working. The mouse is loading and that's all. :disappointed:
