### ISSUE TITLE
uBlock prevents quitting of Chrome on macOS Sierra

### ISSUE THREAD

**Issue by meisterwerkmedien** [gorhill/uBlock#1817]
### Describe the issue

When uBlock Origin is installed in Chrome on macOS Sierra, I am not able to shut down Chrome via CMD+Q, for example (worked before installing Sierra). You have to use force quit, in order to close Chrome. I have already reinstalled Chrome without any other extensions to test wether the issue actually comes from uBlock. As soon as I install uBlock on the clean Chrome, the problem occurs. If I delete uBlock, the problem disappears and I can easily quit Chrome as usual.

### One or more specific URLs where the issue occurs

No specific URL necessary, doesn't even work on about:blank or the settings page.

### Screenshot in which the issue can be seen

Unable to make a screenshot of this bug.

### Steps for anyone to reproduce the issue

1. Open Chrome (with uBlock Origin installed)
2. Close Chrome by using CMD+Q
=> The window closes, but the dot below the dock icon remains and you cannot open Chrome, it's officially freezed.
3. You have to right click on the dock icon and choose force quit, in order to actually quit it and being able to reopen Chrome.

### Your settings

Default settings, clean Chrome install. The only extensions is uBlock Origin.

Chrome Version: 51.0.2704.106 (latest stable)
uBlock Origin Version: 1.7.6 and 1.7.7
macOS Version: 10.12 Public Beta

##### Your filter lists

Default filter lists, clean uBlock Origin install.

##### Your custom filters (if any)

None, clean uBlock Origin install.

**Comment by anewuser** [comment]
If this doesn't happen on OS X, you should report this bug to the Apple developers instead, since you are using their experimental operating system.

**Comment by meisterwerkmedien** [comment]
Many apps that worked under OS X before, won't work under macOS Sierra. However, it's not Apple who will fix it for the developers. I'm not gonna say it's definitely a problem that needs to be solved by uBlock, but I'd like them to look into it. Maybe there is something in the code that conflicts with something handled differently in Sierra now. Or maybe it's something the Chrome developers need to fix. In both cases, Apple won't be of much help. So, please consider looking into this.

**Comment by gorhill** [comment]
> maybe it's something the Chrome developers need to fix

No doubt. Bring this issue to Chrome devs.
