### ISSUE TITLE
1.7.7b14 regression :style operator

### ISSUE THREAD

**Issue by olgon** [gorhill/uBlock#1818]
With 1.7.7b13 this filter worked
`seasonvar.ru##body:style(padding: 0 !important;)`
used to remove large 300px padding top
http://seasonvar.ru/ 

- Browser/version:  Firefox 47
- uBlock Origin version:  1.7.7b14

I noticed that
`seasonvar.ru##html > body:style(padding: 0 !important;)` 
works so close issue

**Comment by olgon** [comment]
Although I found workaround and closed the issue
but I want to clarify whether this is the expected change in behavior beta 14

**Comment by gorhill** [comment]
It is the expected behavior. `html` element will never need to be hidden, hence for plain standard cosmetic filtering, it is ok to use the `:root` prefix. For restyling though, it may very well happen that the `html` element needs to be restyled, hence we can't use `:root` in such case.
