### ISSUE TITLE
Yandex (biggest search engine in Russia) ads not blocked

### ISSUE THREAD

**Issue by ethaniel** [gorhill/uBlock#1819]
### Describe the issue

The ads in Yandex search results are not blocked.
Notice the first 2 ads + the third one is Yandex promoting it's own website.
They are not gone.

### One or more specific URLs where the issue occurs

https://yandex.ru/search/?msid=1468764087.61307.22887.12284&text=%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B8%D1%80%D1%8B%20%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&lr=10620

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
![image](https://cloud.githubusercontent.com/assets/941973/16901046/d5f71762-4c61-11e6-87c8-38d14fc475e0.png)

### Steps for anyone to reproduce the issue

1. Goto URL
2. See results - https://yandex.ru/search/?msid=1468764087.61307.22887.12284&text=%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B8%D1%80%D1%8B%20%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&lr=10620

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Google Chrome 51.0.2704.103 (64-bit)
- uBlock Origin version: 1.7.6.

##### Your filter lists

Default lists for Russia (I didn't touch this setting)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ethaniel** [comment]
This is not an issue with 3-rd party lists. Yandex uses an evading algorithm which can't be fixed through lists. It makes it's ad blocks indistinguishable from other search results. The block can only be found through specific text content - but that needs to be addressed on ublock programming level, not lists.

**Comment by gorhill** [comment]
It is a filter list issue -- I just needed to fine tune the existing one: <https://github.com/uBlockOrigin/uAssets/commit/346866b38241cc7462851194453d60a129cf41ce>.

**Comment by ethaniel** [comment]
![image](https://cloud.githubusercontent.com/assets/941973/18217305/c5714bba-7164-11e6-83cf-9580cc0d745a.png)

Nope, still evading. They have no specific class names or anything. Attributes are randomly generated. Only way to track them down is to search them by their contents. 

Like divs with class .serp_item with sub divs of class .organic__label that contain the word "Реклама". As far as I know this can't be done with lists - it needs actual coding.

![image](https://cloud.githubusercontent.com/assets/941973/18217353/f21abe4e-7164-11e6-95a4-afc87823b607.png)

**Comment by gorhill** [comment]
How about:

    yandex.ru##.serp-item:has(:scope > .organic > .organic__subtitle > .label_color_yellow)

**Comment by ethaniel** [comment]
@gorhill It worked! Thank you!

**Comment by ethaniel** [comment]
@gorhill can you please update uAssets with this change?

**Comment by gorhill** [comment]
I did two days ago: <https://github.com/uBlockOrigin/uAssets/commit/d0005559010f4e1f974056df895b971548bfb4f7>.
