### ISSUE TITLE
Peter Lowe’s Ad server list‎ blocks videos on explosm.net

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#182]
Here http://explosm.net/show/episode/148/Atta-Boy
Video from http://cdn.phoenix.intergi.com/1004219/videos/3588251/video-sd.mp4?hosting_id=1004219
Blocked by `127.0.0.1 intergi.com` from Peter Lowe list

**Comment by anewuser** [comment]
We are not Peter. Please report it directly to him and close this issue to mark it as solved.

**Comment by gwarser** [comment]
This is host file, not ABP filter.

**Comment by CrisBRM** [comment]
It's still a third party list in no way, shape or form related to uBlock. Take the problem to the maintainer of the list.

**Comment by gwarser** [comment]
https://github.com/chrisaljoudi/uBlock/issues/1087#issuecomment-85568153

> I do not have time to maintain filter lists **aside the one needed to address issues specific arising from the use of Peter Lowe's** hosts file by default.

**Comment by gorhill** [comment]
Yes, I will create exceptions to address issue with Peter Lowe's, that's mostly why _Unbreak_  filter list exist.

**Comment by gwarser** [comment]
Thank you.
