### ISSUE TITLE
Problem with cosmetic filtering

### ISSUE THREAD

**Issue by sooqua** [gorhill/uBlock#1820]
_I'm sorry for maybe not the smartest question, but I have struggled with this for a while and so I decided to seek help here._
The problem is that I want to:
**A)** Hide this stupid button:
![stupid button](http://i.imgur.com/2qNBSiL.png?1)
and
**B)** Keep the annotations on

### **1)** Disable cosmetic filtering.
_Result:_
My custom filters get ignored and the button doesn't hide. (see pic above)
The annotations are displayed.
### **2)** Enable cosmetic filtering
**2.1) Whitelist all requests (global "all" is green) - in order for annotations to show up.**
_Result:_
That doesn't affect cosmetic filters (annotations are **not** displayed) but the button is hidden.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sooqua** [comment]
Meh... Do you know how much time I spent with that markdown? :D + English is not my first language
I found that it would be more readable the way I wrote it..

**Comment by gorhill** [comment]
> Do you know how much time I spent

You disregarded CONTRIBUTING, which purpose is to save time for everybody, but especially mine as the maintainer of this project and as the one who has to deal with invalid issues.
