### ISSUE TITLE
OSX kernel_task memory bloated with ext enabled with chrome

### ISSUE THREAD

**Issue by datajerk** [gorhill/uBlock#1821]
### Describe the issue

OSX kernel_task memory bloated with ext enabled with chrome.  4GB increase in RAM usage.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

Default

- Browser/version: Chrome Version 51.0.2704.103 (64-bit)
- uBlock Origin version: 1.7.6

##### Your filter lists

Default.

**Comment by datajerk** [comment]
Chrome version: Version 51.0.2704.106 (64-bit) update appears to fix issue.  Cannot reproduce with this version.

**Comment by datajerk** [comment]
False alarm, just needed to wait a bit longer.

How to reproduce:

1. Start with OSX, latest os, latest chrome 64-bit, latest ublock
1. Open Chrome.  
1. Disable ublock
1. Restart chrome with your existing tabs etc... just ignore them for now
1. Create a new profile "People, add person"
1. Create a new window and change to "Person 2" or whatever was the new person.
1. Go to setting/extenions, add extenions, add ublock orgin
1. Go to youtube or some place like that that will trigger ublock
1. Sit back and wait for 10s of min, watch kernel_task grow about 4GB in size (RAM).
1. From person 2, uncheck ublock, Close person 2 window, restart Chrome to get back memory from kernel_task.

**Comment by gorhill** [comment]
I don't have OSX, and there are no known issues of "kernel_task grow about 4GB in size" on other OS.

**Comment by datajerk** [comment]
Fairly convinced this is a chrome issue, going to close this until I can get more details.
