### ISSUE TITLE
Cannot subscribe to list without .txt extension

### ISSUE THREAD

**Issue by SqualidLowlyBean** [gorhill/uBlock#1823]
I cannot subscribe to custom list http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/
After parsing this url in ublock origins options it has 0 filter available. I think it's due to lack of .txt extensions at the end of link.

firefox 47
uBlock Origin v1.7.6

**Comment by gorhill** [comment]
Works fine from here. Be sure to click _Apply changes_ after you add the custom URL.

**Comment by SqualidLowlyBean** [comment]
It doesn't work for me. I cannot find the reason.
I'm using other custom filters and they works.

**Comment by gorhill** [comment]
> I cannot find the reason.

Show me a screenshot of the whole 3rd-party pane in the dashboard.

**Comment by SqualidLowlyBean** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/20515492/16921718/e996df9e-4d12-11e6-9ebe-492294f5029a.png)

I had to collapse some list to cover whole panel in single screen, but I don't think they are relevant.  I tested some things and it looks that every filter labeled as "http" doesn't work. In asset viewer it's blank.

**Comment by gorhill** [comment]
Click _Update now_.

**Comment by SqualidLowlyBean** [comment]
Ok, it was umatrix which blocked those requests.
Thx for help.
