### ISSUE TITLE
If you are using TBB, Easylist, easyprivacy and fanboy lists are blocked by Cloudflare.

### ISSUE THREAD

**Issue by fastcopy** [gorhill/uBlock#1824]
### Describe the issue
As title said, if you install this add-on to TBB and subscribe easylist/fanboy server's list
uBO failed to update it.

Copying Original reporter: Reddit
https://www.reddit.com/r/TOR/comments/4tf0xr/are_you_using_adblocker_with_tbb_isnt_easylist/

### Steps for anyone to reproduce the issue

1. Install TBB.
2. Install uBO and subsribe.
3. Cloudflared.

1. In TBB, go to easylist list(~~~~~.txt)
2. Welcomed by Cloudflare.

**Comment by gorhill** [comment]
I don't control EasyList server, you need to report to the maintainers: <https://github.com/easylist/easylist.github.io>.

**Comment by fastcopy** [comment]
BTW gorhill, they moved to easylist.to. Check it out.

**Comment by anewuser** [comment]
> If you should encounter unwanted items or problems with the EasyList filter lists you should report the issues in the [EasyList Forums](https://forums.lanik.us/).

**Comment by fastcopy** [comment]
@anewuser

I know that! In fact, I always report something to official. I had to report this to Github instead, BECAUSE, easylist forums is also blocking Tor users. Cloudflare is really pi**ing us off. (adding "T1" to whitelist, and just adding Captcha to forum registration will enough I think!)

@easylist

As a Tor user, I thank your kind heart!
Now I can access to https://easylist.to/easylist/easylist.txt without problem! ... for now.
