### ISSUE TITLE
uBlock Origin crashes Chromium on OS X 10.11

### ISSUE THREAD

**Issue by 1byte2bytes** [gorhill/uBlock#1825]
### Describe the issue

With uBlock Origin installed on the latest Chromium (built last night, has all my Google API keys included so extensions do work) the browser will crash upon visiting certain pages. Even with no other extensions besides uBlock Origin installed the issue will occur. I'm using  
Chromium Version 54.0.2800.0 (64-bit) and uBlock Origin v1.7.6. I am using OS X 10.11.5 on my computer itself. No error message shows up, no dialogue from OS X that my application crashed. Visit a page that invokes this error and Chromium just disappears. This error occurs even when clearing the cache and application data for Chromium, removing all of my extensions and user data.

http://pastebin.com/EFvRfJYv

### One or more specific URLs where the issue occurs

http://www.reddit.com/

### Steps for anyone to reproduce the issue

1. Get the latest Chromium
2. Install uBlock Origin
3. Visit a page that invokes the error

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chromium Version 54.0.2800.0 (64-bit)
- uBlock Origin version: v1.7.6

##### Your filter lists

No settings changed for uBlock Origin or Chromium

**Comment by gorhill** [comment]
uBO is written in javascript: javascript does not crash like this. This is a browser issue, report to Chromium devs.

**Comment by 1byte2bytes** [comment]
Okay, thank you!

**Comment by mmillar-bolis** [comment]
I can also confirm, if others are curious, that this is happening on Mac OS X 10.9.5 using Chrome  51.0.2704.0 and 51.0.2743.82.
