### ISSUE TITLE
New :style() filters don't override !important rules

### ISSUE THREAD

**Issue by hant0508** [gorhill/uBlock#1826]
### Describe the issue

Many ad CSS rules are marked as `!important`. Stylish overrides this rules with your own, if you've marked it as `!important` too, but uBO can't do it. 

### One or more specific URLs where the issue occurs

http://redkassa.ru

### Screenshot in which the issue can be seen

![2016-07-19 13 53 18](https://cloud.githubusercontent.com/assets/12861787/16947961/21c2e376-4dc3-11e6-9239-d0aa7f350e99.png)

### Steps for anyone to reproduce the issue

1. Follow [this link](http://redkassa.ru/)
2. Add it to your filters: `redkassa.ru##body:style(background:none!important;)`
3. Open DOM Inspector (Shift+Ctrl+C for FF) and select `body`
4. Now you can see that `background: url... !important;` isn't overridden and your custom `background: none!important;` isn't applied

### Your settings

- Browser/version: Mozilla Firefox 49.0a2 on Debian GNU/Linux
- uBlock Origin version: 1.7.7b14

### Your filter lists

Default filter lists + RU AdList + [my own list](https://github.com/hant0508/uBlock-fillters)

**Comment by gorhill** [comment]
Try `redkassa.ru##html > body:style(background:none!important;)`, this will cause your selector to have higher CSS specificity and thus get the upperhand.

I did consider such cases could occur, however for now I rather not add code if this can be handled merely by crafting a better filter -- which is the case here.

**Comment by hant0508** [comment]
Thanks, now it works. But should I always specify full path to the element I want to restyle, if it has `!important` rule? It's not always easy to do, e.g. when there many elements with different paths or when the path is too long.

Btw, `style()` filters aren't shown in logger. Is it normal?

**Comment by gwarser** [comment]
https://specificity.keegan.st/

**Comment by gorhill** [comment]
> should I always specify full path to the element I want to restyle

No. The point is just to do whatever is needed to increase the specificity. In the current case, this was the easiest way. It could have been `redkassa.ru##body:not([id]):style(background:none!important;)`.
