### ISSUE TITLE
uBLOCK Origin Not  Updates Easy List And Easy Privacy Please Fix This  >>>>>>>>>

### ISSUE THREAD

**Issue by applesam** [gorhill/uBlock#1828]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by applesam** [comment]
![fireshot screen capture 001 - -](https://cloud.githubusercontent.com/assets/20497954/16978081/a347d226-4e77-11e6-8dbc-a108d5852b30.png)

**Comment by gorhill** [comment]
What do you see when you click [this link](https://easylist.to/easylist/easylist.txt)?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
