### ISSUE TITLE
ubo didn't block images in Android Firefox "* * image block"

### ISSUE THREAD

**Issue by xsectoxu** [gorhill/uBlock#1829]
v1.7.6

1. Install uBO on Orfox(Android firefox).
2. In rules tab, I add & commit "* * image block".
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

3. https://(image gallery)/

ubo didn't block images. Why?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
