### ISSUE TITLE
uBO doesn't update lists if I add "behind-the-scene raw.githubusercontent.com * block" to rules

### ISSUE THREAD

**Issue by xsectoxu** [gorhill/uBlock#1830]
v1.7.6

1. Select some lists.
2. Update it.
3. On rules tab, add "behind-the-scene raw.githubusercontent.com * block".
4. Some days later, ubo doesn't update lists. Click update button never change numbers(and no connection observed).

I select non-raw.githubusercontent.com filters.
Why ubo doesn't connect to filter urls?

**Comment by xsectoxu** [comment]
no-remote-fonts: * true
    * * 3p-frame block
    behind-the-scene raw.githubusercontent.com * block

**Comment by harshanvn** [comment]
> ubo doesn't connect to filter urls?

It is because you blocked access to `raw.githubusercontent.com` from `behind-the-scene` scope.
If i am correct, It is where uBO origin fetches checksums and identifies if it needs to update a said filter or not..

**Comment by gorhill** [comment]
> Why ubo doesn't connect to filter urls?

Because you told it to block behind-the-scene network requests.
