### ISSUE TITLE
Changing uBlock settings via Selenium (Firefox)

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#1831]
I am doing automated testing where filtering ads from external sites is important. I would like to activate filters programmatically. Selenium allows the creation of a profile, adding extensions, and changing settings available in `about:config`, but uBlock doesn't expose a setting for which filters are turned on or off from the config.

- Browser/version: Firefox 45
- uBlock Origin version: 1.7.6

**Comment by gorhill** [comment]
Try `adminSettings`: <https://github.com/gorhill/uBlock/issues/531#issuecomment-125221801>.

**Comment by gorhill** [comment]
Closing because OP abandoned the issue.
