### ISSUE TITLE
"filter log entries" placeholder size too small

### ISSUE THREAD

**Issue by TonnesM** [gorhill/uBlock#1832]
On Firefox (any Aurora) and current uBlock dev version, the field carrying the "filter log entries" placeholder text in the Logger is a bit small, causing some locales to not display all its characters.
Can it be extended by e.g. 5 characters, possibly checking the strings for all locales (i.e. dependant on their max length, or by making it auto-adapt)?

**Comment by gorhill** [comment]
> some locales to not display all its characters

Which locales?

**Comment by TonnesM** [comment]
At least Dutch, which currently uses "logboekvermeldingen filteren" (though this may change). That's 28 characters, where 24 (and a half) chars are displayed so 24 seems to be max length. I didn't test but assume any locale exceeding 24 characters may suffer it - at a glance in Crowdin's view, this includes German, French, Spanish, and a number of others.

A general rule of thumb is to reserve space for other locales sized 1.3 x English size when possible, since in general the average l10n size is about +30% compared to English. And that's only an average; 18 x 1.3 = 24, but this may be a coincidence. ;)

**Comment by gorhill** [comment]
> making it auto-adapt

There was no width set for the input field, so it appears the browser does not adjust the width according to the placeholder. I set the field to be `18em` width at a minimum.

**Comment by TonnesM** [comment]
Thanks!
