### ISSUE TITLE
Wrong addresses and no download of fanboy ultimate on 1.7.6 build

### ISSUE THREAD

**Issue by Felipefpl** [gorhill/uBlock#1835]
First i'd like to thank the dev(s) for accepting my report i made a lot of months ago where i reported that ublock was bloated because of its severa embedded lists/3.5 MB size, now it's 1.5 MB and if you keep following this path soon you'll be less than 1 MB like adblock plus. ;)

I have these problems with ublock:

1 - the social section of ublock doesnt download the lists containend on it, it leads to a russian site which i believe it's dead/changed its address, in any case it would be MUCH better to download those lists directly from the source http://fanboy.co.nz/ http://fanboy.co.nz/filters.html

2 - i couldnt download fanboy ultimate, maybe for the very same reason, like above it's better to go for the source http://fanboy.co.nz/filters.html i downloaded it with adblock and it worked so the problem is with ublock. Also, i added the address manually on ublock and it didnt work. :/

A suggestion: since ublock had a section in the bottom dedicated to easylist from several countries maybe we could have something similar with fanboy's ones too. ;)

That's all, thank you for all your work on ublock and for your attention too.

**Comment by gorhill** [comment]
> the social section of ublock doesnt download the lists containend on it, it leads to a russian site

Be specific, "social section" is not specific enough. Just spell out exactly which URLs you are talking about.

The lists from the _Social_ section are downloaded from whether `https://easylist-downloads.adblockplus.org/` or `https://www.fanboy.co.nz/`, and Fanboy Ultimate is downloaded from `https://www.fanboy.co.nz/`, not from "a russian site".

**Comment by Felipefpl** [comment]
Social section IS specific enough since 1 - you wrote it yourself on ublock and 2 - you just said where the lists from social section on setting can be downloaded. ;)

Regarding the russian site, i deduced this since this is what is displayed on your extension, after all it contains the .ru extension right? ;)

If you dont want ppl to think they are downloading stuff from a russian site just update the addresses or remove them, as you wish.

Just in case you care and want to improve your app, i didnt try the easylist's addresses, which is something YOU should do once the site was moved https://easylist.github.io/ and since it moved the address to ALL lists changed too. ;)

Thanks for nothing.

**Comment by gorhill** [comment]
> Regarding the russian site, i deduced this since this is what is displayed on your extension, after all it contains the .ru extension right? ;)

I still can't make sense of what you are saying -- adding `;)` everywhere is completely of no help. _What_ contains the `.ru` extension?
