### ISSUE TITLE
Conflict with Joomla CMS administration (ISIS template)

### ISSUE THREAD

**Issue by AlphaStarrz** [gorhill/uBlock#1839]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Hi, since i've using ublock origine (Version 1.7.6) with firefox i encouter many problem with my CMS's template (Joomla) on administrator side and some time in frontend!!! This add-on cause conflict with any of my css or javascripts so it simply broke my template!!!
So this problem is going more  accurate after i've installing this following plugin in my website : https://www.nordmograph.com/extensions/index.php?option=com_virtuemart&view=productdetails&virtuemart_product_id=112&virtuemart_category_id=1&Itemid=58 

So note tha after removing ublock origine and installing another adblocking, even ublock! this problem has diseappear! 

### One or more specific URLs where the issue occurs
Can't give you my url because my website is still under construction
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 47.0
- uBlock Origin version: 1.7.6

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Filter list issue, site displays same with ABP with same filter lists. Investigate and report to EasyList/EasyPrivacy maintainers. Also, be more specific than _"simply broke my template"_, describe calmly and accurately the issue to the EasyList maintainers.
