### ISSUE TITLE
Blocks addons that use the sidebar

### ISSUE THREAD

**Issue by jluce50** [gorhill/uBlock#184]
Some addons utilize a sidebar to display data. This data is subject to blocking by uBlock but there is no way to interact with this data in order to add rules, etc. One example is the TickTick addon (task manager). The only way to get this addon to work is to completely disable uBlock.

**Comment by anewuser** [comment]
https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests

**Comment by jluce50** [comment]
I checked my Whitelist and "behind-the-scene" was already there, but the sidebar only loaded if I completely disabled uBlock.

**Comment by gorhill** [comment]
Somehow I missed that new issue. I will investigate.

Version 0.9.7.0 will come with a unified logger, it will be easier to diagnose the problem, as selecting a tab to inspect will no longer be necessary.

**Comment by gorhill** [comment]
By the way, you don't provide much details, I don't even know which browser you are using. Also, a link to the add-on with which the issue can be reproduced -- one not needed the creation of an account etc. is preferred.

**Comment by jluce50** [comment]
Apologies. I'm using multiple recent versions of Firefox on different computers. The extension is TickTick (https://addons.mozilla.org/en-US/firefox/addon/ticktick/?src=search). You should be able to see the problem without creating an account, but it will be more obvious if you sign in.

**Comment by gorhill** [comment]
Can you verify with the unified logger if now you can see (and act upon) whether network requests for the add-on are showing in the logger?

**Comment by jluce50** [comment]
Sorry for the delay. Yes, the requests do now show up in the logger. Thanks!

**Comment by gorhill** [comment]
I need to fix something in order for the popup to be filled properly when opened from the logger for the current scenario. Will fix asap.

**Comment by gorhill** [comment]
With the latest release (RC2), you will finally be able to access and set rules for the addon:

![d](https://cloud.githubusercontent.com/assets/585534/7683178/544e79a0-fd4b-11e4-99ec-f5c096f1abce.png)

**Comment by jluce50** [comment]
Brilliant, thanks!
