### ISSUE TITLE
How to install betas with FF48+ where there is NO way to allow unsigned addons to install?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [gorhill/uBlock#1840]
With Firefox 48 there is NO way to allow/bypass to install unsigned addons, officially. I'm hoping y'all found a way to do just that?

I'd like to always use the bleeding-edge build of ublock.

Much obliged!

**Comment by gorhill** [comment]
> I'd like to always use the bleeding-edge build of ublock.

Use Firefox beta or Nightly.

**Comment by gorhill** [comment]
Also, in case you are not aware, I push dev build of uBO on AMO. These dev builds are signed, see <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>.

**Comment by Unrepentant-Atheist** [comment]
This is such a bullshit from Mozilla...then again I do understand what with the amount of stupid users...oh well, thanks gorhill. Haven't been on Mozilla Addon Site for ages.

**Comment by gwarser** [comment]
http://www.ghacks.net/2016/07/30/firefox-unbranded-build-downloads/
https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds

>Latest release (pending - Firefox 48) builds: Incoming Aug 2, 2016 

:)

**Comment by gwarser** [comment]
How to override the Firefox Add-on Signing requirement
http://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

Only two config files placed inside Fx installation directory are needed.
