### ISSUE TITLE
Anti-Adblock-Killer doesn't work sometimes

### ISSUE THREAD

**Issue by Paviluf** [gorhill/uBlock#1841]
Hello,

I have this issue too https://github.com/gorhill/uBlock/issues/1803 and I was wondering if there something that can be done in µBlock to make the anti-adblock-killer work in those particular cases.

Thanks !

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Paviluf** [comment]
Fair enough :) I though I didn't need to do it since it's the following of an "old" issue that already fulfil the infos needed.

Sorry.
