### ISSUE TITLE
Compatibility with Firefox 49 E10s.

### ISSUE THREAD

**Issue by ankeshdave** [gorhill/uBlock#1842]
### Describe the issue
I am planning to upgrade to Firefox 49 (alpha/beta). This add-on already works well on chrome, will this be compatible on Firefox 49 with the multi process architecture change ??

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

It is compatible. Please do not open invalid issues.

**Comment by wolfblake** [comment]
According to [this](http://arewee10syet.com/#15) ublock origin is e10s compatible.

**Comment by gorhill** [comment]
Just to be clear, as opposed to what the page says, uBO is not shimmed and there are no CPOW issues.
