### ISSUE TITLE
Adblock Edge statement to wiki

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1844]
> By the way, I need to dispel a silly myth given how often it surfaces: Adblock Edge uses Adblock Plus filtering engine, so it is not more efficient than ABP. - https://github.com/gorhill/uBlock/wiki/uBlock-vs.-ABP:-efficiency-compared

Add something like: In fact Adblock Edge discontinued after version 2.1.9.1 in favor of uBlock Origin.

**Comment by gorhill** [comment]
I removed mention of Adblock Edge.

**Comment by davidhedlund** [comment]
@gorhill Thank you.
