### ISSUE TITLE
Filtering ads in other Extensions

### ISSUE THREAD

**Issue by MasTech** [gorhill/uBlock#1846]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Chrono DL Manager loads ads when viewing the options page for the add-on.
https://chrome.google.com/webstore/detail/chrono-download-manager/mciiogijehkdemklbdcbfkefimifhecn?hl=en

### One or more specific URLs where the issue occurs
chrome-extension://mciiogijehkdemklbdcbfkefimifhecn/ui/options.htm
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

Install the extension in Chrome/Chromium.
Open the settings page for the extension.

### Your settings

- Browser/version: Chromium Version 50.0.2661.94 (64-bit) / Chrome Version 50.0.2661.94 m (64-bit)
- uBlock Origin version: uBlock Origin v1.7.6
Default settings

##### Your filter lists

Default filter lists

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Extensions cannot intercept each other's network requests. Chromium-based browsers limitation.
