### ISSUE TITLE
hope add the function to remove the google result which is in the My filters list

### ISSUE THREAD

**Issue by czmecho** [gorhill/uBlock#1847]
just like the [Personal Blocklist (by Google)](https://chrome.google.com/webstore/detail/personal-blocklist-by-goo/nolijncfnkgaikbjbdaogikpmpbdcdef)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
