### ISSUE TITLE
ublock origin filters/code as an ICAP server

### ISSUE THREAD

**Issue by eskhool** [gorhill/uBlock#1848]
the logic, filters and rues in ublock would serve as a great ICAP server to block proxies at the network level. @gorhill, can you quickly provide your input as to the feasibility of this? Any major roadblock that you see that can't be done at the proxy server?

**Comment by anewuser** [comment]
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
I know nothing about ICAP, I would have to read about all this -- so can't provide quick input. Also as pointed out, the issue tracker is for issues, not to be used as a forum -- otherwise this is noise added to the tracker.
