### ISSUE TITLE
Requests of type font not handled in Firefox

### ISSUE THREAD

**Issue by norstbox** [gorhill/uBlock#185]
Open any web page which uses Web Fonts, for example [MDN](https://developer.mozilla.org/en-US/docs/Web/Reference/API)
- Network request logger show no requests of type `font`
- Web font can't be blocked by using filter.

Chromium free from the above issues.
## 

uBlock 0.9.6.0 and 0.9.6.1-rc.0
Firefox 37
Windows 8.1

**Comment by lewisje** [comment]
I noticed that the vAPI code (an attempt at cross-platform compatibility) [does try to recognize webfonts](https://github.com/chrisaljoudi/uBlock/blob/master/platform/chromium/vapi-background.js#L674) as having type `font` even though the webRequest API does not have that listed, and presumably they would be considered `other`: https://developer.chrome.com/extensions/webRequest#type-ResourceType

```javascript
        var ext = tail.slice(pos) + '.';
        if ( '.eot.ttf.otf.svg.woff.woff2.'.indexOf(ext) !== -1 ) {
            details.type = 'font';
            return;
        }
```

I'm not sure where in the code there is any attempt to convert `font` into a type recognized by webRequest, before deciding to block it.

**Comment by gorhill** [comment]
Font requests are merge down to `css`. I plan to add a scope-based switch to generally block web fonts.
