### ISSUE TITLE
dynamic filter column color coding blocked by firefox theming

### ISSUE THREAD

**Issue by Boruch-Baum** [gorhill/uBlock#1850]
In "advanced mode". the ublock pop-up display's global and local dynamic filter status uses only coding (red, green, grey). It should also identify its state using some form of text. One reason why is that when a user 'themes' the browser or sets default colors for web pages, the colors of the ublock pop-up are lost.

For example, using uBlock Origin v1.7.6 and firefox esr v45.2.0, navigate to page about:preferences#content, select 'colors', change the default text and background colors to white text on black background, and select the option to 'always..' over-ride web page defaults. Alternatively, select the check-box to use system colors, and 'always..' over-ride web page defaults. Return to any web page, select the ublock pop-up, and observe that the color-coding is masked.

Currently, my personal work-around is to use a second firefox extension, "toggle document colors". Whenever I bring up the ublock pop-up, I also press key sequence C-M-S-c in order to see the ublock color coding. However, this also re-renders all browser tabs.

**Comment by gorhill** [comment]
You are instructing Firefox to override documents' `color` and `background-color` CSS styles. I don't see what I can reasonable do.

**Comment by Boruch-Baum** [comment]
My suggestion is to additionally have text in the positions you now place the color, similar to what you already do in those columns with '+' and '-' to denote the order of magnitude of blocked items.

**Comment by gorhill** [comment]
The real flaw here is to assume that the only purpose of `background-color` is to be a canvas for text -- this oversimplification of `background-color` purpose is bound to create issues in a lot more places than just uBO. I am going to decline adding ugly hacks to uBO's CSS just for the sake of fixing issues with those overriding uBO's CSS.

**Comment by Boruch-Baum** [comment]
Not as an argument, but just to point out the irony in your reason - your software is all about over-riding other people's imposed code.

**Comment by gorhill** [comment]
> all about over-riding other people's imposed code

Not to the point of making web pages unusable -- rather the opposite.
