### ISSUE TITLE
In page ads shown on youtube's new material redesign

### ISSUE THREAD

**Issue by mauricecaaaaaben** [gorhill/uBlock#1851]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Ads on search page being shown on youtube's new material design (haven't seen any preroll ads though)

### One or more specific URLs where the issue occurs
https://www.youtube.com/results?search_query=test

### Screenshot in which the issue can be seen
http://i.imgur.com/EdQmCuK.png
### Steps for anyone to reproduce the issue
1. Follow [this](https://www.reddit.com/r/youtube/comments/4h0vlv/youtube_material_design_anyone_know_anything/d2mgbjn) guide to force enable youtube's new design.
2. Go to youtube.com
3. Search anything
4. See ads

### Your settings
http://i.imgur.com/7dt7tIA.png

- Browser/version: http://i.imgur.com/SkZePau.png
- uBlock Origin version: 1.7.6

##### Your filter lists
Default filter list

##### Your custom filters (if any)
Anti-Adblock Killer

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) says:

> For **filter-related issues**, report on the respective filter list support site, or at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues).

Given the above excerpt, I would like you explain as best as possible why you opened an issue here and not with the filter list maintainers or at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues). Hopefully I will be able to use your answer to try and make it even clearer of why filter issues should **not** be opened on uBO's own issue tracker.

**Comment by Hrxn** [comment]
I guess the explanation is mostly just 'TL;DR'. Sigh.

**Comment by mauricecaaaaaben** [comment]
Probably because I'm a retard I would wager

**Comment by gorhill** [comment]
youtube.com##.ytd-search-pyv-renderer-0
