### ISSUE TITLE
Possible issue with chome 52 "Offline Auto-Reload Mode"

### ISSUE THREAD

**Issue by DummySYSTEM** [gorhill/uBlock#1853]
### Describe the issue
When watching http://www.bloomberg.com/live US steam, the page will auto reload every few minutes

### One or more specific URLs where the issue occurs

http://www.bloomberg.com/live

### Steps for anyone to reproduce the issue

1. watch  Bloomberg live US steam for few mins, about 10 minutes max
2. all of the sudden the page will auto reload, randomly

to avoid this problem, disable "Offline Auto-Reload Mode", this setting is enable by default.

### Your settings

ublock using default setting
Browser/version: Chrome Version 52.0.2743.82 m (64-bit)
uBlock Origin version: 1.76
OS: Win8.1 x64

##### Your filter lists

everything except privacy, social, multipurpose

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You did not make the case it is a uBO issue rather than a filter list issue (which is the default assumption), or even a site issue (no mention that the issue does not occur without a blocker).

**Comment by DummySYSTEM** [comment]
Sorry about missing detalis, as I really don't know if it belong to uBO or chrome or filter list. I will try give more details here.
 
When uBO is enable and using with Chrome ver 52, that page will auto reload, it seems that because of uBO keep blocking some site then Chrome 52 think the page is offline and auto reload.

1. When uBO is disable the page will not auto reload.
2. When Chrome 52 "auto reload offline page" is disable, but with uBO enable, the page will not auto reload.
3. when using Chrome 49 with uBO enable, with the same setting and filter list as when using chrome 52, the page will not auto reload, so this seems not a filter list or setting issue.
4. If I enable uBO, but not blocking anything(disable all filter list), the page will not reload

So it seems that something change in chrome 52 and when uBO keeps blocking then Chrome may think the page is offline and reload.

p.s. sorry for my bad english, I hope you understand my description.
