### ISSUE TITLE
Local unblock a domain whilte STILL blocking the images

### ISSUE THREAD

**Issue by bracuphoth** [gorhill/uBlock#1854]
### the issue

As a rule I block all images on webpages.
If I block *example.com*  on the global column (the first) so no site would connect to *example.com* and unblock *example.com* in the local column (the second) while browsing *exampe.com* the browser loads the images. But I want the images to remain blocked.

I am aware that might be the planned functionality -- unblock the site, all requests are honored -- but I want a way to let *example.com* connect to itself to get stylesheets, but not the images. **How can I do that?**

Unblocking *example.com* from the global column (the first) fixes the problem, but also would let other sites get files from that domain.

### settings

- Browser/version: Firefox 45.3.0
- uBlock Origin version: 1.8.0

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
