### ISSUE TITLE
[Question] Why is FOSSHUB listed on the Badware risks?

### ISSUE THREAD

**Issue by collectorgeneral** [gorhill/uBlock#1855]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

This is likely not a bug but, as the title asks, I am curious to know why fosshub.com is marked as 'badware' risks. I have been using that site for a long time and as far as I am aware of, they do not have any toolbars/installers or other deceptive stuff. (I would understand if sourceforge was included in that list, but I do not understand the inclusion of fosshub.) 
Yes, I also understand that it is only a warning, but why is it included in the first place? Are there any softwares hosted on the site that can be classified under 'badwares'? 

(Please keep in mind that I am not defending the site in anyway, but as someone who visits that site quite often, I would like to be informed of possible problems.)

Other information:
Browser: Firefox 48
UBO version: 1.8.0 (Default settings)

**Comment by adisib** [comment]
Some downloads on it were recently compromised with a MBR-writing trojan. The commit that adds it to the badware risks says it is a temporary addition.

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/24d17af31b4c9210f3a8eefc2bc86c33f7826805

Has there be an explanation from `fosshub.com` about all this?
