### ISSUE TITLE
Block "Element hiding from Adblock Plus" for 1 Website?

### ISSUE THREAD

**Issue by 3ckH4rd** [gorhill/uBlock#1857]
Hello,

Is it possible to block specific filters for specific websites? I would like to block "Kosmetische Filter zum Verstecken von Elementen analysieren und anwenden." for only 1 website.

Thank you!

**Comment by gorhill** [comment]
Is this an proven issue or a just question?

**Comment by 3ckH4rd** [comment]
question.

**Comment by anewuser** [comment]
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
