### ISSUE TITLE
Chrome Hangs on startup - Waiting for extension uBlock Origin

### ISSUE THREAD

**Issue by issafram** [gorhill/uBlock#1858]
Huge issue.  Take a look.

**Comment by f3n3k** [comment]
Hello same problem here, this bug appear few days ago and i can't open a page without this problem "waiting for extension ublock"

i try to uninstall and reinstall Chrome, extension etc... Nothing work

Thanks

**Comment by gorhill** [comment]
Do you have any web pages opened when you launch Chrome?

**Comment by f3n3k** [comment]
yes, i have 10-12 pages opened when I launch chrome.
Why ? This pages are the problem ? Because it's work fine with them before the bug appear...
No new page before and after the problem.
but i can try to test page by page for found the adress in problem

You think is that ?

**Comment by gorhill** [comment]
Is the _"Advanced user"_ mode selected on your side?

**Comment by issafram** [comment]
Hey guys, I originally opened up this issue.

Let me tell you how I fixed it.

I tried everything and nothing worked until I did a simple process close for ALL open CHROME.EXE processes. 

My guess is that there is something blocking in the extension startup code somewhere that is locking the entire browser. That is simply a guess.

But yes, force close all the instances of CHROME.EXE.

This includes the UI and all extensions.

Then restart Chrome. It *should* work.

I hope this helps someone.

**Comment by gorhill** [comment]
What I am wondering here is if this is related to issue #1927. uBO can fall in an infinite loop if the two following conditions occur on a page:

- The hostname part in the URL ends with a dot `.`; AND
- There is at least one resource with a `data:`-based URL on the page.

**Comment by f3n3k** [comment]
@gorhill  yes i'm in advanced user with Ublock

i don't understand your 2 exemple:
url with dot at end: you mean like that: http://www.kikoo.com/index.php  or .....**/index.**
I try the issue 1927 but i haven't problem like @Halibut80

cya and thanks

**Comment by gorhill** [comment]
> url with dot at end: you mean like that

At the end of the hostname part: `http://www.kikoo.com./index.php`, notice the hostname: `www.kikoo.com.` (just using your example).

**Comment by f3n3k** [comment]
you think this url is the problem at chrome launch?
http://www.internationalsimracing.com/forum/index.php?board=67.0

thanks

**Comment by gorhill** [comment]
No.

**Comment by f3n3k** [comment]
ok thanks, so now i don't understand where is the problem,.
Anyway, thanks you for your help ;)

**Comment by codeoflife** [comment]
Same issue with Chrome 60.0.3112.113 (Official Build) (64-bit)
All tabs hang when the PC resumes from sleep. Start wprking after about 2 minutes.
Status bar mentions it is waiting for Extension ublock.


Solutions:
1. Restart chrome
2. uninstall ublock extension, go back to adblock plus. adblock Plus also suffers from this wait, but recovers in about 10 seconds.

**Comment by mrj** [comment]
Every time I quit Chrome I have been having to restart dozens of times before I finally get past the "waiting for extension" messages for uBlock Origin and Tampermonkey.

I think I've finally found a reliable workaround: Make sure you have at least one tab open that doesn't activate the extensions (nothing to block or script). Then, if when you restart you get a "waiting for extension" hang, make that simple tab and window active in the foreground before quitting. Then restart. Now the first-loaded and first-displayed tab will load properly, and the others seem to load properly after that.

**Comment by xftroxgpx** [comment]
> Look here: https://bugs.chromium.org/p/chromium/issues/detail?id=768998

They restricted that issue? I cannot see it, redirects me to log into google.

**Comment by gorhill** [comment]
Once signed in, I get:

> You do not have permission to view the requested page. 
> 
> Reason: User is not allowed to view this issue

**Comment by Misiek304** [comment]
Yes, it was restricted at my request since some of the logs provided contained personal information. However the discussion moved to this thread now. It should be available to the public. 
https://bugs.chromium.org/p/chromium/issues/detail?id=770201
