### ISSUE TITLE
popup not blocked

### ISSUE THREAD

**Issue by ghajini** [gorhill/uBlock#1859]
### URL(s) where the issue occurs

www.songspk.tv

### Describe the issue

on going to www.songspk.tv, clicking anywhere in page opens a popup of long url 104.154.237.93 showing to update flash, install flv player or install this and that software...it should be blocked by ublock

redirected link=

http://104.154.237.93/MTcxNzgwNDg5OTA3LzE3MTc4MTc4NDAxNi8wN2dvbGxqcmVh?k=57a35f36cfe2d12712179.53211513&h=cac6728180b8baf312ee7f223185a14d95fcaeac&ban=12712179&iid=1470324534073733363092284481697409&r=1294109&ci=ERUCJ8gCDsRVY90Sc10VQZmXXBVSJhlWbURCJ0wDBMwGdZFULxVSm51VQlUSYp1GV4QDPoQAN4QDIswAbwFTVh1Tm51VQlUSYp1GCNwG7tRFElwAbUFWPtEXNdFUm51VQlUSYp1GVkwAb0lVQtEXJZmXXBVSJhlWbURCDsBXMVFWPZmXXBVSJhlWbI0Abk2GVQUCDsRVY90Sc10VQZmXXBVSJhlWbURCDsRXWB1SclkZedFUJlEWatRFJMwGcxUVY9kZedFUJlEWathQDshebUBRJMwGVh1TLxVTXBlZedFUJlEWatRFJkQAIMwGdZFULxVSm51VQlUSYp1GVgwAbwFTVh1Tm51VQlUSYp1GCNwGjthQ&pm=%3DsxWDlkWmVFWLx1Vc5lZUV1G&pabt=%3D%3DQVVx0V&pc=%3D%3DQALgwDAkQCMEgCMwACBcRC&sst=57%2F82%2F0%2F0%2F8&cbiframe=0&sgl=%3D%3DwG3B3G&id=12712179&crr=e698d1722f6035bfa20b%2C%2CwL2RnLrB3cn52bz5yd3d3LvoDc0RHa8a8c4150a4e89f1330c6&optt=b0FXVtFWXxFFwBnZNkAFBkwG&iuh=EtxDKchDKwgFlB1SY9FWqlxDIgwFK0gDLcRCXsADWUGXUZ1SRpXGQYlUaxlfZwlUQVVGVUHdtFncRkxDKchDKwgFl1EUytFXuxVVJlEeZARDPEUGC0wDXBlbZIQCXkACZ02dZokTW11VQ5WEZkwFMYRZYVVVQNkV0txAbgFTbUxGPsACXAQCLcxCNswFK0wGDsRSQthQ&ttc=4j994rrc

### Screenshot(s)

uploaded
![screenshot 23](https://cloud.githubusercontent.com/assets/20338483/17407263/3c780bd8-5a84-11e6-8cad-1bcd1e48cce5.png)
![screenshot 24](https://cloud.githubusercontent.com/assets/20338483/17407262/3c76f072-5a84-11e6-8805-c513caa29522.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/20338483/17407261/3c73d8f6-5a84-11e6-9233-e20ba3b8b3a1.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/20338483/17407995/10cf4a5c-5a87-11e6-8059-8888cd11766a.png)

### Versions

- Browser/version: google chrome Version 52.0.2743.116 m (64-bit)
and mozilla firefox 48  

- uBlock Origin version: 1.8.0

### Settings

- all default settings of filter lists

custom filters-
none

### Notes
intial redirecting url is  i think adexec.net/....... something long url or starting with 104.154.237.93 to whipzmarketing.........something like that...
i have attached cookies information in ss

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
