### ISSUE TITLE
Understanding the change of ownership

### ISSUE THREAD

**Issue by marsfan** [gorhill/uBlock#186]
Hi, 
First off I am sorry that this does not fully follow your guidelines, but I do not have an account for reddit, which is the other cited place to get answers. 

I am a bit confused over the whole change of leadership thing with uBlock. So Chris is now the lead dev, but this ublock still exists. Why did this happen and which repo should I use to download the newest and most feature rich (but still resource light) version of ublock? Also, what is the advantage of using the other repo?

Also, maybe you could leave this issue up so that people have a single place to clarify all of the possible confusion.

**Comment by anewuser** [comment]
Please read this before posting here to know what kind of posts are accepted: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Close this issue to mark it as solved.

**Comment by gorhill** [comment]
Sorry, I am not into life coaching.
