### ISSUE TITLE
uBlock Origin disables Electrolysis on Firefox 48

### ISSUE THREAD

**Issue by Marqin** [gorhill/uBlock#1862]
uBlock Origin 1.8.0
Firefox 48

I have enabled [Electrolysis](https://wiki.mozilla.org/Electrolysis) feature (shipped since 48 in stable) in my Firefox, but `about:support` shows it's "disabled by plugins" when I enable uBlock Origin.

**Comment by Marqin** [comment]
[Here](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox) is guide for making Addons work with Electrolysis.

**Comment by Marqin** [comment]
[this site](http://arewee10syet.com) shows that uBlock Origin is compatibile with Electrolysis

**Comment by Marqin** [comment]
Ok, this site checks only for compability flag on Mozilla's Addons page, not check compability itself.

Btw. this bug makes uBlock Origin not usable in modern Firefox.

**Comment by SW1FT** [comment]
@Marqin Try to change these in `about:config`: 
```
browser.tabs.remote.autostart=true
extensions.e10sBloc­kedByAddons=false
extensions.e10sBloc­ksEnabling=false
```

**Comment by gorhill** [comment]
uBO does not disable e10s, Firefox 48 does. See <https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/>.
