### ISSUE TITLE
uBlock crashes on any page after few minutes

### ISSUE THREAD

**Issue by giulianoriccio** [gorhill/uBlock#1863]
### Describe the issue
uBlock crashes on any page after few minutes

is there any way I can give you more detailed info like a crash report?

### Your settings
- Browser/version: Firefox 47.0/48.0
- uBlock Origin version: 1.8.0

##### Your filter lists
http://i.imgur.com/2T6xYhs.png

**Comment by gorhill** [comment]
What does "crashes" mean exactly?

**Comment by giulianoriccio** [comment]
The button vanishes from the toolbar and it's not available anymore in the buttons list when I go to "customize the toolbar".

The ads load normally as if the addon is disabled/not installed.

I assumed that it's being unloaded by Firefox due to an error that's being raised.

**Comment by gorhill** [comment]
See what the browser console says.

**Comment by giulianoriccio** [comment]
I'm not able to reproduce this at home and I won't be able to access the work PC until the 29th.

I'll try to make more tests comparing settings and changing addons when the office will reopen.

I'm going to close this for now until I've more info.
