### ISSUE TITLE
Block all popups by default?

### ISSUE THREAD

**Issue by FuglyLookingGuy** [gorhill/uBlock#1864]
Is there any way to block ALL popups by default? I know you can select "toggle the blocking of all popups on this site" from the flyout options, but I'd like this to default to "on" for all sites, and be toggled off by me, instead of vise versa.

The popups I'm talking about are on blogs/news sites that popup after a few seconds with something "subscribe to our newsletter" or "join our mailing list" type crap.

**Comment by androidland** [comment]
add this `no-popups: * true` to my rules

**Comment by FuglyLookingGuy** [comment]
Will that still allow me to toggle some popups back on, like login popups on some sites, case-by-case?

**Comment by gorhill** [comment]
Popups refer to separate window/tab opened by site, not DOM-based popups -- there is no universal ways to filter DOM popups, cosmetic filters are needed on a case by case basis.
