### ISSUE TITLE
Audio Ads Still Auto-Play

### ISSUE THREAD

**Issue by Fluffgar** [gorhill/uBlock#1865]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Audio ads still sometimes play when I am on my tumblr dashboard. 

### One or more specific URLs where the issue occurs
[URL(s) for issue on a specific site are **mandatory**]
https://www.tumblr.com/dashboard

### Screenshot in which the issue can be seen
[Screenshot(s) for visual issues are **mandatory**]
n/a

### Steps for anyone to reproduce the issue
1. Visit https://www.tumblr.com/dashboard
2. If audio ad does not play reload page. 
3. Should audio ad still not play repeat step 2. 

### Your settings
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
Default settings. 

- Browser/version: Mozilla Firefox 47.0
- uBlock Origin version: uBlock Origin 1.8.0

##### Your filter lists
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Default

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
You forgot to include the specific filter you used to stop the audio ad.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Fluffgar** [comment]
I am using default filters. As stated. 

Is there a filter you would recommend trying?

**Comment by lewisje** [comment]
Check the logger to see what gets blocked, hidden, or allowed.

**Comment by gorhill** [comment]
CONTRIBUTING:

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets.
