### ISSUE TITLE
Microsoft Edge has been updated with Extensions as of today.

### ISSUE THREAD

**Issue by SylveonBottle** [gorhill/uBlock#1867]
As of Augist 6, Windows update codenamed "Redstone 2" has been released with [b]many[/b] fixes and features, including Microsoft Edge's ability to add extensions via the app store.

The front page of Edge (at this time):
http://i.imgur.com/NdLuIz1.png

When clicking "Get Extensions":
https://i.imgur.com/r8P6L33.png

Simple google for a main page:
https://developer.microsoft.com/en-us/microsoft-edge/extensions/

Can we get uBlock Origin for Edge?! Please please please please!!

**Comment by anewuser** [comment]
Please close this issue and subscribe to #1486.
