### ISSUE TITLE
pages keep reloading

### ISSUE THREAD

**Issue by pantau000** [gorhill/uBlock#1868]
Pages keep often reloading 2-3 times with the addon enabled. Can this be avoided?

No specific URL, default settings.

Firefox 48.0
uBlock Origin 1.8.0
Default filter lists

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
