### ISSUE TITLE
Theme options?

### ISSUE THREAD

**Issue by twophyro** [gorhill/uBlock#1869]
I would simply like to know if it's in the plans to add a theme control or options to make uBlock darker like a night mode so you don't get "blinded by the light".

If the answer is no then just say so, i'll understand that it's not top priority.

**Comment by gorhill** [comment]
The default popup panel would seem to be easy to adapt to a dark theme, but making a workable dark theme for the advanced popup panel would be too much of a time sink for me (have to take into account color-blind mode), so I prefer to decline.

**Comment by twophyro** [comment]
Would it be possible to add support for "custom" CSS modification?
Maybe under some advanced options with a warning that it's not recommended if you're color-blind.
It would take the responsibility away from you and it would be up the each user to config it themselves. 

Anyways there are more pressing issues to attend to.
