### ISSUE TITLE
data URI scheme not processed

### ISSUE THREAD

**Issue by norstbox** [gorhill/uBlock#187]
1. Open any web page which uses `data` scheme, for example [this page](http://dopiaza.org/tools/datauri/examples/index.php).
   - data URI scheme not processed by filters. For example, `|data:` filter don't block data URI.
   - Network request logger show no requests with data URI scheme.

Expected behavior: data-scheme is processed, because it is not presence in Whitelist.
## 

uBlock 0.9.6.0 and 0.9.6.1-rc.0
Firefox 37, Chromium 43.0.2357.18
Windows 8.1

**Comment by gorhill** [comment]
Data URI are not network request, so they won't show in logger. They are embedded in documents, they can't be blocked if the document is not blocked.

**Comment by norstbox** [comment]
It is a pity to hear. ABP (at least for Firefox) is processing data URI, after removing it from whitelist schemes. Is it a uBlock design limitation?
Is there any way to block Web fonts, embedded via data URI?  Like on [LJ](http://www.livejournal.com/), for example.

**Comment by gorhill** [comment]
> ABP (at least for Firefox) is processing data URI, after removing it from whitelist schemes

I am not aware of any "whitelist schemes" in ABP. Since the content is inline, what you want is to use a cosmetic filter, not a network filter. This works for your demo case:

    dopiaza.org##iframe[src^="data:text/html;"]
