### ISSUE TITLE
[NSFW] A popup in http://www.xvideos.com/

### ISSUE THREAD

**Issue by LoreJon** [gorhill/uBlock#1870]
### Describe the issue
Go to http://www.xvideos.com/
Play a video.

**You get a popup. You don't get it with ABP (same lists).**

I need to manually add `||static-hw.xvideos.com/v3/js/html5player.min.js?v=1`.

### Your settings

Default.

- Browser/version: Firefox 48.
- uBlock Origin version: 1.8.2.

##### Your filter lists

EasyList.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Yeah, invalid.

Here is the thing: tell me **exactly** which **existing** filter which was supposed to block a popup did not actually block a popup.

You have the tool to make the case that there is an issue with uBO (the logger), use it and **make the case**. Provide the **existing filter from which filter list** was **not** enforced by uBO, such that you got a popup.

Do not lecture me about "CONTRIBUTING to uBO": if you really cared, you would actually come here regularly to contribute and take care to narrow/validate/invalidate issues opened by other people after trying to reproduce them. As far as I can tell, I am still pretty much alone here with regard to attempt to deal with issues.

**Comment by LoreJon** [comment]
Not everybody knows how to use the logger.
Shouldn't they submit an issue?

[Here](https://s7.postimg.org/489fnnmt7/image.png) is a screenshot.

Thanks.

**Comment by LoreJon** [comment]
Go to http://www.xvideos.com/video16349817/beautyfull_natural_girl_stripping.
Play.

Without `||static-hw.xvideos.com/v3/js/html5player.min.js?v=1` I get [this](https://s7.postimg.org/71517ph57/image.png) in the logger.

Thanks.

**Comment by gorhill** [comment]
> Not everybody knows how to use the logger. Shouldn't they submit an issue?

To use the logger: open it. There is _no excuse_ to not do this for anybody wanting to open an issue regarding filtering. If you can't understand how the logger is useful, than quite probably you are also unable to understand that what you think is an issue is not one.

The rule is: "make the case". The logger is the first thing to open when there are filtering issues. The probability is that it will show you that uBO is just doing what the filter lists or rules are telling it to do.

Asking others to make the case for you, on top of this with dubious or worse _misleading_ information (as is the case here) is really not nice.

You said in your 1st post:

> You don't get it with ABP (same lists).

Now you show that you are using dynamic filtering (**not** present in ABP) to force-allow all 3rd-party everywhere. So you left that important information out, misleading everybody out there that uBO was failing while it was you who made it fail with a global `allow` rule.

**Comment by LoreJon** [comment]
No one was misleading you. 
If you don't want average users to submit issues - mention it (and don't forget to emphasize).
I've never encountered such a rude attitude from a developer. Take a vacation and relax.  

I never intentionally added that rule. 
FYI: Removing it the popup opens and closes. With ABP it doesn't open at all.

**Comment by gorhill** [comment]
> With ABP it doesn't open at all.

False. I got one with ABP, and it did not close. Anybody can see for themselves -- it's just a matter of clearing the cookies before loading the page.
