### ISSUE TITLE
Icons broken when browser.display.use_document_fonts=0 and gfx.downloadable_fonts.enabled=false

### ISSUE THREAD

**Issue by secureemail** [gorhill/uBlock#1872]
Setting 
`browser.display.use_document_fonts=0`
`gfx.downloadable_fonts.enabled=false`
breaks GUI.

https://s8.postimg.org/bz7lapzkl/img.png

- Browser/version: FF/48
- uBlock Origin version: 1.8.0

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/issues?q=is%3Aissue+gfx.downloadable_fonts.enabled>.

**Comment by secureemail** [comment]
You write 

> Except that each time you want to add/modify an icon, you are back to having to do dev work for this, which gnaw away at the advantages of using font-based icons.
 
I don't understand what kind of "dev work" there would be to do. It's not like icons change with each release and it's only the icons on the main GUI, AFAIK. You don't even have to invent new icons, use the font ones and convert to SVG and use that if uBlock detects: browser.display.use_document_fonts==0 && !fx.downloadable_fonts.enabled at least as a fallback for the many users who are affected by this.
