### ISSUE TITLE
Unspecified element removed

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gorhill/uBlock#1873]
Chromium stable 52.0.2743.116 (64-bit)

uBO stable 1.8.2

https://www.reddit.com/

Tested in uBO and ABP with only Fanboy Ultimate list enabled. uBO is removing a couple (useful) unspecified links that aren't affected in ABP.

Ultimate list disabled:

![ultimate-list-disabled](https://cloud.githubusercontent.com/assets/14100003/17459716/7a6ecf14-5c12-11e6-813b-2fc99d6c594b.png)

Ultimate list enabled:

![ultimate-list-enabled](https://cloud.githubusercontent.com/assets/14100003/17459717/88dce8e2-5c12-11e6-9d1d-ebf42eadd86a.png)

**Comment by gorhill** [comment]
I could reproduce. It's a regression following refactored of cosmetic filtering. Exception cosmetic filters were bypassed for some classes of filters.

**Comment by gorhill** [comment]
A new version 1.8.4 which has the fix has been pushed to Chrome store and AMO.
