### ISSUE TITLE
same :contains() rule works in Firefox but not in Chrome

### ISSUE THREAD

**Issue by tx9191** [gorhill/uBlock#1875]
when this [site](http://www.cnbeta.com/articles/527181.htm) detects any ad is blocked, it will show a  red banner on the top of the page with warning message in it. 

uBlock origin with Easylist enabled will trigger that banner.

this behavior is implemented by in-line spcript, and the below rule is expected to prevent the script from runing:
`www.cnbeta.com##script:contains(articles/3.htm)`

this rule works well in Firefox, but fail to prevent the banner from showing in chrome.
 

- Firefox version: 48.0
- Chrome version: 52.0.2743.116 m
- uBlock Origin version: 1.8.2

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#caveats>:

> Script tag filters do not work in all browsers, due to browser API limitations: ... Not supported in Chromium-based browser.

Try: `cnbeta.com##body > div[id][style^="display:block !important;position:fixed;top:0;"]`
