### ISSUE TITLE
JQuery based filters

### ISSUE THREAD

**Issue by VitaliyAT** [gorhill/uBlock#1876]
Is it possible add something like userscripts filters (as default based on jquery)? I clear understand how find and hide random generated ad block if I will use jquery, but don't want teach one more not flxible and pure syntax (I tried but found that it's pure and not powerful at all - that's why ads still with us) If you truely adblock as declared (and not payed by one ads makers agains others like adblock/plus ), it should be interesting for you.

Example:
Try orginize catch block by Regular expression (because id generated partly random) and hide his 'no-id no class nothing catched by DOM' grandgrandparent brothers, but before that could you block (overrid) inline function that check ads on page and load them.

On jquery it's possible (some depends on browser but anyway). And you need top know only jquery. What about this adblock syntax?

As I can see you are using Anti-Adblock Killer features, that mean you already have everithing inside for userscripts filters. Just open it and orginize autoupdates (subscribtion like with other filters)

**Comment by gorhill** [comment]
I can't make sense of what you want -- aside that maybe you want jQuery syntax to filter out DOM elements? Declined.

**Comment by gorhill** [comment]
Also:

> If you truely adblock as declared (and not payed by one ads makers agains others like adblock/plus ), it should be interesting for you.

Trying to manipulate others like this is insulting to their intelligence, please don't do it.
