### ISSUE TITLE
uBlock prevents from data loading

### ISSUE THREAD

**Issue by pubmikeb** [gorhill/uBlock#1878]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Once uBlock is active I can load the data on http://www.artlebedev.ru/

### One or more specific URLs where the issue occurs
http://www.artlebedev.ru/

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Open http://www.artlebedev.ru/
2. Wait until full loading
3. Scroll down till the footer
4. You'll see a blue circle with the text «Ещё», when you click on this element more data should come.
5. Click on this element, nothing happens.
6. If you disable uBlock everything is working OK.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
- Hide placeholders of blocked elements
- Disable tooltips

![07_183519](https://cloud.githubusercontent.com/assets/17231333/17463772/eca5cd42-5ccd-11e6-9c51-b3379e6e7d9c.png)

- Browser/version: 
Chrome 52 rel branch and Chrome 54 dev branch
- uBlock Origin version: 
1.8.4

##### Your filter lists
![07_183536](https://cloud.githubusercontent.com/assets/17231333/17463773/eca69df8-5ccd-11e6-8102-6727069ac9bc.png)

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
