### ISSUE TITLE
Images are still blocked after removing temporary changes with eraser button

### ISSUE THREAD

**Issue by MadClown** [gorhill/uBlock#188]
To reproduce this, do the following:
1) Visit a website such as http://alpha.wallhaven.cc
2) Click the block button for the wallpapers.wallhaven.cc hostname, then refresh. Images should be blocked now.
3) Click the erase temporary rules button and refresh. Images are still being blocked.

The only way I can figure out how to allow images again is to click the allow button for the hostname being affected. I'm not using any permanent dynamic filtering rules or personal filters.

The version of uBlock i'm using is 0.9.6.0 on Firefox 37.0.2 and Windows 7. The only other extension i'm using is uMatrix and it isn't affected by this if I use a similar block rule like the one in the example.

**Comment by gorhill** [comment]
I can't reproduce.

You will have to tell me exactly all the dynamic rules in effect for that site + global rules

**Comment by gorhill** [comment]
OK, I double-checked by testing with 0.9.6.0 specifically, and I cannot reproduce.

**Comment by MadClown** [comment]
Here's an example image of what i'm doing.

First I block on that hostname and then refresh.
![1](https://cloud.githubusercontent.com/assets/2918532/7550056/a6e154c6-f607-11e4-9498-ddbec343797d.jpg)
Objects such as images do get blocked. Here's what it looks like for me.
![2](https://cloud.githubusercontent.com/assets/2918532/7550089/e476a90c-f608-11e4-9d73-b4ffd24e6c78.JPG)

Then I click the erase temporary rules button and the block rule is gone for that hostname. After I refresh, the website still looks like it does in the picture above.
![3](https://cloud.githubusercontent.com/assets/2918532/7550073/1f19b604-f608-11e4-8427-2a0bb60ee45e.jpg)

Here is a picture of my settings. The only other settings change I have is Fanboy's Enhanced Tracking list on. I also could reproduce this on another computer with Windows 8.1 and Firefox 37.0.2.
![4](https://cloud.githubusercontent.com/assets/2918532/7550091/eb785dae-f608-11e4-88ad-a769acd561e2.JPG)

**Comment by gorhill** [comment]
Ok, I could reproduce if I removed all my rules beforehand.
