### ISSUE TITLE
Logger enhancement : filters dropdown list (feature request)

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uBlock#1880]
I think that the logger would be greatly improved if it had a dropdown list of recently applied filtering expressions (think of Wireshark ) : that list would remember a few of the recently used expressions, so that we could very quickly change the filtering without having to type at all into the search box.

As you say, the logger is the most important tool to figure out what uBlock is doing and troubleshoot issues, on the other hand it fills up very fast sometimes, also some websites are kinda sneaky, sending scripts that are only displayed for a brief moment and then disappear.

I reckon that  you can cycle between two or three expressions using CTRl-Z and CTRL-Y in the search box, but having a dropdown list like Wireshark would be a lot better IMHO- what do you think?

**Comment by gorhill** [comment]
I am planning to do this as part of #787 -- some of the presets will be most recent filter expressions.
