### ISSUE TITLE
Allow exceptions to Large Element Blocking?

### ISSUE THREAD

**Issue by qwerty017** [gorhill/uBlock#1881]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs
https://mail.google.com/mail/u/0/#inbox

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Go to https://mail.google.com/mail/u/0/#inbox with Large Element Blocking turned on for 50kb.
Whitelist https://ssl.gstatic.com/chat/ with either Dynamic or Static Filter.
Reload page.

Below URLs are not allowed through even if exact URL is whitelisted.
https://ssl.gstatic.com/chat/babble/sprites/common-517bca7f07a37c64c3263a1411e266a5.png
https://ssl.gstatic.com/chat/sounds/incoming_video_long_e5df1b5146e9cbdba78af43d60005200.mp3
https://ssl.gstatic.com/chat/sounds/incoming_video_short_5abdd7c1c7fa8bbd5d6b4733de315c59.mp3

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chrome/Version 54.0.2816.0 dev-m (64-bit)
- uBlock Origin version: 1.8.4

##### Your filter lists
Default +
https://adguard.com/en/filter-rules.html?id=2
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
By design. _"Block media elements larger than"_ applies to what is not otherwise blocked.
