### ISSUE TITLE
dx-torrent.com

### ISSUE THREAD

**Issue by AlecRobertson** [gorhill/uBlock#1882]
Clicking the background on this site or sometimes clicking the search box, loads a popup that isn't blocked.

Occurs on https://dx-torrent.com/ - the homepage.

Example of a pop-up:

![screen shot 2016-08-08 at 19 46 21](https://cloud.githubusercontent.com/assets/4457688/17491757/dd43045e-5da0-11e6-8a13-bad2647ab877.png)

- Browser/version: Google Chrome 52.0.2743.116
- uBlock Origin version: 1.8.4

Filter lists:

![screen shot 2016-08-08 at 19 49 11](https://cloud.githubusercontent.com/assets/4457688/17491842/378f2d84-5da1-11e6-8186-fdd9282bd47d.png)

![screen shot 2016-08-08 at 19 49 18](https://cloud.githubusercontent.com/assets/4457688/17491845/3a2c3bc2-5da1-11e6-83e2-cae0930f1cea.png)

**Comment by gorhill** [comment]
Force an update of _uBlock filters_.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d5e1d0cd1d037c694373010de3c7eb3d34bda543
