### ISSUE TITLE
files.minecraftforge.net

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#1883]
### Describe the issue

Cannot block ad boxes

### One or more specific URLs where the issue occurs

http://files.minecraftforge.net/

### Screenshot in which the issue can be seen

https://vgy.me/ZvAymP (Grey boxes on left/right/bottom)

### Steps for anyone to reproduce the issue

Add the following filters to "My filters":

```
! 2016-08-08, 9:46:00 PM http://files.minecraftforge.net/
files.minecraftforge.net##.contents > .ad_left

! 2016-08-08, 9:46:07 PM http://files.minecraftforge.net/
files.minecraftforge.net##.contents > .ad_right

! 2016-08-08, 9:46:16 PM http://files.minecraftforge.net/
files.minecraftforge.net##.contents > .wrapper > .middle-ad > .ad_middle
```

Then refresh the page.

### Your settings

https://vgy.me/MZP3Vu

uBlock Origin 1.8.4

##### Your filter lists

- `My Filters`
- `uBlock filters` all of them (including experimental)
- All `Ads` filters except `EasyList without element hiding rules`
- `Malware Domain List`
- `Malware domains`
- `Fanboy’s Annoyance List`
- `Fanboy’s Social Blocking List`

##### Your custom filters (if any)

Filters:

```
! 2015-07-21, 1:27:32 PM https://www.tumblr.com/dashboard
www.tumblr.com###posts > .takeover-container

! 2015-07-25, 12:47:09 AM https://www.tumblr.com/dashboard
www.tumblr.com###posts > .recommended-unit-container

! 2016-01-16, 7:12:49 AM https://www.tumblr.com/dashboard
www.tumblr.com###posts > .video-ad-container

! 2016-08-08, 9:46:00 PM http://files.minecraftforge.net/
files.minecraftforge.net##.contents > .ad_left

! 2016-08-08, 9:46:07 PM http://files.minecraftforge.net/
files.minecraftforge.net##.contents > .ad_right

! 2016-08-08, 9:46:16 PM http://files.minecraftforge.net/
files.minecraftforge.net##.contents > .wrapper > .middle-ad > .ad_middle
```

Rules:

```
no-cosmetic-filtering: www.humblebundle.com true
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
```

**Comment by gorhill** [comment]
Can't reproduce. The only way I can get the dark gray boxes is by disabling cosmetic filtering for the site.

**Comment by gorhill** [comment]
You will have to look into why this does not work on your side -- I can't reproduce, and looking at the DOM, I confirm all the cosmetic filters are inserted on the page just fine. I tested uBO without any other add-on.

**Comment by SoniEx2** [comment]
Ok. Sorry to bother, then.
