### ISSUE TITLE
Bug: Filters containing classes with double dashes are ignored

### ISSUE THREAD

**Issue by danielyli** [gorhill/uBlock#1885]
### Describe the issue

Custom filters that specify an element with a class name that contains a double dash (or double underscore) are ignored.  This issue is reproducible for any page with an element whose class name contains a double dash or double underscore.

For example, say I want to block the top navigation bar that peeks in on Medium sites when you scroll the site up.  My filter is:

`##div.metabar--affixed`

The filter is ignored.

(Use [this](https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78) Medium article as the test case.)

If I change the filter selector to specify a class without the double dash, the filter works.
### Steps for anyone to reproduce the issue
1.  Add the filter `##div.metabar--affixed`
2.  Navigate to [https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78](https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78).
3.  Observe that the filter is not applied (the top navigation bar still creeps in when scrolling up on the site).
### Your settings

All settings are default.
- Browser/version: Chrome 52.0.2743.116 (64-bit)
- uBlock Origin version: uBlock Origin v1.8.4
##### Your filter lists

Default filter lists + the test case specified above

**Comment by gwarser** [comment]
Works when specific, not visible in log.

**Comment by gorhill** [comment]
I can't find any element with the class `.metabar--affixed` on the test page. This is what dev console says:

    > document.querySelector('.metabar--affixed');
    < null

**Comment by gorhill** [comment]
Never mind, got it while scrolling up, as you said.

**Comment by gorhill** [comment]
It's not the double-dash, it's because the class `.metabar--affixed` is added/removed as one scroll up/down. uBO does not listen to class/id changes in its mutation observer.

In any case, this is not ideal as a cosmetic filter, `.postActionsBar` (or even better because specific filters are always better: `medium.com##.postActionsBar`) works better here, as it is a permanent class on the `div`.

**Comment by danielyli** [comment]
What's interesting is that on some other sites (e.g., [this](http://arstechnica.com/science/2016/05/how-ibms-new-five-qubit-universal-quantum-computer-works/)) uBlock accommodates the dynamic addition of classes:

1.  Navigate to [this article](http://arstechnica.com/science/2016/05/how-ibms-new-five-qubit-universal-quantum-computer-works/).  The header bar peeks in when scrolling up.  With dev tools, we see that `scrolled-up` is one of the classes dynamically added to the element.
1.  Create filter: `arstechnica.com##header.site-header.is_stuck.scrolled-up`
1.  Refresh.  The element no longer peeks in when scrolling up.
1.  To make a minimal example, change the filter to: `arstechnica.com##header.scrolled-up`
1.  Refresh.  The element is blocked when you scroll up.

**Comment by gorhill** [comment]
Because specific filters are used in your `arstechnica.com` example. Specific filters (ex. `arstechnica.com##header.scrolled-up`) are always injected, but generic ones (ex. `##header.scrolled-up`) are injected only after uBO's DOM surveyor finds a match. Not watching for `class`/`id` changes prevent uBO from finding out whether new generic filters must be injected when a new `class` or `id` is merely added.

**Comment by danielyli** [comment]
Ah, I see.  Great, thanks for the explanation.

**Comment by ryanbr** [comment]
I've started to notice a trend of a certain CMS's using the "__" div elements. Given the age of this bug, is going to be fixed?

Was trying to filter on tunein.com **"##.footer__socialLink___1Iby-"** Even the following didn't work;

> tunein.com##div[class*="socialLink"]
> tunein.com##div[class^="footer__socialLink"]

**Comment by gorhill** [comment]
The bug title is incorrect, it has nothing to do with double-dash, or any double-anything.

**Comment by gorhill** [comment]
`tunein.com##[class^="footer__socialSection___"]` works fine for me. I can see no `.footer__socialLink___1Iby-` element.

**Comment by gorhill** [comment]
>     tunein.com##div[class*="socialLink"]
>     tunein.com##div[class^="footer__socialLink"]

These filters don't work because there is no `div` with class with `socialLink` in it, there is an `a` element with class `footer__socialLink___1Iby-`, and there is a `div` element with a `data-testid` attribute `socialLinksContainer`.

**Comment by ryanbr** [comment]
hmm annoying, right, doesn't show what type of element it is. Is there feature request to show the type of element being used when using the Picker?

**Comment by gorhill** [comment]
There is #1736, which I interpret as wanting more controls over cosmetic filter crafting.

**Comment by gorhill** [comment]
By the way, how did you come to create the filter with a `div` with the element picker? The element picker would have found no match on the page, and in such case it won't let you create the filter.

**Comment by gwarser** [comment]
One more case I believe: https://www.reddit.com/r/uBlockOrigin/comments/emy5cd/baseballreferencecom_doesnt_load_with_ubo_enabled/

@gorhill, you should change title to something actually describing the issue.

**Comment by gorhill** [comment]
Listening to `class`/`id` changes would affect negatively performance, so such cases have will have to be worked around using either specific cosmetic filters, and [specific-generic cosmetic filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic) will have to be used in case the filter is meant to apply everywhere.
