### ISSUE TITLE
Facebook ads in feed

### ISSUE THREAD

**Issue by SLandstedt** [gorhill/uBlock#1886]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Since Aug 9 2016 facebook now shows ads in feed.

### One or more specific URLs where the issue occurs

www.facebook.com

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/703430/17546627/6ffe5332-5ee3-11e6-951e-fa710fffe148.png)

![image](https://cloud.githubusercontent.com/assets/703430/17546771/fe690586-5ee3-11e6-9395-c39edd57e211.png)

### Steps for anyone to reproduce the issue

Open facebook webpage on desktop.

### Your settings

Default settings.

- Browser/version: Chrome 52.0.2743.116
- uBlock Origin version: 1.8.4

##### Your filter lists

Default filters list

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For **filter-related issues**, report on the respective filter list support site, or at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues).
