### ISSUE TITLE
Playlist not playing while ublock runs

### ISSUE THREAD

**Issue by kkaran360** [gorhill/uBlock#1889]
### Describe the issue
When ublock is running on this site the next song in the playlist doesnt play. You have to manually skip the song so you can play the next one on the list.

### Screenshot in which the issue can be seen
![untitled](https://cloud.githubusercontent.com/assets/14898078/17596059/afe91bd2-5fbd-11e6-97cf-b06f3e1a2655.png)

### Steps for anyone to reproduce the issue
1. Open this ![link] (http://www.saavn.com/s/album/german/Techno-for-Djs-Only-!-Vol.-4-Massive-and-Ultimate-Hard-Techno-Progressive-Schranz-Traxxx-2013/LVOJBT6L7co_).
2. Click on the play icon on the album art.
3. Buffer the song near the ending. 

### Your settings
- Browser/version: Mozilla Firefox v47.0.1 
- uBlock Origin version: 1.8.4

##### Your filter lists
- Default: Easylist
- uBlock filters
- Anti AdBlock killer
- Anti AdBlock Removal List

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
