### ISSUE TITLE
Network request logger UI not complete with 0.9.6.1-rc.2?

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#189]
... or it's related to the new unified logger? 

With 0.9.6.1-rc.2:
![screenshot01286](https://cloud.githubusercontent.com/assets/11029138/7549791/30f1306c-f646-11e4-9da4-b7b4ab0c0083.png)
Cannot display any information. 
A click on the eraser does nothing. I suppose that a click on the "chevron" (leftmost) reverts A-Z to Z-A? 
No refresh icon, no domain page to filter displayed.  

With 0.9.6.0, it looks OK:
![screenshot01285](https://cloud.githubusercontent.com/assets/11029138/7549792/3860db0e-f646-11e4-9674-c6fc86b1870a.png)

Firefox 37.0.2 - WinXP Pro SP3 32-bit.

**Comment by onestepbeyond** [comment]
I just saw that the list of items to filter seems very long to load ... (which led me to believe that nothing happened , sorry) .
I just reread https://github.com/gorhill/uMatrix/wiki/Logger but it is a bit confusing. I will read it carefully.

**Comment by gorhill** [comment]
> seems very long to load

What do you mean "very long"? Within 1-2 second of network traffic occurring, it should start to fill up.

**Comment by onestepbeyond** [comment]
OK , I begin to understand...  
Here, I have to first open the request logger and then the tab to filter. Then it is instantaneous.
However, if I first open a tab (this page where I write for example) and then open the request logger, it remains empty.

**Comment by onestepbeyond** [comment]
Well, I think it works now. 
I do not understand what happened, I did not do anything special, nor restarted Firefox, but it works now, regardless the order of the tabs are open. 
I apologize for this mess.

**Comment by onestepbeyond** [comment]
I understand now what happened/happens. 
This is a issue with the Firefox start page (for example: https://www.google.fr/). 

Steps to Reproduce: 
If it's not already done, choose a start page (not about:blank) and close Firefox. 
Reopen Firefox. 
The defined start page is open on screen. 
Open the uBlock request logger. It opens in a new tab, but the list is blank and nothing happens (like in my first screenshot in this topic). 
Return to the start page tab, refresh the page, go back to request logger tab and see that the list of filterable items is displayed. 

The same thing happens regardless of the start page that I choose (goggle, github, wikipedia, etc.)

**Comment by gorhill** [comment]
> This is just a "cosmetic" issue on the request logger

There is no cosmetic issue. As said when [version 0.8.5.0]  was released, the request log will log entries **if and only if** it is opened.

**Comment by onestepbeyond** [comment]
Thanks for the info. I did not know that.
