### ISSUE TITLE
TypeError: context is null

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#1893]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
"TypeError: context is null" in the Browser Console.

chrome://ublock0/content/frameModule.js
Line: 236.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
http://www.ynet.co.il/articles/0,7340,L-4840619,00.html
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

Open http://www.ynet.co.il/articles/0,7340,L-4840619,00.html.
Open the Error Console.

### Your settings

- Browser/version: FF 48.0.1.
http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-win32-add-on-devel/1471083436/
- uBlock Origin version: 1.8.5.2.

##### Your filter lists

uBlock filters‎ / uBlock filters – Unbreak / EasyList+EasyList Hebrew.

**Comment by gorhill** [comment]
I can reproduce. The debugger says:

    context: DeadObject

Other info:

    type = 4
    location =  `https://www.facebook.com/rsrc.php/v2/yj/r/VSd5MbiWZB2.css?_nc_cb=1
    orign = `https://www.facebook.com/plugins/feedback.php?api_key=117633148253098&channel_url=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FLcj5EtQ5qmD.js%3Fversion%3D42%23cb%3Df35e919a56a2d2%26domain%3Dwww.ynet.co.il%26origin%3Dhttp%253A%252F%252Fwww.ynet.co.il%252Ffa414dbdccb924%26relation%3Dparent.parent&href=http%3A%2F%2Fwww.ynet.co.il%2Farticles%2F0%2C7340%2CL-4840619%2C00.html&locale=en_US&numposts=5&sdk=joey&version=v2.4&width=490

**Comment by Yaron10** [comment]
Hello gorhill,

Thank you. I appreciate it.

Best regards.

**Comment by Yaron10** [comment]
Great. :+1: 

Thank you very much.
