### ISSUE TITLE
uBlock not blocking correctly

### ISSUE THREAD

**Issue by opertowiec** [gorhill/uBlock#1896]
### Describe the issue
Latest uBlock beta not blocking correctly

### One or more specific URLs where the issue occurs
http://www.dobreprogramy.pl/

### Screenshot in which the issue can be seen

uBlock 1.8.4 
http://i.imgur.com/vAe1aV8.jpg

uBlock 1.8.5b5
http://i.imgur.com/boChdZN.png

### Steps for anyone to reproduce the issue

1. Open http://www.dobreprogramy.pl/ with uBlock 1.8.5b5
2. Look on empty space like on screenshot(1.8.5b5)

### Your setting

- Browser/version:  Chromium 54.0.2829.0 54 64 bit
- uBlock Origin version: 1.8.5b5

http://i.imgur.com/yrylWCq.png

##### Your filter lists
 uBlock filters
uBlock filters – Badware risks‎
 uBlock filters – Experimental‎
uBlock filters – Privacy
uBlock filters – Unbreak
Anti-Adblock Killer | Reek
 EasyList‎ 
Peter Lowe’s Ad server list
 EasyPrivacy
Malware Domain List
 Malware domains‎
 Fanboy’s Annoyance List‎ 
Fanboy’s Social Blocking List‎
 POL: polskie filtry do Adblocka i uBlocka‎

##### Your custom filters (if any)
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
https://raw.githubusercontent.com/opertowiec/filtry/master/filtry.txt

**Comment by gorhill** [comment]
Works fine here.

I can get exactly what you have in your second screenshot if I disable cosmetic filtering for the site.

**Comment by opertowiec** [comment]
Uninstall uBlock, restart browser and install again and seems working good now.

**Comment by anewuser** [comment]
@opertowiec Then close this issue. The button is next to the one you used to submit your last comment.
