### ISSUE TITLE
NSFW - wrong pornhub filter proposed by element picker

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#1897]
chrome 53, ubo 1.8.4, all ubo filters, easylist, easyprivacy
site: http://www.pornhub.com/

### Steps for anyone to reproduce the issue

go to main page http://www.pornhub.com/
see the ads on the right side (or at bottom)

right click, "block element"
the first proposed filter (edited - it's very long):
`data:image/png;base64,iVBORw0KG...SuQmCC$domain=www.pornhub.com,image`
editing the filter to ("create" still ON):
`data:image$domain=www.pornhub.com,image`

The ads are gone, refresh page ==> the ads still there

Anyway, other proposed filter is working:
`pornhub.com###switch`

**Comment by gorhill** [comment]
This was supposed to be fixed with #1725, but looks like I forgot to also apply the fix for background image styles.

**Comment by gorhill** [comment]
On top of `pornhub.com###switch`, `pornhub.com##var` also helps.
