### ISSUE TITLE
Option to record all network requests

### ISSUE THREAD

**Issue by Dormann** [gorhill/uBlock#190]
Could there be an option in the network request logger or in the panel of uBlock origin, or even a button in the UI of uBlock origin to record all network request from now on, and stop at will ?
And in this case, since it could be huge, to put it into a file.

Or at least to make it possible for the behind-the-scene requests since they can happen at any time, for any reason (add-ons, updates, ...).
Because if we want to check many tabs simultaneously, we have to change the required tab in the network request logger and it erases everything that has been recorded in the previous tab observation. Or am I missing an already existing feature ? :-S

**Comment by gorhill** [comment]
> we have to change the required tab in the network request logger and it erases everything that has been recorded in the previous tab observation

This is changed in 0.9.7.0, the logger is now [_unified_](https://github.com/gorhill/uMatrix/wiki/Logger), meaning it displays all at once, no need to toggle between tabs anymore.

**Comment by Dormann** [comment]
Ah OK, that's what you meant by unified.
