### ISSUE TITLE
Element picker has a problem with creating rules with specific unicode/HTML-code

### ISSUE THREAD

**Issue by F4z** [gorhill/uBlock#1901]
Google Chrome 52.0.2743.116 m (64-bit)
uBlock Origin 1.8.4/1.8.5b5

To reproduce:
1. Open this website - `https://tpblist.xyz/thepiratebay.php`
2. Use element picker and try block link to `tpb.host` or any similar on this website
![1](https://cloud.githubusercontent.com/assets/11742596/17671513/aac4f164-6317-11e6-82d6-e15275fc1fba.png)
3. Rule made by element picker cannot be created

I think, the problem is with this unicode/HTML-code `&#10;` in a href.

**Comment by gorhill** [comment]
The issue is with the site, it contains malformed HTML -- there is a missing double-quote for the `href` attribute of the link.

I can add a call to `trim()` extracted attribute values just for convenience given it's trivial thing to do for uBO, but I won't bother for all cases of malformed HTML.

**Comment by F4z** [comment]
I do not sure if I understand you correctly, but I think it has double-quote.
Also for test purpose you can create this element on website and try to block this with element picker - 
`<a href="http://example.com&#10;">Example</a>`
or try to create rule to block "Example" on this website - `http://qwaz.cba.pl/`

By the way, thanks for fix, with this fix it works.

**Comment by lewisje** [comment]
> The issue is with the site, it contains malformed HTML -- there is a missing double-quote for the `href` attribute of the link.

Actually, the OP has a point: The character code `&#10;` encodes the line-feed character, and as you can see more closely, the `href` attribute goes to a new line before the double-quote appears; it's just that the Web Inspector pretty-prints the HTML of the document as it exists to use a literal line-feed character and "proper" indentation.

**Comment by gorhill** [comment]
> Actually, the OP has a point: The character code &#10; encodes the line-feed character, and as you can see more closely, the href attribute goes to a new line before the double-quote appears

That's right, I somehow missed that double-quote.
