### ISSUE TITLE
How do I block y if x (prior blocking)

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBlock#1904]
How do I block 

###context-2 > .u-noPrint.Container--withColumn.Container--section.Container > .ContentLayout--bordered.ContentLayout--noExtraColumn.ContentLayout > .ContentLayout-mainColumn > .Grid-space--smallBottom.Grid-space--negativeTop.Grid--verticalGutter.Grid > .Grid-m-width--third.Grid-item:nth-of-type(3)

only if it has Teaser-adLabel--native.Teaser-adLabel as describe here:

###context-2 > .u-noPrint.Container--withColumn.Container--section.Container > .ContentLayout--bordered.ContentLayout--noExtraColumn.ContentLayout > .ContentLayout-mainColumn > .Grid-space--smallBottom.Grid-space--negativeTop.Grid--verticalGutter.Grid > .Grid-m-width--third.Grid-item:nth-of-type(3) > .js-continue_reading--native > .theme-Native.Teaser--smallImage.Teaser > .Teaser-link > .Teaser-body > .Teaser-adLabel--native.Teaser-adLabel

This example can be found in http://www.svd.se/wallstrom-ursaktar-inte-att-jag-star-upp-for-barns-rattigheter/om/turkiets-aldersgrans-for-sex and I ask how to do this so I can learn how to block ads on the site.

**Comment by gorhill** [comment]
> I ask how to do this so I can learn how to block ads on the site.

You know very well about [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) -- it's beyond me to understand that you act is if it does not exist.
