### ISSUE TITLE
Hi,  Our domain (track.atom-data.io) is being blacklisted by your extension which is causing us harm. Our domain is clean under virus total and there is no reason for it to be flagged. Please remove the flag immediately.  Many thanks,  Yigal

### ISSUE THREAD

**Issue by yigald** [gorhill/uBlock#1905]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by zummuz** [comment]
This tracker is for uBlock's issues only. There is another one for the internal filters issues, but your site is in the EasyPrivacy, which is external and uBlock has nothing to do with it.  
EasyPrivacy list is for different tracker/analytic domains, which causes harm to peoples privacy, like yours.   
Btw, flashing porno gif is not a virus and will be skipped by antivirus, but still blocked with extensions like this.
Please close the issue. Thanks

**Comment by Tmp341** [comment]
The word "track" inside that domain explains why you're blacklisted by easyprivacy. Like @zummuz said, you should check their website.
