### ISSUE TITLE
NextDoor.com Sponsored Content (Ads) Not Being Blocked

### ISSUE THREAD

**Issue by prdonahue** [gorhill/uBlock#1906]
![image](https://cloud.githubusercontent.com/assets/4582374/17754092/c6631844-6487-11e6-8c5f-483e1b7e3e33.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by prdonahue** [comment]
My apologies—didn't see that policy. Will take up with filter list providers.
