### ISSUE TITLE
Yahoo Webmail misbehaves with uBlock Origin

### ISSUE THREAD

**Issue by lvmarks** [gorhill/uBlock#1907]
Wonderful extension! Works great with almost everything! The problem is with Yahoo! Webmail. The main portion of the screen contains three frames spaced horizontally: folders, mail list or item, and ad.  The center frame is frequently not wide enough to show the mail item (e.g., large jpegs) requiring panning left-right to view.

Yahoo provides a solution for this. The divider bar between center (mail) and right (ad) frames contains a spot (HTML image map or javascript onClick). When selected, the right frame and divider bar go away and the center frame expands to fill the vacated space. Just a click on the ">" symbol does it.

I'd like to get rid of the ad--it changes continually causing slowdowns and huge memory leaks--but when I do, I can no longer expand the center frame.

A clear list of steps to reproduce the problem
1.	Install default uBlock Origin
2.	Visit Yahoo webmail. Problem occurs with both yahoo.com/mail and att.yahoo.com/mail (these both re-direct). The problem occurs on the default Inbox start page as well as mail-reading and mail-composition pages.
3.	Note that with uBlock the right-hand frame is blank (ad properly suppressed) but there’s no way to expand the center frame.
4.	Try with uBlock disabled or view the pdf, attached or at at https://www.dropbox.com/s/pm3tylcf8f70jwv/Using%20Ublock%20Origin%20with%20Yahoo%20Webmail.pdf?dl=0 
[Using Ublock Origin with Yahoo Webmail.pdf](https://github.com/gorhill/uBlock/files/423875/Using.Ublock.Origin.with.Yahoo.Webmail.pdf)
to see annotated screenshots of the blocked and unblocked behavior. The divider bar contains a “>” (HTML image map or javascript onclick) which expands the center column when clicked. This hides the right-column ad and causes the center frame to expand to cover its real estate.
5.	It’s great that the ad is suppressed but it would be even better if the center frame were expandable as it is without uBlock. In other words, I need to figure out how to not suppress the image map or js-onclick so I can click to expand, or (even better) automatically expand the center column.
Symptoms of the issue
1.	No way to expand center column since apparently an image map or javascript onclick is suppressed. See the PDF.
2.	It would be great if I could figure out how to find this element with the logger and element picker and permit it. Just looking for some guidance on how to pursue it.
Logger Report
•       See the attached PDF.
[uBlockLogger.pdf](https://github.com/gorhill/uBlock/files/423885/uBlockLogger.pdf)
uBlock preferences differing from the default
•	Nothing has been changed from default settings.
uBlock version
•	Version 1.8.4
Browser version
•	Google Chrome Version 52.0.2743.116 m (64-bit)
Operating System version
•	Windows 10 Pro-latest updates
Other Extensions
•	Ebates
•	GoToMeeting
•	Cisco WebEx
•	Google Docs
•	Google DocsOffline
•	Google Sheets
•	Google Slides
Problem occurs with all of these disabled

I'm pretty fluent in HTML, less so in CSS, DOM, or Javascript, but the Yahoo webmail page source, delivered with all whitespace removed, is nearly impenetrable for me. Could you please give me a strategy for solving this? I'm glad to do the legwork.

Sorry for the redundancy in this report. I'm trying to make sure I'm understood.

Larry

**Comment by lewisje** [comment]
I see the same issue with the current version of Yahoo Mail that I noticed in early 2012 when I posted about it on the ABP forums: https://adblockplus.org/forum/viewtopic.php?p=54808#p54808

Specifically, this time around, both `#shellcontent` and `.frost-container` are set to have `position: absolute` and `right: 180px`, leaving a space that will not be covered up just because the stuff intended to fill that space is hidden or fails to load.

The extension that I recommended for Firefox and Chrome to deal with this, Webmail Ad Blocker, is still being updated and still well recommended; you could also consider a custom UserScript or UserStyle.

**Comment by gorhill** [comment]
> The extension that I recommended for Firefox and Chrome to deal with this, Webmail Ad Blocker

Or to just add the following filter in uBO:

    mail.yahoo.com###shellcontent:style(right: 0px !important;)

**Comment by lvmarks** [comment]
James,
Thanks much for the information.
I'm hoping uBlock Origin has some capability to kill or modify these two elements, or at least to display the hot image map/js-onClick, so I can click the space free.
It may just be a case of figuring out how to allow something that's currently suppressed. Maybe I should have allowed each of the blocked elements, one-at-a-time to see if I got satisfactory results... (I'm just learning how to use uBlock.)
In the interest of less complexity, I'm reluctant to stack another extension on top of this one just for Yahoo! but I may be driven to it as a last resort.
Regards,
Laurence Marks

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lvmarks** [comment]
Thank you very much.
Laurence Marks

**Comment by lvmarks** [comment]
Sorry for the misplaced question. I read most or all of the documentation and never saw a reference to Mozilla discourse. 
Laurence Marks

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 17, 2016 at 23:15, Raymond Hill<notifications@github.com> wrote:   
Closing and marking as invalid, as per CONTRIBUTING.

**Comment by Tanhueco** [comment]
1. Go to Firefox Add-ons -> Extensions -> uBlock Origin Options -> Show Dashboard -> My filters
2. Cut/paste the following:
```
##.mb-list-ad
##.mb-list-img-ad
##.mb-native-ad
##.adlink
s.yimg.com/av/curveball/ads/
```
3. Apply changes
