### ISSUE TITLE
[Firefox] uBlock PopUp not displaying correctly!

### ISSUE THREAD

**Issue by Snow8** [gorhill/uBlock#191]
Hi,

this happens on various pages. I don't have a sure way to reproduce the issue, but it happens from time to time and is not limited to a specific page. (I am on Win7, Firefox Beta/Dev Channel and uBlock Origin 0.9.6.0)

Here is a screenshot!
![untitled](https://cloud.githubusercontent.com/assets/11486958/7553860/5e8a112a-f70d-11e4-986e-545f31af6329.png)

As you can see, the right row of the local dynamic blocking rules is "missing".

**Comment by gorhill** [comment]
It's a Firefox bug, see #108.

**Comment by Snow8** [comment]
ok!

Didn't had much time earlier to scan all closed pages and just did a quick look on the first page if the issue was there before opening this thread...

**Comment by anewuser** [comment]
You've said you're using "Firefox Beta/Dev Channel", but the Beta channel is separated from the Developer Edition.

I use the actual Firefox Beta, currently at version 38, and have never had this issue with uBlock.

**Comment by Snow8** [comment]
I have both installed. Dev Channel gives you an option to run it with a seperate profil... I have the issue in FIrefox Beta as well as Dev.
