### ISSUE TITLE
Openload Ads and Popups

### ISSUE THREAD

**Issue by xmaestro21** [gorhill/uBlock#1910]
Hello, first of all i hope this is the right place for this!
So there is an issue with ublock origin and the Openload video player.
Whenever you click on an openload video, it opens at least 2 ads as popup tabs.
Openload seems to be packed with ads, i tried everything including working through the logger but stil couldnt solve the problem. In the end there was always 1 ad / popup left, that doesnt want to be blocked. This happens on every openload video for me, but i added an example link:

https://openload.co/embed/Y8WzfvdsVrU

### Steps for anyone to reproduce the issue

Simply wanting to play an openload video will reproduce this issue.
- Open the link with the openload video.
- press play -> popup will appear, but wont start the video
- press play again -> another popup will appear (sometimes the popups close themselves immdediately, but not always, and stil annoying.
- you have to press play a couple times until it starts, sometimes the browser windows size changes by itself while doing this.
- thats it

### Settings
- default
- i am an experiences user is switched on

- Browser/version: Chrome 52.0.2743.116 m
- uBlock Origin version: 1.8.4

### Filter lists:

Default filter lists + adblock warning removal list, fanboys annoyance list, easylist germany
no costume filters

in the ublock pop ui, i have: 
3rd party scripts globally blocked
3rd party frames globally blocked
openload nooped globally
cloudflare nooped globally (otherwise openload wont work on other sites)
anything else is default.

i already tried blocking every possible thing that could be an ad or popup
i watched what happens in the logger when i try to play an openload video, and blocked everything ad related.
nothing helped, never got rid of every ad / popup
at last i deleted every single one of my own rules because everything was messed up

### Logger Screenshot

i will attach a screenshot of how the logger looks, beginning from when i load the site with the video, until the video actually starts (after all the ads and clicks)

![openload ads](https://cloud.githubusercontent.com/assets/21089903/17785655/f4eef444-6581-11e6-8929-5e359bf70c93.png)

this is the logger without any own rules to block an ad on openload

i hope you can help, thanks :)

Edit: the no pop-ups switch is not an option because i really need to open new tabs frequently on some sites, and i cant switch it on and off a thousand times

**Comment by gorhill** [comment]
CONTRIBUTING:

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets.
