### ISSUE TITLE
s3.amazonaws.com

### ISSUE THREAD

**Issue by DiabSoule** [gorhill/uBlock#1911]
The new pre-release link ---https://github.com/gorhill/uBlock/releases/download/1.8.5rc0/uBlock0.firefox.xpi
Is being blocked by its own filter list--

![screenshot from 2016-08-18 14-58-39](https://cloud.githubusercontent.com/assets/11603431/17788764/c89cff62-6554-11e6-85ba-18d29f494dab.png)

Not sure what to make of it so I am bringing it to attention

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
