### ISSUE TITLE
http://www.nextinpact.com/

### ISSUE THREAD

**Issue by Boeak** [gorhill/uBlock#1914]
Ads not blocked.

- Browser/version: Firefox 48
- uBlock Origin version: uBlock 1.8.4

Default filter lists + FRA.

**Comment by harshanvn** [comment]
This is not the right place for filter list issues.  Please see the contributing.md before posting issues..

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
