### ISSUE TITLE
uBlock conceals some pictures

### ISSUE THREAD

**Issue by akoppa** [gorhill/uBlock#1915]
uBlock disables some pictures, not all of them, just in some pages.  This problem tied me down the whole day.
Maybe the issue is caused by the pictures, but at this moment I don't have the time to investigate.
This is the code in the picture:
```
<div>
<img src="/pictures/pic-1.jpg" alt="pic-1">
<p>Some text here</p>
</div>
```
This is the code in the rendered page as shown in the Firefox Inspector Tool.
```
<div>
<img style="display: none ! important;" src="/pictures/pic-1.jpg" alt="pic-1" hidden="">
<p>Some text here</p>
</div>
```
This is one of the pics I used for testing:
![pic1](https://cloud.githubusercontent.com/assets/21126448/17813035/43103b7a-65ef-11e6-9039-8148940c1490.jpg)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
