### ISSUE TITLE
YouTube - (Recommended for you) videos 

### ISSUE THREAD

**Issue by bonta213** [gorhill/uBlock#1918]
Is there a way to block YouTube - (Recommended for you) videos?

Blocking Mode Medium 
www.youtube.com ytimg.com * noop

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
It took me a while to figure out how to [craft XPath queries](https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/contains), but [this should work](http://stackoverflow.com/questions/1982624/using-xpath-how-do-i-select-a-node-based-on-its-text-content-and-value-of-an-at):

    youtube.com##:xpath(//li[contains(@class,'related-list-item')][descendant::span[contains(@class,'stat') and text()='Recommended for you']])

It does take a while to work; when I tested it, I could notice the Recommended videos before the application of this rule hid them away.
