### ISSUE TITLE
Translate internally new AdGuard's extended selectors where uBO has corresponding support

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1920]
See:
- https://github.com/AdguardTeam/AdguardBrowserExtension/issues/321
  - `yandex.ru##.serp-item[-ext-has=".label.label_color_yellow"]` could be translated into `yandex.ru##.serp-item:has(.label.label_color_yellow)`
- https://github.com/AdguardTeam/AdguardBrowserExtension/issues/322
  - `example.com##div.red[-ext-contains="advert"]` could be translated into `example.com##:xpath(//div[contains(concat(" ",@class," ")," red ")][.//text="advert"])`
  - OR `example.com##div.red:xpath(.//text="advert")` (adding prefix support for `:xpath`)
  - OR a new cosmetic operator `example.com##div.red:has-text(advert)` (simpler for users)

**Comment by zummuz** [comment]
Hi.
I saw a thread on StackOverflow where someone said there is a little chance that selector won't work if the classes are separated with more than the single spaces, and suggested to use `normalize-space`:
http://stackoverflow.com/a/1390680

Also, in the same thread there is another suggestion for a class selection. I don't know if its better, or if it will work at all (it is for 2.0 XPath):
http://stackoverflow.com/a/12165195

**Comment by gorhill** [comment]
All that is mentioned in description has been implemented since then.
