### ISSUE TITLE
'@@||example.com^$domain=example2.com' custom exception filter doesn't seem to work properly

### ISSUE THREAD

**Issue by AmperAndSand** [gorhill/uBlock#1921]
### Describe the issue
I have this filter in 'My filters' which is supposed to allow all elements from 'w.sharethis.com' to load at gmanetwork.com: `@@||w.sharethis.com^$domain=gmanetwork.com`

However, when I view the logs through the uBO logger of this gmanetwork.com page - http://www.gmanetwork.com/news/story/578457/lifestyle/food/squirtle-freakshakes-fast-food-pokestops-cashing-in-on-pokemon-go - I notice that a script from w.sharethis.com is still being blocked (by hpHosts' ATS HOSTS file), while at the same time, a CSS file is being allowed to load w.sharethis.com (due to my custom filter).

![Screenshot of above described issue](https://cloud.githubusercontent.com/assets/1404745/17838101/35da800a-67f7-11e6-9fd1-72c9fb081b8e.png)

Text of related log text:

(Blocked - hpHOSTS ATS)
||w.sharethis.com^  —  script	—http://w.sharethis.com/share4x/js/st.7832885bbad8a3c3fe26a42ce6e8772c.js

(Allowed - My filters)
@@||w.sharethis.com^$domain=gmanetwork.com  — css —http://w.sharethis.com/button/css/buttons.ab966a004186897711de4a5ed256c924.css

It's weird that a script from w.sharethis.com is still blocked at gmanetwork.com while a CSS file is allowed, despite my custom filter stating that all elements from w.sharethis.com is to be allowed at gmanetwork.com. 

### One or more specific URLs where the issue occurs

http://www.gmanetwork.com/news/story/578457/lifestyle/food/squirtle-freakshakes-fast-food-pokestops-cashing-in-on-pokemon-go

### Steps for anyone to reproduce the issue

1. Enable hpHOSTS' ATS filter.
1. Add `@@||w.sharethis.com^$domain=gmanetwork.com` to 'My filters'
1. Load http://www.gmanetwork.com/news/story/578457/lifestyle/food/squirtle-freakshakes-fast-food-pokestops-cashing-in-on-pokemon-go through the logger and notice the issue I described above.

### Your settings

- Browser/version:  Chrome 51.0.2704.106 m (64-bit)
- uBlock Origin version: 1.8.4
- OS: Windows 7
![ublock origin settings screenshot](https://cloud.githubusercontent.com/assets/1404745/17838163/67a88ac2-67f8-11e6-8ce1-37ef0a659eae.png)

##### Your filter lists

hpHOSTS' ATS

##### Your custom filters (if any)
`@@||w.sharethis.com^$domain=gmanetwork.com`

**Comment by monolifed** [comment]
have you tried @@||w.sharethis.com^$~domain=gmanetwork.com

**Comment by gorhill** [comment]
`w.sharethis.com/share4x/js/` is loaded from `edge.sharethis.com`, not `gmanetwork.com`:

![a](https://cloud.githubusercontent.com/assets/585534/17838322/de7bc4ee-6798-11e6-9a3d-19b57237f41f.png)
