### ISSUE TITLE
[Enhanchement] Mark filter choice as persistent

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#1922]
Right now when one changes some filter it goes in a "volatile" list.
It is good because one can test the settings and save them later only if they work OK.
But to "save" the customizations one has to open the dashboard, go to the list, purge unwanted stuff and then save; and apply.
So I am suggesting a small "save" button like thing on the side of the settings panel, so one can just save the current ublock setting/customizations -for the current site only-.
Can this be done?

**Comment by gorhill** [comment]
I don't understand the reported issue.

Filters are always saved permanently.

Dynamic filtering rules are temporary by default, there is already a save button to save the rules for the current site.

**Comment by typhoon71** [comment]
I mispoke...
I am referring to the rules that go to the "My Rules" tab in the Dashboard, so I suppose they are actually the "Dynamic filtering rules" you're talkin about.
I know there's a button there to save them, but I think it's not optimal.
You can't save just some of them, and you have to actually go there (in that tab, which is not immediate)
If you have lots of sites you're working with saving selectively is not immediate.
What I was proposing was the ability to save the custom rules as permanent directly from the main panel (where you set them), but only for the current webpage.
I hope I did explain myself better.

**Comment by gorhill** [comment]
> the ability to save the custom rules as permanent directly from the main panel (where you set them)

But that is already there... <https://github.com/chrisaljoudi/uBlock/issues/731#issuecomment-73878211>.

**Comment by typhoon71** [comment]
OK, I'm offiacially an idiot. 
My brain managed to unsee those icons.
Sorry for taking your time, and thanks.
