### ISSUE TITLE
Wired.com - how to block its "anti-adblock" script

### ISSUE THREAD

**Issue by tahaa7** [gorhill/uBlock#1923]
An example page from wired.com:

https://www.wired.com/2016/08/nissans-crafty-engine-ends-century-compromise/?mbid=social_fb

So a script on the site loads a "veil" which covers the entire page (with a message to disable ad blocker), like this: 
![clipboard01](https://cloud.githubusercontent.com/assets/9203900/17838959/3c631a08-67da-11e6-8102-15954dfafa92.png)

I've done my own bit of inspection, and it seems to me that the script call that loads this "veil" is located in line number 1658 of the source code - like so: 
![clipboard02](https://cloud.githubusercontent.com/assets/9203900/17838977/f81471b6-67da-11e6-9ecf-8af97e9a8eea.png)

How does one block this script from executing?

Browser: Chrome 52, Windows 7 x64
uBlock version: 1.8.4

Settings: Default settings, default 3rd party filters minus the "uBlock filters", no custom filters

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
You block the script with a static filter; here's how to write one: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax

**Comment by Hrxn** [comment]
Why did you disable the uBlock filters?

**Comment by lewisje** [comment]
OP probably had the same mindset as the people behind the "EasyList NoMercy" fork, that whitelist rules never have a legitimate purpose for a Real Adblocker (TM).

**Comment by Grossdm** [comment]
@lewisje you were kind by giving instructions to the OP.
Perhaps you could have included a reminder re: [https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md](url).
I'm a complete n00b and when I clicked the "New issue" button there were obvious instructions to not use this as a support forum.
I could be out of line by posting this, though.

**Comment by lewisje** [comment]
gorhill himself included that reminder already.
