### ISSUE TITLE
[NSFW} Tab on the right is activated when no-popups: www.EXAMPLE.com true

### ISSUE THREAD

**Issue by LoreJon** [gorhill/uBlock#1924]
### Steps for anyone to reproduce the issue

Add no-popups: www.xvideos.com true.
Go to http://www.xvideos.com/video23143545/young_czech_girl_takes_a_pill_for_better_sex.
Have some tabs on the right and left.
Click on the player's black empty part.

### Describe the issue

Tab on the right is activated.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 48.
- uBlock Origin version: 1.8.4.

##### Your filter lists

EasyList and uBO filters.

**Comment by gorhill** [comment]
Browser-specific behavior. uBO does not select any tab, it just closes the popup tab. The Firefox decided to activate the one to the right. Chromium activate the one which opened the popup.

**Comment by LoreJon** [comment]
Thanks.
