### ISSUE TITLE
ubo ui in firefox broken on a french site

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#1925]
see all the details here:
https://forums.lanik.us/viewtopic.php?f=64&t=32274

**Comment by gorhill** [comment]
My best guess is that there is a filter in EasyList France which results in a very inefficient regular expression-based filter. This causes the static filtering engine to time out on Firefox, leaving everything in a bad state. On Chromium, uBO spins forever.

Now is to find which filter in EasyList France is translated into an inefficient regexp.

**Comment by mapx-** [comment]
it's weird even the logger does not "see" nothing or it's due to the timeout

**Comment by gorhill** [comment]
Certainly due to timeout.

In Chromium, if I hard block `tsviewer.com` with dynamic filtering pane, the inefficient filter is not triggered it appears -- though the page still load slowly for whatever reasons -- but at least no need to spinning forever.

**Comment by mapx-** [comment]
yes, adding 
||static.tsviewer.com/short_expire/js/ts3viewer_loader.js$script,domain=teambac.fr

it seems ok

**Comment by gorhill** [comment]
Could be that this script does something nonsensical such as creatig a huge, nonsensical URL, making it hard on some regexp-based filters.

**Comment by mapx-** [comment]
well, but after the famous firefox alert window (script unresponsive, stop, continue etc), after that timeout, ubo ui is broken (even if it seems to do its job), I have to restart firefox to have again entirely ok.

**Comment by gorhill** [comment]
Yes, not sure what can be done about this. Aborting the endless script is a nice Firefox feature, however it leaves that script's environment in a broken state, so Firefox should probably kill the whole extension.

**Comment by mapx-** [comment]
probably first "we" should understand why this issue, but would it possible to interrupt ubo (other adblocker) job (cycles) if after 100 attempts (for a specific filter I guess) still no result ? 

similar request here:
https://issues.adblockplus.org/ticket/4322

**Comment by mapx-** [comment]
the very baaaad filter:
`://*.php?*=*&*=*&*=*&*=*&*=*&*=&*=*=*,*,*,*,$script,third-party`

**Comment by gorhill** [comment]
Interesting. uBO's concert this internally to:

    :\/\/[^ ]*?\.php[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=&[^ ]*?=[^ ]*?=[^ ]*?,[^ ]*?,[^ ]*?,[^ ]*?,

I am guessing the URL which causes the problem is:

    https://www.tsviewer.com/ts3viewer.php?ID=1066729&text=000000&text_size=12&text_family=1&js=1&text_s_weight=bold&text_s_style=normal&text_s_variant=normal&text_s_decoration=none&text_s_color_h=ffffff&text_s_weight_h=bold&text_s_style_h=normal&text_s_variant_h=normal&text_s_decoration_h=underline&text_i_weight=normal&text_i_style=normal&text_i_variant=normal&text_i_decoration=none&text_i_color_h=ffffff&text_i_weight_h=normal&text_i_style_h=normal&text_i_variant_h=normal&text_i_decoration_h=underline&text_c_weight=normal&text_c_style=normal&text_c_variant=normal&text_c_decoration=none&text_c_color_h=ffffff&text_c_weight_h=normal&text_c_style_h=normal&text_c_variant_h=normal&text_c_decoration_h=underline&text_u_weight=bold&text_u_style=normal&text_u_variant=normal&text_u_decoration=none&text_u_color_h=ffffff&text_u_weight_h=bold&text_u_style_h=normal&text_u_variant_h=normal&text_u_decoration_h=none

Try the regex and URL in this online regex tool: <https://regex101.com/#javascript> (notice the javascript regex engine must be picked, no problem with the PCRE one). To force an execution, remove add a `e` at the end of the URL.

Result: timeout.

**Comment by gorhill** [comment]
Or just using the dev console:

    var re = new RegExp(':\/\/[^ ]*?\.php[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=[^ ]*?&[^ ]*?=&[^ ]*?=[^ ]*?=[^ ]*?,[^ ]*?,[^ ]*?,[^ ]*?,');

Then:

    re.test('https://www.tsviewer.com/ts3viewer.php?ID=1066729&text=000000&text_size=12&text_family=1&js=1&text_s_weight=bold&text_s_style=normal&text_s_variant=normal&text_s_decoration=none&text_s_color_h=ffffff&text_s_weight_h=bold&text_s_style_h=normal&text_s_variant_h=normal&text_s_decoration_h=underline&text_i_weight=normal&text_i_style=normal&text_i_variant=normal&text_i_decoration=none&text_i_color_h=ffffff&text_i_weight_h=normal&text_i_style_h=normal&text_i_variant_h=normal&text_i_decoration_h=underline&text_c_weight=normal&text_c_style=normal&text_c_variant=normal&text_c_decoration=none&text_c_color_h=ffffff&text_c_weight_h=normal&text_c_style_h=normal&text_c_variant_h=normal&text_c_decoration_h=underline&text_u_weight=bold&text_u_style=normal&text_u_variant=normal&text_u_decoration=none&text_u_color_h=ffffff&text_u_weight_h=bold&text_u_style_h=normal&text_u_variant_h=normal&text_u_decoration_h=none');

Never complete on Chromium, while on Firefox the script times out.

**Comment by hadmagic** [comment]
vide le cache dans les paramètres, chez moi ça remarche.

Juste clean the cache in the settings panel

**Comment by mapx-** [comment]
it's not about any cache, there were some generic filters (see above) now removed

**Comment by hadmagic** [comment]
ok sorry for my bad answer
