### ISSUE TITLE
Browser hangs with uBlock + uMatrix + disabled javascript

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#1927]
Win 8.1 x64, Firefox Nightly 51.0a1 x64 BuildID:20160822064441, e10s disabled
uBlock Origin 1.8.5rc0
uMatrix 0.9.9b2

Steps to reproduce:
1. Create new profile with this non-default settings:
<code>xpinstall.signatures.required;false
javascript.enabled;false
browser.tabs.remote.autostart.2;false
browser.tabs.remote.desktopbehavior;false</code>
(this issue happens with NoScript, instead <code>javascript.enabled;false</code>, also)
3. Install latest uMatrix (default settings) and uBlock (with "I am an advanced user" enabled) from github repo
4. Open following <a href="http://gelbooru.com./index.php?page=post&s=list&tags=rating%3asafe">link</a>
5. Refresh page one or several times, or navigate to next page

Actual result: browser hang with following errors in console:
```
NS_ERROR_NOT_AVAILABLE: Cannot call openModalWindow on a hidden windownsPrompter.js:351
Error: Script terminated by timeout at:
isIPAddress@chrome://ublock0/content/js/dynamic-net-filtering.js:86:10
toBroaderHostname@chrome://ublock0/content/js/dynamic-net-filtering.js:98:10
Matrix.prototype.evaluateCellZ@chrome://ublock0/content/js/dynamic-net-filtering.js:355:13
Matrix.prototype.evaluateCellZY@chrome://ublock0/content/js/dynamic-net-filtering.js:378:14
PageStore.prototype.filterRequest@chrome://ublock0/content/js/pagestore.js:558:9
filterRequests@chrome://ublock0/content/js/messaging.js:488:13
onMessage@chrome://ublock0/content/js/messaging.js:547:25
vAPI.messaging.onMessage@chrome://ublock0/content/js/vapi-background.js:1728:17
dynamic-net-filtering.js:86:10
```

<a href="https://lh3.googleusercontent.com/-J3lfDszWPPo/V7tOFQnnVzI/AAAAAAAAdQU/E60ns6rwVuE/s0/clipboard.png"><img src="https://lh3.googleusercontent.com/-feFgurvZeQY/V7tOF15BWoI/AAAAAAAAdQY/UdWT90Flypc/s0/thumb_98a0e9addeb192331a03ad936d3156e7.jpg" border=0></a>

**Comment by gorhill** [comment]
What filter lists did you have selected in uBO? Default + what else?

**Comment by Halibut80** [comment]
Default only. 
I forget about browser restart in step 2 or 3, which needed to applying the prefs, which disable e10s.

**Comment by gorhill** [comment]
I could reproduce with `javascript.enabled;false` -- though it is difficult to reproduce reliably (and Nightly has been crashing a lot lately on my side). Resemble #1925, except that in the current case the regexp is ridiculously simple, so this can't be the issue. Need to investigate more.

**Comment by gorhill** [comment]
The issue is that sometimes the hostname part of the URL in the address bar ends with a `.`, i.e. `http://gelbooru.com./index.php?`. uBO does not deal properly with this.

**Comment by gitarra** [comment]
@gorhill Are you using the official Nightlies from https://nightly.mozilla.org/ ?

I've heard reports that the unofficial Ubuntu builds have been crashing lately. Those unofficial Nightly builds are usually done with weird (wrong) build options and it's recommended not to use them as they are not useful.

**Comment by rojagit** [comment]
@gorhill - Happened today for me with Chrome. Reset to default didnt make a diff. Are any of the list sites unavailable and thats why uM hangs ?
