### ISSUE TITLE
758x140 TV Show Banners Are Blocked

### ISSUE THREAD

**Issue by TVfan** [gorhill/uBlock#1928]
### Describe the issue

I've noticed that tv show banners size 758x140 from TheTVdb website and similar are blocked on some sites like; [TVnfo.com](http://tvnfo.com)

### One or more specific URLs where the issue occurs

http://tvnfo.com

### Screenshot in which the issue can be seen

http://i.imgur.com/b7KuUEU.png (uBlock Enabled)

http://i.imgur.com/TklICEt.png (uBlock Disabled)

### Steps for anyone to reproduce the issue

Visit the url above to with enabled uBlock to see for yourself.

### Your settings

- Browsers: Chromium 52 or Firefox 48
- uBlock Origin version: 1.8.4

##### Your filter lists

All filters enabled.

##### Your custom filters (if any)

None.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
