### ISSUE TITLE
Hostname anchor matching behavior

### ISSUE THREAD

**Issue by remusao** [gorhill/uBlock#1929]
Hello,

### Describe the issue

I found cases of URLs blocked by filters I didn't expect would match. These examples make use of hostname anchors (`||`) with partial match of hostname (usually from the end of hostname).

### One or more specific URLs where the issue occurs

This filter `||images-amazon.com^*/clientsidemetricsauijavascript*.js` from _EasyPrivacy_ matches the following url:
* `https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/ClientSideMetricsAUIJavascript-e1384dc5f61a8ce3653669f3f3b4a0b0fe0e8ad3._V2_.js`

(which can be found on product page, for example: https://www.amazon.de/gp/product/b007b7zc30/ref=s9_ri_gw_g421_i2_r/256-1806331-7396801?pf_rd_m=a3jwkakr8xb7xf&pf_rd_s=desktop-1&pf_rd_r=9cwqp08pny66hj7feefk&pf_rd_t=36701&pf_rd_p=c3435e44-81b4-4c2f-9f8b-9b818660cb26&pf_rd_i=desktop)

So we have a partial match from the end of the hostname: `images-amazon.com` matches `ssl-images.amazon.com`.

*But*, the following filter `||a-static.com^$third-party` from _EasyList_ doesn't match the following URL:
* `http://x.kinja-static.com/assets/packaged-js/4.22918f22e5c1665c6cb4.en-US.js`

(from page http://lifehacker.com/lifehacker-pack-for-firefox-our-list-of-the-essential-896766794)

I would expect the second example to match at the end of the hostname too, but it doesn't.

### Steps for anyone to reproduce the issue

You can reproduce the issue with no list but a simple custom filter. Going on a youtube video such as [this one](https://www.youtube.com/watch?v=ds1SkXATOss) (totally random one). Some requests are of the form `https://r6---sn-h0j7sn7d.googlevideo.com/videoplayback...`. I was expecting the two following filter to match these URLs:

1. `||sn-h0j7sn7d.googlevideo.com/videoplayback` (we have a match)
2. `||-sn-h0j7sn7d.googlevideo.com/videoplayback` (we *don't* have a match)

With first filter all URLs of the form specified above are blocked, and with the second (only by adding a `-` at the beginning of the hostname anchor), it doesn't match.

So maybe I didn't understand perfectly how hostname anchors should behave, but I find this behavior a bit inconsistent so I prefer to ask.

### Your settings

- Firefox version _48.0_
- uBlock Origin version _1.8.4_

##### Your filter lists

I first discovered this with EasyPrivacy as well as EasyList enabled. But it's enough to have only one custom filter (shown above) to reproduce this.

Thanks a lot for your time,

**Comment by gorhill** [comment]
Good catch: there should be no match in the 1st case. Unless a `*` is used right after the `||`, the matching should succeed if and only if the part following `||` falls exactly on a hostname label boundary.

**Comment by remusao** [comment]
Thank you so much for your fix!
