### ISSUE TITLE
[Seamonkey 2.33.1 on Windows 7] Network request log - missing elements

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#193]
As of V 0.9.70 the upper part of the "dashboard" is missing (the dropdown with selection of sites/ tabs)
On the lower line (where "filter log entries" testbox is), the refresh button is gone.

It is now impossible to work with the log.

Can you please bring back those elements?

**Comment by gorhill** [comment]
These elements are pointless in a unified log.

> It is now impossible to work with the log

Tell what exactly is impossible. I obviously made sure it is usable before releasing this.

**Comment by LeafG** [comment]
This is V 0.9.70
http://i.imgur.com/Z203H2j.jpg

I have 2 sites on the tabs: Seamonkey and Mozilla.
Currently, I can't choose the site that I want to view and I can't refresh the log at my will.
I could do it before, with the former versions:

This is V 0.9.60
http://i.imgur.com/t85qZdc.jpg

I hope I am clear enough.

**Comment by gorhill** [comment]
> It is possible to click on the status indicator area to open the matrix for the associated tab (if any) [...] The opened matrix will reflect the state of a specific tab in the browser, so log entries which are not related to that tab will be dimmed.

**Comment by LeafG** [comment]
It's less comfotable and intuitive to work with the log as it now. It is why I didn't see how it before your response. As it works now, I need to go back and forth between tabs, and sometimes even different windows:

Currently, if I want to see the log of some tab/site, I need to go to that tab and refresh it, then go back to the log so I can see its details, and so on for each site.
If the status is open, and I want to work on the log for another site/tab, I also must close the status and re-open it, to see the info I want to work on.

Where as before, I could do all the work from the log page, refreshing the log for the site I needed, or switching sites/tabs, if needed.
It was faster and clearer.

This unified log looks nicer I admit, but if you would consider at least add back the manual refresh options, it will be easier to to work.

**Comment by gorhill** [comment]
I will think of something, maybe bring back the tab selector as a filtering widget for the log entries.

**Comment by LeafG** [comment]
Got the re-added tab selector in 0.9.7.5.
Thank you!
