### ISSUE TITLE
uBlock Origin 1.8.4 cannot update Easylist

### ISSUE THREAD

**Issue by runboy93** [gorhill/uBlock#1931]
I have latest uBlock Origin 1.8.4, Chrome 49 (latest possible version for Windows XP SP3) and Windows XP SP3 as OS.

Only "Easylist" enabled, when I try to update I see basic loading bar with all information, but when it ends Easylist is still outdated.

I tried Adblock Plus latest version also, Easylist update there without problems, so I pinned down problem to uBlock Origin.

**Comment by gorhill** [comment]
uBO downloads EasyList from a different place than ABP, so the server serving EasyList could have been down. This is where uBO downloads EasyList: <https://easylist.to/easylist/easylist.txt>. See if something else on your computer is interfering with this download.

**Comment by gitarra** [comment]
Windows XP does not support ECDSA certificates.

Stop using Windows XP or use Firefox as Firefox ships with its own cryptographic library and certificate store (NSS) that has modern cryptographics support.
