### ISSUE TITLE
Parser counts the filter incorrectly in filterlists

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1932]
I have created the following two test custom filterlists:

**1:**

    # Test 1
    test1234567890.zz
    
    
    ## Strict-Blocking
    #||test1234567890.zz^$important,document
    

**2:**

    # Test 1
    test1234567890.zz
    
    
    ## Test 2
    #||test1234567890.zz^$important,document
    

For example 1, the parser (or whatever) counts 2 filters used of 2.
For example 2, the parser (or whatever) counts 1 filters used of 1.

The only difference is a Comment String ...

uBlock Origin v1.8.5rc2 on Win 10 x64 1607

**Comment by gorhill** [comment]
Looks like  in case 1 the `## Strict-Blocking` line is parsed as a cosmetic filter.

**Comment by gorhill** [comment]
> document.querySelector(' Strict-Blocking');
    < null
    > document.querySelector(' Test 2');
    < VM5345:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': ' Test 2' is not a valid selector.(…)(anonymous function) @ VM5345:1

The opening `##` indicates a cosmetic filter. One is a valid cosmetic filter, the other one is invalid.

**Comment by gorhill** [comment]
Conclusion: to avoid ambiguity, do not use line starting with `##` for comments. Use `#_` or `!_` where `_` is a space.

**Comment by Alpengreis** [comment]
Ahhhhh, OKAY! Thank you very much for detailed explaining!
