### ISSUE TITLE
uBlock blocks embedded videos and music on Facebook

### ISSUE THREAD

**Issue by n-o-o-b** [gorhill/uBlock#1933]
### Describe the issue
uBlock Origin is blocking videos from YouTube and Vimeo and tracks from Bandcamp embedded in Facebook posts, after they are clicked on. I'm sure other similar services are also being blocked but these are the only ones I have encountered personally.

### One or more specific URLs where the issue occurs

https://www.facebook.com/DanceTunnel (example of page with embedded Bandcamp track)
https://www.facebook.com/LongLiveSouthbank (example of page with embedded Vimeo video. There is also an embedded YouTube video four posts below)
https://www.facebook.com/youtube/?fref=ts (example of page with embedded YouTube videos; not included in screenshots)

### Screenshot in which the issue can be seen

Post with embedded YouTube video before being clicked on, with uBlock enabled:
![boomtown before with ublock](https://cloud.githubusercontent.com/assets/19697175/17967763/1d89694a-6ac1-11e6-8f42-9d765b5de2c0.jpg)

Post with embedded YouTube video after being clicked on, with uBlock enabled:
![boomtown after with ublock](https://cloud.githubusercontent.com/assets/19697175/17967796/3b92cf26-6ac1-11e6-8202-a6c6d36503be.jpg)

Post with embedded Bandcamp song before being clicked on, with uBlock enabled:
![dance tunnel before with ublock](https://cloud.githubusercontent.com/assets/19697175/17967844/6ea3bd8a-6ac1-11e6-9f6d-8e48a1c811ee.jpg)

Post with embedded Bandcamp song after being clicked on, with uBlock enabled:
![dance tunnel after with ublock](https://cloud.githubusercontent.com/assets/19697175/17967890/be15935c-6ac1-11e6-922f-890d30b020fd.jpg)

Post with embedded Bandcamp song after being clicked on, with uBlock disabled:
![dance tunnel after without ublock](https://cloud.githubusercontent.com/assets/19697175/17967905/d1013cc8-6ac1-11e6-995c-cc4376f4b326.jpg)

Post with embedded Vimeo video before being clicked on, with uBlock enabled:
![southbank before with ublock](https://cloud.githubusercontent.com/assets/19697175/17967930/0a1a0fe4-6ac2-11e6-900e-e31057fdd1ef.jpg)

Post with embedded Vimeo video after being clicked on, with uBlock enabled:
![southbank after with ublock](https://cloud.githubusercontent.com/assets/19697175/17967963/28815b18-6ac2-11e6-8e56-618e6830f3de.jpg)

Post with embedded Vimeo video after being clicked on, with uBlock disabled:
![southbank after without ublock](https://cloud.githubusercontent.com/assets/19697175/17967996/438e5a64-6ac2-11e6-9211-9f9145c0111b.jpg)

I forgot to do an 'after with uBlock disabled' screenshot for the YouTube one but I'm sure you know what an embedded YouTube video is supposed to look like.

### Steps for anyone to reproduce the issue

1. Navigate to any of the FB pages linked above, with uBO enabled.
2. Scroll down to the post with the embedded BC song/YT video/Vimeo video.
3. Click play.

### Your settings

All default settings, except I've unticked "Show the number of blocked requests on the icon".

- Browser/version: Firefox 48.0.2
- uBlock Origin version: 1.8.4

##### Your filter lists

Default settings

##### Your custom filters (if any)
N/A

**Comment by n-o-o-b** [comment]
I apologise in advance if I have presented something incorrectly here but I have tried to follow the "Contributing" guide as closely as possible.

**Comment by androidland** [comment]
its easylist privacy filter issue, just add this filter to myfilter

> @@||staticxx.facebook.com/common/referer_frame.php$subdocument,domain=www.facebook.com

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by harshanvn** [comment]
> I apologise in advance if I have presented something incorrectly here but I have tried to follow the "Contributing" guide as closely as possible.

It is an filter list issue. You have to use uAssrts for this.
