### ISSUE TITLE
Sticker Mule Marketplace

### ISSUE THREAD

**Issue by UdoKifferbrehl** [gorhill/uBlock#1934]
Hi there,
what do you think of adding your design(s) to the Sticker Mule marketplace (https://www.stickermule.com/marketplace)? Thank you!

**Comment by monolifed** [comment]
Is this really not spam?

**Comment by UdoKifferbrehl** [comment]
It was not intended to be spam but you may think of it as you like 😏

**Comment by monolifed** [comment]
OK. Sorry.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
