### ISSUE TITLE
Filters for non-latin domains

### ISSUE THREAD

**Issue by hant0508** [gorhill/uBlock#1937]
### Describe the issue

Ublock doesn't parse filters for non-latin domains (e.g. Russian domain `.рф`).
### One or more specific URLs where the issue occurs

[кто.рф](http://кто.рф/eng/)
[твойдмитров.рф](http://твойдмитров.рф/)
[егэша.рф](http://егэша.рф)
### Steps for anyone to reproduce the issue
1. Follow [this link](http://кто.рф/eng/)
2. Try to block or hide any element
3. Reload the page and see that nothing was blocked
### Your settings
- Browser/version: Mozilla Firefox 50.0a2 on Debian GNU/Linux
- uBlock Origin version: 1.8.5rc3
- Default settings and filter lists

**Comment by gorhill** [comment]
Works fine with Chromium, not with Firefox.

**Comment by gorhill** [comment]
Related: <https://bugzilla.mozilla.org/show_bug.cgi?id=462155>.

**Comment by monolifed** [comment]
Yes punycode encoded filter works xn--j1ail.xn--p1ai
But the normal filter кто.рф does not

**Comment by Dither** [comment]
Maybe something like this will do:
```diff
diff --git "a/uritools.old.js" "b/uritools.js"
index 661d6c6..7e2ae09 100644
--- "a/uritools.old.js"	
+++ "b/uritools.js"	
@@ -66,6 +66,7 @@ var reIPv6PortFromAuthority  = /^(?:[^@]*@)?(\[[0-9a-f:]*\])(:\d*)?$/i;
 
 var reHostFromNakedAuthority = /^[0-9a-z._-]+[0-9a-z]$/i;
 var reHostFromAuthority      = /^(?:[^@]*@)?([0-9a-z._-]+)(?::\d*)?$/i;
+var reHostFromIDNAuthority   = /^(?:[^@]*@)?([^\/?#@]+)(?::\d*)?$/i;
 var reIPv6FromAuthority      = /^(?:[^@]*@)?(\[[0-9a-f:]+\])(?::\d*)?$/i;
 
 // Coarse (but fast) tests
@@ -266,7 +267,7 @@ URI.hostnameFromURI = function(uri) {
     }
     matches = reHostFromAuthority.exec(authority);
     if ( !matches ) {
-        matches = reIPv6FromAuthority.exec(authority);
+        matches = reIPv6FromAuthority.exec(authority) || reHostFromIDNAuthority.exec(authority);
         if ( !matches ) {
             return '';
         }
```
It worked for me but I don't know if it affects anything else.

**Comment by gorhill** [comment]
Actually, issue was solved here as a result of commit f1036395.

**Comment by hant05080** [comment]
What about blocking rules?
E.g. `||кингисепп-сегодня.рф/images/banner/` doesn't work on `http://www.кингисепп-сегодня.рф`.

**Comment by gorhill** [comment]
Yes, this was reported/fixed with #2950. The specific issue here was fixed with f103639 -- I could not reproduce your issue after that one fix.

**Comment by hant05080** [comment]
Ok, I guess images is inside iframes, that's why uBO can't block them. So why the element generates these filters? 
![screenshot_2017-09-02 2](https://user-images.githubusercontent.com/28459131/29997948-778a677c-9028-11e7-905b-d7d13b9725df.jpg)

**Comment by gorhill** [comment]
Can answer without a link?

**Comment by hant05080** [comment]
I've already posted a link: `http://www.кингисепп-сегодня.рф`. Ad banner on the top of the page, `#framemaster`.

**Comment by gorhill** [comment]
Your filter `||кингисепп-сегодня.рф/images/banner/` works for me, of course using 1.14.5rc1.

**Comment by hant05080** [comment]
Oh, sorry, my mistake. I've forgot to check the uBO version, it wasn't updated. All works fine.
