### ISSUE TITLE
'Parse and enforce cosmetic filters' and 'Ignore generic cosmetic filters' options need consistency

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#1939]
**Issue Report Synopsis:**

The behaviors of the _Parse and enforce cosmetic filters_ and the _Ignore generic cosmetic filters_ options need to be consistent.

**Test Environment:**

uBlock Origin version: 1.9.0
Firefox version: 48.0.2 (applies to 32-bit and 64-bit)

**Steps To Reproduce:**
1. Enable _Parse and enforce cosmetic filters_
2. Notice that cosmetic filters in _My Filters_ are enforced
3. Disable _Parse and enforce cosmetic filters_
4. Notice that cosmetic filters in _My Filters_ are still enforced.  This is likely by design, as filters in _My Filters_ are always enforced.
5. Enable _Parse and enforce cosmetic filters_
6. Enable _Ignore generic cosmetic filters_
7. Notice that **generic** cosmetic filters in _My Filters_ are now **_not**_ enforced.  This is inconsistent with _Parse and enforce cosmetic filters_, as for that option, filters in _My Filters_ are always enforced.

**Expected Behavior:**

Either _Parse and enforce cosmetic filters_ and _Ignore generic cosmetic filters_ should both apply to _My Filters_, or neither should apply.

**Recommendation:**

The simplest solution is to have _Ignore generic cosmetic filters_ **not** apply to _My Filters_ so that its behavior is congruent with _Parse and enforce cosmetic filters_.

Alternatively, _Parse and enforce cosmetic filters_ and _Ignore generic cosmetic filters_ could each have additional sub-checkboxes or menulists in order to allow the user to control whether they apply to _My Filters_.

**Comment by gorhill** [comment]
By design. Allowing one single generic cosmetic filters would completely defeat the purpose of ignoring generic cosmetic filters, which is to avoid the overhead of having to survey the DOM.
