### ISSUE TITLE
uBlock looping

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [gorhill/uBlock#194]
![ublock1](https://cloud.githubusercontent.com/assets/12411527/7587911/b77986aa-f8b9-11e4-892c-440671ec3eca.jpg)
On some websites I noticed the uBlock counter looping like crazy.
Here is a perfect example: https://medium.com/@adrianchm
Just visit the site and notice how uBlock never stops ticking up.

I also noticed this behaviour on https://www.amazon.de/ in earlier versions of uBlock, but that seems to be fixed now.

**System:**
- Win7 64bit
- Firefox 37.0.2
- uBlock 0.9.7.0

**Subscriptions:**
- uBlock filters‎
- uBlock filters – Privacy‎
- uBlock filters – Unbreak
- Adblock Warning Removal List‎
- Anti-Adblock Killer | Reek
- Peter Lowe’s Ad server list‎
- EasyPrivacy
- Malware Domain List‎
- Malware domains‎
- EU: Prebake - Filter Obtrusive Cookie Notices
- EasyList Germany+EasyList‎ (https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt)

**Comment by gorhill** [comment]
I carefully followed the steps and I could not reproduce.

I did see this behavior on some other sites, but the issue was not uBlock, it was the site which kept firing non-stop network requests, it's usually the sites which are the problem when this happens (poor coding), uBlock merely intercept and block those non-stop requests made by a site.

**Comment by gorhill** [comment]
Ok, I can see the site never stops ticking, true, but not at a fast pace like I thought you were reporting.

Yes, problem is the site, it keeps trying to ping `https://medium.com/_stat`. Site is issue, uBlock is actually doing its job of blocking the attempt at connecting to `https://medium.com/_stat`.

**Comment by gorhill** [comment]
Also, please check the log next time, you will see what gets blocked, and why.
