### ISSUE TITLE
uBlock causes "Extension Error" in TamperMonkey's user script via CSP policy on Github.com

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uBlock#1941]
1) Install Tampermonkey if you don't have it. Link - https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

2) Install Reek's AAK script. Link - https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js 

3) Go to Github.com and you will see an Extension Error notification on Chrome through the burger menu, click on it and it will open the menu with Extension Error link at the top of the menu.

4) Click on it and it will open "chrome://extensions/" which will show this Warning - https://i.gyazo.com/bacab65bb208bd265a29f640f25df0ed.png

5) Now right click on github.com page and click on Inspect and then open Console tab which lists the details of the CSP execution which lead to this error in Tampermonkey/

PS - This is happening on *.github.com and github.com only!

uBlock Version - 1.9.0

Browsers Tested - Chrome 52, Firefox 48

**Comment by gorhill** [comment]
There is no filter or rule in uBO to filter inline script or websockets, so it won't try by default to add/modify the CSP header.

**Comment by uBlock-user** [comment]
Which custom settings you wanna know ?

**Comment by gorhill** [comment]
The one causing uBO to modify the CSP header on `github.com`.

**Comment by uBlock-user** [comment]
Custom settings of Chrome ? or Tampermonkey ? or whose ?

**Comment by gorhill** [comment]
uBO settings.

**Comment by gorhill** [comment]
Look, read carefully CONTRIBUTING (emphasis in original):

> A screenshot or transcription of **any of uBlock's preferences that differ from the defaults**
> - This includes a whitelisted website, enabled/disabled filter list, anything
> - Please do include everything different from the defaults whether or not it seems relevant to your issue

**Comment by gorhill** [comment]
Also, I cannot see any rule in Reek's user script which apply to `github.com`, so even Reek's user script should not cause CSP header to be modified.

**Comment by uBlock-user** [comment]
uBO Settings - https://i.gyazo.com/d724421edd132ab27816282ed3edf14c.png

Filters - All uBO Filters + All Ads Filters + All Privacy FIlters + All Malware domains + All Social Filters + All Multipurpose Filters + EU: Prebake - Filter Obtrusive Cookie Notices‎

Custom Filters - Adguard Annoyances Filter + Adguard English Filter + Adguard Experimental Filter + Adguard Mobile Ads Filter‎ + Adguard Social Media Filter‎ + Adguard Spyware Filter‎ + Adware filters‎ + Block-EU-Cookie-Shit-List‎ + CCFB for uBO‎ + facebook annoyances blocker‎ + I don't care about cookies‎ + Privacy filters‎ + "uBlock Filters +‎" + Youtube: Pure Video Experience‎

That's all! Anything else ?

**Comment by gorhill** [comment]
Any rules?

**Comment by uBlock-user** [comment]
No rules! No My Filters! No Whitelist!

**Comment by uBlock-user** [comment]
CCFB for uBO - https://gitlab.com/MarkTheFucker/Custom-Cosmetic-Filters/raw/master/CCFB.txt

**Comment by gorhill** [comment]
Open the logger, refresh the github page causing the issue, see what the logger says. The only log entry which are related to CSP header are when `inline-script` and/or `websocket` are blocked.

**Comment by uBlock-user** [comment]
Here you go - https://i.gyazo.com/b0d4415c5d82e85b15574e949ebdde71.png

**Comment by gorhill** [comment]
> CCFB for uBO - https://gitlab.com/MarkTheFucker/Custom-Cosmetic-Filters/raw/master/CCFB.txt

Ok, there is this filter in it:

> ||$websocket

So this forces uBO to modify the CSP header in order to be sure websocket connections are blocked. uBO is doing its job properly. Now you have a user script in Tampermonkey also trying to modify the same CSP header. You will have to find which one.

**Comment by uBlock-user** [comment]
The only userscript i have is Reek's and this WebSocket Detector - https://openuserjs.org/scripts/sscarl24/Web-Sockets_Detector_Mark/source

Can that cause it ?

**Comment by gorhill** [comment]
That does not modify the CSP header, it a copy-cat of the code used in uBO-WebSocket. I will have to look at Tampermonkey, I do not know it that well, there might be something in there modifying the CSP header regardless of user script.

In any case, this is not an error, just a (scary-looking) warning. What is important is that the websocket connections will be blocked for sure by uBO, as mandated by your filter list.

**Comment by uBlock-user** [comment]
By the way, my Tampermonkey config is Advanced Mode! Anything else you wanna know ?

**Comment by uBlock-user** [comment]
I have the github.com inspect logs, do you want to see that ?

**Comment by uBlock-user** [comment]
I will attach it, it will help you I hope - 
[github.com-1472386055684.txt](https://github.com/gorhill/uBlock/files/441123/github.com-1472386055684.txt)

**Comment by gorhill** [comment]
Yes, I just found that mode, and there is this option in there:

> Add Tampermonkey to the site's content security policy (CSP) if there is one: [Yes].

I see Tampermonkey inserts a `'unsafe-eval'` in the `script-src` directive of the CSP header. This is what is causing the warning.

You will have to choose:
- live with the warning
    - keep in mind the [last installed extension trump others](https://developer.chrome.com/extensions/webRequest#conflict_resolution) when there is such conflict
    - this means uBO would lose ability to hard-block websocket connections or the ability to block inline script if you install it after Tampermonkey was already installed
- Uncheck the above option in Tampermonkey (read their doc about this)
    - in your case, because of the filter `||$websocket`, it's as if the option is turned off anyways -- as long as Tampermonkey is not installed **after** uBO.
- Ask the maintainer(s) of CCFB to remove the blanket blocking of websockets.

**Comment by gorhill** [comment]
I need to add a note regarding Tampermonkey adding `'unsafe-eval'` to the CSP header.

uBO never relaxes whatever CSP policy is already present for a web page, at most it will make it more strict.

The purpose of Tampermonkey injectiion of `'unsafe-eval'` is to _relax_ the CSP policy regarding script execution, to make it less strict. For example, `github.com` prevent javascript execution through the `window.eval`, Tampermonkey removes this restriction.

**Comment by uBlock-user** [comment]
This can work too - @@||$websocket,domain=github.com ?

**Comment by gorhill** [comment]
This will work, but only for `github.com`. Not sure about the Tampermonkey code (I would have to look again), but given the filter `||$websocket`, the warning should occur fr whatever web page for which Tampermonkey injects its `'unsafe-eval'` expression.

**Comment by uBlock-user** [comment]
I disabled that option by selecting NO in Tampermonkey, that doesn't help, it still throws the error :(

**Comment by gorhill** [comment]
> I disabled that option by selecting NO in Tampermonkey, that doesn't help, it still throws the error :(

Well it seems Tampermonkey is injecting `'unsafe-eval'` unconditionally -- which means it will always conflict with you filter `'||$websocket`.

**Comment by gorhill** [comment]
Probably best to contact Tampermonkey author about why `'unsafe-eval'` is injected even when the option above is un-checked.

**Comment by uBlock-user** [comment]
I tried every option of Security section, but that fucking Tampermonkey still doesn't stop, fucking hell! I'm just gonna use exception filter for websockets on github.com. I can't remove Tampermonkey as I need Reek's script and I can't disable that blanket websockets filter either as blog owners are going full retard and adding websockets everyday, so only an exception can save me from this headache. Thanks for your time and your help with this investigation.

**Comment by Snapy** [comment]
@uBlock-user Do you have any other userscripts in use ?

**Comment by uBlock-user** [comment]
@Snapy, No!

**Comment by gorhill** [comment]
> Do you have any other userscripts in use ?

I had only Reek's and the `'unsafe-eval'` was still injected. I didn't check but it might still be injected with no user script at all -- I will check.

**Comment by Snapy** [comment]
Didn't you said you had a websocket detector script ?

**Comment by uBlock-user** [comment]
Yeah I still do, that and Reek's script. Gorhill already checked both and said none of them is doing anything to cause this issue. Do you disagree with his conclusion ?

**Comment by Snapy** [comment]
It seems that this userscript (injected in every web page it seems) replicates the function of the uBO Websocket Companion extension (in Chrome Web Store) so you could maybe replace it but if gorhill says it isn't the problem than you could try another script manager such as Violent Monkey.

**Comment by gorhill** [comment]
> you could try another script manager such as Violent Monkey

Looks like there is no conflict with this one. Quick search through the code, I do not see any tampering with response headers.

**Comment by uBlock-user** [comment]
lol I didn't want another extension just for websockets, so I installed that script in the first place. Thanks, is ViolentMonkey as good as TamperMonkey ?

**Comment by gorhill** [comment]
By the way, if you are going to block websocket connections everywhere by default, you don't need the WebSocket wrapper script with v1.9.0+.

**Comment by uBlock-user** [comment]
Wait, so you're telling me, if I uninstalled that script websockets would still be detected and blocked ?

**Comment by gorhill** [comment]
They would not be detected, but they would be blocked everywhere because of your `||$websocket` filter.

**Comment by uBlock-user** [comment]
Thanks for the tip, done. One less script to worry about!

**Comment by uBlock-user** [comment]
I think I found the real issue, it's with the browser itself. Chrome can't handle 2 or more extensions inserting their own CSP policies simultaneously - https://bugs.chromium.org/p/chromium/issues/detail?id=391128

Bug's status remains "Won't fix", so that's a shame on their part.

**Comment by gorhill** [comment]
> I think I found the real issue, it's with the browser itself.

That's what I told you [yesterday](https://github.com/gorhill/uBlock/issues/1941#issuecomment-242971392)...

**Comment by uBlock-user** [comment]
> That's what I told you yesterday, here

I missed that second para completely, since I was busy collecting and posting shitload of filterlist names I have got, for you. Anyways, TM dev says he's fixed the issue in BETA version, so I will wait and see.

**Comment by hwti** [comment]
>Something to consider when you will make the choice of having uBO or Tampermonkey wins the ability to modify the CSP header (again: last one installed wins).

With Firefox it seems random : if I reload a page several times, sometimes the inline-script blocking works, sometimes it doesn't (disabling the option in TamperMonkey works around the issue, but I wonder how many people are affected by this and don't know).

**Comment by gorhill** [comment]
What version of uBO is this? legacy or webext?

**Comment by hwti** [comment]
It's the legacy (installed from AMO), but TamperMonkey is a webext.

Note that even between two webext, [Mozilla documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onHeadersReceived) doesn't seem to specify the order, and the behavior is different from Chrome : 
> If two add-ons listen to onHeadersReceived for the same request, then the second listener will see modifications made by the first listener, and will be able to undo any changes made by the first listener

**Comment by gorhill** [comment]
> Note that even between two webext, Mozilla documentation doesn't seem to specify the order, and the behavior is different from Chrome :

Make sense given this:

> From Firefox 52 onwards, instead of returning BlockingResponse, the listener can return a Promise which is resolved with a BlockingResponse. This enables the listener to process the request asynchronously.

Meaning there is no way to guarantee the order given that a response may be given asynchronously.

**Comment by hwti** [comment]
>the second listener will see modifications made by the first listener

So the second listener should only be called after the first promise is resolved, else both would only see the original headers, and Firefox would have to merge both headers (which would mean removing an header would only work if all extensions remove it...).
