### ISSUE TITLE
Filter France

### ISSUE THREAD

**Issue by Balbek** [gorhill/uBlock#1942]
Can you add this filter France in the list of filters of uBlock? Thank you.

Easylist + FR : https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt

+

http://www.antipubfirefox.org/antipub/antipubfirefox-adblocklist-current-expanded.txt

**Comment by IDKwhattoputhere** [comment]
EasyList and Liste FR are already available in the dashboard.
