### ISSUE TITLE
Problem on www.lapresse.ca with cosmetic filter being ignored

### ISSUE THREAD

**Issue by mikhoul** [gorhill/uBlock#1944]
### Describe the issue

This filter:```
 ! 2016-08-29 10:53:16 http://www.lapresse.ca/
www.lapresse.ca##.zonePubBillboard
``` don't work when I reload the page, it work only the first time we block it with the selector. 

### One or more specific URLs where the issue occurs

http://www.lapresse.ca/

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

http://i.imgur.com/1KOsSKE.png

### Steps for anyone to reproduce the issue

Just load the page with those  custom filters :

! 2016-08-29 10:49:11 http://www.lapresse.ca/actualites/politique/politique-quebecoise/201608/29/01-5015105-caq-le-burkini-pourrait-figurer-au-test-des-valeurs.php
www.lapresse.ca##.articleShared

! 2016-08-29 10:50:55 http://www.lapresse.ca/actualites/politique/politique-quebecoise/201608/29/01-5015105-caq-le-burkini-pourrait-figurer-au-test-des-valeurs.php
www.lapresse.ca##.colspan:nth-of-type(5)

! 2016-08-29 10:51:16 http://www.lapresse.ca/actualites/politique/politique-quebecoise/201608/29/01-5015105-caq-le-burkini-pourrait-figurer-au-test-des-valeurs.php
www.lapresse.ca##.colspan:nth-of-type(6)

! 2016-08-29 10:53:16 http://www.lapresse.ca/
www.lapresse.ca##.zonePubBillboard

! 2016-08-27 12:28:09 http://plus.lapresse.ca/screens/f3901a43-4524-4b2c-a753-6b942190b928%7c_0.html
plus.lapresse.ca##.socialShare

! 2016-08-25 18:34:18 http://www.lapresse.ca/actualites/montreal/201608/25/01-5013992-energie-est-coderre-demande-le-report-des-audiences-de-loffice-national-de-lenergie.php
www.lapresse.ca##.actionBox



### Your settings

- Firefox 48
-  uBlock Origin v1.9.5b0

##### Your filter lists

 Fanboy's Cookiemonster List‎
uBlock filters‎ 
Badware risks
Privacy
Unbreak

 Adblock Warning Removal List‎
Anti-Adblock Killer | Reek‎ 
EasyList‎ 
 Peter Lowe’s Ad server list‎ 

 EasyPrivacy‎ 
Fanboy’s Enhanced Tracking List‎

 Malware Domain List‎ 
Malware domains‎

**Comment by gorhill** [comment]
Can't reproduce, works all fine here.

What else not mentioned in your issue did you do to make the case there is an issue with uBO?

**Comment by mikhoul** [comment]
Try again @gorhill  please,

I've just tried again in a new profile and same thing happen: 

![](http://i.imgur.com/6z7iRTc.png)


Here's the filter and you clearly see that the filter is in the list:
![](http://i.imgur.com/XrGMu8e.png)

I have attached my complete filter list/config to save you time, let me know if you need more information
[mes-donnees-ublock_2016-08-30_17_16_35.txt](https://github.com/gorhill/uBlock/files/445962/mes-donnees-ublock_2016-08-30_17_16_35.txt).

Regards ! :yum:

**Comment by gorhill** [comment]
> I have attached my complete filter list/config to save you time

Thanks.

You turned off cosmetic filtering for `www.lapresse.ca`:

>     "hostnameSwitchesString": "no-cosmetic-filtering: www.lapresse.ca true",

**Comment by mikhoul** [comment]
Ouf !!! Sorry for the disturbance but happy you find it quickly :smile: 

I'm new to Ublock (was with ABP) and transition slowly with the new interface so I'm not familiar with all the advanced features.

I've made the  transition especially to use the advanced feature such the **`HAS()`** "function"  but it's completely a new GUI for me, in few weeks I should be fine :frog: 

Thanks Again for the help !
