### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by inspector71** [gorhill/uBlock#1945]
This is not an issue but sadly there appears to be no way to say thank you within GitHub's toolset.

Thanks for the latest update, creating this addon and all the hard work!

**Comment by lewisje** [comment]
Issues like this with no actual problem should be closed right away, to keep the list of open issues clean.

**Comment by anewuser** [comment]
You can use this to say thanks or ask for help: [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

Please use the button below the comment form to close this issue.

**Comment by inspector71** [comment]
Never did think I'd get angst for saying thanks. What a horrible place the interweb can be.

**Comment by gorhill** [comment]
Closing an issue is not a sign of "angst".

**Comment by Hrxn** [comment]
Think of it like that: Having a really clean issue tracker is more satisfying than random 'thanks' on the internet from random guys.

That would be my assumption :smiley:

**Comment by j4ckhaal** [comment]
+1

I kid, I kid.
