### ISSUE TITLE
$elemhide / $generichide don't work on hindi.business-standard.com

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#1948]
- go to hindi.business-standard.com
- adding
`@@||hindi.business-standard.com^elemhide`

or

`@@||hindi.business-standard.com^generichide`

the hiding filters should be whitelisted, right ?

Nothing happens.

To be able to whitelist what I want I have to add:
```
business-standard.com#@##ad468
business-standard.com#@##wideAdd
business-standard.com#@##rightadpat
business-standard.com#@##adSense
business-standard.com#@##adsense
business-standard.com#@##outsideAds
business-standard.com#@##ad_160x160
business-standard.com#@##adrect
business-standard.com#@##adsIfrme4
```
(I know, adSense is not necessary in ubo, only in ABP)

to remove the anti adblocking trick I add also
```
@@||business-standard.com/*ad$script
@@||hindi.business-standard.com/images/$image
```

(doesnt work in ubo firefox / chrome, ABP firefox / chrome, so perhaps "they" found some other workaround ?!)

**Comment by gorhill** [comment]
Did you really use `@@||hindi.business-standard.com^generichide` or is it a typo when writing down the filter here?

**Comment by mapx-** [comment]
oh ... f..g typo :D 
I wasted time for nothing :D
