### ISSUE TITLE
Tumblr

### ISSUE THREAD

**Issue by Redshift91** [gorhill/uBlock#195]
Hi!
When the blocker is on I cant search on the tumblr page because when I scroll down suddenly the page turns white.

**Comment by hotdogman** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include

**Comment by lewisje** [comment]
For a slightly related issue (poor performance in the theme editor, because of all those frames), I went ahead and whitelisted `www.tumblr.com` (but not `tumblr.com` because that would allow ads on all Tumblr sites).

**Comment by gorhill** [comment]
Will close at the end of the day of no details are provided: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.
