### ISSUE TITLE
Feature request: log domain name only in "my filters"

### ISSUE THREAD

**Issue by bryce-lynch** [gorhill/uBlock#1951]
When the "element picker" is used, a new filter is created in "my filters" starting with a line like this:
! 8/28/2016, 3:10:16 PM http://www.pcworld.com/article/3113457/components-processors/intels-kaby-lake-chip-is-a-must-have-for-4k-video-fiends.html

Logging the domain name only without the path (e.g. http://www.pcworld.com in the example above) would be better for privacy, when other users are sharing the same machine and browser, etc.

**Comment by anewuser** [comment]
Use this page only to report bugs (problems that you make uBlock Origin stop working and you can reproduce). Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).
