### ISSUE TITLE
uBlock0.firefox.xpi does not work in some conditions

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#1953]
uBlock0.firefox.xpi works fine in direct download/install (left click). No problem with this. 
It seems that only _downloaded and stored on the hard drive_ files are not working. 
I've tested other extensions .xpi files: all functional. 

### Screenshot in which the issue can be seen

Testing with a drag'n drop (see _steps_) the last beta (1.9.5b3.xpi) stored on the HDD:

![screenshot01685](https://cloud.githubusercontent.com/assets/11029138/18169620/4e080be0-705b-11e6-89ca-f9656276c73e.png)

Testing with a right-click and selecting "Open with Firefox" gives the same result.

The .xpi files stored on the HDD opens (by my choice) with an unzipper (IZArc). - When open directly (by double-click), gives:

![screenshot01687](https://cloud.githubusercontent.com/assets/11029138/18169997/e097dffc-705c-11e6-96dd-1c821764adbb.png)

All issues described above did not exist before 1.7.7(?) (sorry for not being more specific):

![screenshot01686](https://cloud.githubusercontent.com/assets/11029138/18170156/8c6206c8-705d-11e6-8454-fcbffe98db53.png)
(uBO 1.9.5b3.xpi not listed but also concerned).

### Steps for anyone to reproduce the issue

- On the Github uBO download page, right-click on uBlock0.firefox.xpi and select "Save target as ..." (translated from french, perhaps not accurate, "Save target on the HDD" seems better). 
- Open the folder containing the downloaded .xpi, drag the .xpi in the open FF window, this should install uBO. 

Or:
- Right-click on the .xpi and select "Open with Firefox". This should install uBO. 

Or:
- In case the .xpi file has a Firefox icon, just double-click on it should install uBO. 

In all three cases, it no longer works with the latest downloaded uBO .xpi files. 

### Your settings

Firefox 38.8.0 
Win XP Professional SP3
All uBO versions since 1.7.7(?)

Thanks for reading.

**Comment by gorhill** [comment]
Not a uBO issue: if I click _"Save Link As..."_ with FF38, a bad file is created. Clicking directly on the .xpi file works fine.

**Comment by onestepbeyond** [comment]
I did not understand why FF38 is able to open the old (0.9.9) versions, and why the behaviour is the same with the unzipper.
Will investigate more further. 
Thanks.

**Comment by onestepbeyond** [comment]
> Looks like "Save Link As..." on older FF versions does not take into account redirection.

OK, downloaded with Vivaldi browser and all is fine. :+1:
