### ISSUE TITLE
Automatically lookup site-specific scriptlets.

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1954]
Currently, for many sites a scriptlet from `resources.txt` is injected. For each such scriptlet, there need to be a `##script:inject(...)` filter to make use of the scriptlet. For scriptlets which are meant for specific sites, uBO should look them up automatically without the need for a filter.

For example, I just created a scriptlet in `https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt` for the site `lesechos.fr` -- to counter the site's anti-blocker. To make use if the scriptlet for that site, I had to create the filter `lesechos.fr##script:inject(lesechos.fr.js)`. When landing on `lesechos.fr`, uBO should just automatically lookup for a scriptlet named `lesechos.fr.js`.

This is a common occurrence, so this will save me from having to create a filter for every instance of site-specific scriplet.

**Comment by lewisje** [comment]
What if the user wishes to disable injection of that scriptlet, with a rule like `lesechos.fr#@#script:inject(lesechos.fr.js)`?

**Comment by gorhill** [comment]
I will implement support for exceptions at the same time -- this has been reported as an issue in the past: <https://github.com/uBlockOrigin/uAssets/issues/23>.

**Comment by gorhill** [comment]
Fixed with a7fe367eecf2af16d07e8ec69743638cd2b05adf.
