### ISSUE TITLE
Empty ad boxes via adchoices showing up on msn.com since 1.9.5b2

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#1955]
Since installing 1.9.5b2 and subsequently 1.9.5b3 Empty ad boxes via adchoices are showing up at msn.com.

![capture](https://cloud.githubusercontent.com/assets/410799/18178247/94f0aebe-704b-11e6-8d80-703435c279d4.PNG)

Similar blank boxes appear further down on the page.

Filters:  All uBlock filters, EasyList, EasyPrivacy, Fanboy's Annoyance List,  Fanboy’s Enhanced Tracking List,  Malware Domain List‎, Malware domains‎, Spam404.

I tested with only EasyList and still had the problem.  This was to rule out the other filters.

Normally I would approach this as a filter problem and contact the owner of the lists.  However, msn.com displayed fine until the moment I installed 1.9.5b2.  No filters were updated at this time.

Using Firefox 51.0a1 64 bit version.(Nightly)

**Comment by streetwolf** [comment]
I forgot I had some more filters.  The culprit list is Adguards English Filter list.  Without it No more empty boxes.  As previously mentioned when I went to b2 AG English Filter list was not updated.  Perhaps your conversion of AG rules to uBo has gone awry.

**Comment by gorhill** [comment]
I did not touch that code.

**Comment by gorhill** [comment]
See if you have the issue with only uBO's default filter lists. If not, report to Adguard people.  If so, make the case there is an issue with uBO itself and not a filter issue. I will close and let you make the case.

**Comment by gorhill** [comment]
The problem is that there are invalid cosmetic filters in Adguard's lists.

The issue is not specific to 1.9.5b?, it's present in whatever uBO version. ABP would also have problem with Adguard's bad filters.

uBO is supposed to catch bad cosmetic filters at compile time, and fail to do so in this instance, because `div.matches('.todaystripe::after,#foo');` does not throw.

`div.matches('.todaystripe::after:not(#foo),#foo')` does throw however, so I need to change the code to use this.

**Comment by gorhill** [comment]
The invalid Adguard filters:

    msn.com##.todaymodule::after
    msn.com##.todaystripe::after

**Comment by gorhill** [comment]
The filter list with the bad cosmetic filters will have to have its cache purged to force a re-compilation if the filters -- so that the bad filters can be discarded by uBO 1.9.5b4+ at compile time.

**Comment by streetwolf** [comment]
b4 and purging the cache fixes the problem.  Thanks a lot.
