### ISSUE TITLE
Feature request: Inline commenting support for filters rules

### ISSUE THREAD

**Issue by GnstheGrain** [gorhill/uBlock#1956]
### Feature Request (inline filter commenting)
Currently, we can comment rules using the "!" sign, but this is Per-line only.
Being able to use in-line commenting would help much more convenient.  ie:    <rule here> 		!some comment

- Browser/version:  Chrome 53.0.2785.89 m (64 bit)
- uBlock Origin version: 1.9.4

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).
