### ISSUE TITLE
Feature Request: New Filter added from the Element picker editor (inner-editor) should appear on top instead of bottom

### ISSUE THREAD

**Issue by GnstheGrain** [gorhill/uBlock#1957]
### Feature Request: Change default Location of newly created Filter within "My Filters"

**[Current behavior]**
When we create a new filter using the Element Picker, it adds that new filter rule on the bottom-most of all present filters from within "My Filters" section.

**[Issue]**
This is cumbersome as we need to scroll down each and every time, in order to reach our newly and latest filters.. 

**[Desired behavior]**
Adding newly created filter to top-most of that list would solve that annoyance. 

```
- Browser/version:  Chrome 53.0.2785.89 m (64 bit)
- uBlock Origin version: 1.9.4
```

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).
