### ISSUE TITLE
In firefox, ||domain^$third-party,other - blocks image saving from the domain, if behind-the-scenes is removed from whitelist 

### ISSUE THREAD

**Issue by zummuz** [gorhill/uBlock#1958]
### Describe the issue

Pretty much the title (In firefox, ||imgur.com^$third-party,other - blocks image saving from the site itself, if behind-the-scenes is removed from whitelist). 
Maybe its relevant to https://github.com/uBlockOrigin/uAssets/issues/123#issuecomment-243602934

### One or more specific URLs where the issue occurs

https://i.imgur.com/chOq3Ib.jpg

### Screenshot in which the issue can be seen

![screenshot from 2016-09-04 21-57-08](https://cloud.githubusercontent.com/assets/13698274/18233275/2e78a64e-72eb-11e6-930a-65bb6adb978b.png)

### Steps for anyone to reproduce the issue

Go to the site
Save Image As ...
Get: Failed - imgur.com - ...    in the Downloads

### Your settings

'advanced user' is checked
`behind-the-scene` is deleted from whitelist
`behind-the-scene * 3p noop` is still in the dynamic rules

- Browser/version: firefox 48
- uBlock Origin version: 1.9.4/1.9.5b4

##### Your filter lists

default

##### Your custom filters (if any)

||imgur.com^$other
||imgur.com^$third-party

I heard you could get troubles if unwhitelist behind-the-scenes, but that issue is not present in Chromium

**Comment by gorhill** [comment]
This has been filed before, there is nothing I can do. uBO does not know the context in which the network request is made, it does not know about the _"Save Image..."_ from the browser's contextual menu.
