### ISSUE TITLE
Add blocklists for EU cookie notices

### ISSUE THREAD

**Issue by anonsubmitter** [gorhill/uBlock#196]
Could you add the [Prebake](http://prebake.eu/) and [Block-EU-Cookie-Shit-List](https://github.com/r4vi/block-the-eu-cookie-shit-list) filters to uBlock / uBlock Origin?

**Comment by gwarser** [comment]
Check under "Regions, languages" section.

**Comment by gorhill** [comment]
Prebake is already in there.

The other list is dup of #103.
