### ISSUE TITLE
Bulgarian Adblock list now supports https

### ISSUE THREAD

**Issue by SPU** [gorhill/uBlock#1961]
BGR:Bulgarian Adblock list in the Regional list now supports https. 
https://stanev.org/abp/adblock_bg.txt

**Comment by lewisje** [comment]
This is a job for https://github.com/uBlockOrigin/uAssets/

**Comment by gorhill** [comment]
No, it fits here, the list of filter lists are part of uBO itself: <https://github.com/gorhill/uBlock/tree/master/assets/ublock>.
