### ISSUE TITLE
malwaredomains.com list not updating

### ISSUE THREAD

**Issue by JeremyWW** [gorhill/uBlock#1962]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

malwaredomains.com list not updating

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

Attached

![2016-09-06_122229](https://cloud.githubusercontent.com/assets/544340/18271962/fd6a2f44-742c-11e6-8020-c1106935a29c.png)

### Steps for anyone to reproduce the issue

Tried re-installing ublock, clearing the cache etc. Visiting the website for this list the update URL's posted there do not seem to match the one ublock tries to use when updating.

### Your settings

Advanced user, no use of context menu.

uBlock 1.9.4

##### Your filter lists

My Filters, EasyList, Malware Domain List, Malware Domains

**Comment by gorhill** [comment]
> Visiting the website for this list

URL?

**Comment by JeremyWW** [comment]
I just mean that I went to http://www.malwaredomains.com/ and looked at the URL's listed under 'Latest Updates' there but I notice that even some of those don't seem to work. Maybe this is an error on their side?

**Comment by JeremyWW** [comment]
Screenshot shows the URL used by ublock to try to update this list. Looking at the URL's for 'just domains' in the lists posted on the site I can't find any trace of the same URL.
![2016-09-06_130909](https://cloud.githubusercontent.com/assets/544340/18273066/61f0c116-7433-11e6-88e2-a09a39ace7a5.png)

**Comment by gorhill** [comment]
<https://mirror.cedia.org.ec/malwaredomains/justdomains> works fine from here.

**Comment by JeremyWW** [comment]
Ah...cracked it. 'Enable protection for malicious sites and programs' in Settings was blocking it! Unchecked that option and the list has updated. Thanks, I just needed to click on the link in your post to see exactly what was happening.

**Comment by gorhill** [comment]
Are you saying your browser flagged `https://mirror.cedia.org.ec/malwaredomains/justdomains` as being "malicious"?

**Comment by JeremyWW** [comment]
Yep. Here's the screenshot:

![2016-09-06_132555](https://cloud.githubusercontent.com/assets/544340/18273525/9105003c-7435-11e6-9634-c5190cc4311c.png)

**Comment by gorhill** [comment]
Can you be more forthcoming about what browser you are using, and/or which add-on (or external program) in this browser is emitting this warning? I don't get this with my Chrome/Firefox.

**Comment by JeremyWW** [comment]
This is the Yandex browser, Chromium based, and compatible with uBlock. Further screenshot offering an explanation as to why it's being blocked:

![2016-09-06_133007](https://cloud.githubusercontent.com/assets/544340/18273637/304c2e36-7436-11e6-957b-c77166c344ae.png)

**Comment by JeremyWW** [comment]
Yandex, yes, but it seems to be Sophos that doesn't like it.

**Comment by gorhill** [comment]
Likely a false positive, based on the content of the files, which is a list of malware domains.

**Comment by JeremyWW** [comment]
Indeed. I have nagging feeling that has happened before with this list.
