### ISSUE TITLE
3rd party filters not updating

### ISSUE THREAD

**Issue by svefn** [gorhill/uBlock#1963]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When I purge all caches, filters show they are out of date and new version available. After I click Update now, and it finishes updating, I click purge all caches and it shows out of date again.

### Screenshot in which the issue can be seen
http://i.imgur.com/VeBxlLW.jpg

### Your settings
- Browser/version: Firefox 32bit / 64bit 48.0.2 on a new fresh created profile (default settings with no addons/plugins)
- uBlock Origin version: 1.9.4
- windows 10 build 14393.105
##### Your filter lists
I am using the default filter list after freshly downloaded uBlock origin extension from Firefox Addons site.

##### Your custom filters (if any)
None, using default fresh installed.

**Comment by alexara** [comment]
Not a bug:

https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters

> Purge all caches

> This will remove all locally cached copies of filter lists. Essentially, this will cause all filter lists to become out of date. This can be used to force an update of all filter lists.

**Comment by gorhill** [comment]
Why did click _"Purge all caches"_?

**Comment by svefn** [comment]
i see, my bad lol. didnt know that was how it works.

> Purge all caches

> This will remove all locally cached copies of filter lists. Essentially, this will cause all filter lists to become out of date. This can be used to force an update of all filter lists.

**Comment by gorhill** [comment]
_"Cache"_ may seems technical but it's really the most accurate word to describe what is going on:

> In computing, a cache, is a hardware or software component that stores data so future requests for that data can be served faster; the data stored in a cache might be the result of an earlier computation, or **the duplicate of data stored elsewhere**. [[Wikipedia](https://en.wikipedia.org/wiki/Cache_(computing))].

**Comment by nbark** [comment]
Thanks for posting. I had the same question so this was helpful.
