### ISSUE TITLE
Edit: resolved, please delete

### ISSUE THREAD

**Issue by montiblanc** [gorhill/uBlock#1964]
### One or more specific URLs where the issue occurs

any mature content warning enabled streams on twitch.tv "front page" & streamhtml5.com.

### Steps for anyone to reproduce the issue

try to watch any mature content warning enabled streams on twitch.tv "front page" & streamhtml5.com.

### Your settings

Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate

Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing/beacon 
Prevent WebRTC from leaking local IP addresses 

- Browser/version: 53.0.2785.89 m
- uBlock Origin version: v1.9.4

##### Your filter lists

Parse and enforce cosmetic filters
Ignore generic cosmetic filters

Default filter lists + Adblock Warning Removal List,  Anti-Adblock Killer | Reek‎,  Peter Lowe’s Ad server list‎,  EasyPrivacy‎,  Fanboy’s Enhanced Tracking List‎,  Anti-ThirdpartySocial,  Fanboy’s Annoyance List‎,  Fanboy+Easylist-Merged Ultimate List‎.

I tried turning these filters off & switching easylist without element hiding, no luck.

##### Your custom filters (if any)

no custom filters

EDIT: the problem was Parse and enforce cosmetic filters, sorry, my bad.

**Comment by gorhill** [comment]
I won't delete, I will mark as _invalid_ as per CONTRIBUTING, because you did not make the case there was an issue with uBO itself rather than the filter lists, and you did not provide the all-caps requirement asked to you in CONTRIBUTING about providing **an exact URL**.
