### ISSUE TITLE
Question: is it possible to determine which list a rule came from in the logger?

### ISSUE THREAD

**Issue by dhowe** [gorhill/uBlock#1967]
This would be useful when trying to identify where a problematic rule is coming from... 

thanks

**Comment by gorhill** [comment]
Click on the filter. See: <https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates>.

**Comment by dhowe** [comment]
excellent (just what i was looking for...)
