### ISSUE TITLE
Advice for using uBlock and uMatrix together

### ISSUE THREAD

**Issue by EchoDev** [gorhill/uBlock#1969]
Hi,

I'm using uBlock and uMatrix together and I need some advice for filters.

According to this [ticket](https://github.com/gorhill/uMatrix/issues/32) it is better to use uMatrix for lists that are available in both addons. Is this still the case or do uMatrix and uBlock communicate with each other when both addons are used?

Is there anything else that we need to know about when using uBlock and uMatrix together?

Thanks

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
