### ISSUE TITLE
#587 still occurs

### ISSUE THREAD

**Issue by Maxime-J** [gorhill/uBlock#197]
With Ublock Origin 0.9.7.0 on Linux Mint 17.1 (Chrome last stable release) and 16 (Chrome 34).
Subscriptions:
Liste Fr+Easylist (https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt)
Easy Privacy

As described in https://github.com/chrisaljoudi/uBlock/issues/587,
when I launch the browser, the ads are not removed.

As a test page, you can use this one:
http://www.leboncoin.fr/annonces/offres/rhone_alpes/
Two ads banners and custom background sometimes.

Thanks ;)

**Comment by Maxime-J** [comment]
Update with more details:
When this happens, I have these two errors in the console:
```
Uncaught Error: Attempting to use a disconnected port object extensions::messaging:70 
Uncaught TypeError: Cannot read property 'messaging' of null chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/js/vapi-client.js:142
```

**Comment by gorhill** [comment]
Can you tell **all** settings which differ from out-of-the-box settings (aside _"Liste Fr"_)?

**Comment by Maxime-J** [comment]
-Number of blocked requests on the icon and context menu unchecked
-All built-in lists unchecked aside EasyPrivacy
-One custom list (fusion between Easylist and Liste FR)

**Comment by gorhill** [comment]
I can't reproduce.

I did find a small glitch in the code, but it would manifest **only** if the site is whitelisted -- which I am assuming of course is not your case.

**Comment by Maxime-J** [comment]
Ok, maybe that's because the two PCs are low specs.
If that can help you, here is a screenshot of what is injected when I have that bug:
![injected](https://cloud.githubusercontent.com/assets/12450219/7667677/9deb4510-fc11-11e4-9a8f-1396c2b197f3.jpg)

And after few tests, the only relevant console error for this problem is the following:
```
Uncaught Error: Attempting to use a disconnected port object extensions::messaging:70
```
The other error (Cannot read property 'messaging' of null) is due to vapi-client
```
if ( window !== window.top ) {
    vAPI.shutdown.add(function() {
        vAPI = null;
    });
}

```
Thanks for your time.

**Comment by gorhill** [comment]
> maybe that's because the two PCs are low specs

I did try the following test:

- Set up uBlock as per your settings
- Disable uBlock
- Open the offending [web page](http://www.leboncoin.fr/annonces/offres/rhone_alpes/)
    - Banner ad show up (I see only one at the top)
- Enable uBlock
    - Ad disappear -- leaving behind a white area

Can you see if you get the same thing? This mimics having uBlock starts **after** the web page is loaded.

**Comment by Maxime-J** [comment]
Yep, ad disappear and I cannot reproduce the bug with that procedure (after several tests)

**Comment by gorhill** [comment]
Ok... So now the reverse test, to mimic uBlock starting before the page loads, which is what your screenshot show above:

- Enable uBlock
- Load the offending page
- Disable uBlock
- Enable uBlock

Now you should have just like above, scripts injected from `file://` and from `uBlock Origin`. This is the case you say is not working. I did try this one and all was fine.

**Comment by Maxime-J** [comment]
I don't get it,
because if you disable/enable ublock after ads already have been blocked, we won't see the difference?

If I disable/enable after I encounter the bug, ads are blocked but contentscript-start.js is loaded from `uBlock Origin` AND from `file:///` whereas in the screenshot, it's only loaded from `uBlock Origin`.

**Comment by gorhill** [comment]
> if you disable/enable ublock after ads already have been blocked, we won't see the difference?

I know, but I am at a lost of understanding why the ads are not hidden at start on your side. Just checking everything.

> `contentscript-start.js` is loaded from uBlock Origin AND from `file:///` whereas in the screenshot, it's only loaded from `uBlock Origin`

Good point, I completely missed this.

**Comment by gorhill** [comment]
I will attempt a fix, can you try the dev build if I push one?

**Comment by Maxime-J** [comment]
Of course, but tomorrow only cause I just leaved the place where I have the computer involved.

**Comment by Maxime-J** [comment]
I just tested your last commit (https://github.com/gorhill/uBlock/commit/087cd4e6454c1053654b21501ed7f78e3a753016) and It doesn't change anything.

It's weird that you can't reproduce, even today on a third Windows computer I can see this bug:
I make sure chrome is not running, I launch the desktop shortcut to the offending page and 50% of the time, I have this bug with the console error (Attempting to use a disconnected port object).

Anyway, it's not a very important issue and might as well be caused by a chrome bug.

**Comment by gorhill** [comment]
Ok I will have to take my time to investigate this more thoroughly.

I remember having a good idea of what the problem could be but I forgot about it.. It will come back.
