### ISSUE TITLE
local file:// filter lists not loading in Chromium browsers

### ISSUE THREAD

**Issue by 0strodamus** [gorhill/uBlock#1971]
- Browser/version: I've noticed this behavior in several different chromium-based browsers, i.e Inox 53.0.2785.89, Iridium 51.1, Vivaldi 1.3.551.38
- uBlock Origin version: 1.9.4

Issue: I have a couple local filter lists that I use. If I add them to uBlock0's "3rd-party filters" Custom section using `file:///home/username/.config/ublock0-filters/custom-filters.txt`, they do not load. The filter name shows as `file:///home/username/.config/ublock0-filters/custom-filters.txt` and uBlock0 reports "0 used out of 0" and "out of date".

Resolution: I have found the following will allow local filter lists to load properly. Edit the uBlock0 manifest.json permissions starting at line 47, and add `,file:///*/*` to the end of the list.

**Comment by lewisje** [comment]
That sounds similar to what an extension would need to do to request the permission to "Allow access to file URLs"; some extensions have that checkbox in the Extensions menu, but uBlock Origin does not.

**Comment by gorhill** [comment]
I need to add `"optional_permissions": [ "file:///*" ]` to the manifest.

[Advantage of optional permission](https://developer.chrome.com/extensions/permissions):

> Easier upgrades: When you upgrade your extension, Chrome will not disable it for your users if the upgrade adds optional rather than required permissions.

Last time I changed permissions (added `privacy` to control pre-fetching, webrtc config, etc.), there was a lot of knee-jerking, i rather avoid this this time.

**Comment by 0strodamus** [comment]
I did a quick test with `"optional_permissions": [ "file:///*" ]` in the manifest (replacing the permission I added in my first post) and noticed that my filters still weren't loading. However, after I opened the extensions tab and unchecked/rechecked "Allow access to file URLs", they loaded and are continuing to load properly after restarting the browser.
