### ISSUE TITLE
Firefox hangs every time I start it after Installing uBlock origin

### ISSUE THREAD

**Issue by uptonn** [gorhill/uBlock#1973]
### Describe the issue

Every time when I start Firefox it doesn't respond to anything (crashes) for about 20 seconds, only happens when I install uBlock Origin, it happened to me since version 1.9.4. I waited for version 1.9.6 to be fixed but seems latest version doesn't solve the problem.
- Browser/version: Firefox/48.0.2
- uBlock Origin version: 1.9.6 with default filters

PS: I also removed all other addons except uBlock, the problem still exists.

**Comment by gorhill** [comment]
You will have to investigate on your side, there is no such issue reported elsewhere. See what the browser console says.

**Comment by uptonn** [comment]
this what console says:

![console](https://cloud.githubusercontent.com/assets/22100111/18390488/4f7c43a4-76a2-11e6-9089-4c5c488cff68.png)

**Comment by gorhill** [comment]
Interesting. I get this error on a random basis, and it causes uBO to start malfunction -- related issue #1713.

Frankly, I don't know what to make of it. I think this should be reported to FF issue tracker -- surely someone in there has better insight of what is going than I can provide.

By the look of it, it is as if a modal window is opened in uBO's iframe context -- which is not supposed to happen -- hence the error. uBO of course never opens a modal window, let alone open one in its chrome code, so for some reasons the browser itself is doing this, and this causes the issue.

The above speculation is supported by <https://bugzilla.mozilla.org/show_bug.cgi?id=1167575>, which is what the dev console shows as happening.

Bottomline: we need insight from FF devs, I don't know why this condition arise.

**Comment by gorhill** [comment]
I [commented about the case here in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1167575#c49), awaiting feedback.

**Comment by gorhill** [comment]
Do you have user preferences which differs from default ones?

**Comment by uptonn** [comment]
@gorhill 
no I didn't change anything in uBO settings its all defaults, I also didn't change settings in Firefox

**Comment by gorhill** [comment]
When you launch Firefox and the issue occurs, are there any tab loading? If so, what URL?

**Comment by uptonn** [comment]
Yes, ATM I have default home page set to: "https://www.google.com/ncr" but even when I change it to (Show a Blank page) same result. FF still Crashes for few sencods

**Comment by gorhill** [comment]
Similar issues already reported at bugzilla or elsewhere:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1083803
- https://bugzilla.mozilla.org/show_bug.cgi?id=1186727
- https://www.bountysource.com/issues/25224778-about-blank-the-script-with-alert-function-after-the-restart-the-browser-hangs

**Comment by gorhill** [comment]
If you launch FF without uBO, then enable uBO after FF launched, do you still have the issue?

The fact that you can reproduce at will is kind of precious, this means surely there must be a way to try to find out what is causing the creation of a modal window at launch time.

**Comment by Tmp341** [comment]
Check your crashes with `about:crash`  and/or try creating a new profile.

**Comment by gorhill** [comment]
Actually, try to delete uBO's SQL database, to force it to re-generate it. Maybe a corrupted SQL file is behind this. See <https://github.com/gorhill/uBlock/blob/master/dist/README.md#firefox>  for the locationof teh SQL file.

**Comment by uptonn** [comment]
I might go to hell for doing this because I think the bug isn't 100% identified yet, but when I was googling about how I solve Firefox issues I found about resetting Firefox might solve the problem, so I did "Refresh Firefox" in about:support and then Installed uBO after that the problem is solved and I can't reproduced it, I'm very sorry if what I did will no longer help catch this mysterious bug.

**Comment by uptonn** [comment]
@gorhill
previously when I launched FF without uBO enabled it started fast, but as soon as I Enable it, FF crashes for few seconds, I hope that helps.

**Comment by gorhill** [comment]
Now I am looking more closely at your screenshot and realize I was wrong to say it's similar to #1713, it looks like uBO was timing out on loading the compiled filter lists.

**Comment by coladict** [comment]
@uptonn open `about:config` filter for `e10s`. The values you'll see there will tell you if you're one of the test subjects for the new multiprocess Firefox which requires a migration to the new API in #622 to be compatible in the near and distant future.

**Comment by Zuldra** [comment]
I have the same problem.

Steps to reproduce:

1) Install Firefox E10s / Nightly and configure it for 8 processes.
2) AFTER YOU HAVE A LOT OF TABS, uBlock Origin begins crashing the session upon every startup.

Currently I have 500 tabs. That means uBlock Origin will crash the session every time at startup.

**If you don't have 500 tabs, then uBlock Origin will appear to run normally and will not crash at startup.**

## The more tabs you have, the higher the chance that uBlock Origin will be unable to handle a startup.

There's no possible chance I am ever going to use less than 500 tabs (I have 4 displays, and a special computer just for this purpose) so therefore uBlock Origin is completely unusable.

3) AFTER FIREFOX FINISHES STARTING UP, you **can** enable uBlock Origin, and it works properly.
