### ISSUE TITLE
Adguard blocking and not blocking ublock

### ISSUE THREAD

**Issue by r35p3ct** [gorhill/uBlock#1974]
opera 39.0.2256.71
ublock 1.9.6
filter: https://adguard.com/en/filter-rules.html?id=1
site: http://rufilmtv.org/

When the ublock banner is displayed in 50 % of cases.
Including additional Adguard banner blocked by 100%.

![ruf](https://cloud.githubusercontent.com/assets/7328803/18411637/f26a040c-7783-11e6-973b-f2e31cffd806.JPG)

There is a suspicion that the rule does not work **|| brokeloy.com ^ $ third-party.**
If you watch the log ublock , it is not mentioned , and the logs adguard it appears .
![ruf2](https://cloud.githubusercontent.com/assets/7328803/18411639/058fddcc-7784-11e6-9b17-8476d1d736ab.JPG)

**Comment by gorhill** [comment]
Install [uBO-WebSocket](https://github.com/gorhill/uBO-WebSocket).
