### ISSUE TITLE
Bug: Generic cosmetic filters not enforced in specific circumstance

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#1977]
## The Issue

uBlock Origin does not enforce generic cosmetic filters when "Parse and enforce cosmetic filters" has been enabled, and then is disabled, even when "Ignore generic cosmetic filters" is _unchecked_.
## Steps to Reproduce
1. Create a fresh Firefox profile in Firefox v48.0.2 (current stable release version)
2. Install uBlock Origin v1.9.6 (current stable release version)
3. Check the checkbox for "Parse and enforce cosmetic filters"
4. Press "Apply"
5. Check the checkbox for "Ignore generic cosmetic filters"
6. Press "Apply"
7. Uncheck the checkbox for "Parse and enforce cosmetic filters"
8. Press "Apply"
9. Uncheck the checkbox for "Ignore generic cosmetic filters"
10. Observe that no "Apply" button appears
11. Observe that generic cosmetic filters for "My filters" are **not enforced** even though they are supposed to be enforced
12. Also note that generic filters for all "uBlock filters" lists are now **not enforced** even though they are typically enforced even when "Parse and enforce cosmetic filters" is unchecked (that is another issue)

**Comment by Wannabe-Programmer** [comment]
I can also confirm.

As long as the `Parse and enforce cosmetic filters` is unchecked, the `Ignore generic cosmetic filters` checkbox will not prompt the "Apply Now" button.

**Comment by gorhill** [comment]
Can't reproduce anymore. Just a guess: this was probably fixed when the "3rd-party filters" pane was refactored: <https://github.com/gorhill/uBlock/pull/2314>.
