### ISSUE TITLE
The fix implemented for openload.co now breaks functionality

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gorhill/uBlock#1979]
It worked well for quite a while, but now videos won't play with uBO installed. I tested it in the latest stable Chrome 53.0.2785.101 (64-bit) with default lists (updated) to make sure it wasn't a personal setting. 

Example: https://openload.co/f/KnchpIfAN4g/Warcraft.2016.720p.BluRay.x264-%5BYTS%5D.mp4

Original fix: https://github.com/gorhill/uBlock/issues/1194

**Comment by kasper93** [comment]
They have this code [1] under eval and three other obfuscation methods. This is critical to watch anything. With latest uBO version you can do `openload.co#@#script:inject(noeval.js)` to fix problem until filters are updated.  

1.
``` javascript
$(document).ready(function() {
  var x = $("#hiddenurl").text();
  var s = [];
  for (var i = 0; i < x.length; i++) {
    var j = x.charCodeAt(i);
    if ((j >= 33) && (j <= 126)) {
      s[i] = String.fromCharCode(33 + ((j + 14) % 94));
    } else {
      s[i] = String.fromCharCode(j);
    }
  }
  var tmp = s.join("");
  var str = tmp.substring(0, tmp.length - 1) + String.fromCharCode(tmp.slice(-1).charCodeAt(0) + 2);
  $("#streamurl").text(str);
});
```

ps. This is wrong repository to report filter related issues. You should have reported it here https://github.com/uBlockOrigin/uAssets

**Comment by narcolepticinsomniac** [comment]
My bad, I'll post in the correct place in the future. I updated filters and the problem is resolved. Thanks gorhill.
