### ISSUE TITLE
Ctrl+click support for popup block

### ISSUE THREAD

**Issue by njascgil** [gorhill/uBlock#198]
I am not sure if this qualifies as a bug, but I'll try to describe it anyway.

I really like the popup blocking toggle from the uBlock menu and I am using it for some sites.
I also tend to use the Ctrl+click combination (quite often) to open links in new tabs. However, this behaviour is blocked by uBlock. If I just click any link, the page opens (in the same tab), but Ctrl clicking it does not work, which looks a bit counter-intuitive. Is this working as intended?

**Comment by gorhill** [comment]
You are not giving details about the browser, I will assume you are using a Chromium-based one.

If so, it's a Chromium-based browser limitation. See <https://github.com/chrisaljoudi/uBlock/issues/1143>.

**Comment by njascgil** [comment]
Thanks! And I really thought I searched for the right terms before posting... Shame on me...

**Comment by gorhill** [comment]
Issue was in the main branch, not here.
