### ISSUE TITLE
page broken i think

### ISSUE THREAD

**Issue by ghajini** [gorhill/uBlock#1980]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
forward , backward button not working on itimes.com with ublock enabled

### One or more specific URLs where the issue occurs

http://ww.itimes.com/photo/sunny-leone-skips-own-documentary

### Screenshot in which the issue can be seen

![screenshot 37](https://cloud.githubusercontent.com/assets/20338483/18469630/8a75c8c8-79c6-11e6-9144-57f90e1913e8.png)

### Steps for anyone to reproduce the issue

1. go here itimes.com, i used no cosmetic filtering for this site as this site detects adblock

1. click any news e.g 
http://ww.itimes.com/photo/sunny-leone-skips-own-documentary

1. click forward button to see next pic,this time it will load pic but then
again click forward button it will not show(load next page) next story or pic, similarly backward button :it will not work 
![screenshot 37 1](https://cloud.githubusercontent.com/assets/20338483/18470065/8962d258-79c8-11e6-8e3d-acbaf85cecfb.jpg)

### Your settings

all default settings + antiadblock killer+ adblock warning removal+ 
no cosmetic filtering for itimes.com

- Browser/version: 

        mozilla firefox 48.02
        chrome Version 53.0.2785.101 m (64-bit)

- uBlock Origin version:  1.9.6(for firefox)
 1.9.4(for chrome)

##### Your filter lists
all default settings + antiadblock killer+ adblock warning removal+ 
no cosmetic filtering for itimes.com

##### Your custom filters (if any)
no cosmetic filtering for itimes.com

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
