### ISSUE TITLE
Bug with openload website

### ISSUE THREAD

**Issue by ashleelhaiyelaunda** [gorhill/uBlock#1981]
Hi there,
             the openload doesn't play videos with ublock enabled.but plays soon as it is disable. Th error it shows is the media cannot be loaded either because of the server failed or because the format not supported. Please help

**Comment by gorhill** [comment]
Update your filter lists. Also, report to uAssets next time, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
