### ISSUE TITLE
uBlock Origin has disabling acceleration features of Google Chrome

### ISSUE THREAD

**Issue by J4yRich** [gorhill/uBlock#1982]
One of the reasons why Chrome is slow...

![image](https://cloud.githubusercontent.com/assets/10944814/18475874/ebb2a9f2-797c-11e6-8a99-5dc2e8acddb7.png)

**Comment by jjohns71** [comment]
English Description: 
![capture](https://cloud.githubusercontent.com/assets/6795795/18476199/1abd5304-7997-11e6-8248-84044645ea61.PNG)

**Comment by gorhill** [comment]
Just unselect the _"Disable pre-fetching (to prevent any connection for blocked network requests)"_ option in the _"Settings"_ pane.

Also, read the documentation before opening issues.

**Comment by gorhill** [comment]
> One of the reasons why Chrome is slow

Placebo. You can see for yourself using <http://www.raymondhill.net/ublock/pageloadspeed.html>.

**Comment by J4yRich** [comment]
I was looking for but did not find the problem you say to fix

Please can give picture ?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-pre-fetching

**Comment by jjohns71** [comment]
![capture](https://cloud.githubusercontent.com/assets/6795795/18480086/5b33e656-79a5-11e6-8396-1668be569cfa.PNG)

**Comment by J4yRich** [comment]
Yes, thank you !
