### ISSUE TITLE
a link on wiki is not available

### ISSUE THREAD

**Issue by blob2015** [gorhill/uBlock#1983]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax
➟script:inject(...) →"resource library"【https://github.com/gorhill/uBlock/blob/master/assets/ublock/resources.txt】

click it, 404 :grinning:

**Comment by gorhill** [comment]
Fixed: <https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt>.
