### ISSUE TITLE
Some pages get greyed out

### ISSUE THREAD

**Issue by skanskan** [gorhill/uBlock#1984]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Often  I can hide an element but the rest of the page keeps being greyed out.

### One or more specific URLs where the issue occurs

http://www.avaxhome.co/

### Screenshot in which the issue can be seen

https://imgur.com/a/h9wjC

### Steps for anyone to reproduce the issue

It happens in many web sites, but I don't remember now.
If you pick an element to hide it you can hide it but many times the pages gets greyed out and it's impossible to view it properly or scroll it.

I know the example page I've  posted has some kind of adblock detector but it happens in normal ones too.

### Your settings

Windows 10
Chrome 52
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing/beacon 
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate

- uBlock Origin version: 
uBlock Origin v1.9.4

##### Your filter lists
uBlock
uBlock Badware
Anti-Adblock Killer | Reek
EasyList‎
Peter Lowe’s Ad server list
EasyPrivacy
Malware Domains
AakList

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
