### ISSUE TITLE
Sue ublock.org

### ISSUE THREAD

**Issue by CrazyPython** [gorhill/uBlock#1985]
You are the original developer. You have total copyright control. They make [false claims](https://www.ublock.org/faq/) and act like the "official" adblock.

A cease and desist should be enough.

**Comment by gorhill** [comment]
I don't personally suffer any damage out of this. Those who donated thinking they were supporting uBlock Origin are the ones suffering the damage.

**Comment by CrazyPython** [comment]
@gorhill those donations would've gone to you. and they got ublock.org. Misleading, less users, and less deserved fame.

**Comment by CrazyPython** [comment]
Despite the fact that uBlock is not developed anymore, they still receive donations for server money. Donations for a dead project. Going to the pocket of someone else.
