### ISSUE TITLE
merci gorhill uBlock

### ISSUE THREAD

**Issue by wbmstr** [gorhill/uBlock#1990]
Merci gorhill pour uBo qui bloque les sites pourris par la publicité et **pénalise** les sites qui utilisent les pubs de manière **raisonnée** pour faire vivre leur services.

aujourd'hui ... je mis la clé sous la porte.

cordialement,
webmaster

**Comment by Hrxn** [comment]
Wanna be grateful, read CONTRIBUTING.MD...

**Comment by gorhill** [comment]
Les visiteurs de votre site sont libres de désactiver uBO si ils le veulent. Addresser-vous à eux.

**Comment by wbmstr** [comment]
@gorhill j'ai juste dit Merci !! 

PS: votre façon de communiquer est impoli, orgueil ou vanité je sais pas.

**Comment by uBlock-user** [comment]
Whether he was rude or not, you sound very sarcastic, so that doesn't count. Either way, this is for issues with uBlock only, not for your rants against blocking or not.

**Comment by gorhill** [comment]
> you sound very sarcastic

He definitely was sarcastic.
