### ISSUE TITLE
Problem with newest version ublock origin for firefox - site cda-online.pl detects and blocks ublock origin

### ISSUE THREAD

**Issue by seba2282** [gorhill/uBlock#1993]
Problem with newest version ublock origin for firefox - site cda-online.pl detects and blocks ublock origin.

Can You help me ?

Best Regards

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
