### ISSUE TITLE
Can't create element hiding filters with wildcards?

### ISSUE THREAD

**Issue by maxiedaniels** [gorhill/uBlock#1994]
I'm trying to create a filter that includes a wildcard for a div id. According to multiple sources online regarding adblock filter writing, it seems this is how to do so:

`##div[id*=“testword"]`

But in the rule add window, once I type that in, the create button is greyed out. And preview shows nothing changing.

**Comment by anewuser** [comment]
You've ignored and deleted the template text that appears when you create a new issue.

That text isn't there just for decoration.  Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by Blutgang** [comment]
Um...shouldn't that filter be written as ````##div[id*=“testword"]````?

**Comment by maxiedaniels** [comment]
Sorry, I wrote the * on the wrong side of the =. Still doesn't work for me.

anewuser: I did read the template text, most of it didn't apply to my issue, which seems to be that a valid filter isn't being accepted. If a valid filter isn't being accepted, that would qualify as a bug. If I've written the filter wrong, then fair enough, but if you know what the issue is, I'd be grateful if you could tell me what I'm doing wrong.

**Comment by anewuser** [comment]
>I'd be grateful if you could tell me what I'm doing wrong.

Post on the proper forum and you'll be helped.

**Comment by gorhill** [comment]
Your filter is not valid. See @Blutgang's answer.
