### ISSUE TITLE
Blocking external scripts by contents or IP

### ISSUE THREAD

**Issue by Anorov** [gorhill/uBlock#1996]
I read https://github.com/gorhill/ublock/wiki/inline-script-tag-filtering and see you can block inline scripts by looking for substrings within the script. What about cases where there's an external script resource (`<script src=...`) that, for whatever reason, can't be effectively blocked by network filtering? Will `script:contains()` work for externally loaded scripts?

And for cases where a script may constantly fluctuate between tons of potential domains which all use the few same IP addresses or subnets, is there a way to blocked by resolved IP address?

Thanks.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

The issue tracker is for **actual** issue with uBO. If you can't provide repro steps, it's a sign of an invalid issue.
