### ISSUE TITLE
Suggestions/Request

### ISSUE THREAD

**Issue by mikhoul** [gorhill/uBlock#1997]
Hi @gorhill ,

Could it be possible to have the option of opening the UBO page on their own Windows instead of only in tabs ? 

It would be really useful for me to debug sites which detect UBO to monitor what happen "inside" with the logger and see the webpage at the same time.

Most of the time I have to detach the logger tabs to put it in their own window,  it's not a big thing but it's annoying when you do this many time per day...  :wink: 

Just an option that we can "tick" would be fine ! 

Have a nice day !    :smile:

**Comment by gorhill** [comment]
Press <kbd>Shift</kbd> while clicking the logger icon.

**Comment by gorhill** [comment]
Are you using Firefox or Chromium?

**Comment by mikhoul** [comment]
Thanks @gorhill for the promt reply, :+1: 

 I'm using Firefox (most of the time, sometime I use Chromium for testing) .

I know about the "shift" shortcut but it would be useful to have the option to choose it by default. 

Like I said it's not a "big big thing" but it would be less annoying since most of the time I need to see what happen on the screen when the resources load in the logger.

Regards :smile_cat:

**Comment by gorhill** [comment]
The current behavior annoys me too. I often use the logger to diagnose filter issues, and most of the time forget to press the shift key.

At first I thought of using of hidden settings (in `about:config` for Firefox), but I have settled on the following solution: from now on, the shift key means "toggle and remember for next time the detached/non-detached behavior".

So when using the shift key the first time to bring up the logger, the logger will be launched in detached mode, and this will remembered the next time you bring the logger -- without having the press the shift key. Using the shift key again will toggle the logger back to non-detached mode.

**Comment by mikhoul** [comment]
Great ! :+1: 

On which version it will be implemented @gorhill ?  It will save me some small frustration when debugging more complex filters, especially since @reek and his anti-adblock filter is "missing in action" I have to tweak/update many more filters.

One last question for my curiosity: Where the "setting" is saved when we use CTRL to toggle between tabs and windows ? 

Thanks for your help :octocat:

**Comment by mikhoul** [comment]
@gorhill  Thanks it work perfectly :+1: 

Could you add the same option to  Settings/Options button in the panel ? 

For the same reason I use it a lot when I work with XPATH filter so it would be wonderful if the settings/options/filter page would open in their own window :octocat: 

Best Regards !
