### ISSUE TITLE
Issues when using Box Service.

### ISSUE THREAD

**Issue by Jazzakaz** [gorhill/uBlock#1998]
Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
### Describe the issue

I'm with IT for a company, one of my users has been using this extension for some time. After the 1.9.6 update the user was getting extremely slow upload/download speeds via the Box service (https://www.box.com/). He was experiencing about 400kb/s down when previously speeds upward of 10mb/s were normal. Disabling this extension solved his issue. Note that this only happens when using the Box service, other websites are downloading/uploading at normal speeds with the addon installed and enabled.
### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
https://app.box.com/
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
### Steps for anyone to reproduce the issue
1. Be as detailed as possible:
2. Because we are not looking over your shoulder and
3. Keep in mind: Nobody can read your mind.

Using chrome with uBlock addon installed and enabled.
1. Log into Box account at https://app.box.com/. User experiences this with two different domain box accounts.
2. Choose file stored on Box that you'd like to download. This particular user has many files that are >5GB.
3. Right click file, select download. Download begins. When checking download speed in chrome downloads tab, slower than normal download speed is experienced.
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
- Browser/version: Chrome Version 52.0.2743.116 m
- uBlock Origin version: 1.9.6

Default settings.
##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Default filter lists.

**Comment by gorhill** [comment]
What make you conclude this is a uBO issue rather than a filter issue?

**Comment by Atavic** [comment]
Yes, fine tune your filters, box.com uses 3rd-party scripts.

**Comment by gorhill** [comment]
Assuming filter list issue, thus invalid.
