### ISSUE TITLE
ublock is causing CPU hog with psmag.com

### ISSUE THREAD

**Issue by ray890** [gorhill/uBlock#2]
Hi.  I am a user of ublock with the latest version of chrome and windows 7 x64, and I have found a site that has caused a hog in CPU usage.

All that needs to be done to reproduce this issue is visit this URL with ublock enabled: http://www.psmag.com/
After, take a look at the chrome Task Manager, and there will be a CPU hog coming from the psmag tab.  After disabling ublock and revisiting, there is no longer a CPU hog coming from that tab.

Can you look into this?  I think this may come down to a bug that very well is the cause for experiencing random CPU hogs once I'm on random but simple websites/pages for no reason at all.

Thanks

**Comment by gorhill** [comment]
The page repeatedly try to fetch something at `http://dove.saymedia.com/rid`, but it's blocked by uBlock. Looks like as soon as it is told it was blocked, it tries again immediately. You can stop the issue by not blocking `dove.saymedia.com`.

So problem is the site itself, bad programming. Just investigating the issue, the block counter of uBlock is now over 13K...

**Comment by ray890** [comment]
I suspected this was a case of bad site programming.  I already know psmag isn't the only site with the issue; now and then I'm reading an article on some forign blog site that may have programming flaws and I keep getting this issue randomly.
uBlock should detect these kinds of conditions and handle it from there to stop any obvious loops from continuing.
