### ISSUE TITLE
Canvas - AudioContext - Battery API

### ISSUE THREAD

**Issue by gameb0y** [gorhill/uBlock#2003]
please block this

Block Audio Fingerprinting: (Default: disabled; prevent fingerprinting via the AudioContext API)

Block WebGL Fingerprinting: (Default: disabled; prevent fingerprinting via the WebGL API)

Block Battery Fingerprinting: (Default: disabled; prevent fingerprinting via the Battery API)

Block Device Enumeration: (Default: disabled; prevent having hardware devices detected via the WebRTC API)

Block Gamepad Enumeration: (Default: disabled; prevent having devices detected via the Gamepad API)

Block Canvas Font Access

Canvas Fingerprint
www.browserleaks.com/canvas

AudioContext Fingerprint
https://audiofingerprint.openwpm.com/

Battery API
http://techcrunch.com/2015/08/04/battery-attributes-can-be-used-to-track-web-users/

webrtc unique devices id's and ip leaks
www.browserleaks.com/webrtc

example: ScriptSafe
https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf

![8b02c99c-35c1-11e6-916e-d9ebe5bd736d](https://cloud.githubusercontent.com/assets/19530450/18598496/ce25d73a-7c31-11e6-9cc3-6404379e6826.png)

**Comment by Wannabe-Programmer** [comment]
This add-on does the job for most of them - https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/?src=search

**Comment by gorhill** [comment]
> please block this

Done:

![a](https://cloud.githubusercontent.com/assets/585534/18615271/53a406cc-7d70-11e6-98e6-339a0be8b40c.png)

**Comment by uBlock-user** [comment]
Why not just use Script Safe together with uBlock Origin ? If both are compatible with each other, then just use both, that way you're completely protected.
