### ISSUE TITLE
Icons missing from uBlock interface/ menu

### ISSUE THREAD

**Issue by BelladonnavGF** [gorhill/uBlock#2004]
Dear Gorhill, 

**First of all thanks for creating uBlock and uMatrix!** We use both and think that the applications are just perfect!

I do want to report this issue concerning uBlock, which concerns the application itself, and occurs always, hence is NOT connected with a specific URL. The box it occurs on is a Xubuntu 14.04 LTS (kernel 4.4.0-36) box, where uBlock 1.9.6 is added as extension to Mozilla Firefox 48. uBlock is installed as is, and not configured as "advanced user" or with added filters.

The user of this box noticed at a certain point that the "interface" of uBlock had "changed".
When investigating further, it turned out that **several icons from the uBlock GUI are missing**. I include a screenshot so you can see for yourself.

As you can see the missing icons are:
- the big ON/ OFF power button
- the "picker" icon
- the "logger" icon
- the "film strip", large media toggle icon
- the "remote fonts" toggle icon

I tried to find where the icons would be stored, but could not locate them. The .xpi was where I expected it to be however ($HOME/.mozilla/firefox/blahblah.default/extensions/). I tried the following steps to restore uBlocks original interface:

- deinstall, reinstall the existing (local) .xpi
- deinstall, delete the existing .xpi and subsequent .sqlite, and do a fresh install from addons.mozilla.org
- deinstall, delete fresh install from addons@mozilla, and restore the backup ~/.mozilla profile of the box (rsync) from when all was well

All these options did not restore the interface of uBlock. However, as far as I can see (see screenshot 2), uBlock does still function as it should (Requests blocked > 0%). Funnily enough, using it seems to also influence the missing icons; as screenshot 2 shows the "picker" icons decided to make its return. That makes me suspect that the icons are not simply deleted (is that even possible?) but something else is at hand here.

Puzzled, I wanted to let you know this, and ask what could be a way to restore the original interface/ icons.

![screenshot_2016-09-18_16-46-26](https://cloud.githubusercontent.com/assets/19425080/18616624/92765270-7dbf-11e6-9823-98adabb8fba6.png)
![screenshot_2016-09-18_17-21-08](https://cloud.githubusercontent.com/assets/19425080/18616885/766cd806-7dc4-11e6-8612-5d6c0042b135.png)

**Comment by gorhill** [comment]
The icons are located in the `./src/css/fonts/fontawesome-webfont.ttf` in the extension.

**Comment by gorhill** [comment]
Also see message #32 in the thread: <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827517#32>.

**Comment by BelladonnavGF** [comment]
Hi Gorhill,

Thanks for the lightnin' fast reply!

I followed your suggestions, and had the opportunity to double check with a (Xubuntu 16.04.1) box where all is fine (i.e. the uBlock UI does show the icons). What I found was:
- the .xpi on the box with "no icons uBlock" does contain fontawesome-webfont.ttf
- there is no /usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf on **both** boxes. Did create it on the "no icons uBlock" box - did not resolve the issue. Hence, removed it again. Perhaps this dir is specific to Debian installs?
- tried placing the ttf in the "general fonts dir" - did not resolve the issue, so removed it again.
- Ran a search on both boxes for fontawesome-webfont.ttf, and had no results on **both** the "no icons uBlock" box and its OK counterpart.

But finally resolved it. Really silly actually. Remembered reading it somewhere, so tried it.

In about:config ---> browser.display.use_document_fonts was set to 0
When returned to 1 (default) all is fine and all fonts have returned on the uBlock UI

Why I'm not declaring a complete victory though, because that I found that on the OK box, browser.display.use_document_fonts was also set to 0, and there the uBlock UI is just fine. =P

Thanks again for being so quick in giving pointers!

**Comment by gorhill** [comment]
>  I found that on the OK box, browser.display.use_document_fonts was also set to 0, and there the uBlock UI is just fine.

From Firefox 41 and later, setting `browser.display.use_document_fonts` to `0` would not cause uBO's Fontawesome-based icons to fail rendering (see [_"Firefox 41: Mozilla modifies how icon fonts are handled by the browser"_](http://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/)). What was the version of Firefox for the box where the UI failed rendering properly?

**Comment by BelladonnavGF** [comment]
I double checked it for you - it was Firefox 48.0 - released 2 August 2016
