### ISSUE TITLE
some links/buttons do not work in a banking site

### ISSUE THREAD

**Issue by richlv** [gorhill/uBlock#2005]
while the url is https://ib.swedbank.lv , it probably won't help much, as it is a banking site that requires login.
there are some links that do nothing when clicked.

ublock origin v1.9.6, firefox 48.0.1.

default settings/filters - default lists as per installation, nothing changed at all.

a few things i have tried :
* allowing popups on that site - does not help
* allowing large media, disabling cosmetic filtering, allowing remote fonts (just in case) - does not help
* disabling ublock origin - then the links work

i'm a bit wary providing full log output - could you please suggest steps to narrow down the cause ?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
