### ISSUE TITLE
Official Twitter Account

### ISSUE THREAD

**Issue by z751** [gorhill/uBlock#2006]
Is it possible for us to get an official Twitter for ublock to stay up to date on the latest changes?

**Comment by Tmp341** [comment]
[This](https://github.com/gorhill/uBlock/releases) might help you.

**Comment by gorhill** [comment]
See release notes, as posted by @Tmp341.

**Comment by gwarser** [comment]
RSS https://github.com/gorhill/uBlock/releases.atom
