### ISSUE TITLE
uBlock Origin doesn't allow pulling from sync first on new installation.

### ISSUE THREAD

**Issue by Betsy25** [gorhill/uBlock#2008]
### Describe the issue
After installing uBlock Origin on a new profile (different browser or simple different profile), uBO only allows to export to Sync, although settings have already been uploaded to Sync from another profile/browser.
Only export is available in all filter tabs.

### Screenshot in which the issue can be seen

![Screenshot](http://s11.postimg.org/53w3667fn/2016_09_20_042133.gif)

### Steps for anyone to reproduce the issue

1. Sync uBO settings (Export to Sync server)
2. Install uBO in another profile/FF browser, and open the settings.
3. Observe, only the export button is available, although there are settings synced from another profile/FF browser, thus making Backup/Restore the only valid option to preserve settings upon new installation.

### Your settings

- "Enable cloud storage support " = Checked.
- Browser/version: **Firefox (any version)**
- uBlock Origin version: **1.9.7 rc0**

##### Your filter lists

Default filter lists

**Comment by Betsy25** [comment]
Just to add to this issue, even if you have 2 profiles with kind of the same filters, it seems like the whole Sync things doesn't really seems to do what it is suppose to.

Step To Reproduce : 
- Have 2 profiles open, using the same Firefox Sync profile, with both having the same filters, say in the "My filters" tab.
- Add a few filters in the "My filters" list on one profile, and export to Sync.
- In the other browser/profile, Import or Import & Merge, and observe that the changes are not imported.

**Comment by gorhill** [comment]
Aren't Firefox Sync settings on a per-profile basis?

**Comment by Betsy25** [comment]
AFAIK, the control of what specifics are synced have to be configured per profile, but if using the same login credentials, the same data should be available, no matter what FF version or profile.

I have all my different profiles set to only sync bookmarks and passwords, regarding uBlock data, if data is stored on the server, it could be imported if using the same login credentials for FF Sync.

**Comment by gorhill** [comment]
uBO merely reads the data put in there by FF, if there is nothing, it means no data was synced by FF.

**Comment by gorhill** [comment]
I can't reproduce:
- export _My filters_ data from main FF 48 installation
- quit FF
- launch FF with `-P` option, create new profile
- Sign in to Sync
- wait a bit for FF to sync

Results:
- Extension was installed automatically
- After enabling cloud support, _"My filters"_ pane showed the data previously sent to cloud a few minute earlier with other profile.

**Comment by Betsy25** [comment]
That's weird (and perhaps understandable), even after waiting minutes after enabling cloud support, nothing happens.
I only have bookmarks & passwords checked to be synced, you probably had all sync options checked (including Add-ons & Settings) which makes kinda sense, I was of the impression uBO uses the sync service kinda on it's own, but it seems specific sync options have to be set in order for uBO to be able to properly import after installing.

**Comment by gorhill** [comment]
> I only have bookmarks & passwords checked to be synced

You need "Add-ons".

**Comment by Betsy25** [comment]
Thanks. Now, I understand. Weird thing is, you don't actually need "Add-ons" enabled at all once 1 export has been done.

**Comment by gorhill** [comment]
> you don't actually need "Add-ons" enabled at all once 1 export has been done.

Because of the way FF sync works, uBO merely saves its data in `about:config` entries, which will work regardless of whether FF sync exists or not.

**Comment by Betsy25** [comment]
> Because of the way FF sync works, uBO merely saves its data in about:config entries, which will work regardless of whether FF sync exists or not.

Weird, that actually makes me believe checking "Preferences" to be synced should be enough.

**Comment by gorhill** [comment]
Those are special entries in `about:config`, they starts with `services.sync.prefs.sync.extensions.ublock0.cloudStorage.` -- the `extensions` part is probably what matches the "Add-ons" options in Sync prefs.

**Comment by ronjouch** [comment]
Same problem for me: I'm unable to setup syncing of my rules between two existing, initially non-synced installations (home ↔ work). I have no doubt the reproduction steps using a fresh profile described by @gorhill at https://github.com/gorhill/uBlock/issues/2008#issuecomment-248281746 *do* work, but I'd love to avoid having creating a fresh profile and re-importing all my conf; could anyone help me narrow down to potential mis-configuration of mine?

* Reading the discussion above, I'm unsure which parts needs to be synced: it's `Add-ons`, and `Preferences` does *not* have to be synced, right? Currently I'm syncing `Bookmarks` and `Add-ons`.
* Anything else?
