### ISSUE TITLE
uBlock breaks Evernote Web Clipper

### ISSUE THREAD

**Issue by MacProGirl** [gorhill/uBlock#2009]
The Evernote Web Clipper is broken when uBlock is enabled. Tried to uninstall it and then the web clipper worked.

- Browser/version: Firefox 48
- uBlock Origin version: 1.9.6

![evernote error](https://cloud.githubusercontent.com/assets/15187174/18663366/935145d2-7f1e-11e6-9e79-a95814f8bc73.jpg)

I have a lot of 3rd part filter lists enabled. Don't know how to submit them. No own filter lists.

I also use some dynamic ruled, but I guess that's not the main issue here. 

Would greatly appreciate your help in this issue!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
