### ISSUE TITLE
How do I block this popup bar thingy on YouTube?

### ISSUE THREAD

**Issue by xIxHATExMOBILExPROVIDERSx** [gorhill/uBlock#2019]
With uBlock Original enabled:

![untitled2](https://cloud.githubusercontent.com/assets/20170353/18760437/b50bda24-8109-11e6-8e65-bf7af5d4dfb3.png)

With uBlock Original disabled:

![untitled](https://cloud.githubusercontent.com/assets/20170353/18760451/c2346162-8109-11e6-8a22-6a0ed2153742.png)

This same exact very annoying bar keeps reppearing and I can not find a way to permanently block it, the bar I'm talking about appears above the YouTube button (the Googly thingy).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by jjohns71** [comment]
Are you talking about _wanting_ to display the privacy reminder? If so, it looks like it is a filter included in Fanboy's Annoyance List, just add 

`@@||youtube.com##.yt-consent` to your 'My Filters' tab to override it.
