### ISSUE TITLE
Some connections from whitelist are blocked

### ISSUE THREAD

**Issue by F4z** [gorhill/uBlock#2025]
Google Chrome 53.0.2785.116 m (64-bit)
uBlock Origin 1.9.8/1.9.9b1
Default  settings.

I observed that ublock Origin from 1.9.8 version blocks some connections that are on whitelist, for example here - `http://streamin.to/embed-edpnqlszc9f3-510x340.html`

To reproduce:
1. Open logger
2. Open this website - `http://streamin.to/embed-edpnqlszc9f3-510x340.html`
3. Video player is blocked, because uBO 1.9.8 blocks this:
![image](https://cloud.githubusercontent.com/assets/11742596/18810855/a17484a0-82a0-11e6-9bdb-feb153d82e39.png)

![image](https://cloud.githubusercontent.com/assets/11742596/18810856/aaafec62-82a0-11e6-9a9d-ecb4ec765339.png)

But in uBO 1.9.4 with the same settings and with updated filter lists it is not blocked:
![image](https://cloud.githubusercontent.com/assets/11742596/18810867/24b614b4-82a1-11e6-889f-ed8b55de7e07.png)

![image](https://cloud.githubusercontent.com/assets/11742596/18810870/2da7f7cc-82a1-11e6-9693-301aa551e6e5.png)

If I add this rule - `@@||p.jwpcdn.com^$script,third-party` - to "My filters" it works properly, but if it is only in [Easylist](https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L4829) it is blocked.

**Comment by gorhill** [comment]
Is that site supposed to work with Firefox?

**Comment by F4z** [comment]
In Firefox with uBO 1.9.8 is the same problem, but when I add `@@||p.jwpcdn.com^$script,third-party` to "My filters" it works properly.

**Comment by gorhill** [comment]
I mean with whatever version of uBO, 1.9.4, 1.9.8, 1.9.10, I do not see requests for scripts from `p.jwpcdn.com` when using Firefox/Nightly.

**Comment by F4z** [comment]
Firefox 49.01 and I see this.
![1](https://cloud.githubusercontent.com/assets/11742596/18811516/7fa7e7c4-82b2-11e6-9385-90ae7356cde0.JPG)

**Comment by gorhill** [comment]
Ok never mind, I did not realize the site needed Flash, it was disabled on my side.

**Comment by F4z** [comment]
Ok, no problem, thank you for fix.
