### ISSUE TITLE
Unable to hide cookie notice

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#2026]
From the website: (See the cookie notice at the bottom)

`http://alfahir.hu/`

In the Annoyances and cookies list I have **###sliding-popup.sliding-popup-bottom** which works fine in Adblock Plus but not in uBlock-Origin.

**Comment by ryanbr** [comment]
Ah yes, Parse and enforce cosmetic filters wasnt enabled, seems to be fine. Given most filters are developed with ADB wouldn't it be a good idea to make it default?

**Comment by gorhill** [comment]
_"Parse and enforce cosmetic filters"_ _is_ default.
