### ISSUE TITLE
Adding checksums/signatures to github.com/gorhill/uBlock/releases ?

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uBlock#2027]
Have you considered adding SHA checksums , or (even better) signatures to the downloads page https://github.com/gorhill/uBlock/releases ?

Unless I missed something, I can't find any way to verify the .xpi files on that page : I realize that this may be yet another chore for you, but in light of what recently happened to the official Mozilla server (vulnerabilty to MITM intrusion), people may eventually want to download extensions from somewhere else, if nothing to double-check an extension.

I don't know if this is feasible for you, but having signed hashes of the .xpi files or (alternatively) having detached signatures for them, would IMO increase security (within the limits of the public key scheme, but still better than nothing..).
Thanks.

**Comment by acrobat1** [comment]
BTW, I've also noted that sha256sums between here (github) and AMO don't match: for instance, I'm getting different values for this https://github.com/gorhill/uBlock/releases/download/1.9.10/uBlock0.firefox.xpi vs. this one https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/1.9.10 - aren't they supposedly the same version?

Does Mozilla change something once an extension is uploaded on AMO, due to their signing process?

**Comment by gorhill** [comment]
> Does Mozilla change something once an extension is uploaded on AMO, due to their signing process?

Yes.

**Comment by quilloss** [comment]
Mozilla adds a META-INF folder to the xpi that contains the signature and hash of files. If you are worried that you have been MITM, can't you just check that the extension id has not been changed or that the extension signing is valid.

**Comment by gorhill** [comment]
I used to provide signatures, but it's a tedious, time consuming step I rather avoid. Someone looked into having the signatures created by the build, and [there were issues](https://github.com/chrisaljoudi/uBlock/pull/521).

**Comment by rugk** [comment]
I'd also say adding checksums (but use SHA-256 as SHA-1 should not be used anymore) is a very nice idea. Alternatively/Additionally you could also [sign your git tags and the releases](https://github.com/gorhill/uBlock/issues/2079).

**Comment by DrunkenSasquatch** [comment]
@gorhill 
> I used to provide signatures (valid for the versions released on GitHub), but it's a tedious, time consuming step I rather avoid.

Well if you're developing on Windows, the free version of [HashTab](http://implbits.com/products/hashtab/) is a life saver. It's essentially integrated into the Operating System. Just right click any file and choose your algorithm.

**Comment by Snapy** [comment]
@gorhill The issue can be closed since you're doing it since some time.

**Comment by gorhill** [comment]
@Snapy The request here is for me to provide signatures for the binaries.

But I won't go back to manually build and publish the binaries, this is too much time consuming. So I will close this issue instead of letting it linger without ever resolving it. Whoever does not trust the binaries put in there by Travis build process, I suggest you locally simply clone the repo and build your own binaries.
