### ISSUE TITLE
IGN links not working

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#203]
Any link in www.ign.com don't work. I have to open them with right mouse "Open link in new tab".

Browser: Chrome Version 42.0.2311.152 m (64-bit)
uBlock 0.9.7.0 Default Settings
Windows 8.1 Pro 64bits
No other extensions

**Comment by gorhill** [comment]
Can't reproduce using default settings.

**Comment by gorhill** [comment]
Closing due to no feedback. Anyway, certainly a 3rd-party filter list issue.
