### ISSUE TITLE
adavanced ublock ui false report

### ISSUE THREAD

**Issue by androidland** [gorhill/uBlock#2030]
### Describe the issue

ublock ui report wrong 

### One or more specific URLs where the issue occurs

any

### Screenshot in which the issue can be seen

![fsfsdfsdf2 - copy](https://cloud.githubusercontent.com/assets/9499540/18821912/a27cb536-83d4-11e6-8af1-85b5b571b627.jpg)

### Steps for anyone to reproduce the issue

1.  create new tab
2.  open any site for example cnn.com
3.  then open github.com from the same tab
4.  ublock stil report cnn.com site

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- FF 49.01
- uBlock Origin version:  1.9.11.rc0

##### Your filter lists

 "Default filter lists + https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt
https://easylist-downloads.adblockplus.org/yt_annoyances_other.txt

sorry for my bad language

**Comment by gorhill** [comment]
Unable to reproduce.

Did you try restarting Firefox after updating to 1.9.11rc0?

**Comment by androidland** [comment]
i have restarting
back to ublock 1.9.10, there no problem

**Comment by gorhill** [comment]
Ok, I reproduce.

**Comment by androidland** [comment]
ok its fixed, thanks for quick repsonse
