### ISSUE TITLE
data: urls are not blocked if opened in the same tab

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#2031]
**Issue**

data: urls are not blocked if opened in the same tab

**URL**

http://www-archive.mozilla.org/quality/networking/testing/datatests.html

**Screenshot**

http://i.imgur.com/FVAIw0u.jpg

**Steps To Reproduce**

1.) Browse to http://www-archive.mozilla.org/quality/networking/testing/datatests.html

2). click on URL named - "Larry" image"

3). The data URL will open up in the same tab and won't be blocked by uBO.

**Settings**
- Browser/version: Chromium 55
- uBlock Origin version: 1.9.10

**Filter Lists**

Default + |data:$first-party 
That filter has no effect and uBlock simply ignores it.

**Custom Filters (if any)**

None

**Comment by gorhill** [comment]
The webRequest API does not relay `data:` URI to its listeners -- and there is no such API to deal with the blocking of `data:` URI.

**Comment by rjkpa** [comment]
So data urls in same tab cannot be blocked ? Is that it ?

**Comment by gorhill** [comment]
> So data urls in same tab cannot be blocked ? Is that it ?

Yes, that's it. `data:` URIs are inlined resources, they already loaded in your browser by the time uBO can act on them. It's true for Chromium/Firefox, though for Firefox there could be a solution, I would need to investigate.

**Comment by rjkpa** [comment]
Alright then. Let me know if you find a solution for Firefox, it's good that uBO can block data urls as popups though, thanks.

**Comment by gorhill** [comment]
Why is this re-opened?

**Comment by rjkpa** [comment]
Because as you said you will investigate regarding a possible way for Firefox, so I opened it again as you will do something about it if it's open. I'm keeping it opened for that, however if you feel as there's nothing you can do about it, close it at your own discretion.

**Comment by gorhill** [comment]
> Because as you said you will investigate regarding a possible way for Firefox

I said _I would need_ investigate, not _I will investigate_.

Given that the Firefox version is moving toward WebExtensions, I won't investigate -- i.e. I declined.

**Comment by rjkpa** [comment]
Yeah okay, so is Mozilla going to add some new APIs for data urls and provide more support ?
