### ISSUE TITLE
Suggestions/Request

### ISSUE THREAD

**Issue by mikhoul** [gorhill/uBlock#2032]
Hi @gorhill , 

Could you add the same option as you put for the logger (http://tinyurl.com/j743ddg) to _Settings/Options_ button in the main panel ?

For the same reason I use it a lot the filter windows to debug when I work with **XPATH** filter and other advanced filters, it would be wonderful if the _settings/options/filter page_ would open in their own window :octocat:

Have a Great Day !   :smile:

**Comment by gorhill** [comment]
> I use it a lot the filter windows to debug when I work with XPATH filter and other advanced filters

Would fixing issue #1772 address this? being able to visual see and preview `:xpath` and other procedural filters would prevent you needing to use the _My filters_ pane for testing these filters.

**Comment by mikhoul** [comment]
Both would be **REALLY** useful  :+1: 

Why I say both ? It's because lot of time when I debug website that detect ad blocker I use the _dashboard_ to see an "overall" of which filters I had applied before going further with new filters. Lot of time I apply them and customize them from the _logge_r and after I use the dashboard to follow them .

In fact the best thing IMO (but a little bit more complicated maybe) would be to have an option to open the logger and the _dashboard_ in their "own" windows with 2 tabs. It would speed the the loading since the Browser interface would not be  loaded each time I call the _logger_ or the _dashboard_.

I use lot of scripts and add-on so every time I open a new Firefox window  it take 4-6 second before the window appear, it's annoying.

When I say _"their own window_" it is the same type of Windows that some other addon use like the "Dom Inspector", they are very responsive and fast. 

Take a look here, this this kind of window:

![Image of Yaktocat](http://i.imgur.com/Zu6WSDh.png)


**Best Regards !**

**Comment by mikhoul** [comment]
What happen @gorhill  ? Do you have any commit for this issue ? 

Best Regards 😊

**Comment by anewuser** [comment]
@mikhoul  Changes to open source software are released when/if the developers have time and want to implement them. Be patient and wait silently.

**Comment by mikhoul** [comment]
@anewuser  I develop lot of freeware and when somebody ask me for a feature, question or help I **always** answer, it's not because something is free that you can't ask features or improvement.

**Each week** I take the time to answer to every user that take the time to ask me a question, we just call it respect from where I come. :v: 

So I don't know who you are to tell me " _wait silently_" but one thing is sure you must have a **Big Big EGO** to think "you are the one who knows how it work..."  :alien:

**Comment by mikhoul** [comment]
Thanks a lot @gorhill for the new release I've just installed 1.9.13b0 and will test it with procedural filters on some tricky websites that require more complex filters.

Up to know it with :HAS I replaced for me some userscripts with filters only to block elements.

**Have a good Week-End !** :smile:
