### ISSUE TITLE
Can't block a certain domain with directory ( but ABP, TamperMonkey, uMatrix and uBlock all have this issue )

### ISSUE THREAD

**Issue by Acecool** [gorhill/uBlock#2038]
### Describe the issue
uBlock, AdblockPlus, TamperMonkey and uMatrix have an issue where the url isn't detected; likely when using .htaccess / permanent or temp redirects but this isn't confirmed. I can't open the page using notepad to view-source and trying to view-source in chrome doesn't yield any results either ( likely why the url isn't being detected by uBlock ).

Note, if you go the the below url add this to your blocked list: 

uMatrix has prevented the following page from loading:
https://onclickads.net/afu.php?var=11645&zoneid=429717

### One or more specific URLs where the issue occurs
thevideo.me/mpaabpu/redir - uses https
thevideo.me/mpaabpu/mttc - uses https

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
Not necessary because it is a blank page which redirects; I can't seem to read the source by opening the page in notepad, etc... so it is likely a .htaccess permanent redirect or something but the url should still trigger the block...

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chrome Version 53.0.2785.116 m (64-bit)
- uBlock version: 0.9.5.0

##### Your filter lists
145,326 network filters ＋ 61,615 cosmetic filters from:

  My filters‎ : 33 used out of 53
 uBlock filters‎ : 136 used out of 137purge cache
 uBlock filters – Privacy‎ : 2 used out of 3
Ads (5)
 Adblock Warning Removal List‎ : 239 used out of 255purge cache
 Anti-Adblock Killer | Reek‎  (raw.githubusercontent.com): 2,099 used out of 2,183purge cache
 EasyList‎  (adblockplus.org): 4 used out of 84,714purge cache
 EasyList without element hiding rules‎  (adblockplus.org): 0 used out of 43,977purge cache
 Peter Lowe’s Ad server list‎ (yoyo.org): 1,525 used out of 2,369purge cache
Privacy (2)
 EasyPrivacy‎  (adblockplus.org): 5 used out of 12,546purge cache
 Fanboy's Enhanced Tracking List‎  (fanboy.co.nz): 0 used out of 1,390purge cache
Malware domains (4)
 Malware Domain List‎ (malwaredomainlist.com): 1,251 used out of 1,251purge cache
 Malware domains‎ : 9,370 used out of 9,448purge cache
 Malware domains (long-lived)‎ : 1 used out of 4,019purge cache
 Spam404‎ (spam404bl.com): 5,327 used out of 5,335purge cache
Multipurpose (4)
 Dan Pollock’s hosts file‎ (someonewhocares.org): 10,128 used out of 12,171purge cache
 Fanboy+Easylist-Merged Ultimate List‎  (fanboy.co.nz): 122,860 used out of 122,937purge cache
 hpHosts’s Ad and tracking servers‎ (hosts-file.net): 41,092 used out of 47,853purge cache
 MVPS HOSTS‎ (mvps.org): 12,869 used out of 13,266purge cache

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
||thevideo.me/mpaabpu/redir
||thevideo.me/mpaabpu/mttc
||thevideo.me/mpaabpu/

Each of those are added ( and by default no wildcard means it looks for wildcard; 2 pipes checks for http(s)?://(www)? ) but they aren't blocked. In all fairness, uBlock doesn't seem to work with them either, and tampermonkey doesn't seem to detect it ( wrote something to close tabs with that address and it doesn't execute ) and uMatrix doesn't detect directories...

**Comment by Acecool** [comment]
Update: Actually, view-source: is working now

/redir/
```
<script>
window.location.href = "https://onclickads.net/afu.php?var=11645&zoneid=429717";
//window.location.replace( "https://thevideo.me/rm/aHR0cHM6Ly9vbmNsaWNrYWRzLm5ldC9hZnUucGhwP3Zhcj0xMTY0NSZ6b25laWQ9NDI5NzE3" );
//window.location.href = "http://onclickads.net/afu.php?zoneid=429461&var=645";
</script>
```


/mttc/

```
<script>
//window.location.href = "http://cdn.adsrvmedia.net/adsrvmedia/scripts/direct/direct.html?a=70510504&serverdomain=ads.adsrvmedia.net&context=c70510508&size=1024x768&rt=popunder&ci=10&cb="+Math.random();
window.location.href = "https://www.terraclicks.com/watch?key=5adb382f90c2bd927e3d32829c6c397d";
//window.location.href = "http://ouo.io/51jsK";
//window.location.href = "https://d.castplatform.com/api/pup/1?aus=6055";
</script>
```

**Comment by gorhill** [comment]
> uBlock version: 0.9.5.0

You are on the wrong repo, this is not uBlock here, it's uBlock Origin.

**Comment by Acecool** [comment]
Is uBlock Origin affected by this bug?

**Comment by gorhill** [comment]
I did not really understand the issue you reported. When I tested with uBO, sctrict blocking kicked in, and from there it's up to the user to choose what to do:

![a](https://cloud.githubusercontent.com/assets/585534/18969802/a713bd12-865c-11e6-9113-112bdec97d51.png)

**Comment by lewisje** [comment]
Originally, uBlock did in fact block with a blank page; this is also how urlfilter.ini worked in old Opera.
