### ISSUE TITLE
UBO not working at all on Chrome for some Torrent sites?

### ISSUE THREAD

**Issue by UBOInformer** [gorhill/uBlock#2039]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Pops out new tab to "go.letadnew.com" and redirects to random ad sites

### One or more specific URLs where the issue occurs

http://kickass.cd/full/ or https://kickass.skillproxy.org/full/

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

No Need (Solution provided "Just add it")

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Visit http://kickass.cd/full/ or https://kickass.skillproxy.org/full/
2. Click on any comment bubble before opening link and ads pop out
3. The solution below fixes the ad problem. (Thank me later)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differ from default settings]

- Browser/version: Chrome Version 53.0.2785.116 m (64-bit) (Update available will do after sending this)
- uBlock Origin version: v1.9.10

##### Your filter lists

Default +  Anti-Adblock Killer | Reek

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

||letadnew.com^
||whiteboardnez.com^
||go.*.com$script,domain=kickass.cd
||tostickad.com^
||markergot.com^

##### If you have a fix (please provide it)

Add the following to "My Filters" tab

|http://$script,third-party,domain=kickass.cd
|https://$script,third-party,domain=kickass.cd
@@||ajax.googleapis.com/ajax/libs/$script,domain=kickass.cd

**if it's about popups, add the following filters** (I only use these)
||letadnew.com^
||whiteboardnez.com^
||go.*.com$script,domain=kickass.cd
||tostickad.com^
||markergot.com^

##### Message for gorhill

I have provided you with enough information and the solution to fix this issue
Please add or request above solutions for 3rd party update filters in UBO

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
