### ISSUE TITLE
Problems using a dark Desktop Theme

### ISSUE THREAD

**Issue by maycontainnuts** [gorhill/uBlock#204]
Browser: FF38
uBlock: 0.9.7.0

Firefox uses GTK+ on Linux. Color-settings by used GTK-Theme will affect rendering of browser content too. Current setup for textarea in dyna-rules.css could result in an unusable  editor window [http://i.imgur.com/qOIVHXi.png].
- Not setting (light) textarea/background-color will solve that problem, (dark) GTK+ background-color will be used. 
- Problem should also be solved by adding a dark text-color instead.

**Comment by gorhill** [comment]
You have a link for that dark desktop theme?

**Comment by gorhill** [comment]
Ok I see, it's a OS theme, not a Firefox one.

**Comment by gorhill** [comment]
Here is the thing, I can't fix if I can't test the result of code change. I am running Linux Mint. What is the fastest way for me to test this -- just trying to save much time here.

**Comment by maycontainnuts** [comment]
U should be able to change the Desktop Theme by using a "Settings Manager" or "Control Center".

**Comment by gorhill** [comment]
Yes, went there but it looks like my Firefox is not using the desktop theme. Is there a special flag for this in Firefox?

**Comment by gorhill** [comment]
I will push a dev build, tell me if this fixes your issue.

**Comment by maycontainnuts** [comment]
Dev build won't fix the problem. Textarea in dynamic rules tab is still white on white in edit mode. Could you plz add "color: black;" to #diff textarea in /src/css/dyna-rules.css. It will solve that problem.

**Comment by gorhill** [comment]
Any other textareas which also need to be revisited?

**Comment by maycontainnuts** [comment]
As far as i can see the other textareas receive color settings from OS theme only [http://imgur.com/tsWb4HCl.png].

**Comment by MineyMe** [comment]
Just wanted to pitch in and say that the OP is using a GTK3 build of Firefox (Firefox still uses GTK2 by default in pretty much all distro's as the GTK3 port is still in progress). GNOME provides a dark variant of the Aidwata theme that can be toggled in the tweak tool, which is in a way a GTK3 theme, causing all GTK3 apps (i.e. most importantly GNOME's own apps) to become dark, this theme however does not apply to GTK2 (perhaps there are themes in Mint/Cinnamon however that do).

As you can see however, the darkened default Firefox theme doesn't look that great, I'm not sure this is something you would want to fix right now; it all depends on your perspective, you could enforce background and foreground colors on all elements to enforce a consistent style everywhere (like many websites do) or you could leave it as it is now, where it defaults to the colors from the system. Perhaps Mozilla will even disable the dark theme for the GTK3 build of Firefox or hide it behind a setting in time (it can be enabled or disabled by the application proper).
