### ISSUE TITLE
Logger drop-down menu sort order

### ISSUE THREAD

**Issue by teschmitz** [gorhill/uBlock#2041]
I use both uBlock and uMatrix and I notice the sort order of drop-down menu at the top is alphabetical for uBlock and in tab order for uMatrix.

I know the two add-ons are not necessarily meant to be used in tandem but when you do use both it is a wee bit confusing. Otherwise I find either sort order is fine.

Thanks for these great add-ons!

**Comment by Atavic** [comment]
That's the specific design of both, as one has filter lists which are listed alphabetically (how could be listed otherwise?) while the other has net requests listed by type.

**Comment by gorhill** [comment]
On closer inspection (I went through that code a long time ago), the fact that uMatrix respects tab order is just luck -- there is no code in uMatrix caring about tab order.  The tab order is actually undefined. So the actual fix is to make uMatrix behaves as uBO, sort the entry on tab title.
