### ISSUE TITLE
Some links don't work anymore when ublock is enabled

### ISSUE THREAD

**Issue by julienw** [gorhill/uBlock#2044]
### Describe the issue
Some links don't work anymore when ublock is enabled

### One or more specific URLs where the issue occurs
http://abonnes.lemonde.fr/syrie/article/2016/10/03/syrie-le-plus-grand-hopital-d-alep-detruit-par-des-raids-aeriens_5007545_1618247.html

### Screenshot in which the issue can be seen

The issue is a behavior issue so no screenshot needed.

### Steps for anyone to reproduce the issue

0. Check that ublock is enabled.
1. Go to http://abonnes.lemonde.fr/syrie/article/2016/10/03/syrie-le-plus-grand-hopital-d-alep-detruit-par-des-raids-aeriens_5007545_1618247.html
2. Click on one of the links "Lire aussi"

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 51 but I also got a report for Firefox 47
- uBlock Origin version: 1.9.12

##### Your filter lists

I'm not sure because my Firefox doesn't want to display the preference. It's likely Defaut + France.

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets.
> 
> Ignorance of the above rules is no excuse: Opening an issue for purpose of support or discussion, or opening a filter-related issue will result in the user being immediately blocked. Given the amount of invalid issues being opened, I have no choice but to resort to such a drastic measure.
