### ISSUE TITLE
IBTimes blocking uBlock

### ISSUE THREAD

**Issue by zauberparacelsus** [gorhill/uBlock#2045]
### Describe the issue
The website for the International Business Times is detected uBlock and preventing you from reading the articles by serving up a blurred out version of the text.

### One or more specific URLs where the issue occurs
http://www.ibtimes.co.uk/former-yahoo-executive-says-3bn-user-accounts-could-have-stolen-by-hackers-1584573
http://www.ibtimes.co.uk/kim-dotcom-hopes-megaupload-2-0-will-bring-micropayments-blockchain-masses-1584540

### Screenshot in which the issue can be seen
https://gyazo.com/47f18ccc9851e5a0f7b3610687c303cf

### Your settings

Default Settings

- Browser/version: Chromium 52.0.2743.116 
- uBlock Origin version: 1.9.10

##### Your filter lists
- uBlock Filters (+badware, privacy, unbreak)
- EasyList
- Peter Lowe's Ad server list
- Malware domain list
- Malware domains

**Comment by Atavic** [comment]
_#adbk-user-alert_: http://g.ibtimes.co.uk/sys/js/08b78faf623f3bb03b7ee0d17974d5c3.js

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
