### ISSUE TITLE
Update filter lists issue

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2049]
When I click "Purge all caches" or "purge cache" for some filter it shows me new version available for some filters (EasyList, uBlock filters, Peter) even though I just recently updated. 
I don't think these filters are being updated that fast and though I updated the filters recently it shows new version available for the above mentioned lists.

**How to reproduce?**
Update filter lists then click purge cache you should get new version available for the above filters (if you have them).
 
**Screencapture:**  https://vid.me/JS6f

**Steps taken to resolve issue?**
Reinstalled uBlock, then reinstalled Chrome, disabled all other extensions.

uBlock: 1.9.10, Chrome: 53

**Comment by Hrxn** [comment]
Well, looks like it's working like intended, I'd say.

*Purge cache* means purging your filter lists here..

**Comment by gotitbro** [comment]
> Well, looks like it's working as intended, I'd say.
> Purgecache means purging your filter lists here..
So, purge here means deleting the new filter list cache and replacing it with the one that came with uBlock?

**Comment by gorhill** [comment]
Read the doc please.
