### ISSUE TITLE
Installing from github

### ISSUE THREAD

**Issue by a4art** [gorhill/uBlock#205]
Hey,

I am trying to install the latest release of ublock origin through github. When I click the .firefoxe.xpi file firefox asks permission to download the file but when the download is (about to) complete I get an error message saying the connection to github failed and the file could not be downloaded.

I guess I have to tell firefox to allow github to install the add-on but I'm not sure how...

Thanks in advance

**Comment by gorhill** [comment]
Don't click on the xpi, right-click then select "Save link as...". Once it is downloaded, drag the file to Firefox.
