### ISSUE TITLE
Help blocking something on steam

### ISSUE THREAD

**Issue by shogunreaper** [gorhill/uBlock#2052]
Is it possible to block the community content message on steam with ublock?

this is what it loads on every page

var $Content = $J('<div/>');
			$Content.append( $Header );
			$Content.append( "<div class=\"adult_content_age_gate\">\r\n\t\t\t<img class=\"adult_content_age_gate_header\" src=\"http:\/\/cdn.akamai.steamstatic.com\/steam\/apps\/360430\/header.jpg?t=1475772854\">\r\n\t\t<p>Community content for this product may not be appropriate for all ages, or may not be appropriate for viewing at work.<\/p>\r\n\t<div class=\"adult_content_age_gate_buttons\">\r\n\t\t<div class=\"btn_grey_white_innerfade btn_medium\" id=\"age_gate_btn_cancel\">\r\n\t\t\t<span>Cancel<\/span>\r\n\t\t<\/div>\r\n\t\t&nbsp;\r\n\t\t<div class=\"btn_grey_white_innerfade btn_medium\" id=\"age_gate_btn_continue\">\r\n\t\t\t<span>Continue<\/span>\r\n\t\t<\/div>\r\n\t<\/div>\r\n<\/div>\r\n" );

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
