### ISSUE TITLE
I can't make a global uBlock cosmetic filter?

### ISSUE THREAD

**Issue by Accelyte** [gorhill/uBlock#2054]
I am currently using the TouchVPN extension by northghost on Chrome, and there's a floating icon that I would love to get rid of but there aren't any settings to turn it off, so I decided to use uBlock to block it. I picked its cosmetic element on a page (e.g. example.com###_af_1475875145459_hss_status_icon) but obviously it's only blocked for example.com. The floating icon appeared on all pages, so I wondered if there was a global URL for cosmetic filters.
I tried different methods:
*.*###_af_1475875145459_hss_status_icon
*###_af_1475875145459_hss_status_icon
http://*###_af_1475875145459_hss_status_icon
Is this option not allowed or am I missing something?

Your settings
http://imgur.com/a/aceaz
- Browser/version: Chrome 53.0.2785.143 m (64-bit)
- uBlock Origin version: v1.9.10

##### Your filter lists
http://imgur.com/a/5j54s

##### Your custom filters (if any)
http://pastebin.com/7DD0XyUw

**Comment by lewisje** [comment]
Does the button have the specific ID `_af_1475875145459_hss_status_icon`? Those numbers look like they're random, in which case you might prefer the following filter rule:

    ##[id^="_af_"][id$="_hss_status_icon"]

**Comment by gorhill** [comment]
Go into your _My filter_ pane and edit your filter to remove the hostname prefix.

**Comment by gorhill** [comment]
> Those numbers look like they're random

Yes, `1475875145459` looks like unix timestamp.

**Comment by Accelyte** [comment]
@lewisje thanks for the answer, it worked for me :) 
@gorhill yeah the number string changed when I was trying to filter it again, that's why removing the hostname prefix didn't work.
