### ISSUE TITLE
Hide unnecessary browser elements from logger popup

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#2055]
Like in title. I find location bar, bookmarks and other panels not useful when opening logger popup. I personally use

`location=0,menubar=0,status=0,personalbar=0,resizable=1,toolbar=0,width=1280,height=720` https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L1016

What do you think? Just plain logger with window titlebar. I also think it is good to set initial size, but not sure what would be fine for all.

**Comment by gorhill** [comment]
It used to be like this, I changed it a long time ago: <https://github.com/gorhill/uBlock/commit/180856bd0dc68fbf2c72a1cc4deb34f96fa32c3f>.

I believe the change took care of this issue: <https://github.com/gorhill/uBlock/issues/429>.

I ratehr not revert my change.
