### ISSUE TITLE
It takes a few hours after newly installed local uBlock

### ISSUE THREAD

**Issue by mizhang** [gorhill/uBlock#2057]
I am trying to instsasll uBlock for chrome from the local project since a few days back.  Every time, it didn't work right after installation; however only a few hours after the installation, ublock would start to work.  This has happened 2/2 times since I tried.  

Any URL has this problem, just i.e., daily mail online: http://www.dailymail.co.uk/ushome/index.html.

<img width="1355" alt="screen shot 2016-10-08 at 1 56 26 am" src="https://cloud.githubusercontent.com/assets/2915786/19211151/80b81c08-8cfb-11e6-8c5c-c7789a0896d4.png">

### Steps for anyone to reproduce the issue

1. chrome://extension, 
2. load unpacked extension -> select the folder of local uBlock.
3. go to a website like daily mail;  ads are NOT blocked.
4. wait usually after 10 PM the same day, go to daily mail; Ads ARE blocked. 

### Your settings
- Browser/version:     chrome/53.0.2785.143 (64-bit)
- uBlock Origin version:  1.9.5.1

##### Your filter lists

Default filter lists
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
No

**Comment by gorhill** [comment]
Unable to reproduce.

Where did you get that 1.9.5.1 version? It's no longer available since a month.

> I am trying to instsasll uBlock for chrome from the local project

That is probably your issue, install an official release please.

**Comment by mizhang** [comment]
I downloaded the version 1.9.14.  Still the same issue, not working after immediate install, but needs to wait.

**Comment by mizhang** [comment]
Raymond,
2057 is not resolved yet.  I downloaded the newest version, 1.9.14.  Still the
same issue, can you help me on this?
thanks,

miya
 





On Sat, Oct 8, 2016 5:52 AM, Raymond Hill notifications@github.com
wrote:
Closed #2057.

**Comment by gorhill** [comment]
> can you help me on this?

There is something specific on your side causing this. The filter lists are shipped with the extension, and your symptoms are as if you do not have any filter lists in your package. See if your anti-virus is interfering. Look in the extension console for errors.

**Comment by mizhang** [comment]
I can find the filter list at : chrome-extension://[extension-id]/assets/....   Filter file is also found at local folder.

Still having the same problem. Seems that the new install only starts to work after around 9 or 10 pm center time.

I can't do any programming with such a long delay of installation. 

Can someone help me in debugging steps?

**Comment by mizhang** [comment]
Here is my filter file:

{
	"http://adblock.gardar.net/is.abp.txt": {
		"off": true,
		"title": "ISL: Icelandic ABP List",
		"group": "regions",
		"lang": "is",
		"supportURL": "http://adblock.gardar.net/"
	},
	"https://adblock.dk/block.csv": {
		"off": true,
		"title": "DNK: Schacks Adblock Plus liste",
		"group": "regions",
		"lang": "da",
		"supportURL": "https://henrik.schack.dk/adblock/"
	},
	"https://dl.dropboxusercontent.com/u/1289327/abpxfiles/filtri.txt": {
		"off": true,
		"title": "ITA: ABP X Files",
		"group": "regions",
		"supportURL": "http://noads.it/"
	},
	"https://adguard.com/en/filter-rules.html?id=1": {
		"off": true,
		"title": "RUS: Adguard Russian Filter",
		"group": "regions",
		"supportURL": "http://forum.adguard.com/forumdisplay.php?69-%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D1%8B-Adguard"
	},
	"https://easylist-downloads.adblockplus.org/advblock.txt": {
		"off": true,
		"title": "RUS: RU AdList (Ð”Ð¾Ð¿Ð¾Ð»Ð½Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ð°Ñ Ñ€ÐµÐ³Ð¸Ð¾Ð½Ð°Ð»ÑŒÐ½Ð°Ñ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐºÐ°)",
		"group": "regions",
		"lang": "ru",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=102"
	},
	"https://easylist-downloads.adblockplus.org/bitblock.txt": {
		"off": true,
		"title": "RUS: BitBlock List (Ð”Ð¾Ð¿Ð¾Ð»Ð½Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ð°Ñ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐºÐ° Ñ„Ð¸Ð»ÑŒÑ‚Ñ€Ð¾Ð²)",
		"group": "regions",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=102"
	},
	"easylist-downloads.adblockplus.org/easylist.txt": {
		"title": "EasyList",
		"group": "ads",
		"homeURL": "https://easylist.to/easylist/easylist.txt",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt": {
		"off": true,
		"title": "EasyList without element hiding rules",
		"group": "ads",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://easylist-downloads.adblockplus.org/easylistchina.txt": {
		"off": true,
		"title": "CHN: EasyList China (ä¸­æ–‡)",
		"group": "regions",
		"lang": "zh",
		"supportURL": "http://abpchina.org/forum/forum.php"
	},
	"https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt": {
		"off": true,
		"title": "CHN: CJX's EasyList Lite (main focus on Chinese sites)",
		"group": "regions",
		"supportURL": "https://github.com/cjx82630/cjxlist"
	},
	"https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt": {
		"off": true,
		"title": "CHN: CJX's Annoyance List",
		"group": "regions",
		"supportURL": "https://github.com/cjx82630/cjxlist"
	},
	"https://easylist-downloads.adblockplus.org/easylistdutch.txt": {
		"off": true,
		"title": "NLD: EasyList Dutch",
		"group": "regions",
		"lang": "nl",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=100"
	},
	"https://easylist-downloads.adblockplus.org/easylistgermany.txt": {
		"off": true,
		"title": "DEU: EasyList Germany",
		"group": "regions",
		"lang": "de",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=90"
	},
	"https://easylist-downloads.adblockplus.org/easylistitaly.txt": {
		"off": true,
		"title": "ITA: EasyList Italy",
		"group": "regions",
		"lang": "it",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=96"
	},
	"easylist-downloads.adblockplus.org/easyprivacy.txt": {
		"title": "EasyPrivacy",
		"group": "privacy",
		"homeURL": "https://easylist.to/easylist/easyprivacy.txt",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt": {
		"off": true,
		"title": "Fanboyâ€™s Annoyance List",
		"group": "social",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://easylist-downloads.adblockplus.org/fanboy-social.txt": {
		"off": true,
		"title": "Fanboyâ€™s Social Blocking List",
		"group": "social",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://easylist-downloads.adblockplus.org/liste_fr.txt": {
		"off": true,
		"title": "FRA: EasyList Liste FR",
		"group": "regions",
		"lang": "fr",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=91"
	},
	"https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt": {
		"off": true,
		"title": "LVA: Latvian List",
		"group": "regions",
		"lang": "lv",
		"supportURL": "https://notabug.org/latvian-list/adblock-latvian"
	},
	"http://hosts-file.net/.%5Cad_servers.txt": {
		"off": true,
		"title": "hpHostsâ€™ Ad and tracking servers",
		"group": "multipurpose",
		"supportURL": "http://hosts-file.net/"
	},
	"http://adblock.ee/list.php": {
		"off": true,
		"title": "EST: Eesti saitidele kohandatud filter",
		"group": "regions",
		"lang": "et",
		"supportURL": "http://adblock.ee/"
	},
	"https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt": {
		"off": true,
		"title": "Malvertising filter list by Disconnect",
		"group": "malware"
	},
	"https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt": {
		"off": true,
		"title": "Malware filter list by Disconnect",
		"group": "malware"
	},
	"https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt": {
		"off": true,
		"title": "Basic tracking list by Disconnect",
		"group": "privacy"
	},
	"https://www.certyficate.it/adblock/adblock.txt": {
		"off": true,
		"title": "POL: polskie filtry do Adblocka i uBlocka",
		"group": "regions",
		"lang": "pl",
		"supportURL": "http://www.certyficate.it/adblock-ublock-polish-filters/"
	},
	"https://easylist-downloads.adblockplus.org/antiadblockfilters.txt": {
		"off": true,
		"title": "Adblock Warning Removal List",
		"group": "ads",
		"supportURL": "https://forums.lanik.us/"
	},
	"http://adb.juvander.net/Finland_adb.txt": {
		"off": true,
		"title": "FIN: Finnish Addition to Easylist",
		"group": "regions",
		"lang": "fi",
		"supportURL": "http://www.juvander.fi/AdblockFinland"
	},
	"https://raw.githubusercontent.com/gfmaster/adblock-korea-contrib/master/filter.txt": {
		"off": true,
		"title": "KOR: Korean Adblock List",
		"group": "regions",
		"lang": "ko",
		"supportURL": "https://github.com/gfmaster/adblock-korea-contrib"
	},
	"https://raw.githubusercontent.com/heradhis/indonesianadblockrules/master/subscriptions/abpindo.txt": {
		"off": true,
		"title": "IDN: ABPindo",
		"group": "regions",
		"lang": "id",
		"supportURL": "https://github.com/heradhis/indonesianadblockrules"
	},
	"https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt": {
		"off": true,
		"title": "JPN: ABP Japanese filters (æ—¥æœ¬ç”¨ãƒ•ã‚£ãƒ«ã‚¿)",
		"group": "regions",
		"lang": "ja",
		"supportURL": "https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy"
	},
	"https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt": {
		"off": true,
		"title": "EU: Prebake - Filter Obtrusive Cookie Notices",
		"group": "regions",
		"supportURL": "https://github.com/liamja/Prebake"
	},
	"https://raw.githubusercontent.com/yous/YousList/master/youslist.txt": {
		"off": true,
		"title": "KOR: YousList",
		"group": "regions",
		"lang": "ko",
		"supportURL": "https://github.com/yous/YousList"
	},
	"https://easylist-downloads.adblockplus.org/Liste_AR.txt": {
		"off": true,
		"title": "ara: Liste AR",
		"group": "regions",
		"lang": "ar",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=98"
	},
	"http://margevicius.lt/easylistlithuania.txt": {
		"off": true,
		"title": "LTU: Adblock Plus Lithuania",
		"group": "regions",
		"lang": "lt",
		"supportURL": "http://margevicius.lt/easylist_lithuania/"
	},
	"http://malwaredomains.lehigh.edu/files/immortal_domains.txt": {
		"off": true,
		"title": "Malware domains (long-lived)",
		"group": "malware",
		"supportURL": "http://www.malwaredomains.com/"
	},
	"mirror1.malwaredomains.com/files/justdomains": {
		"title": "Malware domains",
		"group": "malware",
		"homeURL": "https://mirror.cedia.org.ec/malwaredomains/justdomains",
		"supportURL": "http://www.malwaredomains.com/"
	},
	"pgl.yoyo.org/as/serverlist": {
		"title": "Peter Loweâ€™s Ad server list",
		"group": "ads",
		"homeURL": "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext",
		"supportURL": "https://pgl.yoyo.org/adservers/"
	},
	"https://raw.githubusercontent.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt": {
		"off": true,
		"title": "ISR: EasyList Hebrew (obsolete, will be removed soon)",
		"group": "regions",
		"supportURL": "https://github.com/AdBlockPlusIsrael/EasyListHebrew"
	},
	"https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt": {
		"off": true,
		"title": "ISR: EasyList Hebrew",
		"group": "regions",
		"lang": "he",
		"supportURL": "https://github.com/easylist/EasyListHebrew"
	},
	"https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
		"off": true,
		"title": "Anti-Adblock Killer | Reek",
		"group": "ads",
		"supportURL": "https://github.com/reek/anti-adblock-killer",
		"instructionURL": "https://github.com/reek/anti-adblock-killer#instruction"
	},
	"https://raw.githubusercontent.com/szpeter80/hufilter/master/hufilter.txt": {
		"off": true,
		"title": "HUN: hufilter",
		"group": "regions",
		"lang": "hu",
		"supportURL": "https://github.com/szpeter80/hufilter"
	},
	"https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt": {
		"off": true,
		"title": "CZE, SVK: EasyList Czech and Slovak",
		"group": "regions",
		"lang": "cs",
		"supportURL": "https://github.com/tomasko126/easylistczechandslovak"
	},
	"http://someonewhocares.org/hosts/hosts": {
		"off": true,
		"title": "Dan Pollockâ€™s hosts file",
		"group": "multipurpose",
		"supportURL": "http://someonewhocares.org/hosts/"
	},
	"https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt": {
		"off": true,
		"title": "Spam404",
		"group": "malware",
		"supportURL": "http://www.spam404.com/"
	},
	"http://stanev.org/abp/adblock_bg.txt": {
		"off": true,
		"title": "BGR: Bulgarian Adblock list",
		"group": "regions",
		"lang": "bg",
		"supportURL": "http://stanev.org/abp/"
	},
	"http://winhelp2002.mvps.org/hosts.txt": {
		"off": true,
		"title": "MVPS HOSTS",
		"group": "multipurpose",
		"supportURL": "http://winhelp2002.mvps.org/"
	},
	"https://www.fanboy.co.nz/enhancedstats.txt": {
		"off": true,
		"title": "Fanboyâ€™s Enhanced Tracking List",
		"group": "privacy",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://www.fanboy.co.nz/fanboy-antifacebook.txt": {
		"off": true,
		"title": "Anti-ThirdpartySocial (see warning inside list)",
		"group": "social",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://www.fanboy.co.nz/fanboy-korean.txt": {
		"off": true,
		"title": "KOR: Fanboy's Korean",
		"group": "regions",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://easylist-downloads.adblockplus.org/easylistspanish.txt": {
		"off": true,
		"title": "spa: EasyList Spanish",
		"group": "regions",
		"lang": "es",
		"supportURL": "https://forums.lanik.us/viewforum.php?f=103"
	},
	"https://www.fanboy.co.nz/fanboy-swedish.txt": {
		"off": true,
		"title": "SWE: Fanboy's Swedish",
		"group": "regions",
		"lang": "sv",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://www.fanboy.co.nz/r/fanboy-ultimate.txt": {
		"off": true,
		"title": "Fanboy+Easylist-Merged Ultimate List",
		"group": "multipurpose",
		"supportURL": "https://forums.lanik.us/"
	},
	"https://adguard.com/filter-rules.html?id=13": {
		"off": true,
		"title": "TUR: Adguard Turkish Filter",
		"group": "regions",
		"lang": "tr",
		"supportURL": "http://forum.adguard.com/forumdisplay.php?51-Filter-Rules"
	},
	"https://www.fanboy.co.nz/fanboy-vietnam.txt": {
		"off": true,
		"title": "VIE: Fanboy's Vietnamese",
		"group": "regions",
		"lang": "vi",
		"supportURL": "https://forums.lanik.us/"
	},
	"www.malwaredomainlist.com/hostslist/hosts.txt": {
		"title": "Malware Domain List",
		"group": "malware",
		"homeURL": "https://www.malwaredomainlist.com/hostslist/hosts.txt"
	},
	"https://www.void.gr/kargig/void-gr-filters.txt": {
		"off": true,
		"title": "GRC: Greek AdBlock Filter",
		"group": "regions",
		"lang": "el",
		"supportURL": "https://github.com/kargig/greek-adblockplus-filter"
	},
	"https://raw.githubusercontent.com/betterwebleon/slovenian-list/master/filters.txt": {
		"off": true,
		"title": "SVN: Slovenian List",
		"group": "regions",
		"lang": "sl",
		"supportURL": "https://github.com/betterwebleon/slovenian-list"
	}
}

**Comment by gorhill** [comment]
> Can someone help me in debugging steps?

I am trying, but you are not reading carefully what I am asking.

1. Did you look in the dev console of the extension?

2. Did you look for EasyList/EasyPrivacy in `./assets/thirdparties/...`?
- Is `./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt` present?
- Is `./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt` present?

**Comment by gorhill** [comment]
> I downloaded the version 1.9.14

Can you tell me the exact name of the file what you downloaded in the [Releases](https://github.com/gorhill/uBlock/releases) section?

**Comment by mizhang** [comment]
Sorry to not get your points earlier.  Here are my replies now:


 1. Did you look in the dev console of the extension?
 2. I checked the dev console, but didn't find any errors, only some warnings
    regarding network connection might be low.
 3. Did you look for EasyList/EasyPrivacy in ./assets/thirdparties/...
 4.                 Under assets, there is only one folder "ublock".  I didn't
    find "thirdparties" folder at all.  Thus, no files mentioned in your
    following 2 questions are found.  Seems like this might be the cause.

 1. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
     present?
 2. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt
     present?

Also, I downloaded uBlock-1.9.14.zip, and I am using mac computer.
Thanks very much for your debugging help.
miya
 





On Tue, Oct 11, 2016 12:28 PM, Raymond Hill notifications@github.com
wrote:
Can someone help me in debugging steps?

I am trying, but you are not reading carefully what I am asking.

 1. Did you look in the dev console of the extension?
    
    
 2. Did you look for EasyList/EasyPrivacy in ./assets/thirdparties/...?
    
    
 3. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt 
    present?
 4. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt 
    present?

**Comment by mizhang** [comment]
also, here is the error message I got when I was running preinstallation step:
MacBook-Pro-2:ublock-2 Zhang$ ./tools/make-chromium.sh*** uBlock0.chromium:
Creating web store package*** uBlock0.chromium: Copying files*** Packaging
assets in dist/build/uBlock0.chromium/assets... cp:
../uAssets/thirdparties/easylist-downloads.adblockplus.org: No such file or
directorycp: ../uAssets/thirdparties/mirror1.malwaredomains.com: No such file or
directorycp: ../uAssets/thirdparties/pgl.yoyo.org: No such file or directorycp:
../uAssets/thirdparties/publicsuffix.org: No such file or directorycp:
../uAssets/thirdparties/www.malwaredomainlist.com: No such file or directorycp:
../uAssets/filters/*: No such file or directorycp:
../uAssets/checksums/ublock0.txt: No such file or directorydone.***
uBlock0.chromium: Package done.
 





On Tue, Oct 11, 2016 2:04 PM, Mi Zhang mi.zhang@gmail.com
wrote:
Sorry to not get your points earlier.  Here are my replies now:


 1. Did you look in the dev console of the extension?
 2. I checked the dev console, but didn't find any errors, only some warnings
    regarding network connection might be low.
 3. Did you look for EasyList/EasyPrivacy in ./assets/thirdparties/...
 4.                 Under assets, there is only one folder "ublock".  I didn't
    find "thirdparties" folder at all.  Thus, no files mentioned in your
    following 2 questions are found.  Seems like this might be the cause.

 1. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
     present?
 2. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt
     present?

Also, I downloaded uBlock-1.9.14.zip, and I am using mac computer.
Thanks very much for your debugging help.
miya
 





On Tue, Oct 11, 2016 12:28 PM, Raymond Hill notifications@github.com
wrote:
Can someone help me in debugging steps?

I am trying, but you are not reading carefully what I am asking.

 1. Did you look in the dev console of the extension?
    
    
 2. Did you look for EasyList/EasyPrivacy in ./assets/thirdparties/...?
    
    
 3. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt 
    present?
 4. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt 
    present?

**Comment by gorhill** [comment]
> Also, I downloaded uBlock-1.9.14.zip,

So you are not downloading the released package, you are downloading the source files. The assets are not part of the current project, they are pulled and put into the package by the build script. If you want to build your own version of uBO, you will also need to clone `https://github.com/uBlockOrigin/uAssets`, such that you end up with the following structure locally:

    ./uAssets/
    ./uBlock/

Then the `./tools/make-chromium.sh` script should work without errors when launched from within `./uBlock/`

**Comment by mizhang** [comment]
That makes great sense.  Thanks for your help!
Miya
 





On Tue, Oct 11, 2016 2:16 PM, Raymond Hill notifications@github.com
wrote:
Also, I downloaded uBlock-1.9.14.zip,

So you are not downloading the released package, you are downloading the source
files. The assets are not part of the current project, they are pulled and put
into the package by the build script. If you want to build your own version of
uBO, you will also need to clone https://github.com/uBlockOrigin/uAssets, such
that you end up with the following structure locally:

./uAssets/
./uBlock/


Then the ./tools/make-chromium.sh  script should work without errors when
launched from within ./uBlock/

**Comment by mizhang** [comment]
Sorry, didn't get your points earlier,  here are my responses.
  1. Did you look in the dev console of the extension?
 2.                   Yes, but didn't found any error message, all warnings.
 3. Did you look for EasyList/EasyPrivacy in ./assets/thirdparties/...?
 4. Ah, I only have ./assets/ublock folder, not ./assets/thirdparties folder
 5. Is
    ./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txtpresent?
 6.                   There is only one folder under assets, which is ublock.
     So no thirdparties folder at all
 7. Is
    ./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txtpresent?




On Tue, Oct 11, 2016 12:28 PM, Raymond Hill notifications@github.com
wrote:
Can someone help me in debugging steps?

I am trying, but you are not reading carefully what I am asking.

 1. Did you look in the dev console of the extension?
    
    
 2. Did you look for EasyList/EasyPrivacy in ./assets/thirdparties/...?
    
    
 3. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt 
    present?
 4. Is ./assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt 
    present?
