### ISSUE TITLE
cosmetic exception

### ISSUE THREAD

**Issue by Dim-as-integer** [gorhill/uBlock#2058]
hello, i have this case:

```
<li class="mypost">
<div class="mydiv">
<div class="realcontent">
</div>
</div>
</li>

<li class="mypost">
<div class="mydiv">
</div>
</li>

<li class="mypost">
<div class="mydiv">
</div>
</li>
```

the thing is, i want to block all `<li class="mypost">` with exception the one that contain `<div class="realcontent">`
so far im using :has combined with :not , but it seems not working, here's my code:

##li[class="mypost"]:not(li[class="mypost"]:has(div[class="realcontent"]))

and i also have tried : 
##li[class="mypost"]:not(:has(div[class="realcontent"]))
and
##li[class="mypost"]:has(:not(div[class="realcontent"]))

but none of it work,
is it possible to do?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
