### ISSUE TITLE
Feature request - porting to Opera Presto (v12.14)

### ISSUE THREAD

**Issue by Ilya-S-Zharskiy** [gorhill/uBlock#2059]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Is it possible to port?

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
opera:about
About Opera
Version information
Version
12.14 
Build
1738 
Platform
Linux 
System
x86_64, 3.10.0-327.36.1.el7.x86_64

- uBlock Origin version: 
No

**Comment by anewuser** [comment]
Opera 12 is dead, and you aren't even using the safest Linux version: https://www.opera.com/download/guide/?os=linux-x86-64&ver=12.16&local=y

**Comment by Hrxn** [comment]
This is a joke, right?

**Comment by uBlock-user** [comment]
Why would you even use an outdated browser ?

**Comment by Hrxn** [comment]
Only god knows...

**Comment by Ilya-S-Zharskiy** [comment]
> Why would you even use an outdated browser ?

- performance
- usability

**Comment by lewisje** [comment]
This project *started* long after Old Opera went EOL, and I'm not sure any of uBlock Origin's code could be salvaged for a port to the old browser.

**Comment by Hrxn** [comment]
> Why would you even **not** use an outdated browser?

- security
- reliability
