### ISSUE TITLE
Overlay opening stutters on Firefox

### ISSUE THREAD

**Issue by shockme** [gorhill/uBlock#206]
When I click on the uMatrix button to open the overlay, instead of the overlay opening smoothly, it opens at a smaller size (the normal size) then switches to the bigger size (advanced mode) and then moves to the left and to the right for a few times before settling on its final position.

I'm attaching a gif, but it doesn't show the issue so clearly as it happens in reality.

When Firefox is sluggish (I have hundreds of tabs) the issue is very pronounced.
![rec2](https://cloud.githubusercontent.com/assets/470676/7667349/20def520-fc0d-11e4-859f-a3824712e880.gif)

**Comment by shockme** [comment]
The gif makes it look almost smooth :) but it's very stuttery in reality. I don't think I can upload a movie on github, which would show the issue more clearly.

**Comment by gwarser** [comment]
https://github.com/chrisaljoudi/uBlock/issues/996

**Comment by gorhill** [comment]
Pretty much everything has been done with regard to this.
