### ISSUE TITLE
Can not find a safari version

### ISSUE THREAD

**Issue by hagabla** [gorhill/uBlock#2061]
Is there any chance we could get a release for the Safari browser? Pretty please.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Hunter-Github** [comment]
https://github.com/el1t/uBlock-Safari - FWIW

**Comment by ylluminate** [comment]
Huge thumbs up @Hunter-Github. Any reason why we're not seeing this Safari support merged with the main branch @gorhill? Is there anything that prevents you from accepting PRs for this functionality?
