### ISSUE TITLE
Doesn't block BlockAdblock adblock

### ISSUE THREAD

**Issue by thebigsmileXD** [gorhill/uBlock#2062]
http://blockadblock.com/

**Comment by anewuser** [comment]
Please read this carefully before posting here: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by thebigsmileXD** [comment]
I did. What now? 👊

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
