### ISSUE TITLE
feature request: switch off button (per domain) only for certain filter lists

### ISSUE THREAD

**Issue by treaki** [gorhill/uBlock#2063]
Hi,

because that is a general feature request issue on which most of your questioner doesn't apply i wont use it here....

Following situation: you click to some site, mostly newspaper like sites, want to read an article but just after an blink of the eye you'll be forwarded to a "please disable your addblocker plus" page. Of cause i then most times doing so, but i have a problem with that:

My list of filter lists (called Vorgegebene Filter in my german gui (may translated in default filter), that one like easy list) dont only contain lists for blocking advertisements (like easy list) but also lists that are meant to protect me (like easy privacy, male ware domains) i want never surf without.

So this is a request for a feature to transfer the big blue off switch (⏻) into a list of off switches for certain (user configurable) categories (like advertising, privacy, malware, social network buttons) of filter lists, so i can easily switch off only advertising blocking and still dont be supervised with tracking links/cookies/scripts or at risk in getting drive by download malware...

I would be very glad if you could implement such a feature.

thanks a lot in advance and keep up the good work, your the best web browser content filtering application i know (only would need it on android ;))

**Comment by gorhill** [comment]
> you'll be forwarded to a "please disable your addblocker plus" page. Of cause i then most times doing so

The proper solution is for you to report such blocking to filter list maintainers, they will figure a workaround without having to disable any filter lists.

**Comment by Atavic** [comment]
That will create more switches and options to care about on any single site with issues.
Give a proper report of your issue and try to find a solution while discussing here.
That will solve the problem and will eventually added to the Code as an improvement!

**Comment by uBlock-user** [comment]
> Where can I find this Vorgegebene Filter?
Vorgegebene Filter  = predefined filters

**Comment by Atavic** [comment]
Try [this](https://github.com/reek/anti-adblock-killer).
