### ISSUE TITLE
U block   19.12  Jap filler only nothing else     fire fox 49.01  64 bit

### ISSUE THREAD

**Issue by frankflash9** [gorhill/uBlock#2064]
Jap filter only
blocking    to much  on   www.blog.avast.com
firefox 49.01 x64
no other filters installed

screen shot  

i just we to blog avast .com 

just blocking to much
![screen shot](https://cloud.githubusercontent.com/assets/22673806/19261692/6231dc82-8fef-11e6-9a79-460663ff5ff2.PNG)

**Comment by lewisje** [comment]
Ask for support on the filter-list's own project page: https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
