### ISSUE TITLE
uBlock Origin blocking outlook as "malware domain"

### ISSUE THREAD

**Issue by GraphicsComputing** [gorhill/uBlock#2065]
uBlock Origin has prevented the following page from loading:
https://outlook.live.com/
Because of the following filter
||outlook.live.com^
Found in: Malware domains

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
