### ISSUE TITLE
[ RFE ] Reduce/Remove/Consolidate Excessive Filter Comments

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#2066]
### Request

Can we find a way to group and place "same domain" filters together and under a SINGLE heading for cleaner, tidier and more managable interface for `My Filters` tab.
### Issue

Right now when you create filters for each site, you get a comment line saying where and when it was done. In principle, LOVE IT, but it does have a dark side that I think you can/should address better. If you create multiple filters on any given site, you get a line of comment for each one.

So if you create 10 filters on a given page, you actually get 33 lines (10 for the filters themselves)(10 for each comment line that goes with that)(10 spaces between each of these binary blocks of information) so as you can see the list gets messy, unreadable, eventually so busy that is unusable and becomes a problem to go hunting for things, its very very very inefficient.
### URLs

Any url, take www.facebook.com and all these rules that I have created for it which come to a monsterous 15 lines and since some of the urls you are on are LONG, the comment grabs that FULL url which adds to the size even more.

> www.facebook.com##div.pagelet-group#pagelet_advertiser_panel
> www.facebook.com##div#pagelet_rhc_footer
> www.facebook.com##div.pagelet-group#work_mobile_upsell_pagelet
> www.facebook.com##div.pagelet-group#pagelet_trending_tags_and_topics
> www.facebook.com##div.pagelet-group#pagelet_ego_pane

clearly as time goes on, at this rate, you are creating a very very very large and inefficient bunch of data to be parsed each time, it WILL have stability and performance issues over time.
### Screenshots

Not a visual issue, more of a internals issue and housekeeping. This is a built-in function that ANYONE can see, so screenshots are moot and unnecessary but if you absolutely think it makes a difference somehow, let me know.
### Reproduce

Very easy, again part of the functionality of the program, so to reproduce it, is to simply use it as you would. Go to a website, any website, and begin making rules on it and when you have done a few, go look at the `My Filter` tab and you will see exactly what I mean - even if you didn't already know - which I suspect everyone does if you have EVER looked at it.
### Settings

For this particular one, there is none - meaning specific setting for it, but here is my settings none the less, who knows maybe there is a setting for it and I didn't see it, but that would mean I am very blind :)

![image](https://cloud.githubusercontent.com/assets/5274181/19337685/297d9e5c-90cc-11e6-8032-79d49a1af209.png)
- **Browser/version :** Chrome (Stable) Version 53.0.2785.143 m (64-bit) until today's update to Version 54.0.2840.59 m (64-bit) and nothing else has changed.
- **uBlock Origin version :** v1.9.10
### Lists

Again, not applicable here, so I won't clutter here with it but except for a couple extras that I clicked, the rest is pretty default, minus ONE outside list that is actually meant to prevent blocking of the blocking and it is combined with a TM script to ensure that they can't invalidate my blocks.
### Filters

N/A

**Comment by gorhill** [comment]
> clearly as time goes on, at this rate, you are creating a very very very large and inefficient bunch of data to be parsed each time, it WILL have stability and performance issues over time.

uBO [pre-compiles the filter lists](https://github.com/gorhill/uBlock/wiki/Launch-and-filter-lists-load-performance), so the parsing cost is incurred once only, after a change in the list.

**Comment by gorhill** [comment]
> Can we find a way to group and place "same domain" filters together and under a SINGLE heading for cleaner, tidier and more managable interface for My Filters tab.

The content of _"My filters"_ can be modified both by uBO **and** the user, so it's not deterministic from uBO's point of view, especially when it comes to "heading" -- there is no guarantee that a comment is related to the line immediately under it.

**Comment by GuardianMajor** [comment]
Precompile != efficient
You create comment/rule so how can you not know they are related?
Anyway, fix it, don't fix it, care, don't care, I give up. 
You are not the same person I took time to help and I am done trying. Good luck.

**Comment by gorhill** [comment]
> You are not the same person I took time to help and I am done trying.

This is your past contributions:
- <https://github.com/gorhill/httpswitchboard/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3AGuardianMajor%20>
- <https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue%20commenter%3AGuardianMajor%20>

I don't see where you get this "not the same person" idea.

I don't know of any serious issue tracker where arguments for/against are not throw, that is the essence of development. In any case, ultimately I am the one at the end of the requested work load, so it should be accepted when I express reservations or outright decline requests.
