### ISSUE TITLE
Icon greyed out

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#2068]
It seems in very rare cases (at least here) the icon can be greyed out. Was the case for uBlock and uMatrix at the same time.

It was the case after "very fast" opening a page from my bookmark symbol list. It's possible that before a blank page was active (greyed out).

However: the page was ...

http://jessehakanen.net/adblockpluspopupaddon/test.html

... but i can not reproduce it. But both icons were definitely greyed out.

While the icons were grey I had saw that uMatrix was working (saw some green cells) - unfortunately I did not checked uBlock too - but I assume that uBlock was working too.

After page reload (soft or hard, I'm unsure about that) all was normal again.

uBlock v1.9.15b2 and uMatrix v0.9.9b2 on Win 10 Pro x64 (1607) with Fx 49.0.1 x64

PS: I could not open an issue in uMatrix because there are no more issues ...

EDIT: I saw that the AddOn "Pop-up Controller" (https://addons.mozilla.org/de/firefox/addon/pop-up-control/) which I had in use can have influence to uMatrix (if the state was changed from "Pop-up Controller" and status Pop-up window was open yet or something like that), the cells of uMatrix were empty. Could be the same for uBlock too.
Perhaps it has an influence for the "grey problem" too?
However: I have deinstalled this AddOn now and will keep an eye to the Icons ...

EDIT2: Since I have deinstalled the AddOn  "Pop-up Controller" and reinstalled Firefox, I have never seen this behaviour again - so I close this Issue (I will reopen if something changes).

**Comment by Betsy25** [comment]
+1

uBlock Origin 1.9.12 + later
Firefox stable + nightly.
