### ISSUE TITLE
UA spoof

### ISSUE THREAD

**Issue by crssi** [gorhill/uBlock#2069]
The "Issues" page is somehow missing at uMatrix, so I am posting here, since there is the same extraordinary group of developers behind the scene. :)

UA spoof in uMatrix doesn't work on iFrames.

Enable UA spoof and go to https://www.browserleaks.com/javascript
Pay attention on "User-Agent" info.
On top, you have two buttons "window" and "iframe.contentWindow"... click on both... the real UA is revealed under "iframe.contentWindow".

At this time I would also like to thank you for deliver us your great addons.

Cheers

**Comment by gorhill** [comment]
This issue tracker is for uBO only.
