### ISSUE TITLE
Issues with rai.tv videos

### ISSUE THREAD

**Issue by mirkr** [gorhill/uBlock#207]
Hello, I'm experiencing issues with this italian website. 
For instance this video, among many others, doesn't play when uBlock is activated: http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-36c6419c-ea3a-48b8-ad9d-3f1614e269f1.html
Could you do anything about it?
Thank you for your hard work and for making the internet a better place to surf.

**Comment by gorhill** [comment]
Played first try with default lists. So clearly you have selected some filter list(s) which is causing you issue. I don't maintain filter lists, you have to report to the maintainers of whatever filter list is causing you problem.
