### ISSUE TITLE
Hiding this element on YouTube leaves a empty space behind

### ISSUE THREAD

**Issue by XxBonf1r3xX** [gorhill/uBlock#2070]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Hiding the Google Privacy Notice message bar on YouTube leaves a empty space behind

### One or more specific URLs where the issue occurs

https://www.youtube.com/watch?v=moVZpr_os2k

[URL(s) for issue on a specific site are **mandatory**]

https://www.youtube.com/

### Screenshot in which the issue can be seen

![222798_bonfire-poster](https://cloud.githubusercontent.com/assets/20170353/19405638/8b25d48c-9282-11e6-82fb-36d6f33c90ec.png)

[Screenshot(s) for visual issues are **mandatory**]

![222798_bonfire-poster](https://cloud.githubusercontent.com/assets/22847583/19405868/59d289a4-9285-11e6-9ffa-ad51fd13f06e.png)

### Steps for anyone to reproduce the issue

1. Open up that YouTube link mentioned above
1. Make sure you have only mentioned filters below enabled
1. Notice that it will hide the Google Privacy Notice message bar correctly but it will leave a so called "empty space" behind

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 56.0.2890.0 (64-bit)
- uBlock Origin version: uBlock Origin 1.9.10

##### Your filter lists

Fanboy’s Annoyance List‎
Fanboy+Easylist-Merged Ultimate List‎

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

No custom filters

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
