### ISSUE TITLE
No works in Yandex Android

### ISSUE THREAD

**Issue by Molkio** [gorhill/uBlock#2071]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
No works in Yandex Android browser, could you fix it?

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by lewisje** [comment]
Yandex Browser for Android is based on Chromium for Android and does not allow extensions; it does apparently have its own ad-blocker at least.

**Comment by chessgeniusc2** [comment]
Yandex Android has started support for chrome and opera extentions. BUT, they have BLACKLISTED specific extentions and unfortunately, Ublock Origin is one of them along with uMatrix and HTTP Switchboard. The user gets a warning popup saying "this extention (ID of the extention) has been flagged as malicious and has been blocked by The Administrator" Even in developer mode, it cannot be installed. Surprisingly enough,  they haven't blocked Ublock and some other forks.

**Comment by Molkio** [comment]
Where can I get ublock and other forks?
It is very interesting!

**Comment by chessgeniusc2** [comment]
Chrome Web Store.

**Comment by Molkio** [comment]
Thanks! 

I just installed :)

**Comment by chessgeniusc2** [comment]
Which one did u install? Anyway to use uMatrix?

**Comment by Molkio** [comment]
UBlock (not Origin...) and for me now it's perfect!

uMatrix cannot possible :(

**Comment by gorhill** [comment]
@Molkio You need to complain to your browser vendor if they blacklisted uBlock Origin and uMatrix. I would seriously think of using another browser, they clearly do not have the best interests of users in mind by mislabeling uBO and uMatrix as "malicious".

**Comment by Molkio** [comment]
@gorhill Thanks, I'll report the problem to Yandex Team :)

**Comment by chessgeniusc2** [comment]
@gorhil please provide us with some solution. I have complained about this issue to the developer at PlayStore. But they haven't replied yet.

**Comment by lewisje** [comment]
If the browser vendor has blacklisted an extension, there isn't anything the extension developer can do about it.

**Comment by chessgeniusc2** [comment]
Along with me other users have complained as well. So hopefully, they will provide support. @Gorhill Hats off for your hard work.

**Comment by gorhill** [comment]
> @gorhill please provide us with some solution

Use a browser which gives you the freedom to install uBlock Origin.

**Comment by hawkeye116477** [comment]
@chessgeniusc2 Old uBlock can be installed, but it doesn't work properly, settings can't be opened. If I want to install uBlock Origin, appears message that Yandex doesn't support this extension and not that uBlock is malicious, so.... Yandex probably not support all needed API for blockers extensions. Only built-in shocking blocker and Adguard Content Blocker works with Yandex.

@gorhill So only Firefox, because only Firefox fully supports extensions on Android.

**Comment by bershan2** [comment]
@hawkeye116477

> Only built-in shocking blocker and Adguard Content Blocker works with Yandex.
List on https://tech.yandex.com/browser/contentblocker/ contains two more extensions:
 - Adblock Plus
 - Adblock Fast
I wonder why there is a discrepancy.

[Yandex.Browser integrates the blocking functionality into itself, so extensions merely serve as the source of filters](https://tech.yandex.com/browser/contentblocker/doc/dg/concepts/adjustment-docpage/#process-description), thus you don't really use the adblocker -- just the filter lists that it endorses.

**Comment by hawkeye116477** [comment]
I did trick, installed Yandex Browser Alpha, then downloaded zip uBlock Origin from github, unpacked and type chrome://extensions into address bar, then load unpacked extension, I choose manifest.json from unpacked uBlock Origin and uBlock Origin works correctly, so Yandex lie :smile: .
