### ISSUE TITLE
Allow to disable blocking for particular sites only in incognito / private browsing

### ISSUE THREAD

**Issue by piotr-szpetkowski** [gorhill/uBlock#2073]
### Describe the issue

My issue is rather simply in theory, but might be tricky to implement. I wish to have separate blocking settings in private / incognito mode and separate in the normal mode, so if I decide to unblock site in the private mode it is still being blocked in normal mode.

For example - I need to test some website with blocking disabled and so I launch it in private mode and after I'm done I enable the blocking again. It's an option, but if private and normal mode would have different "profiles" it would be much more convenient in my opinion.

### Steps for anyone to reproduce the issue

1. Fire up one browser window in normal mode and another in private / incognito mode.
2. Open the same site in these two browser windows (with blocking enabled).
3. Disable blocking for this website in private mode.
4. Now close the normal browser window and open it again on the same website as before - blocking is now disabled in normal mode as well, which probably is not desired effect for most cases.

### My settings

- Browser/version: Chromium 53.0.2785.143 (64-bit)
- uBlock Origin version: 1.9.10

### Your filter lists

Default filter lists only.

**Comment by gorhill** [comment]
Create two profiles, one for normal mode, one for incognito mode.
