### ISSUE TITLE
My suggestion about UBlock Origin

### ISSUE THREAD

**Issue by czesioanonim** [gorhill/uBlock#2075]
Hello everybody. I am polish user Ublock Origin. This extension is fantastic. I don't know who are authors and how contact with somebody author, so I write my idea/suggestion here. A lot of websites is creating anti adblock/ublock scripts. Filtres AA not worked. My idea is that UBlock Origin in new versions have option who loads all adverts on website (anti-adblock fine) but these adverts change size 0x0px or 1x1 px ;) This is real solution?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
