### ISSUE TITLE
Some images are not blocked or recognized as image

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#2076]
For some reason, I recently noticed images that were added by me to manual filters were not getting blocked. I looked into it and it seems that some of them were only recognized as doc or inline-script not image (maybe something to do with server response, and it wasn't just one website). 

The thing that's weird is I thought it was some browser cache problem after I added a uBO filter but once I cleared browser cache I see that it is recognized by the logger as an image and blocked (I didn't reload the image, just cleared cache btw).

Example URL: https://i.imgur.com/Ml1z5wv.jpg

After adding custom filter and refreshing page (can see another image loaded being recognized though):
https://i.imgur.com/BByZG9X.png

After clearing browser cache:
https://i.imgur.com/S890u4A.png

- Browser/version: 49.0.1
- uBlock Origin version: 1.9.12

##### Your filter lists 
Default
##### Your custom filters (if any)
||i.imgur.com/Ml1z5wv.jpg

**Comment by gorhill** [comment]
The image is served as a `main_frame` by the browser API, because you are loading it directly instead of as a secondary resource. It's by-browser-design.
