### ISSUE TITLE
[Bug?]Twitter Widget Preview doesn't work with everything whitelisted

### ISSUE THREAD

**Issue by Jules-A** [gorhill/uBlock#2077]
### Describe the issue
With everything whitelisted, the Twitter Widgets Configurator does not show the preview content. Works fine when disabled for site but I assume whitelisting should be working?

### One or more specific URLs where the issue occurs
https://twitter.com/settings/widgets/new/search?query=Orokin%20Reactor%20OR%20Catalyst%20from%3AWarframeAlerts

### Screenshot in which the issue can be seen
Disabled for site: http://i.imgur.com/bijxjDe.jpg
Without Whitelist: http://i.imgur.com/EOmr8N9.jpg
With Whitelist (global, I tried local individual too): http://i.imgur.com/EqBmVRd.jpg

### Steps for anyone to reproduce the issue

Use the same settings/(browser?)/(filters?) as me, if it isn't showing the preview also try whitelisting local/global.

### Your settings

All privacy options and default behavior unticked.

- Browser/version: Firefox Dev v51 16/10/2016
- uBlock Origin version: 1.9.15rc0

##### Your filter lists

Fanboy Ultimate. 
Peter Low
Both Anti-adblock
HP Hosts

**Comment by gorhill** [comment]
> With Whitelist

That does not disable cosmetic filtering.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
