### ISSUE TITLE
Wiki editing disabled

### ISSUE THREAD

**Issue by rugk** [gorhill/uBlock#2078]
Why do you request one to edit the wiki ([here](https://github.com/gorhill/uBlock/wiki/Advanced-user-features)) if you disabled the wiki edit option for usual users?

There is no edit button, so you obviously disabled that feature.

**Comment by gorhill** [comment]
Fixed in <https://github.com/gorhill/uBlock/wiki/Advanced-user-features/5d0bc8e957c3fc13bbff393b2476fa3665af1012>.

**Comment by rugk** [comment]
Hmm, not really a nice fix. Why not enable editing?

**Comment by gorhill** [comment]
What do you want to edit?

**Comment by rugk** [comment]
Collaboration? Fixes? Whatever...

Why have you disallowed it?

**Comment by gorhill** [comment]
Stick to _specific_ issues please, as requested in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
