### ISSUE TITLE
How do I track down which 3rd party filter is overriding my local rules?

### ISSUE THREAD

**Issue by vibrasphere** [gorhill/uBlock#2080]
I can't manage to unblock YouTube iframes on www.discogs.com page. I have set these rules:
```
* www.youtube-nocookie.com * allow
www.discogs.com * 3p-frame allow
```

e.g. https://www.discogs.com/Zeta-Reticula-EP5/release/9147818

But uBlock still blocks the www.youtube-nocookie.com and it doesn't show where it's coming from.

Now to debug it by unticking one-by-one of 20 filters to track it down would be a bit unpractical, no?

Anyway, why my local rules can't override 3rd party filters? Local rules set manually should be primary and top priority by default, because it's your custom settings. Just like you set it on uMatrix, works like a charm.

**Comment by gorhill** [comment]
> Local rules set manually should be primary and top priority by default

They have top priority, as documented in the wiki.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
