### ISSUE TITLE
Can we implement subscription for public list of shops with skimming?

### ISSUE THREAD

**Issue by byaka** [gorhill/uBlock#2082]
https://gwillem.gitlab.io/2016/10/11/5900-online-stores-found-skimming/

Don't understand for now, how we can block this sites fully and globally (and ofcourse we need to show reason of blockin, or we confuse user)

**Comment by gorhill** [comment]
> Can we implement

You can create such list on your repo and publish for anybody to use.

**Comment by byaka** [comment]
Oh, @gorhill sorry if i injure u.
I speak about another thing. Subscription like this must fully block site (with high ptiority), as we dont know in what page placed payment dialog. But this can confuse user. Is it possible to create subscription, that not only block resources, but also show some message or notif or redirect to another page (that explain reason)?

**Comment by gorhill** [comment]
Use the `document` option:

    ||joethetaxi.com^$document

This will block the whole document, and the page will provide the filter list which contains the filter which caused the block. Give the filter list a meaningful title so as to provide a hint to the user as to why it is blocked.

**Comment by byaka** [comment]
If somebody need this.. https://raw.githubusercontent.com/byaka/ublock-antiskimming-list/master/build/data.txt

**Comment by gorhill** [comment]
You could notify @collinbarrett, he might be interested in adding your list to his collection of lists at <https://filterlists.com/>.

One thing I could add to uBO is the parsing of a `Support: [url]` field in a filter list subscription, to use as support link in case someone wants to report a missing filter or a false positive.

**Comment by byaka** [comment]
Interesting, thx. I text him, but first i need auto-updater for this subscription (@gwillem updating original list periodically).

**Comment by collinbarrett** [comment]
hey @byaka , great idea to add a list for this. i saw this article floating around a couple of days ago and all of the github/gitlab censoring drama. subscribing to your list on my personal install of uBo to try it out, and filing it away to add to FilterLists eventually. I haven't had much time as of late to work on FilterLists (and it needs it), but I hope to find time soon.

**Comment by byaka** [comment]
Thx, @collinbarrett.

I add auto-updater (and run it on my server). So now subscription is always actual (cheking every 3 hours).

**Comment by collinbarrett** [comment]
hey, @byaka , I just wanted to swing back around and let you know that your list is on the new version of FilterLists that I deployed last weekend. thanks!

https://filterlists.com/#uBlockAntiskimmingList
