### ISSUE TITLE
Neogaf does not load when e10s and ublock origin are enabled

### ISSUE THREAD

**Issue by hungrymonkey** [gorhill/uBlock#2087]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Neogaf does not load when e10s and ublock origin are enabled

### One or more specific URLs where the issue occurs

http://www.neogaf.com/forum/

### Screenshot in which the issue can be seen

The issue can be viewed as here.

![ublock=1|e10s=1](https://cloud.githubusercontent.com/assets/771339/19575720/ea931ca4-96c4-11e6-8f38-cf5b3c8b15ae.png)

When one or another feature is disabled, the site works again. However, you kinda have to clear browser cache.

![ublock=1|e10s=0](https://cloud.githubusercontent.com/assets/771339/19575708/dd28f868-96c4-11e6-9fc8-beae97bcf298.png)

![ublock=0|e10s=1](https://cloud.githubusercontent.com/assets/771339/19575741/0370c9ec-96c5-11e6-8132-2b59c40b7840.png)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: 

 a. Force enable e10s as describe in this link https://wiki.mozilla.org/Electrolysis

 b. download ublock origin

 c. navigate to http://www.neogaf.com/ 

### Your settings

- Browser/version: firefox 49.0.1-1.2 

- uBlock Origin version: 1.9.12

- OS - Opensuse tumbleweed.

[ff.txt](https://github.com/gorhill/uBlock/files/542768/ff.txt)

##### Your filter lists

Default

I wonder if this counts as an actual bug.

**Comment by gorhill** [comment]
Unrelated to uBlock Origin or Firefox. It is reproducible without uBlock Origin, or with Chromium. Quit the browser while ensuring all cookies are cleared, re-launch the browser with no tab present, navigate to Neogaf and often you will have the blank page. The `view-source:` for the page show nothign was sent by the server. It's a server issue.

**Comment by hungrymonkey** [comment]
nvm, it seems to work with 1.9.14.

**Comment by hungrymonkey** [comment]
ok, thank you.
