### ISSUE TITLE
Deactivating uBlock for single page on mobile devices is different

### ISSUE THREAD

**Issue by rugk** [gorhill/uBlock#2089]
### Describe the issue

In the uBlock panel you can Ctrl+click on the big on/off icon to turn tracking the current site.
However on mobile devices this is hardly doable.
### Steps for anyone to reproduce the issue
1. Install uBlock in Firefox for Android and visit a site (with content blocked by uBlock)
2. Open the uBlock panel.
3. Try to deactivate filtering for the current site.
### Your settings
- Browser/version: Firefox 49.0.2
- uBlock Origin version: 1.9.12 on Firefox for Android

If there are alternative ways to deactivate it, I'd be glad to hear, what.

**Comment by gorhill** [comment]
Ctrl-click is for the current page only. For the site, just a click is needed.

**Comment by rugk** [comment]
Ah, yes that's what I mean. Nevertheless it won't work on mobile devices.
