### ISSUE TITLE
Question: Short story of uBlock?

### ISSUE THREAD

**Issue by mawekuwe** [gorhill/uBlock#209]
Hi,
there is a short story why uBlock is now stated "forked from chrisaljoudi/uBlock" and now called 'uBlock origin'? 
What happened? 
What is differences between?

Thanks for the useful extension by the way.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>:

> 1. Submit bugs/issues only.

**Comment by mawekuwe** [comment]
thank you for the very kind reply.
