### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by AndGK** [gorhill/uBlock#2090]
Why would you block google analytics by default? That's pretty bad for website owners.. It does not affect users in anyway, but setting it on default is pretty stupid.

**Comment by Hrxn** [comment]
Wrong place to ask questions...

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
>Why would you block google analytics by default?

data mining/violation of user's privacy and stuff like that.

>That's pretty bad for website owners.. 

Not the user's problem or a concern..

>It does not affect users in anyway

Yes it does affect the user, as google collects information about the user's visit and his/her activity on the website, ergo violation of privacy..

>setting it on default is pretty stupid

That's your opinion, not a FACT, hence invalid.
