### ISSUE TITLE
Images on Google Images not being displayed

### ISSUE THREAD

**Issue by abarragan** [gorhill/uBlock#2091]
Hi I'm new at this so if I miss any data let me know and I will provide. 

I have had a problem where images are not being displayed on Google Images. Bug is reproduced as follows:

1- Search for example "beautiful landscapes" on Google Images. 
2- Start clicking on some images, also on the ones under "Related Images" section.
3- After like a dozen of images it will stop displaying them and from that moment on until I refresh the page, none of any clicked image will show up. Looking like this:
https://ibin.co/2zIhx2IOLHLd.jpg

Browser: Opera x86 41.0.2353.30 beta
OS: Win 8.1 Pro x64 & Win10 x64

I have tried to reproduce it on Firefox and Chrome but the bug didn't come up. On Opera when I disabled uBlock and refreshed the page, no matter how many images I'd clicked it's not reproducible so it has to be something on uBlock I guess. 

My filters are: Default +  Adblock Warning Removal List‎  +  Anti-Adblock Killer | Reek‎ +  Fanboy’s Social Blocking List‎

Also this setting is enabled: Prevent WebRTC from leaking local IP addresses

Thank you.

**Comment by gorhill** [comment]
Did you use the logger to find out what is blocked? If not, how can you rule out this is a filter issue?

**Comment by abarragan** [comment]
Okay so here is a log I have just captured.
http://pastebin.com/qfDkFFcv
The minute 9:22:08 was the first jpg not being displayed, after that every other jpg wasn't displayed. That line and every other jpg wasn't in red, so that means it's not being blocked? Even though the images ARE displayed when your add-on is off that doesn't mean is uBlock fault? 
I don't try to blame anyone Opera or you, just if this is bug I want to get it fixes for users joy. I also have reported this behaviour on Opera's blog.

**Comment by gorhill** [comment]
Disabling all filter lists, see if this still happens. If not, it's a filter list issue.

**Comment by abarragan** [comment]
I have just tried that and yes it's working. It really grinds my gears that uBlock works fine on Chrome, I was just able to reproduce it on Firefox. I'm wild guessing it could be because they use a different url on google searches, I mean with different url params. Anyway thank you and sorry for the troubles.

**Comment by sogen** [comment]
I get this issue too

**Comment by abarragan** [comment]
Hi @sogen after some testing I discovered it's because of any Fanboy social blocking list that you might have enabled.

**Comment by sogen** [comment]
great, thanks

**Comment by gorhill** [comment]
> because of any Fanboy social blocking list

Has this been reported to the list maintainer?

**Comment by abarragan** [comment]
I reported here: https://reports.adblockplus.org/4975b9a1-36dd-48f0-b4d1-c90d6be9bded

For others that might get this issue too:
After reading the advanced user guide and playing with filters and rules, learned how to add static filters so it came up that adding this line on My Filters works as a workaround:
@@||pinimg.com^$third-party,domain=~pinterest.com

That creates and exception for that specific filter that is causing this issue.

Thanks Raymond. Cheers.

**Comment by abarragan** [comment]
No, I will do it soon but I don't think they will hear me since it's not reproducible on chrome.
