### ISSUE TITLE
Facebook right sidebar ads not blocked

### ISSUE THREAD

**Issue by anchev** [gorhill/uBlock#2092]
### Describe the issue

I have the following rules in one of my lists (accessible through http):

facebook.com###pagelet_games_rhc
facebook.com###pagelet_advertiser_panel
facebook.com###pagelet_ego_pane

But when I go to facebook.com the last one (which is responsible for the ads in the right sidebar) doesn't seem to work. I double checked if that is the right DOM element to block and as the screenshot shows - it is.

This started happening since yesterday evening. Also reported to easylist forum: https://forums.lanik.us/viewtopic.php?p=105942#p105942

It is interesting that it doesn't happen all the time although even when it happens the DOM elements are the same as in the list.

EDIT: It seems to happen more often on browser start. I suppose if the site has already been loaded before (I suppose cached in some way) it doesn't seem to happen. I have noticed similar issues with other sites too. Might that be related to uBlock not being able to "catch up" with the speed at which certain sites load?

### One or more specific URLs where the issue occurs

facebook.com

### Screenshot in which the issue can be seen

https://snag.gy/kpS0vU.jpg

### Steps for anyone to reproduce the issue

1. Use the filters described
2. Visit facebook.com

### Your settings

- Browser/version: Chromium Version 53.0.2785.143 (64-bit) on openSUSE Leap 42.1
- uBlock Origin version: 1.9.10

##### Your filter lists

Screenshot: https://snag.gy/yRTl6D.jpg

##### Your custom filters (if any)

http://anchev.net/adblock.txt

! Expires: 5 days

facebook.com###pagelet_games_rhc
facebook.com###pagelet_advertiser_panel
facebook.com###pagelet_ego_pane

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
@anchev 

> still don't know why

So you still didn't read [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). Excerpt:

> Ignorance of the above rules is no excuse: **Opening an issue for purpose of support or discussion, or opening a filter-related issue will result in the user being immediately blocked.**
