### ISSUE TITLE
AllMusic

### ISSUE THREAD

**Issue by svnpenn** [gorhill/uBlock#2095]
AllMusic has an overlay on their pages:

> Help Support AllMusic

> It appears that you are using an AdBlocker or something is blocking
> advertisements from being displayed on our site. This impacts our ability to
> keep AllMusic up and running. Please help us keep our content free by
> selecting one of the following options:

http://allmusic.com/album/tally-ho%21-mw0000044224

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by svnpenn** [comment]
https://github.com/uBlockOrigin/uAssets/issues/171

**Comment by svnpenn** [comment]
https://github.com/reek/anti-adblock-killer/issues/1941

**Comment by svnpenn** [comment]
https://github.com/reek/anti-adblock-killer/issues/2020
