### ISSUE TITLE
Mac App Store links lead to "400 Bad Request"

### ISSUE THREAD

**Issue by gordo** [gorhill/uBlock#2096]
All Mac App Store links seem to lead to the following error message:

```
400 Bad Request
Request Header Or Cookie Too Large
nginx
```

For example, try this:
https://geo.itunes.apple.com/app/deliveries-a-package-tracker/id924726344

System details:
macOS Sierra 10.12
Chrome Version 54.0.2840.71 (64-bit)
uBlock Origin Version 1.9.10
Running default filter lists, with itunes.apple.com on the whitelist.

**Comment by gorhill** [comment]
How did you come to the conclusion uBO is the issue?

**Comment by gorhill** [comment]
Marking as invalid, you need to make the case there is an issue with uBO.

**Comment by gordo** [comment]
Apologies @gorhill – it turned out to be a red herring. uBO is not the culprit at all – it's more likely because of a corrupt cookie I had in Chrome for apple.com.

What led me to mistakenly conclude it was uBO was to disable all extensions in normal mode except for uBO, and then compare it with incognito mode (with all extensions disabled by default) and other browsers where I hadn't installed uBO.

It turns out that I could have just removed uBO in normal mode (since I can export and re-import my uBO settings), or run Chrome with a --disable-extensions flag, and it would have been clear it wasn't uBO after all.

Thanks for following up.
