### ISSUE TITLE
It does not work to switch images by clicking

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBlock#2097]
https://www.kinopoisk.ru/picture/1731467/#1731466

It is necessary to click on the picture - it has to switch to the next. But this does not happen

- Browser/version: Google Chrome 54.0.2840.71 m (64-bit), Firefox 49.0.2
- uBlock Origin version: 1.9.10 for Chrome, 1.9.16 for Firefox

Filter lists: Only - EasyList and RU AdList.

**Comment by gorhill** [comment]
This is a bad code + timing issue on the page.

Given how ABP and uBO works differently for cosmetic filtering, the timing issue is causing the discrepancy between ABP and uBO. uBO does not hold much the page back when it starts to be parsed by the browser<sup>[1]</sup>, and there is some broken javascript on the page (causing the `$.cookie is not a function` message) which ends up being executed earlier with uBO, ultimately preventing the code which set the opacity of the page to 1.

This can be seen just by looking at the console, the sequence of event is different.

ABP:

    GET https://yastatic.net/daas/atom.js net::ERR_BLOCKED_BY_CLIENT
    GET https://an.yandex.ru/system/context.js net::ERR_BLOCKED_BY_CLIENT
    loadContext @ main.js:2527
    checkAdBlock @ main.js:2590
    Uncaught TypeError: $.cookie is not a function
    Uncaught TypeError: $.cookie is not a function

uBO:

    GET https://yastatic.net/daas/atom.js net::ERR_BLOCKED_BY_CLIENT
    Uncaught TypeError: $.cookie is not a function
    GET https://an.yandex.ru/system/context.js net::ERR_BLOCKED_BY_CLIENT
    loadContext @ main.js:2527
    checkAdBlock @ main.js:2590
    main.js:3768 Uncaught TypeError: $.cookie is not a function

As you can see, the faulty code (denoted by `Uncaught TypeError: $.cookie is not a function`) is executed earlier with uBO, and thus cause the following code on the script to abort earlier.

The fix will be to add the following filter to uBO's _Unbreak_ filters: `kinopoisk.ru###image:style(opacity: 1 !important)
`.
***

[1] ABP does, by injecting 17,000+ CSS selectors, not counting those in RU AdList.

**Comment by dimisa-RUAdList** [comment]
Ok,
Thanks!
