### ISSUE TITLE
Issue with http://www.mirrorcreator.com/

### ISSUE THREAD

**Issue by qarqun** [gorhill/uBlock#2098]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Download links will not be generated when uBlock Origin is  enabled.
Disabled all the filters also doesn't fix the issue.
Only by disabling the uBlock Origin, then can view the links.

### One or more specific URLs where the issue occurs

http://www.mirrorcreator.com/files/CNNFRDIG/

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/12039099/19710830/cc68cf00-9b63-11e6-9510-9e875ae744d2.png)

### Steps for anyone to reproduce the issue

1. Make sure uBlock Origin and all the filters are  up to date.
2. Open http://www.mirrorcreator.com/files/CNNFRDIG/ in browser
3. Now you will see **download links** will not appear. (** NOT the big blue "DOWNLOAD NOW button)
4. If disable uBlock Origin extension, then all the links will appear.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Google Chrome/**54.0.2840.71 m (64-bit)**
- uBlock Origin version: **1.9.10**

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

1. Default filter lists minus uBlock -- Experimental
2. EasyList
3. Peter Lowe’s Ad server list‎
4. EasyPrivacy
5. Malware Domain List‎ (malwaredomainlist.com)
6. Malware domains‎ (www.malwaredomains.com)

##### Your custom filters (if any)
none

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Betsy25** [comment]
I wouldn't even start to investigate such a fraud site.

**Comment by Hrxn** [comment]
Welcome to the Internet.

**Comment by gorhill** [comment]
Was properly reported at the right place before: <https://github.com/uBlockOrigin/uAssets/issues/165>.
