### ISSUE TITLE
Why is redirect clause ignored in static filter?

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2099]
### Describe the issue
I'm trying to implement a static filter that will redirect a request for JS to a neutered local resource
```
||st.prntscr.com/*/*/*/*/js/noworker.nude.js$script,redirect=noopjs,first-party
```

I must be doing something wrong because uBO ignores the `redirect` clause. The initial request is blocked but I see no log entry for the redirection. I figured it's a syntax error but [the docs on redirect](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect) are bare.

### One or more specific URLs where the issue occurs

http://prnt.sc/1cmxbx

### Screenshot in which the issue can be seen

In the logger, I see:
![2](https://cloud.githubusercontent.com/assets/12346501/19714745/92bd6dd2-9b1e-11e6-9bd2-cdbb3ac78d96.png)

### Steps for anyone to reproduce the issue

1. Go to the site above, and block all network requests
2. Noop inline-scripts and `prntscr.com`

![1](https://cloud.githubusercontent.com/assets/12346501/19714867/6abea638-9b1f-11e6-882e-c11865bbda59.png)

### Your settings

- Browser/version: Firefox 49
- uBlock Origin version: 1.9.16

##### Your filter lists

![5](https://cloud.githubusercontent.com/assets/12346501/19714928/ddd779ce-9b1f-11e6-867c-7f6cd4a329f8.png)

##### Your custom filters (if any)
Dynamic filters:
```
no-large-media: prnt.sc false
prnt.sc * inline-script noop
prnt.sc prntscr.com * noop
```

**Comment by gorhill** [comment]
Replace `first-party` by `domain=prntscr.com` for now. The parsing of `first-party` is not properly implemented, it current just use the hostname of the resource as the party to match, and in the current case the party is `prnt.sc`, so it never matches `st.prntscr.com`.

I will fix this for next release.
