### ISSUE TITLE
ublock origin "blocks" webtoepub addon on firefox (not on chromium)

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#2100]
I found that ublock origin "blocks" webtoepub on firefox.
The bug happens with Firefox 49.0.1, ublock origin 1.9.15rc1, webtoepub 0.0.0.23.
The bug does not happen on chromium 54.0.2825.0.

webtoepub is an addon that makes epubs out of web pages, specializaling on "novels" content; you can find it here: "https://github.com/dteviot/WebToEpub".

Here is how to reproduce it:

1. I go to "https://translationchicken.com/2016/09/21/rezero-web-novel-fan-translation-table-of-contents/"
2. I click on the webtoepub toolbar button
3. I get "No parser found for this URL. Default parser will be used. You will need to specify how to obtain content for each chapter." [which is OK]
4. I hit OK, so the general parser starts grabbing.
5. I select just 2 links, hit "Pack epub".
6. I instantly get a "NetworkError when attempting to fetch resource." message.
7. I click OK.
8. Back to the main tab of the addon, the "Pack epub" button is greyed out.
9. I see a really small epub is saved (4kb).
10. I don't see traffic on the network in the browser console at all.

If I whitelist the addon window in ublock origin [whitelist entry is "46fb073d-e454-4740-8e95-64f33addd34a.moz-extension-scheme"] the addon then works as expected, the same as it does on chromium, and the epub is created fine; this is strange because in chrome I didn't need to whitelist epubtopdf.

Also, when packing the epub with the addon whitelisted, the console comes to life, but the output disappears as soon as the epub is saved (in firefox).
So I think ublock origin is blocking the network requests in Firefox; but it doesn't this in chrome (even if I have ublock origin websocket installed there).

If anything else is needed just ask.

**Comment by gorhill** [comment]
> this is strange because in chrome I didn't need to whitelist 

In Chromium uBO is not allowed to see the network requests made by other extensions.

**Comment by typhoon71** [comment]
Oh, so firefox is actually better (ublock origin can block more)...
I suppose it's not a bug then?

**Comment by gorhill** [comment]
Does whitelisting `moz-extension-scheme` fix the issue?

**Comment by typhoon71** [comment]
Whitelisting moz-extension-scheme does fix the issue.
But: wouldn't that whitelist all addons network requests (instead of just webtoepub)?

**Comment by gorhill** [comment]
> wouldn't that whitelist all addons network requests

Yes. uBO shouldn't interfere with other add-ons by default.

**Comment by gorhill** [comment]
Also, out of curiosity, what were the network requests being blocked, and by which filters?

**Comment by typhoon71** [comment]
Well, the web page(s) content, so text, images, ... 
I don't know what specific filter got triggered, it just blocked everything.
So I think it was honoring my default "block 3rd party ...".

**Comment by gorhill** [comment]
> * * 3p block
> * * 3p-script block

This was key information which you did not provide in your issue.

**Comment by typhoon71** [comment]
well, obviously I didn't think it was the key info. XD
