### ISSUE TITLE
Australian Taxation Office website is broken with default lists

### ISSUE THREAD

**Issue by tgpraveen** [gorhill/uBlock#2101]
I had to whitelist the Australian Taxation Office site (onlineservices.ato.gov.au) to be able to see details of my Australian Tax Returns, otherwise there are lot of blank spots on the page where the main content should be. Might have to actually whitelist one level above. Maybe worth whitelisting all gov.au sites?

- Browser/version: Chrome 55.0.2883.21 beta (64-bit)
- uBlock Origin version: 1.9.10

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
