### ISSUE TITLE
Popup UI issue in v1.9.16.

### ISSUE THREAD

**Issue by rumorumo** [gorhill/uBlock#2104]
![ublock origin 1 9 16](https://cloud.githubusercontent.com/assets/15052951/19785571/abfc6e0a-9c78-11e6-9e2b-7ae6548ab5b1.JPG)

Chrome 31.0.1650.63 (on Windows XP) and uBlock 1.9.16.

"_Enable Experimental JavaScript_" flag enabled as indicated since 1.9.8 to take advantage of ES6 Set/Map. When this flag is disabled, the popup is OK again. With 1.9.8 or 1.9.10 and this flag enabled it was OK too.

Thank you!

**Comment by gorhill** [comment]
Please look at the dev console of the popup, there must be error message reported. To access the dev console of the popup, right click anywhere on it and click _Inspect_. There is no way for me to test such old Chromium version, so I guess I added js code which was not supported back then.

**Comment by rumorumo** [comment]
There's no apparent error message in the dev console of the popup. For what it's worth here is one sample of what the "_Elements_" panel shows:

![developer tools](https://cloud.githubusercontent.com/assets/15052951/19789934/8dc5ddc6-9c92-11e6-9f9d-e89098fa3259.JPG)

When you say "the dev console of the extension" do you mean the dev console of the dashboard? I haven't found any error reported there either. Could you be more specific on where else I should look?

And from now on I'll try always to use the dev version.

**Comment by gorhill** [comment]
The dev console of the extension is accessible from the _Extensions_ page. If _"Developer mode"_ is checked at the top, uBO will have a link to `background_page.html`. The purpose is to acces teh dev console. I am assuming things were like this for chromium 31 as well, can't remember how things were back then.

**Comment by lewisje** [comment]
You may want to consider upgrading to 49.0.2623.112 (last version of Chrome to support XP or Vista, offline installers have been archived around the Web) or migrating to [Slimjet 10](http://www.slimjet.com/en/dlpage_xp.php) (based on Chromium 50, but with fixes made to keep supporting XP and Vista).

**Comment by rumorumo** [comment]
Thanks for the instructions. Here is what the dev console of the extension shows:

![console](https://cloud.githubusercontent.com/assets/15052951/19812239/8c40752a-9d13-11e6-809d-5ee4b2bd212d.JPG)

**Comment by gorhill** [comment]
Ok I see. As per MDN's info, `Map.prototype.entries` was not available until Chromium 38. This means you will have to disable _"Enable Experimental JavaScript"_, as Map implementation was not really compliant with ES6 Map.

**Comment by gorhill** [comment]
I updated the release note for 1.9.8 to remove hint about _"Enable Experimental JavaScript"_.
