### ISSUE TITLE
Dynamic filtering pane issue in v1.9.16.

### ISSUE THREAD

**Issue by rumorumo** [gorhill/uBlock#2105]
Chrome 31.0.1650.63 (on Windows XP) and uBlock 1.9.16 (using medium mode).

While testing the popup issue at #2104, I found another problem, this time with the dynamic filtering pane.

URL: https://www.estantevirtual.com.br/ (Possibly reproducing the issue won't be straightforward, because in this example it only appears after I sign in at the site. But I think the problem should be quite obvious.)

This is the domains list I was getting with 1.9.14:

![popup 1 9 14](https://cloud.githubusercontent.com/assets/15052951/19816699/1a6a7482-9d27-11e6-9273-fa7c9d90251c.JPG)

And this is what I get with 1.9.16:

![popup 1 9 16](https://cloud.githubusercontent.com/assets/15052951/19816667/fa5e51d6-9d26-11e6-88f2-d3c071362e17.JPG)

When I click on the cells of the last entry of the list, the yellowish one, nothing seems to happen, although in subsequent pages the pane reports the correspondent modification and shows the domains in the right order.

**Comment by gorhill** [comment]
> Possibly reproducing the issue won't be straightforward, because in this example it only appears after I sign in at the site. But I think the problem should be quite obvious.

Yes, I think it is quite probably a side effect of fix to #2053, more specifically the [change in tab.js](https://github.com/gorhill/uBlock/commit/3ff3ae7d7036df5e3a2298300dc12cac7b696ac5#diff-ce215d94a52d449f1a34f292126608d7).

**Comment by rumorumo** [comment]
It seems to be fixed here. Thank you again.
