### ISSUE TITLE
Weird logger issue

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#2106]
**### Describe the issue**
Logger won't display the domain name for an exception filter and would display the domain name as "0"

**### One or more specific URLs where the issue occurs**

https://myanimelist.net/

**### Screenshot in which the issue can be seen**

https://i.gyazo.com/211457b0612d6276ec97429c7d3849ab.png

**### Steps for anyone to reproduce the issue**
1)Open uBlock dashboard and add the following filters -

    ||$third-party,domain=myanimelist.net
    @@||cdn-dena.com^$domain=myanimelist.net

2)Browse to myanimelist.net and open the logger, you will notice that the exception filter the logger displays has value **0** in place of myanimelist.net for the $domain flag which is incorrect.
### Your settings

- Browser/version: Chromium 54/FF 51
- uBlock Origin version: 1.9.16

**##### Your filter lists**

Default

**PS-  this is happening since 1.9.16 and on every exception filter where the format is `@@||example.com^$domain=name.domain`**

**Comment by gorhill** [comment]
I can reproduce.

**Comment by rjkpa** [comment]
so is it fixed and what about https://github.com/gorhill/uBlock/issues/2103 ?

**Comment by gorhill** [comment]
Please: do not _pressure_ developers, it is really unpleasant.

**Comment by rjkpa** [comment]
Not pressuring at all, you haven't said anything or did anything about #2103, so I am curious.

**Comment by gorhill** [comment]
It's definitely pressuring.

I did say something about #2103, it's me who told you to open a separate issue. And even then you should not have any expectations I must say _something_. Specific bugs will get fixed when I have the time and mindset to fix them.

**Comment by gorhill** [comment]
Fixed with b55447635eb63169d76d2e71496f4a97ed5e30c4.
