### ISSUE TITLE
Youtube Comment Section is dead because of ublock 

### ISSUE THREAD

**Issue by Rose2234** [gorhill/uBlock#2107]
ublock has gone to shit it used to be a great adblocker but it's shit. prevents the youtube comments sections from showing up... Gorhill your are shitty developer...

**Comment by lewisje** [comment]
Check the logger, tell us what filter-lists you use,, and please don't insult the developers.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
