### ISSUE TITLE
Disabling uBlock Origin in private browsing mode doesn't work

### ISSUE THREAD

**Issue by terr72** [gorhill/uBlock#2109]
### Describe the issue

In private browsing mode uBlock Origin won't disable the filtering when the big blue on/off button is being used. Reloading the page afterwards via the reload button in the uBlock status field or the one in the Firefox address bar has no effect, the page is still being completely ad-filtered.
This bug exists **only** in private browsing mode.

### One or more specific URLs where the issue occurs

http://www.heise.de/
but basically any page in private browsing mode.

### Steps for anyone to reproduce the issue

1. Enable uBlock Origin and set Firefox in private browsing mode
2. Go to any website like http://www.heise.de/
3. Click on the red uBlock icon in your status bar (or wherever it resides) and push the big blue on/off button to disable filtering.
4. Hit the appearing reload button or the stock one from the Firefox address bar.
5. The page reloads with full ads filtering, though it should be disabled.

### Your settings

- Browser/version: Firefox 45.4.0 ESR on Win 7
- uBlock Origin version: 1.9.16

##### Your filter lists

Default filter lists + Easylist +Easylist Germany

**Comment by gorhill** [comment]
What is your _"Use Tracking Protection in Private Windows"_ setting? If it is enabled, which block list is selected?

**Comment by terr72** [comment]
It's enabled and set to the basic protection of disconnect.me.
And your guess is right: disabling this lets the ads show up after a reload, so this is not related to uBlock Origin. Sorry for blaming uBlock Origin as cause for this behaviour!
