### ISSUE TITLE
Don't raise error if another blocker has gotten to the resource first

### ISSUE THREAD

**Issue by reubenfirmin** [gorhill/uBlock#2113]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

I have both uBlock origin and ghostery installed.  Periodically uBlock will raise an error because ghostery gets to the resource first.

Example:
This extension failed to redirect a network request to data:application/javascript;base64,K...7 because another extension (Ghostery) redirected it to data:application/javascript;base64,dm...s=.

This leads to the chrome menu icon to show an error, despite there being no user-perceptible error.

### Your settings

- Browser/version: Chrome / 54.0.2840.71
- uBlock Origin version:  1.9.16

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
uBO does not raise an error, the browser does.

**Comment by reubenfirmin** [comment]
Then can't ublock detect that ghostery is also installed and avoid clashing with it?

**Comment by rjkpa** [comment]
uBlock doesn't clash at all, in this case, Ghostery does it first and the same action is taken by uBlock later which  causes Chromium/chrome to react like that and spew that warning. Chalk this up to Browser Limitation. I would suggest you to remove Ghostery and only use uBlock.
