### ISSUE TITLE
Conflict with Extension: Blur 

### ISSUE THREAD

**Issue by erreip** [gorhill/uBlock#2114]
### ISSUE:

Getting a the following Warning:

![image](https://cloud.githubusercontent.com/assets/9080659/19893574/01f86c78-a020-11e6-90ac-eb02f955d8b0.png)

### The Full Warning Text is below:

> Warning:
> 
> This extension failed to redirect a network request to data:application/javascript;base64,dmFyIGFiUHJtPXt9O3ZhciBhYk5vT3A9ZnVuY3Rpb24oaSxhKXtyZXR1cm4gKGEmJmEubGVuZ3RoP2FbMF06bnVsbCl8fHRydWU7fSxhYlNDPWZ1bmN0aW9uKG4sdil7ZG9jdW1lbnQuY29va2llPW4rJz0nK3YrJztwYXRoPS87ZXhwaXJlcz0nKyhuZXcgRGF0ZSgobmV3IERhdGUoKSkuZ2V0VGltZSgpKygzMDAwMCo2MCo2MCoyNCkpKS50b0dNVFN0cmluZygpO30sYWJHQz1mdW5jdGlvbihuKXtyZXR1cm4gZG9jdW1lbnQuY29va2llLmluZGV4T2YobisnPScpIT0tMTt9LGFiQWRkTm9PcE1ldGhvZHM9ZnVuY3Rpb24obyxtKXttPW0uc3BsaXQoJywnKTtmb3IodmFyIGk9MDtpPG0ubGVuZ3RoO2krKyl7aWYobVtpXS5tYXRjaCgvXiMvKSl7b1snZ2V0JyttW2ldLnN1YnN0cigxKV09b1snc2V0JyttW2ldLnN1YnN0cigxKV09YWJOb09wO31lbHNle29bbVtpXV09YWJOb09wO319fTt2YXIgYWJDbGlja0V2ZW50PWZ1bmN0aW9uKG4pe2lmKG4uY2xpY2spe24uY2xpY2soKTt9ZWxzZXt2YXIgZT1uLm93bmVyRG9jdW1lbnQuY3JlYXRlRXZlbnQoJ01vdXNlRXZlbnRzJyk7ZS5pbml0TW91c2VFdmVudCgnY2xpY2snLHRydWUsIHRydWUsIG4ub3duZXJEb2N1bWVudC5kZWZhdWx0VmlldywgMSwwLDAsMCwwLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLDAsbnVsbCk7bi5kaXNwYXRjaEV2ZW50KGUpO319O3ZhciBhYlRya3I9e30sYWJHVD1mdW5jdGlvbigpe3JldHVybiBhYlRya3J9LF9nYXQ9e19nZXRUcmFja2VyOmFiR1QsX2NyZWF0ZVRyYWNrZXI6YWJHVCxfZ2V0VHJhY2tlckJ5TmFtZTphYkdULF9hbm9ueW1pemVJcDphYk5vT3B9LF9fdXRtU2V0VHJhbnM9X191dG1MaW5rZXJVcmw9X191dG1MaW5rUG9zdD1fX3V0bVNldFZhcj1fX3V0bVZpc2l0b3JDb2RlPWFiTm9PcCxfZ2FxPXtfY3JlYXRlQXN5bmNUcmFja2VyOmFiVHJrcixfZ2V0QXN5bmNUcmFja2VyOmFiVHJrcixwdXNoOmZ1bmN0aW9uKGEpe2ZvciAodmFyIGIgPSBhcmd1bWVudHMsIGMgPSAwLCBkID0gMDsgZCA8IGIubGVuZ3RoOyBkKyspIHt0cnkge2lmICh0eXBlb2YgYltkXSA9PT0gJ2Z1bmN0aW9uJykgYltkXSgpO2Vsc2Uge3ZhciBlID0gJycsIGYgPSBiW2RdWzBdLCBrID0gZi5sYXN0SW5kZXhPZignLicpO2sgPiAwICYmIChlID0gZlt6XSgwLCBrKSwgZiA9IGZbel0oayArIDEpKTt2YXIgcCA9IGUgPT0gJ19nYXQnID8gX2dhdCA6IGUgPT0gJ19nYXEnID8gX2dhcSA6IF9nYXQuX2dldFRyYWNrZXIoZSk7cFtmXS5hcHBseShwLCBiW2RdLnNsaWNlKDEpKX19IGNhdGNoIChyKSB7YysrfX1yZXR1cm4gYzt9fTthYkFkZE5vT3BNZXRob2RzKGFiVHJrciwnX2RlbGV0ZUN1c3RvbVZhcixfZ2V0TmFtZSxfZ2V0QWNjb3VudCxfZ2V0VmVyc2lvbixfZ2V0VmlzaXRvckN1c3RvbVZhcixfaW5pdERhdGEsX3NldEFjY291bnQsX3NldENvb2tpZVBlcnNpc3RlbmNlLF9zZXRDdXN0b21WYXIsX3NldFNhbXBsZVJhdGUsX3NldFNlc3Npb25UaW1lb3V0LF9zZXRTZXNzaW9uQ29va2llVGltZW91dCxfc2V0VmFyLF9zZXRWaXNpdG9yQ29va2llVGltZW91dCxfdHJhY2tQYWdldmlldyxfc2V0QWxsb3dBbmNob3IsX3NldENhbXBDb250ZW50S2V5LF9zZXRDYW1wTWVkaXVtS2V5LF9zZXRDYW1wTmFtZUtleSxfc2V0Q2FtcE5PS2V5LF9zZXRDYW1wU291cmNlS2V5LF9zZXRDYW1wVGVybUtleSxfc2V0Q2FtcGFpZ25UcmFjayxfc2V0Q2FtcGFpZ25Db29raWVUaW1lb3V0LF9zZXRDb29raWVUaW1lb3V0LF9zZXRSZWZlcnJlck92ZXJyaWRlLF9jb29raWVQYXRoQ29weSxfZ2V0TGlua2VyVXJsLF9saW5rQnlQb3N0LF9zZXRBbGxvd0hhc2gsX3NldEFsbG93TGlua2VyLF9zZXRDb29raWVQYXRoLF9zZXREb21haW5OYW1lLF9hZGRJdGVtLF9hZGRUcmFucyxfdHJhY2tUcmFucyxfdHJhY2tFdmVudCxfYWRkSWdub3JlZE9yZ2FuaWMsX2FkZElnbm9yZWRSZWYsX2FkZE9yZ2FuaWMsX2NsZWFySWdub3JlZE9yZ2FuaWMsX2NsZWFySWdub3JlZFJlZixfY2xlYXJPcmdhbmljLF90cmFja1NvY2lhbCxfZ2V0Q2xpZW50SW5mbyxfZ2V0RGV0ZWN0Rmxhc2gsX2dldERldGVjdFRpdGxlLF9zZXRDbGllbnRJbmZvLF9zZXREZXRlY3RGbGFzaCxfc2V0RGV0ZWN0VGl0bGUsX2dldExvY2FsR2lmUGF0aCxfZ2V0U2VydmljZU1vZGUsX3NldExvY2FsR2lmUGF0aCxfc2V0TG9jYWxSZW1vdGVTZXJ2ZXJNb2RlLF9zZXRMb2NhbFNlcnZlck1vZGUsX3NldFJlbW90ZVNlcnZlck1vZGUsX3RyYWNrUGFnZUxvYWRUaW1lLF9hZGREZXZJZCcpO2FiVHJrci5fbGluaz1fX3V0bUxpbmtlcj1mdW5jdGlvbihsKXtpZihsKWxvY2F0aW9uLmhyZWY9bDt9O2lmKHR5cGVvZih1cmNoaW5UcmFja2VyKT09J3VuZGVmaW5lZCcpdXJjaGluVHJhY2tlcj1hYk5vT3A7 because another extension (uBlock Origin) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CgkvLwoJdmFyIEdhcSA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglHYXEucHJvdG90eXBlLk5hID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5PID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5TYSA9IG5vb3BmbjsKCUdhcS5wcm90b3R5cGUuVGEgPSBub29wZm47CglHYXEucHJvdG90eXBlLlZhID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fY3JlYXRlQXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0QXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5wdXNoID0gZnVuY3Rpb24oYSkgewoJCWlmICggdHlwZW9mIGEgPT09ICdmdW5jdGlvbicgKSB7CgkJCWEoKTsgcmV0dXJuOwoJCX0KCQlpZiAoIEFycmF5LmlzQXJyYXkoYSkgPT09IGZhbHNlICkgewoJCQlyZXR1cm47CgkJfQoJCS8vIGh0dHBzOi8vdHdpdHRlci5jb20vY2F0b3ZpdGNoL3N0YXR1cy83NzY0NDI5MzAzNDUyMTgwNDgKCQkvLyBodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9hbmFseXRpY3MvZGV2Z3VpZGVzL2NvbGxlY3Rpb24vZ2Fqcy9tZXRob2RzL2dhSlNBcGlEb21haW5EaXJlY3RvcnkjX2dhdC5HQV9UcmFja2VyXy5fbGluawoJCWlmICggYVswXSA9PT0gJ19saW5rJyAmJiB0eXBlb2YgYVsxXSA9PT0gJ3N0cmluZycgKSB7CgkJCXdpbmRvdy5sb2NhdGlvbi5hc3NpZ24oYVsxXSk7CgkJfQoJfTsKCS8vCgl2YXIgdHJhY2tlciA9IChmdW5jdGlvbigpIHsKCQl2YXIgb3V0ID0ge307CgkJdmFyIGFwaSA9IFsKCQkJJ19hZGRJZ25vcmVkT3JnYW5pYyBfYWRkSWdub3JlZFJlZiBfYWRkSXRlbSBfYWRkT3JnYW5pYycsCgkJCSdfYWRkVHJhbnMgX2NsZWFySWdub3JlZE9yZ2FuaWMgX2NsZWFySWdub3JlZFJlZiBfY2xlYXJPcmdhbmljJywKCQkJJ19jb29raWVQYXRoQ29weSBfZGVsZXRlQ3VzdG9tVmFyIF9nZXROYW1lIF9zZXRBY2NvdW50JywKCQkJJ19nZXRBY2NvdW50IF9nZXRDbGllbnRJbmZvIF9nZXREZXRlY3RGbGFzaCBfZ2V0RGV0ZWN0VGl0bGUnLAoJCQknX2dldExpbmtlclVybCBfZ2V0TG9jYWxHaWZQYXRoIF9nZXRTZXJ2aWNlTW9kZSBfZ2V0VmVyc2lvbicsCgkJCSdfZ2V0VmlzaXRvckN1c3RvbVZhciBfaW5pdERhdGEgX2xpbmsgX2xpbmtCeVBvc3QnLAoJCQknX3NldEFsbG93QW5jaG9yIF9zZXRBbGxvd0hhc2ggX3NldEFsbG93TGlua2VyIF9zZXRDYW1wQ29udGVudEtleScsCgkJCSdfc2V0Q2FtcE1lZGl1bUtleSBfc2V0Q2FtcE5hbWVLZXkgX3NldENhbXBOT0tleSBfc2V0Q2FtcFNvdXJjZUtleScsCgkJCSdfc2V0Q2FtcFRlcm1LZXkgX3NldENhbXBhaWduQ29va2llVGltZW91dCBfc2V0Q2FtcGFpZ25UcmFjayBfc2V0Q2xpZW50SW5mbycsCgkJCSdfc2V0Q29va2llUGF0aCBfc2V0Q29va2llUGVyc2lzdGVuY2UgX3NldENvb2tpZVRpbWVvdXQgX3NldEN1c3RvbVZhcicsCgkJCSdfc2V0RGV0ZWN0Rmxhc2ggX3NldERldGVjdFRpdGxlIF9zZXREb21haW5OYW1lIF9zZXRMb2NhbEdpZlBhdGgnLAoJCQknX3NldExvY2FsUmVtb3RlU2VydmVyTW9kZSBfc2V0TG9jYWxTZXJ2ZXJNb2RlIF9zZXRSZWZlcnJlck92ZXJyaWRlIF9zZXRSZW1vdGVTZXJ2ZXJNb2RlJywKCQkJJ19zZXRTYW1wbGVSYXRlIF9zZXRTZXNzaW9uVGltZW91dCBfc2V0U2l0ZVNwZWVkU2FtcGxlUmF0ZSBfc2V0U2Vzc2lvbkNvb2tpZVRpbWVvdXQnLAoJCQknX3NldFZhciBfc2V0VmlzaXRvckNvb2tpZVRpbWVvdXQgX3RyYWNrRXZlbnQgX3RyYWNrUGFnZUxvYWRUaW1lJywKCQkJJ190cmFja1BhZ2V2aWV3IF90cmFja1NvY2lhbCBfdHJhY2tUaW1pbmcgX3RyYWNrVHJhbnMnLAoJCQknX3Zpc2l0Q29kZScKCQldLmpvaW4oJyAnKS5zcGxpdCgvXHMrLyk7CgkJdmFyIGkgPSBhcGkubGVuZ3RoOwoJCXdoaWxlICggaS0tICkgewoJCQlvdXRbYXBpW2ldXSA9IG5vb3BmbjsKCQl9CgkJb3V0Ll9nZXRMaW5rZXJVcmwgPSBmdW5jdGlvbihhKSB7CgkJCXJldHVybiBhOwoJCX07CgkJcmV0dXJuIG91dDsKCX0pKCk7CgkvLwoJdmFyIEdhdCA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglHYXQucHJvdG90eXBlLl9hbm9ueW1pemVJUCA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuX2NyZWF0ZVRyYWNrZXIgPSBub29wZm47CglHYXQucHJvdG90eXBlLl9mb3JjZVNTTCA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuX2dldFBsdWdpbiA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuX2dldFRyYWNrZXIgPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gdHJhY2tlcjsKCX07CglHYXQucHJvdG90eXBlLl9nZXRUcmFja2VyQnlOYW1lID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIHRyYWNrZXI7Cgl9OwoJR2F0LnByb3RvdHlwZS5fZ2V0VHJhY2tlcnMgPSBub29wZm47CglHYXQucHJvdG90eXBlLmFhID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5hYiA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuaGIgPSBub29wZm47CglHYXQucHJvdG90eXBlLmxhID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5vYSA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUucGEgPSBub29wZm47CglHYXQucHJvdG90eXBlLnUgPSBub29wZm47Cgl2YXIgZ2F0ID0gbmV3IEdhdCgpOwoJd2luZG93Ll9nYXQgPSBnYXQ7CgkvLwoJdmFyIGdhcSA9IG5ldyBHYXEoKTsKCShmdW5jdGlvbigpIHsKCQl2YXIgYWEgPSB3aW5kb3cuX2dhcSB8fCBbXTsKCQlpZiAoIEFycmF5LmlzQXJyYXkoYWEpICkgewoJCQl3aGlsZSAoIGFhWzBdICkgewoJCQkJZ2FxLnB1c2goYWEuc2hpZnQoKSk7CgkJCX0KCQl9Cgl9KSgpOwoJd2luZG93Ll9nYXEgPSBnYXEucWYgPSBnYXE7Cn0pKCk7.

#### Extension Version: 
 - Blur 6.6.2235

#### Browswer Version: 
 - Google Chrome Version 54.0.2840.71

**Comment by gorhill** [comment]
Duplciate of #1170.
