### ISSUE TITLE
Failed by default, page opens then closes

### ISSUE THREAD

**Issue by extioStorm** [gorhill/uBlock#2115]
### Describe the issue
I use a website called dealnews. As can be expected, it is riddled with ADs because to some degree... well thats what im there for.

Anyway on most of these ublock origin does well, but when i try to open certain pages it opens in a new tab and instantly closes the tab. if i disable it for the page im on, it will open the page where it allows me to temporarily allow the new page to load.

http://dealnews.com/Alienware-Skylake-i7-16-Laptop-w-6-GB-GPU-for-1-323-free-shipping/1821827.html

click the shop now button, or the link to the product. this page will likely expire in a short amount of time, such is the nature of this website's listings.

is it possible to fix this behavior to allow me to temporarily allow the page without disabling the adblocker?

### One or more specific URLs where the issue occurs

http://dealnews.com/Alienware-Skylake-i7-16-Laptop-w-6-GB-GPU-for-1-323-free-shipping/1821827.html

### Steps for anyone to reproduce the issue

1. visit the page before the ad expires
2. with origin turned on, click the shop now, or the url to the alienware laptop.
3. watch tab open then insta-close

### Your settings

default settings with antiadblockkiller running

- Browser/version: Version 54.0.2840.71 m (64-bit)
- uBlock Origin version: uBlock Origin v1.9.16

##### Your filter lists

default with Anti-AdblockKiller Reek enabled

**Comment by Atavic** [comment]
Have you tried whitelisting `https://adfarm.mediaplex.com/`

**Comment by extioStorm** [comment]
i could manually fix this im sure, but im just wondering is it a bug that is causing the insta-close? is that supposed to happen?  shouldnt it give the option to temporarily allow the page?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
For whoever is tempted to open filter list-related issues without first using the logger:

![a](https://cloud.githubusercontent.com/assets/585534/19897654/343b71e4-a02f-11e6-98f8-544cf9675d20.png)
