### ISSUE TITLE
Add Block Detection

### ISSUE THREAD

**Issue by ribata** [gorhill/uBlock#2120]
I am using latest versions Firefox and uBlock and I have the most the 3-rd part filters to prevent the websites to recognize the uBlock like Fanboy+Easylist-Merged Ultimate List‎ and Anti-Adblock Killer | Reek‎..... But on some websites I have warning to remove uBlock.

Example http://www.bg-gledai.tv/online-bnt

Any help will be appreciate.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
