### ISSUE TITLE
Can't seem to permanently disable an element on a specific page or the entire website?

### ISSUE THREAD

**Issue by Wild-Dog** [gorhill/uBlock#2121]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Blocking an element with the element picker doesn't keep said element from returning upon refresh.

### One or more specific URLs where the issue occurs
https://www.youtube.com/watch?v=L1aUcgGVPlk
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
After Element picking:  https://postimg.org/image/dahdb0525/

After Page Refresh: https://postimg.org/image/h9oqohzgd/
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Open Google Chrome

2. Go to any website

3. Block a visible element using the element picker

4. Refresh the page to observe that blocked element returns.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 54.0.2840.87 m
- uBlock Origin version:  1.9.16

##### Your filter lists

"All default and included Third Party filter lists"

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Wild-Dog** [comment]
I hope I got this one right.

**Comment by gorhill** [comment]
You absolutely did not make the case there is an issue with uBO. What filter was generated by uBO? Is that filter shown by the logger to be applied to the page? Is cosmetic filtering disabled in any way for that page?

**Comment by Wild-Dog** [comment]
Sorry. May I try again?

**Comment by gorhill** [comment]
There, I make the case that your issue is invalid:

![a](https://cloud.githubusercontent.com/assets/585534/19936541/218989c6-a0f4-11e6-8d99-10b68e2f0662.png)

**Comment by Wild-Dog** [comment]
... I see.

I'm just wondering, have you considered taking on volunteers?

**Comment by anewuser** [comment]
@Wild-Dog This is an open source project maintained as a hobby. Everybody ever involved is a volunteer.  

Please post only comments related to bugs here. For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by rjkpa** [comment]
This one works too - `youtube.com##.yt-uix-button[data-trigger-for="action-panel-share"]`

**Comment by h1z1** [comment]
Possibly related but I can reproduce this fairly easily on images.  They will be blocked initially but will reappear on either refresh (the exact type of refresh isn't clear).  That is until I force a cacheless refrsh (ctrl-shift-r).  Drives me insane when there are many images I've blocked and the page reloads.

Example:
- Goto imgur.com
- right click on any image, UB block element
- create default filter (||i.imgur.com/fuzzycats.jpg)
- confirm filter is set in My Filters

Image is gone.  Refresh, image returns.

**Comment by rjkpa** [comment]
^^
Not reproducible and also ||i.imgur.com is a network filter not a cosmetic filter.

**Comment by gorhill** [comment]
Closing due to lack of feedback: OP was unable to make the case -- simply providing the specific filter which was supposedly not working + logger output + the value of all settings which can affect cosmetic filtering was the minimal amount of information -- none of which was provided. Assuming OP overlooked a setting on his side.

**Comment by h1z1** [comment]
You're ridiculous..

**Comment by gorhill** [comment]
> You're ridiculous

This is noise. Logger output providing evidence of your filters not being applied would have been more productive.

Forced to lock issue due to noise.
