### ISSUE TITLE
Block popovers by default

### ISSUE THREAD

**Issue by nekohayo** [gorhill/uBlock#2124]
Hi there, one of the remaining pests on the web are popovers. The kind of things that show up as overlays while you scroll down pages, prompting you to subscribe to Yet Another Mailing List.

Have you considered using https://github.com/mistalaba/popover-blocklist in ublock's default set of blocklists?

**Comment by lewisje** [comment]
Inform the maintainer of filterlists.com and it might make it to V2 of the site; also mention it on the adblockplus.org forums, and it might get added to the set of known filter-lists.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1505#issuecomment-201813860
