### ISSUE TITLE
Network Trojan Detected in snort

### ISSUE THREAD

**Issue by Fobio** [gorhill/uBlock#2125]
Behind a pfsense router/firewall and I've been reviewing my firewall logs and 3 out of 4 PC's are running uBlock Origin and of the 3, 2 run it in Chrome.  I've noticed that the 2 PC's that run uBlock in Chrome is triggering a NETWORK TROJAN warning, with a dest ip of 213.230.210.230 port 443.  The 3rd PC runs a VPN and all traffic is routed through it, so it is bypassing the firewall. I've searched online and found that the trigger is that IP being associated with a botnet C&C server and triggering an alert.  

https://feodotracker.abuse.ch/host/213.230.210.230/

I initially thought that I was infected with malware that is connecting to the botnet server and I didn't find much online. After some more digging, I've found that dest ip of 213.230.210.230 port 443 may be the location of a host file for uBlock.  But I can not confirm this.  I'd like to confirm whether this is the case so I can put my mind at ease and disable the rule in snort.

IP: 213.230.210.230
Port: 443
URL: boo.yoyo.org

Chrome version: Version 54.0.2840.87 m (64-bit)
uBlock Origin version: uBlock Origin v1.9.16
Default filter list
No custom filters

**Comment by seanrand** [comment]
> $ host pgl.yoyo.org
> pgl.yoyo.org has address 213.230.210.230

So it is https://pgl.yoyo.org/adservers/

**Comment by DrunkenSasquatch** [comment]
False positive. 
This IP belongs to the `Peter Lowe’s Ad server list` which you obviously have checked.

The links for the lists can be found [here](https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json#L233).

**Comment by gorhill** [comment]
Asnwered by @DrunkenSasquatch.

**Comment by gorhill** [comment]
@pgl Are you aware of this?

**Comment by pgl** [comment]
@gorhill Looking into it now.

**Comment by pgl** [comment]
Seems that another site on the shared host may have been compromised.

**Comment by pgl** [comment]
This issue should have been resolved by now, but I'll keep an eye on things.

**Comment by Fobio** [comment]
Cool. Thank you the updates guys!

**Comment by mateidavid** [comment]
I wanted to point out that today (Nov 14), the IP of `pgl.yoyo.org` is still on the Talos IP blacklist: http://www.talosintelligence.com/feeds/ip-filter.blf .

From the POV of uBlock Origin, is there a document/resource explaining what damage (if any?) a compromised block list can cause?

**Comment by pgl** [comment]
@mateidavid I'm afraid that's indicative of an out-of-date blocklist. Confirmation was received from abuse.ch on November 11 that yoyo.org was delisted.

**Comment by pgl** [comment]
I've sent a delisting request anyway, but it doesn't look like a very well updated list.

**Comment by mateidavid** [comment]
Thanks, and thanks for the list!

**Comment by pgl** [comment]
Confirmation received that the entry should be expired now. I checked the list and yoyo's IP isn't there.

**Comment by Sinderan** [comment]
I know this is closed but I wanted to comment that OpenDNS is still blocking yoyo. We use the OpenDNS Umbrella services for out managed business clients and I've been getting botnet alerts from everyone. I raised a ticket with them yesterday about a potential False Positive. and just got the response this morning.

 
Michael Coleman (Umbrella) 
Nov 16, 14:23 PST 
Hello,
Thank you for contacting OpenDNS. This IP was picked up on November 2nd by our Security team for involvement in botnet activity. The botnet classification is still relevant today and will remain in our block list for the time being.
Let me know if you have any further questions.
Best regards,
Michael Coleman
Customer Support Representative
Cisco Umbrella

**Comment by pgl** [comment]
@Sinderan Do you have a contact I can use?

**Comment by Sinderan** [comment]
@pgl I edited my profile so it shows my email now.

**Comment by pgl** [comment]
I've sent a support request. No idea how it's "still relevant today".

@Sinderan Sorry for not being clear; I meant to ask if you had a contact at OpenDNS I could use. No need to show your email if you don't want to.

**Comment by Sinderan** [comment]
@pgl No I don't, I just raised a support ticket from within the portal.

No worries! I don't really care, just didn't realize it was hidden to begin with.

**Comment by pgl** [comment]
@Sinderan After a bit of back-and-forth with OpenDNS, this issue has been referred to their research analysts.

**Comment by pgl** [comment]
@Sinderan Finally:

> Thank you for your patience, most of our research team was off for the Thanksgiving holiday so we just received the update. We have removed 213.230.210.230 from our IP block list. boo.yoyo.org for example is resolving correctly on our network. Let us know if your user is still reporting any issues.
