### ISSUE TITLE
General failure with dev version 1.9.17b3.

### ISSUE THREAD

**Issue by rumorumo** [gorhill/uBlock#2126]
Chrome 31.0.1650.63 (on Windows XP) and uBlock 1.9.17b3 (using medium mode).

Maybe it's me and my obsolete Chrome again, but things have gone weird here. The dashboard tabs freeze after making a change, so that it's necessary to go to another tab and come back. Custom filters can't be used. The new "_Advanced settings_" pane is empty. And most important: usual blocking doesn't seem to work anymore.

Here is what the dev console of the extension shows (the first two erros appear when opening the dashboard, the other ones appear when accessing https://googlechromereleases.blogspot.com.br/search/label/Stable%20updates):

![console 1 9 17b3](https://cloud.githubusercontent.com/assets/15052951/20010295/b492983e-a28e-11e6-9464-974f3a296c04.JPG)

Hope it makes some sense...

**Comment by gorhill** [comment]
My bad, with all the changes I completely forgot to test the polyfill code path for `objectAssign()`.
