### ISSUE TITLE
Adv. Settings UI not yet good in Fx (1.9.17b3)

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#2127]
This is Screenshot from Chrome 54.0.2840.87 m (64-bit):

![cr-adv](https://cloud.githubusercontent.com/assets/11355601/20012285/ecefbef8-a2ae-11e6-8f94-aeb06c4c4a63.JPG)
<br />
And here Screenshot from Firefox 49.0.2 (64-bit):

![fx-adv](https://cloud.githubusercontent.com/assets/11355601/20012308/00c9b370-a2af-11e6-995d-a7f282d7ee38.JPG)

**Comment by gorhill** [comment]
I did not upload the new `messages.json` to Crowdin yet.

**Comment by Alpengreis** [comment]
Alright, then all is clear.
