### ISSUE TITLE
[question] Support WebSocket in WebRequest API

### ISSUE THREAD

**Issue by skarsgal** [gorhill/uBlock#2129]
I am using Chromium 56.0.2907.0 (64 bit) with uBlock Origin 1.9.17b4 on XXX sites: it do not blocks aggressive advertising from XXX sites for example these of Pornhub NETWORK.

There is an advanced setting for block this advertising ? 
Do You can create a workaround for 'Support WebSocket in WebRequest API' ?

For details about this question see this post on BugReplay http://blog.bugreplay.com/post/152579164219/pornhubdodgesadblockersusingwebsockets

Thanks

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
gorhill long ago made a companion extension to deal with filtering WebSocket connections (originally his implementation was part of the base extension, but it caused some subtle issues): https://github.com/gorhill/uBO-WebSocket#ubo-websocket
