### ISSUE TITLE
google notifications unaccesible

### ISSUE THREAD

**Issue by muhasturk** [gorhill/uBlock#213]
![](http://i.imgur.com/o6A6CIy.png)

**Comment by gorhill** [comment]
Can't reproduce using provided details.

**Comment by muhasturk** [comment]
uBlock 0.9.7.0
Google Chrome  Version 42.0.2311.152 (64-bit)
OSX 10.10.3

What should I provide any info?

**Comment by muhasturk** [comment]
Ok it seems this problem doesn't relevant with uBlock even removed uBlock from Chrome, problem still exist. Sorry
