### ISSUE TITLE
uBO doesn't apply SPECIFIC blocking filters where a wild card character like * is used instead of a TLD

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#2133]
**Describe the issue**

uBO doesn't apply SPECIFIC blocking filters where a wild card character like * is used instead of a TLD, for example `||$third-party,domain=google.*` or `||$third-party,domain=google.*,important`

**One or more specific URLs where the issue occurs**

https://www.google.com/

**Screenshot in which the issue can be seen**

https://i.gyazo.com/5af8ebbdb3b1cb642e6f154fa45d5c64.png

**Steps for anyone to reproduce the issue**

1.) Open uBO Dashboard, add this filter - `||$third-party,domain=google.*` or `||$third-party,domain=google.*,important`.

2.) Browse to `google.com` and open the logger.

3.) Notice that third party domains `googleusercontent.com` and `gstatic.com` are not blocked by either of the filters and the filter itself is NOT applied by uBO.

**Your settings**

- Default
- Browser/version: Chromium 56
- uBlock Origin version: 1.9.16

**Your filter lists**

- Default

**Comment by gorhill** [comment]
> uBO doesn't apply SPECIFIC blocking filters

Because it's not a supported syntax: [Options in blocking rules](https://adblockplus.org/filter-cheatsheet#options). Nowhere in the documentation here or ABP's one is there a mention that such syntax is valid.

**Comment by rjkpa** [comment]
So I need to add each and every domain individually ? Also is the syntax for blocking based on ABP ?
