### ISSUE TITLE
Ublock Origin disabled when FF upgraded to v49.

### ISSUE THREAD

**Issue by bulrush15** [gorhill/uBlock#2137]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

FYI: I upgraded Firefox v47.0.2 to v49 and Ublock Origins was disabled. I uninstalled Ublock and reinstalled it and it runs fine now. 

Why was UO 1.9.0 disabled? Does every version of every plugin have to be verified by Mozilla for every version of Firefox? So UO 1.9.0 was not verified with FF v49? Is that what happened?

### One or more specific URLs where the issue occurs

n/a

### Screenshot in which the issue can be seen

n/a

### Steps for anyone to reproduce the issue

1. Install FF 47.0.2. 
2. Upgrade FF to version 49.0.2. 
3. UO should be disabled by the upgrade process. 
4. Remove UO from FF and restart FF. 
5. Reinstall UO and UO should work fine now. 

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: v47.0.2 to v49.0.2
- uBlock Origin version: v1.9.0

##### Your filter lists

n/a

##### Your custom filters (if any)

n/a

**Comment by gorhill** [comment]
> Why was UO 1.9.0 disabled?

I don't know. From where did you install it? Did you tamper the source code after you installed it the first time? Signed extensions will be automatically disabled if the content of the package does not match the signature.

**Comment by gorhill** [comment]
Did you actually really reproduce the issue with your repro steps?

**Comment by gorhill** [comment]
Going to close this, there is no other report of this happening, so you will have to investigate on your side what caused this.
