### ISSUE TITLE
Can UBO block websites from accessing ressource:// links on Firefox?

### ISSUE THREAD

**Issue by zorates** [gorhill/uBlock#2138]
"Any website can access a selection of Firefox resource files to find out more about the web browser."
Found here: https://redd.it/5c4082
Which links to this article: http://www.ghacks.net/2016/06/12/firefox-resource-leak/

This can be seen in action on https://www.browserleaks.com/firefox

So I was wondering if it might be possible to somehow block these requests in UBO instead of installing a separate addon.

**Comment by gorhill** [comment]
Best is to install a separate extensions, or ask extension authors with the the issue to address it.

**Comment by DrunkenSasquatch** [comment]
@zorates You have to install this addon.

https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/
