### ISSUE TITLE
Compatible with Google Datasaver?

### ISSUE THREAD

**Issue by johnathonm1981** [gorhill/uBlock#2139]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I can't seem to get Google Data saver to "save" me any data when using both the main ublock app and the secondary UBO app. I will list all the specs below.

https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac?hl=en

Are they compatible? Is there a way or work around for me to set them up to work together?

### One or more specific URLs where the issue occurs
https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac?hl=en or https://support.google.com/chrome/answer/2392284?visit_id=0-636144011111195750-2954189020&p=data_saver_off&rd=1
  
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Windows 10 x64 build 10.0.4393 Professional.

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

Chrome Version 54.0.2840.99 m (64 bit)
https://support.google.com/chrome/answer/2392284?visit_id=0-636144011111195750-2954189020&p=data_saver_off&rd=1
https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac?hl=en
Running Ublock build 1.9.17b7
uBlock Origin Websocket 1.1
Google's Data saver is version 2.0.2
I have Grammarly 8.703.584 installed too.
I have advanced user enabled, show me blocked requests unchecked, disable prefetch and auditing are unchecked, prevent webrtc is checked. Parse cosmetic filters is checked. 

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists
I have all the filters down to regions checked except Easy List with element hiding rules checked. Beyond that I have no additional filters checked. 

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
I have no custom filters. Chrome is running in developer mode. I have also zipped and uploaded all the chrome config stuff to my dropbox here:  

https://dl.dropboxusercontent.com/u/4066386/Uploaded/chrome_config.zip

I have no idea if there is anything else you need but if you do, let me know. Lots of porn in there so watch out ;-)

Thanks!

J

**Comment by gorhill** [comment]
How did you conclude it's a uBO issue and not a filter list issue?

**Comment by gorhill** [comment]
Actually, I will mark this issue as invalid and assume it's a filter list issue. You will have to make the case it's not a filter list issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by johnathonm1981** [comment]
Sorry, I didn't... I thought I posted on the other plugin.
