### ISSUE TITLE
[Firefox] Disabling/Enabling uBlock considerably lowers page load times with E10s

### ISSUE THREAD

**Issue by vlaszlo** [gorhill/uBlock#214]
First of all, thanks for creating uBlock and uMatrix and bringing them to Firefox, it's highly appreciated.

While investigating slower page loads in Firefox with E10s and uBlock, I stumbled on a weird effect. Steps to reproduce:
1. With Nightly 41's profile manager ("firefox -p"), create a new profile, install uBlock.
2. Disable E10s, restart browser. Load "http://numion.com/stopwatch" and measure "http://spiegel.de" a few times. Note page load times.
3. Enable E10s, restart browser. Redo the test a few times. Note that load times have gone up measurably.
4. Open Firefox' Add-ons-Manager, disable and immediately re-enable uBlock. Redo tests. Page load times are now lower again, about on non-E10s level, but only until next browser restart, after which another disable/enable-sequence is needed to bring load times down again.

Before the disable/enable-procedure, the browser console shows lots of "Sending message that cannot be cloned. Are you trying to send an XPCOM object?" warnings during page load. These are gone after the sequence. Other than now loading pages faster, uBlock seems to function normally. uBlock's network logger doesn't show any notable differences either.

The effect is measurable with the network analyzer from Firefox' developer tools, too, and it should be noticeable on any non-basic page that needs a few seconds or more to load. If the page is cached or not doesn't seem to make a difference. On some sites it's more pronounced than on others, but especially the "time-to-first-paint" is lower, which gives a much snappier impression.  

Used versions:
Windows 8.1 Pro 64-bit,
Firefox 41.0a1 (2015-05-18) 64-bit, default settings,
uBlock Origin 0.9.7.5-rc.2, default settings.

I first noticed this about a week ago with my dirty main profile, so the effect seems to exist since quite a while, and the exact software versions and settings don't seem to matter. A current version of main branch uBlock shows it, too, while other extensions like uMatrix or Adblock Plus seem to be unaffected by disabling/enabling.

**Comment by vlaszlo** [comment]
Correction: uMatrix, when used alone, also seems to benefit from disabling/enabling on my system, the page load time reduction is not quite as large as in uBlock's case, however.

When using uBlock together with uMatrix, I get about the same speed gain by applying the procedure to either uMatrix or uBlock, additionally dis-/enabling the other one doesn't bring any further reductions.

**Comment by gorhill** [comment]
Will investigate once 0.9.7.5 stable is released.

**Comment by drbluetongue** [comment]
OK This is very strange. 

After disabling and then enabling, about:performance shows zero cross process traffic from uBlock. 

However, pop-ups are no longer blocked (Noticed this on pop-up heavy sites like TPB

**Comment by gorhill** [comment]
> However, pop-ups are no longer blocked (Noticed this on pop-up heavy sites like TPB

Give me a URL please. Also, always check the logger to find out what happens.

**Comment by drbluetongue** [comment]
Sorry.

Site: thepiratebay. la/top - choose "movies" and a pop up will load and close. Disable/Enable ublock, go back to that site an click the link and more than likely the popup will fully load.

Browser: Nightly Firefox. 
uBlock Version: Latest nightly

I'm at work but will send the logger requests through when I get home in a few hours.

Thanks

**Comment by gwarser** [comment]
How you block popups on tpb? By filter or by rule?

**Comment by gorhill** [comment]
@drbluetongue Ok I don't think it has anything to do with enable/disable, it's a regression bug from fix to #266. Looking into a fix.

**Comment by drbluetongue** [comment]
@gwarser I don't manually do it - they usually pop up then disappear immediately. Must be a rule in one of the subscription

@gorhill Oh cool thanks for that

**Comment by gorhill** [comment]
I opened a separate issue for this to keep track of the specific bug, and to keep track of the exact steps to use to test in the future: <https://github.com/gorhill/uBlock/issues/269>.

**Comment by gorhill** [comment]
@vlaszlo Did your test case involved having a lot of of tabs in the browser? (like, 100s)

**Comment by drbluetongue** [comment]
For me, the e10s CPOWS traffic stops even if I do it from a fresh start, or with 100 tabs.

Anything you'd like me to test?

**Comment by gorhill** [comment]
> "Sending message that cannot be cloned. Are you trying to send an XPCOM object?"

I did see a lot of this yesterday, while I was working on other stuff. I searched to find out what would be the cause and found nothing conclusive. The browser console doesn't report a specific source code file (`<unknown>`), so I suspect this occurs in a sandboxed script (content scripts -- though I still need to learn more about FF stuff), and there is only one place from which messages are sent in there. I will need to investigate more.

**Comment by gorhill** [comment]
Ok I see something:

After launching Nightly, going to any web page will cause script injection to throw, because for some obscure reasons the sandbox seems to be in a bad state, i.e. the javascript interpreter sees `Date.now` as not being a function.

If I disable then re-enable uBlock, there is not more throw. Now is to find what can cause the sandbox to be in a bad state.

**Comment by vlaszlo** [comment]
> @vlaszlo Did your test case involved having a lot of of tabs in the browser? (like, 100s)

No. I used as few tabs as possible for testing, mostly just one.

> ...for some obscure reasons the sandbox seems to be in a bad state, i.e. the javascript interpreter sees Date.now as not being a function.

I remember seeing that as well, but I couldn't make any sense of it, because the code in the file linked from the Browser Console seemed syntactically correct. Funnily, I haven't yet seen that error in the Browser Console today with uBlock Origin 0.9.8.4-dev.3 and the June-3-nightly of Firefox, while the CPOW / load time peculiarities are still there.

Interestingly, uMatrix and Deathamns' [Viewhance] (https://addons.mozilla.org/de/firefox/addon/viewhance/) both show the same behavior as uBlock (shorter load times and zero CPOW usage in about:performance after dis-/enabling), while a few other restartless Add-Ons that I tested like Adblock Plus were unaffected. Could it be a systematic problem in similar or identical code parts?

In Viewhance's case, I see an "Object.create is not a function"-error today, but only on some web pages. For example I'm having it on [Spiegel Online] (http://spiegel.de), but not on the [VIM Color Scheme Test] (http://vimcolorschemetest.googlecode.com/svn/html/index-c.html). That could substantiate the suspicion that there's a timing problem at play here. On the other hand... is interpreting JavaScript code of an extension without having the ECMA standard objects available not a browser bug?

**Comment by vlaszlo** [comment]
Sorry for the spam... wrong button.

**Comment by gorhill** [comment]
I am still investigating. It has something to do with browser launch only, issue disappear if manually enabling the addon after startup, or if disabling/enabling like you found out. All is the same code, so I suspect there is some quirks with FF API at launch time.

**Comment by drbluetongue** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1171173

Have filed a bug here gorhill. With e10s bugs they are usually pretty prompt.

**Comment by gorhill** [comment]
Thanks, I was about to do this, I am really at the end f my wits as to why this happens. Since they know the code, just reading the symptoms they may have an idea right away of why this happens.

**Comment by Gitoffthelawn** [comment]
@drbluetongue You got a quick confirmation of the bug from Alice White, a very, very talented developer.

**Comment by drbluetongue** [comment]
@Gitoffthelawn Alice is usually very fast at confirming bugs that I've created - Mozilla is great at turn-around especially with e10s bugs as its top priority for them

**Comment by Gitoffthelawn** [comment]
@drbluetongue It's great for uBlock Origin that it got confirmed to fast.  Alice has already published a regression window.  I submitted a few non-e10s bugs months ago that haven't been triaged.  Any tips to get non-e10s bugs noticed?

**Comment by drbluetongue** [comment]
Usually when I file a bug its to do with whatever nightly build regression I've noticed. I'm active on mozillazine forums and post it there to see if anyone else is experiencing it before filing the bug, if I get confirmation I file the bug and then post it in the relevant thread.

Alice is a regular on the forums so I guess she picks up trends of "me too" but I never really tried to find a way to get noticed or anything. I still have bugs sitting in triage, mostly to do with Android Firefox.

**Comment by atlanto** [comment]
Here is the root bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1172888
prefs.js is loaded wrongly about extensions.bootstrappedAddons(multiprocessCompatible=false).
So firefox treats uBlock as a legacy(?) addon, then e10s module interferes with uBlock.

"interfere" means,
>Sending message that cannot be cloned. Are you trying to send an XPCOM object?

warning spamming in browser console,
>Date.now is not a function

(at frameModule.js#L349)
caused by bad calling from inappropriate module.

Disabling/Enabling cleans up and starts uBlock normally as expected(multiprocess compatible).
If bug 1172888 will be fixed, this problem will be solved.

**Comment by gorhill** [comment]
> Here is the root bug.
> https://bugzilla.mozilla.org/show_bug.cgi?id=1172888

Nice find, this should speed up resolution.

**Comment by drbluetongue** [comment]
Looks like this has been pushed out for next nightly:

https://bugzilla.mozilla.org/show_bug.cgi?id=1171173#c12

**Comment by vlaszlo** [comment]
This issue is confirmed fixed in today's nightly (2015-07-08), so I'm closing this. Thanks, all.
