### ISSUE TITLE
Possibly new filter lists: "Blockzilla", "Czech List" and "Estonian filters by Gurud.ee"

### ISSUE THREAD

**Issue by uBlocking** [gorhill/uBlock#2140]
<https://adblockplus.org/subscriptions> lists seven subscriptions not included in the 3rd party filters section of uBlock Origin. Of these seven, I can find references to four in this repository along with an explanation of why you will not include it. The remaining three may be "new", so I have listed them below for (temporary) completeness.

* "Blockzilla" (<https://zpacman.github.io/Blockzilla/>)
* "Czech List" (<http://dajbych.net/adblock/>)
* "Estonian filters by Gurud.ee" (<http://gurud.ee/>)

Browser/version: Chromium 53.0.2785.143
uBlock Origin version: 1.9.16

**Comment by Atavic** [comment]
I upvote Blockzilla 'unbloated and slim list' idea.

**Comment by IDKwhattoputhere** [comment]
Blockzilla contains some critical filters like:
`||connect.facebook.net^$third-party`
Guaranteed to cause breakage. Many websites use Facebook Connect to provide an option for users to login using their Facebook account (not saying that's a good idea).

**Comment by zpacman** [comment]
As of Blockzilla Version B20 `||connect.facebook.net^$third-party` has been removed. As for the other filters mentioned, no issues have been reported however if issues arise I will whitelist or remove accordingly.

**Comment by Czech123** [comment]
> "Czech List" (http://dajbych.net/adblock/)
Old (modified in 2014 for the last time).

**Comment by TerrakionSmash** [comment]
Adguard's Mobile Ads could be a good alternative. I just hope there are more empirical comparisons between filter lists.

**Comment by gorhill** [comment]
> Adguard's Mobile Ads could be a good alternative

Currently there is no infrastructure in uBO to auto-select a list at install time according to whether a browser is a mobile version or not. Idea is interesting though.

Adguard Japanese is interesting given how overzealous the current one in uBO is, but I don't see recent commits in there: <https://github.com/AdguardTeam/AdguardFilters/tree/master/JapaneseFilter/sections>, last time was 5 months ago.

**Comment by TerrakionSmash** [comment]
There's also the question of if Mobile Ads is supposed to be a standalone filter. If I remember correctly, Adguard Mobile enables Adguard Mobile filters alongside Adguard English.
