### ISSUE TITLE
Twitch.tv's new unblockable SureStream ads

### ISSUE THREAD

**Issue by VirtuallyJesse** [gorhill/uBlock#2141]
Twitch is rolling out new ads specifically designed to circumvent ad blocking. As I understand it these ads are behaviorally the same as the streaming content you are watching - injected directly into the video stream itself. [Blog announcement article here.](https://blog.twitch.tv/introducing-surestream-for-a-better-video-ad-experience-on-twitch-3ca5ce3287c#.8j4xcd5iu)

The new advertising platform is apparently opt-in, but you can find most popular/high viewer [broadcasters](https://www.twitch.tv/directory/all) using these 'Surestream' ads. Example URL Broadcaster > [nl_kripp](https://www.twitch.tv/nl_kripp) 

Over time it will be made available for **every** broadcaster to utilize. I understand these unblockable ads may be difficult to spot as its not clear who is using them and the broadcaster has to manually play the ad themselves.

The pre-roll intro ad remains blockable, but these new ones - issued/controlled by the live broadcaster - aren't. I was hoping to call attention to this issue, as nobody can seem to find a bypass, or if its even possible. 

Lastly I wanted to apologize if this is the incorrect place, as I'm not sure if this falls under uBlock or a 3rd party filter issue. I visisted a few filter web

- Browser/version: Chrome 54.0.2840.71 m (64-bit)
- uBlock Origin version: uBlock Origin 1.9.16

**Comment by Nojevah** [comment]
Pls give a link where you see ads, cause rules:
**ALWAYS INCLUDE A SPECIFIC URL WHERE THE ISSUE OCCURS, even if "it happens everywhere"**.
FYI, I clicked on nl_kripp link, and did not see ads.

**Comment by VirtuallyJesse** [comment]
Sure, another example broadcaster using these ads as of this very moment is > https://www.twitch.tv/eleaguetv

 If you are unfamiliar with Twitch, it is a livestreaming website and the streamer issues the advertisements manually during the live stream.

You can find most popular broadcasters (high viewer count) using the SureStream ads. You can view these broadcasters at the directory page https://www.twitch.tv/directory/all

It is difficult to provide a precise example as the broadcaster needs to be live, and then manually play the ad. There is also difficulty as it is not clear who is currently using them and who is currently using the old ads.

Perhaps this issue is best left until the rollout is complete and more broadcasters are utilizing these SureStream ads. I just wanted to fix the issue before it got bigger and started affecting more uBlock users.

**Comment by Hrxn** [comment]
Well, if the ads are actually part of the stream, there's nothing that can be done anyway.
Except for video processing (in real-time), but that is a completely different beast.

**Comment by gorhill** [comment]
Until it is determined there are missing parts in uBO to filter something, **all** filter list issues must be reported on uAssets -- and with reproducible steps with minimal guessing for whoever will volunteer to investigate this.
