### ISSUE TITLE
Quickly access 'behind the scene' blocking menu

### ISSUE THREAD

**Issue by Lichtenshtein** [gorhill/uBlock#2143]
1) I quite often use the behind the scene blocking feature and i have a long-simmering question. How to quickly access the 'behind the scene' blocking menu? Long-long ago it was pretty easy: click on extension icon → open logger → choose 'behind the scene' → click extension icon again.
But now when i do this actions this strange menu appears, i don't even know what it does and shows. 
![1](https://cloud.githubusercontent.com/assets/13855295/20221509/a9b751ac-a842-11e6-9438-9393956fd917.jpg)
So, to open the 'real' behind the scene menu i need to do these steps:
click on extension icon → open logger → choose 'behind the scene' → wait(!) for any behind the scene action so it will appear in the logger, then → click on the 'eye' → and only then the menu i need will appear. 
![2](https://cloud.githubusercontent.com/assets/13855295/20221510/a9bae63c-a842-11e6-82f7-2fecbceaf17b.jpg)
I don't know if it's an issue or not, but this situation continues from version to version for a very, very long time. This may be a function that very few people use and that's why the problem(?) persists. Or maybe i'm just doing something wrong and there's a way to get into this menu easier and faster.

2) I have a script that shows site icons near the links on the web pages. But sadly, when the 3rd party blocking is enabled, all requests are blocked even if the images are allowed. How can i dynamically allow favicons for all sites, or it's impossible to do? I'm not good at regular expressions, but i tried many rules such as 
![4](https://cloud.githubusercontent.com/assets/13855295/20221788/ca69b09c-a843-11e6-87e4-11a26030f0e3.jpg)
and it didn't work.
![3](https://cloud.githubusercontent.com/assets/13855295/20221511/a9bf1496-a842-11e6-8ab7-3a4cd8d626a9.jpg)

**Comment by uBlock-user** [comment]
In regards to #2, add this filter - @@/favicon$image,important

**Comment by gorhill** [comment]
> add this filter - `@@/favicon$image,important`

Important does not apply to _allow_ filters. Broadly blocking behind-the-scene filters has consequences as stated in the documentation, this is one of them. This may work: `@@/favicon$image,domain=behind-the-scene`. Still, a filter issue, and moreover as a result of using specific dynamic rules -- this is not the place for this as there is no issue with uBO.

**Comment by gorhill** [comment]
To access the behind-the-scene popup:

Chromium: `chrome-extension://pbffolnficoggnnamkphaffidiafpeaf/popup.html?tabId=-1&fullsize=1`.

Firefox: `chrome://ublock0/content/popup.html?tabId=-1&fullsize=1`.
