### ISSUE TITLE
Website not loading properly

### ISSUE THREAD

**Issue by kajal09** [gorhill/uBlock#2144]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Only the text elements load and nothing else.
It loads up perfectly if uBlock is disabled.
![not loading](https://cloud.githubusercontent.com/assets/22082120/20234951/74fe4c16-a853-11e6-916e-5e71e6b6d7f0.png)
 

### One or more specific URLs where the issue occurs

http://the-watch-series.to/

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
I've never changed any setting so just use default setting.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version:  Chrome Version 54.0.2840.71 m
- uBlock Origin version: uBlock 1.9.16

##### Your filter lists

Default setting 

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
