### ISSUE TITLE
Popup Blocker blocks opening New Tab

### ISSUE THREAD

**Issue by Nerdy314159265** [gorhill/uBlock#2145]
I recently switched Popup Blocking to be on for all sites by default, so that I don't have to add a specific site to get protection from malicious popups. However, one caveat of this is that for some reason uBlock will block a new tab from opening via Middle-Mouse or the Context Menu. This issue seems to vary from site to site. 

On Google: It would auto-close any new tabs made

On Github: It would allow new tabs but would disallow the "Search Google for" tabs.

Steps to Reproduce:

1. Add "no-popups: * true" to your filter rules
2. Try opening new tabs via the Middle-Mouse hotkey or Context Menu options on various sites

Settings:
no-popups: * true
* * 3p block
* * 3p-frame block
* * 3p-script block
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop

- Browser/version: Version 54.0.2840.71 m
- uBlock Origin version: 1.9.16

My Filter List:

uBlock Filters - Experimental
EasyList + Peter Lowe’s Ad server list‎
All Privacy
All Malware Domains
All Social

**Comment by gorhill** [comment]
[No popups](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups):

> **Caveat for Chromium-based browsers:** Due to Chromium API limitations, it's not always possible for uBlock to determine for sure whether a new tab being opened is that of a popup, or is the result of a legitimate click on a link by the user. So if the no-popups switch is in use, you may not be able to open a link in a new tab through the context menu.

**Comment by shmerl** [comment]
This can be an issue with Firefox 57 now too, since it's using Web extensions. So it's not only Chromium-based browsers anymore.

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/issues/2919>.

**Comment by shmerl** [comment]
Ah, great. Thanks for the pointer!
