### ISSUE TITLE
The logger description wiki - GitHub [Language Error - English]

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2149]
The description for the logger contains a minor error:

> Green: The request for the resource was allowed to go through because it matched a filter/rule **_which_** purpose is to bypass a matching block filter/rule.

Correct:
Green: The request for the resource was allowed to go through because it matched a filter/rule **_whose_** purpose is to bypass a matching block filter/rule.

**Comment by gorhill** [comment]
Fixed, thanks.
