### ISSUE TITLE
Mr Rebates whitelist doesn't seem to work.

### ISSUE THREAD

**Issue by convexshiba** [gorhill/uBlock#215]
List URL is http://www.mrrebates.com/support/ab_white_list.txt
It's said in the list that it's intended for adp 2.0.
I added it in Custom. But uBlock shows 0 used out of 0 after update.
Is it uBlock or the list's format at fault?
Thanks

**Comment by weakptr** [comment]
uBlock does not support the *document* option that is present in every filter of that list.
 https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions

**Comment by coderant** [comment]
I See. Thank you.
I've added all the hosts to the whitelist section in uBlock.
like: "www.awin1.com"
Does this get the job done?

**Comment by gorhill** [comment]
> Does this get the job done?

Yes, it should work.
