### ISSUE TITLE
request Keyboard Shortcut for toggle popup panel

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2151]
with behavior similar to NoScript: ctrl+shift+s toggles its panel open/close. For NoScript it often means holding down ctrl+shift and pressing 's' to open it then 's' again to close it after a quick look.

This would also be handy in uBO, especially for those of us who already use lots of hotkeys and don't like to mouse much.

Could you add this hotkey combo for uBO?  One idea is ctrl+shift+p  (P for panel)

Also, now that the panel is viewable read-only for non-advanced users this hotkey could be used by a large number of uBO users

**Comment by gorhill** [comment]
The feature is supported browser-side for extensions based on WebExtensions API. It's avaliable for Chromium, and it is up to Firefox to make a UI for doing the same.

**Comment by joey04** [comment]
Thanks for the explanation. That's cool Chrome has the capability, but I use Pale Moon almost entirely, so it doesn't help me much.

I cracked the Xpi and added a XUL overlay for a hotkey to uBO (based on how other extensions do it) but according to the error console no overlays are allowed for Jetpack addons.
