### ISSUE TITLE
Problem to play videos from Digital pro server

### ISSUE THREAD

**Issue by Residentcl** [gorhill/uBlock#2152]
### One or more specific URLs where the issue occurs

http://www.latercera.com/laterceratv/diosdado-cabello-anuncia-leopoldo-lopez-sera-acusado-43-homicidios/
http://www.cnnchile.com/noticia/2016/11/13/las-selecciones-se-preparan-para-una-fecha-este-martes

### Screenshot in which the issue can be seen

![sin titulo](https://cloud.githubusercontent.com/assets/1659401/19163978/861b4f62-8bd4-11e6-89e4-5ef686d7b010.png)

### Steps for anyone to reproduce the issue

Go to the player and put play on the icon to play.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Vivaldi - 1.4.589.38 (Stable channel) (64 bits)
- uBlock Origin version: 1.9.16

##### Your filter lists

![list](https://cloud.githubusercontent.com/assets/1659401/19164253/8ff11688-8bd5-11e6-868b-0d8bd66783f9.jpg)

##### Your custom filters (if any)

No filter.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
