### ISSUE TITLE
ynet.co.il, Firefox for Android

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#2155]
https://github.com/easylist/EasyListHebrew/issues/207
Blank page on articles.
Problematic filter:
`||outbrain.com^`
Please add:
`@@||widgets.outbrain.com/outbrain.js$script,domain=ynet.co.il`
Thanks

**Comment by gorhill** [comment]
Unable to reproduce. I see `http://widgets.outbrain.com/outbrain.js` blocked on my side, yet pages render fine.

**Comment by IsraeliUser** [comment]
Make sure you use Firefox for **Android** with Easylist Hebrew and site is ynet**.co.il**.

**Comment by gorhill** [comment]
Yes, I can reproduce using dev console + device emulation for Nexus 7.
