### ISSUE TITLE
auto close tab that says chrome://ublock has prevented this from opening, etc.

### ISSUE THREAD

**Issue by rhazor** [gorhill/uBlock#2156]
i'm an old wanker browsing through pornhub videos almost everyday and clicking on each video it opens this annoying warning tab and opens video in another new tab and have to manually close the warning tab each time. maybe add an option in settings or something.

cheers, thanks for great tool.

**Comment by mapx-** [comment]
you should use this userscript 
https://greasyfork.org/en/scripts/6587-extendpornhub

**Comment by rhazor** [comment]
but what about other websites? i gave pornhub just as an example.

**Comment by mapx-** [comment]
for other sites search on easylist forum: http://forums.lanik.us/
and report those sites (Ads, popups ,...)

**Comment by rhazor** [comment]
what is the use of getting an extra tab opened saying that some spam was blocked? nobody wants to see none of that, thats why we are blocking them in first play. why report spam? its great it was blocked, but i'm asking how not to get that extra tab opened warning about blocked spam.

**Comment by uBlock-user** [comment]
Find the url of the tab and add a popup filter for it. Example - ||example.com^$popup. That will not block and report, but rather kill the tab from fully opening, ergo, the behavior you're seeking.

**Comment by rhazor** [comment]
that works for a specific given site address. but what about for all sites/global?

**Comment by gorhill** [comment]
The message _"uBlock Origin has prevented this from opening"_ is a result of strict-blocking.

Strict blocking is **unrelated** to popup filtering. Strict-blocking can kick in iwhtout popups, and popups can be with strict-blocked without popup filters present in the filter lists.

The purpose of popup blocking is to automatically close unwanted popup tabs, windows.

The purpose of strict-blocking is to prevent connecting at all to a remote site.

**Comment by gorhill** [comment]
> what is the use of getting an extra tab opened saying that some spam was blocked?

How does uBO knows it is some spam? Try the same thing with ABP and the tab will not only open just like with uBO, but will also load the content. Strict-blocking prevents the content to be loaded, you are informed about this, and you get to decide what to do. If there was a popup filter for that tab, it would be closed automatically.

**Comment by uBlock-user** [comment]
> but what about for all sites/global?

Add `no-popups: * true` switch to my rules. This will kill all new tab/windows invoked by any website or by any browser action, resulting in lots of false positives.

**Comment by gorhill** [comment]
I wonder if

- `|chrome-extension://*/document-blocked.html?` for Chromium-based browsers; OR
- `chrome://ublock0/content/document-blocked.html?` for Firefox

would work.

**Comment by uBlock-user** [comment]
Nope, the behavior still remains the same and the tab window isn't closed as expected, in Chromium and Firefox.
