### ISSUE TITLE
extratorrent.cc don't load with ublock

### ISSUE THREAD

**Issue by DuhBoy** [gorhill/uBlock#2157]
https://extratorrent.cc/

Front page of the site doesn't load when ublock is on, any solutions?

**Comment by mapx-** [comment]
add
`extratorrent.cc#@#br + br + table[class]`

**Comment by uBlock-user** [comment]
Nothing more than a filter list issue, nothing to do with uBlock either.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
