### ISSUE TITLE
groupon.com very slow

### ISSUE THREAD

**Issue by timkgh** [gorhill/uBlock#2158]
http://groupon.com/ web site has become very very slow in Chrome Version 54.0.2840.98 (64-bit) running on Mac OS X Sierra. I see a constant message in the status bar "Waiting for extension uBlock Origin ..."

Just using the default filters/setup of uBlock, nothing custom.

**Comment by gorhill** [comment]
Unable to reproduce. You will need to investigate yourself and make a better case that there is an issue with uBO and not something with your browser/OS/computer.

**Comment by jnns** [comment]
Noticed uBlock Origin rendering my father's PC useless when visiting the Groupon site as well. The counter of blocked entities climbed up till ~150. 

Unfortunately I'm not able to supply more information to reproduce this issue other than that it occured on Ubuntu / Chrome 49 as well as Chrome 56 with uBlock Origin 1.10.4.

**Comment by gorhill** [comment]
Some sites may become buggy when stuff is blocked, this is not a blocker issue, this is a filter issue, report to filter lists maintainers.
