### ISSUE TITLE
[Future request] Add cosmetic filter by attributes

### ISSUE THREAD

**Issue by inoyakaigor** [gorhill/uBlock#216]
Social network VK.com add new ads post in feed. It is no different from the usual records except attribute "data-ads":
![a866aae767](https://cloud.githubusercontent.com/assets/1235286/7702386/5f193512-fe38-11e4-91ec-cbb012c750e4.png)

**Comment by gorhill** [comment]
It's already supported: whatever valid CSS selector is a valid cosmetic filter:

    vk.com##div[data-ads]

See if this works.
