### ISSUE TITLE
ublock broken on firefox 50.0 linux armv7l

### ISSUE THREAD

**Issue by gmsh** [gorhill/uBlock#2160]
### Description of  the issue
ublock orgin is broken on a fresh installed Firefox on Archlinux(armv7l) on Raspberry Pi 3.

1. when you click the UO button on the panel it only displays half of the GUI (like #1713 )
![1479356622](https://cloud.githubusercontent.com/assets/396089/20376531/7419afde-acc2-11e6-86bf-5397af08f002.png)

2. when the checkbox "Auto-update filter lists" is checked, no filter list is shown.
![1479356957](https://cloud.githubusercontent.com/assets/396089/20376530/74174604-acc2-11e6-983d-7b34d7c2fcd2.png)

### One or more specific URLs where the issue occurs
every URL even about:blank or https://github.com

### Screenshot in which the issue can be seen

![1479356622](https://cloud.githubusercontent.com/assets/396089/20376531/7419afde-acc2-11e6-86bf-5397af08f002.png)
![1479358963](https://cloud.githubusercontent.com/assets/396089/20376994/9f156206-acc6-11e6-94e2-d9e22bb32af2.png)

![1479356957](https://cloud.githubusercontent.com/assets/396089/20376530/74174604-acc2-11e6-983d-7b34d7c2fcd2.png)
![1479359042](https://cloud.githubusercontent.com/assets/396089/20377002/a5ff7cf0-acc6-11e6-8aad-1f9336f99f75.png)

### Steps for anyone to reproduce the issue

1. run "pacman -S firefox" on archlinux armv7l (Raspberry Pi)
2. run "firefox -P" to create a fresh profile
3. install ublock origin from https://addons.mozilla.org/
4. click the ublock origin button on the toolbar to reproduce the half UI issue
5. open the dashboard then goto the 3rd party filters
6. click the "Auto-update filter lists" check box to reproduce the second issue.

### Your settings

I'm using the default settings on a fresh profile of Firefox.

- Browser/version: Mozilla/5.0 (X11; Linux armv7l; rv:50.0) Gecko/20100101 Firefox/50.0
- uBlock Origin version: 1.9.16

##### Your filter lists

no filter list since they are hidden in the dashboard.

##### Your custom filters (if any)
none.

##### about:buildconfig of Firefox
about:buildconfig
Build platform
target
armv7l-unknown-linux-gnueabihf
Build tools
Compiler 	Version 	Compiler flags
/usr/lib/distcc/bin/gcc -std=gnu99 	6.2.1 	-Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe
/usr/lib/distcc/bin/g++ -std=gnu++11 	6.2.1 	-D_FORTIFY_SOURCE=2 -O2 -Wall -Wc++11-compat -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wc++14-compat -Wno-invalid-offsetof -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-error=array-bounds -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fno-delete-null-pointer-checks -fno-schedule-insns2 -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -g -freorder-blocks -Os -fomit-frame-pointer -D_FORTIFY_SOURCE=2 -O2
Configure options

--enable-application=browser --enable-update-channel=release --enable-system-hunspell --disable-crashreporter --disable-elf-hack --disable-ion --enable-official-branding --enable-pie --enable-release --enable-startup-notification --enable-system-ffi --enable-system-pixman --enable-system-sqlite --disable-updater --disable-webrtc --prefix=/usr --with-google-api-keyfile=/build/firefox/src/firefox-50.0/google-api-key --with-mozilla-api-keyfile=/build/firefox/src/firefox-50.0/mozilla-api-key --with-system-bz2 --with-system-icu --with-system-jpeg --with-system-libevent --with-system-libvpx --with-system-nspr --with-system-nss --with-system-zlib

**Comment by gorhill** [comment]
Anyone can take this, I am not in a position to investigate, let alone fix.

**Comment by gorhill** [comment]
From the screenshot, it looks like Firefox interrupted uBO's script while it was compiling a filter list. Speculation: EasyList (the largest default selected list in uBO) is taking too long to compile by uBO and Firefox is aborting the script, leaving uBO in a broken state.

There is a `dom.max_script_run_time` in Firefox's `about:config`, maybe you could experiment changing the value to something higher and see if that resolves the issue.

**Comment by gorhill** [comment]
Actually, there are two values in `about:config`, not sure which was would apply to an extension like uBO:

- `dom.max_chrome_script_run_time`: default to 20s
- `dom.max_script_run_time`: default to 10s

**Comment by gmsh** [comment]
Thanks for you reply. 
It works. Everything is OK after the dom.max_chrome_script_run_time increased to 200, and dom.max_script_run_time to 100.
So it is not a bug of ublock. Thanks again.

**Comment by pierrre** [comment]
`dom.max_chrome_script_run_time` to 200 fixes the issue.
I didn't change `dom.max_script_run_time`.
