### ISSUE TITLE
content jumping

### ISSUE THREAD

**Issue by timse201** [gorhill/uBlock#2161]
### Describe the issue

if you scroll down and hover over links on some sites the content seems to rerender and is jumping a little bit up - but only the text not the background etc.
reproduced it on my website. the body margin-top or padding-top seems to get a negative value and the whole text jumped 2 or 3px up
(made a font height to em for a text with different font sizes but i think thats not the only issue)

<div with font-size:, line-height:>
<div with another font size></div></div>

deactivating ublock fixed the problem

on some sites it happens sometimes and sometimes everything is ok

### One or more specific URLs where the issue occurs

many sites
for example vote list on bugzilla
and this github page ;)

### Your settings

- Browser/version: firefox 49 and 50 tested
- uBlock Origin version:  1.9.16

##### Your filter lists
ublock lists without experemental
easy list
easy privacy
easy list germany
no own filters

**Comment by gorhill** [comment]
I don't understand the issue. Will mark as _invalid_ as many things requested in CONTRIBUTING have not been provided.
