### ISSUE TITLE
vatera.hu - Please add filter to Ublock Unbreak

### ISSUE THREAD

**Issue by kovacsattila-hun** [gorhill/uBlock#2162]
Page operational issues, no work _"Licitálj"_ orange button on website:

Example:

[http://auto-motor.vatera.hu/motor_robogo_quad_alkatresz_felszereles/eroatviteli_alkatresz/fek_fekrendszer/fektarcsa/fektarcsa_renault_clio_2db_uj_2388837974.html
](http://auto-motor.vatera.hu/motor_robogo_quad_alkatresz_felszereles/eroatviteli_alkatresz/fek_fekrendszer/fektarcsa/fektarcsa_renault_clio_2db_uj_2388837974.html
)

Please add this filter:
`@@||google-analytics.com/ga.js$domain=vatera.hu`

Thanks!

**Comment by lewisje** [comment]
That kind of request belongs here: https://github.com/uBlockOrigin/uAssets/issues

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
