### ISSUE TITLE
2 websites - incorrectly blocked script (to: uBlock UnBreak)

### ISSUE THREAD

**Issue by kovacsattila-hun** [gorhill/uBlock#2163]
Two websites, and two example pages:

http://allcatvideos.com/7-ways-cats-creep-you-out
http://dogswithbones.com/a-little-girl-and-her-cat-sing-we-built-this-city

Anti-Adblock on the site, and blocked showads.js from video server (Vidyomani)

The script contents:
`var d=document,e=d.createElement('div');e.id='zkcheckadblck';e.style.display='none';d.body.appendChild(e);`

Please add whitelist to uBlock Unbreak this filter:

`@@||cdn.vidyomani.com/c/p/showads.js`

Thanks!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
