### ISSUE TITLE
change static filter

### ISSUE THREAD

**Issue by laozi83** [gorhill/uBlock#2164]
Hello
on the site http://www.meteofrance.com/previsions-meteo-montagne/les-2alpes/38860
I mask different comments on the page with the function of uBlock origin 'block this item'
but at each replacement of comment, again I must hide them,
the blocked element is always in this form:
www.meteofrance.com###article_10154_10180_36876395_4 \.6
can we replace the different digits with wildcards to block all comments and their renewals
Thank you

**Comment by mapx-** [comment]
you need something like this

`meteofrance.com##[id^=article_]`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
