### ISSUE TITLE
Remove Search Engine Tracking

### ISSUE THREAD

**Issue by vlsatheesh** [gorhill/uBlock#2165]
We Know that Google,Yahoo and other Search engine track when user click from its search page , they will use this information for their ads and also collect the information about the page what we visited , it is better to  replace the search redirect link with original page link. 

We have separate addons in Firefox, But sill it is better to integrate in uBlock , To Support All-In-One AdBlocker 

FF Addon name :searchlinkfix 
OpenSource GitHubURl : https://github.com/palant/searchlinkfix

**Comment by vlsatheesh** [comment]
Is the feature already exist in uBlock..? It is better to have this feature

**Comment by vlsatheesh** [comment]
@gorhill

**Comment by gorhill** [comment]
> It is better to have this feature

That is an opinion. I disagree.
