### ISSUE TITLE
uBlock Logger Static Filter Display Error

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2166]
In **uBlock Origin for Chrome** there is an error in the logger whereby when a domain is specified for a filter which also uses the `$script` tag the **Logger** outputs `domain=0`, instead of the real domain `0` is displayed (this happens with filters in **EasyList**).

**Example 1**: This filter `||amazonaws.com^$script,domain=ndtv.com` in the **EasyList** is displayed in the logger as `||amazonaws.com^$script,domain=0`
The above example can be tested on: 
http://www.ndtv.com/world-news/mark-zuckerberg-urges-post-trump-world-not-to-disconnect-1627655

**Example 2**: This filter `@@||ade.clmbtech.com^$script,domain=indiatimes.com` in the **EasyList** is displayed in the logger as `@@||ade.clmbtech.com^$script,domain=0`
The above example can be tested on: 
http://timesofindia.indiatimes.com/home/environment/global-warming/No-consensus-on-tricky-issues-at-climate-meet/articleshow/55519379.cms

**Screenshots of the logger displaying wrong info:**
https://i.imgur.com/HyH1IjF.png (SS for Example 1)
https://i.imgur.com/dP5rfS0.png (SS for Example 2)

_Note: Tested using default settings and default filter lists, using **uBlock v1.9.16** & **Chrome 54.**_

**Comment by lewisje** [comment]
I can reproduce; my guess is it has to do with some improper datatype-conversion.

**Comment by okiehsch** [comment]
It is fixed in uBlock v1.9.17+ #2106
