### ISSUE TITLE
Cannot block Pop-Up window on Xvideos.com

### ISSUE THREAD

**Issue by spooji** [gorhill/uBlock#2167]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Ads are being blocked on xvideos.com successfully, however the pop-up window launches on every click, then closes -- very irritating.  I attempted to add a "script:contains" rule but haven't succeeded.  I'm probably not very clever about this because the filter documentation is limited and doesn't address whether it even filters "included" js files.

Whenever you are viewing a specific video, the page loads several 1st-party scripts.  The following link contains the culprit scripting, to the best of my knowledge, and it linked from the main HTML on any page which loads the html5 video player (this issue may not apply to the Flash Player version).

Source link example (NSFW): http://www.xvideos.com/video6177872/ecr-0032
Likely culprit script source: http://static-hw.xvideos.com/v3/js/html5player.min.js?v=5

This contains a window object named window.openpop=function() which I believe is the target code.  I've used FireBug and deleted this DOM property and it seems to resolve the pop-up issue.  

How am I to attack this with a uBlock rule?

Platform info:  Firefox Version 50.0 32-bit, Windows Pro 7 64-bit.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Visit xvidoes.com.
2. Click a specific video.
3. Click anywhere on the page, on a play button, or on another video link.
4. Pop-up appears, then vanishes if pop-up blocker is enabled.

### Your settings

- Firefox 50.0
- uBlock Origin version: 1.9.16

##### Your filter lists

Attempted rule:

xvideos.com##script:contains(window.openpop)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
