### ISSUE TITLE
Popup code within legit script

### ISSUE THREAD

**Issue by BillyCool** [gorhill/uBlock#2168]
### Describe the issue
It's not really an issue but more of a question. Openload.co has integrated popup ads within the script responsible for generating download links. Therefore, if I create a filter to block the ads and popups, I'm also blocking my ability to download anything. The filters I currently have block any other ads on the website.

So I was wondering, is there any way to block only part of an inline script instead of the whole script?

Thanks in advance.

### One or more specific URLs where the issue occurs

https://openload.co/f/j9Wvlrtdenk/masterkreatif.com-tp5u.rar

### Steps for anyone to reproduce the issue

1. Visit the above URL.
2. Click on the Free Download button.

### Your settings

- Browser/version: Mozilla Firefox 50.0 64-Bit
- uBlock Origin version: 1.9.16

##### Your filter lists

openload.co##script:contains(doPopAds)
openload.co##script:contains(popAds)
openload.co##script:contains(adblock2)
openload.co##script:contains(popAdsLoaded)

**Comment by lewisje** [comment]
I guess `||openload.co^$popup` would help, but it would be nice if a new [redirect resource](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt) were added.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
