### ISSUE TITLE
Checksum polish filters

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#217]
Hi, can you add to this file https://github.com/gorhill/uBlock/blob/master/assets/checksums.txt cheksum for  POL: Adblock polskie reguly‎ (http://www.certyficate.it/adblock/adblock.txt). Now you have there old filter cbde6559e6100aca9690fd01f2a93ad3 assets/thirdparties/raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt .

**Comment by gorhill** [comment]
Filter lists which are pulled from remote servers will get updates regardless of the `checksums.txt` file.

**Comment by MajkiIT** [comment]
I know, but It would by useful when user will see information that filter is out of date like in others filters.
