### ISSUE TITLE
mybank.pl site not working

### ISSUE THREAD

**Issue by mkkot** [gorhill/uBlock#2171]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Hello,

there is no specific rule if I can report such problem or not, so here it goes:
the site mybank.pl has some anti-adblock script which starts few seconds after I enter the site. The site is totally inaccessible until I turn off ublock on that site.

### One or more specific URLs where the issue occurs
http://mybank.pl/

### Screenshot in which the issue can be seen
http://i.imgur.com/qtuvYWY.png

### Steps for anyone to reproduce the issue

1. Install ublock and open http://mybank.pl/
2. Wait about 5 seconds. Full window message appears that you can't use adblock.

### Your settings

Since this is designed by webmaster and 100% reproducible, it blocks also adblock, so my settings are irrelevant.

- Browser/version: 
- uBlock Origin version: Firefox 49.0.2, uBlock 1.9.16

##### Your filter lists

Irrelevant

##### Your custom filters (if any)
Irrelevant

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
