### ISSUE TITLE
possible window.open conflict with popup blocker add-ons

### ISSUE THREAD

**Issue by schomery** [gorhill/uBlock#2172]
I am working on a popup blocker extension for Chrome browser. To block all popups, the extension overwrites the unprotected `window.open` on document_start using:

```js
Object.defineProperty(window, 'open', {
    writable: false,
    configurable: false,
    value: function () {

    }
);
```

When uBlock is installed, web pages can bypass the popup blocker although the `window.open` is still overwritten.
Example: First click on http://vidtodo.com/03pbhekfsihm when browser window is cleared.

Any idea what the problem is?

**Comment by gorhill** [comment]
> Any idea what the problem is?

No, uBO does not overwrite `window.open`, it only listens to `webNavigation`/`webRequest` events to filter popup windows.

**Comment by lewisje** [comment]
If a site wants to be extra-crafty, it can inject a blank `iframe`, extract the `open` method of its `window` object, and apply that to the top-level `window`, to ensure it is able to open a window; one way to do this is to check whether the string representation of `window.open` is the usual one with `'[native code]'` inside, and another way is to inspect the return value (which will be a `Window` object, with a string representation of `'[object Window]'`.

You can defeat some checks like that, by explicitly defining your no-op function's `toString` method, and making the function return the `window` object itself (or maybe the window inside a new `iframe`, to defeat a check for whether the return value is equal to `window`), but basically, trying to disable `window.open` reliably brings you down a deep rabbit-hole of counter-countermeasures.

**Comment by schomery** [comment]
@lewisje thanks, very useful info.
