### ISSUE TITLE
Certain sites won't load with latest FF Dev Edition

### ISSUE THREAD

**Issue by m3Lith** [gorhill/uBlock#2173]
### Describe the issue
I'm a FF Dev Edition (x64, if that matters) user. Today it got update to v52 and I've instantly noticed that some websites keep loading forever with uBO enabled. Some others seems to load fine until a certain point, but not completely (the spinner icon keeps on spinning). If I disable it, all is good. 
I'm also using uMatrix. but I doubt it's related to this problem.

### One or more specific URLs where the issue occurs
https://tweetdeck.twitter.com/
http://alternativeto.net/

### Screenshot in which the issue can be seen
-

### Steps for anyone to reproduce the issue
Try going to https://tweetdeck.twitter.com/ on FF Dev Edition v52 x64 with uBO enabled.

### Your settings
I don't think I have changed any default settings.

- Browser/version: Firefox Developer Edition (52.0a2), x64
- uBlock Origin version: 1.9.16

##### Your filter lists
Default

##### Your custom filters (if any)
-

**Comment by gorhill** [comment]
You will have to investigate the issue on your side.

**Comment by gorhill** [comment]
Actually, also marking as invalid since no effort was made to actually look at what the logger says, a key step when it comes to investigate an issue.

**Comment by m3Lith** [comment]
It seems to be some weird interaction issue with another add-on, [Keepa](https://addons.mozilla.org/en-US/firefox/addon/keepa/) (last update in September).

Originally I didn't think the logger provided any different info, but having uBO and Keepa on and off do show different entries.

If you'd be willing to look at these:
1. [uBO on, Keepa on](http://i.imgur.com/pb0xEVj.png) 
2. [uBO off, Keepa on](http://i.imgur.com/5LjKb6B.png)
3. [uBO on, Keepa off](http://i.imgur.com/SlZDwDT.png)
4. [uBO off,  Keepa off](http://i.imgur.com/xMC6k1i.png)

Or should I try posting in Discourse. Maybe try contacting Keepa's authors? I've no idea which add-on is more at fault here, some FF changes definitely impacted one or another.

**Comment by gorhill** [comment]
I can reproduce with Keepa installed. I need to investigate whether there is an issue with uBO.

**Comment by gorhill** [comment]
Not sure why this happens. It does not happens if the script normally blocked by uBO is not blocked.

I see Keepa is a WebExtension and using the webRequest API to install handlers for `<all_urls>`. I don't know why it listens to **all** URLs given its purpose. The code is not easy to read, only single-letter variables, no comments at all.

This should be looked at by Keepa devs. It could also be an issue with WebExtensions API.

**Comment by gorhill** [comment]
If I use the WebExtension version of uBO, all work fine. So I lean toward a WebExtensions API issue.

**Comment by nazar-pc** [comment]
The same conflict with Ghostery - when it is enabled the same issue happens.
For me it happened after transition from 52 to 53 Nightly builds.

Few more pages:
* https://www.youtube.com/my_videos?o=U
* https://habrahabr.ru/
* https://www.olx.ua/

Firefox Nightly 53.0a1 (2016-11-22)
uBlock Origin 1.9.17b10 (from https://addons.mozilla.org/uk/firefox/addon/ublock-origin/versions/beta)
Ghostery 7.0.1.4

**Comment by gorhill** [comment]
I created an issue on Firefox's issue tracker: <https://bugzilla.mozilla.org/show_bug.cgi?id=1319607>.

**Comment by m3Lith** [comment]
Seems like they fixed it (landed in both nightly and aurora channels), so I guess this can be closed.
