### ISSUE TITLE
It seems some filters are not used

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#2174]
Hi,

Actually I do not know it is a real problem, nevertheless I wanted to ask you.As you can see at the picture below in spite of I use Ublock for a long time I realized that some filters are not used by Ublock.It seems 0.Is it a usual state or not?Thanks.

![capture](https://cloud.githubusercontent.com/assets/16270347/20552873/d4760366-b157-11e6-8a89-06a488e32757.PNG)

- Browser/version:  Chrome v54 on Windows 10 x64
- uBlock Origin version: v1.9.6 with default filters

**Comment by uBlock-user** [comment]
It's pretty normal. It happens because all of them are available in Fanboy+Easylist Merged Ultimate List. Deactivate either of them and the other will load all the filters unless they're already loaded from another list. Only distinct filters are loaded.

**Comment by mozkan007** [comment]
@uBlock-user, I got it.Thank you.
