### ISSUE TITLE
ads on geektime.co.il

### ISSUE THREAD

**Issue by almog123** [gorhill/uBlock#2176]
http://chameleonx.com/ ads on geektime.co.il

they say you have the option to "opt-out" but the ads keep coming back after some days.

I hate those ads, please help me with that.

I've downloaded Adblock in order to remove the ads, but they keep coming back.

reported to HebrewList which don't want to help in this case: https://github.com/easylist/EasyListHebrew/issues/208

**Comment by mapx-** [comment]
you have to report here: https://github.com/uBlockOrigin/uAssets/issues
and provide some screenshot and specific page where the ads are appearing

**Comment by uBlock-user** [comment]
`||$third-party,domain=geektime.co.il`

That should kill any ads from appearing. This will also block any useful and needed resources(if any). In that case, file what breaks the site and find it out using the logger and report back here.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
