### ISSUE TITLE
No uBlock icon/control in popup-Windows (e.g. Chat-windows)

### ISSUE THREAD

**Issue by Obusmydealz** [gorhill/uBlock#2177]
I've encountered this issue several times under different circumstances. An example: On a website is a button for opening a new chat window (e.g. here https://www.congstar.de/handytarife/congstar-wie-ich-will/wunschtarif/ under "Jetzt Chat starten"). In this new small window, there is no uBlock icon such that I cannot allow some scripts (dynamic filtering) needed to run the chat; I've to turn off uBlock temporarily completely such that the chat works.

However, if I right-click there is the uBlock-context-menu entries for blocking an element. How can I access the dynamic-filtering control panel in this new window? Is it possible to add some link to the uBlock-context-menu?

**Comment by gorhill** [comment]
Use the logger for those cases where there is no toolbar icon -- a side effect of opening a browser window with no decorations. See [Logger / Accessing popup UI of a specific page](https://github.com/gorhill/uBlock/wiki/The-logger#accessing-popup-ui-of-a-specific-page).
