### ISSUE TITLE
Youtube bug: prevent Youtube from marking videos as viewed

### ISSUE THREAD

**Issue by porno-creep** [gorhill/uBlock#2178]
### Describe the issue

Ublock Origin prevent Youtube from marking videos as viewed. It happens even when youtube.com added to whitelist or all filter lists are disabled. Only disable of plugin can help. I can reproduce it in Firefox and Chrome (latest stable versions).

### One or more specific URLs where the issue occurs

https://www.youtube.com/feed/subscriptions

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Log in to youtube with your account
2. Go to subscriptions page
3. Open any video from your subscriptions
4. Back to subscriptions page and see that this video wasn't mark as "WATCHED".

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 50 x32, Chrome 55.0.2883.21 x64
- uBlock Origin version: 1.9.16 and 1.9.17.10

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
