### ISSUE TITLE
Can uBlock block YouTube ads on Palemoon?

### ISSUE THREAD

**Issue by WillPittenger** [gorhill/uBlock#2180]
My favorite extension for blocking youtube ads is no longer supported by Palemoon due to Jetpack support going away.  So I'm looking for a replacement.  I'm not talking about ads on the page, but inserted into the videos.

Can uBlock help?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
