### ISSUE TITLE
Extension disappears after every browser restart!

### ISSUE THREAD

**Issue by whiteniggazh** [gorhill/uBlock#2182]
So since I manually update it to the latest version, whenever I restart my browser, it tells me to disable developer mode extensions and it pops a window whether to cancel or disable it and whatever I click, the extension just stops working completely and the ublock folder disappears from the extensions folder, meaning that I need to put a new ublock folder there every single time...

Screenshot: http://prnt.sc/db1z8b

Steps to reproduce:

1. Close your browser.
2. Open your browser.
3. You get the notification I have in the screenshot.

I have all the default settings.

Chrome version: Version 54.0.2840.99 m (64-bit)

- Browser/version: Chrome version: Version 54.0.2840.99 m (64-bit)
- uBlock Origin version: latest

Filter list has nothing to do with it, happens with empty filter list aswell.

**Comment by gorhill** [comment]
Your browser is doing this, not uBO. Contact Google Chrome support.
