### ISSUE TITLE
Issue with dojo.js with using ublock origin on element14 and farnell websites [ Urgent ]

### ISSUE THREAD

**Issue by nitishbhide17** [gorhill/uBlock#2183]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Hello Team ,

Keep uBlock enabled on Chrome or Firefox.
go to : http://au.element14.com/webapp/wcs/stores/servlet/Search?catalogId=15001&langId=43&storeId=10184&categoryName=All%20Categories&selectedCategoryId=
We are seeing error with dojo.js while page loading which is ultimately blocking ability for customers to search , order information page , make payment and other stuff.

can we please look into this issue on urgent basis ?
If you need any specific information , do not hesitate to contact me.

Thanks,
Nitish

### One or more specific URLs where the issue occurs
http://sg.element14.com/webapp/wcs/stores/servlet/Search?catalogId=15001&langId=65&storeId=10191&categoryName=All%20Categories&selectedCategoryId=
http://au.element14.com/batteries-non-rechargeable
http://au.element14.com/webapp/wcs/stores/servlet/Search?catalogId=15001&langId=43&storeId=10184&categoryName=All%20Categories&selectedCategoryId=
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

![ublock_error2](https://cloud.githubusercontent.com/assets/23719442/20596616/5673001e-b237-11e6-821e-71024ea5be1b.JPG)
![ublocker_dojoerror](https://cloud.githubusercontent.com/assets/23719442/20596617/56750f4e-b237-11e6-89ce-39eaaeca10d0.JPG)

### Steps for anyone to reproduce the issue

Go to URL directly and click on left hand side parametric filters or show all product link .

### Your settings

- Browser/version:  Chrome / firefox 
- uBlock Origin version: 1.9.16

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
![ublock_error2](https://cloud.githubusercontent.com/assets/23719442/20596565/16a60ff8-b237-11e6-90a0-4b3cc6d7520c.JPG)
![ublocker_dojoerror](https://cloud.githubusercontent.com/assets/23719442/20596566/16a7b830-b237-11e6-97a8-be741a862550.JPG)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Also, if/when you file an issue at uAssets, be very detailed about what **exactly** is not working, site appears working fine.
