### ISSUE TITLE
Custom filter stops working after I close firefox

### ISSUE THREAD

**Issue by alxthaman** [gorhill/uBlock#2184]
Hello

I'm trying to block two windows advertising Twitch's new 'Bits' feature, which cover a huge part of some channels' chat windows as seen in the pic below :

http://img11.hostingpics.net/pics/354026BitsWindows.png

Using Ublock's logger I've created this static filter :

||api.twitch.tv/bits$important

Now my problem is, the rule works perfectly fine right after I created it

http://img11.hostingpics.net/pics/199380Blocked.png

But if I close firefox and open it again, then the filter just stops working

You can see in the logger that https://api.twitch.tv/bits is not blocked anymore

http://img11.hostingpics.net/pics/402442NotBlocked.png

The same problem happens if I use Ublock's element picker to create those filters :

www.twitch.tv##.bits-promo__content
www.twitch.tv##.bits-card--promo.bits-card--standard

They work fine, until I close firefox

That issue is not related to any specific channel, but here's some where you get the 'Bits' ads

https://www.twitch.tv/dansgaming
https://www.twitch.tv/cohhcarnage

My Settings :

Firefox 50 x64

Ublock Origin 1.9.16
Advanced user features disabled
No custom filters other than the ones mentionned above

My filter lists :

uBlock filters
uBlock filters - Badware risks
uBlock filters - Privacy
uBlock filters - Unbreak

Adblock Warning Removal List
Anti-Adblock Killer
EasyList

Basic tracking list by Disconnect
EasyPrivacy
Fanboy's Enhanced Tracking List

Malvertising filter list by Disconnect
Malware Domain List
Malware domains
Malware domains (long-lived)
Malware filter list by Disconnec
Spam404

Dan Pollock's host file
hpHosts' Ad and tracking server
MVPS HOSTS
Peter Lowe's Ad and tracking server list

FRA: EasyList Liste FR

**Comment by gorhill** [comment]
Works fine here. Did you verify that your filter is still present after your re-open Firefox?

**Comment by alxthaman** [comment]
Yep, the custom filter is still there

I just tried a new firefox profile, with nothing but Ublock Origin, and everything works fine

So this means there's something wrong with my regular profile...

Disabling every addon but Ublock Origin didn't solve the problem, so I don't know what causes this

Maybe it's time for a fresh install

**Comment by gorhill** [comment]
> Disabling every addon but Ublock Origin didn't solve the problem

Did you restart the browser after disabling those other extensions? It's kind of required, some extensions may not shutdown properly when disabled.

**Comment by alxthaman** [comment]
Aye, did a restart of firefox

Maybe it's a stupid question, but could it be related in any way to the fact I've completly disabled disk cache in favor or ram cache?

**Comment by gorhill** [comment]
> could it be related in any way to the fact I've completly disabled disk cache in favor or ram cache?

I don't see how this could be an issue. If a network request is reported in uBO's logger, this means it is seen by uBO. If your filter is in there and not disabled, it should be applied. Maybe look in the browser console if there are errors related to uBO.

**Comment by alxthaman** [comment]
I went with a new profile, and everything works just fine now

Thanks for your help, and for making this amazing add-on!

**Comment by migueldemoura** [comment]
@alxthaman, please mark this as closed!
