### ISSUE TITLE
lepoint.fr

### ISSUE THREAD

**Issue by Giljulien** [gorhill/uBlock#2185]
http://www.lepoint.fr/

![image](https://cloud.githubusercontent.com/assets/22545001/20632320/f514caa8-b33c-11e6-914c-4e58fdae455d.png)

- Browser/version: Google Chrome
- uBlock Origin version: Ublock Origin 1.9.16

Your filter lists : 
![image](https://cloud.githubusercontent.com/assets/22545001/20632374/54de10a2-b33d-11e6-82f4-83caa3881f3c.png)

Your custom filters (if any) : 
www.lepoint.fr/publicite/
www.lepoint.fr
https://idalia.assariaburdine.com

Thanks
Gilles

**Comment by Giljulien** [comment]
+ Tampermonkey

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
