### ISSUE TITLE
Credentials being leaked on uBlock log

### ISSUE THREAD

**Issue by 9662** [gorhill/uBlock#2186]
## Installation

 * uBlock Origin 1.9.16
 * Firefox 49.0.2
 * OpenSUSE Tumbleweed 20161104

## Steps to reproduce

 1. Open uBlock's log
 2. Select "all" in the display filter (just to make this description easier)
 3. Open a new tab
 4. In the address bar, type in a URL containing [basic authentication](https://tools.ietf.org/html/rfc7235) credentials. Those do not have to be real, e.g., `https://user:secret@google.com/` will do. If your browser asks for confirmation that this is the site you want to visit, acknowledge.
 5. Go back to the log tab.

## Actual behaviour

The credentials are visible in uBlock's log.

## Expected behaviour

The credentials, or at least the password, should not be visible. For example, it may be masked.

## Platinum™ Pro® Turbo GTI (pat. pend.) version behaviour

Provide a configuration option to make credentials optionally visible.

**Comment by gwarser** [comment]
Browser console show them also.

**Comment by gorhill** [comment]
Nothing is leaked, the log content is ephemeral, nothing is recorded.

**Comment by 9662** [comment]
> Nothing is leaked, the log content is ephemeral, nothing is recorded.

In that case, I reckon it's quite acceptable to have them visible. As @gwarser points out, that's consistent with console behaviour, at least on Firefox. Cheers!
