### ISSUE TITLE
[Firefox only] uBlock popup opening animation feels jerky

### ISSUE THREAD

**Issue by FatOrangutan** [gorhill/uBlock#2187]
### Describe the issue
The opening animation for the uBlock popup on Firefox feels much less smoother than in Chrome / Vivaldi.

### One or more specific URLs where the issue occurs
Not relevant, but I'm recording the following gif's on http://edition.cnn.com/.

### Screenshot in which the issue can be seen
Not embedding images inline so that the issue is more readable.
1) Firefox, without the dynamic filtering pane visible - no / barely noticeable jerkiness: http://i.cubeupload.com/IviF5M.gif
2) Firefox, with the dynamic filtering pane visible - jerkiness much more noticeable: http://i.cubeupload.com/e9QRH2.gif . [Slowing down](http://i.cubeupload.com/lWO3df.gif) the gif reveals the cause of this jerkiness - for a moment, the popup almost completely detaches itself from where it is supposed to originate from:
![frame_21_delay-0 02s](https://cloud.githubusercontent.com/assets/8336638/20638516/36aa3182-b3cf-11e6-97a4-a73d0bc197d7.gif)

3) Vivaldi, with the dynamic filtering pane visible - no / barely noticeable jerkiness: http://i.cubeupload.com/nwEZUD.gif
4) Smoother animations in Firefox for all popups other than uBlock: http://i.cubeupload.com/A7G40F.gif

All animations on one page: http://imgur.com/a/8vWry.

### Steps for anyone to reproduce the issue
1) Install uBlock in Firefox.
2) Check 'I am an advanced user' from dashboard.
3) Set the uBlock popup to show up in the expanded mode, with the dynamic filtering pane visible.
4) On any web page, click the uBlock toolbar icon and notice the popup animation.

### Your settings
Default, except for 'I am an advanced user.'
- Browser/version: Gifs recorded on Firefox 50; but issue reproducible stable through nightly.
- uBlock Origin version: Gifs recorded in 1.9.17rc0; but issue long existing.

##### Your filter lists
Default.

##### Your custom filters (if any)
None.

**Comment by gwarser** [comment]
https://github.com/chrisaljoudi/uBlock/issues/996

**Comment by alexara** [comment]
> Wouldn't it be possible to set the panel as invisible, render it, get its size, resize the frame, and then display it? There would be a small latency, but at least it wouldn't flicker this way.

**Comment by Dither** [comment]
It's kinda better for me this way:

```diff
From 67a3e13f61d1273bd4bee8382d282cf7f3f4c8b8 Mon Sep 17 00:00:00 2001
From: Dither <Dither@users.noreply.github.com>
Date: Tue, 6 Dec 2016 13:32:01 +0300
Subject: [PATCH] Fix for jerky popup

---
 src/css/popup.css |  7 +++++--
 src/js/popup.js   | 17 ++++++++---------
 src/popup.html    |  2 +-
 3 files changed, 14 insertions(+), 12 deletions(-)

diff --git a/src/css/popup.css b/src/css/popup.css
index 2e8dfef..9b71c5a 100644
--- a/src/css/popup.css
+++ b/src/css/popup.css
@@ -1,9 +1,8 @@
-body {
+html,body {
     background-color: white;
     border: 0;
     float: left;
     margin: 0;
-    opacity: 1;
     overflow: hidden;
     padding: 0;
     white-space: nowrap;
@@ -77,6 +76,7 @@ body[dir="rtl"] #panes {
     }
 body, #panes {
     text-align: right; /* this helps the popup render better at "intermediate" widths */
+    float: right;
     }
 
 #panes > div {
@@ -269,6 +269,9 @@ body[dir="rtl"] #tooltip {
     opacity: 1;
     }
 
+.tooltipContainer {
+    float: left;
+}
 #firewallContainer {
     border: 0;
     font-size: 85%;
diff --git a/src/js/popup.js b/src/js/popup.js
index 50eddd7..a324d88 100644
--- a/src/js/popup.js
+++ b/src/js/popup.js
@@ -407,14 +407,8 @@ var renderPopup = function() {
 
     uDom.nodeFromId('appname').textContent = popupData.appName;
     uDom.nodeFromId('version').textContent = popupData.appVersion;
-    uDom('body')
-        .toggleClass('advancedUser', popupData.advancedUserEnabled)
-        .toggleClass(
-            'off',
-            (popupData.pageURL === '') ||
-            (!popupData.netFilteringSwitch) ||
-            (popupData.pageHostname === 'behind-the-scene' && !popupData.advancedUserEnabled)
-        );
+
+    document.body.classList.toggle('advancedUser', popupData.advancedUserEnabled);
 
     // If you think the `=== true` is pointless, you are mistaken
     uDom.nodeFromId('gotoPick').classList.toggle('enabled', popupData.canElementPicker === true);
@@ -486,7 +480,6 @@ var renderPopup = function() {
         vAPI.localStorage.setItem('popupFirewallPane', dfPaneVisibleStored);
     }
 
-    uDom.nodeFromId('panes').classList.toggle('dfEnabled', dfPaneVisible);
     uDom('#firewallContainer')
         .toggleClass('minimized', popupData.firewallPaneMinimized)
         .toggleClass('colorBlind', popupData.colorBlindFriendly);
@@ -495,6 +488,12 @@ var renderPopup = function() {
     if ( dfPaneVisible ) {
         buildAllFirewallRows();
     }
+
+    document.body.classList.toggle('off', (popupData.pageURL === '') ||
+            (!popupData.netFilteringSwitch) ||
+            (popupData.pageHostname === 'behind-the-scene' && !popupData.advancedUserEnabled)
+        );
+    document.body.style.removeProperty('opacity');
 };
 
 /******************************************************************************/
diff --git a/src/popup.html b/src/popup.html
index e27f253..e0b4820 100644
--- a/src/popup.html
+++ b/src/popup.html
@@ -9,7 +9,7 @@
 <title>uBlock</title>
 </head>
 
-<body>
+<body style="opacity: 0; transition: width 0.3s, height 0.3s, opacity 0.3s;">
 <a href="dashboard.html" target="_blank" id="gotoPrefs" data-i18n-tip="popupTipDashboard" data-tip-position="under"><span id="appname"> </span> <span id="version"> </span><span class="fa">&#xf013;</span></a>
 <div id="panes">
     <div class="tooltipContainer">
-- 
2.10.0.windows.1
```

**Comment by Grossdm** [comment]
Has this been confirmed on new, release versions of Firefox?

I've had trouble with a video card that has given me some insight into the large number of graphics and rendering preferences/settings that the browser has. It appears that some might be legacy from upgraded installations, as one example of how this is a possible concern.

**Comment by Alexander--** [comment]
Same here, the popup is visually painful to open. There is no fade-in (likely, because I don't have a fancy compositing WM) but the two-stage flicker is awful and popup itself takes too much time to open.

@gorhill, please fix this, there are multiple Firefox addons that do not exhibit this behavior. RequestPolicy, Google Translator and multiple others have nice, non blinking popups. They are also "dynamic-sized", they just don't blink. This is the primary reason why I still keep RequestPolicy installed — interacting with flickering uBlock popup is just too painful.
