### ISSUE TITLE
help adding menu item for Panel popup in Firefox legacy

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2188]
I previously requested #2151 for a hotkey to open the panel, which was declined. So I tried to add this myself.

At this point I added a Tools menu item (not hotkey yet) but I can't get it hooked into uBO properly. I've tried both generating a 'popupshowing' event and sending the same message that toggleMinimize does in popup.js. But neither is working.

All of these changes are in platform/firefox/vapi-background.js so I attached my diff with the latest version. It has comments of what I'm seeing in the error console.

Any help on this would be much appreciated. I'm a javascript novice out of ideas at this point.

I'm using Pale Moon 26.5, but I presume this would work for any other Mozilla browser with LegacyToolbarButton (or ideally could work with any of them).

[diff.txt](https://github.com/gorhill/uBlock/files/614369/diff.txt)

**Comment by gorhill** [comment]
Sorry, just do not have the time to assist with other people's project.
