### ISSUE TITLE
help to block

### ISSUE THREAD

**Issue by Toodo** [gorhill/uBlock#2189]
Hello

this is not an issue but i dont know where to write.
on dreamfilmhd.bz is it popups and i find this line to remove the popup but i dont know to how add it to ublocker so can someone help me with that? :)

`<a style="width:100%; height:100%; display:block!important; position:fixed; top:0px; left:0px;cursor: pointer;z-index: 2147483647;" onclick="mainWidget_globalTm.ojdzsmstlqypchwxhfgsfgohomvqzt('PGh0bWw+PGhlYWQ+PC9oZWFkPjxib2R5PjxzY3JpcHQ+ZG9jdW1lbnQubG9jYXRpb24uaHJlZj0naHR0cDovL3BvcC5yZWRpcmVjdC5hZHNqdWRvLmNvbS9yZC9yZHAuaHRtbD91PWh0dHAlM0ElMkYlMkZyZWtvdmVyci5hZGsyeC5jb20lMkZpbXAlM0ZwJTNENzQ5OTQ5MDklMjZjdCUzRGh0bWwlMjZhcCUzRDEzMDMlMjZpc3MlM0QwJTI2ZiUzRDAlMjZhYiUzRDUwMDMlMjZwc2lkJTNEcmVrb3ZlcnImY2w9ZGYwM2U0N2UtOWVmYy1jMzVlLTU0YjktYmQwMzNjYzIxM2E1Jzwvc2NyaXB0PjwvYm9keT48L2h0bWw+');mainWidget_globalTm.close_all();"></a>`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
