### ISSUE TITLE
What is cache and why should they be purged ?

### ISSUE THREAD

**Issue by osminogig** [gorhill/uBlock#219]
Hi !
Thought it would be the first question in FAQ , but ...

Please explain in detail for the average user.

**Comment by 5t3f4n** [comment]
In the Privacy tab on the uMatrix Dashboard, click the question mark icon (?) next to each setting to reveal a brief explanation.

>Some web sites are really bent on tracking you, so much that they will use not-so-nice tricks to work around whatever measures you take in order to not be tracked.

>A few of these tricks rely[1, 2] on the [browser cache](https://en.wikipedia.org/wiki/Web_cache), which content is often long lasting since rarely will users take the time to regularly clear their browser cache.

>There is little inconvenience to clear the browser cache regularly (likelihood is that you won't notice when it happens), and the benefit is to prevent these obnoxious trackers from invading your privacy.

>Check this option to have uMatrix do it for you, at the interval you wish.

><sub>[1] [“Preventing Web Tracking via the Browser Cache”](https://grepular.com/Preventing_Web_Tracking_via_the_Browser_Cache)
[2] [“Cookieless cookies”](http://lucb1e.com/rp/cookielesscookies/)

**Comment by 5t3f4n** [comment]
From the uMatrix Privacy tab. I think this explains it quite well.

>Some web sites are really bent on tracking you, so much that they will use not-so-nice tricks to work around whatever measures you take in order to not be tracked.

>A few of these tricks rely[1, 2] on the [browser cache](https://en.wikipedia.org/wiki/Web_cache), which content is often long lasting since rarely will users take the time to regularly clear their browser cache.

>There is little inconvenience to clear the browser cache regularly (likelihood is that you won't notice when it happens), and the benefit is to prevent these obnoxious trackers from invading your privacy.

>Check this option to have uMatrix do it for you, at the interval you wish.

>[1] [“Preventing Web Tracking via the Browser Cache”](https://grepular.com/Preventing_Web_Tracking_via_the_Browser_Cache)
[2] [“Cookieless cookies”](http://lucb1e.com/rp/cookielesscookies/)

**Comment by CrisBRM** [comment]
@5t3f4n Pretty sure he's talking about the filters' cache.

**Comment by osminogig** [comment]
Yes, I would like to know about the filters' cache.
I asked at local forums - so far all are silent.
Who knows - prompt please !

**Comment by gorhill** [comment]
It holds a copy of downloaded resources.

**Comment by osminogig** [comment]
cache = last update
It is used to rollback updates

Do I understand correctly ?

**Comment by gorhill** [comment]
> cache = last update
> It is used to rollback updates

Yes.

For resources which are packaged within uBlock, the packaged version will be used. For resources which are not packaged with uBlock, this will force the remote resource to be downloaded.

**Comment by osminogig** [comment]
Thank you very much and good luck !
