### ISSUE TITLE
BBC News and BBC iPlayer won't load 

### ISSUE THREAD

**Issue by ReallyGlobal** [gorhill/uBlock#2191]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
BBC News and BBC iPlayer won't load in Firefox (all recent versions) with uBlock origin activated. The tab appears but the page stays white, the "wheel" next to the name in the tab keeps turning and never ever loads. I disabled uBlock Origin and the site now loads. The BBC has no ads, so it's not linked to running an adblocker. BBC News and BBC iPlayer runs, for example, with AdBlock Plus

### One or more specific URLs where the issue occurs
http://www.bbc.co.uk/news
http://www.bbc.co.uk/iplayer

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
With uBlock Origin activated - please note that this page where I am writing to YOU is not loading properly either. The "wheel" in the tab turs without stopping...

![image](https://cloud.githubusercontent.com/assets/24212935/20652194/b9fda9d0-b4f4-11e6-8bb1-c9051b05ec7f.png)

![image](https://cloud.githubusercontent.com/assets/24212935/20652187/a89f920c-b4f4-11e6-9c2c-ce0e89136c33.png)

![image](https://cloud.githubusercontent.com/assets/24212935/20652135/eeb40558-b4f3-11e6-84e4-e69c1094f5df.png)

With uBlock Origin disabled;

![image](https://cloud.githubusercontent.com/assets/24212935/20652230/936f7be4-b4f5-11e6-8114-690adadce116.png)

![image](https://cloud.githubusercontent.com/assets/24212935/20652239/d6ba4c80-b4f5-11e6-991e-638e4ce63870.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 50.0
- uBlock Origin version: 1.9.16

##### Your filter lists
Not sure where to find these...

![image](https://cloud.githubusercontent.com/assets/24212935/20652207/0bca12d0-b4f5-11e6-9ed7-a4d0713923cf.png)

chrome://ublock0/content/dashboard.html#3p-filters.html

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
![image](https://cloud.githubusercontent.com/assets/24212935/20652215/45910140-b4f5-11e6-850e-77cae8d8e916.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ReallyGlobal** [comment]
Fuck you. Will uninstall.
