### ISSUE TITLE
1.9.16 doesn't block by url path

### ISSUE THREAD

**Issue by viraptor** [gorhill/uBlock#2193]
### Describe the issue

Filters which include url path component are ignored. Domain filters still work.

### One or more specific URLs where the issue occurs

Example from easyprivacy list. The list contains filters:
||ga.webdigi.co.uk^
||geckofoot.com/gfcounterimg.aspx?

Blocked: ga.webdigi.co.uk
Not blocked: geckofoot.com/gfcounterimg.aspx?

### Steps for anyone to reproduce the issue

1. Choose any filter with path after the domain
2. Go to that url

### Your settings

- Browser/version: Chromium 54.0.2840.90
- uBlock Origin version: 1.9.16

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
URL where this can be seen?

**Comment by viraptor** [comment]
@gorhill literally provided above.
```
http://geckofoot.com/gfcounterimg.aspx?
```
is in easy privacy, but not blocked.

**Comment by gorhill** [comment]
You mean you are entering `http://geckofoot.com/gfcounterimg.aspx?` in the address bar?

**Comment by viraptor** [comment]
Yes.

**Comment by gorhill** [comment]
See: [Strict blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking).

If you want to strict-block a specific URL, use the `document` option: `||geckofoot.com/gfcounterimg.aspx?$document`.

**Comment by viraptor** [comment]
thanks!

**Comment by gorhill** [comment]
For reference, the way strict-blocking works is the result of feedback about how it was originally implemented: <https://github.com/chrisaljoudi/uBlock/issues/1128>.
