### ISSUE TITLE
Firefox: beacon.enabled option can't be disabled with uBO's "Disable hyperlink auditing" check box

### ISSUE THREAD

**Issue by gmlox** [gorhill/uBlock#2194]
I believe the title is self explanatory, according to:
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-hyperlink-auditingbeacon
this check box option is supposed to disable beacon.enabled option in Firefox -> about:config

How ever it doesn't have an effect on that option which is set to TRUE by default.

uBO version is: 1.9.16
Other firefox add ons are: noscript and HTTPS everywhere.
Firefox version is 45.5.0 from Debian repo.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1884#issuecomment-253813062

**Comment by gmlox** [comment]
I see, maybe I should have search trough open issues before opening new one, sorry.

From what I understood, this specific option is off the table?

**Comment by gorhill** [comment]
> From what I understood, this specific option is off the table?

Yes, by design. There are legitimate uses for `navigator.sendBeacon()`.

The wiki doc is not up to date, I need to work on it.

**Comment by gorhill** [comment]
The documentation was corrected in <https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings/_compare/2342353667de00b817cdcc81670f8aed1e154d43...637ab9f4434f334a6dfba6051a3bd42fc281ad53>.
