### ISSUE TITLE
regions language can't apply

### ISSUE THREAD

**Issue by gatspy** [gorhill/uBlock#2197]
After seleted  items in `regions language` can not be applied, open again the state changes to  unchecked

Env
- Browser/version: mac chrome 54.0.2840.98 (64-bit)
- uBlock Origin version: 1.9.16

**Comment by gorhill** [comment]
Did you click _"Apply changes"_ after you checked the filter lists?

**Comment by gatspy** [comment]
Oops, I think that is automatically saved the message. thank you .
