### ISSUE TITLE
Links are hidden on Firefox, but appear correctly on Chrome

### ISSUE THREAD

**Issue by JBey4you** [gorhill/uBlock#2199]
Hi,

There is a problem with uBlock Origin on Firefox. On certain pages, links are hidden, while they appear correctly on Chrome. Everything’s up-to-date with the same settings on both sides.

### One or more specific URLs where the issue occurs

http://www.igen.fr/telecoms/2016/11/free-mobile-lancera-ses-offres-de-noel-98010

### Screenshot in which the issue can be seen

![firefox](https://cloud.githubusercontent.com/assets/7979756/20759866/92c7f39e-b71e-11e6-8540-a314c9ed2c75.jpg)
On Firefox

![chrome](https://cloud.githubusercontent.com/assets/7979756/20759876/98c140e8-b71e-11e6-8baa-4b730c6a4e5c.jpg)
On Chrome

### Steps for anyone to reproduce the issue

Go to http://www.igen.fr/telecoms/2016/11/free-mobile-lancera-ses-offres-de-noel-98010
See last paragraph

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 51 / Chrome 54
- uBlock Origin version: 1.10.0 / 1.9.16

##### Your filter lists

![capture d ecran 2016-11-30 a 17 03 23](https://cloud.githubusercontent.com/assets/7979756/20760000/ecaa9e84-b71e-11e6-8a57-e93304a1334d.jpg)

##### Your custom filters (if any)

Don't have any.

**Comment by ddraws** [comment]
Filter list issue. Disable `FRA: EasyList`

**Comment by JBey4you** [comment]
It works indeed, but 1) the filter is enabled on Chrome and the links still appear correctly 2) I need this filter since I'm on multiple French websites.

**Comment by ddraws** [comment]
Best solution would be to copy the entire filter list on notepad, remove the offending filters and add it to uBO via custom filter lists panel.

Example: `file:///C:/Users/draws/documents/notes.txt`

**Comment by gorhill** [comment]
Unable to reproduce: the links are missing in both Chrome and Firefox -- due to a filter in EasyList France.

**Comment by JBey4you** [comment]
@ddraws : Are we sure it's related to EasyList though? Since it's working fine on Chrome with uBlock Origin. And like I said in the first post, everything's is up-to-date (filters too) on both Firefox and Chrome.

@gorhill: Really? Interesting. I can assure you that the EasyList France filter is enabled on Chrome with the screenshot provided above.

**Comment by gorhill** [comment]
> I can assure you that the EasyList France filter is enabled on Chrome with the screenshot provided above.

Is your no-cosmetic-filtering switch enabled for that site?

**Comment by JBey4you** [comment]
Nope, nothing is enabled for this site in particular.

**Comment by gorhill** [comment]
Can't help then: if I can't reproduce, I can't investigate. You need to provide all that is needed for me to reproduce.

**Comment by gorhill** [comment]
Also, you say _"Don't have any"_regarding custom filters, and yet your _"My filters"_ list says 23 filters are in effect.

**Comment by JBey4you** [comment]
I do have custom filters, indeed. When I said I didn't have any, I was referring to this site in particular. My bad for the confusion.

**Comment by gorhill** [comment]
This bug will stay forever labeled "unable to reproduce" if you can't provide info on how to reproduce. You still did not report about the logger. Does it show an entry for the blocking filter `##[href^="http://bit.ly/"]` for that page?

**Comment by gorhill** [comment]
> When I said I didn't have any, I was referring to this site in particular.

Generic exception filters are not for any specific site yet they apply everywhere. Do you have a custom filter `#@#[href^="http://bit.ly/"]`?

**Comment by JBey4you** [comment]
I'm not a expert I guess. :)

With the filter disabled, these appear in yellow:

- ##div[id^="dfp-ad-"]
- ##.dfp-tag-wrapper
- google-analytics.com/analytics.js
- igatus.com/*/angular-tag.js
- googletagservices.com/gpt.js

With the filter enabled:

- ##div[id^="dfp-ad-"]
- ##div[id^="block-dfp-728-"]
- ##[href^="http://fave.co/"]
**- ##[href^="http://bit.ly/"]**
- ##.sidebar div img
- ##.sidebar [id*="C"]
- ##.region-pubheader
- ##.dfp-tag-wrapper
- ##.bloc-accroches + h2 + br + [id]
- ##.article a[class]
- ##.article a > img

<blockquote> Do you have a custom filter #@#[href^="http://bit.ly/"]?</blockquote>
I don't.

**Comment by JBey4you** [comment]
I encounter this problem only with this site, so it’s okay if it can’t be reproduce/patched. Just wanted to see if something could be done, but it’s alright.

**Comment by gorhill** [comment]
You have any other extensions on Chrome which maybe changes the `bit.ly` links on the page?

**Comment by JBey4you** [comment]
I was able to reproduce on Chrome, and not on Firefox for some reason.

Settings: Tampermonkey installed, with the Anti-Adblock Killer | Reek script installed and the filter selected in uBlock Origin.

When the script is disabled in Tampermonkey, the links don't appear. When it's enabled, they're here.

I use Greasemonkey on Firefox, but nothing changes when the script is enabled or disabled.

**Comment by gorhill** [comment]
I can reproduce when installing Tampermonkey + Reek's user script.

**Comment by gorhill** [comment]
Ok, the issue is (roughly) that Reek's user script re-generate the document for that page, and uBO's own injected styles and scripts are removed as a result. Firefox does not have this issue because it is possible to disable specific inline script tag. With Chrome, it is not possible, so what is being done (guessing a bit here) is that the document is downloaded using a XHR and the bad inline scripts in it are removed, then the result is inserted as the main document -- meaning uBO's own changes to the document are clobbered.

So issue is incompatibility between Tampermonkey and uBO for that site -- though not harmful, only uBO's cosmetic filtering is broken, network filtering is not affected.

Side note: I have actually been thinking about that sort of solution to bring specific inline script tag filtering to Chromium-based browsers, but using CSP directives instead (`nonce-...`) -- something I have experimented superficially with in the past.
