### ISSUE TITLE
Norwegian sites shows info about ads beeing blocked (and that is just as bad as ads)

### ISSUE THREAD

**Issue by LarsErikOsterud** [gorhill/uBlock#220]
Several norwegian sites has done something to their pages that show lots of banners asking you to turn ads back on when using an ad-filter. Is there a way to block these "ads" too?

For example go to "http://www.aftenposten.no" and see all the "Skru på annonser" boxes :-(

You might need to ad the "NOR norwegian ad-block list" first.

**Comment by gorhill** [comment]
Filter lists are third-party to uBlock, you need to inquire to the filter list maintainers (I don't maintain filter lists myself, coding is already plenty of work).
