### ISSUE TITLE
Easier install process for Opera on Android?

### ISSUE THREAD

**Issue by albell** [gorhill/uBlock#2202]
I switched to Opera on my phone recently, mostly because it offers a free VPN. On the minus side, the Opera store doesn't seem to cover mobile extensions at all. When a user visits the Opera store on Android, there's a big banner that says "These extensions and themes are made for the desktop version of the Opera Browser."

I've fumbled with the manual uBlock installation instructions on Chromium but haven't gotten it working yet. Just a data point that it would be great if this were easier to get going. "Single click install" and all that. Any pointers very much appreciated.

Thanks for an awesome tool. I've successfully pushed it on many friends and acquaintances.

**Comment by gorhill** [comment]
Extensions are not supported on Chrome for Android, I expect it's the same thing for Opera -- both are Chromium-based browsers. Use Firefox for Android if you want to use uBO.
