### ISSUE TITLE
1.10 Chrome store

### ISSUE THREAD

**Issue by TES999** [gorhill/uBlock#2205]
It's been what, 3-4 days and the 1.10 still haven't been pushed to the Chrome store, what gives?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
It's coming, please be patient.

I really shouldn't have to deal with such invalid issues, be considerate.

**Comment by uBlock-user** [comment]
It will appear when he decides to upload, until then hold your breath.

**Comment by TES999** [comment]
Wasn't meaning to be a dick about it, merely thought it had slipped your mind.
