### ISSUE TITLE
added 2 hotkeys for viewing panel in Pale Moon

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2207]
This is a follow-up to #2188 and #2151. Thankfully I eventually figured out how to get both hotkeys working in Pale Moon, so now I have:
* Alt+P for regular open/close of the panel (just like clicking the button)
* Ctrl+Alt+P for opening the panel in a new tab

Here's the patch:
[vapi-background.js.diff](https://github.com/gorhill/uBlock/files/625885/vapi-background.txt)

Note the need for a flag so that Alt+P knows the state of the panel. This syncs it perfectly with the existing panel events of mouse clicks to open/close and pressing Escape to close. Thus it all works just like on Chromium.

Also note you may need to add "&fullsize=1" to the new tab URL for a panel without vertical restrictions. I personally don't need that in my own modified uBO, per #2153.

These new hotkeys will likely work on other Mozilla browsers too.

**Comment by joey04** [comment]
Follow-up post. I was using my modified uBO v1.10.0 in Pale Moon until this past week. (The effort to figure it out was well worth it; I've used the hotkeys literally hundreds of times.) Now I've moved to the latest v1.12.4 with the same modifications. The hotkey patch is still valid, and I also have my panel changes. (In my supplemental browsers, Firefox and GChrome, I just use regular uBO from the official extension stores.)

I'm closing this because Mozilla is currently killing off XUL addons, so this patch will only work for Pale Moon beyond Firefox 52 ESR end-of-life, assuming it still does work in Firefox 52; I've never tested it outside of Pale Moon. Plus, SeaMonkey and the various Firefox rebuilds will no longer have XUL addons after 52 ESR.

**Comment by joey04** [comment]
@gorhill thanks for adding the hotkeys for the XUL version in #113.

So I'm re-opening this to suggest adding my patch's Alt+P hotkey (in the first post above). The relevant portions should be usable alongside the hotkeys you already added earlier today. This way the XUL version will have the same panel opener as Chrome & Webext.

(And the new tab hotkey also comes in handy, if you're interested.)

**Comment by gwarser** [comment]
`https://github.com/gorhill/uBlock/files/625885/vapi-background.txt`

Wrong link?

**Comment by joey04** [comment]
No, it's same patch URL as originally posted. Still works fine in 1.12.4

**Comment by joey04** [comment]
@gorhill Now that Firefox hotkeys are no longer enabled by default with the latest commit, could you add my patch hotkey to vapi-background? It too should be disabled by default.

To be clear, it's not just for Pale Moon. It'll work in current Firefox and other derivatives. It would be nice to have panel opener hotkey the same as Chrome.

**Comment by joey04** [comment]
Might as well close this for good now that gorhill's focus understandably now on Webext for Firefox.

These hotkeys still work great for me, so the patch in the original post is very much alive for those interested.
