### ISSUE TITLE
Feature comparision?

### ISSUE THREAD

**Issue by s-timm** [gorhill/uBlock#221]
Hi!
I would like to switch from ADP to uBlock/uBlockO. 

However, I am still confused as to what the differences are between uBlock and uBlock Origin.
Is there a feature comparison available?

**Comment by CrisBRM** [comment]
uBlock does everything ABP does, and supports hosts files, has dynamic filtering, extended filter syntax, a better network logger, is lighter, faster, and even USED to have local mirroring (not anymore, sadly).
Next time read the wiki though: https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#abp-has-all-the-features-ublock-has

**Comment by alejandrolemus** [comment]
There is no dedicated document with a comparison, AFAIK. Some things I can think of (search both projects issues and wiki for more details):

uBlock has a more polished and user-friendly UI, no per-site switches (popup and strict-blocking), global and local scope columns reverted, better support for Safari and older versions of Gecko.
