### ISSUE TITLE
An option to remove elements from DOM with cosmetic filters

### ISSUE THREAD

**Issue by rowaasr13** [gorhill/uBlock#2211]
Right now cosmetic filters simply add "display: none" to relevant elements - just as documented and as other blockers do with this class of filters. Is it possible to add an option to completely delete matched elements from DOM?

The goal of such option would be to futher reduce page's footprint which would be especially important to people who keep hundreds of tab open (like me).

If it is not possible on injection phase, some unique token can be injected along with "display: none" to style or attributes and then subsequent delayed pass can go over those elements and remove them after load.

**Comment by gorhill** [comment]
Element removal is not something to be used except *maybe* in very exceptional cases, such that this would maybe better left to a scriplet. The main issue is that removing elements may unleash mayhem in the DOM. Consider a filter such as:

    ###blah:first-child + div

Normally, only one element will be targeted by such filter. However if you remove the targeted element, an new one become targeted, until there is no more `div` to remove. So removing elements as a good potential to seriously change the semantic of existing filters.

At most I have entertained the idea of a `:remove` operator, but the need for it needs to be justified with enough real world cases.

For the stated reasons, declined.

**Comment by zylstra** [comment]
How can the videos on the software pages (for example, http://download.cnet.com/Adblock-Plus-for-Chrome/3000-33362_4-75118867.html) of dowload.cnet.com be silenced and hidden?
