### ISSUE TITLE
Is it possible to disable ublock for specific youtube users

### ISSUE THREAD

**Issue by oliwaa** [gorhill/uBlock#2214]
is it possible to disable Ublock for specific YouTube users?
this is for users i support and don't want to block their income

I am using the latest version of ublock so if it is already possible, how?
Thanks

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#a-youtube-channel
