### ISSUE TITLE
google-analytics(.ext) named images are blocked

### ISSUE THREAD

**Issue by nekromoff** [gorhill/uBlock#2217]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
blocking any image called google-analytics(.gif)
### Steps for anyone to reproduce the issue
create a linked image (img src) called google-analytics.gif in a html page
image is blocked on load

### Your settings
hiding items
disabled preloading, auditing, webrtc

- Browser/version: Firefox 50.0.2
- uBlock Origin version: 

##### Your filter lists
default + filters:
- privacy
- unbreak
- anti-adblock killer
- easylist
- easyprivacy
- pete lowe's
- cze, svk

##### Your custom filters (if any)
cosmetic not affecting this issue

**Comment by gorhill** [comment]
> create a linked image (img src) called google-analytics.gif in a html page
image is blocked on load

Easy workaround: name it something else. If you think this is unacceptable workaround, report your issue to the maintainers of the filter list which contains the filter which blocks you image.

**Comment by nekromoff** [comment]
How can I identify, which filter blocked this?

**Comment by gorhill** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates).

**Comment by nekromoff** [comment]
Thanks, reported to easylist.
