### ISSUE TITLE
uBlock origin stopping a plugin from loading on Chrome startup

### ISSUE THREAD

**Issue by MathieuDR** [gorhill/uBlock#2218]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
uBlock is blocking another plugin from loading on Chrome startup

### One or more specific URLs where the issue occurs
https://app.youneedabudget.com/[GUID]/budget
### Screenshot in which the issue can be seen
/
### Steps for anyone to reproduce the issue
1. Have the 'Toolkit for YNAB' installed
2. Have uBlock Origin installed
3. Have YNAB as one of the homepages
4. Close Chrome (completely)
5. Open Chrome (With YNAB as one of the homepages)
6. Select the Tab with YNAB
7. See that the toolkit isn't loaded (Issue)
8. (Refresh tab)
9. (Toolkit is now loaded)

### Your settings
```
{
  "timeStamp": 1480945126407,
  "version": "1.10.0",
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": true,
    "externalLists": "! Examples:\n! https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt\n",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "filterLists": {
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "entryCount": 69553,
      "entryUsedCount": 69496,
      "group": "ads",
      "homeURL": "https://easylist.to/easylist/easylist.txt",
      "off": false,
      "supportURL": "https://forums.lanik.us/",
      "title": "EasyList"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "entryCount": 12229,
      "entryUsedCount": 12192,
      "group": "privacy",
      "homeURL": "https://easylist.to/easylist/easyprivacy.txt",
      "off": false,
      "supportURL": "https://forums.lanik.us/",
      "title": "EasyPrivacy"
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "entryCount": 12231,
      "entryUsedCount": 12204,
      "group": "malware",
      "homeURL": "https://mirror.cedia.org.ec/malwaredomains/justdomains",
      "off": false,
      "supportURL": "http://www.malwaredomains.com/",
      "title": "Malware domains"
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "entryCount": 2367,
      "entryUsedCount": 2367,
      "group": "multipurpose",
      "homeURL": "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext",
      "off": false,
      "supportURL": "https://pgl.yoyo.org/adservers/",
      "title": "Peter Lowe’s Ad and tracking server list"
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "entryCount": 1250,
      "entryUsedCount": 1250,
      "group": "malware",
      "homeURL": "https://www.malwaredomainlist.com/hostslist/hosts.txt",
      "off": false,
      "title": "Malware Domain List"
    },
    "assets/ublock/experimental.txt": {
      "group": "default",
      "instructionURL": "https://github.com/gorhill/uBlock/wiki/Experimental-filters",
      "off": true,
      "supportURL": "https://github.com/gorhill/uBlock/wiki/Experimental-filters",
      "title": "uBlock filters – Experimental"
    },
    "assets/user/filters.txt": {
      "entryCount": 1,
      "entryUsedCount": 1,
      "group": "default",
      "off": false
    }
  },
  "hiddenSettingsString": "ignoreRedirectFilters false\nignoreScriptInjectFilters false\npopupFontSize unset\nsuspendTabsUntilReady false",
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nopera-scheme\nvivaldi-scheme",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": "! 10/4/2016, 9:11:08 AM http://www.nieuwsblad.be/\n||1.adhesecdn.be/pool/lib/145990_2nd.jpg?t=1475507058000$image\n"
}
```

Operating System (Mac/Windows/Etc): Windows
Browser (Chrome/Firefox/Safari): Chrome
Browser Version: Version 55.0.2883.75 m
uBlock Origin version: 1.10.0

##### Your filter lists
'3D Party Filters'

```
 My filters‎ : 1 used out of 1
 uBlock filters‎ : 871 used out of 873purge cache
 uBlock filters – Badware risks‎  (github.com): 7 used out of 7purge cache
 uBlock filters – Privacy‎ : 52 used out of 52purge cache
 uBlock filters – Unbreak‎ : 119 used out of 120purge cache
 EasyList‎ (forums.lanik.us): 69,496 used out of 69,553purge cache
 EasyPrivacy‎ (forums.lanik.us): 12,192 used out of 12,229purge cache
 Malware Domain List‎ (malwaredomainlist.com): 1,250 used out of 1,250purge cache
 Malware domains‎ (www.malwaredomains.com): 12,204 used out of 12,231purge cache
Peter Lowe’s Ad and tracking server list‎ (pgl.yoyo.org): 2,367 used out of 2,367purge cache
```
No customs.

'My Filters'
```
! 10/4/2016, 9:11:08 AM http://www.nieuwsblad.be/
||1.adhesecdn.be/pool/lib/145990_2nd.jpg?t=1475507058000$image
```

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets. **Use the logger to diagnose/confirm filter-related issues**. If something does not work properly with uBO enabled, **the first step is to rule out filter-related issues.**

What did you do to rule out a filter list issue?

**Comment by ySomic** [comment]
> What did you do to rule out a filter list issue?

I've used (or tried to use) 2 things.
1. After a refresh, the page loads correctly. It's only on Chrome start up.
2. I tried using the logging as fast as possible when Chrome started up. However I'm not sure if I got everything and if I read it out correctly.

The only thing blocked by uBlock was a 'google-analytics.com'
On startup: http://i.imgur.com/ibnfqvt.png (No plugin)
After reload: http://i.imgur.com/Hlqr7e7.png (Plugin is loaded)

I hope this is suffice and I hope I did not miss a step.

**Comment by gorhill** [comment]
From your screenshots of the logger, I deduce the issue is caused by uBO not being fully ready internally (still loading its assets), and as a consequence the Google Analytics ("GA") script is not being redirected to the neutered version. Probably it's a site which would break without the neutered version of GA's script.

This is related to a by-design browser issue: the browser does not wait for extensions to be fully ready before loading tabs.

However, I added an experimental setting in uBO 1.10.0 which may fix your issue. Paste the url

    chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/advanced-settings.html

in the address bar of a new tab.

Change the value of the `suspendTabsUntilReady` setting to `true`. Close the tab.

See if this fixes your issue.

**Comment by ySomic** [comment]
Yes

This solves the issue. Chrome is quite slow on the startup thought. 
Should I notify YNAB/YNAB Toolkit team of this so they can fix the breaking without GA or can I do anything else for this issue?

I'm sorry if I could have fixed/deduced this myself and wasted your time.
Thank you for the swift support/bugfix.

**Comment by gorhill** [comment]
> Chrome is a bit slower on the startup thought.

There should not be much difference, all network requests are blocked at start up, meaning less work to do until uBO is ready. However if a network request was blocked for a given tab, uBO is forced to reload that tab once all its filters/rules are loaded.

**Comment by rizhee** [comment]
uBO stooper working on chrome 55. http://screencast.com/t/Ns3xPfXKlt same problem on 2 PC's

**Comment by gorhill** [comment]
Your issue is with your installation. Something messed up your uBO installation, or your browser itself is messed up. I test with Google Chrome 56 here and all is fine.

**Comment by rizhee** [comment]
reinstalled and everything is ok now.
