### ISSUE TITLE
Can't block individual pages/scripts

### ISSUE THREAD

**Issue by PekaFat** [gorhill/uBlock#2219]
### Describe the issue
When i enter in my filter lists link like:
||site.com/path/js/script.js
uBlock just does nothing, but when i add whole site.com - it's blocks fine. Same problem with filters like "||site.com/patch/js/*" - this filter does block nothing.

### One or more specific URLs where the issue occurs
https://music.yandex.ru/pushwoosh-service-worker-light.js

### Your settings
- Browser/version: Google Chrome 55.0.2883.75
- uBlock Origin version: 1.10.0

##### Your filter lists
All, except "uBlock filters – Privacy‎", "uBlock filters – Experimental‎" and in lang filter lists:
 RUS: Adguard Russian Filter‎
 RUS: BitBlock List
 RUS: RU AdList
##### Your custom filters (if any)
||https://music.yandex.ru/pushwoosh-service-worker-light.js

**Comment by PekaFat** [comment]
Just tested some "official" filter lists, like https://easylist-downloads.adblockplus.org/advblock.txt, and there is all filters like "site.com/path/" not working too.

**Comment by okiehsch** [comment]
If you want to block a specific URL/script use the `document` option.
`||site.com/path/js/script.js$document`

Your example:
`||https://music.yandex.ru/pushwoosh-service-worker-light.js$document`

**Comment by PekaFat** [comment]
> If you want to block a specific URL/script use the document option.

It's working now, but i remember i'm just add link and ublock is block it, without any addictions like "$document", and also - so many filters for example https://easylist-downloads.adblockplus.org/advblock.txt (socialmart.ru/widget/) just broken now, it's not blocked and i can open any link. And it's only 1 "$document" here in "@@||my.south.rt.ru^$document", so devs of these filters will need put "$document" to all links like this? Why ublock devs do that?

**Comment by okiehsch** [comment]
There is a difference between strict blocking an url path and a "normal" network filter.
For example the filter
`||ptf.com/js/fdm_banner.js` in `https://easylist-downloads.adblockplus.org/easylist.txt`
Now go to `ptf.com`
you will see that `ptf.com/js/fdm_banner.js` is blocked, 
but you can still go to `ptf.com/js/fdm_banner.js`
the `document` option prohibits even that.

**Comment by PekaFat** [comment]
> There is a difference between strict blocking an url path and a "normal" network filter.

Oh.. Then i'm sorry for misunderstanding...

![default](https://cloud.githubusercontent.com/assets/13280748/20908988/326ceb00-bb72-11e6-984f-c8c1346c75d7.PNG)
