### ISSUE TITLE
Feature comparison?

### ISSUE THREAD

**Issue by s-timm** [gorhill/uBlock#222]
Hi!
I would like to switch from ABP to uBlock/uBlockO. 

However, I am still confused as to what the differences are between uBlock and uBlock Origin.
Is there a feature comparison available? What are the main differences?
I only found a hint about "per-site switches". Anything else?

Thanks.

**Comment by gorhill** [comment]
http://en.wikipedia.org/wiki/UBlock

**Comment by donateur** [comment]
I was going to ask the same question.

Could the link to the Wikpedia article be put somewhere in the documentation?  Perhaps under the Philosophy section?
