### ISSUE TITLE
outlook.live.com server not found

### ISSUE THREAD

**Issue by st1led** [gorhill/uBlock#2221]
### Describe the issue
There is something weird going on with the domain outlook.live.com. When using ublock origin, the site won't just load, as if it is a wrong domain. Firefox indeed reports the typical error page

```
Server not found

Firefox can’t find the server at outlook.live.com.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```
In the ublock Logger I see nothing being blocked (the ublock icon also does not report any number, which means no filter is triggered). Apparently, the only workaround is to completely disable ublock for the domain outlook.live.com. I also tried to purge the cache of all filters and re-download them, but with no success.

I bet this has something to do with Mac OS, because with the exact same settings I have no issues on Windows 10.

### One or more specific URLs where the issue occurs
outlook.live.com

### Steps for anyone to reproduce the issue
1. Visit outlook.live.com with ublock on, and the settings below

### Your settings
- Browser/version: 50.0.2 running on Mac OS X Sierra (10.12.1)
- uBlock Origin version: 1.10.0

##### Your filter lists
Cosmetic filters ON (but generic cosmetic filters ignored)
All ublock filters except the experimental ones
All 4 Ads filters
All 3 Privacy filters
All 6 Malware domains filters
All 3 Social filters
All 5 Multipurpose filters
EU Prebake
ITA ABP
ITA Easylist Italy

**Comment by gorhill** [comment]
What did you do to rule out a filter list issue?

**Comment by gorhill** [comment]
Instead of me trying with all your filter lists, I would rather you try with default uBO setting, and no other extension, and no Tracking Protection enabled in Firefox. When you use the logger, use the _All_ entry in the drop down list.

**Comment by st1led** [comment]
I'm replying a bit late, but this took quite some time to debug. After trying a large combination of 

- Tracking Protection on/off
- Resetting uBlock to the default settings
- Adding filters
- Updating filters
- Rebooting Firefox
- Installing/Reinstalling Firefox
- Tampering with my user profile

I (think I) managed to solve the issue. It was most likely some old / conflicting configuration setting that was not evident from the uBlock preferences page. Thank you very much!
