### ISSUE TITLE
Image blocked with 'google-analytics' in URL

### ISSUE THREAD

**Issue by tomjanssens** [gorhill/uBlock#2223]
### Describe the issue

When `google-analytics` is part of the URL the resource is being blocked by uBlock.

### One or more specific URLs where the issue occurs

Same image, two different URLs:

* Bad: https://www.joomlatools.com/images/documentation/docman/integrations/google-analytics/top-events.png
* Good: https://www.joomlatools.com/images/documentation/docman/integrations/ga/top-events.png

### Steps for anyone to reproduce the issue

Compare the above two links.

### Your settings

- Browser/version: Chrome 55.0.2883.75 (64-bit)
- uBlock Origin version: v0.9.5.0

##### Your filter lists

Stock uBlock without settings changes.

**Comment by mapx-** [comment]
You should use ublock origin (current version 1.10.0) not an outdated ublock
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
