### ISSUE TITLE
[Chrome] $generichide sometimes does not work

### ISSUE THREAD

**Issue by F4z** [gorhill/uBlock#2225]
uBlock Origin 1.10.0/1.10.1b1
Google Chrome 55.0.2883.75 m

Default filter lists + "Anti-Adblock Killer | Reek"‎ + "POL: polskie filtry do Adblocka i uBlocka‎"

I noticed that `$generichide` sometimes does not work correctly.

Steps to reproduce.
1. Open logger
2. Go here - `http://vod.pl/filmy-i-bajki-dla-dzieci/planet-hulk-hulk-na-obcej-planecie/6yxxbzw`
3. Look in the logger
![image](https://cloud.githubusercontent.com/assets/11742596/20980638/a1db1ab2-bcb1-11e6-87d4-7d7d4d14b63a.png)
I think `##.text-ad` should not be hidden, because in "POL: polskie filtry do Adblocka i uBlocka‎" is this rule - `@@||vod.pl^$generichide`

If I add this rule - `@@||vod.pl^$generichide` to "My filters", it works correctly.

![image](https://cloud.githubusercontent.com/assets/11742596/20981149/b461dc50-bcb3-11e6-9ed3-373846eac071.png)

**Comment by gorhill** [comment]
Can you reproduce without Reek's?

**Comment by gorhill** [comment]
Never mind, I can reproduce without Reek's.

**Comment by gorhill** [comment]
For the record, this was caused by a regression bug as a result of the fix to #2103.

**Comment by F4z** [comment]
With the latest version (1.10.1rc1) it works properly.
Thank you.
