### ISSUE TITLE
Incompatibility between ABP and uBO over FETCH (json)

### ISSUE THREAD

**Issue by k2jp** [gorhill/uBlock#2226]
Thank you for maintaining uBO!

### Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>
done

### Describe the issue
FETCH requests are blocked after `|http:$ping` is added.

### One or more specific URLs where the issue occurs
http://www.compareyourcountry.org/pisa/?lg=en (JavaScript is required)

### Screenshot in which the issue can be seen
**BEFORE** `|http:$ping` is added
![Developer Tools](http://cdn-ak.f.st-hatena.com/images/fotolife/k/k2jp/20161208/20161208112619.png) &uarr; **FETCH** (json)

**AFTER** `|http:$ping` is added
![uBO logger](http://cdn-ak.f.st-hatena.com/images/fotolife/k/k2jp/20161208/20161208112614.png) &uarr; **other** (blocked)

![ABP blockable items](http://cdn-ak.f.st-hatena.com/images/fotolife/k/k2jp/20161208/20161208112616.png) &uarr; **$xmlhttprequest** (not blocked)

### Steps for anyone to reproduce the issue
 1. Install and Disable uBlock Origin 1.10.0 and Adblock Plus 2.8.2.
 1. Open http://www.compareyourcountry.org/pisa/?lg=en
 1. Use Firefox 50.0.2 build-in developer tools via **Web Developer** &rarr; **Network** and confirm that `/maps.js?` requests belong to **FETCH** (json) after you reload the page.
 1. Enable uBlock Origin and add `|http:$ping`.
 1. Open the **Logger** and reload the page.
 1. Confirm that `/maps.js?` requests belong to **other** and are **blocked**. This result is unexpected for me.
 1. Disable uBlock Origin
 1. Enable Adblock Plus and add `|http:$ping`.
 1. Open **Blockable Items** and reload the page.
 1. Confirm that `/maps.js?` requests belong to **xmlhttprequest** and are **NOT blocked**.

 - You notice that...
   - uBlock Origin interprets `|http:$ping` as `|http:$other`.
   - uBlock Origin treats **FETCH** as **other**.
 These deference causes incompatibility.

 - Note: I know that uBlock Origin has a setting "**Disable hyperlink auditing/beacon**" and `$ping` filter option is dispensable. However, it would be nice if this incompatibility is fixed!

### Your settings
 - OS: Windows
 - Browser: Cyberfox 50.0.2 (Firefox 50.0.2 compatible) JavaScript enabled
 - uBlock Origin 1.10.0
 - Adblock Plus 2.8.2

##### Your filter lists
This issue is not depend on specific filter lists.

##### Your custom filters (if any)
`|http:$ping`

**Comment by gorhill** [comment]
uBO will map `fetch` to `xmlhttprequest` (`xhr` in logger), that is a quick fix.

However I will implement `ping` eventually.

**Comment by k2jp** [comment]
#### Confirmed the fix. Many thanks!
![uBO 1.10.1rc1](http://cdn-ak.f.st-hatena.com/images/fotolife/k/k2jp/20161208/20161208183359_original.png)

##### Support for ping
Understood.

**Comment by k2jp** [comment]
Reopened for the ping support ;p

**Comment by gorhill** [comment]
Actually, there is already [an issue](https://github.com/gorhill/uBlock/issues/1493) for `ping`, I reopened this one as the substance of the issue here was missing mapping between `TYPE_FETCH` and `xmlhttprequest` in Firefox.

**Comment by k2jp** [comment]
Understood. 
Thanks for the explanation.
