### ISSUE TITLE
Invisible text in dynamic filter pane and "My Rules" tab

### ISSUE THREAD

**Issue by ivso** [gorhill/uBlock#2227]
In Firefox 50.0.2 with uBlock0 1.10.0 the two UI elements with alternating row shading -- the dynamic filtering pane (in medium mode) and the "My Rules" tab on the uBlock0 Dashboard -- appear empty as can be seen on the screenshot below: 

![image](http://i.imgur.com/ONDHlxH.png)
The "My Rules" tab shows two empty rows for the default rules (temporary and permanent) but when trying to edit these the text remains invisible (as if there are no rules at all).

Note: uBlock0 1.9.16 works as expected.

**Comment by gorhill** [comment]
You have user styles in your browser (or a theme)? Can you try with a new profile?

**Comment by ivso** [comment]
No user styles, before reporting the issue I created a new (clean) profile.

**Comment by gorhill** [comment]
Can you use Firefox's Inspector to investigate the style of the text?

I suspect the text is in there, but styled in a way that makes it invisible. You can open the popup panel in a tab by pressing Shift-Ctrl and clicking on the "all" cell in the dynamic filtering pane (the left-most, top-most cell).

Once the popup panel is opened in its own tab, it becomes possible to use the Inspector to investigate the CSS applied to the cells.

**Comment by gorhill** [comment]
Example:

![a](https://cloud.githubusercontent.com/assets/585534/21011674/44979c9e-bd20-11e6-9c0b-19a885447539.png)

**Comment by gorhill** [comment]
Something specific to the dynamic filtering pane since 1.10.0 is that it is styled to use the font "Noto Sans" if it's available, otherwise it falls back to the browser's "sans-serif".

**Comment by ivso** [comment]
The full Noto font set is available, below is the panel as shown in the Inspector:
![The Dynamic Filtering Pane in Inspector](http://i.imgur.com/uMzWwcO.png)

**Comment by gorhill** [comment]
You are not looking at the right element. See my picture again: I focused on the cell, not the row. See if there is text in the cell with the Inspector. This is the first thing to verify.

Also, the Inspector just shows the CSS rules applied, it does not mean that the "full Noto font set is available".

What is your OS?

**Comment by DrunkenSasquatch** [comment]
@gorhill This also tends to happen when notifications are being used by another extension, but it's only temporary until the notifications disappear.

**Comment by ivso** [comment]
I have updated my comment above to clarify things.

For testing purposes I have installed a chromium-based browser (Vivaldi (stable) 1.5.658.56; User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.56) on the same PC (running Linux: Ubuntu 16.04, customized) and **there I don't have this issue** with the latest uBlock0 release.

This observation leads me to suspect some GTK3-theming problem as I have noticed several transparent/semi-transparent elements in the Firefox UI, such as add-on installation notifications (transparent); the hamburger menu (semi-transparent). To further investigate this I have run the browser with the command-line parameter `env GTK_THEME=Adwaita:light firefox` (that is supposed to make Firefox ignore transparency); now the menu and the notifications are not transparent anymore, but the problem with the invisible text in uBlock0 still remain...

**Comment by gorhill** [comment]
So the text is there on your side. Can you now select the `span` element which contains the text? I would like to see all the applied styles.

**Comment by ivso** [comment]
The styles for `<span>` (slightly scrolled down to fit all the styles into the window):
![styles for span](http://i.imgur.com/jCoaJIA.png)

The styles for `::before`
![styles for span-before](http://i.imgur.com/YajdLWf.png)

**Comment by gorhill** [comment]
I see all is fine with the styles. I think at this point it's a issue specific on your side, outside of uBO's realm. The popup panel is really just plain HTML/CSS/javascript, and if it does not render fine, something else is interfering. Best is you investigate on your side using the inspector from the browser toolbox.

**Comment by ivso** [comment]
@gorhill I'll do my best to investigate, but I think you might have an idea why uBlock0 1.9.16 works just fine...

**Comment by gorhill** [comment]
> I think you might have an idea why uBlock0 1.9.16 works just fine on the same setup

No I don't. uBO's popup panel is plain HTML/CSS, there is no reason why it should have an issue rendering in Firefox.

> I have installed a chromium-based browser [...] and there I don't have this issue [...] This observation leads me to suspect some GTK3-theming problem

For now I will close this issue as an external one. If you can make the case there is an issue with uBO itself, I will re-open.
