### ISSUE TITLE
cant select div

### ISSUE THREAD

**Issue by treakiandroid** [gorhill/uBlock#2232]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md> done

### Describe the issue

i cant select the div with the class "quicktip aufruf-winter" to be hidden

on pages like

https://metager.de/meta/meta.ger3?eingabe=testsuche&focus=web&encoding=utf8&lang=all

i tried the rule:

metager.de###quicktip aufruf-winter

### One or more specific URLs where the issue occurs

https://metager.de/meta/meta.ger3?eingabe=testsuche&focus=web&encoding=utf8&lang=all

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.
1. go to the site
2. select ublock's picker mode
3. try to pick the red "aufruf" at the left
4. not working, just selects the whole block at the left
5. open developer tools, find out that it is inside a iframe with a div with class="quicktip aufruf-winter"
6. tried to modify block entry acording to but not working
7. maybe its because theres a blank space inside the class designator...

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: firefox esr 45.4.0
- uBlock Origin version: 1.10.0

##### Your filter lists
not relevant

##### Your custom filters (if any)

metager.de###quicktip aufruf-winter

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
