### ISSUE TITLE
Unable to upadte the list hpHosts’s Ad and tracking servers‎ in uMatrix when uBlock O is activated

### ISSUE THREAD

**Issue by 2drui** [gorhill/uBlock#2233]
I try to update the list "hpHosts’s Ad and tracking servers‎ (hosts-file.net)" in uMatrix but it don't works.
I try again with uBlock O discativated and it works.
All filters activated

**Comment by gorhill** [comment]
Did you use uBO's logger to investigate?

**Comment by gorhill** [comment]
I will reopen if and only if you actually make the case there is an issue with uBO. Your 3-sentence issue is not a valid way to make the case there is an issue with uBO.

**Comment by 2drui** [comment]
DESCRIBE THE ISSUE
I try to update the list "hpHosts’s Ad and tracking servers‎ (hosts-file.net)" in uMatrix but it don't works.
I try again with uBlock O discativated in the addon panel and it works.

ONE URL WHERE THE ISSUE OCCURS
chrome://umatrix/content/dashboard.html#hosts-files

SCREENSHOTS IN WICH THE ISSUE CAN BE SEEN
http://image.noelshack.com/fichiers/2016/50/1481633635-exemple.jpg
http://image.noelshack.com/fichiers/2016/50/1481633641-exemple1.jpg

STEPS TO REPRODUCE THE ISSUE
I don't know if this issue is specific to my browser but:
go to uMatrix Hosts filters panel, empty the caches and try to update the filters. All filters update correctely except "hpHosts’s Ad and tracking servers‎ (hosts-file.net)".
Go to addon panel of Firefox, disable uBlock O and retry to update the filter, now it should work.

MY SETTINGS
Firefox 50.0.2
uBlock Origin v1.10.0

MY FILTER LISTS
All filters activated + EU: Prebake - Filter Obtrusive Cookie Notices + FRA: EasyList Liste FR‎

CUSTOM FILTER
||cdndoge.xyz/lib/sweetalert/
@@||video-download.online/*ad

PS: sorry for the poor issue description yesterday, I was in bed and so tired. Hope it should help now.
Regards.

**Comment by gorhill** [comment]
> The uBlock O logger give no information, the page is blank even after reloading.

Use the _All_ entry in uBO's logger's drop down list, then try to force an update of the lists in uMatrix. Using the logger is a mandatory step for such network-related issue.

**Comment by jjohns71** [comment]
@2drui I had the same problem on Firefox on one of my systems, but not on another weirdly enough. I found it was an easylist filter issue with one of their Static filters:  
`.net/ad_`

![easylist](https://cloud.githubusercontent.com/assets/6795795/21145964/1d019d40-c11e-11e6-9e0a-f7dbe6af87ed.png)


Adding the following rules to 'My rules' tab allows the uMatrix filter list to be updated.

`behind-the-scene http://hosts-file.net/ad_servers.txt xmlhttprequest allow`
`behind-the-scene https://hosts-file.net/ad_servers.txt xmlhttprequest allow`

Alternatively, you can add the following Static filter to the 'My filters' tab:
`||hosts-file.net/ad_servers.txt$xmlhttprequest,domain=behind-the-scene`

![easylist2](https://cloud.githubusercontent.com/assets/6795795/21146093/8298ff7c-c11e-11e6-8b95-f6e27c22066a.png)

Either fix should allow you to download the update for uMatrix. 

Good luck!

**Comment by 2drui** [comment]
Effectively I have accidentaly deleted a whitelist line. So after reseting uBO to defaut settings I try to udate the problematic filter in uMatrix and all works fine.
Thanks for the help and for the good work in general.
