### ISSUE TITLE
uBlock removes product images from E-Commerce website 'royalrobbins.com'

### ISSUE THREAD

**Issue by lexmustafin** [gorhill/uBlock#2234]
Hi,

We have noticed that the product images are being removed by uBlock:

With uBlock: 
http://screencast.com/t/B2vTQ4yOCHSu

without uBlock: http://screencast.com/t/ozwrleB7B2

Example product link: https://www.royalrobbins.com/women/t-shirts/lasting-impressions-tee-1

Can you please help to resolve this issue?

**Comment by mapx-** [comment]
add
`@@||cdn.godatafeed.com/analytics/tracking.min.js$domain=royalrobbins.com`

**Comment by mapx-** [comment]
reported at easylist forum
https://forums.lanik.us/viewtopic.php?f=64&t=34554

**Comment by lexmustafin** [comment]
Thanks for prompt reply. Where should we add it?

**Comment by lexmustafin** [comment]
@mapx- ,

Thanks.

**Comment by mapx-** [comment]
you have to wait the easylist authors to add that exception to easyprivacy list

**Comment by lexmustafin** [comment]
is there any ETA for adding it by authors?

**Comment by mapx-** [comment]
or ... analyze your code to "disconnect" that tracking script from other events on page

**Comment by mapx-** [comment]
no ETA: they have to note the thread, decide what to do ..

**Comment by mapx-** [comment]
anyway, for other ubo filter issues use 
https://github.com/uBlockOrigin/uAssets/issues

or easylist forum (linked above)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
