### ISSUE TITLE
Ublock prevents bookmarks from saving.

### ISSUE THREAD

**Issue by syspal** [gorhill/uBlock#2235]
Ublock prevents bookmarks from saving.
After a reboot a saved bookmark is gone.
After disabling uBlock and restart FF the bookmark saving works fine.

FF 50.0.2
uBlock 1.10.0

**Comment by gorhill** [comment]
Did you use the logger to investigate whether a filter loaded by uBO is interfering?

**Comment by gorhill** [comment]
Make a better case that uBO is _really_ interfering. I can't reproduce, and there is no network request being emitted  as a result of creating bookmark. Try with a blank profile and only uBO with default settings. I will reopen if and only if you actually make the case there is an issue with uBO itself.
