### ISSUE TITLE
[Question] uBlock "vs" ABE (Noscript)

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#2239]
Not really an Issue, but I wanted to ask something about uBlock working with Noscript.

I need to use ABE on Noscript to enable some 3rd party script on some sites but not on the rest of the web; sadly Noscript does not provide an easy interface like ublock, so one wanting more fine control has to write rules in ABE.

In uBlock I can block those script in a more flexible way, I can for example block them on all the web but where I want themm active.

So the question is what is different between the 2 solutions; I mean, does it make sense to use only one of them? Are they redundant? Are they actually different?

**Comment by alexara** [comment]
@typhoon71 

You better close your thread yourself, before the owner does it:
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Questions belong to:
https://discourse.mozilla-community.org/t/support-ublock-origin/6746

**Comment by typhoon71** [comment]
mm, ok, so this does count as "discussion"?
I suppose I will post there then.

**Comment by typhoon71** [comment]
awesome, "Account temporarily on hold" on the first post.
