### ISSUE TITLE
Element picker mode in Firefox CSS failure on https://blog.google

### ISSUE THREAD

**Issue by jjohns71** [gorhill/uBlock#2240]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Issue seems to *only* occur on Firefox, I tested on Firefox 50.1.0 on two Windows computers as well as on Chrome with latest stable uBlock (1.10.0) and element picker seems to WORK as intended on Chrome. 

When using the element picker in Firefox on [https://blog.google](https://blog.google/topics/public-policy/sharing-national-security-letters-public/) the CSS/HTML of the element picker dialog appear to crash/not load and all you see is a white and black box with no functionality to select various div elements on the current page.

I tested on multiple blog.google links and appears to happen on all I tested on.

Additional links you can test on:
`https://blog.google/products/search/year-search-2016/)`
`https://blog.google/topics/education/bringing-virtual-pride-parade-students-bogota-colombia/`

The only thing strange about the site I can think of is that the TLD is '.google' which perhaps causes some crash of expectations in either Firefox or uBlock?

### One or more specific URLs where the issue occurs

`https://blog.google/topics/public-policy/sharing-national-security-letters-public/`

### Screenshot in which the issue can be seen

![bug02](https://cloud.githubusercontent.com/assets/6795795/21185870/658ec232-c1e0-11e6-8601-e02c92a0afce.png)

### Steps for anyone to reproduce the issue

1. Using Firefox 50.1.0 and uBlock Origin 1.10.1rc1
2. Go to https://blog.google/topics/public-policy/sharing-national-security-letters-public/
3. From uBlock panel, enter element picker mode,
4. Observe element picker css/html is broken and appears in top left of browser window and normal "red" overlay with picker is not visible.

### Your settings

Tested on 2 different systems and seems to be reproducible on both with the following settings:
- Operating System: Windows 7
- Browser/version: Firefox 50.1.0
- uBlock Origin version: 1.10.1rc1

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
This is caused by the site using a Content Security Policy preventing the use of inline styles.

Not sure how to fix this at this point.

**Comment by gorhill** [comment]
I can't reproduce with latest version of uBO.

**Comment by gorhill** [comment]
Issue can be reproduced on this site: `https://denuvo.com/`.

First reported at <https://www.reddit.com/r/firefox/comments/6ep779/ublock_origins_element_picker_looks_different_on/>.
