### ISSUE TITLE
RU AdList: Counters‎

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBlock#2241]
Hi Raymond,

For over a year, I strongly support your extension and adapt to uBlock RU-subscriptions. One of the subscriptions, RU AdList: Counters (https://easylist-downloads.adblockplus.org/cntblock.txt), very popular and users are asked to add it to the regular schedule as Bitblock: http://forum.ru-board.com/topic.cgi?forum=5&topic=47694&start=3160#15
Is it possible?

Kind regards,
dimisa

**Comment by gorhill** [comment]
What is the purpose of that list?

**Comment by dimisa-RUAdList** [comment]
Soft block statistics and counters in runet.

**Comment by SMed79** [comment]
> Soft block statistics and counters in runet.

Not covered by easyprivacy?

**Comment by dimisa-RUAdList** [comment]
Not everyone. Subscription EasyPrivacy inefficient working on russian sites. Besides, it is very large.

**Comment by Piter432** [comment]
@dimisa-RUAdList: Why not to have “RU AdList: Counters”, “RU BitBlock list” and “RU AdList: Counters” merged with “RU BitBlock list” (“RU BitBlock+AdList: Counters” or better name)?

**Comment by dimisa-RUAdList** [comment]
These subscriptions have different purposes: https://forums.lanik.us/viewtopic.php?f=102&t=22512
For users Counters unacceptable use BitBlock.

**Comment by Piter432** [comment]
@dimisa-RUAdList: Is there any English version of this topic? I'm asking, 'cause I don't understand Russian 🙁

**Comment by ierenstein** [comment]
@Piter432 https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fforums.lanik.us%2Fviewtopic.php%3Ff%3D102%26t%3D22512&edit-text=

**Comment by dimisa-RUAdList** [comment]
Up!

**Comment by gorhill** [comment]
As explained here: <https://github.com/gorhill/uBlock/issues/3014#issuecomment-329457339>.
