### ISSUE TITLE
Exceptionrules.txt does not work

### ISSUE THREAD

**Issue by marcus86423** [gorhill/uBlock#2243]
### The issue

I switched from Adblock Plus to uBlock Origin for it's lower use of my pc resources. So far I am happy with it, but **I cannot seem to be able to activate the exceptionrules.txt a.k.a the acceptable ads list**. 

At [reddit someone said](https://www.reddit.com/r/ublock/comments/33lieo/quick_question_can_i_subscribe_to_acceptable_ads/?st=iwomw2pn&sh=8f745b55) I just have to add this filter list URL:
https://easylist-downloads.adblockplus.org/exceptionrules.txt

I already tried to put the URL https://easylist-downloads.adblockplus.org/exceptionrules.txt into the predefined filters tab at the end of the page which then created the already checked/activated entry "Allow non-intrusive advertising", but unfortunately acceptable ads are still blocked (even after reloading the site of course).

I also tried to put the URL into the my filter tab where it clearly says I can put in Adblock Plus compatible filter lists.

After that I tried to put the URL into the whitelist to no avail. My last try was to import the URL in the whitelist tab, but then the textbox got filled with the exceptionrules.txt content and the textbox background turned red.

**Please fix this issue or tell me how I can make exceptionrules like the acceptable ads work with uBlock Origin.**

I know uBlock does not support acceptable ads, but your manifesto says the user decides what web content is acceptable or not and for me acceptable ads are what I want to let through, cause I think they can transform the web as a whole for the better. Since I haven't found a better acceptable ads entity yet, I want to use the acceptable ads list by Eyeo.

I also would wish for a non-profit web, but I think there needs to be some steps in between for corporates to change. Whitelisting the good advertisers and force advertising agencys or website owners to make more pleasant ads is in my opinion a good thing for all internet users. At least this way I can say to website-owners my adblocker is not really actived, cause it only blocks intrusive and annoying ads and ask them to change their advertisers or ask them to change the way their ads are presented.

Many thanks in advance and thank you for this awesome extension.

### One or more specific URLs where the issue occurs

For example the google shopping ad on the upper right does not show up on
https://www.google.de/search?q=samsung

#### My settings

- Browser/version: Chrome 55.0.2883.87 
- uBlock Origin version: 1.10.0

#### My filter lists

All except for: "uBlock filters – Experimental"‎, "EasyList without element hiding rules",  "Fanboy+Easylist-Merged Ultimate List"‎, "MVPS HOSTS". From the regional list only "DEU: EasyList Germany" is activated. 

#### My custom filters

https://easylist-downloads.adblockplus.org/exceptionrules.txt (checked/actived)

**Comment by okiehsch** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax
Not supported

document for exception filters (those prefixed with @@):

Not supported. The purpose of the document option when used with an exception filter is to disable uBO completely. The purpose of the document option in static exception filters is mostly for the sake of "acceptable ads" support, which uBO does not support.

The reason it is not supported is to be sure that users explicitly disable uBO themselves if they wish (through whitelisting), not having some external filter list decide for them.

**Comment by uBlock-user** [comment]
If you came for acceptable ads, then you should have stayed with ABP, their extension is only suited for that thing. Secondly, there could be filters which counter the exception filters, which will result in having the higher priority, so the exception filters won't be applied.

Just add the website to your whitelist and it won't block anything.

**Comment by gorhill** [comment]
As pointed out by @okiehsch, exception filters for `document` option are not supported. The purpose of such filters in to disable completely the blocker. Excerpt from [ABP's documentation](https://adblockplus.org/filters#whitelist):

> If you specify `$document` option you will get an exception for the entire page. For example, if your exception rule is `@@||example.com^$document` and you open some page from example.com — Adblock Plus will be entirely disabled on this page and nothing will be blocked.

If you want to entirely disable uBO on a given site, just press the bug blue button in the popup panel for site which you wish to support.

**Comment by gorhill** [comment]
Also, duplicate of:
- https://github.com/gorhill/uBlock/issues/395
- https://github.com/chrisaljoudi/uBlock/issues/66

**Comment by marcus86423** [comment]
@okiehsch: Thank you for the easy to understand explanation, I appreciate it.

> The reason it is not supported is to be sure that users explicitly disable uBO themselves if they wish (through whitelisting), not having some external filter list decide for them.

Well that is odd to me that on the uBlocks' manifesto it says I am the one to decide and then I am not allowed to put my trust into a exception list entitiy from my own country by adding their list at least manually. In my opinion it should be my decision whether I let others do the hassle to create an exception lists for me to use like it's my decision what blocking list I use.

@uBlock-user 
> If you came for acceptable ads, then you should have stayed with ABP

As I said, I came to uBlock for the _lower use of pc resources_, because I have not the most modern pc anymore (Intel E8400) and often have many tabs open in my Chrome or Firefox. I was figuring out the great possibilities to block more things manually with uBlock Origin, but then came to this big downturn of not even being able to put in my preferred exception list manually. 

> Secondly, there could be filters which counter the exception filters, which will result in having the higher priority, so the exception filters won't be applied.

The only filters I can think of would be the dynamic filters or are there other filters that would have higher priority? I would want to be able to override acceptable ads that don't fit my own criteria, of course.

Contrary to your believe I think only intrusive and flashing ads are a menace. I am totally fine with text-ads, ads that are static, non animated pictures or google shopping ads (actually that is more of a feature for me to get a first overview then an "ad"). I was already able to block "shit cookies" and "tracking tools" either by adding more blocking lists to Adblock Plus or by installing another extension, but I wanted to have everything in one fast open-sourced extension. 

In my opinion the acceptable ads initiative already changed the web for the better, cause when I deactivate my adblocker I see less and less annoying ads. More website owners get the clue that they have to change their site in compliance with their userbase in order to still get some money out of ads, because otherwise they get no money from ads at all.

Every adblocker with an acceptable ads exception list activated is a vote for a web that can be enjoyed without a hassle. I would rather have to vote for having an good old advertising pillar every now and then instead of this flashy animated advertising screens that pop up in the cities everywhere where I can't just go by (for example at the train station). Advertising pillars benefit to inform me about new concerts or movies or other local stuff, whereas animated screens cause eye-cancer, make me stressed and give me headache, the same can be applied to online advertising. 

You can have a different opinion on this, but like I said: for me the acceptable ads already forced advertisers to change their ads and I want them to be forced in this direction further. You can say it's a big fat lie, I say it's already become a reality and I want to be part of that change, but not by having to block or allow everything by myself and give up the comfort of adblockers that are lists curated by others.

By your logic of what the manifesto meant uBlock should then have no "fucking list" at all. I took the manifesto by the word and hoped to have finally found an adblocker that fits all my needs.

@gorhill 

I understand that you don't support the ad blocker to be disabled completely, I also understand that you don't support acceptable ads, but I don't understand why it is not possible to add an exception rules list, when your own manifesto clearly states it's up to the user to decide and on the my filter tab it says I can add Adblock Plus compatible filters.

From my understanding you only don't support the `$document` option, but in the whole exceptionrules.txt there are only 18 entries whith that exact option. **Why does the rest of the exception rules list not work too?**

Like I understand it, it should be no diference whether I whitelist everything by myself or whether I use my preferred exception list to do so (no matter if that list gets curated by others or by myself)

I do not want to disable uBO entirely, I just want to be able to use an exception rules list like I am able to use blocking list.

Not supporting acceptable ads is fine by me, everyone has their own opinion on them, but you already don't support them by not having them come as standard (or already activated) with your extension.

I don't think my issue is a duplicate of the other issues, cause I don't want you to have acceptable ads come standard with your extension. All I want is to be able to at least manually add my own preferred exception rules list. 

Otherwise I suggest you to change the wording of your manifesto, cause right now it don't seems like it's "The user decides what web content is acceptable or not in their browser" or "Users are best placed to know what is or is not acceptable to them. uBlock's sole purpose is to give users the means to enforce their **own** choices", when the user is not allowed or be able to use the exception rules lists he decides to choose.

So once again, **please tell me how I can use an exception rules list**. If it is not possible to use an exception rule list I ask you to rethink your decision to be up par with your own manifesto. I don't want to use the resource hungry Adblock Plus extension again.

Regards

**Comment by okiehsch** [comment]
> Well that is odd to me that on the uBlocks' manifesto it says I am the one to decide and then I am not allowed to put my trust into a exception list entitiy from my own country by adding their list at least 
manually.

Well you can add the list manually, but  exception filters for `document` option are not supported.
The rest works just fine.
For example `@@||o0.winfuture.de^$script,image,domain=winfuture.de`
is part of `https://easylist-downloads.adblockplus.org/exceptionrules.txt`
now go to `winfuture.de` and the difference with and without the list is pretty obvious.
![winf](https://cloud.githubusercontent.com/assets/16838044/21252284/f5997996-c355-11e6-8bf7-5bbe1f8442b7.PNG)

> there are only 18 entries whith that exact option.

I count 279 exception filters with a `document` option.
