### ISSUE TITLE
Plugin totally kills our site

### ISSUE THREAD

**Issue by VLDevsHu** [gorhill/uBlock#2244]
Dear Devs!

I'm a website owner and I'm writing here because I cannot found any other contact to You. Please forgive. Many of our users started complaining that our site is totally broken with this plugin. I'm trying to find out what the problem could be but meanwhile I'm asking You to help me because this is extremely urgent to us. Is it possible that one of our concurrent site has sent our urls to your database somehow? If we can modify our site's markup or script to be it OK please tell. Thanks in advance!

### One or more specific URLs where the issue occurs
Our site (adult content!) url is: https://www.videkilany.hu
A girl's datasheet page: https://www.videkilany.hu/59673-lana

### Screenshot in which the issue can be seen
I don't want to include many images because it's an adult site...
Index page uBlock enabled. All the girls card's are hidden.
![index-page-ublock-enabled](https://cloud.githubusercontent.com/assets/625056/21218940/f7bdbf28-c2b2-11e6-9fcf-8c9c366ff773.png)

### Steps for anyone to reproduce the issue
Open the site. All the cards of girls are hidden. Only texts and decoration images are visible. Also when a girls datasheet is being viewed only the pink background can be seen. Cards are hidden because of "cosmetic filtering".

### Your settings
I've just installed the plugin, all settings is on default, nothing were modified.

- Browser/version: Chrome 54.0.2840.99 m
- uBlock Origin version: 1.10.2

##### Your filter lists
All is default.

##### Your custom filters (if any)
All is default.

**Comment by mapx-** [comment]
report directly at hungarian list support site
https://github.com/szpeter80/hufilter/issues

"bad" filter
##[class*="hirdetes"]

you need an exception for your site
`videkilany.hu#@#[class*="hirdetes"]`

faster solution ==> rename that class

**Comment by uBlock-user** [comment]
Wrong place to post. This is a filter list issue. Nothing to do with uBlock itself.

**Comment by szegheo** [comment]
Oh, I see now... Thank You guys for the tip!

**Comment by VLDevsHu** [comment]
Oh, I see now... Thank You guys for the tip!
