### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by Fighter4Freedom** [gorhill/uBlock#2245]
After extension update to 1.10.2 in Cent Browser (ver. 2.2.9.39), an error has appeared (see screenshot).

![ubl_err](https://cloud.githubusercontent.com/assets/24589702/21227939/994c9054-c2e4-11e6-85bf-b8abae58c6f8.jpg)

**Comment by Hrxn** [comment]
I bet my money on a compatibility issue with 'Cent Browser' (You don't even explain what that is, gave a link or whatsoever).

Complain to them about their browser project with a nonexistent market-share if they break commonly used extensions.

**Comment by gorhill** [comment]
Report to this browser devs. Screenshot is uBO's manifest file, there is nothing wrong with it.
