### ISSUE TITLE
uBlock is blocking me from viewing twitch videos

### ISSUE THREAD

**Issue by nightmarejoker** [gorhill/uBlock#2246]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When I go to watch twitch streams uBlock does not let me see the video stuck on loading as seen in picture below
I did test this out by disabling

### One or more specific URLs where the issue occurs

https://www.twitch.tv

### Screenshot in which the issue can be seen
Before disabling
http://i.imgur.com/AuFNqSj.png
After disabling 
http://i.imgur.com/c8lxuVQ.jpg

### Steps for anyone to reproduce the issue

1. Have uBlock on
2. Go to twitch.tv
3. Click on stream of your choice (ex. https://www.twitch.tv/draskyl) 
4. It should be what i showed earlier
5. Disable uBlock and reload website, and video from their on will work as seen in my picture for after disabling

### Your settings

http://i.imgur.com/llv7IyI.png
http://i.imgur.com/a43AFQI.png

- Browser/version: Latest version of google chrome
- uBlock Origin version: Latest version

##### Your filter lists

http://i.imgur.com/a43AFQI.png
and
http://i.imgur.com/p0vyjv0.png

##### Your custom filters (if any)
Do not have

**Comment by veekdot** [comment]
I can confirm this issue with vivaldi, chrome & firefox.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
