### ISSUE TITLE
Non-intrusive "uBlock Origin has prevented the following page from loading" notification?

### ISSUE THREAD

**Issue by SMUsamaShah** [gorhill/uBlock#2247]
Is it possible somehow to not open a new tab every time for "uBlock Origin has prevented the following page from loading"? 

I am using [this site](extratorrent.cc). Unblocking scripts from itself adds an onclick function (inside eval(window.atob(...)) block) which opens `http://130.211.230.53/*`. I added it in filters but now after every page reload, whenever I click on anything  "uBlock Origin has prevented the following page from loading" tab opens. Only after closing and moving back to site I can really click a link or anything else. This happens on first click after every reload. This is just as annoying as an ad opening in the new tab. 

So is it possible to not open New Tab and alternatively show an icon in address bar (like google popup blocker)? It will be perhaps more user-friendly (and not annoying in my case).
 
I am using uBlock Origin 1.10.2 in Chrome.  
`http://130.211.230.53/` is the only custom filter and these are my settings ![image](https://cloud.githubusercontent.com/assets/385283/21287853/9aa23c3e-c496-11e6-9819-1d4c7cf27ca8.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
You get a new tab with that notice, because uBO wasn't able to keep the tab from being opened, but it was able to keep the URL inside the tab from being loaded.

There are cases where you may try to go to a URL through a link that doesn't open a new tab, and in that case, the not-loaded message is in the same tab.

**Comment by gorhill** [comment]
Bottom line: **only** a `popup` filter can prevent a tab from being opened (or allow a tab to be auto-closed). Strict-blocking is **unrelated** to popup filtering.
