### ISSUE TITLE
Show a better response when an URL is blocked with "behind-the-scenes" whitelist off

### ISSUE THREAD

**Issue by toshiya44** [gorhill/uBlock#2248]
### Describe the issue
Show a better response when an URL is blocked by uBO with "behind-the-scenes" whitelist off or deleted 
Currently it says "an unknown error occurred". 

### One or more specific URLs where the issue occurs
For example purposes,  https://github.com/gorhill/uBlock/releases 

### Screenshot in which the issue can be seen
![error](https://cloud.githubusercontent.com/assets/20046789/21289903/c7266818-c476-11e6-9add-042c705c607f.PNG)

### Steps for anyone to reproduce the issue
1. Remove "behind-the-scenes" from whitelist tab.
2. Create the filter `||github.com/gorhill/uBlock/releases/download/*$important`
3. Go to https://github.com/gorhill/uBlock/releases
4. Right click on any download link and select "Save link as"

### Your settings

- Browser/version: Firefox Nightly 53 (tested with Firefox 45 and 50 as well)
- uBlock Origin version: 1.10.2

##### Your filter lists

"Default filter lists"

##### Your custom filters (for example purposes)
||github.com/gorhill/uBlock/releases/download/*$important

Notes: I know that removing the default whitelists is a bad idea if I'm not careful, but it would be nice if uBO shows what error has occurred.

**Comment by gorhill** [comment]
That warning is not from uBO, it's from your browser -- out of control of uBO. Anyways, there is no context attached to behind-the-scene network requests seen by uBO, it wouldn't know whatever is blocked was a result of such high-level UI operation such as "Save as..." or whatever else this could be.
