### ISSUE TITLE
Question about filters

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#2249]
Hi, 
what is the difference between?
```
/*$type,third-party,domain=example.com
*/$type,third-party,domain=example.com
*/*$type,third-party,domain=example.com
*://$type,third-party,domain=example.com
://*$type,third-party,domain=example.com
*://*$type,third-party,domain=example.com
```
and

`$type,third-party,domain=example.com`

or

```
|http://$type,third-party,domain=example.com
|https://$type,third-party,domain=example.com
```

Thank you.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by SMed79** [comment]
Sorry to not provide the necessary information.

**Comment by gorhill** [comment]
Did you get different results between the first group and the second group? You should get the same result, i.e. a filter which will block all 3rd-party network requests when visiting a page from `example.com`.

**Comment by SMed79** [comment]
It is not a matter of preference, it's just to be sure when adding filters, these will work with uBo as ABP.
& Yes i get different results. For example no one of these first group filters block the the third-party image from _ssl.gstatic.com_ on [https://www.google.com/search?q=firefox](https://www.google.com/search?q=firefox) (correctly blocked by Adblock plus).


![http://i.imgur.com/if4DHGB.png](http://i.imgur.com/if4DHGB.png)

![http://i.imgur.com/NNRiZgh.png](http://i.imgur.com/NNRiZgh.png)

**Comment by gorhill** [comment]
> For example no one of the first group filters block the the third-party image from ssl.gstatic.com on https://www.google.com/search?q=firefox (correctly blocked by Adblock Plus).

Yes, I confirm there is an issue.
