### ISSUE TITLE
Image blocked. What is the reason?

### ISSUE THREAD

**Issue by Pirenko** [gorhill/uBlock#225]
Hi,
Why is this image blocked?
http://www.pirenko.com/fount/wp-content/uploads/sites/6/2014/12/adv-1.jpg
And why isn't this one too?
http://www.pirenko.com/fount/wp-content/uploads/sites/6/2014/12/adv-3.jpg

I would like to know the reason so that I can fix this for the website visitors.
Thanks!

**Comment by gorhill** [comment]
Filter lists are 3rd-party to this project, report your issue to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by Pirenko** [comment]
I wasn't aware of that. Thank you for the speedy reply.
