### ISSUE TITLE
Ability to remove DOM element instead of hiding? 

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#2252]
I know that it is canonical way to hide blocked elements. But sometimes it might be useful to actually remove DOM element. At least I don't have any other idea for the following testcase. 

1. Go to http://www.wykop.pl/
666. Switch view mode to "grid". (button on right hand side - marked with red circle on screenshot)
1337. You will see that ads are properly hidden, but this leave blank items in grid. When I manually remove hidden element, grid is properly shown - without blank spaces.

To reproduce those filters are needed. 
```
wykop.pl##li.link:has(a[href*='wykop.pl/reklama'])
wykop.pl##li.link:has(a[href*='wykop.pl/paylink'])
wykop.pl##li.link:has(a[href*='wykop.pl/market'])
wykop.pl##li.link:has(.adsbygoogle)
```

Any ideas how we can work this out? I know leftovers are not that bad, but still would be nice if we could remove them :)

![wykop_leftovers](https://cloud.githubusercontent.com/assets/1126053/21322585/1c8088e4-c61a-11e6-90bb-b4866e60cc9c.png)

**Comment by kasper93** [comment]
Also quite similar issue is with `ul#dyingLinksBox` thing. It is a list of some links. First one sometimes is advert. But you have arrow buttons to go through the list. 

The advert is hidden with the same filters I posted in first post. I can in fact show the non-ad element with `wykop.pl##.dying-links.link:nth-of-type(2):style(display:list-item;!important)` but their JS go through all children of `ul#dyingLinksBox` and set `display: none;` or `display: list-item` so if we go back to the ad we lost the arrow buttons. Best way would be to remove the element. Not sure it is something we can expect uBlock to do. I always used user.js but since uBlock is so powerful it kind of don't make sense anymore except few minor issues.

![ur](https://cloud.githubusercontent.com/assets/1126053/21324753/6040c50e-c623-11e6-822c-67303a9814bc.png)

**Comment by Hrxn** [comment]
What did you mean by manually removing the hidden element? Do you use some userscript / userscript extension? Or manually from the console, etc. ?

**Comment by lewisje** [comment]
He has explained why he won't do it already: https://github.com/gorhill/uBlock/issues/2211#issuecomment-264648203

**Comment by gorhill** [comment]
> uBlock doesn't inject the style

Because the `:style` operator currently works only with plain CSS selectors, not procedural ones.

**Comment by gwarser** [comment]
We have first "exceptional case" here.

**Comment by kasper93** [comment]
> What did you mean by manually removing the hidden element? Do you use some userscript / userscript extension? Or manually from the console, etc. ?

I think it doesn't really matter how I did that. Anyway I used to use my script for a long time. Back in the day most things was not possible to hide with adblock like addons. https://github.com/kasper93/userscripts/blob/master/UkryjWykopPoleca.user.js Recently I decided to port it to uBlock filters. And only three issues are remaining.

1. Leftover space from hidden elements.
286. `dyingLinksBox` thingy. 
8651. `$("body").removeClass("screening");` They have fullpage ads sometimes and ad itself is hidden with `wykop.pl##a[href*="wykop.pl/tracker"]` but there are some css being applied to body for example whole body width is lower. 

While I agree 2 and 3 might be out of the scope for uBlock. I think 1 is something we can discuss further, what do you think?

Anyway don't consider this issue to be request for a feature, I simply want to signalize problems I encountered. Maybe we find some solutions :)

**Comment by lewisje** [comment]
If the "leftover space" is caused from the page deliberately making some part of it less than full-width or full-height ("pulling in", as opposed to having other content "push in"), then it's outside the scope of uBlock Origin.

**Comment by JoseBarakat** [comment]
Hi. I'm new here (at UBO) and this issue got my attention.
Haven't read the entire code yet, so I don't know exactly what the consequences (structure and styling of elements) of removing a certain DOM element could be, but this can be easily done with vanilla JS or jQuery's DOM manipulation method `.remove()` once this element is identified.

**Comment by lewisje** [comment]
I already linked to the comment where @gorhill explains why he won't do it, but thanks for explaining DOM Manipulation 101 to us.

**Comment by gorhill** [comment]
@lewisje About your comment at <https://adblockplus.org/forum/viewtopic.php?f=10&t=52321>:

> uBlock Origin has implemented this with different syntax

uBO does override inline styles with `display: none !important;` by default, there is no need for users to worry about this.

For example, uBO works fine with <http://raymondhill.net/ublock/adbox.html> -- where one element to hide uses `style="display: block !important"`.

**Comment by chylex** [comment]
@gorhill You said you wanted real world cases for removing elements - if you use uBlock on a video element, it just hides it while it keeps autoplaying in the background when you reload the page. I'd appreciate a way to force these elements out of the DOM instead of blocking an element thinking it was gone, and several days later getting jumpscared by invisible videos..

**Comment by gorhill** [comment]
"Real world cases" means _actual URLs_ where I can see for myself what can be done .

**Comment by chylex** [comment]
Here's an example rule that kept autoplaying the video trailer on the site:

```
! 18. 12. 2016 15:24:08 http://www.metacritic.com/game/pc/overwatch
www.metacritic.com##.video_and_autoplay
```

**Comment by gorhill** [comment]
Blocking large media elements would work for that case.

**Comment by chylex** [comment]
Blocking large media elements does nothing here http://www.digitaltrends.com/mobile/phone-unlocking-guide-for-all-carriers/

**Comment by gorhill** [comment]
Works for me. What your threshold for the size? It's 250 KB here.

**Comment by chylex** [comment]
50 kB, only turning it on for individual websites. Both sites still load and autoplay the videos - http://i.imgur.com/Mm0UCxw.png. Using Firefox Developer Edition 54.0a2, 64bit.

It also doesn't solve a case where you'd only want some videos to play, for example blocking twitch's mini player but not blocking the main player (you can do this in twitch settings, but just as an example).

**Comment by gorhill** [comment]
Ok the video is delivered differently on Firefox -- the page is using xhr requests.

**Comment by gorhill** [comment]
Here is another case: #2609. The page keep changing the `style` attributes non-stop to evade cosmetic filtering's `display: none !important;`.

**Comment by kasper93** [comment]
Another case where hiding leave blank space. When node is removed layout is properly calculated.

https://userstyles.org/styles/browse

**Comment by chylex** [comment]
Any update on this? Another website where blocking media doesn't work - http://www.zdnet.com/article/max-memory-limits-for-64-bit-windows-7/

**Comment by gorhill** [comment]
> blocking media doesn't work

    ||ipad-streaming.techrepublic.com/media$domain=zdnet.com

**Comment by gorhill** [comment]
> [example](http://wiki.teamliquid.net/overwatch/Overwatch_Contenders/Season_1/Europe/Playoffs)

I don't see any ads on that page.

**Comment by chylex** [comment]
![obrazek](https://user-images.githubusercontent.com/3685160/31296470-b5c43822-aae2-11e7-9080-33a902ebe0a6.png)

**Comment by okiehsch** [comment]
Already fixed by the filter
`teamliquid.net##script:inject(abort-on-property-write.js, adonisHash)`
in `uBO-filters`

**Comment by vparitskiy** [comment]
http://sport.ua/

Nice example why removing elements instead oh hiding would be helpful.

They use js to detect hidden state and override it which cause constantly dom changes. Or something like that.

http://gifly.com//media_gifly/t/l/J/h/b/tlJh.gif

**Comment by gorhill** [comment]
Try:

    sport.ua##script:inject(abort-current-inline-script.js, parseInt, 676574456c656d656e747342795461674e616d65)

**Comment by slackero** [comment]
It would make sense these days to remove specific filtered elements from DOM instead of just hiding. [Here](http://www.spiegel.de/politik/ausland/metoo-debatte-um-sexuelle-gewalt-erreicht-die-arabische-welt-a-1179978.html) is such an example.

<img width="1131" alt="autoplay" src="https://user-images.githubusercontent.com/15139/33242533-c27c4052-d2d6-11e7-8aec-f7dbe72315eb.png">


My filter: `www.spiegel.de##.autostartvideo` is hiding the element but video still is autoplaying.

I cannot find any working solution for this specific problem. Cosmetic filters are not enough.

**Comment by gorhill** [comment]
> My filter: `www.spiegel.de##.autostartvideo` is hiding the element but video still is autoplaying.

That is a good pro-argument.

**Comment by ThePickNick** [comment]
I have found couple more examples where Video blocking via UBlock Orgin picker only hide the video the video is set on autoplay, and you can still hear the sound. major News sites in particularity incorporate this feature. Only  way to get rid of video is to delete video element from the DOM

http://www.cnn.com/2018/01/12/us/southern-california-mudslides/index.html

mine filter 
`www.cnn.com###large-media` does block the video but sound still plays same issue with these sites 

http://fortune.com/video/2018/01/11/lyft-made-a-beer-that-comes-with-discounted-rides/

filter used 
`fortune.com##.rendered.sticky-video.auto-play.lead-media.autoplay.no-custom-bc-overlay.full-width-media.video.component `

there  needs to be a function to delete elements from DOM instead of just adding `style="display: none !important;"`

**Comment by Hrxn** [comment]
Works with HTML filtering.

**Comment by gorhill** [comment]
Another case: <https://github.com/uBlockOrigin/uAssets/issues/7056>.
