### ISSUE TITLE
Bookmarks bar flickers randomly after installing uBlock on Ubuntu

### ISSUE THREAD

**Issue by dandv** [gorhill/uBlock#2253]
### Describe the issue

The bookmarks bar flashes periodically (several times per minute) but irregularly after installing uBock in a new Chrome profile on Ubuntu 16.04.1 running on a laptop without a graphics card.

This is a Heisenbug, but I've managed to reproduce it reliably on Chrome 55 stable and 57 dev. I've been seeing the issue for the past 3-4 weeks. I can share a minimal Chrome profile privately if useful to reproduce.

### One or more specific URLs where the issue occurs

http://phuket-snorkeling.com/

### Screencasts in which the issue can be seen

https://www.youtube.com/watch?v=BgodzfbUreI
https://www.youtube.com/watch?v=O9DWT3CqbH8

### Steps for anyone to reproduce the issue

1. Launch Chrome with a new/blank user profile, e.g. by renaming the "Default" directory on Ubuntu, ~/.config/google-chrome/Default
2. Make the bookmarks bar visible (Ctrl+Shift+B) and create a bookmark
3. Install the extension from https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en
4. Browse some sites, until you see bookmarks bar flicker (took less than a minute). Some pages that produced particular flicker for me were http://phuket-snorkeling.com/ and [healthline](http://www.healthline.com/health/how-to-get-water-out-of-your-ear). Most sites produce the flicker, though with different frequencies.

### Your settings

- uBlock Origin version: 1.10.4
- no other settings were changed after installing uBlock from the Chrome store
- Dell laptop with integrated Intel HD graphics card and Ubuntu 16.04.1 kept up to date. I know this veers into Chrome territory, so I've filed https://crbug.com/671540 as well. FWIW, I work relatively close to the Chrome team at Google and I can try helping prioritize the issue.

**Comment by gorhill** [comment]
uBO's icon button and popup panel frame are under control of the browser. Report to Chromium devs -- there is really nothing I can do, all is done through chrome API.
