### ISSUE TITLE
New Pop-Unders from site user clicks

### ISSUE THREAD

**Issue by DDube47** [gorhill/uBlock#2254]
### Describe the issue
Pop-unders on this site used to be blocked but now produce pop-unders regularly.

### One or more specific URLs where the issue occurs
http://peeplink.in/5c85d748f024
Pretty much any link generated from this site.

### Screenshot in which the issue can be seen
![githubublockreport](https://cloud.githubusercontent.com/assets/24683179/21362364/e7c71824-c69c-11e6-8403-805e8a79ea1f.png)

### Steps for anyone to reproduce the issue
1) Open Link.
2) Click Anywhere.
3) Pop-Under is sent to user even if popup blocking is enabled.

### Your settings

Browsers Tested: Firefox 51.0b9 (32-bit) & Chrome 55.0.2883.87 m
uBlock Origin version: 1.10.4

##### Your filter lists
![githubublockreportlist](https://cloud.githubusercontent.com/assets/24683179/21362527/9753d912-c69d-11e6-89e3-0ff3f2312a55.png)

##### Your custom filters (if any)
None

-
Please let me know if any more info is needed.

**Comment by mapx-** [comment]
add
`|http://$script,third-party,domain=peeplink.in`

**Comment by DDube47** [comment]
Confirmed, that seems to fix the issue. Thanks!

**Comment by uBlock-user** [comment]
add
`||$third-party,domain=peeplink.in`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
