### ISSUE TITLE
Problems with a countdown timer (Gecko-browsers + uBO)

### ISSUE THREAD

**Issue by TheFinalCut83** [gorhill/uBlock#2256]
### Describe the issue

With uBO after you enter the captcha doesn't want to work countdown to transition to rusfolder link; with ABP (with RUAdList+Easylist) and even Adguard addon with his Russian filter and RUAdList everything is perfectly work.
Occasionally at the bottom [appears the frame with youtube video](http://i.imgur.com/0qLrgou.jpg), in that case timer works fine. Much more often in the bottom frame [appears similar to the following](http://i.imgur.com/3BVrQAx.jpg) (blocked sites change almost every time). It's interesting that in uBO filter is the same, [but without the `script` directive](http://i.imgur.com/MKH4rFE.jpg). In ABP timer [appears](http://i.imgur.com/xFyv2nQ.jpg), in uBO - [doesn't](http://i.imgur.com/RnHtnt3.jpg). Bug doesn't occur in Chrome, only in Gecko-browsers. Another interesting detail: I tried with Anonymox addon, with the British and Dutch IP timer also doesn't work, but with an US once was the behaviour without RUAdList - ads appear at the bottom and the counter starts to work.

### One or more specific URLs where the issue occurs

catcut.net/OeX4 or catcut.net/jfX4 (taken from http://www.mediaboom.org/462513-dark-lunacy-the-rain-after-the-snow-2016.html)

### Screenshot in which the issue can be seen

https://i.imgur.com/RnHtnt3.jpg

### Steps for anyone to reproduce the issue

1. Go to catcut.net/OeX4 or catcut.net/jfX4 with uBO and RUAdList+Easylist enabled
1. Enter the captcha
1. Notice that the timer doesn't appear

### Your settings

Default uBO settings.

- Browser/version: Firefox 50.1.0/51.0b9, Cyberfox 50.1.0
- uBlock Origin version: 1.10.4, 1.10.5b0

##### Your filter lists

RUAdList+Easylist (https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt)

**Comment by gorhill** [comment]
The site listen to `onload` event for the frame containing the ad. The frame is blocked by the filter `|http://$third-party,subdocument,domain=catcut.net|lider-as.ru` (uBO compiles filter lists, so the displayed filter in the logger might be rendered differently than the raw version in the list), and as a consequence the `load` event is never fired for the blocked frame.

Curiously, I observe that the `load` event is fired for the blocked frame when using ABP. I need to investigate further.

**Comment by gorhill** [comment]
Possibly related: <https://bugzilla.mozilla.org/show_bug.cgi?id=444165>.

**Comment by gorhill** [comment]
I confirm issue is related to above bugzilla issue. The solution is to fired a 'load' event manually for iframes which are not loading due to uBO filtering them.
