### ISSUE TITLE
how to add a hotkey for element picker

### ISSUE THREAD

**Issue by lyfd123** [gorhill/uBlock#2257]
I am using firefox and used to set a hotkey [F4] for the 'element hiding helper for abp' in a .js which is named keychanger so that I can easily blcok ads just by press F4.
`keys['F4'] = "window._ehhWrapper.toggleSelection();";//element hiding helper`

So I wonder whether there would be a chance to add a hotkey for element picker just like above. Thank you for your excellent work.

**Comment by Betsy25** [comment]
Sorry for not being knowledged enough, but these are the elements of the element hiding helper button in the DOMi, perhaps they might help you, perhaps not.

> id="gotoPick"
class="fa tool enabled"
data-i18n-tip="popupTipPicker"
data-tip="Enter element picker mode"

**Comment by lyfd123** [comment]
thanks for sharing 👍

**Comment by gorhill** [comment]
This was fixed in [1.13.0](https://github.com/gorhill/uBlock/releases/tag/1.13.0).
