### ISSUE TITLE
popups not being blocked by domains already located in filter list

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#2258]
i didn't notice this before. but i got a ad redirect on a website today and a domain that was used was blocked by Dan Pollock’s hosts fille filter list. only the document version of it though not the popup. isn't it supposed to block popup version of it also or only if specified
![untitled](https://cloud.githubusercontent.com/assets/15130139/21446639/689f8dda-c88e-11e6-9915-114e4e8e3792.png)
?

**Comment by gorhill** [comment]
For popups to be blocked there needs to be the `popup` filter option.
