### ISSUE TITLE
dynamic filter to un-hide specific 3rd-party ads

### ISSUE THREAD

**Issue by leoneckert** [gorhill/uBlock#2259]
Hello! And thanks for this great project!

I am using dynamic filters to disable all cosmetic filtering on specific domains. Is it possible to do the same for specific third party requests? If an ad pointing to XYZ was hidden before by specific rules, I wonder if a dynamic filter can overwrite those rules, making that XYZ ad appears instead. Is that possible? 

Thanks!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
