### ISSUE TITLE
Blocking meta refresh redirects

### ISSUE THREAD

**Issue by seanrand** [gorhill/uBlock#226]
Some sites use [meta refresh](https://en.wikipedia.org/wiki/Meta_refresh) to redirect the tab to ads after several seconds.
As far as I know, there's currently no ad blocker that can handle this type of obnoxious ad/redirect and I haven't seen it being discussed in the issues of uBlock/uBlock₀ (beyond the mention by flyingzebras in [chrisaljoudi:#1397](https://github.com/chrisaljoudi/uBlock/issues/1397#issuecomment-104411425)).
- Issue on the AdBlock Plus tracker: https://issues.adblockplus.org/ticket/2095
- Thread in the AdGuard forums (russian): http://forum.adguard.com/showthread.php?2309-http-www-pics-money-ru-3-85677.  
  Although AdGuard's [HTML filtration rules](http://adguard.com/en/filterrules.html#htmlContentFilter) looked like a promising solution to me, the user over there seems to be saying that the filtration rule `pics-money.ru$$meta[http-equiv="refresh"]` doesn't stop the redirect.

Here's an example, it should redirect after 12 seconds: http://www.pics-money.ru/4/14613/

Edit: Although it addresses a different use-case (pages that use meta refresh to reload themselves), there is an extension on the Chrome web store that might be of interest: [Stop AutoRefresh](https://chrome.google.com/webstore/detail/stop-autorefresh/lcldcllmbokpbniijpnkpgoboadbfphb)

**Comment by CrisBRM** [comment]
Futpib introduced this feature in the latest dev version of Policeman.
https://github.com/futpib/policeman/commit/522dd1c26ea46235a491ca58c3c2a5bee203d744 + older commits address this issue.

**Comment by gorhill** [comment]
I've had my own ideas about how to implement such a thing, I won't use anybody else's ideas for this: I have to come up with something which works for both Firefox and Chromium, and I plan on an implementation which works for both server- and client-side redirects.

**Comment by gorhill** [comment]
Isn't tkane care by the `popunder` filter option?

**Comment by seanrand** [comment]
Yes, as far as I can tell it's taken care of. Well, at least I can't reproduce it anymore as almost all of the examples linked are either down or at least outdated.
