### ISSUE TITLE
New Adblocker forked from uBlock Origin, Possible GPL Violation?

### ISSUE THREAD

**Issue by bgiesing** [gorhill/uBlock#2261]
I was searching Google for uBlock and came across a Press Release for a new adblocker named "ADZBuzz uBlock" that says they use uBlock Origin code "with a minor twist for ADZbuzz to be to utilize this tool to provide a win-win situation for content users and publishers alike." aka they pay publishers when you block ads similar to Brave or Google Contributor.

Since they are using open source code, they are free to make a variant with modifications but with the GPL license they are required to release the code if they make any modifications, right? Well I can't find any code anywhere. 

https://ublock.adzbuzz.com/
https://chrome.google.com/webstore/detail/adzbuzz-ublock/kllohiclobgoaffphlofnjdlabflpgha

**Comment by gorhill** [comment]
It's just a hobby, I won't get into any complicated matters. At least users are informed the extension is based on uBlock Origin, so they are free to investigate whether they want uBO or the derivative work.

**Comment by lewisje** [comment]
In case you ever do want to pursue this, the form is right here: https://support.google.com/legal/troubleshooter/1114905?rd=2#ts=1115658%2C1115673

I did my part, by installing the extension and giving it a one-star review, to help drown out all of the clearly fake five-star reviews that the extension was seeded with.
