### ISSUE TITLE
uBlock0 Back up to file doesn't open Save as in Vivaldi

### ISSUE THREAD

**Issue by MicroBeast** [gorhill/uBlock#2263]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
"Back up to file" in Dashboard doesn't open Save as. Instead, it directly save (with default filename) to whatever default Download folder I set in Vivaldi settings.

Also tested with:
No other extensions running.
Clean Vivaldi Profile. With uBlock0 only.

Already report this in Vivaldi forum. But I've been told to report here instead.

### One or more specific URLs where the issue occurs

none

### Screenshot in which the issue can be seen

none

### Steps for anyone to reproduce the issue

Just click "Back up to file" button.

### Your settings

- Browser/version: < 1.6.689.46 (Stable channel) (64-bit)
- uBlock Origin version: 1.10.4
- System: Debian sid amd64
"<" It's already like that from few versions below.
I didn't really follow uBlock0 versioning in Chromium like browsers. I can't tell since when, but it does still happen in uBlock0 1.10.4.

##### Your filter lists

Default. Minus "Peter Lowe’s Ad and tracking server list"

##### Your custom filters (if any)

none

My filters: Default
My rules: Default
Whitelist: Default

Thanks.

**Comment by Hrxn** [comment]
Not sure if this really an issue..
Guess it follows the settings for download destination, what happens if you turn download options to "ask before each.." in Vivaldi?

**Comment by gorhill** [comment]
By design.

**Comment by uBlock-user** [comment]
If Vivaldi themselves won't help you fix this, better dump it. Get Chromium - https://chromium.woolyss.com/
