### ISSUE TITLE
Want to create a regex to whitelist all google but no luck

### ISSUE THREAD

**Issue by hserhk** [gorhill/uBlock#2264]
I want to allow all traffic from google pages (e.g. google.com, drive.google.com, www.google.com.hk, www.google.co.jp), by using following regex: 

^https?:\/\/(()|(.+\.))google\.(co|com)(()|(\.[a-zA-Z]{2}))\/

no matter I place it into Static or Whitelist, still not working, can anyone help? thanks

**Comment by lewisje** [comment]
Unfortunately, there's no "all-TLD" or "all-suffix" option for dynamic filters, there are no wildcards or regexes allowed in the Whitelist section, and uBO doesn't support the `$document` option for exception filters (static filters section, the one place that *does* allow regexes).

**Comment by gorhill** [comment]
"Whitelisting" in uBO means to disable uBO on a specific page/site.etc. If this is what you want, currently there is a known issue in the _Whitelist_ pane which wrongfully mark an entry as invalid despite being valid, it was reported as a comment in a commit. I need to fix this.

Note: Your regex-based filter is missing the first `/`.

**Comment by hserhk** [comment]
Thanks all!
Should I wait for the nexr release?

Ps: just found that this regex can be insert into whitelist if I remove all brackets.
