### ISSUE TITLE
uBlock fails to block YouTube ads when using a VPN

### ISSUE THREAD

**Issue by mikeanthonywild** [gorhill/uBlock#2265]
### Describe the issue

Browsing YouTube while connected to my VPN (Digital Ocean VPS in Germany) results in YouTube ads slipping through. When the VPN is disabled, ads are blocked as normal (my ISP is based in the UK).

### One or more specific URLs where the issue occurs

* https://www.youtube.com/watch?v=c4nRPckotCw

### Screenshot in which the issue can be seen

![VPN enabled](http://i.imgur.com/Y5uuWhx.png)

![VPN disabled](http://i.imgur.com/1IfeuC3.png)

### Steps for anyone to reproduce the issue

1. Navigate to the aforementioned URL

2. Load the page while connected to a Frankfurt-based Digital Ocean VPN to access YouTube DE with ad.

3. Disconnect from the VPN and refresh the page to see the same video without the ad.

4. Refreshing the page while *still* connected to the VPN does not make the ad disappear.

### Your settings

- Browser/version: Safari 10.0.1 on OSX 10.10.5
- uBlock Origin version: 1.10.0 (all settings on defaults)

##### Your filter lists

Default filter lists + Fanboy's Social Blocking List

**Comment by gorhill** [comment]
Report to proper project please: <https://github.com/el1t/uBlock-Safari#ublock-originfor-safari>.
