### ISSUE TITLE
Make adult site blocking optional.

### ISSUE THREAD

**Issue by WildRat** [gorhill/uBlock#2266]
"Easy list" (assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt) have section "*** easylist:easylist_adult/adult_specific_block.txt ***" witch makes loading sites such as pornhub.com fail. Please, make this behavior optional.

**Comment by gorhill** [comment]
See "EasyList without rules for adult sites" at <https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html>.

**Comment by WildRat** [comment]
On my opinion this must be the default list enabled, and "adult sites blocking" an option.
