### ISSUE TITLE
Enable users to create their own custom scriptlets

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#2267]
### Describe the issue

Enable users to create their custom java scriptlets by offering user-interface similar to `My filters` in uBO to build their own scriptlets namely `My resources`, that way they can build their scriptlets in no time without having to rely solely on resources.txt as it is not customisable to a user's needs.

### Use-case

I came across a website where it was using a variable `canRunAds` which is not present in `/resources.txt`, so I cannot use the scriptlets available there and I have no way of inserting a new scriptlet in that file and retaining it as it would be erased with the extension update AND I have no way of creating a custom scriptlet by myself since there's no interface where I can create it. This is only one example as you can see numerous websites modify their own variables and use it, so a custom interface would be of great help where users can create their scriptlets in accordance to their needs without having to depend on Easylist or you or anyone else.

**Comment by gorhill** [comment]
Greasemonkey or Tampermonkey.

**Comment by rjkpa** [comment]
Yes, I know about those extensions already, however I didn't want to install another extension for this functionality, hence my suggestion.

**Comment by gorhill** [comment]
There is a new [advanced setting](https://github.com/gorhill/uBlock/wiki/Advanced-settings), `userResourcesLocation`.

**Comment by TPS** [comment]
Any idea if this could be used for, e.g., [AdsBypasser's](https://adsbypasser.github.io/releases/adsbypasser.user.js) or [AAK's](https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js) JS to be a single integrated solution for adblock?

**Comment by uBlock-user** [comment]
Yes, that's what I'm wondering too. Can we load userscripts ?

**Comment by gorhill** [comment]
It does no more than what it says it does, there is no reason to think otherwise. In case these questions are disguised feature requests, the answer is no, I do not intend to make it more than it is now.

**Comment by rjkpa** [comment]
Not like the one I was expecting, but still thanks for considering it after all.

**Comment by seanrand** [comment]
@gorhill, the (hidden) advanced settings don't seem to get applied to the incognito instance of uBlock when opening an incognito window in Chromium. Is this intended behaviour?

**Comment by gorhill** [comment]
@seanrand Not by design, an unforeseen side effect of the current implementation. This needs its own issue.
