### ISSUE TITLE
Suggested/Sponsored posts in facebook newsfeed

### ISSUE THREAD

**Issue by ugros** [gorhill/uBlock#2269]
Hello,

Recently I started seeing ad posts in facebook newsfeed. 
They are categorized as "sponsored" or "suggested posts".
Every 6th or 7th post is ad. Aswell anytime I fresh open facebook, second post is AD.

![image](https://cloud.githubusercontent.com/assets/20205489/21482137/6926f6c8-cb70-11e6-9e7f-6be1bdb64553.png)

Is there a way to distinguish between real and ad post and possibly hide those ad posts?
Would make facebook a way more enjoyable place!

(using chrome extension)

Thanks!
PS. I really appreciate the good work! Have been using this for more than a year without any problems!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
