### ISSUE TITLE
WISHLIST - uBlock for Qupzilla

### ISSUE THREAD

**Issue by gericom-hummer** [gorhill/uBlock#2270]
Hi there and Merry Christmas.
Can you provide support for Qupzilla - lightweight qt browser? 
The issue is started here https://github.com/QupZilla/qupzilla/issues/2149#issuecomment-269197603
Thanks

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
As with Microsoft Edge or Safari, this will have to be undertaken by someone else as a fork of this project.
