### ISSUE TITLE
popsci.com.tr web page breakage issue

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#2271]
Hi,
I am using Ublock Origin v1.10.4 with default filters on Chrome v55.I tried to open this page on my browser but I could not diplay it.Although there is no any static,dynamic,cosmetic filter or any other even though Ublock Origin disabled this site can not be displayed on Chrome.I checked to the logger but there is no blocked domains.On the other hand I tried to open this site on Edge browser and it displays perfectly.I attached the screenshots of the site and the logger below.It is very interesting problem.

<http://2.1m.yt/LG9i0F.jpg>

<http://2.1m.yt/_A7aE69.jpg>

**Comment by gorhill** [comment]
Something else on your side is causing this (maybe another extension), investigate what it is.
