### ISSUE TITLE
Swift Selection Search addon compatibility

### ISSUE THREAD

**Issue by AlexFundorin** [gorhill/uBlock#2273]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

Subject addon's purpose is to show popup window near mouse cursor when text is selected. This windows contains list of firefox search engines, which can be used to search selected text.
I'm using Google, Wiki, Youtube and Google Translate engines. The thing is that when ublock is enabled, Youtube search engine is missing from the popup. 

Here you can find Swift - https://addons.mozilla.org/ru/firefox/addon/swift-selection-search/
And source code - https://github.com/CanisLupus/swift-selection-search

google.com, wikipedia.com and every other site, where ublock origin is enabled.

### Screenshot in which the issue can be seen

ublock enabled - http://i.imgur.com/iSZikg5.png
ublock disabled - http://i.imgur.com/obqIGHl.png

### Steps for anyone to reproduce the issue

1. Install Swift addon. In it's settings select desired search engines, including Youtube (default).
2. Enable ublock. Select any text on any site while ublock is enabled. No Youtube icon in popup.
3. Disable ublock. Select any text on any site while ublock is enabled. Youtube icon present in popup.

### Your settings

- Browser/version: 
Firefox 50.1.0 x64, W10
- uBlock Origin version: 
ublock origin 1.10.4

##### Your filter lists

Default lists plus three RUS lists:
 RUS: Adguard Russian Filter‎ (forum.adguard.com)
RUS: BitBlock List (Дополнительная подписка фильтров)‎ (forums.lanik.us)
RUS: RU AdList (Дополнительная региональная подписка)‎ (forums.lanik.us)

##### Your custom filters (if any)
none

**Comment by gorhill** [comment]
You did not provide **all** information required to reproduce the issue. You did not look at the logger as required. Had you done so, you would have seen that the filter `##img[title="YouTube"]` is causing this, which filter is in Fanboy's Social Blocking List, which you did not mention.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
