### ISSUE TITLE
Firefox Android configuration popup scrolling

### ISSUE THREAD

**Issue by ojz0r** [gorhill/uBlock#2274]
### Describe the issue
I have noticed that since a few firefox versions back, on android, that the ublock origin "popup" configuration page opening in a tab doesnt scroll anymore. The issue is that on landscape mode it adjusts to the width of the page without being able to scroll, unlike before when it stayed the same width as in portrait mode and thus fit more on the hight and i can distinctly recall being able to scroll it in both cases.

### Screenshot in which the issue can be seen
Landscape:
![screenshot_20161228-191032](https://cloud.githubusercontent.com/assets/24813994/21528398/79e6e554-cd32-11e6-930d-aef691bba9ea.png)

Portrait:
![screenshot_20161228-191046](https://cloud.githubusercontent.com/assets/24813994/21528394/705b2e28-cd32-11e6-8916-901b1ec80e22.png)

(Locale is Swedish)

### Steps for anyone to reproduce the issue

1. Alter firefox between landscape and portrait mode on the android phone.

### Your settings

- Browser/version: Firefox for Android 50.1.0
- uBlock Origin version: 1.10.4

**Comment by gorhill** [comment]
I forgot about rotation between landscape/portrait, will try to fix this case tomorrow.

**Comment by gorhill** [comment]
Fix available in dev build v1.10.5b4 on AMO.
