### ISSUE TITLE
Why no "Show ads everywhere except for these domains" option like in Adblock?

### ISSUE THREAD

**Issue by danid12** [gorhill/uBlock#2276]
It will be great if uBlock Origin will have such an option.

**Comment by uBlock-user** [comment]
because uBO is not Adblock??? Anyways, there's a white-list feature, use that.

**Comment by danid12** [comment]
What I ask for is black list, to block only specific sites. It can be very useful for many people.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except

**Comment by uBlock-user** [comment]
If you specifically want that, install uMatrix and run it in Allow all/Block Exceptional mode. That will blacklist only those websites you intend to block.

**Comment by danid12** [comment]
The solution to turn off ublock "everywhere except.." is good but works only on the elements level and not on on website level regardless of the specific elements.
