### ISSUE TITLE
Possible issue with chaining procedural operators

### ISSUE THREAD

**Issue by seanrand** [gorhill/uBlock#2278]
I'm using uBlock git HEAD at tag 1.10.5b4.

All right, I'm trying to craft a filter set utilising some procedural operators to replicate parts of [this userscript](https://greasyfork.org/en/scripts/6325-pinterest-without-registration/code), which makes pinterest usable without logging in.

So far, the working filter set (and a nice example of uBlock's capabilities) is
```
pinterest.com##div:has(:scope > div.FullPageModal__scroller)
pinterest.com##:xpath(//div[@data-test-giftwrap='true'])
pinterest.com##div[data-reactid][style*=fixed]:style(position: relative !important)
```

Example pages:
https://www.pinterest.com/explore/design/
https://www.pinterest.com/pin/529876712390175761/
The first two filters remove the various modal login overlays and the third filter makes the page scrollable again.

Problem with this is that the third filter messes up the layout on http://pinterest.com/
So I attempted to exclude http://pinterest.com/ by looking at the canonical link in the head element:

```
pinterest.com##div[data-reactid][style*=fixed]:style(position: relative !important):if-not(head > link[rel=canonical][href$='pinterest.com/'])
```
I also tried
```
pinterest.com##div[data-reactid][style*=fixed]:style(position: relative !important):if(head > link[rel=canonical][href$='pinterest.com/'])
pinterest.com##div[data-reactid][style*=fixed]:if-not(head > link[rel=canonical][href$='pinterest.com/']):style(position: relative !important)
```

When I look at `$('div[data-reactid][style*=fixed]')` in the dev console, I see that uBlock didn't construct a valid CSS style from that filter rule.
![screenshot-20161230t124317](https://cloud.githubusercontent.com/assets/929479/21564432/c0746ee0-ce8d-11e6-9b18-a050e3819b45.png)
Now that I think about it, the issue might be more with the :style operator not parsing correctly. Did I quote everything correctly?

---

Also, on an unrelated but relevant note, to make sure I'm understanding this correctly:
"subject:if(arg) - Select element subject if and only if the result of evaluating arg is one or more elements."

If arg evaluates to one or more elements, the subject element is selected. Selected in uBlock's case means that the filter rule is enacted on it (blocking/styling/etc), right?

Which would mean that when I create a filter such as `pinterest.com##div:if(.AppBase)`, arg should always evaluate to one element. If true then apply rule (block div).

I'm seeing the opposite behaviour though.
`pinterest.com##div:if-not(.AppBase)` hides the div (whole page is grey),
and :if does not apply the filter.

**Comment by gorhill** [comment]
`:style` is not chainable, as it is not an operator, it is an _action_, what to do with the resultset of elements, and as such must always appear at the end. Also, currently it can be applied only to plain CSS selectors, as it is used declaratively as a CSS rule.

**Comment by seanrand** [comment]
Oh, I wasn't aware, must have misread the docs.

**Comment by gorhill** [comment]
> When I look at `$('div[data-reactid][style*=fixed]')` in the dev console, I see that uBlock didn't construct a valid CSS style from that filter rule.

I should further validate the style property to avoid this non-sensical CSS declaration from being created in the first place.

**Comment by gorhill** [comment]
> I'm seeing the opposite behaviour though.
> `pinterest.com##div:if-not(.AppBase)` hides the div (whole page is grey),
and `:if` does not apply the filter.

I do not have a pinterest account, I can't look at the DOM to validate this. Can you post a screenshot of the DOM which make the case that `##div:if(.AppBase)` should evaluate to one or more node? Can you confirm there is indeed a descendant `.AppBase` inside the sibject `div`?

**Comment by seanrand** [comment]
No account needed to test that. And you just made me realise that my thoughts got scrambled up there, there's no .AppBase inside the div, the div is .AppBase. So, that's working as intended - sorry about that.
