### ISSUE TITLE
"Not Available for Android" on Firefox AMO

### ISSUE THREAD

**Issue by samueljun** [gorhill/uBlock#228]
This is what I'm currently seeing:

![screenshot_2015-05-22-00-09-54](https://cloud.githubusercontent.com/assets/1808588/7765817/5b84d394-0017-11e5-9ec4-0790fda10b4e.png)

Firefox Mobile 38.0.1
Installing from the releases page here works fine.

**Comment by gorhill** [comment]
I submitted for a full review and I think I may have selected the wrong set of checkboxes.

**Comment by aereaux** [comment]
![tmp_18968-screenshot_2015-05-27-19-15-22-1532977395](https://cloud.githubusercontent.com/assets/8238401/7850242/0790828c-04a5-11e5-9048-d044aa4f1d57.png).  For some reason if you go to more versions, it shows that Firefox for android is supported.

**Comment by gorhill** [comment]
> it shows that Firefox for android is supported

Because `install.rdf` file says it does support Android. However, for the store I do not check the box for Android, simply because there is no way for me to check whether it works or not, I have no access to a mobile device. I prefer to be cautious and not presume it works flawlessly without being able to verify.

**Comment by aereaux** [comment]
OK, thanks for the quick answer.  I have been using it for a while on android without problem, and it is slightly annoying not being able to have it auto-update.

**Comment by gorhill** [comment]
If one or more users are ready to test and report that all work fine with Android version prior to a release, I would be happy to mark again the extension as being compatible with Fierfox Mobile.

**Comment by samueljun** [comment]
The extent to which I've used uBlock is the default blocklists and importing my whitelist. I can vet those features as working for this release and I'd be glad to vet those features as working in the future.

**Comment by aereaux** [comment]
I'd also be willing to test stuff for future releases.

**Comment by gorhill** [comment]
Thanks for this. I guess the optimal way if you do not want to install the dev version is to wait for the release candidates. If the release candidate works fine on Android, I will mark the extension as available for Android in AMO.

**Comment by samueljun** [comment]
Sounds good to me. What's the best way to keep up with when the RCs are available?

**Comment by Manouchehri** [comment]
I'd also be happy to test it on Android, it's nice to have it on my tablet, saves a fair amount of loading time.

I'm using Chris' release at the moment and I haven't had any issues.

**Comment by gorhill** [comment]
There is a release candidate available. I plan to release to AMO maybe at the end of the day if all is well.

**Comment by samueljun** [comment]
Seems to be in order. Using the default list blocks ads. Whitelist work. Backup settings, restore settings, and reset to default settings is all working.

**Comment by gorhill** [comment]
@samueljun Thanks for testing. One thing I would like to further confirm, to see if updating the filter lists works fine. The read/write of settings was revised to comply with AMO review, and updating filter lists makes heavy use of that new code, so if it works all fine, including all the updated filter lists still being properly cached after restarting the browser, I will assume the code is all fine.

**Comment by AlexVallat** [comment]
To add one more data point, it's working for me too (Firefox 38.0.1 on Android 4.4.4), including updating the filter lists and restarting.

**Comment by samueljun** [comment]
Updating the filter lists worked. The filter lists persist after restarting the browser.
