### ISSUE TITLE
Ublock Origin Extra seemingly breaking Ubiquiti UniFi controller

### ISSUE THREAD

**Issue by AdrianKoshka** [gorhill/uBlock#2280]
### The issue:

Ubiquiti (a company who makes networking hardware) has a piece of software named
"UniFi". Unifi is used to manage their "Unifi" lineup of hardware, and seems to use
websockets, from some short glimpses I've seen of it loading.

Whether it be me accessing UniFi from my local network, or from the Unifi cloud
access site, I get a blank page. After being inspired by a user on the [ubiquiti
subreddit](https://www.reddit.com/r/Ubiquiti/comments/5lhzxn/unifi_just_loading_to_a_blank_page/) to do some trial and error I found that ublock extra seems to be
the cause of the UniFi login page not loading.

After disabling Ublock Origin Extra I could access my controller (and the demo
one setup by Ubiquiti).

### One or more specific URLs where the issue occurs

- https://unifi.ubnt.com
- https://demo.ubnt.com/manage/site/default
- and locally on my own network

#### I'm about to launch into my UniFi controller from the Ubiquiti cloud UniFi cloud access site

![unifi-launch](http://i.imgur.com/6K79DSc.png)

##### You can tell this is from the UniFi cloud access site because of it using SSO (single sign on) in the URL.

![blank-unifi](http://i.imgur.com/5l43IDy.png)

#### Me attempting to access my UniFi controller from my LAN.

![local-access-not-working](http://i.imgur.com/PesJRpc.png)

#### Proof I disabled it:

![disabled](http://i.imgur.com/5KehE73.png)

#### After disabling ublock origin extra, the page loads (local network)

![local-access-working](http://i.imgur.com/rMkB4ds.png)

#### After disabling ublock origin extra, the page loads (Unifi cloud access)

![unifi-cloud-working](http://i.imgur.com/Dn36yWX.png)

### Steps for anyone to reproduce the issue

1. Install google chrome
2. Install Ublock Origin
3. Install Ublock Origin Extra
4. Go to https://unifi.ubnt.com
5. Create a Ubiquiti account (sorry, no way to get around this really :S)
6. Click on the demo.ubnt.com entry, and press "launch" in the sidebar
7. wait for it to try and load the page, but seemingly fail and only see a white blank page

### Your settings

- chrome version: 55.0.2883.87 (64-bit)
- uBlock Origin version: 1.10.4
- uBlock Origin Extra version: 2.4

##### Your filter lists

Default Filter lists

##### Your custom filters (none)

No custom filters

**Comment by gorhill** [comment]
On my side 2.6 appears to fix the demo issue, but I would like you confirm it really fixes your real case on your side. You can [manually install](https://github.com/gorhill/uBO-Extra#installation) 2.6 from [Releases](https://github.com/gorhill/uBO-Extra/releases).

**Comment by AdrianKoshka** [comment]
Well I can access it from the UniFi cloud site, not at home right now though so I'll test it locally when I get home and report back.
