### ISSUE TITLE
 Peter Lowe’s Ad and tracking server list‎ - Hosts format is Downloaded

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2282]
uBO is downloading the **_Peter Lowe’s Ad and tracking server list‎_** in the hosts format for Windows and not in Adblock Plus format as was the case before.
I confirmed this by clicking on the list in the Dashboard and checking the downloaded cache. Also when I purged the cache and updated the list it was pulling it from here:
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext

**Screenshots:**
http://i.imgur.com/qfSSzVE.png - Cached list
http://i.imgur.com/ccWaheV.png - uBO downloading wrong list after purging cache

**How to reproduce?**
Purge cache of Peter Lowe’s Ad and tracking server list‎ and update lists, wrong format of list will be downloaded.

- Browser/version: Chrome 55
- uBlock Origin version: v1.10.4

**Comment by gorhill** [comment]
> and not in Adblock Plus format as was the case before

Wrong, it was never downloaded as Adblock Plus format.

**Comment by gotitbro** [comment]
@gorhill I must have got it wrong then, any reason for using the hosts format over the adblockplus one?
