### ISSUE TITLE
generichide rule problem

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBlock#2283]
### Describe the issue
uBlock does not enforce a filter with a `generichide` rule, if it is accompanied by a 
`genericblock` rule, probably because it doesn't support `genericblock`.
This effects some rules in `Easylistgermany`, for example.
`@@||spiegel.de^$genericblock,generichide`
`@@||tellows.de^$genericblock,generichide`

### Steps for anyone to reproduce the issue

1. Add `@@||github.com^$generichide` to your filter list
2. Go to `github.com`
3. Logger as expected
![gith](https://cloud.githubusercontent.com/assets/16838044/21594975/1caa6316-d129-11e6-910f-307bd318cc76.PNG)

4. If you add `@@||github.com^$genericblock,generichide` instead
![github1](https://cloud.githubusercontent.com/assets/16838044/21595095/6ea2ca36-d12a-11e6-88dd-37bebb5ad05e.PNG)

### Your settings

- Browser/version: Chrome 55
- uBlock Origin version: 1.10.4

##### Your filter lists

default

**Comment by lewisje** [comment]
I guess the `genericblock` option should be ignored rather than causing the whole filter to be rejected: https://github.com/gorhill/uBlock/issues/967#issuecomment-167368858
