### ISSUE TITLE
µblock, µmatrix - how to reduce overlap [focus on script blocking + µblock functionality]

### ISSUE THREAD

**Issue by kernelOfTruth** [gorhill/uBlock#2284]
µmatrix is mostly relying on the "hosts" file blocking 

whereas µblock origin has the option to block more on top of that (country based blocking),

First of all:

how are both interfering when both are run ?
What takes precedent ?

Then:

Is it okay if the hosts blocking files are disabled in µmatrix and only selective objects on the websites are disabled via µmatrix and the rest handled via µblock origin ?

Or is the opposite better ?

Alternatively:

could those additional options brought into µmatrix ?

or what is the rationale of not having country based blocking (this doesn't make sense from the outside) and other based blocking (this might be superseded by the more fine-grained blocking, I understand) ?

Many thanks in advance :)

**Comment by uBlock-user** [comment]
Only activate those settings which are already in use by either of the ext. If you activate one setting, then don't activate the same in the other, simple as that.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
