### ISSUE TITLE
Adguard Filter lists show as Outdated

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [gorhill/uBlock#2287]
Manually added Adguard Filters (for example: Adguard English Filter) keep showing as outdated even when i manually update them. This problem has only been occuring for a while (dont remember when exactly it started)

https://adguard.com/en/filter-rules.html?id=2 (Adguard English Filter)

### Steps for anyone to reproduce the issue

Just add https://adguard.com/en/filter-rules.html?id=2 manually to the filter list subscriptions and try to update it.

### Your settings

- Browser/version: firefox 50.1.0
- uBlock Origin version: 1.10.4

##### Your filter lists

Adguard English Filter (https://adguard.com/en/filter-rules.html?id=2)
but it happens for every adguard filter

**Comment by sdfasdfgawe456h4356** [comment]
problem seems to be gone ... it persisted for days and the minute i opened the issue it disappeared lol :D

**Comment by gorhill** [comment]
This can happen if you removed the whitelisting of behind-the-scene scope + enabled advanced user mode, in such case there is a filter in EasyList which will block the network request to Adguard server.

**Comment by sdfasdfgawe456h4356** [comment]
i didnt change anything and just now after several days it suddenly updated no idea whats going on but as long as it works now all is fine i guess. thx

**Comment by Tmp341** [comment]
Updated with no luck. So i used "clear cache" option for mine, unticked and ticked again. It doesn't show update, for now i think.
