### ISSUE TITLE
Cannot view video on Fox News

### ISSUE THREAD

**Issue by VLM-TechEd** [gorhill/uBlock#2288]
I am a new uBlock user, so probably this question is one of ignorance. 

I am looking at this page [http://www.foxnews.com/opinion/2017/01/06/sean-hannity-top-intel-boss-debunks-dems-big-lie-that-hacks-threw-election-to-trump.html.](url) As the page loads, I can see the image for the video, but then it blacks out. I have gone through the UI, turning items on/off, but I have not found a way to fix this. Instead of pecking through that list, is there a way I can see exactly what setting is blocking this element? Or solve the problem in some other way?

Thanks!

**Comment by mapx-** [comment]
no issues with ublock origin here (chrome). Are you using ublock origin or the outdated ublock ? what's the version ?

**Comment by VLM-TechEd** [comment]
uBlock Origin 1.10.4 in Pale Moon 26.5, Win 7.

**Comment by mapx-** [comment]
tested right now pale moon 27.0.3 + ubo, still no issue here. 
Are you using other blocking addons in palemoon ?

**Comment by VLM-TechEd** [comment]
Only BetterPrivacy, but that just deals with LSO cookies. I can't see how that would be a problem, since I haven't done anything in BP to touch Fox. However, I tried the same web page in IE and got the same result. So there is something wrong on my system that has nothing to do with uBlock. Will keep searching, thanks for your timely help!
