### ISSUE TITLE
[Edge] Can't check/uncheck 3rd party filters

### ISSUE THREAD

**Issue by jack-cole** [gorhill/uBlock#2289]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Clicking the checkboxes on the 3rd-party filters page doesn't work. The checkboxes appear to be clicked, but they don't get checked. (they highlight black on the inside when the mouse button is held down)

Edit: Actually it seems like no checkbox on any of the settings windows works at all

### One or more specific URLs where the issue occurs

ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62/dashboard.html#3p-filters.html

### Screenshot in which the issue can be seen

https://webmshare.com/KEJLm

### Steps for anyone to reproduce the issue

Install uBlock Origin on an Edge browser, go to the settings, and try adding 3rd party filters

### Your settings

- Browser/version: Microsoft Edge 38.14393.0.0, Microsoft EdgeHTML 14.14393
- uBlock Origin version: 1.10.2

##### Your filter lists

Default filter lists 

##### Your custom filters (if any)

none

**Comment by yupi2** [comment]
Post to the [Edge fork](https://github.com/nikrolls/uBlock-Edge)

**Comment by jack-cole** [comment]
OK I posted it at https://github.com/nikrolls/uBlock-Edge/issues/49
