### ISSUE TITLE
popups not being blocked at all

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#2290]
i upgraded to the latest ublock beta on firefox and popups arent blocked at all now and the dont show in the log. i hope im not the only one.

edit: it looks like even downgrading to ublock 1.10.4 doesnt change it. i don't understand what happened?

**Comment by gorhill** [comment]
You have repro steps with specific URL where this occurs?

**Comment by jo2dan23** [comment]
if i go here and click on the video i get a popup:

http://watchers.to/1vxmsclvs9li.html#Enjoy

**Comment by gorhill** [comment]
I can reproduce. Looks like a bad regression.

**Comment by gorhill** [comment]
Are you using Nightly? I could reproduce with Nightly, but not Firefox stable release -- all works as expected with Firefox stable, Pale Moon, or Chromium/Chrome.

I suspect there is an issue with Nightly. It's late now, I will look more into this tomorrow, but so far it seems to be an issue with Nightly.

**Comment by jo2dan23** [comment]
@gorhill yeah im using the latest nightly. so its a problem that they have to fix then? I wonder what they changed

**Comment by okiehsch** [comment]
I can reproduce `popup` issues with uBO  1.10.5.6 and Chrome 55.
1. Enable `no popup` switch for `github.com`
2. Open a new tab per right click on `https://github.com/gorhill`
3. This site is closed.
Logger
![image](https://cloud.githubusercontent.com/assets/16838044/21739969/6e52baa4-d4aa-11e6-92c8-1640673d5407.png)

**Comment by jo2dan23** [comment]
ok so did a fresh install on my pc because i had to anyways. i installed 1.10.5b5 and am running firefox nightly. looks like they changed something in the code because 1.10.5b5 blocked popups before i restarted and updated to the latest nightly.

**Comment by gorhill** [comment]
@okiehsch that would be a different issue, the one here is really a regression in Nightly.

**Comment by gorhill** [comment]
I do believe this might be related: <https://bugzilla.mozilla.org/show_bug.cgi?id=1329288>.
