### ISSUE TITLE
no-popups switch issue with dev build

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBlock#2291]
### Describe the issue
With no-popups switch enabled, opening a new tab  per right click results in the 
current tab being closed, if you use uBO 1.10.5b6.
It works fine with uBO 1.10.5b5

### Steps for anyone to reproduce the issue
1. Enable `no popup` switch for `github.com`
2. Open a new tab per right click on https://github.com/gorhill
3. As a result this tab is closed.
Logger
![image](https://cloud.githubusercontent.com/assets/16838044/21739969/6e52baa4-d4aa-11e6-92c8-1640673d5407.png)

### Your settings

- Browser/version: Chrome 55
- uBlock Origin version:  1.10.5b6

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
In investigating a fix for #2277, I changed the logic of no-popups switch without realizing it.
