### ISSUE TITLE
On click ads

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#2292]
Could you add an option to block all javascript on click events? or the option to block all javascript popups and have a whitelist with it as well. Most pages specially those that stream are using this method to force the opening of popups and sometimes it gets crazy and 5+ popups open at once everytime you click.

**Comment by lewisje** [comment]
That sounds like something that is out of scope.

**Comment by fenslett** [comment]
Do you know what function catches click event? And is it an inline script?
As of Origin 1.2.0 was introduced, you can block *specific inline script tag* in a web page using this:

```
example.com##script:contains(...)
```

For more information, see this [link](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#overview)

**Comment by rayman89** [comment]
Thanks @fenslett I wasn't aware of that. Really useful. Thank you devs for implementing it.

**Comment by lewisje** [comment]
IIRC inline-script filtering only works in Firefox-based browsers (different from blocking all inline scripts, which does work in Chromium-based browsers).
