### ISSUE TITLE
Problem with Adguard Russian filter and current uBO beta

### ISSUE THREAD

**Issue by TheFinalCut83** [gorhill/uBlock#2294]
### Describe the issue
In newest uBO beta (1.10.5b8) with Adguard Russian filter list doesn't work one of the Easylist filters (`://ads.$domain=~ads.am|~ads.colombiaonline.com|~ads.msstate.edu|~ads.nc|~ads.route.cc|~ads.sk|~ads.socialtheater.com|~badassembly.com|~caravansforsale.co.uk|~fusac.fr|~memo2.nl|~reempresa.org|~seriouswheels.com`). This filter is not triggered with 1.10.5b8 and doesn't present in logger; I know, this looks like a filter list issue (if you disable Adguard Russian filter, all is fine), but with absolutely the same settings in uBO 1.10.4 all works well, ads are blocked ([screen](http://i.imgur.com/IimgRmY.jpg), [logger](http://i.imgur.com/nLecdP0.jpg)). 
Note: when I investigated this issue in [Slimjet ](http://www.slimjet.com)(Chrome-based browser) with uBO 1.10.5b8, I saw error warning in the Extensions pane near uBO, maybe this will help. [Screen with the error.](http://i.imgur.com/JxjemTB.jpg)

### One or more specific URLs where the issue occurs
http://www.soccer0100.com/news/954065.shtml

### Screenshot in which the issue can be seen
Ads in red frames - [Scr1](http://i.imgur.com/dAn2z5f.jpg), [Scr2](http://i.imgur.com/wfdSoYD.jpg)

### Steps for anyone to reproduce the issue

1. Go to the link above with uBO 1.10.5b8 installed
1. See banners on the right side

### Your settings

- Browser/version: Firefox 50.1.0/51.0b12, Cyberfox 50.1.0, Slimjet 12.0.15.0
- uBlock Origin version: 1.10.5b8

##### Your filter lists

http://pastebin.com/yUZxWZCc

**Comment by gorhill** [comment]
I can reproduce. One of the regular expression is causing an error in Firefox (in browser console), but not in Chromium:

    SyntaxError: nothing to repeat          static-net-filtering.js:345:17

**Comment by gorhill** [comment]
This is caused by a wird (bad) filter in Adguard's Russian list:

    @@||ads.chatovod.ru^$domain=chat.muz-tv.ru|chatovod.ru|spiritix.eu|??????????.??|???????????????.??|?????????.??|???????????.??|??????????.??

I wasn't expecting such nonsensical filter to be in a list, uBO will have to be ready to deal with such filter -- i.e. continue to work as expected.

**Comment by ameshkov** [comment]
Hi @gorhill, thanks for alerting me!

Actually, there's no bad conversion, rule contains utf-8 characters indeed and looks like this:
`@@||ads.chatovod.ru^$domain=chat.muz-tv.ru|chatovod.ru|spiritix.eu|детскийчат.рф|подростковыйчат.рф|чатволчат.рф|чаткроватка.рф|чатобщения.рф`

Filter link:
http://filters.adtidy.org/extension/chromium/filters/1.txt

It's hard to use punycode for domain names all the time, so AG implicitly converts non-ascii domains to punycode when it parses the rule text.

**Comment by gorhill** [comment]
> Filter link:
> http://filters.adtidy.org/extension/chromium/filters/1.txt

Ok I see. When the `https://adguard.com/en/filter-rules.html?id=1` URL is used instead of the `filters.adtidy.org` one, all the unicode characters are replaced with `?`.

I need to replace the current URL with the new one.

**Comment by ameshkov** [comment]
Yup, it'd be much better to use the new links.

For which filters do you need to know the URLs?

Russian:
http://filters.adtidy.org/extension/chromium/filters/1.txt

English:
http://filters.adtidy.org/extension/chromium/filters/2.txt

Turkish:
http://filters.adtidy.org/extension/chromium/filters/13.txt
