### ISSUE TITLE
ubo options (chrome) opens chrome://extensions tab too

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#2295]
- ubo 1.10.4
- chrome Version 56.0.2924.51 beta (64-bit)
- how to reproduce:
right click ubo icon, click options ==> wont be opened only the ubo dashboard but also the extensions tab

is this a wanted behaviour (by design) ?

**Comment by Hrxn** [comment]
Yes.

Just left click on the icon, and then on the black bar at the top.

**Comment by mapx-** [comment]
yes, I know, I was talking about the other way.

**Comment by gorhill** [comment]
By browser design, it Chrome opening the `chrome://extensions` tab: <https://developer.chrome.com/extensions/optionsV2>.
