### ISSUE TITLE
Safari Equivalent

### ISSUE THREAD

**Issue by hihiguy** [gorhill/uBlock#2296]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Love your work. I know ublock origin and ublock are separate but is there any possibility of bringing ublock origin to Safari?? Or something similar with a different name? That would be awesome. You have the best blocker out there. Sorry if this comment is in the wrong spot, I couldn't find where else to query. Cheers and great work.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Hrxn** [comment]
https://github.com/el1t/uBlock-Safari#ublock-originfor-safari

**Comment by hihiguy** [comment]
You are the man! THANKS!!
