### ISSUE TITLE
oload.tv ublock detect 

### ISSUE THREAD

**Issue by Sdirgantara** [gorhill/uBlock#2299]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
oload.tv , or openload  detect ublock need disable  

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/23011078/21837711/76dacd66-d800-11e6-901b-e04fa6ec9089.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: oload.tv detect ublock
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
- Browser/version: UC browser ver. 6
- uBlock Origin version: 1.10.4

##### Your filter lists
![image](https://cloud.githubusercontent.com/assets/23011078/21837757/c550e066-d800-11e6-8549-3c56670a2c84.png)

##### Your custom filters (if any)

@@||mivo.com^$generichide
@@||mivo.com##script:inject(abort-on-property-read.js, blockAdBlock)

**Comment by aggat** [comment]
Right place for such issues [here](https://github.com/uBlockOrigin/uAssets/issues)
I could make it work by adding this 
`oload.tv##script:contains(logpopup)`
to `My filters` pane

**Comment by rjkpa** [comment]
^ That will only work on Mozilla based browsers, please don't suggest it as a generic solution.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
