### ISSUE TITLE
Logger timestamps are incorrect when system time zone is not on hour boundary

### ISSUE THREAD

**Issue by onetwothreefall** [gorhill/uBlock#2301]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Entry timestamps in the logger are incorrect when the system time zone's UTC offset is not on an hour boundary (e.g. Newfoundland Time Zone at -03:30 UTC, Nepal Standard Time at +05:45 UTC).

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

N/A

### Steps for anyone to reproduce the issue

1. Set the system time zone to one of the above-mentioned.
1. Open the logger, and take any action that adds new entries to the logger (e.g. open <https://github.com/gorhill/uBlock/> in a new tab)
1. Notice the timestamps of the new logger entries (specifically the minute value) do not match the current time.

Fix seems trivial: using `getUTCMinutes()` rather than `getMinutes()` in [line 546 of /src/js/logger-ui.js](https://github.com/gorhill/uBlock/blob/master/src/js/logger-ui.js#L546) gives the correct timestamp, since the offset is already applied via `setTime()`.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 51, Chromium 57
- uBlock Origin version: 1.10.4, 1.10.5b9

##### Your filter lists

N/A

**Comment by lewisje** [comment]
Consider making the PR yourself.

**Comment by gorhill** [comment]
Thanks for investigating the source of the issue.

**Comment by onetwothreefall** [comment]
Confirmed fixed in 1.10.7rc0. Thanks!
