### ISSUE TITLE
feature request, a lot keyboard shortcuts ;)

### ISSUE THREAD

**Issue by msagebiel** [gorhill/uBlock#2302]
like maybe scriptsafe, per domain allow all e.g.
Bottom of extensions settings in chrome.
Thanks for considering

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
Duplicate of #113.
