### ISSUE TITLE
New Function Suggestion: Reversed Whitelist

### ISSUE THREAD

**Issue by catshitz** [gorhill/uBlock#2304]
Stop blocking any ads except for the sites in the whitelist.

**Comment by uBlock-user** [comment]
Sounds utterly pointless.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
