### ISSUE TITLE
fast disappearing elements

### ISSUE THREAD

**Issue by danid12** [gorhill/uBlock#2305]
There are elements that disappear super fast and it is very hard and sometimes impossible to block them.

Good example is alexa site, they made in the last days change so there is very annoying popup that appears every time.

for example: http://www.alexa.com/siteinfo/cnn.com

Can ublock team find a solution for this problem?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
