### ISSUE TITLE
popups and popunders not blocked

### ISSUE THREAD

**Issue by ahmedtds** [gorhill/uBlock#2306]
Firefox 50.1.0 Windows
uBlock origin 1.10.4
All filters are up-to-date

Pages:
http://arenabg.com/
http://arenabg.com/torrents/

Just click some links or anywhere in page. There are many popunders slips through without being blocked.

**Comment by Hrxn** [comment]
https://github.com/uBlockOrigin/uAssets

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
