### ISSUE TITLE
How to specify javascript action

### ISSUE THREAD

**Issue by majkinetor** [gorhill/uBlock#2307]
Pop up on a site has a close button. If I create ublock filter it removes the popup, but unless it is closed via button, underlaying page becomes unusable (it is grayed and keyboard stops working).

I hopped there is a way to specify javascript action such as: `$("#popup-offer-close").click()`

Is that possible or am I totally missing something here ?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
It's called a UserScript.

**Comment by majkinetor** [comment]
@lewisje , I use TemperyMonkey with Chrome now, I thought this one could replace it.

**Comment by gorhill** [comment]
It's a filter issue, the optimal solution might be (and is likely) different than one you have in mind. Just submit _specifics_ to filter list maintainers or at uAssets. Without specifics, nobody can help.
