### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by fabswt** [gorhill/uBlock#2308]
Hi,

Is there any chance to get an option to **disable notifications in the toolbar**?

Getting a counter of how many ads were blocked is distracting. The whole point of an ad-blocking system is to avoid distractions.

Thank you for reading.

Best –
Fabien

**Comment by gorhill** [comment]
Just disable it in setting: <https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings>.

**Comment by uBlock-user** [comment]
> Getting a counter of how many ads were blocked is distracting. The whole point of an ad-blocking system is to avoid distractions.

Contrary to what you believe, it's not "number of ads", it's the number of network requests being blocked. Secondly, it's not distracting, it provides useful information if you were to look into the logger. If you feel distracting, then it's subjective to your belief only, not a fact as you're trying to establish here. 

Lastly, you could have found the setting if you were to explore the extension option before posting the topic and avoiding the whole trouble of making one. 

Also, uBO is not an adblocker, so you might as well not treat it like one. From what I can see here, you prefer install once and forget forever approach, which would be perfect if you were using ABP or any other generic ad blocker.

**Comment by fabswt** [comment]
There's no need for being aggressive. 

I looked for it in the plugin's Preferences, it isn't there -- missed the small cog that gives access to the dashboard.

As for any form of feedback, well, it's valuable or not depending on whether you want it to be.
