### ISSUE TITLE
Can't use the :has-text operator

### ISSUE THREAD

**Issue by migueldemoura** [gorhill/uBlock#2309]
### Describe the issue

I read the [docs](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjecthas-textneedle) on the :has-text operator and tried to use it on a couple of sites, but couldn't make it work.

One example of this operator, apart from the docs, is [this one](https://github.com/uBlockOrigin/uAssets/blob/cb666bc6c3dd4ad2b6f954bcb34e639fe4fa1f8f/filters/filters.txt#L1120):

`nextinpact.com###list_news > section[class]:if(:scope > span:has-text(Publicité))`

Apart from the fact that the "section" has to be replaced with "div", it doesn't work, and makes the textbox on the blocking gui assistant red (I'm assuming that means the filter is invalid).

Another, simpler, example is this one:

`migueldemoura.com##li > a:has-text(GitHub)` 
or
`migueldemoura.com##a:has-text(GitHub)` 

Am I missing something?

### One or more specific URLs where the issue occurs

Example: [https://migueldemoura.com](https://migueldemoura.com)

### Steps for anyone to reproduce the issue

Just try the filter either using the gui or by pasting it into the settings.

### Your settings

All Privacy settings are on.

- Browser/version: Chrome 55.0.2883.87 (64-bit)
- uBlock Origin version: 1.10.4
- *buntu 16.10

##### Your filter lists

All but the regional ones.

#### Side note

If anyone is interested, you can block the ad placeholders on that page (at least in the home) with:

```
www.nextinpact.com###sidebar_pub_top
www.nextinpact.com##.side_content_pub
! Also removes an obnoxious self-promo that wastes space
www.nextinpact.com###container_ban_pub_jauge
```

These work with ABP, so no need to report them to the assets repo. The 2nd rule over there is no longer relevant though.

**Comment by gorhill** [comment]
Not available in 1.10.4.
