### ISSUE TITLE
Inserted Inline Style causes CSP violation

### ISSUE THREAD

**Issue by theseer** [gorhill/uBlock#2310]
For a website with this basic, yet strict Content Security Policy

```
Content-Security-Policy: default-src 'self'; report-uri /report;
```

the inserted <style> node with inline css causes a CSP violation (at least in Firefox) and triggers a violation report to the site. As can be seen in the screenshot, the report details show the content of the style node. Apart from spaming the website with pointless reports, the content of the report's script-sample tells the server uBlock origin is used.

![screenshot from 2017-01-15 18-47-39](https://cloud.githubusercontent.com/assets/111333/21965027/a7453ea0-db57-11e6-92bd-eac38589c6d2.png)

![screenshot from 2017-01-15 19-39-03](https://cloud.githubusercontent.com/assets/111333/21965162/5c7380f0-db5a-11e6-96d7-6e0a94ec0f1e.png)

When uBlock Origin is disabled, the CSP violation does not occur. If "unsafe-inline" is added to the CSP rule, the violation also vanishes - though that is obviously not a fix ;)

I created a small sample PHP script for easy reproduction, served via `php -S 127.0.0.1:8080`. It was used to create the output shown in the screenshots:
```
<?php
header("Content-Security-Policy: default-src 'self'; report-uri /report;");
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de">
    <head>
        <meta charset="UTF-8"/>
        <title>sample</title>
    </head>
    <body>
        <p>Hello world.</p>
    </body>
</html>
```

### Your settings

- Browser/version:  Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
- uBlock Origin version:  1.10.4

I have reset all uBlock settings to factory default. I have also updated all filters on the 3rd party filters tab.

##### Your filter lists

Default filter lists

**Comment by theseer** [comment]
Additional note:
I seem to be unable to reproduce this problem with *only* the given stripped-down testcase on a freshly started instance of Firefox. I have to first open another page that causes the same CSP error. After that I can reload the sample page as after as I want I always get that error.

The "other page" is servers locally from a different port.

I'm not sure if that is in any way related.

**Comment by gorhill** [comment]
Can you try with latest uBO 1.10.5 beta, it's in dev channel on AMO.

**Comment by theseer** [comment]
Will do first thing in the morning.

**Comment by theseer** [comment]
With version `1.10.5b9` I cannot reproduce the behavior described anymore.

So from my perspective, this issue is closed.
