### ISSUE TITLE
Article pages on Runner's World are blurred out

### ISSUE THREAD

**Issue by miishke** [gorhill/uBlock#2311]
Any link to an article from runnersworld.com gets blurred - please not that the front page has nothing blurred.

Blurred link: [http://www.runnersworld.com/boston-marathon/marathon-world-record-holder-added-to-the-2017-boston-field](url)

![selection_039](https://cloud.githubusercontent.com/assets/4196718/21965899/161df356-db37-11e6-92b1-4140ad96be75.png)

Chrome 55.0.2883.87 (64-bit) on Linux
uBlock Origin v1.10.4
Filter list is the default one, no custom filters.

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Report your problem to the maintainers of the appropriate lists.

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=111846#p111846
