### ISSUE TITLE
Blocking in-line javascript in Chrome/image that loads image with random data

### ISSUE THREAD

**Issue by pavlukivan** [gorhill/uBlock#2312]
There's a website that randomizes image data like that:
data:image/png;randomString;base64,base64ImageData
I'm looking for a way to block it.
I've found an inline javascript that loads that image. Howewer, I'm using chrome so I cant block it. Is it possible to block it (except for creating a rule for each of 36^11 possible randomStrings)? Maybe via some function overloading.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
