### ISSUE TITLE
uBlock0 1.10.5b9 and unsigned add-on denial?

### ISSUE THREAD

**Issue by DaveBurbank** [gorhill/uBlock#2313]
I really want to help test uBlock0.
Using firefox 51.0b14 with xpinstall.signatures.required set to false. How can I install uBlock0 1.10.5b9 without getting the unsigned add-on denial?

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
[Front page of the project](https://github.com/gorhill/uBlock#firefox--firefox-for-android):

> [Firefox Add-ons web site](https://addons.mozilla.org/addon/ublock-origin/). There is also a development version if you want to test uBlock Origin with the latest changes: **[see uBlock Origin Version History](https://addons.mozilla.org/addon/ublock-origin/versions/beta)**
