### ISSUE TITLE
Malware Block List (Malware Patrol) falsely identifying uBlock as trouble

### ISSUE THREAD

**Issue by kgizdov** [gorhill/uBlock#2315]
I was running ClamAV on my Linux the other day and it spat a bunch of detections for an extension in Chrome, identified by this ID - cjpalhdlnbpafiamejdnhcphjbkeiagm. This comes from the filter at [Malware Patrol](http://www.malware.com.br/index.shtml). It might be a good idea to add another entry to the [False Positive page](https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin).

I also tried to contact them, but their contact form is really not helpful. Maybe someone else has better luck.

I was also wondering if uBlock could be a vector for malware - meaning malware having integrated itself in my local uBlock after installation? I can't tell if uBlock is verified by Chrome in some way.

**Comment by lewisje** [comment]
Chrome extension content *is* verified by hashes.

**Comment by kgizdov** [comment]
@lewisje on runtime as well or installation only?

**Comment by gorhill** [comment]
Each time before the extension is launched I believe. You can find out by removing or adding something and see what happens when you enable the extension.

**Comment by kgizdov** [comment]
OK, I am satisfied that all is good with the extension itself. I also managed to contact Malware Patrol and let them know of the issue. Not sure how they will handle it.

**Comment by gorhill** [comment]
Could you drag-n-drop here a screenshot of what ClamAV + Malware Patrol warns regarding uBO?

**Comment by Atavic** [comment]
[Here](http://www.malware.com.br/howto_clamav.shtml) they say they use [Extremeshok's clamav-unofficial-sigs](https://github.com/extremeshok/clamav-unofficial-sigs/), while ClamAV allows you to [ignore/whitelist](http://www.clamav.net/documents/how-do-i-ignore-whitelist-a-clamav-signature) individual signatures.

**Comment by kgizdov** [comment]
This is an exerpt of the log with the relevant bits:
```bash
/home/gizdov/.config/google-chrome-back-ovfs/Default/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.10.4_0/assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt: MBL_1191716.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Default/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.10.4_0/assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt: MBL_4437670.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Default/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.10.4_0/assets/thirdparties/mirror1.malwaredomains.com/files/justdomains: MBL_2730588.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Default/Local Extension Settings/cjpalhdlnbpafiamejdnhcphjbkeiagm/000347.ldb: MBL_3307899.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Default/Local Extension Settings/cjpalhdlnbpafiamejdnhcphjbkeiagm/000217.ldb: MBL_3233778.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Subresource Filter/Unindexed Rules/4/Filtering Rules: MBL_4437670.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Subresource Filter/Indexed Rules/10/4/Ruleset Data: MBL_4437670.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Profile 1/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.10.4_0/assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt: MBL_1191716.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Profile 1/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.10.4_0/assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt: MBL_4437670.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Profile 1/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.10.4_0/assets/thirdparties/mirror1.malwaredomains.com/files/justdomains: MBL_2730588.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Profile 1/Local Extension Settings/cjpalhdlnbpafiamejdnhcphjbkeiagm/000067.ldb: MBL_3307899.UNOFFICIAL FOUND
/home/gizdov/.config/google-chrome-back-ovfs/Profile 1/Local Extension Settings/cjpalhdlnbpafiamejdnhcphjbkeiagm/000022.ldb: MBL_3233778.UNOFFICIAL FOUND
```
so it could be that it is detecting domain strings in the database rather than uBlock itself, but I can't be sure.

**Comment by gorhill** [comment]
> it could be that it is detecting domain strings in the database

It detected something in the malware lists and EasyList. The other hits are because uBO will cache the remote content of these lists locally, so there are also hits for whatever files Chrome uses to save extension data (through `chrome.storage.local` API).

It apparently also detect something in Chrome's own block lists.

This confirms false positive.
