### ISSUE TITLE
Can't load any asset

### ISSUE THREAD

**Issue by djcf** [gorhill/uBlock#2316]
I am using uBlock 0.5.9.0.1-let-fixed on Firefox 50.0.2. In the last few days, uBlock has started to block *every external asset*, even assets originating on the page themselves. It does this for *every website* and *every URL*. The problem seems localized: it doesn't happen on Chrome, where I also run uBlock. It would seem like a settings change but I'm not sure what, if anything, I did to cause the change. Please see attached screenshot. In this example, whatever else it is blocking, uBlock should not be blocking assets from startpage.com when I navigate to startpage.com. AdvancedMode is not enabled and I am not aware of any way I have customized uBlock after the default install. When I disable uBlock for that site and click reload the site loads as normal, albeit, of course, with ads.
![screenshot from 2017-01-17 19-19-33](https://cloud.githubusercontent.com/assets/1577064/22036221/ac2cc4ee-dcea-11e6-92cc-4d53c690be40.png)

**Comment by gorhill** [comment]
Wrong repo: uBlock Origin is unrelated to [uBlock](https://github.com/chrisaljoudi/uBlock).
