### ISSUE TITLE
masrawysat.com

### ISSUE THREAD

**Issue by MahmoudKandeel** [gorhill/uBlock#2321]
http://www.masrawysat.com/vb/forumdisplay.php?f=15
is there any filter to block that dam site ads and popups, it contains alot of ads with several popups, please help
that is my settings
http://i.imgur.com/5DFZEmm.png
http://i.imgur.com/5GgRDAN.png
thanks in advance

**Comment by mapx-** [comment]
you already had your filters:
https://forums.lanik.us/viewtopic.php?p=112016#p112016

and you confirmed they work.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
