### ISSUE TITLE
overlay cannot be selected on forbes.com

### ISSUE THREAD

**Issue by elypter** [gorhill/uBlock#2322]
when opening forbes.com there is an overlay that usually closes after a few seconds. however if you have umatrix running the script and cookies required for closing do not work. if you then try to use the element picker of ublock the first layer can be deleted but for the second layer the page does not turn red and the dialog on the bottom right does not appear.

for example go on this page(make sure that you do not have any forbes.com cookies):

http://www.forbes.com/forbes/welcome/?toURL=http://www.forbes.com/sites/quora/2017/01/18/i-was-a-spacex-intern-and-this-is-how-i-got-the-job/&refURL=&referrer=#47416a14697b

and then try to remove the overlays

tested with firefox and vivaldi

**Comment by gorhill** [comment]
There is no overlay, it's the `<body>` element itself which is left, and the element picker does not allow to remove the body element as it makes no sense to do so. The site is tricking you into thinking there is an overlay blurring the text, but it's all fake, what appears to be text is just a background image, which you removed with your first attempt.

**Comment by elypter** [comment]
oh, i didnt think of that. those sneaky fuckers. in situations like this it could be helpful if the element picker  allows to select to block just the background image

**Comment by gorhill** [comment]
> it could be helpful if the element picker allows to select to block just the background image of a node.

It's already implemented, the element picker will offer you to block the background image of whatever it can find under the mouse. Back on topic, Forbes works fine with uBO + default filters.

**Comment by elypter** [comment]
thats great. maybe allow it to block the bg image of <body> too. some website migth decide to bake ads into the website bg or some bgs are just annoying for users or in this case decieving.

>Back on topic, Forbes works fine with uBO + default filters.

thats correct.

**Comment by gorhill** [comment]
> maybe allow it to block the bg image of too

If you meant "of `body` element", you can.
