### ISSUE TITLE
Empty list of 3rd-party filters after update to beta 10

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#2323]
Errors from browser console:
<a href="https://lh3.googleusercontent.com/-bk3qtkj3Noo/WICewhwESHI/AAAAAAAAdWI/jsiNANnExGA/s0/screenshot%2525202017-01-19%252520001.png"><img src="https://lh3.googleusercontent.com/-7FydDBcTq8A/WICexO_DVZI/AAAAAAAAdWM/-xWhSaYByo4/s0/thumb_7517d84fe2eaf530a5ac099d24a8a506.jpg" border=0></a>

Win 8.1 x64, Firefox Nightly 53.0a1 x64 BuildID:20170118030214, e10s disabled. uBlock Origin v1.10.5b10.

**Comment by gorhill** [comment]
Which version did you have before? How did you update the extension? (did you backup your data before, and if so, does the restore work?)

I had this happen with Pale Moon, but I could not find out what happened -- seems to be a Firefox thing as I tested a lot with Chrome and this did not happen. I just tried with FF 50 and all went fine.

**Comment by gorhill** [comment]
By the way, I just noticed your version does not seem to be an official one, the dashboard appears to have been customized.

**Comment by Halibut80** [comment]
>Which version did you have before?
beta 9
>How did you update the extension? 
Manually install, from repo
 >does the restore work?
No. But after install b9 "3-rd party filters" tab work again.
>By the way, I just noticed your version does not seem to be an official one, the dashboard appears to have been customized.
Just css. Disabling custom style does not fix this issue.

**Comment by gorhill** [comment]
Ok I think I might know what is happening. The magic ids did not change between b9 and b10 and maybe uBO is loading from a selfie and this is probably not good (the magic id changes between 1.10.4 and 1.10.5b10 though so in my test this all worked).

**Comment by Havokdan** [comment]
This happened to me, I decided as follows:

1 - Backed up my settings;
2 - I have reset the uBlock settings;
3 - Imported the settings.

**Comment by gorhill** [comment]
Confirmed to be the selfie. Will fix ASAP.

A simple step such as just just adding a custom filter `toto` makes the _"3rd-party filters"_ pane renders properly.
