### ISSUE TITLE
Ad provider: uponit

### ISSUE THREAD

**Issue by resetnow** [gorhill/uBlock#2324]
### Describe the issue

There is an ad provider that uses a number of methods to deliver ads even when they're blocked: <a href="https://uponit.com">https://uponit.com<a>. Their technology is mostly used on garbage clickbait sites and relies on detecting blocked requests and forwarding them though their own servers (which seem to be hosted on some existing CDN?). DOM elements are being inserted with inline styles and `!important` display values.

### One or more specific URLs where the issue occurs

The ads seem to be served with a 3-4 second delay.

http://www.allthetests.com/quiz33/quiz/1484289648/How-much-do-you-know-about-The-Gabbie-Show

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/2057191/22166058/89b29192-df78-11e6-9ca7-eb63a0102bdf.png)

### Your settings

- Browser/version: Firefox 50.1.0
- uBlock Origin version: 1.10.4

##### Your filter lists

Default filter lists + RU

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by resetnow** [comment]
This isn't a filter list issue. It can't be solved with a filter — there is no list, the CDN they use is generic and seems to host other content.

**Comment by gorhill** [comment]
> This isn't a filter list issue. It can't be solved with a filter

    *$websocket,domain=allthetests.com
    ||wodizapt.com^

Report to EasyList maintainers please.
