### ISSUE TITLE
mobile.twitter.com & Parse and enforce cosmetic filters

### ISSUE THREAD

**Issue by LESHIY-ODESSA** [gorhill/uBlock#2325]
Hello.

On mobile.twitter.com site at inclusion "Parse and enforce cosmetic filters" not running a pop-up menu.

http://i.imgur.com/pv4So02.gif
http://i.imgur.com/KqJlrTS.png

Firefox 53.0a1
uBlock Origin version: 1.10.5b9

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
