### ISSUE TITLE
Ublock caught by adblock blocker on cwtv.com

### ISSUE THREAD

**Issue by badtzmaru** [gorhill/uBlock#2326]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When attempting to watch a video on [cwtv.com/](http://www.cwtv.com/) uBlock is detected, and the video will not play without disabling the extension.

### One or more specific URLs where the issue occurs
No videos on the [cwtv site](http://www.cwtv.com/) are playable. [Here](http://www.cwtv.com/shows/the-flash/the-present/?play=d08d09a0-6379-428e-b09e-0d5ab844c272) is an example.
### Screenshot in which the issue can be seen

http://i.imgur.com/wrYwJua.png

### Steps for anyone to reproduce the issue

Go to [cwtv.com](http://www.cwtv.com/).
Click on any full episode from a current show. (or use [this](http://www.cwtv.com/shows/the-flash/the-present/?play=d08d09a0-6379-428e-b09e-0d5ab844c272) link.
uBlock will be detected as an adblocker, and the video will not play.

### Your settings

My settings are all still set to default.

- Browser/version: Google Chrome Version 55.0.2883.87 m
- uBlock Origin version: 1.10.4

##### Your filter lists

Default filter lists + FRA

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
