### ISSUE TITLE
Lock unexpected

### ISSUE THREAD

**Issue by Albert456** [gorhill/uBlock#2327]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### https://issuu.com/vodafonenovedades/docs/epaper_revista_94_cast_
"Always on this site"

[URL(s) for issue on a specific site are **mandatory**]

### http://i66.tinypic.com/118kr39.png

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Google Chrome, Version 55.0.2883.87 m (64-bit)
- uBlock Origin version: uBlock Origin 1.10.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"
! Examples:
! https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt
! https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt

##### Your custom filters (if any)

@@||iptvbin.com^$generichide
@@||sport.es^$generichide
@@||elperiodico.cat^$generichide
@@||pagead2.googlesyndication.com^$domain=iptvbin.com
@@.png#$domain=iptvbin.com
||rolinda.work
http://s.click.aliexpress.com/e/bMbmIAqvf

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Also, please do not use such dubious external sites for hosting your screenshots, just drag-n-drop the images directly in the text area of the issue to add images.
