### ISSUE TITLE
YouTube Cosmetic Damage

### ISSUE THREAD

**Issue by neoaptt** [gorhill/uBlock#2329]
I downloaded ublock, installed it, updated the default filters. Went to Youtube.com hovered over the name.

![test](https://cloud.githubusercontent.com/assets/9214528/22190367/d0814b44-e0f0-11e6-95c4-b93b789ef218.gif)

It should look like this.

![test1](https://cloud.githubusercontent.com/assets/9214528/22190407/fdf2e4ac-e0f0-11e6-95f0-43710cdf4c81.gif)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Hrxn** [comment]
Can't reproduce, btw. Seems to work on my end.
