### ISSUE TITLE
Facebook on Whitelist!

### ISSUE THREAD

**Issue by lukanz** [gorhill/uBlock#233]
i really would like to know why facebook is on the whitelist from strach, and there is no way to remove them! 
this are the 2 rules:
@@||facebook.
@@||fbcdn.net

**Comment by gwarser** [comment]
Where you see them?

**Comment by lukanz** [comment]
![facebook](https://cloud.githubusercontent.com/assets/12429282/7780019/2e0b244a-00da-11e5-93b4-0518e39ce69c.jpg)
i'm using my own adblock list (http://anz.bplaced.com/ff/adl/adblock.txt ) nothing else but with EasyList‎ as the only list enabled there is no problem!

**Comment by gorhill** [comment]
Can't reproduce. Look carefully in your custom filters, there must be entries matching what the logger report.

**Comment by gwarser** [comment]
Probably side effect of your filter
`||facebook.*$domain=~facebook.com|~fb.com`
block `facebook.` everywhere, except on facebook.com and fb.com

**Comment by gorhill** [comment]
@lukanz Could you please provide a URL you navigated when you took that screenshot? (please read **carefully** <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>).

**Comment by lukanz** [comment]
@gwarser you were right, disabling those rules,solved it, but it should be ignored instead of whitelisted, i guess!!
it seems that these rules cause it too 
||facebook.com$domain=~www.facebook.com
||facebook.net$domain=~www.facebook.com
||fbcdn.net$domain=~www.facebook.com 


@gorhill sorry my bad!
1. https://www.facebook.com/
2. open ublock and hit request log & took the screenshot

**Comment by gorhill** [comment]
So you have filter exceptions for when visiting `facebook.com` -- worked as expected.
