### ISSUE TITLE
adguard lists wont add

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#2331]
am on latest ublock beta. if i add any adguard lists to custom filters they dont change name or update. shows 0 out of 0 filters example:

https://adguard.com/en/filter-rules.html?id=2

**Comment by gorhill** [comment]
Did you use the logger with _All_ selected to find out what happens to the fetch requests?

**Comment by jo2dan23** [comment]
ah. my bad. looks like easylist is blocking  /adguard in behind the scene. don't know why they added that filter rule. sorry about that.

**Comment by harshanvn** [comment]
Looks like all the filters were considered invalid..
Just a snippet of the logger..

> 14:56:11		Network filtering – invalid filter: hyperspeeds.com$$div[tag-content="Please enable / Bitte aktiviere JavaScript"][max-length="1200"]
14:56:11		Network filtering – invalid filter: whsports.tv$$div[tag-content="Please enable / Bitte aktiviere JavaScript"][max-length="1200"]
14:56:11		Network filtering – invalid filter: uptobox.com$$script[tag-content="adblock.html"][max-length="3000"]
14:56:11		Network filtering – invalid filter: allsoftinone.com$$script[tag-content="displayMessage("]
14:56:11		Network filtering – invalid filter: allsoftinone.com$$div[tag-content="Please enable / Bitte aktiviere JavaScript"][max-length="400"]
14:56:11		Network filtering – invalid filter: getdebrid.com,debridfast.com,debrid.us$$script[tag-content="adblocker.html"]
14:56:11		Network filtering – invalid filter: @@||extremetech.com^$jsinject,generichide
14:56:11		Network filtering – invalid filter: intoday.in$$script[tag-content="checkAds"][max-length="1550"]
14:56:11		Cosmetic filtering – invalid filter: #alert-danger-enabled { display: none!important; }
14:56:11		Network filtering – invalid filter: @@||download.jkmk.net^$genericblock,~image
14:56:11		Network filtering – invalid filter: openload.co$$script[tag-content="if(typeof adblock"]
14:56:11		Network filtering – invalid filter: @@||4fuckr.com$content,generichide
14:56:11		Network filtering – invalid filter: @@||hackintosh.computer^$generichide,genericblock
14:56:11		Network filtering – invalid filter: @@||uploadocean.com^$generichide,content
14:56:11		Network filtering – invalid filter: @@||trmagnet.mac-torrent-download.net$elemhide,content
14:56:11		Network filtering – invalid filter: indiatimes.com$$script[wildcard="*var _0x*false;if(!_0x*}(document,window));*"][max-length="8000"]
14:56:11		Network filtering – invalid filter: indiatimes.com$$script[wildcard="*blockit*adblocker*var chk*"][max-length="6000"]
14:56:11		Network filtering – invalid filter: theatlantic.com$$script[tag-content="function redirect()"][max-length="1700"]
14:56:11		Network filtering – invalid filter: @@||bdcraft.net/download/?$content
14:56:11		Network filtering – invalid filter: ||allmusic.com^$replace=/_0xe367/0xFFFF/,important

**Comment by gorhill** [comment]
> But many filters are invalid

Yes, these are Adguard-specific filter syntax.

**Comment by harshanvn** [comment]
Ok. Thanks.
