### ISSUE TITLE
Cosmetic bug when removing custom lists

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#2332]
When you have more than one custom list 
- click on X to remove first one
- click Apply changes

Strikethrough effect stays on (is moved to) next position

Edit:
Another one:
- deselect one filter
- Apply changes
- click on X to remove it 

"Apply changes" button not appears.

Fx 52 UBO 1.10.5rc0

**Comment by migueldemoura** [comment]
What 'X' are you talking about? Can you provide some screenshots and specify your OS?

**Comment by gwarser** [comment]
In latest beta/rc custom lists looks like this:
![image2](https://cloud.githubusercontent.com/assets/886325/22224991/0d29567e-e1c1-11e6-8bbc-fa0b2660d05c.jpg)

Linux Mint 17.3

**Comment by gorhill** [comment]
@gwarser Do you build your own uBO? I rather wait tomorrow to published rc1 in case more issues are reported. The workaround currently for this issue is to force a refresh of the pane (select another pane then select again _3rd-party filters_).

**Comment by migueldemoura** [comment]
I built from the latest commit and the issue seems to be fixed.

@gorhill, should probably change the icon for reversing the list removal, i.e., in @gwarser's screenshot, `Adguard English Filter` shouldn't have the same 'X' icon as the rest. Maybe this instead:

http://fontawesome.io/icon/undo/

**Comment by Betsy25** [comment]
Posting this here since I think this might be related, but is the textbox below the custom filter items supposed to be empty ?

Screenshot of the issue : [https://s29.postimg.org/core794g7/2017_01_24_215048.jpg](https://s29.postimg.org/core794g7/2017_01_24_215048.jpg)

**Comment by gorhill** [comment]
> the textbox below the custom filter items supposed to be empty?

Yes. It is not a text field to use for import purpose, not for declaration purpose.
