### ISSUE TITLE
about:blank popups not being blocked again

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#2333]
on latest firefox nightly and ublock beta, i have the no popups true set and somehow they are allowed now :( it blocks other popups and shows about:blank in log but doesnt block it.

screenshot: https://i.imgsafe.org/6b2e06a88e.png

reproduce: go here: https://psarips.com/ and click on a part of the page that the hand doesnt appear as your mouse icon and you will get a about:blank popup shown in logger

**Comment by ilsuli** [comment]
same here , can someone help plz

**Comment by jo2dan23** [comment]
@ilsuli what browser?

**Comment by ilsuli** [comment]
google chrome

**Comment by gorhill** [comment]
> i have the no popups true set

By design: `about:blank` won't be blocked by the no-popups switch, they work only on popup for which a valid hostname can be extracted.

**Comment by uBlock-user** [comment]
Use `|about:blank$popup`
