### ISSUE TITLE
selectively enable large media elements

### ISSUE THREAD

**Issue by yossizahn** [gorhill/uBlock#2334]
### Describe the issue
cannot selectively enable large media elements

### One or more specific URLs where the issue occurs
all sites with more than 1 large-media-element according to configured settings. e.g. (taken from wiki page for per-site switches) http://www.tomshardware.com/reviews/samsung-gear-vr-headset,4405.html

### Steps for anyone to reproduce the issue

1. set "block media elements larger than 50kb"
1. enable logger
1. navigate to http://www.tomshardware.com/reviews/samsung-gear-vr-headset,4405.html
1. logger shows multiple large-media-elements blocked
1. hover mouse over a blocked picture - it will show a magnifying glass
1. click on blocked picture - reload will be attempted 
1. logger shows that the reload was blocked due to "no-large-media: * true"
1. temporarily enable large-media-elements - all blocked pictures display

summary:
there is no way to selectively enable large-media-elements and there is no apparent function for the magnifying glass on hover over blocked picture - unless for some reason the blocked element is constantly changing size.

### Your settings
globally block media elements larger than 50kb

- Browser/version: chrome 55.0.2883.87 m (64-bit)
- uBlock Origin version: 1.10.4

**Comment by yossizahn** [comment]
**Update:** I didn't mention before that I am normally on a very slow connection, and via a proxy. Today when using a fast connection and no proxy I had no problems at all and clicking on a large media element immediately enabled it. So I don't know  if it's the connection speed or the proxy causing thing not to work.

**Comment by gwarser** [comment]
Emulating "Slow 3g" in dev tools, Network tab in Chrome Version 86.0.4240.75 (Official Build) (64-bit). Link from OP, 50kB limit.

Click to load does not allow image to load in 1.30.4.

Loading works as expected in 1.30.5b6. There is a small delay before dotted border is painted - can be page loading images with delay (lazyload)?

**Comment by gorhill** [comment]
> can be page loading images with delay (lazyload)?

The content script for interactivity is injected  with `document_idle`, so it could be just the browser taking its time to inject the content script (it takes care to apply the red border style).

**Comment by gorhill** [comment]
Closing as fixed with recent changes to the related code. A new issue should be opened if new cases are identified.
