### ISSUE TITLE
ads.am

### ISSUE THREAD

**Issue by sevak88** [gorhill/uBlock#2335]
uBlock полностью блокирует мой сайт. `[redacted]`
   Английская версия `[redacted]`
хотя нет никакой рекламы, я думаю, что он блокирует сайт от имени домена.
Сайт предназначен для размещения объявления

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
