### ISSUE TITLE
WebRTC local IP leakage prevention ineffective (Firefox 51)

### ISSUE THREAD

**Issue by pfofi** [gorhill/uBlock#2337]
### Describe the issue

Since Firefox 51 the privacy option `Prevent WebRTC from leaking local IP addresses` does not prevent websites from reading LAN IP addresses.

### One or more specific URLs where the issue occurs

https://browserleaks.com/webrtc

#### Browserleaks.com
![browserleaks](https://cloud.githubusercontent.com/assets/7479939/22285545/63637bb0-e2ec-11e6-9616-f990ec7aa40b.png)

#### Settings
![settings](https://cloud.githubusercontent.com/assets/7479939/22285564/75580cbe-e2ec-11e6-9180-91510d5ceee2.png)

### Steps for anyone to reproduce the issue

1. Activate `Prevent WebRTC from leaking local IP addresses` in uBlock's settings menu
2. Go to https://browserleaks.com/webrtc
3. Look at the **Local IP Address** row

### Your settings

- Browser/version: Firefox 51.0
- uBlock Origin version: 1.10.4
- OS: Windows 7 SP1  x64

(Also tested with Firefox 54.0a1 and uBlock 1.10.5rc1 - same issue.)

### Possible solution

There is a new preference in Firefox 51 called `media.peerconnection.ice.no_host`. If it is set to `true`, local IPs don't seem to be leaking. https://wiki.mozilla.org/Media/WebRTC/Privacy

**Comment by ialexsilva** [comment]
Same settings where and same issue

**Your settings**

Browser/version: 55.0.2883.87 m (64-bit)
uBlock Origin version: 1.10.4
OS: Windows 10 x64

**Comment by gorhill** [comment]
I don't have FF 51 yet, but I could reproduce with Nightly.

**Comment by gorhill** [comment]
> Browser/version: Google Chrome 55.0.2883.87 m (64-bit)

Unable to reproduce with Chrome. Please open a detailed separate issue if you make the case there is one. Note that this is about "Local IP Address" here.

**Comment by ialexsilva** [comment]
> Note that this is about "Local IP Address" 
I forgot to look at this point 🤣
