### ISSUE TITLE
PayPal Images Blocked

### ISSUE THREAD

**Issue by own3mall** [gorhill/uBlock#2339]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

If you visit a page that embeds PayPal button images, the images are blocked by a default installation of uBlock.  I don't think they should be blocked, as they are not ads.  See `https://sellzum.com` or `http://opengamepanel.org` (look at the footer of the site).  A PayPal image is blocked on both sites using a default install of uBlock.

### One or more specific URLs where the issue occurs
`https://sellzum.com` 
`http://opengamepanel.org`

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
Firefox 51
- uBlock Origin version: 
1.9.16

##### Your filter lists
None
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
None

**Comment by own3mall** [comment]
![2017-01-25 16_27_44-store](https://cloud.githubusercontent.com/assets/11792538/22313843/f4048536-e31b-11e6-8cf7-d84717974227.png)

It doesn't always happen, but it does when loaded over ak1s.ambr.net

**Comment by gorhill** [comment]
Did you use the logger as requested in CONTRIBUTING to rule out a filter list issue?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
