### ISSUE TITLE
Request: Easier Exclusions and rules 

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#234]
Could you add the functionality to right click the list of blocked elements (chrome://ublock0/content/logger-ui.html) on the page to add it to the exceptions/rules? (Or something similar)

**Comment by Snapy** [comment]
It's already implemented in the latest dev version. Everything should be explained on the release page.

**Comment by rayman89** [comment]
Release page?

**Comment by hotdogman** [comment]
I assume @rayman89 is referring to DOM elements/cosmetic filters, not network requests, @Snapy.

**Comment by rayman89** [comment]
I'm referring to both. I installed the dev version but the only thing I noticed is that you can click and a magnifier appears and it shows the menu like if you have clicked on the UBo icon from there i don't know what to do and reading the release page did not clarify anything to me. What I'm asking for is something that lets you easily add exceptions to an element of the page like an script image etc like the functionality ABP has on firefox that you see all the elements of the  page (same as that chrome page) and then you can easily create a block or a exclude rule by right clicking on the line and selecting that option.

**Comment by hotdogman** [comment]
> I installed the dev version but the only thing I noticed is that you can click and a magnifier appears and it shows the menu like if you have clicked on the UBo icon from there i don't know what to do and reading the release page did not clarify anything to me.

You're clicking on the wrong pane. Click on the one that's right after the magnifying glass.

**Comment by rayman89** [comment]
Oh thanks. Why is that disabled for the DOM elements?

**Comment by hotdogman** [comment]
>Why is that disabled/not enabled for the DOM elements?
The functionality isn't implemented. The dev build (https://github.com/gorhill/uBlock/releases/tag/0.9.7.6-dev.1), and this commit (https://github.com/gorhill/uBlock/commit/284b4f62d17a0c3ebf3675a0a67be36396faaf3e) refer to it as "Dynamic URL filtering," the keyword being URL.

**Comment by rayman89** [comment]
Yeah but what i mean is why it was decided not to include the dom elements as well. Are there plans to implement it later?

Also for example I set an exclusion for @@social cause i want the 	##.social_icons filter and the ##.bottom_social to be disabled but that exclusion only works with urls and not elements is there a way to make the exclusion disable that cosmetic filter?

**Comment by hotdogman** [comment]
>Also for example I set an exclusion for @@social cause i want the ##.social_icons filter and the ##.bottom_social to be disabled but that exclusion only works with urls and not elements is there a way to make the exclusion disable that cosmetic filter?

@@social refers to network requests
#@#social refers to DOM/cosmetic elements
https://adblockplus.org/en/filters#elemhide_exceptions

>Are there plans to implement it later?

Maybe, but I don't develop uBlock, so I'm not the person to ask.
https://github.com/gorhill/uBlock/commit/5f1eebb11f3bfc890e13bf8716a149bfa2186338
https://github.com/gorhill/uBlock/commit/06334a190ea9589e9838af0a5b381a55f86e71ab
https://github.com/gorhill/uBlock/commit/018da9c2cb7b6909080daede18a6bd4183f05e90

**Comment by gorhill** [comment]
> Are there plans to implement it later

I envision the logger to be the hub for diagnosing/creating filters and rules.

So I do not want any feature requests to be filed, I work best and most productively when I do my own thinking, and prototype then scrap then further prototype solutions, etc. At my own pace.

I know all the needs and I have a lot of ideas of things to try etc., even way beyond whatever people are asking.

Ok here is the thing: So I will ask people from refraining from filing requests in that area, I will come up with with solutions to real issues.

As emphasized in the contributions guideline:

> Submit bugs/issues only

I am open to address small feature requests related to minor usability issues, but for major feature requests, I prefer to come up with my own stuff.

**Comment by gorhill** [comment]
> i want the ##.social_icons filter and the ##.bottom_social to be disabled

    #@#.social_icons
    #@#.bottom_social

For only a specific site:

    example.com#@#.social_icons
    example.com#@#.bottom_social

**Comment by rayman89** [comment]
Thanks
