### ISSUE TITLE
CSS filters and Kaspersky antivirus

### ISSUE THREAD

**Issue by twim32** [gorhill/uBlock#2343]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Hi! Sorry but i speak english not very well but i'll try to explain clearly what is a problem with uBlock.

I created website http://samorodok.nichost.ru/ and when i enable ads filtres, my website looks like that:

http://joxi.ru/v29LMxqS3pd4ym
http://joxi.ru/EA4Q8RyHwpPXer

I'm sure that i haven't any ads on my website.

It's strange but when i disable Kaspersky Antivirus Internet Protection, all going right. When i disable only ads filters in uBlock, it's going well too! But if uBlock filters and Kaspersky is runing - there is a problem.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
You are creating this problem yourself with overly broad rules such as `* { display: block; }`, which causes `style` tags to become visible.
