### ISSUE TITLE
Please enable RU Adlist filter for ex-USSR/CIS locales.

### ISSUE THREAD

**Issue by yurikoles** [gorhill/uBlock#2344]
Ads on most sites in ex-USSR countries are in RU Adlist. For example I live in Ukraine and there is no separate filter for Ukrainian sites, those sites are in RU Adlist, and same for the most ex-USSR/CIS countries. The only exceptions I see now is Estonia and Lithunia.

ABP already does this. If I install it with Ukrainian locale it enable RU Adlist by default, so most Ukrainian users may gain benefit by using it with default settings out of the box.

**Comment by gorhill** [comment]
I would need a list of language codes for which the list must be enabled (i.e. `uk` = Ukrainian).

**Comment by yurikoles** [comment]
@gorhill for now let's say Belarusian `be, bel` and for Ukrainian `uk, ukr`.

**Comment by yurikoles** [comment]
I have created [thread](https://forums.lanik.us/viewtopic.php?f=102&t=35242)(in Russian language) on official forum to ask what more languages this list supports.

**Comment by gorhill** [comment]
RU AdList will be enabled when installing the extension for the first time, the list won't be automatically selected for existing installation.

**Comment by yurikoles** [comment]
I had successfully verified it on Chrome in Ukrainian.
