### ISSUE TITLE
Request: export into txt file list of only used filters

### ISSUE THREAD

**Issue by deningrad82** [gorhill/uBlock#2346]
Hi,

I would like to export from ublock origin, into a text file, all the filters that are set up excluded the redundant ones that , cleverly, ublock origin exclude. so basically a .txt file that included only the used filters.

example, I set
uBlock filters‎ : 746 used out of 964
Fanboy’s Annoyance List‎ (forums.lanik.us): 1,150 used out of 25,268

I would like to be able to export into a txt files 746+1150= 1896 only those filters, excluding the redundant ones.

Thank you.

**Comment by gorhill** [comment]
Declined.

I can't see any useful use for this, and none was argued: _"I would like"_ is never a valid argument when requesting others to volunteer their free time to work on something.
