### ISSUE TITLE
Locking all images contains 300x250 in name

### ISSUE THREAD

**Issue by Track77** [gorhill/uBlock#2347]
- Browser/version: 
- uBlock Origin version: 4.1

Hi!
uBlock Origin by default is lock all images what contains 300x250 in name. 
This is a bad solution.

**Comment by mapx-** [comment]
it's easylist subscription, not ubo, report false positives directly at easylist forum:
http://forums.lanik.us/

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
FYI - There's no uBO 4.1, it's 1.10.x, so whatever extension you're using is not uBO, remove it.
