### ISSUE TITLE
Portal onet.pl show only News section when uBlock is active

### ISSUE THREAD

**Issue by pkast** [gorhill/uBlock#2348]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

When uBlock is on, when I watch onet.pl, I can read only first section in right column (this is section news. 
![bottom page reached](https://cloud.githubusercontent.com/assets/24697675/22468637/56217ca4-e7c9-11e6-800b-d628682ab2e1.png)

### One or more specific URLs where the issue occurs
www.onet.pl

### Steps for anyone to reproduce the issue
Nothing special. Simply turn on or turn off ublock when I have oen this pege in browser.

### Your settings

Default Settings, 
- Firefox 47.0.1
- uBlock Origin version: 1.10.4

##### Your filter lists
![settings](https://cloud.githubusercontent.com/assets/24697675/22468873/46f663a6-e7ca-11e6-9975-d67140c3b0fb.png)

##### Your custom filters (if any)
[My filters.txt](https://github.com/gorhill/uBlock/files/742206/My.filters.txt)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
