### ISSUE TITLE
Dead after update until browser restart

### ISSUE THREAD

**Issue by BooSN** [gorhill/uBlock#2349]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
After auto-updating to 1.10.7rcX ublock is dead until Firefox 51.0.1 is restarted.
Does not happen with stable.

**Comment by gorhill** [comment]
Does it work fine once you restart?

**Comment by BooSN** [comment]
> Does it work fine once you restart?

Yes.

**Comment by BooSN** [comment]
I can reproduce with http://www.inoreader.com . Maybe the problem comes from the dynamic nature of this page? I'll have a closer look at it next update. 
Thanks.

**Comment by BooSN** [comment]
Can be closed. A page reload is enough it seems. I do not know why i never noticed that before, sorry ;)
