### ISSUE TITLE
Not an issue: just a place to drop images for doc

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#235]

**Comment by gorhill** [comment]
Why using a blocker is very important:

![c](https://cloud.githubusercontent.com/assets/585534/7784786/faefbef2-013f-11e5-95bc-afb5d79fd2c2.png)

As I often say, ads are only the small visible tip of the iceberg of the insidious data mining of people.

**Comment by gwarser** [comment]
Maybe use project page for this? https://help.github.com/articles/creating-project-pages-manually/

**Comment by gorhill** [comment]
> Maybe use project page for this?

I'm too lazy to start yet another side project for now.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/7814025/5bf1df88-038d-11e5-9956-ecd3f56efeb0.png)

**Comment by SMed79** [comment]
Why **41%** of **Arabic** translation is not approved?

![ublock](https://cloud.githubusercontent.com/assets/1873139/7816348/b4e195d8-03c5-11e5-84ce-ce2c0f3b701d.png)

**Comment by CrisBRM** [comment]
@SMed79 I'm pretty sure you need to vote on the translations. Just hit the plus button.

**Comment by gorhill** [comment]
@SMed79 

> Why 41% of Arabic translation is not approved?

A proofreader needs to validate the non-validated entries. There are so many translators now that I can't keep track anymroe of who is a proofreader or not. I just gave you proofreading status in Crowdin.

**Comment by SMed79** [comment]
@gorhill Thank you for the new status!

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/7914528/924b9314-0845-11e5-8012-f67e4b1814cd.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/7916008/3dbe0fe8-084f-11e5-9432-9f72e7463b37.png)

**Comment by gorhill** [comment]
For translators:

This is the UI for creating static filter from the logger:

![1433530980494](https://cloud.githubusercontent.com/assets/585534/8023856/ff87c722-0ceb-11e5-9d26-8c6872e8cc05.jpg)

The goal was to stick as much as possible to natural language to create a filter: So what you issue above was built using a template, which is as follow for the English version:

    {{action}} network requests of {{type}} {{br}}which URL address matches {{url}} {{br}}and which originates from {{origin}},{{br}}{{importance}} there is a matching exception filter.

This templating means you can re-order the parts of the sentence as you wish, to what make the most sense in your language.

For all `{{...}}`, this will be replaced by language-independant data. There is one exception, which is the `{{type}}` placeholder. This one will be replaced by another template, the `loggerStaticFilteringSentencePartType` in `messages.json`: `type “{{type}}”`. In that sub-template, `{{type}}` will be replaced by the language-independant type of the request (`image`, `css`, etc.), and the result will be used in the main sentence to replace `{{type}}`.

I am not a linguist, so I am not sure the current main template fits all languages, hopefully it does. The goal is not to find the perfect sentence -- that would grow code complexity exponentially, but more like to get something which is much more easy to read and interact with than the plain and stern syntax of static filtering (i.e. `||cdn.arstechnica.net/wp-content/themes/arstechnica/assets/images/social-icons.png$image,domain=arstechnica.com`).

**Comment by gorhill** [comment]
It was brought to my attention that `{{origin}}` should also use a sub-template (`from {{origin}}`) just like the `{{type}}` one. So I will fix this and re-upload.

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8024482/4c6f01b0-0d03-11e5-942c-64fe9e2a3686.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8034785/0cb141bc-0db9-11e5-9365-1e45ccc50263.png)

Used in <https://github.com/gorhill/uBlock/wiki/The-network-request-logger>.

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8056364/56fc7a36-0e75-11e5-9d9c-2e45ae56feaf.png)

Used in <https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings>.

**Comment by gorhill** [comment]
For translators:

![c](https://cloud.githubusercontent.com/assets/585534/8083232/150d7332-0f51-11e5-8b9d-fc64f4bee9b0.png)

**Comment by gorhill** [comment]
For translators:

![c](https://cloud.githubusercontent.com/assets/585534/8112038/45e8dcd4-1033-11e5-8e93-1475d02bf6f4.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8120888/63723108-1072-11e5-8401-b0e40c132148.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8129341/5d42c496-10d6-11e5-880f-71bea5943cda.png)

Reverse lookup worker in Nightly: the filter lists need to be kept in live memory while the reverse lookup service is alive.

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8130602/abbac4e2-10e1-11e5-8053-eae23334fa86.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8145767/e2d4eafe-11e3-11e5-9af3-6692531403fa.png)

![a](https://cloud.githubusercontent.com/assets/585534/8145768/e431716a-11e3-11e5-859c-794d37c7c41e.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8148424/02e73ff4-126b-11e5-96e6-867b84722103.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8160013/14466ca0-133a-11e5-8d3c-28169288f35a.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8253895/fe92dd8c-1661-11e5-9134-5c2b9159a57c.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8344622/0ce20cc4-1ab2-11e5-8f46-a0a387c91d63.png)

**Comment by gorhill** [comment]
Some [reality check is in order](https://twitter.com/thenickde/status/614503721590898688).

![a](https://cloud.githubusercontent.com/assets/585534/8421391/cbd59f96-1e9b-11e5-886d-278a00a32792.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/8460038/546b7bc4-1fef-11e5-8e47-069448631bad.png)

**Comment by seanrand** [comment]
![screenshot-20150709t145935](https://cloud.githubusercontent.com/assets/929479/8596010/150e5c1c-264d-11e5-85f1-a4afb0981b55.png)

@gorhill: Maybe not the right place to discuss this, but what does the ```</>``` button do and what does the eye icon indicate? Unless I'm turning blind or stupid, it's not documented on the wiki.

**Comment by CrisBRM** [comment]
@seanrand The </> button is used to access uBlock's DOM inspector.

**Comment by seanrand** [comment]
@CrisBRM Oh, thanks for clearing that up. I only clicked it on the "All" tab, so I was slightly confused as all it did was collapse the logger.

**Comment by gorhill** [comment]
For translators:

Experimental feature: new dynamic filtering type: 3rd-party passive content, for css/images. Allows to un-break rendering of a page when using default-deny for 3rd parties, without enabling 3rd-party active content, i.e. scripts/frames. Using techcrunch.com as an example:

![a](https://cloud.githubusercontent.com/assets/585534/8886632/b0a71908-323b-11e5-837b-fe81672f75d0.png)

![c](https://cloud.githubusercontent.com/assets/585534/8886635/c58af5ba-323b-11e5-9e38-60a5ab8e9368.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8889495/c0694db0-32aa-11e5-9c1d-919e89d80c4b.png)

![a](https://cloud.githubusercontent.com/assets/585534/8889496/c573989c-32aa-11e5-9a40-297ef60a58d0.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/8906091/b7334ddc-3439-11e5-848b-9e8a58eff876.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/9021740/41eac000-3821-11e5-9842-c4c6fea573c3.png)

![c](https://cloud.githubusercontent.com/assets/585534/9021738/3d1e42cc-3821-11e5-82be-f236e5fb8ca3.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/9136321/b78c227e-3ce3-11e5-9949-76e87e7e87e8.png)

Globally blocking 3rd-party frames.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/9589096/0b6cc212-4ffa-11e5-82f1-d276b71fef91.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/9775590/7777b176-571e-11e5-9647-12711e53df21.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/9832014/bfb1b8f0-593b-11e5-8a27-fba472a5529a.png)
