### ISSUE TITLE
Local "Allow" (green) doesn't seem to override 3rd Party static filter lists, but Wiki says it should

### ISSUE THREAD

**Issue by Aelius51** [gorhill/uBlock#2350]
### Describe the issue

Speedtest.net's [result page](http://www.speedtest.net/my-result/6017589866) doesn't work with Fanboy's Social list. The page appears as in [this screenshot](http://i.imgur.com/ebO7fZU.png). The culprit is as follows:

    ##.share-body

The wiki [says](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence) that dynamic filter **Allowing** (i.e. set to green, not grey) overrides static filters. However, [when I Allow every domain on that speedtest page](http://i.imgur.com/e3DBX8v.png) and refresh, it still doesn't work.

Yes, I know I can manually add an exception in the *My Filters* section, but that's not the point. **Shouldn't Allow be overriding static filtering? Why isn't it?**

I'm sure this is just a misunderstanding of something on my part.

Thanks!

### One or more specific URLs where the issue occurs

See above

### Screenshot in which the issue can be seen

See above

### Steps for anyone to reproduce the issue

See above

### Your settings

http://i.imgur.com/nTLJ6hj.png

- Browser/version: Firefox 51.0.1 (64-bit)
- uBlock Origin version: 1.10.6

##### Your filter lists

Default filter lists + Fanboy Ultimate + Adblock Warning Removal List + Anti-Adblock Killer + all in the Malware section

**Comment by gorhill** [comment]
Creating  *allow* rules does not disable cosmetic filtering. The cosmetic filtering switch says there are 8 elements hidden on the page. Just toggle it to disable cosmetic filtering. Also, you did not create an _allow_ rule for all cells, the popup says there were still 3 network requests blocked -- creating allow rules and reloading a page will likely causes more requests from other hostnames to be made.

In any case, `speedtest.net` works fine with default filter lists.

**Comment by Aelius51** [comment]
I never realized that the cosmetic filtering button had the opposite functionality of the font button. With the font button, the red **X** means *"Fonts are blocked"* but with the cosmetic filtering button the red **"X"** means *"Cosmetic elements are unblocked"*.

In my opinion, the meaning of the red **X** should be consistent across those buttons.

Thanks for letting me know that the *Allow* rule does not disable cosmetic filtering, however I meticulously combed through the Wiki trying to find where it says this anywhere. Unless I missed it, I suggest you clarify in the Wiki that Allow does **not** override static filtering in the case of elements.

**Comment by gorhill** [comment]
> with the cosmetic filtering button the red "X" means "Cosmetic elements are unblocked".

It means cosmetic **filtering** is disabled. Nowhere [the doc](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) says "cosmetic elements", it says "cosmetic filtering".
