### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by jugi1** [gorhill/uBlock#2351]
I noticed much higher memory usage recently (over 3mb).
I have standard settings, and just a few personal filter lines.
(I did RESET and reastarted)

https://postimg.org/gallery/110bb7lwi

- Browser/version: Cyberfox64  (51.0.1) 
- uBlock Origin version:  1.10.6

filter lists:
https://postimg.org/gallery/110bb7lwi

**Comment by gorhill** [comment]
Don't use about:addons-memory to report memory issue, it's flawed, it does not properly report memory usage. uBO consumes more than just 3MB of memory. Analyzing `about:memory` is the correct way.

Also, making the case there is an issue requires much more than just what you provided. "Much higher" than _what_? Than before? Then provide evidence of what it was before (and not through the flawed about:addons-memory), and make the case that there is something wrong after ruling out all that is normal/expected.

**Comment by jugi1** [comment]
Thank you for reply.

I just wanted to tell you that about changes I noticed,
as I try to keep browser memory as low as possible, and uBO is best so far.
I check memory every time I add some new extension.
uBO Using 17.78 MB (07.46%) -- top(https://github.com/gorhill/uBlock/issues/2351, id=11)

Thank you for great extension and advice.

**Comment by gorhill** [comment]
`about:memory` is the right way to analyze memory. These are the entries I have been able to relate to uBO after a restart of the browser:

![a](https://cloud.githubusercontent.com/assets/585534/22594204/11d001be-e9f0-11e6-8bab-45f9980c13e1.png)

The _about:addons-memory_ extension only reports the bottom entry, which is wrong.
