### ISSUE TITLE
Number of blocked requests absent from menu in Firefox Aurora for Android

### ISSUE THREAD

**Issue by CaptainFrosty** [gorhill/uBlock#2352]
The menu used to show it, now it doesn't. 

# One or more specific URLs where the issue occurs
All URLs affected

 
![2017-02-03-09-26-26](https://cloud.githubusercontent.com/assets/8523498/22595181/4c2b17b4-e9f4-11e6-9edf-45d84b5e0ac7.png)

### Your settings:
Standard settings

Browser version: Firefox Aurora 53.0 alpha 2 build 2017-01-30
- uBlock Origin version: 1.10.6

##### Your filter lists
Standard default filters

Custom filters (if any)
None

**Comment by gorhill** [comment]
I am not in position to test Firefox Aurora for Android.

> All URLs affected

As requested and emphasized in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> - A clear list of steps to reproduce the problem
>     - **ALWAYS INCLUDE A SPECIFIC URL WHERE THE ISSUE OCCURS**, *even* if "it happens everywhere".

Why did you disregard this?

**Comment by gorhill** [comment]
Closing, ad uBO is not now a WebExtensions extension -- and now uBO uses the `browser.browserAction.seTitle` API to report the number of blocked network requests. However this API works properly with FF57 only: <https://bugzilla.mozilla.org/show_bug.cgi?id=1392322>.
