### ISSUE TITLE
Spotify Web Player Ads Playing

### ISSUE THREAD

**Issue by ryanbuening** [gorhill/uBlock#2355]
**### Describe the issue**

Spotify recently updated the web player and ads appear to be playing now. Also reported here (https://www.reddit.com/r/uBlockOrigin/comments/5rq1rc/spotify_ads_now_getting_through_ublock/) and here (https://www.reddit.com/r/uBlockOrigin/comments/5p0zsa/spotify_troubles/).

**### One or more specific URLs where the issue occurs**

https://open.spotify.com

### Steps for anyone to reproduce the issue

1. Open https://open.spotify.com
2. Play several songs.

**### Your settings**

- Browser/version: Chrome 56.0.2924.87 (64-bit)
- uBlock Origin version: 1.10.4

**##### Your filter lists**

Defaults

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
