### ISSUE TITLE
Filter for dynamically added class is not logged

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#2356]
I want to hide these new Youtube annotations that appear at end of movie. UBO selector proposes `##.ytp-ce-element-show.ytp-ce-size-640.ytp-ce-bottom-right-quad.ytp-ce-video.ytp-ce-element`, looks to specific to me, so I cut it to `##.ytp-ce-element-show`. Works fine, but this filter did not appear in logger. Probably because is added dynamically when element is shown.

Where it appears: 

https://youtu.be/s5RM81_6vC8?t=265 (annotation is show at 4:27)

![image5](https://cloud.githubusercontent.com/assets/886325/22627025/52852be6-ebba-11e6-9a48-b5b56bc4cad3.jpg)
![image6](https://cloud.githubusercontent.com/assets/886325/22627027/578b6d62-ebba-11e6-923c-072113b315bd.jpg)

 Filter used 

    youtube.com##.ytp-ce-element-show

Not shown in logger

![image7](https://cloud.githubusercontent.com/assets/886325/22627033/7754f0c8-ebba-11e6-9a00-345c245cb9b7.jpg)

Another filter is working fine

    youtube.com##.ytp-ce-element

![image8](https://cloud.githubusercontent.com/assets/886325/22627039/c00ae462-ebba-11e6-9de4-d9b2dd7caf1a.jpg)

Firefox 53, UBO 1.10.7rc4

**Comment by gorhill** [comment]
If you reload the page at a point where the overlay is visible, it shows in the logger: <https://www.youtube.com/watch?v=s5RM81_6vC8&feature=youtu.be&t=270>.

The issue is that with specific cosmetic filters, uBO will find report only those which are found to match an element on the page, and at `t=265` there is no match for that filter, while there is one at `t=270`.

Not sure at this point how I should fix this, not introducing overhead for when the logger is not in use has precedence over this glitch. Will need to think more about what can be done.

**Comment by gwarser** [comment]
Is this the same bug?

Here http://www.blikmobile.pl/pytania-o-blika/ when you click on FAQ question, answers are unrolled and then hidden by `~kfcdostawa.pl,~allegro.pl,pl##.in` from [Adblock polskie reguly social](https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt)

**Comment by gwarser** [comment]
There may be small glitch (stopped when I try to find STR). Generic + specific filter may be reported twice and log shows both as generic or specific in details dialog. May depend on the order filters are added.

```
youtube.com##.ytp-ce-element-show
##.ytp-ce-element-show
```

https://youtu.be/lavy7qZ1aoo?t=195
https://youtu.be/lavy7qZ1aoo?t=180

**Comment by gorhill** [comment]
I can reproduce when I restart uBO, on the first load of the Youtube page. Will fix.

**Comment by gorhill** [comment]
> Generic + specific filter may be reported twice

Just for the record, this issue is not a regression, it existed also before the changes here.

> log shows both as generic or specific in details dialog

By design: for efficiency purpose, the logger will report at most one hit per list.
