### ISSUE TITLE
Advanced wildcard in attributes filters appear to be not working

### ISSUE THREAD

**Issue by JonasT** [gorhill/uBlock#2357]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
According to https://adblockplus.org/forum/viewtopic.php?t=697 this should be a working filter:
```
#div(id*=promoted-tweet)
#div(class*=promoted-tweet)
```
(which removes `<div>` elements where the id or class attribute contains "promoted-tweet")

However, when testing it, it doesn't seem to be working.

Also, https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions doesn't offer any obvious alternative on how to do this rule if not this way.

### One or more specific URLs where the issue occurs
https://twitter.com/

### Steps for anyone to reproduce the issue

1. Try above filter for promotional tweets (might require to be logged into twitter to see promotional tweets, I'm not sure if a tweet timeline and/or promotional tweets in it can be seen as non-logged in users)

### Your settings

Since I don't know how to export settings, I cannot easily list them here. However, I would gladly do so if someone could tell me how.

- Browser/version: Firefox 54.0a1 Nightly (64bit)
- uBlock Origin version: 1.10.16

##### Your filter lists

Default lists

##### Your custom filters (if any)

Edit: the first filter I had written above was incorrect, but the corrected one doesn't appear to work either

**Comment by mapx-** [comment]
try
```
#div[id*=promoted-tweet]
#div[class*=promoted-tweet]
```
from:
https://adblockplus.org/en/filters#elemhide_simplified
`Adblock Plus supports simplified element hiding syntax (e.g. #div(id=foo)) for backwards compatibility only. Using this syntax is discouraged, usual CSS selectors are preferred. Support for this syntax might be removed at some point.`

**Comment by JonasT** [comment]
I tried this filter:
`#div[id*=promoted-tweet]`
and "Preview" still doesn't show it working, sadly..

**Comment by mapx-** [comment]
sorry, try this 1 (corrected above)
##div[id*=promoted-tweet]

**Comment by JonasT** [comment]
Oh neat, that one actually works :-) I guess this ticket is invalid then, sorry about that.

Also, thanks a lot for the help!

**Comment by gorhill** [comment]
> Also, `https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions` doesn't offer any obvious alternative on how to do this rule if not this way.

Why would you expect a link to an unrelated project to be of any help?

The link in uBO's dashboard is <https://github.com/gorhill/uBlock/wiki/Static-filter-syntax>, and that wiki page further links to <https://adblockplus.org/en/filter-cheatsheet>, where it is explained [how cosmetic filtering filters works](https://adblockplus.org/en/filter-cheatsheet#elementhiding).
