### ISSUE TITLE
uBlock filters‎ triggers popup for sidereel.com

### ISSUE THREAD

**Issue by jaysparrowof75** [gorhill/uBlock#2358]
One of these uBlock filters‎ triggers popup at sidereel.com
that identifies I'm using an adblocker.

 My filters‎ : 0 used out of 14
 uBlock filters‎ : 0 used out of 989purge cache
 uBlock filters – Badware risks‎  (github.com): 0 used out of 7
 uBlock filters – Privacy‎ : 0 used out of 53purge cache
 uBlock filters – Unbreak‎ : 0 used out of 124purge cache

http://www.sidereel.com/

![1](https://cloud.githubusercontent.com/assets/25583094/22645744/23d33e54-ec2e-11e6-8d17-bb073bae48e6.PNG)

Update all filters
Activate all filters listed 
then go to .sidereel.com/

When all deactivated the pop up doesn't appear.
I can't identify which one does it. 

Standard settings

- Browser/version: Google Chrome Version 56.0.2924.87 m (64-bit)
- uBlock Origin version: uBlock Origin v1.10.4

My filter lists
! 2/6/2017, 4:03:11 AM http://www.sidereel.com/
||cdn-gce.sidereel.com/assets/sprites/sidereel-af0130a67ebc15a4becc2f22a485d8c8.png$image

! 2/6/2017, 4:03:41 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-facebook > .fa-facebook.fa

! 2/6/2017, 4:03:53 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-facebook

! 2/6/2017, 4:04:03 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-twitter

! 2/6/2017, 4:04:16 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-youtube

! 2/6/2017, 4:04:26 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-google

! 2/6/2017, 4:04:37 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-instagram

! 2/6/2017, 4:04:46 AM http://www.sidereel.com/
www.sidereel.com##.show-for-large-up > .social-icons > .connect-pinterest

! 2/6/2017, 4:04:55 AM http://www.sidereel.com/
||cdn-gce.sidereel.com/assets/sprites/sidereel-af0130a67ebc15a4becc2f22a485d8c8.png$image

! 2/6/2017, 4:06:23 AM http://www.sidereel.com/
||cdn-gce.sidereel.com/assets/sprites/sidereel-af0130a67ebc15a4becc2f22a485d8c8.png$image

! 2/6/2017, 5:27:02 AM http://www.sidereel.com/tv-shows/love-thy-neighbor/episodes
www.sidereel.com##d1486380410480 > div

! 2/6/2017, 5:27:11 AM http://www.sidereel.com/tv-shows/love-thy-neighbor/episodes
www.sidereel.com##d1486380410480

! 2/6/2017, 5:27:29 AM http://www.sidereel.com/tv-shows/love-thy-neighbor/episodes
www.sidereel.com##d1486380440942

! 2/6/2017, 5:27:41 AM http://www.sidereel.com/tv-shows/love-thy-neighbor/episodes
www.sidereel.com##d1486380459534

My custom filters (if any)
NONE

**Comment by mapx-** [comment]
add
```
sidereel.com#@#script:inject(setTimeout-defuser.js, S(), 1498)
@@||google-analytics.com/analytics.js$script,domain=sidereel.com
```

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by jaysparrowof75** [comment]
How the hell is this invalid?, It is a problem 
Is this what is triggering the popup?

> 
> sidereel.com#@#script:inject(setTimeout-defuser.js, S(), 1498)
> @@||google-analytics.com/analytics.js$script,domain=sidereel.com
> 
DO I need to delete this?

**Comment by gorhill** [comment]
Filter list issues must not be filed here -- as clearly explained in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Just force an update of _uBlock filters_, it's fixed in the filter list.
