### ISSUE TITLE
SharedWorker [sibnet.ru]

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBlock#2360]
uBO 1.11.0
Google Chrome 56.0.2924.76 (64-bit)
uBlock Filters
EasyList
RU AdList

1. Disable hiding filters:
#@#.da_adp_teaser
#@#.directadvert-block
sibnet.ru#@##right_place_wrapper
2. Open `http://www.sibnet.ru/` and wait 2-3 seconds
3. Ads appears at the top of the page.

**Comment by gorhill** [comment]
Ideally we should have a new filter such as `webworker` to accurately filter workers. Currently using the existing `blob:$script` ones to decide whether a CSP to prevent `blob:`-based workers should be forbidden.

**Comment by dimisa-RUAdList** [comment]
Yes, that would be correct.

**Comment by ryanbr** [comment]
blob: can also be an image file, so strictly not just $script

**Comment by dimisa-RUAdList** [comment]
Ok:
https://hg.adblockplus.org/ruadlist/rev/067aaea25c20

**Comment by gorhill** [comment]
> blob: can also be an image file, so strictly not just $script

Sure, but since there is no such thing yet as `webworker` type, using `|blob:$script` specifically to inject a CSP to forbid workers on a page is better, otherwise now I will have to assume that anything starting with `|blob:` should result in a CSP being injected, that is not a safe assumption.

**Comment by dimisa-RUAdList** [comment]
While I will not be in a hurry:
https://hg.adblockplus.org/ruadlist/rev/94b4326fdccc

**Comment by ryanbr** [comment]
> While I will not be in a hurry:

Keep in mind, it's safe without the $script suffix, in Easylist we've made blob: a generic filter. I haven't see a false positive where a site will use 2 types of blobs (one for an Advert, and for a non-advert).   

If I recall the abuse of the blob: was changed from |blob:$script,domain=.. to  |blob:$domain= was due to jpost.

**Comment by dimisa-RUAdList** [comment]
> @ryanbr Keep in mind, it's safe without the $script suffix, in Easylist we've made blob: a generic filter. I haven't see a false positive where a site will use 2 types of blobs (one for an Advert, and for a non-advert).

Unfortunately, it does not work everywhere: http://www.anilibria.tv/release/bernard-jou-iwaku.html
When blocking blobs disrupted video player.  I sometimes encounter similar in Firefox.
> @gorhill fix #2360

Why was removed uBlock Origin 1.11.1b?

**Comment by ryanbr** [comment]
Is there is some legit cases where allowing blob: is fine, anilibria.tv is such one

**Comment by gorhill** [comment]
> Why was removed uBlock Origin 1.11.1b?

Because it wasn't working anymore when `script` was removed from the `|blob:` filter, my implementation was testing for precisely `script` type. I re-implemented to work with either `script` or no specific type, I haven't committed yet.

**Comment by dimisa-RUAdList** [comment]
Clear. But I returned the "script" suffix in RU AdList: https://hg.adblockplus.org/ruadlist/rev/94b4326fdccc
And yes, - blockage in 1.11.1b worked great.
