### ISSUE TITLE
easylist rules not being processed properly

### ISSUE THREAD

**Issue by EduardoSolanas** [gorhill/uBlock#2361]
I am working for a marketing company that has its own internal UI platform, calling via AJAX internal API microservices,  but some calls are being block by the easylist rule that uBlock is consuming.

The ajax call url blocked is the following:

https://cci.test.cciooh.io/accountapi/customers/c101/advertisers/a001/brands

and the reason given in the logs is:
/advertisers/*$domain=~datalift360.com|~home.tapjoy.com|~panel.rightflow.com|~propelmedia.com found in:
EasyList

I am not sure why a custom domain is being blocked if the domain is not between the given ones datalift360.com|~home.tapjoy.com|~panel.rightflow.com|~propelmedia.com

it seems more like a bug to me, it shouldn't block any urls that just contains /advertisers/ only the ones that have one of the given domains ?

Thanks.

**Comment by mapx-** [comment]
~ means exception, so the request containing /advertisers/* on your domain will be blocked

**Comment by gorhill** [comment]
The tilde `~` before a domain name means "do not block on this domain". If you have a case of false positive, report to EasyList maintainers so that they may add your domain to the list of excluded domains.
