### ISSUE TITLE
[Bug?] Custom filters lists and custom filters lists with exclamation mark as first sign aren't shown in textbox area on “3rd-party” tab.

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#2363]
### Describe the issue
The custom filters list, both with normal URL and URL with exclamation mark as first sign disappears from textbox area in “3rd-party” tab of uBO settings after saving changes.

### One or more specific URLs where the issue occurs
uBO settings of 3rd-party filters.

### Screenshot in which the issue can be seen
If they are needed, I'll post them here. Just request it.

### Steps for anyone to reproduce the issue
1. Go to “3rd-party” tab in uBO settings.
2. In textbox area on the bottom part of the tab add at least 2 **correct** filters list: first one with normal URL (it can be also from your computer), the second one with exclamation mark [ ! ] as first sign (can be separated by space bar) or vice versa (the order isn't so much important).
3. Save settings.
4. The entered URLs will disappear from this textbox area.

### Your settings
I think my settings of uBO doesn't matter in this case.

- Browser/version: Google Chrome 56.0.2924.87 (64-bit) on Windows 10 Pro 64-bit with Anniversary Update
- uBlock Origin version: The current newest one – 1.11.0

#### Your filter lists
I think this doesn't matter.

#### Your custom filters (if any)
I think this also doesn't matter.

**Comment by gwarser** [comment]
New design. Check release notes.

**Comment by Piter432** [comment]
@gwarser: But I know about new design, lel XDDDDDDDD The question is this really a bug or not.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/2332#issuecomment-274935354

**Comment by Piter432** [comment]
@gwarser: Aha, nice “feature”, just like replacing the strict blocking button in pop-up panel with media elements blocking button in pop-up panel. However, with the second one I could leave and use uBO.

I think I will move to AdGuard in the future...

**Comment by uBlock-user** [comment]
> The entered URLs will disappear from this textbox area.

Yes, they disappear as they're added and the list if imported, new design. Nothing's wrong with that, it's doing the job.
