### ISSUE TITLE
[feature-request] Possible to see which filters did not take affect

### ISSUE THREAD

**Issue by Quix0r** [gorhill/uBlock#2364]
I would like to see which filters did not take affect (because of an other block list) in details. The current (release v1.10.6 as found over addons) only shows "x used of y" but does not show which are not used. It would be helpful to see which filters are double (because of more than one blocklist is loaded) to optimize own blocklist.

**Comment by gwarser** [comment]
If you want to compile you own list, this can help you https://arestwo.org/famlam/redundantRuleChecker.html

**Comment by Quix0r** [comment]
Why has this been declined? The remote tool doesn't really help. It may no longer exist in the future.

**Comment by gorhill** [comment]
Because it's a lot of work, requiring to throw in code which would need to be maintained, for a very specific/niche feature request not really of interest by the majority of users.
