### ISSUE TITLE
Blank popup and no access to dashboard/logger

### ISSUE THREAD

**Issue by usefulz** [gorhill/uBlock#2366]
### Describe the issue

Toolbar popup is blank, Open Dashboard/Logger from Addons menu doesn't work

### One or more specific URLs where the issue occurs

ANY
https://www.google.com/

### Screenshot in which the issue can be seen

http://i.imgur.com/FpbVq9S.png

### Steps for anyone to reproduce the issue

1) Open Firefox
2) Go to any website
3) Click on the uBlock icon in the toolbar, it will show # of blocks but not any controls
4) Go to Add-ons and hit "Show Dashboard" and "Show Logger", nothing happens, no errors in console either

### Your settings

- Browser/version: Firefox 51.0.1 (64-bit) / Ubuntu 16.04.1 LTS
- uBlock Origin version: 1.10.6

Addons:

http://i.imgur.com/iYQSvch.png

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

Can't see as "Open Logger" and "Open Dashboard" do not work

**Comment by gorhill** [comment]
Try with only uBlock Origin.

**Comment by usefulz** [comment]
No user styles, will test with all other addons disabled later today.

**Comment by gorhill** [comment]
That is such a specific issue (no other report), and I can't reproduce. This suggests something specific in your environment is causing this, and only you can investigate.

**Comment by Atavic** [comment]
Try disabling Ubuntu Firefox Modifications.

**Comment by usefulz** [comment]
@Atavic that worked perfectly, thanks!
