### ISSUE TITLE
Unable to install in Seamonkey

### ISSUE THREAD

**Issue by gulkily** [gorhill/uBlock#2368]
### Describe the issue

I am unable to install uBlock Origin on Seamonkey 2.46.

### One or more specific URLs where the issue occurs

https://addons.mozilla.org/En-us/seamonkey/addon/ublock-origin/

### Screenshot in which the issue can be seen

![seamonkey ublock origin2017-02-09_2138](https://cloud.githubusercontent.com/assets/1530699/22812034/77b16f16-ef10-11e6-99ea-2e46577996a0.png)

### Steps for anyone to reproduce the issue

1. Install the current stable build of Seamonkey browser (2.46)
2. Search Google for "ublock origin seamonkey" and click through to the following page: https://addons.mozilla.org/En-us/seamonkey/addon/ublock-origin/
3. Click the "Add to Seamonkey" button.

Expected: "Add to Seamonkey" button is enabled (step 2). Add-on can be installed (step 3).

Actual: "Add to Seamonkey" button is disabled (step 2). Add-on cannot be installed (step 3).

The following text also appears on the page: 

>This add-on is not compatible with your version of SeaMonkey because of the following:

>    You need to be using Firefox 10.0 or higher.

### Your settings

- Browser/version: Mozilla Seamonkey 2.46 (build 20161213201111)
- uBlock Origin version: 1.10.6

##### Your filter lists

N/A (did not get that far)

##### Your custom filters (if any)

N/A

**Comment by gorhill** [comment]
I set the max version to `*` on AMO, see if this works now.

**Comment by gulkily** [comment]
It worked! Thank you very much.

**Comment by gorhill** [comment]
Fixed in 1.11.b0 with 1d705485e9c855b7c113f6cd7114dcd8e0abeeac.

**Comment by RayLennox** [comment]
Having problems installing it on Seamonkey 2.48. AMO says the addon is corrupt:

https://snag.gy/SEb56r.jpg
