### ISSUE TITLE
Firefox mobile: Can't save site preferences in advanced mode

### ISSUE THREAD

**Issue by bjoli** [gorhill/uBlock#2369]
### Describe the issue

I use ublock origin in advanced mode on firefox mobile. Most of the things work as expected. Changing the settings for a site, say by allowing or disallowing javascript, works fine. The problem is I can't "click" the padlock to save the settings. No matter how I do, I will activate whatever button that is under it. I have tried zooming in and moving the button to a place where there are no elements behind it, but it still won't work. 

### One or more specific URLs where the issue occurs
In the chrome://ublockO/content/popup.html tab that opens when I select Ulock Origin([number]) in the firefox mobile menu.

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

This is me accidentally allowing everything everywhere when trying to click the padlock.

![screenshot_20170210-101456](https://cloud.githubusercontent.com/assets/9133739/22821130/0e4ef38a-ef7a-11e6-956e-e97867802ef9.png)

### Steps for anyone to reproduce the issue

1. Go to a page
2. click the menu button and open the ublock origin control panel
3. make a change in the advanced panel (this requires "I am an advanced user" to be checked")
4. Try to click the padlock.

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

I have the following non-standard settings:
  - Advanced user
  - Block external fonts
- Browser/version: Firefox mobile 50.1.0
- uBlock Origin version: 1.10.6

##### Your filter lists
Default uBlock filters + EasyList + Easyprivacy + Malware Doman List + Malware Domains + Peter Lowe's ad and tracking server list + SWE: Fanboy's swedish

I think I have only enabled SWE: Fanboy's and EasyPrivacy myself.

##### Your custom filters (if any)
None.

**Comment by gorhill** [comment]
Probably fixed in 1.11.0: <https://github.com/gorhill/uBlock/issues/2274>.

**Comment by bjoli** [comment]
Fixed. Still hard to hit, but it works.
