### ISSUE TITLE
Clicking options from context menu opens chrome://extensions

### ISSUE THREAD

**Issue by spaghetti2514** [gorhill/uBlock#237]
Right clicking the uBlock icon on the navbar and then clicking "options" first opens a new tab pointed to "chrome://extensions" and then immediately after opens another new tab containing the actual uBlock dashboard and switches to it. The chrome://extensions tab is just left open.

At first I thought this was a Chrome issue, but uMatrix works as expected doing the same thing.

**Comment by gorhill** [comment]
It is a Chrome issue:

[Migrating from old options pages](https://developer.chrome.com/extensions/optionsV2):

>  Chrome will continue to support the `options_page` manifest field, but new and existing extensions **should use the `options_ui`** to ensure that their options pages are displayed as intended. [...] In a future version of Chrome, any extension which specifies `options_page` will change to match the `options_ui` behavior - most importantly, they will always be embedded in `chrome://extensions` - so **migrate as soon as possible**.

The issue is actually with uMatrix, I need to convert it to the new options behavior.

**Comment by spaghetti2514** [comment]
![screen shot 2015-05-23 at 9 52 57 pm](https://cloud.githubusercontent.com/assets/1966861/7786445/4f4b1bd0-0196-11e5-908b-fff293b81a5f.png)
I just added this (set to true) to the manifest, and it fixed the issue of the unwanted extension page opening. Wouldn't it be good to add this at least until Chrome removes the option or uBlock's options UI is reworked?

**Comment by gorhill** [comment]
> uBlock's options UI is reworked

It's not going to be reworked, there is no way uBlock settings fit in the limited space available in that new options UI -- it was tried before settling to the current way.

**Comment by spaghetti2514** [comment]
>It's not going to be reworked

The way I'm understanding it, they aren't really giving you a choice
![screen shot 2015-05-24 at 12 23 26 am](https://cloud.githubusercontent.com/assets/1966861/7786824/39e136b6-01ab-11e5-872e-f83c6bee1265.png)
I guess this could possibly be taken as "extensions using only options_page will be embedded" but I doubt it. Seems like they're going to force all extensions into the embedded page format.

And regardless, what about setting open_in_tab in the mean time?

**Comment by lewisje** [comment]
I noticed this issue almost from the start, and I noticed that the Extensions page is not opened if, instead, you open the regular popup UI and click the dark grey box with "uBlock" in it; it's such an obvious issue that I just assumed that the reason gorhill *didn't* fix it is that it *couldn't* be fixed.

**Comment by raysegantii** [comment]
The thing I don't understand is other extensions like Pocket or LastPass also have a large settings page but they don't open up the extra Chrome tab as uBlock. Is there any new alternative?

**Comment by spaghetti2514** [comment]
@raysegantii Any extension that doesn't specify **options_ui** in its manifest will continue using the expected behavior, at least until support for it is removed.
10 months later though, chrome still supports opening option pages directly in new tabs when options_ui isn't set, as it isn't in most extensions containing entire-page-option-menus (including uMatrix still).

**Comment by Hrxn** [comment]
Well, according to their doc, `options_page` will be deprecated and the behaviour of `open_in_tab` will be changed.
```
open_in_tab (boolean) - optional

This is only useful to delay the 
inevitable deprecation of the old options UI! 
It will be removed soon, so try not to use it. 
It will break.
```

Options pages should be opened with `chrome.runtime.openOptionsPage()`, maybe they will extend that to make some customization possible.

Setting the size should be possible:


>Sizing
The embedded dialogue should automatically determine its own size based on the options page content. However, the dialogue may not find a good size for some types of options pages. This problem is most common for options pages that adjust their size based on window size.
If this is an issue, provide fixed minimum dimensions for the options page to ensure that the dialogue will find an appropriate size

Maybe this helps somehow?

**Comment by spaghetti2514** [comment]
>according to their doc, `options_page` will be deprecated and the behaviour of `open_in_tab` will be changed

As far as I'm aware, any notion of `open_in_tab` has already been removed from chrome, and it's no longer a recognized option in a manifest.
As for `options_page`, it's true that its behavior is supposed to change *eventually*, but it's been a very long time and we've seen no change in behavior for it. Virtually all other extensions are continuing to use it in the old way (aka not using it at all), and are behaving properly. Frankly, when the behavior is finally changed in chrome, I expect that extensions that don't specify `options_ui` will have their options page jammed into the extension list regardless of manifest, or opened in a new tab brokenly as uBlock's is already, so there doesn't seem to be any reason to specify `options_ui` right now or ever unless there's a properly embeddable options UI in the extension (which there isn't and apparently never will be).

**Comment by mikhaelkh** [comment]
Still supporting `"open_in_tab": true`, for example in [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag) and `"options_page"` in uMatrix. If you turn on flag `#enable-embedded-extension-options` which is supposed to be on eventually Violentmonkey still opens in new tab without opening `chrome://extensions/` while uMatrix breaks.

**Comment by mikhaelkh** [comment]
It's weird that despite uBlock support Chrome 38+ (#2612) while new `options_ui` wasn't supported until Chrome 40 so manifest still has `options_page` for compatibility but there's no `open_in_tab` because it will break in the future.
