### ISSUE TITLE
uBlock Origin crashes Firefox Nightly every time on startup if you have Many tabs

### ISSUE THREAD

**Issue by Zuldra** [gorhill/uBlock#2371]
uBlock Origin has severe problems for the past couple months.
****
Steps to reproduce:

1) Install Firefox E10s / Nightly and configure it for 8 processes.
2) AFTER YOU HAVE A LOT OF TABS, uBlock Origin begins crashing the session upon every startup.

Currently I have 500 tabs. That means uBlock Origin will crash the session every time at startup.

**If you don't have 500 tabs, then uBlock Origin will appear to run normally and will not crash at startup.**

## The more tabs you have, the higher the chance that uBlock Origin will be unable to handle a startup.

There's no possible chance I am ever going to use less than 500 tabs (I have 4 displays, and a special computer just for this purpose) so therefore uBlock Origin is a failure for me and I've had to move elsewhere.

**I have this same problem on two different computers. AND my friend who uses many tabs has the same problem. Basically, uBlock Origin has been eliminated for power users.**

3) AFTER FIREFOX FINISHES STARTING UP, you **can** enable uBlock Origin, and it works properly.

**Comment by Atavic** [comment]
Can't you save the session so you can reload it after firefox has been started and ublock has been enabled?

**Comment by Zuldra** [comment]
Atavic, I am really disappointed by your response...

Translation: "Can't we just allow uBlock to keep on crashing, and force you to do things manually every time you restart?"

You're basically trying to shutdown my legitimate bug report and ask me to do something which is ridiculous.

And by the way: **NO, YOU CAN'T DO THAT, WHEN YOU RESTORE A SESSION WITH MANY TABS, IT CRASHES**

The only thing that works is (3)

If your only response is to suggest that we keep allowing uBlock Origin to crash, then please do not attempt to "help" me.  I find your response offensive, it completely ignores my desire to fix the problem.

**Comment by gorhill** [comment]
What are the errors reported at the browser console?

**Comment by gorhill** [comment]
Also more details please about uBO's version, and which filter lists are selected.

**Comment by Atavic** [comment]
@Zuldra Isn't option (3.) working there? 

Many filter lists won't help your power user sessions.

**Comment by gorhill** [comment]
@Atavic I want to find the source of the issue.

**Comment by gorhill** [comment]
Another thing: did you submit a crash report on [bugzilla](https://bugzilla.mozilla.org/)? A crash is something which should also be investigated by Firefox devs, as uBO is essentially HTML/CSS/JS and should not cause a browser to crash.

**Comment by Atavic** [comment]
It has 500 tabs and should list the OS, Browser version, Addons and the filter lists used.

**Comment by Zuldra** [comment]
> What are the errors reported at the browser console?

How do I see the errors? Firefox is crashing.

> Also more details please about uBO's version, and which filter lists are selected.

Browser: Firefox Nightly, with multiprocess enabled.
uBlock Origin version: 1.10.6
Filter lists: The default ones that come selected with uBO, no alterations made. I have purged and updated.

> Also, are you tabs lazy-loaded?

Yes they are lazy-loaded. Firefox no longer provides an option to disable lazy-loaded tabs. It has been removed from options.

**Comment by gorhill** [comment]
As said, best is to submit a crash report to Firefox devs. The most likely explanation I can think of is that uBO may make a latent issue with Nightly more likely to manifest itself. Hard crashes should always be reported to the devs, who have the tools to investigate them.

**Comment by gitarra** [comment]
@Zuldra Can you share a link to the bug here once you have filed it?

**Comment by gorhill** [comment]
Closing, issue abandoned by OP, was never able to reproduce.
