### ISSUE TITLE
I can't use 3rd party filters

### ISSUE THREAD

**Issue by wasd--** [gorhill/uBlock#2372]
uBlock don't use my third party filters I add, this one for example

https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

I enabled it, wipe all caches and update them again but always **0 used**

![captura](https://cloud.githubusercontent.com/assets/7848838/22861228/e838e4bc-f113-11e6-87f0-509a82702b2d.PNG)

Steps for anyone to reproduce the issue

1. Just subscribe to it and enable it. It shows 0 used.

- Browser/version: Firefox 51.0.1 x64
- uBlock Origin version: 1.10.6

**Comment by toshiya44** [comment]
That list is already built in.

![image](https://cloud.githubusercontent.com/assets/20046789/22861395/e9576afe-f0e5-11e6-846d-b4c369db752f.png)

**Comment by wasd--** [comment]
Oh wow my bad :( 

Thanks!
