### ISSUE TITLE
question about the static filter syntax

### ISSUE THREAD

**Issue by hmztl976** [gorhill/uBlock#2373]
### Describe the issue
The wiki says "uBlock Origin ("uBO") supports Adblock Plus ("ABP") filter syntax".
But when I add a filter rule like 'example.com##div[style*="width:300px"]',nothing happends.

![image](https://cloud.githubusercontent.com/assets/10386497/22861600/e6d872d8-f157-11e6-81a0-01d4538d4a4f.png)

In fact, I want to hide the above one and show the below one.They are quite similar to each other.
So I use a rule as "##div[mrid*="_1024_"]".
I can confirm this rule works well with Adblock Plus.But it seems not work with uBlock Origin.

Then I want to know how to reach my purpose.
Can anyone help me?

### Steps for anyone to reproduce the issue
I think reproduce is not useless.
You can open a website,choose a div and try to hide it with a rule like mine(in your rule,"*=" should be contained)

### My settings
- Browser/version: Chromium	49.0.2623.75
- uBlock Origin version: uBlock Origin v1.11.1.0

**Comment by mapx-** [comment]
it works fine for me, for example on
http://edition.cnn.com/

add
`cnn.com##[class*="banner"]`
or
`cnn.com##[class*=banner]`

**Comment by hmztl976** [comment]
@mapx- 
Thank you for your reply!
You can try this rule on the same url.
`cnn.com##div[data-analytics*=list]`
This is what it should be:
![image](https://cloud.githubusercontent.com/assets/10386497/22862251/429ebd58-f166-11e6-868a-3e93687ff8a6.png)
Does it work well on your computer?

**Comment by gwarser** [comment]
Did you have "Parse and enforce cosmetic filters" checked?

**Comment by mapx-** [comment]
it works fine
uBlock Origin 1.11.0
chrome Version 57.0.2987.37 beta (64-bit)

**Comment by mapx-** [comment]
You should update your browser.

**Comment by hmztl976** [comment]
@gwarser 
I do

**Comment by hmztl976** [comment]
@mapx- 
Thank you.
Maybe it's the reason.I will try.

**Comment by gorhill** [comment]
Do you have cosmetic filter switch turned off for that site?

**Comment by gorhill** [comment]
Question about filter issues need to be made at uAssets.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by hmztl976** [comment]
@gorhill 
I found when I pack it into a crx file,it doesn't work and when I load it without packing,it works well.
It's hard to understand.
