### ISSUE TITLE
[Vivaldi 1.x] On-page full-text search glitches due to UB

### ISSUE THREAD

**Issue by Kein** [gorhill/uBlock#2374]
### Describe the issue
Weird "Search on page" behaviour in Vivaldi when the browser reports no search matches. When you switch between pages while re-using latest full-text search input (F3) with Ublock enabled very, VERY often you receive 0/0 results and no highlight for the matches even though the browser itself can move the page to the search match.

### One or more specific URLs where the issue occurs
Easy to test here:
https://hardforum.com/forums/displays.78/

### Screenshot in which the issue can be seen
https://imgur.com/a/dhMof

### Steps for anyone to reproduce the issue
Search for "dell" on page 1, then start to swap the pages, 1,2,3,4,5,6 while pressing F3 as you would normally to do sort through. Evetually, after the page with 0 actual results you swap to the page where you SHOULD get the match you receive 0/0 matches (even though word "dell" is on the page) and no text highlight.

This DOES not happen without UB. The highlight and counter will MAY appear with delay only after page is loaded but it WILL appear regardless.

### Your settings
Default Ublock setup.
Vivaldi 1.6.x/Vivaldi 1.7.x
Ublock Origin 1.11.0

##### Your custom filters (if any)
Default filter,m all default UB setup.  
Custom Block for reddit header via "www.reddit.com###sr-header-area"

**Comment by gorhill** [comment]
> This DOES not happen without UB.

Yes, it happens without uBO, this has been a long-time chromium issue: <https://bugs.chromium.org/p/chromium/issues/detail?id=2220>.

**Comment by Kein** [comment]
Well, I got tired of this crap and I spend damn hour trying to find out what causes it because multiple people kept telling me they never had it.

With disabled UB I NEVER was able to reproduce it. At best I received delayed hghlight but it always would return results.

With UB I can easily reproduce it in few seconds.

**Comment by gorhill** [comment]
And with uBO whitelisted for the site, do you still have the problem?

**Comment by Kein** [comment]
Sorry, I'm not saying the issue is a valid UB issue, I was just explaining (in previous comment) why I thought it was an UB issue. 

It just kinda weird why I can't reproduce it without UB. Thanks for clarifying.

**Comment by gorhill** [comment]
> It just kinda weird why I can't reproduce it without UB

That's why you should try to see if it still happens if:
- You whitelist uBO for the site; or
- You disable all filter lists and see if it still happens.

Just to rule out that some filters are causing the issue. Other than this, the details of the issue matches pretty well the Chromium issue --- something I have experienced myself with Chromium since forever -- though it does appear to be fixed in Chrome dev build.
