### ISSUE TITLE
uBlock block internal uMatrix pages as popup

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#2375]
In uMatrix create rule: ```* evil.biz * block```
In uBlock create rule: ```no-popups: * true```
Create this link on any web page: ```<a href="http://evil.biz/" target="_blank">--> Click this link <-- </a>```

Result:
<a href="https://lh3.googleusercontent.com/-rW2P2F7hNz0/WKHPtlKa_MI/AAAAAAAAdXg/tRXB2eI-YFQ/s0/screenshot%2525202017-02-13%252520001.png"><img src="https://lh3.googleusercontent.com/-cAWOCaJJ6HQ/WKHPuHoYABI/AAAAAAAAdXk/NAOPm5skwDc/s0/thumb_74d8fb8dcb22ab6cc5809eb067ceb18f.jpg"></a>

Win 8.1 x64, Firefox Nightly 54.0a1 x64 BuildID:20170213030206, e10s disabled.
uBlock Origin v1.11.1b1, default settings.
uMatrix 0.9.9b4, default settings.

**Comment by gorhill** [comment]
That's the expected behavior. A popup to `evil.biz` was detected by uBO, and targeted for automatic closing. That another add-on decided to do something else with the new tab (a redirect by uMatrix in the current case) is of no concern to uBO, it's job in the current case was to auto-close a popup, which it did.

**Comment by gorhill** [comment]
What you could do is create a `no-popups: umatrix false` rule in uBO.

**Comment by gorhill** [comment]
I am having second thoughts about whether uBO should exclude all non-http(s) schemes from the no-popups switch.

**Comment by Halibut80** [comment]
Still blocked.

**Comment by gorhill** [comment]
> Still blocked.

Yeah, I had a brainlapse, my suggestion was silly.

The issue here is actually related to #2277.

**Comment by X01X012013** [comment]
It seems some websites open `about:blank` (or similar stuff) then redirect to ads to bypass popup filter.

**Comment by gorhill** [comment]
uBO's no-popups code has undergone fine-tuning over time and the issue here is not reproducible. For instance `about:blank` is [now explicitly excluded as a popup candidate](https://github.com/gorhill/uBlock/blob/418dc5d8d154efa8fa26e806db1e70b2548bb908/src/js/tab.js#L133).
