### ISSUE TITLE
Failure to create cosmetic filter using element picker mode

### ISSUE THREAD

**Issue by xypha** [gorhill/uBlock#2376]
Failure to create cosmetic filter using element picker mode
Cosmetic filter: ##a[href="\"http://volarenovels.com/cultivation-chat-group/\""]
issue: "Create" button is greyed out, when element is selected using Ctrl-Click
URL: http://volarenovels.com/ccg-chapter-76/
Element: <a href="\&quot;http://volarenovels.com/cultivation-chat-group/\&quot;">[Table of Contents]</a>

### Screenshot in which the issue can be seen
![untitled](https://cloud.githubusercontent.com/assets/12472214/22917647/0654850c-f2ac-11e6-8c1e-08846d8413f9.jpg)

- Browser/version: Google chrome Version 56.0.2924.76 (64-bit)
- uBlock Origin version: uBlock Origin v1.11.0

## filter lists

43,137 network filters ＋ 66,569 cosmetic filters from:
My filters​​​​​1,472 used out of 1,493​​​​
uBlock filters​ 1,005 used out of 1,005​​​
uBlock filters – Badware risks​ ​​7 used out of 7​​​
uBlock filters – Experimental​ ​​6 used out of 6​​​
uBlock filters – Privacy​​​​​53 used out of 53​​​
uBlock filters – Unbreak​​​​​123 used out of 123​​​
Adblock Warning Removal List​ 304 used out of 322​​​
Anti-Adblock Killer | Reek​ ​​2,168 used out of 2,179​​​
Basic tracking list by Disconnect​​​​​10 used out of 34​​​
Malvertising filter list by Disconnect​​​​​149 used out of 5,518​​​
Malware Domain List​​​​​1,123 used out of 1,160​​​
Malware domains​ 17,287 used out of 18,080​​​
Malware domains (long-lived)​ 3,198 used out of 3,205​​​
Malware filter list by Disconnect​​​​​143 used out of 2,782​​​
Spam404​ 5,741 used out of 5,742​​​
Anti-ThirdpartySocial (see warning inside list)​ 46 used out of 65​​​
Dan Pollock’s hosts file​ 8,849 used out of 12,577​​​
Fanboy+Easylist-Merged Ultimate List​ 108,600 used out of 110,296​​​
hpHosts’ Ad and tracking servers​ 43,756 used out of 48,002​​​
MVPS HOSTS​ 12,690 used out of 13,222​​​
Peter Lowe’s Ad and tracking server list​ 2,360 used out of 2,361​​​
EU: Prebake - Filter Obtrusive Cookie Notices

##### Your custom filters (if any)
none

**Comment by gorhill** [comment]
The filter is properly selected on my side. The difference is that there are no backslashes on my side -- these backlashes are anomalous. Possibly another extension is messing up with the DOM?
