### ISSUE TITLE
[build request] Edge support & standalone version

### ISSUE THREAD

**Issue by EMLVIRUS** [gorhill/uBlock#2379]
1. could you transplant this extension to Microsoft Edge?
2. is it possible to build a standalone version as a Windows installer, aka an external blocker, to filter requests made by all Windows app processes that have Internet traffic.

**Comment by gorhill** [comment]
https://www.microsoft.com/en-gb/store/p/app/9nblggh444l4

**Comment by EMLVIRUS** [comment]
so what do you say about external version as a standalone Windows apps?

**Comment by uBlock-user** [comment]
He won't do it. That's why he closed the issue.

**Comment by Hrxn** [comment]
And it's not possible. Unless Windows provides a specific API for that purpose, which is not the case I believe.

**Comment by lewisje** [comment]
The closest thing to a standalone application is probably Ad Muncher; uBlock Origin and similar extensions rely on information provided by the browser to decide whether to block content, and a local proxy or something that just intercepts the network traffic (like Ad Muncher) will not have this information.
