### ISSUE TITLE
1.11.1b1 breaks many websites(default settings)

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#2382]
uBlock Origin1.11.1b1 breaks many websites(default settings) but works fine with older versions eg uBlock Origin1.10.6
New installation with default setting & FF50 & FF54

https://www.flipkart.com/intex-aqua-5-5-vr-champagne-white-8-gb/p/itmenf7fx4ujfznw
or mostly twitter videos or links

Steps for anyone to reproduce the issue:-

1. visit the link
2. now disable UBO1.11.1b1 & reload
3. works now
4.install 1.10.6 & visit the link
5.works

- Browser/version:  FF50 & FF54
- uBlock Origin version: 

Default filters

**Comment by gorhill** [comment]
All works fine here. Reporter deleted his account, so he won't be able to provide the key missing information (what _exactly_ is broken?)

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
> Reporter deleted his account

That's his name for his profile, like yours is Raymond Hill. The account exists. This is how a deleted account looks like - https://github.com/ndksnlndlnsdknknkddl

**Comment by gorhill** [comment]
That's the account: <https://github.com/allbugreporter>.

**Comment by Hrxn** [comment]
?

https://github.com/ghost

Always the same URL. Unless this is a massive account sharing conspiracy, this is indeed what a deleted account looks like...

**Comment by uBlock-user** [comment]
Never saw that one before. I'm talking about @ghost

**Comment by gorhill** [comment]
`https://github.com/ghost` is a generic placeholder account for deleted accounts. OP deleted his account.

**Comment by uBlock-user** [comment]
Yeah it appears so. I never saw that happened before. Quite surprising that they would pick ghost as the placeholder account.
