### ISSUE TITLE
Disable popups instead of hide them

### ISSUE THREAD

**Issue by QualleKalle** [gorhill/uBlock#2383]
uBlock doesn't block annoying popup windows, the popups are visible for some milliseconds in Opera / Chrome before they are eliminated by uBlock, or you can see that a new tab is opened and then immediately closed. Is there a specific reason why uBlock doesn't inject a small script and overwrite the JavaScript .open() method?

With
`window.open = function (open) {return true;};`
you can disable popups completely and no popup will ever appear on the site, no distracting from browsing. I do this job with TamperMonkey on some sites, but it would be nice if uBlock could do this.

Test URL: http://raymondhill.net/ublock/popup.html

**Comment by uBlock-user** [comment]
doesn't work against last 3 tests @QualleKalle

**Comment by QualleKalle** [comment]
@uBlock-user
You need to overwrite window.open() and document.open() to eliminate all popups and it's important that you do it as soon as possible before the webpage can overwrite or backup the method itself.

**Comment by uBlock-user** [comment]
@QualleKalle I'm not a JS expert, would you mind posting the JS here ?

**Comment by QualleKalle** [comment]
```
<script>
window.open = function (open) {alert("popup blocked");};
document.open = function (open) {alert("popup blocked");};
</script>
```
This should block the creation of all popups, test 13 + 14 changing the URL but the popup is blocked. Test 12 uses XMLHttpRequest.open() I never saw this before but if this method can be overwritten, this popup can also be disabled.

**Comment by uBlock-user** [comment]
For test 13 and 14 urls are still changed after I click ok on the popup blocked alert.

**Comment by gorhill** [comment]
> should

Anybody can speculate, it's easy and cheap.

The only valid argument worth to consider on an issue tracker is to fork the code, implement the (currently speculated) idea in a fully functioning uBO, tested on all browsers with no regression, handling all existing filtering cases. In short, make the case.

Anything else than this is just noise, and a burden for maintainers (hence why declined with no comment to minimize burden).

**Comment by uBlock-user** [comment]
Why not just add it as a resource in `/resources.txt` ? So it doesn't directly interact with uBO and won't cause any need to check for regression and other potential bugs.

**Comment by QualleKalle** [comment]
> Anybody can speculate, it's easy and cheap.

Speculated LOL. You never heard what the Tame Javascript by Paul Rupe is? You never used a proxy where this method is used since the early 2000 years to disable popup windows or other nasty stuff like alert, confirm, prompt messages? You don't know that there are complete popup blockers based on this?
I don't want to fork here anything, I don't like JavaScript I'm only experienced with C++/Qt. And my intention should be clear that this would be a nice and small improvement, used since ages but huh I make just noise for the developer.
I will never write here any more commends, your way you answer to people is just poor.

**Comment by uBlock-user** [comment]
Note to self -  we could just use `example.com##script:inject(abort-on-property-read.js, open)`
