### ISSUE TITLE
popunders are not closed

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#2386]
http://raymondhill.net/ublock/popup.html

### Screenshot

![ub_popunder](https://cloud.githubusercontent.com/assets/1126053/23096895/03354342-f627-11e6-93de-4c9e712472ee.png)

### Steps to reproduce the issue

1. Open provided url (22:06:31)
1. Click on testcase 13 or 14.  (22:06:34)
1. popunder is not be closed
1. Click on testcase (again) 13 or 14.  (22:06:36) 
1. popunder is closed

You can see that on the screenshot, refer to the timestamps. From my observation it never close popunder on the first click (or few more), but after it kicks in it closes all of them. Probably some race condition is in play. 

### Settings

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.11.1rc0

**Comment by gorhill** [comment]
You need to test with this filter: `||example.com/AdHandler.aspx?$popunder`, since the test uses a popunder for which there is no valid existing filter.

**Comment by gorhill** [comment]
I modified the test page to make this clear.

**Comment by kasper93** [comment]
@gorhill: Ok, but why it works without `popunder` filter if you click second time. This make those filter ambiguous.

**Comment by gorhill** [comment]
> why it works without `popunder` filter if you click second time.

An implementation side-effect -- I see no obvious fix for this side effect. If you wait more than 10 seconds, it won't work, it works only if you try again before 10 seconds delay.

Basically, popups blocking in uBO works as follow:
- Tab B is opened by Tab A.
- uBO labels Tab B as "potentially unwanted popup".
    - The label is good for at least 10 second, to be sure to handle all possibly delayed redirections inside Tab B.

In the current case, the above happens, but if you click the button before the 10 seconds delay:
- Tab C is opened by Tab B.
- Tab B is loaded with a URL which matches a popup filter from EasyList.
    - Tab B is _still_ labelled as potential popup originating with Tab A.
    - Hence Tab B is closed as a popup (which was opened by Tab A).

So what you have experienced is not popunder blocking, it's popup blocking, unless you use the popunder filter supplied above.

**Comment by gorhill** [comment]
The "10 seconds" delay is what makes uBO successful at blocking case 6. and 7. at this page <http://jessehakanen.net/adblockpluspopupaddon/test.html>, while ABP fails (custom filter `||google.*^$popup` must be used for these tests).

**Comment by kasper93** [comment]
Thank you for comprehensive explanation. Now it is clear to me.
