### ISSUE TITLE
Main image on comicbookmovie.com articles doesn't show when uBlock Origin is enabled

### ISSUE THREAD

**Issue by Nocturnalizer** [gorhill/uBlock#2387]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When using uBlock Origin on comicbookmovie.com the main top image in an article will not show until UBO is disabled on that particular page. Disabling it and refreshing the page shows the main image just fine. It displays a sort of image error or image missing icon instead. It shows a missing placeholder.

### One or more specific URLs where the issue occurs

https://www.comicbookmovie.com/batman/editorial-is-it-time-to-just-give-up-on-the-batman-once-and-for-all-a149058

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

http://i.imgur.com/qKCt0Io.png (UBO enabled)
http://imgur.com/k60itKQ (UBO disabled)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

1) Browse on to comicbookmovie.com with UBO enabled. Click on any article. The main image at the top of each article will not display and shows a missing icon and a placeholder of where it should be.
2) Disable UBO and refresh that page, the image should now display on the article without issue.
3) This is the main top image within articles, doesn't seem to affect anything on the home page of the website.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 51.0.1 (64-bit)
- uBlock Origin version: 1.10.6

##### Your filter lists

Default Filter Lists + Fanboy's Annoyance List (tried just with default and taking FAL off, still happens)

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Not a uBO issue -- the site return a 302 response for that image with a `Location` header set to `https://sync.1dmp.io/pixel.gif?cid=3c966c52-6780-4375-a8ce-fb17bf4c426e&pid=w&ru=https%3A%2F%2Fs24%2Epostimg%2Eorg%2Fdum921dk5%2FBatman%2Ejpg%3Fnoredir%3D1&uid=KyHbN0G2OpnbswnsCA1fIQ`.
