### ISSUE TITLE
Missing text in da-dk localization

### ISSUE THREAD

**Issue by ExactProbability** [gorhill/uBlock#2388]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
There is no text available for some of uBlock origin settings/buttons if using da-dk localization like I do.

This applies to all variants of uBlock Origin on all browsers on the Mac and Windows.

It's seen on the Dashboard page.

### One or more specific URLs where the issue occurs
The Dashboard page of ublock Origin

### Screenshot in which the issue can be seen

Attached ....

<img width="642" alt="ublock-da-dk" src="https://cloud.githubusercontent.com/assets/25787371/23101447/d66ecf50-f693-11e6-97ae-b2fdb01aec08.png">

### Steps for anyone to reproduce the issue

Install uBlock Origin for any browser and operating system if using da-dk(that's Danish in the country of Denmark)

Click the Dashboard tab if not already on the page.

Look towards the bottom of the page where the missing text is.

### Your settings

- Browser/version: Safari 10.0.3 (12602.4.8) on macOS Sierra 10.12.3
- uBlock Origin version: 1.11.1.0 (current release for Safari fork wise)

##### Your filter lists

Default + DNK

**Comment by gorhill** [comment]
More specifically, the issue was with <https://github.com/gorhill/uBlock/commit/e2fd7e48c81886f2dba42020891e070a0daae846#diff-878ed6de21a0a246d3455bacf3f0c016>, the translator translated a keywork which should not have been translated.
