### ISSUE TITLE
[firefox] can auto update ublock ver?

### ISSUE THREAD

**Issue by dsmnoi** [gorhill/uBlock#239]
hi
manual install ublock can auto update ublock ver for firefox? 
can add online auto update ublock ver?

**Comment by gorhill** [comment]
[AMO Review Policies](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews):

> Once reviewed, the version will be updated across the site and deployed through the automatic update service.

uBlock Origin is waiting for the review process to complete.
