### ISSUE TITLE
{Feature request} Email tracking blocking

### ISSUE THREAD

**Issue by cameronaaron** [gorhill/uBlock#2392]
It would be so awesome if you blocked email tracking like pixel block does by blocking the single embedded pixel in emails with tracking this will lead to much less spam in your inbox and also improve privacy of the user by not letting people know you opened there email yet

**Comment by gorhill** [comment]
That is a filter list issue -- report any such instance to filter list maintainers.

**Comment by cameronaaron** [comment]
Hi gorhill I mean no disrespect but It does not sound like you read my request or confused it with someone else. This is asking for a feature that blocks the email tracking pixel in emails to protect user privacy. This has nothing to do with filter lists and is not actually an issue with anything but rather a feature request. I'm sorry if i'm misunderstanding something. Thank you in advance

**Comment by gorhill** [comment]
Tracking pixels need to be identified by their URLs. Once identified, their URL can be filtered using filters, crafted by filter list maintainers.

**Comment by cameronaaron** [comment]
Ah thank you very much! I understand now!
