### ISSUE TITLE
US Gov web elements getting blocked with default filters

### ISSUE THREAD

**Issue by jcklasseter** [gorhill/uBlock#2393]
### Describe the issue
Site elements being blocked from expanding when user clicked

### One or more specific URLs where the issue occurs

https://travel.state.gov/content/passports/en/country/poland.html

### Steps for anyone to reproduce the issue
Load the webpage and try to expand the tabs underneath the quick facts page

### Your settings
- Browser/version: Firefox 51.0.1 64 Bit/Win10
- uBlock Origin version: 1.10.6

### Your filter lists
Default filter list

### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
