### ISSUE TITLE
Not works hiding in 1.11.0 for Firefox on e.mail.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBlock#2395]
uBlock Origin 1.11.0 for Firefox (uBlock filters, EasyList, RU AdList)
Mozilla Firefox 51.0.1

How to reproduce:
1. Open ​https://e.mail.ru/messages/inbox/
2. Open any message ​https://e.mail.ru/message/**************/
3. Open ​https://e.mail.ru/messages/inbox/
Ads appears at the left of the page.
You may need russian IP

Issue doesn't reproduce on:
Adblock Plus 1.12.4 for Google Chrome
Adblock Plus 1.12.4 for Safari
**uBock Origin 1.10.6 for Mozilla Firefox**
uBock Origin 1.11.0 for Google Chrome

Hiding works (for version 1.11.0) if used https://addons.mozilla.org/ru/firefox/addon/user-agent-switcher-firefox/ (any desktop UA).

Also: https://issues.adblockplus.org/ticket/4879#ticket

**Comment by gorhill** [comment]
Not something I will be able to investigate -- I do not have an account and I don't read Russian.

What specific filter is supposed to work but is not working?

**Comment by dimisa-RUAdList** [comment]
login`ublock-test@mail.ru`
pass `issues/2395`
http://i.imgur.com/DqRZ1Sh.jpg

**Comment by gorhill** [comment]
I can't reproduce the left-side ads on my side. Firefox 51 + uBO 1.11.0 + default settings + RU AdList + VPN RU IP:

![a](https://cloud.githubusercontent.com/assets/585534/23127719/08bfc200-f74a-11e6-8498-6e276dd84faa.png)

When I try with uBO 1.11.1rc0, the logger shows that a CSP to prevent web workers is being injected by uBO. Can you also reproduce with 1.11.1rc0.

Otherwise I don't know what to do to reproduce this.

**Comment by dimisa-RUAdList** [comment]
Unfortunately, not all VPN allows to "catch" this ad. This is true. But the version 1.10.6 works fine. I am ready to give remote access (TeamViewer). Leave me your real email in the mail, if you decide to take advantage of it.

**Comment by gorhill** [comment]
> not all VPN allows to "catch" this ad

I will try other RU IPs provided by my VPN.

**Comment by gorhill** [comment]
If I disable uBO for the site, I do get ads on the left-hand side. As soon as I re-enable uBO, the ads do not appear after a reload of the page.

**Comment by dimisa-RUAdList** [comment]
I get a lot of messages about the problem of the Russian users...

**Comment by gorhill** [comment]
> I get a lot of messages about the problem of the Russian users...

I am not saying I don't believe, just that I can't reproduce so far.

Actually I realize my mail.ru interface is in english, and I can't find a setting to turn it into ru -- that might be why I can't reproduce. I turned my whole Firefox into ru:
- `intl.locale.matchOS`: `false`
- `general.useragent.locale`: `ru`
- `intl.accept_languages`: `ru`

The mail.ru UI is still in English.

**Comment by dimisa-RUAdList** [comment]
This I had to switch to the lower right corner. But the presence of advertising does not depend on language interface.

**Comment by gorhill** [comment]
Does the ad's class/id matches any existing filter?

**Comment by dimisa-RUAdList** [comment]
```
e.mail.ru###leftcol-banners
e.mail.ru##.b-datalist__head
e.mail.ru##.b-letter__head__rb
e.mail.ru##.direct-state
```
But the fact is reset styles and id elements are randomly.

**Comment by gorhill** [comment]
> But the fact is reset styles and id elements are randomly.

If a user with dev skills can reproduce the issue and can figure a fix using uBO's specific filter syntax, I am opened to add these uBO-specific filters to uBlock Origin's own filter to fix this.

**Comment by egoroof** [comment]
Can't reproduce too.

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/df43296b83a8

**Comment by Atavic** [comment]
I have never seen those ads. I use the default theme on MailRu.

**Comment by dimisa-RUAdList** [comment]
Кто ещё никогда не видел эту рекламу? Отписывайтесь, не стесняйтесь. Но я, обслуживая подписку RU AdList, ежемесячно обрабатываю ~ 10.000 репортов. И в последние дни - каждый 4-5 репорт идёт с жалобой на почту mail.ru. Как видно в стартовом сообщении, все предыдущие Firefox-версии uBO до 1.11.0 с данной рекламой справлялись вполне успешно. Проблема возникла именно в версии 1.11.0, причём проявляется она только с определёнными российскими ip. Автор расширения не захотел разбираться с этой проблемой и в итоге мне пришлось ввести исключения, разрешив исполнение рекламных скриптов и оставив только скрытие: https://hg.adblockplus.org/ruadlist/rev/df43296b83a8

Но вся соль в том, что ранее я это уже делал:
https://hg.adblockplus.org/ruadlist/rev/84b56ebcad20
https://hg.adblockplus.org/ruadlist/rev/72838d5c841b
и веб-мастера mail.ru просто обновляли триггер детектора и всё начиналось по новой. Так что насколько хватит этой правки, неизвестно.

**Comment by Atavic** [comment]
The issue is opened.
I haven't russian IP.

**Comment by gorhill** [comment]
> The problem arose in version 1.11.0

The site is obviously sniffing and serving content according to the results of its sniffing (user agent string, OS, and whatever else). The main difference between uBO 1.11.0 vs 1.10.6 in Firefox is that uBO no longer injects `style` tags on the page to enforce cosmetic filtering, it is now based solely on user styles -- just like with ABP (except hat uBO injects only the minimum amount of CSS rules).

It just look to me like the site serves stuff according to many variables -- and it's not something uBO should second guess. The real cure is that for whoever is able to reproduce the ads, to find what cosmetic filters work best -- including procedural cosmetic filters if it's what it takes, just as was done with Facebook.

**Comment by dimisa-RUAdList** [comment]
> The main difference between uBO 1.11.0 vs 1.10.6 in Firefox is that uBO no longer injects style tags on the page to enforce cosmetic filtering, it is now based solely on user styles -- just like with ABP (except that uBO injects only the minimum amount of CSS rules).

Yes, the problem has arisen because of these changes.
