### ISSUE TITLE
High resolution icon in right-click menu [uBO Chrome]

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2396]
I recently changed my display resolution to **1920x1080** and noticed after right clicking in **Google Chrome** that the right-click/context menu has a low resolution **uBlock Origin icon** along with the "**_Block element_**" option. It appears **pixelated**, the extension icon appears fine in the toolbar though.

Is there a limit for resolution of context menu icons in Chrome extensions?

**SS:** http://oi66.tinypic.com/2aiiyae.jpg

Right click to see the low resolution icon in the Chrome context menu.

_**Note:** Using Chrome 56 with uBO 1.11.0_

**Comment by gorhill** [comment]
Chromium issue: <https://bugs.chromium.org/p/chromium/issues/detail?id=418380>.
