### ISSUE TITLE
Element selector doesn't work on Chrome's New Tab page

### ISSUE THREAD

**Issue by Pastafarianist** [gorhill/uBlock#2397]
Steps to reproduce:

1. Open a new tab in Chrome
2. Click uBlock's icon in the toolbar
3. Click "activate element selector"

![image](https://cloud.githubusercontent.com/assets/1315874/23138472/bb644ce6-f7b8-11e6-8d26-b9ac50732855.png)

* Expected result: element selector appears, like on normal pages.
* Actual result: nothing happens.

I do not remember changing the default settings, apart from enabling "advanced settings". Disabling them does not have any effect.

- Browser/version: Chrome 53.0.2785.92
- uBlock Origin version: uBlock 1.11.0

(I wanted this to work to get rid of Google's logo and the search bar on the new tab page.)

**Comment by gorhill** [comment]
By design, cosmetic filtering works only on http/https pages.
