### ISSUE TITLE
Disable pre-fetching 

### ISSUE THREAD

**Issue by lukas235** [gorhill/uBlock#2398]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
"Disable pre-fetching (to prevent any connection for blocked network requests)" feature enables the "Use a prediction service to load pages more quickly" setting instead of enabling it.

### One or more specific URLs where the issue occurs
chrome://settings/

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Tested with clean install: Disable all settings in Chromium Settings/Advanced/Privacy and Security. Install uBlock Origin. The "Use a prediction service to load pages more quickly" will be enabled and cannot be disabled unless "Disable pre-fetching (to prevent any connection for blocked network requests)" is disabled.

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Clean chromium install and disabled the six sliders under Privacy and Security.

- Browser/version: Version 58.0.3016.0 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.11.0

##### Your filter lists
Default filters +
Basic tracking list by Disconnect​​​​​
Fanboy’s Enhanced Tracking List​
DEU: EasyList Germany

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Browser bug: <https://bugs.chromium.org/p/chromium/issues/detail?id=693301>.

Prefetching is disabled, it's just the rendering of the button which is incorrect with the new Material Design page.

**Comment by uBlock-user** [comment]
It is disabled, however the material design UI screws it up and shows it enabled. Revert to normal UI for settings via the chrome flag - `chrome://flags/#enable-md-settings` and you will see for yourself.
