### ISSUE TITLE
Broken comments on futura.sciences.com

### ISSUE THREAD

**Issue by onestepbeyond** [gorhill/uBlock#240]
Unless I am mistaken, It seems that something in _uBlock filters - Privacy_ breaks loading of the comments on futura-sciences.com website. Example on [this page](http://www.futura-sciences.com/magazines/espace/infos/actu/d/ceres-planete-naine-ceres-affiche-multitude-points-lumineux-58228/?no_cache=2#comments). 
If _uBlock filters - Privacy_ isn't unticked, can see that a throbber turns and turns instead of displaying comments. 
Although there are only two active filters, I have not figured out how to work around this issue.

**Comment by gorhill** [comment]
Looks like the site needs `s7.addthis.com/js/300/addthis_widget.js`. So you will need to create an exception for that site:

    @@||s7.addthis.com/js/300/addthis_widget.js$domain=www.futura-sciences.com

**Comment by gorhill** [comment]
Hum, actually I realize this won't work because the filter in _Privacy_ has the `important` keyword.

This could be solved if using the lastest dev version of uBlock however, with URL-based dynamic filtering:

    www.futura-sciences.com http://s7.addthis.com/js/300/addthis_widget.js script allow

Otherwise you will have to un-check _Privacy_, or whitelist that web site (or web page if it is the only page you care about).

**Comment by onestepbeyond** [comment]
OK, your first suggestion don't worked for me. 
Following others ideas, I've added `@@||s7.addthis.com/js/300/addthis_widget.js#pubid=futurasci` and `#@#.addthis_toolbox` but works not better. 
I've also unchecked all filter lists and emptyed my own filters, without more success. 
I'll go to uncheck *uBlock filters - Privacy* because whitelisting the site or page is unsuitable for me. 
Thanks for investigating ;-)

**Comment by onestepbeyond** [comment]
Not fully read your edit , I'll see it more closely.

**Comment by onestepbeyond** [comment]
I have already the latest dev release, but how to add an URL like 
`www.futura-sciences.com http://s7.addthis.com/js/300/addthis_widget.js script allow` **?** 
   
Is there the way to proceed ? => ![screenshot01324](https://cloud.githubusercontent.com/assets/11029138/7788105/cc9b2872-022d-11e5-806f-93d2285947cb.png)

**Comment by gorhill** [comment]
> Is there the way to proceed ?

Yes, this should work. Just click the padlock so that the rule becomes permanent.

**Comment by onestepbeyond** [comment]
Works well ! Thanks ! 
Clicking the padlock made it disappear, is this correct ?

**Comment by gorhill** [comment]
> Clicking the padlock made it disappear, is this correct?

Yes, this means there are no temporary rules in the dialog.

**Comment by onestepbeyond** [comment]
OK, thanks a lot !
