### ISSUE TITLE
Some global dynamic filtering rules vanish

### ISSUE THREAD

**Issue by hawran** [gorhill/uBlock#2401]
When I use the "Advanced settings" and set up global dynamic filtering rules, uBlock remembers my "3rd-party" settings (.../scripts/frames - all are red), however my settings for other sites are lost - I need to set them up again when I return to a particular site (after I had already set up my preferences for that site).

What am I missing?

- Browser/version:
Firefox Version 	51.0.1
Build ID 	20170201175806
Update History User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

- uBlock Origin version: 
uBlock Origin v1.10.6

##### Your filter lists
default

NB I've just noticed the 3rd party settings are lost as well (after Firefox's restart). ?

**Comment by gorhill** [comment]
Are you clicking the padlock to persist your rules?

**Comment by hawran** [comment]
Wow, I overlooked that "button".
It seems to be working now, thank you!

Regards,
hawran
