### ISSUE TITLE
"Block media elements larger than" is not working

### ISSUE THREAD

**Issue by phonphen** [gorhill/uBlock#2402]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Block media elements larger than is not working

### One or more specific URLs where the issue occurs

any youtube or facebook video

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. set and enable Block media elements larger than 100 kb in setting
2. go to any youtube video ex.: https://www.youtube.com/watch?v=iy_HGFlC634
3. video still playing but report blocked

![log](https://cloud.githubusercontent.com/assets/25279951/23163941/5040e00a-f867-11e6-8dc2-78ed751f8c43.png)

### Your settings

![setting](https://cloud.githubusercontent.com/assets/25279951/23163370/c4eeaf48-f864-11e6-93a5-9a05a273fb4f.png)

- FF  51.01 32bit
- uBlock Origin version: v1.11.1rc0

##### Your filter lists

"Default filter lists + easy list + easy privacy", or "Default filter lists minus uBlock -- Badware risks"

##### Your custom filters (if any)

![5556](https://cloud.githubusercontent.com/assets/25279951/23163468/22afade4-f865-11e6-8568-3c6bfb727e4c.png)

**Comment by gorhill** [comment]
Youtube videos are not served as media elements, they are served as XMLHttpRequest.
