### ISSUE TITLE
Custom rules vanish from the edit box after apply

### ISSUE THREAD

**Issue by gv01** [gorhill/uBlock#2403]
Custom rules  added to "3rd-party" (bellow "One URL per line. Lines prefixed with ‘!’ will be ignored. Invalid URLs will be silently ignored.") vanish after pressing apply button.

This is very unfortunate if someone want to enable/disable some custom rules several time a day. It's _really_ annoying to paste the link every time after a custom rule is disabled and it need to be enabled again. Also comments related to a specific rule vanish.

Please revert to previous behaviour. Thank you.

**Comment by mapx-** [comment]
You have to add your custom filters in the "my filters" tab / section.
In the "One URL per line.." box you can add your filter list (hosted on some server)

**Comment by gv01** [comment]
Prior to uBO v1.11.0 custom rules like this would stick:

> ! Use this rule when x and not y
> https://www.somewhere.org/rules/rule.txt

Paste the above lines in the custom edit box, apply, the rule where added and the text remain in the edit box.

Starting with uBO v1.11.0 the text from edit box vanished. If a specific custom rule is disabled (press the red X button), I had to paste, again, the text above if I need the rule re-enabled (and press apply).

**Comment by gwarser** [comment]
Use checkbox to disable custom list. Red X is for removing.

**Comment by gorhill** [comment]
Read the release notes for 1.11.0.
