### ISSUE TITLE
1.11.0 and filterlists sources (HTTP/ HTTPS)

### ISSUE THREAD

**Issue by beerisgood** [gorhill/uBlock#2404]
Before 1.11.0 we see which filterlists are available over HTTPS (the most) or only over HTTP.
In 1.11.0 this feature is gone. Why?

For example if i now click on chrome://ublock0/content/asset-viewer.html?url=malware-0 (Malware Domain List) i see **http**://www.malwaredomainlist.com/hostslist/hosts.txt
But not all filterlists show that info, so please add the feature back.

I dont like filterlists which go over HTTP.

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by beerisgood** [comment]
That? Why?
Since when isnt Github a place to speak about bugs. And since when are bugs which are not crash the program no bugs?

I dont care about mozilla.

**Comment by gorhill** [comment]
`www.malwaredomainlist.com/hostslist/hosts.txt` is pulled over https. The unlocked padlock icon is shown only for filter lists which have been pulled over http.

**Comment by beerisgood** [comment]
Thanks.
I see no unlocked padlock. So that means all (default) filterlists use HTTPS by default then?

**Comment by gorhill** [comment]
A filter list can now be downloaded from one or _many_ URLs. Whether a list is pulled from a https URL will be decided at download time (if a URL fails, uBO will try to download with an alternative URL if any), and once a list is downloaded, the unlock padlock icon will be shown if the list was actually downloaded from a non-https URL.
