### ISSUE TITLE
Third-party filter suggestion

### ISSUE THREAD

**Issue by azet12** [gorhill/uBlock#2405]
Hello. I've been working on a new Polish filter for a few months.

It's called KAD and basically it's like Spam404 list, but focused on Polish scams. There is a very big amount of them out there and many people lose money because of these sites.

The fake websites had been originally on a MajkiIT's polish-ads-filter list, but since there are so many of them, a different project maintained by other person was needed.
It would be great if the filter were in the third-party filters list and enabled by default for Polish users.

Here's the RAW: `https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt`
Project site: https://azet12.github.io/KAD/

Thanks in advance

**Comment by matreex** [comment]
`* * 3p block` is not working on firefox v52.0.2, nilgtly v55.0a1 and dev v54.0a2.
`* * 3p block
* * 3p-frame block
* * 3p-script block
* * inline-script block`
And I'm testing, add the rules to uBO v1.11.4, DTA can download files, type about:addons to location bar, click "update add-ons automatically" on the top right corner, old version of addons will be check and update. if uBO v1.11.4 install to firefox v50.1.0, and `* * 3p block` is work.

**Comment by matreex** [comment]
`* * 3p block` is not working on firefox v52.0.2, nilgtly v55.0a1 and dev v54.0a2.
`* * 3p block`
`* * 3p-frame block`
`* * 3p-script block`
`* * inline-script block`
And I'm testing, add the rules to uBO v1.11.4, DTA can download files, type about:addons to location bar, click "update add-ons automatically" on the top right corner, old version of addons will be check and update. if uBO v1.11.4 install to firefox v50.1.0, and `* * 3p block` is work.

**Comment by ryanbr** [comment]
Not a really well optimised filterset.

**Comment by azet12** [comment]
@ryanbr Feel free to elaborate inside an Issue on project's repository.

**Comment by ryanbr** [comment]
minimal use of any filter tags like filter tags like third-party, ^, *, ||, or even element hiding. Not well optimized.

**Comment by azet12** [comment]
@ryanbr This issue was addressed today.

**Comment by gorhill** [comment]
As explained here: <https://github.com/gorhill/uBlock/issues/3014#issuecomment-329457339>.
