### ISSUE TITLE
Ads on Facebook Videos

### ISSUE THREAD

**Issue by peopledrivemecrazy** [gorhill/uBlock#2406]
![image](https://cloud.githubusercontent.com/assets/3922469/23270119/d7fa66c6-fa18-11e6-90ce-b21bf6a90c66.png)
Intrusive ad on facebook video

**Comment by anewuser** [comment]
You've ignored and deleted the template text that appears when you create a new issue.

Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You need to report this to list maintainers instead.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
