### ISSUE TITLE
Youtube ads

### ISSUE THREAD

**Issue by cripii5** [gorhill/uBlock#2407]
I saw today ads on a YouTube video with Ublock Origin working. You know, that ads that appears at the begging of the video but this one you can't skipped 5 seconds later like others Youtube ads.
I've never touch the Ublock Origin settings, no filter, no nothing.
I think is unnecesary to paste the link of the video here because we now how Youtube video ads works, is random... and because I don't remember which video was.
Unfortunely I cannot reproduce the issue twice (I actually didn't tried that much) but it doesn't make sense that happen even once.
If want or need more information please let me know

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
