### ISSUE TITLE
Javascript redirection

### ISSUE THREAD

**Issue by useretail** [gorhill/uBlock#2408]
### The issue
Website uses redirection to block page if uBlock blocks a URL from blacklist.

### Steps for anyone to reproduce the issue
1. Go to: http://www.dasolo.online/
2. Wait for alert message and redirection to: http://www.dasolo.online/adblock/index.html

### Versions
- Browser/version: Google Chrome 56.0.2924.87 (64-bit)
- uBlock Origin version: 1.11.0

### HTML code sample:
```html
<img src="http://js.adscale.de/getads.js:adscale_slot_id/" width="0" height="0" border="0" alt="adblocktest" id="adblocktest" /> 
```
### Javasctipt code sample:
```javascript
function adblockblock() { 
alert('AdBlock active Please disable AdBlock to enter in the website.....Per favore disattiva AdBlock per entrare nel sito !');        
document.location.href='http://www.dasolo.org/adblock/index.html'; 
} 
function adblocktest(testnumber) { 
        abbitem=document.getElementById('adblocktest'); 
        if(!abbitem){ 
                adblockblock(); 
        } else if (abbitem.style.display == 'none' | abbitem.style.visibility == 'hidden'){ 
                adblockblock(); 
        } else if (testnumber!=1){ 
                setTimeout(function(){adblocktest(1);},4000); 
        } 
} 
function doadblocktest(){ 
        if(adblocktest_orig_onload){adblocktest_orig_onload();} 
        setTimeout(adblocktest,1000); 
} 
adblocktest_orig_onload=window.onload?window.onload:false; 
window.onload=doadblocktest; 
```

**Comment by useretail** [comment]
I guess that the temporary solution would be to block adblocktest() function, but is it possible in uBlock?

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=113715#p113715

**Comment by useretail** [comment]
Thanks, that's one way of solving this. I'll repost it here:
```text
||dasolo.online/aadb.js
@@||js.adscale.de/getads.js:adscale_slot_id/|$image,domain=dasolo.online
```

**Comment by mapx-** [comment]
however, the place where to report filter/sites issues is:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
@useretail https://github.com/reek/anti-adblock-killer/issues/2802
