### ISSUE TITLE
uBlock breaks Twitch buttons

### ISSUE THREAD

**Issue by extesy** [gorhill/uBlock#2409]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When uBlock is enabled, it breaks functionality for "subscribe" and "free with prime" buttons: when those buttons are clicked, nothing happens. I have tried using full local allow rule so that not a single request is blocked, but buttons still don't work. The only way to unbreak Twitch is to completely disable uBlock for twitch.tv domain. Theoretically there shouldn't be any difference between "allow all rules locally" and "disable uBlock for current website", is it?

### One or more specific URLs where the issue occurs

https://www.twitch.tv/iamcvh

### Screenshot in which the issue can be seen

Not a visual issue. It's a broken button click functionality.

### Steps for anyone to reproduce the issue

1. Go to any top streamer on Twitch (so that they have Subscribe button available)
2. Log in to Twitch account
3. Press on Subscribe button
Expected: popup dialog providing subscription options
Observed: no popup unless uBlock is disabled for the domain

### Your settings

- Browser/version: Chrome Version 56.0.2924.87 (64-bit)
- uBlock Origin version: 1.11.0

##### Your filter lists

https://i.imgur.com/qzyZxlx.png

##### Your custom filters (if any)

www.engadget.com###latest-product-review
www.engadget.com###hot-topics
www.engadget.com###dynamic-lede
www.engadget.com##article[data-image*="5min.com"]
d3.ru###js-fixed_sidebar
dirty.ru###js-posts_holder > .b-posts_holder > .js-posts_ad.b-user_ad_container
dirty.ru###js-comments > .js-posts_ad.b-user_ad_container
www.braveclojure.com###top-nav
www.torrentleech.org###supportTorrentLeech
www.torrentleech.org###right
followshows.com##.responsive-header-ad
dirty.ru##.js-posts_ad
@@||onmsft.com^$generichide

**Comment by okiehsch** [comment]
Did you try disabling cosmetic filters?

**Comment by extesy** [comment]
Updating `Fanboy's Annoyance List` fixed the problem. Thank you!

**Comment by extesy** [comment]
Wait, but what about locally enabling all requests? Why is the filter still active in this case?

**Comment by okiehsch** [comment]
It only allows all network requests,

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
