### ISSUE TITLE
[Suggestions] - Tooltips, Language Selector, exclude list for website

### ISSUE THREAD

**Issue by Zerobinary99** [gorhill/uBlock#241]
I have recently switched to uBlock and am blown away by how great it is. However, the software is not really intuitive to use even though I have years of experience with ABP. Some tooltips could really help in this regard.

It would also be great if the software allowed the user to set the language instead of just using the browser's language. 

Some filter lists break websites, so it would be nice to exclude those lists for that website while keeping the remaining lists active. Additionally, it would be nice if it possible to just deactivate single filters in those subscribed list. The latter is probably already possible, but I haven't found out how to achieve that.

That being said, keep up the good work. I'm glad I don't have to use ABP anymore :)

**Comment by Snapy** [comment]
Read the wiki to learn how to use uBlock, it will also help you solve your other problems. You will know how to unbreak websites broken by filter lists. You can deactivate single filters by creating exception filters.

**Comment by Zerobinary99** [comment]
I did. Believe it or not. The explanations given are everything but clearly understandable. There are hardly any screenshots or examples available that would help someone achieve above requests. Anyway, even if I was an expert user of this addon, this still wouldn't invalidate the feature request.

**Comment by CrisBRM** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface is extremely comprehensive and well written, with screenshots. If anything, gorhill should create a popup with a link to that tutorial for first time users.

**Comment by Zerobinary99** [comment]
That link is indeed helpful and I agree that users should be directed to it upon first installation. Placing the link on the description page of uBlock would probably already suffice, even though a popup would be more effective.

Anyway, my suggestions still stand, because those features aren't supported yet. Tooltips are just standard in every properly written program and can help loads with a program's usability if done correctly. I read through the documentation. Still, I didn't learn it by heart and thus can't remember every detail. Minor stuff like which column means local and which corresponds to global filters etc could be easily explained by that and could keep the hassle to a minimum. 

Language selection makes a lot of sense for those who run non-English browsers, but might want to google for feature names in English. Also important for error reporting.

Excluding entire lists for certain websites while keeping them active for the rest is not supported, but could improve comfort, usability and probably also performance tremendously. Especially the latter makes sense since multiple lists tend to have overlap which can be reduced that way. That is unless uBlock actually creates a dupe-free internal filter list upon startup. Still, comfort and usability would still stand as important factors especially for less technically inclined users.

**Comment by hotdogman** [comment]
>Especially the latter makes sense since multiple lists tend to have overlap which can be reduced that way. That is unless uBlock actually creates a dupe-free internal filter list upon startup.

It does. That's why it says xx used out of yy in "3rd Party Filters" under the dashboard.
>Language selection makes a lot of sense for those who run non-English browsers, but might want to google for feature names in English. Also important for error reporting and helping others with different languages.

Language selection isn't present.
>Tooltips are just standard in every properly written program and can help loads with a program's usability if done correctly. I read through the documentation.

Tooltips are present in uBlock Origin if you don't have advanced user mode enabled.

**Comment by gorhill** [comment]
> would be nice to exclude those lists for that website while keeping the remaining lists active

I don't see how this could be supported while keeping uBlock efficient resource-wise, uBlock defining trait.

So I went through your laundry list, and other points have been properly answered by other users in here. For the language thing, I don't see this as a big pay off given the amount of time/work required to supprot this.

**Comment by Zerobinary99** [comment]
There are three tooltips in non-advanced mode, None of the dashboard features are explained. 

"Language selection isn't present."

You joker. That's why I requested that.

" I don't see this as a big pay off given the amount of time/work required to supprot this."

I don't see the problem of asking the user upon installation which language to use instead of just deciding it for him.

**Comment by gorhill** [comment]
> But seriously, what's the effort?

The favorite arguments developers all over the world like to be served.

> It's kind of ironic

Sarcasm doesn't drive what features I choose to work on in my free time. Good technical and common sense arguments do.

The language uBlock uses can be changed by changing your browser language -- feasible in both Firefox and Chromium. There is no really good reason why uBlock should burden itself to support a language setting when it can be done from the browser, and this will work for all extensions.

**Comment by alain1965** [comment]
Hello, I don't understand all the subtilities of this discusion but I don't like some messages, @gorhill is the owner, the developer, the creator of ublocko, he takes on his free time to work on it so stop try to say to him what he must do or not, he's the boss if someone don't like what he does try another addon, make yours or make your fork. You have an another ublock who is developed (or trying to be developing) by a teenager of 17 years old. He's not bad but a little slow and lost in his development of ublock, so if somebody is not happy from @gorhill go help @chrisaljoudi and give him your advices, I think he need someone. To @gorhill, you live in montreal, québec, so maybe you have one or two notions of french and like I am french it is more easy to me to say it in french. Continue ton boulot, c'est du très bon travail et ne t'occupe pas des emmerdeurs, thanks.
