### ISSUE TITLE
Cleanup repo

### ISSUE THREAD

**Issue by mathbunnyru** [gorhill/uBlock#2410]
### Describe the issue
Downloading this repository takes a lot of time. It happens, because files like ublock_0.1.0.1.zip were added to this repo. It doesn't matter if they were deleted later - they are still in .git.

But there's a cure:
There's an utility, which works pretty well:
https://rtyley.github.io/bfg-repo-cleaner/

Please, make your repository easier to clone. Thanks.

**Comment by ag-n** [comment]
Why should these ublock_0.1.0.1.zip files be in the git repo anyway ? I don't know much about GitHub : isn't there a way to add them to the "Releases" page without being in the git repo ? Git is for source code, not release archives.

**Comment by mathbunnyru** [comment]
It seems to be possible to create releases without adding zips to repo:
https://help.github.com/articles/creating-releases/
As you can see on the 7th tip, it's easy to drag and drop some binary files to a new release.

**Comment by gorhill** [comment]
I don't really have time to investigate all this for now.

**Comment by mathbunnyru** [comment]
Ok, thank you for your response.

**Comment by magicgoose** [comment]
> It doesn't matter if they were deleted later - they are still in .git.

If you want to download only the most recent state of the repo, then you can add `--depth 1` parameter to git clone command. And then it shall not download anything that's not present at the latest commit. (if I understand it correctly)

**Comment by GuhaPatraR** [comment]
Is this issue fixed or not an issue at all?

**Comment by Atavic** [comment]
It's still an issue, but two workarounds are provided.

**Comment by gorhill** [comment]
Declined as this is asking me to download and execute some external tools on the repo. I will consider only actual git commands with well defined results.
