### ISSUE TITLE
Auto-sync for dynamic filters among browsers/devices?

### ISSUE THREAD

**Issue by testerist** [gorhill/uBlock#2411]
Hi,

Is there a way to sync among devices automatically (or at least more easily) like with static lists? Currently with static ones I can just create my custom list, upload the txt file to my web server and add it to the auto-updated My filters.

I know uBlock has this feature to export to cloud storage. However cloud import seems to be fixed for the particular browser and I don't find a way to easily synchronize "My rules" for example from desktop Chrome to Firefox on Android. Right now to do it I export the settings to a txt file, then upload to Google Drive (because mobile Firefox won't add from local file) and then import them to mobile Firefox. This can be quite a travail when having to sync settings after frequent rule changes.

I wonder if I am just doing things wrong or that may be a new good feature to add?

**Comment by anewuser** [comment]
https://github.com/gorhill/uBlock/issues/1615

**Comment by gorhill** [comment]
> I don't find a way to easily synchronize "My rules" for example from desktop Chrome to Firefox on Android

Sync across different browser is not possible.
