### ISSUE TITLE
[wiki] Dynamic filtering improved in a year :-)

### ISSUE THREAD

**Issue by mdhooge** [gorhill/uBlock#2412]
The wiki page https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax states twice “is always *”. But from what I can test, this is no longer true!

Note that with type-based rules, the **destination hostname is always** *, meaning "from anywhere".

With hostname-based rule, the **type is always** *, meaning the rule will apply to any type of request.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
