### ISSUE TITLE
pornhub.com popunder

### ISSUE THREAD

**Issue by stanlane** [gorhill/uBlock#2413]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
A popunder is activated on the first visit on [pornhub.com](http://pornhub.com/).

### One or more specific URLs where the issue occurs

[pornhub.com](http://pornhub.com/)

### Screenshot in which the issue can be seen

![ubo1](https://cloud.githubusercontent.com/assets/25944158/23377182/3eb503bc-fd2f-11e6-84c0-64ef2e9e1a57.png)
![ubo2](https://cloud.githubusercontent.com/assets/25944158/23377181/3eb34ec8-fd2f-11e6-801f-5fad0c7f3000.png)

### Steps for anyone to reproduce the issue

1. Visit [pornhub.com](http://pornhub.com/)
2. Click on any video.
3. You'll notice the popunder.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox ESR 38.8.0
- uBlock Origin version: 1.11.0

##### Your filter lists
Default filter lists, updated of course.

**Comment by 0xadada** [comment]
Thanks for keeping this issue classy 👍

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
They're using UAParser script

add - `pornhub.com##script:inject(abort-on-property-write.js, UAParser)`

**Comment by stanlane** [comment]
@uBlock-user That did it, thanks!

@gorhill Can you please add that filter to some uBO filter?
