### ISSUE TITLE
hpHosts on http

### ISSUE THREAD

**Issue by elgab** [gorhill/uBlock#2416]
https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json#L131

should be "https://hosts-file.net/ad_servers.txt"
also the red lock for insecure sources would be nice to be more vibrant

**Comment by gorhill** [comment]
That file is no longer used as of 1.11.0. See <https://github.com/gorhill/uBlock/pull/2314>.

Duplicate of #1749.
