### ISSUE TITLE
 uBlock Origin 1.11.0 breaks Chromium 56.0.2924.87 on Mac 10.11

### ISSUE THREAD

**Issue by the-bobo** [gorhill/uBlock#2418]
What can I do to help you debug to determine if this really is uBlock? If I disable uBlock this behavior doesn't happen, which is why I think it's the extension.

### Describe the issue
Chromium 56.0.2924.87 (latest stable Chromium release) crashes unpredictably on Mac. Playing a youtube video can pretty reliably get it to crash (e.g. https://www.youtube.com/watch?v=cmdFne7LnuA), but even a regular web page will sometimes cause it to crash as well (https://www.chromium.org/developers/version-numbers).

I'm also seeing this error sometimes come up in the console, which I think is related to the uBlock extension, perhaps the file contentscript.js?: 
`"Uncaught ReferenceError: vAPI is not defined" source: chrome-extension://[a long string that looks like a hash]/js/contentscript.js`

As well as this error (seems to occur reliably) right before the crash: 
`FATAL:http_util.cc(61)] Check failed: url.is_valid() && (url.SchemeIsHTTPOrHTTPS() || url.SchemeIs("ftp") || url.SchemeIsWSOrWSS()).`

### One or more specific URLs where the issue occurs
will crash - https://www.youtube.com/watch?v=cmdFne7LnuA
will crash - https://www.chromium.org/developers/version-numbers
(in both cases the FATAL error above is the last error before Chromium crashes)

### Steps for anyone to reproduce the issue
Open Chromium with uBlock Origin 1.11.0 enabled and navigate to the above links.

I have tried opening Chromium in the following two ways, in both cases the crash still happens:
1. `chromium/src/out/Default/Chromium.app/Contents/MacOS/Chromium --usr-data-dir=/tmp`
2. `open ./chromium/src/out/Default/Chromium.app`

The first way should avoid any corrupt user data from previous versions of Chromium, but crashes still occur.

If I try it again with uBlock Origin 1.11.0 disabled there's no crash.

I can provide the `Chromium.app` for testing or list the `args.gn` build flags selected if you want to build from source yourself (a time consuming process).

### Your settings
- Browser/version: Chromium / 56.0.2924.87
- uBlock Origin version: 1.11.0

##### Your filter lists
I am willing to re-test with default filter lists - is there a simple way for me to toggle this? Would rather not lose all my custom filters/filter list selections by uninstalling. If there is no other option I will uninstall/reinstall UBlock and manually re-load filters and filter lists one-by-one.

**Comment by gorhill** [comment]
> Chromium 56.0.2924.87 (latest stable Chromium release) crashes unpredictably on Mac.

uBO is HTML/CSS/JS, and a browser is **not** supposed to crash as a result of executing javascript. Report to Chromium devs.

Also probably a good idea you investigate on your side if something is interfering with the proper functioning of your browser, including is something tampered with your browser installation.
