### ISSUE TITLE
Recent change to adminSettings?

### ISSUE THREAD

**Issue by jocooza** [gorhill/uBlock#2419]
I have been using uBlock Origin with `adminSettings` and the following JSON string for a long time:

    {"userSettings": {"advancedUserEnabled": true},"filterLists": {"https://easylist-downloads.adblockplus.org/fanboy-social.txt": {"off": false}},"dynamicFilteringString": "* * inline-script block\n* * 1p-script block\n* * 3p-script block\n* * 3p-frame block"}

This would result in all default 3rd-party filters, plus `Fanboy's Social Blocking list` being enabled.

Some time ago I noticed ads weren't being blocked on YouTube, but I didn't look further into it as first there didn't seem to be any problems on other sites (probably because I don't run Javascript by default). However, I have now investigated the problem and found out the only filter enabled is `Fanboy's Social Blocking list`. 

The following string makes everything work as expected, and maybe it's more resilient in case of the filter moving to a new URL:

    {"userSettings":{"advancedUserEnabled":true},"selectedFilterLists":["plowe-0","fanboy-social","malware-1","malware-0","easyprivacy","easylist","ublock-unbreak","ublock-privacy","ublock-badware","ublock-filters","user-filters"],"dynamicFilteringString":"* * inline-script block\n* * 1p-script block\n* * 3p-script block\n* * 3p-frame block"}

Can anyone tell when the change that made my configuration not work was introduced into uBlock Origin? I would like to know how long my systems have been vulnerable while not being protected by the default filters.

Browser: **Firefox  51.0.1**
Ublock Origin: **1.11.0**

**Comment by gorhill** [comment]
1.11.0, see <https://github.com/gorhill/uBlock/pull/2314>.

Looks like I did not test properly converting the old filter lists representation to the new one.

**Comment by spec1re** [comment]
I have a similar  problem with Chrome Version 57.0.2987.98 (64-bit) and uBlock Origin v1.11.2

![grafik](https://cloud.githubusercontent.com/assets/11883076/23851513/b3618968-07db-11e7-847a-944a9c2b78af.png)

The "`filterLists`" and "`selectedFilterLists`" doesn't apply anymore like before, but eg. "`netWhitelist`" still does?!

jocooza new "`adminSettings`" line doesn't work in Chrome.
