### ISSUE TITLE
overlays blocking

### ISSUE THREAD

**Issue by AddaxSoft** [gorhill/uBlock#2420]
I've searched the issues list about this feature but I couldn't find any relevant ticket about overlays.
Is this planned into implementing in the future?

An overlay example of many:
![image](https://cloud.githubusercontent.com/assets/6898938/23477977/07033f82-fec0-11e6-9740-6c5c6acfe7ff.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by anewuser** [comment]
@AddaxSoft Enable the Fanboy’s Annoyance List and report any missing overlay to the list maintainers (https://forums.lanik.us/).
