### ISSUE TITLE
Option to block 3rd party images only

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#2421]
Currently in the advanced pane it's possible to block all images from a certain website. Is it possible to add an option to block only 3rd party images similar how there is an option to block 3rd party scripts only? 

This would help increase privacy by reducing external connections on some sites where you only want to connect to a single first-party host and its images and not load 3rd party loaded images.

**Comment by gorhill** [comment]
> reducing external connections on some sites where you only want to connect to a single first-party host and its images and not load 3rd party loaded images

Just create a block rule for 3rd-party for these sites.

**Comment by grenzor** [comment]
But would that not also block 3rd party scripts/frames/css/etc as well? If I just wanted to block 3rd party images, that would require me to dynamically allow certain types of requests I want for the site to load properly (which could also inadvertently override and allow some blocked static filters). Let me know if I'm wrong in assuming this

**Comment by uBlock-user** [comment]
You will have to create a static filter

`||$third-party,image,domain=example.com`

**Comment by gorhill** [comment]
> But would that not also block 3rd party scripts/frames/css/etc as well?

Yes. So just noop whatever else 3rd-party domains you want to let in.

I'm going to decline adding yet-another row for something that can already be accomplished.

**Comment by anewuser** [comment]
@grenzor You may be interested in [uMatrix ](https://addons.mozilla.org/firefox/addon/umatrix/), another extension by the same developer. Please read the full description before installing it though.
