### ISSUE TITLE
Generic filter not working on fifth level domain

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2424]
I have noticed that generic filters are not working on a fifth level domain. I came up to notice this issue when some elements weren't hidden for which I already had a generic filter for.

**Error URL:** 
http://m.photogallery.navbharattimes.indiatimes.com/movies/international/the-great-wall/articleshow/56894001.cms

**How to reproduce?**
1. Create a generic filter `##img`
2. Go to above URL, you will notice the images still aren't hidden.
3. Add _**indiatimes.com**_ to the above generic filter to change it to` indiatimes.com##img`, the images will be hidden now.

_**Note:** Using Chrome 56 with uBO 1.11.0_

**PS:** The original filter I was working with was `##[id^="div-clmb-ctn"]` to hide the ads below the images. I have mentioned using ##img as it is a more generic filter.

**Comment by mapx-** [comment]
##img filter cannot work on that site due to the generichide filter in easylist
`@@||indiatimes.com^$generichide`

**Comment by gotitbro** [comment]
Thanks @mapx- , somehow I did not notice that in the logger.

Sorry for the trouble, closing the issue.
