### ISSUE TITLE
Main content of the page doesn´t appears when UBlock is enabled

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#2425]
**Ublok Origin Version 1.11.2
Firefox 51.0.1**

**Steps to reproduce:**

1.- Go to this page: http://www.imagenradio.com.mx/

2.- Clic on any article to open a new of the day, it could be the article that contains "IMAGEN INFORMATIVA".

**Actual results:**

1.- After open the article, the content appears but a white space appears on the left of the page

**Expected results:**

1.- The white space should show the content of the article, for example text an images.

**Note:**
If you disabled Ublock Origin  and refresh the page the content appears

**Ublock Enabled**
![01](https://cloud.githubusercontent.com/assets/16448984/23575855/38c8b984-005a-11e7-92da-c6929874b16b.jpg)
**Ublock Disabled**
![02](https://cloud.githubusercontent.com/assets/16448984/23575858/4965c930-005a-11e7-8df5-d25275d27f15.jpg)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
