### ISSUE TITLE
Long temporary hangs under ublock's safeObserverHandler in Firefox

### ISSUE THREAD

**Issue by jwatt** [gorhill/uBlock#2426]
uBlock initially works absolutely fine when I restore my Firefox session with hundreds of tabs open (most of the tabs are not actually loaded since I don't focused them after restoring a session). Over the course of a few days I will leave virtually all of the pre-existing tabs alone (not load them), but I will open and close many other tabs, roughly closing as many tabs as I open. In other words the number of tabs that are actually _loaded_ at any given moment doesn't really change. Nevertheless, over time Firefox will start to get temporary hangs that get longer and longer, even getting up to 10 seconds long if I allow them to before I restart Firefox.

Using the Gecko Profiler it turns out that the hangs are under uBlock's safeObserverHandler function. I don't know if uBlock is somehow keeping closed tabs alive and therefore the number of tabs that it runs is gets larger and larger, or if there is something else pathological about the mechanics of the code, but since the number of tabs that *should* be alive doesn't change much the performance shouldn't get progressively worse and worse.

I'm running uBlock Origin 1.11.2 with the default settings and filters that it comes with, in Firefox 51.0.1.

**Comment by gorhill** [comment]
Probably this: <https://bugzilla.mozilla.org/show_bug.cgi?id=1339572> ? (also <https://bugzilla.mozilla.org/show_bug.cgi?id=1338942> which I filed myself).

Underlying issue is <https://bugzilla.mozilla.org/show_bug.cgi?id=1334263>.

I have been pondering a possible solution in the past days to work around Firefox's expandos performance issue, I will need to work on a prototype as time allow.

**Comment by gorhill** [comment]
> Gecko Profiler it turns out that the hangs are under uBlock's safeObserverHandler

Could you provide more information about this? Web page URL? Also, what can you see if you keep drilling down about where it's most expansive? (including into Firefox's own code).

**Comment by jwatt** [comment]
Thanks for those links, I'll take a look!

As for the Gecko Profiler results, they look like this:

```
3335.0ms  Startup::XRE_Main
3335.0ms    Events::ProcessGeckoEvents
3325.0ms      Timer::Fire
3283.0ms        nsRefreshDriver::Tick
3139.0ms          js::RunScript
3050.0ms            safeObserverHandler (chrome://ublock0/content/js/contentscript.js:880)
 538.0ms              js::GCRuntime::collect
 167.0ms              js::Nursery::collect
 147.0ms              js::UncheckedUnwrap(JSObject*, bool, unsigned int*) XUL
 131.0ms              ...many more entries at the same level that are JS engine internals
```

Other than the 'safeObserverHandler' entry, there is no attribution to any specific pages by Gecko Profiler. (And the only entries that I can drill into any further are the 'js::GCRuntime::collect' and 'js::Nursery::collect' entries, and for both of them only for one more level, and there's nothing particularly useful in there unless you're well versed in JS engine internals.) I imagine that under 'safeObserverHandler' the code is working on all pages that it is hooked into, but you would know much better than I.

**Comment by gorhill** [comment]
I am pretty sure it's related to the sandbox's xrays issue, which issue become noticeable when having to iterate over large collections. Having a specific URL could help. Here is what I think is happening:

uBO uses an animation frame **and** a timer to collaesce DOM changes which must be handled.

When a tab becomes inactive, I believe animation frame will fired at lesser and lesser interval. This is a good thing, as it prevent uBO from unnecessarily processing DOM events while the DOM is not visible. In parallel to the animation frame, uBO also uses a time out, which is currently set at 20 minutes. The purpose of that timer is to be sure the DOM changes being coalesced do not pile up unduly and end up using too much memory -- they need to be serviced at some points (see #2147).

So the URL of the page where this occurs is key, this way I could confirm the hypothesis that a whole lot of DOM mutations have piled up and are being processed all at once when you switch back the the tab (causing the pending animation frame event to fire). Add to this the performance issue specific to Firefox with regard to xray vision in sandboxes, and this is the best hypothesis I can come up, I could put it to test with a specific URL.

If the hypothesis is right, the issue should not manifest itself on web pages which are not **very** dynamic -- that is unless another extension is not constantly modifying the DOM.

**Comment by jwatt** [comment]
Just so I understand correctly, when safeObserverHandler is called it is only operating on a single page? (Not all the pages uBO is hooked into?)

**Comment by jwatt** [comment]
I've now gone through the bugzilla bugs you linked above. Rather than [possibly] unnecessarily spending effort to debug this issue perhaps we should leave this issue on file and revisit it once those bugs are fixed?

**Comment by gorhill** [comment]
> when safeObserverHandler is called it is only operating on a single page? 

Yes, it's part of uBO's content script, it acts (and has permissions to act) **only** on the document in which it is injected.

**Comment by gorhill** [comment]
Closing this as there is no real case which can be reproduced/investigated, and this was concerning a now old version of FF.
