### ISSUE TITLE
[blockadblock.com] New Anti AdBlock, cause uBlock not Working

### ISSUE THREAD

**Issue by benyaminl** [gorhill/uBlock#2428]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When uBlock is present and working, it block the whole DOM and delete the DOM element of the page.. 

### One or more specific URLs where the issue occurs
I don't remember, but many site now use it.. it's annoying, they doesn't know why we block their ads because their ads is intrusive and contain many malaware, spyware, evenn virus and cuplrit of bandwith..
[URL(s) for issue on a specific site are **mandatory**]
blockadblock.com
### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/2817332/23585051/981dbdc0-01a5-11e7-81b6-9b9cdbbfc954.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
please add option to detect the js and delete it before it's executed... 
### Your settings
default and plus anti adblock killer

- Browser/version: 56.xxx -Chrome
- uBlock Origin version: 1.11.2

##### Your filter lists

overall list i check it, only for country I check IDN

**Comment by gorhill** [comment]
> please add option to detect the js and delete it before it's executed

This has been possible since a very long time.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by RoxKilly** [comment]
@benyaminl , the block you see does not use scripting but rather CSS animations. You can defeat it by using uBlock Origin's [element picker](https://github.com/gorhill/uBlock/wiki/Element-picker) to select and hide the block. This will create a rule that prevents the block from appearing again in the future.

For the page you linked, the following static filter can be added to the *My Filters* tab of uBO settings:
```
blockadblock.com###babasbmsgx
```
This will hide the DOM element that animates the block
