### ISSUE TITLE
Entering URL or search Term does not open up page. 

### ISSUE THREAD

**Issue by jknotzke** [gorhill/uBlock#2429]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
On OSX 10.12.3 using Chrome 56.0.2924.87 (64-bit) and Ublock Origin 1.11.2 (started with 1.11.1) when entering a URL directly into the URL bar, the browser does not attempt to load the page. You have to hit enter again.. This happens on various websites. When typing in a search key into the URL bar, google reformats the URL to the parameters requested for the search, but the page is never called to load the search results. 

This does not happen with Ublock Origin is disabled. This bug does not always happen, only sometimes. I haven't figured out what one must do to trigger it.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> the first step is to rule out filter-related issues.

What did you do to rule out filter-related issues?

**Comment by jknotzke** [comment]
I have no custom filters if that's what you are referring to. These are all filters that come right out of the box.

**Comment by gorhill** [comment]
Filter issues are an issue with any filter.

**Comment by gorhill** [comment]
> [Before you submit](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit)
> [...]
> 7. **Verify that the issue is not related to a 3rd-party filter lists.**

**Comment by gorhill** [comment]
Also

> when entering a URL directly into the URL bar, the browser does not attempt to load the page. You have to hit enter again

I am not aware of any feature which cause the browser to load the URL in the bar without hitting enter.
