### ISSUE TITLE
No Text on Settings-Buttons

### ISSUE THREAD

**Issue by allo-** [gorhill/uBlock#243]
On the about:addons page of the addon there are two buttons (dashboard, and devtools), which are both blank (no text on them at all).

Version: 0.9.1.0, german locale

**Comment by gorhill** [comment]
Browser version please.

**Comment by allo-** [comment]
34.0.5

**Comment by Betsy25** [comment]
All show fine here.

[Firefox 38.0.1](http://i.imgur.com/c9VfhBI.png)
[Firefox 41nightly](http://i.imgur.com/QtorUKZ.png)

**Comment by allo-** [comment]
Inspektor says:

    <setting xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" type="control" desc="" first-row="true">
    <vbox>
    <button id="showDashboardButton" label=""/>
    <button id="showNetworkLogButton" label=""/>
    </vbox>
    </setting>

**Comment by EchoDev** [comment]
Can you try switching to English locale and see if the problem is fixed?

FF39 with English locale here and it looks fine.

**Comment by gorhill** [comment]
Those strings are also in German: <https://github.com/gorhill/uBlock/blob/master/src/_locales/de/messages.json#L494>.

**Comment by allo-** [comment]
Happens on 38.0.1, too.

**Comment by gorhill** [comment]
If the issue was still there, possibly fixed with 9ce6f9eb23196b4b8b6617299c82385589d92983. Re-open if it still occurs.

**Comment by allo-** [comment]
Works for me.
