### ISSUE TITLE
Add a whitelist for all users.

### ISSUE THREAD

**Issue by dougunder** [gorhill/uBlock#2430]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I use this wonderful extension in a virtual public school.
I have 75 windows laptops(teachers and staff)  and 600 ubuntu notebooks(students) using it.
It would be fantastic if i could centrally add a url to a whitelist in the google admin portal.

Alternately can this be done with a script i could push out? Specifically for firefox as it lacks central management.

Currently I have users using Chrome with ublock origin and firefox sans adblock for when thats a problem.
  .
### One or more specific URLs where the issue occurs
k12.com 

There are others but this is the biggie. Kids cant get into their lessons due to an over active filter unless i manually add the url to a whitelist.

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Sign in to a K12.com account, try to attend class.
1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Default 
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
- uBlock Origin version: 
1.11.0
##### Your filter lists
Default
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin>.
