### ISSUE TITLE
Is it possible to redirect a blocked domain to about:blank or x.com

### ISSUE THREAD

**Issue by Travisi** [gorhill/uBlock#2431]
I'm trying to use ublock origin in the chrome browser to block domains so the block screen doesn't appear. Is there a way to make it so nothing appears at all and it just goes to about:blank or redirects to  x.com? 

What I see... https://i.imgur.com/d6F4fHu.png

What I want to see...https://i.imgur.com/3QqBXrW.png

**Comment by gorhill** [comment]
Not possible, uBO does not redirect to other URLs.

**Comment by lewisje** [comment]
Early in uBlock's history, @gorhill tried out minimal-content redirection and then determined that it was a bad idea, because of conflicts with other extensions: https://github.com/chrisaljoudi/uBlock/issues/18

**Comment by RoxKilly** [comment]
Allowing blocklists to do custom redirects also makes users vulnerable to malicious blocklist authors who could write rules to block legitimate sites (paypal.com) and redirect to forgeries (paypal.com.mysite.com)
