### ISSUE TITLE
Make possible to make exceptions from the logger.

### ISSUE THREAD

**Issue by kangarooo** [gorhill/uBlock#2432]
Make possible to make exceptions from the logger.
In logger when i fin what is blocked user wants to select and make action with it to add to exceptions like its possible in AdBlockPlus very fast and easy. Other wise user needs to learn how to make exception and since no one does that for a day to just do 1 simple thing then god hope they will know how to disable only one list of blocks and not all Adblocker or uBlock.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/The-logger#dynamic-url-filtering-rules>.

**Comment by kangarooo** [comment]
Maybe then this can be made bigger button. I never saw it. And a bit complicated. So then that Adblock plus idea can be implemented here also so looks intuitive and understandable. In logger what means green, red and gray and light gray and locked also needed explanation to understand what it means.

**Comment by gorhill** [comment]
As pointed out, it's already possible. Furthermore, ABP's approach of creating an exception filter merely from the whole URL is naive and can very often lead to pointless exception filters. Often URL have changing parts in them, so we can't always just use the whole URL to create an exception filter. Hence why uBO offers a list of URLs from which to choose from. Dynamic URL filtering allows for quick diagnosis to find out what works, and then static filtering can be used to craft a more permanent solution.
