### ISSUE TITLE
AAK Filters

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#2438]
Can you change url to AAK filters? I think that Reek resigned from writing filters. 

https://github.com/reek/anti-adblock-killer/issues/2927

@X01X012013 forked AAK filters and script. 
https://github.com/X01X012013/AdBlockProtector

**Comment by gorhill** [comment]
To me it looks like reeksite.com is just a leftover of an old era, I see `https://reek.github.io/anti-adblock-killer/` as being the official site, it's in the description at the top. The last update was Nov. 6, and before that Jul. 6., so there was a 4 month hiatus before the last update. We shouldn't conclude that Reek abandoned the project just yet.

**Comment by gorhill** [comment]
Reek's AAK was removed from stock filter lists: 651da715.

**Comment by MarcoSulla** [comment]
Well, I know AakList it's a dead project since 2016, but ***it still works***. uBlock anyway alerts that the filter is outdated. 

I think that re-adding it as an optional filter, disabled by default, can harm no one.
