### ISSUE TITLE
[Firefox] Events Pane in the Developer Tools does not work with uBlock enabled

### ISSUE THREAD

**Issue by TRowbotham** [gorhill/uBlock#244]
Hi,

First off, I just want to thank you for making this addon.  I am using Firefox 41 on Windows 7.  Completely disabling uBlock and restarting the browser makes the Events Pane work again.  I have about-scheme, behind-the-scene, and chrome-scheme in my whitelist, but none of them seem to make a difference.  Please let me know if I can provide you with any additional information.

Steps to reproduce:
1) Go to https://bugzilla.mozilla.org
2) Open the Developer Tools and select the Debugger tab
3) Select the Events Pane[1] in the Debugger window

Actual Results:
No events show up in the Events Pane.

Expected results:
All events bound to DOM nodes should appear.

[1] https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Events_pane

Here is the error that is output to the Browser Console in case you find it useful.

```
_getDefinitionSite threw an exception: Error getting function definition site: server1.conn4.pausedobj57 has no Debugger.Script DevToolsUtils.js:58:0

Handler function DebuggerClient.requester request callback threw an exception: TypeError: aResponse.source is undefined
Stack: EventListeners.prototype._getDefinitionSite/<@chrome://browser/content/devtools/debugger-controller.js:1834:7
DebuggerClient.requester/</<@resource://gre/modules/devtools/dbg-client.jsm:353:9
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
Request.prototype.emit@resource://gre/modules/devtools/dbg-client.jsm:1219:29
DebuggerClient.prototype.onPacket@resource://gre/modules/devtools/dbg-client.jsm:1036:7
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
EventLoop.prototype.enter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:373:5
ThreadActor.prototype._pushThreadPause@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:558:5
ThreadActor.prototype.onInterrupt@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:1392:7
DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1456:15
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
Line: 1834, column: 6 DevToolsUtils.js:58:0
```

**Comment by TRowbotham** [comment]
I did some additional testing and found:
-This problem has existed since the first uBlock release for Firefox. (tested with version 8.5.4.0-beta.0)
-This is still a problem even with all filters disabled in uBlock Origin.
-Does not occur when using the same filters in Adblock Plus.
-This occurs in at least Firefox version 36+ (I didn't test any further back)
-Toggling Firefox's multiprocessing mode (e10s) has no effect either.

I filed a bug with Firefox on the issue a few months ago, but it hasn't seen any action.  https://bugzilla.mozilla.org/show_bug.cgi?id=1145996

**Comment by gorhill** [comment]
> I filed a bug with Firefox on the issue a few months ago, but it hasn't seen any action

Yes I saw this, and it's unclear whether uBlock does something wrong or whether Firefox does something wrong. uBlock works differently than ABP, so the fact that ABP does not have this problem is not an indication uBlock is at fault. The important most error message is the first one:

> _getDefinitionSite threw an exception: Error getting function definition site: server1.conn4.pausedobj57 has no Debugger.Script DevToolsUtils.js:58:0

I will have to find `DevToolsUtils.js` in Mozilla's source code and see if I can see why the message occurs.

**Comment by TRowbotham** [comment]
The bug I filed has now been duped against https://bugzilla.mozilla.org/show_bug.cgi?id=942899, which is said to have been a regression from https://bugzilla.mozilla.org/show_bug.cgi?id=905700.  I'm going to go ahead and close this since this appears to be a Firefox issue.  I appreciate any time you may have spent looking into this.
