### ISSUE TITLE
Dynamic URL Filtering fails to take precedence over Dynamic Filtering for worker requests in Firefox 52

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2440]
### Describe the issue
Dynamic URL filtering rule is not working as expected for `worker` requests in `Firefox 52 / uBO 1.11.2`; it does not take precedence over the dynamic filter as it should.  I have the following rules:
```
* google.com * block
* https://www.google.com/recaptcha * noop
```
While most network connections to `www.google.com/recaptcha` are allowed as expected, the logger reports that connections of type `worker` ignore the noop and only listen to the block rule.

### One or more specific URLs where the issue occurs

[Here's an example](https://gooligan.checkpoint.com/).  I even tried adding the `allow` rule below but the worker connection was still blocked according to the logger
```
gooligan.checkpoint.com https://www.google.com/recaptcha worker allow
```

### Screenshot in which the issue can be seen

The first line below:

![1](https://cloud.githubusercontent.com/assets/12346501/23786112/1c0313e2-0539-11e7-94f6-f56dcd760c5e.png)

You can't see from this screenshot, but the two noop requests immediately under the worker (inline-script and frame) have the exact same URL as the worker request; could all three lines be referring to the same request?

### Steps for anyone to reproduce the issue

1. Add the two rules near the top
2. [Visit this URL](https://gooligan.checkpoint.com/) with 1st party script enabled
3. Open the logger

### Your settings

- Browser/version: Firefox 52
- uBlock Origin version: 1.11.2

##### Your filter lists
Default lists + Anti-Adblock Killer - Malware lists

**Comment by Atavic** [comment]
>could all three lines be referring to the same request? 

Yes, there's a .js inside a frame.
And usually recaptcha has a CSS style in head section.

**Comment by gorhill** [comment]
The issue is uBO is testing whether workers are allowed on the page using a hard-coded `blob:` URL (see issue <https://github.com/gorhill/uBO-Extra/issues/19>). This is a trick used for now since there is no such thing as a `worker` request type.

I thnik the proper fix here is to be sure dynamic filtering will not cause an anti-worker CSP to be injected, only static filtering should cause anti-worker CSP to be injected.
