### ISSUE TITLE
Static filtering / Match by query string

### ISSUE THREAD

**Issue by dogancelik** [gorhill/uBlock#2442]
A site uses several domains to open spam links, but they keep changing, yet the site always open spam links with `affId=1919&instId=1733`.
That's why I want to block any URL that has `affId=1919&instId=1733` in its query part.

```
(spam links, don't open)
http://someworks.info/?ad=4&affId=1919&instId=1733&trackId=999123
http://get.uencedrefortifica.bid/?ad=5&affId=1919&instId=1733&otherStuff=1234
```

I checked both documents of uBlock and AdBlock for blocking these URLs by matching query.
I tried these and they did **not work ⭕️**:

```
||*affId=1919&instId=1733*
*affId=1919*
||*^*affId^1919^instId^1733*
||*^*affId=1919&instId=1733*
```

[`^` = seperator character in AdBlock rule](https://cloud.githubusercontent.com/assets/486818/23825313/f2df54f0-068f-11e7-82d4-6e1c67842cd6.png)

**This works ✅ because RegExp:**

```
/.*affId=1919&instId=1733.*/
```

Does uBlock ignore query segment of URLs in non RegExp rules? Am I missing something?

Can we add an option after **$** to include query in pattern search?

**Comment by anewuser** [comment]
You've ignored and deleted the template text that appears when you create a new issue.

That text isn't there just for decoration. Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by dogancelik** [comment]
I'll include browser and add-on version. Can this not be a bug?
