### ISSUE TITLE
URL is truncated

### ISSUE THREAD

**Issue by uihdff** [gorhill/uBlock#2443]
### URL is truncated
Is it possible to view the complete truncated URL when hovering the mouse pointer over it ?

### Screenshot in which the issue can be seen

![block](https://cloud.githubusercontent.com/assets/22044303/23829949/cdba4910-06d4-11e7-806a-de0915ecca3d.jpg)

### Your settings

- Browser/version: Firefox 51.0.1
- uBlock Origin version: 1.11.2

**Comment by anewuser** [comment]
You've ignored and deleted parts of the template text that appears when you create a new issue. That text isn't there just for decoration.

**Comment by gorhill** [comment]
The purpose of the template is really to emphasize how making the case is important, but in the end what really matters is making the case, and it was made here.

**Comment by gorhill** [comment]
This was fixed eventually, probably with the redesigned popup panel, thus closing as obsolete.
