### ISSUE TITLE
WebAssembly in latest Chrome and Firefox. Are we ready?

### ISSUE THREAD

**Issue by byaka** [gorhill/uBlock#2444]
[Changelog of Chrome 57](https://blog.chromium.org/2017/02/chrome-57-beta-css-grid-layout-improved.html)
[Changelog of Firefox 52](https://www.mozilla.org/en-US/firefox/52.0/releasenotes/)

So new security hole enabled by default in major browsers. Are we ready for this?
Is UBlock can block this? For example via Dynamic-filtering's panel.
Or WebAssembly **always** adding to page via standard `<script type='text/javascript'>` tags only (i mean always initiating from js)?

**Comment by gorhill** [comment]
http://webassembly.org/docs/js/
