### ISSUE TITLE
Disable the tab which appears after prevention from loading

### ISSUE THREAD

**Issue by dex73r** [gorhill/uBlock#2445]
Is there any way to disable the tab, permanently?   
The tab that pops up after **uBlock Origin has prevented the following page from loading:**   

It only annoys me, nothing more, if it's on the list of blocked sites, let it be there.   
I've tried to look for the solution, but what I found was disabling the strict blocking which I don't want. I want to block the site, but I don't want the choice whether to unlock or no.

**Comment by gorhill** [comment]
No, the purpose of strict blocking is not to automatically close tabs, the purpose is to prevent all connections to a remote server and inform the user. Create fitlers with the `popup` filter option to automatically close tabs.

**Comment by axsk** [comment]
I have the same problem and not encountered a single case where I actually wanted to load the page. An option along the lines of "Do not open blocked tabs" would be great.
