### ISSUE TITLE
Unable to remove/modify dynamic filter when using wildcard

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#2447]
### Describe the issue & how to reproduce

When you add a dynamic filter from the logger with context to * and type to * it is fine. After that try modifying/removing the dynamic filter and the lock icon will appear to save changes but you can't click on it.

Then you have to manually go to "My Rules" in dashboard and find the rule you're trying to change. In permanent rules will be the URL of the filter you created but in temporary rules it will be a blank line respective to it. You have to get rid of the blank line in temporary rules then commit to delete the filter.

Note: I only tested with * context and type but it may happen with others as well

### One or more specific URLs where the issue occurs

Looks like it can happen on any URL. Try dynamically blocking https://github.com/gorhill/uBlock doc type with * as context and * as type in logger. Then try removing the filter

### Your settings

- Browser/version: Firefox 52
- uBlock Origin version: 1.11.2

Using default filter lists.

**Comment by gorhill** [comment]
Provide a real case please to make me understand the issue.

**Comment by okiehsch** [comment]
I think I can reproduce.
1. Go to `https://github.com/gorhill/uBlock`
2. Block the `inline-script` via dynamic url-filtering and change the context and type to `*`
![unbenannt](https://cloud.githubusercontent.com/assets/16838044/23882565/c1dca5a0-0861-11e7-9991-ecb2cb3cd05e.PNG)
3. Click the padlock to make the rule permanent.
4. Reload
5. Try to remove the `inline-script` block via dynamic url-filtering.
![unbenannt1](https://cloud.githubusercontent.com/assets/16838044/23882658/699ec2e6-0862-11e7-99bb-5c9b434f834c.PNG)
6. Click the padlock to make the change permanent.
7. Result: The padlock icon is not responsive, you have to remove the  `inline-script`  block via
"My Rules" in  the dashboard.
