### ISSUE TITLE
Google APIs (and others) are getting through uBlock???

### ISSUE THREAD

**Issue by uBlockUser** [gorhill/uBlock#245]
First, I don't know if this is an issue, I would use forums if there were some.

But this got me wondering about my privacy...

I use HTTPS Everywhere with uBlock, and HTTPS Everywhere shows, that there's an established HTTPS connection to Google APIs (and others), even if they're blocked by uBlock...

For example when you go to www.gog.com, there's a "fonts.googleapis.com" & "google-analytics.com". My lists block them, and I even blocked them with dynamic filtering. Yet HTTPS Everywhere makes a connection to Google APIs...

BUT! When I try Adguard or Adblock Plus, with the same lists, or just blocking these two manually, the Google APIs is completely gone in HTTPS Everywhere... No connection. But with uBlock, it still makes connection.

I guess this is why someone said this:
"ublock blocks ads just like adblock plus, but triggers the ads API to think it got viewed"

And you said this:
"Completely false. uBlock Origin (and uBlock) does not "trigger" any "ads API" (whatever that is). It prevents network requests from being made according to filter lists so that your browser does not connect to remote servers, period."

I hope there's some good explanation to this, I'm worried about my privacy.

I'm using uBlock Origin 0.9.7.5. (It even happens with the other uBlock, just to make it clear).

EDIT: Also, If I block those items with uBlock for example, uBlock Origin still shows that these items are still there to block. But when I block them with Adguard or Adblock Plus, uBlock and uBlock Origin won't even find them anymore...

**Comment by uBlockUser** [comment]
Just adding images to better explain...
1) When one uBlock already block them:
![screenshot - 27 5 2015 - 15 17 39](https://cloud.githubusercontent.com/assets/12626866/7836972/9c77b2e2-0484-11e5-9499-e8ef2f309e01.png)
![screenshot - 27 5 2015 - 15 18 02](https://cloud.githubusercontent.com/assets/12626866/7836981/ac6d9f54-0484-11e5-9c4c-41abe63faeac.png)

2) Now when Adblock Edge blocks them:
![screenshot - 27 5 2015 - 15 22 28](https://cloud.githubusercontent.com/assets/12626866/7836997/c1769f36-0484-11e5-912d-b1a6b9c9503a.png)
![screenshot - 27 5 2015 - 15 22 45](https://cloud.githubusercontent.com/assets/12626866/7837014/d6451cb2-0484-11e5-921b-65cc88f1c916.png)

**Comment by gwarser** [comment]
I suspect that they are executed in alphabetical order...

**Comment by uBlockUser** [comment]
What do you mean? I'm not talking about that...

When you use uBlock, and block something, other blockers still find that items to block, and even HTTPS Everywhere makes a connection to Google APIs and others.

But when you use for example Adblock Edge, uBlock won't find these items anymore, and HTTPS Everywhere won't even connect to Google APIs.

OR are you saying that HTTPS Everywhere first kicks in before uBlock, and that's why it makes a connection, but uBlock blocks it anyway? Wouldn't the entry dissapear from HTTPS Everywhere?

I bet it's not that... Even the second uBlock will find the items, when they are already blocked by the first one, but I don't know about Adblock Edge/Plus. I have to test it.

But as you see, when you block with Adblock Edge, uBlock Origin and HTTPS Everywhere won't find it anymore. But if you block them with uBlock, uBlock Origin and HTTPS Everywhere finds them.

**Comment by quilloss** [comment]
It does block Google APIs, check the network log. HTTPS Everywhere just detects it first.

**Comment by gorhill** [comment]
> I hope there's some good explanation to this, I'm worried about my privacy.

Check Firefox's network pane in the dev console. You won't get arbitrary results because of whatever order add-ons are called.

**Comment by Snapy** [comment]
@uBlockUser  @quilloss is right.
I checked with both uBlock's logger and Firefox Network Inspector (<kbd>F12</kbd> > `Network` Tab) using this rule `www.gog.com fonts.googleapis.com * block` and the logger reported the connection as blocked whereas the network inspector doesn't show any connection to Google APIs.
Depending on whether uBlock was installed/enabled before/after HTTPS Everywhere, it will do its job in a different order. Here are the two possible cases you encountered :
- HTTPSEW intercepts the http (or just sees the https) connection to Google APIs and reports it in its UI
- uBlock then blocks afterwards the connection  
**OR**
- uBlock intercepts the http(s) connection to Google APIs and blocks it therefore HTTPSEW doesn't see the connection and doesn't report it in its UI  
In both cases your browser **doesn't** connect to Google APIs and your privacy is respected.

**Comment by uBlockUser** [comment]
Thanks a lot for your answers. Sorry if I wasted your time! :) I love uBlock, just found about it few weeks ago. And I saw improvements in speed (my computer is slow).

So there isn't any leakage then. Google doesn't know I visited the page.

But how's that I can see the entries in uBlock Origin, if they are already blocked with the another uBlock? Since I can't see them in uBlock with Adblock Edge enabled...

**Comment by CrisBRM** [comment]
@uBlockUser You're only supposed to use ONE blocker. Disable the ones you're not using or you'll incur a massive performance penalty.

**Comment by uBlockUser** [comment]
I am...... I was just testing this.

**Comment by CrisBRM** [comment]
Even then, you're not supposed to test like that. You have to disable the other blockers in the addons menu for reasons stated in this thread.

**Comment by uBlockUser** [comment]
If you check my screenshots, the second blocker is disabled..

**Comment by logos88** [comment]
In the page of Disconnect they say that the order of installation has to be different in each browser.

"Will Disconnect Private Browsing work if I have multiple blocking extensions installed?
It depends on which browser you are using. On Internet Explorer, Disconnect will work fine even if you have multiple blocking extensions installed. On Firefox, if Disconnect is the first blocking extension you install, then Disconnect will work even if you subsequently install other blocking extensions. On Chrome, Safari, and Opera, it’s the opposite: in order for Disconnect to work on these browsers, it must be the most recent blocking extension installed. We know, it’s silly. And we’d change it if we could. But unfortunately, this weirdness is a function of the browser software, not ours".

https://disconnect.me/help#will-disconnect-private-browsing-work-if-i-have-multiple-blocking-extensions-installed

**Comment by gorhill** [comment]
> But unfortunately, this weirdness is a function of the browser software, not ours

Why would the order matter? Is it redirecting HTTP requests? At most, on Firefox, the order would affect which extension block first, and so only the _reporting_ of what is blocked would be affected. And for Chromium-based browsers, it makes no difference which is installed first or last, unless the extension redirect HTTP requests.
