### ISSUE TITLE
Cannot open Reddit.com comment links with uBlock Origin enabled

### ISSUE THREAD

**Issue by TridentTrue** [gorhill/uBlock#2452]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
With only uBlock Origin installed whenever you click on a reddit comment link it immediately closes

### One or more specific URLs where the issue occurs
https://www.reddit.com/r/aww/comments/5z4x7y/my_five_dogs_may_be_very_different_but_they_are_a/

### Steps for anyone to reproduce the issue

1. Have only uBlock Origin enabled in extensions.
2. Navigate to https://www.reddit.com/
3. Attempt to cick on a comment link

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chrome Version 56.0.2924.87 (64-bit)
- uBlock Origin version: uBlock Origin v1.11.2

##### Your filter lists
Default filter lists

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by VictorHartman** [comment]
I also have this issue, except only when opening comment link in a new tab. I found out that **easylist** is the problem.

**Comment by VictorHartman** [comment]
Easylist has fixed the issue, so go to your 3rd-party filters and Purge and Update them.
