### ISSUE TITLE
Adding dummy Websocket?

### ISSUE THREAD

**Issue by IsraeliAdblocker** [gorhill/uBlock#2453]
### Describe the issue
I would like to know if it's possible to add dummy Websocket redirect like we are doing with scripts and images (307).
let's take sport5.co.il for example with HebrewList filters, they are detecting the CSP by using try catch on the websocket creation and then they just remove the entire images of the article.

I've struggled myself whether to post it here or on ublock assets but since I saw there is no possible way to redirect websocket, I thought that the best place would be here.

### One or more specific URLs where the issue occurs
http://www.sport5.co.il/articles.aspx?FolderID=64&docID=238673&lang=HE

### Screenshot in which the issue can be seen
![sport5](https://cloud.githubusercontent.com/assets/19405330/23894254/12c8b16e-08aa-11e7-9d39-2790601593ac.png)

### Steps for anyone to reproduce the issue

1. just surf the website.

### Your settings
Ublock for chrome with HebrewList

- Browser/version:  chrome 56
- uBlock Origin version:  1.11.2

##### Your filter lists

Easylist + HebrewList

##### Your custom filters (if any)
none

**Comment by uBlock-user** [comment]
Locking `wsBlocked` variable works fine

add - `sport5.co.il##script:inject(abort-on-property-read.js, wsBlocked)`

**Comment by IsraeliAdblocker** [comment]
without the HebrewList and only adding `sport5.co.il##script:inject(abort-on-property-read.js, wsBlocked)` isn't working and I can see ADS from websocket (IL ip).
with HebrewList and the rule sport5.co.il##script:inject(abort-on-property-read.js, wsBlocked) I can still see content blocked same as seen in the screenshot.

**Comment by okiehsch** [comment]
`sport5.co.il##script:inject(abort-on-property-read.js, wsBlocked)` works on my end with 
Easylist + HebrewList, Chrome 57 uBO 1.14
The websocket CSP is injected and the pictures are visible.
![il](https://cloud.githubusercontent.com/assets/16838044/23925021/9daed55c-090d-11e7-9922-31d6502357eb.JPG)

**Comment by uBlock-user** [comment]
@IsraeliAdblocker Remove site data and all cache related to the website and then try again.

**Comment by gorhill** [comment]
Filter issues **must** always be filed at uAssets. If ever there is a case which can't be addressed using all the existing blocking arsenal, then I will decide whether extending uBO is required or not.
