### ISSUE TITLE
[possible data loss] Firefox webext 1.11.3.b2 auto updated to 1.11.5b0 and rules are lost

### ISSUE THREAD

**Issue by sfleiter** [gorhill/uBlock#2454]
After an update from Firefox uBlock Origin webext 1.11.3.b2 to uBlock Origin 1.11.5b0 all "My Rules" are lost.

How to reproduce:

On Firefox Nightly Mac 55.0a1 (2017-03-13) (64-bit) install uBlock Origin 1.11.3.b2 in the **webextension** version.
Have "I am an advanced user" activated and some own "My Rules" configured
Have all settings be migrated in your profiles extension-data folder.

Under Menu Tools -> Addons choose gear icon -> Check for updates.
uBlock Origin is updated to 1.11.5b0.
What is especially remarkable is that the "uBlock origin could not be verified..." message is gone,
so I assume the installed version is the one from addons.mozilla.org and is **not** the **webext** version.
Setting "I am an advanced user" is deactivated and "My Rules" are reset to default.

When installing the webext version from here https://github.com/gorhill/uBlock/releases/download/1.11.5b0/uBlock0.webext.zip over it, it takes quite some time, the addon initializes again and the "My Rules" are back again.
I assume the data is migrated again in that case and maybe "My Rules" modifications done after the initial migration are lost.

What to change:

The bug is probably that the webext version is updated to the non webext version (from addons.mozilla.org). That should not happen.
If possible there should be a firefox and a webext version at addons.mozilla.org and updates should not happen between those 2.

Thanks and regards, Stefan

**Comment by gorhill** [comment]
You can't mix webextension data with legacy data, see [Release notes](https://github.com/gorhill/uBlock/releases).

**Comment by sfleiter** [comment]
I am not sure whether I understand what you want to say.
The really long installation time and the resource drag during that time made it look like the migration was happening again, but that's only a weak sign, I know.

The problem that after an automatic Addon update by Firefox all "My Rules" are (or seem to be) lost until you reinstall the (newest) webext version persists though.
Would be nice if this could be fixed since this will probably happen from now on with every release of uBlock Origin to addons.mozilla.org...

**Comment by gorhill** [comment]
I will change the extension id for now, but this will create an issue for when the webext is officially released for those already using the webext version -- they will have to backup in old extension id and then restore to the new (official) extension id.

**Comment by sfleiter** [comment]
Sounds like a fine interim solution to me.
Thanks a lot for your work and the quick reaction!
