### ISSUE TITLE
Reddit commet sections can't be opened with Ublock active

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [gorhill/uBlock#2455]
### Describe the issue
Trying to go into any comment section of any thread on reddit is not possible either by pressing on the "comment" link or middle-click the mouse (new tab). The tab simply opens and imediately closes.

### One or more specific URLs where the issue occurs

https://www.reddit.com/r/movies/comments/5zgzrj/disney_refuses_to_cut_gay_moment_from_beauty_and/

Edit: Strangely I can enter this from here. But on reddit.com , going into "comment" doesn't work.

Workaround 1): Open new tab, copy the "comment" url, paste into new tab, press enter.
Workaround 2): Left click "comment", press "open in new tab".

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chromium 59.0.3042.0
- uBlock Origin version: uBlock Origin v1.11.4

##### Your filter lists

all ublock filters, All ads, all privacy, all malware domains, all social and all multipurpose

**Comment by ahjorth** [comment]
Go to `Settings | Third Party Filters` and `Purge All caches` then `Update Now` 

One of those filters broke it and fixed it after a few hours. The above worked for me

**Comment by Unrepentant-Atheist** [comment]
That did indeed fix it. Much obliged!
