### ISSUE TITLE
Firefox: browser pref combo unexpectedly globally prevents popup window closure

### ISSUE THREAD

**Issue by blakestorm11** [gorhill/uBlock#2458]
### Describe the issue
Popup window closure by uBlock Origin in **Firefox 52** fails at *all* applicable sites when browser preferences are set as follows:
**browser.tabs.closeWindowWithLastTab** == *false*
**dom.disable_window_open_feature.toolbar** == *true*

(IIRC the issue actually started with Firefox 51, but it took me a while to get annoyed enough to investigate the cause and I no longer have FF 51 installed now.)

Disabling **browser.tabs.closeWindowWithLastTab** is an essential feature for me, so for now I've toggled the less essential **dom.disable_window_open_feature.toolbar** as a workaround. Why the toolbar setting should affect any of this is a mystery - but it does...

### One or more specific URLs where the issue occurs
Happens everywhere; convenient site for testing:
http://jessehakanen.net/adblockpluspopupaddon/test.html

All tests opening a new window (4-8) fail with the filter
||google.*^$popup

### Steps for anyone to reproduce the issue
1. Create a brand new profile for Firefox 52.0
2. Install uBlock Origin from AMO
3. Add filter:
||google.*^$popup 
4. Visit the URL above.
5. All tests work.
6. Set these preferences in *about:config*:
**browser.tabs.closeWindowWithLastTab** to *false*
**dom.disable_window_open_feature.toolbar** to *true*
7. Tests that open a new window (4-8) now fail.

**NOTE**: Setting either of these preferences separately doesn't trigger the issue, only setting both does.

### Your settings
- Browser/version: Firefox 52.0 (tested on Win7 & WinXP)
- uBlock Origin version: v1.11.4 from AMO

All settings are default.

##### Your filter lists
Default.

##### Your custom filters (if any)
! for testing:
||google.*^$popup

**Comment by gorhill** [comment]
It does not look unexpected to me given what these two settings do, rather the opposite: expected.

You are asking Firefox to not close a window after the last tab has been closed. This is what Firefox is doing, it opens a new tab after the last one has been closed, and keeps the window opened, as mandated by your `about:config` settings.

**Comment by gorhill** [comment]
I see that ABP does close the window despite the settings.

I had a similar issue reported for Sea Monkey a long time ago, but I had to reverse the fix, as in some circumstances this was causing the current window to close, due to `popunder` filters.

**Comment by blakestorm11** [comment]
What you're saying (about this not being unexpected) would make sense if **browser.tabs.closeWindowWithLastTab** *alone* was enough to cause this behavior, but that is not the case now and never has been.

**dom.disable_window_open_feature.toolbar**, however, "prevents the navigation toolbar from being hidden" in a popup window, which should have absolutely nothing to do with whether the window can be closed or not.

Also, I've had these settings for years with no problems, including no problems with uBlock until FF 51 or so. I'm not even saying this is something you caused, probably Mozilla guys broke something (they're going out of their way to do that these days...), but the toolbar setting being the trigger is just plain bizarre for me. If you're not interested in fixing this, I can live with the workaround, I just thought you'd find this curious enough to investigate.

**Comment by gorhill** [comment]
> `dom.disable_window_open_feature.toolbar`, however, "prevents the navigation toolbar from being hidden" in a popup window, which should have absolutely nothing to do with whether the window can be closed or not.

I think the behavior make sense from Firefox point of view. `dom.disable_window_open_feature.toolbar` causes popup windows to be tabless, so closing the tab is equivalent to closing the window. When `dom.disable_window_open_feature.toolbar` is true, Firefox will then lookup the setting `browser.tabs.closeWindowWithLastTab` to decide whether to keep the window opened or not.

**Comment by blakestorm11** [comment]
But uBlock closes the popup _window_ (right?), so what difference would it make if it has tabs or not?

**Comment by gorhill** [comment]
uBO closes the tab, not the window.

**Comment by blakestorm11** [comment]
OK then, if that's the case, it does make a certain amount of sense for this to happen. I figured you'd close on the window level.

So, I take it you're not terribly interested in doing anything about this at this point? Maybe leave this open for a while, though, in case more interest is shown?

**Comment by gorhill** [comment]
> I take it you're not terribly interested in doing anything about this at this point?\

Right. As said, trying to make uBO too "smart" was bringing other issues with SeaMonkey, like the current window closing in some cases of popunder (I can't remember where this was reported).

The window-closing code was removed in 73c8a96c.

**Comment by gorhill** [comment]
This is a legacy-specific quirk, and only when specific `about:config` settings have been tampered, so not worth for me to spend time on this.
