### ISSUE TITLE
Ad-choices on this site seems to somehow survive Ublock

### ISSUE THREAD

**Issue by DrReD** [gorhill/uBlock#246]
Tested on Opera, Chrome and Firefox.
http://www.ubuntugeek.com/install-freeradius-on-ubuntu-15-04-server-and-manage-using-daloradius-freeradius-web-management-application.html

![ubuntu geek](https://cloud.githubusercontent.com/assets/4643253/7850160/8a40d018-04de-11e5-9548-15bf1ef712d5.png)

**Comment by gorhill** [comment]
Unable to reproduce with Chromium, neither with Firefox, using default filter lists.

**Comment by gorhill** [comment]
Ok I just reproduced, not sure how, maybe refreshing the page.

**Comment by gorhill** [comment]
I can also reproduce with ABP + EasyList + EasyPrivacy.

**Comment by gorhill** [comment]
It's a 3rd-party filter list issue. This needs to be blocked:

    ||ajax.cloudflare.com/cdn-cgi/nexp/dok3v=7e13c32551/cloudflare.min.js

I don't if there are side effects though. Report to EasyList maintainers: https://forums.lanik.us/viewforum.php?f=62

**Comment by DrReD** [comment]
1) Damm you're FAST...
2) Reported to EasyList maintainers as requested.
3) Thanks for this awesome blocker!
