### ISSUE TITLE
UBlock conflicts with "Reddit Enchancement Suite" in Chrome, unable to open links in new tab.

### ISSUE THREAD

**Issue by staviq** [gorhill/uBlock#2461]
### Describe the issue

This happens in Chrome, when Ublock extension is used on "reddit.com" with "Reddit Enchancement Suite" extension.

When browsing reddit.com, "Open link in new tab" basically does not work, ALL links pointing to reddit.com are blocked and tab closes itself.

It does not happen when i copy and paste the url into the new tab manually.

It does not happen when i "Open link in new Window".

### One or more specific URLs where the issue occurs

https://www.reddit.com/r/pics/comments/5zxmij/my_dad_is_retiring_today_after_44_years/

### Steps for anyone to reproduce the issue

All those steps are peformed on default, non customised settings for both extensions.

1. Open Chrome, and have those extensions installed and enabled:
    - Ublock Origin
    - Reddit Enchancement Suite
2. Go to "reddit.com"
3. Either use middle mouse button, or select "Open in new tab" on any link below a post, saying "[number] comments"
4. Link opens in a new tab and the tab closes itself immediately.

### Your settings

- Browser/version: Google Chrome Version 57.0.2987.110
- uBlock Origin version: uBlock Origin 1.11.4

##### Your filter lists

As default as possible, i have never customized any settings for uBlock.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
