### ISSUE TITLE
"script:contains" doesn't work with "rocketscript"

### ISSUE THREAD

**Issue by ayuanx** [gorhill/uBlock#2463]
Basically, CloudFlare changes all "javascript" tags to "rocketscript" and interpret them using its own js. This effectively breaks the feature of "script:contains".

I don't want to directly block CloudFlare's own interpreter js, because most of the time I still need certain scripts running to load the page. I only need to selectively disable unwanted ones with "script:contains" feature.

Is there a solution to this "rocketscript"?

In fact, this "script:contains" feature is the sole reason I am using uBO instead of ABP.

PS: Honestly I couldn't care less about the performance or memory, which, in my humble opinion, should not be the main focus of uBO. In these days, with i7+16GB everywhere, only functionality matters. The ms speed difference or MB memory difference are really negligible, otherwise we should all use lean Opera or alike that use least of resource, which proved to be virtually dead because nobody cares about them.

Even if uBO costs twice more time and memory than ABP, as long as it still has more functionality, I will choose to use it.

**Comment by ayuanx** [comment]
I would be nice if we could have a text based filter when the file is fetched from network. As long as we can remove some words from a script so that it won't work later when executed, we have achieved our goal to block it.

A further enhancement would be to be able to search and replace text after the file is fetched from network, just before anything is executed.

**Comment by toshiya44** [comment]
inline-script filtering works on Firefox only.

**Comment by ayuanx** [comment]
Oh, I forgot to mention that everything is based on Firefox.

**Comment by toshiya44** [comment]
Which version of firefox? Which version of uBO?
Where are the example URLs where this issue occurs and the filters you tried?

**Comment by ayuanx** [comment]
Example:
Try to disable the inline rocketscript by using "script:contains(GoogleAnalyticsObject)" on http://www.mekameleen.tv/

Or try to disable any inline rocketscript on http://einfogames.com/boards/. There are tons of it for you to experiment on this site.

Focus on the "inline rocketscript" only, and use "script:contains()" method only.

**Comment by toshiya44** [comment]
I tried
```
mekameleen.tv##script:contains(GoogleAnalyticsObject)
mekameleen.tv##script:contains(CloudFlare)```
Both worked

**Comment by ayuanx** [comment]
No, do NOT disable CloudFlare itself!

You are supposed to disable only this **inline rocketscript** as listed below:

<script type="text/rocketscript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-47294628-1', 'mekameleen.tv');
  ga('send', 'pageview');
</script>

**Comment by toshiya44** [comment]
Dude, i told you both worked didn't I? Can you read?

**Comment by toshiya44** [comment]
and you still haven't told me which version of softwares you're using.

**Comment by ayuanx** [comment]
The purpose is to disable only one single targeted rocketscript, not all of them!
Look at your filter `mekameleen.tv##script:contains(CloudFlare)`, you disabled the interpreter, which basically destroyed all rocketscripts.

Firefox 52.0.1 (64-bit) + uBlock Origin v1.11.4

**Comment by ayuanx** [comment]
I guess you have to turn off the default filter list first as I believe most Analytics sites are in the default filter list.

**Comment by uBlock-user** [comment]
First, `script:contains` feature is based on BeforeScriptExecute event which is set to deprecate in Web Extensions so you shouldn't be using that. Second, `$inline-script` flag works just fine regardless of script tags.

**Comment by ayuanx** [comment]
Yes `$inline-script` works, but that kills everything which makes it most of the time useless as more and more sites use scripts to load contents and pictures.

We need a feature to selectively disable inline scripts, as I can almost predict that all anti-adblock are going to be implemented as inline scripts eventually, rendering all current URL based anti-adblock software useless.

**Comment by uBlock-user** [comment]
Use `script:inject` and kill specific properties via scriptlets - https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt

**Comment by ayuanx** [comment]
That's not a bad feature but it doesn't allow me to inject my own script.

And most of the time, it is really not worthwhile to write and inject a fully functioning script just in order to cancel another one.
Because the web editors can change their anti-block script 12 times per day, since that is their paying job and they have all the time on the world to do that everyday.

What we really need is a easy and fast way to selectively disrupt one or two inline scripts, as it can't be any simpler to destroy a script if we just have the weapon so we can easily keep up with the web's change.

**Comment by uBlock-user** [comment]
> doesn't allow me to inject my own script.

Beggining with 1.11.5, you can, see - https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation

even if you selectively disrupt their scripts, they can simply change it or replace it with yet whole new inline script if they intend to play that `whack-a-mole` game, for that situation there's truly no persistent solution.

`BeforeScriptExecute` was that weapon you wanted, however they don't want to give the users that kind of control, and there's no precise replacement for that at the moment, so `script:inject` is the next best thing and is being used in majority of the uBO filters.

**Comment by gorhill** [comment]
uBO uses Firefox's `beforescriptexecute` event. Apparently this event is not fire by Firefox for script tags of type `text/rocketscript`. You will have to open an issue with them.

**Comment by ayuanx** [comment]
In fact, I've been using Mason on Firefox to inject my own scripts  from day 1, which is much superior, but sadly less well known version of GreasyMonkey.

I've got dozens of scripts to anti-anti-block different sites, but most of them would usually expire in a month or two since the internet is a fast-paced-ever-changing thing in nature. And I am really fed up with the work to rewrite and test my scripts every so often.

That's why I am looking for an easy way to handle this ever changing situation, like something to disrupt their script brutally in 5 seconds work, which I could afford and play along with them every few weeks.
I don't mind playing whack-the-mole which is inevitable on internet, as long as I can take less time to counteract than what they have to spend on the change of code, I am winning the game.

**Comment by gorhill** [comment]
The issue here should no longer be one with HTML filtering in latest dev build of uBO and proper HTML filters.
