### ISSUE TITLE
entry.delete is not a function

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#2464]
### Describe the issue

Using `$badfilter` with `suspendTabsUntilReady true` blocks page loading on session restore.
Console message:
```
19:54:07.657 TypeError: entry.delete is not a function[Learn More]  static-net-filtering.js:2100:13
	FilterContainer.prototype.removeBadFilters chrome://ublock0/content/js/static-net-filtering.js:2100:13
	FilterContainer.prototype.freeze chrome://ublock0/content/js/static-net-filtering.js:1638:5
	onDone chrome://ublock0/content/js/storage.js:584:9
	onCompiledListLoaded chrome://ublock0/content/js/storage.js:622:13
	onCompiledListLoaded chrome://ublock0/content/js/storage.js:684:9
	reportBack chrome://ublock0/content/js/assets.js:750:9
	onCachedContentLoaded chrome://ublock0/content/js/assets.js:783:20
	reportBack chrome://ublock0/content/js/assets.js:515:9
	onAssetRead chrome://ublock0/content/js/assets.js:528:9
	prepareResult chrome://ublock0/content/js/vapi-background.js:544:13
	handleCompletion chrome://ublock0/content/js/vapi-background.js:454:21
	permitUnload chrome://global/content/bindings/remote-browser.xml:357:13
	_loadURIWithFlags chrome://browser/content/browser.js:998:38
	loadURIWithFlags chrome://browser/content/tabbrowser.xml:7711:13
	loadTabs chrome://browser/content/tabbrowser.xml:1635:15
	loadOneOrMoreURIs chrome://browser/content/browser.js:2051:5
	_delayedStartup chrome://browser/content/browser.js:1343:9
	bound _delayedStartup self-hosted:913:17
```

### One or more specific URLs where the issue occurs
http://florydziak.com/blogger/2017/03/bezos-sie-swietnie-bawi.html

### Steps for anyone to reproduce the issue

Setup Firefox to restore session (Preferences -> When Firefox starts -> Show my windows and tabs from last time)
Enable `suspendTabsUntilReady` advanced setting
Create `||s.youtube.com^$badfilter` filter in My filters. I think it must be with domain. `||s.youtube.com^` is from EasyPrivacy.
Open http://florydziak.com/blogger/2017/03/bezos-sie-swietnie-bawi.html
Restart browser.
No page will load, even google.com, only blank page is visible

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox 52 (tested on clean) or 54
- uBlock Origin version: 1.11.5b0

##### Your filter lists

Default

##### Your custom filters (if any)

||s.youtube.com^$badfilter

**Comment by gorhill** [comment]
Oops.. Will fix asap.
