### ISSUE TITLE
Dynmamic filtering pane does not show all domains

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#2466]
Hi,actually I am not sure  whether this an issue or not but on some sites Ublock's dynamic filtering pane does not show all blocked domains when Ublock is on.However when I disable Ublock on the site, dynamic filtering pane shows much more blocked domains.You can reproduce the issue using the link which seems on the pictures below.Thanks.

I am using the latest  Ublock version with default filters on Chrome v58 beta.

http://imagetwist.com/mubo8al9r67c/Capture1.JPG
http://imagetwist.com/t7ar7bfzjexv/Capture2.JPG

**Comment by Betsy25** [comment]
Looks pretty normal behavior to me. Remember, when you're blocking, stuff gets blocked which (when not blocked) on itself calls a lot of more crap. When you're block the first nasty in the row from loading, you're disallowing it from fetching more nasties.

**Comment by mozkan007** [comment]
Hmm I see but actually I wish we could see all of them in dynamic filtering pane,it would be so easy to allow/block them in case of any page breakage or  stuff loading issue without making Ublock on/off.Sorry bad language.Thanks.

**Comment by gorhill** [comment]
Asking the impossible, declined.
