### ISSUE TITLE
Logger: can't bring up filtering options for popup entries where URL does not start with http[s]

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2469]
Originally spotted [here](https://github.com/gorhill/uBlock/issues/2465#issuecomment-287911380).

### Describe the issue

In the logger, the filtering options for popup entries where URL does not start with http/https can't be brought up.

### One or more specific URLs where the issue occurs

`http://codepen.io/PaulBGD/pen/zZRLqR`

### Steps for anyone to reproduce the issue

1. Open logger.
1. Open `http://codepen.io/PaulBGD/pen/zZRLqR` in a new tab.
1. Click "Run" button.
1. The entry `data:text/html;base64,SGVsbG8gV29ybGQ=` will appear in the logger, blocked by the filter `|data:text$popup`.
1. Click the cell `--` for that entry.
1. Result: nothing happens. Expected result: the filtering options should appear.

### Your settings

All default settings.

**Comment by mapx-** [comment]
another case here:
https://forums.lanik.us/viewtopic.php?p=116512#p116512

`popup	about:blank` cannot be managed
