### ISSUE TITLE
pop up  ads 

### ISSUE THREAD

**Issue by swathigrate** [gorhill/uBlock#2470]
### Describe the issue
 automatically  open [ads](https://secure.kreationnext.com/servers-and-hosting/dedicated-server/single-cpu-dedicated-server.html)  in new tabs 

https://www.tamilmv.la/
https://www.xvideos.com

filters list 

![fdsadf](https://cloud.githubusercontent.com/assets/14991260/24186443/4ee606e2-0efe-11e7-8751-9992f3734597.JPG)

 Your settings

- firefox 50
- uBlock Origin version: 1.11.4

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
