### ISSUE TITLE
Remove RUS: Adguard Russian Filter from default filters list

### ISSUE THREAD

**Issue by Iowei** [gorhill/uBlock#2475]
Hello, can you please remove filters from this trashware called Adguard? Today I've seen banners on russian popular social network - vk.com, and reason is "RUS: Adguard Russian Filter", they just add banners on videos to white list without any user agreement, I was disabled these filters and banners is gone.

Here is this whitelisting:
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=RUS-2

> @@||pladform.ru/pladformAdvertModule.swf$domain=coub.com|vk.com

And this is not first time they whitelisting ads, they also whitelist this:

> @@||yabs.yandex.ru$domain=yandex.by|yandex.com.tr|yandex.kz|yandex.ru|yandex.ua

This is yandex ads sub-domain.

**Comment by gorhill** [comment]
If you have issues with Adguard filters, bring these to their attention, here is not the place: <https://github.com/AdguardTeam/AdguardFilters/issues>.
