### ISSUE TITLE
Can we remove "Suggested for you " on linkedIn

### ISSUE THREAD

**Issue by rahulgarg** [gorhill/uBlock#2476]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Can we remove "Suggested for you " on linkedIn

### One or more specific URLs where the issue occurs
https://www.linkedin.com/feed/
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![image](https://cloud.githubusercontent.com/assets/128629/24279184/440f68b8-1083-11e7-822a-7054ce5e1db2.png)

[Screenshot(s) for visual issues are **mandatory**]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
