### ISSUE TITLE
uBO 1.11.5rc0 Webextensions under Firefox :  No settings save dialog is displayed.

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2477]
Using uBO 1.11.5rc0 Webextensions version under Fx55 Nightly 64 bit.

After clicking on the 'Backup to file' button to save my settings I do not get a dialog asking me where to save the file.  The backup temp file that Fx creates is in my Windows Temp folder.  This is an interim file Fx creates named something like xxxxxxxxx.fileextension.part.  If the dialog was presented to me and I saved it it would have been renamed to uBO's proper backup settings naming convention.

**Comment by gorhill** [comment]
> I do not get a dialog asking me where to save the file

There has never been a dialog, the backup file is saved into whatever folder your browser is set to save downloaded files.

**Comment by gorhill** [comment]
Although the dialog not showing is not the issue, after trying to reproduce I confirm there is indeed an issue, which is that the backup file is not being saved into the `~/Downloads/` directory on my side, which is   where it should have been saved. Need to investigate.

**Comment by streetwolf** [comment]
People were telling me there was a dialog,  The file is being saved in my temp folder as I mentioned.  Fx creates this temporary file in case the download is interrupted like exiting Fx.  When Fx is run again the download continues.  When the download is done the file should go to it's final destination with the proper name.  In my case it stops at the Temp folder.  uBO does display the file was saved but not to my download folder.  Perhaps Webextensions is causing this to happen.

**Comment by gorhill** [comment]
I get this error in the browser console when trying to back up settings:

    > TypeError: this.mDialog is null[Learn More]  nsHelperAppDlg.js:187:5

**Comment by streetwolf** [comment]
Same message on my system.

**Comment by gorhill** [comment]
"Export to file" for all other cases (My filters, My rules, Whitelist) works as expected.

**Comment by streetwolf** [comment]
The Export button does produce a dialog in all cases unlike the backup settings button and does save the file in my download folder.  Maybe you need a dialog for WE.

**Comment by gorhill** [comment]
> The Export button does produce a dialog in all cases

I did not know that, it's not that way on my side. What is "WE"?

**Comment by streetwolf** [comment]
Webextenions.

**Comment by gorhill** [comment]
Did you get the dialogs with the legacy version of uBO?

**Comment by streetwolf** [comment]
Let me setup a new test version of Fx55.  I'll try both versions.  brb.

**Comment by streetwolf** [comment]
Created a clean test version of Fx55.  Installed uBlock Origin v1.11.4.  Backup Settings button gave me a dialog.  Save worked as expected.  The Export buttons also gave me dialogs.

I then removed 1.11.4 and installed uBO 1.11.5rc0 Webextensions.  Backup Settings gave me no dialog and the backup didn't make it to my download folder.  Exports worked as expected with dialogs.

**Comment by gorhill** [comment]
Ok, thanks for investigating. I don't know why I don't get the dialog, personally I prefer this way anwyays.

So I will just re-work a bit the code to ensure that `vAPI.download` is called from within the dashboard when backing up setting, that is the key difference with other backup buttons.

**Comment by streetwolf** [comment]
Always glad to help.

**Comment by smartfonreddit** [comment]
The problem is most likely caused by the browser's popup blocker. I managed to restore a RES backup file last week. I forgot what exactly I did but after refreshing the page, the popup blocker icon appeared on the right corner of the address bar. Whitelisting it allowed me to restore the database. Before that, clicking the restore button wouldn't open the popup window that allows you to browser your OS and select the backup file.

**Comment by gwarser** [comment]
I cannot create backup on Firefox 54, UBO 1.11.5rc7
"Last backup" date is updated, but no dialog, no file in default download directory, nothing in dev console.
Browser console shows: 
`21:56:02.152 TypeError: this.mDialog is null[Learn More]  nsHelperAppDlg.js:187:5`
