### ISSUE TITLE
no-large-media not work with pac.js proxy

### ISSUE THREAD

**Issue by pavlogafy** [gorhill/uBlock#2479]
In Firefox 52:
UBO can't block images with "no-large-media: * true" and set pac.js (automatic proxy configuration url).
I enable deafult "Block media elements larger than 50kb".

Example: http://leksandra.livejournal.com/114663.html

With set "no proxy" work fine.

**Comment by gorhill** [comment]
If you proxy removes the `Content-Length` HTTP header, this is expected. uBO needs that header to know whether an image must be blocked. Please investigate if this is the case.

**Comment by gorhill** [comment]
Closing due to lack of feedback.
