### ISSUE TITLE
[Firefox] Issue with links that open in a new tab

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#248]
Firefox 38.0.1 / uBlock 0.9.8.1 / no other extensions for the purposes of this example

Hypothetical case:

* Click a link on "example.com" (where scripts are whitelisted or noop)
* A new tab opens to "example-2.com", where scripts are in default deny
* Switch back to "example.com" tab: it's now using the example-2.com's rules, so scripts are blocked

Before clicking link, all is well:
![ublock-normal-original-tab](https://cloud.githubusercontent.com/assets/9421932/7853577/2a8fc282-04c5-11e5-889d-d59b7a6fe4b4.png)

After opening link (t.co is noop as per my own rules):
![ublock-original-domain-after-new-tab](https://cloud.githubusercontent.com/assets/9421932/7853576/233c9f0a-04c5-11e5-9ff2-d8aa67fdf4bb.png)

This is on `tweetdeck.twitter.com`, where opening a link will cause `t.co` rules (or if not t.co, any other domain) to take over the original tab, thus tweets and other things will no longer load. I have to refresh the page to fix this.

Another example would be on `twitch.tv`, where clicking a link in the chat will open a new tab and the video will stop streaming.

No such issue occurs in Chrome.

**Comment by gorhill** [comment]
Can you give me real URLs to reproduce instead of `example.com`? I tried reproduce from what I could understand, but didn't see anything wrong. I want to follow **exactly** your steps to reproduce.

**Comment by luxoflux** [comment]
Yeah, if you look under the screenshots I produced, there are two real URLs where you can try to reproduce. I only used `example.com` (not actually that site) because it appears to occur with any site that has links open in a new tab + different domain.

**Comment by gorhill** [comment]
Ok, I see what you mean, I could reproduce:

1. Log into <https://tweetdeck.twitter.com/>
1. Find an embedded link with the form `t.co/...` somewhere in a tweet
1. Click link
1. New web page open
1. 1st-party in uBlock's popup for <https://tweetdeck.twitter.com/> becomes `t.co`

**Comment by luxoflux** [comment]
Yes, exactly.

Okay, come to think of it, I don't remember this happening with earlier versions of uBlock, so I went and installed 0.9.4.4 just now and confirmed the issue doesn't occur. I'll test some other versions and report back.

**Comment by gorhill** [comment]
I see why it's happening in the code: Firefox is telling uBlock that it is opening a new document to `t.co` in the Tweetdeck window, while there is no navigation to that new document.

**Comment by luxoflux** [comment]
Seems to occur from version 0.9.7.5 and newer.

**Comment by gorhill** [comment]
Fix to #184 is causing the issue here.

**Comment by gorhill** [comment]
Other test cases to validate fix:

https://github.com/gorhill/uMatrix/issues/145
https://github.com/chrisaljoudi/uBlock/issues/516

**Comment by luxoflux** [comment]
It seems this one is back (and reproducible with the same steps).

FF41 / UBO1.1.1

**Comment by gorhill** [comment]
Can't reproduce using [steps above](https://github.com/gorhill/uBlock/issues/248#issuecomment-106426095). If you can reproduce, please provide detailed steps like above fpr me to follow.

**Comment by luxoflux** [comment]
I was able to reproduce using the five steps you outlined above. But again, clicking on any external link which opens in a new tab causes that URL to appear in the original tab uBlock popup.

So here is a screenshot after clicking a few of those links on tweetdeck.twitter.com:

![ublock](https://cloud.githubusercontent.com/assets/9421932/10085560/c238427e-62be-11e5-95bc-b2cf2867122b.png)
