### ISSUE TITLE
www.redfin.com popup window for filters is will not show when ublock is active

### ISSUE THREAD

**Issue by jimmerjohn123** [gorhill/uBlock#2480]
### Describe the issue
When going to www.redfin.com and making a search, there is a filter link on the website which pops up an in-screen box giving the user extra selections. This box does not pop up when ublock is active.

### One or more specific URLs where the issue occurs
https://www.redfin.com/city/17151/CA/San-Francisco

### Screenshot in which the issue can be seen

![withublock](https://cloud.githubusercontent.com/assets/26662282/24316248/de73cfc2-10c2-11e7-9746-ac7bb38633bd.png)
![withoutublock](https://cloud.githubusercontent.com/assets/26662282/24316249/e182c5d8-10c2-11e7-824f-231e507f2dbb.png)

### Steps for anyone to reproduce the issue

1. go to www.redfin.com
2. type in a city, ie. San Francisco
3. Click on the filters link near the top right

### Your settings

all default

- Browser/version: Version 56.0.2924.87 (64-bit)
- uBlock Origin version:  1.11.4

##### Your filter lists

Default

**Comment by mapx-** [comment]
filter issue
add
`@@||google-analytics.com/cx/api.js$script,domain=redfin.com`

for filter issues report here in the future:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
