### ISSUE TITLE
Filter update issue

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#2481]
### Describe the issue

I am using Ublock v1.11.4 with 152 custom filters in additon to the default filters so the total number of all filter is 2.600.000 on Chrome v58 beta.When I click the update now button to update the filters, many of them are not updated and besides the yellow and the red exclamation mark indicators appears as you can see the picture below.Despite I tried to purge all caches button the result did not change.So you can reproduce the issue restoring the backup file which I  added below.By the way there is no problem with the updating sources all of them is up-to-date and working smoothly.Thanks. 

[my-ublock-backup_2017-03-26_21.53.33.txt](https://github.com/gorhill/uBlock/files/870977/my-ublock-backup_2017-03-26_21.53.33.txt)

![capture](https://cloud.githubusercontent.com/assets/16270347/24334356/78871628-1271-11e7-9d56-ab98fc611a81.JPG)

**Comment by gorhill** [comment]
Why did you change the advanced user setting `assetFetchTimeout` from 30 seconds to 1 second?

**Comment by gorhill** [comment]
Please, abstain from opening issues which are caused by your _own_ actions. You could have investigated this yourself given you did the change yourself -- such invalid issues are a burden on this project.
