### ISSUE TITLE
Dynamic URL Filtering issue

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#2483]
for some reason the rule wont work for the below site. i am on latest firefox beta and latest ublock beta. a rule in easylist is breaking the video.

vidlox.tv https://vidlox.tv worker allow

https://vidlox.tv/r3cxqq93s9jx

**Comment by gorhill** [comment]
`worker` type is not implemented yet. uBO outputs this at the logger, but internally it really is a test against `|blob:`. You will need `@@|blob:$script,domain=vidlox.tv` to override. I don't know what other blockers plan with regard to web workers, but so far it seems we need a new `worker` type.

**Comment by gorhill** [comment]
This issue is now obsolete, it was resolved as a result of add the new filter option `csp=` in [1.13.0](https://github.com/gorhill/uBlock/releases/tag/1.13.0), and these can be handled properly through the toggling of dynamic URL filtering in the logger.
