### ISSUE TITLE
Altmetric

### ISSUE THREAD

**Issue by wolfie717** [gorhill/uBlock#2484]
The domain altmetric.com appears to have been added to uBlock. They provide embeddable badges for academic citations and I'm not sure why they are blacklisted.

https://api.altmetric.com/embeds.html

e.g. https://achim-wolf.com/ under 'Publications'

Thank you.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
