### ISSUE TITLE
Reduce the default filtering rules, for example,  the key words log or log.js

### ISSUE THREAD

**Issue by emily-meng** [gorhill/uBlock#2485]
### Describe the issue
now the js file is blocked by the plugin, it can't work normally. the js file is http://g.alicdn.com/retcode/log/log.js 

I hope the plugin can reduce the default filtering rules, let the js file can work normally.

thanks.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by emily-meng** [comment]
@gorhill  why invalid ?  the uBlock plugin block the normal js file loading, I think you can reduce the default filtering rules.

**Comment by gorhill** [comment]
Filter issues must be brought to filter list maintainers. From the look of it, your issue might be related to EasyPrivacy (I can't tell for sure, you fail to provide all the details), report your issue to EasyPrivacy maintainers: https://forums.lanik.us/viewforum.php?f=64<>.
