### ISSUE TITLE
Authorization of elemenets by wiring of these

### ISSUE THREAD

**Issue by takius92** [gorhill/uBlock#2486]
(Google transalte)

Hello,
I allow myself to open this thread to ask you if possible a function
On some page, I sometimes notice things blocked in advance for various reasons

Would it be possible to add a function "authorization by targeting"
For example, with the element selector have indicated either the echo to be blocked or the element to be allowed

Currently, how to authorize an item without lssing it one by one?
I hope to have been clear enough in my application (especially with google trad)

IMG :
http://nsa37.casimages.com/img/2017/03/29/170329073647819979.png

URL : 
http://www.allocine.fr/video/video-19569547/

**Comment by gorhill** [comment]
Je comprend rien. Dites-le en français svp.

**Comment by takius92** [comment]
( tellement l'habitude de devoir le dire en anglais )

si vous regarder l'URL d'allociné et si vous comparez par rapport à la capture d'écran,
on peux voir que certain élément sont bloqué ( le cadre vidéo dans ce cas )

je ne le vois pas ( masqué ) mais peux le sélectionner donc je sais qu'il y a un élément 

serait il possible de rajouter un "bouton" pour qu'avec la pipette, 
on puisse soit masquer un élément soit le faire apparaitre ( si il est masqué )

car actuellement, pour trouver l'élément bloqué, on doit "valider" les différentes lignes un par un pour le faire apparaitre 
via la pipette, on serait directement lequel on doit activer ( ou celle ci s’activerait toute seule )

**Comment by gorhill** [comment]
> serait il possible de rajouter un "bouton" pour qu'avec la pipette,
> on puisse soit masquer un élément soit le faire apparaitre ( si il est masqué )

Si un élément est caché, on peut pas le sélectionner, il est invisible. Vous pouvez essayer le logger, il permet de rendre visible des éléments qui ont été masqué et de créer des filtres d'exception:

![a](https://cloud.githubusercontent.com/assets/585534/24470406/d30114e2-148c-11e7-8d10-afed5b157f9b.png)

De mon côté la vidéo apparaît correctement avec les listes de base.

Les problèmes de filtres doivent être soumis à <https://github.com/uBlockOrigin/uAssets/issues>, ou à <https://forums.lanik.us/index.php>.

**Comment by takius92** [comment]
voici ce que j'ai sur la page
http://nsa38.casimages.com/img/2017/03/29/170329091752337711.png

alors, plutôt que faire des essais éléments par éléments, 
le "bouton" nous ferais un filtre d'exception ( qui déclencherais le bouton par la même occasion )


edit ,  je me doute que le soucis vient du faites que les élément ne sont pas autorisé par défaut chez moi
je ne sais même pas comment activer par défaut 

sur les pages, j'ai la méthode de "l'ajout/autorisation" d'élément
et non la "soustraction/retrait" des éléments

**Comment by gorhill** [comment]
Le ["DOM inspector"](https://github.com/gorhill/uBlock/wiki/DOM-inspector) permet de trouver les éléments cachés sur la page -- c'est l'outil à utiliser pour ce genre de problème.
