### ISSUE TITLE
Cannot open 'My filters' item in new tab

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#249]
In the uBlock Dashboard, on the '3rd-party filters' tab, there are checkboxes for different filter lists.  The first one is 'My filters'.  All of those items except 'My filters' can be opened in a new tab without error.  Opening 'My filters' in a new tab generates a 'File not found' error.

Steps to Reproduce:
1. Open uBlock Dashboard
2. Click on the '3rd-party filters' tab
3. Right-click on the 'My filters' checkbox item
4. Select 'Open link in new tab'

Expected Result:
Opens 'My filters' list in new tab.

Actual Result:
Generates a 'File not found' error.

Tested on: Firefox 38.0.1 in Win7 SP1

**Comment by gorhill** [comment]
Use left-click to open a list. It's a Firefox thing: <https://github.com/chrisaljoudi/uBlock/issues/860#issuecomment-75451306>.

**Comment by Gitoffthelawn** [comment]
When the user wants to quickly view multiple lists, it is useful to open them in separate tabs.  Every list, except 'My filters' can be displayed in a new tab as expected.

Is 'chrome://ublock0/content/assets/user/filters.txt' supposed to resolve correctly?  It generates a 'File not found' error, unlike 'chrome://ublock0/content/assets/ublock/filters.txt', which resolves without error.

**Comment by gorhill** [comment]
> Is 'chrome://ublock0/content/assets/user/filters.txt' supposed to resolve correctly?

No, there is no file for the user filter list in the package.
