### ISSUE TITLE
ublock not blocking popup ads in Vivaldi browser

### ISSUE THREAD

**Issue by ale82to** [gorhill/uBlock#2491]
with exact same filter (even custom) as chrome ublock is not blocking a single ad popup in vivaldi browser is this normal??
test url
 http://cineblog01.site/serie-tv-streaming/6158-the-fosters.html
and try to play the video
(of corse u have to add a custom filter: ||play4k.tv^$popup,script

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
