### ISSUE TITLE
uBlock Origin holds separate settings for Incognito windows - way to disable this?

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uBlock#2492]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Making a uBlock Origin setting change to a webpage on Google Chrome only changes the setting for the window-version I'm in (e.g., Incognito or Regular). I don't like this. If I change a web-page's setting, I want it changed and not to be different somewhere else. Is there a way to configure for this? 

### Steps for anyone to reproduce the issue
1. Be as detailed as possible:
NOTE: I reset uBlock Origin to default before running this test.
1) enable "Block remote fonts" in uBlock
2) go to arstechnica.com in a Regular window and open the uBlock popup and disable font blocking
3) open an incognito window and go to arstechnica.com and view uBlock popup. Font are being blocked (ie, disable font blocking did not take effect in the incognito window).

### Your settings
Default settings before beginning above procedure.

- Browser/version: Google Chrome Version 57.0.2987.133 (64-bit)
- uBlock Origin version: v1.11.4

##### Your filter lists
default filter list

##### Your custom filters (if any)
no custom filters.

**Comment by jjohns71** [comment]
Are you sure? I did your steps and have no problem.

Go to your 'My rules' panel and make sure the following rule `no-remote-fonts: arstechnica.com false` is saved in the permanent category. After doing that the remote fonts are blocked in the incognito window for me.

![font](https://cloud.githubusercontent.com/assets/6795795/24559756/e3bead80-160d-11e7-97f3-8705a631d2b6.PNG)

**Comment by vdcbb** [comment]
Hello, jjohns71. My original description of the problem was faulty. If you follow my new description, I think you will be able to replicate the problem. After following the description, you'll notice that if you open uBlock Origin Dashboard within an Incognito window, then the arstechnica font change will be noted. But if you open uBlock Origin Dashboard from a Regular window, the change is not reflected.

I believe it is related to issue 1188 which I missed in my initial search before posting, so I don't want to bother gorhill with it further.

**Comment by jjohns71** [comment]
I believe that what you are describing is "as intended" as settings set in the incognito window will only be valid for that session (Until you close the window). 

This does look to be the exact same issue as described in [#1188](https://github.com/gorhill/uBlock/issues/1188)
