### ISSUE TITLE
uBO broken on Firefox mozilla-central tip

### ISSUE THREAD

**Issue by rvandermeulen** [gorhill/uBlock#2493]
This hasn't shipped in a nightly build yet since it was merged to mozilla-central after the 2017-03-31 nightlies were created, but bug 1145470 has broken uBO (won't even load).

The error in the browser console is:
Security Error: Content at resource://gre-resources/hiddenWindow.html may not load or link to chrome://ublock0/content/background.html#1.11.4.

**Comment by gijsk** [comment]
Disclaimers: I wrote the change to Firefox that broke this. I also am not a regular user of uBlock Origin or any other similar ad-blocking tools, so YMMV with 'obvious' breakage that I didn't spot or whatever. I also only tested on m-c tip.

I wrote a quick patch that seems to make uBlock Origin work again on current mozilla-central tip. As github helpfully referenced above, it's at https://github.com/gijsk/uBlock/commit/dc06d5fa0cbecfc10f7f1e96af04f945e016bc1c . I would have done a pull request, but your Contributing.md file explicitly says not to do that, so I haven't. I'd happy to click the trivial github buttons to make that happen, of course, though you're also welcome to take that patch in some other way (and/or with tweaks). I tried to follow code style as I saw it, but I might have slipped up in places - habits are hard to shake.

**Comment by gorhill** [comment]
> I would have done a pull request, but your Contributing.md file explicitly says not to do that, so I haven't.

It's really to prevent superficial and undesirable pull requests, I do actually accept pull requests from real developers which solve real issues.

**Comment by gorhill** [comment]
@gijsk Can you submit the pull request?

I tried to create the pull request myself from your repo, but somehow as a result I couldn't see your name as the author of the commit, so I reverted it.

**Comment by gorhill** [comment]
Never mind, found [this help](https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/) on how to do this. Thanks for the fix.
