### ISSUE TITLE
DNS-BH - Malware Domain Blocklist

### ISSUE THREAD

**Issue by stanlane** [gorhill/uBlock#2495]
### Describe the issue
I wonder if there's enough malware protection filters subscribed in uBO.

### One or more specific URLs where the issue occurs
I suggest the **DNS-BH - Malware Domain Blocklist** to uBO - http://www.malwaredomains.com/?page_id=2 

### Your settings

- Browser/version: Firefox 52
- uBlock Origin version: 1.11.4

##### Your filter lists

Default

**Comment by gorhill** [comment]
It's already in there. Refrain from opening invalid issue please.

**Comment by stanlane** [comment]
@gorhill I'm sorry. Should I have reported this to uAssets instead?
