### ISSUE TITLE
Admiral anti-adblock preventing from entering the site

### ISSUE THREAD

**Issue by Humberd** [gorhill/uBlock#2496]
### Describe the issue

I've just installed uBlock origin on my Chrome browser and I can't find a way to remove anti-adblock script from a gaming site. I can't just remove the element from DOM, because the script removed all CSS files from the site and I somehow need to block the script before its execution.

### One or more specific URLs where the issue occurs

[http://www.gry.pl/gra/1001-arabian-nights-7](http://www.gry.pl/gra/1001-arabian-nights-7)

### Screenshot in which the issue can be seen

It's in Polish, but it says that we have an adblock on and we should turn it off.

![image](https://cloud.githubusercontent.com/assets/10242142/24578450/6b9ccb92-1695-11e7-8294-b227258cc56b.png)

### Steps for anyone to reproduce the issue

1. Go on the site provided above.

### Your settings

- Browser/version: Chrome - 49.0.2623.112 m
- uBlock Origin version: 1.11.4

##### Your filter lists

Default filter list + Anti-Adblock Killer | Reek

##### Your custom filters (if any)

none

**Comment by uBlock-user** [comment]
Filter list issues - https://github.com/uBlockOrigin/uAssets/issues

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
