### ISSUE TITLE
[Feature Request] Naming Custom Filters

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#2501]
Is it possible to name a custom filter so that it doesn’t show the url, if not can you add this ability.
Thanks

**Comment by toshiya44** [comment]
Feature already exists.
Just add `! Title: Whatever` at the beginning of the files.

**Comment by gorhill** [comment]
> Just add `! Title: Whatever` at the beginning of the files.

That won't work if the file is not under control of the user. For instance hosts files do not support such directive.

**Comment by zero77** [comment]
So, is there currently any way for me to do this.

**Comment by gorhill** [comment]
No, I want to think about what is the best solution long term. I have ideas, but I want to mature them, and also this is not something I see at the top of the list of things to fix.

**Comment by Zundala** [comment]
Sorry, if i writing this wrong place. Total noob. It seems to me closest open issue to what i want.
I would like to see my cosmetic filtering list automatically sorted and grouped by domain.  Clean and easy to find, edit, delete ...... With my poor english do not think i can explain everything, so took screenshot what im now doing manually to my filter lists. 
![capture](https://cloud.githubusercontent.com/assets/27537315/25061250/ce22d8bc-21ec-11e7-9bd8-11c054abdd6e.PNG)

**Comment by zero77** [comment]
@Zundala  You need to create a new issue
