### ISSUE TITLE
Ublock ad protection by passed

### ISSUE THREAD

**Issue by drunkista** [gorhill/uBlock#2507]
@Gorhill; guys, you should give it a try to demonoid.pw persistence ads !!!! No matter how many times i block the footer (with Block element right click option[chrome browser]), when you click on next page, the footer is always there filled with ads !

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment]
add
`*$websocket,domain=demonoid.pw`
