### ISSUE TITLE
Blocked network request still contains response headers

### ISSUE THREAD

**Issue by gazzalight** [gorhill/uBlock#2508]
### Describe the issue

Network request still returns headers after 307 internal redirect

On request to http://www.googletagservices.com/tag/js/gpt.js even though it is blocked, the response contains a location header which is javascript in Base64 form.

### One or more specific URLs where the issue occurs

http://anichart.net/

### Screenshot in which the issue can be seen

N/A

### Steps for anyone to reproduce the issue

1. Visit the site :+1: 

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 

Comodo Dragon v55.0.2883.59 (based on Chromium 55.0.2883.52).

- uBlock Origin version: 

v1.11.4

##### Your filter lists

- Default minus experimental
- EasyPrivacy
- Malware Domain List, Malware domains, Malware filter list by Disconnect
- Peter Lowe’s Ad and tracking server list

##### Your custom filters (if any)

None that are relevant

**Comment by gorhill** [comment]
Why is it an issue? The requests to `googletagservices.com/tag/js/gpt.js` are redirected to [uBO's own script](https://github.com/uBlockOrigin/uAssets/blob/efbc3dc94ccdd2545f53c3512a7b58478d5e0f88/filters/privacy.txt#L20).
