### ISSUE TITLE
Dashboard: 'Update now' button dimmed

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#251]
Not sure if this is a bug or a UI clarity issue.

In the '3rd-party filters' tab of the uBlock dashboard, there is a button labelled 'Update now'.  That button is dimmed even when 'Auto-update filters lists' is not checked.  This makes it impossible to force a refresh of the 3rd-party filters without performing a manual cache purge.  It would be useful to always have the 'Update now' button enabled.

Test system: uBlock Origin 0.9.7.5, Firefox 38.0.1, Win7 SP1

**Comment by gorhill** [comment]
By design, button is available if and only if there is at least one filter list in need of update.

**Comment by Gitoffthelawn** [comment]
That appears to be only after uBlock checks for updates every 4 days.  By dimming the button in the interim, uBlock prevents the user from manually updating filters even when a filter list is outdated.  The only workaround is to perform a manual purge.

**Comment by gorhill** [comment]
> The only workaround is to perform a manual purge.

It's not a workaround, it's the primary purpose of the purge button, this allows someone to update only one single filter list.

**Comment by Gitoffthelawn** [comment]
Yes, workaround is not the best word.  It's more of a UI clarity and flow issue.  Since the 4 day check period is largely arbitrary (would make a great hidden setting), it would be useful to have the 'Update now' button not dimmed since uBlock doesn't really know if updates are available (probably always not dimmed, but definitely not dimmed when 'Auto-update filter lists' is not checked).

From a usability perspective, if the user wants to update their filters, they see a button to do so, but it is disabled.

**Comment by gorhill** [comment]
>  4 day check period is largely arbitrary

The only time when it's not arbitrary is when there is a fix in one of the filter lists which a user **really** do need -- a rare occurrence I am pretty sure. Those filter lists are pulled from somebody else's server at their own expenses, and there is a need to tamper down the obsession to update all the time. This has been covered amply before.
