### ISSUE TITLE
uBlock enters memory leak on zerohedge.com

### ISSUE THREAD

**Issue by Industry** [gorhill/uBlock#2511]
**Important:** If you are having issue with uBlock Origin ("uBO") on **Firefox Nightly**, please install the most recent developer version of uBO on AMO: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>.

Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
The browser stops working and chrome has a difficult time even exiting the tab when the following filter is enabled:

zerohedge.com###sidebar-right

Navigation doesn't work, although I can access other tabs. After a while the memory usage for the tab skyrockets. 

### One or more specific URLs where the issue occurs

zerohedge.com

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

Attempt to enable the filter and go to the website. 

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Version 56.0.2924.87
uBlock Origin v1.11.4

##### Your filter lists

ublock filters + badware risks + privacy + unbreak + anti-adblock killer | reek + easylist + easyprivacy + malware domain list + malware domains + Peter lowe's ad and tracking server

##### Your custom filters (if any)
I have plenty, but the ones that modify the page are

zerohedge.com##.ad-left-container
zerohedge.com###sidebar-right
zerohedge.com##.view-dom-id-2.view-display-id-default.view-id-featured_posts.view-featured-posts.view
zerohedge.com###block-menu-secondary-links

**Comment by gorhill** [comment]
Two things:

If one or more filters cause you issue on a site, this is a filter issue -- **not** to be reported here.

> Attempt to enable the filter and go to the website

I did, all was fine.

Any **claim** of "memory leak" will have to come with **evidences** of memory leaks. You provide absolutely no evidence for your claim. The browser has all the tools for you to investigate and provide such evidence. I won't go on a hugely time-consuming investigation of someone else's evidence-free claim. I loaded the site and all was fine. Open an issue when you have **actual evidence** there is something wrong with uBO.

**Comment by Industry** [comment]
Sorry gorhill. I will show you more details of what the issue looks like, maybe this will help in investigating the cause.

![2017-04-04 09_15_09](https://cloud.githubusercontent.com/assets/413149/24658546/05b300b4-1918-11e7-9149-594021bc8f3a.png)
![2017-04-04 09_15_39-page unresponsive](https://cloud.githubusercontent.com/assets/413149/24658554/08991f0c-1918-11e7-9288-823fecc2c5cf.png)
![2017-04-04 09_17_53](https://cloud.githubusercontent.com/assets/413149/24658556/0a3f5b64-1918-11e7-9da0-f432a62af5f3.png)

**Comment by gorhill** [comment]
If you want to claim uBO itself is causing you issue, you need to disable all other extensions, and use uBO with default filter lists. Reload the page.. If the issue still occur with uBO **only** + default filter lists, then you need to rule out that a filter list is causing the issue -- disable them one by one, reload the page. If you confirm one filter list is causing the issue, you need to report to maintainers of that filter list. I will look into this only if you confirm that the issue is really with uBO, and not one of the other extensions installed, and neither with one of the filter lists.

**Comment by Industry** [comment]
Setting the settings in uBO to defaults did not prevent the issue from taking place. Disabling extensions one by one narrowed it down to Hover Zoom. The extension doesn't play nicely with uBO only on that one page. The add on has the ability to be disabled on certain pages so things look fine now.
