### ISSUE TITLE
Survole de l'icone "on/off filtre esthetic" = info bulle avec liste des filtres active sur la pages visités

### ISSUE THREAD

**Issue by takius92** [gorhill/uBlock#2512]
bonsoir,
savez vous si il serais possible d'ajouter une "fonction" au icônes "ON/OFF filtre esthétique"
qui lors du survol de celle ci, indique la liste des filtres esthetique actives sur la page visités

je demande cela, car j'ai un soucis de filtre esthétique sur une page
j'ai beau chercher dans l'onglet "mes filtres"
je ne trouve rien apparemment qui se réfère à la page web visités

actuel sur la page en question, j'ai 17 filtre esthétique actives 
( mais j'en retrouve aucun dans l'onglet "mes filtres" )
sachant que sur la page d’accueil du site, j'en ai 4 ( je pense que c'est ceux que j'ai créé )

ou sont stocker les 13 autres ?
et cette info bulle pourrais m'en faire la liste
et éventuellement proposés de les supprimés 

merci

**Comment by gorhill** [comment]
Utilisez le _logger_ pour voir quels filtres sont appliqués sur la page.
