### ISSUE TITLE
[Request] Youtube Filter by channel

### ISSUE THREAD

**Issue by Miatec** [gorhill/uBlock#2513]
Hello,

First, congratulation for the great work.

I don't know if it is the best place for requesting features, but it is the only one I found.

I spend a lot of time on youtube and i get almost no ads thanks to your work. But, I would like to support my favorite authors.

Is it possible to put a white list for channels in youtube? Or semi-white list (for example : Ok to display 1/2 ads, or 1/3 etc...) ?

I think it is an fair idea for the creators.

Thx for reading.
Miatec.

**Comment by anewuser** [comment]
Please search before creating new issues, and read the template text instead of deleting it.

https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#a-youtube-channel

**Comment by gorhill** [comment]
As mentioned, solution is a user script.
