### ISSUE TITLE
0 filtre ( mes filtres) esthétique active mais les éléments sont encore masqués, je coince

### ISSUE THREAD

**Issue by takius92** [gorhill/uBlock#2514]
bonsoir,
j'ai bien compris votre réponse

mais en fait, mon problème ne venait pas de là réellement
car sur un site web que je visite, j'ai un filtre esthétique active qui m’enlève des élément importants de la page ( je le sais via un clic pour les désactiver )

je viens d'utiliser la méthode ultime, j'ai supprimer l'intégralité du contenu de l'onglet MES FILTRES
mais ces éléments sont encore masqué malgré tout

serait il possible de demandé la suite en MP ?

merci

edit : 
je viens de reset Ublock
mais sur la page en question, j'ai encore 15 élément de bloquer
comment faire pour "reset" ces élément masqués

**Comment by gorhill** [comment]
Svp, les problèmes de filtres doivent être soumis à <https://github.com/uBlockOrigin/uAssets/issues> ou à <https://forums.lanik.us/index.php> si la liste qui vous cause des problèmes est EasyList/Liste FR etc.

Icic c'est strictement pour les problèmes avec uBO lui-même.
