### ISSUE TITLE
Cosmetic filters containing pseudo-elements do not show results in manual/interactive selection mode

### ISSUE THREAD

**Issue by SSoulaimane** [gorhill/uBlock#2515]
Tank you for implementing cosmetic filters with pseudo-elements in the last rc #2448.

However in the manual selection mode when a cosmetic filter with pseudo-elements is entered, no result is shown, it shows the number 0 at the corner bottom of the input box and the 'create' button is disabled.

But still the filter works when manually entered in the user filters tab in the settings.

**Comment by gorhill** [comment]
> no result is shown, it shows the number 0 at the corner bottom of the input box

It's not possible to `querySelectorAll` pseudo-elements, so it's not possible for uBO to programmatically find them on the page.

**Comment by SSoulaimane** [comment]
I see, then I suggest the element whom the pseudo-element relates to be the one shown in the match, then the preview should work as `:style()` does, and the `create` button should be enabled.

**Comment by gorhill** [comment]
Fixed with 8d136ec2d5c05e3325bcfbf896b017c4a491c24b.
