### ISSUE TITLE
Advanced Mode

### ISSUE THREAD

**Issue by davimack** [gorhill/uBlock#2517]
### Describe the issue
When in Advanced Mode, uBlock Origin 1.11.4 presents with a transparent main window (see below) with the exception of the grid / table:
<img width="282" alt="untitled" src="https://cloud.githubusercontent.com/assets/12926523/24726992/330aa2fa-1a09-11e7-9577-48f599206e4f.png">

Shown in that image is when I'm visiting https://github.com/gorhill/uBlock/issues/new and click the uBlock icon.

### Your settings
- Browser/version: 52.0.2
- uBlock Origin version: 1.11.4

and the following additional addons:
BarTabLite X v.1.8
Brief v.2.2.2
h264ify v1.0.5
Privacy Badger v2017.3.28
Tree Style Tab v0.19.2017031101

##### Whitelist:
about-scheme
banking.firsttechfed.com
behind-the-scene
ccp2mra.gene.com
chrome-extension-scheme
chrome-scheme
connect.intuit.com
drive.google.com
localhost
loopconversation.about-scheme
members.sonic.net
msa.quickapp.pro
opera-scheme
portal.azure.com
portal.scif.com
pptform.state.gov
shop.raleys.com
store.steampowered.com
webapp.ftb.ca.gov
www.aclu.org
www.adorama.com
www.eftps.gov
www.moo.com
www.statefundca.com
www.tasteslikehome.org

##### Your custom filters (if any)
||cdn.gotraffic.net/projector/v0.10.66/BloombergInsightsPlayer.swf$object
||vp.nyt.com/video$media
www.nytimes.com###video_inner_position_lede_100000004505950 > .vhs-buffering-container
www.bloomberg.com##body > div:nth-of-type(7) > bb-mini-player > .bb-mini-player.style-scope.bb-miniplayer
||videos.usatoday.net$image
||ssl.p.jwpcdn.com/player/$object
||i.cdn.turner.com/money/.element/apps/cvp2/assets/cvp_main_container.swf$object
||zmg-limelightovp3.creatorcloud.netdna-cdn.com/$media
www.sfgate.com###vemba_player_5y6md > .jw-reset.jw-media
www.sfgate.com###vemba_player_5y6md > .jw-reset.jw-aspect
||zmg-rackcdn1.creatorcloud.netdna-cdn.com$media
||dealnews.a.ssl.fastly.net$image
||zmg-rackcdn1.creatorcloud.netdna-cdn.com$media
www.sfgate.com###vemba_player_2lhut
www.sfgate.com###vemba_player_wrapper_2lhut
www.sfgate.com###vembaStickyMove
mediadiversified.org###image-22
mediadiversified.org###image-41
||www.thewrap.com/wp-content/plugins/contextual-links/assets/img/loading.gif$image
||pmd.cdn.turner.com/cnn/big//us/2016/04/13/way-up-there-hi-seas-mars-mission-dome-on-volcano-cm-orig.cnn_cnn_iphone_cell.mp4$media
www.bloomberg.com###awYXOKHrRWOQMURNMC4Qtw_Hlsjs_api
www.bloomberg.com###bbg-video-player-awYXOKHrRWOQMURNMC4Qtw
||pmd.cdn.turner.com/cnn/big//politics/2016/10/17/melania-trump-anderson-cooper-intv.cnn_cnn_iphone_cell.mp4$media
gma.yahoo.com###yui_3_18_1_1_1476823121239_1004
www.bloomberg.com###kVoR8PvS4ypFsyyTRZxeQ_Hlsjs_api
www.bloomberg.com###player-Dh8dqci-child
www.bloomberg.com###player-g1yj6jS-child
www.bloomberg.com###T51RAIFZSG2Jha4gKPvWw_Hlsjs_api
www.bloomberg.com##.bb-mini-player.bb-miniplayer
||player.hearstdigitalstudios.com/$subdocument
finance.yahoo.com###\33 058025547
finance.yahoo.com##.yvp-main
finance.yahoo.com###yvp-content-node-688
finance.yahoo.com##.Pos\(r\).D\(b\).VideoPlayer > .StretchedBox
finance.yahoo.com##.Pos\(r\).D\(b\).VideoPlayer
finance.yahoo.com##.H\(100\%\).W\(100\%\).vm-player
www.bloomberg.com###fFK49V3oSqSvKvC7cVyITg_Hlsjs_api
www.bloomberg.com##.inline-media.standard-video
www.washingtonpost.com##.swiper-slide.wpvlb-playlist-item
time.com##.video-content
time.com##.not-right-rail-adjacent.video-container
www.cnbc.com###player57597\.player
www.cnbc.com###player_0_104161580_0
www.cnbc.com##.theplatform-video__docked.dockable.player-lazy-loaded-mobile
www.cnn.com###cnnvideo_1023984e-videowrapper
www.cnn.com##.el__video--fullwidth.el__video
laughingsquid.com###instagram-embed-0
laughingsquid.com###instagram-embed-1
laughingsquid.com###instagram-embed-2
laughingsquid.com###instagram-embed-3
laughingsquid.com###instagram-embed-4
laughingsquid.com###instagram-embed-5
laughingsquid.com###instagram-embed-6
laughingsquid.com###instagram-embed-7
laughingsquid.com###instagram-embed-8
laughingsquid.com###instagram-embed-9
laughingsquid.com###instagram-embed-10
laughingsquid.com###instagram-embed-11
laughingsquid.com###instagram-embed-12
laughingsquid.com###instagram-embed-13
laughingsquid.com###instagram-embed-14
laughingsquid.com###instagram-embed-15
laughingsquid.com###instagram-embed-16
laughingsquid.com###instagram-embed-17
laughingsquid.com###instagram-embed-18
laughingsquid.com###instagram-embed-19
laughingsquid.com###instagram-embed-20
laughingsquid.com###instagram-media-payload-0
laughingsquid.com###instagram-media-payload-1
laughingsquid.com###instagram-media-payload-2
laughingsquid.com###instagram-media-payload-3
laughingsquid.com###instagram-media-payload-4
laughingsquid.com###instagram-media-payload-5
laughingsquid.com###instagram-media-payload-6
laughingsquid.com###instagram-media-payload-7
laughingsquid.com###instagram-media-payload-8
laughingsquid.com###instagram-media-payload-9
laughingsquid.com###instagram-media-payload-10
laughingsquid.com###instagram-media-payload-11
laughingsquid.com###instagram-media-payload-12
laughingsquid.com###instagram-media-payload-13
laughingsquid.com###instagram-media-payload-14
laughingsquid.com###instagram-media-payload-15
laughingsquid.com###instagram-media-payload-16
laughingsquid.com###instagram-media-payload-17
laughingsquid.com###instagram-media-payload-18
laughingsquid.com###instagram-media-payload-19
laughingsquid.com###instagram-media-payload-20
laughingsquid.com##.entry.category-blog.has-post-thumbnail.format-standard.status-publish.type-post.post.post-594867 > .entry-content > .instagram-media:nth-of-type(5)
www.salon.com##.widget.svp-widget
edition.cnn.com###large-media
vincedes3.com###blue_screen
www.latimes.com###reg-overlay
www.latimes.com###zuw5tfu
www.newsweek.com##.hidden-print.article-videoplayer
www.cnbc.com##.dockable.player-lazy-loaded-mobile
money.cnn.com##.cnnVidplayer
abcnews.go.com###abcn-videoplayer
abcnews.go.com##.isplaying.active.v-lead.video.article-figure
fusion.net###footer-sticky
www.newsweek.com##.videocontent
www.newsweek.com##.embed-responsive-16by9.embed-responsive.videocontent-wrapper
motherboard.vice.com##a[href^="/read/dark-matter-pico-snolab-deap-pandax-lux-admx-axion-wimp"] > .article-media-overlay
motherboard.vice.com##img[src="//motherboard-images.vice.com//content-images/article/40850/1483035198073191.gif?crop=1xw:0.725xh;*,*&resize=600:*&output-format=jpeg&output-quality=90"]
thinkprogress.org##.js-stickyFooter.u-xs-paddingRight10.u-xs-paddingLeft10.u-zIndexMetabar.u-paddingBottom10.u-paddingTop10.u-borderBox.u-boxShadowTop.u-backgroundWhite.u-sizeFullWidth.u-bottom0.u-fixed
medium.com##.js-stickyFooter
www.motherjones.com###bottom-donate
fortune.com##.jumpstart-sticky-inner
fortune.com##.dont-print.brightcove-wrapper
www.google.com##.gb_g.gb_Lc.gb_Tc.gb_Sc > .gb_ha
www.orlandosentinel.com###reg-overlay
artplusmarketing.com##.js-stickyFooter
backchannel.com##.js-stickyFooter

**Comment by gorhill** [comment]
MacOS?

**Comment by davimack** [comment]
Windows 8.1

**Comment by gorhill** [comment]
You have user styles?

Try with only uBO and no other extensions or user styles.

**Comment by davimack** [comment]
I do not have user styles.  I am not about to uninstall my other addons, though.  I can try disabling, though, which I'll do....

**Comment by davimack** [comment]
No joy that way.

**Comment by gorhill** [comment]
You can easily [create a new profile](https://support.mozilla.org/t5/Install-and-Update/Use-the-Profile-Manager-to-create-and-remove-Firefox-profiles/ta-p/2914) and test with only uBO.

Your report is unique enough that the most plausible explanation so far is that there is something specific on your side causing this.

**Comment by davimack** [comment]
I can believe that ... and will try creating a new profile.

**Comment by davimack** [comment]
Right - I'll work on creating a new profile when it doesn't mean shutting down FF, as I've got a bunch of things going right now and don't want to restart FF at the moment.  Will get back to you.

**Comment by davimack** [comment]
Same deal.  Removed, restarted, no joy.  Refreshed FireFox, still no joy, and I get this strangeness:
<img width="576" alt="untitled" src="https://cloud.githubusercontent.com/assets/12926523/24728892/be5ea660-1a10-11e7-995c-a72b4fb57290.png">

**Comment by gorhill** [comment]
I can't reproduce, so I can't investigate. Unless I can reproduce, this will have to be investigated by someone who can.

**Comment by davimack** [comment]
Am trying to make sure FF refresh purges all of the cached bits - to force a reinstall of uBlock.

**Comment by gorhill** [comment]
Observation: it appears that the invisible part represents exactly 33% of the whole available area. This is true for both horizontal and vertical extents.

**Comment by davimack** [comment]
Oooh! Interesting!  It looks like it's only happening when FF is on a secondary monitor.  When I open it on the primary monitor, no problem, but when I throw it (Window + Shift + Arrow) to another monitor, I get something like this:
<img width="439" alt="untitled" src="https://cloud.githubusercontent.com/assets/12926523/24730138/b24033fc-1a16-11e7-934d-c4f0639a9833.png">

Note the uBlock window, down at the bottom.  It does this whether in Advanced mode or not, and with other AddOns installed as well as native.

So.  Maybe class this as a "when it's on a secondary monitor" issue?  Not sure what could be done about it, though.  At least I've a work-around (i.e., put FF onto the primary monitor to create filters).

**Comment by davimack** [comment]
If it helps, my primary monitor is at 1920 x 1080 and my two secondaries are oriented portrait and at 1152 x 2048 resolution.

**Comment by gorhill** [comment]
At this point, I consider this a Firefox isse: uBO does not position the popup panel, it just append an `iframe` to it, so uBO is just using plain HTML/CSS/JS. There are a couple of issues on bugzilla about issues with secondary monitor, not sure which one would be a best match for the one here though:

<https://bugzilla.mozilla.org/buglist.cgi?quicksearch=+secondary+monitor>

**Comment by davimack** [comment]
Agree - this is FF, not uBO.  Coincides with the latest update to FF, I suspect.  Thanks!  Also: thanks for the awesome tool!

**Comment by gorhill** [comment]
I am curious about whether the webext version of uBO suffers the same issue.

**Comment by davimack** [comment]
You want me to test something else?  Happy to help....
