### ISSUE TITLE
uBlock blocks disquis comments from loading on Kiss-Asian in Google Chrome

### ISSUE THREAD

**Issue by soysuva** [gorhill/uBlock#2518]
### Describe the issue
On Google Chrome, I keep getting this error on Kissasian disqus "**Disqus seems to be taking longer than usual. Reload?**", even though disquis loads fine on other websites. It's also not an internet issue, since I've checked my internet by loading the google homepage and it loaded just fine. I've also tested it without any adblocks and it loaded without any problems. Tried going in incognito mode to see if it worked without any extensions and it also loaded fine. Then I added uBlock Origin to the incognito mode to see if it would load, it stopped loading and gave me the same error again. I also tested it on firefox with uBlock Origin and disquis loaded fine there, just not on chrome.

**Another note:** I added "||kissasian.com/*.aspx" to the filters because videos wouldn't load since the admins of the site added an anti-adblock to make users turn off their adblocks. I tested this without it too and disquis still wouldn't load.

### One or more specific URLs where the issue occurs
All pages on Kissasian in google chrome that has disquis comments gets this error. Here is just a link to one of the pages:
http://kissasian.com/Drama/Strong-Woman-Do-Bong-Soon/Episode-12?id=33082

### Screenshot in which the issue can be seen
**On Google Chrome with extensions and uBlock Origin:**
<a href="http://imgur.com/R2hZeYq"><img src="http://i.imgur.com/R2hZeYq.png" title="source: imgur.com" /></a>

**In incognito mode - Google Chrome with only uBlock Origin:**
<a href="http://imgur.com/KE43GXy"><img src="http://i.imgur.com/KE43GXy.png" title="source: imgur.com" /></a> 

**In incognito mode - Google Chrome with no extensions:**
<a href="http://imgur.com/cVhZyck"><img src="http://i.imgur.com/cVhZyck.png" title="source: imgur.com" /></a>

**Firefox with uBlock Origin:**
<a href="http://imgur.com/eBSSeEA"><img src="http://i.imgur.com/eBSSeEA.png" title="source: imgur.com" /></a>

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10, Dell, 64-Bit and 6GB RAM with 1TB memory, Intel Core i3
- Browser/version: Google Chrome Version 57.0.2987.133 (64-bit), Firefox Version 52.0.2 (32-bit)
- uBlock Origin version: uBlock Origin v1.11.4
##### Your filter lists
Does this mean 3rd party filters?
If it's this, I've only selected "Anti-Adblock Killer | Reek" script filter with all the default 3rd party filters

##### Your custom filters (if any)
**I only have one filter in "My Filters" in uBlock origin:**
||kissasian.com/*.aspx

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Report to EasyList maintainers, [this is what breaks Disqus on kissasian.com](https://forums.lanik.us/viewtopic.php?f=62&t=33897&p=107114).

**Comment by uBlock-user** [comment]
`||kissasian.com/*.aspx` is for neutralizing the anti adblock, adding or removing it won't have any effect on disqus being not loaded as it's a filter list issue.
