### ISSUE TITLE
Autogenerated filter breaks a web page

### ISSUE THREAD

**Issue by giogziro95** [gorhill/uBlock#2519]
### Describe the issue

I'm not sure if it's a feature, but it's most likely a bug, I think. So, I was trying to block an element that included ads, but it was blocking other elements on the page as well. I started by right-clicking the element and clicking _Block element_. Then I tried to inspect the web page (which, BTW, is very poorly designed) and it seemed that there was nothing wrong with the filter that uBlock Origin has generated, but it was clearly blocking other portions of the page as well. After about 5 minutes of tinkering, suddenly, it hit me. The autogenerated filter doesn't start with `##body >`, so it matches multiple elements in the DOM tree.

### One or more specific URLs where the issue occurs

- Page URL: _https://forum.ge/_
  - Ad container XPath: _/html/body/table/tbody/tr/td[2]_

### Screenshot in which the issue can be seen

![Screenshot](https://cloud.githubusercontent.com/assets/2781117/24826397/6f0b50a8-1c46-11e7-9903-5982b9f3145b.png)

### Steps for anyone to reproduce the issue

1. Right-click the element.
2. Click _Block element_.

### Your settings

- Autogenerated filter: `##table > tbody > tr > td:nth-of-type(2)`
- Working filter: `##body > table > tbody > tr > td:nth-of-type(2)`

- OS/version: Manjaro 17 (Gellivara) KDE
- Browser/version: Chrome 57.0.2987.110 (stable channel)
- uBlock Origin version: 1.11.4

##### Your filter lists

Irrelevant.

##### Your custom filters (if any)

Irrelevant.

**Comment by mapx-** [comment]
add
```
||sab.turbo.ge^$script
||forum.ge/trash/*
||adjarabet.com^$domain=forum.ge
```

**Comment by giogziro95** [comment]
@mapx- Thanks, but I'm not asking for the help; I'm just reporting a bug...

**Comment by giogziro95** [comment]
> add
> 
> ```
> ||sab.turbo.ge^$script
> ||forum.ge/trash/*
> ||adjarabet.com^$domain=forum.ge
> ```

Besides, this configuration won't hide the elements, so the ad placeholders won't go away...

**Comment by mapx-** [comment]
add also
`||sab.turbo.ge^$subdocument`

**Comment by giogziro95** [comment]
sab.turbo.ge is an ad serving service, so I'm already blocking the domain altogether. I'm also hiding the placeholders on the website using the following:

```
forum.ge##.tableborder > table > tbody > tr > .row4:nth-of-type(2) > table > tbody > tr > .desc
forum.ge##body > table > tbody > tr > td:nth-of-type(2)
```

The point is, I'm not asking for help; I just thought that it's a good idea to start cosmetic filters with `##body >`, so it won't match multiple elements by default.

**Comment by gorhill** [comment]
I can reproduce.

uBO should automatically prepend `body > ` when the suggested filter is still ambiguous after using all the component in the stack.
