### ISSUE TITLE
Animmex at it again

### ISSUE THREAD

**Issue by SuitYourself** [gorhill/uBlock#2520]
![animmex](https://cloud.githubusercontent.com/assets/25052021/24828567/2dd2fb7e-1ca3-11e7-8697-7a4411db44cf.png)
https://www.animmex.tv/video/40920/prison-break-s05e01-ogygia

Just posting in case you weren't aware, if you are or if the unreleased RC versions already address, please ignore.

When clicking the play button, Animmex opens another window for a split second then closes it, then displays the adblock screen within the video screen area.

Win 7 64bit
Latest Chrome: 58.0.3000.4
uBlock version: uBlock Origin v1.11.4

**Comment by mapx-** [comment]
try
```
@@/^((?!wwwpromoter.com|cpmstar|mgid.com|popads|cmpstar.com|oclasrv.com|onclickads.net|.js|onclkds).)*$/$script,third-party,domain=finalservers.net
@@/^((?!wwwpromoter.com|cpmstar|mgid.com|popads|cmpstar.com|oclasrv.com|onclickads.net|.js|onclkds).)*$/$script,third-party,domain=animmex.tv
@@|https://$image,domain=animmex.tv|finalservers.net,third-party
```

**Comment by SuitYourself** [comment]
Thanks mapx!

Works like a charm. 
Still get a blank tab open then close for a split second, but other than that, all perfect!

<3

**Comment by uBlock-user** [comment]
Remove those three white-listing filters and add this - `||finalservers.net$inline-script`

**Comment by gorhill** [comment]
> add this - `||finalservers.net$inline-script`

The video won't start with this.

**Comment by gorhill** [comment]
The problem here is that uBO's `bab-defuser.js` scriptlet does not work because the blockadblock inline script is placed at the top of the page, so it executes before uBO can inject the defuser.

I will have to look for a solution for this, I need to experiment -- that will be a future version.

**Comment by uBlock-user** [comment]
> The video won't start with this.

I suggested that based on the filter you added in uBlockOrigin/uAssets#144 - `||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz$inline-script`

**Comment by uBlock-user** [comment]
> because the blockadblock inline script is placed at the top of the page

Ah! So basically a race condition is preventing the execution of the filter.

**Comment by gorhill** [comment]
Yes, the roundtrip content script => main process => content script causes enough delay that when uBO's content script finally inject the scriptlet, the blockadblock code has already executed. I have been pondering various solutions, this will require experimentation.

**Comment by SuitYourself** [comment]
I managed to screen shot what it was loading up for a split second, not sure if it is of any help.
![image1](https://cloud.githubusercontent.com/assets/25052021/24829619/b7a5d23a-1cb8-11e7-8a73-4923fa0da482.png)

**Comment by SuitYourself** [comment]
ad.directrev.com*
amx.cdn-r2.*
amx-assets-1.*

Also seen these popping up - unsure if they are of any use to you guys.

**Comment by SuitYourself** [comment]
Dunno much about this coding stuff for this uBlock, but does anything like this work?

*.*##script:inject(bab-defuser.js)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

I hadn't realized this was not uAsset here yesterday. Filter issues must not be filed here.
