### ISSUE TITLE
Add more enterprise friendly network blocking statistics - Feature Request

### ISSUE THREAD

**Issue by kurtfalde** [gorhill/uBlock#2521]
### Describe the issue
Ublock currently tracks # of requests blocked on a page as well as total blocked since install.  Depending on the browser this is stored in various locations on the system which are obtainable but not in the easiest fashion for an enterprise looking to add metrics around adblocking.  If possible it would be nice to write out perhaps to an application event id with source of Ublock statistics on a daily basis or maybe on a browser open/close basis etc.  These stats could be more easily gathered via normal enterprise methods such as Windows Event Forwarding or various SIEM solutions (Splunk etc..) to allow reporting across the enterprise on blocked requests per month/day etc.

### Steps for anyone to reproduce the issue

N/A - Feature request

### Your settings

- OS/version: ALL
- Browser/version: ALL
- uBlock Origin version: ALL

##### Your filter lists

Default filter lists

**Comment by Atavic** [comment]
A log file?

**Comment by kurtfalde** [comment]
Preferably event IDs as this is the most commonly / easiest thing to collect / parse.  

Thinking on browser close log into application event log
Source-UBlock
In the data section.
Browser-Firefox/Chrome/Edge
Total Requests blocked this session
It should already have the machine name and user name in the event properties

**Comment by gorhill** [comment]
Sounds like a feature a contracted developer would implement for a specific purpose and for specific parties, of no interest to plain users.

I do not intend to add code useful only to "enterprise" in uBO -- it's completely and uncompromisingly a tool dedicated to users, and on my side this is a hobby, not a paid work.

**Comment by gorhill** [comment]
Anyways, I don't see the point of adding this to uBO or any specific blockers. Just create an extension which listens to `webRequest.onErrorOccurred`/`webRequest.onCompleted` to find out what is blocked and what is not blocked, this will work regardless of which blocker(s) is in use.
