### ISSUE TITLE
Can't log into walgreens.com

### ISSUE THREAD

**Issue by kanfyooz** [gorhill/uBlock#2522]
uBlock Origin 1.11.4.  Can't log into my account at walgreens.com [[ https://www.walgreens.com/login.jsp ]] with uBlock Origin 1.11.4 on.  Have to deselect uBlock for the entire site.  I can make a new account at walgreens.com but can't log into it.  I leave uBlock on and only deselect for the walgreens.com site.  uBlock so far has worked while on with every other site.

Using firefox 52.0.2 32bit on win 7 pro.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by mapx-** [comment]
filter issue, try adding
`@@||assets.adobedtm.com^$script,domain=walgreens.com`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
