### ISSUE TITLE
[Question] Static filter syntax: how can I define a filter to apply to all URL?

### ISSUE THREAD

**Issue by simonbcn** [gorhill/uBlock#2523]
Firefox 52.0.2

I live in Spain and, because of the _brilliant idea_ of the European Commission, I have to see on every website a cookie warning. I want define general rules to suppress all divs with name similar like: _...cookie..._
I have defined these filters:
```
*##.future-cookie-bar
*###adviceCookies
*##.uso-cookie
*###cookieslaw
*###bgon-cookie-bar
*###v-cookielaw
*###wrapperMensajeCookie
*###leydecookies
*###cookies-overlay
*###cookies-layer
*##.ng-scope.cookies-consent
*###contenedorCookie
*###cookie-disclosure
*##.cookies.footer
```
but it doesn't work.
Is there any way to do this?

**Comment by simonbcn** [comment]
Please delete.

**Comment by anewuser** [comment]
Add this to the text area at the bottom of the "3rd-party filters" tab: https://www.fanboy.co.nz/fanboy-cookiemonster.txt .

The next time you need help, please use [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746). Github should be used only to report bugs.
