### ISSUE TITLE
Sites can bypass 3p-script block with an XHR request.

### ISSUE THREAD

**Issue by luop90** [gorhill/uBlock#2527]
### Describe the issue
Sites can bypass `3p-script block` by eval()ing a XHR request. The only way to block this is to block _all_ third party connections. (`3p block`)

The connection shows up in the console as XHR, when in reality it is loading a script. (Content-Type header is `application/x-javascript`)

### One or more specific URLs where the issue occurs
[putlockers.cc](http://putlockers.cc) loads `http://04dn8g4f.space/991742/`

(Warning: The site is full of clickjacking -- the script that is loaded from `.space` is infact JS clickjacking code)

**Note:** in this example, EasyList has updated to block that domain. But as should be obvious from the domain name, it changes often.

### Screenshot in which the issue can be seen
[Screenshot](https://i.imgur.com/SfptCSQ.png)

The "type" of request is set to XHR, so `3p block` works, but _not_ `3p-script block`

### Steps for anyone to reproduce the issue

1. Load site
2. Watch from logger
3. 3rd party scripts are loaded by eval()ing a xhr request.

### Your settings
Globally block 3rd party frames

- OS/version: Windows 10/ChromeOS (latest)
- Browser/version: Chrome 57.0.2987.137
- uBlock Origin version: 1.11.4

##### Your filter lists
Default + all the filters under "Social" category.

##### Your custom filters (if any)
None.

**Comment by gorhill** [comment]
There is no issue.

If you do not want the site to execute a **any** javascript, block 1st-party scripts.

A site can pull data however it wants from 3rd parties (xhr, miages, whatever), and extract "secret" javascript from it, and execute it as 1st party. The only way to prevent this is to block 1st-party javascript, or as you found out, to block all 3rd-parties net work requests.

**Comment by luop90** [comment]
But shouldn't uBlock infer that if an XHR request has a `Content-Type` of `application/x-javascript`, that this is a script being loaded, and not just a normal XHR request?

**Comment by gorhill** [comment]
Why would a server specifically set the `Content-Type` to `application/x-javascript`? The data could still be sent  as plain text and executed through `eval`. The javascript payload could be sent as part of an image, or CSS resource. The bottom line is that you are trusting 1st-party javascript, and you just found out you can't trust 1st-party javascript.

**Comment by gorhill** [comment]
Try `putlockers.cc##script:inject(noeval.js)`. If this fixes the clickjack issue without breaking legitimate functionality, I will add it to uBO filters.

**Comment by luop90** [comment]
Works! The only eval() attempted (from looking at the console) is the clickjacking script. The rest of the site works fine.
