### ISSUE TITLE
ublock origin blocking rightclick search google popup

### ISSUE THREAD

**Issue by AbhiDGamer** [gorhill/uBlock#2530]
### Description
when I am on any webpage and I enable 

> _toggle the blocking of all popups for this site._

it also blocks the request for `search google for  'selected text'` which is usually very helpful while browsing as we highlight the text we want to search and then right click>>search google for selected text.

Also I've noticed that using middleclick to open a link in new tab also doesn't work in above condition first time. if you middle click the the link twice it works.

### One or more specific URLs where the issue occurs
<https://github.com/gorhill/uBlock> (when enabled popup blocking)

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **
![screenshot_2017-04-12_03-33-01](https://cloud.githubusercontent.com/assets/7191374/24932790/cf52fde8-1f30-11e7-8942-2246a368f4ba.png)
**]

### Steps for anyone to reproduce the issue

1. Go to the given url on chrome.
2. _toggle the blocking of all popups for this site._
3. select any text and search google for selected text.
4.you will see that a tab opens and closes automatically.

### My settings

- OS/version: Xubuntu 16.04 LTS
- Browser/version: Google Chrome 57.0.2987.133 (64-bit)
- uBlock Origin version: uBlock Origin v1.12.0

**Comment by uBlock-user** [comment]
Yeah that's by design. There's no heuristic method to determine popups in Chrome.

**Comment by gorhill** [comment]
Not by design, more like a caveat, which I covered in the wiki doc, but I removed it recently, I forgot this could also happen in the current scenario. I [put back the caveat in the doc](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups).

There is no real solution for this.
