### ISSUE TITLE
uBlock0 is loading other filters in background automatically.

### ISSUE THREAD

**Issue by yoursoftwarebug** [gorhill/uBlock#2531]
### Describe the issue

It seems uBlock0 is loading other filters in background automatically.

### Steps for anyone to reproduce the issue

1. In "chrome://ublock0/content/dashboard.html", deselect everything.
2. Check only "Auto-update filter lists" and "Parse and enforce cosmetic filters".
3. Add some filter URLs. Check it and update it.
4. A few days later, when I open "chrome://ublock0/content/dashboard.html" and click
these links(again, I didn't select them in the first place), it shows filter data. This means uBO is
downloading these lists in background each day.

uBlock filters​
uBlock filters – Badware risks​
uBlock filters – Experimental​​​
uBlock filters – Privacy​​​​​​​​​
uBlock filters – Unbreak​​​​​​​​​

Can you just update ONLY what I choose, and not else(especially I didn't select them)?

**Comment by yoursoftwarebug** [comment]
And what is the URL of these lists(which uBO request)?

**Comment by gwarser** [comment]
Some lists are embedded inside extension file:
![image16](https://cloud.githubusercontent.com/assets/886325/24951176/cbd7a9aa-1f73-11e7-9ab7-f34fc0296ebc.png)
and if you click on link in dashboard, then list is immediately downloaded.

**Comment by gorhill** [comment]
> click these links(again, I didn't select them in the first place), it shows filter data

What _else_ would be expected?

When you click on a list, uBO will show you the content of whatever list you click -- which may cause uBO to download it _on the spot_, this is by no mean an indication the list was pulled by uBO as part of its update mechanism, I don't even understand how you came to this conclusion.

**Comment by gorhill** [comment]
@gwarser It's unrelated that some of the lists are in the package, uBO will show the content of a list clicked, and if to do so require to download the list, it will do it.
