### ISSUE TITLE
Facebook Photo Uploads

### ISSUE THREAD

**Issue by Total2Blue** [gorhill/uBlock#2536]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Trying to upload photo's to personal Timeline or Group in Facebook results in an error in the Linux Mint 18.1 version of Firefox and Chromium. uBlock Origin has to be disabled for Facebook in order to upload. 

### One or more specific URLs where the issue occurs
https://www.facebook.com/

[URL(s) for issue on a specific site are **mandatory**]
https://www.facebook.com/

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
![screenshot at 2017-04-12 20-10-43](https://cloud.githubusercontent.com/assets/27383649/24983405/363b63a6-1fbd-11e7-8b38-29e0f3044ce7.jpg)

### Steps for anyone to reproduce the issue

Log into ones Facebook Account
Under "What's on your mind?", click on Photo/Video
Choose a picture to upload
Click on Open
At this point, it gives me and error with a Retry box saying to try later. 

If I disable uBlock Origin for this site and follow the steps, it works and I am able to upload the picture.

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  Linux Mint Mate 18.1
- Browser/version:  Firefox is version 52.0.2 and Chromium is version Version 57.0.2987.98
- uBlock Origin version: Firefox - uBlock Origin v1.12.0 , Chromium uBlock Origin v1.11.4

##### Your filter lists

Default filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
None

**Comment by Aeonflame** [comment]
I am also experiencing this issue.

**Comment by Mikerox9** [comment]
upload.facebook.com is blocked. I disabled uBlock and uploads work fine

**Comment by copydoc** [comment]
add me to the list, this error occurs after the recent UBO build and in firefox 52.0.2 (64-bit). Chrome is fine.

**Comment by Eeems** [comment]
Have you tried whitelisting upload.facebook.com?

**Comment by Total2Blue** [comment]
I've tried whitelisting both upload.facebook.com as well as pixel.facebook.com with no luck.

**Comment by damnnative** [comment]
+1 me too. Disabling uBO restores upload functionality. uBO 1.12.0, uBOE 2.20 default options and filters plus AakList.

**Comment by copydoc** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } White listing does nothing. I'm turning off UBO just for Facebook. Other sites seem ok. 




On Wednesday, April 12, 2017, 11:57 PM, bhtbht <notifications@github.com> wrote:


me too. The problem occurs with Opera Stable 44.0.2510.1218, ublock origin 1.11.4, windows 10 x64 v1703.

**Comment by rorosaurus** [comment]
+1, noticed this issue today as well.  Disabling uBlock fixes the issue.  Tried adding a temporary rule for pixel.facebook.com and upload.facebook.com with no luck... it still gets blocked.

**Comment by rorosaurus** [comment]
```
Static filter ||facebook.com/ajax/*logging found in:
EasyPrivacy
Static filter ||pixel.facebook.com^ found in:
EasyPrivacy
```

**Comment by rorosaurus** [comment]
Solution, for those following this thread! 😃   Add the below lines to your temporary/permanent rules.  These were generated by clicking the "--" column on the problematic rows (during the upload) in logger, then using the "Dynamic URL filtering" UI to toggle all the blocked items to allowed.

```
www.facebook.com https://pixel.facebook.com image allow
www.facebook.com https://pixel.facebook.com/ajax image allow
www.facebook.com https://pixel.facebook.com/ajax/photos image allow
www.facebook.com https://pixel.facebook.com/ajax/photos/waterfall.php image allow
www.facebook.com https://pixel.facebook.com/ajax/photos/waterfall.php?__a=1&__af=iw&__be=-1&__dyn=7AmajEzUGByA5Q9UoHaEWC5ER6yUmyVbGAEG8zCC_8267UDAyoS2N6wAxu13wFG2KfgjyR88xK5WAzEgVrDG4XzErz8iGt0TyKum4UpKq4G-FFUkxvz8-cxnxm1iyECUym2m4oqyUfe5FL-4VZ1G7WAxx4yplyWxmrxqawzKnh45EgAwzCwYypUhKHxhau4u9KiEKcGcw&__pc=EXP2%3ADEFAULT&__req=m&__rev=2953805&__user=1293750795&asyncSignal=2292&data=%7B%22qn%22%3A%223afc11a43e308ad8f8891b0d7c23e046%22%2C%22step%22%3A4%2C%22uploader%22%3A%22chat%22%2C%22upload_id%22%3A%22upload_1024%22%2C%22preview_attachments%22%3A%5B%7B%22upload_id%22%3A%22upload_1024%22%2C%22attach_type%22%3A%22photo%22%2C%22preview_uploading%22%3Atrue%2C%22preview_width%22%3A113%2C%22preview_height%22%3A48%7D%5D%7D&fb_dtsg=AQHVP5oNSwJ2%3AAQFS7fBwgEM5&logging=26581728680531117883119745058658170835510266119103697753 image allow
www.facebook.com https://upload.facebook.com xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax/mercury xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax/mercury/upload.php xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax/mercury/upload.php?dpr=1&__user=1293750795&__a=1&__dyn=7AmajEzUGByA5Q9UoHaEWC5ER6yUmyVbGAEG8zCC_8267UDAyoS2N6wAxu13wFG2KfgjyR88xK5WAzEgVrDG4XzErz8iGt0TyKum4UpKq4G-FFUkxvz8-cxnxm1iyECUym2m4oqyUfe5FL-4VZ1G7WAxx4yplyWxmrxqawzKnh45EgAwzCwYypUhKHxhau4u9KiEKcGcw&__af=iw&__req=l&__be=-1&__pc=EXP2%3ADEFAULT&__rev=2953805&fb_dtsg=AQHVP5oNSwJ2%3AAQFS7fBwgEM5&logging=26581728680531117883119745058658170835510266119103697753&ft[tn]=%2BM xmlhttprequest allow
```

Please upvote this issue on the proper repository: https://github.com/uBlockOrigin/uAssets/issues/367

**Comment by Richard500** [comment]
I have this problem which only developed within the last 24 hours.  I have had to disable Ublock / Ublock Origin to re-enable the upload facility.  I have run Firefox in safe mode : uploads work, ALL Extensions enabled and uploads are OK but as soon as the Ublock plug in is activated the uploads fail again.  Why don't you just undo what ever you did 24 hours ago or "ship" a fix. I don't see why we "users" should have to fix "code".

**Comment by SMed79** [comment]
Someone has already try to update filters lists before reporting the issue ?!!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

https://forums.lanik.us/viewtopic.php?p=116562#p116562

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues/367#issuecomment-293890058
