### ISSUE TITLE
Absolutely too strict

### ISSUE THREAD

**Issue by slarta** [gorhill/uBlock#2537]
The AddOn will turn on automatically, even if it has been turned off before. It also turns off when you visit certain websites. This is an intrusion into my personal sphere.
OFF must be OFF.
I'm not a fighter against advertising and tracking, I'm just using this add-on temporarily.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
