### ISSUE TITLE
Baidu search result is blocked on chrome 40

### ISSUE THREAD

**Issue by ywyywy** [gorhill/uBlock#2538]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Use baidu to search something,the result is blocked.The problem happened on March 7.I tried to install a old version of ublock origin,the problem still occurred.But use ublock,the result don't be blocked.And use the newest chrome to search,the result is shown.
Watch the Logger,it's because the rule--gate.baidu.com,m.baidu.com###container.But the result's url is https://www.baidu.com/s?wd=xx..x  Maybe it only happened on chrome 40.

### One or more specific URLs where the issue occurs
https://www.baidu.com/

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![blocked](http://i.imgur.com/35itHob.jpg)
![disabled](http://i.imgur.com/kTNwdbl.jpg)
![logger](http://i.imgur.com/Qsmczqn.jpg)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
1.visit the website(www.baidu.com)
2.type the word,and click the blue search button(百度一下)
3.go to the result page

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7 Ultimate Edition SP1 (build 7601), 64-bit
- Browser/version: chrome 40.0.2214.94
- uBlock Origin version: v1.12.0

##### Your filter lists
Diablo AdFilters​​-https://coding.net/u/HalfLife/p/list/git/raw/master/ad.txt
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Could you check to see if the `#container` element is inside an `iframe` on Chromium 40? Also, any errors reported at the developer console for the page?

**Comment by ywyywy** [comment]
@gorhill It might be.I can see the picture in an iframe.But is the way I do it correct?No errors in console,it's just a recruitment information.
![1](http://i.imgur.com/uLc2G8N.jpg)
![2](http://i.imgur.com/oFVfO1c.jpg)
![3](http://i.imgur.com/UXNz3C0.jpg)

**Comment by gorhill** [comment]
Can you click on the `###container` filter in the logger to find out and be sure where the filter comes from?

**Comment by ywyywy** [comment]
Click it,there is no pop-up window.
Click the pink ones,there are pops.Before Mar 7,the result was shown.May is it because the chrome is portable?

**Comment by gorhill** [comment]
> Click it,there is no pop-up window.

You should see something like this, it tells from which list the cosmetic filter comes from:

![a](https://cloud.githubusercontent.com/assets/585534/25012892/d6033cce-203f-11e7-9095-8c5d21006273.png)

**Comment by ywyywy** [comment]
I clicked ###container ,but it didn't pop something like above.Others had.
I only subscribe Diablo AdFilters one.
I installed the chrome 41.0.2272.118 just now,the ###container didn't apply,search result was shown.

**Comment by Atavic** [comment]
Investigate Diablo AdFilter, it may block your search.

**Comment by gorhill** [comment]
Most likely explanation is that there was an issue in Diablo AdFilters and it got fixed while the issue here was investigated.
