### ISSUE TITLE
Can't upload photos to Facebook when uBlock is enabled.

### ISSUE THREAD

**Issue by lnx64** [gorhill/uBlock#2540]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
First of all, I'm not sure if this is a filtering issue or not.  When on Facebook, if you attempt to upload any photos, either on your wall, or in a message, it will fail to upload with an error.  If you turn off Ublock for this page, the photos go through just fine.  Other users in Facebooks help pages are having the same problem, and I verified that if they too turn off Ublock, they can upload photos just fine also.  (Of note, at least one person with Ublock is not running into this issue, but I don't know what browser or OS they are using.).

I have removed ~/.config/google-chrome as a test and started the browser fresh, and this did not resolve the issue.

### One or more specific URLs where the issue occurs
http://www.facebook.com
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![screenshot from 2017-04-13 19-42-19](https://cloud.githubusercontent.com/assets/2136976/25028316/6a74290e-2081-11e7-9a2e-906c31a539d8.png)
![screenshot from 2017-04-13 19-42-40](https://cloud.githubusercontent.com/assets/2136976/25028317/6a764e8c-2081-11e7-9c39-9a68e5dc35cd.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Turn on Ublock with Google Chrome
2.  Go to Facebook.com, and try to upload a picture to share a picture on your wall.
### Your settings
They are default, nothing has been changed.
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Ubuntu Gnome 16.10
- Browser/version: Google Chrome 57.0.2987.133 (64-bit)
- uBlock Origin version: v1.12.0

##### Your filter lists
Default filter lists (I don't know about FRA or badware risks, I never changed anything since it was installed.  Whatever you set as default on a fresh install)
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
None, it's entirely default.

**Comment by lnx64** [comment]
It appears it's also affecting Adblock Plus also now..  So I don't know if this is something both ad blockers will need to fix, or if Facebook is doing this on purpose.  Hopefully someone can pitch in as to what is going on here.

**Comment by anewuser** [comment]
Please close this issue.

Refer to https://github.com/gorhill/uBlock/issues/2536#issuecomment-293886244

**Comment by lnx64** [comment]
I apologize, I didn't find it initially.  It wasn't my intention to create a duplicate.
