### ISSUE TITLE
Ublock Origin blocking photos from being uploaded to Facebook

### ISSUE THREAD

**Issue by wietop** [gorhill/uBlock#2541]
Ublock Origin is blocking all photos from being uploaded to Facebook. As soon as I disabled it in Firefox, the photos were able to load. I prefer Ublock to Adblock Plus and would like to get the issue fixed.

**Comment by anewuser** [comment]
Please close this issue and refrain from posting on this repository again.

Refer to https://github.com/gorhill/uBlock/issues/2536#issuecomment-293886244

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
