### ISSUE TITLE
Single page applications nodes leak with uBlock on pages change

### ISSUE THREAD

**Issue by artaommahe** [gorhill/uBlock#2542]
### Describe the issue
On SPA page change there is nodes leak when uBlock extension enabled

### Steps for anyone to reproduce the issue
- chrome incognito mode, all extensions are disabled except uBlock
- load example http://plnkr.co/edit/x6Jo42UOM2XFivzTEyDv?p=preview (ng4 simple app with 2 pages(routes) with one link to another route on each page)
- open devtools, timeline, start recording
- make 20-30 clicks on links
- collect garbage (timeline tab button)
- stop timeline recording, display memory graphs
- see nodes leak
![image](https://cloud.githubusercontent.com/assets/1944061/25040655/68a95ff8-2113-11e7-83ca-5c3fb747c77f.png)
- disable uBlock, reload page, repeat
- no nodes leak
![image](https://cloud.githubusercontent.com/assets/1944061/25040659/6cd54326-2113-11e7-90dc-5e6ad08fe970.png)

### Your settings

**Browser:** Chromium Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
**uBlock Origin:** 1.12.0

##### Your filter lists
Default lists

**Comment by gorhill** [comment]
Can't reproduce:

The difference from your test is that I allowed more time at the end for the garbage collection -- you can't assume that the browser will tidy up everything within 2 seconds after you stop interacting with the page.

Repeat your test with these extra steps for a more careful profiling:

- Open new tab with `http://plnkr.co/edit/x6Jo42UOM2XFivzTEyDv?p=preview`.
- Open dev tools, select Timeline.
- Un-check "Screenshot", check "Memory".
- Click "Collect garbage".
- Click "Record".
- Wait 15 seconds, _do not interact with the page_.
- Click 10 times on the links.
- Click "Collect garbage" three times.
- Wait 15 seconds, _do not interact with the page_.
- Click "Stop".

Result:

![a](https://cloud.githubusercontent.com/assets/585534/25043347/4c94d610-20ed-11e7-83f9-a9c1ac5b7f53.png)

uBO makes use of MutationObserver, this could be what causes the browser's garbage collector to behave differently.

**Comment by artaommahe** [comment]
@gorhill hm, this time it collected nodes immediately O_o browsers are strange.. sry
