### ISSUE TITLE
Facebook Photo Upload Error

### ISSUE THREAD

**Issue by dailyjoe** [gorhill/uBlock#2543]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Cannot add photos in FaceBook Status since the April 11, 2017 update. They will upload into albums only.  Disabled uBLOCK and all photos upload without error.

### One or more specific URLs where the issue occurs
www.facebook.com

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![screen shot 2017-04-15 at 5 23 40 am](https://cloud.githubusercontent.com/assets/27557768/25063546/e1ee2410-219b-11e7-8436-99c8998fd39d.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: OS X El Capitan 10.11.8
- Browser/version:  Firefox 52.0.2 (64-bit)
- uBlock Origin version: 1.12.0

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues/367#issuecomment-293890058
