### ISSUE TITLE
Element picker doesn't work on www.hotcleaner.com

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#2545]
### Describe the issue
Element picker instantly closes.

### One or more specific URLs where the issue occurs
https://www.hotcleaner.com/

### Steps for anyone to reproduce the issue
1. Open https://www.hotcleaner.com/
2. Try to block something using element picker
3. You can't — element picker pops for a moment then closes

### Your settings
-Windows 10 x64 v1607
-Latest Chrome beta (Version 58.0.3029.68 beta (64-bit))
-Latest uBO (1.12.1)
-[Click&Clean](https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod) (installed, disabled)
-[Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) + Anti-Adblock Killer

##### Your filter lists
All non-regional + All Russian

##### Your custom filters (if any)
https://easylist-downloads.adblockplus.org/cntblock.txt

**Comment by gorhill** [comment]
The page has code which removes uBO's element picker from the DOM. It does this for ABP and Adguard as well. You will need to use a workaround:

- disable inline scripts (using dynamic filtering)
- reload the page
- use the element picker, create filter
- re-enable inline scripts
- reload the page

**Comment by okiehsch** [comment]
Adding the filter `hotcleaner.com##script:inject(abort-on-property-read.js, onmousedown)` also works,
atleast on my end.

**Comment by mikhaelkh** [comment]
@okiehsch wow, that worked, is there a tutorial on how to create [extended syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax) static filters?
@gorhill your workaround works too
It seems like this issue belongs [there](https://github.com/reek/anti-adblock-killer), but that project hasn't updated in a while. Is there any Tampermonkey scripts like `anti-adblock-killer` which blocks this kinds of stuff?
