### ISSUE TITLE
Element picker doesn't work on latest Nightly

### ISSUE THREAD

**Issue by azes** [gorhill/uBlock#2546]
### Your settings

- Browser/version: Nightly (2017/04/17)
- uBlock Origin version: 1.12.1 Webextension

Checked in new profile.

**Comment by SW1FT** [comment]
> Do not submit issues which can be reproduced only on Chrome Canary or Firefox Nightly: these are not stable browser versions and in all likelihood, whatever issue is not within uBO.
> Report only if you can reproduce in an official stable release, or a beta release.
