### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#2549]
I am sorry but I couldn't for the life of me find a way to do this under the wiki section or anywhere else. Given its a GitHub component, felt maybe this will do.

For the wiki page: https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist

Can you kindly add the "default rules" (_the ones that ship out of the box_) there for reference (in case anyone actually does delete them instead of properly commenting them out) and also for anyone wishing to restore them (they can just copy and paste it). 

I have to admit, I looked to see if it was available somewhere already but I didn't see it, apologies if I missed it and plus having them as part of the documentation can't hurt, only makes it more robust. I would have been happy to "clone" and edit it and send you a pull request but didn't see that option. Thank you.

**Comment by seanrand** [comment]
The default whitelist is
```
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
loopconversation.about-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
```
(from [src/js/background.js](https://github.com/gorhill/uBlock/blob/50158265469d68efd45e7ddfb221e7f9d7a65896/src/js/background.js#L104-L111))

**Comment by gorhill** [comment]
Added default rules as suggested: <https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist/_compare/e996683ab2dcb692e767769b3ae13bacce48a8b7...6729f722717ab0132ea561af33717a691acd0ff3>.

`loopconversation.about-scheme` is not in there, I need to remove it, it is obsolete (t'was Firefox Hello).

**Comment by GuardianMajor** [comment]
@seanrand please read what I said, I didn't say I don't know it or need it, I said it would be nice to add to the **wiki page**, your response and my own 25+ year of reading source won't change that.

@gorhill merci mon ami 👍 appreciate it.
