### ISSUE TITLE
Bug in temporarily disabling uBlock or Wiki is in error

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#255]
Either the uBlock Wiki is wrong, or there is a bug in uBlock... or my brain is not working at the moment :-).

According to the uBlock Wiki ( https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere ) :

"The ability to turn off uBlock everywhere has been requested many times: #40, #403.
...the ability to "disable" uBlock everywhere is now available, as a side effect of the ability to create a global allow rule for all network requests.
... it's as good as 'globally turn off uBlock'."

This does not appear to be right, or there is a bug.  (BTW, within the Wiki, the issue #'s are pointing to the wrong places too, but that's trivial.)

For example:
1. Go to your uBlock Dashboard.
2. Select the 'My filters' tab.
3. Add a filter for github.com.
4. Apply the filter changes.
5. Open a new tab.
6. Click on the uBlock toolbar button.
7. Create the global allow rule for all network requests as shown in the Wiki.
8. Enter github.com into the Location Bar (urlbar).

uBlock will prevent you from going to github.

Currently, the only way to 'globally turn off uBlock' appears to be by completely disabling the extension.  This can be problematic because Firefox has a longstanding bug that sometimes causes it to move/reorder toolbar buttons when extensions are disabled and then re-enabled.  Also, uBlock begins with a 'u', which is towards the end of the alphabet; if the user has many extensions installed, there can be quite a bit of scrolling to find uBlock in the crowded extensions list.

Is the Wiki wrong, or is there a bug in uBlock (or am I just mistaken in my understanding)?

As an aside:
Why would anyone want to quickly disable such a great and flexible extension like uBlock?

Two cases immediately pop into mind:
1. The user cannot get a website to work, and they don't have the time or expertise to diagnose and fix the problem.  Quickly toggling uBlock gets around the issue (with the costs and risks involved in momentarily using an unfiltered web).
2. The user wants to perform a transaction in which advertising/tracking technologies are required.  For example, perhaps a user wants to take advantage of a special offer made available on site A for site B.  The user doesn't know which technologies site B will use to determine the user was referred from site A (and the offer on Site B is only available to visitors from site A).  Momentarily disabling uBlock will allow the user to accomplish this goal.  This is common for coupons, discounts, affiliate programs, and other deals.

**Comment by gorhill** [comment]
Works as expected: this is a suggestd workaround which may and may not work depending on whether there are current dynamic rules in use, and since now there is strict blocking (wiki was written before strict blocking), strict blocking has precedence over dynamic filtering for `doc` request.

This has also been [covered amply before](https://github.com/chrisaljoudi/uBlock/issues/40) and I don't intend to add this feature, workaround is to disable the extension, all browser provide this ability.

**Comment by Gitoffthelawn** [comment]
Too bad... I was hoping that the Wiki was correct or I was simply mistaken!  :-)

If the info in the Wiki was correct, I thought it would be a good idea to dim the uBlock toolbar button (like it does for whitelisted hosts) if the "All" dynamic filter was used as suggested in the Wiki.  But since that workaround has a different effect than disabling uBlock, I don't think that would be a good idea.
