### ISSUE TITLE
Start audio advertising with active adblock

### ISSUE THREAD

**Issue by matteo78it** [gorhill/uBlock#2551]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Hello,
If I visit this site, multiplayer.it, with active adblock even if I do not see the advertisement part the same audio and it is wanted by the manager. What does not happen with adulterated adblood

### One or more specific URLs where the issue occurs

www.multiplayer.it

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

![immagine](https://cloud.githubusercontent.com/assets/17781453/25228577/2c57af1e-25cd-11e7-885c-f6c3114abff6.png)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

win 10 64 bit 

ublock origin 1.12.1

FF 52.0.2 (32 bit)
##### Your filter lists

Default filter lists + ITA: EasyList Italy + ITA: ABP X Files

##### Your custom filters (if any)
@@||multiplayer.it^$generichide
@@||imasdk.googleapis.com^$domain=multiplayer.it

! 18/4/2017, 21:41:04 http://multiplayer.it/
multiplayer.it###personalization_ads

! 19/4/2017, 10:16:49 http://multiplayer.it/notizie/182281-the-witcher-3-wild-hunt-lautore-dei-romanzi-di-the-witcher-nega-che-i-videogiochi-abbiano-reso-la-sua-saga-piu-celebre-a-livello-mondiale.html
||guardiansofthegalaxy2.movieplayer.it/static/calamita.png$image

! 19/4/2017, 10:17:04 http://multiplayer.it/notizie/182281-the-witcher-3-wild-hunt-lautore-dei-romanzi-di-the-witcher-nega-che-i-videogiochi-abbiano-reso-la-sua-saga-piu-celebre-a-livello-mondiale.html
||guardiansofthegalaxy2.movieplayer.it/static/groot-pre.png$image

! 19/4/2017, 10:17:09 http://multiplayer.it/notizie/182281-the-witcher-3-wild-hunt-lautore-dei-romanzi-di-the-witcher-nega-che-i-videogiochi-abbiano-reso-la-sua-saga-piu-celebre-a-livello-mondiale.html
||guardiansofthegalaxy2.movieplayer.it/static/voce.png$image

! 19/4/2017, 10:17:13 http://multiplayer.it/notizie/182281-the-witcher-3-wild-hunt-lautore-dei-romanzi-di-the-witcher-nega-che-i-videogiochi-abbiano-reso-la-sua-saga-piu-celebre-a-livello-mondiale.html
||guardiansofthegalaxy2.movieplayer.it/static/bomba-mani.png$image

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
