### ISSUE TITLE
Have "Block pop-ups" option in default behaviour section

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [gorhill/uBlock#2554]
I would find it very useful if I didn't have to enable pop-up blocking on a per-side basis so that I have to blacklist each site rather than whitelist. It would be much better if in the "Default behaviours" section there was an option called "Block pop-ups" so that I could make it an opt-out thing rather than an opt-in. Obviously this option doesn't have to be enabled by default, but it would be nice to at least have it there if one wants it.

**Comment by gorhill** [comment]
Just add the rule `no-popups: * true` in _My rules_.

**Comment by SeventhSonOfASeventhSon** [comment]
This is the kind of thing normally expected to be in the GUI options though so it would be nice if you also included it there. I can understand not having all of the options there, but this really is something most people would expect to find there and not have to set it by knowing a certain command in the rules. You have all the options you have when in the main menu of uBlock in the preferences bit, except for the pop-up blocking, so that inconstancy is also a little strange. It makes no sense for them all to be there and just not the pop-up blocking ability.

**Comment by gorhill** [comment]
There are [caveats](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups) with blocking popups unconditionally with Chromium-based browsers, I rather not see issues repeatedly opened about this here. Also, legitimate popups are a common thing -- so blocking all of them unconditionally is not encouraged. Re. _"for them all"_: strict-blocking is another switch for which I also chose to not provide a way to change global default.

**Comment by SeventhSonOfASeventhSon** [comment]
It is true that there many legitimate ones, however if the user feels that for security they would prefer to always block them, then that is their call. And I suppose that that is why you at least give some sort of an option to do it. However I think that it could work if you just had an option which would block pop-ups, but also notify the user of them being blocked so that they may choose to show or block on a pop-up-per-pop-up basis. Other utilities have this ability, it would maybe a nice add to uBlock Origin.

I'm sure that with a little thought you could make this work as a flexible feature which would allow large control over pop-ups.

**Comment by gorhill** [comment]
Popup blocking should never be described as a "security" feature, it's just about automatically closing tabs, not about blocking network requests.
