### ISSUE TITLE
ISSUE: CSN not being anti-adblocked.

### ISSUE THREAD

**Issue by hiya-tiger** [gorhill/uBlock#2555]
### Describe the issue

http://i.imgur.com/a/dwSje.png

I get an anti-adblock awareness image even though I have Reek's anti-adblock enabled.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
