### ISSUE TITLE
Dynamic filtering allow-all still blocks ads, log shows images allowed workers blocked.

### ISSUE THREAD

**Issue by antisymmetric** [gorhill/uBlock#2556]
Hello,

Details:

Win 10 Education Edition 64-bit Version 1607 
OS Build 14393.1066

Google Chrome Version 57.0.2987.133 (64-bit)

uBlock Origin 1.12.1

Filter: Default 

This issue seems to appear on some sites, I first noticed it when myanimelist.net put up its please disable adblocker ad despite the dynamic fitering set to allow all.

![image](https://cloud.githubusercontent.com/assets/27951554/25330558/f301fb9e-28d7-11e7-87e6-46d306462628.png)

But the logger shows the image requests as allowed but the workers are blocked causing the panels to dissapear. The ublock panel shows 0% blocked.

![image](https://cloud.githubusercontent.com/assets/27951554/25331388/cf36e5dc-28da-11e7-9543-7014918f813e.png)

The reason I think that this is a ublock issue is that when I whitelist the ads return:

![image](https://cloud.githubusercontent.com/assets/27951554/25330662/5670375e-28d8-11e7-8329-7f722937266b.png)

Further example: www.gunnerkrigg.com

![image](https://cloud.githubusercontent.com/assets/27951554/25331037/8cd3ff1e-28d9-11e7-8cab-bf7c0052f918.png)

![image](https://cloud.githubusercontent.com/assets/27951554/25331080/af865336-28d9-11e7-9dd7-f15feb665ac5.png)

![image](https://cloud.githubusercontent.com/assets/27951554/25331209/0acb6d94-28da-11e7-854d-10bb87d9de3f.png)

This renders dynamic filtering white list a bit useless for many sites and it can be hard to notice unless they put up a please pay us placeholder.

**Comment by gorhill** [comment]
Fixed with 02323826950c7d99b65d93f9edb8fa018159973c.
