### ISSUE TITLE
overlay-buster.js issue

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#2557]
windows 10
chrome Version 58.0.3029.81 beta (64-bit)
uBo 1.12.1
easylist, easyprivacy, ublock filters

steps:
- go to https://www.im-infected.com/hijacker/how-to-remove-planktab.html
- add (removing the first anti adblocking overlay - background one)
`im-infected.com##script:inject(overlay-buster.js)`
- try creating another hiding (cosmetic) filter

==> the element picker does not work (quickly closed, probably by the same overlay-buster.js )

(the anti adblocking crap can be fixed using this filter
https://github.com/uBlockOrigin/uAssets/issues/379#issuecomment-296483088)

**Comment by gorhill** [comment]
Looks like the site changed and this is no longer an issue. In any case, I consider a filter list issue.
