### ISSUE TITLE
Updating Fanboy’s Social Blocking List‎ let's FF ESR crash on closing

### ISSUE THREAD

**Issue by gizmo21** [gorhill/uBlock#256]
After updating and activating "Fanboy’s Social Blocking List‎ (adblockplus.org): 12.438 benutzt aus 12.438 Leere den Cache" ESR crashes reproducable on closing F,F even with only startpage is open.

Windows Server 2008 R2 Firefox ESR 31.7.0 

AdapterDeviceID: 0x0000
AdapterVendorID: 0x0000
Add-ons: %7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.7.0,uBlock0%40raymondhill.net:0.9.8.1.1-signed
AvailablePageFile: 24406642688
AvailablePhysicalMemory: 11565359104
AvailableVirtualMemory: 3902955520

ProductName: Firefox
ReleaseChannel: esr

Theme: classic/1.0
Throttleable: 1
TotalPageFile: 25746518016
TotalPhysicalMemory: 12874207232
TotalVirtualMemory: 4294836224
Vendor: Mozilla
Version: 31.7.0
useragent_locale: de

As long as i let it un-updated with addons integrated old list-version, it's working:
Fanboy’s Social Blocking List‎ (adblockplus.org): 12.386 benutzt aus 12.386veraltet

**Comment by gorhill** [comment]
I installed FF 31.7 ESR and uBlock Origin 0.9.8.2, and following the described steps, I could not reproduce a crash. I run on Linux however, I can't test on Windows.

Maybe try the following:

- Backup your uBlock settings.
- Quit the browser.
- [Find](https://github.com/gorhill/uBlock/blob/master/dist/README.md#firefox) and delete uBlock sqlite database, named `uBlock0.sqlite`.
- Restart the browser.
- Restore your uBlock settings using your backup file.

See if this works.

Note that I tested using 0.9.8.2, as I don't see any change from 0.9.8.1 which could explain a crash. Also, you may want to report this to Firefox's bugzilla: browsers are not supposed to crash like this from running javascript, so Firefox devs may want to investigate why this happens given it's an ESR release.

**Comment by gorhill** [comment]
Ok, I haven't been able to reproduce, and anyway a browser crash is first a FF issue: file an issue with bugzilla and link to it here.
