### ISSUE TITLE
[Question] Does uBlock efficiently blocks QUIC?

### ISSUE THREAD

**Issue by Sh1d0w** [gorhill/uBlock#2562]
As per https://blog.brave.com/quic-in-the-wild-for-google-ad-advantage/

Could not find any info on the GitHub page of the plugin whether it prevents such kind of ads and tracking?

**Comment by RoxKilly** [comment]
It does not because Chrome does not expose QUIC connections to extensons. You will need to disable it yourself. See [this post on Reddit](https://www.reddit.com/r/uBlockOrigin/comments/66k0eh/psa_disable_quic_in_your_chromiumbased_browser/) seemingly from the Dev.

**Comment by gorhill** [comment]
The answer is in the blog post you linked to.

**Comment by gorhill** [comment]
In any case, it's not even sure at this point whether the blog post is accurate: <https://bugs.chromium.org/p/chromium/issues/detail?id=715140>.

**Comment by uBlock-user** [comment]
I have QUIC enabled since a year or more and I have yet to experience any ads from youtube or google.
