### ISSUE TITLE
connect to githubusercontent.com in background - still true?

### ISSUE THREAD

**Issue by yoursoftwarebug** [gorhill/uBlock#2564]
From version 1.10(1.11?), you mentioned in other issue that *below statements are not true anymore*.

connect to githubusercontent.com in background

If this is true, why not update these pages?

https://github.com/gorhill/uBlock/wiki/Privacy-policy
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/privacy/

**Comment by gorhill** [comment]
> If this is true, why not update these pages?

I did: https://github.com/gorhill/uBlock/wiki/Privacy-policy/_compare/7bb178b9b7416716bc00c86e22cab17a4298d9eb...5c988f8e280d41a7b1c317281bc9d19db8bdc812

I realize the last paragraph does not make much sense anymore, so I just updated it: https://github.com/gorhill/uBlock/wiki/Privacy-policy/_compare/5c988f8e280d41a7b1c317281bc9d19db8bdc812...3da82c00d7af0b9f72018c277cefd64dc629dd97

**Comment by yoursoftwarebug** [comment]
@gorhill, let me one thing perfectly clear - so since v1.11, uBlock0 never connect to below URL anymore?

"https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/checksums/ublock0.txt?_=(random)"

**Comment by uBlock-user** [comment]
Yes, it doesn't. Read the 4th bullet here - https://github.com/gorhill/uBlock/pull/2314
