### ISSUE TITLE
Prevent WebRTC from leaking local IP addresses stops unifi management working

### ISSUE THREAD

**Issue by blowdart** [gorhill/uBlock#2566]
### Describe the issue

Preventing WebRTC from leaking local IP addresses stops unifi management web site working against local network cloud keys when using cloud access. No information was in the ublock logs indicating anything was blocked.

### One or more specific URLs where the issue occurs

https://unifi.ubnt.com

### Steps for anyone to reproduce the issue

1. Recently I found I could no longer use the unifi admin site to manage my local network devices, when connecting through their management cloud. Connecting via local IP address or host name worked just fine. As this happened when they pushed a software update I blamed them :)
1. After much diagnosis and disabling every plugin, incognito mode etc, all fingers pointed to ublock origin.
1. I opened the log window, and refreshed the page, but nothing showed up, except the block for Google Analytics.
1. I turned off blocking for the site, and the problem still occurred.
1. I went into the plugin settings, and disabled the option to prevent WebRTC from leaking local IP addresses. Refreshed the page, and goodness, it all works.

The Chrome console shows

```
5504.5400ms -- WEBRTC_DATA_CHANNEL_OPENING update_default
app.manage.js?v=5.4.14.0:293 35505.6350ms -- WEBRTC_DATA_CHANNEL_TIMEOUT api
(anonymous) @ app.manage.js?v=5.4.14.0:293
(anonymous) @ app.manage.js?v=5.4.14.0:292
(anonymous) @ app.manage.js?v=5.4.14.0:8
f @ app.manage.js?v=5.4.14.0:6
(anonymous) @ app.manage.js?v=5.4.14.0:6
app.manage.js?v=5.4.14.0:293 35508.0500ms -- WEBRTC_CONNECTION_ERROR WEBRTC_DATA_CHANNEL_TIMEOUT
(anonymous) @ app.manage.js?v=5.4.14.0:293
(anonymous) @ app.manage.js?v=5.4.14.0:292
app.manage.js?v=5.4.14.0:293 35511.9550ms -- WEBRTC_DATA_CHANNEL_TIMEOUT update_default
```

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10, Creators Edition, 10.0.15063
- Browser/version: Chrome  58.0.3029.81
- uBlock Origin version:  1.12.1

##### Your filter lists

Default

So I realise this scenario is pretty darned specialised, and will be impossible to diagnose unless you have some ubitiquiti kit in your local network (which makes me an unreasonable ass). I logged the issue for a couple of reasons,

1. It might help others once this gets indexed by google.
1. Could you please consider adding a log entry into the logger window when webrtc gets blocked by the setting? It would have helped diagnose the issue :)

**Comment by gorhill** [comment]
uBO just change a setting in the browser, this means you will have to disable that feature in uBO to prevent the setting in the browser.

**Comment by gorhill** [comment]
I suggest you disable the setting in uBO, and try <https://chrome.google.com/webstore/detail/webrtc-leak-prevent-toggl/kignegkkmknfpincglcjggfbgghpamim>. uBO uses the "Disable non-proxied UDP (force proxy)" internally, maybe you will have better luck with a lower setting which still prevent leakage.

In any case, there is nothing uBO can do, as said uBO merely toggle on a browser setting, everything else after this occurs on the browser side.
