### ISSUE TITLE
Does this block JS-activated  popup/popunders?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [gorhill/uBlock#2567]
Many site use JavaScript to launch new windows when a user clicks anywhere on the page.

Some examples are https://thehiddenbay.info/browse and https://katcr.co/new/.

I recently installed 1Blocker and it’s ineffective against them, at least using the included filters.
The "Hide page elements" function apparently can’t be used to block it, and I’m not savvy enough to use expressions to write additional filters. It needs the ability to block all 3rd-party JS unless the user allows it, per site.

The [Third Party Blocker](https://github.com/yene/Third-Party-Blocker.safariextension) extension for Safari helps on _some_ sites, but is no longer maintained.

Before I waste time testing uBlock, I want to know if it's more capable of blocking these potentially harmful annoyances.

**Comment by lewisje** [comment]
I tried the two sites you linked: My uBO setup (which adds many more filter-lists than the default) did not close the first popup, and it closed the second popup; my guess is that the list-authors have not yet added rules targeting the site that the first popup opens to (I tried a second time and uBO closed *that* popup).

Although I kept speaking about uBO closing some automatically opened popup windows, it *is* also able to block the inline JS that some pages use to make the popups open wherever you click; read the documentation to see how, but that does imply becoming "savvy enough to use expressions to write additional filters" or at least to copy-paste the filters that others may recommend.

**Comment by gorhill** [comment]
Medium mode worked well for me on these sites -- so that it's a filter issue.

The real problem here is someone opening an invalid issue and wasting a project maintainer's time in the name of not "wast[ing] time testing uBlock". With that attitude and disregard for project maintainers, I rather this user look for another blocker.

**Comment by uBlock-user** [comment]
There's no one size that fits all, for popups and such annoyances you will have to investigate and waste time, simple as that.

- For https://thehiddenbay.info/browse, it's third-party, so just block all third-party scripts and you're good to go.

- For KAT, I cannot reproduce it. but if you do, add - `katcr.co##script:inject(abort-on-property-read.js, TID)`
