### ISSUE TITLE
uBlock Origin prevents Bethesda.net from loading (with all filters disabled)

### ISSUE THREAD

**Issue by kamild1996** [gorhill/uBlock#2568]
The Bethesda.net page shows the loading bar on the top of the screen and never actually loads when uBlock Origin is enabled, even with every filter disabled. Disabling uBlock makes it load properly.

### One or more specific URLs where the issue occurs

Eg. https://account.bethesda.net/en/settings/redeem-code

### Screenshot in which the issue can be seen

http://imgur.com/PS7NpxY

### Steps for anyone to reproduce the issue

It's as simple as trying to visit the page above with uBlock enabled.

### Your settings

- OS/version: Windows 10 CU x64
- Browser/version: Opera 44.0
- uBlock Origin version: 1.12.1

##### Your filter lists

Unrelated (check first paragraph)

##### Your custom filters (if any)

none

**Comment by mapx-** [comment]
filter issue, add:
`@@||googletagmanager.com/gtm.js$script,domain=account.bethesda.net`

**Comment by kamild1996** [comment]
Thank you, so I guess uBlock is still blocking stuff even with all filters unchecked. TIL

**Comment by mapx-** [comment]
it seems to be due to _uBlock filters – Privacy​​​​​​​​​_

**Comment by gorhill** [comment]
> TIL

You learned wrong -- the behavior you describe is unreproducable.
