### ISSUE TITLE
Google Optimize snippet causes pages to appear blank for several seconds on page load

### ISSUE THREAD

**Issue by echeese** [gorhill/uBlock#2569]
### Describe the issue

The Google Optimize page-hiding snippet isn't activated because of uBlock and thus must wait for a timeout.

https://support.google.com/360suite/optimize/answer/7100284#deploy-page-hiding

### Workaround

This can be mitigated by calling `window.dataLayer.hide.end()` (if it exists)

### One or more specific URLs where the issue occurs

An example, one of many:
https://optimizationup.com/ (timeout reduced to 2000ms)

### Steps for anyone to reproduce the issue

1. Visit the example site
2. Wait 2 seconds
3. Page appears

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 58
- uBlock Origin version: 1.12.1

##### Your filter lists

Default filter list

**Comment by gorhill** [comment]
Why is this opened as a uBO issue and not a filter issue?
