### ISSUE TITLE
Firefox full review feedback

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#257]
Opening a meta issue to keep track of the process and related code changes, etc.

All these changes will also need to be imported in uMatrix too, which I also have submitted for full review.

**Comment by gorhill** [comment]
2015-05-27:

> 1. Synchronous SQL should not be used. The use of synchronous SQL via the storage system leads to severe responsiveness issues, and should be avoided at all costs. Please use asynchronous SQL via Sqlite.jsm (http://mzl.la/sqlite-jsm) or the `executeAsync` method, or otherwise switch to a simpler database such as JSON files or IndexedDB.
> 
> 2. SQL statements should be static strings. Dynamic SQL statement should be constucted via static strings, in combination with dynamic parameter binding via Sqlite.jsm wrappers (http://mzl.la/sqlite-jsm) or `createAsyncStatement` (https://developer.mozilla.org/en-US/docs/Storage#Binding_parameters)

Fixed with 53fc1063f9281ebbe6d5c5c50ef6ba37bb22ffe9

**Comment by gorhill** [comment]
2015-05-28:

> 1. After installing I got in the Browser Console following error:
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [mozIStorageConnection.createStatement] vapi-background.js:234:0 (
(chrome//ublock/content/js/vapi-background.js)

I could not reproduce, however I revised the code using API doc to harden code: c285ace7d84115fdcac3e2b6009a481e4dc34b91.

**Comment by 5t3f4n** [comment]
I see both [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) and [uMatrix](https://addons.mozilla.org/firefox/addon/umatrix/) are up on [AMO](https://addons.mozilla.org/firefox/user/gorhill/) and at their respective latest versions.
Keep us updated on the review process.

Btw, do the GitHub versions now auto-update to the AMO ones? Or have you changed your mind on updating directly from GitHub?

**Comment by gorhill** [comment]
uBlock Origin was fulle reviewed on July 4th, 2015.
