### ISSUE TITLE
Firefox Reader view circumvents uBO's no-large-media block

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2570]
### Describe the issue
In Firefox, when I switch to [reader view](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages), images that should be blocked by uBO's `no-large-media: * true` are not blocked.

### One or more specific URLs where the issue occurs
https://jotter.jonathankingston.co.uk/blog/2017/04/04/containers-assignment/ 

### Screenshot in which the issue can be seen
Dev tools - network panel of the regular page: browser connects but doesn't download
![3](https://cloud.githubusercontent.com/assets/12346501/25545969/ec67cd68-2c2e-11e7-8d10-650f5abfcd65.png)

Logger of the regular page:
![1](https://cloud.githubusercontent.com/assets/12346501/25545932/cc9bf54a-2c2e-11e7-8ad7-f0fac0b3fab9.png)

Dev tools after hitting Reader view icon: browser reconnects and downloads content
![4](https://cloud.githubusercontent.com/assets/12346501/25545987/f9f458ac-2c2e-11e7-9d43-17a08a2c9811.png)

Logger of the page after hitting Reader View icon
![5](https://cloud.githubusercontent.com/assets/12346501/25545984/f5ae3178-2c2e-11e7-8f91-39c729ab5efc.png)

### Steps for anyone to reproduce the issue
1. Set `no-large-media: * true` rule
2. Go to https://jotter.jonathankingston.co.uk/blog/2017/04/04/containers-assignment/ 
3. You'll notice in the logger that content is blocked.
4. Click the Reader View icon at the far right of the URL bar
5. The images that should be blocked are downloaded (shown both in the browser's network panel and uBO's logger)

### Your settings
- Browser/version: Firefox 53
- uBlock Origin version: 1.12.1

EDIT: I just noticed that the extension is fully disabled in Reader View (the uBO icon in the toolbar turns grey) so it seems this isn't an issue specific to images. This may be a browser imposed limitation. Am still posting in case I'm wong.

**Comment by gorhill** [comment]
uBO is disabled because the context is `reader.about-scheme`, and uBO is whitelisted by default for `about-scheme`. It works fine if un-whitelisted.

**Comment by gorhill** [comment]
Thinking more about it, I will try to see if I can provide the current context in the tooltip of uBO's power button, there is currently no obvious way to find out the current context was `reader.about-scheme` (have to go through the logger).

**Comment by Thorin-Oakenpants** [comment]
as per earthlng's comments [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/84#issuecomment-298173455)

```
matrix-off: about-scheme false
about-scheme * * allow
reader.about-scheme * * block
```

**Comment by gorhill** [comment]
> there is currently no obvious way to find out the current context was `reader.about-scheme`

Actually there is now, since the new popup panel was introduced in [1.27.0](https://github.com/gorhill/uBlock/releases/tag/1.27.0)
