### ISSUE TITLE
gorhill’s a real douche nozzle!

### ISSUE THREAD

**Issue by WHINERgorhill** [gorhill/uBlock#2571]
Left a rude comment, then closed the issue and blocked me so I couldn't retort and hurt his tender little feelings.

Should change his app’s name to uCock!

I don’t believe I opened an "invalid issue," it was a simple question about the app’s capabilities. I’ve already installed and tested several blockers, so I asked if this would do what the others failed to do, because someone had suggested I try this.

I debated using the term "waste time" because I didn’t want it to be taken the wrong way, but I left it because it’s accurate - if I install uBlock and test it for hours or days and discover it’s no better than the others, than I HAVE wasted time.
That’s why I asked **BEFORE** installing it if it could block JS or not. I think that was a prudent thing to do, but the hypersensitive developer was offended.

Besides, other people read these messages, so respectfully answering MY question likely would have helped others as well. Not just today, but in the months to come as people search for answers and end up here.

Instead, gorhill decided to be a prick which helped NO ONE.

**Comment by gorhill** [comment]
> it was a [simple question](https://github.com/gorhill/uBlock/issues/2567)

[Submitting issues](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> For **support/discussions**, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746). [...] gnorance of the above rules is no excuse: **Opening an issue for purpose of support or discussion, or opening a filter-related issue will result in the user being immediately blocked.** Given the [amount of invalid issues being opened](https://github.com/gorhill/uBlock/issues?q=is%3Aissue+label%3Ainvalid+is%3Aclosed), I have no choice but to resort to such a drastic measure. You will still be able to open filter list issues at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues). [...] **The issue tracker is for provable issues only:**.
