### ISSUE TITLE
Liste AR (العربية) filters list dependency are Liste FR + EasyList

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#2572]
Hi,

**Your settings** : 

- Localization of the Browser: Arabic / **عربي**

**Describe the issue** : 

**Liste AR** (القائمة **العربية** لمانع الشرائط الإعلانية آدبلوك بلس) is a supplement sub to for **Liste FR** this mean **Liste AR** required **Liste FR** not only **EasyList**. For **Arabic** users in **[Adblock Plus](https://adblockplus.org/)** the default installed lists are "**Liste_AR + Liste_FR + EasyList**" but it is not the case in **uBo**.

From the header of **Liste AR** https://easylist-downloads.adblockplus.org/Liste_AR.txt

`! Liste AR ~ Filtres arabes complémentaires à EasyList et à la Liste FR`

(2013-02-16) ==> https://hg.adblockplus.org/listear/rev/a5513050cd22

**Request** : 

Make **[Liste FR](https://easylist-downloads.adblockplus.org/liste_fr.txt)** selected at the same times whene **[Liste AR](https://easylist-downloads.adblockplus.org/Liste_AR.txt)** is selected.

**Screenshot** : 

![uBo - Liste AR](http://i.imgur.com/7EGa8Y1.png)

**Related** : 

* https://issues.adblockplus.org/ticket/4890
* https://help.getadblock.com/support/tickets/8778 (http://i.imgur.com/GrhOgr7.png)

**shortlog & forum** : 
* https://hg.adblockplus.org/listear/shortlog
* https://forums.lanik.us/viewforum.php?f=98

Thank you.

**Comment by gorhill** [comment]
Liste FR will be automatically selected at install time when the locale is `ar`, but it won't be automatically selected afterward if a user select Liste AR, by design.
