### ISSUE TITLE
Scripts from antiblock.org and F***AdBlock forces to disable uBlock

### ISSUE THREAD

**Issue by nhatlinh1704** [gorhill/uBlock#2574]
Recently I've found scripts from
[http://antiblock.org/](http://antiblock.org/)
[F***AdBlock](https://github.com/sitexw/FuckAdBlock) (test on https://fuckadblock.sitexw.fr, also beta version)
and uBlock is defeated.

**I. INFO**
_uBlock version:_ 1.12.1
_Tested browsers:_ 
Chrome 58.0.3029.81
Firefox 54.0b3

**II. THE ISSUE**
My current settings
![pic1](https://cloud.githubusercontent.com/assets/5692900/25564649/10ea217c-2de2-11e7-8da8-536b1ec6c23b.png)

This is the problem:
![pic1](https://cloud.githubusercontent.com/assets/5692900/25564702/2fbf6282-2de3-11e7-952a-4255c7704238.png) (AntiAdblock.org demo site)
![pic1](https://cloud.githubusercontent.com/assets/5692900/25564900/61f5ced6-2de7-11e7-8622-fa890bb6006c.png) (http://ally.sh)

I tried to turn off all Ads filter, it still doesn't work. The same message appears. Then I began to look into the source code.
Here is the script which prevents uBlock (taken from [http://antiblock.org/?p=v3&demo&force](http://antiblock.org/?p=v3&demo&force))
`<script>window.document.getElementById("cc8c").parentNode.removeChild(window.document.getElementById("cc8c"));(function(l,m){function n(a){a&&cc8c.nextFunction()}var h=l.document,p=["i","s","u"];n.prototype={rand:function(a){return Math.floor(Math.random()*a)},getElementBy:function(a,b){return a?h.getElementById(a):h.getElementsByTagName(b)},getStyle:function(a){var b=h.defaultView;return b&&b.getComputedStyle?b.getComputedStyle(a,null):a.currentStyle},deferExecution:function(a){setTimeout(a,2E3)},insert:function(a,b){var e=h.createElement("font"),d=h.body,c=d.childNodes.length,g=d.style,f=0,k=0;if("cc8c"==b){e.setAttribute("id",b);g.margin=g.padding=0;g.height="100%";for(c=this.rand(c);f<c;f++)1==d.childNodes[f].nodeType&&(k=Math.max(k,parseFloat(this.getStyle(d.childNodes[f]).zIndex)||0));k&&(e.style.zIndex=k+1);c++}e.innerHTML=a;d.insertBefore(e,d.childNodes[c-1])},displayMessage:function(a){var b=this;a="abisuq".charAt(b.rand(5));b.insert("<"+a+'><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAbAAAABFBAMAAADZSK4HAAAAG1BMVEX9/f3IyMgAAADIyMgAAADIyMgAAADIyMgAAAAZMgcYAAAJAElEQVRoge1Wy3LqSAxtSHgscb4A/AVUOR9AFf4Ab5w1G1izc5bs4s+ec/Toto0hyZ3cmTtTdBhfWdKRdFrq9oTwWI/1Z6w8z9dhmt/xmK75674Sth71HYePo/IRtx9ceZYhQ7667THd8Nd9jc+vrK5/D9XP+fWAX1wIr7+7lWXDCv5LxHJ0borHVIdzbQlzpORLTjtM0w3fWIf76KwSSSGPUI3jlHoomvKVBCQk/x3E8nwjxKabFyTLXtYynHlmRwDCRqcRJjxQ98TqcB+xEq5CUmscJdZDqells9KkfPw8sSzLtG8ZjvMEqSBPmHOt1a2mGz9mGf5yNYkm+rAhMBnD1USHzJw3Hieh4DxZ5YQwac64v2MU9YnWYTjQP47ilEIsWndapxS1urLnwwgvSswiJ+duHHdmQE+6Cr/njBkxtO4F87YJGEXMSpb1iU1sShOxns81seR8g5iMfpb9bmI8/7wnNnL75/5hwaRoNWspaJq/yOxID7s+U5ywlQiRGJxFI8Q6qDxjLk+SWwlZ+Nml26U3FSrLefohTHkCtCLR8NZDQfkaTZDbRq/Q5BP4Is5pFNfkFm/FiBIBuVZyl26sY+sfJqYHnTM1wWOSrXCS+YYRUQfXTKjJsskqm4jzKvpMAwdYNXT20HQWjbx0UJYLRhfCz3fsJ1burfu/rUls72M91mM91n99lWXJ5y3rmFiOWIcBuZ53I2YoO/p+qOey73ijkq+tsnhFhHKr0GEt1HfFsqfsWIcBpbT9iBnKjn4QqhtwgB7NdW8BgGqftgod1nJFjI8nVz6NEtvG3S1GzP8gsef9ljPAEXouyx0lt+1gVc0OjqWOmTjzJ5ND1K4sE4rEDMWps4AqRGKOKl8l4E4FHRzRwL7n1NKkwb5NrCwLgT2VxTa87gtEfPUaXsGmYI6CNey34qOl20+cSzwiSvRECYfyqRQfETRoiZIdVe4oMPrOToSaCgZEYZJdgn2fWDpjNoqMZyZhg40rWKttgKZHXuVGZzyKhNo6SpoDgSYRjNjrvoeKPsEDMnbxXO5lmJjpafurZ6xHDMsnHhNSlvtnakr30X0Vz6066wQNUTZ1YIL16kdLiUWUO3engM4cRzac2fcW9vvEtoOOFUUqcY83aFCHd9ZOQmEbDGdRXKESMbwkYkIjomKKa2J7OQNF8cvEbKjkduCJxcjYccDJ2Mop31LYlupjxLY2kxyqbQgRJQHL4KOol0D5nIgV5T6iyp05lz7bz65RnAjEjd7Ad4lx7+22Y2h522sUvRVLjPuOxOSWQlZxFl+5DPdb7aOhJKCiWK3egfvOKG5Vox17NWcTdjoLAt/LxVt6x77JKzxxguQRMD2Q5M1t2CeaCggUxcecE1R301Eei6hCIGIq/LMWNUQ9bc3ZBa1A4cGz/1LHHuuxHuuxHutvrPnh367gs+UVnuQXF+UTTPPTOORUjwUbcb67xH8sxXjS2/BoTW6sUFhU/CUM5PnRhGGOI35D9SmMO1/59BTVF1Ax6XW8CI9WCkJOKjxVV8Rm94mFq4aJ3+wTYle78VPEUj21u9Zmmh/AcY7pk5nU/jqxE3Un2+/5CfqoOQExhyAv81NwOOLwIYmjBj7zg6KssrdTJwUiH5IzBHXuJRXUnHEYKsEPQcoIWs7BUmgzCa1P1rruKM6Pb4cwq21j4XOkZn6s5QEEhNmpjm0/VYwz58N2VDXicxLom3E+UPAUjBydVYiOljSi5DhEuJTKMkR4O9YaMBJjzw7XxHAMT8GPFX2O1OhAQniDodaBYIksm3HgqJMZNbq3wGhAqVc6oyk0ciUBrQw695JGlBJzuB/7Ws/YsROZvavRRNuzPjGsyu9BjUiNTBYeb8c46bL3+GOcznmWaeBA+HmWgCF1OCifYMRiGX76UlJHRecqEfOjKMS0ZiWGXanreqxjdV35PWhbBc0MrYcwICYbxDjptIumR4zwO8RiGX1iXdSnxMRZ8KychxJ/wzPGoxw/XBCP1PD4IjSc5SjzHyNmcTrEKg1AH72ofKgOklUHuNLIFlCFapA0oaiJcOUiN4oQI5zOs8q5npj+oGNmN5XcMMdqeCuKBsN7IDeg5u7DXHNtUpzFSszqo9Oh/cfU1Z6itsgeUMpwYjFpB4VtdfjcLufab8RanbVktoT9m9UzjJkIFTUgjsfM5gCaqk6aGs6CCtHH46RPnWr0IZs4q9U4q1IKChiwmQeUMuIXzpPqKIpzVSd4rY9KhZnA60+/q//cGvsKX68vfdD/sDX6f6DD9cf04bEe67H+z6tt28tAtbzSDB1u2ttx7aVjXY773Ip8O9d40ujfNs0wU3ulGSb7uBW+Pd/zV+u4z63Io7kGmbsBoz+0w0zt+V7uW8kEs/g3iC1uE+PwtXEC2/MCmpY9aEPfJNAW4LaVKebjEsSZL0uBGMqcLx1i760RU+flJTlrHI0MfTvIpfj2AtNFUohgqBBSPYlY236cOXzLOIGSuXm/COe+ScxN+7H8eL8sPxp5tOK8aJuz919R7twhdnm/iA/hEiel0DgaObR8dHNZMxps8aKVFO8UBOUBpZ4OsaZplh/nJfRn7akQR88+qHvvmTQ8TG0TuJehwV8LH/5z1j2JKHdOyYhS8gJnnLPA4aNxNDLtTS+X4s3nElEwLc4pID26o8gX0HCN7D0buZS/rsmGGMmwztwBTCFyeCDdPPwRrqNEoXPG0u9d4sjeM5fGWVoPz8NcHiyhTOiEHYziFTGtrnnncDe3iKHP5wXHFZdqn5iiYLfpaZrPiNHH4owSYy4brrvEFv1RlHqCUOgSw5wH7lQ0pbsFpiVvlIuEXqIOfj34jxEjyr4nIqQzhtnycT1rHINbHNF8pFvZc1ldS+VDlAk22zL/mqjpElu2HOYOMVQnu3VOJtwgto16U32w9Q3oMh9sS9UEQ5m3CH6tYeoavwMbi2NwiyORm/RFiLn05aJ8QhI8qaZhVNt++whwcJyqqBbN2VRuahvPRtOikf9wazQLPs7iuFBBUOZNYWEvi7P5qYbTvnC4xpHI586XyXNZrIVWtUiCJRVUzP6tNf7t/VvrCx/fX15/ASDVUv9tuOFWAAAAAElFTkSuQmCC" height="69" width="432" alt="" /> <a href="http://ow.ly/lZZBl">[ ? ]</a>'+("</"+a+">"),"cc8c");h.addEventListener&&b.deferExecution(function(){b.getElementBy("cc8c").addEventListener("DOMNodeRemoved",function(){b.displayMessage()},!1)})},i:function(){for(var a="AD300_VAN,ad2Sp,adSpace0,adrow,ads-A,adtab,db_ad,ad,ads,adsense".split(","),b=a.length,e="",d=this,c=0,g="abisuq".charAt(d.rand(5));c<b;c++)d.getElementBy(a[c])||(e+="<"+g+' id="'+a[c]+'"></'+g+">");d.insert(e);d.deferExecution(function(){for(c=0;c<b;c++)if(null==d.getElementBy(a[c]).offsetParent||"none"==d.getStyle(d.getElementBy(a[c])).display)return d.displayMessage("#"+a[c]+"("+c+")");d.nextFunction()})},s:function(){var a={'pagead2.googlesyndic':'google_ad_client','js.adscale.de/getads':'adscale_slot_id','get.mirando.de/miran':'adPlaceId'},b=this,e=b.getElementBy(0,"script"),d=e.length-1,c,g,f,k;h.write=null;for(h.writeln=null;0<=d;--d)if(c=e[d].src.substr(7,20),a[c]!==m){f=h.createElement("script");f.type="text/javascript";f.src=e[d].src;g=a[c];l[g]=m;f.onload=f.onreadystatechange=function(){k=this;l[g]!==m||k.readyState&&"loaded"!==k.readyState&&"complete"!==k.readyState||(l[g]=f.onload=f.onreadystatechange=null,e[0].parentNode.removeChild(f))};e[0].parentNode.insertBefore(f,e[0]);b.deferExecution(function(){if(l[g]===m)return b.displayMessage(f.src);b.nextFunction()});return}b.nextFunction()},u:function(){var a="-adv.jpg,-main/ad.,-popup-ad.,.org/ad.,/adfile/ad,/adsbygoogle.,/advertright.,/display/ads/ad,/main/ad/ad,/promoAd.".split(","),b=this,e=b.getElementBy(0,"img"),d,c;e[0]!==m&&e[0].src!==m&&(d=new Image,d.onload=function(){c=this;c.onload=null;c.onerror=function(){p=null;b.displayMessage(c.src)};c.src=e[0].src+"#"+a.join("")},d.src=e[0].src);b.deferExecution(function(){b.nextFunction()})},nextFunction:function(){var a=p[0];a===m&&this.displayMessage("forced");a!==m&&(p.shift(),this[a]())}};l.cc8c=cc8c=new n;h.addEventListener?l.addEventListener("load",n,!1):l.attachEvent("onload",n)})(window);</script>`

BUT this line got me:
`return b.displayMessage(f.src);b.nextFunction()});return}b.nextFunction()},u:function(){var a="-adv.jpg,-main/ad.,-popup-ad.,.org/ad.,/adfile/ad,/adsbygoogle.,/advertright.,/display/ads/ad,/main/ad/ad,/promoAd.".split(","),b=t`
I think the script checks ad servers to see if they can be reachable. If they can, that darn message won't appear; otherwise, I have to disable uBlock, which is really annoying.
I hope there is a way to stop that darn script from loading forever, otherwise uBlock will become useless if many websites use that script in the future. Using F12 is OK, but it's not a permanent solution.

That was for antiblock.org, but with F***AdBlock, things much more different and more complex. If uBlock can stop F***AdBlock's script from loading, it should work. Since F***AdBlock has various methods to stop uBlock, I think uBlock should prepare that too. The filters won't work at all!

**Comment by mapx-** [comment]
`sitexw.fr##script:inject(fuckadblock.js-3.2.0)`

**Comment by gorhill** [comment]
This can be foiled by uBO. But I will add appropriate anti-blocker-foiling filters **only** for sites which make use of the anti-blocker, not the site which demonstrates/publishes the anti-blocker code.

There is no value in foiling the anti-blocker on this site, other than for silly bragging value, which will more than likely attract the attention of the author of the anti-blocker code, possibly encouraging the code to be revised, which would then force me to revise the anti-blocker foiling code.
