### ISSUE TITLE
Block remote 3:ed party fonts

### ISSUE THREAD

**Issue by Bartolomeus-649** [gorhill/uBlock#2575]
There is a feature called "Block remote fonts". I assumed "remote" meant fonts from other sites than the one I'm visiting.
Downloading a font from the host of the current page is no different than downloading a style sheet or a picture from that site/host.

So to have a feature to block fonts from the same base domain, is kind of strange when there are no checkboxes for either images, style sheets or scripts, which there are quite a few of compared to fonts.

I suggest that the feature "Block remote fonts" is changes in two ways
1. Change the label for the CheckBox to: "Block remote 3:ed party fonts".
2. Change the rule created by enabling this feature to only block fonts from different base domains than the base domain of the current page.

At the very least, the current label should be changed to something like "Block downloading of all custom fonts", to better reflect what the feature actually does.

**Comment by Atavic** [comment]
https://github.com/gorhill/uBlock/issues/1676
