### ISSUE TITLE
[webext] Both webext addons have a yellow "LEGACY" badge 

### ISSUE THREAD

**Issue by TerraX-net** [gorhill/uBlock#2576]
https://dxr.mozilla.org/mozilla-central/search?q=addon.legacy.label&redirect=false
![screenshot_20170501_124438](https://cloud.githubusercontent.com/assets/17962859/25578131/0966a09e-2e6c-11e7-8ed8-0d508a713cc7.png)

As those addons are webext-only and not webext-hybrid as you are planning it for the future, I am confused.
https://github.com/gorhill/uBlock/issues/622#issuecomment-279403362
If those webext addons are already the hybrids, I do not understand why there are legacy and hybrid-legacy addons, but not webextension-only addons. (Importing the webext-only chromium addons into Nightly does not work which I neither would expect).

**Comment by azes** [comment]
> As those addons are webext-only and not webext-hybrid as you are planning it for the future
It's vice versa, webext-hybrid for now, webext-only planned for the future.
> I do not understand why there are legacy and hybrid-legacy addons, but not webextension-only addons.
This is necessary to transition legacy users to webextensions because webextensions may not have access to the legacy addon's settings & data.

**Comment by gorhill** [comment]
The webext version of uBO is a hybrid, a webext wrapped into a thin layer legacy one, necessary for a seamless transition. If you want the label to be different for this case, this is a Firefox issue.

**Comment by TerraX-net** [comment]
Okay, Thank you! The thin legacy layer must be removed until August (Nightly 57) anyway, so I think this label is technically correct and okay for this time. Then I will now try to remove that legacy layer for myself to feel better :D

**Comment by gorhill** [comment]
If I find the free time, I will bring back the pure webext version like it used to be before I converted to hybrid.

**Comment by RalfJung** [comment]
> If I find the free time, I will bring back the pure webext version like it used to be before I converted to hybrid.

Will using the old `make-webext` still "just work" or is it necessary to update that file?

Also, any reason that current releases don't include the webext.xpi any more?
