### ISSUE TITLE
Automatic Local Noop?

### ISSUE THREAD

**Issue by PsyintZ** [gorhill/uBlock#2577]
Hello fellow uBrethren (specifically @Gorhill)!

First off, I would just like to thank you for creating such an amazing extension. Both uBlock and uMatrix are leagues above the competition, and you are nothing short of a hero for sharing this software with us, Gorhill. Thank you.

With that being said, I had a quick question I'd like to ask that shouldn't take up more than a couple of seconds to conclude. After spending hours reading through guides and customizing both uBlock and uMatrix to my liking, I have finally gotten them to operate (very close to) how I want them. There is only one thing that is slowing me down, and I'm not even sure if it's possible to alleviate. 

Is there any way to have a local noop automatically placed on the website I am currently visiting? For example: I visit www.disney.com (with my settings set similar to hard mode) and the broken website displays. Now of course, for me to get anything that resembles a web page, I must locally noop www.disney.com. I was just curious as to whether or not there is a way to have uBlock automatically noop (only) the domain that is currently being visited? Or must I noop these domains one by one, as I visit them - which, in time, will build up my list until eventually I no longer have to noop anything except for sites I have never visited before? 

Thanks in advance for any help you may be able to provide. And thanks again for such a top quality product, Gorhill!

Much appreciative,
Psy

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by PsyintZ** [comment]
@Gorhill, 

My sincere apologies guys. Won't happen again. I just wasn't sure where to ask my question, since there is nothing that points me toward Mozilla Discourse suggesting that all "support/discussion" takes place over there. Now that I know, I will use that from now on. Again, I apologize.
