### ISSUE TITLE
Filterlists' pages don't display correctly with uBO 1.12.3b1

### ISSUE THREAD

**Issue by TheFinalCut83** [gorhill/uBlock#2578]
### Describe the issue
Blank page instead of filter list pages with list of filters and attendant information (filter list version and so on). Home buttons at the right of each filter list also open blank pages. With stable uBO 1.12.1 all is fine.

### One or more specific URLs where the issue occurs

uBO's dashboard, 3rd party filters pane.

### Screenshot in which the issue can be seen

![1](https://cloud.githubusercontent.com/assets/16985985/25608997/dea89da2-2f25-11e7-9f3d-a7c10b16c918.jpg)

### Steps for anyone to reproduce the issue

1. Open the dashboard and go to 3rd party filters pane
2. Click on any filter list
3. Blank new tab will open instead an filter list page with filters and info.

### Your settings

- OS/version: Win 7 x64
- Browser/version: Firefox portable 53, Firefox 54.0b3
- uBlock Origin version: 1.12.3b1

##### Your filter lists

All default (FF53) / http://pastebin.com/yUZxWZCc (FF54.0b3)

**Comment by gorhill** [comment]
This was fixed in fb37378e7cc7caba4cfea8fe60f9ddd58f1a114b and 9a3288a1666516e2fa6ff8c2e1a07f6cc0b2febf.
