### ISSUE TITLE
"My Filters" not saving

### ISSUE THREAD

**Issue by mattncsu** [gorhill/uBlock#2579]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Filters added to the My Filters (chrome://ublock0/content/dashboard.html#1p-filters.html) tab disappear after applying and then changing pages.  Dynamic filters added to My Rules tab save fine.  This is probably related to me using uBlock on a locked-down, non-persistent linux system running a semi-locked down Firefox but reporting here just in case because everything worked as expected on this system until a few days ago.  Every morning, I download uBlock, add to Firefox, configure to advanced user, add the filter lists below, and a custom filter to My Filters. Where does uBlock store the filters? I can check to see if I have write access there.

### One or more specific URLs where the issue occurs
chrome://ublock0/content/dashboard.html#1p-filters.html

### Screenshot in which the issue can be seen

![output_enzo5k](https://cloud.githubusercontent.com/assets/24309552/25619878/756107ae-2f1a-11e7-81ec-a48ab9096e48.gif)

### Steps for anyone to reproduce the issue

1. Type something in My Filters
2. Click Apply
3. Refresh or change tabs and come back to My Filters
4. Observe that My Filters is blank again.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: linux 4/1/36TS_SMP
- Browser/version:  45.8.0 ESR
- uBlock Origin version: 1.12.1

##### Your filter lists
Default filters+
Adblock Warning Removal List
Anti-Adblock Killer | Reek
Fanboy’s Annoyance List
Fanboy’s Social Blocking List

##### Your custom filters (if any)
Attempting to add "AOL_V1/GetOffers"  (blocks modal popup when signing in to AOL webmail)

##(updated to fix gif)

**Comment by gorhill** [comment]
In your gif, I see:

    !example
    AOL_V1/GetOffers

Can you try with a blank line separating the comment line and the filter immediately under?

**Comment by mattncsu** [comment]
Same effect. I've also noticed that there is always a blank line in the box but it doesn't matter if I leave it there (entering my filter on line 2) or deleting it and entering the filter on line 1.  Also tried just saving a comment and just saving the filter with no difference.  When it worked, I'd only enter the filter and it saved fine.

**Comment by gorhill** [comment]
Any relevant errors reported at the browser console?

**Comment by mattncsu** [comment]
Nothing in browser or web console.

**Comment by gorhill** [comment]
Not much I can do, I can't reproduce, you are best placed to investigate why it's not working. uBO saves all its settings in the same place, a sqlite file, which location is [documented here](https://github.com/gorhill/uBlock/blob/master/dist/README.md).

**Comment by mattncsu** [comment]
I can write to the ~/.mozilla/firefox/[profile name]/extension-data folder but there is no ublock0.sqlite file in there.  I am sure it something to do with the way the system is locked down.  Can you think of any options in about:config that might prevent the browser from writing to storage?  It is odd that it remembers the rules but not filters.

**Comment by gorhill** [comment]
> It is odd that it remembers the rules but not filters.

Not odd, just the way it works internally. When you save your filters, uBO saves, them, then compiles them and saves the result of the compile operation. When compilation is complete, the dashboard page send the order to reload all the filters from storage -- but this fails on your side because the filters where not saved.

The rules are always kept in memory, not saved then reloaded.

**Comment by mattncsu** [comment]
Did a little more homework:

- Rebooted which wipes everything (the local storage is on a ram disk).
- Started watching the /home/guest/.mozilla/firefox/[profile]/extension-data/ folder.
- Downloaded and installed uBlock - no sqlite file was created in the extension-data folder.  Filter changes were per the above GIF. 
- Quit Firefox and started it back up
- sqlite file is created ~6.3 MB
- Observe that all my settings I changed initially are reset to default.
- Changed settings and now they are saved in the sqlite file.

So it seems, a FF restart is required (at least on my machine) before the sqlite file is created and I can save options.

**Comment by gorhill** [comment]
Not much I can do here, I can't reproduce such issue. It could be that you switched too early to the _"3rd-party filters"_ pane, before uBO could complete the loading/parsing, which would take longer if uBO can't persist the compiled filter lists. But even if that is not the issue, I can't investigate your specific setup -- so this issue will never go anywhere, except if you or whoever is using your setup investigate the root cause.

**Comment by mattncsu** [comment]
When you add uBO to a clean installation of Firefox, is the sqlite file created right away?  What I noticed on my setup was that uBO would start immediately after adding it to FF, but it doesn't create the sqlite file (and thus not be able to save any settings) until after I closed and reopened FF.  After restarting FF, everything works perfectly.  Maybe on certain systems a FF restart is required to complete installation.

**Comment by gorhill** [comment]
> is the sqlite file created right away?

Yes. Just tested again to be sure, with 1.13.8.

**Comment by gorhill** [comment]
I edited my answer above.

**Comment by mattncsu** [comment]
Interesting...maybe in a few months we'll be upgraded to the next ESR FF version and it'll go away. Thanks for looking in to it.

**Comment by hiragashi** [comment]
every retard on firefox 58 I also completely lose my filters. really annoying problem

**Comment by gorhill** [comment]
You filters/settings are saved at the location described here:
<https://github.com/gorhill/uBlock/tree/master/dist#firefox-webext>.

So if you lose your fitlers/settings every time, it's because that file is being removed (or prevented from being created) by something else on your side, you will have to investigate what is causing this.

**Comment by hiragashi** [comment]
yeah no issues with saving files in the mozilla folder at all - infact, it was working completely fine on 57. 58 however just wipes all filters on reboot.

folder contains: storage.js  storage.js-1.corrupt  storage.js.corrupt
the *.corrupt files are completely empty. storage.js is what I have set after reboot and finding I've lost filters. Rebooting creates another .corrupt file that's completely empty and then subsequently another storage.js file

**Comment by gorhill** [comment]
How are you quitting Firefox? The cause is likely Firefox crashing or otherwise not quitting properly.
