### ISSUE TITLE
Banner on the site www.globes.co.il

### ISSUE THREAD

**Issue by larytet** [gorhill/uBlock#2580]
I am trying to get rid of the large banner at the top of the page 
Screenshot https://drive.google.com/file/d/0B0u8VwdyTwpwNzREMVdTWWpSWHM/view 

When picking the frame (iframe) I am getting something like `###KbwlAk > iframe` - every time a different string. Is there a workaround for the problem?

AdBlockPlus shows correct image link `globes.co.il##img[src="blob:http://www.globes.co.il/6589ccb3-7db5-4652-b44d-2e30a50cc43d"]`, but unfortunately fails as well.

Below is the relevant HTML

`<div id="jumbo_container" class="topBanner nocontent">
`

I tried to add a filter `###jumbo_container` - no result
 
Thanks

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
