### ISSUE TITLE
About donations

### ISSUE THREAD

**Issue by orschiro** [gorhill/uBlock#2581]
From the README:

> Free. Open source. For users by users. No donations sought.

>Without the preset lists of filters, this extension is nothing. So if ever you really do want to contribute something, think about the people working hard to maintain the filter lists you are using, which were made available to use by all for free.

Could you list a few I can support?

Thanks!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by seanrand** [comment]
@orschiro most of the filter lists are volunteer-driven and don't provide a way to donate. The most important and most comprehensive filter list, EasyList, at least doesn't take donations last I checked.

https://www.fanboy.co.nz/ has a paypal link, he's one of the main contributors to EasyList.

Apart from that, try clicking through the home buttons on the 3rd-party filters pane and look for a way to donate. Some of the hosts-file authors accept donations.

**Comment by orschiro** [comment]
@seanrand thank you for your starting help!

I guess I will send fanboy.co.nz a direct donation.
