### ISSUE TITLE
Will HTTP2 multiplexing and server-push features circumvent uBO?

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2582]
Over at the [`ghacks-user.js` project](https://github.com/ghacksuserjs/ghacks-user.js/issues/107#issuecomment-298846713), we've been discussing the benefits of allowing/disabling `HTTP/2` and it turns out that uBO's ability to do its work could play a big role in users' decision on the matter. I'd appreciate any thought you have.

### The Issue
HTTP/2 is [a new spec](https://http2.github.io/http2-spec/) meant to significantly reduce header and connection overhead. Here is [a very simple intro](https://www.sitepoint.com/http2-the-pros-the-cons-and-what-you-need-to-know/) as well as [a basic FAQ](https://http2.github.io/faq/). The protocol has at least two features with important privacy implications and I wondered whether uBO would protect its users from them:

* Multiplexing: whereas in HTTP/1, the browser establishes one connection for each asset it wants to download, in HTTP/2 multiple assets, possibly from multiple hosts, can be transmitted over a single connection

* Server-Push: whereas in HTTP/1, the browser first fetches the HTML, then discovers what else it needs and *then* fetches additional assets (CSS, JS, Fonts...), in HTTP/2 the server can "push" all assets it believes the browser will need as soon as the browser makes the first request

### Let's test
I ran a quick test [on this site](http://www.http2demo.io/) using Firefox 53 and results don't look promising. To replicate:

1. Make sure HTTP/2 is enabled. In FF 53, it's ON by default.  The following prefs should all be set `true`
```
network.http.spdy.enabled
network.http.spdy.enabled.deps
network.http.spdy.enabled.http2
```

2. Add the following rules to uBO. Note that I block certain image URLs to test uBO's effectiveness under HTTP/2.
```
www.http2demo.io * 1p-script noop
www.http2demo.io * 3p-frame noop
www.http2demo.io * inline-script noop
www.http2demo.io http://1153288396.rsc.cdn77.org/http2/tiles_final/tile_1 image block
```
3. Clear the browser cache. Then load this page: http://www.http2demo.io/ . It will open many connections to `cdn77.org` to download image sections that are then stitched together to make the big image on the left of the page. The logger shows that all images with names starting with `tile_1` are blocked. Notice also that the big image is missing some blocks:
![6](https://cloud.githubusercontent.com/assets/12346501/25671446/12eb662a-2ffe-11e7-9443-419d5ffbc0e5.png)
![7](https://cloud.githubusercontent.com/assets/12346501/25671454/1d80e1c8-2ffe-11e7-8edd-d28c773dbb3f.png)

**step 4 is flawed: ignore this result**

4. Clear the browser cache. Then press the `Run HTTP/2 Test` button. This time, uBO is unable to block the same content.
![8](https://cloud.githubusercontent.com/assets/12346501/25671509/4fdd2c26-2ffe-11e7-9337-dc66db716fe9.png)
![9](https://cloud.githubusercontent.com/assets/12346501/25671630/b010fea6-2ffe-11e7-86a5-5e9cbe65a63e.png)

### My question 
```
Can uBO filter HTTP/2 network requests? Would connections be effectively prevented?
```

### Edit
My test was flawed because I didn't realize that HTTP/2 files were being loaded from a different server. In fact uBO succeeded. See my next post below

**Comment by seanrand** [comment]
Uhm. You do realize that the second set of images is loaded from a different server? 😅 
http://1153288396.rsc.cdn77.org/ vs https://1906714720.rsc.cdn77.org/

**Comment by RoxKilly** [comment]
No I didn't notice!  let me rerun the test

**Comment by anewuser** [comment]
@RoxKilly Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by RoxKilly** [comment]
Hi @anewuser Help me out: wouldn't this qualify as an issue with the filtering engine itself? If you guys feel it does not qualify, I would be happy to repost at `discourse.mozilla-community.org`

**Comment by gorhill** [comment]
> wouldn't this qualify as an issue with the filtering engine itself?

What issue? You corrected your first comment that uBO does indeed block properly whatever you wanted it to block.

**Comment by RoxKilly** [comment]
@gorhill  wrote:

> What issue? You corrected your first comment that uBO does indeed block properly whatever you wanted it to block.

yeah uBO seems to block over HTTP/2 so that's resolved. 

I'm getting at something slightly different. If I believed there was a protocol that uBO fails to block and I have test results to share, is the right place to post that stuff here or on Mozilla Discourse? That's what I mean by "issue": as in, would you consider it be an issue legitimate to be posted here or a mere discussion topic that should be on Mozilla Discourse.

**Comment by gorhill** [comment]
The webRequest API normalizes all requests so that uBO does not have to concern itself with whatever underlying revision of the HTTP protocol is in use -- that's way below uBO's scope. If ever there was a case of network requests not relayed to uBO through the webRequest API, then this a browser issue.

**Comment by uBlock-user** [comment]
It's always been working ever since HTTP/2 was implemented in Chromium that was way before Firefox implemented support for that itself.
