### ISSUE TITLE
Advanced settings don't get applied to incognito instance in Chrome/ium

### ISSUE THREAD

**Issue by seanrand** [gorhill/uBlock#2583]
#### Description

This issue applies to Chromium-based browsers. When launched in an incognito window, the incognito instance of uBlock does not reflect user-defined changes to [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) and instead uses the default values.

#### Steps to reproduce

1. Modify a value in the advanced settings pane and apply changes
2. (optionally) reload uBlock from chrome://extensions/
3. Open an incognito window, open the advanced settings pane
4. Observe the settings being reset to default values in the incognito instance of uBlock

#### Environment

Chromium 58.0.3029.81 (64-bit), uBlock Origin 1.12.3.2.

Issue opened because of https://github.com/gorhill/uBlock/issues/2267#issuecomment-298961978

**Comment by gorhill** [comment]
This was fixed when I fixed #3387.
