### ISSUE TITLE
.

### ISSUE THREAD

**Issue by PekaFat** [gorhill/uBlock#2586]

**Comment by PekaFat** [comment]
Other sites if fine.

**Comment by gorhill** [comment]
It's because of uBO-Extra -- same issue seen with Tampermonkey as explanied here: <https://github.com/gorhill/uBlock/issues/2199#issuecomment-263948829>.

Workaround: just use Firefox.

**Comment by PekaFat** [comment]
But why not all blocked ads is unblocked? Only this:
![image](https://cloud.githubusercontent.com/assets/13280748/25774057/de9eef56-3299-11e7-95b6-4066d859e22e.png)

**Comment by PekaFat** [comment]
This happens even without 'Reek's' filters list.

**Comment by gorhill** [comment]
I didn't say it was because of Reek's, I am saying it's because of the same cause as to the other case.

**Comment by PekaFat** [comment]
Ok, I now will use firefox, f0k this buggy chrome.

**Comment by gorhill** [comment]
I did not meant for you to close this, I was just explaining the problem, and a current workaround.

Being able to block specific inline script tags, or more generally HTML filtering would be the solution.

**Comment by PekaFat** [comment]
But i still don't understand this https://github.com/gorhill/uBlock/issues/2586#issuecomment-299650510

**Comment by PekaFat** [comment]
And also, if chrome 58 already support WS block so maybe you can move ubo-extra functionality to ubo?
