### ISSUE TITLE
Some thai fugu

### ISSUE THREAD

**Issue by billyjoebdb** [gorhill/uBlock#2588]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

This is something to get worried about, some sunnafabeach from bangkok...
https blockadblock com

### One or more specific URLs where the issue occurs

https blockadblock com
![imagen 6](https://cloud.githubusercontent.com/assets/28496390/25777670/8441d890-32ba-11e7-81f7-bbe1fb4e6510.jpg)

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
-Check his site. The javascript running there can overrun any setup and is a simple script added to the header of any site that choose to use it. I even turn off µblock and its still showing up. I think it can detect the addon itself.
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Im using µblock, plus greasemonkey adsbypasser, and the anti-adblockkiller/reek, including Cleanlinks 2.7.1 and JavaScript Deobfuscator 2.0.4

- OS/version: MacOS
- Browser/version: TTF (tenfourfox)
- uBlock Origin version: 1.12.1

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

Take a look of the standar example of his

**Comment by RoxKilly** [comment]
This site was addressed on #2441 . Take a look

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
