### ISSUE TITLE
Dead link in wiki

### ISSUE THREAD

**Issue by jmranger** [gorhill/uBlock#259]
Hello,

https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do refers to issue 405, which doesn't exist. I guess it should refer to:
https://github.com/chrisaljoudi/uBlock/issues/405

Apologies for creating an issue for this, but I couldn't think of another way to report it.

Thanks

**Comment by EchoDev** [comment]
It might be better to open up a new ticket here (if it is going to be implemented/fixed), the "normal" uBlock might implement it (earlier?) and sending users to a ticket to the other uBlock that might get marked as fixed will probably confuse users when it is not implemented in uBlock Origins.

**Comment by gorhill** [comment]
Fixed.

You can edit the wiki if you want, there is no restriction.
