### ISSUE TITLE
uBO allowing scripts when denied in uMatrix

### ISSUE THREAD

**Issue by jaywk** [gorhill/uBlock#2590]
I wasn't exactly sure whether to post this issue here or over at the uMatix issue tracker since I use both uM and uBO together but it seems that this may be a uBO issue.  uBO is allowing scripts although they've been blocked in uM. Unless I'm mistaken on how uM works, which is possible, it is my understanding that if uM is set to block scripts (or any other network type) for a specific domain by turning those cells red for that domain then they should be blocked even before they become available for filtering in uBO. How can these scripts be available for filtering in uBO if they've been denied/blocked in uM?

Example website is [here](https://blog.mozilla.org/internetcitizen/2017/04/21/https-protect/). Block scripts from netdna-ssl.com in uM, noop (or allow) the netdna-ssl.com domain in uBO and see that scripts are being allowed.

If I view the uM logger, sure enough all the scripts from that domain are blocked as indicated by red text. Now, if I view the uBO logger it has those same scripts that were blocked in uM showing as being allowed and run on that page as indicated by green rows. They only become blocked in uBO if I set the local filtering for that domain to deny.

If my understanding of how uM works is correct then shouldn't denying (or allowing) network types per domain before filtering takes place with uBO, how are they allowed to be run in uBO? Is my understanding of how these two addons work together wrong or is this a legitimate bug?

I saw this behavior in my default Firefox profile and also tested it in a blank profile with only uBO and uM (with default settings) installed to rule out potential interference from any other addon.

Firefox 53.0.2 (64-bit)
uBO 1.12.1
uM 1.0.0

**Comment by benoit-pierre** [comment]
FWIU: uBlock and uMatrix don't know about each others. The order in which they process requests is also not deterministic (it depends on the installation order I believe). So if uBlock is first, it may well show a script as allowed in its logger, but that does not mean that the script cannot be blocked further down the line by uMatrix itself, and vice versa.

**Comment by gorhill** [comment]
uBO and uMatrix are two different extensions, what one is doing is not known by the other. The logger for each extension reports what it's doing, not what other extensions are doing.
