### ISSUE TITLE
How/can i use wildcard in some filtering rule?

### ISSUE THREAD

**Issue by slrslr** [gorhill/uBlock#2595]
Hello,

i am using uBlock Origin on the Firefox and when logged-in at https://twitter.com/ i mouse right click an "Promoted Tweet" and click to "Block element"

and i end up with something like this after i pick whole promoted tweet:
###stream-item-tweet-832332731627343872

But these promoted tweet numbers are changing, so i assume that i need to use wildcard like:
###stream-item-tweet-*

except * i tried also [*], tilde
but no luck

How can i use wildcard or if it can be implemented to allow wildcard. Thank You

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment]
read https://adblockplus.org/en/filters

try this filter
`twitter.com##[id^=stream-item-tweet-]`
