### ISSUE TITLE
Translating Wiki to Russian

### ISSUE THREAD

**Issue by bershan2** [gorhill/uBlock#2596]
I decided to translate uBO Wiki to Russian, and have a few technical questions/comments. I do realize that it is not an issue -- rather a discussion -- but did not find a more relevant place. (Since [uBO Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746) is primarily concerned with filter rules.) If this is a wrong place please redirect me elsewhere. Thank you.

# My questions/comments:
### (Minor note) Windows does not like special characters in file and folder names.
I could not properly clone Wiki on Windows, since filenames include special characters.
On Windows, special characters like `\`, `/`, `:`, `*`, `?`, `"`, `<`, `>`, and `|` are not allowed in the file and folder names. I worked around the issue by using "Bash on Ubuntu on Windows" -- effectively escaping Windows. Thus it is no longer issue for me, but felt I should point it out.

### How should I name the translated files?
@fang5566 [translated](https://github.com/fang5566/uBlock/wiki) even the file names in to Chinese, but I'm not sure about this because:
 - comparing the Chinese translation and English original is cumbersome, e.g. matching which file is translation of which and whether translation is up-to-date;
 - Chinese characters might puzzle some OS's (not really a problem for browser)

Instead, I think some Latin from original file name and a language code (from [_locales](https://github.com/gorhill/uBlock/tree/master/src/_locales)) are better. For example [Tools](https://github.com/gorhill/uBlock/wiki/Tools) would become "RU-Tools" or "ZH_CN-Tools-".
 - File correspondence is much clearer
 - On pages themselves, files can be linked to and referred to in the local language, e.g. `[工具](Tools ZH_CN)`

For the record: I do not propose renaming the files in Chinese translation -- only using the standardized naming convention in Russian translation.

### Should I include the date of translation?
I feel like the translations should have a message stating the date of translation, so when the original is modified changes that occurred after the translation date can be easily brought into all translations. Yet, I haven't seen these notes anywhere. Do you have a combined file for each language translation? Or do you not need these records since the translation commit date is presumed to be up-to-date at time of commit?

### Is there any particular reason for using absolute paths?

**Comment by gorhill** [comment]
The file names are controlled by GitHub, they are actually the wiki page title, it's not something I can control.

Probably something worth to explore would be GitHub pages, i.e. `gorhill.github.io/uBlock`, but I just haven't had the time to look into this (I did it for one other _very simple_ side project: `https://gorhill.github.io/obj-vs-set-vs-map/`). If I understand correctly, the documentation would be just a GitHub project, meaning control over the site structure and naming of files, something you can't get with GitHub wiki.

**Comment by bershan2** [comment]
Ok, then I will keep the original names for now (to preserve URLs) and just will add a titles translations into individual files. That will avoid confusion for now and does not really matter since the [Home](https://github.com/bershan2/uBlock/wiki/Home---Оглавление) will have the translated names.

I will keep translated files in the https://github.com/bershan2/uBlock/wiki until I'm done translating everything (a while in the future), then I'll probably play with GitHub pages for a short while and once I like the result we could move the new Wiki to GitHub pages at `gorhill.github.io/uBlock`.

I'd appreciate if you could notify me here when you edit main Wiki pages, because Wiki git repository is a bit funny. I could not fork it, so I had to make an empty one under my account and push files to that. If you forget to, that's not a big deal: I'll check the time stamps anyway before making the final commit.

**Comment by Snapy** [comment]
@bershan2 To keep track of wiki changes monitor [this page](https://github.com/gorhill/uBlock/wiki/_pages).

**Comment by bershan2** [comment]
@snapy Thank you!

**Comment by gorhill** [comment]
Closing -- as I don't see anything actionable on my side.
