### ISSUE TITLE
How to install (build from source) on a locked environment?

### ISSUE THREAD

**Issue by stefek99** [gorhill/uBlock#2597]
- Chrome web store: **blocked**
- unzipping files from the internet: **blocked**

> To help protect your computer. Windows has blocked access to this file.

https://github.com/gorhill/uBlock/blob/1.12.2/tools/make-chromium.sh

> This script assumes a linux environment

I could follow the build script manually, it's uncomplicated enough:
```
cp -R src/css               $DES/
cp -R src/img               $DES/
cp -R src/js                $DES/
cp -R src/lib               $DES/
cp -R src/_locales          $DES/
cp -R $DES/_locales/nb      $DES/_locales/no
cp src/*.html               $DES/
cp platform/chromium/*.js   $DES/js/
cp -R platform/chromium/img $DES/
cp platform/chromium/*.html $DES/
cp platform/chromium/*.json $DES/
cp LICENSE.txt              $DES/
```

Another alternative - because `Extract All...` does not work I'll try writing simple `node.js` utility that will unzip the thing...

Any other suggestions?

**Comment by gorhill** [comment]
What do you mean by "**blocked**"?

Why is this opened as a uBO issue? It sounds to me like you are saying your environment is preventing you from doing stuff you want to do, surely that is not a uBO issue?

**Comment by stefek99** [comment]
*blocked* as in not accessible, without being ability to access.

![image](https://cloud.githubusercontent.com/assets/249703/25851955/a89b4346-34bf-11e7-920a-c84180e9688a.png)

I'm on Windows _(Windows has blocked access to this file)_, running the build script does not work, I could however manually execute all the commands - mostly copying files to a new location and then loading unpacked extension

![image](https://cloud.githubusercontent.com/assets/249703/25851989/c308717c-34bf-11e7-9881-e76f679007da.png)

**Comment by gorhill** [comment]
Should be `./tools/make-chromium.sh`.

**Comment by stefek99** [comment]
Correct syntax on Windows (without `./`):
`c:\code\uBlock>bash tools/make-chromium.sh`

That script invokes `make-assets.sh`

![image](https://cloud.githubusercontent.com/assets/249703/25852493/74215efa-34c1-11e7-8ce1-8b1bd5000eef.png)

Question - where do these come from?
```
cp -R ../uAssets/thirdparties/easylist-downloads.adblockplus.org $DES/thirdparties/
cp -R ../uAssets/thirdparties/mirror1.malwaredomains.com         $DES/thirdparties/
cp -R ../uAssets/thirdparties/pgl.yoyo.org                       $DES/thirdparties/
cp -R ../uAssets/thirdparties/publicsuffix.org                   $DES/thirdparties/
cp -R ../uAssets/thirdparties/www.malwaredomainlist.com          $DES/thirdparties/
```

**Comment by gorhill** [comment]
Right, you also need to clone uAssets (at same level as uBlock, i.e. `c:\code\uAssets`), resources from it are added to the final uBO package.

**Comment by stefek99** [comment]
Thanks!

uAssets live here: https://github.com/uBlockOrigin/uAssets

Actually, I've accomplished my goal already - to hide pesky `#hot-network-questions` on StackOverflow!

https://meta.stackexchange.com/questions/222721/how-to-avoid-hot-network-questions-on-the-sidebar

_(not being prompted by "interesting" questions)_

**Comment by Hrxn** [comment]
> Actually, I've accomplished my goal already - to hide pesky `#hot-network-questions` on StackOverflow!

Do they now have a setting for this?

**Comment by stefek99** [comment]
No: https://meta.stackoverflow.com/questions/308022/is-it-a-good-idea-to-disable-hot-network-questions-to-boost-productivity

Highest voted answer:

> You need discipline.

# WTF?

Attention and mental discipline are finite resources, avoiding distractions at any cost... Invested a few minutes to build from source because `#hot-network-questions` was getting out of control, my life is better now.
