### ISSUE TITLE
The elements blocked by ublock are still saved when saving a webpage to local

### ISSUE THREAD

**Issue by liuxb** [gorhill/uBlock#2601]
### Describe the issue

The elements blocked by ublock are still saved when saving a webpage

### Steps for anyone to reproduce the issue

For example, 
use this rule,
|https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
in 
https://www.google.com/
then the image is filtered out, but when i save the complete page, this logo picture can still be found in the saved folder.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
