### ISSUE TITLE
file-scheme default block

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2603]
When opening local files in the browser (.htm and such), I added this rule to block any remote request:

`file-scheme * * block`

I suggest adding this as a _default dynamic_ because it's a good security/privacy measure. Plus it'll foster awareness of file-scheme to users.

**Comment by joey04** [comment]
Okay, I suppose it's a somewhat niche thing. Perhaps it could be mentioned in the wiki for Advanced config? (Part of the reason I posted this is I didn't see anything like this for "file-scheme" searching the repo.)

I do notice unexpected behavior: with this rule I don't see inline scripts being blocked when opening a local .htm file with several inline scripts.

Example 1: saving the [espn homepage](http://www.espn.com/) as HTML-complete in Firefox 53 then opening that saved .htm file in Pale Moon 27.3 caused it to hang for several seconds until a dialog popped-up asking to resume/suspend/stop a certain script. Huh? Shouldn't the `file-scheme * * block` rule block everything, including inline scripts? After all, the similar syntax `espn.com * * block` rule blocks all scripts and shows it in the logger.

Example 2: same but save the homepage as HTML-only. Then open in any browser (GChrome, etc.) and won't see inline scripts in the logger, though everything else appears to be blocked.

**Comment by joey04** [comment]
@gorhill is lack of inline-script blocking a limitation for file-scheme, or could it be added to uBO?

**Comment by gorhill** [comment]
Limitation for `file-scheme`, inline scripting is blocked by injecting a CSP header, and there is no HTTP header with `file:///` URL.

**Comment by joey04** [comment]
Thanks for explaining.
