### ISSUE TITLE
[Wiki] Fixing the old release URLs

### ISSUE THREAD

**Issue by bershan2** [gorhill/uBlock#2604]
@gorhill Unfortunately, GitHub does [not](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) support `pull` requests for Wikis, so you might have to apply fix manually (download my version, diff it with original, (if it's OK) commit it yourself. I kept the fix in my fork's Wiki [here](https://github.com/bershan2/uBlock/wiki/Change-log).

It is a trivial one, but I think we should still fix this.

**Comment by devnoname120** [comment]
I think that you can clone the wiki from there: https://github.com/gorhill/uBlock.wiki.git

**Comment by bershan2** [comment]
@devnoname120 Thank you for your advice, but it does not help me.
 - I already cloned the Wiki (and, in fact, the updated file is on [my clone of the Wiki](https://github.com/bershan2/uBlock/wiki))
 - Your link leads to the exact same page I cited in `not` in my first sentence.

**Comment by devnoname120** [comment]
Never mind, I must have read your post too fast, sorry for the interruption.

**Comment by gorhill** [comment]
I don't understand the issue here. What is "old release URLs"?

**Comment by bershan2** [comment]
@gorhill Sorry for being not specific enough, I meant the [pre-0.2.0.0 Change log](https://github.com/gorhill/uBlock/wiki/Change-log) and links to release .zip's, removed by https://github.com/gorhill/uBlock/commit/f99aa931f0a14d6d1381ea467128a5c82e40eab9.

I must have deleted the branch with a fix, I'm sorry about that.

**Comment by gorhill** [comment]
Ok, well I really won't spend any time on this, life is too short. Also consider there is another issue elsewhere which asks me to reduce the cost of cloning by removing pointless stuff from the git history, and surely all these zips would qualify as stuff to remove.
