### ISSUE TITLE
Dynamic rule "m.dhzw.org * xmlhttprequest block" is not supported. 

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#2605]
The ad URLs in [this script](http://2017512.dhzw.org:88/2017512.js) are often changed, and use the eval function to directly execute xmlhttprequest request ad script ` eval(req.responseText)`
To make a proposal to achieve the dynamic rules of domain name wildcard matching and third-party types of resource definitions, such as:
```
m.* * 3p-xhr block
m.* * 3p-meida block
m.* * 3p-image block
m.* * 3p-object block
```

**Comment by gorhill** [comment]
This can be addressed by existing filter syntax.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Peax** [comment]
How can this be addressed? I'm facing the exact issue right now, that wildcards can't be used on hostnames in dynamic filtering.
