### ISSUE TITLE
Firefox Nightly (v55.0a1) marks uBlock Origin/webext as LEGACY

### ISSUE THREAD

**Issue by geeknik** [gorhill/uBlock#2606]
Firefox Nightly (v55.0a1) is marking uBlock Origin/webext as LEGACY in about:addons. AFAIK, the LEGACY marker is meant to be for non-webextension addons, aka legacy. Is this intended behavior or should I file a bug with Mozilla? 

![untitled](https://cloud.githubusercontent.com/assets/466878/26021938/602f45a8-375d-11e7-8849-870a32c06830.png)

**Comment by gorhill** [comment]
Duplicate of #2576.

**Comment by geeknik** [comment]
Yeah, I noticed that AFTER I clicked submit. Silly me. (;
