### ISSUE TITLE
1.12.5b0 does not hide uMatrix placeholder

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#2607]
uBlock 1.12.3rc2:
<a href="https://lh3.googleusercontent.com/-PzRSojj0Osc/WRbJbMl-BAI/AAAAAAAAdZc/PYmxtQhpMS84y1KTb6y1mRF5h3PfknwHgCHM/s0/screenshot%2B2017-05-13%2B003.png"><img src="https://lh3.googleusercontent.com/-ZebX8MDEgIg/WRbJb8BRfRI/AAAAAAAAdZg/jYbyBopWJugddmyYW-r0Dbm_HPZ3mK3zwCHM/s0/thumb_b3eb0fc5c0ed5af855195bd85c9cb01e.jpg" border=0></a>
uBlock 1.12.5b0:
<a href="https://lh3.googleusercontent.com/-hFIZxm81KoE/WRbJcq4jSzI/AAAAAAAAdZk/-3kZ9GAsU4wqpvE8SYjZSJXO-1j-DZHfACHM/s0/screenshot%2B2017-05-13%2B005.png"><img src="https://lh3.googleusercontent.com/-hOJHErt0J1M/WRbJc8-p1HI/AAAAAAAAdZo/HwGt3PHPXTgxHGD1jacr2QPZNfRxV3dSACHM/s0/thumb_748fdce832cbb3321ffec0aec5d75b54.jpg" border=0></a>

```https://konachan.com/post/show/241863```

Win 8.1 x64, Firefox 52.1.1 x64, uBlock 1.12.5b0, uMatrix 1.0.1b0
Test on clean new profile also, with default browser/addon settings

**Comment by Havokdan** [comment]
Me too in Windows 10 x64, Opera 45 x64, uBlock 1.12.5b0, uMatrix 1.0.1b0

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
My bad, the frames should be collapsed (regardless of uMatrix), and they are not. I need to investigate.
