### ISSUE TITLE
case sensitivity - question 

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#2608]
Can you add functionality that allows you to block items without case sensitivity?

For example this ##.muimerPIa and this ##.muimeRPIa is not the same. Some developers change Letter size and ads are display.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Maybe there is another way to accomplish the filtering?

What you asked is not possible, there is no such thing as case insensitive CSS selector, which is what is used for cosmetic filtering.

**Comment by gorhill** [comment]
> For example this ##.muimerPIa and this ##.muimeRPIa is not the same. Some developers change Letter size and ads are display.

Just to comment further: this is no different than a site using random ids/classes, so the proper approach is to find another way to hide these than to rely on the ids/classes.

**Comment by MajkiIT** [comment]
It's not random. First day it's ##.muimerPIa. Few days later it's ##.muimeRPIa . One week later is ##.MuimerPIa . So always are the same letters but same are lower and some Upper . If it's problem I will find another solution.

**Comment by gorhill** [comment]
I know it's not random, but conceptually it's no different, it's the site changing its markups to work around blocker. A procedural cosmetic filter is probably the right answer here, as said case-insensitivity is not possible for attribute values.

**Comment by gorhill** [comment]
> there is no such thing as case insensitive CSS selectors

Today I learned.. Apparently it's possible to create case-insensitive CSS selector:
<https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors>.

In you case, that would be: `##[class~="muimerPIa" i]`
