### ISSUE TITLE
CloudFlare Analytics button

### ISSUE THREAD

**Issue by sn0wf1ake1** [gorhill/uBlock#261]
The Analytics button at https://www.cloudflare.com is filtered while the rest of the buttons are displayed. For future issues, how do I see which filter that is the culprit so I can report it to the person that is responsible for the mishap?

**Comment by gorhill** [comment]
> how do I see which filter that is the culprit so I can report it to the person that is responsible for the mishap

This is issue #58. For now you can make good guess, according to what filter lists you have selected. I can see the button with default lists.

**Comment by sn0wflake** [comment]
Okay, thank you. Will close the issue then. I'm new to this forum by the way.
