### ISSUE TITLE
Can I block horrible background advertisements like these?

### ISSUE THREAD

**Issue by mzso** [gorhill/uBlock#2611]
On some websites I get these super annoying background ads. Id like to block both the picture and especially think that's activated when I use autoscroll... It would be better if I could do this globally for all websites that do crap like this.

The element can selector select the link, but not the image, also the links constantly change, so it's of not much use.

https://prohardver.hu/hir/intel_itanium_9700_kittson_negy_uj_cpu.html
https://prohardver.hu/temak/proci_tuning/listaz.php

**Comment by mapx-** [comment]
```
prohardver.hu##[onclick^="$.ajax"]
/prohardver\.hu/dl/cnt/[A-Z0-9/-]{40,}/$image
```

**Comment by gorhill** [comment]
> The element can selector select the link, but not the image

Incorrect, the element picker offers you the background image as a choice under **Network filters** when there is one.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
