### ISSUE TITLE
Update Chrome Web Store Entry

### ISSUE THREAD

**Issue by noahleigh** [gorhill/uBlock#2615]
When will the extension version on the [Chome Web Store](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) be updated? 
It's still on [1.12.1](https://github.com/gorhill/uBlock/releases/tag/1.12.1), not the latest [1.12.4](https://github.com/gorhill/uBlock/releases/tag/1.12.4).

**Comment by Hrxn** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
