### ISSUE TITLE
How to Block Popup's and Redirects

### ISSUE THREAD

**Issue by JordanGS** [gorhill/uBlock#2616]
**Environment**

Windows 10
Firefox 53.0.2

**Question**

Trying to figure out how to block redirects and popups such as the ones caused on video streaming sites when you press proceed to video or the play button.

Most links in movie4k.to or tvmuse.com in the comments link to openload or thevideo, etc. They all have popups which i would love to block without affecting the video playback capabilities.

**Example**

[thevideo.me](http://thevideo.me/j26sxse96dof)

with you block, it will prevent all the ads i can see, there is a button **Proceed to Video**, if you click that. It will redirect to the video like it should but it also opens and quickly closes a popup. I would like to know how to prevent such popups. Not only for this site but any site in general.

Could you please shed some light on how i could go about this? If i have posted in the wrong section, please let me know where i should direct my question/support request before you close the topic. Thank you.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
