### ISSUE TITLE
Allow whitelisting current URL

### ISSUE THREAD

**Issue by sguergachi** [gorhill/uBlock#2617]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I would like to be able to whitelist the current URL from the extension instead of having to manually do it in the settings. AdBlock does this very nicely, so that might be a model to look at for reference.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: Chrome 58.0.3029.96 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.12.1

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Atavic** [comment]
From the Wiki: [The feature is already available: it is the big power button.](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site)

**Comment by sguergachi** [comment]
Ah, I thought that disabled uBlock completely (turn it off).
