### ISSUE TITLE
Hiding a page-wide gray filter on Google's Issue Tracker with the Element Selector does not work

### ISSUE THREAD

**Issue by devnoname120** [gorhill/uBlock#2619]
### Describe the issue

Using the Element Selector on a specific page produces a selector, yet the "Create" button is grayed out.

### One or more specific URLs where the issue occurs

https://issuetracker.google.com/issues/37141018

### Screenshot in which the issue can be seen

![Video of the issue.](https://i.imgur.com/VtINeJh.gif)

### Steps for anyone to reproduce the issue

1. Connect to your Google account.
1. Go to https://issuetracker.google.com/issues/37141018.
1. If this is your first time going to Google's Issue Tracker, then an Agreement should appear, if not you'll not be able to reproduce the issue.
1. Open the element selector.
1. Select the background filter blocking out the view.
1. Try to press "Create", but the button is grayed out.

### Your settings

- OS/version: Windows 10, 14393.1066
- Browser/version: Firefox 53.0.2
- uBlock Origin version: 1.12.4

##### Your filter lists

None.

##### Your custom filters (if any)

None on this website.

**Comment by gorhill** [comment]
uBO uses `nth-of-type` when there is ambiguity. However it should always use the tag name when it uses `nth-of-type`, otherwise the ambiguity is not guaranteed to be resolved, as shown by the current issue:

    > document.querySelectorAll('body > .modal-dialog-bg:nth-of-type(8)');
    < (2) [div.modal-dialog-bg, iframe.modal-dialog-bg]length: 2
    <     0: div.modal-dialog-bg
    <     1: iframe.modal-dialog

**Comment by gorhill** [comment]
I forgot about this issue, but ended up fixing it because the same sort of issue was submitted at <https://github.com/uBlockOrigin/uBlock-issues/issues/17>. Thus fixed with 674c3c60796d.
