### ISSUE TITLE
where is the ideal place to report adblock blocking?

### ISSUE THREAD

**Issue by Phlipout** [gorhill/uBlock#2621]
https://www.receive-sms-online.info/read-sms.php?phone=14083896925

Is blocking adblock.  I use uBlock origin on Waterfox and Iridium (chromium) with Reek and AdBlock protector userscripts via tampermonkey

and these filters:

![screen shot 2017-05-16 at 5 55 47 pm](https://cloud.githubusercontent.com/assets/28744287/26134079/ed13de42-3a60-11e7-86b1-d1f75b55c2ef.png)

inline script blocking seems to work in these situations (as it does here) but I am unclear how to examine the contents of an inline script to check for potential breakage

`||www.receive-sms-online.info/read-sms.php?phone=14083896925$inline-script,domain=www.receive-sms-online.info`

**Comment by bershan2** [comment]
@Phlipout Since apparently you already reported this (before I even posted my reply) at [AdBlock Protector issue #211](https://github.com/jspenguin2017/AdBlockProtector/issues/211), I recommend you close this uBO issue.

**Comment by Phlipout** [comment]
yeah I found a  place.  Thank you for your great freeware
