### ISSUE TITLE
ABP Subscription Links Not Understood

### ISSUE THREAD

**Issue by pjpreilly** [gorhill/uBlock#2622]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Trying to add filter subscriptions from filterlists.com. Clicking add returns an error for ABP protocol. This is the only OS I have the problem on. Works fine on Windows 10 as well as any OS x I've tried. Also Adblock plus works fine on this OS on both browsers. This problem occurs without Adblock Plus enabled/Installed.

### One or more specific URLs where the issue occurs
abp:subscribe?location=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Fadwarefilters.txt&title=Adware%20Filters (This is the exact URL)
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
![screenshot_2017-05-14_20-51-56](https://cloud.githubusercontent.com/assets/10430084/26136079/c5e2d6c6-3a87-11e7-898c-40fc03846c18.png)

### Steps for anyone to reproduce the issue
Go to the filterlists.com website
Click ADD to any filter subscription
observe error (Picture)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Manjaro (32 bit) latest stable (rolling release Xfce desktop)
- Browser/version: Firefox 52.1.0 esr (as well as Chromium  58.0.3029.110-1)
- uBlock Origin version: 1.12.4

##### Your filter lists
NA
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
NA

**Comment by gwarser** [comment]
Using left mouse button? This happens when opening in new tab, because is handled by content script.

**Comment by gorhill** [comment]
Timing issue, already reported at: <https://github.com/collinbarrett/FilterLists/issues/79#issuecomment-282627707>.

Potential solution: adding a (1 second?) delay before checking for `abp:` links on the page.

**Comment by pjpreilly** [comment]
Would/should pre-loading filterlists.com first with Ublock disabled & the enabling Ublock have any affect on the timing? Would you expect this to be a work around?
