### ISSUE TITLE
Remove Fanboy's "Officially unsupported" filter lists from regional lists

### ISSUE THREAD

**Issue by stanlane** [gorhill/uBlock#2623]
### Describe the issue
Can you please remove these regional filters?:
* [https://www.fanboy.co.nz/fanboy-korean.txt KOR: Fanboy's Korean]
* [https://www.fanboy.co.nz/fanboy-swedish.txt SWE: Fanboy's Swedish]
* [https://www.fanboy.co.nz/fanboy-vietnam.txt VIE: Fanboy's Vietnamese]

All of they contain this text:
>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>!!!!!!!!!!!!!!!! Officially unsupported !!!!!!!!!!!!!!
>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- uBlock Origin version: 1.12.4

##### Your filter lists
Default

##### Your custom filters (if any)
None

**Comment by stanlane** [comment]
https://github.com/gorhill/uBlock/issues/2592

**Comment by stanlane** [comment]
https://github.com/gorhill/uBlock/issues/2594

**Comment by gorhill** [comment]
Two of them were last updated this year, I still consider them relevant.

Please, do not spam with issue numbers.
