### ISSUE TITLE
Support Adguard's `[-ext-has="..."]` syntax => convert to uBO's `:has(...)`

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2624]
<https://github.com/gorhill/uBlock/issues/1930#issuecomment-241997548>

I am considering adding Adguard's _English filters_ to uBO's stock lists, as it takes care of many things not covered by EasyList, so extending compatibility as much as possible is a requirement.

**Comment by happysurf** [comment]
Actually I use Adguard Spyware filter, Social Filter and Annoyances filter.
These filters are small but very powerful without any problems.
In my opinion are better of > Social > Fanboy's lists and > Privacy >Easy Privacy.
Will be great add also these filters.

**Comment by gorhill** [comment]
> Why UBO use only in the Adguard English filter a very small number of entries?

Read the documentation please: <https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters>.

**Comment by gorhill** [comment]
Fixed with be9d76f43d56efc34d7038657b735ba91373be03.

**Comment by gorhill** [comment]
The real fix does map Adguard's `-ext-has[...]` to uBO's `:if(...)`, given that `-ext-has` is often used with procedural selector `contains` as part of its argument.
