### ISSUE TITLE
[Feature Request] Block Entire Site When Ads Are Present

### ISSUE THREAD

**Issue by Miserlou** [gorhill/uBlock#2626]
This will probably be a controversial idea, and likely out of scope for the project. Still, it is a feature that I want, and that others may want, and that I would be willing to work on to contribute an implementation.

I don't want to support or consume any ad-supported media whatsoever. I would like to block not just the ad, but the entire website which hosts the ad. This way, my web browsing experience will be entirely confined to non-commercial websites (personal homepages, Wikipedia, single-issue community forums, etc) - the "good old" web. You can imagine how this could also lead to the creation of a non-commercial Google alternative. This could be implemented as an "advanced user" feature.

Thoughts?

**Comment by gorhill** [comment]
Declined, beyond uBO's purpose.
