### ISSUE TITLE
Order of whitelist directives not preserved

### ISSUE THREAD

**Issue by ralish** [gorhill/uBlock#2627]
### Describe the issue
Order of whitelist directives is not preserved. This is frustrating and counter-intuitive, particularly when used with comments to break-up larger lists. In this case, all comments are placed at the top while the directives are sorted alphabetically. Issue occurs on clicking *Apply changes*.

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

Before *Apply changes*:
<img width="139" alt="unsorted list" src="https://cloud.githubusercontent.com/assets/3214803/26183094/e259db04-3bbf-11e7-9956-d9b8e18a8798.PNG">

After *Apply changes*:
<img width="143" alt="sorted list" src="https://cloud.githubusercontent.com/assets/3214803/26183093/e25781c4-3bbf-11e7-9b5a-b936971c346a.PNG">

### Steps for anyone to reproduce the issue

1. Populate the whitelist with several directives, comments, and optionally new-lines.
2. Click *Apply changes* and observe the list is immediately sorted alphabetically.

### Your settings

- OS/version: Windows 10 x64 v1703 (Creators Update)
- Browser/version: Chrome v58.0.3029.110 64-bit (Latest stable at time of writing)
- uBlock Origin version: v1.12.4 (Latest stable at time of writing)

##### Your filter lists

N/A (but happy to provide if that's incorrect)

##### Your custom filters (if any)

N/A (but happy to provide if that's incorrect)

**Comment by Atavic** [comment]
It's how it works. I understand that the list Before _Apply changes_ is easy toread than the one
After _Apply changes_ but the #internal entries end with `-scheme` while #Miscrosoft entries are URLs.

**Comment by gorhill** [comment]
I am going to decline this.

The _Whitelist_ pane is merely a view on uBO's internal data, which you are allowed to raw-edit, but once you click _Apply changes_, uBO reads and parses the data to store it back into its internal data structure. For instance, this internal data structure is directly modified by the power button in uBO's panel, and if you were to toggle back on uBO for say `azure.com` (thus removing the whitelist directive `azure.com`), and then back off, there is no way uBO would know that `azure.com` has to be at a very specific place in the list.

**Comment by ralish** [comment]
@Atavic The example I provided is substantially simplified just for illustration. My actual list is far more complex.

@gorhill Thanks for the incredibly fast response and explaining the rationale. It's clear this is not a priority, but if I have some spare time in future would you consider a pull request? I suspect I won't get round to it, but if I did, don't want to waste my time and yours on something that there's no chance would be merged.

**Comment by Atavic** [comment]
So if the actual list is longer, you can keep a backup in text format.

**Comment by ralish** [comment]
@Atavic Sure, but that's a pain to have to remember to keep two lists in sync plus it's time-consuming. Anyways, this honestly isn't a big deal, but if @gorhill is open to the idea of a PR to implement such a capability I might work on it in future.

**Comment by Atavic** [comment]
Problem is that it parses alphabetically. With long lists you can use diff on linux or Notepad++ with its [Compare Plugin](http://docs.notepad-plus-plus.org/index.php/Plugin_Central#C) on windows.
