### ISSUE TITLE
Performance on speedometer benchmark

### ISSUE THREAD

**Issue by koboltzz** [gorhill/uBlock#2628]
- OS/version: Windows 10 Creators Update x64
- Browser/version: Firefox 54.0 - Firefox 55.0 x64
- uBlock Origin version: 1.12.0 - 1.12.5b3, XUL tested, webext hybrid tested, full webextension tested
- my filter lists: Default filter lists + easylist + easyprivacy + fanboy's annoyance list + I don't care about cookies

Dear all,
I wonder why on **clean profile**, just the addon installed, addon enabled, filterlists see above, there is a big hit in performance on [speedometer](http://browserbench.org/Speedometer/)?

When I disable ublock origin I get **97** runs/minute. When I enable ublock origin I get **65** runs/minute.

When I do exactly the same (same browser version, clean profile etc.) with adblock plus (same filterlists added) I get still around **95** runs/minute.

Sadly I observe in several other benchmarks (like traditional javascript benchmarks like [jetstream](http://browserbench.org/JetStream/)) **since one month** ublock origin reduce performance more than adblock plus on firefox nightly 54.0 till today.

Since this is a 'long' period with many updates by mozilla on firefox and by Raymond Hill on ublock origin - but still the same result every release - I want to tell you about it.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/2552

**Comment by koboltzz** [comment]
Interesting, thank you :)

But I have to say, I did the [benchmark](http://www.raymondhill.net/ublock/pageloadspeed.html) from Raymond Hill just now on [www.t-online.de](www.t-online.de) with both ublock origin 1.12.5b3 and Adblock Plus 2.8.2.4246 beta.
Clean profile etc. like always.

Result:
ublock origin: **~1300ms**
Adblock Plus: **~1600ms**

**BUT:**
You see something different, the opposite. While Adblock benchmark is running the website won't go away/become blank for a short time like it is doing while ublock origin benchmark is running.

Therefore the user gets the feeling Adblock Plus is **faster in real world**. Any news on this?

**Comment by koboltzz** [comment]
So this is a 'I don't care!'?

**Comment by gorhill** [comment]
The label says "duplicate".

**Comment by koboltzz** [comment]
I can read that... I was writing about your benchmark which seem to not show real word page loading.

**Comment by gorhill** [comment]
Here I get:

uBO + default settings + EasyList Germany: Average (valid): 2164.43 ms (11/14 iterations)
ABP + EasyList + EasyPrivacy + EasyList Germany: Average (valid): 2788.30 ms (11/17 iterations)

That is real world page load speed.

Just use ABP if you think it offers you better performance, I can only debate objective measurements, not someone else's "feel".

**Comment by koboltzz** [comment]
Shoot a video and you will see the main news will always appear faster on Adblock Plus.

**You** think page load is only finished when even all unimportant things are loaded. 
**The user** thinks, I can read the news first on Adblock Plus.

I just wanted to inform you about this pageload priority which seems to better handled on Adblock Plus. Sad that you are not ready to open your mind for 'someone'. Thx anyways.

**Comment by Hrxn** [comment]
Exact example URL?

**Comment by gorhill** [comment]
> Shoot a video and you will see the main news will always appear faster on Adblock Plus.

Why don't you share your findings with everyone instead of asking to provide evidence to support **your** claims?

**Comment by koboltzz** [comment]
@Hrxn 
Still http://www.t-online.de/
@gorhill 
I do not know why you seem to be pissed off, but that is often read about genius (this is no joke, I have high respect).
I will make two videos to show you.

**Comment by gorhill** [comment]
> Speedometer is close to real world performance

> I do not know why you seem to be pissed off

Locking issue due to trolling. As said, just use ABP and move on.
