### ISSUE TITLE
New Install Warnings

### ISSUE THREAD

**Issue by DVette** [gorhill/uBlock#2633]
First thing that happens on a new install is a scary dialog warning that others have reported as well, resulting in myself & others canceling the install!!!
Screenshot here:
<a href="http://tinypic.com?ref=20h6l5g" target="_blank"><img src="http://i65.tinypic.com/20h6l5g.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
http://i65.tinypic.com/20h6l5g.jpg
http://tinypic.com/r/20h6l5g/9

Dunno which one is gonna work for you

### Your settings

Win 10 Home
Chrome Version 57.0.2987.133
uBlock Origin version 1.12.4 by the Chrome Web Store. Never installed

##### Your filter lists - n/a - never installed

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
> resulting in canceling the install

The install is cancelled if you choose to do so. This warning is from the browser, no uBO.

- <https://github.com/gorhill/uBlock/wiki/About-the-required-permissions>.
- <https://github.com/gorhill/uBlock/wiki/Privacy-policy>.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
