### ISSUE TITLE
Built in filters array update request

### ISSUE THREAD

**Issue by jspenguin2017** [gorhill/uBlock#2634]
Hi, I am the project owner of AdBlock Protector. 
First, thank you for including my filter in the built in filters array, however, the installation instruction is hidden too deep and I believe 9 out of 10 people will miss it. 
The filter doesn't work alone, without the Userscript, some website will be completely broken and some will show first party ads. 
Could you please add " (Please Read Instructions Inside)" to the filter name? 

Update: We ended up renaming the project to remove confusion, the new filter list is moved to: 
https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt

**Comment by Atavic** [comment]
`! This filter list is intended to be used with AdBlock Protector Script.`

> Setups we support:
> Browser: Chrome (desktop)
> Script host: Tampermonkey (desktop)
> Note: Greasemonkey is known to not work.

https://jspenguin2017.github.io/AdBlockProtector/

**Comment by jspenguin2017** [comment]
@Atavic Due to limited resources, I can currently only support one setup, if you wish to help, please let me know.

**Comment by Atavic** [comment]
I should look at your work first. It seems to me that Firefox isn't 'officially' supported? Tampermonkey does work on _Firefox >= 46_

**Comment by jspenguin2017** [comment]
@Atavic Do you want to offer support for FireFox? We did have a few FireFox specific issues, if you want to investigate, please let me know.

**Comment by jspenguin2017** [comment]
I see that the home button points to contribution guideline 😄 
Thank you very much!
