### ISSUE TITLE
Bring back compatibility with W10 14.393.0 builds

### ISSUE THREAD

**Issue by xroginhox** [gorhill/uBlock#2635]
I tried download download the extension in the store for the edge in version 14.393.1198 and it says that it is not compatible with my version and should update to version 15.063 but I did not like this new version of windows and I really like this extension in my opinion Is the best of all. Please release it to anyone who uses this older version of windows in the store if at all possible.

**Comment by gorhill** [comment]
I do not maintain the version for Edge. See <https://github.com/nikrolls/uBlock-Edge/issues>.

**Comment by Hrxn** [comment]
What's the issue with the Windows version? What is wrong with that?

**Comment by xroginhox** [comment]
Sorry I did not know this, I already posted the request in the right place. Thanks a lot for the help!!
