### ISSUE TITLE
Continuous crashing on PortableApps Google Chrome Dev

### ISSUE THREAD

**Issue by kindrudekid** [gorhill/uBlock#2637]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

I use google chrome dev on the portable apps platform.

Recently since last 3-4 Chrome on Dev release channel, the extension keeps crashing. Chrome notifies me of extension crashed, click here to reload it

Version on Portable Apps platform: GoogleChromePortableDev_60.0.3100.2_online.paf.exe 
Version as Per installed dev on windows: Version 60.0.3100.0 (Official Build) dev (64-bit)

The only difference I noticed is the version on portable apps platform being slightly ahead and it being 32 bit.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Download Portable Apps Chrome Dev from https://sourceforge.net/projects/portableapps/files/Google%20Chrome%20Portable/
2. Install it in some directory and run Chrome Dev
3. Install ublock origin, extension crashes.

Install dev channel like a regular install and you will notice it doenst crash.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7
- Browser/version: Latest Dev Channel
- uBlock Origin version: Latest

##### Your filter lists

Default list with facebook annoyance too enabled.

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
uBO is javascript, javascript is not supposed to crash a browser -- you need to report to the browser devs.

Furthermore, you downloaded what seems to be an old version from a non-vendor location, I support only official version of Chromium, Chrome, Firefox, etc.

**Comment by kindrudekid** [comment]
> uBO is javascript, javascript is not supposed to crash a browser -- you need to report to the browser devs.
Okay. Not well versed in this, but it is crashing the extension. It works perfectly fine on the Beta and Release channel of chrome on portable platform.

> Furthermore, you downloaded what seems to be an old version from a non-vendor location, I support only official versions of Chromium, Chrome, Firefox, etc.
The setup simply passes parameter to the installation on where to install . The Portable launcher simple launches chrome by telling where the data is located, similar to firefox profile path (firefox -profile "profile_path"). It still downloads the release package from the Google servers.


Attaching screenshot of versions for both installed and portable platform.
**Portable Dev:**
![image](https://cloud.githubusercontent.com/assets/1558094/26316180/05cb4caa-3ed9-11e7-9e70-f08965155225.png)

**Dev installed**
![image](https://cloud.githubusercontent.com/assets/1558094/26316183/097a1138-3ed9-11e7-89cb-b10dd557732f.png)


The only difference I see is as I mentioned is the 32 bit / 64 bit and the portable version being slightly higher. 

I am currently running an older version on Portable apps platform and the extension is running:

![image](https://cloud.githubusercontent.com/assets/1558094/26316305/6e4a8462-3ed9-11e7-9ab2-8ae55fc65ac1.png)
