### ISSUE TITLE
Redirect Control 

### ISSUE THREAD

**Issue by 1452474** [gorhill/uBlock#2638]
Hi,

I do not know if I am in the right place but this site is not very accessible ... I do not speak English.
I would like to know if it is possible to block the redirection of a page, such as "Redirect Control" which is an addon of Firefox?
https://addons.mozilla.org/en-US/firefox/addon/redirect-control/

This means preventing redirection, and staying on the current page. Instead of blocking the display of the page where we were redirected ...

Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
> I would like to know if it is possible to block the redirection of a page, such as "Redirect Control"

No.
