### ISSUE TITLE
Ublock's Element picker occurs an error

### ISSUE THREAD

**Issue by airoys** [gorhill/uBlock#2639]
When I use a css with Stylus ,The Ublock's Element picker occurs an error
however，the Adblock Plus doesn't have this problem.

css url: https://userstyles.org/styles/104973/theme
the css is used for http://www.kafan.cn/

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Your issue is missing all key info, details, repro steps, pointing **exactly** what is the issue in details.
