### ISSUE TITLE
Regex filters showing up as /undefined/ in logger

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uBlock#2640]
**Environment:**
uBlock Origin 1.12.5b7
Firefox 53.0.3
new profile

**Steps to reproduce:**
1) under Dashboard > 3rd-party filters, un-check all filters except "My filters"
2) add custom filter: `/g[io]/$~stylesheet`
3) open the logger, set to "All"
4) in a new tab, open https://github.com/gorhill/uBlock/
5) look at the blocked items in the logger

**Expected results:** Where items are blocked by the regex filter, logger shows the exact filter in each case.

**Actual results:** Logger replaces the regex filter pattern with `/undefined/`, and replaces the filter's type option with the request type.

**Comment by laniakea64** [comment]
Pattern display is fixed with 1.12.5b8, thanks! 😃 

The filter's type option is still showing as the request type, instead of `~stylesheet`.

**Comment by gorhill** [comment]
> The filter's type option is still showing as the request type

That is by design, uBO reports the normalized (compiled) form of the filter, not the raw form.

**Comment by laniakea64** [comment]
Ah ok, thanks for the explanation.
