### ISSUE TITLE
[Release History] Moving the 0.9.3.0 - 0.2.0.0 release messages to this repo

### ISSUE THREAD

**Issue by bershan2** [gorhill/uBlock#2641]
Currently uBO releases from 0.2.0.0 up to [0.9.3.0](https://github.com/gorhill/uBlock/releases?after=0.9.3.0) do not have release messages (because those were lost during forking), instead Wiki page links to [the old repo releases](https://github.com/chrisaljoudi/uBlock/releases). However, @gorhill, if you have time, you could easily add them by going to https:\//github.com/gorhill/uBlock/releases/tag/[release tag] and clicking button [Edit tag], and adding the message.

Pros:
+ the release date, tag, and commit stay intact; only message content (or title, if you want) and release author are changed (updater becomes the new author).
+ no dependency on old repo
+ remove the annoying ublock.org links and [donate] buttons
+ after this, new repo will have everything except old issues and pull requests.

Cons:
- copying all 93 release messages and release packages (and removing [a beta release](https://github.com/gorhill/uBlock/releases/tag/0.8.5.4-beta.0)) would take time. After doing a trial run on my fork, I estimate it will take ~30-50 min.

**Comment by bershan2** [comment]
Alternatively, I could try to write a tool with [GitHub Release API](https://developer.github.com/v3/repos/releases/), and publish the source code here. Then you would be able to verify its correctness (on a new branch) and then use on the master branch.

**Comment by gorhill** [comment]
> if you have time

No.
