### ISSUE TITLE
Is there a way to prevent users from turning ublock off

### ISSUE THREAD

**Issue by 1951FDG** [gorhill/uBlock#2642]
Hi,

Is there a way to prevent users from turning ublock origin off by clicking on the on/off button, like a setting that can be saved to the configuration for example for google app management.

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

**Comment by gorhill** [comment]
You can't prevent uBO from being turned off on a site, but you can use `adminSettings` to restore the admin-picked whitelist directives so that if a user turned off uBO on a site, the whtielist directive won't be there after a reload of the extension.

**Comment by 1951FDG** [comment]
Thx, that is good to know!
