### ISSUE TITLE
Can't add dynamic rules except with wildcard request-type

### ISSUE THREAD

**Issue by stunpix** [gorhill/uBlock#2644]
I have only 2 default `behind-the-scene` rules in Permanent and Temporary lists. I press Edit on Temporary list and add any number of rules with non-wildcard request-type in any combination. For example:

```
* google.com 3p-script block
* vk.com image block
aaaa aaaa inline-script noop
```

then I press Save and no new rules are saved. Only rules with wildcard request-type accepted:

```
* google.com * block
* vk.com * block
aaaa aaaa * noop
```

Then I can commit them to Permanent list.

"Advanced user" checkbox is enabled.

Linux Ubuntu 16.10 / Chrome Latest / uBlock v1.12.4

**Comment by gorhill** [comment]
There is a link to documentation at the top of the pane: ["Dynamic filtering: rule syntax"](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax).

> With hostname-based rule, the type is always *, meaning the rule will apply to any type of request.

Please be sure you go through the documentation before opening issues.

**Comment by stunpix** [comment]
Sorry. My fault. A "type" word was a bit generic for me, so I didn't recognize what a type. How about to replace it with more specific "request-type"?

**Comment by stunpix** [comment]
Ahh sorry, my fault.
