### ISSUE TITLE
Chrome Beta: Inline scripts still only for hole site ... afterscriptexecute through ws?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#2646]
Sorry, I am confused about the following things:

I use currently Chrome Beta too ...

Am I right with:

1) I can block inline scripts for a hole page only (all inline scripts)?

2) As workaround for afterscriptexecute it's possible to handle that through Websocket (via uBlock Origin and/or uBlock Extra)?

**Comment by Atavic** [comment]
1. Check the [Wiki](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Hrxn** [comment]
FYI, this wiki page is not up to date, unfortunately.
The related Chromium issue is **Wontfix** now, and the spec has changed as well, by removing the parts implemented by Firefox.
 https://github.com/whatwg/html/pull/1103
