### ISSUE TITLE
Facebook image upload + posts not working with uBlock on Safari

### ISSUE THREAD

**Issue by gr4v1ty69** [gorhill/uBlock#2647]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs : https://www.facebook.com

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen : https://d2r1vs3d9006ap.cloudfront.net/s3_images/1601534/RackMultipart20170525-41234-zbu729-issue_inline.jpg?1495741559

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue 

1. Go on Facebook and try to upload a picture in a message, try to upload a file in a group, try to make a post and you'll get the issue. Can't be more detailed then that.

### Your settings : 
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Mac OS Sierra : 10.12.5
- Browser/version: Safari Version 10.1.1 (12603.2.4)
- uBlock Origin version: uBlock 0.9.5.2

##### Your filter lists : Default filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
This is not the place for Safari or Edge.

Safari: <https://github.com/el1t/uBlock-Safari#ublock-originfor-safari>.

Also, investigate your issue yourself first to rule out the problem are caused by bad filters in a filter lists -- any filter issue must be reported to filter list maintainers.
