### ISSUE TITLE
[suggestion] Rework on matrix color system

### ISSUE THREAD

**Issue by monkeymagic29** [gorhill/uBlock#2649]
I'm a Firefox user who really prefers to have a dark screen.
Consequently, rather than having to configure themes individually and unnecessarily compromise the browser by using extensions to manage them, I often setup global coloring instead.
I miss out on some contents; I never care.
I, however, still found myself cycling browser.display.document_color_use between 0 and 2 every now and then only because dynamic filtering matters to me, and its indication system isn't robust for this practice.
After struggling with this for 2+ years, I'd hope you forgive my audacity to reconsider how you implement it.
I know which column is allow, noop, or block; what I can't know at the moment is if and which ones are being activated within global and local columns. Just by associating the value of activated filters with browser.display.foreground_color value would already be enough for me.
But whatever you decide to do, know that I'm very appreciative of your work here. Keep it up!

Problematic url:
chrome://ublock0/content/popup.html

Don't think there's a need for screenshots. 
It's always reproducible by setting the value of browser.display.document_color_use to 2.

- OS/version: wouldn't matter, I think; but I'm using GNU/Linux Ubuntu 17.04
- Browser/version: Firefox 53.0.3
- uBlock Origin version: 1.12.4

**Comment by gorhill** [comment]
Just don't have the time, even less when it comes to address issues as a consequence of someone bypassing HTML document's styles.

**Comment by gwarser** [comment]
I think this is accessibility issue. Looks like this when high contrast is enabled in control panel in windows:

![hicont](https://cloud.githubusercontent.com/assets/886325/26493929/80ebcea0-421c-11e7-90f1-ceb5efddfbde.png)

**Comment by monkeymagic29** [comment]
Aw, didn't think would be shot down so soon. Alas, I do understand it has little to do with core functionality; just thought that since the lead had already developed color blind support, I might as well address the root of the problem, perhaps even replace the color system entirely with least resistant alternative that's not totally dependent on CSS or color. And as @gwarser pointed out, there are people who may legitly need to use high contrast that overrides the CSS and encounter similar problem to me; even if mine is largely self-inflicted.

In the meantime, if anyone could figure out how to create override exception for a particular html without heavy modification on Firefox, kindly let me know.

**Comment by gorhill** [comment]
> replace the color system

How does a HTML document detect what the color system is? There is no built-in functionality for this. Your OS is un-selectively clobbering all the color styles of the HTML document, without its knowledge.

Whatever clever solution one would come up with, it would be just a matter of time before _someone else_ open an issue that uBO is not compatible with _their_ personal external settings (out of control/view of uBO) causing their own set of issues of document style clobbering.

It's not something I want to deal with -- and that is one of reason the project is GPLv3, whoever wants something which I don't want to deal with (a.k.a. "declined"), please respect that I won't spent more time than I can afford or want on this project, or that I won't spend time on what I see quite tedious work for no sense of having accomplished something fulfilling (which is what gets me going with this project): please fork and work on your solution.<sup>[1]</sup>

The nice thing with people being proactive by forking and working on a carefully well-crafted solution for whatever they see as an issue, is that whoever does this will get some insights that whatever they saw as trivial fix (conveniently for _someone else_ to actually deal with) is anything but trivial.

***

<sub>[1]  If the solution is outstanding work, well crafted, with attention to details, and care for all immediate and future consequences of the changes and possible regressions on all platform/settings, I would much more open to accept a pull request.</sub>

**Comment by seanrand** [comment]
Sorry for being off-topic, but thanks for actually spelling that out for once, gorhill. Your moderation style can 
 sometimes be quite harsh and might be misunderstood by people who don't follow the project. I'm just glad you still feel fulfilment from this project, which is not always a given when having to personally deal with requests, questions and gripes from a user base.

**Comment by joey04** [comment]
Well said, Sean. And a big thanks to you, @gorhill for all your hard work and dedication to this truly fantastic browser extension. It's easily the best one I've ever used (and that's going back to the early days of Firefox)!
