### ISSUE TITLE
Lost Disqus Comments

### ISSUE THREAD

**Issue by windyctyprog** [gorhill/uBlock#265]
Since the update to the new signed Firefox version, I have lost the ability to see Disqus comments. 

Even if I turn UBlocko off completely, still blocks comments. 

Livefyre is not affected, just Disqus.

I'm not hapless, but I can't figure out how to fix this...

Thanks.

**Comment by CrisBRM** [comment]
Have you tried disabling it completely? Version of firefox. uBlock's settings. Logger.

**Comment by windyctyprog** [comment]
Yes, completely disabled, nothing happens. Latest version of Firefox. 

I may have misspoke about "all"...I just tried a boatload (50+) of sites that use Disqus, some loaded slower than normal, but they did load.

The only site I can't load Disqus comments (after a sample of about 50 sites) is http://crooksandliars.com/

I've never had an issue on that site, didn't before the update to FF 38.0.1.

I use FanBoy's Ultimate in lieu of the individual lists from ABP - I also use the default lists in UBo, other than the Easy Lists.

Any ideas?

Thanks...

**Comment by gorhill** [comment]
Open the logger and see if there is anything related to Disqus being blocked, and if so, what is blocking it. Logger is the first thing to look at.

**Comment by gorhill** [comment]
> The only site I can't load Disqus comments (after a sample of about 50 sites) is http://crooksandliars.com/

I can see Disqus comments fine at <http://crooksandliars.com/2015/05/afa-wingnut-sandy-rios-liberals-and>. Using default filter lists.

**Comment by windyctyprog** [comment]
1. I can't see anything, none of these sites had issues before the installation of the signed add-ons and/or before FF 38.0.1. There are more sites I have found now where comments (not Disqus) can't be seen like http://talkingpointsmemo.com/

2. As it relates to Disqus on Crooks and Liars: scripts, images, domains are listed as being blocked- there is a boatload of Disqus items.

I had no issues until the updates yesterday, been using your extension for a while now, absolutely no problems.

I'm going to try something, bear with me, be back in a little while.

**Comment by gorhill** [comment]
> As it relates to Disqus on Crooks and Liars: scripts, images, domains are listed as being blocked- there is a boatload of Disqus items.

Blocked by what filter(s)/rule(s)? The logger reports this.

**Comment by windyctyprog** [comment]
I wanted to see if there was a further update, and sure enough it updated me to 9.8.2, after updating yesterday to the previous signed version (I don't remember what the number was). 

I can now see the comments on both sites I mentioned...

What could have happened?

**Comment by gorhill** [comment]
> What could have happened?

No clue. What was the logger saying about what filter/rule was causing the block? Only thing I can think of is that there was a temporary dynamic rule in effect and restarting FF fixed this.
