### ISSUE TITLE
1.12.5  issue

### ISSUE THREAD

**Issue by olgon** [gorhill/uBlock#2651]
Add filter
`*$websocket,domain=~cackle.me` and go [this page](https://riafan.ru/725678-ponravilsya-nash-sait-dobav-v-izbrannoe-instrukciya/comments)
I see this in the logger
`*$websocket,domain=~cackle.me	--	websocket	wss://rt5.cackle.me/ws/cc3990409?_=1495811979541&tag=0&time=&eventid=`
with output logger filter `websocket`. Excluded `cacle.me` blocked

In uBO stable version  1.12.4
I see 5 blocked requests to different domains, among which there is no `cacle.me` ,, as expected

- OS/version:  windows 
- Browser/version:  firefox 54
- uBlock Origin version:  1.12.5b9

**Comment by gorhill** [comment]
Works as expected, you are misunderstanding filter syntax. `*$websocket,domain=~cackle.me` means:

> block all websocket connections while visiting sites **not** from `cackle.me`.

If your goal was to **not** block websocket connection to `cackle.me` while browsing the site `riafan.ru`, then the proper filter would be `@@||cackle.me^$websocket,domain=riafan.ru`, of course needed only assuming you have a block filter such as `*$websocket`.

**Comment by olgon** [comment]
However, this filter  behaves differently in  1.12.4 and 1.12.5b
This is the expected change in behavior, as I understand it

**Comment by gorhill** [comment]
> However, this filter behaves differently in 1.12.4 and 1.12.5b

Let me check this.

**Comment by gorhill** [comment]
I don't see any functional difference between 1.12.4 and 1.12.5b, in both cases the websocket requests were blocked on `https://riafan.ru/` with your `*$websocket,domain=~cackle.me`.

**Comment by olgon** [comment]
Logger output in 1.12.4
![1.12.4](https://cloud.githubusercontent.com/assets/20244103/26503841/f3edb32c-424a-11e7-8926-65ec08261e08.png)

1.12.5b9
![1.12.5b9](https://cloud.githubusercontent.com/assets/20244103/26503852/fdfff7bc-424a-11e7-9d93-6fa1aed038fd.png)

**Comment by gorhill** [comment]
Ok, the logger output is different but functionally the result is the same. This is because with 1.12.4, uBO was injecting a Content Security Policy ("CSP") in document/subdocument to prevent websocket requests, and this injection was reported in the logger. These entries in 1.12.4 did not mean these were actual websocket requests.

With 1.12.5, uBO no longer inject a CSP to block websocket requests, it can block them discretely as they actually occur (assuming your browser supports it), rather than pre-emptly through a CSP.

**Comment by gorhill** [comment]
Related conversation: <https://github.com/gorhill/uBlock/issues/2528#issuecomment-293343564>.

Note that I did change my mind later in the thread, and the behavior you are observing is the result of the change.
