### ISSUE TITLE
ublock0.sqlite has 1.4GB

### ISSUE THREAD

**Issue by knezi** [gorhill/uBlock#2653]
### Describe the issue
I've recently discovered that file extension-data/ublock0.sqlite has shocking 1.4GB. Briefly look into it, there are websites and anchor and classes, so nothing unusual. If you need more info about the exact content, I can provide it.
If this is a feature, can you add an option to limit the size of the database?

### Steps for anyone to reproduce the issue

1. Well, just use it for some time.

### Your settings

- OS/version:  Arch Linux
- Browser/version: Firefox 53 - 64b
- uBlock Origin version: 1.12.4

##### Your filter lists

Just default

**Comment by gorhill** [comment]
With default settings, your sqlite file should be in the 14 MB ballpark -- less if there is no selfie. I've never heard of a case of the file growing to such size, I suspect you are not reading properly the size:

![a](https://cloud.githubusercontent.com/assets/585534/26520771/c17e3b08-42a6-11e7-9290-41275c115fa7.png)

If the size you reported is right, you may be dealing with a corrupted sqlite file, out of control of uBO, and so you should backup your settings, delete the file, then restore your settings.

**Comment by knezi** [comment]
```
[knezi@holly extension-data]$ ls -l ublock0.sqlite 
-rw-r--r-- 1 knezi root 1574338560 27. kvě 16.18 ublock0.sqlite
[knezi@holly extension-data]$ du -h ublock0.sqlite 
1,5G    ublock0.sqlite
```
Ok, I'll delete it. I just thought that you might want some debugging output.

**Comment by gorhill** [comment]
I don't know how this could grow to such size. uBO will issue a `VACUUM` command once per session. Maybe you could inspect with a sqlite viewer to find out what is in there that takes so much size? The sqlite is just used as a key-value store by uBO ( one table).

**Comment by jawz101** [comment]
I just **Purge all caches** and then **Update now**.  I run the same OS and FFox version.

I notice a few MB size increase on other OS's as well but I assume it's just the database padding itself.  Like gorhill said, I dunno how that would happen without actually viewing the sqlite database.

**Comment by knezi** [comment]
Alright,
so there are 16 000 entries in the database.
700MB with 164 entries is occupied by cache/compiled/easylist
400MB, 104 entries, selfie.

There are only 50 distinct lines in easylist and they repeat.

It is full of lines that look like this:
n\u000b0\u000bad\u000b1a\u000b&ad_box_\nn\u000b0\u00
0bad\u000b1a\u000b&ad_channel=\nn\u000b0\u000bad\u000b1a\u000b&ad_classid=\nn\u000b0\u000bad\u000b1a\u000b&a
d_height=\nn\u000b0\u000bad\u000b1a\u000b&ad_keyword=\nn\u000b0\u000bad\u000b1a\u000b&ad_network_\nn\u000b0\
u000bad\u000b1a\u000b&ad_number=\nn\u000b0\u000bad\u000b1a\u000b&ad_type=\nn\u000b0\u000bad\u000b1a\u000b&ad
_type_\nn\u000b0\u000bad\u000b1a\u000b&ad_url=\nn\u000b0\u000bad\u000b1a\u000b&ad_zones=\nn\u000b0\u000badba

**Comment by gorhill** [comment]
> so there are 16 000 entries in the database

You mean the table has 16,000 rows?

**Comment by knezi** [comment]
Yes. These are top frequencies:

5667 blockedRequestCount
5665 allowedRequestCount
1874 assetCacheRegistry
325 assetSourceRegistry
171 cache/compiled/ublock-badware
167 cache/compiled/malware-0
164 cache/compiled/malware-1
164 cache/compiled/ublock-filters
163 cache/compiled/easylist
163 cache/compiled/ublock-privacy
161 cache/compiled/easyprivacy
154 cache/compiled/plowe-0
144 cache/compiled/ublock-unbreak
113 availableFilterLists
111 cache/compiled/public_suffix_list.dat
108 version
104 cache/compiled/user-filters
104 selfie
103 compiledMagic
103 selfieMagic
58 cache/easyprivacy
58 cache/malware-1
57 cache/public_suffix_list.dat
56 cache/easylist
56 cache/ublock-filters
56 cache/ublock-privacy
56 cache/ublock-resources
55 cache/assets.json
55 cache/malware-0
54 cache/ublock-badware
54 cache/ublock-unbreak
51 cache/plowe-0
13 netWhitelist

**Comment by gorhill** [comment]
Something is definitely wrong then, the table is built with the `name` column as the primary key, meaning there should be no duplicate in that column. Only explanation I can think of is corrupt database. It's not too difficult to cause sqlite corruption: force-quitting Firefox (Firefox API drives the sqlite file), or whole OS crash.

**Comment by knezi** [comment]
Force-quitting definitely happened, so it's this then. Thank you for
clarification.

**Comment by ethus3h** [comment]
For what it's worth, mine's more than 14 MB (it's ~75 MB), but I think it's probably normal (probably related to having many filter list subscriptions).

**Comment by jawz101** [comment]
@ethus3h you may want to look at the number beside each list to see how much lists overlap.  For instance, if one says "1,200 used out of 30,000" it's probably not worth using as most entries are being addressed by other lists.

A few other things to note:
The Fanboy+Easylist-Merged Ultimate List is essentially all of the Fanboy and EasyList entries combined so you should probably select _only_ this merged list or all of the EasyList and Fanboy ones for the same coverage.

Personally, I don't use any of the malware domain lists.  Your browser likely has malware site filtering already (Chrome and FFox use SafeBrowsing features to block such sites.)

I've read the Fanboy Social list is already in the Fanboy Annoyance list, so just use the Annoyance list.

**Comment by ethus3h** [comment]
@jawz101 Thanks for the thoughts, but I'm perfectly happy with it as it is... I was just pointing out that it can be substantially larger than 14MB in normal usage.

**Comment by step21** [comment]
@ethus3h Yeah, they did say 'with no selfie and 'usual' subscription' (or something along those lines :)
