### ISSUE TITLE
uBlock counter increases very quickly on twitter

### ISSUE THREAD

**Issue by DaveGahan** [gorhill/uBlock#2655]
Hello, I just noticed that uBlock Origin counter increases very fast when I'm on Twitter web site. Currently more than 50 in 30 seconds.

Here are requests log samples : 

![capture d ecran de 2017-05-27 10-37-26](https://cloud.githubusercontent.com/assets/12768499/26520863/46e9b1da-42db-11e7-9804-80c4e6c67f9a.png)

![capture d ecran de 2017-05-27 12-52-23](https://cloud.githubusercontent.com/assets/12768499/26520873/8b370f4a-42db-11e7-845f-6447ca3bf253.png)

- OS/version: Ubuntu/Gnome 17.04 (64 bits)
- Browser/version: Firefox 53.0.3 (64 bits)
- uBlock Origin version: 1.12.4

Filter lists selected are default filter lists + FRA + no custom : 

![capture d ecran de 2017-05-27 12-58-18](https://cloud.githubusercontent.com/assets/12768499/26520913/60a522fc-42dc-11e7-9895-a45502657b4f.png)

Do you thinks it's a normal behavior ?

Best regards.

**Comment by gorhill** [comment]
The logger shows you this is a normal behavior.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
