### ISSUE TITLE
How to "Not block Google's NoCAPTCHA re-CAPTCHA" information?

### ISSUE THREAD

**Issue by LokeYourLord** [gorhill/uBlock#2657]
### Describe the issue
So i would like to know if it is possible to implement it so, that uBlock Origin does NOT block Google its CAPTCHA information it needs to collect to "Verify that you are Human". Every time i see one of these, i need to do that Picture test in where you need to identify street names or the likes. Normally though, you should only have to click the button, and it should verify that you are Human (because of all the data that is being collected meanwhile you click that button and also before you click the button, all that stuff). But it doesn't do that, resulting in me having to take every single one of these tests, which take up time (not much, but it adds up).

### One or more specific URLs where the issue occurs
bs.to
All sites that use the "Verify that you are Human" reCAPTCHA service from Google.

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/5807595/26528452/7b33c0a8-43ac-11e7-9366-529ce9709f5d.png)

### Steps for anyone to reproduce the issue

1. Open Webpage that uses Google its reCAPTCHA (while running uBlock Origin)
2. See the Magic happen. It will ask you to complete some kind of random test.

### Your settings

- OS/version: Windows 10 Pro Creators Update
- Browser/version: Google Chrome v58.0.3029.110 (x64)
- uBlock Origin version: 1.12.4

##### Your filter lists

![image](https://cloud.githubusercontent.com/assets/5807595/26528470/ecdbc886-43ac-11e7-8cf1-f323a4c8b9f9.png)

##### Your custom filters (if any)

None

**Comment by wolfblake** [comment]
On my Firefox, I disable tracking protection while leaving uBlock enabled and the CAPTCHA shows up.

**Comment by gorhill** [comment]
> that uBlock Origin does NOT block Google its CAPTCHA information it needs to collect to "Verify that you are Human"

I can't understand what is the issue. uBO blocks according to filters, and Google captcha is not blocked with default settings. Sounds like you have a filter issue:

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by LokeYourLord** [comment]
Applied standard settings, issue still applies. I am only requesting help, as the issue still persists with standard filter settings for me.

**Comment by anewuser** [comment]
The person who opened this issue meant this: https://www.google.com/recaptcha/intro/invisible.html

People who use unprotected browsers and are tracked everywhere just have to click once now, while we are seem as "suspicious" for blocking connections to Google/cookies etc.

@LokeYourLord if you are willing to give up the benefit of privacy, you need to find out by yourself what to whitelist, or post on help forums. This repository is only for bugs.

**Comment by Tajnymag** [comment]
@LokeYourLord Have you found a solution?

**Comment by ZenFi** [comment]
uMatric block Google CAPTCHA too. I'll post when I next encounter what to allow through uMatrix.
