### ISSUE TITLE
Can't block behind-the-scene (1.12.5b13)

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#2658]
Blocking b-t-s appears to have stopped working in uBo 1.12.5 / Firefox 53 / Win 10.

This is my basic setup out of the box:

Filter:
`*$domain=behind-the-scene`

Rule:
I block third-party by default, therefore this rule is required: `behind-the-scene * 3p noop`

No whitelists.

- Run a quick test by checking for browser or extension updates, with uBo logger watching b-t-s
- In 1.12.4, observe that any b-t-s requests are now blocked as expected, unless explicitly allowed
- In 1.12.5, b-t-s requests appear to pass through with the filter being ignored

I have reverted to stable channel for now.

Thanks.

**Comment by gorhill** [comment]
The network requests were blocked, it was a logger UI issue, the logger was reporting as not blocked even though they were blocked.

**Comment by luxoflux** [comment]
The requests and connections were made, and I was able to receive b-t-s extension/browser updates. I verified this in the browser console as well.

**Comment by gorhill** [comment]
You're right, there is something else to fix below the first fix.

**Comment by luxoflux** [comment]
Wonderful. Thank you!
