### ISSUE TITLE
Performance issues in Firefox 39 beta 

### ISSUE THREAD

**Issue by tyaremco** [gorhill/uBlock#266]
In Firefox 39 I experience periodic jank (browser hangs) every 1-2min lasting 5-15s each. 
- When I disable uBlock Origin (9.8.1.1) the symptoms disappears.
- I'm not doing anything in particular when the issue occurs (can happen multiple times on a static page)
- I have not experienced this issue in Firefox 38 or below
- my Firefox session has hundreds of tabs, however the issue presents itself with only a few tabs loaded (ie. nearly all of the tabs are pending/unloaded)
- I first noticed this 1 month ago when I was testing Firefox 39 dev version.

I was able to narrow down the culprit by running the Gecko Profiler Addon.  I can upload my performance profile if you need it.  Here is a section of the timeline where I experienced the issue and the offending stack traces:
![screenshot-people mozilla org 2015-05-30 15-56-01](https://cloud.githubusercontent.com/assets/709811/7899550/7aaafd38-06e4-11e5-858b-1a4848241f4e.png)

It seems that vAPI.tabs.getAll() is responsible for the majority of the running time...

**Comment by tyaremco** [comment]
I can confirm that the same problem exists for chrisaljoudi/uBlock 0.9.4.

**Comment by gorhill** [comment]
Thank you very much for the report. This might also be the reason for #252 -- though it was FF 38.0.5.

**Comment by tyaremco** [comment]
The fix appears to be working great!

I maintain several Firefox bugs related to large numbers of tabs so I keep a setup such that these situations are easy for me to test.  I'll test #252 and see if I can get some useful information for you if it's not fixed.
