### ISSUE TITLE
First-party behind-the-scene requests treats as third-party

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#2661]
<a href="https://lh3.googleusercontent.com/-GddlCXtZEq4/WSzhAl4a2jI/AAAAAAAAdaQ/4UlNYL2hbPgQqMDt753QaqHHU0z3bSXGACHM/s0/screenshot%2B2017-05-30%2B006.png"><img src="https://lh3.googleusercontent.com/-ylejtrtPPak/WSzhA-E3kDI/AAAAAAAAdaU/YSa96VWRoAUlhcKpO7gFzKlghaCIjMCMQCHM/s0/thumb_2174b2be6d9790db1b9781d42d6118e5.jpg"></a>

Win 8.1 x64, Firefox 52.1.2 x64, uBlock 1.12.5b17, e10s disabled.

Default uBlock settings and filters + Fanboy’s Enhanced Tracking List + unwhitelisted behind-the-scene scheme.

**Comment by gorhill** [comment]
Behind-the-scene requests are all 3rd-party, that is why they are behind-the-scene, uBO is not given information about where they come from.

**Comment by aggat** [comment]
I think it's about this filter
`/favicon.ico$image,third-party,domain=~reddit.com`
from Fanboy’s Enhanced Tracking List. Favicons dont't load after #2658 fix
Perhaps it's worth adding something like this
`@@/favicon.ico$image,domain=behind-the-scene`
to Unbreak list

**Comment by gorhill** [comment]
Behind-the-scene requests are not filtered by default, one has to go through many steps to end up having them filtered.
