### ISSUE TITLE
Include Problematic Sites list

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#2662]
Hey,

Would be nice if uBo would include the problematic sites list among the list of supported lists. (Guessing under the "Ads" banner)

Limits Adblock Tracking, and stops/limits many Anti-adblock scripts. (Basically sites that track Easylist changes to keep countering us) 

https://secure.fanboy.co.nz/fanboy-problematic-sites.txt

(Is included in the Ultimate list, and Enhanced trackers)

While it uses ABP filters, it would still be useful for uBo users :)

**Comment by finr1** [comment]
Begin very well with 320 :skull: zombie filters "`@@`" which are not needed to uBO.

@gorhill  You have to reject this proposal.

**Comment by ryanbr** [comment]
Not sure if serious. uBo supports all the ABP filters, so going by that logic all subscriptions using ABP should be removed including Easylist, Easyprivacy etc.

**Comment by okiehsch** [comment]
I am pretty sure he means rules like `@@/ad_bomb/*$image` or `@@||shink.in/js/ads.js` which are not needed if you use uBO with default settings because of `redirect` or `script:inject filters` in `uBO-filters`.
But as you correctly state. these kind of exception filters are already part of pretty much all subscriptions.

**Comment by ryanbr** [comment]
I'm not going to fight for it, I see no difference with other related ABP subscriptions used by uBo.  Its just an offer for uBo users to use the subscription as a stand-alone list instead of using Enhanced-list/Ultimate list.

**Comment by okiehsch** [comment]
You misunderstand me, I am not against adding your `Problematic Sites List`, in fact I wonder why 
filters like `@@||shink.in/js/ads.js` are not part of `Easylist`.

**Comment by jspenguin2017** [comment]
@okiehsch That's not going to go well, as they can very well change the script to something that we don't want, instead, uBO should have a scriptlet that defined a read-only property (writing to it would silently fail), I propose a syntax like this: 
```
example.com##script:inject(define-read-only-property.js, canRunAds, true);  <-- for boolean
example.com##script:inject(define-read-only-property.js, canRunAds, 1);  <-- for integer
example.com##script:inject(define-read-only-property.js, canRunAds, "yes");  <-- for string
```
I think copying the code from `abort-on-property-write` and change 2 or 3 lines can get this working. 

I have `a.readOnly` in uBlock Protector, which does similar things... except it often lose in race condition...

**Comment by jspenguin2017** [comment]
I think this would work with minimal modification: 
<details>

```JavaScript
abort-on-property-write.js application/javascript
(function() {
	var magic = String.fromCharCode(Date.now() % 26 + 97) +
				Math.floor(Math.random() * 982451653 + 982451653).toString(36);
	var prop = '{{1}}',
                val = '{{2}}',
		owner = window,
		pos;
	for (;;) {
		pos = prop.indexOf('.');
		if ( pos === -1 ) { break; }
		owner = owner[prop.slice(0, pos)];
		if ( owner instanceof Object === false ) { return; }
		prop = prop.slice(pos + 1);
	}
	delete owner[prop];
        switch (val[0]) {
             case 't':
             case "f":
                 val = (val === "true"? true : false); break;
             case '"': break;
             default: val = parseFloat(val);
        }
	Object.defineProperty(owner, prop, {
                configurable: false,
		set: function() {
			//do nothing
		}, get: function() { return val; }
	});
})();
```

</details>

**Comment by okiehsch** [comment]
I agree with you that the site can easily change the script, my point with `@@||shink.in/js/ads.js`
was that the only way for `Adblock/Plus` users to beat those kind of `Anti-Adblock` scripts is the use of 
exception filters and `Easylist` is meant to work with all "mainstream" blockers and therefore such a filter should be part of, it in my opinion.

**Comment by uBlock-user** [comment]
File-names can be changed so easily, so that makes white-listed filters unreliable and a pain in the ass for the long term. Take for example `openload.co` Those guys would simply swap domain names and file names frequently and it would rather create another job for the filter list maintainer, but by patching the anti adblock and the popunder script, the domains swap and file-name swap no longer affects us in the long term. 

They will never swap one anti adblock script or one popup for another as it would get easily patched or might harm non-adblock users if not paid due attention while swaping and cover all bases before adding.

**Comment by okiehsch** [comment]
I agree and I was only making a general point, btw neither `@@||shink.in/js/ads.js` nor `@@||shink.in/js/showads.js` work anymore, because they changed the script to 
`shink.in/js/show_ads.js`.

**Comment by uBlock-user** [comment]
Yes exactly. They're screwing with the filter list maintainers because by white-listing you're surrendering to them, so they can do whatever the hell they want and when they want. On top of this, the filter list contains some white-listed ad-servers for some domains which is another issue.

**Comment by h1z1** [comment]
Including any list of sites is in effect free advertising for them.   I don't like lists primarily because I don't trust, and quite frankly never visited 99.9% of them.   It's quite simple if I need to add more then an exception or two, your site isn't worth my time.
