### ISSUE TITLE
Filters converted from Adguard are shown incorrectly in the logger

### ISSUE THREAD

**Issue by hant05080** [gorhill/uBlock#2664]
### Describe the issue

The filter list from which the filter was taken isn't shown in the logger.

### Screenshot in which the issue can be seen

![2017-05-30 19-05-04](https://cloud.githubusercontent.com/assets/28459131/26592925/f5338f5e-456a-11e7-95e4-d24aba7b505b.png)

### Steps for anyone to reproduce the issue

1. Subscribe to [Adguard Annoyances Filter](https://filters.adtidy.org/extension/chromium/filters/14.txt) or add this to your filters: `google.ru#$#.pdp-psy > .gb_Lc.gb_g[data-ved]{display:none!important;}`
2. Visit https://google.ru
3. Open the logger and find there `##.pdp-psy > .gb_Lc.gb_g[data-ved]:style(display:none!important;)`

### Your settings

- OS/version: Debian GNU/Linux
- Browser/version: Mozilla Firefox 53.0.3
- uBlock Origin version: 1.12.5b17

**Comment by hant05080** [comment]
The same issue with global hiding filters starting with `~`, e.g. `~example.com##div`.

**Comment by hant05080** [comment]
And one more case: hiding filters that contain several domains are shown correctly only on the last domain in a list. For example, `rbc.ru,yandex.com,yandex.ru##.banner` is shown in logger only on `yandex.ru`.

**Comment by gorhill** [comment]
Actually, all this is by design, not a new behavior: uBO shows you the normalized version of a filter, not the raw, un-parsed version.

So `~example.com##div` is normalized to:

    ##div
    example.com#@#div

While `rbc.ru,yandex.com,yandex.ru##.banner` is normalized to:

    rbc.ru##.banner
    yandex.com##.banner
    yandex.ru##.banner

And uBO won't report these filters if the element(s) they target is not found on the page.

**Comment by hant05080** [comment]
I describe the situation when the elements are found on the page and it's reported in the logger, but user can't see any information about this filter (like on the screenshot).

There are elements named `.banner` on both pages `rbc.ru` and `yandex.ru`, so filter `rbc.ru,yandex.ru##.banner` will work on them and it will be reported in the logger, but it will be correctly reported only on the `yandex.ru`. And vice versa, `yandex.ru,rbc.ru##.banner` will show empty white rectangle on `yandex.ru` and will report the information correctly on `rbc.ru`.

**Comment by gorhill** [comment]
> white rectangle on `yandex.ru`

I can't get the `yandex.ru` to report something about `.banner`, and using the dev console `document.querySelector('.banner');` returns `null`.

**Comment by gorhill** [comment]
Ok never mind, I swapped `yandex.ru` and `rbc.ru` and went to `http://www.rbc.ru/` and can now reproduce the issue.

**Comment by hant05080** [comment]
Just tested it on `rbc.ru`:

1. `rbc.ru##.banner`

![2017-06-08 00-05-17](https://user-images.githubusercontent.com/28459131/26901390-64607d96-4bde-11e7-8e41-3904c3e47079.png)
2. `yandex.ru,rbc.ru##.banner`

![2017-06-08 00-05-44](https://user-images.githubusercontent.com/28459131/26901398-6d62f6b2-4bde-11e7-8e94-441ebb0c7c8a.png)
3. `rbc.ru,yandex.ru##.banner`

![2017-06-08 00-06-14](https://user-images.githubusercontent.com/28459131/26901405-7287ca6e-4bde-11e7-9546-c21c26a9a4d9.png)

> I can't get the `yandex.ru` to report something about `.banner`

My mistake, there's a `###banner` on `yandex`, but the same problem occurs. An example filter `rbc.ru,yandex.com,yandex.ru##.banner` was taken as a part of a very long filter form Adguard Russian Filters.

**Comment by hant05080** [comment]
> uBO shows you the normalized version of a filter, not the raw, un-parsed version.

So there's one more issue with the logger.
1. Subscribe to `RUS: RU AdList`
2. Visit https://rsload.net
3. Open the logger and find `csp`

![2017-06-11 12-47-05](https://user-images.githubusercontent.com/28459131/27010077-fde226c2-4ea4-11e7-9192-d0569803a900.png)

**Comment by Halibut80** [comment]
> So there's one more issue with the logger.

@hant05080 Maybe you need to fill separate issue for that?

As temporally fix, style for Stylish/userContent.css:
```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document url-prefix("chrome://ublock0/content/logger-ui.html") {
    #filterFinderDialog .dialog code {
        max-height: 40vh !important;
        overflow: auto !important;
        display: inline-block !important;
        vertical-align: -6px !important;
    }
}
```

**Comment by gwarser** [comment]
2c9c98eb79c3e210ecba9c346b459fb1d8518881 introduced regression in logger.
On my system up to 10 seconds is needed for cosmetic filter details layer/dialog to appear after I click on it.

**Comment by gorhill** [comment]
Does the 7-second delay occur only the first time you lookup the filter, or does it happens also if you lookup again immediately?

**Comment by gwarser** [comment]
Happens every time, but may be little random in length - more like between 4 and 10 seconds.

This is visible in Chromium profiler in worker thread as regex.

![image](https://user-images.githubusercontent.com/886325/31280063-67ac64b6-aaab-11e7-970f-0a3a65e1eb52.png)
