### ISSUE TITLE
Adblock Protector List needs to be changed

### ISSUE THREAD

**Issue by gh0sti** [gorhill/uBlock#2665]
### Describe the issue
this list needs the URL changed to this link https://github.com/jspenguin2017/uBlockProtector the other one https://jspenguin2017.github.io/AdBlockProtector/ is a dead link so the list can't be updated.

- OS/version: win 10 15063.296
- Browser/version: Chrome  58.0.3029.110 (64-bit)
- uBlock Origin version: 1.12.4

##### Your custom filters (if any)
uBlock Protector List: chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt

**Comment by gwarser** [comment]
Already fixed https://github.com/gorhill/uBlock/commit/0ae695f8b1ac595e536a9a69dda86240e21d37dc#commitcomment-22306999

**Comment by gorhill** [comment]
This was fixed days ago with 0ae695f8b1ac595e536a9a69dda86240e21d37dc.
