### ISSUE TITLE
Dashboard link does not work while app notification is being displayed in Firefox

### ISSUE THREAD

**Issue by arana-krypteia** [gorhill/uBlock#2667]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

The "click to open the dashboard" link accessible from the toolbar icon does not work when an app notification message is displayed in Firefox (see screenshot linked below for clarification). 

Users might run into this issue and assume they mis-clicked the dashboard link, because the link will work once the notification has been cleared (automatically or manually).

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

https://i.imgur.com/NCu4zdJ.png

### Steps for anyone to reproduce the issue

1. Start Firefox with an addon that produces notifications (e.g. self-destructing cookies, random agent spoofer, etc)
2. Wait until the addon generates a notification.
3. While the notification is displayed, click the "click to open dashboard" link. (nothing will happen)
4. Dismiss the notification and click the "click to open dashboard" link again. (dashboard will open)

### Your settings

default settings

- OS/version: Windows 8.1 x64
- Browser/version: Firefox 53.0.3 (64-bit)
- uBlock Origin version: v1.12.4

##### Your filter lists
N/A

##### Your custom filters (if any)
N/A

**Comment by gorhill** [comment]
I can't reproduce on Linux/Cinnamon, the notification is displayed by the OS and i does not interfere. I can't test on Windows, I don't have it.

**Comment by Betsy25** [comment]
Not able to reproduce here, all's fine.

* OS/version : Windows 7 x64
* Browser/version : Firefox 53.0.3 (32bit)
* uBlock Origin version : 1.12.4
* Add-on showing notification : [Cookies Exterminator 2.8.2](https://addons.mozilla.org/en-US/firefox/addon/cookies-exterminator/) with which I replaced the not-e10 compatible [Self-Dustructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/).

**Comment by gorhill** [comment]
@arana-krypteia You will have to investigate the issue on your side, so far it can't be reproduced, suggesting it is specific to your environment.

**Comment by Remu-rin** [comment]
I can reproduce on Win 7 x64, FF 53.0.3 x64, uBO 1.12.4.
Not only link to dashboard doesn't work, but also link to the logger. Element-picker button disappears, dynamic filtering pane becomes empty (created rules are not visible even after notification disappears, but they are actually created). Also affects uMatrix 1.0.1b1, popup is empty, ignores large size setting, logger button doesn't work.
Used notification from https://addons.mozilla.org/en-US/firefox/addon/web-scrobbler/
Screens:
https://i.imgur.com/CuclmSk.png
https://i.imgur.com/vXBnDMD.png

**Comment by gorhill** [comment]
Whoever can reproduce will have to investigate the cause.

**Comment by Remu-rin** [comment]
Browser Console shows this about uMatrix when reproducing:
> TypeError: matrixSnapshot.userSettings is undefined  popup.js:105:5

Nothing about uBO though.

**Comment by arana-krypteia** [comment]
Played around with it some more:

- I was able to reproduce the issue on my laptop, so it's not related to multi-monitors
- The bug (as reported) is not 100% reproducible, in that sometimes the dashboard link works despite the notification icon (seems to be more reproducible on a fresh browser launch with a blank home page)
- A more reproducible (related?) issue is that the element picker disappears when a notification popup is present (this seems to occur with 100% reproducibility)

**Comment by gorhill** [comment]
> A more reproducible (related?) issue is that the element picker disappears when a notification popup is present (this seems to occur with 100% reproducibility)

This suggests communication channel of auxiliary pages of uBO (popup panel, element picker) is being forcibly closed.

Does the issue also occur with the webext version of uBO 1.12.4?

**Comment by Remu-rin** [comment]
> Does the issue also occur with the webext version of uBO 1.12.4?

Nope. Tried on nightly, both webext uBO and uMatrix are not affected, while legacy versions still are.

**Comment by gorhill** [comment]
Obsolete issue. Reproducable by only one user, so if it still occurs, user will have to investigate the cause.
