### ISSUE TITLE
Support for "replace=" AdGuard filters

### ISSUE THREAD

**Issue by o983756** [gorhill/uBlock#2669]
Hello, can you please add support for "replace=" AdGuard filters? Here is example for music.yandex.ru:
https://filters.adtidy.org/extension/chromium/filters/1.txt

`||music.yandex.ru/api/$domain=music.yandex.ru|music.yandex.ua|music.yandex.by|music.yandex.kz,important,replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/`

`||radio.yandex.ru/api/$domain=radio.yandex.by|radio.yandex.kz|radio.yandex.ru|radio.yandex.ua,important,replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/`

`||awaps.yandex.ru/*.xml$domain=radio.yandex.by|radio.yandex.kz|radio.yandex.ru|radio.yandex.ua|music.yandex.ru|music.yandex.ua|music.yandex.by|music.yandex.kz,important,replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/`

It's replases xml/htm files with AD's links to emptiness, but is this will work with uBO?

**Comment by gorhill** [comment]
That filter option is only applicable to Adguard standalone blocker. Extensions can't intercept and modify the content of a response on the fly.
