### ISSUE TITLE
Exception filter not working?

### ISSUE THREAD

**Issue by hotdogman** [gorhill/uBlock#267]
I don't know if this is an actual issue, or if it's just me being too stupid to write a filter properly.
Tested with a clean browser profile, uBlock was the only installed extension, no customizations to about:config.

OS: Windows 8.1 Professional x64
Browser: Firefox 38.0.1
uBlock version: 0.9.8.2

1. Under the dashboard, enable "hpHosts’s Ad and tracking servers‎" and apply changes
2. Open the logger
3. Search for i-mobile
4. Navigate to http://zip.2chan.net/3/futaba.htm
5. Notice that there are blocked network requests due to the 	||spdeliver.i-mobile.co.jp^ filter
![atlmbk 1](https://cloud.githubusercontent.com/assets/4343306/7899880/1d56cadc-06fc-11e5-9229-63f8d32a6978.png)
6. Add @@i-mobile.co.jp under "My filters" and apply changes
7. Navigate to http://zip.2chan.net/3/futaba.htm
8. Notice that the previously blocked network requests (and then some) were allowed
![asomwx 1](https://cloud.githubusercontent.com/assets/4343306/7899889/87412af0-06fc-11e5-802c-ec8aca9acfe0.png)
9. Under my filters, change @@i-mobile.co.jp to @@i-mobile.co.jp$domain=2chan.net and apply changes
10. Notice that the network requests are once again blocked, despite the fact that the exception filter should've allowed them
![jwbcjl 1](https://cloud.githubusercontent.com/assets/4343306/7899907/63793c9c-06fd-11e5-97dd-ed80e7784da8.png)
11. Under the dashboard, check "I am an advanced user"
12. Under "My rules" add 2chan.net i-mobile.co.jp * allow and save your changes
13. Navigate to http://zip.2chan.net/3/futaba.htm
14. Notice that the requests were allowed
![ipbrol 1](https://cloud.githubusercontent.com/assets/4343306/7899921/30bab50a-06fe-11e5-9b2c-4aac59eef0b2.png)

If this is just an issue due to the filter being improperly written, I apologize for taking up your time.

**Comment by gorhill** [comment]
I don't understand the issue. You created a rule to allow `i-mobile.co.jp` while on `2chan.net`, and as per log, the requests to `i-mobile.co.jp` were allowed as expected while on `2chan.net`.

**Comment by hotdogman** [comment]
According to the logger:
@@i-mobile.co.jp - requests allowed to i-mobile.co.jp while on 2chan.net
2chan.net  i-mobile.co.jp * allow - requests allowed to i-mobile.co.jp while on 2chan.net
@@i-mobile.co.jp$domain=2chan.net - requests blocked to i-mobile.co.jp$ while on 2chan.net

**Comment by gorhill** [comment]
The blocked requests to `i-mobile.co.jp` where made in the context of `http://free2.jp/2chan_1/`, it's an `iframe`. ABP filters works differently from dynamic rules, the context is taken from the frame from which the requests are made.

**Comment by hotdogman** [comment]
I apologize then, sorry for the inconvenience.

**Comment by gorhill** [comment]
I have [plan to disclose the context in the logger](https://github.com/chrisaljoudi/uBlock/issues/651), but I am trying to find a way to do this without further cluttering the logger with too much info.
