### ISSUE TITLE
This link when opened fails to be blocked by uBlock.

### ISSUE THREAD

**Issue by XtremeAero426** [gorhill/uBlock#2673]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
uBlock does not successfully block this site and the site keeps giving you prompts to install an extension and also forces fullscreen. **Once you open the URL, the task manager has to be used if you want to close the URL.**

### One or more specific URLs where the issue occurs
csport247.stream/b.php?clickid=1496378761113517588792288907050514&n=w1&v=381921385
**WARNING SPAM URL**

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
I don't think it's a visual issue and I don't want to go to the site again. **Use extreme caution if you open the URL.**

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Open the URL. That's it. 

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
{
  "timeStamp": 1496379475682,
  "version": "1.12.4",
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "http://csport247.stream/b.php?clickid=1496378761113517588792288907050514&n=w1&v=381921385\nhttps://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "plowe-0",
    "malware-1",
    "malware-0",
    "easyprivacy",
    "easylist",
    "reek-0",
    "ublock-unbreak",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "user-filters",
    "http://csport247.stream/b.php?clickid=1496378761113517588792288907050514&n=w1&v=381921385"
  ],
  "hiddenSettingsString": "assetFetchTimeout 30\nautoUpdateAssetFetchPeriod 120\nautoUpdatePeriod 7\nignoreRedirectFilters false\nignoreScriptInjectFilters false\nmanualUpdateAssetFetchPeriod 2000\npopupFontSize unset\nsuspendTabsUntilReady false\nuserResourcesLocation unset",
  "netWhitelist": "192.168.1.1\n5pb.jp\nabout-scheme\nanonymizer.in\nawesome-table.com\nbeeimg.com\nbehind-the-scene\ncanadiansweets.com\nchrome-extension-scheme\nchrome-scheme\nclassroom.google.com\ndocs.google.com\ndocslide.us\ndtechcollegeprep.mymajors.com\ndtechdragon.wordpress.com\ngithub.com\ngraphiq-stories.graphiq.com\ninsider.razerzone.com\nlearnpianobyyourself.com\nlol.item-set.com\nloopconversation.about-scheme\nmail.google.com\nmusic.approachingnirvana.com\nnetpricecalculator.com\nnmd.hsb12.sna.wayport.net\nopera-scheme\npuzzleanddragons.us\nroyalwholesalecandy.com\nservices13.ieee.org\nspeed.cd\nstore.asus.com\nstudentscores.collegeboard.org\nwww.cappex.com\nwww.giftcardgranny.com\nwww.google.com\nwww.jpay.com\nwww.loadingartist.com\nwww.mathxlforschool.com\nwww.nytimes.com\nwww.reddit.com\nwww.tubechop.com\nwww.zeemee.com\nzetamag.atavist.com",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-strict-blocking: static.exoclick.com true\nno-strict-blocking: download.cnet.com true\nno-strict-blocking: dw.cbsi.com true",
  "userFilters": "",
  "filterLists": {
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "off": false
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "off": false
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "off": false
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "off": false
    },
    "https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "off": false
    },
    "assets/ublock/unbreak.txt": {
      "off": false
    },
    "assets/ublock/privacy.txt": {
      "off": false
    },
    "assets/ublock/badware.txt": {
      "off": false
    },
    "assets/ublock/filters.txt": {
      "off": false
    },
    "assets/user/filters.txt": {
      "off": false
    },
    "http://csport247.stream/b.php?clickid=1496378761113517588792288907050514&n=w1&v=381921385": {
      "off": false
    },
    "assets/ublock/experimental.txt": {
      "off": true
    }
  }
}

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
Windows 10 Pro

- Browser/version: 
Version 58.0.3029.110 (64-bit)

- uBlock Origin version: 
uBlock Origin v1.12.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by XtremeAero426** [comment]
Wait, is this a filter issue? I wasn't sure when I posted it. If so, please let me know and I will delete this right away. It's my first time encountering one of these issues and I'm not completely sure.

**Comment by gwarser** [comment]
Nothing happens - "File not found. "
