### ISSUE TITLE
request Steven Black's hosts multipurpose added

### ISSUE THREAD

**Issue by jawz101** [gorhill/uBlock#2675]
https://github.com/StevenBlack/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

It is a well-known and established list which essentially consolidates the following lists along with several others
Malware Domain List​​​​​​​​​
MVPS hosts file
Dan Pollock - someonewhocares.org

**Comment by bershan2** [comment]
@jawz101 If this hosts file is merely a collection of other hosts files (that are already included in uBO subscriptions), why would anyone want to use it? Probably, it is relevant for PC, where only one list is allowed, so it simplifies "copy and de-dup" process. However, uBO can de-dup filter lists automatically, so can load files from the original sources.
