### ISSUE TITLE
default rules question/suggestion?

### ISSUE THREAD

**Issue by jawz101** [gorhill/uBlock#2676]
Would there be any advantage, disadvantage, or nothing at all to default with any of these additional rules?
    * * * noop
    * * 1p-script noop
    * * image noop
    * * inline-script noop
    * * 3p noop

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by jawz101** [comment]
Ok... How does someone ask questions if it's not an issue??  Sheesh

**Comment by mapx-** [comment]
here:
https://discourse.mozilla-community.org/t/support-ublock-origin/6746

**Comment by jawz101** [comment]
Well, I said it once, though I do appreciate the answer.  I'm not likely going to hop around creating accounts everywhere to ask the same question twice.  Maybe that's just me.  No offense.

Thanks again.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#first-solution
