### ISSUE TITLE
Blocking right-click menus...?

### ISSUE THREAD

**Issue by Gyraxis** [gorhill/uBlock#2677]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Right click menus are being blocked., showing only black box with uBlock logo. happens on all sites. Firefox 53.0.3

### One or more specific URLs where the issue occurs

Happens to all URL's. Example: google.com

### Screenshot in which the issue can be seen

http://imgur.com/a/JjQYd

### Steps for anyone to reproduce the issue

1. Right click anywhere while browser open.
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 Pro v. 1607
- Browser/version: Firefox 53.0.3 32-bit
- uBlock Origin version: 1.12.4
##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Gyraxis** [comment]
Apologies, fixed itself somehow...?

**Comment by gorhill** [comment]
Next time open an issue with Firefox, uBO is not responsible to render the contextual popup menu.
