### ISSUE TITLE
Default Filenames When Doing a Backup or Export of any uBlock Settings

### ISSUE THREAD

**Issue by puff-m-d** [gorhill/uBlock#2680]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When doing a backup or export of any of the settings, there is no longer any uBlock generated file name. whatever you try to backup or export always defaults to a name of "download.txt" where it used to always be a name like "my-ublock-backup_2017-05-10_19.06.01.txt".
I do not believe this is because of something that broke within uBlock but think it is a change within Chromium as the same issue is happening with uMatrix. I would also report this under uMatrix issues but the issue tracker there is closed.

### One or more specific URLs where the issue occurs
No URL since this is occurring when doing a backup or export of uBlock settings or list.
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![2017 06 04_15h42m08s_001_00003](https://cloud.githubusercontent.com/assets/8797546/26764841/d43c8ff0-493c-11e7-96bd-18e33efb31fe.jpg)
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Just go into uBlock settings and try to backup or export any of the settings.
1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Advanced user.
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 Pro 64 bit Version 1703 (OS Build 15063.332).
- Browser/version: Chromium Version 61.0.3120.0 (Official Build) (64-bit) but it started on late Chromium 60 builds in mid May.
- uBlock Origin version: 1.12.5.100 but started during the 1.12.5 beta builds sometime in mid May.

##### Your filter lists
Default.
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none.

**Comment by bershan2** [comment]
Works fine for me on *uBO 1.13.2* on both *Google Chrome 59* and on *Chromium 61*.
@puff-m-d Could you check it again, please?

#### Details:
OS: Windows 10 Home 64-bit Version 1607, OS Build 14393.1358
Browser 1: Google Chrome Version 59.0.3071.109 (Official Build) (64-bit)
Browser 2: Chromium Version 61.0.3138.0 (Developer Build) (64-bit)
uBlock Origin 1.13.2

When I export my list, it proposes name `ublock-custom-filters_2017-06-21_15.51.28.txt`. I tried both "ask where to download" and "download automatically" cases (for both -- 4 combinations in total).

**Comment by puff-m-d** [comment]
Hello,

I had not tested this again since Chromium 61.0.3126.0 in which the issue still persisted.
I am currently on Chromium 61.0.3133.0 and after testing with this browser version, the issue is gone and all is working as expected.
I guess this must be attributed to a bug in Chromium since it now works and gorhill has not changed anything in this regard to uBlock or uMatrix.
