### ISSUE TITLE
Add keyboard navigation to element picker

### ISSUE THREAD

**Issue by alexolog** [gorhill/uBlock#2681]
When selecting an element to block, it is often hard (or even impossible) to position the mouse correctly.  Sometimes elements are not visible, other times they are bunched too close together, etc.

It will be helpful to have the following features:
1) Support for navigating the DOM hierarchy using keyboard commands, and
2) Support for selecting an element to hide fro the Firefox Element Inspector.

Both options are available on ABP with the "Element Hiding Helper" extension (https://adblockplus.org/elemhidehelper).  Adding them to uBO will be much appreciated!

**Comment by gorhill** [comment]
> it is often hard (or even impossible) to position the mouse correctly. Sometimes elements are not visible, other times they are bunched too close together, etc.

Provide an example please.

**Comment by gwarser** [comment]
Picker can be linked with UBO DOM viewer. Similar to dev inspector feature 'Pick element from the page'.
