### ISSUE TITLE
hpHosts’ Ad and tracking servers​​​​​ is not updating with this build in FF with uBo 1.12.5rc0

### ISSUE THREAD

**Issue by shellye5** [gorhill/uBlock#2682]
https://hphosts.blogspot.in/2017/06/hphosts-updated-june-3rd-2017.html

hpHosts’ Ad and tracking servers​​​​​ is not updating with this build in FF
maybe https version of the site is down?
uBo should add a fall back to http if https fails for all filters/subscriptions?

http://hosts-file.net/download/hosts.txt

http://www.hosts-file.net/

http://hosts-file.net/?s=Download

all are opening

@gorhill can you please look into this

**Comment by gwarser** [comment]
On my side https not loads, and when I try to open HOST file in browser I get "The connection was reset" error.

Even wget reports problems:

```
pc:~ > wget -c http://www.hosts-file.net/download/hosts.txt
--2017-06-05 10:50:50--  http://www.hosts-file.net/download/hosts.txt
Resolving www.hosts-file.net (www.hosts-file.net)... 107.22.171.143
Connecting to www.hosts-file.net (www.hosts-file.net)|107.22.171.143|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23045128 (22M) [text/plain]
Saving to: ‘hosts.txt’

64% [=================================================================>                                    ] 14.968.515  67,7KB/s   in 2m 27s 

2017-06-05 10:53:19 (99,7 KB/s) - Read error at byte 14968515/23045128 (Connection reset by peer). Retrying.

--2017-06-05 10:53:20--  (try: 2)  http://www.hosts-file.net/download/hosts.txt
Connecting to www.hosts-file.net (www.hosts-file.net)|107.22.171.143|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

```

**Comment by gorhill** [comment]
The link is `https://hosts-file.net/.%5Cad_servers.txt` (not `hosts.txt`).

The `http:` version works fine from the browser.

**Comment by gorhill** [comment]
I confirm falling back to the `http` version works.

**Comment by shellye5** [comment]
hpHosts’ Ad and tracking servers

Still not updating on 1.12.5rc1
shows network error

**Comment by okiehsch** [comment]
`http://www.hosts-file.net` is down.
![hosts](https://cloud.githubusercontent.com/assets/16838044/26812075/ea70664a-4a75-11e7-8c47-87c2024778a0.PNG)

**Comment by shellye5** [comment]
Oh did not know that , does the fix also allows other filters to fallback from https to http if https is down?
It's very useful

**Comment by gorhill** [comment]
> Webextension builds are missing?

Missing where?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues/2684
