### ISSUE TITLE
CANNOT Update Custom filter

### ISSUE THREAD

**Issue by BurningRaptor** [gorhill/uBlock#2687]
On version 1.12.4, I can't update this custom filter:
> https://raw.githubusercontent.com/523860169/list/master/ad4.txt
![firefox_2017-06-07_09-44-30](https://user-images.githubusercontent.com/10308169/26858908-ceff29c2-4b66-11e7-87e3-cc793290d049.png)

But on 1.10.4 I can update it, and I can access that URL, so I guess it is not an network issue. Intergrated filters like EasyList can be updated on both versions.

- OS/version: Windows 10 14393
- Browser/version: Firefox 52.0.2 64-bit
- uBlock Origin version: 1.12.4

**Comment by gorhill** [comment]
Did you look at the logger output like it's asked from you in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)?

**Comment by BurningRaptor** [comment]
![default](https://user-images.githubusercontent.com/10308169/26879572-259b9d62-4bc4-11e7-8035-59fa4a59428b.png)
This is what I've got after cleaning the cache and press the update button. The Chinese characters simply mean "Network Error".
![63 _cr](https://user-images.githubusercontent.com/10308169/26880004-9c9d3578-4bc5-11e7-8961-dc507290a590.png)


It seems that EasyList blocks it. :(

**Comment by gorhill** [comment]
> It seems that EasyList blocks it. :(

Because you allowed behind-the-scene requests to be blocked _despite all the warnings_ about doing so:
- <https://github.com/gorhill/uBlock/wiki/Advanced-user-features>.
- <https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist#important-read-carefully>.

**Comment by BurningRaptor** [comment]
Thank you for telling me so.
