### ISSUE TITLE
uBlock for Safari causes Angular app not loading

### ISSUE THREAD

**Issue by SteveLTN** [gorhill/uBlock#2689]
We have an app built in Angular.js. 

When using uBlock for Safari, and subscribe to "EasyPrivacy", or when adding a custom filter 

```||segment.io^$third-party```

, the Angular app wouldn't load.

We made sure the Angular app itself would work without Segment. By: 
1. Using the same lists in uBlock on Chrome. The app still works
2. Using another ad blocker for Safari, subscribing to the same list. The app still works
3. Blocking the domain `segment.io` in our DNS. The app still works

It turned out, our Angular app would work even if `segment.io` is not accessible, except the case of being blocked by uBlock for Safari. This doesn't look alike a filter issue, but rather a bug of uBlock itself.

A test URL is https://sqore.com/organization/sqore. When Angular doesn't load, you see placeholders wrapped in `{{ }}`. Tested on *Safari 10.1* on *macOS 10.12.5*, with *uBlock for Safari 0.9.5.2*.

**Comment by Snapy** [comment]
@SteveLTN You are using a very old version of uBlock (and it's not uBlock Origin) and issues for the Safari version need to be opened on the [specfic repo](https://github.com/el1t/uBlock-Safari#ublock-originfor-safari).
So I strongly advise that you install the official Safari version from the above repo and if you still encounter issues that you open them in their respective repo (whether it is a filter list issue or a uBO issue).

**Comment by anewuser** [comment]
[I had already told him](https://github.com/chrisaljoudi/uBlock/issues/1685#issuecomment-306012044) that he's using an abandoned project and pointed him to the proper repository.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by SteveLTN** [comment]
My apology. I somehow ended up not clicking @anewuser 's link, but searched for a "GitHub uBlock Origin" on Google.
