### ISSUE TITLE
Unblockable Ads on Drudge

### ISSUE THREAD

**Issue by RAcceleration** [gorhill/uBlock#2691]
### Describe the issue

[Most ads are still blocked but some are getting through even after manually blocking elements. Some on Reddit have also noticed: https://www.reddit.com/r/uBlockOrigin/comments/6fvuo0/ads_leaking_through_on_drudge_report/]

### One or more specific URLs where the issue occurs

[http://drudgereport.com/]

### Screenshot in which the issue can be seen

[https://i.gyazo.com/feddb0e17e758e9cc0269f251f6ac336.png]

### Steps for anyone to reproduce the issue

1. visit http://drudgereport.com/
2. see ad
3. block element
4. create filter
5. refresh page

### Your settings

- OS/version: macOS 10.12.5
- Browser/version: Firefox 53.0.3
- uBlock Origin version: v1.12.4

##### Your filter lists

[All Default filter lists minus Regional lists]

##### Your custom filters (if any)

[! 6/7/2017, 7:33:34 PM http://drudgereport.com/
drudgereport.com###sVKAlHux

! 6/7/2017, 7:33:45 PM http://drudgereport.com/
drudgereport.com###bFwkqHip

! 6/7/2017, 7:33:58 PM http://drudgereport.com/
drudgereport.com###ocKQGXNt

! 6/7/2017, 7:34:11 PM http://drudgereport.com/
drudgereport.com###NQAEzSEd

! 6/7/2017, 7:35:05 PM http://drudgereport.com/
drudgereport.com###Kmemvqhx

! 6/8/2017, 8:38:55 AM http://drudgereport.com/
drudgereport.com###hAwMeMTx

! 6/8/2017, 8:39:01 AM http://drudgereport.com/
drudgereport.com###lwIvaiaY

! 6/8/2017, 8:39:04 AM http://drudgereport.com/
drudgereport.com###nzbnMniP

! 6/8/2017, 8:39:08 AM http://drudgereport.com/
drudgereport.com###NtutMCiN]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
