### ISSUE TITLE
Special Facebook blocking needed. Wildcard not working

### ISSUE THREAD

**Issue by Tomtechbit** [gorhill/uBlock#2692]
My ward has special needs and loves Facebook but is unable to read. He tends to push symbols and has been known to cause problems for others. He has accidentally reported posts which should not be reported, liked and shared content without knowing what he is doing. he once shared an unflattering picture of his best girl which led to her blocking him completely.

https://www.facebook.com/

![chris facebook](https://user-images.githubusercontent.com/5789322/26958869-036979b2-4c9b-11e7-897f-b79d7f7f35b7.jpg)
That shows his standard Facebook Page. 

I have removed both the left and right sidebars and the blue bar at the top using Adblock Plus and will add those filters to uBlock once I have found a way to remove the comments section and the "hideToggle" button which appears on each post.

Since Chris loves to push buttons I have tried for hours to remove the "hideToggle" (the down arrow to the right at the beginning of each post), the"like" buttons, and the comments section but between the method Facebook uses and my failure to get the wildcards to work as part of a "My Filter" I only succeed in blocking the single items instead of all of the items on all pages.

##### Your filter lists

`www.facebook.com###u_0_1b

www.facebook.com###u_0_1m

www.facebook.com###u_0_1

www.facebook.com###u_0_1a > ._5pcr.fbUserContent > div:nth-of-type(2)

www.facebook.com###u_jsonp_3_19 > ._5pcr.fbUserContent > div:nth-of-type(2)

As you can see there are a lot of similarities in the code for those items but when I try to add wildcards the filter becomes completely non functional.

I believe the filters should work on all Facebook posts if the wildcards were working properly.

www.facebook.com###u_0_*

www.facebook.com###fbUserContent > div:nth-of-type(2)

www.facebook.com###div:nth-of-type(2)

Thank you for helping a severely handicapped individual use Facebook without causing issues for those in his life.

Setting below.
{
  "timeStamp": 1496976767126,
  "version": "1.12.4",
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": true,
    "externalLists": [],
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "user-filters",
    "assets.json",
    "public_suffix_list.dat",
    "ublock-resources",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "malware-0",
    "malware-1",
    "plowe-0"
  ],
  "hiddenSettingsString": "assetFetchTimeout 30\nautoUpdateAssetFetchPeriod 120\nautoUpdatePeriod 7\nignoreRedirectFilters false\nignoreScriptInjectFilters false\nmanualUpdateAssetFetchPeriod 2000\npopupFontSize unset\nsuspendTabsUntilReady false\nuserResourcesLocation unset",
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nmoz-extension-scheme\nopera-scheme\nvivaldi-scheme",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": "www.facebook.com###u_0_1b\n\nwww.facebook.com###u_0_1a > ._5pcr.fbUserContent > div:nth-of-type(2)\n\nwww.facebook.com###u_0_1m\n\nwww.facebook.com###u_0_1t\n\n! 6/8/2017, 10:49:10 PM https://www.facebook.com/thomas.davis.7583\nwww.facebook.com###u_jsonp_3_19 > ._5pcr.fbUserContent > div:nth-of-type(2)\n",
  "filterLists": {
    "assets/user/filters.txt": {
      "off": false
    },
    "assets.json": {
      "off": false
    },
    "assets/thirdparties/publicsuffix.org/list/effective_tld_names.dat": {
      "off": false
    },
    "assets/ublock/resources.txt": {
      "off": false
    },
    "assets/ublock/filters.txt": {
      "off": false
    },
    "assets/ublock/badware.txt": {
      "off": false
    },
    "assets/ublock/privacy.txt": {
      "off": false
    },
    "assets/ublock/unbreak.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "off": false
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "off": false
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "off": false
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "off": false
    },
    "assets/ublock/experimental.txt": {
      "off": true
    }
  }
}

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

Windows 10 
Mozilla Firefox
uBlock Origin v1.12.4

**Comment by lassekongo83** [comment]
This is a not an issue with uBO and should not be reported here. 

You can't use CSS wildcards in the open like this `###u_0_*`. You'll need to use [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors). For example `[id^="u_0_"]` where ^ means starts with etc. Also look into [procedural cosmetic filters](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters) which may be handy on facebook.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by anewuser** [comment]
@Tomtechbit or @gorhill  you should delete that screenshot. It reveals their list of friends and includes a post that apparently isn't public.
