### ISSUE TITLE
Spotify stops playing music when an audio ad is loaded

### ISSUE THREAD

**Issue by Paviluf** [gorhill/uBlock#2693]
### Describe the issue
When you listen music on https://open.spotify.com/ after a while an audio ad is loaded and the music stops but the ads is not actually played by Spotify. It's just freezed and you have to refresh the page or manually change song to play audio again.

### One or more specific URLs where the issue occurs
https://open.spotify.com/

### Screenshot in which the issue can be seen
https://i.imgur.com/3AzMrGb.png

### Steps for anyone to reproduce the issue
Play music and wait for an ad to play

### Your settings
- OS/version: Fedora 25
- Browser/version: Firefox 53
- uBlock Origin version: 1.12.4

Happen to "many" people with different settings:
https://www.reddit.com/r/uBlockOrigin/comments/6ev5uf/spotify_stops_playing_music_when_an_audio_ad_is/

##### Your filter lists
Default filter lists + FRA

Thanks !

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Paviluf** [comment]
Hello @gorhill,

Can you say me why you have closed it as invalid because I re-checked and I don't see what's wrong.

Thank you.

**Comment by mapx-** [comment]
You have to report the filter issues here:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by Paviluf** [comment]
Thank you ! I didn't get that.
