### ISSUE TITLE
uBlock seems to hide the ad instead of blocking

### ISSUE THREAD

**Issue by dxerw** [gorhill/uBlock#2694]
I've been using uBlock for a long time now but I've noticed on various websites the ads flash for a second (I can see the banner) and then vanish. I thought they are blocked so that shouldn't happen. I've tried both latest chromium and firefox with latest uBlock on Windows 7 and they both have the same issue. Filter list is the default. 

Any ideas/suggestions?

Thanks!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Also: <https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F>.
