### ISSUE TITLE
Menu has too much space on the top and bottom

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2696]
Icon menu has extra space on the top and bottom as seen where I place arrows on the screenshot.  Mozilla fixed the menu being too wide but evidently didn't fix this problem.  I thought I saw a patch that addressed this on Bugzilla but I could be wrong or it didn't work.

Running latest Fx55 Nightly.  Running uBlock Origin v1.12.5rc2.  Windows 10 64 bit CU with all cumulative updates.

Filter lists not applicable in this case.

![untitled](https://user-images.githubusercontent.com/410799/27005473-65b8d22c-4ded-11e7-9f8a-e3fd9e80e4ed.png)

**Comment by streetwolf** [comment]
The extra space is produced when you turn on Photon mode via 'browser.photon.structure.enabled = true' in prefs.js.  Normal mode it looks OK.  Photon will be upon us soon so It might be proactive to get this fixed soon.

**Comment by gorhill** [comment]
Shouldn't this be filed in Firefox issue tracker?

uBO embed its frame into the Firefox's-provided panel, and it has a `padding` style causing the issue (line 339 in `panelUI.css`):

    /* START photonpanelview adjustments */
    
    #appMenu-popup > .panel-arrowcontainer > .panel-arrowcontent {
      padding: 0;
      border-radius: 0;
    }
    
    photonpanelmultiview panelview {
      background: var(--arrowpanel-background);
      padding: 6px 0;
    }

When commenting out the `padding` style above, it renders fine. The `padding` style above is in addition to the `padding` style seen in one of the ancestor (line 328 in `panelUI.css`):

    .cui-widget-panel > .panel-arrowcontainer > .panel-arrowcontent {
      padding: 4px 0;
    }

Meaning the resulting padding is 10 pixels. I doubt this was meant to be this much. One of the two styles probably needs to be revised.

**Comment by streetwolf** [comment]
Ray…

Are you saying a bug report should be opened on this issue in Bugzilla?  I can do it but I thought that as the author of uBO it would make more sense for you to open up a bug report as you know what the problem is.

Also, I see you took the link to the WE version away.  No doubt from the recent changes Mozilla made.  Are you re-writing uBO for WE or waiting until WE becomes more stable?

____
Gary

**Comment by gorhill** [comment]
> Are you re-writing uBO for WE or waiting until WE becomes more stable?

See <https://github.com/gorhill/uBlock/issues/2684#issuecomment-306498435>. uBO does not need to be re-written, the Chromium version **is** the webext version, with very minor changes.

**Comment by gorhill** [comment]
Looking a bit more into this, I could set the `padding` myself, but that seems a odd thing to do for uBO, as it would force uBO to make assumption about and deal with stuff which are not its responsibility. It's unclear to me what was the intended behavior here by whoever is working on Photon.

**Comment by gorhill** [comment]
I just force the style in uBO, faster for me to change the chrome style than to report an issue on bugzilla. Tested with Pale Moon, Sea Monkey, Firefox 53, Nightly with and without Photon, with legacy and webext.

This means that legacy without Photon won't have padding anymore at the top and bottom like it used to be.
