### ISSUE TITLE
Add column headers to the dynamic filtering pane

### ISSUE THREAD

**Issue by light** [gorhill/uBlock#2697]
It would be helpful to add headers to the dynamic filtering pane table. I don't use that pane very often so I can never remember which column is the *global* one and which is the *local* one. Maybe also a link to the Dynamic-filtering wiki page somewhere would make it easier to use this pane.

**Comment by Remu-rin** [comment]
@light Apparently uBO shows text when you hover upper cells, so you can do it to remember.
![-1](https://user-images.githubusercontent.com/28995228/27007402-ac4d46b8-4e6b-11e7-8617-4621e6117396.png)

**Comment by light** [comment]
@Remu-rin thanks for the tip, I hadn't noticed that before.

@gorhill did you reject this issue because of a specific reason or because of lack of time and would you accept a PR implementing this ?

**Comment by gorhill** [comment]
Duplicate of #840.
