### ISSUE TITLE
[Feature request] Keyboard navigation in DOM (parent/child) for Element Picker

### ISSUE THREAD

**Issue by alphestdev** [gorhill/uBlock#2698]
In most cases I want to select one of the invisible parents, so that the rule would apply for more than just one session.

Similar to wider/narrower in "Element Hiding Helper for Adblock Plus" firefox addon.

**Comment by gorhill** [comment]
If they are parents, then they are listed in the list of suggested filters in the element picker.

**Comment by gorhill** [comment]
Read [the doc](https://github.com/gorhill/uBlock/wiki/Element-picker) please before opening issues:

> The top most cosmetic filter is the most specific which could be derived from the element you clicked. The bottom-most is the broadest, the least specific. Pick the one which matches best what you wish to accomplish.

**Comment by alphestdev** [comment]
Well that's a finger. (Yes, I've read your docs googled before posting, thank you.) 

So I guess there will be no Keyboard navigation for me then.

**Comment by gorhill** [comment]
> I've read your docs googled before posting, thank you.

You said:

> I want to select one of the invisible parents

If you read the doc, I come you still asked for something that's already available in the list of proposed filters? If they are listed, they are not invisible anymore.
