### ISSUE TITLE
Blocking sumome Share links

### ISSUE THREAD

**Issue by kamishiro** [gorhill/uBlock#270]
Here is an odd problem - I use this great extension (in both Firefox/Chrome) and it "does what it says on the tin" quite effectively. I also design/manage a number of Wordpress sites that have started using
the SumoMe.com plugin to display social "share bars" and, on some sites, an email list "subscription prompter". Normally, it does not block such things and on the developer's site (sumome.com)  everything works just fine; I see the Share bar on the left, I get the list box popover...but if I go to ANY other site like http://ShaneShow.com (not one of mine) the SHARE bar is blocked unless I disable the extension. The List Box (or other variations) seems to work (though the "smart bar" option seems to get blocked - for example on http://bayouwoman.com or http://theavenuepub.com) ).
This shows in the log (twice):
09:14:29		||sumome.com^	--	script	http://load.sumome.com/
(apparently it also blocks Google Analytics? A similar entry shows for that)

I've tried to create a whitelist entry, but could not find a method that worked, so have simply been disabling it on these sites - however, as I recommend your extension to so many people, I'd like to be sure they can see these social links on my sites (and others)!

Any ideas would be most helpful.

**Comment by EchoDev** [comment]
I'm pretty sure these kind of issues should not be reported here but for an answer:

uBlock is used to block ads and protect the privacy of users. The sumome seems to be a user tracker and is probably in 1 of the subscriptions list. uBlock does not maintain these lists, if you want to get removed from the list you will have to contact the maintainers (Their contact info should be in the lists themselves).

If you want to whitelist a site manually you can go into the options menu of uBlock and go to the tab whitelist and enter the name of the site or you can go to my filters and add @@||load.sumome.com^

**Comment by gorhill** [comment]
EasyPrivacy: `||sumome.com^$third-party`. If you think it should not be in EasyPrivacy, report to [EasyPrivacy maintainers](https://forums.lanik.us/viewforum.php?f=64).

**Comment by kamishiro** [comment]
Thanks Raymond, most appreciated!
