### ISSUE TITLE
how to counter this website with ub? need guide

### ISSUE THREAD

**Issue by blob2015** [gorhill/uBlock#2700]
for example, enter this website:
**http://www.cnprint.org/bbs/thread/71/276053/**
then the big warning, covering the whole window, will come soon, to persuade you stop the anti-ad tool, including ub.
have tried blocking some scripts by hand, besides, _**cnprint.org##script:contains(論壇需要發展),**_ _**cnprint.org##script:contains(Bitte aktiviere)**_, i also have tried, but the obstacle remains.

---------------

my system info:
FF 52 ESR
ubo 1.12.4. most rules from third party have been selected, including anti-adblock killer

---------------

how to write rule(s) with filter(s) in this situation?

thanks 🍻

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
