### ISSUE TITLE
Accents not showing properly on certain websites

### ISSUE THREAD

**Issue by TenMinutesToDowntown** [gorhill/uBlock#2702]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Kind of weird thing, but on a message board I visit that is in both English and French letters with accents on them don't display properly when uBlock is enabled. I'd whitelist the site, but it has annoying ads that I'd rather not see.

Any idea what could be causing this? How to fix it?

### One or more specific URLs where the issue occurs
It's happening here: http://hfboards.hockeysfuture.com/showthread.php?p=133306049

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
When uBlock is enabled the font looks like this: http://i.imgur.com/XXdJ90h.jpg
WHen it's disabled, it looks like this: http://i.imgur.com/7Uj7R14.jpg

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

Using Version 59.0.3071.86 (Official Build) (64-bit) on Windows 10.
uBlock Origin v1.12.4

##### Your filter lists
hfboards.hockeysfuture.com##TD[width="300"]
hfboards.hockeysfuture.com##DIV[class="threads-latest"]
hfboards.hockeysfuture.com##TD[id="Threads_module_meader"]
hfboards.hockeysfuture.com##DIV[id="rssincl-box-910966"]

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Unable to reproduce.

Frankly, that doesn't make much sense to me that uBO would cause such issue. You will have to figure what else on your side is causing this.

**Comment by TenMinutesToDowntown** [comment]
It seems like it may be an issue with the site itself. Other posters commented on it happening too. I guess I'll see what happens within the next few days.

**Comment by okiehsch** [comment]
This site uses Instart Logic, that is the issue, add
`||hockeysfuture.com^$inline-script,domain=hfboards.hockeysfuture.com`
and the accents will show properly.

**Comment by gorhill** [comment]
Ok, I was testing with Chrome 61, I can reproduce testing with Chrome 58. This is typical of Instart Logic of messing only with current stable release of Chrome. And since they leave Firefox alone, the issue is also not reproducible on Firefox.

**Comment by TenMinutesToDowntown** [comment]
Where do I add that? Sorry, I'm not very familiar with messing with these things. I only know about whitelisting and filters.

**Comment by okiehsch** [comment]
Open the dashboard, select `My filters` and copy and paste
`||hockeysfuture.com^$inline-script,domain=hfboards.hockeysfuture.com`

**Comment by TenMinutesToDowntown** [comment]
Awesome! It's working thanks. :)

**Comment by TenMinutesToDowntown** [comment]
Wait, when doing that I can't click on the little icons to add the code for images or whatever in a post. These:

http://i.imgur.com/8WvXzwV.jpg

They become unclickable. Sigh.

**Comment by gorhill** [comment]
The site is using Instart Logic ("IL") tech to work around blocker. It probably can be fixed if one is willing to use uBO-Extra, but frankly I think the best is if you browse this site with Firefox -- IL refrain from contaminating pages when it detects Firefox.

**Comment by TenMinutesToDowntown** [comment]
I have no problem using another extension if necessary. Would you know what I'd have to do with uBO-Extra? I just had a look at it, and not quite understanding how it works. If it's too much trouble, don't worry about it. I can just whitelist certain threads that people will be typing in French in. NOt a huge issue, but a minor inconvenience.

**Comment by gorhill** [comment]
Could you try to install manually uBO-Extra 2.24 <https://github.com/gorhill/uBO-Extra/releases/tag/2.24> and see if the site works fine overall (registration is [known to be broken however](https://github.com/gorhill/uBO-Extra/pull/48#issue-235726937)).

**Comment by TenMinutesToDowntown** [comment]
Accents work, but not able to post anything when logged in. heh.

**Comment by gorhill** [comment]
Ok, the IL defuser works on my side with uBO-Extra 2.24.

However, the accent problem is for the site to fix. The site chose to install IL's crap, and a side effect of this is to break proper rendering of text: their problem to fix. At least with uBO-Extra 2.24, the site won't be able to bypass uBO.
