### ISSUE TITLE
Clients of Lucky Orange cannot login if they have uBlock installed

### ISSUE THREAD

**Issue by dannywajcman** [gorhill/uBlock#2705]
hello, I am a cofounder of Lucky Orange (www.luckyorange.com). Our clients have been complaining that they are unable to log into our dashboard if they also have you chrome web extension enabled. I was hoping you could somehow whitelabel our domain. happy to jump on a call to discuss more.

danny@luckyorange.com
913-209-2758.

thank you for your consideration. 
danny

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Filter issues must be reported at <https://github.com/uBlockOrigin/uAssets>, as clearly spelled out in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). Furthermore, such issues must come with repro all relevant details and exact repro steps.

**Comment by dannywajcman** [comment]
im sorry for placing this in the wrong area. can you please point me to where or whom to contact to address my issue above?
thanks,
danny

**Comment by gorhill** [comment]
The issue can be in any one of the default filter lists, or one of extra filter lists a user may have enabled. Bottom line: repro steps, detailed settings, logger to find out what is blocked which interfere, etc. uAssets repo is there to deal with these filter issues, uBO itself is not the issue.
