### ISSUE TITLE
In Pale Moon, Firefox, etc., cannot use Menu Wizard to move context menu item

### ISSUE THREAD

**Issue by VLM-TechEd** [gorhill/uBlock#2707]
Pale Moon 27.3, Win 7, uBO 1.12.4

I like to rearrange all my menus, and the tool of choice is the Menu Wizard extension (https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/). But when I attempt to move the uBO menu item within, say, the main context menu, I get the message

"It seems that this is a dynamic menu. Menu Wizard not designed to work with dynamic content."

Now, at first blush this is a Menu Wizard limitation independent of uBO. But I wonder why a dynamic menu item is required and thought I'd ask. Is that necessary to the operation of uBO in Windows?

Thank you!

**Comment by bershan2** [comment]
@VLM-TechEd Unfortunately it is required for the proper work of the menu: the item is created in `uBlock/platform/chromium/vapi-background.js` in `vAPI.contextMenu` upon the appearance of the menu:
```
       chrome.contextMenus.create(JSON.parse(JSON.stringify(entry)), function() {
```
Unfortunately, (at least in the current implementation) the menu has to be dynamic to be able to pick up the element it was created on.

**Comment by VLM-TechEd** [comment]
Thanks for explaining. I see no need to change it, and I see that you've concluded the same. I appreciate your time, which I know is precious.
