### ISSUE TITLE
Cannot see zapper tool

### ISSUE THREAD

**Issue by VLM-TechEd** [gorhill/uBlock#2708]
Greetings! I am running uBO 1.12.4 in Pale Moon 27.3, Win 7.

On this page https://github.com/gorhill/uBlock/wiki/Element-zapper, I read about the element zapper, which sounds very useful. But when I look inside the uBO toolbar box, I see the words "on this page" where the zapper is said to be. I'm new to uBO. Have a messed up a setting that I have not yet read about?

**Comment by mapx-** [comment]
You have to use at least 1.12.5rc3 (dev build)
https://github.com/gorhill/uBlock/releases

**Comment by VLM-TechEd** [comment]
Great, thank you.

 

And … thank you for making the shortcuts configurable in the Firefox family!!!!!

 

BTW, Pale Moon is retaining the entire, existing Firefox extension framework. I’m sure you know that, of course. We have a LOT of grateful uBlock Origin users. J

 

Elchanan, Vibrant Living Ministries
