### ISSUE TITLE
No automatic update of checking blocking ads lists

### ISSUE THREAD

**Issue by alain1965** [gorhill/uBlock#271]
Hello, first of all, sorry for my bad english it's not my native language. I'm on FF 38.0.1 and I use ublock origin 0.9.8.2, today none list of checking blocking ads were updated, I must do it manually. Lits checking are (plus defaut lists), easy privacy, easylist liste FR and fanboy's social blocking list

**Comment by gorhill** [comment]
> today none list of checking blocking ads were updated

How did you come to this conclusion?

**Comment by alain1965** [comment]
Simply, I gone in addons in FF and ublock origin to uncheck "disconnect" (it bocked some pictures) and I red "listes erronées" so I updated manually and it's ok.

**Comment by gorhill** [comment]
I don't understand. "Listes erronées" in the `about:addons` page? That's not from uBlock.

**Comment by alain1965** [comment]
Yes it was in "about:addons page and "listes erronées" its, in french, "lists no updating", it was right close "update now" at the top of the lists page in ublock origin and on the same line of each checking lists.

**Comment by alain1965** [comment]
And now it's the list "malware domains" who is impossible to update !


    Mettre à jour les listes de filtres sélectionnées automatiquement  

Utiliser en plus les règles esthétiques

    58 467 filtre(s) réseau et 45 185 filtre(s) esthétique(s) sont actuellement en vigueur :

        Mes filtres‎ : 12 utilisé(s) sur un total de 12
        uBlock filters‎ : 67 utilisé(s) sur un total de 67
        uBlock filters – Privacy‎ : 2 utilisé(s) sur un total de 3
        uBlock filters – Unbreak‎ : 59 utilisé(s) sur un total de 60 
    Publicités (2)
        Adblock Warning Removal List‎ : 0 utilisé(s) sur un total de ?
        Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com): 0 utilisé(s) sur un total de ?
        EasyList‎ (adblockplus.org): 57 582 utilisé(s) sur un total de 57 645Vider le cache
        EasyList without element hiding rules‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        Peter Lowe’s Ad server list‎ (yoyo.org): 2 422 utilisé(s) sur un total de 2 422httpVider le cache 
    Confidentialité (1)
        Basic tracking list by Disconnect‎ : 0 utilisé(s) sur un total de 28
        EasyPrivacy‎ (adblockplus.org): 10 483 utilisé(s) sur un total de 10 529Vider le cache
        Fanboy’s Enhanced Tracking List‎ (fanboy.co.nz): 0 utilisé(s) sur un total de ? 
    Domaines malveillants (1)
        Malvertising filter list by Disconnect‎ : 0 utilisé(s) sur un total de 14 883
        Malware Domain List‎ (malwaredomainlist.com): 0 utilisé(s) sur un total de 1 423httpVider le cache
        Malware domains‎ : 14 843 utilisé(s) sur un total de 14 848Potentiellement obsolète
        Malware domains (long-lived)‎ : 0 utilisé(s) sur un total de 3 208
        Malware filter list by Disconnect‎ : 0 utilisé(s) sur un total de ?
        Spam404‎ (spam404bl.com): 0 utilisé(s) sur un total de ? 
    Réseaux sociaux (1)
        Anti-ThirdpartySocial (see warning inside list)‎ (fanboy.co.nz): 0 utilisé(s) sur un total de ?
        Fanboy’s Annoyance List‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        Fanboy’s Social Blocking List‎ (adblockplus.org): 12 455 utilisé(s) sur un total de 12 455Vider le cache 
    Tout usage
        Dan Pollock’s hosts file‎ (someonewhocares.org): 0 utilisé(s) sur un total de ?http
        Fanboy+Easylist-Merged Ultimate List‎ (fanboy.co.nz): 0 utilisé(s) sur un total de ?
        hpHosts’s Ad and tracking servers‎ (hosts-file.net): 0 utilisé(s) sur un total de ?http
        MVPS HOSTS‎ (mvps.org): 0 utilisé(s) sur un total de ?http 
    Régions, langages (1)
        ara: Liste AR‎ (liste-ar-adblock.googlecode.com): 0 utilisé(s) sur un total de ?
        BGR: Bulgarian Adblock list‎ (stanev.org): 0 utilisé(s) sur un total de ?http
        CHN: China: cjxlist (main focus on Chinese sites)‎ (raw.githubusercontent.com): 0 utilisé(s) sur un total de ?
        CHN: EasyList China (中文)‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        CZE, SVK: EasyList Czech and Slovak‎ (raw.githubusercontent.com): 0 utilisé(s) sur un total de ?
        DEU: EasyList Germany‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        DNK: Schacks Adblock Plus liste‎ : 0 utilisé(s) sur un total de ?
        ESP: Filtros Nauscopicos‎ : 0 utilisé(s) sur un total de ?http
        EST: Eesti saitidele kohandatud filter‎ : 0 utilisé(s) sur un total de ?http
        EU: Prebake - Filter Obtrusive Cookie Notices‎ : 0 utilisé(s) sur un total de 736
        FIN: Finnish Addition to Easylist‎ : 0 utilisé(s) sur un total de ?
        FRA: EasyList Liste FR‎ (adblockplus.org): 5 727 utilisé(s) sur un total de 5 731Vider le cache
        GRC: Greek AdBlock Filter‎ (void.gr): 0 utilisé(s) sur un total de ?
        HUN: hufilter‎ (raw.githubusercontent.com): 0 utilisé(s) sur un total de ?
        IDN: ABPindo‎ : 0 utilisé(s) sur un total de ?
        ISL: Icelandic ABP List‎ : 0 utilisé(s) sur un total de ?
        ISR: EasyList Hebrew‎ (raw.githubusercontent.com): 0 utilisé(s) sur un total de ?
        ITA: ABP X Files‎ (dropboxusercontent.com): 0 utilisé(s) sur un total de ?
        ITA: EasyList Italy‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        JPN: ABP Japanese filters (日本用フィルタ)‎ : 0 utilisé(s) sur un total de ?
        KOR: Fanboy's Korean‎ (fanboy.co.nz): 0 utilisé(s) sur un total de ?
        LTU: Adblock Plus Lithuania‎ (margevicius.lt): 0 utilisé(s) sur un total de ?http
        LVA: Latvian List‎ (notabug.org): 0 utilisé(s) sur un total de ?
        NLD: EasyList Dutch‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        NOR: Norsk adblockliste‎ (fredfiber.no): 0 utilisé(s) sur un total de ?http
        POL: Adblock polskie reguly‎ : 0 utilisé(s) sur un total de ?http
        ROU: RO-LIST (modified)‎ : 0 utilisé(s) sur un total de ?
        RUS: BitBlock List (Дополнительная подписка фильтров)‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        RUS: RU AdList (Дополнительная региональная подписка)‎ (adblockplus.org): 0 utilisé(s) sur un total de ?
        SWE: Fanboy's Swedish‎ (fanboy.co.nz): 0 utilisé(s) sur un total de ?
        VIE: Fanboy's Vietnamese‎ (fanboy.co.nz): 0 utilisé(s) sur un total de ? 
    Vos propres listes

Une adresse Web par ligne. Les lignes débutant par un ‘!’ seront ignorées. Les adresses Web invalides seront ignorées sans avertissement.

**Comment by alain1965** [comment]
I ununstal ublocko and I repair FF but the result is the same but it seems you don't care about it I close the issue and leave ublocko sorry but I don't like man withselective interest and like I'm french I have a very bad mood sometime.

**Comment by alain1965** [comment]
If it's interesting someone, I resolved the problem, I uninstalled Firefox, erased all traces, reinstalled FF and addons and finally all lits from ublocko updted normally, good work from me many thanks to me, myself and I and sorry if this problem wasn't interresting for the genius.
