### ISSUE TITLE
Click-to-play

### ISSUE THREAD

**Issue by VLM-TechEd** [gorhill/uBlock#2710]
On your page https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-title-bar, you write, "And I had click-to-play enabled in all cases, so it could have been worse (except for default-deny)...".

I really have looked, and I apologize for an obviously newbie question, but in the context of uBlock Origin, what/where is click-to-play?

Thanks!

**Comment by mapx-** [comment]
https://www.howtogeek.com/188059/how-to-enable-click-to-play-plugins-in-every-web-browser/

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3AVLM-TechEd

**Comment by gorhill** [comment]
User blocked due to repeated disregard of [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
