### ISSUE TITLE
uBO randomly fails to collapse a blocked frame

### ISSUE THREAD

**Issue by ameshkov** [gorhill/uBlock#2712]
Here is the original report:
https://forum.adguard.com/index.php?threads/yahoo-filter.22706/

Steps to reproduce, filters, screenshot:
https://forum.adguard.com/index.php?threads/yahoo-filter.22706/#post-141658

Copy/pasting from there:
```
Details:
When the page is loaded for the first time, uBO does not collapse the blocked iframe element:
https://monosnap.com/file/ovtlZ8VxN9W3ncduuooox28x7CtkA9

Steps to reproduce:
1. Disable all the filters
2. Add Adguard English filter: https://filters.adtidy.org/extension/ublock/filters/2.txt
3. Purge all caches in uBO
4. Sign in to the Yahoo mail

The problem occurs randomly, you may need to repeat purge/sign in/refresh steps a couple times, it seems there might be a race condition.
```

- OS: MacOS Sierra
- Browser: Chrome 60
- uBO 1.12.4

**Comment by gorhill** [comment]
The site clobbers uBO's own inline `display: none !important;` style. I see Adguard also set `visibility` and `height`, so this is why it's not happening with Adguard. For now I created a simple filter to take care of the issue.

**Comment by gorhill** [comment]
Should be fixed as a side effect of using user styles, related commit: <https://github.com/gorhill/uBlock/commit/d97c46ffd3eb9ae1be4cc9dcf22b49abbd14ab1d>.
