### ISSUE TITLE
Web Fonts in uBlock and uMatrix

### ISSUE THREAD

**Issue by temporaryaccount** [gorhill/uBlock#2714]
### Describe the issue

There are numerous security related bugs constantly being found in font rendering engines (here is one [example](https://www.mozilla.org/en-US/security/advisories/mfsa2016-37/)) that's why I have disabled web-fonts in my browser.

uMatrix is ugly and nearly unusable without web-fonts, uBlock to some lesser extent.

uMatrix has Issues disabled so excuse me for reporting it here, but uBlock has this issue too.

Would it be possible to use standard unicode characters or old-school icons (PNG or maybe SVG) instead of web-fonts with custom unicode icons?

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
![Screenshot](https://i.imgur.com/Dj8sqs4.png)

### Steps for anyone to reproduce the issue

Disable Web-Fonts in your browser
Use the extension

### Your settings

- OS/version: Windows 8.1
- Browser/version: Firefox 54
- uBlock Origin version: Latest from AMO

**Comment by anewuser** [comment]
>uMatrix has Issues disabled

**If the issues tab for a project is disabled, it's because its developer(s) can't or don't want to get reports for it** currently. Please don't open other projects from the same people to make reports about them. [As @Tailszefox said](https://github.com/horst3180/arc-theme/issues/799#issuecomment-309292439):

>Please remember that developers are human beings like all of us. Sometimes a personal problem might show up forcing them away from their digital life. It's even more true for projects created on the developer's personal time and available for free. We can't expect them to drop everything in their life whenever a problem with their projects shows up. Personal issues will and should always take priority.

As for your report, you intentionally broke the fonts, so you can't complain about it to anybody and demand everybody else to have an inferior GUI because of it. You'd need to prove that there's any security problem with the fonts **included by the extensions, which are used offline** for there to be any consideration about removing them. 

https://github.com/gorhill/uMatrix/tree/master/src/css/fonts
https://github.com/gorhill/uBlock/tree/master/src/css/fonts

**Comment by temporaryaccount** [comment]
> Please don't open other projects from the same people to make reports about them.

I understand that, and that's why I mentioned that the same issue exists in both projects, so reporting it here isn't violating (I hoped) the rules. I'm sorry if my reasoning was wrong.

> As for your report, you intentionally broke the fonts, so you can't complain about it to anybody, or demand everybody else to have an inferior GUI because of it.

Oh, I'm not demanding anything, this was an issue for me and I reported it. Please feel free to close it if you think this is a non-issue. Concerning the "inferior GUI" part I beleive a couple of SVG vector icons take less space on users' computers than a glyph-font with hundreds (thousands?) of icons and the user experience doesn't change.

> You'd need to prove that there's any security problem with the fonts included by the extensions, which are used offline for there to be any consideration about removing them.

I would happily enable web-fonts for the trusted extensions, but the browser's settings allow only global switch.

> Both uBlock and uMatrix can be used to block the download of fonts by specific or all websites, so you can keep the feature enabled on your browser while using the extensions to block online requests to fonts.

I wasn't aware that I could allow scripts and at the same time block, for example, web-fonts and media from a host. If the feature exists then this issue can be safely closed, thank you for your time.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
