### ISSUE TITLE
Chrome Extension releases

### ISSUE THREAD

**Issue by Irbidan** [gorhill/uBlock#2716]
It's not normal when you launch a new release of uBlock Origin (17 hours ago) which is merely a new version. Google thinks it contains malware for each version? Maybe he checks code, integrity, performance, etc? Maybe Google spies us? 

I know that it is relatively impossible contact with Google. 

Something has to be done because if you work for a company the software must be delivered on time.

![captura](https://user-images.githubusercontent.com/541941/27339152-50c354cc-55d7-11e7-903f-b412797c52da.PNG)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
