### ISSUE TITLE
large image blocked even when blocking of large media elements is toggled off

### ISSUE THREAD

**Issue by holvoetj** [gorhill/uBlock#2721]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

uBlock with default settings blocks a large image (see URL below). Toggling blocking of large media elements does not allow the image to be shown.

### One or more specific URLs where the issue occurs

http://www.sportpaleis.be/nl/kalender/2017-2018/queens-of-the-stone-age

### Screenshot in which the issue can be seen

Screenshots attached

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

Everything left at default.

- OS/version: Windows 10
- Browser/version: Firefox 54.0
- uBlock Origin version: 1.13.0

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

None
![imageblocked](https://user-images.githubusercontent.com/29592806/27371520-76e54860-5661-11e7-8c07-72da1ddd2f0a.jpg)
![imageshown](https://user-images.githubusercontent.com/29592806/27371521-76ee84d4-5661-11e7-893e-7f0137529810.jpg)

**Comment by gwarser** [comment]
Static filter `/divolte.js` found in:

    EasyPrivacy

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
