### ISSUE TITLE
Inconvenient default hotkey mapping activation

### ISSUE THREAD

**Issue by koral--** [gorhill/uBlock#2723]
### Describe the issue
When uBlock has been updated to v 1.13.0 and keyboard layout using right Alt is set then browser (Chrome) enters weird state silently.
In some keyboard layouts eg. Polish (programmer) right Alt/Option is used to type letters with diacritics e.g. Alt+Z = ż.
After update to 1.13.0 this feature had been broken and users need to manually remove/change shortcuts.

Possible solutions:

1. Use left Alt instead of right one (if possible from plugin level)
2. Change Alt to something else
3. At least do not enable conflicting hotkey silently on extension update

### Steps for anyone to reproduce the issue

1. Have some keyboard layout set which uses right Alt key (eg. Polish programmer)
2. Update extension to v 1.13.0
3. Try to type e.g. `ż`
4. Element zapper mode is activated instead

### Your settings

- OS/version: macOS/10.12.5
- Browser/version: Chrome/58.0.3029.110
- uBlock Origin version: 1.13.0

**Comment by mliese** [comment]
OS/version: macOS/10.12.5
Browser/version: Chrome/58.0.3029.110
uBlock Origin version: 1.13.0

Alt+L is now opening a new tab to "logger-ui.html"
Alt+L is normally "@".

Had to actually disable the extension for now.
Im missing an option to disable all hotkeys?

**Comment by gorhill** [comment]
Would <Ctrl>-<Shift> instead of <Alt> work better?

**Comment by gorhill** [comment]
<kbd>Ctrl</kbd>-<kbd>Shift</kbd> does not work on my side. I will just remove the suggested default and users configure themselves and use whatever works for them.

**Comment by gorhill** [comment]
Meanwhile, those key bindings can be changed in Chrome, go to `chome://extensions`, scroll down and click _"Keyboard shortcuts"_ at the bottom of the page.

**Comment by gorhill** [comment]
I would like to know if the issue reported here also affects Firefox.

**Comment by gwarser** [comment]
No problem with Polish layout in Linux Mint 17.3, Fx nightly

**Comment by dhigh88** [comment]
@gorhill Hello sir, sorry I know this isn't the place to report another issue but is it possible you or any other staff can please assist me in the ublock edge issue page? Anytime I ask for help I haven't had no assistance from nikrolls.

**Comment by gwarser** [comment]
I also checked Win XP, Fx 52.2esr, UBO 1.13.0. Looks almost good. Left alt+z brings main Fx menu. Picker mode and logger works. I can type żźł (right alt + zxl).

**Comment by gorhill** [comment]
@dhigh88 
> Hello sir, sorry I know this isn't the place to report another issue but is it possible you or any other staff can please assist me in the ublock edge issue page? Anytime I ask for help I haven't had no assistance from nikrolls.

[This](https://github.com/nikrolls/uBlock-Edge/issues/85)?

Looks like a filter list issue to me, should not be opened on uBO Edge's issue tracker, but rather at <https://github.com/uBlockOrigin/uAssets>.

That the issue occurs only with Edge does not make it less a filter list issue, sites will commonly sniff user-agent info and execute specific code path. So always assume filter list issue and report where appropriate, the filter list maintainers will figure out if there is really an issue in uBO itself.

Also, there is no "staff" with uBO, only volunteers contributing on their free time.

**Comment by nietaki** [comment]
I just run into the same problem (Chrome on OSX) and believe me, for any Polish layout user it's an extremely annoying thing to encounter. I was on the verge of ditching uBlock Origin until I read @gorhill's comment :)

I'd argue that setting any shortcuts for uBlock origin's functionality by default is overkill. I consider myself a Chrome poweruser but I never felt the need to have any shortcut for "uBlock Origin logs". While it's a good thing to be able to provide a shortcut for those functionalities, I think for the vast majority of users setting up any default shortcuts will cause more annoyance than it would be helpful.

**Comment by gwarser** [comment]
UBO 1.13.2 in Vivaldi (stable) - manually set shortcuts not work (Probably Vivaldi fault `#2719` `#953`?)

**Comment by gorhill** [comment]
For any issue affecting Vivaldi or any of the Chromium-based browsers no covered here (Chromium, Chrome, Opera), a maintainer will have to step up and fork to deal with issues specific to the platform as was done with Edge and Safari.

**Comment by indywidualny** [comment]
How to disable shortcuts completely? I cannot use my keyboard normally now.

**Comment by gorhill** [comment]
I added details on how to do this in [Release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.2):

> For those already affected by the issue, the suggested shortcuts were already added and won't be removed with this update. You will have to remove or re-assign yourself by clicking _"Keyboard shortcuts"_ link in the page `chrome://extensions` -- the link is at the bottom of the page.

**Comment by bershan2** [comment]
@indywidualny Shortcuts are disabled by default in 1.13.2, so just update: go to `chrome://extensions` and click "Update extensions" in the top right corner.
In general, you can set shortcuts by going to `chrome://extensions` and then scrolling all the way down, clicking "Set shortcuts" in the bottom right corner -- menu will appear.

**Comment by gorhill** [comment]
@bershan2 If the shortcuts have been added by 1.13.0, I don't think they will be removed with 1.13.2, what has been removed is the suggested shortcuts in 1.13.2.

**Comment by dhigh88** [comment]
@gorhill Appreciated the response. I've submitted it to the requested page.

**Comment by gorhill** [comment]
I also modified the code for Firefox: just like with Chromium, users will have to assign the shortcut themselves. By default, there are no shortcuts.

**Comment by akuji1993** [comment]
What @mliese is saying is very annoying and nearly a reason to remove this program from my browser.

**Comment by happysurf** [comment]
The suggested shortcuts like alt-X or accel-X doesn't work on my Firefox 56b10 + UBO 1.14.9b0 on Windows.

**Comment by gorhill** [comment]
@happysurf <https://github.com/gorhill/uBlock/issues/2987>.

**Comment by F-DK** [comment]
How is this issue closed?? 

This extremely annoying keyboard shortcut mapping is still true:
https://github.com/gorhill/uBlock/issues/2723#issuecomment-310032754

> Alt+L is now opening a new tab to "logger-ui.html"
> Alt+L is normally "@".

In consequence one cannot write @ in Chrome at all 😭 

OS/version: macOS/10.12.6
Browser/version: Chrome/61.0.3163.100
uBlock Origin version:  1.14.12

**Comment by F-DK** [comment]
Okay, after further googling I found this super hidden feature in Chrome. Thanks @receter!

https://github.com/chrisaljoudi/uBlock/issues/1688#issuecomment-315674336

> Solution: Go to chrome://extensions/ , scroll down to the bottom, click Keyboard shortcuts, remove the shortcut
