### ISSUE TITLE
Youtube videos can no longer Block

### ISSUE THREAD

**Issue by xXSamyXx** [gorhill/uBlock#2726]
Hello

And I have the following problem I can not see YouTube videos anymore if I have uBlock on but when I do it off then I'm going to have nothing changed that just went on.
The videos just load but nothing happens

**Comment by bershan2** [comment]
Dear @xXSamyXx,

this is likely a filter issue and not uBO issue which should not be reported here but instead to the maintainers of the list with the faulty issue. This post will be marked _invalid_ and closed, please read [CONTRIBURING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) for an explanation why.

Either just wait for someone who knows to fix the problem, or try doing it yourself:
* find the faulty filter
   - open the Dashboard 3-rd party filters pane (click the uBO icon -> in the menu click the cogs icon -> go to "3-rd party filters" pane
   - take note of which filters are enabled, disable all filters
   - try re-enabling filters on-by-one and try playing videos to see which filter causes the error
* find the faulty rule with [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) (or go to step 3 directly if you can't)
   - close all tabs except for one with YouTube and one with a logger (too simplify your search)
   - reload YouTube tab to see all requests
   - in the logger click on used rules and search for the rule that appears in the faulty filter
* report the rule to the list maintainers
   - go back to he Dashboard 3-rd party filters pane and click on the home button next to the filter with error.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
