### ISSUE TITLE
Firefox 57 and UBO

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#2728]
UBO appears to not be compatible with firefox 57+ Are there plans to make it compatible?

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/2576#issue-225417939

**Comment by rayman89** [comment]
So if I understood correctly UBO is both a web extension and a legacy addon and that's why it appears to be labeled legacy even if it's compatible with ff57+?

**Comment by bershan2** [comment]
@rayman89 No, current uBO will not run on FF57+, but future uBO will. Firefox undergoes an API transition right now, and starting from ["Firefox 57, November 14th release Firefox will only run WebExtensions"](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/). Therefore uBO was made into WebExtension with a wrapper code to ensure compatibility with older browsers: uBO just recently dropped support for browsers released in 2015 (see issue 2612)!

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
Search the issue tracker before opening issues please: <https://github.com/gorhill/uBlock/issues?q=is%3Aissue+webext> => <https://github.com/gorhill/uBlock/issues/622>

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by alsternerd** [comment]
Problem is: Addons labeled legacy, even if compatible are now being deactivated randomly on FF 55.0.3. (Not after the update, just randomly sometime while running)

**Comment by anewuser** [comment]
@alsternerd Please report that to Mozilla instead of generating noise here.
