### ISSUE TITLE
Logger color too bright for cosmetic hiding

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2730]
1.13.0 had [this change](https://github.com/gorhill/uBlock/blob/02323826950c7d99b65d93f9edb8fa018159973c/src/css/logger-ui.css#L160) to logger-ui.css that now uses a bright color for all dom (cosmetic) hidden elements in the logger. It's too bright and harsh on my eyes, especially since I do a lot of dom hiding and thus it's a bright block of color. (identical in 1.13.2 on GChrome and 1.13.3b2 on Pale Moon, both using Color-blind friendly mode.)

I changed it to no color (i.e. same white background as permitted requests) and find that it works well for cosmetics -- as you can see in the screenshot they're already clearly indicated with "dom" label + the hiding rule:

![dom_white](https://user-images.githubusercontent.com/14959062/27505758-d63e4396-5875-11e7-9cb9-21bc19a983a4.png)

So, can you remove the "tr.cosmetic" from the .css and use the white background? (I would keep redirects colored, as those should stand out.)

And, btw, very nice job on the many other changes for v1.13! I like the removal of "--" in the logger for cosmetics, so that only blocked requests have them. The leaner static storage is evident in both browsers, and the zapper is cool :)

**Comment by gorhill** [comment]
> 1.13.0 had [this change](https://github.com/gorhill/uBlock/blob/02323826950c7d99b65d93f9edb8fa018159973c/src/css/logger-ui.css#L160) to logger-ui.css that now uses a bright color for all dom (cosmetic) hidden elements in the logger.

There was no change to the color in 1.13.0, only the class name changed. The color itself is the same as was before: <https://github.com/gorhill/uBlock/blob/53b0db3d250caa6ec33577bc514b3ef4192bd260/src/css/logger-ui.css#L160>

**Comment by joey04** [comment]
No, the class name change _certainly_ has the effect of changing the color for all of my browsers in Color-blind friendly mode.

Here's how the logger has always looked for the 2 years I've been using uBO in all 3 browsers (GChrome, Firefox, Pale Moon). This is taken today with 1.12.4 on Firefox:

![old12](https://user-images.githubusercontent.com/14959062/27509165-cd23527a-58c4-11e7-9443-08090eacfddd.png)

And here's 1.13.2 on GChrome with the new cosmetic color due to the class name change (it's the same with 1.13.3b2 on Pale Moon before I made the change to white background):

![new13](https://user-images.githubusercontent.com/14959062/27509184-24b7ad6a-58c5-11e7-8444-453918f4bebd.png)

As I said before, I like the removal of the '--' for dom, but the new color is too bright, especially in low-lighting conditions at night when there's a big group of 10+ hidden elements bunched together in the logger (which is common for me on my most-visited sites).

If you don't want to go with white, please change it to a less-bright color. This is Color-blind mode, which of course is a special case (one which I'm very grateful you'd already added by the time I first learned about uBO).

**Comment by gorhill** [comment]
> No, the class name change certainly has the effect of changing the color for all of my browsers in Color-blind friendly mode.

Sorry, I missed that you were referring to color-blind mode specifically. I can reproduce, this is a regression. I will bring back the original color (i.e. no change). However I won't bring back the `--` field, I will instead use `##`, and remove the `##` prefix from the filter cell.

**Comment by joey04** [comment]
>  I will bring back the original color (i.e. no change). 

Thanks!

> However I won't bring back the -- field, I will instead use ##, and remove the ## prefix from the filter cell.

I suggest keeping it as-is in v1.13 with a blank 4th column for cosmetics. The fact that the filter rule is displayed and it has a colored background makes it prominent enough. Plus, I like seeing the full ##. or ### or ## prefix (to distinguish class or ID or element) on the rule in the 2nd column.

**Comment by gorhill** [comment]
Yes, on second thought, it's not a good idea to remove the `##` prefix, it's part of the filter.
