### ISSUE TITLE
Add way to disable Alt+L shortcut

### ISSUE THREAD

**Issue by kopiczko** [gorhill/uBlock#2732]
### Describe the issue

When I press `Alt+L` in my browser while typing I moved to uBlock log window. This is annoying for polish typist, because it makes impossible to type `ł`.

### One or more specific URLs where the issue occurs

All. For example https://inbox.google.com.

### Steps for anyone to reproduce the issue

1. Go to https://ingox.google.com
2. Start typing a mail.
3. Press `Alt+L`.
4. You see logs window instead `ł` character.

### Your settings

- OS/version: macOS Sierra 10.12.5
- Browser/version: Version 58.0.3029.110 (64-bit)
- uBlock Origin version: 1.13.2

**Comment by anewuser** [comment]
This has been reported many times already. Please close this issue.

https://github.com/gorhill/uBlock/issues/2723#issuecomment-310044763

**Comment by anewuser** [comment]
https://github.com/gorhill/uBlock/issues/2723

https://github.com/gorhill/uBlock/issues/2724

https://github.com/gorhill/uBlock/issues/2727

**Comment by gorhill** [comment]
[Release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.2) contains the solution.
