### ISSUE TITLE
V1.13.3b3 uBlock0.webext.xpi gear icon doesn't open up the dashboard.

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2734]
I just upgraded to V1.13.3b3 uBlock0.webext.xpi.  Clicking on the gear icon does not open the dashboard, it does nothing at all.  I can only open the dashboard via the Dashboard button in my Add-ons Manager screen for uBO.

Running Fx56 Nightly 64 bit on Windows 10 Pro CU 64 bit.

My Browser Console shows this when I click on the gear icon:

[Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://browser/content/ext-tabs.js :: query :: line 482"  data: no]  (unknown)
tabs is undefined  vapi-background.js:481
Unchecked lastError value: Error: An unexpected error occurred  ExtensionCommon.jsm:306

**Comment by bershan2** [comment]
Works fine for me on:
> Chrome 59.0.3071.109 (Official build), (64 bit)

In case you need it:
> Windows 10 Home 64 bit Version 1703; OS Build 15063.413

Testing Firefox now...

**Comment by streetwolf** [comment]
I also just noticed that there is now extra space on the top and bottom of the menu.  I believe this was a problem not too long ago that got fixed. 

To be more precise I am currently on inbound not Nightly.  If my problem is because of a patch on inbound It might not be on Nightly but should be tomorrow.

**Comment by gorhill** [comment]
I talked about that bug on mozillazine a while ago. I can't find the post. It links to the relevant bugzilla bug.

**Comment by streetwolf** [comment]
I thought you removed the WE version for Fx because of this problem.  When I saw it was available again I assumed you fixed the problem and I tried it again.  I mentioned two problems, no dashboard and the extra spaces on the menu.  I know there is a Mozilla bug report about the extra spaces, I came across it the other day.  Is the dashboard problem also a Mozilla problem?

**Comment by gorhill** [comment]
It's a Nightly issue. Same code works fine in Chromium and Edge.

I found the link to the post finally: http://forums.mozillazine.org/viewtopic.php?p=14751077#p14751077

As stated in the commit, I brought back the hybrid-webext because it works with FF54.

Any issue with webext uBO not affecting also the Chromium version is most likely a Nightly issue.

**Comment by heubergen** [comment]
It seems like we're waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1271354 to be fixed?

**Comment by streetwolf** [comment]
I'm on the latest Fx56 inbound along with uBO webext 1.13.7b1 and all the icons on the menu are now working.
