### ISSUE TITLE
  Add the ability to disable only general cosmetic filter for single site

### ISSUE THREAD

**Issue by dinoartino** [gorhill/uBlock#2735]
Same site use a cosmetic to detect ublock origin , ublock origin allow to disable all cosmetic filter for a single site , bat in this way i cannot block static  element !

Can I get a button to disable only generic cosmetic filters for a single domain?

**Comment by bershan2** [comment]
@dinoartino 
[uBlock Origin floating user interface had the ability to disable cosmetic filtering on per-site basis for a while now](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) (as well as three more per-site toggles). Just click the "UO" shield to see it!

Also, please read [CONTRIBTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):
 - this logger is only for **issues** (bugs) with uBO, i.e. problems that make uBlock Origin stop working
 - this issue will be closed and marked _support issue_ and _invalid_
 - > For **support/discussions**, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by dinoartino** [comment]
noo ublock origin disable all cosmetic ,  i neded disable only "generic"  filters  for a single site!
generic filters include  filters to hide  white space  

because when you disable only generic filters you can make a  static filters  while if you disable all cosmetic filters , you cannot make a roules!

the option  Ignore generic cosmetic filters is valide for all site , I ask a way to implement it for individual domains


example
![image](https://user-images.githubusercontent.com/29687633/27520484-df2cf176-5a0c-11e7-9f86-d0cbf2175631.png)

the option  Ignore generic cosmetic filters is valide for all site , I ask a way to implement it for individual domains

**Comment by bershan2** [comment]
I'm not sure what you mean. What "roules" are you talking about? Why are you on the 3rd-party pane? 3rd-party pane defines the global behavior.

Did you try this button (that I linked to above)?
![Image](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1j.png)

**Comment by gwarser** [comment]
https://adblockplus.org/en/filters#options `$generichide`
