### ISSUE TITLE
Counting appears wrong in blocked requests.

### ISSUE THREAD

**Issue by Outernaut** [gorhill/uBlock#2738]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Lack of documentation: 
Procedure:

Click on the uBlock (uB) grey square with the number in it.
This opens the GUI. In GUI, left-click the "requests blocked" text, if the blocks are not showing." See attached image.
Unable to find any docs describing how it is the uB icon count can be 12 (example) and what the meanings of the + and - on the right, and colored bars at left represent. The example in the pic is that of this forum post as I was writing it. 12 blocks from gitHub - hmm. :)

Suggest adding in the docs(?) an explanation of what the red, green and amber may mean, and what the + and - mean at the other side.

Just a thought from a newb.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
https://github.com/gorhill/uBlock/issues/new will do, or any site.

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
![ublock counts](https://user-images.githubusercontent.com/19696413/27563177-0a5b7c6e-5a85-11e7-99b0-9ca737d50be9.jpg)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:Click on the uBlock (uB) grey square with the number in it.
This opens the GUI. In GUI, left-click the "requests blocked" text, if the blocks are not showing." See attached image.
Unable to find any docs describing how it is the uB icon count can be 12 (example) and what the meanings of the + and - on the right, and colored bars at left represent. The example in the pic is that of this forum post as I was writing it. 12 blocks from gitHub - hmm. :)
1. Because we are not looking over your shoulder and (stalkers are!)
1. Keep in mind: Nobody can read your mind. Hire my wife.  :)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  Vista Home, Win 7, 8, 8.1 and 10
- Browser/version: as of this moment, 52.1.2 (32-bit) this may change to an update at any moment.
- uBlock Origin version: 1.13.0

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
uB install default plus any auto updates.
##### Your custom filters (if any)
none

**Comment by bershan2** [comment]
There are a few problems with your report:
1. **What is your issue?**
2. See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):
   > For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).
3. > Lack of documentation:

   <https://github.com/gorhill/uBlock/wiki>
4. Red means "block", green means "white-list" ("allow")

**Comment by Betsy25** [comment]
Also take a close look [here](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide), it'll answer most of your q's.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
