### ISSUE TITLE
Allow advanced users to turn prefetching back on

### ISSUE THREAD

**Issue by smiley** [gorhill/uBlock#274]
I use uBlock mostly for the ad-blocking aspect but also partially for privacy reasons. However, prefetching actually helps with my connection, which can be high-latency at times. Since my IP is dynamic and changes on a near-daily basis, I wouldn't mind as much if I had it on. Can you add an advanced option for overriding this? Since the extension asks for control of the setting, it's no longer user-controlled.

P.S.: I know this is essentially a feature request, but I feel it's relevant due to the new permissions and tried to condense it as much while still explaining _why_ I felt it was important.

**Comment by gorhill** [comment]
Ok, I will provide such setting (enabled by default), though uBlock will still need Chromium's _Privacy_ permission to act on the setting. Unfortunately, the _Privacy_ permission is not in the set of [optional permissions](https://developer.chrome.com/extensions/permissions#manifest).

**Comment by gorhill** [comment]
How fast the next version is published will depend on how fast the translation work comes on.

Now people can re-enable pre-fetching with this new setting, but at least I am satisfied that users are made aware of the negative consequences of pre-fetching, while before those negative consequence were not disclosed up front, undermining the primary purpose of uBlock.

**Comment by galambalazs** [comment]
:+1:

**Comment by Gitoffthelawn** [comment]
@gorhill wrote: "...but at least I am satisfied that users are made aware of the negative consequences of pre-fetching."

That's a good public education service!  How are they currently made aware?

**Comment by gorhill** [comment]
@galambalazs The new setting is worded as follow:

    > Disable pre-fetching (to prevent any connection for blocked network requests)

If you means "currently" as in "before the new setting", well, the [release notes](https://github.com/gorhill/uBlock/releases/tag/0.9.8.2) informed why this was needed.

**Comment by ryanwelka** [comment]
Is there a way to make a prefetch whitelist for sites and only allow prefetching of data on those sites?
