### ISSUE TITLE
How about adding "^" to static filter made from logger?

### ISSUE THREAD

**Issue by yasmise** [gorhill/uBlock#2740]
### Describe the issue
When I create a static filter from logger, I sometimes insert a "^" to the created filter if that doesn't end with specific file name. Please see this image.

![dialog](https://user-images.githubusercontent.com/22886576/27588056-c360a44e-5b81-11e7-94f1-294b762f322e.png)

In this case, I'm making a filter to block javascripts under `www.itmedia.co.jp/js`, however, generated filter is `||www.itmedia.co.jp/js$script,domain=www.itmedia.co.jp`, so, this filter could be overkill if they have javascripts under `www.itmedia.co.jp/js-example` or something.
I would really appreciate it if you could add "^" to the generated filter, like `||www.itmedia.co.jp/js^$script,domain=www.itmedia.co.jp`.

### One or more specific URLs where the issue occurs
You can use any web pages because this is a user interface issue.

### Screenshot in which the issue can be seen
Please see above.

### Steps for anyone to reproduce the issue

1. Visit a web page (e.g. http://www.itmedia.co.jp/).
2. Open logger of uBlock origin and reload the page to make log.
3. Click 4th column of logger to make a static filter (e.g. row of script: http://www.itmedia.co.jp/js/scAccount.js).
4. Select Static filtering tab, change matching URL to a URL which doesn't contain specific file name (e.g. change to www.itmedia.co.jp/js).
5. The generated filter doesn't have "^" before "$".

### Your settings

- OS/version: Windows 10 Home 1703
- Browser/version: Firefox 54.0
- uBlock Origin version: 1.13.0

##### Your filter lists
My filter
uBlock filters
uBlock filters - Badware risks
uBlock filters - Privacy
uBlock filters - Unbreak
EasyPrivacy
Malware Domain List
Malware domains
Fanboy's Annoyance List
Peter Lowe’s Ad and tracking server list
Adguard Japanese filter (http://adguard.com/filters.html#japanese)
Spyware filter (http://adguard.com/filters.html#privacy)
Tofu filter (http://tofukko.r.ribbon.to/abp.html)

##### Your custom filters (if any)
||apis.google.com/js/plusone.js$script,domain=~kitamura.jp
||adtechus.com^$third-party
banner_subscription.gif$image,domain=natgeo.nikkeibp.co.jp
banner_subscription_short.gif$image,domain=natgeo.nikkeibp.co.jp
||bannerfarm.aolp.jp^$script
||dmp.im-apps.net^$script
||hatena.co.jp^$third-party
||itunes.apple.com^$third-party
||line-apps.com^$domain=~matome.naver.jp
||line.me^$third-party
||linkback.contentsfeed.com^$script
||platform.twitter.com/widgets.js$script,domain=~itmedia.co.jp
||play.google.com^$third-party
||query.yahooapis.com^$script
||r10s.jp^$domain=~rakuten.co.jp
||st-hatena.com^$domain=~hatenablog.com|~hatena.ne.jp|~hatelabo.jp|~hateblo.jp
st-hatena.com/ad?

**Comment by gorhill** [comment]
How about instead of `^`, I just keep the `/` character that is already in there? The problem with using `^` is that it forces the filter to be regex-based internally, i.e. inefficient. Using `/` means the engine can use plain string comparison internally. The `^` could still be used for plain hostname matching though.

**Comment by yasmise** [comment]
Yes, I agree with you. I'm for to keep `/`, instead of `^`.
Thanks for your quick reply and kind description.
