### ISSUE TITLE
uBlock Chrome extension makes it impossible to enter certain Polish letters using AltGr

### ISSUE THREAD

**Issue by andrzejc** [gorhill/uBlock#2741]
### Describe the issue
The most common Polish keyboard layout - "Polish Programmers'" uses AltGr (right Alt) combinations to enter diacritics like "ł" (AltGr+l), "ż" (AltGr+z). Starting with some recent release uBlock overrides these shortcuts and makes it impossible to enter these letters, so it's impossible to write Polish in any web forms, documents etc, and its incredibly annoying for people which do it habitually. uBlock keyboard shortcuts should be activated only with "ordinary" (left) Alt combinations or the keyboard shortcuts should be customizable. I believe there are other languages which use AltGr keystroke combinations, which are affected too.

### One or more specific URLs where the issue occurs
every site

### Steps for anyone to reproduce the issue

1. Set your keyboard layout to "Polish Pro"
2. Try entering any of the above-described letters
3. Watch uBlock's log or element picker are activated

### Your settings
- OS/version: macOS Sierra 10.12.5
- Browser/version: Chrome 59.0.3071.109
- uBlock Origin version: 1.13.2

##### Your filter lists
Default filter lists + POL

##### Your custom filters (if any)
none

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/2723 
https://github.com/gorhill/uBlock/releases/tag/1.13.2

**Comment by andrzejc** [comment]
thanks, I haven't checked closed issues as it was still happening. closing the duplicate
