### ISSUE TITLE
domIsLoaded errors

### ISSUE THREAD

**Issue by quilloss** [gorhill/uBlock#2743]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
The following error are logged in the browser console.
>Security wrapper denied access to property "domIsLoaded" on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.
>-contentscript.js:1632:8

>Error: Permission denied to access property "domIsLoaded"
>-contentscript.js:1634:5

I don't think any of the page's content are affected.

### One or more specific URLs where the issue occurs
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=redirect
Not sure if the bug is specific to this site.

### Steps for anyone to reproduce the issue

1. Visit https://bugzilla.mozilla.org/buglist.cgi?quicksearch=redirect
1. Check browser console

### Your settings

Separate Firefox profile with only uBlock Origin reset to default.

- OS/version: Windows 10
- Browser/version: Firefox 55.0b5
- uBlock Origin version: 1.13.4

**Comment by quilloss** [comment]
I forget to add that blocking this script https://bugzilla.mozilla.org/data/assets/021c5500e76c911bb3e2d0340b87f9b7.js?1497361122 prevents the error from occurring.

**Comment by gorhill** [comment]
I didn't get your specific error, but I got these instead:

    07:50:00.930 TypeError: Argument 1 of MutationObserver.observe is not an object.  contentscript.js:968:9
    07:50:01.916 TypeError: context.contentWindow is null  ExtensionContent.jsm:325:9

So it appears uBO's content scripts are injected in a context which is not properly initialized or has some sort of issue, even the browser-side code emits an error (the `ExtensionContent.jsm` one). I consider this a browser issue -- report to Firefox devs please.
