### ISSUE TITLE
[Feature Request] Adguard Filter Lists 

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#2744]
Can you please add the Adguard Filter Lists.

Thanks

https://kb.adguard.com/en/general/adguard-ad-filters

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues?q=is%3Aissue+author%3Azero77+is%3Aclosed

**Comment by bershan2** [comment]
@zero77 You know that you can subscribe to any filter lists yourself, right?
https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

**Comment by gorhill** [comment]
He knows: <https://github.com/gorhill/uBlock/issues/2501>.
