### ISSUE TITLE
@-Shortcut on Mac Chrome opens protocol screen

### ISSUE THREAD

**Issue by davidbru** [gorhill/uBlock#2745]
Since upgrading to the latest current version 1.13.2 there seems to be a new shortcut (at least on Mac+Chrome).
If I hit "CMD" + "L" instead of getting the @ symbol it now opens the protocol screen.
If I disable uBlock the problem disappears.

Since I did not find any way to choose new shortcuts I have now currently two options:
1. Live without uBlock (would rather not)
2. Change to e.g. Word. Write the @ there. Copy and paste it into chrome.

- OS/version: Mac 10.12.5
- Browser/version: Google Chrome 59.0.3071
- uBlock Origin version: 1.13.2

**Comment by 5t3f4n** [comment]
Duplicate of #2723 

Update to latest version.

**Comment by davidbru** [comment]
Thanks for the fast feeback.
Was trying my luck the the search before posting, but "shortcut" != "hotkey" :/

**Comment by bershan2** [comment]
@davidbru By "protocol screen" do you mean [the logger](https://github.com/gorhill/uBlock/wiki/The-logger)? If so, you should disable the shortcuts as described in the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.2).

**Comment by davidbru** [comment]
Yes I of course meant the logger.
Solved my issue by disabling the shortcuts :)

Am 29.06.17 um 23:22 schrieb Anton Bershanskiy:
