### ISSUE TITLE
Dailymotion

### ISSUE THREAD

**Issue by Loeak** [gorhill/uBlock#2746]
Les vidéos Dailymotion ne se lancent plus, il y a un écran noir à la place.

http://www.divertissonsnous.com/2017/06/29/cet-homme-aime-jouer-avec-le-feu-pendant-un-lacher-de-taureau/

Et

www.tout-bon.com

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Issue is with EasyList France, report to maintainers.
