### ISSUE TITLE
[feature option] Generic detection and blocking for execution of polymorphic obfuscated JS code to counteract Secret Media company

### ISSUE THREAD

**Issue by HLFH** [gorhill/uBlock#275]
Hi,

uBlock Origin should detect and block JavaScript polymorphic obfuscated code.

[JavaScript rules GitHub](http://www.itworld.com/article/2842960/javascript-still-rules-github.html) and is now _necessary_ for web users. So, we can't disable JS without affecting the Web.

The French company [Secret Media](http://www.secretmedia.com/) claims that they make useless the adblockers by using a _polymorphic encryption algorithm_ on some JS code used for advertising.

Secret Media CEO, Frédéric Montagnon, criticizes the Eyeo + PageFair model (acceptable advertising) [at the end of their whitepaper](http://www.secretmedia.com/whitepaper/adblocker_whitepaper.pdf) and [on Quora](http://www.quora.com/How-can-websites-beat-AdBlock-and-other-similar-plugins).

They also specifically say that:

> Secret Media provides a solution to bypass ad
> blockers that does not rely on a script; therefore
> the EasyList community cannot overcome it.
> The technology used by Secret Media makes
> sure that each ad gets a specific URL that cannot
> be nor found not added to EasyList by the
> community.
> In order to ensure results, Secret Media also
> measures properly the delta between
> impressions blocked and viewed. 

Could Secret Media use especially for pre-roll videos (that [take the crown according to IAB](http://www.iab.net/media/file/BreakMediaDigitalVideoStudy2012.pdf)) some real-time polymorphism techniques similar to [Shape Security (founded by ex-Googlers)](https://www.shapesecurity.com/technology/)?

So, do you believe, dear @gorhill and contributors that we can block JS polymorphic encryption?

Thanks in advance,

**Comment by gorhill** [comment]
> So, do you believe, dear @gorhill and contributors that we can block JS polymorphic encryption?

I can only deal with real, concrete cases, not vague claims. Give me a case where blockers, including uBlock, fail and I will be interested to find out what can be done.

**Comment by gorhill** [comment]
Alright, it's an impossible to close issue since there is nothing very specific to deal with. Mainly, a press release from company filled with buzz words is busy marketing itself. Whatever happen in the future will be dealt with when there is actual code to investigate.

**Comment by folsomwg** [comment]
I know this a closed issue @gorhill, but I believe I have a concrete example if you're interested.
