### ISSUE TITLE
uBlock Origin opera isn't blocking ad banner, but uBlock Origin chrome does

### ISSUE THREAD

**Issue by amandeep-sharma** [gorhill/uBlock#2751]
On the top of the page, there is an ad banner in the opera; but not in chrome.
Issue can be reproduced using below URL
http://a1.mylivecricket.tv/

opera version - 46.0.2597.32 (uBlock Origin 1.12.4)
chrome version - 59.0.3071.115 (uBlock Origin 1.13.2)

I am using default filter list.

**Comment by gorhill** [comment]
Fix is in <https://github.com/gorhill/uBlock/releases/tag/1.13.6>.
