### ISSUE TITLE
Allow sanitized url() input in style filters?

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#2752]
### Describe the issue

`url()` is not allowed by uBlock. Making impossible to fix background and such with `style()` filter.

### One or more specific URLs where the issue occurs

`http://pclab.pl/`

### Steps for anyone to reproduce the issue

1. Compare page with and without those filters after blocking ads css. 
```
||pclab.pl/css/extra
pclab.pl###spon_left
pclab.pl###spon_right
pclab.pl##.logoS:style(width: 275px; padding: 11px 0 0 5px; height: 74px; float: left;)
```
## Before
![screen shot 2017-07-02 at 20 11 39](https://user-images.githubusercontent.com/1126053/27772431-b9a5e6d2-5f62-11e7-9e0a-3ce47352633a.png)
## After
![screen shot 2017-07-02 at 20 11 04](https://user-images.githubusercontent.com/1126053/27772430-b99bd282-5f62-11e7-9b4a-c5634abfe1ed.png)
## Expected result 
(sort of, coz there is little tweaks to be made for positioning)
![screen shot 2017-07-02 at 20 23 15](https://user-images.githubusercontent.com/1126053/27772517-6667d8a2-5f64-11e7-8db2-2771d30841ca.png)
2. `.logoS` need to be fixed. And since `url()` is blocked we can't use 
```
pclab.pl##.logoS:style(width: 275px; padding: 11px 0 0 5px; height: 74px; float: left; background: url('/img/logo.png') no-repeat;)
```
Note that this is different logo than this in `extra` css. Different colors that match black sponsored background.

My suggestion is to allow first-party images in such cases. Adguard seem to allow that because there are filters using `url()` in their lists. But if you fell it is security concern to allow, we will live without logo I guess :>

-----
I use default + POL filters.

**Comment by uBlock-user** [comment]
@kasper93 if you're still looking for a way, I wrote a [scriptlet](https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L51) which can help you with that fyi.
