### ISSUE TITLE
Picker and zapper not available in FF read mode

### ISSUE THREAD

**Issue by petmue** [gorhill/uBlock#2754]
### Describe the issue

In the read mode "zipper" and "picker" are not available; however there is no reason to make them not available. For instance, the zipper is really helpful for removing elements (like images) before printing the page. 

### One or more specific URLs where the issue occurs

Each website, which offers a readmode. E.g.
`http://www.faz.net/aktuell/feuilleton/debatten/macron-regiert-neoliberal-15083366.html`

### Screenshot in which the issue can be seen

![screenshot](https://user-images.githubusercontent.com/16270886/27791332-c4805d8e-5ff4-11e7-9aaa-e42585651ce3.jpg)

### Steps for anyone to reproduce the issue

1. Open a website where the read mode is offered:
![spectacle tj7894](https://user-images.githubusercontent.com/16270886/27791375-fa8cf78e-5ff4-11e7-8a84-c144ca44325e.png)
2. Activate the read mode 
3. Click on the uBo Icon and find no zipper or picker

### My settings

- OS/version: Ubuntu 17.04 amd64
- Browser/version:  FF 54.0
- uBlock Origin version: 1.13.4

##### My filter lists

Default

**Comment by gorhill** [comment]
By design, uBO does not inject its content scripts in page which are not http/https. In reader mode, the URL address of the page you provide is `about:reader?url=http%3A%2F%2Fwww.faz.net%2Faktuell%2Ffeuilleton%2Fdebatten%2Fmacron-regiert-neoliberal-15083366.html`, not an http/https page.

**Comment by petmue** [comment]
> (see using "View Page Info"), not an http/https page.

I didn't know that, thanks.

But it is the zapper really about injecting scripts?

> Really, this feature is already supported by all browsers if one care to use the **developer tools** of the browser, however the purpose of the element-zapper is to make it easy for everybody to use: **highlight and click with no need to open the developer tools.**

In case you don't change your mind to make at least the zapper available in the read mode, I will have to go the laborious way by using the developer tools. :-(

> By design, uBO does not inject its content scripts in pages which are not http/https

In this case, it does not make much sense to allow users to click on the gray "power button" to "enable" uBlock on a non-http/https site, as this doesn't do anything. Right now it's possible.

Regards

**Comment by gorhill** [comment]
> it does not make much sense to allow users to click on the gray "power button" to "enable" uBlock on a non-http/https site, as this doesn't do anything. Right now it's possible.

Yes it does, uBO can still block network requests for that page.
