### ISSUE TITLE
[Firefox Linux] uBO not working on slideplayer.com

### ISSUE THREAD

**Issue by ntmlod** [gorhill/uBlock#2759]
### Describe the issue
Recently I switched to AdNauseam add-on in replace of uBO, it has been working for every page I browsed until the next URL.
First I was blaming AdNauseam before I realized uBO didn't work too.

### One or more specific URLs where the issue occurs
http://slideplayer.com/slide/3921940

### Screenshot in which the issue can be seen
The ads circling the slideshow are not hidden, few others ads in the page are still displayed.
[![AdNauseam_bug.jpg](https://s12.postimg.org/5x5pgr671/Ad_Nauseam_bug.jpg)](https://postimg.org/image/4i44s153t/)

### Steps for anyone to reproduce the issue
Nothing specific, just browsing the page.
But uBO blocks the ads from the same page under Chromium (1.13.2 version)

### Your settings
Restore uBO default settings via dashboard to confirm the issue
- OS/version: SL6.9 (RHEL6)
- Browser/version: Firefox 52.2.0 (64 bits)
- uBlock Origin version: 1.13.4

##### Your filter lists
Default filter lists

**Comment by anewuser** [comment]
Please close this issue.

You should report missing ads here instead: https://github.com/uBlockOrigin/uAssets

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
