### ISSUE TITLE
Logger: generic hiding rule recorded as active when $generichide in effect

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2763]
using 1.13.4 with Fanboy Ultimate list.

[Wired.com](https://www.wired.com/)  has a $generichide for the site (from EasyList). So I added a hiding rule that's generic in Fanboy Annoyances because it's obviously not applied in this case.

But when I click on the row in the Logger I see this:

![untitled](https://user-images.githubusercontent.com/14959062/27897874-db842ed6-61f0-11e7-8734-de68779e7ea1.png)

I'm surprised to see the generic listed alongside my rule in this case. It should only list my rule because of $generichide, right?

**Comment by gorhill** [comment]
The generic cosmetic filter is not really injected -- the logger is lying. The issue is with the reverse lookup code, it should ignore generic cosmetic filters it finds if they were ignored at injection time.

**Comment by uBlock-user** [comment]
Reproducible with the latest dev build on `kimcartoon.me`

`http://kimcartoon.me/Cartoon/Swat-Kats-The-Radical-Squadron/Season-01-Episode-001-The-Pastmaster-Always-Rings-Twice?id=15144`

![](https://i.gyazo.com/27f34997f08265759d93ffab2ac45b1c.png)

**Comment by gorhill** [comment]
> Reproducible with the latest dev build

I did not mark the issue as resolved.

**Comment by uBlock-user** [comment]
I know, but it occured to me today, so I posted as a reminder incase you forgot about it as it's on the second page now.

**Comment by gorhill** [comment]
Please no reminder, there are many pages of issues following the first one, I sure wouldn't want to be notified about all of these issues. I am fully aware of all the issues which are still opened.

**Comment by uBlock-user** [comment]
Okay, I deleted the posts.
