### ISSUE TITLE
Chromium OSX: ALT-L opens Logger and prevents input of @ char in any form element

### ISSUE THREAD

**Issue by COLABORATI** [gorhill/uBlock#2764]
On Chromium (freesmug edition) on mac OSX I can not input the @ char in any form element because that keyboard shortcut is hijacked by ublock origin and the logger window opens instead.

Also I can not find any option to disable or change this shortcut.

Thanks for your attention, great tool otherwise.

**Comment by gorhill** [comment]
Duplicate of #2723.
