### ISSUE TITLE
Dynamic filtering no autohide in Opera

### ISSUE THREAD

**Issue by FX54** [gorhill/uBlock#2765]
### Steps for anyone to reproduce the issue

1.  install clean Opera x64
2. install uBlock 1.13.6
3. activate Advanced user features 
4. deactivate Advanced user features
5. [Dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) hide after restart Opera

### OS / Browser / Addon

- OS/version:  Windows 7 SP1 Pro x64
- Browser/version:  46.0.2597.39 (PGO) x64
- uBlock Origin version:  v1.13.6

##### Your filter lists

Default filter lists + POL

##### Your custom filters (if any)

none

**Comment by gorhill** [comment]
You activated "advanced user" mode, as a consequence uBO showed the dynamic filtering panel.

You deactivated "advanced user" mode, as a consequence uBO hid the dynamic filtering panel.

Why do you think it is wrong?

**Comment by FX54** [comment]
> Why do you think it is wrong?

In FF or Chrome version this options (Dynamic filtering) hide without restart.

**Comment by gorhill** [comment]
Both Opera and Chrome behaves exactly the same: the dynamic filtering panel expand if one click "advanced user" mode. If you disable "advanced user" mode, the dynamic filtering pane becomes read-only, for informational purpose only. One can hide it again by clicking the "requests blocked" or "domains connected" bars.

**Comment by FX54** [comment]
Who shows if uBlock ignore with disable Advanced user features?
