### ISSUE TITLE
Refresh button in pop up uBO after block web font not work in Opera

### ISSUE THREAD

**Issue by FX54** [gorhill/uBlock#2766]
### Steps for anyone to reproduce the issue

1.  install clean Opera x64
2. install uBlock 1.13.6
3. Open website with web fonts i.e.  [arstechnica.com](https://arstechnica.com) or [dobreprogramy.pl](https://dobreprogramy.pl)
4. block web font in uBO
5. Click refresh button in ublock pop up, no changes
6. Must refresh with <kbd>Ctrl</kbd> + <kbd>F5</kbd> or open website in new tab

### OS / Browser / Addon

- OS/version:  Windows 7 SP1 Pro x64
- Browser/version:  46.0.2597.39 (PGO) x64
- uBlock Origin version:  v1.13.6

##### Your filter lists

Default filter lists + POL

##### Your custom filters (if any)

none

**Comment by gorhill** [comment]
By design, the webRequest is bypassed by the browser when a resource is present in-memory cache. Shift-click refresh allows to by pass the in-memory cache.

**Comment by FX54** [comment]
> Shift-click refresh 

button in pop up not full refresh with pressed shift.

<kbd>Ctrl</kbd> + <kbd>F5</kbd> ~ <kbd>shift</kbd> + <kbd>F5</kbd> in my tests... :disappointed:
