### ISSUE TITLE
Unable to search on forum.xda-developers.com

### ISSUE THREAD

**Issue by clementine123** [gorhill/uBlock#2767]
### Describe the issue
Running Firefox portable 54.0 (32 bit) and uBO 1.13.4. I have not subscribed to any filter subscription and when I perform a basic search on the page, I get a message saying:

"Whoops, search is taking a long time. Either there was an error or JavaScript was disabled. This can also happen if you use the NoScript or AdBlock browser extensions. If you're seeing this message in error, please alert the authorities. You can also use the Advanced Search page."

Folks at Adguard forums have also confirmed and have asked to report this issue to you. Please fix.

Thanks!

### One or more specific URLs where the issue occurs
forum.xda-developers.com

**Comment by gorhill** [comment]
All works fine here. You will have to be more generous about repro steps, other details. Where is that conversation with Adguard people? Why would you go to Adguard forums if you are using uBO?

**Comment by clementine123** [comment]
Any search term gets me to the same page with the message. I thought that this was an issue initially with Adguard filter subscription and that's why approached them to white list so that the search works fine but even after unchecking all the filter subscriptions (barebones) and after clearing cache and then checking, the search is not showing any result. By the way, the link to the adguard forum page : 

https://forum.adguard.com/index.php?threads/forum-xda-developers-com-ubo-on-ff.23077/


Also worth mentioning that I am using FF portable that I downloaded from here:

https://www.firefox-usb.com/

**Comment by gorhill** [comment]
> https://forum.adguard.com/index.php?threads/forum-xda-developers-com-ubo-on-ff.23077/

The CSP uBO injects if from EasyList's `|blob:$domain=...|xda-developers.com` filter, its purpose is to block blob-based URL. So it's a filter list issue, which should not have been opened here. In any case, I can't even reproduce this filter issue, and you keep failing to provide exact **detailed** steps-to-reproduce. Nobody can help you if you do not help other people to reproduce your issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by clementine123** [comment]
brother, relax ok. Your tone is quite rude and I have provided you with the information needed. Just because your extension is quite famous, does not mean you reply in this tone. 

I just checked and completely turned the extension off and still observed the issue. Please close this thread.

**Comment by gorhill** [comment]
> I have provided you with the information needed

Absolutely not, that **is** the problem. When asked to provide detailed steps-to-reproduce, provide them, do not decide unilaterally that they are not needed. Here is what I was faced with trying to repro your issue:

- Is logging in necessary?
- Which search button? (there are two).
- Which search term? (need to be sure that the search term is irrelevant)
- Screenshot of the page when it has the issue.
- What did the logger report?
- What did the browser console report?

You just plain deleted/disregarded the template, which contains a link to a good article explaining how to report issue: <https://www.chiark.greenend.org.uk/~sgtatham/bugs.html>. Excerpt:

> Summary
> 
> - The first aim of a bug report is to let the programmer see the failure with their own eyes. If you can't be with them to make it fail in front of them, give them detailed instructions so that they can make it fail for themselves.
> - In case the first aim doesn't succeed, and the programmer can't see it failing themselves, the second aim of a bug report is to describe what went wrong. Describe everything in detail. State what you saw, and also state what you expected to see. Write down the error messages, especially if they have numbers in.
> - When your computer does something unexpected, freeze. Do nothing until you're calm, and don't do anything that you think might be dangerous.
> - By all means try to diagnose the fault yourself if you think you can, but if you do, you should still report the symptoms as well.
> - Be ready to provide extra information if the programmer needs it. If they didn't need it, they wouldn't be asking for it. They aren't being deliberately awkward. Have version numbers at your fingertips, because they will probably be needed.
> - Write clearly. Say what you mean, and make sure it can't be misinterpreted.
> - Above all, be precise. Programmers like precision.

What is rude is to willfully ignore all this, this is volunteered-time wasting.

**Comment by clementine123** [comment]
> Absolutely not, that is the problem. When asked to provide detailed steps-to-reproduce, provide them, do not decide unilaterally that they are not needed. Here is what I was faced with trying to repro your issue:

Is logging in necessary? No, because if it were, I would have mentioned it in my post
Which search button? (there are two). Doesn't matter I had clearly mentioned it as a basic search (and not advanced search)
Which search term? (need to be sure that the search term is irrelevant) Would have mentioned if it were related to a search term
Screenshot of the page when it has the issue. Does not matter when the error is mentioned.
What did the logger report? Clearly mentioned that no filter subscriptions are used. No need to see the uBO log.
What did the browser console report? Not needed as the folks at adguard have checked and confirmed.

And yes, no body would like to ready your lengthy stories. You can keep it to yourself. I do not wish to continue this conversation with you.
