### ISSUE TITLE
https://bugzilla.mozilla.org/show_bug.cgi?id=1271354

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2768]
If memory serves me correct the bug patch I listed fixes the problem with getting to the dashboard and other things.  It has landed on inbound.  Not sure if it's on Fx Nightly yet.

https://bugzilla.mozilla.org/show_bug.cgi?id=1271354

**Comment by gorhill** [comment]
I am CC'ed on this bug, so I had received the notification this morning.

**Comment by bershan2** [comment]
For the record: this is about issue #2734.
