### ISSUE TITLE
Blocking of google-analytics.com increases page load time

### ISSUE THREAD

**Issue by Palf994** [gorhill/uBlock#2769]
### Describe the issue
I've found that there are several sites that load much more slowly with uBlock enabled than with it disabled. I tried disabling every single filter list, and I don't have any custom rules or filters, but the issue persisted. I then went through and added an 'allow' rule for each element that was blocked on the page one at a time. The only one that I found that significantly reduced page load time was google-analytics.com. I was using breitbart.com to test element blocking (because it's so busy and full of garbage elements) when I discovered the issue. I had to wait about 5 seconds after each reload to see the page. Creating an 'allow' rule for google.analytics.com reduced that page load time to around 2 seconds. I wish I could remember the other sites I was having trouble with before so that I could provide more examples and check if google-analytics.com is to blame for those slow loading speeds as well.

### One or more specific URLs where the issue occurs
http://www.breitbart.com/

### Steps for anyone to reproduce the issue

1. Reload Breitbart.com, noting reload time
1. Create 'allow' rule for google-analytics.com
1. Reload page, again noting reload time

### Your settings

- OS/version: OS X 10.11.6
- Browser/version: Google Chrome version 59.0.3071.115
- uBlock Origin version: v1.13.2

##### Your filter lists

Default filter lists + FRA + DE + I don't care about cookies

Note that this problem exists even with every single filter list disabled

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Though it may not be obvious, that is really a filter list issue (now fixed, force an update of _uBlock filters_) -- the site does not expect Google stuff to be blocked, and this is the result.

I still need to label the issue as "invalid" and "filter issue" for the sake of properly categorizing issue.

**Comment by Palf994** [comment]
Great, thanks for your response and for all the work you do on this excellent project!
