### ISSUE TITLE
uBlock conflicts with Honey extension, prevents Fandango.com from loading

### ISSUE THREAD

**Issue by KeronCyst** [gorhill/uBlock#2771]
### Describe the issue
Even after adding "www.earnhoney.com" to uBlock's whitelist: whenever uBlock and [Honey](https://chrome.google.com/webstore/detail/honey/bmnlcjabgnpnenekpadlanbbkooimhnj) are both active, the website www.fandango.com pulls up a white page with a perpetual loading wheel.

### One or more specific URLs where the issue occurs
www.fandango.com
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/13827055/27972365-f8ef5188-630a-11e7-987d-b677af9da951.png)

### Steps for anyone to reproduce the issue

1. Have both uBlock Origin and the [Honey](https://chrome.google.com/webstore/detail/honey/bmnlcjabgnpnenekpadlanbbkooimhnj) Chrome extension enabled.
2. Go to www.Fandango.com.

### Your settings

- OS/version: Windows 10 Home
- Browser/version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- uBlock Origin version: v1.13.2

##### Your filter lists

Whitelist:

about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
https://www.ebates.com/groupon_10634-xfas?AutoLoginID=C%2Ba%2Bg2prGv%2FMA5hnNm93Sg%3D%3D&tb=yes&sourceName=toolbar&eeid=23509&store_url=https%3A%2F%2Fwww.groupon.com%2Fdeals%2Fgg-running-belt-for-mobile-devices-1
https://www.ebates.com/walmart_2946-xfas?AutoLoginID=C%2Ba%2Bg2prGv%2FMA5hnNm93Sg%3D%3D&tb=yes&sourceName=toolbar&eeid=23509
https://www.topcashback.com/Misc/AdBlockWhiteList.aspx
loopconversation.about-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
www.ebates.com
www.joinhoney.com
www.secretflying.com

##### Your custom filters (if any)

My filters:

||ebates.com/global_files/js/abp/*
ebates.com###backgroundPopup
ebates.com###pjs-overlay
ebates.com##.ABP-container

My permanent rules:

no-strict-blocking: nox-app-player.en.softonic.com true
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop

My temporary rules: None

**Comment by gorhill** [comment]
Issue is not uBO.

The issue is with Honey, it removes the whole `body` element of the web page when network requests to 3rd-party `adobedtm.com` are blocked (by a filter in EasyPrivacy), you need to bring this issue to them.

Use the filter `@@||adobedtm.com^$script,domain=fandango.com` to fix the issue locally until they fix the issue in their own extension.

**Comment by KeronCyst** [comment]
Thanks for the rapid-fire response! I will notify the Honey staff.
