### ISSUE TITLE
Enable by default uBLock on Firefox about:addons page

### ISSUE THREAD

**Issue by John-Shaft** [gorhill/uBlock#2772]
By default uBlock is disabled on pages using the about: URI scheme on both Firefox and Thunderbird.

The addons menu on both software (about:addons) loads a page from addons.mozilla.org. This page is embedded with the Google Analytics tracker 

![firefox-addons-ublock](https://user-images.githubusercontent.com/29988810/27977467-2cf5b84a-636b-11e7-9934-b7c720363036.png)

As the use of GA seems intentional from Mozilla (see https://bugzilla.mozilla.org/show_bug.cgi?id=1302552#c1), I suggest that uBlock should be always enabled on the about:addons page on both Firefox and Thunderbird.

**Comment by hub2git** [comment]
I second this.

**Comment by lapineige** [comment]
@gorhill, could you explain the reason(s) why you declined this request ?
(I'm not here to challenge your decision, just to understand it)

**Comment by gorhill** [comment]
Make a comprehensive assessment that not whitelisting `about-scheme` is not going to cause _any_ issue on any browser in which uBO can be installed. I am the one who will be stuck with all the issues being opened if it turns out that **not** whitelisting `about-scheme` has a lot of unforseen negative consequences.

It's easy to merely just open an issue to ask me to do something. A _real_ contribution however goes beyond just opening an issue, it's going through all the efforts and taking the time to make a _comprehensive_ case that whatever is requested has been **thoroughly** assessed.

**Comment by John-Shaft** [comment]
First of all, sorry for the non-detailled first post. I made this request as I know Mozilla will tell me to GTFO - in a more polite way I guess - if I ask them to respect [their manifesto](https://www.mozilla.org/en-US/about/manifesto/#principle-04) and prevent that tracker to be loaded on the `about:addons` page. I'm aware that oher solutions exist (Using hosts file or lying DNS resolver, switch to IceCat...) but they are not trivial for non-tech users. Another solution is to raise awareness on this issue (I made a [blog post](https://www.shaftinc.fr/mozilla-vie-privee.html) in French - and considering translating it to English. But who reads my blog anyway ?).

As far as my testing goes, the Google Analytics script is one of the few things blocked by enabling uBlock on the `about-scheme` pages in Firefox and Thunderbird. On other pages than `about:addons` just a few of them make HTTP request (healthreport, accounts, credits...) and the only other things blocked so far on my configuration are :

- `no-spurious-csp-report	--	csp_report	https://discovery.addons.mozilla.org/__cspreport__` on the `about:addons` page
- `^metrics^	--	xhr	https://accounts.firefox.com/metrics` on the `about:accounts` page. It is triggered by the ABP Japanese filters which are known to be pretty aggressive

As for Thunderbird, the same tests bring the same results

This was tested on

- Windows 10 Pro x64 & Debian Buster
- Firefox 54.0.1 & Thunderbird 52.2.1 (only on Windows for TB)
- uBlock  1.13.4

With the filter lists : 

- FRA-0
- JPN-0
- easylist
- easyprivacy
- fanboy-thirdparty_social
- malware-0
- malware-1
- plowe-0
- reek-0
- ublock-badware
- ublock-filters
- ublock-privacy
- ublock-unbreak
- user-filters

If there is a way to blacklist `addons.about-scheme` while whitelisting all the other pages as it is possible in uMatrix, this would be a good solution.

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/issues/135#issuecomment-96677379> for an example on how not whitelisting `about` can cause unforeseen issue.

**Comment by gorhill** [comment]
Related: <https://github.com/mozilla/addons-frontend/issues/1107>.

**Comment by anewuser** [comment]
[Just a note](https://support.mozilla.org/kb/hello-status): 

>Firefox Hello has been discontinued and removed from Firefox starting with version 49.
