### ISSUE TITLE
stop ublock.org from riding on the coattails of uBo

### ISSUE THREAD

**Issue by hub2git** [gorhill/uBlock#2773]
### Describe the issue
https://en.m.wikipedia.org/wiki/UBlock_Origin says that ublock.org is asking for donations, even if it's a dead project.

Maybe it's just me. But a name with two words (ublock Origin) may seem derivative of its one-word counterpart (ublock). People may think that ublock Origin is a copycat of ublock(.org). People​ might think that ublock(.org) is the original.

Sidebar: which do you think came first: Coke Light or Coke?

Possible ideas: 
1. Gently ask ublock.org owner​ to transfer the site and the name to you. Email apologies to everyone who donated.
2. Gently ask them to change their name, so thay their new name will not have the word ublock.
3. Change ublock Origin’s name. Maybe change it into a one-word name. Like youBlock. Or iBlock. Then secure the trademark so that no one will create an intentionally similar name like ”Original youBlock”or iBlockYouBlockWeAllBlock.

### One or more specific URLs where the issue occurs
Ublock.org
https://github.com/chrisaljoudi/uBlock#getting-started
https://addons.mozilla.org/en-US/firefox/addon/ublock/

https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn

### Your settings

- OS/version: Linux mint for me. Windows 10 for my mom. 
- Browser/version: Firefox and Chrome/ium
- uBlock Origin version:  ublock(.org). Just kidding

**Comment by hub2git** [comment]
Also change logo and secure trademark.

**Comment by bershan2** [comment]
@hub2git This is a known issue, [README.md directly states that](https://github.com/gorhill/uBlock#beware-ublock-origin-is-completely-unrelated-to-the-web-site-ublockorg) (as well as the store descriptions).

1. >Gently ask ublock.org owner​ to transfer the site and the name to you. Email apologies to everyone who donated. 

    @chrisaljoudi had contributed to the original uBlock repository and @gorhill had transferred it to him because was annoyed by numerous _invalid_ bug reports, but then @chrisaljoudi started doing some bad stuff and their paths diverged. As a result, @chrisaljoudi owns the original repository (and thus the store listing) and it is hard to do anything about it. Most users had switched to uBO and those who did not probably simply do not know of this problem.

2. read 1
3. That would add even more confusion.

Trademark stuff is hard and requires lots of expenses and time. If you have a solid legal background or know someone who would take on this task for free, that could be helpful, otherwise your commoents here are noise.

Also, how do you think, is your report valid or invalid?

**Comment by bershan2** [comment]
Probably, notifying the free host provider `www.ebotservers.com` is the most that could be done without getting too deep into legal matters. But that is @gorhill's decision and authority, not yours or mine.

Please close this issue.

**Comment by hub2git** [comment]
@bershan2
 > Also, how do you think, is your report valid or invalid?
Invalid, for sure.

**Comment by gorhill** [comment]
There a whole lot of scammers out there using uBO in their scam (see <https://twitter.com/gorhill/status/871403572038119424>). The best defense is to just inform people, I am not going to complicate my life by spending energy on fighting any of these. Regarding ublock.org specifically, he is openly scamming people, he is just hurting himself really.
