### ISSUE TITLE
Default deny easily bypassed.. test page included!

### ISSUE THREAD

**Issue by jorvi** [gorhill/uBlock#2774]
### Describe the issue
Default deny turned on, yet going to [this](http://webkay.robinlinus.com/) page and taking a look at uBlock shows that pretty much all (!) third party resources get loaded.

### One or more specific URLs where the issue occurs
This site is specifically made to test privacy tools, so some things slipping through the cracks is expected but this is insane!
http://webkay.robinlinus.com/
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  macOS 10.12.5
- Browser/version: 59.0.3071.115 (64-bit)
- uBlock Origin version: 1.13.2

##### Your filter lists
Default deny mode + default lists + NLD list

Edit:
Stupid me, I forgot default deny only blocks 3rd party scripts and frames, but will show the concerning sites as 'connected' as long as default deny everything isn't turned on!

**Comment by bershan2** [comment]
@jorvi Since you had figured out the problem, please close this issue.
