### ISSUE TITLE
This add-on block sync feature of Firefox

### ISSUE THREAD

**Issue by dehghani-mehdi** [gorhill/uBlock#2775]
Hello,

### Describe the issue
Before installing uBlock I didn't have any issue about `sync` feature of Firefox. I installed uBlock @ home but not @ work, yesterday I updated my bookmarks @ home, but @ work didn't get that updates.

__BTW I'm familiar with sync, how to, ...__

### Steps for anyone to reproduce the issue
- Install uBlock
- Set the setting as `Hard mode`
- Update/Add some bookmark

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Same as [Blocking mode: hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode)

- OS/version: Windows 10 x64
- Browser/version: FF54.0.1
- uBlock Origin version: latest

I have not any other add-on installed @ home, @ work I installed some, I tired with add-on disabled, but still the same result.

Thanks.

**Comment by lewisje** [comment]
I thought that `behind-the-scene` was normally whitelisted, but maybe Firefox has a problem with this, or maybe Firefox Sync involves some connections that are seen as third-party but not as one of the whitelisted schemes, and are therefore blocked.

**Comment by gorhill** [comment]
It works just fine, if one is careful to configure rules appropriately after enabling hard-mode.

There this part in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

> Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to diagnose/confirm filter-related issues. If something does not work properly with uBO enabled, the **first step** is to rule out filter-related issues.

So little details provided in report, and no hint that the you tried to diagnose the issue yourself after enabling a rather advanced mode such as hard mode. Marking as invalid until there are real effort made to make the case, along with convincing evidence that there is an issue with uBO itself.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
