### ISSUE TITLE
Logger incorrectly shows all popups as blocked by one filter. 

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#2776]
### One or more specific URLs where the issue occurs

`http://raymondhill.net/ublock/popup.html`

### Screenshot in which the issue can be seen

![screen shot 2017-07-09 at 01 09 51](https://user-images.githubusercontent.com/1126053/27989846-68d0bea4-6443-11e7-8cfd-19c1110fa0e0.png)

### Steps for anyone to reproduce the issue

1. Open any page with popups.
1. Trigger popup that will get blocked. 
1. Trigger popup again. 

After first blocked popup every other popup that gets blocked or not will be shown as blocked by filter used to block first popup. See the screenshot where `about:blank` is not blocked and it is shown as blocked by the logger. 

### Your settings

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.13.7rc1

**Comment by bershan2** [comment]
@kasper93 Not sure what you expected to see... Are you surprised by the fact that the same filter can be applied multiple times? If so, that is the entire point of regular expressions. According to the filter syntax, `/AdHandler.aspx?` is equivalent to `*/AdHandler.aspx?*`, and `/adhandler.aspx?$popup` means all popups with URLs containing `/adhandler.aspx`, so popup `http://example.com/AdHandler.aspx?` does satisfy this criteria.

**Comment by kasper93** [comment]
> Not sure what you expected to see... 

I expect people to not troll, at least not on GitHub. I've tried to explain the issue the best I can. It is very obvious and apparent issue where logger assign all popups to one filter that happens to match first blocked popup. Instead of explaining how uBlock works, please take a closer look at the screenshot and hopefully you will see the bug.

**Comment by gorhill** [comment]
Pretty sure it's a regression from <https://github.com/gorhill/uBlock/commit/02323826950c7d99b65d93f9edb8fa018159973c>.

**Comment by kasper93** [comment]
@gorhill After refactoring `mapPopunderResult()` should return integer. 

``` diff
diff --git a/src/js/tab.js b/src/js/tab.js
index 95003969..0a3e586b 100644
--- a/src/js/tab.js
+++ b/src/js/tab.js
@@ -650,11 +650,11 @@ vAPI.tabs.onPopupUpdated = (function() {
         }
         var re = new RegExp(logData.regex),
             matches = re.exec(popunderURL);
-        if ( matches === null ) { return ''; }
+        if ( matches === null ) { return 0; }
         var beg = matches.index,
             end = beg + matches[0].length,
             pos = popunderURL.indexOf(popunderHostname);
-        if ( pos === -1 ) { return ''; }
+        if ( pos === -1 ) { return 0; }
         // https://github.com/gorhill/uBlock/issues/1471
         //   We test whether the opener hostname as at least one character
         //   within matched portion of URL.

```

**Comment by kasper93** [comment]
@gorhill: Actually it still fails. `popunderMatch()` calls `popupMatch()`, which can set `logData`, but `mapPopunderResult()` may reject the result and `logData` will still be defined.

I did this to clear `logData` if we have no match.

``` diff
diff --git a/src/js/tab.js b/src/js/tab.js
index 95003969..8ae80f4c 100644
--- a/src/js/tab.js
+++ b/src/js/tab.js
@@ -639,6 +639,7 @@ vAPI.tabs.onPopupUpdated = (function() {
 
     var mapPopunderResult = function(popunderURL, popunderHostname, result) {
         if (
+            result === 0 ||
             logData === undefined ||
             logData.source !== 'static' ||
             logData.token === µb.staticNetFilteringEngine.noTokenHash
@@ -650,11 +651,11 @@ vAPI.tabs.onPopupUpdated = (function() {
         }
         var re = new RegExp(logData.regex),
             matches = re.exec(popunderURL);
-        if ( matches === null ) { return ''; }
+        if ( matches === null ) { return 0; }
         var beg = matches.index,
             end = beg + matches[0].length,
             pos = popunderURL.indexOf(popunderHostname);
-        if ( pos === -1 ) { return ''; }
+        if ( pos === -1 ) { return 0; }
         // https://github.com/gorhill/uBlock/issues/1471
         //   We test whether the opener hostname as at least one character
         //   within matched portion of URL.
@@ -704,9 +705,6 @@ vAPI.tabs.onPopupUpdated = (function() {
     };
 
     return function(targetTabId, openerTabId) {
-        // https://github.com/gorhill/uBlock/issues/2776
-        logData = undefined;
-
         // Opener details.
         var tabContext = µb.tabContextManager.lookup(openerTabId);
         if ( tabContext === null ) { return; }
@@ -751,6 +749,11 @@ vAPI.tabs.onPopupUpdated = (function() {
             }
         }
 
+        if ( result === 0 ) {
+            // https://github.com/gorhill/uBlock/issues/2776
+            logData = undefined;
+        }
+
         // Log only for when there was a hit against an actual filter (allow or block).
         if ( µb.logger.isEnabled() ) {
             µb.logger.writeOne(
```

**Comment by kasper93** [comment]
I think `result` check in `mapPopunderResult()` would be more robust than relying that `logData` is cleared every time. But nevermind.

I'm still worried about this "second try" popunder match which will not be executed even when it should. You check `result !== 0` https://github.com/gorhill/uBlock/blob/7fb034f6403a6eec29c7f4946d28603510a86f71/src/js/tab.js#L690-L692 but `mapPopunderResult()` can return `''` in some code path. This looks like unwanted change in logic from refactoring commit, and will return too early from the `popunderMatch()` function.

**Comment by gorhill** [comment]
> I'm still worried about this "second try" popunder match which will not be executed even when it should.

Why should it? A match has been found, no point to keep trying to find another one.

**Comment by kasper93** [comment]
> Why should it? A match has been found, no point trying to find another one.

I'm talking about the case when the match is **not found**. The https://github.com/gorhill/uBlock/issues/1598 case.

These both cases will return `''` which will be wrongly interpreted:

https://github.com/gorhill/uBlock/blob/7fb034f6403a6eec29c7f4946d28603510a86f71/src/js/tab.js#L653
```
if ( matches === null ) { return ''; }
```

https://github.com/gorhill/uBlock/blob/7fb034f6403a6eec29c7f4946d28603510a86f71/src/js/tab.js#L657
```
if ( pos === -1 ) { return ''; }
```
---
`popunderMatch()` will return because `'' !== 0`
https://github.com/gorhill/uBlock/blob/7fb034f6403a6eec29c7f4946d28603510a86f71/src/js/tab.js#L690-L692
```
if ( result !== 0 )
```

----
Before the changes in  
https://github.com/gorhill/uBlock/commit/02323826950c7d99b65d93f9edb8fa018159973c#diff-ce215d94a52d449f1a34f292126608d7
the check was obviously `result !== ''` now that you return integer two return patch are incorrectly handled.

**Comment by gorhill** [comment]
> `if ( matches === null ) { return ''; }`

This is definitely wrong, I don't know how I missed this. This should be `return 0;`  following refactoring. Thanks for catching this.

**Comment by kasper93** [comment]
Damn, now I remember why I've added 
``` diff
diff --git a/src/js/tab.js b/src/js/tab.js
index 1454cc16..1a385236 100644
--- a/src/js/tab.js
+++ b/src/js/tab.js
@@ -639,6 +639,7 @@ vAPI.tabs.onPopupUpdated = (function() {
 
     var mapPopunderResult = function(popunderURL, popunderHostname, result) {
         if (
+            result === 0 ||
             logData === undefined ||
             logData.source !== 'static' ||
             logData.token === µb.staticNetFilteringEngine.noTokenHash
```

When first call to `mapPopunderResult()` returns 0, but `popupMatch()` have returned `!== 0` meaning `logData` is set, second call to `mapPopunderResult()` might use previous (from the first call) `logData`, if second `popupMatch()` returns 0 i.e not set `logData`.

Still the end result will be 0, because `result` is 0, but `mapPopunderResult()` will do some unnecessary work instead of returning at beginning.
