### ISSUE TITLE
Gorhill please read an actual issue with uMatrix

### ISSUE THREAD

**Issue by firefoxguy** [gorhill/uBlock#2777]
When spoofing a Windows user agent using uMatrix Ipleak.net is still able to detect I am using Linux "Platform: Linux x86_64" If I spoof using RAS it will say my platform is Windows with no issue. I couldn't post this under uMatrix issues because it has been removed. I'd really appreciate it if you look into this. Firefox 54.0.1 x64

With RAS
https://i.imgur.com/1adUwtS.png

With uMatrix
https://i.imgur.com/CiWLmrI.png

**Comment by gorhill** [comment]
Don't use UA spoofing with uMatrix, it's known issue, has been talked about a lot, and bottom line is that spoofing UA is pointless unless one also block all JS at the same time. I said I would remove this feature eventually, because it gives a false sense of privacy, given that as soon as javascript is allowed to execute, fingerprinting is the real issue, of which UA is only a tiny part of it. At most, I will releguate it to a toy feature with no privacy value.

**Comment by anewuser** [comment]
Please consider just adding a notice about it somewhere instead of removing it altogether.

It may not be perfect for people attempting to hide their real machine completely, but it works very well to get the mobile/tablet versions of websites on desktop browsers.

**Comment by DrunkenSasquatch** [comment]
> it gives a false sense of privacy

Very true. The order in which headers are sent are also unique to certain browsers. So, spoofing the UA actually has to opposite intended effect.

**Comment by shevegen** [comment]
Perhaps to the FAQ entry - we could add gorhill's answer above to build/expand to an FAQ entry actually. :) (I never heard of UA spoofing before by the way, probably some other people also never heard about it yet.)

**Comment by bershan2** [comment]
@anewuser User agent spoofing is already built into most major browsers:
https://www.howtogeek.com/113439/how-to-change-your-browsers-user-agent-without-installing-any-extensions
This might not be as easy, but at least someone won't be mislead by uMatrix feature.

**Comment by anewuser** [comment]
@bernd289 uMatrix isn't meant to be installed by users who are "mislead" by something like that in first place, and you seem not to understand the difference between changing your user-agent universally and setting a secondary user-agent only for specific websites - with only three clicks necessary for each of them.
