### ISSUE TITLE
How to block this anti adblocker? ITs a custom script.

### ISSUE THREAD

**Issue by AhsanE** [gorhill/uBlock#2779]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
This page is inaccessible with any adblocker.
https://mirole.com/ad/test.html
### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Windows 19
- Chrome
- Latest

##### Your filter lists
All
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by mapx-** [comment]
`||mirole.com/js/index.js$script`

**Comment by AhsanE** [comment]
does not work.

**Comment by mapx-** [comment]
I was testing mirole.com

try
```
mirole.com##script:inject(abort-on-property-read.js, _0x1673)
@@||mirole.com/*ad$image,script
@@||google-analytics.com$xmlhttprequest,domain=mirole.com
```

**Comment by bershan2** [comment]
@AhsanE try cleaning up the cache (opening Developer tools and clicking "Disable caching" should work). Probably, the unwanted JS is already in the cache (since you opened the page without a filter in the past) and thus the network request is not relayed to uBO.

**Comment by AhsanE** [comment]
where do i add mirole.com##script:inject(abort-on-property-read.js, _0x1673)
@@||mirole.com/*ad$image,script
@@||google-analytics.com$xmlhttprequest,domain=mirole.com ?

**Comment by bershan2** [comment]
Also, what is the "not detected" look of the page? In Firefox, if I completely remove all extensions and load the page, I see just this:
![untitled](https://user-images.githubusercontent.com/22861096/28032842-a02db1de-6571-11e7-8360-53679655526c.png)

**Comment by AhsanE** [comment]
its a country specific website, you cant see it

**Comment by bershan2** [comment]
@AhsanE 
>country specific website

Which country? I can use VPN.

**Comment by AhsanE** [comment]
A small asian country, you wont find vpn for that.

**Comment by mapx-** [comment]
Did you try the filters above ? 
go into options, "my filters" tab, add there the 3 filters.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
