### ISSUE TITLE
Which default whitelist items are needed for Firefox?

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#278]
Here are the current whitelist defaults:

behind-the-scene
chrome-extension-scheme
chrome-scheme
loopconversation.about-scheme
opera-scheme

**Comment by Snapy** [comment]
Here are the recommended ones to keep in FF :
`behind-the-scene` to allow browser features (Safe browsing, auto-update, sync...)
`chrome-scheme` to allow requests on chrome:// pages.
`loopconversation.about-scheme` if you want to use Firefox Hello service.

The following can be removed in FF :
`chrome-extension-scheme` to allow Chrome extension to perform requests...
` opera-scheme` is related to the Opera browser.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by lewisje** [comment]
On a slightly related note, I think `vivaldi-scheme` should be added by default, to support the Vivaldi fork of Chromium.
