### ISSUE TITLE
"Compatible with Firefox 57+" badge

### ISSUE THREAD

**Issue by kpcyrd** [gorhill/uBlock#2782]
uBlock is currently one of the three extensions I have installed and I'd like to get on the multi content process train as soon as possible. :)

I've noticed uBlock currently doesn't have this badge. It links to this page: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

I'm not sure if there's currently progress to this topic, or if it's blocked by anything. Infos would be appreciated. Thank you!

**Comment by kah0922** [comment]
[Check here](https://github.com/gorhill/uBlock/releases/tag/1.13.7rc3)

**Comment by gorhill** [comment]
uBO has been multiprocess-compatible since it was first published on AMO. The "Firefox 57" is about whether it is a full fledged WebExtensions. It's being worked on, there is a dev build available in _Releases_.

**Comment by kpcyrd** [comment]
Thanks!
