### ISSUE TITLE
YouTube behind-the-scene tracker not blocked using rule

### ISSUE THREAD

**Issue by domainedma** [gorhill/uBlock#2787]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Cannot block `https://www.youtube.com/youtubei/v1/log_event` and other YouTube trackers. 

When closing a YouTube video or homepage a connection to https://www.youtube.com/youtubei/v1/log_event is made.

This rule doesn't block the behind-the-scene request:

```
! behind-the-scene
||youtube.com/youtubei/v1/log_event$xmlhttprequest
```

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

https://www.youtube.com

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

`chrome://ublock0/content/logger-ui.html#`
```
xhr | https://www.youtube.com/youtubei/v1/log_event?alt=json&key=../
```

### Steps for anyone to reproduce the issue

1. Open YouTube.com in new tab
2. Open uBlock logger
3. Close YouTube.com tab
4. Observe requests made to YouTube.com
5. Block request using suggested rule from uBlock logger

Repeat steps after watching any video on YouTube and see if request blocked with new rule.

Note: This relates to the `behind-the-scene` request (the non-behind-the-scene request to this domain is blocked by EasyPrivacy)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Mac
- Browser/version: Firefox 56.01a 
- uBlock Origin version: 1.13.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Default filter lists + EasyPrivacy

##### Your custom filters (if any)
 N/A

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests
