### ISSUE TITLE
Chrome: uBlock Requires Additional Permissions

### ISSUE THREAD

**Issue by madranet** [gorhill/uBlock#279]
I wondered why I was suddenly seeing adverts this morning and, when I went into Chrome's preferences I found that uBlock was disabled. When I re-enabled it again, Chrome popped up an alert saying in effect:

```
uBlock has been disabled because the latest version requires additional permissions

* Read and change all your data on the websites that you visit
* Change your privacy related settings
```

I can't see anything about this in the release notes and the listed permissions _seem_ to be the same as what I remember them being before. So what gives?

**Comment by gorhill** [comment]
[_Privacy_  was added in 0.9.8.2](https://github.com/gorhill/uBlock/releases/tag/0.9.8.2).
