### ISSUE TITLE
InfNumFastPopsExpire Round 2

### ISSUE THREAD

**Issue by forkoz** [gorhill/uBlock#2791]
So primewire.ag redirects/popups are back with a vengance.

Previously you were able to set InfNumFastPopsExpire to 2020 or some other time and they would go away. Now advancing the date causes the redirect immediately. Setting it back is safe while sitting on the page but it gets re-created if you click anything.

Filters are useless because a bunch of random character domains were registered and they rotate.
ie. http://153105c2f9564.com/1304358.html?q

A new variable is also there: InfNumFastPops Not sure what it does.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
