### ISSUE TITLE
Bugzilla issues affecting uBlock Origin webext

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2795]
A placeholder issue to track all open issues on [bugzilla.mozilla.org](https://bugzilla.mozilla.org/) affecting the webext version of uBlock Origin:

- ~[1367494](https://bugzilla.mozilla.org/show_bug.cgi?id=1367494): [BrowserAction] properties supported on desktop but not android should warn rather than prevent installation~~
    - This is what is preventing uBO/webext from being installed on Firefox for Android.
    - uBO/webext can't be released on the stable channel of AMO as long as the fix is not in a stable release of Firefox for Android. 
    - **Update:** fixed with <https://bugzilla.mozilla.org/show_bug.cgi?id=1367494>, so not a showstopper anymore.
- ~~[1360285](https://bugzilla.mozilla.org/show_bug.cgi?id=1360285): URL values not normalized to ASCII in WebExtensions API~~
    - I will add workaround code in uBO until issue is fixed.
    - [Test page](http://raymondhill.net/ublock/idn-tricks.html): uBO does not list all hostnames on that page without the workaround code.
    - **Update:** workaround code works just fine, not a blocking issue.
- [1313401](https://bugzilla.mozilla.org/show_bug.cgi?id=1313401): Background Page LocalStorage is cleared along with site storage
    - This prevents uBO from remembering some UI preferences, but especially this breaks "Advanced settings".
    - **Update:** I do not consider this issue to be a showstopper for publishing webext-legacy on stable channel on August 22nd.

**Comment by sabret00the** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=945240 landed which apparently negates the need for https://bugzilla.mozilla.org/show_bug.cgi?id=1360285

**Comment by streetwolf** [comment]
How about: https://bugzilla.mozilla.org/show_bug.cgi?id=1379148

**Comment by leplatrem** [comment]
Even if it's well documented in your wiki, I just opened [1386988](https://bugzilla.mozilla.org/show_bug.cgi?id=1386988): Confusing Legacy label for Embedded WebExtensions addons

**Comment by chetgurevitch** [comment]
[1367494](https://bugzilla.mozilla.org/show_bug.cgi?id=1367494) is fixed for firefox 55.

**Comment by gorhill** [comment]
@leplatrem Not sure they can do anything about this. An embedded webext can be complete or partial.

uBO is a [complete webext](https://github.com/gorhill/uBlock/blob/master/platform/webext/manifest.json) except for the data migration legacy code executed once at first install.

On the other hand I do know that ABP 2.9.1 is declaring `hasEmbeddedWebExtension` but the only webext API used [is `browser.storage.local`](https://github.com/adblockplus/adblockplus/blob/master/webextension/manifest.json), so it's still mostly a legacy extension

**Comment by chiraag-nataraj** [comment]
One thing which isn't exactly a webext problem but the webext migration will cement: handling noscript. Before, you could use browser preferences to set it up so that javascript was _actually_ disabled on certain sites (see [here](http://www-archive.mozilla.org/projects/security/components/ConfigPolicy.html)). However, the new webext API won't provide access to browser preferences, which means this won't be fixable.

**Comment by lizzard** [comment]
We are seeing a very  high volume crash on Firefox for Android 55, the current release, with the 1.14.4 version of uBlock: https://bugzilla.mozilla.org/show_bug.cgi?id=1347984#c30

**Comment by Luke-Baker** [comment]
~~[1271354](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354)~~ is fixed in Firefox 56. [Wiki - Firefox WebExtensions](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#differences-with-ubolegacy) says it's the reason it's no longer possible to block requests from other extensions.

**Comment by gorhill** [comment]
Actually I will close this issue since uBO/webext version has been release since early September. Any remaining issues will be documented in the wiki.
