### ISSUE TITLE
Upgrading to latest pre-release reset all settings and filter lists

### ISSUE THREAD

**Issue by troysjanda** [gorhill/uBlock#2796]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
upgrading to the latest pre-relese from stable webext version reset all settings and filterlists. did not replace previous version but installed a 2nd extention in the addons menu.

### One or more specific URLs where the issue occurs
na
[URL(s) for issue on a specific site are **mandatory**]
na
### Screenshot in which the issue can be seen
no
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
default settings, with advanced user enabled
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: Firefox esr 52.2.1
- uBlock Origin version: 1.13.9b0 from stable1.13.8

##### Your filter lists
fanboy annoyence, social, and tracking, stevenblack list
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
! 7/19/2017, 2:27:09 PM https://betanews.com/
betanews.com##.clearfix.articleBreak

! 7/19/2017, 2:27:46 PM https://sports.yahoo.com/
||s.yimg.com/cv/ae/default/170711/MLB_AllStar_974x80.jpg$image

**Comment by Betsy25** [comment]
All worked fine here on system below : 

*    OS/version: Windows 7
*    Browser/version: Firefox Nightly 56
*    uBlock Origin version: 1.13.9b0 from stable1.13.8

**Comment by gorhill** [comment]
> Browser/version: Firefox esr 52.2.1

Read [Release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.9b0) please.
