### ISSUE TITLE
Cannot install uBlock0.firefox.xpi per https://github.com/gorhill/uBlock/releases/tag/1.13.9b0

### ISSUE THREAD

**Issue by Grossdm** [gorhill/uBlock#2797]
Firefox for Android version 54.0.1

I was just upgraded to the hybrid webext version of uBO, 1.13.9b0.
The lack of user interface makes it unusable, so I tried to install uBlock0.firefox.xpi per the suggestion I the release notes.
Apparently, uBlock0.firefox.xpi is unsigned, and Firefox refuses to install it.
Is it possible to sign this xpi, or does Mozilla do the signing after they deem your addon worthy?

There was a preference that could be set in about:config that showed installation of unsigned addons, but this is no longer available.

**Comment by gorhill** [comment]
Install the [stable version from AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/).
