### ISSUE TITLE
Issues with visual page loading behavior (Firefox WebExtension)

### ISSUE THREAD

**Issue by Lurtzae** [gorhill/uBlock#2798]
### Describe the issue
Some sites show strange visual page loading behavior when using uBlock Origin as a WebExtension in Firefox (Nightly). 
I never wanted to report this because it seems to depend on cosmetic filtering and possibly some filter lists, but it's been there for months, only in Firefox WebExtension and has never gone away.

### One or more specific URLs where the issue occurs
https://www.e-reader-forum.de/

### Screenshot in which the issue can be seen
https://abload.de/img/forumvzqc1.gif

### Steps for anyone to reproduce the issue
-Ensure Parse and enforce cosmetic filters is enabled. 
-Open a site like https://www.e-reader-forum.de/
-Reload the site (it should show the reported behavior with the first reload after opening the site)

### Your settings
- OS/version: Windows 10 15063.483 64bit
- Browser/version: Nightly 56.0a1 (2017-07-19) (64-bit)
- uBlock Origin version: 1.13.9.0

##### Your filter lists
uBlock filters
uBlock filters – Privacy
Adblock Warning Removal List
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Fanboy’s Annoyance List
Fanboy’s Social Blocking List
Peter Lowe’s Ad and tracking server list
DEU: EasyList Germany

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
> strange visual page loading behavior

You need to be more specific, I have no idea what you look for, I can't read mind. Site loads just fine for me.

**Comment by Lurtzae** [comment]
It's hard to describe, that's why I added the animation. 
The elements kind of morph slowly into the site, instead of loading instantly in their correct form.

**Comment by gorhill** [comment]
Nothing to do with uBO, it's just the browser reading CSS resources and as it gets them it applies them.

**Comment by gorhill** [comment]
Even bypassing the cache, I can't get what you see. It's like you have a combination of slow PC, slow connection, disabled browser cache. Any other extension installed?

**Comment by Lurtzae** [comment]
Very strange. It's only happening with Firefox WebExtension, even with a completely new profile. Never could reproduce this otherwise, not even with high CPU load. 

It's the same on my desktop with an i7 6700k and a 50 mbit/s connection. Browser cache is enabled. 

I only have WebExtensions installed, nothing that could interfere with uBlock Origin I think. Foxy Gestures, FoxyTab and TabAutoRefresh. 

It only happened after the mentioned discussion board switched to http/2. Don't know if that could have anything to do with it.

**Comment by gorhill** [comment]
I added Foxy Gestures, FoxyTab and TabAutoRefresh and still can't reproduce. I disabled multiprocess and still can't reproduce.

What may help is if you profile using Gecko profiler, but that is rather technical. Maybe this could help finding out why reading/applying the CSS resources take so long on your side.

**Comment by Lurtzae** [comment]
Gecko Profiler shows a lot of event processing delay in the content process that renders the site. However I have no idea how to interpret the results further than that. 
Maybe a Bugzilla is justified.

**Comment by gorhill** [comment]
Can you share the URL to the profile?

**Comment by Lurtzae** [comment]
https://perfht.ml/2vmzvKd

**Comment by gorhill** [comment]
I see uBO using ~20 ms in content process for your `e-reader-forum.de` page, out of over ~700 ms page load. uBO consumes even less CPU in the extensions process. Disabling cosmetic filtering for that site should remove most uBO overhead from content process, but as said, it's already low, so this should make no difference.

It appears you enabled out-of-process extensions on your side? In any case, I enabled it on my side and this made no difference.

I think these profiling results should be looked at by Firefox devs, but as far as I can tell, uBO proper is not causing this.

**Comment by Lurtzae** [comment]
Yes it's enabled. But it's been happening for months, when out-of-process extensions weren't even in Nightly.

**Comment by Lurtzae** [comment]
Made a new profile now and installed uBO from development channel. Couldn't reproduce. Maybe some kind of data migration issue from the legacy version?

**Comment by gorhill** [comment]
From what I see in the main thread, it seems there is a lot time spent to communicate with the OOP extensions process, but only Firefox devs would be able to see if there is something abnormal.

**Comment by gorhill** [comment]
Maybe you could try disabling OOP in the profile in which you have the issue and see if this changes anything? (to help narrow the problem)

**Comment by Lurtzae** [comment]
No difference whatsoever. Even if i disable multiprocess completely in Nightly it remains the same.

**Comment by Lurtzae** [comment]
I deleted everything from my existing library profile that was connected to uBlock Origin. Then I reinstalled uBlock Origin from development channel and enabled my usual options. 

It was working fine. 

After another restart, the issue is showing again and won't disappear. There seems to be some interaction in my configuration, but I can't figure out what it could be.

**Comment by gorhill** [comment]
> enabled my usual options

What are these options?

**Comment by Lurtzae** [comment]
The described filters, cloud storage support and advanced user option. 

FYI, kmag from Mozilla thinks this is mainly a site issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1382653#c3

**Comment by gorhill** [comment]
That's interesting. I went to try to reproduce and just realize I was testing with my global block rule to `fonts.googleapis.com` still in effect (my bad). After I remove that rule, I now see a marked difference in how the page render when I force reload. So it looks like it's whether the font resources are loaded or not that makes a difference.

**Comment by Lurtzae** [comment]
Just a quick update: 
The issue seems to be gone with uBO 1.13.9.2 and Nightly 2017-07-24.
