### ISSUE TITLE
[Question] What's the frequent the filter it's autoupdate ?

### ISSUE THREAD

**Issue by DjDiabolik** [gorhill/uBlock#2802]
I have look at my dashboard about 5 minutes ago.... i see some filter reported whit "!" symbol it's reported it's not updated in about one week.

I have need to do a "force" update and i have the option activate to autoupdate this filter and my question it's..... because this append ?

What's the default interval to check this updates ? 5 days ? One Week ? One Months ? I can set this value in some mode ?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
The [source code](https://github.com/gorhill/uBlock/blob/20346ef0edd44a827c27148b66d0a2cc7b5be55e/src/js/storage.js#L732) appears to look for a line of the form `!Expires: <number> days` to figure out how frequently to update, but it will not update more than once per two days; [another file](https://github.com/gorhill/uBlock/blob/1c7c703d8ba99d1f05bd5be2431878b72c937233/src/js/assets.js#L365) indicates that the default expiration time is 5 days, and [the built-in list of resources](https://github.com/gorhill/uBlock/blob/42c9928abdbe51658ea4f34958ab02359f5666b1/assets/assets.json) specifies the `updateAfter` values in days.

**Comment by DjDiabolik** [comment]
Thanks for great info.........and sorry for this "wrong place" question.........
