### ISSUE TITLE
Dashboard has new url in latest beta

### ISSUE THREAD

**Issue by Endor8** [gorhill/uBlock#2803]
Hi.
Since uBlock Origin/webext 1.13.9b0 the Dashboard url
is changed from
chrome://ublock0/content/dashboard.html
to
moz-extension://26fac72f-17c3-4db6-cf00-24a400d1f46d/dashboard.html 
is this intentional or related to webextension?

**Comment by gorhill** [comment]
It's related to WebExtensions. Extensions no longer choose their own id in the URL.
