### ISSUE TITLE
uBlock Protector Extension - Error

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock#2804]
When browsing itavisen.no, I get the following error message:

> The uBlock Protector Extension caused that the page stopped working.
Please try to disable it and reload the page.

This despite the fact that I'm not using the 'uBlock Protector' extension.

Link:
http://itavisen.no/

Screenshot:
https://www.mediafire.com/convkey/1ef2/67dicb7v6644ccd6g.jpg

Active filters:
All of them, except for these:
* uBlock filters – Experimental
* EasyList without element hiding rules​​​​​​​​​
* Regional filters

(I'm also using some filters of my own, but disabling them didn't help)

OS:
Windows 8.1 Pro, x64

Browser:
Pale Moon v27.4.0, x64

uBlock Origin:
v1.13.8

**Comment by okiehsch** [comment]
The reason this site thinks you use the `uBlock Protector Extension`
are the filters
````
##CLOUDFLARE-APP[app-id="no-adblock"]
##.adbmodal-cloudflare-app-container
````
in `Fanboy’s Enhanced Tracking List`, you can disable them or add
`itavisen.no##script:inject(abort-on-property-read.js, CloudflareApps.installs)`
to your own filter list.

**Comment by jspenguin2017** [comment]
Their detection is broken, if you actually use my extension, you won't get that.

**Comment by jspenguin2017** [comment]
Are you using AAK-Cont? That has a logic that can be caught in their detection...

**Comment by THEtomaso** [comment]
Thanks a lot for your explainations guys.
Adding that line to my own filter list did the trick, but I might end up deleting it and install 'uBlock Protector' instead! :)

**OFF TOPIC:**
@ gorhill and jspenguin2017:
In light of the upcoming, rather drastic Firefox changes..
Have you considered hosting your extensions at Pale Moon's site?:
http://addons.palemoon.org/extensions/
I think this would make a lot of people very happy, since Pale Moon currently seems to be the only Mozilla-based browser with realistic prospects for the future.
Even Giorgio Maone started hosting his 'NoScript' extension at palemoon.org a few days ago!

**Comment by jspenguin2017** [comment]
Unfortunately, uBlock Protector is Chrome only, it is on the store [here](https://chrome.google.com/webstore/detail/ublock-protector-extensio/ggolfgbegefeeoocgjbmkembbncoadlb). 

Blowing up `CloudflareApps.installs` will work, I'd say most of the time. But it can cause some sites to break. I go with a generic route and interfere with a scripted solution, which only disables NoAdBlock and not other Cloudflare apps.

**Comment by jspenguin2017** [comment]
`ads.js v2` found on `palemoon.org`.

**Comment by THEtomaso** [comment]
> they have anti-adblocker script on their own website.

Yeah, I've blocked those elements myself.
..but you really shouldn't judge Pale Moon simply based on that minor annoyance.
The author has explained himself in that regard in the official forum many times, and the browser itself is probably the cleanest one that you'll ever try!
Even all of Mozilla's telemetry codes has been completely removed at this point, which Moonchild back in 2015 described as a "real mountain" of data:
https://forum.palemoon.org/viewtopic.php?f=4&t=9033&p=61077#p61077

In comparison, since you're building an extension that is compatible with Google Chrome yourself, I assume that you're familiar with how incredibly invasive a browser can be!

The main reason why Pale Moon has a future, as opposed to other Mozilla-based browsers, is this:
http://www.moonchildproductions.info/goanna.shtml

**Comment by jspenguin2017** [comment]
Chrome obeys instructions from my extension as expected, I never had any problem, Firefox, on the other hand, gets in my way with its broken CSP handling, I don't know how Pale Moon acts about this, but since it is a Firefox fork, it should act similarly. 

Blink, the rendering engine of Chrome is also open source, I don't see why Pale Moon's rendering engine would be better as Blink is maintained by top engineers of the world.

**Comment by jspenguin2017** [comment]
> Yeah, I've blocked those elements myself. 

They may randomize it from day to day, that's how `ads.js v2` works. I use a scripted solution to patch `getElementById` to shut it down for good.

**Comment by THEtomaso** [comment]
> Firefox, on the other hand, gets in my way with its broken CSP handling

Judging from PM's changelogs, a lot of work has been done in that department, distancing it from Firefox.
I don't know much myself when it comes to those kind of technicalities, but I highly recommend that you try the browser yourself.
You don't even have to install it, as there are official portable builds available as both 32-bit and 64-bit versions.

--

> They may randomize it from day to day

Hasn't happened yet.

Anyway, we seem to have gotten way off topic here! :)

**Comment by jspenguin2017** [comment]
I see that NoAdBlock updated their code and removed the detection, the cosmetic filter should be once again safe to use in a few days.

**Comment by THEtomaso** [comment]
> I see that NoAdBlock updated their code and removed the detection, the cosmetic filter should be once again safe to use in a few days.

Confirmed fixed now! :)
