### ISSUE TITLE
Can't search when search term starts with install

### ISSUE THREAD

**Issue by treaves** [gorhill/uBlock#2805]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I open a new tab, and start typing into the search field.  Search for 'install rmate'.  Once I hit the 's' key, and get a blocked URL
"uBlock Origin has prevented the following page from loading:
http://insight.adsrvr.org/
Because of the following filter
||adsrvr.org^
Found in: Peter Lowe’s Ad and tracking server list"

### One or more specific URLs where the issue occurs
Just open a new Safari tab and type.

[URL(s) for issue on a specific site are **mandatory**]
'install rmate'

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
open a new Safari tab
type: inst

**Comment by gorhill** [comment]
> open a new Safari tab

This is not the place for Safari issue, the Safari version is not mantained here. Go to <https://github.com/el1t/uBlock-Safari#ublock-originfor-safari>.
