### ISSUE TITLE
Privacy options are inactive in 1.13.9b0

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#2806]
### Describe the issue
Privacy options are inactive and gray out in 1.13.9b0, in 1.13.8 all works fine.

### One or more specific URLs where the issue occurs
Not important

### Screenshot in which the issue can be seen
Not important

### Steps for anyone to reproduce the issue
1. Open the dashboard in Options tab;
2. The Privacy options are inactive;

### Your settings
- XP: 
- Firefox ESR 52.2.1: 
- uBlock Origin version: 1.13.9b0;

##### Your filter lists
Default filters;

##### Your custom filters (if any)
None;

##### Screenshot
______________________________________________________________________________________________________
![w90oyb](https://user-images.githubusercontent.com/13637587/28450690-24363062-6de9-11e7-99df-7531f4a0a1c7.png)
______________________________________________________________________________________________________

**Comment by FatOrangutan** [comment]
>Firefox ESR 52.2.1  
  
See the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.9b0), specifically:  
  
>For all those Firefox and Firefox-based browsers based on Firefox v53 and less, the dev channel of uBO will cease to work, and they will have to install manually the xpi version from the repo here if you want to keep using the dev version of uBO, or install the stable version of uBO on AMO.

**Comment by happysurf** [comment]
Sorry, thank you for the info.

**Comment by gorhill** [comment]
Minimum version was still set at 52 in manifest, changed it to 54, so there should be a warning on AMO about the incompatibility.
