### ISSUE TITLE
*anime*.*##* for myanimelist.net is not working 

### ISSUE THREAD

**Issue by Aonavan** [gorhill/uBlock#2807]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

`*anime*.*##*` doesn't block `myanimelist.net`.

It's should show only white screen, without anything, like with `myanimelist.net##*` filter.

### One or more specific URLs where the issue occurs

https://myanimelist.net

### Screenshot in which the issue can be seen

https://a.pomf.cat/xllauc.png

### Steps for anyone to reproduce the issue

1. Add  `*anime*.*##*` filter.
1. Go to myanimelist.net
1. See that page isn't completely blocked, it's should've been showing white screen only, like with `myanimelist.net##*` filter.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10.0.15063.483 (1703)
- Browser/version: 54.0.1
- uBlock Origin version: 1.3.8

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Default + uBlock filters – Experimental + Adblock Warning Removal List + Anti-Adblock Killer | Reek + Fanboy’s Enhanced Tracking List + Fanboy’s Annoyance List

##### Your custom filters (if any)

 `*anime*.*##*`

**Comment by gwarser** [comment]
Not supported. Only format like `anime.*##.asdf` will work https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#entity-based-cosmetic-filters (UBO extension)

**Comment by gorhill** [comment]
> `*anime*.*##*` doesn't block `myanimelist.net`

Nowhere in the documentation whether [here](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#entity-based-cosmetic-filters) or at [ABP Filter Syntax](https://adblockplus.org/filter-cheatsheet#elementdomains) does it say wildcards are supported like this.
