### ISSUE TITLE
The developer should write better descriptions

### ISSUE THREAD

**Issue by autocorrect88** [gorhill/uBlock#281]
Or maybe have it preconfigured in 4 choices depending on how much privacy and stuff people want.  because right now it's confusing.  ALSO WRITE BETTER DESCRIPTIONS FOR EACH ONE.  

AND LOSE THE ATTITUDE.

**Comment by CrisBRM** [comment]
You should be more respectful. 
Instead of demanding he caters to your every whim, realise he does it for free, on his own time, and your imbecilic self didn't even take the time to make a proper constructive suggestion. It is thanks to people like you that he decided to fork his own extension in the first place, and I don't blame him -- I, too, would have been driven insane if I had to deal with inane ingrates like yourself.

**Comment by TeddStriker** [comment]
What isn't clear exactly? Sure, it could be made simpler, what is it that you don't understand and find confusing? A blanket statement like that helps no one, you should try and be more specific about what you think needs improving. 

>AND LOSE THE ATTITUDE. 

You, could, you know, just forк it without the attitude?

**Comment by gorhill** [comment]
> preconfigured in 4 choices depending on how much privacy and stuff people want

No, it's an install and forget extension, I made a conscious choice to have the extension get out of teh way immediately after install -- as opposed to other blockers. It's by design.

**Comment by autocorrect88** [comment]
//

**Comment by autocorrect88** [comment]
i don't know what boxes to tick off.  it's just a clusterfuck.  

1.  [Fanboy+Easylist-Merged Ultimate List‎] - 

i.  does  include EasyPrivacy?
ii.  does it include "fanboy's social blocking list" + "fanboy's annoyance list" + "fanboy’s enhanced tracking list" + anti-thirdpartysocial (which is also from fanboy) ??

2. Malware domains
i. do i tick off all four? 

3.  Multipurpose
i. Dan Pollock’s hosts file‎ - ???
ii. hpHosts’s Ad and tracking servers‎ - ???
iii. MVPS HOSTS‎ - ???

4. Peter Lowe’s Ad server list‎ - ???

I still see ads on YouTube, on Outlook.com, in Gmail, on SFGate.  

I'm thinking I should go with Norton Security 2015.

**Comment by TeddStriker** [comment]
>does it include EasyPrivacy?

If you click on the list name, you will get an asset, where all the lists are located. I just went in it and searched for easy-privacy and found it there.
>!-----------------General tracking systems-----------------! ! *** easylist:easyprivacy/easyprivacy_general.txt ***

They *could* be listed a bit clearer, I'd give you that, but I hardly consider this a huge issue.

>Malware domains: which ones am i supposed to choose? 

That's up to you I guess, there are domain names next to the lists where you can get more information on the list in question.

>I see ads on YouTube, on Outlook.com, in Gmail, on SFGate. 

That is dependent on the lists you have selected, I don't see ads on either of those sites.

**Comment by gorhill** [comment]
To add to @TeddStriker's answer, the lists are best described by their respective maintainers. So for [Fanboy Ultimate List](https://www.fanboy.co.nz/filters.html):

> This includes Easylist, Easyprivacy, Enhanced Trackers List and Annoyances List
