### ISSUE TITLE
"Storage used" in settings tab says "? bytes"

### ISSUE THREAD

**Issue by yasmise** [gorhill/uBlock#2812]
### Describe the issue
In uBlock Origin 1.13.9.0, "Storage used" in settings tab says "? bytes", as shown in a screenshot below. Stable (1.13.8) says correct value.

### One or more specific URLs where the issue occurs
moz-extension://1926ce9b-fc7f-4e3c-b002-048c0f16ae31/dashboard.html#settings.html

### Screenshot in which the issue can be seen
![screenshot](https://user-images.githubusercontent.com/22886576/28487187-877c5dd0-6ec6-11e7-8c47-696c9a10a7aa.png)

### Steps for anyone to reproduce the issue
1. Open "Dashboard" of uBlock Origin and go to "Settings" tab.
2. "Storage used" doesn't say correct value.

### Your settings
- OS/version: Windows 10 Home 1703
- Browser/version: Firefox 54.0.1 64bit
- uBlock Origin version: 1.13.9.0

I can reproduce this with a clean Firefox profile. Only uBlock Origin is installed.

##### Your filter lists
Default filter lists + JPN

##### Your custom filters (if any)
Nothing

**Comment by gorhill** [comment]
`browser.storage.local.getBytesInUse()` is not supported by Firefox's WebExtensions API: <https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/getBytesInUse>.

**Comment by uBlock-user** [comment]
Issue still exists in FF 57 Nightly.

Do they have any plans of adding it ?

**Comment by yasmise** [comment]
FYI, Bugzilla's URL is here.
https://bugzilla.mozilla.org/show_bug.cgi?id=1385832
