### ISSUE TITLE
[Chrome] Image download fails with "Failed - Blocked" with no-large-media enabled with small max size

### ISSUE THREAD

**Issue by rctdude2** [gorhill/uBlock#2813]
### Describe the issue
When no-large-media is enabled, attempting to download an image with a filesize greater then the max size specified in uBlock fails with a "Failed - Blocked" error. uBlock DOES NOT block the image when accessed directly, only if you attempt to download it.
This only appears to happen in Chrome, as I don't recall this happening in Firefox.

### One or more specific URLs where the issue occurs
Any image with a filesize greater than the max size works.
Example: https://konachan.net/post/show/232141/

### Steps for anyone to reproduce the issue
For the example image above:

1. Enable blocking large media elements with a small max size (e.g. 2048, but anything works as long as it's less than 7MB).
1. Go to link above, see that the preview image loads fine. (Note: clicking on "View larger version" on the message at the top will work as it loads the smaller JPG file, not the larger PNG file).
1. In the sidebar, under options, click "Download PNG"; see that full size image loads fine when accessed directly.
1. Attempt to save image. Download fails with "Failed - Blocked" error. Disabling uBlock/no-large-media fixes issue.

### Your settings
- Notably, no-large-media enabled with max size set to 2048kb
- OS/version: Windows 7
- Browser/version: Chrome 59.0.3071.115
- uBlock Origin version: 1.13.8

##### Your filter lists
Everything but experimental, unbreak, AAK, EasyList w/o elem, uBlock protector, merged ultimate, and regionals.

**Comment by gorhill** [comment]
Unable to reproduce, all working as expected. There is no 7 MB or even 2 MB image at the link you provided. Largest image is ~500 KB. If I use 100 KB as the max size, the image is correctly blocked.

**Comment by gorhill** [comment]
Sorry, misread the whole thing.

At step 4 the image loads fine because the browser is downloading the image as a document (in its own tab).

At step 5, the download fails because the browser is downloading the image as an image. There is no way for uBO to know that the image was downloaded as a result of "Save as".

Solution: right-click over the page, and select + "Temporarily allow large media elements".

**Comment by gorhill** [comment]
I am investigating what could be done at step 5 to prevent the large-media-elements blocking code from interfering when the document in the current tab is itself a media element.
