### ISSUE TITLE
请问下屏蔽所有图片该怎么写规则呢，不区分网站

### ISSUE THREAD

**Issue by piaoyun** [gorhill/uBlock#2814]
只要是在这个浏览器下面的，访问过的所有网站的，图片格式的图片，全部屏蔽

包括：png、jpge、jpg、gif等等

为什么我用： ||*.jpg

保存后，无效果呢

求助了

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by anewuser** [comment]
@BurningRaptor Maybe you can help this person (but if it can't be solved with a single reply, point him out to a forum or somewhere else where they can ask in Chinese).

**Comment by BurningRaptor** [comment]
可以看一下这个
> https://github.com/fang5566/uBlock/wiki
>
wiki里面可能有你需要的信息
顺便一般的浏览器应该是自带屏蔽图像的功能的（至少火狐有）
@anewuser BTW how do you know I can speak Chinese?

**Comment by anewuser** [comment]
@BurningRaptor I just searched for issues about Chinese filters here and found something posted by you.

**Comment by piaoyun** [comment]
@anewuser @BurningRaptor 
感谢楼上的另外朋友。。
