### ISSUE TITLE
||statcounter.com^ doesn't work.

### ISSUE THREAD

**Issue by Aonavan** [gorhill/uBlock#2815]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

`||statcounter.com^` doesn't block  `http://gs.statcounter.com/`

### One or more specific URLs where the issue occurs

http://gs.statcounter.com/browser-market-share#monthly-201706-201706-bar

### Steps for anyone to reproduce the issue

1. Add ``||statcounter.com^` to filter list.
1. Go to URL i linked above. 
1. See that page isn't blocked.

### Your settings

- OS/version: Windows 10.0.15063.483 (1703)
- Browser/version: 54.0.1
- uBlock Origin version: 1.3.8

##### Your filter lists

Default + uBlock filters – Experimental + Adblock Warning Removal List + Anti-Adblock Killer | Reek + Fanboy’s Enhanced Tracking List + Fanboy’s Annoyance List

##### Your custom filters (if any)

``||statcounter.com^`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You did not use the logger as ask from you when investigating a filter issue.
