### ISSUE TITLE
Twitch TV loading and ads

### ISSUE THREAD

**Issue by Irbidan** [gorhill/uBlock#2816]
### Describe the issue

Some issues loading in some scenarios Twitch

### One or more specific URLs where the issue occurs

www.twitch.tv

### Steps for anyone to reproduce the issue

1. Enter website.
2. Waiting to load videos or website itself.
3. You need to wait too much or simply doesn't load. Also some ads when you enter on a stream are showed.

### Your settings

- OS/version: Windows 10 Pro 15063.483 64 bits
- Browser/version: Google Chrome 59.0.3071.115 64 bits
- uBlock Origin version: 1.13.8

##### Your filter lists

Default filters.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues?q=is%3Aissue+author%3AIrbidan+is%3Aclosed
