### ISSUE TITLE
how to unblock a rule of Static list

### ISSUE THREAD

**Issue by Copox** [gorhill/uBlock#2817]
rt

**Comment by Copox** [comment]
weba##div
weba##a
webb##div

how to unblock weba##a ，the only one rule

**Comment by aggat** [comment]
[Disable cosmetic filter](https://adblockplus.org/filters#elemhide_exceptions)
[Disable network filter](https://adblockplus.org/filters#whitelist)

For sure this issue will be marked as invalid for [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). You should close it.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
