### ISSUE TITLE
[Android] Menu entry and dashboard button missing

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#2818]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
After update to UBO beta on Firefox for Android menu entry and buttons in about:addons are missing

![2017-07-22-21-06-05](https://user-images.githubusercontent.com/886325/28494053-4cc726e0-6f23-11e7-9471-261e6a992a38.png)
![2017-07-22-21-06-18](https://user-images.githubusercontent.com/886325/28494054-5a78200a-6f23-11e7-95b4-e5d219a92b54.png)

You see "USI options" here, but I also tested with all other extensions disabled. Also USI menu entry is working.

### One or more specific URLs where the issue occurs
For example:
http://raymondhill.net/ublock/tiles1.html

### Steps for anyone to reproduce the issue

I used UBO from dev channel, and this version was auto updated.
Dev version can be installed by switching to "Stationary mode"(my translation) from Firefox menu, and then like with desktop browser.

### Your settings

- OS/version: Android 4.4.2 on LG L65
- Browser/version: Firefox 54.0.1
- uBlock Origin version: 1.13.9b0

##### Your filter lists

Default + POL

**Comment by gorhill** [comment]
As said in Release notes, only with Firefox for Android v55 can there be a UI for popup panel access, this applies for all webext extensions.

> As per [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Differences_between_desktop_and_Android), only with Firefox Mobile 55 (beta) you can access uBO's popup panel.

And last I tried, the webext version does not install on Firefox for Android 55, the browser reports a "extension corrupted" error.
