### ISSUE TITLE
Whitelist bug when Googling

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock#2819]
Description:
Here's the scenario..
You'd want to block one of the new gTLDs, like **.download** (since 99% of its usage seems to be for adware and malware).
So, you add **.download** to '**My filters**'.
But then, let's say that you'd want to make an exception, e.g. for **mkvtoolnix.download**
Now, you add **mkvtoolnix.download** to uBO's '**Whitelist**'..
Here comes the problem:
If you Google "mkvtoolnix", **mkvtoolnix.download** comes up as the first hit of course.
..but if you simply click on the link provided by Google, nothing happens.
For the link to open, you'll have to right-click on it and choose "Open in new tab / window"!

How to reproduce:
1) Add **.download** to '**My filters**'.
2) Add **mkvtoolnix.download** to '**Whitelist**'
3) Open the Google search link below.
4) Click on the first result (which should be **mkvtoolnix.download**)

Google search link:
https://www.google.com/search?q=mkvtoolnix

--

Active filters:
All of them, except for these:
* uBlock filters – Experimental
* EasyList without element hiding rules​​​​​​​​​
* Regional filters

OS:
Windows 8.1 Pro, x64

Browser:
Pale Moon v27.4.0, x64

uBlock Origin:
v1.13.8

**Comment by gorhill** [comment]
Works fine with default filter lists.

**Comment by gorhill** [comment]
Bad, I can reproduce with Pale Moon, not with Google Chrome (somehow I thought this was the browser used).

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/28504882-d8edecf8-6feb-11e7-906b-84c68161ce9a.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to diagnose/confirm filter-related issues. If something does not work properly with uBO enabled, the **first step** is to rule out filter-related issues.
> 
> Ignorance of the above rules is no excuse

**Comment by THEtomaso** [comment]
Sorry if I did something wrong when submitting the report, but I tried my best.
Even after looking at your screenshot, and using the logger myself, I still don't have a clue as to what's actually going on!
Oh well..

**Comment by anewuser** [comment]
@THEtomaso See if you can install this extension on PaleMoon: https://addons.mozilla.org/addon/dont-track-me-google1/

If you can't, you'll have to whitelist the URL pattern Google uses to track clicks, or improve your filter. If you need help, access the links from the contributing guide posted above.

**Comment by THEtomaso** [comment]
> See if you can install this extension on PaleMoon: https://addons.mozilla.org/addon/dont-track-me-google1/

Trying to install it gives me the following message:

> The add-on downloaded from addons.mozilla.org could not be installed because it appears to be corrupt.

Same thing in both Pale Moon and SeaMonkey.
