### ISSUE TITLE
uBlock Origin latest not working on Android Firefox

### ISSUE THREAD

**Issue by freegigi** [gorhill/uBlock#282]
0.9.8.3 and the latest dev builds are not working on my Android tablet using Firefox. They install fine, but don't work. Filtering is disabled and the big on/off button is disabled.

0.9.8.2 works fine. Probably something happened between 0.9.8.2 and 0.9.8.3.
If it matters I'm running Android 4.2.2 on an Asus Memopad HD7, Firefox 38.0.5 (latest).

Thank you for this awesome extension.

**Comment by gorhill** [comment]
Is there a browser console in Firefox for Android? If so, any error message of interest for uBlock?

**Comment by gorhill** [comment]
never mind, I will see how far I can go trying to install the Android emulator.

**Comment by freegigi** [comment]
there's something called 'remote debugging', but I have no idea how to use it. sorry, I'm just a regular user, not a developer.

**Comment by AlexVallat** [comment]
@gorhill Take a look at [vapi-background.js#L746](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L746)

```tabbrowser.tabs``` on Fennec returns tabs, not browsers. Could do: ```tabbrowser.tabs.findIndex(tab => tab.browser === browser)``` or similar instead.

**Comment by Matth7878** [comment]
+1
Multiple message like this one un console :
Could not read chrome manifest 'file:///data/data/org.mozilla.firefox_beta/chrome.manifest'.

**Comment by gorhill** [comment]
@AlexVallat Thanks for finding the problem.

Looks like I got the big picture right at [line 462](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L462), but did not followed it properly in the code, due to lack of feedback from being unable to run the browser. That Android emulator install is taking forever to install/config properly.

**Comment by AlexVallat** [comment]
Yes, the Android SDK emulator is a total pain, and if you don't have the exact right black magic setup tends to run dog slowly too. Better than nothing, but only just.
