### ISSUE TITLE
Behind-the-scene

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#2821]
As of 1.13.9 b-t-s requests are not reported in the logger, and cannot be blocked.

* Firefox 54 / Win 10
* uBO 1.13.9b0+
* Force browser/addon update check
* Observe nothing reported, nor blocked if you have a b-t-s block rule

Rules:
* \* * * block
* behind-the-scene * 3p noop

**Comment by gorhill** [comment]
[Wiki page about Firefox WebExtensions](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#differences-with-ubolegacy):

> uBO/webext has limited access to behind-the-scene network requests, unlike uBO/legacy which had full access to all behind-the-scene network requests.

**Comment by luxoflux** [comment]
Sorry, I didn't see that.

Well, this is a deal-breaker, so it looks like I'll be stuck with the legacy release for a while.

**Comment by luxoflux** [comment]
Given that [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354) bug is marked as resolved fixed in Firefox 56, what does that mean for uBlock? Because I'm on Nightly with 1.13.11rc0 and nothing has changed.

**Comment by gorhill** [comment]
I linked to this bug because of [comment 14](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354#c14). I don't really know what's their plan.

**Comment by Cerberus-tm** [comment]
Hmm it seems Mozilla have been busy since August last year, but I don't understand the issue enough to tell whether they've _actually_ fixed it. What do you think? Comment 47 on that same bug:

>  Will Bamberg [:wbamberg]
> 	
> Comment 47 • 4 months ago
> 
> So I've tried to document various aspects of this:
> 
> * extensions automatically get their own URL as a host permission: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions
> 
> * tabs.query can include "moz-extension://..." in `url`: I've added a couple of examples for this: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/query#Examples
> 
> * you can listen for requests to your own URLs, with some caveats: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest#Intercepting_extension_requests
> 
> Please let me know if this covers it, or if I've got something wrong.

https://bugzilla.mozilla.org/show_bug.cgi?id=1271354#c47

**Comment by luxoflux** [comment]
This is aggravating.

I switched over from Chrome many years ago because I could neither log nor block requests from extensions and other stuff that didn't use the webRequest API. And now Firefox has the basically the same problem. I don't know if Chrome has changed in that regard since then.

Are there any Firefox forks that don't have this issue? Or has anything changed with Chrome?
