### ISSUE TITLE
Development Version (1.13.9) on Firefox Nightly Unusable if Cookies are not accepted

### ISSUE THREAD

**Issue by thy6** [gorhill/uBlock#2824]
### Describe the issue

If you install the 1.13.9 version on Firefox Nightly it will become unusable if you block cookies and use a whitelist policy.

### Steps for anyone to reproduce the issue

1. Install any of the 1.13.9 version of ublock origin on Firefox Nightly
2. In about:preferences#privacy, uncheck the option for Accept Cookies from sites
3. Ublock stops working and no options are displayed

### Your settings

- OS/version: Ubuntu 16.04 LTS
- Browser/version: Firefox Nightly 56.0a1 (2017-07-25) (64-bit)
- uBlock Origin version: 1.13.9b2

##### Your filter lists

None

##### Your custom filters (if any)

Not related to the issue

**Comment by gorhill** [comment]
Related: <https://bugzilla.mozilla.org/show_bug.cgi?id=1313401>.
