### ISSUE TITLE
Question - How to not only hide the element but to prevernt its download?

### ISSUE THREAD

**Issue by Stamimail** [gorhill/uBlock#2826]
I have download limits.
I want to prevent the download of a video. Not only to hide it.

**Comment by bershan2** [comment]
This logger is only for actual issues, for general support there is https://www.reddit.com/r/uBlockOrigin/

You can block network request using static network filters as described [in Wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax) and on [Adblock Plus site](https://adblockplus.org/en/filter-cheatsheet).

Note that this issue will be marked _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Stamimail** [comment]
Sorry. I have problem with reading lots of English Text. English it's not my native.
However,
My question is about one visit of website and not about blocking permanently.
I can't find easily the answer with your references.
If you prefer that I'll ask my question in Reddit, I'll have no problem to do so.
Thanks.

**Comment by bershan2** [comment]
1. It's better to ask such questions on Reddit. So you should open a question there, if you expect this conversation to prolong.
2. uBlockOrigin allows to temporarily remove only visual elements (via Zapper), but not network requests. However, you can comment out your network rule with `!` or delete it entirely on the My filters pane of [Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard), if you no longer want it.
2.1 Also, how do you imagine a temporary network rule would work? Zapper is used to hide an element after the page loaded and you saw it; in contrast, it is impossible to cancel a network request after it was satisfied. Thus the network rule has to be written before the request is fired, which in general means before the page is loaded.
2.2 Note that already downloaded content might be served from cache, bypassing uBlock Origin (Chrome does not inform uBlock Origin about such requests at all). Therefore clearing out the cache might solve some problems.
