### ISSUE TITLE
Documentation/clarification: How does uBlock relate to uMatrix?

### ISSUE THREAD

**Issue by Bartolomeus-649** [gorhill/uBlock#2827]
uBlock and uMatrix seem to do very similar things, so a few questions arise that I can't find any documentation on:

1. Can/should you run both uBlock and uMatrix at the same time, or are one making the other redundant?
2. Do uBlock and uMatrix play nice together, that is, what if uBlock say one thing and uMatrix say another?
3. Do uBlock and uMatrix filter request and "stuff" individually, or are they just different GUIs on-top of a common filter engine?
4. What about the other plugins in the "uBlock-Family" (like uBlock O. Extra), do they work together with uMatrix or are there any knows incompatibilities or issues?

It would be nice with a graph or something like that, describing how the different plugins relate to each other. Also some kind of "Best practice guide" for different user scenarios (use-cases) might be a good idea, to make sure one uses things in the way they are intended to be used.

**Comment by ZenFi** [comment]
I read from Reddit that if in doubt using uB and uM both then use uB with hard mode. I guess uM is sort of the hard mode of uM? Not exactly sure though. Hoping to get a wider pic.

SOmething that I'd like to see in uB and/or uM is https enforcer incorporated. (sry a bit off topic)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
