### ISSUE TITLE
define a minimum update period for the filters

### ISSUE THREAD

**Issue by jerome-bouat** [gorhill/uBlock#2828]
### Describe the issue

Currently, the filters are updated too frequently when I'm connected through a slow connection from time to time.

### Steps for anyone to reproduce the issue

I would like a setting which could define a minimum update periode. For example : "don't update the filters more than each 30 days".

### Your settings

- OS/version: Windows 7 x86_64 and Debian GNU/Linux x86_64
- Browser/version: Firefox ESR
- uBlock Origin version:

**Comment by anewuser** [comment]
Uncheck the box next to "Auto-update filter lists" in the options, and update them manually.

**Comment by jerome-bouat** [comment]
I saw this feature but I don't want to disable the update. I just want a less frequent update. It could be the same parameter "don't update the filters more than each" with an integer as days. If it is less than 1, it means the update is performed as frequently as the filter source want it.

**Comment by anewuser** [comment]
I've offered a solution for users with slow connections. If it isn't good enough for you, hire a programmer to create a fork that fits your specific needs.
