### ISSUE TITLE
remove 'hidden' and delete <style>will make some rules not working

### ISSUE THREAD

**Issue by zardcopox** [gorhill/uBlock#2829]
OS/version: win10
Browser/version: chrome/60.0.3112.78
uBlock Origin version: uBlock Origin v1.13.8

i create a demo : https://copox.github.io/player/

my block rules : 
`copox.github.io##div`

the code : 
`
       $(function(){
            document.addEventListener('DOMNodeInserted',function () {
            if (document.querySelectorAll('*[hidden]')){
                var ele1=document.querySelectorAll('*[hidden]');
                for (var i=0;i<ele1.length;i++){
                    ele1[i].removeAttribute('hidden');
                }
                var tagStyle=document.getElementsByTagName('style')[0];
                tagStyle.parentNode.removeChild(tagStyle);
            }
        });
       });    `

result: rule not working

------------------------------------------------------------------
but when i open the logger, refresh page by button of logger
rule work again ...
Is it a bug ???

**Comment by gorhill** [comment]
Chromium-based browsers do not support user styles. Use Firefox.
