### ISSUE TITLE
[default lists] Malware domains (long-lived)

### ISSUE THREAD

**Issue by BilBg** [gorhill/uBlock#2830]
### Describe the issue
For some reason `Malware domains (long-lived)` is not fully included in `Malware domains`

```
Malware domains			27,730 used out of 27,731
Malware domains (long-lived)	2,374 used out of 3,204
```

Consider making `Malware domains (long-lived)` a default list (i.e. checked by default).

**Comment by gorhill** [comment]
I plan to remove that list as part of the coming _"3rd-party filter"_ cleaning, that list is pointless.

**Comment by BilBg** [comment]
Pointless because included in the browser (Google Safe Browsing)?

How older versions of uBlock Origin (e.g. 1.12.4 which is stuck in older Chromium < 38) will react to "the coming "3rd-party filter" cleaning"?
(on current  uBO "The added code will convert removed stock filter lists which are enabled into imported filter lists", probably on older the lists will vanish no matter if checked? - not really a problem for me, just wondering if this was tested)

**Comment by 5t3f4n** [comment]
> Pointless because included in the browser (Google Safe Browsing)?

How would that make it useless? Some disable Google Safe Browsing and rely solely on uBlock Origin and the likes.

**Comment by gorhill** [comment]
I think the purpose of "Malware domains (long-lived)" is for domain names for which the remote server no longer respond. I want the stock list to be reduced to what is pragmatic to use, not throw in there everything we stumble upon, I consider the stock lists selection to be bloated now. There is always the ability to import through custom URLs for those who want more than what the stock filter lists.

**Comment by BilBg** [comment]
> I think the purpose of "Malware domains (long-lived)" is for domain names for which the remote server no longer respond.

For me seems they are more than active:

First line of the list:
`#This is a list of long-lived, "immortal", malware domains`

On the web page:
"These are domains which were identified as malicious  anywhere between 90 and 360 days ago. but according to google safebrowsing, are **still** actively involved in badness"
http://www.malwaredomains.com/?p=1282

Probably you can ask the authors if this list is important:
http://www.malwaredomains.com/?page_id=13

**Comment by Kees1958** [comment]
Bigger is not always better, often less is more. Depends on what websites one visits, but on average when you use Google safe browsing you better stick to well maintained filter list. Most community based filterlist have a lot of people adding new websites, but there are few people cleaning those list up.

Best results I have is 
- disconnect simple tracking list
- disconnect simple ad list (is an 80% copy of Peter's Low list but more often updated
- adguard simple DNS filter (a well maintained subset of their adfilters list)
- adguard spyware filter (a well maintained filter  50% less than Easy Privacy set and 95% as effective)

**Comment by BilBg** [comment]
_Off-topic (sorry, I don't know how to ask about locked thread)_

There was misunderstanding here: https://github.com/gorhill/uBlock/issues/2853

loganmarchione:
> @gorhill, there is an undocumented permission (privacy) needed in manifest.json. Bug is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1364975

He needed to say "undocumented by **Mozilla**" (and not by you) and "needed" for "WebExtensions to disable WebRTC"
(I didn't dig in bugzilla to see/understand if this is really "needed")

**Comment by gorhill** [comment]
Issue is now obsolete with 651da715.

**Comment by gorhill** [comment]
> For some reason Malware domains (long-lived) is not fully included in Malware domains

Best is that you contact the maintainer(s) of these lists if you feel strongly about _"Malware domains (long-lived)"_ being part of _"Malware domains"_.
