### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by x0a** [gorhill/uBlock#2832]
### Describe the issue
High use of memory from uBlock, after about a day of browsing (social media, YouTube, and so on). Memory usage goes down about 30k if I update the filters.

### One or more specific URLs where the issue occurs
Everywhere. This is the background process.

### Screenshot in which the issue can be seen
![screenshot from 2017-07-30 12-32-03](https://user-images.githubusercontent.com/13019784/28755569-7c84dc0a-7523-11e7-89f7-b30822e88918.png)

### Steps for anyone to reproduce the issue

Browse YouTube for a couple of hours, without closing the browser.

### Your settings
Default settings

- OS/version: Ubuntu 17.04
- Browser/version: Chrome Version 60.0.3112.78 (Official Build) (64-bit)
- uBlock Origin version: 1.13.8

##### Your filter lists
Default filter lists

##### Chrome heap snapshot/memory profile (5mb)
[Heap-20170730T123333.heapsnapshot.zip](https://github.com/gorhill/uBlock/files/1185870/Heap-20170730T123333.heapsnapshot.zip)

**Comment by gorhill** [comment]
> Memory usage goes down about 30k if I update the filters

So this means there was memory to be garbage collected by the browser, it's out of control of uBO.
