### ISSUE TITLE
ABP problem Display 

### ISSUE THREAD

**Issue by Max9088** [gorhill/uBlock#2833]
Adblock plus causes some display problems on the website : yggtorrent.com
:lol: because of this rule : **yggtorrent.com##table > tbody > tr + tr + tr + tr + tr + tr + tr + tr + tr + tr**
There are many tables (lists) on this website , and ABP blocks the complete display of tables !

Strange to have add this "global" rule : **##table > tbody > tr + tr + tr + tr + tr + tr + tr + tr + tr + tr**
Can you fix this please !

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://forums.lanik.us/viewtopic.php?p=121457#p121457
