### ISSUE TITLE
Not an issue but a PSA phising attempts on google extensions

### ISSUE THREAD

**Issue by gh0sti** [gorhill/uBlock#2834]
Just wanted to let you guys know to watch out for phising emails asking you to login. Looks like there maybe a campaign going out targeting google extension teams. This team didn't watch the link was directing them to a bit.ly and a fake page grabbing login credentials. I wonder if 2FA helps protect against these type of attacks if Google has implemented that.

**Comment by gorhill** [comment]
I know about all this.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Just a reminder to whoever worries this could happen to uBO: just install the extension manually from the repo here, this way you update whenever **you** choose, and can review all the code changes before installing a new version.
