### ISSUE TITLE
Please consider changing the popup icon's cross sign.

### ISSUE THREAD

**Issue by sharethewisdom** [gorhill/uBlock#2836]
Aren't the `VECTOR OR CROSS PRODUCT` or `N-ARY TIMES OPERATOR` variants more widely available than `MULTIPLICATION X`, which is currently used to style the popup's icon overlays?

```css
#extraTools > span.on > span:last-of-type:after {
  content: '\2715';
}
```

using

```
uBlock Origin 1.13.8
Chromium Version 59.0.3071.115 (Developer Build) (64-bit)
Linux arch 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
```

...with the core fonts from Microsoft available for Chromium:

> Andale Mono, Arial, Arial Black, Comic Sans MS, Courier, Courier New, Georgia, Helvetica, Impact, Times, Times New Roman, Trebuchet MS, Verdana, Wingdings 2, Wingdings 3 (via javascript)

While I do not see U+2715 (&#10005;),
both U+2A2F (&#10799;) and U+2A09 (&#10761;) are available in all of the fonts Chromium presents to me.

I'm aware that due to its sandbox, Chromium does not fully integrate with fontconfig/GTK/Pango/X/etc. If there's a way for me to replace that symbol with a complementary font, please let me know.

**Comment by gorhill** [comment]
Actually, I was considering it.

I was planning to import the solution I used in uBO-Scope: [a simple svg element](https://github.com/gorhill/uBO-Scope/blob/master/popup.html#L25).

**Comment by sharethewisdom** [comment]
:+1: 
I'm glad to see you take a simple svg approach. I often see icons rendered on canvas. That fails when starting chromium with `--enable-potentially-annoying-security-features` with a 'getImageData' error. Which is indeed, annoying.

**Comment by BilBg** [comment]
> While I do not see U+2715 (✕),
both U+2A2F (⨯) and U+2A09 (⨉) are available in all of the fonts Chromium presents to me

I see U+2715 (✕) and U+2A09 (⨉) as (X) but U+2A2F (⨯) as square (i.e. non-existent) on this page in Chromium 48 on Windows XP

**Comment by sharethewisdom** [comment]
@BilBg thanks. Beware the outdated browser. Out of curiosity: what's your standard font? (chrome://settings/fonts) Could you list the system fonts available to chromium? You can [test the uniqueness](https://panopticlick.eff.org/results?#fingerprintTable) of your browser's settings, which lists System Fonts, and a uniqueness figure.

In my case, only one in 283.59 browsers tested supposedly have these fonts. Many Windows users have a huge list of fonts there. Anyway, since this cross will likely be replaced with svg, it doesn't matter.

**Comment by BilBg** [comment]
> Beware the outdated browser

The latest possible is Slimjet 10.0.13.0 (Chromium 50) (Portable) 
(7-8 browsers here, including the old Opera 12.16 and Tor Browser 6.5.2 which is the only new-enough)

> Out of curiosity: what's your standard font?

Times New Roman

> Could you list the system fonts available to chromium?

They are about 75

**Comment by gwarser** [comment]
On android 4.4.2 lg l65 I only see U+2715 (✕)
