### ISSUE TITLE
Scriptlet injection filters counted as cosmetic filters

### ISSUE THREAD

**Issue by Golddouble** [gorhill/uBlock#2837]
### Describe the issue

**Question 1:**
I went to the Settings pane in the dashboard, and checked the option "Disable cosmetic filtering" under the "Default behavior" header.
So I am right, that now, it does not matter, if I have activated or deactivated the checkboxes on 1) and/or 2). see below ->

![ublock](https://user-images.githubusercontent.com/13977359/28834277-18821fcc-76e2-11e7-9047-02e01ebb2029.PNG)

**Question 2:**
I went to the Settings pane in the dashboard, and checked the option "Disable cosmetic filtering" under the "Default behavior" header.
And as you can see in the attachment: I also do not want that uBlock does valuate and apply cosmetic filters, and does ignore generic cosmetic filters.

Question: So I thought that I have deactivated all cosmetic filtering. But as you can see in the attachment uBlock claims to use 965 cosmetic filters. (?) Why?

![ublock](https://user-images.githubusercontent.com/13977359/28834277-18821fcc-76e2-11e7-9047-02e01ebb2029.PNG)

Would appreciate your answers. Thank you.

#### My settings

- OS/version: Windows 7 Professional 32 bit
- Browser/version: Pale Moon 27.4.0 
- uBlock Origin version: 1.13.8

##### Your filter lists
![filterliste 1](https://user-images.githubusercontent.com/13977359/28834116-b40a8520-76e1-11e7-8a34-29ab76da3955.PNG)
![filterliste 2](https://user-images.githubusercontent.com/13977359/28834125-b8e91e76-76e1-11e7-8361-2b8ae59f6687.PNG)

##### Your custom filters (if any)
No

**Comment by gorhill** [comment]
[Custom specific cosmetic filters are never ignored](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#parse-and-enforce-cosmetic-filters):

> Note that if you disable this option, your own custom cosmetic filters (if any) will still be enforced.

**Comment by Golddouble** [comment]
Thank ou for your reply.

But I was not able to reproduce this.

This cosmetic filters seem not to be part of my custom cosmetic filter (I do not have any), but they are from 
-uBlock filters and
-uBlock filters – Privacy

As you can see in the following animation:
![ublock cosmetic filters](https://user-images.githubusercontent.com/13977359/28873843-92710106-778f-11e7-8257-ee1742335bdb.gif)

Would appreciate your clarifying answer. Thank you.

**Comment by gorhill** [comment]
Ok, I forget about scriptlets filters -- `##script:inject`, which use cosmetic filter syntax (`##`), but which are not dismissed as cosmetic filters, their purpose is more to modify the behavior of a site than to act purely for cosmetically purpose.

**Comment by gorhill** [comment]
Frankly I am not sure how to solve this, to create yet another category for the count of scriptlet filters is just overload of information.

**Comment by Hrxn** [comment]
Well, why overload? I think, strictly technical, they are their own category, more or less..

**Comment by gorhill** [comment]
Fixed with a9f68fe02f40.
