### ISSUE TITLE
Problem with naruto-tube.org

### ISSUE THREAD

**Issue by Zesko** [gorhill/uBlock#2838]
Example URL: <http://naruto-tube.org/boruto-sub-018>

There are 2 probleme:

1. how can uBlock block ad on video streaming?

2. If i try to click ad on this video, a strict-blocking-page will come.
Then i want to click a button "Go Back", but it does not work sometimes in Chromium (it works fine in Firefox) 
How to fix "Go Back" for Chromium?

### My settings

- OS: Linux Mint 64-bit
- Browser: Chromium version 59.0.3071.109 
- uBlock Origin version:  v1.13.8

**Comment by gorhill** [comment]
> how can uBlock block ad on video streaming?

Filter/support issue, not to be reported here as explicitly stated at the top of [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

>  i want to click a button "Go Back", but it does not work sometimes in Chromium

See #818.
