### ISSUE TITLE
[Enhancement] Allow clicking on domain to expand it to show hosts

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#284]
Currently uBlock popup UI has an "All" expander to expand all domains to show the hosts.

Proposal: Allow clicking on any domain to only show the hosts for that domain.

**Comment by luxoflux** [comment]
That *would* be a nice quality-of-life enhancement, but low priority for me (just my two cents).

**Comment by gwarser** [comment]
Can be closed?

**Comment by gorhill** [comment]
I want to give more thoughts on finer details:

- No need to expand when all subdomains are already visible (example, see `https://news.ycombinator.com/`)
- When a subdomain is cname'd but not the base domain, should the cname'd be always visible? (example, `https://en.wikipedia.org/wiki/Main_Page`)
- Whether there should be a widget on hover for toggling expand/collapse (example, like in uMatrix)

I haven't made a decision yet about these.
