### ISSUE TITLE
cosmetic: Settings>Back up to file timestamp

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [gorhill/uBlock#2840]
### Describe the issue
Settings back up to file timestamp in the dashboard updates before a file is saved

### Steps for anyone to reproduce the issue

1. `browser.download.useDownloadDir` is set as false (this enforces user interaction for security reasons when downloading or saving files and prompts the "Save dialog")
1. go to chrome://ublock0/content/dashboard.html#settings.html - 
2. click "Back up to file"
3. timestamp is updated to current date+time
4. Cancel the save

### Your settings
- Windows 7
- FF54.01 64bit
- v1.13.8

See: issue https://github.com/pyllyukko/user.js/issues/330

Please close this if there is no way for uBo to determine if the action is completed, since the dialog is outside it's scope. Thanks.

**Comment by gorhill** [comment]
So far after looking around MDN documentation, I haven't found a way to deal with this. There does not seem to be any event fired by the browser about what happens beyond relinquishing the control to the browser through the firing of the `click` event on the `<a>` element.

**Comment by Thorin-Oakenpants** [comment]
Thanks gorhill. It's not important. Saved files contain a timestamp in the filename by default, and most (almost all) saves would be completed.
