### ISSUE TITLE
No remote fonts

### ISSUE THREAD

**Issue by Golddouble** [gorhill/uBlock#2844]
### Describe the issue
I normaly do not want to use the fonts from the website, but the font of my own browser. This is not because of security and privacy concerns. I have deactivated antialiasing and each smoothing of the font in my windows system, to get a font which is absolutely sharp. So through this, often some Fonts of the website looks very uncomfortable. This is why I always want to use the font from my browser.

But sometimes, there are some signs, that can not be showed proper with this setting. This is a pity.  When I activate the setting "No remote fonts" in uBlock, and I call the following site: 
http://www.electroncash.org/
then there are signs which are not showed proper:
![homepage-schriften mit ublock geblockt](https://user-images.githubusercontent.com/13977359/28996227-0fd3e6ae-79fc-11e7-929f-57abf7e4ec5f.png)

There is another addon; its name is "Document Font Toggle" which clames to do the same.
https://github.com/7adietri/document-font-toggle
But comically with this addon (and the deactivated setting in uBlock), this signs are showed as they should. So it seems, that this to methods do not lead to the exactly same result:
![homepage-schriften mit separatem addon](https://user-images.githubusercontent.com/13977359/28996063-995aab0a-79f8-11e7-88cd-1994041548d6.png)

Question:
I only want to change the text fonts of a webpage into the browser font, but not such signs. The addon "Document Font Toggle" makes this, but uBlock not. Why not?

### One or more specific URLs where the issue occurs
http://www.electroncash.org/

### Your settings
- OS/version: Windows 7, 32 bit
- Browser/version: Firefox 54.0.1
- uBlock Origin version: 1.13.8

**Comment by gorhill** [comment]
> The addon "Document Font Toggle" makes this, but uBlock not. Why not?

"Document Font Toggle" just toggles a preference in Firefox, the `about:config` entry `browser.display.use_document_fonts`, Firefox is the one [sorting out what fonts should be allowed or not](https://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/), not the extension.

uBO's no-remote-fonts feature is to block the fetching of remote font resources.
