### ISSUE TITLE
Can I circumvent firewall censorship by replacing/redirecting domain original.com -> mirror.com?

### ISSUE THREAD

**Issue by ccaapton** [gorhill/uBlock#2846]
Hi, I'm in China and a lot of websites are censored by the national level firewall. The most sad one is that they blocked ajax.googleapis.com so any sites using googleapis as cdn will not work properly.

I used https://addons.mozilla.org/en-US/firefox/addon/redirector/ to replace/redirect ajax.googleapis.com to ajax.proxy.ustclug.org, which is just a domestic mirror of the google one and not censored. But this addon does not work on firefox android. Is it possible to do the same thing with UBO?

**Comment by gorhill** [comment]
Redirecting requests for remote resources to local resources is outside the purpose of uBO.

This is however the purpose of Decentraleyes: <https://github.com/Synzvato/decentraleyes>.
