### ISSUE TITLE
Problems with Google Drive Website

### ISSUE THREAD

**Issue by Cimbass** [gorhill/uBlock#2849]
Firefox ESR 52.2.1 32bit
Windows 8.1
uBlock Origin 1.13.8

Link: https://drive.google.com/drive/my-drive

I have global set: 
* * 1p-script block
* * 3p-frame block
* * 3p-script block
* * inline-script block

When I switch off uBlock (clicking on the big power button) and reload the page, it don't load it completly (no content of the drive files are shown, the loading circle from Google Drive rotates endless).

When I then switch off  * * 3p-script block, the page loads complete (and uBlocks Power button is still grey).

I have tried a new profile, install uBlock Origin first and the page loads with the same settings, but when I install e.g. convert2mp3 or WOT (AddOns, that wants to restart FF to work), the problem is back. 

I hope, you can reproduce the problem

**Comment by gorhill** [comment]
> I have tried a new profile, install uBlock Origin first and the page loads with the same settings, but when I install e.g. convert2mp3 or WOT (AddOns, that wants to restart FF to work), the problem is back.

Doesn't this mean the issue is not uBO?

**Comment by gorhill** [comment]
Also, try this: when you force a reload of the page, try holding shift while pressing the reload button of the browser. I think I have noticed in the past that uBO's injected CSP to block inline script may still be in there unless one force a bypass of the browser cache when force reloading.

**Comment by Cimbass** [comment]
Shift+Reload doesn't help, also restarting FF (with FF settings restore tabs on start)

> Doesn't this mean the issue is not uBO?
I don't know, but when I deactivate only uBO (and like WOT and convert2mp3 is still active), the page loads correct, thats 1:2 against uBO ;)

And why is there a difference, when the big power button is gray and the "third party scripts" global blocker is changed from red to gray (or green)?

**Comment by gorhill** [comment]
Tested on FF54, with default settings/lists + rules in OP and advanced user mode enabled: can't reproduce. I went as far as installing WOP: still can't reproduce.

Provide exact, _detailed_ steps to reproduce. I will close if no further information is provided to enable other people to reproduce.

**Comment by gorhill** [comment]
Closing issue due to inability to reproduce + lack of feedback by OP.
