### ISSUE TITLE
Firefox warns about outdated addon type

### ISSUE THREAD

**Issue by Symbai** [gorhill/uBlock#2850]
### Describe the issue

Since FF 55 it warns in addon page that uBlock Origin is an outdated addon type and it says these addons can no longer be used after November 2017.

Will there be a compatible version or will you discontinue the development then?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
