### ISSUE TITLE
[Firefox 57+]: Addon listed as Legacy

### ISSUE THREAD

**Issue by jerz4lunch** [gorhill/uBlock#2851]
### Issue Description
Firefox just listed this addon as Legacy: [Link](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing).

### My settings

- OS/version: Arch Linux x64 [Freshly up to date]
- Browser/version: 55.0 (x64)
- uBlock Origin version: 1.13.8 [latest version as of this writing]

**Comment by benoit-pierre** [comment]
#2850 
#2794 
#2728 
...
