### ISSUE TITLE
Gmail text invisible

### ISSUE THREAD

**Issue by Ksymil** [gorhill/uBlock#2852]
uBlock Origin prevents the Gmail messages from displaying in the In-box. It just hides them, supposedly the same way it hides advertisements.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You completely ignored the template, and you also completely ignored that you need to make the case the issue is with uBO and not your filters.
