### ISSUE TITLE
[Firefox] Ability to completely disable WebRTC

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2853]
Firefox's WebExtensions API support [the complete disabling of WebRTC](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/network#Properties). Make this option available to user.

The current option _"Prevent WebRTC from leaking local IP addresses"_ will become a sub-option of _"Disable WebRTC"_. For platform not supporting the disabling of WebRTC, the option _"Disable WebRTC"_ will be disabled (dimmed) and always checked.

**Comment by jspenguin2017** [comment]
> For platform not supporting the disabling of WebRTC, the option "Disable WebRTC" will be disabled (dimmed) and always checked.

I think that is a bit confusing, maybe disabled and always *not* checked?

**Comment by gorhill** [comment]
That's right my bad, _not_ checked is what I really meant.

**Comment by BilBg** [comment]
Slimjet (Chromium clone - http://www.slimjet.com/ ) have this in Settings:
  (I don't know if they changed the source code of Chromium to accomplish this or it is some "hidden setting" in original Chromium they expose)

The screenshot is from Slimjet Browser Portable 10.0.5.0 (based on Chromium 50.0.2661.75)

![Slimjet - Enable WebRTC.png](http://store.picbg.net/pubpic/89/A0/4d4a289ad2fa89a0.png)

**Comment by zero77** [comment]
Just a suggestion but, is that not something that would fit in better with uMatrix, you could even add an extra column in the add on menu.

**Comment by loganmarchione** [comment]
@gorhill, there is an undocumented permission (privacy) needed in manifest.json. Bug is [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1364975#c24).

**Comment by gorhill** [comment]
`privacy` permission is not undocumented, it has been used by uBO since May 30, 2015.
