### ISSUE TITLE
[Firefox] Investigate having the logger into the browser's sidebar

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2854]
Firefox WebExtensions API supports the [`sidebarAction` API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction), which purpose is to open "a pane that is displayed at the left-hand side of the browser window, next to the web page."

I want to investigate whether using the sidebar API to host uBO's logger is practical. I can confirm it is feasible, by simply adding the following entry to uBO's manifest file:

    "sidebar_action": {
       "default_icon": {
          "19":"img/browsericons/icon19.png",
          "38":"img/browsericons/icon38.png"
       },
       "default_title" : "uBlock Origin logger",
       "default_panel": "logger-ui.html"
    },

Result:

![a](https://user-images.githubusercontent.com/585534/29131311-80bf01a4-7cfa-11e7-9d34-2148ef1639b2.png)

Issues to investigate/solve:

- The drop-down list at the top of the logger does not work, for unknown reasons.
- There can be only one logger document opened at any given time, so these approaches must be mutually exclusive:
    - Logger in a separate tab
    - Logger as a popup window
    - Logger in the sidebar
        - Complication: there can be only one logger, so need to deal with the case of many windows with sidebar opened.
- Verify that this also work on Opera, which also supports the sidebar API
    - Using the browser's sidebar is practical only if the maximum width allowed is sufficient

**Comment by heubergen** [comment]
I'm not intend to disturb you but the drop-down seems to work for me with Firefox Nightly. I can select a site and the logger also only shows the requests from the selected site.
<img width="510" alt="screen shot 2017-08-09 at 9 56 07 pm" src="https://user-images.githubusercontent.com/5529410/29141256-bb405ee2-7d4d-11e7-95d2-4959fa1f573d.png">

**Comment by gorhill** [comment]
Looks like you are on MacOS? Could be a Linux-specific issue.

**Comment by heubergen** [comment]
Yes, I'm using MacOS. Maybe someone with Windows OS can confirm the issue?

**Comment by sn260591** [comment]
Is it possible to place the sidebar at the bottom (like a logger in ABP)?

**Comment by luxoflux** [comment]
Just some ideas:

* Left-click on the logger icon would behave as normal
* Right-click opens in the sidebar
* Middle-click opens in a new window

And the tooltip could list these options.

**Comment by gorhill** [comment]
Drop list issue in sidebar: <https://bugzilla.mozilla.org/show_bug.cgi?id=1190679#c11>.

**Comment by sn260591** [comment]
How about [devtools panel](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/devtools_panels)? This can also be implemented in Chrome.

**Comment by elypter** [comment]
it would be cool to have this for vivaldi too.

**Comment by gorhill** [comment]
> How about devtools panel?

uBO's logger is unified. A dev tool panel is meant to provide tools for the current page only. For instance, had the logger not been unified and implemented as a dev panel, it would be next to impossible to witness Instart Logic at work -- uBO's logger is out of reach of such ploy used by Instart Logic.

**Comment by gorhill** [comment]
This will need to be fixed for Opera too, it supports side bars.
