### ISSUE TITLE
Firefox 55 marks uBlock Origin as "LEGACY"

### ISSUE THREAD

**Issue by BraindeadBZH** [gorhill/uBlock#2856]
When navigating to about:addons in Firefox 55, uBlock Origin is labeled as "LEGACY", and therefore will be disabled by November with version 57.

**Comment by Hrxn** [comment]
No need to open new issues about stuff everyone (yes, that includes maintainers) is perfectly aware of...

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
