### ISSUE TITLE
path of extension-data/ublock0.sqlite is hardcoded

### ISSUE THREAD

**Issue by abma** [gorhill/uBlock#2858]
it seems its not possible to change the path of extension-data/ublock0.sqlite to a different folder.

this is needed to exclude the sqlite db from backups on a terminal server as its usually a very large file.

i.e. move it to d:\temp\%username%\ublock\ublock0.sqlite

i tried this with Firefox 52 ESR + uBlock Origin v1.13.8

**Comment by stonecrusher** [comment]
As a workaround I'd suggest just setting a [junction](https://en.wikipedia.org/wiki/NTFS_junction_point).
Depending on what system you are on, this can be done [very easy](http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html).

**Comment by gorhill** [comment]
Declined. With WebExtensions, uBO can't decide where the data is saved on disk, it's the API taken care of this. I do not plan to work on adding features which benefit only the legacy version.

**Comment by abma** [comment]
@stonecrusher:

yeah, had that idea, too but this requires more permissions for the user who creates the link:

https://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7

still thanks for the feedback!
