### ISSUE TITLE
Toggle option changes are always permanent

### ISSUE THREAD

**Issue by Kees1958** [gorhill/uBlock#2859]
### Describe the issue 
Toggle options are always permanent (also in advanced mode). In advanced mode all (other) rules need to be made permanent with the lock icon. Would be more logical when toggle rules would be permanent in simple mode and would be temporary in advanced mode. 

### One or more specific URLs where the issue occurs
All

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/30925856/29209242-d382592e-7e8d-11e7-8870-ee895dc7754c.png)

### Steps for anyone to reproduce the issue
1. Click on "Toggle the blocking of all pop-ups for this site"
2. Click on wheels icon to open the dashboard
3. Click on My Rules tab
4. The pop-up block rule is added (correct) but also made permanent, example: 
no-popups: github.com true

### Your settings
enabled advanced user, kept all other settings default

- OS/version: Windows 7 Ho,e
- Browser/version: Chromium 60
- uBlock Origin version: 1.13.8

##### Your filter lists
uBlock experimental
BlockZilla
Disconnect simple ad-filter

**Comment by anewuser** [comment]
>Would be more logical when toggle rules would be permanent in simple mode and would be temporary in advanced mode.

No, it wouldn't  "be more logical" to change the expected behavior of the extension just to fit your personal needs and affect all the users who have already been using for a long time.

**Comment by Kees1958** [comment]
In advanced mode, other rules are temporarily until you click the lock icon, while toggle rules popup, media elements, etc are permanent. When that does not strike you as an irregularity, fine no need to give such an unfriendly answer.

**Comment by gwarser** [comment]
Will like this too. For example i often disable blocking large media for one time use (clicking in "red frame"  not always work). When not permanent, will work similarly to "zapper" tool.

**Comment by Kees1958** [comment]
Okay let's see whether the developer thinks of it.

**Comment by gorhill** [comment]
> For example i often disable blocking large media for one time use

You can do this using the context menu and click the entry "Temporarily disable the blocking of large media elements". This leaves the switch unchanged.

**Comment by gorhill** [comment]
> Okay let's see whether the developer thinks of this feature request.

This also annoys me that the toggle of switches are not temporary. I have experimented with a UI in the past, and I didn't like the result, over-complicating things for mainstream users goes opposite of what I want. See <https://github.com/gorhill/uBlock/issues/1117#issuecomment-167381796>.

**Comment by Kees1958** [comment]
When you add an option at default behavior section in the settings tab to enable creating per site override rules as temporary the user interface could remain the same, see pictures

UI change to add the option
![image](https://user-images.githubusercontent.com/30925856/29250391-24360b62-8042-11e7-8d64-3420c896e9cc.png)

My Rules tabe would only show these per site rules as temporary (lock icon makes them permanent identical to how other rules are handled)
![image](https://user-images.githubusercontent.com/30925856/29250407-4e038b4a-8042-11e7-852e-75ccdd2ccbfc.png)

**Comment by gorhill** [comment]
I consider the lack of temporary toggle even more of an irritant now that there is a JavaScript master switch.

One idea I am considering is to have the toggle set as temporary when the overview panel is opened (thus allowing the user to persist using the now-visible padlock), and keep it sticky (as it is currently) when the overview panel is not visible.

**Comment by Kees1958** [comment]
That would work for me.

**Comment by gorhill** [comment]
Can't remember why I re-opened, so closing again.
