### ISSUE TITLE
JW Player videos not playing w/ EasyList

### ISSUE THREAD

**Issue by SW1FT** [gorhill/uBlock#286]
Title sums it up. This has been happening, more or less, since the fork change I think. I've gotten an answer from Fanboy (creator of EasyList) and it seems that this is not a problem with the list itself but rather uBlock Origin. https://forums.lanik.us/viewtopic.php?f=64&t=23170

You can test this on any JW Player video, test this one for example:
http://www.miragens.abola.pt/media.aspx?id=22556

Workaround:
I've been using `* jwpcdn.com * allow` to be able to watch JW Player videos.

Specs:
- uBlock Origin Settings: 
![ubosettings](https://cloud.githubusercontent.com/assets/6627739/7950837/0c67f4f0-0998-11e5-905d-1d9c02b704f9.png)
- uBlock Origin 0.9.8.4-dev.3
- Firefox Dev Edition 40.0a2
- Windows 7
- Disabling all my other addons is not changing this behavior

**Comment by tenkuu** [comment]
Happening to me on 40.0a2 too.
![2015-06-02_19-12-24](https://cloud.githubusercontent.com/assets/2627419/7951388/a578ce68-095b-11e5-84e5-a71556a73638.png)

Workaround: `@@||p.jwpcdn.com/6/8/skins/glow.xml`

**Comment by SW1FT** [comment]
@tenkuu Thanks, that's exactly the file that is breaking the ability to play the videos.

**Comment by gorhill** [comment]
hpHosts blocks `p.jwpcdn.com`. hpHosts is not officially supported, so if it breaks something, users are responsible to deal with the issue.

**Comment by Blutgang** [comment]
@SW1FT The problem actually lies with the `hpHosts' Ad and tracking servers` list and not with `Easylist` (as Raymond pointed out). `Easylist` does have an exception `(@@)` rule for `p.jwpcdn.com`. 

Why don't you try: `@@||p.jwpcdn.com/*/glow.xml` or `@@||p.jwpcdn.com/*/skins/glow.xml`
You can use wildcard characters `(*)` `[This stands for any number of characters.]` in the adblock plus filters (https://adblockplus.org/filter-cheatsheet). 
I can't seem to access the video for the wareztuga.tv site so I cannot say if that particular filter will work.

**Comment by SW1FT** [comment]
@Blutgang Thanks for pointing that out.

For anyone facing the same problems as me just try these filters:
`@@||p.jwpcdn.com/*/*/skins/glow.xml`
`@@||p.jwpcdn.com/*/*/googima.swf`
`@@||p.jwpcdn.com/crossdomain.xml`
