### ISSUE TITLE
[Firefox] AMO Link doesn't work in 1.13.9b8 release notes

### ISSUE THREAD

**Issue by rudedogg** [gorhill/uBlock#2860]
### Describe the issue
The `available in dev channel on AMO.` link in the 1.13.9b8 release notes is broken (requires firefox.org login, and says "Oops! Not allowed." if/when logged in). I'm guessing it requires permissions only @gorhill has.

The Web Extensions documentation page uses this link which works though: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1

Sorry, this is pretty minor, but I'm guessing other people will be confused too.

**Comment by gorhill** [comment]
Fixed, thanks for reporting.
