### ISSUE TITLE
uBlock compatibility with Firefox 57.0a1 (2017-08-11)

### ISSUE THREAD

**Issue by edricus** [gorhill/uBlock#2861]
### Describe the issue
I use Firefox Nightly in Archlinux and uBlock is disabled since the last update.

### One or more specific URLs where the issue occurs
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Screenshot in which the issue can be seen
http://i.imgur.com/mFTqZQw.jpg

### Steps for anyone to reproduce the issue
Go on Linux
Download the lastest version of Firefox Nightly on the Mozilla website (57.0a1 (2017-08-11))
Go to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Your settings
- OS/version: ArchLinux LTS 4.9.41-1 x86_64
- Browser/version: Firefox Nightly 57.0a1 (2017-08-11)
- uBlock Origin version: removed by browser (latest)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
