### ISSUE TITLE
Certain elements not filtered by uBo

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#2863]
Adding the following filter **##COOKIE-ALERT** on webpage `http://www.muchgossip.it/` doesn't filter the cookie element.

Works fine in ABP
http://i.imgur.com/OpwB2Xt.png

**Comment by jspenguin2017** [comment]
Works fine on Chrome 60: 
![image](https://user-images.githubusercontent.com/7283682/29236898-0cb676fc-7ed0-11e7-97ad-21976c5d02ba.png)

**Comment by ryanbr** [comment]
Unless I'm doing something wrong? It's still there.

![cookie-filter2](https://user-images.githubusercontent.com/1659004/29237003-1304b836-7f69-11e7-9d82-122490733bf2.png)

**Comment by okiehsch** [comment]
Your filter works fine on Chrome and Firefox on my end.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by gorhill** [comment]
Unable to reproduce with Chrome or Nightly + default settings + `##COOKIE-ALERT`. Did you disable cosmetic filtering for the page? Did you check "Ignore generic cosmetic filters"? Did you un-check _ My filters" in "3rd-party filters" pane?

**Comment by gorhill** [comment]
Closing issue to being not reproducible by many and lack of feedback by OP.
