### ISSUE TITLE
[default lists] Add forbidden.txt to default lists

### ISSUE THREAD

**Issue by hook54321a** [gorhill/uBlock#2864]
### Describe the issue
(I saw another issue related to the default lists so I assumed that this is the correct place to put this even though the other place still exists, if this isn't the correct place then I can move it)

https://github.com/bbb31/easylist/blob/master/forbidden/forbidden.txt

`||functionalclam.com^$third-party` was recently removed from easylist, putting users at risk. I would assume that having the extension simply grab a text file from somewhere wouldn't cause a DMCA takedown request.

**Comment by Hrxn** [comment]
> I would assume that having the extension simply grab a text file from somewhere wouldn't cause a DMCA takedown request.

Well, to be fair, that is exactly what is happening right now, this is basically how it works..

**Comment by hook54321a** [comment]
But it isn't in this repository and it isn't intended to be used as a block list.

**Comment by hook54321a** [comment]
On a side note, Brave doesn't seem to be concerned about it. https://github.com/brave/adblock-lists/commit/2c0e86cd5d8536a2ee74f2b8c31ea1b5a958dfcf

**Comment by Hrxn** [comment]
This is just glorious..

**Comment by okiehsch** [comment]
`functionalclam.com` is already blocked if you use uBO with a default setup, just force an update of the
`Peter Lowe’s Ad server list`. He added quite a few Admiral domains including functionalclam.

**Comment by hook54321a** [comment]
Ah. Then it's not an issue right now.

**Comment by gorhill** [comment]
Also for people following that issue, know that blocking `functionalclam.com` et al. is not always enough. For example, on `meta-chart.com`, which uses Admiral's stuff, the script pulled from `functionalclam.com` is entirely replicated as inline script at the bottom of the page pulled from `meta-chart.com`. So extra filters might be needed to take care of these cases.

**Comment by hook54321a** [comment]
https://twitter.com/getadmiral/status/896486274466533381
