### ISSUE TITLE
CSS rule :not with multiple selectors does not work

### ISSUE THREAD

**Issue by sztanpet** [gorhill/uBlock#2865]
### Describe the issue

On twitter, I want to hide the likes of my followers who like non-followed peoples tweets since it's already used for advertising.
Devised this rule to do that: `.tweet[data-you-follow="false"]:not(.permalink-tweet,.permalink-descendant-tweet,.permalink-ancestor-tweet)` but does not work, the element hiding helper gives it a red background and a capital E, it is a valid css rule though.
Tried separating it into three rules,

    ##.tweet[data-you-follow="false"]:not(.permalink-tweet)
    ##.tweet[data-you-follow="false"]:not(.permalink-descendant-tweet)
    ##.tweet[data-you-follow="false"]:not(.permalink-ancestor-tweet)

which does not work correctly since the :not is there so that directly linked tweets do not get hidden, but they do.

### One or more specific URLs where the issue occurs

https://twitter.com/StarCraft/status/896115349938094081

Nothing shows up, everything is hidden when the original rule is broken into three. With the original rule, it should work fine and everything should be visible.

### Your settings

- OS/version: Win/10
- Browser/version: Chrome Version 60.0.3112.90 (Official Build) (64-bit)
- uBlock Origin version: 1.13.8 and uBlock Origin Extra 2.34

##### Your filter lists

Default filter lists + HUN

**Comment by gwarser** [comment]
How about 
    ##.tweet[data-you-follow="false"]:not(.permalink-tweet):not(.permalink-descendant-tweet):not(.permalink-ancestor-tweet)

**Comment by gorhill** [comment]
No issue with uBO, your CSS is wrong.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sztanpet** [comment]
ah, its only valid in jquery to have multiple selectors in :not, noted, thank you!
