### ISSUE TITLE
Firefox 55.0.1 uBlock Origin is preventing Style Editor from Loading when enabled in a page

### ISSUE THREAD

**Issue by Meeplee** [gorhill/uBlock#2868]
### Describe the issue
On Firefox 55.0.1, tested both on Windows and Mac OSX
the Style Editor (Tools -> Web Developer -> Style Editor, or just F12 -> Style Editor, its on the same toolbox as the Inspector) will not load any file if uBlock is currenty enabled for that page.

For some reason, this issue does not happen when using Private Browsing.

Javascript Console doesn't show anything that could be related to the issue, only regular blockings resulting from the addon's functionality.

### One or more specific URLs where the issue occurs

Any URL that isn't whitelisted by uBlock Origin

### Screenshot in which the issue can be seen

Screenshots are from a pt-PT Locale of Firefox, some interface elements blurred/removed for privacy concerns

**Windows 10 Firefox x64, Google Homepage:**
uBlock Origin Enabled (Style Editor "Editor de Estilos" doesn't show any files in sidebar)
![screenshot](http://i.imgur.com/cnCinre.png)

uBlock Origin Disabled (Style Editor "Editor de Estilos" shows in sidebar, and content)
![screenshot](http://i.imgur.com/aXbJogm.png) 

**OSX Sierra Firefox, Reddit Homepage:**
Normal Tab, uBlock Enabled, Editor Doesn't Load
![screenshot](http://i.imgur.com/fAP85Uh.png)

Normal Tab, uBlock Disabled, Editor Loads (Editted the login field, forgot to remove credentials)
![screenshot](http://i.imgur.com/MWCqSFu.png)

Private Tab, uBlock Enabled, Editor Loads
![screenshot](http://i.imgur.com/Kms2YTf.png)

### Steps for anyone to reproduce the issue
1. Open a page in a Normal tab (Not a Private Tab)
2. Make sure uBlock is Enabled on that page
3. Try to load the Style Editor from the Web Developer Toolbox (As described above)

### Your settings

- OS/version: Windows 10 Pro x64, OSX Sierra 10.12.6
- Browser/version: Firefox x64 for Windows (Release), Firefox for OSX (Release)
- uBlock Origin version: 1.13.8

Only setting that differs from default is the show uBlock Origin on the right-click context menu.

##### Your filter lists

Default Lists (w/ Updates)

**Comment by gorhill** [comment]
I can't reproduce on `www.google.pt`. (Provide the URL next time [_as requested_](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include), having to transcribe what is in the screenshot is tedious -- I do say "even if it happens everywhere" is bold and uppercase).

I can reproduce only on `reddit.com`, but I can reproduce also with uBO completely disabled in `about:addons`.

Hence, issue looks unrelated to uBO.

**Comment by gorhill** [comment]
Ok, if I wait long enough for `reddit.com` without uBO, eventually the styles are loaded -- but not always.

With uBO, the styles are never loaded. If I whitelist the `iframe` from `www.redditmedia.com/gtm/jail` (normally blocked by EasyPrivacy's `||redditmedia.com/gtm/jail?`) that the page tries to load, the styles are now properly loaded.

So it appears the style editor is sensitive to frames being blocked on a page. This is an issue which should be reported to Firefox devs: <https://bugzilla.mozilla.org/>.

Using the webext version of uBO makes no difference, which further confirm this is a browser-side issue.

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1337330

**Comment by Meeplee** [comment]
>(Provide the URL next time as requested, having to transcribe what is in the screenshot is tedious -- I do say "even if it happens everywhere" in bold and uppercase)

I apologize for this, i tried several websites and was getting it consitently so i thought the url didn't matter that much.
