### ISSUE TITLE
It seems websocket connections cannot bypass uBlockOrigin on chrome 58 and above.

### ISSUE THREAD

**Issue by crocket** [gorhill/uBlock#2869]
### Describe the issue

README says websocket connections bypass uBlock Origin.

https://bugs.chromium.org/p/chromium/issues/detail?id=129353#c87 says `chrome.webRequest.onBeforeRequest` intercepts websocket requests on chrome 58 and above.

Is it time to change README and other documents?

**Comment by gorhill** [comment]
Fixed with 1bda3a1c. Thanks for reporting.
