### ISSUE TITLE
keyboard shortcut for element picker no longer working

### ISSUE THREAD

**Issue by foss-** [gorhill/uBlock#2870]
The keyboard shortcut which worked in previous uBlock Origin versions in Firefox is no longer working.
uBlock origin 1.13.9RC1
Firefox 56b2 or
Firefox 57 nightly
macOS 10.12.6

Keyboard shortcut setup for element picker
![ublock origin shortcut](https://user-images.githubusercontent.com/5708172/29279382-e3c72bac-8117-11e7-83c0-81dc6f3c84b5.jpg)

**Comment by gorhill** [comment]
The commands are declared in the manifest. The missing part is the browser missing the UI to assign shortcuts: <https://bugzilla.mozilla.org/show_bug.cgi?id=1303384>.

**Comment by foss-** [comment]
Thanks for the feedback. I do not understand this yet though. Does this mean, it is a regression in firefox? Because the shortcut used worked in previous versions of firefox. I tried a bunch of different shortcuts alt-SomeLetterHere but non would work.

**Comment by yourduskquibbles** [comment]
FYI for all it look it may now be possible to set extension shortcuts in Firefox v60 if I am reading this [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) discussion properly. There seems to be implementation documentation [1] [2] and example [3] as well.

[1] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update
[2] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/reset
[3] https://github.com/mdn/webextensions-examples/tree/master/commands
