### ISSUE TITLE
[Edge] Can't fetch http://localhost/personal_filter.txt

### ISSUE THREAD

**Issue by eEIi0A5L** [gorhill/uBlock#2875]
Can't fetch 'http://localhost/personal_filter.txt' but 'https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/mochi_filter.txt' was OK.

Why I can't fetch my own filter file from localhost?
This issue only happen on the Edge. Firefox and Google Chrome are fine.

Browser: Edge 40.15063.0.0
Ublock Origin: 1.13.8

**Comment by gorhill** [comment]
This is not the place to report issues with Edge.

<https://github.com/nikrolls/uBlock-Edge/issues>.

Also, your issue does not seem to be related to uBO anyways, investigate on your side before opening an issue, most likely explanation is that your `localhost` is the issue.
