### ISSUE TITLE
scriplet injections are Not Logged

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2877]
Can you add Logging of scriplet injections? As far as I can tell, that's the only type of rule that's not already logged.

**Comment by joey04** [comment]
I decided to take a stab at adding this tonight, and thankfully got some results pretty quickly.

I'm using the rule:
`thefreedictionary.com##script:inject(setTimeout-defuser.js, warn)` 


![all](https://user-images.githubusercontent.com/14959062/30576133-b41bd754-9cd3-11e7-9eca-1e14d23fa2d5.png)

Note the `>>` marking (opposite of redirect).

But it's obviously in a preliminary state, and filtering shows that this one injection is being logged 4 times for a single page load:

![inj](https://user-images.githubusercontent.com/14959062/30576131-b2060da4-9cd3-11e7-86d0-a91aba6f6a7b.png)

Here's the diff of work so far:
[code.diff](https://github.com/gorhill/uBlock/files/1313076/diff.txt)

There are 3 marked TODOs for tabID (currently -1), getting scriptlet name, and proper pagename. (The retrieveUserScripts function has domain and hostname inputs.) Assuming these get resolved, there's also the matter of logging 4 different times.

@gorhill -- is this the right place to log these?  Any other thoughts/comments?

**Comment by joey04** [comment]
note: just edited prior post with a new diff file. I had incorrectly swapped the file orders resulting in minuses instead of plusses. It's a correct patch file now.

**Comment by Remu-rin** [comment]
@gorhill 
Thanks for the fix. Now it's easy to observe scriptlets and I have a question, triggered by https://github.com/uBlockOrigin/uAssets/commit/43eb4648ba1126a58c933177da00154d469536dd
Is $badfilter supposed to work with script:inject filters? Looks like it works only for the exact string where it's placed. If the same script:inject exists somewhere without $badfilter (e.g. uAssets), then it's not discarded and working.

**Comment by gorhill** [comment]
`badfilter` is only for network filters.

`script:inject` is parsed as a cosmetic filter, so if you want to cancel it, just use the exception filter syntax:

    #@#script:inject(...)

The exception syntax `#@#` for cosmetic filters is equivalent of `badfilter` for network filter.

**Comment by Remu-rin** [comment]
Thanks, it works as expected.

**Comment by Remu-rin** [comment]
> Is the scriptlet filter for 4chan.org causing issues?

Didn't saw edit. Not now, but back then the first version of filter for 4chan (linked above) broke Violentmonkey there, as you remember. So I thought it would be useful to know how to disable specific scriptlet filter if some problems occur in the future, since now injections would be logged properly.
