### ISSUE TITLE
Revisited: no icons uBO (and uM) interface - Firefox 55

### ISSUE THREAD

**Issue by BelladonnavGF** [gorhill/uBlock#2878]
First of all, I apologise for (re)opening this issue. I know it has been discussed extensively in the past. Nevertheless, I wanted to report it, since it seems actual again. Also, please note that I realise that this issue might not be relevant any more, or might solve itself with the (FireFox) transition to Webext addons (not tried yet)...

With the upgrade of Firefox from 54 to 55, both uBO and uM interfaces don't show their icons any more. This is seen (reproduceable) on multiple boxes (uBO 1.13.8, uM 1.0.0).

As mentioned before, the cause is that on all these boxes that show this behaviour, `browser.display.use_document_fonts` was set to 0. Setting a default font under `about:preferences` doesn't resolve this issue. Restoring `browser.display.use_document_fonts` to 1 (default) however does.

That said, as discussed  here on Git before, this setting does not block JS driven font download, use, and profiling/ finger printing/ tracking. Setting `no-remote-fonts: * true` in uBO does not block JS fonts, nor does ticking `Block remote fonts` in uBO (or both). In Troubleshoot, @gorhill mentioned that setting `browser.display.use_document_fonts` to 1 might not be needed to give uBO and uM access to its font-icons, because 

> [...] choose a default font other than "serif". "Liberation" and "Clear" are known to work.

In addition, @gorhill pointed out correctly that

> In Firefox 41 browser.display.use_document_fonts=0 [won't break font-based icons](https://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/).

However, with the upgrade from FF 54 to 55, all this doesn't seem to apply any more (with `gfx.downloadable_fonts.enabled` set to `true`).
Even more confusing, the icon-fonts seem to be available/ used in some way; for example the "padlock" icon is not shown if greyed out (no changes), but is shown when changes have been made (`browser.display.use_document_fonts=0`). 
![screenshot_2017-08-16_10-06-58](https://user-images.githubusercontent.com/19425080/29353718-79093aa8-826b-11e7-840e-43f287c5043f.png)
![screenshot_2017-08-16_10-07-28](https://user-images.githubusercontent.com/19425080/29353735-86e637fc-826b-11e7-9eb3-dad666563a4e.png)

- (Personal stupidity disclaimer ☺): Am I the only one seeing this behaviour or might this indeed be caused by differences between FF 54 and FF 55? After all, it's difficult to miss Mozillas lovely [LEGACY](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) tag.
- Apart from setting `browser.display.use_document_fonts=1`, is there another solution to restore the uBO and uM GUIs? And yes, I've seen previous Git discussions, and no, they don't work anymore.
- Will/ is this still be an issue with the Webext versions which @gorhill released for [uBO](https://github.com/gorhill/uBlock/releases) and [uM](https://github.com/gorhill/uMatrix/releases)?
- _Only if this is still an issue with the Webext versions:_ with more and more JS forced font use, this seems not to achieve one of uBO/ uMs main goals: disable font finger printing/ tracking. Although I appreciate @gorhill argument about the ease of working with font-icons, shouldn't the use of local svg icons be considered again?

**Comment by gorhill** [comment]
> Restoring `browser.display.use_document_fonts` to 1 (default) however does.

So what exactly is the issue?

If you worry about fingerprinting, you need to worry about a whole lot of other things than just fonts. I suggest you toggle `privacy.resistFingerprinting` to `true` in `about:config`.

**Comment by BelladonnavGF** [comment]
Sorry if I wasn't clear... The issue is:
In FF 54, with `browser.display.use_document_fonts=0`, uBO and uM worked fine. All (font) icons on the GUIs were there. In addition, no fonts were downloaded (= easier on my miserable bandwidth + prefered uniform web experience).
With the update to FF55, `browser.display.use_document_fonts=1` is required for workable uBO and uM GUI interface (see screenshots). Hence the questions were:

- Since only FF changed I assume something changed in FF and not uBO and uM?
- With the transition to Webex addons, will the previous behaviour return (=OK uBO and uM GUI with `browser.display.use_document_fonts=0`)?
- And noticed since my original message: toggling the "Block remote fonts" option in uBO has no effect;  prefered (local) font is still not displayed.

PS THX for `privacy.resistFingerprinting`. No its not a concern, and didn't know about that one. But then again, saw it was 1st introduced in FF55?

**Comment by gorhill** [comment]
If I set `browser.display.use_document_fonts` to `0` in Firefox 55.0.1, the popup panel of uBO renders just fine, with all the FontAwesome-based icons displayed properly. I can't reproduce the issue seen in your screenshots.

**Comment by gorhill** [comment]
It looks to me like your previous issue: your default local font has glyphes defined for some of the FontAwesome slots, and thus it pulls the glyph from your local font instead of the FontAwseome font.

**Comment by BelladonnavGF** [comment]
Yeah, I remember writing you about that before. THX for reminding me. Will play around with that. THX again for your lighting fast replies!
