### ISSUE TITLE
Flag for off hyperlink auditing in Chrome

### ISSUE THREAD

**Issue by kurtextrem** [gorhill/uBlock#288]
chrome://flags/#disable-hyperlink-auditing
That should be it. Just wanted to make sure you know it for the next release changelog.. not sure if it disabled the beacon, but it is something.

**Comment by gorhill** [comment]
Ok, so there is some sort of UI. No way this is something most people would mess up with though.

**Comment by gorhill** [comment]
Release notes corrected.
