### ISSUE TITLE
uBlock Origin does not work

### ISSUE THREAD

**Issue by ovalseven8** [gorhill/uBlock#2880]
I am using Firefox 55.0.1. on Lubuntu 16.04 and have installed uBlock Origin.

Unfortunately, it does not really work and I can't find any reason for it. I also tried the reinstallation of the addon already.
When I visit websites with (typically) a lot of ads nothing is blocked.

Also uBlock Origin shows that since the installation 0 % has been blocked.
Sorry, can't say more but wanted you to let it know.

Perhaps you can fix it or tell me a possible reason for it so that I can change something.

Version: 1.13.8

**Comment by gorhill** [comment]
In the "3rd-party filters" pane, how many filters are reported?

Any other extensions installed?

**Comment by ovalseven8** [comment]
Yeah, also NoScript is installed. But that was not a problem in the past.

I use all the default filters....

**Comment by ovalseven8** [comment]
@gorhill 
I have reset all settings now and it's working again. No idea what was wrong here.
Thanks for your reply!

**Comment by ovalseven8** [comment]
@gorhill 
Every time I reboot my system the problem occurs again and I have to reset the uBlock Origin settings to make the addon work again. Do you know what is wrong here?

**Comment by gorhill** [comment]
You will have to investigate the issue on your side. uBO settings are saved into the file `extension-data/ublock0.sqlite`. Maybe the file is corrupted, see if deleting it helps. Otherwise, can't help, I would have to bit sat at your computer to investigate -- you are better placed than me for this.

**Comment by ovalseven8** [comment]
Hi @gorhill, it's me again.

Now I've already tried to delete the SQLite database and I've also removed my Firefox profile. Nothing works. After reboot sometimes it just does not work:
![2017-08-26-211834_1920x1080_scrot](https://user-images.githubusercontent.com/8258609/29744405-788f2c54-8aa4-11e7-8ac5-35a4ae4903e6.png)

**Comment by gorhill** [comment]
You never answer [my questions above](https://github.com/gorhill/uBlock/issues/2880#issuecomment-322874206).

Also, do not presume other extensions can't possibly interfere because they were "not a problem in the past". So far you have a problem unique to you, you needto throw out all assumptions and very methodically narrow.

**Comment by ovalseven8** [comment]
Well, the only other add-on I use is NoScript. But I think a lot of people use uBlock Origin and NoScript together. Thank you for your work by the way, I really like uBlock Origin! :)

![2017-08-27-100317_1920x1080_scrot](https://user-images.githubusercontent.com/8258609/29748115-1351bc7e-8b0f-11e7-8513-fe6c34475e56.png)

**Comment by gorhill** [comment]
> 0 network filters + 0 cosmetic filters

I can't make sense of this. Anything at the browser console?

**Comment by ovalseven8** [comment]
Sorry, I didn't find a place where Firefox logs about those things. Can you say me where I have to look?

**Comment by gorhill** [comment]
<ctrl>-<shift>-J

**Comment by gorhill** [comment]
Are you using the 32-bit version of Firefox?

**Comment by ovalseven8** [comment]
No, I am using Firefox 55.0.2 (64 bit) and normal uBlock Origin (old technology, not WebExtensions).

**Comment by ovalseven8** [comment]
Well, I am using "uBlock Origin/webext-hybrid" to be exact.

**Comment by gorhill** [comment]
> I am using "uBlock Origin/webext-hybrid" to be exact.

That makes a difference. Maybe you are suffering #2909? Try uninstalling uBO, quit/restart Firefox, then re-install uBO.
