### ISSUE TITLE
Element picker does not work from right-click context menu

### ISSUE THREAD

**Issue by gms77** [gorhill/uBlock#2882]
### Describe the issue
When selecting the element picker from the context menu (Block element) it does not open.  It does work from the toolbar button icon though.

### One or more specific URLs where the issue occurs
https://github.com/gorhill/uBlock

### Screenshot in which the issue can be seen
![screenshot_20170817_142758](https://user-images.githubusercontent.com/15159047/29414661-4f1f9c62-8358-11e7-8812-16aca5275837.png)

### Steps for anyone to reproduce the issue
Open the url above while not logged into github.
There is a large area with "Join github today".
I don't want to see that so I right-click over it and select Block Element.
Nothing happens.
Open the browser console and notice "Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive." (This error appears every time I try the Block element menu).

### Your settings
- OS/version: Linux (KDE Neon User Edition)
- Browser/version: Firefox 56b3
- uBlock Origin version: 1.13.9rc3

##### Your filter lists
Default + Fanboy's Annoyance + AAK-Cont filter for ublock origin

**Comment by gms77** [comment]
Forgot to add, the only extension I had enabled was ublock origin.

**Comment by gorhill** [comment]
For reasons I do not understand, `self.vAPI` in `contentscript.js` is seen as `undefined`, despite it being set in `vapi-client.js`.
