### ISSUE TITLE
Responsive design mode blocks the "picker"

### ISSUE THREAD

**Issue by bbb31** [gorhill/uBlock#2886]
Some ads only show up when using a small device; the element picker does not work when going into this mode: CTRL + SHIFT + M

Firefox 55

**Comment by shevegen** [comment]
Do you possibly have a screenshot? I am only asking out of curiosity, I have no small device myself to see how it looks like.

**Comment by gorhill** [comment]
As asked in CONTRIBUTING, please provide a detailed test case.

**Comment by bbb31** [comment]
Screenshot below:

![screenshot_2017-08-20_12-00-48](https://user-images.githubusercontent.com/24252625/29496394-b4669334-859f-11e7-974f-9bbbb2d4eff8.png)

Weird part is now the picker is not showing up; yesterday it was showing up, and then upon clicking within the screen real-estate of responsive design mode nothing happen.

**Comment by gorhill** [comment]
The same underlying issue as the one raised in #2906.
