### ISSUE TITLE
When showing the logger, don't show about: and newtabs

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#2887]
**Showing about: and newtabs in the logger just clutters the logger**

![ubo-filters](https://user-images.githubusercontent.com/1659004/29491983-23390ffa-85c1-11e7-8891-834f466f0ec6.png)

Too much clutter having non-needed windows (about:* and New Tab) showing up in the list, should be limited to websites only. Probably also applies to a number of extension/firefox-related tabs, since webextensions such as uBo cannot filter them anyways

**Comment by gorhill** [comment]
Browser/version, uBlock/version.

**Comment by ryanbr** [comment]
FF Nightly + 1.13.8

**Comment by gorhill** [comment]
Which flavor of uBO 1.13.8? Legacy? Webext-hybrid? Webext?

**Comment by ryanbr** [comment]
Legacy for the moment

**Comment by gorhill** [comment]
Never mind, you are using legacy from the URL in the logger.

Don't use legacy extension with Nightly, it's expected there will be issue, more and more as Nightly move forward. Use pure webext, available in dev channel on AMO.

**Comment by ryanbr** [comment]
Seems better, though did see an instance of "New Tab" show up

**Comment by gorhill** [comment]
If there is a "New Tab" tab, it will be shown. In Chromium, a "New Tab" tab can make network requests, and these are processed by uBO just like any other tab.

**Comment by ryanbr** [comment]
how can a new (or essentially a blank) tab, make network requests? also even if it did, no one could filter it

**Comment by gorhill** [comment]
Try in Chromium or Chrome. Maybe it will also become like this in Firefox, I don't want to rule out it will never happen with Firefox.

Anyway, I don't see New Tab in the list if I open a new tab. Whatever `browser.tabs.query` returns, uBO will list it -- it shouldn't start to second guess the API about what is worth showing and what is not worth showing: if the API reports it, it will be reported by uBO.
