### ISSUE TITLE
logger's entries disappearing on search

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#2888]
windows 10
chrome Version 61.0.3163.49 (Official Build) beta (64-bit)
uBo 1.13.8
default filters

- open the logger
- go to `https://seriesblanco.com/`
- in the logger page use chrome search (press F3) and search for "blanco". Continue pressing F3.
Result ==> some entries (filters / item address) will be blanked 

![bug ubo](https://user-images.githubusercontent.com/10303732/29493221-9ba49650-8592-11e7-951b-5bc5477136a0.PNG)

- The same behaviour turning OFF uBo for the page and using only the logger
- It happens on all the pages you want to test

**Comment by gorhill** [comment]
- Can't reproduce with Chromium 60 (stable).
- Can't reproduce in Firefox Nightly.
- Can reproduce with Chrome 62 (dev).
- If I toggle the `white-space` style in the style inspector for a problematic cell, the text comes back for all cell.
- The inspector shows that the text node is there -- the browser just cease to render it.

Browser bug, report to Chromium devs.
