### ISSUE TITLE
Disabling hyperlink auditing/beacons in newest dev version

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#289]
Are there any negative consequences for the user to disabling pinging and beacons?  Specifically, does it break any sites?   Also, does it prevent any referral/affiliate/discount/other systems from working?

The [referenced thread](http://www.wilderssecurity.com/threads/hyperlink-auditing-aka-a-ping-and-beacon-aka-navigator-sendbeacon.364904/) has great info on the technical details, but no info on the impact of disabling these "technologies".

BTW, the latest release of Firefox (38.0.5 as of this writing) appears to have pinging disabled and beacons enabled by default.

**Comment by gorhill** [comment]
>  Specifically, does it break any sites?

I don't know.
