### ISSUE TITLE
Blocked add number location over smallicon

### ISSUE THREAD

**Issue by alike03** [gorhill/uBlock#2890]
Hi, I find it quite annoying that the number goes into the Window. 
Can you guys move it abit lower or add an option to move it lower.
I know there is an option to disable the number completely but I want actually know how many adds got blocked.

![icon](https://user-images.githubusercontent.com/8145921/29536044-9836970e-86bc-11e7-9e74-efa9cbb79f62.jpg)

**Comment by Hrxn** [comment]
First of all: Installing uBO together with ABP - completely unnecessary, rather harmful. Don't do it.

Second, you seem to be using some other 3rd-party extensions, something like "Classic Theme Restorer" and its ilk. They are not compatible with WebExtensions, the format Firefox will be using with version 57 (November this year, basically), and thus will stop working.
You should consider getting rid of these altogether..

**Comment by gorhill** [comment]
The badge UI is controlled by Firefox. Use user styles that suits you best to control its appearance.

With the coming release, the number of requests blocked will be also reflected in the icon tooltip, so will be able to disable the badge and still get the information about the number of requests blocked.
