### ISSUE TITLE
uBlock 1.13.0 and later is not working on Opera 20.0

### ISSUE THREAD

**Issue by Audiomaniac** [gorhill/uBlock#2892]
With uBlock 1.12.4 everything was fine.
When I update it to newer version from https://addons.opera.com/en/extensions/details/ublock/?display=en
uBlock became unusable
1. filters not load:
![ublock_1 13_shit2](https://user-images.githubusercontent.com/31223361/29601787-e8dbba52-87e5-11e7-803c-26eb9dd811bf.png)
2. uBlock settings, buttons: "back up to file", "Restore from file" - unclickable :(
![ublock_1 13_shit](https://user-images.githubusercontent.com/31223361/29601631-25369d9c-87e5-11e7-8d21-c20cffb9c0a9.png)
3. no "element picker" icon:
![ublock_1 13_shit3](https://user-images.githubusercontent.com/31223361/29601637-2ca99e58-87e5-11e7-92d1-aab740aaa10d.png)

I tried:
1. delete extension from Opera menu.
2. Delete all extension garbage from Opera profile
C:\Users\Audiomanac\AppData\Roaming\Opera Software\Opera Stable
3. re-install Opera
nothing helps.

Steps to reproduce:
1. install Opera http://www.opera.com/download/index.dml/?os=windows&ver=20.0.1387.91
2. install uBlock 1.13.0 or newer
3. try to open uBlock settings/3rd-party filters
4. try to block any element with element picker on www.yahoo.com

Windows 7, 32-bit

Do not propose to install newer version. Because my old CPU not support it.

**Comment by aggat** [comment]
[Drop support for very old browser versions](https://github.com/gorhill/uBlock/issues/2612)
As far as I know, Opera 20 is based on Chromium 33
uBO 1.13+ needs Chromium 38+

**Comment by gorhill** [comment]
As pointed out by @aggat, minimum supported Opera version is 25.

> Do not propose to install newer version.

I will then propose you install an older version of uBlock Origin. [1.12.4](https://github.com/gorhill/uBlock/releases/tag/1.12.4) should still work.
