### ISSUE TITLE
Firefox Add-on "uBlock Origin" Interferes With Redirection of linkinghub.elsevier.com

### ISSUE THREAD

**Issue by kratzerm** [gorhill/uBlock#2893]
### What's happening?

Elsevier Science Direct uses a redirecting mechanism for DOI links to their scholar content. The Firefox Add-on "uBlock Origin" seems to interfere with that mechanism in a way that lets the user land on a blank page with title "Redirecting" instead of the abstract page of the desired article. 

### Example URL

The following DOI link  may be used to reproduce the issue:
https://doi.org/10.1016/j.jss.2005.05.011?nosfx=y

### Steps for anyone to reproduce the issue

1. Start Firefox with active add-on uBlock Origin.
1. Visit the example URL given above.
1. You will be redirected to http://linkinghub.elsevier.com/retrieve/pii/S0164121205001068 which appears to be a blank page with title "Redirecting".
1. Deactivate uBlock Origin.
1. Revisit the example URL given above.
1. You will be redirected to http://linkinghub.elsevier.com/retrieve/pii/S0164121205001068 first and subsequently land on http://www.sciencedirect.com/science/article/pii/S0164121205001068?via%3Dihub which is the abstract page of the desired article identified by the DOI.

### My settings

- OS/version: Windows 7
- Browser/version: Firefox 55.0.2 (32-Bit)
- uBlock Origin version: 1.13.8

##### My filter lists

Default filter lists + DEU minus
- uBlock filters -- Experimental
- EasyList without element hiding rules
- uBlock Protector List
- Spam404
- Fanboy+Easylist-Merged Ultimate List

I don't use any custom filter lists.

### Additional information

I have already contacted Elsevier Science Direct Support about this issue as well but they told me they had no means to provide me a support for uBlock. However, they offered a contact address in case you would need further information from them in order to fix the issue. So, please just let me know and I will forward that address to you as well.

Best regards
Mathias

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You should have ruled out a filter issue as asked in CONTRIBUTING, the logger shows that `||adobedtm.com^$third-party` from EasyPrivacy is causing the issue.
