### ISSUE TITLE
If uBlock icon is positioned as the last one, it always moves to overflow

### ISSUE THREAD

**Issue by khagaroth** [gorhill/uBlock#2898]
If uBlock icon is positioned as the last one, it always moves to overflow, even if there is plenty of free space for all the icons.

As a workaround, this problem can be resolved by putting some other icon after uBlock icon, or by disabling the blocked request indicator.

- OS/version: Windows 10
- Browser/version: Firefox 57 Nightly
- uBlock Origin version: 1.13.11rc0

**Comment by gorhill** [comment]
uBO is not responsible to position itself on the toolbar, the browser does this.
