### ISSUE TITLE
Offset from mouse pointer to click position

### ISSUE THREAD

**Issue by FreddyFlares** [gorhill/uBlock#2901]
### Describe the issue
When the browser is maximized there is an offset of ~(100, 0) pixels from where the mouse pointer is and where the click position is.

### One or more specific URLs where the issue occurs
http://bridgebase.com/client/client.php

### Screenshot in which the issue can be seen
![clipboard01](https://user-images.githubusercontent.com/2992974/29746446-8e764344-8ad2-11e7-9c02-f6acd3cb7611.jpg)
Without uBlock there is an Ad of about 100 pixels width docked to the left of the page.

### Steps for anyone to reproduce the issue
Enable uBlock.
Maximise the browser.
Navigate to above website.
Try to click around the site.

### Your settings
- OS/version: Windows 7 Home Premium 32 bit SP1
- Browser/version: Firefox 55.0.3 (32-bit)
- uBlock Origin version: v1.13.8

##### Your filter lists
Default filter lists

**Comment by gorhill** [comment]
It's not a uBO issue, it's a site issue as a result of using a blocker -- the site misbehave if their ad is blocked.
