### ISSUE TITLE
Make "My Filters" take precedence over everything

### ISSUE THREAD

**Issue by jsmad** [gorhill/uBlock#2904]
### Describe the issue

I found that several lists contain while-listed tracking domains/links (eg EasyList, EasyPrivacy) and I can't block them!

I would like "My Filters" to take precedence over ALL others, so I can block white-listed domains, even if I break some websites, which I really don't mind.

### Steps for anyone to reproduce the issue

1. Enable EasyPrivacy
2. Add segment.com to "My Filters"
3. Go to a website which tracks users via segment.com and watch it get white-listed by EasyPrivacy

### Your settings

I use default settings.

- OS/version: Fedora 25
- Browser/version: Firefox 55.0.1
- uBlock Origin version: 1.13.8

##### Your filter lists

Default + EasyList + EasyPrivacy + Anti-ThirdpartySocial + Fanboy’s Annoyance List​ + ​​​​​Fanboy’s Social Blocking List​

##### Your custom filters (if any)

||segment.com^

**Comment by mapx-** [comment]
use $important
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#important

example:
`||segment.com^$important`

**Comment by gorhill** [comment]
As pointed out by @mapx-, use `important` option to override exception filters. Another solution is to use dynamic filtering _block_ rules, they always override static filters from filter lists: <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide>.

**Comment by jsmad** [comment]
Terribly sorry for the inconvenience, I wasn't aware that dynamic filtering overrides static filters.
