### ISSUE TITLE
Firefox Responsive Design causes duplicate tabs in logger

### ISSUE THREAD

**Issue by quilloss** [gorhill/uBlock#2906]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Each time responsive design mode is entered, a duplicate tab appears in the logger.

### One or more specific URLs where the issue occurs

Not a site issue.

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Enter responsive design mode in the devtools.
1. Check the logger.
1. The process could be repeated for more duplicates.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: Firefox 56.0b6
- uBlock Origin version: 1.13.11rc0

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
First observations: when we click "responsive design", a new window is created and uBO is notified about this. However, for the previous window which is replaced by the new one, uBO's browser.tabs.onRemoved() listener is not called. So this appears to be a Firefox issue. (Same code onChromium works fine). I will need to invest time to create a minimal extension to highlight the issue and report to bugzilla. (If somebody could find out whether there is already such an issue opened, that would be nice).

**Comment by quilloss** [comment]
Tabcenter Redux seems to also suffer from the same issue.
https://github.com/eoger/tabcenter-redux/issues/140

Not sure if any bug was filed for that issue.

**Comment by gorhill** [comment]
It's a Firefox issue. Please file on Bugzilla, I don't have an account anymore there.

**Comment by LakenH** [comment]
@eoger from Tab Center Redux found a related bug on Bugzilla that handling this issue, and they've pushed some fixes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1404088
