### ISSUE TITLE
Webpages request to disable already disabled Adblocker?

### ISSUE THREAD

**Issue by bsto** [gorhill/uBlock#2907]
As I found out there are more and more webpages which complain about an Adblocker.
They ask the user to disable the AdBlocker.

BUT: uBlock on Firefox v55.0.3 under Win 7 is already completly disabled.

So I guess the Adblocker-check procedure of the webpage does not check if its ads are blocked but if the uBlock is installed (and possibly disabled).

So I am forced not only to disable the uBlock Plugin but to uninstall it

Can this be?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
