### ISSUE TITLE
Android options_ui workaround no longer required

### ISSUE THREAD

**Issue by pwd-github** [gorhill/uBlock#2908]
### Describe the issue
Because it weren't working, you used a workaround, the same thing you helped @mrdokenny with in https://github.com/mrdokenny/Cookie-AutoDelete/issues/12 however the underlying Firefox issues[1][2] have been fixed and thus you no longer need the workaround.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1302504
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1364945

### Screenshot in which the issue can be seen

![screenshot_2017-08-28-14-25-43](https://user-images.githubusercontent.com/203217/29775446-1478c1bc-8bfd-11e7-9ddb-1335786e3727.png)
![screenshot_2017-08-28-14-25-07](https://user-images.githubusercontent.com/203217/29775455-1bf4f6c2-8bfd-11e7-8bd9-c599b023f136.png)
![screenshot_2017-08-28-14-25-28](https://user-images.githubusercontent.com/203217/29775499-45d3978c-8bfd-11e7-92c2-d24983120fb6.png)

### Your settings

- OS/version: Android 7.0
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.13.11rc0

**Comment by gorhill** [comment]
Is says fixed for Firefox 57, so it still is needed for Firefox 55?

**Comment by pwd-github** [comment]
@gorhill Yup, from what I can tell, they've not uplifted the patches to 55 or 56, so the workaround would still be required for any pre-57 builds. Sorry, not the most useful heads up I know.

**Comment by mrdokenny** [comment]
From what I recall, [1302504](https://bugzilla.mozilla.org/show_bug.cgi?id=1302504) was added in FF 56. So the workaround would only be useful in one version.

**Comment by gorhill** [comment]
Fixed with ec3d1bfc88b01cab26ab5b01e67b6d5c1dce0542.

Firefox for Android has been [released a few days ago](https://www.mozilla.org/en-US/firefox/android/56.0/releasenotes/), I expect all the issues with `browserAction.setTitle` and `options_ui` to finally be a thing of the past.
