### ISSUE TITLE
Blocking of URLS?

### ISSUE THREAD

**Issue by joeparkerz** [gorhill/uBlock#2910]
How can I block these URLs with some sort of regex? They are downloaded / used on new tab.

https://www.google.si/_/chrome/newtab?espv=2&ie=UTF-8
https://www.google.si/_/chrome/newtab-serviceworker.js

**Comment by mapx-** [comment]
`||google.si/_/chrome/newtab*`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment]
for filter issues use this repository:
https://github.com/uBlockOrigin/uAssets/issues
