### ISSUE TITLE
The icons on the ublock GUI do not load

### ISSUE THREAD

**Issue by Tamren** [gorhill/uBlock#2912]
As far as I can tell Ublock works properly, however when I click on the ublock icon to open up the details panel, the panel is missing all of it's icons. They are replaced by "placeholders". I can't tell you how long it's been like this because I only noticed today when I was checking my addons for webextension compatibility, but Ublock did work correctly when I first installed it months ago.

Here's a picture.

![ublock problem](https://user-images.githubusercontent.com/25917471/29814786-68e571ee-8c63-11e7-9e07-f6ba8c5f70d3.png)

I'm not sure how to reproduce this on other computers but the icons are clearly not loading correctly. So they may be missing or can't be loaded from wherever the icons are stored. Reinstalling ublock didn't fix the problem.

It's possible that NoScript maybe be interfering with ublock because I only see placeholder icons like that when noscript is blocking a website from using custom icons and fonts.

My ublock settings are stock, I haven't changed anything.

- OS/version: Win 7 64-bit Home
- Browser/version: Firefox 55.0.3 32-bit
- uBlock Origin version:  1.13.10

**Comment by gorhill** [comment]
Do you have `gfx.downloadable_fonts.enabled` set to `false`?

**Comment by Tamren** [comment]
No it is currently set to "enabled" which is the default, this isn't the same issue as #605

After doing some testing with and without extensions I'm pretty sure the problem is NoScript and not Firefox. If I disable extensions and reboot firefox the icons return. 

![ublock problem 2](https://user-images.githubusercontent.com/25917471/29818421-20316c56-8c71-11e7-8783-dd4355f99053.png)

There is a line in about:config that says noscript.forbidFonts which is set to True. If I toggle this on and off ALL fonts come back or are removed, including Ublock. If I disable noscript from blocking fonts and then turn on ublock's font blocker I get my UI icons back and have to toggle fonts using ublock instead of noscript.  

This fixes the problem but it's a bit technical for most users. Ideally noscript could be set to whitelist ublock's fonts or add a setting to make an exception for locally hosted fonts like the ones ublock uses.

**Comment by gorhill** [comment]
Is `moz-extension:` whitelisted in your NoScript?

See <https://forums.informaction.com/viewtopic.php?f=7&t=21568#p89306>, maybe you want to add your input to this thread.

**Comment by Marc66** [comment]
I don't use NoScript and have the same issue since today's update. I only have a small empty icon half the size it should be and when I click on it, nothing happens. Running FF64 on win10

**Comment by Tamren** [comment]
Aha! I found the problem. Long story short this issue is caused by an option in Noscript. I didn't figure this out until I made a new profile and ported over all of my data except for extensions.

Basically there is an option in noscript called "apply these restrictions to whitelisted sites too". What that means is that everything everywhere will be restricted until you manually give it permission to run. Obviously this includes fonts, and moz-extension: is hard coded into the whitelist. For some reason I can't recall I had this option turned on, (it is not activated by default), so of course it was preventing ublock from loading fonts. Having figured this out, in the new firefox profile I deleted my noscript settings and reset them to default, this fixed the issue.

I don't think any action needs to be taken, that noscript option is not on by default and you usually only turn it on for a specific reason like troubleshooting. In the case where you want to have it on, the workaround I found still works. Flip noscript.forbidFonts from true to false and then turn on font management in ublock instead (which is off by default). This lets you restrict whitelisted sites while still having full font control and no messed up icons on the ublock UI.

**Comment by gorhill** [comment]
With the legacy version of uBO, the font resource was pulled from `chrome://`, not `moz-extension://`, I suppose NoScript does not mess with `chrome://` URLs?

**Comment by Tamren** [comment]
chrome: is listed on the whitelist too, so it would result in the same problem.

**Comment by jspenguin2017** [comment]
From https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest
> To use the webRequest API for a given host, you must have the "webRequest" API permission. You must also have the host permission for both the host that initiated the request, and the target of the request. 

There is no way to get host permission of protected schemes `chrome://` and `moz-extension://`, if NoScript can cancel a request from a protected extension context, then it is a bug of Firefox. 

I tested in Chrome and uBlock Origin isn't able to interfere with requests initiated from a privileged extension context of another extension.

**Comment by gorhill** [comment]
@jspenguin2017 I know this, but clearly NoScript still has the ability to handle all requests.

**Comment by Okamoi** [comment]
@Tamren Giorgio probably already accounted for this risk long ago, `moz-extension://` is recent. Forbidding `chrome://` things also probably triggered more obvious bugs.

**Comment by jspenguin2017** [comment]
@Okamoi In Chrome, uBO can't interfere with `chrome://` and `chrome-extension://` schemes, as well as the web store, `https://chrome.google.com/*`. I'm not sure why `chrome://` scheme is in the default white list as uBO doesn't have the privilege to interfere with those page to begin with. 

In Firefox, it should be similar as per their documentation, but the security seems to be bugged right now.

**Comment by Okamoi** [comment]
NoScript can, we're talking about NoScript :)

It is the one messing up uBO since 1.13.10. I hope nothing beyond @font-face is affected though.

**Comment by jspenguin2017** [comment]
> NoScript can, it's a NoScript bug :)

You can access more than you are suppose to, you are broken or the door is broken?

**Comment by Okamoi** [comment]
NoScript isn't a WebExtension yet, legacy add-ons can access whatever they want.
