### ISSUE TITLE
Firefox + Vimperator and UBlock Origin menu

### ISSUE THREAD

**Issue by dschrempf** [gorhill/uBlock#2913]
I am referring to the closed issue #964.

The workaround (namely using the legacy toolbar button) does not work anymore. The menu does not show when clicking the button while having the navigation bar disabled.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You did not provide the minimum amount of information asked from you

**Comment by dschrempf** [comment]
Thank you very much for your answer. I understand that developing and maintaining software is a lot of work but I do think that your behavior is neither friendly nor professional.

I was referring to another issue where you can find a detailed explanation of the problem and how to reproduce it. My version of UBlock Origin is 1.13.10, my version of Firefox is 55.0.3.

Again, I want to thank you very much for your work. I really appreciate it.

Dominik

**Comment by gorhill** [comment]
> My version of UBlock Origin is 1.13.10

I will guess the stable release of 1.13.10. As explained in the release notes, this is a webext (hybrid) version. uBO no longer control it's own placement in the toolbar, the WebExtensions framework controls this.

**Comment by dschrempf** [comment]
Thanks for the clarification. I am sorry, I did not know about this. I found a workaround for vimperator, in case you are interested: https://github.com/vimperator/vimperator-labs/issues/465

Cheers!
