### ISSUE TITLE
uBlock Origin 1.13.10 not supported on ESR builds

### ISSUE THREAD

**Issue by runboy93** [gorhill/uBlock#2914]
Not supported anymore on Mozilla Firefox 52.x ESR builds, not able to download or use it. 1.13.8 was last working version, not even 1.13.11rc build doesn't work (legacy)

**Comment by gorhill** [comment]
Read the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.10), more specifically [Firefox WebExtensions documentation](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions).
