### ISSUE TITLE
No issue with ublock_origin-1.13.11rc0-an+fx (development, full webextension)

### ISSUE THREAD

**Issue by mazesy** [gorhill/uBlock#2916]
uBo 1.13.11rc0-an-fx / Waterfox 55.0.2 / Windows 7

As many I have as well encountered the uBo 1.13.10 hybrid update version.
I restored my previous Waterox profile bringing back uBo 1.13.8
I saved my uBo settings
I uninstalled uBo 1.13.8, deleted its extension-data folder.
I installed ublock_origin-1.13.11rc0-an+fx from uBo's AMO / development channel page
I restored my previously saved settings
uBo running like a charm.

All this fuss with the hybrid legacy to webextension 1.13.10 version because apparently of a Firefox problem when not that of uBo is annoying, especially for gorhill.

It's not complicated to proceed as I did and it leads to a full Webextension and fully functional and reliable uBo

**Comment by doc75** [comment]
I confirm that uBlock origin stopped working after an update.
Uninstalling, then reinstalling make it work like a charm.

**Comment by crssi** [comment]
On one computer 1.13.10 update went OK, on other didn't... so I went there 1.13.11rc0 and works.
Both computers are with FF 55.0.3

What I see uBO is now slow.

**Comment by crssi** [comment]
NAh... the icon went gone on the second computer with 1.13.10... had to updated to 1.13.11rc0.
It works now but uBO is slow.

**Comment by gorhill** [comment]
Report to `https://bugzilla.mozilla.org/`.
