### ISSUE TITLE
LogMeIn Keeps Getting Blocked

### ISSUE THREAD

**Issue by greentrancer** [gorhill/uBlock#2918]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I log into my account and the page below is white, even thought it is whitelisted in uBlock. The only way to get it working is to disable the entire uBlock add-on and restart the browser.

### One or more specific URLs where the issue occurs
https://secure.logmein.com/central/Central.aspx

### Screenshot in which the issue can be seen
https://s26.postimg.org/kx40mk989/firefox_2017-08-29_15-22-03.png

### Steps for anyone to reproduce the issue
Just use uBlock Origin and log into the website.

### Your settings
- nothing as far as I know

- OS/version: Windows 10
- Browser/version: Firefox 55.0.3 (64 bit)
- uBlock Origin version: 1.13.10

##### Your filter lists
https://s26.postimg.org/a2mkkmq49/2017-08-29_15-23-53.png

##### Your custom filters (if any)
- none

**Comment by gorhill** [comment]
Did you look at what is occurring in the logger to rule out a filter issue -- as requested in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)?

**Comment by greentrancer** [comment]
Okay, so this is what I get in there when I reload the page and it is blank:
https://s26.postimg.org/q9jo97id5/2017-08-29_17-00-43.png

**Comment by gorhill** [comment]
Select the _All_ entry in the logger to see all the network requests, including those who could be made i other contexts.

**Comment by greentrancer** [comment]
Part 1: https://s26.postimg.org/ox1z7bkxl/firefox_2017-08-29_17-11-24.png
Part 2: https://s26.postimg.org/ixe83o055/firefox_2017-08-29_17-11-46.png

Does this help? Thank you.

**Comment by gorhill** [comment]
> Just use uBlock Origin and log into the website

I don't have an account, and frankly I rather not give my email to that site. Please make a throwaway account for me to use to log in.

Also, I can't make sense of uBO being the issue since nothing is blocked as per logger. It would be better if you keep investigating. For example, try to disable all filter lists in order to end up with zero fitlers enforced, and see if this makes a difference.

**Comment by greentrancer** [comment]
I am not sure why everything pointed out uBlock Origin yesterday, because I looked into this again and I found the cause - Windscribe plugin.

uBlock Origin seems to be blocking some bits as well, as long as it is turned on for the website, but in this case I 'whitelisted' the website in Windscribe and it works again, as expected. Thank you and sorry for this confusion!
