### ISSUE TITLE
[Firefox] Unchecking uBlock's Hyperlink-Auditing option enables pings even though browser default is *false*

### ISSUE THREAD

**Issue by vlaszlo** [gorhill/uBlock#292]
With uBlock 9.8.5.0-rc0's option unchecked, I can temporarily change the hyperlink auditing browser option to the default, which is _false_ in today's Firefox Nightly, but a uBlock or browser restart will set it to _true_ again. I'd suggest the following behavior instead:
- uBlock's privacy option checked: Always make sure that hyperlink auditing and beacon are disabled (i.e. no change to current behavior).
- uBlock's privacy option unchecked: Right after the user's unchecking, reset the options to the browser default values (at the moment: beacon _true_, ping _false_) and leave them alone afterwards.

This would have to be communicated through the UI, either in the option's description text or by making the info icon a help box like with uMatrix' privacy options.

Reasoning for the suggested change:
- If Mozilla decides to enable ping by default in the near future, a bug in the feature might force them to at least temporarily disable it again as has happened with security bugs in similar features in the past. A user with uBlock's option unchecked will possibly be vulnerable in such a situation without knowing. 
- The user might want to do his/her own micro-management of options. Right now it's not possible to have beacon enabled with ping disabled or vice versa.

**Comment by gorhill** [comment]
If _"Disable [...]"_ is not checked, it means leave the settings alone.

**Comment by vlaszlo** [comment]
This might be a misunderstanding, but I don't see any change in behavior. With uBlock's option checked, it monitors Firefox' preferences on browser or extension restart and makes sure they're both disabled. So far so, good.

But with uBlock's option unchecked, I still can't permanently enable beacon and disable ping, for instance. As soon as I disable/enable uBlock 0.9.8.6 or restart the browser, uBlock enables ping again. Is that the intended modus operandi?

**Comment by gorhill** [comment]
> I still can't permanently enable beacon and disable ping, for instance

Works from here. Steps:

- Unckeck _"Disable hyperlink auditing/beacon"_ (uBlock will restore values it saw at launch).
- Disable uBlock.
- Set the values in `about:config` as you wish (a reset both `beacon.enabled`, `browser.send_pings`).
- Enable uBlock.
- Values are left in the current state.

Unchecking _"Disable hyperlink auditing/beacon"_ means "Do not change values", or if there were changed after launch, it means "restore the values to their original settings if and before uBlock changed them".

**Comment by vlaszlo** [comment]
> ...or if there were changed after launch, it means "restore the values to their original settings before uBlock changed them".
So, in a way I have to train uBlock for my preferred values, by making it see them on startup. In my testing, I managed to get it into a state where it would always re-enable pings, by omitting the "disable uBlock" step above, but it's all good now. So, confirmed fixed and thanks for explaining.

**Comment by gorhill** [comment]
> I have to train uBlock for my preferred values

It can become complicated if uBlock thinks it controls the values, and the values are changed directly by the user. I see there is a [`lockPref`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefBranch#lockPref%28%29) in the Firefox API, maybe I could make use of this. A setting controlled by uBlock would be locked, so a user would be forced first to disable them in uBlock to change them manually -- this should take of eliminating ambiguity arising from being able to change a pref from two places.

I will see if this work.

**Comment by gorhill** [comment]
Ok, I added one line, which causes uBlock to forget immediately the original value when you uncheck the setting in uBlock. So if you change that setting directly in `about:config` without disabling uBlock, uBlock won't override it now.
