### ISSUE TITLE
Auto removed from the extension bar on opening cricbuzz.com

### ISSUE THREAD

**Issue by ssingh55** [gorhill/uBlock#2920]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
On opening the website cricbuzz.com the extension gets auto disabled and auto remove please do something or otherwise i will not use this addon

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
cricbuzz.com

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: windows 10
- Browser/version: firefox
- uBlock Origin version: 
uBlock Origin/webext-hybrid 1.13.10
##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
That makes no sense, web sites cannot remove extensions. Investigate your computer for malwares, sites cannot remove uBO, and even uBO cannot remove itself. There is an issue on your side, and it's not uBO.
