### ISSUE TITLE
Placeholder in logger "Network error" message is not replaced for some locales

### ISSUE THREAD

**Issue by xofe** [gorhill/uBlock#2921]
### Describe the issue

The current English translation uses placeholder `{{msg}}` in the message `errorCantConnectTo`, and the code handling this in `src/js/assets.js` replaces only the string `{{msg}}`. However, some locales seem to be using an outdated message for `errorCantConnectTo` that instead uses `{{url}}` as placeholder, resulting in a broken-looking message appearing in the logger on network error for these locales. 

Affected locales: bn, ca, da, el, eo, fa, fi, fil, lv, ml, mr, sl, ta, uk, zh_TW

Note this also affects uMatrix, except there *all* locales use `{{url}}`.

### Steps for anyone to reproduce the issue

1. Use (for example) Danish locale version of Firefox.
1. Open logger with tab selector set to "All".
1. Open dashboard, block network connections in some way (e.g. firewall), and try to update filters.
1. See message "Kan ikke forbinde til {{url}}" in logger, with visible placeholder.

### Your settings

- Browser/version: Firefox 56b6, Chromium 62.0.3200
- uBlock Origin version: 1.13.11rc0

**Comment by gorhill** [comment]
Just report to Crowdin please, this is where translations are handled, all on a voluntary basis. Since it's all on a voluntary basis, I do not badger anyone to contribute more than they wish to.

**Comment by xofe** [comment]
I don't have a Crowdin account, sorry. I'd say this is also a code issue (especially for uMatrix, where even English is affected), since the code could replace both `{{msg}}` and `{{url}}` until translations are updated to prevent breakage.
