### ISSUE TITLE
local file:/// filter lists url support dropped in FF 55.0.3

### ISSUE THREAD

**Issue by gomoku** [gorhill/uBlock#2922]
Just like there: https://github.com/gorhill/uBlock/issues/1971. `file:///E:/filterlist.txt` not working anymore, uncle Google shows:
https://www.reddit.com/r/firefox/comments/6wcp0m/is_there_any_way_to_make_firefox_extensions/
https://support.mozilla.org/questions/1172041
The question is, will it be "fixed" ( workarounded / hacked ) on uBlock's side (like in New Tab Override), or we say bye to local filter lists? TY.

**Comment by gorhill** [comment]
> will it be "fixed" on uBlock's side (like in New Tab Override)

If you want a New Tab Override kind of fix, then it is already fixed, it's the "My filters" pane in the dashboard.

Otherwise, it's a browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1266960>.

**Comment by gomoku** [comment]
Copy-pasting & combining several local filter lists into "My filters" tab and then managing / scrolling so huge single combined list, is not so handy, rather, each list should be handled individually, like in "3rd party filters" tab. 

For example in "3rd party filters" tab, in the text-pasting field, to add an ability to read & fetch the pasted content not only as a list of urls of filter lists, but also directly as a whole single filter list text content, just like in "My filters" tab. And then after clicking "accept changes" button, the content would appear on the main list, as a single filter list, as it has been entered as an url. To let uBlock distinguish, how to parse the pasted content (as an url/urls or as the whole  content of a single filter list), there can be a checkbox added above the paste-field, named like "parse as a single filter list content", or some special characters would be required in a first row of the pasted content, like "####".

But I also understand that You also wanted to say, that it's rather Mozilla problem, and they should fix their own problems themselves, I see, I didn't want to bother You, just asked. Thx.
