### ISSUE TITLE
uBlock Origin UI is clipped when placed under the ≡ Menu of Firefox

### ISSUE THREAD

**Issue by S-ed** [gorhill/uBlock#2926]
uBlock Origin UI is clipped when placed under the ≡ Menu of Firefox.

![screenshot 1504052537](https://user-images.githubusercontent.com/3008353/29849885-720c5236-8d32-11e7-9b38-c69656baf4ed.png)

1. Place uBlock Origin icon under Firefox menu
2. Press the button

I've tried to restore the setting to default ones, not sure if it did the work (nothing changed visually).

Not sure if it's related to https://github.com/gorhill/uBlock/issues/2809

- OS/version: 
Windows 10
- Browser/version: 
Firefox 55.0.3
- uBlock Origin version: 
1.13.10

**Comment by gorhill** [comment]
Duplicate of #2809.

**Comment by S-ed** [comment]
Ok. At first, I wanted to comment there, but it is locked for comments.

**Comment by lewisje** [comment]
That means the obvious answer is to open a new issue.

**Comment by S-ed** [comment]
@lewisje well, Yes. Since it's not clear if it's the same issue. https://github.com/gorhill/uBlock/issues/2809 was about overflow menu.
It takes more time to report an issue than to read it and close. I didn't blindly make it, I've searched for the similar issues before that. I don't actually see any reasons to lock the topic. That only leads to such duplicates to appear. Hope You follow the logic.
