### ISSUE TITLE
3rd-party filters shows 89,346 filters in fanboy-ultimate while it's only 75,521 lines in the file

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#293]
Do you split complex filters or is your calculation wrong?

**Comment by gorhill** [comment]
[Launch and filter lists load performance](https://github.com/gorhill/uBlock/wiki/Launch-and-filter-lists-load-performance):

> In 0.8.9.0, since all filters are normalized into atomic filter representation, µBlock is now able to detect 100% of filters which are functional duplicates.
> 
> And since µBlock's now report the number of atomic filters, expect the count to go up somewhat compared to previous versions. For instance, currently using default filter lists, 0.8.9.0 reports over 58,000 network filters, while previous versions reported around 55,000 network filters.

**Comment by mikhaelkh** [comment]
OK, but there are 89,346 filters in uBlock0 and 89,186 in uBlock, so one of you may count filters wrong, or uBlock skips more filters that uBlock0 do?

**Comment by gorhill** [comment]
I had to dig, and the explanation is because uBlock Origin supports the `font` object type in static filter. This boost the count of filter on uBlock Origin's side when there is a filter with a "negative" type option:

    example.com$~script
