### ISSUE TITLE
uBlock blocks direct image URLs (page won't load)

### ISSUE THREAD

**Issue by rhazor** [gorhill/uBlock#2930]
### Describe the issue
Cant load image URLs (imgur, etc)

### One or more specific URLs where the issue occurs
http://i.imgur.com/LLfAiSh.png
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![asd](https://user-images.githubusercontent.com/22996586/29866972-cad896ae-8d82-11e7-9090-e2f880ed4a48.gif)
as you can see nothing is happening on pasting photo url and pressing enter on current page or new tab. Works fine with uBlock disabled. No other ad blocker/privacy addons used.

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Install uBlock Origin on Firefox 55.0.3 x64
2. Try to open any imgur photo URL (direct path to photo)
3. Browser doesn't react at all on going to page/pressing Enter.
4. Works fine if uBlock disabled.

### Your settings
Default settings
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 x64
- Browser/version:  55.0.3 x64
- uBlock Origin version: 1.13.10

##### Your filter lists
Default, fresh install of addon.

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Hrxn** [comment]
And if you do the same steps but use the dev version from the AMO page instead?

**Comment by rhazor** [comment]
Same. Version 1.13.11rc0

**Comment by shellye5** [comment]
No problem here, just waited 10 seconds before pasting.
Version 1.13.11rc1

BTW How did you create the animated screen shot?

**Comment by rhazor** [comment]
ScreenToGif, but this is offtopic.

![asdv2](https://user-images.githubusercontent.com/22996586/29869645-7fa01e1e-8d8c-11e7-984f-de2df8b6c76e.gif)

**Comment by gorhill** [comment]
Anything at the browser console (ctrl-shift-j)?

Is your Firefox 64- or 32-bit?

Any other extensions installed?

**Comment by rhazor** [comment]
55.0.3 (64-bit)

[Pastebin of CTRL+SHIFT+J](https://pastebin.com/HTHnDKqF)

**Comment by gorhill** [comment]
Any other extensions installed?

**Comment by rhazor** [comment]
I tracked it down. It's Greasemonkey script Anti-Adblock Killer | Reek from https://greasyfork.org/en/scripts/735-anti-adblock-killer-reek and https://reek.github.io/anti-adblock-killer/

Disabling it solves the issue.

**Comment by Hrxn** [comment]
Uh, I guess gorhill will be slightly mad now ;-)

**Comment by gorhill** [comment]
I just mark as _invalid_ and move on.

**Comment by DeadNumbers** [comment]
Second way, add to greasemonkey exceptions this `/\.(jpe?g|png|gif|ico)(\?|$)/`

**Comment by allanf181** [comment]
third way: use tampermonkey
