### ISSUE TITLE
uBlock Origin for Thunderbird gone?

### ISSUE THREAD

**Issue by CryptOwl** [gorhill/uBlock#2932]
So, I was just trying to find uBlock Origin for Mozilla Thunderbird but apparently the whole addon page is gone now. uBlock Origin can now be found on the TB addon page.

https://addons.mozilla.org/en-US/thunderbird/addon/ublock-origin/
redirects to
https://addons.mozilla.org/en-US/android/addon/ublock-origin/

What are Thunderbird users supposed to do now? Is there any version that can be manually downloaded and installed? Will the TB addon page return?

**Comment by lewisje** [comment]
I know you can often download the extension from the Firefox (for desktop) page, and then it just has to be compatible with the version of Firefox that Thunderbird is based on (usually the ESR).

**Comment by CryptOwl** [comment]
Version 1.13.8 is compatible with Thunderbird 52.3.0 but listed as compatible with Thunderbird 31.0 - 45.* only:
https://addons.mozilla.org/de/firefox/addon/ublock-origin/versions/1.13.8

If I remember correctly this was also the case on the Thunderbird addon page when it was still available. Therefore you were unable to install uBlock via the addon page; manual installation is still possible.

**Comment by Atavic** [comment]
Version 1.13.10 doesn't work, while 1.13.8 installs on TB 52.3.0
Last version lacks thunderbird entries in the install.rdf file. 

Evetnually, you can add a TB entry with its GUID `<em:id>{3550f703-e582-4d05-9a08-453d09bdfdc6}</em:id>` in the install.rdf file.

**Comment by Atavic** [comment]
Last uBo version lacks thunderbird entries in the install.rdf file.

Eventually, you can add a TB entry with its GUID `<em:id>{3550f703-e582-4d05-9a08-453d09bdfdc6}</em:id>` and compatible versions entries in the install.rdf file.

**Comment by gorhill** [comment]
> redirects to

I don't have anything to do with AMO's behavior.

People who wants to use uBO with Thunderbird will have to contribute back by actually spelling out in details what needs to be done to keep uBO compatible with Thunderbird.

**Comment by gorhill** [comment]
I could install 1.13.8 successfully, direct link: https://addons.mozilla.org/android/downloads/file/685614/ublock_origin-1.13.8-an+fx+sm+tb.xpi

Just remember to turn off auto-update for uBO in its add-on preferences.

Using 1.13.8 is just fine, it's not so far behind compared to current 1.14.0. Maybe eventually Thunderbird will be webext-compatible.
