### ISSUE TITLE
Ublock 1.13.10 does not show up in Firefox Developer Edition 56.0b6 (64-bit)

### ISSUE THREAD

**Issue by gitowiec** [gorhill/uBlock#2933]
### Describe the issue
Ublock 1.13.10 does not show up in Firefox Developer Edition 56.0b6 (64-bit), the icon with ublock stuff and information what was blocked never shows up.

### One or more specific URLs where the issue occurs
https://soundcloud.com/alexadair
For sure any page (URL).

### Your settings
- Debian 9 with KDE Plasma
- Firefox Developer Edition 56.0b6 (64-bit)
- uBlock 1.13.10

##### Your filter lists

"Default filter lists"

**Comment by kasperkarlsson** [comment]
I have the same problem - the uBlock button is gone and the blocking seems to be completely disabled. Deactivating and reactivating uBlock did not solve the issue.

### Your settings
* Microsoft Windows 10
* Mozilla Firefox 55.0.3 (32-bit)
* uBlock 1.13.10

##### Your filter lists
"Default filter lists"

**Comment by hagen3000** [comment]
Same issue here.

Windows 10 1703
Firefox 56.0b6 (64-bit)
uBlock 1.13.10

![grafik](https://user-images.githubusercontent.com/7038961/29886077-264eae34-8db9-11e7-901b-923f172a4a36.png)

**Comment by gorhill** [comment]
Did you try the workaround described in the release notes of 1.13.10.

**Comment by gorhill** [comment]
Ok, anyways, from now on any issue of uBO 1.13.10 not showing or similar are going to be closed as a Firefox isse, I've spent way enough time on this. 1.13.10 is an embedded extensions as per documentation on MDN, any issue with it, go to bugzilla.mozilla.org.
