### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by crssi** [gorhill/uBlock#2936]
@gorhill 
That was rude, I was trying to help.
Sorry for "speculations" using "guess" word, but I was giving you working reproduceable example.

Delete this post when read.

**Comment by gorhill** [comment]
Please stop abusing this repo. You were told to profiling data + anaysis of it to make the case. You keep posting comments without what is asked from you. Now I will have to block you if you can't contribute anything more than noise in this repo, including the invalid issue here.
