### ISSUE TITLE
Ublock on a desktop ff is referencing to android

### ISSUE THREAD

**Issue by timse201** [gorhill/uBlock#2939]
### Describe the issue
if you open the addon-page of Ublock 1.13.11rc0 while using a desktop firefox the homepage links to https://addons.mozilla.org/de/android/addon/ublock-origin/?src=api which is for ff android.
Users will get a warning that their firefox version is incompatible.

### One or more specific URLs where the issue occurs

about:addons

### Screenshot in which the issue can be seen

https://www.pc-tweak.de/entwicklung/ublock.png

### Steps for anyone to reproduce the issue

1. open about:addons
2. open settings
3. scroll to the footer and see the url

### Your settings

- OS/version: win 10 17.03
- Browser/version: Firefox 55.0.3
- uBlock Origin version: 1.13.11rc0 webext

**Comment by gorhill** [comment]
I can't reproduce this, the link on my side is `https://github.com/gorhill/uBlock#ublock-origin`.

Please rule out that your user agent string is tampered with. In any case, that URL is presented by Firefox, I have no say in this. Report to https://bugzilla.mozilla.org if upon further investigation on your side you still can't pinpoint the cause.

**Comment by timse201** [comment]
i can reproduce it on 2 different clients but it canges form startup to startup i think
sometimes it links to android and sometimes it links to the desktop page
