### ISSUE TITLE
Video not playing on Chive

### ISSUE THREAD

**Issue by dhprototype** [gorhill/uBlock#294]
Video on Chive site is not playing when uBlock is active. Here is a sample link.
(Chrome/uBlock Origin v0.9.8.3/all default options and filters)

http://thechive.com/2015/06/04/cardinals-pitcher-lance-lynn-throws-epic-game-has-no-idea-what-happened-video/?utm_source=Sailthru&utm_medium=email&utm_term=daily&utm_campaign=theChive%20Daily%202015-06-04#.9usacp:LX3N

**Comment by gorhill** [comment]
There should be an update available for the filter list "uBlock - Unbreak". If not, you will see the update if you restart uBlock.

You can also just use the following custom filter:

    @@||vox-static.liverail.com/swf/$object-subrequest,domain=cdnapi.kaltura.com

And remove it once you get the latest "uBlock - Unbreak".

**Comment by dhprototype** [comment]
Okay. The "uBlock - Unbreak" filter is working now.
