### ISSUE TITLE
uBlock with Ghostery

### ISSUE THREAD

**Issue by peterbandi** [gorhill/uBlock#2941]
### Describe the issue
The same issue as #2897 but I could not get the profiler results in time. At some point the discussion was restricted and I couldn't make any comments to request some time for the test.

The problem is the same: Firefox slows down if both uBlock and Ghostery is enabled. Since the first report Firefox updated itself from 54 to 55.0.3 and the problem is now far less prevalent but I think it is still there.

### One or more specific URLs where the issue occurs
https://www.google.com/gmail/

### Steps for anyone to reproduce the issue

0. Install Ghostery and uBlock together to Firefox.
1. Open a bunch of pages, including:
  https://www.google.com/gmail/
2. Interact with the pages, e.g. GMail. Open emails, browse inbox.
3. See at the processor usage builds up to 100% (on a single core) and Firefox gets unresponsive.

### Your settings

- OS/version: Windows 10 Pro version 1703 build 15063.540
- Browser/version: Firefox 55.0.3 (64-bit)
- uBlock Origin version: 1.13.10
- Ghostery version: 7.3.2.5

##### Your filter lists

uBlock filters​​​​​
uBlock filters – Badware risks​​​
uBlock filters – Privacy
​​uBlock filters – Unbreak​​​​​
EasyList
EasyPrivacy
Malware Domain List
​​Malware domains
Peter Lowe’s Ad and tracking server list

### Profiler output
[profile.zip](https://github.com/gorhill/uBlock/files/1267113/profile.zip)

**Comment by gorhill** [comment]
Your profiling is of no use, use the Gecko profiler.

Anyways, report any performance issue to Firefox devs. I've spent enough time this week with all sort of Firefox issues to no avail.

**Comment by gorhill** [comment]
From now on any issue with Firefox, performance or storage, or any other extension such as Ghostery will have to be reported on their repor, they have people paid to look into their stuff. See <https://bugzilla.mozilla.org/show_bug.cgi?id=1395213>. I've done beyond my share to bring uBO to webext level, now any issue with it is in Firefox's hands.
