### ISSUE TITLE
The pushed out 1.14.0 on Firefox ESR isn't webext compatible

### ISSUE THREAD

**Issue by terr72** [gorhill/uBlock#2944]
### Describe the issue

You managed to push out 1.14.0 for Firefox ESR (52.x), which doesn't work with webext-only addons.
When accepting the update, users are being prompted that the addon doesn't work on FF 52.x

Please fix that.
Users with a bit of knowledge are easily able to roll-back by installing 1.13.8, but an average user will get totally confused.

**Comment by Mikotochan** [comment]
It seems that the version 1.14.0 claims to be compatible on Firefox 52+ while its beta versions claimed to be compatible on Firefox 54.0+. I guess that this was a mistake and also what caused the upgrade?

**Comment by gorhill** [comment]
Ok I fixed this in #2945, I did not realized there was an issue opened about this earlier.

I pushed 1.14.4 to AMO, it's pending review.

**Comment by stanlane** [comment]
1.14.4 is on AMO now.

**Comment by gorhill** [comment]
I was told webext extensions have shorter review time than legacy ones, so it seems this is it.

**Comment by stanlane** [comment]
@gorhill Thank you for sharing this.

**Comment by gomoku** [comment]
Some typos in the description?: https://github.com/gorhill/uBlock/releases/tag/1.14.4

> Firefox for Android 54
> Firefox for Android 55
