### ISSUE TITLE
Firefox 52.2.1: uBlock suddenly disabled due to incompatibility

### ISSUE THREAD

**Issue by Zack-od-Bins** [gorhill/uBlock#2945]
In Firefox 52.2.1 uBlock has been completely disabled. In the addons tab it says that uBlock Origin is not compatible. Strange, since only yesterday it was working 100%, and I didn't update anything. On the addons website page of uBlock I read an other user has the same issue in FF 52.3.0. 

I am assuming it has something to do with the uBlock addon update to version 1.14.0

My PC is running on Windows 7 x64.

As to my personal settings in uBlock; I can't tell, since it is disabled and I can not enter the uBlock user interface. 

[EDIT] I managed to install Version 1.13.9b0 from https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta

**Comment by stanlane** [comment]
"strict min version" must be changed from "54" to "52" in manifest.json as suggested in this [review](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/914147/).

**Comment by stanlane** [comment]
@gorhill "strict min version" must be changed from "54" to "52" in manifest.json as suggested in [this review](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/914147/).

**Comment by stanlane** [comment]
@gorhill Please change 

>  Works with Firefox for Android 54.0 - *, Firefox 52.0 and later 

to

>  Works with Firefox for Android 54.0 - *, Firefox 54.0 and later

in https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/ for version 1.14.0.

**Comment by Quix0r** [comment]
Same issue here with Firefox ESR 52.3.0 under Debian (no higher version available). I now wait with a lower version of ublock.

**Comment by gorhill** [comment]
I can't change `strict min version` to 52, uBO/webext is compatible only with Firefox for Android 55. I actually made a mistake by leaving the min version to 54.

If someone know if I can set a different min version for Firefox for Android, let me know.

**Comment by gorhill** [comment]
Ok AMO allows to override the min/max version in the AMO dashboard for the extension. Maybe I can set min version to 52, than once uploaded I could use that feature to override the min version in the manifest to put back 55 for the Android version.

**Comment by stanlane** [comment]
@gorhill Thank you.

**Comment by gorhill** [comment]
Duplicate of #2944.

**Comment by stanlane** [comment]
@Quix0r Try updating now, 1.14.4 is on AMO.

**Comment by roger21** [comment]
it's not working on firefox 52.3 esr

**Comment by terr72** [comment]
Wasn't the original plan to maintain a separate legacy-only version for the ESR users and a webext-only version for FF55+ users?

**Comment by gorhill** [comment]
It's all in the Release notes. Why not just read them?

**Comment by roger21** [comment]
> It's all in the Release notes

no it is not

the release note says 

> As per popular demand, I set the minimum version to 52.0. However be warned that some features are not available

it's not the case, the 1.14.4 does not work AT ALL with firefox esr, firefox esr just does not let it run.

**Comment by stanlane** [comment]
@roger21 uBO 1.14.4 working for me in Firefox ESR 52.3.0 (64-bit) binary download for GNU/Linux.

**Comment by stanlane** [comment]
@roger21 Can you please try to install uBO 1.14.4 in a fresh profile and reevaluate?

**Comment by gorhill** [comment]
Read all the release notes please, there is no point to keep repeating in latest release notes what has been said in previous release notes -- the whole webext transition has been undergoing for months now, all documented in release notes.

> See [Firefox WebExtensions documentation](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions) for **up to date** information regarding the uBO/webext[-hybrid].

**Comment by roger21** [comment]
> @roger21 uBO 1.14.4 working for me in Firefox ESR 52.3.0 (64-bit) binary download for GNU/Linux.
> @roger21 Can you please try to install uBO 1.14.4 in a fresh profile and re-evaluate?

so i actually switched to 1.13.8 earlier and tried to re-install 1.14.4 after your first answer and it seems to work (with loosing all my settings /o\)

> Read ...

well, there is nothing clear in the doc or the release note and apparently if you let firefox do it just disables the addon and don't enable it again with the 1.14.4 ... so meh
but ok having read the doc and all the past release notes and that thread make it a bit clearer ... "sarcastic big woop"

**Comment by stanlane** [comment]
@roger21 Great.

**Comment by gorhill** [comment]
> "sarcastic big woop"

Feel free to contribute better release notes (I will happily cut & paste any improved doc/notes), I do spend a fair amount of free time on this project, and I did spend a fair amount of free time specifically trying to be as informative as can be from my limited literary skills in the doc/notes, but yes, that won't ever be perfect, unless people start to contribute to address what they see as in need of work. On the other hand, sarcasms are easy so spout, but contributes exactly nothing, so with regards with contributed efforts to a foss project, I think I am ahead of you.

**Comment by roger21** [comment]
and for those who are concerned, the icon position is reset (with the webext), so if you have a customized ui (as i do) it may just disappear (as for me), making it even more unclear: firefox finally not saying it's disabled but no icon though ... adding to that the release note talking about not working UI but for android ... did i switch to android ... not clear

**Comment by gorhill** [comment]
"customized ui" using what?

uBO/webext's toolbar icon placement is controlled by the browser, uBO has no say in it.

**Comment by roger21** [comment]
i use status-4-evar and classic theme restorer and i don't use the address bar

and when you switch to the webext version, the icon disappears from status-4-evar and put back to the address bar (then you can put it wherever you want)

the icon from the old version and the icon from the webext version seem to be 2 different entities for firefox

**Comment by gorhill** [comment]
status-4-evar is a legacy extension. Any issue arising as the result of mixing uBO with a legacy extension will have to be dealt elsewhere, and given legacy extensions are phased out, I seriously doubt Firefox is going to waste time on addressing such issues. Your only resort is to install uBO/legacy (it still is build for every release as `uBlock0.firefox.xpi`), or ask the legacy extension author to do something about the incompatibility.

**Comment by roger21** [comment]
> then you can put it wherever you want

i was really just answering your question i was not implying it has to be addressed whatsoever

**Comment by Zack-od-Bins** [comment]
Like many others who have reasons to stick with Firefox ESR, I am hoping the developer(s) will (continue to) maintain a legacy version of uBO. Not everyone is aware of a legacy version though, or how to install it. Perhaps it is possible to add a link on the addons pages and at the uBO frontpage at github ?
