### ISSUE TITLE
Debian/Ubuntu: Please provide a script to migrate settings from the legacy addon, or tell us how to write one

### ISSUE THREAD

**Issue by spwhitton** [gorhill/uBlock#2948]
Hello!

Debian releases every two years, so we can't ensure that our users will run a version of uBlock Origin that will migrate their data/settings.  They will probably skip from 1.10.4, which is the version in our latest stable release, to a pure WebExtension version of uBlock Origin, without the migration code.

I want to provide a shell/python/whatever script that will migrate their settings.  Could you provide guidance for that, please?  Also, we currently provide packages for both Firefox and Chrome.  Will we need different scripts to migrate the settings of each of those?

Thank you for all your hard work.

**Comment by gorhill** [comment]
There is no change for Chrome, it's only a Firefox issue, which is deprecating the old extension API in favor of the new [WebExtensions one](https://developer.mozilla.org/en-US/Add-ons/WebExtensions).

My knowledge of scripts is minimal, I just learn what I need when I need it. So anyways, basically this is how it things are:

- With uBO/legacy, the settings are located in `~/.config/firefox/[profile]/extension-data/ublock0.sqlite`
    - The content of the `ublock0.sqlite` db is one table, named `settings`, with two columns, named `name` and `value`.
    - Each `name` is unique, and is the name of a setting.
    - Each value is a string, and is `JSON.parse`'d after being read, and before being sent to the caller.
- With uBO/webext, the settings are located in `~/.config/firefox/[profile]/browser-extension-data/uBlock0@raymondhill.net/storage.js`.
    - The content of `storage.js` is simple JSON data, in which each setting is an `[setting name]: [setting value]` entry.

Now given all this, it's a matter of fetching all entries in the sqlite table, and converting them into an object property in the same JSON structure.

Now not all entries in the table are to be transferred to the JSON structure, many entries are strictly for internal use by uBO. Any entry which name starts with `cache/` must be ignored. Additionally, the following entries must also be ignored: `assetCacheRegistry`, `assetSourceRegistry`, `selfie`.

The code to migrate is located in [this `bootstrap.js` file](https://github.com/gorhill/uBlock/blob/1.13.10/platform/webext/bootstrap.js#L39). The function named `getStorageMigrator` contains all the code to deal with reading all entries one by one from the `settings` table.

**Comment by gorhill** [comment]
So far I got _something_ with this command -- needs more work though to get a valid JSON file -- so before I lose that command:

    sqlite3 ublock0.sqlite ".separator ": " SELECT * FROM settings;" | awk '!/^(?:assetCacheRegistry|assetSourceRegistry|cache\/.+|selfie)$/' > output.txt

**Comment by spwhitton** [comment]
Thanks for all the info!

Is it correct that only a legacy addon could run that code?  I.e. it's
impossible for a pure web extension to perform the migration?

If so, preparing a script is my only option, but it looks doable.

-- 
Sean Whitton

**Comment by gorhill** [comment]
Yes, only legacy, webext can't access the underlying file system and no API to deal with sqlite file.

**Comment by Tallefer** [comment]
> There is no change for Chrome, it's only a Firefox issue, which is deprecating the old extension API in favor of the new WebExtensions one.
@gorhill Are you 100% sure about Chrome? I am asking, because today I was messing with some random site and went to check my settings, but there were no filters or rules there (just like with newer version on Firefox after upgrading from 1.13.8). This is... strange, because I am using Chrome with uBlock for quite some time now.
Is there a old version anywhere that can be installed in place of newer one (to check the "old" settings), or the settings file/format is the same on all Chrome versions?

**Comment by gorhill** [comment]
Closing: assuming the issue here is now obsolete.

**Comment by spwhitton** [comment]
Hello,

On Sun 19 May 2019 at 12:46PM -07, Raymond Hill wrote:

> Closing: assuming the issue here is now obsolete.

Someone wrote one and it got uploaded to Debian :)

-- 
Sean Whitton
