### ISSUE TITLE
BPost Belgium

### ISSUE THREAD

**Issue by EkalbM** [gorhill/uBlock#2949]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
The site https://www.bpostbanque.be/portal/start.asp opens on a blank page. 
To access, I must disable ublock completely.

### One or more specific URLs where the issue occurs
https://www.bpostbanque.be/portal/start.asp

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windws 10 1703
- Browser/version: Firefox 55.0.3 (64 bits)
- uBlock Origin version: 1.14.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Reports from other users with similar issues show that the problem is caused by other legacy addons. Disable all your legacy extensions, restart, and see if this fixes your issue. If yes, then enable them one by one to find out the culprit.

**Comment by Betsy25** [comment]
Was able to reproduce the issue from a blank profile.
Complete blank profile : Site loads up fine.
Installing the latest uBO v1.14.3b1, and putting the site in Whitelist, results in a blank site.

OS : Win7 x64
Browser ; Firefox 57.0a1 (2017-09-01) (32-bit)
uBlock Origin : 1.14.3b1

**Comment by mapx-** [comment]
I can reproduce the issue (even whitelisting uBo) in FF 56.0b8 but also using FF dev edition

in the browser console:
![ff2](https://user-images.githubusercontent.com/10303732/29994939-874842f2-8fdc-11e7-9d6c-19c14e67f10a.PNG)

**Comment by gorhill** [comment]
Works with Chromium and same configuration.

Disabling all filter lists did nothing. At this point I suspect something wrong somewhere with webext framework, but I need to investigate more. The console provides no clue as to where the issue lies.

**Comment by gorhill** [comment]
This will have to be reported to Firefox devs (can somebody please do it?):

- I can reproduce the issue with [AdBlock](https://addons.mozilla.org/en-US/firefox/addon/adblock-for-firefox/) alone.
- I can reproduce the issue with [AdBlocker Ultimate](https://addons.mozilla.org/en-US/firefox/addon/adblocker-ultimate/) alone
- I cannot reproduce the issue with uBO/legacy.
- The issue also affects Nightly.

**Comment by gorhill** [comment]
This is this bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1379148>.

Please add to that bugzilla issue, as they are still trying to assess how severe is the issue, i.e. how many web sites are affected by it.
