### ISSUE TITLE
 'blockedRequestCount' did not continue to update, after updating  addon . Started from 0 in UI.  Linux Mint 17.2, Firefox 55

### ISSUE THREAD

**Issue by gkrishnaks** [gorhill/uBlock#2953]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Linux Mint 17.2 - 'blockedRequestCount' did not continue to update addon after updating . Started from 0. 

### Screenshot in which the issue can be seen

First pic : https://imgur.com/a/odLb5

### Steps for anyone to reproduce the issue
I updated to latest version, lost settings. As mentioned in firefox addons page, reverted to old version, exported settings, imported to new version. 
Got back the settings, yes, but blocked request count started from 0, not from ~700k where it was. 
Able to see oldvalue of ~700k in ublock0.sqlite file. 

I read up about 'webext' implementation.. not sure if that has caused this. I can edit a file to put it back to the old values for blockedRequestCount and allowedRequestCount (so that it can calculate percentage?)  ... so it continues to count from the old value if you guide me to the file.

### Your settings

- OS/version: Linux mint 17.2 
- Browser/version:  firefox 55.0.2
- uBlock Origin version: 1.14.0
advanced user enabled 

##### Your filter lists
ublock filters minus experimental. 
plus 2nd pic here : https://imgur.com/a/odLb5

**Comment by gorhill** [comment]
the blocked/allowed counts are not part of a backup, these a per-computer, local settings, and thus they are not imported. If you want to recover your counts, use the uBO/webext-hybrid solution detailed in the [release notes of 1.13.10](https://github.com/gorhill/uBlock/releases/tag/1.13.10).

**Comment by gkrishnaks** [comment]
Hi. Thank you. 
I read your response on https://github.com/gorhill/uBlock/issues/2948 and opened the storage.js file to put the old counts from old .sqlite file.
