### ISSUE TITLE
Wrong compatibility info

### ISSUE THREAD

**Issue by ale5000-git** [gorhill/uBlock#2954]
### Describe the issue
I have installed uBlock Origin on Firefox 53.0.3 (64-bit) and it now work (yesterday it wasn't working).
After I have installed the add-on I have clicked on "Web Site", it go on 
https://addons.mozilla.org/it/firefox/addon/ublock-origin/?src=api and on the site you can see the wrong compatibility info: Firefox 57+.

Can it be fixed please?

### One or more specific URLs where the issue occurs

https://addons.mozilla.org/it/firefox/addon/ublock-origin/?src=api

### Steps for anyone to reproduce the issue

1. Installe uBlock Origin on Firefox 53.0.3 (64-bit)
1. Open the add-on page and find uBlock Origin
1. Click on "Web Site" and see the wrong compatibility info

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 (64-bit)
- Browser/version: Firefox 53.0.3 (64-bit)
- uBlock Origin version: 1.14.4

##### Your filter lists

Default filter lists + ITA

**Comment by gorhill** [comment]
I am not responsible for maintaining the AMO site.

Please refrain from opening such trivial (non-)issue (your uBO is working -- why do you mind what AMO says?), I am currently burdened enough with the webext migration that I rather deal with actual real important issues.

**Comment by ale5000-git** [comment]
Sorry, I thought that the info was provided by extension author.

**Comment by gorhill** [comment]
The label does not say "Firefox 57+ **only**", it's just there to inform people the extension will work fine with FF57, as opposed to a legacy extension.
