### ISSUE TITLE
Cosmetic image not not being blocked

### ISSUE THREAD

**Issue by tsunami2311** [gorhill/uBlock#2957]
![gfbfamt](https://user-images.githubusercontent.com/12301593/29997384-9659c9b6-8fdf-11e7-9abe-764b46dbca0f.jpg)

![d9ftpua](https://user-images.githubusercontent.com/12301593/29997385-9b1ea354-8fdf-11e7-8dd5-29701bd3d4fc.jpg)

I use the following code sites that use similar forums
`forums.guru3d.com##.posterAvatar.listBlock`
`www.snbforums.com##.posterAvatar.listBlock`

which also made me thing the other sites i have listed there to be block are actual being blocked? and no those site i not will to test if they are indeed being block on 1.14.4 bad sites that might inject malware and other stuff upon loading

`||networkframefailure.in^`
`||winsmartscreenfilter.in^`

Again  dont recommend going here i just wondering  "my filters"  are actual work in 1.14.4 cause comestic ones  were not being blocked I did test in 1.14.4 with `||forums.guru3d.com^` and it did block the site so site block does seem to be working it still makes me wonder

 those avatars in 1.13.8  get block, in 1.14.4 those image dont get blocked, I am using Cyberfox 52.3.0 which is on ESR for another 6 months or so. and if i try recreate block in with  element picker preview will show image blocked and when created but when reload page the fillter is ignored 

in Officall 55.0.3 64bit the cosmetic filters do work

**Comment by gorhill** [comment]
> in 1.14.4 those image dont get blocked, I am using Cyberfox 52.3.0
> in Officall 55.0.3 64bit the cosmetic filters do work

I can't provide support for 3rd-party browsers if they fail where the official Firefox works fine, and I can't answer for things I can't investigate -- so really such issues should not be opened.

If you provided repro steps, I would try with Tor browser, which is on 52 ESR, but I have no idea exactly what I need to do. Repro steps must be to the point, and simple to follow (no guessing required by whoever is trying to repro).

All I can say is look at browser console.

**Comment by Betsy25** [comment]
Was able to reproduce the issue, screenshot with browser console content.
Cyberfox : 52.3.0
uBO : 1.14.4

Screenshot:
![2017-09-02_232658](https://user-images.githubusercontent.com/6320902/29998918-22733804-9037-11e7-89ec-cbdd0101f217.jpg)

**Comment by gorhill** [comment]
Ok, so the [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS) says that `cssOrigin` is not available on 52. Ugh. I set the min version because many people were asking it.

**Comment by Betsy25** [comment]
Sorry @gorhill , I relady removed the reply because on repeated tests, there are no longer error messages in the console. but the problem with items not being filtered with rule below though still happens though.
`forums.guru3d.com##.posterAvatar.listBlock`

Cyberfox : 52.3.0
uBO : 1.14.4

**Comment by tsunami2311** [comment]
I provided what I can, I not programer so i not gona pretend to know "why" it hapens just know it works with 1.13.8 but not with 1.14.4 far as i can tell all the 3rd party 64bit FF build are on ESR for 53. I wont going off the assumption this all happen cause  they switching how extension and may other things work, in 57 of FF

**Comment by gorhill** [comment]
I just wanted _at least_ an exact link I can just click to open whatever page you have in your pic, there was no link hence I didn't try to investigate. Example of straight to the point with exact info:

- Add filter `forums.guru3d.com##.posterAvatar.listBlock`
- Go to `[whatever _exact_ URL] you see the issue`
- Result: filter not applied

That simple, and I just have to read bare minimum of info to reproduce. I quickly read your issue, noted your "dont recommend going here", then gave up trying to understand what you were saying.

But I am just really repeating what is in CONTRIBUTING.

**Comment by tsunami2311** [comment]
my bad I thought seeing image have link it  was good enough, I will use direct link to urls from now on, as for explanation of things i bad explain things, from now i will try to short and to the point,, think the more i try to explain things more it i just confuse me and my self

**Comment by gorhill** [comment]
Anyways, thanks for reporting, this was an _actual_ issue in uBO.
