### ISSUE TITLE
[Firefox] Cloud storage causes cosmetic filters to flicker

### ISSUE THREAD

**Issue by asdasdadas23232** [gorhill/uBlock#2959]
When Cloud storage is turned off, cosmetic filters work perfectly. The moment it is turned on, they now flicker, that is, still show up for a few milliseconds after the page is loaded.

I understand that Cloud storage is related to Firefox Sync. I do not have Firefox Sync turned on and have never used it. I noticed this after all of my settings randomly got deleted when uBlock got an update (might want to look into this) and I accidentally turned Cloud storage on.

- OS/version: Windows 10 64bit
- Browser/version: Firefox 52.3.0 esr
- uBlock Origin version: 1.14.4

**Comment by gwarser** [comment]
Probably not related to cloud storage: https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
