### ISSUE TITLE
Behind-the-scene request

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uBlock#296]
I am not able to reopen the issue at https://github.com/gorhill/uBlock/issues/291
I posted screenshots of the behind-the-scene request. Hoping to know more about it.

**Comment by gorhill** [comment]
> I am not able to reopen the issue at #291

You don't have to re-open it. You re-open it if you make the case that that hyperlink auditing requests are not blocked when they are supposed too. A lot of things can make behind-the-scene requests, behind the scene requests does not automatically mean "hyperlink auditing".
