### ISSUE TITLE
[Firefox] Settings Completely Wiped.

### ISSUE THREAD

**Issue by Rokeugon** [gorhill/uBlock#2960]
i was browsing on firefox when all of a sudden both my logger and filters window for UBO randomly closed. and my currently browsing tab was switched to the next tab along. when i re-opened the logger and filter list. straight away ive noticed that my filter list is gone and my settings and preferences for filters are gone. can someone tell me wth has just happened ??? im left in a mass state of confusion and a bit upset as ive lost about a year or two's worth of filtering that i had done.

i would like to link my settings and filters etc but they are all gone. so kinda in a predicament here atm. i dunno if the addon crashed or just simply stopped working or if it was updated. i honestly dont know.

if there are any logs that can be retried from this or further in depth detail as to what has happened id be wiling to help and provide such a thing. but for now im as confused as ever!

also after this strange event happened. when accessing UBO settings or logger or firefox's menus like addons etc a weird glitched screen appears like someone had poured a bunch of dead pixels down into the top of my monitor. this was only visible for a millisecond at best but very noticeable. i tried grabbing screenshots but after i had restarted firefox the issue was no longer present

OS: Windows 10 home 64bit
Browser: Firefox [v-55.0.3]
UBO: 1.14.4

Please delete this or close the issue as someone has messaged me relating to the updated description that was made on firefox's addon page. appoligies for the inconvenience.

**Comment by gomoku** [comment]
Btw in uBO in Settings tab, did you have backup done? Is the backup also gone?

**Comment by gorhill** [comment]
> Please delete this or close the issue as someone has messaged me relating to the updated description that was made on firefox's addon page. appoligies for the inconvenience.

Ok so for reference, the release notes is always the first place to go. The steps to recover settings are explained the [release notes of 1.14.0](https://github.com/gorhill/uBlock/releases/tag/1.14.0).
