### ISSUE TITLE
'Block element' from context menu not working in Firefox, when 0 active filters.

### ISSUE THREAD

**Issue by gomoku** [gorhill/uBlock#2963]
### **Describe the issue:**
Not sure whether this is an issue or feature of the non-legacy version of uBO, but when in uBO in "3rd party filters" tab, no filters are used (Static filters: 0 ÷ Cosmetic filters: 0 from:), when I right click on any element on any website and choose 'Block element' from context menu, nothing happens. Additional sub-issue: on uBO 1.13.10 there is also uBlock icon missing in front of "Block element" command.

### **One or more specific URLs where the issue occurs:**
Any website.

### **Your settings:**

- OS/version: Windows 7 SP1 64bit Ultimate PL
- Browser/version: Firefox 55.0.3 32bit (e10s enabled) / FF Nightly 56.0b8 64bit + uBO above v1.13.8

### **Settings on which the issue doesn't occur:**

- Browser/version: Opera 47.0.2631.71 64bit (PGO) + uBO any version.
- Browser/version: Firefox 55.0.3 32bit (e10s enabled) / FF Nightly 56.0b8 64bit + uBO v1.13.8 and below

### **Additional comments:**
Seems like not a critical bug, but rather cosmetic, since almost everyone have more than 0 filters active, thus that's why I've discovered the bug while in debug/testing mode (and this mean I've had all filters disabled). But whether the error is not more serious, the creator finds, because the bug may be related to other bugs and  break some other things.

**Comment by shevegen** [comment]
I think I may have had this every now and then too. I never thought much about it though and my work around is to simply use the "Pick" functionality instead, which seems to work more realiable. However had, it never seemed to happen on EVERY website, just on some (but I did not analyze this systematically; and of course I can not say whether this is different for others either, so I am just giving the use case from here, my position).

Does the "Pick" variant not for you either though? And can you show a website where both would not work, so it can be more easily reproduced? (It could by "any" indeed, but it could be specifically ONE at the least, with an URL :D )

**Comment by gomoku** [comment]
The "Pick" wariant still and always works, so there is no example urls where both wariants would not work, instead, I can give several example links, where the context menu wariant is broken:
https://www.google.pl/
https://addons.mozilla.org/pl/firefox/addon/ublock-origin/
http://www.darmoweogłoszenia.pl/

**Comment by gorhill** [comment]
Same issue can be reproduced by simply toggling off cosmetic filtering for the page.

Issue seems related to the fact that uBO discards from the content script the DOM filterer and DOM surveyor when no cosmetic filters have to be applied on a page

**Comment by shevegen** [comment]
I just (!) found a site that is not working, ironically for the pale moon browser:

http://linux.palemoon.org/

Here, when I click on "Block element", nothing happens - not even the normal widget that I'd normally get on the bottom right site, where I can then click on "create" or "pick" etc..

That is actually the first website where I do not see anything at all in regards to the "Block element" action. Quite strange.
