### ISSUE TITLE
Completely not working at all in tor 7.0.4/firefox 52.3.0 after 1 september update

### ISSUE THREAD

**Issue by theArhar** [gorhill/uBlock#2966]
### Describe the issue
The is no labels in widget and absolutely no settings

### One or more specific URLs where the issue occurs
All internet

### Screenshot in which the issue can be seen
http://uploads.im/e5OE2.png
http://uploads.im/5vS8d.png

### Steps for anyone to reproduce the issue
really?

### Your settings
see screenshot - its BLANK

- OS/version: Windows 10
- Browser/version: Tor 7.0.4/Firefox 52.3.0
- uBlock Origin version: 1 September 2017

**Comment by gorhill** [comment]
Can't reproduce here.

As a 1st step, see if disabling other extensions -- including NoScript -- fixes the issue.

**Comment by theArhar** [comment]
Yes, NoScript 5.0.9 breaks it

**Comment by gorhill** [comment]
See if this helps: <https://forums.informaction.com/viewtopic.php?f=7&t=21568>.

**Comment by gorhill** [comment]
https://trac.torproject.org/projects/tor/ticket/21270
