### ISSUE TITLE
Bug 1396486 - Bookmarked web page would not open in twitter.com tab if uBlock Origine is installed

### ISSUE THREAD

**Issue by alice0775** [gorhill/uBlock#2967]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Bug 1396486 - Bookmarked web page would not open in twitter.com tab if uBlock Origine is installed.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1396486

All filter is default.

**Comment by alice0775** [comment]
1.14.8 seems fix.

**Comment by alice0775** [comment]
It reproduced again with 1.14.9b0 on Firefox52.0.3esr, 55.0.3 and 56.0b9 but not on Nightly57.0a1.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1396486

**Comment by gorhill** [comment]
Please, go through steps in [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.4).

**Comment by gorhill** [comment]
never mind, I can reproduce, I had missed the "disable e10s" step.

**Comment by gorhill** [comment]
I could also reproduce with [AdBlocker Ultimate](https://addons.mozilla.org/en-US/firefox/addon/adblocker-ultimate/) and [Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/), both WebExtensions-based extensions.

I am unable to reproduce with the egacy version of uBO.

Given all this, I conclude there is an issue somewhere in the WebExtensions framework. There was nothing at the browser console, I have no clue what is going on internally to cause such error. Clicking again the site at step 7 causes the site to finally load.

**Comment by gorhill** [comment]
https://bugzil.la/1401516
