### ISSUE TITLE
Only block ads on specific list of websites

### ISSUE THREAD

**Issue by k-bx** [gorhill/uBlock#297]
Hi!

I don't mind ads in general, since they're a way for website owners to make money. But some websites put so much ads that it's corrupting my user-experience and consumes CPU "just too much". I would like to be able to use full power of uBlock, but only on these 2 or 3 websites which annoy me. How can this be done best?

Thanks!

**Comment by quilloss** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except
Do you mean this?

**Comment by k-bx** [comment]
@quilloss thanks! Sorry that I couldn't find it myself.
