### ISSUE TITLE
uBlock completely breaks the WordPress dashboard

### ISSUE THREAD

**Issue by ruda-almeida** [gorhill/uBlock#2971]
This is not a filter issue. The issue happens even if all filters are turned off.

### Describe the issue

After updating any existing content, uBlock completely breaks the WordPress dashboard

- The title bar shows the full URL instead of the title
- Clicking on links stop working on the content area
- The dev tools JS debugger states "this page has no sources"

### One or more specific URLs where the issue occurs

http://localhost/wp-admin
https://[redacted]/wp-admin

### Screenshot in which the issue can be seen

This is not a visual issue

### Steps for anyone to reproduce the issue

1. Pick a newly-created WordPress install with no plugins installed and the default theme active (Twenty Seventeen)
2. Edit the "Hello World" post and click "update"
3. Click any link on the dashboard menu on the left area

- Turning off uBlock for the current page / site has no effect.
- Whitelisting the entire domain has no effect.
- Clearing all third-party filters, my filters, and whitelist has no effect.
- Reverting to default configuration has no effect.

### Your settings

uBlock Origin 1.14.4
Firefox 55.0.1 (64-bit) -- with all extensions other than uBlock disabled
Fedora 25 (64-bit)
WordPress 4.7.5 / 4.8.1 / probably other versions

##### Your filter lists

All filters are disabled

##### Your custom filters (if any)

No custom filters

**Comment by gorhill** [comment]
Please verify whether:

- one or more legacy add-ons are causing this.
- the cause is <https://bugzilla.mozilla.org/show_bug.cgi?id=1396226>.

As described in [release notes of 1.14.6](https://github.com/gorhill/uBlock/releases/tag/1.14.6).

**Comment by ruda-almeida** [comment]
Hi, thanks for the incredibly fast reply!

I have every extension other than uBlock disabled. The issue persists.
I don't know how to verify bugzilla #1396226 other than https://www.bpostbanque.be/portal/Start.asp is a blank page to me unless I disable uBlock.

**Comment by ruda-almeida** [comment]
Closing as duplicate of #2949

**Comment by ruda-almeida** [comment]
Closing as duplicate of #2949

**Comment by gorhill** [comment]
> I don't know how to verify bugzilla #1396226

Use `view-source:https://[redacted]/wp-admin` and see if there are `document.write` calls in there.

**Comment by gorhill** [comment]
By the way, if you can confirm it is related to <https://bugzilla.mozilla.org/show_bug.cgi?id=1396226>, you need to add to the issue, they are still trying to assess how severe is the issue, how widespread it is.

**Comment by ruda-almeida** [comment]
Hi, sorry but turns out it really was a legacy addon causing the issue.
Anyway, as I'm still affected by #2949 I'll comment on the mozilla bug issue.

**Comment by gorhill** [comment]
> I'm still affected by #2949 I'll comment on the mozilla bug issue.

If you mean you can't load `https://www.bpostbanque.be/portal/Start.asp`, then no need to add to the issue, this affects everybody. They just want to know how many web sites break like this one.
