### ISSUE TITLE
with uBlock the jpg images are white

### ISSUE THREAD

**Issue by yves64250** [gorhill/uBlock#2975]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

With uBlock i have a blank page with a jpg (the JPG is 0 KB with page information),disabling uBlock the jpg is visible

### One or more specific URLs where the issue occurs

https://www.quizz.biz/uploads/quizz/1011995/7_98929.jpg
http://www.italianways.com/wp-content/uploads/2013/12/IW_Antonio-Corradini_LaPudicizia_04.jpg

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: windows 7 64 bits
- Browser/version: Firefox 55.0.3
- uBlock Origin version:  1.14.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Read the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.6) please.
