### ISSUE TITLE
've reposted this because adding youtube.com in front of the rule didn't work. Right now I have this rule and it applies to all youtube pages, not only the specified (youtube.com)

### ISSUE THREAD

**Issue by sNrVJx1** [gorhill/uBlock#2978]
# gorhill said:
> Insert youtube.com before the ## div tag

# I've reposted this because adding youtube.com in front of the rule didn't work. Right now I have this rule and it applies to all youtube pages, not only the specified (youtube.com):
`youtube.com###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)`

# Please help before closing the Issue post. Thank you :+1: 
____________________

### Describe the issue
I can not find a way to have the elements blocked ONLY on one page using the 'Element picker'.
If I block something on the home page of youtube, it automatically blocks the same elements on different pages from youtube (e.g. `youtube/watch/`, `youtube/abc/` , `youtube/asdas/`)

### One or more specific URLs where the issue occurs

Block an element on:
https://www.youtube.com/

For example: `###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)`

What I want to do is to block the recommend page (all the videos from the home, trending, subscriptions pages), it works but the PROBLEM is that: it blocks that element on any page from youtube:
Go to a video, for example this song: https://www.youtube.com/watch?v=L2uT0yivlrw
You'll not view the video because that element is blocked on youtube pages.

### Screenshot in which the issue can be seen

Before `###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)`

![1](http://i.imgur.com/BLIqNME.jpg)

After `###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)`

![2](http://i.imgur.com/p3yB88T.jpg)

# WHAT I DON'T KNOW HOW TO DO (THE PROBLEM)

**I don't know how to apply this rule `###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)` only for the home page of youtube (`www.youtube.com`)**
As you can see in the image below, the rule affects the `https://www.youtube.com/watch?v=L2uT0yivlrw` and I can't see any elements from the page.

![3](http://i.imgur.com/OHNCiJw.jpg)

### Steps for anyone to reproduce the issue

1. Go to `www.youtube.com`
1. Block `###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)` (you are blocking the 
Recommended videos from the home page.
1. Now that you've blocked the Recommended elements (videos), you should go to a video (e.g. `https://www.youtube.com/watch?v=L2uT0yivlrw`)
1. You'll notice that you don't see anything on the page because that rule blocks all elements from all youtube pages.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7 x64 SP1
- Browser/version: Chrome 60.0.3112.113
- uBlock Origin version: 1.13.8

##### Your filter lists

`###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)`

##### Your custom filters (if any)

`###page-manager > .ytd-page-manager.style-scope:nth-of-type(1)`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by UserNameA1** [comment]
Just add `www.youtube.com##ytd-browse[page-subtype="home"]` if you want to block the recommend page only.
