### ISSUE TITLE
Trouble Updating to 1.14.8

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#2980]
Since I know it has been released about 2 days now, I noticed that it is not updating on Firefox 55.0.3 (32) automatically or even by force checking for update. Surprisingly since 1.14.4 none of the updates have been coming through for me, namely 1.14.6 - not expecting RC ones.

Figuring that's just AMO delay getting it out, decided to just use the release files to update manually. However, it is adamantly rejecting to install it as unverified, which unless I am misreading the release page, shouldn't be the case. 

Any suggestions, since the old trick of turning off signatures no longer works on any stable version - meaning neither nightly nor dev? Or do we just have to wait until AMO pushes it out? Any idea why they haven't even pushed 1.14.6 out yet? Might it be the rapid release cycle we have been on recently?

Please advise how to proceed, thanks.

**Comment by akks1981** [comment]
https://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

scroll down to the post from "BlackJack August 14, 2017 at 1:48 pm"  works fine!

**Comment by GuardianMajor** [comment]
@akks1981 Thank you for the heads up but it is not working. I went through the instructions and also double checked everything and yet not only not working, but throws an error on browser start.

## Step 1
Saved `config.js` with the following code:
```
try {
Components.utils.import("resource://gre/modules/addons/XPIProvider.jsm", {})
.eval("SIGNED_TYPES.clear()");
}
catch(ex) {}

try {
Components.utils.import("resource://gre/modules/addons/XPIInstall.jsm", {})
.eval("SIGNED_TYPES.clear()");
}
catch(ex) {}
```
and placed it in the installation directory:

![step-1](https://user-images.githubusercontent.com/5274181/30079349-c60b849a-9234-11e7-90e6-8ad425bb36ed.PNG)

## Step 2
Saved `config-prefs` with the following code:
```
pref("general.config.obscure_value", 0);
pref("general.config.filename", "config.js");
```
and placed it under the default pref folder:

![step-2](https://user-images.githubusercontent.com/5274181/30079428-fb8642ea-9234-11e7-95c2-918161ec15ea.PNG)

## Result
As soon as you start the browser, it throws the following error:

![error](https://user-images.githubusercontent.com/5274181/30079514-4a466ca2-9235-11e7-8cee-87b2e4507eb3.PNG)

So either they removed support for this method, or they changed something which is causing it to fail, or a marginal possibility that I did something wrong (why I provided all the steps taken above in case).

Any other suggestions? Thanks.

**Comment by akks1981** [comment]
//
try {
Components.utils.import("resource://gre/modules/addons/XPIProvider.jsm", {})
.eval("SIGNED_TYPES.clear()");
}
catch(ex) {}

try {
Components.utils.import("resource://gre/modules/addons/XPIInstall.jsm", {})
.eval("SIGNED_TYPES.clear()");
}
catch(ex) {}

**Comment by akks1981** [comment]
step 1 u forget "//"

**Comment by GuardianMajor** [comment]
@akks1981 You are right, I did; but only because that's just a comment indicator, is it not? Just in came I am wrong, I am going to go ahead and add it and see what happens, no harm right? :)

Will post the results in a minute and let you know how it goes, hoping that it fixes it despite what I think 👍 

BRB

**Comment by GuardianMajor** [comment]
I am happy to report that I was wrong, the `//` made the difference, it worked, the browser didn't break on start and I was able to manually load the update.

Thank you for your help; it was a learning experience. Just curious then, if `//` is not interpreted as a comment indicator; out of curiosity and for my own edification, what does it signal that the lack of makes it break?

**Comment by akks1981** [comment]
dk, but 4 eyes see more than 2 ^^

**Comment by GuardianMajor** [comment]
Interesting, you are right it made it work, whatever the reason, thank you - appreciate you catching it for me. I will try to do some search and see if I can figure out why something that is usually just a comment indicator would make a difference. Maybe in the Firefox environment, it serves another reserved function, who knows. Either way, thanks.

**Comment by GuardianMajor** [comment]
@akks1981 Quick update, something very odd happened today. It worked before and has been running fine since but just now it popped up out of the blue and says this:

![disabled](https://user-images.githubusercontent.com/5274181/30132829-a3dc9986-9306-11e7-83d8-979bd33748b7.png)

Could there be some secondary check somewhere on a cycle that ignores the bypass we used and still disables what it considers unverified?

**Comment by akks1981** [comment]
idk sorry
