### ISSUE TITLE
Page navigation fails on some sites

### ISSUE THREAD

**Issue by Thorarin** [gorhill/uBlock#2981]
### Describe the issue

On some sites, Firefox navigation does not work as expected when uBlock Origin is enabled. The URL in the address bar changes, but otherwise nothing happens.

The development tools show that the page is requested, but for some reason the Transferred column is completely empty. The Response tab for that particular request is also completely empty.

The issue also occurs when uBlock Origin is disabled for the site in question, but the Addon itself is still enabled.

### One or more specific URLs where the issue occurs

https://www.tweakers.net/

This is not the only site on which I've encountered this, but I can't remember the others. There is a forum thread on this site where many other users report the same issue, unfortunately in Dutch: https://gathering.tweakers.net/forum/list_messages/1796753

### Screenshot in which the issue can be seen

![tweakers-pagenotloaded-networktab](https://user-images.githubusercontent.com/1827726/30076758-3d8a4b60-927a-11e7-937a-abfbce036012.png)

### Steps for anyone to reproduce the issue

1. Go to https://www.tweakers.net/
2. Navigate to an article
3. If the page loads normally, navigate back using the logo on the top left
4. Try navigating to an article again. Repeat until the page doesn't load.
   * Sometimes it takes some tries for the page load to fail (maybe 30% chance to fail for me)
   * It will occur even if uBlock Origin is disabled for the site, although it *appears to* occur less often.

### Your settings

All default settings.

- OS/version: Windows 10 (version 1703)
- Browser/version: Firefox 55.0.3 (32-bit)
- uBlock Origin version: 1.14.4

##### Your filter lists

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Unbreak
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list

##### Your custom filters (if any)

None.

**Comment by gorhill** [comment]
Try the steps documented in the [release notes of 1.14.6](https://github.com/gorhill/uBlock/releases/tag/1.14.6) please.

**Comment by gorhill** [comment]
Also see if the browser console (ctrl-shift-j) says something useful.

**Comment by Thorarin** [comment]
Thanks for the quick response.

Disabling legacy addons does indeed appear to make a difference. I have two: Lastpass and Xmarks.
If I disable both and restart Firefox, everything appears to be okay (although I haven't done a really extensive test yet)

I've re-enabled Lastpass, at which point everything still seems okay. Re-enabling Xmarks seems to bring back the issue.

Here's the browser console:
![browser-console](https://user-images.githubusercontent.com/1827726/30078687-5eb74ce4-927e-11e7-95ae-af6de84f87c7.png)

I don't know much about the internals of browser addons, but that main.js seems to include minified code snippets from multiple addons, not just one.

**Comment by gorhill** [comment]
As said in the release notes, all these legacy extensions which are interfering with uBO/webext qill no longer be allowed to load in FF57 in a few weeks. You could report the incompatibility to Firefox devs, whether they choose to spent time fixing this is doubtful. uBO merely uses the webext API, it knows nothing about other extensions.

**Comment by Thorarin** [comment]
Firefox 57 is scheduled for November 14th, so that's a bit more than a few weeks... But yeah, it's somewhat doubtful that things will get fixed before then if the issue is with FF itself.

**Comment by Maikell84** [comment]
I still have the issue on Firefox 57.0b9 (64-bit) on debian 9
