### ISSUE TITLE
uBlock Origin may prevent displaying result of form submission.

### ISSUE THREAD

**Issue by sagamusix** [gorhill/uBlock#2982]
### Describe the issue

Try uploading a file through [this example form](http://sagamusix.untergrund.net/fileupload-2.htm). If uBlock Origin is disabled, this works as expected and you see a page saying "Done!".
But if you enable uBlock Origin in Firefox 55, the form is submitted, but without visually changing to the target URL. The request is processed on the server but the browser keeps displaying the form page forever.
There is also another variant of this form which crashes Firefox entirely when uBlock Origin is enabled. I have submitted it as a private bug report to Mozilla as it might be relevant for security. Since GitHub issues do not support reporting such sensitive information, I will not post the URL here.

### One or more specific URLs where the issue occurs

http://sagamusix.untergrund.net/fileupload-2.htm

### Steps for anyone to reproduce the issue

1. Open example URL from above
2. Select a file to upload
3. Hit submit button.

### Your settings

- OS/version: Windows 7 x64
- Browser/version: Firefox 55 / 52 ESR x64
- uBlock Origin version: 1.14.4

##### Your filter lists

Default filter lists + EasyList Germany

**Comment by gorhill** [comment]
Please, go through [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.4). Close if you find the cause is a legacy extension.

**Comment by KapitanKabzon** [comment]
Found a few addons which interfere with uBlock and make browsing impossible,
Superstart,New tabs at the end either of these with connection with uBlock Origin on Firefox 55 and 53 makes the display not update even though the URL has changed.
The testbench i used was just Ebay.co.uk, enter something into search e.g.:"525tds injector", when running without ublock but SUperstart and New tab at the end is running the site works as intended, as soon as uBlock is turned on as addon the page stays on the start page even though the URL has changed, If needed further proof a video will be made.

**Comment by sagamusix** [comment]
The bug seems to happen in combination with any of those three add-ons:
* Better Stop
* Image Zoom (Ugly Fixes)
* Web Developer

**Comment by gorhill** [comment]
What are the errors reported in the browser console? From other cases, I wonder if the issue is specifically caused by SDK-based extensions. If so, maybe there is a trivial fix that can be made by Firefox devs. In any case, this needs to be reported to them.

**Comment by sagamusix** [comment]
After submitting the form there are only four events in the console:
* TypeError: this._recipeManager is null[Weitere Informationen]  LoginManagerParent.jsm:106:9
* Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/  jquery-1.12.4.min.js:4:26272
* TypeError: document.getElementById(...) is null[Weitere Informationen]  fileupload-2.htm:30:25
* TypeError: document.getElementById(...) is null[Weitere Informationen]  fileupload-2.htm:30:25

I somehow feel that the warning about synchronous XMLHttpRequests in jQuery might be somewhat related.

**Comment by sagamusix** [comment]
Before reporting the issue here, I also reported it at https://bugzilla.mozilla.org/show_bug.cgi?id=1396396

**Comment by ToddAndMargo** [comment]
Add to the list of web sites giving issues:
      https://email12.godaddy.com/pcompose.php
      workspace email can not compose

      http://www.gunwerks.com/ballistics
      login button ignored

**Comment by drmike** [comment]
A quick check of the elements in question shows that it's filtering on tinymce.  Should be a matter of finding which filter is filtering on that in relation to godaddy.
