### ISSUE TITLE
ublock origin no longer works on Firefox Mobile

### ISSUE THREAD

**Issue by fu8765** [gorhill/uBlock#2983]
### Describe the issue
On firefox Mobile 54.0.1
ublock origin seems not to be working/not blocking ads.
on the options/hamburger menu, ublock origin entry is no longer there.

If you go into tools/addons, ublock origin is installed, and enabled.

### One or more specific URLs where the issue occurs
everywhere

### Steps for anyone to reproduce the issue
1)Install Firefox Mobile from the play store
2) Install Ublock origin from Firefox addon repository

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Android 7.1.1
- Browser/version: Firefox Mobile 54.0.1
- uBlock Origin version:  1.14.4

**Comment by gwarser** [comment]
Search here for android https://github.com/gorhill/uBlock/releases

**Comment by gorhill** [comment]
> options/hamburger menu, ublock origin entry is no longer there

Duplicate of #2958.
