### ISSUE TITLE
Can't update filters on Tablet

### ISSUE THREAD

**Issue by findow** [gorhill/uBlock#2985]
I can't update filters on tablet: debugging remotely I have these errors in Console

AbortError (2)vapi-cachestorage.js:231:16
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. (2)vapi-cachestorage.js:231

Firefox Nightly updated yesterday, lastest Ublock development channel

**Comment by gorhill** [comment]
It's as if uBO's `indexedDB` was not allowed. You wholly disabled cookied, or some related setting in `about:config`?

**Comment by findow** [comment]
On my Tablet? Not at all.

**Comment by gorhill** [comment]
Private mode then?

**Comment by findow** [comment]
This happens at browser startup, before I can even start opening tabs.

**Comment by gorhill** [comment]
This can happens if you are using permanent private mode. At this point you need to investigate on your side, I can't do this for you. Maybe share the information shown in `about:support`.

**Comment by findow** [comment]
Got these errors while trying to update filters

[uBlock0 cacheStorage] error { target: IDBRequest, isTrusted: true, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 318158.318663, cancelBubble: false, originalTarget: IDBRequest, explicitOriginalTarget: IDBRequest }  vapi-cachestorage.js:86:9
[uBlock0 cacheStorage] [object Event]  (sconosciuto)
QuotaExceededError  vapi-cachestorage.js:231:16
[uBlock0 cacheStorage] error { target: IDBRequest, isTrusted: true, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 318472.781121, cancelBubble: false, originalTarget: IDBRequest, explicitOriginalTarget: IDBRequest }  vapi-cachestorage.js:86:9
[uBlock0 cacheStorage] [object Event]  (sconosciuto)
QuotaExceededError  vapi-cachestorage.js:231:16
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.  vapi-cachestorage.js:231

**Comment by gorhill** [comment]
The other errors do not matter, only the first one matters. I will need `about:support`, if there is anything I can do, that will be only with this. If nothing comes out of this, report to Firefox devs,

**Comment by findow** [comment]
Informazioni di base
--------------------

Nome: Fennec
Versione: 57.0a1
ID build: 20170905100122
Canale di aggiornamento: nightly
User agent: Mozilla/5.0 (Android 4.2.2; Tablet; rv:57.0) Gecko/57.0 Firefox/57.0
SO: Linux 17
Finestre multiprocesso: 0/1 (Disattivato)
Processi contenuti web:
Stylo: false (disattivato per configurazione build)
Chiave Google: Disponibile
Chiave per il servizio Mozilla Location: Disponibile
Modalità provvisoria: false

Segnalazioni di arresto anomalo degli ultimi 3 giorni
-----------------------------------------------------

Tutte le segnalazioni     Caratteristiche di Nightly
----------------------------------------------------

Nome: FlyWeb
Versione: 1.0.0
ID: flyweb@mozilla.org

Estensioni
----------

Nome: Decentraleyes
Versione: 2.0.0beta1
Attiva: true
ID: jid1-BoFifL9Vbdl2zQ@jetpack

Nome: uBlock Origin
Versione: 1.14.9b0
Attiva: true
ID: uBlock0@raymondhill.net

Nome: Violentmonkey
Versione: 2.6.3
Attiva: true
ID: {aecec67f-0d10-4fa7-b7c7-609a2db280cf}

Nome: View Source Mobile
Versione: 0.1.1.1-signed.1-signed
Attiva: false
ID: viewsourcemobile@xuldev.org

Grafica
-------

Caratteristiche
Composizione: OpenGL
Panoramica/zoom asincroni (APZ): input touch attivo; scorrimento automatico attivo
Informazioni driver WSI WebGL 1: -
Renderer driver WebGL 1: WebGL creation failed: * Requires vertex_array_object. * Exhausted GL driver options.
Versione driver WebGL 1: -
Estensioni driver WebGL 1: -
Estensioni WebGL 1: -
Informazioni driver WSI WebGL 2: -
Renderer driver WebGL 2: WebGL creation failed: * Error during native OpenGL init. * Error during native OpenGL init. * Exhausted GL driver caps. * Exhausted GL driver options.
Versione driver WebGL 2: -
Estensioni driver WebGL 2: -
Estensioni WebGL 2: -
GPU #1
Attivo: Sì
Descrizione: Model: Sirius_Evo_QS, Product: Sirius_Evo_QS, Manufacturer: VONINO, Hardware: Sirius_Evo_QS, OpenGL: ARM -- Mali-400 MP -- OpenGL ES 2.0
ID produttore: ARM
ID dispositivo: Mali-400 MP
Versione driver: OpenGL ES 2.0

Diagnostica
AzureCanvasAccelerated: 1
AzureCanvasBackend: skia
AzureContentBackend: skia
AzureFallbackCanvasBackend: none
TileHeight: 256
TileWidth: 256
Device Reset: Avvia ripristino dispositivo
Registro decisioni
HW_COMPOSITING:
force_enabled by user: Force-enabled by pref
OPENGL_COMPOSITING:
force_enabled by user: Force-enabled by pref
WEBRENDER:
opt-in by default: WebRender is an opt-in feature




Media
-----

Back-end audio: opensl
Numero massimo di canali: 2
Layout preferito dei canali: unknown
Frequenza di campionamento preferita: 44100
Dispositivi di output
Nome: Gruppo
Dispositivi di input
Nome: Gruppo

Preferenze importanti modificate
--------------------------------

browser.cache.disk.capacity: 102400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.startup.homepage_override.mstone: 57.0a1
dom.presentation.device.name: Sirius_Evo_QS
extensions.lastAppVersion: 57.0a1
font.size.inflation.minTwips: 120
general.useragent.updates.lastupdated: 1504398092735
media.autoplay.enabled: false
media.gmp-gmpopenh264.abi: arm-eabi-gcc3
media.gmp-gmpopenh264.enabled: false
media.gmp-gmpopenh264.lastUpdate: 1470959328
media.gmp-gmpopenh264.version: 1.6
media.gmp-manager.buildID: 20170905100122
media.gmp-manager.lastCheck: 1504725317
media.gmp.storage.version.observed: 1
media.peerconnection.ice.proxy_only: true
media.webrtc.debug.log_file: nspr
network.cookie.prefsMigrated: true
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.predictor.enabled: false
network.prefetch-next: false
plugin.importedState: true
privacy.trackingprotection.pbmode.enabled: false
storage.vacuum.last.index: 0

Preferenze importanti bloccate
------------------------------

JavaScript
----------

GC incrementale: true

Accessibilità
-------------

Attivato: false
Impedisci accessibilità: 0

Versioni librerie
-----------------

NSPR
Versione minima prevista: 4.17 Beta
Versione in uso: 4.17 Beta

NSS
Versione minima prevista: 3.33 Beta
Versione in uso: 3.33 Beta

NSSSMIME
Versione minima prevista: 3.33 Beta
Versione in uso: 3.33 Beta

NSSSSL
Versione minima prevista: 3.33 Beta
Versione in uso: 3.33 Beta

NSSUTIL
Versione minima prevista: 3.33 Beta
Versione in uso: 3.33 Beta

Caratteristiche sperimentali
----------------------------

**Comment by gorhill** [comment]
I don't see anything in there. I don't know what to do at this point aside report to Firefox devs -- from uBO's point of view, the browser does not want uBO to get access to the `indexedDB` database.

**Comment by findow** [comment]
Did I add too many filter lists?
![index1](https://user-images.githubusercontent.com/2287498/30136160-f0f4cee4-935d-11e7-8102-6aa17a778c19.png)
![index2](https://user-images.githubusercontent.com/2287498/30136159-f0b48000-935d-11e7-9d81-0063b1e7b249.png)
![index3](https://user-images.githubusercontent.com/2287498/30136158-f09082cc-935d-11e7-9821-ba78f81033ac.png)
![index4](https://user-images.githubusercontent.com/2287498/30136164-f1f7c936-935d-11e7-8e00-7db613cc26db.png)

**Comment by gorhill** [comment]
> Did I add too many filter lists?

If this was the issue then there would be no error message just launching uBO?

But you can always try to un-check filter lists and see if this helps.

**Comment by gorhill** [comment]
Any news on this?

**Comment by findow** [comment]
Sorry for delay.
I have not reported the error on Bugzilla, but I discovered that QuotaExceededError is thrown from the onabort() method, but you only implemented onerror().
https://www.html5rocks.com/en/tutorials/offline/quota-research/#toc-how_to_handle_going_over_quota
That aside, when I get the error I have the same visual bug as in https://github.com/gorhill/uBlock/issues/3018

**Comment by gorhill** [comment]
> but I discovered that QuotaExceededError is thrown from the onabort() method

So it would appear there is a limit to the amount of data uBO can save in indexedDB after all.

**Comment by findow** [comment]
It seems to be related to the free space on the device, but with the Legacy version I never had such a problem.

**Comment by findow** [comment]
Is there anything else I have to provide?
At this point I see 2 roads:
1. Ask mozilla to increase the limits for low memory devices (tablet and smartphones usually have 4, 8 and recently 16GB of internal memory)
2. Compress (zip compress?) ublock cached assets before storing them
Whathever decision you take, could you implement onabort() so to make updating filters fail gracefully?

**Comment by gorhill** [comment]
I will add code to deal with `onabort`.

**Comment by jasoncook** [comment]
Is this issue strictly limited to tablets? I'm having a similar issue on Windows and FreeBSD clients:

`A network error prevented the resource from being updated`

![image](https://user-images.githubusercontent.com/4571376/30767080-d88cbee2-9f9d-11e7-9ce9-fb88c6fab141.png)

**Comment by vladus2000** [comment]
I see the same issue as jasoncook on arch linux, release channel firefox.  I have many of the filter lists checked.

**Comment by gorhill** [comment]
Please do not add noise to this issue. Network errors are unrelated to the issue here. Something is preventing uBO from fetching the list on your side, investigate these errors networks on your side.

**Comment by gorhill** [comment]
`onabort` handlers added with a264975c9cc03c53f8d264dbb8783e2a8a85aef9.
