### ISSUE TITLE
Spinner on site https://answers.microsoft.com/en-us/newthread?threadtype=Questions&cancelurl=%2Fen-us

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2990]
Windows 10 Pro x86-64
Fx57 Nightly
uBlock Origin v1.14.9b0
Default filter lists.

Going to the site with uBO enabled results in a spinner that never ends.  Using the page will result in errors.  Site works fine when I disable uBO.  Please be aware that there is another add-on that causes the same problem.  It is called bitwarden which is also a true Webextensions add-on.  If you need more info give me a SHOUT.

https://answers.microsoft.com/en-us/newthread?threadtype=Questions&cancelurl=%2Fen-us

**Comment by mapx-** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1397399
https://bugzilla.mozilla.org/show_bug.cgi?id=1379148

**Comment by gwarser** [comment]
Should be fixed now in Firefox nightly and beta.
