### ISSUE TITLE
Is there any way to "embed" ublock origin inside my website

### ISSUE THREAD

**Issue by ZeroCool940711** [gorhill/uBlock#2996]
Hi there, I know this could sound weird and to be honest I'm not sure if its possible but I would like to have ublock origin embedded into my website, what I mean by this is I would like to have some way to have ublock installed into my website blocking all ads and things the same way it work if you install it normally on firefox or chrome. The reason why i want to do this is because I use a few video hosting services like openload.co and streamango.com and they have a lot of ads, I tried using different methods to block the ads but had no luck with that and almost got banned from both services, the only way to block the popups and ads from those hosting is with ublock origin or another adblock extension, I do not want to tell my users to install extensions and redirect them to another site to install them as many users do not like that or do not trust websites that ask to install extensions, many of those websites usually send you to install some kind of malware so, what I want to do is have ublock embedded into my website blocking those annoying ads for my users so they can enjoy the content without having to worry for popups or ads. If this could be possible and you could give me some info on how to do it I would appreciate it a lot. Thanks for your time.

**Comment by gorhill** [comment]
This is not the place to ask for this.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
