### ISSUE TITLE
Prebake - Filter Obtrusive Cookie Notices - not updated

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#2997]
Can you remove this filters ?
! Title: Prebake - Filter Obtrusive Cookie Notices 
! Last modified: 04 May 2016 20:17 UTC

**Comment by gorhill** [comment]
Which one out there is best to use as replacement?

**Comment by MajkiIT** [comment]
I will find new filters. Give me a few days.

**Comment by mapx-** [comment]
https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

**Comment by hawkeye116477** [comment]
@gorhill I don't care about cookies is the biggest, but it's not updated almost 2 months. On the other hand though, Fanboy's Cookiemonster is updated frequently, but is smaller. I do not know whether I do not care will continue to update or not, so probably the best choice is Fanboy's Cookiemonster.

Also for Polish sites I would add this -> https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt, because Fanboy's or I don't care both has little rules for Polish sites.

**Comment by gorhill** [comment]
Thanks for the input.

In the end I picked "Fanboy's Cookiemonster". The entry has been put under "Social", which I intend to rename "Annoyances".

**Comment by shellye5** [comment]
@gorhill can you also add
English filter
Spyware filter
Social media filter
Annoyances filter
Experimental filter
Mobile ads filter
Safari filter
Simplified domain names filter

from
https://kb.adguard.com/en/general/adguard-ad-filters

as they are fork and block everything (easylist allows somethings & prefer these)

**Comment by signalguest** [comment]
Fanboy's Cookiemonster seems a subset of Fanboy’s Annoyance

**Comment by hawkeye116477** [comment]
@signalguest Yes, it's subset of Fanboy’s Annoyance. But Annoyance blocks other elements than cookies too and not everyone wants to block other elements than cookies, so that's why there are 2 fitler lists.

**Comment by signalguest** [comment]
What if we ~~do something like this~~ on the subset when the set is used?

**Comment by Myer** [comment]
This is also a good replacement for the old Prebake filterlist:
https://gitlab.com/isaakm/Custom-Prebake
https://gitlab.com/isaakm/Custom-Prebake/raw/master/filterlist.txt

> A set of Adblock filters to block obtrusive EU cookie law notices. This is a fork from the original Prebake files because the updates there were many months behind and the list becoming bloated with outdated records, therefore I decided to make my own fork. It's as much as possible updated and cleaned up.

**Comment by vlakoff** [comment]
I think it doesn't fit well in the "Social" section. How is it related to this?

I suggest moving it to either:
* section "Privacy'
* section "Regional", prepended with "EU", as before
* create a new section "Retard laws"

**Comment by vlakoff** [comment]
btw, refs #1609 :)
