### ISSUE TITLE
Tab For a Cause ads not loading after whitelist in Chrome

### ISSUE THREAD

**Issue by baudtack** [gorhill/uBlock#300]
Running:
Tab for a Cause 5.13 (http://www.tabforacause.org)
uBlock Origin 0.9.8.3
Google Chrome Version 42.0.2311.90 (64-bit) on Debian Linux

Using the following whitelist:

> about-scheme
> behind-the-scene
> chrome-extension-scheme
> chrome-scheme
> loopconversation.about-scheme
> opera-scheme
> www.tabforacause.org

ads in new tabs for tab for a cause fail to appear. However they do appear when going directly to http://www.tabforacause.org/newtab

**Comment by baudtack** [comment]
Trying to add `chrome://newtab` or `newtab` to the white list did not resolve the problem

**Comment by Snapy** [comment]
Try with `newtab.chrome-scheme`.

**Comment by baudtack** [comment]
Still doesn't work.

**Comment by Snapy** [comment]
Then add `behind-the-scene` if it's not already there.

**Comment by gorhill** [comment]
> Try with `newtab.chrome-scheme`

This won't work.

Here is what I observe: when a new tab is created, an orphan `iframe` is created, which URL is something like `http://www.tabforacause.org/newtab/?browser=chrome&v=5.13`. uBlock's whitelisting applies to top frames, not embedded frames. So given that the user wants to whitelist whole `www.tabforacause.org` anyways, I created a static exception filter:

    @@*$domain=tabforacause.org

This resulted in a lot of ad-related network request to go through all fine. But there are still a couple of network requests which are still filtered, and I am investigating why. These requests are reportedly made outside any context, this should not happen.

**Comment by baudtack** [comment]
Hrm. You add that under My Filters?

**Comment by baudtack** [comment]
If i'm reading the log right it looks like it lets a bunch of requests through but still blocks the doubleclick requests because of `||doubleclick.net^`

**Comment by gorhill** [comment]
uBlock is kind of in an anomalous state for that new tab: it has to do with the unexpected case of an embedded frame (the `tabforacause.org` one) being used in that new tab, but that frame has no parent frame like all normal web page do. Give me time to investigate.

**Comment by gorhill** [comment]
Ok, I have a fix, and as expected you won't need to whitelist `www.tabforacause.org` or to create a special filter `@@*$domain=tabforacause.org`. The only requirement will be to whitelist `newtab.chrome-scheme` as Snappy pointed out. This is what was broken.

**Comment by gorhill** [comment]
I published the fixed version (0.9.8.6) to the Chrome store, but now the extension always take time before being approved, so given that it's Friday, I wouldn't be surprised that it gets approved next week only.

**Comment by baudtack** [comment]
\o/ awesome!

**Comment by gorhill** [comment]
For the record to prevent future regression, I believe the bug here was a regression of #248.
