### ISSUE TITLE
REEK AAK Auto removed when updating filters

### ISSUE THREAD

**Issue by bit-blit** [gorhill/uBlock#3002]
### Issue
This is NOT an issue with a specific filter, so I thought it would be ok to post the issue/change here. Sorry if this is not protocol (not sure - new to this), but the issue is with the LIST of stock filters within uBO.

Updated filters today and REEK's AAK auto removed itself from list of filters. Expected behaviour/List now removed from stock?

Steps to reproduce:
[1] Update filters as normal (I always do a manual update)
Behaviour: REEK's AAK list is auto removed/deleted from the list of stock filters

### Settings

- OS/version: macOS 10.12.6 
- Browser/version: Firefox 55.0.3 (latest stable)
- uBlock Origin version: 1.14.4

##### Filter lists

Default filter lists + REEK's AAK

**Comment by gorhill** [comment]
It's removed from stock filter lists, it should appear as a custom filter list, look carefully.
