### ISSUE TITLE
Outlook Web App not working with the webextension, even if disabled for the whole site

### ISSUE THREAD

**Issue by Gyokur0** [gorhill/uBlock#3004]
We are using the OWA with MS Exchange internally for e-mail, and with the webextension of uBlock it now longer works correctly (e.g. when creating a new mail, the signature is missing).

This is **not** a filter issue, if I disable the extension for the whole webpage (grayed out uBlock icon) it still throws js errors. Only if I uninstall or disable the extension in the firefox addon manager, it works again.

**This is the reason I opened a issue, because it seems that uBlock in the webextension version is still injecting some javascript into the page even if it is disabled.** 

In the firefox devtools console I see the following error thrown from Outlook Web App
Exception Details
Message: TypeError: i is undefined
(...)
Line: <ourDomain>/owa/prem/15.0.1263.5/scripts/boot.0.mouse.js::82

- OS/version: Win 8.1 Pro 64
- Browser/version: Firefox Dev 56.0b10
- uBlock Origin version: Any webextension based, currently 1.14.4  and 1.14.9b0

**Comment by gorhill** [comment]
Did you disable _all_ legacy extensions?

If so, then this is browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1379148>.
