### ISSUE TITLE
ublock causes google chrome tab to crash on web page which uses ajax to load tons of new content

### ISSUE THREAD

**Issue by arekm** [gorhill/uBlock#3005]
### Describe the issue
When uBlock is enabled and site that endlessly loads new content after scrolling current page then browser tab crashes finally. If uBlock extension is disabled then there is no such problem.

### One or more specific URLs where the issue occurs
https://jokideo.tumblr.com/

### Steps for anyone to reproduce the issue

1. Install google chrome (here 61.0.3163.79 on Linux)
2. install uBlock
3. configure as:

[my-ublock-backup_2017-09-11_12.13.03.txt](https://github.com/gorhill/uBlock/files/1292171/my-ublock-backup_2017-09-11_12.13.03.txt)

4. use fresh google chrome or allow uBlock to be used in incognito mode and go into new incognito tab
5. open web page: https://jokideo.tumblr.com/
6. press and keep "space" key to scroll page and load new content.
7. do that for few minutes until google chrome tab crashses with "oops something went wrong"

### Your settings

- OS/version: PLD/Linux Th 64bit (current)
- Browser/version: google-chrome 61.0.3163.79 64bit
- uBlock Origin version: 1.14.8

**Comment by gorhill** [comment]
Report browser crash to Chromium devs.
