### ISSUE TITLE
 locked and limited conversation...

### ISSUE THREAD

**Issue by nickma82** [gorhill/uBlock#3008]
@gorhill https://github.com/gorhill/uBlock/issues/2965#issuecomment-328555722 brought me nowhere... 

Beside that: I have to say how fucked up it is to prevent one to speak in an - anyway - closed topic, about that very topic!
It's **your notification settings** which are wrong, not the matter of fact one wants to speak about it!

**Comment by gorhill** [comment]
> It's your notification settings which are wrong

Take the time to read carefully instead of asking repo owners to change their notification settings.

**Comment by hukkay** [comment]
@nickma82 Stop your drama / vulgarity / harassing
