### ISSUE TITLE
Firefox legacy version (uBlock0.firefox.xpi) is missing an updateURL in its manifest

### ISSUE THREAD

**Issue by user139** [gorhill/uBlock#3013]
I want to keep using the legacy version, so instead of sticking to 1.13.8, I figured I should just install uBlock0 directly from GitHub. The problem is, if I let Firefox (52 ESR) update the add-on, it gets updated to the WebExt version off of AMO.

**Comment by gorhill** [comment]
Just disable auto-update for uBO.

**Comment by uBlock-user** [comment]
You will have to compromise something if you intend to stay on LEGACY versions, also in time development of LEGACY version may cease completely FYI
