### ISSUE TITLE
A favour

### ISSUE THREAD

**Issue by xevidencex** [gorhill/uBlock#3015]
Hi gorhill, could you please provide me the code to make ubo 1.11.4, (the only version that works with my ff44 that supports all my addons)
run wildcards, if it wouldn't mess with ff44's ui to the point of crashing it, actually, any version above ubo 1.11.4 makes troubleshooting information & other sites
like https://support.mozilla.org/en-US/questions/new/desktop/other/form?search=FF & sites that have icons that allow me to upload files, crash..

ex: www.ebay.*###anything..
& co..

**Comment by mapx-** [comment]
You can download it directly from:
https://github.com/gorhill/uBlock/releases/tag/1.11.4
