### ISSUE TITLE
Dashboard not showing up in Firefox 55.0.2 for Android

### ISSUE THREAD

**Issue by Mad5555** [gorhill/uBlock#3016]
### Describe the issue
On my Galaxy Tab S3 (SM-T825) with Firefox 55.0.2 it is not possible to open dashboard of uBlock Origin anymore. uBlock Origin 1.14.8 is the only installed add-on. Also tried 1.14.11b0 with same issue.

On my Galaxy S7 (SM-G930F) everything works as expected.

### One or more specific URLs where the issue occurs

Any URL.

### Screenshot in which the issue can be seen

![screenshot_20170915-083257](https://user-images.githubusercontent.com/31981485/30469599-4d087f34-99f1-11e7-9f4e-b95c28a61400.png)

### Steps for anyone to reproduce the issue

1. Open Firefox.
2. Open any URL.
3. Open Menu and try to access uBlock Origin dashboard.

### Your settings

- OS/version: Android 7.0, Build NRD90M.T825XXU1AQF3 from Samsung
- Browser/version: Firefox for Android 55.0.2
- uBlock Origin version: 1.14.8 & 1.14.11b0

##### Your filter lists

Defaults only, as freshly installed in order to troubleshoot.

##### Your custom filters (if any)

No.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/2958
