### ISSUE TITLE
[firefox version]The page does not open

### ISSUE THREAD

**Issue by 247192825** [gorhill/uBlock#3017]
http://img02.taobaocdn.com/tfscom/TB1pspSQFXXXXbKXFXXxKNpFXXX.jpeg
The page can not be opened, chrome browser can be opened, firefox disable uBlock Origin can be opened
http://img01.taobaocdn.com/tfscom/TB1c_oYQpXXXXcXaXXXxKNpFXXX.jpeg
http://img01.taobaocdn.com/tfscom/TB1B8dsQFXXXXbEXXXXxKNpFXXX.jpeg

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
