### ISSUE TITLE
Filter list updates hang on Firefox

### ISSUE THREAD

**Issue by matoro** [gorhill/uBlock#3018]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Ever since migrating to webext, I have been unable to *manually* update filter lists.  The update available marker will change to the loading circle and hang indefinitely.  I believe automatic updates to be working, though I am not sure of the automatic update frequency so I can't verify this.

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

See attached recording
[recording.zip](https://github.com/gorhill/uBlock/files/1306798/recording.zip)

### Steps for anyone to reproduce the issue

The issue is always reproducible

### Your settings

All defaults, except for advanced mode enabled.

- OS/version: Arch Linux 4.12.13
- Browser/version: Firefox 55.0.3
- uBlock Origin version: 1.14.8

##### Your filter lists

Default filter lists minus all languages

**Comment by gorhill** [comment]
Manual update is exactly the same code path as automatic update, only the timing changes.

As asked from you in CONTRIBUTING, you did not investigate minimally.

Investigating minimally means:

- Did you look at uBO's logger?
- Did you look at the browser console?
- Did you try to find out whether another extension is interfering? (disable all other extensions).

There is no issue of uBO failing to update its filters, and such reported issues were always traced back to another extension interfering. So I will close this issue, and ask you to investigate first to minimally make the case the issue is with uBO itself -- I can't do this for you.

**Comment by Hirato** [comment]
My filter lists haven't been updated in well over 2 months either, and i just thought to finally look into why.

The extension that was blocking the updates was uMatrix.
A bit odd IMO, since I thought it whitelisted all the special chrome/extension/about urls by default.

**Comment by matoro** [comment]
@gorhill Fair enough.  Went through and checked some of the basic possible causes you mentioned.

- The console does not seem to show anything - no network requests logged on the network tab, no javascript errors on the console tab.
- uBlock logger does not show anything, no network requests
- Disabled all other extensions, problem still persists.
- Connection issues are not the problem.  I let the update run for 30+ minutes - always loading circles on all filter lists.  This did not use to be a problem on the same connection.
- I also verified that this was a Firefox-specific issue - the issue does not show up on Iridium (Chromium-based) browser.

I understand that this is very little information to go off of, and if this makes the problem undiagnosable, I understand.

**Comment by gorhill** [comment]
Can you tell me what if any are the custom settings you have in your Firefox?

**Comment by matoro** [comment]
Will ```prefs.js``` contain only overridden settings or all settings?

**Comment by gwarser** [comment]
Modified, not resetted.
Maybe `about:config` -> "Important Modified Preferences"?

**Comment by gorhill** [comment]
> Maybe about:config -> "Important Modified Preferences"?

I think you meant `about:support`.

**Comment by matoro** [comment]
Here's modified settings: 
[prefs.txt](https://github.com/gorhill/uBlock/files/1308492/prefs.txt)

**Comment by gorhill** [comment]
I can't figure why you have this issue. Last thing I can suggest is try with a new profile. If this does not work, somebody else will have to figure your issue, I don't see what can be the cause.

**Comment by theDuckIsAlive** [comment]
Just add the following in uMatrix under "My rules" :

matrix-off: moz-extension-scheme true

**Comment by mazesy** [comment]
I've had this issue, that of filters lists not being "updatable" with a Firefox profile located on a RAM disk. uB0-legacy would update but not uB0-WE, whatever version and with the exact same browser configuration. Never encountered the issue with a Firefox profile on the hard disk.

**Comment by Devices** [comment]
My filters didn't update until I added the solution posted by @theDuckIsAlive 

Confirmed to work for me at least.

**Comment by mazesy** [comment]
The solution posted by @theDuckIsAlive concerns uMatrix, not uB0.

**Comment by theDuckIsAlive** [comment]
> The solution posted by @theDuckIsAlive concerns uMatrix, not uB0.

Yes it concerns also uBlock, if you use both together.
uBlock-legacy URL is ` chrome://` and uBlock-WE URL is `moz-extension://`
Just like` chrome-scheme`  make sure that `moz-extension-scheme` is also whitelisted in both uBlock and uMatrix

under "uBlock >> Whitelist"
`moz-extension-scheme`

under "uMatrix >> My rules"
`matrix-off: moz-extension-scheme true`

**Comment by mazesy** [comment]
OK, i get it, I should have figured that out, here with uB0 only.

But rather than adding `moz-extension-scheme` to _uBlock's Whitelis_t I'll proceed as I did with all the schemes included by default in that Whitelist, that is, in _My rules_ : 

```
moz-extension-scheme * 3p noop
moz-extension-scheme * 3p-frame noop
moz-extension-scheme * 3p-script noop
```

Seems to me this ads security to flexibility.

**Comment by gorhill** [comment]
> Seems to me this ads security to flexibility.

This won't accomplish much with uBO/webext, as uBO is not allowed to intercept network requests from other extensions.

**Comment by mazesy** [comment]
> This won't accomplish much with uBO/webext, as uBO is not allowed to intercept network requests from other extensions.
I ignored this limit concerning uBO-WE because, after having tested it quickly, I prefer for the time being rely on the legacy version (uBlock0.firefox.xpi 1.14.10 at this time), which is why the `moz-extension-scheme` appeared to me logical. To illustrate this pertinence (on uBO-legacy, OK)I did have two Webextensions blocked by uBO which required,
```
141820ae-fbd0-48f7-ad5c-952e4cafc024.moz-extension-scheme meteoblue.com * noop
4f89a4c0-7217-468a-bc7f-08801e7a829b.moz-extension-scheme googleusercontent.com * noop
```

The first being the _InfoWeather_ Webextension, the second being the AnonTab Webextension. I deleted both above with the three `moz-extension-scheme` added to _My rules_

Now, from what you write, @gorhill , as I understand it any Webextension will not be filtered by uBO-WE which means that the user will have to rely on the system's protection to defeat unhealthy connections established by a Webextension. I'm not fond of that. One more reason to stick on uBO-legacy as long as possible.

**Comment by gorhill** [comment]
> as I understand it any Webextension will not be filtered by uBO-WE which means that the user will have to rely on the system's protection to defeat unhealthy connections established by a Webextension. I'm not fond of that.

Me neither, I want users to be able to control all network requests from other extensions. Even just the ability to observe those network requests would be an improvement, currently users are left completely in the dark about where extensions are phoning. People will have to ask Mozilla to support this, probably through a specific permission. But frankly by the look of it, I am not too optimistic about this.

**Comment by matoro** [comment]
@mazesy , that was it!  I was using graysky's profile sync daemon ( https://github.com/graysky2/profile-sync-daemon ) to keep my Firefox profile in RAM for faster loading, turns out it was interfering with uBlock origin!  However I can use uBlock and PSD in combination with Chromium-based browsers.  I will report this issue on PSD's bug tracker and close this issue.  Thank you for giving this a shot on such limited information @gorhill .
