### ISSUE TITLE
hpHosts list updates blocked

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#302]
Looks like the EasyList rule `.net/ad_` is blocking filter updates from http://hosts-file**.net/ad_**servers.txt when behind-the-scenes is noop, obviously. Will require an unbreak rule?

(Also, `hpHosts’s` should just be `hpHosts`, or, if you want to denote ownership, just `hpHosts’`.)

**Comment by gorhill** [comment]
[Behind the scene network requests](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests):

> **Important:** Filter behind-the-scene requests at your own risk. I will close without further comment any reported issue which is a direct consequence of blocking behind-the-scene network requests.

**Comment by luxoflux** [comment]
Right, my bad.

Then you can address that tiny grammar issue, so this wouldn't be a totally wasted report. Heh.

**Comment by neilishere** [comment]
I used noop in My rules (overrides static filters):
`behind-the-scene easylist-downloads.adblockplus.org * noop`
`behind-the-scene pgl.yoyo.org * noop`
`behind-the-scene raw.githubusercontent.com * noop`

Maybe `behind-the-scene hosts-file.net * noop`  ?

**Comment by gorhill** [comment]
> I used noop in My rules (overrides static filters)

`noop` overrides dynamic filtering rules, not static filtering.

Using a dynamic URL filtering rule might be the answer:

    behind-the-scene http://hosts-file.net/ad_servers.txt other allow

Etc. (not sure about the request type, never notice what it was).

**Comment by luxoflux** [comment]
Yep, I know, and I've done that already (was an XHR).

Thanks.

**Comment by gorhill** [comment]
Actually I just realized [this pull request](https://github.com/gorhill/uBlock/pull/273) is what is causing this. There was a reason I picked the alternative name originally, and this the reason was to prevent ABP filters from matching the filter list. I will revert to the previous name.
