### ISSUE TITLE
inline-font classified as 'other'

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#3020]
I just picked up the latest changes (1.14.11) and now inline-fonts are being blocked with the rule `*$other`. I was on 1.13.8 prior to this and hadn't seen that before. 

STR: add that rule and refresh this page. There should be an inline-font block in the logger. Using Pale Moon 27.4

Should they be classified as 'font' type?

edit: that rule was added to block CSP reports. It's ham-fisted but until now hadn't had any side-effects that I'd seen. But I now removed it and added new specific rules targeting those reports on a few sites I'd seen them. That means no more inline-font blocks. But I still wonder if 'inline-font' should be classified as 'other'.

**Comment by gorhill** [comment]
Is it just on my side or GitHub no longer provide a link to the commit?

**Comment by gorhill** [comment]
Fixed with 2c4faaa84dc11a19a083e1f33e2961737cfe5e46.

**Comment by joey04** [comment]
Thanks for the quick fix. Verified I can safely restore `*$other`
