### ISSUE TITLE
[Firefox] Hidden tabs appears when middle-clicking (mousewheel-clicking) lists in "3rd-party filters" tab

### ISSUE THREAD

**Issue by gacelperfinian** [gorhill/uBlock#3023]
### Summary

When middle-clicking (mousewheel-clicking) lists in "3rd-party filters" tab (which does not apparently does not open) and closing all tabs in a window, hidden (not visible, but counted by Firefox) tabs are still present.

### Settings

- OS/version: Windows 10 Pro Creators Update (version 1703, build 15063.540
- Browser/version: Firefox 55.0.3
- uBlock Origin version: ~~1.14.4~~ Tested also on on 1.14.8, still exists.

##### Filter lists

It appears that the issue appears whenever the lists (and the settings overall) is in default (used when reproducing, see below) or modified (also verified on a heavily-loaded profile with lots of filters activated and custom user-specific filters added)

### One or more specific URLs where the issue occurs

None, it is an internal uBlock bug/defect.

### Steps to Reproduce

Note: Done on a clean-slate profile, but reproducible on my personal profile

1. Create a new profile (with the command `firefox -p` and follow the instructions on the screen) and open that profile
2. Open a new tab and access the special page `about:debugging` and access the `Tabs` tab (for monitoring purposes)
3. Install uB0, and access its dashboard and update the lists.
4. Middle-click any lists and check the `Tabs` list
  - *Expected:* Either the contents of the list is opened in a new tab (standard browsing behaviour) or nothing happens
  - *Actual:* New tabs are seen in the `Tabs` list but not displayed on the window (see Screenshot no. 4)
5. Close both tabs BUT do not use the universal close button (use the close button on the tabs themselves)
  - *Expected:* Window closes and Firefox exits
  - *Actual:* Window is still open without visible tabs (see Screenshot no. 5) and when closing, it requests to close X tabs (which is phantom, see Screenshot no. 6)

### Screenshots

![A Firefox window with the Add-ons store loaded withe the search term "uBlock" and a finished installation of "uBlock Origin"](https://user-images.githubusercontent.com/18494181/30511695-250840de-9b11-11e7-845e-d9fd6269f6ec.png)
Screenshot No. 1: Installation of uB0

![uBlock Dashboard open, updating lists](https://user-images.githubusercontent.com/18494181/30511717-aeb1a4a6-9b11-11e7-89b5-e37597338504.png)
Screenshot No. 2: Updating the list

![Filters are opened](https://user-images.githubusercontent.com/18494181/30511786-cd7f975c-9b12-11e7-8c83-d8ff66dcec09.png)
Screenshot No. 3: Filters were opened (some by left-click, which lefts the visible violet links, and some by middle-click)

![about:debugging window listing the phantom tabs](https://user-images.githubusercontent.com/18494181/30511809-683bf5ba-9b13-11e7-9a8a-6eaa4d33e8a1.png)
Screenshot No. 4: `about:debugging` window listing the phantom tabs

![All tabs closed, but Firefox is still open](https://user-images.githubusercontent.com/18494181/30511833-b2e24b14-9b13-11e7-9495-9a7d4afe5440.png)
Screenshot No. 5: All tabs were closed, however the window is left open.

![Do you want to close 14 phantom tabs?](https://user-images.githubusercontent.com/18494181/30511834-b2e7f26c-9b13-11e7-8f68-98aa737a54ae.png)
Screenshot No. 6: Closing the window asks if it should close phantom tabs.

**Comment by gorhill** [comment]
Browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1357589>.

Fixed in Nightly.

**Comment by gacelperfinian** [comment]
### UPDATE: Apparently, this is a browser bug.

Apparently, the Firefox's implementation of `target="_blank"` is broken.

In normal HTTP(S) pages, it is okay: see [this demonstration page](https://gacelperfinian.github.io/ub0-issue-3023/).

However, in extensions, it does not work. I also tested [Einar Egilsson's Redirector](http://www.einaregilsson.com/redirector/) by clicking into the help "button" (but in source it is an `<a>` link with that `target="_blank"`) and it also does **NOT** work.

You can close this now as a browser bug,
