### ISSUE TITLE
Regression "Temporarily allow large media elements"

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#3024]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Right click -> "Temporarily allow large media elements" no longer work

### One or more specific URLs where the issue occurs
https://www.dobreprogramy.pl/HP-ponownie-blokuje-nieoryginalne-kartridze-w-swoich-drukarkach,News,83144.html

### Screenshot in which the issue can be seen

![screenshot_20170916_132852](https://user-images.githubusercontent.com/886325/30511901-0687123a-9ae3-11e7-8798-e966b69fbf88.png)

![screenshot_20170916_135546](https://user-images.githubusercontent.com/886325/30512080-fd68d18a-9ae6-11e7-842a-082d2dc6a930.png)

### Steps for anyone to reproduce the issue

1. Default UBO settings + "Block media elements larger than" checked
2. Open https://www.dobreprogramy.pl/HP-ponownie-blokuje-nieoryginalne-kartridze-w-swoich-drukarkach,News,83144.html
3. Open UBO logger
4. Right click and select "Temporarily allow large media elements"
5. You can see in logger that UBO iterates over image elements, but not unblocks them

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Mint 18.2
- Browser/version: Firefox ESR or Nightly
- uBlock Origin version: good 1.14.10, bad 1.14.11b0

##### Your filter lists

Default

### Comment

Probably caused by this https://github.com/gorhill/uBlock/commit/5626b5005a5e6a09afed0cf4b5c9d25c685f56f7
Related https://github.com/gorhill/uBlock/issues/2946

**Comment by gorhill** [comment]
Fixed with 1e760f94299678c39b0e13ae2c98be0f6e573d16.
