### ISSUE TITLE
No popup rule not blocking popups

### ISSUE THREAD

**Issue by Martan404** [gorhill/uBlock#3027]
When visiting dreamfilmhd.sh the site always manages to sneak in popups that either overtake the current tab or open a new tab or sometimes even completely new windows even when I set the no-popup rule to true.
I've tried both of these addons and they prevents all popups on the site
https://addons.mozilla.org/sv-SE/firefox/addon/popup-blocker-ultimate/ (annoying to use, asks to allow on every single page you visit if aware mode)
https://addons.mozilla.org/sv-SE/firefox/addon/strict-pop-up-blocker/ (no white- or blacklist, disables all or nothing)

### One or more specific URLs where the issue occurs
https://dreamfilmhd.sh/ - whole site. 

### Steps for anyone to reproduce the issue
This happens randomly. Doesn't really matter what you click. Mostly it happens if you search for a video, then click on it to go to the movies page and then click on the video. That should grant at least 1 popup

### Your settings
- OS/version: Windows 10 - Latest
- Browser/version: Firefox 55.0.3
- uBlock Origin version: 1.14.8

##### Your custom filters (if any)
no-popups: dreamfilmhd.sh true

**Comment by mapx-** [comment]
```
dreamfilmhd.sh##script:inject(abort-on-property-read.js, _gunggo)
||onesignal.com^$script,domain=dreamfilmhd.sh
```

**Comment by gorhill** [comment]
The site is using popunder, not popup. The no-popup switch does not apply to popunders, because this would cause too many positive.

This is a filter list issue. The popunder does not happen with Adblock Ultimate because they make use of Adguard filter list, which blocks the site serving the popunder code:

    ||1app.blob.core.windows.net^$third-party

**Comment by gorhill** [comment]
Actually, looking at the files, it looks like Adblock Ultimate is mostly [Adguard](https://github.com/AdguardTeam/AdguardBrowserExtension) under the hood.

@ameshkov Did you know this?

**Comment by gorhill** [comment]
> I've tried both of these addons and they prevents all popups on the site
https://addons.mozilla.org/sv-SE/firefox/addon/popup-blocker-ultimate/

Ugh, I read "Adblocker Ultimate", you are talking about "Popup Blocker Ultimate". Yes, it works differently using the legacy API. uBO uses filter lists to do the job, and so far there is no blocking tab API to cancel tab opening. If ever this is added to WebExtensions, I will consider using it.

**Comment by ameshkov** [comment]
@gorhill I'll check it, thanks for the tip!

**Comment by gorhill** [comment]
What a scam. Here is the diff of one of the file, they changed nothing except for the header comment:

![a](https://user-images.githubusercontent.com/585534/30524154-4f0fb0dc-9bbc-11e7-8cdb-5461bf9e3ebb.png)

**Comment by ameshkov** [comment]
Huh, according to the [donations page](https://uploads.adguard.com/up04_dgwhu.png), it takes seven full-time soldiers to copy & paste the code.

**Comment by Martan404** [comment]
Is there anything that can be done against Adblocker Ultimate for doing this? Even if it's open source surely it can't be allowed to blatantly copy someone else work and just rename it? And from the looks of it, they haven't even touched their GitHub page since ripping Adguard off. 2 years since the last commit and the addon still gets updated on the firefox and chrome store. Doesn't that violate the license at least?
They seem to be making some nice money off it considering the video they have on the front page of their website.

**Comment by gorhill** [comment]
I've reported the extension using the "Report abuse"  button:

> This extension is essentially a copy of Adguard extension for the core code, and essentially a copy of ABP for the user interface aspect.
> 
> Whatever the legal aspect with regard to the GPL license, I find that allowing such scammy extension on AMO to be detrimental to developers who do the actual genuine work, and detrimental to AMO by allowing in its repo such parasitical extensions with no actual added value versus the original (actually the opposite given how limited the UI is versus that of Adguard)
> 
> Surely users willing to donate to developers would be better served if they were not deceived into donating to scammers/opportunists.
