### ISSUE TITLE
Newly added 3rd-party filter does not get removed from Custom Group

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#3028]
### Describe the issue
After `Adguard’s Annoyance List` was added to Social group, it is still present in Custom group.
Both have the same url `https://filters.adtidy.org/extension/ublock/filters/14.txt`

### Steps for anyone to reproduce the issue

1. Have assets version which does not contain `Adguard’s Annoyance List` yet (for example, from newly installed uBlock Origin in Chrome) and add `https://filters.adtidy.org/extension/ublock/filters/14.txt` to Custom group.
1. Update assets to version which contain `Adguard’s Annoyance List` (Purge all caches + Update now)
1. Filter list is present in both Social group (`Adguard’s Annoyance List`, disabled) and Custom group (`Annoyances filter`, enabled).
1. Remove `Annoyances filter` from Custom group
1. Add `https://filters.adtidy.org/extension/ublock/filters/14.txt` to Custom group
1. Now `Adguard’s Annoyance List` toggles to enabled in Social group.

### Your settings

- OS/version: Windows 10 x64 v1607 (14393.1715)
- Browser/version: 61.0.3163.91 (Official Build) (64-bit)
- uBlock Origin version: 1.14.8

##### Your filter lists
```
  "selectedFilterLists": [
    "https://filters.adtidy.org/extension/ublock/filters/14.txt",
    "plowe-0",
    "malware-1",
    "malware-0",
    "easyprivacy",
    "easylist",
    "ublock-unbreak",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
  ],
```

**Comment by gorhill** [comment]
> it is still present in Custom group.
> Both have the same url https://filters.adtidy.org/extension/ublock/filters/14.txt

They don't have the same token id however, `adguard-annoyance` vs `https://filters.adtidy.org/extension/ublock/filters/14.txt`.

You will have to remove the one in custom manually, uBO won't do this for you. It merely tries to resolve to a stock list at import time.
