### ISSUE TITLE
[Vivaldi] UI Broken with Vivaldi chromium browser

### ISSUE THREAD

**Issue by PowerAccess** [gorhill/uBlock#3030]
Clicking Apply Changes, Import, etc. in Dashboard (Settings) as well as Element Picker, etc. for drop-down panel all fail to do anthing with latest Vivaldi Chromium browser (1.11.917.43 (Stable channel) (64-bit) with latest uBlock Origin (1.14.8) for Windows 10 x64.
This same version work fine with latest Google Chrome browser however.

Please fix so works with other Chromium-based browsers besides Google Chrome.

**Comment by PowerAccess** [comment]
However, there is one issue that also occurs with latest Google Chrome (latest stable) too:
Export button for custom filters fails with Chrome to show any save file dialog, though Import and Apply Changes work.

**Comment by okiehsch** [comment]
> Export button for custom filters fails with Chrome to show any save file dialog

Works on my end.
![unbannt](https://user-images.githubusercontent.com/16838044/30527376-39e569e2-9c28-11e7-8a98-a68ac5352529.PNG)

**Comment by gorhill** [comment]
I don't support Vivaldi, someone else will have to come forward and volunteer for issues affecting specifically Vivaldi.

There is no issue with Chrome -- there is a setting in advanced setting, _"Ask where to save each file before downloading"_ which can be toggle to force the file dialog to show.

**Comment by anewuser** [comment]
Issues should be reported directly to the Vivaldi developers.

>Because Vivaldi is built using the Chromium web browser project, extensions available in the Chrome Web Store can also be installed in Vivaldi. In some instances, extensions built for the Chrome browser will behave differently when installed in Vivaldi, but for the most part your favourite Chrome extensions will work just fine in Vivaldi.

>If an extension does not work as expected, please let us know by emailing the Vivaldi support team using the contact form on our website.

https://help.vivaldi.com/article/extensions/

https://vivaldi.com/contact/

https://vivaldi.com/bugreport
