### ISSUE TITLE
Firefox Android (nightly 57) popup scrolling

### ISSUE THREAD

**Issue by ojz0r** [gorhill/uBlock#3032]
### Describe the issue
I have previously reported (#2274) a bug that you fixed that the scrolling did not work in landscape for android. You fixed it quick last time but now it has returned when im testing the nightly builds.

### Steps for anyone to reproduce the issue

Please see bug  #2274.

### Your settings

- Browser/version: Firefox Android (nightly  57.0a1)
- uBlock Origin version:  1.14.8

**Comment by gorhill** [comment]
Please report to Firefox devs. There has been no change in the popup panel code, and it still work fine in Fennec 55 and used to work fine in Nightly until recently, hence this means the issue is with Nightly. Using Chrome's mobile device debugger shows that there too uBO's popup panel works fine.

**Comment by gorhill** [comment]
Hmm, wait a bit, I just noticed that the `mobile=1` is not part of the URL. Investigating.

**Comment by gorhill** [comment]
I suspect this might be related to #2908. Something changed in Nightly which seems to cause my `browserAction.onClicked` handler to no longer be call. That handler was opening the popup panel with the `mobile=1` parameter, but now it seems Nightly is opening the panel itself, bypassing the handler.
