### ISSUE TITLE
[Bug] Some filter not works

### ISSUE THREAD

**Issue by hawkeye116477** [gorhill/uBlock#3034]
### Describe the issue

This filter not works on uBlock Origin 1.14+ -> `@@||*/wp-content/plugins/cookie-law-info/js/cookielawinfo.js$script`. On 1.13.10 it works, so I assume that this is a bug of uBlock 1.14+.

### One or more specific URLs where the issue occurs

http://meizupolska.pl/
www.mmarocks.pl

### Screenshot in which the issue can be seen

![screenshot_20170918_172719](https://user-images.githubusercontent.com/19818572/30550136-daa4fdfc-9c96-11e7-8b8e-d8a453b79770.png)

### Steps for anyone to reproduce the issue

1. Subscribe this filter -> `https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt`
2. Go to one of the URL's.
3. You can see on uBlock logger that script cookielawinfo.js is blocked despite being whitelist given.

### Your settings

- OS/version: Manjaro Linux 17.04
- Browser/version: Waterfox 55.0.2
- uBlock Origin version: 1.14.8

##### Your filter lists

All uBlock filters (except experimental)+Adblock warning removal list+EasyList+AAK Cont+EasyPrivacy+Malware domains+Fanboy's Social+Peter Lowe’s Ad and tracking server list​​​​​+all Polish lists from https://www.certyficate.it/adblock/ except AlleBlock.

**Comment by gorhill** [comment]
Sure, I can fix this, but really, why the leading `||*`? This accomplish absolutely nothing.

**Comment by hawkeye116477** [comment]
@gorhill Ok, my bad. Not it works, when I removed `||*` . Thanks and sorry for the trouble.

**Comment by gorhill** [comment]
I will fix it, but really I didn't expect this to occur. In general avoiding `*` is good, as this will cause fast plain string comparison internally. As soon as there is a `*`, a regex must be used.

**Comment by gorhill** [comment]
The chosen solution is that uBO will internally normalize filters with leading/trailing asterisks:

- `||*abc...` or `|*abc...` => `abc...`
- `...xyz*|` => `...xyz`

So that in the end the fast plain string comparison can be used.

**Comment by gwarser** [comment]
Should not `||*/abc` match only on the beginning of the path?
`||` domain anchored, `*` any domain (not "any string"), `/abc` path.

**Comment by gorhill** [comment]
> `*` any domain (not "any string")

That would be sensible behavior when `||` is involved, but as far as I am aware, there is no ABP documentation for this behavior.
