### ISSUE TITLE
uBlock Origin breaks the sign in button on https://thewalrus.ca/

### ISSUE THREAD

**Issue by jrmuizel** [gorhill/uBlock#3035]
There's some investigation into the issue here: https://github.com/webcompat/web-bugs/issues/9992#issuecomment-330331574

### One or more specific URLs where the issue occurs

thewalrus.ca

### Steps for anyone to reproduce the issue

1. Turn on uBlock Origin in the default configuration
2. Click "Sign In" on thewalrus.ca
3. Nothing happens (without uBlock Origin a sign in pop-up appears)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: MacOS
- Browser/version: Firefox Nightly 57/Chrome 63
- uBlock Origin version: 1.14.8

##### Your filter lists

Default filter lists.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> There's some investigation into the issue here: webcompat/web-bugs#9992 (comment)

Logger shows this is a filter issue: EasyList's `/dfpload.js` blocks `https://thewalrus.ca/wp-content/plugins/paxdfp/dfpload.js`, while the javascript code of the site assumes this can never ever happens.
