### ISSUE TITLE
Cannot inspect inside iframes with logger inspector

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uBlock#3036]
### Describe the issue
It is not possible to determine which cosmetic filter(s) are hiding a specific element inside an iframe.  The logger inspector appears to have no way to inspect the contents of iframes.

### Screenshot in which the issue can be seen

![ublock-origin-iframe-problem](https://user-images.githubusercontent.com/16628411/42057695-28aba06c-7aec-11e8-8cd6-02de47b5321e.png)

### Steps for anyone to reproduce the issue

1) Dashboard > My Filters, add this filter -
```
###goButton
```
2) Open the logger
3) Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Example1 .  Notice that the button inside the iframe is hidden.
4) Go back to the logger, and open the logger inspector and try to find the hidden button.

(Some related discussion on mozillaZine: http://forums.mozillazine.org/viewtopic.php?p=14766503#p14766503 )

### Your settings

- Browser/version: Firefox 55.0.3 or SeaMonkey 2.49.1, new profile
- uBlock Origin version: 1.14.11b2 (legacy).  Also happens with uBO/webext 1.14.11b2 in Firefox.

##### Your filter lists

default

##### Your custom filters (if any)
see steps-to-reproduce

**Comment by uBlock-user** [comment]
@gorhill This should also be closed after the implementation of https://github.com/gorhill/uBlock/commit/db7f54dbf6c39cf2e6f35359248bf9f408e2d134

**Comment by gorhill** [comment]
This represents a huge amount of work, beneficial for few people who care digging that far in the logger's features. Workaround is to open the frame in its own tab. For those with the urge to answer that not all iframe can be opened in a tab, I agree and in such case I invite them to fork and further develop the requested feature here, then I will consider importing their work into uBO.
