### ISSUE TITLE
Logger always highlights first match

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#3037]
The first match is almost always the actual match, but sometimes it's not.

I saw it again [here](http://www.icepop.com/favorite-90s-stars-now) with this plain string rule that's word-boundary enforced by default:
![1](https://user-images.githubusercontent.com/14959062/30570166-6e4e6ba4-9cad-11e7-95b2-1582c37cc96c.png)

(Another case for me is #3011, but that requires the change I made to enforce word-boundary for > 7 char tokens.)

<hr>

update:

I wrote [this addition](https://github.com/joey04/xulBlock-Advanced/blob/master/src/js/logger-ui.js#L140-L155), which finds the actual match for every case I've come across.

(I've since refined my patch to be a do-while(1) loop with a single null test, still using the exact same regex statements. Functionally, this just saves a few CPU cycles, but it's a nice aesthetic improvement.)

**Comment by joey04** [comment]
Since I added scriplet logging I thought I'd tackle this one too.

[This is the patch](https://github.com/gorhill/uBlock/files/1316104/diff.txt).

That was a tricky regex to get just right. I tried to make it robust (even more cases than I use) so that it could potentially be used with EasyList and other big lists. But I haven't tested it beyond my own small rule set.

Now the logger matches the word boundary I added to #3011 

![1](https://user-images.githubusercontent.com/14959062/30619390-216ebf3a-9d6d-11e7-8427-38e0eef96c47.png)

(The clickbait link above doesn't have that particular tracker today so couldn't verify it there, but I'm confident the next Prefix1 like that will be logged properly when I come across it.)

**Comment by joey04** [comment]
Closing per https://github.com/gorhill/uBlock/issues/3011#issuecomment-415983637

**Comment by gorhill** [comment]
I thinks its best that the logger shows the real match which occurred inside uBO.

**Comment by joey04** [comment]
I agree, but are there any other cases besides the prefix1's I reported? If not, then it's a niche consideration like #3011.

**Comment by gorhill** [comment]
I couldn't reproduce with the original URL provided, however I could reproduce and verify the fix using those hand-crafted URL/filter pairs:

- `http://example.org/1s.crazyclickstats.com/1/?` with `/1`
- `http://example.org/123456s.crazyclickstats.com/123456/?` with `/123456`
- `http://example.org/1234567s.crazyclickstats.com/1234567/?` with `/1234567`
