### ISSUE TITLE
SlowMo UI 

### ISSUE THREAD

**Issue by publicarray** [gorhill/uBlock#3038]
### Describe the issue

In FF Nightly and uBO 1.14.11b2 the Dynamic filtering panel opens in slow motion. (Is this a bug or a feature 😜 ) could also be a ff nightly bug

![ublock](https://user-images.githubusercontent.com/5497998/30598320-bd563f34-9d9c-11e7-876f-68d798b3b23c.gif)

### Your settings

Ticked "I am an advanced user", medium mode.

- OS/version: macOS 10.12.6 
- Browser/version: Firefox Nightly - 57.0a1 (2017-09-19) (64-bit)
- uBlock Origin version: 1.14.11b2

**Comment by gorhill** [comment]
I can't reproduce. Is this the webext version of uBO?

There was the fix to #3032, which was to add screen-size based heuristic to decide whether the popup panel must fill the whole viewport or not. Your screen size is obviously larger than the popup viewport. Did you toggle any settings in Firefox which could impede access to `window.screen.availWidth` or `window.screen.availHeight`?

**Comment by gorhill** [comment]
Ok, I can reproduce with `privacy.resistFingerprinting` set to `true`.

**Comment by publicarray** [comment]
Ah yes I am using https://github.com/ghacksuserjs/ghacks-user.js which also sets these prefs:

```js
/* 4501: enable privacy.resistFingerprinting (FF41+)
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=418986 ***/
user_pref("privacy.resistFingerprinting", true); // (hidden pref) (not hidden FF55+)
/* 4502: set new window sizes to round to hundreds (FF55+) [SETUP]
 * [NOTE] Width will round down to multiples of 200s and height to 100s, to fit your screen.
 * The override values are a starting point to round from if you want some control
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1330882
 * [2] https://hardware.metrics.mozilla.com/ ***/
user_pref("privacy.window.maxInnerWidth", 1600); // (hidden pref)
user_pref("privacy.window.maxInnerHeight", 900); // (hidden pref)
```

**Comment by gorhill** [comment]
All of these cascading issues is because `browserAction.onClicked` stopped being called on Firefox for Android -- no clue whether by design.

**Comment by publicarray** [comment]
Thanks for the speedy fix 😄
