### ISSUE TITLE
problem after edit "my filters"

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#304]
after edit "my filters", element hide not working any more.
i must create all element hide from beginning

**Comment by gorhill** [comment]
You probably have syntax errors in your edited filters. Share them here if you do not mind, to confirm whether there are errors.

**Comment by androidland** [comment]
first I also thought like that, then i restore my filters back up, but It's still not working

**Comment by gorhill** [comment]
I can't help you if you do not share all the details which will allow me to help you. Given how stable uBlock is currently, the likelihood is that there is something specific on your side causing thos, it can be many things, and the better you spell out in details what are the symptoms exactly, with URL, filters etc., the  easier it will be for me to help you.

**Help me help you.** See <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

**Comment by androidland** [comment]
i have create new firefox profile and clean instal ublock. the problem is finished, thanks any way
