### ISSUE TITLE
Can't extract package in tmp folder on manjaro 17.0.5 and chromuim 61.0.3163.91 x64bit

### ISSUE THREAD

**Issue by zor1984qq** [gorhill/uBlock#3040]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Can't extract package in tmp folder on manjaro 17.0.5 and chromuim 61.0.3163.91 x64bit
Other package called "ublock origin extra" are installed normally.
Please fix these in 14.4>till your hourly beta release.
According to some posts on reddit it has been an issue for many people since 3 last month.
I tried to extract latest beta 14.4 release and install it in developer mode but no luck it wont work at all with lastest version of my browser. Luckily I have other browsers works with that.

And btw why did "extra" package availible only in Crhomium web store? I didn't see it anywhere else as a project despite "matrix" existence but it more like noscript or something that just need manual setup.

PPS the extracted beta package dated 1 hour ago release is installed properly and working ver. uBlock Origin v1.14.11.3

Thanks.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
