### ISSUE TITLE
Often a warning because uBlock about CSP (content security policy) conflict in Chrome

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#3041]
Hello

I had switched from Firefox to Chrome. Now I have often a warning because uBlock about CSP (content security policy) conflict.

![ubo_csp-problem](https://user-images.githubusercontent.com/11355601/30620338-08f3e146-9da5-11e7-863e-1a6d41dbec25.JPG)

I can't deliver a certain URL or exact steps (till now) to reproduce ...

- OS/version: Windows 10 [Version 10.0.15063]
- Browser/version: Chrome 62.0.3202.18 Beta x64
- uBlock Origin version: 1.14.11b3 (with uBlock Extra 2.51 and uMatrix 1.0.1rc1)

I have no filter lists selected with pure domains, to avoid problems with uMatrix (because I know, that Chrome cannot make (such) simulteaneous requests of multiple PlugIns at the same time, so I use uMatrix for domain things).

Is this behaviour normal (now) and can I just ignore this?

Greetings

PS: The error appears in uMatrix, however: uBlock produces it, so I report it here ...

**Comment by gorhill** [comment]
Duplicate of #1170.
