### ISSUE TITLE
uBlock CDN? 

### ISSUE THREAD

**Issue by bojanstef** [gorhill/uBlock#3043]
This might be a weird question but nevertheless: is it possible to include uBlock on your own website? If I could add some type of `ublock.js` CDN to my `head.html` that would be great. The use case is: 

- Fullscreen website playlist of all uploads from my Youtube channel
- [OBS](https://github.com/jp9000/OBS) capture the website source
- CDN include in head of my website to remove ads 
- Loop playlist on Facebook video

Not sure if this is possible, if anyone knows some hack I could do, it would be much appreciated. 
Thank you

**Comment by gorhill** [comment]
I don't understand what you are asking. There is no web site associated with this project -- as stated in the [privacy policy](https://github.com/gorhill/uBlock/wiki/Privacy-policy):

> uBlock Origin has no home server.

**Comment by gorhill** [comment]
Anyways, closing as this sounds like a request, not an issue with uBO.

**Comment by Atavic** [comment]
Bojan: You can't! A browser addon isn't a script.
