### ISSUE TITLE
Cannot enable add-on after disabling it via about:addons

### ISSUE THREAD

**Issue by Matthewus** [gorhill/uBlock#3048]
### Describe the issue
Cannot enable add-on after disabling it via about:addons

### One or more specific URLs where the issue occurs
about:addons

### Screenshot in which the issue can be seen
Browser console:
![ublock](https://user-images.githubusercontent.com/9383850/30771404-7d350608-a047-11e7-8a2e-10e5d402e073.png)

### Steps for anyone to reproduce the issue
Disable the add-on via about:addons

### Your settings
- Advanced user

- OS/version: Windows 10 64 bit
- Browser/version: Firefox 55.0.3 64 bit 
- uBlock Origin version: 1.14.10

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
