### ISSUE TITLE
uBlock crashes after clicking the badge

### ISSUE THREAD

**Issue by dudamoos** [gorhill/uBlock#305]
To reproduce:
Click on the uBlock badge to view the page statistics or mange dynamic filtering. It happens everywhere, but this particular time it happened at https://www.youtube.com/watch?v=60FCdesFgRw

Rather than loading the uBlock popup, the extension will crash after a few seconds. This happens every time I click the badge. I started happening between when I got the extension at version 0.9.6 and before the update to 0.9.7 I think. This happens even after removing and reinstalling the extension and clicking the button to reset to default settings. Disabling all other extensions doesn't help.

I am currently using the most recent version of uBlock Origin (0.9.8.3) on the most recent version of Chrome (43) x64 for Windows 7. In addition to uBlock I am using Ghostery, HTTPS Everywhere, Keep MORE Opt-Outs (from Privacy Choice), and Application Launcher for Drive (by Google). All of these except the last are additionally allowed to run in Incognito. I have a few other extensions but I've had all but those listed above disabled for a few months now.

I've tried watching the Javascript console for the background page and the tab itself when the crash occurs, but nothing gets logged to the tab's console and the background page's console closes (due to the crash) before anything gets logged.

**Comment by gorhill** [comment]
You need to report this to Chromium devs: <https://code.google.com/p/chromium/issues/list>.

Javascript code is not supposed to cause a browser to crash. If it happens, there is an issue with the browser. You can submit a crash report in Chrome, this will help Chromium developers in tracking down the reason for the crash.

Launching the browser from the console may provide some hints *maybe*, as the browser will report stuff as it crashes.

**Comment by dudamoos** [comment]
It's not the browser that's crashing, just the extension. Is that still something I should report to the chrome devs?

**Comment by 5t3f4n** [comment]
Does it also happen with the [latest version](https://github.com/gorhill/uBlock/releases) ([0.9.8.6](https://github.com/gorhill/uBlock/releases/tag/0.9.8.6)) ?

**Comment by 5t3f4n** [comment]
Does it also happen with the [latest version](https://github.com/gorhill/uBlock/releases) ([0.9.8.6](https://github.com/gorhill/uBlock/releases/tag/0.9.8.6)) ?

**Comment by dudamoos** [comment]
It still happens with the latest version from Github. Is there a good way to get logging from uBlock? I can't find a way to see console output from the extension.

**Comment by gorhill** [comment]
> It's not the browser that's crashing, just the extension. Is that still something I should report to the chrome devs?

Extensions and tabs execute each in their own thread. When an extension crashes (the bubble), it's the thread in which it runs which crashes, and given the per-process architecture of Chromium, the browser is left unscathed by that specific thread crash. A tab or extension crash is really something to be submitted to the Chromium devs, it's not supposed to crash.

**Comment by gorhill** [comment]
> Is there a good way to get logging from uBlock?

If uBlock's thread crashes, this will bring down its dev console as well. As said, try launching the browser from the command line, maybe it will provide a hint of where the crash occurs. But even then, Chromium devs are best to deal with this -- crashing while executing javascript is a browser bug.

**Comment by dudamoos** [comment]
@gorhil There's already a ticket in the chrome bug tracker here:
https://code.google.com/p/chromium/issues/detail?id=404687&can=1&q=uBlock%20crash&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

Should I continue that ticket or make a new one? Additionally, the crash reporter at chrome://crashes doesn't seem to have picked up on the extension crash.

**Comment by gorhill** [comment]
> There's already a ticket in the chrome bug tracker here

Yes, I opened this one myself, https://github.com/chrisaljoudi/uBlock/issues/159.

If the output at the command line is similar, I suppose it should be reported in the same bug.

Did you try running uBlock alone, without all the other extensions?

**Comment by dudamoos** [comment]
I tried disabling the other extensions and it didn't help. Also, when I ran chrome at the command line it backgrounded itself and didn't log anything. Is there a way to keep it from doing that?

**Comment by gorhill** [comment]
> Is there a way to keep it from doing that?

I don't know about Windows, somebody else might know about this.

**Comment by TjWallas** [comment]
I can confirm this behavior using the latest chromium from the Ubuntu 14.04 repositories under the following environment specs:
```
Chromium	43.0.2357.81 (Developer Build) Ubuntu 14.04 (64-bit)
Revision	        4d096306deb9e86953c81f08454dd6db07b406b5
OS	                Linux 
Blink	                537.36 (@195776)
JavaScript	V8 4.3.61.23
Command Line	/usr/lib/chromium-browser/chromium-browser --enable-pinch --ppapi-flash-path=/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so --ppapi-flash-version=14.0.0.177 --flag-switches-begin --disallow-autofill-sync-credential --debug-packed-apps --disable-device-discovery-notifications --no-pings --disable-ntp-other-sessions-menu --disable-account-consistency --enable-deferred-image-decoding --enable-devtools-experiments --enable-download-resumption --enable-drop-sync-credential --disable-experimental-app-list --enable-fast-unload --disable-fill-on-account-select --disable-offer-store-unmasked-wallet-cards --enable-offline-auto-reload-visible-only --enable-offline-auto-reload --disable-password-generation --disable-password-link --disable-pinch-virtual-viewport --disable-pinch --enable-stale-while-revalidate --disable-sync-app-list --enable-tcp-fastopen --enable-website-settings-manager --extension-content-verification=enforce --enable-lcd-text --disable-overlay-scrollbar --overscroll-history-navigation=0 --reduced-referrer-granularity --save-page-as-mhtml --touch-events=disabled --flag-switches-end
```

```
uBlock Origin v0.9.8.6
```

Usually, I have ublock side by side with:
* Privacy badger: https://www.eff.org/privacybadger
* uMatrix: Configured so as not to overlap with the blocking list in uBlock Origin

However even after disabling all privacy-related extensions, the problem persists. Any help how I could get more meaningful output why the extension crashes?

**Comment by gorhill** [comment]
> Any help how I could get more meaningful output why the extension crashes?

You setup is quite similar to mine except Linux Mint instead of Ubuntu. So a plainly cut and pasted the whole command line into my console and went on to test, including with Privacy Badger and I could not reproduce the issue.

If you launch from a terminal, is there anything dumped in it when it crashed? If so, you should add this information to the related Chromium issue.

**Comment by TjWallas** [comment]
I fiddled with a few settings with both: uBlock and uMatrix and now, uBlock no longer crashes when its badge is clicked. Not sure exactly what resolved the problem but, I suspect it was the "disable hyperlink auditing" filter. It was turned on in both extensions. It should be enabled in only one of them.

**Comment by dudamoos** [comment]
It was crashing for me before that option was added, but I tried that and it still crashed. I'm also not using uMatrix, so that shouldn't be an issue anyways. Still no response from the Google people when asked if I should continue the issue @gorhill opened or open a new one. Given that I can't tell what the cause of the issue is, should I just open a new chromium issue and let them sort it out?

**Comment by gorhill** [comment]
> should I just open a new chromium issue and let them sort it out?

The key is to provide information. A crash report, or like I did in the original bug the output at the console when it crashes. Without useful information just reporting that something crash is not going to help if they can't reproduce it.

**Comment by dudamoos** [comment]
Finally got what looks like a crash report from it. Hopefully they get something out of it.

**Comment by dudamoos** [comment]
Opened up a new issue via the crash reporter: https://code.google.com/p/chromium/issues/detail?id=500789

**Comment by gorhill** [comment]
@dudamoos 

A user reported a similar crash on reddit: <https://www.reddit.com/r/ublock/comments/3a38qe/crash_on_reddit_linked_to_ad_injection/>.

It does look to me this user is afflicted by some adware/malware, `static.chromenotice.com`.

I think you should look on your side for something like this. Plugging "static.chromenotice.com" in a search engine, with quotes, returns worrying results.

**Comment by dudamoos** [comment]
I've checked and the only program on that list I have installed is Adobe AIR because some of the Lenovo system tools that shipped with my computer use it. I also have up to date antivirus which has not detected anything wrong (though I have it running yet another full system scan right now just to make sure).
