### ISSUE TITLE
Where is version 1.13.8 in version history Mozilla Addons

### ISSUE THREAD

**Issue by NigNog9001** [gorhill/uBlock#3050]
I wanted to install 1.13.8 because >1.13.9 breaks everything 
It was there before, now it's gone. What happened?

**Comment by Betsy25** [comment]
It is there. https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=1#version-1.13.8

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
