### ISSUE TITLE
Can't update filters in Firefox (Windows, FreeBSD and MacOS)

### ISSUE THREAD

**Issue by jasoncook** [gorhill/uBlock#3051]
### 
![image](https://user-images.githubusercontent.com/4571376/30831027-146c60fe-a1ea-11e7-9638-1e3bb90b762c.png)

### Steps for anyone to reproduce the issue:

1. Open the uBlock Dashboad
1. Click on the 3rd-party filters dashboard
1. Click the "Update Now" button

### My settings

- OS/version: FreeBSD 11.1-RELEASE-p1 **AND** Windows Server 2012 R2 **AND MAC OS 10.12.6
- Browser/version: 55.0.3 (64-bit **AND** 32-bit)
- uBlock Origin version: 1.14.10
- Multiple Networks Tested: Comcast, Centurylink, AT&T

##### Your filter lists

Default Filter Lists

**Comment by gwarser** [comment]
Any other extensions?

**Comment by banther7** [comment]
Unable to update here too but the older version 1.13.8 updates fine, also AAK-cont isnt a filter for mine.

**Comment by gwarser** [comment]
Add `matrix-off: moz-extension-scheme true` to uMatrix (Dashboard -> My filters) or whitelist `moz-extension://` scheme in any other content blocking extension.

**Comment by banther7** [comment]
@gwarser i dont think i can do that with no-script

**Comment by gwarser** [comment]
>do that with no-script

Then just read [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.10)

**Comment by gorhill** [comment]
Network errors are cause by something on your side, you will have to investigate what is blocking uBO's network requests,I can't do this for you.
