### ISSUE TITLE
Query about Kaspersky Script

### ISSUE THREAD

**Issue by Fernandolor** [gorhill/uBlock#3052]
Hi..

Kaspersky Internet Security injects a web page interaction script into web traffic. This script ensures the operation of such components as Safe Money, Private Browsing, Parental Control, Anti-Banner, URL Advisor, and Secure Data Input.

[https://help.kaspersky.com/KIS/2017/en-EN/68219.htm](url)

**kaspersky-labs.com**
**gc.kis.v2.scr.kaspersky-labs.com**

Why ublock block these?

Thx for your help

+
Win 8.1 (64 bits)
Chrome Versión 61.0.3163.100 (Build oficial) (64 bits)
uBlock Origin v1.14.8
All settings are default in Unblock / i dont make any change
Default filter lists

![ublock](https://user-images.githubusercontent.com/32278339/30831855-483fc7f6-a206-11e7-97ef-934a58d96264.JPG)
![webtraffic](https://user-images.githubusercontent.com/32278339/30831567-1c14d2a8-a205-11e7-9b09-e1a48a575780.JPG)](url)

**Comment by gwarser** [comment]
Why you think it's blocked? Row is green, with "+" - no blocking.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
