### ISSUE TITLE
Popunders are not blocked

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#3053]
### Describe the issue

Since version 1.14.11b4 popunder are not blocked/closed. Last working version is 1.14.10. Probably caused by this change https://github.com/gorhill/uBlock/commit/2660bee0d20e8355380b1b8c64973601514526cd

### One or more specific URLs where the issue occurs

`http://raymondhill.net/ublock/popup.html`

### Steps for anyone to reproduce the issue

1. Go to url
1. Wait 10s
1. Test popunder (13.)

### Your settings

- Browser/version: Firefox 58.0a1 (2017-09-25) (64-bit)
- uBlock Origin version: 1.14.11rc0

##### Your custom filters

`||example.com/AdHandler.aspx?$popunder`

**Comment by kasper93** [comment]
@gorhill: It is better, but while testing I noticed slightly harder to reproduce issue. Probably no longer related to original issue.

1. Open browser
2. Load test page - everything should work at this point
3. Open uBlock Dashboard in new tab
4. Go back to tab with test page
5. Try again. It will fail to close popunder.

Interesting thing is that, it will keep only one pounder open and close next ones,  but if I manually close the first tab with popunder, on next try it will be reopened.

Let me know if you can reproduce.

**Comment by gorhill** [comment]
I could reproduce.

The issue is with Firefox only, all works fine with Chromium.

Upon investigation, I find that with the case at hand, the callback to Firefox's [`webNavigation.onCreatedNavigationTarget`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/onCreatedNavigationTarget) is being called with the `sourceTabId` property set to `-1`, meaning there was no opener for the new tab, while it definitely is not the case.

So yes, this is unrelated to the regression fixed here, this is a Firefox-specific bug.

**Comment by gorhill** [comment]
By the way, it seems opening uBO's dashboard is key to reproduce the issue. When uBO's dashboard is opened, I see this error being reported at the browser console:

    [Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://browser/content/ext-tabs.js :: query :: line 482"  data: no]  (unknown)
        query chrome://browser/content/ext-tabs.js:482:29
        InterpretGeneratorResume self-hosted:1272:8
        next self-hosted:1179:9
        query self-hosted:943:17
        call resource://gre/modules/ExtensionParent.jsm:617:24
        next self-hosted:1179:9

So I suspect the error above leaves Firefox's internals in a bad state, leading to the broken `webNavigation.onCreatedNavigationTarget`.

**Comment by gorhill** [comment]
@kasper93 Can you report to bugzilla.mozilla.org?

**Comment by gorhill** [comment]
@Rob--W I don't know what to make of this -- picture below is browser toolbox debugger with "Pause on all exceptions" enabled. This occurs by clicking the dashboard icon in uBO's popup panel. As a result of clicking that icon, this is the code being called in uBO (and failing with an exception in browser API code):

https://github.com/gorhill/uBlock/blob/b1f04c79b024a993bd77a2ff222c6c1481c24f55/platform/chromium/vapi-background.js#L482

Where `targetURLWithoutHash` is the URL for uBO's dashboard, `moz-extension://[extension id]/dashboard.html`.

![a](https://user-images.githubusercontent.com/585534/30872466-2c3a9010-a2b8-11e7-8e62-bc850037d19b.png)

![b](https://user-images.githubusercontent.com/585534/30872459-24e8dc0e-a2b8-11e7-8fa5-12151b2747f7.png)

**Comment by Rob--W** [comment]
@gorhill `moz-extension:`-URLs are only supported in Firefox 56 and later (https://bugzilla.mozilla.org/show_bug.cgi?id=1271354). That's probably why `tabs.query` fails.

Did I answer all of your questions, or should I also take a look at the comments before your last comment?

**Comment by gorhill** [comment]
Thanks, this answers my question.

**Comment by gorhill** [comment]
@Rob--W Just in case this may be an issue that affects more than just uBO, I finally narrowed the issue reported above in #3057. Summarily, Firefox's `webNavigation.onCreatedNavigationTarget` seems to be broken for good after one open uBO's dashboard through its popup panel. This also occurs in Nightly.
