### ISSUE TITLE
GreaseMonkey + Ublock = pages no loading

### ISSUE THREAD

**Issue by Owyn** [gorhill/uBlock#3055]
### Describe the issue
https://github.com/greasemonkey/greasemonkey/issues/2524
https://github.com/greasemonkey/greasemonkey/issues/2583

I reported it to GM first but it seems to be Ublock's fault

### Steps for anyone to reproduce the issue

1. Have FF 55, GM 3.13, uB origin 1.14.10, Windows 10
2. Have any GM userscript to run @ document-start
3. Open any page - see it failed loading

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You failed to read the release notes.
