### ISSUE TITLE
Filters Not Updating Properly

### ISSUE THREAD

**Issue by kingphantom** [gorhill/uBlock#3056]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
--> When opening FireFox, the filter lists become outdated every time. The Filters fail to work until updated again every time you open FireFox.

--> I've removed all extensions and even re-installed ublock from default. Issue remains the same. Filters fail to remain updated.

### One or more specific URLs where the issue occurs
[URL(s) for issue on a specific site are **mandatory**]

--> This issue occurs on most if not all sites the filters apply to because they become outdated in ublock on opening of FireFox.

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

--> To reproduce this issue, just update your filters, close FireFox, open FireFox again, and view the third party lists. They immediately become outdated, even though you just updated them. This will happen over and over.

I find this to be less on the lists but more on ublock since ublock is failing to hold the lists as updated.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

-->Disabled "Hide placeholders of blocked elements"

--> Activated "Prevent WebRTC from leaking local IP addresses"

--> Disabled "Auto-update filter lists"

- OS/version: Windows 7
- Browser/version: FireFox Dev 56 (64 bit)
- uBlock Origin version: 1.14.10

##### Your filter lists
--> "My Filters" No data here. No custom filters.
--> "ublock filters"
--> "ublock filters - Badware Risks"
--> "ublock filters - Privacy"
--> "uBlock filters – Unbreak"
--> "Adblock Warning Removal List"
--> "Malware domains"
--> "Spam404"
--> "Fanboy+Easylist-Merged Ultimate List"
--> "Peter Lowe’s Ad and tracking server list"

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
--> None

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/issues/2925#issuecomment-325968653>.
