### ISSUE TITLE
Popup/popunder blocking broken after opening uBO's dashboard through popup panel

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#3057]
First reported [here](https://github.com/gorhill/uBlock/issues/3053#issuecomment-332215533) by @kasper93.

This is unrelated to the regression, which was fixed.

This affects all versions of Firefox, including in Nightly.

The repro steps are quite simple (from my end, both with Firefox 55 and Nightly):

1. Launch browser.
2. Open [popup test page](http://raymondhill.net/ublock/popup.html) in a new tab.
3. Verify that the popup from the first test ("direct url tab") is properly blocked.
    - uBO's popup blocking depends on `webNavigation.onCreatedNavigationTarget` to properly set the `sourceTabId` property. 
4. Open uBO's dashboard (or logger) **through uBO's popup panel**.
    - The issue can't be reproduced if opening the dashboard from uBO's preferences in `about:addons`.
5. Go back to the popup test page previously opened above, and repeat the test in 3.

Result: uBO fails to properly filter the popup.

After much investigation, it turns out that the one call to [`vAPI.closePopup()` in `vapi-common.js`](https://github.com/gorhill/uBlock/blob/0e078e536d8630e0823a488c6d1cdb222b0b01bb/platform/chromium/vapi-common.js#L80) is causing this issue:

    window.open('','_self').close();

The issue does not exist with Chromium, with the same code path.

I have no idea why this happens. It appears Firefox's internals are in a bad state after step 4: the `sourceTabId` from `webNavigation.onCreatedNavigationTarget` is always `-1`.

**Comment by gorhill** [comment]
The fix is a workaround. The consequence of this workaround is that uBO's popup panel is now sticky, i.e. it will remain open after you click to open the logger, dashboard, element picker, element zapper. You will have to close it yourself by pressing the Esc key, or clicking outside the popup panel.

**Comment by kasper93** [comment]
Hmm, I'm wondering why you do `window.open('','_self').close();`? `window.close();` works just fine and doesn't break anything in the process. At least for Firefox.

**Comment by gorhill** [comment]
@kasper93 I don't know, I didn't put this code there: <https://github.com/gorhill/uBlock/commit/b301ac031e0c2e9a99cb6f8953319d44e22f33d2#diff-bc664f26b9c453e0d43a9379e8135c6a>.

It didn't occur to me to try `window.close()`, I assumed there must have been issue with it as the rationale to use what is currently in there. I will give it a try, and if it works, I will use it just for Firefox until I understand why `window.open('','_self').close()` was used.

**Comment by kasper93** [comment]
@gorhill: Sure, I just read here https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups 

> The popup can be closed programmatically by calling window.close() from a script running in the popup.

So it seems to be blessed way to close popups. Might be hard to remember why you did this way after all this time. :)

**Comment by gorhill** [comment]
@kasper93, you're right, I confirm this works fine. Wish I had seen your comment before pushing rc2.

**Comment by gorhill** [comment]
I removed the "browser bug" label, but I do wonder what is occurring internally for Firefox API's `webNavigation.onCreatedNavigationTarget` to become broken. I wonder if this issue can be triggered by a web page.

**Comment by gwarser** [comment]
https://stackoverflow.com/questions/57854/how-can-i-close-a-browser-window-without-receiving-the-do-you-want-to-close-thi :)

**Comment by gorhill** [comment]
Putting back the browser bug, this simple HTML document will break `webNavigation.onCreatedNavigationTarget`:

    <!DOCTYPE html>
    <html>
    <head></head>
    <body>
    <script>
        window.open('','_self').close();
    </script>
    </body>
    </html>

**Comment by Rob--W** [comment]
Thanks for the debugging @gorhill and others. I have poked a bit more at it, created a test case and reported the bug at: https://bugzilla.mozilla.org/show_bug.cgi?id=1403349
