### ISSUE TITLE
Add global toggle through middle click on the toolbar icon

### ISSUE THREAD

**Issue by shmerl** [gorhill/uBlock#3058]
It can be useful to toggle the add-on temporarily (testing, verification and so on). Middle clicking the toolbar icon is a good method, because it's unlikely to happen by mistake, while at the same time it's not overly complicated when needed.

And it's different from "disable / enable for this site", because "for this site" actually modifies the whitelist and it's not global.

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).
