### ISSUE TITLE
[Enhancement] Ability to open the request logger in a window pane 

### ISSUE THREAD

**Issue by tyaremco** [gorhill/uBlock#306]
uBlock's request logger can be made more useful by having it open in a pane next to the page being investigated.  ABP had this feature: http://i.imgur.com/GkxfNlT.png

It can make dynamic filtering and troubleshooting much more intuitive because you can see requests come in as the page content is populated.  
For example, it becomes easy to see which resources are still being loaded _after_ the useful portions of page are loaded (in order to block them).  Moreover, you can interact with a page and see the resulting requests immediately. For example, pressing 'play' on a video player to see where a filter might be preventing the video from loading.

Having to switch back and forth between the request logger and the page in question makes the above examples cumbersome.

**Comment by androidland** [comment]
ublock also has a feature like this, see https://github.com/gorhill/uBlock/wiki/The-network-request-logger
ublock can also create static filter from logger up 0.9.8.7

**Comment by tyaremco** [comment]
@androidland My comment perhaps wasn't very clear...I added a sentence at the beginning.

**Comment by gorhill** [comment]
I did it [for Chromium at one point](https://github.com/chrisaljoudi/uBlock/issues/433#issuecomment-68728494). However I wanted the code to be portable and I ended up using a plain window.

I still did consider the idea lately, I agree that it would be more convenient. There are complications however, and this is what is holding me back. Mainly, uBlock's logger can be more accurately compared to Firefox's browser console (<kdb>Ctrl</kbd>-<kdb>Shift</kbd>-J): it is a global console which cannot be docked because its output is not that of a specific tab.

But I could probably find a solution for this, though it will have its quirks (if many are docked, where are behind-the-scene requests logged?).

Anyway I am willing to look into this, however I will have to read about FF, one requirement is that I can embed the logger as is, i.e. FF API allows to embed HTML-based pane in its dev console.

**Comment by tyaremco** [comment]
Actually, I wasn't intending that the logger show only tab-specific requests when it is docked.  In fact, I think it's more trouble than it's worth.  I just want to be able to attach that global logger to the tab I'm investigating as a matter of convenience and efficiency.  

> it is a global console which cannot be docked because its output is not that of a specific tab.
Are you saying that *because* the logger is global in scope it is not allowed/not possible to be docked to a single tab?  Or you feel this is a UX issue?

**Comment by anewuser** [comment]
@tyaremco Try this:

![uBlock Sidebar settings](https://cloud.githubusercontent.com/assets/6733770/8611859/f4f484aa-269d-11e5-8ae3-43c3f14f9004.png)
![uBlock Sidebar collapsed](https://cloud.githubusercontent.com/assets/6733770/8611861/f4f966be-269d-11e5-8edc-43fcd273dd74.png)
![uBlock Sidebar expanded](https://cloud.githubusercontent.com/assets/6733770/8611860/f4f97e38-269d-11e5-9ca2-d58d23519aee.png)

**Comment by tyaremco** [comment]
If I could make that sidebar a horizontal pane instead of a vertical one it would be perfect.  Otherwise, things are too compressed for my liking.  I also use vertical tabs so I have even less horizontal room to work with.  I would sooner use a floating window than a vertical pane.

**Comment by silverwind** [comment]
One feature I often used in AdBlock's logger is the ability to right click a request and create a rule based on the URL of the clicked entry with wildcards. Would love to see something like this in uBlock, along with a split pane instead of a full window.

**Comment by gorhill** [comment]
> create a rule based on the URL of the clicked entry

https://github.com/gorhill/uBlock/wiki/The-logger#static-network-filters

**Comment by silverwind** [comment]
Wouldn't a "Add custom filter rule based on current filter" button make sense in the logger UI?

**Comment by silverwind** [comment]
Ah, I just discovered the clickable column that triggers this dialog. Maybe some kind of icon in that column would make it more discoverable.

(deleted my old comment as it didn't make sense)

**Comment by gorhill** [comment]
> Maybe some kind of icon in that column would make it more discoverable

That column is to report whether a request is blocked (`--`), allowed (`++`), or noop'ed in some circumstances (`**`), and it can be used in a filter expression to filter out rows (`|--` will show rows of requests which have been blocked). An icon would get in the way of this functionality.

**Comment by silverwind** [comment]
@gorhill maybe a table header could improve the UX in that case.

**Comment by silverwind** [comment]
Also, I think the buttons in the Logger UI could use some hover text. I'll see if I can contribute that.

**Comment by gorhill** [comment]
Ability to open logger in a sidebar was added in [1.15.0](https://github.com/gorhill/uBlock/releases/tag/1.15.0).
