### ISSUE TITLE
newest version no longer compatible with latest Pale Moon

### ISSUE THREAD

**Issue by sucht** [gorhill/uBlock#3063]
please make it compatible again.

if you cannot do it for what ever reason, fix this sentence please "uBlock Origin is compatible with SeaMonkey, Pale Moon, and possibly other browsers based on Firefox." because it is somewhat misleading

latest Pale Moon compatible version is no longer working on twitch it seems, i get advertisement :(

if this is a config problem on my end please enlighten me on how to fix it.

thanks.

**Comment by gorhill** [comment]
You completed fail to respect what is asked from you in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), and you dismissed to minimally provide information asked from you in the issue template.

I installed uBO 1.14.11rc7 in Pale Moon 27.5.0 and all worked fine.

There is a visual glitch in the advanced filtering pane of the popup panel when there is a scroll bar, but this part renders fine with all other browsers, and it used to render fine with previous Pale Moon version -- hence in all likelihood a regression in Pale Moon in properly rendering CSS styles.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

if you want me to keep supporting a working version of uBO for Pale Moon, you will have to actually make efforts when you file an issue to make the case there is an issue with uBO. You completely failed.
