### ISSUE TITLE
Twitch Beta gets ads through

### ISSUE THREAD

**Issue by Zetawilk** [gorhill/uBlock#3064]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Ads are playing on Twitch "Beta". 

### One or more specific URLs where the issue occurs
https://go.twitch.tv/[Enter any user name here.]
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
https://imgur.com/a/Qd55M
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
1. Try to view a live stream on Twitch. 

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
No settings differ from the default settings. 
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7
- Browser/version: Firefox 55.0.3
- uBlock Origin version: 1.14.10

##### Your filter lists
Default filter lists. 
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
