### ISSUE TITLE
Feature request: Bypassing websites like awin using document-blocked page.

### ISSUE THREAD

**Issue by hoshsadiq** [gorhill/uBlock#3066]
There are many websites that link to other sites like `awin` (see below) where the final URL is in the `awin.com` URL, but it's escaped (e.g. hotukdeals.com loves to do this but many other sites do it too).

As a user I can either temporary allow this website and reach my final destination, or I can manually unescape the final URL (open chrome dev-tools > type `unescape('<URL HERE>')`) and then open the link.

I'm proposing that make this automatic. We can put a list of any link that might be in the URL (escaped and non-escaped, as some sites put non-escaped link there). That way the user can simply click on the link and open it as opposed to having to temporary allow the URL on the filter list, or having to manually escape and then open.

![awin](https://i.imgur.com/WFbdQ4Z.png)

**Comment by gwarser** [comment]
Did you try to click on magnifier icon on the right?

**Comment by hoshsadiq** [comment]
Ah! Wow. I've been doing this manually for a long time...
