### ISSUE TITLE
[Firefox] 3rd-party filters out of date when using private browsing

### ISSUE THREAD

**Issue by nsaneman** [gorhill/uBlock#3071]
Update your uBO filters and then enable the history option to always use the private browsing mode. Restart when prompted and then look at the 3rd-party filters in uBO.

With uBO 1.14.10 you'll find that the following are moved to "Custom".
* AAK-Cont Filter For uBlock Origin
* AdGuard English filter​
* Spyware filter
* uBlock filters – Resource abuse

And the following claim to be out of date.
* uBlock filters
* uBlock filters – Badware risks
* uBlock filters – Privacy
* uBlock filters – Unbreak
* EasyList
* EasyPrivacy
* Malware Domain List
* Malware domains
* Peter Lowe’s Ad and tracking server list

With uBO 1.14.11rc8 the filters are listed correctly, but it'll constantly say the following are out of date when you relaunch Firefox.
* uBlock filters
* uBlock filters – Badware risks
* uBlock filters – Privacy
* uBlock filters – Resource abuse
* uBlock filters – Unbreak
* EasyList
* EasyPrivacy
* Malware Domain List
* Malware domains
* Peter Lowe’s Ad and tracking server list

I've never noticed this problem before and it certainly isn't an issue when using Chrome, so I guess this is a new uBO or Firefox 56.0 x64 bug/limitation?

**Comment by gorhill** [comment]
See <https://bugzilla.mozilla.org/show_bug.cgi?id=1313401>.

**Comment by nsaneman** [comment]
So if my understanding is correct, uBO originally used the browser.storage.local API and then a Firefox dev said that you should be using indexedDB instead. You've now switched to that and found that indexedDB uses more resources and it doesn't work with the browser setup to use the private browsing mode.

I guess I'll stick with Chrome if Mozilla refuse to fix this major issue.

**Comment by gwarser** [comment]
You can try one "trick":

- If you set "Firefox will newer remember history" or "Use custom settings for history" -> "Always use private browsing mode"
- go to uBlock dashboard
- right click -> View Page Info
- Permissions tab
- "Set Cookies" -> uncheck "Use Default" -> check "Block"
- UBO should now use permanent `browser.storage.local` (`browser-extension-data/uBlock0@raymondhill.net/storage.js`). With all downsides, of course.

**Comment by nsaneman** [comment]
Hey @gwarser, thanks for that. Your suggestion works perfectly with the latest RC build of uBO.

I know that ABP is currently using storage.js and that produces a smaller file than indexedDB, but it has an issue with 32-bit versions of Firefox. Are there any other issues that I should be aware of?

https://bugzilla.mozilla.org/show_bug.cgi?id=1371255#c27

**Comment by gorhill** [comment]
> found that indexedDB uses more resources

I did not find that. Another user reported performance issues, but by the look of the bugzilla entry, it's not clear what the issue is really for that user. I myself said it works as expected, more perfomant than browser.storage.local for sure.

**Comment by nsaneman** [comment]
Thanks for that @gorhill. I guess I'll have to keep an eye on the bug reports.

If Mozilla don't fix the issue couldn't you check if private browsing mode is enabled and if it is revert to browser.storage.local? Surely that's better than having uBO attempting to update the filters every time the browsers launched.
