### ISSUE TITLE
*.chrome-scheme not detected, toggle X badges not show

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [gorhill/uBlock#3073]
### Describe the issue
- FF56 (windows 7), uBo 1.14.10 (note I just updated from 55 and 1.13.8->1.13.10->current, restarted etc)
- On about:newtab the panel shows my default settings including blocking remote fonts `no-remote-fonts: * true` - see the red X lower right. Note the uBo icon is greyed out. This is recognized as `newtab.about-scheme` in uMatrix
![ubo-newtab](https://user-images.githubusercontent.com/16656956/31044562-3481ef9c-a62e-11e7-9800-ce3d111e00c6.png)
- My actual newtab page is a speed dial that is recognized as `speeddial.chrome-scheme` in uMatrix [note the extension I use is Speed Dial [FVD] which is currently legacy but they have a chrome version which will be coming to AMO]
- this is how uBo handles *.chrome-scheme* - note the red x missing on remote fonts. Also note the uBo icon is NOT greyed out
![ubo-chrome](https://user-images.githubusercontent.com/16656956/31044590-c3e13030-a62e-11e7-80b2-214614392849.png)

### to reproduce
- Create a nilla profile
- Install uBo
- Install [Speed Dial [FVD]](https://addons.mozilla.org/en-US/firefox/addon/fvd-speed-dial/?src=search)
- Set `no-remote-fonts: * true`
- open about:newtab and click on uBo icon - note red X across remote fonts
- open speed dial home page - note red X missing on remote fonts

I looked but did not find anything similar lodged as an issue. Apologies if one already exists. I also do not know what else loads a *.chrome-scheme, and once FF57 lands, this legacy extension will be updated to a web extension, and I do not know what that will use. If this is not that important (eg its just because of my extension), then close it and I will see what happens after 57 :) Thanks

**Comment by gwarser** [comment]
May be https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#differences-with-ubolegacy

>uBO/webext has limited access to behind-the-scene network requests, unlike uBO/legacy which had full access to all behind-the-scene network requests. For example, you won't be able to see (and block) network requests made by other extensions. Related: "Support moz-extension: urls in MatchPattern".

**Comment by gorhill** [comment]
When the `about:newtab` is opened, I see uBO's `browser.tabs.onUpdated` listener being called, however the `changeInfo.url` is `undefined`. This what is causing the issue, uBO ends up not recording the tab as an existing one.

However I see that the `tab.url` parameter is correctly set. So at first glance it seems uBO could fall back on this value when `changeInfo.url` is not set. The same code is used with Chromium, so I am wondering of the case of `changeInfo.url === undefined` ever occurred with Chromium, and whether this should be considered an issue with Firefox.

**Comment by gorhill** [comment]
Fixed as said above, uBO will be able to add rules/whitelist for `about:newtab` now.

However, as @gwarser pointed out, the network requests made by the `about:newtab` page are out of reach of uBO.

**Comment by Thorin-Oakenpants** [comment]
Yeah, I know about the privileged behind-the-scenes :-(

I am actually troubleshooting something else, so lots of stuff happening in a nilla profile with uBo + greasemonkey, but here's some more on this issue

##### one
I compared the default in my nilla with the one I reported the issue
```js
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme    <------------- I was missing this (is it new?)
fvd.speeddial.chrome-scheme  <--- i added this at some stage for some reason (testing?)
moz-extension-scheme
opera-scheme
vivaldi-scheme
```

when loading the speed dial "new page"
- I removed the `fvd.speeddial.chrome-scheme` and the speed dial tab now displays the uBo icon as red, and the red X shows on block remote fonts (I think this is applying "site" rules)
- I added the `chrome-scheme` and now the icon is greyed out (as should be because we can't enforce rules on this scheme)
- as a test I blocked popups BUT a site rule was applied
   - `no-popups: fvd.speeddial.chrome-scheme true`
   - is this an issue?

##### two
- in my nilla profile, I set firefox to use a blank page
   * options>general> when firefox starts> use a blank page
- uBo icon on this is ... and I'll come back and edit this post to fill this in because I'm not concurrent profiles and I forgot

... watch this space

**Comment by gorhill** [comment]
uBO knows nothing about protected pages, it just won't see network requests made from it. It does see however the context of the page, that is extracted from the scheme or hostname of the page. When uBO has a context, rules can be created for the context. This is what was fixed here, looking up the proper context, so that when one whitelist or toggle a per-site switch, the proper whitelist/rule is created for the current context.

Whether these contexts are pointless is outside the realm of uBO, it's for the user to deal with. For instance, blocking network requests from `newtab.about-scheme` used to work until recently, it seems they might have changed this.

**Comment by Thorin-Oakenpants** [comment]
no worries - I'm just wondering how someone gets to ever see the global scope in the dropdown panel :)
