### ISSUE TITLE
Ublock origin is completely broken for android

### ISSUE THREAD

**Issue by meepingsnesroms** [gorhill/uBlock#3074]
With the newest build from the firefox store on firefox for android clicking the ublock origin tab in the drop down menu does nothing and with icecat android and the newest nightly the ublock origin tab does not even appear or disappears after a few launches.

**Comment by gwarser** [comment]
Check this https://github.com/gorhill/uBlock/issues/2958

**Comment by gorhill** [comment]
Also labelling as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
