### ISSUE TITLE
Some websites show a blank page for a few seconds before the actual content

### ISSUE THREAD

**Issue by darkbasic** [gorhill/uBlock#3075]
### Describe the issue

Some websites show a blank page for a few seconds before showing the actual content of the page.

### One or more specific URLs where the issue occurs

[https://www.trovaprezzi.it/](https://www.trovaprezzi.it/)

### Screenshot in which the issue can be seen

![ublock_origin_trovaprezzi](https://user-images.githubusercontent.com/1047358/31047262-8b530120-a607-11e7-84b9-b99825f4a686.png)

### Steps for anyone to reproduce the issue

1. Visit the above mentioned link.

### Your settings

- OS/version: Arch Linux
- Browser/version: Chromium 61
- uBlock Origin version: 1.14.8

##### Your filter lists

Each of the following lists gives me the above mentioned problem with trovaprezzi:
- uBlock filters - Privacy
- EasyPrivacy
- Peter Lowe's Ad and tracking server list

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
Page renders fast if allowing google-analytics.com, hence an obvious filter issue.

**Comment by darkbasic** [comment]
Isn't `uBlock Privacy` your own filter list? Where am I supposed to file a bug about `uBlock Privacy`?

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues

**Comment by gorhill** [comment]
> Where am I supposed to file a bug about `uBlock Privacy`?

[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> For filter-related issues, report on the respective filter list support site, **or at uBlockOrigin/uAssets**.

**Comment by gorhill** [comment]
Force an update "uBlock fitlers" to get the fix.

**Comment by darkbasic** [comment]
Thanks, your fix works. I'm sorry if didn't choose the right repository to file the bug report, but I didn't know of uAssets.
