### ISSUE TITLE
Githubusercontent.com down and lists not updated

### ISSUE THREAD

**Issue by ShintoPlasm** [gorhill/uBlock#3078]
### Describe the issue

Githubusercontent.com has been down and unreachable for over a week now, with no explanation provided on any Github blog as far as I could search. This leads to any uBO filter lists hosted on that domain not being updated - including uBO's own internal filter lists (e.g. Badware, Unbreak...).

I am aware that this is not directly your remit, gorhill, but I was wondering if Github have transferred user content to a different domain and whether you would need to update your filter lists' source URLs within uBO.

### One or more specific URLs where the issue occurs

N/A - filter lists included with uBO function properly, but cannot be updated.

### Screenshot in which the issue can be seen

<img width="524" alt="screen shot 2017-10-01 at 09 32 01" src="https://user-images.githubusercontent.com/15131665/31053036-eaaa3e7a-a68b-11e7-9cb2-211b57f4366a.png">

### Steps for anyone to reproduce the issue

1. Switch to the '3rd-party filters' tab in the dashboard.
2. Click 'Update now'
3. A broken network icon appears next to all selected uBO-own filter lists (as well as certain selected external filter lists).
4. Filter lists cannot be updated and the 'Update now' button remains active.
5. Any other internet connection works fine in my browsers.

### Your settings

- OS/version: macOS High Sierra 10.13
- Browser/version: Opera Stable 48.0.2685.32; Firefox 56.0
- uBlock Origin version: 1.14.8 (Opera from Chrome Store); 1.14.10 (FF)
- 'I am an advanced user' selected (I have confirmed the issue is there with this setting unselected)
- 'Prevent WebRTC from leaking...' selected
- 'Ignore generic cosmetic filters' selected

##### Your filter lists

Default filter lists; minus EasyList, EasyPrivacy; plus ISR

##### Your custom filters (if any)

BarbBlock; AdGuard's English, Dutch and Spyware filter lists (all of these update fine as they don't appear to be hosted on githubusercontent.com).

**Comment by ShintoPlasm** [comment]
<img width="524" alt="screen shot 2017-10-01 at 09 32 01" src="https://user-images.githubusercontent.com/15131665/31053077-19e78afc-a68d-11e7-8c3a-103d5c8b2cfb.png">

**Comment by ShintoPlasm** [comment]
For a screenshot not hosted on githubusercontent.com:

https://postimg.org/image/fq04tkr6j/

**Comment by gorhill** [comment]
uBO is telling you it can't fetch something sue to network error: please find what is blocking these network requests on your side. Read carefully [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ShintoPlasm** [comment]
Thank you, gorhill, that solved it - it was Sky's Broadband Shield causing the blockage.

**Comment by BilBg** [comment]
> I've tried several IsItDown websites which all said GHUC.com was down...

`raw.githubusercontent.com` exists, `githubusercontent.com` does not ("githubusercontent.com’s server DNS address could not be found")

http://downforeveryoneorjustme.com/raw.githubusercontent.com

http://www.websitedown.info/raw.githubusercontent.com

http://downforme.org/is-raw.githubusercontent.com-down-today-for-everyone

https://www.siteuptime.com/users/quickcheck.php?HostName=raw.githubusercontent.com&Domain=&Content=&ServiceId=1&Locations%5B1%5D=on&Locations%5B5%5D=on&Locations%5B7%5D=on&Action=Check

https://www.siteuptime.com/users/quickcheck.php
