### ISSUE TITLE
Firefox does not refresh pages like Ebay with uBlock version 1.14.10

### ISSUE THREAD

**Issue by ki-dragon** [gorhill/uBlock#3079]
### Describe the issue
Firefox does not refresh pages like Ebay with uBlock version 1.14.10.
It works with 1.13.8.
There are several negativ feedbacks on the Firefox add-on homepage already.

### One or more specific URLs where the issue occurs
www.ebay.de
or any other ebay pages

### Screenshot in which the issue can be seen
No possible.

### Steps for anyone to reproduce the issue
Just do a search for things which deliver more search pages than one.
Press "2" or which other "page" ever. Nothing happens then. You see the url changing but the page does not refresh. You have to refresh it manually.
Related to several other Ebay pages too.

### Your settings
- OS/version: Windows 10 pro.
- Browser/version: 55.0.3 (or several before)
- uBlock Origin version: 1.14.10

##### Your filter lists
Default

##### Your custom filters (if any)
No

**Comment by gorhill** [comment]
Read [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.10).

**Comment by rodneyrod** [comment]
This bug is still present in Firefox 56 on OSX.

**Comment by nebrot** [comment]
I had same problems with ebay, but after deactivating "blocksite" (legacy extensions), the page starts to work again.

**Comment by sp00n** [comment]
I had the same problem with Firefox Unbranded Nightly 54.0.2 64bit on Win7x64 and version 1.14.14. Ublock was even set to "off" (but not disabled) for ebay, but the pages still wouldn't load the new content, which was driving me nuts.

I've now switched to the pre-release version 1.14.15b0 that was just released, and it started working again.

**Comment by gorhill** [comment]
@sp00n This makes no sense, let's not spread erroneous conclusions. [Nothing in 1.14.15b0](https://github.com/gorhill/uBlock/compare/1.14.14...master) changed to come to such conclusion. As explained repeatedly in release notes, this is a Firefox webext issue, and fixed in FF57.
