### ISSUE TITLE
How to block this ads?

### ISSUE THREAD

**Issue by emresaracoglu** [gorhill/uBlock#3080]
This ad server bypasses the "uBlock".

This sites has a lot of ads

For example site: 
[Click Here 1](https://тестування.укр/testkrok/buclet/7/2)
[Click Here 2](http://zhzh.info/news/2017-07-20-32983)

How we can block this site?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
