### ISSUE TITLE
[Suggestion] Visual hint to `Back up to file` in uBO's popup (if long time passed since last backup)?

### ISSUE THREAD

**Issue by BilBg** [gorhill/uBlock#3081]
(because this will probably be closed fast I will try to be short)

### Describe the issue
It seems to me that many people do not do Backups of the uBO Settings.
(they post about it only when they (finally) lose their settings because e,g, browser bug in some new browser version)

I hope people at least look from time to time at the uBO's popup (especially people which had changed any settings)

### Suggestion
I imagine some visual hint in uBO's popup like:
- change colour (e.g. to pink) of the `Open the dashboard` icon
- change colour of its background (around icon)
- new (violet) icon appears with `data-tip` "Back up your Settings / Last backup was XX days ago"
- anything else that attracts user attention in a not-very-annoying way (is this possible ;) )

The hint will show if (XX days passed since last backup) && (Settings had changed)
Default interval may be 30-60 days (will be good to be user selectable)

P.S.
I don't need this for me but I remember why I was hesitant to do [Back up to file] for the first time when I was a new user of uBlock Origin: 
just above the button is written "Storage used: 46,303,767 bytes" and I was thinking the [Back up to file] will create this big a file :)

(unfortunately I wasn't able to be short (Mark Twain comes to mind))

**Comment by gorhill** [comment]
> (because this will probably be closed fast I will try to be short)

Please do not make such assumption -- I judge issues on their own merit, not on the meta arguments made.

Just by reading the title, I already agreed this was a good idea.

**Comment by gorhill** [comment]
I updated comment above.

**Comment by BilBg** [comment]
> those who really would rather have also a hint on the icon itself

People which use the popup but rarely go to Dashboard.
They may be unaware that when they click "The large power button" or "per-site switches" or respond to strict-blocking page something changes in the panes of Dashboard.
(I had seen such questions: "I clicked Permanently, how to undo?")

They may on first use look/set '3rd-party filters' and when open again Dashboard will land on the same pane and they may not look the others.
("I am a computer newbie so I better leave alone 'My rules' or 'Settings' to not break something.")

**Comment by gorhill** [comment]
I am going to pass on this, reality is I just don't have the time. Issues are still being opened and their number is not going down, so no point working on "would be nice stuff" stuff. Workaround: set up a recurring reminder on your side".
