### ISSUE TITLE
Disabling javascript breaks ublock origin

### ISSUE THREAD

**Issue by pksadiq** [gorhill/uBlock#3083]
Disabling javscript in Firefox browser breaks ublock origin.

How to reproduce:
0. Visit some web page
1. Go to `about:config` page
2. search for `javascript.enabled` and set it to `false`
3. Now clicking ublock origin icon brings a broken UI with dysfunctional buttons.
    Also, the ublock settings opens a blank page, and of course ublock no longer blocks anything.

If the above process doesn't break ublock origin, restart firefox after disabling javascript, and try.

#2966 describes the same, but with no-script addon.

- OS/version: Debian Stretch GNU/Linux
- Browser/version: Firefox/52.4.0
- uBlock Origin version: 1.14.10

**Comment by gorhill** [comment]
Obviously a browser issue -- uBO has no say in when the browser chooses to not executing its own extension code.
