### ISSUE TITLE
ISP blocking uBlock Origin, need advice

### ISSUE THREAD

**Issue by ukheather** [gorhill/uBlock#3086]
This is a little different type of problem but no idea where else to post it, my ISP is blocking uBlock from updating any filter with their broadband shield. They said that Symantec block the sites and they block specific urls not apps.

All filters fail to update with a network error if I have my ISP broadband shield enabled, when I turn it off I can update fine.

What url could it be that they are blocking as they said I need to give them one so they can pass it on to Symantec?

**Comment by gorhill** [comment]
Open the logger, then force an update. The logger will contain the URLs which failed:

![a](https://user-images.githubusercontent.com/585534/31075595-4e38f27a-a744-11e7-904d-778106eaea10.png)
