### ISSUE TITLE
Disabling scripts does not prevent Admiral scripts from running

### ISSUE THREAD

**Issue by chylex** [gorhill/uBlock#3088]
### Describe the issue

Some websites that use Admiral still display the anti-adblock popup, even though I've disabled all scripts for that website in uBlock (as I always do for other types of anti-adblock popups, and that works most of the time).

Disabling JavaScript completely in Firefox (using `about:config` -> `javascript.enabled = false`) prevents the popup from showing, so there must be something wrong with how uBlock disables JS on individual sites.

I included my settings file below. This is happening on 3 computers I use with the same settings; it does not happen with the default uBlock settings, so one of my lists must be blocking something Admiral doesn't like, but the issue is that Admiral scripts or any other JS on the website should not be running in the first place.

### One or more specific URLs where the issue occurs

http://www.thewindowsclub.com/game-mode-in-windows-10

### Screenshot in which the issue can be seen

Disabled inline scripts, first & third party scripts, third party frames:

![image](https://user-images.githubusercontent.com/3685160/31126863-5f0303c0-a84d-11e7-81d9-eda6874d4281.png)

### Your settings

- **OS/version:** Windows 10, 1607 & Windows 7
- **Browser/version:** Firefox Developer Edition 55.0b9
- **uBlock Origin version:** 1.14.10, happened with 1.13.8 too
- **uBlock Origin settings:** https://www.dropbox.com/s/d9wsf0kunca56nc/ublock.txt?dl=1

**Comment by mapx-** [comment]
Are you using "ublock filters". If no just enable that list and remove the dynamic filters for that site.

**Comment by gwarser** [comment]
Why Firefox 55dev? I cannot confirm in UBO Stable or Dev in Firefox ESR, Stable (multiprocessing on/off) and Nightly.

**Comment by gorhill** [comment]
Unable to repro, no script were executed when I blocked all scripts.

First, not blocking scripts, one is able to see the source and put breakpoints in the debugger:

![a](https://user-images.githubusercontent.com/585534/31132065-cfc05596-a829-11e7-9f41-fe7fb27191af.png)

When blocking all scripts, the debugger can't see any scripts from the site, the only one shown are those of uBO itself and some from the browser's framework:

![b](https://user-images.githubusercontent.com/585534/31132090-e12d05c2-a829-11e7-8817-3a8d34c39632.png)

You will need to provide better evidences, and make a better case for such a claim. Closing as _invalid_ until you do so.

**Comment by uBlock-user** [comment]
Clear all site, cache and cookie data for that domain and then try again via blocking all the scripts.

**Comment by chylex** [comment]
**Adding `uBlock filters` fixed the issue, thanks @mapx-**

Don't know what exactly caused the issue, it still popups the Admiral page if I uncheck uBlock filters in the list.

There definitely still is a difference between disabling scripts in uBlock and the `javascript.enabled` flag, since disabling scripts in uBlock still loads the main website in the debugger and lets me put a breakpoint in it, and `javascript.enabled = false` does not show any scripts at all... so the behavior on your screenshot is different to what I'm experiencing, but I can't figure out why.

Just as a side detail, this also happens in an old Pale Moon also running on Windows, basically both Firefox-based browsers running on Windows I have can repro the same issue. I might test it on Linux when I can to see if there's a difference, but since Admiral isn't causing issues anymore, it might not be worth trying to figure out anyway.

### Disabled scripts in uBlock
- Script from www\.thewindowsclub.com is still loaded, looks different from your screenshot
- However, all other scripts and third party stuff is gone, so that works at least

![obrazek](https://user-images.githubusercontent.com/3685160/31144845-2d15d5ba-a882-11e7-87ac-7841f7128db5.png)

### Nothing disabled in uBlock
- Just for reference, this is how the debugger looks without disabling scripts in uBlock, to prove that I'm not disabling scripts wrong or something

![obrazek](https://user-images.githubusercontent.com/3685160/31145373-e3df8a9c-a883-11e7-96a3-929f48771fab.png)

### Disabled JS using `javascript.enabled`
![obrazek](https://user-images.githubusercontent.com/3685160/31144851-30592d6c-a882-11e7-955e-4620772837ec.png)

**Comment by gorhill** [comment]
Use ctrl + click reload button in toolbar, see if it makes a difference.

**Comment by chylex** [comment]
It did not, here is the logger:

![logger](https://user-images.githubusercontent.com/3685160/31152898-72f1a23c-a89e-11e7-8e93-61c0eddc2455.png)

The Admiral banner appears the moment `puzzlingfall.com` request finishes, and then it loads the images and font. That domanin is mentioned in a `<script>` tag on line 517 in the FF debugger, but it also has some syntax highlighting errors - could malformed HTML interfere with the script detection?

Here's also the console contents, though it seems pretty much identical to what's happening in the logger (all parts mentioning `<script>` translate to "failed loading script element from source ...")

```
00:47:20.569 GET http://www.thewindowsclub.com/game-mode-in-windows-10 [HTTP/1.1 200 OK 993ms]
00:47:21.553 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/themes/TwcMetro/style.css [HTTP/1.1 200 OK 83ms]
00:47:21.554 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/plugins/yet-another-related-posts-plugin/style/widget.css [HTTP/1.1 200 OK 50ms]
00:47:21.554 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/plugins/addthis/frontend/build/addthis_wordpress_public.min.css [HTTP/1.1 200 OK 46ms]
00:47:21.565 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/plugins/yet-another-related-posts-plugin/style/related.css [HTTP/1.1 200 OK 45ms]
00:47:23.612 Načtení prvku <script> ze zdroje „http://www.google-analytics.com/analytics.js“ se nezdařilo.  game-mode-in-windows-10:1
00:47:23.618 Načtení prvku <script> ze zdroje „http://www.thewindowsclub.com/wp-includes/js/wp-emoji-release.min.js?ver=4.8.2“ se nezdařilo.  game-mode-in-windows-10:1
00:47:23.638 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2017/04/enable-use-Game-Mode-in-Windows-10.png [HTTP/1.1 200 OK 27ms]
00:47:23.638 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2017/04/enable-use-Game-Mode-in-Windows-10-1.jpg [HTTP/1.1 200 OK 52ms]
00:47:23.639 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2017/04/enable-use-Game-Mode-in-Windows-10-2.jpg [HTTP/1.1 200 OK 72ms]
00:47:23.639 GET http://0.gravatar.com/avatar/66d16430bc205a37b8766f241950183c [HTTP/1.1 200 OK 32ms]
00:47:23.639 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/themes/TwcMetro/images/twc-logo-11.png [HTTP/1.1 200 OK 23ms]
00:47:23.639 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/themes/TwcMetro/images/spritesheet.png [HTTP/1.1 200 OK 48ms]
00:47:23.640 Načtení prvku <script> ze zdroje „https://s7.addthis.com/js/300/addthis_widget.js#pubid=happyandyk“ se nezdařilo.  game-mode-in-windows-10:133
00:47:23.641 Načtení prvku <script> ze zdroje „https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js“ se nezdařilo.  game-mode-in-windows-10:135
00:47:23.641 Načtení prvku <script> ze zdroje „http://www.googletagservices.com/tag/js/gpt.js“ se nezdařilo.  game-mode-in-windows-10:1
00:47:23.641 Načtení prvku <script> ze zdroje „http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js“ se nezdařilo.  game-mode-in-windows-10:216
00:47:23.641 Načtení prvku <script> ze zdroje „http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js“ se nezdařilo.  game-mode-in-windows-10:262
00:47:23.643 Načtení prvku <script> ze zdroje „http://cse.google.com/cse.js?cx=partner-pub-5950002284129980:7lz6cl-5ojg“ se nezdařilo.  game-mode-in-windows-10:1
00:47:23.643 Načtení prvku <script> ze zdroje „http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js“ se nezdařilo.  game-mode-in-windows-10:375
00:47:23.643 Načtení prvku <script> ze zdroje „http://thewindowsclub.disqus.com/recent_comments_widget.js?num_items=5&hide_avatars=1&avatar_size=32&excerpt_length=40&hide_mods=0“ se nezdařilo.  game-mode-in-windows-10:403
00:47:23.739 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-includes/images/rss.png [HTTP/1.1 200 OK 23ms]
00:47:23.768 Načtení prvku <script> ze zdroje „http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js“ se nezdařilo.  game-mode-in-windows-10:404
00:47:23.770 Načtení prvku <script> ze zdroje „http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js“ se nezdařilo.  game-mode-in-windows-10:426
00:47:23.770 Načtení prvku <script> ze zdroje „http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-includes/js/wp-embed.min.js?ver=4.8.2“ se nezdařilo.  game-mode-in-windows-10:453
00:47:23.912 Načtení prvku <script> ze zdroje „http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js“ se nezdařilo.  game-mode-in-windows-10:504
00:47:24.091 Načtení prvku <script> ze zdroje „http://ad.doubleclick.net/ddm/adj/Azvgq/Asby“ se nezdařilo.  game-mode-in-windows-10:1
00:47:24.131 GET http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/themes/TwcMetro/style.css [HTTP/1.1 200 OK 0ms]
00:47:24.263 Načtení prvku <script> ze zdroje „http://ad.doubleclick.net/ddm/adj/Ahljp/Bryokm“ se nezdařilo.  game-mode-in-windows-10:1
00:47:25.741 POST XHR http://puzzlingfall.com/00242bdef5bee94ef8189ee2063c0eb43a7d10c331f2f83b48d745ba921c7b526f16f633c59840393de2ed1160957b904cd1eb853f9d727dd9efecc4eb07a9bbcecd73d8b497e5500670df8e09a8d6bf6ed42b78f44ca169aef7b989af8843 [HTTP/1.1 200 OK 176ms]
00:47:25.943 GET http://www.thewindowsclub.com/Admiral-TWC-engage-assets/Windows%20Club-engage-assets/windows-club-engage-background.jpg [HTTP/1.1 200 OK 78ms]
00:47:25.946 GET http://fonts.googleapis.com/css [HTTP/1.1 200 OK 0ms]
00:47:26.130 GET http://www.thewindowsclub.com/Admiral-TWC-engage-assets/Windows%20Club-engage-assets/windows-club-logo.png [HTTP/1.1 200 OK 24ms]
00:47:26.134 POST XHR http://puzzlingfall.com/2ff335054e161b13a05b2962be87bf767d73b5beadab8739d933a474bd303f1b9b100b02bcadb8aa39b421787e841de626289c2146bda3e42152ae3b8f018fea023410713c3e21a00384ff7eeee977f6bf24d5091854e90e6c [HTTP/1.1 200 OK 134ms]
```

**Comment by gwarser** [comment]
Other extensions? Maybe you have CSP disabled in about:config? (For userscripts?)

**Comment by chylex** [comment]
Oh, yes it turns out `security.csp.enable` was actually turned off on both computers that I can test right now (and the third one should then have it off as well). I have no idea why it was disabled - I don't think I ever had a reason to turn if off manually on multiple computers at once. Anyway, thanks for help!
