### ISSUE TITLE
[SUGGESTION] Add Adguard Spanish/Portuguese filter

### ISSUE THREAD

**Issue by ruiumbelino** [gorhill/uBlock#3089]
I would like to suggest adding the "Adguard Spanish/Portuguese filter"(https://kb.adguard.com/en/general/adguard-ad-filters#spanish).

Thanks

**Comment by gorhill** [comment]
@ameshkov I see filters of the following form in there:

    ||mundome.com^$popup,image,~image

What is the purpose of declaring/undeclaring image type in the same filter?

**Comment by ameshkov** [comment]
As it's stated in the filter description, it was originally forked from Fanboy's Spanish, and these rules seem to be leftover from it. This odd modifiers usage reminds me of an old bug of ABP which required it.

Anyways, I don't see why we'd need these rules, removed them from the filter.
