### ISSUE TITLE
Translations: addon name

### ISSUE THREAD

**Issue by UK992** [gorhill/uBlock#309]
Translations that include addon name, should start using something like `{{addonname}}` for addon name, because its big mess, some translation using uBlock₀, µBlock, uBlock or uBlock Origin. 
And I do not know which name to use, since there are uBlock and uBlock Origin.

**Comment by gorhill** [comment]
> I do not know which name to use

As a rule, "uBlock Origin", and if conciseness is better in a specific context (depends of language etc.), use "uBlock₀".
