### ISSUE TITLE
[Firefox] [Suggestion] Add support for Firefox Contextual Identities / Containers

### ISSUE THREAD

**Issue by hermes3por3** [gorhill/uBlock#3091]
Mozilla has been experimenting with containers to slice cookies, localStorage, etc into independent blocks, unaccessible from one container to the other. It has now become an extension available to everybody.
See:
[https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers](url)
[https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/](url)
[https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/](url)

It would be wonderful to add another filtering column (in advanced mode) between global and local to include the current container. Thus, container rules supersede global rules, and local rules supersede global and container rules. Or something like that.

Firefox Cookie Autodelete addon, for example, already allows to apply rules by container.

**Comment by laurentS** [comment]
I feel that this would be a nice improvement.
Example use case:
I allow facebook in its own container, that is only used for that purpose. To make it work, I need to let it through ublock, which means that fb can now track all my other containers (cookies are not gonna be accessible there, but fb probably knows how to reconnect these "different" profiles).
Workaround:
- use a separate browser, but that defeats the purpose of containers

**Comment by deepj** [comment]
@gorhill What kind of the reason is why you don't want to support Firefox containers? You've closed 2 issues about this without some explanation. I'd be really happy if I could define separated rules for containers for more privacy and secure benefits. Thank you.

**Comment by nick75e** [comment]
@laurentS if you don't want Facebook to track you, use these:
```
||facebook.net^$domain=~facebook.com,important
||fbcdn.net^$domain=~facebook.com,important
||facebook.com^$third-party,important
||fbcdn.com^$domain=~facebook.com,important
||fb*.akamaihd.net^$domain=~facebook.com,important
```

No need to use containers.
