### ISSUE TITLE
vidlox player

### ISSUE THREAD

**Issue by mat41997** [gorhill/uBlock#3094]
site
https://a-o.ninja/anime/osake-wa-fuufu-ni-natte-kara/1

i don't can remove this
![2017-10-05 04_45_43-ballroom e youkoso 01 pl full hd a-o ninja anime pl full hd online](https://user-images.githubusercontent.com/5884000/31208904-1afdc782-a988-11e7-835d-c8861e88eb94.png)

i don't can block with this
![2017-10-05 04_42_02-ballroom e youkoso 01 pl full hd a-o ninja anime pl full hd online](https://user-images.githubusercontent.com/5884000/31208815-9de659ee-a987-11e7-81cb-1cf080e2a20b.png)

ub 1.14.8
ubpe 11.354
chrome 61.0.3163.100
win 10

![2017-10-05 04_38_11-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/31208693-076f7c20-a987-11e7-9e0c-8dd9e1487889.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gwarser** [comment]
Duplicat of https://github.com/gorhill/uBlock/issues/1744 
>This is caused by the fact that the element picker does not "drill" into embedded frames....

**Comment by gorhill** [comment]
There is not enough data to conclude it's a duplicate -- difficult to be more obscure than _"i don't can remove this"_.

**Comment by gwarser** [comment]
Cursor in top right corner of video frame.
