### ISSUE TITLE
Have some problem

### ISSUE THREAD

**Issue by tsai1225** [gorhill/uBlock#3099]
### Describe the issue

Some ads will delay blocked, probably because the rules are loaded slower, may I ask this can be resolved?

**Comment by gwarser** [comment]
>may I ask this can be resolved?

Not without details [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

Probably generic cosmetic filters https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
