### ISSUE TITLE
I need to thank for you, I think.

### ISSUE THREAD

**Issue by BEnc0de** [gorhill/uBlock#310]
Hi,
uBlock Origin and uMatrix are very very good addons, I just like them even their logo. So cute, so convenient, and I have to thank because I need to say it I think, only thanks for u, bother. I'll back u up. I want to be liked by more and more people.
Bye.
Regards.

**Comment by anewuser** [comment]
> Submit bugs/issues only. 

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Please close this issue and avoid creating new ones that aren't about bugs.
