### ISSUE TITLE
Toggle / Replace class (not style) Ex. change .md-12 to .md-4

### ISSUE THREAD

**Issue by jsEveryDay** [gorhill/uBlock#3100]
Is such thing possible with uBlock?

Im simply trying to change the class of an element from **col-md-12** to **col-md-4**
script:inject(...) doesn't do anything. Am I supposed to put a url to a js file? or inline js? I tried both. Also read that it only works with uBlock resources ... no further explanation. 

1. So is there a method to replace class? is regex replace allowed? 
2. And running your own javascript code is out of the question?

_Adguard allows:_

> rule = [domains]  "#%#" script

ex. `domain.com#%#alert("It works")`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
