### ISSUE TITLE
Investigate performance issue when looking up a cosmetic filter's origin in the logger

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#3101]
Issue first raised in <https://github.com/gorhill/uBlock/issues/2664#issuecomment-334573022>:

> 2c9c98e introduced regression in logger.
On my system (Firefox ~85k cosmetic filters) up to 7 seconds is needed for cosmetic filter details layer/dialog to appear after I click on it.
> 
> In Chromium, this is about 2s.

**Comment by gorhill** [comment]
@gwarser,

I transcribed what I see in your screenshot at <https://github.com/gorhill/uBlock/issues/2664#issuecomment-334755589>:

Regex of filter to lookup: `/[^\n]*\\*"\.googad\\*"[^\n]*/`.

Content of compiled EasyList which is scanned with above regex:

[compiled-easylist-cosmetic-filters.txt](https://github.com/gorhill/uBlock/files/1363058/compiled-easylist-cosmetic-filters.txt)

When I paste/try the regex and content at <https://regex101.com/>, after selecting "javascript" in the left hand sidebar, I get a timing of 30-40 ms withough the `g` flag, and 250-300 ms with the `g` flag (your screenshot shows over 500 ms). The (only) matching line is about 1/3 down from the beginning of the scanned content.

The result with the `g` flag is curious, given that there is only one match for that regex. Can you tell me what kind of timing you get on your side with this test?

**Comment by gorhill** [comment]
Interesting... If I add `^` and `$` at the start and beginning of the regex and use the `m` flag, the timing decrease dramatically when using the `g` flag:

    /^[^\n]*\\*"\.googad\\*"[^\n]*$/gm

**Comment by gwarser** [comment]
64ms without global `/[^\n]*\\*"\.googad\\*"[^\n]*/`
517ms with global `/[^\n]*\\*"\.googad\\*"[^\n]*/g`

36ms with `^...$` and mg `/^[^\n]*\\*"\.googad\\*"[^\n]*$/gm`
