### ISSUE TITLE
There should be an option to suppress the opening of uBlock message windows

### ISSUE THREAD

**Issue by Huygenz** [gorhill/uBlock#3103]
Let's say I setup a filter for a domain. When that domain gets opened I'll get a window like this:
http://i.imgur.com/DINi5Lu.png

It would be nice to be able to suppress this totally, even said message from uBlock.
It's fine, I did block this site, why bother me with a message about that? It may be handy in some cases, but I find it mostly annoying.

- OS/version: Windows 10
- Browser/version: Chrome
- uBlock Origin version: 1.14.8

**Comment by mapx-** [comment]
`Tip: If you wish, you may entirely disable strict blocking everywhere by adding the rule no-strict-blocking: * true to the My rules pane in the dashboard (don't forget to click Commit to make the rule stick).`

read
https://github.com/gorhill/uBlock/wiki/Strict-blocking

**Comment by gwarser** [comment]
This looks like popup, if  you set correct popup filter no message (or even window) will appear.

**Comment by Huygenz** [comment]
@mapx Thanks for your help, but I'm totally fine with strict blocking. It just would be nice to restrain uBlock from putting out this information.

@gwarser Then what am I doing wrong? Let's say I want to block everything from domain.com. What I do is I put this domain.com into my filters, [just as described here](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#hosts-files). Result is described in OP. Where's my mistake?

**Comment by gwarser** [comment]
> Where's my mistake?

Here:

[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

For **filter-related issues**, report on the respective filter list support site, or at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues). Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to diagnose/confirm filter-related issues. If something does not work properly with uBO enabled, the **first step** is to rule out filter-related issues.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
