### ISSUE TITLE
Filter lists in the ublock are not updated or downloaded.

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uBlock#3104]
ubuntu 16.04 firefox 56 (at 55 that problem was too)
Filter lists in the ublock are not updated or downloaded.
At the new clean profile they are downloaded before browser restart, and after that they can't be updated ever.
But at the latest version of umatrix 1.1.0 all filter-lists are updated or downloaded properly.
May be you can compare their code or something, I don't think that bug can be reproduced.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
