### ISSUE TITLE
Block Individual Functions in an External JS File

### ISSUE THREAD

**Issue by bbielsa** [gorhill/uBlock#3106]
### Proposal
Create a new syntax for blocking specific function(s) in an external js file. 
Example:
`$$hostname.*/script.js##offendingFunction`

#### Step-by-step 
The flow of the requests might look something like this

1. Page requests a filtered JS file.
2. uBlock Origin blocks the request from the page.
3. uBlock Origin initiates a new request which will not be blocked to retrieve the source code. 
4. uBlock Origin parses the file and replaces the filtered function with a blank function
5. uBlock Origin injects the modified script into the page

#### Forseen problems
This obviously wont block anonymous functions, but maybe uBlock Origin can offer a place to replace files manually. This would require some code editing on the users part, but is perfectly doable.

#### Examples of usefulness
I was trying to block ads on a site which used an anti-adblocker, but the site still knew the request was being blocked because the function that initiated the request rightly assumed because the request fail an ad blocker was preventing it from loading. If I had an easy way to block the offending function by specifying a file and some kind of function selector I could prevent the script from even being requested.

**Comment by gorhill** [comment]
You are assuming uBO can't deal with your undisclosed case -- you might be quite wrong. As asking in CONTRBUTING, fitler issues must be submitted at uAssets.
