### ISSUE TITLE
game spot notifaction pop ups

### ISSUE THREAD

**Issue by tsunami2311** [gorhill/uBlock#3108]
https://www.gamespot.com/articles/destiny-2-xur-location-guide-where-is-xur-what-exo/1100-6453837/

example url above but most article refering to game will at some point have pop asking to sigh email if you site on the page long enough.

https://screenshots.firefox.com/ySdHKtN8lfXvkIX9/www.gamespot.com

### Steps for anyone to reproduce the issue
1. go to gamespot.com
2. click article refering to game
3. look at article for said game and above will  happen

### Your settings

Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
I am an advanced user (required reading)

Privacy
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing 
Prevent WebRTC from leaking local IP addresses

- OS/version: windows 10
- Browser/version: 56.0 64bit
- uBlock Origin version: 1.14.10

##### Your filter lists
uBlock filters​
uBlock filters – Badware risks​
uBlock filters – 
​​uBlock filters – Resource abuse​​​
uBlock filters – Unbreak​​​​​
Easyprivacy
Easylist
Malvertising filter list by Disconnect​​​​​
Malware Domain List​​​​​
Malware domains​​​​​
Malware filter list by Disconnect​​​​​
​​Spam404​
​​​​MVPS HOSTS​​​​​
Peter Lowe’s Ad and tracking server list

#####my rules
www.gamespot.com https://static.gamespot.com/js/compiled/seamlessContent.js script block
 
(stops autofeed of articles)

I belive this can be stop if your loged to the site with an account? but if you not loged in with an account, those pop ups just keep happening.

**Comment by mapx-** [comment]
try
`||lightboxcdn.com^`

**Comment by tsunami2311** [comment]
that seem to fix it !!
I will keep eye on it to see if it some how breaks things on the site

**Comment by mapx-** [comment]
as a rule:
`* lightboxcdn.com * block`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
