### ISSUE TITLE
v1.14.12 doesn't show control pannel in Firefox android 56.

### ISSUE THREAD

**Issue by cusn** [gorhill/uBlock#3109]
v1.14.12 doesn't show control pannel in Firefox android 56.

**Comment by gorhill** [comment]
What's the purpose of release notes?

**Comment by cusn** [comment]
Oh,thank you.

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1364945

**Comment by cusn** [comment]
But there is a problem：
It has no effect when I click "uBlock Origin"(uBO's entry in the browser) just now.It returns to normal after uninstalling all other extensions.

Then I install uBO first,and then　install other extensions，it works well.

**Comment by gorhill** [comment]
Are your other extensions legacy add-ons?

Create a bookmark for the dashboard after you open it. Then you should be able to access the dashboard whenever you want using that bookmark. Hopefully all glitches will be gone with FF57.

**Comment by cusn** [comment]
CanvasBlocker belongs to WebExtension。When installing only CanvasBlocker and uBlock Origin, above problems occur if uBlock Origin is not installed first.
