### ISSUE TITLE
Unable to turn off Twitch commercial notification

### ISSUE THREAD

**Issue by Maxhype** [gorhill/uBlock#311]
![untitled](https://cloud.githubusercontent.com/assets/12036035/8025496/42262446-0d61-11e5-99a7-db1c921d82d3.png)

There used to have a X button where you could close that commercial notification.

**Comment by anewuser** [comment]
uBlock just provides the technology to block ads and other elements. It's up to the lists to actually block them. Report this problem directly to the maintainer(s) of the lists you use.

**Comment by gorhill** [comment]
You have a URL where I can get exactly what is in your screenshot?

Also: browser version, uBlock version, filter lists in effect, custom filters + any other setting which is not default one.

**Comment by gorhill** [comment]
Related: <https://adblockplus.org/forum/viewtopic.php?f=2&t=34166>.

**Comment by SW1FT** [comment]
No one could "fix" this yet.

Related: https://adblockplus.org/forum/viewtopic.php?f=2&t=21235

**Comment by gorhill** [comment]
Fanboy's filter is better, the user posted two filters which overlap:

    twitch.tv##.sub-upsell

**Comment by gorhill** [comment]
Closing, because this is a filter list issue.
