### ISSUE TITLE
Static filtering: left-anchor / right-anchor

### ISSUE THREAD

**Issue by john103** [gorhill/uBlock#3110]
### Steps for anyone to reproduce the issue

1. install uBlock Origin, restart browser
2. Add filter:
```
|https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.pn|$image,domain=github.com
```
3. Open uBlock Origin logger.
4. Visit: https://github.com/gorhill/uBlock

### Expected results:
https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.png is not blocked.

### Actual results:
https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.png is blocked.

### Your settings
new profile
- Browser/version: Firefox 56.0
- uBlock Origin version: 1.14.10

##### Your filter lists
default

##### Your custom filters (if any)
```
|https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/icon38@2x.pn|$image,domain=github.com
```

**Comment by gwarser** [comment]
If I'm searching right, I see only these two filters in 43 filter lists 
```
1.txt:|http://wimg.yandex.net/12/54/t-12542.png|
liste_fr.txt:|data:,|$popup
```
1.txt is Adguard Russian filter
