### ISSUE TITLE
cloud syncing not working anymore

### ISSUE THREAD

**Issue by lemmy04** [gorhill/uBlock#3113]
### Describe the issue
Since (i think) the update for mozillas new extension architecture cloud-syncing ublock origin settings between devices has stopped working.

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
setup mozilla sync
enable cloud support in ublock origin
observe that there are no settings to be imported, even after manually triggering a mozilla sync

### Your settings

- OS/version: any. Windows 10, openSUSE Leap 42.2, openSUSE Leap 42.3, RHEL 7.4
- Browser/version: 52.4.0 ESR on RHEL, latest available on Windows 10, 52.4.0 ESR on openSUSE
- uBlock Origin version: uBlock Origin v1.14.14

##### Your filter lists
default + DEU

##### Your custom filters (if any)
none so far since it's not syncing.

**Comment by gorhill** [comment]
> observe that there are no settings to be imported

Because Firefox sync storage for the new webext architecture is not shared with the legacy one. You will have to push again your data in the cloud. There is nothing uBO/webext can do, it does not have access to legacy cloud storage.

**Comment by gorhill** [comment]
Also, duplicate of #3022.

**Comment by lemmy04** [comment]
...so? even *with* manually pushing once every instance of FF only sees its own data. I cannot sync between different machines.

**Comment by lemmy04** [comment]
got it nailed. Having FF 52 ESR was the issue. I updated Firefox on my linux systems to FF 56 (same as on windows) and *pop* it syncs properly now.

**Comment by gorhill** [comment]
Right, sync storage was added in Firefox 53: <https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage#Browser_compatibility>. Not available in Firefox for Android.

**Comment by lemmy04** [comment]
I guess I better file tickets with Red Hat and SUSE requesting they update their ESR versions to something newer.

**Comment by alexolog** [comment]
So those of us that are on the ESR track are stuck on 1.13.8?

**Comment by andreasstieger** [comment]
SUSE will stay on ESR for their Enterprise and stable Leap releases.

**Comment by alexolog** [comment]
@gorhill, is there any way to support sync on 52ESR?  Maybe fallback to the old method?
