### ISSUE TITLE
Disqus not working on a specific website

### ISSUE THREAD

**Issue by w-biggs** [gorhill/uBlock#3114]
### Describe the issue

Disqus no longer works for me on Weather Underground; it works on other pages, though. All images and embeds are blocked. This began happening a few weeks ago.

### One or more specific URLs where the issue occurs

https://www.wunderground.com/cat6/nate-sweeps-across-us-gulf-coast

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/3406010/31348349-611dd4d8-aced-11e7-8de3-d35c3dacdcb5.png)

### Steps for anyone to reproduce the issue

1. Just enter the site, scroll down and try to use Disqus.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- uBlock Origin version: 1.14.8

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

```
#Hide the "advertise on twitter" box
twitter.com##.Footer-adsModule
```

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
