### ISSUE TITLE
Order of My Filters

### ISSUE THREAD

**Issue by henrikenberg** [gorhill/uBlock#3115]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

As far as I can ascertain, the filters in "My Filters" are applied _before_ the filters I subscribe to, making overriding them impossible. This should probably not be the state of affairs.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  Windows 7
- Browser/version:  Chrome 61.0.3163.100
- uBlock Origin version:  1.14.8

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
