### ISSUE TITLE
[Firefox] Incorrect popup size on a scaled screen

### ISSUE THREAD

**Issue by searly4** [gorhill/uBlock#3116]
### Describe the issue
When the uBlock icon is clicked, the popup displays with the incorrect size and clips some of the contents. This occurs when the browser window is on the secondary screen and that screen is configured in Windows to use a different scaling than the primary screen. When the browser window is on the primary screen, the popup displays normally.

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/20506636/31371486-edcbafec-ad45-11e7-818c-968664eb0787.png)

### Steps for anyone to reproduce the issue

1. On a system with 2 or more monitors, verify monitors have different scaling settings
2. Place the uBlock icon on the toolbar
3. Move the browser window to the secondary display
4. Click the uBlock icon, popup should have incorrect size
5. Move the browser window to the primary display
6. Click the uBlock icon, popup should have correct size (usually, sometimes retains odd size)

### Your settings

- OS/version: Windows 10 x64 1703
- Browser/version: Firefox 57.0b6
- uBlock Origin version: 1.14.14
- No other extensions enabled
- Primary (left) screen: 3840 x 2160, 150% scaling
- Secondary (right) screen: 1920 x 1080, 100% scaling

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=624992

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1387340
