### ISSUE TITLE
Filters Update

### ISSUE THREAD

**Issue by Anoop2609** [gorhill/uBlock#3117]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Filters are not updating automatically. Last filter update is 2 day ago

- OS/version: Windows 10
- Browser/version: Nightly FF 58
- uBlock Origin version: 1.14.14

##### Your filter lists
Default filter lists,hpHosts’ Ad and tracking servers, Adguard Base filter, Adguard Spyware, Fanboy’s Annoyance List
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Betsy25** [comment]
I think that's quite normal, someone correct me if I'm wrong but I think the default update period is every 3 days, except for when the list contains a longer expiration period.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
