### ISSUE TITLE
generated cosmetic filters (using element picker)

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#3119]
windows 10

uBo 1.14.8 / 1.14.11.114 chrome 62/ firefox 57
default filters setup

go to `http://www.businessinsider.fr/free-attaque-netflix-en-justice-france-debit`

at the bottom there is an ad (contenu sponsorisé)

I used the element picker mode to create a cosmetic filter

![cos1](https://user-images.githubusercontent.com/10303732/31403473-77cafd2a-adf9-11e7-86be-c469b59e0f0b.png)
I wanted to select the relevant part - clicking on the third row - (`tag-sponsored-content` class) but what i get is only the first part (`post-48422 div`)

Is it by design or it's some regression ?

**Comment by gwarser** [comment]
Problem with UI?

When you click, most efficient selector for **this one** element will be chosen - ID (`#post-36410`) is best for selecting one element. If ID is missing full path will be used.

I you want to select similar elements, use ctrl-click.

**Comment by mapx-** [comment]
thanks, ctrl-click is doing what I intented.
