### ISSUE TITLE
cosmetic: order of eraser/padlock

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [gorhill/uBlock#3121]
In uBo's panel when you make changes from the saved state, you get an eraser and padlock, in that order left to right. In uMatrix, the panel displays padlock then eraser. I am not a UI expert, and heavens forbid we **upset people's muscle memory** (I suspect its way too late to the party to change now) .. but ... for consistency, shouldn't these be in the same order?

Just a thought :) Feel free to close

**Comment by gorhill** [comment]
These are two different extensions, I never created them to specifically be used together. At this point I rather not change the UI of either just for the sake of consistency across unrelated extensions (aside that they came from the same author). Generally, I just put the padlock closer to where I think the rule setting is likely to be done, as I expect the padlock to be used most.
