### ISSUE TITLE
'...' next to export button

### ISSUE THREAD

**Issue by jony0008** [gorhill/uBlock#3123]
What are the dots doing there next to the export button?

![skarmbild fran 2017-10-11 07-20-10](https://user-images.githubusercontent.com/23194385/31423407-f1bcd666-ae54-11e7-9298-20c15face449.png)

**Comment by gwarser** [comment]
Placeholder - nothing is exported jet.

Please close this issue, and read [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) before opening new one.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
