### ISSUE TITLE
ebay not working with uBlock

### ISSUE THREAD

**Issue by waza123x** [gorhill/uBlock#3124]
Just try to surf ebay.com or ebay.co.uk with enabled addon uBlock and links will stop working.
If you DISABLE(in addons section) addon uBlock, ebay will work fine.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sp00n** [comment]
I had the same problem with Firefox Unbranded Nightly 54.0.2 64bit on Win7x64 and version 1.14.14. Ublock was even set to "off" (but not disabled) for ebay, but the pages still wouldn't load the new content, which was driving me nuts.

I've now switched to the pre-release version 1.14.15b0 that was just released, and it started working again.
