### ISSUE TITLE
Not working on ultrahorny.com

### ISSUE THREAD

**Issue by thrwat** [gorhill/uBlock#3126]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Ultrahorny.com is blocking the adblocker

### One or more specific URLs where the issue occurs

ultrahorny.com

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Use UBO
2. Get Blocked
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Win 10
- Browser/version: Chrome 61
- uBlock Origin version: latest

##### Your filter lists

Default

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
