### ISSUE TITLE
Specific $popup filters incorrectly converted to $popunder

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#3129]
First reported here http://forums.mozillazine.org/viewtopic.php?p=14770533#p14770533 and https://github.com/uBlockOrigin/uAssets/issues/759

### Describe the issue
uBlock Origin 1.14.14
SeaMonkey 2.49.1

Steps to reproduce -

1) add this filter

    `||adobe.com^$popup`

2) visit http://get.adobe.com/flashplayer/about/
3) in the right sidebar of the page, left-click the link "Games".

Result: Link opens in a new tab, as expected, but the original tab is closed. Logger reports this -

    ||adobe.com^$popup   --   popunder   http://get.adobe.com/flashplayer/about/

**Comment by Hrxn** [comment]
Is this SeaMonkey specific?

**Comment by gorhill** [comment]
Issue is in the core code, it happens with Chromium as well.

**Comment by gwarser** [comment]
In https://github.com/uBlockOrigin/uAssets/issues/759 @mihp reported:


- Browser/version: Firefox Nightly 58.0a1 (2017-10-12) (64-bit)
- uBlock Origin version: uBlock Origin 1.14.14
- URL `http://www.triglav.si/zavarovanja/posamezniki/zavarovanja_na_potovanjih/zdravstveno-zavarovanje-na-potovanjih-v-tujini-z-asistenco/zdravstveno-zavarovanje-na-potovanjih-v-tujini-z-asistenco`
- Middle click the red button with text "Sklenite zavarovanje - popust do 20 %" that leads to `https://skleni.triglav.si/isklepanje/zdravstveno/`
- Filter is `||triglav.si/$popup` found in: SVN: Slovenian List

**Comment by joey04** [comment]
I updated my Pale Moon 27.5 to latest 1.14.15b1 and tested this. The Adobe popup isn't blocked at all, even with `*$popup`, but it does block popups on other sites.
But in Chrome with 1.14.8 it blocks the Adobe popup.
