### ISSUE TITLE
uBlock Origin do not update title filter when filter edited

### ISSUE THREAD

**Issue by phuc365** [gorhill/uBlock#313]
<b>I speak English very bad, i hope you understand :D</b>

<b><i>1) </i></b>I have used filters that its title changed regularly.

<i>e.g:</i> http://abpvn.com/filter/abpvn-55751a98da3e6.txt

I also realized title of filters has changed recently.

<i>e.g:</i> Anti-Adblock Killer => <b>now:</b> AakList

<b><i>2) </i></b>Why not combine them into one?

http://s24.postimg.org/6oy3zh7d1/image.png

<b><i>3) </i></b>Why is there an overlap like this?

http://s14.postimg.org/5rhyaictd/image.png

<b>Thank you for your interest.</b>

**Comment by gorhill** [comment]
> 2) Why not combine them into one?

Because I want it this way -- users can pick only filter lists which are used for a specific purpose.
