### ISSUE TITLE
suspendTabsUntilReady and Violentmonkey compatibility issue.

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#3130]
### Describe the issue

When restoring session current page load is aborted when `suspendTabsUntilReady` is enabled along with Violentmonkey extension.  

I'm reporting this on uBO issue tracker, but I haven't looked into details so it might be as well Violentmonkey fault. /CC @gera2ld

### Steps for anyone to reproduce the issue

1. Set `suspendTabsUntilReady` to `true` and enable Violentmonkey  extension.
1. Open any page and restart the browser. Make sure session restore is enabled.
1. Page load is aborted and `about:blank` page is displayed instead.

### Your settings

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.14.14
- Violentmonkey  version: 2.8.13

**Comment by gwarser** [comment]
I don't think this is Violentmonkey. I can reproduce on clean profile. Mentioned this month ago https://github.com/gorhill/uBlock/issues/2970#issuecomment-327030447

**Comment by uBlock-user** [comment]
> Mentioned this month ago #2970 (comment)

That appears to be limited to FF. Can't reproduce on Chromium 63.

**Comment by gorhill** [comment]
Anybody has verified whether this also occurs with Firefox 56 (stable)?

**Comment by gwarser** [comment]
Works only in ESR

**Comment by gwarser** [comment]
It's working on Nightly, when I set `extensions.webextensions.remote;true`.
Looks weird - page is refreshed 1-3 times (white flashes).
