### ISSUE TITLE
Unable to install on Seamonkey 2.48

### ISSUE THREAD

**Issue by mzs114** [gorhill/uBlock#3131]
### Describe the issue
Unable to install uBlock  addon from official mozilla addons website on version 2.48. I was able to install an old version 1.13.8 and it is working fine at the moment.

### One or more specific URLs where the issue occurs

https://addons.mozilla.org/En-us/seamonkey/addon/ublock-origin/versions/

I had to use the "View other versions" URL as the above addon URL was getting redirected to below Andorid url, not sure why this is happening as this is the first time I am experiencing this.

https://addons.mozilla.org/En-us/android/addon/ublock-origin/

### Screenshot in which the issue can be seen

![ublock-1-14](https://user-images.githubusercontent.com/5303615/31548312-12e26014-b048-11e7-8c4a-709f09fdedad.png)

### Steps for anyone to reproduce the issue

1. Install latest stable version of Seamonkey - 2.48
2. Search for 'uBlock origin for seamonkey' on the web, click open the mozilla addon page
3. It might be redirected to Andorid addons page, in this click on 'View other versions'.
4. Try to install most recent available addon from the list.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Tested this on two OS - Debian 8 and FreeBSD 11, both 64 bit
- Browser/version: Seamonkey 2.48
- uBlock Origin version: Versions above 1.13.8 are not getting installed with the Corrupt message pop up

##### Your filter lists

N/A

##### Your custom filters (if any)
N/A

**Comment by gorhill** [comment]
uBO/webext is not compatible with Sea Monkey 2.48. AMO serves uBO/webext.

**Comment by mzs114** [comment]
I am sorry I did not understand what AMO is. So uBlock is not supported on Seamonkey anymore?

**Comment by gorhill** [comment]
AMO = `addons.mozilla.org`.

See <https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#future-of-ubolegacy>.
