### ISSUE TITLE
Custom filterlist in Firefox

### ISSUE THREAD

**Issue by FTno** [gorhill/uBlock#3132]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Add local custom filterlist:
file:///C:/customlist.txt

It is added to the Custom group, but shows '0 used out of 0', and then clicking on it to open the filterlist file in a new tab it is just a blank page.

I then tried with the old legacy Ublock origin 1.13.8 instead and it worked fine then.

(A test with v.1.14.14 and Firefox 57.0b3 resulted in the same problem as with 56.0.1.)

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Win 7 64
- Browser/version: Firefox 56.0.1
- uBlock Origin version: 1.14.14

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Default

**Comment by gorhill** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1266960>.
