### ISSUE TITLE
[regression] Popup blocking

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#3133]
I reported this yesterday as a comment in #3129 but it's a separate issue so filing a new one here.

The global rule `*$popup` does not block all popups in the latest 1.14.15b1, but it does in 1.14.8. (For examples, see #3129)

The regress occurred in #2919, which was fixed after 1.14.8 was released. The root cause is [this assumption](https://github.com/gorhill/uBlock/blob/69241fb3db078fb9e72fca9479ecee327aa67390/src/js/tab.js#L760) in the latest code.

I commented out the `areDifferentURLs` check, and now my modified 15b1 blocks all popups with that rule.

I consider this a regression, because if I tell uBO to block all popups it should do so. Just like any other request type.

**Comment by gorhill** [comment]
The popup tab is not blocked because it matches the URL clicked.

**Comment by joey04** [comment]
In terms of actual browsing, I would agree that you would want to not block those types of popups. But I think uBO should block those if told to do so.

**Comment by gorhill** [comment]
You will have to argue this with those who think differently: <https://github.com/gorhill/uBlock/issues/2919>. This is not an isolated case, new tabs being closed unexpectedly is an old recurring complaint.

**Comment by joey04** [comment]
Another consideration:
Removing the URL check has the advantage of blocking undesired popups instantly. An example is [thepiratebay.org](https://thepiratebay.org/browse/601) which opens popups with about half the clicks I make on the site. (Using my own rule set which is not as thorough as EasyList in this particular case since I hadn't been to that site in a long time. I saw it mentioned as a popup problem on the uAssets issue tracker which is why I'm using it as an example case, since they'll likely change their methods again.)

With the revert, it nukes them at the very beginning (the initial about:blank), but before it was allowing the popup to open and run a script before detecting it and closing the popup tab. So it did block the popup pretty quickly, but the instant method is preferred.

**Comment by joey04** [comment]
I won't argue your decision, since I realize that there are various types of popups and trade-offs. But for my own use I'll be keeping this revert as one of my uBO patches.

**Comment by gorhill** [comment]
> Removing the URL check has the advantage of blocking undesired popups instantly

There is no such thing as _instantly_ with the webext API, it's all asynchronous, and so is [`browser.tabs.remove`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/remove).

That being said, there is no issue with uBO blocking as soon as it can if the popup opened is `about:blank`:

![a](https://user-images.githubusercontent.com/585534/31578039-51d5e9ae-b0e7-11e7-9cd7-62bdd5afb7d7.png)

**Comment by joey04** [comment]
I'm using Pale Moon, so not webext. My word "instantly" is probably better stated "as fast as possible". In this case my logger looks just like your picture. The initial about:blank is blocked.

**An idea:** what about making this URL check optional with an Advanced setting? By default it would do the check but then obsessive folks like me could change it with the setting. That way all bases are covered here.
