### ISSUE TITLE
No way to reset filter usage counts

### ISSUE THREAD

**Issue by alanbur** [gorhill/uBlock#3136]
There appears to be no way of resetting the filter usage counts, not even uninstalling and reinstalling uBlock does it. Being able to do this would help users evaluate which filter lists are currently the most useful for them, "since first install" counts don't allow that. I'm assuming there's a space/speed cost for additional filters so being able to restrict filter lists to just the ones that best fit your particular browsing patterns would have performance benefits as well.

**Comment by uBlock-user** [comment]
There's no such thing as `filter usage count` in uBO. There's a network requests blocked count which appears when opening UI popup.

**Comment by gorhill** [comment]
There is no such thing as "filter usage counts", so of course there is no reset for something which does not exist.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by alanbur** [comment]
The counts I'm referring to are the "XXX used out of YYY" counts on the "3rd-party filter" tab:

![counts](https://user-images.githubusercontent.com/419189/31585912-9cbeaeee-b1c1-11e7-8a77-810bfd914405.png)

**Comment by gorhill** [comment]
> The counts I'm referring to are the "XXX used out of YYY" counts on the "3rd-party filter" tab

Then I can't make sense of your request. What does "reset" really means here?

**Comment by alanbur** [comment]
> Then I can't make sense of your request. What does "reset" really means here?

Set the "XXX" value back to zero. I assume the XXX counts refer to the number of times filters from the associated file have been used to block something? If not, what *does* that value refer to?

**Comment by gorhill** [comment]
[Dashboard: 3rd party filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters):

> uBlock Origin discards duplicate filters, so the **number of filters used within a filter list** depends on how many duplicate filters were detected within that filter list.

**Comment by alanbur** [comment]
Ah, thanks - that makes sense - I was assuming it was the number of times rules from a file had blocked something, not the number of non-duplicate rules. I know you can see the counts of items blocked on each page, is there any way of seeing global counts per filter file?

**Comment by gorhill** [comment]
> is there any way of seeing global counts per filter file?

No.

That is <https://github.com/gorhill/uBlock/issues/1353>.

_That_ sort of feature is a performance-degrading one, and that is why I have repeatedly [declined to implement it](https://github.com/gorhill/uBlock/issues/983). Also, turns out this feature was changed to disabled by default in ABP for Firefox for performance reasons (see their tracker), and is no longer present in the webext version of ABP.

**Comment by alanbur** [comment]
If it would be a performance hog then, yes, that sounds like the right call - at best it would have to be optional-off. Thanks for the explanations, and thanks for UBO!
