### ISSUE TITLE
Can't post on https://answers.microsoft.com/fr-fr/

### ISSUE THREAD

**Issue by S3ndG** [gorhill/uBlock#3137]
Ublock origin causes issues on thes forums. If I disable it via the extension, the problem still happens. If I disable the extension in about:addons, **the problem doesn't happen**.

URL : https://answers.microsoft.com/fr-fr/newthread?threadtype=Questions&cancelurl=%2Ffr-fr

### Screenshot in which the issue can be seen
https://screenshots.firefox.com/qkzOZYym5kVuBg7V/answers.microsoft.com

### Steps for anyone to reproduce the issue
Go to the webpage, try to post a new thread. You get that error message (in french) : {"ErrorMessage":null,"IsError":false,"Result":{"message":"Le message doit comprendre entre 6 et 60 000 caractères."},"Success":false,"CorrelationVector":null,"DependencyCorrelationVector":null}

### Your settings
- OS/version:  windows 8.1 64 bit
- Browser/version:  firefox 56.0.1 64 bit
- uBlock Origin version:  1.14.14

##### Your filter lists
It doesn't matter about this problem.

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/issues/2990

**Comment by S3ndG** [comment]
OK thanks so it's fixed in FF 57+... I will have to be a bit patient :/
>You can close the bug report :-)

**Comment by mapx-** [comment]
close it yourself :)
