### ISSUE TITLE
facebook images not opening

### ISSUE THREAD

**Issue by carlos19silva94** [gorhill/uBlock#3138]
Hi, facebook images shown in posted links are not showing up.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment]
`@@||fbcdn.net/safe_image.php?$image,domain=facebook.com`

**Comment by carlos19silva94** [comment]
yeah, thats it. thanks
