### ISSUE TITLE
Element picker doesn't work on youtube.com

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#314]
[Chromium for Win64](http://chromium.woolyss.com/download/)
[Youtube app](https://chrome.google.com/webstore/detail/youtube/blpcfgokakmgnkcojhhkbfbldkacnbeo)

**Comment by CrisBRM** [comment]
Tried using that specific version of Chromium, using the web store version of uBlock (0.9.8.6). It worked just fine.

0.9.8.7 gives me this error: 
    var onExternalFileError = function() {
        console.error(errorCantConnectTo.replace('{{url}}', path));
        cachedAssetsManager.load(path, onCachedContentLoaded, onCachedContentError);
    };

js/assets.js:882 (onExternalFileError)
js/assets.js:312 (onErrorReceived)

However, it also worked.

**Comment by mikhaelkh** [comment]
@CrisBRM, it turns out you need official [Youtube app](https://chrome.google.com/webstore/detail/youtube/blpcfgokakmgnkcojhhkbfbldkacnbeo) installed

**Comment by CrisBRM** [comment]
It's funny, because that isn't even an app, it's literally just a link to youtube, but it does break the element picker. Here's the console output:

![gorhill](https://cloud.githubusercontent.com/assets/9098352/8120104/7f7fa328-1093-11e5-83cf-7ca895995f2c.png)

**Comment by gorhill** [comment]
I installed [Youtube app](https://chrome.google.com/webstore/detail/youtube/blpcfgokakmgnkcojhhkbfbldkacnbeo), and tried the picker and it worked fine. Chromium 43/Linux.

**Comment by mikhaelkh** [comment]
Now element picker works fine.
