### ISSUE TITLE
Prevents proper page loading on localhost

### ISSUE THREAD

**Issue by ygoe** [gorhill/uBlock#3141]
### Describe the issue

My website works fine on the public domain. But in my local XAMPP environment, hosted on localhost, no page loads when clicking on an internal link from one page to another. The URL changes, but neither the page title nor the page content. Not even navigating to another local site bookmark does load anything. Only after pressing F5 the page is loaded and displayed correctly. When the page isn't loaded, mouse gestures (Gesturefy add-on) are also not working in the tab. Otherwise they do.

Restarting Firefox doesn't help.

Disabling only this extension resolves the issue immediately.

### One or more specific URLs where the issue occurs

http://localhost/mydomain

### Screenshot in which the issue can be seen

Nothing interesting to see. Whatever was displayed before remains on the screen. No other page is ever loaded unless F5 is pressed.

### Steps for anyone to reproduce the issue

1. Load the page on http://localhost/mydomain
2. Click on any internal link (external links to other hosts will load just fine)
3. Open another site from a bookmark, like http://localhost/otherdomain

### Your settings

- OS/version: Windows 10.1607 x64
- Browser/version: Firefox 56.0.1 x64
- uBlock Origin version: 1.14.14

##### Your filter lists

Default; but the add-on does not report anything blocked on my page anyway.

##### Your custom filters (if any)

```
||google-analytics.com^$third-party
||googleadservices.com^$third-party
||facebook.net^$third-party
||facebook.com^$third-party
||twitter.com^$third-party
||instagram.com^$third-party
||ioam.de^$third-party
```

**Comment by ygoe** [comment]
PS: Whitelisting the domain "localhost" does not change anything.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext

**Comment by ygoe** [comment]
I have disabled all other legacy extensions and restarted Firefox. Still just one process. Still loading/rendering failure. What else can I try?

**Comment by mapx-** [comment]
Perhaps you should use FF 57 (eventually test the portable one)

**Comment by gorhill** [comment]
> I have disabled all other legacy extensions and restarted Firefox. Still just one process. Still loading/rendering failure. What else can I try?

You seems to have ignored the other Firefox issues mentioned in there (which are fixed in FF57). You will need to investigate more on your side to make a solid case that uBO is causing your issue, and not one of the various bug still in FF56.

**Comment by gorhill** [comment]
Due to the too many invalid issues being opened, limiting the issue tracker to contributors for the time being.
