### ISSUE TITLE
Unable to install in Seamonkey - corrupt add on

### ISSUE THREAD

**Issue by RayLennox** [gorhill/uBlock#3143]
### Describe the issue

I am unable to install uBlock Origin on Seamonkey 2.48

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

https://addons.mozilla.org/En-us/firefox/addon/ublock-origin/

### Screenshot in which the issue can be seen

![corrupt](https://snag.gy/SEb56r.jpg 'corrupt')

### Steps for anyone to reproduce the issue

1. Install the current stable build of Seamonkey browser (2.48)
2. Search for "ublock origin seamonkey" and click through to the following page: https://addons.mozilla.org/En-us/firefox/addon/ublock-origin/
3. Click the "Add to Firefox" button.

Expected: Add on to be installed

Actual: Add on install stops because the add on is corrupt, see screenshot.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: windows 7 x64
- Browser/version: Seamonkey 2.48 (20170707010522)
- uBlock Origin version: 1.14.14

##### Your filter lists

n/a

##### Your custom filters (if any)
n/a

**Comment by uBlock-user** [comment]
- >> https://github.com/gorhill/uBlock/issues/3131

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
