### ISSUE TITLE
Ad "Get to Google faster. Switch your default search engine to Google."

### ISSUE THREAD

**Issue by sogen** [gorhill/uBlock#3144]
### Describe the issue
Pop-up ad 

### One or more specific URLs where the issue occurs
Google.com

### Screenshot in which the issue can be seen
![screen shot 2017-10-17 at 11 30 49 pm](https://user-images.githubusercontent.com/2784323/31702333-96422f7c-b393-11e7-80b5-1f28a7b7a330.png)

### Steps for anyone to reproduce the issue
1 .- Use **Safari** or **Firefox**
2.- **Visit Google.com**

### Your settings
OSX Sierra
Safari: Version 11.0 (12604.1.38.1.7)
Safari ublock: uBlock Origin 1.14.14
Firefox: 56.0 (64-bit)
Firefox Ublock: uBlock Origin 1.14.14

##### Your filter lists

- All the ones that start with "Ublock filters"
- Adblock Warning Removal List​
- Adguard Base Filters​
- EasyList
- EasyPrivacy​​​
- Fanboy’s Enhanced Tracking List
- Spam404
- All the Annoyances filters (5)
- MVPS hosts

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
