### ISSUE TITLE
nana10.co.il video player no pause in firefox with no filters enabled

### ISSUE THREAD

**Issue by EasyListHebrew** [gorhill/uBlock#3145]
### Describe the issue
using uBlock Origin v1.14.14 on firefox 56.0 **with no filters enabled even if ublock is disabled on site**, the pause\play not working.

### One or more specific URLs where the issue occurs
http://news.nana10.co.il/Article/?ArticleID=1269195&sid=126
http://news.nana10.co.il/Article/?ArticleID=1269587&sid=126

### Screenshot in which the issue can be seen
<a href="https://ibb.co/dGEe5m"><img src="https://preview.ibb.co/iu0K5m/ublock.png" alt="ublock" border="0"></a>

### Steps for anyone to reproduce the issue

1. go to one of the urls
2. try to pause the video

### Your settings
- OS/version:  windows 10 64 bit
- Browser/version:  firefox 56.0
- uBlock Origin version:  v1.14.14 

##### Your filter lists
not relevant

**Comment by gorhill** [comment]
I can't get the video to play even without uBO.

Did you try to further narrow down to make the case it's really a uBO issue?

- Did you try without uBO enabled in `about:addons`?
- Did you try with another webext-based blocker (Adguard, Privacy Badger)?

**Comment by gwarser** [comment]
I can reproduce in 56.
Third party cookies are required.
Work fine in 57.

**Comment by mapx-** [comment]
I can reproduce the issue in FF 55 + uBo 1.14.14

error in console: `TypeError: this.player is null`

working fine in FF 57

**Comment by gwarser** [comment]
Page is using synchronous XMLHttpRequest.

**Comment by EasyListHebrew** [comment]
issue doesn't happen when disabling ublock in ff settings.
also happens with AdblockPlus
didn't yet check FF 57

**Comment by EasyListHebrew** [comment]
works with FF57
issue solved
thanks @mapx-
