### ISSUE TITLE
[Firefox] The extension doesn't work in addons.mozilla.org website

### ISSUE THREAD

**Issue by temporaryaccount** [gorhill/uBlock#3146]
### Describe the issue

The blocking doesn't seem to work for any page under https://addons.mozilla.org. I can see the requests going to Google Analytics in Developer Tools and about:networking.

uMatrix has the same issue.

### One or more specific URLs where the issue occurs

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Steps for anyone to reproduce the issue

1. Open uBlock Origin's (or uMatrix's) Logger window
2. Open a new tab
3. Press F12 to open Developer Tools
4. Open the Network tab in the Developer Tools
5. Choose the "Images" filter under the Network tab (optional)
6. Visit https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
7. Observer the requests, https://ssl.google-analytics.com/r/__utm.gif is being accessed while it's being shown as blocked (in red) in the Logger window

### Your settings

- OS/version: Ubuntu
- Browser/version: FF 56.0.1
- uBlock Origin version: Latest from AMO

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
Firefox disable installed WebExtensions on `addons.mozilla.org`, so that no extensions can interfere with the site, by design.

**Comment by temporaryaccount** [comment]
Thanks, this is frustrating though. Is it possible to disable this "feature" using about:config? If not, can you please show me the discussion which led to this decision in Mozilla's issue tracker or mailing lists?

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1310082

**Comment by temporaryaccount** [comment]
Thanks, so it seems the next version of Firefox (57) will have an option to disable this behavior by setting privacy.resistFingerprinting.block_mozAddonManager to true.

**Comment by gwarser** [comment]
I wonder if this have any side effects. @gorhill this is worthy mentioning in wiki.
