### ISSUE TITLE
ublock in PM: no button; no prefs; no pop ups - is it doing anything?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [gorhill/uBlock#3149]
I installed ublock from the Pale Moon site. The only button I saw in the customize dialog that I didn't recognize was "Activity Indicator". I dragged it to a tool bar & I've never seen it again. I tried stretching the window way out, but it isn't there. The only pref setting is for updating prefs. Nothing under the tools menu. I've seen no popups from it. This is in Ubuntu 16.04 under Open Box, no further DE, under X. Is there some likely way for me to fix this?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
