### ISSUE TITLE
Easy List Inserting Ad and Porn Links

### ISSUE THREAD

**Issue by ViperDaimao** [gorhill/uBlock#315]
The Easy List filter in the Chrome uBlock settings is injecting spam and porn links in webpages I save to my desktop and possibly more. 

When I right click on a page and hit save as, I see

```
[href^=”http://www.linkbucks.com/referral/”],
[href^=”http://www.faceporn.net/free?”]
{display:none !important;}
```

added to the html code of the page I save. 

I tested by having parse and enforce cosmetic filters on and then having the EasyList (adblockplus.org) filter checked. Found a webpage and hit save as to save it to an html file. Open it up in notepad and see the links added on to the html. Then I uncheck the EasyList, hit apply changes, reload my web page and save as again. This time I don’t see any added spam links.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/About-that-CSS-selector-with-%22www.faceporn.net%22-in-it...

**Comment by gorhill** [comment]
> injecting spam and porn links

These are not "spam and porn links", these are CSS selectors, used in a `style` tag -- very different. Explanation at https://github.com/chrisaljoudi/uBlock/issues/161 as pointed out by @gwarser.

**Comment by asl97** [comment]
It doesn't matter what they are call, it is fairly clear that this is an (small) issue cause they are unwanted stuff that get saved along with the pages.

iirc, stuff in the shadow DOM doesn't get save with the pages so those CSS selectors and other stuff should go in there.
