### ISSUE TITLE
NoCoin list?

### ISSUE THREAD

**Issue by despicere** [gorhill/uBlock#3151]
Need support for an updated list, like this one https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt

**Comment by gwarser** [comment]
Only these are not included in UBO:

```
*://minecrunch.co/web/*
*://coinerra.com/lib/*
*://miner.pr0gramm.com/xmr.min.js*
*://kiwifarms.net/js/Jawsh/xmr/xmr.min.js*
*://anime.reactor.cc/js/ch/cryptonight.wasm
*://joyreactor.cc/ws/ch/*
*://kissdoujin.com/Content/js/c-hive.js*
*://minero.pw/miner.min.js*
```

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
