### ISSUE TITLE
uBlock blocks contents of outside message in automatic replies in mailing in Office365.

### ISSUE THREAD

**Issue by RobertZXR** [gorhill/uBlock#3152]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
In the last Firefox uBlock blocks display **contents** of outside message in automatic replies in mailing in Office365, despite including outlook.office365.com in whitelist.

It works bad even uBlock is disabled for current page, but it works fine when uBlock is disable completely.

### One or more specific URLs where the issue occurs
https://outlook.office365.com/owa/?realm=[xxxxx]&exsvurl=1&ll-cc=1033&modurl=0&path=/options/automaticreplies/mode/popup
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
**From user account:**
![image](https://user-images.githubusercontent.com/32954207/31813505-eeca5dd2-b586-11e7-847c-61f9214f9689.png)

**From admin account:**
![image](https://user-images.githubusercontent.com/32954207/31813533-0e5231fc-b587-11e7-929d-646802f8a098.png)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Simply, set Automatic replies as shown on screenshots.

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Default.
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
Win10
- Browser/version: 
FF 56.0.1 (64-bit)
- uBlock Origin version: 
uBlock Origin v1.14.14
##### Your filter lists
Default.
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by BilBg** [comment]
I don't understand what is blocked (you assume everybody knows what is Office365, how it works and have account at outlook.office365.com)

What is shown as blocked in logger
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by RobertZXR** [comment]
This is about "Automatic replies" in OWA in Office365, part for outside senders.

**This is without uBlock:**
![image](https://user-images.githubusercontent.com/32954207/31816609-48fa66f8-b591-11e7-93f8-d1099846fc52.png)

**This is with uBlock - content (text "OUTSIDE") has disappeared:**
![image](https://user-images.githubusercontent.com/32954207/31816729-ba3f4004-b591-11e7-919a-575af356c21f.png)

**Comment by gorhill** [comment]
Why is this not a filter issue?

**Comment by gwarser** [comment]
OP says:

>It works bad even uBlock is disabled for current page, but it works fine when uBlock is disable completely.

Also logger seems to confirm this.

This is Firefox 56 - may be browser issue.

**Comment by gorhill** [comment]
> This is Firefox 56 - may be browser issue.

Yes, most likely.

@RobertZXR Can you try to reproduce with Firefox 57 beta or Firefox Nightly. There were many issues of improper page rendering with Firefox 55-56 and WebExtensions.

Another way to indirectly confirm this is a browser issue is to see if you setill have the issue with only Privacy Badger, or only Adguard installed.

**Comment by RobertZXR** [comment]
In version 57.0b9 (64-bit) it works OK - THX!

**Comment by gorhill** [comment]
So marking as a browser issue. However can only speculate about which one specifically it is. From the look of it, I will assume it's the [`document.write` one](https://bugzilla.mozilla.org/show_bug.cgi?id=1379148).
