### ISSUE TITLE
Block CoinHive JavaScript code

### ISSUE THREAD

**Issue by mhalano** [gorhill/uBlock#3154]
Some websites implements a JavaScript code called CoinHive to mine Monero alternative coins. The idea here is create an option to block this code insde uBlock Origin itself. There's a extensions called No Coin which already do this, but first it's one more extension, and uBlock is a wide spectrum blocker and JavaScript miners are in the spetrum.

**Comment by KingThunder** [comment]
But we already have a filterlist with that, it's called:

> uBlock filters – Resource abuse

**Comment by mhalano** [comment]
I mean may be a more clear ans specific option because it's a problem very current.

**Comment by uBlock-user** [comment]
CH relies on `WebAssembly` and JS `workers`, blocking one of them or both should do the job for you.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
