### ISSUE TITLE
want to eliminate white blank space

### ISSUE THREAD

**Issue by manjusr81** [gorhill/uBlock#3155]
![screenshot - 10_21_2017 2_59_50 pm](https://user-images.githubusercontent.com/9315238/31850510-a7cdecce-b670-11e7-8ca9-56e188954ffb.png)

**Comment by manjusr81** [comment]
As u see in the above screenshot 
![screenshot - 10_21_2017 2_59_50 pm](https://user-images.githubusercontent.com/9315238/31850527-f7a270ee-b670-11e7-80ca-5aaf9ae46744.png)
I want to eliminate the white space starting of the page.  (i,e above Crude Oil WTI Futures,  nearly about 4 lines space).   How to do this.

**Comment by mapx-** [comment]
- for filterts report here:
https://github.com/uBlockOrigin/uAssets/issues

- when you post in the correct repository provide all the necessary info (browser version, uBo version, filter lists, example links to those pages above)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
