### ISSUE TITLE
Ublock don't work properly with Tor browser 7.0.7

### ISSUE THREAD

**Issue by bup4gr** [gorhill/uBlock#3156]
In Tor browser 7.0.7 ublock don't work if security level is set to medium or high.

To reproduce bug:
- in tor browser (onion icon) set the security level medium or high
- close tor browser
- open tor browser
- Ublock don't work properly

Problems:
- Ublock don't filter, request blocked is always zero (and you cannot see the number of filter items in ublock icon)
- if you go in list of filters and click on a filter, you cannot see the filter rules 
- in register of requests, you can see only few requests

**Comment by gorhill** [comment]
What version of uBO? (mind [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) please).

**Comment by bup4gr** [comment]
Ublock 1.14.14

**Comment by gorhill** [comment]
Was this _not_ happening with the previous version of the Tor Browser, or is it just the first time you happened to notice it?

The fix here will make uBO loads properly the filter lists, but it will need to do it from scratch at every launch, and this means the filter lists will need to be all updated at every launch, because medium security setting and above does not allow the use of `indexedDB`, where UBO caches the filter lists and their compiled versions.

**Comment by bup4gr** [comment]
The first time i notice it, is with tor browser 7.0.7. When i have 7.0.6 i have no problem. I also think a problem with the update from 7.0.6, but i have the same problem also with a clen installation of 7.0.7.

If i close tor browser with with high in security setting and reopen it, i cannot update the filter list.
Also if i click on update button in ublock, then update of filter lists don't work.

**Comment by bup4gr** [comment]
For me the problem is not solved with ublock 1.14.16.

With "security settings" low:
- all works
- on bing i see
![u1](https://user-images.githubusercontent.com/27068733/31854678-8c005a1a-b68c-11e7-9240-a812abd23707.jpg)

With "security settings" medium:
- i cannot update the filters in the list
- look like no filter works (see image, but in the register of requests you can some blocked connections)
- on bing i see:
![u2](https://user-images.githubusercontent.com/27068733/31854686-acd5c2fc-b68c-11e7-8eaf-0c5a857fd9a5.jpg)

**Comment by gorhill** [comment]
I could reproduce the original issue. I identified that the opening of the indexedDB databased silently failed. This is what I have fixed. I can no longer reproduce the issue:

![a](https://user-images.githubusercontent.com/585534/31855047-b2b734b0-b670-11e7-8f59-a850b124830c.png)

You will have to investigate on your side to figure out what is your new issue. If I can't reproduce something, I can't investigate it.

**Comment by bup4gr** [comment]
On my side i don't see any change from ublock 1.14.14 to 1.14.16. For me the problem is always the same.
I have a clean installation of Tor Browser 7.0.7 (installed today) on Windows 10, so in my opinion is not a particular setting that cause the problem.

Here there is what i see in browser console after that Tor browser start:
![1](https://user-images.githubusercontent.com/27068733/31855637-78a7be38-b69e-11e7-93a3-bb2ca56c917c.jpg)

Now, how can i investigate the problem?

**Comment by gorhill** [comment]
In medium security, the filter lists will take significantly longer to load into memory, because uBO is forbidden to use indexedDB to cache the filter lists.

Are you waiting long enough to be sure the filter lists are all loaded before testing?

**Comment by bup4gr** [comment]
When security level in not low, Tor browser take more time to load. Also after the complete load of Tor browser i wait 1 min, but the i have always the problem.

At the same time i have:
filters seems don't work (also if filter don't work is strange that domains connected is 0 of 1)
![2](https://user-images.githubusercontent.com/27068733/31855907-55feb214-b6a4-11e7-9181-afc9093f9173.jpg)
filters seem work
![3](https://user-images.githubusercontent.com/27068733/31855908-63ffd7e4-b6a4-11e7-85ba-a0011c1378ac.jpg)

And somethnig that for me is unclear:
total filters are 59560, but only easylist is 76612 (this also after 5 min after open the browser)
![4](https://user-images.githubusercontent.com/27068733/31855931-f02ad1ce-b6a4-11e7-9ef0-c336f53776ff.jpg)

**Comment by gorhill** [comment]
What is that other extension you have installed? I test with only uBO, no other extension.

**Comment by bup4gr** [comment]
Yes, the problem is with noscript (installed by default with tor browser).

3 cases:

```
1.
- Security level in Tor Browser is high or medium
- disable all plugins (except tor button and torlauncher)
- close and reopen tor browser
- enable ublock
- ublock works (the only plugin enabled)

2.
- Security level in Tor Browser is high or medium
- disable all plugins (except tor button and torlauncher)
- close and reopen tor browser
- enable ublock
- close and reopen tor browser
- enable noscript
- ublock works (also if noscript is enable and also if close and reopen tor browser with noscript enabled)

3.
- Security level in Tor Browser is high or medium
- disable all plugins (except tor button and torlauncher)
- close and reopen tor browser
- enable noscript
- close and reopen tor browser
- enable (or install) ublock
- ublock DON'T works
```



From my own experience:
The third case is the most common because noscript is enabled in the tor browser installation.
When security level in Tor browser is set to medium or high, is also changed some settings in noscript (for example is disabled javascript).
This changes cause the problem in ublock.
So if Tor browser has security level medium or high, and no script is enabled before ublock, then ublock don't work.
All people that install tor browser and then install ublock have this problem, if the security level is medium or high (also if security level medium or high after installation of ublock).

Are you able to reproduce this problem?
There is a solution to solve this problem?

**Comment by bup4gr** [comment]
After some test in "case 2", i see that in ublock the filters work, but "element picker" and "element zapper" don't work

**Comment by gorhill** [comment]
@laniakea64 Any known issue with NoScript to explain observations in <https://github.com/gorhill/uBlock/issues/3156#issuecomment-338437991>?

**Comment by laniakea64** [comment]
I'm not the best person to ask.  I don't know Tor browser at all.

Is this reproducible in the corresponding Firefox version?

**Comment by Hrxn** [comment]
Should be, Tor Browser is basically Firefox, after all. Maybe some different default settings..

**Comment by gorhill** [comment]
I am not able to reproduce case 2 or 3. uBO works fine in either case.

**Comment by bup4gr** [comment]
Today i made other tests (torbrowser 7.0.8 and ublock 1.14.16) and ublock don't works also if is the only extension enabled (with torbutton and torlauncher)
![im](https://user-images.githubusercontent.com/27068733/32133745-bf90a5e2-bbcd-11e7-87a9-4081ece32fea.jpg)

Then i disable ublock, reactive it and then ublock works.
![im2](https://user-images.githubusercontent.com/27068733/32133787-8f2a27a6-bbce-11e7-9588-155ec279dd21.jpg)

So, after more tests, i think that the problem is not related with noscript, but i don't understand the source of the problem.

**Comment by gorhill** [comment]
As said above, I can't reproduce your issue with uBO and Tor Browser in medium security mode, with or without NoScript. So at this point this means whoever is able to reproduce it will have to investigate on their side to narrow the cause of it.
