### ISSUE TITLE
The first line in the README doesn't get the point across

### ISSUE THREAD

**Issue by anohren** [gorhill/uBlock#3157]
### Describe the issue
The only reason I looked at the frontpage/README is to determine whether I should download uBlock Origin or ublock.org from chrome store. The headline in the readme says "BEWARE! uBlock Origin is (and has always been) COMPLETELY UNRELATED to the web site ublock.org" -- but the problem is that at this point I have no idea whether I'm looking at the repo of uBlock Origin or ublock.org, so this sentence doesn't get the point across. There is no title for the readme that clearly says "This is uBlock Origin" (there's just a small comment far away above the repo directory listing that mentions it) so it actually gives the opposite effect when the page starts with "**Beware! uBlock Origin** [...]". 

All I could think of was "Are you warning me about uBlock origin?"

**Comment by gorhill** [comment]
> There is no title for the readme that clearly says "This is uBlock Origin"

There is a big fat title which says "uBlock Origin".

**Comment by anohren** [comment]
Well, if you don't want to read what I wrote there's nothing more to be said. We usually start reading from the top, downwards. (Hint: the big fat title is beneath the line to which I'm referring).

**Comment by gorhill** [comment]
Yes ok, after editing to see how it looked, you're right, I agree having the title at the top is better.

**Comment by Hrxn** [comment]
The Chrome Web Store (as well as Mozilla's Add-ons) always show essential information like the version number and the date of the last update of said version, this should help you to always figure out what is what, and what to use..

**Comment by anohren** [comment]
@gorhill 👌

@Hrxn I think you might have misunderstood my described issue. This was about using this repo's Readme to quickly identify which of the seemingly identical extensions in the store corresponds to this repo. Versions and updates are not related to this. 

In short, I was trying to help ease friction in the onboarding process for people like me who were convinced of trying the plugin after following link to the performance comparison in this repo.

**Comment by Hrxn** [comment]
Sure, no problem. I have no qualms or anything with the suggested change etc.
Just as general guidance, to help ease friction, and so on, you're right.
And by the way, this repo is linked from the Web Store page.
