### ISSUE TITLE
Add "Firefox WebExtensions" to wiki Home Page

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#3158]
Please add link to [Firefox WebExtensions (Read carefully if using uBO/webext)](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions), to [Wiki Home page](https://github.com/gorhill/uBlock/wiki). I propose to put it in Troubleshooting section.
Thank you.

**Comment by gorhill** [comment]
I've allowed everybody to edit the wiki so that you can edit as you see fit. Thanks.
