### ISSUE TITLE
:style filters incorrectly shown in logger

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#3159]
### Describe the issue

Minor issue with the logger. After commit 6112a68faf46d89c58defdd9e14d4342747c9523 logger shows 

```
example.com##body
```
instead 
```
example.com##body:style(background-image: none !important;) 
```

- Browser/version: Firefox Nightly 
- uBlock Origin version: 6112a68faf46d89c58defdd9e14d4342747c9523

**Comment by gorhill** [comment]
This was on my mental list of things to do, I ended up forgetting about this one.

**Comment by okiehsch** [comment]
It also does not show the origin of the `:style` filter and "breaks" the dom-inspector.
Example: `https://www.quora.com/What-type-of-people-should-I-not-trust-in-life`
![unbenannt](https://user-images.githubusercontent.com/16838044/32694908-1ff80cba-c74d-11e7-8ddb-93a80f3a2fe0.PNG)

![screenshot 5](https://user-images.githubusercontent.com/16838044/32694982-d5a38baa-c74f-11e7-9d44-af1d4251e439.png)

**Comment by kasper93** [comment]
Also procedural filters are not included in dom-inspector. They were before the changes.
