### ISSUE TITLE
csfd.cz - infinite loop + high cpu usage

### ISSUE THREAD

**Issue by holdenger** [gorhill/uBlock#316]
Hello there,

on csfd.cz uBlock Origin starts blocking inifinite number of elements which cause high cpu usage. Can you look into this? It's relative big czech website similar to IMDB.com.

Check the screenshot with log please.

https://www.dropbox.com/s/ndoi4qtifpxy7at/Screenshot%202015-06-08%2015.08.05.png?dl=0

**Comment by offhub** [comment]
Temporary workaround for csfd.cz: (allow xhr)

Add the following filter to "My Filters":
'''@@||www.csfd.cz/log?type=js$xmlhttprequest,domain=www.csfd.cz'''

**Comment by gorhill** [comment]
Can't reproduce -- assuming default settings due to lack of details provided.

**Comment by gorhill** [comment]
You screenshot shows that the web page served by that site is making a huge amount of requests, and uBlock is doing its job blocking them. The issue is with the site which misbehave if a network request fails. It's a site/3rd-party filter list issue, not a uBlock issue.

**Comment by offhub** [comment]
@holdenger please update your EasyPrivacy list.

https://forums.lanik.us/viewtopic.php?f=23&t=23214&p=71353&hilit=csfd#p71353

**Comment by gorhill** [comment]
That explains why I couldn't reproduce, my _EasyPrivacy_ probably had the fix.

**Comment by holdenger** [comment]
Aha! Now i see where is the problem, thank you guys.
