### ISSUE TITLE
Ublock Origin has issues blocking elements that are randomly generated everytime the page loads

### ISSUE THREAD

**Issue by Question2** [gorhill/uBlock#3162]
# Describe the issue

This seems to happen most often on sites like pornhub.com and gelbooru.com. They have elements for ads that are randomly generated everytime the page loads.

### One or more specific URLs where the issue occurs

E.G. https://gelbooru.com/index.php?page=post&s=list&tags=tokisaki_kurumi

### Screenshot in which the issue can be seen

![ublock](https://user-images.githubusercontent.com/1191378/31865195-577d5cc2-b7b6-11e7-97a6-0ebbaf94e9be.jpg)

### Steps for anyone to reproduce the issue

As you can see the element name is some gibberish that gets randomly generated everytime the page loads and ublock origin cannot figure out how to block it permanently. 

I can block the host for the ad images (which is why you dont see the ads in the screenshot) , but ublock does not hide the empty element for some reason and there are ugly empty white spaces on the page.

Blocking "inline scripts" will hide the empty white spaces but will also block all images on the site, basically breaking the entire site. I do have "hide placeholders for blocked elements" on but it does not apply as the element is techncially not being blocked, the images are. And i cannot block the element as it is randomly regenerated everytime the page loads.

### Your settings

OS : Win 7 64 bit
Firefox 52.4 ESR
uBlock Origin version: 1.13.8

##### Your filter lists

Not a filter issue

##### Your custom filters (if any)

Not a filter issue

**Comment by friendlytherapist** [comment]
Ive also had problems with the new element blocking. Mainly its not specific on what it blocks anymore and it tends to block more than I asked for which breaks the page. For example: If I select a specific button it writes in "###button" and removes all the buttons on the page!

**Comment by okiehsch** [comment]
The `gelbooru` issue has been fixed with https://github.com/uBlockOrigin/uAssets/commit/c889626754804486965f625ad1aa894cc82a42b8, still works on my end with Chrome and Firefox.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Question2** [comment]
@okiehsch : Could you be more specific please? Is the element hiding fixed in an unreleased version or something?

@gorhill : This is not a filter issue. Are we on the same page here? Im talking about using the element hiding tool that ublock origin has. That is completely unrelated to filters.

**Comment by mapx-** [comment]
Force an update of your lists (especially `ublock filters` and test again.

**Comment by okiehsch** [comment]
It is fixed in `uBO-filters` by preventing `gelbooru` to randomly generate the elements in the first place.

**Comment by Question2** [comment]
@mapx, @okiehsch : The issue was that the version of ublock origin i was using was out of date, as stated in the OP, i was using 1.13.8. I did not realise my addons were set to not auto-update.

**Comment by Question2** [comment]
@mapx @okiesch : An hour after I tested it and found it working, it is no longer working. I am still using the latest 1.14.16 version and have tried purging/updating all my lists.

The elements with gibberish names are back. Maybe the website owner updated his scripts or whatever to counter the filter block?

What exactly is the filter entry that is supposed to be blocking these anyway?

**Comment by okiehsch** [comment]
The site indeed changed again, I can reproduce, add
````
gelbooru.com#@#script:inject(abort-current-inline-script.js, setTimeout, exosrv)
gelbooru.com##script:inject(abort-current-inline-script.js, setTimeout, banner)
````
until I upload thefix.
