### ISSUE TITLE
Open in new tab produces 6+ 'popup' lines in logger

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#3165]
### Describe the issue
When I open links by middle click or by context menu -> Open Link in New Tab, UBO logger show 6 or more 'popup' events.

### One or more specific URLs where the issue occurs
On this page, middle click on Issues on top [(or here)](https://github.com/issues).

### Screenshot in which the issue can be seen

22:57:15 |   |   |   | popup | `https://github.com/issues`
-- | -- | -- | -- | -- | --
22:57:15 |   |   |   | popup | `https://github.com/issues`
22:57:14 |   |   |   | popup | `https://github.com/issues`
22:57:14 |   |   |   | popup | `https://github.com/issues`
22:57:14 |   |   |   | popup | `about:blank`
22:57:14 |   |   |   | popup | `https://github.com/issues`
22:57:12 |   |   |   | popup | `https://github.com/issues`
22:57:12 |   | \|\|collector.githubapp.com^ | -- | xhr | `https://collector.githubapp.com/collect`
22:57:12 |   | \|\|google-analytics.com^ | -- | xhr | `https://www.google-analytics.com/r/collect`
22:57:12 |   |   |   | popup | `about:blank`

### Your settings

- OS/version: Mint
- Browser/version: Firefox (tested on beta and nightly)
- uBlock Origin version: bisected to https://github.com/gorhill/uBlock/commit/526ffe214da00c6933fd6f8f73083887f59b8e89 webext -> https://github.com/gorhill/uBlock/issues/3073

##### Your filter lists

Default + POL

**Comment by gorhill** [comment]
It's a Firefox-specific issue. There so much uBO can do to deal with the way Firefox API fired the `tabs.onUpdated` event. Even trying to be a bit smarter to avoid the weirdness, I get:

![a](https://user-images.githubusercontent.com/585534/31916374-6cc2fba4-b820-11e7-93d4-1b1e45fc3113.png)

Of course it makes no sense that `https://github.com/issues` became `about:blank` then `https://github.com/issues`, but that is what Firefox fires to the extension.

**Comment by gwarser** [comment]
Can be closed - browser issue or something. I put this here only to be documented.

**Comment by gorhill** [comment]
Well I think I will keep my fix to detect duplicate URLs in `onUpdated` (it code change seems trivial enough, but then it's difficult to foresee everything), but beyond that the logger will still look weird.

**Comment by uBlock-user** [comment]
Happens on Chromium 63 too, I get `5` popup entries.

![](https://i.gyazo.com/574f5005c67e519ef77b1bc13ed3b146.png)

**Comment by okiehsch** [comment]
With Chrome 62 
![unbenant](https://user-images.githubusercontent.com/16838044/31919193-09cf2b12-b861-11e7-8008-7c99046c88d4.PNG)

**Comment by Okamoi** [comment]
With `no-popups: * true` it becomes impossible to open a new tab by highlighting text that happens to be a URL and selecting `Open link in a new tab`.

Do you know a work around to keep the `no-popup` directive without having to whitelist all sites to be highlighted ? Or is it only something Mozilla and Google can do at this point ?
