### ISSUE TITLE
[Feature Request] Random OS Spoofing

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#3168]
Under the privacy part in settings can you please ad random OS and browser spoofing where it randomly changes your OS, browser and screen resolution from 1 to 10 minutes or ever new domain visited.
Thanks

**Comment by gorhill** [comment]
A dedicated extension for anti-fingerprinting is the appropriate solution -- it's a huge undertaking in itself, not something I will take on.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by zero77** [comment]
Ok thanks for your speedy reply also, are you able to recommend a WebExtensions supporting one.

**Comment by uBlock-user** [comment]
For Chromium/Chrome, I suggest ScriptSafe. There isn't one for FF, but see if someone decided to port it.
