### ISSUE TITLE
Reddit.com - Analytics

### ISSUE THREAD

**Issue by Ineluctable** [gorhill/uBlock#3170]
Hello, I was wondering if you could assist me. I'm wanting to prevent the analytics on reddit.com from firing - the "sh" and "st" variables that are put at the end of each comment page are annoying me - and I know it's leaking a lot of personal data back to them.

`<a class="title may-blank outbound" data-event-action="title" href="https://www.cnbc.com/2017/10/24/twitter-will-label-political-ads-including-who-bought-and-spend.html" tabindex="1" data-href-url="https://www.cnbc.com/2017/10/24/twitter-will-label-political-ads-including-who-bought-and-spend.html" data-outbound-url="https://out.reddit.com/t3_78ih3b?url=https%3A%2F%2Fwww.cnbc.com%2F2017%2F10%2F24%2Ftwitter-will-label-political-ads-including-who-bought-and-spend.html&amp;token=TOKENHERE&amp;app_name=reddit.com" data-outbound-expiration="1508897422000" rel="">Twitter will now label political ads, including who bought them and how much they are spending</a>`

`<a href="/r/worldnews/comments/78ih3b/twitter_will_now_label_political_ads_including/" data-inbound-url="/r/worldnews/comments/78ih3b/twitter_will_now_label_political_ads_including/?utm_content=comments&amp;utm_medium=front&amp;utm_source=reddit&amp;utm_name=worldnews" data-href-url="/r/worldnews/comments/78ih3b/twitter_will_now_label_political_ads_including/" data-event-action="comments" class="bylink comments may-blank" rel="nofollow">992 comments</a>` 

I'm already stripping the above outbound links with the following Greasemonkey script.

`(function() {`
`    "use strict";`

    $(".outbound").attr("data-outbound-url", null);
    $(".title").attr("data-inbound-url", null);

    $(".outbound").attr("data-href-url", null);
    $(".outbound").removeClass("outbound");

    $(".bylink").attr("data-href-url", null);
    $(".bylink").attr("data-inbound-url", null);
`})(); `

Apparently Reddit doesn't like that, so 0.5-1 second after loading a comments page page, it gets redirected to the same page, but with the 'sh' and 'st' variables defined.

I determined that the offending code is in reddit-init*.js ... if there was a way to override the function `r.analytics`, it should put a stop to it all. Otherwise, is there a way to block their `window.location` calls from redirecting the page? I've tried naively blocking the -init.js script altogether, but that stops other site features (such as comment collapsing) from working correctly.

My apologies if this is the wrong place to ask - I understand this is more privacy related than ad related - but I figured you guys would have the most expertise in figuring this out - or pointing me in the right direction.

### One or more specific URLs where the issue occurs
https://www.reddit.com/
https://www.reddit.com/r/worldnews/comments/78ih3b/twitter_will_now_label_political_ads_including/
https://www.redditstatic.com/reddit-init.en.js

### Screenshot in which the issue can be seen
https://i.imgur.com/z9ZOMy5.png

### Steps for anyone to reproduce the issue

Strip Reddit's outbound/inbound tracking links, and then click any comments link, and watch as the location bar updates. Example URL is shown above in a screenshot.

### Your settings

- OS/version: Windows 7
- Browser/version: Chrome 61.0.3163.123
- uBlock Origin version: v1.14.12 w/ uBlock Origin Extra 2.52 (and uBlock Protector 12.35)

##### Your filter lists

All uBlock filters, Adblock Warning Removal List, EasyList, EasyPrivacy, Malware Domain List, Malware domains, Peter Lowe’s Ad and tracking server list​, uBlock Protector List

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
