### ISSUE TITLE
Menu not visible in Edge if Advanced is enabled

### ISSUE THREAD

**Issue by ToniCipriani** [gorhill/uBlock#3172]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
See screenshot, Menu is not resized to the wider view when Advanced is enabled

### One or more specific URLs where the issue occurs
Not Applicable
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
https://i.imgur.com/4Xa3T6x.png
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Open extension menu in Edge

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10.16299.19
- Browser/version: Edge 41.16299.15
- uBlock Origin version: 1.13.18

##### Your filter lists
Not Applicable
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
This is not the place for reporting Edge issue: <https://github.com/nikrolls/uBlock-Edge#edge>.
