### ISSUE TITLE
Many external subscriptions are not shown, some lists changed to "custom subscriptions"

### ISSUE THREAD

**Issue by wallofbytes** [gorhill/uBlock#3174]
I can't see (and choose) some filter lists listed [here](https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json) in my [3p-filters page](/dashboard.html#3p-filters.html). For example, I can't see EU: Prebake.
![15083296928780](https://user-images.githubusercontent.com/18580942/32122721-038984c6-bb6a-11e7-8422-b8cd758d0dd6.png)

other (previously visible) went to the "user's lists" block, for example, Ru AdList:BitBlock, uBlock Protector, Basic tracking by Disconnect. I tried to enable "advanced user mode" and reinstall uBlock, but this did not have the expected effect, many lists are still hidden. Why?

**Comment by gwarser** [comment]
Because this file and filter lists are outdated. https://github.com/gorhill/uBlock/blob/master/assets/assets.json is used now.

**Comment by gorhill** [comment]
I do from time to time revise what is listed in _"3rd-party filters"pane, and may choose to remove some lists from there for various reasons. When this happens, and a removed list is selected, it will be moved to custom filter lists. It's all explained in the release notes, please read these before opening an issue next time.
