### ISSUE TITLE
Could you backport some GUI-related code from uBlock to uMatrix to make the latter work properly on Android?

### ISSUE THREAD

**Issue by KOLANICH** [gorhill/uBlock#3175]
### Describe the issue
Since uMatrix is a WebExtension now, I have installed it on FF for Android. It has some GUI issues: I cannot open the tab with the matrix by selecting uMatrix from the menu. uBlock seems to have this issue solved. Since it shares most of the code with uMatrix I ask you to backport the fixes from uBlock to uMatrix. Also I wonder if it makes sense to modularize that code into a library and modify this in single place, propagating the changes to both addons automatically. Thank you.
### Your settings
- OS/version: Android
- Browser/version: FF 56.0b11
- uBlock Origin version: the latest development one from AMO: 1.14.17b7
- uMatrix version: the latest development one from AMO: 1.0.1rc4

**Comment by gorhill** [comment]
uMatrix is not marked as being compatible with Android, and is not presented as being compatible with Android on AMO.
