### ISSUE TITLE
[NSFW] sub-domain pages of rule34hentai.net

### ISSUE THREAD

**Issue by catshitz** [gorhill/uBlock#3176]
win10 1709 Pro
Chromium 61.0.3163.100
uBlock Origin 1.14.12
uBlockProtector 12.42

uBlock basic rules
EasyList
Adguard Base Filters
Adblock Warning Removal List
EasyPrivacy
and a few basic local rules

Random click open-up ads pages like this:
http://k26fe9xhuzm.com/921851.html?q
This happens whenever your first few opens of different sub-domain pages of rule34hentai.net,
and once after a sub open-up ads page appeared, it stops showing in the same page for long,
but the other continues before the first click, quite annoying.

Custom block rules showing like this,
##div:nth-of-type(17) 
number changes, it won't help.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
