### ISSUE TITLE
[feature] Block website access (without prompting it later) in a single-click

### ISSUE THREAD

**Issue by fabionar** [gorhill/uBlock#3177]
It's painful to select the website's url, open the dashboard, select my personal filter, and then see that a new domain trespassed ublock again. And even doing this ublock prompts it later with a "return" option that nobody wants to see.

A simple button to delete the current's popup domain is the most important feature for ublock Origin.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Still, I made an effort to understand what you are talking about, I can't understanding what you are saying. Respect [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) if you like the project -- it's a burden to deal with invalid issues.
