### ISSUE TITLE
Be able to remove Easylist and Easyprivacy if Ultimate list is selected

### ISSUE THREAD

**Issue by drbluetongue** [gorhill/uBlock#318]
Hi,

Latest dev version of uBlock0 for Firefox.

What I'd like to achieve is being able to purge both Easylist and Easyprivacy, as well as Fanboys Annoyance as I have selected Fanboy+Easylist ultimate. 

You can deselect them, but there is no purge button and it says "0 out of xxx used".

To stop people removing them accidentally, can this be enabled for when I have ticked "advanced user"?

![screenshot](https://cloud.githubusercontent.com/assets/12694883/8040645/f17db32a-0e09-11e5-9b83-a0d806cf2b91.png)

Cheers

**Comment by gorhill** [comment]
> but there is no purge button

This means there is no cached content. The _"0 out of xxx used"_ does not mean the list is loaded by uBlock.

**Comment by gorhill** [comment]
> being able to purge both Easylist and Easyprivacy, as well as Fanboys Annoyance as I have selected Fanboy+Easylist ultimate

I read again, and if you mean to remove them from the stock filter lists, I do not intend top do this. How would you bring them back in case of change of mind? Many other things in the code that do not fit this idea, so I rather not destabilize uBlock for such a special request.

**Comment by drbluetongue** [comment]
I knew that if it said "0 out of ?" meant that it wasn't loaded, but I wasn't sure if when it actually gave a number for "0 out of 10560" it had loaded or not. 

It still says "0 out of 10560" if it's ticked or not.

No problem, thanks for looking into it :)
