### ISSUE TITLE
Remove anti-AdBlock DRM circumvention measures

### ISSUE THREAD

**Issue by AdBlockDRM** [gorhill/uBlock#3180]
### Describe the issue

The content blocker UBlock Origin provides a functionality that is illegally bypassing anti-AdBlock DRM measures. anti-AdBlock is a DRM  measure used to restrict access to a software blocking advertisements.

### Solution

Remove all the circumvention measures, that bypass anti-AdBlock DRM measures. 

Note: **In case of non-compliance, legal action may be pursued.**

**Comment by Hrxn** [comment]
[Citation needed]

**Comment by AdBlockDRM** [comment]
https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json`

```
	"https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
		"off": true,
		"title": "Anti-Adblock Killer | Reek",
		"group": "ads",
		"supportURL": "https://github.com/reek/anti-adblock-killer",
		"instructionURL": "https://github.com/reek/anti-adblock-killer#instruction"
	},
```

The content blocker intentionally incorporates an external anti-AdBlock DRM circumventing measure(s).

**Comment by GuardianMajor** [comment]
Troll, @gorhill ignore it as this "citation" has been deprecated already and this account was created today just to post this, hardly legitimate.

**Comment by uBlock-user** [comment]
This troll is going around posting shit here too - https://github.com/jspenguin2017/uBlockProtector/issues/675

**Comment by thrwat** [comment]
I hope you are trolling. This is not fair, adblock is my right.

**Comment by lfmnovaes** [comment]
Maybe he is not trolling, but doesn't mean he is right. No matter how we see it this is a lost cause for him.

**Comment by Betsy25** [comment]
When can we expect the movie about it ?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
