### ISSUE TITLE
Ad-blocking to the cloud? By DNS!

### ISSUE THREAD

**Issue by EC-O-DE** [gorhill/uBlock#3184]
Easylist and uBlock Origin and others - it would be great to have ad-blocking done at server side.

**OpenNIC** might be interested to setup DNS servers where ads could be filtered by common lists such as Easylist and Easyprivacy etc.

https://www.opennic.org/

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
...and when that cloud server get compromised, users get trolled. No thanks.
