### ISSUE TITLE
ublock unhides hidden elements when it's updated

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#3185]
### Describe the issue

ublock unhides hidden elements when it's updated

### One or more specific URLs where the issue occurs

tumblr.com/dashboard

### Screenshot in which the issue can be seen

[pending ublock update]

### Steps for anyone to reproduce the issue

1. put something like `www.tumblr.com##.post[data-is_recommended="1"]` in your custom filters
2. go on a page with such elements
3. wait for ublock to update

### Your settings

set:

- hide placeholders
- show blocked count
- use context menu
- advanced mode
- no prefetch
- no auditing

unset:

- everything else?

- - -

- OS/version: arch linux x86_64
- Browser/version: firefox 56.0.1
- uBlock Origin version: 1.14.17b9

##### Your filter lists

all ublock
easylist
adblock warning removal
easyprivacy
malware domain list
malware domains
fanboy's annoyance
fanboy's social
peter lowe's ad/tracking list
aaklist (which is apparently "custom"?)

##### Your custom filters (if any)

```
! 2017-04-19, 12:18:23 PM https://uk.pinterest.com/autisticmind/drawings/
uk.pinterest.com##div:nth-of-type(3) > div:nth-of-type(3)

! 2017-05-03, 5:43:42 PM https://www.tumblr.com/dashboard
www.tumblr.com##.post[data-is_recommended="1"]

||belarr.com/bakercat/
||belarr.com/bakercat/$document

! 2017-08-16, 12:27:28 AM https://www.tumblr.com/dashboard
www.tumblr.com##.chat-status-banner

! 2017-08-16, 12:27:45 AM https://www.tumblr.com/dashboard
www.tumblr.com##.status-indicator

! 9/24/2017, 12:30:08 PM https://www.tumblr.com/dashboard
! www.tumblr.com##.post:has(.recommendation-reason-link)
!

! speedtest stuff
@@/hello^$xmlhttprequest,domain=speedtest.net
@@/ping^$xmlhttprequest,domain=speedtest.net
@@/download^$xmlhttprequest,domain=speedtest.net
@@/upload^$xmlhttprequest,domain=speedtest.net
```

edit: I believe this can be fixed with startup hooks: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onInstalled (but I'm not an extension developer)

**Comment by gorhill** [comment]
Browser behavior, probably by design.

**Comment by SoniEx2** [comment]
Could this be reopened?

**Comment by gorhill** [comment]
You can comment on it without having to re-open. Anyway, I will try something on my side, I just realized I broke the manual injection of scripts at launch with a recent change.

**Comment by gorhill** [comment]
What do you mean by "startup hook"?

**Comment by gorhill** [comment]
Un-hiding cannot be fixed, this is a by-design browser behavior. However I fixed the broken manual injection of content scripts, so the cosmetic filters should be re-applied as used to be the case.

**Comment by SoniEx2** [comment]
You can reapply the hiding when the startup hook is called, I think. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onInstalled

**Comment by gorhill** [comment]
I know about these listeners -- uBO of course knows when its being launched, this is not the issue. The issue is to have the content scripts injected **only** when all the filter lists have been loaded so that the required cosmetic filters can be fetched. Anyways, fixed as best as can be with the last commit.
