### ISSUE TITLE
Request: Create black list filter?

### ISSUE THREAD

**Issue by Ravor9** [gorhill/uBlock#3186]
### Describe the issue
I would love to not have ad blocked by default and selecting each site/page manually. Unfortunately I cant block ad for specific page when I allow the rest of the site (like an specific stream on twitch or channel on youtube)

### Steps for anyone to reproduce the issue

When you have ublock active on chrome you have option to disable for the whole site and for a specific page. But you cant do the reverse of it, allow for the whole site but one specific page. If you ctrl + click the block button the page will be whiteflagged but the rest of the site will have the ads blocked (the opposite of what I wanted)

### Your settings

- OS/version:  Windows 10 home x64; Version:1709 ; OS Build:16299.19
- Browser/version: Google chrome/61.0.3163.100
- uBlock Origin version: v1.14.12

**Comment by uBlock-user** [comment]
use uMatrix instead of uBO then. It offers `allow all-block exceptions` functionality.
