### ISSUE TITLE
Static-filtering: $object_subrequest blocking method

### ISSUE THREAD

**Issue by john103** [gorhill/uBlock#3187]
### Describe the issue
Might be related due to developing policy: https://github.com/gorhill/uBlock/issues/2747#issuecomment-312153435

### One or more specific URLs where the issue occurs
http://bartbonte.com/factoryballs3/

### Steps for anyone to reproduce the issue

1. install uBlock Origin, restart browser
2. Add filter:
```
! Below filter reported by uBlock Logger as invalid. I guess because "$object_subrequest" is not really supported.
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com

||server.cpmstar.com/adviewas2.swf$object-subrequest,domain=bartbonte.com

||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
```
3. Open uBlock Origin logger.
4. Visit (requires flash): http://bartbonte.com/factoryballs3/

### Expected results:
http://server.cpmstar.com/adviewas2.swf is blocked.

### Actual results:
http://server.cpmstar.com/adviewas2.swf is not blocked.

### Known workaround:
```
||server.cpmstar.com/adviewas2.swf$other,domain=bartbonte.com
```
With type "$other" it is blocked as expected.

### Further thoughts:
```
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
```
Something here might be wrong. Because filter with this type is offered by uBlock Origin if user attempts to block / allow such request via static-filtering from uBlock Logger.

### Your settings
new profile

- Browser/version: Firefox 56.0.2
- uBlock Origin version: 1.14.16

##### Your filter lists
Default except:
EasyList
EasyPrivacy
Peter Lowe’s Ad and tracking server list

These were unchecked because there were filters blocking that subrequest.

##### Your custom filters (if any)
```
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com

||server.cpmstar.com/adviewas2.swf$object-subrequest,domain=bartbonte.com

||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
```

**Comment by uBlock-user** [comment]
Chrome webRequest API [doesn't support](https://developer.chrome.com/extensions/webRequest#type-ResourceType) that, I doubt it will get added here.

**Comment by john103** [comment]
> Chrome webRequest API doesn't support that, I doubt it will get added here.

I see.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType
> Browsers that don't have a dedicated object_subrequest type (see browser compatibility below), also label subsequent requests sent by the plugin as object.

So since v55 firefox started to label such requests as: "object_subrequest" instead of plain "object". Hence uBlock is unable to classify these and is treating them as "other" now?

But what is this type for:
https://github.com/gorhill/uBlock/blob/6b293dd58b2ce14b59583aeda6c059d194493b90/src/js/static-net-filtering.js#L1341

And still uBlock Origin suggests a filter for this new request type. Isn't it kind of misleading to user? See below:
```
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
```

**Comment by uBlock-user** [comment]
What I think is there's a good chance that both of these types are going to get removed by the time 2020 rolls out, if they're only used by Flash, as it will be reaching it's EOL as per Adobe's decision.

**Comment by gorhill** [comment]
> Something here might be wrong. Because filter with this type is offered by uBlock Origin if user attempts to block / allow such request via static-filtering from uBlock Logger.

The logger reports the type as given to it by the webRequest API, while the static filtering engine normalize the type before filtering. With your observation, I can tell that Firefox's webRequest API is using `object_subrequest`, which is not something I mapped internally, because from uBO's point of view, this is a new type of request.

I will just map it to `object`. I do not have Flash in my Nightly, and really rather not install it on my computer. The fix is trivial but I would appreciate your report whether it works once I release a new dev build.

**Comment by john103** [comment]
> The fix is trivial but I would appreciate your report whether it works once I release a new dev build.

Sorry to bother you. I have loaded 1.14.17b10 WebExtensions version temporarily via about:debugging. But the fix didn't do it i guess. Because i can still see these requests as: "object_subrequest". Tried to block it as:
```
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
```
Without a success.

**Comment by gorhill** [comment]
I did not create a new dev build yet after the fix.

**Comment by john103** [comment]
> I did not create a new dev build yet after the fix.

Okay i have tried it. I guess rc0 has the fix now. But it didn't succeed in blocking either. Yet there is a change. Filter type that is suggested in static-filtering builder of uBlock still the same: "object_subrequest". But actual filter that is created in "My filters" after that has now type of "object". Also filter in "My filters" with type "object_subrequest" does not generate an error in uBlock Logger anymore. That's pretty much all that has changed. Request still is not blocked. These filters didn't succeed:
```
||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
```

**Comment by john103** [comment]
Still unresolved. That request is not getting blocked. I have tried rc1 and these filters:
```
||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
```

**Comment by gorhill** [comment]
> `||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com`

That filter is not valid, it's `object-subrequest` as per ABP filter syntax.

For the `object` one, I didn't change anything about it -- there is no reason it should no longer work. Use the shift key to force the cache to be bypassed when you force a reload of the page.

**Comment by gorhill** [comment]
I tested your filter `||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com` with Chrome -- which comes with Flash installed -- and it worked fine, `http://server.cpmstar.com/adviewas2.swf?poolid=28267&subpoolid=16` was blocked (I had to disable Peter Lowe's and EasyPrivacy because they wholly block `cpmstar.com`).

**Comment by john103** [comment]
> If you still can't make it work with Firefox, please report what the logger says about that network request.

I am not sure what logger you meant here. Well uBlock logger reports that there are 3 networks requests being made starting with:
```
http://server.cpmstar.com/adviewas2.swf?poolid=28267&subpoolid=16
```
If this first request is blocked then other two are not made. I have watched it in console log of browser too:
```
GET http://server.cpmstar.com/adviewas2.swf [HTTP/1.1 200 OK 577ms]
Response headers
Accept-Ranges bytes
Cache-Control no-store, no-cache, must-revalidate
Content-Length 10287
Content-Type application/x-shockwave-flash
Date Sat, 04 Nov 2017 06:17:46 GMT
ETag "e2bc2fdfb4cd31:0"
Expires Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified Tue, 24 Oct 2017 19:12:08 GMT
P3P policyref="/w3c/p3p.xml", CP="NOI NID CURa ADM DEVa PSAa PSDa OUR OTR IND UNI NAV STA"
Pragma no-cache
Server Microsoft-IIS/8.5

Params
poolid 28267
subpoolid 16
```

The only filter that still works for me is:
```
||server.cpmstar.com/adviewas2.swf$other,domain=bartbonte.com
```
With this i am not observing 2 other requests in the uBlock Logger and that first request is colored red also browser log console does not show any of these 3 requests being made.

I have tried these steps:
1. Completely new profile.
2. Loaded WebExtension version temporarily via about:debugging.
3. Disabled: Peter Lowe's and EasyList (i didn't have to disable EasyPrivacy maybe outdated).
4. Set filters:
```
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
||server.cpmstar.com/adviewas2.swf$object-subrequest,domain=bartbonte.com
||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
```
5. Visit page.
6. Reload page.
7. Reload page with shift + click.

**Comment by gorhill** [comment]
I installed Flash plug-in and I confirm the issue is fixed in rc1:

![a](https://user-images.githubusercontent.com/585534/32404663-b322376e-c12a-11e7-8177-2972b9559a4f.png)

You will have to look more on your side as to why you still have the issue. If the logger reports `other`, it's because you are not running rc1.

**Comment by john103** [comment]
> You will have to look more on your side as to why you still have the issue. If the logger reports other, it's because you are not running rc1.

You were right. My bad. I was sure i was running rc1 but when i have checked about tab it was rc0. I guess when i was saving xpi filename was same so i have simply replaced it but it didn't get overwritten probably because it was currently in use by browser. Confirming:
These filters are blocking request.
```
||server.cpmstar.com/adviewas2.swf$object-subrequest,domain=bartbonte.com
||server.cpmstar.com/adviewas2.swf$object,domain=bartbonte.com
```
This filter does not:
```
||server.cpmstar.com/adviewas2.swf$object_subrequest,domain=bartbonte.com
```

**Comment by gorhill** [comment]
> This filter does not:

Yes, because `object_subrequest` is not a valid [ABP-compatible filter option](https://adblockplus.org/filters#options). It has to be `object-subrequest`. The logger reports what the webRequest API reported. For example, `beacon` or `csp_report` are not valid filter options, and they are filtered as `other`. However the logger reports them as seen by the webRequest API.
