### ISSUE TITLE
uBlock blocking pictures 

### ISSUE THREAD

**Issue by jmcampmany** [gorhill/uBlock#3188]
I have a fresh install of uBlock with default settings which for some reason is keeping me from load pictures from domains like imgur or catbox.moe. I updated to the last pre-release and nothing changed. Both domains are added to the white list and I'm still unable to load them, I have to disable the add-on to do it.

I'd be glad if anyone could give me a hand with this.

**Comment by gwarser** [comment]
Diagnose using this: https://github.com/gorhill/uBlock/wiki/The-logger

Will be better if you ask support questions on reddit https://www.reddit.com/r/uBlockOrigin/

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
