### ISSUE TITLE
talkwithstranger.com has ads undetected

### ISSUE THREAD

**Issue by sanGtH** [gorhill/uBlock#3189]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Currently using Ublock Origin v1.14.12. The target website that is flooded with ads 
and Ublock is unable to block the ads. 

### One or more specific URLs where the issue occurs
talkwithstranger.com
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
- OS/version: Windows 7 64-Bit
- Browser/version: Firefox 51 (32-Bit) & Chrome 61.0.3163.100 (64-Bit)
- uBlock Origin version: 1.14.12

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by mapx-** [comment]
`talkwithstranger.com##script:inject(abort-current-inline-script.js, atob, TextDecoder)`

**Comment by sanGtH** [comment]
thanks mapx for the info. i have posted there.
