### ISSUE TITLE
Spam404 filter update problem.

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#319]
As title says. My newest version of uBlock Origin for Chrome shows that Spam404 filter is outdated, but when I go to the homepage of that filter, this website load normally. What the hell?!

**Comment by gorhill** [comment]
> when I go to the homepage of that filter, this website load normally

The filter lists is at a different domain name: <https://spam404bl.com/spam404scamlist.txt>.

In any case, I checked that filter list and is updated just fine on my side.

**Comment by Piter432** [comment]
<blockquote>In any case, I checked that filter list and it updated just fine on my side.</blockquote>
But not on my side. Also, the link you provide give an error in Chrome: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

:(

**Comment by gorhill** [comment]
That's a browser error, not a uBlock one. Try the non-SSL version:

    http://spam404bl.com/spam404scamlist.txt

**Comment by Piter432** [comment]
The non-SSL version loads very quickly on my newest Chrome :)

**Comment by gorhill** [comment]
> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

I don't get this error on Chromium. Not sure why you get this. How about Firefox? It loads fine in both browsers for me.

**Comment by Piter432** [comment]
Funny. Both in my newest Firefox on Windows XP and newest Firefox on Windows 7 64 bit (mom's laptop) updating is fine of this filter. Maybe one of Chrome options broke something or my anti-virus (which shouldn't, by the way)?

**Comment by gitarra** [comment]
ECDSA isnt supported on Windows XP. Use Firefox for modern HTTPS support on XP.

Better yet, upgrade to a supported OS.

**Comment by Piter432** [comment]
<blockquote>ECDSA isnt supported on Windows XP. Use Firefox for modern HTTPS support on XP.</blockquote>

Google, WTF you're doing? -.-

**Comment by gitarra** [comment]
Chrome uses Windows for HTTPS authentication, while Firefox uses NSS. If you want to stay safe and/or connect to sites using modern HTTPS on Windows XP you need to use Firefox.

**Comment by gorhill** [comment]
> If you want to stay safe and/or connect to sites using modern HTTPS on Windows XP you need to use Firefox.

So browser issue, thanks for the info.

**Comment by Piter432** [comment]
Maybe you add a http version of Spam404 filter for those, who have problems with https version? :)

**Comment by gorhill** [comment]
> Maybe you add a http version of Spam404

This would just unduly bloat the filter lists page with a duplicate, confusing people. It's is such an edge case, that the sensible solution is to just use `http://spam404bl.com/spam404scamlist.txt` as a custom filter list.

**Comment by Piter432** [comment]
Okay, I added http version as custom filter. But I think you should noticed people about this problem in Chrome on Windows XP to avoid more topics with issue, which I already reported :)
