### ISSUE TITLE
uBlock block reply in GoDaddy web based email

### ISSUE THREAD

**Issue by mzelden** [gorhill/uBlock#3190]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
uBlock blocks reply in GoDaddy web based email for HTML reply

broke with 1.13.9
1.13.7 RC4 works
Beta Version 1.14.17b10 still broken

The reply page just "hangs" with "loading". 

There are 3 connected domains I see in the logs besides godaddy.com.  I white listed
all 3 of them, but it still doesn't work.   godaddy.com,  wsimg.com, and secureserver.net.

### One or more specific URLs where the issue occurs
https://email15.godaddy.com/pcompose.php?aEmlPart=0&type=reply&folder=INBOX&uid=32772

### Screenshot in which the issue can be seen

https://i.imgur.com/wdtj4Ml.png

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

I'm not sure how to sate this other than you must:

1) Use godaddy email and have an account.  For example, mine is:
 https://sso.secureserver.net/?app=email&realm=pass&domain=email.mzelden.com

2) Be set to use HTML (not plain text) for replies.

3) Attempt to reply to an email

4) Be using a version of uBlock >= 1.13.9

### Your settings

- OS/version:      Windows 10 Pro 64-bit 
- Browser/version:   56.0.2 64-bit
- uBlock Origin version:   Multiple tried, see above.. breaks with 1.13.9, currently have beta 1.14.17b10

##### Your filter lists
I reset all settings to defaults yesterday after giving up with white lists trying to fix. 

behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop

##### Your custom filters (if any)
None
[my-ublock-backup_2017-11-01_12.37.34.txt](https://github.com/gorhill/uBlock/files/1435081/my-ublock-backup_2017-11-01_12.37.34.txt)

**Comment by gorhill** [comment]
Read the release notes please.

**Comment by mzelden** [comment]
Hint?  I read all release notes from current and f1.13.9 where it broke.  Is there a user forum?  I don't want to take up your time, but I can't figure out how to make it work with the current version(s).

**Comment by gorhill** [comment]
First: you have any legacy extension?

**Comment by mzelden** [comment]
Only classic theme restorer.  I tried disabling it and that didn't help.  BTW, before I posted the problem I deleted my firefox profile.ini file and my profile folder etc.  Did a complete clean install.   That didn't help.   Oh, I did just find the user form on Reddit.

**Comment by gwarser** [comment]
Duplicate https://github.com/gorhill/uBlock/issues/2982
