### ISSUE TITLE
Feature request: Cypto currency mining prevention

### ISSUE THREAD

**Issue by anandumdas** [gorhill/uBlock#3191]
Crypto coin mining is the new way of online money making. Websites use client CPU for mining crypto currencies such as BitCoin. A crypto miner script inclusion would be highly appreciated.

**Comment by wasd--** [comment]
You should read before posting, there is already a list only for that.

**Comment by gwarser** [comment]
"uBlock filters – Resource abuse​​​​​", selected by default.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
