### ISSUE TITLE
WARN Please specify whether you want browser_style or not in your browser_action options

### ISSUE THREAD

**Issue by sharethewisdom** [gorhill/uBlock#3192]
### Describe the issue

This warning appears, even though browser_style is specified in the manifest. This might have been there before, and it may be an issue specific to firefox.

> addons.webextension.uBO-Scope @ raymondhill.net WARN Please specify whether you want browser_style or not in your browser_action options.

### Steps for anyone to reproduce the issue

It is virtually the same as described in [this issue](https://github.com/EFForg/https-everywhere/issues/12775).

### Your settings

I'm using firefox 56.0.2 (64-bit) for `Linux libreboot 4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64 GNU/Linux`

**Comment by gorhill** [comment]
> This warning appears, even though browser_style is specified in the manifest.

If the browser warning is spurious, this has to be a browser issue -- why open an issue here?

**Comment by xkpd3** [comment]
The reason why it is here, is that the extension developer needs to add `"browser_style": true` or `false` to the manifest. I'm not sure what it does, but I've seen various commits at various plugins that implement this change.

So I think the issue is correctly opened here.

Best Regards,
Stefan

**Comment by gorhill** [comment]
It's already in the manifest:

https://github.com/gorhill/uBlock/blob/master/platform/webext/manifest.json#L13
