### ISSUE TITLE
Disabling uBlock doesn't work

### ISSUE THREAD

**Issue by ntopulos** [gorhill/uBlock#3194]
### Describe the issue

Since a few months something in uBlock has changed and a lot of pages doesn't work well or at all when it is enabled. This could be an acceptable issue if disabling uBlock was an option, but at the same time this problem occured, the disable function of uBlock broke and it still doesn't work.
Many website and webapps don't work with uBlock enabled, but disabling it with the provided button has absolutly no effect. The only way the get rid of this problem is to disable the plugin entirely.

### Steps for anyone to reproduce the issue

1. Go on any webapp that has content blocked by uBlock Origin;
2. disable uBlock for this page, reload;
3. access the same page with uBlock Origin plugin disabled and notice the difference where there shouldn't be any.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 56.0.2 (64-bit)
- uBlock Origin version: 1.14.16

**Comment by gorhill** [comment]
> Go on any webapp that has content blocked by uBlock Origin

What is a "webapp"?

[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> **ALWAYS INCLUDE A SPECIFIC URL WHERE THE ISSUE OCCURS**, _even_ if "it happens everywhere".

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
