### ISSUE TITLE
Also show blocked URL decoded

### ISSUE THREAD

**Issue by alexara** [gorhill/uBlock#3195]
### Describe the issue

If a link is forwarded by a tracker website, parts of the destination URL are HTML encoded as it is passed as a parameter.
That means for instance 

`http://www.dgb.de/themen/++co++5acd842c-bfbf-11e7-8e2f-52540088cada?t=1&et=rxKMuV&lnkname=klartext-40-2017-Lebensversicherungen-werden-zur-Handelsware.pdf`

becomes

`http%3A%2F%2Fwww.dgb.de%2Fthemen%2F%2B%2Bco%2B%2B5acd842c-bfbf-11e7-8e2f-52540088cada%3Ft%3D1&et=rxKMuV&lnkname=klartext-40-2017-Lebensversicherungen-werden-zur-Handelsware.pdf`

This makes it difficult to copy and paste the destiniation URL in order to open the website without visiting the tracker webpage.

Therefore it would be convenient if the decoded URL would also be shown.

### One or more specific URLs where the issue occurs

`http://www.dgb.de/themen/++co++5acd842c-bfbf-11e7-8e2f-52540088cada`

### Screenshot in which the issue can be seen

![screenshot](https://user-images.githubusercontent.com/13819719/32372819-c1275356-c096-11e7-9631-d3640b7ece63.png)

### Steps for anyone to reproduce the issue

1. Open the above given URL

### Your settings

- OS/version: Ubuntu 17.10
- Browser/version: FF 56.0
- uBlock Origin version: 1.14.16

##### Your filter lists

Default + Easylist German + Peter Lowe’s Ad and tracking server list

**Comment by gorhill** [comment]
It's already implemented, just click the magnifier in the bottom-right corner of the URL.

**Comment by alexara** [comment]
Thanks! Sorry that I missed that!
