### ISSUE TITLE
[Firefox] Use local image in Add-ons Manager

### ISSUE THREAD

**Issue by ujc75573** [gorhill/uBlock#3196]
Hi, is it possible to use local icons instead of the ones from Mozilla?

https://addons.cdn.mozilla.net/user-media/addon_icons/607/607454-64.png

I noticed this when I browsed the Add-ons Manager and used Inspector. I noticed that only uBlock is making a 3rd party request to retrieve an image from Mozilla.

![Sample](http://i65.tinypic.com/33omwdt.jpg)

I think that in the previous versions (before the web extension), uBlock is able to use a local image.

- OS/version: Windows 7
- Browser/version: Firefox 56.0
- uBlock Origin version: 1.14.17rc1

Hoping for your kind consideration, thanks.

**Comment by gorhill** [comment]
uBO has nothing to do with how the `about:addons` page is rendered -- this is all under control of the browser.

**Comment by gwarser** [comment]
I think, this may be because UBO uses 64px icon. They _require_ now 48 and 96px. 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons

**Comment by gorhill** [comment]
@gwarser Thanks for the hint, I will try 48px/96px to see if this makes a difference.
