### ISSUE TITLE
3rd-party filters are out of date between restarts

### ISSUE THREAD

**Issue by virtualghetto** [gorhill/uBlock#3197]
I have umatrix v1.0.0 and ublock v1.14.16 installed on the tor-browser v7.0.9 - Linux (64-Bit) with its security slider set to Low. Both plugins installed via about:addons.

The checked by default ublock 3rd party filters keep appearing as out of date after I click on update now, wait for all of them to update, then close and relaunch the tor-browser.

The Purge all caches button in ublock is unclickable after the relaunch.

The umatrix Hosts files update is not affected and does not require updating between restarts, it's purge all caches button is clickable.

I have no custom filters for ublock but I do have the following filters for umatrix:

    * * script block
    * * cookie block

I don't remember experiencing this with previous versions.

**Comment by gorhill** [comment]
Unable to reproduce. Your symptoms are that of uBO being unable to cache the downloaded lists into its indexedDB store. You will have to investigate on your side why this happens, re-open when you make the case this is an issue with uBO itself.

**Comment by gorhill** [comment]
Consider: <http://forums.mozillazine.org/viewtopic.php?f=9&t=3034189>.

**Comment by Thorin-Oakenpants** [comment]
@virtualghetto - to set an extension cookie exception see https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.7-Setting-Extension-Permission-Exceptions
