### ISSUE TITLE
Firefox - some links won't open when multiprocess is disabled

### ISSUE THREAD

**Issue by NoEscape** [gorhill/uBlock#3200]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
In Firefox when multiprocess is disabled (install an incompatible addon such as LiveHTTP Headers) some links on webpages will not open when clicked on. For example go to any Twitter page that has links under the profile on the left or in any "tweet". Click on the link and the link will not open. Enable multiprocess (Disable the incompatible addon e.g. LiveHTTP Headers). Click on the link on the Twitter page. Link will open.

This problem is not confined to Twitter and can manifest on many sites such as Facebook or sites with photo galleries which clicking on thumbnails should display the larger resolution image. However the problem is consistent on Twitter.com

### One or more specific URLs where the issue occurs
https://twitter.com/jimmykimmel
(any twitter page)
(click on youtube link or any link in tweets).

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
see above

### Your settings
all factory defaults, no site specific settings

- OS/version:  Windows 7 Professional, 32bit service pack 1, a required/recommended patches installed
- Browser/version: Firefox 56.0.4
- uBlock Origin version: 1.14.16

##### Your filter lists
all default

##### Your custom filters (if any)
none

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions

**Comment by gorhill** [comment]
Always read the release notes please.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
