### ISSUE TITLE
$generichide filter entry appears twice in the Logger on first load

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#3201]
### Describe the issue

$generichide filter entry appears TWICE in the Logger on first load.

### One or more specific URLs where the issue occurs

https://www.cbr.com/

### Screenshot in which the issue can be seen

![](https://i.imgur.com/yOYWH2y.png)

### Steps for anyone to reproduce the issue

1) Add `@@||cbr.com^$generichide` in _My Filters_.
2) Keeping the logger open, browse to https://www.cbr.com/  in a new tab.
3) Go back to the running logger and notice a double entry for `generichide` filter.

### Expected result

To show a single entry for `$generichide` filter as usual.

### Actual result

Shows an additional entry during the first load.

### Your settings

- OS/version: Win 10 Pro x64
- Browser/version: Chromium 64
- uBlock Origin version: 1.14.17.102

##### Your filter lists

Default + CSP filter for `cbr.com`

**Comment by rjkpa** [comment]
Not specific to cbr.com though as it happens on any domain on first load - https://i.imgur.com/EeYHd6e.png

**Comment by gwarser** [comment]
Confirmed on Firefox Nightly.

**Comment by toshiya44** [comment]
Most likely a webext only issue. I don't get this on Waterfox with latest legacy version of uBO.

**Comment by rjkpa** [comment]
More likely a regression left out which wasn't patched yet.

**Comment by gorhill** [comment]
Not a regression, neither a webext-only issue, this has been there forever with Chromium. It's just how it's not trivial to associate a tab with a URL for that tab internally. This can be done through webRequest.onBeforeRequest API, or webNavigation.onCommitted API. There is no guaranteed order between these two events, and as a consequence uBO must internally associate the tab and the URL in it from within these two listeners. Doing so causes the duplicate log entry.

**Comment by Ravizz** [comment]
Confirmed on Firefox 58.0.2.
