### ISSUE TITLE
[Feature] Add an address bar for page specific actions

### ISSUE THREAD

**Issue by MikkCZ** [gorhill/uBlock#3203]
The only place to use page specific actions (pause uBO, elements picker, per website switches) is the general toolbar button. The WebExtensions API offers address bar buttons ([page actions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Page_actions)) exactly for this kind of actions. It would be easier to discover per tab/website actions if they are on their own here.

**Comment by gorhill** [comment]
Page actions are supposed to be used only for [extensions which work on a small number of sites](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction):

> Page actions are for actions that are only relevant to particular pages. If your icon should always be available, use a browser action instead.

Furthermore, [I've asked for clarification in the documentation](https://bugzilla.mozilla.org/show_bug.cgi?id=1415132). On Chromium-based browsers, it is not allowed to mix usage of pageAction API with browserAction API.

**Comment by MikkCZ** [comment]
Well, in the current Nightly the page actions can be moved to the page action menu, where are builtin features like Screenshots, URL copy or bookmarking, which are for all pages. I think "particular page" means "the specific page opened in this tab". If the actions are not specific to the particular tab, but general settings, of course you should use the browser action (toolbar button).

**Comment by MikkCZ** [comment]
The page actions are allowed in Firefox for purpose. If this is something that Chromium-based browser do not support at this time, it would be nice to have the page action added programtically in Firefox only for now. If Chromium adds the option to have both page and browser action at the same time, it won't be hard to move it to manifest.json and remove the page specific actions from the toolbar button.

**Comment by gorhill** [comment]
One thing I worry about is causing bloat to the page action menu.

**Comment by MikkCZ** [comment]
By the number of page specific tools in the popup, or by adding the page action itself?

**Comment by gorhill** [comment]
Both? If I add all per-page tools present in the popup in the page action menu, I worry about the bloat this could cause -- uBO is just one extension, a user could have many which add to the page action menu, and there is already those built-in added by the browser.

**Comment by MikkCZ** [comment]
At least some quick enable/disable button would be helpful. I think that's the most used think on websites.

**Comment by gorhill** [comment]
Closing as invalid as per request.
