### ISSUE TITLE
Blocker is too proactive about popups, usually blocking popups that *I* open

### ISSUE THREAD

**Issue by timeshifter** [gorhill/uBlock#3204]
### Describe the issue
Most notably in Hotmail/Outlook.com, virtually *any* link I click on in an email gets killed by uBlock. Gets frustrating, having to manually copy-paste all the time.

### Steps for anyone to reproduce the issue
1. Open an email on Outlook.com that has a link
2. Click the link.
3. Watch popup get killed by uBlock

### Your settings
- OS/version: Win7 Ultimate x64
- Browser/version: Chrome 61.0.3163.100
- uBlock Origin version: 1.14.16

##### Your filter lists
Default

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Did you look at what the logger reports?

uBO does not block popups unless there is a directive to do so in a filter list (hence a filter list issue), or through the no-popups switch (hence your own directive).

I will re-open if you make the case this is a uBO issue, and not a filter list issue or your own choice to block all popups through the no-popups switch.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by timeshifter** [comment]
Well that's no way to handle support.

Where are the logs? They don't appear to be linked anywhere in the plugin's limited UI, and again, I'm only using the default lists.

**Comment by timeshifter** [comment]
So are you gonna help solve a problem or just be a pompous ass? Because there's a problem, and you're not helping me help you figure it out.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by timeshifter** [comment]
Thank you, I was able to identify that `no-popups: outlook.live.com true` is apparently a default rule, and was responsible. I would argue that this is a bad rule to have as a default, for obvious reasons.

**Comment by gorhill** [comment]
> So are you gonna help solve a problem or just be a pompous ass?

You seem to have the wrong idea about this project.

[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> This project is a hobby, do not expect "customer support"-style interaction. Requiring people to investigate as much as possible before opening an issue will more than likely avoid burdening the project with invalid issues or issues unrelated to uBO.

**Comment by gorhill** [comment]
> I would argue that this is a bad rule to have as a default, for obvious reasons.

There is no such rule by default, you have to toggle it on yourself.
