### ISSUE TITLE
Messenger games don't load with uBlock enabled

### ISSUE THREAD

**Issue by wadie** [gorhill/uBlock#3207]
### Describe the issue
Messenger games do not load with uBlock enabled. they usually stay on 0%. after disabling uBlock they load with no issues.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

https://www.facebook.com/messages/t/4Pics1WordOriginal
https://www.facebook.com/messages/t/JigsawPuzzleMessenger

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
https://i.imgur.com/BGN0T5B.png
### Steps for anyone to reproduce the issue

1. Log in to Facebook
2. Go to any Messenger game, like the one I linked to above
3. with uBlock enabled it should not load, freezes on 0% until you disabled uBlock,close the game and reopen it.

### Your settings

- OS/version:  Ubuntu 16.04 (64-bit)
- Browser/version: 56.0 (64-bit)
- uBlock Origin version: 1.14.16

##### Your filter lists

Default filter list only.

**Comment by gwarser** [comment]
Why you think this is not filter issue? Use this https://github.com/gorhill/uBlock/wiki/The-logger to find which one.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
