### ISSUE TITLE
Settings resets every Waterfox launch

### ISSUE THREAD

**Issue by MiraziHeket** [gorhill/uBlock#321]
OS: Windows 7
Browser: Waterfox (x64 version of firefox)
Version: 0.9.8.2

What happens: settings - blacklists, whitelists websites are lost upon closing and launching again browser.

**Comment by Maxhype** [comment]
Same issue on Chrome Canary. uBlock 0.9.8.6 + Chrome Canary x64 45.0.2427.0.

**Comment by MiraziHeket** [comment]
In order to save settings, every change you made on whitelist and on blacklist, you need to click on padlock icon. Here is kind of explanation. Case solved.
http://i.imgur.com/YsywzxC.png
