### ISSUE TITLE
Removing Subscription list not working in latest beta

### ISSUE THREAD

**Issue by troysjanda** [gorhill/uBlock#3213]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
when selcting the trash can to remove list, and selecting apply the list gets a line thru it but does not remove it.

### One or more specific URLs where the issue occurs
not sure
[URL(s) for issue on a specific site are **mandatory**]
not sure
### Screenshot in which the issue can be seen
don't have ability to provide screen sht
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
add a list
attempt to remove list

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
default settings and list with addition of fanboy and steven black
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
Windows 10, firefox 57rc3 
- OS/version: 
- Browser/version: 
- uBlock Origin version: happens on 1.14.19b1 but returning to 1.14.18 solves issue

##### Your filter lists
default settings and list with addition of fanboy and steven black
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none but no csp

**Comment by gwarser** [comment]
$ git bisect good
386e8bee9c17937df4903c2c91ef06a36e9549a7 is the first bad commit
commit 386e8bee9c17937df4903c2c91ef06a36e9549a7
Author: gorhill <rhill@raymondhill.net>
Date:   Thu Nov 9 12:53:05 2017 -0500

    fix #3210

**Comment by uBlock-user** [comment]
I can reproduce it on Chromium too.
