### ISSUE TITLE
[uMatrix for Chromium] hotkeys not working

### ISSUE THREAD

**Issue by leedoyle** [gorhill/uBlock#3215]
Hello! I couldn't find the bug tracker for uMatrix, so I thought I should probably leave it here.

Keyboard Shortcuts don't work in Chromium on Linux (the latest uMatrix 1.0.0 from Chrome Store, and looking at the change log the bug has not been fixed anyway). The only key shortcut working is "_activate the extension_"(which is provided and handled by Chromium itself), others, like 

> Open dashboard, Revert all temporary changes .Temporarily whitelist all, Temporarily whitelist page domain 

don't work at all.
That's really frustrating because it would streamline user experience a lot if these hotkeys actually worked.
It does not seem to be a Chromium issue, as addon hotkeys do work in other addons.
The settings for the hotkeys can be found at chrome://extensions/ at the bottom of the page. 

Sorry for any possible inconvenience this may have caused and thanks for your work!
Best regards

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by leedoyle** [comment]
@gorhill The issue I'm describing has nothing to do with filters or URLs
What additional information should I have provided?

**Comment by gorhill** [comment]
It's invalid because it's here is a uBlock Origin issue tracker -- this is not an issue with uBO.

I've removed the command shortcuts, these were leftover from HTTPSB, and not connected to working code in uMatrix.

**Comment by leedoyle** [comment]
@gorhill  There are many keyboard-oriented people that would prefer to hit one shortcut instead of having to click 4 times with the mouse to temporarily enable all (except for generally forbidden hosts like google analitics) on page, i.e. - one click to show the popup, another click on the "all" field, then click on the reload button and then click somewhere else on page to get rid of the popup.
Is there a hope the shortcuts will be back one day? I believe it would be a nice killer feature as compared to ScriptSafe.
