### ISSUE TITLE
I would like to proofread the crowdin translation of Ublock Origin to Bengali

### ISSUE THREAD

**Issue by sakibarifin** [gorhill/uBlock#3216]
I would like to proofread the crowdin translation of Ublock Origin to Bengali. The translation is hanging for about two years without any approval. I use this extension and would love to see it in my own mother tongue.

**Comment by gorhill** [comment]
Just create an account on https://crowdin.com/project/ublock and contribute however you want, there is nothing more formal than this.

**Comment by gorhill** [comment]
Ok I see you are already in there. There is already a proofreader for Bengali, and he is active, for instance many strings were translated yesterday. Best is that you worked with the existing proofreader. In any case, all this has to be handled on Crowdin, here is not the place.
