### ISSUE TITLE
[Fx Legacy] nsPrefBranch::{get,set}ComplexValue with Ci.nsISupportsString removed in Nightly

### ISSUE THREAD

**Issue by pintassilgo** [gorhill/uBlock#3217]
Firefox 55 introduced `Services.prefs.setStringPref(prefName, prefValue)` and `Services.prefs.getStringPref(prefName)` in [bug 1345294](https://bugzilla.mozilla.org/show_bug.cgi?id=1345294).

Now, Nightly removed `Services.prefs.setComplexValue` and `Services.prefs.getComplexValue` when `Ci.nsISupportsString` is the second argument, see [bug 1414096](https://bugzilla.mozilla.org/show_bug.cgi?id=1414096).

/js/vapi-background.js and /js/vapi-common.js should be fixed.

Example:
https://github.com/gorhill/uBlock/blob/0e078e536d8630e0823a488c6d1cdb222b0b01bb/platform/firefox/vapi-common.js#L124
`this.pb.getComplexValue(key, Components.interfaces.nsISupportsString).data;`
should be replaced by
`this.pb.getStringPref(key);`
to work on Nightly.

With conditionals to not break users from Fx 54-, like 52 ESR.

**Comment by gorhill** [comment]
> Now, Nightly removed

Legacy extensions are not supported on FF57 and above. Nightly is FF58.
