### ISSUE TITLE
Sort out the uBlock's icons.

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#3221]
### Describe the issue

After recent changes I noticed that there is little bit mess if it comes to icons. 

* Legacy Firefox version uses SVG icons
`platform/firefox/img/browsericons/icon16-off.svg`
`platform/firefox/img/browsericons/icon16.svg`
* Chromium uses PNG versions of the same icon in 16px and 24px sizes.
* Opera and Firefox webext uses also PNG version in 19px and 38px sizes.

And there are multiple duplicates of SVG icon including `doc/img/ublock-16.svg` which is thinner version of normal uBO icon. 

---------

My suggestion is to keep one version of `ublock.svg` and `ublock-off.svg` and feed it everywhere. Remove all duplicates SVG icons and PNG versions form the repository. If there are browser bugs that prevent SVG icons to be used they should be reported and fallback PNG versions should be used in the meantime. 

-------

Also for the Firefox webext if you open the addon details it still fetches `https://addons.cdn.mozilla.net/user-media/addon_icons/607/607454-64.png`  you should add 64px line in the manifest to make it happy.

**Comment by gorhill** [comment]
It's a hobby. I don't want that sort of managerial issue to be opened, it feels like someone wants to manage me and tell me how to organize stuff in the repo. I house-keep all the time informally, when I feel like doing it, no need to open issues for this. I am aware of all the things which could be organized better, I could open tens of issues for this, I just address as time pass and as I see fit. Keep issue tracker for actual end product issues please, my actual goal if it's not clear is to lower the pile of issues to low double-digit, and each time that such of non-issue issue keep being opened it just make me dread visiting github.

**Comment by kasper93** [comment]
Sorry if you felt this way, my only intention was to help. Normally I would create pull request, but I follow you long enough to know that you like to do thing your own way so instead I created this issue as a suggestion to consider. As a time passes it is easy to forget about things of such low importance as icons and since you were making related changes I wanted to just point out related changes that could also be done. Because I simply think SVG is better for the job here.

Thank you for making this clear I will refrain from making comments/issues it will certainly save me my personal time.

**Comment by gorhill** [comment]
> Normally I would create pull request

Ok, please make a pull request, I will consider it seriously. Note that all versions of uBO affected by the change will have to be evaluated to find out if they are negatively affected, this means Pale Moon, Sea Monkey, older Chromium versions.

**Comment by gorhill** [comment]
@kasper93 Sorry for having snapped. The reality is that given how these projects have grown, I do need help with development. Your last pull request made me realize you had a good grasp on how things work, so I would appreciate if you join me on the development side.

**Comment by kasper93** [comment]
@gorhill Hey, sorry for late response. The reality is I have often little time to spare. I have one project that I neglected and I fell bad for that. I don't want to make any commitments. That say I can help form time to time, but you can expect me to disappear. 

You can take a look for this SVG patch https://github.com/kasper93/uBlock/commit/7f52c016c8023ceda941c7d4b307a3ce8b519e48
