### ISSUE TITLE
version 1.14.18 and onwards slows Newsfox rss reader

### ISSUE THREAD

**Issue by joiwind** [gorhill/uBlock#3222]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
After updating to v1.14.18 and beyond Newsfox rss reader slows down to a halt and the feeds will no longer update. I realise that this will be difficult to reproduce ...

### One or more specific URLs where the issue occurs but when I "downgrade" to 1.14.12 everything works fine.

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: xp pro sp3
- Browser/version: Palemoon 24.7
- uBlock Origin version: 1.14.18 ?

##### Your filter lists

Default filter lists + FRA plus quite a few others, however the same lists do not cause a problem with v1.14.12 - so I reckon it's not a filter problem.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You are going to need to provide better steps-to-reproduce details:

- What is "Newsfox rss reader" (where is this thing?)
- How do I have to use it exactly to reproduce the issue? (what feed, etc.)
- You say "I realise that this will be difficult to reproduce". Why?

I will re-open when more efforts are made to provide what is asked from you in CONTRIBUTING.
