### ISSUE TITLE
WebRTC filtering

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#3225]
Would it be possible to support advanced WebRTC filtering as part of advanced mode? There doesn't seem to be a WebRTC request type currently, and I'd like to be able to use WebRTC for things like mixer and webtorrents, while blocking everything else.

**Comment by uBlock-user** [comment]
bug tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=707683

**Comment by SoniEx2** [comment]
Firefox?

**Comment by uBlock-user** [comment]
Someone will need to open an issue there.

**Comment by Atavic** [comment]
@SoniEx2 Seen uAssets? https://github.com/uBlockOrigin/uAssets/issues/251#issuecomment-269914097

**Comment by SoniEx2** [comment]
Firefox?

**Comment by Atavic** [comment]
See: https://github.com/gorhill/uBlock/issues/3009#issuecomment-335249546

**Comment by SoniEx2** [comment]
please stop linking google chrome stuff. I'm asking about firefox and only firefox.

**Comment by Atavic** [comment]
>I'd like to be able to use WebRTC for things like mixer and webtorrents, while blocking everything else.

I'll relink your issue to #3009 again, as what are you asking above doesn't exist yet, neither on Chrome nor on Firefox.

**Comment by SoniEx2** [comment]
And what's the relevant firefox bugtracker issue?

**Comment by Atavic** [comment]
There isn't, but you can see the W3C Draft: https://w3c.github.io/webappsec-csp/

**Comment by gwarser** [comment]
@SoniEx2 https://bugzilla.mozilla.org/show_bug.cgi?id=1390801

**Comment by gorhill** [comment]
The `nowebrtc` scriptlet can be used for this.
