### ISSUE TITLE
Pop-up advertising

### ISSUE THREAD

**Issue by Pizuk** [gorhill/uBlock#3226]
Pop-up advertising executives not blocked by uBlock.

Http://www.streaming-foot.club/

Thanks !

**Comment by mapx-** [comment]
add
`||streaming-foot.club$inline-script`

However, in the future report to the filters dedicated repository:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by uBlock-user** [comment]
`streaming-foot.club##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/)`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
