### ISSUE TITLE
[Feature] More granular control over types of content

### ISSUE THREAD

**Issue by AndyScull** [gorhill/uBlock#3228]
Hi, is it possible to add filtering based on content type?
Like in uMatrix - separate images, scripts, etc
For example - I am on a riotpixels.com site. I want to allow scripts only from riotpixels.net and I can't do it even by manually adding a rule in settings (manually changing * to inline-script or any other type of filter deletes the line)
Currently it seems that I can only allow everything or deny everything. please correct me if I missed something in docs.
Like, there are sites requiring scripts from 3rd party domains to work correctly. But I don't want to download images from that sites. Or otherwise, sometimes you need images (for example, button pictures) but don't want to run any scripts from that site.

**Comment by gorhill** [comment]
You disregarded CONTRIBUTING and opened a support issue.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
