### ISSUE TITLE
Improving filter update speed

### ISSUE THREAD

**Issue by terr72** [gorhill/uBlock#3229]
### Describe the issue
It takes at least a minute to complete when starting a manual 3rd-party filter update by pushing the 'Update now' button. It seems like uBlock Origin does a sleep(5) after every single entry in the entry list in order to avoid network DDoS issues. It would be very cool if this could be parallelized (or minimized, at least for different domain resources) in order to speed up this process.

### Your settings
uBlock Origin 1.14.18 on Firefox 52 ESR and Firefox 57 on Linux and Windows with Intel Core i 4-core processors via a 50MBit internet connection.

**Comment by gorhill** [comment]
There is a two seconds delay between each fetch -- I want to be sure updating operation works on slow computer with slow connections. There is a `manualUpdateAssetFetchPeriod` in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings), it default to 2000 (ms), you can lower it to your liking.

**Comment by gorhill** [comment]
No feedback, assuming OP is fine with the advanced setting.
