### ISSUE TITLE
[Firefox] Medium Mode My Rules not syncing through Firefox Sync

### ISSUE THREAD

**Issue by avamk** [gorhill/uBlock#3230]
### Describe the issue

With Medium Mode set up on two Firefox instances, after enabling cloud storage support in uBlock Origin and enabling Firefox Sync, my Medium Mode "My Rules" do not sync.

### Steps for anyone to reproduce the issue

1. I have Firefox 56 installed on two systems. One running [Red Hat Enterprise Linux 7.4](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux) and the other [Manjaro Linux 17.0.6](https://en.wikipedia.org/wiki/Manjaro_Linux), both fully updated.
2. I have Firefox Sync set up on both instances with all options checked, including sync for "Add-ons" checked. Firefox Sync works fine except for the problem described here.
3. I followed the instructions on the wiki [Medium Mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) page exactly to set up my uBlock Origin 1.14.18 to Medium Mode.
4. After that, I ticked "Enable cloud storage support" in both instances.
5. On one machine, I clicked the "Upload to cloud storage" button in the "My rules" tab of uBlock Origin settings. I could see that my rules have been "uploaded" and see an upaded OS/timestamp next to the button like this:

> Linux x86_64
> Tue, 14 Nov 2017, 23:20:15 GMT

(I note that it says "Linux x86_64" instead of my Firefox Sync's machine name, not sure if this is a symptom of the problem?)

6. I initiate a sync in that instance of Firefox to sync those rules.
7. On the *other* machine, I initiate a sync for the Firefox there.
8. I go into the "My rules" tab in that Firefox's uBlock Origin settings but **do not** see the updated settings.
9. I tried clicking on "Import from cloud storage" anyway, and do not see my rules from the other machine.
10. I tried this sync in the reverse direction and it didn't work either.
11. I tried upgrading to the newly released Firefox 57 and this problem persists.

### Your settings

My settings are exactly as specified by the [Medium Mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) page. Plus I enabled the cloud storage option.

- OS/version: RedHat Enterprise Linux 7.4 and Manjaro Linux MATE Edition 17.0.6
- Browser/version: Firefox 56 (also tried Firefox 57)
- uBlock Origin version: 1.14.18

##### Your filter lists

Exactly as specified by the [Medium Mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) page.

##### Your custom filters (if any)

No custom filters.

**Comment by gorhill** [comment]
Please first look into `about:sync-log`, these are time-consuming repro steps and I have already confirmed n the past that Firefox Sync worked properly, so I want you to first rule out issues with Firefox Sync out of uBlock's control.

**Comment by avamk** [comment]
Thank you @gorhill .

> Please first look into `about:sync-log`

OK, I can see the logs but have no idea how to interpret them. Are there certain things to look for?

> Also mind that there are limits with Firefox Sync (throughput and size), and if you are hitting these limits, uBO can't help. You also need to rule out this.

How do I rule this out? Is this also something to look for in `about:sync-log`??

**Comment by gorhill** [comment]
> no idea how to interpret them

I am not better placed, I just see that some logs are named `error-sync-[timestamp].txt` on my side, so just look at the most recent ones, see if there is such error logs, and if the time matches your last operation, then open it and see what it says.

> How do I rule this out?

Save your rules and keep only a handful ones and see if Firefox Sync works.

**Comment by avamk** [comment]
@gorhill Hmmmm, OK I'll do my best and take a look. Thank you!

**Comment by gorhill** [comment]
Any news on this?

**Comment by avamk** [comment]
I tried monitoring my sync logs over several days, but don't see anything specific to uBlock Origin..... and the problem persists. I've asked a question [here](https://redd.it/7cmbk0), and apparently a couple others have the same problem but no solution..... I know you're super busy and thank you for developing this amazing tool, but is there someone else I can ask about this?

**Comment by avamk** [comment]
@gorhill Wow.... After much tribulation, I think I *finally* narrowed it down to something:

The default machine name uBlock assigns to my Firefox installation is "Linux x86_64", for **both** machines. Once I changed the uBlock machine name on at least one of the machines to something else, sync for "My Rules" works!

May I propose adding something to the wiki stating the need to manually name each uBlock instance?

**Comment by gorhill** [comment]
The device name is strictly cosmetic, it's not acted upon when it comes to push or pull data from the cloud -- it's use is only for you so that you know where the cloud data came from, and when it was uploaded.

**Comment by gorhill** [comment]
One thing though. Looking at the code, I realize uBO is using `window.localStorage` to get/set the device name, and I believe this can throw when a user forbid cookie globally or with some other `about:config` setting. I need to see if this can happen, and if so that might explain why some people can't use cloud storage. There is a Firefox issue regarding using `window.localStorage` in extensions when cookies are forbidden.
