### ISSUE TITLE
Errors reported with loading dev build in Chromium - Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by greggsav** [gorhill/uBlock#3232]
### Describe the issue
When loading a stock dev build based on 1.14.19.4 into Chromium, errors are indicated.
![image](https://user-images.githubusercontent.com/20907535/32856863-0f1f99c0-ca14-11e7-87b8-e8c97b6f15c0.png)

The error is in storage.js.  The local variable "re" is not initialized in certain cases.  There is logic to create re but it is only executed once for each instance of the listMatchesEnvironment object and is stored in the reLang property of that object.  

### One or more specific URLs where the issue occurs
chrome://extensions

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

![image](https://user-images.githubusercontent.com/20907535/32856973-5d663eb8-ca14-11e7-9e5e-f028109891b3.png)

### Steps for anyone to reproduce the issue

1. Build the code from 1.14.19.4 for chrome/chromium by using tools/make-chromium.sh
2. Launch Chromium,
3. from chrome://extensions, Load unpacked extensions and select the dist/build/uBlockO.chromium folder, click Open

### Your settings

- OS/version:  Ubuntu 17.10
- Browser/version: Chromium, Version 62.0.3202.89 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)
- uBlock Origin version: 1.14.19.4

##### Your filter lists

Filters are not applicable to this issue.

**Comment by gorhill** [comment]
Thanks for reporting, happy to see putting the dev build in Chrome store paid off.

**Comment by gorhill** [comment]
That was a bad breakage, I will need to always test new installation before I push to the store, I usually just test with an already installed version (once in a while I test new install), while this bug affected badly new installations.

The fix has been pushed to the Chrome store, but it's "pending review", it might take a while. I don't know why the Chrome store feels the need to review an extension with less than 400 users each time I update it.
