### ISSUE TITLE
element picker doesnt work in firefox 56.0 32bit on linux mint

### ISSUE THREAD

**Issue by elypter** [gorhill/uBlock#3234]
when i click on the element picker icon nothing happens. i havent used it in a while so i dont know what introduced it.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by cy7yz2rj** [comment]
Probably same as #2963, just enable cosmetic filtering for the current page/globally then reload.

**Comment by elypter** [comment]
it has been enabled all the time and disabling an reenabling it again doesnt do anything either.
