### ISSUE TITLE
What is happening when I block permanently?

### ISSUE THREAD

**Issue by bythckr** [gorhill/uBlock#3236]
I would like to know the general behaviour of ublock origin. Just to state a recent example.

> uBlock Origin has prevented the following page from loading:
http://www.shareasale.com/r.cfm?B=734319&U=1513362&m=59485&afftrack=&urllink=training.linuxfoundation.org

I choose to block permanently. After which I was lead to the below link:

> https://training.linuxfoundation.org/?SSAID=1513362

I was expecting that ublock will lead me to the _urllink_ which is **training.linuxfoundation.org**. But why did it pass _U_ as _SSAID_ which is **1513362**? Why not block that also?

**Comment by gorhill** [comment]
I can't understand your reported issue, but is sounds like a support issue, not an issue with uBO. Respect CONTRIBUTING please, and also read very carefully what uBO is telling you, it sounds like you did not read properly what strict blocking was telling you.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
