### ISSUE TITLE
search & filter in "My filters"

### ISSUE THREAD

**Issue by dot256** [gorhill/uBlock#324]
please add search & filter in "My filters" like in [Adguard for Opera](https://addons.opera.com/en/extensions/details/adguard/?display=en)

![image](https://cloud.githubusercontent.com/assets/8755264/8056562/9d1234e6-0ea9-11e5-9bb2-90769f5af84a.png)

**Comment by 5t3f4n** [comment]
<kbd>CTRL</kbd>+<kbd>F</kbd> or <kbd>CMD</kbd>+<kbd>F</kbd> works fine in the Dashboard.

**Comment by gorhill** [comment]
As @5t3f4n pointed out, the custom filters are in a plain textarea in the _"My filters"_ pane in the dashboard, you can search them using the built-in browser search feature.
