### ISSUE TITLE
Blocking one specific site

### ISSUE THREAD

**Issue by TheHacki** [gorhill/uBlock#3242]
### Describe the issue
Hello there,(I hope this is the right section) I have an issue with an ad, which dosen't go away, even if i blocked it directly
The ad appears at every video even with specific filters, what am I doing wrong
### One or more specific URLs where the issue occurs
watchbox.de
almost every video
Direct link to one video(random):
https://www.watchbox.de/filme/boulevard-15365.html
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
I open a video, normally, it appears ads.
Then i tried to block them manually without blocking the whole server because then the video doesn't load (ssl.*.damoh.watchbox.de)
### Your settings
I don't have many specific setting, the only thing I edited was
-blocking local IP Adress with WebRTC

- OS/version: Linux Solus MATE 1.18.2
- Browser/version: Firefox 57.0 (64 bit)
- uBlock Origin version: uBlock 1.14.18

##### Your filter lists

Default filter list

##### Your custom filters (if any)
ssl.*.damoh.watchbox.de^$mp4
||ssl.*.damoh.watchbox.de^$mp4
https://ssl.*.damoh.watchbox.de^$mp4
||https://ssl.*.damoh.watchbox.de^$mp4
http://ssl.*.damoh.watchbox.de^$mp4
||http://ssl.*.damoh.watchbox.de^$mp4

Please tell me, what am I doing wrong if you have enough time for my problem
Thanks a lot
TheHacki

**Comment by mapx-** [comment]
You posted in the wrong place, report here:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by TheHacki** [comment]
Then I can just say sorry
