### ISSUE TITLE
[FF] Container tabs integration

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#3245]
I'd like to have separate uBO instances per container. Benefits:

- Block some elements and objects on account A, which runs on container A, but different elements and objects on account B which runs on container B.
- Selectively allow ads for specific youtubers by simply opening their videos in the right container.
- "NSFW" container, with aggressive blocking.

**Comment by gorhill** [comment]
Try `about:profiles`.

**Comment by SoniEx2** [comment]
Profiles can go to hell. Guess it's time to make a webext to run webexts.
