### ISSUE TITLE
Universal selectors not working (see webpage example)

### ISSUE THREAD

**Issue by hundreAd100** [gorhill/uBlock#3247]
### Describe the issue

a universal selector (`##.comments`) not working on the webpage given.
note that the filter IS correct, see screenshot below

conversely, filtering for (e.g.) `co.il##.comments`, `l##.comments` works fine -- there needs to be something before the `##` for it to work (ONLY on ublock, on other adblockers this works fine); tried `*##.comments`, `*|*##.comments` and various other variations, to no effect

ublock problems with this filter may be due to some inline script run by the webpage (as a workaround, `||haaretz.co.il$inline-script` prevents the problem); the filter does work fine on "normal" webpages that do not add via scripts.

### One or more specific URLs where the issue occurs

https://www.haaretz.co.il/news/weather/1.4608509

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/33790536/32984080-c540b780-cca7-11e7-93a6-60a4abe2b137.png)

### Steps for anyone to reproduce the issue

add filter, load page
`##.comments` filter ignored
(hiding via element picker will hide the element, but it will show on successive page reloads)

### Your settings

- OS/version: Microsoft Windows [Version 10.0.16299.64]
- Browser/version: 57.0 64-bit
- uBlock Origin version: 1.14.18

##### Your filter lists

default (clean install)

##### Your custom filters (if any)

none (removed everything), other than the single filter tested

**Comment by okiehsch** [comment]
`@@||haaretz.co.il^$generichide` in `EasyList Hebrew` is the reason the generic filter `##.comments` will not work.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> Use the logger to diagnose/confirm filter-related issues. If something does not work properly with uBO enabled, the first step is to rule out filter-related issues.

Use the logger please next time to rule out filter issue.
