### ISSUE TITLE
[Suggestion] Label the "global" and "local" dynamic filtering rules columns

### ISSUE THREAD

**Issue by Noexpert** [gorhill/uBlock#3248]
A suggestion to label the "global" column as "All sites" and the "dynamic" as "This site".
IMHO it will make it much easier for new users to quickly understand what each one does.

**Comment by gorhill** [comment]
If you take the time to use dynamic filtering after the required reading, you will observe that a global rule "bleed" into the local one, while the reverse is not true. This makes it unambiguous as to which one is global and local. There are also tooltips in top cells.

**Comment by gorhill** [comment]
Duplicate of #840.
