### ISSUE TITLE
uBlock inserts own styles into page messing colors and other stuff up

### ISSUE THREAD

**Issue by Owyn** [gorhill/uBlock#3249]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

when you enable uBlock some weird styles with `!important` get added to some pages, when you disable uBlock - they dissapear.

![76 _proc](https://user-images.githubusercontent.com/1309656/32991962-f7dff922-cd55-11e7-8662-4990466518dd.jpg)

### One or more specific URLs where the issue occurs
http://fastpic.ru

### Screenshot in which the issue can be seen

![76 _proc](https://user-images.githubusercontent.com/1309656/32991962-f7dff922-cd55-11e7-8662-4990466518dd.jpg)

### Steps for anyone to reproduce the issue

1. have Ublock enabled
2. Visit http://fastpic.ru

### Your settings

- OS/version: Win 10
- Browser/version:  Firefox Quantum 57
- uBlock Origin version: uBlock Origin 1.14.19b7

##### Your filter lists

Default filter lists + RUS: RU AdList

##### Your custom filters (if any)

none

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
