### ISSUE TITLE
Product description is being blocked on Staples.com

### ISSUE THREAD

**Issue by dhprototype** [gorhill/uBlock#325]
uBlock is blocking the entire product description area from being displayed on Staple.com page.
http://www.staples.com/Logitech-MK550-Cordless-Desktop-Wave/product_701218

**Comment by gorhill** [comment]
Because of EasyPrivacy's `||ensighten.com^$third-party`.

Report issue to EasyPrivacy maintainers: <http://forums.lanik.us/viewforum.php?f=64>.

Custom for workaround meanwhile: `@@||nexus.ensighten.com/staples2/$script,domain=staples.com`.

**Comment by dhprototype** [comment]
Thanks! Reported at EasyPrivacy's forum.
Using custom filter in the mean time.
