### ISSUE TITLE
Document the left side of the popup interface

### ISSUE THREAD

**Issue by scarf** [gorhill/uBlock#3251]
Could you please document the left side of the popup interface?  For example see the screenshot.  There appear to be several categories at the top, and then a list of the domains at the bottom.  for each of these rows there are 6 columns on the right with green/red/gray colors.  also there are colors associated with the domains on the far left, and various plus and minus signs in the right columns.  the only tips i could see are for the "all" row, where it says the first 3 columns are for global rules and the last 3 columns are for local rules.  
What does it all mean?
Thanks

![screenshot](https://user-images.githubusercontent.com/2446600/33001693-a455a0a6-cd6c-11e7-92ae-a1846574065a.png)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by aggat** [comment]
["Dynamic filtering pane available only to advanced users"](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide)

["Advanced users are expected to read the documentation. This is very important."](https://github.com/gorhill/uBlock/wiki/Advanced-user-features)

**Comment by gorhill** [comment]
No need to post links, there is already a linked labeled "required reading" right aside the _"I am an advanced user"_ setting which must first be enabled to access dynamic filtering. There is no excuse for dismissing this prominent link, dismissing [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), and burden the repo with such an invalid issue.
