### ISSUE TITLE
Requesting official procedure for submitting new lists

### ISSUE THREAD

**Issue by DandelionSprout** [gorhill/uBlock#3252]
I can't find any info out there, on how to submit new filter lists to uBlock Origin's stock filter lists; nor on what the criteria for them are. Therefore I request a clarification of such a procedure (if any), that explains how to submit lists (or if it's completely prohibited to submit any lists), what the criteria are for lists to be accepted, and possibly examples of why some lists are accepted whereas others aren't; possibly as an article on the wiki, or elsewhere. That's all.

**Comment by gorhill** [comment]
There is no procedure. If I feel a list is in widespread use and proven to be maintained since a long time, I may add it as I see fit -- with not bloating the 3rd-party panes as a top concern.
