### ISSUE TITLE
script:contains() does not work in WebExtensions

### ISSUE THREAD

**Issue by haarp** [gorhill/uBlock#3255]
Recent versions of uBlock for Firefox seem to not support script:contains() anymore. As Firefox 57 is out now, I have no way of running a previous uBlock release.

Inline script tag filtering, as described in the [documentation](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering), looks like it should be working. Yet it is not. I *think* this is known already, at least the first WebExtension beta had it in it's changelog. However I could not find any reference or issue report for the release version, so either I am doing something terribly wrong, or this is indeed an issue.

Tested using uBo 1.14.18 in Firefox 54 and 57, with otherwise virgin uBo configs.

If this is known, can you link the corresponding issue # or Mozilla bug report if additional features are yet to be implemented?

Thanks!

**Comment by Halibut80** [comment]
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1286822">1286822 - Remove beforescriptexecute/afterscriptexecute</a>
Use [this](https://github.com/uBlockOrigin/uAssets/issues/618#issuecomment-321842729) as replacement.

**Comment by kowith337** [comment]
`##script:contains()` no longer support in WebExtension (Same as chrom[e|ium])

You need to look for other rules or fallback to Firefox ESR or other forks, e.g. Cyberfox, Waterfox, Pale moon.

**Comment by gorhill** [comment]
This has been documented in the release notes when the webext version of uBO came out.

**Comment by gorhill** [comment]
Documentation updated.

**Comment by uBlock-user** [comment]
WebExtensions is based on Chrome's Extension API, so it doesn't have BSE/ASE by default.

**Comment by gorhill** [comment]
Note that if you are comfortable with javascript, `script:inject(abort-current-inline-script.js, ...)` can be used often to disable specific script tags.

**Comment by gorhill** [comment]
Fixed with a9f68fe02f40472c.
