### ISSUE TITLE
FF 57 - ublock Origin doesn't work

### ISSUE THREAD

**Issue by Lital84** [gorhill/uBlock#3256]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

In FF56 an FF57, uBlock Origin doesn't work, meaning it is installed successfully, but not showing in the FF toolbar and ads are not blocked (in other computers in the house they are)

### One or more specific URLs where the issue occurs
All links
[URL(s) for issue on a specific site are **mandatory**]
https://www.walla.co.il
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
[https://imgur.com/a/FrWii](https://imgur.com/a/FrWii)
### Steps for anyone to reproduce the issue

I don't know how to reproduce. It does work well with FF in another computer with same OS

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 1703, 64-bit
- Browser/version: FF57 stable
- uBlock Origin version: 1.14.18

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none

**Comment by kowith337** [comment]
`##script:contains()` is no longer support in  WebExtension, if you still want to use that rules, find the Firefox ESR build or use Cyberfox, Waterfox, Pale moon and obtain updates from releases page.

**Comment by gorhill** [comment]
Unable to reproduce.

> I don't know how to reproduce.

Sorry I won't be able to help. You will have to investigate on your side, there is something specific on your side causing this.

**Comment by lewisje** [comment]
I noticed this happening with a Firefox profile that I had been keeping around for many versions, and I ended up building a whole new Firefox profile; ideally I'd figure out what was causing this problem and post about it in this Issue.
