### ISSUE TITLE
Possible regression bug: Preview of CSS 'style' filters no longer works

### ISSUE THREAD

**Issue by yourduskquibbles** [gorhill/uBlock#3257]
When using the Element Picker tool, clicking preview on filters that contain the CSS modifying `:style(foo !important;)` tag no longer seems to work. Wondering if this is somehow related to the fix for #3159?

### One or more specific URLs where the issue occurs

https://digg.com/

### Screenshot in which the issue can be seen

Can post animated gif if needed.

### Steps for anyone to reproduce the issue

1. Navigate to 'https://digg.com'
2. Use the Element picker tool to click on the header and add the following filter
`###js--digg-header:style(position: absolute !important;)`
3. Click 'Preview' and scroll down the page, the header SHOULD stay at the top and not be a floating header but in the newest versions of uBlock the preview behavior seems to have stopped working.
4. In order to confirm this is a valid filter that will pin the header to the top of the screen, click 'Create' and reload the page and observe the correct behavior of the header staying at the top of the screen.
5. In previous versions of uBlock you used to be able to click 'Preview' and see the impact before having to create the filter.
6. Is this possibly related to [374e157](https://github.com/gorhill/uBlock/commit/374e157b11833631c98c7c2aa757e5dc18eba1aa) which fixed #3159?

### Your settings

Tested on: 
- Windows 7 
- uBlock Origin dev build 1.14.19.8 on Chrome 62.0.3202.94 (Official Build) (64-bit) AND 1.14.19.b8 on Firefox 57

##### Your filter lists
Default lists

##### Your custom filters (if any)

None

Thank you for looking into this, your plugin is awesome! I have a number of people using your plugin and [my Annoyances filter list](https://github.com/yourduskquibbles/webannoyances) to unsuck the web, one user at a time :)

**Comment by gorhill** [comment]
Unable to reproduce, the header stays at the top with or without the filter.

**Comment by yourduskquibbles** [comment]
Hi @gorhill, thanks for taking a look apologies if my first example did not work.

Can you try reproducing with the following steps on a different site?

1. Navigate to https://www.redditgifts.com/exchanges/manage/#/exchange/secret-santa-2017/
2. Use the Element picker tool to click on the "sticky" header and add the following filter `##.js-header-main.header-main:style(position: absolute !important;)`
3 .Click 'Preview' and scroll down the page, the header under previous versions SHOULD be PINNED to stay at the top and not be a floating header but in the newest versions of uBlock the preview behavior seems to have stopped working and the header remains a floating header while scrolling down after clicking 'Preview'.
4. In order to confirm this is a valid filter that will pin the header to the top of the screen, click 'Create' and reload the page (shift + f5) and observe the correct behavior of the header being 'pinned' to stay at the top of the screen.
5. In previous versions of uBlock you used to be able to click 'Preview' and see the impact before having to create the filter.

**Comment by gorhill** [comment]
Ok, I understand what you mean, with the filter, the top banner should scroll with the rest of the page, not being pinned in the viewport. I will investigate.

**Comment by gorhill** [comment]
The regression was introduce in fix to #2984: <https://github.com/gorhill/uBlock/commit/6112a68faf46d89c58defdd9e14d4342747c9523#diff-3b15596213ed9ba37fb5b8bb1402a6c2L811>.

**Comment by gorhill** [comment]
Good catch, thanks for reporting.

**Comment by yourduskquibbles** [comment]
Thank you @gorhill for the quick fix and all you do for the community!
