### ISSUE TITLE
Dynamic filtering: Quick guide question

### ISSUE THREAD

**Issue by jerkstore369** [gorhill/uBlock#3259]
What is a "noop rule"??

EDIT:
Ok, I found out what it is... but it's crazy, you have to figure out and type stuff you want to "noop" into my filters? You're got to make it easier for the average user. Or at least users who are used to the old noscript. Firstly, the red/yellow/green buttons should have some kind of label, at least mouseover label or something somewhere clearly visible. Second, everything that it allowed or blocked should be visible, not just a + or -, then you can add noop rules through the UI or do I sound completely lost here? Anyways, if you can find a way to do all this visually in the UI please that would be great. Thanks.

**Comment by mapx-** [comment]
noop = no operation

```
noop: exclude network requests from being subjected to dynamic filtering.
It cancels dynamic filtering, but it does not cancel static filtering.
```
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> You're got to make it easier for the average user.

Using dynamic filtering is optional, you don't have to use it, and it's not available by default, so as to allow uBO to be an install and forget extension for the majority.
