### ISSUE TITLE
[Enhancement] "Black list only" mode

### ISSUE THREAD

**Issue by selivan** [gorhill/uBlock#326]
Hello!

Thank you for creating uBlock, it's very useful.

I'm generally not against advertisement in web - it's honest way for site owners to earn money. I'm only against obsessional advertisement: when page if so swarming with banners, I barely can read it's content. It may be nice for uBlock to have "blacklist" mode - no blocking by default(grey icon), and start blocking on explicit adding site to block list by clocking "switch" button.

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except>.

I do not intend to go further than this.

**Comment by selivan** [comment]
Thanks :) I'll try this.
