### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by github-fanuser** [gorhill/uBlock#3263]
I apologize in advance if this is not the correct place to post this question. I am a new user of Github. I recently decided to give uBlock Origin a try in Hard Mode to replace NoScript. I did make one change from the docs...I selected ALL filters EXCEPT Adguard Mobile, Experimental, and Regions.

My question is what is the difference in Choosing Green or Dark Gray? I have read the documentation and I am not understanding clearly. Sites seem to work under both Green and Dark Gray, I can't find any difference. 

Is there a time when I would want to choose one over the other? Can you give me an example when I would want to use Green and example of using Dark Gray. Thanks. Keep up the excellent work on uBO.

**Comment by happysurf** [comment]
In green mode the filter is always OFF, gray mode is ON only for session, red mode is ON always.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
