### ISSUE TITLE
Inbuilt auto Popup Blocker

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#3266]
Is it possible to have an inbuilt popup blocker that automatically stops websites opening additional webpages in the background, without having to use specific rules.
Thanks

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups

**Comment by uBlock-user** [comment]
It's in development - https://bugs.chromium.org/p/chromium/issues/detail?id=756089

**Comment by zero77** [comment]
Thanks, 
> Due to Chromium API limitations, it's not always possible for uBlock Origin to determine for sure whether a new tab being opened is that of a popup, or is the result of a legitimate click on a link by the user.

I am using Firefox not Chromium so, is there a way to enable it by default like the “No remote fonts” option.
Thanks

**Comment by gorhill** [comment]
> is there a way to enable it by default

Go to _My rules_, enter `np-popups: * true`.

**Comment by zero77** [comment]
thanks
