### ISSUE TITLE
[Suggestion] Make "hard mode" clearer in UI.

### ISSUE THREAD

**Issue by jerkstore369** [gorhill/uBlock#3268]
From a novices perspective, from looking at the preferences UI, it's not clear what "I'm an advanced user" checkbox actually does. Why not have something like a bold heading "SCRIPT BLOCKING" and a checkbox that says "Enable (for advanced users only)" or something followed by the same link to the instructions as exists now. Thanks.

**Comment by toshiya44** [comment]
"Advanced users" should be able to sort this out themselves.

**Comment by jerkstore369** [comment]
That's a lazy excuse. It benefits everyone, advanced or less-advanced users, to label things more clearly.
