### ISSUE TITLE
Popup disabling issue

### ISSUE THREAD

**Issue by Matthewus** [gorhill/uBlock#3269]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Enabling the block all popups on this site option makes it impossible to open YouTube videos (clicking on the video title), and embedded  tweets (clicking on the date) to open on a new tab.

### One or more specific URLs where the issue occurs
https://www.theverge.com/2017/10/9/16130500/star-wars-the-last-jedi-new-trailer-rian-johnson-watch

### Screenshot in which the issue can be seen
-

### Steps for anyone to reproduce the issue
- Visit a site with embedded YouTube video
- Enable block all popups on this site option
- click on the title of the YouTube video

### Your settings
Default settings, only the block all popups on this page option enabled (no-popups: www.theverge.com true)

- OS/version: Windows 10 64 bit
- Browser/version: Firefox 57 64 bit
- uBlock Origin version: 1.14.18 and 1.14.19rc0

##### Your filter lists
Default filter lists

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Unfortunately, the page is installing an event listener on the link which "eats" the mouse click events, preventing uBO from knowing that the user explicitly clicked on the link, which is what the no-popups code need to determine that the popup (new tab) is legitimate.

**Comment by gorhill** [comment]
There is no solution for this, same underlying issue as #3282.
