### ISSUE TITLE
No warning for unsaved changes in dashboard

### ISSUE THREAD

**Issue by darkred** [gorhill/uBlock#3271]
### Describe the issue

Currently, if you make changes in "My filters", "My rules" or "Whitelist",
but forget to press 'Apply changes' (or 'Save'),
and then just either switch to another dashboard's tab, or close the browser tab altogether,
then your changes are lost.

_My suggestion is to display a confirmation message/popup in such cases, such as: 
"Your changes have not been saved. To stay on the page so you can save your changes, press Cancel"._

### Steps for anyone to reproduce the issue

1. open uBO's dashboard | "My filters" tab _(or "Whitelist" tab)_
2. add a filter or modify an existing one _(notice that the 'Apply' button indeed becomes active)_ 
3. switch to another dashboard tab, or close the browser tab altogether.
4. switch back to "My Filters" tab (or reopen: dashboard | "My filters") : 
_notice that your changes have been lost_.

Similarly, in dashboard | 'My rules', (which of course works differently than "My filters")
when you press 'Edit' in "Temporary rules" and make some addition/modification but forget to press 'Save',
and then switch to another dashboard tab (and switch back) or close the browser tab, 
your changes are lost.

### Your settings

- OS/version: win10 x54
- Browser/version: Firefox 57 and Chrome 62
- uBlock Origin version: 1.14.18 in both.

**Comment by grauenwolfe** [comment]
Doesn't sound like an issue, sounds like you need to click the "Apply Changes" and "Save" buttons. That's why they are there...

**Comment by darkred** [comment]
> Doesn't sound like an issue, sounds like you need to click the "Apply Changes" and "Save" buttons. That's why they are there...

Do not twist things, that's not what I meant!

&nbsp;

I wrote that:

> 
> Currently, if you make changes in "My filters", "My rules" or "Whitelist",
> but **forget to press 'Apply changes' (or 'Save')**,
> and then just either switch to another dashboard's tab, or close the browser tab altogether,
> then your changes are lost.
> 
> My suggestion is to display a **confirmation message/popup** in such cases, such as:
> "_Your changes have not been saved. To stay on the page so you can save your changes, press Cancel_".

i.e. to get a confirmation message/popup whenever I switch dashboard tabs, or close the browser tab,
in order **to prevent accidentally losing my changes.**
i.e. my reasoning is close to this SO answer "[Warn user before leaving web page with unsaved changes](https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes)", applied both to the dashboard's page _frames_ (the dashboard's tabs) 
and the browser page itself, with the dashboard.

**Comment by uBlock-user** [comment]
An alternative would be to automatically save changes to _My Filters_ tab and other tabs like _Whitelist_ and _My rules_ when tabs are switched.

**Comment by mikhaelkh** [comment]
There's no warning when closing `Advanced settings` tab with unsaved changes.

**Comment by gorhill** [comment]
Declining this one.

**Comment by mikhaelkh** [comment]
Then maybe it's better to move `Advanced settings` to a pane in dashboard visible when `I am an advanced user` is on?

**Comment by uBlock-user** [comment]
> There's no warning when closing Advanced settings tab with unsaved changes.

Why would there be ? There's no adjacent tab/pane to accidently switch over. The only way you would any unsaved setting there is if you close that tab/window.

**Comment by mikhaelkh** [comment]
@uBlock-user, you can switch over to other tabs. When you close browser window, uBO warns when there's unsaved changes in Dashboard, but not in Advanced settings.

**Comment by uBlock-user** [comment]
> When you close browser window, uBO warns when there's unsaved changes in Dashboard, but not in Advanced settings.

True, but the values in Advanced settings are mostly predefined and the tab itself is isloated from any other tabs, so chances of accidenctal loss are minimal to non-existing.
