### ISSUE TITLE
Unable to play video with jwplayer

### ISSUE THREAD

**Issue by molitar** [gorhill/uBlock#3272]
### Describe the issue
Unable to play jwplayer video when uBlock enabled. How can I exclude jwplayer media?

### One or more specific URLs where the issue occurs
https://www.tomsguide.com/us/galaxy-x-foldable-phone,news-24862.html

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: 
Go to url above and attempt to play the video on the foldable phone

### Your settings
My filters
uBlock filters​
​​​​uBlock filters – Badware risks​
​uBlock filters – Privacy​​
uBlock filters – Resource abuse​​​
​​uBlock filters – Unbreak​​​​​
​
Adblock Warning Removal List​​​​​79 used out of 406​​
​​Adguard Base Filters​
​​EasyList​
​​​​
EasyPrivacy

Malware Domain List​​​​​
Malware domains​
​​​​
Adguard’s Annoyance List

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7 Ultimate 64 bit
- Browser/version: Cyberfox 52.4.1 (same core as Firefox with old UI style)
- uBlock Origin version: uBlock Origin v1.14.18

##### Your custom filters (if any)
sankakucomplex.com##cloudflare-app[app-id="no-adblock"]
sankakucomplex.com##script:inject(abort-on-property-read.js, BetterJsPop)

@@||images-amazon.com/images/*/video$object,domain=amazon.com
@@||images-amazon.com/*.mp4$object,domain=amazon.com
||images-amazon.com$object,domain=amazon.com
||images-amazon.com$object,domain=amazon.com
||images-amazon.com$object,domain=amazon.ca
||images-amazon.com$object,domain=amazon.co.uk
||images-amazon.com$object,domain=amazon.co.jp

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
