### ISSUE TITLE
play nice with reader

### ISSUE THREAD

**Issue by Dmole** [gorhill/uBlock#3273]
### Describe the issue
Firefox mobile reader is not filterd by ubo.

### One or more specific URLs where the issue occurs
https://www.google.ca/search?q=oled+laptop

### Screenshot in which the issue can be seen
https://ibb.co/bJsfnm

### Steps for anyone to reproduce the issue
1. android
1. firefox + ublock
1. google search
1. Reader (icon in the address bar)

### Your settings
dark reader theme for oled power saving.

- OS/version: android 8
- Browser/version: firefox 57
- uBlock Origin version: 1.14.18

##### Your filter lists
Default filter lists

**Comment by gorhill** [comment]
That is a browser issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1371786#c36>.

Reader page is not accessible by extensions, this is considered a "privileged" page by the browser.
