### ISSUE TITLE
[Minor] Hangs when many elements were blocked

### ISSUE THREAD

**Issue by mr1snipes** [gorhill/uBlock#3274]
### Describe the issue
When the uBlock icon shows many blocked elements (>2k) it takes a long time until the menu opens after the icon is clicked. After that, the popup menu is unresponsive.
With even more blocked elements (>3k or >4k) i get a warning about an unresponsive script:
![report2](https://user-images.githubusercontent.com/33908434/33212276-30b5e3ca-d11a-11e7-9db1-8564bfcfaf9e.png)
After i reload the page, everything is normal again.

### One or more specific URLs where the issue occurs
https://www.humblebundle.com

### Steps for anyone to reproduce the issue
I think the only thing that's really needed is a large amount of blocked elements (>2k).
Here is how this happens for me:
Visit humblebundle, click on some bundle (not sure if required) and wait.
Do some other stuff, this takes a while (just leave the tab open).
After some time the blocked-elements counter will start to increase and eventually show >2k.
![report](https://user-images.githubusercontent.com/33908434/33212006-01f206aa-d119-11e7-8709-47bc4f748a2c.png)
At some point these requests just start and then there is roughly one each second.
To be clear: it's not the problem that these elements get blocked.
I just wanted to show how you get there.
The corresponding rule is `||pubnub.com/time/*uuid=$third-party` from Fanboy’s Enhanced Tracking List.

It also happens on youtube but the counter increases significantly slower there.
If the counter shows >2k, click on the uBlock icon.
It will take some time until the menu shows.
Wait longer (>4k) and you get the warning.

### Your settings
Using Firefox 57.0 (64-bit) and uBlock 1.14.18.
Other Addons are HTTPS Everywhere (Version: 2017.11.21) and Video DownloadHelper (Version 7.0.0).
System is Arch Linux, up-to-date as of this posting.
I'm using standard settings + Adguard Spyware Filters​​​​​, EasyPrivacy​ Fanboy’s Enhanced Tracking List + dynamic filters.
The rules are
```
* * 3p-script block
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
dropbox.com dropboxstatic.com * allow
steamcommunity.com akamaihd.net * allow
wikia.com nocookie.net * allow
www.humblebundle.com akamaihd.net * allow
www.humblebundle.com google.com * allow
www.humblebundle.com gstatic.com * allow
www.humblebundle.com stripe.com * allow
www.youtube.com google.com * allow
www.youtube.com gstatic.com * allow
```
##### Edit
First rule for dynamic filters. I should really learn markdown.

**Comment by gorhill** [comment]
What would help is that you profile using the Gecko profiler: <https://perf-html.io/>.

I am very skeptical that there should be an issue with uBO's popup, there is no reason it should be affected by the blocked counts. However I think it's possible that other extensions may also have something to do with that warning given that all webext shares the same content process -- this means one inefficient extension can cause other extensions in the same process to appear slow as well.

Another thing to try is to try uBO alone, without the other extensions, and see if you get the same result. As said, the blocked count in uBO should have no hit on performance at all, we are talking about mere counters here.

**Comment by mapx-** [comment]
similar issue on ABP side ?!
https://issues.adblockplus.org/ticket/6067

**Comment by uBlock-user** [comment]
The request counter of uBO blows up for me on https://www.humblebundle.com/books/java-books on Chromium 64.

**Comment by mr1snipes** [comment]
Hi again,
i took another look.
First, just for completeness: there was a rule missing in the post.
The first rule for dynamic blocking is `* * 3p-script block`, i used Markdown wrong.

So, i disabled all addons except uBlock and restarted FF.
Then i did another try. To speed things up i blocked pubnub from the start: `www.humblebundle.com pubnub.com * block`.
Also i didn't open the logger this time.

Sadly the behaviour is unchanged.
Also, i noticed that just by leaving the popup menu open and doing nothing with it, the FF main process eats up one cpu. The load hits 100% but is spiked:
![report_3](https://user-images.githubusercontent.com/33908434/33222870-783044ba-d152-11e7-8abc-ea4b2dc9c3be.png)

I tried to install the profiler but it said that it's not compatible with FF57.
Since i really don't know much about addon development and Web API i'm not sure how to dig further.
I played around with the developer tools but couldn't find anything interesting and just editing the xpi apparently doesn't work.
I will take a look at the profiler regularly to see if it gets an update.

**Comment by gorhill** [comment]
What is the reason for you to use `allow` rules rather then `noop` ones?

**Comment by gorhill** [comment]
Here is a case which is much, much worst than yours, I can get to 10K blocked requests in seconds, and yet I don't experience any hang when opening the popup panel (I have outof-process extensions enabled): <https://www.nfl.com/>.

**Comment by snow-frog** [comment]
Having similar issue on Youtube

**Comment by gorhill** [comment]
This issue is unreproducible, it will have to be fully investigated by whoever can reproduce it, and the case will have to be made it's an issue with uBO itself.
