### ISSUE TITLE
Limit rule to URL

### ISSUE THREAD

**Issue by ololoe** [gorhill/uBlock#3275]
Question: can a hiding rule be limited to a certain URL, not to whole site? E.g. `site.com/viewtopic.php##....`

**Comment by gorhill** [comment]
Answer is no.

Please, respect  [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

No support question on issue tracker please.

**Comment by ololoe** [comment]
Ok, where can they be asked?

**Comment by gorhill** [comment]
It's in CONTRIBUTING...

**Comment by okiehsch** [comment]
> For support/discussions/help, there is /r/uBlockOrigin on Reddit -- this is where I see the most activity for people helping each other regarding uBlock Origin.
 
just read https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
