### ISSUE TITLE
Rewrite URL from Qwant search engine to avoid it knowing which results are clicked

### ISSUE THREAD

**Issue by Okamoi** [gorhill/uBlock#3276]
### Describe the issue

When using [Qwant Lite](https://lite.qwant.com/) with JavaScript disabled, search results' links are prepended with a Qwant redirect that allows them to know which link was clicked.

Links look like `https://lite.qwant.com/redirect/[hash]/[CLICKED_SEARCH_RESULT_URL]?position=X&query=[the_query]&t=web&l=en`, and it would be nice to turn them to just `CLICKED_SEARCH_RESULT_URL` on page loading, kind of like some scripts like Google Analytics get replaced with a neutered, local version that fixes any site breakage. Except this one would be link replacement and the purpose would be privacy protection.

I could see you considering that it's not uBO's job, but there are arguments on the both sides of the coin so I'm bringing this to your attention :)

### Steps for anyone to reproduce the issue

1. Disable 1p scripts and inline scripts using uBO or another add-on
2. Go to [Qwant Lite](https://lite.qwant.com/)
3. Search for anything and look at the URLs of search results: They don't go straight to the relevant websites

### Your settings

- OS/version: Windows 7 64 bit
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.18

**Comment by gorhill** [comment]
This sort of requests has been declined multiple times already, please search the issue tracker before opening a new issue. This task is best taken by a dedicated extension.

**Comment by Thorin-Oakenpants** [comment]
@Okamoi  Use Quant Lite with only css + images allowed - no JS, XHR etc. [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/) | [GitHub](https://github.com/sblask/webextension-skip-redirect) will remove any tracking

![skipredirect](https://user-images.githubusercontent.com/16656956/33236600-52e18d88-d2bd-11e7-9c3c-ab97af7ba73b.png)
