### ISSUE TITLE
Jumps in memory consumption

### ISSUE THREAD

**Issue by logan344** [gorhill/uBlock#3277]
Sometimes with two open tabs, the blocker can consume 64 MB of memory, and sometimes with 5-6 tabs, only 47 MB. Why?

I'm using the latest version of google chrome
and version ublock 1.14.18

and what is the average memory consumption should be?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Luckz** [comment]
As a question, off the top of your head, without any research, how much more memory do you feel uBlock takes? I tried starting a FF59 nightly with and without uBlock, and having it enabled or enabling it at runtime seems to add an extra 150-250 MB (~14%). My test session has about 5000 inactive tabs.

=> My Firefox 59 nightly / 5000 inactive tabs / 5 tabs loaded with uBlock enabled peaks at about 1750 MB during startup, goes down to 1350 MB after a bit of idleness. This is versus 1150 MB on the non-uBlock version.
I'm neither looking for support nor complaining, merely wondering if this is expected.

**Comment by Hrxn** [comment]
Just a ballpark estimate, but yes those numbers look reasonable to me..
