### ISSUE TITLE
uBlock Origin causes video and audio on any webpage to be out of sync after a while.

### ISSUE THREAD

**Issue by PlainBread** [gorhill/uBlock#3278]
As the title states, when viewing a video online on websites such as Twitch or YouTube, after a short amount of time (I haven't measured this exactly, but I'd estimate 10-15 minutes) the video and audio are noticeably out of sync (audio is ahead of the video by a few seconds).

This issue only occurs when uBlock Origin is enabled. When it is disabled through the Chrome extension menu there is no delay issue.

### Steps for anyone to reproduce the issue

1. Open a video on YouTube
2. Watch for 10-15 minutes

### Your settings
- OS/version: Windows 10 64-bit
- Browser/version: 62.0.3202.94 (latest)
- uBlock Origin version: uBlock Origin v1.14.18

##### Your filter lists

Default filter lists.

##### Your custom filters (if any)
Default.

**Comment by gorhill** [comment]
This is unactionable. uBO just block/allow network request -- it doesn't control media playback at all, it's not hooked so deep in the browser code so as to have any say in how video/audio is synchronzed. If you think this causes your issue, report to browser devs.

**Comment by HyperScorpio** [comment]
It does the same thing even opening the youtube page as normal we do. This sucks.
