### ISSUE TITLE
uBlock blocks first line of Yahoo Mail inbox listing

### ISSUE THREAD

**Issue by terrillmoore** [gorhill/uBlock#3279]
First, thanks very much for this great tool.

### Issue Description
When using ublock with yahoo's web mail and Firefox, default settings, the first line of the inbox is not rendered. Disabling ublock fixes the problem. I have not tested with other browsers.

### One or more specific URLs where the issue occurs
https://mail.yahoo.com

### Screenshot in which the issue can be seen

Attached find two screen shots: one of correct behavior (with uBlock disabled), another with incorrect behavior (uBlock enabled).

#### uBlock disabled:
![image](https://user-images.githubusercontent.com/19333103/33242828-c6b7f928-d2a8-11e7-9af3-674e4189df79.png)

#### uBlock enabled
![image](https://user-images.githubusercontent.com/19333103/33242817-a3a94324-d2a8-11e7-88d9-f62e926f5f79.png)

Curiously, the "missing first line" appears momentarily then vanishes.

Here's the log. I suspect that the yellow line is the culprit because it seems to appear at the moment the line vanishes.

![image](https://user-images.githubusercontent.com/19333103/33242921-043502ea-d2aa-11e7-86b9-f3915fb34e0b.png)

### Steps for anyone to reproduce the issue

1. Install uBlock on Firefox, default settings, and enable it.
1. Browse to mail.yahoo.com
1. note that the first line of the inbox is not displayed.

### uBLock settings
```json
{
  "timeStamp": 1511718882541,
  "version": "1.14.18",
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": [],
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "ublock-abuse",
    "user-filters",
    "assets.json",
    "public_suffix_list.dat",
    "ublock-resources",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "malware-0",
    "malware-1",
    "plowe-0"
  ],
  "hiddenSettingsString": "assetFetchTimeout 30\nautoUpdateAssetFetchPeriod 120\nautoUpdatePeriod 7\nignoreRedirectFilters false\nignoreScriptInjectFilters false\nmanualUpdateAssetFetchPeriod 2000\npopupFontSize unset\nsuspendTabsUntilReady false\nuserResourcesLocation unset",
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nmail.yahoo.com\nmoz-extension-scheme\nopera-scheme\nvivaldi-scheme",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": "",
  "filterLists": {
    "ublock-abuse": {
      "off": false
    },
    "assets/user/filters.txt": {
      "off": false
    },
    "assets.json": {
      "off": false
    },
    "assets/thirdparties/publicsuffix.org/list/effective_tld_names.dat": {
      "off": false
    },
    "assets/ublock/resources.txt": {
      "off": false
    },
    "assets/ublock/filters.txt": {
      "off": false
    },
    "assets/ublock/badware.txt": {
      "off": false
    },
    "assets/ublock/privacy.txt": {
      "off": false
    },
    "assets/ublock/unbreak.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "off": false
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "off": false
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "off": false
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "off": false
    },
    "assets/ublock/experimental.txt": {
      "off": true
    }
  }
}
```

- OS/version: Windows 10 1709 x64 (build 16299.64).

- Browser/version: 57.0 (64-bit)

- uBlock Origin version: v1.14.18, installed via Firefox.

##### Filter lists

See above json; all are default.

##### Custom filters (if any)

None

**Comment by gorhill** [comment]
Filter issue, report to filter list maintainers please: <https://forums.lanik.us/viewforum.php?f=64>.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
