### ISSUE TITLE
The no-popups rule blocks "Open in a new tab" user action

### ISSUE THREAD

**Issue by Okamoi** [gorhill/uBlock#3282]
Hi,

### Describe the issue

With `no-popups: * true` it becomes impossible to open a new tab by highlighting text that happens to be a URL, right clicking it and selecting `Open link in a new tab`. The issue also occurs when opening in a new contextual tab or in a new window, private or not.

It does not happen with "Search with ... for ..." or the regular `Open link` in current tab.

### One or more specific URLs where the issue occurs

Any URL that can be highlighted and right clicked in order to be opened in a new tab.
e.g. `https://github.com/gorhill`

### Steps for anyone to reproduce the issue

1. On a default profile with default uBO configuration, set the dynamic filtering rule `no-popups: * true`
2. Open uBO's logger
3. Highlight the following text, right click it and select "Open link in a new tab": `https://github.com/gorhill`
4. See that the new tab is not opened. uBO's logger shows that the no-popups rule has been triggered

It would be nice if uBO could detect this and open that kind of pop-up, which is reported as such by browsers but arguably it's not a pop up any more than a middle click on a link such as [this](https://github.com/gorhill) is. Since middle click works in spite of the no-popups rule, it would be coherent to unify behaviour if possible.

Thanks for looking into this!

### Your settings

- OS/version: Windows 7 64-bit
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.18

**Comment by gorhill** [comment]
Sorry but there is no solution for this, aside disabling the no-popups switch when it interferes negatively with your browsing. That switch is meant to be used for hard cases of popup blocking, for those sites which constantly evades the filters. There are negative side effects as a result, and the one you are reporting is it.

**Comment by Okamoi** [comment]
Ok, thanks anyway :)

Is it related to #3165 ?

> It's a Firefox-specific issue. There so much uBO can do to deal with the way Firefox API fires the tabs.onUpdated event.

Should I bring this up to Mozilla so they alter some API in some way ?

**Comment by gorhill** [comment]
> Should I bring this up to Mozilla so they alter some API in some way ?

Ideally from my point of view, if there was a blocking `tabs.onBeforeCreate` API with ability to block the attempt that would be great -- well that would be great for all blockers -- but I am just assuming this would be not really considered.
