### ISSUE TITLE
uBlock Protector ?

### ISSUE THREAD

**Issue by xDarkARG** [gorhill/uBlock#3283]
AAK-Cont filter lists disappeared to uBlock Protector

![](https://i.imgur.com/FaO9xDX.png)

**Comment by phonphen** [comment]
AAK-Cont Is Discontinued [#3241](https://github.com/gorhill/uBlock/issues/3241)

**Comment by xDarkARG** [comment]
and now how we defend them from the anti adblock

**Comment by gorhill** [comment]
Please always read the release notes -- they always contain important information.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
