### ISSUE TITLE
Suggestion: option to mask ads instead of blocking them on sites that check for an ad blocker

### ISSUE THREAD

**Issue by scippie75** [gorhill/uBlock#3284]
Some websites won't load if you use an ad blocker. They probably notice that the content is not being downloaded.

To fight back, I would suggest not blocking the ads, but not showing them either. Images can just not be shown on screen but get loaded in an invisible buffer, video's can be just masked with a 'commercial' countdown, not showing the video and sound. They lose money paying for the commercials and the bandwidth, and they won't make any money because everyone is watching a blank commercial.

This could be a website-specific setting. A list of those websites could be maintained to automatically do this for users.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
It has been known to be a bad idea for literally years: https://adblockplus.org/forum/viewtopic.php?t=8620
