### ISSUE TITLE
NSFW not closed popup

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#3287]
uBo 1.14.19.101
chrome 63

go to `http://imgadult.com/img-5a1a3afb33591.html`

I added these filters:

```
/url2.php*$popup
||imgadult.com^$script
@@||imgadult.com/newimg.js.php$script
@@||imgadult.com/js/jquery$script
```

click "continue...." at the top
sometimes you have to click twice to get the image in the original tab
A new tab is opened something as `http://imgadult.com/url2.php?i=7` which is not closed by the first filter !

In the original tab finally I get the wanted image.
Click on page => ...surprize => a popup is quickly closed by ...the first filter.

Why this behaviour ?

**Comment by gorhill** [comment]
It's a bug in uBO, this needs fixing. The bug is that uBO wrongly detects `http://imgadult.com/url2.php?i=7` as not different than `javascript:;`, because it tries to find a `://` in the URLs.
