### ISSUE TITLE
whitelist deprioritization & subscription weighting

### ISSUE THREAD

**Issue by sanitizetheweb** [gorhill/uBlock#3289]
I subscribe to many filter lists.  Some of these have built-in whitelists.  Some block items which others whitelist.

How do I give weight to block rules over whitelists?  How can I adjust various priorities?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
Find the whitelisting filters and either create a block rule with `$important` or copy paste the whitelisted with `$badfilter` directive
