### ISSUE TITLE
Can we block behind-the-scene requests through dynamic url filtering?

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#329]
In the below case, i am not able to block behind-the-scene requests through dynamic url filtering.
### Steps To Reproduce:
1. Open Network Request logger
2. open a new tabl and goto https://github.com/gorhill/uBlock/releases
3. observe in request logger that below request logged as behind-the-scene and of type <b>websocket</b>
   <code>network request: https://live.github.com/_sockets/Nzc5NjMwOmMzYjRiOGM2OTBjMGU3Yzg2ZmE4Y2NhYTdlNWFkNzc3OjU1ZmE0NWM5Y2VhM2NkMGZkNGM2OWE2Njc1YThmNzNkYzlkNzgxNWVjZmE4NGEyZDFlNDM5ODNmZDU5Yzc5N2I=--fee6f9a1da9932f96bc72e98e9f8395936c4d369</code>
4. below rule created thru dynamic filtering url - <br>
   <code>behind-the-scene https://live.github.com/_sockets websocket block</code>
5. refresh the page described in step 2.
6. you will still see the request pass through and not blocked.
##### Note:

When observed this request thru firefox dev console, the data transferred (response) is 0KB irrespective of whether rule (As said in step 4) is present or not.
##### Config:

uBlock  (0.9.8.7 dev 5) - 3p Scripts & Frames blocked by default along with images.
FF v38.0.5, W7

Let me know if you need more details.

**Comment by androidland** [comment]
yes you can,
https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests

**Comment by harshanvn** [comment]
thanks. i did have whitelisted behind-the-scene scope. hence the issue.

**Comment by gorhill** [comment]
@harshanvn 

Glad to see you back by the way.

**Comment by harshanvn** [comment]
@gorhill 

thank you. I was away for couple of weeks. Got recently married :)
