### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by github-fanuser** [gorhill/uBlock#3290]
I am not familiar with Github enough to know how to post. I am not sure if this is where I need to post feature requests; so please forgive me if this is incorrect.

I recently started using uBO in advance mode (Hard) to replace NoScript as a script-blocker. FF 57 is not compatible with the NoScript v5x and v10 is a little bit more confusing and not feature complete. 

I am not sure if this has been asked before, but is there a way to have the uBO blocked window/tab to close automatically?

Also, what about adding Clickjacking and ABE protection? Thanks.

**Comment by jjohns71** [comment]
Wrong place to ask questions like this, the github issue tracker is for bug reports only.

Try asking your questions on https://reddit.com/r/uBlockOrigin

Please read CONTRIBUTING and close this issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
