### ISSUE TITLE
Conflict between uBlock and Imagus add-on on Yandex.ru in Firefox

### ISSUE THREAD

**Issue by RJ2k6** [gorhill/uBlock#3291]
### Describe the issue

The Imagus add-on is not work correctly with pictures on site yandex.ru when uBlock turned on. If uBlock to turn off, there is no problem. Problem with yandex site only.

### One or more specific URLs where the issue occurs

https://yandex.ru/images/search?text=pictures&rdrnd=671448&redircnt=1511895607.1
Choose any of images.

### Screenshot in which the issue can be seen

ublock turned off: http://s018.radikal.ru/i520/1711/02/1d2d013d698f.png
uBlock turned on: http://s018.radikal.ru/i522/1711/b2/1cd873091403.png

### Your settings

- OS/version: Win7 x64
- Browser/version: Firefox 53.0.3 and 56.0.2
- uBlock Origin version: 1.14.18
- Imagus 0.9.8.59 (https://addons.mozilla.org/ru/firefox/addon/imagus/)

##### Your filter lists

Default filter lists without any additions.

##### Your custom filters (if any)
No custom filters.

**Comment by Atavic** [comment]
Image URL with Tour Eiffel has a redirection:

```
https://yandex.ru/images/search?text=best-wallpaper%20tour&wp=wh16x9_1366x768&img_url=https%3A%2F%2Fst.depositphotos.com%2F1038117%2F2849%2Fi%2F950%2Fdepositphotos_2849
```

**Comment by RJ2k6** [comment]
Yes. Imagus lets to open full size image without clicking on link. Just put cursor over preview. Google pictures is the same: https://www.google.ru/imghp?hl=ru&tab=wi And there is no any problem with google.

**Comment by gorhill** [comment]
A cosmetic filter is causing your issue.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
