### ISSUE TITLE
[Suggestion] Automatically block session replay scripts

### ISSUE THREAD

**Issue by bobsage123** [gorhill/uBlock#3292]
Article for justification - https://www.bleepingcomputer.com/news/technology/popular-websites-are-recording-your-every-move/

Some sites\scripts already gathered - https://gist.github.com/gunesacar/0c67b94ad415841cf3be6761714147ca

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
