### ISSUE TITLE
[Japanese] Seconds on the logger page not showing issue.

### ISSUE THREAD

**Issue by eEIi0A5L** [gorhill/uBlock#3293]
### Describe the issue
Seconds of the logger page is not showing on Japanese fonts. Could you expand the width of 
the column a little bit? Thanks!

### One or more specific URLs where the issue occurs
moz-extension://ff2815cd-8906-4f67-9cb9-ddb17fb583b8/logger-ui.html#tab_196

### Screenshot in which the issue can be seen
(attached)
![default](https://user-images.githubusercontent.com/30253227/33347353-f126ccf0-d4d5-11e7-9940-d78059e5c1b0.jpg)

### Steps for anyone to reproduce the issue

1. Open the logger page.

### Your settings

- OS/version:  Windows 10 64bit Japanese
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.18

##### Your filter lists

EasyList

**Comment by gorhill** [comment]
Can you tell me the font face used by the browser? (use the browser style inspector).

**Comment by eEIi0A5L** [comment]
It is "Meiryo" font.
![22](https://user-images.githubusercontent.com/30253227/33349315-e952822e-d4dc-11e7-8a8c-d0e1d33faadb.jpg)

**Comment by yasmise** [comment]
I'm not sure I'm doing right, but changing `css/logger-ui.css` as follows works fine for me.

Line 122--124:
```
#netInspector table > colgroup > col:nth-of-type(1) {
    width: 5.2em;
    }
```

Line 137--139:
```
#netInspector table > colgroup > col:nth-of-type(6) {
    width: calc(100% - 16.2em - 20%);
    }
```

![logger_changed](https://user-images.githubusercontent.com/22886576/33352121-c3acf03c-d4ea-11e7-884e-593b4b2c002b.png)

Tested with uBlock Origin 1.14.19rc2 with this change, on Firefox 57 and Chrome 62.0.3202.94, on Windows 10 Home Japanese. Font is Meiryo.

**Comment by eEIi0A5L** [comment]
Works fine!

I modified uBlock Origin 1.14.18, changed css/logger-ui.css as you said above. It worked fine here!!
Thank you so much! Now I close this issue.

![33](https://user-images.githubusercontent.com/30253227/33352843-3974d44e-d4ee-11e7-9bdf-86f570b79655.jpg)

**Comment by yasmise** [comment]
Thanks for your confirmation.
But, could you re-open this issue? gorhill will close after he/she makes changes to the source code.

**Comment by eEIi0A5L** [comment]
Sorry. I re-opened.

**Comment by gorhill** [comment]
The ideal fix would be one where I don't have to guess the width.

I tried `width: min-content;`, but unfortunately it didn't work, that would have been perfect fix because there would be no need to guess the width.

**Comment by yasmise** [comment]
Well, I played with logger-ui.css and found that this seems working.
But I couldn't tell this is expected behavior or not, so I'm feeling that "forcing a specific font" would be safer fix.

```
#netInspector table {
    border: 0;
    border-collapse: collapse;
    direction: ltr;
    table-layout: auto;   /***** changed from fixed to auto *****/
    width: 100%;
    }

#netInspector table > colgroup > col:nth-of-type(1) {
    width: 5em;
    }
#netInspector table > colgroup > col:nth-of-type(2) {
    width: 2.5em;
    }
/***** comment out
#netInspector table > colgroup > col:nth-of-type(3) {
    width: 20%;
    }
*/
#netInspector table > colgroup > col:nth-of-type(4) {
    width: 2.5em;
    }
#netInspector table > colgroup > col:nth-of-type(5) {
    width: 6em;
    }
/***** comment out
#netInspector table > colgroup > col:nth-of-type(6) {
    width: calc(100% - 16em - 20%);
    }
*/

/***** added *****/
#netInspector tr td:nth-of-type(3) {
    min-width: 15vw;
    max-width: 15vw;
    }
#netInspector tr td:nth-of-type(6) {
    min-width: 50vw;
    max-width: 50vw;
    }
```

**Comment by uBlock-user** [comment]
Were the fonts changed for the logger page ? I'm seeing a different font in the logger on v1.14.21.101.
