### ISSUE TITLE
easylist does not update

### ISSUE THREAD

**Issue by deningrad82** [gorhill/uBlock#3294]
I use a linux machine based on Ubuntu. I use Firefox and ublock origin since long time. I am experiencing, since some months, an issue with easylist. I does not update. I have also chromium installed and easylist updates fine. all the other lists updates fine. Before I was frozen with an update of the 23/08/17. for some reason unknown to me on the 08/11/17 easylist got updated. now it is frozen since then.

I have tried to reinstall both the browser and the OS itself. I also updated Lubuntu from 17.04 to 17.10. same issue. In the same machine I have anyway chromium installed and ublock origin updates easylist just fine.

PS before I used to use easylist without element hides, I do not know if it can be useful.

![screenshot from 2017-11-29 11-44-38](https://user-images.githubusercontent.com/25414879/33373632-b937683e-d4fa-11e7-940f-806ccd9731db.png)

- OS/version: Lubuntu 17.10
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.18 , also the current RC2, and also with previous versions in the last few months

**Comment by gorhill** [comment]
You will need to investigate more on your side -- it's something specific on your side causing this.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Use the browser console (Network category), use uBO's logger.

**Comment by gorhill** [comment]
You are also not detailing the exact repro steps you performed that ledt to you to conclude that EasyList is not updating.

**Comment by Znrl** [comment]
The List from november 8 gets shiped with uBlock so it got updated with uBlock.
Since then it never got updated since then.
Probably you are running Firfox in Private Mode? It can't update lists then.

What I noticed is that in
filter-lists.json
The URL of the EasyList doesn't start with https:// unlike any other.
Could that prevent it from beeing loaded und included in the releases?

**Comment by Remu-rin** [comment]
> Could that prevent it from beeing loaded
Nope, filter-lists.json file is deprecated and not used AFAIK, see https://github.com/gorhill/uBlock/blob/master/assets/assets.json

**Comment by Znrl** [comment]
OK, thx.
The raw link shows the old (Nov 8) List.
Sorry if this is a stupid question but does this mean it gets updated manually from time to time?

I'm one of the "private mode always on" users and it's a little annoying that filter lists can't be updated for now until mozilla fixes that.

**Comment by deningrad82** [comment]
Hi,
exactly, I am always in private mode.
I have tried to update ublock origin's lists in "remember the history" mode and easylist got updated

**Comment by deningrad82** [comment]
strangely, if I switch back to "remember the history" mode and I update easylist to the last available list, if I then go back to incognito mode and and check easylist , it shows me that it is not updated since the 8th of November. than I go back to "remember the history" mode and the easylist version is the today's version (2nd of December).

**Comment by Znrl** [comment]
Yes there is a known issue with firefox this is mainly on mozillas side and you will need to wait.
See: https://github.com/gorhill/uBlock/issues/3071
