### ISSUE TITLE
excessive opening of the tab

### ISSUE THREAD

**Issue by Artlant** [gorhill/uBlock#3295]
- OS/version:  Archlinux
- Browser/version: Chromium Version 62.0.3202.94 (Developer Build) (64-bit)
- uBlock Origin version:  v1.14.18

![screenshot from 2017-11-29 16-46-18](https://user-images.githubusercontent.com/13064767/33380785-dfecd138-d524-11e7-814f-4ad9d1b4fa52.png)

Hello! 
I have suffered for a long time but it bothered me (strange but probably only me). When you open the pages options uBlock, to redirects chrome://extensions/ to redirect to the popup extensions and open to the setting uBlock. I have a question - why to open extensions page (and popup "options_ui")? why not open the options page to direct?
Regards Raingart

**Comment by gorhill** [comment]
By design. uBO's options can only fit in a whole tab, so redirection is needed to make the whole tab open rather than a useless embedded frame in the `chrome://extensions/` page, which is forced upon by Chrome.

**Comment by Artlant** [comment]
but you can open a link directly `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html` pointing at manifest `"options_page": "dashboard.html",` not using `options_ui` . Or I'm wrong?

**Comment by uBlock-user** [comment]
This doesn't happen on uMatrix, so why only with uBlock Origin ?

**Comment by gorhill** [comment]
<https://developer.chrome.com/extensions/optionsV2#migration>:

> At least until Chrome 40 is stable, you should specify both the `options_ui` and the `options_page` fields. 
> 
> Older versions of Chrome will only recognize `options_page`, and only open in tabs. Chrome 40 and onwards prefer to use the `options_ui` field if it's specified.
>
> [...]
>
> In a future version of Chrome, any extension which specifies options_page will change to match the options_ui behavior - most importantly, they will always be embedded in `chrome://extensions` - so migrate as soon as possible.

@uBlock-user uMatrix still uses `options_page`, but it also needs to move to `options_ui`, as stated by Chrome documentation.

**Comment by Artlant** [comment]
@gorhill Oh, I see. The question is closed
Can I ask one more question? why uBlock access to the file system? Namely manifest `"optional_permissions": [ "file:///*" ],`

**Comment by gorhill** [comment]
uBO does not access the file system on its own, the option exists only to let you import filter lists which URL is a file on your computer.

**Comment by uBlock-user** [comment]
@gorhill So you're saying the uBO behavior will happen with uMatrix soon ? That sucks.

**Comment by jspenguin2017** [comment]
But why is a new tab needed? Why not just replace the current tab (`chrome://extensions`) with the dashboard?
