### ISSUE TITLE
New Version of Firefox blocking manual Installation.

### ISSUE THREAD

**Issue by Indevious** [gorhill/uBlock#3296]
### Describe the issue
Same as title, also seems the program isn't compatible on the add-on page.

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
N/A

### Steps for anyone to reproduce the issue

Try and install manually through github or on the add-on page.
Get a learn more or OK message that can send you to the signed add-on help page.

### Your settings

N/A

- OS/version: Windows 10
- Browser/version: Firefox Quantum
- uBlock Origin version: N/A

##### Your filter lists

N/A

##### Your custom filters (if any)
N/A

**Comment by gorhill** [comment]
Unable to reproduce. uBO is not responsible for AMO malfunctioning, reports your issue to Firefox devs: <https://github.com/mozilla/addons-frontend/issues>.
