### ISSUE TITLE
Whitelisting a local IP address does not work

### ISSUE THREAD

**Issue by broadstairs** [gorhill/uBlock#3299]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
The problem is that I need to access my router via a local IP address but accessing it does not work unless I turn off uBlock on it, so I decided to add the local IP address to the whitelist. However when I access the router again uBlock is still blocking and the log function does not display.

### One or more specific URLs where the issue occurs
The url is simply the IP address and individual pages from the router do not show.
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings] All my settings are default as per the initial install

- OS/version: Windows 7
- Browser/version: Firefox 56
- uBlock Origin version: 1.14.20

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
All filters are as set on install, no changes

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
I can whitelist my router IP address just fine.

Investigate more on your side.
