### ISSUE TITLE
uBlock temporarily blocking disabled breaking downloads/save as

### ISSUE THREAD

**Issue by CB49** [gorhill/uBlock#3302]
uBlock, when blocking disabled temporarily, presents a problem when downloading. Refer to the images below.

The URL that has presented problems to me is [https://vjs.zencdn.net/6.4.0/video.min.js](https://vjs.zencdn.net/6.4.0/video.min.js)

As you can see below, I have the Japanese filters enabled (I have every filter enabled).
![image](https://user-images.githubusercontent.com/25035681/33469415-95cf5b2c-d617-11e7-87fd-9e39e21e069f.png)

Upon selecting `Temporarily`, it takes me to the JS file, as seen below.
![image](https://user-images.githubusercontent.com/25035681/33469473-f9f296e6-d617-11e7-8387-4653c8f65293.png)

When I want to save the page (Ctrl-S), which, once again, is a JS file, it shows me that the download has been completed.
![image](https://user-images.githubusercontent.com/25035681/33469524-41be2d8c-d618-11e7-8776-10e0141a7967.png)
 
But when I clicked on the file, it told the file was removed. I tried a couple times again with no success.
![image](https://user-images.githubusercontent.com/25035681/33469550-548744a8-d618-11e7-9476-cf7da22c8a94.png)

I determined it to be uBlock after disabling all my extensions vs having only uBlock enabled. The file successfully downloaded after disabling uBlock.

My information is as follows:
OS: Windows 10 Pro Version 1703 Build 15063.729 (64-bit)
Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
uBlock: uBlock Origin v1.14.18

Filters, rules, and whitelist are empty. All filters enabled (default+3rd-party filters). Settings are as follows.
![image](https://user-images.githubusercontent.com/25035681/33469813-e9239264-d619-11e7-802b-f3df87ab870d.png)

Thank you for your help.

**Comment by uBlock-user** [comment]
Nothing to do with uBlock, filterlist issue. Add `||zencdn.net^$badfilter`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by CB49** [comment]
Really? But, do filters have the ability to do this?

**Comment by gorhill** [comment]
Use the logger to diagnose your filter issues -- and please respect CONTRIBUTING, this is not the place for filter issues.
