### ISSUE TITLE
UBO can not update itself on chrome?

### ISSUE THREAD

**Issue by SJH114488406** [gorhill/uBlock#3304]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

i have to delect the .18 version to re-install the new version of .20

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
