### ISSUE TITLE
(SeaMonkey) Logger inspector is just blank

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uBlock#3306]
### Describe the issue
Since uBlock Origin 1.14.20, the logger inspector is just blank and clicking the buttons doesn't change that.

### One or more specific URLs where the issue occurs

https://www.seamonkey-project.org/releases/seamonkey2.49.1/

### Screenshot in which the issue can be seen

![ublock-origin-logger-inspector-blank](https://user-images.githubusercontent.com/16628411/33512256-67b15504-d6fa-11e7-8ef5-cbc38efddcdd.png)

### Steps for anyone to reproduce the issue

SeaMonkey 2.49.1
new profile

1) install uBlock Origin 1.14.20 or 1.14.21b0
2) open the popup, click to open the logger
3) reload the existing page from the logger
4) toggle to the logger inspector

**Expected results:** DOM of the page should be shown, and should be able to go through and see what cosmetic filters are in effect, if any.

**Actual results:** see screenshot.  I tried adding the following random cosmetic filter for that page, but it does not change the result:
```
www.seamonkey-project.org##font > b
```
uBlock Origin 1.14.18 works as expected.

### Your settings

- OS/version: Linux x86_64
- Browser/version: SeaMonkey 2.49.1
- uBlock Origin version: 1.14.20 or 1.14.21b0

##### Your filter lists

default

##### Your custom filters (if any)
none / see above

**Comment by gorhill** [comment]
It's in the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.20):

> Some refactoring was necessary to move forward this part, and as a result the DOM inspector is currently not available on legacy Firefox.

**Comment by gorhill** [comment]
I won't bring the necessary changes to fix this for Seamonkey, it's probably a huge amount of work for which I don't have the motivation to undertake.
