### ISSUE TITLE
Custom scriptlets

### ISSUE THREAD

**Issue by vobruba-martin** [gorhill/uBlock#3307]
Hi, is there any way how to add URL of my own scriptlets or how to define them? Thanks!

**Comment by uBlock-user** [comment]
Open` advanced-settings.html` via Dashboard and add the URL at `userResourcesLocation`

This is how mine looks like - https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.txt

**Comment by vobruba-martin** [comment]
No other way how to use them as a third party filter so I can update them on demand?

**Comment by uBlock-user** [comment]
Not sure what you mean but you can use the scriptlets you created by injecting them via `##script:inject` filters.

**Comment by gorhill** [comment]
> so I can update them on demand

You can force an update of what you add to `userResourcesLocation` by purging the cache for "uBlock filters".
