### ISSUE TITLE
Ublock Crashing in Chrome

### ISSUE THREAD

**Issue by Alphaboy202** [gorhill/uBlock#3308]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Plugin crashes in Chrome immediately after opening the browser. Ublock was working fine for me on December 1st

### One or more specific URLs where the issue occurs
ALL WEBSITES

### Steps for anyone to reproduce the issue

1.Open  chrome
2. click the three dots showing the plug ins and it disappears
3. Have the latest version of Chrome on Android installed as well
4. go to Ublock's Chrome store page to see a message saying "This item has been disabled in Chrome"
5. The only way to currently fix this is to repair the extension

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 : Creator's update
- Browser/version: Chrome (latest
- uBlock Origin version: 1.14.20

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
Not a uBO issue, it's an issue on your side, something is modifying your browser and/or uBO installation. You will need to investigate this yourself.
