### ISSUE TITLE
[question] back up everything

### ISSUE THREAD

**Issue by jerkstore369** [gorhill/uBlock#3309]
when I go to settings > backup to file, that just backs up the setting I guess right? Is there a way to backup EVERYTHING, including my filters, my rules and whitelist. All in one file. Or do I have to export everything separately? Thanks.

**Comment by adisib** [comment]
It backs up everything. You could have found this out very easily by trying it, or even just reading the contents of the file.

**Comment by jerkstore369** [comment]
sorry

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
