### ISSUE TITLE
uflash.tv has anti adblocking

### ISSUE THREAD

**Issue by doonoo** [gorhill/uBlock#3313]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
uflash.tv has anti adblocking (BE WARN ITS A NSFW porn site), i have to disable my adblock to watch a video.

### One or more specific URLs where the issue occurs
uflash.tv
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
not a good idea
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Go to a video on a website and it'll be blank, but if you turn ublock off the video appears.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
Default
- OS/version:
Void Linux 
- Browser/version:
Pale Moon 
- uBlock Origin version: 
1.14.20
##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Default Filter List

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
anti adblock script

```javascript
$(function(){var c;var d=$('.ad300x250');var e=d.height();var f=d.width();var g=$(d).is(':visible');if(g&&d.length===7&&f===300&&e===250){var h,check3,check4;$.when($.getScript("https://ads.exoclick.com/ads.js").done(function(a,b){h=true}),$.getScript("https://ads.exoclick.com/nativeads.js").done(function(a,b){check3=true}),$.Deferred(function(a){$(a.resolve)})).then(function(){if(h&&check3){var a=new SWFObject("http://www.uflash.tv/media/player/player.swf?f=http://www.uflash.tv/media/player/config.v89x.php?vkey="+video_id+"","main","728","458","9","#000000");$('#flash').append('<video width="728" height="458" controls="controls"><source src="'+base_url+'/mobile_src.php?id='+video_id+'" type="video/mp4"></video>');a.addParam('allowfullscreen','true');a.addParam('wmode','transparent');a.write("flash")}})}else{}});
```

**Comment by doonoo** [comment]
thanks, how do i use it tho
