### ISSUE TITLE
Request: add ability to white list or black list items on the website from no-blocked items mode

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [gorhill/uBlock#3314]
For example, on this website:
https://www.androidauthority.com/samsung-galaxy-s9-809963/

The default behavior of the plugin is to block various things, including the comments section.
I would like to either white list the comments section, or to black list each item that I want.

I've tried using the UI of the plugin to do it, but I failed:
For white list, I tried pressing on "requests blocked" but it doesn't have toggles for each item blocked. 
For black list, I tried to disable the blocking on the website, but right clicking on ads and then choosing "block element" doesn't do anything. Same goes to the buttons of the popup window of the plugin button, when I click on it. 

It seems the plugin only works when I choose to enable it for the specific website, but then it blocks at least the default stuff, which is something I want to avoid for some websites.

**Comment by gorhill** [comment]
> it blocks at least the default stuff

Filter list issue then. Just report to filter list maintainers.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by AndroidDeveloperLB** [comment]
It's not about the filter list maintainers, because this is just one example of a website.
I want to be able to do those things on all websites:
To be able to white list or black list items per website, even if the default filters don't work well with them.
There are 2 ways to do it:
1. Given the default behavior of the filter on the specific website, allow to white list specific items, including viewing them (to verify that's what we wish to unblock)
2. Given that we don't want to use the default filter on the specific website, allow me to mark exactly which items in the website to block, one after another.

**Comment by gorhill** [comment]
Sorry, can't help you, because it's completely not clear to me what is your **specific** issue. You provide a link, but I have no clue what exactly is wrong on that page, basically you fail to describe precisely what I should be observing at the page you link to, I can't read minds.

Now without a clear and detailed description of what you think is wrong at the linked page -- including screenshots if necessary, you go onto asking for some sort of solution that nondescript problem, which if I understand correctly is to be able to still filter out stuff when disabling filtering completely uBO for a site. If so, this just makes no sense.

The core problem with this issue is to disrespect all what is asked from you in CONTRIBUTING: report _issues_ properly. Then if I agree there is an issue, I can then decide whether to fix it, and if so, would be the best solution.

**Comment by AndroidDeveloperLB** [comment]
I wrote exactly what's wrong:
It blocks the comments section.
Now, as I wrote, I tried 2 methods to overcome this:
1. White list the comments section, by looking at what was blocked, and disabling whatever caused the comments section to be removed.
2. Start from scratch: disable plugin on this website, and choose one ad after another.

Here's the page with ads removed (see there's no comments section) :

![image](https://user-images.githubusercontent.com/5357526/33553289-c6b6e084-d900-11e7-827e-89cb14238dd9.png)


Here's the page with ads not removed (see there's a comments section) :
![image](https://user-images.githubusercontent.com/5357526/33553270-b5b3054c-d900-11e7-9120-cec29ee0ec32.png)

It's not an issue of the plugin. It's a request to overcome such situations. The default filters cannot be expected to always filter only what's the best to filter. Sometimes we need to filter more. Sometimes we need to filter less.

**Comment by uBlock-user** [comment]
> It blocks the comments section.

Run the logger and find the filter which blocks it, then add a whitelisting filter for it or simple `$badfilter` the blocking filter.

**Comment by AndroidDeveloperLB** [comment]
@uBlock-user This is what the logger shows:
![image](https://user-images.githubusercontent.com/5357526/33554242-97aec15e-d904-11e7-9146-aac4c86a7fde.png)
Can't find the filter that blocks the chat, because there is no visual indication which item there is the chat.
But even if I had a suspect in the list, I don't see a toggle for the items, there is no button or a right click menu to white list it.
There is also no place to put `$badfilter` , and it's not intuitive to know that this is what I have to add. It should be easier to add something to the white list, or to the black list. 
Currently I don't see either of those.
I tried to select a script item there, and choosing to "allow" it. I chose to create the rule, but then I don't see it. After seeing that it didn't do anything on the page (after refresh), I wanted to undo the new rule, but there was no undo option. Instead, I could go to the same rule, and choose "block" instead, and then to create this new rule. So now I think I have 2 rules that negate each other somehow.

**Comment by gorhill** [comment]
That site is a cesspool of 3rd parties. There is no magic solution for this: it is a filter issue.

If you want to un-break sites, just use dynamic filtering, just like I did:

    www.androidauthority.com 206ads.com * allow
    www.androidauthority.com adsrvr.org * allow
    www.androidauthority.com doubleclick.net * allow
    www.androidauthority.com googlesyndication.com * allow
    www.androidauthority.com googletagservices.com * allow
    www.androidauthority.com moatads.com * allow
    www.androidauthority.com spots.im * allow

Then I used the inspector to reveal the chat section and create an exception filter:

    www.androidauthority.com#@#.tpd-box

Figuring what to filter or not requires work, there is no magic solution whereby uBO would do all for you. There are already tools to do what you asked, I just used them to get the above result.

**Comment by AndroidDeveloperLB** [comment]
@gorhill I didn't ask for magic.
I asked for 2 features:
1. white list items from the list, by seeing them directly in the plugin window (not a new webpage), and having a toggle for each. If possible, turning each of them off would reveal the content that was blocked. If not, it will just offer to refresh the webpage.

2. block list of items, one after another, without the help of the default filter. Just let me add the rule for each of them. I click exactly on the stuff I want to block. For each one, it will offer me a textbox of the specific rule, and I could change it so that it would be more general (example : it would offer "http://somewebsite.com/ads/ad1.jpg" and I could changed it to "http://somewebsite.com/ads/ad*.jpg" or even "http://somewebsite.com/ads/*" ).

**Comment by gorhill** [comment]
> When I choose to avoid filtering on the website, it doesn't allow me to add my own filter.

Sorry, can't help you -- these two statements are contradictory, you want to disable filtering but enable filtering at the same time. Best is probably you fork and implement your specific feature as you see fit.

**Comment by AndroidDeveloperLB** [comment]
@gorhill You don't understand. 
I want to disable what it's trying to do with the website using the default filters, and use my own (user's) rules, one after another. 
You can call it "custom filter" , "my filter" or  "user filter".

As I wrote, there is no way a filter can be perfect. You should be able to have a while list of what not to use in it, and to avoid it completely, having your own block list of rules for the specific page.

**Comment by gorhill** [comment]
> I want to disable what it's trying to do with the website using the default filters, and use my own (user's) rules, one after another.

Dynamic filtering pane in the popup panel is the closest you will get to this. In any case, for what you ask specifically, I decline -- it's just not something I would want to work on, this would require a from the ground-up rewrite of the extension, in short that would require a new extension, so it's best you develop your own idea on your side exactly as you want it to be.

**Comment by AndroidDeveloperLB** [comment]
I don't get why.
Why would it require such a thing? 
There are already the "element picker mode" and "element zapper mode". What is their use, if I can't use them on my own, and always have to use the default filters first?
And, for white list, you wrote it already has it using `$badfilter` . So just add a button for each item, to turn it on or off.
And I don't see "dynamic filtering".
This is what I see:
![image](https://user-images.githubusercontent.com/5357526/33559679-40da99ea-d916-11e7-8401-562d9de1e16c.png)
None of the things I hover (using the mouse) shows "dynamic filtering" .

**Comment by gorhill** [comment]
Please respect that I declined -- to keep arguing that I should work on your idea after I already declined is unpleasant.

Since you already evaluated that it is trivial to implement, as said just fork, you will get what you want, the way you want it, and without having to wait on someone else to do it for you.

**Comment by mapx-** [comment]
@AndroidDeveloperLB  You should read the docs

- for example go into options (dashboard) and select "i am an advanced user" to see other things
- see https://github.com/gorhill/uBlock/wiki/Advanced-user-features

**Comment by mapx-** [comment]
You should also read about the logger and how to create your filters 
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by uBlock-user** [comment]
@AndroidDeveloperLB Read the wiki please, and not everything is going to be present in the UI. Creating filters requires patience and interest. Asking for every little obstacle you face while trying will not help.

**Comment by AndroidDeveloperLB** [comment]
@gorhill I'm not an expert in HTML/JavaScript. 
I write this as a user of the plugin.

@mapx- I've enabled it, read about dynamic filtering [here](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide), and tried to mark as yellow a lot of things on the chart, on the most right column, where it's supposed to work only for the current website.
Didn't work (after a refresh), so I've marked more and more. Still didn't. Chose all of the items (clicked the top item that says "all", and indeed all were marked green), and still it didn't restore the comments section. The counter that appears on the plugin button (that I assume shows how many stuff were blocked) doesn't even show a number anymore.

![image](https://user-images.githubusercontent.com/5357526/33566913-2b31f84a-d92a-11e7-83b1-f6408fb92272.png)


Only when I chose to disable the plugin for the current page, it showed the comments section.

I don't see a way in the plugin to add a customized dynamic filter using textbox.
Only thing I see is "my filters" , but adding what `gorhill` wrote, into there, didn't do anything.

**Comment by mapx-** [comment]
remove all those dynamic filters and test these "normal" filters
```
androidauthority.com#@#.tpd-box
@@||3lift.com^$domain=androidauthority.com
@@||206ads.com^$script,domain=androidauthority.com
```
(be sure you are not using any other blocking extension)

**Comment by AndroidDeveloperLB** [comment]
@mapx- What do you mean by "remove all those dynamic filters"? 
Marking all green on this website (as I've shown on the screenshot) - still blocked the comments section.

Where exactly do you put the "dynamic filters" ? The UI of the "dynamic filters" doesn't have a textbox. It's a chart that all I can do is mark with colors.

I tried to add what you wrote into the "my filters" part, with and without all stuff marked green. 
Still didn't do anything.

**Comment by mapx-** [comment]
"remove all those dynamic filters" => click on the top left icon (click to revert your changes)

However, the dynamic filters are named "rules" and you can edit them as text in "my rules" section in your dashboard. => it's why I asked you to read more and more docs

You didn't tell us nothing about browser (version), uBo version, filter lists (standard setup or modified one), if you tested keeping only uBo enabled and so on.

**Comment by thewriteway** [comment]
@AndroidDeveloperLB 

if you want the chat to show up just add these to your whitelist : 
spot.im
spots.im
www.spot.im

Happy now?

**Comment by AndroidDeveloperLB** [comment]
@mapx- 
What "top left icon" ? There is no icon on the top left. Look a the screenshot.
I've read the docs about "dynamic filters". I don't see there mentioning about it.
I didn't tell about Web browser, because this was a request. Not a bug report.
Cent Browser
Version 3.0.4.29 (Official Build) (32-bit) (Chromium 62.0.3202.94)
I've also tried official Chromium. Has same behavior.

@thewriteway Now it works. Thank you.

Still, it should be easier to white list and black list things. People can't always be happy with the default filters.

**Comment by mapx-** [comment]
the rubber icon is in your image:
![rubber](https://user-images.githubusercontent.com/10303732/33572693-f50856ba-d933-11e7-9f74-9ae4ab0c6689.PNG)

my filters are for the comments section you specified is missing in your first post

**Comment by AndroidDeveloperLB** [comment]
@mapx- This cleans all markings made by me. 
I don't understand the second sentence.
I can't add new filters using text. Only thing I see there are what I can toggle. Even if I toggle all of them to be allowed (mark as green), it will still filter out the comments sections for some reason.
