### ISSUE TITLE
[suggestion] add clear statistics option

### ISSUE THREAD

**Issue by logan3444** [gorhill/uBlock#3315]
Good afternoon, I would like to ask and offer. Could you add an option that would reset the statistics that is responsible for the amount of blocked ads since the installation of the extension. For example, how it is done in the aguard. Thank you.

**Comment by gwarser** [comment]
Workaround -> export your UBO settings -> remove UBO -> install UBO -> import your settings.

**Comment by logan3444** [comment]
This is not what I said.
