### ISSUE TITLE
[Suggestion] Add keyboard shortcuts for common operations (i.e. enable/disable for this site) / Add option to "always refresh" / Make the menu less sticky

### ISSUE THREAD

**Issue by 2151023** [gorhill/uBlock#3317]
Hello,
I have three suggestions:
1 - add a keyboard shortcut that does the same as clicking the power icon
2 - add an "always refresh" option (so that you don't have to hit refresh after hitting the power icon)
3 - make the uBlock menu close itself when you use the built-in refresh / press f5 / close the tab

Ideally, I'd prefer two keyboard shortcuts to:
--- hit the power button
--- hit the power button + refresh

I don't know about most users, but I perform these 4 clicks (open the menu, click the power button, hit refresh, click away to hide menu) frequently enough that a keyboard shortcut would be greatly appreciated.

Thanks

**Comment by gorhill** [comment]
I am going to decline this.

1. and 2.: Whitelisting a site should not be such a common occurrence so as to deserve an keyboard shortcut.

3.: that would be bad, I my self already use the refresh button a lot when trying to unbreak site, and I want my popup to stay open until I have good confidence a site might be unbroken.
