### ISSUE TITLE
[suggestion] add Cryptocurrency (Bitcoin) Mining Protection List 

### ISSUE THREAD

**Issue by xqk94524** [gorhill/uBlock#3319]
I saw this some time ago in the adblock, looks like a interesting addition

https://cdn.adblockcdn.com/filters/nominers.txt

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+mining+is%3Aclosed
