### ISSUE TITLE
Accessing popup UI of a specific page

### ISSUE THREAD

**Issue by HyperCriSiS** [gorhill/uBlock#332]
Hi,

I could not find much information about this.
What does it mean if I flag an entry here with grren/grey/red and so on?
A popup with a small description when hovering over the functions would be nice.

Thanks and greetings
Hyper

**Comment by gorhill** [comment]
I don't understand the question.

"grren/grey/red" seems to refer to dynamic filtering, which is an advanced feature, for which there is a required reading: <https://github.com/gorhill/uBlock/wiki/Advanced-user-features>.

**Comment by CrisBRM** [comment]
@gorhill does yellow mean some network requests are blocked for a given hostname, but not all?

**Comment by gorhill** [comment]
Yellow? There is a yellow but only in color-blind mode, and it corresponds to green in normal mode.

**Comment by CrisBRM** [comment]
To the left of the hostnames!

**Comment by gorhill** [comment]
Ah yes, means some blocked some went through. Kind of redundant with the `+` and `-`.

**Comment by hotdogman** [comment]
>Kind of redundant with the + and -.
I don't think so. Depending on the font used, + and - can be hard to see.
![screenshot56](https://cloud.githubusercontent.com/assets/4343306/8097826/2317f7e8-0fad-11e5-8d8a-bfbf1d1c5ae4.png)

**Comment by CrisBRM** [comment]
@hotdogman You make a good argument for the minus symbol to be able to see at times.

**Comment by gorhill** [comment]
> Depending on the font used, + and - can be hard to see

Yes, I see this on Nightly. Now that the font issue is resolved, I might decide to package a font that is guarantee to always work. Currently the browser decide and even though I use the same size and family, it's rendered differently depending on the browser.

**Comment by HyperCriSiS** [comment]
I just don't understand what I am able to do there.What the different colours and + and - count mean and the difference at general  between the two columns behind the hostname.
Who can bring a bit more light into this thing? :)

Thanks in advance.

**Comment by gorhill** [comment]
> What the different colours and + and - count mean

It's all in the wiki, which is what "Required reading" leads to: <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide>.

**Comment by HyperCriSiS** [comment]
Uff sorry oversaw this one :/
