### ISSUE TITLE
Ocsigen.org freezes when clicking links

### ISSUE THREAD

**Issue by leviroth** [gorhill/uBlock#3321]
### Describe the issue

Chrome tabs freeze when navigating links on Ocsigen.org. The page becomes unresponsive, and the tab takes longer than normal to close.

### One or more specific URLs where the issue occurs

http://ocsigen.org/

### Steps for anyone to reproduce the issue

1. Visit http://ocsigen.org/.
2. Click the big button that says "Tutorial: Your first app in 5 minutes!"
3. Observed behavior: address bar changes to the target link; page does not update; the mouse pointer remains in the "pointer finger" state everywhere on the page. Fan starts running very high, but I couldn't get the Chrome dev tools profiler to work, presumably because the tab itself wasn't responsive.
4. Middle-click the browser tab to close it; there will be a noticeable lag before the page is able to close.

### Your settings

- OS/version: Windows 10 with the Fall Creators Update (version 1709)
- Browser/version: Chrome 62
- uBlock Origin version: 1.14.20

This is with default settings/filter lists and no other extensions enabled.

**Comment by leviroth** [comment]
In lieu of a proper profile, here is what the Chrome process manager looks like after allowing the tab to stall for 5-10 seconds. The CPU usage was at a steady 25%, while the memory kept growing.

![resources](https://user-images.githubusercontent.com/17488252/33621060-9fcfe076-d9b7-11e7-92b7-06fa55db1ea5.png)

**Comment by uBlock-user** [comment]
Can reproduce on Chromium 64 too, it freezes.

**Comment by gorhill** [comment]
The site's code is constantly removing uBO's style tag as fast as it is re-added.

**Comment by mapx-** [comment]
I disabled all filters / lists

filters triggering that behaviour:
```
##A[href*="/click.php"]
##[id=likepagefb]
##[Lol^="abcd"]
```
filters which don't trigger:
```
###likepagefb
site.com##A[href^="abcd"]
```
so, generic filters but not all of them

**Comment by gorhill** [comment]
The first filters are categorized as highly generics and always injected. The other ones are lowly generic but matches nothing on the page.
