### ISSUE TITLE
Page can't load when uBlock is on

### ISSUE THREAD

**Issue by KrzysztofUrbanczyk** [gorhill/uBlock#3322]
### Describe the issue

Page: 
https://system.t-mobilebankowe.pl/web/login

can not load when uBlock is on.

- OS/version: Win 10
- Browser/version:   Wersja 62.0.3202.94
- uBlock Origin version: 1.14.20

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
