### ISSUE TITLE
HTTPS site reported as insecure even if all HTTP content is blocked

### ISSUE THREAD

**Issue by ololoe** [gorhill/uBlock#3324]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
HTTPS site is reported as insecure even if all HTTP content is blocked. Adblock Plus behaved differentely - if all HTTP links were blocked a site was reported as secure.

### One or more specific URLs where the issue occurs
https://pornolab.net/forum/index.php

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows
- Browser/version: Firefox 
- uBlock Origin version:

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ololoe** [comment]
You and your piece of "software" are invalid
