### ISSUE TITLE
Caret (text cursor) stuck in place

### ISSUE THREAD

**Issue by Luke-Baker** [gorhill/uBlock#3325]
### Describe the issue
The moment you click in the middle of the text on the My Filters tab, the caret (text cursor) stops blinking. It doesn't move when the arrow keys are pressed. This doesn't happen when clicking outside of text, i.e. the empty lines below the custom filters. It seems the more filters, the more sluggish the caret response becomes. In my testing, it was fine with 90 filters but became unusable past 100.

### Screenshot in which the issue can be seen
[MP4](https://i.imgur.com/8f0GvxO.mp4). The recording hid the mouse cursor at the start, but you get the gist of what's going on.

### Steps for anyone to reproduce the issue
1. Start Nightly in a brand new profile.
2. Install the latest uBlock Origin.
3. On the My Filters tab, enter a large number of filters (a little over 100 does it in my case), then click the Apply button when done. The actual filters themselves are irrelevant; I just used 101 instances of `! just a comment`
4. Click in the middle of one of your filters.
5. Press any of the arrow keys.

### Your settings
As I said, I tested in a brand new profile. No settings were touched and the custom filters themselves were just comments.

- OS/version: Windows 10 x64
- Browser/version: Nightly 59.0a1 build 20171206100053
- uBlock Origin version: 1.14.20

##### Your filter lists
Whatever the default set is.

##### Your custom filters (if any)
Over 100 instances of `! just a comment`

**Comment by gorhill** [comment]
Can't reproduce on stable Firefox 57.

Can reproduce on Nightly.

Profiling shows nothing when filtering output using `moz-` and javascript.

Please file an issue on bugzilla, uBO is doing nothing when the text area is clicked or when the cursor is moved, there is no event listener for these events.

**Comment by gorhill** [comment]
Seems to happens when `extensions.webextensions.remote` is set to `true`. Please report to bugzilla.
