### ISSUE TITLE
domain exception 

### ISSUE THREAD

**Issue by olgon** [gorhill/uBlock#3328]
Add this filter and go https://www.kaspersky.com/blog/
`/jquery.smartbanner.$domain=~blog.kaspersky.com|~kaspersky.com`

Exception `|~kaspersky.com` does not work.  Requests with `/jquery.smartbanner.` are bloked on kaspersky.com
![2017-12-08 06 12 24-fullpage](https://user-images.githubusercontent.com/20244103/33749780-c164e47c-dbe0-11e7-9698-13e1dadc9e89.png)

But if you change the order, exception works  ok.  With this filter
`/jquery.smartbanner.$domain=~kaspersky.com|~blog.kaspersky.com`
Requests with `/jquery.smartbanner.` are not filtered

- OS/version:  Win8.1
- Browser/version: Firefox 52.5
- uBlock Origin version: 1.14.21rc2

**Comment by gorhill** [comment]
Good catch, thanks for reporting.

Regression from 5928996f2af6.

**Comment by gorhill** [comment]
To assess severity, I looked a bit in EasyList to find out if any existing filters would suffer the issue here, and I suspect there might be no case of filters being affected. Normally a filter such as:

    /jquery.smartbanner.$domain=~blog.kaspersky.com|~kaspersky.com

Would be really written as

    /jquery.smartbanner.$domain=~kaspersky.com

Because there is no point specifying `~blog.kaspersky.com` given that it's already being excluded with `~kaspersky.com`.

**Comment by olgon** [comment]
`Because there is no point specifying...`

I see, but filter maintainers modify old filters, add exceptions so, probably, it turned out with this filter

`/jquery.smartbanner.$domain=~1-ofd.ru|~blog.kaspersky.kz|~blog.kaspersky.ru|~kaspersky.co.in|~kaspersky.co.uk|~kaspersky.co.za|~kaspersky.com|~kaspersky.com.au|~kaspersky.com.br|~kaspersky.com.cn|~kaspersky.com.tr|~kaspersky.de|~kaspersky.es|~kaspersky.fr|~kaspersky.it|~kaspersky.nl|~kaspersky.ru`

From [RU AdList: BitBlock](https://easylist-downloads.adblockplus.org/bitblock.txt)

Requests with `/jquery.smartbanner.` are blocked on `kaspersky.ru` because
`~blog.kaspersky.ru` located before `~kaspersky.ru`
