### ISSUE TITLE
Crashes Chrome/Chromium when Decentraleyes Addon is activated as well

### ISSUE THREAD

**Issue by escapedsalmon** [gorhill/uBlock#3329]
### Describe the issue
Chromium tabs keep crashing when having uBlock Origin and Decentraleyes AddOn activated at the same time. (Affects Windows and Linux/Fedora+Chromium so far.)

### One or more specific URLs where the issue occurs
https://navigator.gmx.net/ 
(when logged in obviously)

### Steps for anyone to reproduce the issue
1. Download uBlock Origin through Chrome Webstore.
2. Download Decentraleyes through Chrome Webstore.
3. Enable both.
1. Log into an account at GMX.net (create one if you don't have one).
1. Keep opening mails for about 30secs and your Chrome Tab will probably crash.

### Your settings
- OS/version: WIndows 10 + Fedora 27 (both fully updated)
- Browser/version: Version 62.0.3202.94 (Official Build) (64-bit) 
- uBlock Origin version: uBlock Origin v1.14.20

##### Your filter lists
Default filter lists + DEU + Peter Lowe’s Ad and tracking server list​ + Fanboy’s Enhanced Tracking List + Adblock Warning Removal List

##### Your custom filters (if any)
not set.

Will submit this issue to decentraleyes addon as well.

**Comment by gorhill** [comment]
Browser crash must be reported to browser devs -- uBO is javascript, it's not supposed to crash the browser.

**Comment by liberodark** [comment]
for me not crash
