### ISSUE TITLE
Firefox installation not possible

### ISSUE THREAD

**Issue by marisana** [gorhill/uBlock#3330]
uBlock Origin can not be installed.
FF 57.0.1 (64-bit)
Lubuntu 16.04

In the AddOn section of Firefox:
"An error occurred while downloading ublock origin"

When downloading from https://github.com/gorhill/uBlock/releases and install via AddOn area DropDown menu:
"The AddOn downloaded from this page could not be installed because it seems to be damaged."

**Comment by gorhill** [comment]
Install from AMO, releases here are not signed, your browser won't accept to install them.

**Comment by marisana** [comment]
The problem was that there was no space left on my system HDD. Now installing over the Firefox settings AddOn has worked. Sorry.
