### ISSUE TITLE
new polish filters list

### ISSUE THREAD

**Issue by KonoromiHimaries** [gorhill/uBlock#3332]
add a "Polskie filtry annoyance"
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/PPB.txt

to replace with
![33788352-f593f8d2-dc71-11e7-9364-86d4eeb2c581](https://user-images.githubusercontent.com/5884000/33791342-a8e61100-dc8a-11e7-8c84-3898d643deed.png)

**Comment by gorhill** [comment]
Why the replacement?

**Comment by mat41997** [comment]
@gorhill 

"polskie filtry do uBlocka uzupelnienie" not be longer nedded, because
https://github.com/gorhill/uBlock/issues/3331

"Polskie filtry annoyance" ist be a most usefull
https://github.com/azet12/PopupBlocker/blob/master/PPB.txt

**Comment by mat41997** [comment]
@gorhill see it
https://github.com/NanoAdblocker/NanoCore/pull/19#issuecomment-350601332

**Comment by nnzmj** [comment]
great~

**Comment by KonoromiHimaries** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/8413

**Comment by gorhill** [comment]
I rather not bloat the stock filter lists with regional specialization such as "annoyances" etc. I added an information link recently to <https://github.com/MajkiIT/polish-ads-filtear#polish-filters-for-adblock-ublock-origin--adguard>, so that users can find more flavors of POL lists.
