### ISSUE TITLE
Block BitCoin miners

### ISSUE THREAD

**Issue by ecoitsolutions** [gorhill/uBlock#3334]
### Describe the issue
Many more websites are silently installing bitcoin miners into the browser's cache localtion. Can you prevent that? Similar filter has AdGuard extension

### One or more specific URLs where the issue occurs
http://www.filmeonline2013.biz/
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
<img width="1440" alt="screen shot 2017-12-10 at 13 26 15" src="https://user-images.githubusercontent.com/3727896/33804441-c2729a84-ddad-11e7-9c5d-93bdc4d48d0d.png">

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Go on some websites like this one: http://www.filmeonline2013.biz and if you have AdGuard extension enabled when you click on a movie it will warn you that the website is trying to install a bitcoin miner. You click NO and it will still be installed in cache. Luckly the antivirus does his job very well and removes it.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  Mac OsX High Sierra 10.13.2
- Browser/version:  Safari Latest, Chrome Latest
- uBlock Origin version: 1.5.2

##### Your filter lists

Default lists

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
I don't see any coin mining running with uBO.
