### ISSUE TITLE
popup issue

### ISSUE THREAD

**Issue by SANJAYSKIM** [gorhill/uBlock#3338]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
popup issue

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
https://7starhd.info/
https://bdupload.info/v7l0b5skwcka
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
just go to website and click
1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: win10
- Browser/version: chrome v64
- uBlock Origin version: 1.14.20

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
easy list+ublock protector

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
