### ISSUE TITLE
Request - cookie blocking

### ISSUE THREAD

**Issue by Tony874** [gorhill/uBlock#3339]
Can you add some cookie blocking lists for example the privacy matchup block list.
https://www.eff.org/files/cookieblocklist.txt

**Comment by jspenguin2017** [comment]
Am I missing something? How is that a "block list" when it's all exception rules?

**Comment by Tony874** [comment]
Good question, it was just an example as I know they do block cookies, their filters must be different.
There are other cookie block lists and methods available as well.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
