### ISSUE TITLE
TypeError: button is null - in Firefox 38, Debian.

### ISSUE THREAD

**Issue by pachanka** [gorhill/uBlock#334]
Hello,

This is not a critical error, but I thought I'd let you know.

 I'm using Firefox 38.0.5 on Debian, with uBlock Origin v0.9.8.2. and uppon startup I get the following error messages:

<pre><code>console.error: 
  [CustomizableUI]
  TypeError: button is null -- chrome://ublock0/content/js/vapi-background.js:1645
console.error: 
  [CustomizableUI]
  TypeError: button is null -- chrome://ublock0/content/js/vapi-background.js:1645
console.error: 
  [CustomizableUI]
  TypeError: button is null -- chrome://ublock0/content/js/vapi-background.js:1645</code></pre>

This plugin is by far the best thing thats happened to my add free browsing, and I'm a huge fan. Thanks for all the hard work.

**Comment by gorhill** [comment]
The fix is trivial but I would like to know how this case can happen. Do you have any customizations applied to the browser itself? Any add-ons which modifies the browser UI?

**Comment by pachanka** [comment]
Not that I'm aware of.
I tried deactivating all plugins, themes, and services and still got a warning.

![screenshot](https://cloud.githubusercontent.com/assets/948134/8117437/f6fb8fac-107f-11e5-86b4-c6feea06e9dd.png)

I guess the next step would be to try a fresh install.

**Comment by gorhill** [comment]
Ok I see the uBlock button is overflowing in your screen, so that might explain why this was happening. In any case there was a bug in the code, and probably the overflowing caused the bug to manifest itself.
