### ISSUE TITLE
contentscript.js shows error "dom surveyor shutting down: too many misses"

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#3341]
I had a problem with the contentscript.js and error msg: "dom surveyor shutting down: too many misses".

Cannot say an URL (till now), I saw an orange error sign in Cr but (highly) probably not immediately. I clicked that error sign and saw the following screenshot from extension window ...

![ublock-error](https://user-images.githubusercontent.com/11355601/33915257-aba646ce-dfa2-11e7-8131-67479312656d.JPG)

If I will have a reproducing method, I will post it here later ...

- OS/version: Win 10 Pro x64 Ver. 1709 Build 16299.19
- Browser/version: Chrome x64, Dev Version 64.0.3282.24
- uBlock Origin version: 1.14.21rc4

All "uBlock filters", Adguard Base Filters, EasyPrivacy, DEU: EasyList Germany

I wrote all possible data (I hope). However, I thought it's worth to report it in this manner ...

**Comment by gorhill** [comment]
It's just a warning, working as expected.
