### ISSUE TITLE
unsubscribe to whitelist parts

### ISSUE THREAD

**Issue by Ploklopse** [gorhill/uBlock#3345]
> https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

This is neither a feature request nor a bug, but an interrogatory. 

### Describe the issue

Given a set of enabled filter subscriptions how can I disable some whitelisting while retaining the blocking?    While I can create 'always' overrides for offensive content like every google widget or property this seems like iterative tedium

### Screenshot in which the issue can be seen

![screen shot 2017-12-14 at 3 49 11 pm](https://user-images.githubusercontent.com/34557626/34019992-649a2c74-e0e6-11e7-95de-6e98dc435565.png)

### Your settings

- OS/version: OSX 10.12.6
- Browser/version: Firefox 57.0
- uBlock Origin version: 1.14.22

##### Your filter lists

![screen shot 2017-12-14 at 3 50 59 pm](https://user-images.githubusercontent.com/34557626/34020029-9a29804c-e0e6-11e7-990d-b8c1fb99bc55.png)

**Comment by aggat** [comment]
[Overriding exception filters](https://github.com/gorhill/uBlock/wiki/Privacy-stuff#overriding-exception-filters)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
