### ISSUE TITLE
[Firefox] Cosmetic filters are not being applied and some filter lists can't be updated if Firefox profile folder is inside the TrueCrypt container

### ISSUE THREAD

**Issue by Faberman** [gorhill/uBlock#3346]
This is a weird issue, but I was able to reproduce it a few times. Also when I move profile folder to another Firefox instance (portable or regular), everything works as expected.

Steps to reproduce the issue:

1. Install Firefox. Default settings.
2. Create TrueCrypt container (NTFS in my case).
3. Mount TrueCrypt container file  (for example, as `H:` drive).
4. Run Firefox with `-profile` key and the path (inside TrueCrypt container) where the new Firefox profile will be created. For example, `firefox.exe -profile H:\ProfileFolder`.
5. Install uBlock Origin. Default settings.
6. Open uBlock Dashboard -> 3rd-party filters. Click 'Update now'. At this point, most of the selected lists will be successfully downloaded, although EasyList and EasyPrivacy will probably fail to do so.
7. Click 'Purge all cache' button.
8. Click 'Update now' button again. This time filter lists won't be updated. 'Updating' icon will spin continuously and cosmetic filters will not be applied.

Settings:
- Windows 7 SP1 x64
- Firefox 58.0b6 x64
- uBlock Origin 1.14.22
- TrueCrypt 7.1a

Filter lists:
Default filter lists minus Malware Domain List, Peter Lowe’s Ad and tracking server list.

**Comment by lewisje** [comment]
Maybe Firefox doesn't have the necessary permissions to modify files inside the TrueCrypt container.

**Comment by Faberman** [comment]
@lewisje, TrueCrypt container works (well, should work) as a regular logical drive. Also I don't have any issues with the other extensions, and I think I haven't had this issue with the legacy uBlock Origin and pre-Quantum Firefox.

**Comment by gorhill** [comment]
uBlock is merely using browser APIs, please investigate your very specific issue -- it is beyond the scope of this project.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Faberman** [comment]
Well, I still don't know how to fix this. Two months of testing and nothing.
- Clean Windows 7, clean Firefox, default profile in %APPDATA%, latest stable uBlock build -> Update now — everything works.
- Clean Windows 7, clean Firefox, profile inside TrueCrypt/VeraCrypt container, latest stable uBlock build -> Update now — nothing happens. No log entries in uBlock Logger, no entries in Fiddler. Just a continuously spinning 'Updating' icon. It seems uBlock doesn't send any requests.

I don't have any issues with other extensions.

**Comment by Faberman** [comment]
@gorhill, I got it, but the problem exists and it's not my particular problem. For example, legacy versions of uBlock (e.g. 1.7.6) work just fine with pre-Quantum Firefox (e.g. 48). So I doubt TrueCrypt/VeraCrypt is the problem here.

![ublock_1.7.6](https://i.imgur.com/AKshiQg.png)
