### ISSUE TITLE
1337x.to broken 

### ISSUE THREAD

**Issue by u7m** [gorhill/uBlock#3347]
### Describe the issue
Ublock breaks 1337x.to. once any page with a list is opened first it becomes sluggish and eventually hangs up the page.

### One or more specific URLs where the issue occurs

http://1337x.to/top-100-movies

### Screenshot in which the issue can be seen

![untitled](https://user-images.githubusercontent.com/33958387/34068819-fdfdfdfe-e263-11e7-9e7a-c38c356f3dcb.png)

### Steps for anyone to reproduce the issue
 open the page and try to hover your mouse pointer over the list without scrolling the page, in a couple of seconds page will become unresponsive 

### Your settings

Defualt settings. Fresh installed chrome and ublock

- OS/version: windows 10
- Browser/version:  google chrome 63
- uBlock Origin version: 1.14.22

##### Your filter lists

Default filter lists

**Comment by mapx-** [comment]
filter issue.

**Comment by u7m** [comment]
yeah that fixed the problem.
