### ISSUE TITLE
Issues on Firefox startup / Browser issue only

### ISSUE THREAD

**Issue by mazesy** [gorhill/uBlock#3349]
uBO 1.14.22 / Firefox EME Free 57.0.2 (64-bit) / Windows 7 (64-bit)
---
I'm encountering an issue now with uBO webextension on Firefox 57 I had never met with uBO legacy on previous Firefox versions.

Two points, maybe related:

1- When starting Firefox with the its default about:home page, uBO is not functioning (logo is grayed out), as well as other webextensions apparently, but appears OK once I've reloaded the page. If I choose another homepage than Firefox's (i.e. Quck Dial which is used as New Tab alternative) then uBO is operational at start.
![shot-1](https://user-images.githubusercontent.com/31442711/34070546-895cbf8a-e268-11e7-8faf-d845c714f9d6.jpg)

2- This is more problematic: Firefox being my default browser, when I open it with a link to a whatever site uBO shows as operational (logo is blue) but in fact doesn't filter:
![shot-2](https://user-images.githubusercontent.com/31442711/34070587-d3c823fc-e268-11e7-8a4f-861f34618997.jpg)
I thought uBO didn't have the time to be initialized correctly, so I changed advanced-settings / suspendTabsUntilReady from false to true, closed the browser, opened it again with the same url, and problem persisted. I checked if suspendTabsUntilReady was true as I had set it, but it showed false, yet 
browser-extension-data / uBlock0@raymondhill.net / storage.js shows \nsuspendTabsUntilReady true\

From there o, if I reload the above page, uBO filters then correctly:
![shot-3](https://user-images.githubusercontent.com/31442711/34070640-f14fa26e-e269-11e7-9e48-d34896e332f2.jpg)

Unfortunately I don't follow all threads here and my issue may be either a non-issue or an issue related to my own configuration, i.e.. conflict with another add-on. So before investigating any further I'd appreciate to have a first advice on this odd issue. Thanks.

**Comment by mapx-** [comment]
it seems to be duplicate of https://github.com/gorhill/uBlock/issues/1327

**Comment by mazesy** [comment]
@mapx- thanks for the info. Problem is the issue had been fixed and must have been considering I never encountered it with uBO legacy with previous versions of Firefox.

As the screenshots show it, other webextensions don't run before the page reload as well, so I would suspect this is, once again, a Firefox issue, in which case, if confirmed, brings my post to obsolete.

**Comment by mapx-** [comment]
it was labeled as `browser bug`  in the related issue

The mozilla bug is still untriaged 
https://bugzilla.mozilla.org/show_bug.cgi?id=1378459

**Comment by mazesy** [comment]
OK, @mapx- I got it, thanks. This is the problem of not (being able/having the time) to follow all related threads, even if I try to stay "updated" on the main features/issues. I'll close this post of mine after having renamed it. I had to be explicit should it have been only to discover it was a non uBO issue but instead a full Firefox one. Thanks.

**Comment by gorhill** [comment]
> Problem is the issue had been fixed

I also commented:

> If the fix does not help, then it will mean there is nothing uBO can do.

**Comment by mazesy** [comment]
Right, gorhill. I didn't know/acknowledge the context before posting this thread. Sorry for the disturbance and thanks.

**Comment by superlex** [comment]
Hi, 2) seems to be the same bug:
https://github.com/el1t/uBlock-Safari/issues/58
I can't reproduce it on Firefox, but I can on Safari.
@mazesy , try reducing your filter list, maybe it could help you.

**Comment by gorhill** [comment]
@superlex 

The filter lists are compiled, and even more, uBO creates a snapshot of its internals for fast loading. So I doubt reducing filter lists will make a difference.

**Comment by mazesy** [comment]
Anyway I realize a bit lately that other extensions are concerned as well. This is definitely a Firefox 57+ issue. Concerning the idea of reducing, be it uBO's filter list (even if as gorhill mentions it those lists are pre-parsed and therefor unlikely to have an incidence), be it whatever payload, especially those of extensions, in order to settle a gentleman's agreement with a buggy browser is not my cup of tea.
