### ISSUE TITLE
uBlock stopped working, perhaps due to corrupted database?

### ISSUE THREAD

**Issue by Osmose** [gorhill/uBlock#3350]
### Describe the issue

My partner's copy of uBlock origin stopped blocking ads completely a few days ago. We also observed the following:

- All the checkboxes in the preferences page were unchecked. 
- The "reset all to default" button in the preferences did nothing when clicked.
- The 3rd-party filter list had no entries.
- The uBlock icon was not in the toolbar or customize mode.
- The browser console had multiple lines saying "WebExtension for uBlock0@raymondhill.net could not be found."

We were able to fix the issue by renaming `extension-data/ublock0.sqlite` so that Firefox thought it didn't exist. Upon reboot, uBlock started working like a new install again. I'm able to open the database in a viewer, but I dunno how to interpret what's inside.

@gorhill The broken database has a bit of private info in it due to custom filters, but I'd be happy to send it directly to you if you have a preferred email. 

### One or more specific URLs where the issue occurs

- https://www.youtube.com/
- https://www.reddit.com/
- Pretty much all of the URLs

### Steps for anyone to reproduce the issue

I cannot reproduce the issue, sadly. :(

### Your settings

- OS/version: Mac OSX 10.11
- Browser/version: Firefox 57.0.1
- uBlock Origin version: 1.14.22 WebExtension

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
If your sqlite file was corrupted, there is nothing uBO can do, it is merelt using the browser API to deal with the database. Such corruption can occur if you force quit your browser or have a browser or system crash. Your best bet is to back up your settings regularly and quit the browser normally.

**Comment by gorhill** [comment]
Examples of corrupted sqlite databases:

- https://github.com/gorhill/uBlock/issues/2653
- https://github.com/gorhill/uBlock/issues/1137
- https://github.com/gorhill/uBlock/issues/1090
- https://github.com/gorhill/uBlock/issues/847
