### ISSUE TITLE
Expose API for other webextensions?

### ISSUE THREAD

**Issue by cmcaine** [gorhill/uBlock#3352]
### Describe the issue

Would you be happy to expose a small API to other webextensions? I'd like to be able to do something like `runtime.sendMessage(ublockID, {'addCosmeticFilter', '#cookiePopup'})`.

### More context

Tridactyl, a vimperator-like UI-replacement add-on for Firefox recently added a quick way for users to select and remove elements from a page.

https://github.com/cmcaine/tridactyl/pull/238

This UI is a nice way for our users to quickly remove a troublesome element, but we don't have any persistence for these removals or UI for adding and removing them.

We could write all that, but uBlock already does all that very well and will already be used by many of our users.

**Comment by cmcaine** [comment]
Hi, would you in principle accept a PR for this idea?

**Comment by gorhill** [comment]
Frankly I am not comfortable opening uBO's internals to other extensions, it seems to me this is a recipes for a variety of bad surprises in the future. Add to this that such API becomes a "contract" with the outside world that may also become a burden eventually development-wise.
