### ISSUE TITLE
Random DIV-names cannot be blocked

### ISSUE THREAD

**Issue by UnityUser** [gorhill/uBlock#3356]
### Describe the issue
Random DIV-names cannot be blocked (like 
"div.content__cjS1PK4UDqNi3"
or
"div#ghg6j5962g6.cjS1PK4kRr921N3s.dvqopwa.cwcydwoh"

Filter cannot hide this type of Ad, because class name is always random.

### One or more specific URLs where the issue occurs
https://tv.yandex.ru/213
https://tv.yandex.ru/213/channels/18
https://tv.yandex.ru/213/channels/353
(Press Ctrl+F5 to force reload the page, after that ADs will appear)
[URL(s) for issue on a specific site are **mandatory**]
https://tv.yandex.ru/213/channels/18

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
https://screenshots.firefox.com/irOnf7QXg32tJ174/tv.yandex.ru
### Steps for anyone to reproduce the issue
Open the page:
https://tv.yandex.ru/213/channels/18
Press Ctrl+F5 to force reload the page, after that ADs will appear

### Your settings
Default

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Win10 x64
- Browser/version: Firefox x64 (57.0.2)
- uBlock Origin version: 1.14.22

##### Your filter lists
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
EasyList
EasyPrivacy
Malware Domain List​​​​​
Malware domains
Peter Lowe’s Ad and tracking server list

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
