### ISSUE TITLE
##script:inject(...) takes too long to inject the script

### ISSUE THREAD

**Issue by bakugo** [gorhill/uBlock#3357]
The `##script:inject(...)` directive seems to take 10-50ms to actually inject the specified script after the document starts rendering. This becomes a problem when using scripts like `abort-current-inline-script.js` because inline scripts placed early enough in the document can bypass it completely by executing early on.  It can also lead to cases where a "blocked" script will execute on some page loads but not others.

For example, this rule:
```
##script:inject(abort-current-inline-script.js, String.fromCharCode)
```

Should kill this script, but if it loads too fast, it won't happen:

```
<script>
	window.test = String.fromCharCode;
	console.log("this is not blocked :(");
</script>
```

Is there any way to remove this delay or is this a browser issue that can't be fixed?

- OS/version: Windows 8.1
- Browser/version: Chrome 63.0.3239.84
- uBlock Origin version: 1.14.20

**Comment by uBlock-user** [comment]
Chrome has a race condition issue, so it's not just that it executes late.

**Comment by gorhill** [comment]
Browser limitation.

**Comment by gorhill** [comment]
I've been looking at how to solve this issue since a long time. For example, see <https://github.com/gorhill/uBlock/issues/3069>.

**Comment by uBlock-user** [comment]
But that's just for Firefox, what about chrome ?
