### ISSUE TITLE
Add an "Import and Replace" button to the Whitelist tab

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#3358]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

The current "Import and Append" button does not clear the existing whitelist if a user is maintaining a whitelist offline (Git repo, etc). A manual step is required to clear the existing list before importing its replacement.

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

<img width="608" alt="append" src="https://user-images.githubusercontent.com/4619810/34158150-305a3fec-e4bc-11e7-92e5-840e05002e07.png">

### Steps for anyone to reproduce the issue

1. Open uBlock settings
2. Click on the Whitelist tab
3. Click Import and append
4. Select whitelist file
5. Whitelist is not cleared beforehand

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: macOS 10.13.2 (17C88)
- Browser/version: Firefox Quantum 57.0.1
- uBlock Origin version: v1.14.22

##### Your filter lists

Default Lists

##### Your custom filters (if any)

N/A

**Comment by gorhill** [comment]
Just delete the list before importing.

**Comment by jose-cardoso** [comment]
And yet your restore settings behaviour contradicts your own suggested action?

Intresting response.

**Comment by gorhill** [comment]
You are comparing restoring all uBO's settings with importing content into a single text box.

**Comment by jose-cardoso** [comment]
I'm simply pointing out inconsistencies on restoration behaviour that could be easily resolved with a user firendly button that just replaces the existing list.

Point in fact, when I click the restore from cloud option this replaces the whitelist rather than append to it.

**Comment by gorhill** [comment]
Can you submit a pull request?

**Comment by jose-cardoso** [comment]
Fine. Will do that instead.

**Comment by jose-cardoso** [comment]
Pull request #3360 submitted. Tested and localised as thoroughly as I could.
