### ISSUE TITLE
Plugin blocking all requests on web application

### ISSUE THREAD

**Issue by TrofimenkoAI** [gorhill/uBlock#3359]
Hi guys, I am here to find solution how to avoid uBlock on my website. Right now I am implementing online store with different fetch API functionality. My customers found that if uBlock active, all requests(POST, GET) not working :( I saw a lot of opened issues but the matter of short time to fix this thing, I'd like to ask how to deactivated this things for all customers who is using this plugin? Mb I should add some kind of script or ...? Sorry if this questions already exists, but I couldn't find any examples.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment]
filter issue, report at easylist repository:

or uassests (if filter issues on uBo specific filters)
https://github.com/uBlockOrigin/uAssets/issues
https://github.com/easylist/easylist/issues

However, you should test yourself in uBo / ABP, and see in the logger what's blocked to help debugging your issue.
