### ISSUE TITLE
Consider mentioning that "Whitelist" overrides anything in "Static filtering" window.

### ISSUE THREAD

**Issue by xftroxgpx** [gorhill/uBlock#3361]
### Describe the issue
Would be cool if the `Static filtering` window (seen in the screenshot below) would textually mention that it's possible that this new filter you're trying to create could have no effect if the site or directive is in the [Whitelist](https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist), especially because the `|even if| there is a matching exception filter` can be selected thereby user could wrongly believe that this new filter would take preceedence over the Whitelist(even though it clearly states in the Whitelist that uBlock will `disable itself completely. When uBO is disabled on a page, there will be no filtering applied to that page.` - though the fact that the request still got displayed in the log made me expect that the new filter would likely override the whitelist (which is never the case, i know now)
![2untitled](https://user-images.githubusercontent.com/26243389/34213760-6c202642-e5a0-11e7-8ca1-0e06430ca98b.png)
)

![untitled](https://user-images.githubusercontent.com/26243389/34212726-7f96c9a4-e59d-11e7-93ab-beebdd9ccd9a.png)

Anything below is irrelevant:

### One or more specific URLs where the issue occurs
any youtube video url

### Steps for anyone to reproduce the issue

Just trying to ensure this filter is always enabled:
`||www.youtube.com/sw.js$domain=behind-the-scene,important`
For that to happen, I had to comment out like `#behind-the-scene` in Whitelist.

(Reason why I want to block sw.js is because (some (modified, I guess)version of)chromium always complains at shutdown that it leaked `n` (n>=1) urls and they are all this same `https://www.youtube.com/sw.js` url; actually it would normally stackdump after that)

**EDIT:** It's also true for `Dynamic URL filtering` window , forgot to mention.

**Comment by gorhill** [comment]
There is a point where adding too much documentation in the UI is just too much. The wiki documentation is the ultimate reference no matter what we would throw at the UI.
