### ISSUE TITLE
Adblock Detector

### ISSUE THREAD

**Issue by Cicorione** [gorhill/uBlock#3364]
Hi There,

this is not a bug report but I would like to report this repository on Git Hub:

https://github.com/InteractiveAdvertisingBureau/AdBlockDetection

IAB tries to detect if someone is using an AD Blocker, they are also creating an Ad Blocker to block ads do not comply with their rules https://github.com/InteractiveAdvertisingBureau/AdBlockDetection.
By the way IAB AD Blocker is not the point, the point is the navigation on my browser is personal what I do with my browser should be private and personal, if I use an Ad Block I don't want that a publisher from the other side knows my behavior.

Do you believe that is possible preventing the publishers to know if I am using uBlock Origin?

Thanks

Cicorione!

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). It includes a link to a forum where you can ask such questions.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
