### ISSUE TITLE
OWA content injection in Edge

### ISSUE THREAD

**Issue by 4fd81048a9cd8a3fd43f1f4e52f84181** [gorhill/uBlock#3366]
Composing messages in Outlook Web Access in Edge with the uBlock Origin pluging installed, results in styles being inserted into the sent message.  This is causing outbound mail filtering to block the message.

```
a[href*=3D'://3wr110.xyz/'], ADS-RIGHT, AFS-AD, [ad-id=
^=3D'googlead'], [lazy-ad=3D'lefttop_banner'], [onclick^=3D'window.open(\'h=
ttp://adultfriendfinder.com/search/'], a[data-obtrack^=3D'http://paid.outbr=
ain.com/network/redir?'], a[data-redirect^=3D'http://click.plista.com/pets'=
], a[data-redirect^=3D'this.href=3D\'http://paid.outbrain.com/network/redir=
?'], a[data-url^=3D'http://paid.outbrain.com/network/redir?'], a[data-widge=
t-outbrain-redirect^=3D'http://paid.outbrain.com/network/redir?'], a[href$=
=3D'/vghd.shtml'], ... { display: none !important; }--></st=
yle>
</head>
```

### Steps for anyone to reproduce the issue
1. Install uBlock Origin from the Microsoft Store
2. Launch Edge
3. Login to an OWA site.
4. Compose and send an E-mail
4a. Outbound mail filtering might quarantine the message due to the content injected.
5. Inspect the received E-mail.

### Your settings
- OS/version:  Windows 10 1709
- Browser/version: Edge
- uBlock Origin version: 1.14.23

**Comment by gorhill** [comment]
What is a "OWA" site?

**Comment by jspenguin2017** [comment]
`Outlook Web App` a.k.a. `https://outlook.live.com/mail/#/inbox`

**Comment by Atavic** [comment]
@4fd81048a9cd8a3fd43f1f4e52f84181 Set up your mail client:

       - Incoming: pop3.live.com
       - Outgoing: smtp.live.com
       - Enable “My outgoing server (SMTP) requires authentication”
       - Incoming Server Port: 995  (Requires SSL)
       - Outgoing Server Port: 25  (Requires TLS)

**Comment by lewisje** [comment]
Disable cosmetic filters on OWA sites.

**Comment by gorhill** [comment]
I sent myself an email through `https://outlook.live.com/mail/#/inbox`, and I did not observed the reported behavior. Will close until OP is more forthcoming about the issue, or whoever can reproduce investigate more about the issue and a solution to it.

**Comment by mrrogers75** [comment]
I have a user in Edge having the same issue intermittently.
