### ISSUE TITLE
Cant update filters when Out of blink CORS is Enabled in Chrome

### ISSUE THREAD

**Issue by ambrosso** [gorhill/uBlock#3369]
### Description

On Google Chrome 64 Beta on MAC OS cant update all selected filters
when in chrome://flags
Out of blink CORS  #out-of-blink-cors  is Enabled

Not tested on Windows.

### Screenshot in which the issue can be seen

<a href="http://piccy.info/view3/11909706/07daac620d5f6549c74f2e599db474a0/orig/" target="_blank"><img src="http://i.piccy.info/i9/f432dff5e90afe71e371b79af2c68266/1514232806/93755/1207907/ublock_cors_enables_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2017-12-25-20-13/i9-11909706/447x800-r" target="_blank"><img src="http://i.piccy.info/a3/2017-12-25-20-13/i9-11909706/447x800-r/i.gif" alt="" border="0" /></a>

### Steps for anyone to reproduce the issue

1. In Google Chrome 64 beta on MAC OS
2. In chrome://flags enable #out-of-blink-cors
2. Pick all filters as in Screenshot
3. Purge and Update Cache

### Your settings

- OS/version: macOS 10.13
- Browser/version: Chrome 64 Beta
- uBlock Origin version: 1.14.22

##### Your filter lists

All filters except Country Specific

**Comment by gorhill** [comment]
How is this a uBO issue?

If you think this is a uBO issue, please provide the solution to make the case it is a uBO issue.
