### ISSUE TITLE
uBlock blocking amazon S3 URLs

### ISSUE THREAD

**Issue by stevewillard** [gorhill/uBlock#337]
Just recently, uBlock seems to be blocking URLs on Amazon's S3, in the form:

https://s3.amazonaws.com/xxxxxxx.min.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

Any reason why this is happening all of a sudden? This was working a few hours ago

**Comment by CrisBRM** [comment]
Just use the logger next time. It has to do with the list 'Malware domains‎ (lehigh.edu)'
https://github.com/gorhill/uBlock/issues/336

Just yesterday they fixed pastebin, which was also incorrectly blacklisted there.

**Comment by stevewillard** [comment]
Great -- thanks!

I purged my uBlock cache, re-downloaded and things seem good now

**Comment by CrisBRM** [comment]
Oh, so they fixed s3 as well. I only grep'd pastebin last night when I was checking for differences. Good to know.

**Comment by hotdogman** [comment]
Nope, you're not crazy. S3, along with pastebin, was incorrectly listed in the Malware Domains list (http://malwaredomains.lehigh.edu/files/domains.txt), which unlock ships with enabled by default.

**Comment by gorhill** [comment]
I forced an update of justdomains on GitHub so that people will be warned there is an update available.
