### ISSUE TITLE
Allow/Block/Noop only if 1st party scripts allowed

### ISSUE THREAD

**Issue by Kusresa** [gorhill/uBlock#3370]
I am using uBO in a hard kind of mode (block all 1st/3rd party scripts and 3rd party frames by default). I also use Decentraleyes for CDNs and have their global noop rules in uBO so it can function properly. I noticed this is maybe not the best end solution to do so as I could be blocking all scripts from a site but since I nooped all CDNs so Decentraleyes can function they will be allowed regardless of my 1st/3rd party script global blocks. 

I am wondering whether it is possible to create some kind of extra tag or function where me allowing local/global 1st party scripts (not 3rd party scripts since they are rarely ever nooped/allowed) will allow the set of noop rules to then take effect.  The only other way I can think to limit allowing these CDNs on a per site rule but that can become a little more tedious and to me the former is a better compromise. 

I'm not really sure whether they is some way to do this or maybe what I said is not a great way either but I read you also use Decentraleyes so maybe you have insight on how I can limit these noop rules to only work when absolutely wanted (and not bypass global blocks).

**Comment by gorhill** [comment]
Declined. Not something I would want to work on.
