### ISSUE TITLE
$badfilter does not work on a CSP filter

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#3371]
### STR

1) Add `@@*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval',domain=investopedia.com` and `@@*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval',domain=investopedia.com,badfilter` to _My Filters_

2) Keeping the logger open, browse to `https://www.investopedia.com/`  

3) Exception filter is applied even though `$badfilter` is present as per the logger - 
![](https://i.gyazo.com/bd8d246b04ee4d85efcd0688443b4ca0.png)

### Your settings

- OS/version: Win 10 x64
- Browser/version: Chrome 65
- uBlock Origin version: 1.14.23.2

**Comment by uBlock-user** [comment]
Actually `$badfilter`, doesn't work on any CSP filter.

For example, Add

```
||example.com^$csp=script-src 'self'
||example.com^$csp=script-src 'self',badfilter
```

to _My Filters_ and then browse to `example.com`, the CSP filter is still applied as per the logger.

**Comment by gorhill** [comment]
As a workaround for now, a specific exception filter is pretty much the equivalent of `badfilter`:

    @@||example.com^$csp=script-src 'self'

**Comment by uBlock-user** [comment]
Yeah, that will do for now, I hope you're able to patch this one soon though.
