### ISSUE TITLE
Regular expression flags in procedural cosmetic filters

### ISSUE THREAD

**Issue by Kusresa** [gorhill/uBlock#3372]
Currently, it looks like the procedural cosmetic filter that can take in regex are not able to take in other trailing flags such as `/g` `/i` `/m` or even within the regex like `/(?i)example/`.

Can support for these be added? They can improve efficiency of rules that can use them and reduce filter length/number of some filters.

**Comment by gorhill** [comment]
The syntax is the same a literal javascript flags:

    example.com##body:has-text(/PRIOR/i)

Only two flags are supported: `i` and `m` (support for `g` is pointless).

I partially checked with some filter lists know to use procedural selectors and I could not find any ambiguity. If ever someone need to lookup for a string literal like `/ad/im`, the solution is to use a regular expression to work around flag parsing: `/\/ad\/im/`.

**Comment by jspenguin2017** [comment]
Would `/ad/im*` be parsed as string literal or still RegExp?

**Comment by gorhill** [comment]
String literal. I don't want special syntax such as wildcards -- that is why regex literal are supported, to take care of when a literal string is not enough.

**Comment by jspenguin2017** [comment]
So the proper solution to make `/ad/im` a string literal would be add a trailing wildcard?

**Comment by Kusresa** [comment]
> Only two flags are supported: i and m (support for g is pointless).

Just curious, what's the reason it's pointless?

**Comment by jspenguin2017** [comment]
If it matches it matches, doesn't matter how many times.

**Comment by Kusresa** [comment]
So am I to understand that the `g` flag isn't needed because uBO already will find all matches and not just stop after the first match? (please correct me if I'm wrong)

**Comment by jspenguin2017** [comment]
You only need to match once for the filter to trigger.
