### ISSUE TITLE
nnm-club ad

### ISSUE THREAD

**Issue by spartaque12** [gorhill/uBlock#3377]
cant block this shitty ad at nnm-club.name
![default](https://user-images.githubusercontent.com/6484816/34394345-3a08e2c2-eb61-11e7-8050-8436d963587d.PNG)

**Comment by mapx-** [comment]
ses if works
```
||nnm-club.name^$csp=script-src 'self' * 'unsafe-inline'
nnm-club.name##[id*=Composite]
```
However you should report filter issues here:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by mapx-** [comment]
You should use `RUS: Adguard Russian Filter` too (where the issue was already fixed)

**Comment by spartaque12** [comment]
@mapx- thanks , i didnt use Adguard Russian Filte , my bad

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
