### ISSUE TITLE
Issue loading a site - not sure if uBlock Origin issue or just a filtering list error

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#338]
When trying to open `http://www.aliexpress.com/` in a new Firefox 38.0.5 installation with uBlock Origin 0.9.8.2, uBlock Origin prevented loading the page, displaying the strict blocking screen instead: 

`uBlock₀ has prevented the following page from loading:`
`http://stat.gmonitor.aliimg.com/stat.htm`

`Because of the following filter`
`||gmonitor.aliimg.com^`

Trying to load the site again worked fine.  As did several subsequent attempts.  Clearing the cache and all cookies and trying to access that site worked without a problem three times.  Then, it failed again, giving the same block screen.

I don't have the time to diagnose the issue, so I thought it best to post it here.  I'm guessing it is something like a redirect issue with the site triggering a match to a list, but the behavior is odd enough that it warrants further diagnosis.

**Comment by gorhill** [comment]
What is the issue?

From what I read, all went as expected.

How did you try to reach `http://www.aliexpress.com/`? Clicked a link?

As documented, if you temporarily override strict blocking, it will work until the temporary override is revoked, which the wiki [documents](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking) as "after one minute". So strict blocking kicked in after 60 seconds.

**Comment by Gitoffthelawn** [comment]
Thanks.  How do I re-open an issue?  I see `Edit` (to edit the title) and `New Issue`, but no `Re-open`.

To try to open AliExpress, I just type `http://www.aliexpress.com/` into the Location Bar.

At that time, sometimes, but not always, I get uBlock Origin's screen blocking the attempt to access that URL, but it says that the page being blocked is 'http://stat.gmonitor.aliimg.com/stat.htm', which is not what I typed into the Location Bar.  My guess is that there is perhaps a redirect to that site, but I don't have time to step through it.

The issue is that I am going to `http://www.aliexpress.com/`, but uBlock Origin is intermittently blocking access to that site, claiming I am trying to go to 'http://stat.gmonitor.aliimg.com/stat.htm'.  Might be an issue with uBlock Origin, or might just be an unfortunate side-effect of how the site is coded.

**Comment by gorhill** [comment]
> I don't have time to step through it

Look at the logger.

>  How do I re-open an issue?

As I said: reopen if you make the case uBlock is doing something wrong.

**Comment by Gitoffthelawn** [comment]
I don't have time now to look through the logger.  Maybe some other time.  Or perhaps someone else is interested.

If it is a uBlock issue, how does one re-open the issue via the github web interface?

**Comment by gorhill** [comment]
> how does one re-open the issue via the github web interface?

Just provide data supporting that there is an issue and I will reopen.
