### ISSUE TITLE
Block google globally except for dependent domains

### ISSUE THREAD

**Issue by jsEveryDay** [gorhill/uBlock#3381]
I don't think this feature exists yet, maybe it doesn't have to be a feature, just for google would be enough.

Basically I want to block all google.com or *.google.com since there's plenty of websites that use that domain for tracking. How can I globally block this source except for the google services ie youtube gmail hangouts etc...

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
