### ISSUE TITLE
Incorrect filter parsing issue

### ISSUE THREAD

**Issue by toshiya44** [gorhill/uBlock#3386]
### Describe the issue
There seems to be an issue with filter parsing. The filter in question is from `RUS: Adguard Russian Filter`. This filter seems to get injected into every webpage and when I click on it to see where it's coming from, it shows up blank.

![screenshot](https://user-images.githubusercontent.com/20046789/34465111-e88ab6e4-ee96-11e7-8a85-fb69e926d693.PNG)

`
kanobu.ru,num-link.ru,matchtv.ru,vse.fm,seetv.tv,mk.ru,sto4ou933dx3.ru,gismeteo.ru,kurs.com.ua,websetnet.com,lifenews78.ru,life.ru,звонки.онлайн,bitru.org,hdrezka.tv,stopgame.ru#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}
`

After some trial and error, this seems to be the smallest version of that filter that triggers this behavior

`звонки.онлайн,stopgame.ru#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}`

### One or more specific URLs where the issue occurs

Example: https://github.com 

### Steps for anyone to reproduce the issue

1. Add the filter in "My filters".
2. Open logger and browse any site (github).

### Your settings

- OS/version: Win 8.1
- Browser/version: FF Dev 58.0b12 (32-bit)
- uBlock Origin version: 1.14.23b9

##### Your filter lists

Default

##### Your custom filters (if any)

`
kanobu.ru,num-link.ru,matchtv.ru,vse.fm,seetv.tv,mk.ru,sto4ou933dx3.ru,gismeteo.ru,kurs.com.ua,websetnet.com,lifenews78.ru,life.ru,звонки.онлайн,bitru.org,hdrezka.tv,stopgame.ru#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}
`

**Comment by gorhill** [comment]
Thanks for reporting.

Yes, silly mistake on my side.
