### ISSUE TITLE
Changed advanced settings aren't stored permanently

### ISSUE THREAD

**Issue by terr72** [gorhill/uBlock#3387]
### Describe the issue

Advanced settings aren't being stored. After a restart the values are reset to their default values.

### Steps for anyone to reproduce the issue

1. Go to advanced settings.
2. Change manualUpdateAssetFetchPeriod from 2000 to 1000 and hit the Apply button.
3. Close and restart Firefox.
4. Go to advanced settings and manualUpdateAssetFetchPeriod is back at 2000.

### Your settings

- OS/version:  Linux Mint XFCE 18.3
- Browser/version: Firefox 57.0.3
- uBlock Origin version: 1.14.22

**Comment by gorhill** [comment]
Because <https://bugzilla.mozilla.org/show_bug.cgi?id=1313401>.

I will move the advanced settings out of local storage when I fix #3318.

**Comment by gorhill** [comment]
Fixed with a81d2a759bd8.
