### ISSUE TITLE
Update ublock origin blocking and benchmarking documentation

### ISSUE THREAD

**Issue by erotavlas85** [gorhill/uBlock#3388]
Hi,
I consider ublock origin the best ad blocker on the Web. However, the documentations related to tracking and malware blocking capabilities [here](https://github.com/gorhill/uBlock/wiki/uBlock-and-others%3A-Blocking-ads%2C-trackers%2C-malwares) and the benchmarking related to CPU and memory usage [here](https://github.com/gorhill/uBlock) are outdated (old plug in and browser version).
Today we have a great change especially for firefox quantum (since version 57) and we have brave a new browser with integrated ad blocking. It would be great if you would have time to update both documentation at least with firefox quantum, chromium/chrome and brave (it would be greatest also with safari and edge).
Thank you in advance.

**Comment by gorhill** [comment]
Anybody can run benchmarks, it does not have to be me. I still run benchmark for dev purpose, so I as to ensure continued uBO efficiency. But I am not going take on even more stuff for me to do at this point.

**Comment by erotavlas85** [comment]
Ok, it sounds like now ublock origin does not have any more the previous advantages over the other ad blocker, otherwise I do not see why do not public the documentation.
Thank you

**Comment by gorhill** [comment]
First day of 2018 on GitHub...

> otherwise I do not see why do not public the documentation

I don't have the time, as said -- there is [no reasons](https://twitter.com/adildean/status/936183316134416384) for me to think there is an issue with efficiency relative to other blockers. These benchmarks demand a lot of work to do correctly to get reliable, solid data; it's time-consuming, at the expense of fixing actual issues affecting users.

You can do benchmarks if you are curious yourself about this. Why don't you do it yourself? So far nobody has come forward as showing uBO being less efficient in real usage, so there is no reason to think otherwise without evidence to the contrary.

**Comment by erotavlas85** [comment]
I would not be rude with my request, but I think it is necessary since a lot of water has flown under the bridge.
Latest benchmark on tracking and malware blocking is dated 16 February 2015 with very old version of ublock, adblock plus, disconnect and ghostery.
Moreover, benchmarking about CPU and memory are done with firefox 41 which was 64 bit only on GNU/linux (me, but about 3% users), but not on Windows (about 85% users) where it started to be 64 bit since 43 [link](https://wiki.mozilla.org/Firefox/Win64).
I found this interesting data on your github page with recent version of firefox 52 and chromium 59 [link](https://github.com/gorhill/uBlock/wiki/Firefox-version:-benchmarking-memory-footprint).
Moreover, firefox has an integrated tracking protection since version 57 [link](https://support.mozilla.org/en-US/kb/tracking-protection?as=u&utm_source=inproduct) and it is full multiprocess. So many differences are expected in term of CPU, memory and tracking capabilities.
Finally, my point is to show which is at the moment the best browser and ad blocker. I do not think to have the necessary competencies in order to do it by myself, but it would be very interesting as spare time project.
Best Regards
