### ISSUE TITLE
XPath 3.1 support?

### ISSUE THREAD

**Issue by sebast889** [gorhill/uBlock#3389]
I was using XPath filters and noticed some syntax and functions are not able to be used. From searching it looks like this is may be because Firefox only supports version XPath 1.0 and uBO can only use this version(?). They also have no plans to upgrade to 3.1 as far as I know, I don't know why since the W3C recommends version 3.1 and functions in the new versions could definitely be more helpful in creating XPath filters. I am not sure whether it is possible to implement XPath 3.1 support yourself as an extension author or if this something that is limited by the browser. But if it's possible to do this in extensions I think this can be an useful upgrade.

**Comment by gorhill** [comment]
> whether it is possible to implement XPath 3.1 support yourself

I am speechless. Such a huge unrealistic feature request with not even a single use case provided to make the case this is actually needed.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sebast889** [comment]
@gorhill please don't mistake my simple intentions as wanting you to undertake gigantic tasks!! I am not a coder so I don't know how code implementation works, I just want uBO to be good as possible so I asked whether this upgrade is even possible (I don't know if this can be done by the extension author or the browser). I thought xPath was a library of resource code which can be modified by extension authors for their own use since it is a standard..forgive my ignorance if this isn't how it works. Re-reading my post I can see why you might have thought that I wanted you write all xPath code yourself, I apologize for not being clearer in what I thought sometimes I forget things that are small details in my mind may be big in others. Judging by your response (I still don't know for sure) it means for xPath 3.1 you will need write all the code yourself? I can post some examples but I am only a beginner in using xPath and I don't think the extra functions I thought to have would be worth it if you have to write all the code yourself to upgrade to XPath 3.1.

**Comment by jspenguin2017** [comment]
It is implementable in JavaScript: 
https://github.com/ilinsky/jquery-xpath/
https://github.com/FontoXML/fontoxpath

**Comment by jspenguin2017** [comment]
AFAIK, for Chromium, it uses libxml2 which refused to implement anything newer than XPath 1.0.
