### ISSUE TITLE
0.9.8.7-dev.9 doesn't block any ads

### ISSUE THREAD

**Issue by drbluetongue** [gorhill/uBlock#339]
Hi,

After updating to the latest dev build on Firefox nightly, all ads are now green and uBlock doesn't block anything.
1. Update to 0.9.8.7-dev.9
2. Browse any news site, see the ads
3. Downgrade to 0.9.8.6 and refresh the page - the ads will disappear

Thanks

**Comment by gorhill** [comment]
Works fine with me.

> Browse any news site

From <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>:

> **Always include a URL**, even if "it happens everywhere". Just do it.

**Comment by drbluetongue** [comment]
Sorry!

Http://bristolpost.co.uk/ is one that springs to mind.

**Comment by gorhill** [comment]
> Http://bristolpost.co.uk/ is one that springs to mind.

I don't see any ads with Nightly + 0.9.8.7-dev.9.

You say "all ads are now green". You mean in the logger? If so, show a screenshot of the logger.

**Comment by Betsy25** [comment]
I can confirm, even on this same page here, using the default lists, everything is allowed.
No blocking list filters nor your own ones nor element hiding occurs.

Firefox nightly 41
Using the current commit a722d54bc4801399947fcb30ae6d684dc6e9aa46 (= Latest  0.9.8.7-dev.9 + 3 commits)

![Screenshot](http://i.imgur.com/ltX1eVB.png)

**Comment by gorhill** [comment]
> Issue seems gone after purging caches and updating lists

Hmmm ok... I thought I should not need to force the compiled filter lists to be invalidated, but to be on the safe side I will force such operation in the next dev build, which I will submit shortly.
