### ISSUE TITLE
HTML filtering can break encoding

### ISSUE THREAD

**Issue by hant0508** [gorhill/uBlock#3391]
### Describe the issue
HTML filters convert text to Unicode, but Firefox still chooses language-based encoding.

### One or more specific URLs where the issue occurs
`https://vk.com/rbc`
`https://new.pikabu.ru/best`

### Screenshot in which the issue can be seen
![screenshot_2018-01-02 1](https://user-images.githubusercontent.com/28459131/34492717-fd262714-eff9-11e7-9048-641d8569d6f5.png)
![screenshot_2018-01-02](https://user-images.githubusercontent.com/28459131/34492718-feac14ea-eff9-11e7-820b-0950d8830720.png)

### Steps for anyone to reproduce the issue
1. Visit [vk.com/rbc](https://vk.com/rbc). You can see correct Russian text on the page. Check your encoding: it should be `Cyrillic (Windows)`.
![screenshot_2018-01-02 2](https://user-images.githubusercontent.com/28459131/34493113-819585de-effb-11e7-8317-7da25fe4cf55.png)
2. Hide something using HTML filtering. For example, `vk.com##^.current_text`.
3. Refresh the page. Now you can see broken text. Check encoding: it is still `Cyrillic (Windows)`.
4. Select Unicode. Now the text is correct.

### Your settings

- OS/version: Debian GNU/Linux
- Browser/version: Mozilla Firefox 57.0.3
- uBlock Origin version: 1.14.23b10

**Comment by gorhill** [comment]
Thanks for the report, it's going to involve some investigation/thoughts.

uBO uses TextEncoder to convert back the modified DOM into a buffer array expected by the browser's StreamFilter. TextEncoder however does not allow to encode into anything else than utf-8. I made uBO add a `<meta charset"utf-8">` at the top of the DOM to be sure the browser decode properly the data, however this does not seem to work in your repro case.

So I will need to investigate about what can be done, if anything.

Ultimately, I figure if all fail and nothing can be done when using TextEncoder, I might have to consider custom encoders, possibly using WebAssembly, if I want HTML filtering to be available to more than just utf-8-encoded pages.

**Comment by harshanvn** [comment]
> I made uBO add a <meta charset"utf-8">

Just checking. You meant `<meta charset"utf-8">`. `=` missing in your reply.

**Comment by gorhill** [comment]
I think I will go on a usage basis. According to [this page](https://w3techs.com/technologies/history_overview/character_encoding), probably worth to provide encoding for the top most likely:

charset | usage Jan 2018
---- | ----
ISO-8859-1 | 4.3%
Windows-1251 (case here) | 1.5%
Shift JIS | 0.8%
Windows-1252 | 0.7%
GB2312 | 0.6%

**Comment by gorhill** [comment]
The Shift_JIS and GB2312 mapping will have to be loaded dynamically, on a per-need basis, these are huge character sets.
