### ISSUE TITLE
Filter lists can't be updated in Tor Browser

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [gorhill/uBlock#3393]
The title should be pretty much self-explanatory. Filter lists remain outdated after the update, which is very easy no notice by the number of filters in the "Resource abuse" list (it's supposed to be over 100, but stays at 39). It's also impossible to open any list by clicking on it.

Fresh install of Tor Browse 7.0.11 (Firefox 52.5.2) with default settings, uBlock Origin 1.14.22, Windows 8.1 x64.
Confirmed on multiple systems.

It started after uBO was converted to WebExtension. This problem should be caused by the Firefox bugs that are described here: http://forums.mozillazine.org/viewtopic.php?f=9&t=3034189
But it will take a while for the fix from Mozilla to arrive, especially in Tor Browser, which is based on the ESR branch (and the mentioned workaround with whitelisting doesn't seem to work in Tor Browser). So I think that it's necessary to implement some kind of fix in uBO itself (if possible).

**Comment by gorhill** [comment]
Use the legacy version if you do not want to suffer issues specific to the WebExtensions version.

**Comment by tsjnachos117** [comment]
It seems I spoke too soon: uBlock has gone right back to it's old behavior. Back to the 1.13* versions for me. I guess that will make things interesting when the Tor Browser eventually updates to the next ESR.
