### ISSUE TITLE
Scriptlet injection

### ISSUE THREAD

**Issue by Coverlin** [gorhill/uBlock#3394]
Option to disable/ignore it for a website ? instead of removing the whole filter or disabling ubo on the website

Example:
example.com##script:inject(yavli-defuser.js)
I want to disable any js injection on the example.com to prevent site breakage
And/Or
Disable/ignore a specific js , in this case only yavli-defuser.js on the example.com domain

**Comment by okiehsch** [comment]
`example.com#@#script:inject(yavli-defuser.js)` disables the specific script-injection, i.e. `yavli-defuser.js`, for the given site.
If you want to disable all script-injections on a specific website, you have to disable all of them one by one.

**Comment by Coverlin** [comment]
@okiehsch Working great , thanks for the help !
I will close this issue , sorry if it was known i've read the help section and didn't saw this method there

**Comment by gorhill** [comment]
If you set a local `allow` rule for the 1st-party domain (`example.com` in your example), this will prevent all scriptlet injection.
