### ISSUE TITLE
Parts of uBlock matrix remains open after disabeling advanced user modus

### ISSUE THREAD

**Issue by heubergen** [gorhill/uBlock#3395]
### Describe the issue
After activating and deactivating the  _I am an advanced user_ modus, uBlock still shows parts of the matrix (see screenshot below). I don't think that this is the correct behavior as a user would expect that the menu would be the same again as right after the installation of the add-on.

### One or more specific URLs where the issue occurs

Not related to website but I tested it with https://www.google.com/

### Screenshot in which the issue can be seen

<img width="510" alt="screen shot 2018-01-02 at 9 32 56 pm" src="https://user-images.githubusercontent.com/5529410/34507495-89bc1b8e-f004-11e7-88d9-2adfa0fbd791.png">

### Steps for anyone to reproduce the issue

1. Open uBlock settings and activate _I am an advanced user_
2. Open a new tab and click on the uBlock icon
3. Switch back to the uBlock settings and deactivate _I am an advanced user_

### Your settings

- OS/version: macOS 10.13.1
- Browser/version: Firefox Nightly Build 2018-01-02
- uBlock Origin version: 1.14.22

**Comment by Coverlin** [comment]
Can confirm , however if you wish to hide the domain lists you can do so by clicking on requests blocked or domains connected and it will compact the UI

**Comment by gorhill** [comment]
By design, that panel is not prevented from being opened in normal mode, just collapse it by clicking the "requests blocked" or "domains connected" labels.

**Comment by heubergen** [comment]
May that how a user can restore the original UI but it is for sure not how uBlock should work because this bug changes the UI without user interaction.

**Comment by gorhill** [comment]
> without user interaction

You enabled "advanced user" mode. The firewall panel opens automatically the first time as a convenience, those who check "advanced user " mode surely wants to access that panel.

I am going to add documentation in <https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-number-of-domains-connected> for this.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel
