### ISSUE TITLE
Sync does not work reliably

### ISSUE THREAD

**Issue by martinrotter** [gorhill/uBlock#3396]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I use uBlock Origin on Firefox on Linux and Windows, both devices have Firefox sync enabled in uBlock settings. Sometimes, I add some extra filter and it appears in "My filters", this filter does not get sync'ed.

### Steps for anyone to reproduce the issue
1. Run Firefox 57 with UO, have sync enabled in FF and UO.
1. Go to Linux machine, add some filter to "My filters" and push "Export to cloud storage" button.
1. Restart to Windows machine, go to "My filters" and hit "Import from cloud .... and merge ..." button.
1. Filter added in step 2 does not appear.

### Your settings
Enabled cloud storage support in settings.

- OS/version: Linux + Windows 10
- Browser/version: Firefox 57
- uBlock Origin version: uBlock Origin v1.14.22

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment]
You will have to diagnose this yourself, you are the best placed to investigate. Go through the issue tracker for all that sort of issue. There is a lot of things out of control of uBO with Firefox Sync, and you need to look at that side first.

**Comment by martinrotter** [comment]
OK
