### ISSUE TITLE
HTML encoding broken when page is encoded with win-1250

### ISSUE THREAD

**Issue by Kisuke-CZE** [gorhill/uBlock#3397]
Hello,

simillar problem like in bug [3391](https://github.com/gorhill/uBlock/issues/3391), only difference is page encoding is windows-1250. For example www.idnes.cz. Any chance to fix this encoding too?

**Comment by gorhill** [comment]
I am having problem having that site display fine, even with Chromium, so it's not a good test case for me. You have a better site for testing this issue?

**Comment by Kisuke-CZE** [comment]
What about www.gaz.cz or www.lidovky.cz ?

**Comment by gorhill** [comment]
> What about `www.gaz.cz`

Yes, this one renders fine.

Do you have issue with `www.idnes.cz`?

**Comment by gorhill** [comment]
Looks like `www.idnes.cz` is using cookies to decide to serve a good or broken page. When I use uMatrix with cookies blocked, the page renders fine all the time. As soon as I allow cookies, I get a broken version. I suspect it's a way to force people to disable their blocker.

**Comment by Kisuke-CZE** [comment]
`www.idnes.cz` and `www.gaz.cz` acts similar for me. When I try to filter out script or some HTML object, it only has bad encoding.

On idnes.cz I am using this filter to avoid their anti-adblock JS: `idnes.cz##script:contains(addEventListener)`

Works for me so far. Only that encoding thing.

Reproducing on `www.gaz.cz`:
- go to `www.gaz.cz`
- add this filter to uBlock Origin: `gaz.cz##^.zvyrazni`
- refresh page

**Comment by gorhill** [comment]
> On `idnes.cz` I am using this filter to avoid their anti-adblock JS:
> `idnes.cz##script:contains(addEventListener)`

Works for me. You should really submit it for inclusion at <https://github.com/tomasko126/easylistczechandslovak/issues>.

**Comment by Kisuke-CZE** [comment]
Many thanks, works great now.
