### ISSUE TITLE
HTML filtering breaks webpages of Shift_JIS encoding

### ISSUE THREAD

**Issue by yasmise** [gorhill/uBlock#3399]
### Describe the issue
An issue similar to #3391 and #3397 also happens when the webpage's encoding is Shift_JIS. I think you are aware of this regarding to [your comment](https://github.com/gorhill/uBlock/issues/3391#issuecomment-354868704), so I'm glad if you could add support for Shift_JIS.

### One or more specific URLs where the issue occurs
http://www.sony.jp/
http://www.itmedia.co.jp/

### Screenshot in which the issue can be seen
Left side is good, right side is broken.

www.sony.jp
![sony](https://user-images.githubusercontent.com/22886576/34563829-8e103d70-f197-11e7-8338-5836ca25d074.jpg)

www.itmedia.co.jp
![itmedia](https://user-images.githubusercontent.com/22886576/34563830-90552eec-f197-11e7-93d2-3e76e72201a8.jpg)

### Steps for anyone to reproduce the issue
1. Add these testing filters.
```
sony.jp##^script:has-text(sony-marketing)
itmedia.co.jp##^script:has-text(document.write)
```
2. Visit `http://www.sony.jp/` or `http://www.itmedia.co.jp/`. The page is broken.
3. Even I change the encoding to Unicode, text is still broken.

### Your settings
- OS/version: Windows 10 Home 1709
- Browser/version: Firefox 57.0.3
- uBlock Origin version: 1.14.23b12

##### Your filter lists
Default + JPN

##### Your custom filters (if any)
itmedia.co.jp##^script:has-text(document.write)
sony.jp##^script:has-text(sony-marketing)

**Comment by gorhill** [comment]
This is part 1 of the fix: if a text encoding is not supported, bail out of enforcing HTML filtering. I thought I had it fixed when I fixed #3397, but clearly this was not working as intended. I tested the repro cases here, and HTML filtering was correctly skipped, since the encoding for Shift_JIS is not available yet.

**Comment by gorhill** [comment]
ftp://ftp.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/SHIFTJIS.TXT

**Comment by eEIi0A5L** [comment]
### Describe the issue
I have faced same issue. Just adding information.

### One or more specific URLs where the issue occurs
http://www.wowkorea.jp/starnews/400626.html

### Screenshot in which the issue can be seen
![default](https://user-images.githubusercontent.com/30253227/35765141-75dd1ec2-0901-11e8-8dd2-dbc318041f40.jpg)

### Steps for anyone to reproduce the issue

1. Create and use a new profile for Firefox.
2. Install uBlock Origin 1.15.0
3. The filter settings are only below:
  .jp##^div[id^="div-gpt-ad"]
4. Go to http://www.wowkorea.jp/starnews/400626.html


### Your settings

- OS/version:  Windows 10 Japanese 16299.214
- Browser/version: Firefox 58.0.1 64 bit
- uBlock Origin version: 1.15.0

##### Your filter lists
just below only, no other filters.

.jp##^div[id^="div-gpt-ad"]

![2](https://user-images.githubusercontent.com/30253227/35765184-21b4c182-0902-11e8-81c2-48684d9f7629.jpg)

![3](https://user-images.githubusercontent.com/30253227/35765203-9f5d2c8c-0902-11e8-8839-709fb4313834.jpg)
