### ISSUE TITLE
Yahoo mail ads unable to be blocked through EasyList

### ISSUE THREAD

**Issue by AmperAndSand** [gorhill/uBlock#340]
There recently have been a lot of reports at the EasyList forums about unblocked Yahoo mail ads appearing at the top of the list of email messages at https://mail.yahoo.com (once logged in). I've also experienced this issue even when subscribed to Fanboy's Ultimate List (combined EasyList + EasyPrivacy, among others). The ads link to URLs that start with `beab.gemini.yahoo.com`.

[![screenshot of issue described above](https://i.imgur.com/tvsqfZs.png)](https://i.imgur.com/tvsqfZs.png)

Screenshot source: https://forums.lanik.us/viewtopic.php?f=62&t=23261
Other reports on the same issue:
https://forums.lanik.us/viewtopic.php?f=62&t=23261
https://forums.lanik.us/viewtopic.php?f=62&t=23215
https://forums.lanik.us/viewtopic.php?f=62&t=23209
https://forums.lanik.us/viewtopic.php?f=62&t=23179
https://forums.lanik.us/viewtopic.php?f=62&t=23077

The EasyList maintainers haven't acted on the multiple reports. This leads me to believe that these ads can't be blocked on EasyList's side. I've tried Element Picker but I can only block one instance of an ad per filter - it appears again on a new page load. How do I configure uBlock Origin to block these ads? 

I'm using Firefox 38.0.5, uBlock Origin 0.9.8.5 on Windows 7. My uBlock Origin settings: http://pastebin.com/Lxrwzh7U

**Comment by 5t3f4n** [comment]
Select it with the [element picker](https://github.com/gorhill/uBlock/wiki/Element-picker) or block its domain?
[Dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) with default-deny would of course also take care of the problem.

**Comment by LeafG** [comment]
>Dynamic filtering with default-deny would of course also take care of the problem.

Actually, not always.
I wasn't able to re-produce an exact scenario so I didn't report it as an issue, but it's happening with default-deny as well.

my config:
Seamonkey 2.33.1
uBlock 0.9.8.6
Win7 x64

**Comment by androidland** [comment]
This might be the reason yahoo buys ClarityRay
http://www.thehubcomms.com/news/yahoo-buys-software-that-shows-you-the-ads-youre-trying-to-block/article/366806/

**Comment by gorhill** [comment]
> The EasyList maintainers haven't acted on the multiple reports

Strange. Same thing on that ABP forum thread: <https://adblockplus.org/forum/viewtopic.php?f=10&t=31494>, no answer from the ABP people. Blockable or not, they would at least have answered, but no answer at all in all instances.
