### ISSUE TITLE
Add filter URL *.me & *.bid

### ISSUE THREAD

**Issue by theray85** [gorhill/uBlock#3402]
This urls alert my antivirus as URL/Malware.
I create as my private filter list, but anyone add url to ublock update. I dont know how.
I will never not use these domains (*.me) from my country, so i blocked it.
Sorry for my bad english.

vcfs6ip5h6.bid
https://kho3au7l4z.me
do69ifsly4.me
https://hzsod71wov.me/ca.bin
https://npdaqy6x1.me
*.me/*.bin
*.me
*.bid

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
