### ISSUE TITLE
uBlock can't block ad at http://kaztorka.org

### ISSUE THREAD

**Issue by inDigazzZ** [gorhill/uBlock#3403]
### Describe the issue
There's iFrame `##body > iframe` which doesn't disappear after blocking.

### One or more specific URLs where the issue occurs
http://kaztorka.org

### Screenshot in which the issue can be seen
https://imgur.com/a/MLF9G

### Steps for anyone to reproduce the issue
1. Open http://kaztorka.org (problem that you have to use Kazakhstan's proxy)
2. Try to block ad

### Your settings
- Windows 10 Insider Preview 17063: 
- Opera Develore/51.0.2809.0: 
- uBlock Origin version/1.14.22: 

##### Your filter lists

Default filter lists + 

AakList (Anti-Adblock Killer)​​​​​​
Basic tracking list by Disconnect​​​​​
NoCoin Filter List​​​​​
RU AdList: BitBlock

**Comment by mapx-** [comment]
the filter issues have to be reported here:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by mapx-** [comment]
close the issue

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
