### ISSUE TITLE
HTML filtering not working in GBK's webpage.

### ISSUE THREAD

**Issue by ghcsd** [gorhill/uBlock#3405]
### One or more specific URLs where the issue occurs

http://www.163.com/
http://www.qq.com/

### Steps for anyone to reproduce the issue

1.  Add
 ```
www.qq.com##^body
www.163.com##^body
 ``` 
to My Filters.

2.  Browse to http://www.163.com/
3.  This page's body has not been removed.

### Your settings

- OS/version: win 10 x64
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.23b13

##### Your filter lists
Default

**Comment by gorhill** [comment]
Given that [GBK is listed at 0.2%](https://w3techs.com/technologies/history_overview/character_encoding) (and that figure will only go down with time), I will decline, especially that you do not provide an actual case for which only HTML filtering can solve the issue.

**Comment by jspenguin2017** [comment]
`qq.com` is one of the largest if not *the* largest news site in China, it's owned by Tencent.

**Comment by ghcsd** [comment]
It is added that GB2312 is a subset of GBK.

**Comment by gorhill** [comment]
<https://en.wikipedia.org/wiki/GB_2312#Two_implementations_of_GB2312>:

> W3C's technical recommendation specifies a GBK encoding to be inferred for streams labelled gb2312, which in turn uses a GB18030 decoder.[

**Comment by Atavic** [comment]
In 2017 QQ users went down to 850M, surpassed only by WeChat with 963M users.
 
Ref: https://github.com/gorhill/uBlock/issues/3405#issuecomment-355719242

**Comment by gorhill** [comment]
I might have to ship 1.15.0 without encoding for Shift JIS and GBK available -- these are anything but trivial size-wise. It's a pity that such encoding code is present in the browser, but unavailable to extensions.

**Comment by jspenguin2017** [comment]
Looks like `TextDecoder` can still decode it, just `TextEncoder` can't encode it due to [awesome specs](https://www.w3.org/TR/encoding/#dom-textencoder). 
If you modify the header and trascode the stream, does it still break? Or you are worried about performance?

**Comment by gorhill** [comment]
> modify the header and trascode the stream

It's what I used to do in early versions of HTML filtering, normalizing all HTML-filtered pages to utf-8. This causes more issues in the end, because web pages can dynamically fetch content to add to the page which is not processed through HTML filtering.
