### ISSUE TITLE
Add cryptocurrency mining blocklist

### ISSUE THREAD

**Issue by PalZer0** [gorhill/uBlock#3407]
With the rise in sites using cryptocurrency mining scripts (https://www.extremetech.com/computing/257786-browser-cryptocurrency-mining-exploding-across-web) and with Opera including a cryptocurrncy mining blocker in its latest version (https://betanews.com/2017/12/25/opera-50-bitcoin-cryptocurrency-mining/), I feel that there should be some sort of cryptocurrency mining filter list included in the default installation (I'm not sure if there's such a filter list available - it may need to be created via the uAssets repo).

**Comment by mapx-** [comment]
look at the lists under uBo => resource abuse
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt

**Comment by PalZer0** [comment]
@mapx- Thanks for pointing that out.

**Comment by mapx-** [comment]
there is a section in the easyprivacy list about mining and there is also other list available (nocoin list) here:
https://adblockplus.org/en/subscriptions#type_other
