### ISSUE TITLE
Allowing a domain via menu and using uBO's own reload button does not do a cache-invalidating reload

### ISSUE THREAD

**Issue by foobar13373** [gorhill/uBlock#3408]
### Describe the issue

In the later versions of uBO (can't exactly say since when, just noticed this. maybe it was always this way, maybe since the webext version), on some website uBO's own reload button does not correctly reload the website.

Below you'll find an example website. This website has an image slider below its menu. If all resources are disabled by uBO (red button on "all resources" in the left column) the example website will tell you that you need JavaScript to fully use the site. If you then allow the main-domain (I tried both, the middle gray and green button in right column, to make sure it's not a filter issue) and click uBO's own reload button, the page will reload with all styles. However the image silder will still say that it's needs JavaScript - however uBO does not actually block JS, the message comes from the browser cache. Doing a Ctrl+F5 (cache-invalidating) reload, will correctly load the now working JavaScript-enabled slider.

I noticed this on some website now, so I assume this is a rather new behavior. I'm not sure if it is intented or changed in some FF / uBO version, but to me it feels wrong.

### One or more specific URLs where the issue occurs

https://www.kfw.de/kfw.de.html

### Steps for anyone to reproduce the issue

1. Block everything using uBO (red button on all resources, left column)
1. go to example website (see above)
1. you should see unstyled content, where somewhere it says that you'll need JS enabled (German: "Tipp: Aktivieren Sie Javascript, damit Sie alle Funktionen unserer Website nutzen können.")
1. Allow the domain (right column of uBO buttons, gray or green, for this domain)
1. Click uBO's own reload button
1. "JS missing" warning still appears (scroll to top to see it, it's styled now, but same text, image slider won't work)
1. reload again using Ctrl+F5
1. the image slider loads correctly now

### Your settings

- OS/version: Windows 10
- Browser/version: FF 57.0.4
- uBlock Origin version: 1.14.22

**Comment by gorhill** [comment]
Browser issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1376932>.

I won't make uBO bypass the cache by default, but I can make uBO's reload button behaves as the browser's reload button.
