### ISSUE TITLE
Question - Annoyances List By Default

### ISSUE THREAD

**Issue by Tony874** [gorhill/uBlock#3409]
I was wondering why none of the annoyances lists like the uBlock, Adguard and Fanboy, have been enabled by default, particularly as they seem to block a lot of adds and popups.

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).  It includes a link to a forum where you can ask such questions.

**Comment by gorhill** [comment]
None have been enabled by default.
