### ISSUE TITLE
Cannot follow links from twitter

### ISSUE THREAD

**Issue by Bladtman242** [gorhill/uBlock#341]
With uBlock enabled (even when disabled on twitter), I can no longer follow links from tweets.
The problem disappears when the uBlock origin plugin is disabled entirely from the browser settings.

**Comment by CrisBRM** [comment]
Can you give us a link to a tweet that contains a tweet? Did you check the [logger](https://github.com/gorhill/uBlock/wiki/The-logger)?

**Comment by gorhill** [comment]
> I can no longer follow links from tweets.

I could follow links just fine. Did you ask uBlock [to block all popups](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-popups)?

**Comment by luxoflux** [comment]
If you mean `t.co` links not redirecting, it's probably the `<noscript>` issue again. Allow `t.co` and it will redirect properly.

**Comment by Bladtman242** [comment]
It seems to be the "block all popups" option.
But should that matter when uBlock is disabled on the site?

**Comment by gorhill** [comment]
> should that matter when uBlock is disabled on the site?

Good point. Looking at the code, the no-popups switch is the only per-site switch which is not bypassed by the master switch.

**Comment by Bladtman242** [comment]
>Good point. Looking at the code, the no-popups switch is the only per-site switch which is not bypassed by the master switch.

Funny. So how do we proceed from here?
_My_ issue has been resolved, but should I leave the issue/ticket open?
