### ISSUE TITLE
Where is Ublock Origin's configuration stored ?

### ISSUE THREAD

**Issue by uihdff** [gorhill/uBlock#3410]
### Describe the issue
Where is Ublock Origin's configuration stored ?

- OS/version: Windows 10
- Browser/version: Firefox 56.0.2
- uBlock Origin version: uBlock Origin v1.14.18

**Comment by Hrxn** [comment]
In your case:
`C:\Users\<User>\AppData\Roaming\Mozilla\Firefox\Profiles\<profile_id.name>\browser-extension-data\uBlock0@raymondhill.net`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
