### ISSUE TITLE
opera 26.0 and U0

### ISSUE THREAD

**Issue by pah96** [gorhill/uBlock#3411]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

I'm using Opera 26.0.1656.60 and uBlock since 2 years now and it was working perfect till friday. Since yesterday suddenly it doesn't anymore. Tried deaktivation/activation, deinstall and install, nothing changed. Also uMatix suddenly stpped working for me. Only http switchboard is working correctly at this moment.

I'm using this browser/version because it is the only I can use accessing my TLSv3 Admin-WebGui's. 

### One or more specific URLs where the issue occurs

all and especially on https://github.com :-(

### Screenshot in which the issue can be seen

![u01x](https://user-images.githubusercontent.com/29300737/34653026-d417faf4-f3dd-11e7-848f-886ea36c31cd.jpg)

![u2x](https://user-images.githubusercontent.com/29300737/34653029-db05a546-f3dd-11e7-8db3-7369ee019a14.jpg)

![u3x](https://user-images.githubusercontent.com/29300737/34653030-e0b04e38-f3dd-11e7-8dfa-4245fda269ec.jpg)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

Can not say how to reproduce it. Suddenly both extentions stopped working and can not be controlled anyhow.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: W7 Ultimate Service Pack 1
- Browser/version: Opera 26.0.1656.60 
- uBlock Origin version: 1.14.22 <<< stopped working
- uMatrix version: 1.1.20  <<< stopped working 

- HTTP Switchboard version 1.0.1.5   << new, still working

##### Your filter lists

No rules or filters left anymore since extensions stopped working.

##### Your custom filters (if any)

Please help!

Best regards!

pah96

**Comment by mapx-** [comment]
If all those extensions got in trouble could be some corrupt profile in opera

**Comment by gorhill** [comment]
> Opera 26 was released on December 3, 2014, based on Chromium 39. [[source](https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser#Opera_2014)]

You need whatever Opera version is based on Chrome 45 or above, your version is way too old, it was published over 3 years ago.

**Comment by pah96** [comment]
Thank you for reply.

I know it is old but as I wrote it is the last one which supports TLSv3. It is a little bit disappointing that this extension stopps working without any action and curiously just when the last update happend. And I didn't update! And other extentions still working! I'm confused.

But if this is the last point I've to accept. Even I do not like this way to act with users!

Best regards,
pah96

**Comment by pah96** [comment]
Thank you for reply.

I know it is old but as I wrote it is the last one which supports TLSv3.
It is a little bit disappointing that this extension stopps working
without any action and curiously just when the last update happend. And I
didn't update! And other extentions still working! I'm confused.

But if this is the last point I've to accept. Even I do not like this way
to act with users!

Best regards,
pah96


gorhill/uBlock
<reply@reply.github.com>
schreibt:

**Comment by lewisje** [comment]
I think you mean SSLv3, and what sites are you using that still support SSLv3 and do not support TLS?

**Comment by pah96** [comment]
You ae fully right, SSLv3. Older WebUIs like monitorings etc which I use internal. Not@internet :-)

**Comment by lewisje** [comment]
At this point, you might as well install SeaMonkey and dedicate that to legacy monitoring UIs (it's also among the few remaining browsers that supports plugins like Java and Shockwave and is still being updated).

**Comment by pah96** [comment]
wow, that's very nice! thank you for the hint!
I'll try it at the end of the week. Hopefully it'll work so I can come back with a newer opera version and so can use this addons again!
