### ISSUE TITLE
UBlock Origin Disappears from Waterfox 56 after Latest Update

### ISSUE THREAD

**Issue by MarjaE2** [gorhill/uBlock#3412]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

After today's UBlock Origin update, UBlock Origin has disappeared from Waterfox 56. It still appears in Firefox 52. I haven't tested Firefox 56 and need to find acceptable accessibility tools before trying Firefox 57+.

### One or more specific URLs where the issue occurs

The bookmarks toolbar, the customize screen, and sites where ads punch through. It still appears in the list of installed add-ons.

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Use Waterfox 56. (I don't know whether Firefox 56 has the same bug.)
2. Try to use UBlock Origin.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: MacOS Sierra 10.12.6.
- Browser/version: Waterfox 56.0.1.
- uBlock Origin version: 1.14.22 as of January 7th update.

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Default filter lists.

##### Your custom filters (if any)

None. I use some other about:config settings, add-ons, and user styles to try to block flashing/strobing and other animation.

**Comment by MarjaE2** [comment]
Appears again in 56.0.2. Not sure what is going on or why.

**Comment by gorhill** [comment]
I don't support Waterfox specifically, any issue specific to it will have to be fully investigated by whoever experience them.
