### ISSUE TITLE
Rockfile

### ISSUE THREAD

**Issue by giampi75** [gorhill/uBlock#3413]
Rockfile.co
The image says all:
![rockfile](https://user-images.githubusercontent.com/17108055/34662845-d86f794e-f453-11e7-9bbf-588fc2813bfe.jpg)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
