### ISSUE TITLE
Error 'tabContext is null' in tab.js:446

### ISSUE THREAD

**Issue by Loirooriol** [gorhill/uBlock#3417]
### Describe the issue

I saw this error in Firefox's browser console:

```
tabContext is null tab.js:446
	Context.prototype.init moz-extension://18685708-d93c-4335-ab4b-96786b7e1255/js/tab.js:446:9
	Context moz-extension://18685708-d93c-4335-ab4b-96786b7e1255/js/tab.js:442:9
	createContext moz-extension://18685708-d93c-4335-ab4b-96786b7e1255/js/tab.js:463:16
	PageStore.prototype.createContextFromFrameId moz-extension://18685708-d93c-4335-ab4b-96786b7e1255/js/pagestore.js:447:19
	onBeforeRequest moz-extension://18685708-d93c-4335-ab4b-96786b7e1255/js/traffic.js:122:26
	onBeforeRequest moz-extension://18685708-d93c-4335-ab4b-96786b7e1255/js/vapi-webrequest.js:140:16
	apply self-hosted:4198:5
	applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:297:16
	fire resource://gre/modules/ExtensionChild.jsm:833:28
	receiveMessage resource://gre/modules/ExtensionChild.jsm:836:38
	_callHandlers/< resource://gre/modules/MessageChannel.jsm:866:17
	_callHandlers resource://gre/modules/MessageChannel.jsm:865:14
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:940:7
	_handleMessage resource://gre/modules/MessageChannel.jsm:937:24
	_handleMessage self-hosted:950:17
	receiveMessage/< resource://gre/modules/MessageChannel.jsm:210:9
	forEach self-hosted:271:13
	receiveMessage resource://gre/modules/MessageChannel.jsm:203:5
```

Effectively, `lookup(tabId)` is assumed to be an object but can be `null`:

https://github.com/gorhill/uBlock/blob/f53b3e39306a5e050e730f0aacca10aa05e74231/src/js/tab.js#L445-L446

https://github.com/gorhill/uBlock/blob/f53b3e39306a5e050e730f0aacca10aa05e74231/src/js/tab.js#L378-L380

### Your settings

- OS/version: Windows 10 1709
- Browser/version: Firefox Nightly 59
- uBlock Origin version: 1.14.23b15

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
What are the repro steps?

**Comment by Loirooriol** [comment]
I just noticed the error by chance when I was looking at the console for something else. I don't know when it occurred so I don't know the precise steps, sorry. But the source of the error is clear, just checking `tabContext === null` should do the trick.

**Comment by gorhill** [comment]
> the source of the error is clear, just checking `tabContext === null` should do the trick.

Sure, but I am especially interested in the cause. The error tells me that uBO was asked to handle a network request from an unknown tab, that is not normal.
