### ISSUE TITLE
Treating legitimate tabs as popups. 

### ISSUE THREAD

**Issue by oMarethyu** [gorhill/uBlock#3418]
If you choose to block all popups on a site, then select a piece of text and try to google it with the right click drop down, it will treat the new tab as a popup and immediately close it. 

You can easily replicate this by simply enabling all popups blocked, and then selecting some text, right click and select search google. It will open a new tab, then close it.

**Comment by Hrxn** [comment]
Probably a limitation by the browser?

**Comment by gorhill** [comment]
Duplicate of #3282.
