### ISSUE TITLE
Request to add filter list for Iran

### ISSUE THREAD

**Issue by nimasaj** [gorhill/uBlock#3419]
### Request
Adding a new filter list for Iran

### Filter list URL

`https://raw.githubusercontent.com/nimasaj/uBO_Filterlist/master/BLF.txt`

### Note
Is it possible to add aforementioned filter list to regional lists of uBO? It could be added as a list for Iran.
It's more effective than the current list for Iran.
Looking forward to have your comments.

Thanks in advance

**Comment by gorhill** [comment]
There is already a list for Iran, I prefer to stick with the long maintained one.

Even without this, I wouldn't include your list, you have tons of filters which are generic, i.e. not Iran-specific, and a lot of them really are suboptimal (lots of `||ad2`-like filters which are untokenizable).
