### ISSUE TITLE
Blocks streaming service

### ISSUE THREAD

**Issue by vibrasphere** [gorhill/uBlock#342]
Cannot watch Infinite HD stream services at www.dingit.tv on Firefox with uBlock enabled. Disabling it solves the issue.

So I was wondering maybe there's a particular filter/list I need to untick in the settings? But I just want this affect only www.dingit.tv site.

**Comment by CrisBRM** [comment]
uBlock version, browser version, extensions running alongside uBlock, filter lists.
P.S.: [Check the logger](https://github.com/gorhill/uBlock/wiki/The-logger), it lets you know what's being blocked, which list is the culprit, and let's you create exceptions.

**Comment by vibrasphere** [comment]
v0.9.1.0.1-signed doesn't have lists icon.

**Comment by vibrasphere** [comment]
OK, updated to 0.9.5.0, but it still doesn't have that lists icon like it says in that wiki page. Also this dingit.tv website detects uBlock as AdBlock and tells to disable it. Anyway to work this around?

**Comment by vibrasphere** [comment]
OK, my bad, it has it, but it's different style icon.

**Comment by gorhill** [comment]
> dingit.tv website detects uBlock as AdBlock and tells to disable it

I don't maintain filter lists. You will need to report to filter list maintainers.

**Comment by gorhill** [comment]
Also you did not provide a URL for me to use for your test case, I can't afford spending time guessing around what was your test case. Nothing plays even with uBlock disabled.

**Comment by vibrasphere** [comment]
So how do I block http://www.dingit.tv/js/lib/fuckadblock.js

**Comment by gorhill** [comment]
> So how do I block http://www.dingit.tv/js/lib/fuckadblock.js

EasyList blocks this already.

**Comment by vibrasphere** [comment]
It still popups at http://www.dingit.tv/channel/DingItCSGO telling to disable AdBlock which I don't have and only then the stream works if you disable uBlock.

**Comment by gorhill** [comment]
I can't play a single stream on that site even without a blocker, site appears to sabotage itself if you use a blocker, and I do not maintain filter lists.

**Comment by hotdogman** [comment]
The issue also occurs with ABP after updating EasyList. This isn't an issue with uBlock itself, it's a filter list issue.
Report it here: https://forums.lanik.us/
