### ISSUE TITLE
Individual import functionality not working in Android

### ISSUE THREAD

**Issue by Kusresa** [gorhill/uBlock#3421]
### Describe the issue

When doing single full backup then importing it works. When I try to export individual backups (my rules/whitelist) and import them back nothing is changed.

### Steps for anyone to reproduce the issue

1. Export My Rules individual backup
2. Remove some rules from My Rules and save
3. Import My Rules individual backup
4. The whitelist section remains unchanged

### Your settings

- OS/version: Android 7
- Browser/version: Firefox 58
- uBlock Origin version: 1.14.22

##### Your filter lists

Default

**Comment by Kusresa** [comment]
Just restarted the phone and for some reason it now imports properly. So maybe not a bug.

**Comment by gorhill** [comment]
> The whitelist section remains unchanged

I don't understand this step. What "whitelist" section?

**Comment by Kusresa** [comment]
>What "whitelist" section?

I meant the whitelist rules in settings page. But import works now after a phone restart so I think there isn't a bug here.

**Comment by gorhill** [comment]
Could be that the list was pulled from the browser cache.

**Comment by Kusresa** [comment]
I'm not 100% sure but I think the reason import didn't work is because the backup file was no longer on the device even though it was still present in the 'Recent' files list. Either I accidentally cleared the browser cache (which deleted the backup files) or Android automatically deletes files after a certain time/certain number of files have been download but since deleted files still showed up in the 'Recent' files list (which I used to select the backup file) that may be why nothing was imported.
