### ISSUE TITLE
Cosmetic filtering switch doesn't display number of filters in popup UI

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uBlock#3425]
### One or more specific URLs where the issue occurs

http://collider.com/ or any URL where cosmetic filters are present. 

### Screenshot in which the issue can be seen

![](https://i.gyazo.com/810d1636a9ceff281c2b8843a5be1188.png)

### Steps for anyone to reproduce the issue

1. Browse to http://collider.com/ and keep the logger open
2) Open the pop UI and notice cosmetic filtering switch doesn't display the number of cosmetic filters applied even though cosmetic filters are applied as seen in the [logger](https://i.gyazo.com/c0faf159610d0d7d4a0d0046e280a9f3.png)

### Your settings

- OS/version: Win 10
- Browser/version: Chromium 65
- uBlock Origin version: 1.14.23.16

**Comment by uBlock-user** [comment]
@gorhill Just noticed this happen with 1.14.23.16, so could a recent regression

**Comment by uBlock-user** [comment]
If you need another test-case, then - https://www.reddit.com/r/uBlockOrigin/

**Comment by gorhill** [comment]
The fix is simple enough, however I am trying to figure out when I broke this. I am pretty sure very recently it was working, but I can't find what change broke this.

**Comment by gorhill** [comment]
Ok, that is what broke it: <https://github.com/gorhill/uBlock/commit/6cdb20dffea3425b721a4882d67f9370175767d7#diff-d04c15ee6bff6a6269c6aee25a7c7522R397>.
