### ISSUE TITLE
Spectre/Meltdown suggestion

### ISSUE THREAD

**Issue by jugi1** [gorhill/uBlock#3427]
I was wondering can uBlock Origin
add Spectre and Meltdown protection for browsers ?

https://spectreattack.com/
http://xlab.tencent.com/special/spectre/spectre_check.html

**Comment by uBlock-user** [comment]
Only affected browsers are stable versions of Chromium like Chrome/Vivaldi/Opera Stable.

**Comment by gorhill** [comment]
Browsers are best placed for this. As pointed out by @uBlock-user, Firefox 57 is not affected, and neither is Google Chrome 65.
