### ISSUE TITLE
Questionable Content - Comic Images Too Small

### ISSUE THREAD

**Issue by aeridus** [gorhill/uBlock#3429]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Questionable Content is suddenly not loading right as of a few days ago. The comic images are way too small. If I turn off uBlock, it goes back to normal.

### One or more specific URLs where the issue occurs
http://questionablecontent.net/view.php?comic=3654

### Screenshot in which the issue can be seen
![qc_sizebug](https://user-images.githubusercontent.com/357438/34842377-5027833c-f6d9-11e7-9de4-c1e9e3b14494.png)

### Steps for anyone to reproduce the issue
1. Open Vivaldi
2. Go to Questionable Content
3. Watch the comic image get resized to a smaller dimension while the page loads.

### Your settings

- OS/version: Windows 7 64-bit
- Browser/version: Vivaldi 1.13.1008.40
- uBlock Origin version: 1.14.22

##### Your filter lists

uBlock filters​
uBlock filters​ - Badware risks
uBlock filters​ - Privacy
uBlock filters​ - Resource abuse
uBlock filters​ - Unbreak
Adblock Warning Removal List
EasyList
EasyPrivacy
Malware Domain List
Malware domains​
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
AakList

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
