### ISSUE TITLE
Parsing error in style-injection rules starting with '##' (match all urls)

### ISSUE THREAD

**Issue by eladkarako** [gorhill/uBlock#3430]
Used those two style-injection rules:
<pre>
##body:style(overflow:visible !important;)
##html:style(overflow:auto !important; word-break:normal !important; overflow-wrap:break-word !important; word-wrap:break-word !important;)
</pre>

it caused an error to be shown in the console,
I've figured it was a URL parsing-error, so after few tries, 
I've included a single <code>\*</code> character to make the URL less-ambiguous,
and it worked fine:
<pre>
*##body:style(overflow:visible !important;)
*##html:style(overflow:auto !important; word-break:normal !important; overflow-wrap:break-word !important; word-wrap:break-word !important;)
</pre>

This issue only happens with style-injection rules starting with <code>##</code>,
hiding-rules starting with <code>##</code> works fine.

<hr/>

You can replicate it using: 
<ul>
<li>uBlock Origin dev build 1.14.19.4</li>
<li><code>chrome-extension://ialihgfoehhbfbpinglihepgejjbkgcj/dashboard.html#1p-filters.html</code>:
<pre>
##body:style(overflow:visible !important;)
##html:style(overflow:auto !important; word-break:normal !important; overflow-wrap:break-word !important; word-wrap:break-word !important;)
</pre>
(nothing else is required)
</li>
</ul>

<hr/>

here is an error-example (trimmed) <sup><em>(using just those two lists: <a href="https://github.com/eladkarako/hosts/blob/master/build/hosts_adblock_anti_annoyances_hide.txt">1</a>, <a href="https://github.com/eladkarako/hosts/blob/master/build/hosts_adblock_anti_annoyances_style_inject.txt">2</a>)</em></sup>.
<pre>
<strong>Error in event handler for (unknown): SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule </strong>'[__COMMENT^="-- All Ad                            ---"], [adonis-marker], [class*="-ad-"]:not([class*="ytp-video"]), [class*="-adv"], [class*="-banner-ad-"], [class*="ad_icon_popout"], [class*="ad_section"], [class*="ad_text"], [class*="ad_wrapper"], [class*="ad-bottom-"], [class*="ad-container"], [class*="ad-link"], [class*="ad-panel"], [class*="ad-slot"], [class*="ad-unit"], [class*="ad-wrap"], [class*="adbanner"], [class*="adContainer"], [class*="aditize"], [class*="admpu"], [class*="adroll"], [class*="adRoll"], [class*="adrotate"], [class*="ads-ad"], [class*="ads-visurl"], [class*="adsky"], [class*="adslot"], [class*="AdUnit"], [class*="adv-"], [class*="advertisement-"], [class*="adVideo"], [class*="afs_ads"], [class*="azmodal"], [class*="banner__"], [class*="banner"][class*="ad"], [class*="BannerBox"], [class*="cc_banner-wrapper"], [class*="cc_banner"], [class*="dvertisment"], [class*="essb-mobile"], [class*="FloatingAd"], [class*="imagead"], [class*="inner_ad"], [class*="js-dfp-ad"], [class*="overlay-ad"], [class*="removeAd"], [class*="singlead"][class*="container"], [class*="sponsorBottom"], [class*="SponsoredAds"], [class*="supportAds"], [class*="topAds"], [class*="topbar-ad"], [data-ad-client], [data-ad-slot], [data-auto="advertisement"], [data-entrycode*="RemAds"], [data-target*="adkex"], [href*="tkjs.us/"], [id*="-ad-"], [id*="-adv"], [id*="adrotate"], [id*="ads.spot"], [id*="adsens"], [id*="AdTarget"], [id*="advertisement"], [id*="azbounce"], [id*="b-teaser"], [id*="B-TEASER"], [id*="FloatingAd"], [id*="searchAdv"], [id*="topad"], [id*="vPromo"], [id*="vspopup"], [id^="ad_"], [id^="ad_inters"], [id^="ad-link"], [id^="ad-slot-"], [id^="ad-unit"], [id^="AdBar"], [id^="AdFragment"], [id^="aditize"], [id$="adunit"], a[onclick*="expand_ad"], div.banner[onclick*="unc"], div.purchad.footban, div.wpcnt div.wpa, div[class*="footer-ad"], section[id*="-ad-sec1"],
[__COMMENT^="-- All Ad - EVENT                    ---"], [onclick*="adunit"],
[__COMMENT^="-- All Ad - HREF                     ---"], [href*="/ads"], [href*="aditize.com"], [href*="adurl"], [href*="advert"], [href*="advertisements.com"], [href*="revcontent.com"], [href*="rotator.offpageads.com"], [href*="wpbblogad"], a[href$="#advertising"],
body:style(overflow:visible !important;),
html:style(overflow:auto !important; word-break:normal !important; overflow-wrap:break-word !important; word-wrap:break-word !important;)
{display:none!important;}'.
<strong>
    at Object.add (chrome-extension://ialihgfoehhbfbpinglihepgejjbkgcj/js/contentscript.js:54:15)
    at domFilterer.addCSSRule (chrome-extension://ialihgfoehhbfbpinglihepgejjbkgcj/js/contentscript.js:223:29)
    at bootstrapPhase1 (chrome-extension://ialihgfoehhbfbpinglihepgejjbkgcj/js/contentscript.js:1867:25)
    at Object.messageListener (chrome-extension://ialihgfoehhbfbpinglihepgejjbkgcj/js/vapi-client.js:112:17)
</strong>
</pre>

**Comment by eladkarako** [comment]
https://github.com/gorhill/uBlock/issues/3375 related?

**Comment by gorhill** [comment]
Generic `:style(...)` filters are not allowed, they must be specific. This was caught fine before, so this is a regression from refactoring in the current pre-release version.

Fix is to catch the invalid filter and report the error in the logger.
