### ISSUE TITLE
Reload button has no tooltip 

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#3431]
### Describe the issue
1. Can you add a tooltip to reload button? It wasn't necessary up until ability to bypass cache has been added. All other clickable elements in popup have tooltips.
2. There's no description of reload button in [popup-user-interface wiki](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface)

### Steps for anyone to reproduce the issue

1. Toggle toggle cosmetic filtering switch in popup
1. Reload button appears, which has no tooltip

### Your settings
- OS/version: Windows 10 x64 v1607
- Browser/version: Google Chrome 64.0.3282.85 (Official Build) beta (64-bit)
- uBlock Origin version: 1.14.23.100

**Comment by Thorin-Oakenpants** [comment]
Also, the reload icon status loses it's "sync" if you "lose" the panel (eg temporarily flicking to another tab to check something, eg the logger or settings - or deliberately dismissing it) - meanwhile, the eraser & lock icons stay in sync

Should the display of the reload be based on the logic for the eraser/padlock (temporary changes)?

**Comment by gorhill** [comment]
> Should the display of the reload be based on the logic for the eraser/padlock (temporary changes)?

No, the reload button depends on whether ruleset changes have been made *after* the page loaded. The padlock.eraser depends on whether there are temporary, unsaved rules.

In any case, declining original issue.
