### ISSUE TITLE
Crunchyroll advertisments back

### ISSUE THREAD

**Issue by SylveonBottle** [gorhill/uBlock#3432]
### Describe the issue

First advertisement ends after 1 second with just a black screen. A second one appears for 30 seconds, related to either Crunchyroll/VRV or a new anime. 

After refreshing the page constantly, the 9th and 10th time resulted in no ads being shown, further refreshing showed the same before-video ad.

### One or more specific URLs where the issue occurs

http://www.crunchyroll.com/overlord/episode-13-player-vs-non-player-character-736661

### Screenshot in which the issue can be seen

https://i.imgur.com/xjaylsq.png
10 second gif: https://i.imgur.com/z3kR2Bb.gifv

### Steps for anyone to reproduce the issue

1. Open web page above
2. Video will auto-start with ad before the actual anime (Overlord, in this case) shows.

### Your settings

https://i.imgur.com/xM7YogM.png

- **OS/version:** Windows 10 Version 1709 (OS Build 16299. 192)
- **Browser/version:** Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- **uBlock Origin version:** uBlock Origin 1.14.22

##### Your filter lists

Everything except Experimental and other languages.

##### Your custom filters (if any)

`! http://www.crunchyroll.com/
www.crunchyroll.com##.premium
www.crunchyroll.com###ecom_deal_img_div
www.crunchyroll.com##.large-margin-bottom:nth-of-type(1)
www.crunchyroll.com###showmedia_about_info_details > div:nth-of-type(3)
||static.ak.crunchyroll.com/i/star*$image
www.crunchyroll.com##.clearfix.right
www.crunchyroll.com##.small-margin-bottom.container-shadow.cf.white-wrapper.showmedia-submenu
www.crunchyroll.com##.footer-categories-container > .footer-column:nth-of-type(3)
`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
