### ISSUE TITLE
filter not being applied because of $webrtc

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#3433]
### Describe the issue

The recent commit; https://github.com/easylist/easylist/commit/3f6789582d4ca6b22c351dbc443e74efd3e3b7df isn't working in uBo. I believe its related to the webrtc filter.

### One or more specific URLs where the issue occurs

https://github.com/hoshsadiq/adblock-nocoin-list/issues/94
https://forums.lanik.us/viewtopic.php?p=130417#p130417

### Steps for anyone to reproduce the issue

The following filter isn't being applied properly.

    $script,stylesheet,subdocument,third-party,webrtc,websocket,xmlhttprequest,domain=estream.to

The moment I remove $webrtc filter, the filter will work fine.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  Windows 10
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.14.22

##### Your filter lists

Easylist

**Comment by ryanbr** [comment]
I've removed the webrtc switch for the moment, https://github.com/easylist/easylist/commit/d1eb11fb5c93465f6d81f3d3e9761d7434ee72cf  Surprised that this is a thing. Can't imagine all the other webrtc filters not being applied

```
fanboy@host:~/git/easylist/easylist$ grep -r webrtc *.txt | wc -l
132
```

**Comment by gorhill** [comment]
> Can't imagine all the other webrtc filters not being applied

This requires to unconditionally creating a wrapper for all WebRTC stuff content script-side, so it's quite invasive, and if the wrapper breaks something legitimate, the only workaround is to disable completely the whole extension (whitelisting is not sufficient).

There has been some actions lately on CSP working group to address the [issue of WebRTC not being covered by CSP](https://github.com/w3c/webappsec-csp/issues/92#issuecomment-357371357), so as soon as browsers start to support this, I will make use of it.

For now uBO uses script injection to disable WebRTC.
