### ISSUE TITLE
Add stylesheets to filtering

### ISSUE THREAD

**Issue by marak8** [gorhill/uBlock#3434]
I'm using UBO in hard mode. I block `all` globally but allow `images` globally. For sites I _trust_ (GitHub), I set `noop` in `all` locally. This is easy and non-intrusive. But I'd still like to load external stylesheets alongside images on sites I do not _trust_. UBO in Advanced Mode should allow user to load both `images` and `stylesheets` as they are not that harmful (you can just include stylesheet inline and circumvent the block logic). uMatrix is too complex for my needs.

It doesn't have to be in the filtering GUI. Since I only need to specify it for all sites, I can just write it in rules. But according to [1], I cannot explicitly allow external stylesheets.

[1] https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

**Comment by gorhill** [comment]
Hard mode is to block all 3rd parties. That would be wrong to allow 3rd-party images/stylesheets when a rule to block all 3rd parties is in effect. Just use medium mode.

**Comment by marak8** [comment]
Well, I want to block all JS regardless of the party. But I want to be able to load CSS and images from 1st party. How am I supposed to do that?

**Comment by gorhill** [comment]
Don't use hard mode, just block inline, 1st- and 3rd-party javascript.

**Comment by uBlock-user** [comment]
> Well, I want to block all JS regardless of the party. But I want to be able to load CSS and images from 1st party.

Your desire for that specific behavior reminds me of uMatrix. It's perfect for you.

**Comment by marak8** [comment]
uBlock is nice, uncluttered, easy. For my desire I added NoScript. This way uBlock handles filters and NoScript my desire to block all JS by default.

**Comment by gorhill** [comment]
@marak8 Ok so what you really want is #3436.

**Comment by marak8** [comment]
Well, depends. It really seems inconsistent a bit that you're allowed to block images but stylesheets fall into `all` category. When you block images, does uBlock also block images in stylesheets (background)? Though I agree that #3436 is what I wanted.

**Comment by gorhill** [comment]
> you're allowed to block images

Rationale was to save bandwidth. I actually would like to remove it since when I added the ability to block images blocked by size.
