### ISSUE TITLE
Minor usability issue: block all scripts

### ISSUE THREAD

**Issue by tomtom** [gorhill/uBlock#3436]
uBlock currently offers four general (medium mode) buttons to disable scripts: (1) inline scripts, (2) current page, (3) third party.

Let's assume some users usually want to disable scripts but want to whitelist some domains. They would have to gray out all three options. This is cumbersome.

IMHO it would be preferable if there were another option: (4) "all scripts" that comprises inline, current page & third-party scripts.

**Comment by gorhill** [comment]
For translators:

![a](https://user-images.githubusercontent.com/585534/44939163-22a51300-ad51-11e8-9c59-bae982f17337.png)

![a](https://user-images.githubusercontent.com/585534/44939176-318bc580-ad51-11e8-87d2-9a58a5239f05.png)

**Comment by happysurf** [comment]
Will be great have also in Default behavior >**Block popup** for the users that want then allow per site.
