### ISSUE TITLE
ebay captcha image is blocked

### ISSUE THREAD

**Issue by bdqp** [gorhill/uBlock#3437]
When sending a message via "Contact seller" button in eBay, the capture image is blocked. Disabling uBlock Origin permits the image to show. This is on FF Quantum but it has been an issue since before then.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
