### ISSUE TITLE
alltube.pl - bad rule

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#3439]
### Describe the issue
This rule `*$third-party,subdocument,domain=alltube.tv` block content like Google Recaptcha and players

### One or more specific URLs where the issue occurs

http://alltube.tv/film/3d-mala-wielka-stopa-the-son-of-bigfoot-2017/59226

### Screenshot in which the issue can be seen

https://www.screencast.com/t/H0xX3kgxF

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: win10
- Browser/version: FF 57
- uBlock Origin version: 1.4.24

##### Your filter lists

uBlock Origin -- Resource-abuse filters

**Comment by mapx-** [comment]
it was already removed yesterday, update your lists
https://github.com/uBlockOrigin/uAssets/commit/853634d0c9a2cf9c8f510df921f44f3d38a1ec95

**Comment by MajkiIT** [comment]
Ok, thanks . I think that better rule is `/(http|https):\/\/[a-z0-9.]{5,20}\.[a-z]{2,10}\/$/$subdocument,domain=alltube.tv`
