### ISSUE TITLE
Custom lists don't retain their state after a restore

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#344]
A simple test case is to add some custom lists, disable some of them, and do a backup.
Upon restoring, **ALL** the custom lists got downloaded and enabled, which should obviously not happen.

This is always reproduceable on uBlock 9.8.6, all browsers.

**Comment by Alpengreis** [comment]
This needs really a fix ... it's bad if an import is not really an import ... I have still the problem with unticked Experimental Filter list after import the exported setting.

**Comment by gorhill** [comment]
Fixed with 3b9fd49c508812dfe2545836c63bd5d8cfd2ead4.
