### ISSUE TITLE
Bluejeans teleconferencing doesn't work (whitelisting has no effect on "prevent WebRTC leaking IP" setting)

### ISSUE THREAD

**Issue by yarda** [gorhill/uBlock#3440]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Bluejeans teleconferencing (http://bluejeans.com) doesn't work with the default settings. When clicking "Disable ublock for this site" it adds bluejeans.com to the whitelist, but the option " Prevent WebRTC from leaking local IP address" is still enabled for the site which causes the app to behave very weirdly and the voice communication not to work. I had to manually set this option globally to 'off' or disable ublock completely otherwise the bluejeans doesn't work.

### One or more specific URLs where the issue occurs
http://bluejeans.com

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Start teleconferencing through the bluejeans WebRTC

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Fedora 26, x86_64
- Browser/version: Firefox 57.0.4
- uBlock Origin version: v1.14.24

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Default filter lists

**Comment by gorhill** [comment]
> Bluejeans teleconferencing (http://bluejeans.com) doesn't work with the default settings

> it adds bluejeans.com to the whitelist, but the option " Prevent WebRTC from leaking local IP address" is still enabled

"Prevent WebRTC from leaking local IP address" is not enabled by default.

It's a global setting, it cannot be disabled by whitelisting.
