### ISSUE TITLE
Not all images blocked 'Block media elements larger than' set to 0kb

### ISSUE THREAD

**Issue by BigNickBurgess** [gorhill/uBlock#3441]
Change the settings 'Block media elements larger than' set to 0kb. No images show generally.

Then go to

https://www.androidauthority.com/best-android-phones-568001/ 
or 
http://www.bbc.co.uk/news

### Screenshot in which the issue can be seen

![example images](https://user-images.githubusercontent.com/31211392/34985733-032aa730-faad-11e7-85f1-4a0dd913e356.jpg)

### Steps for anyone to reproduce the issue

1. Change setting in uBlock origin to Block media elements larger than 0kb
2. Go to https://www.androidauthority.com/best-android-phones-568001/ or http://www.bbc.co.uk/news
3. See images loaded

### Your settings
userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": true,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 0,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": true
  }

- OS/version: Windows 10 Enterprise Version 1703 Build 15063.674
- Browser/version: Firefox 57.0.4 64 Bit
- uBlock Origin version: 1.14.24

##### Your filter lists

"selectedFilterLists": [
    "plowe-0",
    "disconnect-malware",
    "malware-1",
    "malware-0",
    "disconnect-malvertising",
    "easyprivacy",
    "adguard-spyware",
    "easylist",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "user-filters"
  ]

##### Your custom filters (if any)

Nothing in 'My Filters'

**Comment by gorhill** [comment]
I can reproduce on FF57, but not on Chromium.

**Comment by uBlock-user** [comment]
@gorhill Every image which is blocked appears twice in the logger, is that on purpose ?

![](https://i.gyazo.com/b84a301dde24353874a033fdb61f7f39.png)

**Comment by gorhill** [comment]
It's normal. The images are first seen but not blocked by onBeforeRequest handler, and reported as such in the logger -- so you know that a connection to the remote server occurred.

Then they are blocked once uBO receives the response headers, and reported as such in the logger. It's impossible to block image by size in the onBeforeRequest handler, uBO needs the response headers.

**Comment by uBlock-user** [comment]
Doesn't happen with fonts when I use `Block remote fonts`, they only appear once, so it's specific to images only ?

**Comment by gorhill** [comment]
Fonts can be blocked by onBeforeRequest handler, no need to connect to remote server because no need for response headers.

**Comment by uBlock-user** [comment]
Another question, checking for size wouldn't be needed if I set the size to 0 kB or is it ?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues/1473#issuecomment-259244428
