### ISSUE TITLE
Version Number Inconsistency

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#3442]
I just noticed this morning that after the `1.14.25rc0` the version changed to `1.14.23rc1` and was wondering if this was an intentional decision to refactor the versioning or just a typo before upgrading to this version. Thanks.

**Comment by GuardianMajor** [comment]
A quick update, white the github page shows .23rc1, Firefox's update page shows .25rc1 so it might have been corrected already and just not reflecting, not sure, thought I share the extra info in case. While we are at it, after updating to it, the app itself shows the .25rc1 version so it seems just a disconnect and probably not an issue.

![version-github](https://user-images.githubusercontent.com/5274181/34999659-292786e4-fa97-11e7-89ca-c99ccc397835.png)
![version-firefox](https://user-images.githubusercontent.com/5274181/34999669-2ef1661c-fa97-11e7-8c57-6de756f4b0a9.png)
![version-ublock](https://user-images.githubusercontent.com/5274181/34999800-8e115738-fa97-11e7-9520-1155c2851824.png)

**Comment by gorhill** [comment]
Fixed.

**Comment by GuardianMajor** [comment]
Thank you.
