### ISSUE TITLE
uBlock be able to detect and block "suspicius" addresses in extensions (Google Analytics, spam, big data...)

### ISSUE THREAD

**Issue by timofonic** [gorhill/uBlock#3443]
NOTE: I'm not sure if this is a filter issue or an "addon" issue. I just want to know if uBlock Origin can filter spammy/privacy-endangering stuff from extensions.

Hello.

I would like to know if uBlock Origin can detect and offer to block "suspicious" stuff in extensions. I would like to choose between uninstall/not install it or block that stuff. 

An inspector of URLs and able to easily report them would be a nice plus, even more if there's some collaboration with Mozilla. But I'm a little uncomfortable when I installed the "Notes" "Experiment", as I was briefly some stuff about a SSL... Google Analytics URL. 

Trackers are one of the zillion of ways of Internet to break privacy, it's a shame Mozilla uses them.

### One or more specific ~~URLs~~ extensions where the issue occurs

* [Mozilla Testpilot - Notes Experiment](https://testpilot.firefox.com/experiments/notes): It uses Google Analytics!

### ~~~Screenshot~~~ JavaScript code in which the issue can be seen at "notes@mozilla.com.xpi" file

Lines 1 to 5 of background.js:
```javascript
/* exported sendMetrics */
/**
 * Google Analytics / TestPilot Metrics
 */
const TRACKING_ID = 'UA-35433268-79';
```
### My settings

- OS/version: Windows Server 2016
- Browser/version: Firefox Nightly 
- uBlock Origin version: 1.14.24

##### My config 
* I has been OCD and added too many filters. It's easier to put the [exported config file here](https://gist.github.com/timofonic/d8ac1660cfe4ef6e0131cefe6098fbc2).

**Comment by gorhill** [comment]
> I just want to know if uBlock Origin can filter spammy/privacy-endangering stuff from extensions.

No.

Any future questions please use [reddit](https://www.reddit.com/r/uBlockOrigin/) as stated [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
