### ISSUE TITLE
[sharing some info] Detecting Adblocker Blockers

### ISSUE THREAD

**Issue by t33rex** [gorhill/uBlock#3445]
Perhaps worth reading in case it may improve uBO:

https://www.schneier.com/blog/archives/2018/01/detecting_adblo.html

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://news.ycombinator.com/item?id=16027449

**Comment by uBlock-user** [comment]
More like detecting Easylist filters, they don't have any heuristic way of detecting it, so they resolve to use easylist baits.
