### ISSUE TITLE
Minor annoyance: #top href links don't display

### ISSUE THREAD

**Issue by Fasmea** [gorhill/uBlock#3446]
### Describe the issue
Anything with "a[href="#top"]" gets hidden. Inconvenient when using sites that actually make good use of it. 
Found in: https://hastebin.com/jerowadacu, so I assume it is caused by a filter list.

### One or more specific URLs where the issue occurs
https://boards.4chan.org/o/thread/16832611

### Screenshot in which the issue can be seen
![screenshot_20180117_202347](https://user-images.githubusercontent.com/14368931/35062364-5c63f91a-fbc4-11e7-98e3-a9fb50e14c1e.png)

### Steps for anyone to reproduce the issue
Navigate to an imageboard of your choice and enter a thread. The top navlinks are displayed normally, while the ones on the bottom now lack the link for "[Top]". Disabling uBlock Origin (or using different filters?) seems to fix the problem but that's not a solution.

### Your settings
![screenshot_20180117_202848](https://user-images.githubusercontent.com/14368931/35062599-0ed2d788-fbc5-11e7-97c7-cee687f794d8.png)

- OS/version: Windows 10
- Browser/version: Chromium 63
- uBlock Origin version: 1.14.24

##### Your filter lists
My filters, uBlock filters, uBlock filters – Badware risks, uBlock filters – Privacy, uBlock filters – Resource abuse, uBlock filters – Unbreak, Adblock Warning Removal List, Adguard Base Filters, EasyList, Adguard Spyware Filters, EasyPrivacy, Fanboy’s Enhanced Tracking List, Malvertising filter list by Disconnect, Malware Domain List​​​​​, Malware domains, Spam404, Fanboy’s Annoyance List, Fanboy’s Social Blocking List​, Dan Pollock’s hosts file, Peter Lowe’s Ad and tracking server list​, Fanboy+Easylist-Merged Ultimate List, Malware domains (long-lived), uBlock Protector List

##### Your custom filters (if any)
@@||4chan.org^$domain=4chan.org
@@||4cdn.org^$domain=4chan.org
@@*/_/api/chan/*$domain=4chan.org
@@||googleapis.com^$domain=4chan.org
@@||twitter.com^$domain=4chan.org
@@||github.io^$domain=4chan.org
@@||4chan.org^$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'
*$inline-script,domain=4chan.org
*$third-party,script,domain=4chan.org
*$third-party,xmlhttprequest,domain=4chan.org
*$third-party,websocket,domain=4chan.org

4chan.org##script:inject(abort-current-inline-script.js, String.fromCharCode)*.mgid.com

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> `4chan.org##script:inject(abort-current-inline-script.js, String.fromCharCode)*.mgid.com`

That is an invalid filter by the way.

**Comment by Fasmea** [comment]
Pardon, I didn't read properly. Sorry.
