### ISSUE TITLE
Page refresh required before filtering works

### ISSUE THREAD

**Issue by shapiro125** [gorhill/uBlock#3447]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Every so often, a page will load on Firefox 57 but appear to only block some requests -- as if cosmetic filtering isn't being loaded properly. Refreshing the page fixes the issues. On Chrome, this problem does not appear to be an issue.

### One or more specific URLs where the issue occurs

Example page used in screenshot: https://lifehacker.com/you-don-t-have-to-pay-to-check-a-bag-1822172991

This has occurred on other sites as well, such as Reddit.

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

The best way to see this happen is to use a news reader/RSS feed, such as Feedly. When links are opened in the background in new tabs, this occurs much of the time.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: MacOS 10.13.2
- Browser/version: Firefox 57.0.4
- uBlock Origin version: 1.14.24

##### Your filter lists

uBlock filters​​​​​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
​​uBlock filters – Resource abuse​​​​​
​​uBlock filters – Unbreak
    ​​ 
Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters
EasyPrivacy
Fanboy’s Enhanced Tracking List​

Malvertising filter list by Disconnect​​​​​
Malware Domain List​​​​​
Malware domains
Spam404​

Adguard’s Annoyance List
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social

Dan Pollock’s hosts file​​​​​
hpHosts’ Ad and tracking servers​
MVPS HOSTS​
Peter Lowe’s Ad and tracking server list​

##### Your custom filters (if any)

gizmodo.com##._3fuZ4Zij-D
lifehacker.com##._3fuZ4Zij-D
jezebel.com##._3fuZ4Zij-D

<img width="1552" alt="screen shot 2018-01-18 at 9 45 21 am" src="https://user-images.githubusercontent.com/7659910/35103950-6c4fb2b2-fc35-11e7-9f61-93a7ecd24eaf.png">
<img width="1552" alt="screen shot 2018-01-18 at 9 45 28 am" src="https://user-images.githubusercontent.com/7659910/35103952-6ca1386c-fc35-11e7-9d9f-54502cb1d1af.png">

**Comment by gorhill** [comment]
Does this happen when you launch the browser?

**Comment by shapiro125** [comment]
No, this happens even after the browser is open for awhile. I do have `suspendTabsUntilReady` set to false, but could try changing it.

The best way I have of reproducing is as follows (and it occurs almost every time I use this method).

Open Feedly to gather RSS feeds
Use control click to open a series of tabs in background
When viewing each individual tab, experience cosmetic (or other blocking) issue
Refresh tab, filtering works perfectly

**Comment by gorhill** [comment]
What is "Feedly"? Does this require an account? Does this require configuration? If so, what would it be?

**Comment by gorhill** [comment]
Also, do you have other extensions? If so, did you try without these? Do you have custom about:config settings? If so, which ones?

**Comment by shapiro125** [comment]
Ah, apologies -- it's an RSS reader. https://feedly.com/

I do have other extensions, but no custom about:config settings. I will try
turning them on and off.

**Comment by shapiro125** [comment]
Disabling other extensions doesn't solve the issue. It seems to be an issue on Firefox when opening tabs in the background. Not affected in Chrome.

**Comment by gorhill** [comment]
I am not able to reproduce with reddit pages so far.

I am able to reproduce with lifehacker pages. Currently I suspect the issue lies with the lifehacker site, i.e. there is javascript code in there which executes according to the visibility of the page.

**Comment by gorhill** [comment]
I am going to blame the web site until proof to the contrary. Try this:

- Open `https://lifehacker.com/either-your-sick-co-worker-goes-home-or-you-do-1822172740`.
- Open the logger, and be sure the selector is at the top of the logger is for that page.
- Activate another tab
- Force a refresh of the lifehacker page using the logger's refresh button
    - This will force a reload of the page while it's not active and visible
- Wait for the lifehacker page to reload, as per logger
- Switch to the lifehacker page

Result:

Same visual issues as you reported in comment #0.

The site most certainly executes javascript conditionally to portion of the page being visible.

Further confirmation:

- Disable uBO
- Restart the browser, just to be sure no remnant of uBO or any other extension in memory.
- Repeat repro steps
    - Be sure to wait for the opened page to fully load before switching to it

Result:

Same visual issues as you reported in comment #0.

Note: since the page takes longer to load now (due to all 3rd-party being freely allowed in), it may take a couple of reload before the issue is seen. I can see it all the time when the page finish to reload fast before switching to it.

**Comment by shapiro125** [comment]
Interesting, yes -- that definitely reproduces the issue. Do you have any idea why this happens in Firefox and not Chrome? I'm wondering if it's also partially a Firefox bug somewhere.

**Comment by gorhill** [comment]
> Do you have any idea why this happens in Firefox and not Chrome?

No clue, I would have to investigate the site's code. I rather have their own developers look at this.

**Comment by Matthewus** [comment]
This happens to me too on reddit.com and soompi.com.
- I open Firefox in private mode
- open some pages then close them (none of them are reddit)
- then i open a bunch of links at once, reddit pages are on background tabs
- for cosmetic filtering to apply on reddit, i have to refresh the pages.
