### ISSUE TITLE
1.14.25rc1 (maybe rc0) site compression error

### ISSUE THREAD

**Issue by BzfpWg9g** [gorhill/uBlock#3448]
### Describe the issue

Occasionally I got errors when surfing some webpages on Waterfox 56,0,3: "**The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression**."

After reloading Site with F5 it usually worked. Trying to change Firwall/Antivir-Settings/network.http.accept-encoding-settings, etc with no change. Finally tried to go back to uBlock origin 1.14.24 and the error were gone.

### One or more specific URLs where the issue occurs

Tried with https://twitter.com because the error messages were reproducible best.

### Screenshot in which the issue can be seen

Standard error page: See http://1.bp.blogspot.com/-RkOJfqRmp4A/UNOHlErnmyI/AAAAAAAAAHo/FtXK_ueDKQc/s640/compression-error.gif as an example

### Steps for anyone to reproduce the issue

1. https://twitter.com 
2. Go to random twitter profile
3. hit Ctrl+F5 till error page appears (~4-5 clicks in my case)

### Your settings

- OS/version: Windows 7 rof
- Browser/version: Waterfox 56,0,3
- uBlock Origin version: 1.14.25rc1

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
There is no support for Waterfox, report issue only for supported browsers.
