### ISSUE TITLE
The element picker window is almost invisible

### ISSUE THREAD

**Issue by stanlane** [gorhill/uBlock#3449]
### Describe the issue
The element picker window is to hard to detect (I thought it was broken) after an element has been Picked. 

### One or more specific URLs where the issue occurs
Any URL.

### Screenshot in which the issue can be seen
![screenshot from 2018-01-20 04 14 40](https://user-images.githubusercontent.com/25944158/35179336-a6a5e008-fd98-11e7-9d94-996675873f00.png)

### Steps for anyone to reproduce the issue
* Open the Element picker
* Pick an element
* The Element picker window will popup, but its almost invisible.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: GNU/Linux
- Browser/version: Firefox 57.0.4
- uBlock Origin version: 1.1.4.24

##### Your filter lists

Default

**Comment by Thorin-Oakenpants** [comment]
move your mouse into/over the picker-section (bottom right), it then becomes the focus and lights up like a xmas tree

**Comment by stonecrusher** [comment]
Indeed as I first used it, it also left me a bit baffled what to do next. I suggest adding an opaque border to the uBO overlay. That way it won't disturb the view to the underlaying website but still indicates something has happened.
When you choose an element, the red box freezes but leaves you without response so one thinks it's broken. Bad user experience.

**Comment by shevegen** [comment]
I think the problem is how other people may use ublock origin. I assume quite many like the way it is.

The way how I personally use it is to just click on "pick", and manually select which element I want to get out of my sight. It is admittedy at the least one click more, but I don't really mind it.

**Comment by gorhill** [comment]
I implemented a slow fade-out of the dialog when no hovering over it.
