### ISSUE TITLE
Zapper/Picker Not Working On Website

### ISSUE THREAD

**Issue by bytos** [gorhill/uBlock#3453]
On MPC-HC's website the zapper and picker don't work as expected.

[https://mpc-hc.org/](url)

![s](https://user-images.githubusercontent.com/16452541/35194031-77088d74-fe82-11e7-9e7c-041a354929be.png)

Firefox 57.0.4
Windows 8.1
uBlock Origin 1.14.24
Default filter lists

**Comment by gorhill** [comment]
Duplicate of #2240.
