### ISSUE TITLE
Disable uBlock for a domain in a filter list

### ISSUE THREAD

**Issue by sdtbluethink** [gorhill/uBlock#3454]
Hello,

I'm using my own adblock list with my own filters and exceptions. 

On some pages I have deactivated the ad blocker. 
Example: @@calendar.google.com$document

Unfortunately, it doesn't work with uBlock.
It would be great to allow exceptions in filter lists.

Best

**Comment by mapx-** [comment]
You can use the dynamic filtering or the `badfilter` option

read here:
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#not-supported
