### ISSUE TITLE
When Going To a Blocked Site the "Do You Want To Continue Page?" Show's '(I.e.' Instead of Exclamation Point Icon

### ISSUE THREAD

**Issue by Bj007pro** [gorhill/uBlock#3455]
### Describe the issue

Showing  '(I.e.' instead of the normal icon.
Happens when going to ads.com and haven't been able to reproduce this by trying 5 other blocked sites. 

### One or more specific URLs where the issue occurs

`http://ads.com`

[Screenshot(s) for visual issues are **mandatory**]

https://i.imgur.com/a2i0fXu.png

### Steps for anyone to reproduce the issue

1. Go to Ads.com with uBlock Origin on.
2. Once uBlock Origin has kicked in and blocked the site.
3. The icon should have changed to "(I.e"

### Your settings

https://i.imgur.com/7lFDSt4.png
https://i.imgur.com/S2qOUNj.png
https://i.imgur.com/Wzkjryp.png
https://i.imgur.com/eMPc7FF.png
https://i.imgur.com/iosnKrg.png

Versions:

- OS/version: Windows 10
 
- uBlock Origin version: 1.14.24

##### Your filter lists

I've kept everything default. The only changes I've done/added are on my Custom Filter list.

##### Your custom filters (if any)

[https://pastebin.com/DDNiaTWP](url)

**Comment by shevegen** [comment]
Your first link at https://i.imgur.com/a2i0fXu.png does not work; it redirects to https://github.com/gorhill/uBlock/issues/url instead. (Just mentioning it, sorry.)

**Comment by gorhill** [comment]
> - Browser/version: 

Why did you leave that out?

In any case, I can't reproduce, you will have to investigate the cause on your side.
