### ISSUE TITLE
Links clicked in GMail that open in new tab instantly closed

### ISSUE THREAD

**Issue by sgmiller** [gorhill/uBlock#3457]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Recently, when clicking on links in GMail, which typically open in a new tab, uBlock is immediately closing them, as it correctly does for Ad popups.  Possibly some change on the Google side.

### One or more specific URLs where the issue occurs

https://gmail.com

[URL(s) for issue on a specific site are **mandatory**]

### Steps for anyone to reproduce the issue

1. Visit an email in GMail with an embedded link.
2. Click the link.
3. Observe the new tab created and then closed a fraction of a second later.

### Your settings

- OS/version: Ubuntu 17.10
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.24

##### Your filter lists

Default filter lists + EasyList & EasyPrivacy.

##### Your custom filters (if any)

None

**Comment by sgmiller** [comment]
I should add that disabling uBlock fixes the issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sgmiller** [comment]
Yep, thanks.

**Comment by mapx-** [comment]
filter issue, see here (already fixed in easylist)
https://forums.lanik.us/viewtopic.php?f=64&t=39742
