### ISSUE TITLE
Seamonkey Cannot download from addon site

### ISSUE THREAD

**Issue by Arckonicon** [gorhill/uBlock#3459]
when trying to download ublock from the addon section of seamonky. you are now greeted with a button that says it is for firefox only. and there is no option to download anyway. it forces you to go to a firefox download site. figured you would want to know it is broken for us who prefer seamonkey.

**Comment by cy7yz2rj** [comment]
Install the legacy version from this repo.

https://github.com/gorhill/uBlock/tree/master/dist#firefox-legacy

https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions
