### ISSUE TITLE
Timing of script:inject() in Safari and Chrome

### ISSUE THREAD

**Issue by mun35** [gorhill/uBlock#3460]
### Describe the issue

I'm using script:inject to 'hijack' an anti-adblock function but it works only intermittently on Safari. It works fine on Chrome. My suspicion is that on Safari, the property assignment may occur too early, allowing the property to be reassigned when the script loads.

Is there a difference in injection timing between Chrome and Safari versions?

### One or more specific URLs where the issue occurs

Just as a quick example:

https://jsfiddle.net/

### Screenshot in which the issue can be seen

Chrome:
![screen shot 2018-01-25 at 1 33 57 pm](https://user-images.githubusercontent.com/1611736/35369654-b6a9150c-01d4-11e8-8829-a5a62b8cf6fb.png)

Safari:
![screen shot 2018-01-25 at 1 34 34 pm](https://user-images.githubusercontent.com/1611736/35369657-bb555098-01d4-11e8-8d84-e9c6f09a866a.png)

### Steps for anyone to reproduce the issue

1. Add filter:

`jsfiddle.net##script:inject(set-constant.js, _carbonads_go, trueFunc)` in Chrome and Safari

2. Go to https://jsfiddle.net/

Run `_carbonads_go` in both consoles.

3. Chrome shows the new definition `ƒ (){ return true; }` whilst Safari shows original definition.

### Your settings

- OS/version: OSX 10.12.6
- Browser/version: Safari 11.0.2, Chrome 63.0
- uBlock Origin version: uBlock Origin v1.14.14 (Safari), uBlock Origin v1.14.24 (Chrome)

**Comment by uBlock-user** [comment]
Probably a Safari issue, submit on the safari repo.

**Comment by gorhill** [comment]
This is not the place for Safari issue. Go there please: <https://github.com/el1t/uBlock-Safari/issues>.

Also, yes, `script:inject` is susceptible to race conditions, and this is browser specific.
