### ISSUE TITLE
Network filter not working

### ISSUE THREAD

**Issue by mun35** [gorhill/uBlock#3461]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Custom network filter does not block images.

### One or more specific URLs where the issue occurs

https://www.reddit.com/r/uBlockOrigin/

### Screenshot in which the issue can be seen

Expected result:

![screen shot 2018-01-25 at 10 33 29 pm](https://user-images.githubusercontent.com/1611736/35388627-431c0242-0220-11e8-9589-944bbe229674.png)

Actual result:

![screen shot 2018-01-25 at 10 34 41 pm](https://user-images.githubusercontent.com/1611736/35388543-f861c39a-021f-11e8-81e4-632a074f9ebf.png)

### Steps for anyone to reproduce the issue

1. Go to https://www.reddit.com/r/uBlockOrigin/

- OS/version: OSX 10.12.6
- Browser/version: Chrome 64.0
- uBlock Origin version: v1.14.24

##### Your custom filters (if any)

`||b.thumbs.redditmedia.com/*.*$image`

**Comment by mapx-** [comment]
your filter is working fine for me

try also:
`||b.thumbs.redditmedia.com^$image`

**Comment by mun35** [comment]
@mapx- Nope, that doesn't work either. Same happens on bing.com:

Expected result: 

![screen shot 2018-01-25 at 11 03 24 pm](https://user-images.githubusercontent.com/1611736/35389582-fbf6a5e4-0223-11e8-85c7-051d98bb4de3.png)

Actual result:

![screen shot 2018-01-25 at 11 03 30 pm](https://user-images.githubusercontent.com/1611736/35389587-01f2aab0-0224-11e8-9482-c95e54447ddc.png)

Filter used:

`||www.bing.com/s/a/hpc23.png$image`

**Comment by gorhill** [comment]
All works fine here.

Given that you haven't use the logger to make the case, the most likely explanation is that you have filters/rules on your side causing this, so you will have to investigate on your side. "Making the case" there is an issue with uBO requires better investigation effort than what you went through as per the content of your issue.

**Comment by gorhill** [comment]
One thing, be sure you reload with bypassing the browser cache when you experience the issue, it's possible the images are in the short-term memory cache, which bypass extensions' webRequest listeners.

**Comment by Ravizz** [comment]
Yes, the most likely. It happened to me too, several times, several days ago, until I realised I had to do hard reload of the page (CTRL + F5) which bypass the cache.
