### ISSUE TITLE
"My Filters" entries disappeared and moved to 3rd-party filters tab

### ISSUE THREAD

**Issue by shmerl** [gorhill/uBlock#3462]
I used to have a few custom filters in My Filters tab, and now I noticed that it's empty, while 3rd-party filters tab got a check box "My Filters" which says `​​​​​4 used out of 4​​​`. Filters actually work, but the whole change looks messy, and I can't access those filters in the UI anymore.

- Debian Linux (testing) x86_64, KDE Plasma 5.10.5.
- Firefox 59.0b3
- uBlock Origin: v1.14.24

**Comment by gorhill** [comment]
> but the whole change looks messy

What does that mean? Please investigate more thoroughly on your side, this is a strange issue which is specific to you.

**Comment by gorhill** [comment]
I've never heard of such bizarre issue, you will need to come up with a better issue report to make the case there is an issue with uBO. Mind [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), especially the 1st paragraph.

**Comment by shmerl** [comment]
Thinking of it, it's possible that it was caused by data corruption, because I had a power spike that restarted my computer just prior to when I noticed this. So reproducing this might be tricky indeed. And in such case it wouldn't be really uBlock Origin issue.

**Comment by gorhill** [comment]
> I had a power spike that restarted my computer just prior to when I noticed this

In such case, it's possible your filters got lost and yet uBO is still using the compiled versions of these filters. The compiled filters will be discarded whenever you modify your filters.

**Comment by shmerl** [comment]
Ah, yes indeed. I just tried adding one filter to the empty list, and my filter count went from 4 to 1. So you guess sounds correct.
