### ISSUE TITLE
[Question] Why uBlock can't deal with Yandex.Direct

### ISSUE THREAD

**Issue by uboextrauser** [gorhill/uBlock#3463]
Hello, I'm just wondering why uBlock can't block Yandex.Direct with they random classes/divs etc? Why uBlock can't get code from JS Fixes (greasyfork.org/en/scripts/19993-ru-adlist-js-fixes) and do it?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by uboextrauser** [comment]
Why you can't just answer?

**Comment by Hrxn** [comment]
Why you can't just read?
