### ISSUE TITLE
Failing to set noCSPReports to true by default (via source code)

### ISSUE THREAD

**Issue by xftroxgpx** [gorhill/uBlock#3467]
### Describe the issue
I want to have `noCSPReports` be checked (aka true) when the addon gets installed (in Firefox) ie. checked by default. Currently, it's unchecked by default.

### Screenshot in which the issue can be seen
![euntitled](https://user-images.githubusercontent.com/26243389/35477740-d9ac0f94-03ca-11e8-86db-0a4ebc1be0fb.png)
(clicking it adds `no-csp-reports: * true` to `My rules`)

### Steps for anyone to reproduce the issue

What I tried:
1. added line `noCSPReports: true,` to [this](https://github.com/gorhill/uBlock/blob/51fc60223aeacc62d2d29a001f901038da7129d7/src/js/background.js#L70) has no effect.
2. modified [this](https://github.com/gorhill/uBlock/blob/51fc60223aeacc62d2d29a001f901038da7129d7/src/js/start.js#L260) to:
`'dynamicFilteringString': 'behind-the-scene * 3p noop\nbehind-the-scene * 3p-frame noop\nno-csp-reports: * true', //added '\nno-csp-reports: * true'`
3. like 2, to:
`'dynamicFilteringString': 'no-csp-reports: * true\nbehind-the-scene * 3p noop\nbehind-the-scene * 3p-frame noop',`
4. like 2, to:
`'dynamicFilteringString': 'no-csp-reports: * true\n',`

For 2., 3. and 4. in all cases, the `no-csp-reports` line gets removed from `Permanent rules` and `Temporary rules` (in cases 2. and 3. the `behind-the-scene` lines are kept)

- OS/version: ArchLinux 64 bit
- Browser/version: Firefox Nightly (compiled by myself)
- uBlock Origin version: latest from master

My guess is that somehow `no-csp-reports` is precomputed before `dynamicFilteringString` is parsed and thus since `no-csp-reports` is false(so to speak), it won't get added to `dynamicFilteringString` and that's what's causing the perceived removal. However `behind-the-scene` is not affected, possibly because it's not a boolean.

**Comment by jspenguin2017** [comment]
You need to make change like [this](https://github.com/NanoAdblocker/NanoCore/blob/4a877683181d075570a42a299470b0aedaee3200/src/js/start.js#L271) to make CSP reports to be blocked by default. 
You almost hit the right thing.

**Comment by xftroxgpx** [comment]
ohhh very nice @jspenguin2017 I could kiss you, but I'm afraid it would be against the terms of github conduct between humans and penguins =)
![kuntitled](https://user-images.githubusercontent.com/26243389/35481752-1d6f5c72-042a-11e8-8c9e-6348c70bc8a3.png)

```patch
diff --git a/src/js/start.js b/src/js/start.js
index 57f34081..e7116e90 100644
--- a/src/js/start.js
+++ b/src/js/start.js
@@ -259,7 +259,7 @@ var onSelectedFilterListsLoaded = function() {
         'compiledMagic': '',
         'dynamicFilteringString': 'behind-the-scene * 3p noop\nbehind-the-scene * 3p-frame noop',
         'urlFilteringString': '',
-        'hostnameSwitchesString': '',
+        'hostnameSwitchesString': 'no-csp-reports: * true', //thanks jspenguin2017 src: https://github.com/gorhill/uBlock/issues/3467#issuecomment-361035196
         'lastRestoreFile': '',
         'lastRestoreTime': 0,
         'lastBackupFile': '',
```

me so happy =)
