### ISSUE TITLE
Ublock crashs on Chrome

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#3469]
Hi, I am using ublock on chrome and when I am surfing on the internet it crashs roughly once every half an hour.I took the dmp file from directory of chrome browser and  the ublock backup file I am sharing the file with you  below for what you can take advantage of these files.

[b90e4a3a-b4ef-4f39-b9f5-21b7ff7df901.zip](https://github.com/gorhill/uBlock/files/1671425/b90e4a3a-b4ef-4f39-b9f5-21b7ff7df901.zip)

[my-ublock-backup_2018-01-28_21.27.19.zip](https://github.com/gorhill/uBlock/files/1671429/my-ublock-backup_2018-01-28_21.27.19.zip)

- OS/version: Windows 10 x64
- Browser/version: Chrome v64
- uBlock Origin version: 1.14.24

**Comment by Hrxn** [comment]
Extensions should not be able to crash the browser..
So I guess the issue is something else entirely.

**Comment by gorhill** [comment]
Report to browser devs, uBO is HTML/CSS/JS, the browser is not supposed to crash.

**Comment by mapx-** [comment]
or create a new profile, perhaps the old one is corrupt.
