### ISSUE TITLE
List with examples of my-rules

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [gorhill/uBlock#347]
I'd like to see some examples what's all possible to write in my-rules. Some sort of documentation would be nice, unless I'm blind and these already exist.

**Comment by Krak-n** [comment]
You're just blind! D;

https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

Unless that's not what you're looking for?

**Comment by anewuser** [comment]
Please close this issue. Read the wiki before posting and don't bother the developer with duplicates.

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-default-deny:-useful-rulesets
