### ISSUE TITLE
HTML filtering on site like trakt.tv

### ISSUE THREAD

**Issue by zmni** [gorhill/uBlock#3470]
### Describe the issue

Element removed on full page load, reappeared after clicking any links.

### One or more specific URLs where the issue occurs

All urls on `trakt.tv`

### Screenshot in which the issue can be seen

- Element removed on full page load

![screenshot-2018-1-29 trending movies2](https://user-images.githubusercontent.com/841523/35487146-fce9f68e-04aa-11e8-9e51-0576427d1302.png)

- Element reappeared after clicking any links (ex, Movies top nav link)

![a](https://user-images.githubusercontent.com/841523/35487280-5c798b22-04ac-11e8-910c-3ecd41802ae7.jpg)

### Steps for anyone to reproduce the issue

1. Visit `trakt.tv`.
2. Use my custom rules below.
3. Visit other page, for example click TV or Movies on top navigation.
3. Fully reload the page, <kbd>Ctrl+r</kbd> or <kbd>F5</kbd> : element removed.
4. Re-visit the page by clicking the same link or visit other page : element reappeared.

### Your settings

[Hard-mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode)

- OS/version: `Windows 10.0.16299`
- Browser/version: `Firefox 58`
- uBlock Origin version: `1.14.25rc1`

##### Your filter lists

Default filter lists

##### Your custom filters (if any)
```
...
...
trakt.tv##^.auth-services
trakt.tv##^.btn-google
trakt.tv##^.btn-list-subscribe
trakt.tv##^.btn-watch-now
trakt.tv##^.feeds
trakt.tv##^.get-tickets
trakt.tv##^.huckster-grid-item
trakt.tv##^.huckster-vip-info
trakt.tv##^.vip-actions
trakt.tv##^.vip-sidebar-links
trakt.tv##^.watch-now
trakt.tv##^[id^="huckster-"]
trakt.tv##^a.feed-icon
trakt.tv##^a[href^="/pro"]
trakt.tv##^li:has(:scope > a[href^="/apps"])
trakt.tv##^li:has(:scope > a[href^="/vip"])
...
...
```

**Comment by gorhill** [comment]
By design.

HTML filtering currently only applies to requests of type `main_frame`/`sub_frame` which mime is `text/html`, not to any other types of response. When you click a link, the site does not pull a new `text/html`, it dynamically updates the DOM.

Just use cosmetic filtering, it's better suited for your case.
