### ISSUE TITLE
Zapper Element Mode Shortcut

### ISSUE THREAD

**Issue by bytos** [gorhill/uBlock#3473]
Would it be possible to add a keyboard shortcut to activate the element zapper mode?

When the icon is in the overflow menu it takes three clicks to activate per element you want to zap plus waiting for the UI to show (when using CSS suggestion).

Since addons are no longer supported uBlock could be used to edit web pages to remove unwanted elements before saving with another web extension to reduce their size.

**Comment by gorhill** [comment]
It's already supported, you will just have to assign a key yourself. For Firefox, the Firefox UI does not yet support assigning a keyboard shortcut.
