### ISSUE TITLE
[Nightly] Redirection to neutered scriptlet broken by forbidden redirection to data: urls

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#3474]
Originally filed at:
<https://github.com/uBlockOrigin/uAssets/issues/1370>

Corresponding bugzilla entry:
<https://bugzilla.mozilla.org/show_bug.cgi?id=1434357>

Test case (from original issue):
`http://kissasian.ch/Drama/Age-of-Youth-2/Episode-1?id=34574&s=beta&pfail=1`

**Comment by jspenguin2017** [comment]
How about using request filtering to replace the response data with the neutralized version? One request will hit the script server, but that's better than breaking the page and having to disable all filtering. 

I have yet to study how filtering engine is implemented, but from my current understanding, some refactoring might be required, as the request needs to be allowed then filtered later.

**Comment by ff2000** [comment]
I know this is about nightly... But since blocking is basically not working anymore since firefox update from 58.0 to 58.0.1 I wanted to ask if this is caused by the same issue or if I should open a new one.

**Comment by gorhill** [comment]
> blocking is basically not working anymore since firefox update from 58.0 to 58.0.1

I know of no such issue. Please investigate more on your side before opening a new issue -- if you open a new issue without being able to make the case there is an issue with uBO itself, I will close as invalid.
