### ISSUE TITLE
BlockAdblock: a script intended to mess with uBlock

### ISSUE THREAD

**Issue by luarum** [gorhill/uBlock#3476]
### Describe the issue
A service called BlockAdblock  (located at https://blockadblock.com/) has been cropping up on various sites. It uses an embedded script to send users to a nagpage that withholds the site unless you unblock all ads. Sometimes clicking the "I turned off adblock" button without turning off adblock will result in being sent to an unrelated page. Other times it sends you back to be nagged again.

It would help if an easy to use script-blocker could be added to uBlock to help users find and block unwanted behaviors like this in the future. Something like the zapper function, only it listens for and logs the last (3 by default, maybe more?) scripts that went off. From there the user can block/unlock the scripts and try reloading the site.

...is there a function like this already in uBlock that I have missed?

If sites are starting to use scripts like this to block out adblockers, we will also need a list of common blocker-blocking scripts added to the filter lists to go along with the script-blocking feature. 

### One or more specific URLs where the issue occurs

Example of basic functions plus scripts:
 https://blockadblock.com/

Example of Auto-forwarding to a site on click with adblock on;
https://ithubpk2.blogspot.com/2018/02/telegram-removed-from-apples-app-store.html

### Screenshot in which the issue can be seen
![block adblock](https://user-images.githubusercontent.com/36089303/35758175-8ca29aea-0840-11e8-9a81-9848e9da421e.png)

### Steps for anyone to reproduce the issue

1.  Go to blockadblock.com
2. Wait a few moments and the example script will kick in.

This holds true on any site using this script or it's variants.

### Your settings

Technically this should be browser/system agnostic as it's meant as a multiplatform blocker stopper. Here's my settings anyway.

- OS/version:  Windows 10
- Browser/version: Firefox 56.0.2 (64-bit)
- uBlock Origin version: uBlock Origin v1.15.0

##### Your filter lists
uBlock filters​​​​​
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList​
EasyPrivacy​
    Malware Domain List
Malware domains​
Peter Lowe’s Ad and tracking server list​

##### Your custom filters (if any)
No custom filters.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues?q=is%3Aissue+BlockAdblock+is%3Aclosed

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment]
dedicated scriptlet:
`example.com##script:inject(bab-defuser.js)`

for simple cases just use:
`@@||example.com^$generichide`

in your case:
`@@||ithubpk2.blogspot.com^$generichide`

but also:
`ithubpk2.blogspot.com##script:inject(bab-defuser.js)`
