### ISSUE TITLE
Gmail emails cant open subscribed content links properly any-more

### ISSUE THREAD

**Issue by futagoza** [gorhill/uBlock#3477]
### Describe the issue

On Gmail there are some notification-type email's that will automatically get a 'Button' on the emails row, allowing the user to click on the button to open the link to the subscribed content while automatically marking the email as read.

Among some of the ones I have, the one I use the most is GitHub notifications. Now what should happen is that the links take me to Issues or PR's on GitHub by opening a new tab, but it closes that new tab straight away and returns me to the tab that I was on before my Gmail tab.

This issue only started happening about several hours ago when I turned on my laptop for the first time today, turned on Firefox, and uBlock (and _ONLY_ uBlock) automatically updated. I managed to fix the issue by putting `mail.google.com` in my Whitelist, but I don't think I should have to resort to this when I haven't had to do this in the past 6 months that I have been using this addon (first on Opera, now on Firefox)

### One or more specific URLs where the issue occurs

https://mail.google.com/

### Screenshot in which the issue can be seen

Can't get one, it open's and closes too fast.

### Steps for anyone to reproduce the issue

1. Log into your Gmail Inbox
2. Click on a GitHub notification's `View Issue` button

### Your settings

- **OS/version:** Windows 10 x64, Version 1709, Build 16299.192
- **Browser/version:** Firefox 58.0.1 
- **uBlock Origin version:** 1.15.0

##### Your filter lists

- Default filter lists
- Adblock Warning Removal List

##### Your custom filters

Whitelisted mail.google.com, but no custom filters

**Comment by okiehsch** [comment]
Well, what does your logger say in regards to which filter closes the new tab?

If you do not know how to investigate using the logger. here is some light reading
https://github.com/gorhill/uBlock/wiki/The-logger

If you still don't know how to troubleshoot your problem, open the logger, then go to your inbox, click the "Button", then post a screenshot.

**Comment by futagoza** [comment]
@okiehsch Thanks, but it looks like you won't need the screenshot 😄, the culprit is `wyciwyg://$popup` 

After opening the logger, it seem's that when clicking on these button's, new tabs that have links starting with `wyciwyg` are blocked (opened and closed tab, logline is red), and after clicking on the specific log line for more details, it says that `wyciwyg://$popup` is linked to EasyLists, but I don't know if this is a 3rd part filter that is enabled by default. I'll ask my brother in the morning if he enabled any of the 3rd party filters, but is this enabled by default? Also, I was under the impression that the 3rd part filters update their list separately from the add-on, but since this problem cropped up after uBlock updated, does that mean that some of them are manually updated?

**Comment by okiehsch** [comment]
EasyList is enabled by default, but the filter `wyciwyg://$popup` was [removed 12  days ago](https://github.com/easylist/easylist/commit/d778925d637a9664286f196ddc7e6b10ea79ac9f#diff-1663b367f85f751b45adc7a818a868f8), I don't know how it ended up causing your issue.

**Comment by jspenguin2017** [comment]
The extension package comes with outdated filters.

**Comment by okiehsch** [comment]
So the packaged filters replace the up to date filters if uBO auto-updates?

**Comment by jspenguin2017** [comment]
No, but they will be used on first install. For about an hour.

**Comment by okiehsch** [comment]
That`s what I thought. but the OP said that his uBO **updated** and then his issue appeared, so he should not have `wyciwyg://$popup` in his EasyList installation.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> For a few hours.

They will be all up to date after less than 45 minutes after first install.
