### ISSUE TITLE
difference between "Storage used & ublock0.sqlite" size!

### ISSUE THREAD

**Issue by lukanz** [gorhill/uBlock#348]
![ublock](https://cloud.githubusercontent.com/assets/12429282/8148427/710057be-129d-11e5-99c0-db90431d4a3d.jpg)

Storage used: 474.838 bytes vs ublock0.sqlite size: 4.784.128 bytes, and it wont change after purging either, must be a misspelling in code!
i'm using uBlock Origin v0.9.9.0

**Comment by gorhill** [comment]
There is no guarantee a SQLite file will match the storage used -- as there might be gaps of unused data within the SQLite file. uBlock will emit once a while a `VACUUM` command to the SQLite database in order to remove these gaps. The `VACUUM` command occurs once per session at most, and only when uBlock sees the computer is idle, as a vacuum command [can be costly resource-wise](https://developer.mozilla.org/en-US/docs/Storage/Performance#Vacuuming_and_zero-fill).

**Comment by gorhill** [comment]
Close as "by design".

**Comment by Gitoffthelawn** [comment]
@gorhill 
Is the entire SQLite database stored in memory all the time the browser is running?  (Not suggesting there is another way, just trying to gain knowledge.)

Is the 'Storage used' only the size of the filters/rules/whitelist database (the contents of the SQLite database), or is it reflective of more or less than that?  Does it include the size of the actual extension in memory?

I too have noticed that the value reported in 'Storage used' is not the same as the actual size of the database, even after forcing a vacuum of the database.  But it's always fairly close (within 250KB).  I've always chalked it up to SQL headers or the like.  But if that doesn't explain it, maybe it is a small issue.   After vacuuming, on your test systems is the database size and the 'Storage used' value the same?

@lukanz 
Did you delete a bunch filter lists before performing that comparison?  That's approximately a 1 to 10 ratio between reported size and actual size.  Try letting uBlock Origin vacuum the database (or vacuum it manually), and then report back.  Alternatively, backup your filters, rules, and whitelist by hand and delete the database file.  uBlock Origin will recreate it on the next launch. Then see if your numbers are more in line with expectations.

**Comment by gorhill** [comment]
uBlock just uses the Firefox API to access the SQLite database, all it knows about is the API, all else is under Firefox API control.

**Comment by Gitoffthelawn** [comment]
@gorhill Thanks.  Is the 'Storage used' size just the total size value reported by the Firefox API for the uBlock Origin SQLite database?
