### ISSUE TITLE
[UI] Weird tree/category collapsing behaviour in 3rd Party pane.

### ISSUE THREAD

**Issue by Ravizz** [gorhill/uBlock#3480]
![capture_070_05022018_090845](https://user-images.githubusercontent.com/35421792/35794003-320d3714-0a54-11e8-910a-581d670873cc.png)

uBlock Origin v1.15.4
F 58.0.1 & O 50.0.2762.67 (PGO)

Weird tree collapsing behaviour in 3rd Party pane.

All the trees/categories: 
a) have unique name of category
a) collapse completely 
b) show number of active lists

But the top tree has not neither a) nor b) nor c)
As for a) it should be named "uBlock"
That top tree is like a black sheep.
Are these (a b c) bugs or intended behaviors (why)?

**Comment by gorhill** [comment]
By design.
