### ISSUE TITLE
Request : Stop Chromium From Adding Custom Search Engines

### ISSUE THREAD

**Issue by gallieni** [gorhill/uBlock#3482]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### When we use search in web page .Chromium add itsel serach engine in : Other search engines ; in setting ; Manage search engines.

It woulb be great to have an option to block this in uBlock Origin.
Before have an extension ;  but now not working.
Don't add custom search engines
https://chrome.google.com/webstore/detail/dont-add-custom-search-en/dnodlcololidkjgbpeoleabmkocdhacc?hl=en

### https://korben.info/

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Go to https://korben.info/
2. Enter one seacrh word
3. After the search ; you see 

Search engine .............................Keyword..................................................Query URL
korben.info...................................korben.info..............................................https://korben.info/?s=%s

In : Other search engines
in setting ; Manage search engines.

### Your settings
In Privacy and security:
All is uncheck.

That's all difference settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7 SP1 32bit
- Browser/version: Chromium	66.0.3331.0 32 bit
- uBlock Origin version: 1.15.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

Default filter lists ; all.

##### Your custom filters (if any)
No

**Comment by Hrxn** [comment]
There is an open issue on the Chromium tracker for this.
Let's hope that it will be addressed in the not too distant future.
