### ISSUE TITLE
Images don't load when accessed directly, and occassionally on pages too

### ISSUE THREAD

**Issue by caviidae** [gorhill/uBlock#3483]
I've been having this issue for a while and have now just realised uBlock is the problem. Same problem these people are having https://www.reddit.com/r/uBlockOrigin/comments/6ww10v/ublock_origin_blocks_images_from_displaying_in/

If I click any image links from anywhere they always just show a blank page. Examples:
https://i.imgur.com/q0XTR83.png
https://gelbooru.com//images/32/2f/322f5e5aa6957cc5ce75acb3654246b9.jpg

- Windows 10
- Firefox ESR 52.5.3 (64bit)
- uBlock 1.15.4

Filter lists or uBlock settings don't matter. I've emptied all filters and rules and tried. I've also reset the settings and tried.

The images only start loading again when uBlock is actually disabled in the Add-ons page. The logger doesn't show anything being blocked.

![blankublock](https://user-images.githubusercontent.com/19197453/35804660-d2e4a2b2-0acc-11e8-8819-b4a210d17524.png)
It seems to make the network request but I don't know if it's getting the proper data:
![network](https://user-images.githubusercontent.com/19197453/35804764-315eec12-0acd-11e8-954f-92393dbb6d8b.png)
![ublock _ _logger_-_2018-02-05_23 34 04](https://user-images.githubusercontent.com/19197453/35804786-499b17b0-0acd-11e8-9eb5-1dd966c85a1b.png)

What I've been doing all this time is just doing a ctrl+s on the blank pages to download the images and then view them outside of the browser, since they don't display in the browser.

**Comment by caviidae** [comment]
The people in that reddit thread were talking about greasemonkey but that isn't my problem. However these issues may be related? 
https://github.com/greasemonkey/greasemonkey/issues/2524

**Comment by gorhill** [comment]
What version of uBO is this? Legacy or webext?

**Comment by caviidae** [comment]
How do I check? I just reinstalled the one from here https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ . I don't see any LEGACY label on the add-ons page. But I am using FF ESR so maybe I wouldn't anyway.

**Comment by gorhill** [comment]
So you have the webext version.

See <https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions>. Using the webext version with FF56 and less along with legacy extensions is likely going to cause issues, and this was confirmed with Greasemonkey in thepast.

**Comment by caviidae** [comment]
Oh sorry I haven't had time to keep up to date. I've installed the latest legacy version now along with ublock0-updater and everything is working fine :)
