### ISSUE TITLE
Ublock origin is not work on these sites

### ISSUE THREAD

**Issue by CyberMan571** [gorhill/uBlock#3486]
Hello everybody
The Ublock origin does not stability work on these sites.

### One or more specific URLs where the issue occurs
www.youtube.com
http://720pizle.com/izle/dublaj/batman-gotham-by-gaslight.html/5
http://uptostream.com/iframe/bbi2qg6ug3kw/
https://www.fullhdfilmizlesene.org
filmkolikhd.com/the-flash-3-sezon-izle-turkce-dublaj.html

The Problems
1.at any time any buttons and links or the search box is clicked after open a pop-up and ublock origin is  not block them (https://www.fullhdfilmizlesene.org and filmkolikhd.com)
2.there is bug on youtube 
of block number/count  has continuous increase
3.it is not work on uptostream 

![screenshot from 2018-02-06 05-58-50](https://user-images.githubusercontent.com/30759335/35840038-c32d71ae-0b04-11e8-8066-25b0c5ecc28a.png)
![screenshot from 2018-02-06 05-59-14](https://user-images.githubusercontent.com/30759335/35840039-c3562d4c-0b04-11e8-8277-13c0df3c9cd9.png)
![screenshot from 2018-02-06 06-00-21](https://user-images.githubusercontent.com/30759335/35840040-c37c8794-0b04-11e8-9ae8-d4ed4d678d3d.png)

![screenshot-20180206064627-1592x387](https://user-images.githubusercontent.com/30759335/35840824-8142ec06-0b09-11e8-837b-e1f82bb4732c.png)

### Your settings
Linux os and android os
any browser
uBlock Origin 1.13.11.100

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by CyberMan571** [comment]
@gorhill 
Fixed the invalid filter issue
I used  following filters
TUR: Adguard Turkish  Filter​​​​
![screenshot-20180224175525-586x622](https://user-images.githubusercontent.com/30759335/36631589-fbe39330-1972-11e8-9412-3791c244bcd4.png)
![screenshot-20180224175613-610x312](https://user-images.githubusercontent.com/30759335/36631590-fc4cac76-1972-11e8-9586-19f4a9e61b9d.png)

​​​
