### ISSUE TITLE
https://www.urbandictionary.com/

### ISSUE THREAD

**Issue by babbelnedd** [gorhill/uBlock#3487]
### Describe the issue
Site looks weird

### One or more specific URLs where the issue occurs
https://www.urbandictionary.com/

### Screenshot in which the issue can be seen
https://i.imgur.com/Vyg0LWX.png

### Steps for anyone to reproduce the issue
Just open the website 🤷‍♀️ 

### Your settings

Windows 10  
Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)  
uBlock Origin 1.15.2

##### Your filter lists
Default + DEU + AAK

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
