### ISSUE TITLE
Add Web Annoyances Ultralist

### ISSUE THREAD

**Issue by Ravizz** [gorhill/uBlock#3489]
Add Web Annoyances Ultralist ( by @yourduskquibbles ): 
https://github.com/yourduskquibbles/webannoyances

**Comment by anewuser** [comment]
uBlock Origin already has two extensive third-party lists for annoyances besides its own.

If you find any missing case, report it to https://github.com/uBlockOrigin/uAssets/issues

**Comment by Ravizz** [comment]
I've expected such illogical reply like:
a) can have 2 but cannot have 3

illogical coz:

(1)

 It can be easily paraphrased to: 
b) can have 1 but cannot have 2
c) can have 3 but cannot have 4
d) can have 4 but cannot have 5
and so on, so how did you calculated, which one is suitable? Roughly?

(2)

Statement "extensive" apply only to a case wherein an user has all the lists enabled at once, so why do you assume that and how do you know that anyone will turn them on all at once? 

The facts are simply the opposite: 

a) that most users don't use and don't have all lists enabled:
https://www.google.pl/search?q=ublock+3rd+party&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj1yp_94pXZAhVvgaYKHTDKCJYQ_AUICygC&biw=1024&bih=687&dpr=1.25#imgrc=_

b) and even by default in UBO only some of the list are enabled

(3)

Using them all at once or not is simply not your business, it is an end user's decision how many lists one wants to enable and use.

**Comment by Hrxn** [comment]
> abusing https://en.wikipedia.org/wiki/European_Union_competition_law

What the... seriously?
Please explain how Articles 101-109 TFEU apply to open source projects on GitHub?!
Jesus Christ. No, wait, please don't. Just get out of here.

**Comment by gorhill** [comment]
> illogical coz

It's not illogical when the purpose of the lists offered in the "3rd-party filters" pane is that of convenience, not as a comprehensive library of all filter lists available at <https://filterlists.com/>.

**Comment by Ravizz** [comment]
> @Hrxn :
> What the... seriously?
> Please explain how Articles 101-109 TFEU apply to open source projects on GitHub?!

Not seriously, not directly, not in the legal/law sense, that's why I've written: "morally equivalent" which has meant that my intention has been to be taken not too seriously, I 've just meant that's a bit unfair, so I think you have just misunderstood or do not read with understanding.

> @Hrxn : Jesus Christ. No, wait, please don't. Just get out of here.

Please do not insult/attack me, if one deserves to get out of here, it is definately you, not me, for your vocabulary, and we are not in the church, so don't call Jesus Christ here, do not call God in vain, impious.

> @gorhill: It's not illogical when the purpose of the lists offered in the "3rd-party filters" pane is that of convenience, not as a comprehensive library of all filter lists available at https://filterlists.com/.

I've nowhere have written to add all lists, but if you say like that, I can paraphrase/reverse you and  write: then go and remove all lists from uBO then and everyone will add lists on their own.

But let's leave such extremes, we agree that there must be some consensus/balance and the point is:

a1) where is the center of this balance? 
b1) why a), and not b), c) or d) ? 
c1) by what criteria/mathematical formula is it calculated?

d1) is Web Annoyances Ultralist worse/lower quality than AdGuard / Fanboy ? 
e1) is Web Annoyances Ultralist smaller than AdGuard / Fanboy ? No, it fits in the middle between them.

I think that assumption to be guided by size and quality of lists in case of adding to uBO is proper, so Web Annoyances Ultralist meets these criteria.

**Comment by anewuser** [comment]
Please check this page: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). 

 It includes a link to a forum where you can ask, argue and discuss anything with other uBlock Origin users and contributors. We have no time to keep repeating ourselves, especially when people are rude.

**Comment by uBlock-user** [comment]
> we agree that there must be some consensus/balance and the point is

Gorhill would only add lists which he finds it worth adding, you requested it and he declined, that's how it is. There's no ''center of this balance" as you put it. There's no other logic here.

**Comment by Ravizz** [comment]
>  @anewuser : especially when people are rude.

Quote please, no slanders/accusations please, as I see I've nowhere been rude, only tech-talk and expressed my opinion that it is worth to add Web Annoyances Ultralist, and then the facts that:

- my opinion was different from yours 
- you can't give neither technical counterarguments nor answers to my questions, 
- so you can't reasonably decline my request, so you decline it by personal attacks

Caused:
- caused @Hrxn's to insult me, 
- and now  @anewuser to insult me again by his slander/accusation,

So:
- it's not me who insult / is rude here.
- noone here takes any action against people who off-topic/insult me
- insulting people is tolerated here

> @uBlock-user :  which he finds it worth

It seems a mystery how he does it...he is known to decline very many things for no reason/with no clear explanation/reasonable counterarguments / no deals, and that is why a competition in the form of Nano Adblocker has been created, not mentioning that he allows people to insult on his repo.

> @uBlock-user : There's no other logic here.

Sad true.

**Comment by gorhill** [comment]
Reason is I think there are enough good choices in the current selection.

Arguing everything to no end is a recipe to bring development to a halt, hence why I often decline with no further comment.
