### ISSUE TITLE
uBlock conflicting with reddit's gold popup box

### ISSUE THREAD

**Issue by D-avid** [gorhill/uBlock#349]
When enabled, it causes a conflict with reddit's "give gold" diaglouge box. Instead of displaying the popup, it redirects you to https://www.reddit.com/gold/payment page and this page does not include the additional options to gild anonymously.

Disabled, the gold popup box displays.

I have uploaded two screen shots, the red rectangles represent the symptoms, and both demonstrating both enabled and disabled. 
![enabled](https://cloud.githubusercontent.com/assets/12883418/8149188/bc606d56-12b2-11e5-8d3e-a2cfedb322f3.png)
![disabled](https://cloud.githubusercontent.com/assets/12883418/8149189/bc63aaca-12b2-11e5-8072-cad1549f895a.png)

Version: µBlock v0.9.8.6
Web Browser: Opera 30.0.1835.59
OS: Windows 7

**Comment by gorhill** [comment]
_"uBlock filters – Unbreak‎"_  has been updated, purge its cache in _"3rd-party filters"_ pane and for an update.
