### ISSUE TITLE
blogspot cosmetic filter

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBlock#3491]
### Describe the issue
The cosmetic filter `example.blogspot.*##whatever`
does not work, you have to use the specific `example.blogspot.com` or whatever country you reside in.

### One or more specific URLs where the issue occurs

`mimaletadepeliculas.blogspot.com` https://github.com/uBlockOrigin/uAssets/issues/1480

### Steps for anyone to reproduce the issue

- Add `mimaletadepeliculas.blogspot.*##.clearfix` to your filters, which should hide the content.
- Go to `http://mimaletadepeliculas.blogspot.com`
- The content is still visible.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 64
- uBlock Origin version: 1.15.2

##### Your filter lists

default

**Comment by jspenguin2017** [comment]
I don't think you can match half of a Public Suffix. `mimaletadepeliculas.*##.clearfix` correctly match `http://mimaletadepeliculas.blogspot.com/`. Similarly, `example.c*##h1` does not match `example.com`.

**Comment by gorhill** [comment]
Ah that's right, `blogspot.com` is a public suffix, this escaped me.
