### ISSUE TITLE
Issue with blocking of StackPath CDN content

### ISSUE THREAD

**Issue by Mike1B** [gorhill/uBlock#3492]
### Describe the issue

Using Firefox 58.0.2 (64-bit) and Windows 10 Pro (Ver 1709 - Build 16299.192), I've tested works fine displaying the website, till installing the adblocker plugin "uBlock Origin 1.15.4". Then it shows only half the webpages, with the following errors under the console...

Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-includes/js/jquery/jquery.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-includes/js/jquery/jquery-migrate.min.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-content/themes/artrage/inc/plugin/shortcodes/js/init.js”. www.artrage.com:17 
ReferenceError: jQuery is not defined[Learn More] www.artrage.com:17:1 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-content/plugins/revslider/public/assets/js/jquery.themepunch.tools.min.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-content/plugins/revslider/public/assets/js/jquery.themepunch.revolution.min.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-content/plugins/thirstyaffiliates/js/app/ta.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-content/themes/artrage/js/main.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-content/themes/artrage/js/mobile-menu.js”. www.artrage.com:17 
Loading failed for the <script> with source “https://wwwartragecom-akuj6lcbutr8ndmkzcy.stackpathdns.com/wp-includes/js/wp-embed.min.js”. www.artrage.com:17 
ReferenceError: jQuery is not defined[Learn More] www.artrage.com:19:48 
Failure at Presize of Slider:ReferenceError: jQuery is not defined 

It appears that the adblockers latest version is blocking the stackpath CDN?

### One or more specific URLs where the issue occurs

https://www.artrage.com/

### Screenshot in which the issue can be seen

http://i68.tinypic.com/2hhj1xf.jpg

### Steps for anyone to reproduce the issue

Enable "uBlock Origin 1.15.4" on Firefox web-browser and CTRL+F5 (Force refresh) the webpage of ArtRage. It appears the sliders / jquery won't load.

### Your settings

- OS/version: Windows 10 Pro (Ver 1709 - Build 16299.192)
- Browser/version: Firefox 58.0.2 (64-bit)
- uBlock Origin version: uBlock Origin 1.15.4

##### Your filter lists

Default

**Comment by Mike1B** [comment]
Sliders affected I've found to be Slider Revolution. There's however no ads on the website what-so-ever.

**Comment by anewuser** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what list has blocked your request, and report it to the maintainers of that list.

Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).  It includes a link to a forum where you can ask for help with such issues.

**Comment by Mike1B** [comment]
Closing sorry.
