### ISSUE TITLE
Make element removal rules backwards/Chromium-compatible

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#3493]
@mapx- changed my rule in https://github.com/uBlockOrigin/uAssets/pull/1507 because apparently Chrome would just discard it.

I couldn't find any discussion about this. Have you considered parsing new rules such as 

`www.google.ca##^#hplogo`

as

    www.google.ca##^#hplogo
    www.google.ca###hplogo

? That'd be useful for us to use `^` in filter lists while keeping compatibility with Chromium-based browsers.

**Comment by mapx-** [comment]
HTML filtering (`##^`) is supported only by Firefox 57+
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters

**Comment by gorhill** [comment]
HTML filtering is not the same as cosmetic filtering, they are not semantically the same. For any issue, it's preferable to use a cosmetic filter when it works, because HTML filtering is only available on Firefox 57+.

**Comment by anewuser** [comment]
>HTML filtering (##^) is supported only by Firefox 57+

That's what I meant, since `www.google.ca##^#hplogo` only works on Firefox 57+, it could be interpreted as

    www.google.ca##^#hplogo
    www.google.ca###hplogo

So this element gets completely stripped on Firefox 57+ while still being hidden on older versions and browsers.

I know it can filter more than just `<body>` IDs and classes, but I'm talking about them specifically (`example.org##^#test` and `example.org##.#test`).

I understand if you prefer not to add this and keep using  only cosmetic filters on official filters.

**Comment by gorhill** [comment]
Ok I understand your point. I need to ponder more about this.

**Comment by anewuser** [comment]
Yes, I had mentioned in the original post (and then removed it to keep it concise) that my link isn't the best example, since HTML filtering on it just blocks the loading of a small image from the same domain.

If the static images hidden by certain cosmetic filters are larger or from third-party domains, though, it's preferable to remove the element altogether instead of downloading such hidden images on the background. I'll try to find some good example if you decide to keep this issue open. 

However, if there's the expectation that toggling `no-cosmetic-filtering:` to `true` will show all content "hidden" by subscription lists, HTML filtering for structural elements like `div`, `p` etc. would have to be turned off too when this setting is used.

**Comment by anewuser** [comment]
Ah, I just remembered this, which has larger images (although also from the same domain): https://github.com/AdguardTeam/AdguardFilters/pull/10140

`moviechat.org` changed the path of its image banners from `moviechat.org/images/affiliates/` (previously blocked by AdGuard) to `moviechat.org/images/aff/`, while keeping the same CSS class for the parent elements of ads.

The result of this is that the banners started being loaded in the background, while still being hidden by AdGuard and EasyList cosmetic rules. This was fixed only when I noticed this by watching the logger and reported it to them. 

If they change the path of banners again, they'll once again start being downloaded in the background until someone notices it (and since subscription lists hide the parent element, you need to be watching the logger or disable cosmetic filtering to notice it).

**Comment by gorhill** [comment]
Thinking more about it, this can't work, the semantic is too different. You can find cases for which this works, but then the question will become what for cases for which the conversion causes issue.

**Comment by okiehsch** [comment]
You can just disable the inline-script that pushes the ads at `moviechat.org`, in which case it does not matter if they change the path again.
For example
`moviechat.org##script:inject(abort-current-inline-script.js, $, adblock)`
should work.

**Comment by anewuser** [comment]
@okiehsch Apparently they've changed their code again. It had simple image tags with custom banners inside `.adc` before, not Amazon banners inserted by a script. That's why I used it as a case for HTML filtering. Anyway, this was just an example of what I had I mind.

I've converted all my personal cosmetic filters to HTML filters after updating uBlock Origin. This is a feature I missed from the old Opera, which blocked the download of images hidden by userCSS. 

Well, let's hope Google doesn't take long to support HTML filtering.

**Comment by gorhill** [comment]
We can still use HTML filtering for cases where it's worth it (possibly on some Polish sites from what I've seen) -- even if we have to create another extra filter for Chromium (or not and suggest users to move to Firefox when there is no solution for Chromium). Ideally Chromium will implement the filterResponseData API (which would render uBO-Extra irrelevant) and we won't have to worry about this.
