### ISSUE TITLE
Scriptlet injection exception erroneously reported as being from a filter list in which it isn't present

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#3494]
### Describe the issue

Exception filter for scriptlets don't take effect when the filter originates from an external filter list. Creating a scriptlet filter and then adding an exception filter yourself seems to work fine.

### One or more specific URLs where the issue occurs

https://www.reddit.com/

### Screenshot in which the issue can be seen

https://i.imgur.com/TZS7mPs.png

### Steps for anyone to reproduce the issue

1. Add this filter list: https://github.com/yourduskquibbles/webannoyances/raw/master/ultralist.txt (which has `reddit.com##script:inject(set-constant.js,isPinned,true)` filter)
2. Create an exception filter `reddit.com#@#script:inject(set-constant.js,isPinned,true)`
3. Exception filter still shows up in the logger and also shows as originating in the Web Annoyances list even though it doesn't have the exception filter

### Your settings

- OS/version: Windows
- Browser/version: Firefox 58
- uBlock Origin version: 1.15.4

##### Your filter lists

Default + https://github.com/yourduskquibbles/webannoyances/raw/master/ultralist.txt

##### Your custom filters (if any)

reddit.com#@#script:inject(set-constant.js,isPinned,true)

**Comment by gorhill** [comment]
> Exception filter still shows up in the logger

That part is normal, no?

What is incorrect however is that it shows the filter as originating from Web Annoyances Ultralist.

**Comment by grenzor** [comment]
If I create a scriptlet filter myself and then add a scriptlet exception filter the scriptlet filter isn't shown in the logger at all (I think this behavior also is the same for cosmetic exception filters). 

Example:
Add `reddit.com##script:inject(addEventListener-defuser.js, scroll)` and see logger (it is injected)
Then add `reddit.com#@#script:inject(addEventListener-defuser.js, scroll)` and see logger (the injection filter or the exception filter is not shown at all)

**Comment by uBlock-user** [comment]
> That part is normal, no?

As far as I know cosmetic filters starting with `#@#` don't appear in the logger, but the ones used with script injection do, so I don't think this is normal.

**Comment by uBlock-user** [comment]
Example - Add the following filters to My Filters, the result should be that the first doesn't get applied and the second one doesn't appear in the filter and that's how exactly it happens.

```
github.com##.js-issue-title
github.com#@#.js-issue-title
```

**Comment by gorhill** [comment]
> Then add reddit.com#@#script:inject(addEventListener-defuser.js, scroll), refresh and see logger (the scriplet exception filter is not shown at all)

It is on my side.

**Comment by grenzor** [comment]
My bad, yes I can see it too.

**Comment by uBlock-user** [comment]
There're two issues as I see it - 

* The scriptlet filter is still in effect even when scriptlet exception filter is added

* The scriptlet exception filter appears in the logger.

**Comment by gorhill** [comment]
@grenzor How did you come to the conclusion the filter `reddit.com##script:inject(set-constant.js,isPinned,true)` is still taking effect?

**Comment by gorhill** [comment]
> So I think @uBlock-user is right that scriptlet exception filters are shown in the logger while cosmetic exception filters aren't.

That is by design. No point reporting the cancelled filter. The exception must be reported to inform the user that a `script:inject` filter was cancelled. I can't make sense of seeing this as an issue.

I can't reproduce issues of `#@#script:inject` not cancelling a matching `##script:inject`, so the only issue left is the logger improperly reporting the filter lists. I will change the title accordingly.

**Comment by Ravizz** [comment]
> @grenzor : But IMO showing both scriptlet and cosmetic exception filters in the logger should be the correct way of displaying they're taking effect

I agree, and that's the old unresolved issue: https://github.com/gorhill/uBlock/issues/127

**Comment by uBlock-user** [comment]
> No point reporting the cancelled filter

Then why is the cancelled scriptlet exception filter shown in the logger ? I can't make sense of that.

**Comment by gorhill** [comment]
> Then why is the cancelled scriptlet filter shown in the logger ?

It's not. The exception `#@#script:inject` filter is shown, look at the screenshot I posted.

**Comment by okiehsch** [comment]
I think he means, if you think the user has to be informed that a `script:inject` filter has been cancelled,
why is that not also the case if a regular cosmetic filter has been cancelled.

**Comment by grenzor** [comment]
I think there is only a confusion/miscommunication here between how the scriptlet exception filters and cosmetic exception filters are displayed in the logger. Scriptlet exception filters when they correctly cancel out scriptlet filters are displayed in the logger whilst cosmetic exception filters when they correctly cancel out cosmetic filters are currently not displayed in logger (which @uBlock-user may have thought meant that scriptlet exception filters weren't actually cancelling out scriptlet filters since they still showed in the logger). But I just tested a scriptlet exception filter now and it is cancelling out a scriptlet filter as intended. So I think the only issue/confusion here is that cosmetic exception filters that successfully cancel out cosmetic filters are currently not displayed in logger (which seems to be #127).

**Comment by gorhill** [comment]
> why is that not also the case if a regular cosmetic filter has been cancelled

Well that is still an opened issue. I meant to fix it with the refactoring of cosmetic filtering last fall but it turned out to be more complicated than expected. It was easy to do it for `script:inject` filters though.

**Comment by uBlock-user** [comment]
> The exception #@#script:inject filter is shown, look at the screenshot I posted.

I thought the exception filters started with @@, that's why I called it cancelled and since scriptlet injecttion filters are an extension of cosmetic filters.

**Comment by Ravizz** [comment]
> @uBlock-user : How's that an exception filter ? I thought the exception filters started with @@ as per https://github.com/gorhill/uBlock/wiki/Static-filter-syntax, that's why I called it cancelled and since scriptlet injection filters are an extension of cosmetic filters.

As uBO's syntax is also based on ABP's syntax (from the same link you've provided):

> uBlock Origin ("uBO") supports Adblock Plus ("ABP") filter syntax

then if something is not described in uBO's documentation, then it is described in ABP's documentation, and from ADP's documentation we can read that ADP has:

a) not only blocking rules exception filters (@@): 
https://adblockplus.org/en/filter-cheatsheet#exceptions 

b) but also also element hiding rules exceptions (#@#, #@##): 
https://adblockplus.org/filters#elemhide_exceptions

and from b) link: 

> These exceptions will be applied to [advanced pseudo-selector rules](https://adblockplus.org/filters#elemhide-emulation) as well. 

and from this link we read:

> (Extended CSS selectors (Adblock Plus specific)

and since uBO's syntax is based on ADP's syntax, these exception rules analogically apply to uBO's [Static extended filtering](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-extended-filtering) because it is just enhancement to ADP's (Extended CSS selectors (Adblock Plus specific)

**Comment by Ravizzz** [comment]
https://adblockplus.org/filters#elemhide_exceptions
https://adblockplus.org/filters#whitelist

**Comment by Raaviz** [comment]
> @uBlock-user : How's that an exception filter ? I thought the exception filters started with @@ as per https://github.com/gorhill/uBlock/wiki/Static-filter-syntax, that's why I called it cancelled and since scriptlet injection filters are an extension of cosmetic filters.

As uBO syntax is based on ABP syntax:
https://adblockplus.org/filters#whitelist
https://adblockplus.org/filters#elemhide_exceptions

> @grenzor : I think he means, if you think the user has to be informed that a script:inject filter has been cancelled, why is that not also the case if a regular cosmetic filter has been cancelled.

> uBlock-user : The discrepancy here is that one is shown and the other is not, either show both or show none. Showing only one and not displaying the other begs the question as to why it's being done.

Agree.

**Comment by WowDude** [comment]
> @uBlock-user: How's that an exception filter ? ...

Not only `@@` are exception filters: [[1]](https://adblockplus.org/filter-cheatsheet#exceptions) [[2]](https://adblockplus.org/filters#whitelist) but `#@#` [too](https://adblockplus.org/filters#elemhide_exceptions), as from [uBO doc](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax):

> uBlock Origin ("uBO") supports Adblock Plus ("ABP") filter syntax, so you can refer to  [existing filter syntax documentation from Adblock Plus web site](https://adblockplus.org/en/filter-cheatsheet).

So ADP doc applies for uBO as well, as for now I see that uBO doc has been updated with [#@# info](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-extended-filtering).
