### ISSUE TITLE
Unblocking trouble

### ISSUE THREAD

**Issue by msjacksonville** [gorhill/uBlock#3495]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
There are websites that I try to allow the pop ups, such as coupons.com or CVS.com and other grocery stores to see their weekly ad. You can see the image, how I click on the button to allow the pop ups, but it doesn't allow. I have tried to uninstall, reinstall, clear history & cache also. I have also added the cvs weekly ad to the allowed pages on firefox, under their security settings.

### One or more specific URLs where the issue occurs
https://www.cvs.com/weeklyad
publix.com
coupons.com
[URL(s) for issue on a specific site are **mandatory**]
![20180208_121754](https://user-images.githubusercontent.com/36274706/35988193-b418a740-0cf5-11e8-92c8-cc9f2a3c3989.jpg)
![20180208_121800](https://user-images.githubusercontent.com/36274706/35988196-b45afce4-0cf5-11e8-9180-281a27ecdb9c.jpg)
![capture](https://user-images.githubusercontent.com/36274706/35988231-cce539aa-0cf5-11e8-8193-f08badde8dc7.JPG)
![capture2](https://user-images.githubusercontent.com/36274706/35988233-cd02e3ec-0cf5-11e8-991f-a1a199cf8e46.JPG)
![capture4](https://user-images.githubusercontent.com/36274706/35988234-cd5d765e-0cf5-11e8-9fed-7668a7c09a3b.JPG)
![capture5](https://user-images.githubusercontent.com/36274706/35988235-cd91cb5c-0cf5-11e8-88a8-64416475c5c8.JPG)
![capture6](https://user-images.githubusercontent.com/36274706/35988236-cdaee1e2-0cf5-11e8-9d9b-d91750db0dda.JPG)

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: There are websites that I try to allow the pop ups, such as coupons.com or CVS.com and other grocery stores to see their weekly ad. You can see the image, how I click on the button to allow the pop ups, but it doesn't allow. I have tried to uninstall, reinstall, clear history & cache also.
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: windows 7 professional
- Browser/version: Mozilla Firefox 58.0.1
- uBlock Origin version: uBlock Origin v1.15.4

##### Your filter lists
I have no personal filters. I see the third party filters.

These are listed under whitelist:
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
www.coupons.com
www.cvs.com
www.staples.com

##### Your custom filters (if any)
I have no custom filters.

**Comment by gorhill** [comment]
Your screenshots show you have Firefox's Tracking Protection enabled.

**Comment by msjacksonville** [comment]
Thank you, that helped. I read on Mozilla and not understanding what the correlation is.

**Comment by anewuser** [comment]
This page is for bugs and development. The next time you have any problem, go to [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) and open the link to the support forum where other users can help you figure out what's breaking the site you want to browse.

Since this issue is now solved, please open this page on your browser (open the link from your email) and click on the "Close issue" button below my comment.
