### ISSUE TITLE
Wont Load Website

### ISSUE THREAD

**Issue by PowerPress** [gorhill/uBlock#3496]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Ublock fails to load one specific site with the chrome stating waiting on ublock.

### One or more specific URLs where the issue occurs
https://stockcharts.com/
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
Here is a video: https://screencast-o-matic.com/watch/cFnQ2JoEbS
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Just visit the url https://stockcharts.com/ and watch the video Here is a video: https://screencast-o-matic.com/watch/cFnQ2JoEbS

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Win 10 version 1709 Build 16299.214
- Browser/version: Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- uBlock Origin version: 1.15.2

##### Your filter lists
Default
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
Unable to reproduce.

It's unclear that your issue is with uBlock Origin, note that there were other messages in the status bar, including "Waiting on HTTPS Everywhere" (this does not mean the issue is with HTTPS Everywhere either). I see you are using a lot of extensions, you should try to disable all your other extensions except uBO, restart the browser and see if the issue resolves. In any case, since I can't reproduce, the issue is likely something else specific on your side.

**Comment by Darstion** [comment]
I have the same problem (http://www.guru3d.com, https://derstandard.at, and others).
When I turn uBO off the site loads fine, the problem also occurs with a clean install of the browser and only uBO running.

OS/version: Win 8.1
Browser/version: Vivaldi  1.15.1094.3 (Official Build) (64-bit), based on Chromium 64.0.3282.143
uBlock Origin version: 1.15.2

**Comment by gorhill** [comment]
> When I turn uBO off the site loads fine

Investigate with the logger. uBO merely enforces your rules/filters, so maybe you have some which interfere negatively with the site. All load fine here with default filters/settings.

**Comment by amitai** [comment]
This is not a uBO issue. I was able to reproduce this issue on Firefox with uBO disabled. HTTPS Everywhere was enabled. When I disabled HTTPSE, the problem went away.

**Comment by Hrxn** [comment]
Just ditch HTTPS Everywhere, it's utter crap anyway..
