### ISSUE TITLE
Unable to force style

### ISSUE THREAD

**Issue by giogziro95** [gorhill/uBlock#3498]
### Describe the issue
I'm trying to force a style on every page via _My filters_, but it doesn't seem to work.

Filter: `##*:style(text-decoration-skip-ink: none !important;)`

Interestingly, adding just `##*` makes all pages blank, so it does have an effect while forcing a style doesn't. Also, if the website domain precedes the filter, forcing the style does work (limited to the specified domain).

### One or more specific URLs where the issue occurs

Affects everything.

### Screenshot in which the issue can be seen

N/A.

### Steps for anyone to reproduce the issue

1. Go to the extension settings → _My filters_.
2. Add a filter that forces a style on `##*` like this: `##*:style(/*your CSS here*/)`.

### Your settings

Replicable regardless of the settings.

- OS/version: Manjaro 17.1.3 (Gellivara) KDE
- Browser/version: Chrome 64.0.3282.119 (Stable channel)
- uBlock Origin version: 1.15.2

##### Your filter lists

Irrelevant.

##### Your custom filters (if any)

Irrelevant.

**Comment by uBlock-user** [comment]
You can't make generic filters with `:style`

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#style

> As with the other new cosmetic filtering selectors, the :style can be used only for specific cosmetic filters, i.e. there must be a hostname of entity specified for the filter.

**Comment by giogziro95** [comment]
Uh-oh. All right. Thanks for the response and sorry for my ignorance regarding this.

Closing the issue.
