### ISSUE TITLE
Latest version of Firefox wont allow install.

### ISSUE THREAD

**Issue by StuartB4** [gorhill/uBlock#3499]
Just tried to install the latest version of uBlock in to the latest version of Firefox but it keeps blocking it.
It blocks it because it's not signed.
I click on allow but it still does'nt install.
Any ideas would be appreciated.

![untitled6](https://user-images.githubusercontent.com/16980026/36063449-f28617d0-0e74-11e8-8c06-407e37df29ea.jpg)

![untitled7](https://user-images.githubusercontent.com/16980026/36063450-f863b04a-0e74-11e8-9801-54de2d22a03d.jpg)

My OS is Windows 7 Pro 64bit.
Firefox version is 58.0.1 64bit.
uBlock Version 1.15.4

**Comment by gorhill** [comment]
Install from AMO please.

**Comment by StuartB4** [comment]
Yeah thats fine but what is AMO?

**Comment by cy7yz2rj** [comment]
[addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)

**Comment by StuartB4** [comment]
Ok cy7yz2rj.
Thanks, working now.
