### ISSUE TITLE
Add topics to the GitHub repository

### ISSUE THREAD

**Issue by Smibu** [gorhill/uBlock#3500]
In GitHub, when searching for topic [adblock](https://github.com/topics/adblock) or [ublock](https://github.com/topics/ublock), the topmost result is the obsolete uBlock repo. This happens because uBlock Origin repo has no topics, so it will never appear in any topics listings.

My suggestion is to add at least the topics [ublock](https://github.com/topics/ublock) and [ublock-origin](https://github.com/topics/ublock-origin) and maybe some others to this repo. The obsolete repo has these topics: ublock, blocker, chrome, safari, safari-extension, extension, adblock, firefox, javascript.

**Comment by Hrxn** [comment]
It now has, I think this can be closed?

**Comment by Smibu** [comment]
Yep.
