### ISSUE TITLE
Blocking issue (exception rules used for blocking)

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock#3503]
### Description:
Problem rules:
```
@@||inquisitr.com/wp-content/uploads/*-Social-Media-$image,domain=inquisitr.com
@@||vice.com/images/*-social-media-$image
```
Filters containing the above rules:
```
Fanboy's Annoyance List
Fanboy's Social Blocking List
```

Somehow, uBlock Origin picks out this part of the rules, and uses it as a blocking rule:
`-social-media-$image`
Perhaps it gets confused by the asterisks?

--

### Example URL:
http://www.hotflick.net/u/g/?d=4823857

--

### Changed settings:
I am an advanced user = Enabled
Block CSP reports = Enabled

--

### Version info:
- OS/version: Win8.1Pro,x64
- Browser/version: Pale Moon v27.7.2,x64
- uBlock Origin version: v1.15.4

**Comment by gorhill** [comment]
> Somehow, uBlock Origin picks out this part of the rules, and uses it as a blocking rule:
>     -social-media-$image
> Perhaps it gets confused by the asterisks?

Found in Fanboy's Annoyance List:

    -social-media-$~script,~stylesheet,~xmlhttprequest
