### ISSUE TITLE
Request that goes to "/count?type=" will get blocked by uBlock Origin.

### ISSUE THREAD

**Issue by jeffdagala** [gorhill/uBlock#3505]
**Issue**: Any request that goes to "**_/count?type=_**" will get blocked by uBlock Origin.

**Steps to recreate**:

1. Go to https://api.jquery.com/jquery.get/
2. Open Chrome's dev tools and go to console.
3. Copy and paste this tiny jquery script `$.get("/test/count?type=1");`
4. You will see that there's an issue "**net::ERR_BLOCKED_BY_CLIENT**"

**Expected Result**: It should be 404 because jQuery does not have the specified route.

Screen shot of the logger
![ublock-origin-issue-count-type](https://user-images.githubusercontent.com/1627542/36087534-cb20e1bc-100d-11e8-9e56-c5699d1af0ec.png)

OS/Version: Ubuntu 17.10
Browser/Version: Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
uBlock Origin version: uBlock Origin 1.15.2
uBlock Filters: Default (I just install my uBlock origin)

**Comment by gwarser** [comment]
Static filter /count?type= found in:

    EasyPrivacy

**Comment by jeffdagala** [comment]
Thanks, sorry I did not know there's a list of endpoints that were commonly blocked for privacy.
