### ISSUE TITLE
rarbg is not good

### ISSUE THREAD

**Issue by qwertccc** [gorhill/uBlock#3509]
- OS/version: win10 x64
- Browser/version: chrome v64 x64
- uBlock Origin version: v1.15.2

uBlock filters​​​​​
uBlock filters – Annoyances
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list
CHN: CJX's EasyList Lite
CHN: EasyList China (中文)
CJX's Annoyance List

https://rarbg.is/torrents.php 
can not click anything

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
