### ISSUE TITLE
Shortcut link to dashboard.

### ISSUE THREAD

**Issue by smed79** [gorhill/uBlock#351]
Hi;
it is possibl to add shortcut link to **uBlock icon** to quick access dashboard?

Thanks!

**Comment by gorhill** [comment]
Clicking the title bar in uBlock's popup brings you to the dashboard.

**Comment by SMed79** [comment]
:+1: Solved !

**Comment by SMed79** [comment]
If possibl ... add tooltip text **Show Dashboard** when hover title bar in uBlock's popup.

**Comment by gorhill** [comment]
Tooltip is there already.

**Comment by SMed79** [comment]
! No tooltip for me when mouse pointer hover title bar in uBlock's popup.

![capture d ecran_2015-06-16_22-16-10](https://cloud.githubusercontent.com/assets/1873139/8194778/c3499812-1475-11e5-864f-91fb6ad98f24.png)

**Comment by gorhill** [comment]
> Any idea?

Looks like stock tooltips do not work inside an extension popup in Firefox.

**Comment by SMed79** [comment]
I confirm NOT work on firefox.
Chromium test: 

![capture d ecran_2015-06-16_22-47-19](https://cloud.githubusercontent.com/assets/1873139/8195336/d4d0e730-1479-11e5-896e-479803c26fee.png)

**Comment by harshanvn** [comment]
@gorhill 
Just skimming thorugh old bugs, and found this..
I believe this is no longer an issue in firefox with the upcoming release (v1.4.1). Can be closed..

**Comment by gorhill** [comment]
Thanks; yes I forgot about this issue when I fixed 876c6b3658263b8b2891bbac555a838ea5084ff9.
