### ISSUE TITLE
Include the nocoin filter list

### ISSUE THREAD

**Issue by mnp** [gorhill/uBlock#3511]
### Describe the issue
Coin miners are an increasing problem. There's already 200+ on this guy's list:
https://github.com/hoshsadiq/adblock-nocoin-list/

I suggest this list gets added to the set of default 3rd party ones.

### Your settings

- OS/version: 
- Browser/version: 
- uBlock Origin version:

**Comment by gorhill** [comment]
uBO has its own "Resource abuse" list, enabled by default.

**Comment by mapx-** [comment]
lot more ati mining filters are in [easyprivacy](https://easylist.to/easylist/easyprivacy.txt) (enabled by default in uBo), see `! Mining` section

**Comment by mnp** [comment]
Great, thanks guys!
