### ISSUE TITLE
do you still need to enable and add the rules for 3rd party scripts

### ISSUE THREAD

**Issue by cardassian-tailor** [gorhill/uBlock#3514]
Two comments and a question here. One, it was stated that gorhill no longer used umatrix as ublock origin now provides the features that umatrix once did. Is this true? 

Second. 
When you enable advanced mode, to use dynamic filtering according to the wiki page you are supposed to add these to your rules 

* * 3p-script block
* * 3p-frame block 

However, when you check advanced user and click the ublock icon, third party scripts and iframes are already listed. Is it no longer necessary to add these two rules manually?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
