### ISSUE TITLE
Advertising is not completely blocked

### ISSUE THREAD

**Issue by cg1cz** [gorhill/uBlock#3515]
### Describe the issue
About a week ago uBlockOrigin stopped blocking some advertising on this resource.

### One or more specific URLs where the issue occurs
[http://nnm-club.me](url)

### Screenshot in which the issue can be seen
[http://s01.geekpic.net/di-9W1G0G.png](url)

### Your settings

- OS/version: Windows 7 64-bit build 6.1.7601 OEM License
- Browser/version: Opera 51.0.2830.26
- uBlock Origin version: 1.14.24

##### Your filter lists
uBlock filters 3 991
uBlock filters – Badware risks 7
uBlock filters – Privacy ​​​​​65
uBlock filters – Resource abuse​​​​​ 195
uBlock filters – Unbreak​​​​​ 294
Adblock Warning Removal List 390
EasyList ​​​​​79 690
Adguard Spyware Filters​​​​​ 2 384
EasyPrivacy​​​​​ 14 049
Fanboy’s Enhanced Tracking List​​​​​ 2 342
Malware Domain List​​​​​ 1 130
Malware domains​​​​​ 15 227
Adguard’s Annoyance List​​​​​ 8 561
Fanboy’s Annoyance List​​​​​ 8 852
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​ 68
Fanboy’s Cookiemonster List​​​​​ 8 462
Fanboy’s Social Blocking List​​​​​ 17 776
Peter Lowe’s Ad and tracking server list​​​​​ 2 579
RUS: Adguard Russian Filter​​​​​ 15 783
RUS: RU AdList ​​​​​21 635

**Comment by uBlock-user** [comment]
`nnm-club.me##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)`

**Comment by cg1cz** [comment]
Thank you very much guys!
