### ISSUE TITLE
Personal filters stop working.

### ISSUE THREAD

**Issue by oltodosel** [gorhill/uBlock#3516]
uBlock stops masking elements from personal filters. Happens to all personal filters on all websites.
When I open mini-menu and click on element-picker(pipet) or zapper - menu disappears and nothing else happens.
Restarting the extension solves the issue until it starts acting up again in couple of hours.

- OS/version: Linux 4.15.3-1-ARCH
- Browser/version: Chromium 64.0.3282.140
- uBlock Origin version: 1.15.2

**Comment by gorhill** [comment]
Did you look at the logger as asked in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)?

**Comment by krystian3w** [comment]
Try copy your filters to gist and subscirbe raw version:

https://gist.github.com/

**Comment by oltodosel** [comment]
uBlock stopped reacting even to restart. I reinstalled it, and it seems to work now.
I'll reopen the issue if it occurs again.
