### ISSUE TITLE
Microsoft Outlook (Hotmail.com) blocks e-mails from loading w/ ublock Origin

### ISSUE THREAD

**Issue by Shadesttone** [gorhill/uBlock#3517]
As the Subject says, I cannot view e-mails in my Hotmail account unless I specifically disable uBlock Origin. That's the only fix I can find for it. I'm not sure how much more information I can give.

- OS/version: Windows 7 64-bit
- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.6

**Comment by thekingofspain** [comment]
Outlook.com changed their ad banner i think last week and my personal rule for blocking ads no longer works.  Check to make sure that you do not have personal rule for outlook.com.  My guess is you have a personal rule that was pretty open in blocking dom elements and the old rule is doing bad things on the new outlook.com site.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
