### ISSUE TITLE
"My filters" not refreshed at start

### ISSUE THREAD

**Issue by SunStroke74** [gorhill/uBlock#3518]
Windows 8.1
Latest Firefox and uBlock

I tried to sync uBlock settings between my comps automatically by placed storage.js from browser-extension-data in cloud. After changes settings on one comp, on another comp at Firefox start "Settings", "3-party filters", "My rules", and "Whitelists" changes and applyed. But "My filters" changes and NOT applyed, like uBlock used cached info instead. If i change "My filters" and click "Apply" button, changes applyed as expected.

Can this be changed to reread and reapplyed "My filters" at start, so all settings can be synced that way? I think, My Filters is not so big to not reapplyed it at each start.

PS. Sorry for my poor English.

**Comment by gwarser** [comment]
Filters are saved inside indexedDB. 
`/storage/default/moz-extension+++XXXXXXXXXXXXXX/idb/XXXXXXXXXXXXXX.sqlite`

**Comment by SunStroke74** [comment]
Thanks! Now i can fully sync uBlock data. Another way is delete this folder at computer boot to force uBlock rebuild cache with settings from storage.js at first Firefox start after reboot or power on.

**Comment by gorhill** [comment]
> Can this be changed to reread and reapplyed "My filters" at start

I won't explicitly support such trick to share configurations. If it works, it's just luck, but I can't guarantee that this will always be the case.
