### ISSUE TITLE
[Enhancement] Allow for comments in strict domain blocking pages

### ISSUE THREAD

**Issue by riking** [gorhill/uBlock#352]
Proposed UI:

![image](https://cloud.githubusercontent.com/assets/627891/8153053/8f565f9a-12db-11e5-9e79-61ed669391e9.png)

I think this would inflate the size of the filter lists, but it might be worth it for the UI?

Note: This change requires cooperation from filter list authors

**Comment by lewisje** [comment]
It would also require all other major ABP-style extensions to start supporting this, because comments inline with filters are not supported anywhere at this moment.

**Comment by anewuser** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

> Submit *bugs/issues only*. 
> Do *NOT*: Submit design ideas.
> Do *NOT*: Submit feature requests.
> Do *NOT*: Submit "revolutionary ideas".

**Comment by gorhill** [comment]
In 0.9.9.0, the filter list(s) from which a filter comes from is show below the filter: <https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking>.
