### ISSUE TITLE
fail block ads and console error

### ISSUE THREAD

**Issue by raingart** [gorhill/uBlock#3522]
### Describe the issue

as I understood the reason for the unstable Internet connection. (in the console was https://www.chromestatus.com/feature/5718547946799104). Can I find out if there is a way around the limitation of chromium? Thank you in advance. And sorry if I bothered.

### One or more specific URLs where the issue occurs

http://finance.liga.net/economics/2018/2/16/news/56766.htm

### Screenshot in which the issue can be seen
![screenshot from 2018-02-16 19-56-19](https://user-images.githubusercontent.com/13064767/36321808-ca9b3046-1353-11e8-8cf0-7750ff6a96fb.png)

- OS/version: 
`Linux hostname 4.15.3-1-ARCH  x86_64 GNU/Linux`
- Browser/version: 
`Chromium Version 64.0.3282.167 (Developer Build) (64-bit)`
- uBlock Origin version: 
`v1.15.2`

##### Your filter lists

```
uBlock filters – Resource abuse
EasyList
Fanboy’s Cookiemonster List
RUS: RU AdList
```

##### Your custom filters (if any)
https://easylist-downloads.adblockplus.org/cntblock.txt

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
