### ISSUE TITLE
Usability: equate/drop http: and https: in dynamic URL filtering rules

### ISSUE THREAD

**Issue by blakestorm11** [gorhill/uBlock#3524]
As the title says, it would be nice if dynamic http: rules applied to https: and vice versa (or rather just drop the protocol part), as scenarios to URL filter a resource for only one of the two would seem rather esoteric, whereas having stuff slip by depending on your connection security status can be an annoyance, and the obvious workaround (manually doubling the rules for every URL) is both tedious and hard to remember to do.

I've seen you mention that you want to keep dynamic URL filtering rules very simple, but I think dropping the protocol part would be easy enough to implement and actually simpler for users. Sure, this could already be done with static filters, but isn't that less efficient?

**Comment by gorhill** [comment]
I will decline this. Given how usage of `http:` is more and more rare, I don't see the requirement to create two distinct rules to be a burden, especially that the primary reason URL filtering exists at all is to be a tool for filter list maintainers, in which case the rules are temporary.
