### ISSUE TITLE
Localhost 3rd-party list won't update / also can't add another localhost list

### ISSUE THREAD

**Issue by Ravizz** [gorhill/uBlock#3527]
Not sure if it's an uBO's issue but in case it is...

### Describe the issue

As per https://github.com/gorhill/uBlock/issues/2922 since several months I use http://www.wampserver.com/en/ to load my custom list to uBO 3rd-party pane, generally, as I keep developing the list, I didn't notice any problems with adding/using/updating (even XX times per day) such list, always after adding another bunch of new filters onto the list, I always use "force update" clock'icon button and then press big orange Update Now button, and the list always gets updated with no problems, but this morning, after leaving my computer/Firefox turned on overnight as always, the list won't update anymore, it looks like as it has been updated but it is not, the list still contains the old content/filters. Also can't add another localhost lists with a link like: `http://localhost/local_filters_lists_uBO/MyList.txt`, I have to add some unknown characters at the end like: `?_=210988` generated by uBO to be able to add the list. On the other hand, the other lists (non-localhost) update (force-update) without any problems. Neither:
- closing & reopening uBO's control panel tab 
- nor disabling/enabling uBO 
- nor restarting WampServer

is fixing the issue, I guess the issue can be simply "fixed" by:
- remove the list, and then add the list again using a link with some odd/unknown option/numbers added at the end: (`http://localhost/local_filters_lists_uBO/MyList.txt?_=210988`)
- using the uBO's clear cache button 
- or by restarting the browser. 

But that's just a workaround, not a real fix, unless the uBO's clear cache button is accepted as the fix?

### One or more specific URLs where the issue occurs

1_ When I try to force update the list (click "force update" + "update now" buttons)  I notice in the logger (Behind-the-scene) is showing:
`09:01:18				xhr	http://localhost/local_filters_lists_uBO/MyList.txt?_=210988`

The list won't update.

2_ When I try to force update a different (non-localhost) list  (click "force update" + "update now" buttons)  I notice in the logger (Behind-the-scene) is showing:
`09:07:21				xhr	https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt?_=210988`

The list will update.

3_ When I copy the list's url from 3rd-party lists pane it's showing as:
`moz-extension://12d2c9e2-2247-4d5c-af2c-a8214037019f/asset-viewer.html?url=http://localhost/local_filters_lists_uBO/MyList.txt`

4_ When I try to clone/add the list by pasting this link in 3rd-party lists pane text field:
`http://localhost/local_filters_lists_uBO/MyList.txt`

The list is not added to uBO and the logger (Behind-the-scene) is showing nothing (is that expeced?)

5_ When I'm pasting this into the browser's adress bar and go to it
`http://localhost/local_filters_lists_uBO/MyList.txt`

It is showing the newest/updated list.

6_ When I'm clicking at the list in uBO's 3rd-party pane (the link: `moz-extension://12d2c9e2-2247-4d5c-af2c-a8214037019f/asset-viewer.html?url=http://localhost/local_filters_lists_uBO/MyList.txt`)

It is  showing the old (non-updated) list.

7_ When I try to clone/add the list by pasting this link in 3rd-party lists pane text field:
`http://localhost/local_filters_lists_uBO/MyList.txt?_=210988`

 I notice in the logger (Behind-the-scene) is showing:
`09:14:02				xhr	http://localhost/local_filters_lists_uBO/MyList.txt?_=210988&_=210988`

And list is added correctly as the newest/updated version.

### Steps for anyone to reproduce the issue

Unable / too rarely to reproduce as for now / a random issue.

### Your settings

- OS/version: Windows 7 SP1 U 64 PL
- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.6
- WampServer Version 2.4
- NanoDefender 13.31
- AdsBypasser userscript
- AntiAdware userscript
- bunch of private userscripts
- old browser profile
- Greeasemonkey 4.2 and 13 other active browser extensions

##### Your filter lists

<details>

 <summary>My lists</summary>

```
! #"My filters"
! #http://localhost/local_filters_lists_uBO/MyList.txt
! #NanoDefender Browser Addon + it's filters lists:
! #NanoBase
! #NanoTimer
! #NanoWhitelist
! #uBlockProtectorList
! #end of  NanoDefender filters lists
! #AdsBypasser userscript
! #AntiAdware userscript
! #uBlock filters
! #uBlock filters – Privacy​​​​​
! #uBlock filters – Resource abuse​​​​​
! #uBlock filters – Unbreak
! #Adblock Warning Removal List
! #Adguard Base Filters
! #EasyList
! #Adguard Spyware Filters (as localhost because I did modifications/optimalizations)
! #Adguard Annoyance List
! #EasyPrivacy
! #Fanboy’s Enhanced Tracking List
! #Fanboy’s Cookiemonster List
! #Peter Lowe’s Ad and tracking server list
! #POL: polskie filtry do Adblocka i uBlocka
! #http://adblocklist.org/adblock-pxf-polish.txt
! #hpHosts’ Ad and tracking servers (as localhost because I did modifications/optimalizations)
! #https://raw.githubusercontent.com/michaeltrimm/hosts-blocking/master/_hosts.txt (as localhost because I did modifications/optimalizations)
! #https://mrsatterly.com/abp_filters.txt (as localhost because I did modifications/optimalizations)
! #http://mrc.pl/adblock.txt
! #http://www.bsi.info.pl/filtrABP.txt
! #http://www.niecko.pl/adblock/adblock.txt​
! #https://raw.githubusercontent.com/thoughtconverge/abf/master/abf.txt​
! #Adblock & uBlock polish filter - AdGuard supplement​
! #Adblock Polska​
! #AlleBlock
! #Anti popads.net​
! #Block-EU-Cookie-Shit-List​
! #Blockzilla​
! #EasyList Polish​
! #Fake-News List
! #Fanboy's Polish​
! #I don't care about cookies​
! #KAD - Przekręty​
! #NoCoin Filter List​
! #Polskie filtry ciasteczkowe
! #Polskie filtry wewnętrzne
! #Prebake - Filter Obtrusive Cookie Notices
! #Privacy filters​
! #uBlock Filters +​
! #uBO-Personal-Filters​
```

</details>

##### Your custom filters (if any)
A bunch of private filters in "My filters"

At the time of writing this, I've tried to update the other locaclhost list to check if they are affected too and...after trying to update one of the other custom localhost list, the issue has gone away, all the custom localhost lists have begin to udpate correctly? Wth? Anyway leaving it open and up to @gorhill's decision to close or not, as he may still find a bug here, and also the issue may happen again.

_Added:_ OK that is strange, the issue is back again ( I haven't restarted my browser, that's still the same session). So the issue occurs randomly: is randomly appearing and dissappearing. In this case I've tried the purge cache uBo button and it has worked, I'll try to keep the browser session as long as possible to see if that "purge cache" soultion fix the issue definately (atleast for the current browser session), or it will get back again soon and I'll have to restart the whole browser.

**Comment by gorhill** [comment]
> Over 30 custom lists (5 of them are localhost)

IndexedDB imposes limit on storage size, depending on factors such as the space left on disk. Be sure this is not the issue you are facing: reduce the number of filter lists and see if this fixes the update issue.

**Comment by Ravizz** [comment]
OK: 

- sorry for not listing all the filters lists I do use, I've updated my 1st comment (see "My lists" spoiler), 
- my total count of active filters being showed in uBO 3rd-party pane is:  
`static (network) filters 106 796 + cosmetic filters: 86 956`, so I'm definately not from these users which use all the lists from https://filterlists.com/ / which have 2.000.000+ filters enabled, so I'm guessing that my filters lists don't hit the IndexedDB limit?
- several minutes after the issue began to appear I got a Windows low memory warning like this:
https://zipso.net/fix-low-memory-warnings-in-windows-vista-xp-and-windows-7/ could be it the reason of hitting IndexedDB size limit? I have 4 GB RAM + 4GB SWAP pagefile (min 4096, max 4096). But you were more like talking about the space left on disk, not RAM, but on the other hand SWAP resides on disk, but I have several GB of free space on Windows & Firefox partition.

**Comment by gorhill** [comment]
> so I'm guessing that my filters lists don't hit the IndexedDB limit?

See <https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits>.

**Comment by gorhill** [comment]
> Also can't add another localhost lists with a link like: `http://localhost/local_filters_lists_uBO/MyList.txt`

That is normal if the list is already imported. That would explain why adding characters at the end cause the list to be imported, from uBO's point of view it is a different URL and thus a different filter list.

**Comment by Ravizz** [comment]
- I had 5GB of free space on my 30GB Windows partition, now after I've disabled mySQL database service (which is a part of WAMP server) I have 8,6 GB of the free space.
- I have had and still have 529MB of the free space on my 2GB Firefox's profile dedicated partition

So:
- my global limit of Firefox's profile partition is 529MB x 50% = 264,5MB
- my group limit is 264,5MB x 20% = 52.9 MB
- in my profile > extensions-data folder I have ublock0.sqlite file of 31.6MB
- in my profile > storage folder it takes 51,5MB

And now looking at that 51,5MB storage used vs 52.9 MB limit, it seems that it sometimes hits the limit, I guess I should make my Firefox's profile dedicated partition larger (for ex. 4GB), and also it seems unrealted to Windows low memory warnings which is another issue which I probably have already solved by disabling unused WAMP's mySQL database service.
