### ISSUE TITLE
Dynamic filtering UI broken  + unable to update uBO

### ISSUE THREAD

**Issue by Ravizz** [gorhill/uBlock#3528]
### Describe the issue

I'm not sure if the issues deserve to be reported as separate because they have happened at the same time: while/after updating from 1.15.6 to 1.15.8 on two different profiles (old [issue 2] and new [issue 1]), so they might be related (or not).

**Issue 1 (solved):** "in uBO 1.15.8/1.15.10 (on my 2nd FF's profile)" Dynamic filtering UI broken: column nr 1 missing + half of the UI missing + column nr 2 broken (mouse clicking is taking no effect, colors on mouse hover don't appear). I've searched the repository issues for a phrase: https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=in%3Atitle+dynamic+filtering , it has returned 45 results, but found nothing similiar, am I missing something obvious? My uBO settings attached: 
[ublock-kopia-zapasowa_2018-02-20_17.45.49.txt](https://github.com/gorhill/uBlock/files/1741039/ublock-kopia-zapasowa_2018-02-20_17.45.49.txt)
_Edited: Also have updated uBO on my test profile from 1.15.8 to 1.15.10 but still the issue 1 is present._
_Edited: OK I've just read uBO WiKi documentation again, and it seems that Dynamic filtering is activated after enabling "I'm advanced user" in uBO's settings pane", and since I use NanoDefender which requires this setting to be enabled - that is obvious it should be enabled but it was not due to this bug: https://github.com/gorhill/uBlock/issues/3387 As for the fresh profile, I've just forgot to enable it, and it turned out while installing NanoDefender._

**Issue 2 (solved):**  "can't update from 1.15.6 to 1.15.8 (on my 1st FF's profile)" I've tried to reproduce the issue 1 on my main FF's profile, but after I've updated uBO from 1.15.6 to 1.15.8 in Firefox's addons panel, after the update completed, it still is showing as 1.15.6, even after restarting the browser. My settings on this profile are the same as here: https://github.com/gorhill/uBlock/issues/3527#issue-298517501. I just add that first time I've been seeing some strange behaviour while updating uBO: the blue updating bar has hanged long time at 80%, and then after 10s it has finally showed 100% but the blue bar has remained (not sure/ don't remember if the blue bar should remain or should dissappear) anyway then I've just restarted the browser), but uBO is still 1.15.6.
_Edited: ok as for the Issue 2 - solved - I've repeated the update process and have been successfully updated to uBO 1.15.10 (this time update process has been quick and lagless (2s) and as for the blue bar, this time the blue bar has dissappeared once the update process has finished). All that mean that was probably some nasty lag/crash during the first update...I don't know if the lag was at Mozilla's side or at my side, or if it was anything else caused failure the first time._ 

### One or more specific URLs where the issue occurs

Any, but for example: https://www.heise.de or https://www.google.pl

### Screenshot in which the issue can be seen

a_ Test profile (the issue is present, uBO 1.15.8 / 1.15.10
b_ Also a brand new fresh profile, uBO 1.15.10:
![capture_001_20022018_171926](https://user-images.githubusercontent.com/35421792/36435565-46e6d37e-1662-11e8-82e2-07339ce9849a.png)

Main profile (the issue not present uBO 1.15.6 / 1.15.10):
![capture_002_20022018_172430](https://user-images.githubusercontent.com/35421792/36435848-0ae2b162-1663-11e8-9f14-d496ea726fb7.png)

### Steps for anyone to reproduce the issue

I've just tried to help to reproduce the issue and do steps as provided here on the screenshoot: https://github.com/gorhill/uBlock/issues/3526#issuecomment-366977765, so I've just:
1. launched my Firefox's test profile (no addons, just uBO) 
2. opened uBO's control pane
3. went to Settings tab
4. clicked Restore default settings button
5. now the uBO should have restarted, which mean it's Control Pane tab should close & the icon should dissappear and then reappear
6. and indeed, the Control Panel tab has gone, the icon too, but it seems that uBO has died because the icon has not reappeared
7. so restarted Firefox, the icon has been back
8. then went to https://www.heise.de
9. clicked at uBO's icon and opened Dynamic Filtering UI as on the gorhill's screenshot
10. noticed that Dynamic filtering UI broken: column nr 1 missing + half of the UI missing + column nr 2 broken (mouse clicking is taking no effect, colors on mouse hover don't appear). 
11. disabling/enabling uBO in the browsers addons panel hasn't helped
12. restarting the browser hasn't helped
13. I guess the most likely I can fix the issue by creating a fresh profile, but I've thought it might be worth reporting anyway...._EDITED: have tried right now on a brand fresh profile - it hasn't helped, wth?_
14. in my old main profile the issue is not present
15. on Opera 51.0 the issue is not present

### Your settings
- screen resolution 1280x1024
- Windows DPI: medium 125% (Control Panel > Looking and Personalisation > Display)
- OS/version: Windows 7 SP1 U 64 PL
- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.8 / 1.15.10

##### Your filter lists

Default

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
> sometimes it is not due to this this bug: #3387

Unrelated, "I am an advanced user" is not saved as an advanced settings.

Regarding "can't update uBO", this is outside uBO's control: the browser updates extensions, uBO has no code to update itself.

**Comment by Ravizz** [comment]
Thanks for the checking/feedback

> @gorhill: Unrelated, "I am an advanced user" is not saved as an advanced settings.

Yes, I was also thinking about that, wasn't sure at 100% if it was related to this bug or not, but since I was sure I had this option enabled in the past due to use of Nano Defender, I'm wondering how the option turned out to be disabled, or better - what/who/when disabled it, as I:
- don't remember me disabling this option
- have no reason to disable it - since I use Nano Defender which I have always enabled and which requires it to be enabled
- my last uBO backup restore is from 07.02.2018, and this backup has "I am an advanced user" enabled

Anyway still possible that it was me who disabled it, maybe:
- it was mistakenly
- or I disabled it (don't know why, maybe was checking something), and then forgot to enable again

I ju

> @gorhill : Regarding "can't update uBO", this is outside uBO's control: the browser updates extensions, uBO has no code to update itself.

OK.
