### ISSUE TITLE
segfaults upon install of uBlock0 on grsecunoff kernel-based Linux

### ISSUE THREAD

**Issue by miroR** [gorhill/uBlock#3530]
The issue is described much better than in words (I'd hope) at:

Pale Moon and uBlock0 on a grsec-hardened kernel
https://www.croatiafidelis.hr/foss/cap/cap-180220-PaleMoon-uBlock0/

and I've posted about it my detailed (non-expert) analysis at:

Installing uBlock Origin breaks Pale Moon on grsec-hardened kernel
https://forum.palemoon.org/viewtopic.php?f=46&t=18389

- OS/version:  Devuan Linux
- Browser/version: Pale Moon 27.7.2
- uBlock Origin version: 1.15.6
It's late night in Europe, and I've worked all day on this, tired, I hope if my opening post of this issue is lacking, I can be forgiven.

**Comment by gorhill** [comment]
Segfault is a browser issue, please report to browser devs. uBO is HTML/CSS/JS, it's not supposed to crash the browser.
