### ISSUE TITLE
Cnet stopped working in the last couple days.

### ISSUE THREAD

**Issue by risner** [gorhill/uBlock#3532]
### One or more specific URLs where the issue occurs

https://www.cnet.com/

### Screenshot in which the issue can be seen

pop up of:
https://www.cnet.com/
<img width="599" alt="cnet" src="https://user-images.githubusercontent.com/8061434/36458666-0188730c-167e-11e8-97fb-b653d40008f9.png">

### Steps for anyone to reproduce the issue
Turn on uBlock and go to 

https://www.cnet.com/

### Your settings

- OS/version: Macos 10.13.3
- Browser/version:  59.0b6
- uBlock Origin version: 1.15.10

Adblock Warning Removal List​​​​ enabled
Whitelists:
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
facebook.com
moz-extension-scheme
opera-scheme
retailerservices.alliance-games.com
vivaldi-scheme
www.speedtest.net

I am an advanced user (required reading) enabled
Block remote fonts enabled (but tried without)

rest of the settings 

##### Your custom filters (if any)

No person ones, but I just put all them here. The X used out of Y should show the enabled ones.
71,314 network filters ＋ 44,596 cosmetic filters from:

        My filters​​​​​0 used out of 0​​​​
        uBlock filters​

​​​​4,033 used out of 4,059​​
​​
uBlock filters – Annoyances​​​​​​​​​
uBlock filters – Badware risks​
​​​​7 used out of 7​​
​​
uBlock filters – Experimental​
​​
​​​​​​
uBlock filters – Privacy​​​​​62 used out of 65​​
​​
uBlock filters – Resource abuse​​​​​203 used out of 205​​
​​
uBlock filters – Unbreak​​​​​292 used out of 296​​

    ​​ 

Ads (2)

    Adblock Warning Removal List​

​​​​397 used out of 402​​
​​
Adguard Base Filters​
​​
​​​​​​
Adguard Mobile Filters​
​​
​​​​​​
EasyList​
​​​​80,062 used out of 80,292​​

    ​​ 

Privacy (1)

    Adguard Spyware Filters​

​​
​​​​​​
EasyPrivacy​
​​​​14,126 used out of 14,281​​
​​
Fanboy’s Enhanced Tracking List​

    ​​​​​​​​ 

Malware domains (2)

    Malvertising filter list by Disconnect​​​​​​​​​
    Malware Domain List​​​​​1,130 used out of 1,146​​

​​
Malware domains​
​​​​15,558 used out of 15,558​​
​​
Malware filter list by Disconnect​​​​​​​​​
Spam404​

    ​​​​​​​​ 

Annoyances

    Adguard’s Annoyance List​

​​
​​​​​​
Fanboy’s Annoyance List​
​​​​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
​​​​​​​​
Fanboy’s Cookiemonster List​
​​​​​​​​
Fanboy’s Social Blocking List​

    ​​​​​​​​ 

Multipurpose (1)

    Dan Pollock’s hosts file​

​​​​​​​​
hpHosts’ Ad and tracking servers​
​​​​​​​​
MVPS HOSTS​
​​​​​​​​
Peter Lowe’s Ad and tracking server list​
​​​​2,585 used out of 2,585​​​​Regions, languages

    ara: Liste AR​

​​​​​​​​
BGR: Bulgarian Adblock list​
​​​​​​​​
CHN: CJX's EasyList Lite​
​​
​​​​​​
CHN: EasyList China (中文)​
​​​​​​​​
CZE, SVK: EasyList Czech and Slovak​
​​​​​​​​
DEU: EasyList Germany​
​​​​​​​​
DNK: Schacks Adblock Plus liste​
​​​​​​​​
EST: Eesti saitidele kohandatud filter​
​​​​​​​​
FIN: Finnish Addition to Easylist​
​​​​​​​​
FRA: EasyList Liste FR​
​​​​​​​​
GRC: Greek AdBlock Filter​
​​​​​​​​
HUN: hufilter​
​​​​​​​​
IDN: ABPindo​
​​​​​​​​
IRN: Adblock-Iran​
​​​​​​​​
ISL: Icelandic ABP List​
​​​​​​​​
ISR: EasyList Hebrew​
​​​​​​​​
ITA: ABP X Files​
​​​​​​​​
ITA: EasyList Italy​
​​​​​​​​
JPN: ABP Japanese filters (日本用フィルタ)​
​​​​​​​​
JPN: Adguard Japan Filter​
​​
​​​​​​
KOR: Korean Adblock List​
​​​​​​​​
KOR: YousList​
​​​​​​​​
LTU: Adblock Plus Lithuania​
​​​​​​​​
LVA: Latvian List​
​​​​​​​​
NLD: EasyList Dutch​
​​​​​​​​
POL: polskie filtry do Adblocka i uBlocka​
​​
​​​​​​
POL: polskie filtry do uBlocka uzupelnienie​
​​​​​​​​
RUS: Adguard Russian Filter​
​​
​​​​​​
RUS: RU AdList​
​​
​​​​​​
spa, por: Adguard Spanish/Portuguese​
​​
​​​​​​
spa: EasyList Spanish​
​​​​​​​​
SVN: Slovenian List​
​​​​​​​​
SWE: Frellwit's Swedish Filter​
​​​​​​​​
TUR: Adguard Turkish Filter​
​​
​​​​​​
VIE: ABPVN List​
​​​​​​​​

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
