### ISSUE TITLE
Chrome: 'Enable network service' breaks logger

### ISSUE THREAD

**Issue by MNGrrrl** [gorhill/uBlock#3534]
### Describe the issue

After enabling 'Enable network service' in Chrome (URL: 'chrome://flags'), Logger no longer shows /all/ network requests. Blocked requests are still shown. 
![netsvc_disabled](https://user-images.githubusercontent.com/24402536/36466228-9426efd4-169e-11e8-8442-10a2ae10f7f1.png)
![netsvc_enabled](https://user-images.githubusercontent.com/24402536/36466231-980492a0-169e-11e8-84be-19284ba6741b.png)

### One or more specific URLs where the issue occurs

Any URL
https://www.google.com

### Screenshot in which the issue can be seen

N/A

### Steps for anyone to reproduce the issue

1. Open Chrome.
2. Type 'chrome://flags' into the URL bar (without quotes).
3. Search for 'Enable network service' and enable it (without quotes).
4. Restart Chrome.

### Your settings

- OS/version: Windows 8.1
- Browser/version: Version 64.0.3282.167 (Official Build) (64-bit
- uBlock Origin version: v1.15.7.3 (DEV version)
- All plugins but uBlock Origin were disabled, problem persisted.
 
##### Your filter lists

All except: uBlock filters – Experimental & Regions, languages

##### Your custom filters (if any)

! https://www.xaprb.com/blog/2005/10/26/adblock-patterns/
/\bads\b|2o7|a1\.yimg|adbrite|adclick|adfarm|adrevolver|adserver|adtech|advert|atdmt|atwola|banner|bizrate|blogads|bluestreak|burstnet|casalemedia|coremetrics|doubleclick|falkag|fastclick|feedstermedia|googlesyndication|hitbox|httpads|imiclk|intellitxt|js\.overture|kanoodle|kontera|mediaplex|nextag|pointroll|qksrv|rightmedia|speedera|statcounter|tribalfusion|webtrends/
! Amazon.com - blocks sponsored ad 
www.amazon.com###sponsoredProducts2_feature_div
! heyephiphora.com - block beggar overlay
heyepiphora.com##[id^="spu-"]
! 11/26/2017, 11:13:53 PM behind-the-scene
||www.cnet.com/service-worker.js$script,domain=behind-the-scene
! Reddit.com - disable fonts that look bad with cleartype off
||www.redditstatic.com/*$font,domain=www.reddit.com
@@||www.redditstatic.com/desktop2x/fonts/icon/*$font,domain=www.reddit.com
! 12/9/2017, 6:52:40 PM www.ranker.com
||*.g00.ranker.com/g00/*/*arg_$/$/$/$/$?i10c.ua=1$subdocument
! 2/16/2018, 12:24:32 AM www.pjstar.com
www.pjstar.com###wrapper
! 2/19/2018, 12:16:13 PM www.amazon.com
www.amazon.com##.a-spacing-large.a-alert-warning.a-alert.a-box
! 2/19/2018, 12:36:39 PM www.amazon.com
www.amazon.com###risk-container
! 2/20/2018, 7:07:36 PM c4dcafe.com
||c4dcafe.com/ipb/uploads/css_built_115/*_stickynotes.css.*$stylesheet,first-party
! 2/20/2018, 7:07:36 PM c4dcafe.com
||c4dcafe.com/ipb/uploads/css_built_115/*$stylesheet,first-party
! 2/20/2018, 9:05:05 PM www.reddit.com
www.reddit.com###onboarding-splash
! 2/20/2018, **** FUCK YOU cnet.com ***
www.computerworld.com###teads0 > iframe
www.computerworld.com##.sm-screen.teads-inread
www.cnet.com###videoPlayer1
www.cnet.com##.sm-screen.teads-inread > div
www.cnet.com##.sm-screen.teads-inread
www.cnet.com###article-body > .col-4
www.cnet.com######[a-z]{23}
||g00.cnet.com/*^$script
||g00.cnet.com/*^$xmlhttprequest
||g00.cnet.com/*^$inline-script
||cnet.com/g00*^$inline-script
www.cnet.com##.popOut.videoContainer

**Comment by gorhill** [comment]
Report to Chromium devs please. uBO uses webRequest listeners, if these are no longer being fed with event data, there is nothing uBO can do.

**Comment by Ravizz** [comment]
I've tried on Opera 51.0 & uBO 1.15.10, but after step 4:
1) Opera has crashed and has been saying that it'll try to recover automatically, then it has restarted automatically
2) Opera has crashed again and has been saying again that it'll try to recover automatically, then it has restarted automatically again
3) Opera has crashed again and has been saying again that it'll try to recover automatically, then it has restarted automatically again
4) Opera finally has recovered with all the extensions disabled
5) I've disabled the network service and clicked restart button.
6) Opera has restarted
7) I've enabled uBO again
8) The end of the story about messing with the experimental newtork service feature on Opera

**Comment by uBlock-user** [comment]
It's not complete in Chrome yet. Do not enable it.
