### ISSUE TITLE
[Firefox] Bring back dev channel versions

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#3538]
On February 5th, 2018, I received an email from Firefox Add-ons Team:

> Hello,
> 
> You’re receiving this message because you’re an add-on developer registered on AMO (addons.mozilla.org) and you are using the beta versions feature in at least one of your add-ons. We want to inform you about major changes coming to this feature.
> 
> The add-ons ecosystem is very complex, which makes managing AMO code significantly difficult. Newer developments have caused certain feature sets to overlap and become nearly redundant. As a way to reduce complexity on AMO and leverage existing features, we’ll stop supporting beta versions for add-ons.
> 
> As an alternative to beta versions, we recommend using the self-distributed versions feature instead. You can create an self-hosted version branch for your beta versions that you can distribute on your own. Automatic updates would also need to be managed by you. You can find more information about signing and distributing self-hosted versions on [MDN web docs](http://addons-server.readthedocs.io/en/latest/topics/api/signing.html).
> 
> Once this change is deployed, beta versions will not appear on listing pages anymore. Current beta version users will update to the stable add-on update branch once a higher version of your add-on is available. We plan to deploy this change on February 22, 2018.
> 
> Regards,
> 
> The Add-ons Team

At this point I have nothing to deal with self-hosted versions. Also, I am confused as to whether I can really use self-hosted for development builds while the stable release is hosted on AMO, my understanding had been that an extension [cannot be both on AMO _and_ self-distributed](https://developer.mozilla.org/en-US/Add-ons/Distribution#Signing_your_add-ons):

> you're given a choice between listing on AMO or self-distribution

The reference documentation given in the email is <http://addons-server.readthedocs.io/en/latest/topics/api/signing.html>. It is suggested to whether use a Node.js utility or directly use a sign-in API.

I do not want Node.js dependencies, I prefer the bash script and/or Python script approach, which are already being used for build purpose.

In any case, at this point I would appreciate help in resolving this.

<sub>Please keep the comment for what **brings the issue closer to resolution** -- anything else will be considered noise and unwelcome (i.e. no bickering here about Mozilla etc.)</sub>

**Comment by jspenguin2017** [comment]
As far as I understood, one extension can either be listed or unlisted, but you can change the ID so the dev build is treated as "another extension". You can definitely host it on GitHub, it's been done by Violentmonkey for a long time. 

It's one-liner (almost) with a Node.js script: https://github.com/NanoAdblocker/NanoBuild/blob/master/lib/addons-server.js#L30
For other languages you'll need to learn and understand how to calculate `jwt-token` which seems to be a pain to me. 

I know there is the meme about downloading half the Internet in Node modules, but honestly that's too exaggerated, Node.js is way faster than Python, not even close, even PyPy.js is 3 times faster than CPython. 

![image](https://user-images.githubusercontent.com/7283682/36548527-bee346ae-17ad-11e8-815c-296f98de0abd.png)

**Comment by gorhill** [comment]
> you can change the ID so the dev build is treated as another extension

The feedback I received when I created an extension with a different id is:

> Please submit your development builds as self-hosted versions to your original add-on.

**Comment by jspenguin2017** [comment]
Did you choose unlisted when uploading the dev build?

**Comment by gorhill** [comment]
I can't remember.

**Comment by FatOrangutan** [comment]
>I can't remember.

I found your extension on the Recently Updated queue that day, so you must have chosen 'listed.' Unlisted ones don't appear there.

**Comment by gorhill** [comment]
[This is informative](https://discourse.mozilla.org/t/simultaneously-providing-amo-and-self-hosted-updates/24108?u=gorhill):

> When I upload a new version of my addon, I can choose whether I want to distribute the update via AMO or if I want to self-host it.
> 
> My question is about what happens with published updates when I am publishing a new update to an extension with the same id but via a different distribution option.

Answer:

> If your self-hosted files have an update_url defined in them, then it’s simple: AMO versions update to new AMO versions and self-hosted versions update to new self-hosted versions. You can update either channel whenever you want without affecting the other.

**Comment by jspenguin2017** [comment]
I guess that would work too, but the risk of clicking the wrong button is too high, and it's too easy to get confused. And if it goes wrong it breaks the stable version. 

I think it means this button but I never tried. 
![image](https://user-images.githubusercontent.com/7283682/36556698-5339b90e-17c3-11e8-8b0f-8aa706361a1b.png)

Mozilla doesn't screen unlisted extension, they won't care if you have a separate unlisted extension for dev build or whatever.
