### ISSUE TITLE
wix.com popups persisting even when fully blocked

### ISSUE THREAD

**Issue by 2SI3NX** [gorhill/uBlock#3539]
Can anyone try to reproduce this?

website link: http://www.webdesigndev.com/wordpress-themes/
wix.com popup keeps fucking popping up.  Its the only issue ive had so far.

Ive even enabled 
uBlock filters – Annoyances
Adguard’s Annoyance List
Fanboy’s Annoyance List

**Comment by mapx-** [comment]
for other filter issues report here:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by 2SI3NX** [comment]
Nevermind, i had to restart the browser and now it blocks.
