### ISSUE TITLE
Can't open top right Google Apps, Notifications or Account 'buttons' in Gmail (Firefox)

### ISSUE THREAD

**Issue by paulderdash** [gorhill/uBlock#354]
Not so tech savvy, so unsure if this is a filter or uBlocko issue, but I am unable to left click open the above without disabling uBlocko. This wasn't happening before, and I have not changed any settings or added any filter lists recently. Using FF38.0.5 and uBlocko 0.9.9.0. If this is as it should be, please close this issue!

**Comment by gwarser** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=23355

**Comment by paulderdash** [comment]
Thanks - problem solved!
