### ISSUE TITLE
Allow use of mirrors

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#3540]
### Describe the issue

If you attempt to subscribe to a list mirror from secure.fanboy.co.nz, uBo will fail to use the mirror. 

### One or more specific URLs where the issue occurs

https://secure.fanboy.co.nz/    Select Easylist (Unofficial Mirror), attempt to subscribe.

### Your settings

- OS/version: Win10
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.15.10

**Comment by ryanbr** [comment]
Was reported here; https://www.reddit.com/r/uBlockOrigin/comments/7zlhkb/how_do_i_make_ublock_use_fanboys_site_not/

**Comment by Ravizz** [comment]
And here: https://github.com/gorhill/uBlock/issues/3537

**Comment by ryanbr** [comment]
Okay, didn't relise this.
