### ISSUE TITLE
Some sites bypassing ublock

### ISSUE THREAD

**Issue by Alkaris** [gorhill/uBlock#3542]
### Describe the issue
There's been some sites I've come across that will completely bypass uBlock filtering altogether and instead scan the browser for adblock plugins, and issue a notice that you are running adblock plugins and to disable them. Doesn't matter what Ant-Adblock filters I apply to uBlock, they don't seem to work. Even turning off the uBlock plugin temporarily, or disabling outright from the extensions tab it still detects it.

### One or more specific URLs where the issue occurs
For example here this site, they are using Adobe Flash, but I'm using Google Chrome which uses it's own built-in PepperFlash plugin.
https://www.rte.ie/player/au/live/7/

### Screenshot in which the issue can be seen

![shutter__2018-31-02-24-18__05_02_42_am](https://user-images.githubusercontent.com/6682988/36611631-0fc5edc0-1924-11e8-984c-8cf98ec460f8.png)

- OS/version: `Linux Mint 18.3 (Sylvia)`
- Browser/version: `Google Chrome 64.0.3282.167`
- uBlock Origin version: `v1.15.2`

##### Your filter lists

Defaults
uBlock Extras
Adblock removal
AdGuard
EasyList
EasyPrivacy
Peter Lowes Ad and tracking server list

##### Your custom filters (if any)

    no-strict-blocking: cloudfront.net true
    no-strict-blocking: rte.ie
    * cloudfront.net * allow
    * rte.ie * allow

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Alkaris** [comment]
invalid my ass.

**Comment by okiehsch** [comment]
If you open a new issue this is the first thing you see

-- Filter issues **MUST NOT** be reported here. Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets. Use the logger to diagnose/confirm filter-related issues. If something does not work properly with uBO enabled, the first step is to rule out filter-related issues.

What exactly don't you understand about this concept?
Do you think your issue is somehow not filter related?

**Comment by Alkaris** [comment]
@okiehsch Yes actually, I don't think this is a filter related issue here, since the method applied here is completely bypassing any kind of filtering and directly scanning the plugin of the browser.

**Comment by okiehsch** [comment]
Well, here is a screenshot of `https://www.rte.ie/player/au/live/7/` with a default setup on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/36628328-eac7a972-194c-11e8-8922-1ee06b818e1c.JPG)
as you can see, the video plays fine.

Now I add the **filter** `||pubads.g.doubleclick.net^$object,domain=rte.ie,important`
and try again.
![unbenannt11](https://user-images.githubusercontent.com/16838044/36628620-7fa4e686-194d-11e8-9304-f96708fb3320.JPG)

Wow, I can reproduce by adding a single filter, this "bypassing any kind of filtering and directly scanning the plugin of the browser." is probably still in beta.

**Comment by Alkaris** [comment]
You know if you're gonna be a fucking cunt about it you can just fuck off.

**Comment by Hrxn** [comment]
@Alkaris Please go troll somewhere else, kid..
