### ISSUE TITLE
Cloud sync do not work (Firefox webext)

### ISSUE THREAD

**Issue by piotrjurkiewicz** [gorhill/uBlock#3544]
Cloud storage feature do not work. I tried both on Linux and Windows. Exported settings/filters from one device are not visible on the other one.

After analyzing the source code I see that uBlock sets some preferences. However, none of them are actually set. The only preferences which contains phrase ublock in `about:config` are:

- `browser.uiCustomization.state`
- `extensions.webextensions.uuids`

Moreover, uBlock is unable to get `services.sync.client.name` (which is present in about:config) and uses `window.navigator.platform` instead.

Therefore I suspect that there is some kind of problem with access to preferences.

**Comment by gwarser** [comment]
WebExtensions use sync api https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync

**Comment by gorhill** [comment]
You are failing to provide the most basic information as requested aside precise, detailed steps to repro. Hence closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
