### ISSUE TITLE
HTML filters with the character "^" doens't work on Youtube

### ISSUE THREAD

**Issue by owhous** [gorhill/uBlock#3545]
### Describe the issue

`www.youtube.com##^.style-brand` doens't work, button "Sign in" is visible.

### One or more specific URLs where the issue occurs

https://www.youtube.com

### Your settings

Default

- OS/version: Windows 10 1709
- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.10

**Comment by gorhill** [comment]
There is no `.style-brand` in the response data.
