### ISSUE TITLE
gmx.de login not work!

### ISSUE THREAD

**Issue by Flauschi1981** [gorhill/uBlock#355]
hi,

(sry for my bad english) i have a email adress by gmx.de and with ublock 0.9.9.0 gmx.de startpage work, the login and more on this page dont work anymore correkt! when i klick on my emails the page dont load correkt (https://navigator.gmx.net/navigator/show?sid.... ) plz fix it!

**Comment by gorhill** [comment]
You are not providing the details as asked in <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

Also, look at the logger, it's there to assist in diagnosing/fixing page breakage.

**Comment by akks1981** [comment]
ok now i testing the version ublock 0.9.9.1-rc.0 and now it works fine with gmx! sry and thx

**Comment by gorhill** [comment]
> now it works fine with gmx

More than likely a filter list issue. Did you have _EasyList Germany_ selected with 0.9.9.0? I see exception filters in that list for `gmx.de`. At this point, it always comes down to filter lists when sites break -- selecting too many lists will increase likelihood of breakage.
