### ISSUE TITLE
uBo 1.15.11b3 not stopping popups.

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#3551]
### Describe the issue

Popups are being generated regardless of filters.

### One or more specific URLs where the issue occurs

(NSFW) Open; `http://www.vidz7.com/2018/02/27/fetishnetwork-operationescort-cadence-lux/`

### Steps for anyone to reproduce the issue

NSFW; Only enable Easylist (update before hand), no uBo lists enabled.

Open; `http://www.vidz7.com/2018/02/27/fetishnetwork-operationescort-cadence-lux/`
Click on video;
PopAds seems to override Easylist. Originating from `fffzquckf.com` and flmditew.com

### Your settings

- OS/version: win10
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.15.11b3

##### Your filter lists

Easylist, Easyprivacy, Annoyances.
Disabled ubo-specific lists.

##### Your custom filters (if any)

Tried the following, to try and mitigate it; without any luck.

`*$popup,domain=moecdn.io|stream.moe|oload.stream|oloadcdn.net|vidz7.com`
`*$popup,domain=moecdn.io|stream.moe|oload.stream|oloadcdn.net|vidz7.com`
`||flmditew.com^$popup`
`||oloadcdn.net^$popup`
`||fffzquckf.com^$popup`
`||oload.stream^$popup`
`||vidz7.com^$popup,third-party`

**Comment by troysjanda** [comment]
First off NOT SAFE FOR WORK!!! with that said I am unable to reproduce with default settings and filterlists.

**Comment by okiehsch** [comment]
He mentions in his issue report that he it is a NSFW link and that you will not be able to reproduce with a default setup.

> NSFW; Only enable Easylist (update before hand), no uBo lists enabled.

I can reproduce with `1.15.11b3`, the popup is blocked with  the stable version `1.15.10`.

**Comment by ryanbr** [comment]
okiehsch, can you re-test with the ublock filters disabled (clear the cookies for that domain also). Just enable Easylist, which technically should be enough to block the popups.

**Comment by ryanbr** [comment]
Okay, here's what I'm seeing. 

https://www.youtube.com/watch?v=YCrkBiyP2lo

**Comment by okiehsch** [comment]
Like I said I can reproduce your issue with `1.15.11b3`.

With the uBO stable version the popup is blocked on my end.

**Comment by ryanbr** [comment]
Yeah, misread the post. and was removed
