### ISSUE TITLE
[Request] CRX File Support

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#3552]
Can you lease provide CRX file downloads for installing in chrome.
Thanks

**Comment by gorhill** [comment]
[Chrome 33 Hosting Changes](https://developer.chrome.com/extensions/hosting_changes):

> Users can only install extensions hosted in the Chrome Web store, except for installs via enterprise policy or developer mode.

**Comment by TCB13** [comment]
Still this is useful for browsers like Ungoogled Chromium...
