### ISSUE TITLE
Issue with entire www.alluc.ee website - entire site now blocked :/ not good

### ISSUE THREAD

**Issue by DIW79** [gorhill/uBlock#3553]
### Describe the issue
As it says on the tin. I have only the default settings selected. The results of turning uBlockOrigin 'On' on Alluc are either that only a partially scrambled page of text appears, or that nothing appears. 

### One or more specific URLs where the issue occurs
https://www.alluc.ee
http://www.alluc.ee

### Screenshot in which the issue can be seen

https://photos.app.goo.gl/S9mtsi28zXTVIvvd2

### Your settings

I ensured that uBlock was reset to default 24 hours before submitting the issue

- OS/version: Ubuntu 17.04
- Browser/version: 57.0.4 (64 bit)
- uBlock Origin version: 1.15.10

##### Your filter lists

I have no personal filters added, or enabled

##### Your custom filters (if any)
None

**Comment by uBlock-user** [comment]
Add

`alluc.ee##script:inject(abort-on-property-read.js, document.styleSheets)`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
