### ISSUE TITLE
Clarification for Thunderbird/PM and non-WebExt builds

### ISSUE THREAD

**Issue by DandelionSprout** [gorhill/uBlock#3555]
### Describe the issue
There's been at least some confusion among users of Thunderbird and Pale Moon (I can't speak for Seamonkey users) in the past few months over how to download updated versions of uBlock Origin. Being a Thunderbird user myself, it wasn't easy for me to figure out where to get a hold of the newest version of uBlock Origin for it, or if one even existed, until I found out about how the legacy-focused ublock0.firefox.xpi still support those browsers/clients to this day.

So in an attempt to help alleviate any confusion about it, I suggest that maybe an extra line could be added to [the repo README](https://github.com/gorhill/uBlock/blob/master/README.md)'s "_Installations → Firefox / Firefox for Android_" section? Something like «Users of Thunderbird, Pale Moon, Seamonkey, and of other Firefox-based browsers without support for WebExtensions, can install the Firefox non-WebExt builds from [the Releases page](https://github.com/gorhill/uBlock/releases), which are named ublock0.firefox.xpi.»?

### One or more specific URLs where the issue occurs
• https://addons.mozilla.org/En-us/thunderbird/addon/ublock-origin/versions/ (Only lists the Webext versions, which Thunderbird does not support, for post-1.13.8 versions.)
• https://forum.palemoon.org/viewtopic.php?t=16543 (A few Pale Moon users figuring out how to install the GitHub releases. Ignore the NoScript topic that they're also discussing.)

### Screenshot in which the issue can be seen
• https://images2.imgbox.com/7c/1d/CCka6LDk_o.png
• https://images2.imgbox.com/e0/d4/3Wtb0gSO_o.png (The current README section, which does not mention exactly _how_ the newest uBO builds are compatible with the Firefox-based browsers.)

### Your settings

- OS/version: Windows 10, build 16299
- Browser/version: I'm writing this report from my Chrome 64-bit v64.0.3282.186
- uBlock Origin version: 1.15.11.4 on my Chrome (1.15.10 on my Thunderbird)

**Comment by kowith337** [comment]
For current temporary solution, only [this tool](https://github.com/JustOff/ublock0-updater) can perform auto update for non-WebExt, but first of all, you need to install uBlock first to make this tool work.

**Comment by DandelionSprout** [comment]
I am thankfully aware of the tool's existence, but I had for the past month been both aware of the tool while also being _un_-aware of how to install a regular post-1.13.8 build.

But indeed that's a great suggestion that could've been useful on paper for other people to know if they were in the same situation as what I was.

**Comment by gorhill** [comment]
Given that I solved the auto-update issue of the webext dev build, I could look into solving this as well for the Firefox build.

**Comment by DandelionSprout** [comment]
The doc text edit seems like a good enough solution to me for now, since I after all didn't have picky demands nor wanted to come across as abrasive.
