### ISSUE TITLE
NSFW Scriplet-injection-doesn't-work-sometimes-(randomly) 

### ISSUE THREAD

**Issue by Ravizzz** [gorhill/uBlock#3560]
### Describe the issue

Scriplet injection doesn't work sometimes. I'm not sure if it is an uBO's bug / Firefox's bug / or not a bug at all. Not sure if it is a dupe/related/derivative of: https://github.com/gorhill/uBlock/issues/3069 / https://github.com/gorhill/uBlock/issues/3357, so I've decided to inform about it in a case it'll help somehow.

### One or more specific URLs where the issue occurs

Just an example url, but there is many more similiar websites:  `blackxxxvids.com`

### Screenshot in which the issue can be seen

![capture_007_26022018_145334](https://user-images.githubusercontent.com/36917388/36780328-f0c33c8c-1c72-11e8-9a2a-f1cb450b8cdb.png)

### Steps for anyone to reproduce the issue

1. Disable all filters lists, and add the custom filters only.
2. Open uBO's Logger
3. Open the website.
4. Select the website in the logger.
5. Add `|dom| || --` expression
6. Switch back to the website's browser's tab
7. Press the browser's reload button / F5.
8. Switch back to the logger and try to notice the red static image filter's entries which mean that one of the 3 inject scriplets failed.
9. As the issue occurs randomly like a coin toss/roulette, you most likely have to repeat steps 6-8 X times until you reproduce.

Note 1: As for the step 5:
- f) I've been the most probably also unable to reproduce without the expression , I've written "probably" because I've seen rarely single cases but I'm not sure as I just don't rememebr, I've been trying later to reproduce without the expression but couldn't  reproduce.

Note: 2: As for the step 7:

- a) I've been unable to reproduce the issue using uBO's reload button despite that uBO declared to do the same what the browser's reload button does
- b) I've been unable to reproduce the issue using CTRL + uBO's Logger reload button (bypass cache)
- c) I've been the most probably also unable to reproduce using the browser's CTRL + F5 , I've written "probably" because I've seen rarely single cases but I'm not sure if that wasn't just bad-pressed CTRL key , I've been trying later to reproduce with a properly-pressed CTRL but couldn't  reproduce.
- d) I've been able to reproduce using https://addons.mozilla.org/pl/firefox/addon/tab-auto-refresh/ set on 5s (no bypass), but it's much harder/longer to reproduce, than manually.

Note: 3
- I see 3 injected scripplets (3x3=9 yellow injected filters) in the logger in unaffected browser / version of uBO, while I see only 2 injected scripplets  (2x3=6 yellow injected filters) on affected browser
 / version of uBO, which mean that one of the injected scripplets has failed, and the images leaked.

### Your settings
- clean profile, the only addon is uBO.
- OS/version: Win 7 64bit
- Browser/version: affected  Firefox 58.0.2 64bit, unaffected: Opera 51.0 64bit
- uBlock Origin version:  affected: 1.5.10, 1.15.11b1, unaffected: 1.15.11b0

### Your filter lists

None

### Your custom filters (if any)

```
blackxxxvids.com##script:inject(abort-on-property-read.js, random_imglink_pimp_)
blackxxxvids.com##script:inject(abort-on-property-read.js, random_imglink_pimp_2)
blackxxxvids.com##script:inject(abort-on-property-read.js, random_imglink_pimp_3)
||78.140.163.205/blackxxxvids/images/*0x*$image
```

**Comment by Ravizzz** [comment]
(@gorhill ' s comment copy):

Set `streamScriptInjectFilters` to `true` in advanced settings, see if that makes a difference. As explained in release notes, the scriptlets are back to be injected in a delayed manner, and from looking at the source code of the page, it's plausible that sometimes the inline scripts on the page win over uBO's injected scriptlets.

An another solution is a HTML filter: `blackxxxvids.com##^script:has-text(/random_imglink_pimp_/)`.

> I've been the most probably also unable to reproduce without the expression

The logger has absolutely no influence on what uBO does internally.

**Comment by Ravizzz** [comment]
[>>> THE VIDEO <<<](https://files.fm/f/yzsfentz)

**Comment by uBlock-user** [comment]
Put NSFW before the link atleast.

**Comment by gorhill** [comment]
What happened to the original issue?

With the "normal" way to inject scriptlets (`streamScriptInjectFilters` = `false`), there is no guarantee they will run before anything else on the web page. Many things may make the delay longer, browser-specific internals, having other extensions, etc.

uBO's content script needs to communicate with the core process to find out which scriptlets to inject and however long it takes for the answer to be received by the content script is out of control of uBO.

So the roundtrip delay between content script process => core process => content script maybe too long sometime (having other extensions may increase this as well) that some early script tags in the page may end up executing. This is what #3069 was about.

**Comment by uBlock-user** [comment]
> What happened to the original issue?

It mysteriously disappeared from the issue tracker.
