### ISSUE TITLE
Inform user about new filter -> delete exception

### ISSUE THREAD

**Issue by Erikuio** [gorhill/uBlock#3563]
1. Site is not working - for example: https://github.com/uBlockOrigin/uAssets/issues/1641
2. Cause the filter lists update only every X days: i turn of the adblocker (exception) - in general: many users could do that, especially those who dont know the concept of adblockers
3. A new filter is fixing the problem, BUT i dont know about it because of the exception
4. Result: many users forget about the exception or dont know how to delete the exception and see always ads - although there is a working filter which fixes problem described in 1.

Perhaps it is possible:
1. to increase filter update time 
or
2. inform those users (show a layer with option to delete exception) who have set exceptions on a specific site that the site should work fine because of new filter if the site is visited again

**Comment by gorhill** [comment]
uBO is not equipped with artificial intelligence, it can't tell why someone created a whitelist directive, and whether a filter list update would render that whitelist directive irrelevant.
