### ISSUE TITLE
1.15.11b6  uBlock0.webext.xpi Not Signed?

### ISSUE THREAD

**Issue by puff-m-d** [gorhill/uBlock#3564]
Hello,

### Describe the issue
The 1.15.11b6  uBlock0.webext.xpi is not updating and it appears it is because it is not signed. I am not fully accustomed to this new way of updating the dev/beta version yet so I am not sure if this is an issue or not. If this is not a true issue, I apologize in advance for that so then please disregard this topic and close. Thanks!

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
N/A

### Steps for anyone to reproduce the issue
N/A

### Your settings
N/A

- OS/version:  Windows 10 Pro 64-bit Version 1709 (OS Build 16299.248)
- Browser/version:  Firefox Developer Edition 59.0b13
- uBlock Origin version: 1.15.11b5 (not updating to 1.15.11b6)

##### Your filter lists
N/A

##### Your custom filters (if any)
N/A

Best regards,
Kent

**Comment by overdodactyl** [comment]
From the [releases](https://github.com/gorhill/uBlock/releases) page under 1.15.11b6:

>**Note**: Mozilla AMO signing API seems to not be available at the moment, hence why `uBlock0.webext.signed.xpi` is not available yet. I will try again later at regular interval.

**Comment by gorhill** [comment]
I am going to label such requests as _invalid_. If waiting for the package to be signed is seen as an issue, the workaround is to git clone and build locally. There was a delay out of my control in the current case, and in the future there might be delay for other reasons, including personal reasons.

**Comment by puff-m-d** [comment]
Hello,

I apologize for posting this issue. I did look at the release notes as I have made that a habit but I obviously overlooked that note somehow. At least I did learn something new about the updating of the new signed web extension Thank you.
Best regards....
