### ISSUE TITLE
Update CPU graph to change μblock to ublock

### ISSUE THREAD

**Issue by gene1wood** [gorhill/uBlock#3565]
### Describe the issue

The [README CPU graph](https://github.com/gorhill/uBlock/blob/master/README.md#cpu) still has the old name of μblock and should probably be updated to ublock

### Screenshot in which the issue can be seen

![chart](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/benchmarks/cpu-usage-overall-chart-20141226.png)

**Comment by Thorin-Oakenpants** [comment]
PS'd for ya

![cpu-usage-overall-chart-20141226](https://user-images.githubusercontent.com/16656956/36877103-730fbd12-1db0-11e8-904f-a3083bc5993f.png)

**Comment by jspenguin2017** [comment]
Meanwhile in the background page... 
![image](https://user-images.githubusercontent.com/7283682/36879018-e7b185d8-1d7e-11e8-9811-7968a39532e2.png)

**Comment by gorhill** [comment]
Thanks for the fix. Ideally I should update these charts, they are quite dated -- this is time consuming though.
