### ISSUE TITLE
"Filtros Nauscópicos‎" list allows some connections to Google Analytics

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#357]
I was surprised to see a green indicator next to google-analytics.com on the uBlock popup for the Lastpass password manager (https://lastpass.com/?ac=1&lpnorefresh=1). The Network request logger revealed that it is because of this filter entry in the list "ESP: Filtros Nauscópicos‎":

![Google Analytics exception filter](https://cloud.githubusercontent.com/assets/6733770/8172376/534b2286-1396-11e5-868d-c5d904711d4b.png)

This is a privacy issue for uBlock users, and the list hasn't been updated since 2013.

**Comment by gorhill** [comment]
> the list hasn't been updated since 2013

I should remove it, and let people install it as a custom user list if they wish.

There was another issue with that list: <https://github.com/chrisaljoudi/uBlock/issues/837>.

**Comment by logos88** [comment]
Since this are the only ones that are specifically for Spanish, I would leave them but with an information warning that they are not update and can broke things or something.

**Comment by anewuser** [comment]
There's also [Fanboy's Spanish/Portuguese list](https://secure.fanboy.co.nz/fanboy-espanol.txt) too. It hasn't been updated since 2013 either, but as far as I'm aware, it doesn't have any privacy problem.

**Comment by gorhill** [comment]
The filter list has been removed from stock filter lists in https://github.com/gorhill/uBlock/commit/9fa05aa7c4a2d9ec80f42b9209c8ba8093f60085.
