### ISSUE TITLE
Syncing my settings, custom filters onto different machines (and browsers)

### ISSUE THREAD

**Issue by czardoz** [gorhill/uBlock#3572]
### Describe the issue
It would be great to sync customizations across different devices, through Dropbox/Google Drive. I could contribute this myself, if the core team thinks it's a good idea!

### Your settings

- OS/version: All
- Browser/version: All  
- uBlock Origin version: All

**Comment by gorhill** [comment]
Duplicate of #2468.

**Comment by jspenguin2017** [comment]
How would you store the access token? It feels dangerous to just put it in extension storage. I think Dropbox API is intended to be handled on server side.

**Comment by jspenguin2017** [comment]
Violentmonkey can sync to Google Drive, so it's definitely possible. With a few quirks though: https://github.com/violentmonkey/violentmonkey/issues/278

**Comment by ivysrono** [comment]
Violentmonkey support OneDrive too.
Support onedrive, please.

**Comment by xianghongai** [comment]
I use Firefox and Chrome browsers, Both are installed uBlock, The current synchronization operation is a bit inconvenient.

I recommend adopting third-party mature cloud storage solutions like Tampermonkey.

![storage script  and settings](https://user-images.githubusercontent.com/2075006/38713103-17c3e7bc-3f02-11e8-94d4-b6b5ef1f3171.png)
