### ISSUE TITLE
Unable To Install 1.15.11b8 On Latest Builds Of Firefox Nightly And Stable

### ISSUE THREAD

**Issue by CrossbowDemon** [gorhill/uBlock#3574]
### Describe the issue
Unable To Install 1.15.11b8 On Latest Builds Of Firefox Nightly And Stable

### One or more specific URLs where the issue occurs

 https://github.com/gorhill/uBlock/releases/tag/1.15.11b8

### Screenshot in which the issue can be seen

 https://i.imgur.com/yUbx8WH.png

### Steps for anyone to reproduce the issue

- OS/version: Windows 10 64 Bit
- Browser/version: Firefox Nightly 60.0a1 (2018-03-05) (64-bit) & Firefox Stable 58.0.2 (64-bit)
- uBlock Origin version: 1.15.11b8

**Comment by Raaviz** [comment]
Both, downloading from AMO and through about:addons works fine for me with Firefox 58.0.2 64bit, also take a look at similiar issues: https://github.com/gorhill/uBlock/issues/1413 / https://github.com/gorhill/uBlock/issues/3478

**Comment by gorhill** [comment]
Unable to reproduce -- th xpi package is properly signed. You will have to investigate on your side, there is something specific on your side causing this.

**Comment by FatOrangutan** [comment]
I believe I have run into this issue a bunch of times by now. Filed [Bug 1443387](https://bugzilla.mozilla.org/show_bug.cgi?id=1443387).

@CrossbowDemon , do you see a similar error in Browser Console?
