### ISSUE TITLE
Odd filter count

### ISSUE THREAD

**Issue by Raaviz** [gorhill/uBlock#3575]
### Describe the issue

Since both:
`website1.com,website2.com` and 
`website1.com|website2.com` 
means the same, then why uBO does show diferrent counts, for filter:
`website1.com,website2.com##element` uBO shows cosmetic 2
`element$domain=website1.com|website2.com` uBO shows network 1
uBO shows total count: used 3 from 3:

uBO has to decide: show for the both filters: either 2 or 1  (total count used 4 from 4, or used 2 from 2).

### One or more specific URLs where the issue occurs

--

### Screenshot in which the issue can be seen

![odd_filter_count](https://user-images.githubusercontent.com/36993809/36996205-79e8f67c-20b6-11e8-9161-964bf5711f67.png)

### Steps for anyone to reproduce the issue

1. Add the filters to uBO's My Filters pane
2. Switch to uBO's 3rd-party pane
3. Notice the odd filters count

### Your settings

OS/version: Win 7 U SP1 64bit
Browser/version: Firefox 58.0.2 64bit
uBlock Origin version: v1.15.11b8

##### Your filter lists

--

##### Your custom filters (if any)

`website1.com,website2.com##element`
`element$domain=website1.com|website2.com`

**Comment by gorhill** [comment]
One is a cosmetic filter the other is a network filter. Each is a different filtering engine, with its own implementation. That's just the way I implemented tthis -- no other fancy explanation.

**Comment by Raaviz** [comment]
Also have found another case:

### Describe the issue

uBO doesn't show all filters hits count on it's browser tollbar icon, it shows only network filters hits count, with no DOM filters hits count included.

### One or more specific URLs where the issue occurs

Any, for ex.  www.google.pl

### Screenshot in which the issue can be seen

![ubo_icon](https://user-images.githubusercontent.com/36993809/37019330-352ecd38-2118-11e8-912d-f1a380d00529.png)

![capture_002_06032018_081526](https://user-images.githubusercontent.com/36993809/37019327-326a252a-2118-11e8-99f6-74fd2d5b07b2.png)

### Steps for anyone to reproduce the issue

1. Add the filters to uBO's My Filters pane
2. Switch to uBO's 3rd-party pane
3. Notice it says used 4 from 4 (2 network +2 cosmetic)
4. Open the logger
5. Visit the website.
6. Notice in the logger that there are 5 filters hits shown (3 x network [red] + 2 x cosmetic [yellow])
7. Now switch to www.google.pl tab in the browser.
8. Notice that uBO icon showing only 3 (network) filters hits.

### Your settings

OS/version: Win 7 U SP1 64bit
Browser/version: Firefox 58.0.2 64bit
uBlock Origin version: v1.15.11b8

##### Your filter lists

--

##### Your custom filters (if any)

```
##._Ubu
###prm-pt
/adservice.$domain=~adservice.io
/gen_204?
```

**Comment by gorhill** [comment]
> , it shows only network filters hits count

By design. Counting blocked DOM elements require non-trivial work, hence why it's shown only when the popup is opened.
