### ISSUE TITLE
 fonts.woff2 & downloadable_fonts. causing high CPU usage when in foreground with ublock

### ISSUE THREAD

**Issue by shellye5** [gorhill/uBlock#3577]
Steps to reproduce:

easy
STR

install Ublock addon
open filters
update

spinners(webfonts) causing high cpu spikes

mac/win10 latest Firefox

https://bugzilla.mozilla.org/show_bug.cgi?id=1443496

just in case @gorhill

**Comment by gorhill** [comment]
Your issue could be on your side specifically -- your OS, drivers, etc.

**Comment by gorhill** [comment]
By the way, uBO uses [`ttf` font](https://github.com/gorhill/uBlock/tree/master/src/css/fonts) for the spinner, not `woff2`.

**Comment by shellye5** [comment]
on windows 10

it happens with ubo
easy way is just click update button and see cpu usage, now switch to blank tab and switch back to ubo page
if woff is disabled in firefox
the spinners turn into boxes so isn't it WOFF??
