### ISSUE TITLE
Warn user about CSP reports instead/in addition to blocking them

### ISSUE THREAD

**Issue by Alexander--** [gorhill/uBlock#3578]
As previously discussed elsewhere, Content-Security-Policy reports can be abused for pervasive tracking, when other means of tracking are disabled. Because of this, uBlock allows to disable them.

Unfortunately, disabling CSP reports has number of downsides

1. It marginally decreasing security by making accidental discovery of compromises less likely
2. It lowers usefulness of CSP reports as debugging tool and notification channel

It can be argued, that people, who disable/block CSP reports, are also the ones most well-equipped to react on them. As such I believe that uBlock should alert user about each blocked CSP report to allow reporting it to website administrator or otherwise advertising the discovery.

Simply printing CSP report details to browser console does not cut it - nobody really looks there when normally browsing web. Instead it should be something like NoScript's or Internet Explorer warning popups - big, distinctively looking panel with warning message and link to explanation (and preferably, contents of the blocked report).

This feature should be configurable in add-on settings, and filters should be able to block websites, that abuse CSP reports for non-security purposes, from triggering the warning.

**Comment by gorhill** [comment]
There is a link to <https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports> aside the setting.

**Comment by Alexander--** [comment]
@gorhill 

I didn't ask for additional help articles or explanation texts.

This issue is asking to display a big warning popup in browser window **each time a report is blocked**.

**Comment by uBlock-user** [comment]
> As such I believe that uBlock should alert user about each blocked CSP report to allow reporting it to website administrator or otherwise advertising the discovery.

No, majority of the users don't care and don't want any such annoyance "popping up" as you put it. Those who do care can toggle the setting. CSP reports are a service to the admins without a prior consent from the users, so it's justified that users block it.

**Comment by rjkpa** [comment]
Already discussed to death over here - https://github.com/gorhill/uBlock/issues/3140

**Comment by Alexander--** [comment]
@rjkpa Could you please point to specific post, that discusses this issue? I have read all comments in that ticket, and most of them are completely irrelevant. I am fine with blocking reports, just not *silently* blocking them.

By the way, here is a comment by @gorhill from that ticket:

> Why is the security violation silently reported to a remote server? If you think the security violation is for the benefit of the users, why is it not first reported to them by the browser?

I am proposing to do exactly that: show reports about CSP violations to user instead of sending them somewhere else.

**Comment by gorhill** [comment]
This was a _rhetorical_ argument, because the counter argument being made was that CSP reports are for the benefit of the users.
