### ISSUE TITLE
Whitelist bugsnag

### ISSUE THREAD

**Issue by bcherny** [gorhill/uBlock#358]

**Comment by CrisBRM** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by bcherny** [comment]
@CrisBRM what's the process for submitting proposed filter changes? to me, blocking bugsnag is a bug.

**Comment by Krak-n** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

>5\. Verify that the issue is not related to a 3rd-party filter lists.

@CrisBRM find the 3rd party list it's related to, then email the maintainer of said list.
