### ISSUE TITLE
Established HTML filters don't go into effect until a page is reloaded

### ISSUE THREAD

**Issue by overdodactyl** [gorhill/uBlock#3585]
### Describe the issue
Established HTML filters don't go into effect until a page is reloaded

### One or more specific URLs where the issue occurs

`https://github.com/gorhill/uBlock/issues/3526`

### Steps for anyone to reproduce the issue

1. Create a new Firefox (58) profile and download uBO (1.15.10)

2. Visit `https://github.com/gorhill/uBlock/issues/3526`

3. Observe the presence of a user's avatar next to each comment

4.  Utilize `view-source` to find these avatars have the following form:

    `img alt="@gorhill" class="avatar" height="26" src=...`

5. Go to the "My Filters" panel and create the following html filter:

    `github.com##^.avatar`

6. Refresh `https://github.com/gorhill/uBlock/issues/3526`

7. Observe the avatar is gone.

8.  Click the 'Issues' button.

9.  Select any *different* issue than the one just at.

9.  Observe that the avatars are present and there is no indication of the filter in the logger.

10.  Refresh the webpage.

11.  Observe that the avatars are removed and the corresponding filter is now visible in the logger. 

### Your settings

- OS/version: macOS 10.13
- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.10

##### Your filter lists

Defaults
##### Your custom filters (if any)
Only `github.com##^.avatar` after its addition.

**Comment by gorhill** [comment]
HTML filtering works only on response dats of document requests (main_frame, sub_frame), it's not a replacement of cosmetic filtering.

**Comment by overdodactyl** [comment]
Thank you for the explanation, my apologies for my misunderstanding
