### ISSUE TITLE
userResourcesLocation URL appears twice in the logger

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uBlock#3586]
### Describe the issue

`userResourcesLocation` URL appears twice in the logger when _uBlock Filters_ is updated.

### Screenshot in which the issue can be seen

![](https://i.gyazo.com/b2f29d33f727aa3e5e04eac359499378.png)

### Steps for anyone to reproduce the issue

1. Open Advanced Settings page and paste `https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.txt` at `userResourcesLocation` as the URL and save it.

2. Open 3rd party Filters page and open the logger page for it, now click on the clock icon near _uBlock Filters_, followed by clicking on `Update Now` button.

3. Observe the logger page and notice there's a **double entry** for  `https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.txt`

### Your settings

- OS/version:  Win 10 
- Browser/version:  Chromium 67
- uBlock Origin version: 1.15.11.9

**Comment by uBlock-user** [comment]
P.S -  As seen from the screenshot, the network requests are shown as `behind-the-scene` which didn't happen before, was this an intended change ?

**Comment by gorhill** [comment]
> which didn't happen before

This has always been behind the scene, these are requests made by uBO, there is no tab associated with the extension.

**Comment by uBlock-user** [comment]
Really ? I remembered differently perhaps..

**Comment by uBlock-user** [comment]
Can no longer reproduce this, so closing. Logger refactorisation must have taken care of this for good.

**Comment by gorhill** [comment]
I could reproduce today. There is a race condition so this may or may not be reproduced according to how fast resources are updated. If they update fast, the resource file may be pulled twice. Anyway, I will push an update where this is fixed.
