### ISSUE TITLE
[suggestion] Refresh page when closing uBO popup

### ISSUE THREAD

**Issue by stonecrusher** [gorhill/uBlock#3587]
See the most common action in advanced mode:

1. Go to a site, site doesn't work because of very strict blocking
2. Open uBO popup and set noop on the domain you are on
3. Click into the page - the page should refresh automatically now

So this refresh when closing of course only should take place if you've changed something.
And basically yes, it only saves you one click. But this is such a repeating action that it would be an improvement.

Many pages don't need the repeating allow - test by refresh button - allow - test by refresh button cycle as setting noop on main domain is enough.

I can't imagine a usecase where you change stuff, close uBO popup and **don't** want to reload. If you can (please tell me), I'd still suggest my proposal as an option.

p.s.: If Firefox would get its keyboard shortcut API done and there's a shortcut for noop on main domain this would be obsolete. But that seems far away, so still at least four clicks are necessary for this frequent action. This suggestion makes it three clicks.

/edit
Forget what I wrote in p.s.
A shortcut will never know that you also wanted to noop `example-img.com` and `example-cdn.com`. No further testing needed. So this proposal is still relevant in the future.

**Comment by gorhill** [comment]
<https://www.reddit.com/r/privacytoolsIO/comments/7g6lk6/a_umatrix_guide_for_firefox/dqpksob/?context=1>.

**Comment by Kusresa** [comment]
What are your thoughts on an advanced setting to reload on uBO popup close?
