### ISSUE TITLE
Use user style sheets on Chromium 

### ISSUE THREAD

**Issue by mjethani** [gorhill/uBlock#3588]
Chromium now supports user style sheets via the `cssOrigin` option to `tabs.insertCSS`. Adblock Plus has already implemented changes to use the feature when it's available. uBlock Origin should do the same.

For reference, see [Chromium bug #632009](https://crbug.com/632009).

**Comment by gorhill** [comment]
Unfortunately, `chrome.tabs.removeCSS` is not implemented and this breaks some features in uBO, notably the [toggling of cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) (not a deal breaker, it just affects the real-time part of the feature), but more importantly this breaks the [DOM inspector](https://github.com/gorhill/uBlock/wiki/DOM-inspector).

**Comment by uBlock-user** [comment]
It's a WIP apparently - https://bugs.chromium.org/p/chromium/issues/detail?id=608854

**Comment by uBlock-user** [comment]
I'm on version 1.15.25.100 and if I add `static.kzar.co.uk##.hideme` and then visit `https://static.kzar.co.uk/chrome-style-problem/` the `HIDE ME` text still appears, is it suppose to happen ?

**Comment by uBlock-user** [comment]
Yes, in Canary.

**Comment by gorhill** [comment]
I'm puzzled as to what motivated them to implement this _now_ after all that time ignoring the original pull request.
