### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBlock#3590]
### Describe the issue
The filter 
````
*/content/libs/comscore/comscore.min.js$script,first-party,redirect=noopjs
````
does not lead to a redirection of the request.

### One or more specific URLs where the issue occurs
````
http://www.whas11.com/article/news/atf-investigating-after-congressional-candidate-cut-apart-ar-15/291-526898428
````

### Steps for anyone to reproduce the issue

- Disable `uBO-unbreak`

- Go to 
````
http://www.whas11.com/article/news/atf-investigating-after-congressional-candidate-cut-apart-ar-15/291-526898428
```` 
the video will not play because of the blocked `content/libs/comscore/comscore.min.js` request.

- Add `*/content/libs/comscore/comscore.min.js$script,first-party,redirect=noopjs` to your filter list and reload.
The video will still not play and the logger shows that no redirection has occurred.

- Add `*/content/libs/comscore/comscore.min.js$script,~third-party,redirect=noopjs` to your filter list and reload.
The video will play and the logger shows a successful redirection.

### Your settings

- OS/version: Windos 10
- Browser/version: Chrome 65
- uBlock Origin version: 1.15.2

##### Your filter lists

Default

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/37237313-d9b73922-23ce-11e8-8110-a4a1c142743f.png)

**Comment by jspenguin2017** [comment]
That is weird. With `first-party` the `redirect=` directive is discarded because there is no destination domain. Hold on, let me trace it. 

![image](https://user-images.githubusercontent.com/7283682/37237380-9fc593ac-23cf-11e8-86ca-db3250d96831.png)

**Comment by okiehsch** [comment]
Well, why does `~third-party` work then?

I reported this, privately,  to gorhill and he aggreed that this, ie. `~third-party` works, `first-party` does not work should be fixed and asked me to open an issue.

**Comment by jspenguin2017** [comment]
Found the problem: `redirect-engine.js` has a special case that handles `first-party` but nothing that handles `~third-party`: 
![image](https://user-images.githubusercontent.com/7283682/37237433-59417bde-23d0-11e8-98fb-1ab7c911c449.png)

<details>

![image](https://user-images.githubusercontent.com/7283682/37237430-4f0d0e3a-23d0-11e8-935f-17105bdc7562.png)
![image](https://user-images.githubusercontent.com/7283682/37237431-4f0dec6a-23d0-11e8-878d-45f707b3d2fc.png)

</details>

**Comment by okiehsch** [comment]
Yes, to quote gorhill:

> The current behavior is how I reworked redirect over time. Originally there had to be a domain option and a hostname part to the filter (||). Eventually I allowed first-party to be used in place of domain. Again later I allowed a redirect directive to not longer be forced to have a hostname. However the parsing needs to be reworked further it seems, I should not discard the directive if first-party is present without a hostname. A redirect directive is really two things at once: a static filter, and a redirect directive. I need to adjust the parser code for this.

**Comment by jspenguin2017** [comment]
Looks like `~third-party` is completely discarded by the redirect engine, I think it should be checked with `first-party` but push a `*` instead of empty string if there is no domain.

**Comment by jspenguin2017** [comment]
NVM I read his code wrong. `~third-party` is ignored, so the filter would be equivalent to: 
```
*/content/libs/comscore/comscore.min.js$script,redirect=noopjs
```
Which isn't intended. 

The actual code that handles redirection is probably not aware of request party and needs to be adjusted. The parser is easy to fix (still need to figure out how to flag it as `first-party` though): 
```patch
diff --git a/src/js/redirect-engine.js b/src/js/redirect-engine.js
index a7d539c..61ca5bf 100644
--- a/src/js/redirect-engine.js
+++ b/src/js/redirect-engine.js
@@ -318,8 +318,8 @@ RedirectEngine.prototype.compileRuleFromStaticFilter = function(line) {
             srcs = option.slice(7).split('|');
             continue;
         }
-        if ( option === 'first-party' ) {
-            srcs.push(µburi.domainFromHostname(des) || des);
+        if ( option === 'first-party' || option === '~third-party' ) {
+            srcs.push(µburi.domainFromHostname(des) || des || '<flag-first-party>');
             continue;
         }
         // One and only one type must be specified.
```

**Comment by Raavizz** [comment]
I confirm the issue.

***Your settings:***

- OS/version: Windows 7 SP U 64bit
- Browser/version: Firefox 58.0.2 64bit / Opera 51.0 64bit
- uBlock Origin version: 1.15.11b9

**Comment by gorhill** [comment]
The `redirect=`/`redirect-rule=` options should no longer suffer syntax quirks in latest dev build -- the options are now parsed/compiled and enforced in the static network filtering engine. They can also be excepted just the same way we can except `csp=` and `queryprune=` filters -- all these filters are considered _modifier_ filters.
