### ISSUE TITLE
Ghostery is now open source -> Most Advanced AI-Powered Privacy Protection Tool on the Market

### ISSUE THREAD

**Issue by Erikuio** [gorhill/uBlock#3592]
https://www.ghostery.com/press/ghostery-8-ai-powered-privacy/

..."Since its launch in 2009, Ghostery has offered the most comprehensive database of trackers in the market; it allows users to prevent all known tracking scripts from loading, using either its default settings or customizable options. But as tracking companies constantly update existing trackers and add new ones, it would be impossible to detect and block all trackers on the internet. To solve this gap in protection, Ghostery now has added a new technology to the blocklist-based approach: AI-powered anti-tracking for complete protection. This new technology was developed by Ghostery’s parent company, Cliqz, which specializes in building revolutionary technologies for private browsing and search. Ghostery 8’s enhanced privacy protection detects and overwrites any uniquely identifying data points being passed to a third party – even trackers that aren’t caught by Ghostery’s comprehensive blocklist. The combination of these two technologies means that Ghostery protects users’ privacy better than any other tool in the world."

https://www.wired.com/story/ghostery-open-source-new-business-model/

@gorhill : i dont use ghostery but perhaps interesting for u to look into it - AI Powered anti-tracking sound at least cool. perhaps just marketing. who knows :)

**Comment by Hrxn** [comment]
What is this? Some PR blurb and a crappy article on Big Corp Media™, S.I. Newhouse's _honorable_ media mob, mouthpiece Wired?

Well, no, thanks. Unless you have something real, I'm going with _"Most Advanced Bullshit Powered Tool on the Market"_..

**Comment by Raavizz** [comment]
@Hrxn stop your drama / harassing / insulting / rude tone / negativity.

**Comment by Hrxn** [comment]
_"Father, forgive them, for they do not know what they are doing."_
  — Luke 23:34

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Raavizz** [comment]
> @Hrxn : "Father, forgive them, for they do not know what they are doing."
> — Luke 23:34

@Hrxn : Stop your off-topic, harassing, until you have something constructive to add...this is not a pulpit in the church to preach.
