### ISSUE TITLE
Anti Adblock being asked to be disabled on following sites

### ISSUE THREAD

**Issue by xMikasa** [gorhill/uBlock#3593]
### Describe the issue
I was told anti adblock is inside ublock origin already so i should not be getting disable adblock notices.

### One or more specific URLs where the issue occurs
http://intercelestial.com/
http://adzeni.com/uHHTJTS

### Screenshot in which the issue can be seen
https://i.imgur.com/xB2kGFC.png
https://i.imgur.com/1TRZuH4.png

### Your settings

- OS/version: Mac
- Browser/version: Firefox/Chrome 
- uBlock Origin version: 1.15.10

**Comment by uBlock-user** [comment]
> I was told anti adblock is inside ublock origin already so i should not be getting disable adblock notices.

There's no such thing inside uBlock Origin FYI.

**Comment by Raavizz** [comment]
Agree, you have to install it manually: [Nano Defender](https://jspenguin2017.github.io/uBlockProtector/)

**Comment by okiehsch** [comment]
Well, if I install Nano Defender and disable the filter that was added to `uBlock-filters` to fix
`intercelestial.com`, you will get an anti-adblock messaage.
![unbenannt](https://user-images.githubusercontent.com/16838044/37250806-05a4a4f2-2505-11e8-947d-5674d91c2ecd.JPG)

This is not meant as a knock on Nano Defender, but there is no such thing as 
" anti adblock is inside whatever already so i should not be getting disable adblock notices"

**Comment by uBlock-user** [comment]
@xMikasa it has been patched, force update uBlock Filters.

**Comment by Raavizz** [comment]
I agree, there is no out-of-box solution to block ALL anti-adblock messages / ads etc.:
1. an anti-adblock message / ad medicine must be first implemented to uBO/ND
2. to a medicine be implemented, an anti-adblock message / ad must be first known/reported to maintentainers uBO/ND
3. the maintentainers after being informed/reported or realize themselves, if possible, will implement the medicine into uBO/ND
4. the users must then do an update or will be auto-updated, to the medicine take an effect

(The same applies to Anti-Viruses as well.)

Which doesn't change the fact, as opposed to @okiehsch 's comment based on a single particular case, that generally ND greatly enhances anti-adblock defusing coverage of uBO, especially hard to block anti-adblock message cases wherein uBO fails. (This is not meant as a slight on uBO).

**Comment by mapx-** [comment]
@xMikasa  for any filter issue in the future just use the correct repository:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by okiehsch** [comment]
> opposed to @okiehsch 's comment based on a single particular case

https://github.com/jspenguin2017/uBlockProtector/search?q=commenter%3Aokiehsch&type=Issues&utf8=%E2%9C%93

Check this issues, most of them are also these "particular cases" and where did I say that "Nano" does not enhance anti-adblock defusing coverage?
It clearly does, it uses `generic` solutions, which uBlock does not.

> I wonder what would @okiehsch say if the actual anti-adblock message case would be too hard to be blocked by uBO

I would say I can not find a filter, so far if jspenguin2017 pinged me to fix an anti-adblock message, I think I said it once and he then suggested a working filter which I then added to `uBlock-filters`.

**Comment by jspenguin2017** [comment]
Nano Adblocker was created for experiments: syntax highlighter, filter linter, timer boosting, etc. 
I also took the opportunity to rebrand Nano Defender, but I have *never* claimed that Nano is better than uBO. 

Specific cases still need to be handled in uAssets, but I have generic rules that fixes a large amount of websites. For example, I have a rule that defuses *all* URL shortening system that uses `app_vars`. This does have the side effect of slowing down other websites, but I always run benchmarks to make sure the impact is acceptable. 

It is pretty rare that filters cannot fix a problem, but it happens, in those case I usually create a new script snippet to deal with it, Nano Defender is mostly for generic rules these days. 

If you like Nano you can use it, but it doesn't mean you need to make others to do the same.
