### ISSUE TITLE
Codemirror not showing error font color on filters with unclosed parenthesis

### ISSUE THREAD

**Issue by yourduskquibbles** [gorhill/uBlock#3595]
When editing My Filters, filters with unclosed parenthesis do not show up as red text indicating there is an error in the filter.

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

![capture](https://user-images.githubusercontent.com/22258847/37297872-bbbbf8a0-2616-11e8-9f07-23325deaea0b.PNG)

### Steps for anyone to reproduce the issue

1. Create filter using `:has(foo.Foo`, `:xpath(.//*[@foo="foo"]` or `:style(foo !important;` condition and don't close the parenthesis.
2. Expected Result: Based on other incorrect filter behavior (shown at bottom of screenshot) filter should be red to indicate to user there is an error in the filter.
3. Actual Result: Filter remains blue which indicates the filter is working

### Your settings

- OS/version: Win 10
- Browser/version: Firefox/Chrome 
- uBlock Origin version: 1.15.11b12 dev build on FFX, 1.15.11.10 dev build on chrome

edit: updated screenshot to better demonstrate the error.

**Comment by gorhill** [comment]
I never documented this was a feature, and release notes say:

> Please do not open feature requests related to this, I intend to informally improve the integration as time pass and replace all textareas with the CodeMirror editor.

**Comment by yourduskquibbles** [comment]
OK sorry about that, I was not intending for this to be interpreted as a feature request.

**Comment by uBlock-user** [comment]
I see those highlighted hastags,directives etc..(#,$), is that a bug or an intended feature ?
