### ISSUE TITLE
 Lists update problems 

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#360]
I use ublocko 0.9.9.1 on Firefox 38.05 on windows 7 and I have a problem of automatic update of the filter lists checking. It's not the first time and it's the same problem with the automatic update with any filter lists whatever the version from the browser or the addon. I must do it manually.

![ublock _ _tableau_de_bord_-_2015-06-16_17 47 48](https://cloud.githubusercontent.com/assets/12104299/8187767/0b105e20-1452-11e5-8ae1-1515fee8816d.png)

**Comment by gorhill** [comment]
Let it update itself, it will. There is no guarantee a remote server will always be up and ready. When this happens, uBlock will try again at some point in the future.

**Comment by alain1965** [comment]
Ok thanks and keep on ubloclo is a really good adblock, even the best.
