### ISSUE TITLE
Please remove/deactivate the Romanian block list

### ISSUE THREAD

**Issue by Eig8phei** [gorhill/uBlock#3603]
### Describe the issue
Hello, this list was recently (and automatically?) activated for Romanian users.
The problem is that the maintainers have a political agenda.

For example, in the issue at https://github.com/tcptomato/ROad-Block/issues/18 some user asks why the site stiripesurse.ro is blocked and the response is because the site is listed at a third party site https://verificasursa.ro/

I will quote the explanation given at https://verificasursa.ro/intrari/stiripesurse.ro (machine translation)

> At first, a little history. Originally as a platform of gossip, shifts and political shucks, pesurse.ro has earned its fame to present the fastest information behind closed doors. The revolution had a significant impact on the success of the platform, but also increased competition on this media segment. After the bowel fight on the domain name, the website of pesurse.ro split in stiripesurse.ro and psnews.ro. Both platforms have increased their number of collaborators and have invested in increasing quality journalism with more or less success. As with any kind of journalistic approach, you present unforeseen and unrecognized information, with SOURCES titles, we recommend you pay more attention to both sites.

As a matter of fact I personally don't trust or like many of the news sites we have (international ones included) but I think that block lists should stick with blocking ads, annoyances and third party exposure and not block entire sites based on opinions of even more _questionable_ people. 

### Screenshot in which the issue can be seen

![ro_block](https://user-images.githubusercontent.com/22045484/37391464-eb776ae4-2773-11e8-85ab-54919205dea1.png)

### Your settings

- OS/version: Linux
- Browser/version: Firefox 59
- uBlock Origin version: v1.15.10

**Comment by mapx-** [comment]
You can simply unblock that site if you want to use it and trust it.

**Comment by tcptomato** [comment]
We don't have any kind of political agenda, this is why we used a third party site as a reference. And we did it this way because opt-out is easier than opt-in ( you just have to click on "Permanent").  Or you can use the light version of the list, which doesn't flag this kind of sites.

https://raw.githubusercontent.com/tcptomato/ROad-Block/master/road-block-filters-light.txt
