### ISSUE TITLE
Unresponsive switchboard in Nightly

### ISSUE THREAD

**Issue by JW-IT** [gorhill/uBlock#3605]
No Clicks are registered on uBlock's DropDown Menu.

the same problem as in uMatrix
see https://github.com/gorhill/uMatrix/issues/968

windows10-64bit
firefox nightly 61.0a1 64-bit

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1445537

**Comment by geeknik** [comment]
This is fixed in today's latest Nightly build (ID 20180315223216).

**Comment by JW-IT** [comment]
can confirm, latest nightly update fixed this
win10 (64bit), Nightly 61.0a1 (2018-03-15) (64-bit)

**Comment by Porkepix** [comment]
Same as for https://github.com/gorhill/uMatrix/issues/968 @JW-IT @gorhill this should probably be closed?
