### ISSUE TITLE
Match partial IP address in dynamic filtering

### ISSUE THREAD

**Issue by Kusresa** [gorhill/uBlock#3606]
Currently, uBO can't match partial domains or IPs in dynamic block filtering rules. You mentioned it could be done here https://github.com/gorhill/uBlock/issues/802#issuecomment-147824006 but I couldn't find a open issue for this so wanted to ask here.

**Comment by gorhill** [comment]
I looked at the code and partial matching is supported. Hence closing as invalid since no repro case was provided -- as required.

**Comment by gorhill** [comment]
My bad, for whatever reasons I was confused when I verified this issue -- partial ip address matching is indeed not implemented.
