### ISSUE TITLE
Cosmetic filtering removes Facebook posts

### ISSUE THREAD

**Issue by miracleflame** [gorhill/uBlock#3608]
### Describe the issue
For a few days now clicking on any button including "Comment", "Like" maybe "Share" as well instantly hides the whole post from the view of newswall. You can technically "clear" post by post this way. Of course refreshing the whole page makes the post to reappear.

### One or more specific URLs where the issue occurs
https://www.facebook.com/?sk=h_chr

### Screenshot in which the issue can be seen
This is not very much visual thing. I could make a screenshot BEFORE and AFTER where you could see that post above and below are suddenly next to each other but I believe you can imagine that well from this description.

### Steps for anyone to reproduce the issue
0. Have Firefox 59.0 (64-bit) on Windows 10 (64-bit) build 16299.rs3_release.170928-1534
1. install and enable uBlock Origin add-in for FF
2. make sure Disable cosmetic filtering in uBlock Options is unchecked
3. navigate to https://www.facebook.com/?sk=h_chr
4. Like any post or click Comment button
5. Observe the post being removed from the list

### Your settings
- OS/version: Windows 10 (64-bit) build 16299.rs3_release.170928-1534
- Browser/version: Firefox 59.0 (64-bit)
- uBlock Origin version: 1.15.10

##### Your filter lists
factory defaults

##### Your custom filters (if any)
none

**Comment by ostrolucky** [comment]
Cosmetic filtering makes facebook experience very broken. I didn't occur your problem (removed post when clicking on a button), but ublock removes tons of posts each time I refresh my wall. See below to see what happens each time I click on Home.

![peek 2018-03-17 15-52](https://user-images.githubusercontent.com/496233/37556802-55b56800-29fb-11e8-9962-2507fa76cec1.gif)

**Comment by miracleflame** [comment]
I believe my case is very much associated to the new behavior FB introduced in my case. When unblocked/unremoved this is popping-up after hitting a button

[](https://snag.gy/A8U1WI.jpg)

That is I am always prompted to tag a friend.

**Comment by pleswi** [comment]
I have same problems like @miracleflame  and @ostrolucky, and many my friends reports the same behavior.

**Comment by Serkan-devel** [comment]
When not logged in, the page doesn't display at all

**Comment by jackorp** [comment]
Hello, I have the same problems as @miracleflame and @ostrolucky described.

**Comment by mapx-** [comment]
open the logger, repeat the steps and post here what filters (especially cosmetic ones) are triggered

**Comment by ostrolucky** [comment]
I've resintalled ublock origin and no longer see this problem with cosmetic filtering enabled :thinking: 

Currently installed: uBlock Origin 1.15.18

**Comment by miracleflame** [comment]
I haven't reinstalled anything, Just re-enabled cosmetic filtering and all seems to work fine now. Tag a friend popping-up without post disappearing, etc.

Shall I close this then?

**Comment by jackorp** [comment]
Hmm I reinstalled as well, I can like and comment and posts don't disappear but the posts stil can't load properly and I see the flickering. I'll try to open logger and post results here.

**Comment by jackorp** [comment]
so this was the output after I loaded into facebook and tuned into log:
https://paste.fedoraproject.org/paste/CGkommIknjGwgOO-IRxShA

**Comment by mapx-** [comment]
add these exceptions and test again:

```
facebook.com#@?#div[id^="hyperfeed_story_id_"]:-abp-has(input[data-next-question-id])
facebook.com#@?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-contains(Char))
facebook.com#@?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-contains(Sp))
facebook.com#@?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-contains(Spon))
```

**Comment by jackorp** [comment]
These exceptions fixed it for me.

**Comment by mapx-** [comment]
@monzta

**Comment by miracleflame** [comment]
The original issue is right back now.

I was hardly able to narrow it down to this in logger, hopefully this is what I should copy out:
Dynamic URL filtering
```
  | https://www.facebook.com/ajax/typeahead/first_degree.php?dpr=1.5…__rev=3753764&__spin_r=3753764&__spin_b=trunk&__spin_t=1522045346
-- | --
```

static filtering exception filter:
`||www.facebook.com/ajax/typeahead/first_degree.php?dpr=1.5&context=mentions&viewer=100000352364272&token=1522017557-7&filter[0]=page&filter[1]=group&filter[2]=app&filter[3]=event&filter[4]=user&options[0]=friends_only&options[1]=nm&__user=100000352364272&__a=1&__dyn=7AgNe-4amaxx2u6aJGeFxqeCwKyaGey8gFLFwxx-6ES2N6wAxu13wqpUKbnyorxuF89XyEjKewXGt0TyKdwJKqq4e9Dxh1rDAzUO5UlwnoCidwBx62q3PxqrV8iABxG7WxWeCxa6EowODBwJwGxy8wADx6WK6468nxK44fjG12Bxd1GbyEky8-nyES3m6ogzoymf-Egy9GzEswCGcyZ1zzGyo8fiAxqt5ouxGh4yEiypryovxbBgOUOax2qdxS44&__req=4z&__be=1&__pc=PHASED%3ADEFAULT&__rev=3753764&__spin_r=3753764&__spin_b=trunk&__spin_t=1522045346$xmlhttprequest,domain=www.facebook.com`

and/or
Dynamic URL filtering
`https://www.facebook.com/story/suggest_story_friend/?caller_id=c…nity_conversations&ft_id=1883106985055122&purpose=mention&dpr=1.5`

static filtering exception filter:
`||www.facebook.com/story/suggest_story_friend/?caller_id=community_conversations&ft_id=1883106985055122&purpose=mention&dpr=1.5$xmlhttprequest,domain=www.facebook.com`

**Comment by gorhill** [comment]
> static filtering exception filter

And from what filter list is that filter coming from? Can't find it in any of the default lists, and neither Fanboy Annoyance/Adguard Base.

**Comment by monzta** [comment]
@mapx- https://github.com/easylist/easylist/commit/f8edd08
