### ISSUE TITLE
Make dashboard more easily accessible

### ISSUE THREAD

**Issue by hjudt** [gorhill/uBlock#361]
Please make the dashboard accessible more easily. If one wants to check the filter lists (are they up-to-date?), one has to navigate to the add-on manager, then click on settings, then scroll down a huge wall of text, then look for the "show dashboard" button. Two recommendations:

1) Why don't you make the settings button behave like that of other add-ons, that is to bring up the settings dialog (which for me is what the dashboard represents)? At the moment, it shows the "more" dialog instead of the dashboard.

2) How about adding a small settings button to the toolbar icon popup? There seems to be enough space besides the other three icons at the bottom of the popup. BTW: A tooltip for these icons that tells what they do would be a nice usability improvement too.

**Comment by gorhill** [comment]
> make the dashboard accessible more easily

<https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-title-bar>.

> A tooltip for these icon...

<https://github.com/gorhill/uBlock/wiki/Advanced-user-features#no-tool-tips>.

**Comment by hjudt** [comment]
ok, sorry for the noise.
