### ISSUE TITLE
Random content disappears only on tabs after initial tab

### ISSUE THREAD

**Issue by joshudson** [gorhill/uBlock#3610]
### Describe the issue

Random content disappears only on tabs after initial tab

I'm really sure this is not a filter issue. This is also not 100% reproducible but reproduces more than 2 times out of 3 on the same page. The same text may or may not be affected on subsequent tries.

This never happens only on the first tab but only on subsequent tabs

### One or more specific URLs where the issue occurs

https://stackoverflow.com/  <open random questions in new tabs>
https://blogs.msdn.microsoft.com/oldnewthing/20180315-00/?p=98245
default firefox home page affected but it's not immediately obvious
ublock - Dashboard (almost completely blank)

Please note that disabling ublock on the site from the ublock menu and pressing refresh on the browser toolbar does *not* make the issue go away. Disabling the add-on entirely from firefox add-on manager does however.

### Screenshot in which the issue can be seen

![screenshot_20180315_182546](https://user-images.githubusercontent.com/16249210/37499157-83187fc6-287f-11e8-9145-034ba9f3b5f2.png)
 attached

### Steps for anyone to reproduce the issue

1. Have Windows
2. Have High Contrast Black
3. Open https://stackoverflow.com
4. Right click on questions, open in new tab
5. Switch to tabs question.

Issue will occur most of the time and it's rather random. The page text *is* there but its being drawn black on black. It can be selected and copied. Moving the mouse over links causes them to appear.

### Your settings

- OS/version:  Windows 7 x86; High Constrast Black enabled
- Browser/version: Firefox 59
- uBlock Origin version: (unable to obtain because ublock - dashboard is affected)

Firefox 58.0.2 is unaffected.

##### Your filter lists

I believe filter lists are all default.

##### Your custom filters (if any)

None

**Comment by FatOrangutan** [comment]
>Browser/version: Firefox 59 Firefox 58.0.2 is unaffected.

This is likely [Bug 1435472](https://bugzilla.mozilla.org/show_bug.cgi?id=1435472) (so a Firefox issue, and not a uBlock issue).

By any chance, do you have clear type disabled in Windows? Does the issue go away if you enable clear type (and preferably restart computer)? If you don't want to do that, you can try disabling hardware acceleration in Firefox. This will negatively affect performance, so you'd want to keep track of the above bug and re-enable hardware acceleration once it is fixed.

**Comment by joshudson** [comment]
On checking I found that the turning off hardware acceleration does indeed fix the problem so it likely is the aformentioned firefox bug. I thought that remote desktop had eliminated that possibility but nope!

I had searched for a firefox bug based on the observed symptoms and had found not. Bisection showed the problem going away when disabling plugins so that's what I thought it was.

Sometimes you do everything right and it still comes out wrong. :(

**Comment by Thorin-Oakenpants** [comment]
@joshudson FYI: probably https://bugzilla.mozilla.org/show_bug.cgi?id=1435472

also something to do with only affecting users who have turned off cleartype font rendering within their windows settings. so a workaround for the moment would either be to turn cleartype back on or disabling hardware acceleration in firefox - regurgitated from somewhere, I haven't bothered to fully read the bug
