### ISSUE TITLE
"My Rules" tab is not displayed properly in FF RTL

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#3611]
### Describe the issue
"My Rules" tab is not displayed properly in FF RTL (e.g. Hebrew)

### One or more specific URLs where the issue occurs

chrome://ublock0/content/dashboard.html#dyna-rules.html
### Screenshot in which the issue can be seen
![default](https://user-images.githubusercontent.com/10229320/37545193-9021bf9c-2970-11e8-9328-66de2b8c7fbe.png)

Above.
### Steps for anyone to reproduce the issue

1. Firefox Hebrew.
2. Set user_pref("intl.accept_languages", "he, he-IL, en-US, en");
3. Open chrome://ublock0/content/dashboard.html#dyna-rules.html

### Your settings
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.ublock0.dashboardLastVisitedPane", "settings.html");
user_pref("extensions.ublock0.immediateHiddenSettings", "{\"suspendTabsUntilReady\":false,\"userResourcesLocation\":\"unset\"}");
user_pref("extensions.ublock0.shortcuts.launch-element-picker", "");
user_pref("extensions.ublock0.shortcuts.launch-element-zapper", "");
user_pref("extensions.ublock0.shortcuts.launch-logger", "");

- OS/version:  Windows 7.
- Browser/version: Firefox 52.
- uBlock Origin version: v1.15.14.

##### Your filter lists
EasyList + ISR

**Comment by gorhill** [comment]
Please confirm that this is fixed with the pre-release version `uBlock0.webext.signed.xpi` from <https://github.com/gorhill/uBlock/releases/tag/1.15.15rc0>.

**Comment by Yaron10** [comment]
Great. :+1: 
Thank you for the quick fix.
***
A related issue:
Type "scheme" in the "White List" tab's search box.
-- The word and the number are overlapped.

![default](https://user-images.githubusercontent.com/10229320/37547935-3ebf65a2-297d-11e8-8bf4-233c9e786bd6.png)

In "My Filters" tab the search box layout is LTR.
IMO it should be the same in "White List" tab.
***
Another point:
when hovering over the Search and Prev/Next images, the cursor should change to "pointer".

**Comment by gorhill** [comment]
When you type `scheme` in the search box, is your expectation that the search term appear on the right as seen in your picture, or that it appears left?

**Comment by Yaron10** [comment]
I'd like the search term to appear on the left.
But I think the entire layout should be LTR as it is in the "My Filters" tab.

![default](https://user-images.githubusercontent.com/10229320/37548520-21d4bfa6-2981-11e8-9c6c-51b71da73245.png)

Thank you.

**Comment by gorhill** [comment]
In 1.15.15rc1 I hard-coded the search widget to be left-to-right -- the CodeMirror editor is also hard-coded to be left-to-right.

**Comment by Yaron10** [comment]
:+1: 
Thank you. I appreciate your great work.

Regarding the cursor: I meant a regular "pointer" (the one you get when hovering over a toolbar icon; not the "hand"). And it should apply to the "Search" image as well. :)

**Comment by gorhill** [comment]
> Regarding the cursor: I meant a regular "pointer"

It was already the regular pointer on my side. The magnifier is not interactive, it's just to signal that the widget is for searching purpose.

**Comment by Yaron10** [comment]
> It was already the regular pointer on my side.

I get the "hand" on my side (I'm not using the webext if it should make a difference).

> The magnifier is not interactive, it's just to signal that the widget is for searching purpose.

Isn't this slightly confusing?

**Comment by gorhill** [comment]
I changed to the hand (css `pointer`) in response to your comment:

> when hovering over the Search and Prev/Next images, the cursor should change to "pointer".

What were you seeing before the change? The text cursor? In any case I will force CSS `default` (pointer) for next release.

**Comment by Yaron10** [comment]
> What were you seeing before the change? The text cursor?

Indeed, the text cursor.

>  In any case I will force CSS default (pointer) for next release.

Great. Thanks again.
