### ISSUE TITLE
Not wanted

### ISSUE THREAD

**Issue by 20waddk** [gorhill/uBlock#3612]
I DO NOT WANT UBLOCK I WANT IT GONE!!

**Comment by akks1981** [comment]
mimimimimi

**Comment by Hrxn** [comment]
With regard to the efficiency of uBlock Origin, I present exhibit A...

**Comment by uBlock-user** [comment]
Oh, so it's one of these days!

**Comment by gwarser** [comment]
Hamburger -> Addons/Extensions -> Remove 

:)

**Comment by Atavic** [comment]
Let's close this for time immortal.

**Comment by gorhill** [comment]
Yes, I will go through all of them as time allow.
