### ISSUE TITLE
EasyPrivacy (current and former versions) block Foxnews.com videos from playing

### ISSUE THREAD

**Issue by lakrsrool** [gorhill/uBlock#3617]
EasyPrivacy current Version 201803171328 (and former versions) block videos from playing on Foxnews.com.

Example URL (among all videos on Foxnews.com): http://www.foxnews.com/politics/2018/03/17/trumps-lawyer-calls-for-russia-probe-to-be-shut-down.html#

Video will fail to play with EasyPrivacy version 201803171328 (updated 3-17-18) and prior versions as well ENABLED in uBlock Origin.

Video will play successfully with EasyPrivacy version 201803171328 and prior versions as well DISABLED in uBlock Origin.

Nothing else is a factor since whether the Foxnew.com video will play or not play is solely dependent upon whether the current version of EasyPrivacy is enable or not enabled.

**Comment by joey04** [comment]
I'm able to play the video no problem in a profile with EasyPrivacy and several other big lists. The key is that I don't use generic cosmetics, which are a known source of problems like this. (It's why EasyList has about 1000 generichide rules.)

I've not tested with enabling them but that may be the problem here.

**Comment by lakrsrool** [comment]
Again --- the page works with EasyPrivacy **version 201803171328** **disabled** all other factors remaining the same (and does not work when enabled).  Wouldn't that suggest that it would have to be EasyPrivacy that is interfering?

I have tested this in more than one ad-blocker and in fact using no other ad-blocking of any kind -- only EasyPrivacy and get the same results.

**Comment by lakrsrool** [comment]
Okay -- by using just HTML5 and not HTML5 + MSE and if I double-click on the video it WILL play with EasyPrivacy enabled.

Sorry for all the confusion -- apparently this was the problem.

Thanks for your feedback.

**Comment by lakrsrool** [comment]
I'm still having problems going to the next video (not a problem regarding this in another browser using EasyPrivacy however) -- but since the initial video now works with EasyPrivacy enabled (other factors changed) I'm going to assume my continuing issues are other factors and not an EasyPrivacy issue.

The fact that EasyPrivacy is working for others suggests the problem is elsewhere as well --- so thanks for all the feedback --- I'll consider the matter closed.

**Comment by uBlock-user** [comment]
cc @ryanbr

**Comment by ryanbr** [comment]
Works fine, Firefox with no flash/HTML5 only. With Easyprivacy enabled too.
