### ISSUE TITLE
Malvertising filter by Disconnect

### ISSUE THREAD

**Issue by Aranjedeath** [gorhill/uBlock#362]
I'm not sure what exactly to do about that list, but it's a problem. They list digits.com, which is a Twitter project (and maybe you don't like them for privacy reasons, but it's not malvertising). 

Due to the discussion in https://github.com/chrisaljoudi/uBlock/issues/1406 it sounds like an open question. Maybe the list can just be edited? But I think we're not in the business of maintaining other people's lists.

**Comment by gorhill** [comment]
> I think we're not in the business of maintaining other people's lists

So why open an issue about this?
