### ISSUE TITLE
Disable included filterlists by directive

### ISSUE THREAD

**Issue by hawkeye116477** [gorhill/uBlock#3622]
### Describe the issue
Can you add some way to disable filterlists included by directive `#include`?

### Your settings

- OS/version: Manjaro Linux
- Browser/version:  Waterfox 56.0.4.1
- uBlock Origin version: 1.15.16

**Comment by KonoromiHimaries** [comment]
to handle multiple lists and their selective deactivation

example.
it would help resolve the conflict with the fanboy's rss

**Comment by KonoromiHimaries** [comment]
there is a bug when I try to load several lists
![screenshot_20180318_151346](https://user-images.githubusercontent.com/5884000/37567890-d1d922a0-2acd-11e8-8913-a3c2efa50994.png)

**Comment by gorhill** [comment]
The `#!include` directive is a convenience syntax for filter list authors to make it easy to manage the content of their lists -- it is _not_ intended for users. If users want different content for a given filter list, they need to ask the author to provide it as a separate filter list.

**Comment by KonoromiHimaries** [comment]
@gorhill i don't want to create 100+ filters list containing each case, example

<details><summary>filter lists</summary>

```
social+popup+rss
social+rss
social+popup
social+fb_icon
social+ttwitter_icon
social+fb_icon+rss
```

</details>

that no have any sense
normal users don't use these lists..

**Comment by gorhill** [comment]
> i don't want to create 100+ filters list

Then don't -- I am asking you nothing. If somebody is asking you this, then deal with these requests as you wish, I will not abuse the purpose `#!include` directive to turn it into a nightmare of maintenance and code paths. The semantic of `!#include` is crystal clear: to **seamlessly** load another filter list as part of the parent filter list so that the result is a whole filter list being the sum of its sub-filter lists -- it is not intended for any other purpose.

**Comment by KonoromiHimaries** [comment]
ok. how to i can fix rss conflict? ( not everyone wants to block rss and hate me about that )

I would like to point out that creating a separate set does not make sense because nobody will know it.
everyone will install the original set

**Comment by gorhill** [comment]
Whatever a filter list does should be clear, I assume it's in the description. Then if people install it and are not happy with the result, they should remove it. If people hate you because your list does what it is supposed to do, they should work to fix their own issue themselves as they see fit.

**Comment by KonoromiHimaries** [comment]
if ublock allows you to whitelisting the rule, why would not it be the same for the directive?
it is really worth it, it gives many possibilities and makes work easier

that's what it's all about? why not do it? for fear of collisions?

> What were you doing before

i'am played on the minecraft
