### ISSUE TITLE
2 included filterlists by directive are doubled

### ISSUE THREAD

**Issue by hawkeye116477** [gorhill/uBlock#3624]
### Describe the issue
If I include 2 filterlists to one filterlists with `#include`, then they are doubled.

### Screenshot in which the issue can be seen
![screenshot_20180318_151346](https://user-images.githubusercontent.com/19818572/37567927-5035fcf4-2ace-11e8-84fc-c8b0a0308f74.png)

### Steps for anyone to reproduce the issue

1. Import my Social filterlist -> https://raw.githubusercontent.com/hawkeye116477/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt
2. Then go to uBO Dashboard
3. Click on my Social Filterlist to view in viewer
4. Scroll up to down and see doubled lists.

### Your settings

- OS/version: Manjaro Linux
- Browser/version: Waterfox 56.0.4.1
- uBlock Origin version: 1.15.16

##### Your filter lists
https://raw.githubusercontent.com/hawkeye116477/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt

**Comment by Hrxn** [comment]
How is this a uBO issue?

**Comment by hawkeye116477** [comment]
@Hrxn uBO supports !#include and I have that includes on my filterlist:
```
!#include social_filters_uB_AG.txt
!#include /RSS/Polish_RSS.txt
```
So only one social_filters_uB_AG.txt and one /RSS/Polish_RSS.txt should be on viewer.
