### ISSUE TITLE
Google sites freezing uBlock origin really hard.

### ISSUE THREAD

**Issue by ardydo** [gorhill/uBlock#3627]
### Issue

Some Google sites causes uBlock origin to freeze my computer really badly. Sometimes 2m+. It's an old computer but this didn't happen often. I tough that maybe it was a browser issue so I hoped to many different browser. The issue went away for some time after I whitelisted google.com (which is really non ideal) but then it started to hang again until I actually disabled the extension. After that no more hangs where experienced. drive.google.com hangs the hardest but the other sites sometimes hangs too.

### Url
https://drive.google.com/
https://calendar.google.com/

### Steps for anyone to reproduce the issue

1. Download browser
2. Install uBlock Origin
3. Refresh drive.google.com a few times.
4. Browser freezes the whole computer using 100% CPU

### Your settings

- OS/version: Ubuntu 17.04
- Browser/version: Firefox 59.0.1/Vivaldi 1.14.1077.55/Waterfox 56.0.4/Pale Moon 27.8.1/Chrome  65.0.3325.162 (all the latest stable ones)
- uBlock Origin version: 1.15.2/1.15.10 (Pale Moon)

##### Your filter lists

Just the default filter with nothing changed.

##### Your custom filters (if any)

No custom filters

**Comment by Hrxn** [comment]
Can't reproduce so far..

**Comment by ardydo** [comment]
I'll try to narrow down the reproduction steps as even I'm now unable to reproduce. It did actually freeze once (in vivaldi) but not again in any other browser.

**Comment by ardydo** [comment]
The only way I've found to reproduce the issue is to use the browser for some time and then open google drive. It will load but a few seconds after it will freeze sometimes just to never unfreeze forcing a hard reset.

The thing is I'm not sure that it's uBlock itself that is causing this, another extension (the only one I'm using is keepass) or both of them together and I don't have time available to test it right now so I'll close the issue for now and if I stumble across some way to reproduce it I'll do it.

Thanks for the attention and the good work :)
