### ISSUE TITLE
Unable to Override "No Remote Fonts" with Dynamic URL filtering.

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#363]
I intended to use this feature to block most if not all webfonts by default, and of course, I can re-enable the whole site.

However, some sites might want to load various fonts, whereas I might only want them to load an "icon font" and let the text fall back to whatever my browser has.

The Dynamic URL filtering will allow finding the blocked font, going through the steps, but the no remote fonts will trump it.

Steps to Reproduce:
1. Visit and site that loads fonts, block it from loading remote fonts.
2. Open Logger, create unblock (neither noop nor allow work in the end) rule, either for the file or path.
3. Refresh and see that the fonts will still be blocked.

**Comment by gorhill** [comment]
What about:

    no-remote-fonts: * true
    ...
    no-remote-fonts: example.com false
    example.com https://fonts-whatever-cdn.com font block
    example.com https://fonts-whatever-cdn.com/icons.ttf font allow

?

**Comment by CODYQX4** [comment]
That sounds viable, though it requires extra rules to accomplish.

**Comment by CODYQX4** [comment]
Hm, still requires me to completely enable fonts, and end up in allow by default mode.

As in if a site uses font CDNs, I'd have to explicitly block those, block the 1st party fonts, then allow the specific 1st party font. All while if they change CDNs, those fonts would load.

This ties in with #320 to where if I could specify a rule such as test.com * font block would allow the block by default behavior to function. As of now, such a rule is silently trashed as invalid.

**Comment by Snapy** [comment]
You could use static filtering : `*$font` to block fonts everywhere and then `@@||fonts.com$third-party` for font CDN and/or `@@||website.com/fonts/*$first-party` for 1st party fonts.
Or you can use Fanboy Anti Fonts filter list.

**Comment by yurikhan** [comment]
Is there a reason not to use `*$font` as the default font blocking method? It has the desirable property of allowing easy exceptions.

**Comment by collinbarrett** [comment]
Is there a way to block all 3rd-party fonts? If I am already trusting a 1st party domain by loading their site's html, I trust them enough to load a font directly from them. I know that Fanboy Anti Fonts essentially covers this, but is there a rule that would be essentially `no-remote-fonts: 3rd-party true` (that rule does nothing, currently, that I can see) so I can ensure that all 3rd party fonts are blocked while still allowing all 1st party fonts (and not needing to create a new rule to allow 1st-party fonts for every individual site)? I've been searching for a solution for awhile for this, and haven't found anything. Thanks.

**Comment by gorhill** [comment]
`*$font,third-party`?

**Comment by collinbarrett** [comment]
@gorhill perfect, thanks.

**Comment by collinbarrett** [comment]
@gorhill , if I use `*$font,third-party` as a global rule, is there a way I can override it to allow third-party fonts when viewing a specific site? thanks.

**Comment by IDKwhattoputhere** [comment]
*$font,third-party,domain=~example.com|~example2.net

**Comment by collinbarrett** [comment]
@IDKwhattoputhere , perfect! thanks.

**Comment by atomGit** [comment]
blocking only 3rd party fonts...
`*$font,third-party`

just tried that with uBO and it won't accept the filter - i assume something has changed with the filter syntax since 2017
