### ISSUE TITLE
 The uBO button on my toolbar doesn't open the dash when I click on it. 

### ISSUE THREAD

**Issue by derrick3000** [gorhill/uBlock#3630]
The uBO button on my toolbar doesn't open the dash when I click on it. 

 Happens for every page I visit.

Screenshot in which the issue can be seen

![untitled](https://user-images.githubusercontent.com/6899670/37649659-5c6979e4-2c2a-11e8-8d4a-fdc7ac76ce41.jpg)

### Steps for anyone to reproduce the issue
As you can see, after I press it, the dash looks slightly open at the bottom of the button, as if it's hidden behind the bookmarks toolbar. I tried removing the bookmark toolbar, same thing happens. I tried putting it in the title bar, on the bookmark toolbar, anywhere it could possibly go, and it still does that.

### Your settings

- OS/version: Windows 10 pro
- Browser/version: Firefox 56.0b9 (64-bit)
- uBlock Origin version: 1.15.18

**Comment by mapx-** [comment]
Did you try updating FF to the last version ?

**Comment by derrick3000** [comment]
No I prefer not to, I tried it and my Googlebar Lite doesn't work. The problem only started yesterday. Never had a problem with my current version of FF.

**Comment by mapx-** [comment]
FF 56 is known having a lot of bugs, however in your case you could try a clean profile just to see if you still can reproduce the issue.

**Comment by derrick3000** [comment]
Just tried. Same thing on new profile. Then it auto-upgraded to latest version on FF and worked. I downgraded back to v56. No dice.

**Comment by Hrxn** [comment]
> Browser/version: Firefox 56.0b9 (64-bit)

Yeah, I can only second what has been said above. Either use latest stable or the ESR releases.
But not this version. It is outdated, and has unfixed security issues. Your "Googlebar Lite" may not work, okay, but don't complain about being "hacked" then..

**Comment by derrick3000** [comment]
Do the ESR releases work standalone or overwrite previous version of FF?

**Comment by derrick3000** [comment]
Thanks for the advice. The ESR release works great with uBO.

**Comment by gorhill** [comment]
> Firefox 56.0b9

Using the **beta** version of an **old version** of Firefox. This is an example of why the issue tracker turned into a mess.

**Comment by derrick3000** [comment]
My only concern now is the security of th ESR. Are security patches kept up-to-date on these versions?

**Comment by uBlock-user** [comment]
If you're not willing to update, expect bugs and issues which will continue to haunt.

**Comment by Hrxn** [comment]
> My only concern now is the security of this 52.7.2 ESR. Are security patches kept up-to-date on these versions?

Yes. If you use the latest, official ESR release you will get security updates.
