### ISSUE TITLE
Websites like 9to5 getting around Ublock, won't block social toolbars and webpage breaks where ads are being blocked

### ISSUE THREAD

**Issue by gh0sti** [gorhill/uBlock#3633]
### Describe the issue
websites like 9to5mac.com. 9to5google.com, and 9to5toys.com sometimes when I reload the page, ublock is properly blocking all ads and social toolbars, next time I reload, some ads are blocked and the interface shows spaces where ads were that are blocked and social toolbar shows up.

### One or more specific URLs where the issue occurs
9to5mac.com
9to5google.com
9to5toys.com

### Screenshot in which the issue can be seen
https://imgur.com/a/yEzsw

### Your settings
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
Enable cloud storage support 
I am an advanced user (required reading) 
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing 
Prevent WebRTC from leaking local IP addresses 

All filters turned on except regional ones, I also have nano defender installed and setup.
- OS/version: Windows 10 1709
- Browser/version: Chrome 65
- uBlock Origin version: latest

##### Your filter lists
all filters except international

**Comment by gh0sti** [comment]
A minute later I refreshed the page and its blocking the ads and social bar correctly 
https://imgur.com/a/PNe62

**Comment by mapx-** [comment]
for uBo filters issues report here:
https://github.com/uBlockOrigin/uAssets

Close this issue.
