### ISSUE TITLE
add feature Remove double included filter list

### ISSUE THREAD

**Issue by KonoromiHimaries** [gorhill/uBlock#3634]
example. with i download the latest [easylist.txt](https://easylist.to/easylist/easylist.txt) to my mirror and include this downloaded list to my filter list, them i have 2 the same list in my ubo control panel.

you can add some feature to not include these list in my ubo when i have the same list enabled by default?

> It is about forcing the loading of required filter lists for proper operation other filter lists
> I know that downloading the required filter lists is optional, but most users don't know how to do this
>
> https://github.com/gorhill/uBlock/issues/3622

**Comment by krystian3w** [comment]
No possible read this embedded rules in my opinion (uBlock / NA should ignore it).

**Comment by KonoromiHimaries** [comment]
@krystian3w possible, because any adblocker can read `Title: EasyList` before included
