### ISSUE TITLE
Loading a .javascript file from a WebExtension's web_accessible_resources causes a bug in Firefox that causes problems with macOS file associations

### ISSUE THREAD

**Issue by AlexanderOMara** [gorhill/uBlock#3636]
### Describe the issue

Due to [an apparent bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1448374) loading a `.javascript` file from a WebExtension's [web_accessible_resources](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/web_accessible_resources) causes problems with the macOS file associations, most notably so with TextMate 2.

This issue started with 1.15.12, specifically with commit 17930cc778c20e11fd4c760d710e8ba619aab666.

Fortunately, this issue only appears to affect `.javascript` file extensions, and not `.js` or any other extension I have tried, so avoiding the buggy behavior should be possible.

### One or more specific URLs where the issue occurs

- https://about.gitlab.com/
- https://cdn.rawgit.com/AlexanderOMara/485d4a794eb861dc36745a85503edea2/raw/523fe64b31abb33fb844bd39b771dd51b7f7d3f8/index.html (minimal example)

(Basically any page that redirects to a `web_accessible_resources` `.javascript` file, which includes pages using Google Analytics)

### Screenshot in which the issue can be seen

A screenshot cannot show the issue, but here's a video: https://www.youtube.com/watch?v=YwDoVEp1YFw

### Steps for anyone to reproduce the issue

1.  Create 2 files on your drive: `file.js` and `file.txt`
2.  Install [TextMate 2 RC 8](https://github.com/textmate/textmate/releases/download/v2.0-rc.8/TextMate_2.0-rc.8.tbz) (exact version probably does not matter).
3.  In Finder, select `file.js` and `file.txt`, click File > Get Info, and set all of them to open with TextMate, making sure to click "Change All" for each one.
4.  Make sure TextMate is not running, then open Firefox 59.0.1 (exact version probably does not matter), ideally with a new profile.
5.  Make sure uBlock Origin is installed.
6.  Verify in Finder that TextMate is still the default editor for `.js`, and `.txt` files.
7.  Go to a page that loads `google-analytics.com/analytics.js`, like [this minimal one](https://cdn.rawgit.com/AlexanderOMara/485d4a794eb861dc36745a85503edea2/raw/523fe64b31abb33fb844bd39b771dd51b7f7d3f8/index.html).
8.  In Finder, select `file.js`, and `file.txt` again and click File > Get Info and see that it has changed (you can also try opening them to confirm it has changed).
9.  Open TextMate.
10. Repeat step 8 to see it has actually changed back.
11. Reload the page from step 7 to see it change again.

### Your settings

Reproducible with default setting on a fresh profile with only uBlock Origin installed.

- OS/version: macOS 10.13.3 (native and in a clean VM)
- Browser/version:
  - Firefox 59.0.1 (Stable)
  - Firefox 60.0b5 (Developer Edition)
  - Several previous Firefox versions
- uBlock Origin version: All versions since 1.15.12 (commit 17930cc778c20e11fd4c760d710e8ba619aab666 to be precise)

##### Your filter lists

Default filter lists, specifically this rule and probably ones like it:

```
||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js
```

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
Note that in your `test-extension.zip` (as posted on bugzilla) you redirect to `war-test.javascrip`, not `war-test.javascript`. Is it a typo or does the issue really also occurs with `.javascrip`?

**Comment by AlexanderOMara** [comment]
That's a typo, thanks for the heads up!

**Comment by AlexanderOMara** [comment]
I've updated the Gist and the attachment on Bugzilla to reflect the code I used for testing. Thanks for pointing that out.

**Comment by gorhill** [comment]
1.15.19b2 contains the fix. If you want to confirm that it works, it's at: <https://github.com/gorhill/uBlock/releases/tag/1.15.19b2>.

**Comment by AlexanderOMara** [comment]
Indeed it does fix the issue! Awesome! Thanks!
