### ISSUE TITLE
Updates Since 1.15.19b0 All Require Restart

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#3637]
### Describe the issue

All releases since 1.15.19b0 now require a browser restart, this was never the case before. Did something change that requires this?

![image](https://user-images.githubusercontent.com/5274181/37849241-26c9b51c-2e94-11e8-9b34-a5b8e43883a9.png)

After .19b1 I posted on Mozilla Support asking instead of opening an issue but didn't hear back, so figured it was a one-off but it happened just now again with .19b2 so wondering what happened? TIA.

**Comment by gorhill** [comment]
> Did something change that requires this?

No.

**Comment by GuardianMajor** [comment]
Thank you, but it is odd, suddenly started happening and I have changed nothing on my end and was wondering if it was by design. So we can rule that out.

Any thoughts on the observed behavior above? Same browser (FX 56.0.2 x64) and always on the "dev" version of uB0 (WebExt) version but suddenly the updates are requiring restart. Do you know of any setting in FX for example that would make this kind of behavior happen, so I can check to see if that got flipped somehow?

Any thoughts on how I can make it reproducible or figure out the cause so I can share? All I know is that it is happening for me and I am stumped. Thanks for any assist.

**Comment by quilloss** [comment]
I had this happen before on every single update but it fixed itself when Firefox update. Maybe it is a bug in Firefox 56.

**Comment by krystian3w** [comment]
I have sometime similar bug with other addons in WebExtesion standard.

**Comment by GuardianMajor** [comment]
@krystian3w I am hoping that by any chance you found what was causing it, or can point me to the related discussions so I can hopefully surmise what might be the potential cause? Thank you.

**Comment by gorhill** [comment]
It was found this is a combination of factors causing the issue. See <https://github.com/ghacksuserjs/ghacks-user.js/issues/399#issuecomment-383139093>.
