### ISSUE TITLE
parameters do not work with directive

### ISSUE THREAD

**Issue by KonoromiHimaries** [gorhill/uBlock#3638]
![2018-03-24-ublock asset](https://user-images.githubusercontent.com/5884000/37866299-31936a38-2f89-11e8-9671-12868c1fdc86.png)
`https://raw.githubusercontent.com/KonoromiHimaries/polish-ads-filter/patch-1/test/test.txt`

Win 10
uBO 1.15.24

> it will be a great addition for it
> https://github.com/gorhill/uBlock/issues/3622

**Comment by gorhill** [comment]
Support for directives are in latest dev build.
