### ISSUE TITLE
[Suggestion] Emphasize the crapware risk via different strict blocking page layout

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#364]
Now, that there will be a filter list dedicated to sites documented as crapware risk, I think it would be very informative to tell the user explicitly that the site is being blocked because it is found to be a crapware.

Most of the sites won't be affected by this, because this message will only come to the front from sites that were manually added to this list by you/contributors, which is of course a small amount of sites.

This will drastically improve the web as a lot of people will probably just dismiss the strict blocking page and skip it for the most part, but if they will be warned that this site can be dangerous in the most simple way (I'm thinking about a red triangle instead of an orange one, or maybe something with a red background like Chrome's malware warning page?), I am sure they will put more consideration to it.

Thanks gorhill.

**Comment by gorhill** [comment]
> I think it would be very informative to tell the user explicitly that the site is being blocked because it is found to be a crapware.

That's exactly why I named the filter list **uBlock filters -- Adware/crapware risks**: the name of the filter list of why the site is blocked will be shown under the filter.

**Comment by Mikey1993** [comment]
@gorhill I am focusing here about raising more awareness of the crapwareness of a documented site to the simple users more alarmingly than just presenting the same layout and icons of the strict blocking page, and not about the reason as it's already presented to date.

**Comment by gorhill** [comment]
I don't see the point of "emphasizing": all is there to warn a user: the blocked page, the name of the filter list(s). The whole purpose is to give a gentle reminder to the user of where he is heading. There is no point overdoing it.

**Comment by Mikey1993** [comment]
> The whole purpose is to give a gentle reminder to the user of where s/he is heading.

IMHO, when dealing with crapware and the average user, you should be more explicit about it, just like Chrome does with their anti malware system.
