### ISSUE TITLE
Settings are reset/forgotten frequently

### ISSUE THREAD

**Issue by abrkn** [gorhill/uBlock#3643]
### Describe the issue

My advanced settings are forgotten.

Before reset:

![image](https://user-images.githubusercontent.com/843958/37890651-3cd0065c-310c-11e8-83cd-b085679209bd.png)

After reset:

![image](https://user-images.githubusercontent.com/843958/37890839-fd93552e-310c-11e8-8e80-43803c8f810f.png)

Happens a few times a week. Driving me insane. Here are my settings:

![image](https://user-images.githubusercontent.com/843958/37890870-10b538ac-310d-11e8-8e93-1fa1cffe156b.png)

![image](https://user-images.githubusercontent.com/843958/37890882-17296884-310d-11e8-9eaa-b026f8f2f5b9.png)

**Comment by gwarser** [comment]
Lock button in top left corner.

**Comment by uBlock-user** [comment]
That padlock is there to ensure they're not forgotten.

**Comment by abrkn** [comment]
Well now I feel silly.
