### ISSUE TITLE
Don't block Tag Manager's by default, block the third party vendor's which are loaded through them

### ISSUE THREAD

**Issue by corbinspicer68** [gorhill/uBlock#3644]
Tag manager's are currently blocked such as TealiumiQ, GTM etc.

Some tag manager's execute javascript which enhance the user experience, or even automatically apply discount codes etc, instead you should concentrate blocking the third party vendors which are loaded through them.

I know for a fact that TealiumiQ does not store any information about any user, but may use extensions to personalise the user's experience.

**Comment by Atavic** [comment]
Policies, for privacy: https://tealium.com/privacy/
and cookies: https://tealium.com/cookie-policy/
