### ISSUE TITLE
Troubles clearing "My filters" list on Firefox for Android

### ISSUE THREAD

**Issue by superlex** [gorhill/uBlock#3646]
Hi!

### Describe the issue
I encounter many difficulties when I clear the list:
- when a line is finished, the deletion doesn't continue in the previous line;
- selecting the entire text, it can not be deleted;
- selecting and cutting the entire text, it disappears and reappears.
Maybe a "Clear" button could help.
However, I don't find these issue on Firefox for Desktop.

### Steps for anyone to reproduce the issue
1. Go to "My filters" tab;
2. Select the entire text;
3. Try to delete it.

### Your settings
- OS/version: Android 7.1.2
- Browser/version: Firefox 59.0.2
- uBlock Origin version: 1.15.18

##### Your filter lists
Default filter lists

**Comment by superlex** [comment]
> I clicked "Select All", then I deleted using Backspace
Me too. With uBlock Origin 1.15.10 it works fine, but with uBlock Origin 1.15.18 the text doesn't disappear. 
On the contrary, on Firefox for Desktop both .10 and .18 work fine. The behavior is different also because on Firefox for Desktop when a line is finished, the deletion continues in the previous line,
while on the contrary on Firefox for Android when a line is finished, the deletion doesn't continue in the previous line.

**Comment by gwarser** [comment]
1.15.19b2
Android 7.1.2

 - select all "My Filters"
 - press backspace
 - page blinks white, and nothing happens

**Comment by gorhill** [comment]
I already asked above and no answer so far: How do you select the entire text?

**Comment by superlex** [comment]
> How do you select the entire text?

1) Single click in the text: the keyboard appears;
2) long pression with finger -> "Select All" .

@gwarser 

> page blinks white, and nothing happens

I don't understand: do you have the same issue or are you not able to reproduce it?

**Comment by gorhill** [comment]
> Single click in the text: the keyboard appears;

Ok I do it differently, hence I could not reproduce. With you way however, the keyboard disappears,so I cannot press the backspace key.

On my side:

1. Set focus to the editor
1. Tap and hold anywhere in the editor
1. Android widget appear: select 3-dot menu and click "Select all"
1. Tap backspace key
1. All filters are gone

**Comment by superlex** [comment]
> Single click in the text: the keyboard appears;

sorry, I meant in the text in order to _set focus to the editor_ me too;

> long pression with finger

as you, I meant _tap and hold anywhere in the editor_

> Android widget appear: select 3-dot menu and click "Select all"

me too

> Tap backspace key

me too

> All filters are gone

they are still there in my case.

**Comment by gwarser** [comment]
For me: 

 - Set focus to the editor (tap on it) - keyboard appears
 - Scroll up a bit, because I see only one line
 - Tap and hold anywhere in the editor
 - Android widget appear: select 3-dot menu and click "Select all"
 - Tap backspace key (keyboard is visible all the time)
 - text and gutter flashes white and moment later are back - not sure this is graphics issue or text is really deleted and then reappear.

**Comment by superlex** [comment]
> text and gutter flashes white and moment later are back - not sure this is graphics issue or text is really deleted and then reappear.

yes, and the button "Apply changes" doesn't become yellow.

**Comment by gorhill** [comment]
Ok I think I understand now what is happening. The last fix attempt won't work, I did this before I understood what was happening. The issue is when there is more text than can fit in the editor. When selecting all, for some reasons only the visible portion of the text is selected, meaning deleting what is selected won't delete all. I need to read more about CodeMirror to figure what to do. I need to revert the fix attempt, things are worse now.

**Comment by superlex** [comment]
I confirm that if there is less text than can fit in the editor (e.g only 2-3 entries) it works well.
Thanks for the investigation.

**Comment by gorhill** [comment]
It took a lot of trial/error but I think what is there now (1.15.19b7) is acceptable for the current issue:

- One tap in the gutter will select the associated line.
- Two taps in the gutter will select all -- so no need for the contextual menu which confuses the editor.

**Comment by superlex** [comment]
Ok, thanks.

For now I'm trying 1.15.19b8:

> One tap in the gutter will select the associated line

Yes

> Two taps in the gutter will select all -- so no need for the contextual menu which confuses the editor.

Yes, two taps in the gutter select all, but when press backspace the text doesn't disappear.

**Comment by gorhill** [comment]
> when press backspace the text doesn't disappear

That is something I am unable to reproduce -- works every time on my side. Somebody who can reproduce will have to investigate.

**Comment by superlex** [comment]
I think my backspace triggers the backspace keyboard event because everytime I press it the text flashes one time, as @gwarser said in the previous comment.

**Comment by gorhill** [comment]
After you select all using the double-tap on gutter, what happens if you press space character?

**Comment by gorhill** [comment]
Note that I use [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard), maybe this makes a difference.

**Comment by gwarser** [comment]
Works on first line. 

Not on others.

When I select line 3 by taping on gutter, "4" turns darker, and after backspace, line disappears, numbers on gutter changes to 1,2,2,3,4... page starts to be laggy, after taping and scrolling all text in editor and gutter disappears, only reload helps.


Double tap on gutter + backspace - text disappears (only "1" on gutter stays visible) and reappears after moment.

**Comment by gwarser** [comment]
Space is working! Text is removed, only space is inserted.

**Comment by superlex** [comment]
With AnySoftKeyboard backspace works well.
With AOSP keyboard (LineageOS default keyboard) and GBoard only space works, as regards backspace I confirm that _text disappears and reappears after moment_.

**Comment by gorhill** [comment]
Seems like backspace is often an issue on Android, as per Android design: <https://github.com/codemirror/CodeMirror/issues?q=is%3Aissue+backspace+android+is%3Aopen>.

So for now we will have to use space to delete stuff when backspace does not work.

**Comment by gwarser** [comment]
AOSP keyboard must be broken.different keyboard is working fine.

**Comment by superlex** [comment]
Another difference is that with AnySoftKeyboard when a line is finished, the deletion continues in the previous line, with AOSP and GBoard it doesn't.
