### ISSUE TITLE
ublock breaks fastback feature on latest Android nightly 

### ISSUE THREAD

**Issue by ale82to** [gorhill/uBlock#3647]
### Your settings

- OS/version: 
- Browser/version: 
- uBlock Origin version:

**Comment by ale82to** [comment]
### Screenshot in which the issue can be seen



### Steps for anyone to reproduce the issue



### Your settings



- OS/version: 
- Browser/version: 
- uBlock Origin version: 

##### Your filter lists



##### Your custom filters (if any)

**Comment by ale82to** [comment]
enabling ublock origin on latest Android nighlty 61 breaks fastback feature for example go to APKMirror.com click any links and then hit the android back button while going to previous page it reloads,disabling ublock origin previous page is loaded immediately,restoring last week nighlty 61 version also fixes the issue

**Comment by gorhill** [comment]
Will assume filter or site issue. The front page of `apkmirror.com` never finishes loading completely, so navigating back to it will just bring back the never-finish-loading behavior.
