### ISSUE TITLE
Latest ublock opens some browser windows in new windows

### ISSUE THREAD

**Issue by IsaakGroepT** [gorhill/uBlock#3648]
### Describe the issue
At random some browser windows open in a new window with minimal GUI interface, in the way that it doesn't show all tool- and menubars. Happens in both Firefox (older and newest version) and chromium based browsers, and thunderbird. In windows and linux on any hardware. Android seems unaffected

### One or more specific URLs where the issue occurs
any url with ublock origin enabled and at random it happens
example:
startpage.com

### Screenshot in which the issue can be seen
https://image.tf/show/nCAAqrmm9vNaQLh9

### Steps for anyone to reproduce the issue

1. surf to startpage.com
2. search for something, for example: test
3. open the wikipedia result page as an example, but happens with any website at random and on any other website than startpage.com
4. see it happen quite frequently

Disabling ublock orgin doesn't trigger this issue for me

### Your settings
Happens with default settings and customised settings (for example: custom list, advanced user mode enabled,...)

- OS/version: windows 7 pro 64 bit, linux 64 bit
- Browser/version: firefox, chromium, thunderbird. any version of them it seems
- uBlock Origin version: latest

##### Your filter lists

Default filter lists

**Comment by mario-d-s** [comment]
Issue can be reproduced in Firefox 59.0.2 64-bit on Windows 10 professional version 1709.

For me though, it happens **really** infrequently (using the provided steps by @IsaakGroepT). I'd estimate about once every 20-30 links I click on startpage.com.

In the popup window without toolbars, the first line in the dev console is:
> The resource at “https://app-abb.marketo.com/js/forms2/js/forms2.min.js” was blocked because tracking protection is enabled. [[Learn More]](https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

This line does not appear when the link works as expected.

Unfortunately I can't figure out how to get to the uBlock console from the window without toolbars.

**Comment by gorhill** [comment]
I am closing this as _invalid_.

I've never experienced such an issue, and from the description provided there is not actual evidence that uBO is causing this reportedly infrequent behavior.

To make the case there is an issue in uBO rather than something else specific on your side, there need to be at least basic investigation using the logger -- as this could be a case of malware, a side effect of a filter issue, etc.
