### ISSUE TITLE
Remove Jasmin.com and Livejasmin.com from the list

### ISSUE THREAD

**Issue by marcotonetti** [gorhill/uBlock#3649]
### Describe the issue
Jasmin.com and Livejasmin.com are in the block list. They should be not instead.

### One or more specific URLs where the issue occurs

https://easylist.to/easylist/easylist.txt

### Screenshot in which the issue can be seen

-

### Steps for anyone to reproduce the issue

-

### Your settings

-

##### Your filter lists

-

**Comment by Havokdan** [comment]
Report this to anyone who keeps the list. Not Here.

**Comment by Betsy25** [comment]
For problems with easylist, [https://forums.lanik.us/](https://forums.lanik.us/)

**Comment by mapx-** [comment]
@ryanbr @monzta

**Comment by marcotonetti** [comment]
@Havokdan can you clarify who could I should report to?

**Comment by ryanbr** [comment]
Jasmin.com / Livejasmin.com are notorious for generating popups, why should it be removed? Its specifically for third-party content, so it won't affect the site.

**Comment by Havokdan** [comment]
> @Havokdan can you clarify who could I should report to?

@Betsy25  already answered.

**Comment by gorhill** [comment]
> the fact is that **they create adverts**

The purpose of EasyList is to block ads.
