### ISSUE TITLE
The European Portuguese translation has been reverted to an outdated spelling

### ISSUE THREAD

**Issue by Sukigu** [gorhill/uBlock#365]
I love translating and I love uBlock. Seeing as its translation is being actively maintained, I've refrained from participating in its Crowdin project, however I had to go check there today since I've noticed some European Portuguese strings have been reverted to follow outdated spelling rules which, as of May 13, 2015, are no longer officially accepted in Portugal. [Here's one of many sources](http://economico.sapo.pt/noticias/acordo-ortografico-passa-a-ser-obrigatorio-em-portugal_218195.html): "Spelling reform becomes mandatory in Portugal".

Independently of one's personal opinions for or against them, the new rules are being actively used virtually everywhere: the media use them, kids learn them in school, and all tech companies are implementing the reform. For instance, Google, Microsoft, Facebook and Mozilla have fully adopted them in their products, so Windows, Firefox and Chrome, where many uBlock users have it installed, all use the new spelling.

From what I can infer from [some discussion](https://crowdin.com/translate/ublock/13/enca-pt#233) I've come across, it seems that Crowdin user cristiano04 was promoted to proofreader and promptly deleted (not even simply disapproved) the previous, correct strings, scrapping the other proofreader (SW1FTmeister)'s work.

For the reasons above, I think cristiano04's permissions on Crowdin should be revoked so SW1FTmeister can do his job as usual.

**Comment by SW1FT** [comment]
Thank you for bringing this to light here on GitHub, I also want to point out that smarquespt did a lot of the work that was reverted as well.

I'll be working on the translation as soon as @gorhill removes cristiano04's permissions or he apologizes for starting all this drama and for his general attitude towards the project.

**Comment by gorhill** [comment]
> For the reasons above, I think cristiano04's permissions on Crowdin should be revoked so SW1FTmeister can do his job as usual.

Done.

**Comment by SW1FT** [comment]
Thank you @gorhill, I've re-added all the A.O translations back and everything should go back to normal when you import the changes.

**Comment by 0xBRM** [comment]
@gorhill The orthographic agreement was imposed on the nation without a referendum and is being boycotted as we speak. [Only 30% of the population agree with it.](http://blogtailors.com/2406945.html)

@SW1FT 

> or he apologizes for starting all this drama and for his general attitude towards the project

Fuck off cuck. People like you who stand idly by whilst ancient cultures are stepped on by the powers that be in unconstitutional ways make me sick. You are an enemy of freedom.

**Comment by gorhill** [comment]
> Only 30% of the population agree with it.

That's from March 2009. How is it more than six years later?

**Comment by CrisBRM** [comment]
It's worse because the trial period has just ended. I have no statistics to back this up as that was the only study of its sort, but given the public unrest it's safe to assume nothing has changed.

**Comment by gorhill** [comment]
Here is one thing I could do, since I can't possibly decide for a whole other people: everybody become translator, and the translation with the most vote will be the one automatically picked. That will sort if out for me, and whatever people vote for will be what is used.

**Comment by CrisBRM** [comment]
Hardly fair, considering there are only 4 translators and 3 of them are pro-OA.

**Comment by gorhill** [comment]
It's better than me deciding something I should not have to decide, and more fair than one translator  deciding for all. The way I see it, the majority who cares to vote will decide.

**Comment by Sukigu** [comment]
As I stated in my initial message, you shouldn't make these decisions based on personal preference. What matters is that the trial period has effectively ended and most products are using the new spelling already. Why does my browser and operating system use "ativar" and only uBlock uses "activar"?

Having someone that oversees approved translations is always good to achieve some level of consistency, so I vote that SW1FTmeister be kept proofreader, as he seems to be making the most rational choices. It doesn't have much to do with the fact that he's for or against the reform.

**Comment by CrisBRM** [comment]
@Sukigu only 30% of the country supports something that didn't pass a fucking referendum, yet I'm being accused of making a decision 'based on personal preference'.

**Comment by SW1FT** [comment]
A.O is official, it's no longer an option as of May 2015. The transition period is over. You had 6 years to adapt to it, if you couldn't, then it's not my fault, I'm sorry.

> Fuck off cuck. People like you who stand idly by whilst ancient cultures are stepped on by the powers that be in unconstitutional ways make me sick. You are an enemy of freedom.

And this is why we can't have you as a proofreader. You're just mad because you don't like the A.O, I get it, I don't like it as well because I needed to re-learn to write some words, but that doesn't make me deny the fact that it exists and it's the way we need to write from now on. Please refrain from irrational thinking and try to be an impartial translator, if you can't do it, don't translate anything on uBlock Origin. Thank you.

**Comment by CrisBRM** [comment]
@SW1FT Actually, from a legal standpoint, it only ends in [September 2016](http://www.publico.pt/portugal/noticia/o-acordo-ortografico-de-1990-nao-e-obrigatorio-a-partir-de-13-de-maio-de-2015-1695336). It was also postponed in Brazil. :^]

**Comment by Sukigu** [comment]
@CrisBRM, that **is** everyone's personal preference. What's official, however, is that the old rules shouldn't be used anymore. I don't agree with 100% of the changes, but I use them all, because I'm not going to cherry-pick what I like and what I don't. For standardization, there's the official, prescripted rules. In your own writing, you're free to write however you want.

I don't have links at the moment, but there were two separate documents which stated: a) The trial period was 6 years; b) The rules started to be applied on May 13, 2009. That made the past month be considered the end of the adaptation period. In Brazil (as in every other Portuguese-speaking country), there are different periods. There, it ends on January 1, 2016.

**Comment by CrisBRM** [comment]
@Sukigu 
>What's official, however, is that the old rules shouldn't be used anymore. 

Sorry, I don't endorse cuckoldry. No referendum, no care. The majority of the country seems to agree with me. They will revert this at some point.

>In Brazil (as in every other Portuguese-speaking country), there are different periods. There, it ends on January 1, 2016.

Incorrect. It was postponed last year, in December.

>a) The trial period was 6 years

Yes, refer to http://www.publico.pt/portugal/noticia/o-acordo-ortografico-de-1990-nao-e-obrigatorio-a-partir-de-13-de-maio-de-2015-1695336

**Comment by SW1FT** [comment]
@CrisBRM Ok, fair point, however why should we live in the past if we can live in a future-proof present? You're gonna make me change all the translations back again to non-A.O now, and back again to A.O in September 2016? I'm sorry but I won't do it. I'll stick with what we have now because it's what most products have as well, which is the A.O version. You're the only person in the uBlock translation project voting non-A.O, if you didn't realize already.

**Comment by CrisBRM** [comment]
>You're the only person in the uBlock translation project voting non-A.O, if you didn't realize already.

Ah, yes... A sample size of 4 people, how accurate...

**Comment by SW1FT** [comment]
> Ah, yes... A sample size of 4 people, how accurate...

Already gave you plenty of other arguments, you don't accept none.

**Comment by CrisBRM** [comment]
@SW1FT 
>you don't accept none

So I did accept all of them? Flawless English, as I would expect from a cuck.
You've given me no valid arguments. All of them boil down to 'B-BUT IT'S THE LAW NOW! WE MUST ABIDE BY THE LAW!' when what they did is/was unconstitutional and a vast majority of the populace disagree with it. Fucking authoritarian vermin trying to impose their will on the masses. 
Can't wait for the day a lawful command is issued for all cucks to jump off a bridge.

**Comment by SW1FT** [comment]
> So I did accept all of them? Flawless English, as I would expect from a cuck.
You've given me no valid arguments. All of them boil down to 'B-BUT IT'S THE LAW NOW! WE MUST ABIDE BY THE LAW!' when what they did is/was unconstitutional and a vast majority of the populace disagree with it. Fucking authoritarian vermin trying to impose their will on the masses.
Can't wait for the day a lawful command is issued for all cucks to jump off a bridge.

You don't deserve any valid arguments now. I'm not even gonna bother criticizing your attitude because it's pretty clear. 

@gorhill I think you now know who you can trust.

**Comment by CrisBRM** [comment]
@SW1FT Don't forget to tip your fedora on the way out, bootlicker.

**Comment by Sukigu** [comment]
Público [Portuguese newspaper] has always been anti-reform, so it doesn't surprise me that they're presenting their own "conclusions" with no official statement to back them. Those two documents I mentioned were published in Diário da República [where Portugal's legislative texts are published] and thus, the only possible conclusion is that the trial period has ended in May.

And again, Brazil abides by different laws. The last change to their adaptation period was made [in December 2012](http://educacao.estadao.com.br/noticias/geral,dilma-adia-para-2016-implantacao-definitiva-do-novo-acordo-ortografico,978484), when it was about to expire, extending it to the end of this year.

Anyway, just by the way you speak, it doesn't seem you're mature enough to have a serious discussion and I wouldn't want you to coordinate my work's translations.

**Comment by gitarra** [comment]
@CrisBRM Maybe you should go exercise your freedom of speech and protest elsewhere. I dont think anyone here cares.

You dont seem like a person that should do any translation work.
