### ISSUE TITLE
Will OptinMonster be blocked even when click triggered?

### ISSUE THREAD

**Issue by joneslloyd** [gorhill/uBlock#3653]
I saw [this exchange](https://twitter.com/dohertyjf/status/979385256351432704), and was wondering if [OptinMonster](https://optinmonster.com/) will be blocked even when the user explicitly clicks to trigger it?

For example, we use OptinMonster solely for [triggering modals](https://giphy.com/gifs/Xtf4oXxks7Tir81HII/fullscreen) when the user makes the informed decision to do so, and to block this would seem unfair on the face of it.

Any clarification here would be great.

**Comment by uBlock-user** [comment]
uBlock didn't block it, it's blocked Peter Lowe's Ad and Tracking Server List

cc @pgl

**Comment by joneslloyd** [comment]
I see! Okay – Is there a way I can put this case (my ticket) forward as an 'appeal' to not block it in all instances?
