### ISSUE TITLE
Tomshardware only rendering properly the first time

### ISSUE THREAD

**Issue by jpluimers** [gorhill/uBlock#3657]
### Describe the issue

Any Tomshardware page only displays correctly the first time Chrome starts. Any future loads give some really large UI elements and the CSS is screwed.

As soon as I disable uBlock origin, then it displays fine.

It also displays fine in incognito mode (which has no uBlock origin).

I will likely need some guidance on how to approach investigating the cause, so any help is much appreciated.

I'm not sure when this started, but it is quite a while ago (think months rather than weeks), it's just that I do not use Tomshardware as frequently any more as a few years back.

### One or more specific URLs where the issue occurs

- http://www.tomshardware.com/news/ssd-price-drops-512gbit-hmb,36266.html
- http://www.tomshardware.com

### Screenshot in which the issue can be seen

Second and up time load:

![screenshot 2018-03-31 18 07 58](https://user-images.githubusercontent.com/2033367/38165220-8dbc728c-3510-11e8-8be4-80957490f404.png)

First time after Chrome restart:

![screenshot 2018-03-31 18 11 48](https://user-images.githubusercontent.com/2033367/38165219-84896210-3510-11e8-9f2f-87552c4399b5.png)

### Steps for anyone to reproduce the issue

1. Start Chrome
2. Ensure uBlock has default settings (go to [chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#settings.html](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#settings.html), click the button "Reset to default settings...")
3. Load any Tomshardware URL: only after a fresh browser restart you get the second image
4. Load the same URL again in the same or second tab

Often the page displays correctly for less than half a second, then displays like the first image.

#### Things I tried (didn't make a difference):

- disable all 3rd party filters.

### Your settings

Default settings.

- OS/version: MacOS Sierra 10.12.6
- Browser/version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- uBlock Origin version: v1.15.18

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

None

**Comment by jpluimers** [comment]
I was wrong. Disabling this 3rd party filter makes tomshardware working again: chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=easylist

Apparently testing various permutations of disabling 3rd party filters, I forgot to refresh the test page.

**Comment by WowDude** [comment]
I can't reproduce the issue on default settings, only can reproduce after blocking the website's main stylesheet by a custom filter like: `||www.tomshardware.com/g00/*$stylesheet,first-party`, EasyList enabled/disabled doesn't make any difference.

**Comment by jpluimers** [comment]
@WowDude I was right after all: EasyList does not matter: first page load is OK; page reload (Command-R or Command-Shift-R) fails consistently.

**Comment by jpluimers** [comment]
Thanks @WowDude for the help so far.

I think I found it: flash block clashes with uBlock Origin.

Disabling https://chrome.google.com/webstore/detail/flashblock/cdngiadmnkhgemkimkhiilgffbjijcie from setting chrome://extensions/?id=cdngiadmnkhgemkimkhiilgffbjijcie makes tomshardware consistently work.

Will update when I find more. For now it looks good.

**Comment by gorhill** [comment]
Two things:

- Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to diagnose filter issues.
- `tomshardware.com` is afflicted by [Instart Logic](https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful), install [uBO-Extra](https://github.com/gorhill/uBO-Extra) -- this is most likely your issue.
