### ISSUE TITLE
Default value of suspendTabsUntilReady allows ads and malware to be loaded during browser startup 

### ISSUE THREAD

**Issue by jnk0le** [gorhill/uBlock#3658]
### Describe the issue

Default value of suspendTabsUntilReady is set to `false`. It allows browser to delay initialization of uBlock during startup and by the time it's not ready, a webpage with all scripts/ads is being loaded.

Normally it means wasted mobile transfer and refreshing current page but users would also face with; regular phishing, 0-days or even "YOUR ANDROID IS IN DANGER" ads that completely blocks browser/system interface until you pay them money "to fix all your issues & dangers". It's not only the case for typical Torrent&Porn websites since malware-through-ad-injection attacks were distributed through legit ad-platforms and websites for a very long time.

### One or more specific URLs where the issue occurs

Almost ewerywhere where malware or ads are present.

### Screenshot in which the issue can be seen

Random site after ff restart, in clean virtualbox installation which is way harder to reproduce than native os:
![virtualbox_session_startup](https://user-images.githubusercontent.com/10984660/38168180-87bae370-3545-11e8-922d-9dda36b647e4.png)

And after refreshing page:
![virtualbox_after_refresh](https://user-images.githubusercontent.com/10984660/38168185-9a8ce9da-3545-11e8-9600-02a2369cbe47.png)

### Steps for anyone to reproduce the issue

0. install browser/uBlock
1. Configure browser to recover previous session at startup.
2. Open a page that should have a lot of ads. 
2,5. If step 5 doesn't work as expected; open 20+ random pages and pick the last one.
3. Close browser.
4. Start browser.
5. Observe that even though ublock have blocked a lot of requests, it ist still less than after refresh and most of the ads are still beeing displayed (probably depends on internet/hdd speeds, size of the session and type of the ads itself).
6. Repeat with `suspendTabsUntilReady` set to `true`.
7. There are no more ads displayed.

### Your settings

- OS/version: Windows 10 and also Android
- Browser/version: Firefox 59.0.2
- uBlock Origin version: v1.15.18
- ca. 150/100 mbps internet
- and typical 640GB seagate hdd

Probably valid for ony OS and any browser that delays addon initialization to speedup own startup.

##### Your filter lists

Default lists + NoCoin

##### Your custom filters (if any)

Advanced settings:  `suspendTabsUntilReady`

**Comment by gorhill** [comment]
Baffling.

The wiki doc mentions these words in relation to that setting: "experimental", "impossible for uBO to guarantee".

**Comment by uBlock-user** [comment]
> Default value of suspendTabsUntilReady allows ads and malware

No value can ever have that sort of power over ads and malware.

**Comment by jnk0le** [comment]
Blocking whole domains (add filter for google.com and visit it) seems to always work as expected regardless of that setting.

Is there a case when `suspendTabsUntilReady` is set to true, something is not blocked, especially after restarting connections?

**Comment by gorhill** [comment]
- https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue+suspendTabsUntilReady
- > "Warning! Change these advanced settings at your own risk. [link](https://github.com/gorhill/uBlock/wiki/Advanced-settings)"
- <https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental>:
    > **This is a by-design browser issue** -- do not open an issue on uBO issue tracker about this.

Your issue here is just a confirmation of why [the issue tracker ended up being unmanageable](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by jnk0le** [comment]
Ok, as I understand reliability of this option in terms of security is browser related, but in almost every case it suppresses all annoying ads.

**Comment by uBlock-user** [comment]
> but in almost every case it suppresses all annoying ads.

that's because, in those cases, the extension loads **first** before the page loads, and when it doesn't, you see ads..
