### ISSUE TITLE
Add exception for specific filter on per-page basis

### ISSUE THREAD

**Issue by reallyuniquename** [gorhill/uBlock#3659]
I have a filter `||mydomain.com/js/stuff.js$script,domain=mydomain.com` that blocks `mydomain.com/js/stuff.js` on domain `mydomain.com`. 

Now I'd like to add exception for this rule i.e. allow that script but only on specific page (URL) on the same domain e.g. `https://mydomain.com/html/important_page.html`.

I've spent some time googling and looking through the wiki, had no success though. At first I thought ABP `document` exception modifier would help me but it is not available in uBlock and moreover it's not filter-specific.

So how do I approach this?

**Comment by gwarser** [comment]
You can whitelist specific page by ctrl + click on _power_ button i UBO popup (or paste URL in _Whitelist_ tab in UBO settings)

**Comment by reallyuniquename** [comment]
@gwarser I don't want to disable every rule, only specific one and for one exact page.

**Comment by joey04** [comment]
This capability doesn't exist. Very niche use case that you'd have to create for yourself, i.e. you can fork and modify.

**Comment by uBlock-user** [comment]
Not possible, such granularity doesn't exist.

**Comment by reallyuniquename** [comment]
Well that's unfortunate. 

Any workaround ideas e.g. blocking resources on per-page basis?

**Comment by gorhill** [comment]
The key expression from @joey04: "very niche use case". It's not worth implementing if there is no real use cases which are beneficial to more than very specific need from a handful of users. Notice that no use cases to solve real actual issues affecting all users has been provided.
