### ISSUE TITLE
I can not download file from Sourceforge

### ISSUE THREAD

**Issue by phuc365** [gorhill/uBlock#366]
I can not download Portable from Portableapps.

e.g. http://portableapps.com/apps/utilities/crystaldiskinfo_portable

I receive a message like this when trying to download it.

http://s4.postimg.org/e77427031/Capture.png

<b>Thank you for your interest.</b>

**Comment by androidland** [comment]
http://blog.tedd.no/2014/11/25/sourceforge-malware/

you can temporaly disable ublock or disable ublock filter

**Comment by gorhill** [comment]
> I receive a message like this when trying to download it.

Read carefully the message.
