### ISSUE TITLE
Support for Firefox Containers

### ISSUE THREAD

**Issue by marpala** [gorhill/uBlock#3660]
I think it might be useful to be able to set different rules (or just modes) for each container.

For example, you could have uBlock running in easy or medium mode in all containers, and then have a container named "Hard mode" where everything is blocked by default.

I know this is achievable by using different profiles, but containers offer a more granular yet simpler experience.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/3091
