### ISSUE TITLE
Mailchimp Signup Form Blocked

### ISSUE THREAD

**Issue by swidnikk** [gorhill/uBlock#3662]
### Describe the issue
uBlock Origin is blocking a mailchimp newsletter signup form. I do not recall this behavior while developing the site and curious if there is anything I can do with my form so that it shows up or if recent ublock origin update caused this behavior. 

### One or more specific URLs where the issue occurs
http://generation.blue

### Screenshot in which the issue can be seen
na

### Steps for anyone to reproduce the issue
1. Visit http://generation.blue 
2. No signup form visible at the bottom of the page.
3. Disable ublock origin
4. Refresh page
5. Signup form present at the bottom of the page. 

### Your settings
default

- OS/version: 
OS Sierra 10.12.3 

- Browser/version: 
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

- uBlock Origin version: 
1.15.18

##### Your filter lists
default

##### Your custom filters (if any)
na

**Comment by mapx-** [comment]
for filters issues don't use anymore this repository but:
https://github.com/uBlockOrigin/uAssets/issues
and now please close the issue

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9facf95fa4ac6de3c761eb384bbcb37891dbd9c6
