### ISSUE TITLE
Create a version for Palemoon/basilisk/legacy Forks of UBO before plan to drop support for Firefox/legacy once Firefox 60 ESR is released for users who prefer those browsers

### ISSUE THREAD

**Issue by kamuferepe** [gorhill/uBlock#3666]
Hi @gorhill @Deathamns @chrisaljoudi 
Thanks for making and maintaining such a wonderful Adblocker!

As a user of Palemoon/basilisk/waterfox which is well maintained and provides better UX on my laptops
can  you guys please Create a version for Palemoon/basilisk/legacy Forks of UBO before the plan to drop support for Firefox/legacy once Firefox 60 ESR is released for users who prefer those browsers
An update to latest release once a few months or bug fix mode might be enough(security updates and fixes)
as the code base will/shall not change much as the browsers are forks.

Please consider us users who are in the minority here

P.S:- can you guys upload it to the respective store

https://addons.palemoon.org/extensions/

**Comment by joey04** [comment]
As a [XUL forker of uBO](https://github.com/joey04/xulBlock-Advanced) who [also proposed a uBO-alike fork](https://github.com/joey04/xulBlock-Advanced/issues/2), I must say that this may be the biggest facepalm issue on this tracker yet. You do realize you're asking gorhill to not only completely reverse his decision to drop XUL support (which he's been stating he would for months) but also host it at Tobin's addon site? Legit LOL!

But on a serious note, the fact that you pinged Deathamns is a good opportunity to recognize his important work on uBO. He did a lot of the gory browser interface stuff that's been rather stable for several years on XUL (certainly for my abundant use on Pale Moon). All of us on Firefox forks owe him a debt of gratitude. And while I'm at it, the same goes for Alex Vallat who also made important contributions to the XUL version.

**Comment by kamuferepe** [comment]
sorry am I missing something here?
@joey04 current legacy works so can't it be maintained like a simple fork with fixes here and there without interfering with ubo webext? just for Palemoon/basilisk.
what;s with tobin? some bad blood?

sorry for silly questions.

**Comment by joey04** [comment]
@kamuferepe -- I appreciate your good humor here.

Honestly, if you want to contribute on this front you'll need to learn the history of this project and its XUL version. Plan on at least several hours of reading (and that's assuming you're already a proficient uBO user). The two links I've provided are a good starting point.

**Comment by kamuferepe** [comment]
@joey04  was not trying to humor anyone but glad it worked for you.

Yes read those links you provided(Thankful)
but as a non computer person did not get the total details.

So your xulblock is an older version of UBO which is not re-based on the current version of UBO without any support?
or just testing things?

So again
"current legacy works so can't it be maintained like a simple fork with fixes here and there without interfering with ubo webext?"

By @gorhill and @joey04 as 
with you guys overseeing things mainlining a legacy version + webext version(both are very different !!)? as Ublock team or UBO group officially.

**Comment by gorhill** [comment]
> current legacy works so can't it be maintained like a simple fork with fixes here and there without interfering with ubo webext?

Sure. Best is that someone using Pale Moon is committing to do this -- it does not have to be me. I will be there to answer any technical question when needed.

**Comment by kamuferepe** [comment]
@joey04 hence the first comment asking @gorhill to create a keep low priority basilisk/legacy fork/branch

**Comment by joey04** [comment]
This guy has upvoted every single one of _his own_ posts, yet he has the gall to downvote a helpful comment from gorhill. Talk about biting the hand that feeds you.

**Comment by Xmetalfanx** [comment]
not knowing the coding details, ignoring this thread for a second ... I am sure there may be someone else, that would fork this and if any advice is needed, may even reach out to @gorhill  for tips or advice .. even if not the person who opened this thread.   

I know this is off topic, but one of my favorite FF addons, DownloadThemAll hasn't worked since FF 57 and people have been reaching out  saying they'd be willing to try to help code wise.  This is "going in the other direction" but the point that I am getting at is that there are talented people out there there may be willing to fork the project to get a certain use-case working, even if not the original developer

**Comment by gorhill** [comment]
I created a new branch [`firefox-legacy`](https://github.com/gorhill/uBlock/tree/firefox-legacy), which can be developed separately from the main branch. From now on I will start making changes in the main branch which may break the Firefox legacy version. The new branch ensure the Firefox/legacy version can still be build and I am willing to do trivial fixes for the Firefox/legacy version (pull requests are welcome).

From now on, whoever is building a Firefox/legacy version of uBO should do it from the new `firefox-legacy` branch, as the version in `master` may end up broken at any time.
