### ISSUE TITLE
[question] conversion of |blob and |data filters

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#3668]
I was reminded of this today: `|blob` and `|data` filters of EasyList are [converted to $csp rules](https://github.com/gorhill/uBlock/blob/081e5b4db98054c2f0fee00e62d0486e9cfe5273/src/js/static-net-filtering.js#L1598).

My question is in the linked code, why are the 2 items seemingly swapped? You'll notice the |blob section uses a data: scheme in the CSP rule and vice versa. (I assume it's correct because it's been that way for a long time in uBO, just would like to know why it's that way.)

**Comment by joey04** [comment]
@gorhill can you briefly explain?

**Comment by gorhill** [comment]
If you want to filter out `data:` URIs, then you must whitelist everything else except `data:`. CSP directives are whitelist directives.

**Comment by joey04** [comment]
Filtering `data:` means the EasyList `|data` filter. But then why is it converted to `default-src 'self' * blob: 'unsafe-inline' 'unsafe-eval'`. I don't see how `unsafe-` is whitelisting it for `blob:` when it would appear to be blocking it. Perhaps I'm misunderstanding CSP syntax then.

**Comment by gorhill** [comment]
`|blob:` means "block `blob:`-based resources", it does not mean "block inline javascript" or use of `eval()`.

**Comment by joey04** [comment]
I understand it a little better now. The `blob:` in the $csp of the converted `|data` rule means `blob:` scheme is okay (whitelisted). (Then its the opposite for `|blob` rules.)

I don't grok this particular $csp well enough to make a rule like this myself, but at least now I can close this. The main thing is the rule conversion is the way gorhill wants it to be.

Thanks for responding, gorhill, and for doing a great job applying your expertise for the benefit of us many uBO users.

**Comment by gorhill** [comment]
> the rule conversion is the way gorhill wants it to be

It's more like, "what is the best way to implement filtering of `|blob:` (or `data:`)?" The result is these CSP directives.
