### ISSUE TITLE
Suggestions for add features of Adblock. 

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#367]
"Allowed users to whitelist specific YouTube channels of their choosing, so that they don't have to enable ads on all YouTube channels" 
Feature added in the release 2.6.31

And "Sped up the locating of YouTube channel names by using the YouTube API instead of scanning the HTML and allowed users to disable the ad counter on the toolbar menu from the Options page"  in the 2.16 release of Adblock (not ABP)  it's write in the Wikipedia releasenotes (https://en.m.wikipedia.org/wiki/AdBlock) and i love this features ! It's Just suggestions, thanks for all i love your work gorhill :)  and sorry for my bad english and if m'y suggestions are stupid

**Comment by gorhill** [comment]
I don't like the idea of having code in uBlock to whitelist one specific vendor. There are [instructions](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#a-youtube-channel) on how to do this using a user script.

**Comment by LifeIsStrange** [comment]
I agree with you but a user script is not pragmatic, the major party of the humanity don't know how use userscripts :/, yes it's not very partial and Just to whitelist one specific vendor, but without that people completely deactivate uBlock Origin for YouTube :/ 
And for the YouTube API instead of scanning the HTML, I think you're right. 
Sorry for my very bad english.
