### ISSUE TITLE
(uBlock origin FF LEGACY) uBlock origin doesn't work in K-Meleon - Goanna.

### ISSUE THREAD

**Issue by Peacock365** [gorhill/uBlock#3670]
Hi there!

This is just a hint that the current uBlock Origin FF legacy add-on isn't working correctly in the K-Meleon browser. The issues were mentioned in this thread:

http://kmeleonbrowser.org/forum/read.php?19,145497

To quote:

> I can confirm @KM2fan problem, same here. Installation was fine, however I still see the ads and I can't open the uOrigen options to see the filters. I tested CSS enable/disable and all privacy settings but nothing works here. Really miss a good integrated adblock extension in KMGoanna.

Apparently, it is not filtering ads at all and the settings can't be viewed. You can find the most recent KM-Goanna builds for testing purposes here:

http://kmeleonbrowser.org/forum/read.php?19,143253,page=24

I know that the K-Meleon project is a small browser project only, but I thought that since uBO legacy supports Pale Moon, a fix might not be too hard to do. It could very well be an easy one-time fix.

I hope that you are fixing the issues described despite the K-Meleon project being small, if you find the time. It would be great to have this fixed before the uBlock Origin legacy add-on support is dropped.

Thanks for your attention.

**Comment by WowDude** [comment]
Hi,

> @Peacock365 : I hope that you are fixing the issues

I don't think so: https://github.com/gorhill/uBlock/issues/3666#issuecomment-378318234

**Comment by Peacock365** [comment]
@WowDude:

Huh? The thread you are linking to is about an extension of support. What does that have to do with my topic? Assuming the uBlock Origin legacy versions are created as long as Firefox ESR 52 is supported (until August 28th, 2018), it seems reasonable to ask for a bugfix in March(!) ...

**Comment by WowDude** [comment]
@Peacock365 
Keep in mind several facts:
- K-Meleon is not officialy supported by uBO
- indeed "Firefox ESR 52 is supported (until August 28th, 2018)",  but uBO legacy support is to be dropped at [May 7](https://github.com/gorhill/uBlock/releases/tag/1.15.20):

> Keep in mind I plan to drop support for Firefox/legacy once Firefox 60 ESR is [released on May 7](https://wiki.mozilla.org/RapidRelease/Calendar). This will remove a roadblock for simplifying uBO's code base in many areas.
- and by the comment I linked to I meant that gorhill is busy

**Comment by uBlock-user** [comment]
K-Meleon is not officially supported, so you will need to find someone who's willing to dig into this.

**Comment by Peacock365** [comment]
@WowDude:

Thanks for the info regarding the May 7 deadline. Although I find it odd that the last ESR isn't supported until its official EOL.

@gorhill:

> My guess is that this dated version of K-Meleon is based on Pale Moon 26 or less, and hence incompatible with uBO -- uBO supports Pale Moon 27.

K-Meleon 75.1 is the last "stable", yeah. But K-Meleon 77 is on its way, and it is based on Goanna 3.x (which is used in Pale Moon 27). See here:

http://kmeleonbrowser.org/forum/read.php?19,143253,page=24

> **Addendum:** Anyway I do not have Windows, as usual, anybody is free to contribute and fix what you label with "fix might not be too hard to do. It could very well be an easy one-time fix".

This is not to say that I _know_ how hard a fix will be, it's just speculation. The settings not showing up seems to be a graphical issue only. It not filtering ads at all could be harder to track down, though. With "easy" I meant that no additional work has to be done on the basic code structure, as the engine (Goanna) is already supported. It wouldn't be a totally new version of uBlock Origin, just a fixed one.

**Comment by gorhill** [comment]
Open the browser console (ctrl-shift-j), see if there is anything of interest.

**Comment by gorhill** [comment]
Closing due to lack of feedback.
