### ISSUE TITLE
Chrome is freezing with Ublock

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#3671]
Hi, I have a different problem with Ublock. While I was using Ublock 1.5.18 with 180 custom filter (approximately 1.800.000 network filters) on Chrome v65 x64 there was no problem and everything was working smoothly. However, after I had added a few more custom filter into Ublock and my problem came out. There is a freezing on Chrome nearly every 5 minutes. On the other hand, I am using Ublock with identical filters and settings on Firefox v59 and everything is working smoothly. I also have  i7-7700HQ 3.8 ghz, 16 gb ram powerful laptop and thus I do not think that this problem is about the performance of my computer. I am not sure that this problem is caused by whether Ublock or Chrome. I am adding below my Ublock backup. Thanks.

[my-ublock-backup_2018-04-01_17.09.18.txt](https://github.com/gorhill/uBlock/files/1874746/my-ublock-backup_2018-04-01_17.09.18.txt)

**Comment by mozkan007** [comment]
Sorry @WowDude I typed wrong, it would be v65.

**Comment by WowDude** [comment]
Any specific websites I should visit?

**Comment by mozkan007** [comment]
@WowDude  Hi again, I guess my problem resolved by itself. Because there is no freezing for 2 hours. I close this issue.

**Comment by WowDude** [comment]
Hi. Ok.

**Comment by gorhill** [comment]
Purported performance issue with uBO are always dismissed unless they come with actual profiling data which make the case uBO is the issue.
