### ISSUE TITLE
Do not block miner

### ISSUE THREAD

**Issue by dimmduh** [gorhill/uBlock#3675]
### Describe the issue
Coinhive Miner was not blocked by uBlock

### One or more specific URLs where the issue occurs
http://potomy.ru/things/1375.html

### Steps for anyone to reproduce the issue

1. Open website
2. Open task manager to see cpu usage
3. Observe 100% cpu usage

### Your settings

- OS/version: windows 7
- Browser/version: chrome 65.0.3325.181
- uBlock Origin version: 1.15.24

##### Your filter lists

Default filter lists

**Comment by mapx-** [comment]
use the correct repository for reporting filter issues:
https://github.com/uBlockOrigin/uAssets/issues

Now you can close this issue.
