### ISSUE TITLE
uBlock breaks some Link Shorteners

### ISSUE THREAD

**Issue by timmyrs** [gorhill/uBlock#3676]
### Describe the issue

Most link shorteners which use the AdLinkFly Template are broken when uBlock is enabled.

### One or more specific URLs where the issue occurs

- http://linkrex.net/A3Rkb
- https://dz4link.com/HSl4k
- http://adlinkfly.ga/IgaZ

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/11009697/38332463-551a946a-3856-11e8-8344-92ab48b82f1c.png)

### Steps for anyone to reproduce the issue

1. Open one of the given links
2. Solve the captcha
3. Profit

### Your settings

- OS/version: Windows 8.1 (64 bit)
- Browser/version: Chrome 65.0.3325.181 & Firefox 59.0.2 (64 bit)
- uBlock Origin version: 1.15.18 on Chrome & 1.15.24 on Firefox

I've reset to default settings and the issue still occurs.

##### Your filter lists

Default filter lists

**Comment by mapx-** [comment]
I get an issue (`bad request`) only on the first link

add
`linkrex.net#@#script:inject(nano-setInterval-booster.js)`

and test again

**Comment by jspenguin2017** [comment]
Well, looks like they started to enforce the delay on server side... That's unfortunate.

**Comment by timmyrs** [comment]
@mapx- I added that to my filters and the issue still occurs.

**Comment by okiehsch** [comment]
Only the first link has this issue with uBO, because there are no `booster` filters for the other two domains with a default setup.
I can reproduce your issue only  if I **add** `dz4link.com##script:inject(nano-setInterval-booster.js)` to my filter list.

**Comment by okiehsch** [comment]
@timmyrs Do you use `uBlockProtector`?

**Comment by timmyrs** [comment]
@okiehsch No, I don't use uBlockProtector, I only use uBlock Origin.
