### ISSUE TITLE
uBlock redirecting request failed alarm !

### ISSUE THREAD

**Issue by Gerrard373** [gorhill/uBlock#3677]
My Chrome  frequently report extension problem issue! Due to uBlock was redirected to other extension's hyperlink these days! Even after I clicked the mention on chrome and first close the extension(uBlock) & reopen it not for a long time! It's just a daily frequency!

How to resolve this issue? I don't know where is the root cause, because the extension and browser are using as normal as usual before the issue emerged out. I 'm Chrome & uBlock fans!

The details as below:

![ublock](https://user-images.githubusercontent.com/18229005/38355406-667bc852-38ef-11e8-9b11-966db97c9bf5.png)

Thanks for the uBlock develop team to give us a wonderful tool for internet surfing!

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/3639#issuecomment-378595755
