### ISSUE TITLE
Add by default 3rd-party filter lists: NoCoin adblock list

### ISSUE THREAD

**Issue by MS-PC** [gorhill/uBlock#3680]
They could add the anti-mining cryptocurrency filter by default in the "3rd-party filter" list. Please thanks.
Reference: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by WowDude** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3511.  Also can check these as well: https://github.com/gorhill/uBlock/issues/3407, https://github.com/gorhill/uBlock/issues/3600

**Comment by KonoromiHimaries** [comment]
it is worth adding this list because it is very popular

instead of a CoinBlockerLists
https://github.com/gorhill/uBlock/issues/3600

**Comment by okiehsch** [comment]
And basically nobody knows that `EasyPrivacy` also includes a ton of anti-mining filters.
