### ISSUE TITLE
Update for "Opera Browser"

### ISSUE THREAD

**Issue by Jhovany200** [gorhill/uBlock#3688]
### Describe the issue
Could update to the latest version for "Opera browser" in the "Opera store". Thanks.

**Comment by anewuser** [comment]
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).  It includes a link to a forum where you can discuss update delays.

**Comment by Jhovany200** [comment]
It was only a suggestion since it takes time to update.

**Comment by gorhill** [comment]
It has been "awaiting moderation" since April 9th:

> uBlock Origin v1.15.24 was submitted. Awaiting moderation.
> 
> -- gorhill; Apr 9, 2018 2:09:46 PM UTC
