### ISSUE TITLE
Severe problem with ublock and chrome canary

### ISSUE THREAD

**Issue by ale82to** [gorhill/uBlock#369]
severe problem on latest chrome canary ublock do work on any website but if i middle click on a specific website where i have custom filter the new tab opened from that website will have ublock not working  even right click contextual menu for ublock if selected WONT DO ANYTHING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

please let me know if its chrome canary fault!!!!!!!!!!

**Comment by gorhill** [comment]
> please let me know if its chrome canary fault

Please follow guide on how to submit issue: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.
