### ISSUE TITLE
UBO - Firefox android - keep 'popup tab' open when switched to another tab

### ISSUE THREAD

**Issue by gkrishnaks** [gorhill/uBlock#3692]
### Describe the issue
Hi, in UBO Firefox android, when I open Ublock Origin from menu, it opened in new tab (as expected behaviour for Firefox android) However, when I switched to another tab, the ubo popup tab closed itself. 

### One or more specific URLs where the issue occurs

All URLs. 
### Steps for anyone to reproduce the issue

1. Install UBO in Firefox android 
2. Open any site
3. Open UBO from browser menu to see UBO 'popup tab' for current page.
4. Open another site tab. 
5. Now the UBO 'popup tab' closes itself.

### Your settings

Vanilla install of UBO in android Firefox without any new setting change. 
- OS/version: Android 7.1
- Browser/version: 59.0.2
- uBlock Origin version: latest from AMO.

##### Your filter lists

Default lists only upon UBO install.

##### Your custom filters (if any)
No custom filter.

Can you please point me in code where this auto-close popup tab logic resides? Only for Firefox android UBO users, we can provide a setting switch to keep the 'popup tabs' open until user manually closes it.

**Comment by gorhill** [comment]
> However, when I switched to another tab, the ubo popup tab closed itself.

That is also the expected behavior for Firefox for Android -- it's the browser doing this.
