### ISSUE TITLE
Filterissue

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock#3693]
**Description**:

For some reason uBO has a problem with this filter:
`https://zerodot1.github.io/CoinBlockerLists/list_browser_UBO.txt`

After having applied it to uBO's list of custom filters, everything seems to work fine at first.
..but after having used it for some time, it suddenly can't be updated anymore (see screenshot below).
This has happened to me three times now.
When it comes to fixing the issue, simply removing and re-adding the filter doesn't work.
The only method I've found that works, has been to delete ublock0.sqlite, and then reconfigure/re-add everything.

**Screenshot**:

![ublockorigin-bug-filter](https://user-images.githubusercontent.com/9382674/38494275-c03e2c84-3be4-11e8-9da9-5559b458f213.jpg)

**Reference**:

https://github.com/gorhill/uBlock/issues/3600

--

- OS/version:  Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.3 (x64)
- uBlock Origin version: 1.15.24 (XUL)

**Comment by gorhill** [comment]
Before opening the issue: did you use the logger as asked?

**Comment by THEtomaso** [comment]
LOL!
I actually had no idea that uBO's logger would display anything from the filter updating process.
Thanks for the info, gorhill.. that solved it!! :)
The update process gets blocked by the 'NoCoin Filter List' filter, because of this rule:
||github.io^$third-party,xmlhttprequest,domain=~github.com|~tumblr.com
I'll report it to the filter's author.

**Comment by gorhill** [comment]
Don't report it to the filter author. I just wanted it to be investigated on your side.

The issue is caused by the change in 1.15.20, in which I removed the `behind-the-scene` whitelist directive. You may put it back if you want. A real fix would be to find out whether the Firefox/legacy framework can provide the equivalent of Firefox/webext's `documentUrl`. I suspect it's possible, however not sure I will have time to work on this.

**Comment by gorhill** [comment]
Actually, the change was not applied to Firefox/legacy, so this means you had removed the `behind-the-scene` directive yourself from the Whitelist pane. In any case, if someone wants to being the same logic to Firefox/legacy as that of Firefox/webext, i.e. the `documentUrl` thing, that would help prevent such false positives.

**Comment by THEtomaso** [comment]
Actually, I just performed a clean install of uBO 1.15.24 (XUL), and the **behind-the-scene** whitelist directive IS missing by default!

**Comment by THEtomaso** [comment]
But how come that the rule in 'NoCoin Filter List' doesn't prevent uBO from updating that other filter ALWAYS?
At the moment, I can update just fine.
Only after a few days does the issue take hold again.

**Comment by uBlock-user** [comment]
I didn't have `behind-the-scene` whitelisted even before 1.15.20 but they didn't get blocked unless `$behind-the-scene` was used, so what changed ?

**Comment by THEtomaso** [comment]
> As detailed in the Release notes of 1.15.20, you have to add the behind-the-scene directive manually for a new installation.

Obviously.
But you just said that the change was never applied to Firefox/legacy, and therefore I must have removed the directive myself.
I'm simply pointing out the fact that the directive HAS been removed for Firefox/legacy too.

Anyway, this still doesn't explain why I'm able to update the CoinBlockerLists for several days each time, before it suddenly becomes a problem.

**Comment by THEtomaso** [comment]
> if someone wants to bring the same logic to Firefox/legacy as that of Firefox/webext, i.e. the documentUrl thing, that would help prevent such false positives.

Just a thought; but wouldn't it be much easier to simply add the `behind-the-scene` whitelist directive back to the XUL version of uBO by default?
