### ISSUE TITLE
Cloud synchronization bar fails to load

### ISSUE THREAD

**Issue by giogziro95** [gorhill/uBlock#3694]
### Describe the issue

The cloud synchronization bar on top of the page under the _My filters_ tab in the dashboard sometimes fails to load under certain circumstances.

### One or more specific URLs where the issue occurs

Relevant to the extension pages only.

### Screenshot in which the issue can be seen

![My filters tab in the uBlock Origin dashboard](https://user-images.githubusercontent.com/2781117/38524003-3f24d952-3c5e-11e8-9f0e-9e01d2ee28dd.png)

### Steps for anyone to reproduce the issue

1. Open up the dashboard and check _Enable cloud storage support_ under the _Settings_ tab.
2. Go to the _My filters_ tab.
3. Reload the page.
4. The bar should fail to load; if not, try reloading again.
5. After it fails to load, you can make it appear by changing the viewport size (e.g., going full screen).

### Your settings

Cloud storage support enabled.

- OS/version: Manjaro Linux 17.1.6 (Hakoila) KDE
- Browser/version: 65.0.3325.181 (Stable channel)
- uBlock Origin version: 1.15.24

##### Your filter lists

Irrelevant.

##### Your custom filters (if any)

Irrelevant.

**Comment by giogziro95** [comment]
Another issue that might be related to this one:

When you reload the page as described in step 3, sometimes the bar loads, but then the filter list text field is taller than it needs to be, resulting in its bottom part being out of the viewport.

**Comment by gorhill** [comment]
I could reproduce. Seems like a similar issue as <https://github.com/gorhill/uMatrix/issues/990>.
