### ISSUE TITLE
Help Help

### ISSUE THREAD

**Issue by lcqlcq5** [gorhill/uBlock#3697]
@gorhill 
1.The website tomtop.com is attacked and has been inserted script
2.We have cleared the script
3. Really hope you can help us to solve this problem,we want to appeal for this,if you need any information just feel free to ask us,we will reply you asap.
Best Regards

**Comment by zippy5** [comment]
What are you talking about? And what does it have to do with uBlock Origin?

**Comment by gorhill** [comment]
I suspect OP is just spamming the name of his site, look at his history.

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?f=91&t=40437
