### ISSUE TITLE
Thunderbird 60 support?

### ISSUE THREAD

**Issue by owensgithub** [gorhill/uBlock#3698]
With Thunderbird moving away from legacy add-ons, towards web extensions, I’m just wondering if there’ll be support for it in the future? It worked very well for blocking ads in the RSS reader. However, with the current Thunderbird 60 beta, it’s not working. Hope it’s possible to see some support for it in the future. Thanks.

**Comment by anewuser** [comment]
Please close this and follow #117 instead.

**Comment by gorhill** [comment]
I closed the other old issue, it had more to do with uBO/legacy. The one here concerns uBO/webext.

**Comment by M-Reimer** [comment]
Is it realistic now to add the webextension version of uBlock to TB 60? The changelog states, that WebExtensions are now enabled in TB 60. What exactly has to be added to test this?

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/952d6q/ublock_origin_is_not_compatible_with_thunderbird/

**Comment by M-Reimer** [comment]
Looks like they only did a partial integration of the WebExtensions API. For example "browserAction" (which is needed for the uBO toolbar icon) seems to be missing.

I wonder how many Addons will actually run with this reduced API...

**Comment by gorhill** [comment]
I will be able to see what I can do once I get upgraded to Thunderbird 60.

**Comment by xMateMCPE** [comment]
Any updates?

**Comment by seth100** [comment]
+1

**Comment by davidhedlund** [comment]
I requested Mozilla to implement WebExtension support at https://bugzilla.mozilla.org/show_bug.cgi?id=1396172

**Comment by Serkan-devel** [comment]
Doesn't ublock work already on Thunderbird?

**Comment by webserfer** [comment]
Please tell me the version of Thunderbird in which working ublock **and** main functional (at least google and yandex)

**Comment by uBlock-user** [comment]
@webserfer https://github.com/gorhill/uBlock/releases

**Comment by webserfer** [comment]
@uBlock-user, Thunderbird 65 doesn't work with modern mail providers, ublock doesn't want to block on Thunderbird 76+

**Comment by gorhill** [comment]
Closing as _obsolete_. Any specific issue for Thunderbird should be opened at <https://github.com/uBlockOrigin/uBlock-issues/issues> along with all the thorough technical details of the exact issue and what exact changes in the code need to be made. 

Issues which are equivalent of one-liner such as _"Picker does not work"_ won't be accepted, I want issue which explain why the picker does not work and what needs to be changed in the code to fix it.
