### ISSUE TITLE
In logger, exceptions rules with "elemhide" are "red"

### ISSUE THREAD

**Issue by F4z** [gorhill/uBlock#370]
To reproduce the problem please open logger and for example go to the https://easylist.adblockplus.org/en/
Look in logger:
![](http://i.imgur.com/rCefVUY.png)
The exception rule is red, but I think it should be green or maybe I don't understand how it works?
uBlock Origin v0.9.9.1
Chrome 43.0.2357.124 m
Windows 8.1

Other question.
For example on this website [Neowin](http://www.neowin.net/news/fallout-4-is-coming-to-xbox-one-playstation-4-and-pc-on-november-10th) I want to block a frame from youtube.com, so I open logger and I set something like this:
![image](https://cloud.githubusercontent.com/assets/11742596/8240213/4b0b1776-1601-11e5-9d79-38aa0fefa874.png)
So, filter option for "frame" is "sub_frame" but it doesn't work for me, I think it should be "subdocument" or maybe I do something wrong?
This same for "doc" is "main_frame" and I think it should be "document", no?

**Comment by gorhill** [comment]
> filter option for "frame" is "sub_frame" ... maybe I do something wrong?

No, there was a bug, I fixed it. Looking into a fix for `elemhide`.

**Comment by IDKwhattoputhere** [comment]
This is causing actual breakage of sites.

Example:

1. Subscribe to `DEU: EasyList Germany‎`
1. Go to http://www.lablue.de/nu.html and click `Login für Mitglieder` (`Login for members`) in the upper right corner.

Result: The login doesn't open. It's broken because uBO interpreted the filter `@@||lablue.de^$elemhide,script` incorrectly.

**Comment by gorhill** [comment]
What breaks the site is the blocking of `http://www.lablue.de/js/nu.js`, not the use of `elemhide`.

**Comment by gorhill** [comment]
Never mind, I see the issue. This is a separate issue than the one reported here, please open a new issue for this.
