### ISSUE TITLE
Filter List Cursor Positioning

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#3701]
### Describe the issue

@gorhill Normally I would rather not open an "issue" for this kind of thing but for better ability to track it felt I add this here rather than a comment on the commit. Feel free to close it once you have looked at it and/or "fixed" it. Not a super critical issue, just that the commit stated that in the "filters" tab, it will set the cursor at the end, initially it didn't do that but in later updates it was working as intended, but as of the last update (at least when I noticed it), it started staying at the first line again and not moving to the end, just wanted you to know that. Since it's internal "usability"/"cosmetic" matter, don't really have much else to add to this ticket, but do let me know if something else will help. TIA.

**Comment by gorhill** [comment]
I removed this -- I changed my mind about the convenience of putting the cursor at the end, it makes the loading of the pane more glitchy IMO (this was also a party in causing #3694). In the end, a simple ctrl-end does the job if one wants to move the cursor at the end.

**Comment by GuardianMajor** [comment]
@gorhill Understood, thank you - appreciate the info. You are correct, that would be just as easy to do, closing this.
