### ISSUE TITLE
[request] Remember the cursor position in 'My Filters' tab.

### ISSUE THREAD

**Issue by smed79** [gorhill/uBlock#3706]
### Current behavior

When you switch between tabs (or close uBo/browser) the cursor automatically jump to the bottom in the filter textarea of 'My Filters' tab.

### Screenshot 

* https://i.imgur.com/UG3kBG4.gifv

### Request/Change

Make uBo remember/restore the cursor position in 'My Filters' tab if you switch between tabs or close uBo/browser.

**Comment by Atavic** [comment]
I don't think this is possible. You are changing the focus on the same program, so the cursor position is gone. To my knowledge, you are asking about a feature found in real editors, not browser addons.

**Comment by gwarser** [comment]
Related https://github.com/gorhill/uBlock/issues/3701

**Comment by gorhill** [comment]
> I do question the usefulness of such feature.

I think the idea is that when working in a specific area of the filter list, most likely you want to resume work from the same point -- just like opening the dashboard auto-select the last pane used. In latest dev builds I remove the auto-scroll to the end of the list -- I ended up finding it annoying just like @SMed79, but to go to the last cursor position does make sense. Probably best to write to localStorage when the pane is about to unload.

**Comment by jspenguin2017** [comment]
> Probably best to write to localStorage once when the pane is about to unload. 

Yes, that's what I meant. 

> resume work from the same point

Hum, I like dropping the cursor to the very end better.

**Comment by gwarser** [comment]
Clarification: cursor is restored to the beginning of the line.

**Comment by gorhill** [comment]
Yes, I didn't think restoring the column would be very useful.
