### ISSUE TITLE
FF property "privacy.resistFingerprinting=true" causes uB0 "[ ] Auto-update" to be without effect (LineageOS 7.1.1, FF 59.0.2, uB0 1.15.24)

### ISSUE THREAD

**Issue by MarkusML** [gorhill/uBlock#3707]
### Describe the issue 

After disabling "[ ] Auto-update filter lists" on tab "3rd-party filters" 
in uB0, no connection attempts related to asset updates should appear. 
But connection attempts to "filters.adtidy.org" (assets.json) 
can be seen (i.e. via tcpump, wireshark, firewall, ...) when Firefox 
property "privacy.resistFingerprinting" is set to "true" 
and Firefox is restarted (Firefox for Android). 

This might be a "first-update-after-install-issue" caused 
by initial filter updates. Still when "Auto-update" has been 
disabled right after installation (while network is down), 
no connection attempts at all should be made later (when 
network is up again and Firefox is started). 

### One or more specific URLs where the issue occurs 

URL does not matter. 

### Screenshot in which the issue can be seen 

Connection attempts can be monitored via tcpump, wireshark 
or by a firewall, that filters out-going traffic (i.e. NetGuard).

### Steps for anyone to reproduce the issue 

Tested with Firefox 59.0.2 and Fennec 59.0.2 several times.

Between some of the steps one might need to wait 5-20 seconds 
(i.a. after initial start / installation) so Fennec or Firefox 
can run through it's initial setup process. 
Most of the installation steps are done without 
network (i.e. via side-loading / local files).

The idea is to stay offline while installing and
configuring the components (so no immediate update
spoils the final test).

1. Disable WAN + WLAN on device. 

2. Download and install (but not start) latest 
Fennec 59.0.2 (f-droid) or Firefox 59.0.2 (PlayStore) 
via "adb install" (or install from f-droid / PlayStore 
with network still up). Really disable network now.

3. Start Firefox/Fennec and set "privacy.resistFingerprinting" 
to "true" in "about:config".

4. Download uB0 XPI-file ("ublock_origin-1.15.24-an+fx.xpi")
from Mozilla via desktop browser (right-click-on-Download->Save-as),
transfer xpi-file to device (i.e. via "adb push") and install it in Fennec / Firefox
(i.e. via local html file containing a link
`<a  href="ublock_origin-1.15.24-an+fx.xpi">install</a>`
to the xpi-file in the same directory on the device - both files
can be transferred via "adb push" to the device). HTML-file can
be opened via Android file browser => open with Fennec/Firefox.
Granting access right to storage (/sdcard) might be required.

5. Configure uB0 in Fennec/Firefox
=> especially disable "[ ] Auto-update filter lists" on tab "3rd-party filters".

6. Close all tabs first (maybe important). Then close Firefox/Fennec (important).

7. Connect device to WLAN.

8. Start Fennec/Firefox.
=> After some time (<5 min) one sees
=> connection attempts to "filters.adtidy.org".

The connection attempts can be monitored i.e. with help of NetGuard
configured in  filtering mode denying all Firefox/Fennec out-going connections.
... or via tcpdump/wireshark running on your WLAN-gateway. 

Usually Firefox is very "chatty" when started, i.e. connection 
attempts to "app.adjust.com", "incoming.telemetry.mozilla.org", etc. etc. 
But if Firefox has been configured to be very silent (i.e. not  to make
any connections unless requested by accessing an URL), 
the uB0 connection attempts become very well visible.

Cross check:

When "privacy.resistFingerprinting" is "false" (default) 
and "[ ] Auto-update filter lists" is disabled, not a single 
uB0-asset-update connection attempt can bee seen. 

### Your settings

- OS/version: LineageOS 7.1.1
- Browser/version: Fennec (f-droid) 59.0.2 / Firefox (Playstore) 59.0.2
- uBlock Origin version: ublock_origin-1.15.24-an+fx.xpi (Mozilla-signed)

- Fresh install of Fennec/Firefox (default, except privacy.resistFingerprinting = true)
- Fresh install of uBlock-Origin (default settings, except "[ ] Auto-Update" disabled)

### Your filter lists

No change in filter lists.

### Your custom filters (if any)

No custom filters involved.

**Comment by gorhill** [comment]
uBO never update filter lists at launch, regardless of whether "auto update" is enabled or not. The only reason uBO would fetch a list reom a remote server if because it does not have a copy locally. The only reason uBO may not have a copy is because it was not allowed to save the fetched copy into its indexedDB. You will have to investigate on your site why this is so.

**Comment by gorhill** [comment]
So let me see... You are preventing uBO from fetching a list which is currently selected, and when uBO finally fetches it, you consider this to be a flaw? "Auto-update" prevents auto-update, it does not prevent fetching a list which is not yet available locally. See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)...

**Comment by MarkusML** [comment]
I did read CONTRIBUTING before posting and was pretty sure, this is a real issue.

If "auto update" is disabled and "privacy.resistFingerprinting" is "false", uBO does not do any connection attempts, but if "privacy.resistFingerprinting" is "true", uBO does.

=> So the property "privacy.resistFingerprinting" has influence on how  uBO
reacts on disabled  "auto update" setting. Maybe uBO should not be dependent
on that Firefox property.

**Comment by gorhill** [comment]
I doubt `privacy.resistFingerprinting` has anything to do here. What influence whether the list is downloaded is:

At launch:
- Is it selected?
    - No = do nothing
    - Yes. Is it available locally?
        - No = download it
        - Yes = do not download it

At update time, first 11 minutes after launch:
- Is auto-update enabled?
    - No = do nothing. Check again in _x_ hours
    - Yes. Is the list out of date?
        - No = do nothing
        - Yes = download it
