### ISSUE TITLE
Weird type reporting in logger

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#3710]
### Describe the issue

CSS files that are supposed to be served normally as CSS are showing up with duplicate requests as both CSS and behind-the-scene + XHR requests. What's weirder is they are showing up as XHR, but I have javascript disabled for 1st and 3rd parties so I have no clue how that happens. @gorhill Not sure what to make of this, whether it is a bug or something going on with the site itself. I should also mention I use uMatrix and these show up in the its logger just like uBO but not in the matrix itself.

### One or more specific URLs where the issue occurs

https://www.reddit.com/

### Screenshot in which the issue can be seen

https://i.imgur.com/WBOyxiP.png

### Steps for anyone to reproduce the issue

1. Open logger
2. Visit https://www.reddit.com/

### Your settings

- OS/version: Windows
- Browser/version: FF 60
- uBlock Origin version: 1.15.24 

##### Your custom filters (if any)

`||redditstatic.com^$important,domain=~reddit.com` (this doesn't make a difference to reproduce I think but I added it stop requests from going through)

**Comment by gorhill** [comment]
uBO just processes/reports what is given to it through its webRequest listeners.

I can't see what you get on my side. Do you have any other extensions which could be causing this?

In the logger, what is the context for the network request? Click to bring up the filtering dialog, the context is shown in there:

![a](https://user-images.githubusercontent.com/585534/38734030-220ad0ec-3ef2-11e8-82cd-c955188baf01.png)

**Comment by grenzor** [comment]
Context is behind the scenes given by eye in https://i.imgur.com/WBOyxiP.png (also made sure in logger). 
By the way I just restarted my comp and tried to reproduce again and couldn't. Just odd. 

Maybe not a uBO issue but something else, like some one time glitch. I'll have to keep checking. I'll close this but you can reopen if you think it may be to do with uBO (I'll post if I see it happen again).

**Comment by gorhill** [comment]
> Context is behind the scenes given by eye

The "slashed eye" just mean "can't associate to specific tab" -- there can still be a context which is not literally `behiind-the-scene`. There might still be a context, I wish you just had look as asked and reported.

**Comment by grenzor** [comment]
I couldn't show you because I already restarted my comp and couldn't reproduce again. But I know it was behind the scene 100% because the first filter I created was a block rule from the logger for $domain=behind-the-scene

**Comment by gorhill** [comment]
> the first filter I created was a block rule from the logger for `$domain=behind-the-scene`

The filter reported in your screenshot is `||redditstatic.com^$important,domain=~reddit.com`, not `$domain=behind-the-scene`.

**Comment by gorhill** [comment]
Ok, understood. That's really anomalous then since Firefox usually almost always provide a context such that falling back to literal `behind-the-scene` is probably rather rare. I wonder if these requests might have been caused by activity streamer, or maybe the thumbnail generator for thumbnails used in the New Tab page.
