### ISSUE TITLE
ublock bug: If the URL is modified by JS or previous browser button, current page are not updated on Firefox ESR 52

### ISSUE THREAD

**Issue by Pbast** [gorhill/uBlock#3711]
### Describe the issue
When using ublock on  Firefox 52 Extended Support Release (ESR), if the URL is modified by JS or previous browser button, current page are not updated

To fix this issue ublock must be deactivated. Set ublock to Off (or use white list)  doesn't fix this issue.

(FF59 + ublock working well)

### One or more specific URLs where the issue occurs

https://twitter.com/

### Steps for anyone to reproduce the issue

1. Go to https://twitter.com/
2. Click on Subscribe link
3. FF is on https://twitter.com/signup
4. Click on "Previous" icone of Firefox toolbar
5. UTL in adress bar is  https://twitter.com/
6. **but** the page displayed is still https://twitter.com/signup

### My settings

* Firefox ESR: 52.7.2 (32bits)/Seven/uBlock 1.15.18
* Firefox ESR: 52.7.3 (64 bits) / Debian/uBlock 1.15.24
* Firefox ESR: 52.7.3 (64 bits) / Debian/**uBlock1.15.25rc2 (last version)**
##### My filter lists

Default

##### My custom filters
Nope

Thxs for you great addon

Pascal B

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1401516
