### ISSUE TITLE
whitelist specific element

### ISSUE THREAD

**Issue by Ninjacat64** [gorhill/uBlock#3713]
### Describe the issue
i often play games the site https://dan-ball.jp/en/
however, ublock will block certain games and i will have to disable it in order to play the game.
this usually happens with the html5 versions
it also might be worth noting that the games are hosted locally

### One or more specific URLs where the issue occurs
https://dan-ball.jp/en/javagame/dgo/
https://dan-ball.jp/en/javagame/hamrace2/
https://dan-ball.jp/en/javagame/shisensho/
https://dan-ball.jp/en/javagame/stickman/

### Steps for anyone to reproduce the issue

just go to the website and click on the game

### Your settings

all deafault

- OS/version: OSX 10.11.6
- Browser/version: 65.0.3325.181 (x64)
- uBlock Origin version: 

##### Your filter lists

default
##### Your custom filters (if any)

i just put these here?

! 2/12/2017, 10:22:26 PM http://knowyourmeme.com/memes/card-games-on-motorcycles
||www.ora.tv/embed/partner/knowyourmeme/playlist/262/v/1$subdocument

! 2/17/2017, 11:42:21 AM http://mangafox.me/manga/yu_gi_oh/v07/c054/
||h.mfcdn.net/store/mfbanners/pc.read_1485224881.jpg?token=1ce13b3402067f60e8bb7dc8404aece0&ttl=1487433600&v=1485224881$image

! 3/23/2017, 5:36:40 PM https://www.aol.com/article/news/2017/01/19/president-barack-obamas-first-inauguration-speech-full-text/21657532/
||o.aolcdn.com/images/dims?image_uri=https%3A%2F%2Fs.aolcdn.com%2Faoldotcom-releases%2Ftiles%2Ftrump_first_100_days_timeline%2F2017-01-20%2F11%3A00%2F300x300%2F8A2E.jpg&resize=%2C300&crop=300%2C300%2C0%2C0&client=14d356460ccd1a3da7ce&signature=a3f98b57670826320b37d54a0c85087e0c547fae$image

! 3/23/2017, 5:36:55 PM https://www.aol.com/article/news/2017/01/19/president-barack-obamas-first-inauguration-speech-full-text/21657532/
www.aol.com##.m-navbar__nav-right.m-navbar__services.m-navbar__nav

! 4/3/2017, 1:07:20 PM https://www.reddit.com/r/touhou/comments/62cqfe/rough_translation_of_sumirekos_interview_from/
www.reddit.com##.submit-text.submit.sidebox > .morelink > .access-required.login-required

! 4/3/2017, 1:07:26 PM https://www.reddit.com/r/touhou/comments/62cqfe/rough_translation_of_sumirekos_interview_from/
www.reddit.com##.submit-link.submit.sidebox > .morelink > .access-required.login-required

! 4/3/2017, 1:07:32 PM https://www.reddit.com/r/touhou/comments/62cqfe/rough_translation_of_sumirekos_interview_from/
||b.thumbs.redditmedia.com/pICowR86UrL5WW0rkj0__00tiUDhTh3nmW9jeRiByQw.png$image

! 4/3/2017, 1:07:37 PM https://www.reddit.com/r/touhou/comments/62cqfe/rough_translation_of_sumirekos_interview_from/
||b.thumbs.redditmedia.com/t6IpJ-RWC-mWYGdHO9uMJfH4Y4zFbknJPG2RCZPpN4I.png$image

! 4/12/2017, 10:46:32 AM http://www.marketwatch.com/watchlist
www.marketwatch.com###circular-widget

! 4/27/2017, 1:14:23 PM https://quizizz.com/join/
||cf.quizizz.com/join/img/correct_meme/cm13.jpg$image

! 4/27/2017, 1:14:48 PM https://quizizz.com/join/
||cf.quizizz.com/join/img/correct_meme/$image

! 4/27/2017, 1:16:13 PM https://quizizz.com/join/
||cf.quizizz.com/img/memes/$image

! 2/8/2018, 5:19:29 PM http://readcomiconline.to/Comic/Uncle-Scrooge-1953/Issue-12?id=57823#15
readcomiconline.to##.z3g1CpPsko

! 2/8/2018, 5:28:02 PM http://readcomiconline.to/Comic/Uncle-Scrooge-1953/Issue-12?id=57823#15
readcomiconline.to##.z3g1CpPsko

**Comment by mapx-** [comment]
test this filter
`@@||dan-ball.jp/javagame/*/img.gif?$image,first-party`

You should report filter issues only here:
https://github.com/uBlockOrigin/uAssets/issues
