### ISSUE TITLE
Error extension in Chromium with HTTPS Everywhere

### ISSUE THREAD

**Issue by reno-a** [gorhill/uBlock#3714]
Hello,

### Describe the issue
Error extension in Chromium (64.0.3282.119) with HTTPS Everywhere (2018.4.11)

"Warning:
This extension failed to redirect a network request to chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/59fb24a2d12455d15bea20980e8a6801.js?secret=rdfcfnod2xg7 because another extension (HTTPS Everywhere) redirected it to https://www.google-analytics.com/analytics.js."

### Steps for anyone to reproduce the issue
observice not all time

### Your settings

- OS/version:  Debian 9x
- Browser/version: Chromium
- uBlock Origin version: 1.15.24

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/3639

**Comment by reno-a** [comment]
Thanks gwarser for the link.
Maybe HTTPS Everywhere is less useful than before.
I will try without.

**Comment by WowDude** [comment]
Also https://github.com/gorhill/uBlock/issues/3709
