### ISSUE TITLE
Sourceforge in Badware Filters

### ISSUE THREAD

**Issue by AsukaLangleyfag** [gorhill/uBlock#373]
> SourceForge pledges to present third-party offers only with the projects that explicitly opted-in to that program.
> Mirrors which are not co-maintained with the one or more of the original developers, except where the upstream site has been discontinued, have been removed effective immediately.

Source: http://sourceforge.net/blog/project-mirroring-policies-will-be-revisited-with-our-community-panel-existing-mirrors-removed/

**Comment by Hrxn** [comment]
Yes, I noticed that too...

And what do you suggest?

Shall we do a vote? ;-)

**Comment by gorhill** [comment]
> SourceForge pledges to present third-party offers only with the projects that explicitly opted-in to that program

This does not mean SourceForge's downloads won't be affected with badware. Filezilla is a project which opted-in, and it's [affected with badware](http://blog.tedd.no/2014/11/25/sourceforge-malware/).

**Comment by Hrxn** [comment]
What Source Forge has to say about this:

https://sourceforge.net/blog/project-mirroring-policies-will-be-revisited-with-our-community-panel-existing-mirrors-removed/

> SourceForge pledges to present third-party offers only with the projects that explicitly opted-in to that program.

We'll see how this turns out..

For the record, as this blew up in May:

**Comment by AsukaLangleyfag** [comment]
Well, I suggest to make a list for projects who's opted for program since some distros like Manjaro for example uses Sourceforge as their download location and some projects like msys2 also uses Sourceforge as their place to store binaries and they are clean. But yes, distributing adware is unacceptable.

**Comment by gorhill** [comment]
> I suggest to make a blacklist for projects who's opted for program instead of blocking the whole site 

Strict blocking does not support this, it's hostname-based. The blocking page is easy to dismiss, there are two buttons to do so, on a temporary or permanent basis.
