### ISSUE TITLE
Softonic

### ISSUE THREAD

**Issue by KaKi87** [gorhill/uBlock#3733]
Hello,

Why is softonic.com commented at line 56 ?

Thanks !

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/926#issuecomment-350116454

**Comment by KaKi87** [comment]
Okay it's more like [this one](https://github.com/uBlockOrigin/uAssets/issues/476) which explains why Softonic is commented but thanks.
