### ISSUE TITLE
Please don't leave Windows XP users alone

### ISSUE THREAD

**Issue by palikacska** [gorhill/uBlock#3741]
Dear @gorhill ,

I have opened this here because this is only for you.

I have already opened an [issue](https://github.com/uBlockOrigin/uBlock-issues/issues/282) in your global issue tracker but I'm afraid one of your volunteers has just labeled it as invalid, referring to [another issue](https://github.com/uBlockOrigin/uBlock-issues/issues/84#issuecomment-416002317) where it was stated that Chrome version must be bumped above **49** because of a JavaScript syntax it doesn't support. So the minimum Chrome version number must go up to **51.0**. There are two problems with that.

1. The last version of Chrome available for Windows XP is Chrome/Chromium 49.
2. Windows XP is still used by millions of people. At least twice as much than of Linux, according to NetMarketShare.

So that's not just a simple version number. It affects **millions of people**. And especially that kind of people who need the capabilities of your great blocking extension the most.

On Windows XP there are a limited set of browsers available. One of these is the Firefox branch, more exactly the forks that have been created from older versions of Firefox and the last versions of Firefox ESR that used to support XP. These are [Centaury](https://github.com/Feodor2/Mypal/releases/tag/Centaury) (built from Basilisk), [Mypal](https://github.com/Feodor2/Mypal) (built from Pale Moon) and [New Moon](https://msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/) (built from Pale Moon). On these browsers you must use an older version of uBlock, around version **1.13**. Since this is Firefox codebase, all of them are really slow because the unoptimized and bloated engine Firefox codebase generally comes with. So you know it's not that good on an old computer running XP.

There is [Advanced Chrome](http://browser.taokaizen.com/) that has a build above version 51.0 but does not support hardware acceleration (yes it's possible under XP) and is not a real stable alternative because it crashes sometimes. I had the chance to try it and I wouldn't rely on it for everyday use.

There is Chromium 49 which is full-featured, supports all video codecs but doesn't support GPU hardware acceleration under XP. It's much faster than any Firefox fork mentioned above. It's preferred because it's more easily obtainable than official Chrome 49 which needs a little more Googling among broken links and archives of older Chrome versions. It also doesn't display the annoying notification of Google's hypocritical warning message for upgrading to a different OS (billion dollar Google would have the resources to support XP but they decided not to and left alone millions of people). Chromium 49 is **affected** by your version number change.

There is Chrome 49 which is full-featured, supports all video codecs and GPU hardware acceleration under XP. It's the **fastest alternative**. Way faster than any version of Firefox, a bit faster and much more stable than Advanced Chrome, even if it's an older version. Chrome 49 is **affected** by your version number change.

Speed, efficiency, the key principles uBlock Origin has been built upon are the **most needed by users of older computers with less resources**. People stick to XP because they would need a new computer for Windows 7 or 10 due to the absence of drivers. Even 2nd generation Intels are unsupported on Windows 10, even though the i5s are nearly as powerful as today's Intel i3s. Desktop Linuxes wouldn't mean a real alternative either as as GTK3 and Qt5 are heavy weight frameworks and all applications are built around them. So the least bad alternative is to keep XP which is still good for most of the tasks performed on a computer. There are two critical aspects out there why XP users need uBlock Origin the most.

1. To filter out all unnecessary advertising content
2. To block all malicious sites XP computers are more vulnerable to.

That's why it would be important to keep up the support for Chromium 49 somehow. Either by using a syntax different from for node of nodes, or creating a legacy branch of the old code. It would be great if XP users could install uBlock Origin from the Chrome Web Store again. Please help us make that possible.

**Comment by gorhill** [comment]
The issue tracker here is closed to non-contributor.
