### ISSUE TITLE
uBlock Origin prevented the page from loading:

### ISSUE THREAD

**Issue by seriesgato** [gorhill/uBlock#3751]
when entering my domain seriesgato.com ublock origin tells me the following message

http://prntscr.com/n026ke

how can I prevent this window from ever coming out again in my domain, I am the owner of it

**Comment by mapx-** [comment]
Try updating that list (or all the lists), I get no such filter

**Comment by seriesgato** [comment]
I appear from my desk as I showed in the current photo, contact malwaredomains to remove my domain will have to do something else

**Comment by mapx-** [comment]
Did you purge caches + update ?

**Comment by seriesgato** [comment]
mapx thanks for your help seriesgato.com has been solved now it's still happening with the domain seriesgato.tv

http://prntscr.com/n02s1g

thank you king

**Comment by mapx-** [comment]
No issues anymore, tested in FF / chrome using the 2 malware lists

However, the filter issues have to be reported here:
https://github.com/uBlockOrigin/uAssets/issues

You should close this issue.

**Comment by seriesgato** [comment]
thanks to you I will open a discussion in that area

**Comment by gwarser** [comment]
Removed: http://dns-bh.sagadc.org/removed-domains-20190318.txt
