### ISSUE TITLE
Deploying uBlock Origin to machines with Firefox

### ISSUE THREAD

**Issue by logan-19** [gorhill/uBlock#3753]
Hello friends!

I've read all these [comments](https://github.com/gorhill/uBlock/issues/832) and this [instruction](https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin) and am still having issues.

I have a lot of machines with Firefox 52.0.2 + uBO 1.17.4 Windowx XP 32bit

uBO does not accept the settings that are advised in the comments.
Please let me know what settings are needed?

Thank you!

**Comment by gwarser** [comment]
I think you need to use uBO legacy on such old Firefox. WebExt storage.managed was introduced in 57.

**Comment by gorhill** [comment]
Closing as invalid since no details were provided regarding what was not working.
