### ISSUE TITLE
Questions about how uBlock works

### ISSUE THREAD

**Issue by MarcoSulla** [gorhill/uBlock#3756]
Hello. I installed uBlock because Abe NoScript is not yet supported for the new Firefox API. 

I want to use uBlock only for blocking tracking sites, like Facebook and Youtube. For scripting, I use NoScript and for ads I use Adblock Plus.

Can you please tell me how it works uBlock? If a site embeds Facebook, uBlock blocks Facebook and let you navigate, like ABE, or the entire site is blocked?

I currently use these filters:
- uBlock filters – Badware risks​
- ​uBlock filters – Privacy​​​​​
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak​​​​​
- Malware Domain List​​​​​
- Malware domains​
- Peter Lowe’s Ad and tracking server list

PS: cosmetic filtering can be disabled if I use Adblock Plus or you filter something more?

PPS: I visited https://www.ublock.org/ and I got this message:
> uBlock Origin has prevented the following page from loading:
> https://www.ublock.org/
> Because of the following filter
> ||ublock.org^$document
> Found in: uBlock filters – Badware risks 

:-P

**Comment by uBlock-user** [comment]
Read the wiki -- https://github.com/gorhill/uBlock/wiki
