### ISSUE TITLE
SoundCloud ads are no longer being blocked

### ISSUE THREAD

**Issue by MAnoDew** [gorhill/uBlock#3759]
I've been using uBlock Origin for awhile now. It always blocked SoundCloud ads until now. (Ads started appearing on 9 Oct 2019)

Website URL: soundcloud.com

- OS/version: Windows 10 Home 64-Bit
- Browser/version: Chrome 77.0.3865.90 (Official Build) (64-bit)
- uBlock Origin version: v1.22.4

Filters:
- Default filter lists

Image:
![Screenshot_1](https://user-images.githubusercontent.com/32684492/66517914-4ace7c00-eae4-11e9-9cd7-26559780d519.png)

Hope I provided enough information. If not, let me know what more information you need.

Thanks,
Dew

**Comment by okiehsch** [comment]
Filter issues should be reported at https://github.com/uBlockOrigin/uAssets
See https://github.com/uBlockOrigin/uAssets/issues/6423
