### ISSUE TITLE
No window action buttons

### ISSUE THREAD

**Issue by crazyyzarc** [gorhill/uBlock#3761]
After opening the uBlock Monitoring window and closing Firefox, the uBlock window is still open. Right?

If you close the uBlock window afterwards, then everything is closed. Okay!

But if you now open Firefox and restore the previous session, uBlock will open with, but without minimize, shrink and close buttons in the upper right corner.

![2019-12-13 14_34_56-Erweiterung_ (uBlock Origin) - uBlock₀ — Protokoll der Netzwerkanfragen](https://user-images.githubusercontent.com/4954535/70804214-3180cf00-1db6-11ea-846a-d10421adf4ff.png)

**Comment by gorhill** [comment]
Firefox issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1516819>.
