### ISSUE TITLE
filter addition - EZTV

### ISSUE THREAD

**Issue by grrrrr** [gorhill/uBlock#377]
I hope this is the right place for filter suggestions, I did not see another repo.

I am suggesting adding EZTV sites into filter for badware.

EZTV site was hijacked very recently and the people who stole the sites are trying to monetize  on their gained control and send users to third party downloads.

Sites affected:
- eztv.it
- eztv.ch
- EZTV-Proxy.net

Links to backup the claims of site takeover

https://en.wikipedia.org/wiki/EZTV#Hostile_takeover
https://torrentfreak.com/take-over-new-eztv-domain-name-150425/
http://www.digital-digest.com/news-64115-EZTVs-it-Domain-Taken-Over-by-Scammers.html
http://www.oystermag.com/eztv-has-been-taken-over-by-scammers

**Comment by gorhill** [comment]
<https://eztv.ch/news/83/scam-warning/>:

> UPDATE: you can use both eztv.it and eztv.ch from now on!

**Comment by gorhill** [comment]
I have to be very cautious about that badware.txt list. It will loose its value if non-badware sites end up in it. So I want completely unambiguous information as to whether `eztv.ch` is legit or not. Show me examples of bad downloads.

**Comment by grrrrr** [comment]
none of it is (officiall) EZTV related not, all downloads are rarbg owned.  The update you linked to is its self old / fake as it's on the site the real owners no longer control - https://torrentfreak.com/eztv-shuts-down-after-hostile-takeover-150518/

I think you are right though, it is probably not a place for badware, it is really more a scam at this stage.  Do you have any recommendations as to where (if anywhere) it would be best suited

**Comment by gorhill** [comment]
I don't see any instance of badware in those articles.
