### ISSUE TITLE
Unable to block a certain behind-the-scene connection

### ISSUE THREAD

**Issue by crisalis** [gorhill/uBlock#378]
The HTTPS Everywhere add-on connects to check.torproject.org every time the browser starts up. Note this is unrelated to Tor Browser or the Tor network, it's HTTPS Everywhere's doing and happens just for using said add-on on regular Firefox or other browsers. It may be fixed in the future: https://trac.torproject.org/projects/tor/ticket/9693

HTTPS Everywhere does this to check if the browser is using the Tor network. I don't know for what purpose HTTPS Everywhere checks this, but it's a privacy issue anyway.

One would expect uBlock to be able to block this behind-the-scene connection, but it appears it happens too early for uBlock to notice it. If you set chrome://ublock0/content/logger-ui.html as Firefox's home page in other to log every connection noticed by uBlock since the very startup, the connection to check.torproject.org isn't logged. Thus, something like "behind-the-scene https://check.torproject.org other block" doesn't work. If you go to Firefox's about:networking internal page, the connection does appear.

uBlock should be able to notice this connection. It isn't even made by Firefox itself, but by another add-on, so if that add-on is able to be that "fast", uBlock should be able too. (Actually I don't really know what I'm talking about.)

**Comment by gorhill** [comment]
uBlock has absolutely no control as to when it's loaded and executed, the browser decides. If the browser decides HTTPS Everywhere will be loaded and executed first, there is nothing uBlock can do.

**Comment by crisalis** [comment]
Well, OK then.
