### ISSUE TITLE
Constant SQlite updates break cloud sync (blockedRequestCount and allowedRequestCount)

### ISSUE THREAD

**Issue by nyanpasu64** [gorhill/uBlock#380]
uBlock0.sqlite is updated with blockedRequestCount and allowedRequestCount every few minutes. As a result, Seafile must reupload the entire 13MB file every few minutes, taking up massive amounts of storage space on my self-hosted cloud server.

You should add an option to disable blockedRequestCount and allowedRequestCount, to reduce the constant updates to sqlite. "Show the number of blocked requests on the icon" did not help, and I didn't find any relevant options in the settings export file.

**Comment by gorhill** [comment]
You are asking a very specific feature which is for your very specific use case. That's not how I work, I am not a coder for hire. The real solution to your issue is #80.

**Comment by jimbo1qaz** [comment]
Can I submit a pull request after coding the feature?

**Comment by gorhill** [comment]
No, I do not want code in uBlock that is useful to only one user.

**Comment by jimbo1qaz** [comment]
What is the use of blockedRequestCount and allowedRequestCount in the first
place?

**Comment by gorhill** [comment]
To compute the "since install" stats in the popup.
