### ISSUE TITLE
' POL: Adblock polskie reguly' freezes page

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#382]
This page:
http://www4.rp.pl/article/20150619/KULTURA/306199771

Encountered on Fx 39b7, uBlock 9.9.2 - Firefox freeze, 100% cpu core.
Tested on Opera 32, uBlock 9.9.1 (default setting + POL list) - Current tab freeze, 100% cpu core.
In both cases, works when POL list is disabled.

I cannot find anything related to 'POL: Adblock polskie reguly' in uBlock log. (maybe because is not updated after freeze).

**Comment by gorhill** [comment]
This is first:

- A site issue
- A filter list issue

**Comment by gwarser** [comment]
Of course. If I only know which filter...

**Comment by gorhill** [comment]
Chromium + logger should work to identify the filter, as Chromium does whole-freeze like Firefox. I tried again your link and the freeze is gone.

**Comment by gwarser** [comment]
Seems to be fixed by the author of the list. Thank you anyway.
