### ISSUE TITLE
[Firefox] Mozilla trying to hide uBlock from search?

### ISSUE THREAD

**Issue by arachnist** [gorhill/uBlock#383]
It appears that using the built-in addon search in firefox you can't find neither uBlock nor uBlock Origin.
![uBlock](https://cloud.githubusercontent.com/assets/117764/8266588/86297696-1736-11e5-9dc1-b85701c82608.png)
![uBlock Origin](https://cloud.githubusercontent.com/assets/117764/8266587/8628ae96-1736-11e5-8d65-3c2b6dc07921.png)

**Comment by metaphoricgirrafe** [comment]
Most likely due to the add-on only having a preliminarily review by Mozilla.

**Comment by gorhill** [comment]
Because they are not fully reviewed yet. It's explained somewhere on AMO.

**Comment by benyaminl** [comment]
Now they're busy on Servo and E10S. This two things cause allot of problem... I just move to opera because of this...
