### ISSUE TITLE
CTRL + Z clears "My Filters" and other Dashboard text areas on Firefox

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#385]
Case I 
1. Open the Dashboard and go to the "My Filters" page. 
2. Click on the text field with your rules
3. Press CTRL + Z

Expected result: nothing to change, since no edits have been made to the filters.
Actual result: the text area is cleared.

---

Case II
1. Open the Dashboard and go to the "My Filters" page. 
2. Click on the text field with your rules
3. Type or delete something
4. Press CTRL + Z twice

Expected result: the edit that has been made to be reverted, and nothing else.
Actual result: the text area is cleared. 

---

I've opened an existing text file on Pastebin.com and pressed CTRL + Z to check if this was a Firefox bug, but it didn't clear the editor.

EDIT: this happens to other Dashboard text areas too, like the box to input links to custom lists.

uBlock Origin 0.9.9.2
Firefox 39 for Windows

**Comment by gorhill** [comment]
> if this was a Firefox bug, but it didn't clear the editor

Using Chromium, Ctrl-Z does nothing. uBlock does absolutely nothing with keyboard events, and just make use of plain HTML stuff, so I don't see how this can be a uBlock issue.

**Comment by gorhill** [comment]
This was fixed as a consequence of now using CodeMirror: 61ec088d4342.
