### ISSUE TITLE
Fails to block video ads on YouTube

### ISSUE THREAD

**Issue by ZiotecH** [gorhill/uBlock#387]
I'm not sure when this started, but it has to have been recently.

uBlock can no longer block video ads on YouTube, it simply removes the ability to skip it manually.

This issue was found in Chrome version 43.0.2357.124 m.

**Comment by gorhill** [comment]
No URL provided. No setting details provided.

Tried one Youtube video: no ad.

From now on, I will close issue reports for which no effort is provided for me to reproduce without having to go on a time-wasting quest to figure all the details on how to reproduce.
