### ISSUE TITLE
sourceforge.net false alarm from Badware risks

### ISSUE THREAD

**Issue by folos1** [gorhill/uBlock#388]
sourceforge.net false alarm from Badware risks

https://www.virustotal.com/hu/url/bd589f9663d3f5fe01ae60efcf002959ded015ebb4b15051358ab9147134cdb9/analysis/1434946482/
1/63

**Comment by hotdogman** [comment]
https://github.com/gorhill/uBlock/blob/19487f10cd41cfc01b88e8b11b094e780395982f/assets/ublock/badware.txt/#L8-14

**Comment by SW1FT** [comment]
@folos1 Instead of posting 2 issues, maybe you should read more about the "problems" you've encountered.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Badware-risks>.
