### ISSUE TITLE
http://www.phonearena.com/ false alarm from Malvertising filter list

### ISSUE THREAD

**Issue by folos1** [gorhill/uBlock#389]
http://www.phonearena.com/ false alarm from Malvertising filter list

https://www.virustotal.com/hu/url/b5a204a71cc3d00a31c6c1d29ef3433f13d33f629013ae2a563dd431a2498cae/analysis/1434956236/
0/63

**Comment by hotdogman** [comment]
If you think there is an issue in the malvertising list, report it to the people who maintain the malvertising list.
>https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
># Contact: support [at] disconnect.me
