### ISSUE TITLE
[Firefox] Some hidden by cosmetic filters elements is stay visible

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#390]
ABP:
<a href="https://lh3.googleusercontent.com/--fHfoHrhUQU/VYgelX1iovI/AAAAAAAAbWc/cC6TaoSmzaY/s0/screenshot%2525202015-06-22%252520008.png"><img src="https://lh3.googleusercontent.com/-euwoWcIeZFQ/VYgemiLnhJI/AAAAAAAAbWg/Sh12UVnUWT8/s0/thumb4.png" border=0></a>

uBlock Origin:
<a href="https://lh3.googleusercontent.com/-482gMZRg9LM/VYgeixAyE9I/AAAAAAAAbWM/bWJQ_G0gg10/s0/screenshot%2525202015-06-22%252520007.png"><img src="https://lh3.googleusercontent.com/-iveMmewD5Mk/VYgekO_an8I/AAAAAAAAbWQ/_wQfJ2K5hG0/s0/thumb3.png" border=0></a>

<a href="http://skidkaonline.ru/moskva/shops/diksi/">http://skidkaonline.ru/moskva/shops/diksi/</a>

Win 8.1 x64, Firefox Nightly 41.0a1 x64 BuildID:20150621030204 (e10s disabled), uBlock Origin v0.9.9.2("Parse and enforce cosmetic filters" - enabled)/ABP 2.6.9.3954, Easylist + RU AdList.

**Comment by gorhill** [comment]
The issue occurs *only* if:

- Non-multiprocess Firefox
    - Does not occur on multiprocess Firefox
    - Does not occur on Chromium
- Forcing a reload through a reload button
    - Does not occur if navigating to the page (click or address bar)

I suspect there is something peculiar to Firefox behind this: it is as if uBlock's content scripts are not executed if it is a forced reload.

Does not occur if using a _specific_ filter:

    skidkaonline.ru##.hidden-xs.hidden-print.ads

**Comment by gorhill** [comment]
I can't reproduce the issue with 0.9.9.3-dev.? build.

**Comment by Halibut80** [comment]
Still occurs for me, with dev.8.

**Comment by DropTable69** [comment]
Occurs for me with the last several versions of uBlockO on Firefox and Chrome(ium). Windows and Linux. Seems to be related to user agent somehow, I've zero idea why. Sometimes it'll actually hide things for a couple page loads then they always reappear.

**Comment by DropTable69** [comment]
Occurs for me with the last several versions of uBlockO on Firefox and Chrome(ium). Windows and Linux. Seems to be related to user agent somehow, I've zero idea why. Sometimes it'll actually hide things for a couple page loads then they always reappear.

**Comment by ferrerverck** [comment]
I can reproduce this bug with twitter. I am using firefox 42.0, Ubuntux86 on 2-core machine and uBlock Origin 1.3.6.
The rule which most of the time does not work: twitter.com###signin-dropdown

I use cookie cleaner, so when I open any twitter page (for example: https://twitter.com/reuters) site thinks I am a new user and I always get that annoying sing-in popup window, which should be hidden by the aformentioned rule. Also when I click on the link "Have an account? Log in" in the upper right corner, that popup shows too, but should be hidden.
Also element hiding tool seems to be not working at all on google translate.

I hope my feedback will help to catch this elusive bug. And thx for great addon. :+1:

**Comment by gorhill** [comment]
@ferrerverck I looked into your case and there is no reason why the rule `twitter.com###signin-dropdown` should not work. Please provide all the filter lists you are using, and all your custom rules, and whether your are using dynamic filtering rules and whether there is the cosmetic filtering switch is off for Twitter.

See reasons of why you Twitter filter may not work: <https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappear-when-you-reload-the-page>.

**Comment by Halibut80** [comment]
Looks like this fixed by <a href="https://github.com/gorhill/uBlock/issues/1015">https://github.com/gorhill/uBlock/issues/1015</a>. So I close issue as duplicate.

**Comment by ferrerverck** [comment]
I have have solved my issue with twitter. The problem was that I have blocked completely twitter in a dashboard, but enabled it on twitter. But it affected cosmetic filters, so they did not work.
I found this being counterintuitive that cosmetic filters are enabled by checking allow domain in a dashboard.

**Comment by gorhill** [comment]
> I found this being counterintuitive that cosmetic filters are enabled by checking allow domain in a dashboard.

This is why there is a [_Required reading_ link](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) aside _"advanced user mode"_ checkbox: `allow` should only very rarely used, `noop` is what should be used most of the time.
