### ISSUE TITLE
Problem with Ublock Origin's URL logger behaviour

### ISSUE THREAD

**Issue by enomat** [gorhill/uBlock#391]
The logger doesn't show the media files.
1. Open this page:

www.europa2.sk/srv/www/content/db/sk/tim-a-show/mp3-archiv/
1. Type this in the logger's filter:

.mp3

If you open Adbock's blockable item list, you can find this url. Adbolck Plus/Edge recognizes it as "audio/video" type.

http://i.lagardere.cz/europa2/file/edee/tim-a-show/mp3-archiv/15388/06_0.mp3

The Ublock Origin's behaviour is strange and buggy.
- Sometimes this URL doesn't appear in Ublock Origin's logger.
- Sometimes multiple instances will appear of the same file.
- Sometimes only one URL will appear.

I've even created a new clean Firefox profile, installed Ublock Origin 0.9.9.1 from addons.mozilla.org .

Screenshot:
![ublockbug_3](https://cloud.githubusercontent.com/assets/12612250/8286570/9fc6c600-190a-11e5-9060-837e23a414b1.JPG)

Then opened the above mentioned page (www.europa2.sk/srv/www/content/db/sk/tim-a-show/mp3-archiv/), and:
- reloaded that page multiple times
- disabled/enabled Ublock Origin, then tried again the refreshing

The bug occurs randomly.

Tried the standard µBlock 0.9.3.5 from addons.mozilla.org, but the problem is the same.

This bug means that the Ublock's logger engine is not reliable.

**Comment by gorhill** [comment]
uBlock reports exactly whatever Firefox API pass to uBlock.

I can see this resource is pulled differently by Firefox, using ranges:

    Range: bytes=0-

And thus the response from the remote server looks like:

    Content-Range: bytes 0-115826687/115826688

If there are multiple entry for the same resource, it's simply because Firefox's makes multiple requests for the same resource, uBlock merely shows you what is happening internally.

**Comment by enomat** [comment]
But even if the URL is not shown in the logger, the media file still downloads and plays. (So the user won't be able to find the URL of the media file that is playing, if the bug occured while he is using the logger.)

So the problem is still that Ublock sometimes doesn't report all the files that are downloaded from the page.

And it's worth mentioning that Adblock shows this file every time properly (always 1 .mp3 URL at every refresh).

**Comment by gorhill** [comment]
> problem is still that Ublock sometimes doesn't report all the files that are downloaded from the page

This could be because the HTTP observer is not taking into account cache resources. This can be added.

**Comment by neilishere** [comment]
I also have problems with the unified logger:
When the selector is set "behind-the-scene" and I "reload all tabs", the logger becomes flooded with all requests (as if the selector changes to "all"), but the selector still says "behind-the-scene".  Then if I hit the eraser, only behind-the-scene requests are deleted.  It is not only until I change the selector to "all" and hit eraser, and select "behind-the-scene" again can I resume monitoring.

Opera 30 and Palemoon 25 (both stable) on win 8.1 - ublock 9.9.2

Some history: My other computer has same Opera but with ublock 9.6.0 (last version before unified logger), and behind-the-scene logger is "pinned", and only behind-the-scene requests are shown - even after launch.  (Sure, some requests are not blocked or missing after launch, but I just hit eraser and can resume monitoring behind-the-scene requests)

Thank you

**Comment by gorhill** [comment]
@neilishere Please open a new issue, merging all kind of different issues into a single one is messy.

**Comment by enomat** [comment]
But that .mp3 file is never cached. (It always starts downloading from the beginning.)

The chance of that the bug occurs is highly increases if you disable/enable Ublock Origin in the current session.

**Comment by gorhill** [comment]
> But that .mp3 file is never cached

I am tracing into the code and I can see only one network request reported by Firefox. Yet I am seeing 3 reported requests in the logger. Investigating.
