### ISSUE TITLE
uBlock Orign blocking 23,000 requests on HBO Go

### ISSUE THREAD

**Issue by static-pixel** [gorhill/uBlock#392]
![image](https://cloud.githubusercontent.com/assets/13009943/8297337/62e06424-192a-11e5-941f-b08795bac53e.png)

I feel this is an issue that needs to be looked into. HBO Go shouldn't be having over 23k places to block.

**Comment by unitbroker** [comment]
I see you conversations, and thank you.   On this side, I am pushing these two machines as hard as I can.  The desktop is in need of being wiped and started over, and I am using this new tool without taking the time to read and set it up properly.  I just grabbed a bunch of apps and threw them in and fired it up!  I don’t think I have it configured right.

 

I appreciate the notes.  And I tell you what I would love to share with you, if I can be helpful in getting you dialed into whatever issue I would like that, And I have a couple other items that you may want to look at. I am putting together a product and could use an extra set of eyes.  

 

I have an open source crawler that I am having trouble configuring,   Do you guys do any side work?

**Comment by tenkuu** [comment]
What's being blocked in the network logger?

**Comment by unitbroker** [comment]
There is some trickery going on here, yes sir. It’s a firewall Scott Gumble put together for me,  The hardest time I have with it is getting it to loosen up enough to let me do what I need,  I think my crawler is blocked and  the fire wall, in addition to being configured wrong.

 

What, I sending of 23,000 of anything?  And to HBO?  Yeah, let me take a look real quick what’s going on. Maybe I’m under attack or caught bug.

**Comment by unitbroker** [comment]
It’s malware, I must have a bug. Crap!

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.
