### ISSUE TITLE
[Firefox] Closing a window doesn't remove its tabs from the network logger picker

### ISSUE THREAD

**Issue by AlexVallat** [gorhill/uBlock#394]
Just a minor thing, but as I encountered it when investigating a related bug in uBlock I thought it was worth reporting.

Repro steps:
1. Open network request log
2. Open a new window, navigate to example.com. Note that "Example Domain" appears in the tab picker on the network log page.
3. Close the new window. Note that "Example Domain" has not been removed.

For comparison, doing the same thing but opening a new tab instead of a new window does remove it. There may be other side-effects to onTabClose not being called for tabs of a closing window, but this was the most obvious one.

**Comment by gorhill** [comment]
Thanks for reporting.
