### ISSUE TITLE
[suggestions] optional list of acceptables ads. 

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#395]

**Comment by LifeIsStrange** [comment]
(Oh ! Sorry I did something wrong with my keyboard !) 

Please add the list of Adblock plus for the acceptables ads, of course Just in option.

**Comment by alejandrolemus** [comment]
This project does not support acceptable ads, please see [uBlock's Origin manifesto](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md).

**Comment by RandomAcronym** [comment]
Why people come and ask for this confuses me.
Should one not find a **truly** acceptable advert that exists, before asking for them to be added to a whitelist?
It's hard to make a list of items that, currently, are only theorized to be possible; I've not seen one myself.

**Comment by LifeIsStrange** [comment]
+1 RandomAcronym 

I think that a web of acceptables ads is more desirable than a web full paying. Because the money narrow the web contents for the poor. 
Because the donation can't replace fully the price or the ad, it's Just a very good complement. Me too I Hate ads because it's a mass disinformation ! But we will be realist. 

Nowadays the people can have access to a web without ads and without cost grace at you gorhill, grace at your awesome ublock0 or grace to all the others blockers, but it's cheating and 
Like all good things, it has an end, why ?? Because one Day (probably during this decade) all humans will have ads blockers, it's statistic and so during this decade If you don't change this with an OPTIONAL list of true ACCEPTABLE ads, the web of ads will die....  It's awesome !! Not truly... Because it will be paying,and it will be a tragedy, sincerely. The web can't will be full free, but without money there are no motivation (Just the altruisme and on the free time..  It's beautiful but the human is unfortunately bad, or his education makes bad and you can't remake the World :/). 

You say in your manifest that the people can do his list of whitelist, but it's utopic, it's true for 0.1 % of the people, because it's need an personnal and chronophage effort, and for what ? For see ad ? It must be brave

While a single option list will be so much more desirable, so much easier, so much more convenient, plus it forces advertising agencies to adopt acceptable pubs ! 
Please add this Just in option for the good of the future of the web, Thank you for your understanding and I am very sorry for take your precious time.

**Comment by alejandrolemus** [comment]
I've seen this debate countless times, and it still confuses me why do people think that Internet cannot survive without ads. 
Personally, I don't appreciate ads been forced on my pages, so I don't find any of them "acceptable". The whole term is misleading, sorry. You can choose to serve them on your site, I can choose to block them on my browser (I pay for my connection, after all). 
You say blocking ads is cheating, I beg to differ. Cheaters are those trying to monetize my browsing without option or consent. If they truly feel they content is so valuable, make it pay-per-view. If it has any merit, it will grow. If not, then get a job in another field. Or try a different approach to monetize your traffic, ads are not the only model out there.

**Comment by RandomAcronym** [comment]
Personally I think any form of ethnical advertising would have to be impossible to engage with (no links) and the people being paid would need to be apart of the ad, at least in the embedded tobacco ads of yesteryear the people making money off killing people with cancer were also giving themselves cancer

**Comment by anewuser** [comment]
Please read https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Ideas that affect the purpose of the extension and "+1" comments aren't allowed in this repository.

**Comment by MarcoSulla** [comment]
I don't understand why adding it as unched by default can harm someone. Who wants to activate it, he can activate it.

Yes, we're free to add it manually, but how many people do? How many people ever ***knows*** that such a list exists?

I think adding a list unchecked by default can harm no one and I think it's not a big effort for devs (but maybe I'm wrong, I don't know the source code)

**Comment by gorhill** [comment]
Nobody said it can "harm someone". uBO is not to be used to prop up the revenues of for-profit corporations.

**Comment by uBlock-user** [comment]
> I don't understand why adding it as unchecked by default can harm someone.

By that logic, there are hundreds of other lists lying around on github whom should be added too because they don't harm anyone either.

Fyi, lists are no longer added on suggestions, but by the uBO team via internal discussions and secondly, regarding this list, it goes against the uBO's manifesto.
