### ISSUE TITLE
[Firefox] Question - hiding elements

### ISSUE THREAD

**Issue by gituporabnik** [gorhill/uBlock#396]
I have a question relating to hiding website elements.

When ads are blocked, there are often empty banners left and I hide them with uBlock element picker.
The problem is, there are some webpages on which universal filter rules don't work: sometimes each subpage has different number/characters. Hence banners cannot be hidden by one filter rule, because rules for every subpage should be added manually.

Example:
<code>www.etiketamagazin.com###post-43421 > .banner.slide</code>

Question: in the upper example, number "43421" changes with every subpage. Is there any way to replace this number with a universal sign? The asterisk sign (*) doesn't work, since this is not a URL.

**Comment by gorhill** [comment]
Cosmetic filters are [CSS selectors](http://www.w3.org/TR/css3-selectors/) prefixed with `##`. So whatever is a valid CSS selector will work:

    www.etiketamagazin.com##[id^="post-"] > .banner.slide

**Comment by lencc** [comment]
It works. Thank you!
