### ISSUE TITLE
theage.com.au/smh.com.au gets stuck hammering fairfaxau.d1.sc.omtrdc.net

### ISSUE THREAD

**Issue by CarlosMerc** [gorhill/uBlock#397]
Connecting to theage.com.au or smh.com.au via firefox 38.0.1 ESR with ublock enabled (with only easylist active, tried the default ones too), the connection hammers fairfaxau.d1.sc.omtrdc.net about 15k/sec up and down for a long time. 
Disabling ublock has unpredictable results. Sometimes "normal" behaviour will return, other times not.
Removing ublock causes "normal" results all the time.

**Comment by gorhill** [comment]
Can't reproduce with out of the box settings + updated filter lists.

Reminder: uBlock is not responsible for effects of 3rd-party filter lists -- bring any issues to their respective maintainers.
