### ISSUE TITLE
Can't Open uBlock Or on Avant Browser Gecko - FF based

### ISSUE THREAD

**Issue by benyaminl** [gorhill/uBlock#398]
![untitled](https://cloud.githubusercontent.com/assets/2817332/8350332/cf590ca2-1b4e-11e5-9bb7-eadb64097a3d.png)
This is a problem, I think maybe should be considered, because I'm experience it self, when I click the logo nothing happend, or shown from UBlock..

Ver : 0.9.9.2
I hope there's a things can be done with this problem, I hope so, thanks before

**Comment by gorhill** [comment]
I don't plan on taking care of more browsers than what I am currently taking care of. It's a fork case.
