### ISSUE TITLE
[SeaMonkey] 3rd-party filters gone until settings reset

### ISSUE THREAD

**Issue by bytes-and-bits** [gorhill/uBlock#399]
Using uBlock0 0.9.9.2 on SeaMonkey 2.33.1 on Windows XP, I'm seeing an issue where the contents of the 3rd-party filters tab is as expected on initial install, but is blank after the browser is restarted.  Toggling the "auto-update filter lists" and "parse and enforce cosmetic filters" checkboxes on and off eventually allows the "Apply changes" button to show up, but clicking "Apply changes" doesn't seem to do anything and the cursor just shows the hourglass icon.  The only way to fix this appears to be resetting uBlock0 to the default settings every time.

Steps to reproduce (from a fresh SeaMonkey install):
1. Launch SeaMonkey
2. Install uBlock0
3. Go to uBlock0 Dashboard -> 3rd-party filters
4. Verify filters are as expected
5. Restart SeaMonkey
6. Go to uBlock0 Dashboard -> 3rd-party filters
7. Filters are no longer listed

![ublock0_seamonkey_filter_bug](https://cloud.githubusercontent.com/assets/8423814/8350586/b882146a-1adb-11e5-99a2-e7ee49c1b2d9.png)

For what it's worth, uBlock 0.9.5 doesn't seem to have this problem.  From the comments, it would appear that commit https://github.com/chrisaljoudi/uBlock/commit/d9b23d4f109881a87e2516aee31c20f23105c90e had something to do with it.

**Comment by gorhill** [comment]
I could reproduce. uBlock is in a bad state after launch.

Disabling/enabling uBlock put it back in a good state.
