### ISSUE TITLE
Palemoon

### ISSUE THREAD

**Issue by 3k2** [gorhill/uBlock#40]
Hi

Any chance to get palemoon support?

**Comment by Havokdan** [comment]
Talvez isso lhe interesse: http://forum.palemoon.org/viewtopic.php?f=16&t=7373

**Comment by gorhill** [comment]
See <https://github.com/chrisaljoudi/uBlock/issues/518>. I do not intend to spend time any more time on this. I did provide ability to access the popup UI from the request log, that's as far as I am willing to go. It's volunteered work, so in my opinion another developer should step up for addressing whatever needs to be worked on for Palemoon support if they think it's worth it.
