### ISSUE TITLE
Exact address blocking not working

### ISSUE THREAD

**Issue by vaindil** [gorhill/uBlock#400]
- Windows 8.1, x64
- Chrome stable, 43.0.2357.130 (32-bit)
- uBlock version: 0.9.9.2

I'm using the rules at the bottom of this issue to attempt to block a specific address (my reddit user page, as an example), but the page is not being blocked. I do not see anything on [the relevant wiki page](https://github.com/gorhill/uBlock/wiki/Filter-syntax-extensions) that would preclude the [ABP rule](https://adblockplus.org/en/filter-cheatsheet) from working, so I'm not sure what's wrong.

Rules I'm using (in the `My Filters` section):

```
|reddit.com/u/icefall5|
|www.reddit.com/u/icefall5|
|reddit.com/user/icefall5|
|www.reddit.com/user/icefall5|
|http://reddit.com/u/icefall5|
|http://www.reddit.com/u/icefall5|
|http://reddit.com/user/icefall5|
|http://www.reddit.com/user/icefall5|
|https://reddit.com/u/icefall5|
|https://www.reddit.com/u/icefall5|
|https://reddit.com/user/icefall5|
|https://www.reddit.com/user/icefall5|
```

**Comment by SW1FT** [comment]
`||reddit.com/*/icefall5` should do the trick.

**Comment by gorhill** [comment]
> but the page is not being blocked

Whole pages are blocked **if and only if** the filter matches only the hostname part of the URL (reference: https://github.com/chrisaljoudi/uBlock/issues/1128).

**Comment by gorhill** [comment]
Fixed with fa4e3ca492d2ff4d02e467b538695702e4b0be18.

**Comment by harshanvn** [comment]
So, this is part of strict blocking functionality? And now we will allow to block specific pages instead of just domains. This is really great news and nice addition!
If so, i think this might deserve to have an update in Release Notes and in Wiki section..
Another feature ublock and ABP like are missing..

**Comment by gorhill** [comment]
> So, this is part of strict blocking functionality?

I figure this was needed if I wanted to warn about `tucows.com/downloads`, which is cited in a couple of places as being one of the worst when it comes to badware.

**Comment by neilishere** [comment]
Does this change?  https://github.com/gorhill/uBlock/wiki/Filter-syntax-extensions#not-supported

Are static lists now given the ability to make exceptions - and override our filters? like ABP?

**Comment by gorhill** [comment]
> Does this change?

No, the `document` filter option is still ignored for exception filters.
