### ISSUE TITLE
Unified logger errors behind-the-scene requests - Opera and legacy Firefox

### ISSUE THREAD

**Issue by neilishere** [gorhill/uBlock#404]
When the selector is set "behind-the-scene" and I "reload all tabs", the logger becomes flooded with all requests (as if the selector changes to "all"), but the selector still says "behind-the-scene".  Then if I hit the eraser, only behind-the-scene requests are deleted.  It is not only until I change the selector to "all" and hit eraser, and select "behind-the-scene" again can I resume monitoring.

Opera 30 and Palemoon 25 (both stable) on win 8.1 - ublock 9.9.2

Some history: My other computer has same Opera but with ublock 9.6.0 (last version before unified logger), and behind-the-scene logger is "pinned", and only behind-the-scene requests are shown - even after launch.  (Sure, some requests are not blocked or missing after launch, but I just hit eraser and can resume monitoring behind-the-scene requests)

Thank you

**Comment by neilishere** [comment]
More info:
* only between 15 and 25 tabs,
* I updated ublock for both browsers from your releases page

I can see *maybe* where other tabs in the selector should default to `all` after a reload or relaunch, but `behind-the-scene` should be persistent - since it is always there - as in 9.6.0.

This error does not seem to be browser-dependent.

**Comment by gorhill** [comment]
> after a reload or relaunch

Not sure I understand.. Are you saying the issue is when reloading uBlock while the logger is still open?

**Comment by neilishere** [comment]
No, ublock is never off.  It is the reloading of tabs (F5) I am talking about - whether from starting the browser (reload tabs from previous session option in browser), or reload all tabs menu.  The logger is one of those tabs.

**Comment by gorhill** [comment]
Ok I see, the issue is forcing a reload of the logger tab itself, in which case its internal state is out of sync with its widgets (forcing a reload of all tabs also forces a reload of the logger).

**Comment by neilishere** [comment]
9.6.0 logger seemed to remember it's state even after a tab reload, whereas the new logger does not?

**Comment by gorhill** [comment]
0.9.6.0 was not the unified logger, things worked differently. But it still suffer from a similar issue: enter a filter expression, reload the logger, filter expression won't apply (something I will also fix aside the tab selector quirck).

**Comment by neilishere** [comment]
Thank you,
Behind-the-scene is a great feature, just another of the many that set uBlocko apart from the rest.

. . . (Hey, don't listen to that guy (#405))
