### ISSUE TITLE
Why we need to have two filters for lowercase/capital letters?

### ISSUE THREAD

**Issue by smed79** [gorhill/uBlock#408]
Hi, 
for an **adblocker** i like to know what is the difference between two urls written in lowercase or capital letters?

for example this filters `##a[href^="http://www.FriendlyDuck.com/AF_"]` found on **easylist** can't block banners link to: FriendlyDuck.**C**om/AF_

why we need to have two filters for just one lowercase/capital letter **C**? 

```
##a[href^="http://www.FriendlyDuck.com/AF_"]
##a[href^="http://www.FriendlyDuck.Com/AF_"]
```

test: `http://tinyurl.com/warez-world`
Thanks!

**Comment by gorhill** [comment]
> why we need to have two filters for just one lowercase/capital letter C?

Cosmetic filters must be valid [CSS Selectors](http://www.w3.org/TR/css3-selectors/), and so are bound by the semantic of CSS Selectors. Attribute values are case-sensitive.

**Comment by gorhill** [comment]
By the way, you test case can be solved using a smarter filter:

    ###headerinfo-right-a

There can be only one `id` per element, so case sensitivity is not an issue when basing the cosmetic filter on the `id`.
