### ISSUE TITLE
Unable to hide some elements on nextinpact.com/

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#409]
Hi guys,

For the last 2 weeks i'm unable to hide some elements with ublock on http://www.nextinpact.com/
I tried to block this ad with the element picker but when  i reload the page it comes back.
http://hpics.li/1a56812
In this page the same thing happens : http://www.nextinpact.com/news/95569-uberpop-doit-etre-dissous-reclame-francois-hollande.htm
I tried to hide the element on the right but with no luck http://hpics.li/ebf772f

I noticed that each  time I block an element, it reappears with a new address. 

I'm using Chromium  45.0.2437.0

**Comment by gorhill** [comment]
> it reappears with a new address

I am not a filter list maintainer, I can't start to answer all requests to create a specific filter for whoever asks, that will become a full time task, not something I ever plan on taking on as hobby. I am sure there are forums out there where people can help each other with such issues.
