### ISSUE TITLE
Ublock does not seem to work with Youtube ads

### ISSUE THREAD

**Issue by xavhan** [gorhill/uBlock#410]
Something must have changed, uBlock does not work anymore on youtube content. 
Do you have an idea of what is happening ?

AdBlock Plus either btw.

**Comment by SW1FT** [comment]
That's a problem with the lists you are using. Maybe they are not blocking ad servers in your country.

**Comment by gorhill** [comment]
I don't maintain EasyList. Please report to EasyList maintainers.
