### ISSUE TITLE
Balloon Translate Google Chrome

### ISSUE THREAD

**Issue by ialexsilva** [gorhill/uBlock#411]
When open the dashboard of ublock origin the balloon of translate show up

Windows 8.1 
Google Chrome 43.0.2357.130 m
uBlock Origin 0.9.9.2

**Comment by gorhill** [comment]
I opened the dashboard and no balloon appeared.

**Comment by ialexsilva** [comment]
to reproduce you need a non-English browser

**Comment by gorhill** [comment]
> you need a non-English browser

I launched the browser in French, using `LANGUAGE=fr chromium-browser` on the command line, went to the dashboard, and no balloon appeared.

**Comment by ialexsilva** [comment]
Try to uninstall the ublock and install again and open dashboard

**Comment by IDKwhattoputhere** [comment]
@gorhill Do you have translation of foreign languages switched on?
@ialexsilva Which language is your browser in?

**Comment by gorhill** [comment]
Was never able to reproduce this weird issue --- appears to be specific to user. If it occurs again, you will have to first **make the case** it is a uBO issue before opening an issue here.
