### ISSUE TITLE
Clicking on ads that should open in a new tab instead open in the parent tab

### ISSUE THREAD

**Issue by tagline15** [gorhill/uBlock#412]
I have whitelisted a few pages in uBlock Origin and when I click on ads that are supposed to open in a new tab, ublock kicks in and prompts me to allow temporarily or permanently. So far so good.

The issue is that the ads open in the parent tab. Also a new empty tab is created.
Is it possible to leave the parent tab as it is and open the ublock dialogue in a new tab where I then can allow/deny the ad to load?

Windows 7; Firefox 38.0.5; uBlock Origin 0.9.9.2

Thanks for looking into this. :D

**Comment by gorhill** [comment]
> Thanks for looking into this

I can't, you did not give me steps to reproduce and settings, as explained here: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

**Comment by tagline15** [comment]
Sorry, here is an example:

1. Go to http://stadt-bremerhaven.de/
2. Whitelist the page
3. Click on the small LG ad on the right side
4. ublock dialogue opens in parent tab and new empty tab is opened

Filters active:

uBlock filters‎
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Unbreak
EasyList
Peter Lowe’s Ad server list‎
EasyPrivacy‎
Malware Domain List
Malware domains
Fanboy’s Social Blocking List‎

**Comment by gorhill** [comment]
Works fine on Chromium, seems to be something specific to Firefox.

**Comment by atlanto** [comment]
In my case,
at http://filehippo.com/download_smplayer/ , click the link to sourceforge.net (in "By The SMPlayer Project  (Open Source)")
Expected: blocking page opened in a new tab
Actual: a new blank tab opened and blocking page opened in the source tab

This will happen when the link has 'target' attribute.(including &lt;base target=...&gt;)

As far as I could investigate, contentObserver.shouldLoad is being called twice.
The first call comes from the current tab without opener.
The second call comes from a new tab with opener.

(btw, though I'm not understanding about pending request at all, httpObserver.createPendingRequest doesn't make an array, and httpObserver.observe doesn't handle multiple pending requests. As a result, uBlock is processing the first call(blocking page is opened in the source tab), and not processing the second call(new tab is left blank), maybe)

My humble idea is...
Detect the link has 'target' or not. If it has 'target' and opener is null, ignore the request.

Just a test code (frameModule.js, 0.9.9.3)
176:        if ( !context.top || !context.location ) {
177:            return this.ACCEPT;
178:        }

        // Omit the invalid request - having target and not for the target
        let element = context.document.activeElement;
        if ( element !== null ) {
            let target = element.target;
            if ( target !== null ) {
                if ( target === "_blank"
                    || ( target !== "_self" && target !== "_top" && target !== "_parent"
                        && target !== context.name ) ) {
                    if ( context.opener === null ) {
                        return this.ACCEPT;
                    }
                }
            }
        }

180:        let isTopLevel = context === context.top;
181:        let parentFrameId;
182:        if ( isTopLevel ) {

I would appreciate if you will consider it when you have time.
Best reagrds.

**Comment by gorhill** [comment]
@atlanto 

> As far as I could investigate, contentObserver.shouldLoad is being called twice.
> The first call comes from the current tab without opener.
> The second call comes from a new tab with opener.

Thanks for the investigation, this really helps.

I will look into your proposed solution.

**Comment by gorhill** [comment]
The solution relying on the link's target being one of `_blank` etc. is putting a lot of faith on the assumption that `shouldLoad` will be called twice in such case. If ever this is not true for a future (or even past) version of Firefox, this will break uBlock. So far I haven't found a solution, but I need to still look more. However, for now, I rather have user deal with this quirky issue by using right-click then _"Open Link in New Tab"_.

**Comment by gorhill** [comment]
Can no longer reproduce using the two cases provided.
