### ISSUE TITLE
Add the "Adware filters" blocklist to uBlock Origin

### ISSUE THREAD

**Issue by anonsubmitter** [gorhill/uBlock#413]
Can you add MonztA's "Adware filters" blocklist to uBlock Origin?
https://adblockplus.org/en/subscriptions

**Comment by gorhill** [comment]
People can add it by clicking the subscribe link at the link you provide.

**Comment by anonsubmitter** [comment]
I am aware of that, I just thought it was worth including as a filter in the extension itself. But I now see that this repository only accepts bug reports so never mind.

**Comment by gorhill** [comment]
I plan to have a wiki page with all filter lists that one may want to subscribe, and you could directly edit that wiki page and add whatever lists you think is worth it. However, I need to extend the subscribe syntax in order for uBlock to react to the link properly.
