### ISSUE TITLE
Zscaler Safe Shopping filter

### ISSUE THREAD

**Issue by anonsubmitter** [gorhill/uBlock#415]
[Zscaler Safe Shopping](https://addons.mozilla.org/firefox/addon/zscaler-safe-shopping/) is a Firefox add-on that warns the user if the online store the user is visiting is hacked or a scam site. I was wondering if it would be possible to somehow extract Zscaler Safe Shopping's filter list and turn it into a uBlock filter?

**Comment by anewuser** [comment]
> Submit bugs/issues only. 
> Do NOT:    Submit design ideas.
> Do NOT:    Submit feature requests.
> Do NOT:    Submit "revolutionary ideas".

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by gorhill** [comment]
That should not be filed here. If you think the list used by Zscaler Safe should be public, file an issue with Zscaler Safe asking them to do so, and even then, unlikely I will agree it should be a stock filter list in uBlock -- I rather stick to the ones likely to be used by more than a handful of users, or else this will just lead to an impossibly long list of filter lists.
