### ISSUE TITLE
uBlock Origin not blocking ads on GameSpot

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#417]
I don't have a problem with the ads on gamespot(ill turn it off to support them). Just thought I'd let you guys know.

http://www.gamespot.com/videos/fenix-on-his-big-play-and-where-he-stands-vs-bjerg/2300-6425761/

**Comment by hotdogman** [comment]
Please report it to the EasyList maintainers on https://forums.lanik.us/. uBlock does not maintain third-party filter lists.

**Comment by IDKwhattoputhere** [comment]
Issue still exists: https://www.reddit.com/r/uBlockOrigin/comments/48ct9p/video_ads_on_gamespotcom_not_being_blocked/

No solution was found on the EasyList forums: https://forums.lanik.us/viewtopic.php?f=62&t=26352

I too have been unlucky to find a way to block the ads.

Chrome 48 with flash
uBO 1.6.2
