### ISSUE TITLE
Cannot block request to YouTube after video closed

### ISSUE THREAD

**Issue by metaphoricgiraffe** [gorhill/uBlock#418]
**Issue summary**
Cannot block behind-the-scene image request after YouTube video is closed.

**To reproduce**
1. Open YouTube video (e.g. https://www.youtube.com/watch?v=3TtVsy98ces) in a new tab
2. Open uBlock logger (chrome://ublock0/content/logger-ui.html)
3. Close YouTube video tab and observe outgoing requests
4. See image requests to https://s.youtube.com/api/stats/qoe?event=streamingstats and https://s.youtube.com/api/stats/watchtime?ns=yt&el=detailpage being made in the logger after video is closed
5. Create filter from UI to block requests
6. Retry steps 1-4 to see requests are blocked

**Screenshots**

UI Logger in step 4 and 6 showing requests to s.youtube.com being made:
![requests](https://cloud.githubusercontent.com/assets/12890281/8399895/c95de2a6-1e59-11e5-8fe7-ada00dcfa8d9.png)

Filters created in step 5:
![filter](https://cloud.githubusercontent.com/assets/12890281/8399904/042d4624-1e5a-11e5-8ef3-cbb988f2e941.png)

Filters in uBlock dashboard:
![youtube-image](https://cloud.githubusercontent.com/assets/12890281/8399998/27767faa-1e5b-11e5-8f86-4f103839a0cc.png)

**Symptoms of the issue**

Requests made to https://s.youtube.com/api/stats/qoe?event=streamingstats and https://s.youtube.com/api/stats/watchtime?ns=yt&el=detailpage should be colored red (ie, a blocked request), instead of white.

**Browser details**

uBlock Origin 0.9.9.3 (beta), HTTPS Everywhere
Firefox 38.0.5 (latest version)
Windows 7

Also reproduced in:
uBlock Origin 0.9.9.1
Chrome 43.0.2357.130 (latest version)
Windows 8
Type of request is "object" instead of "image" in Google Chrome

**Comment by hotdogman** [comment]
Do you have "I am an advanced user" enabled in the dashboard? No? Then it won't work.
>https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests
>The filtering of behind-the-scene network request is available to advanced users.

**Comment by metaphoricgiraffe** [comment]
![dynamic](https://cloud.githubusercontent.com/assets/12890281/8401029/f286b678-1e6b-11e5-96ce-26b14d17f253.png)


@hotdogman Yes, I use the dynamic filtering as well.

I just tried  dynamic filtering instead of static filtering and it still doesn't turn "red" like my other blocked requests.

Were you able to reproduce?

**Comment by gorhill** [comment]
Is `behind-the-scene` whitelisted? (it is by default)

**Comment by metaphoricgiraffe** [comment]
Yes, it was whitelisted. 

That fixes it.

**Comment by aoaaxy** [comment]
I would like to note that requests to `s.youtube.com` (probably the one with `watchtime` in the url - I'm guessing) are used to remember the position(timecode) that the video was on,  and this position is restored later on when revisiting said video eg. upon browser restarts, or visiting the same video a few days later. This works for multiple videos not only the last viewed one.

Curiously, I remember that this worked even though I've whitelisted s.youtube.com (and in behind-the-scene) within uMatrix, BUT uBlock Origin still had it blacklisted(red);  I think it was dependent on the order that these 2 addons were installed.
