### ISSUE TITLE
Two questions - Filter list URL and Performance improvements

### ISSUE THREAD

**Issue by gituporabnik** [gorhill/uBlock#420]
I have 2 different questions concerning uBlock Origin.

1) Since the latest version, Badware filter list has been added. Could its URL be pasted here for the users of older versions (since AMO does not update add-ons frequently)? I would like to add filter list manually.

2) The latest uBlock version (by chrisaljoudi) has some "Firefox performance improvements". Have they been implemented in uBlock Origin as well?

Thank you!

**Comment by SW1FT** [comment]
1) You can use this `https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/badware.txt` for now.

2) I have no idea, but there were some improvements, but I don't think all of them were forked here (e.g: ability to block an element from the web-inspector).
Some of the improvements made for Firefox: 
https://github.com/gorhill/uBlock/commit/909244cdbdf2fc46217dec7239ac5704a41c7d60
https://github.com/gorhill/uBlock/commit/9406e40fdc1644040234b3e0b240e24fa576a214
https://github.com/gorhill/uBlock/commit/77c1e8b694c8f29c7bcf1d97775961a57bdb026a
https://github.com/gorhill/uBlock/commit/9e3684d6ca903fdf651e4fc6941e4bd091ad8878
https://github.com/gorhill/uBlock/commit/4091cd3a1d45fe58bdf834dbaa4febd010c64f4a
https://github.com/gorhill/uBlock/commit/c4b08567237af79bd97d130b93f7933002e8a64d
https://github.com/gorhill/uBlock/commit/013b07765624d93493dcd192145b09bc423934be
https://github.com/gorhill/uBlock/commit/6470216530548cd3dfecdce7d9aa94816d10d863
https://github.com/gorhill/uBlock/commit/2cb1f423355920ea8c22c148918ac41f8f4702fc
https://github.com/gorhill/uBlock/commit/62849f164d6487dc73f5f2343cc7691e9f3b43ca

**Comment by gorhill** [comment]
> Could its URL be pasted here for the users of older versions (since AMO does not update add-ons frequently)?

https://github.com/gorhill/uBlock/blob/master/assets/ublock/badware.txt

> The latest uBlock version (by chrisaljoudi) has some "Firefox performance improvements". Have they been implemented in uBlock Origin as well?

The original issue was [opened here](https://github.com/gorhill/uBlock/issues/266) (great issue report), it was fixed within 2 days with refactoring the problematic code, and the fix was released in [0.9.8.3](https://github.com/gorhill/uBlock/releases/tag/0.9.8.3).

**Comment by gorhill** [comment]
> The latest uBlock version (by chrisaljoudi) has some "Firefox performance improvements"

@chrisaljoudi likes to be vague so as to leave

**Comment by gorhill** [comment]
> but I don't think all of them were forked here (e.g: ability to block an element from the web-inspector)

uBlock Origin will have its [own DOM inspector](https://github.com/gorhill/uBlock/commits/inspector), optimized to deal with cosmetic filters, and working on all platforms. It's magnitude more work to implement, but this will make it a breeze to create cosmetic filters (including the missing ability to create _exception_ cosmetic filters).
