### ISSUE TITLE
Breaks on some pages of paypal.com

### ISSUE THREAD

**Issue by kiernangs** [gorhill/uBlock#423]
Paypal.com homepage fails to load - as well as their new shipping system.

**Comment by SW1FT** [comment]
Not happening to me. Please explain which errors occur, what's your uBlock Origin version, OS, Browser and filters.

**Comment by CrisBRM** [comment]
Can't replicate it either -- I mean, don't get me wrong, their servers _are_ rubbish and did take a WHILE to load, but they did load in the end.

**Comment by gorhill** [comment]
Could not reproduce either. Also marked as _invalid_ given that no details other than one domain name was given.

**Comment by gorhill** [comment]
Closing: un-reproducible issue abandoned by OP.
