### ISSUE TITLE
Youtube filters

### ISSUE THREAD

**Issue by DiabSoule** [gorhill/uBlock#424]
The new youtube filters that are listed here have all triggered a DNS attack popup. After some digging with who is 213.239.212.163 and reading some reports. More than a few have said that the IP is involved with  Dictionary Attacks. I am not saying it is a fact just bringing forth the info. Anybody else getting these alerts?

**Comment by gorhill** [comment]
> new youtube filters that are listed here

?

**Comment by DiabSoule** [comment]
yes

**Comment by gorhill** [comment]
I have no clue what you are talking about. What "new youtube filters that are listed here"? The only Youtube filters I can think of are from 3rd-party lists, i.e. EasyList, etc.

**Comment by gorhill** [comment]
`213.239.212.163` is `filter2.adblockplus.org`, a server from where EasyList et al. are downloaded.

**Comment by DiabSoule** [comment]
New wiki page for easy subscription to a choice of filter lists

Here: Filter lists from around the web

Not saying anybody here but the filters posted from that list are potentially bad. Just a heads up is all I am trying to say.

**Comment by gorhill** [comment]
The only popup there is is uBlock's one when clicking on the _Subscribe_ link, to offer the user to import the filter list into uBlock. It's by design.

**Comment by DiabSoule** [comment]
yes all of the youtube filters triggered dns alerts like this: 
![tooltip_003](https://cloud.githubusercontent.com/assets/11603431/8443839/de53cd96-1f4f-11e5-8108-29ab079de747.png)

**Comment by DiabSoule** [comment]
if link to that flter is clicked thats when I get warnings. Not from here just the links leading to the filter lists.

**Comment by gorhill** [comment]
> I get warnings

Which browser?
