### ISSUE TITLE
Filters 

### ISSUE THREAD

**Issue by DiabSoule** [gorhill/uBlock#425]
Why did you close the issue in the middle of explaining the problem? A bit rude to put it nicely. If click on subscribe link I get warning like this:
![de53cd96-1f4f-11e5-8108-29ab079de747](https://cloud.githubusercontent.com/assets/585534/8444038/842440fc-1f5a-11e5-80e6-4d424a76d8a9.png)

**Comment by DiabSoule** [comment]
I get these warning on all of the youtube filters none of the others. Nothing from here. I just wanted to bring it to attention is all. Click at own risk.

**Comment by gorhill** [comment]
I tried all the links with the WorldIP add-on and I get no warnings.

**Comment by DiabSoule** [comment]
If I hadn't found the multiple dictionary attacks I wouldn't have thought much of it. Just letting everybody know to be aware of possibility is all. Thanks

**Comment by gorhill** [comment]
> A bit rude to put it nicely.

I could not make sense of what you were talking about, I finally figured it with internet searching "WorldIP".

**Comment by DiabSoule** [comment]
no problem lol. i was typing and taking screenhots them looked up to see closed

**Comment by anewuser** [comment]
@gorhill You should just keep ignoring these people until they post all reasonable details. Don't waste your time and patience on them.

**Comment by LazerPanther** [comment]
:+1: @anewuser

**Comment by SARG04** [comment]
As far as I can tell, this has nothing to do with uBlock.
It is slimly the way how easylist-downloads.adblockplus.org 	handle its load balancing.

Depending on where and when you ask for a IP for easylist-downloads.adblockplus.org you get a different IP. In contrast to bigger CDN they don't use anycast to keep the same IP, even if the server are in different locations in the world. 

And that is exactly what WorldIP is telling you. The DNS request from your system got a different IP for the domain name, then the add-on got via a different DNS server.
If you have more questions you should ask the people behind WorldIP what there massage exactly means.
