### ISSUE TITLE
uBlock is not blocking ads in about:newtab images

### ISSUE THREAD

**Issue by johnp** [gorhill/uBlock#426]
STR:
1. Open about:newtab
2. See ads in the page thumbnails
I didn't see this on my laptop, because of my host-file blocking, but my fedora box shows ads in nearly all of the thumbnails shown (These are in-page ads, captured in the images, and not the "suggested tiles" feature).

I'm also using Add-Ons like NoScript, RequestPolicyContinued and others. Also experimental tracking protection is enabled in Firefox. But somehow it seems that none of them is able to block those ads :(

edit: Here is the Mozilla Bug regarding the issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=904341

**Comment by ElectricRogue** [comment]
I think this is due to some adware plugin.
.

**Comment by johnp** [comment]
There's no adware whatsoever installed on this pc. This is a freshly installed fedora workstation without any plugins. The captured images for the newtab-page are created from background fetches that do not get properly blocked by uBlock.

**Comment by TeddStriker** [comment]
There is no adware, Mozilla decided to put ads in the newtab page now. You can go around it by disabling the new tab completely. If my memory serves, gorhill mentioned a filter for uBlock (or uMatrix) that filtered out the tracking aspect of the ads, don't know if it blocks them completely though. Look around the issue pages for something of the sort.

**Comment by gorhill** [comment]
I don't have any ad yet in my own  `newtab` page. What version of Firefox is required? Is Linux excluded from those ads? In any case, first thing I would do is use the logger to see if I could identify the network requests used to fetch these ads. If the requests can be seen in the logger, uBlock can block them.

**Comment by johnp** [comment]
@TeddStriker :
As I've said in my first comment: These are not the "suggested tiles"  provided by Mozilla! Please read before posting. Also one does not have to disable the new tab page to get rid of them. Just toggle the "Include suggested sites" check-box and they're gone!

@gorhill :
The inspector doesn't show any request, even during a hard refresh.
The code explicitly states that plugins are disabled for those background loads:
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/thumbnails/BackgroundPageThumbs.jsm#34

**Comment by johnp** [comment]
![newtab-ads](https://cloud.githubusercontent.com/assets/314391/8456366/38e837fe-200b-11e5-8130-4987868b21bb.png)

**Comment by gorhill** [comment]
I see, you means the pages used to generate the thumbnails have ads in them.

You point out:

> The code explicitly states that plugins are disabled for those background loads

Then this answers it all: uBlock can't do anything either if it's not given an opportunity by the browser to do its job.

**Comment by johnp** [comment]
I just had a look at the code, and there's an option to disable thumbnails altogether:
browser.pagethumbnails.capturing_disabled = false
Otoh, I'm not sure if 'plugins' explicitly includes Add-Ons...

**Comment by johnp** [comment]
I did some digging and found the Mozilla bug about that:
https://bugzilla.mozilla.org/show_bug.cgi?id=904341

Unfortunately, no progress in one year :(
I assume this is happening, because they're creating a new custom remote thumbnail browser in the background:
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/thumbnails/BackgroundPageThumbs.jsm#152

**Comment by harshanvn** [comment]
@johnp. Nice find!

Good that, I browse in InPrivate mode. So, no tracking for me.

How ever I assume it should be advisable to disable thumbnail generation setting for all. Perhaps an entry in ublock wiki somewhere.

And I assume this is also not captured in dev tools. (Am not in front of a PC, so cannot check my self)

**Comment by gorhill** [comment]
> I did some digging and found the Mozilla bug about this issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=904341

Can you add this to your OP? So that other people will be able to see the matching Firefox issue without having to go through the whole thread.
