### ISSUE TITLE
get notified of updates

### ISSUE THREAD

**Issue by qwertygc** [gorhill/uBlock#428]
Hello !
The AMO's Ublock version is little different of Github version (previous release). it's possible to get notified if a new version is outing on github? It's more easy for newbies.

Thinks and congrulation for the work!

**Comment by SvenPM** [comment]
Subscribe to this feed
https://github.com/gorhill/uBlock/releases.atom

**Comment by gorhill** [comment]
Here is a feed for the _Releases_ page: <https://github.com/gorhill/uBlock/releases.atom>.

I do not plan to add notification as part of uBlock, I prefer to keep the extension as "silent" as can be with regard to its own network traffic. The only network requests are for purpose of updating important assets.
