### ISSUE TITLE
this release is totaly junk

### ISSUE THREAD

**Issue by tntc4** [gorhill/uBlock#43]
this release is not working at all.
![screenshot_1](https://cloud.githubusercontent.com/assets/3246834/7107690/ef3c05e6-e175-11e4-91fb-0c9b647ba83f.png)

**Comment by Havokdan** [comment]
Did you notice that has two ublock icons there? You realize you need to do a backup of the previous version and then import into this version? So think about it. I'm using Firefox 37.0.1 and functioning normally with me.
