### ISSUE TITLE
Override CSS style

### ISSUE THREAD

**Issue by wernight** [gorhill/uBlock#430]
Sites that have a sidebar for ads, sometimes it's not enough to just set `display: none` on the sidebar to get back the space taken by it. For example it may have `body { padding-right: 300px; }`. Of course another extension could handle styling for a given website, but it should really go hand in hand with the blocking of ads (enabled and disabled together).

Is there a way to write custom CSS that should be injected for given websites?

**Comment by SW1FT** [comment]
Stylish?

**Comment by gorhill** [comment]
> Is there a way to write custom CSS that should be injected for given websites?

Not with uBlock. What you ask is really best done with Stylish.

**Comment by anewuser** [comment]
You don't need to use any extension to do that on Firefox: http://superuser.com/a/319322/33758

**Comment by wernight** [comment]
I do know about other extensions, but it should be part of the ad-block as it's not to re-style the page, but really just to hide ads. Enabling back ads for example, should not apply those styles.

Why not have it part of uBlock?

**Comment by SW1FT** [comment]
You can enable ads back, if you know what you're doing, by disabling certain filters (cosmetic and/or network based).

**Comment by wernight** [comment]
My point is that users may want to enable/disable ads and uBlock should completely hide them when it can, not just leave a blank rectangle. In some cases this would be possible only by having some CSS filter or CSS override (when uBlock is enabled for that particular site).

**Comment by SW1FT** [comment]
You would have to make that yourself as it would be difficult to go through every single website with ads and do that. Thats why you should either use Stylish or userContent.css. Integrating Stylish or something similar to uBlock would make it heavier and not many people would want that to be honest.
