### ISSUE TITLE
uBlock does not work in SeaMonkey properly

### ISSUE THREAD

**Issue by simaelena** [gorhill/uBlock#431]
Upon installation uBlock does not show any icons in any toolbars in SeaMonkey, therefore can not manage it by this way. After restarting browser 3rd parties' rules disappeared and not implemented.

**Comment by gorhill** [comment]
Unable to reproduce on SeaMonkey 2.33.1, as per details provided.

**Comment by simaelena** [comment]
Thanks, but ... 
On SeaMonkey 2.33.1 do disable / enable extension and it works for current session, After restart filter list is empty again. Icon do not appear at all (see screenshot attached).
![2015-07-02 16-36-29](https://cloud.githubusercontent.com/assets/13150169/8478368/a0e219b4-20d9-11e5-92fb-a463dfc04824.png)

**Comment by gorhill** [comment]
I mark issue as invalid when they have too little details in them, which is the case here.

**Comment by jumpycats** [comment]
The missing 3rd-party filters on restart bit sounds awfully like https://github.com/gorhill/uBlock/issues/399, which was fixed in the 0.9.9.3 preview releases.

**Comment by gorhill** [comment]
> sounds awfully like #399

I am going to assume it's a duplicate of #399, though I can't tell for sure since no uBlock version info was provided.
