### ISSUE TITLE
Toggling fonts?

### ISSUE THREAD

**Issue by gerroon** [gorhill/uBlock#432]
Hi

Can you please add some more mouse info to the dropdown menu about these ttoggles? For example when I toggle the fonts(big red cross on A), am I blocking the fonts or am I just disabling the blocking? A bit confusing.

thanks

**Comment by hotdogman** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-site-based-switches

**Comment by 5t3f4n** [comment]
The tooltips could be made dynamic so that when remote fonts are enabled it says `Block remote fonts for this site` and vice versa. This could be applied to the other buttons as well. It would be way more intuitive.

**Comment by gorhill** [comment]
Yes, this was suggested on Crowdin more than a month ago, I agreed to it.

**Comment by dungsaga** [comment]
If there are 2 tooltips for 2 statuses (on/off) of a toggle, then should the tooltip popup show the current status, or the next status which will come into effect (after clicking on the toggle)?
For example: when the toggle for remote font is "on", should the tooltip popup say "Remote fonts are blocked" or "Click to allow remote fonts"?
We can show both of them, but it seems too verbose then.

**Comment by dungsaga** [comment]
I think if the icon is more meaningful, then we don't need 2 tooltips for 2 statuses (on/off).
IMHO, we should show the overlay (:x: or :no_entry_sign:) when status is "on", but users may be confused if we change this behavior now.
