### ISSUE TITLE
Logger opens in new window

### ISSUE THREAD

**Issue by hotdogman** [gorhill/uBlock#433]
I know that the logger opening in its own window is [intentional](https://github.com/gorhill/uBlock/commit/ad827576ce5ae2c1b4faadeff7bde62da1a1e467) (so this isn't a bug, and should be closed, I suppose), but would it be possible to have an option or a preference to have it open in a tab? Personally, I preferred it when the logger opened in its own tab, and setting browser.link.open_newwindow.restriction to 0 in about:config had no effect on it.
Sorry for bothering.

uBlock 0.9.9.3
Firefox 39.0
Windows 8.1

**Comment by gorhill** [comment]
Given that it's a dev version, I reserve the right to change things around. So: The logger will open as before. However, clicking the logger icon with the <kbd>Shift</kbd> key pressed will open the logger as a popup window. In next dev build.

**Comment by hotdogman** [comment]
Thank you, I appreciate it.
