### ISSUE TITLE
uBlock not blocking when opening tabs from previous session

### ISSUE THREAD

**Issue by Smultie** [gorhill/uBlock#434]
Since a couple of updates (I'm now running 0.9.9.3 dev) the addon is no longer blocking ads on the 2 pages that auto-load on my system. After a refresh of those pages, ads are blocked correctly.

**Comment by Krak-n** [comment]
Please read this section of: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include)

**Comment by gorhill** [comment]
Making as invalid until clear, repro steps with specific details are provided.

**Comment by gorhill** [comment]
Closing due to near total lack of details, and abandoned by OP.
