### ISSUE TITLE
Readme warns about a fixed chromium memory leak

### ISSUE THREAD

**Issue by nivintw** [gorhill/uBlock#437]
Unless I am seriously misunderstanding the conversation over on https://code.google.com/p/chromium/issues/detail?id=441500 the memory leak you warn about in the readme has been fixed and merged on March 10, 2015. Just wanted to send you a heads-up.

**Comment by gorhill** [comment]
Fixed in 7161c21b14ffb1e6ccedc90d28b6f78b6cf6335c.
