### ISSUE TITLE
Green on AMO

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#439]
Now Ublock0 is not an "experimental" anymore it is an ordinary addon and its version is 0.9.9.2 on AMO for Firefox of course. Good news for a great job, keep on @gorhill !

**Comment by gorhill** [comment]
Nice. I thought this was the usual preliminary review while waiting for the full review, but now looking more carefully at my inbox I realize it says "Fully Reviewed" -- I had missed this.
