### ISSUE TITLE
accepting donations?

### ISSUE THREAD

**Issue by Skrell** [gorhill/uBlock#440]
I realize this isn't a software bug, but i didn't know where else to post.  I wanted to encourage Gorhill to start accepting paypal donations as many of us LOVE his addon and want to show our support!  Especially those of us using Palemoon!! :)

**Comment by gorhill** [comment]
Thanks for the thought but the stated (and nono-stated) reasons I don't want to deal with donations are still valid.

@AlexVallat is responsible by the way for making uBlock/uBlock Origin fully functional on Palemoon.

**Comment by Skrell** [comment]
My apologies!  I did not realize you had already made a statement regarding donations.  :-/

**Comment by anewuser** [comment]
@Skrell the official position is that you should redirect your donations to the list maintainers or some other open source project: https://github.com/gorhill/uBlock/blob/master/README.md#about
