### ISSUE TITLE
Add multiple sites to Badware

### ISSUE THREAD

**Issue by bgiesing** [gorhill/uBlock#446]
# Sites
- CNET/Download.com
- Tucows
- FileHippo
- Softpedia
- SnapFiles
- FreewareFiles
- NoNags
- MajorGeeks

Article:  [How-To-Geek](http://www.howtogeek.com/207692/yes-every-freeware-download-site-is-serving-crapware-heres-the-proof/)

**Comment by gorhill** [comment]
I will use the information [here](https://github.com/gorhill/uBlock/wiki/Badware-risks). Once an entry is well-sourced -- ideally more than just one source, but many, and over time, I will add them to `badware.txt`.

**Comment by gorhill** [comment]
I added `download.com`/`download.cnet.com` after going into a good cites quest. Whatever other candidate will be added when there are enough good sites to backup the _badware risks_ qualifier.

**Comment by anonsubmitter** [comment]
With this new filter rule you can't access articles on the website. The new filter rule offers no additional protection as far as I can tell since CNET Download.com's bundleware was already blocked via the filter rule for dw.cbsi.com

**Comment by gorhill** [comment]
> CNET Download.com's bundleware was already blocked via the filter rule for dw.cbsi.com

I did not know this was blocking the download button. As far as I can tell, `dw.cbsi.com` is more for tracking purpose (found in EasyPrivacy). All the sources I are using the site's own domain name, `download.com`, so I rather stick with this, as this will result in `download.cnet.com` = _Badware risks_, which different information than `dw.cbsi.com` = _EasyPrivacy_. Whoever disagree with the block can simply permanently disable it.
