### ISSUE TITLE
Since last update (0.9.9.3), I can no longer use hotlinks in gmail. I am using palemoon 25.5.0, 

### ISSUE THREAD

**Issue by patchel** [gorhill/uBlock#447]

**Comment by Ge-Bra** [comment]
+1 firefox 41.0a2

**Comment by gorhill** [comment]
What do you call "hotlinks"?

**Comment by Ge-Bra** [comment]
eg. "View it on github"
Other add-ons may be involved, I will investigate further.

**Comment by gorhill** [comment]
Well I tried links embedded in messages and it worked all fine. Tested with FF25, FF 39, Nightly 41.

**Comment by gorhill** [comment]
As usual, marked as invalid due to lack of provided details.

**Comment by patchel** [comment]
What details do you need? These are the other extensions I use: Add to Amazon Wish List Button    1.10.1, auto-plugin-checker    0.6.4.2.1, BetterPrivacy    1.68.1, F.B. Purity - Cleans Up Facebook    13.2.3, Foxamp    0.4.2, Googlebar Lite    5.0.6.1, IE Tab 2 (FF 3.6+)    5.12.12.1, IMDB Search    1.0.1, LastPass    3.1.95, Nightly Tester Tools    3.7.1, NoScript    2.6.9.29, Pin It Button    1.35, Pinterest Pin Button    38.2, Session Manager    0.8.1.6.1, Tab Mix Plus    0.4.1.8, TrafficLight    0.2.23.1, uBlock Origin    0.9.9.3, WOT  20150421

Ublock Origin is the only one that updated yesterday. I had no problems before then.

**Comment by gorhill** [comment]
> What details do you need?

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include

**Comment by Ge-Bra** [comment]
The culprit is add-on WOT, see
https://addons.mozilla.org/en-us/firefox/addon/wot-safe-browsing-tool/
Should close this.

**Comment by gorhill** [comment]
@Ge-Bra Thanks for investigating.
