### ISSUE TITLE
Request minor change to "Quick guide: popup user interface"

### ISSUE THREAD

**Issue by vasa1** [gorhill/uBlock#448]
Under https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-number-of-requests-blocked there is this:  
> Click the eye icon to open the network request logger in a separate tab. This allows you to inspect real-time network traffic within the browser.

I think **"eye icon"** isn't correct but I don't know what name would be more appropriate.

**Comment by gorhill** [comment]
Thanks for spotting this. I used _list_, as it's what the Fontawesome name is for this icon.
