### ISSUE TITLE
One more filter for you

### ISSUE THREAD

**Issue by DarkeningNightofSofia** [gorhill/uBlock#449]
https://easylist-downloads.adblockplus.org/adwarefilters.txt

**Comment by anewuser** [comment]
Use the search bar and read the [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) file before posting.

Close this because it's a duplicate of #413.

**Comment by gorhill** [comment]
Should be added there: https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web.
