### ISSUE TITLE
Use case: does an advanced user still need tooltips?

### ISSUE THREAD

**Issue by Hunter-Github** [gorhill/uBlock#451]
First-time uBlock<sub>o</sub> user here (stable v0.9.9.3). Enabling "advanced" settings is orthogonal to having all the interface buttons learned by rote. Think it should be easy to switch tooltips on and off without disabling dynamic filtering. And yes, this would mean another checkbox in the dashboard, and another config setting.

Pro: 
 * faster learning without consulting the wiki all the time;
 * ability to turn on headlights without shutting down wipers.

Con: some may view this featreq as "feature bloat".

BTW, thanks for the addons.

**Comment by anewuser** [comment]
I agree that this should be a separate option. It's not bloat because the code already exists. It just have to be moved to another new checkbox.

**Comment by Mikey1993** [comment]
I fully support having an option to show or hide the tooltips.
This has all the benefits of not having to memorize each and every option there are, and I don't find the tooltips bloating the interface.

**Comment by SoniEx2** [comment]
:+1:

**Comment by CarlosCuevas** [comment]
I concur

**Comment by gorhill** [comment]
Fixed with d7523aad6ded86a189e2f676b9238bb93c6a35fd.

**Comment by flyingzebras** [comment]
@gorhill I too fully support having an option to show or hide the tooltips, in both user modes.
