### ISSUE TITLE
Popup identified as "doc" request when opened by iframe

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#452]
I've set these dynamic rules to block popups from [this page](http://geektv.me/watch/14861):

> no-popups: geektv.me true
> no-popups: youwatch.org true

The popup is blocked if I open the iframe URL directly and click on the player: http://youwatch.org/embed-xlmfhm97etcg-850x450.html

![popup blocked](https://cloud.githubusercontent.com/assets/6733770/8534102/abcd76c8-240f-11e5-9be6-6a467214015d.png)

However, if I click on the same player on the Geektv page, the ad popup isn't blocked because it's seen as a legit new document request: http://geektv.me/watch/14861

![popup identified as doc](https://cloud.githubusercontent.com/assets/6733770/8534120/c1e860bc-240f-11e5-8831-edea2c620c7c.png)

These two sites both have other ads, which I've blocked with other rules and filters. This issue is only about popups called by this function:

    function lads() {
        window.open('http://ds1.vids.ma/KeclfbD2', 'velro', 'location=no,fullscreen=yes'); 
    }

The popup URL may be different when you test it because they keep changing their ad hosts.

Firefox 40 (Beta) for Windows
uBlock Origin 0.9.9.3

**Comment by gorhill** [comment]
I can reproduce.

**Comment by anewuser** [comment]
Thank you!
