### ISSUE TITLE
logger-ui bug aero transparency

### ISSUE THREAD

**Issue by MurkBRA** [gorhill/uBlock#454]
Work all fine but if I open this ui to help me create new filters I get this bug.
I'm on Firefox 40 beta 1 x64
uBlock Origin v0.9.9.3
Win7 x64
edit:
only if I click on dropbox botton

![6aca60e28c](https://cloud.githubusercontent.com/assets/12011370/8537129/c15529ca-2430-11e5-99ac-99a808545973.png)
![1e7c3ce1c8](https://cloud.githubusercontent.com/assets/12011370/8537134/cadbaafa-2430-11e5-9a83-ac4a947a513a.png)

**Comment by gorhill** [comment]
I don't understand the report. What is "aero transparency"?

**Comment by CrisBRM** [comment]
A windows theme (Vista & 7) known for its frosted glass like window borders.

**Comment by gorhill** [comment]
The only thing uBlock does when you open the logger is to call Firefox API's [`loadOneTab`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Method/loadOneTab). If your theme is messed up as a result, the bug is more likely on Firefox's side I would think.

**Comment by MurkBRA** [comment]
The same bug does not happen in chrisaljoudi/uBlock

**Comment by MurkBRA** [comment]
![8426a09f56](https://cloud.githubusercontent.com/assets/12011370/8558982/b9e06638-24de-11e5-8da2-ad086ec25870.png)

**Comment by MurkBRA** [comment]
The bug is back.
I can confirm the regress on v1.0.0.1
