### ISSUE TITLE
Will the uBlock in Chrome update automatically? 

### ISSUE THREAD

**Issue by enerai** [gorhill/uBlock#456]
I have found the latest 0.9.9.3 in github, but the version in Chrome is still 0.9.9.2. How can I obtain the latest version in Chrome? Will it update automatically?

Thanks!

**Comment by anewuser** [comment]
Install it from this page and forget about it: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

It's always going to be updated automatically. The Github links are meant to be used by advanced users and testers only.

**Comment by enerai** [comment]
I just hope that the new stable version 0.9.9.3 could be uploaded to Chrome Store sooner.

**Comment by anewuser** [comment]
The "Close issue" button is next to the "Comment" button. Please press it. If you want to keep discussing uBlock with other users, go to the subreddit. The link is listed here: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by enerai** [comment]
Thanks for your reminder.

**Comment by CrisBRM** [comment]
They review more popular extensions a bit more carefully nowadays, so Gorhill can't push updates as often, or he'll risk potentially pushing a buggy build since they take longer to be approved.

**Comment by enerai** [comment]
Thanks for your kind reply!
