### ISSUE TITLE
3rd-party filters settings page not working properly on Firefox Ultimate 64 bits

### ISSUE THREAD

**Issue by tailHey** [gorhill/uBlock#46]
Hello everyone. Here are the steps to reproduce this issue:

-Install Firefox Ultimate 64 bits (latest version, grab it here: http://sourceforge.net/projects/firefoxultimate/ )
-Install uBlock₀
-Go to the Settings
-Go to the 3rd-party filters tab
-Only three filtering lists appear (My filters, uBlock filters, uBlock filters - Privacy), settings can't be remembered. This bug make uBlock₀ much less useful. This issue is also affecting uBlock, except one difference: uBlock₀ displays the message box to enter custom URLs for filtering lists and the Parse button.
http://i.imgur.com/iGKQvZC.png

Thanks in advance, have a good day

**Comment by gorhill** [comment]
Closed as per <https://github.com/chrisaljoudi/uBlock/issues/1245#issuecomment-92509425>.
