### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by JeremyWW** [gorhill/uBlock#460]
I'm curious to know why you think it's any advantage to have local IP addresses hidden. If WebRTC was prevented from revealing my public IP I'd be more interested from a privacy point of view, but I'm highly dubious as to whether it matters a jot if someone knows my LAN side address.

**Comment by anewuser** [comment]
This repository is for bug reports only. To discuss this and other features, please use the Reddit community instead: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by gorhill** [comment]
<https://torrentfreak.com/huge-security-flaw-leaks-vpn-users-real-ip-addresses-150130/>:

> With a few lines of code websites can make requests to STUN servers and log users’ VPN IP-address **and the “hidden” home IP-address**, as well as local network addresses.

**Comment by JeremyWW** [comment]
I've signed up to reddit but not sure how to use it (never used it before). I'll try to comment there but the WebRTC feature actually doesn't work, any more than anyone else's efforts have done. I've used VPN's extensively and this issue has been a thorn in the side of VPN users for a long time, to the best of my knowledge unsolvable in Chrome. The option you've added blocks the local network address but crucially not the public IP whether it's VPN or ISP. Tested on Chrome 43.0.2357.132 m.

**Comment by gorhill** [comment]
I tested with a VPN and my ISP address was not seen.

**Comment by JeremyWW** [comment]
Tested again using Zenmate. All test sites reveal my ISP address.

**Comment by gorhill** [comment]
I would like to see what are other people findings.

I could not see my ISP IP address on my side when behind a VPN. Chromium 43/Linux Mint.

**Comment by JeremyWW** [comment]
Yes, that's because you run Linux. It does not work in Windows.

**Comment by gorhill** [comment]
<https://code.google.com/p/chromium/issues/detail?id=457492#c44>:

> It works with **full VPN**. Not with browser VPNs addons like ZenMate

**Comment by JeremyWW** [comment]
Ah. OK. Makes sense.
