### ISSUE TITLE
[GUI Improvement] Consider adding loading throbbers if loading takes more than X amount of time

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#461]
As the title says.

On my low end machine (Athlon X4 631 CPU + NVIDIA GeForce GT 520 GPU),
it takes some good 5 seconds to load it in the beginning (while the system, especially the HDD, under some load).

I would suggest adding a spinning throbber only if the loading takes more than X seconds (I think 1 second is OK for the throbber to show) while loading tabs in the dashboard (just like e10s on FF is doing when there is some work that blocks the renderer from showing up the page).

This would tell the user that everything is OK while he is waiting for the page to load.

My lucky guess is that most of the people who use uBlock Origin have some kind of lowish end system, this can be a great perceivable improvement for them for the "first time experience" with uBlock.

**Comment by TeddStriker** [comment]
Do you mean adding a throbber when you click the uBlock toolbar button, for the dropdon menu? Or do you meant the logger UI? In any case, I'm running Firefox 39 with uBlock0 on a 8 year old Dell, with a 800MHz Core 2 Duo, with integrated graphics and it runs just fine. Have you tried disabling/enabling hardware acceleration to see if that speeds things up? Sorry in advance if I misunderstood what you were trying to say.

**Comment by Mikey1993** [comment]
@TeddStriker I mean adding a throbber when doing any operation which changes on screen content, and especially I'm taking about going to the dashboard and clicking on the 3rd-party filters tab, which can take a hefty amount of time on a low end machine which is under some load (maybe your HDD is in a good defragmented state, have a lot of physical memory headroom and etc).

**Comment by gorhill** [comment]
There is no performance issue. What you may be experiencing is network delay when fetching `https://raw.githubusercontent.com/gorhill/uBlock/master/assets/checksums.txt`, which is what the _3rd-party filters_ does first, the first time you visit that tab.

**Comment by Mikey1993** [comment]
@gorhill This is quite puzzling, as on my high end PC, which is connected to the same router as the low end PC, I can see this behavior very rarely (and surely not 5 seconds as the low end machine).

In any case, it will be nice to have a throbber to indicate that the page is working on something..

**Comment by luxoflux** [comment]
As @gorhill said, it's only on the first visit of that pane. But I agree with the suggestion to reduce the appearance of delay — make the whole page slightly opaque before fully loading, with or without a loading indicator. Simply for a smoother UX.

**Comment by gorhill** [comment]
uBO no longer rely on fetching `https://raw.githubusercontent.com/gorhill/uBlock/master/assets/checksums.txt` when opening the _3rd-party_ filters pane since assets code was refactored.
