### ISSUE TITLE
[Firefox] Some requests are being blocked on a whitelisted site

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#463]
<h1>Steps to reproduce:</h1>

1) Enter: https://www.rdio.com/account/signin/
2) Whitelist the site using the big power button.
3) Reload the page.
4) Some request are shown as blocked on the statistics/advanced users panel (js-agent.newrelic.com & www.google.co.il requests).

It seems like there is some race condition going on with the page loading and uBlock being aware of the fact that the site is whitelisted.

As if loading the page **without a cache**, there is no js-agent.newrelic.com request going through (reported by the Network Monitor tool from the Firefox DevTools), and uBlock reports that it blocked it.
**But**, uBlock reported that it has blocked the request when it isn't the case after loading the page with a cached version of the site, where the js-agent.newrelic.com came from cache (again, confirmed using the Network Monitor tool).

Using uBlock Origin latest Dev build, default settings.
**Only** reproduceable on Firefox (reproduced on latest Nightly build, clean profile).

**Comment by gorhill** [comment]
I don't have an account with that site.

**Comment by gorhill** [comment]
I observe that the blocked requests are made in the context of a subdomain of `rlets.com`. The whitelisted site is `rdio.com`, a different context. Still, I would expect all the requests to not be blocked, as the master switch applies to all contexts on a page.

**Comment by harshanvn** [comment]
Another test case -

### STR
1. Open http://www.snapdeal.com/product/philips-qt4000-beard-trimmer/716782929
2. Open Network Request log 
3. Whitelist above site, by clicking Blue button on popUp UI and refresh the page
4. You will still see the requests blocked in logger.
5. I have disabled noop'ed all my dynamic filtering rules for this test case (thru mini Matrix UI). (I have some dynamic URL filtering rules active, though they are not related to this site)

Note: This issue i have observed some 2 weeks ago, but was lazy/busy to report it.

#### Config
Win 7 32 bit - FF v39 - uBlock v0.9.9.4 (some dev version)

Please let me know if you need more details. Below screenshot showing the problem -

![ublock request incorrect block](https://cloud.githubusercontent.com/assets/779630/8595675/1bae3770-2618-11e5-8dc0-fa857474bcc2.png)

**Comment by gorhill** [comment]
It's Firefox loading an `iframe` as if it was a root document -- one more FF API quirk to deal with... Works all fine with Chromium.

**Comment by Mikey1993** [comment]
@gorhill Does that mean it's better to open a bug on bugzilla.mozilla.org for mozilla to look at this with some more technical background people on the API?

**Comment by Jan02** [comment]
I found this similar issue browsing soundcloud.com I would add eventlogger.soundcloud.com to white-list and the domain would still get blocked by the "EasyPrivacy‎ (forums.lanik.us)" list.

**Comment by gorhill** [comment]
I tried to reproduce according to steps [here](https://github.com/gorhill/uBlock/issues/463#issuecomment-119952932), and it worked all fine. Possibly fixed when I refactored the tab context code. Will re-open if someone provides new detailed steps to reproduce.
