### ISSUE TITLE
googlevideo is being blocked for no reason

### ISSUE THREAD

**Issue by harmonymeow** [gorhill/uBlock#465]
I don't know what happened but googlevideo is blocked. No youtube video can be loaded. Is it only me?

![blocked](https://cloud.githubusercontent.com/assets/3032746/8590751/4582d00a-25d8-11e5-98eb-6f5a3ea76387.png)

**Comment by harmonymeow** [comment]
Uninstalling and reinstalling seems to have fixed the issue somehow. Please disregard. Thanks.

**Comment by gorhill** [comment]
Still, I would like to understand what happened -- when something is blocked, the reason for the block is supposed to always appear in the logger -- and it's blank in your pic.
