### ISSUE TITLE
"My filters" don't work with latest Chromium

### ISSUE THREAD

**Issue by octoploid** [gorhill/uBlock#469]
With Chromium Version 45.0.2453.0 (64-bit) on Linux all filters from the "My Filters" list are silently ignored.
Might be related to this bug: https://code.google.com/p/chromium/issues/detail?id=501580

**Comment by octoploid** [comment]
Sometimes I get the following Stack Trace:
Context: Unknown
js/assets.js:565 (onRepoFileError)
js/assets.js:312 (onErrorReceived)

**Comment by gorhill** [comment]
> js/assets.js:565 (onRepoFileError)

The GitHub repo could not be reach. It's ok, uBlock recovers from this by using the local version of a filter list.

> "My Filters" list are silently ignored.

Can you give me a screenshot of your _3rd-party filters"_ pane?

**Comment by octoploid** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/327746/8598846/6f4a0374-265d-11e5-89a2-71360ebc1ef1.png)

**Comment by gorhill** [comment]
> Can you give me a screenshot of your 3rd-party filters" pane?

**Comment by octoploid** [comment]
![3rd-party filters pane](https://cloud.githubusercontent.com/assets/327746/8598928/e406aa64-265d-11e5-8e5c-28d5f83e06c4.png)

**Comment by gorhill** [comment]
All looks fine so far. What does not work **specifically**? Follow <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

**Comment by octoploid** [comment]
Well, all the filters are ignored.
To reproduce simply generate a filter. It will have no effect whatever.

**Comment by octoploid** [comment]
Everything works fine with 45.0.2434.0 (64-bit).

("Collapse placeholder of blocked elements" from uMatrix also stopped working
with 45.0.2453.0.)

**Comment by gorhill** [comment]
Look for error messages in the dev console of the web page where it does not work: filter output of console using `contentscript`. See if there are errors related to `contentscript-start.js`, `contentscript-end.js`. From your description, there should be, it appears the content scripts are failing.

**Comment by octoploid** [comment]
There's nothing of interest in the dev console.

The latest dev-channel release of Chrome already has the bug:
 https://www.chromium.org/getting-involved/dev-channel

**Comment by gorhill** [comment]
I tried using the first cosmetic filter in your list, `www.niederschlagsradar.de##DIV[id="box"]`, and the corresponding DOM element on `http://www.niederschlagsradar.de/` was correctly hidden.

You will have to provide me with one case where the bug manifest itself. Please provide:

- The custom filter which reportedly does not work
- A URL where the filter is expected to work

**Comment by octoploid** [comment]
As a simple example take this page itself.

If I add:
github.com##.container > .site-footer

The footer is removed with Chromium 45.0.2434.0, but not with the latest dev-channel release
of Chrome.

**Comment by octoploid** [comment]
Just downloaded the latest dev-channel release 
and the bug is fixed (Version 45.0.2454.6)
