### ISSUE TITLE
[Feature] Youtube ads

### ISSUE THREAD

**Issue by ghandhikus** [gorhill/uBlock#47]
Hey,
I used original Adblock for a long time before switching to uBlock. I really love the performance of it, but I miss the youtube feature from it.

Youtube feature in original Adblock allowed users to disable ad blocking for specific channels. On top of that I would love to see blocking of full-video ads which can last for 30 seconds if not skipped.

Cheers!

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#a-youtube-channel>
