### ISSUE TITLE
Firefox option issue

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#470]
1) Open Firefox
2) Click uBlock icon, then on top when version to show Dashboard
3) Ctrl+N for New Window
4) Click uBlock icon, then on top when version to show Dashboard
On step 4, nothing happens

**Comment by TeddStriker** [comment]
Can confirm on Firefox 39.0, Windows 7 Ultimate, with: 
* Clean profile / default uBlock origin (Stable and Dev). 

* And my usual profile with non-default uBlock origin (With custom filters and such).

The Dashboard doesn't open in a new window if its already open in another.
