### ISSUE TITLE
How I can whitelist Spotify fonts?

### ISSUE THREAD

**Issue by DarkeningNightofSofia** [gorhill/uBlock#471]
Filter "https://www.fanboy.co.nz/fanboy-antifonts.txt" will break Spotify fonts on "https://play.spotify.com".

**Comment by CrisBRM** [comment]
Create a custom rule:

@@||glue-static.s3-external-3.amazonaws.com/fonts$font,domain=spotify.com

**Comment by gorhill** [comment]
Report issue to maintainers of the filter list.

**Comment by anewuser** [comment]
@DarkeningNightofSofia you can report it to **fanboy** here: https://forums.lanik.us/viewforum.php?f=64

**Comment by DarkeningNightofSofia** [comment]
Where do I add that?

**Comment by CrisBRM** [comment]
'My filters'
