### ISSUE TITLE
Not blocking twitch.tv pre-roll video ads

### ISSUE THREAD

**Issue by vasive** [gorhill/uBlock#472]
Recently within the past few days I've been seeing pre-roll ads on twitch.tv

Is this happening for anyone else?

**Comment by gorhill** [comment]
Closed due to invalid as per <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>. I will re-open if issue is properly filled, and if not related to a 3rd-party filter list issue.

**Comment by anewuser** [comment]
@vasive If you use the default lists/EasyList, report it to them here: https://forums.lanik.us/viewforum.php?f=62
