### ISSUE TITLE
Icon (button) disappears from toolbar 

### ISSUE THREAD

**Issue by ackern** [gorhill/uBlock#473]
The icon (button) disappears from toolbar when you close FF and then re-open it, so you have to go into Toolbars >Customize and add it again.  However it's not absolutely every time you close FF, more like 80% of the time. Once in a while, you open FF and the button is still there.

**Comment by CrisBRM** [comment]
Has literally never happened to me. FF version? Custom userstyle/chroma?

**Comment by gorhill** [comment]
Marking as invalid until details as per <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md> are provided.

If this kind of poor report continue, I will start to issue temporary user block.

**Comment by ackern** [comment]
I haven't done anything involving custom userstyle or chroma. I've never seen those words in connection with FF extensions.

v0.9.9.3

ff 28

Win 7 pro 64 bit

Advertising Cookie Opt-out	1.5	true	optout@google.com
Dict.cc Translation	3.5.1-signed	true	searchdictcc@roughael
DownThemAll!	2.0.18.1-signed	true	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
Flashblock	1.5.18.1-signed	true	{3d7eb24f-2740-49df-8937-200b1cc08f8a}
FlashGot	1.5.6.12.1-signed	true	{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}
Ghostery	5.4.5.1-signed	true	firefox@ghostery.com
Google Analytics Opt-out Browser Add-on	0.9.6	true	{6d96bb5e-1175-4ebf-8ab5-5f56f1c79f65}
Greasemonkey	1.15.1-signed	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
LEO Dictionaries	2.0.0.1-signed	true	contextMenuExtension@leo.org
Lucifox	0.9.12.1-signed	true	Lucifox@lucidor.org
Mozilla Archive Format	3.1.0	true	{7f57cf46-4467-4c2d-adfa-0cba7c507e54}
NoScript	2.6.9.22	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Open Bookmarks in New Tab	0.1.2012122901.1-signed	true	openbookmarkintab@piro.sakura.ne.jp
Pinboard Extension	1.2.1-signed	true	pinboardff@pinboard.in
Print pages to PDF	0.1.9.3	true	printPages2Pdf@reinhold.ripper
ProfileSwitcher	1.6.2	true	{fa8476cf-a98c-4e08-99b4-65a69cb4b7d4}
Quick Translator	1.0	true	{5C655500-E712-41e7-9349-CE462F844B19}
Redirect Cleaner	2.4.0	true	redirectcleaner@example.net
Re-Pagination	2015.01.11	true	{6072cb90-a0bd-11da-a746-0800200c9a66}
RightToClick	2.9.5	true	{cd617375-6743-4ee8-bac4-fbf10f35729e}
Self-Destructing Cookies	0.4.7	true	jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack
Session Manager	0.8.1.6	true	{1280606b-2510-4fe0-97ef-9b5a22eafe30}
Show Parent Folder	2.1.1-signed	true	showParentFolder@alice
Social Fixer	11.2	true	socialfixer@mattkruse.com
Status-4-Evar	2014.07.06.05	true	status4evar@caligonstudios.com
translator	2.0.3.1	true	translator@dontfollowme.net
UAControl	0.1.3.1	true	uacontrol@qz.tsugumi.org
uBlock Origin	0.9.9.3	true	uBlock0@raymondhill.net
Video Myxa	1.9.91	true	{0C07EECD-53B6-4748-BB2B-4395BF51DD8B}
YouTube Center Developer Build	526	true	jid1-cwbvBTE216jjpg@jetpack
YouTube Video and Audio Downloader	0.3.9.1.1-signed	true	feca4b87-3be4-43da-a1b1-137c24220968@jetpack
anonymoX	2.4.7	false	client@anonymox.net
EPUBReader	1.5.0.6	false	{5384767E-00D9-40E9-B72F-9CC39D655D6F}
Evernote Web Clipper	6.0.15	false	{E0B8C461-F8FB-49b4-8373-FE32E9252800}
facepaste	2.8	false	facepaste.firefox.addon@azabani.com
Form History Control	1.4.0.3	false	formhistory@yahoo.com
HTTPS-Everywhere	4.0.2	false	https-everywhere@eff.org
Screengrab (fix version)	0.98.06c	false	{02450914-cdd9-410f-b1da-db004e18c671}

Problem does not occur on fresh never-used profile with no extensions.

**Comment by gorhill** [comment]
> ff 28

That was an important piece of information. I won't be able to test this before end of week.

**Comment by CrisBRM** [comment]
On a completely unrelated note, you have LOTS of overlapping addons.
Stuff you should probably remove: noscript (activate uBlock's dynamic filtering), YouTube Video and Audio Downloader (youtube center does that and you  have it installed), RightToClick (duplicates browser functionality, set dom.event.contextmenu.enabled to false in about config), Google Analytics Opt-out Browser Add-on (unnecessary thanks to uBlock), Ghostery (unnecessary thanks to uBlock) and Advertising Cookie Opt-out (unnecessary thanks to uBlock).

**Comment by onestepbeyond** [comment]
An additional idea: is `extensions.ublock0.forceLegacyToolbarButton` set to `true` in `about:config` ?
If no, right-click on this item and **invert**, and take some time to see if it helps.

**Comment by ackern** [comment]
>An additional idea: is extensions.ublock0.forceLegacyToolbarButton set to true in about:config ?
If no, right-click on this item and invert, and take some time to see if it helps.

You mean toggle, right?

**Comment by onestepbeyond** [comment]
Yes, Toggle (*Inverser* in french ;-)

**Comment by ackern** [comment]
Thank you. It would be great to weed out duplicates. Some I can, some I can't and some are maybes but anyway it's good to know.

>noscript (activate uBlock's dynamic filtering)

Could be nice but I'd estimate the learning time at 20 hours minimum. I just now spent 30 minutes just figuring out what dynamic filtering is in the first place. There's a huge heap of things to learn - noop, frames, scripts, 3rd-party to name just a few.  I know I *could* teach myself but I don't have the time. Even switching it on isn't an option now because I need tool tips. I haven't the faintest idea what "eye dropper" means. Triangle with exclamation point? Two pieces of paper?  Little jumble of shapes that looks like an eye with a triangle in front of it?

>YouTube Video and Audio Downloader (youtube center does that and you have it installed)

I like YTVAD because it tells you the size of each download choice

> RightToClick (duplicates browser functionality, set dom.event.contextmenu.enabled to false in about config)

I'll try this but I doubt it allows you to see all the images from a slide show together on one page so you can click and save whichever ones you want.

> Google Analytics Opt-out Browser Add-on (unnecessary thanks to uBlock), Ghostery (unnecessary thanks to uBlock) and Advertising Cookie Opt-out (unnecessary thanks to uBlock).

Definitely will delete these!

**Comment by TeddStriker** [comment]
@ackern 
>haven't the faintest idea what "eye dropper" means.

Its the DOM inspector if I'm not mistaken.  You basically need to learn which domain to block/allow via the options to the left. You won't even be using the little icons most of the time. Just remember that after editing a setting:

*  The eraser looking icon on the top left that appears reverts any temporary changes. 

* The lock icon will save them.

That's about it.

**Comment by hotdogman** [comment]
@onestepbeyond's solution should work.
FF28 is pre-australis (without customizeableUI)/legacy FF.

**Comment by anewuser** [comment]
>  I just now spent 30 minutes just figuring out what dynamic filtering is in the first place

@ackern  Please keep using NoScript and disable the advanced preferences of uBlock.

**Comment by jimgust** [comment]
I'm using FF 39 and the uBlock icon is missing from the toolbar as well.  I've tried to reinstall with no success.  This is the only add-on I'm using.

**Comment by TeddStriker** [comment]
@jimgust 

Do you have any UI modifications added? Via userchrome.css or the likes, some toolbars hidden perhaps? If you right click on the UI and then go to `customize`, can you find the icon there? A screenshot will definitely help.

**Comment by onestepbeyond** [comment]
@jimgust

Have you tried the proposal I made [above](https://github.com/gorhill/uBlock/issues/473#issuecomment-120148371)?

![screenshot01345](https://cloud.githubusercontent.com/assets/11029138/8634435/93b5f7f8-27f8-11e5-9f84-3f0491c49e8f.png)

**Comment by ackern** [comment]
@onestepbeyond 

> set  extensions.ublock0.forceLegacyToolbarButton to false

That on its own didn't work. But then I disabled Ghostery since someone said it's redundant with uBlock, and now it looks like the button is staying there. So if my reasoning's correct - assuming the button remains -  we don't know if the solution was the combination of disabling Ghostery *and* the forceLegacyToolbarButton change, or,  disabling Ghostery was sufficient and the change of setting was neutral.

At any rate, if it was up to me I would wait a day or two before concluding the disappearing-button issue is solved on my system since sometimes problems appear solved then come back.

**Comment by ackern** [comment]
@anewuser

>Please keep using NoScript and disable the advanced preferences of uBlock.

I already said I was doing that.

#mansplaining

**Comment by TeddStriker** [comment]
@ackern 
>So if my reasoning's correct - assuming the button remains - **we don't know if the solution was the combination of disabling Ghostery and the forceLegacyToolbarButton change**, or, **disabling Ghostery was sufficient and the change of setting was neutral.**

Seeing as how the `about:config` string didn't help on its own, you can try:

* Disabling the `about:config` string, with Ghostery disabled. If the icon is still there, disabling Ghostery did the trick

>If not:

* Use the `extensions.ublock0.forceLegacyToolbarButton` with Ghostery disabled, this would mean that a combination of both did the trick.

Hope that's clear.

**Comment by ackern** [comment]
Icon is still disappearing from navigation bar after each restart. All other icons remain where they are on toolbars. Ghostery is disabled and extensions.ublock0.forceLegacyToolbarButton is set to true.

I can post the rest of browser config if needed.

UO 1.0.0.1

FF 28, Win 7

Advertising Cookie Opt-out	1.5	TRUE
Dict.cc Translation	3.5.1-signed	TRUE
Disconnect	3.15.3.1-signed	TRUE
DownThemAll!	2.0.18.1-signed	TRUE
FlashGot	1.5.6.12.1-signed	TRUE
Google Analytics Opt-out Browser Add-on	0.9.6	TRUE
Greasemonkey	1.15.1-signed	TRUE
LEO Dictionaries	2.0.0.1-signed	TRUE
Lucifox	0.9.12.1-signed	TRUE
Menu Wizard	2.1	TRUE
Mozilla Archive Format	3.1.0.1-signed	TRUE
NoScript	2.6.9.35	TRUE
Open Bookmarks in New Tab	0.1.2012122901.1-signed	TRUE
Pinboard Extension	1.2.1-signed	TRUE
ProfileSwitcher	1.7.2	TRUE
Redirect Cleaner	2.4.0	TRUE
Re-Pagination	2015.01.11.1-signed	TRUE
RightToClick	2.9.5.1-signed	TRUE
Search by Image for Google	1.2.0.1-signed	TRUE
Self-Destructing Cookies	0.4.7.1-signed	TRUE
Session Manager	0.8.1.7	TRUE
Show my Password	2.0.1-signed	TRUE
Show Parent Folder	2.1.1-signed	TRUE
Social Fixer	11.2	TRUE
Status-4-Evar	2014.07.06.05.1-signed	TRUE
translator	2.0.3.1.1-signed	TRUE
UAControl	0.1.3.1.1-signed	TRUE
uBlock Origin	1.0.0.1	TRUE
Video Myxa	1.9.91.1-signed	TRUE
www.Tran	5.2.1-signed	TRUE
YouTube Center Developer Build	533	TRUE
YouTube Video and Audio Downloader	0.3.9.1.1-signed	TRUE
anonymoX	2.4.7.1-signed	FALSE
EPUBReader	1.5.0.6.1-signed	FALSE
Evernote Web Clipper	6.0.15.1-signed	FALSE
facepaste	2.8.1-signed	FALSE
Flashblock	1.5.18.1-signed	FALSE
Form History Control	1.4.0.4.1-signed	FALSE
Ghostery	5.4.6	FALSE
HTTPS-Everywhere	5.0.9	FALSE
Linky	3.0.0.1-signed	FALSE
Print pages to PDF	0.1.9.3.1-signed	FALSE
Screengrab (fix version)	0.98.08c	FALSE
SoundCloud Downloader - Technowise	0.94.1-signed	FALSE
Stylish	2.0.2.1-signed	FALSE

**Comment by gorhill** [comment]
Likely fixed when issues with toolbar/context menu/etc. were fixed.
