### ISSUE TITLE
Issue when editing Dynamic URL rules in My Rules tab

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#475]
#### STR
1. Open uBlock Settings window, and save the below rule (i.e., click commit) in <b>My Rules</b> tab
<code>* http://ajax.aspnetcdn.com/ajax script noop</code>

2. Click <b>edit</b> button, and remove <code>http://</code> from above rule

3. Click <b>save</b> button after removing above part from the rule.

4. You will see that new rule is not created. Only a temporary entry created to remove the old rule. New rule is altogether missing

##### Config
uBlock v0.9.9.4 dev7 - FF 39.0 - W7

![ublock rule creation missin](https://cloud.githubusercontent.com/assets/779630/8615377/0b661560-26c0-11e5-9558-216532638e80.png)

**Comment by g3939434** [comment]
WIKI - [Dynamic URL filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-URL-filtering)
>destination URL is URL to match: the URL of a resource must start exactly with the destination URL of a rule for a match to occur.

**Comment by harshanvn** [comment]
thanks, i missed that.
I some how wondering, it works similarly to dynamic filtering, except you could create more granular request based type rules...

**Comment by harshanvn** [comment]
Ok, I have another question, reg. Dynamic URL Filtering rules.
Whether the requests allowed by URL filtering rules reflect the dynamic Filtering UI (mini Matrix). Right now it is not. Is it expected?

![ublock url filtering in ui](https://cloud.githubusercontent.com/assets/779630/8616909/e2a89794-26cc-11e5-9bee-f4ed745a454c.png)

**Comment by g3939434** [comment]
>Whether the requests allowed by URL filtering rules reflect the dynamic Filtering UI (mini Matrix). Right now it is not. Is this expected?

No.

I suggest you should reopen the issue and change the topic, reporting this issue.
Noop rules of Dynamic URL filtering count as blocked on Dynamic filtering pane.

**Comment by harshanvn** [comment]
Ok Thanks. Will do that.

**Comment by gorhill** [comment]
> Whether the requests allowed by URL filtering rules reflect the dynamic Filtering UI (mini Matrix). Right now it is not. Is this expected?

Yes it is expected: dynamic URL rules can't be represented in the mini-matrix, as this mini-matrix is entirely based on hostnames. This is just impossible to represent in there: two URL rules can contradict each other for the same cell, plus other intractable UI issues as consequences of trying to reflect URL rules in the matrix.

See it as if trying to fit a square shape into a circle receptacle.

**Comment by harshanvn** [comment]
> two URL rules can contradict each other for the same cell

Not exactly sure. Is it not feasible, to count number of requests allowed/blocked and assign it to the cell
Say
a.com/url - block rule based on dynamic filtering setting
a.com/url- allow rule based on dynamic <b>url</b> filtering. And this takes precedence

can we not represent a.com cell as + -
this would help the users greatly in depicting if the requests are really allowed or blocked, if one is using more and more dynamic url filtering rules?

Note: Sorry, i am just trying to understand. If it is not meaningful and feasible. We can leave this here..

**Comment by g3939434** [comment]
>can we not represent a.com cell as + -

Your example isn't that good. It already reflected on the UI with `+  -` and in yellow. The real problem is when handling the noop rule.

**Comment by harshanvn** [comment]
> It already reflected on the UI with + - and in yellow.

Actually, i was referring
![ublock url filtering in ui](https://cloud.githubusercontent.com/assets/779630/8618327/208a341a-26db-11e5-9837-52cb87eb5c86.png)
 to this one

**Comment by g3939434** [comment]
That is the problem of noop rule. The only request from ajax.googleapis.com was that jquery.min.js. And a loop rule (I assumed) should count as nothing but now count as blocked. So it only showed with `-` and in` red`. But I assumed it should showed with `+` and in `green`.

You can test your case in real situation when the requests from same domain have more than one requests. One request is blocked by `a.com` and other one is allow `by a.com/url`
>a.com/ - block rule based on dynamic filtering setting
a.com/url - allow rule based on dynamic url filtering. And this takes precedence.

It would became `+ -` and in `yellow`.

With only one request and blocked by `a.com` should be `red` and `-`
With only one request and allowed by `a.com/url` should be `green` and `+`

**Comment by gorhill** [comment]
I am getting lost in the issues here. The one in OP is not an issue, it is by design.

The [new one added](https://github.com/gorhill/uBlock/issues/475#issuecomment-120363317) to this issue, it looks like I have misinterpreted it. [This one](https://github.com/gorhill/uBlock/issues/475#issuecomment-120396822) is unspected, **unless** there was a request blocked for `ajax.googleapis.com`. Can you please give URL etc. on how to reproduce?

**Comment by g3939434** [comment]
@gorhill
>Ok Thanks. Submitted #476

**Comment by gorhill** [comment]
Ah ok, I had missed this one.
