### ISSUE TITLE
Update benchmarcks graphs. 

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#477]
Please update benchmarcks graphs for Firefox 41 (who have massive memory improvements for adblock plus) and also for see the evolution of uBlock.

**Comment by anewuser** [comment]
Firefox stable is at version 39. Please read https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md and stop creating threads that aren't about bugs.

**Comment by LifeIsStrange** [comment]
I'm very sorry.
