### ISSUE TITLE
Not blocking Twitch Ads

### ISSUE THREAD

**Issue by Kevin138** [gorhill/uBlock#478]
For the past 2 days I have started seeing ads on Twitch.tv. The ads have been pre-roll ads for 5hr Energy. I have not seen ads mid-stream even though the broadcaster has stated they are running ads.

This also does not occur every time I load a stream, likely just when the pre-roll happens to be the 5hr Energy ad.

This issue has also been reported by at least 4 other people on the Support tab of the chrome web store for uBlock Origin.

uBlock Origin version: 0.9.9.3
Browser: Chrome version 43.0.2357.132 m (64-bit)
OS: Windows 7 SP3

Other Running Extensions:
Hyperlink Text Selector 1.3
ImprovedTube - YouTube Extension 0.6.3.1
Reddit Enhancement Suite 4.5.4
Session Buddy 3.4.6
LastPass: Free Password Manager 3.2.11
The Great Suspender 4.74

**Comment by g3939434** [comment]
Duplicate of #472

**Comment by gorhill** [comment]
Without a URL where you spotted an ad there is nothing I can do -- I could end up wasting a huge amount of time watching random twitch videos for which maybe there are no ads. I can't emphasize it more in there: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include>.

**Comment by Kevin138** [comment]
Ok, I did not know if you needed/wanted a specific channel link. I will keep an eye on which channels are having this issue.

Do you think it is less a problem with uBlock and more a filter list issue?

If that is the case then I am not sure which list/filter I would need to report the problem to.

**Comment by anewuser** [comment]
@Kevin138 uBlock doesn't block anything by itself. It's all in the filters. If an English-language site that used not to have ads now show ads, report it to EasyList. Your specific problem has already been reported, and they usually take a few days to add new filters: https://forums.lanik.us/viewtopic.php?f=62&t=23898

If you need help to learn to identify ads and block them by yourself, [read the documentation](https://github.com/gorhill/ublock/wiki) and/or ask for help on Reddit (the link is on the . [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include) page).

**Comment by gorhill** [comment]
> Do you think it is less a problem with uBlock and more a filter list issue?

At this point, uBlock's blocking engine is definitely mature enough to suspect a filter list issue. I see entries for `twitch.tv` in EasyList. I did try a few random videos and there were no ads, and I could see stuff blocked (red) or allowed (green, exception filters) in the logger related to what appear ads (`doubleclick.net`), but no ads played. For example:

<http://www.twitch.tv/mrtakahashi/v/6697058>:

![a](https://cloud.githubusercontent.com/assets/585534/8629008/77d44810-2725-11e5-8ea2-b3a2a569eb4c.png)

**Comment by Kevin138** [comment]
OK, sorry for the false submission. Closing this.
