### ISSUE TITLE
Show resource type blocked next to domain

### ISSUE THREAD

**Issue by georgiopandarez** [gorhill/uBlock#479]
I run with 3rd party requests disabled, often only one domain needs to be enabled for the css or images to load and make the site usable. Sometimes it is obvious which one, other times it is not. If it is possible if the context of the block could be taken to display some kind of indicator next to the blocked domain would make life in this mode easier.

**Comment by gorhill** [comment]
There is not really any space in the UI for this.

**Comment by SARG04** [comment]
You could use [uMatrix](https://github.com/gorhill/uMatrix) to block 3rd party requests.
There it is easy to see which type of contend is blocked.

**Comment by georgiopandarez** [comment]
Thanks, didn't know about uMatrix. 

Shame it allows subdomains as first party requests. Sorry for the noise.
