### ISSUE TITLE
Popup Mouse Over Info & No strict blocking...

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#48]
If we mouse over the popup, does it tell us what the 3 options are?

![popup-1j](https://cloud.githubusercontent.com/assets/11289036/7129446/f772f5e6-e24f-11e4-8d2c-30bea8063acf.png)

I know there is information explaining these on GitHub;

https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-cosmetic-filtering

But it would be nice if there is a popup that gave a brief description. 

I also thought mouse over in the last versions for the eye dropper and paper next to it, told us what they were too?

Also for the `No strict blocking` where are these `Go Back`Temporarily`and`Permanently``` being displayed? I don't see these anywhere...

Hmm

**Comment by DoodleChan** [comment]
Tool tips are disabled when "advanced user" is enabled.

>Also for the No strict blocking where are these Go Back Temporarily and Permanently being displayed? I don't see these anywhere...

When you try to visit `example.com` with a filter like: `||example.com^`

**Comment by gorhill** [comment]
It's all in the wiki.

**Comment by meuwe** [comment]
Sorry I've been reading, didn't notice this, my bad... :(
