### ISSUE TITLE
Cosmetic changes to the popup interface

### ISSUE THREAD

**Issue by Korodny** [gorhill/uBlock#480]
The popup user interface's height is only about a third of the browser window. IMHO, this could easily be increased to 50 or 60 percent - which would let me see twice as many domains without scrolling.

Not sure if there are style guides for adding UI elements to Firefox, but none of the popup elements in Firefox I regularly use have a title bar - uBlock having one really stands out. And not in a good way, IMHO (screenshot is from Gnome theme, but it looks the same with standard theme):

![ublock](https://cloud.githubusercontent.com/assets/2822120/8633940/7fa79352-27e4-11e5-9a1d-2d0b5738f4bc.png)

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit>:

> Do NOT: [...] Submit design ideas.

These are subjective = never ending debate.
