### ISSUE TITLE
Cog button in addon manager should take me to dashboard

### ISSUE THREAD

**Issue by Korodny** [gorhill/uBlock#482]
On uBlock 0.9.9.3,  if I display the list of extensions I have installed, the button "settings" ("Einstellungen") takes me to the same page as the "Mehr" ("More") link: 

![ublock3](https://cloud.githubusercontent.com/assets/2822120/8634101/1e705bee-27eb-11e5-81ba-e884f9a61cce.png)

With my other extensions, the settings button always opens the configuration instead - the equivalent to uBlock's dashboard.

**Comment by alejandrolemus** [comment]
Same as your other issue I just replied to. Please close both issues and report to [uBlock](https://github.com/chrisaljoudi/uBlock) instead.

**Comment by gorhill** [comment]
There are no cog buttons in my Firefox 39.

**Comment by alejandrolemus** [comment]
>There are no cog buttons in my Firefox 39.

Because he is using uBlock, not Origin. If you look at his other issue, it says "Homepage: https://github.com/gorhill/uBlock", not sure why.

**Comment by Korodny** [comment]
My Apologies, I simply followed the link in the addon manager which took me here.

**Comment by gorhill** [comment]
I see, I have a _Preferences_ button instead of a cog icon.

**Comment by gorhill** [comment]
I still want to look into this fir this version here.

**Comment by Korodny** [comment]
Switched to uBlock Origin now, updated screenshot and description.

**Comment by alejandrolemus** [comment]
My apologies too, seeing as it was the 'other' uBlock I didn't even try to understand what the issues where about.

**Comment by gorhill** [comment]
I can have the _Preferences_ button open the dashboard by modifying the manifest file, however this would not be a good thing for Firefox on Android. I would need to test the result on Android to find out if the current behavior is maintained.

**Comment by TeddStriker** [comment]
Wait is it not supposed to do that? I've been using origin for a while now, and it always took me to the **more** page, and I went `go to dashboard` from there. I thought it was a bit unnecessary, but never bothered to bring it up.

**Comment by gorhill** [comment]
I will have to decline this one. I tested with Firefox Mobile and unfortunately, if I make the _Preferences_ button open the dashboard, this cripples Firefox Mobile.

**Comment by g3939434** [comment]
>Wait is it not supposed to do that?

It supposed to do so.

>With my other extensions, the settings button always opens the configuration instead

The options button doesn't always opens the configuration. Some add-ons may have config directly on the "more" page, i.e. Adblock Plus. For those which directly open the configuration wouldn't have anything other than "Option" button on the "more" page. And uBlock Origin has "Show Dashboard" button and "Show Logger" button on "more" page.
