### ISSUE TITLE
uBlock was blocking my PayPal Business dashboard

### ISSUE THREAD

**Issue by BoomLiam** [gorhill/uBlock#483]
uBlock seems to have caught something on the PayPal dashboard for business accounts (not sure if it affects all, otherwise I would assume this issue might have been raised already) but upon visiting my dashboard on PayPal, the two tabs for balance and transactions were constantly loading. After whitelisting the PayPal site on uBlock, the issue was resolved. But I did want to raise this in case it was unknown and could be fixed to avoid any future confusions with anyone.

Thanks!

**Comment by gorhill** [comment]
This should be brought to the filter list maintainers, which are 3rd-party to uBlock. Use the logger to find out which filter list is at fault (I don't have a PayPal account, can't look this up).
