### ISSUE TITLE
Maybe 1st-party vs 3rd-party for images / CSS, not just scripts?

### ISSUE THREAD

**Issue by wolftune** [gorhill/uBlock#484]
As an advanced user, I thought that block-all by default would replace requestpolicy smoothly. It's close, but I seem to be blocking CSS and images for 1st-party sites, so that 99% of sites are broken, even those that don't rely on 3rd-parties *or* JavaScript.

I think it would be ideal to have separate 1st-party vs 3rd-party options for images and CSS.

Here's the real issue: there seems to be *no* setting to block all 3rd-party images but not block 1st-party, and also, there's a bug where I can go to a *very* plain site (such as https://www.seas.upenn.edu/~cis194/spring13/ ) and the layout itself is broken if I default to block *all*, but the layout works correct if I block every one of the other thing to block (images, scripts, scripts and frames of all sorts). So, blocking all is blocking extra 1st-party stuff that isn't separately categorized among the general options… I'm unclear what it is that is extra to block (CSS I suppose). I don't want to block 1st-party CSS, but I'm unsure whether blocking all is otherwise blocking anything else I'd *like* to block, since I'm unsure the total list of non-blocked things when all general options except for "all" are set to block…

**Comment by gorhill** [comment]
I personally do not see `all` as very being very useful. Why not use `3rd-party`? That's what I use, and that what RP does if I am not mistaken.

**Comment by TeddStriker** [comment]
Using the site you posted, blocking `all` does break the site. And there's no option to allow CSS/Images only for the first party. 

However, and @gorhill can correct me if I'm mistaken, I think uBlock wasn't meant to allow such precise options, I think you're looking for functionality [uMatrix](https://github.com/gorhill/uMatrix/) has to offer. 

This is all under the assumption that I understood what you were trying to say correctly, if not, I apologize.

**Comment by wolftune** [comment]
Thanks, I guess I was being over-cautious. I think that 3rd-party is all I really need when combined with static-filters. @gorhill is the reason 3rd-party scripts not blocked in your screenshot because you use NoScript for that?

**Comment by gorhill** [comment]
> 3rd-party scripts not blocked in your screenshot because you use NoScript for that?

They are blocked, through `3rd-party` cell.

**Comment by wolftune** [comment]
@gorhill okay, so last question then: is it an inconsistency in the UI versus the backend that marking "3rd-party" as blocked doesn't create a light-red indication for "3rd-party scripts" and "3rd-party frames"?

**Comment by gorhill** [comment]
> is it an inconsistency in the UI versus the backend that marking "3rd-party" as blocked doesn't create a light-red indication for "3rd-party scripts" and "3rd-party frames"?

Yes, ideally they should light up in sync with `3rd-party` unless they have their own rules. The matrix coloring uses the same code paths as the request evaluation. I am sure I wanted this originally but it was not as straightforward as thought back then.
