### ISSUE TITLE
Issues Malware filter list by Disconnect‎?

### ISSUE THREAD

**Issue by phuc365** [gorhill/uBlock#485]
<i>Malware filter list by Disconnect‎</i> sometimes to appear, sometimes to disappear?

<b>Please watch this video :)</b>

https://youtu.be/IguzjAuJLB8

<b>After restart Firefox browser</b>

https://youtu.be/XolQPOAnXQQ

<b><i>Thank you for your interest</i></b>

**Comment by gorhill** [comment]
_Malware filter list by Disconnect‎_ is part of stock filter lists in 0.9.9.3, but I removed it as stock filter list last week after the list blocked `s3.amazonaws.com`. So if you purge all caches, it's like going back to install settings and the filter list will reappear.

I will put it back, but no longer selected by default as it was before.
