### ISSUE TITLE
Awesome New Tab Page search bar not blocking/hiding

### ISSUE THREAD

**Issue by alidan** [gorhill/uBlock#486]
i use Awesome New Tab Page because i don't like chrome's standard sense they made changes a long time ago. 

until this morning, i used ABP but i was convinced to try ublock.

the first thing i did was open a new tab and the search bar was at the top... at some point they added it but it was always blocked or hidden with ABP and i either cant block it or am to stupid to block it with ublock... 

is this an issue that needs addressing? am i to stupid to figure out the solution? any help if i am?

**Comment by anewuser** [comment]
* uBlock Origin whitelists extension pages by default not to break things accidently. We don't recommend novice users to change this setting
* Awesome New Tab Page [has been bought by an adware provider](http://www.omgchrome.com/chrome-users-start-raise-awareness-extensions-known-peddle-adware/). I suggest you to uninstall it and find an an alternative

**Comment by gorhill** [comment]
> i use Awesome New Tab Page because i [...]

Reading the reviews, I don't feel like installing that _Awesome New Tab_ thing. Marked as _available_ if someone else wants to look into this.

**Comment by lewisje** [comment]
I suggest Panda as an alternative to Awesome New Tab Page.
