### ISSUE TITLE
The icon for debugging the site is missing from the pull down 

### ISSUE THREAD

**Issue by gerroon** [gorhill/uBlock#487]
Hi

I do not know what that icon is called but It was used for showing the site and all the blocks and connections from the  page. It was next to element picker.

The element picker is still there.

I am using 1.0 on Iceweasel  39 on Debian 64

thanks

**Comment by gorhill** [comment]
Do you have some user styles which are interferring with uBlock's popup?

**Comment by gerroon** [comment]
No I do not.  THis was working fine in the previous version.

**Comment by gorhill** [comment]
Can you provide me with a screenshot of the popup?

**Comment by alejandrolemus** [comment]
That one (among other small issues) has happened to me a few times in the past, after upgrading to a new version. Usually a browser restart of disabling/enabling uBlock solved the issue(s).

**Comment by gerroon** [comment]
![menu_002](https://cloud.githubusercontent.com/assets/8519469/8655346/38dd5c86-2956-11e5-81fb-da7e64af1a5f.png)

**Comment by gorhill** [comment]
I am going to let you deal with your issue: it appears uBlock's choice of fonts are overriden on your system<sup>[1]</sup>, so you will have to find out why and fix your system.

[1] uBlock uses `sans-serif` fonts, and your popup shows `serif` font, on top of having FontAwesome being overriden apparently not just for the logger button, but also for the whitelist switch, and the font switch.

**Comment by gerroon** [comment]
well sure, I can figure out the font issue but what about the icon that is missing? My system has not changed and this disapperaing icon issue just started happening after I upgraded 1.0

**Comment by gorhill** [comment]
> this disapperaing icon issue just started happening after I upgraded 1.0

Here is another coincidence: <https://github.com/dillbyrne/random-agent-spoofer/issues/259>.
