### ISSUE TITLE
[not a bug] couple of things to correct on home page

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#488]
On the home page, I see below statements are no longer true, we can remove them -

<code>
uBlock Origin works fine on Nightly with e10s enabled, however there is bugzilla issue 1171173,  which causes uBlock to not perform optimally. To work around this issue, disable then renable uBlock after launching Nightly with uBlock already enabled. The issue does not occur if e10s is not enabled.
</code>

And <b>below</b> statement, might not longer be true, as you started supporting legacy browsers from 0.9.9.2 version if i am not mistaken -

<code>
proper support for legacy Firefox-based browsers.
For Firefox legacy versions -- prior to Firefox 29 -- it is best to install chrisaljoudi/uBlock as it has official support for legacy Firefox versions.
</code>

And the important  thing, i don't see any where mentioned about Android. I believe most people are unaware that one can install it on the android too!. Can we have the below link added under firefox section? Good news is that, it is listed as <b>featured</b> addon
<code>https://addons.mozilla.org/en-US/android/addon/ublock-origin/</code>

Note: I do not see any link to edit the page. Hence submitting a ticket.

**Comment by gorhill** [comment]
Thanks for the notice.
