### ISSUE TITLE
tiny logger bug

### ISSUE THREAD

**Issue by androidland** [gorhill/uBlock#489]
![logger ui](https://cloud.githubusercontent.com/assets/9499540/8646749/9e30250c-297c-11e5-8fa6-b203d480c5b3.png)

i dont know this is bug or new ui
win 7, ff 39, ublock0 1.0.0.0-rc.0

**Comment by harshanvn** [comment]
i do not think this is a bug (you will see various selectors <expand, clear>, in a stick way, when the page is scrolled down). i believe this is by design.

**Comment by gorhill** [comment]
By design. I see no harm in having the toolbar "float" over the log entries.
