### ISSUE TITLE
3rd-party filters issue

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#49]
On Seamonkey v2.33.1:
1st-time setting of 3rd-party filters works well.
After the browser is closed, and then newly opened, the check-boxes setting is not restored and the parsing doesn't work. It only shows the text box with list of URLs and the "parse" button is disabled.

This happens as soon as one of the following URLs are added to the custom list:
https://secure.fanboy.co.nz/israelilist/IsraelList.txt
https://easylist-downloads.adblockplus.org/israellist+easylist.txt

**Comment by gorhill** [comment]
> It only shows the text box with list of URLs and the "parse" button is disabled

The parse button is always disabled if there are no changes in the text area.

**Comment by gorhill** [comment]
Best solution is to have at least one developer to step up to volunteer work for SeaMonkey support.

**Comment by lewisje** [comment]
I didn't even think that uBlock Origin was supposed to support Firefox; I thought that was just for the version that had been transferred to chrisaljoudi.

**Comment by WyohKnott** [comment]
From the console if it helps:
```
Timestamp: 25/04/2015 00:07:13
Error: TypeError: getTabBrowser(...) is null
Source File: chrome://ublock0/content/js/vapi-background.js
Line: 498

Timestamp: 25/04/2015 00:07:13
Error: TypeError: vAPI.lastError is not a function
Source File: chrome://ublock0/content/js/assets.js
Line: 130

Security Error: Content at moz-nullprincipal:{0e4202ec-a982-4d2c-826a-d4e46d7b2be7} may not load or link to chrome://ublock0/content/3p-filters.html.

Security Error: Content at moz-nullprincipal:{0e4202ec-a982-4d2c-826a-d4e46d7b2be7} may not load or link to chrome://ublock0/content/3p-filters.html.

Timestamp: 25/04/2015 00:07:14
Error: TypeError: vAPI.lastError is not a function
Source File: chrome://ublock0/content/js/assets.js
Line: 130

Timestamp: 25/04/2015 00:07:14
Error: TypeError: vAPI.lastError is not a function
Source File: chrome://ublock0/content/js/assets.js
Line: 130

Security Error: Content at moz-nullprincipal:{0e4202ec-a982-4d2c-826a-d4e46d7b2be7} may not load or link to chrome://ublock0/content/settings.html.

Security Error: Content at moz-nullprincipal:{0e4202ec-a982-4d2c-826a-d4e46d7b2be7} may not load or link to chrome://ublock0/content/dyna-rules.html.

```

**Comment by gorhill** [comment]
Ok, @AlexVallat's [work](https://github.com/chrisaljoudi/uBlock/commit/5ac4ec21e9e960346b72889e842dbb6b0772aa76) on <https://github.com/chrisaljoudi/uBlock> addresses all the issues of supporting legacy Firefox-based browsers. I decided I won't be importing his fixes, he is the best placed developer to provide follow-up support on whatever issue may arise relative to his work. So for those who wish a fully workable uBlock on legacy Firefox-based browser, <https://github.com/chrisaljoudi/uBlock> is the version to install.
