### ISSUE TITLE
Do not allow enabling duplicate filter lists

### ISSUE THREAD

**Issue by SnowGabe** [gorhill/uBlock#491]
For example, 'Fanboy’s Annoyance List‎' contains 'Fanboy’s Social Blocking List‎'. The block lists shouldn't under any circumstances be used concurrently. 
UBlock should prevent the user from enabling duplicate filter lists.

**Comment by gorhill** [comment]
Declined. There is no terrible harm in having filter lists which intersect, and the number of filter used in a list is sufficient information for someone to decide whether a filter list is useful or not.
