### ISSUE TITLE
LINK: Fanboy+Easylist-Merged Ultimate List

### ISSUE THREAD

**Issue by C4R2T3N** [gorhill/uBlock#492]
https://www.fanboy.co.nz/fanboy-ultimate.txt
is now:
https://www.fanboy.co.nz/r/fanboy-ultimate.txt

**Comment by gorhill** [comment]
> https://www.fanboy.co.nz/r/fanboy-ultimate.txt

And that's what uBlock uses.

**Comment by C4R2T3N** [comment]
Sry, precisely: the homeURL is right, but the link at the filtermenu (dashboard) is not working - it leads to https://www.fanboy.co.nz/fanboy-ultimate.txt. Or am i complete wrong?

**Comment by ldgbc** [comment]
Please also change the link in 
uBlock's Setting > 3rd-Party Filters >  Fanboy+Easylist-Merged Ultimate List
Currently (v1.0.0.r3) link this when hover "chrome://ublock0/content/asset-viewer.html?url=assets/thirdparties/www.fanboy.co.nz/fanboy-ultimate.txt"
Clicking on it will lead to a 404 page.

**Comment by gorhill** [comment]
> Clicking on it will lead to a 404 page

I don't get a 404. The local copy of Fanboy Ultimate is opened, and since Fanboy Ultimate ships with uBlock, it can't 404.

**Comment by ldgbc** [comment]
Yes you are correct. However copy/pasting the UR page "www.fanboy.co.nz/fanboy-ultimate.txt" would lead to a 404 page.

**Comment by gorhill** [comment]
> However copy/pasting the URL

There is no documentation which supports copy/pasting the URL works. As it is now, the `url` parameter in `chrome-extension://pbffolnficoggnnamkphaffidiafpeaf/asset-viewer.html?url=assets/thirdparties/www.fanboy.co.nz/fanboy-ultimate.txt` must be seen as a key to identify uniquely the filter list, there is no guarantee this key can be used as a plain functional URL.
