### ISSUE TITLE
No privacy policy

### ISSUE THREAD

**Issue by bwiklak** [gorhill/uBlock#493]
There's no privacy policy on uBlock page.
Does uBlock send and/or collect any data about user behavior, statistics or any other information, even anonymous?

**Comment by harshanvn** [comment]
It does not collect any kind of data and sent to home! (it does not have its own server)

You can take a look at the below page for the required permission, where Raymond clearly explains the use of all the permissions required by the extensions, to do its job -

https://github.com/gorhill/uBlock/wiki/About-the-required-permissions

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Privacy-policy
