### ISSUE TITLE
ny times webrtc ip address collection

### ISSUE THREAD

**Issue by pcause** [gorhill/uBlock#494]
not sure if you saw that the ny times is using webrtc to gather addresses

http://no-adware.com/blog/ny-times-webrtc-hack/

thanks to ublock, we're protected, i hope.  code is here so you can check and perhaps adding the stun server to the ublock filter list.

**Comment by gorhill** [comment]
> perhaps adding the stun server to the ublock filter list

`tagsrvcs.com` can now be found in EasyPrivacy.
