### ISSUE TITLE
Blocking Font Awesome icons

### ISSUE THREAD

**Issue by erikcw** [gorhill/uBlock#495]
uBlock is blocking [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/#brand) "brand" icons.

Seems to be the same issue as Adblock Plus:

```
Apparently, Adblock Plus can remove Font Awesome brand icons with their "Remove Social Media Buttons" setting. We will not use hacks to force them to display. Please report an issue with Adblock Plus if you believe this to be an error. To work around this, you'll need to modify the social icon class names.
```

**Comment by gorhill** [comment]
> [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/#brand)

I see them fine. If you mean the font is blocked when selecting _Fanboy's Social Blocking List_, then it is a 3rd-party filter list issue, not a uBlock issue.
