### ISSUE TITLE
Bottom popup toolbar is getting cut off in Chrome with page zoom 175%

### ISSUE THREAD

**Issue by serg472** [gorhill/uBlock#497]
I use Chrome "43.0.2357.134 m" for Win7 with the default page zoom set at 175% (set in Chrome settings). This causes the bottom toolbar inside the uBlock extension popup to be cut off (see screenshot). To reproduce it change the default page zoom level in the settings and restart the browser. 
![untitled](https://cloud.githubusercontent.com/assets/1200229/8740493/12b9e03c-2bff-11e5-9beb-07ee733eca0c.png)

**Comment by gorhill** [comment]
The browser limit the height of the popup, The max size of the popup is out of uBlock's control.

**Comment by serg472** [comment]
The size of the popup is out of control, but the positioning of elements inside the popup isn't. The bug is in positioning elements, not browser not resizing the popup window.
At the very least an auto scrollbar can be easily added so if the content doesn't fit you can still get to the bottom somehow.

**Comment by gorhill** [comment]
> The bug is in positioning elements

The bug is using much larger font size while the popup max size stays the same. Try 500% zoom, and see how this works.

**Comment by gorhill** [comment]
I can make the scroll bars appear when the popup is not large enough on Chromium. However, they appears all the time with Firefox.

**Comment by gorhill** [comment]
I just tested with Chromium 84 and uBO 1.28.4 and this is no longer an issue, there is a vertical scrollbar appearing in case the popup panel is larger the the browser-supplied viewport.
