### ISSUE TITLE
Hidden tab can be opened in the logger's window, so closing it generates a prompt

### ISSUE THREAD

**Issue by enomat** [gorhill/uBlock#498]
1. Open the logger in a new window (shift+click).
2. Load any page, so items will appear in the logger.
3. Click on the 2. column, so the popup UI will appear in the logger.
4. Click on the Ublock name/version which opens Ublock's settings menu.

The settings menu will be opened in a new tab in the logger's window. That tab cannot be closed (because the tab bar is hidden). So if you want to close the logger's window, a prompt will appear which says 2 tabs wil be closed and asks if you want to continue.
( Firefox 38.0.5 with UBlock Origin 1.0.0.0 )

**Comment by luxoflux** [comment]
Confirmed.

Though personally, I just open the logger normally and drag the tab out to separate it.

**Comment by gorhill** [comment]
This was fixed at some point, the tab bar and other bars are no longer hidden when the logger is opened in a separate window.
