### ISSUE TITLE
Ublock Origin not blocking ads on gaming.tv

### ISSUE THREAD

**Issue by rogama25** [gorhill/uBlock#499]
![ublock](https://cloud.githubusercontent.com/assets/11318350/8752206/1e3a892a-2cb3-11e5-97e7-b2e6bcd90761.png)
Some ads appears on the streaming and I need to wait 5 seconds and click the "Skip ad" button to continue watching :)

**Comment by CrisBRM** [comment]
Gorhill doesn't maintain the lists. 
Use the logger to determine the culprits and then report them here: https://easylist.adblockplus.org/en/

**Comment by gorhill** [comment]
I tried with ABP and EasyList/EasyPrivacy, and an ad also played. So it's a filter list issue.

**Comment by gorhill** [comment]
Out of curiousity, I created this filter, `||epsiloncdn.net$domain=www.gaming.tv,object`, and it does appear the ad got blocked.

So you should report this to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=62>.
