### ISSUE TITLE
uBlock₀ taken down from Chrome store (I have no clue why)

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#50]
This is what I got today when I logged in my Chrome store dashboard:

![ublock-remove-from-chrome-store](https://cloud.githubusercontent.com/assets/585534/7136396/6dd43a46-e27e-11e4-9b82-b4215c4aa558.png)
- I have no clue why it was removed
- I did not receive any email about this
- I don't see any email which I can contact to find out what is the problem
- The version removed is **exactly** as the [latest one in the release section](https://github.com/gorhill/uBlock/releases)
- The [other uBlock](https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn) is still in the store.
- The message says: "[...] did not comply with [our policies or terms of service](https://ssl.gstatic.com/chrome/webstore/intl/en-GB/gallery_tos.html)"

**Comment by harshanvn** [comment]
when i click the chrome store link, it says - 
```
An error occurred:
Item not found. This item may have been removed by its author.
```

**Comment by my-password-is-password** [comment]
Could it be because the code was too similar to uBlock and they think all you did was copy it and add a ₀ to it?

**Comment by caizixian** [comment]
That's so strange.

**Comment by gorhill** [comment]
> Could it be because the code was too similar to uBlock

Code is GPLv3.

**Comment by yuan18** [comment]
Please try to re-upload。

**Comment by gorhill** [comment]
> Please try to re-upload。

There is no point. There is something the Google Chrome store doesn't like in there and whatever that is they want it changed. But I have no clue what it is.

**Comment by weakptr** [comment]
You could always try contacting them (or banging head against wall) at 
https://support.google.com/chrome_webstore/contact/developer_support/?hl=en

**Comment by gorhill** [comment]
@weakptr Thanks. I submitted a ticket. Will see.

**Comment by lewisje** [comment]
"properly respecting git history"

I realize this sounds incredibly noobish, but how would that be done? I haven't been able to get merge conflicts resolved any way but manually, which means that git history is not respected. (Maybe it's something that can be done in command-line Git but not in Github for Windows.)

Anyway, it's nice to know that you didn't just take your own extension down; I was about to file an issue about it only to see that you already did.

**Comment by weakptr** [comment]
I found the page by following links via googling chrome store help.

**Comment by gorhill** [comment]
> I realize this sounds incredibly noobish, but how would that be done?

Create a pull request as was [done here](https://github.com/chrisaljoudi/uBlock/pull/1229), or `git cherry-pick`, or at the _very least_ when manually bringing changes, keep track of where the code comes from in [commit messages/code comments](https://github.com/gorhill/uBlock/commit/63d9143d6bfdac1d603b5f8f62f99aecc67371d2).

Imagine if everywhere whoever contributes to a project is not only stripped from authorship of their contribution. I am pretty sure this is a frowned upon practice.

**Comment by gorhill** [comment]
I received an answer for the above complaint I filed with the Chrome store. Full answer:

    Hello Raymond,

    Thank you for contacting Chrome Web Store Support 

    Sorry to hear that your extension was taken down.

    It's seems it had a policy violation and thus it was taken down.

    An email was sent to rhill@raymondhill.net  explaining in further detail.

    Check your spam folder just in case. Let us know if you have any other questions or concerns.

    Cheers,
    Apurva
    CWS Developer Support team. 

    On 04/14/15 07:54:14 rhill@raymondhill.net wrote:

        dev_first_name: Raymond
        dev_last_name: Hill
        dev_email: rhill@raymondhill.net
        dev_chrome_ID: cjpalhdlnbpafiamejdnhcphjbkeiagm
        dev_describe_issue: When I opened my dashboard this morning, I was greeted
        with a message telling me the extension's status was "TAKEN DOWN". When I
        click "Action needed!", this just reload the dashboard, with a generic
        message: "At least one of your items has been removed from the store
        because it did not comply with our policies or terms of service". So I have
        no clue what exactly is not in compliance with "policies or terms of
        service".

        I filed an issue here: https://github.com/gorhill/uBlock/issues/50
        developer_support_attachment: There was a file uploaded for this field.
        upload_original_filename: ublock-remove-from-chrome-store.png
        upload_cns_filename:
        AK6tmUNzDyRw2uQnonseDHAMqEIugrs78ElvAPk8cOAk5XjRf27T1Mz4bNtebAtSMPW-0aTeTYHyO52wTYls5x8JUWj2kBdgMj1NGdFhovo3RQLhtrrc2inD4ClREI-wnYJdw3m1rW-cTm4P5ihNvDzwgRRW3pP0fkqx_q4iIArFAQ1w3soB5wKX_c29819aeKzRmpi1r434iz0M2szaUCaXyevWytCAZoS7bNh2kypusV7UuQ67BE0gV0eBxHbKl7lYXo5UUbwbPuIoOKmlucFXWaD5xbM3qw
        upload_document_id: dade969940aa9ccb561478f3408333839e650130


        :---- Automatically added fields ----:
        Language: en
        IIILanguage: en
        auto-helpcenter-id: 1154727
        auto-helpcenter-name: chrome_webstore
        auto-internal-helpcenter-name: chrome_webstore
        auto-full-url:
        https://support.google.com/chrome_webstore/contact/developer_support/?hl=en
        auto-user-logged-in: true
        auto-user-was-internal: false
        IssueType: developer_support
        form-id: developer_support
        form: developer_support
        subject-line-field-id:
        body-text-field-id: 

I **did not** receive an _"explaining in further detail"_, and I did triple-check my mailbox, including junk folder.

Looks like a dead end to me.

**Comment by tlu1024** [comment]
Policy violation??? Wasn't this also the justification why ABP and Adaway were removed from the Android Play Store 1 or 2 years ago?

**Comment by gorhill** [comment]
I replied to the email, in a last attempt at finding out what is going on. My answer:

    Greetings.

    You say:

    > An email was sent to rhill@raymondhill.net  explaining in further detail

    I did not receive any such email. I did look carefully in my junk folder.

    I had no problem receiving your answer below.

    Is it possible please to re-send the email -- or better, to attach it in
    a reply to this email?

    Thank you,
    Raymond Hill.

**Comment by tlu1024** [comment]
This is waht happened to Adaway and ABP in the Play Store:

http://lifehacker.com/5990448/google-has-started-removing-ad-blockers-from-the-play-store

I suspect something bad :-(

**Comment by hipunk** [comment]
How dare you blocking Google! Bad developerpuppy!

You should be happy that at least somebody wants to know what's up in your life. Why block the interested away?

Just kidding, of course.

Yeah, don't be evil. Google never stated what's evil in their eyes. Seems that blocking their ads is.

**Comment by kurtextrem** [comment]
https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions
You could try posting there as well.

**Comment by gorhill** [comment]
> You could try posting there as well

I can't start to run around to try finding out something they could just have emailed me with their last email reply. They just have to email me back the detail about what specific policy was violated -- that should not be too difficult -- unless of course it's corporate secret.

**Comment by kurtextrem** [comment]
I feel with you - you're not the only one who feels like this. In that exact group, there are often these cases and problems. I don't follow every single one, but some were solved this way.

**Comment by Decme** [comment]
What's a reasonable time for them to respond? 2 days? Thereafter I think you're well entitled to look into other avenues to get the problem resolved.

**Comment by gorhill** [comment]
> What's a reasonable time for them to respond?

They answered my [original complaint](https://github.com/gorhill/uBlock/issues/50#issuecomment-92890224) in [less than two hours](https://github.com/gorhill/uBlock/issues/50#issuecomment-92956050).

**Comment by lewisje** [comment]
"Policy violation??? Wasn't this also the justification why ABP and Adaway were removed from the Android Play Store 1 or 2 years ago?"

**Play Store != Chrome Web Store**

Also, ABP for Android works differently from ABP for Chrome; the former is a filtering proxy that arbitrarily modifies the behavior of other apps (something [not allowed by the Play Store TOS](https://adblockplus.org/blog/adblock-plus-for-android-removed-from-google-play-store)), while the other is a browser extension that doesn't even modify other programs on the user's computer; at least Android doesn't (yet) lock down the platform so you can only get apps from the Play Store, the way that Stable or Beta versions of Chrome for Windows cannot get extensions outside the Chrome Web Store.

**Comment by kintpuash** [comment]
There were a couple of feedbacks past week from two(?) users complaining they could not uninstall the extension. I assumed it was user error. Perhaps there was more to it.

**Comment by gorhill** [comment]
The Chrome store is ridiculous. They should just be straightforward and state the reason of why the extension is taken down right in the dashboard. What's so difficult about this?

Currently I am completely left clueless about what needs to be done according to them. I did not receive any email contrary to what they claim, and the dashboard says nothing. How convenient that they can take something down with no explanation aside a very generic "policy violation".

The extension has been there for months, and suddenly apparently there is an "issue" out of nowhere, and I am supposed to guess it.

**Comment by gorhill** [comment]
> they could not uninstall the extension

Yes, I saw this. Not much I can do. One was complaining the extension had been installed using "enterprise policy". So there is nothing I can do about how their extension was installed. I am pretty sure there are tainted versions of uBlock out there, so users can blame only themselves if they install from an unreliable source, which would be anything else than the Chrome store, Opera store, or the Github repo.

**Comment by gorhill** [comment]
However I look at this, the most plausible explanation I can think of is foul play, it just does not make sense that this happens out of nowhere with barely in change in the extension code base/behavior aside small feature changes.

**Comment by kintpuash** [comment]
I wonder how the Chrome Store responds when served with a legal notice? Shoot first, ask questions later similar to Youtube? Odd this comes less than 48 hours after the developer of Adblock Edge throws her or her support behind uBlock.

**Comment by gorhill** [comment]
I changed the logo. Just trying something random, since I have no clue what is the issue. I don't know what would be the next thing to try if this doesn't work.

**Comment by RomanZhilich** [comment]
Unfortunately there's not much to be done with this kind of Google behavior. There's a lot of stories out there about applications\extentions being taken down without proper notice and explanation. This is a complex problem which effected a lot of Youtube channel owners, android app developers etc. There are even some petitions trying to force Google to change this fault practice.

Your best options are probably:

* Make a big fuzz about it. It'll probably really help if some technical news sites \ bloggers were to write about this.
* Try to unofficially contact some Google employees and ask them to get an inside view on a situation.
* Dig around and look for other similar take-downs. There's a chance you wasn't the only one effected.

**Comment by Caspy7** [comment]
No idea, but is there some sort of policy about similar names (wherein an extension attempts to unfairly take advantage of or even deceive via a slightly different name)?
Obviously it would be ironic and unfair in this instance, but perhaps a report and next to zero research would explain for the outcome.

**Comment by meuwe** [comment]
The name should be changed to something like aBlock...

I wouldn't be surprised in the future if the name similarites causes issues.

**Comment by Ricardo1991** [comment]
aBlock might suggest this is only an ad blocker. You could try to deviate from that.

Also, i came up with this. the blue stop sign is kinda, you know... http://imgur.com/yJhBzv1

**Comment by kintpuash** [comment]
@Ricardo1991 

That icon is pretty snazzy.

**Comment by RandomAcronym** [comment]
@Ricardo1991 I swear I made this before I saw yours
![ublock0_300px](https://cloud.githubusercontent.com/assets/2810488/7151394/5f1ba178-e2f7-11e4-83eb-afea5036972f.png)

**Comment by meuwe** [comment]
@Ricardo1991 very nice image!

That makes me realize a NEW name then!

```uBlockIt``` or maybe written instead as, ```uBlockIT```

**Comment by tlu1024** [comment]
@lewisje 
> Play Store != Chrome Web Store

Yes, but in both cases it's Google, and in both cases it seems to be the same pattern.

**Comment by tlu1024** [comment]
@Ricardo1991 

I like it!

Although I believe to remember that a rather similar icon is used by another extension - or was it an AV program ... ? I'm not sure.

**Comment by gorhill** [comment]
@Ricardo1991 

Well I have imported and reworked it, so it will look different. I think you probably used curve fitting or something like this, there were a whole lot of control points in there. Also there is the constraint that the icon has to be rendered at 16 x 16 pixels, so this means we need  to cover as much as possible the 128-pixel grid so that there are more pixels used in lower res. So anyway, for now I just want a solution quick enough for me to re-submit a new package to the Chrome store and see what happen. It can be re-worked in the future, but currently I like this shield shape, so I will stick with this (and back to the original uBlock color).

**Comment by gorhill** [comment]
So I changed all icon and re-submitted a new package.

Could be something else... May be the Chrome store didn't like the screenshot I used for the add-on:

![ss-chromium-3](https://cloud.githubusercontent.com/assets/585534/7159065/7ec53db2-e34d-11e4-9dc8-d5c10d4002e3.png)

**Comment by harshanvn** [comment]
If it is so, then it will be hilarious reason of the decade!! :)

**Comment by dhowe** [comment]
I had a similar problem with an addon recently. Someone from Google eventually responded to my complaint and un-removed it, but I never figured out why it had happened in the first place. Its very frustrating and bad practice for Google. 

Anyhow, sorry if this was covered elsewhere, but why the separate projects in the first place (ublock and ublock-origin)?

**Comment by gorhill** [comment]
@harshanvn Yeah, just a tongue-in-cheek comment, I really doubt that would be the case. They deserve a whole lot of criticism though, as the Chrome store completely misrepresents itself when it says in writing in many places that they send "email with detail" as for the reason of a take down. I never received such email, and when I asked to have it send "again", no answer. So as far as I am concerned, it's plain misrepresentation from Google.

**Comment by tlu1024** [comment]
@gorhill 
> it's pure misrepresentation from Google

Yes, and if I may add this: One more reason to have Firefox versions of your extensions. If what happened to you turns out as a new Google policy (because they see it as a threat for their business model) it might be time to say good-bye to Chromium/Chrome. I sincerely hope that won't happen.

**Comment by RomanZhilich** [comment]
> it might be time to say good-bye to Chromium/Chrome

I disagree. Chromium != Google. There's a whole bunch of browsers based of Chromium opensource project. 
I personally use vanilla Chromium build and would be really sad to lose this extention - I'd rather update it manually.
Better option would probable be looking for an alternative way of distributing it to Chrome/Chromium users.

**Comment by gorhill** [comment]
It's back. So it was the logo apparently.

**Comment by dhowe** [comment]
Good news. Any further info on: "why the separate projects in the first place (ublock and ublock-origin)?"

**Comment by gorhill** [comment]
@dhowe  <https://github.com/gorhill/uBlock/issues/38#issuecomment-91871802>

Given there is already divergence in a way I disagree, I will keep mine going, and share it as I did with the other.

**Comment by PKOneTwo** [comment]
Yeah. but to clarify:
does this mean: you will continue toi develop this plugin for Chrome as you did before the seperation? (this will be a complete seperate developed project?)

And will your fork (ublock Origin) have all new features from the other ublock (being developed by chris) just with some bug fixes and some additions/substractions?

**Comment by tlu1024** [comment]
> It's back. So it was the logo apparently.

Whoopee!

**Comment by tlu1024** [comment]
@RomanZhilich 

> I disagree. Chromium != Google. 

Well, I'd say it is to large extent (although I don't know how much of the code is actually written by Google employees). Anyway, my point is that even with Chromium you are dependent on the Chrome Web Store unless you want to manually update all your extensions from, e.g, github.

But that discussion is pointless. uBlock Origin is back - that's all what counts.

**Comment by Ricardo1991** [comment]
I'm glad it is back on the store, adding it manually on developer mode is not practical

**Comment by AMKohn** [comment]
@gorhill I noticed the new icon and just found this discussion.  FYI, it almost certainly has absolutely _nothing_ to do with changes you did or didn't make.  I recently updated my own extension (iChrome, I'm not competition) and then had to release a bugfix immediately afterwards that was stopped for review for 5 days.  I had changed a total of ~6 characters.

I then looked into it and found a number of other developers with similar issues, new and old.

From what I can tell the CWS has bad filtering rules (reviews are automatically triggered) and Google shrank the team back in 2012.  That's also the reason why it's slow, poorly designed and impractical to use (try uploading descriptions in other languages, one at a time...).

Since it's the only way to reach the average Chrome user, we simply have to put up with, or boycott, it.  But a boycott would have to involve major extensions that they do want (basically not adblockers unless people would get really upset).  A better way to do that might be for adblocker devs to replace ads with campaign images for a day, like AdBlock did for April Fools.  The reach would be enormous, a lot of people would complain and Google would get bad press.

**Comment by gorhill** [comment]
For sake of completion, I received this email this morning:

    Dear Developer,

    Thank you for your email. We've reviewed your item and reinstated it. It is now available on the Chrome Web Store.

    Thank you for your cooperation,
    Google Chrome Web Store team

    ---------------------------
    Developer Terms of Service:
    https://developers.google.com/chrome/web-store/terms

    Program Policies:
    https://developers.google.com/chrome/web-store/program_policies

    Branding Guidelines:
    https://developers.google.com/chrome/web-store/branding

Doesn't add anything, if only to emphasize that there is still no explicit confirmation the problem was the logo.

**Comment by kintpuash** [comment]
@gorhill 

I'm not seeing the extension in the Chrome Store this moment? Am I missing something?

**Comment by gorhill** [comment]
> Not showing up in search

Interesting. Let's see if this last, maybe it's a side-effect of being taken down.

**Comment by RandomAcronym** [comment]
you can still get to it by googling "uBlock" at least, hopefully it will be added back to the CWS search index soon.

**Comment by kintpuash** [comment]
Appears to be back in search as of 30 minutes ago.

**Comment by vitaly-zdanevich** [comment]
The same story for me too - taken down without email.

**Comment by lewisje** [comment]
What are you referring to? If it's not your own fork of uBlock, it's not relevant for this thread.
