### ISSUE TITLE
Removing list from use doesn't disable filters unless purge of cache

### ISSUE THREAD

**Issue by 133794m3r** [gorhill/uBlock#500]
As it says above it refuses to work for me. If i disable a list it does not remoe those filters from use. they are still being used and will be continued t obe in use unless you purge all  caches.

**Comment by gorhill** [comment]
Are you clicking _"Apply changes"_ after you disable a list?

**Comment by gorhill** [comment]
Marked as _invalid_ until specific, detailed steps are provided to reproduce, along with all missing information (version, browser, os): <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

**Comment by 133794m3r** [comment]
Chromium 36, debian build, ublck 0.9.9
and as I said. You remove the filter from the active list. Hit apply
then it still is blockign items based on the list that is no logner active. Only way to resolveit is to purge all caches.

It was either easylist/fanboy's anoyance a those two are the ones I notice. YOu deactive it, and look at the request log and it's still blocknig based on their filters ven though their inactive.

Also the request log page is god awful now. It takes up ~100px of heght for the iframe page on it, whereas old ublock back before change tothe icon I beieve 0.8.4 if I remember right, the reuqest log was jsut fine and didn't take up such little space.

**Comment by 133794m3r** [comment]
uBlock Origin v0.9.9.0

**Comment by gorhill** [comment]
- Give me a filter list to deactivate.
- Give me a URL where the filter list to deactivate has an impact.
- Give me the specific filter which is involved.

I will try to reproduce when I have that information in hands.
