### ISSUE TITLE
Block sex and porn

### ISSUE THREAD

**Issue by ruy-benton** [gorhill/uBlock#502]
(Firefox user & fan)

I'm using this lists: 
http://rlwpx.free.fr/WPFF/hosts.htm to block sex & porn in kids computers.
http://rlwpx.free.fr/WPFF/hsex.7z        696.180 sites

and http://rlwpx.free.fr/WPFF/hmis.7z       521.790 sites         in other computers

I Download the files ... unpack and load in uBlock.

It work in Linux, Mac and many other O.S.

And would like to add:
https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

What is the procedure?

Put only the address and uBlock users follow my procedure?

Thank you for your great work Mr. gorhill,

Ruy

**Comment by gorhill** [comment]
> What is the procedure?

I would say create a special section at the bottom of the page for these links, but no _Subscribe_ link for whatever list is too large to reasonably subscribe, these should be added from local network or using `file:`-based URL.

**Comment by ruy-benton** [comment]
Thank you for your comments.

And you give permissions to put in the end of your page?

Regards,
Ruy

**Comment by gorhill** [comment]
> And you give permissions

Yes, the wiki is freely editable by anybody.

**Comment by ruy-benton** [comment]
Thank you for your comments.

In normal pages uBlock blocks porn subpages - third adds, etc

If we load the porn page he warns:
( strict blocking )
"...  the user will be given the choice to go back by closing the window or proceed to the web page by disabling strict blocking by selecting either: ..."


In your syntaxe - BLOCK ...

                         porn list   *   block     all

And we can't see the warning

Regards,
Ruy

**Comment by gorhill** [comment]
> And we can't see the warning

The warning popups only for static filters, not dynamic filtering rules.

**Comment by ruy-benton** [comment]
And the list "hosts.sex" is in static filters.

I ask if it possible to add a rule to block all this address ... no warning.

It's possible load the "hosts.sex" in dynamic filter ... ???

**Comment by gorhill** [comment]
> I ask if it possible to add a rule to block all this address ... no warning.

No, without warning there would be no way to work around of false positives, which would be a big problem.

uBlock is about fully disclosing what is happening in a user's browser. To me it seems you are looking for a sort of net-nanny extension. I do not have plan to turn uBlock into a net-nanny, this would actually go counter to full disclosure/full control philosophy.

**Comment by ruy-benton** [comment]
Yes it's better - net-nanny

It's the user - write the "hosts.sex   *   block     all"    not uBlock.
I ask if its possible to write a rule to INSERT in uBlock ... 
It's up to user insert or not ...

**Comment by gorhill** [comment]
There are users already using `hosts.sex * all block`, changing the behavior of uBlock would break uBlock for them.

**Comment by ruy-benton** [comment]
Sorry  ...
We only can put "source host" ... not a list ... no file
In static and dyn is an host or *.domain
Please explain ...


In https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock%27s-network-filtering-engine
"Context whitelisted" it's NOT of this one

Thank very much your attention

**Comment by Hrxn** [comment]
Highly misleading issue title, IMHO.

AKA 'clickbait'

**Comment by ruy-benton** [comment]
>Highly misleading issue title, IMHO.
>AKA 'clickbait'

I don't understand ... can you explain???
I'm using these lists and  successfully block !!!!
I'm using /etc/hosts and in others uBlock ...

And I inserted this lists in WIKI in the special section.

And I ask Mr. gorhill if possible block complete list.
I Admin and install Linux, Mac and W$n computers and servers.
