### ISSUE TITLE
[Enhancement] Open DOM inspector from Element Picker

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#503]
A button, which will open the DOM inspector (in a separate window?), within the Element Picker.
It fits there nicely.

It will also make the DOM inspector more usable and discoverable for new users.

**Comment by gorhill** [comment]
As per <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>: "Submit feature requests" -- even more so for new landed features.
