### ISSUE TITLE
[Enhancement/DOM inspector] Add the ability to show/expand only hidden DOM paths (red arrows)

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#504]
It would be a really good way to debug a site in real time (unhide/re-hide specific elements) on a given page.

Say you have a page which looks funny because a certain problematic element is being hidden, and it affects the layout of the page in a certain way you would like to revert/fix.

**Comment by gorhill** [comment]
As per <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>: "Submit feature requests" -- even more so for new landed features.
