### ISSUE TITLE
[Enhancement/DOM inspector] Ability to search in the DOM inspector

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#505]
It can be a nice addition to help a user find the right element he was looking for to block.

I am talking about some textbox which will be in the DOM inspector windows and will be able to show only the filtered trees.

**Comment by gorhill** [comment]
As per <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>: "Submit feature requests" -- even more so for new landed features.
