### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by foobar13373** [gorhill/uBlock#508]
You say "+0.0.0.1. New minor feature: +0.0.1.0. New major feature: +0.1.0.0" - but the new version is 1.0.0.0 and not the expected 0.10.9.3, so in fact you did a +1.-9.-9.-3 (or a +1.0.0.0 if you want clean numbers) instead of a +0.1.0.0.

Or do you treat the "." as a decimal mark? Which would be highly confusing, because a number is only allowed to have one of it in a mathematical sense. Which would also lead to a logical problem here (version numbers treated mathematical even though they are clearly non-mathematical because they have multiple decimal marks).

Not that I care about the actual number, but your statement and the number disagree, which is confusing. Without the statement I'd not be confused by the way and all would be fine. ;)

**Comment by seanrand** [comment]
Well, he did say "There is nothing extraordinary with this version "1.0".". So I guess he just wanted to get into the 1.x range, as 0.x is usually considered unstable in software versioning.

**Comment by gorhill** [comment]
> Without the statement I'd not be confused by the way and all would be fine

I don't know, to me `0.10. ...` looks weird, though I have no problem with `1.10. ...`. Given uBlock has been considered stable since a while now, let's just say it was probably time to reflect this in the major version number.

**Comment by Hrxn** [comment]
I agree, a 1.x ... version marks a stable, general availability release, whereas the 0.x ... range is used during development phase where usually a lot can change.

Since uBlock can be counted as stable, I fully support the new version scheme.
