### ISSUE TITLE
Which version of uBlock should I choose?

### ISSUE THREAD

**Issue by caizixian** [gorhill/uBlock#51]
I have no idea what the difference between the origin version and the new version is. Will them be different? Different in what way?

**Comment by Maxxee** [comment]
This is a valid question.

Although I am familiar with both versions/projects I cannot recommend one over the other, yet.

**Comment by gorhill** [comment]
Try both and decide for yourself? I can't decide for you, you are best placed to find out what **you** like.

**Comment by caizixian** [comment]
@gorhill @Maxxee 
I just want to know what the difference between them is.

**Comment by harshanvn** [comment]
@caizixian 

```
##### uBlock Origin
- It is maintained by Raymond (gorhill), the original creator of uBlock.
- It is considered feature complete. Hence not many features will be added. Unless Raymond feels something is missing.
```

##### uBlock
- Handed over to Chris by Raymond.
- I believe it is less aggressive than Origin version, as defaults were changed.
- UI Settings window is little more modern (i.e., buttons in it) than uBlock (it is my personal opinion)
- Firefox version has the ability to block elements from Dev Tools via 3D inspector

**Comment by gorhill** [comment]
@harshanvn 

I saw that the per-site switches are gone in uBlock.

**Comment by tlu1024** [comment]
> I saw that the per-site switches are gone in uBlock.
Indeed. I'm normally using your version but tested 0.9.3.5 Beta 2 of uBlock and noticed that, too. At least on Chrome, I haven't tested it on Firefox yet.

**Comment by harshanvn** [comment]
> I saw that the per-site switches are gone in uBlock.

Thanks Raymond for pointing it out. Updated my post, to reflect that.

> I haven't tested it on Firefox yet.

Its gone in firefox too.

**Comment by tlu1024** [comment]
@harshanvn 
> I believe it is less aggressive than Origin version, as defaults were changed.

Could you elaborate?

**Comment by harshanvn** [comment]
> I believe it is less aggressive than Origin version, as defaults were changed.
> 
> Could you elaborate?

Ahh, I dont see any differences in the settings window. I just wrote it becuase i remember reading some where at reddit. Maybe some one can confirm..

**Comment by Debeet** [comment]
I hope you don't mind me asking @gorhill but what was the point of all of this? Why abandon the project, give it to someone else just to fork it a few days later? I'm curious and I think I'm not the only one that is confused by the situation.
