### ISSUE TITLE
When allowing "All" the requests for a site, there are still requests that get blocked

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#510]
Steps to reproduce:

1) Enter: http://sitexw.fr/fuckadblock/
2) Allow the global (doesn't matter if allowing per site) "All" cell (mark with green) **and** block (mark the cell with red) all the "3rd-party scripts" globally (also doesn' matter is toggled per site).
3) Observe that there are still some request blocked.

An important note: If then (after following step 2 above) marking the **per site** 3rd-party scripts a no-op, there are **still** requests that get blocked, which should not happen if I understant the "All" row correctly.

Seems like the "All" row isn't getting the right importance in the blocking pipeline.

Reproduced on uBlock 0.9.9.3 and 1.0.0.0 with both Chrome and Firefox.

**Comment by gwarser** [comment]
All is least important

https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence

**Comment by Mikey1993** [comment]
@gwarser So how would you explain that when marking the **per site** "3rd-party scripts" with a no-op (when the global "3rd-party scripts" is marked red), combined with the "All" cell marked green, I still get some requests going in? per site rules should always take precedence.

So, to recap, the "All" row is the least important in the **Dynamic Filtering rules**, I get that, but it should not be inferior to the static rules... right?

**Comment by gorhill** [comment]
> 3) Observe that there are still some request blocked.

By design. The `3rd-party scripts` cell is more specific, so its rule overrides broader `all` cell.

> So how would you explain that when marking the per site "3rd-party scripts" with a no-op (when the global "3rd-party scripts" is marked red), combined with the "All" cell marked green, I still get some requests going in?

What does "requests going in" mean? I noop'ed the local `3rd-party scripts` cell after step 3, and the 3rd-party scripts on the page where neither allowed or blocked through dynamic filtering rules. `google-analytics.com` got blocked by a static filter.

**Comment by Mikey1993** [comment]
@gorhill You are right.. the 3rd-party scripts gets allowed/disabled as it should per no-op'ing, my bad..
But why is the "All" row isn't affecting the static rules? I would expect it to do so..

**Comment by gorhill** [comment]
> But why is the "All" row isn't affecting the static rules?

It is, unless a narrower rule says to disregard dynamic filtering, which is what `noop` is about.

**Comment by Mikey1993** [comment]
Yes, I see how it all fits now.
Sorry for bothering for nothing.
