### ISSUE TITLE
New Logger Tab / Windows - Output incorrectly formatted within Palemoon 25.5.0

### ISSUE THREAD

**Issue by MatrixUser** [gorhill/uBlock#512]
Hi gorhill, hi everybody,

since the early stages of the introduction of the new DOM inspector I have a problem using ublock in Palemoon 25.5.0

The best description of the problem are these two screenshots:

![palemoon-logger](https://cloud.githubusercontent.com/assets/13422609/8784910/73e575ec-2f24-11e5-9ffb-cde8a9d6bf98.jpg)

![palemoon-dcom](https://cloud.githubusercontent.com/assets/13422609/8784921/8378d44a-2f24-11e5-99dc-3dd5cdbd0c73.jpg)

As you will notice, the first textlines are partially covered by the icons. The problem occurs in the tabbed and windowed mode of the logger, and it exists since 0.9.9.4 dev3 or dev4 ( can't remember exactly )

When I am using the same version of ublock within firefox 39.0 EME free, everything works and looks like it should.

Any idea what is going wrong here ? If you need any additional information about the config of Palemoon, please let me now.

C.U. MatrixUser

**Comment by gorhill** [comment]
Fix in [dev build](https://github.com/gorhill/uBlock/releases).
