### ISSUE TITLE
My Rules sorted by hostnames

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#514]
From
```
test.google.com
test.youtube.com
www.google.com
www.youtube.com
```
to
```
test.google.com
www.google.com
test.youtube.com
www.youtube.com
```

**Comment by lewisje** [comment]
I think you meant something like sorting by base domains, because that first example actually *is* sorted by hostnames.

**Comment by vzjrz** [comment]
Yeah I realized my mistake, that's why i closed this issue. That and this is more of a feature request and I read those aren't really welcomed here.
