### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#52]
https://github.com/gorhill/uBlock#chromium needs to be updated, as uBlock₀ is no longer available on the chrome store.

On https://github.com/gorhill/uBlock/tree/master/dist#install, you can link to https://github.com/gorhill/uBlock/releases/latest instead of https://github.com/gorhill/uBlock/releases.

https://github.com/gorhill/uBlock/releases/latest links to the latest stable/non-dev version.

Not issue related, but thank you for developing & maintaining uBlock. I really appreciate it, and I'm sure many other people do too. I'm sorry that it became taxing, and felt like more of a chore than something to do in your spare time for fun.

**Comment by gorhill** [comment]
I am trying to reinstate it, too early to change this. I changed the icons, maybe they didn't like that it looked too much like the icons I crafted in the other project before the fork...

**Comment by hotdogman** [comment]
Alright, I apologize.
