### ISSUE TITLE
www.meo.pt and other sites

### ISSUE THREAD

**Issue by ruy-benton** [gorhill/uBlock#523]
www.meo.pt - we can't see the video ... and the only thing in logger is adds.
If we click in "+all cell" - green ... it's ok.
https://www.meo.pt/PublishingImages/MEO/videos/game-of-phones/game-of-phones.mp4

www.meo.pt - If the client  login from login.telecom.pt the page don't redirect to cliente.meo.pt. uBlock extension disable voila.

I'm trying to update some list (last update 2013).

http://www.mariosegura.com in right side ... lots of adds.
With "Element picker" I can hide the adds ... but I would like to block.
I can block one by one add ... but one line ...

**Comment by gorhill** [comment]
> www.meo.pt - we can't see the video ... and the only thing in logger is adds.

There is more than "ads" in the logger.

Using the logger, I see that EasyPrivacy's `/googleanalytics.js` prevents the video from loading. So it's a 3rd-party filter list issue. So report the issue to the maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Meanwhile, workaround filter: `||conteudos.meo.pt/Style%20Library/consumo/js/googleanalytics.js$script`.

> www.meo.pt - If the client login from login.telecom.pt the page don't redirect to cliente.meo.pt.

I don't know how to do this. In any case. Likely a 3rd-party filter list issue.

> http://www.mariosegura.com in right side ... lots of adds

I do not maintain filter lists, report to those who do.

**Comment by ruy-benton** [comment]
> Meanwhile, workaround filter: @@||conteudos.meo.pt/Style%20Library/consumo/js/googleanalytics.js$script.

Thank you for your knowledge and erudition.



> http://www.mariosegura.com in right side ... lots of adds

> I do not maintain filter lists, report to those who do.

I know ... "Element picker"  suggest an option to block ... sometimes only ###
