### ISSUE TITLE
web freezes

### ISSUE THREAD

**Issue by makarboy** [gorhill/uBlock#524]
When I go to these webs http://www.divxtotal.com/ 
http://www.mejortorrent.com/

The page freezes when I select a movie or a series and I cannot browse, I have to disable ublock Origin. I have tried with others addons like Adguard and the same problem happens. In the second link the problem is weaker, because instead of selecting the title of the movie/series, you select the picture there is no problem. The problem appears when you select the title.

**Comment by gorhill** [comment]
Marking as invalid until the reported issue complies with <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.
