### ISSUE TITLE
Non-packaged stock filter lists do not auto-update

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#528]
I think.. I have to look into this. For example, the Disconnect filter lists.

**Comment by ruy-benton** [comment]
Hi,
There is several issues with some sites.
One is if you have HTTP Referrer - Block, Custom



For ex. https://secure.fanboy.co.nz/r/fanboy-ultimate.txt
___________________________________________________________
Error 1010 Ray ID: xxxxxxxxxxxxxxxxxxxxxxxx UTC
Access denied
What happened?

The owner of this website (secure.fanboy.co.nz) has banned your access based on your browser's signature (xxxxxxxxxxxxxxx-mh5).
___________________________________________________________

**Comment by seanrand** [comment]
Prompted by this bug I just did a manual update with the logger open and noticed that all requests got filtered by the default-deny 3rd party rule. While somewhat commendable that uBlock applies rules even to itself, it's kinda unexpected. I didn't even think of whitelisting the filter list requests and only just noticed this by accident.

**Comment by gorhill** [comment]
> There is several issues with some sites.
> One is if you have HTTP Referrer - Block, Custom

Unrelated to uBlock. Some servers will block access if they think the client is a bot, and blanking the referrer may do this.

**Comment by ruy-benton** [comment]
>  with behind-the-scene * * noop

in "all" ( local ).

>"behind-the-scene * 3p noop" 

"3rd-party scripts" right
