### ISSUE TITLE
Website sliders not working with ubock orgin enabled

### ISSUE THREAD

**Issue by ElectricRogue** [gorhill/uBlock#529]
pcworld.com slider do not work when ublock origin is enabled.
Below is the one that I was trying to view.  Please look into it.

http://www.pcworld.com/article/2450480/10-amazing-data-driven-websites-that-will-change-the-way-you-see-the-world.html

And chartbeat.com design breaks with Peter Lowe’s Ad server list‎  enabled.

**Comment by gorhill** [comment]
These two EasyList filters are breaking the page:

EasyList: `.lazyload-ad.`
EasyPrivacy: `/b/ss/*&aqe=`

Report to the EasyList/EasyPrivacy maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Meanwhile, workaround filters:

    ! 24/07/2015, 18:42:55 pcworld.com
    @@||pcworldcommunication.d2.sc.omtrdc.net/b/ss/pcwmw-pcworld/$image,domain=www.pcworld.com
    ! 24/07/2015, 18:44:17 pcworld.com
    @@||www.pcworld.com/www/js/ads/jquery.lazyload-ad.js$script,domain=www.pcworld.com
