### ISSUE TITLE
[Firefox] Picker not working

### ISSUE THREAD

**Issue by JareD-OnGhub** [gorhill/uBlock#53]
Hey Gorhill, big time user first time posting an issue to you.

For whatever reason (uBlock₀ 0.9.4.2, FF 39.0a2, Mac OS X 10.8.5) I can't get the eyedropper-picker to work for whatever reason.

Thank you very much, and I will try to respond to requests for more information as I notice them.

--JaredDow

**Comment by Ricardo1991** [comment]
Works on my FF 40.0a1 (nightly)

Are you using other extensions?

**Comment by JaredDow** [comment]
it might be the "Addon-Bar Restoerd" addon that I have. I prefer uBlock in the bottom right, but it hasn't given me this problem before which is weird. Lemme do a quick test.

**Comment by JaredDow** [comment]
Yep, it was the addon-bar addon. Everything else works in it, so I'll just have uBlock₀ in the top right. Thanks for mentioning other extensions, I woud never have thought about it otherwise!
