### ISSUE TITLE
Chrome Web Store significant delay

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#530]
It's been a week since the release of 1.0.0.0, and Chrome Web Store still hasn't updated to this version. Is there any way to shorten this delay? How using bash and git can I get the latest release in some directory to load as unpacked extension?

**Comment by ialexsilva** [comment]
@mikhaelkh maybe its under review... @gorhill confim this?

**Comment by gorhill** [comment]
No, I did not submit it yet. As said before somewhere else, I will wait until I am comfortable that there are no regression bugs before publishing.
