### ISSUE TITLE
possibility of deploying custom lists?

### ISSUE THREAD

**Issue by vtknightmare** [gorhill/uBlock#531]
I was wondering if it was possible to deploy a custom list of 3rd party filters. I am deploying ublock origin across my domain and have also tweeted to you in hopes of hearing if there is a possibility of making this happen. By giving us systems guys such capability we can ensure our users are not hindered by the various lists while also tweaking as needed to enable access to the sites that might be blocked but needed.

**Comment by gorhill** [comment]
> have also tweeted to you in hopes of hearing if there is a possibility of making this happen

Sorry, I visit Twitter once in a while, so it's not the best place to context me, GitHub is really where I am most of the time.

Admin stuff is really not my expertise, so I am not sure about what can be done. What browser are we talking about here?

Someone on Wilders Security [posted a link](http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-55#post-2506161) to [this page](http://decentsecurity.com/ublock-for-firefox-deployment/), so it appears someone is deploying uBlock Origin, though I don't know if using only default or using custom settings.

**Comment by vtknightmare** [comment]
Thanks for getting back to me. Well, what I was hoping for was the ability
to push a file (or registry key) post-deployment which overrode the 3rd
party filters uBlock-0 used. This way, for example say we got a ticket
where we identified one of the default lists was blocking a site we needed
the users to be using, or we (the systems people) wanted to push exception
sites list i.e. ignore *.domain.com to ensure uBlock wasn't the problem
when debugging a webapp etc.

Do you think you could help? I am a systems engineer for an academic
institution and plan on rolling out your plugin to roughly 150+ systems
next week. Such a feature would come in quite handy in case of any
"oopsies" post-deployment.

Thanks and looking forward to your reply friend :)

**Comment by gorhill** [comment]
> push a file (or registry key)

uBlock as an extension can't access local file system or registry -- extensions are isolated from the system on which they run, except through whatever API the browser provide.

For Chromium-based browsers, it seems `chrome.storage.manage` is what is needed:

> Items in the managed storage area are set by the domain administrator, and are read-only for the extension; trying to modify this namespace results in an error.

For Firefox, an `about:config` could be used I suppose, if an admin could push such setting to all computers.

**Comment by vtknightmare** [comment]
Yes I can push about:config settings via CCK2. My question is what would
the setting(s) be to be able to override the 3rd party filters in use, or
to be able to push out custome domain exceptions as mentioned before.

**Comment by gorhill** [comment]
I am thinking about a JSON string, which would contains the uBlock settings which must override the local ones -- and that the layout of this JSON string would match that of the one created when uBlock creates a backup.

1. See if said setting in `about:config` is present;
1. If so, parse as JSON string;
1. For each property, overwrite the local one;
1. Once done, continue initializing uBlock the usual way;

So admin configure uBlock, create a backup, take backup and remove whatever is not meant to be locally overwritten, use the resulting JSON as a string in the `about:config` entry (after removing newlines?), and uBlock will make use of this entry according to steps above.

**Comment by vtknightmare** [comment]
That would be PERFECT! Looking forward to it.

**Comment by gorhill** [comment]
For Firefox, the following `about:config` entry is looked up:

`extensions.ublock0.adminSettings`

Must be valid, parsable json string. Layout is same as that created through uBlock's backup file. Admins can removed entries, those which are left to the user's choice.

For Chromium, the `adminSettings` entry is looked up in the `localStorage` of the extension itself.

**Comment by vtknightmare** [comment]
gorhill,

Is this already implemented, or to be implemented?

**Comment by gorhill** [comment]
It's implemented, in the latest dev build.

**Comment by CODYQX4** [comment]
By any chance, would it be possible to implement a "subscription" feature (it could work with the admin if needed).

Basically, subscribe to blocking rules, update them on server, extension fetches update. Admin could simply include the lists.

I manage lots of txt files with "profiles", especially because I use some browsers, but don't want to enable sync (if that even works), and it has gotten very tedious at this point to continue managing them, then importing all the changes (and removing old stuff) from the extension.

**Comment by gorhill** [comment]
> By any chance, would it be possible to implement a "subscription" feature (it could work with the admin if needed).

I will give some thoughts to this. One "bad" side effect though is this could delay uBlock's startup time if it needs to fetch settings from a remote location. But then this would affect only those who use such feature. In any case is sort of fit well with what has been implemented here.

**Comment by gorhill** [comment]
I did not receive feedback regarding this feature from OP, but I did receive sort-of feedback through issue  #592 (i.e. looks like it's working as intended).

**Comment by quertest** [comment]
I would like to use a Mozilla.cfg file to predefine ublock0 admin settings like this:
…
pref("extensions.ublock0.adminSettings.externalLists", "! Examples:\n! https://.....");
lockPref("extensions.ublock0.adminSettings.cloudStorageEnabled", true);
lockPref("extensions.ublock0.adminSettings.webrtcIPAddressHidden", true);
…
Is this possible?

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin>.
