### ISSUE TITLE
problem with one site

### ISSUE THREAD

**Issue by khafan11** [gorhill/uBlock#532]
hi , first of all thanks for your great extension :+1:  . 

i have issues with this site http://forum.persiantools.com/ when uBlock is on page not be complete loaded !! but when is off everything fine !
i use Google Chrome 64bit .

one more question uBlock are block ads from loading or just hiding them >?

**Comment by gwarser** [comment]
No obvious issues for me - third party list issue?
and
https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F

**Comment by khafan11** [comment]
can you try with user login and look at the topics ? editor to send post not be loaded
![postproblem](https://cloud.githubusercontent.com/assets/13505498/8893373/e8301222-33a2-11e5-9bc7-8221687e01aa.jpg)

**Comment by khafan11** [comment]
hello ? any idea ?

**Comment by gorhill** [comment]
Look in the logger to see what is blocked, and by what filter.

**Comment by khafan11** [comment]
with this filters
 EasyList‎ 
 EasyPrivacy‎ 
 Malware Domain List‎
 My filters‎ : 43 used out of 47
 uBlock filters‎ : 69 used out of 69purge cache
 uBlock filters – Badware risks‎ : 3 used out of 3purge cache
 uBlock filters – Privacy‎ : 4 used out of 4purge cache
 uBlock filters – Unbreak‎
 Malware domains‎

and this is looger

http://paste2.org/fxt8pHs8
![loog](https://cloud.githubusercontent.com/assets/13505498/8905723/d2c20cde-347d-11e5-9485-4c114a1be1fb.jpg)

**Comment by gorhill** [comment]
I do not have a login account for this site, and do not plan to create one just for this issue. I will have to guess what might be wrong. It's not uncommon that some sites will break if Google Analytics is blocked.

Try this custom rule: `@@||www.google-analytics.com/ga.js$script,domain=forum.persiantools.com`. See if this works. If not, will look for something else.
