### ISSUE TITLE
Block new twitch ads

### ISSUE THREAD

**Issue by extesy** [gorhill/uBlock#534]
According to https://www.reddit.com/r/ublock/comments/3cijxr/allowing_twitch_ads/ this new filter is needed to block new twitch ads:

> ||d2f8tie0ouoft.cloudfront.net$object,domain=www.twitch.tv

**Comment by Betsy25** [comment]
Specs:
>
Firefox nightly 42
Win7 x64
latest Ublock Origin dev version.

Weird, I'm using the default lists, and watch twitch.tv almost daily, and I don't remember ever seeing any ad....

**Comment by gorhill** [comment]
> According to https://www.reddit.com/r/ublock/comments/3cijxr/allowing_twitch_ads/ this new filter is needed to block new twitch ads

This should be brought up to _EasyList_ maintainers: <https://forums.lanik.us/viewforum.php?f=62&sid=d191d773519072fbfbab5c2ae21d822d>.

But they will need a case to reproduce. I [could not reproduce on my side](https://github.com/gorhill/uBlock/issues/478).

**Comment by lewisje** [comment]
Let's make it more general when you do send your idea to EasyList:

`||d2f8tie0ouoft.cloudfront.net$object,domain=twitch.tv`

**Comment by extesy** [comment]
I saw ads on twitch in the last few days, with many uBlock filters enabled, included all easylist ones. This custom filter from reddit helped remove them.

**Comment by gorhill** [comment]
Seen on Adblock Plus forum: ["Twitch.tv's new HTML 5 player prevents ads from being block"](https://adblockplus.org/forum/viewtopic.php?f=2&t=39725).

So apparently there is a new HTML5 player out there for TwitchTV, and this is where the issue would be. When I tried TwitchTV, there was no option for an HTML5 player, I was served with the message that I needed to install Flash to watch videos (Flash is disabled in my browser).

This new HTML5 player is likely the reason for those new ads appearing on TwitchTV. I don't know how to force TwitchTV use this HTML5 player though.

**Comment by extesy** [comment]
Looks like twitch is a/b testing this new html5 player right now. I get it on one machine but not on another, using the same account. No idea how to force enable it.

**Comment by gorhill** [comment]
I still can't make the site use HTML5 player on my side.

**Comment by anewuser** [comment]
I believe that this may be closed now. I just opened two videos and they played normally without ads.

**Comment by arrivance** [comment]
I can report that this issue is still occurring to me. https://www.twitch.tv/esl_csgo (The ads occur during timeouts during the stream). 

I got an ad for an Amazon series, which could be useful seeing as how Amazon is the owner of Twitch, and therefore is a 1st party.

**Comment by Hrxn** [comment]
Wait a second..
You can't block ads that are part of the stream itself. Don't know why there should be an Amazon ad on the ESL channel, but I wouldn't rule that one out. On the other hand, I'm pretty sure that ESL has ads in the stream.

Before we can proceed here, we need to distinguish between these two types of ads here.

**Comment by arrivance** [comment]
This is not an ad that is a part of a stream. This was a Twitch ad, the type that streamers can configure to occur during breaks or so. It isn't a part of the actual video stream, and it is clickable (to re-direct to the link).

The ad I received was for an Amazon original series (and Amazon Originals have been  the majority of any ads I've received), ergo my suspicion that it was a 1st party ad bypassing the filter. I think I'm right on this regard due to this post: https://blog.twitch.tv/introducing-surestream-for-a-better-video-ad-experience-on-twitch-3ca5ce3287c#.mhjbtvkfd

In any case, I've had luck based on a filter that a reddit user suggested, which was: www.twitch.tv##.player-ad-overlay.player-overlay

**Comment by Hrxn** [comment]
Yes, correct in this case. Just tried with an empty browser profile and saw those Amazon ads on some Twitch streams.
