### ISSUE TITLE
Strict blocking

### ISSUE THREAD

**Issue by hant0508** [gorhill/uBlock#536]
Doesn't show wich custom list contains this filter.

uBlock Origin prevented the loading of the page:
                 http://baddomain.net/malware
                       Because of the filter:
                         ||baddomain.net^
                                 found in:
 
![screenshot_27](https://cloud.githubusercontent.com/assets/12861787/8916671/cbaad010-34b5-11e5-8218-ca75c66c55b4.png)

**Comment by gorhill** [comment]
Are you using a custom filter lists which has no title?

**Comment by gorhill** [comment]
Never mind, I read more carefully.
