### ISSUE TITLE
Consistency between the buttons on the popup UI

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#54]
Hi Gorhill,

This is not a bug/feature-request, but rather UI <b>consistency</b> improvement in popupUI. 

Currently, if you hover over on site-switches, the buttons don't change (behaves as if it is in disabled state), unlike element picker and network request logger buttons, which changes to black color when you hover on them.

Is it possible to make it consistent for site based switches to behave as those two (i.e., network request logger, element picker icons)
###### If this is out of scope. I am sorry, please close it. I have another in mind (from long time), which i will not raise.

Thanks Again! for your  wonderful extension. And all the best for uMatrix development ;)

Thanks, Harsha.

**Comment by harshanvn** [comment]
Thinking a bit. Not sure, I will close it.
Please reopen if you feel it needs to be addressed. Thanks!

**Comment by gorhill** [comment]
I agree with the bug report. It's just a CSS rule to add somewhere.

Please do not feel like you are walking on eggshells when you submit a bug report. Bugs need to be fixed, that's not something I will ever argue against.

**Comment by harshanvn** [comment]
Thanks! :)
