### ISSUE TITLE
Site loading constantly with uBlock: eg. AdFox, AdRiver, Magna problem

### ISSUE THREAD

**Issue by olloff** [gorhill/uBlock#540]
So the problem is - most of the large sites in .ru and .ua segments of Internet (http://echo.msk.ru, http://lenta.ru, http://meduza.io) use one of these large banner networks (AdFox, AdRiver, Magna). 

With uBlock enabled these sites **would be loaded constantly except I stop it manually**. Why its bothers me - there are plenty of userscripts/browser addons which can run own code after onPageLoad event only (or so).

AFAIK all of these networks use similar way to create banners (on example of http://ria.ru/science/20150723/1143577829.html): 
* there are async js code which is used to create an element (div, xmp or iframe);  
* that code is hosted on corresponding domain (six third-party scripts hosted on http://content.adriver.ru);
* most of the ad content is third-party too (elements from http://colo1.adriver.ru);
* async code was driven by js code hosted on home domain (see http://ria.ru/js/adriver.core.2.js);
* by blocking site which host content of the ad (colo1.adriver.ru) or its async code (content.adriver.ru) we rush init code (adriver.core.2.js) to constantly request async code and page would not be loaded.

For now I use brute force: I allowed all content from adriver.ru, but use primitive userscript to find and delete all elements corresponding to these banner networks - https://gist.github.com/olloff/3af0a483f55d012137a1

Obviously its resource demanding and the main problem (third-party scripts) is intact. So there I need your help, is there a way to block some scripts by name to stop init code to be executed? Or at least to clean page form unwanted elements in a faster/"lighter" way?

Btw, @gorhill, you've done a fantastic work building a cleaner web, something I really appreciate.
Thanks.

**Comment by gorhill** [comment]
I tried with provided URL, <http://ria.ru/science/20150723/1143577829.html>, + _RU Adlist_ and I could not reproduce the reported issue. What do I need to do to reproduce it?

**Comment by olloff** [comment]
Could you please to assure there is any request to ad.adriver.ru or http://ria.ru/js/adriver.core.2.js from that page? If not, these banner networks could serve different content based on geolocation.

You can try some other sources: 
* http://www.colta.ru/articles/society/8043
* https://slon.ru/posts/54612

Both of them listed some content from adfox.ru (working similar way as in my example - small in-page js code downloading async code to create banner elements).

Following sources are working, because some scripts from adfox.ru was whitelisted as workaround by ru.adlist community so the ad content was blocked:
* https://meduza.io/feature/2015/07/24/istorichka-v-youtube
* http://www.vesti.ru/doc.html?id=2646608
* http://w-o-s.ru/news/15870

Its working solution but problem with third-party scripts remains. You need to block any content from adfox.ru to reproduce the problem

Its not the browser-related issue, results can be reproduced either on all (I almost sure) versions of Google Chrome or Mozilla Firefox since 2011. Personally I started getting this issue around 2 years ago but was too lazy (and got a somewhat working solution pretty fast) to ask for help.

**Comment by gorhill** [comment]
> http://www.colta.ru/articles/society/8043

I could reproduce with this one. Though I see no more network requests in the logger, the browser shows the site has never fully loaded.

> Its not the browser-related issue

It's not a uBlock-related issue either, it's the page itself the issue. Blocking inline script for that page fix that specific problem, if that solution is acceptable to you. In any case, this is an issue with the site not behaving properly if some of its stuff is blocked.

**Comment by gorhill** [comment]
> http://w-o-s.ru/news/15870

For that site, the issue is present even without uBlock.

So all these are really site-side issues, not uBlock issues.

**Comment by olloff** [comment]
I do realize its have nothing with uBlock, sorry if I misguided you. And its most certainly the way ad-networks force users to whitelist certain domains.

An enhancement or an issue, can you, please, bring expert opinion to this problem? **It is possible to add some way to disable/override init scripts or certain functions** of these banner networks so these scripts can be disabled? 
uBlock already can disable inline scripts or block certain script-files and its really helpful; for example, http://ria.ru/science/20150723/1143577829.html loaded normally without inline scripts (though it breaks some page functions as go-to-top button, etc.). **If individual inline scripts or functions can be disabled** as-well, it will be awesome.
I think its not only me who can find that feature useful. 

> http://w-o-s.ru/news/15870
> issue is present even without uBlock

I doubt its the same issue, because I can't reproduce it without ad-blocker. But its a js-rich website on a custom (i think so) engine so I assume it can't be testcase anymore.

**Comment by olloff** [comment]
Two more example to clarify: 
* https://meduza.io/feature/2015/07/29/ig-prevraschaetsya-v-obychnuyu-stranu-na-samom-dele-net
There are 7 inline script-nodes over the page. Third one is for AdFox initialization (look for FuckingAdFox() or AdFox_getCodeScript() functions). Unfortunately it missing id so I can't try to delete script-node.
* http://lenta.ru/news/2015/07/29/cat/
On this page functions AdFox_getCodeScript() and adfoxStart() hidden into http://icdn.lenta.ru/assets/core-ae2a0b3722ca96df9f2639cefa4ee00b.js file. Unfortunately that script-file supports animation and other basic webpage functions, so it can't be blacklisted.

Can it be possible to disable that certain script node without altering other? Or can you suggest the way to override content of FuckingAdFox()/adfoxStart() or AdFox_getCodeScript() functions?

I really ashamed to bother you, sorry for that.

**Comment by gorhill** [comment]
> Can it be possible to disable that certain script-node (within inline scripts or 1-st party src scripts) without altering other?

For 1st-party scripts, dynamic URL filtering is a way to quickly disable a specific script. For inline script, it's not possible. I have ideas I wanted to test a while ago but never found the time to do so. I may tried them eventually, but that would be very experimental and I am completely unsure about the results.

**Comment by olloff** [comment]
Thanks for the answer.
I expect that, it would be impossible that nobody show any interest to this topic before. I'm nothing to lose, so feel free to ask if I can help you with something.

> For 1st-party scripts, dynamic URL filtering is a way to quickly disable a specific script.

To be a little specific, its also not possible *to disable a specific script tag* inside certain 1st-party script, right? Except to copy all content of that 1st-party script (wiping some functions) and than inject it again to the page.

**Comment by olloff** [comment]
Just tried the 7970f4dc70cbc878e0c2b616ef8e35e10edddf16 and it works awesome! 

New cosmetic filters allow to completely deal with inline ad-scripts e.g. test cases

    http://www.colta.ru/articles/society/8043
    https://slon.ru/posts/54612

@gorhill, you're the best!

**Comment by gorhill** [comment]
I made the syntax a bit more flexible in latest dev build: you can now also use a plain string to match. If the string in `contains(...)` is surrounded by `/`, it will be treated as a regular expression, otherwise it will be treated as a plain string. I figure being forced to use a regular expression could be tedious when we only want to match a plain string in the script text.

**Comment by gorhill** [comment]
Solved in uBlock Origin 1.2.0 with the [new inline script tag filter](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering).
