### ISSUE TITLE
Safari Version for ublock/gorhill

### ISSUE THREAD

**Issue by phone8588** [gorhill/uBlock#547]
With gorhill not contributing code to chrisaljoudi/uBlock  - can we now expect there will be a Safari version for gorhill/ublock - especially with Apple's upcoming blocking API in Safari on El Capitan? It is a pity to not get the latest features being added to the Chrome/Firefox versions on Safari.

**Comment by gorhill** [comment]
Duplicate of #64.

**Comment by Zearin** [comment]
> With gorhill not contributing code to chrisaljoudi/uBlock - can we now expect there will be a Safari version for gorhill/ublock - especially with Apple's upcoming blocking API in Safari on El Capitan? It is a pity to not get the latest features being added to the Chrome/Firefox versions on Safari.

:+1:
