### ISSUE TITLE
delete requests counter

### ISSUE THREAD

**Issue by laozi83** [gorhill/uBlock#550]
Hello (FireFox 39.0)
How do I delete or set to zero the counter of blocked requests (page and always)  ?
Thanks

**Comment by gorhill** [comment]
There is no way, it's no such feature.

For Chromium-based browsers, you can remove/reinstall the extension (backup your settings so you can restore).

For Firefox-based browsers, remove the extension, delete the `ublock0.sqlite`, which location is documented [here](https://github.com/gorhill/uBlock/blob/master/dist/README.md), then reinstall uBlock.
