### ISSUE TITLE
Bring back 3rd-party css/images option in dynamic filtering (aka 3p-passive).

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#553]
As title says. I don't want to temporary turn off blocking or try to find the proper rule in dynamic filtering and enable it to browse the page without breaking it (`css/images`). The better solution (for me, of course) was enabling `3rd-party css/images` globally until you remove it :/ Can you this option bring back, please?

**Comment by gorhill** [comment]
> I don't want to temporary turn off blocking

`3p-passive` had nothing to do with turning off blocking.

`* * 3p block` + `* * 3p-passive noop` ~= `* * 3p-script block` + `* * 3p-frame block`.

So if you have:

    * * 3p block
    * * 3p-script block
    * * 3p-frame block

Setting a local `noop` for _3rd-party_ is similar to setting a local `noop` for _3rd-party passive_. So it was redundant, and as such, cluttering the (space-constrained) UI

**Comment by Piter432** [comment]
I still prefer to `allow` `3rd-party css/images` globally instead of temporary turning off blocking or setting temporary `noop` or `allow` in `3rd-party` rule when site is "broken" :P

**Comment by seanrand** [comment]
Then only block 3rd-party scripts/frames globally and turn off the global 3rd party deny rule.

**Comment by Piter432** [comment]
@seanrand That options was the best for me (and propably not only for me), but @gorhill removed it :/

**Comment by RoxKilly** [comment]
@Piter432 What @seanrand said is still possible. You can achieve what you want without using `3p-passive`.  
1) Globally block `3rd-party scripts` and `3rd-party frames`
2) Globally unblock or noop `3rd party`

@gorhill What's the difference between a `noop` setting and leaving a filter unset?  My understanding is that they have the same effect (allow unless instructed otherwise by a static filter)

**Comment by gorhill** [comment]
> What's the difference between a noop setting and leaving a filter unset?

None, the default state of cells is noop. Explicit noop rules are needed only to override a lower precedence block or allow rule.

**Comment by Piter432** [comment]
So, @gorhill? Will you bring it back, please? :)

**Comment by gorhill** [comment]
I do not intend to bring this back, for [the stated reason above](https://github.com/gorhill/uBlock/issues/553#issuecomment-126946551):

`* * 3p block` + `* * 3p-passive noop` ~= `* * 3p-script block` + `* * 3p-frame block`.

In both cases, 1 single click is necessary to unblock 3rd-party passive content.

**Comment by Piter432** [comment]
Hmm, okay. Let it be as it's now, but I think I'll be right soon :)
