### ISSUE TITLE
uBlock origin extension keeps getting disabled

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#554]
From Chromium issue tracker, copied here so that users can find out more easily about the corresponding Chromium issue, <https://code.google.com/p/chromium/issues/detail?id=515275>:

> It seems to be randomly getting disabled.

Also, often seen in the feedback section of the Chrome store. For examples:

> As others have reported, this extension periodically gets disabled for no apparent reason. I can understand if it was due to permissions increases, but this has happened at least half a dozen times so that seems unlikely to be the reason.

or

> the extension sometimes disable by itself, usually whenever I turn on PC/laptop the next day at work.

etc.

**Comment by Havokdan** [comment]
It may be related, maybe not, but I installed Opera 31, and extensions that I used with the "Load unpacked extension" no longer work, including Ublock and Umatrix, had to use the option that is next to make work.

**Comment by Alaric-VISIGOTH** [comment]
Same issue for me but Chromium based browsers delete the extension. I have sync functions disabled.

**Comment by gorhill** [comment]
[moved from issue #594, more chance to be related to issue here]

I just has a case with Chrome 46.0.2478.0 were uBlock went completely blank, it was no longer blocking anything. There was an exception logged in uBlock's dev console. Had to restart the extension. Will investigate, not sure how it happened, I force refreshed the Youtube page a couple of time before this happened.

**Edit:** I can't reproduce. ~~I don't see this related to the currently reported issue anyway.~~ For whatever reason, it appeared uBlock was restarted by the browser, and it seems the restart didn't go well because it's as if the `privacy` permission in the manifest was not seen by the browser, and this caused uBlock to fail to initialize properly. This could be related to some users who have reported uBlock disabling itself as if permissions had changed: <https://code.google.com/p/chromium/issues/detail?id=515275>.

**Comment by gorhill** [comment]
See ["Software known to have uninstalled uBlock Origin"](https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin).
