### ISSUE TITLE
Please add option to block sites from tracking battery status

### ISSUE THREAD

**Issue by wolftune** [gorhill/uBlock#557]
See http://www.theguardian.com/technology/2015/aug/03/privacy-smartphones-battery-life

**Comment by gorhill** [comment]
This does not fit that well in uBlock, which is first a network request blockers.

Even blocking that one specific manner of gathering bits for fingerprinting, there is so much more other sources of bits which can be used for fingerprinting purpose (like canvas fingerprinting) -- this would have to be a large list, and quite a lot of (hopefully free of bad side effects) hacky javascript code.

The best way to protect against this specific one and all other bit-gathering-for-fingerprinting-purpose is already in uBlock: block 3rd-party scripts/frames by default. Nowadays, the most likely sources bent on tracking users are the 3rd-party ones, through their scripts. Whatever 1st-party is found to be gathering fingerprinting bits can be blocked with static filtering (aka EasyPrivacy).

What I am saying is caring about this one specific method of fingerprinting is pointless if not caring for all of them, which is a huge undertaking, worthy of its own extension.

**Comment by wolftune** [comment]
Okay, thanks for the thorough reply. Personally, I do the 3rd-party block-by-default already. And, I'll be honest: I wanted this to be brought to attention in case it made sense to do something about, but I'm not personally worried about it. I'm *more* annoyed on a practical day-to-day basis with various things I may do online affecting my online experience and with blocking ads than about the hardest-core version of privacy, although it all matters somewhat.

Thanks again for uBlock

**Comment by gorhill** [comment]
By the way, I meant but forgot to mention [Chameleon](https://github.com/ghostwords/chameleon), for which such feature request would be more natural. Looking at the feature set of the extension, you can see there not really any direct overlap with uBlock, so they probably both complement each other.
