### ISSUE TITLE
dynamic filtering documentation screenshot incorrect?

### ISSUE THREAD

**Issue by jawz101** [gorhill/uBlock#558]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

This screenshot under explaining how to create a noop rule for YouTube doesn't make sense.  It looks essentially like the screenshot 2 images above it which shows all 3rd party frames are blocked so I don't understand what has changed.

https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/df-qg-07.png

**Comment by jawz101** [comment]
... now I see what you did.  I guess I don't know why you'd even include this first solution because it's not the solution you'd want to do anyways.

**Comment by gorhill** [comment]
> I don't know why you'd even include this first solution because it's not the solution you'd want to do anyways.

It serves to explain one concept of dynamic filtering: local rules override global ones.
