### ISSUE TITLE
Please Remove SourceForge from your badware filter.

### ISSUE THREAD

**Issue by mikeloeven** [gorhill/uBlock#561]
I found myself constantly blocked from accessing source-forge after installing Ublock Origin My personal opinions aside blanket blocking of entire websites that are not ad related goes beyond the expected scope of a Ad block utility and is quite invasive. The lists you use contain false positives and the blanket block of sourceforge proves that there is a personal or political bias in the block lists that is simply not acceptable. Marking a website for distribution of open source software as BadWare is almost comical because its very hard to hide malicious software when many of the projects have the full source code available

**Comment by gorhill** [comment]
> constantly blocked from accessing source-forge after installing Ublock Origin

Read carefully the choices offered to you: you can permanently disable strict blocking for `sourceforge.net`, just click the _Permanently_ button:

![strict blocking](https://cloud.githubusercontent.com/assets/585534/8160013/14466ca0-133a-11e5-8d3c-28169288f35a.png)

Manually enter the rule `no-strict-blocking: sourceforge.net true` in the _My rules_ pane in the dashboard, this will permanently disable strict blocking of `sourceforce.net`.

> goes beyond the expected scope of a Ad block utility

As the creator of uBlock, I reserve the right to decide what is [the scope of uBlock Origin](https://github.com/gorhill/uBlock/wiki/Blocking-mode):

> uBlock Origin is not an "ad blocker", it is a wide-spectrum blocker, which happens to be able to function as a mere "ad blocker".
