### ISSUE TITLE
Statcounter ad not blocked (but blocked with same filters in AdBlock)

### ISSUE THREAD

**Issue by Ryan-Goldstein** [gorhill/uBlock#562]
When logged into statcounter.com, an iframe is loaded on the left side with this URL: https://statcounter.com/frame/?side

An ad appears there with image URL http://www.statcounter.com/images/advertise/gain-new-customers.png linking to http://statcounter.com/overflow

The applicable EasyList filter is set, and per this EasyList forum thread I started, it should be blocked: https://forums.lanik.us/viewtopic.php?f=62&t=24411&p=74659

I disabled all other extensions, and it still appears. Any ideas? Seems to be a uBlock bug.

Platform is latest Chrome stable on both Windows 10 and Linux Mint 17.2. AdBlock (https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom?hl=en) blocks this ad with its default filters, uBlock doesn't.

Thanks.

**Comment by gorhill** [comment]
Explanation of why this happens:

- uBlock Origin comes with _"Peter Lowe’s Ad server list‎"_ enabled.
- `statcounter.com` is wholly blocked by _"Peter Lowe’s Ad server list‎"_.
    - This causes `statcounter.com`'s own web site to be broken.
- Consequently, _"uBlock -- Unbreak"_ has an exception filter for 1st-party requests for `statcounter.com`
- This exception filter happens to cancel the block filter `/advertise/*` in _EasyList_.

Hence `http://www.statcounter.com/images/advertise/gain-new-customers.png` is not being blocked.

So it's really an issue of filter lists conflicting. You would get same above issues if you were using _"Peter Lowe’s Ad server list‎"_ with ABP.

Possible solution:

- Disable _"Peter Lowe’s Ad server list‎"_ and _"uBlock -- Unbreak"_ to get the exact same blocking behavior as ABP with _EasyList_ + _EasyPrivacy_.

Use a custom filter ` ||www.statcounter.com/images/advertise/$important`.

**Comment by Ryan-Goldstein** [comment]
Cool, thanks - adding the custom filter worked in hiding the image. Per the request log:

14:03:12		||www.statcounter.com/images/advertise/$important	--	image	http://www.statcounter.com/images/advertise/gain-new-customers.png

However, it still appears to be downloaded, then hidden. This is causing a mixed content SSL warning - lock icon with a yellow triangle. Any idea how to block the image download entirely, instead of just hiding it?

Thanks again!

-Ryan

**Comment by gorhill** [comment]
> However, it still appears to be downloaded, then hidden

The image is blocked, what you see is probably the `iframe` being collapsed:

> https://statcounter.com/frame/?side

You could create a filter for this `iframe`, this might actually be a better solution than the other filter:

    ||statcounter.com/frame/?side$important

Or even

    ||statcounter.com/frame/$important

If you think there is no bad side-effects for using this broader block filter.

**Comment by Ryan-Goldstein** [comment]
Brilliant; the first custom filter did it! Thanks so much for your quick and helpful responses.
