### ISSUE TITLE
Automatic Filter Updates

### ISSUE THREAD

**Issue by heinst** [gorhill/uBlock#563]
Would it be possible to automatically check for filter updates and update them once a day? Not an expert in the Chrome Extension API so not sure if it is possible

**Comment by gorhill** [comment]
> Would it be possible to automatically check for filter updates

This feature is already part of uBlock:

![c](https://cloud.githubusercontent.com/assets/585534/9074952/7d894b72-3add-11e5-8705-bee5e41ded54.png)

**Comment by heinst** [comment]
Ah wow....didn't even see that, sorry!
