### ISSUE TITLE
How to view "the items has been blocked" and "the items can be block"?

### ISSUE THREAD

**Issue by phuc365** [gorhill/uBlock#564]
I love uBlock Origin, and I have a small question about it: How to view "the items has been blocked" and "the items can be block"?

<b>Thank you for your interest.</b>

**Comment by gorhill** [comment]
> How to view "the items has been blocked" and "the items can be block"?

I don't understand the question.

**Comment by phuc365** [comment]
I wanted to know what has been blocked on the page (when using uBlock0)

**Comment by gorhill** [comment]
Here: <https://github.com/gorhill/uBlock/wiki/The-logger>.

**Comment by phuc365** [comment]
Thank you very much :)
