### ISSUE TITLE
Brazilian Walmart is incorrectly blocked?

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#567]
http://www.walmart.com.br/ doesn't work if blocking is enabled.

**Comment by gorhill** [comment]
Invalid issue report, because:

- What exactly "doesn't work"?
- Browser/version?
- uBlock version?
- Filter lists selected?
- Any other uBlock settings which differ from default ones?

**Comment by SoniEx2** [comment]
The website doesn't work. The menus don't load and stuff. uBlock Origin 1.0.0.1, firefox nightly, arch linux.

Filter lists:
```
My filters
uBlock filters
uBlock filters - Badware
uBlock filters - Privacy
uBlock filters - Unbreak
EasyList
Peter Lowe’s Ad server list‎
EasyPrivacy
Malware Domain List
Malware domains
```

Settings:
```
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
I am an advanced user
[ All privacy settings ]
```

(If private browsing is relevant: private browsing)

**Comment by gorhill** [comment]
> The menus don't load and stuff

This is not very specific, so I am still left to guess you maybe mean the images meant to appear in the menus do not appear. In such case, it is a 3rd-party filter list issue:

EasyPrivacy's `/realmedia/ads/*` is blocking network requests from `http://oasc14.247realmedia.com/RealMedia/ads[...]`. Hence report the issue to EasyPrivacy maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Possible workaround meanwhile: set a local `allow` rule for `oasc14.247realmedia.com`, or use custom static filter `@@||oasc14.247realmedia.com/RealMedia/ads/$domain=www.walmart.com.br`.

**Comment by SoniEx2** [comment]
I mean the actual menu contents don't load.

**Comment by gorhill** [comment]
> I mean the actual menu contents don't load.

Load fine on my side, using above `allow` rule:

![c](https://cloud.githubusercontent.com/assets/585534/9093843/6b12b0e2-3b7c-11e5-9a71-c0f17bea04db.png)

So if this does not work for you, you have undisclosed custom settings causing this.
