### ISSUE TITLE
Kissanime.com evading ublock

### ISSUE THREAD

**Issue by 49c29fa9** [gorhill/uBlock#568]
Can you please tell me how to block ads on Kissanime.com?

It blocks ads but the site shows an anti-adblock message and stops the video from playing further. 

If you want a specific video

Try this : http://kissanime.com/Anime/Sword-Art-Online-II/Episode-024

Ublock have all filters checked including the antiadblock filters.

**Comment by anewuser** [comment]
Select the HTML player and pick the desired resolution. When the episode starts playing, right click on it and use the "View video" context menu option.

**Comment by gorhill** [comment]
Sorry, I don't maintain filter list.

**Comment by gorhill** [comment]
<https://adblockplus.org/forum/viewtopic.php?f=2&t=39850>

**Comment by vzjrz** [comment]
Maybe also try this greasemonkey script: https://greasyfork.org/en/scripts/4900-kissanime-anti-adblock-blocker
