### ISSUE TITLE
Firefox has started blocking unsigned extensions

### ISSUE THREAD

**Issue by pcause** [gorhill/uBlock#569]
I run from Nightly, and I installed the latest and I just noticed that it is disabled.  Firefox says it is disabled because it is unsigned.  Mozilla announced intent to do this and apparently they have started to enable.  If you use nightly or developer addition you can toggle (make true):

xpinstall.signatures.required

and install the latest from github.  Mozilla site says that if you use released or beta this option isn't available.

**Comment by Bec-de-Xorbin** [comment]
Why don't you install it from here? https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by pcause** [comment]
I usually pull development releases so I've just pulled from github.

**Comment by AmrEldib** [comment]
Maybe documentation should be updated to add the xpinstall.signatures.required fix for people who are installing the unsigned release.

**Comment by 5t3f4n** [comment]
While having self-hosted (i.e. hosted outside of AMO) extensions signed is possible, it still requires review from Mozilla. I think gorhill (when on a roll) releases new builds at a pace that is too fast – sometimes two in a day. Unless the review process is improved.

@AmrEldib 
>the xpinstall.signatures.required fix

This won't be possible in Firefox Stable or Firefox Beta after the next update.

**Comment by wohali** [comment]
I installed from https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ and it still lists as unsigned. Am I doing something wrong?

**Comment by gorhill** [comment]
uBlock Origin from AMO is signed, so you should not have warning -- all extensions from AMO are signed.

**Comment by gorhill** [comment]
I created a development channel on [uBlock Origin's page on AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/): scroll to the bottom, expand _Development Channel_.

My understanding is that the AMO-hosted version is signed, and it will auto-update whenever I push a new beta version.

**Comment by pcause** [comment]
I just went there and looked and the developer channel in the site says you can't install these versions of uBlock on released versions of Firefox.  From what I've read released means released and beta.  Not an issue for me as I use nightly, but may be for others.


![ublock](https://cloud.githubusercontent.com/assets/1071479/9236636/06397c8a-4114-11e5-89ce-877009b8f962.JPG)

**Comment by gorhill** [comment]
> the site says you can't install these versions of uBlock on released versions of Firefox

I know, but somehow I could install it fine on Firefox 40 on my side (Linux).

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm <x-apple-data-detectors://2> I keep my lights
on!
We have really cool stuff!
Have a good weekend!

On Wednesday, August 5, 2015, pcause <notifications@github.com> wrote:

> I run from Nightly, and I installed the latest and I just noticed that it
> is disabled. Firefox says it is disabled because it is unsigned. Mozilla
> announced intent to do this and apparently they have started to enable. If
> you use nightly or developer addition you can toggle (make true):
>
> xpinstall.signatures.required
>
> and install the latest from github. Mozilla site says that if you use
> released or beta this option isn't available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uBlock/issues/569>.
>


-- 
Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052

**Comment by kintpuash** [comment]
On the new uBlock development channel installed from AMO on Firefox beta (41). Extension updated earlier today. No warnings in addon-manager, no problems.

**Comment by gwarser** [comment]
![ubo](https://cloud.githubusercontent.com/assets/886325/10868407/0820ee5c-808e-11e5-8d7a-abe952329ca6.png)
Fx 43 on win7, uBO from dev channel 1.3.3b2
xpinstall.signatures.required;false

**Comment by yupi2** [comment]
@gwarser see https://github.com/gorhill/uBlock/issues/569#issuecomment-130446739

**Comment by magicgoose** [comment]
Unfortunately, regular Firefox doesn't allow turning off this blocking.
Maybe it's time to switch to GNU IceCat…
