### ISSUE TITLE
uBlock makes some web pages to not comlete loading

### ISSUE THREAD

**Issue by SBI-boy** [gorhill/uBlock#572]
Hi, I'm a Firefox user, I recently switched from ABP beacause of the overhead it causes. Noticed form the first moment I'm using this addon that some web pages with content blocked never end to load, I don't think it's normal... The only way to make that web page to end loading is disabling almost all filters or powering off the addon.
Here is an example what I'm talkng about http://imgur.com/tr9LVp9
Tab 1: disabled most of filters
![sin titulo](https://cloud.githubusercontent.com/assets/13672854/9104803/2a522088-3bd6-11e5-8d7c-16b76936fb08.png)

Tab 2: no idea why home page of this site it's not loading completely
Tab 3: same domain, another section, finished loading by disabling some filters
Tab4: no filters disabled, din't end to load

**Comment by gorhill** [comment]
Unable to reproduce using default settings. Provide more details about browser version, uBlock version, filter lists, and all other settings which are not the default ones.

**Comment by 5t3f4n** [comment]
I don't know if this is related or not but seeing as uMatrix and uBlock Origin are siblings it might be.

With uMatrix enabled, any GitHub page never gets "Done" for me but says "Stopped" instead (in the status bar). I have to allow `Other` from `api.github.com` in order for the page to finish loading as expected. Maybe you have something that blocks this in uBlock Origin?

**Comment by gorhill** [comment]
Also, by the way, blocking stuff from web pages _can_ lead to this sort of behavior, so this must be considered a normal side effect of using a blocker. But as said, in the current instance I was not able to observe this behavior using OP's URLs seen in pic (please post textual URLs next time, more convenient than transcribing from pic).

**Comment by SBI-boy** [comment]
Hi again, I think it's a aproblem with my FF proxy configuration, somehow an addon changed that configuration, I reverted the change and now everything it's quite normal

**Comment by PalZer0** [comment]
I think I've managed to find a solid repro case. I've been running into this issue myself and it's only been since I installed the Hola extension (http://www.hola.org).

**Comment by SBI-boy** [comment]
Yep, I forgot to mention that changing to default the proxy config just was a temporary fix, had to disable hola to avoid issues with ublock

**Comment by PalZer0** [comment]
Yeah I was going to post a new issue that mentions Hola but I saw yours and thought that I'd chime in as I was seeing the same thing as you.

Hopefully @gorhill has something to work with now.

**Comment by 5t3f4n** [comment]
@SBI-boy and @PalZer0 
You might want to check [this](http://adios-hola.org/) out.
