### ISSUE TITLE
Picked hiding filters stop working after page refresh

### ISSUE THREAD

**Issue by TheRealMarnes** [gorhill/uBlock#573]
I've run into this problem several times now:
-go to website
-see annoying content
-pick element to hide and create filter
-rule is saved in My filters, element disappears from page
-refresh
-element is back

One example is on facebook:
http://goo.gl/rLVWHf
My filter list has contained the #rightCol filter for ages now but rightCol still shows up: http://goo.gl/Qn1hmT

If I let it make the filter again, I get

    ! 06/08/2015 14:12:49 https://www.facebook.com/?_rdr=p
    www.facebook.com###rightCol

And the column vanishes from the page. When I refresh the same page, `rightCol` is there again.

My filters is enabled on the filter list page, though it does say "142 used out of 147", so I'm wondering why some filters aren't being used and which.

**Comment by gorhill** [comment]
Browser/version, uBlock version?

**Comment by TheRealMarnes** [comment]
Firefox 39, ublocko 1.0.0.1
Filter lists: http://goo.gl/0f9Diq
Settings: everything except color-blind enabled
I can't immediately think of a page where it happens besides the main page on facebook. I recall other glitchy blocking but that might have been due to the pretty wonky and cluttered design of those websites (memembase and such)

**Comment by gorhill** [comment]
Is [cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-cosmetic-filtering) disabled for that site?

> everything except color-blind enabled

So this means _"I am an advanced user"_ is checked? If so, are there any rules for `facebook.com`, and if yes, what are they?

**Comment by TheRealMarnes** [comment]
Yes, it's enabled, I've used it this way for months. I use the dynamic blocking and such.

* facebook.com * block
* facebook.net * block
www.facebook.com facebook.com * allow
(block 3rd party facebook, allow as 1st party)

**Comment by gorhill** [comment]
> `www.facebook.com facebook.com * allow`

That's your issue: having an explicit rule to `allow` facebook.com` on `facebook.com` [will also disable cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-disabling-cosmetic-filtering-for-the-current-site).

`allow` rules are very rarely needed, mostly only to un-break a web site. What is the reason you created this `allow` rule?

**Comment by TheRealMarnes** [comment]
To unbreak facebook...

This is what happens when I remove that allow rule: http://goo.gl/z9YiZk

I want fb to be blocked on other sites but I don't need it blocked when I'm actually trying to use it.

There's a better way to unbreak 1st party sites when you have a filter for them as 3rd parties and I'm missing it, aren't I? I'm just gonna re-read the doc, it's been months since I read it.

**Comment by gorhill** [comment]
What other rules is causing this? `* 3p * block`?

**Comment by TheRealMarnes** [comment]
Sorry?

I have no rules mentioning facebook besides those 3. Using the generalized options ( http://goo.gl/UtHnjc ) doesn't unbreak fb.

**Comment by TheRealMarnes** [comment]
... Adding a noop override rule instead of an allow override seems to be fixing it. Makes sense, I just had a little trouble telling the difference between no rule and a noop rule in the UI. I thought clicking the center just once when allow/block is already selected would made it a noop rule, but it just unselects the option. Had to click again to make it noop (grey).

I think it works now. Sorry for the mess, I guess this is closed and invalid now. :)

**Comment by gorhill** [comment]
> Using the generalized options ( http://goo.gl/UtHnjc ) doesn't unbreak fb.

Ok I see, you block `facebook.com` everywhere.

When I say that `allow` rules are mostly useful to un-break web sites, I really mean to un-break web sites broken by static filter lists, not by one's own dynamic filtering rules. If your goal is strictly to block `facebook.com` everywhere except when visiting `facebook.com`, the best way is to make use of `noop` rules, not `allow` rules.

So in your case I would remove all `allow` rules, because they actually prevent blocking static rules from being enforced, and rewrite your rules as follow for facebook.com:

    www.facebook.com facebook.com * noop

Just to override your global `* facebook.com * block`.
