### ISSUE TITLE
uBlock breaks Marvel Unlimited

### ISSUE THREAD

**Issue by velour-fog** [gorhill/uBlock#576]
I have found an issue with uBlock Origin while using Marvel Unlimited.

Essentially, there's something in uBlock Origin that is blocking JavaScript from properly working.

I am using the latest version of Chrome and uBlock Origin, with the default filters and set to "hard mode". This means:

    no-remote-fonts: true
    * * 3p block
    * * 3p-frame block
    * * 3p-script block
    marvel.com annihil.us * noop

(I allow `1p-script` and `inline-script` for all sites.)

**Steps to reproduce:**

2. Visit a page on Marvel Unlimited (e.g. http://marvel.com/comics/series/18457/daredevil_2014_-_present)

3. Click on "Sort & Filter". Nothing will happen. Chrome's console will output:

    **Uncaught TypeError: Cannot read property 'each' of undefined** [daredevil_2014_-_present:46](http://marvel.com/comics/series/18457/daredevil_2014_-_present)

     j @ [5d43fb602804a6159b9a6ff0e5133164.js:1](http://i.annihil.us/u/prod/marvel/s/js/5d43fb602804a6159b9a6ff0e5133164.js)
    (anonymous function) @ [5d43fb602804a6159b9a6ff0e5133164.js:1](http://i.annihil.us/u/prod/marvel/s/js/5d43fb602804a6159b9a6ff0e5133164.js)
    nrWrapper @ [daredevil_2014_-_present:46](http://marvel.com/comics/series/18457/daredevil_2014_-_present)

4. Click on "Show More". Nothing will happen. Chrome's console will output:

    **Uncaught TypeError: Cannot read property 'xtraAPIParams' of undefined** [daredevil_2014_-_present:46](http://marvel.com/comics/series/18457/daredevil_2014_-_present)

    h @ [5d43fb602804a6159b9a6ff0e5133164.js:1](http://i.annihil.us/u/prod/marvel/s/js/5d43fb602804a6159b9a6ff0e5133164.js)
    (anonymous function) @ [5d43fb602804a6159b9a6ff0e5133164.js:1](http://i.annihil.us/u/prod/marvel/s/js/5d43fb602804a6159b9a6ff0e5133164.js)
    b.event.dispatch @ [db7d9a6c0412de673a594ef9c332029c.js:4](http://i.annihil.us/u/prod/marvel/s/js/db7d9a6c0412de673a594ef9c332029c.js)
    v.handle @ [db7d9a6c0412de673a594ef9c332029c.js:4](http://i.annihil.us/u/prod/marvel/s/js/db7d9a6c0412de673a594ef9c332029c.js)
    nrWrapper @ [daredevil_2014_-_present:46](http://marvel.com/comics/series/18457/daredevil_2014_-_present)

This is what I see:

![screen shot 2015-08-06 at 11 39 08 am](https://cloud.githubusercontent.com/assets/13682761/9120323/834aff02-3c30-11e5-8000-6ae19e63b8f2.png)

This is what I should see (I whitelisted the site to take the screenshot):

![screen shot 2015-08-06 at 11 41 41 am](https://cloud.githubusercontent.com/assets/13682761/9120324/885fc68a-3c30-11e5-8b42-16ef111fbe7d.png)

I am not sure how to fix this. Is there perhaps a specific script that I must whitelist? I know that for some sites it ends up being something like Google Tag Services.

Thank you in advance for your help.

*Post edited to add screenshots.*

**Comment by gorhill** [comment]
> an issue with uBlock Origin

There is no issue with uBlock Origin: if you are blocking scripts for the page, it is not unexpected that a page may not work as intended.

Whoever blocks 3rd-party scripts by default must be ready to deal/fix with the page breakage -- hence why dynamic filtering is for advanced users, the same way NoScript is an extension suitable for advanced users.

**Comment by gorhill** [comment]
Add this to your set of rules:

    marvel.com googletagservices.com * noop
    marvel.com js-agent.newrelic.com * noop

As said though, I can't start to fix everybody's page breakage, it's best to ask around, on [Reddit](https://www.reddit.com/r/uBlockOrigin/) for example.

**Comment by Krysisx** [comment]
yes that's right. Indeed I use a script blocker and after allowing some scripts that site works great, even the "sort & filter"
