### ISSUE TITLE
Some way to group related requests

### ISSUE THREAD

**Issue by wolftune** [gorhill/uBlock#578]
I block 3rd-party requests by default. Sometimes, I'm willing to temporary show an embedded YouTube video. I need to then unblock youtube.com, ytimg.com, and googlevideo.com, but I can't do it all at once because I need to try playing the video a couple times to see the option to unblock show up for each successive item.

So, I'd like a setting that ties the allowing of youtube.com to those other related CDNs. In general, I'd like the ability to group a bunch of domains so that a single setting controls them all.

**Comment by gorhill** [comment]
I would suggest you try uMatrix. An embedded Youtube can be opened in a new tab with one click, hence it will open with (presumably) all it's required "3rd-party" resources whitelisted.

**Comment by wolftune** [comment]
Thanks, I'll give that a try. Is there documentation already about the interactions of uMatrix and uBlock and how/when/why to run either or both?

**Comment by gorhill** [comment]
There is no interactions between uMatrix and uBlock beyond there overlapping features. No special instructions other than common sense when understanding well what each does should be required -- and whatever is advisable depend entirely on what one is trying to achieve.

I always prefer to be told of issues, for which I will than think of various solutions, so what you suggest I will keep thinking about it from an issue perspective, the issue being: "How to encourage users to block 3rd-party frames by default with as little annoyances as possible."

**Comment by gorhill** [comment]
By the way, for now, another solution which I have been using, is to globally noop `ytimg.com`, `googevideo.com`, but not `youtube.com`. So for embedded videos, locally noop-ing `youtube.com` will generally let the video play with one click. Usually I have observed that `ytimg.com` and `googevideo.com` are not listed as 3rd-party for embedded Youtube videos, until you noop `youtube.com`.

**Comment by wolftune** [comment]
Indeed. I would frame the overall issue as wanting everyone to have "*all* 3rd-party requests work as *opt-in* rather than *opt-out*, but in as many cases as possible have the opt-in be as quick as possible one-click that is completely effective for the use but no *more* permissive than that"

For example, I want Disqus blocked all the time, even on sites I commonly frequent, but I like being able to one-click opt-in to letting it load on a case-by-case basis (not a site-by-site basis). For this reason, I like Ghostery's function that allows a single-time load button for widgets in-page. uBlock isn't quite that straightforward.

That Youtube-specific suggestion makes sense, thanks. I'll do that.

For dream-style, long-term, a great general end-user goal would be that the *presence* of embedded YouTube videos are shown in pages, with one-click buttons to either just load in place or load in a new *private* tab (i.e. to avoid YouTube connecting that video with the user's YouTube account). The smoothest user experience is if the effective *play* button is actually the letting things load so that no 3rd-party loading happens until the user chooses to play a video.

**Comment by lewisje** [comment]
@gorhill I think you meant `googlevideo.com` and just forgot the `l`
