### ISSUE TITLE
Suggestion - list which content is blocked

### ISSUE THREAD

**Issue by Decme** [gorhill/uBlock#58]
Just a small suggestion (I hope), not sure if it's hidden in the settings somewhere, but would be nice to be able to pull a list of the lines that are blocked on a particular webpage. If possible, to list the blocklists that contribute towards each item would help a lot to troubleshoot which adblock lists may be at fault for breaking a page. Eg:

```
*/ads.com* - EasyList
*pulllistadvertising* - EasyPrivacy
*insert.randomfilter.here* - Fanboy's Annoyance List
..etc
```

Edit: looks like [code] tags don't work in this post.

**Comment by gorhill** [comment]
Yes, it's <https://github.com/chrisaljoudi/uBlock/issues/43> (it was still opened when I handed the main project). Very old issue, but very challenging given how all worked internally. But I have been thinking a whole lot about of to resolve this, and there may be thing I want to try in the future. This is actually one of those features I consider I could work on. I will keep thinking about it.

**Comment by Draky50110** [comment]
As I'm not sure if it is related, I up this with a question : 
I'm using 0.9.5.0 on FF.
This page have the comment form blocked : http://aldus2006.typepad.fr/mon_weblog/2015/05/le-piratage-de-livres-sur-le-store-de-google.html
If I unblock the page and use the little tool to select the comment form, I can block it.
But I want the opposite : block page but just unblock this part.

Don't know if possible in fact, maybe a little tool to select part to unblock, or domain list that are blocked ?

Thanks.

**Comment by Snapy** [comment]
@Draky50110 It's maybe a bit late but you can block the whole page and make an exception filter for the part you want to unblock or you can use the logger and enter `--` in the searchbox to see what's blocked.

**Comment by gwarser** [comment]
Putting search box in "3rd-party filters" tab, that allow searching inside selected filter lists will make life lot easier.

**Comment by Draky50110** [comment]
@Snapy : yes but it is pretty... not so easy.
Example : http://aldus2006.typepad.fr/mon_weblog/2015/05/f%C3%AAte-des-m%C3%A8res-quelle-liseuse.html
The Typepad comment form is blocked !
So how can I unblock just the comment form without whitelisting the whole typepad.com domain ?

@gwarser : nice idea !

**Comment by gorhill** [comment]
> how can I unblock just the comment form without whitelisting the whole typepad.com domain?

What does the logger report? Which filter blocks what?

**Comment by Draky50110** [comment]
Found the problem maybe : some of filter lists were blocking too much things.
Finaly disabled some lists and now it works.

In general, this exteionis a killer for blocking on WordPress blogs.

@gorhill which filters listsdo you use ?

**Comment by gorhill** [comment]
@Draky50110 default ones + the new Disconnect lists + dynamic filtering default deny (globally block 3rd-party + 3rd-party frames in the unlikely case I noop 3rd-party).

Unelss the filter list is really causing many false positive, it's usually best to just create a filter exception for the one site a filter is breaking rather than disable a whole list.
