### ISSUE TITLE
jsfiddle.net not allowing local noop rule

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#580]
Steps to reproduce:
1. New firefox profile (39.0.3)
2. Install ublock origin 1.0.0.1
3. Activate advance mode and set this rules:
`* * 3p block`
`* * 3p-frame block`
`* * 3p-script block`
`jsfiddle.net jquery.com * noop`
`jsfiddle.net jshell.net * noop`
4. Visit https://jsfiddle.net/yufe3vyh/1/ and try running thereby loading https://code.jquery.com/jquery-2.1.3.js

From what I understand `jsfiddle.net jquery.com * noop` should allow jsfiddle.net to load an external library from jquery.com but it shows it is blocked:
![ublockbug](https://cloud.githubusercontent.com/assets/930620/9149208/f742cdb0-3d64-11e5-8ea5-d2b9ad75d689.png)

**Comment by g3939434** [comment]
`fiddle.jshell.net jquery.com * noop`

The request was made from iframe.

**Comment by vzjrz** [comment]
Wow I'm an idiot didnt see that it came from https://fiddle.jshell.net/_display/ but thanks!

**Comment by gorhill** [comment]
Still, I am curious: how did you end up on `https://fiddle.jshell.net/`? When I follow your original link, `https://jsfiddle.net/yufe3vyh/`, I am not redirected to `https://fiddle.jshell.net/`.

**Comment by g3939434** [comment]
@gorhill You forgot to click run.

`<form method="post" id="show-result" target="result" action="//fiddle.jshell.net/_display/">`
