### ISSUE TITLE
Unable to whitelist a popup request using dynamic filtering - popup closes without control

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#581]
<h1>Steps to reproduce</h1>

1) Ensure you have the `||goo.gl^$third-party,popup` static rule (which can be obtained from the "Block all well known privacy trackers‎" list - http://gnuzilla.gnu.org/filters/blacklist.txt, as reported by the logger)
2) Enter https://plus.google.com/b/118413096576909445716/+AndroidDevelopers/posts/K3dk18g7GfM
3) Click on the "Smaller PNG Files (100 Days of Google Dev)" text.
4) Observe a popup getting closed immediately after opening (`https://goo.gl/XQYvFz` is the popup request).
5) Try to green the domain from the Dynamic Filtering panel - fails, still shows a "-" (minus sign) within the green cell, the request isn't whitelisted.
6) Try to green the request through the Dynamic URL filtering - fails, still shows as blocked request in the logger afterwards.

**Important Notes**:
1) The above steps are only reproduceable on Chrome (v46 Canary). Firefox 42 Nightly allows to open the link in a new tab and there is no `https://goo.gl/XQYvFz` request shown in the logger.
I'm not sure if this is a different behavior of the site to other browsers, or a problem of uBlock on FF to show the request in the logger. 
2) Adding manually a whitelist static filter of `@@||goo.gl^$third-party,popup` resolves the issue (therefore the issue is with the dynamic filtering engine)

Tested on latest uBlock v1.0.0.1

**Comment by Mikey1993** [comment]
@gorhill, is this a limitation of Chrome or a bug in uBlock?
If it's some shenanigans of Chrome, it's better to open an issue on their tracker ASAP IMHO.

**Comment by gorhill** [comment]
Sorry, I missed this issue, probably saw it but forgot to come back to it.

> Try to green the domain from the Dynamic Filtering panel - fails

I checked and I confirm that the popup blocking code does not take into account dynamic filtering. I suppose it should.

**Comment by gorhill** [comment]
There was a reason I didn't take into account dynamic filtering. Real solution will need bit more work.
