### ISSUE TITLE
Incomplete warning of "badware risks"

### ISSUE THREAD

**Issue by user65478** [gorhill/uBlock#583]
uBlock Origin completely blocks some websites (strict blocking) that may actually be seen as legitimate websites, such as sourceforge.net. (uBlock filters – Badware risks)
It's written in the filter definition list itself that these sites are "documented to put users at risk of installing adware/crapware etc." and "the purpose is to at least ensure a user is warned of the risks ahead.". This is a legitimate reason. There are no objections to it.

However, this information is **not** shown to the user when he sees the warning message. It's just written that the website *http:/blabla.net* was blocked because of filter rule *||blabla.net^$other*. There is no explanation *why* a specific website was blocked. If you are an unexperienced user, you might think that (a) this is a false positive, or (b) the website was taken over by hackers and thus the website was put on a malware domain list included in uBlock Origin, but probably no one ever will immediately recognize that this website was blocked only "to at least ensure a user is warned of the risks ahead". You have to actually look into the filter definition list to get this information and it is very unlikely that an unexperienced user will do that. You get the point?
So I would suggest to add this information directly to the warning message.

**Comment by gorhill** [comment]
Previous related issue: #364.

The chosen solution which is good enough is to make the list name a link to the [_"Baware risks"_](https://github.com/gorhill/uBlock/wiki/Badware-risks) wiki doc. This is the optimal solution as this required minimal code change, hence not a risk to uBlock's stability.

**Comment by RoxKilly** [comment]
@user65478 I get your point and a couple of months ago I would have agreed.  Today I think that uBlock Origin has the right approach though.  Consider:

A good piece of software keeps things as simple as possible for inexperienced/casual users, while allowing advanced users to dig deeper and customize behavior.  This is what's happening here. If a casual user wants to be protected, he simply needs to follow suggested behavior and he'll be fine.  On the other hand, an advanced user like you can quickly get to the bottom off what's going on and disable this behavior by unticking a single checkbox.  Even for casual users who trust Sourceforge, this block can be overcome temporarily or permanently with a single click on the block page itself.

Note that it's not actually accurate to say that there is no information presented with the block.  The name of the filter, shown on the block itself (`uBlock Filter - Badware risks`) is informative.  

@gorhill  Perhaps one improvement would be to add a link to that page to the content of the filter, perhaps scrolled to the line that triggered the filter.  I think this might fit your criterion: require minimal code change, hence not risk stability

**Comment by user65478** [comment]
@RoxKilly: I don't think that the word "Badware risks" is very informative in this situation. An unexperienced user might probably associate this with "real" malware (because he doesn't know the exact difference between these words). So he might not be able to tell the difference between "it's just a warning of possible unwanted software" and "the website was taken over by hackers and thus the website was put on a malware domain list included in uBlock Origin". In the first case, it's save to click on "disable strict blocking". In the latter case, it's not!

I really like the solution by gorhill, this will help a lot IMHO.

**Comment by RoxKilly** [comment]
@user65478 
> I really like the solution by gorhill, this will help a lot IMHO
Which solution?
