### ISSUE TITLE
Annoying ads in GMX Inbox

### ISSUE THREAD

**Issue by doomkrad** [gorhill/uBlock#585]
First of all, many thanks for an excellent and extremely efficient add-on! ^_^

I'm extremely happy with uBlock's inconspicuous behavior, there is however one instance it didn't weed out: the ads the email provider GMX places into my Inbox regularly. The word to look for is 'Anzeige'.
I already looked into the nuts and bolts of uBlock, hoping to be able to add a rule myself, only to discover that I'd have to digest all the knowledge behind it, which I'm not capable of at the moment...

Could you please add a filter OR offer me an example of a similar, already existing, rule?

Many thanks in advance.

Best,
Valentin

![gmx adds](https://cloud.githubusercontent.com/assets/12195728/9160771/a639ee5a-3f3d-11e5-83ba-273da80cf78b.JPG)

**Comment by Betsy25** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Browser ? OS ? uBlock version ?

Regarding the issue, I don't think there's any filter available for these kind of ads, since there's most probably nothing externally requested, but you can of course try to create a cosmetic filter using the element picker to remove those ad items from sight.

**Comment by doomkrad** [comment]
Many thanks for the link, I wasn't yet aware of its existence. ^_^

I'm on Cyberfox 39.0.3, Windows 7 x64, uBlock 0.9.1.0.1
(To be honest, I didn't ask myself whether this submission page is able to sniff out the relevant software and the versions involved...)

Also, thank you for the clarifications with regard to cosmetic filters, I'll try to create one.

Best,
Valentin

**Comment by gorhill** [comment]
Sorry, I do not maintain filter lists. For filter syntax, consult <https://adblockplus.org/filter-cheatsheet>.
