### ISSUE TITLE
[Suggestion] Filter lists from around the web 

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#586]
The Wiki page of Filter lists from around the web is very interesting specially for the Block-EU-Cookie-Shit-List.
Will be good (in my opinion) put the page link in the Third-Party Filter options page otherwise the many users that don't read the wiki or the version 1.0.0 release notes never know the existence.
I suggest also to add the link in the AMO page because It is not specified.
Thanks.

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm <x-apple-data-detectors://2> I keep my lights
on!
We have really cool stuff!
Have a good weekend!
Happysurf, your going to love our stuff.

On Monday, August 10, 2015, happysurf <notifications@github.com> wrote:

> The Wiki page of Filter lists from around the web is very interesting
> specially for the Block-EU-Cookie-Shit-List.
> Will be good (in my opinion) put the page link in the Third-Party Filter
> options page otherwise the many users that don't read the wiki or the
> version 1.0.0 release notes never know the existence.
> I suggest also to add the link in the AMO page because It is not specified.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uBlock/issues/586>.
>


-- 
Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052

**Comment by Snapy** [comment]
@gorhill Any update ?

**Comment by gorhill** [comment]
There is an icon now which is a link to the wiki page.

**Comment by IDKwhattoputhere** [comment]
I can not find the icon. Even in 1.6.0rc0. I'm either blind or it's not there. Which pane should I be looking at?

**Comment by IDKwhattoputhere** [comment]
So I eventually found the button the other day. It's pretty damn small but I guess if it was bigger it wouldn't match the other icons.
