### ISSUE TITLE
[Suggestion] uBlock origin for Microsoft Edge

### ISSUE THREAD

**Issue by asd55** [gorhill/uBlock#587]
Hi @gorhill plz port ublock origin on edge,
uBlock Edge. :smiley: 

Greetings.

**Comment by ialexsilva** [comment]
Yes, but edge dont have support yet...

**Comment by anewuser** [comment]
@asd55 https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by Snow8** [comment]
As far as I understand, there will be addon support for Edge in the futured. They stated that is should be possible to use Chrome Addons in Edge. So no port needed as uBlock Origin already exists for Chrome!

**Comment by alain1965** [comment]
Hello, actually, it's impossible to download from chrome store if you don't have chrome. I think that a edge "store" will be exist to have addons.

**Comment by Snow8** [comment]
So? Who cares if there is a store or not as long as a dev can simply upload his chrome extention into the "microsoft store" or however they distribute addons.

**Comment by alain1965** [comment]
The problem is not where can you upload from but if a developer begins the distribution for a Microsoft browser because until internet 11 it was very limited and hard, I hope for edge it will be more simply with all the addons who have existed yet for chrome, Firefox and opera.
