### ISSUE TITLE
[Suggestion] Pup up blocker

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#588]
Can you add the functionality of this add-on to ublock origin? Some sites open pop ups that show blank but still have the url on them which is annoying.

https://addons.mozilla.org/en-US/firefox/addon/adblock-plus-pop-up-addon/

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-popups for example

**Comment by rayman89** [comment]
That's a workarround isn't it? Same site can contain useful and publicity pop ups also.

**Comment by gwarser** [comment]
`$popup` option is supported, you can create custom filter.

**Comment by gorhill** [comment]
> $popup option is supported, you can create custom filter.

That is the answer.
