### ISSUE TITLE
What did the fork enhance?

### ISSUE THREAD

**Issue by auzias** [gorhill/uBlock#589]
I would like to know (without going through the 680 commits ahead and the 280 ones behinds), what are the differences between this fork and the original https://github.com/chrisaljoudi/uBlock please ? :)

**Comment by harshanvn** [comment]
First of all this is not a fork in reality. 
He just gave away the maintainership and created another branch, to work on it..

Raymond is the creator of this product, which stemmed from httpswitchboard (which is also his project).

For starters, you can read the wiki - https://en.wikipedia.org/wiki/UBlock

Or more detailed information can be obtained by looking at https://github.com/gorhill/uBlock/releases

**Comment by auzias** [comment]
Thanks a lot, I'll take a look at these :+1:

​
Best regards,
---
​​
Auzias Maël - auzias.net <http://www.auzias.net/>
​PhD candidate
<http://auzias.net/?p=phd>
​- ​
IRISA
​
Member of the Scientific Council
<http://auzias.net/Generation14/index-en.html>
GSM : *0033 695 118 774*

**Comment by harshanvn** [comment]
Welcome!
