### ISSUE TITLE
Lack of "select an element to hide".

### ISSUE THREAD

**Issue by kubsztal** [gorhill/uBlock#591]
Lack of "select an element to hide". Still forced to use AdBlockPlus for this feature.

**Comment by yupi2** [comment]
https://github.com/gorhill/uBlock/wiki/Element-picker

**Comment by kubsztal** [comment]
Thanks! No too obvious.

**Comment by hotdogman** [comment]
![rzmojhtbfq88 1](https://cloud.githubusercontent.com/assets/4343306/9234086/585fe458-40fc-11e5-804d-ecdd53c5643e.png)
https://jii.moe/V1ynsF4j.webm

**Comment by kubsztal** [comment]
Just got it :) Thx.
