### ISSUE TITLE
Social Widget momentarily getting through despite filter list.  

### ISSUE THREAD

**Issue by Epidomis** [gorhill/uBlock#593]
![ublock](https://cloud.githubusercontent.com/assets/5743285/9237513/29d1a4ba-4100-11e5-9b96-1c6179615c21.jpg)

I have noticed since using Ublock origins in both Firefox and Chrome that social widgets get through at least initially before they get blocked.  It seems they fully load their script b/c you can access them if you click fast enough before Ublock kicks in and blocks them.  

I wanted to know if my interpretation of events is correct, b/c one of the reason I subscribe to the filter is to block social widgets and the scripts that appear nowadays in enough repetition that it can jank a browser.  I noticed that in the past ABP didn't have the problem, or it worked differently that I never noticed it in the years I used it before I switched to Ublock. 

Ideally everything would be blocked before they even load.  I am afraid that if Ublock is allowing things to load first, then maybe some malware advertisement might work its magic before it is blocked and having those malware fighting subscriptions would be moot.    

I have been able to repeate the same results on two computers.  To repeat reliably you need to clean out your close out your browser, make sure it doesn't resume previous tabs, and make sure you clean out your web browser cache.  If the website cache is still there, then you cannot recreate the problem.  A browser with a cache of the webpage will not show any symptoms and ublock blocks as should.  

I am using Ublock 1.0.1 and subscribed to the Fanboy Annoyance List.  I would appreciate any clarification on the issue.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters>.

**Comment by gorhill** [comment]
A specific cosmetic for your specific example (screenshot -- please provide URL next time):

    ! 12/08/2015, 17:58:41 http://www.nbcnews.com/meet-the-press/first-read-one-two-punch-tough-news-hillary-clinton-n408411
    www.nbcnews.com##.article_share

**Comment by Epidomis** [comment]
Sure thing about the link.  I been reading your linked articles, not the easiest to understand to a layman.  So beside social widgets, are ads or anything on the malware blocking filters listed as "cosmetic"?

**Comment by gorhill** [comment]
> not the easiest to understand to a layman. So beside social widgets, are ads or anything on the malware blocking filters listed as "cosmetic"?

Use the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what is blocked by which filters. Things blocked by cosmetic filters are reported as type `dom` -- pale yellow entries. Everything else are network requests.

**Comment by anewuser** [comment]
> probably not the best place to have a conversation

@Epidomis https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

> Use issues as replacement for threads on a bulletin board. You can use Reddit for general discussion among users.
