### ISSUE TITLE
YouTube Video Ads Broken Google Chrome Version 46

### ISSUE THREAD

**Issue by mistical** [gorhill/uBlock#594]
On the latest update for Google Chrome Dev version, 46.0.2478.0, YouTube video ad blocking has broken. I haven't tested this elsewhere on other video sites, so I'm not sure if other things have become broken. Regular ad blocking seems to be just fine though from what I've noticed at least so far.

When running the latest Stable version of Chrome, 44.0.2403.155, this does not happen. Only with the development version.

All settings, filters, etc are either up to date or are the same on each.

I haven't seen any discussion or others complaining about this yet anywhere online (reddit or forums) so figured I'd give a heads up here first.

I understand it's a dev version I'm using, not too worried about it right now, however eventually in the future this will become a stable version, so figured I'd report it now rather than later. If there's anything I can provide for you, let me know and a quick how to.

**Comment by anewuser** [comment]
@mistical Please read this and report everything you're asked to: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by mistical** [comment]
As I continue to try and find more about this and a "source" to the problem. I am constantly watching the logger on a video where it plays ads.

I am noticing more that the video ad is not being blocked and only sometimes will be blocked (complete log at the bottom).

While watching the logger, I am noticing the following, this is when the ad is blocked:

15:50:11		##iframe[id^="google_ads_frame"]	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:50:09		##[href^="https://www.youtube.com/cthru?"]	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:50:09		##.ytp-ad-progress-list	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:50:09		##.video-ads	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:50:09		##.ad-container	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:50:09		###watch7-sidebar-ads	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:50:09		###watch-channel-brand-div	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8

and here is when the video ad is not being blocked:

15:55:20		##[href^="https://www.youtube.com/cthru?"]	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:55:20		##.ytp-ad-progress-list	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:55:20		##.video-ads	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:55:20		##.ad-container	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:55:20		###watch7-sidebar-ads	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8
15:55:20		###watch-channel-brand-div	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8

Now, being relatively new to all of this, please correct or point me in the right direction but it seems as if the following is the problem for when the video ad is played.

15:50:11		##iframe[id^="google_ads_frame"]	--	dom	https://www.youtube.com/watch?v=qoNYlV07Cf8

Whenever I see a video ad play on YouTube, I'm not seeing that blocked/logged in the Logger. But when I don't see an ad, I'll see that list. It's coming from the EasyList (if that matters).

Here is a complete log: http://pastebin.com/7pKK37WN

**Comment by gorhill** [comment]
I tried with Chrome version 46.0.2478.0 dev (64-bit, Linux) here and I did not see any ad, and the cosmetic filter `##iframe[id^="google_ads_frame"]` above was never applied in my case.

**Comment by gorhill** [comment]
I just has a case with Chrome 46.0.2478.0 were uBlock went completely blank, it was no longer blocking anything. There was an exception logged in uBlock's dev console. Had to restart the extension. Will investigate, not sure how it happened, I force refresh the Youtube page a couple of time before this happened.

**Comment by gorhill** [comment]
I've been playing Youtube videos for 2 hours now on Chrome 46 and no ad.

**Comment by mistical** [comment]
After reading that link/issue, I'm not sure if that applies to me as I'm not seeing the extension get disabled and looking in the user data directory/preferences file, I'm not seeing any disable_reasons found either.

I am still getting ads though here and there on videos though. I opened Chrome's Console, not seeing anything there either or fails other than something unrelated to Google Cast.

I'm at lost what else to attempt, unless you have something else I can look for log related that I may not be familiar with yet. I went back to 100% default filters again, I only had about 3 others related to anti ad killer and disconnect me checked) but the ads still persists. I've already tried with the extensions disconnect me and tampermonkey disabled for a bit too and they are not playing a part in it.

**Comment by gorhill** [comment]
uBlock's static filtering engine has been stable since months now, so if something is not blocked, the causes are most likely:

- Infested by adware
- Youtube implemented a new scheme to serve ads and is rolling out to few people randomly (hence difficulty for others to reproduce).

If I was affected by what you experience, I would keep the logger opened, and as soon as an ad appear, I would click stop and examine the logger. You may want to share the content in such case with people familiar with how ads are blocked through ABP-compatible filters. The logger output you shared above is not of much value, as you stripped out the most important parts of it, the network requests, to keep only the probably inconsequential cosmetic filters -- video ads are blocked through the blocking of network filters, I doubt this is done using cosmetic filters.

**Comment by jtamlin** [comment]
It just looks like the filters haven't been updated for the new way that YouTube is serving ads. I blocked https://www.youtube.com/watch_fragments_ajax and I'm watching youtube videos ad free again.

**Comment by kristofferR** [comment]
I've been experiencing Youtube ads lately on Chrome 45 with uBlock Origin too, came here to see if anyone else had the problem. Since I haven't changed anything in my uBlock Origin settings lately and other people have the problem, it seems like it is a real issue (and not a problem on my end)

**Comment by gorhill** [comment]
This is something I can't reproduce on my side however many times I try. So if a new filter is required, the solution will have to come from those who experience the issue (as usual, make use of the [logger](https://github.com/gorhill/uBlock/wiki/The-logger)), and submitted to EasyList maintainers.

**Comment by mistical** [comment]
What kristofferR said did not work, so I'm nearly certain his issue is completely unrelated to what is being discussed here and not a filter issue and either a change within Chrome or a fix needed for uBlock. Someone else mentioned the same exact issue related to mine 16 days ago now on the uBlockOrigin subreddit here: https://reddit.com/r/uBlockOrigin/comments/3gyh6m/ublock_not_blocking_youtube_ads/

As what to do going forward? Weeks ago I went back to .44 stable for the first time ever instead of the dev version, so I'm just holding on until .46 becomes stable and hope that whatever the issue is, gets randomly fixed or breaks again forcing me do something else. I know it still exist as every update or few days I still check to see and it still does.

**Comment by gorhill** [comment]
Someone opened on issue on Chromium: <https://code.google.com/p/chromium/issues/detail?id=526413>.

I did run Google Chrome Version 46.0.2490.6 dev (64-bit) for a while yesterday on Youtube, and all worked fine. The person who opened the Chromium issue mentions that it is a difficult-to-reproduce bug.

From the screenshots provided, it is as if uBlock's `onBeforeRequest` handler is no longer being called, which would result in uBlock no longer working -- except for cosmetic filtering.

**Comment by blinxwang** [comment]
Chrome 45 is now stable and this bug seems to still be present in it.

**Comment by random6969** [comment]
I'm also having an issue with Ublock origin in chrome 45 not blocking Youtube ads on occasion. Adblock blocks them fine, but it also severely increases page load times, so I'll stick with Ublock and just hope it's fixed soon.

**Comment by gorhill** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=25033

**Comment by afritsch** [comment]
Interesting. I had this problem too but I have not seen any Youtube ad for like two weeks now (I don't know why it solved itself, only difference is that now I am subscribed to EasyList and Easy Privacy, not the combined one). I am on Chrome Dev channel, current version being 47.0.2498.0.

**Comment by xrogaan** [comment]
It looks like this is a browser issue: https://code.google.com/p/chromium/issues/detail?id=526413#c6

This can be closed again, I guess.
