### ISSUE TITLE
No Issue, Question About Embeded Slideshows

### ISSUE THREAD

**Issue by windyctyprog** [gorhill/uBlock#595]
New user question, can't find it in the documentation.

There are a number of sites that have embedded slideshows, sites like Tech Republic, Inhabitat, ZDnet, and etc.

I can't get the slideshows to work on any of these sites anymore and don't know if it's the 3rd. party filters (I use Fanboy's Ultimate, have for years) or something in uBlock I need to change?

Short of turning off uBlock, how do I get the slideshows to work again?

I love this add-on, but this is the single frustration I have.

Thanks, in advance...

**Comment by CrisBRM** [comment]
You use the logger to determine the culprit and then create an exception rule.

**Comment by gorhill** [comment]
Sorry but I can't assist if fixing issues with 3rd-party filter lists, writing/maintaining the code/doc/project is already taking up all my time. best is to ask help where anybody can jump in to help you, here is for issues with the code.

**Comment by windyctyprog** [comment]
Didn't request a fix, said it wasn't an issue up front, just a question, have no idea if it's 3rd. party or not.

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm I keep my lights on!
We have really cool stuff!
Have a good weekend!


On Thursday, August 13, 2015, windyctyprog <notifications@github.com> wrote:

> New user question, can't find it in the documentation.
>
> There are a number of sites that have embedded slideshows, sites like Tech
> Republic, Inhabitat, ZDnet, and etc.
>
> I can't get the slideshows to work on any of these sites anymore and don't
> know if it's the 3rd. party filters (I use Fanboy's Ultimate, have for
> years) or something in uBlock I need to change?
>
> Short of turning off uBlock, how do I get the slideshows to work again?
>
> I love this add-on, but this is the single frustration I have.
>
> Thanks, in advance...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uBlock/issues/595>.
>


-- 
Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052
