### ISSUE TITLE
Q: uBlock replaces ABE, what about Ghostery and RequestPolicy?

### ISSUE THREAD

**Issue by Diapolo** [gorhill/uBlock#596]
I today learned about this great extension, which intends to replace AdBlock Edge (which I uninstalled). But I used that in combination with Ghostery and RequestPolicy Continued. What is the advice to do/use? I'm aware of the dynamic filtering mode in uBlock, but feel unfamiliar with it for now.

**Comment by zummuz** [comment]
@Diapolo https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

If you turn on enough filters in uBlock Origin it will cover Ghostery which btw isn't trustworthy extension. Additional filters for uBlock you can find here https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web.
To replace RequestPolicy you can try uMatrix from the same developer (https://github.com/gorhill/uMatrix/wiki/Using-uBlock-with-uMatrix).
And read wikies a bit:
https://github.com/gorhill/uBlock/wiki
https://github.com/gorhill/uMatrix/wiki

**Comment by harshanvn** [comment]
I think you can safely disable ghosted.  However not so sure about RP.. 

You can take a look at wiki,  see below links - 

https://github.com/gorhill/uBlock/wiki/Blocking-mode
https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode

https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode

**Comment by Diapolo** [comment]
Thanks for your valuable help, I'm start digging in the Wiki :).

**Comment by anewuser** [comment]
@Diapolo  You shouldn't be using anything like Ghostery with any adblocker that supports privacy lists. You were just wasting your resources.
