### ISSUE TITLE
missing dashboard link on uBlock icon in browser bar

### ISSUE THREAD

**Issue by Diapolo** [gorhill/uBlock#597]
I'm missing a better way of opening ``chrome://ublock0/content/dashboard.html`` without the need to go via Addons menu. I't should be placed in the uBlock icon popup menu IMHO.

**Comment by harshanvn** [comment]
You can click on the black bar in the top on uBlock popup UI

**Comment by Diapolo** [comment]
Thank you, so this is fixed and was a no-issue ;).
