### ISSUE TITLE
Use same HTTP method after (temporarily) allowing a site

### ISSUE THREAD

**Issue by blueyed** [gorhill/uBlock#598]
I've posted an issue at https://sourceforge.net/p/firejail/tickets/new/, and uBlock blocked the request when submitting it - I have only temporarily allowed it before.

When allowing it temporarily again then, the (POST) request was sent as GET instead, and even without the POST parameters converted to GET.

This resulted in the long text to be lost - because SF.net is using some WYSIWG editor that does not display the text anymore when going back, and even Textarea cache wasn't able to help (apparently because of the WYSIWG editor).

It would have been great if uBlock would have used the same method (POST) again.

**Comment by gorhill** [comment]
Closing as obsolete -- if it is still an issue, best to open a new issue with steps to reproduce, and more details, like for instance how exactly uBO _"blocked the request"_.
