### ISSUE TITLE
[Firefox] Links in dashboard section "about" opens in the frame

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#599]
<a href="https://lh3.googleusercontent.com/-aHeyOXnx8bw/Vc5HTLjPDXI/AAAAAAAAb8U/IN19txIF-cs/s0/screenshot%2525202015-08-14%252520002.png"><img src="https://lh3.googleusercontent.com/-tVR4ozFMc0g/Vc5HTwV2FdI/AAAAAAAAb8Y/6D-x0WqJQV0/s0/thumb.png" border=0></a>

Win 8.1 x64, Firefox Nightly 43.0a1 x64 BuildID:20150814030208, uBlock Origin 1.1.0.0b2
Tested on new clean profile with e10s disabled.

**Comment by gorhill** [comment]
This was a superficial fix, the real issue is a regression bug -- as this was working fine before without the changes here needed.
