### ISSUE TITLE
[Bug] Clicking on github link in the dasboard opens in the frame and not in a new tab.

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#600]
Clicking on github link in the dasboard opens in the frame and not in a new tab.
Last ublock origin 1.1.0.0b2 and firefox 40.0.2

**Comment by typhoon71** [comment]
nevermind.

**Comment by gorhill** [comment]
> I now get a popup when I go on any github page.

How do you navigate to GitHub? This warning occurs because you are trying to open a GitHub page from within a frame object, which GitHub forbids through the use of a [`X-Frame-Options` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options), hence the warning.

**Comment by typhoon71** [comment]
sorry, I was fixing the post

**Comment by gorhill** [comment]
Ok, no problem.

**Comment by typhoon71** [comment]
Shouldn't new pages get opened in new tabs since it's the browser default?

**Comment by gorhill** [comment]
Yes, this was fixed in #599.

**Comment by gorhill** [comment]
Actually, I should ask, which link in the dashboard caused the issue on your side?

**Comment by typhoon71** [comment]
so the dev build on mozilla is outdated already?

**Comment by typhoon71** [comment]
link causing it was the github one: "https://github.com/gorhill/uBlock/graphs/contributors"

**Comment by gorhill** [comment]
> the dev build on mozilla is outdated already?

Yes, but I can't update it for every single change I make, I try to update when its worth it.

**Comment by typhoon71** [comment]
OK, I got it.

**Comment by gorhill** [comment]
Duh... I looked deeper into this, and all was working fine before, and I should have looked more carefully at the original issue, which is actually a regression bug -- the fix to #599 was not the proper one.

**Comment by typhoon71** [comment]
well, at least it wasn't lost time now, too bad it is a regression.

**Comment by typhoon71** [comment]
It does indeed fix the one I knew of. Well done. 
Already avail on AMO. You are fast!
