### ISSUE TITLE
Remove from project all filter lists which are not selected by default

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#602]
They cause the package to be too large.

The _3rd-party filters_ pane will still allow to easily select these non-default 3rd-party filter lists, only difference is that they will have to be downloaded the first time they are selected (this already happens anyway for most 3rd-party filter lists -- to fetch latest versions). A couple of current stock 3rd-party filter lists are already natively remotely fetched (not part of uBlock's package).

The transition needs to be completely transparent to users (as in nothing to do), and this requires `filter-lists.json` to be backward compatible until all uBlock Origin installations have been updated to deal with the filter lists which are now pointing strictly to their remote locations.

**Comment by charlesay** [comment]
i was about to ask for the implementation of a 'select all' option, which would be useful but partially moot if this change occurs

**Comment by gorhill** [comment]
I would have not accepted to implement such feature anyways.

**Comment by charlesay** [comment]
ok, why not (out of interest)?

**Comment by gorhill** [comment]
Common sense. The question is rather why would someone wants to do this?

**Comment by charlesay** [comment]
couldn't it be faster to deselect the undesired or -necessary lists than selecting individually the ones that should be active. i haven't compared the content of the lists in detail so, it could mostly be pointless i suppose.

**Comment by gorhill** [comment]
Fixed in efccaf141660c5173269c5432774b7e1dd4032ea.
