### ISSUE TITLE
Badware risks: potential website

### ISSUE THREAD

**Issue by lencc** [gorhill/uBlock#604]
I have come across this website (do NOT click):
www.xscyz.com/index.php?main_page=product_info&products_id=245

I did not open the website, because it was blocked by Avast Antivirus. The reported reason was malicious software (I think trojan). Is there a way to check this website for its harmfulness (without opening it directly)?

If it proves to be dangerous, I suggest to add it into "Badware risks" uBlock filter list.

**Comment by gorhill** [comment]
Google has nothing (at least yet) for this site: <https://www.google.com/safebrowsing/diagnostic?site=xscyz.com>.

Please report to the malware list maintainers -- they probably have the tools to confirm/infirm:

- <http://www.malwaredomainlist.com/>
- <http://www.malwaredomains.com/>

_Badware risks_ is for those high-traffic web sites for which there are enough reliable and objective 3rd-party sources documenting the sites as risk of badwares.
