### ISSUE TITLE
On web searches i cant use the cached option for web pages

### ISSUE THREAD

**Issue by s1raz1** [gorhill/uBlock#606]
If you do any websearch, the results shown will have a direct link, and the cached version of the page(thats an older version of the last time the page was updated), using this add on makes  it unable to choose using the cached option, this option is shown on browsers right next to the domain name of the website, for ex. WWW.blablabla.com -->cached option,  you click on it and it  drop a small option saying cached.
 I dont know if i can change this on the dashboard or if its possible, but i really like to be able to use cached option since using it makes far easier for me  to find what am looking for in a page since it highlights keywords used on the search.

**Comment by gorhill** [comment]
> the results shown will have a direct link, and the cached version of the page

I don't see any issue with this:

![a](https://cloud.githubusercontent.com/assets/585534/9310877/bb81d9d2-44e0-11e5-97ea-f8e45ab4cce1.png)

This is exactly why I emphasized:

> please describe **exactly** all the steps I need to perform to produce exactly the issue your are experiencing

You do not provide any detailed steps. Example:

1. browser version/ublock version
1. these settings, these filter lists, these custom filters.
1. do this.
1. do this.
1. do this.
1. observe this.
1. click this.

**Comment by gorhill** [comment]
Marked as invalid until all details for anybody to reproduce the issue are provided.
