### ISSUE TITLE
[Firefox] uBlock sometimes stopped working

### ISSUE THREAD

**Issue by Halibut80** [gorhill/uBlock#608]
This error occurs in rare cases (all hide rules and "picker" are stopped working) last couple of weeks. Some errors from console:

    01:20:24.316 SyntaxError: test for equality (==) mistyped as assignment (=)?1 vapi-client.js:57:33
    01:20:24.618 SyntaxError: test for equality (==) mistyped as assignment (=)? contentscript-end.js:174:57
    01:20:24.618 SyntaxError: test for equality (==) mistyped as assignment (=)? contentscript-end.js:537:35
    01:20:24.619 SyntaxError: test for equality (==) mistyped as assignment (=)? contentscript-end.js:741:48
    01:20:52.775 NS_ERROR_XPC_BAD_CONVERT_NATIVE: 1 frameModule.js:162:0
    01:20:54.233 NS_ERROR_XPC_BAD_CONVERT_NATIVE: 1 frameModule.js:340:0
    01:23:29.632 ReferenceError: reference to undefined property availableEntry.homeURL1 storage.js:245:13

After trying open picker:

    01:24:22.501 SyntaxError: test for equality (==) mistyped as assignment (=)? vapi-client.js:57:33
    01:24:22.502 SyntaxError: test for equality (==) mistyped as assignment (=)? udom.js:339:31
    01:24:22.502 SyntaxError: test for equality (==) mistyped as assignment (=)? udom.js:716:42
    01:24:22.527 ReferenceError: reference to undefined property thisRules[ruleKey] dynamic-net-filtering.js:209:1
    01:24:22.531 load Sidebar chrome://ublock0/content/popup.html
    01:24:22.535 ReferenceError: reference to undefined property details.broadcast vapi-client.js:202:1
    01:24:22.541 ReferenceError: reference to undefined property hnDetails.totalAllowCount popup.js:203:1

(This error is often happens, when navigation within ~ 5-10 min, at this site: <a href="http://ru-board.com/">http://ru-board.com/</a> (with new clean profile also)).

Win 8.1 x64, Firefox Nightly 43.0a1 x64 BuildID:20150817061040 (e10s disabled), uBlock Origin 1.1.0.0b3

Possible invalid. If so, sorry.

**Comment by gorhill** [comment]
> Some errors from console

I am guessing you refer to the shell console? If so, what command do you use to launch Nightly? Are there command line options?

**Comment by Halibut80** [comment]
No start from console, i mean "browser console" in Firefox (ctrl+shift+j). This related to uBlock errors from this console, when it's issue happened.
(Sorry for bad English)

**Comment by gorhill** [comment]
Do you have `javascript.options.strict` set to `true` in `about:config`?

**Comment by Halibut80** [comment]
Yes. I thought, the more information - the better. :) But I not saying that these errors, from the log, relates to the issue.

**Comment by gorhill** [comment]
In any case, I am trying to fix these bad javascript strictness-related warnings, but they are just warnings, so this should not cause uBlock to stop working. If it happens again, filter the console output to display only errors, and see if there is anything about uBlock in there, and if so, this could be what causes uBlock to stop working -- if you can report the result here. (I am assuming you know how to filter console output to display JS errors only, not warning or info).

**Comment by Halibut80** [comment]
@gorhill Looks like problem is gone after this commit. Thank you.
<br></br>
Perhaps it does not matter, but a couple of warnings still showing:
```
01:23:10.561 SyntaxError: test for equality (==) mistyped as assignment (=)?1 vapi-client.js:57:33
01:23:10.653 ReferenceError: reference to undefined property details.broadcast1 vapi-client.js:202:1
```

**Comment by gwarser** [comment]
Happened to me just now on my profile page on `wykop.pl`.
Cosmetic filters and picker not work.
Ublock log shows dynamic filter working, but no cosmetic rules.
Only these two lines from browser console are ublock related:
```
19:53:21.640 NS_ERROR_XPC_BAD_CONVERT_NATIVE:  frameModule.js:164:0
19:53:22.622 NS_ERROR_XPC_BAD_CONVERT_NATIVE:  frameModule.js:364:0```
Refreshing, reloading (ctrl+r) do not fix this. No problem on new tab.
I just closed this tab, and cannot reproduce again.

uBlock 1.3.1rc2, Fx43a2 64bit e10s disabled
