### ISSUE TITLE
new uBlock fork

### ISSUE THREAD

**Issue by alejandrolemus** [gorhill/uBlock#609]
Opening this issue since I cannot edit the Wiki anymore. Please, feel free to close if irrelevant.

There is a new uBlock Origin fork in Chrome Store: [Unnoficial uBlock BETA](https://chrome.google.com/webstore/detail/unofficial-ublock-beta/kjagjnchnnlgiafjjlahaedeagnmhefi?hl=en-US) by Nikolas Resiv, in case you want to keep that section of the Wiki up to date. It appears from a couple of comments there that it's serving custom advertising.

**Comment by gorhill** [comment]
I see it's a mostly a clone of 0.9.8.4. As opposed to what someone says in the feedback section, it does **not** _"shows unasked own advertisings"_. It looks like it's really someone who wanted to make a beta version in the Chrome store but has apparently stopped doing so.
