### ISSUE TITLE
FF 37 / uB 0.9.4.3 - can't download anything

### ISSUE THREAD

**Issue by atomGit** [gorhill/uBlock#61]
can't download any file from anywhere
happens with earlier versions as well
note that, in this case, static is disabled, all dynamic are noops and there are no (-) chars to indicate that anything is blocked

http://s6.postimg.org/m3i14j869/screenshot_102.png
http://s6.postimg.org/rsy9ouech/screenshot_103.png
![screenshot_104](http://s6.postimg.org/jbyrdx9nl/screenshot_104.png)

**Comment by my-password-is-password** [comment]
You removed/commented out `behind-the-scene` from your whitelist.  So you either
*  add `behind-the-scene` back to "Whitelist"
*  add `behind-the-scene * 3p noop` to "My rules"
*  `noop` each domain individually for `behind-the-scene` that you want to filter

**Comment by gorhill** [comment]
Like @my-password-is-password said, except that `behind-the-scene * 3p noop` is equivalent to `behind-the-scene * * noop` (since there is no 1st-party to `behind-the-scene` scope.

**Comment by atomGit** [comment]
behind-the-scene was not removed - it is in the whitelist, along with...
chrome-extension-scheme
chrome-scheme

**Comment by gorhill** [comment]
You will have to share your settings. Read carefully: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include>.

**Comment by gorhill** [comment]
You have to find how I can reproduce. I can't:

![a](https://cloud.githubusercontent.com/assets/585534/7180210/826023e0-e40d-11e4-9387-acd0bf647341.png)
