### ISSUE TITLE
cannot show popup UI when ublock is at the firefox tab bar

### ISSUE THREAD

**Issue by hhuimie** [gorhill/uBlock#610]
system: win7 x64 sp1  <br />
browser: firefox 38  <br />
i'm using _vimperator_ plugin. i don't navigation bar, so i `:set gui=nonavigation`, and then drag the ublock's icon to the tab bar.  <br />
in this case, when i click the ublock's icon, it doesn't pop anything.  <br />
only when i `:set gui=navigation`, the click action work fine.  <br />
other plugins, such as _lastpass_ __does not__ has this problem.  <br />
thanks.

**Comment by hotdogman** [comment]
https://github.com/chrisaljoudi/uBlock/issues/720

**Comment by hhuimie** [comment]
ohhhhhh,thanks!!!!it working fine by `: style -name ublick * #nav-bar * { visibility: visible; }`
