### ISSUE TITLE
Firefox: custom filter rule doesn't work properly

### ISSUE THREAD

**Issue by lencc** [gorhill/uBlock#611]
I noticed one of my custom filter rules doesn't work properly anymore.
I am suspecting uBlock, beacuse I remember a while ago the same rule was working normally.

I've been using this custom filter rule:
<code>||twitter.com^$domain=~twitter.com|~gov.si</code>
With this filter, I should be able to view twitter notifications on this site (the Twitter window is on the left side of the following website): http://meteo.arso.gov.si/met/sl/weather/fproduct/graphic/general/

But recently, the twitter notifications are blocked, despite I am using <code>~gov.si</code> in the rule.
If I delete the whole rule, twitter notifications window loads normally. Could you test it?

**Comment by gorhill** [comment]
I see the notifications just fine with default settings, with or without your custom filter.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/The-logger>.

**Comment by lencc** [comment]
Just to let you know, I figured out the issue.
I discovered that uBlock was somehow blocking the css request (http://platform.twitter.com) despite the exception rule.
Instead of creating a separate exception rule only for css, I instead modified the existing rule from:
<code>||twitter.com^$domain=~twitter.com|~gov.si</code> to:
<code>||<strong>^</strong>twitter.com^$domain=~twitter.com|~gov.si</code>

Now the exception rule works well.
Thanks anyway!

**Comment by gorhill** [comment]
> I discovered that uBlock was somehow blocking the css request (http://platform.twitter.com) despite the exception rule.

This can't be. The only CSS request I see from `platform.twitter.com` is:

    http://platform.twitter.com/embed/timeline.b67ffafa652943d0ebac45e422e410f7.default.css

And the request is properly "excepted" with your original custom filter `||twitter.com^$domain=~twitter.com|~gov.si`, no need to add `^` before `twitter.com`.

**Comment by lencc** [comment]
I made screenshots of Logger lists.

The 1st picture shows blocked/allowed requests with the original filter rule (<code>||twitter.com</code> ...):
http://imgur.com/ICuKpDe

The 2nd picture shows the same, but with modified rule (<code>||^twitter.com</code> ...):
http://imgur.com/r2Xbqrn

There are some remaining logs in both logger lists, but none them are blocked.
It is strange, beacuse <code>platform.twitter.com</code> requests arise only in the first case. But as you said, they shouldn't be blocked anyway.

I also need to mention that I have quite a few more filter rules in my custom list. But I deleted them temporarily to make sure they do not affect the website in this case.
I also have Firefox Tracking Protection enabled. But I don't think this is related, since it is turned on all the time.

**Comment by gorhill** [comment]
I see that `||twitter` is reported as the filter which blocks the requests. Can you click on this filter to find out from which filter list it comes from?

**Comment by gorhill** [comment]
As per your screenshot, the only explanation I can think of is that the context of the request is not `gov.si` nor `twiter.com`. You can find the context by clicking the fourth column in the logger for the blocked request (`--`), and select the static filter pane in the modal dialog. The context is the hostname spelled out after _"and which originates"_. Can you report this value here?

**Comment by lencc** [comment]
I looked up the blocked requests in the static filter dialog.

I case of the original filter rule (<code>||twitter.com</code>...) there is 1 image and 1 css blocked from twitter, by which their URL matches with:

<strong>a)</strong> platform.twitter.com/embed/timeline.93933550310288c77a13ff57ab42950b.default.css
which originates from:
--> "*pbs.twimg.com*", except if there is exception rule:
<code>||platform.twitter.com/embed/timeline.93933550310288c77a13ff57ab42950b.default.css$stylesheet,domain=pbs.twimg.com</code>
--> "*twimg.com*", except if exception:
<code>||platform.twitter.com/embed/timeline.93933550310288c77a13ff57ab42950b.default.css$stylesheet,domain=twimg.com</code>
--> "*anywhere*", except if exception:
<code>||platform.twitter.com/embed/timeline.93933550310288c77a13ff57ab42950b.default.css$stylesheet</code>

<strong>b)</strong> platform.twitter.com/embed
which originates from:
--> "*pbs.twimg.com*", except if exception:
<code>||platform.twitter.com/embed$stylesheet,domain=pbs.twimg.com</code>
--> "*twimg.com*", except if exception:
<code>||platform.twitter.com/embed$stylesheet,domain=twimg.com</code>
--> "*anywhere*", except if exception:
<code>||platform.twitter.com/embed$stylesheet</code>

**Comment by lencc** [comment]
Sorry, the upper description is for blocked css only, However in the case of image it is very similar:
"stylesheet" in the the rules is replaced with "image".

**Comment by gorhill** [comment]
Not sure I understand all of your comment, but I think you are saying the context was `twimg.com`, in which case, try rewritting your original filter as:

    ||twitter.com^$domain=~twitter.com|~twimg.com|~gov.si

See if this works as originally intended.

**Comment by lencc** [comment]
Yes, the original filter which you provided works now. Thank you!

It is interesting that the modified filter (<code>||^twitter.com</code>...) somehow managed to show twitter notifications properly even though there was no <code>twimg.com</code> rule included among exceptions.

I believe the issue is solved now.

**Comment by gorhill** [comment]
> It is interesting that the modified filter (`||^twitter.com`...) somehow managed to show twitter notifications properly

That filter was discarded as non-supported. `^` should never appear after `||`.
