### ISSUE TITLE
Possible to block Gmail ads under Promotions tab?

### ISSUE THREAD

**Issue by jluce50** [gorhill/uBlock#612]
Other ad blockers are somehow able to block the ads that look like emails under the promotions tab, but I can't figure out how to do it with uBlock. The element picker tool treats them like normal emails. Is this possible with uBlock?

![2015-08-19_084210](https://cloud.githubusercontent.com/assets/8754370/9357750/3b25579a-464e-11e5-822d-bd1ecf2759e3.JPG)

**Comment by gorhill** [comment]
I only have a rarely used throwaway Gmail account, and I am not seeing any ads anywahere in it. I would need to have ads on my side to be able to tell what is the solution.

**Comment by harshanvn** [comment]
@jluce50 
by any chance did you disable cosmetic filtering for that site?

Enabling cosmetic filtering hides the ads for me..And below is the rule fired for me...

<code>.aeF > .nH > .nH[role="main"] > .aKB</code>

**Comment by gorhill** [comment]
> did you disable cosmetic filtering

That's why I should just really stick to first mark as _invalid_ issues which are devoid of any details as per (as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues)) until details required to investigate are properly provided.

**Comment by jluce50** [comment]
I added the Fanboy+Easylist-Merged Ultimate List, which wasn't previously checked, and they are still showing. Cosmetic filtering is enabled.

>That's why I should just really stick to first mark as invalid issues which are devoid of any details -- as per CONTRIBUTING -- until such details required to investigate are properly provided.

Apologies. I intended this as more of a question than a bug report and I wasn't aware of the appropriate place to ask. I just saw the link to the subreddits in the CONTRIBUTING page, so I will ask there.

**Comment by gorhill** [comment]
> Cosmetic filtering is enabled

Are there any entries related to `.aeF > .nH > .nH[role="main"] > .aKB` in the logger when the page with the ads load?

**Comment by jluce50** [comment]
Okay, so the problem was that I had allowed google.com locally in the dynamic filtering pane. Setting it to noop allowed the ads to be blocked, but the problem is that it also breaks the Insert Photo dialog in Compose as well as some other things. I'll need to investigate this further to figure out what's responsible for that. Feel free to close this and I can continue to pursue this on reddit...

**Comment by LimboSlam** [comment]
Those are just suggested ads based on what you have "liked," "tweeted," "followed," "subscribed to" and what pages you have visited over the years. Or, a.k.a tracking by mouse clicks. These are official  ad-links by Google, produced by third party's that Google supports.
