### ISSUE TITLE
Ublock hiding Google signin button by default

### ISSUE THREAD

**Issue by gitpenguin** [gorhill/uBlock#613]
The default setting on ublock now completely hides the signin button on this page

http://google.com/analytics

Assume its the same for other google apps.

Was very confusing initially!

**Comment by harshanvn** [comment]
This is 3rd party filter issue -
Offending Filter Rule <code>/analytics/js/*</code> From <code>EasyPrivacy/Fanboy+Easylist-Merged Ultimate List</code>

Creating a below allow rule using Dynamic URL filtering should fix the issue for you -
<code>google.com http://www.google.com/analytics/js/analytics.min.js script allow</code>

Also, reporting the issue to Filter Maintainers ~~https://forums.lanik.us/~~ would resolve the issue for every one..

**Comment by gitpenguin** [comment]
ok got it...thanks for the superfast response.
