### ISSUE TITLE
[Vivaldi] 3rd party filters > my filters

### ISSUE THREAD

**Issue by SanyaIV** [gorhill/uBlock#615]
Hi,

There seems to be an issue with uBlock Origin in the browser Vivaldi, I know that browser isn't officially supported so I don't expect much to come from this.

Anyway, I'm trying to block abs.twimg.com/b/front_page/EU_*.jpg in order to block the frontpage images on twitter (before one logs in) and this works fine in chrome but in Vivaldi the images will be allowed because the third-party list Easylist has the rule `@@||twimg.com^$third-party,image` which means that seemingly third-party rules for some reason have a higher priority than rules in My Filters.

In my personal opinion My Filters should always have top priority.

I know this is easily fixed by disabling Easylist but I'd rather not.

Regards,
SanyaIV

**Comment by gorhill** [comment]
> images will be allowed because the third-party list Easylist has the rule `@@||twimg.com^$third-party,image`

I can't find `@@||twimg.com^$third-party,image` in EasyList.

> In my personal opinion My Filters should always have top priority

uBlock has the same behavior as ABP's regarding static filters. But uBlock extended ABP-filters syntax to give end-user more control over 3rd-party filter lists: the `important` filter option will solve your problem here. Try:

    ||abs.twimg.com/b/front_page/EU_*.jpg$important

**Comment by LimboSlam** [comment]
They have just added support for extensions with a UI. This tells me they are still alpha, am I right?

**Comment by SanyaIV** [comment]
Using $important fixed it.

I assumed it was Easylist because
![untitled](https://cloud.githubusercontent.com/assets/7038749/9386538/30ae7eae-475c-11e5-9722-9a0de89b845e.png)

**Comment by gorhill** [comment]
> I assumed it was Easylist

I see, this was [added 2 days ago](https://hg.adblockplus.org/easylist/rev/8d178da88de4).

I don't understand why this was added to EasyList, as there is no blocking filter for `twimg.com`, i.e. no need to create exception for it. Kind of prevent foiling Twitter tracking through image requests, unless one uses dynamic filtering to block everything from `twimg.com` (except on `twitter.com`).
