### ISSUE TITLE
[Firefox question] Does the toolbar icon badge have a specific CSS selector?

### ISSUE THREAD

**Issue by Fironet** [gorhill/uBlock#616]
More of a general question, wasn't sure sure the best place to ask. I change all of my toolbar icons in Firefox to match a certain style using Stylish/CSS, and using the DOM inspector to check what uBlock uses for it's badge styling I couldn't identify the selector/element except that the icon had the attribute 'badge' when the badge was present.

Is anyone aware if the type of badge uBlock uses for it's toolbar icon able to be targeted/styled using CSS?

**Comment by gorhill** [comment]
`#ublock0-button`:

![a](https://cloud.githubusercontent.com/assets/585534/9392702/3bc907c4-474c-11e5-8a96-79f658103cfa.png)

**Comment by Fironet** [comment]
.toolbarbutton-badge was what I was after, thanks gorhill!
