### ISSUE TITLE
(Palemoon) No doorhanger in Ublock's UI, why? 

### ISSUE THREAD

**Issue by LimboSlam** [gorhill/uBlock#618]
Hey there. 

I have notice this for awhile but dismissed it because at the time Pale Moon was not officially supported, so now that it is, could you fix the missing doorhander for Pale Moon. This is only an issue in Pale Moon, well for pre-australis Firefox at least. See, doorhanger in Firefox (gorhills screenshot):  

![screenshot 2](https://cloud.githubusercontent.com/assets/10698432/9398086/245f3804-4758-11e5-8767-2209aef8358f.png)

**Comment by hotdogman** [comment]
I think this is what you're talking about?
https://github.com/chrisaljoudi/uBlock/issues/1449
https://github.com/gorhill/uBlock/commit/fb25df9f0549b65ccaeae9f4b6f0c0289bce7d97
https://github.com/chrisaljoudi/uBlock/commit/c6f5c898897e72320be85f4a8ddfb8fac3563bb3

**Comment by LimboSlam** [comment]
No, that's the down arrow to the side of the Ublock icon.  It has been removed in Ublock. I'm taking about that doorhanger that only appears in Unlocks icon for Firefox 29+. My screenshot shows it, you know that white arrow that comes down when click Ublock.

**Comment by LimboSlam** [comment]
Hey @gorhill. Can this please be looked into. Also, has it always looked like this for Firefox pre-australis, no door hanger?

**Comment by AlexVallat** [comment]
This is provided by the browser, by the modern popup system that came in, I think, with Australis. If you are using the legacy toolbar button, either through the ```extensions.ublock0.forceLegacyToolbarButton``` preference or through using a browser that only supports legacy buttons, then you won't get the prettier popups.

**Comment by LimboSlam** [comment]
@AlexVallat:  Ahh, ok. But I believe this can be fixed because I know a couple of add-ons that do this even though we don't support Australis. But if it can't be fixed by you guys, can it be somehow ported over to Pale Moon (prettier popups/doorhanger)? Is this feasible @wolfbeast?

**Comment by wolfbeast** [comment]
@LimboSlam Why are you asking me? This would have to be done in the add-on, which is not my code to write.

**Comment by LimboSlam** [comment]
@wolfbeast: Ok.
