### ISSUE TITLE
(Site Based) Wildcard CSS ID Filter: #id*

### ISSUE THREAD

**Issue by X4** [gorhill/uBlock#619]
Hi,

if µBlock origin could create a rule with the help of the element picker that filters all IDs starting with bsa via a rule ``#bsa*`` site-wide that would be awesome!

There are a few annoying anti-adblockers that effectively stop visitors from viewing the site unless ad-blockers are disabled. They have a div sitting ontop of the site, that is only removed, if no adblocker is detected. It's predictably creating these divs with IDs starting with ``#bsa<random-chars> ``.

**Comment by hotdogman** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
```
[attr^=value]
    Represents an element with an attribute name of attr and whose value is prefixed by "value".
[attr$=value]
    Represents an element with an attribute name of attr and whose value is suffixed by "value".
[attr*=value]
    Represents an element with an attribute name of attr and whose value contains at least one occurrence of string "value" as substring.
```
Instead of `###bsa*` (which doesn't work), try `##div[id*="bsa"]` for contains bsa, or better yet, `##div[id^="bsa"]` for starts with bsa.

**Comment by gorhill** [comment]
> could create a rule with the help of the element picker that filters all IDs starting with bsa via a rule `#bsa*`

It can, but the element picker won't do it for you. Hiding rules are [just plain CSS selectors](https://adblockplus.org/filters#elemhide):

> In general, any CSS selector supported by Firefox can be used for element hiding. For example the following rule will hide anything following a div element with class "adheader": ##div.adheader + *. 

So in your case, a valid CSS selector:

    ##[id^="bsa"]

In uBlock it's not too complicated to do this:
1. Pick the element to hide using the element picker
1. Click on one of the suggest cosmetic filter (they are ordered from narrower to broader)
1. Edit the result in the text area to furtehr fine tune your cosmetic filter
    - The element picker "assist" you because it will highlight whatever elements on the page which match your filter
    - If your filter is invalid, you won't be able to create it
