### ISSUE TITLE
FF 37 / uB 0.9.4.3 - messing with FF history UI

### ISSUE THREAD

**Issue by atomGit** [gorhill/uBlock#62]
happens once in a while...
http://s6.postimg.org/uplap4k69/screenshot_105.png

**Comment by gorhill** [comment]
Must be your behind-the-scene thing? Please, do niot play with features which you do not understand. It's why they are labeled "For advanced users", and marked with [**"required reading"**](https://github.com/gorhill/uBlock/wiki/Advanced-user-features).

**Comment by atomGit** [comment]
behind-the-scene thing?
what are referring to?
regardless of how uB is configured this should not happen

**Comment by gorhill** [comment]
> **regardless of how uB is configured it** certainly should not break chrome/UI components

First, you have absolutely no case that whatever the problem is here, it is because of uBlock. I just see a screenshot of an empty Firefox dialog box. It's the kind of bug report I warn against in <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

Second, you are **warned** that blocking behind-the-scene can break the browser functions. The part I emphasized in your quote above means one thing: do not use uBlock's advanced features, it's definitely not made for you.

**Comment by atomGit** [comment]
for the THIRD TIME, behind-the-scene WAS NOT BLOCKED - it is, and ALWAYS WAS on the white-list, so if that is the problem, then there is most certainly a bug in  0.9.4.3 that i have not noticed in previous versions

also, once again, i clearly stated that "this happens occasionally, not consistently, with the same filters/config". it never happens when uB is disabled, however i cannot reproduce it reliably

thirdly, uB SHOULD NEVER BREAK BASIC CHROME UI ELEMENTS and cause all the controls to disappear - again, this happens in 0.9.4.3 and no other versions that i have noticed 

so because the ext. has bugs, my technical ability is lacking?  you're a funny guy

**Comment by gorhill** [comment]
Your bug report is one picture with the caption _"happens once in a while..."_ -- you need to actually **contribute** more efforts toward making the case it is a bug in uBlock. I see no such effort. You are not still sharing **any details** of browser/uBlock your config beyond "FF 37 / uB 0.9.4.3".

Some insights about reporting bugs: [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

I appreciate contributors who take the time to file bug report, but what I see here is _not_ a bug report.
