### ISSUE TITLE
Image blocking doesn't work in some cases

### ISSUE THREAD

**Issue by annoyncs** [gorhill/uBlock#623]
E.g. on page http://stackoverflow.com/questions/931092/reverse-a-string-in-python profile images like `https://www.gravatar.com/avatar/a790e6ce0929fcd647f0879edbd9ec3d?s=32&d=identicon&r=PG`  don't get blocked by any filter I've tried, like `||gravatar.com/avatar/`. However if you follow the image link directly, the image is blocked.
Same with https://twitter.com/search?q=foobar&src=typd. Profile images don't get blocked by filter `/profile_images/*`.
This all is not the case with adblock plus.

**Comment by gorhill** [comment]
Use the logger first to diagnose filter issue, it tells what happens:

![a](https://cloud.githubusercontent.com/assets/585534/9422284/e36b56d4-485b-11e5-9944-e74b03143ea8.png)

I think there is also an exception filter for Twitter images.

To override an exception filter, possible solutions:

- Use the `important` filter option: `||gravatar.com/avatar/$important`
- Use a [dynamic URL filtering rule](https://github.com/gorhill/uBlock/wiki/The-logger#dynamic-url-filtering-rules): `* https://www.gravatar.com/avatar/ image block`
  ![a](https://cloud.githubusercontent.com/assets/585534/9422300/58ed89cc-485c-11e5-9529-0fff62c06f22.png)

Personally I block `gravatar.com` through [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering), it's ubiquitous enough to be considered a tracker IMO.

**Comment by annoyncs** [comment]
Correct, thank you!
