### ISSUE TITLE
No favicon in hard mode blocking mode

### ISSUE THREAD

**Issue by podabed** [gorhill/uBlock#625]
When I use hard mode blocking mode I don't see favicons on every site.

**Comment by harshanvn** [comment]
You might want to  check the request log to see which rule is blocking it..

**Comment by gorhill** [comment]
Yes, see request logger, it will tell you what uBlock blocks and why.

Marking as _invalid_ and closing as per [CONTRIBUTIONS](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by podabed** [comment]
* * 3p block blockinhg favicon. For example site foobar2000. See page source: <link rel="shortcut icon" href="/favicon.ico" />. But icon don't see! Why third party filter blocking image from first party domain?

My rules:
* * 3p block
* * 3p-frame block
* * 3p-script block
* * image allow

**Comment by harshanvn** [comment]
It might be coming in behind-the-scene request. 
Can you post the log entries by keeping the tab selector entries as 'all'

**Comment by podabed** [comment]
Everything's alright on Mobile Firefox with identical rules. I've tried it on many sites.

**Comment by harshanvn** [comment]
Still you are not answering my question!! 
Can you post the request log entries by keeping tab selector to 'all'

**Comment by podabed** [comment]
foobar200.org:
17:57:04		* * 3p block	--	image	http://www.foobar2000.org/favicon.ico#-moz-resolution=16,16
17:57:04		##.db_link	--	dom	http://www.foobar2000.org/
17:57:04		* * 3p-script block	--	script	http://apis.google.com/js/plusone.js
17:57:03		* * 3p-script block	--	script	http://www.google-analytics.com/ga.js
17:57:03		* * 3p block	--	image	http://www.dbpoweramp.com/images/dmc/dmc.png
17:57:03		* * 3p block	--	image	http://www.dbpoweramp.com/images/cd-ripper-secure.png
17:57:03		* * 3p block	--	image	http://www.dbpoweramp.com/images/pt-art-main.png
17:57:03		* * 3p block	--	image	http://mobile.foobar2000.com/images/foobar-kickstarter.png
17:57:03		* * 3p-script block	--	script	http://api.flattr.com/js/0.5.0/load.js?mode=auto
17:57:03		* * 3p-script block	--	script	http://apis.google.com/js/plusone.js
17:57:03		* * 3p block	--	image	http://www.dbpoweramp.com/images/dmc/dmc.png
17:57:03		* * 3p block	--	image	http://www.dbpoweramp.com/images/cd-ripper-secure.png
17:57:03		* * 3p block	--	image	http://www.dbpoweramp.com/images/pt-art-main.png
17:57:03		* * image allow	++	image	http://www.foobar2000.org/tinyfoobar.png
17:57:03		* * 3p block	--	image	http://mobile.foobar2000.com/images/foobar-kickstarter.png
17:57:03		* * image allow	++	image	http://www.foobar2000.org/foobarlogo.png
17:57:03				css	http://www.foobar2000.org/foo.css
17:57:03				inline-script	http://www.foobar2000.org/
17:57:03				doc	http://www.foobar2000.org/

github.com:
17:59:07		* * 3p block	--	websocket	https://live.github.com/_sockets/NDM1MjE2ODphODc2MGE1MzMxNjEwZDIxNzA5NWE2YWMyODgyNjgzNDoyNWRkNjlmMjk0YTUyMzc1YTI5M2Q3MmFlMmY3MmE2OWNiNWMxY2NkOWE5MDkwZDhlZjc3OGM4YzIwZjhhMzk1--7cfd2f8c3ff1025f8a1420e6c1be7bba9b965a3f
17:59:00		* * 3p block	--	websocket	https://live.github.com/_sockets/NDM1MjE2ODphODc2MGE1MzMxNjEwZDIxNzA5NWE2YWMyODgyNjgzNDoxMzg4ZmEzOTEyZTg5YWI5NDQ2MWVhMjdhZjQ0Yjg4NDBjMzg0MzZiNWFlZDVhNDQ0MDJkMGExNGVjMWU5ZjFh--c822bcf5cb8bf6a8eaa5ccd968040bef73e0760f
17:58:53		* * 3p block	--	websocket	https://live.github.com/_sockets/NDM1MjE2ODphODc2MGE1MzMxNjEwZDIxNzA5NWE2YWMyODgyNjgzNDoxMzg4ZmEzOTEyZTg5YWI5NDQ2MWVhMjdhZjQ0Yjg4NDBjMzg0MzZiNWFlZDVhNDQ0MDJkMGExNGVjMWU5ZjFh--c822bcf5cb8bf6a8eaa5ccd968040bef73e0760f
17:58:50		* * 3p block	--	websocket	https://live.github.com/_sockets/NDM1MjE2ODphODc2MGE1MzMxNjEwZDIxNzA5NWE2YWMyODgyNjgzNDoxMzg4ZmEzOTEyZTg5YWI5NDQ2MWVhMjdhZjQ0Yjg4NDBjMzg0MzZiNWFlZDVhNDQ0MDJkMGExNGVjMWU5ZjFh--c822bcf5cb8bf6a8eaa5ccd968040bef73e0760f
17:58:48		* * 3p block	--	other	https://api.github.com/_private/browser/stats
17:58:48				other	https://api.github.com/_private/browser/stats
17:58:48		* * 3p block	--	websocket	https://live.github.com/_sockets/NDM1MjE2ODphODc2MGE1MzMxNjEwZDIxNzA5NWE2YWMyODgyNjgzNDoxMzg4ZmEzOTEyZTg5YWI5NDQ2MWVhMjdhZjQ0Yjg4NDBjMzg0MzZiNWFlZDVhNDQ0MDJkMGExNGVjMWU5ZjFh--c822bcf5cb8bf6a8eaa5ccd968040bef73e0760f
17:58:47		* * 3p block	--	image	https://assets-cdn.github.com/favicon.ico#-moz-resolution=16,16
17:58:47		* * 3p block	--	image	https://www.google-analytics.com/collect?v=1&_v=j30&a=506320807&t=event&ni=1&_s=3&dl=https%3A%2F%2Fgithub.com%2F&ul=en-us&de=UTF-8&dt=GitHub&sd=24-bit&sr=1024x600&vp=1004x529&je=0&ec=Dashboard&ea=view&el=context%3Auser&_u=eACAAAQEM~&jid=&cid=1006233413.1440304210&tid=UA-3769691-2&cd1=Logged%20In&cd4=Current%20repo%20nav&z=2077928155
17:58:47		* * 3p block	--	image	https://www.google-analytics.com/collect?v=1&_v=j30&a=506320807&t=event&ni=1&_s=2&dl=https%3A%2F%2Fgithub.com%2F&ul=en-us&de=UTF-8&dt=GitHub&sd=24-bit&sr=1024x600&vp=1004x529&je=0&ec=Rails&ea=view&el=dashboard%23index&_u=eACAAAQEM~&jid=&cid=1006233413.1440304210&tid=UA-3769691-2&cd1=Logged%20In&cd4=Current%20repo%20nav&z=681928236
17:58:47		* * 3p block	--	image	https://www.google-analytics.com/collect?v=1&_v=j30&a=506320807&t=pageview&_s=1&dl=https%3A%2F%2Fgithub.com%2F&ul=en-us&de=UTF-8&dt=GitHub&sd=24-bit&sr=1024x600&vp=1004x529&je=0&_u=eACAAAQAM~&jid=&cid=1006233413.1440304210&tid=UA-3769691-2&cd1=Logged%20In&cd4=Current%20repo%20nav&z=182464697
17:58:47		||collector-cdn.github.com^	--	script	https://collector-cdn.github.com/assets/api.js
17:58:46		##.subscribe-feed	--	dom	https://github.com/
17:58:45				script	https://assets-cdn.github.com/assets/github/index-40d6542150b87982b73f0d4b4430af56830310bc4b0e49aa3441e966da238799.js
17:58:45				script	https://assets-cdn.github.com/assets/frameworks-d57b85eb0208f46172d97d4746c78b19441b324803d3cc53d37e5a405f584b6d.js
17:58:45		* * 3p block	--	image	https://avatars3.githubusercontent.com/u/4352168?v=3&s=40
17:58:45				css	https://assets-cdn.github.com/assets/github2/index-9f11074052a3551cd7bae2fba8b949844d2d7329927a7f1cb5a2c2a821f016e0.css
17:58:45				css	https://assets-cdn.github.com/assets/github/index-17ad0ea72cb80a46ba6d1bd6e3c69789acb0e1c0cae43beb90477759cce1bdfd.css
17:58:45				inline-script	https://github.com/
17:58:45		* * 3p block	--	websocket	https://live.github.com/_sockets/NDM1MjE2ODphODc2MGE1MzMxNjEwZDIxNzA5NWE2YWMyODgyNjgzNDo4YjQwMGNlOGQ0MjM0YTAyMDJkNjA2ZDQ2OTg4MDk4YjRkMmRhNzQzMGYyZWQ4OWUyZTY5MzNiNTU1OWQzNTEw--bf003558886dfebffdbd6b92c2c12873d6363906
17:58:45				doc	https://github.com/

forum.xda-developers.com:
18:00:08		* * 3p block	--	image	http://forum.xda-developers.com/favicon.ico#-moz-resolution=16,16
18:00:07		* * 3p-script block	--	script	http://ads.servebom.com/tmnhead.js
18:00:07		* * 3p-script block	--	script	http://tags.bkrtx.com/js/bk-coretag.js
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/XDA2013/navigation/up-arrow.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/arrowRight.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/legend/attachment.png
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/XDA2013/forum/header/speech.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/header/discussion.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/navigation/home.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/navigation/btn_usercp.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/navigation/btn_searchForum.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/navigation/btn_searchDevice.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/navigation/textField.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/sprites.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/layout/line.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/user/mail.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/layout/navBack.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/header/icon_online.png
18:00:07		* * image allow	++	image	http://cdn4.xda-developers.com/images/XDA2013/header/icon_registered.png
18:00:07		* * 3p-script block	--	script	http://www.google.com/jsapi
18:00:07		||clickcdn.xda-developers.com^	--	script	http://clickcdn.xda-developers.com/api/vglnk.js
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/leaseweb175x50.png
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/XDA2013/header/xdaLogo_small.png
18:00:07		* * image allow	++	image	http://forum.xda-developers.com/images/icons/advanced/info_2.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/thread/thread_hot_lock.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/starRating.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/legend/smallArrowRight2.png
18:00:07		* * image allow	++	image	http://forum.xda-developers.com/images/icons/icon1.gif
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/forum/thread/thread_hot_new.png
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/XDA2012/buttons/sortasc.gif
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/XDA2012/buttons/collapse_tcat.gif
18:00:07		* * image allow	++	image	http://forum.xda-developers.com/images/google_small.png
18:00:07		* * image allow	++	image	http://cdn3.xda-developers.com/images/invisible.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/header/swappa.png
18:00:07		* * image allow	++	image	http://cdn1.xda-developers.com/images/XDA2013/header/xdaLogo.png
18:00:07		* * 3p block	--	css	http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css
18:00:07		* * 3p-script block	--	script	http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js
18:00:07		* * 3p-script block	--	script	http://www.google-analytics.com/ga.js
18:00:06		* * 3p-script block	--	script	http://ads.servebom.com/tmnhead.js
18:00:06		* * 3p-script block	--	script	http://tags.bkrtx.com/js/bk-coretag.js
18:00:06		* * 3p-script block	--	script	http://www.google.com/jsapi
18:00:06		* * 3p-script block	--	script	http://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js
18:00:06				script	http://cdn2.xda-developers.com/clientscript/deviceSearch.js?1440204865
18:00:06				script	http://cdn1.xda-developers.com/clientscript/suggest_devices.js
18:00:06		* * 3p block	--	css	http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css
18:00:06		* * 3p-script block	--	script	http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js
18:00:06				script	http://cdn1.xda-developers.com/clientscript/2013.min.js
18:00:06		* * 3p-script block	--	script	http://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js
18:00:06		* * 3p-script block	--	script	http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
18:00:06				css	http://cdn1.xda-developers.com/css/2013.1024.min.css
18:00:06				inline-script	http://forum.xda-developers.com/subscription.php
18:00:05				doc	http://forum.xda-developers.com/subscription.php

**Comment by gorhill** [comment]
The rule which blocks your favicons is right there in the logger: `* * 3p block`.

**Comment by podabed** [comment]
OK, but my rules are:

    * 3p block
    * 3p-frame block
    * 3p-script block
    * image allow

And favicon usually places in 1p domain.

**Comment by gorhill** [comment]
In Firefox, Favicons are usually pulled from behind-the-scene, not from the tab which uses them.

**Comment by podabed** [comment]
It works! Thank you very much.
