### ISSUE TITLE
Speedtest.net ads are blocked in Adblock Plus, not in uBlock Origin

### ISSUE THREAD

**Issue by tancrackers** [gorhill/uBlock#626]
I found this revision:
https://hg.adblockplus.org/easylist/rev/22e256c71c6f

I updated Easylist in both Adblock Plus for Firefox and Chrome, and in uBlock Origin for Firefox and Chrome.

The ads do not show up while using Adblock Plus, but they get through uBlock Origin.
EDIT:
Website:
http://www.speedtest.net/
Web browsers:
Firefox 40.0.2 x64
Chromium 44.0.2403.157 x64
OS: Arch Linux x64 KDE Desktop 5.3.2-3
Firefox extensions:
uBlockO 1.0.0.1
AdblockPlus 2.6.10
Chromium extensions:
uBlockO 1.0.0.1
AdblockPlus 1.9.1

Filter subscription:
EasyList‎
I disabled every filter except for Easylist, and then I ran my tests.
Here are my uBlockO settings:
https://i.imgur.com/gVcxrnK.png

Screenshot of the webpage with uBlockO:
https://i.imgur.com/QxDNs4p.png
Screenshot of the webpage with uBlockO after performing the speedtest:
https://i.imgur.com/g4pIjpQ.png
Screenshot of the webpage with AdblockPlus:
https://i.imgur.com/a4MyLz3.png
Screenshot of the webpage with AdblockPlus after performing the speedtest:
https://i.imgur.com/Yp4gUUH.png

I saw these in the logger (red):
||wistia.net/embed/$domain=speedtest.net
||betrad.com^$third-party
I'm not sure how helpful those are.

The site's ads load with uBlockO in both Chromium and in Firefox.

**Comment by gorhill** [comment]
1. Please attach a screenshot of what ad is shown
1. uBlock version/browser version
1. [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues)

**Comment by gorhill** [comment]
Unable to reproduce on Chromium 44 using default settings.

**Comment by kintpuash** [comment]
I get the ad in Chrome and Firefox with Origin with Fanboy Ultimate. Installed ABP in Chrome, default settings. Ad is still not blocked.

So they are probably attempting to actively work around Easylist. Ad is perhaps geo-specific?

**Comment by gorhill** [comment]
It would help to have a screenshot of whatever ad there is, I have no idea what to expect, where, etc.

**Comment by kintpuash** [comment]
![speedtestscreenshot](https://cloud.githubusercontent.com/assets/12130085/9429880/dae39b44-49a4-11e5-8437-9794394b1aa3.png)

This is Chrome 44 64 bit on an Ubuntu based distro, Origin 1.0.0.1, Fanboy Ultimate /w Peter Lowe's and Malware Domains

**Comment by gorhill** [comment]
Is this a Flash-based thing or is it a plain image?

**Comment by kintpuash** [comment]
![stscreen](https://cloud.githubusercontent.com/assets/12130085/9430226/8a34034c-49b2-11e5-9e42-9d2fc02ef796.png)

This is what it looks like on Firefox 41. No flash installed.

This is a url when hovering over the ad image.

[link example](http://c.speedtest.net/javascript/speedtest-main.js?p=VmLaPpirfiB1&r=3220fiwsKCtQRUV3enkkIXkjRH1EeicteCR7eSQheSNEJnssRSh5K0V5JCF5I1UwdyFTV2FXZSIrLmNsImhqbXdmY01qTXVnZHtnWmluV34se0l4TW4mJ2cvI0tmTVtKbklKbCgwZSlpKXcmKyZ5K113RylXK2Mpby9tYEYoJEMlbFp6TGtlekZGWkwmaFtaJ1lNanpMK2QwKHhbYFhvbHt5a2hGL3lNbXlIRiIxRnhiYUtJeSQhLmwjSEtHJUstfTwrIX1TWX1GVyphYGkyYE1HKyhoZmx9bjI8d3otKiRTfiwsKCtQRUV3enkkIXkjRH1EeicteCR7eSQheSNEJnssRXd5JCM7SVwrdztJWmI7SEx3ITtJWlgqJiV3WiIid2x3XnhceWFYSWddKU0nan1XeGoxKih5X1dXV1dbV1t9ImRNaWFafVdtZGpuTCpMT1dtWmAqKCVkTWFpV1tiX1hbbnpJejFLMnldbCRwXmgkeUlnLXglbEYtfVtgcEhwL25IJCxvbXokMVdbYEh9WyJ3XmhGeVonLmJJekl6MUsyeV1sJHBeaCR5SWcteCVsRmIyTy14SHArb25kJ2ZqXW9XLjBaL1dfWUpXX1dMfV8tYjJnR2Vaay55SVgkcG1oRnBuZEZiJUskellPMnpcTzJ4SWwxb0hsL3hIJC16XE8rcG1cI3BuYCF4SFwxcGZ9WX5kX3sjV2UjV0t9WkpXZSdXL159WFddZ1h9XX1YfnhvWC9XO0hMJi0lO0laRjtITHkhejtJWktdfShjLztITCshfTtJWldlWkxKdUYuK29XJSRaR2okJX14KSJNSUpjblwlKEZYKi87SEx5JCF7Jiw7SVp5d0MoLXhDS0tGS09GS0tNT0tPT09GSztITHd6LSokO0lafiwsKCtQRUUrLHd9K0R4JC17I3chRHknJUUrISx7RUdMTk1LO0hLSVwofiEmLDtIS0laey57Jiw7SEtIS0laeSQheSM7SEtITCh-ISYsO0hLSVp3IXo7SEtIS0laSktLSEhHTjtIS0hMKH4hJiw7SEtJWighejtIS0hLSVpHR09MTE1KTEk7SEtITCh-ISYsO0hLSVp5IXo7SEtIS0laTk5JS0hNTDtIS0hMKH4hJiw7SEtJWnkqIXo7SEtIS0laTEpITkxOTE07SEtITHonJns7SEtJWn4sLChQRUV4LSshJnsrK0QueyohMicmLyEqeyR7KytEeSclRXknJix7JixFeEh4RXsmRXgtKyEmeysrQygqJyUnLCEnJitFfXssQy57KiEyJyZDeC0rISZ7KytEfiwlJDtIS0hLSVx5JSg7SEtIS0laWFdZQ1hDXmdDZGVkQ2lDV21DZGVkW0NYX1lDY25DWltDWGtDTk5JS0hNTHVHSEpJSUtGdUdHT0xMTUpMSXVMSkhOTE5MTUNkZWRb&q=208975e%3Dqec%26xD%3Dip&b=)

**Comment by neilishere** [comment]
I had to put `||speedtest.net/javascript/speedtest-main.js*&b=^$important` in my filters to remove that in both browsers - chrome and firefox.

**Comment by kintpuash** [comment]
@neilishere

that works :+1: 

     ||c.speedtest.net/javascript/speedtest-main.js$script,domain=www.speedtest.net,important

triggers an adblock warning

**Comment by neilishere** [comment]
Depending on how far you want to take this:
`speedtest.net http://c.speedtest.net/flash/standard-wide-new-1button.swf object block`
`speedtest.net http://c.speedtest.net/images image block`
`speedtest.net http://c.speedtest.net/javascript/jquery-analytics.min.js script block`
in My Rules.
This will clean up everything and leave just the basic test.  I have just the default 3rd party lists.

**Comment by gorhill** [comment]
Ok, I can reproduce in Nightly, if using a US server VPN. I can't reproduce with ABP. Investigating.

**Comment by gorhill** [comment]
@nellisphere Yes this is where I was at:

    ||c.speedtest.net/javascript/speedtest-main.js$image,important

There is an exception filter in EasyList that prevented that image from being blocked, hence we need `important`. Also kind of weird that what looks like a URL to a JS resource is actually an image.

**Comment by kintpuash** [comment]
My guess it is tied to user agent as well. Messing around with it-spoofing to Internet Explorer 6-8, no ad. 10-11, ad. Appears Ad content changes based on user agent as well.

**Comment by kintpuash** [comment]
Installed Nightly. Origin default, ad shows. ABP default, no ad. Site detecting ABP and not serving the ad? How would that work?

**Comment by gorhill** [comment]
Probably because ABP Firefox uses user-stylesheets, which have absolute priority over any other styles. This is not true for Chromium, so ABP on Chromium suffers the issue as well. Using @neilishere's suggested filter works well as solution, and it also works for ABP Chromium, and anyways, a solution which relies on blocking network requests is better than a solution on purely hiding DOM elements.

If using `||speedtest.net/javascript/speedtest-main.js*&b=^$important`, the difference between the network requests can be seen in [this diff](https://www.diffchecker.com/1a3tuoqd).

**Comment by kintpuash** [comment]
>Probably because ABP Firefox uses user-stylesheets, which have absolute priority over any other styles.

Easylist w/o element hiding rules does show the ad.

**Comment by tancrackers** [comment]
I edited the OP with more information.
I have this bug with both Firefox and Chromium.
Can ADP use Firefox style-sheets in Chromium?

**Comment by kintpuash** [comment]
@tancrackers 

did you paste this filter under "My Filters" in the dashboard in uBlock Origin?

     ||speedtest.net/javascript/speedtest-main.js*&b=^$important

**Comment by gorhill** [comment]
> Can ADP use Firefox style-sheets in Chromium?

There is no such thing as user stylesheets on Chromium. Anyway, as said, use @neilishere's solution, it's better. It should be submitted to maintainers of EasyList, as this would also fix the problem for ABP Chromium.
