### ISSUE TITLE
[Firefox] uBlock breaks Firefox Runtime Analyzer / Profiler

### ISSUE THREAD

**Issue by robert7k** [gorhill/uBlock#627]
I'm using Firefox 40.0.2 on 64bit Linux with uBlock 1.0.0.1.

uBlock seems to break the Firefox Profiler / Runtime Analyzer. Here's how to reproduce:
* Make sure uBlock is enabled.
* Open https://bugzilla.mozilla.org/show_bug.cgi?id=1172157
* Open Profiler (CTRL + SHIFT + I)
* Start Analyzing
* Refresh page (F5)
* Stop Analyzing after refresh is completes
* The Profiler keeps on loading and never ends. The following exception appears in `.xsession-errors`:

```
onPacket threw an exception: Error: Server did not specify an actor, dropping packet: {"error":"unknownError","message":"error occurred while processing 'getProfile: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data\nStack: ProfilerActor.prototype.onGetProfile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/profiler.js:182:19\nDSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1456:15\nLocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11\nmakeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14\nmakeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14\nLine: 182, column: 18"}
Stack: DebuggerClient.prototype.onPacket@resource://gre/modules/devtools/dbg-client.jsm:944:1
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
Line: 944, column: 0
```

When I disable uBlock the problem is not reproducible, so I guess this issue is triggered by uBlock. Here's the related Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1172157

**Comment by jsantell** [comment]
Hey -- Firefox performance tools dev here -- this is due to non-ascii characters, presumably in uBlock. Since the profiler measures an entire process of JS, if uBlock is in that process, it'll break -- so any recording anywhere in single process Firefox, or the chrome/addon process in [multiprocess Firefox](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox).

That being said, the fix in Firefox landed in Fx41, or if you ran it in multiprocess mode (which probably can't on release in Fx40? Not sure), or a fix on uBlock's end would be removing non-ascii characters

**Comment by jsantell** [comment]
Can you confirm that the problem is no longer in Fx41?

**Comment by gorhill** [comment]
Duplicate of #603 probably.

**Comment by jsantell** [comment]
Yeah, looks like.

**Comment by robert7k** [comment]
Yes, this bug is not reproducible in Firefox 41.0beta3. Thanks for the hint.
