### ISSUE TITLE
Blocks ad.fly Timer and Next Page button

### ISSUE THREAD

**Issue by mikeloeven** [gorhill/uBlock#628]
Ublock origin will block the ads from ad.fly links however it also blocks the elements responsible for the delay timer and removes the button needed to click past the ad page and access the actual page your trying to get to. I would rather not have to enable ads on this page just to be able to click past them

**Comment by gorhill** [comment]
> I would rather not have to enable ads on this page just to be able to click past them

I don't maintain filter lists, best is you report what you want and the required filters to those who maintain filter lists.
