### ISSUE TITLE
Settings import enables 3rd-party filters not present in backup

### ISSUE THREAD

**Issue by 4nd3r** [gorhill/uBlock#63]
1. install uBlock Origin from Chrome Web Store
2. verify that "Malware Domain List‎" and "Malware domains" are not present in backed up settings file
3. Restore from file...
4. view 3rd-party filters
5. "Malware Domain List‎" and "Malware domains" still selected

**Comment by gorhill** [comment]
Good one. Reading this I realize it's a side effect of a change I did a while ago to minimize noise in backup file.
