### ISSUE TITLE
[request] popup block for all sites

### ISSUE THREAD

**Issue by Krysisx** [gorhill/uBlock#630]
Hi,

is it possible to add the possibility to set an option to block popups for all sites?
Something like what this addon does: https://addons.mozilla.org/en-US/firefox/addon/pop-up-control/?src=cb-dl-updated

Thanks for your great work.

**Comment by harshanvn** [comment]
> option to block popups for all sites?

try adding this rule in <code>My Rules</code> tab <code>no-popups: * true</code>

And read more about popup blocking here https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-popups

**Comment by Krysisx** [comment]
Ok thanks.

**Comment by Krysisx** [comment]
I have tried that, but I can see that it really blocks all popups including all sites that have links that open in a new tab. 
The extension I have reported above https://addons.mozilla.org/en-US/firefox/addon/pop-up-control/?src=cb-dl-updated does make difference, indeed it does not prevent sites from opening links in a new tab, but block the popups that uBlock can't block with filters.

**Comment by gorhill** [comment]
See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues). Provide all the details please.

**Comment by gorhill** [comment]
Closing due to no detailed repro steps provided.
