### ISSUE TITLE
Spotify Webplayer ads bypassing filters

### ISSUE THREAD

**Issue by justastranger** [gorhill/uBlock#633]
I am using Chrome version 45.0.2454.46 beta-m (64-bit) and uBlock Origin 1.0.0.1

Despite using the following filter, spotify still plays ads coming from that domain and requests to it are not listed in the page's request log (In fact, nothing is listed in the webplayer's request log at all)
```
||d7zatysqm84hv.cloudfront.net/mp3-ad/*$object
```

Ads on other sites are blocked, and the spotify ads themselves do get caught if [opened directly](http://d7zatysqm84hv.cloudfront.net/mp3-ad/89a1e07ec7034b1610b7d9209f290bb4b2591bbb)

Spotify ads used to be blocked up until now.

**Comment by gorhill** [comment]
You did not provide a URL -- see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues) and read everything carefully, be sure it is **not** a filter issue.

> requests to it are not listed in the page's request log

uBlock logs all network requests that go through it. Be sure you select the proper tab in the tab selector in the logger.

**Comment by justastranger** [comment]
There is no exact URL, the issue simply occurs for the [spotify webplayer](http://play.spotify.com/), and yes, I was certain that I had the proper tab opened, 
![ss 2015-08-25 at 01 11 52](https://cloud.githubusercontent.com/assets/6827479/9475218/ea19a572-4b2a-11e5-9434-1e6deaf936ae.png)
As for settings
![ss 2015-08-25 at 01 14 35](https://cloud.githubusercontent.com/assets/6827479/9475275/470352d8-4b2b-11e5-9ed4-6ca16f38424c.png)

If you actually need steps for reproduction, start playing something, an ad eventually plays after a number of songs.

**Comment by gorhill** [comment]
Can you try: `||d7zatysqm84hv.cloudfront.net/mp3-ad/*`?

**Comment by justastranger** [comment]
Ads still played.

**Comment by gitarra** [comment]
No ads here.

Firefox 43.0a1 (2015-08-25)
uBlock Origin v1.0.0.1

**Comment by justastranger** [comment]
I've been getting NAPA and Duncan Donuts ads all day :\

**Comment by shytikov** [comment]
The issue, as far I can tell happens due to upgrade to new PapperFlash. And relevant to Chrome only.

**Comment by gorhill** [comment]
Workaround: <https://github.com/gorhill/uBlock/issues/675#issuecomment-137978118>.
