### ISSUE TITLE
Thousands of requests per second

### ISSUE THREAD

**Issue by medecau** [gorhill/uBlock#634]
.1 Google Chrome 44 (64-bit) + uBlock Origin 1.0.0.1
.2 default everything
.3 navigate to page
.4 http://www.thestar.com/sports/hockey/2015/08/24/russia-fined-115000-for-snubbing-canadas-anthem-at-world-hockey-championships.html
.5 wait a few seconds
.6 observe the block counter

I noticed this because the computer fans started blowing. Chrome listed uBlock Origin with 99% cpu use. uBlock Origin had hundreds of thousands of requests blocked by that time.
Not sure if uBlock Origin can do anything about it but disabling bad behaving JS would be nice.

**Comment by gorhill** [comment]
This is a web site and/or filter issue, not a uBlock issue. I block 3rd-party scripts/frames by default, and I don't see this behavior.
