### ISSUE TITLE
Scrolling in advanced mode

### ISSUE THREAD

**Issue by pnsantos** [gorhill/uBlock#635]
Not sure if this is a uBlock Origin problem or an issue with my synaptics drivers but whenever I try to do two-finger scrolling in advanced mode while mousing over the dashboard (that appears when you click the icon on the toolbar) the uBlock Origin the dashboard just flickers and disappears. I can see the mouse icon turn to the scroller indicator. Works fine if I click the scrollbar and drag though.

Windows 8.1 x64
Synaptics 18.0.7.103
Lenovo T440p laptop
uBlock Origin 1.0.0.1
Firefox 40.0.2

**Comment by gorhill** [comment]
Does this happen with the popup UI (what you call the _dashboard_) of any extension?

**Comment by pnsantos** [comment]
Thx for the fast reply gorhill (and thx for all the work you have put into this little gem). Weird thing, the "problem" stopped happening, I can't reproduce it anymore. Maybe it was a FF gfx "glitch" ? (at the time I dind't think of trying other popup UIs, the only other one I have is lastpass but it isn't scrollable).

Sorry for the bother. Closing this.
