### ISSUE TITLE
SpeedTest.net ads appearing

### ISSUE THREAD

**Issue by PolarisBeaver** [gorhill/uBlock#636]
On http://www.speedtest.net/ there is 2 ads, one on top initially, and another one on the left side which shows up after completing a speed test. I understand you may not be directly involved with the ad lists, however I don't know who to report this to, if you happen to know which ad list can be submitted to. Can close issue if you need me to report elsewhere.

**Comment by PolarisBeaver** [comment]
....nevermind, should have read the CONTRIBUTING.md

**Comment by gorhill** [comment]
See #626.
