### ISSUE TITLE
Weather.com seems to be using old data in a cache somewhere.

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#638]
This problem seems to happen with all adblockers.

Weather.com has forecasts which are usually every 15 minutes.  With uBlock Origin the forecasts will vary considerably as far as the date/time displayed.  I've had forecasts that were from the previous day.  It's not just forecasts that are affected.  If old data is being used then just about anything can be out of date.

It seems that if I use the option' Purge All Caches' on the '3rd party filters' screen that will 'jump start' weather.com and for the moment things are as they should be.  But from then on things begin to change again.

This problem has been driving me nuts for a long time.  It used to work months ago.  Perhaps weather.com is doing something different.  

btw... This only seems to be a problem on Firefox.  I've tried IE and Edge and they report correctly.

**Comment by gorhill** [comment]
3rd-party filter issue.

**Comment by streetwolf** [comment]
weather.com fixed the problem via a workaround.  They claim there is a bug in Fx39+ in the way they handle the cache.
