### ISSUE TITLE
[Suggestion] Add tooltips for elements and buttons

### ISSUE THREAD

**Issue by rosolko** [gorhill/uBlock#639]
Hi, 

It would be nice, if you add tooltips with element name or functions, when you hover the mouse on the element.

For example:
On the main form, when you click on the addon icon and hover element on some icon, like picker or network request, or element, that disable font - show a tooltip about function.

That would be helpful for most new, or not experience users.

Thanks.

**Comment by Piter432** [comment]
Tooltips are seen in not-advanced mode. If you enable advanced mode, the tooltips will not show.

**Comment by rosolko** [comment]
For the network request log it isn't work. Even when switched off advanced mode.

**Comment by quickfold** [comment]
I know gorhill says "Tool tips are useful for novice users, but can become annoying to advanced users. Tool tips are turned off for advanced users."

Why can't this just be a preference item? I want the advanced features, but (woe is me) my memory isn't so great for icons and I WANT tooltips or text under the icons to help me remember their purpose. I am forced to use novice user mode just for the tooltips even though I also want the advanced features.

Please change this to optional!

**Comment by gorhill** [comment]
I am opened to the idea, it's why I did not close issue #451 -- of which this bug is a duplicate (so closing as _duplicate_).
