### ISSUE TITLE
[Firefox] Global uBlock installation on Ubuntu

### ISSUE THREAD

**Issue by jocooza** [gorhill/uBlock#640]
Installing uBlock Origin globally on Ubuntu 12.04 or 14.04 will produce the following error when starting Firefox 40 from the terminal:
```
addons.xpi	WARN	Exception running bootstrap method startup on uBlock0@raymondhill.net:
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) 
[nsIAppShellService.hiddenDOMWindow]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  
location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> file:///usr/lib/firefox/browser
/extensions/uBlock0@raymondhill.net/bootstrap.js :: startup/onReady :: line 64"  data: no] Stack 
trace: startup/onReady()@resource://gre/modules/addons/XPIProvider.jsm -> file:///usr/lib/firefox
/browser/extensions/uBlock0@raymondhill.net/bootstrap.js:64 < startup()@resource://gre/modules
/addons/XPIProvider.jsm -> file:///usr/lib/firefox/browser/extensions/uBlock0@raymondhill.net
/bootstrap.js:97 < XPI_callBootstrapMethod()@resource://gre/modules/addons
/XPIProvider.jsm:4638 < XPI_startup()@resource://gre/modules/addons/XPIProvider.jsm:2359 < 
callProvider()@resource://gre/modules/AddonManager.jsm:221 < _startProvider()@resource://gre
/modules/AddonManager.jsm:703 < AMI_startup()@resource://gre/modules
/AddonManager.jsm:874 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2514 < 
AMC_observe()@resource://gre/components/addonManager.js:55 < <file:unknown>
```
uBlock icon is not shown in the toolbar. The buttons 'Show Dashboard' and 'Show Logger' in the Add-ons Manager are blank. After restarting Firefox everything works as expected.

Steps to reproduce:

1. `$ wget "https://addons.mozilla.org/firefox/downloads/latest/607454/addon-607454-latest.xpi"`
2. `# mkdir /usr/lib/firefox-addons/extensions/uBlock0@raymondhill.net`
3. `# unzip addon-607454-latest.xpi -d /usr/lib/firefox-addons/extensions/uBlock0@raymondhill.net/`
4. `# chmod -R a+r /usr/lib/firefox-addons/extensions/uBlock0@raymondhill.net/`
5. `$ firefox`

**Comment by afrayedknot** [comment]
This happens on CentOS 7 x64 also, with the latest Firefox ESR so not Ubuntu specific.

Just commenting because I had previously opened a duplicate issue about the same problem until I saw this.

**Comment by jocooza** [comment]
I have found a question on stackoverflow that contain a similar error message:

http://stackoverflow.com/questions/24679282/hiddendomwindow-failed-after-browser-restart

Could the proposed solution also solve this issue?

**Comment by gorhill** [comment]
@jocooza Thanks, I will give this a try when I have time.
