### ISSUE TITLE
http://www.speedtest.net seems to have caught up to the new uBlock filter

### ISSUE THREAD

**Issue by kintpuash** [gorhill/uBlock#641]
test site: http://www.speedtest.net

text it now shows: 

>Your ad blocker is breaking Speedtest.net. It appears that your ad blocker is causing Speedtest.net to not function properly. Please disable it or whitelist the speedtest.net domain to resolve the issue.

Tested in Firefox 41.0b2 and Chrome 44.0.2403.157 (64-bit)

**Comment by typhoon71** [comment]
Firefox 40.0.2 here, uBlock 1.1.0.0rc1, but I can't reproduce.
I have noscript allowing only speedtest.net, and ublock just has a "2" on the icon.
I see no ads at all and I can test speed, see old results, change prefs...

**Comment by typhoon71** [comment]
I read the commit and the other related post.
So it was only affeting some browsers?
And it's fixed with that custom filter? Will that be added to the custom filters?

**Comment by kintpuash** [comment]
@typhoon71 

see #626 

Site behavior seems tied at least to IP location if not other variables. The new filter appears to work well.

**Comment by typhoon71** [comment]
OK, I did read 626 but I didn't know if it was working now (as I wrote here, I don't see those ad).
Thanks for the info, since I often recommend speedtest.net in place of similar stuff.
(well, it's not a -certified- result but it's a good indicator of line quality)
