### ISSUE TITLE
Whitelist Ads

### ISSUE THREAD

**Issue by GRMrGecko** [gorhill/uBlock#644]
I want to be able to say that I allow these ads or these ad tracking sites. In other words undo a specific block done by an EasyList.

Example: I do not mind Google Ads, so I want to allow Google Ads so at least sites using Google Ads makes money.

Example 2: I do not mind tracking if it's done by the site itself and not a third party, using a program such as Piwik. So I want to allow Piwik instead of blocking it.

I know there is a whitelist, but that is for allowing all ads on a specific site.

**Comment by gorhill** [comment]
Create your own custom filters?

**Comment by GRMrGecko** [comment]
I tried doing so for piwik and failed. I haven't tried with Google Ads.

**Comment by gorhill** [comment]
> I tried doing so for piwik and failed

Nobody can help you if you don't provide any details at all. Be very specific all the time about everything. See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by gorhill** [comment]
Also consider learning about [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering): `allow` rules, generally not that useful, are actually a good match for what you want, i.e. you could easily point-and-click to globally allow ads from whatever are the Google servers hostnames.

**Comment by GRMrGecko** [comment]
Ok, I just learned the exception rule is @@ and I can add as a filter
@@*piwik*
Now piwik is allowed and I can also allow google ads using this new knowledge.

Sorry for taking your time.
