### ISSUE TITLE
Removes github folder when named facebook

### ISSUE THREAD

**Issue by PuercoPop** [gorhill/uBlock#649]
When navagitation github repositories.

- See here: https://github.com/jgeboski/bitlbee-facebook/

**Comment by gorhill** [comment]
To emphase how the logger is the go-to tool in uBlock Origin:

![a](https://cloud.githubusercontent.com/assets/585534/9523157/9ec68680-4ca6-11e5-9524-c9b727503693.png)

**Comment by gorhill** [comment]
Also marking as _invalid_ because of pretty much no details provided at all as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues).
