### ISSUE TITLE
[Suggestion] Preview element picker filters

### ISSUE THREAD

**Issue by trlkly** [gorhill/uBlock#650]
It would seem not to be too difficult to add a preview button to the option in Add-on picker mode. When clicked, it would temporarily apply the selected hiding rule. It you click "Quit," it would automatically be removed. If you clicked "Create" then you'd just leave the rule in the list.

This would make it more convenient to test the results, as sometimes it's not 100% obvious what will disappear or how other items will move around.

I wouldn't ask if it didn't seem like a fairly easy-to-implement addition. I notice you have approved other Suggestions that are simple, and have left plenty more not deleted.

Also, I understand you don't like demands or people begging for features. That's not what I'm doing. It just seems like an obvious thing that is missing, making things more convenient with only a small change.

**Comment by gorhill** [comment]
For translator:

![a](https://cloud.githubusercontent.com/assets/585534/14582201/85ebfb4e-03cc-11e6-8f9c-c13ba4ef6183.png)

**Comment by happysurf** [comment]
This great feature works fine on Firefox 46beta but in Aurora 47 (with e10s) the "Preview" button doesn't appear.

**Comment by gorhill** [comment]
Works fine here on Nightly 48.0a1 (2016-04-16).

Any error message in the browser console?

**Comment by happysurf** [comment]
No console error and the inspector only report the Create, Pick and Quit buttons.
Very strange thing.

**Comment by Hrxn** [comment]
I'm not sure, but is e10s on by default in Aurora? So far, only Nightly should have it, I think.

Anyway, you should be able to check this if you look for the 'e10s' at the end of the tab info-tip.

**Comment by gorhill** [comment]
> inspector only report the Create, Pick and Quit buttons

Only sensible explanation is that you are not running uBO 1.6.9b1 on that installation.

**Comment by happysurf** [comment]
After a new (?) 1.6.9b1 installation the "Preview" works fine, maybe I forget the installation on Aurora (I have too many Firefox versions on my PC).
Thank you for this great addition.
