### ISSUE TITLE
Filter lists from around the web

### ISSUE THREAD

**Issue by wd401959** [gorhill/uBlock#653]
Thanks for all your efforts.
The list shows changes at https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web
but nowhere does it show the changes.
Would you please highlight new changes in the list with dates to make it easier to determine what has changed.
ie: added 11/11/15, deleted 11/10/15, changed 10/11/15
thanks again

**Comment by r-a-y** [comment]
You can view the revision history here:
https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web/_history

Hope that helps.
