### ISSUE TITLE
Entire tab is blocked and history is overriden because of iframe form submit

### ISSUE THREAD

**Issue by LordJZ** [gorhill/uBlock#654]
This piece of code is extracted from aliexpress.com which has been failing to load in Firefox 40 with uBlock Origin + EasyPrivacy enabled for quite some time already. #338
```
<html><head></head><body><script>
var t = {
url: window.location.href
};
var r = document.createElement('div');
var n = 'page-timing-' + (new Date).getTime();
r.innerHTML = '<iframe width="0" height="0" id="' + n + '"name="' + n + '" frameBorder="0" style="top: -100%; position: absolute;"></iframe>';
document.body.appendChild(r);
var i = document.createElement('form');
i.style.display = 'none';
i.target = n;
i.method = 'POST';
i.action = ('https:' === document.location.protocol ? 'https://' : 'http://') + 'stat.gmonitor.aliimg.com/stat.htm';
for (var a in t) {
var o = document.createElement('input');
o.type = 'hidden';
o.name = a;
o.value = t[a];
i.appendChild(o)
}
var s = document.createElement('input');
s.type = 'submit';
s.value = '';
i.appendChild(s);
document.body.appendChild(i);
i.submit()
</script></body></html>
```

To reproduce, copy the code to local .html file and open it with the browser.

There are 2 problems here:

1. The entire page is blocked by the "`uBlock Origin has prevented the following page from loading` window. This must not happen. Instead this window should be displayed in the iframe.

2. The last history item is overriden, so opening the history and/or trying to go back redirects the browser to the URL the user visited *before* going to the page opening the iframe. This cannot be reproduced with a local file, but can be reproduced on aliexpress.com.

**Comment by gorhill** [comment]
Provide proper details please: see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues).

If a page is blocked because of strict blocking, you have the [choice to turn off strict blocking for a site](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking) if it bothers you.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/9560485/7df5aa50-4de4-11e5-9316-56481efb17fd.png)

**Comment by LordJZ** [comment]
WTF? The url is given, it's aliexpress.com.
> If a page is blocked because of strict blocking, you have the choice to turn off strict blocking for a site if it bothers you.

Attempt number 3: the strict blocking is applied to a **DIFFERENT** page other than the one is **INTENDED** to be filtered.
Filtered url: gmonitor.aliimg.com
Blocked url: aliexpress.com **OR ANY OTHER USING THE TECHNIQUE DESCRIBED ABOVE**

**Comment by gorhill** [comment]
> The url is given, it's aliexpress.com

My bad, I was trying with Chromium. I can reproduce with Firefox Nightly. However, once I permanently disable strict blocking for `stat.gmonitor.aliimg.com`, I don't see any more pages strict blocked on aliexpress.com.

**Comment by gorhill** [comment]
Steps:

1. uBlock Origin with default settings, Firefox 40/Nightly.
1. Open a tab to <http://www.aliexpress.com/>.
1. Click "Consumer Electronics" in the top-left corner menu.
1. Click "Camera and Photo" in the list.
1. A new tab opens for the clicked link.
1. Shortly after the page loads, uBlock's strict-blocking page appears.
    - If it does not appear, close the tab an go to 4.
1. "uBlock Origin has prevented the following page from loading: `http://stat.gmonitor.aliimg.com/stat.htm`".
1. Click "Permanently" to permanently disable strict-blocking for `stat.gmonitor.aliimg.com`.
1. Blank page appears (issue #598).
1. Close the tab.
1. Go to 4.
1. uBlock Origin no longer strict block pages on <http://www.aliexpress.com/>.

So what is different on your side?

**Comment by LordJZ** [comment]
Surely disabling the filter works around the bug.

However, this is not a solution because the filter is legitimate and useful and I want to keep it.

Additionally, this is a potential attack on uBO users -- if users follow your advice, any website can force the user to disable any filter.

Finally, the repro steps are much simpler, as mentioned in the first post: save the code to an .html file and open it in the browser. The local file is blocked!

**Comment by gorhill** [comment]
> However, this is not a solution because the filter is legitimate and useful and I want to keep it

This does not disabled the filter, this disables the strict blocking for the site. [Wiki: Strict blocking](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking):

> This will prevent the web page proper for the site from being blocked by uBlock in the future: the filtering of the site will be done exactly as per ABP-filtering semantic

**Comment by LordJZ** [comment]
First of all, this is simply not true. You can clearly see the request going through to stat.gmonitor.aliimg.com/stat.htm both on aliexpress.com and local file if you temporarily or permanently disable strict blocking. Probably yet another bug.

Second, it doesn't really matter. Even if it just disables the strict blocking feature, it means that the vulnerability is still there -- it basically means the entire script blocking feature (filtering feature for now) is completely useless since any site can force a user to disable filtering for any particular other site.

Third, the main problem from the user's perspective is that a filter for site A blocks site B. Again, as it turns out, site B can be any other site. Fix this bug by displaying the blocked message in the iframe, and most of the other stuff is auto-fixed (probably except for the history issue). Since regular iframe (without form submit) is properly blocked and does not expose attack vectors, I consider the discussed problem a bug and not an intended feature.

Finally, I've found another probably related bug: disabling strict blocking on such a page redirects to the page being unblocked, which is wrong behavior. But most probably it will be fixed when the iframe block message will display in that iframe.

**Comment by gorhill** [comment]
> But most probably it will be fixed when the iframe block message will display in that iframe

Strict blocking will never result in the content of a frame to be replaced, just like images, the network requests are blocked and the corresponding DOM elements are collapsed.

I do see an anomaly with regard to `http://stat.gmonitor.aliimg.com/stat.htm`: Firefox fires the following (through the `shouldLoad` handler):

- A resource at `http://stat.gmonitor.aliimg.com/stat.htm` is of `TYPE_DOCUMENT`

then not long after:

- A resource at `http://stat.gmonitor.aliimg.com/stat.htm` is of `TYPE_SUBDOCUMENT`

So essentially Firefox is telling uBlock two resources, with the exact same URL but of different types, are being loaded. Apparently however, the first event is "fake", and this trips uBlock.

**Comment by LordJZ** [comment]
> Strict blocking will never result in the content of a frame to be replaced, just like images, the network requests are blocked and the corresponding DOM elements are collapsed.

Yep, that's how it works for "normal" iframes. It does not work this way for those "special" iframes with form submits. That is what these 2 github issues are talking about. Instead, uBlock is blocking the entire tab.

I'm fine with collapsing iframes -- that will solve the main issue. I'd personally prefer to show the block message inside the iframe at least for form submits -- this will make the blocking more explicit to the user, as form submit can be legitimate user input. However, showing the block message outside of the iframe -- the thing uBlock is doing right now -- is NOT okay for reasons described extensively in this github issue and #338.

**Comment by LordJZ** [comment]
Thanks, that fixed it! (love the cloud storage thing too)
