### ISSUE TITLE
Can't use bookmarklets when blocking inline scripts 

### ISSUE THREAD

**Issue by tyaremco** [gorhill/uBlock#655]
Occasionally, I want to block inline scripts on a page but also want to enhance the page with a bookmarklet (to join multipage articles, restyle the article for easy reading, etc.).  Bookmarklets don't run if inline scripts are blocked in the local scope (in Firefox).

**Comment by gorhill** [comment]
Related: <https://github.com/gorhill/uMatrix/issues/306>.
