### ISSUE TITLE
Unable to sync "My filters" to Cloud (Firefox)

### ISSUE THREAD

**Issue by fireattack** [gorhill/uBlock#656]
After clicking Upload, it still shows "..." and no download button:

![qq 20150829033035](https://cloud.githubusercontent.com/assets/4130991/9561126/5f8b25ee-4dfe-11e5-870b-bbd30d3bc8a2.png)

I can upload other settings without problem. e.g. 3rd-party filters:

![qq 20150829033043](https://cloud.githubusercontent.com/assets/4130991/9561144/ef2c3b70-4dfe-11e5-9600-dba9c7785b11.png)

**Comment by gorhill** [comment]
What version of uBlock?

**Comment by fireattack** [comment]
Sorry. I was using 1.1.0.0rc2.

**Comment by fireattack** [comment]
As I mentioned in #657, this is already fixed in rc3 but since the link in release was wrong so I accidentally installed rc2 for testing.. sorry for inconvenience and I closed this issue.
