### ISSUE TITLE
Sync status failed to show non-ANSI characters

### ISSUE THREAD

**Issue by fireattack** [gorhill/uBlock#657]
![qq 20150829033043](https://cloud.githubusercontent.com/assets/4130991/9561135/92dc4720-4dfe-11e5-9ba3-d9c81ecfe62c.png)

As you can see, the characters before and after my user name "Administrator" is messed up. I suppose they should be Chinese characters (I'm using Chinese OS and Firefox), but didn't get encode/decode correctly.

**Comment by gorhill** [comment]
uBlock version please. See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by fireattack** [comment]
@gorhill I was supposed to try it in the newest version (rc3), however the link [in your rc3 release](https://github.com/gorhill/uBlock/releases/tag/1.1.0.0rc3) is actually rc2:

(I mean this link: https://addons.mozilla.org/firefox/downloads/file/337402/ublock_origin-1.1.0.0rc3-sm+fx+an.xpi)

**Comment by gorhill** [comment]
> however the link in your rc3 release is actually rc2

Weird, I got b2 on my side. Let me look into this.

**Comment by fireattack** [comment]
Yeah, it's b2, my typo.

**Comment by gorhill** [comment]
Ok, my bad, I understood incorrectly how AMO linked to beta versions, and rc3 ended up pointing to b2. It's fixed now. Can you verify again the issue with the latest build? Probably you were using a version which did not have the fix for Unicode characters.

**Comment by fireattack** [comment]
Yeah, it's all fixed! And the AMO version does have "rc3' there:

![default](https://cloud.githubusercontent.com/assets/4130991/9562827/2ba49e74-4e3d-11e5-8161-8a7e54dbc692.png)

The attached xpi in release page doesn't have "rc3" text here.

**Comment by gorhill** [comment]
> The attached xpi in release page doesn't have "rc3" text here

Link is now fixed, it was really pointing at b2, an older version. Sorry for the inconvenience.
