### ISSUE TITLE
Links in programs open Fx Nightly in a blank new tab.

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#659]
In most cases when I click on a link that appears in another program, Fx opens up to a blank new tab instead of the link's page.  If Fx is already opened it seems to work fine. I narrowed it down to uBlock Origin by disabling my add-ons .

Any ideas on how to fix this?

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by streetwolf** [comment]
Windows 10 Pro x64 with all Windows 10 updates.
Fx43 Nightly
uBlock Origin 1.1.0.0rc3
All uBlock options and filters are OFF (to make things easier)
To test...grab the program CPU-Z @ http://www.cpuid.com/softwares/cpu-z.html
Run CPU-Z and select the About tab and click on the first link www.cpuid.com

CPU-Z is just one of many programs that cause the issue.  Sometimes I get to the link in a program with uBlock Origin enabled.  But in every case I can get to links in programs when uBlock Origin is disabled in Fx.

As I stated I disabled all options and filters.  I guess we can rule these out, so it must be uBlock Origin itself.

**Comment by streetwolf** [comment]
It looks like this is a problem with e10s.  When I turn off e10s in the Options menu of Fx all the links in other programs work fine.  When e10s are on I get the problem.

So it appears uBlock Origin and e10s don't play nicely when Fx is opened via another programs links.

**Comment by gorhill** [comment]
When this occurs, any error message related to uBlock in the browser console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>J</kbd>)?

**Comment by streetwolf** [comment]
There is nothing regarding uBlock in the browser console.

**Comment by streetwolf** [comment]
Raymond, have you confirmed this?

**Comment by gorhill** [comment]
I don't have native Windows, I need to launch a VM with Windows 10, I did not try your test case yet.

**Comment by streetwolf** [comment]
Did a lot more testing and here's the bottom line so far.

Links within other programs work under any of these conditions:
1. uBlock disabled with or without e10s
2. uBlock enabled and e10s disabled
3. Firefox already open under any conditions.

There were times that I got to a site with uBlock enabled.  I think this was due to testing.  It appears that when I enable uBlock again I need to run Fx, exit it, and then run a link within a program.  

If you would like to use TeamViewer to gain remote access to my system I can show you what's happening and maybe you can do some debugging.  Let me know and I'll send you the TV codes.  Is there a PM function here to do that?

**Comment by streetwolf** [comment]
Found out that doing a restart within Fx also produces a blank tab page.  The 3 conditions above must  be followed.  I happen to use a restart add-on found here: newhttps://addons.mozilla.org/en-US/firefox/addon/re-start/?src=ss

I suspect any sort of restart would produce the same results.  Installing a non-restartless add-on probably does the same thing.

**Comment by streetwolf** [comment]
I did see a couple of uBlock messages in my browser console after doing a restart with e10s enabled.  The last two entries at the bottom.

:TypeError: container is null
Stack trace:
style@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel/utils.js:386:1
onContentReady@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel/utils.js:280:7
EventListener.handleEvent*EventTargetInterposition.methods.addEventListener@resource://gre/modules/RemoteAddonsParent.jsm:624:5
AddonInterpositionService.prototype.interposeProperty/desc.value@resource://gre/components/multiprocessShims.js:160:52
make@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel/utils.js:309:3
setup@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel.js:150:16
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/disposable.js:48:56
dispatch@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/method/core.js:119:12
Disposable<.initialize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/disposable.js:71:17
constructor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/heritage.js:146:23
create_firefox_panel@resource://gre/modules/commonjs/toolkit/loader.js -> resource://support-at-lastpass-dot-com/lastpass/lib/main.js:1187:154
onLoad@resource://gre/modules/commonjs/toolkit/loader.js -> resource://support-at-lastpass-dot-com/lastpass/lib/main.js:1191:51
doDelayedOnload@resource://gre/modules/commonjs/toolkit/loader.js -> resource://support-at-lastpass-dot-com/lastpass/lib/main.js:1531:229
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://support-at-lastpass-dot-com/lastpass/lib/main.js:1532:251
evaluate@resource://gre/modules/commonjs/toolkit/loader.js:278:19
load@resource://gre/modules/commonjs/toolkit/loader.js:330:5
CuddlefishLoader/options<.load@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Users/garys/AppData/Roaming/Mozilla/Firefox/Profiles/090t1z3z.default/extensions/support@lastpass.com/bootstrap.js -> resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18
main@resource://gre/modules/commonjs/toolkit/loader.js:747:10
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:744:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:776:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:711:7
readURI/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/net/url.js:50:9
NetUtil_asyncFetch/<.onStopRequest@resource://gre/modules/NetUtil.jsm:128:17
Utils</<.loadURI@resource://flashstopper/modules-cui/utils.jsm:71:13
initFromFiles@chrome://flashstopper/content/content.js?0.29643049387363485:147:30
ContentHandler</<.init@chrome://flashstopper/content/content.js?0.29643049387363485:45:13
@chrome://flashstopper/content/content.js?0.29643049387363485:193:1
tbb.onBeforeCreated@chrome://ublock0/content/js/vapi-background.js:2578:9
CustomizableUIInternal.wrapWidgetEventHandler/aWidget[aEventName]@resource:///modules/CustomizableUI.jsm:2368:16
CustomizableUIInternal.buildWidget@resource:///modules/CustomizableUI.jsm:1310:9
CustomizableUIInternal.getWidgetNode@resource:///modules/CustomizableUI.jsm:859:16
CustomizableUIInternal.insertNodeInWindow@resource:///modules/CustomizableUI.jsm:1112:26
CustomizableUIInternal.insertNode@resource:///modules/CustomizableUI.jsm:1098:7
CustomizableUIInternal.onWidgetAdded@resource:///modules/CustomizableUI.jsm:904:5
CustomizableUIInternal.notifyListeners@resource:///modules/CustomizableUI.jsm:2071:11
CustomizableUIInternal.createWidget@resource:///modules/CustomizableUI.jsm:2179:9
this.CustomizableUI.createWidget@resource:///modules/CustomizableUI.jsm:3196:1
tbb.init@chrome://ublock0/content/js/vapi-background.js:2642:9
@chrome://ublock0/content/js/vapi-background.js:2663:5
@chrome://ublock0/content/js/vapi-background.js:29:2

**Comment by streetwolf** [comment]
Did a lot of testing and it appears the problem is some sort of conflict between the add-on FlashStopper and uBlock Origin.  I posted the problem over at the forum that the author of FS uses.  You can read it here http://forums.mozillazine.org/viewtopic.php?f=48&t=1483305&p=14308397#p14308397

**Comment by streetwolf** [comment]
The developer of FlashStopper provided a workaround for my problem.  Seems there was a conflict when the uBlock and FS icon was on the toolbar, in my case the Bookmarks toolbar.  Moving the uBlock icon to the hamburger menu was one way to fix the problem.  I opted for the FS developers workaround so I can place it on the toolbar.  I'm not sure where the fault lies. I'll let you decide whether to close this incident.

**Comment by gorhill** [comment]
Couple of fixes have been brought to uBO since then, most all related to ensuring the `readyState` of whatever document uBO had to deal with reached the `complete` status. So I will guess the issue here was related to this. Reopen if this is still happening.
