### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by Havokdan** [gorhill/uBlock#66]
Good morning, sorry nag, but the version that is in the Opera store is still under your responsibility? He is out of date, I wonder if you will send your version there?

**Comment by gorhill** [comment]
Yes, I plan to post an update soon.

**Comment by Havokdan** [comment]
Thanks for the answer, just one last question, if I may, the uBlock operates in the store will be the version of Chris and you cast the uBlock0 there? Or you will update the version that already exists?
Since now, I leave my services for such a great software.

**Comment by gorhill** [comment]
uBlock in Opera store will be uBlock Origin.

**Comment by gorhill** [comment]
Submitted to the Opera store.

**Comment by petersaints** [comment]
Shouldn't you rename it to uBlock Origin on the Opera Store? This way you avoid confusion if the uBlock author decides to make his version available for Opera.
