### ISSUE TITLE
Block ext -> .exe .bat .dll .sh .dmg, .cmd, .cpl, .lnk

### ISSUE THREAD

**Issue by ruy-benton** [gorhill/uBlock#662]
Hi,

This is a Question, not an Issue

Firefox -> Mac, Linux, W$N

I'm blocking:
.exe .bat .dll .sh .dmg, .cmd, .cpl, .lnk, .pif, .scr, .vbs, .vbe, .vb, .ws, .wsc, .wsf,.msi, .dll, .reg, .jse, .bas, .chm, .scf, .sct

in "My filters"

It's the correct ... procedure ... any other way?

And to protect Firefox ... .XPI?
But he don't update ?

Thank for your comments

**Comment by gorhill** [comment]
I can't answer without knowing what you are trying to achieve with those filters.

**Comment by ruy-benton** [comment]
Thank you for your answer.

Most of virus,  malware enter via Browser.

I'm trying to block all malic. code
Anti-Virus test the .ext of the files.

If some page download any of the ext ... uBlock catch

Kind regards,

**Comment by gorhill** [comment]
Yes, _"My filters"_ is the place to enter our own custom filters. Next time please ask on a forum (for example Reddit). Only issues/bugs should be filed here. See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by ruy-benton** [comment]
Thank you for your comments,
In future I will Q. there.
