### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by hant0508** [gorhill/uBlock#664]
It seems rather strange that "custom" in Russian translation is written with a lowercase letter, while all the other tabs - with a capital.
![screenshot_5](https://cloud.githubusercontent.com/assets/12861787/9566999/e522aae4-4f23-11e5-922f-c66cc86b637f.png)

**Comment by gorhill** [comment]
Can you comment on https://crowdin.com/translate/ublock/13/enca-ru about this? This is where translations are done.

**Comment by zummuz** [comment]
Sorry, my mistake. I haven't noticed its from tab title and thought it from main popup UI. I would notice it later, I use stable version. Thank you for remark and thank gorhill for correction

**Comment by gorhill** [comment]
Fixed in 12249b232637e99b629d241a22ec0a960092758d.
