### ISSUE TITLE
Blocking icons from medium.com/_/static

### ISSUE THREAD

**Issue by octref** [gorhill/uBlock#665]
This morning I found uBlock origin starts to block medium like and comment buttons.

Previously:
<img width="727" alt="screen shot 2015-08-30 at 10 03 15 am" src="https://cloud.githubusercontent.com/assets/4033249/9567572/739c72e4-4efe-11e5-9a1c-d9d8d5ab1fd9.png">

Now:
<img width="738" alt="screen shot 2015-08-30 at 10 04 26 am" src="https://cloud.githubusercontent.com/assets/4033249/9567574/85572a88-4efe-11e5-9796-19e5ad629230.png">

Specifically, you are blocking the following request:

From request log:
```
09:58:14		||medium.com/_/stat	--	image	https://medium.com/_/static/_/fp/icons/icons.fmpTqLjNd8xw9NvZvTWWXQ.svg#svg-bell25px
```

The problem should be that you are blocking `medium.com/_/stat`, and that rule wrongly affected `medium.com/_/static`.

My browser is Chrome 44.0.2403.157, and uBlock origin 1.0.0.1.

**Comment by gorhill** [comment]
EasyPrivacy issue, which [they already fixed](https://hg.adblockplus.org/easylist/rev/a76f7838a67f). Purge the cache for EasyPrivacy, then force an update.
