### ISSUE TITLE
You broke some filters

### ISSUE THREAD

**Issue by PekaFat** [gorhill/uBlock#669]
After v1.1.0.0 update all these filters stop working:
https://easylist-downloads.adblockplus.org/bitblock.txt
https://easylist-downloads.adblockplus.org/advblock.txt
https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
https://easylist-downloads.adblockplus.org/fanboy-social.txt
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
https://www.fanboy.co.nz/fanboy-antifacebook.txt
https://www.fanboy.co.nz/enhancedstats.txt
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

Why? :/

They all are fresh.

**Comment by gorhill** [comment]
What do you mean "broke"? Please explain what is "broken". You enumerate filter lists, not filters.

**Comment by PekaFat** [comment]
When i put these links in "Third-party filters" ublock does not load links from op-post, but before v1.1.0.0 all was fine...

![1](https://cloud.githubusercontent.com/assets/13280748/9583912/82b311ca-5016-11e5-83c5-40ff29d69b53.png)

**Comment by gorhill** [comment]
These are all part of the built-in filter lists, just selected them in the built-in filter lists.

Admittedly I did not expected users to import filter lists which are already available in the stock filter lists. There is absolutely no benefit in importing external filter lists which are already listed in the stock filter lists.

**Comment by PekaFat** [comment]
But before this update all is working, why now it stop working?

**Comment by gorhill** [comment]
Because of issue #602.

These stock filter lists were packaged with the extension, they are no longer packaged and are now listed as external stock filter lists, and their location (which is used as an identifier) is that of their remote location.

In retrospect, if I knew users were importing stick filter lists as custom filter lists, I would have added code to deal with this, but as said, I did not expect users importing filter lists which were already available as stock filter lists.

**Comment by PekaFat** [comment]
But maybe you can make rule:
if no checkboxes for default filters lists enabled in ublock - then allow put these links in custom filter list?

**Comment by PekaFat** [comment]
And some filters still packaged in extension
![default](https://cloud.githubusercontent.com/assets/13280748/9584192/7523db0a-5018-11e5-9518-e0c3cfd61e36.png)

**Comment by gorhill** [comment]
> And some filters still packaged in extension

Yes, as explained, filter lists which are selected by default will still be part of the package, because they have to work immediately without the need to download them the first time uBlock is launched.

**Comment by PekaFat** [comment]
packaged lists updating like non-packaged? when i press "update now" - all filter lists updating from their servers?

**Comment by gorhill** [comment]
> packaged lists updating like non-packaged?

Yes. But if you create a new installation of uBlock, the first time uBlock launches, EasyList will be fetched from local folder. After this, uBlock will update using remote server.

**Comment by PekaFat** [comment]
Ok, then all is fine, thanks!

**Comment by gorhill** [comment]
The fix might be a bit too late, but it is still useful if ever an older backup is restored.
