### ISSUE TITLE
Export an interface for addons to interact with uBlock

### ISSUE THREAD

**Issue by dhowe** [gorhill/uBlock#67]
See this [ticket](https://github.com/dhowe/AdNauseam/issues/234) over at AdNauseam
We'd would love to add support for ublock in our next release...

the way this works in adblock-edge can be seen [here](https://bitbucket.org/adstomper/adblockedge/src/a184cbb98c2e7f931e71e7dd2d19cfce03133f0c/lib/main.js?at=default) and [here](https://bitbucket.org/adstomper/adblockedge/src/a184cbb98c2e7f931e71e7dd2d19cfce03133f0c/lib/Public.jsm?at=default)

thanks!

**Comment by gorhill** [comment]
> AdNauseam works together with an 'Ad Blocker' simulating clicks on each blocked ad

Sorry but this go counter to what I am trying to accomplish here: give the means for users to reduce their privacy exposure, which is best accomplished by **not** connecting to remote servers in the first place.

**Comment by mushon** [comment]
@Gorhill, while we definitely share the concerns for data privacy, with Http://AdNauseam.io we're trying to take a slightly more subversive and playful approach to the subject of data surveillance. AdNauseam aims to use automated ad clicks to not only to protect privacy by making the collected data unusable but actually provide some agency against data hoarding ad networks. Some uBlock users have been interested in doing that and we would rather support your great work rather than tell them they can only get AdNauseam with other ad blockers.

Obviously it's your call, but I wanted to give you some extra input and encourage you to reconsider. Thanks!

**Comment by RandomAcronym** [comment]
@mushon Speaking for myself; connecting to a tracking network's servers at all is to be avoided whenever possible.

The only privacy conscious way of doing this I can think of would include a Sandboxed browser and VPN to stop any user data from being leaked.

**Comment by mushon** [comment]
We are trying to expand the privacy debate to a more expensive and political level and to go from individual protection into collective action, but I understand your concerns and as I said, it's your call. 

All the best,
Mushon.

**Comment by agilob** [comment]
The feature request is not about whitelisting some domains/sites, but about possibility to get access to interface of µblock, like adblock allows it. You might not agree with what AdNauseam does, but it is a 3rd party plugin, that is installed independently. It doesn't change how µblokc/adblock work, clicks are made only if user has AdNauseam installed, so it's users choice to visit the link.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by RandomAcronym** [comment]
:-1:

**Comment by SirCmpwn** [comment]
I suppose the thing that's wrong here is that uBlock is taking a stance because they disagree with AdNauseum. Refusing to add an API that allows it to be extended by other add-ons is detrimental to the software in general, despite the fact that it might be used by some projects like AdNauseum. Refusing to implement a useful feature because you disagree with one possible use-case is silly, just like RMS is doing with gcc right now (refusing to export the AST because he thinks it'll lead to people circumventing the GPL - but makes gcc less useful than clang).

**Comment by RandomAcronym** [comment]
@SirCmpwn Nice [Strawman](https://youtu.be/cGZkCPo7tC0) you got there.
>I suppose the thing that's wrong here is that uBlock is taking a stance because they disagree with AdNauseum. Refusing to add an API that allows it to be extended by other add-ons is detrimental to the software in general, despite the fact that it might be used by some projects like AdNauseum. Refusing to implement a useful feature because you disagree with one possible use-case is silly, just like RMS is doing with gcc right now (refusing to export the AST because he thinks it'll lead to people circumventing the GPL - but makes gcc less useful than clang).

Gorhill has stated, on multiple occasions, that he does not wish to spend **his free time** coding something he does not personally find useful, painting it as a refusal of some *cosmic duty* to do everything asked of him... frankly I find it insulting. 
Also calling it "an API" does not make it one, whatever you think that means.

**Comment by SirCmpwn** [comment]
Gorhill doesn't necessarily have to do it. The closing of this issue implies that it wouldn't be merged into uBlock if someone else does it. For the record, I have almost 200 Github repositories and I'm very well acquainted with the nature of being an open source software maintainer. The purpose of my comment is to justify the feature for inclusion into the codebase, regardless of who writes it.

Also, an API is exactly what this is. I'm not sure what you're going on about.

**Comment by CrisBRM** [comment]
@SirCmpwn Fork it, if people find it useful, they will flock to it.

**Comment by SirCmpwn** [comment]
I don't think that immediately degrading the discussion into the "fuck off and fork it" response is appropriate. Surely we can discuss the merit of a proposed feature without resorting to that.

**Comment by gorhill** [comment]
> Surely we can discuss the merit of a proposed feature

Right, the merit of **me** working on making this happens. I am not interested to work on this, it's a feature I will never use, and a feature which is opposite to the main goal of uBlock. Common sense dictates that somebody who believe in the merit of this feature should work on it.

**Comment by gorhill** [comment]
> Gorhill doesn't necessarily have to do it.

I don't want the code base to be tampered to support this, I am the one who has to maintain that code base. The most pragmatic solution is indeed to fork.

**Comment by mushon** [comment]
I realize and respect @gorhill's leadership on this project. He wrote the code, he maintains it and he has the vision for it. It is important to know this vision excludes extensibility for blocker add-ons along the lines of [Add-Art](http://add-art.org/), [Element Hiding Helper](https://addons.mozilla.org/en-US/firefox/addon/elemhidehelper/?src=ss) [Adblock Plus Pop-up Addon](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus-pop-up-addon/?src=ss), [Filter Uploader for Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus-filter-uploader/?src=dp-dl-oftenusedwith) and yes, also [AdNauseam](http://adnauseam.io). Currently, if you want to have such features you are indeed required to fork uBlock or just use something else. I don't want to see this project split over this, there are too many parallel efforts going on as it is. I do hope @gorhill might reconsider, for now we will continue to point our users at the other Blockers that do supports such extensibility.

**Comment by RandomAcronym** [comment]
"element hiding" GUI and pop-up blocker are both built into uBlock. no fork needed.
