### ISSUE TITLE
Not updating to 1.1.0.0 final when using development version

### ISSUE THREAD

**Issue by Smultie** [gorhill/uBlock#670]
As the topic title states; when using the Development version from AMO, it won't install 1.1.0.0 final over RC4, while I think that it should.

**Comment by Betsy25** [comment]
it'll probably update to the next beta or RC, which ain't a bad thing at all, and AFAIK, the latest development version on AMO is identical to the so called "final" version 1.1.0.0, so you're all fine, and a new version is on the way.

**Comment by Smultie** [comment]
Thanks for the reply @Betsy25

**Comment by gorhill** [comment]
> when using the Development version from AMO, it won't install 1.1.0.0 final over RC4, while I think that it should

It's a AMO feature, stable won't install over dev build, dev build won't install over stable. Not an issue, if you installed dev build, you always have the latest version available anyways.
