### ISSUE TITLE
Improvements for the UI to become more user friendly and intuitive

### ISSUE THREAD

**Issue by privacytoolsIO** [gorhill/uBlock#671]
First of all: Thanks for your great work on uBlock. We recommend your plugin on our [Website](https://www.privacytools.io/#addons).

I have a couple of suggestions to improve the usability:
- Add a link to the dashboard, clicking on the "uBlock Origin" link is not obvious enough.
- Use mouse hover descriptions / titles for all buttons
- The design of the on/off button is not obvious enough, it could use a message like "uBlock is on/off" underneath the big standby icon.

When it comes to usability, there is one basic rule: "Don't make me think" there is even a book about it. Currently uBlock is making the user think a lot, but it's easy to fix the usability issues.

**Comment by zummuz** [comment]
Hi @privacytoolsIO.

> Use mouse hover descriptions / titles for all buttons

There are tips on mouse hover but they appear only when checkbox for "I am an advanced user (Required reading)" is off.
https://github.com/gorhill/uBlock/wiki/Advanced-user-features
"Tool tips are useful for novice users, but can become annoying to advanced users. Tool tips are turned off for advanced users." - gorhill.

> The design of the on/off button is not obvious enough, it could use a message like "uBlock is on/off" underneath the big standby icon.

There is message, it shows up on hover on/off button when "I am an advanced user (Required reading)" is off. And there is popup tip for dashboard too :)

By the way, gorhill has addon called uMatrix. Its for advanced users and similar to NoScript and Policeman and also available for firefox.

**Comment by anewuser** [comment]
#451

**Comment by gagarine** [comment]
I agree tool tips are not accessible because you have to go over each button to know what the purpose of them instead of directly clicking on the right one.

**Comment by srus** [comment]
I think tooltips are useful even in expert mode. Some day you learn how every icon works, but then, after a long time, it is good to have a quick tip to remember what an icon actually does. I don't think tooltips are annoying at all.

**Comment by Matt-Deacalion** [comment]
I agree, as I find the UI a little difficult. I wasn't sure if the power button being blue meant it was on or off. Green and red for on and off would be more intuitive: https://github.com/Matt-Deacalion/uBlock/commit/e50f0d

**Comment by anewuser** [comment]
It was green, but @gorhill  found that:
>Green may lead to confusion, especially when the dynamic filtering pane is opened.

[Source](https://github.com/chrisaljoudi/uBlock/issues/745).

**Comment by gagarine** [comment]
@srus I mean real button with texts that are always visible.
Like:
![screen shot 2015-11-28 at 22 01 37](https://cloud.githubusercontent.com/assets/164074/11453856/9deb907a-961b-11e5-985a-9ee4bb9456eb.png)
You have icon and text..

**Comment by srus** [comment]
@gagrine, you are right, but that would require big changes in the UI. Having tooltips would be enough for me.

**Comment by ilu33** [comment]
I'd love to have tooltips in advanced mode. I'm a long time user of request policy so I should know my ways but uBlock and uMatrix give me tons of headaches. The matrix idea seems neat but there's not enough explanatory text or tooltip. The 2 colums in advance mode really need a header or at least a tooltip. Even if I figured it out once I'm prone to forget everything after some weeks.

**Comment by LimboSlam** [comment]
> I'd love to have tooltips in advanced mode. I'm a long time user of request policy so I should know my ways but uBlock and uMatrix give me tons of headaches. The matrix idea seems neat but there's not enough explanatory text or tooltip. The 2 colums in advance mode really need a header or at least a tooltip. Even if I figured it out once I'm prone to forget everything after some weeks.

@ilu33: I agree totally!    

Tooltips are fine with me though. The only problem I have is I don't know how to block a certain element for that individual website. For example, I don't want see social media buttons on every website, just on Pandora and a few others. But I can't do this because I don't understand how to use Ublock Origin in Advance Mode, like how the hell am I supposed to know what's global and local. There's no indication!

**Comment by gorhill** [comment]
First two points have been addressed since long ago. 3rd point, I disagree that it is confusing.
