### ISSUE TITLE
[Performance] manually extract class tokens

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#672]
Benchmarking latest browsers (Chromium 44, FF 40), `Element.classList` shows to be slower than manually extracting class tokens using `String.indexOf`.

Benchmark:
- Front page of cnn.com.
- Measurement = total time spent in `contentscript-end.js`/`classesFromNodeList` divided by number of class token extracted -- last value dumped after page is fully loaded.
- Averaging for 10 reload of cnn.com.

| | Chromium 44 64-bit | Firefox 40 64-bit |
| --- | --- | --- |
| Element.classList | 2.745 µs/token | 9.884 µs/token |
| String.indexOf | 1.633 µs/token | 5.736 µs/token |

Also: <http://jsperf.com/enumerate-classes>.

**Comment by publicarray** [comment]
Mac OS X 10.10.5 | Safari 8.0.8                  | Chrome 44.0.2403.157          | Firefox 40.0.3
---------------- | ----------------------------- | ----------------------------- | ---------------------------
classList        | 2,765,259 (±1.00%)            | 1,319,853 (±1.43%, 15% slower) | 810,357 (±2.36%, 61% slower)
while-indexOf    | 1,288,432 (±1.09%, 53% slower) | 1,544,353 (±0.62%)            | 2,083,323 (±3.22%)

Results in Ops/sec

**Comment by gorhill** [comment]
I rewrote the jsperf code to be closer to what is required to properly manually tokenize content of className: <http://jsperf.com/enumerate-classes/6>.

Results:
- Chromium 44: roughly break even between two methods
- Firefox Nightly: good improvement with manual tokenization

**Comment by gorhill** [comment]
The jsperf benchmark is just to roughly validate an idea. The real benchmark are the following code blocks.

Tokenize through classList:

    var cc = 0;
    var ta = 0;

    var classesFromNodeList = function(nodes) {
        if ( !nodes || !nodes.length ) {
            return;
        }

        var qq = queriedSelectors;
        var ll = lowGenericSelectors;
        var node, v, vv, len;
        var i = nodes.length;

        var t0 = window.performance.now();

        while ( i-- ) {
            node = nodes[i];
            vv = node.classList;
            if ( typeof vv !== 'object' ) { continue; }
            len = vv.length || 0;
            while ( len-- ) {
                v = vv[len];
                cc += 1;
                if ( typeof v !== 'string' ) { continue; }
                v = '.' + v;
                if ( qq.hasOwnProperty(v) ) { continue; }
                ll.push(v);
                qq[v] = true;
            }
        }
        ta += window.performance.now() - t0;
        if ( cc !== 0 ) {
            console.debug('%s µs/token (%d)', (ta * 1000 / cc).toFixed(3), cc);
        }
    };

Tokenize manually:

    var cc = 0;
    var ta = 0;

    var classesFromNodeList = function(nodes) {
        if ( !nodes || !nodes.length ) {
            return;
        }

        var qq = queriedSelectors;
        var ll = lowGenericSelectors;
        var v, vv, len, c, beg, end;
        var i = nodes.length;

        var t0 = window.performance.now();

        while ( i-- ) {
            vv = nodes[i].className;
            if ( typeof vv !== 'string' ) { continue; }
            len = vv.length;
            beg = 0;
            for (;;) {
                // Skip whitespaces
                while ( beg !== len ) {
                    c = vv.charCodeAt(beg);
                    if ( c !== 0x20 && (c > 0x0D || c < 0x09) ) { break; }
                    beg++;
                }
                if ( beg === len ) { break; }
                end = beg + 1;
                // Skip non-whitespaces
                while ( end !== len ) {
                    c = vv.charCodeAt(end);
                    if ( c === 0x20 || (c <= 0x0D && c >= 0x09) ) { break; }
                    end++;
                }
                cc += 1;
                v = '.' + vv.slice(beg, end);
                if ( qq.hasOwnProperty(v) === false ) {
                    ll.push(v);
                    qq[v] = true;
                }
                if ( end === len ) { break; }
                beg = end + 1;
            }
        }
        ta += window.performance.now() - t0;
        if ( cc !== 0 ) {
            console.debug('%s µs/token (%d)', (ta * 1000 / cc).toFixed(3), cc);
        }
    };

I will revisit once in a while to find out whether manually tokenizing is still appropriate.

I do not have access to a Safari browser. The jsperf benchmark re. Safari could be a jsperf benchmark artefact, the block codes above would really tell how the code perform when accomplishing its real purpose.

**Comment by publicarray** [comment]
I thought there is no support for Safari. So isn't safari irrelevant for now?

**Comment by CrisBRM** [comment]
@publicarray gorhill doesn't support safari.

>Safari
>There is no support for Safari for uBlock Origin.
>Best is that you install chrisaljoudi/uBlock, which has official support for Safari.
