### ISSUE TITLE
Add chip.de (or certain pages within chip.de which offer the "CHIP installer") to badware risks

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#673]
The German tech site chip.de sometimes offers software downloads through what they claim to be a "secure" CHIP installer. In fact, this is nothing more but a wrapper program bundling adware.

You can find an example of such a download here:
http://www.chip.de/downloads/ENBSeries-fuer-GTA-5_82717063.html

It is possible to use a manual download but the blue button is, of course, more prominent.

You can find sources for this adware tactics here (which, unfortunately are in German, but you can use Google Translate if you want):
http://anleitung.trojaner-board.de/chip-installer
http://www.randombrick.de/downloads-von-chip-de-ueber-den-chip-installer-vermeiden/

You can also take a look at Google images for the chip.de installer (which definitely show malware):
https://www.google.de/search?q=chip.de+installer&biw=1366&bih=605&source=lnms&tbm=isch&sa=X&ved=0CAkQ_AUoBGoVChMI8fL-qoPXxwIV5RbbCh3QdAze

**Comment by publicarray** [comment]
The mac version of the chip installer is detected as adware by 7 / 56 AV companies - [virustotal.com](https://www.virustotal.com/en/file/c977b9be0aeabcfa7f35beeb3958e69cecfc15beadc360c0e9140e1a5ee025f9/analysis/1441167513/). Such a shame, I used to download programs from them when I had win XP

**Comment by tobbi** [comment]
Is there any more info that you might need?

**Comment by gorhill** [comment]
And candidate for _Badware risks_ need to be documented there: <https://github.com/gorhill/uBlock/wiki/Badware-risks>. Once there are enough reference material for one candidate, I will add it to the filter list. The key is enough good reference material, and the more recent material the better. I will let you add to the wiki, I don't read German (please respect tidyness, alpha ordering by base domain, reverse chrono ordering for references, etc.).

**Comment by IDKwhattoputhere** [comment]
Can confirm. I already had to remove some Chip.de Installer crap from my relatives' devices.
Questions about the Wiki  page: Why is Chip.de not marked as candidate when it's not yet in the list? And why is 01net.com marked when it's already in there?

**Comment by krystian3w** [comment]
<p>Update <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="153673611" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/42" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/42/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/42">#42</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="185532658" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/178" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/178/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/178">#178</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="104376646" data-permission-text="Title is private" data-url="https://github.com/gorhill/uBlock/issues/673" data-hovercard-type="issue" data-hovercard-url="/gorhill/uBlock/issues/673/hovercard" href="https://github.com/gorhill/uBlock/issues/673">gorhill/uBlock#673</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="524202202" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/6587" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/6587/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/6587">#6587</a></p>

**Comment by krystian3w** [comment]
<p>Update <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="153673611" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/42" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/42/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/42">#42</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="185532658" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/178" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/178/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/178">#178</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="104376646" data-permission-text="Title is private" data-url="https://github.com/gorhill/uBlock/issues/673" data-hovercard-type="issue" data-hovercard-url="/gorhill/uBlock/issues/673/hovercard" href="https://github.com/gorhill/uBlock/issues/673">gorhill/uBlock#673</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="524202202" data-permission-text="Title is private" data-url="https://github.com/uBlockOrigin/uAssets/issues/6587" data-hovercard-type="issue" data-hovercard-url="/uBlockOrigin/uAssets/issues/6587/hovercard" href="https://github.com/uBlockOrigin/uAssets/issues/6587">#6587</a></p>
