### ISSUE TITLE
NOT AN ISSUE : uBlock Origin on Sept.1 Security Now Podcast.

### ISSUE THREAD

**Issue by Betsy25** [gorhill/uBlock#674]
Podcast : https://twit.tv/shows/security-now/episodes/523?autostart=false
:clap:

**Comment by zazdxscf** [comment]
It's also available on youtube: https://www.youtube.com/watch?v=dB9zKOJJYaI

**Comment by seanrand** [comment]
Nicely done. There were a few hiccups when he described dynamic filtering - could have made the difference between dynamic/static filtering more clear and his description of the noop rule was a bit off. Apart from that, good job emphasising that uBlock is already nicely featured in non-advanced mode, that's something I personally tend to forget about with advanced mode enabled.

I guess this could be counted as an endorsement of #451, separating tooltips from advanced mode.

You should probably cross-post this to [/r/ublockorigin](https://www.reddit.com/r/ublockorigin) as that's probably the better suited place for discussion.
