### ISSUE TITLE
[Warning] uBlock is not found when searching from about:addons

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#676]
Just reporting something I found by chance.
I'm puzzled, when searching from about:addons, the term "uBlock " doesn't give ublock origin as a result (nor uBlock), only adblock plus and others.
It is in the mozilla addon page(s), so why?

**Comment by gorhill** [comment]
Probably because you have uBlock already installed. If I search for "adblock", Adblock Plus is not reported either, but then I have it installed.

**Comment by typhoon71** [comment]
Okie, so it's expected. I never noticed that already installed addons were filtered out.
I expected uBlockO to show up, maybe with a "installed" icon of sort on it, but ... mozilla designs (tm).
