### ISSUE TITLE
And Kaspersky Protection Extension  4.6.0.377error.

### ISSUE THREAD

**Issue by potkeys2** [gorhill/uBlock#677]
caveat:
This extension can not be modified in response to a network request header "Content-Security-Policy", as this modification and another extension (uBlock Origin) had a conflict.

**Comment by gorhill** [comment]
No browser version provided, I will assume it is a Chromium-based browser.

Chromium does not allow more than one extension to modify a HTTP header. uBlock Origin modifies the CSP header when inline scripts are blocked. So you have to choose which extension will apply CSP.
