### ISSUE TITLE
filter list: hpHosts’ Ad and tracking servers 

### ISSUE THREAD

**Issue by androidland** [gorhill/uBlock#678]
can not update hpHosts’ Ad and tracking servers filter list anymore

**Comment by seanrand** [comment]
Works for me, with uBlock Origin master and Chromium.
But gorhill, is there a reason for requesting http://hosts-file.net/.%5Cad_servers.txt instead of http://hosts-file.net/ad_servers.txt ?

**Comment by gorhill** [comment]
@androidland Sometime the site can be down, out of uBlock Origin's control. You are not providing any details with your issue, it's impossible to help you without knowing exactly what issue you are experiencing, your browser/version, settings, etc.

@seanrand To prevent the network request to be filtered by EasyList, as the URL would match the `.net/ad_` filter in EasyList.

**Comment by androidland** [comment]
i am sorry
i am firefox 40 user and ublock0 1.1.0.1
the problem just can not add hpHosts’ Ad and tracking servers filter list anymore
when i click the hpHosts’ Ad and tracking servers filter list  link, its just open blank tab

so i must add it manual from http://hosts-file.net/ad_servers.txt

**Comment by seanrand** [comment]
Oh, I see. The asset viewer seems to be getting a ```999 No Hacking``` response when requesting the file from hosts-file.net.

**Comment by androidland** [comment]
ok thanks seanrand for the answer

**Comment by gorhill** [comment]
Yes, asset viewer is not using the proper URL, because double percent-encoding.
