### ISSUE TITLE
Allow blocking by header rules

### ISSUE THREAD

**Issue by Baldrs** [gorhill/uBlock#680]
Some pages with scrambled urls provide some headers like  X-Meta-Url: http://ad_uri/

Please add a feature to detect such requests by header and block them

**Comment by gorhill** [comment]
> Some pages

See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by RoxKilly** [comment]
The headers you're referring to are HTTP Response headers right?  They are shown only *after* a request and a connection to the remote server have been made, so blocking them would be like closing the barn after the horses have left.  In other words, uBlock stops requests from being made.  In the case of response headers, the request has already been made.

**Comment by gorhill** [comment]
Closing as invalid: concrete issues must be reported, solutions will then be investigated -- issues asking to implement solutions without concrete issues with detailed steps to reproduce will be closed as invalid.
