### ISSUE TITLE
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': 

### ISSUE THREAD

**Issue by kucenkelate** [gorhill/uBlock#682]
"Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': "

was shown for latest version - uBlock Origin 1.1.0.1

any info? Browser : Slimjet/chromium

**Comment by gorhill** [comment]
> was shown for latest version

Shown where? uBlock Origin does not make use of `canvas` elements.
