### ISSUE TITLE
hpHosts Problem

### ISSUE THREAD

**Issue by bkrucarci** [gorhill/uBlock#683]
Hello,

Can anyone tell me whats the problem with hpHosts ad server lists?
I cannot view the list from uBlock Origin filter list?
Does it discontinued?

Thanks,

**Comment by gorhill** [comment]
Fixed in #678.

**Comment by gorhill** [comment]
Just to be clear, the content of hpHosts is parsed and read fine by uBlock, it's just the display of its content from the _3rd-party filters_ pane which is broken.
