### ISSUE TITLE
Cannot watch the network operation (behind-the-scene) of extension in dashboard

### ISSUE THREAD

**Issue by enerai** [gorhill/uBlock#686]
I have installed the uBlock Origin v1.1.0.0 in Chrome 45.0.2454.85 (64-bit). 

I remember I could see the behind-the-scene network operation by extension (e.g. Xmarks, bookmarket sync) in the dashboard a few weeks ago. However, I cannot see these behind-the-scene network operations anymore, not only Xmarks but also all extensions.

BTW, I have a concern that whether some behind-the-scene operation could be blocked by uBlock in the case.

**Comment by CrisBRM** [comment]
https://github.com/gorhill/uBlock/issues/675#issuecomment-137978118

**Comment by gorhill** [comment]
See https://github.com/gorhill/uMatrix/issues/338.
