### ISSUE TITLE
Block urls clicked by user that have certain pattern to them

### ISSUE THREAD

**Issue by Mackbd** [gorhill/uBlock#688]
If this is possible, sorry I haven't been able to figure out how to do it.  Appreciate any help.

There are many sites that have sneaky links to Amazon (for example) with a affiliate code embedded in the url, such as this:

    http://www.amazon.com/dp/B00GDQ0RMG/?tag=[affiliate-code]

I hope uBlock can block it and save me from accidentally clicking on this links.  Or if not doable currently, perhaps a future feature.

**Comment by gorhill** [comment]
Use the `document` filter option, like so:

    `||www.amazon.com/dp/*/?tag=$document`

This will make web pages which match the filter be blocked through [strict blocking](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking).

**Comment by Mackbd** [comment]
OMG! Thank you so much, that works!  I had a feeling it needed strict blocking but just couldn't figure it out even after hours of crawling through forums and google.

I also just realized Amazon's tag can also be separated by **&**, so I amended this to my filters and it seems to be working great:

    ||www.amazon.com/*^tag=$document

Now as an aside, if uBlock can one day rewrite urls via regex that will be amazing... just a thought.  Thanks again.

**Comment by luxoflux** [comment]
Great, this also works for YouTube redirects/link tracking:

`||www.youtube.com/redirect?q=$document`

I've been trying to do this in Gmail as well, but without success. I think all Gmail redirects start with this URL: `mail.google.com/_/scs/mail-static/_/js/k=`. The filter works if I manually visit the URL from the address bar, but not if I click a link in an email.

**Comment by gorhill** [comment]
> The filter works if I manually visit the URL from the address bar, but not if I click a link in an email

What does the logger report? Strict blocking applies to network requests reported as type `doc` in the logger. This should help you identify the type of URL used for the redirect.

**Comment by luxoflux** [comment]
The URL isn't reported anywhere (logger or console) unfortunately. I guess Facebook calls them "link shims" <sup>[[1]](https://www.facebook.com/notes/facebook-security/link-shim-protecting-the-people-who-use-facebook-from-malicious-urls/10150492832835766)</sup> and I really despise their deceptive nature.

> [...] we install an onmousedown handler that modifies the link on the fly after the person has clicked it, so their browser hits the link shim first
