### ISSUE TITLE
Question about cloud backup

### ISSUE THREAD

**Issue by pnsantos** [gorhill/uBlock#690]
Hi there, I've tried using the cloud storage system and the upload seems to work ok (at least I see the name+date next to the icon being updated) but when I hit the download nothing seems to happen (temporary rules stay the same and there is no date+name next to the download icon). I have currently three firefox instances, one in OSX, another in Win8.1 and another in an Android device. "Normal" firefox sync is working ok between these machines.

Do I need to have addons or preferences enabled in firefox sync preferences? (I only have bookmarks and history enabled). I expected that if in one machine I hit upload then I could hit download in other machines and the uploaded settings would be downloaded.. am I doing something wrong?

**Comment by gorhill** [comment]
> I only have bookmarks and history enabled

I think you have to also check _Add-ons_ (which does is not available on Firefox for Android).

**Comment by pnsantos** [comment]
Yeahit worked thanks!
