### ISSUE TITLE
Make target URL in strict blocked referrer clickable 

### ISSUE THREAD

**Issue by jnns** [gorhill/uBlock#691]
Sometimes access to a site is blocked because the request is sent through a third-party referrer (mostly googleadservices.com, in my case). Users currently have the option to disable strict blocking the site in question permanently or temporarily.

In my opinion, a useful third alternative could be to make the warning page's target link clickable to directly visit the desired site without going through the third-party site at all. 

[See this image for reference.](https://cloud.githubusercontent.com/assets/206281/9717195/f09cac8c-5570-11e5-947f-9e2b3046b031.png)

The problem with this approach would be that the target URL might be difficult to extract. Sometimes there's more than one URL in the blocked site's address. But making all non-urlencoded URLs clickable would still be a benefit, I think.

**Comment by gorhill** [comment]
Yes, I have been thinking about doing something like this since a while.

**Comment by gorhill** [comment]
Is it possible for me to reproduce your case? I would like to use it as test case -- it looks like a good one given that the URL appears to contains many encoded URLs as parameters.

**Comment by gorhill** [comment]
Reference image:

![URL parsing](https://cloud.githubusercontent.com/assets/585534/9832014/bfb1b8f0-593b-11e5-8a27-fba472a5529a.png)

**Comment by TroudhuK** [comment]
This is one of your best features, can you just report it into uMatrix?
Ok ok you don't have time... But I don't know why, uMatrix has now the priority and blocks pages before uBlock (it wasn't like that before) so I have to allow it to go to this uBlock's document-blocked page.
