### ISSUE TITLE
Can we have link to docs under My Filters tab?

### ISSUE THREAD

**Issue by bulrush15** [gorhill/uBlock#695]
I thought the syntax for the My Filters tab was SOURCEURL DESTURL TYPE ACTION but apparently it's not. It's a regex in between //.

Please, on the My Filters tab, put a live link leading to the documentation for this tab. I think there is some page on the uBlock Wiki.

**Comment by anewuser** [comment]
It explicitely says:
> One filter per line. A filter can be a plain hostname, or an Adblock Plus-compatible filter. Lines prefixed with ‘!’ will be ignored.
After reading that, In 3 seconds you can get to https://adblockplus.org/filters

**Comment by bulrush15** [comment]
That would be great to put the adblockplus link on that actual page. Thus reducing the time to look it up. I always try to make my apps as easy as possible for users of all levels.

**Comment by anewuser** [comment]
"1pFormatHint":{
        "message":"One filter per line. A filter can be a plain hostname, or an Adblock Plus-compatible filter. Lines prefixed with &lsquo;!&rsquo; will be ignored.",
        "description":"English: One filter per line. A filter can be a plain hostname, or an Adblock Plus-compatible filter. Lines prefixed with &lsquo;!&rsquo; will be ignored."
      },

https://github.com/gorhill/uBlock/blob/master/src/_locales/en/messages.json

**Comment by bulrush15** [comment]
Yep, I finally found it. But can we put HTML in the "message" or "description" line?

**Comment by bulrush15** [comment]
I can try to make this edit, but do I make a branch for this change, make and test the change on my PC, then make a pull request? I'm new to Git.

**Comment by gorhill** [comment]
This will be taken care in time, please do not submit pull request. Linking to ABP's page is not the solution, given that uBlock Origin extends the syntax  with `important`, `inline-script`, etc.

**Comment by anewuser** [comment]
I assumed that @bulrush15 wanted to make his own locale, and not that he was going to try to insert a link to a rival extension to the uBlock GUI.

**Comment by gorhill** [comment]
>  a link to a rival extension to the uBlock GUI.

I have no problem linking to Adblock Plus where convenient. There is already such link in the 3rd-party filter panes (the help box for cosmetic filters toggler). It's just in the current case I prefer to link to the wiki so that a user is made aware of uBlock-specific filter options, and that wiki page will in turn link to ABP for further details on the syntax.

**Comment by bulrush15** [comment]
I wasn't trying to fork uBlock Origin to make a competing product. I followed directions on a webpage to make a change, which told me to fork it. However I could not get the change to work on my browser so I stopped.
