### ISSUE TITLE
Don't show "restore_on_demand" tabs in logger UI

### ISSUE THREAD

**Issue by digital-carver** [gorhill/uBlock#697]
The dropdown menu to select tabs in the logger page shows tabs that whose content has not actually been loaded - tabs which are present from previous sessions but waiting for a load-on-click, as per `browser.sessionstore.restore_on_demand `. Showing these tabs in the menu serves no purpose since they haven't loaded anything and hence can't have a log at all. 

These tabs are all listed by their URL in the dropdown menu, and make the menu unnecessarily large and difficult to navigate. So, pruning them off would make it easier to get to the tabs we actually wish to check.

**Comment by gorhill** [comment]
Dev notes:

The session manager causes `TabOpen` event to be fired before the `pending` attribute has been set to `true`.
