### ISSUE TITLE
Changing Tamil translation strings

### ISSUE THREAD

**Issue by digital-carver** [gorhill/uBlock#698]
I've contributed a few translation corrections to Tamil at Crowdin. Most of these are stuff that have misinterpreted out of context (eg. the "net" in "net filters" was translated in the sense of "net income" rather than "network"). These make the experience of using the addon in Tamil often an exercise in puzzle interpretation right now. 

Is there any next step to get these changes integrated into uBlock0? I saw some references to proofreaders here in other issues, but couldn't figure out whether Tamil had one or not (and the Wiki doesn't seem to have content about this).

**Comment by gorhill** [comment]
I pull the changes from Crowdin on a regular basis, using a shell script.

**Comment by digital-carver** [comment]
Okay, but what happens when there are two or more translations for the same text in the same language with no vote differences (like here)? The latest one overrides the previous ones or something?

**Comment by zummuz** [comment]
@digital-carver Nothing happens. Owner of the project, manager and proofreader can approve translations. Votes serves to show them which version translators like most.
