### ISSUE TITLE
Need larger, variable-based translation texts for "static filtering wizard"

### ISSUE THREAD

**Issue by digital-carver** [gorhill/uBlock#699]
I'm attempting to add Tamil translations at the Crowdin project, and came across the translation texts [with context "static filtering wizard"](https://crowdin.com/translate/ublock/13/enca-ta#q=static+filtering+wizard). The way they have been split doesn't work for languages with very different grammatical ordering from English, like Tamil, and lead to quite awkward and unintelligible translated results. 

For eg., a good translation of the first line requires something like `"{{type}} type network requests Block"`, and this type of reordering is (afaik) not possible with the current text. 

The ideal way would be to have the whole wizard as a single text (with embedded variables), allowing us to reorder stuff around for the best possible translation. But if you think this might prove too difficult for the translators, at least having line-level reordering would help make things much better. Each physical, visible line in that wizard can be made into a translation text of its own, with variables inside, so we can make better, more intelligible translations.

**Comment by gorhill** [comment]
> The ideal way would be to have the whole wizard as a single text (with embedded variables)

That's how it is:

    {{action}} network requests of {{type}} {{br}}which URL address matches {{url}} {{br}}and which originates {{origin}},{{br}}{{importance}} there is a matching exception filter.

The variables are the `{{...}}` placeholders.

**Comment by digital-carver** [comment]
Oh, the [sentence text](https://crowdin.com/translate/ublock/13/enca-ta#765) doesn't have "static filtering wizard" in its context like the individual parts do, so I didn't realize there was a whole sentence text made up from these parts at all. 

The Tamil translation doesn't have any value in the sentence text right now, and so the addon seems to use just the parts that are available substituting them in the middle of the English sentence (which is partly what made it unintelligible). I'll add the sentence's translation now.
