### ISSUE TITLE
Wiki - unexisting reference to issue in "Quick guide: popup user interface"

### ISSUE THREAD

**Issue by asantos3** [gorhill/uBlock#7]
Where it says:

> Why the change? Because issue #1013 brought forth why it is desirable sometimes to block completely a web site, as opposed to what ABP-filtering semantic dictates.

The issue doesn't exist. I only noticed this because I was reading that specific page so I don't know if there's other references to the old location of the issues in the wiki.

**Comment by gorhill** [comment]
Fixed.
