### ISSUE TITLE
uBlock & Auto Updates

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#700]
Sometime ago I installed uBlock from AMO, and every now and then it auto updated itself to newer versions.
Now I notices there's a 1.1.0.0 version, and uBlock doesn't updates to it (from 1.1.0.0rc4).
Is it normal? I used to update by hand from github so I'm wondering.

**Comment by gorhill** [comment]
> Is it normal?

Yes. Beta versions won't update to release versions and vice versa.
