### ISSUE TITLE
Make target URL in strict blocked referrer clickable without any parameters

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#705]
I have a filer, `||twitter.com/*^src=$document` to block twitter links with referrals in them.
Could you maybe make the URL without any parameters clickable like so:
![ublockbug2](https://cloud.githubusercontent.com/assets/930620/9830621/71d61454-58fb-11e5-8f3b-4684784dc1f0.png)

**Comment by gorhill** [comment]
This is looking as a rather specialized request. In most cases this won't work, as the link would just cause the destination to be strict blocked just the same. How about selecting the part of the URL you want to use, right-click and select _Opened in a new tab_?

**Comment by gorhill** [comment]
Chosen solution is to keep the blocked URL as plain text, but to provide a new entry, "without parameters", in the parsed URL section:

![a](https://cloud.githubusercontent.com/assets/585534/9832014/bfb1b8f0-593b-11e5-8a27-fba472a5529a.png)

Also, now whether the parsed URL section is expanded will be remembered.
