### ISSUE TITLE
"Own fonts option" in Firefox breaks the symbols in the popup

### ISSUE THREAD

**Issue by sojusnik** [gorhill/uBlock#706]
If the ["Allow pages to choose their own fonts, instead of my selections above"](https://support.mozilla.org/en-US/kb/settings-for-web-content-pop-ups-fonts-languages) option in Firefox is disabled, then the uBlock popup looks [this](http://i.imgur.com/09rfNKQ.png) way.

Observed under Ubuntu 15.04 with Firefox 40.0.3 and uBlock 1.1.0.0.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues?q=is%3Aissue+firefox+fonts+is%3Aclosed
