### ISSUE TITLE
Credit Card Payments are not working with uBlock Origin enabled

### ISSUE THREAD

**Issue by albertalbs** [gorhill/uBlock#709]
Hi, 

Recently (For 1 month), I am facing issue while making credit card payments in India. 

Example, After entering CC details in Payment gateway, It will take me to OTP (One time password) page. But If I installed and enabled uBlock Origin, it is not taking me to OTP page. It is simply saying "payment URL not found" or "your payment id is invalid" (This error message differs for different payment system companies like: Visa, Mastercard.) 

But I tried disabling uBlock Origin in Private Window, this time, it worked. 

So whenever I make online transactions (CC transaction in India), I need to open Private window with uBlock Origin disabled. (Continuously 5 times I faced this issue). 

@gorhill  Do we have any solution for this?

**Comment by albertalbs** [comment]
I am using Latest Windows 10 and Latest Firefox and Google Chrome. 

Tested in both browsers. Same issue happening.

**Comment by albertalbs** [comment]
I got this message before going to OTP page. 

![trnsaction-declined-message](https://cloud.githubusercontent.com/assets/608213/9836980/353476ec-5a4c-11e5-80a1-1b505c3e32e1.png)

**Comment by gorhill** [comment]
I can't investigate what I can't reproduce -- and I don't plan to make any credit card transactions just to try to reproduce. The logger is there is assist you in finding what is being blocked which should not be blocked. Furthermore, it's likely that a 3rd-party filter list is causing the issue, and uBlock is not responsible for breakage occurring as a result of using a 3rd-party filter lists, their respective maintainers are (exception is if something in _Peter Lowe_'s causes the breakage).

**Comment by albertalbs** [comment]
@gorhill I will try finding what is happening in behind the scenes. 

But can I simply do **"Reset to default settings..."** to disable 3rd Part filters?
or If I disable all 3rd party filters, will uBlock Origin work normally?

I hope following filters are officially supported by uBlock Origin.

* uBlock filters‎ : 74 used out of 74
* uBlock filters – Badware risks‎  (github.com): 4 used out of 4
* uBlock filters – Privacy‎ : 4 used out of 4
* uBlock filters – Unbreak‎ : 58 used out of 58

>**Screenshot of enabled 3rd party filters in my browsers:**

![chrome-filters-ublock-origin](https://cloud.githubusercontent.com/assets/608213/9837109/f647287a-5a51-11e5-91b2-409ed7078720.png)
![firefox-filters-ublock-origin](https://cloud.githubusercontent.com/assets/608213/9837108/f646a5e4-5a51-11e5-96b1-453a93240c5d.png)

**Comment by gorhill** [comment]
With _Reset to default settings_ you may also lose other settings than the selection of filter lists.

Any filter list which does not start with "uBlock ..." is a 3rd-party filter list.

Even if they are selected by default, _EasyList, _EasyPrivacy_ are also 3rd-party filter lists. If something from these lists is causing breakage, you need to report the breakage to the maintainer of these lists. You can easily confirm whether these lists are responsible by finding out if you get the same issue with Adblock Plus + _EasyList_ + _EasyPrivacy_.
