### ISSUE TITLE
uBlock origin is blocking Piwik's private user/admin panels, leading to blank pages

### ISSUE THREAD

**Issue by nekohayo** [gorhill/uBlock#710]
Hi there, I spent a week worrying about what I thought was a corrupt MySQL database for my instance of Piwik.org, because the contents would not show up when logged into the (private) system and this happened for only one of my two Piwik instances (which is weird, I have no explanation for that).

I spent a lot of time bisecting five multi-gigabytes databases until I tried Epiphany instead of Firefox, and found out that Firefox's uBlock plugin was the cause!

Some other people have encountered this issue (I wish I found that thread earlier):
http://forum.piwik.org/read.php?2,129115,129151

Please fix your extension (and maybe notify the ublock derivatives if they could be affected) to allow Piwik to work. Thanks!

**Comment by gorhill** [comment]
There are many filters with `piwik` in _EasyPrivacy_, a filter list which is 3rd-party to uBlock. Report to _EasyPrivacy_ maintainers: <https://forums.lanik.us/viewforum.php?f=64>.
