### ISSUE TITLE
After some time stops blocking elements

### ISSUE THREAD

**Issue by naoliv** [gorhill/uBlock#713]
I am seeing a bad thing happening with uBlock origin installed in Firefox: after some time, some elements aren't blocked anymore.
For example, right now I have Firefox with ublock and I am seeing this (`lg stylus g3`):

![After some time](http://i.imgur.com/yLBSZ0j.png)

What I have enabled is:

![Lists](http://i.imgur.com/puI8MaA.png)

But, if I remove uBlock, restart Firefox and install it again, with the same lists, it starts working as expected:

![After install](http://i.imgur.com/4oVQDg6.png)

I see the same problem in some other sites too and it's reproducible in two different Linux machines (one with Iceweasel 41.0a2 (2015-07-11) and other with Iceweasel 42.0a2 (2015-09-06).

**Comment by gorhill** [comment]
What version of uBlock Origin? What are the other settings? What does the logger show when the ads are showing?

**Comment by naoliv** [comment]
The machine with Iceweasel 41.0a2 is using uBlock Origin 1.1.0
The other one has uBlock Origin 1.1.1rc3

Using the one with 1.1.1rc3 I have this:

uBlock's log:
![Ublock log](http://i.imgur.com/srFywt5.png)

And the browser console:
![Browser console](http://i.imgur.com/cOMTwaR.png)

Settings:
![Settings](http://i.imgur.com/sY8FIAc.png)

I have nothing in My filters and My rules. Whitelist is the default one.
It also seems that sometimes closing and running Iceweasel again makes it work as expected.

**Comment by gorhill** [comment]
What other extensions are in use when uBlock stops working properly?

**Comment by naoliv** [comment]
Tab Counter + uBlock Origin on one.
Greasemonkey, Send Tab URLS, Tab Counter, Troubleshooter and uBlock Origin on the other.

**Comment by naoliv** [comment]
The strange thing is that it seems to happen only in Google and Facebook.
I am not seeing ads anywhere else.

**Comment by Tharn** [comment]
I've had this happen as well. Leaving the browser open overnight with a certain tab loaded, that tab will no longer block any ads even when clicking links and browsing within it. I think it somehow isn't seen as having an address anymore but becomes part of some system 'scheme'.

**Comment by naoliv** [comment]
Indeed it happens after leaving the browser always open.

**Comment by gorhill** [comment]
Ok, I will try to reproduce by letting the same tab opened for a couple of days.

**Comment by Betsy25** [comment]
Just FYI, I have never have this happened to me, even after multiple days of browser open & notebook on.
Firefox Nightly 44, Win7-x64

**Comment by PRabahy** [comment]
I hate to be a "me too", but I've had this happen to me a couple of times. The first time it happened, I noticed that entire 3rd-party filters tab was messed up. I can't remember exactly, but it didn't have any checkboxes; It only showed text. I have just uninstalled uBlock and reinstalled it to fix the issue. If it happens again, I'll take some screenshots and/or get some more logs. FYI, I leave Firefox open almost 24/7 because I use it to run Chatzilla.

**Comment by gorhill** [comment]
Looking for error message in the browser console would be appreciated too.

Removing/reinstalling uBO seems drastic. A simple disable/enable does not work?

**Comment by PRabahy** [comment]
I'll make sure to watch for error messages next time it happens.

Honestly uninstalling/reinstalling uBO takes ~30 seconds. When you uninstall it, it gives you an option to undo and I just click that. After doing that it still remembers all my settings so its good to go.

**Comment by seiichiro0185** [comment]
Same has happened to me too. I usually fixed it by going to the dashboard and refreshing the filter lists + clearing the cache from there. I will have a look at the browser console when it happens again. Usually my browser also runs for a long time, since I rarely reboot my laptop and only suspend it most of the time.
