### ISSUE TITLE
nintendo eshop does not finish loading with ublock enabled

### ISSUE THREAD

**Issue by rhelmer** [gorhill/uBlock#716]
In Firefox 40.0.3 with no other add-ons installed, the Nintendo eShop never finishes loading:
http://www.nintendo.com/games/game-guide/#filter/wii+u|-|-|-|-|descend|releaseDate|-|-|-|1

If I disable ublock then it works (it's a bit slow normally).

**Comment by Betsy25** [comment]
It's being blocked by the `/foresee/*` rule, which is found in the Easylist.
Better submit your problem on the [Easylist Forum](http://forums.lanik.us/)
For the time being, If you want to keep Easylist enabled, just add the follow line to your "My filters" list : 
`@@||www.nintendo.com/js/foresee$script,domain=www.nintendo.com`
