### ISSUE TITLE
uBlock Origin far ahead 🏆

### ISSUE THREAD

**Issue by TraderStf** [gorhill/uBlock#717]
https://www.raymond.cc/blog/10-ad-blocking-extensions-tested-for-best-performance/view-all/

Sorry did not know where to put this comparison.

Any plan to have uBlock ORIGIN on Mac Safari?

Thanks

**Comment by ialexsilva** [comment]
:+1:

**Comment by Dashed** [comment]
see: https://github.com/gorhill/uBlock/issues/64#issuecomment-93714843

**Comment by gorhill** [comment]
I don't have a Mac. It takes only one (disinterested) proactive Mac OS developer to plunge into the project.
