### ISSUE TITLE
forecast.weather.gov map broken by rule in "uBlock filters – Privacy‎"

### ISSUE THREAD

**Issue by mestan** [gorhill/uBlock#719]
The following rule in the "uBlock filters - Privacy" list breaks the display of the area map on the forecast pages for www.weather.gov (the NOAA weather prediction site):

||addthis.com^$third-party,important

Forecast pages served by forecast.weather.gov have a clickable map (in the "Click Map for Forecast" area) next to the "Detailed Forecast" area.  With the above rule turned on the map is blank (not visible or clickable).  With the above rule turned off the site loads the following scripts and frame from s7.addthis.com:

script:  http://s7.addthis.com/js/300/addthis_widget.js#async=1
script:  http://s7.addthis.com/static/layers.40d7f588e30ee02f4e08.js
frame:  http://s7.addthis.com/static/sh.7c3d802d.html#rand=0.3341372957494375&iit=1442464867005&tmr=load%3D1442464866735%26core%3D1442464866761%26main%3D1442464866988%26ifr%3D1442464867017&cb=0&cdn=0&kw=&ab=-&dh=forecast.weather.gov&dr=http%3A%2F%2Fwww.weather.gov%2F&du=http%3A%2F%2Fforecast.weather.gov%2FMapClick.php%3Flat%3D37.877149664000456%26lon%3D-119.37765774199971&href=http%3A%2F%2Fforecast.weather.gov%2FMapClick.php&dt=7-Day%20Forecast%20for%20Latitude%2037.87%C2%B0N%20and%20Longitude%20119.37%C2%B0W%20(Elev.%208661%20ft)&dbg=0&cap=tc%3D0%26ab%3D1&inst=1&jsl=1&prod=undefined&lng=en-US&ogt=&pc=men&pub=xa-4b05b2d91f18c9cc&ssl=0&sid=55fa446297da85bb&srpl=1&srcs=1&srd=1&srf=0.01&srx=1&ver=300&xck=1&xtr=0&og=&aa=0&csi=undefined&toLoJson=chr%3DUTF-8%26md%3D0%26vcl%3D0&rev=v2.5.2-wp&ct=1&xld=1&xd=1&fcu=VfpEYpdMfd7
script:  http://s7.addthis.com/static/menu.25a22aa5986907801922.js
script:  http://s7.addthis.com/static/hi-res-css.97cdbcb2b89b6afd0f73.js
script:  http://s7.addthis.com/js/300/addthis_widget.js#library=1

The map is then visible and clickable.  So, I turned off the "uBlock filters – Privacy‎" list, moved the rules into "My Filters", and changed the addthis.com rule as follows:

||addthis.com^$third-party,important,domain=~forecast.weather.gov

The maps on the forecast pages now work again.

Steps:
1) Go to www.weather.gov
2) In the <Local forecast by "City, St" or ZIP code> box in the top left corner, enter a city or zip code.
3) Next to the "Detailed Forecast" section of the page, under "Click Map for Forecast" there will be a blank box.

Broken page:

![broken map](https://cloud.githubusercontent.com/assets/7691241/9925416/17ce10ec-5cc0-11e5-9ed4-ee102f121584.png)

Working page:

![working map](https://cloud.githubusercontent.com/assets/7691241/9925492/19ae3972-5cc1-11e5-9855-4a0673450685.png)

Browser: Firefox 40.0.3
uBlock Origin: 1.1.0.0

**Comment by gorhill** [comment]
Workaround using a custom dynamic rule:

    forecast.weather.gov http://s7.addthis.com/js/300/addthis_widget.js script allow

**Comment by gorhill** [comment]
I think you should contact the site to ask them to fix their site: `addthis` is a notorious fingerprinter, and by respect to visitors, a site should be able to deal with the AddThis applet not being available -- even more so that this is a government site in the current case. The AddThis applet on the page is completely unrelated to the map widget, so that's an even better reason for the site to fix this: the AddThis applet "crashes" the site, and the site should not tolerate such 3rd-party behavior.

**Comment by gorhill** [comment]
Sent an email to the webmaster:

> addthis.com is a notorious fingerprinter, and I do not want anything from them to run in my browser.[1] However when I block everything from `addthis.com`, your map widget ("Click Map For Forecast") does not work, the map does not display.[2]
> 
> The AddThis widget is completely unrelated to the map widget, so if the AddThis widget is blocked, this should have *no effect* on the map widget. By respect to visitors' choices, I think you should prevent AddThis from breaking the web page at all.
> 
> [1] https://www.propublica.org/article/meet-the-online-tracking-device-that-is-virtually-impossible-to-block
> 
> [2] http://forecast.weather.gov/MapClick.php?lat=39.290379757000494&lon=-76.61218815899963#.Vfq0f98TX0r

**Comment by gorhill** [comment]
Received this answer from the webmaster:

> Hello, Ray,
> 
> You are correct. We only recently discovered this inadvertent issue when the Add This script was escalated to ad status by 3rd-party vendors.
> 
> It's an easy fix, but we have to wait until the next release candidate. You will need to allow the Add This script until then.
> 
> Sorry for the inconvenience.

So the [workaround above](https://github.com/gorhill/uBlock/issues/719#issuecomment-141045682) is the way to resolve the issue, until it is fixed server-side-wise.
