### ISSUE TITLE
Leftover "uBlock₀"

### ISSUE THREAD

**Issue by tenkuu** [gorhill/uBlock#72]
Top left:
![2015-04-16_23-12-34](https://cloud.githubusercontent.com/assets/2627419/7196854/20586546-e48e-11e4-9f7d-80c90b2a68a3.png)
and in the dashboard page title:
![2015-04-16_23-12-45](https://cloud.githubusercontent.com/assets/2627419/7196856/21c5876a-e48e-11e4-94fa-8df555ad0c9c.png)

Firefox 37.0.1
uBlock Origin 0.9.4.4

**Comment by gorhill** [comment]
uBlock<sub>0</sub> is the ofiicial short name for uBlock Origin. It's useful for when conciseness is needed, like above.
