### ISSUE TITLE
How to block duckduckgo Instant?

### ISSUE THREAD

**Issue by mb1234** [gorhill/uBlock#721]
Linux + FIrefox 40.03 user here with uBlock origin.

Just a query!

If you search on duckduckgo (e.g. search for bbc news), then there is an obnoxious gray box just below the search box that I believe it called "Instant". I have right-clicked on it and created element blocks for it several times but it always reappears on a page refresh.

On other sites I am able to block the annoyances this way but duckduckgo instant is an exception. Any ideas how to make it worK?

**Comment by hotdogman** [comment]
`duckduckgo.com###search_form_homepage > .search__autocomplete`
or 
`||ac.duckduckgo.com/ac/?callback=*&q=*$script,first-party`

**Comment by gorhill** [comment]
Turn this off through [DuckDuckGo's settings](https://duckduckgo.com/settings)?

Otherwise, @hotdogman's suggestion is good, except use both filters, not just one or the other:

    duckduckgo.com##.search__autocomplete
    ||ac.duckduckgo.com/ac/?callback=*&q=*$script,first-party

First one blocks the visual element in the DOM, the second one blocks network requests each time you type a character.
