### ISSUE TITLE
Tor ad blocking

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#722]
Should add some Tor filter lists

**Comment by publicarray** [comment]
With uBlock you can add any community made filter list that is either a host file or uses Adblock Plus syntax. If there is one for Tor all you have to do is add it. If there isn't you are welcome to create one.
you can add it to the [wiki] (https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web)
> The default behavior of uBlock Origin when newly installed is to block ads, trackers and malware sites -- through EasyList, EasyPrivacy, Peter Lowe’s ad/tracking/malware servers, various lists of malware sites, and uBlock Origin's own filter lists.

**Comment by gorhill** [comment]
> Tor filter lists

You do not provide any links to such filter lists.
