### ISSUE TITLE
Wrong "Domains Connected" displayed

### ISSUE THREAD

**Issue by LarsOL** [gorhill/uBlock#725]
I have recently made the jump to "hard mode" and the usage of dynamic filtering and the "domains connected" seems broken (also the little allowed etc shading) which makes sure you have got everything a lot harder. 
Hopefully i can explain everything:

This is my popup: (note that everything thing but 1st party content should be blocked)
![image](https://cloud.githubusercontent.com/assets/2637528/9978311/fb48b85c-5f6a-11e5-8ef5-72411d84721a.png)

The only exception is this:
![image](https://cloud.githubusercontent.com/assets/2637528/9978317/359da9b8-5f6b-11e5-999c-ebda89d185b4.png)

By the shading is wrong i mean the shading (green = allow right?) on a obviously denied connection. Also the "+" and "-" seems wrong?

![image](https://cloud.githubusercontent.com/assets/2637528/9978320/558fcc7e-5f6b-11e5-98a6-0d7c9a17fc51.png)

Finally in the logs everything seems to be blocked, which is very confusing becuase that implies the exact opposite of what the popup says

![image](https://cloud.githubusercontent.com/assets/2637528/9978327/794a5ba2-5f6b-11e5-8c60-e95447420d68.png)

Also on a side note (I can make a new issue if you want), i dont know why the javascript file isnt blocked? From my understanding, the domain is set to noop, therefore it should continue to static filtering, which as can be seen it is on the list for. but it still is loaded??

![image](https://cloud.githubusercontent.com/assets/2637528/9978354/b1e545de-5f6c-11e5-9952-9b6b6c8213f1.png)

Thanks,
Lars

Edit: added info asked in CONTRIBUTING.md

Ublock Version 1.1.1 - installed from webstore 
Win 10 Pro / chrome (Version 45.0.2454.93 m (64-bit))  
URL: http://www.theverge.com/2015/9/17/9338963/welcome-to-hell-apple-vs-google-vs-facebook-and-the-slow-death-of-the-web

Extensions:
Enhanced steam
Web of trust
Lastpass
Https Everywhere
NEnhancer
Session Buddy
Office Editing for docs, sheets and slides

Non default settings
My rules:
![image](https://cloud.githubusercontent.com/assets/2637528/9978417/826d401e-5f70-11e5-97ce-a8a9d91b3376.png)

3rd party filters:
 default + 
 Peter Lowe’s Ad server list‎ 
 Basic tracking list by Disconnect‎ 
 EasyPrivacy‎ 
 Fanboy’s Enhanced Tracking List‎

Main settings:
![image](https://cloud.githubusercontent.com/assets/2637528/9978432/56df470c-5f71-11e5-9d92-5844c99682d6.png)

**Comment by vzjrz** [comment]
Have you read this?: https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide
The shading on the left means that most requests to that domain are allowed (based on your adblock filter rules). The shading on the right means that the requests are actually blocked (based on your dynamic filtering rules).
Second, that filter is actually an exception rule written to allow that script to run. The maintainers of Fanboy’s Enhanced Tracking List‎ may have found that blocking that script made the website not work anymore.

**Comment by gorhill** [comment]
I see you have three tabs open for `www.theverge.com`. I suspect the popup you show is not the one which matches what is seen in the logger. What seems to have happened is that you loaded a page from The Verge without much blocking (an `allow` rule somewhere?), then you created block rules and reloaded another page from The Verge in a different tab, but then used the popup of the first page in your screenshot, while used the logger of the second page in your other screenshot. In short, I suspect the popup and logger in your screenshots are for different tabs.

**Comment by LarsOL** [comment]
I have re-visited the site and it is now shown properly. 

But I can guarantee that it was the right popup  + logger at the time, I checked multiple times before logging the issue. This can be seen in the last image if you open the full version. Where the popup was open from the logger (hence having the minimise and close in the "popup") , therefore eliminating that error.

It also does not explain how the red "shading" became contradictory to the "+" and "-" signs and the leftmost "green" shading. 

It seems somehow the gui state became out of sync with the core framework. But i agree it seems to be hard to reproduce. Ill play around with it and see if i can get it to come back.

On a side note chrome on win 10 + AMD seems to have rare redraw issues. It may be the problem but i thought i re-opened the popup enough times to eliminate that as the issue

**Comment by gorhill** [comment]
> It also does not explain how the red "shading" became contradictory to the "+" and "-" signs and the leftmost "green" shading.

The red shading in your screenshot represent the rule in effect for the cell. The left-most color and the `+`/`-` signs represents what happened to the network requests. You could whitelist the page, force a reload, then add a block rule for all 3rd-party: this will cause most cells to turn reddish (reflecting the whatever rule for any given cell), while the `+`/`-` signs are still representing what happened last time the page was loaded, which means all would be `+` is such case (because last reload the page was whitelisted). In short: cells have many visuals, what rules is currently in effect (regardless of what rules was in effect at last reload), and layered below this visuals to indicate what happened last reload. These two sets of visual can become contradictory if you change rules after the page has loaded.

**Comment by LarsOL** [comment]
Ok I can reproduce somewhat. 
Normal Blocking:
![image](https://cloud.githubusercontent.com/assets/2637528/9979282/6dcd8e4c-5fa8-11e5-9a76-be5533601a8f.png)


Un clicked my 3rd-party global blocks, clicked the in pluging refresh of page:
![image](https://cloud.githubusercontent.com/assets/2637528/9979279/ec671440-5fa7-11e5-9ec5-de21a76cbbbe.png)

Then re applied 3rd party global blocks and issue is back:
![image](https://cloud.githubusercontent.com/assets/2637528/9979281/2507d6cc-5fa8-11e5-9c0d-78748649d4d3.png)

Issue persists between browser triggered page refreshes (F5 and button). But disapears once the tab is closed then reopened. So it seems the blocking is applied dynamically between page refreshes, but the popup gui is not refreshed until the tab is closed?

**Comment by LarsOL** [comment]
Sorry i missed your last comment, was in the middle of making mine... I have read you comment and i understand that it shows the "last load" metric, and the shading will be different for a just applied rule. 

Just to make sure, i have run through the steps again making sure to manually refresh between setting changes, and the result is the same.

**Comment by gorhill** [comment]
> Issue persists between browser triggered page refreshes (F5 and button)

I don't get this here. Could you try without any of the other extensions enabled? What thing which I find anomalous in your logger screenshots is that it show `http` network requests despite HTTPS Everywhere being installed. When I used HTTPS Everywhere, all network requests in the logger are  `https`.

**Comment by LarsOL** [comment]
Will do, i'll try in a private browsing window with just ublock active one sec.

**Comment by LarsOL** [comment]
Ok you were right there seems to be a conflict of extensions. Also i didn't notice but you're right about the https everywhere. Ill try to find the offending extension and report back

**Comment by LarsOL** [comment]
Ok more weirdness... it seems regardless of extensions (i turned them all on as test) the issue seems to never come up. Though that could be because private browsing clears something between refreshes that's not normally cleared.

I have cleared all my extensions in normal browsing and the issue remains.
![image](https://cloud.githubusercontent.com/assets/2637528/9979365/5e41c700-5fac-11e5-92c9-800cf6886267.png)


Going to restart brower, check if thats it.

**Comment by LarsOL** [comment]
Ok restarted the computer and with all extensions installed and normal browsing it is working properly.
Also on the https everywhere it is working, the https are just higher, that section of domains apparently doesn't support https.

For now i guess the browser was just in a weird state, and it seems a chrome bug not your extension. I play around and try to get it back for a bit anyway.

**Comment by LarsOL** [comment]
Ok, sorry about this. But can reproduce again:
Reset settings to default using main setting button.
tick i am a advanced user.
Go to site
Enable the 3rd party blocking
refresh.
Issue is back:
![image](https://cloud.githubusercontent.com/assets/2637528/9979444/481f10c8-5fb0-11e5-8d35-66cf37779eaf.png)

**Comment by LarsOL** [comment]
Can confirm with no other changes than restarting the browser the issue is now gone. Seems to only be the first time the advanced mode is set.

**Comment by gorhill** [comment]
Very weird all this. Since the log and the web page shows that uBlock is working as expected, it appears this is only a UI issue for the popup. All the popup internal data is supposed to be reset each time a page reload, and it's as if this was not happening in your case -- so the popup UI ended up showing the merge of old data + new data regarding network requests.

**Comment by LarsOL** [comment]
Just to confirm can you now reproduce the issue with the latest steps? Or is it still something specific with my computer?

**Comment by gorhill** [comment]
> can you now reproduce the issue with the latest steps

I can't reproduce using above steps on Chrome 47.0.2508.0 dev (64-bit) on Linux (I don't have Chrome 45).
