### ISSUE TITLE
Clear all caches after not updating rules

### ISSUE THREAD

**Issue by potkeys2** [gorhill/uBlock#726]
Clear the cache, update rules, can not be updated
![1](https://cloud.githubusercontent.com/assets/14056326/9981148/d8b07114-5fe6-11e5-8c6b-d1c28d6c1364.PNG)

![2](https://cloud.githubusercontent.com/assets/14056326/9981141/a9fe3946-5fe6-11e5-97d0-c3975e671b89.PNG)

**Comment by gorhill** [comment]
I don't understand what is the reported issue.

**Comment by potkeys2** [comment]
Point after point after clearing the cache update rules, the rule can not be updated

**Comment by potkeys2** [comment]
Clear the cache, update rules, can not be updated

**Comment by gorhill** [comment]
I clicked _Purge all caches_, then clicked _Update now_. All the filter lists were properly updated.

Can you load directly in your browser the following links?

- <https://easylist-downloads.adblockplus.org/easylist.txt>
- <https://easylist-downloads.adblockplus.org/easyprivacy.txt>
- <http://mirror1.malwaredomains.com/files/justdomains>

**Comment by potkeys2** [comment]
Yes, but there will not be updated in uBlock
![1](https://cloud.githubusercontent.com/assets/14056326/9981262/4bc420ac-5feb-11e5-902f-855dca2fef35.PNG)
![2](https://cloud.githubusercontent.com/assets/14056326/9981263/4bc6ceba-5feb-11e5-9923-e8bb5ee00b17.PNG)
![3](https://cloud.githubusercontent.com/assets/14056326/9981264/4bc784b8-5feb-11e5-93b2-cd0169cb7335.PNG)
![4](https://cloud.githubusercontent.com/assets/14056326/9981265/4c04db42-5feb-11e5-964b-6c871dd04621.PNG)
![6](https://cloud.githubusercontent.com/assets/14056326/9981266/4c9b1fee-5feb-11e5-8707-85381bdc1b27.PNG)

**Comment by potkeys2** [comment]
Rule content uBlock in the open, some old, some blank
![1](https://cloud.githubusercontent.com/assets/14056326/9981303/381e3744-5fec-11e5-888d-8305fe7ca5f7.PNG)

![3](https://cloud.githubusercontent.com/assets/14056326/9981304/3855743e-5fec-11e5-9968-9dadafc071aa.PNG)
![4](https://cloud.githubusercontent.com/assets/14056326/9981305/3921860a-5fec-11e5-9f74-5db5d53608c2.PNG)

**Comment by gorhill** [comment]
Can you look at the extension's dev console to see what is happening with the `XMLHttpRequest` of the filter lists?

![a](https://cloud.githubusercontent.com/assets/585534/9981295/8ea91f62-5f87-11e5-897f-81f363c5dedf.png)

![a](https://cloud.githubusercontent.com/assets/585534/9981299/9a60d5b6-5f87-11e5-8adb-622b2f312c0f.png)

![a](https://cloud.githubusercontent.com/assets/585534/9981319/05ab9496-5f88-11e5-84df-3314e39ac09f.png)

**Comment by potkeys2** [comment]
![1](https://cloud.githubusercontent.com/assets/14056326/9981435/6e2774e2-5fef-11e5-9a75-d82474183395.PNG)

**Comment by gorhill** [comment]
`ERR_BLOCKED_BY_CLIENT` means one of your extension is blocking the network requests. Are you blocking behind-the-scene network requests?

**Comment by potkeys2** [comment]
I do not understand, if this whitelist options?

![1](https://cloud.githubusercontent.com/assets/14056326/9983318/5e38cdd4-602a-11e5-89d7-0dc6bf716fe3.JPG)

**Comment by potkeys2** [comment]
After restoring default, does not remove the white list, try a few times, you can update the

**Comment by gorhill** [comment]
Cut and paste the following in _Whitelist_:

    about-scheme
    behind-the-scene
    chrome-extension-scheme
    chrome-scheme
    loopconversation.about-scheme
    opera-scheme
