### ISSUE TITLE
Disable easy-lists by default

### ISSUE THREAD

**Issue by HeikoAdams** [gorhill/uBlock#727]
Since the easy-lists are mainly maintained by Eyeos (the company behind ABP) which has an suspicious business model theses lists are no more trustworthy and should by shipped disabled by default and removed  once there are equivalent alternatives.

**Comment by gorhill** [comment]
EasyList is a community-maintained filter list, not maintained by Eyeo. "Acceptable ads" list is maintained by Eyeo.

**Comment by HeikoAdams** [comment]
You're right but Eyeos employees are very active contributors to the lists.

**Comment by gorhill** [comment]
See [Very easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode): it is the result of EasyList, so clearly it's working well and beneficial to users. If you do not want to use it it's your personal choice.
