### ISSUE TITLE
[Firefox 42+] Big number icon 

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#730]
In Firefox 42 beta1 and up the number of blocked request appear very big.
The problem affect also other addon, in my case on image is present also "Weather Forecast" for that I think that Mozilla from 42 have changed something in UI.

![bigger](https://cloud.githubusercontent.com/assets/13637587/10013757/8088982a-6114-11e5-8fab-2d1f29bff7b2.jpg)

Firefox 42 beta1 + Windows XP.

**Comment by gorhill** [comment]
> The problem affect also other addon
