### ISSUE TITLE
How to add a rule a.k.a on the useability of the GUI?

### ISSUE THREAD

**Issue by liar666** [gorhill/uBlock#731]
The interface is very poorly designed: it took me hours to find were to enter a filter rules: clicking on the icon on the toolbar button gives you a menu with only 2 icons: one that leads you to a "picker GUI" the other to a "logger view", none of them allow to simply enter a filter rule, which is supposed to be the core principle of the addon!
  + the "picker view" lets you pick an element on the page, and pops up a "window" (*that you cannot see if not pointing the mouse at it!*) where the "create" button become *grayed-out as soon as you try to customize* the rule, with no apparent reason nor any explanation.
  + the "logger view" does not allow you to enter rules... 
- There is absolutely no documentation (in the mozilla addon page of the github page) that explains how to use the addon, nor any blog/forum/... that would talk about it.
- If you manage to find how to enter a rule (by going to FF menu -> Addons -> uBlock -> Show Dashbord!), then you realize than the syntax is the one of adblock and has *nothing* to do with RegExes! The availability of the wildcard `*` has nothing to do with the possibility to use true RegExes like '.*' or '[a-z]' or '[0-9]{4}'!!!!

**Comment by gorhill** [comment]
> then you realize than the syntax is the one of adblock and has nothing to do with RegExes

I have no clue what you are talking about. uBlock supports Adblock Plus filter syntax, it's written black-on-white in the _My filters_ pane at the top:

> One filter per line. A filter can be a plain hostname, or an **Adblock Plus-compatible filter**. Lines prefixed with ‘!’ will be ignored.

**Comment by gorhill** [comment]
> where the "create" button become grayed-out as soon as you try to 

[Wiki](https://github.com/gorhill/uBlock/wiki/Element-picker):

> The Create button will be enabled only if a proper filter can be created from the content of the text area. Once you click the Create button, the element picker will add the necessary tokens to ensure the filter apply only to the current web site, will add it to your custom list of filters and save it.

**Comment by harshanvn** [comment]
> The interface is very poorly designed: it took me hours to find were to enter a filter rules: clicking on the icon on the toolbar button gives you a menu with only 2 icons: one that leads you to a "picker GUI" the other to a "logger view", none of them allow to simply enter a filter rule, which is supposed to be the core principle of the addon!

Once you get a hang of it, it is actually quite well organized and is quite easy to use...

To better have an understanding over the UI, it is defintely needed to take a look at the quick gides listed under <a href="https://github.com/gorhill/uBlock/wiki">Wiki</a> section.

**Comment by harshanvn** [comment]
> the "logger view" does not allow you to enter rules

> There is absolutely no documentation

this is not true. Please refer <a href="https://github.com/gorhill/uBlock/wiki">Wiki</a>. And for logger, look <a href="https://github.com/gorhill/uBlock/wiki/The-logger">here..</a>. It will explain how to create filters (static/dynamic), and how to filter log entries (which is quite brilliant)..

**Comment by liar666** [comment]
Hey! Thanks all for your quick answers... Sorry for the language... I'm still on my nerves after my unfortunate attempts...

You're right, it's not written on your sites that you use regexes, but I was referred to this addon on some forums that pretends it does. My mistake to have believed all I read on the internet :) Please forgive me. 

Concerning the docs, it would be more than welcome to provide the 2 links you give me on the mozilla-addons webpage and/or in the about:addons page and/or on the pages themselves.

Whatever, your quick reaction gives me the will to learn more about this tool. Thanks and sorry again for the agressivity...

**Comment by harshanvn** [comment]
> learn more about this tool

Yes, this tool is quite different, as it serves for a larger role, than merely as an ad-blocker.

Just go through the wiki. You will see lot of detail on <i>how-to</i> and its <i>inner workings</i> too.. :)

**Comment by gorhill** [comment]
> Concerning the docs, it would be more than welcome to provide the 2 links you give me on the mozilla-addons webpage and/or in the about:addons page and/or on the pages themselves.

**Comment by gorhill** [comment]
Link to documentation added to description. AMO updated with new version.

**Comment by lewisje** [comment]
I thought uBlock Origin did allow regexes as blocking rules now.

**Comment by gorhill** [comment]
> I thought uBlock Origin did allow regexes as blocking rules now.

It does, just as per ABP-filter syntax allows it. The statement I quoted [here](https://github.com/gorhill/uBlock/issues/731#issuecomment-142290657) is wrong, as it implies uBlock's filter syntax is wholly regex-based, which is not the case.
