### ISSUE TITLE
[request for help] Washington Post comments

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#733]
I am trying to see the Washington post comments and can't.
I get an error: "Unable to retrieve Canvas config from the storage"

If I completely disable ublock for that article, I can see the comments.

Can you help me find how to see them with ublock enabled?

Example link:
https://www.washingtonpost.com/news/the-switch/wp/2015/09/22/jeb-bush-says-hed-repeal-net-neutrality/

Details:
For the sake of this request I installed ublock on a clean profile.

With default setting of ublock, I get no response when pressing the comments link.

With "I am an advanced user" and "Dynamic filtering pane" enabled, I "noop-ed" localy every host on the pop up.
At that point I got the above error message after the page showed "Loading" for a while.

My settings:
SeaMonkey 2.33.1 on win 7 x64
ublock ver 1.1.1 with default settings + "I am an advanced user"

**Comment by hotdogman** [comment]
https://github.com/gorhill/uBlock/commit/032becfd76f43c2c25fe18df6c85044ccccb5c6b
>Comments section is broken, but given this is to work around a more severe breakage (the impossibility to just read an article), I thought this was acceptable. The elemhide solution does not prevent a redirection to https://subscribe.washingtonpost.com/.

**Comment by gorhill** [comment]
Is the Washington Post still asking users to disable their blocker?
