### ISSUE TITLE
[bug] play button in embeded spotify iframe is unable to open popup

### ISSUE THREAD

**Issue by nhantrn** [gorhill/uBlock#734]
The play button in embeded spotify iframe is unable to open up the popup login page. If you click on the title/artist text, however, it will open up in a new tab instead. This does not happen with ABP. Need fix.

**Comment by hotdogman** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by gorhill** [comment]
> Need fix

Need detailed steps for me to reproduce the issue. Once I can reproduce, I can investigate. Assume I know absolutely nothing about Spotify (which is the case) -- so **detailed steps** are key.

**Comment by nhantrn** [comment]
Sorry. Anyway, here's a page that has an embeded spotify iframe: http://www.josepvinaixa.com/blog/cali-y-el-dandee-por-fin-te-encontrare/

Try click on the play button with uBlock off/on to see the problem.

**Comment by gorhill** [comment]
> This does not happen with ABP.

Incorrect: It does not work either with ABP + EasyPrivacy. 

Report the issue to the maintainers of [EasyPrivacy](https://forums.lanik.us/viewforum.php?f=64). Workaround:

    @@||www.googletagmanager.com$script,domain=embed.spotify.com
