### ISSUE TITLE
broken link in Filter lists from around the web

### ISSUE THREAD

**Issue by scgaw2000** [gorhill/uBlock#735]
In the section of **Disconnect simple ad filters**, there is a hidden char after the word ".txt" of the link https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt. Both of the subscription link and the link to the file are affected.

![screen shot 2015-09-24 at 6 09 02 pm](https://cloud.githubusercontent.com/assets/3814422/10070830/9cacf292-62e7-11e5-9609-9e37248d5204.png)

**Comment by lewisje** [comment]
I think that was my fault, because I'm the one who added a link to that list; however, I don't see anymore how I can edit that wiki page.

**Comment by Piter432** [comment]
@lewisje: I think @gorhill removed possibility to edit his wiki (or only that page, can't remember now). Shame :/

**Comment by gorhill** [comment]
Fixed, thanks for reporting the quirk.
