### ISSUE TITLE
Not an issue: another place to drop images

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#736]
The [other place](https://github.com/gorhill/uBlock/issues/235) grew a bit too large.

**Comment by gorhill** [comment]
![mem-usage-overall-chart-ff41](https://cloud.githubusercontent.com/assets/585534/10074130/0577118c-629c-11e5-9902-bf367c6a96c3.png)

![mem-usage-overall-chart-chr45](https://cloud.githubusercontent.com/assets/585534/10074141/15f04128-629c-11e5-9155-177fd4909083.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10198632/d9961864-676a-11e5-910f-c93d0c214c6d.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10397383/6c93aeae-6e75-11e5-918e-39a587ecb888.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10417577/ec9bbe80-700e-11e5-8fc1-3f21358b45ee.png)

![c](https://cloud.githubusercontent.com/assets/585534/10417578/eeb27aba-700e-11e5-9c2e-0845cd27b404.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10513149/aa42ac9e-7313-11e5-8b71-42383b58fcd4.png)

![c](https://cloud.githubusercontent.com/assets/585534/10513464/b3e0f09c-7315-11e5-8e0b-90d3cc8614f7.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10591492/5ef41740-7684-11e5-9990-25627df4a791.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10864111/0a9cf23c-7fb9-11e5-83c0-97bc3f143849.png)

**Comment by gorhill** [comment]
Many are not aware about how ABP has been propped-up through astroturfing, so keeping this here for reference for when I need to substantiate the evidence of astroturfing:

![a](https://cloud.githubusercontent.com/assets/585534/11093638/63237a86-8859-11e5-9802-23124eb28912.png)

Source: <http://web.archive.org/web/20120504040231/http://chrome-plugins.org/about-us/>.

Excerpts (my emphasis):

> Our goal is to create a website that provides a better overview about available plugins than the Chrome web-store by writing **impartial and concise reviews** about every plug-in [...] Instead of just trusting what the developers write themselves about their product, users should consult reviews from an **impartial source such as this website** first [...] This website is ad-free and a non-profit project. We only feature high-quality plugins for Chrome, **paid sumissions are not be accepted**.

[`chrome-plugins.org`](http://www.chrome-plugins.org.ipaddress.com/):

> We found 2 hostnames for IP Address 95.130.17.36
> - www.sedo.org
> - www.chrome-plugins.org
> 
> [...]
> 
> Creation Date
> 04/26/2011
> 
> [...]
> 
> Registrant
> Till Faida
> Eyeo GmbH
> 
> [...]
> 
> Technical Contact
> Wladimir Palant
> Eyeo GmbH

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/12767755/219dd856-c9d9-11e5-8ae3-40df5ff6a442.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/14185866/b2309870-f749-11e5-8c37-2008e3f2ec10.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/18037421/6a9e8bce-6d51-11e6-802a-e778ca42240d.png)

**Comment by gorhill** [comment]
Crass incompetence or hidden agenda? For sure you will never see this individual substantiate his statements below (because it's BS).<br>
![a](https://cloud.githubusercontent.com/assets/585534/19246018/2eb01c78-8ef2-11e6-95ee-f6fa74902bee.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/20042797/2800dcd4-a44e-11e6-9bc8-a5e0c960262c.png)

**Comment by gorhill** [comment]
![c](https://cloud.githubusercontent.com/assets/585534/20142632/9869bf24-a663-11e6-9189-02a470f95a96.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/21744505/ffc4c826-d4e4-11e6-9780-3d68ef222cbd.png)

**Comment by gwarser** [comment]
I have noticed that even if wiki is mirrored on few computers, images don't have any backup we can access. So I crawled wiki source and saved them locally, just in case. Every time new image is added, I'm saving a copy with correct (final) file name to be easy to restore. And finally it ended up on Mega - https://mega.nz/folder/HNw3DQoa#wv6iugxFJ-PXPpNpPzNhAg

**Comment by gorhill** [comment]
I don't know how images are stored, so I have assumed that they are probably kept around until maybe they haven't been requested for a very long time.
