### ISSUE TITLE
uBlock Origin causes OS X Firefox application menu to stop working

### ISSUE THREAD

**Issue by Sunfoo** [gorhill/uBlock#737]
Firefox 41.0, OS X 10.10 "Yosemite", uBlock Origin 1.1.1
Default uBlock Origin settings
The problem does not happen with uBlock Origin disabled. I have confirmed this issue on two different computers with the same exact settings.
Steps to reproduce on OS X 10.10 and Firefox 41.0:
1. Install uBlock Origin from Get Add-Ons page
2. Restart Firefox
3. Go to any web page (e.g. mozilla.org)
4. Close the current window with the red X
5. Try to click on Firefox > About or Firefox > Quit (neither of them works)
The issue does not happen on Firefox 40.0.3, which makes me think that there is a conflict with the new Firefox [tracking protection feature](https://support.mozilla.org/en-US/kb/tracking-protection-firefox?as=u&utm_source=inproduct) (and the issue happens even if tracking protection is disabled).
See https://support.mozilla.org/en-US/questions/1084999 for more details
![example](https://cloud.githubusercontent.com/assets/14826629/10083807/9e33ae98-62c5-11e5-84f4-3441d2dde635.png)

**Comment by gorhill** [comment]
I don't have OSX, I can't investigate this.

**Comment by rafuse** [comment]
I'm on Mac OS 10.10.5 with Firefox 41 and I can reproduce, although that problem does not occur every single time. Sometimes the menu works. Really strange.

I could also reproduce the problem on newest Firefox Dev Edition 42.0a2. 

(Both Firefox Versions are clean installs with uBlock's default settings.)

**Comment by gorhill** [comment]
Are there any errors of interest in the browser console?

**Comment by rafuse** [comment]
When I click on Firefox > About (Step 5) I get this:
NS_ERROR_NOT_AVAILABLE:     utilityOverlay.js:506:0

**Comment by rafuse** [comment]
On Firefox Dev, I get this when closing the window (Step 4):
unsafe CPOW usage TabState.jsm:109:0

Then this when clicking on About > Firefox (Step 5):
NS_ERROR_NOT_AVAILABLE:  utilityOverlay.js:506:0
NS_ERROR_NOT_AVAILABLE:  viewSourceUtils.js:150:0

And after a few seconds doing nothing this comes up:
1443168826531	Toolkit.Telemetry	ERROR	TelemetryStorage::loadAbortedSessionPing - error removing ping: PingReadError JS Stack trace: PingReadError@TelemetryStorage.jsm:80:15 < TelemetryStorageImpl.loadPingFile<@TelemetryStorage.jsm:1448:13 Log.jsm:749:0

**Comment by kingtosh** [comment]
On OS X 10.8.5, there are no problem like that.

**Comment by 5t3f4n** [comment]
I can reproduce this on the following setup.

`Firefox 41.0`
`uBlock Origin 1.1.1`
`OS X 10.10.5 (14F27)`

**Comment by pidg** [comment]
I can also reproduce this with Firefox 41.0 on 10.11.

Someone has opened a [thread on Mozilla Support](https://support.mozilla.org/en-US/questions/1084999), suggesting it is a conflict between uBlock Origin and Firefox's built-in tracking protection.

**Comment by rafuse** [comment]
The issue **DOESN'T OCCUR ANYMORE** with latest the Firefox Version. 
If anyone else can confirm this, i think we can **close** it. 

```
Tested with:

Firefox 41.0.2 
Firefox Dev 43.0a2 (latest)
uBlock Origin 1.3.0
```

**Comment by Sunfoo** [comment]
I'm still having the issue with uBlock Origin 1.3.0, Firefox 41.0.2, and OS X 10.11.

**Comment by gorhill** [comment]
> I'm still having the issue

He did say the "latest", and then pointed out 43.0a2 as the "latest". So the fix would be in the latest dev version if I understand correctly.

**Comment by scottmacpherson** [comment]
There's an issue over on Mozilla's Bugzilla about this as well, which mentions uBlock Origin: https://bugzilla.mozilla.org/show_bug.cgi?id=1211286

**Comment by entonio** [comment]
This still happens, it's just that FF 43 included a change that **sometimes** makes the bug go away. But it's a issue still, and an annoying one.

> Kannan Vijayan [:djvj] 2015-11-24 09:21:34 PST
> No idea how my changes affect this problem.  I suspect the underlying problem still exists, and hinges on javascript execution timings.
> My patch will affect the execution start time and end time of js scripts (it pushes script compilation to a background thread).
> This issue is likely still present, and might show up intermittently still.

https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=f7cbf3aa76fc9768bb3c2860226195d1f54e93fc&tochange=ad320eee186e1f57aef89c322148cc3d73c3fc91
