### ISSUE TITLE
Dynamic Filtering feature request - 'video' rule type

### ISSUE THREAD

**Issue by astral-sa** [gorhill/uBlock#74]
Hi there - big fan of the extension. I'd like to request a 'video' rule type be added for dynamic filtering to cover 'video'/'source' elements (or perhaps some sort of 'media' type to encompass those+audio?)

Use case: I've got third party requests blocked in Dynamic Filtering. I'd like to be able to use a noop to allow third-party video requests from a specific site to any number of different target domains without having to either noop all third-party requests for that site or specifically noop each domain as it's encountered.

**Comment by gorhill** [comment]
Sorry but it's beyond the UI model of uBlock. The kind of functionality you are talking about is dealt with fine by [Policeman](https://addons.mozilla.org/en-us/firefox/addon/policeman/) (Firefox) or [uMatrix](https://chrome.google.com/webstore/detail/%C2%B5matrix/ogfcmafjalglgifnmanfmnieipoejdcf) (Chromium). It doesn't fit at all in uBlock, this would require changes such that would turn uBlock into uMatrix, which is not something I intend to do.

**Comment by harshanvn** [comment]
Ok. I guessed your reply here :)
I have a question little relevant to this kind of feature. Just wanted to know your standing on this kind..
 Would it be ideal to implement CSS types to be allowed/blocked, not from the UI, but from "My Rules" dashboard..

something like this.. 
- * * 3p-css block
- * * 3p-css allow

The advantage here is, when one uses default deny approach, many of them (which i encounter), usually had some CSS files blocked. With the support of CSS rule one might face little less site to tinker for proper rendering.

I perfectly understand if this does not include in current scope of uBlock. Just wanted your opinion :)
