### ISSUE TITLE
Pupup page not blocked

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#740]
Open this page:
http://www.freshremix.ru/house/98579-ghostchant-sincerity-2015.html
Scroll down to the bottom page and click to embedded Flash for listen the music, at this point will appear the http://www.djsradioshow.com/ popup page not blocked by Ublock Origin.
My suggestion for all cases like this is add to context menu option "Block this page" for automatically add the page in permanent rules.
In any case I have added manually in permanent rules the code djsradioshow.com * block, then when I try to open the page I get only a blank page.
Maybe will be better add a warning triangle with a blocking message like "The page is blocked by this rule.... or something like this.

Firefox 41 final + Ublock Origin 1.1.1 +
My filters‎ : 78 used out of 80
    uBlock filters‎ : 82 used out of 82
    uBlock filters – Badware risks‎  (github.com): 4 used out of 4
    uBlock filters – Privacy‎ : 3 used out of 4
    uBlock filters – Unbreak‎ : 58 used out of 58
Ads (2)
    Adblock Warning Removal List‎ (forums.lanik.us): 81 used out of 82 
    EasyList‎ (forums.lanik.us): 57.577 used out of 57.594
Privacy (1)
    EasyPrivacy‎ (forums.lanik.us): 10.420 used out of 10.430
Malware domains (2)
    Malware Domain List‎ (malwaredomainlist.com): 1.486 used out of 1.488
    Malware domains‎ (www.malwaredomains.com): 10.616 used out of 10.683
Social (1)
    Fanboy’s Social Blocking List‎ 
Custom (1)
    Block-EU-Cookie-Shit-List‎ : 1.002 used out of 1.004:

**Comment by gorhill** [comment]
There is no rules in any of the filter lists to block popups from `djsradioshow.com`, so you will need to add one:

    ||djsradioshow.com^$popup
