### ISSUE TITLE
 img unblockable[solved]

### ISSUE THREAD

**Issue by apache404** [gorhill/uBlock#742]
![captura de pantalla_2015-09-25_13-54-23](https://cloud.githubusercontent.com/assets/14836366/10099860/f067e0b2-638d-11e5-81b7-cca236e21dcd.png)

newpct.com

**Comment by apache404** [comment]
![captura de pantalla_2015-09-25_13-54-23](https://cloud.githubusercontent.com/assets/14836366/10099860/f067e0b2-638d-11e5-81b7-cca236e21dcd.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/10099973/9abf744e-635c-11e5-8dc8-8246b0cf5964.png)

**Comment by apache404** [comment]
Thanks ,,, 
excelente el complemento es siempre lo primero que instalo a firefox 
Muchas gracias
