### ISSUE TITLE
Consider adding strict blocking message at top of page

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#744]
Disclaimer: You must disable the filter named **uBlock filters** to use this test case as uBlock Origin 1.2.0 now blocks tube8.com popunders. This issue is about the UI for strict blocking, not [popunder blocking](https://github.com/gorhill/uBlock/issues/795).

RequestPolicy (but not RequestPolicy Continued) put this message at the top of pages on strict blocking "This webpage has asked to redirect to http....".

![screenshot from 2015-09-26 16 23 42](https://cloud.githubusercontent.com/assets/11916082/10117974/6a44e1fa-646a-11e5-96e4-642fdf24b0f2.png)

This feature would be nice to have in uBlock Origin instead of **being redirected** to a blank page that says "uBlock Origin has prevented the following page from loading:". It is time consuming to click "Back" each time, and almost as frustrating as being redirected to the ad site itself.

![screenshot from 2015-09-26 16 28 04](https://cloud.githubusercontent.com/assets/11916082/10117988/dc7a5750-646a-11e5-8a76-6ac27295f2cf.png)

See also
* [EasyList forums: Pornhub NETWORK popups](https://forums.lanik.us/viewtopic.php?f=62&t=22848&p=77727)
* [Ablock Plus issues: Prevent background redirects](https://issues.adblockplus.org/ticket/2095)

**Comment by flyingzebras** [comment]
@gorhill Screenshot added.

**Comment by gorhill** [comment]
The advantage of using a full page is that more details regarding the block can be provided:

- The reason for the block (what filter)
- The filter lists which contain the filter
- The parsing of the redirect URL

Also, uBlock works at HTTP request level, meaning such a bar is not trivial to implement, let alone implement in a browser-independent way.

The "eating" of the history is something which may be fixed though regardless of the feature request here.

**Comment by flyingzebras** [comment]
What do you think about the idea of opening a new separate tab for the full page?

**Comment by gorhill** [comment]
> What do you think about the idea of opening a new separate tab for the full page and leave the previous page intact?

Not sure I follow. It's not for uBlock to decide whether something must be opened in a new tab or not, this is for web pages to decide -- according to their HTML/JS, or for the user to decide through right-click "Open in a new tab..."

**Comment by flyingzebras** [comment]
>The "eating" of the history is something which may be fixed though regardless of the feature request here.

Can you come up with any ideas that can make this less annoying?

I really love the strict blocking feature with uBlock Origin at the same time I really hate being disrupted in my browsing experience. There must be some smart ways to resolve this issue and I think it is important as you lead the way for strict blocking right now.

**Comment by publicarray** [comment]
The domains that are blocked are usually for a very good reason (e.g. malvertising) so in my day to day browsing I hardly ever get to see the warning. I think a full page is well justified for protecting the user from potential malware or adware.

**Comment by gorhill** [comment]
The root issue here is a site using a "popunder" -- and how uBlock can handle this gracefully for the user. I remember testing prototype code to test for this but eventually moved onto something else and eventually scrapped the code. I will try again to see if I can do something. Pop-unders are a mirror case of pop-ups -- so I figure it should be possible to handle these, only difference is that the original tab will be closed, not the new one.

**Comment by flyingzebras** [comment]
@gorhill I'm glad to hear that you are somewhat familiar with this issue. Can you please label this issue?

**Comment by flyingzebras** [comment]
@publicarray The problem is that the Pornhub NETWORK (owned by MindGeek) is full of malvertising (see https://en.wikipedia.org/wiki/MindGeek#Malvertising).

**Comment by gorhill** [comment]
> Can you please label this issue?

https://github.com/gorhill/uBlock/issues/99

**Comment by flyingzebras** [comment]
Thank you.

**Comment by flyingzebras** [comment]
@gorhill Feel free to close this issue if you feel that this is a duplicated issue. Just try to keep in mind that the screenshots at the top can be useful for demonstration though.

**Comment by publicarray** [comment]
The popunder issue is fixed since https://github.com/gorhill/uBlock/commit/31a95b2326a63881e421a4014df54050ea543adc

**Comment by flyingzebras** [comment]
@publicarray The issue in this post is about the UI for strict blocking, not popunders.

**Comment by flyingzebras** [comment]
@gorhill Can you please provide me a test case for another domain than tube8.com? 

I need it to take new screenshots on another site as Inline script tag filtering now takes care of tube8.com.

**Comment by gorhill** [comment]
I don't know of any other test case. Just disable unselect _uBlock filters_ in _3rd-party filters_ pane.

**Comment by JoshMackus** [comment]
How do i disable this error message? It drove me to insanity, to the point (esp. on TPB) so I had to change to ABP.

**Comment by gorhill** [comment]
Read carefully what the page is telling you.
