### ISSUE TITLE
[Firefox] Blank tab on blocking

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#745]
Open the link:
 http://forums.iobit.com/forum/general-forums/news-offers/211659-driver-booster-3-0-3-3-0-3-257-is-released-september-22-2015
and then click on download button.
The page to download.cnet.com is correctly blocked as badware risk but this action make also a new annoying blank tab.

Firefox 41 final + Windows 7

**Comment by gorhill** [comment]
Specific to Firefox, works fine with Chromium.

**Comment by happysurf** [comment]
Thank you for info but is possible fix this behavior in any way?

**Comment by gorhill** [comment]
I can't answer until I investigate thoroughly if something can be done.

**Comment by gorhill** [comment]
Can't reproduce anymore.
