### ISSUE TITLE
Spotify ads not being blocked anymore

### ISSUE THREAD

**Issue by green-big-frog** [gorhill/uBlock#746]
Hi!
I just wanted to inform you that ads on play.spotify.com aren't being blocked anymore...

**Comment by SW1FT** [comment]
I'm not getting a single ad on play.spotify.com, which filter lists are you using?

**Comment by green-big-frog** [comment]
![image](https://cloud.githubusercontent.com/assets/6208894/10117549/6a0deb96-645b-11e5-939f-7ba51e2fbb18.png)

A few days ago there weren't any ads... maybe something somehow crashed...

**Comment by gorhill** [comment]
Missing details. Browser? Version? Etc.

Do you have a Spotify app installed? See <https://github.com/gorhill/uBlock/issues/675#issuecomment-137978118>. If it is the issue, don't forget to restart the browser after removal of the app.

**Comment by green-big-frog** [comment]
Sorry that I fergot to include the system details...

I actually had the spotify app installed... Can't remember installing it...

Now they are gone again.

But this still doesn't explain why the ads suddenly come/came back?

**Comment by gorhill** [comment]
The link I provided above has the answer: a Chromium regression bug in version 45.

**Comment by JulianNorton** [comment]
Last week Spotify web ads where being blocked, now they're not.  Will try and capture console next time it happens.

**Comment by JulianNorton** [comment]
<img width="1416" alt="screen shot 2017-07-24 at 2 34 00 pm" src="https://user-images.githubusercontent.com/2412992/28538706-33abf09a-707d-11e7-9745-3ae8ac99f0ba.png">

**Comment by gorhill** [comment]
Please report filter issues at <https://github.com/uBlockOrigin/uAssets>.
