### ISSUE TITLE
why not add by default the ad list of the locale of the browser?

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#747]
For example my firefox is in french so the fra easylist should be enabled by default.

**Comment by zummuz** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

Hi, at first it's not hard to check one/few lists. 
At second gorhill has decided not to include all lists by default to make extension package smaller from uBlock 1.1.0.0 version. So when you check not default list first time - list downloading starts. It's not very convenient to download something what user could not want right after addon installation.
Also regional filters have different quality or could stop maintain, so it's better to leave this decision for user.

**Comment by SukharevAndrey** [comment]
Ok, extension may be shipped with preinstalled lists (by the way, outdated). But what if one can enable and install regional lists after installation?

**Comment by LifeIsStrange** [comment]
Yes,most of people never open settings... :(

**Comment by mikhaelkh** [comment]
Actually, this is a duplicate of [this](https://github.com/chrisaljoudi/uBlock/issues/957).
