### ISSUE TITLE
uB disabled in FF Developer

### ISSUE THREAD

**Issue by silat** [gorhill/uBlock#748]
As of right now uB is disabled by FF in Dev. 430a2
![ub ff](https://cloud.githubusercontent.com/assets/7036902/10119520/5e688656-644d-11e5-9d4d-12e047a51bc0.jpg)

**Comment by luxoflux** [comment]
You didn't even mention which uBlock version you're using.

Anyway, either install the signed uBlock [here](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin), or disable the signature requirement:

1. Go to `about:config`
2. Search for `xpinstall.signatures.required` and double click that (set to false)

(FYI: You won't be able to disable this "feature" in future versions of Firefox.)

**Comment by gorhill** [comment]
uBlock Origin is signed, install [from AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/). You can also install a dev version from AMO if you want the [latest dev build](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta).
