### ISSUE TITLE
Polish ADBlock List

### ISSUE THREAD

**Issue by joksik** [gorhill/uBlock#75]
Hi, at start sorry for my poor englih :/ 
i use ublock long time and every time when i install this great extension on my or my friends computer i must add manual the new address for Poland list.

list which is default  use in options:
https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt

is very old and not longer updating. its from 07 Nov 2014.

can you change in options to list that is actual and still keeping update:
http://www.certyficate.it/adblock/adblock.txt

**Comment by gorhill** [comment]
I have fixes for this locally. I will push the changes with the next version, this weekend.

**Comment by marek45** [comment]
It's very good news. Do you plan to add to uBlock a cookies filters like:
https://github.com/r4vi/block-the-eu-cookie-shit-list/blob/master/filterlist.txt
http://www.certyficate.it/adblock/adblock_cookies.txt

**Comment by gorhill** [comment]
Cookie filters is already in there: _"EU: Prebake - Filter Obtrusive Cookie Notices‎ "_, in the _"Regions, languages"_ section.

**Comment by gorhill** [comment]
Fixed in 0.9.4.4.

**Comment by marek45** [comment]
But "EU: Prebake - Filter Obtrusive Cookie Notices‎ " not include polish cookies filters.
![1b](https://cloud.githubusercontent.com/assets/11302675/7215255/75688678-e5cf-11e4-9338-1b5ee78bf353.png)
![1a](https://cloud.githubusercontent.com/assets/11302675/7215256/756d2e30-e5cf-11e4-8f9f-42c1275df24d.png)

**Comment by gorhill** [comment]
> But "EU: Prebake - Filter Obtrusive Cookie Notices‎ " not include polish cookies filters

Is there a reason or a back story for why these two lists are not merged? Both are for cookies in Europe.

**Comment by marek45** [comment]
polish cookies filters include only filters in Poland. EU: Prebake - Filter Obtrusive Cookie Notices‎ not include all filter in Poland. It's a global EU filter.
