### ISSUE TITLE
is it possible to block all inline scripts and then allow exceptions based on new cosmetic filter syntax?

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uBlock#750]
e.g.
rules:
* * inline-script block

filters:
@@||facebook.com##script:contains(/^require\("TimeSlice"\)/)
or
@@facebook.com##script:contains(/^require\("TimeSlice"\)/)

i tried both and they wont work

**Comment by gorhill** [comment]
No.

**Comment by Betsy25** [comment]
@gorhill Sorry for this kinda dumb question.
You got any good web reference for which regex brand uBlock uses, since there are more flavors around. Would this one be a fine one ? http://www.rexegg.com/regex-quickstart.html

**Comment by gorhill** [comment]
Javascript regex. I use <https://regex101.com/#javascript>, quite neat.

**Comment by Betsy25** [comment]
Thanks @gorhill !
Perhaps it might be an idea to add some small clickable "question mark" icons here & there, might save you a bunch of unneeded issue requests.
