### ISSUE TITLE
New extension to benchmark: "Adblock Fast"

### ISSUE THREAD

**Issue by kurtextrem** [gorhill/uBlock#751]
https://github.com/rocketshipapps/adblockfast
But from their description it seems like it blocks way less than uBlock does.

**Comment by zummuz** [comment]
@kurtextrem AF has got 7(sic!) rules and uBlock has (in my case) 338,477 rules and 56,070 cosmetic, default is about 100k+ filter rules (default AB/ABP has 50k rules) so its quite fun to compare these extension.
There are many extensions: adblock super, adblock pro, adblock ultra mega pro, youtube blocker, youtube super blocker, adblock gold ultra mega pro plus etc. And these extension have more users than Adblock Fast, so it's inadequate to compare with crapware/malware forks or with unpopular ones.
Plus it takes some time to benchmark and this time is better to spend on something useful.

**Comment by kurtextrem** [comment]
You're right, but it's interesting how it still blocks ads. 
Youtube, german newspaper sites and so on are completely ad free. You get the gist? AF blocks "everything" (I guess there are pages which have ads, but I haven't found them) with 7! rules, while uBlock / others need 338k.

A note on the other extensions: They're not on Github and are malware / scam (based on their reviews), so you can't compare them with AF (which is also completely new.. which means it can't have a huge user base).

**Comment by harshanvn** [comment]
> AF blocks "everything" (I guess there are pages which have ads, but I haven't found them) with 7! rules, while uBlock / others need 338k

AF has those 7 regex rules derived from EasyList/Bluehell. So, your uBlock should technically achieve the same by selecting Easylist. No need for 338K rules..

And AF has additional cosmetic filters <a href="https://github.com/rocketshipapps/adblockfast/blob/8f0918c26f67e475a93a53713b84fea5033dde90/opera/chrome/scripts/hiding.js">here</a>

**Comment by gorhill** [comment]
Everybody can run benchmarks, it does not have to be me. I did [benchmark BluHell once previously](https://github.com/gorhill/uBlock/blob/master/doc/benchmarks/mem-usage-overall-chart-20150205.png)  and it is essentially what Adblock Fast is: 7 regexes coalescing a subset of EasyList filters.

**Comment by gorhill** [comment]
Also, I did run a mini-benchmark once for Adblock Fast and posted results on Hacker News: https://news.ycombinator.com/item?id=10198994. Bottomline: on average you will end up with a smaller footprint relative to Adblock Fast if you have more than a couple of tabs opened, because uBlock Origin blocks _more_ stuff on web pages, causing web pages themselves to consume less -- eventually the higher footprint of the extension will be amortized by the lower footprint of the web pages.

**Comment by kurtextrem** [comment]
Interesting, I knew you'd be interested in AF. Thanks @gorhill :)
