### ISSUE TITLE
uBlock build of IE 11

### ISSUE THREAD

**Issue by drankinatty** [gorhill/uBlock#755]
All,
This is a **feature request**, not a bug. Is there an chance uBlock can be built for IE 11? I have switched to uBlock with FF on Linux, but when I boot Win 7, I use IE (why?, no real need to load the FF behemoth and add a second complete browser, I use TBird for mail, so installing FF isn't the issue, the issue is can uBlock be built for IE?) Generally, I would say there would be MS issues that prevent a clean build/integration from the proprietary standpoint, but after seeing [**AdBlock Plus**](https://adblockplus.org/) release for IE 11, that got me thinking, Why not uBlock?)

Just food for thought. IE 11 would be much better served if AdBlock was replaced with uBlock. Keep up the great work.

**Comment by gorhill** [comment]
I personally don't plan to ever work on a IE11 version. Code is GPL so anybody is free to fork and make one.

**Comment by lewisje** [comment]
Gaze upon what Eyeo had to do to get ABP working (barely) in Internet Explorer, and have fun trying to improve on their work: https://adblockplus.org/blog/working-towards-adblock-plus-for-internet-explorer
