### ISSUE TITLE
Hangouts Doesn't Work

### ISSUE THREAD

**Issue by Ryan-Goldstein** [gorhill/uBlock#757]
With uBlock enabled, Google Hangouts do not work properly (e.g. launching a video call from https://hangouts.google.com/ or the Gmail chat area). I've whitelisted both hangouts.google.com and plus.google.com, and the network request log shows nothing being blocked, and the uBlock icon is grayed out. Specifically, viewing the other person's video does not work (the screen remains black), and it says after 5-10 seconds that the video call has ended and disconnects me.

The only solution I have found is disabling the uBlock extension entirely, after which Hangouts works perfectly. Any ideas?

**Comment by harshanvn** [comment]
which browser, version and config settings?

do you happen to have "Prevent WebRTC from leaking local IP addresses" option checked? See #681 

If so, may be you can check by unselecting above option, and see if it works for you.

**Comment by gorhill** [comment]
No browser model, version, no details about settings, marking as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Ryan-Goldstein** [comment]
Sorry for not providing those details. This happens on the latest stable version of Chrome (45.0.2454.101) on Linux. I do have the default uBlock setting to block leaking local IP enabled. Even after whitelisting hangouts.google.com and plus.google.com (uBlock icon is grayed out in the Hangouts window), only disabling the uBlock extension entirely resolves these issues with Hangouts.

**Comment by gorhill** [comment]
> I do have the default uBlock setting to block leaking local IP enabled

The setting _"Prevent WebRTC from leaking local IP addresses"_ is **not** checked by default.

> only disabling the uBlock extension entirely resolves these issues with Hangouts

I've seen elsewhere somebody reporting that enabling this setting causes Hangout to not work properly. Please verify if this is the case, un-check the setting and see if it works (you may need to restart the browser).

If the setting is the cause, you will have to remove this setting if you want to use Hangout. You may file an issue with Chromium devs if you think preventing WebRTC leakage should not prevent Hangout from working.

I will let you close the bug if you confirm the WebRTC setting is the cause of the problem.

**Comment by Ryan-Goldstein** [comment]
You were correct; I can confirm that unchecking "Prevent WebRTC from leaking local IP addresses" does make Hangouts start working properly again (no browser restart required, just relaunching the Hangouts page after deselecting that option). Thanks for your time. I plan to file a Chromium bug about this.

**Comment by MatthewHerbst** [comment]
@Ryan-Goldstein any chance you have a link to that Chromium bug?

**Comment by Ryan-Goldstein** [comment]
I never got around to filing a bug for that and haven't tried re-enabling that option in uBO.
