### ISSUE TITLE
commit 12baeadac4 breaks "My filters" on chromium

### ISSUE THREAD

**Issue by octoploid** [gorhill/uBlock#758]
Starting with commit 12baeadac4 filters defined in  "My filters"  have no effect anymore.
Chromium Linux Version 47.0.2520.0 (64-bit).

Reverting the commit "fixes" the issue.

**Comment by gorhill** [comment]
It works on my side, so you will have to give me exact repro steps for me to reproduce -- this means including a custom filter which you say does not work anymore.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/issues/469>.

**Comment by octoploid** [comment]
Hmm, it is working again, apparently because I have hit "Apply Changes" in the "My filters" tab.

Before that a simple filter, e.g.: `www.perlentaucher.de###content > .home_teaser_row`
didn't have any effect.
