### ISSUE TITLE
Suggestion: Popup blocker behave for websites

### ISSUE THREAD

**Issue by Saad1988** [gorhill/uBlock#76]
Firefox has a feature to block popups depended on mouse events. please read:
http://www.ghacks.net/2013/05/27/how-to-block-mouse-click-popups-in-firefox/

i think if we be able to select allowed event for every website, will be more useful and better.
for example :
||p30world.com^$popup@click, mouseup

do you develop it?

**Comment by gorhill** [comment]
The popup blocker currently in uBlock addresses well enough the issues of unwanted popups for when there is no filter.
