### ISSUE TITLE
uBlock filters not updating automatically after purge all caches

### ISSUE THREAD

**Issue by vasicsek** [gorhill/uBlock#760]
uBlock filters does not update automatically after clicking Purge all caches -> Apply changes -> Update now.

Before purge:
- uBlock filters : 83 used out of 84 `purge cache`
- uBlock filters - Unbreak : 58 used out of 58 `purge cache`

After Purge all caches:
- uBlock filters : 79 used out of 79
- uBlock filters - Unbreak : 58 used out of 58

After browser restart:
- uBlock filters : 79 used out of 79 `new version available`
- uBlock filters - Unbreak : 58 used out of 58 `new version available`

After Update now:
- uBlock filters : 83 used out of 84 `purge cache`
- uBlock filters - Unbreak : 58 used out of 58 `purge cache`

So the problem is after I purged all caches then updates all the filters uBlock does not update its own filters. After a browser restart, uBlock offers the filter updates.

Google Chrome 45.0.2454.101 m (64-bit)
uBlock Origin 1.1.1

Filters:
My filters‎ : 0 used out of 0
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy‎
uBlock filters – Unbreak‎
EasyList
Peter Lowe’s Ad server list
Basic tracking list by Disconnect‎
EasyPrivacy
Fanboy’s Enhanced Tracking List‎
Malvertising filter list by Disconnect‎
Malware Domain List‎
Malware domains‎
Malware filter list by Disconnect‎
Spam404
Fanboy’s Social Blocking List
Dan Pollock’s hosts file
hpHosts’ Ad and tracking servers‎
MVPS HOSTS
HUN: hufilter

**Comment by gorhill** [comment]
What do you call a "browser reset"?

I purged all filter lists, then clicked "Update now", and all filters were properly updated.

**Comment by vasicsek** [comment]
Not browser reset, browser restart, sorry.

**Comment by gorhill** [comment]
The local checksum entries are not reset when purging their respective filter lists.

**Comment by vasicsek** [comment]
Sorry for bothering you about this, but could you do something about this issue?

**Comment by gorhill** [comment]
> could you do something about this issue?

I will give priority to this.

**Comment by vasicsek** [comment]
Thank you!

**Comment by wuxiaspear** [comment]
my easylist not updating after purge

**Comment by gorhill** [comment]
Use the logger (select _All_ in the drop down list) to find out whether the request went through and succeeded. It may happen the remote server serving EasyList is down.
