### ISSUE TITLE
Request: for dynamic filtering, match against URLs, not just hostnames

### ISSUE THREAD

**Issue by sebalis** [gorhill/uBlock#761]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax explains that dynamic filtering rules consist of four elements, the first of which are source and destination hostnames. I would like to see this extended from hostnames to URLs. This should be downwards compatible if patterns without slashes are matched against the hostname part of the URL.

**Comment by Snapy** [comment]
[Partially available](/gorhill/uBlock/wiki/Dynamic-URL-filtering) (only for destination).

**Comment by sebalis** [comment]
Thank you. I tested it and it works (if I include the protocol in the destination URL). Please update the documentation in https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax as this is linked to from the uBlock Origin dashboard.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah i couldnt find documentation on this but i remember that one time ublock somehow made a dynamic rule for me blocking an image i wanted blocked on soundcloud.com. it was <domain> <url> image block
i think

**Comment by sumyungguy** [comment]
I would like to second the request to add a wiki link to https://github.com/gorhill/uBlock/wiki/Dynamic-URL-filtering from https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax. As sebalis mentioned, the latter is linked in the dashboard, and should have the information. Thanks...

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-rule-syntax/_compare/0121fe3817a613c843d88760f0d44e11983738d2?short_path=8fdb03e#diff-8fdb03e55cee42186dc18fa83f5581a4

**Comment by gorhill** [comment]
Closing as fixed with above commit.
