### ISSUE TITLE
Seamonkey: Missing icon on toolbar not in Customize

### ISSUE THREAD

**Issue by grumpygeek** [gorhill/uBlock#763]
Can't use this without a user interface to configure site rules, and also like to see what's blocked.  I can open the Dashboard but that isn't enough (I see no.way to add a rule even if I wanted to settle for no toolbar icon).  I have used HTTP Matrix in Chromium based browser so I'm familiar with the usage.

uBlock icon also now missing (it has stayed in Firefox variants so far).  [Ghostery has gone hiding as well - old problem not yet fixed in Seamonkey.]  This missing or just moving-to-far-right happens with several no-restart extensions -  possibly a bug in jetpack itself, except it doesn't affect all restartless extensions.

**Comment by 5t3f4n** [comment]
I've noticed both uBlock Origin and uMatrix icons disappear from the toolbar, seemingly randomly, from time to time, but I've always been able to simply re-add them from the customize menu. Try disabling/enabling uBlock Origin or restart SeaMonkey and look in customize again.

But for what it's worth, you **can** use uBlock Origin without the icon, but it is not optimal.

Open `about:addons`
For uBlock Origin, click `More` then `Show Logger`
Now, from the logger (`chrome://ublock0/content/logger-ui.html`) select the site/scope you want to manage from the dropdown and then click the cell directly to the right of the timestamp cell.
You should now have the popup and be able to use it normally.

You can also enter filters and rules manually in the My filters and My rules tabs in the Dashboard.

**Comment by grumpygeek** [comment]
Yes, the random disappearance of the toolbar icons is the issue.   It is more important to have the icon for uMatrix but I want it for uBlock too if I use both.  I did get uBlock icon back by reenabling it after a restart.  Didn't get to test uMatrix yet (SeaMonkey has locked itself in safe mode!) but I assume it will come back too.  I will take a look at logger.  But based on past experience with the frequency of occurrence of this problem with other extensions, I don't consider disabling/re-enabling (or restart or even deleting localstore was necessary at times) to be an acceptable solution.  Where there are other extensions that perform similar functions, I would settle for those that are stable even if not my favorite.

**Comment by 5t3f4n** [comment]
The above steps work (roughly) the same for uMatrix as well just FYI but I realize this is not something most people are comfortable with. But the disappearing icon issue is not exclusive to uBlock Origin or uMatrix, it has happened at least once to each of my extensions that have an icon.

Have you enabled `extensions.ublock0.legacyToolbarButtonAdded` ?

**Comment by grumpygeek** [comment]
That setting is already enabled.  This one wasn't so I enabled it too:
extensions.ublock0.forceLegacyToolbarButton
The uBlock icon is already gone again, but I'll see how it does after restarting with this.
FWIW, on settings tab, I have checked 1-3 and 6-9 (only color blind and cloud storage not checked).

Logger was interesting in that it showed requests that don't show in LiveHTTP or HTTPFox.

I'm just learning uBlock's features; seems to have good potential if you dig deeper.

**Comment by gorhill** [comment]
> the random disappearance of the toolbar icons is the issue

If only I could reproduce easily that would allow me to investigate the issue. Is it possible this occurs only when some other extensions are present?

**Comment by gorhill** [comment]
Don't know if it's related, somebody is reporting a similar issue with Pale Moon: <http://forum.palemoon.org/viewtopic.php?f=15&t=9599>.

**Comment by grumpygeek** [comment]
Yes, Pale Moon, Waterfox, and various Firefox browsers I've used all have the problem.   But there is no hope of getting Mozilla to fix their code - it's been happening since the teen version #s best I can remember - so I hope the extension devs can work around it.   Other extensions it affects include Bluhell Firewall, Clean Links (and probably others by this dev), Request Policy, Ghostery (which is presently not functional in SM anyway) - all restartless.  I'm not positive but it may have something to do with those that place their icon on the navbar after install rather than letting the user add it.  I really want to be able to put nearly all extension buttons on a different toolbar without causing problems; I like to keep my navbar for just the url box and a few nav specific.buttons. It's annoying to me but I know extension authors add their buttons there by default now because Mozilla/Firefox devs did away with the status/addon bar and they think users are too dumb to find it and add it themselves.

I suppose I could test with a clean profile and only uBlock and/or iuMatrix installed.   But I'd be surprised if it is due only to interaction with certain other extensions.  I don't normally want to run the browser without certain extensions so I don't have and likely won't have a lot of experience using it bare.  I understand it's just for testing though, so I may try it (no promises).

The force icon setting did not make any difference.

**Comment by grumpygeek** [comment]
I've experimented some with the other extensions that have this problem disabled.  In Seamonkey, I started with a clean default profile, and installed only uBlock Origin.   In Waterfox, I just disabled the worst offenders and am using uMatrix.  Both setups are showing more stability of the uBlock/uMatrix icons so far.  

In Seamonkey with uBlock, I next tried installing LastPass and after restart the uBlock button was bumped off the toolbar but was in Customize.   No further problems with other addons I've added since, including some restartless ones (but not the worst ones).  It may be a little early to say that the problem was caused by one or more of the other extensions.  I'll try doing without them and see how it does.  

I believe that uMatrix more so than uBlock, once properly configured for my browsing, might replace many of the functions I relied on those other extensions to provide. But I'll keep uBlock in the other less used profile for further testing.

**Comment by gorhill** [comment]
I release an [rc4 version](https://github.com/gorhill/uBlock/releases/tag/1.3.0rc4) with code for toolbar icon reworked. Would be nice to see if this helps with the issue here.

**Comment by hu475** [comment]
I too have been experiencing missing icon issue time to time (seems to be random but more frequent after Firefox v. 40 and onwards). Just installed the rc4 version and it seems to fix my problem. Will update you if anything changes.

**Comment by grumpygeek** [comment]
Thanks.  I tried installing RC4 xpi but could not get it to install.  In Waterfox, it hung on the verifying step with the install button greyed out.  In Seamonkey, I clicked "Install Software" button, it disappears, then nothing.  I've also got Cyberfox and PCXFirefox installed (the latter is basically plain FF under different name).   I can try those too sometime if it might matter but I'm doing some research right now and don't want to shut down Waterfox..  FWIW, uBlock icon has been stable in my clean profile in SM.

**Comment by hu475** [comment]
Update: the icon (rc4) is gone again in the latest FF (41.0.2). But uBlock is working without a doubt. My log entry is only showing every second this: http://127.0.0.1:12546/ I'd be happy to provide you with more information if needed. Best.

**Comment by gorhill** [comment]
> the icon (rc4) is gone again in the latest FF (41.0.2)

Are you using the Australis or the legacy toolbar icon?

For anyone trying the latest version, I would suggest to first:

- `about:config` => reset the `extensions.ublock0.legacyToolbarButtonAdded` entry
- `about:config` => set the `extensions.ublock0.forceLegacyToolbarButton` to
    - `false` if you want to use Australis-based toolbar icon
    - `true` if you want the legacy toolbar icon (can be used to address issues like [uBlock Origin popup UI not accessible if removing URL toolbar](https://github.com/gorhill/uBlock/issues/112))

Then restart Firefox and customize as you wish. The latest code re. toolbar icon has really been proof against failure and I am not able to reproduce any issue with it, trying all sort of Firefox version (Pale Moon, SeaMonkey, FF41, Nightly) with legacy/Australis toolbar icon.

Note that I have only uBlock installed, no other extensions. So if something does not work, it would be useful to investigate whether your issues with uBlock toolbar icon disappear if you run uBlock alone, and if so, to try to narrow to which other extension might interfere.

**Comment by gorhill** [comment]
From [Pale Moon forum](http://forum.palemoon.org/viewtopic.php?f=15&t=9599&start=20#p67870):

> I realized that this is not an issue of uBO by itself, but rather some kind of incompatibility with the Ghostery addon. It seems that Ghostery is rather aggressive in putting its icon back to the navigation toolbar, and in the process, it somehow "pushes" the uBlock Origin icon from the toolbar.

I just tested (FF41, Ghostery does not install on Pale Moon) and I can confirm that Ghostery's toolbar icon disregard the previously assigned position when it is placed immediately after uBO's button -- but only when uBO's button is in legacy mode.

Maybe other extensions behave similarly, which could push uBO's button further to the right, and maybe eventually off the toolbar. The way @AlexVallat wrote the button insertion code for uB/uBO means it is respectful of the current order as laid out in the `currentset` attribute of the toolbar, so it won't "strongarm" other extension buttons off the toolbar.

**Comment by gorhill** [comment]
I pushed a new rc5 in Releases, may be the last commit will change something. After looking at the content of the `currentset` attribute, I see a lot og "garbage" in there, i.e. references to removed add-ons. So given this I modified a bit the code to narrow the scope if finding an insertion point to the target toolbar only.

**Comment by gorhill** [comment]
rc6 on _Releases_ page -- will check feedback later when I am back.

**Comment by hu475** [comment]
Hi. I am using the latest FF so I guess I am on Australis. 

However, after following your advice, I tried to pin down which add-on, if any, might cause the issue. And, I am positive that RSS icon in url bar is forcing the uBlock's icon (1.3.0.rc6) to disappear. A link to the add-on can be found here: https://addons.mozilla.org/en-GB/firefox/addon/rss-icon-in-url-bar/?src=api

I have a couple of add-ons so what I did, first, was to disable all but uBlock, then enable them one by one on separate instances to see if uBlock works nicely. After enabling RSS icon add-on and restarting FF forced uBlock's icon to hide/disappear. Happy to provide more info if needed. Best.

**Comment by gorhill** [comment]
Closing as because OP reported above that _"uBlock icon has been stable in my clean profile in SM"_.

**Comment by timur-tabi** [comment]
Is there a way to re-open this issue?  I'm running the Seamonkey 2.39 on Linux, and I never see the uBlock button, even on clean profiles.

**Comment by gorhill** [comment]
I see it fine on Linux/Seamonkey 2.39. Investigate on your side why this happens, I can't investigate if I can't reproduce -- works fine here. If ever you figure steps for _anybody_ to reproduce, I will look into it.

**Comment by timur-tabi** [comment]
Ok, I figured it out.  Somehow, it was removed from the Navigation Toolbar.  Apparently, the default behavior for new profiles is to not display that button.  All I had to do is right-click on the bar, click "Customize..." and drag the uBlock button to the toolbar.

I don't see any mention of this in the documentation.

**Comment by gorhill** [comment]
> Apparently, the default behavior for new profiles is to not display that button.

You're right, I could reproduce this with a new profile. The button should definitely appear by default. Open an issue about this I will look into it as time allow.

**Comment by Hrxn** [comment]
Slightly off-topic, but I don't recommend using Seamonkey 2.39. That version is slightly outdated, based on an older version of Firefox.

You might be missing these:
https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/

In the end, it's your decision, of course. If you feel safe, fine..

**Comment by timur-tabi** [comment]
Uh. 2.39 is the latest version: http://www.seamonkey-project.org/
