### ISSUE TITLE
blocking site focus.de completely

### ISSUE THREAD

**Issue by ullix** [gorhill/uBlock#764]
using uBlock Origin 1.1.1 in Firefox 41.0 on Ubuntu the site focus.de is blcoked completely, no content is visible. onl the start buttons for video are visible

**Comment by gorhill** [comment]
The site is visible, it's just you have to scroll down. Same issue with ABP + same filter lists, so this is a 3rd-party filter lists issue, reporter to EasyGermany maintainers: <>.

This filter seems to work: `||www.googletagservices.com/tag/js/gpt.js$domain=focus.de`.

**Comment by 5t3f4n** [comment]
Blocking `script` from `www.googletagservices.com` fixes it.
This dynamic filter
`focus.de www.googletagservices.com script block`
or this static filter
`||www.googletagservices.com$script,domain=www.focus.de`
Should solve it I think.

**Comment by ullix** [comment]
@gorhill: no, the site is NOT visible. what is visible when you scroll down is the bottom part of focus.de. The top part remains blocked.

@5t3f4n : I put this under "my filter", and it worked:
www.googletagservices.com$script,domain=www.focus.de

First I put "focus.de www.googletagservices.com script block"   under my filter, but that did not do anything. Though, if dynamic filters need to be put elsewhere, I don't know where.

Thanks
