### ISSUE TITLE
Block sites

### ISSUE THREAD

**Issue by bluegeekgh** [gorhill/uBlock#765]
Is it possible to block completely the access to sites like the SiteBlock extension. The rule "* domain.com * block" downloads the main page from domain.com.
Thanks

**Comment by Snapy** [comment]
Make a static filter and add the `$document` option. It should trigger the strict blocking page.

**Comment by gorhill** [comment]
You can strict-block with dynamic filtering. You can however with static filtering as answered by @Snapy:

    ||domain.com^$document
