### ISSUE TITLE
Please add uBlock Origin to addons.opera.com

### ISSUE THREAD

**Issue by mathiasbynens** [gorhill/uBlock#767]
Please consider uploading the extension to https://addons.opera.com/. This way Opera users can easily install it.

Note that this requires 0 code changes — the code already runs in Opera since it’s Chromium-based.

**Comment by harshanvn** [comment]
its already in there! look <a href="https://addons.opera.com/en/extensions/details/ublock/?display=en">here</a>

Not sure why Raymond did not update the title though..

**Comment by mathiasbynens** [comment]
Ah, whoops! I actually did notice that one, but thought it was the original uBlock rather than uBlock Origin. My bad!

**Comment by gorhill** [comment]
> thought it was the original uBlock rather than uBlock Origin

The Opera store people told me it was not possible to change the name, so uBlock Origin is stuck with the old name in Opera store.

**Comment by harshanvn** [comment]
Maybe you can add a one line note in the description.. Just a thought
