### ISSUE TITLE
https in whitelist

### ISSUE THREAD

**Issue by bones78** [gorhill/uBlock#768]
Is is possible to add https in whitelist without a specific domain? I would like to have this feature do deactivate uBlock on every https site.

**Comment by Snapy** [comment]
Add `@@|https://` in "My filters" tab.

**Comment by bones78** [comment]
unfortunately this does not work.

**Comment by Snapy** [comment]
Did you put it in the right tab and have you checked My filters in the "3rd party filters" tab ?

**Comment by gorhill** [comment]
`https://` is not a valid whitelist directive.

**Comment by bones78** [comment]
in the log I see a difference to a website on the whitelist. The site on the whitelist it is highlighted green. The (new) https site (not in the whitelist) is not green highlighted.

**Comment by Snapy** [comment]
@bones78  But is the request blocked ?
@gorhill  But is `@@|https://` a correct filter ?

**Comment by gorhill** [comment]
> But is `@@|https://` a correct filter ?

Yes.

**Comment by bones78** [comment]
if blocking means in the log a red highlight then no.

**Comment by gorhill** [comment]
I tried it, the filter is properly enforced: all network requests which URL starts with `https://`, which would be otherwise blocked by a block filter, are properly excepted by the `@@|https://` filter.

**Comment by gorhill** [comment]
> the doc entry is not green in unknown https sites

`@@|https://` is an exception network filter -- not a whitelist directive -- it's a workaround which has been proposed to you because `https://` is not a valid whitelist directive. The `@@|https://` won't apply if it does not need to be applied, i.e. it does not apply to non-blocked network requests.

**Comment by bones78** [comment]
@gorhill thanks a lot for the explication. By the way is there any filter which deactivate a range of local websites e.g. 192.168.0.1. to 192.168.0.100?

**Comment by gorhill** [comment]
> is there any filter which deactivate a range of local websites e.g. 192.168.0.1. to 192.168.0.100

Doesn't this work: `@@||192.168.0.*/`?

**Comment by bones78** [comment]
seems to work, thanks a lot.

**Comment by anewuser** [comment]
@bones78 Please click on the "Close issue"  button next to the "Comment" button to mark your issue as solved.
