### ISSUE TITLE
RFE: cosmetic filtering integration with the firefox web-inspector

### ISSUE THREAD

**Issue by bagodoosh** [gorhill/uBlock#771]
it would be nice to merge the changes from chrisaljoudi branch, regarding the integration with firefox's web-inspector.

added in chrisaljoudi  0.9.3.5, apr 19, 2015.
if i'm not mistaken: chrisaljoudi/uBlock#1211 + chrisaljoudi/uBlock#1324

**Comment by harshanvn** [comment]
See <a href="https://github.com/gorhill/uBlock/wiki/DOM-inspector">DOM Inspector</a>. gorhill implemented in browser independent way, unlike the other one.

**Comment by bagodoosh** [comment]
i understand. i thought this browser-specific feature would be a nice addition, if it does not cause a conflict.

**Comment by AlexVallat** [comment]
If you don't mind building the xpi from source, I've got a branch that does exactly that: https://github.com/AlexVallat/uBlock/tree/gorhil-master

**Comment by gorhill** [comment]
Duplicate of #119.
