### ISSUE TITLE
Update README.md - 70b4d3e

### ISSUE THREAD

**Issue by weakptr** [gorhill/uBlock#772]
https://github.com/gorhill/uBlock/commit/70b4d3e037bf69d29e919207256038d4aa6098a2
Typo (uBlock Origin is **pusblished** under the name "µBlock" in the Opera store -- the name can't be changed). 
Should be (uBlock Origin is published under the name "µBlock" in the Opera store -- the name can't be changed).

**Comment by gorhill** [comment]
Thanks, fixed.
