### ISSUE TITLE
Create landing pages in the wiki for features with caveats

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#773]
From [Hacker News](https://news.ycombinator.com/item?id=10318862):

> Oh I had no idea ["prevent WebRTC's local IP address leakage"] would prevent [Hangout] from working. I wish they made that clear.

Currently the WebRTC setting extra info URL links directly to <https://www.w3.org/wiki/Privacy/IPAddresses>. This is not very helpful to quickly inform about whatever current caveats may exist when using a specific feature on a specific browser.

I will create landing pages in the wiki to detail whatever current caveats as a consequence of using the feature. Then this landing page can further link to good 3rd-party information.

**Comment by KrisSiegel** [comment]
Since a majority of people never read directions, regardless of whether they should or not, I think it would be handy to toss something next to the option itself like "```(may break some services that relay on WebRTC such as Hangouts or Facebook Messenger)```".
