### ISSUE TITLE
Backup File Naming Scheme

### ISSUE THREAD

**Issue by iamzam** [gorhill/uBlock#774]
I want to submit a would-be-nice-to-have feature request.  This could be for umatrix as well, maybe that's a copy/paste kind of thing...

I have backups of ublock/umatrix going back a few months, and I back up regularly and then import into my other computers.  When I have to manage lots of files centrally in dropbox or GDrive I adopt a naming scheme like YYYYMMDDhhmm-<computer name>-<app name>-<file contents>.txt so for ublock I have from the last backup:

201509271809-mrmini-ublocko-backup.txt
201509271809-mrmini-ublocko-static-filters.txt
201509271810-mrmini-ublocko-rules.txt
201509271810-mrmini-ublocko-whitelist.txt

This has the effect of naturally sorting the files in the order they are created and it is trivial to find the last backups or to go back and find all the backups from one specific day.  

It would probably be too much to implement some sort of custom naming scheme with macros like %y for year %m for month and so on but perhaps you could change the order of the elements of the current backups to at least have the date with year/month/day first or you may even have another naming scheme in mind that would be better.

Now, you might say I could sort the files by date created or modified but some text editors don't have the ability to sort in the sidebar (looking at you atom) and if you don't know exactly which day you are looking for your eye has to roam deep into the list and to the right to look for the right month/day, etc.

Thanks for the best ad/tracking blocker and for giving it a think

dv

**Comment by gorhill** [comment]
This was fixed with da163bbe4bfdb46d5e02790daf98ea455676ec6a.
