### ISSUE TITLE
uBlock shows empty ad space before hiding it

### ISSUE THREAD

**Issue by slaughtermouse** [gorhill/uBlock#775]
Apologies if this has been mentioned before, I wasn't really sure what search criteria to use.

For example, in Chrome, if you browse http://www.gpforums.co.nz/ you can see the empty space up the top where the ad was before it's hidden and the main forum contents shifts up to where that empty space was. This only happens once per visit, however if you close the browser and open it again the empty space is shown then hidden.

Note, the ad isn't displaying just the empty space where it was, with Adblock this empty space isn't displayed.

Is it possible for the empty space to already be hidden instead of displaying it before shifting all the elements?

Below is a screenshot of what I'm talking about.
<img width="1387" alt="initial load" src="https://cloud.githubusercontent.com/assets/14948829/10260883/95c1ddb6-69dc-11e5-86f9-0ddb819d2e9f.png">

<img width="1380" alt="empty space hidden" src="https://cloud.githubusercontent.com/assets/14948829/10260882/958efa86-69dc-11e5-9b47-37d5629ee4ed.png">

**Comment by weakptr** [comment]
See if adding the following site specific filter to _My filters_ makes a difference:
`www.gpforums.co.nz###layoutTopBanner`

**Comment by slaughtermouse** [comment]
Thanks, that does stop the empty space showing.

I should have added this happens on any site with ads, gpforums was easiest to display the behaviour

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

**Comment by gwarser** [comment]
@gorhill, for how long these filters are cached?

**Comment by gorhill** [comment]
> how long these filters are cached?

- cache units are per-hostname.
- cache units are flushed after 20 min of being unused.
    - except: the 10 most recently used cache are always exempted from being flushed.
- the cache janitor kicks-in every 5 min.
