### ISSUE TITLE
Default enabled HTTP-only rulesets

### ISSUE THREAD

**Issue by smarek** [gorhill/uBlock#776]
Hello,

I've come again to uBlock since Adblock was sold, and so far it's really nice experience.
Bugs I've observed before are now gone, thanks for hard work on this project!

I'd like to discuss one thing, by default, there are HTTP-only rule sources enabled, which is in my opinion dangerous. Would it be plausible for you to enable only HTTPS sources in default settings?

Thank you!

**Comment by gorhill** [comment]
> HTTP-only rule sources enabled

I don't know what you are talking about. What is "HTTP-only rule sources"?

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think they mean the 3rd-party filters which are downloaded through http urls? (which are also clearly labeled)

**Comment by smarek** [comment]
@berrythesoftwarecodeprogrammar i'm sorry, yes, that's exactly what i was talking about. Though they are labeled, some of them are enabled by default, which feels insecure to me.

**Comment by gorhill** [comment]
> which feels insecure to me

The concrete benefits of having these filter lists enabled by default for all users vastly outweigh the _feel_ of insecurity _you_ may feel.
