### ISSUE TITLE
Weird graphic glitch on FF Beta

### ISSUE THREAD

**Issue by Tajnymag** [gorhill/uBlock#778]
Hi, when I visit the custom lists section in settings of the addon, I get this type of weird glitching while scrolling down. Actually I don't know how better to describe my problem than to show you the images, so here they are:

![4mci6nw](https://cloud.githubusercontent.com/assets/3985946/10264067/f2e5f1aa-6a02-11e5-9294-a41a245aebbb.png)
![uhrrmqu](https://cloud.githubusercontent.com/assets/3985946/10264080/0ec870f0-6a03-11e5-8e58-908987aa94bf.png)
![cpj5z6o](https://cloud.githubusercontent.com/assets/3985946/10264084/2a40e344-6a03-11e5-8352-4b82e2e37309.png)
![z3cuhuv](https://cloud.githubusercontent.com/assets/3985946/10264100/6bd76c6a-6a03-11e5-9205-cf94d279279b.png)

**Comment by gorhill** [comment]
uBlock Origin's dashboard are just plain HTML/CSS/JS documents. There is something specific in your browser settings which causes this. Use the inspector to find out what's going on in the DOM -- apparently something on your system is messing with uBlock's pages. The HTML source for that web page is in the repo: <https://github.com/gorhill/uBlock/blob/master/src/3p-filters.html>.

**Comment by gorhill** [comment]
Closed by mistake.

**Comment by Tajnymag** [comment]
OK, I solved it by updating from FF42.0b2 to FF42.0b3 . Even though it's fixed for me now, there might be still people having this problem. Thanks for your time :)
