### ISSUE TITLE
[Palemoon] Incorrect classification as 'newtab.about-scheme'

### ISSUE THREAD

**Issue by Tharn** [gorhill/uBlock#779]
Hi,

When I opened a Youtube tab from one of my bookmarks just now, I noticed that uBlock was disabled on it. Turns out that enabling it with the 'power' button removed the 'about-scheme' whitelist setting I had set. There is apparently a condition where a regular browsing tab ends up being classified as 'about-scheme'. It does not happen every time and I haven't been able to discern a pattern to this behaviour.

This has happened before with an older version, with 1.1.1 and with the 1.1.2 beta I'm using now.

Update: A broken tab like this will remain broken even when it's reloaded, when clicking links or typing in other URLs. It is listed in uBlock's network request log simply as 'New Tab'. uMatrix is running alongside and is handling it correctly.

Update 2: I think I have figured out a way to reproduce this. First you open a new tab. Then you go into bookmarks (which is on my tab bar as a classic menu button, not the sidebar one) and spend some time just hovering over the various links and looking at the tooltips, half a minute's usually enough. When you do open a bookmark, there is a high chance that it'll show this issue.

**Comment by Tharn** [comment]
I've narrowed this down. 1.0.0.1 is the last 'good' version. The bug was introduced in a commit to 1.1.0.0.

**Comment by gorhill** [comment]
I think the issue behind this could be #852, which was fixed in 1.3.2. This needs confirmation.

**Comment by Tharn** [comment]
I haven't seen it happen in several weeks so I suppose this has been fixed around 1.3.0 already. Wish I knew what it was, but there we go. ;)
