### ISSUE TITLE
Visually identify 3rd party filters that are fetched over insecue http

### ISSUE THREAD

**Issue by grrrrr** [gorhill/uBlock#78]
Could we get a feature added to the _3rd-party filters_ tab  that will show either:
- which filters are done over https.
- which filters are done over http.

As I am sure everyone is now aware; anything done over HTTP is easily manipulated and given that these filters have the ability to manipulate your browsing traffic it would be important that it is made clear which 3rd party lists are susceptible to man in the middle attacks and could put you more at risk

**Comment by sergeevabc** [comment]
@gorhill, red is enough to increase attention, extra step with strike-through makes label noisy and hard to read. If you’re that sure we need to clutter interface with this label (I believe we should not), think of something without strike-through, e.g. simply put *http* in red.

@grrrrr, it’s trendy to speak of securing assets by means of HTTPS nowadays, yet public adblocking lists, updated by prominent people, verified by millions of users daily are the least subject to worry about.

**Comment by lukelarris** [comment]
Some sort of tooltip or legend about the red http indicators would be helpful, I had to google this issue to figure out whether it meant my lists weren't being fetched because their servers were down.

**Comment by tofof** [comment]
Tooltip would be helpful. I also ended up at this issue wondering exactly what the indication meant.
