### ISSUE TITLE
AMD Drivers/Support site problem 

### ISSUE THREAD

**Issue by m1losh** [gorhill/uBlock#780]
Hi! I hope I'm reporting this in a right place! :)

http://support.amd.com/en-us/download
...clicking on a 'DISPLAY RESULTS' button, after filling up 'STEP1-4' combo-boxes, does nothing.
Of course, after disabling uBlock & reloading page, everything works properly.

uBlock 1.1.1 (stock settings), Opera 32 x86 (clean install, no additional extensions), Windows 7 x64.

Anyway, thanks for an amazing extension. All the best - Miloš

**Comment by Tharn** [comment]
Can't confirm, it works fine here. This is either a blocklist or a script blocking issue. uBlock by itself is not responsible.

**Comment by Zod-** [comment]
The site needs `google-analytics.com` and `googletagmanager.com` to work. 

Add this to your filters

```
@@||google-analytics.com^$domain=support.amd.com
@@||googletagmanager.com^$domain=support.amd.com
```

**Comment by m1losh** [comment]
@Zod- I've added those two lines, and now it works fine. Maybe 'support.amd.com' should be whitelisted? Anyway, I've had a customer calling me, all confused because she couldn't download drivers - although I knew what was the culprit, I assume it's not that obvious to the regular user.. I just wanted to point it out, so uBlock doesn't get the bad rep. Thanks & good job! HF :)
