### ISSUE TITLE
[feature request] allow tooltips for advanced users

### ISSUE THREAD

**Issue by mbillen** [gorhill/uBlock#784]
Advanced user mode disables all tooltips by default but sometimes it might be useful to have them even though advanced user mode is enabled. Is it possible to add a configuration checkbox which enables tooltips for advanced users?

**Comment by publicarray** [comment]
Duplicate of #451

**Comment by publicarray** [comment]
See: https://github.com/gorhill/uBlock/issues/639#issuecomment-135095683
