### ISSUE TITLE
Drop-down list with preset filter expressions in logger

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#787]

**Comment by gorhill** [comment]
Context for translators:

![a](https://user-images.githubusercontent.com/585534/50184153-34033280-02e2-11e9-9700-5079dbda00f0.png)

"eventful" is to show only the items in the logger for which uBO actually did something: blocked, allowed, redirected, hid, etc.

**Comment by gwarser** [comment]
Anyone seeing this?

![image](https://user-images.githubusercontent.com/886325/50368660-83b85700-058b-11e9-9f25-b1d5f0a28c5a.png)

Input shrinks in width when I start typing and logger content changes, clicking on "V" restores it back.

**Comment by okiehsch** [comment]
Looks fine on my end.
![image](https://user-images.githubusercontent.com/16838044/50368939-5c16be00-058e-11e9-8407-17b27a2f8fa6.png)

**Comment by gwarser** [comment]
Firefox only?

**Comment by gwarser** [comment]
I see this on all branches of Firefox. Left and right borders of the input switches between 8 and 2.

**Comment by gwarser** [comment]
Yes

**Comment by gorhill** [comment]
Ok I can reproduce some changes in width, though not as pronounced as what you report. Now I can investigate.

**Comment by gorhill** [comment]
It's related to the background color set by uBO, somehow. No need to type characters in the field, what matters is that the input field's focus is toggled:

1. Open inspector
2. Bring forth Rules inspector
3. Inspect the `input` field
4. Check `:focus` on it
5. Toggle `background-color` property on uBO's rule `input:focus`
6. Resize a just a bit the logger window
7. Goto 5.

You will see a change in the size of the input field depending on whether the background color property is that of uBO or the user agent's default one.

Forcing a default background color to something fixes the issue. Alternatively, removing the rule `input:focus` also fixes the issue.
