### ISSUE TITLE
Incompatibility with Beyond Australis?

### ISSUE THREAD

**Issue by Quicksaver** [gorhill/uBlock#788]
Can anyone confirm the following incompatibility with my Beyond Australis add-on: https://addons.mozilla.org/firefox/addon/the-fox-only-better/reviews/751404/
> I had to disable it because it slows down the scrolling on OS X (Yosemite with FF 40.x) which becomes annoyingly jumpy
> UPDATE: it seems that it's the interaction with another plugin. From a few quick tests I feel that it interferes with uBlock Origin

In short, supposedly scrolling the webpage becomes laggy/jumpy when both uBO and BDA are enabled together, but I can't reproduce it with the latest versions of both add-ons on FF41, and I only have access to OS X Lion unfortunately.

**Comment by publicarray** [comment]
I have OS X 10.11 (El Capitan) and I can't reproduce with FF 41.0.1, uBlock Origin v1.2.0rc1 and Beyond Australis v1.3.1

**Comment by publicarray** [comment]
Is there a particular URL where this problem is occurring? (would be good to have a test case)

**Comment by Quicksaver** [comment]
I asked the user (he sent me an e-mail once after my reply to that review) but he hasn't replied since. I'll wait for a few more days, but if he doesn't reply until then and if no one else confirms this, we'll have to close this as either invalid or fixed in the latest version(s).

**Comment by publicarray** [comment]
@Quicksaver your link/review now returns a 404 error. I would assume that the OP has solved the issue or lost interested in fixing it. Thanks for reporting the issue but I think this issue can be closed now.

**Comment by Quicksaver** [comment]
That's actually because the review was removed by an AMO moderator for being a bug report, and a poor one at that for having no follow-up. Yeah, since none of us can reproduce the issue, I can only assume it's either been fixed in the latest versions of the add-ons/firefox. I'll re-open if I ever have more info, thanks for testing it before.
