### ISSUE TITLE
make cloud storage import+merge more discoverable?

### ISSUE THREAD

**Issue by fjarlq** [gorhill/uBlock#790]
I just noticed this excellent tip in the [cloud storage documentation][1]:

> **Tip:** if you hold the <kbd>Shift</kbd> key when clicking the _"Import from cloud storage"_ button, uBlock will import and _merge_ with the current pane settings (as opposed to overwriting the pane current settings).

I wish this import+merge function was somehow more easily discoverable in Options, because I've been wanting it for a while, but I had no idea it existed.

Would it work to have two buttons?
* "Import from cloud storage (_replacing_ the current settings)"
* "Import from cloud storage (_merging_ with current settings)"

[1]: https://github.com/gorhill/uBlock/wiki/Cloud-storage

**Comment by torzsmokus** [comment]
any update on this?

**Comment by gorhill** [comment]
New button added:

![a](https://cloud.githubusercontent.com/assets/585534/12530293/c1b2a8b4-c1a8-11e5-8f94-079df0d3259b.png)

The <kbd>Shift</kbd> key trick has been removed.
