### ISSUE TITLE
"Blocked since install" goes to zero after restart FF *solved*

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#793]
After one week of use while NO issues occurs: Suddenly the counter "of all blocked actions since install"... goes to ZERO (0) everytime I shutdown/restart my Firefox. Before that fatal moment uBlock Origin was counting as advised and SAVED it, no probs! (I didn't do something that might cause this behavior... even no updates!) . Is there a secret option which sets the counter to zero after shutdown (I would prefer... btw.)?
Version 1.1.1 of uBlock Origin
Browser: Firefox 41 and Iceweasel 38.03 ESR (additionally both tested WITH A CLEAN home folder and no other addons installed).
OS: Linux Mint Debian edition Betsy 2

**Comment by 5t3f4n** [comment]
uBlock Origin was recently updated to version [1.2.0](https://github.com/gorhill/uBlock/releases/tag/1.2.0). Try updating (or even re-installing) and see if your problem persists.

**Comment by Laserfischen** [comment]
I've updated uBlock Origin in the past due this problem to all available versions (beta AND the stable 1.2.0 release, too)... problem persits. I've created an new home for Firefox (like a new installation of Firefox)... problem persists. I don't know, what might cause this behavior... While the endless tests I realised that at some point (maybe like leaving the browser open for several minutes with some blocked events logged or sometimes going over 350 blocked events logged) the counter reminds the ammount correctly after a restart of FF... but than it counts after each restart again from the former saved value (like the 350).

**Comment by gorhill** [comment]
The count values are stored in the SQlite database in the user's home folder (see <https://github.com/gorhill/uBlock/tree/master/dist#firefox>). Is there something tampering with uBlock's SQlite database on your system?

**Comment by Laserfischen** [comment]
Normally not... like I don't change any option by my OS to manipulate this (simply I don't know how) and I've tested it with a clean FF Home (and no other addons in). Or what do you mean? As I wrote in the earlier post: In the first week... nothing like this behavior was noticed. I've replaced the uBlock Origin database several times... problem persists.

**Comment by gorhill** [comment]
> I've replaced the uBlock Origin database several times btw

What do you mean by "replaced the uBlock Origin databse"?

**Comment by Laserfischen** [comment]
I mean... I erased the whole FF home folder (with all data in it) or
sometimes only the uBlock Origin database several times, so that I can
reveal the cause of the problem uBlock Origin shows in this special
case. It was part of my research... and was only used AFTER I was aware
of the counter malfunction.

**Comment by gorhill** [comment]
When the issue occurs, can you look at the browser console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>J</kbd>) to see if there are any messages of interest?

**Comment by Laserfischen** [comment]
Sounds to find something like this?

getPreventDefault() shouldn't be used anymore. Use instead
defaultPrevented. jquery-1.7.1.min.js:3:0  (translated by me, hope I get
it!)

and

TypeError: target.getAttribute is not a function


Am 08.10.2015 um 19:07 schrieb Raymond Hill:
> When the issue occurs, can you look at the browser console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>J</kbd>) to see if there are any messages of interest?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gorhill/uBlock/issues/793#issuecomment-146625932
> 

-- 








-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFXXNOUBEACvAd4mw6jl3o7wsgblDRclU9QVEHCDSvh6PO3yzTRjjaUhI/bC
UAgliOcPkW1DfFFzxN6ccB+lfrFTkUVpVM124PWdbFOA7smYtNUXLobTSW6LqAlc
OSX8w+B6ACqSrNl+jvxdOcUn02rFDaDawCvrpDBxLymekIrejg4UWlkKtq0JeFkd
dVDKI7pGegbey07ponwYVKKi9qFpQ2l86PjsYJCxyKGVHc5i6koFeYvWVz0PII6t
Vnp6wl+Aua9SjRf0t7fomt8M6j/ZK7WPcwtXK1qQ1ZksoS8Msv9HbKjKNitz4kX8
7TjQf2KEJrHdegOS97mV5lqenlwB9fFiSd9KG9NWSHCtWehxJRnGtwWcidGDvQpF
kv2bKViRoUIhae+UAs6DLUhXrZuSJzDyrddYU2cvZO3vEw05XmS94AEXHRjkx7Se
LRHoRP43AVxa4BM3u87ouIYiC7zYjEhATP5rMCgsbqfsqZaDPZFpO5azGR3U9ugX
YSyz145ZQ9Mzx4+IfBQN3lD40hIvAZmxSgG8ZlbCgiMmJSylFN4nxi27N+PmPoMu
nD0O2j6tN6OI3bSiJ/vhOacyaMxRaqY92bfdRofogq+20JCu9v8unf7chHQvdb3W
RJD9KeKxDN6Za8ncIWeqzBkLLPgGLUhTOo2yQXCz+2IJJC5yeGg46FSa1QARAQAB
tBtTw7ZyZW4gPFNvZXJlbkBTb2VycmVhbC5kZT6JAj8EEwEIACkFAlXXNOUCGyMF
CQlmAYAHCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRD/XXfZjr3vlWcaEACK
7aa4TbOkRHfO3MZKSJODYpuL4GPqBKPM5j02TVYFlgZkOd0OyAyo8WocJymJoMC2
7nijTY3daY6AcAV1+rzNMEaudWic5oejoeKzZlBUeq89PS7+tOsIChFeSdkDW+ax
aMiLP6at0mXbEVBWOvbQ6QB7udLr6D2H/fH2IaXPIEugjM77zUxk3Y+xcYClRBFz
G7o2eROJHkRUbG++UoAt0dYq//KeSwiyuiULm9RTy/9xqC55rWoEB2c7ba/+I0/m
5t22tGn/1uDe6TmdtJeIVSKRgmurFYdz3qSGLpzClLt0uVelAM+A1CBOsaJ00jwk
+XHtnRHiPSRxiK5XC8J1ddSOfFA55CQqtdIb/iQj2wCwvOEWXc2UOLswKmk5n9Wb
FP8aLn3DmediN4ycOHjUVLYLe6DLoUjz9SE4eqa979eregIBJ8nEfOrEfhr7HOTO
mSUASPCYkofDqg+b/7slNVZlv8wd+182slk5xcTR3tCjYNpmcw8B+mket+pLhBfr
TLlq1BYWxc1fXN+yzU3O1KZeKEzAHnl8mYe6ExyU8qQ2q/3fldpYcxN+NdwqUz/k
eMk+6KJD7O0SIYdBw7ZfurRQmuaT9agL7iwPs3og08bk2tfhYYc2qiiAFuZjcmCH
dG/SB+l+1qGLvJQCYYm5w/F11LakDHE8n9iK1GAjMLkCDQRV1zTlARAAyJChfz6F
KX9gfIko3icpTOkQf8dJCR1xFlap1RXRBuZew73Iyl+9om2mZ5ihSUspCklBIArH
jMyZplLHJ370nvsOzttaoPTurcS/A0zDnILl4T1LGkwOqdCSt17cesqlVVQJzSKR
HEphYE9jw8wBV9vWRiS6mYLcxfrQzDfjYwZ5sfcAjwk6jgqGgWQSjJNN4XnCcEH1
ms2oqVja8iwOnfPdifMPPxMjBK+mV90JQXFCagE6/gwiMEL61LU7hrN0E+LVZ2xV
RrvxpI8WufQUm1ahw5FtREJSBYlYBC0/YS1P2fzlLIPSqZ/nsLUFOG7nxy7N2YN0
7JD9RsEee6g9iZTr1rGRvwZz+SH7A2YSbAcK8pXUNQP04t9Vjvil053MLUMV8jce
X0wGStSzwYYaJaKo9TjMXmYRciRlmGNY1ZPWTezdrRZb6xpTQHVjIrkx6Mkj/tVB
p10anxjgy2MKZvUvKL9/TKESgCR6spy8exEcTnn/CLtUcSMcj8Vq90L/aQMcDCRN
O51KbPU+MBojhj6+oVPkzMyUDdHpnNBUDLL/pEfdSQuwAzrsSjinFq1Z1zz6od01
VgP3ITRiDJz0tSPQY1YO7gClI57/vEAW6BC74IF3FzUthomk89gu2e5PyG7cN7tF
+WprCpM0jroBNJW1daOf0C/3eM1RQrUKmTcAEQEAAYkCJQQYAQgADwUCVdc05QIb
DAUJCWYBgAAKCRD/XXfZjr3vlVtwD/4k2LnOZRe/PdNRpm/fX4R0ldBKDil0BAn7
p10/Axd/SQCzVw65Cc7NBHk5xzBscukrfHdm9pcsJfTTj1v12V8VRZXblQP1km9r
M+pYPseo6UeM+PPuFkd352BI+f4B5cB16WyYcJon/2/UImhOTGK23Ed4QsWKOV6a
OAoYnOA4ZOIK2VTgkYrxmuJI84yBkhDwHia2akhO8pfnukScNB0HDY6OBbPXNkQe
DxTAdFuPd9mAz+tQYaWqiO0kw8WFt5MeMhzVk95Zc+hFz6rzL6gkWtA1RRfYexhi
2upIqkYlPm1VJrnP1/nbka4bs/T+tN9HbgDqLKJEtZMzGlBPu3thwOf3r/845lay
oAZHWG5f2bNayWjL+dvMmzSAF3E80TPA0k1ASeMfibwIbVZDPhJ8cpB/C946vhis
tVhQfb4rNatrqKj7RactmZYcXjZwrnFgYKyG135yHJWAHopo/na1VFF36hRBfUdq
QiIA9Eli07cuObhDIEolHMKTjg0CCiQx6snfq1XPc/bSZZj9Swc8wNrWe4Fmk1yT
iC37pLFEs3Hx1n8Yp+rfol6EfEugHo2H1CJhDuIWUZJ1FFCoJZTii5O2WB9TvZUf
jh0O0c69TDnDxik+Mqje+9GHXN8BdIA4e8LwH1a6tmTuKTvLLiDft5lqKEswIhGX
dlC95JCLQg==
=g9g4
-----END PGP PUBLIC KEY BLOCK-----

**Comment by gorhill** [comment]
> If I left the browser open (after counting some blocked actions) for about 5 minutes, the counts were saved and correct shown after a restart

Ok... My understanding was that the counts were _never_ saved. There is a delay before uBlock Origin saved the counts, which is currently set at 4 minutes. This is to avoid writing to often to the DB -- the counts are not critical data.

**Comment by Laserfischen** [comment]
I mentioned that in an eralier post, too. Additionally I added there,
that there is "a critical mass" at around 350 blocked actions... from
which the counts where saved, too... even if I was under 5 minutes delay
to collect them.

Nevertheless, why wasn't it in the week before like this? I remembered
that there was no delay... or am I wrong?



Am 08.10.2015 um 22:49 schrieb Raymond Hill:
>> If I left the browser open (after counting some blocked actions) for about 5 minutes, the counts were saved and correct shown after a restart
> 
> Ok... My understanding was that the counts were _never_ saved. There is a delay before uBlock Origin saved the counts, which is currently set at 4 minutes. This is to avoid writing to often to the DB -- the counts are not critical data.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gorhill/uBlock/issues/793#issuecomment-146681132
> 

-- 








-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFXXNOUBEACvAd4mw6jl3o7wsgblDRclU9QVEHCDSvh6PO3yzTRjjaUhI/bC
UAgliOcPkW1DfFFzxN6ccB+lfrFTkUVpVM124PWdbFOA7smYtNUXLobTSW6LqAlc
OSX8w+B6ACqSrNl+jvxdOcUn02rFDaDawCvrpDBxLymekIrejg4UWlkKtq0JeFkd
dVDKI7pGegbey07ponwYVKKi9qFpQ2l86PjsYJCxyKGVHc5i6koFeYvWVz0PII6t
Vnp6wl+Aua9SjRf0t7fomt8M6j/ZK7WPcwtXK1qQ1ZksoS8Msv9HbKjKNitz4kX8
7TjQf2KEJrHdegOS97mV5lqenlwB9fFiSd9KG9NWSHCtWehxJRnGtwWcidGDvQpF
kv2bKViRoUIhae+UAs6DLUhXrZuSJzDyrddYU2cvZO3vEw05XmS94AEXHRjkx7Se
LRHoRP43AVxa4BM3u87ouIYiC7zYjEhATP5rMCgsbqfsqZaDPZFpO5azGR3U9ugX
YSyz145ZQ9Mzx4+IfBQN3lD40hIvAZmxSgG8ZlbCgiMmJSylFN4nxi27N+PmPoMu
nD0O2j6tN6OI3bSiJ/vhOacyaMxRaqY92bfdRofogq+20JCu9v8unf7chHQvdb3W
RJD9KeKxDN6Za8ncIWeqzBkLLPgGLUhTOo2yQXCz+2IJJC5yeGg46FSa1QARAQAB
tBtTw7ZyZW4gPFNvZXJlbkBTb2VycmVhbC5kZT6JAj8EEwEIACkFAlXXNOUCGyMF
CQlmAYAHCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRD/XXfZjr3vlWcaEACK
7aa4TbOkRHfO3MZKSJODYpuL4GPqBKPM5j02TVYFlgZkOd0OyAyo8WocJymJoMC2
7nijTY3daY6AcAV1+rzNMEaudWic5oejoeKzZlBUeq89PS7+tOsIChFeSdkDW+ax
aMiLP6at0mXbEVBWOvbQ6QB7udLr6D2H/fH2IaXPIEugjM77zUxk3Y+xcYClRBFz
G7o2eROJHkRUbG++UoAt0dYq//KeSwiyuiULm9RTy/9xqC55rWoEB2c7ba/+I0/m
5t22tGn/1uDe6TmdtJeIVSKRgmurFYdz3qSGLpzClLt0uVelAM+A1CBOsaJ00jwk
+XHtnRHiPSRxiK5XC8J1ddSOfFA55CQqtdIb/iQj2wCwvOEWXc2UOLswKmk5n9Wb
FP8aLn3DmediN4ycOHjUVLYLe6DLoUjz9SE4eqa979eregIBJ8nEfOrEfhr7HOTO
mSUASPCYkofDqg+b/7slNVZlv8wd+182slk5xcTR3tCjYNpmcw8B+mket+pLhBfr
TLlq1BYWxc1fXN+yzU3O1KZeKEzAHnl8mYe6ExyU8qQ2q/3fldpYcxN+NdwqUz/k
eMk+6KJD7O0SIYdBw7ZfurRQmuaT9agL7iwPs3og08bk2tfhYYc2qiiAFuZjcmCH
dG/SB+l+1qGLvJQCYYm5w/F11LakDHE8n9iK1GAjMLkCDQRV1zTlARAAyJChfz6F
KX9gfIko3icpTOkQf8dJCR1xFlap1RXRBuZew73Iyl+9om2mZ5ihSUspCklBIArH
jMyZplLHJ370nvsOzttaoPTurcS/A0zDnILl4T1LGkwOqdCSt17cesqlVVQJzSKR
HEphYE9jw8wBV9vWRiS6mYLcxfrQzDfjYwZ5sfcAjwk6jgqGgWQSjJNN4XnCcEH1
ms2oqVja8iwOnfPdifMPPxMjBK+mV90JQXFCagE6/gwiMEL61LU7hrN0E+LVZ2xV
RrvxpI8WufQUm1ahw5FtREJSBYlYBC0/YS1P2fzlLIPSqZ/nsLUFOG7nxy7N2YN0
7JD9RsEee6g9iZTr1rGRvwZz+SH7A2YSbAcK8pXUNQP04t9Vjvil053MLUMV8jce
X0wGStSzwYYaJaKo9TjMXmYRciRlmGNY1ZPWTezdrRZb6xpTQHVjIrkx6Mkj/tVB
p10anxjgy2MKZvUvKL9/TKESgCR6spy8exEcTnn/CLtUcSMcj8Vq90L/aQMcDCRN
O51KbPU+MBojhj6+oVPkzMyUDdHpnNBUDLL/pEfdSQuwAzrsSjinFq1Z1zz6od01
VgP3ITRiDJz0tSPQY1YO7gClI57/vEAW6BC74IF3FzUthomk89gu2e5PyG7cN7tF
+WprCpM0jroBNJW1daOf0C/3eM1RQrUKmTcAEQEAAYkCJQQYAQgADwUCVdc05QIb
DAUJCWYBgAAKCRD/XXfZjr3vlVtwD/4k2LnOZRe/PdNRpm/fX4R0ldBKDil0BAn7
p10/Axd/SQCzVw65Cc7NBHk5xzBscukrfHdm9pcsJfTTj1v12V8VRZXblQP1km9r
M+pYPseo6UeM+PPuFkd352BI+f4B5cB16WyYcJon/2/UImhOTGK23Ed4QsWKOV6a
OAoYnOA4ZOIK2VTgkYrxmuJI84yBkhDwHia2akhO8pfnukScNB0HDY6OBbPXNkQe
DxTAdFuPd9mAz+tQYaWqiO0kw8WFt5MeMhzVk95Zc+hFz6rzL6gkWtA1RRfYexhi
2upIqkYlPm1VJrnP1/nbka4bs/T+tN9HbgDqLKJEtZMzGlBPu3thwOf3r/845lay
oAZHWG5f2bNayWjL+dvMmzSAF3E80TPA0k1ASeMfibwIbVZDPhJ8cpB/C946vhis
tVhQfb4rNatrqKj7RactmZYcXjZwrnFgYKyG135yHJWAHopo/na1VFF36hRBfUdq
QiIA9Eli07cuObhDIEolHMKTjg0CCiQx6snfq1XPc/bSZZj9Swc8wNrWe4Fmk1yT
iC37pLFEs3Hx1n8Yp+rfol6EfEugHo2H1CJhDuIWUZJ1FFCoJZTii5O2WB9TvZUf
jh0O0c69TDnDxik+Mqje+9GHXN8BdIA4e8LwH1a6tmTuKTvLLiDft5lqKEswIhGX
dlC95JCLQg==
=g9g4
-----END PGP PUBLIC KEY BLOCK-----

**Comment by gorhill** [comment]
> with that option available before

Resetting the counter was never available before. One "easy" way is to backup settings, disable uBO, delete uBO's SQlite file, restart uBO, then restore the backup. Another way would be to modify the proper value directly in the SQlite using appropriate app.
