### ISSUE TITLE
Inline script tag filtering - Concrete examples of usefulness

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#795]
Pornhub.com have Global Alexa Rank 65 at this writing.

Can you please add how to block the popunder for pornhub.com in https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#concrete-examples-of-usefulness ?

What do you think about adding https://adblockplus.org/forum/viewtopic.php?t=27067 as reference to the text: "http://dayt.se/forum/activity.php: dayt.se##script:contains(adBlockDetected) (see "Blocking FuckAdblock")" in https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#concrete-examples-of-usefulness ?

**Comment by gorhill** [comment]
> Can you please add how to block the popunder for pornhub.com in https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#concrete-examples-of-usefulness ?

Interesting challenge, will see what can be done -- **if** something can be done with the new filter. Can you give me a specific URL on that site for which the issue occur for sure, I don't feel like hunting for a test case -- I just need one URL.

**Comment by flyingzebras** [comment]
@gorhill Just click on any video on pornhub.com to trigger a popunder. In fact, this mechanism is how _all_ popunder in the whole Pornhub NETWORK works!

**Comment by gorhill** [comment]
Does this work?

    www.pornhub.com##script:contains(FastPopSessionRequestNumber)

**Comment by flyingzebras** [comment]
@gorhill Amazing! Congratulations to be the first developer to ever have blocked inline scripting AFAIK!

Can you please add that line to any uBlock filter and confirm?

**Comment by gorhill** [comment]
Ok, added `pornhub.com##script:contains(FastPopSessionRequestNumber)` (leading double pipes are not a valid cosmetic filter syntax).

Even with this new filter, just a reminder this it is still a cat and mouse game between sites/blockers.

**Comment by flyingzebras** [comment]
@gorhill 

Also, can you please write about this in
* https://forums.lanik.us/viewtopic.php?f=62&t=22848
* https://issues.adblockplus.org/ticket/2095#comment:16
* Related GitHub issue pages.

**Comment by flyingzebras** [comment]
@gorhill Thank you.

Where did you add `pornhub.com##script:contains(FastPopSessionRequestNumber)`

**Comment by gorhill** [comment]
> can you please write about this in

Not sure I want to "advertise" this on EasyList forum, I wouldn't be surprised in the site's owners have people monitoring the latest solutions in there around their pop-under "feature".

**Comment by gorhill** [comment]
> Where did you add ...

It's in <https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt>.

**Comment by flyingzebras** [comment]
@gorhill Thank you.

Is it ok if I give you code to block popunders for the rest of the Pornhub NETWORK in https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt.?

**Comment by gorhill** [comment]
> Is it ok if I give you code to block popunders for the rest of the Pornhub NETWORK

If you can confirm it works for all of them -- that will save me having to check.

**Comment by flyingzebras** [comment]
@gorhill Ok, I'll see what I can do.

I recommend that you move `pornhub.com##script:contains(FastPopSessionRequestNumber)` to https://github.com/gorhill/uBlock/blob/master/assets/ublock/badware.txt per https://en.wikipedia.org/wiki/MindGeek#Malvertising. What do you think about it?

**Comment by flyingzebras** [comment]
@gorhill This will block popunders in the whole Pornhub NETWORK:

`extremetube.com|gaytube.com|mofosex.com|pornhub.com|redtube.com|spankwire.com|thumbzilla.com|tube8.com|tube8.es|tube8.fr|xtube.com|youporn.com|youporngay.com##script:contains(FastPopSessionRequestNumber)`

Can you please add it to https://github.com/gorhill/uBlock/blob/master/assets/ublock/badware.txt and confirm?

**Comment by gorhill** [comment]
Added suggested filter. FYI, I had to edit your suggested filter:

- `|` is not a proper domain separator for cosmetic filter, `,` is what needs to be used.
- I used a single _entity_ specifier `tube8.*` in place of `tube8.com`, `tube8.es`, and `tube8.fr`.

**Comment by flyingzebras** [comment]
`extremetube.com##script:contains(FastPopSessionRequestNumber),gaytube.com##script:contains(FastPopSessionRequestNumber),mofosex.com##script:contains(FastPopSessionRequestNumber),pornhub.com##script:contains(FastPopSessionRequestNumber),redtube.com##script:contains(FastPopSessionRequestNumber),spankwire.com##script:contains(FastPopSessionRequestNumber),thumbzilla.com##script:contains(FastPopSessionRequestNumber),tube8.*##script:contains(FastPopSessionRequestNumber),xtube.com##script:contains(FastPopSessionRequestNumber),youporn.com##script:contains(FastPopSessionRequestNumber),youporngay.com##script:contains(FastPopSessionRequestNumber)`

**Comment by flyingzebras** [comment]
@gorhill Peter Lowe ignored adding these to his List:

 All these domains are used to dislpay ads on the Pornhub NETWORK:

    ||addthis.com^$third-party
    ||are-ter.com^$third-party
    ||bannerflow.com^$third-party
    ||contentabc.com.com^$third-party
    ||doublepimp.com^$third-party
    ||dvdcdn.com^$third-party
    ||e-n-t-e-r-n-e-x.com.com^$third-party
    ||ebocornac.com^$third-party
    ||etahub.com^$third-party

**Comment by gorhill** [comment]
I see most of them in Peter Lowe's list. To be clear, I do not intend to become a filter list maintainer -- whatever I put in uBlock's filter lists is completely at my own discretion, I do not intend to take requests to add stuff in these lists, these requests should be directed to known filter list maintainers.

**Comment by flyingzebras** [comment]
@gorhill Ok.

**Comment by flyingzebras** [comment]
@gorhill Perhaps you want to add 
`extremetube.com,gaytube.com,mofosex.com,pornhub.com,redtube.com,spankwire.com,thumbzilla.com,tube8.*,xtube.com,youporn.com,youporngay.com##script:contains(FastPopSessionRequestNumber)` to https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#concrete-examples-of-usefulness

**Comment by flyingzebras** [comment]
@gorhill Do not forget to add keezmovies.com as I just did, it was the final Pornhub NETWORK domain.

**Comment by flyingzebras** [comment]
@gorhill Can you please mention the inline script tag filtering feature in README.md and https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ?

**Comment by flyingzebras** [comment]
@gorhill Why didn't you move the block to https://github.com/gorhill/uBlock/blob/master/assets/ublock/badware.txt as I suggested per https://en.wikipedia.org/wiki/MindGeek#Malvertising?

**Comment by gorhill** [comment]
> why didn't you move

Because this filter is to prevent spurious popunders, not warn of risk of badware ahead.

**Comment by flyingzebras** [comment]
@gorhill Thanks.

**Comment by flyingzebras** [comment]
@gorhill Putting `extremetube.com,gaytube.com,keezmovies.com,mofosex.com,pornhub.com,redtube.com,spankwire.com,thumbzilla.com,tube8.*,xtube.com,youporn.com,youporngay.com##script:contains(FastPopSessionRequestNumber)` to https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#concrete-examples-of-usefulness make sense as it includes multiple domains with very high Alexa ranks. Will you add it?

**Comment by Hrxn** [comment]
Short question:
This list https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt 
is always active, with default settings, isn't it?

Because this could be a bit misleading, as I just read these [Examples](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#concrete-examples-of-usefulness).
> Try without, then with the respective inline script tag filter:

I guess this won't work then for users with current Firefox and uBlock0 versions.

I also noticed that these filters don't work in Chrome/Chromium, but this is correct, according to the same page [(caveats)](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#caveats).
I didn't notice that first, maybe don't put it at the end of the page, so this doesn't get overlooked

**Comment by gorhill** [comment]
Good points, I fixed the doc.

**Comment by flyingzebras** [comment]
@gorhill I guess it would be good to state in https://github.com/gorhill/uBlock/wiki/Badware-risks that "*.exe" files are the most common practice to spread malware files. What do you think?

**Comment by Hrxn** [comment]
That is true, I guess.

But, in my humble opinion, that is fundamental common sense of using the Internet. The Badware warning is to remind users to be cautious, it's not an exhaustive guide of using the Web safely.

uBlock0 is not Internet Basics 101, so this is out of scope for this project.
As I said, just my humble opinion on the matter.

**Comment by flyingzebras** [comment]
@gorhill pornhub.com popunders have been resurrected, despite that pornhub pages still use FastPopSessionRequestNumber. Can you fix this with some parameters in ```extremetube.com,gaytube.com,keezmovies.com,mofosex.com,pornhub.com,redtube.com,spankwire.com,thumbzilla.com,tube8.*,xtube.com,youporn.com,youporngay.com##script:contains(FastPopSessionRequestNumber)```

**Comment by gorhill** [comment]
I can't reproduce, works from here. Anything out of the ordinary with your environment?

**Comment by flyingzebras** [comment]
@gorhill Yes, I upgraded from IceCat 31 to IceCat 38. Nothing more than that.

**Comment by flyingzebras** [comment]
@gorhill However, the popunders are catched by ```"uBlock Origin has prevented the following page from loading:



Because of the following filter

||ebocornac.com^
Found in: Peter Lowe’s Ad server list 
"```

**Comment by gorhill** [comment]
> IceCat 38

What is the result of [this test](http://www.w3c-test.org/html/semantics/scripting-1/the-script-element/script-before-after-events.html) for IceCat 38?

**Comment by flyingzebras** [comment]
@gorhill 
```
Summary

Harness status: OK

Found 4 tests
4 Pass
```

**Comment by flyingzebras** [comment]
@gorhill I downloaded and installed Trisquel 7 from trisquel.info and installed icecat with: apt-get update && apt-get install icecat

Trisquel GNU/Linux can be used live from USB.

**Comment by flyingzebras** [comment]
@gorhill IceCat 38.3.0 is based on Firefox ESR. You can download and try the latest FF ESR here: https://ftp.mozilla.org/pub/firefox/releases/latest-esr/

**Comment by gorhill** [comment]
Ok I installed and investigated. The reason is simply that FF 38 API does not support [process message managers](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Message_Manager/Message_manager_overview#Process_message_managers), which is required in the current implementation of inline script tag filtering.

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/940

**Comment by flyingzebras** [comment]
@gorhill Should

```extremetube.com,gaytube.com,keezmovies.com,mofosex.com,pornhub.com,redtube.com,spankwire.com,thumbzilla.com,tube8.*,xtube.com,youporn.com,youporngay.com##script:contains(FastPopSessionRequestNumber)``` be merged to
```|http://$popunder,third-party,domain=xhamster.com```

like this:

```|http://$popunder,third-party,domain=xhamster.comextremetube.com,gaytube.com,keezmovies.com,mofosex.com,pornhub.com,redtube.com,spankwire.com,thumbzilla.com,tube8.*,xtube.com,youporn.com,youporngay.com```?

**Comment by gorhill** [comment]
I can't see any popunder anymore on these sites, I may have to remove the corresponding `script:contains` filter. If you can confirm there is no more popunder, I just checked three of them.

**Comment by flyingzebras** [comment]
@gorhill Thank you. I just checked all of them, they have removed ```FastPopSessionRequestNumber``` from all of the sites. Can you please remove ```extremetube.com,gaytube.com,keezmovies.com,mofosex.com,pornhub.com,redtube.com,spankwire.com,thumbzilla.com,tube8.*,xtube.com,youporn.com,youporngay.com##script:contains(FastPopSessionRequestNumber)``` from assets/ublock/filters.txt and confirm?

**Comment by flyingzebras** [comment]
@gorhill Can you please add ```redtube.com.br``` to https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt, a new redtube.com site for Brazil.
