### ISSUE TITLE
Strict blocking reference in wiki

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#796]
Can you please let me know the URL for strict blocking in the Wiki?

**Comment by 5t3f4n** [comment]
I don't believe there is much about this in the wiki since it's quite self-explanatory (I'm guessing) aside from [this page](https://github.com/gorhill/uBlock/wiki/Manually-editing-per-site-switches) which explains how you can disable it.

**Comment by publicarray** [comment]
is this what you are looking for? https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking

**Comment by gorhill** [comment]
URL posted by @publicarray is the one.

**Comment by berrythesoftwarecodeprogrammar** [comment]
surprised i havent seen that. my ublock dynamic filters shall now start off like this :) 

```
no-remote-fonts: * true
no-popups: * true
* * inline-script block
```
