### ISSUE TITLE
firefox: no info window when icon docked on statusline toolbar

### ISSUE THREAD

**Issue by jimdigriz** [gorhill/uBlock#797]
I use the Vimperator plugin for Firefox which provides a toolbar (the 'Liberator Statusline toolbar') at the bottom of the page where I can dock extension icons instead.   I, and most other Vimperator users, tend to have the whole address bar and those icons to the right hidden/turned off and not shown.

The problem is that when I click on the icon to get the info popup window when it is docked in the statusline toolbar, I see nothing, probably as it is being rendered off screen below my desktop?

The attached screenshot shows uBlock docked in its 'regular' place (next to the address bar that I have temporary enable for this bug report) and the info info window appearing as expected.  Where I normally put the icon is alongside the Privacy Badger icon you can see in the bottom right.

Make sense?  If you need more details do ask.
![screenshot](https://cloud.githubusercontent.com/assets/2567406/10346473/42dc2a0e-6d27-11e5-8eff-154d4c76f321.jpeg)

**Comment by publicarray** [comment]
> Where I normally put the icon is alongside the Privacy Badger icon you can see in the bottom right.

How do I accomplish this?

**Comment by jimdigriz** [comment]
Hi,

 1. Install the Vimperator and uBlock plugins
 2. from the view menu, go to toolbars and enable the 'Liberator Statusline toolbar'
 3. go again to the view menu, toolbars and go to customise
 4. in the customisation window that opens, click on 'Restore Defaults' just to give you a clean slate
 5. in the 'Show/Hide Toolbars', check the 'Liberator Statusline toolbar' is still enabled
 6. drag the uBlock icon into the statusbar in the bottom right
 7. click on exit customisations
 8. browse to some website with a pile of ads
 9. click on the uBlock icon to try to get an info window, you should see nothing appears (though the icon will show it has been depressed)

This what you are after, if not do ask.

Thanks

**Comment by publicarray** [comment]
Thanks. seems to work for me.
![screen shot 2015-10-08 at 11 07 48 pm](https://cloud.githubusercontent.com/assets/5497998/10367055/89b4fad8-6e11-11e5-84a2-0da4069c3a26.png)

However there is a graphical glitch when you minimise the dynamic filters/matrix:
![screen shot 2015-10-08 at 11 10 34 pm](https://cloud.githubusercontent.com/assets/5497998/10367099/cbea7234-6e11-11e5-994c-627e4537ec4f.png)

**Comment by publicarray** [comment]
@AlexVallat maybe you can chime in? (I assume you are still responsible for Firefox?)

**Comment by AlexVallat** [comment]
If you want the popup to work when the navigation bar is hidden, you need to set the `extensions.ublock0.forceLegacyToolbarButton` to `true`. See #610 and various other discussions on the subject.

**Comment by publicarray** [comment]
Of course. Thanks. Only one rhetorical question remains: Why does it work without the setting on Mac OS?

**Comment by AlexVallat** [comment]
I haven't got a Mac, so I can't check myself, but given the screenshots you posted I would say because you haven't hidden the navigation bar. If you do hide the nav bar, and the popup still works with the modern button, then that would be a curiosity.

**Comment by publicarray** [comment]
Yes, you are right I had to enable the legacy toolbar button for the popup window to show
![screen shot 2015-10-10 at 10 08 58 am](https://cloud.githubusercontent.com/assets/5497998/10408043/bc3a05bc-6f37-11e5-8503-5cbfdda1d443.png)

**Comment by publicarray** [comment]
@jimdigriz does [AlexVallet's solution](#issuecomment-146551533) to turn `extensions.ublock0.forceLegacyToolbarButton` to `true` fix your issue?

1.  in the navbar (Awesome Bar) enter `about:config`
2.  click on the `I'll be careful, I promise!` button
3.  search for `ublock0`
4.  double click on `extensions.ublock0.forceLegacyToolbarButton` so that the value = `true`
5.  restart Firefox

**Comment by jimdigriz** [comment]
Works For Me(tm)

Thanks

**Comment by publicarray** [comment]
@jimdigriz can you close the issue then?

**Comment by jimdigriz** [comment]
Surely something should be added to the codebase to (if possible) detect this and automatically apply the workaround to stop the next person opening a bug report?  At the least a documentation note describing this workaround?

**Comment by publicarray** [comment]
>  At the least a documentation note describing this workaround?

To prevent future issues like this I would add something like the following to the [Troubleshooting wiki page](https://github.com/gorhill/uBlock/wiki/Troubleshooting).

@gorhill How do you like this suggestion?

### The uBlock's popup UI is not displaying when using Firefox

You can fix this by following the following steps:
1.  In the navigation bar (Awesome Bar) enter `about:config`
2.  Click on the `I'll be careful, I promise!` button
3.  Search for `ublock0`
4.  Double click on `extensions.ublock0.forceLegacyToolbarButton` so that the value = `true`
5.  Restart Firefox

***
```
### The uBlock's popup UI is not displaying when using Firefox

You can fix this by following the following steps:
1.  In the navigation bar (Awesome Bar) enter `about:config`
2.  Click on the `I'll be careful, I promise!` button
3.  Search for `ublock0`
4.  Double click on `extensions.ublock0.forceLegacyToolbarButton` so that the value = `true`
5.  Restart Firefox

***
```

**Comment by gorhill** [comment]
@publicarray Thanks, added to the troubleshooting guide.

**Comment by jimdigriz** [comment]
Thanks folks
