### ISSUE TITLE
Blocking URLs from other applications

### ISSUE THREAD

**Issue by TheTopMostDog** [gorhill/uBlock#799]
Intermittently having issues opening URLs sent via IM programs such as Trillian, Steam, Skype. Toggling uBlock off and then back on seems to fix it. Exact cause unidentified, will update if I narrow it down.

**Comment by publicarray** [comment]
Huh? uBlock is a browser plugin, uBlock can't interact with anything outside the browser.

**Comment by TheTopMostDog** [comment]
Of course. I imagine it's somehow preventing the page from opening after Firefox receives the request from whichever third party application I'm attempting to open the URL from. It is definitely related to this extension somehow, as disabling it immediately rectifies the 'block' and allows the next click to open a new tab as normal.

I have been unable to reproduce it intentionally; it seems to be occurring randomly. Is there anything I can do on my end to locate the cause while it is happening? I'm not familiar with extensions in the slightest.

**Comment by publicarray** [comment]
The extension uses JavaScript so you can have a look in the browser console if there are any errors. In Firefox you can open it from Tools -> Web Developer -> Web Console. Also can you tell me the operating system that you are running?

**Comment by TheTopMostDog** [comment]
I'll have a look next time it acts up.
I'm running Windows 7, x64.

**Comment by publicarray** [comment]
Thanks. I am on a Mac and so far I have been unsuccessful in reproducing. It would help if someone else using Windows can test this. Indeed it's a strange problem.

**Comment by TheTopMostDog** [comment]
I managed to get it to happen twice more by toggling it off and on and switching between tabs which had it enabled or disabled. I still don't know which specific combination of actions replicate it, as it stopped recurring after that. I'm fairly sure that toggling it once more or changing to a new tab is enough to allow the next attempt through.

I'll see if I can narrow it down with use over time, though if no one else is having this issue then perhaps it's a conflict on my end. I'll update if I find anything of use.

**Comment by Betsy25** [comment]
@TheTopMostDog Can you close the issue please ?
