### ISSUE TITLE
Suggestion - Allow syncing through firefox sync.

### ISSUE THREAD

**Issue by rascal-hats** [gorhill/uBlock#80]
After even a modest day of using uBlock I find that I have added over a dozen custom blocks to the preference list. It would be great if these were synced across my devices so I don't have to re-add them every time I find something I want to block.

Thanks for a fantastic add-on.

https://wiki.mozilla.org/Services/Sync/Addon_Sync#Are_Add-on_Settings_Synchronized.3F

**Comment by lewisje** [comment]
He has considered it, and ideally he would do it in a cross-platform way: https://github.com/chrisaljoudi/uBlock/issues/126

Also, you're better off asking for feature requests like this in the version that chrisaljoudi now owns.

**Comment by gorhill** [comment]
Mind <https://bugzilla.mozilla.org/show_bug.cgi?id=753289>.

**Comment by gorhill** [comment]
For translators:

![a](https://cloud.githubusercontent.com/assets/585534/9213128/5f29f5f2-405d-11e5-92a9-b2d9e8db3d42.png)

- Left-hand button is to export to cloud, there is a tooltip for this button to translate
- Right-hand button is to import from cloud, there is a tooltip for this button to translate
- The string to translate related to device name is found bu clicking the cog wheel at the top-right of the cloud widget area.

**Comment by lychichem** [comment]
Bug report: If the  sync device name uses none-ASCII characters, the sync setting will show messy code
![2015-08-18 13 52 46](https://cloud.githubusercontent.com/assets/9316590/9323232/ea97096a-45b0-11e5-8108-3b617c9f7df1.png)

**Comment by gorhill** [comment]
That string is extracted from `services.sync.client.name` in `about:config`, which is the sting appearing in the user-editable input field, _Device name_, in the _Sync_ settings pane of Firefox. What is the string appearing there in your case?

**Comment by lychichem** [comment]
@gorhill Okay, The string in about:config is "用户LeiChi运行于LeiChi-PC的Nightly", you can see that messy characters are all Chinese characters which are not ASCII characters.
