### ISSUE TITLE
How to allow any IP rule in dynamic filtering?

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#802]
I visiting some sites, where are videos which requires to set the IP rule (ex. 188.240.220.150 on site [vidto.me](vidto.me)) to `noop` or `allow`. For now, the best option, when having set to `block` the 3rd-party rule in global, is to set `noop` 3rd-party rule in local. I've tried to allow any IP rules (not specific one) in dynamic filtering on global, but uBlock Origin can't accept that. Can you do something with that, @gorhill?

**Comment by publicarray** [comment]
From: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

>Always include a URL, even if "it happens everywhere".

Test URL: http://vidto.me/9vgfnm4afboh.html

Now to the issue:

>  I've tried to allow any IP rules in dynamic filtering on global, but uBlock Origin can't accept that. 

I tried
```
* * 3p block
* 188.240.220.150 * noop
```
And the video plays back fine. As an alternative I would use:
```
* * 3p-frame block
* * 3p-script block
vidto.me fonts.googleapis.com * block
vidto.me longtailvideo.com * block
```
This is because the IP address might change from video to video.

**Comment by Piter432** [comment]
@publicarray: I forgot to add that I want to allow **any** IP rule on global, not **the specifice one** like the one you provided :P

**Comment by publicarray** [comment]
So are you asking if you can block, noop or allow all ip addresses. I think that it is a bad idea in terms of security. But anyway.

@gorhill are regular expression filters supported? I have tried `@@||/(?:\d{1,3}\.){3}\d{1,3}/` with no success.

**Comment by gorhill** [comment]
> I forgot to add that I want to allow any IP rule on global

Please write down an example of rule you say you would like.

**Comment by gorhill** [comment]
> are regular expression filters supported

Dynamic filtering rules do not support regexp, that would be inefficient and impossible to have a matrix-like UI. Pattern-based filtering applies only for static filtering.

**Comment by publicarray** [comment]
Sorry I meant rules.
From ABP syntax:
 > For example the filter /banner\d+/ will match banner123 and banner321 but not banners.

**Comment by publicarray** [comment]
@gorhill Never mind. what I was trying to do would not work because the static filter would get overwritten by the dynamic filters anyway.

@Piter432 It's not currently possible to so what you ask but an alternative solution is to block on per site bases like I did above. This is probably the closest you can get unless you develop static filters and don't use dynamic filtering.

**Comment by gorhill** [comment]
@Piter432 Please provide an example of a rule you are asking for.

**Comment by gorhill** [comment]
Mark as invalid until requested feedback is provided.

**Comment by Piter432** [comment]
@publicarray: <blockquote>So are you asking if you can block, noop or allow all ip addresses. I think that it is a bad idea in terms of security. Just my opinion anyway.</blockquote>I don't worry about my security, because I have a powerfull anti-virus software and I have many filters lists and at least one extension, which will protect me against sites with malware or virus ;)
___

@gorhill: <blockquote>Please write down an example of rule you say you would like.</blockquote>I'm not sure if I understand correctly, because English isn't my native language, but I'll write it to you:
`* * *.*.*.* allow`

**Comment by gorhill** [comment]
`*.*.*.*` would be pattern-matching -- incompatible with dynamic filtering: there is no pattern-matching in dynamic filtering, only plain string comparisons, for efficiency purpose, **and** for the ability to translate properly the rules into a point-and-click matrix.

**Comment by Piter432** [comment]
Hmm, so maybe something like `* * ip-address allow`?

**Comment by gorhill** [comment]
Way too broad, with no obvious purpose for most end users. You are likely the only one to somehow find this useful.

**Comment by gorhill** [comment]
When I try `http://vidto.me/`, there were network requests to `188.240.220.150` and these were not blocked on my side: I block 3rd-party scripts/frames. I don't see the point of inventing circumambulated solutions to what can already be handled just fine.

**Comment by Piter432** [comment]
@gorhill: <blockquote>[...] here were network requests to 188.240.220.150 and these were not blocked on my side: I block 3rd-party scripts/frames.</blockquote>I have also blocked normal 3rd-party in global, not only 3rd-party scripts and 3rd-party frames ;)

**Comment by gorhill** [comment]
> I have also blocked normal 3rd-party in global

I understand, but what is the issue of blocking only 3rd-party scripts/frames for specific site when you are ready to unblock literal IP addresses indiscriminately?

**Comment by seanrand** [comment]
Another case in point: beeg.com (NSFW) requires these and more with 3p-block:

```
* * 3p block
* * 3p-frame block
* * 3p-script block
beeg.com cloudflare.com * noop
beeg.com staticloads.com * noop
beeg.com 209.8.96.131 * noop
beeg.com 209.8.96.135 * noop
beeg.com 209.8.96.137 * noop
beeg.com 209.8.96.143 * noop
beeg.com 209.8.96.145 * noop
beeg.com 209.8.96.69 * noop
beeg.com 209.8.96.73 * noop
beeg.com 209.8.96.75 * noop
beeg.com 209.8.96.77 * noop
beeg.com 209.8.96.79 * noop
beeg.com 209.8.96.81 * noop
beeg.com 209.8.96.85 * noop
```

http://bgp.he.net/net/209.8.96.0/21

Would allowing subnets in the syntax be an option?
```
beeg.com 209.8.96.0/21 * noop
```

But yeah... nooping 3p is also a solution.

**Comment by Piter432** [comment]
@gorhill: In total, none. For me at least :P

**Comment by gorhill** [comment]
> Another case in point:

The proper solution here is to implement in uBlock what I fixed recently in uMatrix: <https://github.com/gorhill/uMatrix/issues/122>. So the following rule for your specific example would work:

    beeg.com 209.8.96 * noop

**Comment by publicarray** [comment]
>  But yeah... nooping 3p is also a solution.

Yes, I always prefer to do it that way.
```
* * 3p block
beeg.com * 3p noop
beeg.com addthis.com * block
beeg.com fonts.googleapis.com * block
beeg.com google-analytics.com * block
```
