### ISSUE TITLE
Is "ads tolerance" removed like in adblock edge ?

### ISSUE THREAD

**Issue by delicacy1** [gorhill/uBlock#804]
Does it already work like adblock edge ? if not, it would be great to make it work 
the same for a specific particularity:

"adblock edge" doesnt have an "ads tolerance" so the control is honest.

**Comment by zummuz** [comment]
Reason: Discontinued in favor of Ublock Origin, a general purpose blocker, that not only outperforms Adblock Edge but is also available on other browsers and, of course, without "Acceptable Ads Whitelist". (from https://addons.mozilla.org/ru/firefox/addon/adblock-edge/)

**Comment by gorhill** [comment]
Reported issue makes no sense.

**Comment by lewisje** [comment]
uBlock and uBlock Origin have worked that way from the beginning; among ad-blocking extensions, *only* Adblock Plus includes the Acceptable Ads whitelist.

(BTW, among iOS 9+ content-blockers, several actually do use the Acceptable Ads whitelist; I know ABP for iOS lets you turn that off, but I don't know whether the others do, and ABP for iOS is so far the best of breed in that space.)
