### ISSUE TITLE
Buttons don't respond on strict blocking warning pages.

### ISSUE THREAD

**Issue by rumorumo** [gorhill/uBlock#806]
I'm using Chrome 31.0.1650.63 (a bit old, I know, but...). Since uBlock 1.1.0.0 the buttons on strict blocking warning pages have stopped responding to mouse and keyboard (links still work). The only way of accessing blocked sites is whitelisting them manually on the dashboard...

Thank you for all the great work in uBlock!

**Comment by lewisje** [comment]
IIRC there's no platform where Chrome 31 works but Chrome 45 doesn't, so I don't know why you're still using Chrome 31; I do know that Chrome dropped support for OS X Leopard after 21, and for Debian 6 after 27, but I haven't seen any drop in platform support after 31.

I guess rare cases like yours would lead to the desire to be able to download an older version of a Chrome extension from the store, and to keep extensions from updating to known-incompatible versions.

**Comment by gorhill** [comment]
I suppose there are error message in the dev console of the "strict blocking" page? (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd>)

**Comment by rumorumo** [comment]
Maybe this: "Uncaught TypeError: Cannot read property 'length' of undefined"?

**Comment by gorhill** [comment]
Line 201?

**Comment by gorhill** [comment]
You have a line number with the error message?

**Comment by lewisje** [comment]
I guess more defensive coding is in order: `if (!url || !url.search || !url.search.length) {` (or other idioms as appropriate).

**Comment by rumorumo** [comment]
Sorry, I was caught yesterday as non-human by a GitHub robot and my profile was blocked in the middle of the conversation... Now I'm back. Is there anything more I can help about this issue?

**Comment by gorhill** [comment]
> more defensive coding is in order

Except that this doesn't explain why the error occurs. `url` should be `null` or an instance of `URL` -- which object [has a `search` property](https://developer.mozilla.org/en-US/docs/Web/API/URL). According to the reported error, `url` is not `null`, but somehow `url.search` does not exist.

> Is there anything more I can help about this issue?

Can you try this javascript snippet in the browser console (any one will do)? (paste at the bottom of the console, hit enter, see result).

`var u = (URL || webkitURL); var a = null; try { a = new URL('https://toto.com/'); } catch(e) {}; a.search.length;`

**Comment by rumorumo** [comment]
The result: "TypeError: Cannot read property 'length' of undefined".

**Comment by gorhill** [comment]
Can you try:

    var u = (URL || webkitURL); var a = null; try { a = new URL('https://toto.com/'); } catch(e) {}; a;

Then expand the result to see the listed properties? For example, on my side I get:

    var u = (URL || webkitURL); var a = null; try { a = new URL('https://toto.com/'); } catch(e) {}; a;
    URL {}
        hash: ""host: "toto.com"
        hostname: "toto.com"
        href: "https://toto.com/"
        origin: "https://toto.com"
        password: ""pathname: "/"
        port: ""protocol: "https:"
        search: ""username: ""
        __proto__: URL

**Comment by rumorumo** [comment]
The result here is "URL {}" too, but I don't know how to expand it...

**Comment by lewisje** [comment]
In Chrome, you should see a ▶ symbol, that when clicked will expand the list of properties; in other modern browsers, the interface is similar.

**Comment by rumorumo** [comment]
Here in my console I don't see such symbol.

**Comment by gorhill** [comment]
Try replacing the trailing `a;` with `console.log('%o', a);`.

**Comment by rumorumo** [comment]
Here is what I get (there are many more levels of expansion, tell me how further I have to go):

```
var u = (URL || webkitURL); var a = null; try { a = new URL('https://toto.com/'); } catch(e) {}; console.log('%o', a);
    URL
        __proto__: URL
            constructor: function URL() { [native code] }
                arguments: null
                caller: null
                createObjectURL: function createObjectURL() { [native code] }
                length: 0
                name: "URL"
                prototype: URL
                revokeObjectURL: function revokeObjectURL() { [native code] }
                toString: function toString() { [native code] }
                __proto__: function Empty() {}
                <function scope>
            __proto__: Object
                __defineGetter__: function __defineGetter__() { [native code] }
                __defineSetter__: function __defineSetter__() { [native code] }
                __lookupGetter__: function __lookupGetter__() { [native code] }
                __lookupSetter__: function __lookupSetter__() { [native code] }
                constructor: function Object() { [native code] }
                hasOwnProperty: function hasOwnProperty() { [native code] }
                isPrototypeOf: function isPrototypeOf() { [native code] }
                propertyIsEnumerable: function propertyIsEnumerable() { [native code] }
                toLocaleString: function toLocaleString() { [native code] }
                toString: function toString() { [native code] }
                valueOf: function valueOf() { [native code] }
                get __proto__: function __proto__() { [native code] }
                set __proto__: function __proto__() { [native code] }
undefined
```

**Comment by gorhill** [comment]
Thanks, this explains the problem. Could you try one last js snippet to confirm the fix?

    var u = (webkitURL || URL); var a = null; try { a = new URL('https://toto.com/'); } catch(e) {}; console.log('%o', a);

**Comment by rumorumo** [comment]
```
var u = (webkitURL || URL); var a = null; try { a = new URL('https://toto.com/'); } catch(e) {}; console.log('%o', a);
    URL
        __proto__: URL
            constructor: function URL() { [native code] }
                arguments: null
                caller: null
                createObjectURL: function createObjectURL() { [native code] }
                length: 0
                name: "URL"
                prototype: URL
                revokeObjectURL: function revokeObjectURL() { [native code] }
                toString: function toString() { [native code] }
                __proto__: function Empty() {}
                <function scope>
            __proto__: Object
                __defineGetter__: function __defineGetter__() { [native code] }
                __defineSetter__: function __defineSetter__() { [native code] }
                __lookupGetter__: function __lookupGetter__() { [native code] }
                __lookupSetter__: function __lookupSetter__() { [native code] }
                constructor: function Object() { [native code] }
                hasOwnProperty: function hasOwnProperty() { [native code] }
                isPrototypeOf: function isPrototypeOf() { [native code] }
                propertyIsEnumerable: function propertyIsEnumerable() { [native code] }
                toLocaleString: function toLocaleString() { [native code] }
                toString: function toString() { [native code] }
                valueOf: function valueOf() { [native code] }
                get __proto__: function __proto__() { [native code] }
                set __proto__: function __proto__() { [native code] }
undefined
```

**Comment by gorhill** [comment]
Ugh, there was a mistake in my js snippet. Can you rather try:

    var U = (webkitURL || URL); var a = null; try { a = new U('https://toto.com/'); } catch(e) {}; console.log('%o', a);

**Comment by rumorumo** [comment]
```
var U = (webkitURL || URL); var a = null; try { a = new U('https://toto.com/'); } catch(e) {}; console.log('%o', a);
    URL
        __proto__: URL
            constructor: function URL() { [native code] }
                arguments: null
                caller: null
                createObjectURL: function createObjectURL() { [native code] }
                length: 0
                name: "URL"
                prototype: URL
                revokeObjectURL: function revokeObjectURL() { [native code] }
                toString: function toString() { [native code] }
                __proto__: function Empty() {}
                <function scope>
            __proto__: Object
                __defineGetter__: function __defineGetter__() { [native code] }
                __defineSetter__: function __defineSetter__() { [native code] }
                __lookupGetter__: function __lookupGetter__() { [native code] }
                __lookupSetter__: function __lookupSetter__() { [native code] }
                constructor: function Object() { [native code] }
                hasOwnProperty: function hasOwnProperty() { [native code] }
                isPrototypeOf: function isPrototypeOf() { [native code] }
                propertyIsEnumerable: function propertyIsEnumerable() { [native code] }
                toLocaleString: function toLocaleString() { [native code] }
                toString: function toString() { [native code] }
                valueOf: function valueOf() { [native code] }
                get __proto__: function __proto__() { [native code] }
                set __proto__: function __proto__() { [native code] }
undefined
```
