### ISSUE TITLE
Ads on some sites take a second or two to fully collapse.

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#807]
If you go to this site http://www.freeware-guide.com/html/updates.html there is an add right below the current days list of software.  It starts out as an empty space where the ad was and then collapses after a second or so.  

SPECS
----------
Ublock Origin 1.2.2b2
Firefox 44 (Nightly) 64bit version
Filter lists:  Just the default ones.

i7 Quad 3770K @ 5Ghz[b]|[/b]ASUS P8Z77-V Deluxe[b]|[/b]Corsair 1050W PSU[b]|[/b]Corsair H100 CPU Cooler[b]|[/b]Corsair DDR3 16GB RAM @ 2400MHz[b]|[/b]Sapphire HD7970 3GB[b]|[/b]DUAL ASUS PA249Q IPS 24" LCDs[b]|[/b]Samsung SSD 830, 840 256GB[b]|[/b]2TB Seagate SATA3[b]|[/b]Windows 10 Pro x64[b]|[/b]AMD 15.9.1 CATS[b]|[/b]120Mbps/40Mbps

**Comment by CrisBRM** [comment]
Can't replicate. I see no placeholders.

**Comment by streetwolf** [comment]
First of all what I am seeing only happens the first time you go to the site.  When you go here you do not see an empty space between the first two lists of software in the boxes?  It disappears in about a second.

**Comment by CrisBRM** [comment]
I made sure to visit it again in incognito mode and still nothing. 
Is e10s enabled? I just noticed you're using nightly, and I'm using stable /e10s is disabled). I've had quite some problems before in the past, with e10s, (strictly) performance wise.

**Comment by streetwolf** [comment]
Disabled e10s and I get the same 'problem'.  Nightly might be the key.  I'm also on the 64bit version of Fx44 with PGO.  Btw, e10s work great on Nightly.  They made a lot of improvements.

**Comment by streetwolf** [comment]
The delay is really a little bit longer than in the gif.

![sample](https://cloud.githubusercontent.com/assets/410799/10407717/ad050f5e-6ebc-11e5-9a5a-30c4dd1ae825.gif)

**Comment by CrisBRM** [comment]
Oh I know what to look for now... You said it was 'right' below the current days list of software' and it's between the first table and the second date. 
Well, this is normal. I've ran this a few times and I think you're exaggerating  because my CPU is a bit weaker than yours (i5-4670 at stock speeds) and I don't think the worst case was over 0.5 seconds.

Have a read: https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

**Comment by streetwolf** [comment]
I guess it's normal after reading from the link you gave.  Thanks for replying, Cris.
