### ISSUE TITLE
Images for social media like Twitter, Facebook, etc, don't display

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#809]
Go to http://www.neowin.net/ the first article is about Twitter and the image is missing.  I can still click on the empty spot to get to the article.  This is due to using Fanboy's Annoyance List.  There must be a way to override this.  Happens with all the social media stuff.

![neowin](https://cloud.githubusercontent.com/assets/410799/10411893/8d0bb2f8-6f42-11e5-9894-90aa659b1b03.jpg)

**Comment by gitarra** [comment]
Thats the point of that list?

**Comment by streetwolf** [comment]
I used to use AdGuard and the AG folks were able to provide a filter specific to neowin.net that displayed these missing images.

**Comment by gorhill** [comment]
If you ask a fix to maintainers of _Fanboy’s Social Blocking List‎_, the solution will work for everybody and for whatever blocker, not just for you and your AdGuard installation. In general it's how it works: if a 3rd-party filter list blocks something it should not block, the first thing to do is to report the issue to the filter lists maintainers.

**Comment by streetwolf** [comment]
I reported it to Fanboy.

Gary

----- Original Message -----

**Comment by gitarra** [comment]
I dont think you understand the list is supposed to block all social media embeds.

**Comment by streetwolf** [comment]
It's true that the filter in Fanboy's annoyance list is blocking it.  But in my mind the blocking should be done for all the small social media icons that are on sites not an image of some Twitter or Facebook article.  Can't these sort of images be allowed perhaps if they are over a certain dimension?

Gary

----- Original Message -----

**Comment by gitarra** [comment]
Oh, right. It may not be feasible to create exceptions for every single common false positive like this, theyve always been there and are easily solvable temporarily by the user.

**Comment by streetwolf** [comment]
Fanboy gave me a filter that works fine.  FWIW  it's @@||neowin.net/images/uploaded/$image
