### ISSUE TITLE
Documentation notes

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#810]
@gorhill Will you mention this in README.md and https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ?:
* the unique inline script tag filtering feature.
* the unique strict blocking feature - This is not found in uBlock.
* Thunderbird support.

**Comment by gorhill** [comment]
No, the README is an overview, those features are specifics, enumerating them in the README would defeat the point of "overview". They are best left to the wiki.

**Comment by flyingzebras** [comment]
@gorhill Ok, but should they not be mentioned in https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ?

**Comment by flyingzebras** [comment]
@gorhill Ok, but should they not be mentioned in https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ? I'm sure it will increase the popularity significantly.

**Comment by flyingzebras** [comment]
More.

@gorhill said: "uBlock Origin is not "based on" uBlock 0.9.5.0 or any version -- the two versions diverged starting at 0.9.3.0. I don't like the word "based on" because from my point of view I have just kept developing it without interruption since June 2014."

**Comment by flyingzebras** [comment]
@gorhill I still suggest that you mention this in https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ?:

* the unique inline script tag filtering feature - This is not found in uBlock.
* the unique strict blocking feature - This is not found in uBlock.
* Thunderbird support - This is not found in uBlock.

Finally, 

gorhill said: "uBlock Origin is not "based on" uBlock 0.9.5.0 or any version -- the two versions diverged starting at 0.9.3.0. I don't like the word "based on" because from my point of view I have just kept developing it without interruption since June 2014." - https://github.com/gorhill/uBlock/issues/839#issuecomment-148926481

You might want to add that to https://github.com/gorhill/uBlock/blob/master/README.md along the text "There is an idea floating around that uBlock Origin is a lesser branch relative to uBlock."

**Comment by flyingzebras** [comment]
@gorhill I think the proper place to mention these features would be at https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#abp-has-all-the-features-ublock-has. Can you please add it?

**Comment by flyingzebras** [comment]
@gorhill Can you please add `To block "popunders" windows/tabs. To be used in the same manner as the popup filter option, except that it will block popunders.` to https://github.com/gorhill/uBlock/wiki/What-uBlock-can-and-can-not-%28currently%29-do#abp-has-all-the-features-ublock-has ?

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1542
