### ISSUE TITLE
Result links on Google Search sometimes don't work

### ISSUE THREAD

**Issue by djc** [gorhill/uBlock#813]
With uBlock Origin 1.2.1 on Firefox Nightly (44.0a1 2015-10-08), I have the following problem:

Steps to reproduce:
1. Do a Google search
2. Open two or three results in another tab (via right-click)
3. Attempt to open another result normally

Expected result:
Result page opens.

Actual result:
Result page does not open. When looking in the Developer Console, I see a Permission denied error, mentioning "navigateTo()" and google.

I'm using uBlock Origin with pretty much default settings.

**Comment by zummuz** [comment]
> 3. Attempt to open another result normally

Do you mean just left click on the link?
I can't repeat in Firefox Nightly 44.0a1 (2015-10-10), uBO 1.2.1.

**Comment by djc** [comment]
Yes, that's what I meant.

Note that the first (few) left clicks on the link usually work for me. It seems to be only after I open a few other links through other means (e.g. in a new tab), the normal one stops walking. Also, intriguingly, I have keyboard shortcuts added for Google Results, and those appear to work normally.

**Comment by gorhill** [comment]
> in the Developer Console, I see a Permission denied error, mentioning "navigateTo()" and google.

Why not print the whole error here?

**Comment by djc** [comment]
Okay, at least now I'm also unable to reproduce it.
