### ISSUE TITLE
uBlock filters – Privacy‎ [3rd-party filters]: filter rule issue

### ISSUE THREAD

**Issue by lencc** [gorhill/uBlock#814]
The rule <code>##.addthis_toolbox</code> in the "uBlock filters – Privacy‎" distorts content on some websites (I am using Firefox). Example (here the article's date is overlapping its content):
http://tech.co/swiss-innovation-solar-impulse-2015-08

**Comment by weakptr** [comment]
Just add the following to 'My filters':
tech.co#@#.addthis_toolbox

**Comment by lencc** [comment]
I have already, thanks anyway.
I mentioned it because it could be also added to the uBlock Privacy list as an exception rule.
