### ISSUE TITLE
uBlock not blocking any ads at all (Firefox 41.0.1)

### ISSUE THREAD

**Issue by spaghetti-** [gorhill/uBlock#815]
Default settings, release 1.2.0 from github releases.

**Comment by gorhill** [comment]
Any errors in browser console?

**Comment by spaghetti-** [comment]
<img width="447" alt="screen shot 2015-10-13 at 5 09 27 pm" src="https://cloud.githubusercontent.com/assets/2093506/10450492/31606ace-71cd-11e5-8a67-17c0c3bc81eb.png">
No errors in browser console. Anywhere else I can look? It says 0% blocked in a lifetime but I'm a heavy user and definitely spend the better part of a day browsing.

**Comment by gorhill** [comment]
Look in the [logger](https://github.com/gorhill/uBlock/wiki/The-logger), see what is happening in there.

**Comment by spaghetti-** [comment]
Is there a way to export these logs so that I can gist it or something?

Anyway some screenshots here.

<img width="1552" alt="screen shot 2015-10-14 at 2 38 42 am" src="https://cloud.githubusercontent.com/assets/2093506/10465214/399bda5e-7220-11e5-9542-8b384517d900.png">
<img width="1552" alt="screen shot 2015-10-14 at 2 38 45 am" src="https://cloud.githubusercontent.com/assets/2093506/10465219/3f4880c4-7220-11e5-8a1c-56a829cc3574.png">

**Comment by gorhill** [comment]
For now there is just select-then-cut-and-paste.

**Comment by spaghetti-** [comment]
Even without it it is quite obvious that nothing is being blocked thought.

**Comment by gorhill** [comment]
> quite obvious

No: maybe the document is being whitelisted, but I can't tell from your screenshots.

**Comment by spaghetti-** [comment]
True, well I did mention default settings thought. Anyway screenshots of settings here: http://imgur.com/a/mJ2AW

I have also did a clean install of firefox and ublock again, no change.

**Comment by spaghetti-** [comment]
Clicking `Update filter list` did the trick. I noticed it said 0 filters. However why it was in that state I don't know; but I think this issue can be closed?

**Comment by gorhill** [comment]
This is anomalous:

![.](http://i.imgur.com/UITcK7a.png)

I will need to look in the code if and how this anomalous condition can arise.

Was it the first time ever you installed uBlock?

**Comment by spaghetti-** [comment]
Well I had it on my Yosemite install; did a fresh install of El-cap, installed Firefox and the first plugin I installed was uBlock Origin.

**Comment by spaghetti-** [comment]
I faced the same issue again when I was trying to help out by reproducing https://github.com/gorhill/uBlock/issues/818

Check out my filter settings in incognito mode.

<img width="1552" alt="screen shot 2015-10-14 at 2 40 01 pm" src="https://cloud.githubusercontent.com/assets/2093506/10476575/b73b65e0-7281-11e5-89eb-12bca25114aa.png">
<img width="1552" alt="screen shot 2015-10-14 at 2 39 59 pm" src="https://cloud.githubusercontent.com/assets/2093506/10476576/b73fe5fc-7281-11e5-825e-5325d5a1cea3.png">

**Comment by gorhill** [comment]
I just noticed there is an _Apply changes_ button in your pane -- this means you changed the filter lists without applying the changes. Also, is it possible there are scriptlets injected by Greasemonkey on the page?

**Comment by spaghetti-** [comment]
When I restart my firefox my filter preferences disappear.

<img width="1552" alt="screen shot 2015-10-14 at 11 44 25 pm" src="https://cloud.githubusercontent.com/assets/2093506/10488928/93138386-72cd-11e5-8952-58a89cd2f62a.png">

Also, once I click the auto-update filter lists button the Apply button goes away.

**Comment by spaghetti-** [comment]
Greasemonkey has only [4chan-x](https://github.com/ccd0/4chan-x) enabled on `*.4chan.*`

**Comment by gorhill** [comment]
> When I restart my firefox my filter preferences disappear

Something is messing up uBlock Origin's SQlite file content? (location of uBlock's SQlite file [detailed here](https://github.com/gorhill/uBlock/tree/master/dist).)

There definitely appears to be something specific on your side messing things up for uBlock Origin -- or else you wouldn't be alone with such problem given the user base. You are best placed to figure how your environment differs from the "normal" one. (Sandboxie?, etc.)

**Comment by sol-arion** [comment]
Been having the same issue on 41.0.2 for the past week, it barely blocks anything at all.

**Comment by gorhill** [comment]
> it barely blocks anything at all

What does the logger say? Any specifics about what you think should be blocked and is not blocked (it's just impossible to investigate vague statements).

**Comment by sol-arion** [comment]
It was just leaving all the ads and popups unblocked lately, it still kept some stuff blocked a couple days ago though.

I just noticed whenever I click update or apply changes on the 3rd-party tab it greys out and it stops responding. I've reinstalled ublock and disabled other add-ons and it still happened, after enabling them I disabled a couple filters and applied the changes and it's working fine now, I think, at least on the couple sites I tried.

**Comment by spaghetti-** [comment]
I found the sqlite file and it seems to be having data inside it. Heres the keys from the settings tables
```
sqlite> select name from settings;
advancedUserEnabled
allowedRequestCount
allowedRequestCount
allowedRequestCount
allowedRequestCount
autoUpdate
blockedRequestCount
blockedRequestCount
blockedRequestCount
blockedRequestCount
cached_asset_content://cache://compiled-filter-list:0ac3e036
cached_asset_content://cache://compiled-filter-list:22695657
cached_asset_content://cache://compiled-filter-list:27dbcb9c
cached_asset_content://cache://compiled-filter-list:56f302f3
cached_asset_content://cache://compiled-filter-list:5b554665
cached_asset_content://cache://compiled-filter-list:955ecae7
cached_asset_content://cache://compiled-filter-list:a4b35371
cached_asset_content://cache://compiled-filter-list:c5181d72
cached_asset_content://cache://compiled-filter-list:da6a3cf4
cached_asset_entries
cloudStorageEnabled
collapseBlocked
colorBlindFriendly
compiledMagic
contextMenuEnabled
dynamicFilteringEnabled
experimentalEnabled
extensionLastVersion
externalLists
firewallPaneMinimized
hostnameSwitchesString
hyperlinkAuditingDisabled
netWhitelist
parseAllABPHideFilters
prefetchingDisabled
remoteBlacklists
requestLogMaxEntries
selfieMagic
showIconBadge
version
webrtcIPAddressHidden
```
Does not seem to be overwritten or wiped everytime firefox starts, but it doesn't load the filter lists all the same.

My firefox is installed via homebrew-cask which is the only thing different I have about my environment.

**Comment by gorhill** [comment]
I don't understand why there 4 entries for `allowedRequestCount` and `blockedRequestCount`. That's the only anomaly I see, maybe inconsequential.

**Comment by gorhill** [comment]
Do the entries starting with `cached_asset_content://cache://compiled-filter-list:` have data in them?

**Comment by gorhill** [comment]
@sol-arion 

>  I disabled a couple filters

Is it possible for you to share these filters?

**Comment by Gittino** [comment]
Hi, I don't know if my issue is related to this but today uBlock origin doesn't work anymore.
Into the Dashboard panel -> 3rd-party filters I see this instead of the usual checkboxes list:

![ublock](https://cloud.githubusercontent.com/assets/13353503/10751978/713c2cb0-7c85-11e5-9df6-44f82ef6acde.png)
(Note also that the buttons Update now and Purge all caches are disabled)

I suppose that some file/database has been corrupted for some reason. 
Is there a manner completely remove uBlock with all its configuration etc to make a new clean installation?

I use it in sandboxie without problems from many time, few days ago I installed greasemonkey I don't know if it could be related.

Thanks and best regards,

**Comment by gorhill** [comment]
What browser/version?

Any error message in the browser console?

Did you have custom filters? If so, can you share?

**Comment by Gittino** [comment]
Browser: Firefox 41.0.2
In browser console I have those errors concerning ublock0:
"SQLite error  11 database disk image is malformed                                vapi-background.js:368:17
runStatement/<.handleError()                                                                   vapi-background.js:368"

I don't have custom filters, but probably sometime I tried to create some filter just to see how it works but I don't remember on which site and if after the try I deleted them.

**Comment by gorhill** [comment]
> "SQLite error 11 database disk image is malformed vapi-background.js:368:17
runStatement/<.handleError() vapi-background.js:368"

Ugh, that does not look good.

> Is there a manner to clear the UBlock part of the database to the initial condition?

Normally clicking _"Restore default settngs"_ in _Settings_ pane in dashboard is supposed to work. I wonder if this will work though given your SQlite file is hosed. If this does not work, deleting manually the SQlite file will work for sure. Location of the file is [detailed here](https://github.com/gorhill/uBlock/tree/master/dist).

**Comment by Gittino** [comment]
Whoooa it worked! 
I had to delete the sqlite file manually but now all seems to work correctly again. 
Thanks a lot for the support, used to uBlock I had forgotten how annoying some banner are. 
Staying just for half a day with uBlock borcken was making me mad!!!

**Comment by gorhill** [comment]
I wonder if the use of Sandboxie has anything to do with the corruption of the SQlite file.

**Comment by Gittino** [comment]
Mmmh i doubt it, 
I use sandboxie everyday and this is the first time that the sql file has been corrupted.
In any case if I notice anything related to this issue I'll report it here.
Some day ago I installed greasemonkey but it doesn't work well, the script added to it is not executed on the targeted page, maybe there is some interference with ublock? Or maybe it is only a coincidence.

**Comment by MrTorch** [comment]
I can confirm that sandboxie is probably not the problem. I've never used that and my SQlite file still seemed to have gotten corrupted somehow.

**Comment by gorhill** [comment]
Looking up the error code `11` for SQlite leads to [documentation](https://www.sqlite.org/lockingv3.html#how_to_corrupt) about how the SQlite file can be corrupted.

**Comment by spaghetti-** [comment]
@gorhill so I just installed on a fresh macbook (15" latest) and via brew cask, it is performing flawlessly with no problems.

I guess its something really specific to my old machine.

**Comment by spaghetti-** [comment]
@gorhill updating this, created a new profile on the old laptop, works again

Something profile specific then.
