### ISSUE TITLE
no roadmap page on the wiki

### ISSUE THREAD

**Issue by elypter** [gorhill/uBlock#817]
especially if you do not want users to suggest features you should point out somewhere what you are planning for the near or distant future or what you have thought about already. then poeple will at least not bug you about the most freuquently wanted stuff.
btw this is not a feature request because there is something going wrong (people getting upset and wasting time)

**Comment by gorhill** [comment]
I don't decide on what I will work in advance. If I have an idea about how to solve something, I may decide to work on it just because I feel like working on it -- and this may be something not in the pile of issues.

**Comment by elypter** [comment]
"roadmap" is a bit strict but every developer has a todo or idea list or am i wrong? or is this something you do not want to disclose?

**Comment by gorhill** [comment]
> every developer has a todo or idea list ... is this something you do not want to disclose?

[Again](https://github.com/gorhill/uBlock/issues/817#issuecomment-147535233):

> I don't decide on what I will work in advance. If I have an idea about how to solve something, I may decide to work on it just because I feel like working on it -- and this may or may not be something in the pile of issues.

**Comment by elypter** [comment]
well, at least this clears up some questions about the fork drama. you should paste that in the contribution readme. most developers have fundametally different coding motivations. this would help to avoid misunderstandings.
