### ISSUE TITLE
can't "Go back" from document blocked page

### ISSUE THREAD

**Issue by fjarlq** [gorhill/uBlock#818]
1. Visit some site that is blocked, like:
   - http://sourceforge.net/
   - http://taboola.com/
2. Now you're at uBlock's blocked page. Try clicking "Go back", or click the browser's back button.
3. Notice that you're still at the blocked page -- going back is prevented.

When at uBlock's blocked page, the blocked URL is listed in the browser tab's page history as the most recent previous page, so going back results in another blocked page.

If uBlock cannot prevent the blocked URL from getting listed in the history as the previous page, then maybe "Go back" could be smarter by choosing the most recent history item that wasn't blocked, and perhaps a note should be added to the uBlock blocked page explaining that the browser's Back button will not work.

Observed in Chrome 45.0.2454.101 on OS X 10.10.5.

**Comment by gorhill** [comment]
I could go back fine after clicking the two provided URLs.

**Comment by fjarlq** [comment]
Hmm.. I disabled all my other extensions, and it still happens for me, both on my laptop (running OS X 10.11) and on my desktop (OS X 10.10.5), current Chrome stable on both. I can reproduce it by clicking the links from here in this bug report, every time. I don't know what else might be different about my system to cause this issue. I'm on uBlock Origin 1.2.0.

Any ideas? I obtained a packet trace but did not observe any HTTP redirects. I don't have any other filtering programs installed.

I have set a few uBlock Origin options... I believe this is the complete list:
* unchecked "Show the number of blocked requests on the icon"
* checked "Enable cloud storage support"
* checked "Prevent WebRTC from leaking local IP addresses"
* added a couple dozen hosts to my whitelist
* enabled a few additional filters including the defaults:
  * _Adblock Warning Removal List_
  * _Anti-Adblock Killer_
  * _Basic tracking list by Disconnect_
  * _Malvertising filter list by Disconnect_
  * _Malware domains (long-lived)_
  * _Malware filter list by Disconnect_

**Comment by fjarlq** [comment]
Also happens on Windows 7 running the latest Chrome stable (45.0.2454.101).

**Comment by fjarlq** [comment]
Still happens on the newly released Chrome stable 46.0.2490.71. Both OS X and Windows 7.

**Comment by spaghetti-** [comment]
I can reproduce this, but I thought it was intended.

Firefox 41.0.1

**Comment by publicarray** [comment]
I can reproduce in Chrome. I think the problem for chrome is that sourceforge.net is in the history (creating the redirect loop) while in FF it is not. (OSX 10.11)

Firefox 41.0.1:
![screen shot 2015-10-15 at 1 25 00 pm](https://cloud.githubusercontent.com/assets/5497998/10504128/7d075e6e-7340-11e5-9b9c-c1244409f861.png)

Chrome 46.0.2490.71:
![screen shot 2015-10-15 at 1 26 09 pm](https://cloud.githubusercontent.com/assets/5497998/10504130/7e494aa8-7340-11e5-8ddd-ab8194489a68.png)

**Comment by fjarlq** [comment]
@spaghetti- I cannot reproduce this in Firefox 41.0.1 on Windows 7. I tried both the default uBlock settings and then with my usual customizations as I described above, but the Back button and "Go back" both always work.

Neither could @publicarray reproduce it in Firefox.

Are you sure that it reproduces for you in Firefox? If so, any idea what might be different in your Firefox to cause it to reproduce there?

**Comment by gorhill** [comment]
> I can reproduce in Chrome

I can't reproduce neither with Chrome or Firefox.

uBlock Origin will replace the top entry in the history with it's own block page, so whatever was blocked should be replaced with uBlock warning page, and this mean the back button will go to whatever was in there before navigating to teh blocked page.

This does not work well though with redirect -- a known issue. I have meant to look into this but haven't yet taken the time. However there is no redirect in the current case, so I don't understand why this happens when merely clicking on the links in OP.

**Comment by fjarlq** [comment]
Yeah, I'm baffled that you can't reproduce it. I suppose that suggests there is some Chrome setting that @publicarray and I have, but you don't, that is responsible. (and maybe a Firefox setting as well, to explain what @spaghetti- observed?)

It might be helpful if someone tried starting with a freshly-installed OS, downloading Chrome and uBlock Origin to it (without logging in and synching Chrome settings from the cloud), and seeing if that alone can reproduce the problem. Based on my test of Firefox, the defaults are insufficient there to reproduce.

**Comment by publicarray** [comment]
>  I suppose that suggests there is some Chrome setting that @publicarray and I have,

I created a new chrome user to test this. Only uBlock Origin is installed. On the first try it worked as expected, but when I tried again I entered the loop (sourceforge.net was not overwritten on the second try).

**Comment by publicarray** [comment]
> uBlock Origin will replace the top entry in the history with it's own block page

OK. I have another test case If I open sourceforge.net in new tabs really fast (middle click or control click) most pages act like you said i.e. back button is disabled/empty however I got a few (3 out of ~30) that have the back button enabled with sourceforge.net in it's history. (Might be a browser bug)

**Comment by publicarray** [comment]
I noticed If I right click and `Open Link in Incognito Window` sourceforge.net is fully loaded.

**Comment by gorhill** [comment]
> I noticed If I right right click on the link and Open Link in Incognito Window sourceforge.net is fully loaded.

This is a browser quirk, there is no way to prevent this for sure. The reason is that there is no guarantee that uBlock Origin will be up and running before a page loads. Once the first private window is opened, uBO will be able to blocked as expected when using _"Open Link in Incognito Window"_.

**Comment by abjugard** [comment]
I have this issue as well, running latest Chrome, can reproduce consistently on Windows 10, happens occasionally on OS X, can't reproduce at all on Linux.

**Comment by gorhill** [comment]
It's explained above, it's a browser limitation: both Chromium and Firefox when launched do not wait for all extensions to be up and ready before loading web pages.

**Comment by gorhill** [comment]
> can reproduce consistently on Windows 10

Ok, I will give this a try in VM'ed Win7.

**Comment by gorhill** [comment]
Ok even on Chrome/Window 7 I can't reproduce.

For those who can reproduce, please provide the following details when the issue occur:

- The exact URL which is blocked, as reported by uBO.
- The exact URL of the previous entry in the history while uBO's blocked page is displayed (go to History if needed to)
- Any other extensions installed which could be tampering the History stack?

**Comment by fjarlq** [comment]
Exact URL which is blocked, as reported by uBO: http://sourceforge.net/

Exact URL of previous entry in history at that time: https://github.com/gorhill/uBlock/issues/818

Prior to testing, I disabled all my extensions except uBO. Also, though I don't know why it would matter, my Flash Player and Native Client are disabled completely in chrome://plugins. The only other plugins I have are Widevine and Chrome PDF.

I tested this just now on Chrome 46.0.2490.80 on Windows 7, with uBO 1.3.3. I can reproduce it every time, on both Windows and Mac Chrome. (I haven't tried anything else.)

I can't think of any other software that might be interfering with my browser on both Mac and Chrome. There is no proxy or firewall software. I'm behind a Comcast Xfinity cable modem and an Apple Airport.

A few other changes to my Chrome config that I can recall:

* I disable "Prefetch resources to load pages more quickly"
* I disable "Use a web service to help resolve spelling errors"
* I enable "Send a "Do Not Track" request with your browsing traffic"
* I block third-party cookies and site data
* I've selected "Let me choose when to run plugin content"

**Comment by gorhill** [comment]
Right-clicking on the back button, this is what I get:

![a](https://cloud.githubusercontent.com/assets/585534/11037927/7507a7fe-86ce-11e5-9406-4091f01a981a.png)

**Comment by gorhill** [comment]
I am going to have to assume there is a timing issue here, and for some `sourceforge.net` ends up in the history (probably would display a kind of "can't connect" error page). Now I have to try and figure how to make this deterministic. Reading the content of the history stack is not possible -- unless I ask for yet another API permission, which is out of question.

**Comment by fjarlq** [comment]
Interesting. I'd be happy to run any test extensions you might come up with, to help you figure out what's going on, since I can reproduce it so easily.

For completeness, I obtained a screenshot in the same state that you did above, showing the extraneous item in the history:

![screen shot 2015-11-11 at 00 49 42](https://cloud.githubusercontent.com/assets/441483/11086494/e770d324-880e-11e5-981f-974a42ec2074.png)

**Comment by cnanney** [comment]
I run into this every time, exactly as described.... I'm on good page A, click link to blocked page B, uBlock warning opens as page C. Page B is the last history entry, so clicking the browser back button or the one on the uBlock page just returns me to B, which then immediately re-opens C.

To get back to A, I have to manually open the back history to go back two places.

Chrome 54.0.2840.71 m (64-bit)

**Comment by gorhill** [comment]
> I have to manually open the back history to go back two places.

No need to open history, just right-click on the back button.

**Comment by cnanney** [comment]
Yeah that's what I meant (poorly worded). I should have read through the comments more closely, I see there is no easy fix because it is inconsistent and no way to see if you need to go 1 or 2 back in the history. Oh well, no big deal. Thanks for an amazing extension!

**Comment by evildog1** [comment]
I'm having the same problem with uBlock Origin
