### ISSUE TITLE
Import (with merge) from cloud storage doesn't handle deletions

### ISSUE THREAD

**Issue by fjarlq** [gorhill/uBlock#819]
1. Add `example.com` to your whitelist
2. Upload your whitelist to cloud storage
3. On a second device, import the newly-updated whitelist
4. Later, notice ads while browsing `example.com` and get irritated by it
5. Delete `example.com` from your whitelist
6. Upload the new whitelist
7. On a second device, import (with merge) the newly-updated whitelist
8. Notice that `example.com` hasn't been deleted from the imported-with-merge whitelist

I'm not sure if import with merge is supposed to handle deletions, but I would like that. In step 7, I imported with merge (rather than without merge) because I never want to use import without merge -- importing without merge is a good way to lose whitelist changes that you forgot to upload to cloud storage.

What I really want, of course, is when I update the whitelist on one of my browsers, the whitelist is automatically updated in the same way on all of my browsers.

**Comment by gorhill** [comment]
> import (with merge)

That's why.

> I'm not sure if import with merge is supposed to handle deletions, but I would like that.

The sync storage is clipboard-like, it's not a journal of all that happens on every single involved computers.
