### ISSUE TITLE
[Firefox] uBlock disabled on first unloaded tab on the left

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#820]
Set Firefox to restore session from last time, and don't load tabs until selected.
Open few tabs. Select either tab on the right.
Restart browser.
Right click on tab bar on the first tab on the left, and select 'Reload Tab', wait until loaded. (may be automatically loaded when using [Auto Unload Tab](https://addons.mozilla.org/en-US/firefox/addon/auto-unload-tab/) extension)
Switch to this tab.
uBlock icon is grey, power button is grey, nothing is blocked.

It works when simply switching to first tab, but some resources may slip through.

Fx 41.0.1 on Linux Mint 17.2, 
Fx 43a2 on Windows 7
uBlock 1.2.2b2

Example url:
https://encrypted.google.com/search?q=buy+iphone
https://www.inoreader.com/all_articles

Broken:
![broken](https://cloud.githubusercontent.com/assets/886325/10451282/7ba779f2-719f-11e5-83bc-17edb67b7060.png)
Reloaded:
![reloaded](https://cloud.githubusercontent.com/assets/886325/10451284/806491b4-719f-11e5-9e80-b69a4545c4ec.png)

**Comment by gorhill** [comment]
Unable to reproduce using FF 41.0.1, Linux Mint 17.2.

**Comment by gorhill** [comment]
Firefox's tab management is really complicated...

1. The tab is created when Firefox launches
1. It's URI is `about:blank`
1. It's `pending` attribute is **NOT** set (unexpected)
1. Eventually `LocationChangeListener` for the tab is called with `https://www.inoreader.com/all_articles`
1. However its `pending` attribute is now set...
1. Which means the event is ignored, and thus the tab is not rebound to the proper URI.

**Comment by gorhill** [comment]
Also, the fact that the `pending` attribute is not set on suspended tabs at load time means that now issue #697 is back...

**Comment by gwarser** [comment]
Looks good, thank you.
