### ISSUE TITLE
Filter addition: Pornhub NETWORK

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#822]
This message popup show up the second visit on any video page, placed over the videos with the text "Level UP! Congratulations, you leveled up! Please Login or Sign Up to save your points." This is nonsense. EasyList do not consider this to be ads so they decided not to add this filter even after months of discussion (see https://forums.lanik.us/viewtopic.php?f=62&t=21495&p=67911). This filter will block on tube8.com, tube8.es, and tube8.fr:

`||tube8.*##.main-wrapper > .content-wrapper > .level-up-popup-wrapper`

Can you please add this filters to https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt @gorhill ?

**Comment by RoxKilly** [comment]
@flyingzebras I would be cautious about going down the line of adding filters to everybody's install for nagging features on specific sites. I don't see the privacy or malware implication of this popup behavior so I don't know why uBlock should censor it by default (unless uBlock is in the business of popup blocking)

Doesn't uBlock give us the ability to add our own custom filters exactly for this use case?

**Comment by gorhill** [comment]
I could not reproduce this anyways. If I had and found that this was the site promoting itself, I would not add it for couple of reasons: 1) I am not a filter list maintainer; 2) This should not be blocked by uBlock -- this is something for Fanboy Annoyances at most.

**Comment by flyingzebras** [comment]
@gorhill Thank you for pointing this out, I will contact Fanboy about it.
