### ISSUE TITLE
Whitlist flattr.com didn't work

### ISSUE THREAD

**Issue by Tuffiglig** [gorhill/uBlock#823]
Hallo.
I added flattr.com to the Withlist, but when I open, for example, this page:
http://freakshow.fm/fs162-das-fix-ich-jetzt-einfach-mal
the flattr buttons are still blocked.

**Comment by gorhill** [comment]
How did you "whitelist" Flattr?

**Comment by Tuffiglig** [comment]
ublock Dashbord --> Tab:Whitlist --> fill in:flattr.com --> save changes

![ublock _ _dashboard_-_2015-10-14_07 13 25](https://cloud.githubusercontent.com/assets/15114290/10475382/553d380c-7243-11e5-8d96-a7ae591d84be.png)

**Comment by gorhill** [comment]
The _Whitelist_ pane are directives which tells uBlock Origin where it should completely disable itself. This is not what you want, what you want is an exception filter.

When I try the Flattr button on the site, I see nothing being blocked by uBlock Origin, so you should not need any exception filter using default settings. What is the issue exactly?

**Comment by Tuffiglig** [comment]
I made a new Firefox profile, installed ublock0 and chose the same filters like my main profile.
Her are the results:

ublock0 activated:
![2015-10-14 19_52_21-screenshots](https://cloud.githubusercontent.com/assets/15114290/10492753/fea91d42-72ad-11e5-95b5-a64eb31f6c94.png)

ublock0 deactivated:
![2015-10-14 19_51_36-screenshots](https://cloud.githubusercontent.com/assets/15114290/10492768/10b1f7b6-72ae-11e5-8f11-4afad49cda8b.png)

recorded requests:
![2015-10-14 19_54_37-ublock protokoll der netzwerk-anforderungen](https://cloud.githubusercontent.com/assets/15114290/10492825/45cd5896-72ae-11e5-8bfb-0cc50ce4a660.png)


Thank you for your help!
Thanks,
Tuffi

**Comment by gorhill** [comment]
> chose the same filters like my main profile

As said, there is no issue with the default settings. If you clicked on the filter in the logger, you would find out that `||api.flattr.com^third-party` is a filter from _Fanboy’s Annoyance List‎_, which is **not** part of uBlock Origin's default settings. The list is also 3rd-party to uBlock, any issue with it must be reported to its maintainers (<https://forums.lanik.us/viewforum.php?f=64>).

The cause of the issue was easy to find: click on the filter in the logger to find out where it comes from, and once you find out where it comes from, the name of the filter list is a link to the support site for that list.

**Comment by gorhill** [comment]
I ended up forgotting the original topic which was to "whitelist" Flattr...

you can use the logger for this, it will assist you to create filters: <https://github.com/gorhill/uBlock/wiki/The-logger#dynamic-url-filtering-rules>.

![a](https://cloud.githubusercontent.com/assets/585534/10495862/12996810-728c-11e5-9a0c-3130af20354e.png)

In the current case, you want:

    freakshow.fm http://api.flattr.com script allow

This goes in _My rules_.

**Comment by Tuffiglig** [comment]
Wonderful! Now it is working like I expected it and I can use flatter in the whole web without de- and activating ublock all the time!
I mixed up the whitelist in the first place and didn't know that it is so easy to create filters.
Thank you for your great help and for the work on ublock0!
Is there a way to support you?

Thank you,
Tuffi

**Comment by gorhill** [comment]
>  I can use flatter in the whole web without de- and activating ublock all the time!

If you want Flattr to work everywhere, the above instructions are not the best -- I thought you wanted only on that site.

For the _everywhere_ case, best is to forget what I said above and to instead add these filters in _My filters_:

    @@||flattr.com^
    #@#.flattr-button
