### ISSUE TITLE
Background color of up arrow

### ISSUE THREAD

**Issue by ekrabismi** [gorhill/uBlock#824]
Dear Admin,

I want to change the background color for up arrow of popup window. It's now white but how I can change the color to black? Which code file I have to change?
![ublock](https://cloud.githubusercontent.com/assets/5256169/10469634/96f15848-7228-11e5-8295-83471990e254.png)

**Comment by zummuz** [comment]
Browser's button *Open menu* has the same arrow, so I think extensions don't control that part of the interface and you have to change the style in browser's code. It's assumption.

**Comment by ekrabismi** [comment]
Is it possible to control the color by using extension?

**Comment by gorhill** [comment]
> Is it possible to control the color by using extension?

No, this part of the popup is under control of Firefox.

**Comment by ekrabismi** [comment]
Thanks for our help. You just save my times. Thanks again. Your extension is really great.
