### ISSUE TITLE
Yandex Browser

### ISSUE THREAD

**Issue by bibihh** [gorhill/uBlock#825]
The function "Prevent WebRTC from leaking local IP addresses" is not working in Yandex browser, latest version, which is Chrome based. I am running latest version on uBlockOrigin.

**Comment by gorhill** [comment]
You are not providing any details about how you find out _exactly_ "it's not working". In any case, it could very well be that Yandex people removed the WebRTC setting in the browser. Also, on which version of Chromium is the Yandex browser based on? Etc. etc. Details please.

**Comment by zummuz** [comment]
I'm sorry to interrupt. @bibihh If you care about privacy you better not to use Амиго/Yandex/Комета browsers.

**Comment by bibihh** [comment]
The latest version of Yandex is based on Chrome 41.0.2272.118. I tried version UblockOrigin ver 1.1.1 and ver 1.2.0. So when the option "Prevent WebRTC from leaking local IP addresses" is enabled in Ublock and when I make tests I see my local ips leaking from the browser. When I test again Ublock same versions in Chrome 43, 44 or 45 that option is working like should be.

**Comment by bibihh** [comment]
@zummuz what's the reason for your suggestion?

**Comment by gorhill** [comment]
> based on Chrome 41.0.2272.118.

The answer is at [the link aside the setting](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address), which providing further information:

> Caveats ... Chromium-based browsers ... The feature works only on version 42 and above

**Comment by zummuz** [comment]
@bibihh Wireshark, company's reputation, forum discussions, type of distribution (not open source). You don't agree?
