### ISSUE TITLE
Remove element picker overlay/background?

### ISSUE THREAD

**Issue by jykata** [gorhill/uBlock#826]
When I use the element picker the page will go black, is this the intended functionality? and if so would it be possible to remove it so it's easier to see what it is being highlighted.

Here's a screenshot on the github new issue page for example: http://i.imgur.com/LQcjq1K.png

I'm not sure if this is related to my windows(7)/firefox(41.0.1) theme or settings so I apologise if that's the case.
Thank you for this excellent addon.

**Comment by gorhill** [comment]
You probably have user styles overriding uBlock Origin's own styles. See <https://github.com/chrisaljoudi/uBlock/issues/806>.

**Comment by jykata** [comment]
That was indeed the problem. Unfortunately it's still very difficult to see with the dark overlay in place but that is probably down to several tools I use which change the browser background colour/text & adjust the monitor colours to avoid eye strain and remove blue light. 

Thanks again for the addon and your help.
