### ISSUE TITLE
Dynamic filtering rules for images

### ISSUE THREAD

**Issue by Ineluctable** [gorhill/uBlock#829]
Hello! First off, I should let you know I'm using uBlock's advanced mode, and this issue pertains to that.

On certain forums, I'd like to whitelist third party sites where avatars are hosted, more specifically, their images. For a while, I'd just whitelisted the sites in the GUI menu, and that was fine, but I'd wondered if there was a way to restrict it to just allow images...and wonderfully, there is! :D Or seems to be, if I can get it to work.

I followed the instructions [here](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax), and tried to alter my rules for the 3rd party image sites to only allow images, but uBlock doesn't seem to accept the altered rules.

**Accepted:** examplesite.com imgur.com * noop
**Not accepted:** examplesite.com imgur.com image noop

Is there something I'm doing wrong? If so, how could I go about achieving my desired result (allowing only images from those third party websites)?

Thanks!

**Comment by gorhill** [comment]
> wondered if there was a way to restrict it to just allow images

That's beyond the scope of uBlock Origin. uMatrix is what you are looking for, it allows that kind of granularity.

**Comment by Ineluctable** [comment]
Okay, thank you. I'll start looking into the process of switching from uBlock to uMatrix!
