### ISSUE TITLE
Panel bug when icon in Firefox panel

### ISSUE THREAD

**Issue by justabrah** [gorhill/uBlock#83]
Hey, there is an error like this.?
![untitled](https://cloud.githubusercontent.com/assets/12006096/7215112/ef8eb07c-e5f1-11e4-8a23-f7abae8efbc2.png)

**Comment by crisalis** [comment]
Yes, it is a known problem:
https://github.com/chrisaljoudi/uBlock/issues/505
https://github.com/chrisaljoudi/uBlock/issues/730
https://github.com/chrisaljoudi/uBlock/issues/857
https://github.com/chrisaljoudi/uBlock/issues/1015

**Comment by hairycactus** [comment]
Mine is as shown in the following screenshot.

1. With dynamic filtering inactive, but there is a large white space on the RHS of the dropdown panel with blue button.
2. Clicking on the title about the blue button opens the Dashboard UI in a new tab, which looks fine to me.

![ff-ublock0v0 9 4 4-hambugerpanel-19apr15](https://cloud.githubusercontent.com/assets/9943769/7217385/63f13aa8-e65a-11e4-84f6-a8e3f74f8eb8.png)

**Comment by SW1FT** [comment]
Fixed here: https://github.com/chrisaljoudi/uBlock/commit/82b97760db6665411ccad109e477c6e56b822805

**Comment by gorhill** [comment]
Need to fix positioning of ruleset tools as well.
