### ISSUE TITLE
Noop dynamic filter does not work at all.

### ISSUE THREAD

**Issue by enomat** [gorhill/uBlock#831]
Example:
- open github.com
- set global or local noop all
- open logger
- you will see that *noop* rule does not work at all, **static filters are still able to block items**, (and in the logger the items should have gray background, indicating the noop filter, but they are not gray, ...)

Block and allow rules work.

Tested on Firefox ESR 38.3.0 and Firefox for Android 42.0b4 .

**Comment by vzjrz** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

Noop does exactly that, let stuff through dynamic filtering but block stuff in static filters.

**Comment by enomat** [comment]
Yes, in theory, but somewhy it doesn't disable the static filters at all. I'ts a bug.
