### ISSUE TITLE
mc.yandex.ru cookie

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#836]
0) Enable "Block 3-rd party cookie" in [Chromium win64](http://chromium.woolyss.com/download/) settings
1) Enable Fanboy-Ultimate list (which contains `||mc.yandex.ru^`)
2) Install [this](https://chrome.google.com/webstore/detail/musicsig-vkontakte/hanjiajgnonaobdlklncdjdmpbomlhoa) extension
3) go to http://www.kinopoisk.ru
4) mc.yandex.ru somehow installed a cookie

**Comment by publicarray** [comment]
I was unable to reproduce:
![screen shot 2015-10-17 at 4 35 03 pm](https://cloud.githubusercontent.com/assets/5497998/10557375/7de163e4-74ed-11e5-9167-161db6ab98dc.png)

Maybe you visited the site before without you setting mentioned above. I would delete all cached data and cookies and test again.

**Comment by mikhaelkh** [comment]
@publicarray You need to install [this](https://chrome.google.com/webstore/detail/musicsig-vkontakte/hanjiajgnonaobdlklncdjdmpbomlhoa) extension to reproduce the problem.

**Comment by publicarray** [comment]
> @publicarray You need to install this extension to reproduce the problem.

![screen shot 2015-10-17 at 4 51 08 pm](https://cloud.githubusercontent.com/assets/5497998/10557418/67bb5910-74ef-11e5-8c2d-10812e0361c8.png)

**Comment by mikhaelkh** [comment]
@publicarray use settings->content settings->all cookies and site data.

**Comment by publicarray** [comment]
I see. So installing the extension will set two 3rd party cookies.

**Comment by publicarray** [comment]
in the extension `scripts/background.js`

```js
 4448      chrome.runtime.onInstalled.addListener(function(a) {
 4449          console.log(a.previousVersion, "previousVersion")
 4450:     }), browsers.browserAction.setIcon("/images/icon/" + (parseInt(window.localStorage.icon) || 0) + "_48.png"), a.ajax("http://mc.yandex.ru/watch/26846286?page-url=http%3A%2F%2Fmusicsig.ru%2F");
 4451      var g = function(a, b) {
 4452              var c;
```
also in the manifest file the extensions is allowed to set cookies.

@gorhill I tried blocking all Behind the scene request at no avail also the ajax request above wasn't logged in the logger.

**Comment by gorhill** [comment]
I don't know  why @mikhaelkh opened an issue for this, we already discussed in [another issue](https://github.com/gorhill/uMatrix/issues/379#issuecomment-148822676) this was not possible for Chromium-based browsers to block network requests made by other extensions.

There is nothing uBlock can do, it'a a Chromium-based browser behavior.
