### ISSUE TITLE
Seamonkey extension store warning

### ISSUE THREAD

**Issue by kintpuash** [gorhill/uBlock#837]
On the Seamonkey add-on page:

https://addons.mozilla.org/en-US/seamonkey/addon/ublock-origin/?src=ss

I receive the following error, with the install button grayed out.:

>Not available for SeaMonkey 2.38

 Of course it installs fine regardless. 2.38 was released a few weeks ago.

**Comment by gorhill** [comment]
> Of course it installs fine regardless.

Ok, I bumped the max version to 2.38 in 230639d959468fc67c7ca5cf0249009eee0853b8.
