### ISSUE TITLE
The script tag filters ignore the whitelist

### ISSUE THREAD

**Issue by enomat** [gorhill/uBlock#838]
The specific inline script filters are constantly enabled, even if the site is whitelisted.

This is a good site for testing:

http://www.tizag.com/javascriptT/javascriptredirect.php

On that page scroll down and click this link: "Time Delay Redirect"
That page has a redirect script, delayed with 5 seconds.

I use this filter to block the redirect script:

tizag.com##script:contains(delayer)

But it blocks the redirect even if I whitelist the page.

**Comment by gorhill** [comment]
Need to reopen the issue, as the current solution won't work for inline script tag filters inside frame elements.

**Comment by gorhill** [comment]
Current implementation of `script:contains` can't be implemented with WebExtensions API, so I won't work on the current implementation of `script:contains` for Firefox legacy.
