### ISSUE TITLE
Blocked from uBlock Origin for unknown reasons

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#839]
Please read https://github.com/chrisaljoudi/uBlock/issues/1558 @gorhill.

**Comment by gorhill** [comment]
Reason was that I did not want to be flooded with most issues like these:
<https://github.com/chrisaljoudi/uBlock/issues?q=author%3Adavidhedlund+sort%3Acreated-asc>.

There might be a couple of valid issues in there, but most of them are non-issues, questions, duplicates, or feature requests. Merely having to _just respond_ (with possibly endless back and forth) to all of these quickly become a significant burden taking away at the time I allocate to this project.

**Comment by flyingzebras** [comment]
@gorhill Ok. However, it seems like [Important: Add "Global" and "Local" to the GUI](https://github.com/chrisaljoudi/uBlock/issues/1371) is missing in uBlock Origin despite it being based on uBlock 0.9.5.0. How come?

**Comment by gorhill** [comment]
uBlock Origin is not "based on" uBlock 0.9.5.0 or any version -- the two versions _diverged_ starting at 0.9.3.0. I don't like the word "based on" because from my point of view I have just kept developing it without interruption since June 2014.

**Comment by flyingzebras** [comment]
@gorhill I suggest that you state that somewhere else too.

**Comment by Dashed** [comment]
@gorhill Just a suggestion. Some repos have a bot (example: https://github.com/eslint/eslint/issues/4174#issuecomment-148864914) to deal with some of these issues. This can get folks to be actually aware of the [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) guidelines despite having a header for it shown on the 'new issues' page.

**Comment by steckerhalter** [comment]
As a matter of fact it looks like **uBlock** is based on **uBlock Origin** and not the other way around, the original repo is gorhill/uBlock, look at the git history from chrisaljoudi: https://github.com/chrisaljoudi/uBlock/commits/master?page=3

from some point on chrisaljoudi was not contributing to this repo anymore but started to develop on his own. the last commit on chrisaljoudi's fork was two months ago. contrast this to gorhill's original version here where development is steady and commits are made every day

**Comment by publicarray** [comment]
> As a matter of fact it looks like uBlock is based on uBlock Origin and not the other way around

according to [github](https://github.com/gorhill/uBlock/commits/master?page=95) uBlock started by Raymond Hill (@gorhill) on [23 June 2014](https://github.com/gorhill/uBlock/commit/182cd059e2cf1c63568c16aa77d66a239304bd6a). Later ownership was given to chrisaljoudi. Immediately after that gorhill forked uBlock to form uBlock Origin. You can read more about it here: https://en.wikipedia.org/wiki/UBlock

**Comment by steckerhalter** [comment]
@publicarray ok, thanks for explaining
