### ISSUE TITLE
Someone can explain me the popup window?

### ISSUE THREAD

**Issue by AminaG** [gorhill/uBlock#841]
I have read the documenation and didn't found an answer.
![image](https://cloud.githubusercontent.com/assets/3584317/10563253/873b4060-758b-11e5-9d12-bc05e2c9e19a.png)

On each resource I see 8 buttons. From red to green. 4 on the left and 4 on the right?
What are the buttons doing?

I am understanding what mean block, and whitelist. But why so many buttons?

**Comment by SW1FT** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

Please don't add question-type issues when you can just get your answer from the documentation.

**Comment by AminaG** [comment]
Sorry.
Where is the best to place to ask questions about this extension?

**Comment by SW1FT** [comment]
I would say reddit ([/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)), but you can find more information in the [documentation](https://github.com/gorhill/uBlock/wiki).

**Comment by gorhill** [comment]
There are not buttons, they are just indicators to give an overview whether network requests were all blocked, allowed or both -- somewhat redundant to the pluses and minuses.
