### ISSUE TITLE
`/\.js$/` does not work

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#842]
As reported in AMO's feedback section:

> When using regexes it seems the $ option symbol interferes with the regexes. For example /\.js$/ does not work until I remove the $ but then I can't match the end of the string. Is this a bug, and any workaround?

**Comment by RoxKilly** [comment]
Would this work?
`/\.js.{0}$/`

**Comment by gorhill** [comment]
No. The parsing code just naively lookup the first `$` encountered, this is what I need to fix.

**Comment by gwarser** [comment]
This works:
`/\.js\u0024/$document`

**Comment by gorhill** [comment]
Yes, but if you  want to use the regex special character `$`, it won't -- that is the issue to fix.

**Comment by gorhill** [comment]
@gwarser the `$` is used as a special regex char in OP, not as a literal char.

**Comment by gwarser** [comment]
Ahhh yes. I tested too quickly. 

About this bug, I saw this earlier https://github.com/chrisaljoudi/uBlock/issues/1317#issuecomment-98083927
