### ISSUE TITLE
Pictures blocked www.dn.se (android only)

### ISSUE THREAD

**Issue by SuperPutte** [gorhill/uBlock#846]
I have ublock on both Firefox android and Firefox desktop versions.
On andriod with ublock enable, no pictures can be viewed on a specific media site: www.dn.se
"All" other similar media sites - no problem. And on the desktop version - no problem. Only the android version.
To read a newspaper site without pictures is annoying.... 
I have tried everything I guess, without overcome the problem. 
It is not a specific uBlock-issue, I encounter the same with ABP and similar adblockers, but nevertheless.

Question:  The particular site www.dn.se has been very active in trying to "fight adblockers", and apparently they seems to success on android-adblockers.  
Be course of this, I wonder if you could have a look on this "case".

**Comment by gorhill** [comment]
I see picture fine on Firefox for Android on that site. Just use the logger to find out why the pictures are blocked, that's the first thing to look at when to find out what blocks what.

**Comment by gorhill** [comment]
You will have to provide me more info:

- **All** uBO settings which differs from default ones (custom filters, rules, whitelist, etc.)
- Firefox for Android version, uBO version

**Comment by SuperPutte** [comment]
uBlock right out of the box, no changes. Version the latest, currently 1.30, but also previous versions had the same issue.
Firefox Android, always the latest stable version installed, currently 41.0.2.

I have noticed this issue since at least 6 months. As I mentioned before it is not just uBlock, also ABP.

**Comment by gorhill** [comment]
I tried again, and the images load fine. Only notable quirk is that I got two warnings telling me the site was unresponsive due to some javascript on it. I click to _Continue_, i.e. not preventing the script from running. Eventually the site fully loaded.

**Comment by SuperPutte** [comment]
Hi again, I understand you can't fix it if you can't reproduce my problem.
However, I have solved it myself with a CSS-style. Link https://userstyles.org/styles/120290/dagens-nyheter-mobilversionen
Have a look if you are interested.
I had to disable uBlock on this particular site, and use my CSS + ADAway to get rid of all commercials.

**Comment by gorhill** [comment]
I see you use `mobil.dn.se` in your user styles -- not sure this is what I was being served when I tried on Firefox for Android. So if I use this using Chromium mobile emulator (FF one's doesn't spoof UA string which causes `mobil.dn.se` to be redirected to `www.dn.se`), I can reproduce. Will see why this happens now that I can reproduce.

**Comment by gorhill** [comment]
Ok, this is a 3rd-party filter list issue. The filter `-adap.` in EasyList causes the script `http://mobil.dn.se/Static/Scripts/dn-adap.min.js?v=2` to be blocked. This script contains the necessary code to lazily-load the images. You need to report to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Workaround filter: `@@||mobil.dn.se/Static/Scripts/dn-adap.min.js$script`.
