### ISSUE TITLE
Not keeping any changes?

### ISSUE THREAD

**Issue by MrTorch** [gorhill/uBlock#847]
For some odd reason uBlock stopped keeping changes I make to it. If I block an element on a page or add a new rule or filter it won't save those changes. If I use the "picker" tool it will keep the elements I blocked, blocked until I restart Firefox, but then I have to add them again. Not sure if it's from a new updated Firefox or what. I'm on Firefox ver 41.0.2, the latest uBlock (tried uninstalling it and reinstalling it), and Mac OSX. uBlock is still functioning at its default settings though.

**Comment by RoxKilly** [comment]
Is the issue limited to uBlock?  For instance, try a couple of changes:
1)  go to `about:preferences` and temporarily change your homepage. 
2) go to `about:config` and temporarily change a setting (the first setting, `accessibility.accesskeycausesactivation` could be changed by double-clicking it)

Then restart the computer and check whether both changes persisted.

**Comment by MrTorch** [comment]
It's not limited to uBlock. It kept the change I made to the boolean and to the homepage. Do you need any logs or anything?

**Comment by RoxKilly** [comment]
I'm having trouble understanding your feedback. You original post said uBlock stopped keeping changes. Your latest post said "it's not limited to uBlock...it kept the change I made to the boolean"    "It's not limited to uBlock" gives the impression that the problem also occurs outside of uBlock, but your 2nd sentence gives the impression that it does *not* occur outside of uBlock.  Please clarify

**Comment by gorhill** [comment]
All uBO settings are saved into a SQlite file on disk. See location of such file [here](https://github.com/gorhill/uBlock/tree/master/dist#firefox). If uBO is for whatever reason prevented from writing to that file, then settings won't be persisted.

Now you need to investigate if this is the issue, and why it happens, this is not something I can do for you remotely.

**Comment by MrTorch** [comment]
I'm so sorry RoxKilly. I didn't mean to put the "not" there. It was probably late at night lol. It *IS* limited to uBlock.

For me the file was located in-
/Volumes/User/Library/Application Support/Firefox/Profiles/v1g2lepa.default/extension-data/

and then the file was named "ublock0.sqlite".

Strangely, it says the file was last modified on Oct 10th even though I've changed settings a bunch since then. To give you a better example of what's happening.

On SkypeForWeb, there's a small banner that pops down if you don't have their calling plugin installed. I can block it with the picker tool and reload the page and it will be gone. Then if I restart firefox and load Skype's web page again the banner is there again. So the picker tool work per firefox session, however if I go into the settings page for uBlock and make a change and then reload the page the changes I made won't apply at all.

If that doesn't make sense I could try recording a video of it and uploading it to youtube if you'd like. I don't think it's a permission based problem, but I will login into my admin account and see if I can update uBlock settings there instead.

**Comment by gorhill** [comment]
> If that doesn't make sense I could try recording a video

I believe you, no need for this. You say the SQlite file was last modified October 10, that's a red flag, it should be modified everytime a new setting is saved -- including a custom filter. First thing to check would be that the file is not read-only for the current user session. I don't know OSX, so maybe somebody has some insight on this. What is the size of the file? Could there be a limit on FF/OSX for the size?

**Comment by MrTorch** [comment]
File size is 7.2mb and my user was set to read & write. However, I changed all users on the computer to be able to read and write as well. It's still not working though. If I go to 3rd party filters and check one of them to add another filter and then hit "apply changes" -- it instantly unchecks all the changes I made.

**Comment by gorhill** [comment]
> it instantly unchecks all the changes I made

This means change could not be saved to storage: when you click _Apply changes_, changes are written to storage. Then when all filters reload, the set of selected filter lists is read back, and apparently it's the same as it was before in your case.

Be sure that the SQlite file used by uBO is actually the one appearing in your home folder. Is it possible uBO ends up using an SQlite file somewhere else on the file system -- for which write permissions are not allowed?

**Comment by gorhill** [comment]
Also, does the dev console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>J</kbd>) report anything when you try to change a setting?

**Comment by MrTorch** [comment]
The dev console didn't show anything when I made changes in ublock. It only showed the start of downloads when I clicked "update filters".

Also, I'm on the latest firefox and this is the only change that was made since October 10th (the last time the sqlite was modified). https://www.mozilla.org/en-US/security/advisories/mfsa2015-115/ That doesn't seem like something that would break the add-on though. But if you think it would help, I could try downgrading my firefox.

**Comment by gorhill** [comment]
Back-up your uBO settings, rename you SQlite file to something else and restart Firefox. See what happens. Is there a new `extension-data/ublock0.sqlite` file created?

**Comment by MrTorch** [comment]
That fixed it. It created a new ublock0.sqlite file and I can make changes and exit and reopen firefox now and the changes I made persist. I think the original file might've gotten corrupted or something. Probably a user error since I've had quite a few hard shutdowns recently. 

Thanks for all the help! Great add-on by the way. Way better than ABP.

**Comment by gorhill** [comment]
I will be linking SQlite file issues to each others. So here:

- #815
