### ISSUE TITLE
Sync download buttons not showing up

### ISSUE THREAD

**Issue by hambon** [gorhill/uBlock#848]
First I must say... gorhill you are my hero. Two very nice products I use everywhere, uBlock0 and uMatrix. (http switchboard long before)

My problem today is that the download sync icons in FF are not showing up. New box, Win10, latest FF. In Chrome everything works, but that surely has little to do with anything other than I cross copy my FF and Chrome settings for both add-ons, as I use both browsers. Was using 1.3.0, upgraded to 1.3.1rc1 just in case.

I've blown away the profile, resynced, everything comes across, but once I enable the cloud setting, nothing. I've successfully used this on several machines several times since you added that feature. 

I'm wondering if you have any thoughts as to how to track this down. Like I said, everything else synchronizes just fine.

**Comment by gorhill** [comment]
> New box, Win10, latest FF

That's the problem. New install of uBO will void cloud storage content, [a Firefox caveat](https://github.com/gorhill/uBlock/wiki/Cloud-storage#firefox-browsers):

> A new installation of uBlock Origin will cause cloud storage data to be blanked.

**Comment by hambon** [comment]
Hahahaha... an new install of uBo ANYWHERE (meaning on a different machine)... I just dismissed that as if you replace it on the same box.

Not an unfixable problem as I have several boxes with the right info I can re-upload from.

The reason I'm dying laughing here... so you keep your money at... Bank A... and you use your ATM card at Bank B... that zeros your account. So sorry. 

I'm sure it's my bad and I need to read up on the reasoning behind this. Our friends at Mozilla do not usually do dumb things for a reason.

**Comment by gorhill** [comment]
> need to read up on the reasoning behind this

It's a bug. I added info in the wiki about it being fixed in FF 43.3.

**Comment by hambon** [comment]
Out of curiosity... if I set up FF, sync it with a clean profile (create a new FF account for this purpose) and then switch back to the 'real' sync account... do you think that would prevent this?

**Comment by gorhill** [comment]
> do you think that would prevent this?

I don't think so. I suppose each profile has its own uBO entries, and if these are not present, uBO will create them -- a requirement for FF Sync to work, the entries need to exist even if empty. That's (my understanding of) the FF bug, it will make use of these empty entries.
