### ISSUE TITLE
Clearer description for "Prevent WebRTC from leaking..."

### ISSUE THREAD

**Issue by RalfJung** [gorhill/uBlock#851]
I recently enabled the uBlock option "Prevent WebRTC from leaking local IP address", because I believed that this is exactly what it is doing: Somehow making sure that WebRTC does not leak my IP address - of course, it goes without saying, that the rest of WebRTC keeps working as expected.

A few days later, to my surprise, I noticed that Jitsi Meet stopped working. It took me half the day to remember this setting, and to figure out that by "Prevent", the plugin actually means "Completely disable WebRTC". That should be made much clearer in the description. The way it is described now, it's not at all clear that there are any downsides to the way uBlock does this "prevention". Really, this is a complete misnomer.

I suggest something like "Disable WebRTC, to prevent leakage of local IP address".

**Comment by Snapy** [comment]
There is a [link] (/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address) explaining what it does which should be displayed after the setting (see #773).

**Comment by RalfJung** [comment]
Even that page does not clearly state that WebRTC is *completely disabled* - so, it doesn't say what the option actually does. This can only be inferred from the FAQ concerning Firefox Hello.

**Comment by Snapy** [comment]
Agreed. gorhill should update the wiki page.

**Comment by gorhill** [comment]
The wiki page was updated.
