### ISSUE TITLE
First Tab - Reload first or what went wrong?

### ISSUE THREAD

**Issue by Laserfischen** [gorhill/uBlock#854]
Hello,

what's up with uBO on sites like www.arcor.de ? I have to reload the page after initial loading it to get rid of the ".jpg-ads" shown first (located upper right-hand corner and center). 
For example: http://www.arcor.de/img/ZTlDN7kI6zmTDal.jpg 

Steps to reproduce:
1. Open an absolute new FF session.
2. Open www.arcor.de in the first tab (without loading any pages before!!) -> You can see the ads.
3. Press reload button -> The ads are gone at all.

Additionally: If another website was loading in the first tab before launching www.arcor.de, no ads are showing, too. 

Settings:
Version: uBO 1.3.1 in nightmare mode -> btw. if not in nightmare mode (say the default setting - all allowed first) the ads will never be gone even by reloading!
Browser: Iceweasel 38.3 ESR and FF 41.03 (both tested with a clean home folder, no other addons installed)
OS: Debian

Thanks for your effort!

**Comment by publicarray** [comment]
Can you try this filter?
`arcor.de##script:contains(uabDetect)`

@gorhill what is the best practice with creating these filters? one that is more future prof and might brake other things or one that is based of a variable name? E.g `arcor.de##script:contains(DOMContentLoaded)` vs `arcor.de##script:contains(uabDetect)`

**Comment by publicarray** [comment]
> For example: http://www.arcor.de/img/ZTlDN7kI6zmTDal.jpg

The link will change every time you visit the website.

**Comment by Laserfischen** [comment]
arcor.de##script:contains(uabDetect)

I've tried this filter... no changes. 
I think you won't get the point correctly, because after a reload the ads are gone... and, as I've mentioned before, if another page was loaded in this tab before, also.

The link will change each time I visit the page... sure it does. What is the essence you want me to know?

Another example for this behavior is www.bild.de (crap webpage, I know, only for test purposes). There will comes up the "NOSCRIPT is aktivate" message... and if you follow my steps above... you will get the real website content instead.

**Comment by publicarray** [comment]
Sorry I understood but I did not try to reproduce. I think this might happen because the extension is not fully loaded (I can only confirm if I set http://www.arcor.de as my home page and I restart the browser)

**Comment by publicarray** [comment]
Ok, I can confirm with about:blank and about:home as my home page and manually entering the website.

**Comment by Laserfischen** [comment]
Ok, if you open up the browser and won't do nothing at all for about one minute...  maybe time enough to load uBO at all... and try again like before, the problem persists nevertheless.

**Comment by gorhill** [comment]
>  I have to reload the page after initial loading it to get rid of the ".jpg-ads" shown first (located upper right-hand corner and center). 

If these ads are not removed, it means they are not taken care of by EasyList. Now, these self-defacing ads are not easily removed -- uBO introduced an inline script tag filter to deal with them at the source.

Now, no extensions on FF can guarantee that it will be up and running **before** the content of a tab loads. This is out of control of uBO or [any other extensions](https://adblockplus.org/forum/viewtopic.php?f=1&t=22906). In this case when this happens, uBO will try to clean the page after it has loaded.

This works well for most cases. One thing which help is to make sure the extension load as fast as possible, and [this work has been done for uBO](https://github.com/gorhill/uBlock/wiki/Launch-and-filter-lists-load-performance). ([demo](https://www.youtube.com/watch?v=BpypOeK10N8))

However in your case, by the time the page loads at launch time, if uBO was not up and ready, the javascript has already been executed, and there is no way to retroactively "un-execute" javascript to enforce inline script tag filters.

> Ok, I can confirm with about:blank and about:home as my home page and manually entering the website

This is another issue, known: <https://github.com/chrisaljoudi/uBlock/issues/531>.

**Comment by gorhill** [comment]
> Ok, I can confirm with about:blank and about:home as my home page and manually entering the website

Actually I guess I am not understanding the issue. What is the problem here? (steps) If I type `focus.de` after launch with a default `about:blank` page, it works fine.

**Comment by Laserfischen** [comment]
Try manually fill in www.arcor.de or www.bild.de . On other sites this behavior doesn't show up as far as I've investigated yet.

**Comment by publicarray** [comment]
Can you try www.arcor.de with ?
```
www.arcor.de * 3p block
www.arcor.de * inline-script block
```

**Comment by gorhill** [comment]
> Try manually fill in www.arcor.de

Tried it and it worked fine. How many extensions do you have? It could be that uBO loads late because of all the other extensions in front in the queue line.

**Comment by Laserfischen** [comment]
As I've mentioned above: 
Browser: Iceweasel 38.3 ESR and FF 41.03 (both tested with a clean home folder, no other addons installed)

**Comment by Laserfischen** [comment]
Remember to start a new FF session with about:blank set as homepage and no othe website was ever loading before before the test.

**Comment by gorhill** [comment]
> Remember to start a new FF session with about:blank set as homepage and no othe website was ever loading before before the test.

That's what I did, I can't reproduce.

**Comment by Laserfischen** [comment]
Hmm... publicarray can reproduce it and I've tested it additionally on a Win7 machine with FF 41.03. I can reproduce it again.

**Comment by gorhill** [comment]
I am on Linux here, uBO loads in a fraction of second. Could it be your uBO takes quite long to load?

**Comment by Laserfischen** [comment]
I'm on linux, too and uBO/FF loads nearly under 1 second (I've got a SSD, btw).

**Comment by publicarray** [comment]
Hm. for me I can't reproduce once I updated the filter lists... sorry

**Comment by Laserfischen** [comment]
Ok, thanks...

**Comment by gorhill** [comment]
> uBO/FF loads nearly under 1 second

So just to be sure, you are saying that if you load the page manually, after uBO is fully loaded, the inline script tag filter won't work?

**Comment by gorhill** [comment]
@publicarray 
> what is the best practice with creating these filters?

To answer your question: `DOMContentLoaded` is too generic if there are narrower pattern in there. There is a point where too generic becomes equivalent of just plainly blocking all inline scripts -- something which can be done more efficiently using an `inline-script` filter or rule. I added `arcor.de` to the current inline script tag filter `uabInject` already in uBO filter list.

**Comment by publicarray** [comment]
To reproduce I disabled the uBlock filter list: https://youtu.be/2p_dIbwNnIM

> I added arcor.de to the current inline script tag filter uabInject already in uBO filter list.

Thanks, I just noticed and that is why it seems to have fixed it for me.

**Comment by Laserfischen** [comment]
For me, I don't have to disable the uBO Filters shown in this YT video to reproduce it... but the effect shown is exactly what I mean. :)

**Comment by gorhill** [comment]
@Laserfischen 

Ok, I get it, after reading very carefully your first comment.

> uBO 1.3.1 in nightmare mode -> btw. if not in nightmare mode (say the default setting - all allowed first) the ads will never be gone even by reloading!

First, `arcor.de` was not in uBO's filter list, I just added it a few minutes ago. Now the real issue reported in the end here is the fact that your dynamic filtering inline script rule (from nightmare mode) is not enforced if you type the URL directly in the address bar on a blank page. I am able to reproduce this. The logger does not report any entry for `inline-script`, so it's as if the response headers were not passed to uBO. (it could be related to https://github.com/chrisaljoudi/uBlock/issues/531 I mentioned above).

**Comment by Laserfischen** [comment]
Ok, sounds legit. 
As a workaround I have to get a homepage tab which is not about:blank to bypass "this bug" until it might get fixed? 
I can deal with it...

Thank you very much.

**Comment by publicarray** [comment]
@Laserfischen Did you try updating the filter lists. For me It solved the problem on arcor.de

**Comment by Laserfischen** [comment]
@publicarray Yes, I have but no it doesn't. :)

**Comment by gorhill** [comment]
Confirmed to be a bug in uBO. The whitelist flag is not updated appropriately in some case when the location of the tab changes, or something resembling this. Will fix asap.

**Comment by Laserfischen** [comment]
Ok... meanwhile my workaround is to activate uBO on the about:blank page manually. So everything works fine and I feel much more secure since about:blank is observed by uBO now! :)

Thanks both of you!

**Comment by gorhill** [comment]
Fix in [latest dev build](https://github.com/gorhill/uBlock/releases).

**Comment by kylebshr** [comment]
I found this page from Google — I have a similar issue. When I load Twitter, uBlock usually works, but sometimes it takes a reload before it blocks the ads and custom elements I have blocked. I'm on Safari 9.0.2 with uBlock 0.9.5.2. This issue has been around for a while though.

**Comment by gorhill** [comment]
> I'm on Safari 9.0.2 with uBlock 0.9.5.2. This issue has been around for a while though.

You are not using uBlock Origin, you are using [this uBlock](https://github.com/chrisaljoudi/uBlock).
