### ISSUE TITLE
Plz Help

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#855]
hi,

plz i need help to block video ads on www.chip.de

example:
http://www.chip.de/video/Diese-Zurueck-in-die-Zukunft-Gadgets-haben-es-in-die-Realitaet-geschafft-Video_84560974.html

big thx

**Comment by gorhill** [comment]
I am not a filter list maintainer -- see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). Your query is best placed with maintainers of EasyList Germany: <https://forums.lanik.us/viewforum.php?f=90>.
