### ISSUE TITLE
[Firefox] Branch switching remove all cookies

### ISSUE THREAD

**Issue by UK992** [gorhill/uBlock#856]
Switching Firefox from branch Nightly (44) to Beta (42) cause delete all cookies, but switching from Beta to Nightly everything ok.

Tried with clean profile and only uBO installed and is same behavor.

This bug exists the last 2-3 weeks.

**Comment by gorhill** [comment]
uBlock does not touch any cookies. Did you try with clean profile and **no** uBO?

**Comment by UK992** [comment]
This problem disappears when uBlock is disabled or not installed.

**Comment by gorhill** [comment]
Firefox Beta and Nightly do not overlap on disk, they are like two different installations -- so claiming that cookies from Nightly are removed by Beta does not make much sense if these are two different installations.

**Comment by Betsy25** [comment]
Switching FF branches using the same profile is the perfect recept for disaster.
Don't blame any add-ons for that, educate yourself that a lot under-the-hood changes are in place when using the same profile with different Firefox branches.

If you do want to use different branches, at least have them have their own profile.

**Comment by gorhill** [comment]
@UK992 Are you using the same `.mozilla/firefox/` (or whatever it is in your OS) config location for both Nightly and Firefox?

**Comment by UK992** [comment]
yes.... since firefox 4 and until now no problems with shared profile...

**Comment by gorhill** [comment]
> since firefox 4 and until now no problems with shared profile...

I am not aware at all that Firefox promise forward-compatibility for profiles -- i.e. using newer profile data with older Firefox versions -- which is what you are trying to do with using a Nightly profile with a Firefox Beta version. I don't even see how this can be blame on uBO -- which has nothing to do with the cookies in your browser.

**Comment by UK992** [comment]
It is weird... idk why but somehow uBlock cause cookie get delete... anyway i created seperate profile for Nightly and prevent this happend again...
