### ISSUE TITLE
annoying ad which can be killed with inline script blocking

### ISSUE THREAD

**Issue by zummuz** [gorhill/uBlock#857]
Hi,
There is site http://blockadblock.com/ with blocking popup which appears in 5-10 seconds. Just go there with default filter lists. 
That annoying script can be blocked with `blockadblock.com##script:contains(BlockAdblock)`. 
Also the site owners are spreading that script: http://blockadblock.com/blockadblock_basic_script.php .
Maybe there is a way to block it by adding to *uBlock filters* with something like `*##script:contains(MostSuitableUnicArgmentFromThatScript)` at least for Firefox users?

**Comment by gorhill** [comment]
I really don't care "un-breaking" this site, it's meant to be used by visitors who despise content blockers.

**Comment by zummuz** [comment]
>I really don't care "un-breaking" this site, it's meant to be used by visitors who despise content blockers.  

I don't need/like this site, I saw on reddit someone said uBlock doesn't work on it. It's like testing case. But main thought was: that filter for inline script should kill the popup on sites which use the "blockadblock" script from this site.
>Generic inline script tag filters are not supported, due to efficiency concerns.

What I was interested in.

**Comment by gorhill** [comment]
Try this: `blockadblock.com##script:contains(DMCA)`. But as said, I won't bother put this in uBO's filter list.
