### ISSUE TITLE
uBlock Origin wrecks context menu

### ISSUE THREAD

**Issue by Mr6686** [gorhill/uBlock#858]
Since 1.3.0rc4, when restoring session with multiple windows, uBlock Origin wrecks context menu except for the first window.

**Comment by gorhill** [comment]
Total lack of details, assuming FF41. Unable to reproduce "wrecks context menu except for the first window".

**Comment by gorhill** [comment]
Closing as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by Mr6686** [comment]
Sorry, I began to fill the issue but after some tests I couldn't reproduce this bug on a clean profile so I stopped there. Still searching what cause this.

**Comment by Mr6686** [comment]
So I finally find that HTTPS-Everywhere 5.1.1 cause this issue in conjunction with uBlock Origin 1.3.0rc4

**Comment by Mr6686** [comment]
Firefox 41.0.2, Windows 7 Pro SP1
Normal Context Menu
![normalcontextmenu](https://cloud.githubusercontent.com/assets/8061617/10719647/ed713b58-7b8c-11e5-8f0a-e23c7f06fae6.png)
Wrecked Context Menu
![wreckedcontextmenu](https://cloud.githubusercontent.com/assets/8061617/10719648/ed7424ee-7b8c-11e5-90fa-fd30c6b74ee4.png)

**Comment by Mr6686** [comment]
No problem with version 1.3.2

**Comment by gorhill** [comment]
Duplicate of #906.
