### ISSUE TITLE
[Suggestion] Provide visual cue for temporary rules

### ISSUE THREAD

**Issue by WyohKnott** [gorhill/uBlock#86]
(If you don't accept Pull Requests or Features Requests, can we at least ~suggest~ some?

Currently, when setting up some temporary rules for a website, the popup displays a padlock to validate these changes definitively. However there is no way of telling which rules are the temporary ones directly from the popup panel: which one has been changed from its original state and therefore will be committed when I click on the padlock? Providing a visual cue, like a special border colour, would allow to review these temporary rules before validating them.

My work on this suggestion: https://github.com/WyohKnott/uBlock/tree/temp-rules
Visual: http://i.imgur.com/ViNYL87.jpg

**Comment by dungsaga** [comment]
another method is to show round border on temporary rules
![round borders](http://i.imgur.com/cgavmTo.png)
