### ISSUE TITLE
Simplest way to allow a family of URLs?

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#862]
FF 41
uBlock.0 1.3.1
Windows 7

I use dynamic filtering with the following rules: `* * 1p-script block` `* * 3p-frame block` `* * 3p-script block` `* * inline-script block`.  When a site requires JS to work, it very often relies on JQuery, most often from a Google CDN.  I'd like to find a way to white-list these scripts from all domains. I envision that most of the time, they will not be run, but when I enable 1st-party scripts and these external libraries are called, they will automatically be connected.

The Google hosted JS libraries can be found [here.](https://developers.google.com/speed/libraries/)  I am particularly interested in allowing the JQuery scripts. They are of the form `https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js`.  Problem is, there are a couple dozens of them for the different versions, so I have a two part question.

1) Is there a way to white-list a regex? eg: `^/http(s)?://ajax.googleapis.com/ajax/libs/jquery/[\d].[\d].[\d]/jquery.min.js$/`

2) If so, would uBlock's performance be faster if I manually entered all such links? in the `My Rules` tab instead of relying on a regex?

**Comment by publicarray** [comment]
Some common domains that I have nooped:
```
* ajax.googleapis.com * noop
* akamaihd.net * noop
* bootstrapcdn.com * noop
* cloudflare.com * noop
* google.com * noop
* gstatic.com * noop
* vimeocdn.com * noop
* wp.com * noop
* www.googleapis.com * noop
* youtube-nocookie.com * noop
* youtube.com * noop
* ytimg.com * noop
```

**Comment by RoxKilly** [comment]
Thanks. I don't want to open up the whole `ajax.googleapis.com` subdomain though, just the JQuery scripts.

By the way, doesn't `* google.com * noop` bother you? This allows any `google.com` hosted script from to run unless a static filter stops them.  Privacy-wise it makes me a bit uncomfortable.  `* cloudflare.com * noop` would worry me even more because any site can cache its scripts on Cloudflare so I would have no idea what kind of scripts I'm allowing with that rule.

**Comment by harshanvn** [comment]
> If so, would uBlock's performance be faster if I manually entered all such links? in the My Rules tab

I believe plain string must be faster..

> I don't want to open up the whole ajax.googleapis.com subdomain though

you can use dynamic URL filtering for that...
here is the rule i use..
<code>* https://ajax.googleapis.com/ajax/libs/jquery script noop</code>

**Comment by publicarray** [comment]
> By the way, doesn't * google.com * noop bother you? This allows any google.com hosted script from to run unless a static filter stops them. Privacy-wise it makes me a bit uncomfortable. * cloudflare.com * noop would worry me even more

You raise a good point but I am probably not as paranoid. I prefer to have more websites that work rather than to add more rules. In other words in this case I prefer convenience over privacy. Another point is that I only nooped them. This means they're falling back to filter lists, which should block the majority of tracking scripts and other bad scripts.
P.S. Based on your comment have removed cloudflare.com from my dynamic rules for now. :tada:

**Comment by RoxKilly** [comment]
@harshanvn that's interesting thanks. I'll try that.

**Comment by gorhill** [comment]
@harshanvn:

> You can use dynamic URL filtering for that. Here is the rule i use..
> `* https://ajax.googleapis.com/ajax/libs/jquery script noop`

Yes, that is the answer.

**Comment by RoxKilly** [comment]
Didn't know dynamic filtering looked beyond the domain. That's good news.  Is the path case-sensitive? In other words would `* https://ajax.googleapis.com/ajax/libs/jquery script noop` match `https://ajax.googleapis.com/ajax/libs/JQUERY`

**Comment by gorhill** [comment]
> Didn't know dynamic filtering looked beyond the domain

It's more accurately "dynamic URL filtering". See ["Overview of uBlock's network filtering engine"](https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock's-network-filtering-engine).

**Comment by RoxKilly** [comment]
For reference to anyone else who runs into this: here is the page explaining [Dynamic URL Filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-URL-filtering) in detail.

In the last paragraph of that page, @gorhill calls for a better example of the usefulness of Dynamic URL Filtering's granularity. The problem I ran into is a good case in point. I am not interested in allowing all scripts from `ajax.googleapis.com`, but JQuery is so common that instead of finding myself noop-ing that domain on site after site, I can create the relevant dynamic URL filters (http and https versions) and be done with it.
