### ISSUE TITLE
"Storage used" and ublock0.sqlite size growing

### ISSUE THREAD

**Issue by Zulen** [gorhill/uBlock#863]
Auto-update filters is disabled. 44 830 + 55 800 filters. File size (and "Storage used") is 8 mb, after some sites browsing the file size (and "Storage used") abruptly grows up to 12 mb. Certainly vacuum/compact don't reduce the size.

**Comment by harshanvn** [comment]
Not sure, if it is ok to have larger or smaller size. However, in my case it was 17 MB, after months of use.

Looked into it, and saw multiple entries starting with below name, in settings table -
<code>cached_asset_content://cache://compiled-filter-list:*</code>

Deleting all but latest and compacting, reduced the file size to <code>8.4 MB</code> down from <code>17 MB</code>.

![ublock sqllite](https://cloud.githubusercontent.com/assets/779630/10727156/02f9c1fe-7bae-11e5-8767-bf73a3de19f3.png)

**Comment by gorhill** [comment]
> after some sites browsing the file size (and "Storage used") abruptly grows up to 12 mb

Nothing out of the ordinary with this. It's [explained here](https://github.com/gorhill/uBlock/wiki/Launch-and-filter-lists-load-performance) what happens internally. Things that will cause storage space to grow:

- Filter lists from remote servers saved locally.
- Filter lists are pre-compiled into a format suitable for fast loading.
- uBO's ability to create a selfie of itself to storage, for even faster load.

**Comment by harshanvn** [comment]
@gorhill As shown in my above post, is there any limit on how many previous copies of <code>cached_asset_content://cache://compiled-filter-list:*</code> stored in <code>sqllite</code> file?

Would it be ok, if i delete some older entries?

**Comment by gorhill** [comment]
@harshanvn Did you look into the _3rd-party filters_  pane to see if there were unused filter lists with a "purge cache" button? First move to free on-disk storage would be to purge the cache of unused filter lists: this will remove the saved and the compiled version of a list.
