### ISSUE TITLE
[Firefox] popup did not unfold to full size

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#864]
![ubpopup2](https://cloud.githubusercontent.com/assets/886325/10729276/8cd5e620-7be8-11e5-814f-e35eaca19b3b.png)

Browser console:
`TypeError: location is null1 vapi-background.js:2413:18`

Not sure this can be reproduced this way, but after opening lots of pages this morning I hibernate my pc, and wake it up now with network disabled.

Restarting uBlock from add-on manager didn't fix this, but works fine in new window.

uBlock 1.3.2rc3, Fx 41.0.2 on Mint 17.2 64b

**Comment by gorhill** [comment]
> `TypeError: location is null1 vapi-background.js:2413:18`

Something is wrong, there is [no code at that line](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L2413) for rc3.

However, there is an older version of `vapi-background.js` which [matches that error message](https://github.com/gorhill/uBlock/blob/0eb0708a5b0e3a30cda630ba9d9441c423b32c8d/platform/firefox/vapi-background.js#L2413).

It looks to me like your Firefox still had old code from a previous version of uBO lingering in the browser and being executed.

**Comment by Betsy25** [comment]
Confirmed.
Firefox stable + Firefox nightly.
uBlock 1.3.2rc3

Needs a browser restart to show the popup.
http://i.imgur.com/8iI34LZ.png

**Comment by harshanvn** [comment]
Not sure, from which version (either rc1 or rc2), i updated to rc3 yesterday, and i saw similar distorted pop-up (did not check the console though).
After restarting every thing is back to normal.

FF v41.0.2

**Comment by gorhill** [comment]
There was an issue in rc2 which could prevent uBO from shutting down properly, fixed with <https://github.com/gorhill/uBlock/commit/da6c7b8b5e01cde43dcddf1650a120e35e4a05af> (the "LIFO" comment). This could be the cause.

**Comment by harshanvn** [comment]
Ok, Thanks You.

**Comment by gwarser** [comment]
>Something is wrong, there is no code at that line for rc3.

It's not first time Firefox is wrong about line numbers.

I just realized this may be Firefox problem: I see similar behavior in hamburger menu -> "?" (help button)

**Comment by gorhill** [comment]
> It's not first time Firefox is wrong about line numbers

As pointed out above, it does however matches exactly that of an older version of uBO. uBO rc2 and maybe the version before would throw an exception at uBO's shutdown time (which occurs when uBO is updated by FF) , this is probably what is behind the issue here. This was fixed for rc2.

**Comment by gwarser** [comment]
I will reopen if happens again.
