### ISSUE TITLE
can't log into my bank

### ISSUE THREAD

**Issue by zooko** [gorhill/uBlock#865]
When I have uBlock Origin enabled, this web page (my bank) doesn't do anything when I click the "login" button or hit enter:

https://www.elevationscu.com/

When I disable uBlock Origin, then clicking "login" or hitting enter results in getting logged in to my bank account.

**Comment by gorhill** [comment]
A filter in EasyPrivacy, `||googletagmanager.com/gtm.js?$third-party` is blocking the network request `https://www.googletagmanager.com/gtm.js?id=[...]`, whichbreaks the page.

Report to EasyPrivacy maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Meanwhile you can use this custom filter: `@@||www.googletagmanager.com/gtm.js$script,domain=elevationscu.com`.

**Comment by zooko** [comment]
Fixed: https://forums.lanik.us/viewtopic.php?f=64&t=26109
