### ISSUE TITLE
[Issue] Ability to skip interstitial ads like feed portal on CNN

### ISSUE THREAD

**Issue by akshetpandey** [gorhill/uBlock#867]
Not sure if this is a bug or a new feature request.

Example URL that shows the ad before redirecting to the actual website. It would be awesome if the plugin could directly go to the actual website.

http://rss.cnn.com/c/35492/f/676961/s/4afd2e34/sc/38/l/0L0Scnn0N0C20A150C10A0C260Chealth0Craise0Eminimum0Esmoking0Eage0Cindex0Bhtml0Deref0Frss0Itopstories/story01.htm

Here is what I see when I open the page,

<img width="1440" alt="screen shot 2015-10-26 at 2 45 00 pm" src="https://cloud.githubusercontent.com/assets/1213060/10743430/30043eb2-7bf0-11e5-8030-af44e1b5fc80.png">

Version: uBlock Origin v1.2.0
Browser: Chrome Version 46.0.2490.80 (64-bit)
OS: OSX 10.10.5

**Comment by elypter** [comment]
that would require a syntax with replacement support. ublock once had something like this. no idea if it will ever come back.

**Comment by gorhill** [comment]
I don't plan to support this.

The URL could be encoded in whatever manner and having to reverse engineer all encoding out there is way beyond this project, and even then I just wouldn't have the time for this -- I see this as a full time occupation for whoever may decide to do something about this.

**Comment by elypter** [comment]
i could imagine that jdownloader has done quite some work in this direction. but you're right that it is impossible to cover all encodings, not to speak of hashes with serverside lookup tables. however there are still many cases where a simple regex+urldecode+base64 would be enough.
I understand that you dont want to code this but i do not understand why you close the ticket if you think that it generally is desireable feature. closing it burries it. why not flag it with "too much work"? maybe someday someone reads over it and decides to implement it.
