### ISSUE TITLE
$popup doubts

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#869]
I would like to know how to block popups i know there is $popup thing for the custom rules but i cannot get the syntaxis right.

For example www.siteA.com opens www.SiteB.com pop-up how do I block that pop up from appearing?

I tried looking into the wiki but I couldn't find what I was looking for. is there an other place I can check  that is easy to understand without much knowledge or a more suitable place to ask for this?

**Comment by gwarser** [comment]
First try this: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-popups
If not work, use:
`||SiteB.com^$popup,domain=siteA.com` to block siteb.com when browsing sitea.com, or
`||SiteB.com/popup/url$popup,domain=siteA.com` to block specific popup url, or
`||SiteB.com^$popup` to block siteb.com popups everywhere

**Comment by gorhill** [comment]
Thanks @gwarser, this is the answer.

**Comment by rayman89** [comment]
Thanks a lot  @gwarser.
