### ISSUE TITLE
Suggestion : Have (Remove all temporay changes) icon like in uMatrix

### ISSUE THREAD

**Issue by z-v-n** [gorhill/uBlock#87]
Is it possible to have this function in uBlock pop up user-interface using dynamic filtering default deny.

**Comment by WyohKnott** [comment]
I am interested by this too.
Current proposal at https://github.com/WyohKnott/uBlock/tree/flush-changes

**Comment by gorhill** [comment]
https://github.com/chrisaljoudi/uBlock/issues/731#issuecomment-73964956
