### ISSUE TITLE
Relax the blocking of some Sourceforge websites

### ISSUE THREAD

**Issue by gouessej** [gorhill/uBlock#871]
Hi

I've read the paragraph about Sourceforge blocking:
https://github.com/gorhill/uBlock/wiki/Badware-risks#sourceforgenet

My own project isn't concerned (yet?) by those crapwares. My self-contained native application bundles are safe, my build machine is clean, you can check it by yourself:
http://sourceforge.net/projects/tuer/files/tuer/tuer-0.0.0/

The current blocking harms my project. I have worked on it for 9 years. I would accept the blocking without complaining if my project was concerned by those crapwares. I don't try to earn money, I don't show any ads. I plan to move to my own self hosted server but it takes some time. I'm willing to cooperate but I find the current blocking justified for numerous softwares on Sourceforge but too radical in my particular case. I disallow repackaging my software with ads, I protect my registered trademark, I do my best.

Please consider adapting the rule to stop blocking the website of my main project... and keep up the good work.

**Comment by weakptr** [comment]
The following filter would unbreak your project pages:
`@@||sourceforge.net/projects/tuer^`

**Comment by RoxKilly** [comment]
Best of luck with your project.

**Comment by gorhill** [comment]
@gouessej I believe you, but I do not have the time to research every single project on Sourceforge, so it's why the filters are named "Badware **risks**": it does not mean the content is harmful, just that as per the record, it has happened often -- and the warning is most beneficial to less experienced users, more experienced one will understand and know how to be cautious.

**Comment by gouessej** [comment]
@gorhill I understand your objection, it seems to be reasonable to me. I thank others for their support and their help :) I'm reluctant to move my project to another temporary source hosting facility again. Therefore, I'll self host it, it will solve this problem as I'm not a big fan of trackers, spywares, viruses, ads, ... I'd prefer keeping concentrated on my project. Best regards.
