### ISSUE TITLE
[Firefox] cosmetic filtering have no effect

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#873]
On this page http://florydziak.blogspot.com/2015/10/starszy-brat.html ("popup" with article)
![fl](https://cloud.githubusercontent.com/assets/886325/10768306/b4a3946a-7ce0-11e5-9e2f-7ab6a9a6f124.png)

For example "Fanboy’s Annoyance List" `##.share-controls`, filters created by picker or manually.
Filters are visible in uBlock log. Sometimes they are applied, but very rarely. Mostly on first time, when loaded in background (last time happens when juggling with filter list and reloading from uBlock log).
I know, this page is broken: sometimes stops loading on "cogwheels" screen. Sometimes buttons in top left corner are missing (<, >, g+). Browser console reports problem with x-frame-options:
```
Security Error: Content at https://www.blogger.com/comment-iframe.g?blogID=8681818539802867443&postID=6053747354527061714 may not load data from http://florydziak.blogspot.com/2015/10/starszy-brat.html.
Load denied by X-Frame-Options: https://www.blogger.com/comment-iframe.g?blogID=8681818539802867443&postID=6053747354527061714 does not permit cross-origin framing. <unknown>
```
Should this affect uBlock?

I see this for some time on Fx 41 (42, 43) on Win7, Mint17,  uBlock 1.3.2rc4 with EasyList+uBlock+uBlockPrivacy+`florydziak.blogspot.com##.share-controls` (and earlier uBlock versions with more filters)

**Comment by gorhill** [comment]
Looks like uBO's `style` tag is being removed by the site. Need to investigate more.

**Comment by gwarser** [comment]
Another example http://bialy-dev.blogspot.com/2014/12/what-is-bpg.html

**Comment by gorhill** [comment]
> Another example http://bialy-dev.blogspot.com/2014/12/what-is-bpg.html

If I set 3rd-party to `block`, the page is left blank.

**Comment by gorhill** [comment]
Disregard my previous comment (deleted), I thought I was commenting about something else.

This is an issue specific to pages on `blogspot.*` sites: pages are rendered through javascript, in a way which removes completely the `body` element to replace it with another `body` element. uBO's mutation observer attaches itself to the `body` element, so this means it's being flushed when the page is rendered with the real content.

Attaching the mutation observer to the `html` element fixes the issue.

**Comment by gorhill** [comment]
> Attaching the mutation observer to the `html` element fixes the issue.

Actually, not completely. The page not only flush the initial `body` element, but also the `head` element, which means that the `style` tag install by UBO before the DOM completely loads (for specific or cached cosmetic filters) are also removed.
