### ISSUE TITLE
Connecting to facebook yields DNS_PROBE_FINISHED_NXDOMAIN error

### ISSUE THREAD

**Issue by lthibault** [gorhill/uBlock#874]
I have reset uBlock Origin to its default settings, but the problem still persists.  Please advise.

OS:  Mac OS X El Capitan
Browser:  Google Chrome v 46.0.2490.80 (64-bit)

**Comment by CrisBRM** [comment]
How is this related to uBlock? It just means the DNS lookup was not successful.
Try this: https://support.apple.com/en-us/HT202516 or change your DNS servers to something else.

**Comment by grabber24** [comment]
Or perhaps, kindly ask them
