### ISSUE TITLE
Cosmetic filters not always reported by logger on Firefox 42 if you refresh the page

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#876]
Please try to reproduce this:

1. Enable the `RUS: BitBlock` and `Fanboy’s Annoyance` lists
2. Open https://www.kifi.com/signup or http://anonymouse.org/cgi-bin/anon-www.cgi/http://handycache.ru/
3. Watch the logger and refresh the page a couple of times

On Chrome, uBlock Origin 1.2.0   reports the cosmetic filters every time I refresh the page:
![untitled-1](https://cloud.githubusercontent.com/assets/6733770/10787862/d7b55dba-7d5a-11e5-98bf-fff212621f8f.png)

On Firefox 42 Beta though, uBlock Origin 1.3.1 most often doesn't show me the cosmetic filters :
![untitled-1](https://cloud.githubusercontent.com/assets/6733770/10787926/3be58918-7d5b-11e5-8a18-ed8e94548335.png)

Despite this problem with the logger, the filters are still correctly applied and all elements  are hidden accordingly to the filter lists.

I wonder if this has something to do with my Firefox cache settings or other extensions. Anyway, since those are cosmetic filters,  I assume that they should always be listed.

My current settings:

![untitled-2](https://cloud.githubusercontent.com/assets/6733770/10788136/84dbd55e-7d5c-11e5-8788-0b0c81eafb51.png)

**Comment by gorhill** [comment]
I can reproduce.

I am guessing the script to survey filtered DOM elements is being executed before `DOMContentLoaded`.
