### ISSUE TITLE
3rd party filter, NOR: Norsk adblockliste‎ no longer exists

### ISSUE THREAD

**Issue by grrrrr** [gorhill/uBlock#878]
The 3rd party filter `NOR: Norsk adblockliste‎` located at http://home.fredfiber.no/langsholt/adblock.txt  no longer exists.

I can find one [forum post](https://forums.lanik.us/viewtopic.php?t=22993) that makes mention of it no longer existing and links to a [year old mirror](https://github.com/ytakano/adchecker/blob/master/adblock.txt) of the list on github

**Comment by gorhill** [comment]
Fixed in 88a103e86f091dc608737321fde71f67e6bfadaf.
