### ISSUE TITLE
Two connected domains... but where are the images?

### ISSUE THREAD

**Issue by Laserfischen** [gorhill/uBlock#881]
![test1](https://cloud.githubusercontent.com/assets/15244080/10822325/f37b90ee-7e56-11e5-8b23-3e27183d1003.jpg)

Even if I whitelist or mark "green" both sources... the image don't come up (blank space - it is as the visible avatars hosted at twimg.com). In the logs there is nothing of the image source blocked. And why there is only 1 of 2 domains connected? Btw: I have no host files in my filterlists.

![log](https://cloud.githubusercontent.com/assets/15244080/10822320/ee1c320c-7e56-11e5-960c-489977a94c3a.jpg)

Firefox 38.03 ESR and FF 41.03

**Comment by gorhill** [comment]
Can you give me a clickable URL? Having to transcribe it from the picture will be rather tedious.

**Comment by Laserfischen** [comment]
https://twitter.com/langziehohr/status/658984313388670976

**Comment by gorhill** [comment]
Also, as usual, browser/version, all uBO settings which differ from default.

**Comment by gorhill** [comment]
Can't reproduce using FF 41.0.2 + rules as seen in your screenshot. I have `google-analytics.com` in my list (blocked). **Be sure** nothing is blocked before reaching uBO.

**Comment by Laserfischen** [comment]
Browser: Iceweasel 38.03 ESR and FF 41.03
OS: Debian
uBo settings: Nightmare and all lists ->  WITHOUT: 
Dan Pollock’s hosts file‎ (someonewhocares.org)
Fanboy+Easylist-Merged Ultimate List‎
hpHosts’ Ad and tracking servers‎ (hosts-file.net)
MVPS HOSTS‎
EasyList without element hiding rules‎

**Comment by Laserfischen** [comment]
Browser: Iceweasel 38.03 ESR and FF 41.02
OS: Debian 8
uBo Filterlists: All but loacle only the German Easylist and disabled the host lists (Dan Pollock and so on).

**Comment by Laserfischen** [comment]
Browser: Iceweasel 38.03 ESR (like FF 38.03 ESR) and FF 41.02
OS: Debian
uBo Settings: Nightmare and nearly all filterlists without the host ones (like Dan Pollocks list and so on). Locale only the german easy list.

**Comment by gorhill** [comment]
Can you select the _All_ entry in the tab selector of the logger? See if the image is blocked somewhere in there.

**Comment by Laserfischen** [comment]
Hmm there are two Icons clickable at postion "others"... if i cklick them... the uBo Popup GUI comes up for github settings?! Ok...?!

![all1](https://cloud.githubusercontent.com/assets/15244080/10823120/6fb96c3c-7e5a-11e5-83d1-d9725588bb16.jpg)
![all2](https://cloud.githubusercontent.com/assets/15244080/10823125/737d18e6-7e5a-11e5-8ce4-ac2717cf8e86.jpg)

**Comment by gorhill** [comment]
Does the blocked image, `https://pbs.twimg.com/media/CSUuuLZW0AABsfb.jpg` appear in the logger when you select _All_?

**Comment by Laserfischen** [comment]
No, it doesn't... like you can see in the screenshots above.

**Comment by gorhill** [comment]
On my side the image is at <https://pbs.twimg.com/media/CSUuuLZW0AABsfb.jpg>. Can you load this in your browser?

**Comment by gorhill** [comment]
What other extensions do you have installed and activated in your browser?

**Comment by Laserfischen** [comment]
Extensions: Even if i disable all Extensions... the problem still persists. I have no other software in front of any network access which can cause this. I ve phoned with my brother. He is on Win 7... even there is no picture shown.

**Comment by gorhill** [comment]
If you right-click on where the image is supposed to be and click _Inspect Element..._, does the DOM look the same as seen below?

![a](https://cloud.githubusercontent.com/assets/585534/10825229/718e98d6-7e3a-11e5-85fc-a247976a4363.png)

**Comment by Laserfischen** [comment]
It is not possible to locate the place, where the pic shut show up... if I try, it marks the whole tweet with her avatar and so on.

**Comment by gorhill** [comment]
Can you try pressing <kbd>Shift</kbd> when you click the reload page icon?

**Comment by Laserfischen** [comment]
Ok... normal reload with no additional tasks performed... done... no picture. Or what does shift + reload perform (without my notice)?

**Comment by gorhill** [comment]
Just to be sure, did you try with uBO disabled?

**Comment by Laserfischen** [comment]
I have to apologize honestly... what the hack. I must dig deeper... somethings wrong beneath... or near by uBo but it seems not to be the fault of uBo cause by disabling uBo the pics aren't shown, too. SORRY for wasting your  time. I go to benefit an animal shelter since you don't accept a donation for your work on uBo. :)

**Comment by Laserfischen** [comment]
I've got it: Since FF goes above version 38 one privacy setting I made in about:config in the past might lead to the misbehavior now -> so I have to deal with less privacy and some pics will shown up. That's it. Since I know the cause... i will let this setting persist... cause privacy is more important... and the misbehavior occures only on twitter until now. :)

**Comment by gorhill** [comment]
> one privacy setting I made in about:config

Anything that you can share? If ever somebody has the same symptom, could be useful to document here to remind to look at the possibility.

**Comment by Laserfischen** [comment]
Sure... it's called dom.indexedDB.enabled -> set to FALSE. (default is true).
Before FF 38 ESR (with this setting) there were no probs at all...

**Comment by lewisje** [comment]
I don't understand why people disable IndexedDB to begin with; I've read several pieces of advice reminding people to ensure it's enabled and wondered why that would even be necessary to say.

**Comment by Laserfischen** [comment]
Ok, did you know that before FF 35 -it- was disabled by default if you use the "private mode" of FF? Ok, I don't think so. As I mentioned above I use FF ESR, because it allows me to use FF as long as possible without the shiny new features that will be added each month I don't want my browser to do. FF should show pages and not loging and caching all that stuff websites might use (maybe to track). 
Oh, and there comes up several new methods to compromise FF if enabled, like this: https://www.mozilla.org/en-US/security/advisories/mfsa2015-16/

**Comment by Laserfischen** [comment]
In addition, if security/privacy doesn't matter:
If I want to enable indexedDB for some reasons, since I am aware something might get broken if not, I put (here on linux) /home/username/.mozilla/firefox/somewhat.default/storage in a ram-file (automated done by fstab -> after a shutdown the ram is flushed). Why: If you play for example ONE arcade game (not flash!) on archive.org you will get min. 17 mb data cashed persistent in that storage folder. Now think about the fact you maybe visit that page only once in a lifteime... or on the other hand how big such file might get in the future.
