### ISSUE TITLE
Random uninstall on Firefox

### ISSUE THREAD

**Issue by Serg86** [gorhill/uBlock#882]
**FIXED: Anti-Virus software was blocking it without telling me.**

uBlock Origin sometimes flat out disappears from my latest Firefox. It isn't just disappearing from my toolbar, it's no longer installed under addons and I have to reinstall it every day. I have no idea what causes this.

Restarting Firefox doesn't make it disappear on purpose.
Restarting my PC doesn't make it disappear on purpose.
The next day I start the PC and Firefox, more often than not, it's gone.

I have no idea where to even begin investigating this issue.

I am using:
Windows 7 64 bit
Avira AntiVirus
Firefox 41.0.2 (As of this moment)
I have the Ghostery Firefox Addon installed

I have an SSD as my main OS drive, I install every program, including my browser, on a separate HDD.

This is all the vaguely relevant information I can think of.

**Comment by gorhill** [comment]
There is no code in uBlock Origin to uninstall itself without the browser asking first -- so this is an external issue, something else on your computer is causing this.

**Comment by Serg86** [comment]
Obviously, that's why I listed all the other things not related to uBlock Origin. However, I came here since this is the only addon this happens to and I have absolutely no idea what causes this. I was hoping you would be able to help me track down the issue.

As I said above, I don't even know where to begin.

**Comment by gorhill** [comment]
Hopefully someone else will have an idea of how this can happen. My config differs quite a lot from yours, I am nowhere near able to try to reproduce.

**Comment by kintpuash** [comment]
http://forums.anandtech.com/showpost.php?s=b55dd13bf47f1b7c0633b001eeedc906&p=37761378&postcount=10

Someone else with a similar problem. Suggests Avira tripping out on the Malware Domain list. As a quick work around/troubleshooting, you could try removing the Malware Domain lists and purging the cache.

**Comment by Serg86** [comment]
I've already looked inside the Avira logs, there is nothing shown regarding the .xpi of uBlock. I just added it to the exceptions list so will report later if that fixed it.

**Comment by anewuser** [comment]
You can uninstall Ghostery if you enable EasyPrivacy‎ and  the Basic tracking list by Disconnect‎ on uBlock Origin. There's no point in having both extensions at the same time.

**Comment by grinderX19** [comment]
I have the same issue with Firefox account synced between two PCs: one has Ubuntu 14.04 and the second one is Win 7 with Avira installed. Probably Avira is the culprit.

**Comment by gwarser** [comment]
I can confirm. You can find xpi in Avira quarantine.

**Comment by TheTipo01** [comment]
Yep. Too for me, it's in Avira quarantine.

**Comment by Serg86** [comment]
I just checked again, Avira is the culprit. The weird thing is, it doesn't tell me it found a suspicious file nor does it show up in the log, just the list of already quarantined files.

**Comment by lewisje** [comment]
I noticed something similar happening with the Chrome version of uBlock Origin: When I ran the Junkware Removal Tool, this extension and a couple others were uninstalled, but fortunately my settings were still there, so all I had to do was re-install uBlock Origin.

**Comment by gorhill** [comment]
So I guess I should collate the names of those tools known to have removed uBO: <https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin>.
