### ISSUE TITLE
[Firefox] Filter options

### ISSUE THREAD

**Issue by Snapy** [gorhill/uBlock#883]
#### Steps
1. Enable "I am an advanced user" setting
2. Remove behind-the-scene from the whitelist
3. Add `|http://$domain=behind-the-scene` to "My filters"
4. Open the logger
 
>
- Go to https://github.com and wait for a websocket request from `live.github.com` to occur
- Open the dialog to create a network static filter
  - create this filter `||live.github.com/_sockets$websocket,domain=behind-the-scene`
    - note that `websocket` is offered as a filter option

_**OR**_

>
- Install [Keygen music play button] (https://addons.mozilla.org/firefox/addon/keygen-music-play-button/)
- Add this filter `@@||keygenmusic.tk/mp3/kgm$media,domain=behind-the-scene` to "My filters" 
    - note that the `media` filter option is available when creating from the logger
- Click the extension button
- A request of type media is blocked

#### Symptoms
Filters created are not enforced by uBlock Origin.
Workaround is to use the $other filter option. Maybe related to the [typeMap] (https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L1737) (and nsIContentPolicy) and chrisaljoudi/uBlock#649.
I suggest adding to the wiki the list of available filter options and/or removing from the logger the ability to create static filters with such options.

> uBlock Origin 1.3.2
Firefox 42 beta
Windows 7

**Comment by hotdogman** [comment]
Have you removed behind-the-scene from the whitelist?
![egynuqqo54ff 1](https://cloud.githubusercontent.com/assets/4343306/10836634/ca022206-7e7d-11e5-91f3-21450cc4d45e.png)

**Comment by Snapy** [comment]
Yes, see the second step.
> Remove behind-the-scene from the whitelist

**Comment by hotdogman** [comment]
My apologies. Should've read better.
