### ISSUE TITLE
[Firefox] Images sometimes visible despite 3rd-party dynamic block

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#884]
Happens to me nearly every day on https://www.inoreader.com/ when I scroll through long list of articles (~150). Sometimes when switching folders. Inoreader is configured to load 12 articles in expanded view.
My workflow: open browser, load in background 5-6 pages from speeddial, start inoreader and scroll through articles opening some of them in background. When one of the next "batches" of articles loads I see images in them.

I have globally
blocked 3rd-party scripts, 3rd-party frames
allowed youtube.com, ytimg.com, ajax.googleapis.com, googlevideo.com, jquery.com 
locally 
blocked 3rd-party
noop ajax.googleapis.com, explosm.net, pidjin.net, release24.pl, xkcd.com, youtube.com
no-cosmetic-filtering true

I saw images from (for example) http://www.ghacks.net/feed/, http://pclab.pl/xml/rss.xml, http://feeds.feedburner.com/glowny-di (maybe requested from cache), http://sceper.ws/category/tv-shows/feed (most annoying).
I afraid that other resources may also be loaded.

Probably caused by automatic update check. When I turned off 'Auto-update filter lists' for couple days, problem disappeared. When happened to me today (reenabled auto-update), uBlock shows that there is update available for `assets/ublock/filters.txt`.
I think you says, something like this may happen on filters update, but this happens to me too often.

uBO 1.3.3b1 (and earlier) on Fx 42 (and erlier) on Mint 17, Win 7

**Comment by bendawwas42** [comment]
I believe u-block is seeming useless when I am cloned and not seeing my own screen sometimes. I also am unaware of the reasoning for administration to allow faulty help in a project i think I'm in the middle of. It also makes it hard on me to decide what to block or what to not to block.

**Comment by gwarser** [comment]
I just purged all cashes, next update should happen after 4 days, will see.

**Comment by gorhill** [comment]
Did you look at the URLs of the images you saw?

**Comment by gorhill** [comment]
> Probably caused by automatic update check

Very unlikely. The only time something can go through because of auto-update is a **fraction** of second for when uBO reloads all the filter lists, and this occurs once every 4-5 days only.

**Comment by gwarser** [comment]
>Did you look at the URLs of the images you saw?
Yes, in inspector, they are third party. However I have no luck to catch them in uBlock loger. I always forget to turn it on.

**Comment by Laserfischen** [comment]
@gorhill
You say a fraction of a second to reload the filterlists? Does it mean the same as "downloading" them at all? Hm... my update seems to take several seconds if all picked lists were updated from source (with 16mbit/s).

**Comment by gwarser** [comment]
>Does it mean the same as "downloading"...

No. They are downloaded into a buffer, "compiled" and then swapped in fraction of a second.

**Comment by Laserfischen** [comment]
Ok, I misunderstood.

**Comment by anewuser** [comment]
@gwarser  Since this is very specific to you, just disable the `Auto-update filter lists` option and do it manually.

**Comment by gorhill** [comment]
Thinking of it, it could be because of auto-update. I said earlier that this occurs every 4-5 days, but this could happens more often if I update uBO's own filter lists, which would cause one or more filter lists marked as "new version available" -- in which case updating could occurs more often. I have been modifiying `unbreak.txt` and `filters.txt` often lately.

**Comment by gwarser** [comment]
I may exaggerate _a bit_ with "nearly every day", but this happens to me regularly. 

Trying to trigger this today by cache purging, force update and autoscroll in old articles, but no success.

**Comment by gwarser** [comment]
Happened just now.
Fx is runing over 5 hours. I watched a movie for a while, switched back to browser, opened inoreader (14th tab), scrolled through ~40 articles, opened 11, and just realize that something is wrong: 
![uboir](https://cloud.githubusercontent.com/assets/886325/10917759/b3bfedd2-8262-11e5-8c54-531f7ebdccdb.png)
When scrolled back, I see that article 26 already have visible image.
Article 18 was about Firefox extension - **I installed it!**.
Nothing special in browser console (jquery from another page)
I've seen image in article ~35, but disappeared after some time. Now cannot be accessed ("Could not load the image" tooltip in inspector).
All "Purge cache" buttons have "Last update: 3 days ago" tooltip.

Looks like this is not about uBO update check, but Fx update check. Firefox enters into some unstable state when extension is installed/updated, and takes some time to stabilize.

**Comment by gwarser** [comment]
Again. Last extension update 2 hours ago. Last filter list update 3 hours ago.
Images starts appearing after switch to another feed in tree panel.
One batch full of images (12), then one image from cache in next batch (article 22) and nothing to the end (36 articles). In browser console 1,5h earlier: 
```
17:01:43.904 [CustomizableUI] Custom widget with id loop-button does not return a valid node CustomizableUI.jsm:166
19:34:54.030 Asynchronous operation was aborted as selection changed. breadcrumbs.js:129
19:35:26.365 DOMException [InvalidAccessError: "A parameter or an operation is not supported by the underlying object"
code: 15
nsresult: 0x8053000f
location: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/styleinspector/css-logic.js:1335] protocol.js:907
19:35:26.417 Protocol error (unknownError): InvalidAccessError: A parameter or an operation is not supported by the underlying object rule-view.js:54
19:35:26.420 Protocol error (unknownError): InvalidAccessError: A parameter or an operation is not supported by the underlying object Promise-backend.js:937
19:35:39.234 navigated; resolution of _defaultNode aborted Promise-backend.js:937

```
and after opening first page from _broken batch_ (before I realize)
```
21:04:39.908 Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery.min.js:3:0
21:04:47.507 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2330:1
21:04:47.508 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2337:17
21:04:47.508 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2338:17
21:04:47.509 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2339:17
21:04:47.509 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2340:17
21:04:47.509 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2341:17
21:04:47.510 ReferenceError: bmone2n is not defined zatwierdzono-sposob-leczenia-raka-przy-pomocy-genetycznie-modyfikowanych-wirusow:2342:17
21:04:47.607 wykop is undefined PokazywarkaWykopoZakopowiczow%252B.user.js:73:98
21:04:47.636 attributeValue is undefined Wykopowy_AdBlock.user.js:41:5
21:04:48.280 Use of Mutation Events is deprecated. Use MutationObserver instead. c679d0d9bbf02fda2837b188b4c75d62.js:2:0
21:04:53.903 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7027:1
21:04:53.903 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7034:17
21:04:53.903 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7035:17
21:04:53.904 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7036:17
21:04:53.905 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7037:17
21:04:53.905 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7038:17
21:04:53.905 ReferenceError: bmone2n is not defined krakow-pylomierze-psuja-sie-od-smogu-komunikaty-znikaja-z-tablic:7039:17
21:04:53.987 wykop is undefined PokazywarkaWykopoZakopowiczow%252B.user.js:73:98
21:04:54.035 attributeValue is undefined Wykopowy_AdBlock.user.js:41:5
```

**Comment by gwarser** [comment]
After scrolling back and forth in this feed all but three images disappeared. Now they are visible even when i click again on this feed in tree panel. They must be loaded from cache. I see links to them in response source code, no base64 strings, they are not visible in uBO log (All requests, Behind the sceene).
Log shows one small xhr (counters), then favicon, large xhr with source, 10 blocked images (2 missing), xhr with source, 11 blocked images (1 missing), xhr with source, 9 blocked images .

**Comment by gorhill** [comment]
> they are not visible in uBO log

Not sure what to make of this. I suppose with Firefox this can happen if another extension prevent those images from being loaded -- uBO will just report everything it sees to the logger, so if something is not there, it's because uBO's listeners were not called by FF.

If it happens again, disregard the type and see if the _URLs_ of those images are in the log. If not, copy-paste one of the URL directly in the address bar in a new tab, see if these URLs are undergoing redirections.

**Comment by gwarser** [comment]
I see one behavior that may contribute to this bug - images loaded from cache are visible when 3p content is blocked.
For example:
* in inoreader open feed with images blocked by 3p rule (cosmetic filters disabled)
* copy image url, and open in another tab (you may also open another page which contains this image)
* refresh feed in inoreader
* image is visible but not reported in log

Is very fortunate that browser tends to always reload javascript from web.

**Comment by gorhill** [comment]
Any other extensions installed?

**Comment by gwarser** [comment]
A lot. I just disabled them all, and restarted browser - no change. I may also have some about:config changes - should I check?
Fx 43b1 64bit on Linux Mint

**Comment by DropTable69** [comment]
Is this related to uBlock ignoring everything on the "My Filters" tab? I've tried on Linux, Windows, Chromium, Slimjet, Palemoon, Firefox, Chrome. If I block the side bar on say, Youtube or IMGUR it comes back on page reload.

**Comment by gorhill** [comment]
@DropTable69 What is the exact filter which does not work on Youtube or Imgur?

There are [many reasons](https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappear-when-you-reload-the-page) why your filters may not be enforced. This is unrelated to this issue.

**Comment by DropTable69** [comment]
www.youtube.com###watch7-sidebar
imgur.com###right-content 

It always comes back on page load, browser restart, page change. But if I readd it, it's applied temporarily for the page/instance I added it on.

**Comment by gorhill** [comment]
`www.youtube.com###watch7-sidebar` works fine from here. Did you look into the many reasons above why this may not work?

**Comment by DropTable69** [comment]
Yes, I'm kind of desperate to fix this, I don't know what I may be doing on my side to cause it. I'll try with everything disabled except uBlock again.

**Comment by Alpengreis** [comment]
Would it be possible that uBlock could even avoid that "fraction of a Second" while auto update, for example with a suspend technique?

**Comment by gwarser** [comment]
I did not saw this behavior for months now.

**Comment by Alpengreis** [comment]
Thanks for answering, gwarser and it's good to hear that. Nevertheless it would be better to not have a such "time window" because on fast systems with fast connections COULD this be enough to let some things through or not?

**Comment by gorhill** [comment]
> I did not seen this behavior for months now.

Given this, closing this issue.
