### ISSUE TITLE
Add filter license note

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#885]
"Some of the 3rd-party filters (simple data files) in this software are under non-free licenses. However, it is not clear that the works in question are actually subject to copyright or that the licensing terms could apply. As such, we urge you to use redistribute those filters with caution that someone may try to claim copyright on the works." - https://directory.fsf.org/wiki/UBlock_Origin (see license note when logged in)

**Comment by seanrand** [comment]
Would linking to a "filter licenses" wiki page from the about tab be enough to finally silence https://github.com/chrisaljoudi/uBlock/issues/1461? I'd try to compile a list, then.

IIRC, gorhill already said that adding it to the third-party filters tab would be too much clutter.

**Comment by flyingzebras** [comment]
@seanrand I think that will do it. Thanks.

**Comment by gorhill** [comment]
Since <chrisaljoudi/uBlock#1461>, I have removed all 3rd-party filter lists which are not selected by default. EasyList and EasyPrivacy are GPL-licensed. This leaves Peter Lowe's, and the two malware filter lists selected by default. I added README files for all of these since a while:

- Peter Lowe's: <https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/pgl.yoyo.org/as/README.md>.
- malwaredomains.com: <https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/mirror1.malwaredomains.com/files/README.md>.
- malwaredomainlist.com: <https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/www.malwaredomainlist.com/hostslist/README.md>.

**Comment by flyingzebras** [comment]
@gorhill Thank you too.

**Comment by seanrand** [comment]
Alright then, here we go:

---

Filter List | Default | GPL | Creative Commons | MIT | Public Domain | Other | Undetermined
----------- | ------- | --- | ---------------- | --- | ------------- | ----- | ------------
uBlock filters |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
uBlock filters - Badware risks |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
uBlock filters - Privacy |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
uBlock filters - Unbreak |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
Adblock Warning Removal List‎ |||||||X
Anti-Adblock Killer (Reek‎) |||[CC BY-NC-SA 4.0](https://github.com/reek/anti-adblock-killer/blob/master/LICENSE)||||
EasyList‎ |X|[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
EasyList without element hiding rules‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
Peter Lowe's Ad server list‎ |X|||||[McRae GPL](http://pgl.yoyo.org/license/)|
Basic tracking list by Disconnect‎ ||[GPL3](https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt)|||||
EasyPrivacy‎ |X|[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
Fanboy's Enhanced Tracking List‎ |||[CC BY 3.0](https://fanboy.co.nz/enhancedstats.txt)||||
Malvertising filter list by Disconnect‎ ||[GPL3](https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt)|||||
Malware Domain List‎ |X|||||[Free for all](http://www.malwaredomainlist.com/)|
Malware domains‎ |X|||||[Non-commercial](http://www.malwaredomains.com/?page_id=1508)|
Malware domains (long-lived) ||||||[Non-commercial](http://www.malwaredomains.com/?page_id=1508)|
Malware filter list by Disconnect‎ ||[GPL3](https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt)|||||
Spam404‎ |||||||X
Anti-ThirdpartySocial |||||||X
Fanboy's Annoyance List‎ |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt)||||
Fanboy's Social Blocking List‎ |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/fanboy-social.txt)||||
Dan Pollock’s hosts file‎ |||||||X
Fanboy+Easylist-Merged Ultimate List‎ ||[GPL3](https://fanboy.co.nz/r/fanboy-ultimate.txt)|[CC BY-SA 3.0](https://fanboy.co.nz/r/fanboy-ultimate.txt)||||
hpHosts' Ad and tracking servers‎|||||||X
MVPS HOSTS‎ |||[CC BY-NC-SA 4.0](http://winhelp2002.mvps.org/hosts.txt)||||
ARA: Liste AR‎ |||[CC BY-NC-SA 3.0](https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt)||||
BGR: Bulgarian Adblock list‎ |||||||X
CHN: China: cjxlist ||[GPL3](https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt)|[CC BY-SA 3.0](https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt)||||
CHN: EasyList China ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
CZE, SVK: EasyList Czech and Slovak‎ |||[CC BY-SA 4.0](https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt)||||
DEU: EasyList Germany‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
DNK: Schacks Adblock Plus liste‎ |||||||X
EST: Eesti saitidele kohandatud filter‎ |||||[CC0 1.0](http://adblock.ee/list.php)||
EU: Prebake - Filter Obtrusive Cookie Notices‎ ||||[MIT](https://github.com/liamja/Prebake/blob/master/README.md)|||
FIN: Finnish Addition to Easylist‎ |||||[Unlicense](https://iadb.azurewebsites.net/Finland_adb.txt)||
FRA: EasyList Liste FR‎ |||[CC BY-NC-SA 3.0](http://www.adblock-listefr.com/A_propos)||||
GRC: Greek AdBlock Filter‎ |||[CC BY-SA 3.0](https://www.void.gr/kargig/void-gr-filters.txt)||||
HUN: hufilter‎ |||[CC BY-SA 4.0](https://github.com/szpeter80/hufilter/blob/master/README.md)||||
IDN: ABPindo‎ ||[GPL3](https://raw.githubusercontent.com/heradhis/indonesianadblockrules/master/COPYING)|[CC BY-SA 3.0](https://raw.githubusercontent.com/heradhis/indonesianadblockrules/master/COPYING)||||
ISL: Icelandic ABP List‎ |||||||X
ISR: EasyList Hebrew‎ ||[GPL3](https://raw.github.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt)|[CC BY-SA 3.0](https://raw.github.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt)||||
ITA: ABP X Files‎ |||[CC BY-NC-SA 2.5](http://noads.it/#contact)||||
ITA: EasyList Italy‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
JPN: ABP Japanese filters ||[GPL3](https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt)|[CC BY-NC-SA 4.0](https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt)||||
KOR: Fanboy's Korean‎ |||[CC BY 3.0](https://www.fanboy.co.nz/fanboy-korean.txt)||||
KOR: Korean Adblock List‎ |||||||X
LTU: Adblock Plus Lithuania‎ ||[GPL3](http://margevicius.lt/easylistlithuania.txt)|||||
LVA: Latvian List‎ |||[CC BY-SA 4.0](https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt)||||
NLD: EasyList Dutch‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
POL: polskie filtry do Adblocka i uBlocka‎ |||[CC BY-NC-SA 4.0](https://www.certyficate.it/adblock/adblock.txt)||||
RUS: BitBlock List |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/bitblock.txt)||||
RUS: RU AdList |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/advblock.txt)||||
SWE: Fanboy's Swedish‎ |||[CC BY 3.0](https://www.fanboy.co.nz/fanboy-swedish.txt)||||
VIE: Fanboy's Vietnamese‎ |||[CC BY 3.0](https://www.fanboy.co.nz/fanboy-vietnam.txt)||||

MIT             - http://choosealicense.com/licenses/mit
GPL3            - http://choosealicense.com/licenses/gpl-3.0/
CC BY 3.0       - https://creativecommons.org/licenses/by/3.0/
CC BY-SA 3.0    - https://creativecommons.org/licenses/by-sa/3.0/
CC BY-SA 4.0    - https://creativecommons.org/licenses/by-sa/4.0/
CC BY-NC-SA 2.5 - https://creativecommons.org/licenses/by-nc-sa/2.5/
CC BY-NC-SA 3.0 - https://creativecommons.org/licenses/by-nc-sa/3.0/
CC BY-NC-SA 4.0 - https://creativecommons.org/licenses/by-nc-sa/4.0/
CC0 1.0         - https://creativecommons.org/publicdomain/zero/1.0/
Unlicense       - http://unlicense.org/
McRae GPL       - http://pgl.yoyo.org/license/

---

And the Markdown source:

```
Filter List | Default | GPL | Creative Commons | MIT | Public Domain | Other | Undetermined
----------- | ------- | --- | ---------------- | --- | ------------- | ----- | ------------
uBlock filters |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
uBlock filters - Badware risks |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
uBlock filters - Privacy |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
uBlock filters - Unbreak |X| [GPL3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) |||||
Adblock Warning Removal List‎ |||||||X
Anti-Adblock Killer (Reek‎) |||[CC BY-NC-SA 4.0](https://github.com/reek/anti-adblock-killer/blob/master/LICENSE)||||
EasyList‎ |X|[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
EasyList without element hiding rules‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
Peter Lowe's Ad server list‎ |X|||||[McRae GPL](http://pgl.yoyo.org/license/)|
Basic tracking list by Disconnect‎ ||[GPL3](https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt)|||||
EasyPrivacy‎ |X|[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
Fanboy's Enhanced Tracking List‎ |||[CC BY 3.0](https://fanboy.co.nz/enhancedstats.txt)||||
Malvertising filter list by Disconnect‎ ||[GPL3](https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt)|||||
Malware Domain List‎ |X|||||[Free for all](http://www.malwaredomainlist.com/)|
Malware domains‎ |X|||||[Non-commercial](http://www.malwaredomains.com/?page_id=1508)|
Malware domains (long-lived) ||||||[Non-commercial](http://www.malwaredomains.com/?page_id=1508)|
Malware filter list by Disconnect‎ ||[GPL3](https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt)|||||
Spam404‎ |||||||X
Anti-ThirdpartySocial |||||||X
Fanboy's Annoyance List‎ |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt)||||
Fanboy's Social Blocking List‎ |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/fanboy-social.txt)||||
Dan Pollock’s hosts file‎ |||||||X
Fanboy+Easylist-Merged Ultimate List‎ ||[GPL3](https://fanboy.co.nz/r/fanboy-ultimate.txt)|[CC BY-SA 3.0](https://fanboy.co.nz/r/fanboy-ultimate.txt)||||
hpHosts' Ad and tracking servers‎|||||||X
MVPS HOSTS‎ |||[CC BY-NC-SA 4.0](http://winhelp2002.mvps.org/hosts.txt)||||
ARA: Liste AR‎ |||[CC BY-NC-SA 3.0](https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt)||||
BGR: Bulgarian Adblock list‎ |||||||X
CHN: China: cjxlist ||[GPL3](https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt)|[CC BY-SA 3.0](https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt)||||
CHN: EasyList China ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
CZE, SVK: EasyList Czech and Slovak‎ |||[CC BY-SA 4.0](https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt)||||
DEU: EasyList Germany‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
DNK: Schacks Adblock Plus liste‎ |||||||X
EST: Eesti saitidele kohandatud filter‎ |||||[CC0 1.0](http://adblock.ee/list.php)||
EU: Prebake - Filter Obtrusive Cookie Notices‎ ||||[MIT](https://github.com/liamja/Prebake/blob/master/README.md)|||
FIN: Finnish Addition to Easylist‎ |||||[Unlicense](https://iadb.azurewebsites.net/Finland_adb.txt)||
FRA: EasyList Liste FR‎ |||[CC BY-NC-SA 3.0](http://www.adblock-listefr.com/A_propos)||||
GRC: Greek AdBlock Filter‎ |||[CC BY-SA 3.0](https://www.void.gr/kargig/void-gr-filters.txt)||||
HUN: hufilter‎ |||[CC BY-SA 4.0](https://github.com/szpeter80/hufilter/blob/master/README.md)||||
IDN: ABPindo‎ ||[GPL3](https://raw.githubusercontent.com/heradhis/indonesianadblockrules/master/COPYING)|[CC BY-SA 3.0](https://raw.githubusercontent.com/heradhis/indonesianadblockrules/master/COPYING)||||
ISL: Icelandic ABP List‎ |||||||X
ISR: EasyList Hebrew‎ ||[GPL3](https://raw.github.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt)|[CC BY-SA 3.0](https://raw.github.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt)||||
ITA: ABP X Files‎ |||[CC BY-NC-SA 2.5](http://noads.it/#contact)||||
ITA: EasyList Italy‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
JPN: ABP Japanese filters ||[GPL3](https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt)|[CC BY-NC-SA 4.0](https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt)||||
KOR: Fanboy's Korean‎ |||[CC BY 3.0](https://www.fanboy.co.nz/fanboy-korean.txt)||||
KOR: Korean Adblock List‎ |||||||X
LTU: Adblock Plus Lithuania‎ ||[GPL3](http://margevicius.lt/easylistlithuania.txt)|||||
LVA: Latvian List‎ |||[CC BY-SA 4.0](https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt)||||
NLD: EasyList Dutch‎ ||[GPL3](https://easylist-downloads.adblockplus.org/COPYING)|[CC BY-SA 3.0](https://easylist-downloads.adblockplus.org/COPYING)||||
POL: polskie filtry do Adblocka i uBlocka‎ |||[CC BY-NC-SA 4.0](https://www.certyficate.it/adblock/adblock.txt)||||
RUS: BitBlock List |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/bitblock.txt)||||
RUS: RU AdList |||[CC BY 3.0](https://easylist-downloads.adblockplus.org/advblock.txt)||||
SWE: Fanboy's Swedish‎ |||[CC BY 3.0](https://www.fanboy.co.nz/fanboy-swedish.txt)||||
VIE: Fanboy's Vietnamese‎ |||[CC BY 3.0](https://www.fanboy.co.nz/fanboy-vietnam.txt)||||

MIT - http://choosealicense.com/licenses/mit
GPL3 - http://choosealicense.com/licenses/gpl-3.0/
CC BY 3.0 - https://creativecommons.org/licenses/by/3.0/
CC BY-SA 3.0 - https://creativecommons.org/licenses/by-sa/3.0/
CC BY-SA 4.0 - https://creativecommons.org/licenses/by-sa/4.0/
CC BY-NC-SA 2.5 - https://creativecommons.org/licenses/by-nc-sa/2.5/
CC BY-NC-SA 3.0 - https://creativecommons.org/licenses/by-nc-sa/3.0/
CC BY-NC-SA 4.0 - https://creativecommons.org/licenses/by-nc-sa/4.0/
CC0 1.0 - https://creativecommons.org/publicdomain/zero/1.0/
Unlicense - http://unlicense.org/
McRae GPL - http://pgl.yoyo.org/license/
```

**Comment by flyingzebras** [comment]
@seanrand That is a good initiative!

**Comment by flyingzebras** [comment]
@seanrand Is there a page for this table that can be used as reference when it is updated?

**Comment by seanrand** [comment]
I'm hoping gorhill copy/pastes it into a page on the wiki. Shouldn't need much maintenance unless filters are added/removed.

**Comment by Snapy** [comment]
For Easylist filter lists, license is [here] (https://easylist-downloads.adblockplus.org/COPYING).

**Comment by seanrand** [comment]
It's actually not as clear-cut which lists are Easylist filter lists and which are Easylist-affiliated filter lists that use different licenses (Easylist FR, for example) - and some non-Easylist filter lists also use Easylist's license file. In any case, I linked to the relevant license file in the table wherever I was able to find them.

**Comment by gorhill** [comment]
> I'm hoping gorhill copy/pastes it into a page on the wiki.

Thanks for this reference work. I opened the wiki again for editing by anybody, you can create a new page as you wish.

**Comment by Snapy** [comment]
Easylist and affiliated are hosted under hg.adblockplus.org and downloadable under easylist-downloads.adblockplus.org. So it includes Adblock warning removal (which you marked as undetermined).

**Comment by seanrand** [comment]
@gorhill: Done. https://github.com/gorhill/uBlock/wiki/Filter-list-licenses

@Snapy: The way I understood Easylist's license file was that it may not apply to lists other than EasyList, EasyPrivacy, EasyList Germany and EasyList Italy. EasyList FR for example is available through https://easylist-downloads.adblockplus.org/liste_fr.txt as well, but ships with a different License comment in the file.

Anyway, I created the page, everyone should feel free to expand/correct/reword.

**Comment by flyingzebras** [comment]
@seanrand @gorhill I added this to https://github.com/gorhill/uBlock/wiki/Filter-list-licenses

"Some of the 3rd-party filters (simple data files) in this software are under non-free licenses. However, it is not clear that the works in question are actually subject to copyright or that the licensing terms could apply. As such, we urge you to use redistribute those filters with caution that someone may try to claim copyright on the works." - Joshua Gay, Licensing & Compliance Manager, Free Software Foundation
