### ISSUE TITLE
What happend to the "NOR Norwegian Ad Block" list

### ISSUE THREAD

**Issue by LarsErikOsterud** [gorhill/uBlock#886]
1. Firefox (latest 42.0 beta and 44 nightly)
2. Try http://www.nettavisen.no
3. Background ad showing (not showing with uBlock, might be lack of "Norwegian Ad Block list")        

Just changed from uBlock to uBlock Origin. But suddenly some norwegian newspapers got lagre background ads again. Only difference is that Origin don't have the "NOR Norwegian Ad Block list" in the list of filters. Why don't you? Would have been to bad having to switch back again :-(

**Comment by sslizer** [comment]
it appears that the filter list no longer existed, see #878.

If that is the case you probably had a locally cached copy which is why it worked for you.  But new users would have got no benefit.

**Comment by gorhill** [comment]
You will have to install it as a custom filter list: <https://raw.githubusercontent.com/ytakano/adchecker/master/adblock.txt>.

The original list is no longer online, and the mirrored one is un-maintained -- so I can no longer have this list part of uBO's stock filter lists.

**Comment by DandelionSprout** [comment]
This is probably very, very belated of me to mention, but there's a new and active [Norwegian filter list](https://github.com/DandelionSprout/adfilt/blob/master/ExperimentalNorwegianList.txt) nowadays, that could fill the gap of the old Norwegian list.
