### ISSUE TITLE
A page becomes functional after a few seconds

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#888]
Firefox 42. Windows 7.

STR:

Add the IsraelList filters.
Go to http://tv-guide.walla.co.il

Result:
The page becomes functional (scroll bar, clickable links) only after a few seconds.

Thank you.

**Comment by gorhill** [comment]
Make the case that uBO is really the issue, I will reopen. I can scroll and click links before the page finishes loading.
