### ISSUE TITLE
A droplist won't open

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#889]
Firefox 42. Windows 7.

STR:

Add the following filters:
||perfectpro.co.il^$popup,third-party
||leshem.info^$popup,third-party

Go to: http://www.inn.co.il/Forecast.aspx
Press the [Forecast list](http://s28.postimg.org/vd71it5lp/image.png).

Result:
The list opens for a brief second and then it's closed.

**It works properly with ABP.**

Thank you.

**Comment by gorhill** [comment]
If you open the droplist before the page finish loading, it will close, regardless of whether uBlock Origin is installed or not.
