### ISSUE TITLE
Connecting to raw.githubusercontent.com without user notice - spyware?

### ISSUE THREAD

**Issue by mewblock** [gorhill/uBlock#89]
background.js

```
// EasyList, EasyPrivacy and many others have an 4-day update period,
// as per list headers.
updateAssetsEvery: 97 * oneHour,
projectServerRoot: 'https://raw.githubusercontent.com/gorhill/uBlock/master/',
```

---

Look, I just want uBlock to update my subscriptions.
I don't ask you to update "3rd party list" lists or something.

Please explain what uBlock is sending what/where/when.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/tree/master/assets>

**Comment by gorhill** [comment]
I suggest you stop using uBlock if your first assumption is "spyware". Find something else, there is plenty of choice out there.
