### ISSUE TITLE
Dynamic Filtering: show number of requests per each domain (optionally)

### ISSUE THREAD

**Issue by tophf** [gorhill/uBlock#895]
Assuming this usage scenario for cautious users: 
- all 3rd-party resources are disabled by default
  
  ![1-fs8](https://cloud.githubusercontent.com/assets/1310400/10870754/8ec98c34-80e3-11e5-9caf-9b55b4e0b13e.png)
- frequently used sites are whitelisted manually

---

Now the user opens a new nonwhitelisted site ([example](http://www.allmusic.com/artist/jim-beard-mn0000847263)) that loads lots of resources like CDN, etc.:
- the site looks distorted
- the user opens uBlock popup and sees a lot of domains
- but even CDN is not always easy to spot, and it's not the only one needed for a fully functional site, there are several such domains quite often. Currently uBlock shows `-` and `+` but it's almost useless as you can see on the screenshot below (`rovicorp` line isn't any different from the others).

---
### The suggestion: show the number of requests for each domain.
- The domains important for rendering are likely to have a high number of blocked requests.
- It could be toggled by an option, enabled by default. I think it should replace current display of `+` and `-`.
- UI examples:
  
  ![1-fs8](https://cloud.githubusercontent.com/assets/1310400/10870847/638a6720-80e6-11e5-817b-f2c39c5fbb7f.png)
  
  ![4](https://cloud.githubusercontent.com/assets/1310400/10870591/9df6a8ee-80df-11e5-8bc0-63d3f9db739e.png)
  
  ![5-fs8](https://cloud.githubusercontent.com/assets/1310400/10870625/6e8aac94-80e0-11e5-9852-64f615840806.png)

**Comment by gorhill** [comment]
> `rovicorp` line isn't any different from the others

It becomes different once you un-block the CDN domain `hwcdn.net`.

**Comment by tophf** [comment]
@gorhill, there are many sites where even CDN isn't possible to guess because all domains have just one `+` or `-` and the name doesn't contain `cdn`.

**Comment by tophf** [comment]
Another screenshot of how it could look with numbers instead of `+` and `-`:

![1](https://cloud.githubusercontent.com/assets/1310400/10870847/638a6720-80e6-11e5-817b-f2c39c5fbb7f.png)

**Comment by gorhill** [comment]
I decided against using numbers (that was my 1st prototype) early when I designed the dynamic filtering panel, because of visual pollution and the inability to guarantee that whatever goes in the cell won't grow out of it. Number of requests allowed/blocked on some sites can quickly become large (try Google Maps).

Using the log of the number of requests with maxing at 2 is what I believe to be optimal, the main point is to provide an overview -- at a glance -- with minimal visual pollution.

**Comment by tophf** [comment]
I see the problem with google maps.

However since the current implementation isn't very helpful, so what about using more fine scale using a narrow character like `|` with `letter-spacing: -3px;` and increase the number of `+`/`-` to 6 or 9 (delete `/ Math.LN10`)?

**Comment by tophf** [comment]
Also you can simply use `99+` for large numbers.

Well, I don't insist since I already use a custom modification, which you've rejected, to remove the limit for the popup's height, so I guess I can easily add another one.

**Comment by vzjrz** [comment]
@tophf Why not just use uMatrix in conjunction with uBlock? uMatrix to control 3rd-party requests and uBlock to specific requests.
Note how uMatrix gives you pretty much exactly what you're looking for:
![umatrix3](https://cloud.githubusercontent.com/assets/930620/10873375/8c8ba5ec-80d9-11e5-946b-ec09e469d1cb.png)

**Comment by tophf** [comment]
@vzjrz, that's an interesting suggestion, but one extension is more comfortable.

Also, in my opinion `+` and `-` in uBlock are the noise because they don't convey information.

**Comment by Betsy25** [comment]
@tophf Actually, I like the way you coded is, and while not really more 'cluttering' to the UI, it does present more precise than using the + ++ +++ way, showing the users more precise views.
I hope @gorhill takes your code into consideration.

**Comment by androidland** [comment]
i would prefer, what content is blocked, s = scrpt, i = image or f = frames

**Comment by RoxKilly** [comment]
I think having exact numbers in every cell is not a good idea. I think a broad, less cluttered overview is better so I like the current implementation. I suppose one compromise is to make it an option in settings, but we then have to ask whether that is the best way to spend development time, not only for the initial coding but also for the bug-fixing and support requests that will follow.

**Comment by tophf** [comment]
> but we then have to ask whether that is the best way to spend development time

Oh please! The code is already posted in the message above.

**Comment by RoxKilly** [comment]
Thanks

**Comment by tophf** [comment]
@gorhill, I've found another solution which solves the original problem (finding the CDN domains quickly without blind guessing): just show the domains sorted by total request count (allowed + blocked) in descending order in `addFirewallRow`.

Since I'm not familiar with your uDom library I've used vanilla js:

```js
var addFirewallRow = function(des) {
..........................
    var total = hnDetails.totalAllowCount + hnDetails.totalBlockCount;
    var nodes = [].slice.call(document.querySelectorAll('#firewallContainer .isDomain *[data-des]'));
    var before;
    nodes.some(function(e) {
    	var d = popupData.hostnameDict[e.dataset.des];
    	var dtotal = d.totalAllowCount + d.totalBlockCount;
    	if (total > dtotal || total == dtotal && des < d.domain) {
    		before = e.parentNode;
    		return true;
    	}
    });
    document.getElementById('firewallContainer').insertBefore(row.nodes[0], before);
```

**Comment by tophf** [comment]
With the recent change in uBlock that adds subdomains the importance of *sorted* display has been increased, this is what my code does now (the subdomains are dimmed unless mouse-hovered):

![screenshot](https://cloud.githubusercontent.com/assets/1310400/12349501/39c0c71a-bb81-11e5-8ece-9c64ea923b04.png)

**Comment by gwarser** [comment]
>With the recent change...

Click on "- all".

**Comment by gorhill** [comment]
> With the recent change in uBlock that adds subdomains

"[R]ecent"? Subdomains have always been available -- in fact it's the reverse, collapsing to base domain was added later in the dynamic filtering panel.

**Comment by tophf** [comment]
The mode has been recently changed for some reason, I didn't know of it before. The point was different though, and hopefully clear.
