### ISSUE TITLE
[Firefox] New tab not showing in logger selector + other bad side effects

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#896]
Repro steps:
- FF 41.0.2, uBO 1.3.2
- Launch Firefox
- Click the `+` button to create a new tab
- New tab opens

Wrong:
- Open uBO's logger: the new tab is not in the selector's list
- Try to toggle uBO's whitelist button: it always resets to disabled state

**Cause:** The newly opened browser object as reported by `vAPI.net.registerListeners`/`LocationChangedListener` does not really end up in a tab after all - so it ends up being unregistered from uBO. One more quirk to deal with.

**Potential solution:** having `tabWatcher`/`onSelect` expressly register non-registered browser objects, i.e. calls `vAPI.tabs.onNavigation` if needed.

**Comment by Notoll** [comment]
Simple adjustment: Make about:blank not whitelisted at all... so this "bug" isn't present anymore. No sideffects by now.

**Comment by gorhill** [comment]
> Make about:blank not whitelisted at all

This makes absolutely no difference.

**Comment by Notoll** [comment]
Well, my "homepage" is about: blank... so each new tab. If about:blank is set to "not whitelisted", all new tabs shown up propper with no bugs you mentioned above are visible.

**Comment by gorhill** [comment]
I can reproduce even the New Tab page set to a blank page. What version of FF/uBO are you using?

**Comment by Notoll** [comment]
uBO Version 1.3.2 and FF 38.03 ESR. 
OK, 38.03 ESR might lead to a different behaviour... but I don't have the ressources to test FF 42 by myself on my productive machine yet. 
Sorry, if my post in this case is not helping anyway!

**Comment by gorhill** [comment]
Assuming the issue still exists, it's now irrelevant with WebExtensions.
