### ISSUE TITLE
Requests render issue when multiple Request Logs inspectating the same tab

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uBlock#9]
Sometimes I have many request logs open for different tabs and sometimes I just find the nearest one and to insepct another tab meaning I'll have more than 1 request log inspecting the same tab.  When you refresh, it doesn't know which request log to render it in.
1. Open a tab to wired.com
2. Open another tab to github.com/gorhill
3. Open the request log for each tab
4. Pick one of the request log and inspect the other tab
5. Refresh the tab that both request log are inspecting

![ublock2requestlogs](https://cloud.githubusercontent.com/assets/6408935/7077646/72d49d3e-dec7-11e4-8c4f-c4fdee7cbf2e.gif)

```
uBlock0 0.9.3.1
Chrome (stable)
Win XP
```

**Comment by gorhill** [comment]
I don't understand the issue. Do you mean you want all the request log for one specific tab to contain exactly the same content?

**Comment by my-password-is-password** [comment]
Maybe just render it in tab you clicked refresh in.  Don't need it in all request logs.

**Comment by gorhill** [comment]
Ok I see the issue. Not sure there is an easy solution, if any. The logs pull data fro the background process, and when the data is pulled, it's not kept around. Each log window doesn't know about the others, and the background process does not know about them either, it just answer to request for data by giving whatever data has accumulated in the internal buffer.

**Comment by my-password-is-password** [comment]
Yeah, don't worry about it.  If i'm annoying you with these little issue just let me know.  You can tell me to shut up anytime.  :)

**Comment by gorhill** [comment]
I used to have a version where the log was embedded in the dev console, so that issue would not exist if it worked this way, but I could not figure a way to make this portable across platform. That would be the solution, but then I would need to figure how to do the same on Firefox. Maybe I should look into all this again.
