### ISSUE TITLE
Slideshows on Wired.com are broken

### ISSUE THREAD

**Issue by elpres** [gorhill/uBlock#901]
Take this one for example: http://www.wired.com/2015/11/the-most-nonsense-concepts-from-the-tokyo-motor-show/ . After you click the right arrow several times (4 in this case), it stops working. Here's what I found fixes the breakage:

```
www.wired.com googleadservices.com * allow
www.wired.com googletagservices.com * noop
```

**Comment by gorhill** [comment]
Works fine with default settings.

**Comment by elpres** [comment]
I've been coming across this problem several time already, on several machines. Are you sure you can navigate the whole slideshow, from start to finish? It breaks somewhere in the middle.

**Comment by vzjrz** [comment]
With default settings after 6 clicks a blank slide appears but that seems to be an ad. Apart from that I can navigate through the whole slideshow just fine.

**Comment by gorhill** [comment]
> Are you sure you can navigate the whole slideshow, from start to finish?

Yes, all 9 slides.

>  It breaks somewhere in the middle.

It does not break in the middle, the one which does not display is an ad slide.

**Comment by elpres** [comment]
That is strange. To debug this, I've just nuked all my rules, blocked 3rd party scripts and frames, and then the slideshow broke. Could you please try if you can reproduce it this way?

**Comment by gorhill** [comment]
> blocked 3rd party scripts and frames

Your are creating block rules for 3rd-party frames/scripts, it's not an issue with the project, it's an issue with your own custom rules.

**Comment by elpres** [comment]
Ok, that is fair. But wouldn't this be at least a case for "uBlock filters – Unbreak"?

**Comment by gorhill** [comment]
Actually, even blocking 3rd-party frames/scripts the slideshow works fine.

> But wouldn't this be at least a case for "uBlock filters – Unbreak"?

Dynamic filtering rules override whatever static filters might have kicked in, by design (so users have absolute last word, not the filter lists) -- this is explained in the [Required reading](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) link.

See [how it works internally](https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock's-network-filtering-engine).

**Comment by elpres** [comment]
> Actually, even blocking 3rd-party frames/scripts the slideshow works fine.

Not for me. I've no idea what's different with my setup, but I've spent more time figuring out how to unbreak this issue, on several occasions, than I care to admit.

> Dynamic filtering rules override whatever static filters might have kicked in, by design (so users have absolute last word, not the filter lists) -- this is explained in the Required reading link.

Good, that makes sense. Well, at least I'm happy to have figured out the solution for my own use case :)

**Comment by harshanvn** [comment]
slideshows does break for me. Although it is not my default setup. Attached the screenshot for details..

However i am able fix it by disabling the inline-scripting for that site..

![u](https://cloud.githubusercontent.com/assets/779630/10918573/70fdc4e0-828c-11e5-84c4-0986ad54c3a2.png)

**Comment by gorhill** [comment]
uBo can't guarantee either that things will all work fine when selecting more 3rd-party filter lists than the default ones. As said, with default settings, it worked fine. If selecting an extra 3rd-party filter list breaks things, this needs to be taken to the maintainer(s) of that filter list.
