### ISSUE TITLE
On my Firefox mobile aurora 44 and nightly 45 uBlock don't work. 

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#908]
It's obviously a browser bug but maybe you can do something ?

**Comment by Snapy** [comment]
Which version of uBlock Origin are you using ? A similar bug was reported in #749 and has been fixed in latest 1.3.4b2.

**Comment by LifeIsStrange** [comment]
Yes I know I think it's the same problem, I use uBlock Origin 1.3.2 on my aurora and I have still the bug, BUT my Firefox nightly have the 1.3.4b2 dev release and the issue is repared, 
Sorry and thanks.
