### ISSUE TITLE
EBates Doesn't Work with uBlock

### ISSUE THREAD

**Issue by 8888anon8888** [gorhill/uBlock#911]
When I access an ebates-supported site, the site will indicate that an adblocker is preventing eBates from work properly. I am asked to install a 3rd party filter list in order to take advantage of ebates; however, the instruction to add that filter only works with adblockplus. How can I get eBates to work with ublock? TIA!

**Comment by gorhill** [comment]
> I am asked to install a 3rd party filter list in order to take advantage of ebates

You are not providing any links to that filter list. In any case, it quite probably because this list is designed to completely disable uBO for a list of servers, using the `document` filter option. uBO does not support exception filters using the `document` option, by design ([see doc](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#not-supported)).

**Comment by 8888anon8888** [comment]
This is the link.

[quote]abp:subscribe?location=http%3A%2F%2Fwww.ebates.com%2Fwhitelist%2Febates-cash-back-shopping.txt&title=Ebates%20Cash%20Back%20Shopping[/quote]

Hope that helps.

**Comment by gorhill** [comment]
> `@@||track.linksynergy.com^*$xmlhttprequest,subdocument,document,script,object,image,~third-party,stylesheet`

The whole content iis filled with filters using the `document` option. See my answer above.

Example on converting the above unsupported filter to a whitelist directive to be pasted in the _Whitelist_ pane in the dashboard:

    `track.linksynergy.com`

**Comment by PumSeed** [comment]
Removing all the markup, below is the current list of domains from EBATES' white list found at https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt which can simply be copied and pasted into uBlock Origin's white list.  Of course you may wish to remove some of these lines for sites you don't shop from.

Best regards.

~Andrew
=======================================

ebates.com
ebates.ca
ebates.ru
ebates.cn
ebates.kr
ebatesinc.com
fatwallet.com
ebates.sg
ebates.com
ebates.ca
ebates.ru
ebates.cn
ebates.kr
ebatesinc.com
fatwallet.com
ebates.sg
optimizely.com
service.bfast.com
www.qksrv.net
www.jdoqocy.com
www.kqzyfj.com
www.dpbolvw.net
www.tkqlhce.com
www.anrdoezrs.net
www.commission-junction.com
linksynergy.com
clickserve.cc-dt.com
centinel400.cardinalcommerce.com
centinel300.cardinalcommerce.com
centinel600.cardinalcommerce.com
paymentech.cardinalcommerce.com
www.pntrs.com
www.gopjn.com
www.pntra.com
www.pjtra.com
www.pjatr.com
www.pntrac.com
images.revtrax.com
scripts.affiliatefuture.com
dtrack5.com
media303.com
ebates.shop.com
quinst.com
media.quinstreet.com
dtrk5.com
doubleclick.net
dtrack3.com
centinel1000.cardinalcommerce.com
centineltest.cardinalcommerce.com
www.shareasale.com
www.tripalertz.com
avantlink.com
www.awin1.com
aos.prf.hn
rover.ebay.com
www.amazon.com
www.bluenile.ca
www.avantlink.ca
www.grandinroad.com
www.frontgate.com
www.bluenile.com
www.comcastadvantage.com
www.timewarnercable.com
www.wirefly.com
www.groupon.com
www.iherb.com
prf.hn
ad.zanox.com
gearshop.dpreview.com
rover.ebay.com
ebay.com
go.redirectingat.com
itunes.apple.com
www.comcastspecial.com
www.cannonsatellitetv.com
ad.admitad.com
ad.zanox.com
www.zanox.com
www.ozon.ru
www.iherb.com
click.linkprice.com
www.bestbuy.com
clickmeter.com
levexis.com
dotomi.com
pepperjamnetwork.com
emjcd.com
mplxtms.com
intelliad.de
7eer.net
metalyzer.com
atdmt.com
xg4ken.com
reuseit.com
roia.biz
ojrq.net
tradedoubler.com
thecorner.com
onenetworkdirect.net
lauramercier.com
evyy.net
hostelbookers.com
agkn.com
abebooks.com
babiesrus.com
swarovski.com
tpptracker.com
searchignite.com
bluehost.com
getaroom.com
mediaplex.com
ru4.com
go2jump.org
1800gotjunk.com
swimspot.com
cj.com
elizabetharden.com
carhartt.com
airfrance.com
magiccabin.com
hearthsong.com
problemsolvers.com
kidsfootlocker.com
netmng.com
shareasale.com
gamefly.com
motosport.com
analytics.yahoo.com
bat.bing.com
steelhousemedia.com
mb4a.com
adsrvr.org
s.cxt.ms
r.msn.com
connexity.net
google-analytics.com
facebook.com
twitter.com
google.com
adap.tv
bidswitch.net
cxt.ms
yieldmanager.com
spotxchange.com
adadvisor.net
casalemedia.com
openx.net
rewardstyle.com
sephora.com
btstatic.com
demdex.net
hotjar.com
go-mpulse.net
mpstat.us
thebrighttag.com
tapad.com
mediaforge.com
rlcdn.com
flashtalking.com
skimresources.com
marinsm.com
fiksu.com
mathtag.com
adnxs.com
apxlv.com
tubemogul.com
cloudfront.net
rmtag.com
quantserve.com
t.co
triggit.com
dc-storm.com
abmr.net
adtechus.com
mookie1.com
lijit.com
sharethrough.com
sonobi.com
taboola.com
contextweb.com
exelator.com
burstnet.com
liverail.com
mythings.com
gwallet.com
nanigans.com
gssprt.jp
turn.com
bluekai.com
w55c.net
simpli.fi
addthis.com
rubiconproject.com
