### ISSUE TITLE
Smaller power button?

### ISSUE THREAD

**Issue by corobin** [gorhill/uBlock#919]
Hello,

I'm making a feature request to consider making the power button smaller, it seems unnecessarily large for a whitelist feature to take up 1/3 of the primary information panel.

Contrast that to the four toggle buttons which are crammed in at the very bottom, which together take up a fraction of the power button's size.

perhaps something like a more rectangular button would be better?

Thanks!

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit>
