### ISSUE TITLE
gorhill blocked me for no reason. Is he a child?

### ISSUE THREAD

**Issue by mewblocked** [gorhill/uBlock#92]
"You have been blocked from this repository."

"Connecting to raw.githubusercontent.com without user notice - spyware?"
https://github.com/gorhill/uBlock/issues/89

My question: uBlock is a spyware or not?
Your answer: block me instantly WITHOUT ANSWER.

Very funny.

**Comment by gwarser** [comment]
https://developer.github.com/changes/2014-04-25-user-content-security/

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

**Comment by alejandrolemus** [comment]
@mewblocked 
So you created an account 3 days ago just to ask for acceptable ads in uBlock, despite that been a key point in uBlock's philosophy, and then later accused the extension developer of serving spyware?

Yup, you are right, he must be a child...
