### ISSUE TITLE
Very minor cosmetical suggestion for Chromium version

### ISSUE THREAD

**Issue by moppman** [gorhill/uBlock#921]
This is really minor and not important at all, but if you activate "Material design" in chrome://flags , the number on the uBlock icon indicating the blocked elements gets ever so slightly cut off at the bottom. 
The entire bar is probably a few pixels smaller in Material mode. (see screenshot)
![ublock](https://cloud.githubusercontent.com/assets/10085380/11019687/37837388-8604-11e5-81fc-b4358ae0b053.png)

**Comment by gorhill** [comment]
The icon/badge size/position is controlled by the browser, this is a browser issue.
