### ISSUE TITLE
:not() selector not working

### ISSUE THREAD

**Issue by markreg** [gorhill/uBlock#923]
:not() selector doesn't function in custom filters list. I'm trying to block a class except for an element with the same class yet with a child div with a specific id.

**Comment by Betsy25** [comment]
care to share the specific filter ?

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

Absolutely no details to substantiate `:not` selector not working. Will reopen when provided and if there is really an issue.

**Comment by markreg** [comment]
It doesn't work on `www.investopedia.com##.pg-wrapper:not(.pg-wrapper > #Content)`.

In order to circumvent ad blockers the site randomly selects which of the 101 `.pg-wrapper` blanks it selects to add the content related divs to. Plus it randomly selects a few of the other `.pg-wrapper`s for ad windows which is the object of elimination by the dynamic filter.

**Comment by gorhill** [comment]
> It doesn't work on `www.investopedia.com##.pg-wrapper:not(.pg-wrapper > #Content)`.

Not a valid selector. Try in the browser console:

> document.querySelector('.pg-wrapper:not(.pg-wrapper > #Content)');
> Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.pg-wrapper:not(.pg-wrapper > #Content)' is not a valid selector.(…)

Valid:

> document.querySelector('.pg-wrapper:not(#Content)');

**Comment by gorhill** [comment]
Maybe it's what you wanted: `www.investopedia.com##.pg-wrapper > div:not(#Content)` ?

**Comment by gorhill** [comment]
By the way, if you block inline script for the site, the DOM is saner -- no tons of `.pg-wrapper` elements.

**Comment by markreg** [comment]
Ah, I realize my mistake. There's no parent selector yet.

Where would the option to block inline-scripts be exactly? That might take care of the problem too.

**Comment by Betsy25** [comment]
>Ah, I realize my mistake. There's no parent selector yet.

>Where would the option to block inline-scripts be exactly? That might take care of the problem too.

![Screeshot](http://i.imgur.com/WxcOMm6.png)

**Comment by lewisje** [comment]
By the way, when the "parent selector" does appear, it will be known as `:has()` following the example of jQuery; then you could do something like `:not(:has())` I think.

**Comment by markreg** [comment]
When I block `inline scripts` it stops the inline script for the video player as well. Is there a way to make an exception for the player?

**Comment by gorhill** [comment]
For whatever reason, with Firefox there is no need to block inline scripts, and videos play fine.

**Comment by lolom** [comment]
Try this.

    investopedia.com#IFRAME[id$="google_ads_iframe"]
