### ISSUE TITLE
UblockOrigin hangs FF on a script

### ISSUE THREAD

**Issue by CheechGe** [gorhill/uBlock#925]
I had this problem with uBlock and was advised to install uBlockOriginal, which I did.   The same problem occurs which is with uBlock_o enabledl the site Marketwatch.com runs scripts that cause uBlock to complete hangup FF.  At times I need to force FF out of the system.   This is very repeatable on my system, Win/7 with the latest version of FF. A screenshot of the message is provided.  Disabling uBlock resolves the problem.

![ublockorg](https://cloud.githubusercontent.com/assets/3653639/11023423/2b4dff48-8636-11e5-9f1f-d3deb73be65e.png)

**Comment by publicarray** [comment]
> uBlockOriginal

close, it's called uBlock Origin. :smile: 

Can you list all add-ons installed, the uBlock version and the Fire Fox version?

**Comment by CheechGe** [comment]
Sorry, eyes and attention span don't work like they use to.
![ublockorg_01](https://cloud.githubusercontent.com/assets/3653639/11023535/0d92b55e-8639-11e5-8e67-30866db60a33.png)

**Comment by CheechGe** [comment]
FF 42.0, uBlock 1.3.2

**Comment by gorhill** [comment]
> the site Marketwatch.com runs scripts that cause uBlock to complete hangup FF

Force an update of _uBlock filters_, it contains the cure.

**Comment by gorhill** [comment]
Actually, your version of uBO should already have the fix as part of the package. If the page still freeze, this means that something else is filteringg the DOM elements above. Disable any other "ad" blocker-like add-ons and see if this works. You do not need BluHell if you enable uBO, it's pointless.

**Comment by CheechGe** [comment]
OK, I disabled BluHell and Ghostery, same results, but did not restart 
FF. Any others that I should remove/disable?

**Comment by gorhill** [comment]
> Any others that I should remove/disable?

I don't have a clue about most of your add-ons, so you will have to find out. Be sure you did not disable filter lists in uBO and it should work fine, it does here.

**Comment by gorhill** [comment]
Hum actually, I see I added the markwatch fix 10 days ago, so it is not part of 1.3.2. Just force an update of the filter lists in the dashboard, that will fix the issue.

**Comment by CheechGe** [comment]
I doubt I disabled the filter list as I don't know how to do that. I 
disabled everything that has the appearance of being an add blocker.  I 
will restart FF and see if that helps

**Comment by CheechGe** [comment]
OK, I'm back to how do I force and update of the filter lists?

**Comment by gorhill** [comment]
Click the title bar of uBO's popup, then go to "3rd-party filters". The "Update now" button should be highlighted, click it.

**Comment by CheechGe** [comment]
Raymond

That worked.

Q. the update lists automatically was checked so why was it necessary to 
do it manually?

Thanks,

Frank

**Comment by gorhill** [comment]
> the update lists automatically was checked so why was it necessary to
do it manually?

The update is made gradually, in the background, in a lazy way, to minimize spikes in the CPU/memory. All filter lists would have been updated about one hour or so after first install.

**Comment by CheechGe** [comment]
Understood, thanks for your help.  I permanently removed bluHell, will 
need to research the others as they may be redundant with uBO.

**Comment by CheechGe** [comment]
BTW, I had the same problem with uB on Chrome, replaced it with uBO and 
went through the same process and it works fine.

Thanks again for your assistance.

Frank

**Comment by grabber24** [comment]
Wonderful feedback from all. Thank you.
