### ISSUE TITLE
Syntax issue: single (dot) left on the list blocks ALL websites

### ISSUE THREAD

**Issue by edgrd** [gorhill/uBlock#926]
I woke up to this error today:

![ublock syntax error](https://cloud.githubusercontent.com/assets/11416158/11075766/29482706-87de-11e5-9457-01dc7237e830.png)

Apparently the list maintainer forgot a single "." (dot) on the top of the list .txt, which makes the extension block ALL domains and completely breaks browsing.

Could you make uBlock's syntax rules ignore this single dot, so a small mistake like that doesn't break everything ?

thanks

**Comment by edgrd** [comment]
http://www.joewein.net/dl/bl/dom-bl.txt‎

**Comment by edgrd** [comment]
I'm kinda desperate because I had added this blocklist to like 10+ PCs, and now everything breaks.

lol

**Comment by edgrd** [comment]
I talked to Joe by e-mail and he fixed his list. (thanks!)

But the syntax issue remains still, if you willing to change it.

**Comment by gorhill** [comment]
> But the syntax issue remains still, if you willing to change it.

I can't change uBO to make it start to second guess whether a filter should be _really_ used or not. Now it's a period `.`, next it could be a dash `-`, and then a `/`, a `s`, etc. The incident is unfortunate but it's not sufficient to start to introduce arbitrariness in the code.

**Comment by edgrd** [comment]
But it's only a single dot, maybe it would be wise to ignore the filter if it's just a single "." followed by nothing, that blocks everything.

just saying btw

**Comment by gorhill** [comment]
I don't want uBO to start arbitrarily second-guessing that a filter is really wanted or not.
