### ISSUE TITLE
[reflection] replace the new Firefox tracking protection by uBlock Origin ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#927]
Since the release 42, Firefox use in private mode a tracking protection Feature which is based on a disconnect privacy list and maybe use the disconnect addon in an embedded form (I have not find informations) 
The problem are : the disconnect list is very poor and bad supported compared to the easyprivacy list. 
The tracking protection is not as efficient as uBlock Origin is. 
This is not or very little evolutive. 
So replace this "disconnect embedded"  by an uBlock Origin embedded with only easyprivacy by default and the ability to add others privacy related lists and maybe virus /cookies related lists but with the impossibility to add by default an ad related list. 
If we do this, the Firefox base will gain huge privacy improvement, better battery, better ram and cpu usage and security and maybe that this will be enabled by default on Firefox with no privacy mode and this will be changed the face of the web !!! Grow the Firefox marketshare and do a huge gain for the humanity and the free software =). 
If you are agree with me you should create a bug on bugzilla or comments the tracking protection bugs, also I can help you for argument with the Firefox devs. 
Also maybe that mozilla can paid you for that, because security fixe are payed, you should be payed because having uBlock Origin even without ads related lists improve dramatically the security and the privacy.

**Comment by RoxKilly** [comment]
Thanks for your suggestion.  Firefox 42 does not use an embedded add-on. It uses the Disconnect block list directly, so there is no "Disconnect embedded" that can be replaced with a "uBlock Origin embedded"

Some companies will pay cash prizes for finding security vulnerabilities, but they typically won't pay you for providing a fix. Do you have any reason to think that Mozilla is different?

**Comment by gorhill** [comment]
If Firefox thought uBlock Origin was valuable to users privacy- and security-wise, there would have been signs of this already by now. There is no such signs. The only sign I have seen from Firefox is that they apparently agree that uBlock Origin helps make Firefox for Android run more efficiently, that's it.

In any case, I rather stay completely independent, this way I can ensure the project stays uncompromisingly dedicated to the interests of users. For the record, I do not think Firefox entering in ["commercial partnerships"](https://blog.mozilla.org/advancingcontent/2015/05/21/providing-a-valuable-platform-for-advertisers-content-publishers-and-users/) with advertisers is in the interests of users.

**Comment by RoxKilly** [comment]
At the risk of taking us slightly off topic: Firefox is in an odd position and I get its dilemma. It takes a lot of resources to maintain a secure, constantly updated, standards-compliant browser across many OSes, as well as an OS of its own (Firefox OS).  @gorhill how is Mozilla to pay for this?  

1.  It could charge its users. That boat has sailed; it's really difficult to start charging for a product that has been free for years, and freemium wouldn't work well in a browser because it has to be secure and standards compliant to be any good. I would gladly pay $20/yr for Firefox but I think only a tiny fraction of its user base would.  To most people a browser is just a commodity.

2.  It could make it free and accept donations in addition to voluntary coding contributions.  I don't know of another project of this size that has run purely on donations.  Wikipedia is the biggest donor funded web project I can think of, but I'm not convinced that its costs are on par with Mozilla's because Wikipedia's content is user-generated.  Apache is another great project but because it is back-end software it doesn't have to evolve as quickly as Firefox.

3.  It could enter commercial partnerships. This is the road chosen. It started with Firefox selling its default search box to Google (a deal worth [hundreds of millions of dollars](http://www.extremetech.com/computing/194650-firefox-drops-google-as-global-default-search-provider-switches-to-yahoo)). When I learned that at the time 85% of Firefox's revenue came from Google I felt really uneasy but I honestly don't know how else Mozilla can raise that kind of money.  It has to be careful though not to cross that tenuous line between serving users and serving advertisers.  [The Pocket integration](http://news.slashdot.org/story/15/06/09/1722236/mozilla-responds-to-firefox-user-backlash-over-pocket-integration) went too far in my opinion but otherwise I think Mozilla has done well.

Firefox is competing against extremely well funded alternatives (Chrome by Google, IE and Edge by Microsoft, and Safari by Apple).  I just don't know how it does that  while remaining untarnished by commercial partnership.  And this is coming from a guy who browses with JavaScript off by default, within a virtual environment, through a VPN.  in other words I'm not exactly liberal on privacy.

**Comment by LifeIsStrange** [comment]
@Roxkilly "Firefox 42 does not use an embedded add-on. It uses the Disconnect block list directly, so there is no "Disconnect embedded" that can be replaced with a "uBlock Origin embedded""
I don't knew thanks but this mean that the tracking protection use a list without cosmetic filtres ?? It must broke some sites ! Also there is a more complete list on the Firefox options (maybe Just in nightly currently I don't remember) she must broke Even further... 
So Firefox will have many gains if it use by default à uBlock Origin embedded without ads lists... No broken sites, better perf, better efficiency, better ram, far better privacy/security, evolutivuty. And so on better marketshare for Firefox and for uBlock Origin (the masse stay on adblock plus because ignorance) 

Secondly, "Some companies will pay cash prizes for finding security vulnerabilities, but they typically won't pay you for providing a fix. Do you have any reason to think that Mozilla is different?" 
Absolutly that I have reasons to think that mozilla is différent, firstly mozilla is not really à companie but rather a fondation of altruism and no lucrative. 
An exemple on what she is différent : http://www.networkworld.com/article/2997761/software/mozilla-will-donate-1-million-to-open-source-projects.html
UBlock Origin merit to be parts of this. 
So if we convince mozilla to integrate uBlock Origin (without ads lists) i'm pretty sûre that they will give a big tips to gorhill =) because we cannot navigate with privacy and security on the web without this addon (yes there is other and olders addons but uBlock is far more powerfull and efficient) also on Android your addon is responsible of a big part of the Firefox mobile marketshare because chrome deliberately don't support addons. With uBlock Origin my Firefox mobile become Faster than chrome ! 

Now @gorhill you say "If Firefox thought uBlock Origin was valuable to users privacy- and security-wise, there would have been signs of this already by now. There is no such signs. The only sign I have seen from Firefox is that they apparently agree that uBlock Origin helps make Firefox for Android run more efficiently, that's it."
But uBlock Origin is valuable to users privacy- and security-wise it's an objective fact indeniable. The Firefox devs have not Just had the idea because they are not perfect. You loose nothing to create a debate on bugzilla you have Just to win and the devs have also to win and the users also again ! 

"In any case, I rather stay completely independent, this way I can ensure the project stays uncompromisingly dedicated to the interests of users. For the record, I do not think Firefox entering in "commercial partnerships" with advertisers is in the interests of users."

But you can stay full independant and earn money from mozilla and give your addon by default on Firefox or by default Just in privacy mode. 
"For the record, I do not think Firefox entering in "commercial partnerships" with advertisers is in the interests of users.""
It's really not also simple, you know it's a non lucrative fondation of altruism. 
I think that there is an infondate mozilla bashing. 
This ads firstly are not really ads, it's links with à favicon it's not disinformation, it's not lie and don't use the psychanalyse, your subconscient for push you to buy products/services, it's Just promotion to websites it's not terrible it's not immoral. Mozilla need to make this since their contract with Google is broken, mozilla need money for continue to defending our rights against immoral firms like Google and to develop Firefox and servo And others innovations like webgl, shumway, asm.js, emscripten, support and develop open standards, etc. Without money there is no mozilla and without Firefox there is no true open source navigator and without open source navigateur there is no privacy, no security, no liberty, only backdoors.
It is the fault of the people which massively use the spyware named chrome, It is the fault of the people to not donate and develop to mozilla,And it is the fault of our "democracies" if the people are as ignorant and passive. 
Don't blâme mozilla try to understund

**Comment by LifeIsStrange** [comment]
@Roxkilly cIt could enter commercial partnerships. This is the road chosen."
Yes it's the road chosen but mozilla have also chosen this road "It could make it free and accept donations in addition to voluntary coding contributions. I don't know of another project of this size that has run purely on donations. Wikipedia is the biggest donor funded web project I can think of, but I'm not convinced that its costs are on par with Mozilla's because Wikipedia's content is user-generated. Apache is another great project but because it is back-end software it doesn't have to evolve as quickly as Firefox." Firefox is at this majority make by users code contributions. But people don't give donations, It is not yet in habits but when ads will die the people will far more often donations, like https://www.tipeee.com/creators
OR https://www.patreon.com/
OR crowdfunding like kickstarter and indiegogo ! 
Also the Google contract is dead, now Firefox have à Yahoo. Yandex and Baidu contacts. 
"The Pocket integration went too far in my opinion but otherwise I think Mozilla has done well." Firefox will remove pocket see this : http://www.ghacks.net/2015/11/08/good-news-pocket-to-become-a-firefox-add-on-once-again-sort-of/
And will promote wallabag which is free software. 
I have explained for the Firefox ads in my gorhill answer and this ads are necessary for the good of mozilla and are easyly disablable. 

"I just don't know how it can offer a compelling browser to its users while remaining untarnished by commercial partnerships." money is not all, far from this ;)  the future is the servo layout engine. Mozilla have far less money that Google but have better devs, true genious. Like @pcwalton that Google haven't. 
With far less money Firefox arrive to be the major actor in web innovations (shumway, webGL, asmr.js, Servo, emsrciptem, webVR, webassembly, do not tracks, etc...) 
I think it's because genious can't be genious without be ethical so genious can't work at Google or Just on the ethical parts like Google callico for immortality research. 

"within a virtual environment, through a VPN. in other words I'm not exactly liberal on privacy."
Just a question, you use chrome ? 
Again sorry for my bad english and thanks for your answers :)

**Comment by lewisje** [comment]
Indeed, the Disconnect list is just a list of domains to block; Firefox Tracking Protection has no equivalent for "cosmetic filters," and even if it did, they wouldn't be the filters that keep certain sites from being broken.

**Comment by RoxKilly** [comment]
@LifeIsStrange I don't think donations, whether from Patreon or other similar services would be sufficient to fund Firefox.  I hope I am wrong.  According to [Wikipedia](https://en.wikipedia.org/wiki/Kickstarter#Top_projects_by_funds_raised), the biggest fundraiser ever on Kickstarter was $20 million for the Pebble watch.  This would only pay for a few months of operations at Mozilla.
>But [**gorhill**] can stay full independant and earn money from mozilla

If someone is paying you to do something, you are not fully independent.  If you're responsible for a core component of the browser, I don't think you can be independent.
>Just a question, you use chrome ?

I have used Chrome to test whether it supports certain features but I don't trust Chrome. Firefox is my regular browser.

**Comment by LifeIsStrange** [comment]
I'm infinitely sorry for the late ! 

@Roxkilly "don't think donations, whether from Patreon or other similar services would be sufficient to fund Firefox. I hope I am wrong. According to Wikipedia, the biggest fundraiser ever on Kickstarter was $20 million for the Pebble watch. This would only pay for a few months of operations at Mozilla."
I think that phenonomen of fad can revolutionne the donation. 

"If someone is paying you to do something, you are not fully independent. If you're responsible for a core component of the browser, I don't think you can be independent."

having responsability is different of be dependant, with responsability gorhill must do good and secure and stable code, but he can always do what he want as long as his code is good, efficient, secure and stable. 

"I have used Chrome to test whether it supports certain features but I don't trust Chrome. Firefox is my regular browser."
You are right,Chrome is a fucking spyware, but you should also use Linux instead of Windows, because block JavaScript and having native backdoors is a non sens ;)  but maybe you are already on Linux !

**Comment by gorhill** [comment]
Closing because not an issue with uBlock Origin.
