### ISSUE TITLE
The "bidgewalbelp blocking filters" are still alive.

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBlock#930]
Hello.

I just want to inform about the **bidgewalbelp blocking filters**, which was removed from one of the uBO's wiki pages, that they are still alive. The old address was http://bidgewalbelp.neocities.org/blocking/filters.txt, which don't work, but the new is http://bidgewalbelp.neocities.org/filters.txt. If you can add it the list of custom filters in uBO's wiki page, @gorhill, that will be nice :)

**Comment by publicarray** [comment]
@gorhill I added it to the wiki. I assume this is ok since it can benefit people.
 
As of writing the txt file was last updated at Fri, 13 Nov 2015 07:25:58 GMT (taken from the response header)

**Comment by gorhill** [comment]
Thanks.
