### ISSUE TITLE
Huge amount of blocked elements on youtube leading to freeze

### ISSUE THREAD

**Issue by alph4** [gorhill/uBlock#932]
Chromium 46.0.2490.80 (64-bit)
uBlock 1.3.3
ArchLinux 64bit
Youtube, HTML5 player

Just play any video. If I start some recommended videos or just let autoplay run, there is no page reload. Only some kind of js reload. This leads to a large number of blocked elements and finally freezing/not responding tab. If I'm lucky and able to close the tab and afterwards restore the tab (strg+shift+t) the number of blocked elements starts by 0 and no problem.
On my setup the number increases by around 20 blocked elements per chosen video and starts freeze/lag at about 800/900 blocked elements.

**Comment by gorhill** [comment]
What you call "blocked elements" is simply a count of the number of network requests uBO blocked -- this has absolutely no effect on the CPU/memory.

**Comment by gorhill** [comment]
Also, always provide your filter lists and other settings which differ from stock settings.

**Comment by gorhill** [comment]
By the way, you did not make the case uBO is behind your issue. For this, you need to repeat the same scenario with another blocker with similar filter lists. As impressive as the block count is, it's just a mere counter, not an indicator of how much resource uBO is.

**Comment by gorhill** [comment]
Closing due to lack of feedback. Next time, use Task Manager and dev tool profiler to provide supporting evidence the issue is with uBO proper.
