### ISSUE TITLE
"Block similar elements" option in the "Block Element" dialog

### ISSUE THREAD

**Issue by teresaejunior** [gorhill/uBlock#933]
In uBlock there is already the "Block Element" tool, but there is one feature of Adguard that makes me switch to it constantly to write new filters, which is called "Block similar elements".

As an example, on Inoreader.com, uBlock blocks ads, but leaves empty spaces between feed items (the cosmetic filters don't work there).

Using uBlock, I select the empty space, and it returns the element `###leaderboard_ad-564435f7bb14f` to block. The problem with this approach is that `564435f7bb14f` here is just a random string, which changes every time I visit Inoreader.

To block ads like this effectively, I have to activate Adguard, open the "Block Element" dialog, select that element, which will return `###leaderboard_ad-564435f7bb14f` too. But then I click on "Advanced settings" and then "Block similar elements", which gives me `inoreader.com##.block_article_ad, .mobile_leaderboard_ad, .ad_size_mobile_leaderboard, .sinner` instead. I have used this rule in uBlock and it always works!

I have seen some very annoying ads on some other websites which also use that random string approach, and I can only write the rules easily for them with Adguard, and then I import them to uBlock.

**Comment by gorhill** [comment]
Where can I see that `leaderboard_ad-` DOM elements? Can you tell me how to get to that page, and what is the element on that page?

**Comment by teresaejunior** [comment]
Hi, @gorhill! You need to create an account on inoreader.com and subscribe to some feed there. The feeds should be set to be displayed as columns.

uBlock will block the ads but will leave gaps above and between the feed items, where it was supposed to appear ads:

![1](https://i.imgur.com/wt7Rdnt.png)

![2](https://i.imgur.com/kVDYnSe.png)

**Comment by teresaejunior** [comment]
I have noticed today that the website quora.com also uses this same method of random strings, which seems to have been designed to fool adblockers. If you start browsing questions there, they will eventually display an annoying popup trying to force you to login to display more questions.

**Comment by gorhill** [comment]
URL?

**Comment by teresaejunior** [comment]
Oh, sorry! I'll just give one example of an URL on quora.com: https://www.quora.com/Why-do-people-answer-questions-on-Quora-1

You won't see the annoying login message right away, but from there, if you start browsing through related questions, it appears after around three or five pages:

![1](https://i.imgur.com/dyYMm6h.png)

**Comment by gorhill** [comment]
> website quora.com also uses this same method of random strings

It's just a matter of removing the variable part using a fancier CSS selector in the current instance:

    ! 14/11/2015, 10:05:02 https://www.quora.com/What-makes-people-answer-questions-on-Quora
    www.quora.com##[id$="_modal_signup_wrapper"]

This specific case wouldn't be solve with a "Block similar elements" feature, as the variable part is in the unique id of the DOM element.

**Comment by teresaejunior** [comment]
I have just opened Adguard, and "Block similar elements" gives me `quora.com##.dialog, .modal_signup_dialog`, which works well with uBlock too.

**Comment by gorhill** [comment]
This was fixed with 1c4347d69d540916b609835dd63c56a11ab7b2e5, I hadn't realize there was an issue opened about this. Ctrl-click will now pick better broad selectors.

**Comment by teresaejunior** [comment]
That's awesome, thank you!

**Comment by cmwhyk** [comment]
what is the equivalent on OSX? I tried ctrl, option, cmd, shift to no avail
