### ISSUE TITLE
Help with a web site

### ISSUE THREAD

**Issue by bonbonboi** [gorhill/uBlock#934]
Hello, I'm using this web site and it's full of bad things, how can I keep using it without the need to put it into the white-list?  the URL is http://jo.jeeran.com/en/
The issue is that all things connected together, when I login and click on Notifications or to write a review just nothing happened when I click on one of them, even they are not ads..

**Comment by zummuz** [comment]
@bonbonboi Try this filter `@@||cdn.mxpnl.com/libs/mixpanel-2-latest.min.js$script,domain=jo.jeeran.com` (put it in *My filters* tab in the settings)

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit).
