### ISSUE TITLE
Support for nested domain filters

### ISSUE THREAD

**Issue by khatribharat** [gorhill/uBlock#935]
Does uBlock support nested domain filters? 

`adwords$script,domain=[abc.com, xyz.com]`

This would block all `script` resources having `adwords` in the url and originating from an iframe hosted at `*.abc.com` inside of a top frame hosted at `*.xyz.com`

I don't have a use case for this, but am curious as Adblock Plus seems to support it (as can be seen [here](https://github.com/adblockplus/libadblockplus/blob/master/include/AdblockPlus/FilterEngine.h#L297)), but its [documentation](https://adblockplus.org/filters) doesn't mention any way to achieve this using its filter syntax.

**Comment by gorhill** [comment]
> I don't have a use case for this

That's the most important aspect for any feature request. And even if there is a use case, it has to be broadly useful.

Adblock Plus syntax does not support pattern-matching for the domain option.

**Comment by lewisje** [comment]
The [function that that header file refers to](https://github.com/adblockplus/libadblockplus/blob/master/src/FilterEngine.cpp#L297) appears to look recursively through the chain of document URLs in the nested frames, looking for a document URL that matches the domain specifier.
