### ISSUE TITLE
sourceforge.net SVN should be explicitly unblacklisted

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#937]
Things such as `http://sourceforge.net/p/tom7misc/svn/*` should be unblacklisted somehow.

**Comment by publicarray** [comment]
I think the best way to keep everyone happy is to change the filter so something like `||sourceforge.net/*/download$document` so only the download pages are blocked.

**Comment by publicarray** [comment]
Related: #871 #561

**Comment by SoniEx2** [comment]
What if you have a `download` file in a SVN repo?

**Comment by gorhill** [comment]
One single click on the "Permanently" button and uBO will be out of your way forever on SourceForge.

**Comment by publicarray** [comment]
> What if you have a download file in a SVN repo?
If you only want to block project downloads: `||sourceforge.net/projects/*/download$document`

**Comment by hant0508** [comment]
Sourceforge has recently changed its owner. The new one is going to reestablish project reputation and clean it from adware. I think it's worth to encourage this idea and remove sourceforge.net from Badware Risks list.

> Our first order of business was to terminate the “DevShare” program. As of last week, the DevShare program was completely eliminated.

http://sourceforge.net/blog/sourceforge-acquisition-and-future-plans/

**Comment by gorhill** [comment]
All the source material supporting that `sourceforge.net` is "badware risks" are independent of the site. So It's going to take independent source material to make the case that `sourceforge.net` is no longer "badware risks". The announcement you link to is not independent source material.

**Comment by publicarray** [comment]
http://www.ghacks.net/2016/02/10/good-news-sourceforge-stops-bundling-adware-with-installers/

**Comment by gorhill** [comment]
It's a blog post on the company's announcement, not actual research work to confirm bundles known to ship with badware are now clean.

**Comment by kdt** [comment]
From the above link:

> A quick check revealed that the SourceForge installer is **no longer used** by projects like FileZilla that used it in the past. The programs are **delivered without a wrapper** that promotes the installation of third-party software on machines running Windows.

Of course it was a quick research, but "actual research" would be probably identical. Spreading FUD w/o reason is not a good idea :)

**Comment by gorhill** [comment]
I will just wait for a little while before removing as badware risks. The badware issue has been there for years, I prefer to wait a bit longer than a couple of days before assuming all is now fine.

**Comment by publicarray** [comment]
I wanted to do some additional checking so I used a [plugin to emulate Internet Explorer 11](https://chrome.google.com/webstore/detail/ie-on-chrome/kmomimblkpkjeilfbkinoonalgiejlcl) (I am running a Mac) to download some of the popular programs from sourceforge. **Update:** When I did these tests on the 2016-02-11 I did not have to signup to use the plugin.

![01](https://cloud.githubusercontent.com/assets/5497998/13026160/090415d2-d26a-11e5-9f4d-71722a702f4d.png)

Here are my Results:

| Website | Filename | VirusTotal on sourceforge files |
| --- | --- | --- |
| [7-zip](http://www.7-zip.org/) | 7z1514.exe | [0/54](https://www.virustotal.com/en/file/ae895c2831ff7f3c446a45b93b41bac8300038d0fbbc0fd6e4de6ff744bd81cb/analysis/) |
| [VLC media player](https://www.videolan.org/vlc/) | vlc-2.2.1-win32.exe | [0/54](https://www.virustotal.com/en/file/2eaa3881b01a2464d2a155ad49cc78162571dececcef555400666c719a60794d/analysis/) |
| [Audacity](http://www.audacityteam.org/) | audacity-win-2.1.0.exe | [0/54](https://www.virustotal.com/en/file/74d62afa0407fa7746ddeb24b3bf0e10192c045bb9414d824f3803cb69eb9d3e/analysis/) |
| [FileZilla](https://filezilla-project.org/) | FileZilla_3.15.0.1_win64-setup.exe | [0/54](https://www.virustotal.com/en/file/c268afcd1c134f13cb651d5dbfdef1dfada0d6088638c269c292671396b4e8d7/analysis/) |

I also wanted to confirm that all mirrors serve the same file. So downloaded 7zip from all but one sourceforge mirror (the mirror send me in a redirect loop) and compared the hashes. To than confirm if the mirrors are serving the same file from the original author, I downloaded it from [7-zip.org](http://www.7-zip.org/a/7z1514.exe) and compared the hashes. Luckily they all matched:

![03](https://cloud.githubusercontent.com/assets/5497998/13026173/41bc43ae-d26a-11e5-945d-306169993bd4.png)

While I was at it... Comparing some more sha256 hashes

| File | File from original source | Published hash if available | Sourceforge |
| --- | --- | --- | --- |
| 7z1514.exe | ae895c2831ff7f3c446a45b93b41bac8300038d0fbbc0fd6e4de6ff744bd81cb | | ae895c2831ff7f3c446a45b93b41bac8300038d0fbbc0fd6e4de6ff744bd81cb |
| vlc-2.2.1-win32.exe | 2eaa3881b01a2464d2a155ad49cc78162571dececcef555400666c719a60794d | [http://download.videolan.org/pub/videolan/vlc/2.2.1/win32/vlc-2.2.1-win32.exe.sha256](http://download.videolan.org/pub/videolan/vlc/2.2.1/win32/vlc-2.2.1-win32.exe.sha256) | 2eaa3881b01a2464d2a155ad49cc78162571dececcef555400666c719a60794d |
| audacity-win-2.1.0.exe | 74d62afa0407fa7746ddeb24b3bf0e10192c045bb9414d824f3803cb69eb9d3e | | 74d62afa0407fa7746ddeb24b3bf0e10192c045bb9414d824f3803cb69eb9d3e |
| FileZilla_3.15.0.1_win64-setup.exe | n/a | [https://sourceforge.net/projects/filezilla/files/FileZilla_Client/3.15.0.1/FileZilla_3.15.0.1.sha512/download](https://sourceforge.net/projects/filezilla/files/FileZilla_Client/3.15.0.1/FileZilla_3.15.0.1.sha512/download) The irony, at least for the latest version it is on their [website](https://filezilla-project.org/download.php?show_all=1) (click on the 'i') | c268afcd1c134f13cb651d5dbfdef1dfada0d6088638c269c292671396b4e8d7 |

So as far as I can tell sourceforge.net does indeed provide clean downloads for now. However sourceforge does seem to serve slightly outdated versions of some of the programs.

**Note:
This however does not confirm or deny that *all* downloads are clean nor does it mean that sourceforge.net will provide clean downloads in the future.**

**Comment by gorhill** [comment]
Thanks for spending time researching some of this. I might remove them from badware risks this week-end.

**Comment by war59312** [comment]
Personally I'd wait 30 days. Just saying.

Better safe than sorry. Your call of course.

**Comment by gorhill** [comment]
I commented out the `sourceforge.net` filter, I feel comfortable doing so with recent changes.

**Comment by RoxKilly** [comment]
A relevant article was published by [Ars Technica on June 17, 2016](http://arstechnica.com/information-technology/2016/06/under-new-management-sourceforge-moves-to-put-badness-in-past/)
