### ISSUE TITLE
uBlock Breaks Euroleague.net Live-Stats JS-based Navigation

### ISSUE THREAD

**Issue by nuliukas** [gorhill/uBlock#939]
uBlock breaks Euroleague.net live-sats JS-based navigation. See, for instance [here] (http://live.euroleague.net/gamesjs.aspx?ig=euro_57&st=20&dp=FELG2F36D462124FF8C22437G&z=0). Clicking on the tabs and buttons with uBlock enabled does not do anything. With uBlock disabled, it works as it should.

**Comment by gorhill** [comment]
Purge _uBlock filters -- Unbreak_ then for an update by clicking _Update now_.

**Comment by nuliukas** [comment]
It works! Thank you very much! :-)

**Comment by ryanbr** [comment]
https://hg.fanboy.co.nz/rev/22d99e9b87c5
