### ISSUE TITLE
0.9.4.5 stills shows 0.9.4.4 in popup and dashboard

### ISSUE THREAD

**Issue by ozar** [gorhill/uBlock#94]
I've installed 0.9.4.5 three different times on Firefox and it's still showing as 0.9.4.4 on the dashboard page, and in the uBlock popup.  Shutting down Firefox and restarting it didn't help.  Am I doing something wrong during the install to cause this behavior?

**Comment by weakptr** [comment]
No, you're not doing anything wrong. The version number wasn't updated in install.rdf

**Comment by gorhill** [comment]
It's because 0.9.4.5 is only for Opera, and I forgot to change version number for Chromium/Firefox platform. Travis will just build all package regardless. From a Firefox build point of view, there is virtually nothing new in 0.9.4.5 -- so no worry, you are not missing anything.
