### ISSUE TITLE
Don't block Google Pagespeed Beacon (by default)

### ISSUE THREAD

**Issue by DuckDagobert** [gorhill/uBlock#942]
Hi,

ublock origin blocks the (ngx) Google pagespeed beacon (e.g. for lazyloading) by default, which should not happen.

Please fix it.

**Comment by gorhill** [comment]
No clue what you are talking about.

uBO blocks whatever the filter lists tell it to block.

**Comment by lewisje** [comment]
DuckDagobert, do you have an example of a URL where the ngx PageSpeed beacon is blocked? I might be able to figure out a URL pattern to whitelist it and possibly what filter-list is blocking the beacon, so the issue can be reported with the list maintainers.

**Comment by DuckDagobert** [comment]
Hi lewisje, thanks!
you can see the pagespeed beacon here https://goo.gl/tHsW7c
It normally is  http://mydomain/ngx_pagespeed_beacon?url=

I saw some people use this "^/ngx_pagespeed_beacon$" in nginx.conf to match it.

**Comment by Kirkis** [comment]
Hi,
On httpd, the default beacon is called:
/mod_pagespeed_beacon

**Comment by IDKwhattoputhere** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out which filter list blocks it and report to the maintainers. This is not the place to discuss filters.

**Comment by IDKwhattoputhere** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out which filter list blocks it and report to the maintainers of that list. This is not the place to discuss filters and you can't be helped here.

**Comment by eladkarako** [comment]
<sub>interesting (although this issue is closed for a long time I've came across a got similar case)
maybe trying this will help to isolate the problem?
`@@*$important,beacon` (w/wo `,domain=yourdomain.com`)
if the rule above will not help, it means you can not override it with the general rule-engine,
so it might be hard-coded somewhere..</sub>

**Comment by camlafit** [comment]
Hi

Issue is yet open on easy list editor : 
https://forums.lanik.us/viewtopic.php?f=64&t=28154&p=85520&hilit=ngx_pagespeed_beacon#p85520

Doesn't look solved actually.
