### ISSUE TITLE
Default browser font does not work well for dynamic filtering panel

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#943]
At least for Linux/Firefox -- the default browser font is too wide.

Just like uMatrix, consider shipping with the optimal font to be used for the dynamic filtering panel.

**Comment by lewisje** [comment]
For your specific distro, are you talking about DejaVu Sans?

I'd consider just widening the popup UI to compensate, and then allowing Segoe UI *et al.* to be too narrow.

**Comment by gorhill** [comment]
> For your specific distro, are you talking about DejaVu Sans?

I don't know what Firefox is using for `Sans-serif`, it does look like DejaVu Sans:

![a](https://cloud.githubusercontent.com/assets/585534/11196824/5e1527c4-8c87-11e5-948e-cae5204651e7.png)

I myself usually change this to Droid Sans:

![c](https://cloud.githubusercontent.com/assets/585534/11196832/6a0d9d86-8c87-11e5-8af6-55426c3ba1cf.png)

By packaging a specific font, I ensure uBO will look the same regardless of the platform.

**Comment by lewisje** [comment]
I guess if you were curious enough, you could set up a page with the text font set to `sans-serif` and then use the Web Inspector to see the computed font; anyway I wonder whether subsetting or something similar could be reliably done, to reduce the additional size in the extension package.

**Comment by Goderw** [comment]
From my point of view the default font DejaVu Sans is extremely legible - despite or perhaps it takes up more space. Both facts stand in contrast to Droid sans... and I think legibility is much more important. So far I am not yet come across that some writings would have come off screen... I use also the German translation and German words use sometimes even more space than English ones. In terms of the size of the resulting extension package and also that you come across to prescribe a special font to a user, which he probably sees as "ugly", I would not even give me so much work to accomplish this little thing and to create by the way possibly discontent.

**Comment by Goderw** [comment]
Addition: 
I am very pleased that this extension follows my font settings in particular because for me under Linux the entire system uses DejaVu Sans... so that the overall picture inserts this extension into the perfect.

**Comment by gorhill** [comment]
Forcing the pluses and minuses to monospace takes care of the issue.
