### ISSUE TITLE
Microblock causing vimium hints to be hidden

### ISSUE THREAD

**Issue by mijoharas** [gorhill/uBlock#945]
I've come across some pages that cause uBlock to insert the following css into the page:

```
<style>
div[style^="left: "], a[href="http://www.spendcrazy.net/"], a[href="http://www.spendcrazy.net"], .MClose, .ad.super, #header + #content > #left > #rlblock_left, #content > #right > .dose > .dosesingle, #content > #center > .dose > .dosesingle {
    display: none !important;
}
</style>
```

The original `div[style^="left: "]` causes vimium link hints to be hidden. I'm having trouble tracking down exactly where in the code this gets added could anyone help me debug how the above style tag gets added?

**Comment by gorhill** [comment]
Can you look from which filter list this comes from? I see one instance in EasyList:

    animenova.tv,animetoon.tv,gogoanime.com,goodanime.eu,gooddrama.net,toonget.com##div[style^="left: "]

I do not maintain EasyList, you will have to report to EasyList maintainers.

**Comment by mijoharas** [comment]
I just came back to close this issue as I dug in further and found the list. Sorry for posting before investigating further.

**Comment by mijoharas** [comment]
oh and thanks for a brilliant extension. :+1:
