### ISSUE TITLE
No adblocking on spiegel.de

### ISSUE THREAD

**Issue by TimeForAChange** [gorhill/uBlock#946]
I got confused by the uBlock competition: https://github.com/chrisaljoudi/uBlock/issues/1573#issuecomment-157192304

Anyway, I tried _this_ uBlock on both Chrome and Firefox, latest version of everything, and the spiegel.de ad shows up. According to some other comments this should be blocked by an inline script block?

**Comment by TimeForAChange** [comment]
Update: I found https://www.reddit.com/r/uBlockOrigin/comments/3sizv9/help_hiding_elements_on_spiegelde/ but the ad DOES still show up.

**Comment by TimeForAChange** [comment]
Update: I found https://www.reddit.com/r/uBlockOrigin/comments/3sizv9/help_hiding_elements_on_spiegelde/ - unfortunately I use Chrome...

**Comment by harshanvn** [comment]
As said in the other thread, Inline script tag filtering only works in Firefox for the moment. So, using firefox with uBlock Origin should work for you.
also, you can take a look at the <a href="https://github.com/gorhill/uBlock/blob/master/assets/ublock/filters.txt">filter list</a> for the remaining german sites, where this version blocks the ads properly -

**Comment by TimeForAChange** [comment]
That last link, I copied the last paragraph into "My Filters" - should that work on Chrome too (because it doesn't)? As I said above, I got it working with Firefox so all that's left is a Chrome solution.

**Comment by harshanvn** [comment]
> I copied the last paragraph into "My Filters"

You don't need to. uBlock Origin ships those filters by default.

> should that work on Chrome too

No it will not. These filters (containing <code>example.com##script:contains(<string>)</code> will only work in Firefox. Not Chrome/Opera or any chromium based browsers.

**Comment by gorhill** [comment]
> confused by the uBlock competition

It's not competition (which would benefit users), it's a scam -- an abandonware advertised as currently developed on its donation page.

**Comment by gorhill** [comment]
The more people star the [chromium issue](https://code.google.com/p/chromium/issues/detail?id=168175), the more chance it will be addressed.

**Comment by harshanvn** [comment]
Not sure, what their stand on this now. It looks like the one devloper (Rob Wu), who supported these events (onbeforescriptexecute,..) is withdrwawn his support and suggesting a rather different approach..
More info here..https://groups.google.com/a/chromium.org/d/msg/blink-dev/bChX6leKqtg/Cj9bvbceDQAJ

@gorhill I think you might aware of this conversation already.

**Comment by gorhill** [comment]
> I think you might aware of this conversation already.

I wasn't aware the thread was brought back from the dead.

I think I will just pitch in to demonstrate uBO's specific use case. @Rob--W says that this can be worked around (and provide an example of how to do so), but this is something blockers will always have to deal with -- anti-blocker schemes trying to work against the users' choices. `beforescriptexecute` just add one more tool in the arsenal on the users' side. Still I will welcome any new idea which put the user in full control ultimately, web standards should prevent browsers to be turned into proprietary devices -- so if something even better than `beforescriptexecute` can see the day of light, that would be great, though at some point this has to materialize into reality.
