### ISSUE TITLE
Element hider bug on flash ads

### ISSUE THREAD

**Issue by b0nk** [gorhill/uBlock#947]
Steps to reproduce:

1 Fresh firefox 42.0 install
2 Ublock origin default settings + update default lists
3 Go to http://www.dn.pt/sociedade/interior/ilda-e-a-menina-da-brasileira-ha-52-anos-cafe-abriu-ha-110--4891695.html
4 Scroll to the near bottom of the page there should be a flash ad on the right side of the page
5 Use ublock element hider on the flash ad
6 The click "goes through" and opens the ad

**Comment by gorhill** [comment]
Firefox-specific quirk: won't fix.

Firefox does not relay click events to listeners when clicking on a Flash-based elements.

Workaround: set Flash plugins to "Ask to Activate". There are no good reasons nowadays to allow Flash-based elements to load and play by default.

**Comment by b0nk** [comment]
Thank you for the tip. Keep up the amazing work.
