### ISSUE TITLE
Block ad videos playing automatically

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#949]
I am not sure whether there's anything you can do, but:

chip.de has videos that play automatically when loading a site, which is extremely annoying. After a few seconds of loading the normal videos, an ad video starts playing.

You can find an example here:
http://www.chip.de/news/Halbvoll-in-2-Minuten-Huawei-zeigt-neue-Superakkus_85752247.html

Is there anything that can be done about this, or is this a matter of up-to-date filter lists?

**Comment by lewisje** [comment]
It probably does have to do with up-to-date filter lists; also make sure you're subscribed to EasyList Germany.

**Comment by gorhill** [comment]
Same issue exists with ABP, so it's a filter list issue. Report to maintainers of EasyList Germany: <https://forums.lanik.us/viewforum.php?f=90>.

**Comment by jjacquess** [comment]
he tried: https://forums.lanik.us/viewtopic.php?f=90&t=26232

Not a filter issue, it's server side include ads - a system which can't be broken (VAST).
https://forums.lanik.us/viewtopic.php?f=62&t=26352 (another system)

https://easylist.adblockplus.org/blog/2012/10/07/aktuelle-probleme-mit-videoportalen

here in france same on http://www.canalplus.fr/ (checked with your logger tool)

**Comment by gorhill** [comment]
I see, it's not a filter list issue, it's rather a site which found a way to bypass a user's blocker. I may want to look into this eventually.

**Comment by gorhill** [comment]
If using the latest dev  build, adding these two filters:

    ||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/hd-main.js$script,domain=cdnapi.kaltura.com
    ||hgc.svonm.com/hd-main.js$script,domain=cdnapi.kaltura.com

Will cause the video ads on `chip.de` to be properly blocked -- you won't see anymore the numerous network requests like `[...].3.damoh.chip.de`.

**Comment by akks1981** [comment]
||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/hd-main.js$script,domain=cdnapi.kaltura.com
||hgc.svonm.com/hd-main.js$script,domain=cdnapi.kaltura.com

dont work with dev beta 3! dev beta 1 works perfekt and block the video ad!

greetings

**Comment by gorhill** [comment]
I changed things a bit for b3, I am still fine tuning the feature.

If you purge all the cache from the 3rd-party filters pane, it should work fine thereafter.

**Comment by akks1981** [comment]
ok deleet the firefox cache and all the cache from the 3rd-party filters pane the it works now perfekt, like dev beta 1! big thx

**Comment by seanrand** [comment]
@gorhill will you make redirect-resources.txt available through a new tab in the advanced UI once it's stable? Would be handy to be able to add own destinations for redirect rules.

**Comment by TonyTough** [comment]
Hello,

a lot of popular german news sites seem to use now this intrusive new method like
www.welt.de
i.e: http://www.welt.de/politik/ausland/article149235570/Hollande-und-Obamas-klare-Botschaft-fuer-Moskau.html
http://www.welt.de/politik/article149038801/Das-ist-die-Realitaet-in-einer-Berliner-Brennpunktschule.html

and www.focus.de
i.e: http://www.focus.de/politik/videos/nach-abschuss-von-russischem-kriegsflugzeug-rettungsversuch-mit-fallschirm-zeigt-dieses-video-wie-auf-die-piloten-geschossen-wird_id_5109613.html
http://www.focus.de/gesundheit/videos/zeichen-der-haut-das-verraet-die-stelle-des-pickels-ueber-ihre-gesundheit_id_5109486.html

**Comment by gorhill** [comment]
I wasn't able to see a single ads in the above linked videos.

**Comment by TonyTough** [comment]
The two focus.de links give me ads each time with a countdown at the top.

The two welt.de links not every time, but mostly, countdown at the bottom of the video.

Maybe this depends on geolocation of the IP address?

**Comment by gorhill** [comment]
> Maybe this depends on geolocation of the IP address?

Tried to reproduce, could finally reproduce by enabling Flash plugin. So the solution is simply to disable Flash plugin in your browser.

**Comment by TonyTough** [comment]
OK, thanks.

**Comment by nick75e** [comment]
Hello!
About your new redirect engine (which I think is a great idea!), there's this new firefox addon [Decentraleyes] (https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) that tries to do the same thing.
You could contact the developer and perhaps integrate it into uBlock.

See also:
https://github.com/Synzvato/decentraleyes
http://www.ghacks.net/2015/11/23/decentraleyes-for-firefox-loads-cdn-resources-locally/

**Comment by gorhill** [comment]
> that tries to do the same thing

Not the same thing at all. uBO's redirection is closer to my understanding of NoScript's surrogates (to be clear I never looked into the specifics of NoScript's surrogates). What I am trying to do here is to prevent some sites from causing users to disable uBO, and as a result dropping all protections provided by the blocker.

**Comment by akks1981** [comment]
why after a restart of firefox or my pc, i must delete the cache from the 3rd-party filters pane manually before it works?? 1.3.7b7

**Comment by gorhill** [comment]
This was an issue prior to b7, should be fine from now on -- problem was that the redirection data was not part of the selfie, fixed in b7.

**Comment by tobbi** [comment]
http://www.myvideo.de/themen/der-kleine-nils/der-kleine-nils-hartz-iv-keuchhustenhotline-hoer-mal-wer-da-spricht-video-m-6946784 also has ad videos that play automatically (I decided not to open issues needlessly).

**Comment by gorhill** [comment]
@tobbi This is a different issue, the player code is not the same as the one used for chip.de. I can't  get any videos to play: _"Dieses Video ist auf ihrem Browser oder Gerät leider nicht verfügbar."_

**Comment by tobbi** [comment]
Hmm. Do you want me to open a new issue re. this video?

**Comment by Hrxn** [comment]
> "Dieses Video ist auf ihrem Browser oder Gerät leider nicht verfügbar."

Hu? Okay this is a bit off..

I just tested with an US-based IP (VPN), and I got this:
_"Dieses Video ist in deinem Land nicht verfügbar."_

So, it definitely is geofenced.

Maybe the site tries to enforce the Flash player, and you get this other error if you have turned off Flash in the browser..

**Comment by tobbi** [comment]
From what I can tell, the script responsible is http://s4.myv-img.de/304/javascripts/simad.js

**Comment by tobbi** [comment]
I can see another automatic ad video on http://www.welt.de/videos/article139034591/Wenn-im-Todestrakt-das-Gift-ausgeht-Gruende-und-Folgen.html Can anyone reproduce?

**Comment by akks1981** [comment]
tobbi no video ad with ubO 1.7.2b2 and Firefox 47beta 9 and flash disabled!

greetings
