### ISSUE TITLE
Location of uBo font based icons

### ISSUE THREAD

**Issue by Goderw** [gorhill/uBlock#950]
The icons in the dashboard are indeed font based. If I do not like that pages can load fonts under circumstances from 3rd party sites, I can shut the font download in about: config (by setting gfx.downloadable_fonts.enabled;false). 

But since then the icons in ublock origin dashboard do not appear - I wonder now: Where is the origin of the uBo font icons ... or is it here to speak only a "local download" (font is implemented in code and no internet download is accomplished to get them)?

**Comment by gorhill** [comment]
Firefox: `chrome://ublock0/content/css/fonts/fontawesome-webfont.ttf`
Chromium: `chrome-extension://pbffolnficoggnnamkphaffidiafpeaf/css/fonts/fontawesome-webfont.ttf`
