### ISSUE TITLE
Support subscribe links

### ISSUE THREAD

**Issue by szepeviktor** [gorhill/uBlock#951]
Adblock Plus support:
- https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/szepeviktor/lean-filter/master/leanfilter.txt&title=Lean%20filter (non-existent subdomain)
- ~~abp://https://raw.githubusercontent.com/szepeviktor/lean-filter/master/leanfilter.txt~~
- abp:subscribe?location=https://raw.githubusercontent.com/szepeviktor/lean-filter/master/leanfilter.txt

Please consider supporting something like it.

**Comment by szepeviktor** [comment]
`abp:` seems to be supported.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/blob/master/src/js/subscriber.js#L56

[abp:link](abp:subscribe?location=https://raw.githubusercontent.com/szepeviktor/lean-filter/master/leanfilter.txt) (at least one abp: link required?)

**Comment by 5t3f4n** [comment]
This is already supported, but it seems you have to click a link form a site. Copying the URL and pasting in your URL bar does not seem to work. You can test for yourself [here](https://adblockplus.org/features).

Example 1: [clicking a link](https://i.imgur.com/ZoQ12qf.png)
Example 2: [entering the URL](https://i.imgur.com/OlyFQDc.png)

**Comment by gwarser** [comment]
Sorry, my browser hangs, and I accidentally removed my comment.
It seems this feature works only on pages with at least one `abp:` link (I cannot create one on github to test it here)
https://github.com/gorhill/uBlock/blob/master/src/js/subscriber.js#L56

**Comment by szepeviktor** [comment]
@5t3f4n Yes, that is a pseudo URL, only for links.

**Comment by szepeviktor** [comment]
@gwarser My problem is the same: I this pseudo URL ( https://subscribe.adblockplus.org ) beacuse GitHub does not allow the `abp:` scheme.

**Comment by szepeviktor** [comment]
It would be nice to support this or another pseudo URL.

**Comment by szepeviktor** [comment]
@gorhill Thank you very much.

**Comment by happysurf** [comment]
No more works for me because is open only the .txt page instead the subscription dialog window.
Firefox 43beta7 + UBO  1.3.7b8.

**Comment by gorhill** [comment]
@happysurf what link exactly are you trying to click?

**Comment by happysurf** [comment]
Any" Subscribe" links on https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web but also on Prebake page button or on the page http://www.kiboke-studio.hr/i-dont-care-about-cookies/ links like:
http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/
abp:subscribe?location=http://www.kiboke-studio.hr/i-dont-care-about-cookies/

**Comment by gorhill** [comment]
> Any "Subscribe" links on https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web 

Works fine from here. Are you clicking the **subscribe** link? The link above the **subscribe** link is to go to the list's site so that one can look at the list before installing it.

**Comment by happysurf** [comment]
I know, in any case I tried Firefox 43 beta + uBO 1.3.7b10 in a clean profile and works.
Then I discover the culprit, the Clean LInks extension change the link on the fly.
Thank you for support.
