### ISSUE TITLE
[Firefox] Exit from element picker

### ISSUE THREAD

**Issue by szepeviktor** [gorhill/uBlock#953]
It would be nice to cancel element picker by pressing <kbd>Esc</kbd>

**Comment by gorhill** [comment]
It's already like this.

**Comment by szepeviktor** [comment]
When I see red rectangles, Esc does nothing.

**Comment by gorhill** [comment]
When I see red rectangles, Esc quits the element picker mode.

This is why the content of [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) is very important when reporting issues.

**Comment by szepeviktor** [comment]
Maybe my alpha Firefox 44 is the cause.
Sorry.

**Comment by gorhill** [comment]
I tried on Nightly 44 and it still work fine.

**Comment by gorhill** [comment]
> Only after selecting something and deselecting it makes Esc functional

Ok, I can reproduce with Nightly 44 (not with Firefox 42 though).

**Comment by szepeviktor** [comment]
Thank you. 


-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!

**Comment by tobbi** [comment]
Is this still the case? I am asking because I can't exit element picker mode using Esc on my Firefox Nightly 55.0a1 (2017-05-26) (64-bit). uB0 version 1.12.5rc0

I am wondering whether this is the bug I am experiencing or whether it's something different.

**Comment by Atavic** [comment]
>Is this still the case? 

Issue is open, so Yes.

**Comment by Betsy25** [comment]
Suffering from the same issue, the "workaround" gorhill explained on [Wilderssecurity forum](https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-111#post-2681028) does indeed make it trigger as expected. Something is blocking the ESC key to trigger using the "normal" procedure.

**Comment by gorhill** [comment]
It's a difficult one to crack. When uBO's popup panel closes, the focus seems to be in limbo, and calls by uBO to set the focus to the picker are ignored. Pressing shift-tab brings back the focus to the page and key events starts to be properly reported to uBO's picker.

**Comment by FX54** [comment]
Bug on x64 plaforms in Firefox? unable to reproduce in Windows 7 Pro x86.

**Comment by szepeviktor** [comment]
@FX54 Could you open a bug?

**Comment by FX54** [comment]
In [bugzilla](https://bugzilla.mozilla.org/)? I think I will not rave there.

**Comment by FX54** [comment]
about:config
```
browser.tabs.remote.autostart;false
browser.tabs.remote.autostart.2;false
```

I can not create bug file.

**Comment by gorhill** [comment]
Unable to reproduce in latest Nightly.

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/8yiers/hold_mouse_button_delete_to_quickly_zap_elements/
