### ISSUE TITLE
uBlock Origin sometimes doesn't automatically update filters

### ISSUE THREAD

**Issue by vgturtle127** [gorhill/uBlock#954]
First, my setup.

I am using 64-bit Firefox 42.0 EME-free version on all three systems.

All systems are running 64-bit Windows 10 Pro.

All systems have uBlock Origin, HTTPS Everywhere, and Privacy Badger installed.

All systems are identical in every way, except for hardware.

If you would like the hardware specs, let me know. I don't think it is relevant though.

The issue seems to occur on the two systems that aren't mine. The other two systems don't update the filter lists unless I do it manually.

I have tried uninstalling and reinstalling Firefox, the addons, and plugins, I have tried disabling other addons, I have tried restarting, I have tried completely removing everything and starting over, I have tried to replicate the issue on my system, etc.

I can't seem to figure out why this happens. All I can assume is that it is a bug.

All three uBlock versions were at version 1.3.4 until today I updated them to 1.3.5.

Nothing has changed.

The logger acts like everything is fine, because the logger is never on when the issue happens.

Any testing, additional information, or help would be greatly appreciated.

Attached are screenshots of all settings.

![screenshot 4](https://cloud.githubusercontent.com/assets/3183676/11313644/0b58dd6c-8fa4-11e5-94c2-dfcab156dd99.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/3183676/11313645/0b5bfc22-8fa4-11e5-9316-570f7f969510.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/3183676/11313647/0b5ce074-8fa4-11e5-9c5c-6b321fb64451.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/3183676/11313646/0b5c41e6-8fa4-11e5-8f68-4b4828099710.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/3183676/11313648/0b5fe666-8fa4-11e5-89f6-700f00ac8ffd.png)

**Comment by gorhill** [comment]
> The other two systems don't update the filter lists unless I do it manually.

I did you come to this conclusion?

**Comment by vgturtle127** [comment]
@gorhill What do you mean? They always have outdated filters, unless I download updates manually. Then when they update, uBlock says they are out of date, but doesn't update them automatically.

**Comment by gorhill** [comment]
So if I understand your answer, they have the label `out of date` attached to them? And this _never_ goes away? Does this apply to all filter lists?

**Comment by vgturtle127** [comment]
Yes, yes, and yes. :laughing:

**Comment by gorhill** [comment]
Purge all caches, quit the browser, launch the browser, open the logger, set the logger's selector it to "All", open the browser console and leave the browser on idle for 1 hour. Come back after one hour, see what the logger says, uBO's requests to fetch the filter lists should be recorded in the logger. If the filter lists were not properly updated, look into the browser console for error messages.

**Comment by gorhill** [comment]
By the way, there is no out of date filter lists in your screenshot of the _3rd-party filters_.

**Comment by vgturtle127** [comment]
@gorhill Those were taken on my PC, not the affected systems. I wanted to show what filters I was using.

I will do that to the affected PCs.

**Comment by gorhill** [comment]
I am also running the test to provide reference screenshots of how things should look like.

**Comment by gorhill** [comment]
Here:

![a](https://cloud.githubusercontent.com/assets/585534/11315144/6e7e2a98-8fbb-11e5-9f08-7247352e6f9b.png)

As you can see, the filter lists were fetched as per logger (the `xhr` requests), and the browser console confirms the fetching went fine (`200 OK` status).

**Comment by vgturtle127** [comment]
OK, let me re-run the tests on the affected machines to see if I can get the same result.

**Comment by vgturtle127** [comment]
The issue was fixed when I re-installed Firefox and uBlock. Sorry, it appeared to be an older version was conflicting with the new version. 32-bit to 64-bit Firefox installs are a bit buggy.
