### ISSUE TITLE
uBlock Origin 1.3.4 (and next) broken in Firefox for Android Release (42.0.1) until I disable/enable

### ISSUE THREAD

**Issue by Ronnie91** [gorhill/uBlock#955]
Hi,
I'm sorry for my poor english. 

Reflected the same problem: https://github.com/gorhill/uBlock/issues/749 but with uBlock Origin 1.3.4 (and next) in Firefox for Android Release (42.0.1).

Waiting for news, thanks in advance.

**Comment by gorhill** [comment]
Tried FF for Android 42.0.1 with uBO 1.3.5 and all was fine.

What exactly is "broken"?

**Comment by MadClown** [comment]
I'm also having the same problem on 4 of my devices. It also started happening on version 1.3.4. It's almost guaranteed that uBlock Origin won't start until I disable then enable, at least on my slower devices.

**Comment by gorhill** [comment]
If you install <https://addons.mozilla.org/en-US/android/addon/console/>, is there anything related to uBO in the console?

**Comment by Ronnie91** [comment]
![tmp_1540-screenshot_2015-11-21-07-01-35-1-1778461635](https://cloud.githubusercontent.com/assets/15952258/11317014/136be95c-901e-11e5-89fd-6d4657277f73.png)

**Comment by MadClown** [comment]
Those are the same errors I get.

**Comment by gorhill** [comment]
Can someone with the issue try the `xpi` from latest dev build? (can non-signed `xpi` be added, I am not in a position to test myself).

<https://github.com/gorhill/uBlock/releases/tag/1.3.6b2>

**Comment by Ronnie91** [comment]
This resolves for me.

It can add xpi not signed to Firefox for Android.

Thanks, good work.

Best regards

**Comment by gorhill** [comment]
Just before I pusblish the fix with an official release version, is it possible to confirm rc0 works fine?

rc0 => <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>

I currently have no access to an android device, there is no way for me to test all is fine.

**Comment by Ronnie91** [comment]
Yes, works fine.
