### ISSUE TITLE
inline script filter for all sites and wildcard for single character

### ISSUE THREAD

**Issue by geokis** [gorhill/uBlock#957]
Hello,
I try to create a filter rule to block an inline script for all visited sites. So I tried:
```
##script:contains(function(n, t, e))
*##script:contains(function(n, t, e))
*.*##script:contains(function(n, t, e))
```
Nothing is working. Is it possible to create this kind of filter?

In most cases I use the script filter for the **Addefend** Ads. I have noticed, that the inline script for Addefend,  always have the same logic with two or three different arguments that are only one character long. Example:
```
function (w, g)
function (n, t, e)
function (a, b)
```
If we had a wildcard for a single character, we could blocking this ad-type for the most sites.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/releases/tag/1.2.0

**Comment by geokis** [comment]
So, I think you want to draw my attention on this:
>Caveats of current implementation:
>   The filter must apply to a **specific hostname** or entity. Generic script tag filters will be rejected.

Okay...sorry for the question.
I hope it will be introduced soon.

**Comment by gorhill** [comment]
> I hope it will be implemented soon.

I currently do not intend to implement this.

**Comment by lewisje** [comment]
Also, @geokis, if we had a wildcard for single-character arguments in a function, that would lead to major false positives.

**Comment by geokis** [comment]
Maybe you are right. I don't have enough experience to evaluate this.
It was an idea based on my practice with this Ad-Type. The first what I do, is to looking for a huge inline script that begins with  ~ `function( *, *)` or `function( *, *, *)` 

So,  thanks for your effort.

**Comment by lewisje** [comment]
In the world of minified scripts, you'll encounter *tons* of anonymous functions with two or three parameters with single-character names, hence false positives.
