### ISSUE TITLE
Button in context menu gone

### ISSUE THREAD

**Issue by JIscariot33** [gorhill/uBlock#958]
Hiya,

since updating to 1.3.5 the button in the context menu disappears after each start of Firefox (mine is 42). I have to (re)activate this option (uncheck and check) each time using the dashboard for it to appear again. Done on purpose or just an error? 
Thx in advance.

J.

**Comment by gorhill** [comment]
I can't reproduce. Provide me **all** the detailed step on how you reproduce it (as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)).

**Comment by publicarray** [comment]
Maybe setting the button to legacy mode will help?  https://github.com/gorhill/uBlock/wiki/Troubleshooting

**Comment by JIscariot33** [comment]
Sorry for the late response. I worked it out myself. The HDD has defective sectors. I transferred the folder (it's portable) to a different drive. Everything is working fine now. Thanks for your help here and via email.
J.
