### ISSUE TITLE
AJAX loaded content not blocked

### ISSUE THREAD

**Issue by shouya** [gorhill/uBlock#961]
This problem can be reproduced by adding the rule:

    twitter.com##.promoted-tweet

The expected effect is to block all promoted tweets. However, if you scroll down the page and wait for the new content to load by ajax. You'll see some new promoted tweets that obviously match the rule but ain't blocked.

**Comment by gorhill** [comment]
You don't need that cosmetic filter, it's already ni EasyList. You will have to disclose all the settings which are not the default ones. Here are reasons of why cosmetic may not be applied: <https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappear-when-you-reload-the-page>.

See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by shouya** [comment]
Yes, the problem was caused by putting `twitter.com` into the whitelist. Sorry, it was a wrong guess. I'm closing this issue since the problem has been resolved.
