### ISSUE TITLE
Firefox 42 and cosmetics

### ISSUE THREAD

**Issue by Zulen** [gorhill/uBlock#963]
Sorry, if my short video is not clear to understand the issue: 
https://youtu.be/B-8gLtS2PfM

**Comment by gorhill** [comment]
The site is probably adding the blocked element after uBO injected its styles + adding `display: block;` style directly to the element. I made a fix for this I did a while ago, stashed somewhere.

**Comment by Zulen** [comment]
Is there any progress? :)

**Comment by stankarp** [comment]
Same issue appeared on vk.com 2 days ago. Ads started to popping through uBlock.

**Comment by UksusoFF** [comment]
> Same issue appeared on vk.com 

Confirm this

**Comment by gorhill** [comment]
Can you see if the latest 1.7.7b0 fixes the issue?

**Comment by Zulen** [comment]
Yes. Great!

**Comment by gorhill** [comment]
Fixed with the refactoring of cosmetic filtering code content script-side.
