### ISSUE TITLE
uBlock popup is not shown (Firefox, Vimperator)

### ISSUE THREAD

**Issue by demokritos** [gorhill/uBlock#964]
I am using Firefox with Vimperator extension, which hides the nav-bar. So I customized the toolbar and moved the uBlock toolbar button from the nav-bar to the tab-bar. With this setting, I cannot see the popup when I press the button.
If I make the nav-bar shown (using Vimperator javascript command `:js document.getElementById('nav-bar').collapsed = false;`), I can see the popup.

**Comment by gorhill** [comment]
Try: force `extensions.ublock0.forceLegacyToolbarButton` to `true` in `about:config`.

**Comment by demokritos** [comment]
Thank you for the quick reply. 
It is working.

**Comment by dschrempf** [comment]
Fix works but this is still an issue.

**Comment by gorhill** [comment]
How is this an issue if it works?

**Comment by gorhill** [comment]
> moved the uBlock toolbar button from the nav-bar to the tab-bar. With this setting, I cannot see the popup when I press the button

I do see uBO's popup panel when its icon sits in the tab bar.

**Comment by dschrempf** [comment]
It does not work by default if the nav bar is disabled.

**Comment by homeworkprod** [comment]
Thanks for the workaround (I'm using Vimperator as well); it works, and I've now seen the popup in Firefox for the first time. Too bad the workaround is necessary at all.

The popup looks (has no border) and behaves/"feels" a bit strange, though, but that has (partly) already been reported in other issues.

**Comment by gorhill** [comment]
Closing, since there is a workaround.

**Comment by corrupt** [comment]
I'm reopening this as the workaround does not work anymore now that uBlock Origin has become a WebExtension. 
Many of us vimperator users have moved to Firefox ESR (52.2 at the moment) now that Quantum has made the usage of non WebExtensions impossible. OP's problem ist still there for us, only uBlock doesn't store its settings in about:config anymore. 

**For people coming here through google looking for a fix in Firefox ESR**:
As per suggestion of [uBlock Origin's official wiki](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext), uninstall uBlock Origin and install [version 1.13.8](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=1#version-1.13.8), then disable updates for that. This will at least solve the problem for ESR users until about June 2018. Either vimperator will have adapted to Firefox' new APIs by then or moved on to Palemoon, Waterfox, or similar alternatives.

**Comment by gorhill** [comment]
> As per suggestion of uBlock Origin's official wiki, uninstall uBlock Origin and install version 1.13.8

Bad advice, installing the latest uBlock0-firefox.xpi, should work fine -- no need to ask people to install an older version. Reopening the issue will just be annoying, there is nothing I can do for the webext version.
