### ISSUE TITLE
$generichide and $genericblock now in ABP

### ISSUE THREAD

**Issue by lewisje** [gorhill/uBlock#967]
If you don't plan to support them, they should at least be mentioned in the Wiki; both options exist only for whitelist rules: https://adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock

`$generichide` is like `$elemhide` except that it disables only *generic* hiding rules, meaning hiding rules with no domain specifiers, or "with a few exceptions" (I might need to look into the code to see what is meant by "a few" but for now it looks like "a few" means "fewer than 1").

`$genericblock` is like `$document` except that it disables only *generic* blocking rules, meaning blocking rules with no `$domain` or `$sitekey` option, or "with a few exceptions" (in the same sense as above) in the `$domain` option.

The purpose of these experimental options is to whitelist the common generic rules that anti-adblock technology tests against, without painstakingly doing so on a script-by-script basis or outright allowing all content on a page.

**Comment by gorhill** [comment]
`generichide` is already supported -- this was easy, since this was how I implemented `elemhide` in the first place, to disable only generic cosmetic filters. The cosmetic filtering switch can be use to disable all cosmetic filters.

I am going to wait for an official release of ABP version with support for these filter options and see how often used and how useful they are before making a decision.

**Comment by gorhill** [comment]
For the time being I will decline implementing `generickblock`.

From what I see, this is ABP answer to some anti-blocker mechanisms, and I disagree with the approach: ABP's solution to work around anti-blocker mechanisms is to punch holes into the blocking filters, i.e. to _block less_. This is not a pro-users solution.

When time allows, I will be running comparative benchmarks to demonstrate this.

**Comment by toshiya44** [comment]
Will it be possible to support it as a user side setting? 
For example, we have the option to enable and disable `Parse and enforce cosmetic filters` , something like that.
