### ISSUE TITLE
Remove Javascript Restrictions Using uBlock

### ISSUE THREAD

**Issue by phone8588** [gorhill/uBlock#968]
How can uBlock be used to remove (strip) javascript restrictions from a web page - for example sites that don't let you right click on them or ones that don't let you select/copy text from the web page? Using the blanket option to remove all inline scripts break the web page and renders it useless in most cases.

Looking for similar functionality as the extension RightToClick (https://addons.mozilla.org/en-US/firefox/addon/righttoclick/) - given uBlock's capability it feels a waste to have a second extension running.

**Comment by gorhill** [comment]
Without details about a very specific issue, I can't repro, I can't investigate, and so I can't answer.

See <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.

**Comment by phone8588** [comment]
Look at page - http://www.imdb.com/media/rm1140695296/tt1430132?ref_=tt_ov_i

You cannot right click (to copy image) or select the main picture of Wolverine in the webpage - essentially Firefox's select/copy/paste tools are rendered ineffective by the javascript handlers.

**Comment by gorhill** [comment]
There is a `oncontextmenu="return false;"` on the image.

Blocking inline scripts fix this, but this maybe break something else on the page.
