### ISSUE TITLE
feature request: possibility to set update interval for filter lists

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#970]
Hello,

I would like to automatically update the filter lists every 24 hours. With current update cyclus they are often several days old and need a manual update.
Maybe it is possible to include an individual update interval setting in a future version?

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> Do NOT: [...] Submit feature requests.
