### ISSUE TITLE
feature request: possibility to activate/deactivate own filter lines with single mouseclick

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#972]
Hello,

it would be great if own filter lines and whitelists could be deactivated and activated with just a mouseclick (like in ABP), so that you don't have to add "!" or delete it in every line.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> Do NOT: [...] Submit feature requests.
