### ISSUE TITLE
Skip click-through sites without blocking.

### ISSUE THREAD

**Issue by dlazerka** [gorhill/uBlock#973]
Hello,

Currently, we're blocking click-through websites like googleadservices.com (e.g. [Veterinarian U-Block](https://www.google.com/aclk?sa=l&ai=C3J8qFPpUVt-KOIOj-gPP_bHQDu2yt7MHnbTplrgB3_jel78BCAkQASDezc8eKBRgyfb4hsijoBmgAbuYyP0DyAEHqgQnT9CPbbDmFeLfJBQNn66fZGSaD6LD4p9wV-NC3R3wrUpjZDkY3HOIwAUFoAYmgAet57cCiAcBkAcCqAemvhvYBwHgEuD58InotoDoHw&sig=AOD64_3r4dRSavyNjW_5b9JBJuWbf-J_sw&adurl=http://www.universalmedicalinc.com/veterinarian-u-block-with-pad-7-1-4-h-x-14-w-x-14-l.html&ctype=5&clui=1&q=&ved=0ahUKEwiHvcSnoqrJAhWHMogKHchkAvEQpysIBQ&ei=FPpUVofjNYfloATIyYmIDw))

But it would be nice to just show user their target page, instead of showing "page is blocked" for blocked click-through domain.

Here I wrote simple 15-lines chrome extension that does what I mean: https://github.com/dlazerka/clickthrough/blob/master/background.js
it would be nice to incorporate that to uBlock₀.

**Comment by gorhill** [comment]
Just click the magnifier in the lower right-corner of the offending URL, it will parse and expand URL parameters, where often the destination URL can be seen. Using your example:

![a](https://cloud.githubusercontent.com/assets/585534/11385167/1d844510-92e4-11e5-979f-8b2b5aafcac3.png)

**Comment by dlazerka** [comment]
Good to know, thanks.
