### ISSUE TITLE
uBo is causing CPU hog with imdb.com (popup video)

### ISSUE THREAD

**Issue by offhub** [gorhill/uBlock#978]
1. Google Chrome Version 47.0.2526.73 (64-bit) / Windows 7 SP1 / uBo 1.3.7
2. Default settings with "I am an advanced user" enabled. (All other extensions are disabled.)
3. Open: http://www.imdb.com/name/nm1111968/?ref_=tt_cl_t1
4. Go to "Releated Videos" section (scroll down)
5. Open one of the videos (it should popup on same page)
6. Wait until it loads, then close the popup (via X or ESC)
7. CPU usage will increase after closing the video and uBo extension will be unresponsive.

No problem with uBo 1.3.6

**Comment by gorhill** [comment]
I am unable to get a "popup" at step 5. A new page with the video opens instead, and all is fine.

**Comment by offhub** [comment]
I tested with 1.3.7 b1 and b4.

Replace ``` class=" " ``` with ``` class="video-colorbox" ```
Replace ``` data-context="ımdb" ``` with ``` data-context="imdb" ```

Try this: 
![eg-04249x](https://cloud.githubusercontent.com/assets/6871698/11424721/3ed1572e-9458-11e5-87aa-2b09b05da214.jpg)

**Comment by gorhill** [comment]
Ok, my mistake, I thought I had to click "Related Videos", while the step says "**Go to** Related Videos".

I can reproduce, will investigate.

**Comment by gorhill** [comment]
The page somehow ends up with an `iframe` which URL is `http://about:blank/`, i.e. an invalid URL -- it should be `about:blank`. So I have to make uBO ready to deal with such nonsensical URL.
