### ISSUE TITLE
Help with Vaughnlive ad

### ISSUE THREAD

**Issue by Dkzn** [gorhill/uBlock#979]
http://vaughnlive.tv/111aaacharkreality
If you block the ad at the bottom the whole video doesn't play.

https://adblockplus.org/forum/viewtopic.php?t=29907
The last post here works but I'd rather not install an extension for a single ad.

I couldn't find an answer on easylist, was wondering if you could find a fix.

**Comment by gorhill** [comment]
@@||vast.yashi.com$object,domain=vaughnlive.tv

**Comment by Dkzn** [comment]
Wow, I'm pretty sure I saw that somewhere and tried it.
Guess not. Thanks :P

**Comment by gorhill** [comment]
Can you report to EasyList maintainers, so that all benefit?

**Comment by Dkzn** [comment]
Sure.
