### ISSUE TITLE
Question about expired filters

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#98]
Hi, I have somethimes in filters list, that same are out of date and I must update them, but same have newer version and uBlock not alert me. How uBlock know that same filters have new version?

**Comment by lewisje** [comment]
The lists themselves mention how long they should be considered fresh, and uBlock keeps track of when the lists were downloaded; if a list doesn't explicitly mention an expiration date, uBlock assumes a default expiration (I think it's 5 days after download). Then, uBlock periodically checks the expiration dates for the lists, and if it finds some lists have expired, it checks for new versions, and if it finds new versions, it downloads them.

I'm thinking that the ones that have newer versions that uBlock hasn't told you about yet are the ones for which the expiration date hasn't passed; in particular, EasyList is updated several times per day, even though it specifies an expiration date 4 days after download: https://hg.adblockplus.org/easylist/

I'm thinking that uBlock wants to lessen the load on the servers hosting the subscriptions, so unlike ABP, there is no way to force an update check.

**Comment by marek45** [comment]
Thank's . This all information are very important to me.

**Comment by gorhill** [comment]
> How uBlock know that some filters have new version?

There is two ways for uBlock to determine whether a filter list needs to be updated:

1. uBlock's checksums file: if the local checksum does not match the remote checksum, the list will be marked as "new version available".
2. If the list is fetched from a remote server, the list will be considered obsolete after 4-5 days, regardless of whether the filter list has changed on the remote server.

**Comment by marek45** [comment]
How generate checksum to filter?

**Comment by gorhill** [comment]
I do. Your uBlock will download it.

**Comment by marek45** [comment]
But on easylist is line: ! Checksum: Kad++EkO4vL3k9xg1vd6Yw 
So generating checksum by filter autor is not nessesery.

**Comment by gorhill** [comment]
uBlock does not use the checksum embedded in filter lists.

**Comment by marek45** [comment]
Thank's. I no longer take your time.

**Comment by colaas** [comment]
Hi, I can't seem to update my filter lists. Purging the cache doesn't help.
For example, the EasyPrivacy list I have is from the 18th of April and the actual list has been updated today. The [checksum](https://github.com/gorhill/uBlock/blob/master/assets/checksums.txt) is not for my version nor for the latest version. Looking at wireshark quickly it seems ublock is not even contacting their server. (This is on 0.9.5.0)

**Comment by marek45** [comment]
Maybe clear all cache all filters and try update all filters.

**Comment by gorhill** [comment]
@colas Is EasyPrivacy marked as "obsolete" after you force an update?

**Comment by colaas** [comment]
No it's never marked as obsolete. Purge cache tooltip said 5 hours ago. I purged, applied and updated, now it says last updated a minute ago but it's still the same old list if you click on it.

**Comment by marek45** [comment]
If you open this list on browser by url then you see new version?

**Comment by gorhill** [comment]
@colaas How do you open the list? There is a known quirk in Firefox, if you open the list with the middle button, it will show you the one shipped with the extension, not the one currently in use.

**Comment by colaas** [comment]
Ah, yes, that's what I was doing, I never actually tried just left clicking. First time I hear of this quirk. Weird that I wasn't seeing traffic even after purging though. Thanks
Looking forward to uMatirx on FIrefox!

**Comment by marek45** [comment]
Something is wrong. This filters are update daily, but last update is 7 days ago. I use version 0.9.6.0 and enable autoupdate.
https://www.dropbox.com/s/3o529l2chyqoe28/adblock7.png?dl=0

**Comment by gorhill** [comment]
@marek45 Left-click on the filter list, what is the date in it?

**Comment by marek45** [comment]
I fix it. My Internet Provider use squid and it cached txt files to long. I reported this and it was repaired. Sorry and thank's for your time.
