### ISSUE TITLE
Suggestion: Need an uBlock icon in SeaMonkey's bottom status bar.

### ISSUE THREAD

**Issue by antdude** [gorhill/uBlock#980]
Hello.

With AdBlock Plus, I prefer and use its icon to be in the web browser's status bar instead of in the toolbar since it was smaller. I'd like to see the same for uBlock Origin's icon.

Thank you in advance. :)

**Comment by rcmero** [comment]
I usually just keep the uBlock icon on the bookmarks bar. 

It would be nice to add uBlock's icon to the status bar, but keep in mind Stylish doesn't add one either, and it's still compatible with SeaMonkey.

**Comment by wyatt8740** [comment]
I second this request. This is the one thing I miss from ABP.

**Comment by ektus** [comment]
Any news on this? I'm missing it badly :-(

**Comment by gorhill** [comment]
I will decline this one -- just do not have the time.

**Comment by wyatt8740** [comment]
@gorhill Whaaa!!??? That's terrible. You can even look at ABP's code as an example of how to do it. Would you accept a pull request?
