### ISSUE TITLE
Suspicious clone/scam attempt of uBO in Chrome Web Store

### ISSUE THREAD

**Issue by Hrxn** [gorhill/uBlock#981]
I was just playing around with a new profile, added uBO as my first extension, obviously - and then I saw this:

![scrnshot-cws](https://cloud.githubusercontent.com/assets/12064918/11431295/84a2d9fc-9495-11e5-9d5a-abbc4b7285ec.jpg)

Seems very fishy to me..

What I did:

* Open CWS
* Select search bar in upper left corner
* Searched for 'ublock origin'

**Comment by LimboSlam** [comment]
Yes this is a definite scam. He also has one for Adguard Adblocker.

**Comment by Hrxn** [comment]
BTW, I directly used the 'report' feature on CWS. Might take some time for them. Will happen faster the more people report, I guess ;-)

**Comment by gorhill** [comment]
Looks like it was removed: <https://chrome.google.com/webstore/search/ublock>.
