### ISSUE TITLE
Not able to create a redirect request for ga.js

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#982]
#### STR
1. create below entry in "My Filters" tab -<br/>
<code>||www.google-analytics.com/ga.js$script,domain=www.tomshardware.com,redirect=ga.js,important</code> 
<br/>or<br/>
<code>||www.google-analytics.com/ga.js$script,redirect=ga.js,important</code> 
<br/>or<br/>
<code>||www.google-analytics.com/ga.js$script,redirect=www.google-analytics.com/ga.js,important</code> 
<br/>or<br/>
<code>www.google-analytics.com/ga.js$script,domain=www.tomshardware.com,redirect=www.google-analytics.com/ga.js,important</code>
2. Open <code>tomshardware.com</code>
3. You will see ga.js is blocked and could see below rule fired from "My Filters" tab instead of redirecting..<br/> Checked dev console, and could not see any ga.js loaded..
   <code>||www.google-analytics.com/ga.js$domain=www.tomshardware.com,important,script</code>

#### Config
- W7, FF v42, uBlock Origin v1.3.7b5

**Comment by gorhill** [comment]
Redirection are not reported in the logger, the blocking is reported though. If you use the Networtk pane in the browser's dev tools, you should see the URL for `ga.js` is `data:[...]`.

**Comment by harshanvn** [comment]
I have checked in the network pane, and could not see it.
Here is the screenshot. I have added debugger pane, uBlock Origin popUp Window and redirect rule in the screenshot for your reference..

![ublock surrogate ga](https://cloud.githubusercontent.com/assets/779630/11442015/743bfefa-94df-11e5-8782-7068046d5bb1.png)

**Comment by gorhill** [comment]
As per screenshot, your rule is:

    ||www.google-analytics.com/ga.js$script,redirect=ga.js,important

There is no resource named `ga.js` in the redirection library. The proper token is `www.google-analytics.com/ga.js`. So the correct filter would be:

    ||www.google-analytics.com/ga.js$script,redirect=www.google-analytics.com/ga.js,important

**Comment by gorhill** [comment]
Also, by the way, currently you do not have to noop `google-analytics.com`, the redirection will take place if the resource is blocked, regardless of how it's blocked. The idea is that it's a completely neutered resource -- so even when "hard" blocking using dynamic filtering, there is no harm to fall back on a neutered resource.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@gorhill will users be able to create their own redirect resources or will there only be one list updated by you

**Comment by harshanvn** [comment]
> ||www.google-analytics.com/ga.js$script,redirect=www.google-analytics.com/ga.js,important

I have tried this one. But no luck. Not sure if i am messing something up. Please see the attached screenshot -
![ublock surrogate ga 1](https://cloud.githubusercontent.com/assets/779630/11442655/2fad4608-94e5-11e5-8169-5a9d8d8e51cf.png)

Can you try and show me screenshot of your network pane..

> Also, by the way, currently you do not have to noop google-analytics.com, the redirection will take place if the resource is blocked, regardless of how it's blocked.

Wow! Nice. I was wondering about the same, and thought i might have to tinker with my existing dynamic filtering rules. Good to know. :)

**Comment by gorhill** [comment]
Ok my bad, the Network pane in Firefox does show blocked/redirected network requests apparently.

In Firefox, best way to see redirection is to go to Debugger pane, and click `ga.js`, you should see uBO's code.

**Comment by harshanvn** [comment]
I have already checked there..but its not listed. Please see the below screenshot -
![ublock surrogate ga 2](https://cloud.githubusercontent.com/assets/779630/11443031/c2946ef4-94e7-11e5-8dba-09b10d4556da.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/11443210/23ca11aa-94e9-11e5-8371-d5a96b6ee2de.png)

**Comment by harshanvn** [comment]
Ok, Thanks. I will be away from system for around 2.2-5 hours. 
I will try later and report back.

**Comment by harshanvn** [comment]
##### Update:

Issued resolved, by restarting the browser. Weird!
However, i have tried to reproduce the issue by installing an old version (v1.3.6) and then updated to latest beta (b5) without restart. This time its working as expected.

So, closing it for now. Not sure what happened.
Sorry, for the trouble. Thanks my friend.
