### ISSUE TITLE
Video ad filter seems broken.

### ISSUE THREAD

**Issue by Scyris** [gorhill/uBlock#984]
On this page http://anilinkz.tv/taimadou-gakuen-35-shiken-shoutai-episode-6?src=3 last night, there was no thing about skipping a video ad, it went right to the epsiode I wanted to watch, today it makes me wait for a timer to go by with a blank videoscreen until I can hit "skip this add" to watch it, they did something on there that broken ublocks origin's blocking of these types of things it seems.

**Comment by gorhill** [comment]
Report to [EasyList maintainers](https://forums.lanik.us/viewforum.php?f=62) please.

**Comment by gorhill** [comment]
I got curious whether it was a difficult case, it's simple:

    ||video.api-exchange.com/tags/video.php$script,domain=anilinkz.tv

Please report solution to EasyList maintainers so that all benefit from it.
