### ISSUE TITLE
cannot load extension from ... must declare JSON Schema v3 version in $schema

### ISSUE THREAD

**Issue by kklepper** [gorhill/uBlock#985]
Hi, 

I followed the instructions for manual installation due to using Comodo Dragon. Next I failed with 

    cannot load extension from ... must declare JSON Schema v3 version in $schema

managed_storage.json shows:

    {
      "$schema": "http://json-schema.org/draft-03/schema",
      "type": "object",
      "properties": {
        "adminSettings": {
          "title": "A valid JSON string compliant with uBO's backup format.",
          "description": "All entries present will overwrite local settings.",
          "type": "string"
        }
      }
    }

What can I do?

Thanks.

**Comment by kklepper** [comment]
That's it. Thanks a lot. 

Also: 

    Beim Versuch, diese Erweiterung zu installieren, wurden Warnungen ausgegeben:
        Unrecognized manifest key 'options_ui'.
        Unrecognized manifest key 'short_name'.

BTW, just for the record: 

On an different machine, I had installed both Comodo Dragon and Chromodo (they cannot run both at the same time) along with Comodo Anitivrus. An update of the latter apparently deleted dragon.exe. So I tried a regular installation on Chromodo which went fine, whereas (my version of) Comodo Dragon cannot install from Google (your version is not supported by web store), hence my manual installation.

These days, we experience very nasty image ads on commercial magazine sites like spiegel.de which AdBlock plus cannot (or maybe will not) catch. uBlock can. Thanks a lot (this is the reason I looked for alternatives - the english Wikipedia gave the hint). These ads are regular jpg images from the site itself, probably injected by some Javascript code. Their style and content is awful, so it is even questionable if the honorable publishing companies want this to happen (which actually must be as the images are hosted on their site). Really mysterious.

**Comment by kklepper** [comment]
Sorry to say, I was wrong. There are ads in Chromodo as well. The same is true for Google Chrome. I activated the German filter list.

See http://www.spiegel.de/wissenschaft/mensch/venus-fund-auf-schwaebischer-alb-steinzeit-sexsymbol-betoert-forscher-a-624618.html 

In order to help you spot those ads, here are 3 cutouts from a screenshot in Chromodo, from top to bottom (you will get different ads each time, of course):

![googlechromead1](https://cloud.githubusercontent.com/assets/6130319/11939185/a1c2baea-a820-11e5-87b0-27f5ab8d7370.png)
![googlechromead2](https://cloud.githubusercontent.com/assets/6130319/11939187/a1c6897c-a820-11e5-8bd8-fc79309bc635.png)
![googlechromead3](https://cloud.githubusercontent.com/assets/6130319/11939186/a1c57cee-a820-11e5-9cbb-f725310c969a.png)

**Comment by gorhill** [comment]
Please, do not add unrelated issue to existing issues. See <https://github.com/gorhill/uBlock/issues/999>.
