### ISSUE TITLE
How remove the old custom 3rd-party filters?

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#986]
![old lists](https://cloud.githubusercontent.com/assets/13637587/11452596/39ba5280-95ee-11e5-9fe4-38ebff9fe3af.png)
I have three custom 3rd-party filters subscriptions, but now with the new I don't care about cookies filters the other are redundant and obsolete.
What is the way for remove these two from the list?
Thanks.

**Comment by gorhill** [comment]
Remove the corresponding entry in the text box where you added it in the first place.

**Comment by happysurf** [comment]
Sorry but I don't understand , both are off but the list name remain.

**Comment by gorhill** [comment]
How did you add these filter lists in the first place?

**Comment by happysurf** [comment]
1. Prebake: http://prebake.eu and then click on Subscribe  (abp:subscribe?location=https%3A%2F%2Fraw.github.com%2Fliamja%2FPrebake%2Fmaster%2Fobtrusive.txt&title=Prebake%20-%20Block%20obtrusive%20EU%20cookie%20notices)
2. https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web and then click on Block-EU-Cookie-Shit-List: (https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt?location=https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt&title=Block-EU-Cookie-Shit-List)

**Comment by gorhill** [comment]
https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/3rd-party-filters-custom.png

**Comment by happysurf** [comment]
OK, thank you very much!  :-)

**Comment by happysurf** [comment]
Any chance to add this list in UBO default filters?
