### ISSUE TITLE
uBlock Filters: more Addefend sites

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#987]
Hello,

there are a lot of websites that should be added to the following line in uBlocks filter list:

arcor.de,auto-motor-und-sport.de,boerse-online.de,echo-online.de,fem.com,finanzen.net,focus.de,gamestar.de,kabeleins.de,pcwelt.de,prosieben.de,prosiebenmaxx.de,rp-online.de,sat1.de,sat1gold.de,sixx.de,spiegel.de,the-voice-of-germany.de,tvspielfilm.de,wetter.com,wetteronline.de##script:contains(uabInject)

The following sites use the same Addefend ads:

ariva.de
main-spitze.de
wormser-zeitung.de
lampertheimer-zeitung.de
wiesbadener-tagblatt.de
buerstaedter-zeitung.de
wiesbadener-kurier.de
rhein-main-presse.de
allgemeine-zeitung.de
spox.com
shz.de
lustich.de
transfermarkt.de
motorradonline.de
20min.ch

**Comment by Betsy25** [comment]
I think a global **.de** might be better off than keep on adding german sites ad infinitum.

**Comment by gorhill** [comment]
I could not see any of these self-defacement ads on the following sites, so I did not add them:

    4wheelfun.de
    autostrassenverkehr.de
    computerbild.de
    itectale.de
    lustich.de
    motor-klassik.de
    sportauto.de
    stern.de
    transfermarkt.de

**Comment by TonyTough** [comment]
Hello,
thanks.

I edited my post a few minutes after posting and deleted some sites. They were from Reek's script.

transfermarkt.de
uses the ads on some subsites i.e.:
http://www.transfermarkt.de/hsv-gewinnt-nord-derby-ndash-hannover-mit-befreiungsschlag/view/news/218743

and
lustich.de
has no ad at the top, but on the right side.

**Comment by gorhill** [comment]
Ok, `transfermarkt.de` and `lustich.de` confirmed, I added them.

**Comment by gorhill** [comment]
Any reason why a rule like `@@/ad_bomb/*$image,domain=de` is not used for these sites to foil these self-defacement ads?
