### ISSUE TITLE
Pop unders

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#99]
Not sure if this is a browser issue, a uBlock₀ issue, or if there's anything that can be done to solve/work around this.

OS: Arch Linux x86_64
Browser: Firefox 37.0.1
uBlock₀ version: 0.9.4.6/latest git master (e16dac)  
uBlock₀ settings are default, nothing has been modified, no extra filter lists, no custom rules, except pop-ups are blocked for pornhub.com (`no-popups: pornhub.com true`)

Here's a short minute and a half video/screen recording of the issue being reproduced: http://a.pomf.se/odgapf.mp4 (warning, NSFW)

Steps to reproduce:
1. Add `no-popups: pornhub.com true` under My Rules 
2. Clear browser cache/cookies/etc
3. Navigate to pornhub.com
4. Click on categories

The pop under is opened, and the current/destination tab is closed. This should be the other way around.
When pop ups are allowed for pornhub.com, the pop under opens in a background tab, leaving your browser tab focus on the current one/your destination (also NSFW: http://a.pomf.se/bfiiqy.mp4).

Not issue related, but thanks for all of your hard work.

**Comment by kurtextrem** [comment]
I can confirm that, I noticed that too.

**Comment by forkoz** [comment]
this is also an issue on primewire.ag recently, in adblock too.  switched the htpc to ublock trying to combat this to no avail. 

domain blocking the ad servers leads to images being blocked and getting a page of text.
blocking all popups for primewire.ag causes the ad to open in a new tab or even in the current window. blocking scripts fixes popups but breaks sorting.

**Comment by flyingzebras** [comment]
See also
* https://forums.lanik.us/viewtopic.php?f=62&t=22848&p=77727
* https://issues.adblockplus.org/ticket/2095

**Comment by flyingzebras** [comment]
Fixed in uBlock Origin 1.2.1. See https://github.com/gorhill/uBlock/issues/795 for example.

**Comment by flyingzebras** [comment]
@gorhill Can you please close this issue?
