### ISSUE TITLE
uBlock "Advanced-Popunder" Filter

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#991]
New filter for "uBlock filters":
||ebocornac.com^
It's present in hpHosts’ Ad and tracking servers, Malvertising filter list by Disconnect, Peter Lowe’s Ad server list and MVPS HOSTS meaning it's not blocked in the default configuration.
It originates from pornhub.com (NSFW). In fact I believe they set this domain up exclusively for Pornhub. They use a technique where the actual popunder is loaded on the original tab and the video you clicked on is opened in a new one. This way most Ad/popup-blockers can't block it. They also don't use any (external) scripts for this; it's in every pages source code.
uBlock however can block this using a strict rule like the one above and thanks to it's ability to entirely block pages from loading.
To test this filter visit pornhub.com and click on a video thumbnail.

**Comment by gorhill** [comment]
> meaning it's not blocked in the default configuration

Peter Lowe's is enabled in default configuration, so yes `ebocornac.com` is blocked by default.

The popunder is properly blocked in Firefox. In Chromium, it is not because it [does not yet support `beforescriptexecute` event](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering).

**Comment by IDKwhattoputhere** [comment]
Oh, didn't remember Peter Lowe's was default.

It actually works for me in Chrome 46.0.2490.86 
![2015-11-29_19-16-48](https://cloud.githubusercontent.com/assets/16030872/11459076/69fae3f2-96ce-11e5-8ea8-dbb8d171ef68.png)

**Comment by gorhill** [comment]
> Is this like blocking scripts that are created "on the fly"?

I don't understand the question.

The screenshot you posted is a whole page being blocked as per [strict blocking](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking). The With the Firefox version of uBO, that page won't even come up, because the inline script tag responsible to create it is prevented from executing using an [inline script tag filter](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering).

**Comment by IDKwhattoputhere** [comment]
Ok, I get it now. Let's hope they add support for it in the future.

**Comment by gorhill** [comment]
Related: #99.

**Comment by gorhill** [comment]
Fix in latest dev build, see if this works for you.

**Comment by gorhill** [comment]
Works well for Chromium, but not for Firefox -- tab management on Firefox has always been more flaky.

**Comment by IDKwhattoputhere** [comment]
Seems to work perfectly with that build. Thanks so much for this. Sadly you don't accept donations. ;)
