### ISSUE TITLE
VIsual corruption of uBlock third party filter screen

### ISSUE THREAD

**Issue by vgturtle127** [gorhill/uBlock#992]
When I scroll through the filters I get visual corruption which appears to be zoomed in versions of the page, various characters in place of letters, and white space. I have included some screenshots:

![screenshot 4](https://cloud.githubusercontent.com/assets/3183676/11463524/8cba21e0-96e8-11e5-9aa6-eada8c5b2d4d.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/3183676/11463521/8cb76f68-96e8-11e5-8273-a09970a13e83.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/3183676/11463523/8cb9784e-96e8-11e5-82a4-bc27e1f056a5.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/3183676/11463525/8cbbe516-96e8-11e5-9d20-cd22bfa8baae.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/3183676/11463522/8cb90a6c-96e8-11e5-8371-d3444d36c757.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/3183676/11463520/8cb793a8-96e8-11e5-987a-94e53c2b1b03.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/3183676/11463530/8cc86c32-96e8-11e5-9f6c-6baea9e3785c.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/3183676/11463526/8cc4ef62-96e8-11e5-8b43-e2282ea16cd9.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/3183676/11463529/8cc75ebe-96e8-11e5-8445-b519b8f7fc6f.png)
![screenshot 13](https://cloud.githubusercontent.com/assets/3183676/11463527/8cc5ee44-96e8-11e5-8a55-8888baa7dc1b.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/3183676/11463528/8cc6983a-96e8-11e5-863e-9e2ca68b48d5.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/3183676/11463531/8cc8cbdc-96e8-11e5-93d8-695999c1b7e6.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/3183676/11463533/8cd3d306-96e8-11e5-94c5-9f19a9d09c3b.png)
![screenshot 17](https://cloud.githubusercontent.com/assets/3183676/11463532/8cd2338e-96e8-11e5-81ff-ebc5811c5d44.png)

**Comment by gorhill** [comment]
The dashboard is just plain HTML/CS/JS -- your symptoms are way beyond a uBlock Issue. Please file an issue with the browser.

**Comment by vgturtle127** [comment]
Alright, thanks Gorhill.
