### ISSUE TITLE
Tisoomi - Anti-Adblock similar to Ad-Defend

### ISSUE THREAD

**Issue by TonyTough** [gorhill/uBlock#993]
Hello,

the following sites are using a script and inject ads on the top and on the right side.
The ads look like Ad-Defend, but they are from Tisoomi:

rechtslupe.de
motorsport-total.com
infranken.de
autozeitung.de
formel1.de
fremdwort.de
inside-handy.de
podcast.de
getvids.de
spielespielen24.de (ads on subsites)

Maybe a filter like that for Ad-Defend (i.e. rp-online.de) could be added in ublocks own filterlist?

**Comment by gorhill** [comment]
Checked a couple of them and I don't see anything. here is how it will work: Report to EasyList Germany maintainers.

_If_ they can't fix it because of limitations to Adblock Plus, _then_ I will look into it.

**Comment by TonyTough** [comment]
Hello,

it was already reported to Easylist German forums, but with no final success, here is the link:
https://forums.lanik.us/viewtopic.php?f=90&t=22867

I have made screenshots from the first 3 sites:
http://postimg.org/image/jzbsbfnq3/
http://postimg.org/image/cmwjkc4wx/
http://postimg.org/image/3msju7umz/

In ublock origin I have activated all standard filters + EasylistGermany + Reek's filter.

I posted it also on Reek's github site, where "yoshimo" posted an edited script, but I don't know if this works.
https://github.com/reek/anti-adblock-killer/issues/793

**Comment by TonyTough** [comment]
Hi,

Reek has further investigated this case and found out the following:

"This anti-adblock seems to work only when one has a German IP,
In effect adds advertisements when adblocker is detected instead of a message.
I may be found a generic solution, I'm going to do some testing and I would test you"

**Comment by gorhill** [comment]
I could reproduce with a VPN.

One was not dependant on inline scripts, so I will leave it to the filter list manitainers: `infranken.de`.

**Comment by TonyTough** [comment]
Hi,

a BIG thank you!

I have 4 more sites to add, where your filter ##script:contains(window.tisoomi)
seems to work:

aussenwirtschaftslupe.de
http://postimg.org/image/pocrtee97/
donnerwetter.de
http://postimg.org/image/n3dfqopwz/
wintotal.de
http://postimg.org/image/w21cd998p/

On this site it seems not to work, although "tisoomi" is in the source code:
dialo.de
http://postimg.org/image/s4j2xyqrx/


And finally for ##script:contains(uabInject)
1erforum.de

Thanks again,
I will report infranken.de to Easylist German forum.

**Comment by gorhill** [comment]
Added.

Blocking 1st-party js for `dialo.de` prevents the ads -- so it's something the filter list maintainers can fix.

**Comment by TonyTough** [comment]
Thanks again,

I have reported dialo.de to Easylist Germany forum.
