### ISSUE TITLE
Suggestion: A public forum for uBlock users.

### ISSUE THREAD

**Issue by antdude** [gorhill/uBlock#994]
Especially for newbies. ;)

**Comment by gorhill** [comment]
I do not have the time and skills to deal with maintaining a forum. It's best that I stick to coding and if whoever believe it would be worth to have some forums somewhere is free to go ahead -- it does not have to be me.

**Comment by antdude** [comment]
Ah bummer. Yeah, someone should start it. Not me since I am a newbie. ;)

**Comment by CrisBRM** [comment]
There's plebbit for that already, and Mozilla's uB0's support section.

**Comment by antdude** [comment]
Thanks. I found Reddit's, but where's Mozilla's at?

**Comment by CrisBRM** [comment]
Ah, nevermind. It was for [uMatrix](https://discourse.mozilla-community.org/t/support-umatrix/5131).

**Comment by antdude** [comment]
CrisBRM: Interesting. That could be useful how to use it even after reading UO's wikis.

**Comment by harshanvn** [comment]
You can ask your questions <a href="http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/">here too!</a>
