### ISSUE TITLE
Block a popup in xHamster.com

### ISSUE THREAD

**Issue by LoreJon** [gorhill/uBlock#995]
http://xhamster.com/

When selecting a category, you get a popup page.
Can you please block it?

Thanks.

**Comment by gorhill** [comment]
3rd-party filter list issue: <https://forums.lanik.us/viewforum.php?f=62>.

**Comment by LoreJon** [comment]
Thanks.

**Comment by gorhill** [comment]
For systematic reproduction of the issue, the cookies must be cleared -- as the site won't try to create a popunder if a certain cookie is present.

**Comment by gorhill** [comment]
Duplicate of #991.

**Comment by LoreJon** [comment]
Thanks.
https://forums.lanik.us/viewtopic.php?p=81288&sid=85f369e4ff86af12dd67e6a8dd0579a9#p81288
