### ISSUE TITLE
DOM white list rule is invild too

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#998]
eg: tieba.baidu.com#@#div.card_banner

**Comment by gorhill** [comment]
It's a valid exception cosmetic filter. What is the issue exactly?

Keep in mind that as per ABP-filter syntax semantic, an exception cosmetic filter (aka "element hiding" filter) must match exactly the corresponding block cosmetic filter to have any effect. This means that with...

Filters:

    ###toto
    #@#div.card_banner

And:

    <div id="toto" class="card_banner">
      [...]
    </div>

The exception filter will not work. Only these filters will work:

    ###toto
    #@##toto

**Comment by lewisje** [comment]
> as per ABP-filter syntax semantic, an exception cosmetic filter (aka "element hiding" filter) must match *exactly* the corresponding block cosmetic filter to have any effect,

I was wondering how ABP decides that a certain element matches a hiding-exception filter and ensures that hiding filters don't hide it; I didn't realize that it *doesn't* do that.

**Comment by gorhill** [comment]
No feedback for days now -- unclear what the issue was. Reopen if whatever issue there was is still there with more details for me to understand what it that issue.

**Comment by xinggsf** [comment]
I see.
